### ISSUE TITLE
CHPL_{TASKS,THREADS}_MODEL_H are problematic

### ISSUE THREAD

**Issue by gbtitus** [chapel-lang/chapel#10004]
### Summary of Problem

The implementation-specific .h files for the runtime tasking and threading layers are named after those specific layers.  For example, for `CHPL_TASKS=qthreads` the internal runtime .h file is `runtime/include/tasks/qthreads/tasks-qthreads.h`.  The general .h file for tasking as a whole, `runtime/include/chpl-tasks.h`, has to `#include` the implementation-specific .h file but cannot name it directly because its filename depends on which implementation is configured.  Our solution to this, long ago, was to define a preprocessor variable in the runtime `Makefile`:

```
... -DCHPL_TASKS_MODEL_H=\"tasks-$(CHPL_MAKE_TASKS).h\" ...
```

and then do `#include CHPL_TASKS_MODEL_H` in `chpl-tasks.h` and other places that we need this variably-named .h file.  We do a similar thing with the threading implementation and `CHPL_THREADS_MODEL_H`.

This has always been fragile.  The double-quotes around the include file name have to be included in the preprocessor variable's value because otherwise the way the `#include` directive is dealt with is implementation-defined, according to the C standard, and if memory serves we had portability problems if we didn't do it that way.  Alas, this exposes the double-quotes to danger, such as for example being stripped if the setting in the `Makefile` somehow ends up getting passed through a shell.  Trouble ensues when this happens, obviously.

For the comm layers we took another approach, which was to give the implementation-specific .h file the same fixed name in all cases and differentiate one from another just based on position in the hierarchy, such as `runtime/include/comm/gasnet/chpl-comm-impl.h`.

The task here is to rename the implementation-specific tasking and threading .h files using the comm layer approach, removing the need for the problematic `CHPL_{TASKS,THREADS}_MODEL_H` preprocessor variables.

**Comment by lydia-duncan** [comment]
Noting for posterity, this issue causes portability problems when using Cython in our Python interoperability story on a Cray.  I'm not sure why I don't have this problem on my OSX laptop.
