### ISSUE TITLE
precedence of unmanaged / borrowed

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#10012]
Currently the following program does not parse:
``` chapel
class MyClass { var x:int; }

proc printType(type t) {
  writeln(t:string);
}

proc type MyClass.typemethod() type {
  return MyClass;
}

unmanaged MyClass.typemethod();
```

This relates also to a precedence question. Is `type x = unmanaged MyClass.typemethod();` to be parsed as `type x = unmanaged (MyClass.typemethod())` or as `type x = (unmanaged MyClass).typemethod())` ? Consider for example the following program which will have different output depending on this choice:

``` chapel
class MyClass { var x:int; }

proc printType(type t) {
  writeln(t:string);
}

proc type (unmanaged MyClass).typemethod() type {
  return int;
}

proc type MyClass.typemethod() type {
  return MyClass;
}

type t = unmanaged MyClass.typemethod();
writeln(t:string);
type t1 = (unmanaged MyClass).typemethod();
writeln(t1:string);
type t2 = unmanaged (MyClass.typemethod());
writeln(t2:string);
```

The output of this program indicates that `unmanaged MyClass.typemethod()` is currently interpreted to be the same as `unmanaged (MyClass.typemethod())` which isn't necessarily what we want.

- [ ] possibly remove parentheses in test/classes/deitz/class-constructor/constructor_disambiguity.chpl once this is resolved

**Comment by psahabu** [comment]
I prefer the `type x = unmanaged (MyClass.typemethod())` interpretation, since type methods should be on the underlying type whereas `unmanaged` etc. is more like a modifier on it.

**Comment by mppf** [comment]
But I can (and did) make a type method on `unmanaged MyClass`...

**Comment by psahabu** [comment]
Right, I just mean as a default interpretation.

**Comment by BryantLam** [comment]
Suggestion: The dot operator should bind with higher precedence when parentheses are omitted (the current program should be correct). The rationale is that it's less confusing versus the alternative of having whitespace binding with higher precedence. In most cases, we should encourage users to simply add parentheses to clarify intent.

**Comment by mppf** [comment]
We considered the precedence of delete-free features in #13482 and I'm satisfied with the result. At this point, I don't think we should move `unmanaged` to have higher precedence than `.` . Other commenters on this issue seemed to agree, so I'm closing this one.
