### ISSUE TITLE
Should we support coercions from owned to shared?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#10013]
Suppose I have an `owned` variable. How can I write a coercion to make it into a `shared` type?

~~What about an `unmanaged` variable that now I'd like to convert into `owned`?~~

~~The previous Owned/Shared strategy included constructors for this purpose, e.g. `var x = new Owned(myUnamangedClass)` or `var y = new Shared(myOwnedClass)`. However we now call these types `owned` and `shared` so this constructor approach probably isn't what we want.~~

Additionally we could consider allowing coercion from owned to shared on a method call, e.g.:

``` chapel
class MyClass { var x:int; }
proc f(arg:shared MyClass) { }

var myOwned = new owned MyClass();
f(myOwned); // transfer ownership to f
```

Such a conversion might simplify code using the datetime interface, where the fact that the timezone field is shared isn't as fundamental as the fact that the by constructing a datetime with a timezone, you pass responsibility for freeing it to the datetime. Of course the datetime initializer could have a version accepting an owned timezone, but should such library authors have to do that?

~~This question is also interesting when considering the case that `nil` is the original value desired, and maybe it should coerce to `shared`.~~

**Comment by psahabu** [comment]
The two syntaxes that pop in my head are:
```chapel
var x = new unmanaged MyClass();
var y = x: owned MyClass;
```
and
```chapel
var x = new unmanaged MyClass();
var y = x: owned;
```
This would mirror the proposed method call coercion, which I support.

**Comment by mppf** [comment]
Also casting to unmanaged:
``` chapel
var x = ... something borrow type ...;
var y = x:unmanaged;
```

Note this should probably fail with an error if x is of record type.

**Comment by mppf** [comment]
Besides the cast, `new owned(myUnmangedVar)` and `new owned myUnmanagedVar` are currently working. These seem at least as reasonable as the cast to me.

**Comment by mppf** [comment]
In later work, we removed the `new owned(myUnmanagedVar)` and now this needs to be done with a cast or with `create`.

**Comment by mppf** [comment]
Based on other discussions, I don't think we'll want to add implicit conversions from owned to shared, and the other elements of this issue were resolved with `shared.create` or with casts. So I am closing this issue.
