### ISSUE TITLE
Disable enum->int casts when enums are lacking associated values

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#10026]
As a Chapel programmer, I don't want my enums to cast to ints if I haven't associated values with them in order to support the concept of a truly abstract enum type while also avoiding assumptions about whether enums use 0- or 1-based numbering by default.

Acceptance criteria:
* enum->int casts are only supported for those enum symbols that have associated integer values

**Comment by cassella** [comment]
Is it interesting if only some of the enum's values have associated integer values?

```chapel
enum entities { stars, planets = 9 }; // stars without number
```

**Comment by bradcray** [comment]
Definitely interesting.  Current plan / approach is to support the cast from `entities` to integers, but to generate an error if someone tries to cast `stars` to an integer (hopefully compile-time for a param / compile-time cast and execution-time for a const / var cast).

The main alternative I've considered is to count down from the first initializer for such cases, but (a) this seems like a lot of work that the user could have avoided with a tiny bit of effort (and maybe the user wanted a non-int error-case enum in their list? and (b) it also seems like it could lead to confusion or disagreements about what should happen for a case like:

```
enum color {red, orange=1, green, blue=4, violet};
```

My hypothesis is that the common / important cases will be (a) enums have no values, (b) first enum has a value, the rest inherit from there, (c) every enum has a value.
