### ISSUE TITLE
Spike: Investigate alternative sparse formats for arbitrary sparse domains

### ISSUE THREAD

**Issue by ian-bertolacci** [chapel-lang/chapel#10038]
From what I understand, sparse domains are in COO, which isn't as efficient as we want. Ideally we'd use CSR. Currently if you want to use CSR, you have to use LayoutCS which is restricted to 2-dimensional arrays.

In this spike I would look at possible alternatives for CSR (or CSR-like) representations.

**Comment by ben-albrecht** [comment]
Open question: Should there be a default sparse format? Every format has advantages and disadvantages. Should we require users to explicitly specify the format, rather than be surprised when a certain operation is slower than they expected?

This would follow the convention of many other sparse libraries, including Python's `scipy.sparse`.

I'm not sure how I feel about it, but thought it's worth considering.

**Comment by bradcray** [comment]
> Should there be a default sparse format?

I think strongly "yes" for the same reason that we don't require users to explicitly dmap their dense arrays to row-major vs. column-major vs. whatever storage format:  productivity.

**Comment by ian-bertolacci** [comment]
I agree with a default sparse format, probably dense-major sparse-minor(s) format.

One of the things influencing my thinking and driving interest in this is the [tensor compiler](http://tensor-compiler.org/), where you essentially label a dimension as sparse or dense, which is very simple to grasp, and can encompass entire families of sparse formats. This work also has some really impactful methods for merging iterations over operations between latices and their results (i.e. zippered iteration).

**Comment by ben-albrecht** [comment]
> I think strongly "yes" for the same reason that we don't require users to explicitly dmap their dense arrays to row-major vs. column-major vs. whatever storage format: productivity.

I agree, but want to note that performance characteristics are much more diverse across sparse layouts than dense layouts, so I don't think it's an apples to apples comparison.

Another thing `scipy` does is throw warnings when doing an inefficient operation on a sparse array. That's one mechanism for keeping users aware of the performance tradeoffs, especially when there is a default sparse array format being used. This can probably be split off into a separate issue and discussed at a later point.
