### ISSUE TITLE
Allow extern proc renaming to take a param string

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#10053]
We support renaming of extern procs so that a different function name is available to Chapel code. e.g. 

```chpl
extern "foo_in_c" proc foo_in_chapel(): c_int;
writeln(foo_in_chapel()); // will generate a call to foo_in_c
```

Today, the external name must be a string literal, since it's substituted in at parse time. It'd be nice to allow this to be a param string instead. This would allow us to compute external names based on types and other sorts of things, which would be really beneficial for cleaning up things like our Atomics implementation.

Since our runtime support for atomics is in C, we have to embed the type name in the function. So even though Chapel supports generics and overloads, today we create nearly identical records for each type just so that we can call unique C routines. So for each type currently we have something like:

```chpl
extern proc atomic_fetch_add_explicit_int_least64_t(ref obj:atomic_int_least64_t, operand:int(64), order:memory_order):int(64);
inline proc add(value:int(64), order:memory_order = memory_order_seq_cst):void {
  on this do atomic_fetch_add_explicit_int_least64_t(_v, value, order);
}

// repeated ~10 times for the other types
```

We could instead just have one generic record (or really 1 for integral, 1 for real, and 1 for bool) with something like:

```chpl
proc externType type { return _v.type; }
proc plainChplType type {
  if externType == atomic_int_least64_t then return int(64);
  /* other types ... */
}
proc cFuncSuffix() param {
  if externType == atomic_int_least64_t then return "int_least64_t";
  /* other types ... */
}

inline proc add(value:plainChplType, order:memory_order = memory_order_seq_cst): void {
  extern "atomic_fetch_add_explicit_"+cFuncSuffix()  /* param renaming */
    proc atomic_add(ref obj:externType, operand:plainChplType, order:memory_order):plainChplType;
  on this do atomic_add(_v, value, order);
}
```

**Comment by bradcray** [comment]
I really like this idea and had been musing about it with @ian-bertolacci earlier this week completely independent of Elliot's use-case.
