### ISSUE TITLE
proposal to replace : in where clauses

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#10060]
Historically, the Chapel compiler has changed `A:B` in where clauses to mean to query whether A is a subtype of B (where here subtype also includes instantiation, in case B is generic).

This issue proposes changing that behavior:
 * `:` in where clauses would mean a cast, just like in other execution contexts
 * a new included-by-default `proc` will allow the previous query
 * the new `proc` is a function taking two types and returning a param bool
 * the new proc can be called in where clauses and also outside of where clauses

The main question I have is whether conceptually we should refer to such a query as checking if A is a subtype of B or if it should be checking if A is convertible to B (or coercible). According to the [Wikipedia page on subtyping](https://en.wikipedia.org/wiki/Subtyping), there is an idea of an *inclusive* subtype vs a *coercive* one. In Chapel, if B is a parent class to A, then a variable of type A is inherently also a B (this is *inclusive*). But `int(8)` can only convert to `int(64)` as a new value (and so this is *coercive*). But my point here is that we *could* use the terminology of just *subtype* to refer to both situations.

The closest previous work I can find is C++ type traits. They have `is_convertible` (which is the closest to the present question) as well as several other related queries like `is_constructable` and `is_assignable`.

I'm proposing that `isSubtype` be the name of the new function, and that `isSubtype(A,B)` can return `true` in all of these cases:
 * `A` is the same type as `B`
 * `A` is a class type that inherits from `B`
 * `A` is a generic instantiation of `B`
 * `A` is coercible to `B`.

(Relates to #10019).

**Comment by bradcray** [comment]
Since my eyes were recently opened, I'm a huge supporter of ceasing to treat `:` specially in where clauses.  A few notes:

> just like anywhere else

I think this should read "just like in other execution contexts" (since, in declaration contexts, they're less casts and more type specifiers / constraints).

If I were implementing this, I'd see how far we could push things without relying on a new procedure that does what `:` does currently.  E.g., if I found code like `x:integral`, I'd change to `isIntValue(x)` rather than `isSubType(x, integral)`.  In some cases, this will probably mean needing to understand what the function is trying to constrain rather than applying a global query-replace.  My pipe dream would be that no `isSubtype()` predicate would be required.  More realistically, I'd hope that it would only be required in a relatively small number of places which might illuminate what it should mean.

**Comment by mppf** [comment]
I still like `isSubtype` but I wanted to point out there might be some reason to use `isCoercible` to be harmonious with our intended direction for user-defined coercions in #5054. However if you take the viewpoint that coercibility is a kind of subtype, I don't think this is too big of a deal.

**Comment by mppf** [comment]
@vasslitvinov @benharsh @psahabu - care to comment on this issue about removing special behavior for `:` in where clauses?

**Comment by mppf** [comment]
I also think `<:` or `<=` on types might be interesting. I'm not sure if the use of `isSubtype` would be common enough to justify using a punctuation-based operator, though.

**Comment by benharsh** [comment]
I share Brad's interest in seeing how many ``:`` we can convert to use existing ``is*`` functions.

I'm OK with ``isSubtype`` for now, but eventually would like to see some operators that could be used on types.

Does ``:`` already return true for coercability?

**Comment by mppf** [comment]
> Does ``:`` already return true for coercability?

No, but I'm proposing that `isSubtype` would.

**Comment by mppf** [comment]
> I'm OK with ``isSubtype`` for now, but eventually would like to see some operators that could be used on types.

Do you know what these would be? Why are operators important in this context?

**Comment by benharsh** [comment]
> Do you know what these would be? Why are operators important in this context?

I think this is a matter of personal taste. I'd rather write something like ``A.type <= B.type`` than ``isSubtype(A, B)``. I don't have a particular proposal for operators at the moment, I just think we shouldn't stop at ``isSubtype`` and should look for something more elegant (again, perhaps just my personal taste).

**Comment by psahabu** [comment]
I agree with @benharsh, I have a slight preference for `A.type <= B.type` to say "the type of A is a subtype of the type of B". This comes out of the formal mathematical representation `<:`, which Scala also uses.

I'm good with `isSubtype(A, B)` being used as a placeholder in the meantime, though.

**Comment by mppf** [comment]
If we all like `A.type <= B.type` I don't see any reason not to implement that directly. I'm certainly OK with it.

**Comment by mppf** [comment]
I've learned about a variety of situations in which isSubtype seems to be needed. One issue is that if the parent type is generic, a straightforward type method doesn't work (because the compiler insists that the actuals are concrete). Primitives don't have this problem.

**Comment by mppf** [comment]
I'm converting tests away from : in where clauses. I did find one that was trying to use the : as a cast: users/thom/domCapture.chpl.

**Comment by mppf** [comment]
In terms of whether or not `isSubtype` or `<=` allows for coercions, this question for me seems a little bit connected to #7779, where we decided coercions did not apply to arguments like `proc f(type t:someType)`. 

I still think `isSubtype` should allow coercions though, because I think coercibility is a kind of subtype. We might need other queries in the future though.

**Comment by mppf** [comment]
amax in BLAS.chpl package module also was trying to use `:` as a cast.

**Comment by mppf** [comment]
At this point the proposal is implemented, along with comparison operators, so I'm closing this issue.
