### ISSUE TITLE
Compiler segfaults when incorrectly forwarding to self

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#10063]
### Summary of Problem
Compiler segfaults when a class forwards to itself. Note that the compilation succeeds if the code in `main` is removed but the self-forwarded class remains (probably because it doesn't get instantiated or simply optimized out).

### Steps to Reproduce

**Source Code:**

```chapel
module ForwardtoSelf {
class A {
  forwarding var data: A;
}
proc main() {
  var a = new A();
  delete a;
}
} // end module ForwardtoSelf
```

### Configuration Information
`chpl version 1.18.0 pre-release (b0251ba45e)`

**Comment by cassella** [comment]
There's also a segfault if the forwarding forms a cycle:

```chapel
class A {
  forwarding var data: B;
}
class B {
  forwarding var data: A;
}
```

(with the rest of the module unchanged.)
