### ISSUE TITLE
Read from HDF5 to a distributed array in a scalable way

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#10070]
As a Chapel programmer, I'd like to be able to read data from an HDF5 file to a distributed array in a way that scales (though it need not be optimal) because that way I can work on large data sets without an inherent scalability bottleneck.  Specifically, the approach should avoid reading the data in on one locale and then copying it to other locales (because that may use too much memory or make the one locale a bottleneck).  I'd expect each locale to query what indices it owns using the "local subdomain" interface, to scan to the appropriate part(s) of the file, and to read the corresponding data into the chunk(s) it owns.

Acceptance criteria
* I have some means of reading from HDF5 into a distributed array

**Comment by bradcray** [comment]
For this initial task, choosing a specific distributed array (e.g., Block) is fine.  The ultimate implementation should work for any distribution that implements the "local subdomain" interface (and bonus points for getting that version done first).  I think there are also design questions related to whether this routine should generate the distributed array from scratch, or whether the user should pass in a distributed array that they want to read into.  For this initial task, I'm more interested in the capability than the final design.

**Comment by daviditen** [comment]
PR #10422 adds a function to read a dataset into a `Block` or `Cyclic` distributed array with each locale reading its local portion in parallel with the other locales.  It doesn't currently support BlockCyclic because it expects the blocks yielded by the `localSubdomains()` iterator to be dense in memory, but this is not the case for `BlockCyclic`.

**Comment by daviditen** [comment]
Closed with PR #10422.
