### ISSUE TITLE
Failure initializing from a type variable in a class.

### ISSUE THREAD

**Issue by npadmana** [chapel-lang/chapel#10100]
### Summary of Problem
Attempting to initialize from a type variable inside a class fails. 

### Steps to Reproduce

**Source Code:**

The following code fails to compile 
```chapel
/*
  This fails.
*/
class A {
  proc init(i :int) {
  }
}

class B {
  type t = A;
  var x : t;
  proc init() {
    x = new t(2);
  }
}

var a = new A(2);
var b = new B();
```
with the error message --
```
bug-1.chpl:12: In initializer:
bug-1.chpl:13: error: unresolved call 'A(2)'
```

Note that, if ``A`` had no parameters in its initializer, then it compiles just fine --
```chapel
class A {
  proc init() {
  }
}

class B {
  type t = A;
  var x : t;
  proc init() {
    x = new t;
  }
}

var b = new B();
```

Or if the type parameter was not in a class, this works as well...
```chapel
/*
  This works.
*/
class A {
  proc init(i :int) {
  }
}

type t = A;
var a = new t(2);
```

### Configuration
```chpl version 1.18.0 pre-release (b67cf3a)```

Thanks to @LouisJenkinsCS  and @e-kayrakli for exploring some of these variants.

**Comment by cassella** [comment]
If I change `x` to be pure generic, I get an internal error:

```chapel
/*
  This fails.
*/
class A {
  proc init(i :int) {
  }
}

class B {
  type t = A;
  var x ;
  proc init() {
    x = new t(2);
  }
}

var a = new A(2);
var b = new B();
```

```
initA.chpl:12: In initializer:
initA.chpl:13: internal error: the type of the actual argument 'this' is generic [callInfo.cpp:124]
```

It compiles if the expression is `x = new A(2);`.

**Comment by cassella** [comment]
@benharsh Are you tracking the "pure generic" failure separately?  The version I posted above with just `var x;` still hits the same internal error even after that PR.  I don't see an issue for it.
