### ISSUE TITLE
StencilDist : Error computing destination slice -- issue with periodic on the same slice

### ISSUE THREAD

**Issue by npadmana** [chapel-lang/chapel#10113]
### Summary of Problem
StencilDist fails with "Error computing destination slice" on this slab-decomposed array. I believe this 
error occurs when periodic is selected as the ghost elements are on the same locale.

### Steps to Reproduce

**Source Code:**

```chapel
use StencilDist;

// How to set up the target locales
config const Ng=4;
const Dom = {0.. #Ng, 0.. #Ng, 0.. #Ng};
var targets : [0.. #numLocales, 0..0, 0..0] locale;
targets[..,0,0] = Locales;

const Space : domain(3) dmapped Stencil(Dom,targetLocales=targets,  
                                        fluff=(0,0,1), periodic=true) = Dom;
```

**Compile command:**
`chpl bug1.chpl`

**Execution command:**
`./bug1 --nl 2`

This fails with -- 
```
bug1.chpl:9: error: assert failed - StencilDist: Error computing destination slice.
```

### Configuration Information
```
chpl version 1.18.0 pre-release (b67cf3a)
```

**Comment by npadmana** [comment]
@benharsh -- this might be of interest to you....

**Comment by npadmana** [comment]
This looks like my bug --- you cannot use `periodic` without `fluff`. I'm happy to close this (or we could just put in an assertion in the code that fails if `periodic` is set without `fluff`). 

This does bring up a possible feature request -- `periodic` should allow for periodic/non-periodic boundary conditions to be set along each dimension separately. If you agree, I can file that as a separate issue.

**Comment by benharsh** [comment]
Adding a check sounds good to me.
