### ISSUE TITLE
Should Chapel permit functions and variables with the same name at the same scope?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#10110]
Consider the code:

```chapel
proc foo() { ... }
var foo = ...;
```

Should this be legal Chapel or not?  (Today it generates the error message "`foo` has multiple definitions; redefined at: <location>")

Argument for:
* Chapel permits paren-ful and paren-less overloads of a function to be defined at the same scope and a variable could be considered similar to a paren-less function.

Arguments against:
* We tend to be a single namespace language (i.e., we don't think of there as being a "variable namespace" and a "function namespace")
* In the "argument for" above, the paren-less function always wins, making the paren-ful function pointless; if we were to do the same for variables, it's likely just to add confusion rather than clarity to users (and arguably we might want to do the same for the overloads of paren-ful and paren-less functions cases...)

**Comment by ian-bertolacci** [comment]
I think it should not be allowed, as it would make calling `this` on objects with parameters confusing.
For example, what would the following code print?
```chpl
class Bar {
  proc this( x ){
     return x + 1234;
  }
}

proc foo( x ) {
  return x - 9876;
}

var foo = new Bar();
writeln( foo( 0 ) );
```

**Comment by bradcray** [comment]
Ian: I don't think it should be allowed either, but if it were, arguably your example would do the same thing that it would do if `Bar()` supported two overloads of foo(), one which took parenthesis and the other which did not:  Print out `1234`:

```chapel
class Bar {
  proc this( x ){
     return x + 1234;
  }

  proc foo (x) {
    return x - 9876;
  }

  proc foo {
    return new Bar();
  }
}

var foo = new Bar();
writeln( foo.foo( 0 ) );
```

**Comment by gbtitus** [comment]
In the past we've talked about programmers being able to go back and forth easily between struct-of-arrays and array-of-structs implementations for `array(idx).member` style coding, by implementing `array()` as either a variable (an actual array) or a function.  Would permitting functions and variables with the same name at the same scope impact this ease-of-use argument?

**Comment by bradcray** [comment]
> Would permitting functions and variables with the same name at the same scope impact this ease-of-use argument?

I don't think so because presumably it would be ambiguous which of the two was being referred to?  (or else we'd have to break the ambiguity arbitrarily as we do for paren-less vs. paren-ful overloads).

**Comment by bradcray** [comment]
gbtitus: Let me know if there's something I'm missing above...  It seems like there must be, but I can't imagine what it would be.

For context, I filed this issue when coming across the test `test/users/bguarraci/function_name.chpl` which it looks like @mppf filed on Brian Guarraci's behalf some time ago.  I believe that the error has improved since the test was added and would consider it "good enough to retire."  But the .future file itself seems to suggest that it should be reasonable to have a function and variable with the same name at the same scope, which is why I kicked off this issue.

gcc/g++ generate a nicer error message for issues like this: `redefinition of 'foo' as different kind of symbol`

**Comment by gbtitus** [comment]
@bradcray No, I don't think you're missing anything.  I sort of led myself down a garden pathway thinking about the asymmetric behavior between

```chpl
var x: int;
var x: [1..2] int;
```

which would presumably cause a compile-time error, and

```chpl
var x: int;
proc x(i) { return ... };
```

which presumably would "work", and the asymmetry bothered me.

**Comment by bradcray** [comment]
@gbtitus: Happily, neither of those work today.  Both generate the message:

```
testit.chpl:1: error: 'x' has multiple definitions, redefined at:
  testit.chpl:2
```

**Comment by gbtitus** [comment]
Sorry I wasn't more clear about this in the first place.  I wasn't so much arguing against the change as I was trying to make sure we understood it and were generally okay with it.  It is a corner case -- clearly there are lots of ways for array-of-structs or struct-of-arrays implementations of syntactically identical code to behave differently at compile or execution time.  One could argue that this is just one more.  I think the thing that worried me is that with the change in place, the same code (as shown in my earlier comment) would be arguably correct or at least legal usage in the struct-of-arrays coding style and definitely non-conforming in the array-of-structs coding style.  I'm still mulling for myself how big a deal that is.

**Comment by bradcray** [comment]
To be crystal clear, I'm not arguing in favor of this change.  Since a .future test did do so, and I disagreed with it, I put it up in an issue for debate.  (So you don't need to try and convince yourself very hard to get behind this... :)  ).  I was mostly probing to see if anyone would say "Yes, clearly we should support this!"

**Comment by bradcray** [comment]
> how do we disambiguate between those?

I believe that you're correct that we always choose the paren-less one (though I should double-check the spec and/or historical notes).  I agree that if this is the case, it's worthy of a compiler warning.

**Comment by mppf** [comment]
I don't think it should be legal.

Additionally I don't think we should allow paren-full overloads and paren-less overloads of the same function in the same scope. (I.e. I think that should be an error, not a warning).

**Comment by bradcray** [comment]
I just stumbled across this issue and believe that we're all in violent agreement here; and my own belief that the current behavior is appropriate has only grown since I opened this as a devil's advocate on behalf of a future test (though I didn't note which one...).  So I'm closing it.
