### ISSUE TITLE
Unused class forall loop shadow variable causes internal error

### ISSUE THREAD

**Issue by daviditen** [chapel-lang/chapel#10122]
### Summary of Problem
An otherwise unused class that is an argument to a function that passes it into a `forall` loop hits an internal compiler error.  The error is that the class's reference type is missing during `processShadowVarsNew`.

Declaring an instance of the class type makes the problem go away.

### Steps to Reproduce

**Source Code:**
```chapel
class C {
  proc foo(A: []) {
  }
}

proc bar(A: [], x: C = nil) {
  forall a in A {
    if x then x.foo(A);
  }
}

// The internal error this test is about goes away if
// the declaration below is uncommented.
//const c: C;

var A: [1..10] int;

bar(A);
```

**Compile command:**
`chpl unusedClassForallArg.chpl`

**Associated Future Test(s):**
[test/parallel/forall/diten/unusedClassForallArg.chpl](https://github.com/chapel-lang/chapel/blob/master/test/parallel/forall/diten/unusedClassForallArg.chpl)
### Configuration Information

- Output of `chpl --version`:
chpl version 1.18.0 pre-release (97454bcc72)
Copyright (c) 2004-2018, Cray Inc.  (See LICENSE file for more details)

**Comment by vasslitvinov** [comment]
Resolved by #10658.
