### ISSUE TITLE
Should IO.readline() return false for the last line of a file if it's not newline-terminated?

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#10134]
### Summary of Problem

On success `IO.readline()` returns true and reports the number of
bytes read through `out numRead`.  Except, as noted in #9629/#9637, if
the last line of the file doesn't end with a newline, it returns false
(still reporting the number of bytes read).

This doesn't seem right, and seems a somewhat unintuitive interface to
program to.  Should it return true in this case?

**Comment by mppf** [comment]
it seems pretty clear to me that this is a bug
