### ISSUE TITLE
How should enums be represented by binary file I/O?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#10139]
In the past, we've typically represented enums in a binary file by casting to their underlying integer value and writing that out to the file using the smallest integer type applicable to all of the enum's underlying integer values.  Now that not all enums have an underlying integer value (issue #9785), this strategy doesn't work anymore, leading to a few alternatives:

Value written
==========

ordinal-always
--------------
In this scheme, we'd always use the ordinal values of the enum when writing binary I/O files.

hybrid approach
-----------------
In this scheme, we'd do binary I/O using the enum's underlying integer values if it has them, falling back to its ordinal values otherwise

The main tradeoffs between these schemes, as I see it are:
* ordinal-always is consistent across all enums; hybrid is inconsistent depending on whether the enum is abstract (has no underlying integer values) or concrete (does have them)
* for semi-concrete enums (those in which some, but not all enums have ints), it seems we'd need to use the ordinal approach, which could be confusing
* ordinal-always preserves state when enums have duplicate values (issue #9786); hybrid doesn't in such cases
* ordinal-always can get away with the minimal number of bits required to write the enum; in common cases, hybrid can as well, but for enums with large values (e.g., long bitmasks), it can't
* presumably if the user wanted to use the integer values, they could do so by writing out the enum cast to int; conversely, if the user wanted the ordinal value, they could do this if/when we expose enumToOrder() as a public procedure

some other approach?
-----------------------
Is there something else I haven't thought of?

Size written
=========
In either scheme, there are also choices to be made about the size being written out:

* always write out the smallest integer value that holds the ordinal values / integer values?
* always write out a consistent integer value unless the user says otherwise?

Here, the main tradeoff seems to be one of efficiency (minimal number of bits) vs. consistency (trivially predictable number of bits).  Presumably the user could override the default choice whatever it was.  For Chapel<->Chapel I/O, it almost doesn't matter; but for Chapel I/O on binary files that are read/consumed by other languages, it may.

Note that currently we use the "smallest" approach.

**Comment by mppf** [comment]
Thanks for explaining, I'm feeling pretty good about "ordinal-always" and the smallest size approach right now.

**Comment by gbtitus** [comment]
I like smallest-size, and I like ordinal-always because it allows for non-param associated values, which I also like.

**Comment by bradcray** [comment]
As of PR #10026, Greg's preferred solution is implement on master (and mine, I guess :) ).

**Comment by bradcray** [comment]
Since what's on master (ordinal-always, smallest-size) seems to fit what those of us who've commented on this issue want/expect, I'm going to move this issue to the Icebox and de-assign myself from it for now with the option for others to resurrect it down the road if the need arises.

**Comment by mppf** [comment]
> Since what's on master (ordinal-always, smallest-size) seems to fit what those of us who've commented on this issue want/expect, I'm going to move this issue to the Icebox and de-assign myself from it for now with the option for others to resurrect it down the road if the need arises.

@bradcray - I'd like to propose that we simply close this issue, unless you know of a reason to second guess the agreement reached.

**Comment by bradcray** [comment]
That seems OK to me.
