### ISSUE TITLE
default intent for shadow variables from owned

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#10142]
Based on the design in #8938, the type instantiated for an unconstrained generic formal, when passed an owned actual, is the borrow type:

``` chapel
proc f(x) {
  // x.type is borrowed MyClass
}
f(new owned MyClass());
```

This issue asks if a corresponding behavior should apply to shadow variables. Consider:

``` chapel
var x = new owned MyClass()
forall a in A {
  writeln(x.type:string); // borrowed or owned?
}
```

Current Direction:

Make the shadow variable be `borrowed` by default.

* arguably more consistent with outer-vars-pass-like-blank-function-arguments
* less likely to have perf surprises

Alternative of transferring ownership doesn't make sense as a default coforall/forall

Alternative of 'const ref owned' could work but
    * wouldn't want this dereference for the formal of a generic
    * don't think it's necessary for shadow variables to track changes

By analogy to 'int' or 'unmanaged'
  * int/unmanaged is copied
  * shadow variable won't track changes to outer variable

When is transferring ownership to make a shadow variable useful?
 * not for coforall/forall since only one task gets the ownership & it's racy
 * (could conceivably work with shared but what is the point?)
 * more useful for begin - transfer ownership into a task

Presumably using an intent leaves the type alone:
``` chapel
var x = new owned MyClass()
forall a in A with (const ref x) {
  writeln(x.type:string); // owned
}
```

**Comment by mppf** [comment]
Even if the shadow variable is borrowed by default, what should happen for non-default intents?

We could:
 a) use the intent to indicate ownership transfer or `ref` behavior in these cases
 b) completely ignore the intent (other than intent type) for the purposes of this change

Note that ownership transfer isn't really useful for `forall`/`coforall`/`cobegin` because it's inherently racy. However for `begin` it is useful.

Should this transfer an `owned` thing into the task?
``` chapel
var x = new owned MyClass()
begin (with in x) {
  writeln(x.type:string); // is it owned & destroyed by the task?
}
```

Or should the user instead write this:
``` chapel
var x = new owned MyClass()
begin (with var taskX = x) {
  writeln(taskX.type:string); // is it owned & destroyed by the task?
}
```

**Comment by mppf** [comment]
Task private variables for `begin` don't seem to be working:

``` chapel
class MyClass {
  var x:int;
}

config const n = 4;
proc test() {
  
  {
    var outerOwnedMyClass = new owned MyClass(1);
    var outerSharedMyClass = new shared MyClass(2);

    writeln("task local copy begin");
    sync {
      begin with (var locOuterOwnedMyClass = outerOwnedMyClass,
                  var locOuterSharedMyClass = outerSharedMyClass) {
        writeln("  ", outerOwnedMyClass.type:string);
        writeln("  ", outerSharedMyClass.type:string);
      }
    }
    writeln(outerOwnedMyClass);
  }

}

test();
```

**Comment by mppf** [comment]
> > Note that ownership transfer isn't really useful for forall/coforall/cobegin because it's inherently racy. 

> I suggest to make `[const] in` intent in this case a compiler error.


I'm currently leaning towards making `in` just pass the borrow by `in` intent (i.e. be the same as the default). The task-private-variable case above would be the way to write the ownership transfer pattern.

**Comment by vasslitvinov** [comment]
> Task private variables for begin don't seem to be working

Task-private variables are currently available only with foralls.
The above program should generate a user error, not an internal error, however.

**Comment by vasslitvinov** [comment]
> I'm currently leaning towards making in just pass the borrow by in intent

I am open to that. However, that would be a divergence from the behavior of a function argument, so is not a perfect solution.

One advantage, though, is that the user can have a modifiable borrow shadow var, which would be less elegant to achieve otherwise.

**Comment by mppf** [comment]
> I am open to that. However, that would be a divergence from the behavior of a function argument, so is not a perfect solution.

I'm trying to say that I think that both function arguments and shadow variables should behave this way.

**Comment by vasslitvinov** [comment]
> I think that both function arguments and shadow variables should behave this way.

I can see a virtue in making `in` intents mean "borrow" in both cases, and relying on @mppf's suggestion for passing ownership:

* to a function argument - by marking it `owned` or `shared` -- assuming this works as a no-op for non-class types,

* to a begin task's shadow variable - by creating a task-private variable as in the above example.

**Comment by mppf** [comment]
One thing it occurs to me to worry about is how nested intents would work with the shadow variable strategy.

``` chapel
var x:shared
coforall i in 1..10 {
  coforall j in 1..10 {
     if something then
       someGlobalVariable.someSharedField = x;
  }
}
```

How could the user write that pattern? It's clear enough with the intents-behave-differently strategy:

in intent:

``` chapel
var x:shared = new shared SomeClass();
coforall i in 1..10 with (in x) {
  coforall j in 1..10 with (in x) {
     if something then
       someGlobalVariable.someSharedField = x;
  }
}
```

ref intent, which is normally a way for coforall to capture outer variables the way a serial loop would
(This way the reference count is only adjusted in the event it needs to be, vs for every task):

``` chapel
var x:shared = new shared SomeClass();
coforall i in 1..10 with (ref x) {
  coforall j in 1..10 with (ref x) {
     if something then
       someGlobalVariable.someSharedField = x;
  }
}
```

It seems we'd need something else for the task-shadow-variables-borrow strategy:

``` chapel
var x:shared = new shared SomeClass();
coforall i in 1..10 with (var x1 = x) {
  coforall j in 1..10 with (var x2 = x1) {
     if something then
       someGlobalVariable.someSharedField = x2;
  }
}
```

``` chapel
var x:shared = new shared SomeClass();
coforall i in 1..10 with (shared x) {
  coforall j in 1..10 with (shared x) {
     if something then
       someGlobalVariable.someSharedField = x;
  }
}
```

But both of these update reference counts for each task - making me question why `ref` doesn't make it behave the same as an outer variable for a `for` loop, say.

**Comment by vasslitvinov** [comment]
Looks like the ref intent is the only viable approach among the options above.

> why ref doesn't make it behave the same as an outer variable for a for loop, say.

How is it behaving differently?

**Comment by mppf** [comment]
I think this issue has had good discussion but I think what's implemented is OK for now:
 * intent other than blank or `const` disables making the shadow var a borrow
 * default is to borrow
