### ISSUE TITLE
Reduce the overhead of uncontested locking I/O

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#10141]
https://github.com/chapel-lang/chapel/pull/10133 switched `chpl_sync_lock()` from an atomic spinlock to a native qthread sync lock. qthread sync variables have a lot more overhead than a simple atomic spinlock for the uncontested case, so this change hurt the performance of serial I/O. 

Ideally we would have some sort of hybrid lock that spins for a while before going to sleep. This could either be a new lock, or ideally probably a change to the sync variable implementation so that we get this benefit for all sync variables and not just a special case lock. That said it's probably a lot easier to design a hybrid lock that's built on top of sync vars instead of trying to stuff that into the implementation, so a good first start might be a new lock. Thematically related to https://github.com/chapel-lang/chapel/issues/9881 (create a chapel mutex library with a hybrid spinwait/blocking mutex)

https://github.com/chapel-lang/chapel/issues/7748 also has some microbenchmarks and other thoughts about a hybrid lock. 

[Here](https://chapel-lang.org/perf/chapcs/?startdate=2018/06/27&enddate=2018/07/10&graphs=parboilbfsexecutiontime,parboilsadserialexecutiontime,timetotreepaircount,cvschplwritingsinglenewlinestostdout) are some of the regressions for code doing serial I/O that were hurt by this change: 

![image](https://user-images.githubusercontent.com/1588337/42673206-0694db54-861f-11e8-9386-636aea441cb9.png)

![image](https://user-images.githubusercontent.com/1588337/42673227-21b3ba18-861f-11e8-84f4-29664ec8f19b.png)

![image](https://user-images.githubusercontent.com/1588337/42673234-28ce9016-861f-11e8-835c-2c2a829f6759.png)

**Comment by ronawho** [comment]
There has also been some discussion of trying to do compiler analysis to detect when locking isn't needed. To get a sense of the benefit of that versus a hybrid lock I wanted to compare locking vs non-locking I/O for Chapel and C/C++ to get a sense of the performance space. 

Here's some performance results for a really simple microbenchmark that compares performance of locking vs non-locking I/O. These programs just serially write the string "output" to stdout 100,000,000 times. The non-locking aren't locked, the test-and-set uses an atomic test-and-set lock and "mutex" uses a pthread mutex, std::mutex, or our I/O locking which uses a sync var today, and a spin-lock before #10133. Compiled with `--fast` or `-O3` and run with output redirected to `/dev/null` timed externally with `time`:

| config                 | non-locking | "mutex" lock | test-and-set lock |
| ---------------------- | ----------- | ------------ | ----------------- |
| chpl spin (pre #10133) |  2.8s       | 14.4s        |  4.2s             |
| chpl qt lock (#10133)  |  2.8s       | 29.1s        |  4.2s             |
| C                      |  1.9s       |  2.2s        |  4.1s             |
| C++                    |  2.2s       |  2.4s        |  4.1s             |

So our non-locking I/O is competitive with C/C++, but our locking really suffers. And pthread/std:: mutex is somehow faster than a simple atomic test-and-set lock, which is kinda surprising to me. I would have expected them to be on par. I think this shows that even our old spin-lock had more overhead than just the atomic spinwaiting lock since it was so much slower than a base test-and-set lock.

(and note that this is kinda a worst-case scenario for locking where the amount being output is crazy small, so the overheads are amplified. If your output was larger the overhead would probably be negligible.)

---
"Benchmark" Code:

```c++
/* ==> locking.cpp <== */
#include <iostream>
#include <mutex>

int main() {
  std::mutex lock;
  for (int i=0; i<100000000; i++) {
    lock.lock();
    std::cout << "output";
    lock.unlock();
  }
}

/* ==> manual-locking.cpp <== */
#include <iostream>
#include <atomic>

int main() {
  std::atomic_flag lock = ATOMIC_FLAG_INIT;
  for (int i=0; i<100000000; i++) {
    while (lock.test_and_set()) {}
    std::cout << "output";
    lock.clear();
  }
}

/* ==> non-locking.cpp <== */
#include <iostream>

int main() {
  for (int i=0; i<100000000; i++) {
    std::cout << "output";
  }
}
```

```c
/* ==> locking.c <== */
#include <stdio.h>
#include <pthread.h>

int main() {
  pthread_mutex_t lock;
  pthread_mutex_init(&lock, NULL);
  for (int i=0; i<100000000; i++) {
    pthread_mutex_lock(&lock);
    printf("output");
    pthread_mutex_unlock(&lock);
  }
}

/* ==> manual-locking.c <== */
#include <stdio.h>
#include <stdatomic.h>

int main() {
  atomic_flag lock = ATOMIC_FLAG_INIT;
  for (int i=0; i<100000000; i++) {
    while (atomic_flag_test_and_set(&lock)) {}
    printf("output");
    atomic_flag_clear(&lock);
  }
}

/* ==> non-locking.c <== */
#include <stdio.h>

int main() {
  for (int i=0; i<100000000; i++) {
    printf("output");
  }
}
```

```chpl
/* ==> locking.chpl <== */
for 1..100000000 {
  write("output");
}

/* ==> manual-locking.chpl <== */
const nb = openfd(1).writer(locking=false);
var lock: atomic bool;
for 1..100000000 {
  while lock.testAndSet() do chpl_task_yield();
  nb.write("output");
  lock.clear();
}

/* ==> non-locking.chpl <== */
const nb = openfd(1).writer(locking=false);
for 1..100000000 {
  nb.write("output");
}
```

**Comment by mppf** [comment]
@ronawho note that calls like printf normally do use locking, if the program is linked with pthreads. Additionally note that our stdout actually wraps C stdout, for interoperability reasons. So we could do a better job of comparing I/O systems with C and C++ if we were writing to a file descriptor openned in the program. (Of course maybe stdout performance really is what one cares about, though. If that's the case, we might be able to optionally disable wrapping C stdout and just use the file descriptor instead - at the cost of mangling printfs from C code).

**Comment by immadisairaj** [comment]
I would like to work on this issue. Can I get some tips from where to start with this issue to solve.
I would also like to know if this issue to be done after #9881 or now.

**Comment by ronawho** [comment]
@immadisairaj the I/O locking code is implemented in the runtime, which is written in C. I would expect resolving this to be a relatively involved and low-level.

#9881 is only thematically related because it's about locking.

The original issue is asking for a hybrid lock, that would be implemented in each tasking layer. An alternative that we've recently used in other code (https://github.com/chapel-lang/chapel/pull/13013) would be to use an atomic test-and-test-and-set lock. The tricky part here is that we'd need to implement the lock in the runtime and have something that's efficient for all atomic implementations.

I'd probably recommend looking for a different issue to tackle, but you're welcome to take a stab at this if you're still interested.
