### ISSUE TITLE
Should INT_ASSERT() take an optional AST to indicate source location?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#10152]
When INT_ASSERT()s are triggered, it seems to take extra work to figure out where things went wrong.  It seems as though if there were a two-argument overload where one argument was an AST source location (as with INT_FATAL, USR_FATAL, etc.) we'd get more information out when assertions were triggered (though we'd also have to train people to try and write INT_ASSERT()s in the two-argument form.

**Comment by chris980** [comment]
Hi,
Could you take a look at this [PR,](https://github.com/chapel-lang/chapel/pull/15376) please? Thanks in advance
