### ISSUE TITLE
Chapel doesn't complain about too-big integral literals

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#10158]
### Summary of Problem

I declared a clearly too-large integer literal expecting the compiler to complain about it, but it didn't.

### Steps to Reproduce

**Associated Future Test(s):**
[`test/types/integral/tooBig.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/types/integral/tooBig.chpl
          ) #10157

### Configuration Information

- Output of `chpl --version`: `chpl version 1.18.0 pre-release (efcef43)`

**Comment by nspark** [comment]
"good first issue" 😆

**Comment by bradcray** [comment]
> "good first issue" 😆

My C string-to-int fu isn't the greatest, but I suspect it's probably a simple matter of adding some error checking to [buildIntLiteral()](https://github.com/chapel-lang/chapel/blob/master/compiler/AST/build.cpp#L262).

**Comment by bradcray** [comment]
Actually, I didn't dig quite deep enough... the culprit is more likely to be in [define_str2Int()]( https://github.com/chapel-lang/chapel/blob/master/compiler/util/stringutil.cpp#L143)

**Comment by daviditen** [comment]
Closed with PRs #11413, #11432.
