### ISSUE TITLE
Seg fault upon closing unopened channel

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#10169]
### Summary of Problem
Attempting to close an unopened channel results in a segmentation fault. 

### Steps to Reproduce

**Source Code:**

```chapel
var logFile: channel(true, kind=iokind.dynamic, locking=true);
logFile.close();
```

### Configuration Information

- Output of `chpl --version`: `chpl version 1.18.0 pre-release (4382fa1)`

**Comment by mppf** [comment]
it should be throwing an error, if that's not obvious
