### ISSUE TITLE
Shared class in record causes internal compiler error

### ISSUE THREAD

**Issue by daviditen** [chapel-lang/chapel#10182]
### Summary of Problem
Simple code involving Shared class as record member trips internal compiler error `internal error: would add problematic deref [wrappers.cpp:1673]`.

### Steps to Reproduce

**Source Code:**
```chapel
use SharedObject;

class C { }

record R {
  var sc: Shared(C);
}

proc main {
  var r = new R();
}
```

**Compile command:**
```
chpl sharedClass.chpl
```

**Associated Future Test(s):**
[sharedClassInRecord.chpl](https://github.com/chapel-lang/chapel/blob/master/test/classes/delete-free/shared/sharedClassInRecord.chpl)

### Configuration Information

- Output of `chpl --version`:
```
chpl version 1.18.0 pre-release (cf7a90470d)
Copyright (c) 2004-2018, Cray Inc.  (See LICENSE file for more details)
```

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: clang
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: intrinsics
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none
```

**Comment by bradcray** [comment]
@daviditen: Checking my memory.  Am I correct that this issue wasn't directly related (at least obviously) to the memory leaks in issue #7894, but was something you came across while working on that issue?  Thanks.

**Comment by daviditen** [comment]
Yes, that's right.  I came across this while reducing the test case for #7894, but it's not directly related to the leaks there.

**Comment by mppf** [comment]
This compiles now and in fact the .future was removed in PR #10459.
