### ISSUE TITLE
setchplenv.bash interacts poorly with Ubuntu-style empty $MANPATH when $CHPL_HOME is already set

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#10196]
### Summary of Problem

After sourcing `setchplenv.bash`, I can't view non-Chapel manpages on my
Ubuntu system.

My setup configures an empty `$MANPATH`.  When `$MANPATH` is empty,
`man` uses its own mechanism to find the system man pages.

`setchplenv.bash` leaves `$MANPATH` set to
`/home/fortytwo/src/chapel/man: `.  The trailing space keeps `man`
from using its own mechanism, and it can no longer find system man
pages.

### Steps to Reproduce

```
fortytwo@magrathea:~/src/chapel (master)$ echo $MANPATH

fortytwo@magrathea:~/src/chapel (master)$ manpath
/usr/local/man:/usr/local/share/man:/usr/share/man
```
```
fortytwo@magrathea:~/src/chapel (master)$ . util/setchplenv.bash 
Setting CHPL_HOME to /home/fortytwo/src/chapel
Setting CHPL_HOST_PLATFORM to linux64
Updating PATH to include /home/fortytwo/src/chapel/bin/linux64
                     and /home/fortytwo/src/chapel/util
Updating MANPATH to include /home/fortytwo/src/chapel/man
```
```
fortytwo@magrathea:~/src/chapel (master)$ echo ,$MANPATH,
,/home/fortytwo/src/chapel/man: ,
fortytwo@magrathea:~/src/chapel (master)$ manpath
manpath: warning: $MANPATH set, ignoring /etc/manpath.config
/home/fortytwo/src/chapel/man: 
fortytwo@magrathea:~/src/chapel (master)$ man ls
No manual entry for ls
See 'man 7 undocumented' for help when manual pages are not available.
```

If I manually set `$MANPATH` to remove the space, `man` can find
both the system and Chapel man pages.

```
fortytwo@magrathea:~/src/chapel (master)$ export MANPATH=/home/fortytwo/src/chapel/man:
fortytwo@magrathea:~/src/chapel (master)$ manpath
manpath: warning: $MANPATH set, appending /etc/manpath.config
/home/fortytwo/src/chapel/man:/home/fortytwo/src/chapel/man:/usr/local/man:/usr/local/share/man:/usr/share/man
fortytwo@magrathea:~/src/chapel (master)$ man ls | head -1
LS(1)                                        User Commands                                        LS(1)
```

**Comment by mppf** [comment]
I don't understand why but I'm not seeing this issue. On my Ubuntu 18.04 system, MANPATH isn't set at all (doesn't appear in `env`) and the setchplenv.bash script doesn't leave a space. Which version of Python are you using?

**Comment by cassella** [comment]
Hmm.  I'll look into it further tonight.  In the meantime, I'm using python 2.7.12.

**Comment by cassella** [comment]
I see `fixpath.py` producing the space:

```
fortytwo@magrathea:~/src/chapel (master)$ env | grep MAN
MANDATORY_PATH=/usr/share/gconf/fvwm.mandatory.path
fortytwo@magrathea:~/src/chapel (master)$ echo ",$(util/config/fixpath.py MANPATH),"
, ,

fortytwo@magrathea:~/src/chapel (master)$ MANPATH=""
fortytwo@magrathea:~/src/chapel (master)$ echo ",$(util/config/fixpath.py MANPATH),"
, ,

fortytwo@magrathea:~/src/chapel (master)$ export MANPATH
fortytwo@magrathea:~/src/chapel (master)$ echo ",$(util/config/fixpath.py MANPATH),"
,,
```

From a fresh login with this change,

```diff
--- a/util/config/fixpath.py
+++ b/util/config/fixpath.py
@@ -32,6 +32,10 @@ def main(env='PATH', delim=':'):
     # Split path into list separated by non-escaped ':'s, and sieve chpl_home
     newpath = [escape_path(p) for p in re.split(pattern, path) if chpl_home not in p]
 
+    print(',{path},'.format(path=path))
+    print(re.split(pattern, path))
+    print(newpath)
+
     # Return path delimited by shell-type (':' vs. ' ')
     return delim.join(newpath)
 
```

```
fortytwo@magrathea:~/src/chapel (master)$ util/config/fixpath.py MANPATH
, ,
[' ']
[' ']
```

Which seems like what the script should do if `os.getenv()` returns
`' '` as directed by the `default=' '`.


And reading `setchplenv.bash`, it's clear that if `fixpath.py` returns
a space, `$MYMANPATH` will be a space, and `MANPATH` will be set to
`"$CHPL_HOME/man: "`, with a space.

Do you get something different from the `getenv()` call, or from
`re.split()`, or?

**Comment by mppf** [comment]
I get this (fresh login):
```
$ util/config/fixpath.py MANPATH
, ,
[' ']
[]
```

```
$ env | grep MAN
```

has no output.

Maybe fix_path.py is using the ' ' default to do something with CHPL_HOME?

Again from a fresh login:
```
export CHPL_HOME=`pwd`
$ util/config/fixpath.py MANPATH
, ,
[' ']
[' ']
```

Anyway so it appears to be the case that CHPL_HOME must be set for this problem to appear.

@ben-albrecht added the defaults of ' ' in PR #2742. Ben - do you know if there is a reason that the ' ' defaults need to stay?

**Comment by cassella** [comment]
Hah!  I set CHPL_HOME in my `.bashrc`.  I wonder why I do that.  Thanks!

**Comment by cassella** [comment]
I confirmed my problem goes away if I don't set `CHPL_HOME` before sourcing `setchplenv.bash`.  I'm satisfied with that.  Feel free to close the issue and PR if it's not interesting.

**Comment by mppf** [comment]
I think it's probably worth fixing but I'm waiting for @ben-albrecht to have a look

**Comment by ben-albrecht** [comment]
> @ben-albrecht added the defaults of ' ' in PR #2742. Ben - do you know if there is a reason that the ' ' defaults need to stay?

Are you asking if the defaults can be removed or if there was a reason for them to be `' '` instead of `''` ? Since they are always called from the `setchplenv.*` scripts which should set `CHPL_HOME`, it's probably safe to remove the defaults, but I also see no reason why the default of `''` wouldn't work. I could be missing something though.

**Comment by cassella** [comment]
Note, the `setchplenv.*` scripts all call `fixpath.py` before setting `CHPL_HOME`.

Though it may be set already.  Besides my `.bashrc`, `CHPL_HOME` may be set if you're changing from one `CHPL_HOME` to another.  (In which case `fixpath` will see it and be able to remove the old `CHPL_HOME` paths from `PATH` and `MANPATH` before adding the new ones.  That's convenient.)

**Comment by mppf** [comment]
> Does a default value of '' accomplish that?

It does for Paul, see PR #10197.
