### ISSUE TITLE
User-defined Error cannot use keyword `override` with `throws`

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#10218]
### Summary of Problem
Requires #10217 to be fixed. Workaround: Annotate `throws` on `writeThis` method around line 58 of `$CHPL_HOME/modules/internal/ChapelError.chpl`.

Same code as #10217 correctly omits a compiler warning to recommend annotating `UserError.writeThis` with `override`, but when doing so, this error occurs:
```
syntax error: near 'override'
```
I assume this error is because this feature is still work in progress. Just a data point because this issue will probably crop up when adding `override` on everything.

### Steps to Reproduce

**Source Code:**

```chapel
module IOThrowingFunctionWriteErrorInheritanceOverride {
class UserError: Error {
  proc writeThis(f) override throws /* throws override */ {
    f.write("UserError is child of Error");
  }
}
proc main() {
  try {
    throw new UserError();
  }
  catch e {
    writeln(e);
  }
}
} // module IOThrowingFunctionWriteErrorInheritanceOverride
```

**Compile command:**
`chpl --force-initializers --override-checking`

### Configuration Information
`chpl version 1.18.0 pre-release (e5cdbf130e)`

**Comment by cassella** [comment]
This is closer to working,

```chapel
  override proc writeThis(f) {
    f <~> "UserError is child of Error";
  }
```

But the compiler says that `class Error` itself needs to use an `override` on its `writeThis()` (I think):

```
fortytwo@magrathea:~/src/chapel (master)$ chpl --force-initializers --override-checking overridethrowthis.chpl
$CHPL_HOME/modules/internal/ChapelError.chpl:58: warning: Error.writeThis override keyword required for method matching signature of superclass method

fortytwo@magrathea:~/src/chapel (master)$ ./overridethrowthis -nl 1
UserError is child of Error
```

**Comment by cassella** [comment]
I think you mean

```chapel
  override proc writeThis(f) throws {
```
which makes it behave the same as #10217

`ChapelError`'s `Error.writeThis` is now marked with `override`.

**Comment by lydia-duncan** [comment]
I believe Paul is right, it is accurate that this is a syntax error because `override` should be placed before `proc`.  I'm going to close this issue - Bryant, please let me know if you think that is incorrect.
