### ISSUE TITLE
Compiler warning when throwing specific exception to outer general handler

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#10224]
### Summary of Problem
Occurs in #10221 too, but filed separately because it was unrelated.

C-compiler backend warning is generated when specific-exception handler in an inner exception try-catch block throws to a general-handler outer block.
```
In function: 'chpl_user_main':
warning: comparison of distinct pointer types lacks a cast
  throwingHandledError_chpl = (call_tmp_chpl3 == e_chpl);
                                              ^~
```
Code still executes:
```
Caught NilThrownError
Caught general error
```

### Steps to Reproduce

**Source Code:**

```chapel
module ExceptionWarning {
  proc main() {
    try {
      try {
        throw new NilThrownError();
      }
      catch e: NilThrownError {
        writeln("Caught NilThrownError");
        throw e;
      }
    }
    catch e {
      writeln("Caught general error");
    }
  }
} // module ExceptionWarning
```

**Compile command:**
No flags.

### Configuration Information
`chpl version 1.18.0 pre-release (e5cdbf130e)`

**Comment by lydia-duncan** [comment]
I'm going to play with this issue, assuming no one else has grabbed it

**Comment by lydia-duncan** [comment]
This issue is with the first catch block itself.  It appears that specifying the subtype of Error causes issues when it is rethrown, no matter whether the try/catch block is stand-alone or wrapped in another try/catch block.  This is not the case when the caught error does not specify its subtype.
