### ISSUE TITLE
Hang in Spawn module upon multiple waits

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#10225]
### Summary of Problem

Calling `wait` or `communicate` on a spawned process more than once results in a hang. I believe we should be able to catch this and either throw an error or return the same result as the previous `wait` or `communicate` (this is what python does).

### Steps to Reproduce

**Source Code:**

```chapel
use Spawn;

var process = spawn(['ls'], stdout=PIPE, stderr=PIPE);

process.wait();
writeln('Process done');
process.wait();
writeln('Process done again');
```

**Output:**

```
Process done
<hangs indefinitely>
```

### Configuration Information

- Output of `chpl --version`: `chpl version 1.18.0 pre-release (4382fa1)`

**Comment by ben-albrecht** [comment]
This was discovered by @aheye

**Comment by bradcray** [comment]
@mppf: Is this an easy fix?

**Comment by mppf** [comment]
@bradcray - I think this is highly likely to be easy to fix but I havn't dug into the details.
