### ISSUE TITLE
Feature request : offsetof

### ISSUE THREAD

**Issue by npadmana** [chapel-lang/chapel#10231]
[ This issue arose from a discussion on gitter with @mppf]

Every so often (eg. when interacting with C code), I need to know the offset of elements of a record. C provides the `offsetof` macro; it would be useful to have the same functionality in Chapel as part of a standard module.

As a prototype, the following code does appear to work ---

```chapel
use Reflection;

proc offsetof(type t, param fieldname : string) {
  var x : t;
  return c_ptrTo(getFieldRef(x, fieldname)):uint - c_ptrTo(x):uint;
}
```

Running it with 
```chapel
record Test {
  var x : int(8);
  var y : int;
  var z : real;

}

writeln(offsetof(Test,"x"));
writeln(offsetof(Test,"y"));
writeln(offsetof(Test,"z"));
```
produces
```
0
8
16
```
as expected.

**Comment by bradcray** [comment]
I'm not fully convinced we want to go down the route of exposing a lot about memory layout at the Chapel level.  This seems more appropriate at the C level (or C interoperability level).  For instance, if Chapel were to provide the routine above, it would probably be appropriate to consider it a `param` function, but implementing it as a `param` would be challenging in the presence of back-end compiler optimizations (by the C compiler or LLVM).

**Comment by npadmana** [comment]
@bradcray -- I agree that this is a C interoperability issue.

**Comment by mppf** [comment]
Right, we were talking about including some sort of `offsetof` routine in CPtr.chpl next to `sizeof`.

**Comment by lydia-duncan** [comment]
I'm going to take a stab at this if no one else has grabbed it

**Comment by lydia-duncan** [comment]
I made some minor changes, but it is otherwise not very altered.  #11416 has the details, feel free to take a look and offer feedback!

**Comment by lydia-duncan** [comment]
@npadmana - I've merged the PR, but it only covers records.  We believe that support for classes would require some modification of code generation.  Would you like us to look into adding the support for classes as well?

**Comment by npadmana** [comment]
@lydia-duncan, all -- Thanks for pushing this through. I don't have a particular use case with classes, so I'm happy with this just for records (the case I had was to pass a user-defined type in HDF5).
