### ISSUE TITLE
Spike: Investigate possible LCALS issues on ARM

### ISSUE THREAD

**Issue by dmk42** [chapel-lang/chapel#10233]
We see an accuracy issue on the order of 4 out of 10**16.  This looks suspiciously like it might be only one ULP for double precision floats, so it might not be a problem.  We need to know if it is a problem and fix if it is a Chapel issue.

**Comment by dmk42** [comment]
My initial suspicion was very close.  The closest possible representation to the exact expected value in 64-bit IEEE floating point is `0x1.a207d05644b6fp+53`.  Our answer is `0x1.a207d05644b71p+53` which as you can see is 2 ULP off (I had guessed 1 ULP).

@daviditen - I will investigate a little more but so far I am inclined to say that 2 ULP is a reasonable error.  What do you think?

**Comment by dmk42** [comment]
Confirmed.  If I rewrite the check to divide the difference by the expected value, I find that allowing only a 2 ULP error is actually too strict for several of the tests.

An absolute difference of 0.17 is sometimes very tiny and sometimes huge compared to the expected answer.  A relative difference of 3e-16 is 2 ULP.

**Comment by dmk42** [comment]
Closed by #10408 .

**Comment by daviditen** [comment]
@dmk42 I agree that using a relative error instead of absolute sounds reasonable.
