### ISSUE TITLE
deprecate casts from numeric types to c_string?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#10248]
I just noticed that the cast function from complex to c_string cannot possibly work:
https://github.com/chapel-lang/chapel/blob/7c8091f78a8e70c655f55fee52a65138c19b3054/modules/internal/CString.chpl#L144-L170 

The problem is that `+` on `c_string` was removed in PR #4487.

In this issue, I'm proposing removing the cast functions that create c_string as well. If we decide to continue to support such an operation in the library, I think we would be better served by explicit routines. The issue is that somebody has to free the returned C string and it's hard to understand that when looking at code just containing a cast. I think we should just support `string` versions of these casts.

**Comment by bradcray** [comment]
I'm generally in favor of this, but will be curious to know what breaks or needs to be worked around if we pull these out.

**Comment by daviditen** [comment]
I noticed that the comparison at line 153 is also incorrect.  `im` is always an empty c_string at that point.  I think it wanted to do `if x.im == -0.0` or maybe `if x.im:string == "-0.0"`.

**Comment by mppf** [comment]
@bradcray - I like questions that I know how to answer. There is just 1 failure in regular testing and it's a test that I just un-futured:
 [Error matching program output for types/string/thomasvandoren/int-to-c_string]

**Comment by bradcray** [comment]
I'd be in favor of removing it then.  I think the less that Chapel tries to make `c_string` productive / first-class, the better...  I was worried we might rely on these casts for config parsing or I/O or the like, but if not...

**Comment by mppf** [comment]
I was adding a deprecation warning (which leaves it in for a release). Given it's scant use, can we just remove it entirely?

**Comment by bradcray** [comment]
> Given it's scant use, can we just remove it entirely?

I wouldn't be absolutely opposed to this, though the deprecating warning seems kinder (and easy enough to implement compared to some other cases we've discussed recently) if you've already gotten a good start on that.
