### ISSUE TITLE
BLAS module cannot find lapacke.h when linking against Intel MKL

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#10251]
### Summary of Problem
With the caveat that I don't know much about BLAS, LAPACK, or Intel MKL --

Compiling one of the test programs in `$CHPL_HOME/test/library/packages/BLAS` to use Intel MKL results in an error saying it can't find header file "lapacke.h".

Workaround: Symlink `$MKLPATH/lib/intel64/mkl_lapacke.h` to `$HOME/chpl/include/lapacke.h` and include that directory on the compile line.

I imagine the proper fix is to apply whatever logic `isBLAS_MKL` is using on `lapacke.h` as well.

### Steps to Reproduce

**Source Code:**
`$CHPL_HOME/test/library/packages/BLAS/test_blas1.chpl`

**Compile command:**
I modified the Makefile:
- Added `BLASFLAGS = -sisBLAS_MKL=true -I$MKLPATH/include -L$MKLPATH/lib/intel64 -I$HOME/chpl/include -lmkl_rt`
- Commented out LAPACKFLAGS
- Appended $(BLASFLAGS) to CHPLFLAGS

`chpl test_blas1.chpl --ccflags -Wno-enum-conversion -sisBLAS_MKL=true -I$MKLPATH/include -L$MKLPATH/lib/intel64 -I$HOME/chpl/include -lmkl_rt -o test_blas1`

### Configuration Information
`chpl version 1.18.0 pre-release (e5cdbf130e)`
Intel MKL 2017.0.3

### Priority
Not a high priority now that I have a workaround.

**Comment by ian-bertolacci** [comment]
@ben-albrecht Did we have a fix for this?

**Comment by ben-albrecht** [comment]
Yes - I have a fix for this, which adds a simple `-sisLAPACK_MKL` config param to `LAPACK` module. I will attempt to get that in soon.

Note that MKL deviates from the established interface for the low level `LAPACK` routines, so MKL users must rely only on the high level `LAPACKE` routines.
