### ISSUE TITLE
Clean up the bigint implementation

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#10280]
We have a lot of code in the bigint implementation that looks something like:

```chpl
if _local {
  ret = mpz_op(x.mpz)

} else if x.localeId == chpl_nodeID {
    ret = mpz_op(x.mpz)

} else {
  const xLoc = chpl_buildLocaleID(x.localeId, c_sublocid_any);

  on __primitive("chpl_on_locale_num", xLoc) {
    ret = mpz_op(x.mpz);
  }
}
```

Which is pretty gross because of all the code duplication and because we're using the `chpl_on_locale_num` primitive. I think this case could simply be rewritten as:

```chpl
on this {
  ret = mpz_op(x.mpz);
}
```

without perf loss for `--local` (since on stmts are completely removed) and without performance loss for the `x.localeId == chpl_nodeID` now that we optimized direct on stmts (https://github.com/chapel-lang/chapel/pull/3890)

The above is only for operations on a single bigint, operations on multiple bitints is trickier. For instance this is what we do with addition between 2 bigints:

```chpl
proc +(const ref a: bigint, const ref b: bigint) {
  var c = new bigint();

  if _local {
    mpz_add(c.mpz, a.mpz, b.mpz);

  } else if a.localeId == chpl_nodeID && b.localeId == chpl_nodeID {
    mpz_add(c.mpz, a.mpz, b.mpz);

  } else {
    const a_ = a;
    const b_ = b;

    mpz_add(c.mpz, a_.mpz, b_.mpz);
  }

  return c;
}
```

We don't just want that to be: 
```chpl
proc +(const ref a: bigint, const ref b: bigint) {
  var c = new bigint();

  const a_ = a, b_ = b; // localize

  mpz_add(c.mpz, a_.mpz, b_.mpz);

  return c;
}
```

Because we'd pay the cost of a deep copy even when a/b are local, but we could still improve the existing code. Or maybe if we had a steal constructor or something we could have a localize() call that would return the existing record if it is local, otherwise make a deep copy?

**Comment by jabraham17** [comment]
This was implemented in https://github.com/chapel-lang/chapel/pull/21738. Many bigint operations now use a `.localize()` method and `bigintWrapper` to reduce code duplication
