### ISSUE TITLE
enable forall loop over forall expr over zip(A,B)

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#10282]
The following code currently crashes the compiler,
while we agree that it should work.

```chpl
var A, B: [1..4] int;
forall xy in ([ab in zip(A,B)] ab) do
  xy = (1,5); // expected to update A and B's elements
```

The cause appears to be inconsistency of what the "zippered" flag means in the ForallStmt node.

test:
```
test/expressions/loop-expr/forall-over-zip-over-arrays.chpl
```

**Comment by bradcray** [comment]
That explanation works for me.  I don't necessarily trust that what the compiler does is always right when it comes to tuples, which is partially why I asked.

**Comment by vasslitvinov** [comment]
I am moving this to backlog to support robustness of the shape preservation feature.
