### ISSUE TITLE
Doc generation breaks when PYTHONPATH used instead of CHPL_PYTHONPATH

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#10291]
### Summary of Problem
Documenting this issue for awareness; I'm not sure if there's anything to fix other than maybe some additional documentation.

Generating documentation from source. I'll be focusing on chpl-venv because it seems indicative of whether the rest of doc generation will succeed.
- On tag 1.16.0, doc generation works fine. It didn't matter whether I set `PYTHON`, `PYTHONPATH`, or `CHPL_PYTHONPATH` (though the last one didn't exist in 1.16). However, I'm not remarking that 1.16 was better than right now; just providing a data point for the comparison below.
- On tag 1.17.1, I ran into problems. `make docs` uses the system site-package's version of Sphinx (1.4.4 on my system) instead of Sphinx 1.3.3 as specified in chpldoc-requirements.txt when `PYTHONPATH` is set. However, if `CHPL_PYTHONPATH` is set, everything works correctly (though you might want to `git clean` to be sure).

Some takeaways:
- Use `CHPL_PYTHONPATH` and don't use `PYTHONPATH`
- The correct setting for `CHPL_PYTHONPATH` is probably whatever the output is of `python -m ensurepip`.
- `make chpldoc-venv` uses `python -S`, which appears to ignore the system site-packages (at least it does on my system). This basically necessitates the use of `CHPL_PYTHONPATH` to find `pip`.

My thought process and the behaviors I encountered:

#### 1.  Initial problems searching site-packages
`cd third-party/chpl-venv && make chpldoc-venv`
```
export PYTHONPATH="$CHPL_PYTHONPATH:<multiple dirs for chpl-venv>:$PYTHONPATH" && \
        python -S /path/to/pip install ...
Traceback (most recent call last):
  File "/path/to/pip", line 7, in <module>
    from pip import main
ImportError: No module named pip
```
Okay. `pip` isn't found, which is weird. I see `PYTHONPATH` is both used and set, and the user's `PYTHONPATH` is prepended, so I'll use that and point it at my site-packages.

#### 2.  Using PYTHONPATH
(Add `export PYTHONPATH=/path/to/system/python2.7/site-packages` to .bashrc and open a new shell.)

Make again, and it looks like it works, except there are hints that things are wrong:

```
Installing collected packages: ...
  Found existing installation: MarkupSafe 1.0
    Not uninstalling markupsafe at /path/to/system/python2.7/site-packages, outside environment $CHPL_HOME/third-party/chpl-venv/install/linux64/py2.7/chpl-virtualenv
  Found existing installation: Jinja2 2.9.6
    Not uninstalling jinja2 at /path/to/system/python2.7/site-packages, outside environment $CHPL_HOME/third-party/chpl-venv/install/linux64/py2.7/chpl-virtualenv
  Found existing installation: Pygments 2.1.3
    Not uninstalling pygments at ...
  ... repeat for most of the packages being installed ...
Successfully installed ...
```

That's the only hint that things will go wrong when `make docs` tries to use sphinx-build inside virtualenv.
```
cd $CHPL_HOME && make docs
...
Running Sphinx v1.4.4
...
```

#### 3.  Use CHPL_PYTHONPATH instead of PYTHONPATH
Everything works correctly. I don't know whether prepending vs. appending to `export PYTHONPATH` made a difference, or whether something else broke between the multitude of scripts that get called along the way.

### Configuration Information
- Chapel git tag 1.17.1
- Python 2.7.12

**Comment by BryantLam** [comment]
It might not be easily reproducible, so I'm okay with that. This issue shouldn't be a high priority if it takes a lot of effort to figure out. :smiley: 

CentOS 6.x
Manually installed Python 2.7.12
- Custom site-packages directory (`python -m site` dumps out typical site-packages directories with one custom/unique system-specific site-packages directory as the last entry in the list. This directory is also outputted when `pythom -m ensurepip` is executed and is what `CHPL_PYTHONPATH` is now set to.)
- Environment does not have `PYTHONPATH` set (e.g., `env | grep PYTHON` yields no output).

**Comment by jabraham17** [comment]
Closing, I don't think this is relevant anymore as I can find no mention of `CHPL_PYTHONPATH` in our build scripts and the python dependency part of our build system is very different now
