### ISSUE TITLE
Implicit double-free from rethrown exception inside TaskErrors handler

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#10297]
### Summary of Problem
Compiler inserts a `delete` on all exceptions inside a handler for `TaskErrors` even though one of those exceptions was rethrown.
```
Caught some TaskErrors
UserError.deinit(0)
UserError.deinit(3)
UserError.deinit(1)
UserError.deinit(2)
Outer catch
UserError.deinit(0) // <-- double free
End of main
```

### Steps to Reproduce

**Source Code:**

```chapel
module ReThrown {
class UserError: Error {
  var x: int;
  proc init(x: int) { this.x = x; }
  proc deinit() { writeln("UserError.deinit(", this.x, ")"); }
}
proc main() {
  try {
    try {
      forall i in 0..3 {
        var ex = new UserError(i);
        throw ex;
      }
    }
    catch errors: TaskErrors {
      writeln("Caught some TaskErrors");
      for i in errors {
        throw i;
      }
    }
  }
  catch e {
    writeln("Outer catch");
  }
  writeln("End of main");
}
} // module ReThrown
```

### Configuration Information
`chpl version 1.18.0 pre-release (e5cdbf130e)`

**Comment by mppf** [comment]
It's likely that a solution to #10221 would also solve this.

**Comment by BryantLam** [comment]
After #12090, this code is hard to fix because `TaskErrors` stores `unmanaged Error`s in the inner catch block. Here is my story. I have not managed to fix this yet in an acceptably generic way (i.e., yield `owned UserError` from `TaskErrors` without having to construct one explicitly).

## Attempted remedies
### throw new owned <obj>
```chapel
    catch errors: TaskErrors {
      writeln("Caught some TaskErrors");
      for i in errors {
        throw new owned i; // Is this syntax intended? It compiles.
      }
    }
```
I'm unsure if this was intended. The compilation fails if the *for* loop is replaced with `throw new owned errors[0]`. Nevertheless, the program compiles, still double-frees, and will sometimes segfault on subsequent runs. Possibly a syntax bug.

## cannot coerce unmanaged to owned
```chapel
    catch errors: TaskErrors {
      writeln("Caught some TaskErrors");
      for i in errors {
        var ex: owned = i; // error: Could not coerce unmanaged Error to _owned in initialization
        throw ex;
      }
    }
```
I tried this because I thought the `TaskError` objects were owned, but they weren't. Possible solution is to make `TaskErrors` hold `owned Error`s.

###  try to construct owned Error
```chapel
    catch errors: TaskErrors {
      writeln("Caught some TaskErrors");
      for i in errors {
        var ex: owned = new owned Error(i); // error: unresolved call 'Error.init(unmanaged Error)'
        throw ex;
      }
    }
```
`Error` doesn't have a copy initializer for `unmanaged Error` to use. Possible solution is to add one.

**Comment by mppf** [comment]
@BryantLam - yes TaskErrors should contain `owned Error` and that it doesn't was a simple oversight. I'll have a look.

**Comment by BryantLam** [comment]
This code is correctly resolved by #12225 and after changing the code's `throw new` to `throw new owned`.

That said, it feels problematic that the original code still compiles on master (and emits a warning) in an attempt to aid user porting. The warning would only truly be applicable if the old error handling worked, but it didn't.

`warning: Throwing borrowed error - please throw owned` should really be an error.

**Comment by BryantLam** [comment]
Related #12157

**Comment by BryantLam** [comment]
Interesting observation that I didn't realize before. The original code
```chapel
      forall i in 0..3 {
        var ex = new UserError(i);
        throw ex;
      }
```
yields `Throwing borrowed error`, but changing it to:
```chapel
      forall i in 0..3 {
        throw new UserError(i);
      }
```
now yields `Throwing unmanaged error` (and the correct behavior due to new catching-owned logic).

**Comment by mppf** [comment]
@BryantLam - thanks for the interesting observation - it led me to change one of those two cases into an error in PR #12341.
