### ISSUE TITLE
Performance regressions from #10114

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#10303]
There were some performance regressions for fasta as a result of "disabling enum->int casts for enums without explicit values" (https://github.com/chapel-lang/chapel/pull/10114)

Here's some of the [graphs](https://chapel-lang.org/perf/chapcs/?startdate=2018/06/27&enddate=2018/07/10&graphs=fastashootoutbenchmarkn25000000,fastareduxshootoutbenchmarkn25000000)

![image](https://user-images.githubusercontent.com/1588337/42662470-8c8596b0-85e6-11e8-9a2a-fc0bbbc3b358.png)

Fasta uses binary I/O, which may be related.

**Comment by bradcray** [comment]
I believe that the fasta cases should be resolved by PR #10308.  I'm not seeing any enums in @npadmana's benchmark, though, so am not sure what's going on there.  Possibly something deeper in the internal modules, so I'm going to wait to see whether #10308 restores the old performance before digging further.

**Comment by ronawho** [comment]
Whoops, I was wrong about the "Time to tree paircount" regression being from this. That regression is mine a result of slower serial  I/O as a result of https://github.com/chapel-lang/chapel/pull/10133. Will update the issue description and the link to the performance graphs

**Comment by ronawho** [comment]
I added the "Time to tree paircount" regression to https://github.com/chapel-lang/chapel/issues/10141

**Comment by ronawho** [comment]
Fasta perf is back to normal: 

![image](https://user-images.githubusercontent.com/1588337/42771461-249ddf8c-88dc-11e8-9b6f-63475d9a9a7e.png)
