### ISSUE TITLE
Out Of Memory when allocating big distributed arrays

### ISSUE THREAD

**Issue by samsumas** [chapel-lang/chapel#10344]
Hello,
### Summary of Problem

I get an out of memory error when trying to allocate a "big" distributed array, that is too big for one locale alone. 

### Steps to Reproduce

**Source Code:**
When using this program on one or 2 Locales with n=3 * 1024 * 1024 * 1024 (~3GB per locale), it ends successfully, but when running this program on 4 Locales (each has 8Gb RAM), i get four times :

> big.chpl:7: error: Out of memory allocating "array elements"

Here's the program, it should allocate 3 Gb of memory on every node and write on it.
```chapel
use BlockDist;

config const n = 5;
var space = {1..n * numLocales};
const D : domain(1) dmapped Block(boundingBox=space) = space dmapped Block(boundingBox=space);

var arr : [D] real; //this is line 7 that throws the error

arr = 1.0;
writeln("Array allocating successful!");
```

**Compile command:**
chpl file.chpl

**Execution command:**
./file -nl4 --n=$((3*(1024**3)))

### Configuration Information

- Output of `chpl --version`:
```
chpl version 1.17.0
Copyright (c) 2004-2018, Cray Inc.  (See LICENSE file for more details)
```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: ibv +
  CHPL_GASNET_SEGMENT: large
CHPL_TASKS: qthreads
CHPL_LAUNCHER: gasnetrun_ibv *
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: intrinsics
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
`gcc (GCC) 7.3.0`

**Comment by e-kayrakli** [comment]
I recall seeing similar errors due to misconfiguration that leads to all locales (processes) run on a single node. First thing I'd try to pinpoint the issue would be running your executable with `-v` flag. This should show how the launcher is used and what nodes the job is being run on. 

In my case, the telling thing was that node ids for all the processes were the same. And I forgot to set the `GASNET_IBV_SPAWNER=ssh`

Also, if you are using `gasnetrun_ibv` you should already be inside an allocation, or run it via a qsub file.

**Comment by samsumas** [comment]
oh i see i forgot to post some information : i used `qsub run.sh` to run the program, heres the run.sh script : 
```
#!/bin/bash -l
#
#PBS -l nodes=4:ppn=40,walltime=00:01:00
#
# job name 
#PBS -N testjob
#
# stdout and stderr files
#PBS -o last.out -e last
#
# first non-empty non-comment line ends PBS options
./file -nl4 --n=$((3*(1024**3)))

```
and i had following environment variables for gasnet : 
```
export GASNET_IBV_SPAWNER=mpi
export GASNET_SPAWNFN=C
```

but setting `export GASNET_IBV_SPAWNER=ssh` worked for me, thanks!

But someone should maybe fix the docs at https://chapel-lang.org/docs/latest/platforms/infiniband.html#using-mpi-for-job-launch if `GASNET_IBV_SPAWNER` always has to be set to `ssh` and not `mpi`
![image](https://user-images.githubusercontent.com/13918999/42758680-94e8204a-8904-11e8-8c79-717938ce366c.png)

**Comment by mppf** [comment]
@samsumas - if you see how to improve the documentation, we'd welcome a PR doing so. (If it's not obvious, that documentation is in `doc/rst/platforms/infiniband.rst` if you checkout the project with git.) See also https://chapel-lang.org/contributing.html and https://github.com/chapel-lang/chapel/blob/master/doc/rst/developer/bestPractices/ContributorInfo.rst which cover more details of how to make a 1st PR.

**Comment by samsumas** [comment]
I rechecked and every node has 64 Gb (not 8, my bad) of Ram (but not everything is available with CHPL_GASNET_SEGMENT=large)
