### ISSUE TITLE
Add CI testing to AI workflow

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#10389]
Requirements:

- Execute test runner upon opening / updating a PR
- Execute test running upon merging a PR
- Send notification email upon a merged PR test failing
- Extra credit:
  - To help catch errors due to changes to Chapel vs. changes in the repository (since we're running off master), run the tests on 2 versions each night:
    - 1. The master branch.
    - 2. The last version that passed testing.

**Comment by awallace-cray** [comment]
2018-10-01

Ben says:

> The commands we'd want to try upon testing right now would be:
> ```
> cd chapel-ai/tests/hpo && make tests
> cd chapel-ai/tests/fs && make tests
> ```
> I plan to rename the repo. 
> 

I could get started by just trying the Stash-Jenkins build trigger config.

**Comment by ben-albrecht** [comment]
Migrated to https://github.com/Cray/crayai/issues/63
