### ISSUE TITLE
fields not usable after Module.getRecord()

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#10397]
The following programs do not compile but one might expect them to.

In both cases, an explicit module decorates a function call to a module that is not used (e.g. `C.make_struct()` ). This function returns a record. Following code cannot access the record's field.

 test/classes/ferguson/module-call-returns-type.chpl

``` chapel
module C {
  record my_struct {
    var my_field:c_int;
  }

  proc make_struct():my_struct {
    var ret:my_struct;
    ret.my_field = 0;
    return ret;
  }
}

proc test() {
  var tmp = C.make_struct();
  var f = tmp.my_field;
  writeln(f);
}

test();
```

 test/extern/ferguson/externblock/extern-record-field-scope-issue.chpl

``` chapel
module C {
  extern {
    typedef struct my_struct {
      int my_field;
    } my_struct;

    static my_struct make_struct(void) {
      my_struct ret;
      ret.my_field = 0;
      return ret;
    }
  }
}

proc test() {
  var tmp = C.make_struct();
  var f = tmp.my_field;
  writeln(f);
}

test();
```

**Comment by mppf** [comment]
In both cases, putting a `use C` in the function serves as a workaround.

**Comment by lydia-duncan** [comment]
This seems kinda related to #7857

**Comment by lydia-duncan** [comment]
Are these tests in the process of getting committed to the repository?  I'm not seeing them in my current checkout.

**Comment by mppf** [comment]
they will be added by PR #10398

**Comment by lydia-duncan** [comment]
I've got a branch which should fix them. I'll be sure to double check, though

**Comment by lydia-duncan** [comment]
Well, one of them at least.  Not sure about the extern block

**Comment by lydia-duncan** [comment]
Okay, neither, my change was specifically tied to use statements.

**Comment by mppf** [comment]
Ah, yes, these don't have use statements. (They used to, but I removed that...).
Since 'use only;' doesn't add any meaningful symbols, maybe we could put back the normalization change but instead of adding a new block it could add 'use only' to the parent block?

**Comment by mppf** [comment]
There's probably a better way, though...

**Comment by lydia-duncan** [comment]
That was my first thought as well.  I'll muse on it a little more and if I don't think of anything better will probably just follow that path

**Comment by mppf** [comment]
Ideally, ScopeResolve and Resolve would know how to work with module decorators like this directly.
