### ISSUE TITLE
Allow minloc, maxloc as reduce intents

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#10404]
We want minloc, maxloc as reduce intents, for uniformity.
Right now a minloc intent crashes the compiler:

```chpl
var opt: 2*int;
forall (val,idx) in zip(A,A.domain) with (minloc reduce opt) {
  opt = (val,idx); // see reduce= below
}
```

gives me INT_ASSERT in callDestructors.cpp:681.

We really want `reduce=` instead of `=` in the above.
For that, we simply need to add accumulateOntoState to our
minloc, maxloc classes in ChapelReduce.chpl.
That does not affect the above assertion, though.

A related issue is that we want a useful error message
when the type of `opt` above is incorrect. Right now
we'd get `unresolved access of 'int(64)' by '(1)'`.

**Comment by bradcray** [comment]
Until these are supported, it'd be nice to get a better error message if that was low-hanging fruit.

**Comment by vasslitvinov** [comment]
Works on my branch now.
