### ISSUE TITLE
Github label refresh

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#10401]
For those who care about GitHub labels...  As we continue to work with them, I find myself wondering...

* whether we should change the "area: Modules" tag to "area: Libraries" just because I think it's more descriptive
* whether we should have an "easy issue" label in addition to "good first issue" (because I think something could be easy for us without being a good first issue for someone new to the project)
* whether we could add a "be Brad's hero" label as a way for me to flag things that I'd love to see receive some attention.  :)  Or if that's too ego-centric, whether we could have a general "be my hero" issue for devs to put on things that they'd really like to advocate for (e.g., as a means of bringing them to attention to other devs).  I'm thinking of this as something to look for along with "user issue" in any given sprint planning preparation.

**Comment by lydia-duncan** [comment]
> "be my hero"

I've typically used 👍 or 🎉  reactions on the description itself to indicate that (which has the benefit of showing if multiple people feel that way versus just one person)

**Comment by lydia-duncan** [comment]
I'm in favor of the other two proposals

**Comment by bradcray** [comment]
> but could you just put things like this into the backlog as an indication that it should receive attention sooner rather than later?

Have you seen how many things are in the backlog?  :)

**Comment by lydia-duncan** [comment]
I might be tempted to add a "quality of life" label

**Comment by bradcray** [comment]
I implemented the first two proposals here (calling the second easy / straightforward so that it would sort near "good first issue" in the list) and didn't feel there was enough support for the third, so am closing this issue.
