### ISSUE TITLE
String initializer for taking ownership

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#10410]
String.chpl includes initializers for taking ownership of a C string. Since strings generally are allocated by whatever is filling them in, it's common for code interacting with C (including the C runtime) to want to create Chapel strings from a C string - including taking ownership of the buffer.

This string initializer supports this pattern:

https://github.com/chapel-lang/chapel/blob/6482aaf58cc01d687849d22c93e5fa4dd5745ee7/modules/internal/String.chpl#L226-L227

However I find it hard to reason about the interaction of `isowned` and `needToCopy`. (Besides that isowned is improperly camel-cased..). This issue is proposing that we publicize instead a new method or function that just does the right thing in this situation and has an appropriate and memorable name.

It might be:

``` chapel

proc string.retain(cs:c_string, length: int = cs.length)

proc string.reset(cs:c_string, length: int = cs.length)

proc string.take(cs:c_string, length: int = cs.length)

proc createStringOwning(cs:c_string,  length: int = cs.length)

proc type string.take(cs:c_string, length: int = cs.length)
```

**Comment by mppf** [comment]
@benharsh - wondering your opinion on this issue

**Comment by benharsh** [comment]
I do think it would be better to have some different and more explicit means of handling c strings.

I think we should also consider whether we want to allow simple casts from c_string to string, or if we want to require users to think about the c_string's ownership by calling one of these methods instead of a cast.

I'm partial to type methods over standalone functions for this case.

**Comment by mppf** [comment]
> I think we should also consider whether we want to allow simple casts from c_string to string, or if we want to require users to think about the c_string's ownership by calling one of these methods instead of a cast.

The casts are OK but might leak memory if they always copy. I suppose you're saying "But a memory leak is a bad problem, so users should have to explicitly say copy or take" ?

**Comment by benharsh** [comment]
> I suppose you're saying "But a memory leak is a bad problem, so users should have to explicitly say copy or take" ?

At least in this case, yeah.

**Comment by e-kayrakli** [comment]
@mppf and/or @benharsh can this be closed?

**Comment by mppf** [comment]
@e-kayrakli - yeah but you might want to link to the PR / issue that you did that adds functions along the lines of createStringOwning.

**Comment by e-kayrakli** [comment]
https://github.com/chapel-lang/chapel/pull/13914 added string/bytes factory functions that does specific ownership transfers.
