### ISSUE TITLE
Improve support for enums within scoped contexts

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#10433]
As a Chapel programmer, I want to use enums within scoped contexts (functions, classes, etc.) without penalty because it represents a natural composition of language concepts.  At present, several cases in which enums are used in scoped contexts result in problems (issues #6871, #7861, #10409), and likely others remain as well.  Some of these relate to general scope resolution fragility within the compiler; others relate to the compiler trying to determine param integer values for enum symbols (related to #10115).

Acceptance criteria:
* Enums can be used within scoped contexts without problems

**Comment by DanilaFe** [comment]
All the issues in this epic are completed. The one issue mentioned in the OP that isn't completed (https://github.com/chapel-lang/chapel/issues/10115) is tracked in https://github.com/chapel-lang/chapel/issues/10434 instead. Closing.
