### ISSUE TITLE
Add deprecation warning for user constructors

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#10457]
Given a program like the following:

```chpl
/*  1 */ class C {
/*  2 */   var x : int;
/*  3 */
/*  4 */   proc C(x : int) {
/*  5 */     this.x = x;
/*  6 */   }
/*  7 */ }
/*  8 */
/*  9 */ proc C.C(s : real) {
/* 10 */   this.x = s:int;
/* 11 */ }
/* 12 */
/* 13 */ var c = new C(1.5);
```

We want the compiler to emit a deprecation warning on lines 4 and 9.

### Initial proposal
Compiler emits the following for each occurrence of a constructor:
``Type '%s' defines a constructor here``

For the first warning only, the compiler will print the following note:
``Constructors have been deprecated as of Chapel 1.18. Please use initializers instead.``

For the program above, the total compiler output would be:
```
foo.chpl:4: note: Constructors have been deprecated as of Chapel 1.18. Please use initializers instead.
foo.chpl:4: warning: Type 'C' defines a constructor here
foo.chpl:9: warning: Type 'C' defines a constructor here
```

**Comment by vasslitvinov** [comment]
Looks good! My suggestions are:

* Use "defines" instead of "defined".

* Start the "note" with the key point, "constructors have been deprecated". I propose:
```
Constructors have been deprecated as of Chapel 1.18. Please use initializers instead.
See (appropriate URL) for details.
```

**Comment by lydia-duncan** [comment]
You've probably already thought of this, but I would also hope that
```chapel
/*  1 */ class C {
/*  2 */   var x : int;
/*  3 */
/*  4 */   proc C(x : int) {
/*  5 */     this.x = x;
/*  6 */   }
/*  7 */ }
/*  8 */
/*  9 */ class D {
/* 10 */   var y: real;
/* 11 */ 
/* 12 */   proc D(y: real) {
/* 13 */     this.y = y;
/* 14 */   }
/* 15 */ }
/* 16 */
/* 17 */ var c = new C(4);
/* 18 */ var d = new D (1.0);
```
Would generate:
```
foo.chpl:4: warning: Type 'C' defined a constructor here
foo.chpl:4: note: As of Chapel 1.18 constructors have been deprecated and replaced by initializers
foo.chpl:12: warning: Type 'D' defined a constructor here
```

**Comment by benharsh** [comment]
@vasslitvinov : I like your suggestions (not sure about the URL though), and will update the issue.
