### ISSUE TITLE
Write a new setenv script to respond to #9551 (new scripts to build customizable Cray module from source)

### ISSUE THREAD

**Issue by awallace-cray** [chapel-lang/chapel#10461]
Write a new build_configs.py setenv script that we can use as a starting point for the external users envisioned in #9551, using the following:
1. https://github.com/chapel-lang/chapel/issues/10120 - build_configs.py changes to work with "Chapel Cray module build script"
2. https://github.com/chapel-lang/chapel/issues/10109 - Working version of "Chapel Cray module build script"
3. https://github.com/chapel-lang/chapel/issues/10119 - Working version of "Chapel Cray module packaging script"

The deliverable will work on a Cray-internal machine.

**Comment by awallace-cray** [comment]
We agreed to implement a setenv-example-3.bash in response to #9551 without yet completing the Cray module packaging script. 
Implemented in https://github.com/chapel-lang/chapel/pull/10663

**Comment by ben-albrecht** [comment]
Apologies if this has been discussed elsewhere already (I didn't see it) : Do we plan to enable some form of nightly testing on `build_configs.py` and friends?

**Comment by bradcray** [comment]
Right: The testing will be our own continual use of them in our own BTR workflow.  Personally, I'd like to see this happen by 1.18.0 rather than long-term.

**Comment by awallace-cray** [comment]
> Personally, I'd like to see this happen by 1.18.0 rather than long-term.

Even if this all looked fully-baked in time, I wouldn't advise using it for 1.18.0. Risk of undetected changes in the released RPMs.

**Comment by awallace-cray** [comment]
Looks like a full story-point-day was spent on improving the README and embedded commentary. 
Personally, I like the result a lot better.
