### ISSUE TITLE
extern procs declared at record/class scope called with `this` argument

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#10466]
We insert a `this` argument to extern procs declared at record/class scope. e.g the following:

```chpl 
record R {
  extern proc extern_foo(i: c_int): c_int;
  proc foo(i: int): int {
    return extern_foo(i:c_int): int;
  }
}

var r: R;
writeln(r.foo(0));
```

```c
static inline int extern_foo(int i) { return i+1; }
```

fails at c compile time with:

```
error: too many arguments to function call,
      expected single argument 'i', have 2 arguments
call_tmp_chpl = extern_foo(this_chpl, ((int32_t)(i_chpl)));
```

It seems like a bug that we insert an implicit `this` for extern procs. It's not obvious to me what the right behavior is for exported procs though.

**Comment by ronawho** [comment]
And note that things work if the extern proc is declared inside a method. Here's a more comprehensive listing of what cases do and do not work:

```chpl
record RIn {
  proc foo(i: int): int {
    extern proc extern_foo(i: c_int): c_int;
    return extern_foo(i:c_int): int;
  }
}

record ROut {
  extern proc extern_foo(i: c_int): c_int;
  proc foo(i: int): int {
    return extern_foo(i:c_int): int;
  }
}

record CIn {
  proc foo(i: int): int {
    extern proc extern_foo(i: c_int): c_int;
    return extern_foo(i:c_int): int;
  }
}

record COut {
  extern proc extern_foo(i: c_int): c_int;
  proc foo(i: int): int {
    return extern_foo(i:c_int): int;
  }
}

// works
{
  extern proc extern_foo(i: c_int): c_int;
  writeln(extern_foo(0));
}

// works
{
  var r: RIn;
  writeln(r.foo(1));
}

// doesn't work today
{
  var r: ROut;
  writeln(r.foo(2));
}

// works
{
  var c = new CIn();
  writeln(c.foo(3));
}

// doesn't work today
{
  var c = new COut();
  writeln(c.foo(4));
}
```

**Comment by ronawho** [comment]
cc'ing @mppf just because of your recent work with extern procs.

**Comment by cassella** [comment]
Should `record CIn` and `record COut` be classes?

**Comment by mppf** [comment]
@ronawho - I'd think `extern proc` inside a `record` or `class` declaration should either make a method or be an error.

It might seem like nonsense, but the following *does* have a reasonable interpretation:
``` chapel
record R {
  extern proc mymethod();
}
var r:R;
r.mymethod();
```

I think such behaviors will be particularly important when we get to supporting C++ interoperation.

**Comment by mppf** [comment]
Making it not add the this argument for a non-extern record/class is also reasonable.

**Comment by ronawho** [comment]
Hmm, that's not quite right at least for the use-case I'm trying to use this for with cleaning up the Atomics.chpl implementation. There I'm using types that are fields in the record and those aren't visible with the above patch. 

i.e. I'm trying to do something more like:

```chpl
record R {
  type externType = c_int;
  extern proc extern_foo(i: externType): externType;
  proc foo(i: int): int {
    return extern_foo(i:externType): int;
  }
}

var r: R;
writeln(r.foo(0));
```

which fails with the above patch with:

```
f.chpl:3: In function 'extern_foo':
f.chpl:3: error: 'externType' undeclared (first use this function)
```

So maybe what I'm trying to do here is sufficiently weird, and I should just stick with declaring the extern routines inside the methods and not worry about duplicating the extern decls

**Comment by lydia-duncan** [comment]
> do we have private extern procs?

I believe so.  I don't think there's a test of it specifically (at least, I'm not finding one), but ordinary functions can be private (just not methods) and the parser doesn't prevent it for extern procs.

**Comment by ronawho** [comment]
The original motivation for this was for cleaning up the atomics module. What we do currently is something like: 

```chpl 
record AtomicT {
  type T;
  var _v:externT(T);

  proc fetchAdd(value:T): T {
    extern externFunc("fetch_add", T)
      proc atomic_fetch_add(ref obj:externT(T), operand:T): T;

    var ret:T;
    on this do ret = atomic_fetch_add(_v, value);
    return ret;
  }

  proc add(value:T): void {
    extern externFunc("fetch_add", T)
      proc atomic_fetch_add(ref obj:externT(T), operand:T): T;

    on this do atomic_fetch_add(_v, value);
  }
}
```

and I wanted to avoid the duplicated declaration of extern `fetch_add`. The extern is computed based on the basetype T, so you can't move the declaration outside the record itself.

i.e. I wanted something like: 

```chpl 
record AtomicT {
  type T;
  var _v:externT(T);

  extern externFunc("fetch_add", T)
    proc atomic_fetch_add(ref obj:externT(T), operand:T): T;

  proc fetchAdd(value:T): T {
    var ret:T;
    on this do ret = atomic_fetch_add(_v, value);
    return ret;
  }

  proc add(value:T): void {
    on this do atomic_fetch_add(_v, value);
  }
}
```

That said, I'm willing to accept the argument that even though it's an extern method, it should still have `this`. I was originally only thinking of C interop where an actual extern method doesn't make sense, but now that we're expanding our extern/interop support the desire for an actual extern method seems more possible.
