### ISSUE TITLE
Remaining release/examples memory leaks

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#10508]
Switching to initializers by default (https://github.com/chapel-lang/chapel/pull/10459) resolved memory leaks for SSCA#2, which had been the single largest leak across the entire test suite.

![leaks](https://user-images.githubusercontent.com/1588337/43201760-627de128-8fe7-11e8-94f3-2aeab5f0d12d.png)

Now that the SSCA leak has been resolved we're down to 10 tests and only ~2,000 bytes being leaks for release/examples. That's tantalizingly close to having leak free example tests so I wanted to characterize the remaining leaks: 

User leaks (unmanaged domain maps):

 - [x] hpl.chpl
 - [x] distributions.chpl

Anonymous module-level arrays-of-arrays leak (#5660):

 - [x] isx.chpl
 - [x] meteor.chpl
 - [x] opaque-domains.chpl
 - [x] arrays.chpl
 - [x] decl-with-anon-domain.chpl
 - [x] meteor-fast.chpl

Anonymous module-level array type alias leak (possibly #5660 too):

 - [x] typeAliases.chpl

**Comment by bradcray** [comment]
Just noting that there are [a lot of open issues](https://github.com/chapel-lang/chapel/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+leaks+in%3Atitle) that try to characterize / categorize leaks opened by @benharsh and others which may be of use, or perhaps should be re-evaluated in an initializers-based world/

**Comment by bradcray** [comment]
The remaining cases relate to issue #12732.
