### ISSUE TITLE
Assertion failed from chpl_memcpy for multi-locale executions

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#10500]
### Summary of Problem
Code creates an array of records and does a single element assignment to self. On multi-locale executions, this runtime error is asserted:
```
chpl_memcpy: Assertion `dest != src || num == 0' failed.
*** Caught a fatal signal SIGABRT(6) on node 0/4
```
Single-locale executions are not affected.

### Steps to Reproduce

**Source Code:**

```chapel
module MemcpyTest {
  record R {
    var x: int;
  }
  proc main() {
    var data: [0..#10] R;
    data[5] = data[5];
    writeln(data);
  }
}
```

**Compile command:**
- For single-locale, assertion does not occur.
- For multi-locale, assertion does not occur if `--fast`.
  - No options will cause the assertion.

### Configuration Information
- `chpl version 1.18.0 pre-release (6e8996b7c9)`
- `CHPL_COMM=gasnet`
- `CHPL_COMM_SUBSTRATE=smp` [Emulating multi-locale, but repro'd on ibv conduit too.]

**Comment by mppf** [comment]
This is related to PR #759 and PR #1410.

**Comment by ronawho** [comment]
I think we need to examine everywhere where we currently call `memcpy` in the runtime and evaluate if overlap is possible and if so switch to `memmove`. Converting `chpl_gen_comm_get()`/`chpl_gen_comm_put()`  to use `memmove` resolves it for this case, but there are likely other cases where we get this wrong. (e.g. we just ran into this while working on https://github.com/chapel-lang/chapel/pull/11206)

There are potential performance considerations here (memmove _might_ be more expansive that memcpy on some platforms) but I think memmove should be our default and we should only switch to memcopy if we run into performance issues or have cases where we are confident there is no overlap.

**Comment by ronawho** [comment]
This should be resolved with https://github.com/chapel-lang/chapel/pull/11565, which converted calls to memcpy where overlap is possible to memmove.
