### ISSUE TITLE
Chapel master Docker image?

### ISSUE THREAD

**Issue by tjstavenger-pnnl** [chapel-lang/chapel#10510]
We’re developing against features in the 1.18 pre-release found in the master branch. We had been building on GitlabCI using https://hub.docker.com/r/chapel/chapel/, but since we’ve switched to master the builds are failing as the available Docker images are only for releases. 
 
I could pretty easily make my own Docker image against master, but it would be nice to have an official one. Would it be possible to add a new image that gets updated periodically from master (on commit, nightly, or some other schedule)?

**Comment by ben-albrecht** [comment]
Design Q: What frequency would work best? 

I imagine building nightly images would be easiest implementation-wise.

@awallace-cray seems like the right person to tackle this.

**Comment by tjstavenger-pnnl** [comment]
How often do your Travis CI builds run? It looks like they're running on commit (which is normally how they work)?

Anyone developing against master would have to expect frequent changes, but some stability through the day would probably be welcome. Anyone needing the latest & greatest would have to wait at most a day. Unless someone is actively working on Chapel & their own code simultaneously, I would think nightly should be acceptable.

**Comment by ben-albrecht** [comment]
> How often do your Travis CI builds run? It looks like they're running on commit (which is normally how they work)?

We run Travis CI sanity checks upon commits, Jenkins smoke tests on 1 configuration post-merge, and Jenkins full testing over all configurations nightly.

**Comment by tjstavenger-pnnl** [comment]
Ah, so it seems best to rebuild a chapel/chapel:master docker image nightly after you know the Jenkins build has passed. I suspect someone wouldn't want to use a non-functional Chapel Docker image.

**Comment by tjstavenger-pnnl** [comment]
I forked Chapel so I could add the Dockerfile and use it while we wait for the feature to be included within Chapel itself. See https://github.com/tjstavenger-pnnl/chapel/blob/master/util/dockerfiles/master/Dockerfile

I had thought I'd be able to copy/paste your other Dockerfile and modify it to pull from master instead.

I can successfully create the image, but running ``start_test`` outputs this: 

> perl: warning: Setting locale failed.
> perl: warning: Please check that your locale settings:
> 	LANGUAGE = (unset),
> 	LC_ALL = (unset),
> 	LC_COLLATE = "C",
> 	LANG = "en_US.UTF-8"
>     are supported and installed on your system.
> perl: warning: Falling back to the standard locale ("C").

Do you modify the Docker image after building the Dockerfile to correct this?

**Comment by awallace-cray** [comment]
> Do you modify the Docker image after building the Dockerfile to correct this?

No, but the last time I used the Dockerfile was for the last release.
At a guess, we probably need to tweak the Dockerfile for the next release.

**Comment by tjstavenger-pnnl** [comment]
Seems like a bit of a kludge, but StackExchange to the rescue! I forced the local to en_US.UTF-8 and now I don't get the perl warnings.

* https://serverfault.com/questions/362903/how-do-you-set-a-locale-non-interactively-on-debian-ubuntu
* https://serverfault.com/questions/362903/how-do-you-set-a-locale-non-interactively-on-debian-ubuntu#801162

I also set the debian image to v9.4 as it looks like that is what was released back when Chapel 1.17 was released. The debain:stretch image has since changed to v9.5.

I'll get a pull request put together for you.

**Comment by tjstavenger-pnnl** [comment]
See https://github.com/chapel-lang/chapel/pull/10570

**Comment by awallace-cray** [comment]
tjstavenger-pnnl - thank you for the updates and the reminder.

**Comment by riftEmber** [comment]
With https://github.com/chapel-lang/chapel/pull/20705 merged, the Dockerfile in the source root can now be used to build from latest code (or any commit you choose). To achieve a gasnet build, one can use the official gasnet Dockerfile in `util/packaging/docker/gasnet`, basing it off of the base Chapel image built from whatever version of the code is desired.

**Comment by bradcray** [comment]
@riftEmber : Do you think this issue can be closed now?  (or maybe could've / should've been when #10570 was merged?)  Or if not, what would you say needs to be done to consider it done?

**Comment by riftEmber** [comment]
The reason I’ve left it open is that the OP requests an official *image* built from latest code, whereas what we’ve provided (and was previously provided by #10570, slightly differently) is an official *Dockerfile* capable of building an image from any version of the code. The door is still open for us to do something like publishing an official nightly Docker image from the CI, which I think is an idea worth considering.

**Comment by riftEmber** [comment]
The reason I’ve left it open is that the OP requests an official *image* built from latest code, whereas what we’ve provided (and was previously provided by #10570, slightly differently) is an official *Dockerfile* capable of building an image from any version of the code. The door is still open for us to do something like publishing an official nightly Docker image from the CI, which I think is an idea worth considering.

**Comment by riftEmber** [comment]
Consideration of an official nightly Docker image is now tracked in https://github.com/Cray/chapel-private/issues/4632 and not currently prioritized. As mentioned in https://github.com/chapel-lang/chapel/issues/10510#issuecomment-1265630457, our primary Dockerfile can now be used to build an image from whatever version of Chapel is desired down to commit granularity. We may revisit publishing an official nightly image if/when we have a method for identifying "good" nightly builds, but as we don't have that at the moment it is left up to users to decide what SHA they want to work off of.

With this I think all concerns from this issue are addressed, so I will close it.
