### ISSUE TITLE
Memory leak when pop_front pops last element in array

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#10520]
Consider the following program:
```chpl

class C {
  var x : int;
}

record R {
  var c : C;
  proc init() { }
  proc init(x:int) {
    c = new C(x);
  }
  proc init(other:R) {
    this.c = new C(other.c.x);
  }
  proc deinit() {
    if c != nil then delete c;
  }
}

proc =(ref LHS : R, rhs : R) {
  if LHS.c then delete LHS.c;
  LHS.c = new C(rhs.c.x);
}

proc main() {
  var A = for i in 1..4 do new R(i);

  // A copy of R(4) is leaked
  while A.size > 0 do A.pop_front();
}
```

In this program, a copy of the last element "R(4)" is made during the final pop_front but is never deinitialized.

If I compile with ``-sdebugArrayAsVec`` and run with ``--memLeaks`` I observe the following output:
```
pop_front reallocate: 1..4 => 3..4 (5..4)

=================================================================================================================
Allocated Memory (Bytes)         Number   Size     Total    Description                      Address             
=================================================================================================================
foo.chpl:22                      1        16       16       C                                0x00007fc501d01a10  
=================================================================================================================
```

The second range (3..4) printed by pop_front debugging seems incorrect. This is the range passed to ``dsiReallocate``, but it is non-zero in length despite the new indices 5..4 being non-zero in length. I suspect this means we do not attempt to deinitialize array elements when ``A`` is finally destroyed.

**Comment by bradcray** [comment]
@benharsh: You labeled this as a modules bug...  How confident are you that that's correct (i.e., that it's not a compiler bug?).  Maybe put another way: Is this something that @daviditen could/should fix as the author of `pop_front()` or does it require someone fixing memory management of records in general?  Or do we need someone to dig into it to figure that out?  Thanks.

**Comment by benharsh** [comment]
I think the bug is due to incorrect math in the module code. I'm not 100% sure, but the new ranges for the internal and top-level indices look wrong to me, and the compiler wouldn't have control over those.

I think someone familiar with the ``pop_front`` implementation (@daviditen or whoever) should investigate further and verify.

**Comment by ian-bertolacci** [comment]
I have a program where *all* the listNodes leak:
```
proc foo( N : int ){
  var l : list(int);
  for i in 1..#N do l.push_back( i );

  while l.size > 0 {
    var v = l.pop_front();
  }
}

config const N = 3;

proc main(){
  foo(N);
}
```

which gives the following when run with `--memLeaks`
```
=================================================================================================================
Allocated Memory (Bytes)         Number   Size     Total    Description                      Address             
=================================================================================================================
test.chpl:6                      1        24       24       listNode(int(64))                0x00007f28502e2240  
test.chpl:6                      1        24       24       listNode(int(64))                0x00007f28502e2220  
test.chpl:6                      1        24       24       listNode(int(64))                0x00007f28502e2200  
=================================================================================================================
```

as a quick fix I modified `pop_front` to delete `oldfirst` right before the return ([see return line of pop_front](https://github.com/chapel-lang/chapel/blob/master/modules/standard/List.chpl#L197)) and I seem to have fixed all my leaks.

**Comment by daviditen** [comment]
> I have a program where all the listNodes leak:

That's a good catch, but I think it is unrelated to this issue.  This issue is about `Array.pop_front()` which is independent of `list.pop_front()`.
