### ISSUE TITLE
Internal error when using lambda defined in function that accepts generic domain

### ISSUE THREAD

**Issue by ian-bertolacci** [chapel-lang/chapel#10521]
The following code fails to compile under 1.17.1 (and master at around c1acda2) giving the internal error PRE1599.
```chapel
proc foo( arg : domain ){
  var bar = lambda( i : int ) : int { return 1 - i; };

  for i in arg do writeln( bar( i ) );
}

foo( {1..10} );
```
[TIO](https://tio.run/##LY0xDsMgFEN3TuERhkZlLephSCAtEuFHX7QdEGenn6qDZcmyn7enP2Me42TasBNpeH7ghkCHTwWmKeDtGavojuyPNXiNJI1UKszfGzjWFxdYXJAculOy24mlKZSJDIQPpxpz0RM2GQbGqa7U77bZZbHXLtEYXw)

Using a complete domain type (e.g. `domain(1)`) does not cause the error ([See TIO](https://tio.run/##LY0xDsMgFEN3TuERhkZlLephfgJpkQg/@qLtgDg7IVEHy5JlPy9v2kPqfRdesDJrkLzwgOeNYtbWwFQFfEkwDz2RaJs9acRRirnA/L1CQvlIhsUN0aE5NXYry2jGfFE94yexhJT1CTsZA@9UU@p6rnaa7L2NqPcD)).
Further, using a default range type as an argument (i.e. `proc foo( arg : range )` does not cause the error ([See TIO](https://tio.run/##LY2xDoMwEEP3@wqPyVDUrET9mAMCPSkk6JS2A@LbQ0AdLEuW/Ty@eQux1k3ziDlnA9YFPZTTEmB3Ar6sGJpeiLwOExtIK0gqsH/foaF8NMHhAfE4PLXdnLU1Jd3EKeOnUkJM5oJdDAvr6SC6X13XuWcLaj0B))

**Comment by bradcray** [comment]
Thanks for filing this (bonus points if you add a future! :) ).  

I'm guessing that the difference between the behavior for the `domain` and `range` cases is that `range` is a generic type for which all generic fields have a default, and is therefore concrete.  That is, you can say:

```
var r: range;
```

whereas `domain` does not specify a fully instantiated type, so only implies a type constraint, not a concrete type.  My guess is that we'd see a similar error if we had a generic class or record:

```chapel
record R {
  type t;
}
```

and took `R` in as the argument.

Speculating further, I'd guess that the pass that creates first-class functions is trying to capture all closed variables as fields, like `arg`, but can't create a field of generic type.  This raises questions for me as to whether procedure-local first-class functions are running too early and should wait until after the enclosing function has been instantiated.

**Comment by cassella** [comment]
The original code here compiles and runs now,

```
0
-1
-2
-3
-4
-5
-6
-7
-8
-9
```

**Comment by cassella** [comment]
If @bradcray 's analysis is correct, the test `test/functions/lambda/NestedLambdaInGenericFn.chpl` is probably covering this case.  It was added by #20554 which plausibly is what fixed this issue.
