### ISSUE TITLE
Shape preservation for (serial) for-expressions?

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#10538]
Should for-expressions preserve the shape?
Our answer is "yes" for forall-expressions, which are parallel.
Cf. for-expressions are serial.

For example:
```chpl
var S = {1..8,1..8};
var A = for S do read(int);
writeln(A.domain);   // should this be {1..64} or {1..8,1..8} ?
```

[Added 7/26] How about (parallel) forall-expressions over ranges?

For example:
```chpl
var A = [idx in -1..1] idx;
writeln(A.domain);   // {-1..1} or {1..3} ?
```

**Comment by bradcray** [comment]
I think that the shape should be preserved for serial for expressions as well as parallel ones for consistency and to avoid surprises when converting between parallel and serial code.  Do you have arguments in mind for doing differently?

For your second case:

```chapel
var A = [idx in -1..1] idx;
writeln(A.domain);   // {-1..1} or {1..3} ?
```

I think that the domain should be `{-1..1}` to match the case in which we sugar creating an array over a range: `var A: [-1..1] int;`

**Comment by bradcray** [comment]
@vasslitvinov : What's the level of effort required for this?  Would it round out the shape preservation features / story for the upcoming release or are there other issues open that capture other things that don't yet work as we'd like?  Thanks.

**Comment by vasslitvinov** [comment]
@bradcray : should be a modest effort, worth a 1-point spike for a more precise estimate.

>  Would it round out the shape preservation features / story for the upcoming release or are there other issues open that capture other things that don't yet work as we'd like?

Perhaps the best resource for the answer is [the Shape Preservation epic on ZenHub](https://app.zenhub.com/workspace/o/chapel-lang/chapel/issues/10234), currently:

Backlog:
#10238 Handle nested forall-expressions - 1
#10480 Handle nested forall-expressions - 2
#10239 Ensure test coverage for shape preservation
#10282 forall loop over forall expr over zip(A,B) ?
#10376 Forall expression failures under valgrind - 2
#10477 Forall expression failures under valgrind - 1
#10538 Shape preservation for (serial) for-expressions (this issue)
#10240 Design: passing a shapeful expression as a function argument

Icebox:
#7777 Initializing a variable from forall expressions is serial
#10235 Convert the shape field to store a domain1
#10301 performance with shape preservation
#10325 Effect of adjusting a shape-preserved domain
#10359 "Shape" of an iterator / promoted expr / forall-expr a user-facing feature?
