### ISSUE TITLE
"use only" prevents visibility through _defaultOf

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#10547]
Related #9983 
Related #7857

### Steps to Reproduce
When using `use A only`, this error is emitted:
```
In function 'main':
error: unresolved call '_defaultOf(type R(int(64)))'
```

If `only` is omitted, the program compiles.

**Source Code:**

```chapel
module A {
  record R {
    type t;
  }
}

proc main() {
  use A only;
  var r: A.R(int);
}
```

### Configuration Information
`chpl version 1.18.0 pre-release (d2735623e9)`

**Comment by lydia-duncan** [comment]
On it, thanks for reporting!
