### ISSUE TITLE
Multilocale programs won't start on other servers

### ISSUE THREAD

**Issue by Gesp2613** [chapel-lang/chapel#10571]
I'm getting familiar with Chapel, but encountered some problems that I can't solve.

I've got 2 identical servers, each with 2x E5-2630 v3 and 32GB RAM, connected with InfiniBand.

To compile Chapel 1.17.1 I set following environment variables:
```
export CHPL_TARGET_ARCH=haswell
export CHPL_COMM=gasnet
export CHPL_COMM_SUBSTRATE=ibv
export CHPL_COMM_LAUNCHER=gasnet_ibv
export GASNET_SSH_CMD=ssh
export GASNET_SSH_SPAWNER=ssh
export GASNET_SSH_OPTIONS=-x
export GASNET_SSH_SERVERS="node19 node20"
export GASNET_SPAWNFN=S
```
Now when I compile the `hello6-taskpar-dist.chpl` and run it with `GASNET_PHYSMEM_MAX=20G ./hello -nl 2` the output tells me that both spawned locales are running on node19; node20 doesn't get used. To check if that is really the case, I wrote a simple program that does some calculations for a time and looked at the cpu load on both servers, and indeed both locales get spawned on node19.

Just a side note: If i don't supply the compiled Chapel programs with the `GASNET_PHYSMEM_MAX`-variable and it runs its "potentially slow probe" it just fills the memory completely, and causes a load of 100% on all cpu cores of node19 to the point it gets unresponsive, and the program crashes after some time.

Quick help would be really appreciated.

**Comment by ronawho** [comment]
https://chapel-lang.org/docs/platforms/infiniband.html may be useful if you haven't seen that documentation already. 

Some of the env var names look a little off. I think it should be:

 - `CHPL_COMM_LAUNCHER=gasnet_ibv ` => `CHPL_LAUNCHER=gasnetrun_ibv`
 - `GASNET_SSH_CMD=ssh` => `GASNET_IBV_SPAWNER=ssh` (GASNET_SSH_CMD may work too, but I've only ever used that one for the udp conduit)

If that doesn't help, can you provide the output of `$CHPL_HOME/util/printchplenv --anonymize`?  You can also try running the program with `-v` or `--verbose` to see the exact command that's being used to launch.

For `GASNET_PHYSMEM_MAX` and the probing there's some info in that infiniband documentation I linked to, and https://github.com/chapel-lang/chapel/blob/master/third-party/gasnet/gasnet-src/ibv-conduit/README has a lot more details.

**Comment by Gesp2613** [comment]
Thank you very much, I had read this page so many times yesterday but apparently everytime I've overlooked the SSH-section.
Replacing the env vars did it.
