### ISSUE TITLE
Add official cray-cs nightly testing

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#10607]
Currently, we test on a `cray-cs` system nightly, but treat it as a linux cluster (`CHPL_HOST_PLATFORM=linux64`) with infiniband (`CHPL_COMM_SUBSTRATE=ibv`) network.

It would be nice to add testing for `CHPL_HOST_PLATFORM=cray-cs` on the variety of networks that we have available on internal machines.

**Comment by ben-albrecht** [comment]
Motivated by recent issue encountered on `cray-cs`: https://github.com/chapel-lang/chapel/issues/10539

**Comment by ben-albrecht** [comment]
Probably relevant to @awallace-cray

**Comment by ronawho** [comment]
I think this is done now that we have cray-cs performance testing. We run gasnet-ibv segment fast and large, as well as gasnet-mpi and ofi: https://chapel-lang.org/perf/16-node-cs/
