### ISSUE TITLE
problem with initializer initializing field from this

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#10606]
``` chapel
class MyClass {
  var i:int;
}

class MyGenericClass {
  var mx;
  var i;
}

proc MyGenericClass.init(x) {
  this.mx = x;
  this.i = this.mx.i;
  // this seems to work: this.i = x.i;
}

var x = new unmanaged MyGenericClass(new unmanaged MyClass(1));
writeln(x);

delete x.mx;
delete x;
```

```
x.chpl:10: In initializer:
x.chpl:12: internal error: CAL0124 chpl version 1.18.0 pre-release (91da8ff5d8)

Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug -- 
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.

```

```
x.chpl:10: In initializer:
x.chpl:12: internal error: the type of the actual argument 'this' is generic [callInfo.cpp:124]
```

**Comment by mppf** [comment]
@benharsh - I ran into this problem when working on PR #10558

**Comment by benharsh** [comment]
The problem here is that the AST going into resolution transforms the 'this.mx' portion of the problematic line into a method call. Resolution doesn't work with methods on non-instantiated types, and so blows up.

A solution doesn't seem readily obvious to me, but I'll keep looking.

**Comment by mppf** [comment]
Some ideas:
 * stop converting this.mx into method calls generally
 * or in `proc init`
 * or make resolution identify this pattern in certain initialization statements & un-do it

**Comment by benharsh** [comment]
Ah: we already have some parts of initializer-specific normalization that undo this pattern, but are limited to expression involved in field initialization. I think the right path forward is to update InitNormalize/initializerRules to apply these transformations to all expressions (at least in phase 0/1).
