### ISSUE TITLE
Compiling Multilocale with MPI and intel compilers

### ISSUE THREAD

**Issue by SwetaYamini** [chapel-lang/chapel#10624]
Summary:
A way to override mpicc and mpicxx from environment flags to compile multilocale chapel using MPI conduit and intel compilers (with intel MPI).

Details:
When compiling  Chapel-1.17.1 with the settings

export CHPL_HOST_COMPILER=intel
export CHPL_TARGET_COMPILER=intel
export CHPL_COMM=gasnet
export CHPL_COMM_SUBSTRATE=mpi
export CHPL_LAUNCHER=gasnetrun_mpi

and environment

$ util/printchplenv --anonymize
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: intel *
CHPL_TARGET_ARCH: unknown
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: mpi *
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: gasnetrun_mpi *
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: intrinsics
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none

gives a warning and eventually fails to compile.

configure: WARNING: The compiler families of $CC and $MPI_CC do not match:
      CC:  COMPILER_FAMILY:INTEL	COMPILER_VERSION:1800.20170811
  MPI_CC:  COMPILER_FAMILY:GNU	COMPILER_VERSION:4.9.2
If this is not what you intended, then set $MPI_CC to select a different MPI compiler.
.....
.....
.....
make[3]: *** No rule to make target `XXX/chapel-1.17.1/third-party/gasnet/install/linux64-intel-unknown/substrate-mpi/seg-everything/nodbg/include/mpi-conduit/mpi-par.mak'.  Stop.
make[2]: *** [all.helpme] Error 2
make[1]: *** [runtime] Error 2
make: *** [comprt] Error 2

Following on the warning, and setting MPI_CC=mpiicc successfully compiles and chapel is built. However, it does not compile example program hello4.

 $ bin/linux64/chpl -o hello4 examples/hello4-datapar-dist.chpl 
g++: error: unrecognized command line option '-wd177'
g++: error: unrecognized command line option '-wd279'
g++: error: unrecognized command line option '-wd1572'
gmake: *** [/tmp/chpl-seetham2-9562.deleteme/hello4.tmp] Error 1
error: compiling generated source

The default mpi c and c++ compilers must be overridden. mpicc can be overridden using the environment flag MPI_CC. However, mpicxx does not have an environment flag to override.

In file $CHPL_HOME/runtime/etc/Makefile.comm-gasnet we have

```
# For the linker, we tend to want a C++ linker, in order to support
# linking in components developed in C++ like re2 or user C++ code.
# However, GASNet doesn't provide any guarantees that their linker
# will be a C++ compiler.  Based on conversation with the GASNet
# team, we should expect it either to be GASNET_CC, GASNET_CXX, or
# MPI_CC.  The following conditional handles these cases, switching
# to the C++ choice in the first and third cases.
#
ifeq ($(GASNET_LD),$(GASNET_CXX))
LD = $(GASNET_LD)   # GASNet chose C++ linker so stick with it
else ifeq ($(GASNET_LD),$(GASNET_CC))
LD = $(GASNET_CXX)  # GASNet chose C, so switch to C++
else ifeq ($(GASNET_LD_REQUIRES_MPI),1)
LD = mpicxx         # GASNet chose mpicc, so we'll choose mpicxx
else
LD = $(CXX)
$(warning GASNET_LD unexpectedly set to '$(GASNET_LD)'.  Please file a Chapel bug against this.)
endif
endif
endif
```
Manually changing mpicxx to mpiicpc fixes all problems and chapel is able to compile and run multilocale programs.

Request: mpicxx is hardcoded in the makefile and able to set it using environment flags instead of modifying the makefile would be nice. Even the $MPI_CC warning gets lost in the huge output and is not easy to figure out what the problem is from the last lines of the error.

**Comment by ronawho** [comment]
I'm looking for a system to test this on, but in the meantime can you see if the following patch works for you? You should be able to apply the following patch and set `MPI_CC=mpiicc` and `MPI_CXX=mpiicpc`. 

```diff
diff --git a/make/compiler/Makefile.mpi-gnu b/make/compiler/Makefile.mpi-gnu
index f354164d4a..5fdfa6c30c 100644
--- a/make/compiler/Makefile.mpi-gnu
+++ b/make/compiler/Makefile.mpi-gnu
@@ -19,5 +19,13 @@

 include $(CHPL_MAKE_HOME)/make/compiler/Makefile.gnu

-CC=mpicc
-CXX=mpicxx
+ifeq (, $(MPI_CC))
+MPI_CC=mpicc
+endif
+
+ifeq (, $(MPI_CXX))
+MPI_CXX=mpicxx
+endif
+
+CC=$(MPI_CC)
+CXX=$(MPI_CXX)
diff --git a/runtime/etc/Makefile.comm-gasnet b/runtime/etc/Makefile.comm-gasnet
index eb213cd92f..63ff8094e8 100644
--- a/runtime/etc/Makefile.comm-gasnet
+++ b/runtime/etc/Makefile.comm-gasnet
@@ -58,7 +58,10 @@ LD = $(GASNET_LD)   # GASNet chose C++ linker so stick with it
 else ifeq ($(GASNET_LD),$(GASNET_CC))
 LD = $(GASNET_CXX)  # GASNet chose C, so switch to C++
 else ifeq ($(GASNET_LD_REQUIRES_MPI),1)
-LD = mpicxx         # GASNet chose mpicc, so we'll choose mpicxx
+ifeq (, $(MPI_CXX))
+MPI_CXX = mpicxx    # GASNet defaults to mpicc, so we'll default to mpicxx
+endif
+LD = $(MPI_CXX)
 else
 LD = $(CXX)
 $(warning GASNET_LD unexpectedly set to '$(GASNET_LD)'.  Please file a Chapel bug against this.)
```

**Comment by ronawho** [comment]
Alright, found a system to test on. I was able to reproduce your error and confirm that the above patch fixes it. https://github.com/chapel-lang/chapel/pull/10626 is the PR for that patch.

**Comment by SwetaYamini** [comment]
Yes, that fixes the issue.

**Comment by ronawho** [comment]
@SwetaYamini The fix has been merged to master -- we also decided to default to mpiicc and mpiicpc when we detect that intel is being used so you shouldn't have to set MPI_CC or MPI_CXX yourself.
