### ISSUE TITLE
problem with generic type query and borrowed

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#10628]
``` chapel
class GenericClass {
  type t;
  var v: int;
}

class OtherGenericClass {
  type t;
  var v: int;
}

record Wrapper {
  var f;
}

proc g(x: Wrapper(borrowed GenericClass(?))) {
  writeln(x);
}

var c = new Wrapper(new borrowed OtherGenericClass(int, 3));

g(c); // error - type mismatch
```

A compilation error (failure to resolve) is expected but the program runs anyway.

Related Future: functions/ferguson/query/query-generic-type-leaf-q-borrowed.chpl

**Comment by cassella** [comment]
Modifying `g()` to include `x.type:string` in its writeln, the `g(c)` line produces

`(f = {v = 3}): Wrapper(OtherGenericClass(int(64)))`

which is a curious static type for `x` given how it's declared.

**Comment by bradcray** [comment]
Based on this example and another one Paul asked me about in chat, I wonder whether we're being too loose about how we resolve generic arguments.  Specifically, `x` in `g()` is generic in the sense that it's a `GenericClass(?)` but it's not so generic that anything could be passed to it.  I wonder if the compiler is using a much more blanket "it's generic, so I can resolve this" test than it should be in cases like this.

**Comment by mppf** [comment]
It seems likely. I'd just consider it a bug. We have special code in normalization for these cases, and it seems to leave out a filter in this case.
