### ISSUE TITLE
Improve error messages for generic type initialization mismatches

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#10639]
### Summary of Problem

In writing some programs to exercise generic types, I got some surprising error messages that I don't think would be at all clear to an end-user.  Diving into them, they reveal that we're still using defaultOf() and assignment for these cases which was a surprise to me (but not to Lydia or perhaps BHarsh).

### Steps to Reproduce

**Associated Future Test(s):**
[`test/types/records/init/generic/mismatch.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/types/records/init/generic/mismatch.chpl
          ) #10638 
[`test/types/records/init/generic/mismatch2.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/types/records/init/generic/mismatch2.chpl
          ) #10638 

### Configuration Information

- Output of `chpl --version`: `chpl version 1.18.0 pre-release (65f8c7f)`

**Comment by bradcray** [comment]
@benharsh: Following up on our discussion today, I moved these into the backlog, as I think these are problematic w.r.t. the intended semantics for initializers and _may_ cause problems (or at least surprises) for end-users writing advanced record types.  (to be clear, I'm more concerned about the fact that we're default initializing + assigning than the specific error messages that this future is about).  Is this something we could improve without solving the generic `init=` questions we we've been talking about lately?  (it seems like it, but maybe I'm oversimplifying).

**Comment by cassella** [comment]
Those two futures are no longer futures,

mismatch.chpl via #12387
mismatch2.chpl via #11120

**Comment by bradcray** [comment]
Thanks!
