### ISSUE TITLE
Internal error MIS0564 in class defining an enum type

### ISSUE THREAD

**Issue by ian-bertolacci** [chapel-lang/chapel#10635]
Code [TIO](https://tio.run/##JY1BCkMhDET3nmKWCqXQbaXL9gS9gEjKF6yK@r@Uj2e3ERcJ4c1kxm4mkR/DelMKXjHiFACF/Ysnr/cvEU7EQBfUFtE1q4fJPH4n3OFCnSjlaPl2VeJYFGoGAXVz5brcj/U1/V10IWbOh2mgNpslbkqLll0lHyQrSo/xBw):
```chpl
class Foo {
  enum EnumType { one, two };
  var value : int;
  proc init( v : int){
    this.value = value;
  }
}

var f = new Foo( 1);
writeln( f );
```

Error:
```
test.chpl:4: internal error: MIS0564 chpl version 1.18.0 pre-release (10f16d949c)
```

+ chpl --version: `chpl version 1.17.1`

**Comment by lydia-duncan** [comment]
I believe this is a duplicate of #6871

**Comment by lydia-duncan** [comment]
At the very least, it is related

**Comment by ian-bertolacci** [comment]
It is.
