### ISSUE TITLE
Visibility of assignment operator

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#10650]
Should the following program compile?
```chpl
module A {
  record R {
    var x : int;
  }
}
var X = new A.R(5);
var Y = new A.R(10);
X = Y;
```

At the time this issue was created (cdff7ca) , it does not.

The final line will attempt to invoke the assignment operator between two Rs. Our current implementation generates an assignment implementation in the same module as the type. If we take a strict view of visibility, then it seems obvious that the assignment operator would not be visible from the last line.

But assignment is generally part of the core usage of a type, so the lack of visibility here may seem surprising to some users. It may also cause one to question the point of using a qualified path like ``A.R`` without using ``A``.

**Comment by bradcray** [comment]
I feel like I can argue this either way:

* Intuitively, it seems like it should resolve.  Just as methods are available on a type even if the module defining the method isn't, it seems like this common / core operator ought to be.
* OTOH, since `=` is defined as a standalone function, strictly speaking it seems like it shouldn't be.
* I think at times we've debated whether `=` should be defined as a method rather than a standalone function (?).  Maybe this is further incentive for doing so?

**Comment by bradcray** [comment]
Since @mppf thinks a lot about visibility and has also done a certain amount of work on operator overloading, I'll definitely be curious what he thinks when he has a chance to weigh in.

**Comment by mppf** [comment]
I think it'd be nice to think about this in terms of "What if operators were normally defined as methods?". In that event other code we have would allow it.

I'd argue that we could/should allow operators to be defined both as methods and as standalone functions, and that in that environment, operators would always get the special visibility treatment currently applied to methods.

In any case I'd like for the above program to work. Of course one could argue that the `=` on the last line is just as clear as `somefunction(X,Y)`. However we cannot write `X A.= Y;` and the visibility rule I've been advocating in discussions about method visibility is that the compiler should find the thing if you don't have the ability to decorate the call. By that logic, `=` and as well `+` or any other operator should be automatically included. (Unless we decided `X A.= Y;` was the right answer, which seems unlikely to me).
