### ISSUE TITLE
What should the generated Python module be called?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#10666]
The tutorial for Cython tends to use a different name for the .a/.so/.h/.pxd combo and the .pyx/.py final python module name.  What should we use as the base name for the .pyx/.py files?  How should the user control it?

Options:

1.  Use the name specified via `-o` as the name for the .pyx/.py file and a different, generated name for the .a/.so/.h/.pxd file
  - Rationale: when creating a Python module, it may be that the user doesn't care as much about the C style library
2. Use a different name for the .pxd file, and have the .pyx/.py file match the name of the .a/.so/.h
  - I need to experiment to see if this is actually valid.  I also need to experiment with the .h having a different name from the .a/.so
3. Allow the user to specify the name for the generated python module, and use that name for the .pyx/.py file.  Flag would potentially be named `--library-python-name`
  - If the flag is not provided, the name defaults to `chpl_libraryName` where libraryName is the name used for the .a/.so.

The .pxd file name will match the header name, since the file will probably get hidden from the user.

I lean towards 2 if possible (with 3's strategy as the way to change the name).  If 2 is not possible, then I lean towards just 3

**Comment by bradcray** [comment]
> The tutorial for Cython tends to use a different name for the .a/.so/.h/.pxd combo and the .pyx/.py final python module name.

Is there a reason they can't all share the same name?  I.e., is it for pedagogical purposes of some kind within the tutorial, or is it a requirement of some sort?

**Comment by lydia-duncan** [comment]
It seems to be just a general best practice.  I can use the same name for the .pxd and .pyx/.py files today without issue.  I suspect Cython probably won't disable that support in the future but they may not test it as thoroughly as the other strategy or something, so it might be better to honor it?  I'm not married to following it, but left to my own devices I probably would.

**Comment by mppf** [comment]
I'd favor using the same name if possible. If you're uncertain about how weird/tested that is, maybe you could ask on a Cython chat channel / mailing list?

**Comment by lydia-duncan** [comment]
[Here's the Cython chat thread](https://groups.google.com/forum/#!topic/cython-users/q25rLV1UBRM).  Basically, the names are supposed to match when the code is entirely implemented in the .pyx/.pxd files.  Because the code is implemented in a library file, the .pxd file and .pyx file should have different names.  But the .pyx can match the library.  So strategy 2 seems like the way to go (with a flag to change the name of the generated Python module)

**Comment by mppf** [comment]
I tried to follow that thread but I can't understand if there is any recommendation at all.

One thing from that thread:

> You may also consider moving everything into a package (probably named "myLib" then).

I don't really understand what that means, but it's presumably another option, right?

In Strategy 2, does a (normal) user of a Chapel from Python need to be aware of this alternative module name? I'm asking because my viewpoint is that anything a user is expected to interact with and that they might conceptually view as representing "the library" should have the same name.

**Comment by lydia-duncan** [comment]
>>  You may also consider moving everything into a package (probably named "myLib" then).

> I don't really understand what that means, but it's presumably another option, right?

Yeah, I'm not sure what that means either

> In Strategy 2, does a (normal) user of a Chapel from Python need to be aware of this alternative module name? I'm asking because my viewpoint is that anything a user is expected to interact with and that they might conceptually view as representing "the library" should have the same name.

I would say the user wouldn't need to be aware of this name.  The intention is that the .so/.a/.h file would use the same name as the .pyx and the name that gets generated for the final Python module.  The .pxd would use a separate name.  I'm leaning towards also cleaning up the .pxd/.pyx files once we get to generating the module itself, and in that case the user wouldn't necessarily know that a different name was used at all.

**Comment by lydia-duncan** [comment]
I've sent a follow up asking for more clarity on the package comment

**Comment by lydia-duncan** [comment]
#10787 uses the same name as the library file (minus the "lib" portion when we insert that by default).
