### ISSUE TITLE
Invoking initializers on instantiated types

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#10677]
Should we allow initializers to be invoked on instantiated types?

For example: A user might create a type alias to save time typing out a common instantiation. This user may still wish to invoke an initializer with this alias:

```chpl
record R {
  type t;
  var x : t;
}

type RI = R(int);

var r : RI = new RI(10);
```

Open questions:
- Should the compiler attempt to invoke a 'normal' initializer in such cases?
- How could the compiler reliably match type/param fields to formals?
- Should we allow some patterns, but not others?
- Should the language require a special kind of initializer for instantiations?

**Comment by lydia-duncan** [comment]
I feel like this was something @nspark wanted at some point, but I'm having difficulty finding the issue itself

**Comment by nspark** [comment]
I think #5143 shows the cases I was interested in.

**Comment by bradcray** [comment]
@benharsh: Almost too obvious to be worth mentioning, but continuing the `init=` for generics proposal I sent last night, my hope would be that:

```chapel
type RI = R(int);

var r : RI = new RI(10);
```

would be equivalent to how we'd handle:

```chapel
var r: R(int) = new R(10);
```

The more interesting case would be a type alias for a partially instantiated generic where the declaration would fill in the other missing bits to still have a fully instantiated type (where I think the answer is likely "concatenate the argument lists", but that seems better suited for a separate issue (and also constitutes a bonus over the base functionality in my mind).

**Comment by vasslitvinov** [comment]
@benharsh can this issue be closed now?

**Comment by benharsh** [comment]
I think there are still open questions involving fully-generic fields.

**Comment by bradcray** [comment]
Would it be possible to fork those off to distinct issues (if they haven't been already) since, on the surface, it feels like this one (as stated) is done?

**Comment by benharsh** [comment]
I think #16508 is a suitable successor to this issue.
