### ISSUE TITLE
default intent tuple argument modifies call site

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#10711]
``` chapel
proc fun(arg: 3*int) {
  arg(1) = 0;
}

proc main() {
  var tup = (1,3,6);

  fun(tup);

  writeln(tup);
}
```

Should this program output 0 or 1, or be a compilation error?

Right now it outputs 0.

**Comment by mppf** [comment]
@ysahil97 fyi

**Comment by mppf** [comment]
CHIP 6 says:

> In particular, the driving design principle is that a 1-element tuple should behave similarly to just the element. This applies when passing the tuple to a function by blank intent, when returning it from a function, or when assigning it to a new variable. The behaviour of tuples with more elements can be understood as a generalization of 1-element tuples.

That would imply that a 1-element tuple containing an integer behaves as an integer argument, which gives compilation error in this case:
``` chapel
proc intfn(arg: int) {
  arg = 0;
}
```

So, I think that the above program should result in compilation error.

**Comment by ysahil97** [comment]
If it were to give a compilation error, what would be the appropriate place in Chapel source code which could handle this error?

**Comment by mppf** [comment]
it would be in compiler/resolution/lateConstCheck.cpp  ; I'm looking at it
