### ISSUE TITLE
Exporting Chapel -- const string

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#10782]
As I understand it (famous last words), when passing C strings into an exported Chapel routine, Chapel will copy that C string to prevent mutation or destruction while using it.

[Are there optimizations for when the Chapel prototype specifies it takes a `const char*` instead of a mutable string?](https://github.com/chapel-lang/chapel/issues/10782#issuecomment-413370092) This seems like an easy place to optimize away unnecessary string copies, though there might be corner-cases from null-character string termination.

**Comment by lydia-duncan** [comment]
That's an interesting question.  I'm not aware of any specific optimizations, but would imagine that we don't turn off any that would occur for an ordinary function.

**Comment by lydia-duncan** [comment]
@mppf - I suspect you would know more about this than I do

**Comment by BryantLam** [comment]
If `f` uses the `c_string`, I get this warning:
```chapel
export proc f(arg: c_string) {
  writeln(arg);
}
// error: Cannot write a c_string, cast to a string first.
```
Somewhat disappointing since I'm not (apparently) writing to the string; only reading from it. I only tried with `writeln`, so maybe it doesn't happen on all instances of reading from `c_string`.

The `--savec` generated code for `writeln(arg: string)` (cast to `string`) yields:
```c
void f(c_string arg) {
  string call_tmp_chpl;
  string ret_tmp_chpl;
  ...
  _cast2(arg, &ret_tmp_chpl, ...);
  call_tmp_chpl = ret_tmp_chpl; // strings are records. This is a copy?
  writeln_chpl2(&call_tmp_chpl, ...);
  ...
}
```

**Comment by BryantLam** [comment]
My original post is a little different than the example I posted, since I'm now casting to `string`.

The original intent was to understand where using `c_string` in Chapel was limited, as in this case here where I'm just reading from it. If the interface specified it took `const arg: c_string`, is there opportunity for optimization?

**Comment by mppf** [comment]
Regarding
``` chpl
export proc f(arg: c_string) {
  writeln(arg);
}
// error: Cannot write a c_string, cast to a string first.
```

the "cannot write a c_string" error is specifically about writeln. The copy you observe is coming from the cast from c_string to string.

Compare with the following program that "uses" the c string but does not make a copy:
``` chapel
export proc f(arg:c_string) {
  writeln(arg.length);
}

proc test() {
  var my_c_string:c_string = "test_string";
  f(my_c_string);
}
test();
```

You might reasonably ask - should casting a c_string to a string cause a copy - and is there a reasonable way to write "Make me a string that takes responsibility for freeing this other string" - that's something we are discussing in issue #10410.

But, if this response doesn't help, I have a feeling I still don't understand the question.

**Comment by mppf** [comment]
> Sorry about that. #10410 is helpful because it deals with taking ownership of a c_string buffer from within Chapel. However, here, I want to prevent copies from being made when I know one side of the string usage is const. Put another way, if I'm passing strings between Chapel and C/Python, is there a way to wrap or extract one from the other to prevent copies from being made when using C?
> 
> ### Question 1
> C function takes `const char* arg` and will not be mutating arg. Can I pass it a c_string derived from a Chapel string without copying the string data?
> 
> **Edit:** It's probably Chapel's `string.c_str()` when using a C function from Chapel.

Yes, that's right. `string.c_str()` will not copy the string. Note that if the string were possibly remote, you'd need `string.localize().c_str()` which will copy the string if it's remote (since otherwise C would get a pointer to a different locale, which isn't something it handles).

> Is there an equivalent conversion when using Chapel strings from C?
> Maybe something like `const char* chpl__get_c_str_from_chpl_string(string x) { ... }`.

Right now, I don't think we're expecting C code to work with the Chapel string type at all. You might run into a more basic problem before that function could be written. But anyway, in theory if the C code could use the `string` type from Chapel, it could probably also call `.c_str()`. I don't personally know how you'd do either of those things at present. (Of course you could look at the generated C and hack something together.... but there isn't a prescribed way that Chapel types turn into C and the string type isn't exported and C doesn't have methods and ...)

**Comment by mppf** [comment]
> 
> ### Question 2a
> I have an exported Chapel function that takes a `const arg: string` that the Chapel function will not be mutating. This function is intended to be callable from C/Python. 

Using `string` as the argument type in an exported proc currently results in an error after PR #10788. If you're asking about how it would work in Python interoperability in some future moment when it's not an error... I don't know but maybe @lydia-duncan can say?

I would suppose you'd be able to call whatever #10410 settles upon (and probably alternatively a way to create a string that "borrows" a `const char*`) from Python. But designing such things now just seems like getting ahead of ourselves.

**Comment by lydia-duncan** [comment]
> Using string as the argument type in an exported proc currently results in an error after PR #10788. 

It was already an error, #10788 changes it from a link time error that you can possibly hack at until you get a representation that works to just a compiler error.  For now you can have an exported function that takes a c_string and calls the Chapel function which takes a string after transforming the argument.

The hope is that eventually we will be able to export the string type itself, so you could call the string cast function or initializer with the char* you want to use in C and then send the result of that to the Chapel exported function.  But exporting types is a little further out.

**Comment by bradcray** [comment]
Hi @mppf, @lydia-duncan, @BryantLam : I've lost the thread on this issue.  The original issue, as posted, seems like it could be closed, but then it spun into a number of other Q's and A's...  Thanks for any help here.

**Comment by bradcray** [comment]
@BryantLam , @lydia-duncan, @mppf: Still trying to understand where we are with this issue in order to determine where to sort it.  Thanks.

**Comment by mppf** [comment]
I'm closing this issue because:
 * it seems like it might be resolved (questions were answered, anyway)
 * library work now allows exporting procs with `string` arguments
