### ISSUE TITLE
use-only-as rename on module results in successful compilation, but unusable symbol

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#10798]
### Summary of Problem
Background: I was trying to figure out whether you could rename a module on a `use` statement. The following code compiled when it should not.

```chapel
module Toolbox {
  var x = 1;
}

proc main() {
  use Toolbox only Toolbox as tb; // This compiles by itself.
  // writeln(tb.x); // Generates compile error: 'tb' undeclared
}
```

### Configuration Information
`chpl version 1.18.0 pre-release (f18926d825)`

**Comment by BryantLam** [comment]
Edited the post to make this into a feature request instead of a bug report.

**Comment by lydia-duncan** [comment]
That's real weird.  We do some symbol matching on the list of symbols in an `only`/`except` list, so I'm a bit surprised it is able to "find" Toolbox at all, but it may be that the particular check is only triggered when the renamed symbol is used

**Comment by lydia-duncan** [comment]
> Edited the post to make this into a feature request instead of a bug report.

A bug report is also reasonable, since it really should complain about the use statement when it can't find the symbol.  For instance, if you replaced Toolbox with `somethingElse` when somethingElse is not in the module, does it still "work"?

**Comment by BryantLam** [comment]
>  For instance, if you replaced Toolbox with somethingElse when somethingElse is not in the module, does it still "work"?

No it does not. That's why I opened the initial report. Maybe it would be better to create both issues?

**Comment by BryantLam** [comment]
Hah. Sorry for the churn. I'll just make both. Feel free to revert this back to a bug report.
