### ISSUE TITLE
Spike: Study how to handle Chapel ABI interoperability in the LLVM back end

### ISSUE THREAD

**Issue by dmk42** [chapel-lang/chapel#10836]
LLVM delegates responsibility for ABI observance to the language front end.  This ensures that language-dependent data types are properly represented, but it burdens the front end with detailed knowledge of many different hardware architectures.  It also makes interoperability difficult, because if one language wants to create functions callable by another language, or wants to call functions in another language, the two front ends must share ABI information with each other instead of simply depending on LLVM to get it right.

This is a thorny issue.  This spike is intended to be a deep investigation, and if time permits, part of the solution may be developed during the spike.  Some of the strategies that need to be considered are:

* Should all Chapel functions be ABI compliant, or should only imported and exported functions be ABI compliant?

* Can Chapel's LLVM interface handle the ABI compatibility, or should we use Clang for that?  At first thought, it sounds easier to use Clang.  However, Clang's ABI compatibility code operates only on Clang AST, so we would have to generate Clang AST to make this work.

*  Is ABI tolerance enough, rather than ABI enforcement?

**Comment by mppf** [comment]
This seems interesting and relevant https://github.com/apple/swift/blob/master/docs/CallingConvention.rst

**Comment by mppf** [comment]
I think we could use the Swift calling convention. Our error handling strategy is similar and we'd likely benefit (for error handling calls) from storing the error in a dedicated register. We can use swiftself and swifterror since these are in LLVM trunk.

**Comment by dmk42** [comment]
The Swift ABI sounds interesting.  That warrants its own spike.
