### ISSUE TITLE
Reference: String Bibliography

### ISSUE THREAD

**Issue by dmk42** [chapel-lang/chapel#10831]
# String Bibliography
This issue is for reference only, so that other issues can refer to it.  It is derived from a bibliography posted to e-mail by Kyle some time back.

## General background
Some may advocate a particular point of view.

- http://www.unicode.org/standard/WhatIsUnicode.html
- http://www.joelonsoftware.com/articles/Unicode.html
- http://utf8everywhere.org/
- https://unspecified.wordpress.com/2012/04/19/the-importance-of-language-level-abstract-unicode-strings/
- http://eev.ee/blog/2015/09/12/dark-corners-of-unicode/
- http://seriot.ch/resources/talks_papers/i_love_unicode_softshake.pdf
- https://en.wikipedia.org/wiki/Han_unification
- https://docs.python.org/3.5/howto/unicode.html

### Perl
- https://stackoverflow.com/questions/6162484/why-does-modern-perl-avoid-utf-8-by-default
### Python
- https://www.python.org/dev/peps/pep-0393/
- http://lucumr.pocoo.org/2014/1/5/unicode-in-2-and-3/
- http://lucumr.pocoo.org/2014/5/12/everything-about-unicode/
### Swift
- https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/StringsAndCharacters.html
### Rust
- http://doc.rust-lang.org/book/strings.html
- http://doc.rust-lang.org/reference/types.html#textual-types

## An early proposal from Kyle
- https://gist.github.com/Kyle-B/44138a37907a2a53c4b2

### ICU
- http://site.icu-project.org/
- http://userguide.icu-project.org/strings/utf-8

Kyle's comment:
ICU's utf8 support seems to have gotten better since I last looked; it's probably worth more exploration. I'm still not sure how viable it would be to embed the library by default though.

### utf8proc
- http://julialang.org/utf8proc/

Kyle's comment:
Julia uses [utf8proc] for some of their support, it's supposed to be a decent
library I think. It doesn't do everything we'd want though.

### Possibly of interest
- https://bitbucket.org/knight666/utf8rewind/overview

**Comment by bradcray** [comment]
@dmk42: Since this issue doesn't represent work to be done, is it OK if I close it?  (won't prevent others from referring to it).

**Comment by dmk42** [comment]
That's fine.
