### ISSUE TITLE
Design: String Strategy

### ISSUE THREAD

**Issue by dmk42** [chapel-lang/chapel#10834]
Chapel now has UTF-8 support.  The mechanism most closely resembles Rust, where strings are stored in UTF-8 rather than UCS-4, indexing into strings is by byte, and codepoints can be accessed if desired.  As with Rust, the codepoint access is explicit, e.g. `str[i: codePointIndex]` so that the use of slow operations is clearly documented in the code.

The question now is whether we want to add a new feature set, the support of grapheme clusters.  Multiple Unicode codepoints may be used to fill a single print position on a page, and a grapheme cluster is the full set of codepoints that combine to make a printed symbol.

Based on historical discussions, this issue is not likely to be resolved to everyone's satisfaction.  If there is no consensus, this issue will serve as a collection of the design decisions considered.

See issue #10831 for a bibliography on strings.

**Comment by dmk42** [comment]
Personal opinion:
Grapheme clusters are an expensive distraction.  In creating Chapel's current UTF-8 support, it turned out to be extremely useful that a single codepoint could be represented in a fixed-sized data object (a 32-bit integer).  If that ability were to disappear, there would be many more dynamically-allocated temporaries because the size of a grapheme cluster can be arbitrarily large and cannot be guaranteed to fit any particular fixed-size data object.

**Comment by mppf** [comment]
Handling grapheme clusters seems relatively easy to handle in a fashion. There is a C standard routine, wcwidth, which the I/O system uses to appropriately line up tables of Unicode characters. This is not quite the same as determining the grapheme cluster but I believe it could easily be used to that end. The only question is whether or not to associate any zero-width code points (as reported by wcwidth) with the character before or the character after, and I believe it would always work to associate with the character before:

From [unicode.org](http://unicode.org/faq/char_combmark.html):

> A combining character sequence is a base character followed by any number of combining characters. It is one type of a text element, but words and sentences are also examples of text elements.

Additionally, if we wanted to, we could support indexing by "column in the terminal", which is closer to what the I/O system needs/uses.

The same linked-to page above includes a question I'll summarize here:

> Q: How are characters counted when measuring the length or position of a character in a string?

> A: Computing the length or position of a "character" in a Unicode string can be a little complicated, as there are four different approaches to doing so, plus the potential confusion caused by combining characters. The correct choice of which counting method to use depends on what is being counted and what the count or position is used for. 

> (see link for a nice example)

> 1. Bytes
> 2. Code units
> 3. Code points
> 4. Grapheme clusters

We already have 1 and 2 (for our representation, UTF-8, this is bytes). We implemented 3 recently. I think a reasonable 1st cut at implementing 4 is the wcwidth strategy described above. That hopefully addresses any concern like "It would be too hard to support". As far as program performance goes, as long as the routines working with grapheme clusters are separate, they wouldn't impact other performance and they can be slow (at least for now). This seems a similar situation to code point indexing now.

That's not to Unicode support will be totally complete and never need to be enhanced. I just think it'd be a reasonable starting point. Users of unicode might want more character classes - see [Q: Is the POSIX ctype.h model sufficient for Unicode?](http://unicode.org/faq/char_combmark.html). Additionally it wouldn't surprise me if someday somebody wants an implementation of [Unicode Text Segmentation](http://www.unicode.org/reports/tr29/) in Chapel but for now I believe we can avoid the issue. Lastly I'm pretty sure the wcwidth strategy would work for *most* Unicode, but there might be some really weird use cases it wouldn't support. Usually weird use cases of Unicode involve ancient scripts.

**Comment by dmk42** [comment]
This is the first I have heard of wcwidth.  It is not a standard C function, so I don't know if we can trust its availability.

**Comment by mppf** [comment]
It's POSIX.1-2001. E.g. http://pubs.opengroup.org/onlinepubs/009604599/functions/wcwidth.html

Besides that, since we've been using it for I/O and that library wouldn't link without it, I'm pretty sure it exists everywhere we test. (the C code includes a dummy implementation if wctype.h is not available - and wctype.h is needed for iswalpha etc that you already are using).

**Comment by dmk42** [comment]
How does it help us determine something like isalpha for a grapheme cluster?

**Comment by mppf** [comment]
I just meant that the header wctype.h is used for iswalpha - meaning we are already testing that the header providing wcwidth is generally available and that wcwidth can be linked with and works (in the tests that use it).

**Comment by dmk42** [comment]
But how do we do it?

**Comment by dmk42** [comment]
I suppose one strategy might be to have Chapel's `isAlpha()` ignore characters within a grapheme cluster whose wcwidth is zero.  However, I don't have confidence that we would be defining it the way it's intended.  I think if we had to support grapheme clusters, it would be better to use a third-party library written by people whose primary focus is international characters.

**Comment by mppf** [comment]
I was talking about grapheme clusters solely for indexing and length calculations. I don't actually know the use case for something like `isAlpha` on a grapheme cluster string where simply using the answer of the base character wouldn't be sufficient. (I.e. I don't see any reason to change isAlpha to support grapheme clusters).

**Comment by dmk42** [comment]
What if you have the letter `e` followed by an accent over it?  If we want to claim to support grapheme clusters, the resulting cluster should have `isAlpha` return true.  That would require a change.

**Comment by mppf** [comment]
From [unicode.org](http://unicode.org/faq/char_combmark.html):

> A combining character sequence is a base character followed by any number of combining characters. It is one type of a text element, but words and sentences are also examples of text elements.

I.e. that would be represented by the code point for `e` followed by the code point for the accent. So isAlpha would (presumably) apply to the `e` only and ignore the rest. (Does it not do that? If it doesn't using wcwidth to find 0-width characters to ignore would probably be fine).

**Comment by dmk42** [comment]
No, it does not do that.  Right now it has no basis for doing so.  The definition of it is to check each character, not each grapheme, so it would return false for the accent.

Now we are back to the point I was making.  At first blush, to people who do not specialize in international characters (even if we have more exposure to them than most people do), it does seem reasonable - when in grapheme mode - to ignore characters whose wcwidth is zero for the ctype tests.

However, this is a rather simplistic solution, and as I said, I don't have confidence that it would catch all the cases properly and work as it should.  I don't think we should get involved in grapheme clusters, but if we do, it would be much better to use a third-party library where that is their focus, so we don't end up inventing things that turn out to be wrong.

**Comment by mppf** [comment]
From the issue description:

> The question now is whether we want to add a new feature set, the support of grapheme clusters. 

I think it'd be reasonable to add grapheme cluster length and indexing computations.

Regarding the ctype issues, we already know that the sets that are inspired by ctype don't necessarily make sense for Unicode. See [Q: Is the POSIX ctype.h model sufficient for Unicode?](http://unicode.org/faq/char_combmark.html) which I linked to earlier but I will quote here for emphasis:

> A: POSIX “ctype.h” knows but two cases, whereas Unicode knows three. In POSIX, only European Arabic digits can pass “isdigit”, whereas Unicode has many sets of digits, all putatively equal in their status as digits. In POSIX “ctype.h”, that which is “alnum” but not “alpha” must be a “digit”, but Unicode is aware that not all numbers are digits, nor are all letters alphabetic. Unicode groks spacing and non-spacing marks, but POSIX comprehends them not. 


The approaches available to us specifically about ctype are:
 1. Use a strategy to allow simple combinations to work.
 2. Error if ctype functions are called on strings with combining characters
 3. Throw out ctype functions and use Unicode Character Properties instead (see https://en.wikipedia.org/wiki/Unicode_character_property )

I personally prefer we do 1 or 2 and in the future do 3, but it might be reasonable to desire 3 is addressed immediately in the name of API stability.

**Comment by mppf** [comment]
Note also that the RE2 library we bundle and link with already has the capability to know which code points are in which Unicode character classes. See unicode_groups.cc. I'm not so sure it's part of the public RE2 interface, but we already patch RE2 and could make a little interface for it.

**Comment by bradcray** [comment]
> indexing into strings is by byte

I continue to be concerned about (a) whether this is the correct choice, and (b) the general lack of discussion about it within the team.  So I'm tacking those concerns onto this issue here.  The following is an edit of some notes I sent to David by email earlier:

Should default indexing be by byte vs. codepoint vs. grapheme vs. something else?  Rather than supporting indexing by different units via distinct methods (e.g., `this()` vs. `str()` vs. `...`), we could support multiple overloads of `this()` taking different argument types:

```chapel
proc this(i: byteOffset) ...
proc this(i: codePoint) ...
proc this(i: graphemeCount) ...
```

This would make all string indexing simply looks like indexing, where the argument type indicates which kind of indexing to do.

In such an approach, maybe we:

* don't support integral indexing at all (to avoid mis-assumptions about what its units are), or 
* support integral indexing and have it default to bytes (fast) or code points / graphemes (logical) or whatever we decide is the best default
* support integral indexing, but with a required (or optional?) "units" argument indicating which units to use:

```chapel
proc this(i: int, unit: stringOffset [ = ...]) ...
```

such that anyone reading the interface would know exactly what needed to be provided.

I remember that a previous time that we were working hard on strings, @mppf asked something like "where do we think these indices that are used for these calls will be coming from? (because that might determine how opaque or user-comprehensible the default ought to be)."  I thought that was a great point, so I'll ask the question again here in a few ways:

1) In a "bytes-by-default" world, where do we anticipate that the indices being provided will be coming from?
2) Which of our string library functions return offsets and how user-comprehensible do those offsets need to be?

**Comment by mppf** [comment]
I've just created several issues based on the experience of using the Unicode support to write some examples.
 * problem looping over Unicode strings #11060
 * string this sometimes returns an integer and sometimes string #11061
 * string slicing by a range of codepoints #11062
 * should there be a way to explicitly request byte units? #11063

**Comment by dmk42** [comment]
The resolution to this issue was that we decided to defer any implementation of grapheme support for now, but avoid making design changes that will preclude adding grapheme support some time in the future.
