### ISSUE TITLE
Add Jenkins Job for testing Spack Integration

### ISSUE THREAD

**Issue by Spartee** [chapel-lang/chapel#10833]
The tests for the Spack integration are found in `CHPL_HOME/test/mason/spack-integration`. These tests need to be run on a nightly job on the CentOS VM(chapel-centos7-02). 

Steps to reproduce this testing manually(might be of benefit):
- clone Chapel repo
- `make`
- `make test-venv`
- `source util/setchplenv.bash`
- `cd $CHPL_HOME/tools/mason && make mason`
- `cd $CHPL_HOME/test/mason/spack-integration && start_test`

All env vars should be taken care of by Mason.

These tests do the following:
- Spack download and bootstrap setup
- Installation of `openBLAS` package through Spack integration
- test compilation of custom`LinearAlgebra` module using downloaded openBLAS

**Comment by awallace-cray** [comment]
Build slave setups

Install gcc-fortran
`sudo yum install gcc-fortran compat-gcc-44-gfortran`

Configure gcc-fortran
* same userid as Chapel tests run
`mason external compiler --edit` 
* detail TBD
