### ISSUE TITLE
Should you be allowed to release() an owned record?

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#10832]
This code is somewhat nonsensical on records. Are you allowed to `release` an `owned record`?
```chapel
record R {
  var a: int;
}
proc main() {
  var x = new owned R(1);
  var y = x.release();
}
```
```
error: unresolved call 'R.release()'
$CHPL_HOME/modules/internal/OwnedObject.chpl:190: note: candidates are: ref _owned.release()
$CHPL_HOME/modules/internal/SharedObject.chpl:79: note:                 ReferenceCount.release()
```
`chpl version 1.18.0 pre-release (f18926d825)`

**Comment by mppf** [comment]
`new owned R` does exactly the same thing as `new R` and returns something of type `R`. It does this to support generic programming - one might create a function where they don't know if the type being constructed is a record or not. That choice could be revisited though. (I don't think it has an issue of its own yet but I'd name such an issue "Should `new owned SomeRecord` be an error?")

 `R` doesn't have a `release` so the error is not surprising to me.

**Comment by BryantLam** [comment]
> `new owned R` does exactly the same thing as `new R` and returns something of type `R`. It does this to support generic programming

Understandable. Though if true, I would expect this example to work in some form. If you have an `owned R` which really is just an `R`, it can't really behave like an `owned` you can call `owned` methods on. I don't have an answer, but this seems problematic enough to consider revisiting the `new owned R == new R` decision (where one resolution is to make `new owned record` an error as you mentioned and another solution could be to specialize `owned record` with a Copyable-like interface).

**Comment by bradcray** [comment]
I think Bryant's point is a good one.  @mppf, are there cases where we're currently relying on the generic capability that the current implementation permits?  If not, I'd be inclined to make `owned` on non-class types an error for the time being and to relax it for the generic case if/when we have that compelling example in hand.
