### ISSUE TITLE
Spike: Array-as-vec performance regression from #10793

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#10875]
https://github.com/chapel-lang/chapel/pull/10793 resolved some leaks for the array-as-vec operations, but it appears to have introduced a [performance regression](https://chapel-lang.org/perf/chapcs/?startdate=2018/08/08&enddate=2018/08/22&graphs=arrayvectoroperations) for pop_front and pop_back:

![image](https://user-images.githubusercontent.com/1588337/44550103-29001300-a6f1-11e8-9119-94f049ed8e44.png)

**Comment by ronawho** [comment]
@daviditen it wasn't obvious to me if this was an expected regression or not. Would you mind looking into it?

**Comment by daviditen** [comment]
@ronawho yes, I'll take a look. Thanks.

**Comment by daviditen** [comment]
Closed with PR #11017

**Comment by daviditen** [comment]
The time for popFront/popBack dropped back to the previous level as expected:

![image](https://user-images.githubusercontent.com/7740834/45227887-37b8ff00-b287-11e8-8418-f6bd9e8c370d.png)
