### ISSUE TITLE
typed param declarations use problematic coercions

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#10884]
``` chapel
param q:int(8) = 257;
writeln(q);
```

This program outputs `1` but I would expect it to fail to compile.

This issue is related to PR #7668.

**Comment by mppf** [comment]
The compiler is translating it into 
```
 (388560 'move' q[177311](388558 call _cast call_tmp[522550] 257))
```

and this is happening in the normalizer:

https://github.com/chapel-lang/chapel/blob/b3bb994800650c590705a6f6d2b6247a551b9377/compiler/passes/normalize.cpp#L2167-L2171

**Comment by mppf** [comment]
Removing that case in normalizer gets further but then there are param issues in resolution...

**Comment by bradcray** [comment]
I don't think that this has the same root cause as #10158, but the two issues remind me of one another.

**Comment by cassella** [comment]
Today's behavior looks like what's desired:

```
foo.chpl:1: In module 'foo':
foo.chpl:1: error: Could not coerce param into requested type
foo.chpl:1: error: cannot initialize 'q' of type 'int(8)' from '257'
```

**Comment by mppf** [comment]
PR #21653 will add this now-working case as a test.
