### ISSUE TITLE
Make CHPL_LIBMODE settings trigger a separate runtime/third-party build

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#10898]
Today, the runtime/third-party packages don't distinguish between CHPL_LIBMODE=shared and unset CHPL_LIBMODE, meaning that changing between these settings does not trigger a fresh build.  This setting impacts whether -fPIC is thrown when compiling the Chapel runtime and third-party libraries, meaning that the two compilation modes cannot be used interchangeably.  We should have the build react to changes in this setting similarly to how it reacts to changes in other settings

**Comment by bradcray** [comment]
Capturing my understanding of discussion from yesterday, it was suggested that we verify that there isn't an opportunity to interoperate with Python without requiring -fPIC since, if there were, we might choose to remove the support for CHPL_LIBMODE which would remove the need for this change.

**Comment by lydia-duncan** [comment]
According to [this post](https://groups.google.com/d/topic/cython-users/duzWT0Jdip4/discussion), it doesn't appear to be possible?

**Comment by lydia-duncan** [comment]
I had thought I saw that it was possible if Cython compiled the C code itself into a library, but I can't seem to find that link again (and maybe that wouldn't work for our third-party libraries since they are already made into libraries?)
