### ISSUE TITLE
CHPL_LIBMODE=shared breaks parallel `make -j`

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#10901]
Clean git directory. Commit a5828c85a78425f95473be.
No fancy environment variables other than `CHPL_LIBMODE=shared` (building single-locale).

```bash
cd $CHPL_HOME # Git directory.
git clean -Xfd .
make -j
```

When doing a parallel build with `make -j` and **`CHPL_LIBMODE=shared`**, the build breaks consistently, always, and exactly (sample size = 5) when it gets to this part:

```terminal
...
cd <$CHPL_HOME>/third-party/qthread/build/linux64-gnu-native-flat-jemalloc-hwloc && make
...
Making all in src
  CC       cacheline.lo
  CC       envariables.lo
  CC       feb.lo
  CC       hazardptrs.lo
...
  CCPAS    fastcontext/asm.lo
  CC       fastcontext/context.lo
<$CHPL_HOME>/third-party/qthread/qthread-src/src/alloc/chapel.c:18:22: fatal error: chpl-mem.h: No such file or directory
 #include "chpl-mem.h"
                      ^
compilation terminated.
make[7]: *** [alloc/chapel.lo] Error 1
make[7]: *** Waiting for unfinished jobs....
<$CHPL_HOME>/third-party/qthread/qthread-src/src/affinity/hwloc_via_chapel.c:7:23: fatal error: chpl-topo.h: No such file or directory
 #include "chpl-topo.h"
                       ^
compilation terminated.
make[7]: *** [affinity/hwloc_via_chapel.lo] Error 1
make[6]: *** [all-recursive] Error 1
make[5]: *** [all-recursive] Error 1
make[4]: *** [qthread-build] Error 2
make[3]: *** [<$CHPL_HOME>third-party/qthread/install/linux64-gnu-native-flat-jemalloc-hwloc] Error 2
make[2]: *** [third-party-pkgs] Error 2
make[1]: *** [runtime] Error 2
make: *** [comprt] Error 2
```

Notes:
1. This error does not happen when `CHPL_LIBMODE` is unset (sample size = 1).
2. If I run `make -j` again right after the failure, the build completes successfully.

**Comment by lydia-duncan** [comment]
I don't get this behavior with `make clobber; make -j`.  Can you remind me what `git clean -Xfd .` does?

**Comment by BryantLam** [comment]
`git clean -Xfd .` will "remove only files ignored by Git" so it checks .gitignore and removes only those files, leaving untracked directories and files around (e.g., my scripts).

**Comment by gbtitus** [comment]
I don't have time to check this right now but will tomorrow: I'm wondering if this is due to, or at least related to, a `compileline` failure as described in #10542.

**Comment by bradcray** [comment]
Tagging @ronawho just because it's been awhile since I've had a bad case to point to for why I don't use `make -j`... :D

**Comment by ronawho** [comment]
I'm unable to reproduce this on my mac, a 24-core linux box, and a 36-core XC login node. I wonder if you have some leftover non-PIC third-party libraries left that can't be linked in or something? Maybe try doing a `make clobber` in addition to the `git clean`. I can't imagine the git clean leaving any stale third-party libs around, but I'm not sure what else to look for just yet.

re Greg's compileine note, could you see if `$CHPL_HOME/util/config/compileline --includes-and-defines` works after the build has failed?

**Comment by BryantLam** [comment]
I deleted the directory, re-cloned, and ran `make -j`. I can't reproduce this error anymore. I'm okay closing this issue out, but I'm rather befuddled at what could have caused the initial issue, especially since my build scripts currently run "git clean" before build. Sorry for the wild goose chase.

As a safety precaution, my build scripts include `make clobber` now.

**Comment by bradcray** [comment]
> As a safety precaution, my build scripts include `make clobber` now.

Superstitious invocations of `make clobber` always make me sad (I find I very rarely need to use this fallback—like maybe once every six months—and am always disappointed when I have to do so, in part on principle and in part due to the increase in build times).  Though I don't want you to suffer needlessly, if I were you, I'd try to continue living in the `make clobber`-free world; and if you were to run into this again, I'd be curious what the diff between the `git clean...` copy of the tree and the fresh snapshot were.  (e.g., I could imagine that there are some files that are not .gitignored and therefore were lingering across your `git clean...` step when you/we wouldn't have wanted them to?)

**Comment by lydia-duncan** [comment]
To follow up on Brad's comment - I think a `make clobber` should only be necessary when switching the value of CHPL_LIBMODE.  Otherwise, it shouldn't be necessary.  Once #10898 is resolved, it should stop being necessary in the CHPL_LIBMODE case as well

**Comment by BryantLam** [comment]
> (e.g., I could imagine that there are some files that are not .gitignored and therefore were lingering across your git clean... step when you/we wouldn't have wanted them to?)

@bradcray - I thought that might be the case, but `git status` didn't report any untracked files that I thought should be ignored; I could have remembered wrong. The error .. stopped happening and I didn't know what changed given the number of tries I was doing, the irregular cleaning (git, clobber, new repo), and the long build times. Next time this happens, I'll save a copy of the repo.
