### ISSUE TITLE
Spike: investigate what is required to get CSV PR into master

### ISSUE THREAD

**Issue by daviditen** [chapel-lang/chapel#10966]
Investigate what is required to merge PR #10154 and get it into a package module vs. implemented in the test directory.

**Comment by daviditen** [comment]
To get #10154 merged as a test we just need to merge master into it, fix a few simple merge conflicts, and fix a few places where classes are created without using borrow/shared/owned/unmanaged.  It should probably also have another reviewer.

The CSV module uses DataFrames, so to get CSV into the packages directory instead of the test directory, we first need to make DataFrames a package or remove the dependence on DataFrames from CSV.  We should also add a significant amount of testing for CSV before making it a package.

**Comment by bradcray** [comment]
Why does CSV depend on DataFrames?  (if anything, I'd have expected the reverse)

**Comment by daviditen** [comment]
CSV defines a function `csvDataFrame` that reads CSV into a DataFrame.  Maybe that function should just be removed or moved to DataFrames.chpl.  But then there's really not much to the CSV module anymore - just an `openCSV()` function that reads CSV data into a 2D array.
