### ISSUE TITLE
Reproduce existing LAPACK.chpl with gen scripts

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#10976]
`LAPACK.chpl` has diverged from the script-generated version. Ideally, additional changes to the module should be done in such a way that we could regenerate them with the script, so that we can automate changes made globally.

It seems like we currently need to update the `LAPACK` header, add `require` statements into function bodies instead of globally, and remove trailing whitespaces.

**Comment by ben-albrecht** [comment]
@ian-bertolacci -- FYI

**Comment by riftEmber** [comment]
I made a duplicate of this in https://github.com/chapel-lang/chapel/issues/10976 without realizing -- closing this one as the new one contains marginally more info
