### ISSUE TITLE
parse error with queried star tuple type

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11001]
``` chapel
proc f(tuple: 2*?t) {
}
f( (1,2) );
```

fails to parse

**Comment by mppf** [comment]
Doesn't work either with integral instead of ?t

**Comment by bradcray** [comment]
I changed the tags on this because I think it's one of a large number of pattern matching / generic type constraints that have never been implemented rather than something we tried or claim to support and failed to.  Give a shout if that seems wrong.

**Comment by mppf** [comment]
I implemented support for it in the normalizer in PR #10135 and my PR message claimed it worked. The pattern works if a generic type is used instead of `?t`. AFAIK that PR cleared up a large number of *pattern matching / generic type constraints that have never been implemented*.

**Comment by bradcray** [comment]
> I implemented support for it in the normalizer in PR #10135

But not the parser?  That still strikes me more like unimplemented than a bug, then.

> and my PR message claimed it worked.

I don't consider PR messages to be language documentation.

> The pattern works if a generic type is used instead of ?t

But not `integral`?  I guess that makes that case feel more like a bug to me.

**Comment by mppf** [comment]
Right, I'm just saying I view it as a bug. There's probably multiple bugs here though.

**Comment by cassella** [comment]
This works today, as written and with `integral` in place of `?t`.

**Comment by mppf** [comment]
PR #21653 will add the case discussed here as a test. Closing because this is working now.
