### ISSUE TITLE
tracking initializers & delete free spec changes for 1.18

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11018]
### Types chapter:
Class Types -> delete-free

### Conversions Chapter
Implicit Conversions -> delete free

### Methods chapter:
The Method Receiver and the this Argument -> delete-free

### Classes chapter:
Classes -> intro refers to constructors and deleting. Probably we both need to change it.
Class Declarations -> removed extern classes
Class Types -> delete free
Class Values -> delete-free
Class Fields -> initializers
Nested Classes -> initializers (removed 'outer')
Default Initialization -> initializers
Class Constructors -> initializers
User-Defined Constructors -> initializers
* example simpleConstructors.chpl -> initializers and delete-free

The Compiler-Generated Constructor -> initializers
Implicit Class Conversions -> delete-free
Common Operations -> delete-free
Deleting Class Objects -> "deinitializer" and delete-free
Class Deinitializer -> update?

### Records chapter:
Nested Record Types -> initializers (removed 'outer')
Record Initialization -> initializers
* example recordCreation.chpl -> initializers

Record Deinitializer
* example recordDeinitializer.chpl -> initializers and delete-free

TODO discuss copy initialization (CHIP 13?)

### Generics/Generic_Types:
Type Aliases in Generic Types
Parameters in Generic Types
Fields without Types
The Type Constructor
Generic Methods
The Compiler-Generated Constructor
User-Defined Constructors
* example constructorsForGenericFields.chpl -> initializers and delete-free

**Comment by mppf** [comment]
Where to define the term "copy initialize"?

**Comment by benharsh** [comment]
Perhaps in the section on records?

**Comment by mppf** [comment]
I think we need to split the "Class Constructors" section into 2 sections:
 * how to *write* initializers
 * how to *new* classes (aka call initializers)

Also the examples with both --legacy-new and --no-warn-constructors will conflict probably

**Comment by mppf** [comment]
I'll also need to edit Class Types for delete-free.

**Comment by mppf** [comment]
Where can we define "lifetime"?

**Comment by benharsh** [comment]
I'm leaning towards not defining copy initialization for now in case we accept something like the ``init=`` proposal.
