### ISSUE TITLE
Allow yielding types and params from iterators.

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#11023]
Today we generate a compiler error when an iterator tries to yield a type or param.  It seems like it would be nice to allow this in the future.

**Comment by bradcray** [comment]
There are some feature request futures for this here:

test/functions/iterators/bradc/compileTime/bothIter.future
test/functions/iterators/bradc/compileTime/paramIter.future
test/functions/iterators/bradc/compileTime/typeIter.future

**Comment by bradcray** [comment]
I just noticed that I somehow missed this issue when I was filing #12087 and am proposing we close this one and keep that one since it uses the issue template a bit better.

**Comment by lydia-duncan** [comment]
Isn't that the same one that created the futures listed in your previous comment?  I'll close either way :)

**Comment by bradcray** [comment]
No, those futures have been in there since July 2010.  It just refers to them, didn't add them.
