### ISSUE TITLE
LinearAlgebra correctness tests timeout for valgrind and baseline testing

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#11027]
The dependency-free `LinearAlgebra` interface test completes on most machines in ~50 seconds. However, it times out for `--baseline` at 5 minutes, and `--valgrind` takes ~36 minutes.

For now, we skip these configurations in the nightly testing, but it would be helpful to understand why it is taking so long and try to reduce its execution time so that we can test it with valgrind and baseline configurations.

The test lives here:

`test/library/packages/LinearAlgebra/correctness/no-dependencies/correctness.chpl`

**Comment by ronawho** [comment]
FYI the slow part seems to be here:

https://github.com/chapel-lang/chapel/blob/2a64141798e4b45d93b1c7611bd3e836a739a0df/test/library/packages/LinearAlgebra/correctness/no-dependencies/correctness.chpl#L837-L839

It might be worth lowering the size there or moving it into a different test or something.

And FWIW I only see 3s execution times on chapcs with the std config (50s total if you include the 47s compilation time.)  Getting rid of those lines I see baseline and valgrind execution finish in under 5 seconds.
