### ISSUE TITLE
Write documentation for strings

### ISSUE THREAD

**Issue by dmk42** [chapel-lang/chapel#11052]
Currently, strings lack any documentation.  That leaves us with no place to put updates when we change things, like adding UTF-8 support.

We should document the API to make it clear what is available.

**Comment by ronawho** [comment]
https://chapel-lang.org/docs/builtins/String.html ?

**Comment by dmk42** [comment]
Thanks.  I wonder where that came from.  It didn't show up in a grep at all (for things like ASCII, string, isAlpha).

**Comment by ronawho** [comment]
It's just chpldoc from the String module https://github.com/chapel-lang/chapel/blob/master/modules/internal/String.chpl

**Comment by ronawho** [comment]
```
git grep ASCII modules/
modules/internal/String.chpl:    left to do. As of Chapel 1.17, only ASCII strings can be expected to work
modules/internal/String.chpl:    Future work involves support for both ASCII and unicode strings, and
modules/internal/String.chpl:     :returns: A string with the single character with the ASCII value `i`.
...
```

**Comment by dmk42** [comment]
Never mind.  I was totally ignorant about the automatically-generated documentation, which is actually pretty good.
