### ISSUE TITLE
Merge Norm and LinearAlgebra modules

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#11068]
The [Norm](https://chapel-lang.org/docs/master/modules/packages/Norm.html) module was originally not merged into [LinearAlgebra](https://chapel-lang.org/docs/master/modules/packages/LinearAlgebra.html), because of the `BLAS` and `LAPACK` dependencies.

 Now that the `LinearAlgebra` module supports compiling without dependencies available, `Norm` functionality should be merged into `LinearAlgebra`, and `Norm` should be deprecated.

The process for doing this will go as follows:

1. Re-evaluate `Norm` interface and implementation, making any changes necessary so that it fits well into the `LinearAlgebra` interface.
2. Add `Norm` functions to the `LinearAlgebra` module.
3. Deprecate `Norm` for 1 release cycle, then remove it entirely.

**Comment by dungarpan** [comment]
@ben-albrecht Can I work on this issue?

**Comment by ben-albrecht** [comment]
Hi @dungarpan - while the implementation of this change is `easy / straightforward`, it will require consensus among the development team before proceeding. That's likely why it is not marked `good first issue`.

With code/doc freeze for Chapel 1.19 being today, this probably won't get discussed until after the 1.19 release, due to competing priorities.

Below is some feedback on your branch (https://github.com/dungarpan/chapel/commit/d54507116ad79f7ab365c918e6e80fd2339c4e04) if you want to pick this back up once it has been discussed with team.

We'll want to:

- add a deprecation message to the `Norm` module (see other deprecation warnings for example wording)
- add a line of documentation to `Norm` stating that is has been deprecated for `LinearAlgebra`
- to add a deprecation test for `Norm` (see `test/deprecation` for examples)
- Update any tests that previously used `Norm` and confirm they still work (note: they will now require `compopts`)

**Comment by Aniket21mathur** [comment]
@ben-albrecht Can I work on this?

**Comment by ben-albrecht** [comment]
@Aniket21mathur - I'm going to peel the easy sticker off of this one since it is primarily a design/consensus question for the core dev team. Once we get around to discussing and it is agreed upon, I'll put the label back on.

**Comment by ben-albrecht** [comment]
> 1. Re-evaluate Norm interface and implementation, making any changes necessary so that it fits well into the LinearAlgebra interface.

Regarding the interface, I don't have any specific changes to propose. The current interface closely follows [numpy.linalg.norm](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html) which is my typical reference for prior work.

We may add some more options like `axis` and `keepdims` in the future.
