### ISSUE TITLE
Merge HDFS and HDFSIterator modules

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#11067]
[HDFSIterator](https://chapel-lang.org/docs/master/modules/packages/HDFSiterator.html) contains a single iterator supporting the [HDFS](https://chapel-lang.org/docs/master/modules/packages/HDFS.html) module. It would be reasonable to merge this iterator into `HDFS` itself.

**Comment by krishnadey30** [comment]
@ben-albrecht I would like to take this issue.

**Comment by krishnadey30** [comment]
I have opened a PR that solves this issue https://github.com/chapel-lang/chapel/pull/12605

**Comment by ben-albrecht** [comment]
After a discussion with @mppf, it sounds like the plan is to move the HDFS module into mason and to utilize the I/O framework @mppf is working on: https://github.com/mppf/chapel/tree/io-plugins-chapel

This would make this issue redundant, therefore I'm closing this now.
