### ISSUE TITLE
Merge FFTW and FFTW_MT modules

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#11065]
[FFTW](https://chapel-lang.org/docs/master/modules/packages/FFTW.html) and [FFTW_MT](https://chapel-lang.org/docs/master/modules/packages/FFTW_MT.html) support FFTW with and without mulithreading, respectively. To my understanding, these modules can be merged (perhaps as a module / submodule).

Design decisions we need to make:

1. Should `FFTW_MT` be a submodule of `FFTW`?
2. What should we call `FFTW_MT` (submodule or sibling module)

Based on the limited feedback so far, I'll propose some strawman answers:

1. Yes
2. We call the submodule `FFTW.Multithreaded`

Lastly, there are some module-level initialization functions called in both modules. So whoever implements this needs to ensure that there are no conflicts between the module-level initialization functions (might require some additional checks before initializing).

**Comment by ben-albrecht** [comment]
@npadmana suggested this a while ago, and may be more aware of the historical reasons for these originally being split into 2 modules.

**Comment by bradcray** [comment]
I like the idea of making FFTW_MT a sub-module and renaming it to something like "MT" or "Multithreaded" or ...

**Comment by aditmehta9** [comment]
@ben-albrecht I would like to take this issue. Sir, I have made some changes please review my pull request.

**Comment by aditmehta9** [comment]
@ben-albrecht Do you think I need to make any changes?

**Comment by ben-albrecht** [comment]
Hi @aditmehta9 - while this issue is considered "easy/straightforward" to implement, there are a few open design questions that will require some feedback from the core Chapel developers. I plan to ping other developers for feedback, but this process may take a week or so.

Additionally, now that I see the code, I realize there may be some challenges in merging the module-level initialization functions. For this reason, I'm removing the "easy/straightforward" label.

**Comment by aditmehta9** [comment]
Thanks, Sir for your review.

**Comment by ben-albrecht** [comment]
From @npadmana (the author of FFTW):

> I'd suggest a different route here. The multithreaded transforms 
are not very different from the single threaded versions. In 
particular, the actual calls for the FFTs (including the FFT plan 
creation) are the same; the only difference is a setup/teardown 
and a function call to let FFTW know how many threads to use for 
subsequent plan creation. 
>
> So, I'd be tempted to merge FFTW and the FFTW_MT routines, with 
multi-threaded capabilities controlled by a config variable (so 
that it can be controlled at run time). The module deinit can be 
used to destroy any resources initialized by the module.
>
> One of the reasons we moved MT into its own module was that the 
FFTW module not only includes headers, but also specifies the 
libraries to link against. I actually think this is a bad idea, 
and we should just remove that from both, and let the user include 
the FFTW modules at link time. In which case, there is no reason 
to not just use the same module for both. And its just much 
simpler.

**Comment by aditmehta9** [comment]
> 
> 
> From @npadmana (the author of FFTW):
> 
> > I'd suggest a different route here. The multithreaded transforms
> > are not very different from the single threaded versions. In
> > particular, the actual calls for the FFTs (including the FFT plan
> > creation) are the same; the only difference is a setup/teardown
> > and a function call to let FFTW know how many threads to use for
> > subsequent plan creation.
> > So, I'd be tempted to merge FFTW and the FFTW_MT routines, with
> > multi-threaded capabilities controlled by a config variable (so
> > that it can be controlled at run time). The module deinit can be
> > used to destroy any resources initialized by the module.
> > One of the reasons we moved MT into its own module was that the
> > FFTW module not only includes headers, but also specifies the
> > libraries to link against. I actually think this is a bad idea,
> > and we should just remove that from both, and let the user include
> > the FFTW modules at link time. In which case, there is no reason
> > to not just use the same module for both. And its just much
> > simpler.

Thank you Sir I will make the required changes in some days as my exams are going on currently.

**Comment by ben-albrecht** [comment]
Closed in https://github.com/chapel-lang/chapel/pull/13248/files
