### ISSUE TITLE
should there be a way to explicitly request byte units?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11063]
We have `codePointIndex` to request code point indexing in some string functions. This issue is to ask if there should be a corresponding type for explicitly requesting byte indexing. Currently integer arguments request byte indexing.

**Comment by dmk42** [comment]
Closed by #12468 and the decision to implement `byteIndex`.  When `byteIndex` becomes available, default indexing will be by codepoint instead of by byte.
