### ISSUE TITLE
string slicing by a range of codepoints

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11062]
String support currently allows for indexing into the string with `codePointUnit` but that doesn't work to enable slicing. There is not currently a way to get a string slice with code point units.

``` chapel
var x = "éú";

var firstCodePoint = 1:codePointIndex;
var y = x[1:codePointIndex];
writeln(y);

var z = x[firstCodePoint..firstCodePoint];
writeln(z);
```

I'd expect this program to output
```
é
é
```

(but see also issue #11061 - the first line output is a numeric value currently).

**Comment by mppf** [comment]
I wonder if there should be a more general mechanism to make numbers with units, and then if ranges of united-numbers can be supported.

**Comment by dmk42** [comment]
@bradcray - Thanks for offering to create ranges of codePointIndex records.  This is just a reminder that I'll do the rest once that's available.

**Comment by bradcray** [comment]
@dmk42: Ranges of codePointIndex should now be supported as of #11231.  Let me know if you run into any problems that are obviously on my side of things.
