### ISSUE TITLE
What types should indexing and iteration return?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11061]
What types should string indexing and iteration return? 

Currently, string this sometimes returns an integer and sometimes string .

With** support for `codePointIndex`, `this` on strings now sometimes returns a `string` and sometimes returns an `int`, depending on the argument. I found this confusing when trying to create examples for the documentation.

I think that the return type of `this` is an independent question from its unit.

I'd propose that `this` always return a `string` and that a new method is created that always returns an `int` (including when byte offsets are requested).

**Comment by mppf** [comment]
I'm sure this is not a complete list but here's my attempt at pros and cons:

The argument for returning `int` is:
 * it has better performance (but #11221 is an alternative way to achieve that performance)
 * it matches C
 * it makes programs reasoning about character/code point numeric values simpler (e.g. in C it would be normal to write mystring[i] < 'a' )
 * it separates the type of a *character* from the type of a *string*

The argument against is:
 * separation of the type *character* from the type of a *string* is unnecessary and actually confusing in the face of the full variety of Unicode code points, combining characters, etc
 * it matches Python
 * reasoning about numeric code point / character values should be explicit anyway, and in many cases functions like `isLower` will suffice.

**Comment by dmk42** [comment]
Closed by #11991 and the decision to always return a string.
