### ISSUE TITLE
Spike: Investigate Fortran's story for array interoperability

### ISSUE THREAD

**Issue by daviditen** [chapel-lang/chapel#11093]
What is required to pass an array to a Fortran function from Chapel?

What is required to pass an array to a Chapel function from Fortran?

**Comment by daviditen** [comment]
Greg points out that the Fortran 2003 standard defines some C interoperability, so if the Fortran is coded to that standard we should be able to use our existing C interface.  ...At least for aspects of Fortran that match well to C.

**Comment by daviditen** [comment]
There is an Interoperability interface described in ISO TR 29113 that would be useful for passing more complicated arrays such as multidimensional slices between Fortran and Chapel.  Fortran compilers that implement this define a header file named "ISO_Fortran_binding.h" that include structures and functions to define interoperable arrays.  We could define an extern interface to "ISO_Fortran_binding.h" in order to allow passing complicated arrays.

c2chapel does a reasonable job of translating this header, but misses a lot of the macros because they aren't defined with trivial integers.  After running c2chapel we'd have to go through it by hand to add anything that was missed.  The header is around 200 lines, so would not be too bad to go through by hand.

A main piece of the Fortran/C interoperability is an array wrapper similar to [`chpl_external_array`](https://github.com/chapel-lang/chapel/issues/11167) named `CFI_cdesc_t`.  We'd want to provide wrapper functions for converting between Chapel arrays and `CFI_cdesc_t`s.

Not all Fortran compilers currently implement this, and so it would be restricted to the ones that do.  The only ones I have access to that do are Cray and Intel.  Clang and GNU do not appear to support it.  The ones that do implement it each have slightly different versions of "ISO_Fortran_binding.h", so it may require an extern interface per backend compiler.

**Comment by ty1027** [comment]
As far as I experienced, the Fortran/C interoperability for general multidimensional arrays (including allocatable arrays) is still not well supported by many Fortran compilers (as of 2018) and does not seem to be supported in the near future... So, for example, I have zero experience of  manipulating Fortran allocatable arrays via "array descriptors" from C routines. I guess it is probably sufficient if we can pass a contiguous chunk of memory between languages somehow (even via explicit reference of undelying pointers).
