### ISSUE TITLE
bare "new owned C()" leaks

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#11101]
### Summary of Problem

Writing a bare `new owned C()` without capturing the new object in a
variable causes the new object to be leaked without its deinitializer
being called.  Similarly, `new shared C()`.  `new borrowed C()` does
not leak, and the deinitializer is called.

### Steps to Reproduce

**Source Code:**

```chapel
class C {
  var x: int;
  proc init(_x) {x = _x; writeln("init(",x,")"); }
  proc deinit() { writeln("deinit(",x,")"); }
}

proc foo() {
  writeln("entering foo");
  new owned C(1);
  writeln("exiting foo");
}

foo();
writeln("returned from foo()");
writeln();

proc bar() {
  writeln("entering bar");
  new borrowed C(2);
  writeln("exiting bar");
}

bar();
writeln("returned from bar()");
writeln();

proc baz() {
  writeln("entering baz");
  new shared C(3);
  writeln("exiting baz");
}

baz();
writeln("returned from baz()");
```

**Execution command:**

```
fortytwo@magrathea:~/src/chpl$ ./delfree -nl 1 --memLeaks 
entering foo
init(1)
exiting foo
returned from foo()

entering bar
init(2)
exiting bar
deinit(2)
returned from bar()

entering baz
init(3)
exiting baz
returned from baz()

======================================================================================================================================
Allocated Memory (Bytes)                              Number   Size     Total    Description                      Address             
======================================================================================================================================
delfree.chpl:9                                        1        16       16       C                                0x00007ff3e500f110  
delfree.chpl:29                                       1        16       16       C                                0x00007ff3e500f120  
$CHPL_HOME/modules/internal/SharedObject.chpl:187     1        16       16       ReferenceCount                   0x00007ff3e500f140  
======================================================================================================================================

```

**Associated Future Test(s):**
 [`test/classes/delete-free/uncaptured-new.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/classes/delete-free/uncaptured-new.chpl
          ) #11585

### Configuration Information

```
fortytwo@magrathea:~/src/chapel (master)$ chpl --version
chpl version 1.18.0.64d5d1b
Copyright (c) 2004-2018, Cray Inc.  (See LICENSE file for more details)

fortytwo@magrathea:~/src/chapel (master)$ printchplenv --anonymize
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: intrinsics
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none

fortytwo@magrathea:~/src/chapel (master)$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
```

**Comment by cassella** [comment]
FWIW, I've since noticed that a bare `new C()` also leaks, and doesn't produce the `result of new C is now managed by default` warning that `var c = new C()` does.

**Comment by bradcray** [comment]
In working on shutting down user-level leaks in the testing system these past few weeks, I've run into at least one case of this which came from a test other than Paul's (though I need to check my other computer to remember which one it is).  I also ran into a potentially related issue in which using `new C()` as a default argument value similarly leaks and opened issue #12637 against it.

**Comment by bradcray** [comment]
I found them again.  Some tests that leak due to this issue are:

* test/classes/initializers/postInit/class-generic.chpl
* test/classes/initializers/postInit/class-nongeneric.chpl

**Comment by cassella** [comment]
Those are both `new unmanaged MyCls(10);`

**Comment by bradcray** [comment]
True.  I should've clarified that they still leak when I removed the `unmanaged`, but I'll check updates with that change to avoid confusion and shift the blame away from the user.

**Comment by bradcray** [comment]
See PR #12697
