### ISSUE TITLE
Naming convention for eigvals() in the LinearAlgebra module

### ISSUE THREAD

**Issue by ty1027** [chapel-lang/chapel#11142]
In the `LinearAlgebra` module, the `eigvals()` routine returns both eigenvalues and optionally eigenvectors (as of Chapel 1.17):

https://chapel-lang.org/docs/modules/packages/LinearAlgebra.html#LinearAlgebra.eigvals

But I guess the meaning may become more clear if the name like `eig()` (or `eigfact()`) is used instead if eigenvectors may also be returned optionally. Then, `eigvals()` may be newly defined as a wrapper routine returning only the eigenvalues, such that `eigvals(A) := eig(A, left=false, right=false)`, which may be useful to avoid possible confusion.

For comparison, I've gathered similar eigensolver routines in different libraries below:

eig() in MATLAB
https://www.mathworks.com/help/matlab/ref/eig.html?lang=en

eig() and eigvals() in Numpy
https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.eig.html
https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.eigvals.html#numpy.linalg.eigvals

(Other libraries appear to be similar...)

eig_sym() etc in Armadillo (C++)
http://arma.sourceforge.net/docs.html#eig_sym
http://arma.sourceforge.net/docs.html#eig_gen
http://arma.sourceforge.net/docs.html#eig_pair

EigenSolver() in Eigen (C++)  // this is using a different style from Matlab etc
https://eigen.tuxfamily.org/dox/classEigen_1_1EigenSolver.html

eig() etc in Julia
https://docs.julialang.org/en/v0.6.2/stdlib/linalg/#Base.LinAlg.eig
https://docs.julialang.org/en/v0.6.2/stdlib/linalg/#Base.LinAlg.eigvals
https://docs.julialang.org/en/v0.6.2/stdlib/linalg/#Base.LinAlg.eigvecs
https://docs.julialang.org/en/v0.6.2/stdlib/linalg/#Base.LinAlg.eigfact
(Edit: The latest version seems to have changed the name further to eigen() etc)
https://docs.julialang.org/en/v0.7.0/NEWS/#Deprecated-or-removed-1

eig() in Swix (Swift)  // this seems to return only eigenvalues (at the moment)
https://stsievert.com/swix/matrix.html#matrix.complex_math.eig

**Comment by ben-albrecht** [comment]
@ty1027 - Thanks for the feedback.

I agree that `eig()` would be more intuitive than `eigvals()`, and even have suggested it in an email not too long ago. I'd be in favor of adding `eig()` in place of `eigvals()`, and keeping `eigvals()` around for supporting only eigenvalues, as you suggest.

@daviditen is the original author of this procedure, and may have additional input.
