### ISSUE TITLE
spike: LLVM performance issue with array vector ops RemoveBack

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11155]
The RemoveBack test is significantly slower with --llvm than with the C backend:

https://chapel-lang.org/perf/chapcs/llvm/?startdate=2018/07/12&graphs=arrayvectoroperations

1.29 s vs 0.51 s.

The first step is to diagnose the problem

[edit: The test above was removed when array-as-vec operations were.  The following graph shows the closest equivalent:

https://chapel-lang.org/perf/chapcs/llvm/?startdate=2021/02/27&enddate=2021/05/28&graphs=listoperations

in the PopBack, Append, and RandomAccess lines]

**Comment by bradcray** [comment]
I was looking through LLVM performance issues and found that the link above doesn't work anymore.  @chapel-lang/perf-team : Anybody happen to know what happened to this graph?

**Comment by ronawho** [comment]
It was removed in https://github.com/chapel-lang/chapel/pull/14557 with the removal of array-as-vec. I believe a list equivalent was added in https://github.com/chapel-lang/chapel/pull/14821

**Comment by bradcray** [comment]
Ah, _those_ array vector ops, thanks.  I've updated the OP to include an updated link.

**Comment by mppf** [comment]
I'm closing this since it's a spike we don't plan to get back to.
