### ISSUE TITLE
adjust Chapel module to work with --llvm without a PrgEnv

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11166]
As a Chapel user on a Cray, I would like to be able to use the distributed Chapel module's LLVM backend without needing to use a particular PrgEnv C compiler. That way, using Chapel will be easier and less confusing.

The strategy here has two parts.

1. update util/config/gather-cray-prgenv-arguments.bash as follows:
 * if cc is not in the path and/or does not refer to a PrgEnv module, look for CC in /opt/cray/pe/craype/default/bin
 * try to behave as though PrgEnv-gnu is loaded for the purpose of this command by setting the environment variable`PE_ENV=GNU`

2. ~~update the Cray Chapel module to cause a GCC module to be loaded.~~ I don't think this is necessary - I think we can set GNU_VERSION instead.

Relates to #10905.

**Comment by mppf** [comment]
@ronawho @dmk42 fyi

**Comment by mppf** [comment]
I think we'll also have to set `GNU_VERSION` to 7.3.0 (or whatever version we wish).

**Comment by ronawho** [comment]
> update the Cray Chapel module to cause a GCC module to be loaded.

Why do we need a gcc module loaded?

**Comment by mppf** [comment]
I updated the issue description to cross it out because setting GNU_VERSION is probably sufficient.

**Comment by mppf** [comment]
Here is a patch that has the same effect but is arguably less brittle, because it only uses user-facing module commands:

```
diff --git a/util/config/gather-cray-prgenv-arguments.bash b/util/config/gather-cray-prgenv-arguments.bash
index d2d7cb7c..c52dd747 100755
--- a/util/config/gather-cray-prgenv-arguments.bash
+++ b/util/config/gather-cray-prgenv-arguments.bash
@@ -27,7 +27,14 @@ if [[ $FAIL == 1 || -z $2 || -z $3 || -z $4 ]]; then
     exit 1
 fi
 
-# Set up the environment to amke the proper libraries and include
+# Try loading PrgEnv-gnu if no module is loaded
+module list 2>&1 | grep -q PrgEnv
+if [ $? != 0 ]
+then
+  module load PrgEnv-gnu
+fi
+
+# Set up the environment to make the proper libraries and include
 # files available.
 export PE_PKGCONFIG_PRODUCTS="PE_CHAPEL:$PE_PKGCONFIG_PRODUCTS"
 export PE_CHAPEL_MODULE_NAME="chapel"
```

The idea here is to just run `module load PrgEnv-gnu` if no PrgEnv environment is loaded. AFAIK module commands just manipulate the environment, and since we run this in a bash script, it should have no effect outside of the script.

@ronawho - does this seem like a reasonable approach? (In sprint planning, Greg and Brad were concerned about how brittle the proposal was. This alternative just occurred to me but arguably should have been "obvious").

**Comment by bradcray** [comment]
If we'd had the time in the meeting itself for architecture discussion, this was what I was going to ask about / counter-propose.

**Comment by dmk42** [comment]
I am suddenly much less confused.  This looks like a good path to me.

**Comment by ronawho** [comment]
I think loading a PrgEnv and continuing to call `cc -craype-verbose` just to harvest the link flags is a workaround and not something we should be happy with longterm. It also takes ~2 seconds:

```
time -p cc -craype-verbose &>/dev/null
real 1.88
```

I'm ok with something like this going in as a stop-gap, but I think we really need someting more officially supported. e.g. our own driver for chapel or a more official hook into the PE drivers.

**Comment by mppf** [comment]
@ronawho - I think it's better than the previous proposal. It seems that improving the speed of it is a totally separate problem. I havn't found a solution to this that I like, though.
