### ISSUE TITLE
Add ability to dynamically link LLVM libraries

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11160]
As a Chapel developer, I'd like the Chapel compiler binary to be able to dynamically link with LLVM so that I can have more flexibility in building and installing LLVM separately from Chapel.

Dynamically linking Chapel with LLVM libraries might help with Chapel build times but at the very least it adds flexibility for packaging the Chapel compiler, especially with system installed LLVMs that don't necessarily include the .a files.

This issue adds these tasks:
 * adding the optional ability to link LLVM dynamically including with the included LLVM build
 * investigate whether activating this mechanism by default helps

**Comment by gbtitus** [comment]
Is this dynamically linking the Chapel compiler with LLVM libs or dynamically linking the LLVM-emitted executable with libraries of codegen-oriented support code?  Both, maybe?

**Comment by mppf** [comment]
It's strictly about dynamically linking the Chapel compiler.

**Comment by mppf** [comment]
On my system, linking dynamically saves about 2 seconds from the link command.
I don't see a good way to link the clang libraries dynamically, though. Clang does build a dynamic library but it doesn't have the ability to code-generate (which we need). I briefly investigated it if it's trivially easy to create a .so from several clang .a libraries, but that didn't work for me (and I don't know why). In any case it might be that improving `make` time for `chpl` itself isn't a priority enough to follow through on further design points here.

**Comment by mppf** [comment]
We were already dynamically linking the LLVM compiler with system LLVM
