### ISSUE TITLE
Make type names into reserved keywords

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#11174]
In a recent chatroom discussion, it was noted that we diverge from most languages by not making type names like `bool`, `int`, `real`, reserved keywords in Chapel.  I don't recall the reason for this anymore (*), and had long since forgotten that other languages _do_ reserve these keywords.  I think we should join the rest of the world and reserve these in order to reduce the potential for user confusion, enable syntax highlighting, etc.

* = Best guesses: There may have been some thought that doing so would someday permit users to create type aliases that change the default size of something like `int`... but this isn't likely to ever work in today's language (e.g., `type int = int(32);` presumably wouldn't work in Chapel for the same reason that `int x = 2*x;` doesn't).  Another possibility is that we simply thought we should reserve the smallest number of keywords possible; though that doesn't explain why we reserved `domain`.

**Comment by bradcray** [comment]
Tagging @e-kayrakli who seemed particularly taken aback by this.  :)

**Comment by cassella** [comment]
Is this issue a good place to request also making `true` and `false` reserved words?  (Or some other way of making `var true = false;` not valid.)  `var nil = "nada";` already doesn't compile (`syntax error: near 'nil'`).

The Chapel spec defines them to be literals.

python 3: https://stackoverflow.com/questions/18050815/why-were-true-and-false-changed-to-keywords-in-python-3
java: https://docs.oracle.com/javase/tutorial/java/nutsandbolts/_keywords.html
rust: https://doc.rust-lang.org/grammar.html#keywords
C++: https://en.cppreference.com/w/cpp/keyword

Go on the other hand allows assignments to `true` and `false`.

**Comment by bradcray** [comment]
I believe @mppf successfully resolved this issue in PR #11405 .
