### ISSUE TITLE
Move knl correctness tests from purie to kay-elogin

### ISSUE THREAD

**Issue by awallace-cray** [chapel-lang/chapel#11178]
Purie is going away ~end of Sep~ *new date: will be gone Monday Oct 8*
Kay has KNL nodes.
Should be able to run some correctness tests on kay-elogin.
Not the highest priority. 

Related, also low priority: ~rm the dead envoy jobs and slaves, clean up the JJB.~ *Done*

**Comment by gbtitus** [comment]
The Issue title says "kay-elogin2" but the [comment above](https://github.com/chapel-lang/chapel/issues/11178#issue-361303177) says "kay-elogin" so this may be superfluous info for you, but: I'd definitely recommend our scripts refer to "kay-elogin" rather than "kay-elogin2".  I strongly suspect that "kay-elogin2" was just temporary while both systems were online and will go away soon.  Those names are already synonyms, if you look at the output of `ypcat hosts | grep kay-elogin | sort -u`.

**Comment by awallace-cray** [comment]
2018-09-25
```
+ export CHPL_TEST_LAUNCHCMD=/lus/scratch/chapelu/jenkins/chapel-ci.bogus/kay-elogin2/workspace/cray-module-correctness-cray-xc-loc-knl-quad/CHPL_LAUNCHER/aprun/COMMUNICATION/ugni-qthreads/COMPILER/gnu/LOCALE_MODEL/knl/label_exp/kay-elogin2/util/test/chpl_launchcmd.py
+ CHPL_TEST_LAUNCHCMD=/lus/scratch/chapelu/jenkins/chapel-ci.bogus/kay-elogin2/workspace/cray-module-correctness-cray-xc-loc-knl-quad/CHPL_LAUNCHER/aprun/COMMUNICATION/ugni-qthreads/COMPILER/gnu/LOCALE_MODEL/knl/label_exp/kay-elogin2/util/test/chpl_launchcmd.py
+ export 'CHPL_LAUNCHCMD_HOSTLIST=1:nodetype=mom-x86_64+<num_locales>:aoe=quad_0'
+ CHPL_LAUNCHCMD_HOSTLIST='1:nodetype=mom-x86_64+<num_locales>:aoe=quad_0'
++ cnselect -c class.eq.KL
+ export CHPL_TEST_MAX_LOCALES=7
+ CHPL_TEST_MAX_LOCALES=7
+ '[' 7 -gt 4 ']'
+ export CHPL_TEST_MAX_LOCALES=4
+ CHPL_TEST_MAX_LOCALES=4
```

```
[Executing program /lus/scratch/chapelu/jenkins/chapel-ci.bogus/kay-elogin2/workspace/cray-module-correctness-cray-xc-loc-knl-quad/CHPL_LAUNCHER/aprun/COMMUNICATION/ugni-qthreads/COMPILER/gnu/LOCALE_MODEL/knl/label_exp/kay-elogin2/util/test/chpl_launchcmd.py ./hello -nl 4]
[launchcmd reports elapsed execution time for "release/examples/hello" - 21.112 seconds]
[Elapsed execution time for "release/examples/hello" - 22.015 seconds]
[Executing ./PREDIFF]
[Executing diff hello.good hello.exec.out.tmp]
1a2,5
> Unexpected KNL MCDRAM cache size 271007744
> Unexpected KNL MCDRAM cache size 271007744
> Unexpected KNL MCDRAM cache size 271007744
> Unexpected KNL MCDRAM cache size 271007744
```

**Comment by dmk42** [comment]
The error message is issued by hwloc, but the cause is a BIOS bug.  We can't do anything about this, but the tests should work anyway.

**Comment by awallace-cray** [comment]
2018-09-26 : 

> The XC system PURIE will be permanently deinstalled as of Monday, October 8.  
> After that date, 24 nodes of KNL will be installed into Jupiter 

Could run KNL test on jupiter? Depends on how Slurm works.

**Comment by dmk42** [comment]
Yes, slurm can do what we need.  The machine will have to be configured to reboot the node when a new KNL configuration is needed, just like with other WLMs.  The ability to reboot a node is not automatic; the sysadmins will need to choose it.

**Comment by awallace-cray** [comment]
2018-10-01 

> The error message is issued by hwloc, but the cause is a BIOS bug. We can't do anything about this, but the tests should work anyway.

I forgot we already have this: this fixes everything. 
`export CHPL_SYSTEM_PREDIFF=$WORKSPACE/util/test/prediff-for-knl_unexpected_cache_size`

kay-elogin will work well enough, so long as they don't take away all the KNL parts.

**Comment by awallace-cray** [comment]
2018-10-05 
This took an extra day or two because 
I also reactivated the snc4 KNL job (in addition to quad KNL) and moved it to run on kay also. 
I refactored a bunch of host-specific env variable definitions used in Cray correctness tests so that almost all of them are in the same place, ie the chapel-code scripts.
