### ISSUE TITLE
spike: comm=ofi: what to do about the hobbled 'verbs' provider?

### ISSUE THREAD

**Issue by gbtitus** [chapel-lang/chapel#11180]
One of the questions asked after a recent demo of the ofi mockup had to do with the state of libfabric/ofi support on InfiniBand-based systems such as our chapcs cluster.  I answered that the ofi `verbs` provider is "famously hobbled" compared to a number of other providers.  ("Famously" because it is easy to find people griping about this on the internet.)  The question for this issue is what to do about the verbs provider's limitations.

See `man fi_verbs` for details about the verbs provider anywhere there is a libfabric install on an InfiniBand-based system, for example chapcs.  The following are some high points, though, compared to the sockets (TCP/IP), gni (Cray Gemini/Aries), psm (Intel PSM 1.x for Intel TrueScale Fabric), and psm2 (PSM 2.x interface for Intel Omni-Path Fabric) fabrics:
- Support for RMA (direct `PUT`/`GET`) is limited and requires application support for progress on the receive side, thus is not entirely one-sided.  The other providers all support RMA fully.
- There is full support for AM-style message send/receive but not for so-called multi-receive, in which a single receive operation can specify a buffer in which multiple messages will be laid down one after another, each with its own completion queue (CQ) event, and the receiver will be informed when the buffer is used up so that it can supply another one.  Instead, the receiver must do a receive operation for every incoming message, individually.  The other providers all support multi-receive.
- An "endpoint" in libfabric can be thought of as a addressable portal to network communication capabilities, and a "context" as a transmit or receive engine associated with an endpoint.  A "scalable endpoint" is an endpoint that can support multiple transmit or receive contexts which operate independently.  To manage concurrency and improve performance (higher rates and/or greater bandwidth) in multi-threaded programs one can either use multiple endpoints or a scalable endpoint with multiple contexts, but the coding style is different for these two approaches and the former uses more network addresses.  The sockets, gni, and psm2 providers support scalable endpoints but the psm and verbs providers do not.
- The verbs provider has more limitations on which libfabric memory registration models it supports, and places more requirements on applications, than do the sockets or gni providers or, seemingly, the psm and psm2 providers (though the latter 2 man pages don't mention memory registration, so it's a hard to be confident about this in regard to them).  While both sockets and gni have flaws that prevent production use (performance for sockets, thread scalability for gni) our hope has been that going forward the providers would get easier to work with in terms of memory registration.  The verbs provider seems a step backward in this respect.

As mentioned during the demo, the libfabric interface is such that at execution time, there is an initial back-and-forth negotiation regarding what capabilities the application wants or needs and what the provider can supply.  The result is that decisions with performance and even functional implications that might have been made at design time end up instead being made in the code, at execution time.  This has some performance effect, but more importantly the resulting branchiness just makes the code more complicated.  The number of limitations in the verbs provider's capabilities will maxmize this effect, since for performance we will still want to use the capabilities it is missing with providers that do supply them.

The extreme solution would be to code two separate ofi-based comm layers, one for the verbs provider and one for everything else.  Hopefully there is a less-extreme approach that will satisfy the functional requirements but not produce a tangle in the code.  The first step should be to take a more-detailed look at the verbs provider's limitations, how each would affect the comm layer code, and how each could be best be dealt with.

**Comment by ronawho** [comment]
Note that today we use GASNet with the ibv substrate/conduit to target InfiniBand -- https://chapel-lang.org/docs/platforms/infiniband.html

We do correctness testing with this conduit, but to date we have not added performance testing (requested in https://github.com/chapel-lang/chapel/issues/6324)

We know that the ibv conduit, like the aries conduit, has the problem where all memory is registered at startup, which kills numa affinity. This is why things like STREAM triad under gn-aries are 2x behind our ugni layer (more details in https://github.com/chapel-lang/chapel/issues/5703)

While InfiniBand performance is obviously important in the medium to long term, in the short term I would expect us to use gasnet (and try to work with the gasnet team to improve affinity) before heavily investing in an ofi-ibv implementation. That said, if the ofi-ibv provider offers scalable registration (seems unlikely based on the shortcomings documented in the issue) it may be worth pursuing even if it ends up just being a point of comparison to GASNet and we keep gasnet-ibv as the default way to target InfiniBand.
