### ISSUE TITLE
spike: how to implement array initialization as initialization, not assignment

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#11195]
This is needed to enable shape preservation with ranges.

This spike is to work out a way to create an array whose elements are initialized from a given expression, ex. upon `var A = EXPR;` . Cf. currently this happens via default initialization followed by assignment.

One possible direction is to implement noinit for arrays. I.e. enable creating an array without initializing its elements. So that we can run an initializer on each array element later.

This will be a solution to:
* #11039, which is needed to enable #10899
* implement array initialization as initialization, not assignment #10374
* if the solution is based on array noinit, it should address first-touch memory allocation for arrays

Additionally, if possible support typed array initialization to solve #11498.

**Comment by mppf** [comment]
PR #15239 moves away from default-init/assign for array initialization patterns.
