### ISSUE TITLE
Release Chapel 1.18.0 Cray-XC aarch64 module (ARM)

### ISSUE THREAD

**Issue by awallace-cray** [chapel-lang/chapel#11209]
The Chapel Cray module for aarch64 (ARM-based processors) was dropped from the "Chapel 1.18.0" release completed on Sep 20 2018.  Two reasons: 
* chpldoc is broken (https://github.com/chapel-lang/chapel/issues/11119)
  * We want this fixed. However, see https://github.com/chapel-lang/chapel/issues/11209#issuecomment-425498615
* No one else is releasing software for Cray-XC aarch64 yet, at least not through Cray RM (the tool we use to release Chapel Cray modules).
  * We have to wait until everything is ready. Oct 10 at the earliest. 

Deliverable: Chapel 1.18.0 Cray-XC aarch64 module is released.

**Comment by awallace-cray** [comment]
2018-09-23 12:30

build_configs in dev (https://github.com/awallace-cray/chapel/tree/build_configs5) now produces a Chapel 1.18.0 Cray Module for aarch64, in which chpldocs works.
Also passes 100% Jenkins-driven correctness tests in sandbox.

Note: I do not know why chpldocs works when run from the build_configs version of Chapel 1.18.0 Cray module for aarch64, and does not work when run from the Jenkins-built Cray module. There must be a reason, but it is not understood yet.

However, maybe we don't need to understand it. We want to replace the legacy build scripts that Jenkins uses with "build_configs", anyway. https://github.com/chapel-lang/chapel/issues/10458

I would like to create a sandbox Jenkins job that runs build_configs in Jenkins the same way as I have just done manually, and test if chpldocs works from that Cray module.

**Comment by awallace-cray** [comment]
2018-09-28 09:50 - 

See https://github.com/chapel-lang/chapel/issues/10458#issuecomment-425497166 for status.

**Comment by awallace-cray** [comment]
2018-09-28 13:50 
The manually-built Chapel 1.18.0 Cray-XC aarch64 RPM (release candidate 1) is installed on kay-aarch only, thanks to DC Ops accepting my out-of-band PE install request (thanks Jeff)

chpldoc still works. All Jenkins tests we usually run for a Cray release module have passed, except for a handful of chpl test errors caused from using test files from the current master branch to test the older source code in the Chapel 1.18.0 release.

**Comment by awallace-cray** [comment]
2018-09-28 14:30 - On hold until PE software for Scout can be released through Cray RM. 
Est. Oct 10.

**Comment by awallace-cray** [comment]
2018-10-10
Still on hold waiting for PE

**Comment by awallace-cray** [comment]
2018-10-18
PE released two things yesterday, but Diana suggests we wait a few more days. She'll let us know.

**Comment by bradcray** [comment]
We've now released an ARM module for 1.19 and I believe have codified the steps such that future releases will also have an ARM module, so closing this.
