### ISSUE TITLE
ref to nil causes weird error message

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#11257]
```chapel
ref x = nil;
```
reports
```
error: Cannot set a non-const reference to a const variable.
```

This error message seems like a weird one for this specific case. Please fix.

Are nil references allowed? When can they occur? I am by no means suggesting we should have nil references if they cannot occur.

**Comment by mppf** [comment]
References cannot be `nil`. Objects of class type can be `nil`, but not references. PR #11258 will add a better error message.

**Comment by mppf** [comment]
Additionally references cannot be re-targeted once they are created. (But again variables of class type can do that).
