### ISSUE TITLE
Should :throws: documentation be manual or generated?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#11268]
Should `:throws:` documentation be manually written by the person writing the documentation, or should it be generated by the compiler?  (see #8867)

---------------------------------------
My opinion is that it should be manual.

My rationale for this expectation is that no other part of chpldoc requires resolution to run - while it would be handy, it opens a can of worms implementation-wise and it seems like something the author should know ahead of time instead of relying on chpldoc to tell them.

Relatedly, we have expected that the user could write documentation prior to the implementation of the function itself - return statements don't have to be present in the body for the function to be documented with a return type, but such functions would encounter an issue should they get resolved. As an example, the following file is perfectly documentable prior to the implementation of foo's body:

```chapel
/* Some documentation */
proc foo (): int { }
```

I think we should treat throws consistently with the return type in this regard.

Of course, the expectation is that the implementation of foo will be complete before the documentation gets distributed but this avoids forcing the programmer into a particular ordering for their work (which might encourage bad design)

**Comment by vasslitvinov** [comment]
I agree that :throws: can behave like :returns:.

Given that **whether** a function throws is known at parse time, I suggest that the chpldoc for any throwing function should at least indicate that it throws.

**Comment by mppf** [comment]
I'd expect chpldoc will show which functions throw in the function signature portion (listing the `throws` keyword after the arguments and closing paren). I'm happy with adding `:throws:` so users can say anything else, including describing what it can throw and what conditions cause it to do so.

**Comment by lydia-duncan** [comment]
Chpldoc already supports listing `throws` in the function's signature when present

**Comment by vasslitvinov** [comment]
> Chpldoc already supports listing throws in the function's signature when present

That should fulfill my request.

**Comment by ben-albrecht** [comment]
To clarify, `:throws:` documentation in this issue is referring to documenting what types or errors are being thrown, not whether or not the function throws, right?

**Comment by lydia-duncan** [comment]
That's correct

**Comment by lydia-duncan** [comment]
Not hearing any objections, I'm going to close this issue.  Thanks!

**Comment by cassella** [comment]
I'll close #22163 as a dup of this one, but I want to leave a pointer back that it has some thoughts on chpldoc issuing warnings when the `:throws :` clauses in doc comment are incomplete, if chpldoc were to include resolution, or have resolution artifacts available.
