### ISSUE TITLE
nightly LLVM testing should include an asserts-on build

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11266]
Right now, to save in compile time and library size, asserts are disabled by default for the LLVM libraries built with Chapel. To enable them, one can activate a Debug build with `CHPL_LLVM_DEVELOPER=1` which relates to this Makefile code:

https://github.com/chapel-lang/chapel/blob/b1c96abc3934fb649415b650e81436f2b250c817/third-party/llvm/Makefile#L8-L13

We should at least test "Hello World" in ~~~this Debug LLVM~~~ an assertions-enabled configuration and potentially other tests.  `--fast` might be worthwhile. test/performance/ferguson/ might be a good candidate as it tests --llvm-wide-opt which includes custom LLVM passes.

**Comment by vchuravy** [comment]
There is a difference between a full DEBUG build of LLVM and a build with assertions turned on. The latter is nearly as fast and if what we use in Julia to run all our CI on. With a `ccache` setup it builds in a reasonable time from scratch and we provide [caching for CI server](https://github.com/staticfloat/LLVMBuilder)

To enable asserts outside a debug build pass: `-DLLVM_ENABLE_ASSERTIONS:BOOL=ON`

**Comment by mppf** [comment]
@vchuravy - thanks!
