### ISSUE TITLE
Reword range error messages to avoid `int`-only implication

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#11277]
Range error messages currently use phrases implying that only `int` ranges are supported,
which is no longer true.  This task involves rewording the error messages to make them more
general and accurate in today's richer world of ranges.

**Comment by cassella** [comment]
I don't see any errors (checking only `compilerError()`s in `ChapelRange.chpl` that specify or imply `int`.  A few mention `integral`.  Are there still any problematic ones?

**Comment by bradcray** [comment]
This situation does seem to have improved since I filed this—thanks!  (note to self: be more clear about what error messages you're referring to in the future)
