### ISSUE TITLE
spike: Chapel memory model understanding and reassurance

### ISSUE THREAD

**Issue by gbtitus** [chapel-lang/chapel#11280]
I am not sufficiently familiar with the Chapel memory model, its implications, and the implementation both in terms of what is done and what remains to do.  I need to spend time getting comfortable with all these.  This initial issue is a spike, because I don't know how much trouble I'll have grappling with the topic.

**Comment by daviditen** [comment]
I think the "user issue" label should be removed from this?

**Comment by gbtitus** [comment]
Does 'user issue' mean specifically that there is an Issue in an issue tracker for this somewhere?  If so then yes, I should remove the label.  I added it thinking it meant a user's experience with Chapel was what led me to take this on right now.

**Comment by gbtitus** [comment]
I only spent about 1 day on this, but I think I gained enough knowledge to hold my own for the time being, so I'm closing it.
