### ISSUE TITLE
array + loop-expr + initializer woes

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#11299]
This is an exposé of known issues throw a user's eye. "I wrote this simple program, it did not work, it took a lot of under-the-hood knowledge to make it work, and the error messages did not help much." Here, the user was Vass.

Here is the program I'd like to write:

```chpl
class CCC {
  const yyy: int;

  proc init(idy: int) {
    writeln("CCC.init ", idy);
    yyy = idy;
  }

  proc deinit() {
    writeln("CCC.deinit ", yyy);
  }
}

record RRR {
  const xxx: int;
  const cls: owned CCC;

  proc init(idx: int) {
    writeln("RRR.init ", idx);
    xxx = idx;
    cls = new owned CCC(idx);
  }

  proc deinit() {
    //delete cls; // not needed when it is 'owned'
    writeln("RRR.deinit ", xxx);
  }
}

proc helper(x: int) {
  return new RRR(x);
}

proc main {
  const array = for i in 1..3 do helper(i);
  writeln(array);
}
```

Here is what it took to make it work:

* Add `RRR.init()` with no arguments. That's because `array`'s elements are default-initialized at first.

* Switch RRR's fields from `const` to `var` because `array`'s elements are getting assigned from `helper(i)`, and `const` fields prevent assignment.

* Switch `cls` from `owned` to `unmanaged`. Something was not working with `owned`. Because of that, uncomment `delete cls` in RRR.deinit().

* Add a copy-initializer to RRR. Since the copy-initializer needs to transfer the reference in the `cls` field from the source to the destination, the source formal needs to be `ref`. Cf. the source is `const ref` in the compiler-generated copy-initializer.

Below is a working version of the above. It executes an unnecessary pair of init+deinit for each element of `array`.

```chpl
class CCC {
  const yyy: int;

  proc init(idy: int) {
    writeln("CCC.init ", idy);
    yyy = idy;
  }

  proc deinit() {
    writeln("CCC.deinit ", yyy);
  }
}

record RRR {
  var xxx: int;
  var cls: unmanaged CCC;

  proc init() { }

  proc init(ref other:RRR) {
    writeln("RRR.copy ", other.xxx);
    this.xxx = other.xxx;
    this.cls = other.cls;
    other.cls = nil;
  }

  proc init(idx: int) {
    writeln("RRR.init ", idx);
    xxx = idx;
    cls = new unmanaged CCC(idx);
  }

  proc deinit() {
    delete cls; // not needed when it is 'owned'
    writeln("RRR.deinit ", xxx);
  }
}

proc helper(x: int) {
  return new RRR(x);
}

proc main {
  const array = for i in 1..3 do helper(i);
  writeln(array);
}
```

Bonus: here is an even-smaller program that currently does not compile:
```chpl
class CCC { }

record RRR {
  const cls: owned CCC;

  // This example breaks with or without this init().
  proc init() {
    cls = new owned CCC();
  }
}

proc helper() {
  return new RRR();
}

proc main {
  var rrr = helper();
}
```

Test:
```
test/classes/initializers/records/array-from-for-expr.chpl
```

**Comment by bradcray** [comment]
I'm trying to understand what it would take to close this issue.  It currently feels like several issues jammed together that would be better teased apart.

**Comment by vasslitvinov** [comment]
It may be wise to come back to this after we resolve #10374 and move away from initCopy to init/init=.

**Comment by bradcray** [comment]
I'm still not clear what we'd be coming back to.  This issue is labeled "woes" and lists things you ran into, but it's not clear what specific thing would need to be fixed / resolved in order to close it.

**Comment by bradcray** [comment]
Offline, we discussed this and Vass said that the way to close this issue is to get the test that the issue names de-futurized.  This issue is hard to focus on in and of itself because it encompasses several distinct issues, so I'm moving it to the icebox for now and hoping that other existing issues subsume this one.

**Comment by cassella** [comment]
> Bonus: here is an even-smaller program that currently does not compile:

It compiles now.
