### ISSUE TITLE
preserve the line number when re-throwing an exception

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#11300]
A Chapel user may want to write code that reacts to an exception from a called function then re-throws it so that it is handled higher up in the call stack.

When this re-thrown exception is caught higher up in the call stack, we want it to report the file/line number for the location where it was thrown originally, not where it was re-thrown. Right now the latter happens.

For example:
```chpl
proc willthrow() throws {
  throw new Error();          // original throwing location
}

proc rethrow() throws {
  try {
    willthrow();
  } catch e {
    ... some actions upon an exception: examine it, do cleanup, etc. ...
    throw e;                 // re-throwing location
  }
}

proc main throws {
  rethrow();
}
```
Upon execution, we want the program to report the uncaught exception as originating in willthrow(), not in rethrow().

Test:
```
test/errhandling/errorMessages/preserveLineNoUponRethrow.chpl
```

**Comment by vasslitvinov** [comment]
@mppf fyi

**Comment by vasslitvinov** [comment]
@cassella mentions that other languages use `throw;` without the expression to indicate re-throwing of the error that triggered the current `catch` clause.

@cassella also reminded me that in Java, in my recollection, the file/line number of an error object is set when that object is created, regardless of where it is thrown. In order to record the location of the throw ing statement, a wrapper error would be used, something like:
```
throw new Error(anAlreadyExistingError);
```

**Comment by dlongnecke-cray** [comment]
I have an implementation of this that works, however it does incur a runtime penalty because it uses a flag (that is a field of Error) to prevent file/line IDs from being set more than once.

I am trying to find a compile-time only solution, but it is proving to be a bit more difficult because calls to `chpl_fix_thrown_error` are inserted early on during normalization.

---

Question: Is it worth the extra time I'll need to implement a version with no runtime overhead? Or should I open a PR with the simple version now?

**Comment by dlongnecke-cray** [comment]
> @cassella mentions that other languages use `throw;` without the expression to indicate re-throwing of the error that triggered the current `catch` clause.
> 
> @cassella also reminded me that in Java, in my recollection, the file/line number of an error object is set when that object is created, regardless of where it is thrown. In order to record the location of the throw ing statement, a wrapper error would be used, something like:
> 
> ```
> throw new Error(anAlreadyExistingError);
> ```

If we were to go with the approach used by Java, which ties the file/line of an error to the point of their initialization, then implementing the desired behavior with no runtime overhead would be trivial.

Do we want to do this?

**Comment by bradcray** [comment]
> Is it worth the extra time I'll need to implement a version of this behavior with no runtime overhead?

Is the runtime overhead incurred only when an error condition occurs?  If so, that doesn't seem like a big concern to me (i.e., something exceptional / erroneous happened, so who cares if it's a little slower).  If the impact occurred on the error-free path as well, that would be more concerning.

**Comment by dlongnecke-cray** [comment]
> > Is it worth the extra time I'll need to implement a version of this behavior with no runtime overhead?
> 
> Is the runtime overhead incurred only when an error condition occurs? If so, that doesn't seem like a big concern to me (i.e., something exceptional / erroneous happened, so who cares if it's a little slower). If the impact occurred on the error-free path as well, that would be more concerning.

Calls to `chpl_fix_thrown_error` (which inserts line/file info) are inserted into the AST after every `throw` statement in `compiler/passes/normalizeErrors.chpl`.

```cpp
    INT_ASSERT(call->numActuals() == 1);
    CallExpr* callFixError = new CallExpr("chpl_fix_thrown_error",
                                          call->get(1)->remove());
    call->insertAtTail(callFixError);
```

The simple version modifies the body of `chpl_fix_thrown_error` rather than removing calls we don't need.

**Comment by bradcray** [comment]
So are you saying "yes, the runtime overhead is only incurred when an error condition occurs"?

**Comment by dlongnecke-cray** [comment]
It occurs every time an error is _thrown_ (do we consider that to be an error occurring? A seemingly dumb question, but still).

Sounds like it's an OK solution either way, so I'm going to open a PR for it.

**Comment by bradcray** [comment]
I think so.  Or maybe put another way: I don't think we should worry overmuch about throws needing to be as cheap as possible.
