### ISSUE TITLE
Cannot array-initialize an array of owned objects

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#11328]
```chapel
class Foo {
  var data: int;

  proc init(x: int) {
    this.data = x;
  }
}

// This compiles.
var goodfoo: [1..2] owned Foo;
goodfoo[1] = new owned Foo(1);
goodfoo[2] = new owned Foo(2);

// This fails to compile.
var badfoo: [1..2] owned Foo = [new owned Foo(1), new owned Foo(2)];
```
emits
```
error: type mismatch in assignment from Foo to _owned(Foo)
```
using `chpl version 1.18.0`.

**Comment by benharsh** [comment]
@mppf : I think this can be fixed by making ``chpl__buildArrayExpr`` use in-intent instead of blank intent. Does that sound like the right approach?

**Comment by BryantLam** [comment]
FYI -- Ran into this issue again.

**Comment by bradcray** [comment]
@mppf: I wanted to check in and see what your thoughts on this issue are w.r.t. recent discussions about undecorated class types and generic programming.  E.g., is this issue likely to self-resolve with upcoming changes, or are additional changes likely to be required?

**Comment by mppf** [comment]
I'm guessing the upcoming changes will help but that there will be some minor effort here
