### ISSUE TITLE
comparison operators for records

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11347]
The compiler currently generates <, <=, >=, > comparison operators for tuples but not for user-defined records. It does generate == and != for records.

I think the compiler should generate <, <=, >=, > for records as well. This would make certain patterns easier to express.

**Comment by mppf** [comment]
See also #8545 which proposes comparison operator as `<==>`, `<=>`, or maybe `<~>`.

**Comment by bradcray** [comment]
I'm having trouble finding a good explanation for "why", but for some reason, it gives me pause to support relational operators (<, >, <=, >=) on records.  Even on (heterogeneous) tuples, it gives me pause; homogeneous ones, less so.

**Comment by bradcray** [comment]
> We already support the relational operators on tuples.

I understand, I'm just saying that I've never been completely comfortable with them either, particularly in the heterogeneous case.

My hesitation isn't about floating point or class pointers, though (although the class pointer case is an interesting one).  It's more that when I create multi-field records, I don't think I often think of them as having an intrinsic ordering based on the order in which I've declared the fields.  I could learn that obviously, but I think it'd be more surprising for me to find that all/most records had default relational operators than to find out that they did not.

**Comment by mppf** [comment]
Another interesting point is that multi-dimensional arrays don't necessarily have a well-defined ordering. I think it'd be reasonable to handle all of these cases with a compilation error in the default generated `<`.

> My hesitation isn't about floating point or class pointers, though (although the class pointer case is an interesting one). It's more that when I create multi-field records, I don't think I often think of them as having an intrinsic ordering based on the order in which I've declared the fields. I could learn that obviously, but I think it'd be more surprising for me to find that all/most records had default relational operators than to find out that they did not.

It's just a default. If the default `<` implementation based on field ordering isn't what you want, you'd create a `<` overload yourself (or a comparator for things like `sort`). If you need to specify the ordering, you have to create this `<` overload whether or not we have this default.

The difference is just what behavior people get when they try to use `<` on a record and when they havn't added an `<` overload. We can choose between:
 1. It's a compilation error (that we can hopefully make less ridiculous than listing all `<` overloads in the program), or
 2. In many (most?) cases, the compiler generates a `<` that does *something* by default, but might not be appropriate in all cases.

The desire to have `<` by default is similar to the desire to have everything support a hash function. We'd like to allow many (most?) types to be stored in an associative domain, right? Would you agree that the fact we use a hashtable right now, rather than a binary tree, is an implementation choice rather than a fundamental one? (E.g. C++ std::map uses a tree...) If we used a tree, allowing most types to be stored in an associative domain without adding `<` overloads would require us to generate `<` by default for most types.

In fact my past history of being happy with OCaml generating `<` by default was in the context of wanting to use my types in a tree-based data structure. In this context, it's not actually that important what the exact ordering generated by `<` is - it's just important that there is one.

A programmer who cares about the exact ordering of `<` will probably need to write a `<` overload or be careful about the order of fields in their record - but I think it's reasonable to expect them to discover this through the normal process of running / testing their program.

**Comment by benharsh** [comment]
FWIW, it looks like python2 had default object comparison but dropped it for python3.

I'll add a third option to the mix, though I doubt it would satisfy either of you. In Rust you can derive the [PartialOrd](https://doc.rust-lang.org/std/cmp/trait.PartialOrd.html) trait manually, which will generate an implementation for the less-than operator based on the order of the fields.

This might satisfy the concerns about "having a surprising default" and "providing an easy path to a < implementation", but not the concerns about "field order is a weird choice" or "providing a default for users".

**Comment by mppf** [comment]
From that C++ `<=>` proposal document http://open-std.org/JTC1/SC22/WG21/docs/papers/2017/p0515r0.pdf :

> In previous discussions, including in Oulu plenary discussion and Issaquah EWG discussion, a number  of experts said that when there are no user - declared comparisons, they were happy to have compiler-generated == and  !=comparisons, but expressed sustained concerns about having compiler-generated ordered comparisons <, >, <=, and <=for a variety of reasons, such as that the 
result was not semantically meaningful to the class, and/or that it exposed the implementation 
detail of the data member order. Note that this paper’s key design principle that 
by default,  a = b implies  a == b is a direct and strong argument for compiler-generated == and !=, but is silent about whether to generate the others. (I personally don’t share the concern
and prefer Option 2; as others have also noted, private members are not exposed, and the observable side effect of their type and order on compiler-generated comparison doesn’t seem much different from other observable side effects of data members’ type and ordering, such as whether their copying throws. 

I think some of these concerns are a different way to state Brad's position.

> If we choose to accept §3.1.3 to generate == and != but not  ordered comparisons (<, >, <=, >=) when there are no user-declared comparisons, some experts would like the set<Point>in the previous section to work anyway by default even though Point has no < comparison.

I think it'd be to our advantage if simple types didn't need a comparison overload to go into a set / associative domain, even if that set is implemented with a binary search tree. I believe that this is the reason that the compiler generates hash functions for all types by default today.

**Comment by bradcray** [comment]
These comments:

> In fact my past history of being happy with OCaml generating < by default was in the context of wanting to use my types in a tree-based data structure. In this context, it's not actually that important what the exact ordering generated by < is - it's just important that there is one.

> I think it'd be to our advantage if simple types didn't need a comparison overload to go into a set / associative domain, even if that set is implemented with a binary search tree. I believe that this is the reason that the compiler generates hash functions for all types by default today.

make me wonder whether the compiler should instead provide an `treeOrder(x,y): bool` function which invokes `<` if available and does something arbitrary but deterministic if not.  I realize there's no deep difference between the two, and yet...

**Comment by mppf** [comment]
@bradcray - that's also a path the C++ working group was discussing. No idea where they ended up though (and I'm not really sure how to find that out).

From the same C++ <=> proposal document http://open-std.org/JTC1/SC22/WG21/docs/papers/2017/p0515r0.pdf :
> If we choose to accept §3.1.3 to generate == and != but not ordered comparisons ( <, >, <=, >=) when there are no user - declared comparisons, some experts would  like the  set<Point> in the previous section to work  anyway by default even though  Point has no < comparison. Two ways to achieve that are: (a) Change std::set et al. to use the std::weak_order() function in §2.5;  this  would be a binary breaking change for the ordered associative containers. Alternatively: (b) Extend std::less to use the same fallback strategy as the function templates in §2.5, to add additional fallbacks not legal today...

At the moment, I personally like the idea of:
 * compiler always generates a generalized comparator for a type
 * the generated comparator is not called `<==>` (or whatever we end up with as the comparison operator) but rather something else like `default_comparator` or `arbitrary_ordering` or something. These would need to call a user's `<==>` or `==` or `<` etc if they exist.
 * a `set` type based on a tree can call `default_comparator` rather than `<==>` or `==` or `<`
 * arrays will need a`default_comparator` than returns `bool` rather than an array of `bool` (since `default_comparator` is intended for use in generic code rather than to be called directly)

**Comment by bradcray** [comment]
I think the above proposal would work for me.  I'm assuming no current comparison capability goes away in this proposal (?).

**Comment by mppf** [comment]
>  I'm assuming no current comparison capability goes away in this proposal (?).

That's my understanding. We could optionally consider deprecating array.equals (in favor of `default_comparator`) or normal comparison overloads like `<` (in favor of `<==>`), but I wasn't proposing that. Either way I think the main remaining work is to decide on some details of `<==>` (see the comments at the end of #8545).

**Comment by mppf** [comment]
Besides a tree-based set, I think it's reasonable to want to be able to sort records, even if `<` does not work on them for some reason. Do you think sorting could/should also use `default_comparator`?

**Comment by bradcray** [comment]
@mppf: Should classes support default comparators as well?  (based on the class fields, not on the pointer's value).  I'd imagine the implementation to be identical to records.

**Comment by mppf** [comment]
@bradcray - if pointer comparison is rare in Chapel, then yes, I think that'd be reasonable. Of course nilable classes have to worry about where nil sorts in the order.

Also in this issue we discussed some other things (like `<==>` or `default_comparator`) but I think the current direction is to generate `<` `<=` etc overloads by default. (And these would call `<==>` one day if we add it, presumably).

**Comment by mppf** [comment]
Adding `<` on classes would be problematic if it made `==` pointer-equality but `<` compare fields.

**Comment by bradcray** [comment]
> Should classes support default comparators as well?

I asked this thinking that the goal was to have all records support a working default `<` operator and wondering what we'd do about class fields.  Re-reading, I'm seeing that the goal would more likely be phrased as "sufficiently simple records should support a working default `<` and so we can say that those containing classes are not sufficiently simple.  Michael's point about `==` and `<` having pretty different meanings for classes sticks for me as well (as a reason not to support default `<` for classes).

**Comment by e-kayrakli** [comment]
What is "sufficiently simple"? I am not necessarily asking for clear lines, but what if the class has an `<` overload? Then, does the record containing that class support `<`, too? (Assuming all the other fields of the record do)

To me the answer should be yes: if the compiler can resolve an operator for all the fields of the record, then it should be able to resolve the operator for the record.

**Comment by e-kayrakli** [comment]
After a round of standard paratest, the only failure was `test/library/packages/Sort/errors/errors-key.chpl` and that brings up the somewhat philosophical question of what happens with empty records:
```chapel
record R {}
var r1 = new R();
var r2 = new R();
writeln(r1<r2);
```
I see two options
1. Print false, because they are equal
2. Make this a compiler error, because they don't contain any data for which comparison makes sense

1 makes more sense to me from consistency standpoint (empty records are not that special, are they?)

**Comment by mppf** [comment]
Yes I'd do 1 in that case

**Comment by bradcray** [comment]
I agree that two empty records should be considered equal.
