### ISSUE TITLE
forgotten zip keyword leads to memory leak

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11342]
In this program:

``` chapel
var A:[1..10] int = 1;
var B:[1..10] int = 2;

for (a,b) in (A,B) { // OOPS! forgot zip keyword
  a = b;
}

writeln(A);
writeln(B);
```

the compiler doesn't give any error or warning that the zip keyword was forgotten. Could it?

In any case the program leaks memory.

**Comment by mppf** [comment]
Right, but in this program, I don't see how the compiler can meaningfully interpret it as tuple iteration.

If I had `for a in (A, B)` then yeah, a could be A and then B, but what does the compiler think it's doing with (a,b) ?

**Comment by bradcray** [comment]
That is definitely weird.  What are the types of `a` and `b` within the loop?

**Comment by mppf** [comment]
@bradcray - `int`

**Comment by bradcray** [comment]
Huh... weird.

**Comment by cassella** [comment]
Does this help?

```chapel
var A:[1..10] int = 1;
var B:[1..10] int = 2;

for i in 1..10 {
        A[i] = i;
        B[i] = 11*i;
}

for (a,b,c) in (A,B) { // OOPS! forgot zip keyword
  writeln("a: ", a, " b: ", b, " c: ", c);
  a = b;
}

writeln(A);
writeln(B);
```

```
a: 1 b: 2 c: 3
a: 11 b: 22 c: 33
1 2 3 4 5 6 7 8 9 10
11 22 33 44 55 66 77 88 99 110
```


This is exciting,

```chapel
for (a,b,c,d,e,f,g,h,i,j,k,l,m) in (A,B) { // OOPS! forgot zip keyword
  writeln("a: ", a, " b: ", b, " c: ", c, " ... m: ", m);
```
```
fortytwo@magrathea:~/src/chapel (master)$ ./nozip -nl 1
nozip.chpl:9: error: halt reached - array index out of bounds: (13)
fortytwo@magrathea:~/src/chapel (master)$ chpl --fast nozip.chpl
fortytwo@magrathea:~/src/chapel (master)$ ./nozip -nl 1
a: 1 b: 2 c: 3 ... m: 0
a: 11 b: 22 c: 33 ... m: 0
1 2 3 4 5 6 7 8 9 10
11 22 33 44 55 66 77 88 99 110
```

**Comment by bradcray** [comment]
> Does this help?

I think it's just hurting my head and heart anyway.

**Comment by mppf** [comment]
I wish I had the label "Weird Bug".

**Comment by cassella** [comment]
> I wish I had the label "Weird Bug".

I believe it is within your power to make that happen.

**Comment by mppf** [comment]
> Right, but in this program, I don't see how the compiler can meaningfully interpret it as tuple iteration.
> If I had for a in (A, B) then yeah, a could be A and then B, but what does the compiler think it's doing with (a,b) ?

So, I think the compiler is interpreting it as:
 * tuple iteration that yields index=A and then index=B
 * var (a, b, c) = index

Here is an (arguably?) more reasonable program that does the same thing:
``` chapel
var A:[1..2][1..3] int;

A[1][1] = 11;
A[1][2] = 12;
A[1][3] = 13;
A[2][1] = 21;
A[2][2] = 22;
A[2][3] = 23;

for (a,b,c) in A {
  writeln("a=", a, " b=", b, " c=", c);
}
```

But the equivalent expression in a non-loop context gives an error:
``` chapel
var A:[1..2][1..3] int;
var (x,y,z) = A[1];
```

```
error: illegal tuple variable declaration with non-tuple initializer
```

I'm looking at extending this error to the loop case.
