### ISSUE TITLE
tuple iteration does not allow modification of components

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11357]
``` chapel
param n = 3;
var threeReals: n*real;
for r in threeReals {
  r += 1.0;
}
writeln(threeReals);
```

This program fails to compile with an error like
```
tt.chpl:4: error: illegal lvalue in assignment
```

I would expect tuple iteration to allow modification of the tuple components, in the same way that array iteration allows modification of array elements.

The spec says in section 15.4 "The iterator variable for an tuple iteration is a either a const value or a reference to the tuple element type, following default intent semantics"

**Comment by bradcray** [comment]
When you say "the spec says..." is the implication that you think the spec should be changed to match your expectation, or that you think the implementation is not implementing what the spec says?

**Comment by mppf** [comment]
> When you say "the spec says..." is the implication that you think the spec should be changed to match your expectation, or that you think the implementation is not implementing what the spec says?

I think the spec should be changed, but I was mainly noting that we'd need to update it if we decide to change the behavior.
