### ISSUE TITLE
Improve error message for undefined cast for records

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#11368]
### Summary of Problem
An undefined cast to a record type results in a misleading error message, referring to the record as a *non-type*.

### Steps to Reproduce

**Source Code:**

```chapel
record R { }

var a = 1:R;
```

```
error: illegal cast to non-type
```

This error message can be  emitted from `functionResolution.cpp` and `preFold.cpp`.

For reference, the class-equivalent seems more reasonable:

```chapel
class C { }

var a = 1:C;
```

```
error: illegal cast from int(64) to C
```

### Configuration Information

- Output of `chpl --version`: `chpl version 1.19.0 pre-release (72480ce5ea)`

**Comment by ben-albrecht** [comment]
The desire to improve this error message was motivated by #11365

@bradcray may be interested.

**Comment by cassella** [comment]
The error message is more like the `class` case today:

```
foo.chpl:3: error: illegal cast from int(64) to R
```

Though I don't see a test locking it in.

**Comment by jabraham17** [comment]
> The error message is more like the class case today:

Thanks @cassella, https://github.com/chapel-lang/chapel/issues/11368 will lock in the nice error message and resolve this issue
