### ISSUE TITLE
Crypto module thread safety issues

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11366]
I'm seeing apparent thread safety issues with the Crypto module.

For example, the following program reliably core-dumps with openssl 1.0.2.

``` chapel
config const n = 100;

proc main(){
  use Crypto;

  var SHA2 = new owned Hash(Digest.SHA256);
  var s = "The quick brown fox jumps over the lazy dog";
  writeln(s);

  var buf = new owned CryptoBuffer(s);

  var digests:[1..n] owned CryptoBuffer;
  forall i in 1..n {
    digests[i] = SHA2.getDigest(buf);
  }
}

```

OpenSSL apparently needs some callback functions to be set for locking to work right. See
https://groups.google.com/forum/#!topic/mailing.openssl.users/ttj-E155rZM

**Comment by mppf** [comment]
@saru95 - perhaps you'll be able to have a look at this, thanks.

**Comment by saru95** [comment]
@mppf I'll look at it this week. Thanks for pointing this out.

**Comment by reuster986** [comment]
Any updates on this thread? I'm attempting to hash many strings in parallel and running into this issue.

**Comment by mppf** [comment]
@reuster986 - perhaps you could use the Chapel-native SHA-256 implementation in test/exercises/duplicates/forStudents/SHA256Implementation.chpl if that will work for you.

Otherwise, somebody will have to update the OpenSSL integration.

**Comment by reuster986** [comment]
@mppf thanks for the tip! I will give it a shot.
