### ISSUE TITLE
Declaring Matrix of bigints

### ISSUE THREAD

**Issue by octonion** [chapel-lang/chapel#11365]
### Summary of Problem

One method for declaring a matrix of type bigint works; another fails. I believe both are intended to work.

### Steps to Reproduce

```chapel
use BigInteger;
use LinearAlgebra;

// Works

var P = Matrix(2,2,eltType=bigint);
P = Matrix([0,2],[3,1]);

// Fails
// $CHPL_HOME/modules/packages/LinearAlgebra.chpl:382: In function 'Matrix':
// $CHPL_HOME/modules/packages/LinearAlgebra.chpl:394: error: illegal cast to non-type

var Q = Matrix([0,2],[3,1],eltType=bigint);
```

**Compile command:**
```
chpl -lblas main.chpl
```

**Execution command:**
```
./main
```

### Configuration Information

- Output of `chpl --version`:
```
chpl version 1.18.0
```
Copyright (c) 2004-2018, Cray Inc.  (See LICENSE file for more details)
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: intrinsics
CHPL_GMP: none
CHPL_HWLOC: hwloc
CHPL_REGEXP: none
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by ben-albrecht** [comment]
Thanks for reporting. I believe this is a result of a lack of user-defined casts from integral types to `bigint`. Should be an easy fix to add this cast.

**Comment by ben-albrecht** [comment]
This should be fixed now - thanks again for reporting @octonion.
