### ISSUE TITLE
param-hex-string concatenation emits wrong result

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#11376]
```chapel
param a = "12";

param pstr1 = "\x30";
param pstr2 = pstr1 + a;

var vstr1 = pstr1;
var vstr2 = vstr1 + a;

writeln(pstr2);
writeln(vstr2); // "012"
writeln(pstr2 == vstr2);
```
emits a backend C-compiler warning
```bash
ChapelStringLiterals.c: In function ‘chpl__initStringLiterals’:
/tmp/chpl-lam-9397.deleteme/ChapelStringLiterals.c:260:38: warning: hex escape sequence out of range
 init26(&initTemp81, ((c_ptr_uint8_t)("\x3012")), INT64(3), INT64(4), UINT8(false), UINT8(false), INT64(1816), INT32(8));
                                      ^
```
and outputs the wrong runtime result
```
./app 
i
012
false
```
The first output from `pstr2` is a garbage value. The actual result should be true.

`chpl version 1.19.0 pre-release (449409b)`

**Comment by mppf** [comment]
Right now, the compiler stores string literals internally in escaped form. I think this bug is reasonable justification to store them in un-escaped form and then do the escaping when emitting them.
