### ISSUE TITLE
Feature request for integer-literal separators

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#11378]
Feature Request. Could I get an integer-literal separator?

C++14 uses the quote character.
> Optional single quotes(') may be inserted between the digits as a separator. They are ignored by the compiler. ... `unsigned long long l2 = 18'446'744'073'709'550'592llu; // C++14`

Rust uses underscores.
> * All number literals allow _ as a visual separator: 1_234.0E+18f64

Swift also uses underscores.

**Comment by lydia-duncan** [comment]
Is the intention behind this something like the comma in English numbers?  i.e. 1,200 == 1'200 in C++?

**Comment by BryantLam** [comment]
Yep. It's basically just to break up long literals to be more readable.

**Comment by daviditen** [comment]
I think underscores to separate groups of three digits would make the most sense for this.  I don't think we can use commas because it would be ambiguous with tuples and function arguments.  I don't think we can use quotes like c++14 because it would be ambiguous with single-quoted strings.

I think the separators should only be allowed after every third digit from the right.  These should be allowed:
```
123_456_789
1_234
12_345
```

These should not be allowed:
```
123_45
_123
123_
```

I think supporting this for decimal integer literals makes sense and would be useful.  It may also be useful for the other supported integer literal bases (binary, octal, hexadecimal) and for floating point literals.

**Comment by benharsh** [comment]
I'm not sure about only allowing the underscore after three digits. At a glance, I'm not seeing other languages with that restriction.

A motivating example might be a phone number:
```
555_867_5309
```

This python PEP has links to this kind of feature in other languages: https://www.python.org/dev/peps/pep-0515/#prior-art

**Comment by daviditen** [comment]
> I'm not sure about only allowing the underscore after three digits. At a glance, I'm not seeing other languages with that restriction.

OK, removing that restriction sounds fine to me.

**Comment by bradcray** [comment]
Should non-decimal (binary, hex, octal) literals support these as well?  My thinking is yes, particularly if we're not limiting it to marking thousands places.  For example, I could imagine it being useful to separate binary literals into chunks of 8 bits, hex to chunks of 4 or 8 hex symbols, etc.  (With a quick glance, it appears the Python PEP suggests they went that route as well?).

**Comment by daviditen** [comment]
> Should non-decimal (binary, hex, octal) literals support these as well?  [edit: Oh, and floats as well?]

I also think yes.

**Comment by mppf** [comment]
and floating point values!

**Comment by dmk42** [comment]
I agree with removing the three-digit restriction.  Although western countries tend to group three digits at a time, the most important powers of 10 in Japan are multiples of four.

**Comment by daviditen** [comment]
Closed with PR #11464.

**Comment by ronawho** [comment]
Do we want/expect this to work for config vars and/or string->int casts?

```chpl
config const i = 1_000;
writeln(i);
```

```
./configUnderscore --i=1_000
uncaught IllegalArgumentError: bad cast from string '1_000' to int(64)
  $CHPL_HOME/modules/internal/ChapelBase.chpl:1073: thrown here
  $CHPL_HOME/modules/internal/ChapelBase.chpl:1079: uncaught here
```

```chpl
const i = "1_000":int;
writeln(i);
```

```
./castUnderscore
uncaught IllegalArgumentError: bad cast from string '1_000' to int(64)
  castUnderscore.chpl:1: thrown here
  castUnderscore.chpl:1: uncaught here
```

**Comment by ronawho** [comment]
> That's a good question. I think it's worth opening a design issue to consider this question.

https://github.com/chapel-lang/chapel/issues/11756
