### ISSUE TITLE
Should inferConstRefs or remoteValueForwarding run only under --fast?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11385]
Over in PR #11373, I adjusted the compiler to always run inferConstRefs, instead of only running it as part of remoteValueForwarding. That PR enabled inferConstRefs by default, even for non`--fast` compiles, because that was the situation for removeValueForwarding (always enabled if `on` statements are outlined).

That brought up two questions:
 * Should remoteValueForwarding only run under `--fast`?
 * Should inferConstRefs only run under `--fast`? (Or possibly if remoteValueForwarding will run or if `--fast` is specified?)

**Comment by vasslitvinov** [comment]
I like the idea of running remoteValueForwarding and inferConstRefs regardless of --fast. That way it is easier to detect their shortcomings, if any.

**Comment by bradcray** [comment]
My reaction was the same as Vass's.

**Comment by mppf** [comment]
OK, that's how it is now, so I'll close this issue. The only disadvantage is the compiler does more by default (and so might be slower).

**Comment by bradcray** [comment]
That doesn't seem inconsistent with current philosophy, which I'd say is "do things by default, use `--baseline` to turn them off", use `--fast` to opt into making code less safe in exchange for speed."
