### ISSUE TITLE
Should array slices within an on-clause generate a compile-time warning?

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#11391]
### Summary of Problem
The following program results in a helpful compiler-time warning, since a user might expect the `on` clause to use the locale of the tuple elements rather than the tuple itself:

```chpl
on (Locales[0],) {
  writeln(here.id); // prints 0
}
```

Array slices are also a local expression, but do not generate this warning:

```chpl
on A[2..3] {
  writeln(here.id); // prints 0
}
```

This could be confusing for users who expect a slice of a distributed array to have a `.locale` representing where that slice lives.

### Steps to Reproduce

**Source Code:**

```chapel
use BlockDist;

var space = {0..#8};
var dom = space dmapped Block(boundingBox=space);
var A: [dom] int;

writeln(A[5].locale.id);
writeln(A[2..3].locale.id);

on A[2..3] {
  // User might expect 1 (for numLocales = 4)
  writeln(here.id); // prints 0
}
```

### Configuration Information

- Output of `chpl --version`: `chpl version 1.19.0 pre-release (449409b083)`

**Comment by benharsh** [comment]
What would happen if the slice involved elements on multiple locales? A runtime error?

**Comment by ben-albrecht** [comment]
> What would happen if the slice involved elements on multiple locales? 

Exactly. To be clear, I'm not advocating for the array slice within an on clause to change behavior from what it does today, due to this ambiguity you pointed out.

I think the right answer is to emit a warning notifying the user that the slice is a local expression and will always return the `here` locale, like other local expressions do. This tripped up a user during a tutorial session, for example.

**Comment by ben-albrecht** [comment]
@mppf - this is the issue we chatted briefly about on Thursday.

**Comment by cassella** [comment]
Both expressions generate the same compile-time warning today:

```chapel
on (Locales[0],) {
  writeln(here.id); // prints 0
}

var A [ 1..10 ] int;
on A[2..3] {
  writeln(here.id); // prints 0
}
```

```
foo.chpl:1: warning: accessing the locale of a local expression
foo.chpl:6: warning: accessing the locale of a local expression
```

Though the only tests I see that have that warning in their `.good` files are in `test/multilocale/deitz/oneOrMoreLocales/` and none of them test tuples or array slices.

**Comment by mppf** [comment]
PR #21653 will add the array slice case as a test.
