### ISSUE TITLE
Add another dimension to build_configs.py for CHPL_LIB_PIC 

### ISSUE THREAD

**Issue by awallace-cray** [chapel-lang/chapel#11394]
CHPL_LIB_PIC was just added to Chapel's set of build env variables. 

Normally, build_configs.py should have a dimension for every possible Chapel build env variable. 

So we should add CHPL_LIB_PIC to build_configs, unless there is some reason not to.

**Comment by lydia-duncan** [comment]
I think we'll want to do so

**Comment by awallace-cray** [comment]
https://github.com/chapel-lang/chapel/pull/11560

**Comment by awallace-cray** [comment]
2018-11-05 10:38
https://github.com/chapel-lang/chapel/pull/11560 merged
