### ISSUE TITLE
Document QT_AFFINITY?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#11392]
I've had this variable set in my .bashrc whenever I build with `gasnet` but I don't see any documentation on when it should be used.  At least, searching the online docs didn't turn up anything (and it should since it impacts things).

Edit: removed CHPL_QTHREAD_ENABLE_OVERSUBSCRIPTION since Greg found it when I had missed it

**Comment by ronawho** [comment]
These have been replaced with `CHPL_RT_OVERSUBSCRIBED`, which is documented here:
 - https://chapel-lang.org/docs/master/usingchapel/executing.html#oversubscription
 - https://chapel-lang.org/docs/master/usingchapel/tasks.html#overloading-system-nodes

(Manually setting `QT_AFFINITY` and `CHPL_QTHREAD_ENABLE_OVERSUBSCRIPTION` has been replaced with `CHPL_RT_OVERSUBSCRIBED` in https://github.com/chapel-lang/chapel/pull/12600 / https://github.com/chapel-lang/chapel/pull/12813. `QT_AFFINITY` isn't really something we want to expose to users, and `CHPL_RT_OVERSUBSCRIBED` better conveys why we're using it when running multiple gasnet/chapel instances on a single node)
