### ISSUE TITLE
improve error message for queried domain used in cast

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11408]
``` chapel
  var array = ([1,2,3]: [?D] uint(8));
```

This program results in an internal error. If it continues to not be supported it should get a better error message.

**Comment by cassella** [comment]
This looks like a better error message:

```
foo.chpl:1: error: domain query expressions may currently only be used in formal argument types
```

The only test with that message in `.good` only tests it in a class field init expression --  `test/classes/generic/domainQueryField`.  (The `-feature` version of that test is a future suggesting that it not be an error case.)

**Comment by mppf** [comment]
PR #21653 will add this case as a test.
