### ISSUE TITLE
Add CHPL_LIB_PIC to ChapelEnv.chpl and Compiler flags

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#11400]
The other environment variables are in these places, so CHPL_LIB_PIC should be, too

**Comment by ben-albrecht** [comment]
Some tests to add to: 

- https://github.com/chapel-lang/chapel/tree/master/test/chplenv/printchplenv
- https://github.com/chapel-lang/chapel/tree/master/test/compflags/albrecht/chplenv
