### ISSUE TITLE
Internal error when sending generic type to type argument

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#11410]
### Summary of Problem
Sending a generic type as an actual to a function asking for a type argument results in an internal compiler error.  This should be a user error, since it is obviously due to the user writing it (though the internal error can also be triggered by compiler developer mistakes)

### Steps to Reproduce

**Source Code:**

```chapel
proc bar(type t) {
  writeln(t: string);
}

class Foo {
  var x;
}

bar(int);
bar(Foo);
```

**Compile command:**
`chpl foo.chpl`

**Associated Future Test(s):**
[`test/functions/lydia/genericActualTypeArg.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/functions/lydia/genericActualTypeArg.chpl) #11411 

### Configuration Information

- Output of `chpl --version`: chpl 1.19.0 pre-release

**Comment by ben-albrecht** [comment]
There are a couple of variations of this error that I encountered out in the wild. Posting them here instead of a new issue:

```chpl
class Generic {
  var x;
}

writeln(Generic:string);
```

```chpl
class Generic {
  type t;
}

writeln(Generic:string);
```

The error for both of them (when compiling with `--devel`) is:

```
internal error: the type of the actual argument 'Generic' is generic [resolution/callInfo.cpp:124]
```
