### ISSUE TITLE
Support setting array argument default value to empty array literal

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#11423]
I had a function with an array argument and wanted to give the argument a default value of empty array without creating an overload. I was surprised that the following program was not valid:

```chpl
proc f(x: [] string = []) {
  writeln(x.size);
}

f(['f']);
f();
```

Compiling this generates a syntax error:

```
$ chpl default-arg.chpl
default-arg.chpl:1: syntax error: near ']'
```

For reference, passing a non-literal empty array works today:

```chpl
var emptyArray: [1..0] string;

proc f(x: [] string = emptyArray) {
  writeln(x.size);
}

f(['f']); // 1
f();  // 0
```

However, this isn't really a satisfactory work-around, since the default `ref` intent for arrays could result in the `emptyArray` getting unintentionally modified.

Also, giving an array a non-empty array literal default value is allowed today:

```chpl
proc f(x: [] string = ['g']) {
  writeln(x.size);
}

f(['f']); // 1
f(); // 1
```

### Configuration Information

- Output of `chpl --version`: `1.19.0 pre-release (9099c557dd)`

**Comment by bradcray** [comment]
OK, now I've tested, and was misremembering:  I don't think we currently have either an empty-tuple nor empty-array syntax.

**Comment by ben-albrecht** [comment]
I just tested too - it appears I have misremembered as well, and thought we did. Do you know if there's an open (or closed) issue for empty array literals?

**Comment by bradcray** [comment]
I don't.

**Comment by ben-albrecht** [comment]
I'll create an issue for that language feature request instead.

**Comment by ben-albrecht** [comment]
Closing this issue for a more distilled language feature request in #11427
