### ISSUE TITLE
Default argument value for arrays asserts size for in intent

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#11424]
### Summary of Problem
The `in` intent introduces an implicit (and likely unintentional) assertion about the argument size for array arguments with default values, causing a halt when the array argument does not match the size of the default value.

### Steps to Reproduce

**Source Code:**

Here is an example for an empty array:

```chapel
var emptyArray: [1..0] string;

proc f(in x: [] string = emptyArray) {
  writeln(x.size);
}

f(['f']);
```

This program generates a runtime halt, because the argument shape does not match the default value shape.

This program works fine if the `in` intent is removed, the default value is removed, or if an empty array is passed to `f()`.

**Execution command:**

```
$ ./default-arg
default-arg.chpl:7: error: halt reached - assigning between arrays of different shapes in dimension 1: 0 vs. 1
```

### Configuration Information

- Output of `chpl --version`: `1.19.0 pre-release (9099c557dd)`

**Comment by cassella** [comment]
This program works today, producing output `1`.
