### ISSUE TITLE
Task-private arrays generate an internal error

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#11422]
### Summary of Problem

Task-private arrays generate an internal error.

### Steps to Reproduce

**Source Code:**

```chapel
forall i in 1..10 with (var A: [1..10] real) {
  writeln(A[i]);
}
```

**Compile command:**
```
$ chpl repro.chpl

internal error: CHE0627 chpl version 1.19.0 pre-release (9099c557dd)

$ chpl repro.chpl --devel

internal error: Primitive should no longer be in AST [checks.cpp:627]
```

### Configuration Information

- Output of `chpl --version`: `chpl version 1.19.0 pre-release (9099c557dd)`

**Comment by ben-albrecht** [comment]
FYI - @vasslitvinov

**Comment by bradcray** [comment]
I've promoted this to a user issue since we had a user mail about wanting to do this today.
