### ISSUE TITLE
rename string.isEmptyString()?

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#11437]
One of these doesn't look like the rest..

- `array.isEmpty()`
- `domain.isEmpty()`
- `range.isEmpty()`
- `string.isEmptyString()`

Should `string.isEmptyString()` be `string.isEmpty()` like the others? 

I am not aware of the motivation for the unique string method name here if such a motivation exists.

**Comment by ben-albrecht** [comment]
Motivated by making breaking changes sooner than later, similar to #5041 (`domain.member` -> `domain.contains`)

Other potential changes like this are mentioned #6698.

**Comment by mppf** [comment]
> Should string.isEmptyString() be string.isEmpty() like the others?

Makes sense to me.

**Comment by dlongnecke-cray** [comment]
This is great! `string.isEmptyString()` is incredibly tedious to write.
