### ISSUE TITLE
Longest Common Subsequence

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#11433]
Following my habit of using issues as feature requests.

I came across this commit for [longest common subsequence](https://github.com/chapel-lang/chapel/pull/3574/commits/7fab47386b6ddb6f66dcbbc8d781dfc9d15c9175) and I would love to see this pushed into the string library or other basic text processing library with some of the functionality from python's [difflib](https://docs.python.org/2/library/difflib.html) specifically `SequenceMatcher()`

**Comment by buddha314** [comment]
blessed? So mote it be...   Nice theming!

**Comment by daviditen** [comment]
I wrote something like this a long time ago.  [test/trivial/diten/lcs/lcs.chpl](https://github.com/chapel-lang/chapel/blob/master/test/trivial/diten/lcs/lcs.chpl).  It could probably use some cleaning up and modernization if we wanted to make it an official thing.

**Comment by ankugupt** [comment]
I tried writing code for common subsequence whose algorithm looks similar to @ben-albrecht . Kindly take a look at it .

`proc input_string(out str1: string, out str2: string)
{
  var  infile=open(filename, iomode.r).reader();

  infile.read(str1);
  infile.read(str2);
  infile.close();
}

proc lcs ( str1:string,str2:string,len1,len2)
{
    var L:[0..len1,0..len2] int;
    
    for i in 0..len1
    {
        for j in 0..len2
        {
            if i==0 or j==0 
            {
                L[i,j]=0;
            }
            elif str1[i-1]==str2[j-1]
            {
                L[i,j]=L[i-1,j-1]+1 ;
            }
            else
            {
            L[i][j] = max(L[i-1][j], L[i][j-1])  
            }
            
        }
    }
    var index : int = L[len1][len2];
    
    var lcs[index+1] : string;
    lcs[index] = '';
    
    var m:int = len1;
    var n:int = len2;
    
    while m > 0 and n > 0 
   { 
      
      if str1[m-1] == str2[n-1]) 
      { 
          lcs[index-1] = str1[i-1];  
          m-=1; n-=1; index-=1;     
      } 
  
      elif  (L[m-1][n] > L[m][n-1]) 
         m-=1;
      else
         n-=1; 
   } 
   
return lcs;

}

proc main()
{
    
    config var filename="commonsubs";
    
    var str1,str2 : string ;
    var len1,len2 : int ;
    
    input_string(str1,str2);
    
    len1= str1.size;
    len2= str2.size;
    
    writeln(lcs(str1,str2,len1,len2));
    
}`

**Comment by ben-albrecht** [comment]
Hi @ankugupt - thanks for your interest. I expect this issue to be closed by the addition of the [StringUtils](https://github.com/chapel-lang/mason-registry/pull/14) package to the mason registry.

If you think your implementation is an improvement over that one, I encourage you to contribute to the StringUtils package: https://github.com/AnubhavUjjawal/Chapel-StringUtils
