### ISSUE TITLE
better error message for variable decl with generic type and no initial value

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#11436]
Given the code:

```chpl
record R {...} // a generic record
var r: R;
```

the compiler reports:

```
error: Cannot default-initialize a variable with generic type
note: 'not-fully-instantiated' has generic type 'R'
```

I would like to see the variable name instead of "not-fully-instantiated" in the second line:

```
note: 'r' has generic type 'R'
```

Towards that end, I am not seeing the value of having the note differentiate between "not-fully-instantiated" and "abstract" in `functionResolution.cpp:9750` .

**Comment by vasslitvinov** [comment]
@lydia-duncan or @benharsh - what are your thoughts on the significance of "not-fully-instantiated" vs. "abstract" in this error message?

**Comment by lydia-duncan** [comment]
It looks like that was a poor translation of an earlier error message.  I don't understand the difference, either, and agree that using the instance's name instead would be better

**Comment by krishnadey30** [comment]
@lydia-duncan @vasslitvinov I tried to solve this but I am not able to get the variable name in this function.

![image](https://user-images.githubusercontent.com/22263782/54314467-bfe6db00-4601-11e9-81c0-a7abed42ff93.png)

Can you guide me a little. I tried to get the `baseExpr` from the CallExpr and then tried to convert the `baseExpr` to `SymExpr` but I failed to get the variable name.

**Comment by lydia-duncan** [comment]
What's the lview output of `call` in this scenario?  (gdb, break on the USR_FATAL_CONT line, `lview call`)

**Comment by krishnadey30** [comment]
I think I need to learn more about debugging and chapel compiler. I will learn and will try to solve this.
Thanks @lydia-duncan

**Comment by vasslitvinov** [comment]
primInitHaltForUnacceptableGeneric() is invoked from resolvePrimInit(). The latter has the formal argument `val`, which I suspect is the symbol being initialized. If we pass `val` to primInitHaltForUnacceptableGeneric() as an extra argument, we can use it in the error message.

**Comment by krishnadey30** [comment]
@vasslitvinov Thanks. It worked. I will create a PR for this.

**Comment by krishnadey30** [comment]
@lydia-duncan @vasslitvinov I have created a PR https://github.com/chapel-lang/chapel/pull/12594. Please have a look.
