### ISSUE TITLE
Missing libpython*.so for certain python builds

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#11450]
On Cori, I am unable to use Chapel libraries from python for certain python installations available on the system, e.g.

```python
"""test.py"""

import chpl_module
```

```bash
$ module load python/3.6-anaconda-5.2
$ python test.py
ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
```

```bash
$ module load python/3.6-anaconda-4.4
$ python test.py
 # works
```

```bash
$ module load cray-python/3.6.5.1
$ python test.py
 # works
```

### Configuration Information

- Output of `chpl --version`: `1.19.0 pre-release (9099c557dd)`

**Comment by ben-albrecht** [comment]
FYI @lydia-duncan

**Comment by ben-albrecht** [comment]
This could be a packaging issue. The package was delivered by just copying over the built `libfoo.so` and the python code. There might be a more robust mechanism for packaging the cython-built library.

**Comment by lydia-duncan** [comment]
I was able to reproduce this.  Looking for libpython.so.1.0 in the anaconda install gave me a directory that, once added to my LD_LIBRARY_PATH, allowed the error to go away.  It seems strange that Anaconda 4.4 would not need this when Anaconda 5.2 would (and Ben said that it didn't work for him, though I suspect he will try again when he gets the chance)

**Comment by ben-albrecht** [comment]
>  Ben said that it didn't work for him, though I suspect he will try again when he gets the chance

My previous attempts to set `LD_LIBRARY_PATH` to get it to work were from within a Jupyter notebook environment, so I must have not been setting it right there.

>  It seems strange that Anaconda 4.4 would not need this when Anaconda 5.2 would 

I suspect that the difference between these python modules is that some are built with `--enable-shared` and some are not. When `--enable-shared` is not enabled, the user must have the path to the `libpython.so` in their `LD_LIBRARY_PATH`.

I tested the above modules with the following program and the results confirm this suspicion so far:

```python
"""enableshared.py"""
import sysconfig
# Prints [1] if built with --enable-shared, [0] otherwise
print(sysconfig.get_config_vars('Py_ENABLE_SHARED'))
```

```bash
$ module load python/3.6-anaconda-5.2
$ python enableshared.py
[0]
```

```bash
$ module load python/3.6-anaconda-4.4
$ python enableshared.py
[1]
```

```bash
$ module load cray-python/3.6.5.1
$ python enableshared.py
[1]
```

**Comment by ben-albrecht** [comment]
It looks like anaconda now distributes python built without `--enable-shared` intentionally for performance reasons [[1]](https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/z7RboI3Pir8), so this problem would occur for any new versions of anaconda. 

They claim that this recommendation came from upstream, but I can't find a source on that. However, I see that python 3.8-dev comes built without `--enable-shared`.

**Comment by lydia-duncan** [comment]
Something about the version of python built was causing the inclusion of libpython3.6m.so.1.0 in the .so generated by Cython.  However, a fresh, unmodified Python install did not cause libpython to be included.  We consider this issue to be an installation error and so are going to close it.  If in the future someone else encounters it, they should feel free to let us know
