### ISSUE TITLE
Improve error message for `with` clauses

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#11462]
### Summary of Problem
`with` clauses could benefit from better error messages in general, but here are a couple of cases I think would be particularly helpful to users:

### for loops

User is debugging a `coforall` or `forall` by switching a `for` loop, but forgets to drop the `with` clause:

```chapel
var A: [1..10] int;

for i in 1..10 with (ref A) { }
```

current error:

```
3: syntax error: near 'with'
```

suggested error:

```
error: 'with' clauses are only valid in forall and coforall loops
```

### parentheses

User forgets that a `with` clause requires parentheses:

```chapel
var A: [1..10] int;

forall i in 1..10 with ref A { }
```

current error:

```
3: syntax error: near 'ref'
```

suggested error:

```
error: missing parentheses after 'with' clause
```

**Comment by cassella** [comment]
For the first case, I'd argue for allowing it to compile, though emitting a warning that the `with` clause is being ignored. (Maybe only when the with clause includes only `ref` items.) In working on AoC problems, I frequently hit this changing a `forall` statement with a `with` clause into a `for`.  But removing the with clause means that when I want to change it back to a `forall` I have to rewrite the clause.  Allowing the `for` statement to have an ignored `with` clause would make it easier to change back and forth.

Though `with` items that have `in`, `var`, or `reduce` intents, ignoring the `with` clause would be wrong.  Could for statements accept and apply these task intents?

**Comment by bradcray** [comment]
@cassella : I believe that current thinking agrees with you that for-loops should accept with clauses (and implement them properly) for convenience.  We're currently working on getting with-clauses working properly with foreach loops, so maybe for loops can come thereafter.

**Comment by jabraham17** [comment]
Closing, this was implemented in https://github.com/chapel-lang/chapel/pull/24234

**Comment by cassella** [comment]
The second case (missing parentheses) still reports the original syntax error.

**Comment by bradcray** [comment]
@cassella: I think you're proposing that this should be re-opened, or that that case should be split off into its own issue?  @jabraham17 : What do you think?

(Also, I didn't see this issue earlier and recently enough to make this comment, but: we've been feeling pretty strongly that it's probably appropriate for `for` loops to support `with` clauses as well (https://github.com/chapel-lang/chapel/issues/17857), to simplify rewriting parallel loops into serial loops, simply by changing the keyword; so the error message for the first-case, may be short-lived when we get to that).

**Comment by jabraham17** [comment]
Well that's unfortunate, I missed that when closing this issue. Instead of reopening this, I've just opened https://github.com/chapel-lang/chapel/pull/25611 to add better errors altogether for `with` clauses
