### ISSUE TITLE
units (e.g. meters) and dimensional analysis

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11486]
Recent work on the string library has us adding different types for different forms of string offsets (byte offset vs. codepoint offset). This made me wonder, could we have a generalized system for units like meters? Certainly units are very important in physical calculations. How useful would that be? And, are the requirements for physical units very different from the string case?

I don't know the answers to these questions but I suspect handling physical units would be pretty different from the string case. Physical units have many more units and consider products of unit types (e.g. ft-lbs or meters/second). The string conversion between byte offset and codepoint offset depends on the string, which is also not a property of the physical units.

For physical units, it seems like a reasonable end goal would be to have compile-time type checking of the units (e.g. can't add feet and seconds) that was robust enough to be not-too-annoying for physical simulations. My quick look at prior art seems to suggest that compile-time analysis can provide better error messages than libraries adding the functionality.

Here are links about prior art for units in programming languages:
 * https://stackoverflow.com/questions/107243/are-units-of-measurement-unique-to-f
 * Boost Units
 * F# https://fsharpforfunandprofit.com/posts/units-of-measure/
 * Ada Units of Measurement package http://www.dmitry-kazakov.de/ada/units.htm
 * Osprey: A Practical Type System for Validating Dimensional Unit Correctness of C Programs http://web.cs.ucdavis.edu/~su/unitfull.pdf
 * Units-of-Measure Correctness in Fortran 
Programs https://www.cl.cam.ac.uk/~acr31/pubs/contrastin-units.pdf
 * Experience Report: Type-checking Polymorphic
Units for Astrophysics Research in Haskell https://cs.brynmawr.edu/~rae/papers/2014/units/units.pdf
 * Object-Oriented Units of Measurement https://www.cs.tufts.edu/~nr/cs257/archive/neal-glew/mcrt/Fortress/p109-allen.pdf

**Comment by mppf** [comment]
@npadmana - I was just wondering if you have a quick reaction to the question of how valuable compile-time unit checking/dimensional analysis would be in Chapel. Thanks!

**Comment by bradcray** [comment]
With the disclaimer that I haven't read through the bibliography you provide above:  When I've discussed units with users, the traditional reaction has been that at first they seem nice when you're looking at simple examples, but then it all tends to fall apart once you actually start doing "real" math with them (integrals, differentiation, etc.).

**Comment by npadmana** [comment]
I've not had a chance to look through the bibliography either, but I have used Mathematica's implementation of units at various points. Some thoughts (in no particular order, and these are really just my impressions and no more):

--  I rarely use units inside of a calculation; I normally just use these at the start and end of a calculation to get results into the most useful form. So, even in Mathematica, I'm not using these as a check, but rather just for unit conversions. Indeed, in many cases, I try to write the problem in dimensionless form and just put the units in at the start and end. 

-- Units tend to be very domain- and problem-specific. So you either need to build a large curated list of unit systems/physical constants (which is what Mathematica does), or you are relying on the user to put this together in which case I think its simpler to just do it by hand. 

-- As an example of how units get complicated, a common thing to do in physics problems is to work in units where the speed of light is 1 (dimensionless). So either Chapel would need to be able to handle non-trivial unit systems like this, or you are going to insist that the users complicate code by dragging along units, or people will just not use units. 

I largely agree with Brad that this always seems like a nice idea, but I've only seen this used for toy examples. Tracing units through complicated calculations isn't easy. While I often use units to check results at the end, I almost never use them in the actual steps of a calculation (unless I find something doesn't work).

**Comment by mppf** [comment]
I'm going to close this issue, since it wouldn't make sense to schedule work on it in the near term, but if/when somebody wants to or is able to work on units in Chapel it will still exist and hopefully be useful.
