### ISSUE TITLE
Arrays should initialize, not assign

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#11498]
As I understand it, currently when we declare new arrays with initializer expressions, we default initialize them and then assign to them.  As initializers become more and more mature, it seems as though we ought to be able to move to a world in which arrays are initialized directly rather than relying on initialization plus assignment, for efficiency and consistency with other types.

This can be seen using a test like the following

```chapel
var A: [1..3] real = [1.2, 3.4, 5.6];
```

and putting a writeln() statement into the built-in array assignment operator, which triggers.

**Comment by bradcray** [comment]
Oops, I think this is a duplicate of issue #10374.  Closing.

**Comment by mppf** [comment]
I'd actually make this issue track a more general problem with typed array initialization:
``` chapel
var A:[1..10] int;
var B:[A.domain] int = A; // uses a default-init + assignment pattern
```

Issue #10374 is specifically about initializing the array *elements* rather than assigning them. I think this could be clearer in the title. Obviously these are connected problems.

**Comment by bradcray** [comment]
Oh, interesting.  You're right that I didn't understand that #10374 was about initializing each array element rather than initializing the array as a whole.  I also apparently am unable to close an issue when I say I'm going to (this is the nth time this has happened recently.  I'll leave this one open as a result (though I think you're right that they're linked (if we're not calling the array's initializer, we're never going to call the element's initializer).
