### ISSUE TITLE
quickReference.pdf minor bitrot

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#11528]
doc/rst/language/quickReference.pdf has a few out of date bits.  I created a branch to fix them.  But I don't know how to edit the file, so you get an issue instead of a PR.

First section:

Quick Start: one-line "hello, world"

```
$ chpl hello.chpl
./a.out
hello, world
```

Should now be `./hello` instead of `./a..out`

Middle section:

```chapel
Classes
class Circle {
  var p: Point;
  var r: real;
}
var c = new Circle(r=2.0);
```

Maybe `var c = new unmanaged Circle(r=2.0);`, since ti's deleted later?
Or leave it as `new (borrowed) Circle` and drop the `delete c` line?

Penultimate section:

```chapel
var c: Circle
on Locales[i] {
   writeln(here);
   c = new Circle();
}
writeln(c.locale);
on c do { ... }
```

`c = new owned Circle()`?

Ultimate section

```
www: http://chapel.cray.com
```

`chapel-lang.org`?

**Comment by mppf** [comment]
c = new owned Circle() doesn't work because of issue #10566.

**Comment by mppf** [comment]
https://github.com/mppf/chapel/tree/update-quickreference does the updates in a way I think is reasonable (but doesn't regenerate the PDF yet). I think we should fix  #10566 before merging it though.

**Comment by cassella** [comment]
That's done now, right?

**Comment by mppf** [comment]
yes, thanks for the reminder, I created PR #12456 to help this get into the upcoming release
