### ISSUE TITLE
Fix environment variable passing for Perl-implemented launchers

### ISSUE THREAD

**Issue by dmk42** [chapel-lang/chapel#11536]
#11355 was a user issue with the slurm-gasnetrun_ibv launcher, fixed by #11532 .  In fixing the user issue, it was noticed that other launchers have similar problems.

Examine all the gasnetrun_ibv, gasnetrun_mpi, and gasnetrun_ofi launchers and apply the following fixes as necessary.

1.  Some launchers do not pass the full environment to the compute nodes.
2.  These launchers are written in Perl, with a preamble that mangles the character-set-locale (via LC_ALL et al.).  When these environment variables are passed to the compute nodes, the mangled version is passed.  The workaround from #11532 should be applied.

**Comment by ronawho** [comment]
Just curious, is something we should ping the GASNet folks about? i.e. do we think this is a "bug" on their end, or just an oddity in testing for us (or something else)

**Comment by dmk42** [comment]
No, this is not GASNet's fault.  They are working around a design bug in Perl.  Perl assumes all strings contain nothing but characters in the character set described by the current locale (in the POSIX sense of the word locale).  Consequently, strings of binary bytes are mangled by Perl.  GASNet sets the locale to ASCII to keep the binary communications between login and compute nodes from being mangled by Perl.

If GASNet could do anything to fix this, it would be to rewrite these launchers in something other than Perl.
