### ISSUE TITLE
Portable way to launch a process per node for GASNet launchers

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#11533]
For gasnet launchers like gasnetrun_ibv, gasnetrun_mpi, gasnetrun_ofi, etc we currently just specify how many processes to launch with `-n <numLocales>`. By default gasnet will use mpirun to launch and how these processes get mapped to target locales is up to the mpirun implementation. MPICH seems to default to scattering processes so we end up with a process per node, but Open MPI seems to pack processes so we end up oversubscribing a single node, which is really bad for us.

On a system with Open MPI here's what we see: 

```sh 
$GASNET_BIN/gasnetrun_ibv -n 2 ./hello6-taskpar-dist_real -nl2
```
>Hello, world! (from locale 0 of 2 named chapcs11)
>Hello, world! (from locale 1 of 2 named chapcs11)

Adding `-N 2` to specify the number of nodes to run on seems to fix this:

```sh
$GASNET_BIN/gasnetrun_ibv -n 2 -N 2 ./hello6-taskpar-dist_real -nl2
```
>Hello, world! (from locale 0 of 2 named chapcs11)
>Hello, world! (from locale 1 of 2 named chapcs10)

However,  I'm not sure how portable of a solution this is because this option is listed as "not always supported", and I'm not sure what happens in cases where it's not supported.

**Comment by ronawho** [comment]
Note that this is the root problem for https://github.com/chapel-lang/chapel/issues/11030

**Comment by ronawho** [comment]
@PHHargrove and/or @bonachea I'm hoping you comment on this. Thanks!

**Comment by PHHargrove** [comment]
If I understand correctly, the concern is over GASNet's "not always supported" disclaimer for the `-N` option.  The truth is that we have correct support for that option on the vast majority of `mpirun` implementations (including use of `aprun` and `srun`).  However, we cannot always know in advance what changes the MPICH or Open MPI folks will make when we aren't looking.

In response to "I'm not sure what happens in cases where it's not supported":
When an mpirun not recognized/supported, the user will get a message.
```
WARNING: Don't know how to control process->node layout with your mpirun
WARNING: PROCESS LAYOUT MIGHT NOT MATCH YOUR REQUEST
```

The other good news is that the support for this is in perl, not C.
So adding support for an unrecognized mpirun could potentially be done "in the field" w/o the need to rebuild or reinstall GASNet.

If one does encounter a system where `-N` is not working, we would try to add the necessary recognition and support.  However, we'd also suggest that ssh-based spawning (which always supports `-N`) is a decent alternative when the system is configured to allow ssh among the allocated nodes.

**Comment by ronawho** [comment]
Thanks Paul

I can confirm `-N`  works for Open MPI 1.10.6, MPICH 3.3, and Intel MPI 2018.

Unfortunately it does not seem to work with Open MPI 3.X. On a Cray CS400, it works for openmpi/gcc/1.10.7, but not openmpi/gcc/3.0.0 or openmpi/gcc/3.1.0 (where not working means we get that warning and we're getting packed processes)

**Comment by PHHargrove** [comment]
> Unfortunately it does not seem to work with Open MPI 3.X.

@ronawho if you can, please enter a GASNet bug report at https://upc-bugs.lbl.gov/bugzilla and attach the `mpirun -h` output for the Open MPI installations which are misbehaving.  We use that output as a fingerprint to identify the implementation.

We have Open MPI installed on some of our test systems, but I am not sure if we are using it for spawning or not.

**Comment by PHHargrove** [comment]
@ronawho Nevermind entering the bug report.

I already see the problem, which is that the help output has been changed dramatically in Open MPI 3.  So, I'll enter the bug report myself.

When I have a few minutes (not now, unfortunately) I think I can generate a 1- or 2-line patch to fix this.

**Comment by ronawho** [comment]
Whoops, too late -- https://upc-bugs.lbl.gov/bugzilla/show_bug.cgi?id=3803

**Comment by PHHargrove** [comment]
No problem.  :grin:

**Comment by ronawho** [comment]
Open MPI 3 support has been fixed upstream (https://bitbucket.org/berkeleylab/gasnet/pull-requests/240/bug3803/diff, https://upc-bugs.lbl.gov/bugzilla/show_bug.cgi?id=3803) and we have high confidence for most MPI implementations, so I think this can be closed. 

Like Paul mentioned if `-N` isn't support, the user will just get a warning, which should serve as a good indication to ping us or the GASNet team.
