### ISSUE TITLE
Outdated documentation for BigInteger

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#11571]
Changes from #11381 make [these lines](https://github.com/ben-albrecht/chapel/blob/f8eea58d7931e34f68f78439fbda2de64cec4e0c/modules/standard/BigInteger.chpl#L67-L76) no longer correct. Those lines won't compile anymore.

xref  to #11500.

**Comment by bradcray** [comment]
Thanks @BryantLam.  @daviditen : Can you wrangle this one when you get the chance?

(This brings the "testable documentation" request in issue #11090 to mind...)
