### ISSUE TITLE
Design for utility methods for creating distributed domains/arrays in one call

### ISSUE THREAD

**Issue by daviditen** [chapel-lang/chapel#11578]
Issue #10718 asks for utility functions for creating distributed domains in a single call.  There, the following functions were suggested:

```chpl
proc createCyclic(dom : domain) {
   return dom dmapped Cyclic(startIdx=dom.low);
}
proc createCyclic(rng : range) {
   return createCyclic({rng});
}
proc createCyclic(sz : integral, startIdx = 1) {
   return createCyclic(startIdx..#sz);
}
proc createBlock(dom : domain) {
   return dom dmapped Block(dom);
}
proc createBlock(rng : range) {
   return createBlock({rng});
}
proc createBlock(sz : integral, startIdx = 1) {
   return createBlock(startIdx..#sz);
}
```

@bradcray stated that:
* He's not crazy about the versions that take a start index and size, and doesn't feel that (0..n-1) is worse than (n, 0).
* Wants utility routines for creating both domains and arrays, so `createBlockDom()`, `createBlockArr()`.
* Wants variable number of ranges to make multidimensional versions instead of requiring it to be a domain literal: `(1..n, 1..n)` vs. `({1..n, 1..n})`.
* Suggested `newBlock...` instead of `createBlock...`.

So following @bradcray's recommendations, I propose adding to their respective modules:

```chpl
proc newBlockArr(dom: domain) { }
proc newBlockDom(dom: domain) { }
proc newBlockArr(rng: range...) { }
proc newBlockDom(rng: range...) { }

proc newCyclicArr(dom: domain) { }
proc newCyclicDom(dom: domain) { }
proc newCyclicArr(rng: range...) { }
proc newCyclicDom(rng: range...) { }
```

Other distributions can have similar utility functions added at a future date, but we should start here since they're the most widely used.  Other distributions will likely require additional arguments as well, e.g. `blocksize` will be required for `BlockCyclic`.

**Comment by ben-albrecht** [comment]
I think this will be a lot easier to read/write for distribution creation. 

Since we're adding these to each module, could one consider this an extension of the DSI, i.e. domain map authors should provide one of these for their users and users should expect this functionality to be available for an arbitrary domain map?

Unfortunately, this introduces an *N ways to do 1 thing* problem. Is one style preferred over the other when possible? Which style would we want new users to start with? Tutorial slides, example codes, primers, etc. should probably follow this guideline.

**Comment by daviditen** [comment]
I typically think of the DSI as things that act on the implementation classes directly, vs. these working more with the wrapper records.  I don't think these are strictly required as things in the DSI are.

We already have multiple ways to declare a distributed array or domain, so I don't think this introduces an _N ways to do one thing_ problem, just makes it into _N+1 ways_.  I'd think most new users would want to start with the most simple way (D4 below), but some may want to fully specify everything even as they're learning the basics.  They might pick D1 or D2.  That's fine with me.

```
use BlockDist;

const Space = {1..100};
const D1: domain(1) dmapped Block(boundingBox=Space) = Space;
const D2 = Space dmapped new dmap(new Block(boundingBox=Space));
const D3 = Space dmapped Block(boundingBox=Space);
const D4 = newBlockDom(Space);
```
