### ISSUE TITLE
change "get/put" to "read/write" in runtime network atomics interface

### ISSUE THREAD

**Issue by gbtitus** [chapel-lang/chapel#11653]
The runtime interface for comm layer network atomics uses the terms `get` and `put` for the operations that are known elsewhere in atomics terminology as `read` and `write`.  `get` and `put` are uGNI/Gemini/Aries terms.  We should change our interfaces to use `read` and `write` instead.

**Comment by ronawho** [comment]
Note that the runtime interface (and C11/C++11) refer to these operations as load/store. In Chapel we call it read/write, but I think we should keep our runtime API the same for processor/network atomics. i.e. I think we should change get/put to load/store. https://github.com/chapel-lang/chapel/commit/a6864bde45fe788cab3c82cbb42b298be884c907 mentions the original motivation for the naming: 

"""
  After discussions with Brad and Michael, renamed load/store to
  read/write to be more consistent with sync and single variables
  conventions.
"""

**Comment by ronawho** [comment]
I'm also ok with changing to read/write if we also change the processor atomic API to read/write.
