### ISSUE TITLE
spike: Investigate testing failures with RV vectorization

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11679]
Address tests that fail when RV integration is enabled and testing is run with `--fast --llvm` (and the prediff described in issue #11678).

Wrong output, problem with 2nd induction variable
[Error matching program output for distributions/robust/arithmetic/basics/test_zipper_range]

Compile failure `isHandleInSync() && "invalid iterator access!"`
~~[Error matching compiler output for npb/cg/bradc/cg-dense]~~

seem to be working after intUintSlice fix:
~~[Error matching program output for domains/bradc/intUintSlice]~~
~~[Error matching program output for studies/hpcc/RA/bradc/ra-bradc-domainPromote]~~
~~[Error matching program output for studies/hpcc/RA/bradc/ra-bradc]~~

seems to be working after nsw and reduction intrinsic fix:
~~[Error matching compiler output for studies/programs/norm]~~
~~[Error matching compiler output for users/aroonsharma/LinearAlgebra/2mm]~~
~~[Error matching compiler output for users/npadmana/twopt/do_smu_aos]~~
~~[Error matching compiler output for studies/shootout/spectral-norm/lydia/spectral-norm-double-time]~~
~~[Error matching compiler output for reductions/waynew/reductions]~~

Bug in test:
~~[Error matching program output for npb/is/diten/is]
[Error matching program output for npb/is/diten/is_no_buckets]
[Error matching program output for studies/hpcc/RA/marybeth/ra2]
[Error matching program output for studies/hpcc/RA/marybeth/ra2-param-test]
[Error matching program output for studies/hpcc/RA/marybeth/ra3]~~

**Comment by mppf** [comment]
This is a reproducer related to the intUintSlice failure:
``` chapel
var U = {1:uint..10:uint};

var A: [1..10] real;

proc kernel() {
//  for i in vectorizeOnly(U) do  // this works
//  for i in vectorizeOnly(1:uint..10:uint) do  // this works
  forall i in U do              // fail
    A[i:int] += 1;
}

kernel();
writeln("A is: ", A);
```

**Comment by simoll** [comment]
> This is a reproducer related to the intUintSlice failure:
> 

Ok. This one is fixed by https://github.com/cdl-saarland/rv/commit/409a7f49edb8f67fbe2b128f74b5cfd5a73b8351

**Comment by mppf** [comment]
@simoll - thanks! I'll try that and investigate the other issues shortly.

**Comment by simoll** [comment]
How about we bypass that issue by using different metadata for RV (e.g. `rv.vectorize.enable`, instead of `llvm.vectorize.enable`)?
That way you can leave LLVM's LV in the pipeline and have RV on annotated loops without spurious warnings/remarks.

**Comment by mppf** [comment]
@simoll - here is another small reproducer:
``` chapel

const D = {1..4};
var A:[D] real;
A = 2.0;
var sum1 = normX(A);
writeln(sum1);
var sum2 = normY(A);
writeln(sum2);

proc normX(A) {
  var sum: real;
  forall x in A with (+ reduce sum) {
    sum += x;
  }
  return sum;
}

proc normY(A) {
  return + reduce A;
}
```

Compilation fails with an assertion in RV:
```
chpl: /home/mppf/w/llvm2/third-party/llvm/llvm/include/llvm/ADT/ArrayRef.h:241: const T& llvm::ArrayRef<T>::operator[](size_t) const [with T = llvm::Type*; size_t = long unsigned int]: Assertion `Index < Length && "Invalid index!"' failed.
```

This happens on this line: https://github.com/cdl-saarland/rv/blob/master/src/transform/redTools.cpp#L102 . Here elemTy is double and vecTy is `<4 x double>` and redKind is `rv::RedKind::Add`. The failure seems to have to do with the intrinsic wanting to access argument 2 but the Tys array only having elements 0 and 1.

**Comment by mppf** [comment]
@simoll - note that Intrinsic::experimental_vector_reduce_fadd seems to have 3 arguments: https://github.com/llvm-mirror/llvm/blob/master/lib/IR/IRBuilder.cpp#L322-L330

**Comment by mppf** [comment]
Here is a small reproducer for the miscompilation for test_zipper_range:
``` chapel
var A1D:[1..100] real;
  
proc kernel(A) {
  forall (a,i) in zip(A1D, 1.. by 2) do
    a += 2.0*i;
}

kernel(A1D);
writeln(A1D);
```

**Comment by simoll** [comment]
fadd/fmul reductions are fixed by https://github.com/cdl-saarland/rv/commit/36f94db8fd6825959e47c2d5a591f5ac54528b41
> This happens on this line: https://github.com/cdl-saarland/rv/blob/master/src/transform/redTools.cpp#L102 . Here elemTy is double and vecTy is `<4 x double>` and redKind is `rv::RedKind::Add`. The failure seems to have to do with the intrinsic wanting to access argument 2 but the Tys array only having elements 0 and 1.

**Comment by simoll** [comment]
https://github.com/cdl-saarland/rv/commit/7471660b1085c62fd951eef30be96afa31211ff9 makes sure RV leaves the loop scalar in that case (ICMP_EQ on loop exit condition but no nsw/nuw hints on iteration variable).

> chpl: /home/mppf/w/llvm2/third-party/llvm/llvm/tools/rv/src/transform/remTransform.cpp:217: llvm::Value& rv::BranchCondition::synthesize(int, std::__cxx11::string, llvm::IRBuilder<>&, std::set<llvm::Value*>*, std::function<rv::IterValue(llvm::Instruction&)>): Assertion `nuwFlag && "can not extrapolate wrapping exit conditions"' failed.

**Comment by mppf** [comment]
npb/is/diten/is: I'm pretty sure the problem is in the test itself. in fullVerify
``` chapel

  serial {
    // This has a problem with RV
    [i in D] {
      atomic {
        keyBuff1(buffer(i)) -= 1;
        keyArray(keyBuff1(buffer(i))) = buffer(i);
      }
    }
```

will work if it is:
``` chapel
for i in D {
      keyBuff1(buffer(i)) -= 1;
      keyArray(keyBuff1(buffer(i))) = buffer(i);
    }
```

**Comment by mppf** [comment]
test/studies/hpcc/RA/marybeth/ra2.chpl : similar to the is.chpl case:

``` chapel
    serial {
      [j in RandStepsDomain with (ref temp)] // no race - in 'serial'
        if (( ran >> j) & 1) then temp ^= RandomSteps(j);
    }
```

will work if it is:
``` chapel
    for j in RandStepsDomain {
      if (( ran >> j) & 1) then temp ^= RandomSteps(j);
    }
```

**Comment by mppf** [comment]
For Compile failure isHandleInSync() && "invalid iterator access!"
[Error matching compiler output for npb/cg/bradc/cg-dense]

to reproduce:
```
cd test/npb/cg/bradc
chpl -o cg-dense --cc-warnings --llvm --fast --no-warnings cg-makea.chpl cg-dense.chpl --no-devel
```

For this test, it appears to be the case that in this code:
https://github.com/cdl-saarland/rv/blob/5d26b942905c96be977c0f78a1060370985e0b25/src/analysis/AllocaSSA.cpp#L68-L72

&summary == &predSummary. This might plausibly occur if a block is a predecessor of itself. The result is that the loop iterates over a liveAllocas array while appending to it.

Presumably it'd be possible to simply copy the liveAllocas array before iterating over it. Indeed, the following patch resolves the issue for me:
```
diff --git a/src/analysis/AllocaSSA.cpp b/src/analysis/AllocaSSA.cpp
index 3416756..85e71aa 100644
--- a/src/analysis/AllocaSSA.cpp
+++ b/src/analysis/AllocaSSA.cpp
@@ -67,7 +67,8 @@ AllocaSSA::computeLiveness() {
 
       // transfer liveness to predecessors
       auto & predSummary = requestBlockSummary(*pred);
-      for (auto * liveAlloc : summary.liveAllocas) {
+      auto tmpArray = summary.liveAllocas;
+      for (auto * liveAlloc : tmpArray) {
         predChanged |= predSummary.liveAllocas.insert(liveAlloc).second;
       }
 
```

However there might be a more fundamental error. @simoll - could you have a look? Thanks.

**Comment by simoll** [comment]
Fixed by https://github.com/cdl-saarland/rv/commit/16fa594d8fe0fcf49a0b997853c162f208f6647d

> For Compile failure isHandleInSync() && "invalid iterator access!"
> [Error matching compiler output for npb/cg/bradc/cg-dense]

**Comment by mppf** [comment]
I'm closing this issue (since it was about investigating the failures, which I've done). Issue #11833 describes the remaining failure.
