### ISSUE TITLE
Error messages should print types of literals when they differ from the defaults

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#11706]
### Summary of Problem

Issue #9923 (resolved by PR #9953) was about error messages being confusing when a literal value is printed out whose type differs from the default.  For example, if a `param uint` has the value "1" and is merely printed as `1` it's indistinguishable from an `int` (which is what `1` would default to).  It seems that other instances of this behavior still exist, either because they weren't within the scope of #9953 or slipped through the cracks.  It seems as though if we were to unify how/where literals were printed out, we could potentially close all such remaining cases.

### Steps to Reproduce

**Associated Future Test(s):**
[`test/functions/resolution/paramUintNoTypeInError.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/functions/resolution/paramUintNoTypeInError.chpl
          ) #11687

### Configuration Information

- Output of `chpl --version`: `1.19.0 pre-release (b8f451f)`

**Comment by cassella** [comment]
@bradcray This one was also defuturized by #20528.

**Comment by bradcray** [comment]
Sweet!
