### ISSUE TITLE
Should param uint actuals dispatch to int formals?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#11705]
We typically permit param values to be passed to other argument types if the value is within the range of the formal.  For example, a param int with value "42" can be passed to a formal of type `int(32)` because the integer value "42" is within the legal range of the `int(32)` type.  However, it seems that we do not permit param uints to be passed to formals of type int in the same way, which seems inconsistent.  This issue asks whether we could/should do so, or whether it would cause ambiguities that would cause more problems than they're worth.

**Associated Future Test(s):**
[`test/functions/resolution/paramUintDispatchesToInt.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/functions/resolution/paramUintDispatchesToInt.chpl
          ) #11687

### Configuration Information

- Output of `chpl --version`: `1.19.0 pre-release (b8f451f)`

**Comment by cassella** [comment]
@bradcray  The linked future was defuturized by #20528.  Ready to close?

**Comment by bradcray** [comment]
Yep, thanks Paul!  (you're making me think of the days when we imagined that a script would be helping us catch cases like this...    somehow that never came to pass...)
