### ISSUE TITLE
What should isClass*() do with managed classes?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#11735]
This issue asks a design question and logs what I consider to be a bug w.r.t. how `isClass*()` routines behave for managed class types:

* The design question is whether `isClass*()` should return `true` or `false` for `owned` and `shared` objects.
  * the argument in favor of `true` would be that we tend to describe these to users as "managed classes" and have them behave in a class-like manner, so intuitively they seem like classes.
  * the argument in favor of `false` might be that the implementation uses a record to wrap the classes, so the objects are not technically classes from the compiler's perspective.

* the bug part is that currently `isClass*()` queries return `false` for the types themselves, but `true` for objects of those types.  Whatever we decide with the design question, it seems these calls should give identical results.  The future below captures this behavior.

**Associated Future Test(s):**
[`test/classes/delete-free/isClassTest.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/classes/delete-free/isClassTest.chpl
          ) #11734

### Configuration Information

- Output of `chpl --version`: `1.19.0 pre-release (45c48d6)`

**Comment by bradcray** [comment]
Though I tried to write the text above neutrally, it's probably obvious that I think "true" is the right answer for these queries, primarily for the reasons given above.

It also would seem strangely inconsistent to me to have `isOwnedClass()` return `true` for an `owned C` (as it currently does), but for `isClass()` to return `false`.

**Comment by mppf** [comment]
I'm pretty sure we want isClass to return true for owned/shared. There might have been discussion about this before somewhere (I didn't go looking) but I view the issue with types not behaving that way as a bug. I wouldn't have even considered this an open design issue.

So, as far as I know there is only agreement that isClass(owned MyClass) should return true. @vasslitvinov - are you on the same page with this, or do you have a different view? Thanks.

**Comment by vasslitvinov** [comment]
I agree isClass to return true for owned/shared. The user view of owned/shared/borrowed/unmanaged prefix is a decoration, without affecting class-ness of the type/value.
