### ISSUE TITLE
Rename CHPL_TARGET_ARCH->CHPL_TARGET_CPU and CHPL_TARGET_MACHINE->CHPL_TARGET_ARCH 

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11740]
PR #11638 adds CHPL_TARGET_MACHINE to fit in with CHPL_TARGET_ARCH. But, CHPL_TARGET_MACHINE + CHPL_TARGET_ARCH isn't a great choice of names for these variables. In particular, one might think a "machine" is more specific than an "architecture". Additionally, while "machine" has precedent in `uname -m', one might think it's supposed to be hostname...

In case you've forgotten what these variables mean:
 * CHPL_TARGET_ARCH currently is the "architecture" for specialization. It's named this way because for GCC on x86_64, we add a `-march=` flag to specialize the binary. Example settings are sandybridge, thunder-x2, m68030.
 * CHPL_TARGET_MACHINE is the "machine" which is the general architecture. It's named this way because it's the same usually as `uname -m` and the uname command calls it "machine". For example, x86_64, aarch64, m68k.

The proposed follow-on change is
 * rename CHPL_TARGET_ARCH to CHPL_TARGET_CPU
 * rename CHPL_TARGET_MACHINE CHPL_TARGET_ARCH

Why do this?
 * The subset relationship is clearer: a given CPU has a particular architecture
 * GCC on some platforms uses -mcpu for this purpose, so there is still pretty good precedent
 * Other open source projects in common usage call x86_64 an "architecture":
   * https://www.ubuntu.com/download/server
     "Alternative architectures" includes ARM, POWER, IBM Z
    * https://getfedora.org/en/server/download/
      "Select the format and architecture" and then lists x86_64, aarch64

How to manage user impact?

One might be reasonably concerned that people who have set CHPL_TARGET_ARCH in a script, or who are used to setting it, will be annoyed with this change. I have a simple strategy to suggest for the transition that I think alleviates these problems:

 * if both CHPL_TARGET_ARCH and CHPL_TARGET_CPU are set, we follow what the user said. But this presumably won't happen for somebody who needs to update their script or their brain,
 since CHPL_TARGET_CPU didn't exist.

 * if CHPL_TARGET_CPU is set and CHPL_TARGET_ARCH is not, we infer CHPL_TARGET_ARCH. Again, this one isn't relevant to helping people migrate. But, it's important to understand. For example CHPL_TARGET_CPU=sandybridge will cause us to infer CHPL_TARGET_ARCH=x86_64.
  
 * if CHPL_TARGET_ARCH is set and CHPL_TARGET_CPU is not, and CHPL_TARGET_ARCH is a valid value for CHPL_TARGET_CPU, e.g. sandybridge, we:
    * infer CHPL_TARGET_CPU as the value user provided for CHPL_TARGET_ARCH (CHPL_TARGET_CPU=sandybridge in the running example)
    * set CHPL_TARGET_ARCH to the default based on that CHPL_TARGET_CPU per the normal rule above  (so set CHPL_TARGET_ARCH=x86_64 for the running example)
    * print a warning to suggest they update

**Comment by mppf** [comment]
Some people have already expressed an opinion about this:

Discussion is on an earlier PR, see comments starting here: https://github.com/chapel-lang/chapel/pull/11638#issuecomment-442093509

@mppf
> I do think that CHPL_TARGET_CPU would be a better name that CHPL_TARGET_ARCH the way we are using it. Then the new CHPL_TARGET_MACHINE could be CHPL_TARGET_ARCH, which I do think is slightly more intuitive for what it is. I'm just uncertain if this is clearer to anybody else and if it's worth the potential for confusion to change the meaning of CHPL_TARGET_ARCH.

@gbtitus 
> I agree, assuming I'm understanding you correctly. I think of "architecture" as the broader term (examples: x86_64, aarch64, m68k), and "cpu" as the more specific one (examples: sandybridge, thunder-x2, m68030).

@dmk42 
> Whether we make a change or not, it will be confusing. In gcc and clang, x86 targets use -march for the specific CPU. In other targets, they use -mcpu for that. If we change, we'll be confusing when the target is x86. If we don't change, we'll be confusing when the target is other than x86.
>  The non-x86 usage is more intuitive, though. I won't advocate for changing, but it won't bother me if everyone else is on board.

@ben-albrecht 
> I think the redefining of CHPL_TARGET_ARCH to mean x86_64 vs aarch64 makes a lot of sense.

@ronawho 
> we need to figure out how we're going to document this transition and not make it a huge pain for users. This is a very disruptive change IMO

**Comment by mppf** [comment]
@dmk42 
> Whether we make a change or not, it will be confusing. In gcc and clang, x86 targets use -march for the specific CPU. In other targets, they use -mcpu for that. If we change, we'll be confusing when the target is x86. If we don't change, we'll be confusing when the target is other than x86.
The non-x86 usage is more intuitive, though. I won't advocate for changing, but it won't bother me if everyone else is on board.

I think it's important to point out that we should view `-march` and `-mcpu` as precedent rather than as inherent to the purpose of the variable. In particular, when a (future) Chapel user works with an LLVM-by-default Chapel, they won't be invoking GCC, and whether `clang` is involved or uses one flag or another is implementation details that normally would not require any thought on the part of the user.

**Comment by bradcray** [comment]
I support this plan and appreciate the effort put into thinking about easing the transition.  I think I'd like to see the transition help (bullet three, essentially) retired after a release to avoid confusion in the steady-state.

**Comment by mppf** [comment]
I think there are enough of us with good support for this proposal to move forward with it.
