### ISSUE TITLE
Should Chapel users be able to request byte or codepoint indexing explicitly?

### ISSUE THREAD

**Issue by dmk42** [chapel-lang/chapel#11749]
### Current status
Chapel users can request byte or codepoint indexing explicitly.

### Advantages
With string data stored in a multibyte format such as UTF-8, random access can occur faster when done by byte.  Codepoint indexing requires traversing the string to count the number of codepoints, yet is still useful for many situations.  Also, being able to specify the unit of indexing makes Chapel more flexible, and able to handle more situations, such as strings that contain data other than multibyte characters.

### Disadvantages
If the only way to index is by byte, slow indexing will not be an issue.  If the only way to index is by codepoint, strings that contain only multibyte characters can be indexed by codepoint less verbosely.

**Comment by dmk42** [comment]
Regardless of whether we allow arbitrary data in strings, I find utility in allowing both kinds of indexing -- bytes for speed and codepoints for indexing specific to the character set that is in use.

**Comment by gbtitus** [comment]
Allowing both seems nice from a functionality point of view, and assuming that whatever we have to do to not rule out codepoint indexing doesn't harm the speed of byte indexing.

**Comment by bradcray** [comment]
I think supporting both types of indexing falls somewhere between a no-brainer and a necessity.

I think the more challenging questions relate to how a user should select between the two indexing styles, whether there should be a default indexing mode, and what that default mode should be.  (I'm guessing those will be covered in distinct issues, though).

**Comment by mppf** [comment]
I think the standard/internal string implementation should only offer bytes indexing and anything else can be handled by a package module (that does things like compute grapheme clusters, visible widths, converts to/from other character sets, ...)

I'm not the only one who thinks this is reasonable. See:

http://utf8everywhere.org/#faq.python

 > Therefore, we oppose representation-agnostic handling of strings, in favor of representation-transparent API with a UTF-8 internal representation. Indexing operations would be counting code units rather than the code points...

**Comment by dmk42** [comment]
It sounds like we have consensus on what to allow (both), and there are just options on how/where to implement both.

**Comment by dmk42** [comment]
This is resolved by the decision to have explicit indexing by both byte and codepoint.
