### ISSUE TITLE
Should a string be able to store non-multibyte-character data, e.g. binary data?

### ISSUE THREAD

**Issue by dmk42** [chapel-lang/chapel#11748]
### Current status
Strings can contain arbitrary binary data.

### Advantages
Perl is an example of a language that forces strings into the format of the current character set.  GASNet found this to be a mistake after they wrote launchers in Perl.  Arbitrary binary data needed to be stored for transmission between the login node and compute nodes, and Perl changed it.  GASNet's solution was to force Perl into ASCII mode so it would not alter strings.  This means that programs that need to manipulate binary data in strings cannot use any more than the simplest character set in the rest of the program.  It also caused problems for Chapel, because we had to allow the launchers to force ASCII mode, and then reinstate the desired character set upon transfer to Chapel code.

Keeping Chapel fully general in this respect would avoid future problems when people want to manipulate binary data (or other non-multibyte-character data) in strings.

### Disadvantages
If the string code knows that it will only ever manipulate multibyte characters, it might be able to use alternate internal representations that speed random access, such as storing UCS-4 whenever UTF-8 is input.

**Comment by dmk42** [comment]
I believe we should avoid the mistake that Perl made and allow arbitrary data in strings as we currently do.

**Comment by mppf** [comment]
I think we should allow arbitrary data in a string, assuming/asserting that it's UTF-8 only when certain string operations are used. This is the approach that Go takes.

**Comment by gbtitus** [comment]
I think we should allow arbitrary data in strings.  Saying that particular functions or operations are only defined on UTF-8 or other supported encodings seems reasonable, but unilaterally munging strings that are not otherwise operated upon (as I understand perl to have done) is hard to justify!

**Comment by bradcray** [comment]
I agree that we would benefit by having a way to store arbitrary binary data in strings, though I'd prefer to do it by supporting a byte string encoding rather than using UTF-8 strings and ignoring their multibyte nature in some way.  

I'm not concerned about the disadvantage listed above (inability to auto-optimize the character set)—I don't think that the compiler/language/runtime should change the format out from under the user without their involvement.  If the compiler thinks it knows better, I think it should give hints, warnings, or suggestions to the user and let them decide, not make the decision invisibly.

**Comment by dmk42** [comment]
It sounds like we have consensus that we should allow arbitrary binary data, though Brad seems to have a different model of thinking about it from the others.

**Comment by mppf** [comment]
> It sounds like we have consensus that we should allow arbitrary binary data, though Brad seems to have a different model of thinking about it from the others.

I'm not so sure...

I put a comment on another issue that really belongs here:

> I think one facet of this question is whether or not a string-like type storing non-character data (e.g. bytes) should exist or if such data can just be stored in a string.

> Different languages do different things here. The reference I've recently been appreciating though would request that we have a different type for non-textual data so that string is always UTF-8. http://utf8everywhere.org/#faq.liberal :

>> it becomes a problem when the same type, such as std::string, means different things in different contexts. 

I'd be very surprised if nobody wants to argue for "string is always valid UTF-8". Here's what I see as the tradeoff:

* Just store binary data in `string` -> one might reasonably be surprised that only certain string operations actually work on that string. It might be harder to track down which part of a program was responsible for creating a string that is invalid UTF-8. Additionally one might run into issues, such as if the I/O system thinks it's doing character-oriented output it UTF-8, and you try to output something that isn't valid Unicode, it might output a Unicode replacement character or throw an exception.
* Have a different type for binary data -> requires extra effort for typical system-facing scenarios (such as filenames in linux) which are normally interpreted as UTF-8 but don't have to be. But, it's always clear in e.g. an I/O call from the type whether the buffer is to be interpreted as just a sequence of bytes or if it's to be interpreted as textual data.

I think Brad's comment is perhaps requesting two types:

> I agree that we would benefit by having a way to store arbitrary binary data in strings, though I'd prefer to do it by supporting a byte string encoding rather than using UTF-8 strings and ignoring their multibyte nature in some way.

@bradcray - would the difference between a byte-string and a UTF-8-string be known at compile-time or at runtime?

If it's known at compile-time, then we're back to having 2 different types (where the name for `bytes` might just be `string(encoding=bytes)` e.g.). If it's only known at runtime... I'm not as sure of the benefit... but presumably it could be inferred based on the string data itself.

**Comment by dmk42** [comment]
I'm very strongly opposed to string being always valid UTF-8.
And the deadline for this was last night, with nobody asking for more time before the deadline.

**Comment by bradcray** [comment]
> would the difference between a byte-string and a UTF-8-string be known at compile-time or at runtime?

I was definitely imagining compile-time.

**Comment by mppf** [comment]
I was under the impression that in off-GitHub discussions, we reached design consensus on the answer to this question being "No". (Otherwise why would we need a bytes type a-la #13519?). Can this issue be closed?

**Comment by dmk42** [comment]
Yes, now that we have the `bytes` type, we can close this.
