### ISSUE TITLE
Assigning a raw tuple expansion does not fail when it should

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#11784]
### Assigning a tuple expansion
Probably a bug. Assigning a tuple expansion does not fail and yields weird results.
```chapel
var x1 = (1,);
var y1 = (...x1);
writeln(y1);  // 1

var x2 = (1, 2, 3);
var y2 = (...x2);
writeln(y2);  // 3

var x3 = (1, 2, 3, 4, 5);
var y3 = (...x3);
writeln(y3);  // 3 <-- How?
```

### Compiler break

Furthermore, declaring an incorrect type on `y3` doesn't do anything:
```chapel
var x3: 5*int = (1, 2, 3, 4, 5);
var y3: 5*int = (...x3); // This type is wrong.
writeln(y3.type:string);
writeln(y3);
```
outputs
```terminal
int(64)
3
```

and even more fun, if you wrap the code in a `main` function, it now completely breaks:
```chapel
proc main() {
  // Same code. No changes.
  var x3: 5*int = (1, 2, 3, 4, 5);
  var y3: 5*int = (...x3); // This type is wrong.
  writeln(y3.type:string);
  writeln(y3);
}
```
yields compiler error
```terminal
internal error: OPT-SCA-ACE-0354 chpl version 1.19.0 pre-release (0001e1ca6a)
```

### Namespace clash
And one more. Likely unrelated. Likely a namespace conflict that I didn't intend when I was quickly iterating on the previous example:
```chapel
writeln(y1); // ... and nothing else.
```
yields compilation error
```terminal
error: y1: can not capture overloaded functions as values
```

`chpl version 1.19.0 pre-release (0001e1ca6a)`

**Comment by cassella** [comment]
```chapel
y1();
```

```
y1.chpl:1: error: unresolved call 'y1()'
$CHPL_HOME/modules/standard/Math.chpl:1257: note: candidates are: y1(x: real(32)) [193076]
$CHPL_HOME/modules/standard/Math.chpl:1268: note:                 y1(x: real(64)) [193167]
y1.chpl:1: note: unresolved call had id 182223
```

**Comment by bradcray** [comment]
I agree that this is a bug.  The tuple expansion of:

```chapel
var x: 5*int = (1, 2, 3, 4, 5);
```

should effectively turn `(...x)` into `1, 2, 3, 4, 5` yet the following declaration doesn't really mean anything:

```chapel
var y = 1, 2, 3, 4, 5;
```

In our historical focus more on getting correct code working than incorrect code erroring properly, I'm guessing that we just do the expansion regardless of whether or not it makes sense in that context.  I'm imagining the fix being to put in an explicit check for legal contexts.  Quickly thinking about the syntactic contexts where tuple expansions make sense I've come up with:

* argument lists
* domain literals
* tuple literals (requires another set of parenthesis)

Any others?  

And: I have no guess as to why you get `3` in that y3 case...
