### ISSUE TITLE
Is our implementation of network atomic subtraction wrong?

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#11791]
For network atomics in ugni and ofi we implement `atomic_sub(obj, op)` as `atomic_add(obj, -op)`:

https://github.com/chapel-lang/chapel/blob/27a71319bc1e4bcb4d0b32a5b7a6c41bf0f02ffd/runtime/src/comm/ugni/comm-ugni.c#L6770-L6782

https://github.com/chapel-lang/chapel/blob/27a71319bc1e4bcb4d0b32a5b7a6c41bf0f02ffd/runtime/src/comm/ofi/comm-ofi.c#L2252-L2261

We think this is wrong for `min(_t)` for integer ops since for instance `-INT_MIN` is UB.

**Comment by gbtitus** [comment]
For context, quoting from the email conversation that led to this Issue:

@gbtitus:
> ... we actually do this for network atomics in comm=ugni and comm=ofi, because neither Gemini/Aries (thus GNI) nor libfabrics have atomic subtract operators.  Is that a problem?

@dmk42:
> It could be a problem for signed integers.  Unsigned integers are well-defined to wrap.  The issue is that the compiler could say "I'm allowed to assume that there is no undefined behavior, and the most negative value would create undefined behavior here, so that means the most negative value must never be possible."  Then it could use that assumption elsewhere in the program.
>
> If the APIs are defined to operate on unsigned values, then you can just cast any signed value to unsigned before negating.  If they operate on signed values, though, it may not be a good idea to cast to unsigned, negate, and then cast back, because the cast back is implementation-defined and might do different things on different compilers, including trap.  (At least it isn't undefined, though.)
>
> Since it's a network operation, it might be OK to spend the extra time to check the value.  You could do something like this.
>
> #define FOO_NEGATE(x) ((x) == FOO_MIN ? (x) : -(x))

@gbtitus:
> The Chapel API has network atomic subtract for 32- and 64-bit signed ints.  But if we cast to unsigned for the negation eventually we’d have to cast back (for Aries/GNI which only has signed int atomics of both sizes) or at least type-pun (for libfabric which has unsigned int atomics which might invite us to treat the target object as unsigned even though it was signed).  So there doesn’t seem to be a safe way to avoid the test.
