### ISSUE TITLE
should the serial statement prevent vectorization?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11798]
I noticed in #11679 that RV vectorization was causing the fullVerify routine in test/npb/is/diten/is.chpl to fail. The relevant section is this:

``` chapel
serial {
    [i in D] {
      atomic {
	keyBuff1(buffer(i)) -= 1;
	keyArray(keyBuff1(buffer(i))) = buffer(i);
      }
    }
}
```

In commit 7cc609cb9d923ff2a217a489eb77654b7bcf2d18, I change it to this:
``` chapel
  for i in D {
    keyBuff1(buffer(i)) -= 1;
    keyArray(keyBuff1(buffer(i))) = buffer(i);
  }
```

which resolves the issue.

The `atomic` statement isn't implemented yet, so it's not surprising that it doesn't do anything. But the `serial` statement is implemented and presumably whomever put it there thought it would work around the lack of an `atomic` statement.

Should the `serial` statement inhibit vectorization? In one regard vectorization is a kind of parallelism...

**Comment by ronawho** [comment]
Last time @bradcray and I discussed this (3+ years ago when I was working on vectorizeOnly iterator and related vectorization stuff) our thought was that serial should not disable vectorization. The thought was similar to thinking that if you do a `serial forall` it has to run serially, but the iterations could still run in any order. e.g.

```chpl 
serial do forall i in 1..10 do writeln(i);
``` 

is allowed to print 1-10 in any order still (even though our current implementation will happen to print in order.)

i.e. running a forall loop serially doesn't change the semantics of the forall and if vectorization was legal in the parallel case, then it still is in the serial case.

**Comment by gbtitus** [comment]
'Serial' in general usage has a connotation of "in order".  But for Chapel specifically all we say is that a serial-stmt disables task creation within its extended body.  So `serial do forall ...` could mean that although the iterations all run on a single task, that task is nevertheless allowed to do them in any order it wants.  That's useful, especially in the presence of certain kinds of cross-iteration dependencies, but it also seems a bit subtle.

**Comment by bradcray** [comment]
I think I'm going to agree with Elliot and Greg.  To me, Chapel's `serial` means "don't create tasks" (even though perhaps that is not the most precise term for it in retrospect), so I don't think it should impede vectorization.  A back-end compiler may choose to auto-vectorize for loops (right?) which aren't going to vary in their implementation depending on serial, so if we were to decide that serial should squash vectorization, it also implies that we'd need to squash it for all loops within the block, not just parallel ones (right?).

Down the road, if we find we need another way to squash vectorization within code, maybe we invent another way to do so at that time?
