### ISSUE TITLE
Why is K-nucleotide coforall-strings slower with --llvm?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11809]
It's about 20% slower.

https://chapel-lang.org/perf/chapcs/llvm/?startdate=2018/07/05&graphs=knucleotideshootoutbenchmark

**Comment by bradcray** [comment]
This looks like a duplicate of https://github.com/chapel-lang/chapel/issues/11809 and that one has a bit more information, so I'm closing this one.
