### ISSUE TITLE
lifetime annotation syntax proposal

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11804]
This issue discusses syntax for lifetime annotation. This relates to PR #11795, issue #8377, issue #9853, and issue #11680.

### What problems does the lifetime syntax solve?

There are three problems that the lifetime syntax needs to address:
 1. While the inferred return lifetimes are usually good enough to get programs to compile, occasionally the checker will complain about something that is valid. In those events, it's important to be able to specify the return lifetime. (see also #8377)
 2. Certain functions need to require that call sites have a certain constraint among the lifetimes. This came up in the context of array `push_back` in issue #9703. `push_back` needs to be able to require that `this` will not last longer than a borrow pushed on to the array.
 3. The lifetime checker currently uses special rules for `=` since `=` can generally allow the lifetime of the LHS to be inferred from the RHS. This special rule relies on the function name `=` and so it would be worthwhile to have a different way to activate the inference.

### The specific syntax proposal

After a function signature but before the body, a function declaration can include a `lifetime` clause. This is kindof like a `where` clause. (I had originally thought to include these constraints in the `where` clause but that might imply that they have an impact on function disambiguation - and they do not).

For example, this function returning a global hashtable element might need to specify the return lifetime, because otherwise the lifetime analysis will infer that it returns the lifetime of the single argument:

``` chapel
proc getGlobalHashtableElement( key: borrowed ) : borrowed
{
  return globalHashTable[key];
}
```

Here is the same function with a lifetime annotation indicating the lifetime of the result matches the lifetime of `globalHashTable`:
``` chapel
proc getGlobalHashtableElement( key: borrowed ) : borrowed
lifetime return globalHashTable
{
  return globalHashTable[key];
}
```

The idea of the syntax here is that `lifetime` introduces the lifetime clause and that `return globalHashTable` indicates that the lifetime of the returned value from this function is the lifetime of that global.

The lifetime clause can also specify a lifetime constraint among formal arguments. Consider the case of array.push_back:

``` chapel
proc array.push_back( val: borrowed )
{
   ...
}
```

It should be an error use `push_back` to store a borrow into an array that lives longer than that borrow. But, the lifetime checker will not infer this property of `push_back` from the function body and it's not visible from the signature. The following lifetime constraint syntax will communicate this property of `push_back`:
``` chapel
proc array.push_back( val: borrowed )
lifetime this < val
{
   ...
}
```

Now, one might have a function that is similar to `=` but not actually named `=`. For example:

``` chapel
proc setit(ref lhs: borrowed C, rhs: borrowed C)
{
  lhs = rhs;
}
```

Certain call patterns of this function can cause confusing checking errors because the lifetime of the `lhs` will not be inferred to be the lifetime of `rhs`. However there is syntax applicable to the lifetime clause to do that:

``` chapel
proc setit(ref lhs: borrowed C, rhs: borrowed C)
lifetime lhs=rhs
{
  lhs = rhs;
}
```

Here the statement `lhs=rhs` in the lifetime clause should be read as "This function sets lifetime of LHS to the lifetime of RHS".

For more complex cases, the lifetime clause will:
 * allow comma-separated combinations of the above clauses
 * combine inference results as inferring the minimum of the applicable clauses
 * check lifetime constraints from all clauses

**Comment by bradcray** [comment]
Two questions:

1) Can any of `<`, `>`, `<=`, `>=` be used?
2) You and I were discussing a `<=>` lifetime indicator—is that still on the table?

**Comment by mppf** [comment]
> Two questions:
> 
> 1) Can any of `<`, `>`, `<=`, `>=` be used?

Yes

> 2) You and I were discussing a `<=>` lifetime indicator—is that still on the table?

Yes but I havn't implemented it and I think it's reasonable to view it as an enhancement. I've been able to prototype swap with `lifetime lhs=rhs, rhs=lhs` (minus the unrelated detail that the PR uses `&&` instead of `,` right now). I'm not yet certain if that' sufficient.

**Comment by vasslitvinov** [comment]
I like this proposal!
