### ISSUE TITLE
"always RVF" pragma doesn't seem to work at global scope

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#11810]
At present, module-scope variables of a record type declared with the "always RVF" pragma aren't rvf'd.  @benharsh suggests that this is most likely because we don't consider module-scope variables for remote-value forwarding.  Here's a snapshot of a code I was using to determine this.  It the code is pushed into a local scope, it works as expected:

```chapel
class C {
  var y: int;
}

pragma "always RVF"
record R {
  var x: int = 42;
  var c: unmanaged C = new unmanaged C(23);

  record RserHelper {
    var x: int;
    var y: int;
  }
  
  proc chpl__serialize() {
    writeln("In my serialize");
    return new RserHelper(x, c.y);
  }

  proc type chpl__deserialize(data) {
    writeln("In my deserialize");
    return new R(x=data.x, c = new unmanaged C(y=data.y));
  }
}

var myR: R;

writeln(myR);
writeln(myR.locale);
writeln(myR.c.locale);
on Locales[1] {
  writeln(myR);
  writeln(myR.locale);
  writeln(myR.c.locale);
  }
}
```

**Comment by benharsh** [comment]
Just to clarify: is the desired behavior that ``myR`` is broadcasted to all locales?

**Comment by bradcray** [comment]
I was imagining that it would mean that when we entered an on-clause that needed to reference it, we'd RVF it at that time.

**Comment by benharsh** [comment]
What would happen if I referred to the global in a function called within the on-stmt?

```chpl
on Locales[numLocales-1] {
  foo();
}

proc foo() {
  writeln(myGlobal.locale);
}
```

Would we just not RVF in this case?

**Comment by bradcray** [comment]
Oh, that's an interesting point.  I suppose not (and I _think_ that's OK).

I'm trying to think whether there are analogies in the case of nested procedures and without using the "always RVF" pragma that would suggest doing something different.

(the presence of the "always RVF" pragma in this issue complicates things a bit since it isn't first-class yet...  but part of my reason for exploring this is to think about how we could/should potentially expose the notion of a "localize me" type or variable in the language proper, replacing "always RVF".

**Comment by bradcray** [comment]
Tradeoffs between RVF-ing globals and broadcasting them:

RVF-ing when "always RVF" is set:
+ makes handling of slices more consistent regardless of scope
+ only communicates slices to locales that need them
...

Broadcasting:
+ more similar to what we do for privatized arrays at global scope (?)
+ pay once, reap benefits multiple times (?)
...
