### ISSUE TITLE
Internal errors between syntax choice of generic parameterized types

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#11846]
Related #11410. Bug report and user story.
Today, I write this generic code with parameterized types (this works):
```chapel
proc main() {
  var r: R(2, 3);
  writeln(r.type:string);
  writeln(r);
}

record R {
  param n, m: int;

  proc type data_t type {
    return n*(m*int);
  }

  var data: R(n, m).data_t;
}
```
But I want to write this:
```chapel
record R {
  param n, m: int;

  type data_t = n*(m*int); // internal error: RES-TUP-LES-1180

  var data1: R.data_t; // internal error: RES-CAL-NFO-0124 (#11410)
  var data2:   data_t; /* ideally */// error: 'data_t' undeclared (first use this function)
}
```
The internal errors are based on a combinatorial explosion of the two working and non-working code pieces.
`chpl version 1.19.0 pre-release (0001e1ca6a)`

**Comment by lydia-duncan** [comment]
I believe the line with the type field declaration should work.  I view the first var declaration as verbose - it shouldn't give an internal error, but I don't think it is reasonable for it to work either.  Once the type field declaration works, I would expect the second var declaration to work without issue.  Does that match your thinking?

**Comment by lydia-duncan** [comment]
> where partial instantiations are not possible
(which we are also hopefully moving towards supporting)

**Comment by BryantLam** [comment]
> but I don't think it is reasonable for it to work in a world where partial instantiations are not possible.

Sorry, I'm having a hard time parsing that statement. Could you give an example?

> Once the type field declaration works, I would expect the second var declaration to work without issue. Does that match your thinking?

I definitely agree, but there's usually a non-obvious counterargument.

**Comment by cassella** [comment]
This mostly works today:

```chapel
proc main() {
  var r: R(2, 3);
  writeln(r.type:string);
  writeln(r);
}

record R {
  param n, m: int;

  type data_t = n*(m*int); // internal error: RES-TUP-LES-1180

  //var data1: R.data_t; // internal error: RES-CAL-NFO-0124 (#11410)
  var data2:   data_t; /* ideally */// error: 'data_t' undeclared (first use this function)
  var data3:  R(n,m).data_t;
}
```

```
R(2,3,2*3*int(64))
(data2 = ((0, 0, 0), (0, 0, 0)), data3 = ((0, 0, 0), (0, 0, 0)))
```


With `data1` uncommented, it gives the  error

```
foo.chpl:12: error: Cannot replace an instantiated field with another type
foo.chpl:12: note: field 'data1' has type '2*3*int(64)' but is set to '_uninstantiated'
```

But I think that makes sense because `R.data_t` refers to the generic `R`'s generic `data_t`.  (Though maybe the error could be clearer.)

**Comment by cassella** [comment]
Hi @BryantLam , when I tried it the internal errors were gone, and the "ideally" case was working.  If this is working for you, do you want to submit that ideal as a test to lock it in?

**Comment by bradcray** [comment]
Should've noted earlier, but I filed tests here on @BryantLam's behalf and closed this upon doing so.  Thanks for pointing this out, Paul!
