### ISSUE TITLE
What units of string indexing, iteration, and slicing should be supported?

### ISSUE THREAD

**Issue by dmk42** [chapel-lang/chapel#11849]
### Current status
We currently support indexing, iteration, and slicing by byte, and we have partial support for codepoints (remainder of support in progress).

### Advantages of current approach
Byte units provide fast random access as well as allowing non-character data.  Access by codepoint units is slower because it is sequential rather than random access, but allows accessing by assembled multibyte units.  Supporting both of these types of access provides a good mix of capabilities without the added complexity of graphemes.

### Disadvantages
Some character sets allow printing multiple characters in the same printing space to build more complex graphical depictions called graphemes.  Graphemes can be arbitrarily long, which adds a new dimension not required of bytes or codepoints.  String access by grapheme makes it possible to count the number of printing spaces if multiple characters per printing space are used.

**Comment by bradcray** [comment]
I think we need to support byte and codepoint indexes.  I don't think we should worry about supporting a grapheme index type now, but I don't think we should preclude supporting them in the future.

**Comment by dmk42** [comment]
I spent a lot of time scraping the intermediate discussions (online and offline), and I think I have a summary that covers the conclusions toward which we gravitated.  @bradcray and @mppf , have I represented the following accurately?

1.  string.these should yield strings that each contain a single codepoint (as opposed to a single byte).  The reasoning was that in a string, it is more natural for the default accesses to be by codepoints.

2.  string.byte() and string.bytes() should yield integers.  The reason for this is that if we are accessing a single byte within a string, it is likely that we are doing so in order to get its value.

3.  string.codepoint() and string.codepoints() should yield integers.  The reason is that they are more appropriate replacements for ascii() now that we support multibyte characters.

4.  At some point we might want an explicit way to get item 1 on this list, to ease transition if we add graphemes in the future.  However, such an explicit access method can wait because we don't currently have a plan for graphemes (see the comment above).

If I've represented these to your satisfaction, then I can go ahead and implement #12199 .  However, please let me know if I've misunderstood anything.

**Comment by mppf** [comment]
@dmk42 - I'm happy with what you described above, but I think that `string.this` and `string.these` should have consistent behaviors (so according to the above both would yield a string containing a single codepoint).

**Comment by dmk42** [comment]
We decided to provide mechanisms for iterating by byte and by codepoint.  We will leave room to iterate by grapheme in the future but do not have plans to implement it at this time.  We'll add a `byteIndex` and change the default `string.these` to iterate by codepoint.
