### ISSUE TITLE
What character classes/properties should be supported?

### ISSUE THREAD

**Issue by dmk42** [chapel-lang/chapel#11850]
### Current status
We currently support C-like character classes such as `isAlpha` and `isUpper`.

### Advantages of the current approach
Supporting C-like character classes makes it possible to use widely available underlying libraries (the standard C library and the POSIX library).  This also makes it possible to allow multiple multibyte encodings, which we currently do (#11745).  The set of Unicode Character Properties is larger, more complex, and limited to the Unicode character set.

### Disadvantages
If only Unicode is supported, Unicode Character Properties can divide characters up into smaller categories.  For example, C-like character classes distinguish punctuation from non-punctuation; Unicode Character Properties distinguish opening vs. closing punctuation such as open or close brackets, and other subcategories. See https://en.wikipedia.org/wiki/Unicode_character_property .

**Comment by bradcray** [comment]
Apart from "level of effort" is there any reason to believe that a user wouldn't want both?  (C-like character properties and unicode-like character properties?)

**Comment by dmk42** [comment]
The resolution to this issue was that we decided to stick with the ctype classifications for now, but avoid making design changes that would preclude adding Unicode character classifications in the future.
