### ISSUE TITLE
Replace manual page breaks in Spec with more principled solution

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#11872]
#4703 added a bunch of manual page breaks to the spec, likely due to the sections in question getting split weirdly across pages.  Unfortunately this means that when the text shifts due to adding or removing content, the spec ends up looking a bit weird, such as page 122 in the current spec.  That particular example has been fixed today by the addition of other content, but there may be others that are lying around and don't look as good.

I suspect there is probably a way to tell LaTeX to keep content grouped together (such as a modification to the chapelexample syntax or something), but I haven't looked into it yet.  This seems like a good code/doc freeze task, though.

**Comment by mppf** [comment]
The page breaks no longer exist now that the spec has moved to .rst.
