### ISSUE TITLE
Consume any outstanding CQ events if we fail to acquire a comm domain in ugni

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#11876]
If we can acquire a comm domain, but its CQ is full, we should try to consume any outstanding CQ events and decrement the counter.

Currently we only consume outstanding CQ events after we issue comm, but this would help reduce CQ counter pressure that's the result of non-blocking comms where we don't always consume events. 

A related question is whether non-blocking comms should consume any outstanding events on their comm domain before issuing their own request.

Follow on to https://github.com/chapel-lang/chapel/pull/11875

**Comment by vasslitvinov** [comment]
@ronawho is this still on the table? how about closing it?

**Comment by ronawho** [comment]
Yes, this is still on the table
