### ISSUE TITLE
avoid evaluating the argument of .type

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#11882]
Right now evaluating this expression:

```chpl
(+ reduce [idx in myIter()] idx).type
```

results in computing the full reduction at run time, including running `myIter()`. Not once -- twice!

It will be great to avoid that. At least when the resulting type has no runtime component. Ideally, even if it does.

Tests:
```
test/expressions/vass/eval-of-arg-of-.type.chpl

// extracted from this test:
test/arrays/deitz/runtime_types/test_array_type4.chpl
```

**Comment by bradcray** [comment]
This seems somewhat related to issue #11813 and is also an age-old question ("Should computing the type of something evaluate the expression for side-effects, if any").  I definitely think it would be reasonable to not evaluate expressions in this context, and it would be symmetric with our choice to eliminate calls to type functions with side effects at compile-time (at least, I think that's what I've observed).

If we went this route, a potential implementation path (which might help with issue #11813 as well) might be to convert such myExpr.type expressions into type functions and just use the one machinery to handle both cases.

Tagging @mppf on this issue, as I think he picked up #11813 in this sprint (?).
