### ISSUE TITLE
nil checker catches programs that should be valid

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11918]
The nil checker should probably know not to look into conditionals that can't be reached. The programs below are safe and reasonable to write during development.

``` chapel
class C { var x: int; }

proc main() {
  var obj: unmanaged C?;

  if obj then
    writeln(obj.x);
}

```

``` chapel
proc f() {
  return 1;
}

proc main() {
  try {
    f();
  } catch e: Error {
    writeln(e.message());
  }
}
```

Tests:
```
# the first example above
test/classes/vass/if-object-2.chpl
# see also
test/classes/nilability/if-object-1.chpl
# the second example above
test/classes/nilability/catch-no-throw.chpl
```

Updated 2019-10-04:
* `catch-no-throw.chpl` (the second example above) works now
* `if-object-2.chpl` (the first example above) works when using owned/shared/borrowed instead of unmanaged

Updated 2019-12-10:
* `if-object-2.chpl` (the first example above) now works with unmanaged, too, as of #14579 / b9fdd4ced1, so it is [no longer a future](https://github.com/chapel-lang/chapel/pull/14620).
* Still, it is unlikely that the underlying shortcoming has been fixed. We need either to build a reproducer or else declare this issue resolved.

**Comment by vasslitvinov** [comment]
@mppf - in the "postfix-`!` is always required" world, how to expose the shortcoming of the nil checker whereby it looks into the then-branch of `if obj` in this example?
```chpl
  var obj: unmanaged C?;

  if obj then
    writeln(obj.x);
```

In the non-prototype mode `obj.x` reports an error, causing the compiler to exit before nil checker is run.

**Comment by mppf** [comment]
@vasslitvinov - I'm not sure what you're asking. Are you saying that the nil checker no longer complains when the `!` is present? If so, I don't think that changes anything about the priority of fixing this issue (say).
