### ISSUE TITLE
Using LinearAlgebra with 1.18

### ISSUE THREAD

**Issue by damianmoz** [chapel-lang/chapel#11913]
### Summary of Problem

Compiling the following source code

     use Norm;
     use LinearAlgebra;

     var x : [1..10] real = 1.0:real;

     writeln(norm(x));
     writeln(dot(x, x));

with

     chpl --set blasImpl=none --set lapackImpl=none testdot.chpl

works.

Trying something larger fails with

$CHPL_HOME/modules/packages/BLAS.chpl:2155: error: file '' does not have a recognized suffix.

I am using no other LinearAlgebra routines than 'dot'.

**Source Code:**

Attached.

// To the extent possible, providing simplified programs demonstrating the
// problem will be appreciated.

Sadly no.

**Compile command:**
chpl --set blasImpl=none --set lapackImpl=none t2.chpl

**Execution command:**
N/A

chpl version 1.18.0
Copyright (c) 2004-2018, Cray Inc.  (See LICENSE file for more details)

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: intrinsics
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: none
CHPL_AUX_FILESYS: none

gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)

**Comment by ben-albrecht** [comment]
@damianmoz  - Sorry to hear you're running into issues. I have not witnessed the error you are encountering before and suspect it's a bug on our end, so thanks for taking the time to report it.

> $CHPL_HOME/modules/packages/BLAS.chpl:2155: error: file '' does not have a recognized suffix.

I think I know what's going on here, but haven't been able to reproduce the issue myself yet.

> Trying something larger fails with

Could you elaborate more on what you mean by larger? A larger program, matrix, or something else? 

A reproducer of the issue would be very helpful in tracking the problem down.

**Comment by damianmoz** [comment]
I thought I had attached my failing example to my original Github post.

Obviously that failed (Github novice). I'll try again from the office later today.

Thanks for looking at the issue.

**Comment by damianmoz** [comment]
Sorry. Hit wrong button. Did not want to close it!!!

**Comment by damianmoz** [comment]
My file is 144 lines and 2405 bytes. Is that too long for Github to handle in-line.

**Comment by bradcray** [comment]
No, you should be able to cut-and-paste it without problems.  On email you mentioned something about "small windows" but in my version of Chrome, you can drag the lower right corner to make it as big as you need (or a scrollbar will show up if you exceed the visible area).  Pro tip:  To make the code Chapel-formatted, surround it as follows:

```
```chapel
code here
```

(and then three more tics on a line by themselves to close the section).  This will end up looking like:

```chapel
var x: string = sampleFn();
```

**Comment by damianmoz** [comment]
[t2.txt](https://github.com/chapel-lang/chapel/files/2696564/t2.txt)

Try this.

Note that my Chrome browser objected to attaching a file called t2.chpl and said it was unsupported

**Comment by bradcray** [comment]
The link works.  I'll leave it to @ben-albrecht to dig into the actual issue.

**Comment by ben-albrecht** [comment]
This is a 2-in-1 special: one issue is responsible for the error itself, and another issue is responsible for the confusing BLAS error message. I'll get a fix together and include more details in the PR.

@damianmoz  - another pro tip: You can paste larger programs in a [Github Gist](https://gist.github.com) which supports syntax-highlighting and editing instead of uploading the file here. Either way works fine for us, but just letting you know.

For example: https://gist.github.com/ben-albrecht/9398d8c5d5d9d46485beefbfde67e051

**Comment by damianmoz** [comment]
Thanks. I was starting to think it was a pre-Christmas brain-fade. No rush.
