### ISSUE TITLE
Unify optimization flags grammar involving iterators?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#11921]
Real nit-picky and minor, but --[no-]optimize-range-iteration and --[no-]optimize-loop-iterators seem like they should just pick one way of saying it?  Maybe "iterators" to be in keeping with --[no-]inline-iterators?  Maybe I'm misguided, though.

**Comment by lydia-duncan** [comment]
It just seems a little confusing for the user that would type the flags, is all

**Comment by aditmehta9** [comment]
@lydia-duncan Can I take this issue?

**Comment by aditmehta9** [comment]
Am I on right path?

**Comment by lydia-duncan** [comment]
Oh, sorry if I was unclear.  This issue is not looking to change the functionality of the flags.  This is looking to unify their naming scheme so that they follow a similar pattern.  It's not useful for them to be all named the same, I don't even know if the compiler would be able to handle duplicate names.

I'm looking for the flags to be changed to either:
```
--[no-]optimize-range-iterators
--[no-]optimize-loop-iterators
```
or
```
--[no-]optimize-range-iteration
--[no-]optimize-loop-iteration
```

**Comment by aditmehta9** [comment]
@lydia-duncan Now I got it.
Thanks

**Comment by aditmehta9** [comment]
Please review this previous commits were wrong @lydia-duncan

**Comment by lydia-duncan** [comment]
In talking to the rest of the team, it sounds like the different naming was intentional, to indicate a technical difference in their function. We think the names should be improved, but I think doing so in a meaningful way will be difficult without further context.  As a result, I'm going to close this issue without resolving it in the way that was originally suggested
