### ISSUE TITLE
gsoc19

### ISSUE THREAD

**Issue by Naba7** [chapel-lang/chapel#11940]
hey! is chapel participating in gsoc19?
I tried the mailing list,but no response and twitter

**Comment by lydia-duncan** [comment]
Sorry, the Chapel team was on vacation until today.  We'll try to get back to you soon!

**Comment by mppf** [comment]
We're working on getting an application together but we don't yet know if we'll be participating.

**Comment by mppf** [comment]
I'm closing this issue since the question is answered for now & we'll continue working on the GSoC application.

**Comment by Naba7** [comment]
Okay,thanks

**Comment by bradcray** [comment]
> but we don't yet know if we'll be participating.

(If the above is not clear, it means is that our participation will depend upon whether or not Google accepts our application).
