### ISSUE TITLE
complex arithmetic - does real * complex involve promotion of the real to a complex first

### ISSUE THREAD

**Issue by damianmoz** [chapel-lang/chapel#11941]
I went fishing for something on this but could not find anything related.

Given
```chapel
     var x : real;
     var y : complex;
     .....
     var t = x * y;
     var s = (x, 0.0):complex * y;
```
Does Chapel treat the computation of the variation 't' the same as the computation of 's' or is it smart enough, or will it be smart enough, to simply apply the real floating point multiplication of x to each of the components of y when it tries to complex 't'.

**Comment by bradcray** [comment]
HI @damianmoz — It does not; it computes the real * complex product directly to save a few floating point operations, which is one of the reasons we introduced imaginaries and reals distinctly from one another (and from complex types) in the language.

BTW, questions of clarification like this that are not bug reports, feature requests, design brainstorming would be most appropriate (and useful) if posted on StackOverflow with a 'chapel' tag if you're willing to do that (reason being that that's where most people look for Q&A style discussion on Chapel).

Let me know if this answer feels sufficient to close this issue.
