### ISSUE TITLE
Spike: Investigate problems with cstdlib atomics under clang

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#11956]
We tried making cstdlib atomics the default under clang in https://github.com/chapel-lang/chapel/pull/4480, but we ran into portability issues so we reverted in https://github.com/chapel-lang/chapel/pull/4536. We had the start of a workaround in https://github.com/chapel-lang/chapel/pull/4534, but we never finalized anything there. 

This spike is to investigate a better way to work around those issues. We could also consider only making cstdlib atomics the default on macs to start and worry about system header incompatibles later.

**Comment by ronawho** [comment]
@dmk42 Do you know if we still have a system we can reproduce this on? I can't repro on chapcs with clang 3.8 and gcc 4.8.5. However, that's with the clang you built, not a system installed one.

(Linked issues in the description have more info and context)

**Comment by dmk42** [comment]
The whiteboxes or a Cray XE system should be able to reproduce this -- anything running SLES11.

**Comment by ronawho** [comment]
Alright can repro on an ubuntu 14 VM with gcc 4.8.4 and clang 3.9.1 

I can also repro on chap*/chapcs* machines with a setup_clang38_sysheaders.bash variant.

Current thoughts for a workaround are a configure-like check that sees if the following program compiles: 

```c++
#include <atomic>
std::atomic_bool ab;
bool foo() { return atomic_load(&ab); }
```
