### ISSUE TITLE
extern block error : multiple definitions when structures refer to each other

### ISSUE THREAD

**Issue by npadmana** [chapel-lang/chapel#11983]
### Summary of Problem
Consider the code below, which fails with an error that `B` has multiple definitions.

The issue appears to be the fact that `A` has a element that is a `B`; commenting that out works. Also, while defining `b1` doesn't work, `b2` does.

### Steps to Reproduce

**Source Code:**

```chapel
extern {
  typedef struct A_struct A;
  typedef struct B_struct B;
  
  struct A_struct {
    int i;
    // Commenting out this line gets everything working
    const B* b;
  };
  
  struct B_struct {
    A* a;
  };
  
  static B* make() {return 0;}
}


// This line does not work
var b1 = make();

// This line works
var b2 : c_ptr(B_struct) = make();
```

**Compile command:**
`chpl test.chpl` fails with 

```
test.chpl:15: error: 'B' has multiple definitions, redefined at:
  test.chpl:15
```

### Configuration Information
`chpl version 1.19.0 pre-release (6509986)`

**Comment by bradcray** [comment]
You're clearly not taking the universe's hint that c2chapel is the superior way to go... :)

**Comment by npadmana** [comment]
@bradcray  -- nope. :-)

**Comment by npadmana** [comment]
@mppf -- is the following failure related?

```chapel
extern {
  typedef struct {
    int x;
  } A;

  typedef A B;
}

var b : B;
```
fails with
```
test3.chpl:9: error: 'B' undeclared (first use this function)
```
