### ISSUE TITLE
const checking problem with first class functions

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11987]
There appears to be a problem with const-checking and first class functions.

This bug is pointed out by @ty1027:

``` chapel
proc mult10( ref i: int ): void {
    i *= 10;
}

proc test2( fn ) {
    var y = 5;
    fn( y );                // this becomes an error
    writeln( "y = ", y );   // expected result = 50
}

/* test-1 (this works)
var x = 7;
mult10( x );
writeln( "x = ", x ); // gives 70
*/

test2( mult10 );  // error
```

**Comment by cassella** [comment]
This works for me as written today, reporting `y = 50`

**Comment by mppf** [comment]
I've created #21230 to add the case here as a test case to prevent future problems. Will close this issue when that PR merges.
