### ISSUE TITLE
feature request : Chapel equivalents of numpy's `arange`, `linspace` and friends

### ISSUE THREAD

**Issue by npadmana** [chapel-lang/chapel#11992]
Prompted by a discussion on [SO](https://stackoverflow.com/questions/54080440/chapel-equivalent-to-numpy-arange-equivalent-c-for-loop/54081153#54081153), it would be nice to have Chapel equivalents of Python/Numpy's `arange` and friends.

Looking at the numpy documentation, the functions include `arange`, `linspace`, `logspace`, `geomspace`, `meshgrid`, `mgrid` and `ogrid`. 

If I had to pick, `arange`, `linspace` and `logspace` would be the most useful.

A draft version of `arange` exists on the SO link.

**Comment by npadmana** [comment]
The hardest question might be what to call the module these live in!

**Comment by npadmana** [comment]
Here is a version with everything except the grid-procedures defined. I don't have a strong opinion whether this should be part of the extra modules or whether it should just be its own standalone module -- so I'll leave that up to you. 

```chapel
/* This module provides some Numpy look-alike
   functions. As far as reasonable, these are pretty
   close in calling convention to the equivalent numpy
   functions.

*/

module NumpyLike {

  /* Return evenly spaced elements between [start, stop).

     Specifying the type allows one to coerce the output
     to a particular type.

     This is the most generic form, with all parameters specified.

     If step is a floating point number, then stop may/may not
     be included, depending on how the rounding is done. 

     Note that, unlike in Numpy, the type is specified at the
     front.
  */
  iter arange(type dtype, start, stop, step=1:dtype) {
    assert(stop > start, "Stop must be greater than start");
    assert(step > 0, "Step must be greater than 0");
    var x : dtype = start;
    while (x < stop) {
      yield x;
      x += step;
    }
  }

  /* In this case, the type is inferred from start.

     step defaults to 1 here.
  */
  iter arange(start:?t, stop:t, step:t=1:t) {
    for x in arange(t, start, stop, step) do yield x;
  }

  /* Defaults to start=0, step=1, and a specified type */
  iter arange(type dtype, stop) {
    for x in arange(dtype, 0, stop, 1) do yield x;
  }

  /* start=0, step=1, and type inferred from stop */
  iter arange(stop:?t) {
    for x in arange(t, 0, stop, 1) do yield x;
  }

  /*
    Generate num linearly spaced elements between
    start and stop of type dtype.

    If endpoint is true, then the final value is also included.

    Currently, start and stop only take in scalar values like the
    older Numpy functions.

    In general, linspace returns real values, unless coerced.
   */
  iter linspace(type dtype, start, stop, num, in endpoint:bool=true) {
    assert(num > 0, "number of points must be > 0");
    if num==1 then endpoint = false;
    const ninterval = (if endpoint then num-1 else num):real;
    const dt = (stop-start)/ninterval;

    for i in 0..#num do yield (start+i*dt):dtype;
  }


  iter linspace(start, stop, num, endpoint=true) {
    for x in linspace(real(64), start, stop, num, endpoint) do yield x;
  }


  /*
    Generate num logspaced spaced elements. 

    The starting value is base**start, while the end is
    base**stop.

    If endpoint is true, then the final value is also included.

    Currently, start and stop only take in scalar values like the
    older Numpy functions.

    In general, logspace returns real values, unless coerced.
   */
  iter logspace(type dtype, start, stop, num,endpoint:bool=true, base=10.0) {
    for x in linspace(real(64), start, stop, num, endpoint) do
      yield (base**x):dtype;
  }

  iter logspace(start, stop, num,endpoint:bool=true, base=10.0) {
    for x in logspace(real(64), start, stop, num, endpoint, base) do
      yield x;
  }

  /*
    Generate num logspaced spaced elements. 

    The starting value is start, while the end is stop.

    If endpoint is true, then the final value is also included.

    Currently, start and stop only take in scalar values like the
    older Numpy functions.

    In general, logspace returns real values, unless coerced.
   */
  iter geomspace(type dtype, start, stop, num,endpoint:bool=true) {
    const sgn1 = sgn(start);
    const sgn2 = sgn(stop);
    assert(sgn1==sgn2,"start and stop must have the same sign");
    assert(sgn1!=0,"start/stop cannot be zero");
    for x in linspace(real(64), log(sgn1*start:real),
                      log(sgn2*stop:real), num, endpoint) do
      yield sgn1*exp(x);
  }

  iter geomspace(start, stop, num,endpoint:bool=true, base=10.0) {
    for x in geomspace(real(64), start, stop, num, endpoint) do
      yield x;
  }

}
```

**Comment by bradcray** [comment]
@npadmana : Do you think you'd want to see either of the arange/linspace cases incorporated into ranges so that you could do something like:

```chapel
for i in 1.1 to 1.8 by 0.2 do ...
```

say?  As mentioned on SO, this is something that @ronawho and I were kicking around recently when I was working on extending our ranges to work with types other than just integers (namely, enums, booleans, and bigints).

**Comment by npadmana** [comment]
@bradcray : the short answer is that would be nice, but I'm also just as happy with these as iterators. While I see how arange could be written in a range syntax, I don't quite see how you'd do linspace (without extending it). And both are useful in different places.  And I do use logspace/geomspace as  well, so unless you can merge those into ranges as well, I think you'd still need some version of these iterators.

This did bring up a separate question -- is there a way to convert a range directly into an array? For instance, using the iterators above, I can write 
```chapel
var x = geomspace(1,1000,4)
```
which is quite convenient. However, I couldn't seem to find a way to do this with ranges (I didn't try very hard).

**Comment by bradcray** [comment]
As always, feel encouraged these short Qs as SO posts, as they may help others (and will help our standings in some of the language popularity contests).

**Comment by npadmana** [comment]
@bradcray -- I suggest we close this for now and just develop on the Mason project. That'll give us experience with usage, and we'll understand if this should be part of the main language or not. BTW, interested in putting #10328 as part of this?

**Comment by bradcray** [comment]
I think developing it as a mason package would be a fine step forward, but don't think this issue needs to be closed per se.  If `enumerate()` feels like it fits naturally with this effort, it'd be fine with me to have it be incorporated there as well (I don't have a good enough perspective on Python's library landscape to know whether they feel like they go together naturally or not).

**Comment by bradcray** [comment]
@ben-albrecht , @npadmana : Given the merge above, what should we do with this issue?

**Comment by ben-albrecht** [comment]
> I suggest we close this for now and just develop on the Mason project. That'll give us experience with usage, and we'll understand if this should be part of the main language or not.

It sounds like we should close this for now and consider reopening in the future depending on experience with the package, and interest from other users in this feature in the future.

**Comment by ben-albrecht** [comment]
@npadmana (or others) - let me know if you disagree, and we can reopen.

**Comment by npadmana** [comment]
@ben-albrecht -- agreed!
