### ISSUE TITLE
llvm+gasnet support is broken on Crays

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#12011]
We use a [cross-configure script](https://github.com/chapel-lang/chapel/blob/5b13ac20d603fb698b6d3d66768a6f4163fdab19/third-party/gasnet/Makefile#L60) to build GASNet on Crays. This cross-configure script forcibly sets `CC='cc' CXX='CC'`, which means we're always building with the Prgenv- wrappers and not clang-included for llvm.

We happen to build our cray-module with cce first, so this results in us building gasnet for llvm with the cce compiler. When we try to compile a Chapel program as part of `make check`, we're using clang/llvm to link in an object generated by cce, which results in undefined references to cce builtins. e.g. `undefined reference to '__cray_RTOI'`

---

I tried updating the cross-configure script to use `CC=${CC:-'cc'} CXX=${CXX:-'CC'}`. With that we actually build GASNet with clang-included, but our clang-included doesn't have mpi support so the build fails.

I also tried just swapping to PrgEnv-gnu thinking that it should be ABI compatible. The build is successful, but I'm getting runtime failures along the lines of: 

```
node 0 error gasnetc_init_messaging() at /lus/scratch/eronagha/chapel/third-party/gasnet/gasnet-src/gemini-conduit/gasnet_gemini.c:1166: am mmap failed:
*** FATAL ERROR: fatalerror (see above)
NOTICE: Before reporting bugs, run with GASNET_BACKTRACE=1 in the environment to generate a backtrace.
NOTICE: We recommend linking the debug version of GASNet to assist you in resolving this application issue.
srun: error: nid00076: task 0: Aborted
```

Where it looks like the core issue is that mmap (or huge_mmap) failed.

---

Related to https://github.com/chapel-lang/chapel/pull/1866

Note that we ran into this when trying to expand when we run `make check` for llvm in https://github.com/chapel-lang/chapel/pull/12003, but I think this has always been a problem.

**Comment by ronawho** [comment]
Possibly related to this, I'm not sure our use of `CHPL_ORIG_TARGET_COMPILER` in `compiler_is_prgenv` is correct (originally added in #1866)

From discussions with Michael:

```
it just seems wrong to me
CHPL_ORIG_TARGET_COMPILER should be set when we're doing an LLVM build to indicate the "original" compiler
E.g. has_std_atomics in that same file uses get_compiler_name which uses it
-> LLVM build for PrgEnv-gnu would use cc and determine if gcc had atomics
-> would use cstdlib for --llvm which isn't what we want (yet)
vs e.g. in adjust_architecture_for_compiler, it asks if the "original" compiler is prgenv separately
I think that's probably the correct/better way
the use of compiler_is_prgenv in util/chplenv/chpl_3p_qthreads_configs.py get_link_args seems wrong
because it checks chpl_llvm.get which checks for "is the compiler built with LLVM" rather than "Are we working with --llvm"
That should probably check instead for compiler_is_prgenv(orig compiler) and CHPL_LLVM_CODEGEN!=0
I think we should have 2 functions: compiler_is_prgenv and orig_compiler_is_prgenv
uses of compiler_is_prgenv in chpl_arch look OK to me
compiler_is_prgenv in start_test should be orig_compiler_is_prgenv

So:
- remove the check for ORIG_TARGET_COMPILER in compiler_is_prgenv
- add orig_compiler_is_prgenv which includes that check
- fix util/chplenv/chpl_3p_qthreads_configs.py to use orig_compiler_is_prgenv and CHPL_LLVM_CODEGEN
- compiler_is_prgenv in start_test should be orig_compiler_is_prgenv
```

**Comment by ronawho** [comment]
FYI when building with PrgEnv-gnu, gn-mpi seems to work, it's just gn-aries that runs into the mmap execution time failure. Random guess --  maybe we're missing some compile time flags that result in us taking a different code path in gasnet, possibly a result of: 

https://github.com/chapel-lang/chapel/blob/19cd743342b603e79852f375548ea09c7a8fc5d2/third-party/gasnet/Makefile.setup#L16-L29

**Comment by ronawho** [comment]
I'm able to run hello.chpl with `--llvm` under gn-aries if I build with `export CHPL_GASNET_MORE_CFG_OPTIONS=--disable-hugetlbfs`. I don't think that's something we actually want to do, but it probably points to the core issue.

**Comment by mppf** [comment]
So, the GASNet configure arguments are the same except for:
 * CC, CXX, MPI_CC
 * --prefix

**Comment by mppf** [comment]
In a build with CHPL_COMM_DEBUG=1, I'm seeing an assertion failure (((gethugepagesize())&((gethugepagesize())-1)) == 0). I think somehow libhugetlbfs isn't being loaded properly.

**Comment by mppf** [comment]
I think one problem here is that the --llvm binary doesn't include setup_libhugetlbfs which is declared like this:
``` c
static void __attribute__ ((constructor)) setup_libhugetlbfs(void)
```

it's expected to magically run at program initialization for programs linking with it.

**Comment by mppf** [comment]
So, I've reproduced a form of the issue with clang:

``` c
#include <stdio.h>
#include <hugetlbfs.h>

int main() {
  long huge = gethugepagesize();
  printf("gethugepagesize returns %li\n", (long int) huge);
  return 0;
}
```

(clang commands below refer to the built clang-included compiler with its -resource-dir flag)
```
clang -c test.c
clang test.o -lhugetlbfs -static
# resulting program is missing setup_libhugetlbfs
clang test.o -lhugetlbfs 
# this one works but dynamically links with libhugetlbfs.so
clang test.o -Wl,--whole-archive,-lhugetlbfs,--no-whole-archive  -static
# this one works
```

The whole-archive linker trick is used in the libhugetlbfs test scripts.

**Comment by mppf** [comment]
Apparently GCC uses collect2 (instead of / before ld) for the reason of running such constructors:
https://gcc.gnu.org/onlinedocs/gccint/Collect2.html

> The program collect2 works by linking the program once and looking through the linker output file for symbols with particular names indicating they are constructor functions. If it finds any, it creates a new temporary ‘.c’ file containing a table of them, compiles it, and links the program a second time including that file.

**Comment by mppf** [comment]
Here is a C-only version of the issue with clang:

``` c
// ctor.c
#include <stdio.h>

static void __attribute__ ((constructor)) setup_libhugetlbfs(void)
{
  printf("hi from constructor\n");
}
```
``` c
// user.c
#include <stdio.h>
int main() {
  printf("in main\n");
  return 0;
}
```

```
clang-6.0 -c user.c
clang-6.0 -c ctor.c
clang-6.0 user.o ctor.o  # works!

ar rcs libctor.a ctor.o
clang-6.0 user.o -L. -lctor # does not work
clang-6.0 user.o -L. -Wl,--whole-archive,-lctor,--no-whole-archive # works
```

**Comment by mppf** [comment]
` -Wl,--whole-archive,-lhugetlbfs,--no-whole-archive` has the problem of producing duplicate symbols if it appears twice.

`-Wl,--require-defined=setup_libhugetlbfs` asks the linker to please include setup_libhugetlbfs (the library constructor) and appears to work.

**Comment by mppf** [comment]
#12202 made some improvement but there are two remaining TODOs.


1. Consider changing gather-cray-prgenv-arguments.bash to accept the arguments to pass to the compiler (which would simplify the -lhugetlbfs workaround from #12202 and possibly enable GASNet compiled with PrgEnv-cray).
2. Adjust the GASNet build for --llvm to use PrgEnv-gnu or clang-included.
