### ISSUE TITLE
What should happen if an exported function returns a global array (in the opaque array pointer case)?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#12017]
In our meeting yesterday, @mppf asked about the memory management of a global array that was returned via an exported function using opaque array pointers.  I'm going to list potential strategies in this issue and indicate which one I think we should follow at the end (obviously, feel free to disagree and/or propose alternatives I haven't thought of).

- Strategy 1: The C/Python user owns this array now.
  - Pros:
    - This is probably the simplest to implement.  Local arrays get updated so that they won't get cleaned up when they go out of scope - no addition action would be needed to avoid doing this for global arrays and the cleanup function wouldn't need to be updated to account for letting the module cleanup function handle the global.
    - It is relatively simple for the client of the Chapel generated library.  They won't have to reason about whether a pointer returned to them should or should not be cleaned up (there are other strategies to achieve this, though, e.g. adjusting the clean up function to respond to if the array was a local or a global).
  - Cons:
    - If the client of the Chapel generated library does not clean up the global array, it will get leaked (this is true of any array returned to the client, though)
    - The writer of the generated library has to be careful about using the array they return in other places.  To protect the client, they have to be very explicit about when the array is used in other places - i.e. function B will have to explicitly note if it relies on the array returned by function A, so the client knows not to call B after cleaning up the array.  This will make their library less of a black box to their clients.
        - I suspect that in practice library functions will only operate on array arguments that get passed to them.  The main notable exception is likely the locales array, which might be very bad to clean up outside of the normal module clean up function.

- Strategy 2: Track whether the array returned is a local or global array.
This will probably involve a mixture of compiler analysis and an additional field or two on the type.  Compiler analysis for determining at return if special action should be taken (since making the programmer do this seems burdensome and error-prone) and a field to be updated in this case which can be checked at clean up time (to avoid making the user determine whether they should call the clean up function or not, as complexity is more likely to cause mistakes).
  - Pros:
    - This strategy is the best at guarding against leaks or memory errors.
    - Both the client and the writer of the library have to do no additional work.
    - A solution like this could be useful for separate compilation.
  - Cons:
    - Potentially more implementation effort
      - If we can leverage our current lifetime checking in some way, it wouldn't be too bad, though.

Side note: This is kind of a temporary problem.  If we were able to export global variable definitions today, the user would be less likely to obtain them via a function that returns them and it would be natural for the module clean up function to continue to handle cleaning up this global.  However, since returning them would still be possible regardless, having a solution in place is still useful.

**Comment by lydia-duncan** [comment]
I think I've convinced myself that Strategy 2 is the better choice.  @bradcray and @mppf, would you mind weighing in on this question?

**Comment by mppf** [comment]
@lydia-duncan - why wouldn't you use exactly the same rules we have now for non-exported Chapel functions returning an array?
``` chapel
proc f() {
  var localA:[1..10] int;
  return localA; // responsibility for freeing passed to caller
}
var globalA:[1..10] int;
proc g() {
  return globalA; // copy is made, responsibility for freeing that passed to caller
}
proc h() ref {
  return globalA; // No copy is made, caller gets a ref and has no responsibility to free
}
```

**Comment by lydia-duncan** [comment]
Riiiiiiight, I forgot about how that occurred.  Remind me, does that come naturally from in intents?  I.e. for a conversion function
```chapel
proc convertToExternalArray(in arr: []): chpl_opaque_array
    where (getExternalArrayType(arr) == chpl_opaque_array) {

    arr._externally_managed = true;
    return arr._value: chpl_opaque_array;
  }
```
which gets inserted into a wrapper function calling the original, this would fall out naturally?

**Comment by lydia-duncan** [comment]
> But presumably we'd like to allow users to *not* copy an existing array whilst returning it for use in an interop scenario.

In that case, would we want them to have to clean it up afterwards?

**Comment by mppf** [comment]
> > But presumably we'd like to allow users to *not* copy an existing array whilst returning it for use in an interop scenario.

> In that case, would we want them to have to clean it up afterwards?

Consider for example a program returning `globalA` that is a global array variable. The Python/C might want to use this global array (say updating elements or something - so it matters that there is only 1 copy of it). The memory for it is cleaned up normally at the end of the program / when the Chapel library is cleaned up. There is no action required to clean up any interop-specific data structures.

**Comment by lydia-duncan** [comment]
Not entirely certain I understand how this works, so I'm going to try and sketch it out:

The exported versions of function f and g will have a similar signature:
```C
chpl_opaque_array f();
chpl_opaque_array g();
```
The exported version of function h will have a slightly different signature because it is returning a ref instead of a copy?
```C
chpl_opaque_array * h();
```
The user will see the difference between these two signatures and know that they should call the cleanup function on the result of f and g but not on h?  And if they call it on a deref of h's result, that will lead to memory corruption errors and it will be their own fault?

I'll have to think about how to pass h's result to a function that wants a chpl_opaque_array from Python.  I'm sure it's possible, but it might require an additional helper function

**Comment by mppf** [comment]
I don't think it's practical for `h` to return `chpl_opaque_array*`. So,`h` would still return `chpl_opaque_array` but it would have `unowned=true`.

The C user would call the cleanup functions for `f` and `g`. They could call the cleanup function for `h` too, because it will find `unowned=true` and do nothing.

**Comment by lydia-duncan** [comment]
I've incorporated this into my branch.  I'll clean it up possibly today but more likely Mondays (due to having to do goals).  In the meanwhile, I consider this question resolved so I am closing the issue.  Thanks!
