### ISSUE TITLE
Defining rectangular domains using tuples of indices

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#12013]
As a Chapel programmer, I'd like to be able to define a multidimensional rectangular domain using (what appears to be) a range whose elements are tuples because in some contexts (like rank-independent programming),given:

```chapel
var low = (1, 1);
var high = (n, n);
```

 it's far more convenient to say:

```
const D = low..high;
```

than

```chapel
const D = {low(1)..high(1), low(2)..high(2)};
```

In making this proposal, I'm suggesting that rather than interpreting `k*integral..k*integral` as "a range of integer k-tuples" we interpret it as "a domain whose low bounds are defined by the first tuple and whose high bounds are defined by the second one.

**Comment by bradcray** [comment]
> This would involve changing what .. means, which I think might be a bit confusing, since today finding .. in the code pretty much always means "range construction". 

I hear the hesitancy, but find `(1,1)..(n,n)` or `lowIntTuple..highIntTuple` to be such an obvious- and intuitive-seeming way to define a multidimensional domain in a rank-neutral manner that I reach for it intuitively whereas relying on a factory would require learning that it exists and remembering the name.  So maybe turning the question around:  Do you find it valuable to search your code for `..` in order to identify ranges?  I.e., if we migrated it away from "range construction", what would the practical impact be on your workflow?  (Speaking for myself, I do search for `..` often, but am usually happy to have it identify either ranges or domains, where the latter case would show up like `{1..n, 1..n}` today, obviously.

We could potentially interpret this case as a form of promoting range construction (so it's still range construction, just promoted to multiple dimensions).  Or we could just define that ranges of integer tuples are supported and indistinguishable from domains (though I'm not crazy about that because it suggests `D.type` might be vague...)

**Comment by brandon-neth** [comment]
What if `var x = low..high;` creates a tuple of ranges and `var d = {low..high};` creates the multidimensional domain? I think that would match with the non-tuple syntax and would keep the `..` to mean range construction and the brackets to mean domain construction. @bradcray is that what you mean by promoting range construction?

**Comment by brandon-neth** [comment]
Making this distinction would change some behavior: 
```
var rangeTuple = (0..10,0..10);
var domainFromTuple= {rangeTuple};
writeln(domainFromTuple.type:string);
```
currently gives: `DefaultAssociativeDom(2*range(int(64),bounded,false),true)`

**Comment by bradcray** [comment]
>  @bradcray is that what you mean by promoting range construction?

Not exactly, but it is closer to what I meant by making ranges of integer tuples supported and indistinguishable from domains.  My slight hesitation with the proposal is that _typically_ in Chapel an expression like `var x = expr;` causes `x` to have `expr.type` as its type.  There are a few exceptions, but they're not ones we're particularly proud of which makes me reluctant to add additional ones.

By "promoting range construction" I meant "ranges are typically created with integer, enum, or bool arguments; but what if we were to permit a tuple to essentially say "create me multiple ranges" such that:

```
(1, 1, 1)..(n, n,n)
// effectively became
1..n, 1..n, 1..n
// and then we just agreed to put the domain-necessary curly brackets around it:
{1..n, 1..n, 1..n}
```

It's not exactly our normal promotion since that would permit arrays; but since arrays' sizes aren't known and we'd need to know the sizes in order to get the domain's rank (which must be known at compile-time), it seems reasonable to only support it for tuples.  And adding the curly brackets is admittedly beyond normal promotion, but again... it seems like a/the natural interpretation of such expressions to me.

An intermediate option would be to support ranges of tuples and then to permit them to be placed within curly brackets, thus:

```chapel
var D = {(1, 1, 1)..(n, n,n)};
var D2 = {myLowTuple..myHighTuple};
```

I think the main disadvantage to this is that it means that the ranges of tuples without the curly brackets would also need to be valid expressions, which leads to questions like "Well, what would that mean in any other context?"  (i.e., are we just creating a different form of a domain to support and get confused by?)

**Comment by bradcray** [comment]
> Making this distinction would change some behavior:

I don't imagine that case would change or need to (or at least don't understand why it would).  Here, we're only talking about ranges whose bounds are tuples rather than integers.  But your example doesn't contain any such ranges?

**Comment by mppf** [comment]
> So maybe turning the question around: Do you find it valuable to search your code for `..` in order to identify ranges? I.e., if we migrated it away from "range construction", what would the practical impact be on your workflow? (Speaking for myself, I do search for `..` often, but am usually happy to have it identify either ranges or domains, where the latter case would show up like `{1..n, 1..n}` today, obviously.

No I wouldn't search for `..` - it is more just that it makes it easier to understand the code if `x..y` is normally producing a range. (Part of this is coming from the fact that, currently, domain construction is a whole lot more expensive in terms of performance than range construction).

I'd be pretty happy with this approach:

``` chapel
var low = (1, 1);
var high = (n, n);

const D = {low..high};
```

because the `{ }` make it clear that it is constructing a domain.

> I think the main disadvantage to this is that it means that the ranges of tuples without the curly brackets would also need to be valid expressions, which leads to questions like "Well, what would that mean in any other context?" (i.e., are we just creating a different form of a domain to support and get confused by?)

In

``` chapel
var low = (1, 1);
var high = (n, n);

var x = low..high;
```

I would expect `x` to be a tuple of ranges. I think using tuples of ranges to represent part of a domain is common and something we do regularly already (e.g. with `.dims`). As you said in your comment, with that interpretation, the `{low..high}` being a multidimensional domain just falls out.

**Comment by brandon-neth** [comment]
Should `x` be `2*range(int)` or `range(2*int)`?

`2*range(int)`:
- matches operator promotion of operators like `+`  
- matches current use in representing parts of domains

`range(2*int)`:
- matches the notion that we're dealing with a sequence of 2d index values rather than a pair of things. a tuple of ranges doesn't represent that the two sequences are related
- matches the typing of Range Literals: ["The type of a range literal is a range with the following parameters:"](https://chapel-lang.org/docs/language/spec/ranges.html#range-literals)

For strided ranges:
```
var low = (1, 1);
var high = (10, 10);

var x = low..high;
var xs = x by (1,2);
```

If `x` is a tuple of ranges, the "promotion" of the `by` operator would need to be better defined. Especially the notion of "scalar promotable", as I would not normally consider a sequence of integers to be a scalar. 

Choosing `range(2*int)` does then require `..` to consider an order over `2*int`. This becomes slightly problematic with the expression `low..<high`. I would expect the final point of that sequence to be `(9,9)`, not `(10,9)`, which is in line with `..` and `..<` being promoted. 

I think I'm still in favor of `2*range(int)`, with reservations about a tuple of ranges being considered a "range type"

**Comment by bradcray** [comment]
> Should x be 2*range(int) or range(2*int)?

I think Michael's saying he would expect it to be (or be OK with it being?) `2*range(int)`.  That surprises me a little, though, since it seems to contradict:

> it makes it easier to understand the code if x..y is normally producing a range.

But maybe the point is that since none of us are very excited about interpreting it as `range(2*int)`, he'd consider the asymmetry to be worthwhile given the benefits?

I'm a little skeptical that having `low..high` create a tuple of ranges is more intuitive than having it simply create a domain, but also not opposed to having it do so.

I also wanted to note that:

> Part of this is coming from the fact that, currently, domain construction is a whole lot more expensive in terms of performance than range construction

If we felt "domain" was the right answer, I wouldn't want this to stop us from pursuing it, as I think there's reason to believe those overheads could be reduced with some effort.  I'm not clear on what would make creating a DR (default) domain inherently more expensive than a tuple of ranges (say).

**Comment by mppf** [comment]
> I'm not clear on what would make creating a DR (default) domain inherently more expensive than a tuple of ranges (say).

There is probably some clever way around this (maybe with a copy-on-write type strategy) but the issue is that there could be an array declared over the domain (DR or not) and then changing the domain needs to resize the array. That has two implications:
 1. The array needs to refer to the domain and not to the domain's value (we might say it "preserves domain identity").
 2. The domain needs to refer to the array (so that the array can be reallocated when the domain is resized)

I think we can (and do) avoid some of this for domains stored in `const` variables. But it seems to me that these constraints imply that the domain needs to at least be heap allocated (vs being a stack variable like a tuple of ranges).

**Comment by bradcray** [comment]
> > (Part of this is coming from the fact that, currently, domain construction is a whole lot more expensive in terms of performance than range construction).

> the issue is that there could be an array declared over the domain

But aren't we talking about the relative costs of creating a domain vs. a range or tuple of ranges, not of re-assigning an existing one?  I.e., if I write `loTup..hiTup` and create a domain from it, there won't be any arrays declared over it yet, right?  Or are you saying that we pay a lot of cost at the domain creation point even if no array is declared over it yet in order to be ready for arrays to potentially be created using it later?  If that's the case, could we defer that cost until the first array is declared over the domain?

**Comment by brandon-neth** [comment]
> I'm a little skeptical that having `low..high` create a tuple of ranges is more intuitive than having it simply create a domain, but also not opposed to having it do so.

Letting `low..high` create a domain erodes the distinction between ranges and domains. Having it create a tuple of ranges does the same for a singular range and a tuple of them; for example:
```
var low = 1;
var high = n;
var r1 = low..high; // r1.type is range(int)
var r2 = (low,)..(high,); //r2.type is 1*range(int)
```
r1 and r2 would need to behave the same when initializing domains or arrays over them.

Overall, I would rather have `..`, `by`, `[]`, and `{}` all support limited promotion (perhaps solely to tuples) than have `..` create ranges sometimes and domains other times.

**Comment by mppf** [comment]
> > > (Part of this is coming from the fact that, currently, domain construction is a whole lot more expensive in terms of performance than range construction).
> 
> > the issue is that there could be an array declared over the domain
> 
> But aren't we talking about the relative costs of creating a domain vs. a range or tuple of ranges, not of re-assigning an existing one? I.e., if I write `loTup..hiTup` and create a domain from it, there won't be any arrays declared over it yet, right? Or are you saying that we pay a lot of cost at the domain creation point even if no array is declared over it yet in order to be ready for arrays to potentially be created using it later? If that's the case, could we defer that cost until the first array is declared over the domain?

Yes, we path that cost at domain creation to be ready. I'm not sure we can defer the cost until the first array is declared because - if we need to modify the domain - how can we know we are modifying the same domain the array is referring to and not a copy of it?

**Comment by bradcray** [comment]
Here's a case I keep mentally coming back to on this issue.  If I write:

```chapel
var low = (1, 1), high = (n, n);

forall i in low..high do
  writeln(i);
```

with the "creates tuple of ranges" approach, this is essentially equivalent to `forall i in (1..n, 1..n) do` which would give me as output:

```
1..n
1..n
```

Whereas with the "creates a domain" approach, it would be equivalent to `forall i in {1..n, 1..n} do` and give me the n**2 elements in the domain / cross-product of the end coordinates.

My sense (and fear) is that the former is more surprising and more likely to be a cause of surprise and errors than the latter...

**Comment by brandon-neth** [comment]
> ```chapel
> var low = (1, 1), high = (n, n);
> 
> forall i in low..high do
>   writeln(i);
> ```
This is a compelling example. Its a similar reason that `{tupleOfRanges}` is ambiguous between an associative domain with tuple elements and a multidimensional rectangular domain, but is much more direct. This use case is worth making an exception and using `..` to create a domain.

**Comment by mppf** [comment]
I'd probably go the other direction and make iterating over a tuple of ranges do something different or make this pattern have a warning. But I don't have a strong opinion here.

**Comment by bradcray** [comment]
> I'd probably go the other direction and make iterating over a tuple of ranges do something different

I don't like the idea of defining the language to say "iterating over tuples normally yields their elements; however if the tuple is a tuple of ranges, something else [more domain-like] happens."  To me this is a step backwards towards the days when we used plain-old tuples to indicate zippered iteration (i.e., "tuples are interpreted in special ways sometimes").

**Comment by brandon-neth** [comment]
Feels a little weird returning a domain from a function called `chpl_build_bounded_range`, but I think I've got it done. Test wise:

should compile (reverses implied):
- [ ] 1, 2, and 3, dimensional int tuples
- [ ] enum tuples
- [ ] bool tuples
- [ ] 2*int(32) .. 2*int(64)
- [ ] 2*uint(32) .. 2*int(64)

should break:
- [ ] scalar..tuple
- [ ] 2tuple..3tuple
- [ ] 2*int..2*enum

Any other test cases suggestions?

**Comment by bradcray** [comment]
Cool!

> Feels a little weird returning a domain from a function called chpl_build_bounded_range

We could definitely rename this going forward (e.g., `chpl_build_bounded_sequence` or the like).

**Comment by bradcray** [comment]
One other thought that occurs to me since Brandon has implemented this, but it's not obvious to me whether we have a enough agreement to move forward with it:  We could make it a feature that's only available when you opt-in with a config param, and then see whether, over time, users lean on it more and appreciate it / want it always-on, or fear it and want it gone.
