### ISSUE TITLE
Internal error from (bad?) initializer

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#12026]
### Summary of Problem

The following program is generating an internal error:

```chapel
class C {
  var name: string = "hi";
}

class D: C {
  type t;

  proc init(type t) {
    this.t = t;
  }

  proc init(s: string, type t) {
    this.name = s;
    this.t = t;
  }
}

var myD = new owned D("bye", int);
writeln(myD);
```
**Associated Future Test(s):**
[`test/classes/initializers/generics/inheritance/badInit.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/generics/inheritance/badInit.chpl
          ) #12025

### Configuration Information

- Output of `chpl --version`: `1.19.0 pre-release (63d96663cb)`

**Comment by bradcray** [comment]
Attn: @benharsh

**Comment by benharsh** [comment]
I think your associated ".good" file is incorrect. Shouldn't the user be writing "super.init(name)" instead? I think the pattern as-is would be a compile-time error message like:
```can't set the value of field "name" from parent type before calling this.init() or super.init()```

**Comment by bradcray** [comment]
I agree that that's the preferred form that should be written, but I couldn't decide/remember whether this form was also legal or not (and am fine if the .good file changes... I was just filing something as a placeholder and should've noted it as such beyond the "bad?" in the issue title).  I find that I use particular initializer patterns and then can't always remember what we decided for others (because I don't stray from my preferred pattern very often).  Mostly I just wanted to stop the internal error from happening.

Here's how I was rationalizing that this form _might_ be legal.  The compiler might say:
* I don't see a super.init(), so I'll call the default one and initialize the string to the empty string
* now the object is a C
* now it's OK to assign to C.name and override the empty string since that's something that can be done to a C.
* now I see the initializations of the other fields, so I'll initialize them

Specifically, changing the `type t` to an `int variable` permitted a similar pattern to work without errors I believe which is what made me start wondering whether this form was legal as well.

Again, though, I haven't completely internalized all the rules very well, and am not advocating for changes to them, just for the internal error to go away.

**Comment by benharsh** [comment]
The problem appears to be that the compiler is generating "this.name = s;" as a field accessor method call. We try and resolve that method with a 'this' that has the generic, uninstantiated type 'B'. If I sidestep that error, I then encounter an error when the compiler attempts to cast 'this' to the parent type. I'm not sure how to work around the cast call since we have to resolve "_cast" to see if there's a more specific version than the PRIM_CAST wrapper in ChapelBase.

Perhaps we should say that field accessor methods won't be invoked until after this.complete() ?
