### ISSUE TITLE
proposal: interop type for fixed size arrays

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#12033]
This is a specific proposal that started from #12004 and #11939.

Some interoperability scenarios involve C arrays of fixed size. For example, this structure field:
``` c
  typedef struct {
    double dat[2];
  } mypair;
```

This issue proposes adding a new type, `c_array`, that represents a fixed-size C array. This type will be added to the internal module `CPtr.chpl`. Here is a sketch of the interface for this type:
``` chapel
/* This class represents a C array with fixed size.
     A variable of type c_array can coerce to a c_ptr with the same element type.
     In that event, the pointer will be equivalent to `c_ptrTo(array[0])`.
     A c_array behaves similarly to a homogenous tuple except that its indices
     start at 0 and it is guaranteed to be stored in contiguous memory.
     A c_array variable has value semantics. Declaring one as a function local
     variable will create the array elements in the function's stack. Assigning
     or copy initializing will result in copying the elements (vs resulting in two
     pointers that refer to the same elements).
     A `nil` c_array is not representable in Chapel.
 */
class c_array {
  /* The array element type */
  type eltType;
   /* The fixed number of elements */
   param size;
    /* Retrieve the i'th element (zero based) from the array.
      Does the equivalent of arr[i] in C.
        Includes bounds checking when such checks are enabled.
    */
    inline proc this(i: integral) ref { ... }
    /* As with the previous function, returns the i'th element (zero based)
        from the array. This one emits a compilation error if i is out of bounds.
    */
    inline proc this(param i: integral) ref { ... }
    /* Print the elements */
    proc writeThis(ch) { ... }
    /* Copy-initialize from another `c_array` */
    proc init(other: c_array) { ... }
}
/* Copy the elements from one c_array to another.
    Raises an error at compile time if the array sizes or
    element types do not match. */
proc =(ref lhs:c_array_ptr, rhs:c_array_ptr) { ... }
```

Here are some important things to emphasize about this proposal:
 * `c_array` is a value type, like tuples
 * `c_array` will only ever be 1-dimensional and only ever store 1 element type
 * `c_array` index starts at 0

Besides the above notes, these are important details of the implementation:
 * A `c_array` field or variable will generate to C code as a C array, e.g. `double dat[2]`
    * and to LLVM IR as an LLVM array
 * The compiler will include a coercion from `c_array(eltType)` to `c_ptr(eltType)`; the result of the coercion will be equivalent to `c_ptrTo(array[0])`.
 * In C, it *is* possible to reassign the pointer in a fixed-size array. That won't be possible in Chapel code using these types.
 * C treats these fixed-size arrays mostly as pointers. This would conceivably lead to a mismatch if a C function returns a fixed-size array, but such C functions are not legal C. An `export proc` should (at least initially) result in an error if it tries to return a `c_array`, since it wouldn't be representable as a C function signature. Such fixed size arrays can be allocated by the caller and the elements can be returned through an argument. Our `export proc` support could one day do this transformation automatically if necessary.

Lastly, besides interoperability, this type could possibly be used to improve compiler support for homogenous tuples. In particular, the compiler would not need to create 1024 fields for a tuple such as `1024*int` as it does now - it could use a `c_array` instead to implement the tuple.

**Comment by bradcray** [comment]
I like this proposal.

**Comment by mppf** [comment]
Once this proposal is implemented, there are two TODOs:

 1. Update the extern technote to recommend this approach for fixed-size arrays
 2. Update the test in issue #12055 to use the new approach and verify that it works
