### ISSUE TITLE
spike: diagnose and fix comm=ofi bugs demonstrated by full testing failures

### ISSUE THREAD

**Issue by gbtitus** [chapel-lang/chapel#12064]
In #11942 I fixed nearly all of the testing failures for full comm=ofi testing which were caused by problems with the testing itself, whether in .good files or other aspects of testing such as system prediff filtering.  However, that still left about 150 failures that were looked like problems in the comm layer itself, or were timeouts.  So now it's time to buckle down and solve these harder problems.

**Comment by gbtitus** [comment]
Most of the non-timeout failures that looked like actual comm layer problems are fixed by #12098.  Moving on to the timeouts ...

**Comment by gbtitus** [comment]
The most important question in regard to the timeouts I saw in comm=ofi full testing on chapcs was whether they were indicative of comm layer problems or were just due to a fundamental lack of performance for sockets-based communication.  To give myself some context, I ran the `performance/comm/low-level/many-to-one` test on chapcs with comm=ofi and the sockets provider, and on XC with comm=ofi+sockets, comm=ofi+gni, and comm=ugni.  The runtime libraries were built optimized/non-debug and the compilations were done with `--fast`.  All the runs used 8 nodes.  The XC nodes were IV24 ones, as the best match for the chapcs nodes.  (The nightly XC performance runs use 16 nodes but we don't have that many chapcs nodes and I wanted to use the same everywhere.  So, the comm=ugni column results don't match our XC nightly performance results.)  All of these results are mOps/second:

op | chapcs, ofi, sockets | XC, ofi, sockets | XC, ofi, gni | XC, ugni
-- | -- | -- | -- | --
get | 0.19 | 0.12 | 32. | 77.
put | 0.17 | 0.12 | 14. | 14.
fetchAmo | 0.18 | 0.12 | 32. | 72.
amo | 0.21 | 0.12 | 32. | 84.
fastOn | 0.063 | 0.036 | 0.44 | 1.4
on | 0.0095 | 0.0041 | 0.37 | 0.72

Surprisingly, ofi+sockets is actually faster on chapcs than on XC, by as much as 2x in some cases.  As expected, native ugni-based comm is as much as several hundred times faster than sockets.

**Comment by gbtitus** [comment]
A discovery: at least one test, `distributions/bharshbarg/stencil/periodic`, is not actually hanging on chapcs, it's just much slower there.  In one example (it's highly variable), it ran for almost 19 minutes of wall time on 4 24-core nodes, while burning through almost 2.5 hours of user+system CPU time.

**Comment by ronawho** [comment]
> A discovery: at least one test, distributions/bharshbarg/stencil/periodic, is not actually hanging on chapcs, it's just much slower there. In one example (it's highly variable), it ran for almost 19 minutes of wall time on 4 24-core nodes, while burning through almost 2.5 hours of user+system CPU time.

It might be interesting to see how long that test takes for gasnet-udp in a similar setup (i.e. use 4 locales instead of local spawning.)

**Comment by gbtitus** [comment]
An enduring puzzle with regard to the timeouts has been: why do they occur on chapcs with the sockets provider, but not on XC with that same provider? Certainly the sockets provider should be ignorant of the (hardware) network architecture. There could be performance benefits below the syscall interface in the SW stack, and in the hardware, but the code paths in the sockets provider itself should be the same in both cases. And although there is some difference between chapcs and XC performance with the sockets provider on the `many-to-one` test, the advantage there actually goes to chapcs (see [this comment above](https://github.com/chapel-lang/chapel/issues/12064#issuecomment-456932515)).

The implication is the that cause of the much slower execution on chapcs is somewhere other than in libfabric itself.  The system launcher (mpirun on chapcs vs. srun on XC) is an obvious candidate, but I've looked at how OpenMPI is managing the launches and don't see anything wrong.  In particular, whether I launch within a `salloc` job and use remote slurm-managed compute nodes with no overloading or launch manually with mpirun on a single node with overloading allowed, the CPU masks allow use of all cores and the slowdown is the same.

**Comment by gbtitus** [comment]
> It might be interesting to see how long that test takes for gasnet-udp in a similar setup (i.e. use 4 locales instead of local spawning.)

I tried it just now; it ran in about 7 seconds.  My XC comm=ofi runs were longer (~20 seconds), but that may be because I'm using a debug runtime.

**Comment by ronawho** [comment]
>>It might be interesting to see how long that test takes for gasnet-udp in a similar setup (i.e. use 4 locales instead of local spawning.)

> I tried it just now; it ran in about 7 seconds. My XC comm=ofi runs were longer (~20 seconds), but that may be because I'm using a debug runtime.

I see similiar timings (10~12 seconds per execopt)

Misc thoughts -- we're already throwing `-bind-to-none` so I'd be surprised if Open MPI affinity was interfering (could run with `QT_AFFINITY=no` to see if that has any impact though). It might also be worth looking at what args gasnet-mpi throws to mpirun.

**Comment by gbtitus** [comment]
Neither `QT_AFFINITY=no` nor `QT_SPINCOUNT=300` seems to have any effect.

**Comment by gbtitus** [comment]
> ...  It might also be worth looking at what args gasnet-mpi throws to mpirun.

I built gasnet with `CHPL_COMM_SUBSTRATE=mpi` and then used `strace -e trace=process` to watch the `gasnetrun_mpi` launcher run `mpirun` on chapcs.  The result was nothing fancy.  It just threw `-np <procs> -npernode 1`.  Outside of a slurm  job the mpirun griped about lack of resources, and inside of a slurm job the target program ran to completion.  But in particular, it doesn't look like they're throwing any of the binding options to mpirun.

**Comment by gbtitus** [comment]
@ronawho I should mention: I'm not creating all these comments because I'm stumped, and in particular am not seeking to yank you off of your scheduled work to help with this.  I'm just using this story as a place to log information.

**Comment by gbtitus** [comment]
I turned on debug AMO logging and noticed that I was seeing a lot of atomic int64 reads, way more on chapcs than on XC.  Mental pattern matching led me to believe they had to do with coforall-node `endCount` waiting.  I added counters to the AM 'done' waiting and sure enough, typical spin loop counts for AM 'done' are < 100,000 on XC and often > 10,000,000 on chapcs.  (All are executeOn, by the way, there don't seem to be any other AMs happening.) So something is delaying the arrival of AM executeOn 'done' indicators.  It shouldn't be that the actual on-stmt bodies are taking longer to execute, because the processors on chapcs and the XC nodes I'm using are about the same: 24 cores at just over 2.5 gHz.  It could have to do with lack of progress for the 'done' `ofi_write()` operations on the on-stmt target nodes.  I'm going to instrument those wait loops next.

**Comment by gbtitus** [comment]
> It could have to do with lack of progress for the 'done' `ofi_write()` operations on the on-stmt target nodes. I'm going to instrument those wait loops next.

This is looking like a fruitful line to pursue.  I put counters into the loops that wait for completions from AM  'done' `fi_write()` operations back to the initiators.  (I had to recode the one for the AM handler's tx counter which is used in the 'fast' case where the handler itself executes the on-stmt body, because the existing code doesn't wait for completions there but instead just consumes the contextless counter events as they occur.)  On the XC typical wait loop counts are < 10 across the entire program (still `distributions/bharshbarg/stencil/periodic`).  The only exceptions I saw were 3 instances of 10 trips around the loop.  On chapcs I see over 9000 instances of wait counts >= 1000, and the program is nowhere near finished executing.  Nearly all of these are for txCqs but (as of this writing) 3 are also for the AM handler's txCntr.

So something is delaying AM 'done' write completions on chapcs.  It could be a progress problem, but there are other possibilities as well.

**Comment by gbtitus** [comment]
I have pretty solid evidence that this is a platform-related progress problem.  Changing from manual to automatic progress brings the chapcs execution time down to a pretty solid 20+-1 second over 5 runs.  For reference, on XC it's a little faster but a little more variable, at 19+-2 seconds.  So basically, that puts them even.

Automatic progress actually raises the average AM 'done' wait loop trip count to over 60, versus just under 30 for manual progress.  This makes sense, because it introduces more threads to do the progress management.  But it greatly improves overall performance by reducing the worst case behavior.  Looking at the distribution of AM done completion wait loop trip counts is instuctive.  Here are the results for a run with manual progress:

log10(trips) | # AM done waits
-- | --
1 | 1529838
2 | 1459
3 | 6943
4 | 9020
5 | 118
6 | 0

In nearly all cases we wait hardly at all, but there are almost 10,000 instances where we wait for 10,000 trips or more.  And here are the results for a run with automatic progress:

log10(trips) | # AM done waits
-- | --
1 | 17416
2 | 511185
3 | 40576
4 | 148
5 | 80
6 | 16
7 | 0

The expected case rises to the 10-100 trip range, but the worst case behavior is much better: now we hardly ever wait for 10,000 trips or more.

I'll be looking at what might be delaying transaction progress next.
