### ISSUE TITLE
Spike: Design an IO interface combining NetCDF, HDF5, CSV, etc.

### ISSUE THREAD

**Issue by daviditen** [chapel-lang/chapel#12060]
Design an IO interface that combines various IO formats and libraries into a single powerful library.

**Comment by ben-albrecht** [comment]
[Pandas' IO interface](https://pandas.pydata.org/pandas-docs/stable/io.html) might be a good starting point for this.

**Comment by daviditen** [comment]
I opened issue #12161 with a link to a gist showing my proposed interface for discussion.
