### ISSUE TITLE
Spike: Investigate standalone vector/set types

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#12068]
This spike involves the investigation of standalone vector/set types in two ways:
- how deprecation warnings for old push/pop_front/back methods will impact user code
- how these types could be implemented outside of the _array infrastructure

**Comment by benharsh** [comment]
The following tests would encounter compiler warnings for usage of vector ops. They fall into different categories.

A) Vector always used in same scope
- arrays/bharshbarg/popFrontLeak2.chpl
- arrays/bharshbarg/popFrontLeak3.chpl
- arrays/bharshbarg/popFrontLeak.chpl
- arrays/diten/array-as-vec-bounds-checking.chpl
- arrays/diten/array-as-vec-remove-elts.chpl
- arrays/diten/array-as-vec-start-idx.chpl
- arrays/diten/arrayAsVecShrinkBug.chpl
- arrays/diten/arrayBack2D.chpl
- arrays/diten/arrayBackOOB.chpl
- arrays/diten/arrayClear.chpl
- arrays/diten/arrayFront2D.chpl
- arrays/diten/arrayFrontBack.chpl
- arrays/diten/arrayFrontOOB.chpl
- arrays/diten/arrayInsertPastEnd.chpl
- arrays/diten/arrayRemove.chpl
- arrays/diten/arrayReverse.chpl
- arrays/diten/popReturns.chpl
- arrays/diten/vectorArrayMisuse.chpl
- arrays/diten/vectorArray.chpl
- arrays/methods/vectorMethods.chpl
- arrays/userAPI/arrayOps2D.chpl
- associative/bharshbarg/domains/recordWithRange.chpl
- classes/delete-free/lifetimes/bad-push-back-borrow.chpl
- classes/delete-free/lifetimes/push-back-borrow.chpl
- classes/delete-free/lifetimes/push_back_lifetime.chpl
- classes/delete-free/push-back-owned.chpl
- exercises/c-ray/<various>
- library/packages/MatrixMarket/mm-dense4x3-write.chpl
- library/standard/DateTime/testDate.chpl
- optimizations/bulkcomm/bharshbarg/stridedAssignDR.chpl
- release/examples/primers/arrayVectorOps.chpl
- studies/dedup/dedup-distributed-ints.chpl
- studies/dedup/dedup-distributed-strings.chpl
- studies/dedup/dedup-extern.chpl
- studies/dedup/dedup-local.chpl
- studies/dedup/dedup-spawn-sort.chpl
- studies/twitter/sleepsort.chpl

B) Vector used/passed as an array type
- arrays/diten/timeVectorArray.chpl
- arrays/ferguson/pushback-no-leak.chpl
- sparse/CS/multiplication/correctness.chpl
- sparse/CS/multiplication/performance.chpl
- studies/shootout/reverse-complement/bharshbarg/revcomp-buf.chpl
- studies/shootout/reverse-complement/bharshbarg/revcomp-line.chpl

C) Vector used in standard lib
  - Spawn
    - compflags/diten/savec.chpl
    - io/ferguson/stdin-is-directory/stdin-is-directory.chpl
    - library/standard/Spawn/illegal-args.chpl
    - library/standard/Spawn/spawn-popen-input-error-long.chpl
    - library/standard/Spawn/spawn-popen-input-output-error-long.chpl
    - library/standard/Spawn/spawn-popen-input-output-error.chpl
    - library/standard/Spawn/spawn-system-shell.chpl
    - patterns/cltools/fileCompile/chplCompile.chpl
    - performance/compiler/elliot/updateDatFiles.chpl
  - LinearAlgebra
    - library/packages/LinearAlgebra/correctness/no-dependencies/correctness.chpl
    - release/examples/primers/LinearAlgebralib.chpl
  - library/packages/TOML/*
    - mason itself, and its tests
  - Path
    - library/standard/Path/prithvi-unnati/commonPath/testCommonPathArray.chpl
    - library/standard/Path/prithvi-unnati/commonPath/testCommonPathStringArguments.chpl
    - library/standard/Path/victor-ludorum/testcases_isAbsPath.chpl

D) Used in vector-wrapper
- release/examples/benchmarks/lcals/LCALSMain.chpl

**Comment by benharsh** [comment]
The following tests fail when compiler warnings are added for set operations:
- associative/bharshbarg/arrays/arraySetOps.chpl
- associative/bharshbarg/arrays/opEquals.chpl
- associative/bharshbarg/domains/domainSetOps.chpl
- associative/bharshbarg/domains/opEquals.chpl
- associative/bharshbarg/domains/reduceArrOfAssocDom.chpl
- domains/diten/assocDomIntersect.chpl
- domains/sungeun/assoc/equals_minus_1.chpl
- domains/sungeun/assoc/index_not_in_domain_1.chpl
- domains/sungeun/assoc/minus_equals.chpl
- domains/sungeun/assoc/plus_equals.chpl
- exercises/duplicates/duplicates-alt-assoc-reduce.chpl
- reductions/vass/histogram-1.chpl
- reductions/vass/histogram-2.chpl
- release/examples/primers/associative.chpl
- users/engin/sparse_bulk_dist/sparseAdd1D.chpl
- users/engin/sparse_bulk_dist/sparseAdd2D.chpl
- users/engin/sparse_bulk_dist/sparseBulk1D.chpl
- users/engin/sparse_bulk_dist/sparseBulk2D.chpl

**Comment by bradcray** [comment]
Does category A ("Vector always used in same scope") reflect cases where we'd have to update the code (e.g., change the type of the variable from array to vector) but wouldn't otherwise need to make changes to keep it working?  (as opposed to category B, say, where it sounds like we'd need to change function signatures or support vectors being passed where arrays are supported?)

**Comment by benharsh** [comment]
Yes, that's correct. Category C (usage in standard libs) contains both kinds of patterns from A and B, but since we control the standard lib I thought it was worth splitting into its own section.

**Comment by bradcray** [comment]
This seems encouraging then, I think (?).  Like, we could probably inject an explicit vector(t) type into our testing system without too much trouble (of course, it would still likely cause pain and suffering for users, but better to get that out of the way now than wait until later?)

**Comment by benharsh** [comment]
I think that's accurate.

Also: we can keep the set operations on associative domains, right? Seems like we could because there isn't the one-to-one array-domain requirement.

**Comment by benharsh** [comment]
(Closing for sprint-tracking purposes)
