### ISSUE TITLE
check-returns-good.chpl leaks memory

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#12091]
There seems to be a problem with lowering error handling where the error is not freed in this test.
It comes up also in other tests with a catch block containing a return.

test/errhandling/psahabu/check-returns-good.chpl

``` chapel
proc minusOne(x: int): int throws {
  if x == 0 then
    throw new owned Error();
  return x - 1;
}

proc consumeMinusOne(x: int) {
  try {
    return minusOne(x);
  } catch {
    writeln("caught error");
    return 0;
  }
}

writeln(consumeMinusOne(5));
writeln();
writeln(consumeMinusOne(0));
```

**Comment by e-kayrakli** [comment]
Neither the test, nor the reproducer leaks today. @mppf does this issue capture anything beyond this snippet that we should still be aware of? Otherwise I think we can close it.
