### ISSUE TITLE
Documentation rolling up "special" class/record methods

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#12104]
As a new Chapel programmer, I'd like to see some friendly documentation (e.g., a primer example) that runs through all of the "special" method calls that one might define on a class or a record such as `this()`, `these()`, `[read]writeThis`, etc. because currently documentation on such features is spread around and it's useful to know what options are available for creating a rich object type in Chapel.

**Comment by daviditen** [comment]
Closed with PR #12245
