### ISSUE TITLE
Minor problem with Learn Chapel in  Y MInutes

### ISSUE THREAD

**Issue by tmacd8** [chapel-lang/chapel#12120]
Minor problem with Learn Chapel in  Y MInutes

### Summary of Problem

The learnchapelinyminutes web page contains:

```
// one line comment

   multi-line comment
```

but there is no multi-line comment example.

**Comment by tmacd8** [comment]
Hmm - after closing the Brave browser and rebooting, the multi-line comment is now preset,  Go figure.

**Comment by tmacd8** [comment]
All is well.

**Comment by tmacd8** [comment]
OK - one more time.  If I use URL:

https://learnxinyminutes.com/docs/chapel/

the comment text looks good.  However, if I use:

https://chapel-lang.org/docs/primers/learnChapelInYMinutes.html?highlight=learn

the issue is present.  Sorry for the confusing issue as I am easily confused.

**Comment by daviditen** [comment]
I see the issue in Chrome too.  The comment delimiters aren't showing up in the chapel-lang.org version of the document.

**Comment by mgautam98** [comment]
From where can I see the scripts that are used to turn Chapel sourcs in .rst?

**Comment by bradcray** [comment]
I'm not the expert on this (so someone may get you to a more direct answer), but I believe that the Makefile step that kicks off the process can be found here:  https://github.com/chapel-lang/chapel/blob/master/doc/Makefile#L55 (which suggests that the script in question is `$CHPL_HOME/doc/util/chpl2rst.py`.

**Comment by bradcray** [comment]
@tmacd8 : Thanks for reporting this.  It took us awhile to get around to fixing it, but our new summer intern, @ShreyasKhandekar knocked it out this week (after running into it himself).
