### ISSUE TITLE
Compiler performance regression from #12090

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#12142]
There was a non-trivial regression in terms of the number of statements we emit and compiler performance from "Catch blocks catch owned, test code throws owned" (#12090)

Here's some graphs ([emitted code size](https://chapel-lang.org/perf/chapcs/?startdate=2019/01/19&enddate=2019/01/24&graphs=jacobiemittedcodesize), [compilation time](https://chapel-lang.org/perf/chap01/?startdate=2019/01/19&enddate=2019/01/24&suite=allcompilationpasstimings)): 

![image](https://user-images.githubusercontent.com/1588337/51715764-f2eff380-1fee-11e9-800b-4819de804d98.png)

![image](https://user-images.githubusercontent.com/1588337/51715769-f84d3e00-1fee-11e9-83eb-6c989206dc51.png)

**Comment by mppf** [comment]
#12090 added OwnedObject to the included-by-default modules and I'm pretty sure (but not absolutely certain) that action is responsible for the increase in compilation time.

**Comment by ronawho** [comment]
Even if the end result ends up being "The compiler needs to get faster" and we can't fix this for now, it'd be good to understand what exactly caused the slowdown.

Ping me if you want a hand digging

**Comment by ronawho** [comment]
I think all the extra code is init/deinit and release/clear for the owned record used for any routine that throws errors. It's only adding ~10 lines per use of owned, but there's hundreds of uses so it adds up quickly. He's a sample diff between the generated code before and after the PR (basic pattern repeated a couple hundred times when looking at the whole diff):

```diff
<     new_temp = _new7(&local__str_literal_2065, _ln, _fn);
<     call_tmp61 = chpl_fix_thrown_error(((Error)(new_temp)), _ln, _fn);
<     *(error_out) = call_tmp61;
<     i_x = &str;
<     deinit30(i_x, _ln, _fn);
---
>     new_temp = _new7(&local__str_literal_2069, _ln, _fn);
>     init61(&initTemp, new_temp);
>     call_tmp61 = initTemp;
>     i_x = &call_tmp61;
>     i__retArg = &ret_tmp2;
>     _formal_tmp_x = *(i_x);
>     call_tmp63 = release11(&_formal_tmp_x);
>     init67(&initTemp2, ((Error)(call_tmp63)));
>     call_tmp64 = initTemp2;
>     ret3 = call_tmp64;
>     ret2 = ret3;
>     *(i__retArg) = ret2;
>     chpl__autoDestroy13(&_formal_tmp_x, _ln, _fn);
>     coerce_tmp = ret_tmp2;
>     _formal_tmp_err = coerce_tmp;
>     call_tmp62 = chpl_fix_thrown_error(&_formal_tmp_err, _ln, _fn);
>     *(error_out) = call_tmp62;
>     i_x2 = &str;
>     deinit51(i_x2, _ln, _fn);
```

I doubt there is much to be done here, so I'm going to close -- @mppf let me know if you think otherwise.

**Comment by benharsh** [comment]
Inlining the _cast functions for _owned can help reduce this impact by a tiny bit (few hundred less statements emitted), but that's probably insufficient. I suspect what we really need to do is focus on the resolution and generation of _owned in general.
