### ISSUE TITLE
fatal error: 'jemalloc/jemalloc.h' file not found

### ISSUE THREAD

**Issue by bonachea** [chapel-lang/chapel#12151]
### Summary of Problem

Our CI builds of Chapel master started failing on all platforms around Jan 21st, somewhere between 343bd44  (which worked) and d2eb05f  (which fails). The error message:

```
In file included from /scratch/upcnightly/EX-dirac-ibv-clang/runtime/bld/opt/chapel/third-party/qthread/qthread-src/src/alloc/chapel.c:18:
In file included from /scratch/upcnightly/EX-dirac-ibv-clang/runtime/bld/opt/chapel/runtime//include/chpl-mem.h:58:
/scratch/upcnightly/EX-dirac-ibv-clang/runtime/bld/opt/chapel/runtime//include/mem/jemalloc/chpl-mem-impl.h:26:10: fatal error: 'jemalloc/jemalloc.h' file not found
#include "jemalloc/jemalloc.h"
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
compilation terminated.
gmake[8]: *** [alloc/chapel.lo] Error 1
```
As far as we know there have been no changes in our scripting to explain this failure.

### Build logs of the failure:

* Linux x86_64 / ibv : [Config info](https://upc-bugs.lbl.gov/upc_tests/config.php?date=2019-01-24&config=EX-dirac-ibv-clang-opt) , [Build log](https://upc-bugs.lbl.gov/upc_tests/showlog.php?date=2019-01-24&config=EX-dirac-ibv-clang&opt=opt&log=chapel)

* macOS Mojave : [Config Info](https://upc-bugs.lbl.gov/upc_tests/config.php?date=2019-01-24&config=EX-mojave-smp-clang-pthr-opt) , [Build log](https://upc-bugs.lbl.gov/upc_tests/showlog.php?date=2019-01-24&config=EX-mojave-smp-clang-pthr&opt=opt&log=chapel)

* WSL x86_64 : [Config Info](https://upc-bugs.lbl.gov/upc_tests/config.php?date=2019-01-24&config=EX-wsl_ubuntu-smp-gcc-pshm-opt) , [Build log](https://upc-bugs.lbl.gov/upc_tests/showlog.php?date=2019-01-24&config=EX-wsl_ubuntu-smp-gcc-pshm&opt=opt&log=chapel)

* ppc64le Linux : [Config Info](https://upc-bugs.lbl.gov/upc_tests/config.php?date=2019-01-24&config=EX-ppc64el-smp-gcc-pshm-opt) , [Build log](https://upc-bugs.lbl.gov/upc_tests/showlog.php?date=2019-01-24&config=EX-ppc64el-smp-gcc-pshm&opt=opt&log=chapel)

Any help tracking this down would be appreciated.

CC: @PHHargrove

**Comment by ronawho** [comment]
@bonachea and @PHHargrove this should be resolved by the just merged https://github.com/chapel-lang/chapel/pull/12163. 

Thanks for reporting, and let me know if you're still running into issues.

**Comment by bonachea** [comment]
Confirmed - thanks for the fix @ronawho !
