### ISSUE TITLE
Explore moving the eltType field into BaseArr

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#12166]
Every subclass of BaseArr adds this field, except BaseArrOverRectangularDom (whose child class adds it).  This adds potential for code drift and a maintenance burden, potentially.  It also meant that the initial cleanup function called for chpl_opaque_array would leak for arrays of arrays.  In discussions with Brad, it seemed desirable to place eltType as a field on BaseArr if we could.  There's a comment on BaseArrOverRectangularDom which seems to indicate it was an intentional design consideration:

> BaseArrOverRectangularDom has this signature so that dsiReallocate
> can be overridden with the right tuple size.
> 
> Note that eltType is not included here. eltType could be included
> in a base class, but here we're looking for a way to narrow
> overloaded functions to only those working with a particular
> kind of bounding box. So if eltType is included, we should make
> another base class.

This issue is to explore what happens if eltType gets moved to BaseArr.  If doing so results in more than a couple of days of work, then the alternative solution for the opaque array clean up is to define an overloaded method to accomplish it.  That will continue the maintenance burden referred to above, so it is less preferable if we can accomplish this task without an unreasonable amount of effort

Connected to #12153

**Comment by ben-albrecht** [comment]
Doing this for other param/type fields as well could potentially be a solution to https://github.com/chapel-lang/chapel/issues/8543.

**Comment by lydia-duncan** [comment]
I opened #12175 for more general array clean up.  I'll add your comment there :)

**Comment by lydia-duncan** [comment]
Defining `eltType` on `BaseArr` immediately causes problems for `BaseDom`'s `_arrs` field, which is a list of `BaseArr`s.  The field is declared with just a type.  In order for the same domain to be used for different element types, this field needs to be defined lower in the hierarchy (for reasons that are described generally in #11999)

**Comment by lydia-duncan** [comment]
This might argue for a separate type in between `BaseArr` and the 9 types that inherit from it, but that seems like a larger discussion

**Comment by lydia-duncan** [comment]
Resolved by #12243
