### ISSUE TITLE
EP size D slight multilocale perf regression

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#12173]
#12131 seems to cause a 3% slow-down of the EP size D benchmark (ep-D.dat) in 16-locale testing on jupiter. This issue is to fix this slowdown.

**Comment by bradcray** [comment]
To my eyes, this appears to be back to normalish today, so may have been a red herring.

**Comment by ronawho** [comment]
I don't see it being back to normal, I still see the small regression -- https://chapel-lang.org/perf/16-node-xc/?startdate=2019/01/02&enddate=2019/01/30&suite=nasparallelbenchmarksperf

![image](https://user-images.githubusercontent.com/1588337/51954427-00ddb400-23f5-11e9-9700-e2b27cc0ab71.png)

**Comment by bradcray** [comment]
Oh shoot, you're right.  I made the classic mistake of having a stopdate other than 'today' in the URL and having a tab open to the graph a few days before the merge went in (so I was looking at the previous dip).

**Comment by ronawho** [comment]
@vasslitvinov is this on your radar for the release?

**Comment by vasslitvinov** [comment]
Not at the moment. Should it be?

**Comment by ronawho** [comment]
IMO yes since it's a regressions since last release, but I'm not in charge of prioritization.

It's not a very important benchmark for us currently, but during the perf meeting we were speculating that it could be from doing reductions over tuples, which is an idiom we care about.

**Comment by bradcray** [comment]
I'm more worried about the memory leaks than this (so the sprint prioritization seems appropriate), but it'd be nice to have some understanding of what changed here and whether there's an opportunity to fix it.

**Comment by vasslitvinov** [comment]
If somebody helps me narrow where in the generated code the problem occurs, I can see what in the compiler caused that.

**Comment by bradcray** [comment]
Nobody's done that investigation (or is planning to at present).  There are only two major operations in the timed code, both of which are reductions over tuples.  Given that the changes involved were to reductions, if I were running with this issue, I'd create a test that computed a + reduction over tuples, time it before and after the change and see if that'd reproduce it.

**Comment by vasslitvinov** [comment]
I am still unable to reproduce the performance difference, either in the cray-xc-16-node or chapcs --local configurations. For the latter, the "after" version is 1-2% faster than the "before" version in my runs. Even though we observe the same 3% slowdown in the nightly testing for both configurations.

However, looking at the generated code, I suspect that the culprit is the un-inlined call to `accumulateOntoState()` in the "after" version. Given that it looks quite scary, despite simply adding two tuples of reals, gcc may well not inline it, missing optimization opportunities. Whereas the "before" version performs the tuple addition in-line, as a `+=` operator in Chapel. While all the scary stuff is still present, it is local and so is plausibly optimizable.

The introduction of `accumulateOntoState()` in the "after" version is due to eliminating the specal-casing for standard reductions in the "before" version. Whereby the compiler used to go like this: "is this a sum reduction? great, let's insert +=".

For the record, here is the generated code for the "before" version:
```c
  for (i_chpl = (&this_chpl7)->_low; ((i_chpl <= end_chpl)); i_chpl += INT64(1)) {
    gaussPairsBatch_chpl(i_chpl, INT64(65536), &ret_tmp_chpl15);
    memcpy(&tmp_chpl24, &((&ret_tmp_chpl15)->x1), sizeof(_tuple_10_star__real64));
    memcpy(&call_tmp_x1_chpl, &tmp_chpl24, sizeof(_tuple_10_star__real64));
    call_tmp_x2_chpl = (&ret_tmp_chpl15)->x2;
    call_tmp_x3_chpl = (&ret_tmp_chpl15)->x3;
    read_x1_chpl = &((_yieldedIndex_x2_chpl)->x1);
    coerce_tmp_chpl11 = (_yieldedIndex_x2_chpl)->x2;
    coerce_tmp_chpl12 = (_yieldedIndex_x2_chpl)->x3;
    *(tup_chpl + INT64(0)) = 0.0;
    // ditto 1..9
    memcpy(&result_chpl, &tup_chpl, sizeof(_tuple_10_star__real64));
    *(result_chpl + INT64(0)) = ((_real64)((*(*(read_x1_chpl) + INT64(0)) + *(call_tmp_x1_chpl + INT64(0)))));
    // ditto 1..9
    call_tmp_chpl90 = (coerce_tmp_chpl11 + call_tmp_x2_chpl);
    call_tmp_chpl91 = (coerce_tmp_chpl12 + call_tmp_x3_chpl);
    memcpy(&call_tmp_x1_chpl2, &result_chpl, sizeof(_tuple_10_star__real64));
    read_x1_chpl2 = &call_tmp_x1_chpl2;
    call_tmp_chpl92 = &((_yieldedIndex_x2_chpl)->x1);
    memcpy(call_tmp_chpl92, read_x1_chpl2, sizeof(_tuple_10_star__real64));
    (_yieldedIndex_x2_chpl)->x2 = call_tmp_chpl90;
    (_yieldedIndex_x2_chpl)->x3 = call_tmp_chpl91;
  }
```

vs. the "after" version:
```c
  for (i_chpl = (&this_chpl7)->_low; ((i_chpl <= end_chpl)); i_chpl += INT64(1)) {
    gaussPairsBatch_chpl(i_chpl, INT64(65536), &ret_tmp_chpl12);
    call_tmp_chpl94 = ret_tmp_chpl12;
    _yieldedIndex_chpl = call_tmp_chpl94;
    memcpy(&tmp_chpl23, &((&_yieldedIndex_chpl)->x1), sizeof(_tuple_10_star__real64));
    memcpy(&chpl_redIdx_x1, &tmp_chpl23, sizeof(_tuple_10_star__real64));
    chpl_redIdx_x2 = (&_yieldedIndex_chpl)->x2;
    chpl_redIdx_x3 = (&_yieldedIndex_chpl)->x3;
    coerce_tmp_chpl11 = &AS_chpl_redSVar_chpl;
    read_x1_chpl = &chpl_redIdx_x1;
    (&coerce_tmp_chpl12)->x1 = read_x1_chpl;
    (&coerce_tmp_chpl12)->x2 = chpl_redIdx_x2;
    (&coerce_tmp_chpl12)->x3 = chpl_redIdx_x3;
    accumulateOntoState2(RP_chpl_redSVar_chpl2, coerce_tmp_chpl11, &coerce_tmp_chpl12);
  }

// where...
static void accumulateOntoState2(SumReduceScanOp__tuple_3__tuple_10_star__real64__real64__real64 this18,
                                 _tuple_3__tuple_10_star__real64__real64__real64 * state,
                                 _tuple_3__ref__tuple_10_star__real64__real64__real64 * x) {
  _tuple_10_star__real64 call_tmp_x1;
  _ref__tuple_10_star__real64 read_x1 = NULL;
  _real64 coerce_tmp;
  _real64 coerce_tmp2;
  _ref__tuple_10_star__real64 call_tmp59 = NULL;
  _tuple_10_star__real64 result;
  _tuple_10_star__real64 tup;
  _real64 call_tmp60;
  _real64 call_tmp61;
  _ref__tuple_10_star__real64 read_x12 = NULL;
  _ref__tuple_10_star__real64 call_tmp62 = NULL;
  read_x1 = &((state)->x1);
  coerce_tmp = (state)->x2;
  coerce_tmp2 = (state)->x3;
  call_tmp59 = (x)->x1;
  *(tup + INT64(0)) = 0.0;
  // ditto 1..9
  memcpy(&result, &tup, sizeof(_tuple_10_star__real64));
  *(result + INT64(0)) = ((_real64)((*(*(read_x1) + INT64(0)) + *(*(call_tmp59) + INT64(0)))));
  // ditto 1..9
  call_tmp60 = (coerce_tmp + (x)->x2);
  call_tmp61 = (coerce_tmp2 + (x)->x3);
  memcpy(&call_tmp_x1, &result, sizeof(_tuple_10_star__real64));
  read_x12 = &call_tmp_x1;
  call_tmp62 = &((state)->x1);
  memcpy(call_tmp62, read_x12, sizeof(_tuple_10_star__real64));
  (state)->x2 = call_tmp60;
  (state)->x3 = call_tmp61;
  return;
}
```

**Comment by vasslitvinov** [comment]
I would like to try #12691 to see if we get performance back.

**Comment by vasslitvinov** [comment]
> I would like to try #12691 to see if we get performance back.

Indeed we are observing performance increase from that.

Consider this issue resolved?

**Comment by ronawho** [comment]
Agreed, the performance regressions has been resolved.
