### ISSUE TITLE
Introduce 'vector' type as a package

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#12189]
This issue tracks the progress of introducing a 'vector' type as a bundled package module. This vector type must:
- have the same vector op methods as _array
- support 'this' and 'these'
- implement writeThis

**Comment by bradcray** [comment]
> have the same vector op methods as _array

Though we might consider changing / improving their naming if desired.  I think the current names were taken from C++, but if Python or other languages suggest better names, I think we should be open to taking them.  Some of us have also been hoping the underscores would go away.

**Comment by bradcray** [comment]
I hadn't noticed before that this issue involved adding a new parallel safe implementation.  In thinking about the design for that, I wonder if there ought to be a way to opt out of the parallel safety to improve performance (rather than requiring users to fall back to a different type).
