### ISSUE TITLE
Spike: Investigate better ways to locate gcc include files

### ISSUE THREAD

**Issue by dmk42** [chapel-lang/chapel#12198]
It is common for `/usr/local/bin/gcc` to be a symbolic link to `gcc-<version_number>` in a different directory.  Also, `gcc` may be a symbolic link to `ccache`.  In these cases, our LLVM machinery's `find-gcc-prefix.sh` fails to find the header files for use with our compiled clang.

Investigate better ways to locate the gcc header files.

**Comment by mppf** [comment]
Does `gcc -###` help at all?

**Comment by dmk42** [comment]
That does help some, if we don't go back too far in gcc versions.  The path it gives for `COLLECT_LTO_WRAPPER` sometimes works by itself, and sometimes works by substituting `lib` for `libexec` in the path.  That works at least as far back as gcc 4.7 but not as far back as gcc 4.3.

**Comment by mppf** [comment]
What about `touch test.c; gcc -### test.c` ? That shows some more interesting options, like the path to cc1 and collect2, lots of -L flags, COMPILER_PATH. Seems like something here could work.

**Comment by dmk42** [comment]
We could get the same thing with less extraneous output with `gcc --print-prog-name=cc1`.  That's what I found before, but back then I didn't realize that I could just substitute `lib` for `libexec` when it didn't quite give the right location.

None of this works on a Mac with Homebrew-installed gcc, which has a really strange path to the include files, but we don't need to find the gcc includes on a Mac.

**Comment by mppf** [comment]
I'd bet there's a way to ask the preprocessor for the paths to some particular header file. Would that help even in the homebrew case?

**Comment by dmk42** [comment]
If you create the following file `stddef.c`
```c
#include <stddef.h>
```
you can say `gcc -M stddef.c` and it will show the path to `stddef.h` as a make dependency.  The catch is that the output can get complicated, especially on Linux.

**Comment by dmk42** [comment]
```sh
gcc -M stddef.c | xargs -n 1 echo | fgrep /stddef.h | sed -e 's,/stddef.h$,,'
```
