### ISSUE TITLE
No compile time diagnostic emitted when a writer channel is reused as reader channel

### ISSUE THREAD

**Issue by tmacd8** [chapel-lang/chapel#12249]
### Summary of Problem

The following program goes into an infinite loop when a writer channel is reused as a reader channel.  No EEOF is detected with the 'chn <~> s` loop.  Perhaps a compile time diagnostic is needed?

### Steps to Reproduce

**Source Code:**

```chapel
var fl: file = open("/tmp/test-file.txt", iomode.cwr);
var chn: channel = fl.writer();
chn <~> "Line";
chn.flush(); chn.close();

var s: string;
var j = 0;
fl = open("/tmp/test-file.txt", iomode.rw);
chn = fl.reader(start=0);
while (chn.error() != EEOF) { chn <~> s; writeln(s, j); j += 1; }
chn.close(); fl.close();
```

**Compile command:**

chpl x.chpl

**Execution command:**

./x

### Configuration Information

- Output of `chpl --version`:

chpl version 1.18.0

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: intrinsics
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none

gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

**Comment by lydia-duncan** [comment]
Now that fileReader and fileWriter are distinct and separate types, I don't think this is possible any more.  Closing
