### ISSUE TITLE
make a Chapel package in Spack

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#12252]
This relates to #10367.

Since mason uses Spack, we'd like to get used to working with Spack in our project and streamline the experience for people who do install Spack. So, we'd like to have a Spack package for the Chapel compiler (and related libraries).

Hopefully this process would include creating a binary Spack package and support building from source for other non-default configurations.

**Comment by mppf** [comment]
See also https://github.com/spack/spack/pull/11002 in which @navdeeprana has added a basic Spack package for Chapel. Thanks @navdeeprana!

**Comment by ben-albrecht** [comment]
@LouisJenkinsCS recently pointed out that the externally contributed spack package (spack/spack#11002) has some issues:

> Spack package for chapel executable segfaults even for a simple program or when trying to do --about

**Comment by mppf** [comment]
We have a working Spack package now after the Spack PR https://github.com/spack/spack/pull/42197 is merged. Thanks @arezaii !
