### ISSUE TITLE
add memory_order argument to chpl_comm_atomic functions 

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#12250]
The comm interface for atomic functions (and fences) should include a memory_order argument:

 * It may matter in the future
 * It matters immediately for the optimization being worked on in #12150 since otherwise the memory order information is lost by later in compilation

**Comment by ronawho** [comment]
i.e. 

```c
chpl_comm_atomic_add_int64(void* op, c_nodeid_t locale, void* object)
``` 

should be:

```c
chpl_comm_atomic_add_int64(void* op, c_nodeid_t locale, void* object, memory_order order)
``` 

and we should add support for an equivalent of `chpl_atomic_thread_fence()`
