### ISSUE TITLE
Are array slices snapshots or ongoing definitions?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#12289]
This issue asks whether slices should be interpreted as an instantaneous snapshot of a sub-array expression or an array expression that specifies an ongoing relationship with respect to its domain and array.  I don't believe that this question comes up in the common case, yet is important to have an answer for it in the general case.

Consider the following code:

```chapel
var D = {1..n};   // declare a domain and array
var A: [D] real;

var Inner = {2..n-1};
ref AS = A[Inner];  // capture a reference to A sliced by Inner

Inner = {3..n-2};   // modify inner
writeln(AS);      // refer to the slice
```

Should the code above print `A[2..n-1]` (the definition of the slice at the time the reference to it was created) or `A[3..n-2]` (the definition of the slice based on the revised definition of `Inner`)?  The argument in favor of the former is that it is sufficiently intuitive that it's likely what most new Chapel programmers would expect (though, again, I think it's most likely that they may never write code that runs into this situation).  The argument in favor of the latter is that slices are array expressions, all array expressions in Chapel have a domain and an ongoing relationship with that domain, and `Inner` is a natural domain for the slice's virtual array.  One other argument in favor of it is that the first interpretation requires making a copy of `Inner` in the event that it's not constant and such copies can be expensive in the event that `Inner` is a distributed domain.

Here's a second, and slightly more esoteric, example using the same declarations as above:

```chapel
ref AS2 = A[4..];  // capture a reference to a slice of A
D = {1..2*n};       // resize A

writeln(AS2);   // refer to the slice
```

Should this second example print out `A[4..n]` or `A[4..2*n]`?

Note that this decision can arguably be made independently of the previous one because it comes down to whether the anonymous domain that we create for the unbounded range `4..` in the slice expression is (a) `{4..}` (a domain with an unbounded range as proposed in issue #10595) or (b) `{4..n}` (we take the intersection with the array's domain at the time of the slice's creation to create a bounded domain at that point in time).  And since the anonymous domain can't be re-assigned, the original question doesn't come into play.  That said, the two questions share a thematic similarity.

**Comment by mppf** [comment]
In thinking about this, I keep changing my mind, so the only thing I know is that I don't have a strong and solid opinion. It seems to me to be something that is a corner case in the language enough that we should decide it based upon other principles the language tries to follow.

This leads me towards having a slight preference for the second answer in both examples, since I can point to the consistency argument (that @bradcray already pointed out) for the array-domain relationship. *However* if this were to cause serious performance challenges, I wouldn't hesitate to make the other choice. At the very least one might imagine `const` domain support would solve any such problem and that the compiler could infer when a domain is never actually modified.

And, besides that, I've never really liked the array-domain relationship, since it modifies arrays without making that connection obvious at the time the domain is modified....

Can we think of a more plausible application / benchmark scenario for these examples? Could they come up in a stencil context or something?

I think either way, a user could have either behavior:
 * If modifying the slice domain / array domain modifies the slice, they can not do that, declare copies of domains, and/or make domains const
 * If they wish to have a slice over an updated domain, they can re-create the slice at that time (to get a new, current snapshot)

Each of these alternative paths might be awkward in a real application setting though, which makes me wonder if we can find an application that wants slices over arrays with changing domains.

**Comment by bradcray** [comment]
I had some thoughts on this while tossing and turning overnight that I'm going to add here before reading Michael's comment above so that they aren't (yet) persuaded by whatever he's written.

The first is that I was thinking about sparse slicing of dense arrays yesterday and realizing that that's a case where the overhead of creating a snapshot of the domain isn't O(rank) or O(rank * numlocales) as in the dense domain case, but O(nnz) (or O(nnz + numlocales)), which seems unfortunate if the copy doesn't actually need to be made (that said, if we could prove the domain was constant, we'd of course not need to make the copy).  It also seems like sparse domains are a case where it might be powerful to have such a reference reflect an ongoing relationship since it would provide a convenient way to talk about "all the people that are adults" for example without having to re-establish the slice anytime someone turned 18 or 21.  So it seems powerful in that regard to talk about an ongoing subset relationship.

My second thought was that if we adopt the approach of "always snapshotting the domain", it doesn't really give the programmer any way to conveniently set up an ongoing relationship between the slice and its domain, forcing them to re-establish a new slice each time they need it.  Whereas if we say that slices are governed by their domains like any other array is, but someone wants the snapshot behavior, they can always create a copy of the domain and take the slice with that.

These have both made me lean toward "maybe it should be an ongoing relationship" and also "in which case we should literally use the domain that's passed in rather than converting it to the array's distribution" (where it seems like it would be friendly to warn about cases that do something silly like slice a block array with a default rectangular domain that spans all of the locales rather than the block-distributed equivalent of the same).

This seems a little bit dicey, but only a little bit since (a) I expect that people will slice more often with ranges than with domains (and expect that we'll continue to make appropriate domains from their ranges and that these domains will be constant so the ongoing relationship property won't matter), (b) even when people slice with domains, I expect that they won't often be modifying the domains (since most programs don't modify most domains much anyway) in which case they'll be none the wiser and happy that we're not spending time copying their domain.

With respect to the unbounded range slice case in the original issue, I think that when (if?) we support domains with unbounded ranges we should have them store the unbounded ranges.  Until then our only real option is to create a bounded domain at the time the slice is taken.  I also don't think this change is likely to affect people much since it will only occur when the original array is resized (which, again, doesn't actually happen that often I think).

OK, now I'll go back and read Michael's comment once I've woken up a bit more.

**Comment by bradcray** [comment]
I set this down for awhile while working on the release, but have come back to it this past week as a study break.  My takeaway from the last round of conversations was that for many programs the decision wouldn't really matter, but that both Michael and I were leaning more toward having a slice expression take the slicing domain as its domain for consistency with other slices, and to avoid overheads associated with creating a snapshot of the domain for the slice.  Talking to some folks offline, I got a similar sense that this seemed like the right way to go.

Michael asked this rhetorical question which I forgot to answer:

> which makes me wonder if we can find an application that wants slices over arrays with changing domains.

I don't know if I'd call it an application, but I think a pattern where this might come up would be if you had an array (rectangular or associative) and a sparse subdomain on that array whose membership changed over time (maybe it reflects a changing set of points of interest in a physical simulation? 
 maybe it reflects the senior citizens in a population that was aging over time?).  Since the sparse subdomain is changing over time, a single slice expression `ref ArrSubset = Arr[SparseSubset];` could be created that would represent the set of points in question over time even as `SparseSubset` changed.

Meanwhile, I implemented a branch [`slices-use-domain`](https://github.com/bradcray/chapel/tree/slices-use-domain)  branch that implements these semantics and only one failure turned up in local testing and three additional ones in GASNet testing.  All four were cases in which a non-distributed domain was used to slice a distributed array which exposed that on master, we create a new copy of the slicing domain using the array's distribution (so the slicing domain ends up being a new, distributed one), whereas on the branch the slicing domain is the original default rectangular one, so isn't distributed (which can show up when iterating over it in parallel, say... the iterations are no longer spread over the target locales).  The fix of course is pretty simple:  slice with a distributed domain.

This case does point out one of the ones I'm most worried about in this approach, though:  At present, when slicing a rectangular domain with a bunch of ranges, there is no "slicing domain" so we create a new one by slicing the array's domain by the ranges, and this turns out to be distributed.  But the result of this is that `A[1..n, 1..n]` has a different effect than `A[{1..n, 1..n}]`.  Namely, if A is distributed, the former results in a distributed slicing domain while the latter results in a local slicing domain.  Of course, people rarely use the curly brackets in this case, but the same is true if they had named the domain previously (i.e., `D = {1..n, 1..n};  ...A[D]...` vs. `...A[1..n, 1..n]...`).  It seems subtle to have default rectangular domains behave one way and collections of ranges behave another, but which should be made to behave more like the other?

This last paragraph also relates to the tension between efficiently implementing a "big slice" like `A[2..n-1, 2..n-1]` and a small (perhaps intentionally localized) one like `A[lo..lo+2, k..k+myBlockSIze]`.  For the former, you might be willing to communicate with all locales to have them establish a privatized version of the distributed `{2..n-1, 2..n-1}` domain that we create today, but for the latter, this seems like overkill.  This makes me wonder whether slicing by both local domains or ranges ought to create the distributed version of the domain lazily rather than aggressively, as in the range case today.  If so, they could both be implemented in a similar manner yet without paying more than is necessary at the time of slicing.  This idea relates to issue #11840.

In any case, while I continue to worry about the efficient implementation of slicing by local domains or ranges, nothing that I've seen has made me think that having slice expressions use the domains that established them to define themselves is a bad idea.  And maybe more importantly, doing so permits such cases to be more efficient than they are today as an already-distributed domain will not generate additional communication as it does at present (due to making a copy of it as the snapshot).

**Comment by benharsh** [comment]
> ... whereas on the branch the slicing domain is the original default rectangular one, so isn't distributed (which can show up when iterating over it in parallel, say... the iterations are no longer spread over the target locales). The fix of course is pretty simple: slice with a distributed domain.

I think this iteration part bothers me most. Could we have some optional part of the DSI that allows us to pass the dimensions over which to iterate?

```chpl
forall i in downDom.these(dims=upDom.dims()) do ...
```

Or would that be problematic if only some domain maps supported this functionality, and others did not? Would it be easier to just tell users to always manually slice a distributed domain?

**Comment by bradcray** [comment]
I'd also wondered about whether the dsi should be extended in this way (e.g., an optional argument to `these()`?) and how much work it would be to plumb this through all of the domain maps.

I think the reason that I don't find this completely terrifying is that it would only occur when someone sliced with a non-distributed domain, which I don't think happens all that often (e.g., I'd either have to do `A[{2..n-1, 2..n-1}]` or name a local domain and slice with it.  I think the more common cases would be to use a named distributed domain or a list of ranges (where my current thinking is to have the domain created from the ranges adopt the slice's distribution).  But just because something is atypical doesn't mean it isn't worth putting in more effort to have it be less surprising which is why I'd wondered about changing the dsi interface in this way.

What do you mean by "manually slice"?

**Comment by benharsh** [comment]
Sorry, manually isn't really the right word. I intended to refer to the extra step of doing ``A.domain[expr]``.
