### ISSUE TITLE
Error when using `openwriter()` or `open().writer()` from within a module

### ISSUE THREAD

**Issue by ty1027** [chapel-lang/chapel#12297]
### Summary of Problem
In the following code, I am trying to write data from within a module,
but the compilation fails with the message:

```chapel
test.chpl:5: In function 'main':
test.chpl:7: error: call to throwing function openwriter_default_hints without throws, try, or try! (relaxed mode)
$CHPL_HOME/modules/standard/IO.chpl:2568: note: throwing function openwriter_default_hints defined here
test.chpl:7: error: call to throwing function openwriter_default_url without throws, try, or try! (relaxed mode)
$CHPL_HOME/modules/standard/IO.chpl:2569: note: throwing function openwriter_default_url defined here
test.chpl:7: error: call to throwing function openwriter without throws, try, or try! (relaxed mode)
$CHPL_HOME/modules/standard/IO.chpl:2567: note: throwing function openwriter defined here
test.chpl:10: error: call to throwing function writeln without throws, try, or try! (relaxed mode)
$CHPL_HOME/modules/standard/IO.chpl:4215: note: throwing function writeln defined here
test.chpl:11: error: call to throwing function close without throws, try, or try! (relaxed mode)
$CHPL_HOME/modules/standard/IO.chpl:4318: note: throwing function close defined here
```

Using `open().writer()` instead also gives a similar error:
`error: call to throwing function open_default_hints without throws, try, or try! (relaxed mode)...`

If I remove the module declaration (by commenting out the lines with "<--"), then
the code works as expected.

Although I used OSX10.11, the same error seems to occur also on [TIO](https://tio.run/##hY8xDoMwDEV3n@KLiUhVgHZEPUwUjBopkCikZUCcPQSoKrb@ycP7z7Z@Kc82pcF1b8uIPMU8YiHywWkMyoyloIWQ81EBPZ5wnsc5mMihRLE3ZKdiAdEeVFVduStxg3FZzlLPEPJrEC3@hA5tfxbsbmzqGo28P347e6mtmzjLaCVa8w04H0ppAw).

Am I doing something wrong in the code...?

### Steps to Reproduce

**Source Code:**

```chapel
module testmod {  // <--

proc main()
{
    var f = openwriter( "test.dat" );
    // var f = open( "test.dat", iomode.cw ).writer();

    f.writeln( "100 1.23" );
    f.close();
}

} // module  <--
```

**Compile command:**
`chpl test.chpl`

**Execution command:**
`./test`

### Configuration Information

- `chpl --version`:
chpl version 1.18.0
Copyright (c) 2004-2018, Cray Inc.  (See LICENSE file for more details)

- `$CHPL_HOME/libexec/util/printchplenv --anonymize`:
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: clang
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: intrinsics
CHPL_GMP: none
CHPL_HWLOC: hwloc
CHPL_REGEXP: none
CHPL_AUX_FILESYS: none

- `clang --version`
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0

**Comment by mppf** [comment]
Hi @ty1027 - this is working as intended, see https://chapel-lang.org/docs/master/technotes/errorHandling.html#fatal-mode-for-implicit-and-prototype-modules

The rationale for having looser error handling outside of a `module` is that `module`s are more likely to be used in library code, where halting on an error is more problematic. You can use `prototype module` at present to tell the compiler not to worry about halting on the error. Otherwise, you need to adjust your code to handle the potential for an error. You should be able to do that by marking `main` with `throws` or using a `try!` block around the body of it.

For example:
``` chapel
module testmod {
  proc main() throws
  {
    var f = openwriter( "test.dat" );
    f.writeln( "100 1.23" );
    f.close();
  }
}
```

If I first `mkdir test.dat` and then run this program, it prints out an error abut test.dat being a directory (as expected).

**Comment by cassella** [comment]
It sounds like this issue can be closed?
