### ISSUE TITLE
Internal Compiler Error With Queried Domain

### ISSUE THREAD

**Issue by tmacd8** [chapel-lang/chapel#12299]
### Summary of Problem
Internal Compile Error with the code below.

### Steps to Reproduce

**Source Code:**
```chapel
module M {
 config const r: int = 8;
 config const c: int = 9;

 var nbr: int = r;
 var nbc: int = c;
 var ndr: int = r+1;
 var ndc: int = c+1;

 class gs {

   var bd: [0..nbr-1, 0..nbc-1] uint(8);
   var sf: [ 0 .. 3 * ndr * ndc - 1, 0 .. 1 ] uint(8);

   proc init() {
     bd = 0;
   }
 };

 proc gs.c_l(
   ref ar: [?D, 0 .. 1] uint(8)) {   // <- source of the error

   return ar[0];
 }

 proc gs.ic() {
   c_l(sf);
 }

 proc main() {
   var b = new owned gs();
   b.ic();
 }
}
```

**Compile command:**
`chpl foo.chpl`
foo.chpl:21: internal error: CAL0078 chpl version 1.18.0
Note: This source location is a guess.

### Configuration Information

- Output of `chpl --version`:
chpl version 1.18.0

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: intrinsics
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none

- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

**Comment by lydia-duncan** [comment]
Hi Tom.  We think this should just be a user error because we don't support querying part of a domain.  Would you want that to be supported in the future?  We probably won't be able to do that as quickly (so would make it a user error for now and open a separate issue for supporting partial queries) but it seems worth considering if that would be something you'd like to see.

**Comment by bradcray** [comment]
Thanks for filing this Tom.  Adding to Lydia's comment, I think that ultimately, we'd like to do a bunch more of this query-style pattern matching than we do today (so in this case, I'd think of `D` as being bound to a range), but at present we only support a few cases like querying the whole domain or element type of an array.

Also I'm realizing nobody has said, but a workaround for this issue (if you haven't found one or others stumble across this issue) would be to query the domain and its first dimension explicitly from within the routine:

```chapel
 proc gs.c_l(ref ar: [] uint(8)) {   // <- source of the error
  const D = ar.domain.dim(1);

   return ar[0];
 }
```

(at which point you'll run into the next issue which is that `ar` is 2-dimensional so needs a 2D index).

**Comment by tmacd8** [comment]
I've already worked around it.  I should have been clearer in the original post that all that needs to be fixed (IMHO) is the Internal Compiler Error.  I was just "playing around" and bumped into the ICE.  I'm not suggesting a a language enhancement here.  When I dug into the grammar It became clearer that this wasn't supported.  I'm fine with that and I am using the suggested workaround - thanks.
