### ISSUE TITLE
init proposal: this conveys known type

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#12318]
Prev: #12317 Next:  none

This proposal is based on some ideas by Brad (the main difference being that this proposal/discussion does not create type initializers separately from initializers - instead the compiler just handles such issues directly).

In this proposal, `this.type` can be queried to access known type components. Type aliases for types with default fields are still generic (lazily evaluated). `rec.type.x` works on a typeless field.

One way to view some of this proposal is to have conditional default arguments. If we wanted these to be a generalized feature, it might look like this:
``` chapel
proc f( x, y = if x.type==int then x ) { }
```

The idea is that the conditional operates on compile-time known information available at the call site.
``` chapel
f( 4 ); // ok, y defaults to x for x.type==int
f( 1.0 ); // error, y has no default value for x==real
```

It is not necessary for this user-facing feature to be implemented but the below will describe some functionality in terms of it. The implementation effort could handle these matters directly for initializers.

The examples below further suppose that `if this.type.x` queries if the type component `x` of `this` is available at the call site. If so, the conditional is used, if not, it is ignored (and the default value will be ignored).

Strengths:
 * only one compiler generated initializer
 * potential for user to manually write the compiler-generated initializer or to write a single user initializer with similar capability

Weaknesses:
 * changes more of the language with the conditional defaults pattern
 * increases resolution work per-call (for initializers)
 * some new expressions on type aliases require passing arguments by name
 * user-written initializers are more complicated for generic types if `new` on an instantiated type is to work

Note that this issue can combine pleasantly with the pass-type-alias-arguments-as-named-arguments-to-initializers strategy that is already implemented, since the relevant arguments still exist. That combination would resolve the main weakness, at a cost of further complicating the design.

### Instantiated Type
``` chapel
record R {
  type T;
  var x : T;
}
type RI = R(int); // compiler notes that in RI, T=int
var x = new RI(5); // becomes new R(5), which won't resolve, can't pass 5 to type T
var x = new RI(x=5); // works OK, T uses default value from this.T

// compiler-generated default initializer:
// Note that the this.T argument default value is ignored if at
// the call site, T is not known
proc R.init(type T= if this.T then this.T, x:T = default(T) ) {
  this.T = T;
  // Here, note that assigning to a type/param in the initializer:
  //   * has no effect if the type/param is known already and matches what it is set to
  //   * raises an error if the type/param is known already and does not match what it is set to
  //   * sets the type being initialized if the type/param is not known already

  this.x = x;
}
```

### Instantiated Type with Two Typeless Fields
``` chapel
record R { var x,y; }
// compiler generates this initializer
// the default values are ignored if the relevant type component is unknown
proc R.init(x=if this.type.x then default(this.type.x), y= if this.type.y then default(this.type.y)) {
  // Note that this initializer takes the types of x and y
  // from the type of `this` in the event that `this` has
  // specified types for those.
  // this.x.type = if this.type.x then this.x.type else x.type
  this.x = x;
  // this.y.type = if this.type.x then this.x.type else y.type
  this.y = y;
}

var A : R(int, real); // becomes R(int,real).init() - this.type.x and this.type.y are set in arguments, defaults used
var B = new R(5, 10.0); // becomes B.init(5, 10.0), this.type.x and this.type.y are not known in the arguments, and the type is built based on the types of the arguments 5 and 10.0

type RIR = R(int, real);
var C = new RIR(5, 10.0); // becomes R(int,real).init(5, 10.0) - the default arguments for x and y are available but unused. The types are checked in the this.x = x line.

var D: RIR; // becomes R(int,real).init() - this.type.x and this.type.y are set in arguments, defaults used
```

Additionally, support the following
``` chapel
record R { var x; }
var a: R(x=int); // says that x has type `int`, not that it is `int`
a.type.x; // evaluates to `int`
```

### Default Values in Type Fields
``` chapel
record MyRange {
  type idxType = int;
  param stridable : bool = false;
}
type MR = MyRange; // MR is still a generic type
type MR_Int = MR(int); // OK
type MR_Uint = MyRange(uint); // OK

// The compiler-generated initializer for MyRange is this:
proc R.init(type idxType = if this.type.idxType then this.type.idxType else int,
            param stridable = if this.type.stridable then this.type.stridable else false) {
  this.idxType = idxType;
  this.stridable = stridable;
}

var x:MyRange; // OK, uses default type/param information; runs MyRange.init()
var x: MyRange = new MyRange(idxType=real); // OK, LHS interpreted as generic type, RHS matches, runs MyRange.init(idxType=real) and uses default param value

var a: range = 1..10 by 2; // OK
var b: range = color.blue..color.green; // OK
```

### Two Explicit Type Fields
``` chapel
record R {
  type T;
  var x : T;
  type Q; // note: not contiguously declared
  var y : Q;
}
// compiler generates this initializer
proc R.init(type T= if this.T then this.T, x:T = default(T),
            type Q= if this.Q then this.Q, y:Q = default(Q)) {
  this.T = T;
  this.x = x;
  this.Q = Q
  this.y = y;
}

var A = new R(int, 5, real, 10.0); // works, doesn't use defaults
type RI = R(T=int);
type RIR = R(T=int, Q=real);
var x = new RI(Q=real, y=5.0); // becomes R(T=int).init(Q=real, y=5.0); -- resulting in using the default value of 0 for x
var y = new RIR(5, 10.0); // does not compile, because can't pass 5 to T
var y = new RIR(x=5, y=10.0); // OK

var d: RIR; // becomes R(T=int, Q=real).init() -- resulting in using the default values for x and y
```

### Generic type default init=
``` chapel
record R {
  type T;
  var x : T;
}
// The compiler generates this default init=
// Here the this.type constraint means that any known
// components of this.type must match. Note that this.type
// might still be generic at this point.
proc R.init=(other : this.type) {
  this.T = other.T;
  this.x = other.x;
}
var a: R(int);
var b = a; // OK, compiler infers this.type = a.type before calling R.init=
var c: R(real) = a; // doesn't resolve because other.type isn't a subtype of R(real)
```

### Generic type init= changing type
``` chapel
record Wrapper {
  type T;
  var x : T;
}
proc Wrapper.init=(x: integral) {
  this.T = if this.T then this.T else x.type;
  this.x = x:this.T;
}
var x : Wrapper(int(8)) = 5; // creates a Wrapper(int(8)) storing this.x = 5:int(8)
var y: Wrapper = 10; // creates a Wrapper(int)
```

### Type Alias Mismatch Error
``` chapel
record R {
  var x;
}
// compiler generates this initializer
proc R.init(x=if this.type.x then default(this.type.x)) {
  // this.x.type = if this.type.x then this.x.type else x.type
  this.x = x;
}

type RI = R(int);
var D = new RI("value"); // R(int).init("value") 
// results in an error inside the instantiated compiler-generated initializer
// when trying to assign this.x = "value" when this.x is an int
```

### Partial instantiations
``` chapel
record R (type T; type U; type V; var t: T; var u:U; var v:V; }
type R_I = R(int); // OK
type R_IR = R_I(real); // OK
type R_IRS = R_IR(string); // OK

// compiler generates this initializer
proc R.init(type T= if this.T then this.T,
            type U= if this.U then this.U,
            type V= if this.V then this.V,
            t:T = default(T),
            u:U = default(U),
            v:V = default(V)) {
  this.T = T;
  this.U = U;
  this.V = V;
  this.t = t;
  this.u = u;
  this.v = v;
}

var x = new R_IR(V=string); // R(T=int, U=real).init(V=string)
var D: R_IRS; // R(T=int, U=real, V=string).init()

var y = new R_IR(T=real); // doesn't compile, because this.T = T line will have type mismatch, not be ignored
```

### run-time types
``` chapel
record R { type T; var x:T; }
  
var D = {1..2};
var Arr:[D] int;
var a = new R(Arr.type, Arr);
var b = a;

var OtherDom = {2..5};
var OtherArr:[OtherDom] int;
var c:R(OtherArr.type) = a;
// C.x has domain OtherDom
// Why? In the compiler-generated init= call (below),
// the assignment this.T = other.T is ignored in the
// event that this.T is already set and matches the
// compile-time type for other.T. In that event, this.T
// should already have a runtime type.
proc R.init=(other : this.type) {
  this.T = other.T;
  this.x = other.x;
}

// The compiler translates
var c:R(OtherArr.type) = a;
// into
var c:R(OtherArr.type) = noinit; // compile-time types only, no default init
c.T = OtherArr.type; // Set the appropriate runtime type field in c
c.init=(a);
```

### array init=
``` chapel
// the compiler could directly support
proc _array.init=(d : domain, type eltType, expr);
// or the compiler could add a type argument for the runtime type component
// (since it's not actually available in a field of _array before it is initialized)
proc _array.init=(type ThisType, type eltType, expr);
```

### Wrapper Pattern with User Initializers
What if the user wanted to support this default initialization pattern but provided custom initializers for the type?

They need only provide a single initializer that uses conditionals matching the compiler-generated initializer:

``` chapel
record Wrapper { var x; }
proc Wrapper.init(x=if this.type.x then default(this.type.x)) {
  this.x = x;
}
type WrapperInt = Wrapper(int);
var a: Wrapper(int); // becomes Wrapper.init(x=default(int));
var b: Wrapper(int); // becomes Wrapper.init(x=default(int));
var c = new Wrapper(5); // becomes Wrapper.init(5)
```

### Partial Instantiation and Typeless Fields
``` chapel

record R {
  var a;
  var b;
  var c;
  var d;
}


type RI = R(int);

var something = new RI(b=2,c=3,d=4); // user is expecting to produce R with a=0, b=2, c=3, d=4
// Note, user would expect new RI(1, ... ) to set a=1
```

Under this proposal, the compiler would generate this initializer:
``` chapel
// compiler generates this initializer
proc init(a=if this.type.a then default(this.type.a),
          b=if this.type.b then default(this.type.b),
          c=if this.type.c then default(this.type.c),
          d=if this.type.d then default(this.type.d)) {
  this.a = a;
  this.b = b;
  this.c = c;
  this.d = d;
}
```

What happens to the call of interest?

``` chapel
var something = new RI(b=2,c=3,d=4);
// This call is translated into R.init(b=2, c=3, d=4)
// which resolves to the call above (using the default value for a)
// and functions as expected
```

What if the user wanted to create custom initializers for R? What initializers would they need to create to support arbitrary patterns of partial instantiation? In this proposal the user can literally write the compiler generated initializer:
``` chapel
proc init(a=if this.type.a then default(this.type.a),
          b=if this.type.b then default(this.type.b),
          c=if this.type.c then default(this.type.c),
          d=if this.type.d then default(this.type.d)) {
  this.a = a;
  this.b = b;
  this.c = c;
  this.d = d;
}
```

which would support the same patterns as the compiler-generated initializer.

What if the user didn't want to use defaults for the partially instantiated types? They could leave out the `if` default values that depend on the type. They can do this on a per-argument basis.

**Comment by benharsh** [comment]
Some thoughts:

Can we use either "this.foo" or "this.type.foo" for type and param fields?

The "if this.T then this.T" stuff is kind of cumbersome. Long-term I'd like to see something like the elvis operator: "this?.T" or maybe "this.T?", where the 'else' result is something like "any" for types and "none" for params? That doesn't account for default values though...

Is it the case that if the user wants to implement an initializer for default initialization on a generic type that they have to do all of the "if this.T then this.T" stuff? Maybe postinit helps?

I'm not entirely sure what to think about the NamedExprs challenge. It would be nice if users did not have to manually use them when type aliases are involved (e.g ``new RI(x=5)``). But it does feel sort of redundant to pass information to the kinds of formals seen here (``type T = if this.T then this.T``). If we were to use NamedExprs, are these the only cases that need "this.type" ?
  - default initialization
  - typeless fields

**Comment by mppf** [comment]
> Can we use either "this.foo" or "this.type.foo" for type and param fields?

That would make sense to me

> Is it the case that if the user wants to implement an initializer for default initialization on a generic type that they have to do all of the "if this.T then this.T" stuff? Maybe postinit helps?

If they're implementing an initializer, they don't have to use this pattern. They might want to use the pattern to get their initializer on a generic type to handle things like default initialization for type alias specifying the type/param fields.

> I'm not entirely sure what to think about the NamedExprs challenge. It would be nice if users did not have to manually use them when type aliases are involved.... 

I personally would prefer that we not tie field names to initializer argument names (which the automatic NamedExprs business does do) and I'd rather have users use NamedExprs when they might at first seem not to be required, given the choice between those two.

If we chose to continue to add the automatic NamedExprs to initializer calls, I think the this.type stuff will be used for `init=` and for typeless fields. I don't think it's needed for default initialization in a case like `record R { type T; var x:T; }` (the NamedExprs would be sufficient there).

**Comment by mppf** [comment]
I think that a library author might want to limit which types are settable in their initializers, e.g.
``` chapel
record Matrix {
  type eltType;
  type derivedMatrixType; // not to be set by users
}

proc Matrix.init(type eltType) { ... }
```

However it is the case that under this proposal, if somebody wanted
``` chapel
type IntMatrix = Matrix(int);
var r: IntMatrix;
```

to work, then they'd need to provide an initializer where the `eltType` argument has the default value.

> I personally would prefer that we not tie field names to initializer argument names

I stand by that, but I wonder, if we combine this proposal with the automatic-named-arguments proposal in the right way, can we support all of these cases easily?

In particular, what if the compiler passed the automatic named arguments if it could, and fell back on the default strategy if it couldn't? That would mean it's still possible (but harder) to create initializers with different arguments than the field names (using e.g. `eltType = if this.eltType then this.eltType`) but probably in the common case that wouldn't be necessary.

**Comment by lydia-duncan** [comment]
This one also seems reasonable to me.  I had a question on the previous proposal related to this one, but it might just have been me misunderstanding something

**Comment by bradcray** [comment]
Here are some notes I jotted down while reading through this for the first time, some of which I think duplicate comments @benharsh made above:

* The following:

  ```chapel
  var x = new RI(5); // becomes new R(5), which won't resolve, can't pass 5 to type T
  ```

  was the first and main place that made me balk a little bit.  I understand the interpretation, but my 
  intuition is "I already told you T is `int`, so why are you making me explicitly skip past it when calling 
  the initializer?"

* The above also seems a little inconsistent relative to this:

  ```chapel
  record R (type T; type U; type V; var t: T; var u:U; var v:V; }
  type R_I = R(int); // OK
  type R_IR = R_I(real); // OK
  type R_IRS = R_IR(string); // OK
  ```

  which implies an automated stacking of type/param information without requiring a name to jump to the right slot.  I realize that this is in the type context and the previous was in the value context, but intuitively it seemed inconsistent to require me to name the right field in one case and not in the next (at least when both things are compiler-generated).

* Given the frequency of the `if x then x else y` pattern in cases like the following, I wonder if we should introduce something (a helper function?  syntax?) to help support these common case patterns.

  ```chapel
  proc R.init(type idxType = if this.type.idxType then this.type.idxType else int,
              param stridable = if this.type.stridable then this.type.stridable else false) {
  ```
  Seeing Ben's comment, the Elvis operator seems as though it could help...

* In the pattern above, I found myself wondering why it refers to `this.type.idxType` rather than simply `this.idxType` given that in most contexts we can simply do the latter.

* Here:

  ```chapel
  var b = a; // OK, compiler infers this.type = a.type before calling R.init=
  ```

  I wanted to note the relationship between this and some of our classic "initializing with the type changes the type" cases (which I increasingly think users will want the ability to tap into as well).

**Comment by mppf** [comment]
I generally agree with your remarks.

In this proposal, I was intentionally trying not to invent new syntax because I'd like us to agree on the initializer design part. But I agree the syntax used here is wordy and could be improved.

> * The following:
>
>  ```chapel
>  var x = new RI(5); // becomes new R(5), which won't resolve, can't pass 5 to type T
>  ```
>
>  was the first and main place that made me balk a little bit.  I understand the interpretation, but my 
>  intuition is "I already told you T is `int`, so why are you making me explicitly skip past it when calling 
>  the initializer?"

Yep. If we combine this proposal with named-arguments-for-instantiated types, *or* with the specialization described in #12317, then this example can work. Those two strategies are dual to each other.

> * Here:
>
>  ```chapel
>  var b = a; // OK, compiler infers this.type = a.type before calling R.init=
>  ```
>
> I wanted to note the relationship between this and some of our classic "initializing with the type
> changes the type" cases (which I increasingly think users will want the ability to tap into as well).

Yes, but I think we need a separate mechanism to handle the type change cases. I don't think it makes sense to try to express than in the declarations for init or init= for a type.

Ben discussed this in the gist here https://gist.github.com/benharsh/38fa7e96833b0e19c4b3b7c3a5ee2fce#file-9-user-defined-type-inference-md and of those options my current favorite is a method indicating what type the compiler should infer, e.g.

``` chapel
proc MyWrapper.inferType() type {
  return wrappedField.type;
}
```

**Comment by mppf** [comment]
We implemented towards this design. While there are still some missing features (particularly with typeless fields), I'm closing the issue since it has served its purpose and @benharsh is planning to make some more specific issues (that will perhaps link here).
