### ISSUE TITLE
init proposal: special specialization

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#12317]
Prev: #12316 Next: #12318

This one is a proposal based on the idea of partially evaluating the initializer (aka specializing it) when working with initialization of a type where some components are known.

Type aliases for types with default fields are still generic (lazily evaluated). `rec.type.x` works on a typeless field.

When specializing an initializer for a new instantiation of that type, the compiler will:
 * detect which arguments are used in *simple initialization* of a related field when:
    * the argument name is the same as the field name
    * the field is set directly by the argument, e.g. `this.x = x`.
    * Note that these patterns are not *simple initialization*, assuming a field `x`:
       * `this.x =f(x)`
       * `var tmp = x; this.x = tmp`
       * `this.x = y`
 * for arguments that are *simple initialization* of a type/param field, remove those arguments if the initialized field matches the type/param already known for a specialized type.
 * for arguments that are *simple initialization* of a typeless field e.g. `var x` that now has type `T`, give the argument a default value e.g. `x = default(T)`.
 * inside of the body of the initializer, remove initialization of type/param fields already known (but evaluating the expressions doing so for side effects).

Strengths:
 * Low language design impact
 * Feels relatively natural
 * new expressions on type aliases don't require arguments by name
 * Wrapper pattern only requires a single initializer

Weaknesses:
 * Somewhat complex rule allows the capabilities of compiler-generated initializers in custom initializers
    * Creates a loose relationship between generic field names and initializer formal argument names
    * Users may be surprised that adding to an initializer makes certain patterns no longer work
    * Users might find it unintuitive how to enable or disable this behavior
 * Probably more challenging to implement than other proposals

Also, note that this is totally incompatible with the pass-type-alias-arguments-as-named-arguments-to-initializers strategy that is already implemented, since the relevant arguments won't exist under this proposal.

### Instantiated Type
``` chapel
record R {
  type T;
  var x : T;
}

// The compiler generates this initializer for R
proc R.init(type T, x:T = default(T) ) {
  this.T = T;
  this.x = x;
}

type RI = R(int); // compiler notes that in RI, T=int

// When needed, the compiler specializes R.init to R(int).init.
// In doing so, it removes moot compiler-generated arguments and moot field initializations.
// Note here that `T` is part of the type RI.
proc R(T=int).init(x:T = default(T)) {
  this.x = x;
}

var x = new RI(5); // OK
var x = new RI(x=5); // OK
```

What about a record with a user initializer?
``` chapel
record R {
  type T;
  var x : T;
}


proc R.init(x) {
  a();
  this.T = b(x.type);
  this.x = c(x);
  d();
}
proc R.init() {
  e();
  this.T = f();
  this.x = g();
  h();
}
proc R.init(type T, x: T) {
 ...
}
type RI = R(int); // compiler notes that in RI, T=int

// How does the compiler specialize the user initializers?
// They become:
proc R(T=int).init(x) {
  a();
  b(x.type); // but result is not used because it is moot
  this.x = c(x);
  d();
}
proc R(T=int).init() {
  e();
  f(); // but result is not used because it is moot
  this.x = g();
  h();
}
// Here compiler assumes that it can remove the `type T`
// argument because it has the same name as the type field.
// If users didn't want that, they can use a different argument name.
proc R(T=int).init(/*type T, */ x: T) {
  ...
}
```

### Instantiated Type with Two Typeless Fields
``` chapel
record R { var x,y; }
// compiler generates this initializer
proc R.init(x, y) {
  this.x = x;
  this.y = y;
}

// How would the compiler specialize that to R(int, real) ?
proc R(int,real).init(x:int = 0, y:real = 0.0) {
  this.x = x;
  this.y = y;
}

var A : R(int, real); // becomes R(int,real).init()
var B = new R(5, 10.0); // OK

type RIR = R(int, real);
var C = new RIR(5, 10.0); // becomes R(int,real).init(5, 10.0) - the default arguments for x and y are available but unused. The types are checked in the this.x = x line.

var D: RIR; // becomes R(int,real).init()
```

Additionally, support the following
``` chapel
record R { var x; }
var a: R(x=int); // says that x has type `int`, not that it is `int`
a.type.x; // evaluates to `int`
```

### Default Values in Type Fields
``` chapel
record MyRange {
  type idxType = int;
  param stridable : bool = false;
}
type MR = MyRange; // MR is still a generic type
type MR_Int = MR(int); // OK
type MR_Uint = MyRange(uint); // OK

// The compiler-generated initializer for MyRange is this:
proc R.init(type idxType = int,
                   param stridable = false) {
  this.idxType = idxType;
  this.stridable = stridable;
}

var x:MyRange; // OK, uses default type/param information; runs MyRange.init()
var x: MyRange = new MyRange(idxType=real); // OK, LHS interpreted as generic type, RHS matches, runs MyRange.init(idxType=real) and uses default param value

var a: range = 1..10 by 2; // OK
var b: range = color.blue..color.green; // OK
```

### Two Explicit Type Fields
``` chapel
record R {
  type T;
  var x : T;
  type Q; // note: not contiguously declared
  var y : Q;
}
// compiler generates this initializer
proc R.init(type T, x:T = default(T),
                  type Q, y:Q = default(Q)) {
  this.T = T;
  this.x = x;
  this.Q = Q
  this.y = y;
}

var A = new R(int, 5, real, 10.0); // works, doesn't use defaults
type RI = R(T=int);

// Compiler creates this init specialization:
proc R(T=int).init(x:int = 0, type Q, y:Q = default(Q)) {
  this.x = x;
  this.Q = Q
  this.y = y;
}

type RIR = R(T=int, Q=real);

// Compiler creates this init specialization:
proc R(T=int, Q=real).init(x:int = 0, y:real = 0.0) {
  this.x = x;
  this.y = y;
}

var x = new RI(Q=real, y=5.0); // becomes R(T=int).init(Q=real, y=5.0); -- resulting in using the default value of 0 for x
var y = new RIR(5, 10.0); // OK, becomes R(T=int,Q=real).init(5, 10.0)
var y = new RIR(x=5, y=10.0); // OK

var d: RIR; // becomes R(T=int, Q=real).init() -- resulting in using the default values for x and y
```

### Generic type default init=
``` chapel
record R {
  type T;
  var x : T;
}
// compiler generates this init=
proc R.init=(other : this.type) {
  this.T = other.T;
  this.x = other.x;
}
// instantiates like this
proc R(T=int).init=(other: R(int)) {
  this.x = other.x;
}
proc R(T=real).init=(other: R(real)) {
  this.x = other.x;
}
var a: R(int);
var b = a; // Compiler runs R(int).init=(a)
var c: R(real) = a; // doesn't resolve because other.type isn't a subtype of R(real)
```

### Generic type init= changing type
``` chapel
record Wrapper {
  type T;
  var x : T;
}
// this is a user-provided initializer
proc Wrapper.init=(x: integral) {
  this.T = x.type;
  this.x = x:this.T;
}
// This is the instantiation of it for int(8)
proc Wrapper(T=int(8)).init=(x: integral) {
  this.x = x:this.T;
}
var x : Wrapper(int(8)) = 5; // creates a Wrapper(int(8)) storing this.x = 5:int(8)
var y: Wrapper = 10; // creates a Wrapper(int)
```

### Type Alias Mismatch Error
``` chapel
record R {
  var x;
}
// compiler generates this initializer
proc R.init(x) {
  this.x = x;
}

type RI = R(int);
// compiler creates this specialized initializer
proc R(x=int).init(x: int) {
  this.x = x;
}

var D = new RI("value"); // R(int).init("value") 
// results in an error because R(int).init(string) does not resolve
```

### Partial instantiations
``` chapel
record R (type T; type U; type V; var t: T; var u:U; var v:V; }
type R_I = R(int); // OK
type R_IR = R_I(real); // OK
type R_IRS = R_IR(string); // OK

// compiler generates this initializer
proc R.init(type T,
                  type U,
                  type V,
                  t:T = default(T),
                  u:U = default(U),
                  v:V = default(V)) {
  this.T = T;
  this.U = U;
  this.V = V;
  this.t = t;
  this.u = u;
  this.v = v;
}

// and this specialization
proc R(T=int, U=real).init(type V,  t:T = default(T), u:U = default(U), v:V = default(V)) {
  this.V = V;
  this.t = t;
  this.u = u;
  this.v = v;
}
// and this specialization
proc R(T=int, U=real, V=string).init(t:T = default(T), u:U = default(U), v:V = default(V)) {
  this.t = t;
  this.u = u;
  this.v = v;
}

var x = new R_IR(V=string); // R(T=int, U=real).init(V=string)
var D: R_IRS; // R(T=int, U=real, V=string).init()

var y = new R_IR(T=real); // doesn't compile, because R(T=int,U=real) doesn't have a T argument
```

### run-time types
``` chapel
record R { type T; var x:T; }
  
var D = {1..2};
var Arr:[D] int;
var a = new R(Arr.type, Arr);
var b = a;

var OtherDom = {2..5};
var OtherArr:[OtherDom] int;
var c:R(OtherArr.type) = a;

// compiler generates this init=
proc R.init=(other : this.type) {
  this.T = other.T;
  this.x = other.x;
}

// and this specialization
proc R(ArrayType).init=(other : this.type) {
  this.x = other.x;
}

// The compiler translates
var c:R(OtherArr.type) = a;
// into
var c:R(OtherArr.type) = noinit; // compile-time types only, no default init
c.T = OtherArr.type; // Set the appropriate runtime type field in c
c.init=(a);
```

### array init=
``` chapel
// the compiler could directly support
proc _array.init=(d : domain, type eltType, expr);
// or the compiler could add a type argument for the runtime type component
// (since it's not actually available in a field of _array before it is initialized)
proc _array.init=(type ThisType, type eltType, expr);
```

### Wrapper Pattern with User Initializers
What if the user wanted to support this default initialization pattern but provided custom initializers for the type?

They need only provide a single initializer that uses *simple initialization* of the relevant field:

``` chapel
record Wrapper { var x; }
proc Wrapper.init(x) {
  this.x = x;
}
type WrapperInt = Wrapper(int);
var a: Wrapper(int); // becomes Wrapper(int).init(x=default(int));
var b: Wrapper(int); // becomes Wrapper(int).init(x=default(int));
var c = new Wrapper(5); // becomes Wrapper.init(5)
```

### Partial Instantiation and Typeless Fields
``` chapel

record R {
  var a;
  var b;
  var c;
  var d;
}


type RI = R(int);

var something = new RI(b=2,c=3,d=4); // user is expecting to produce R with a=0, b=2, c=3, d=4
// Note, user would expect new RI(1, ... ) to set a=1
```

Under this proposal, the compiler would generate this initializer:
``` chapel
// compiler generates this initializer
proc R.init(a, b, c, d) {
  this.a = a;
  this.b = b;
  this.c = c;
  this.d = d;
}
```

What happens to the call of interest?

``` chapel
var something = new RI(b=2,c=3,d=4);
// This call is translated into R(a=int).init(b=2, c=3, d=4)
// which resolves to the call below and functions as expected.

// How would the compiler specialize that to R(a=int) ?
proc R(a=int).init(a:int = 0, b, c, d) {
  this.a = a;
  this.b = b;
  this.c = c;
  this.d = d;
}
```

What if the user wanted to create custom initializers for R? What initializers would they need to create to support arbitrary patterns of partial instantiation?
``` chapel
proc R.init(a, b, c, d) {
  this.a = a;
  this.b = b;
  this.c = c;
  this.d = d;
}
```

would support the same patterns as the default initializer because it uses *simple initialization* of each field.

What if the user didn't want to use defaults for the partially instantiated types? They would need to use different initializer argument names or otherwise disrupt the compiler's pattern matching.

**Comment by lydia-duncan** [comment]
No additional weaknesses.  I prefer this to the first one, but I can see the already-present weaknesses being too great.

**Comment by lydia-duncan** [comment]
I'm partially through looking at option 3.  It seems like the compiler generating `= default(T)` stuff is not a show stopper for that proposal, but it is for this one?  What would prevent us from exposing that support to the user for this proposal but allows us to do so for the other one?  Am I misunderstanding something?

**Comment by mppf** [comment]
@lydia-duncan - in this proposal, there is no way for a user to reproduce the behavior of the compiler-generated initializer with a user initializer. In option 3, they can do so with the optional default arguments.

Consider the "Two typeless fields" proposal:

``` chapel
record R { var x,y; }
// in Option 3, the compiler generates this initializer
// the default values are ignored if the relevant type component is unknown
proc R.init(x=if this.type.x then default(this.type.x), y= if this.type.y then default(this.type.y))
```

The point is that a user could write that `R.init` if they wanted to. Vs under this proposal, they'd have no way to access the same functionality. (Of course, we could talk about mixing the proposals and using this approach to solve that one problem, or something else).

**Comment by lydia-duncan** [comment]
I thought the problem was that `default(T)` is not available at all, though?  Like, being able to write a default value involving an if statement aside, we'd still need to add support for `default(T)`, right?

**Comment by mppf** [comment]
I don't think it'd be a big deal to provide a way for users to write `default(T)`, so I'm assuming either way that we would be willing to allow a user to write something along those lines.

In this option, if the user had:
``` chapel
record R { var x; }
proc R.init(x) {
  ...
}
```

then we have no way of telling the compiler that it should get a default value for `x` in the event that it's specialized, at least not within that initializer:

``` chapel
type Rint = R(int);
var x: Rint; // what initializer does this run? In this proposal, it runs Rint.init(), which doesn't resolve
```

**Comment by lydia-duncan** [comment]
Oh, okay!  That's what I was missing, thanks!

**Comment by vasslitvinov** [comment]
This proposal and the pass-type-alias-arguments-as-named-arguments-to-initializers strategy are very similar w.r.t. the user experience.

```chpl
record R {
  type T;
  var x;
  type Q;
  proc init(type T, x, type Q) ...  // or compiler-generated
}

// user code
type RI = R(int);
new RI(5,real);

// convertion by compiler under this proposal
proc R(int,?,?).init(x, type Q) ... // implicitly added by compiler
new RI.init(5,real);

// convertion by compiler under "pass named arguments"
new R.init(T=int, 5, real);

// This should probably not be an error despite passing 'T' - make it a special case?
new RI(T=int, 5, real);

// This should definitely be an error because int!=real.
new RI(T=real, 5, real);

```


I suggest that we apply the *simple initialization* restriction regarding of which strategy we choose - whether specializing or passing named arguments.

**Comment by mppf** [comment]
Closing because we ended up implementing towards a different design.
