### ISSUE TITLE
The file.check() function succeeds when the file is closed.

### ISSUE THREAD

**Issue by tmacd8** [chapel-lang/chapel#12373]
### Summary of Problem

If a file variable has never been assigned to using some open() function then file.check() fails.  However,
if the file is opened and then closed - file.check() succeeds.  Is this intended?  After a file is closed,
all other file functions throw an error.  It seems that if file.check() succeeds then one might reasonably assume that other file operations are allowed.  Should file.check() throw an error if the file is closed?

### Steps to Reproduce

**Source Code:**

```chapel
var f: file;

try {
  try {
    f.check();
  } catch e: SystemError {
    writeln("file.check error:  " + e.details);  // expected
  }

  try {
    f = open("/tmp/test", iomode.cw);
  } catch e: SystemError {
    writeln("open error:  " + e.details);  // not expected
  }

  try {
    f.close();
  } catch e: SystemError {
    writeln("close error:  " + e.details);  // not expected
  }

  // try 'check' on a closed file
  try {
    f.check();
    writeln("Not expected as file is closed!!!!!");
    writeln(f.path);
  } catch e: SystemError {
    writeln("file.check/path error:  " + e.details);  // what should happen here?
  }

  try {
    var len = f.length();
  } catch e: SystemError {
    writeln("file.length on closed file:  " + e.details);  // expected
  }
} catch {
  halt("catchall");
}
```

**Compile command:**
`chpl foo.chpl`

**Execution command:**
`$ ./foo`
file.check error:  Operation attempted on an invalid file
Not expected as file is closed!!!!!
file.check/path error:  in file.path
file.length on closed file:  in file.length()

### Configuration Information

- Output of `chpl --version`:  chpl version 1.18.0
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: intrinsics
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none

- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

**Comment by mppf** [comment]
Fixed by #12591
