### ISSUE TITLE
should Math module have signbit ?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#12395]
I just noticed that the Math module doesn't have any way to detect the sign of a zero or NaN.
In C you can do this with `signbit` or `copysign` but neither of these functions are available in our Math module.

Should one or both of them be made available?

E.g. `-0.0` and `0.0` have different signs, as do `-NAN` and `NAN`.

**Comment by bradcray** [comment]
This seems like reasonable functionality to me.  The names don't particularly resonate with me, but I don't have better suggestions either.

**Comment by AnubhavUjjawal** [comment]
I added the `signbit` function in Math module and wrote some tests. Please have a look at https://github.com/chapel-lang/chapel/pull/12606
