### ISSUE TITLE
deque/list design: references

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#12412]
We will be replacing the current list/deque functionality on arrays with distinct types. This issue concerns the design of those types and whether references can be invalidated.

At some point during the life of a container, it will need to allocate additional memory for new elements. A simple implementation of these types could allocate a new chunk of memory and copy the old elements over, but this would invalidate any old references to those elements.

Should these types be implemented such that references to elements are never invalidated?

What does this mean for the API? Do we still support insert/remove operations?

**Comment by bradcray** [comment]
@benharsh / @dlongnecke-cray: Seems like this could potentially be closed now?

**Comment by dlongnecke-cray** [comment]
Closed with the merge of https://github.com/chapel-lang/chapel/pull/13173. The `list` type is implemented with a segmented array as backing store, a consequence of which is that emplaced elements are never moved when allocating space for more elements.
