### ISSUE TITLE
Request for stack-allocated array

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#12420]
Feature request. #12417 tries to use a homogeneous tuple like a stack-allocated array and the compilation time blew up. Is there language support for stack-allocated arrays? If not, I want a stack-allocated array in whatever syntax makes sense. I assume that means a regular array syntax with some modifier, but maybe there's an optimization to be had by transforming homogeneous tuples into stack-allocated arrays (homogeneous tuples also have unique syntax vs. regular heterogeneous tuples).

I don't know if you'd want to support distributed stack-allocated arrays; I don't have use for distributed yet. You can't distribute a tuple, so that's one of the side benefits of a homogeneous tuple being a proxy for / turned into a stack-allocated array.

**Comment by mppf** [comment]
@BryantLam - actually we already support this (new in this release and documentation is forthcoming). PR #12156 added a `c_array` type that is stack allocated.

**Comment by mppf** [comment]
I'm closing this issue since `c_array` is a stack allocated array.
