### ISSUE TITLE
Add a standardized deprecation warning built-in

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#12438]
It would be nice to have a standardized deprecation warning function to ensure deprecation messages are consistent, e.g.

```chpl
deprecationWarning('foo', 'bar');
```

```
chpl example.chpl
example.chpl:1 warning: foo is deprecated - please use bar
```

**Comment by ben-albrecht** [comment]
Related for docs: https://github.com/chapel-lang/chapel/issues/7120

**Comment by AnubhavUjjawal** [comment]
@ben-albrecht could I work on it ?? I could maybe create something similar to `warning()` ?? Do you have any ideas/preference on this??

**Comment by ben-albrecht** [comment]
Hi @AnubhavUjjawal - Despite being simple to implement, I haven't marked this one with `good first issue`, because it's primarily a political task of making sure the majority of core contributors are on board with the design and exact wording of the warning. 

It's also fairly low-priority, so I was going to wait until post-1.19 release to bring it up to the core contributors.

**Comment by lydia-duncan** [comment]
Given the introduction of the `deprecated` keyword, I think this can be closed (though one could argue that it should wait until we've made a user-facing version of the feature)

**Comment by ben-albrecht** [comment]
@lydia-duncan - agreed. Let's close once `deprecated` is user-facing. 

For anyone stumbling across this issue looking for info on the `deprecated` keyword,. they can find information in the [deprecation docs](https://chapel-lang.org/docs/main/developer/bestPractices/Deprecation.html#best-practices-deprecation).

**Comment by jabraham17** [comment]
Closing, `@deprecated` is the user-facing way to do this today, see https://chapel-lang.org/docs/main/technotes/attributes.html#stability-attributes.
