### ISSUE TITLE
C backend error when uint-param used in array assignment

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#12461]
Related xx

Bug. Low priority since there's a workaround available. There's a C-backend bug when a param is type `uint` and is being used in an array assignment initializer.

```chapel
record Data {
  type pt;
  param p: pt;
}

record DataArray {
  type pt;
  param p: pt;
  
  var data: [1..10] Data(pt, p);
}

proc main() {
  // Ok
  Data(int, 42);
  Data(real, 42.1);
  Data(uint, 42:uint);
  Data(uint, 42);
  
  // Ok
  DataArray(int, 42);
  DataArray(real, 42.1);
  DataArray(uint, 42:uint);
  
  // C-backend error: incompatible types when assigning to type ...
  DataArray(uint, 42);
}
```
`chpl version 1.19.0 pre-release`

**Comment by bradcray** [comment]
I got as far as tracking this down to the calls to:

```c
          __primitive("array_set_first", x, i, y);
```

[in ChapelBase.chpl](https://github.com/chapel-lang/chapel/blob/master/modules/internal/ChapelBase.chpl#L859) but then started looking through the code generation for this primitive and got tangled up at this late hour.  @ronawho, are you familiar with this code?  (I'm guessing maybe only the module portion of it, and not the codegen portion?)

**Comment by ronawho** [comment]
I'm familiar with it, but I'm not sure that's where the problem is. Looking at a cut down example, it looks like we're getting the type of `p` wrong, so we're just emitting incorrect types: 

```chpl
record Data {
  type pt;
  param p: pt;
}

var data: [1..1] Data(uint, 42);
compilerWarning(data[1].p.type:string); // reporting int(64), instead of uint(64)
```

Hardcoding the type of p to a uint does not help either:

```chpl
record Data {
  type pt;
  param p: uint;
}
```

**Comment by bradcray** [comment]
> var data: [1..1] Data(uint, 42);
> compilerWarning(data[1].p.type:string); // reporting int(64), instead of uint(64)

Oh that's interesting...  So maybe an initializer-related problem? (@benharsh)  Or maybe simply a `param` problem?

**Comment by benharsh** [comment]
This is... pretty bizarre. I'll take a look.
