### ISSUE TITLE
internal error when combining if expression and forall expression

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#12499]
``` chapel
config const branch = true;


proc main() {
  var array: [1..10] int;
  var b = if branch
          then forall a in array do a
          else array;

  writeln(b[1].type:string, " ", b);
}
```

```
prog.chpl:6: internal error: not handled [resolution/resolveFunction.cpp:2708]
Note: This source location is a guess.
```

**Comment by bradcray** [comment]
Is this a longstanding error, or a regression since the last release?

**Comment by bradcray** [comment]
Took the time to check myself, and it looks like it was in the last release at least:  https://tio.run/##TY7BCoMwEETv@YrBk4JIvSr9EvGwSVcNpImsaYuUfnsa0ELnsrAzbxiz0MouJRP8ZGfks0VoIW8WXBHlwb1SapVgcCfrywpvBTxJQCK0dxjapmkvI6yP/enoTNrpbMm/n@LCHlMQcg6UgaMCtwDqtijWz39hdhsfgTwAeImN7Hyph3Zs4r7ySdQoUNTQVa8@KX0B

**Comment by mppf** [comment]
The context was - I just noticed it when I was writing some code to explore performance of sorts and thought it worth an issue.

**Comment by mppf** [comment]
Good point. I was thinking that the compiler should be able to infer the type of `b` as an array even if the conditonal returns a loop expression on one side and an array on the other. 

``` chpl
config const branch = true;


proc main() {
  var array: [1..10] int;
  var b = if branch
          then forall a in array do a
          else array;

  writeln(b[1].type:string, " ", b);
}

```


```
prog.chpl:6: internal error: not handled [resolution/resolveFunction.cpp:2708]
Note: This source location is a guess.
```

**Comment by bradcray** [comment]
So should the OP be updated?  (and ideally a future filed?)
