### ISSUE TITLE
String varargs leak when referenced as tuple

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#12506]
The following program leaks two strings:
```chpl
proc foo(paths: string ...?n) : string {
  var ret : string;

  for p in paths do writeln(p);

  return ret;
}

proc main() {
  // some dummy strings built up to emphasize this isn't an issue with string literals
  var x, y : string;
  for i in 0..9 do x += i:string;
  for i in 0..9 by -1 do y += i:string;

  foo(x, y);
}
```

The components of 'paths' are copied when the compiler decides it needs to turn 'paths' into a tuple, but fails to insert autoDestroys for those copies. This happens in callDestructors during ``ReturnByRef::updateAssignmentsFromRefArgToValue``.

Oddly enough, it also seems to matter that 'foo' returns something, even though that returned value has nothing to do with the values in 'paths'.

This leak can be worked around by adding the ``in`` intent to the ``paths`` formal.

The exact usage of 'paths' doesn't much matter as long as the compiler creates a tuple. This won't happen if the user refers to components using literals (e.g. "paths(1)"), but can happen if paths is referred to as a whole:
```chpl
for p in paths do ...
writeln(paths);
for param i in 1..n do ... paths(i) ... // very weird
```

**Comment by bradcray** [comment]
Was this true in 1.18 as well?  (guessing / hoping so)

**Comment by benharsh** [comment]
I just verified that this was a bug in 1.18 as well.

FYI, I don't intend to try and tackle this for 1.19, I think the fix would be too risky at this point.

**Comment by dlongnecke-cray** [comment]
Great! I'll have my fixes to the Path module done after I run a full test.
