### ISSUE TITLE
Memory leaks from #12225 (and parallel error-handling in general)

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#12511]
https://github.com/chapel-lang/chapel/pull/12225 introduced new memory leaks for tests added in that PR, but it looks like there might have been existing leaks for parallel error-handling. Here are the current leaks for `test/errhandling/parallel/`:

```
====================
Leaked Memory Report
==============================================================
Number of leaked allocations
              Total leaked memory (bytes)
                           Description of allocation
==============================================================
          13           624  TaskErrors
           5           240  _EndCount(AtomicT(int(64)),int(64))
          13           200  array elements
==============================================================

=======================
Memory Leaking Programs
==============================================================
Total leaked memory (bytes)
              Program
==============================================================
         768  nested-coforall-throws.chpl
         104  forall-throws-subtasks.chpl
          96  forall-wrap-first-error.chpl
          48  forall-range-throws.chpl
          48  forall-throws.chpl
==============================================================
```

**Comment by ronawho** [comment]
Hmm, Supposedly this was fixed before with https://github.com/chapel-lang/chapel/pull/7110 (but even going back to right after that PR, I still see leaks in `test/errhandling/parallel`)

**Comment by mppf** [comment]
PR  #12516 fixes the easy problem (which is the source of the array and TaskErrors leaks).

There is a harder problem though. We had `defer` blocks for the `EndCount` to make sure it is deleted. But these are processed (and changed to delete calls at the end of a block) in callDestructors. Then, lowerIterators lowers the ForallStmt into a more complex structure and no longer calls the `delete` if the body of the forall threw an error.

**Comment by mppf** [comment]
I think that problem is a little bit related to #4953. I wonder if @vasslitvinov has any insight into how we might solve it.

**Comment by vasslitvinov** [comment]
#11303 ?? (Fixes leaks that occur when throwing out of chpl_initCopy that produces an array.)
