### ISSUE TITLE
Function isRecord returns true for strings

### ISSUE THREAD

**Issue by daviditen** [chapel-lang/chapel#12586]
The function `isRecord(x)` returns `true` for strings and the string type.  I think it should hide the fact that strings are implemented with records and return `false`.

```
writeln(isRecord(string));
writeln(isRecord("hello"));
```

Prints

```
true
true
```

### Configuration Information

chpl version 1.19.0 pre-release (7e39e187a5)

**Comment by bradcray** [comment]
Bummer.  I definitely agree with your assessment.

**Comment by AnubhavUjjawal** [comment]
Should I add `isStringType(t)` in the or conditions there ??

![Screenshot 2019-03-13 at 3 03 49 AM](https://user-images.githubusercontent.com/22658701/54237730-a891ea00-453c-11e9-9323-7ac2e7eaf661.png)

**Comment by AnubhavUjjawal** [comment]
Ok, So I changed the code and added `isStringType(t)` in the above `proc` and `isRecord` is giving false for those conditions. The only doubt I have is, where to put the tests ??

**Comment by lydia-duncan** [comment]
I would put them under `test/types/string`

**Comment by daviditen** [comment]
I think you've taken the right approach, and agree about `test/types/string`.

**Comment by AnubhavUjjawal** [comment]
I thought so , but directly in `test/types/string` ? There are a lot of folders with contributors names on it inside the  `test/types/string` directory. Should I create my own folder, or directly keep it under ` `test/types/string` directory ?

**Comment by bradcray** [comment]
We're trying to move away from using contributor-specific subdirectory names in the test system.  Now, when adding new tests, I either put them at the top level (like test/types/string in this case) if they feel sufficiently major/key/central to the concept and that directory doesn't already feel overstuffed, or a subdirectory with a reasonably chosen name if not.  In this case, I could see either putting them in that directory directly or in a `queries/` or `typeQueries` subdirectory maybe?  No strong preference here.

**Comment by AnubhavUjjawal** [comment]
please see https://github.com/chapel-lang/chapel/pull/12589
