### ISSUE TITLE
Dynamic cast from parent to generic child causes compiler internal error

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#12585]
Design question. Usage question. Causes internal error in compiler at `[1]`.

(I don't know the Chapel terminology for this, so I'll use the phrasing from C++.)

I want to create classes with straightforward tree inheritance and do a dynamic "downcast" from parent to child when the parent object is detected to be a child object. The children, however, are generic. How do I cast into a generic child object if I'm passing around parent objects?

If there's a known solution or design pattern I should be using, please update the documentation to reflect this usage.

```chapel
class A {
  proc is_child() { return false; }
}

class B {
  // Generic B causes internal error at [1]
  // Comment out these next three lines and the program will work.
  type t;
  var val: t;
  proc init() { t = int; val = 42; }

  override proc is_child() { return true; }

  proc do_child_func(): string {
    return "Called B.do_child_func() successfully";
  }
}

proc check(value: A) {
  if (value.is_child()) {
    writeln("B = ", value);
    writeln( (value: B).do_child_func() ); // [1]
  } else {
    writeln("A = ", value);
  }
}

proc main() {
  var a = new shared A();
  check(a.borrow());

  var b = new shared B();
  check(b.borrow());
}
```
`chpl version 1.19.0 pre-release`

  proc init() {
    t = int;

**Comment by BryantLam** [comment]
Whoops. `class B --> class B: A`

**Comment by mppf** [comment]
> I want to create classes with straightforward tree inheritance and do a dynamic "downcast" from parent to child when the parent object is detected to be a child object. The children, however, are generic. How do I cast into a generic child object if I'm passing around parent objects?

Two key points.
 1. Use cast on classes to do downcast. You get `nil` if the instance isn't of that type.
 2. You have to cast to a fully instantiated type. (Doing something otherwise would require some different strategies for generic compilation besides the instantiation strategy we have now, AFAIK).
 
Here is an example:

``` chapel
class Parent {
}

class Child : Parent {
  type t;
  var val: t;

  proc do_child_func(): string {
    return "Called Child(" + t:string + ").do_child_func() successfully";
  }
}

proc check(value: Parent) {
  var asChildInt = value:Child(int);
  var asChildReal = value:Child(real);
  if asChildInt != nil {
    writeln("value = ", value);
    writeln( asChildInt.do_child_func() );
  } else if asChildReal != nil {
    writeln("value = ", value);
    writeln( asChildReal.do_child_func() );
  } else {
    writeln("value = ", value);
  }
}

proc main() {
  var a = new shared Parent();
  check(a.borrow());

  var b = new shared Child(int, 0);
  check(b.borrow());
  
  var c = new shared Child(real, 0.37);
  check(c.borrow());
}
```

> If there's a known solution or design pattern I should be using, please update the documentation to reflect this usage.

The language spec covers this in section 9.2.4, "Explicit Class Conversions". Arguably there should be some note about it in the Classes chapter.

**Comment by BryantLam** [comment]
Perfect. Thanks!
