### ISSUE TITLE
Recursive type alias causes compiler segfault

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#12612]
Bug. Not a high priority. This arguably incorrect code causes compiler segfault.

I was trying to basically make it so I didn't have to write `R(size)` everywhere, but accidentally wrote a type alias was recursive(?).

```chapel
record R {
  param size: uint;

  proc type t type
    return uint(size);

  type this_type = R(size); // Recursive? This line causes a segfault.

  var x: this_type.t;
}

proc main() {
  var r: R(64);
}
```
`chpl version 1.19.0 pre-release`

Somewhat unrelated, but this simple program causes an internal error:
```chapel
record R {
  param size: integral;
}
proc main() {
  R(64);
}
```
This program has no priority for me. I was curious what would happen if `size: integral`.

**Comment by BryantLam** [comment]
Probably a duplicate of #12562, but I have no idea.

**Comment by bradcray** [comment]
@mppf: Just to make sure I'm following, is it correct that #18069 resolved the first/main issue here, but that you kept this issue open due to the second one?

**Comment by mppf** [comment]
Yes, that's the current situation. I think it'd be reasonable to split the second program out into another issue and close this one but I haven't. (And at the moment I have enough side projects).

**Comment by mppf** [comment]
(Note that the 2nd program does still seem to fail with an internal error.)

**Comment by bradcray** [comment]
OK, I had the same thought, just wanted to confirm I was understanding.  I'll try to split it out.

**Comment by bradcray** [comment]
Closing in favor of #18147.
