### ISSUE TITLE
HDFS package module does not compile

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#12627]
The HDFS package module is known to be broken for `chpl version 1.19.0.dec8fd3341`. I have not tracked down the specific point at which it broke, but this does include Chapel 1.19 release.

This issue should be addressed in the IO plugin effort being done in https://github.com/mppf/chapel/tree/io-plugins-chapel.

**Comment by bradcray** [comment]
By "as of" do you mean that it was the first point at which it broke (how it reads to me), or that you know it's broken for that version but that it might well be broken for previous ones too?

**Comment by ben-albrecht** [comment]
@bradcray  - Updated description for clarity. Not sure if this includes previous versions.
