### ISSUE TITLE
type-inferred default argument value `new C()` doesn't accept `new C()` as actual

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#12638]
### Summary of Problem

It seems that if a default argument value is `new C()` (with no type specifier), we cannot pass `new C()` in as an actual argument which seems surprising.  I'd expect the type of the formal to be `[borrowed] C` which would suggest that `new C()` ought to be able to be passed in.  If the formal is explicitly given `C` as its type, this works as expected (but seems it should not be necessary).

### Steps to Reproduce

**Associated Future Test(s):**
[`test/classes/delete-free/default-arg-typeless.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/classes/delete-free/default-arg-typeless.chpl
          ) #12636 

### Configuration Information

- Output of `chpl --version`: `chpl version 1.19.0.f2774d2`

**Comment by cassella** [comment]
[Moving example here from comment in PR #12636]

```chapel
class C {
  var x: int;
}

proc bar(c = new C()) {
  writeln(c.type:string);
  writeln(c);
}

writeln("Default bar");
bar();

writeln("Supplied unmanaged C");
bar(new unmanaged C());
```

```
Default bar
unmanaged C
{x = 0}
Supplied unmanaged C
unmanaged C
{x = 0}
```

**Comment by mppf** [comment]
This is probably related to #10104.
