### ISSUE TITLE
Should users be able to apply two management flavors to a given clas

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#12639]
### Summary of Problem

I was surprised to find that our compiler permits two memory management flavors to be applied to a given class type without complaint and filed the future below against it thinking it was a bug.  In the PR, Michael raised questions about whether it really was a bug and what the implications were for the language.  This issue is designed to capture the topic as a language design discussion.

### Steps to Reproduce

**Associated Future Test(s):**
[`test/classes/ferguson/class-double-modifier.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/classes/ferguson/class-double-modifier.chpl
          ) #12603

### Configuration Information

- Output of `chpl --version`: `chpl version 1.19.0.28d7ebe`

**Comment by mppf** [comment]
Here is my comment from the PR

It's unclear to me. Part of the reason it works the way it does now - besides implementation reasons - is that I had imagined that there were scenarios where one would want, in generic code, to allocate a new instance of some type, where the type comes from a type argument. When doing that, I think the generic code might:
 a. Want to use whatever management discipline the type included, or
 b. Want to specify the memory management that should be applied to the allocation

Supposing the generic code wanted to do `b`, today they would write
``` chapel
proc f(type t) {
  var instance: owned t = new owned t();
}
```

(for example) and that would work today.

If we decided to make this an error, they would have to write
``` chapel
proc g(type t) {
  type borrowT = t.borrow();
  var instance: owned borrowT = new owned borrowT();
}
```

but that's presuming we still allow the behavior to go from borrowed to owned (but not say owned to shared).

How would you write the b case if it were always an error to "upgrade" a `borrowed MyClass` to a `owned MyClass`? Wouldn't that require that we introduce a user-facing view of `MyClass` as a different type from `borrowed MyClass`? That would seem unfortunate.

**Comment by bradcray** [comment]
Oh, I was just working on pasting it here.  You beat me to it.  :)

**Comment by bradcray** [comment]
In a recent discussion, we decided to leave this as-is.  As I understand it, the thought was that requiring the user to "unwrap" flavored class types and then "rewrap" them was onerous.  It also led to a puzzling  question along the lines of "What is an unwrapped class type?" given that `C` in Chapel code usually means `borrowed C` rather than simply `class C`.
