### ISSUE TITLE
isSubset not supported on rectangular domains

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#12651]
isSubset (and probably isSuperset) don't work on rectangular domains:

``` chapel
var a = {1..10};
var b = {1..2};

writeln(b.isSubset(a));
```

```
d.chpl:4: error: isSubset not supported on rectangular domains
```

I see no reason why they could not work. I would expect the above program to output `true`, for example.

**Comment by akshansh2000** [comment]
I've observed that the issue does not persist if I write:
```chpl
var a = {1, 2, 3, 4, 5};
var b = {1, 2};
writeln(b.isSubset(a));
```
Output: `true`

However, if I replace the content with a range, as in:
```chpl
var a = {1..5};
var b = {1..2};
```
it fails.

I'd like to take up this issue.

**Comment by mppf** [comment]
@akshansh2000 - right, the first example is using associative domains.

As far as how to fix, look here:

https://github.com/chapel-lang/chapel/blob/cf27c21e6281e3f7eaae27960ef95d4801d502b7/modules/internal/ChapelArray.chpl#L1558-L1594

You might be able to use https://chapel-lang.org/docs/master/builtins/ChapelRange.html#ChapelRange.range.contains (range contained with other range) along with https://chapel-lang.org/docs/master/builtins/ChapelArray.html#ChapelArray.dims

I just noticed your PR - yes, it works, but it does extra work for rectangular arrays, since the forall iterates over every element rather than doing range operations.

I think it's likely that we'll want to change the names of these methods in the future. It may be that simply renaming `isSubset` to `contains` is the direction to go. However in your PR please leave the names as-is.

**Comment by akshansh2000** [comment]
@mppf, thanks for this! I've made the necessary modifications.
