### ISSUE TITLE
Failing tests in interop/python when CHPL_LLVM=llvm and --compopts --llvm

### ISSUE THREAD

**Issue by dlongnecke-cray** [chapel-lang/chapel#12661]
Tests in `interop/python` fail on `darwin` when:

- `CHPL_LLVM=llvm`
- Invoked with `start_test --compopts --llvm`

These are the tests that fail:

- arrayOpaquePointer_block.chpl (segfault)
- arrayOpaquePointer_block_with.chpl (segfault)
- intArrays.chpl (Python MemoryError)
- realArrays.chpl (Python MemoryError)

I suspect these failures are related to a similar issue with opaque arrays in `interop/C/llvm/exportArray`, though I can't say for sure.

@lydia-duncan suggested making a llvm subdirectory in `interop/python` to track these failures, so I'll do that first.

These tests fail after the changes introduced by #12653. I don't know if they occur before then. I'll run against master before merging #12653 to find out.

**Comment by lydia-duncan** [comment]
Yeah, that definitely seems to be limited to arrays, thank goodness.

Meta note: I'd update your description to mention that it occurs after the changes in your PR

**Comment by dlongnecke-cray** [comment]
Looking into this issue, but I no longer seem to be able to reproduce these failures.

**Comment by dlongnecke-cray** [comment]
Closing, neither Brad or I were able to reproduce these failures (and it's been awhile, so I have no doubt that the circumstances for interop+LLVM support have changed).
