### ISSUE TITLE
Support `chpl` version number queries from Chapel source

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#12686]
As a Chapel user, I'd like to be able to query and reason about Chapel's version number within my source code as param values so that I could add overloads or features in a way that was sensitive to the version number for backwards compatibility.  For example, imagine the ability to write things like:

```chapel
proc _domain.contains(i) where (CHPL_VERSION_MAJOR == 1 && CHPL_VERSION_MINOR < 19) {
  return this.member(i);
```

as a means of getting backwards compatibility for a routine that had changed names.

**Comment by lydia-duncan** [comment]
Is this a duplicate of #5491?

**Comment by bradcray** [comment]
Look at that, it sure is!  Thanks!

**Comment by ronawho** [comment]
I was hoping you could do something like:

```chpl
proc _domain.contains(i) where !canResolveMethod(this, "contains", i) {
  return this.member(i);
}
```

but I guess that's an infinite call chain.
