### ISSUE TITLE
The --dynamic flag should create a shared library when compiling with --llvm

### ISSUE THREAD

**Issue by dlongnecke-cray** [chapel-lang/chapel#12699]
Currently, it looks like the LLVM backend creates a static library irregardless of whether `--static` or `--dynamic` is passed to Chapel as an argument.

The `makeBinaryLLVM()` function in `compiler/llvm/clangUtil.cpp` branches to `makeLLVMLibrary()` when compiling a library. This function creates a static library using the `ar` utility.

It appears that no additional linking step is taken in the case of `--dynamic`. If this is indeed the case (and I'm not missing something), it would be a simple fix to invoke the linker with the correct arguments to create a shared library.

**Comment by lydia-duncan** [comment]
I have no reason to believe your analysis is incorrect :)
