### ISSUE TITLE
how many string types per program?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#12726]
Currently, there is only 1 string type, `string`, which is not generic. Additionally, the current implementation uses C functions for a variety of multi-byte-string tasks. As a result, the current implementation has a string encoding that depends on the setting of environment variables.

Here the question is - how many `string` types do Chapel programs need? (And a related question is - what is the type of a string literal?).

I think that we have started to conflate two issues in answering this question. In particular, when asked if all Chapel strings could be UTF-8, we say "Not all the textual data that someone might need to manipulate is UTF-8, so we can't assume that everything is UTF-8". 

My point now is that *even if we do support working with textual data in other encodings* the string type could still consist only of some variant of Unicode. How would that work? The string data would be converted between Unicode and the other encoding in the process of doing I/O.

### Python 3

In Python 3, a `str` is always Unicode, but a *file* can specify an arbitrary encoding. String literals always start out as UTF-8 since Python assumes that all Python source code is encoded in UTF-8. Python may represent a given string using a different Unicode encoding than UTF-8, but *it's still always a Unicode string*. [Reference](https://www.b-list.org/weblog/2017/sep/05/how-python-does-unicode/).

When you `open` a file in Python, you specify if you want the file to be in *text mode* or *binary mode*. 

For binary mode, file operations generally work with `bytes`.
For text mode, file operations generally work with `str`, the Unicode string type.

For text mode files, you can pass an `encoding` [Reference](https://docs.python.org/3/library/functions.html#open). The default `encoding` comes from the POSIX locale environment variables [Reference](https://docs.python.org/3/library/locale.html#locale.getpreferredencoding) although in some cases Python uses UTF-8 by default [PEP 538](https://www.python.org/dev/peps/pep-0538/) and it's possible to request Python default to using UTF-8 instead of the POSIX locale [PEP 540](https://www.python.org/dev/peps/pep-0540/).

Python supports about 100 encodings, including things like Big5, shift-jis,  UTF-32-little-endian, iso8859_10.

Besides specifying the encoding in the `open` call, you can specify how encoding errors are handled. You can select among these options:
 * `string` raise an error
 * `ignore` ignore errors (generally causes data loss)
 * `replace` replace malformed data with a replacement character
 *  `surrogateescape` use private use code points to escape invalid bytes
 * `xmlcharrefreplace` when writing, replace unsupported characters with `&#nnn;`
 * `backslashreplace` replaces malformed data by `\` escaped characters
 * `namereplace` when writing, replace unsupported characters with `\N{...}`

Lastly, Python files working in text mode automatically convert line endings, and this too can be customized with `open` arguments.

So, we can see in Python 3 that there are 2 "string" types:
 1. `str` is a Unicode string, in some Unicode encoding. String literals are this type.
 2. `bytes` contains arbitrary bytes. `b"bla"` literals are this type.

There are not 100 string types. There are not even 5. Just 2.

How would you work with a file containing mixed text and binary data in Python?
 * open the file in binary mode
 * then convert certain `bytes` read to Unicode `str` according to the file format

### Rust

Rust has several string types:
 * `std::string::String` is a UTF-8 string
 * `&[u8]` is a "byte slice"
 * `OsString` (for interoperation with the OS, e.g. for file names)
 * `CStr` (for interoperation with C)

To create a string from arbitrary data, one uses `from_utf8` [Reference](https://doc.rust-lang.org/nightly/std/str/fn.from_utf8.html).

In Rust, all files are opened in "binary" mode; there is no concept of text mode for files.

When reading a string e.g., Rust only provides two options in the standard library:
 1. Read the string data into a bytes buffer
 2. Read string data into a `String` but will return an error if it encounters data that is not UTF-8

Part of the design is that it's cheap and easy to convert a `String` to an `OsString`. When converting an `OsString` to a `String`, one chooses how non-UTF-8 data is handled by choosing the method for the conversion:
 * `into_string` - doesn't convert if the string contains non-valid unicode
 * `into_string_lossy` replaces invalid unicode sequences with the unicode replacement character
But to convert an `OsString` into a `String` requires that it be valid UTF-8.

There is a contributed Crate for doing conversions to or from Unicode [encoding_rs](https://docs.rs/encoding_rs/0.8.7/encoding_rs/index.html) but Rust itself only really supports "bytes" and "UTF-8" strings.

### Swift

Swift stores strings in *some* Unicode representation (but doesn't say which one). [Reference](https://developer.apple.com/documentation/swift/String). There are methods to get the UTF-8, UTF-16, ... versions of the string. It's possible to create strings from binary data in the various unicode encodings. It's possible to convert bytes into a string while specifying the encoding but only 23 encodings are currently supported [Reference](https://developer.apple.com/documentation/swift/string/encoding). 

Swift does not currently have any File I/O capabilities within its own standard library but rather developers are expected to use existing libraries. These libraries (e.g. the C library) tend to return bytes (rather than ensuring the file contains UTF-8, say). After reading some bytes, one can decode the bytes into a String using one of the many encodings that are supported.

### Java
Java represents strings in UTF-16 (with surrogate pairs).

It's possible to construct a string from a `byte[]` and a character set.

FileReader reads textual data but InputStream reads binary data. One can specify the character set for a given file by constructing a custom [InputStreamReader](https://docs.oracle.com/javase/8/docs/api/java/io/InputStreamReader.html). It might be dependent on the Java VM running a program exactly which character sets are supported. But in practice there are a large number - I measured 171 [TIO](https://tio.run/##dY4xD4IwEIX3/oo3QoyNrhImZidG41CgYqG0pD1IiOG3Y1NwdLmXvPvevevELM52lKZr@m1Tw2gdoQsmN8ry@i2cl8SLXTPGai28x30pon4YME6VVjU8CQoyW9VgEMokJTll2scTwrU@jSigDKG2U5g5Llm0XtbhgNHL5YajjIcnlBaVlofhk5QHoJSUpL97QLl4kgO3E/Ex3CBtkgCl2bHey045rruzsj@hCMbYytZt@wI).

When creating an InputStreamReader, if no charset is specified, the platform's default is used.

### C#

C# also uses UTF-16 Strings. However it's possible to construct an invalid UTF-16 string (invalid surrogate pair) [Reference](https://docs.microsoft.com/en-us/dotnet/api/system.string?view=netframework-4.7.2#Unicode)

Like Java, C# supports lots of encodings.

In C#, you can create a StreamReader to read file data in a particular encoding [Reference](https://docs.microsoft.com/en-us/dotnet/api/system.io.streamreader?view=netframework-4.7.2).

When creating a StreamReader, the default encoding is UTF-8 but one can request a different encoding, including the "system default" [Reference](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.default?view=netframework-4.7.2).

### Go

Go allows its string type to store non-UTF-8 data [Reference](https://blog.golang.org/strings).

Many operations have a reasonable interpretation when applied to arbitrary bytes or to UTF-8 (e.g. split, find, indexof, replace). (Note that this relies on certain properties of UTF-8 to be reasonable).

Some methods assume it is storing UTF-8 and might have no effect if not - e.g. [ToTitle](https://golang.org/pkg/strings/#ToTitle) simply doesn't convert non-UTF-8 data. One can convert a string to an array of codepoints (aka runes) and in that event, any bytes that are invalid UTF-8 will be replaced with the Unicode replacement character 0xFFFD � [Reference](https://yourbasic.org/golang/convert-string-to-rune-slice/). See also my [example program](https://play.golang.org/p/F6cl936AHrl) exploring some of these things.

There does not seem to be any facility for reading different character sets in the I/O system. Instead, like Rust, the string I/O operations assume UTF-8 input and output. [Reference](https://golang.org/pkg/bufio/#Reader.ReadRune)

## Summary

Of the languages surveyed, no language includes a string type with parameterizeable encoding that spans something like Big5 and UTF-8. Some languages allow a variety of Unicode encodings (Swift, Python). Other languages pick one (C#, Java use UTF-16; Rust and Go use UTF-8).

Of the languages surveyed, no language uses a string type which has its encoding based upon an environment variable (e.g. the POSIX locale environment variable).

All of the languages surveyed have some concept of a "bytes" type, although in some of them it is pointer-to-uint8 or array-of-uint8.

Not all of the languages surveyed support opening a file in "text mode" from a specified character set, but Python, Java, and C# have this kind of idea.

Not all languages necessarily respect POSIX locale environment variables at all:
 * Python, Java do when constructing a text reader
 * Rust and Swift do not (unless interoperating with C)
 * C# text readers default to UTF-8 but code can explicitly request the system encoding

I do not think we should vary greatly from the design in these other languages. I think we should:
1. include a concept of a `bytes` type. Since `string` includes much functionality that is different from `c_ptr(uint(8))` or `[] uint(8)`, I think it makes sense for us to create a `bytes` type that has many similar methods to `string`. However one could argue that `[] uint(8)` should serve this purpose.
2. include a string type with a fixed Unicode format (probably UTF-8, based on our work so far)
3. decide how we want I/O to work when reading `string`, where we can choose between
   a. Just jam the bytes read into `string` - `string` stores UTF-8 or invalid UTF-8 and you get an error when doing UTF-8 things with it if it's not actually UTF-8 (as far as I know, only Go uses this strategy)
   b. Have an idea of "text mode" files and convert the characters read from an optionally specified character set to UTF-8 when reading (and from UTF-8 when writing). (Python, Java, C# do this).
   c. Have an idea of reading in "text mode" but that only means reading UTF-8. (Rust does this).
   d. Only allow reading `bytes` and force users to convert from them to `string` manually (Swift arguably does this now).

### Appendix: Kyle's String Proposal

An aside. I think Kyle did a good job of identifying some issues with Unicode support and many of these issues are not yet resolved. See https://gist.github.com/Kyle-B/44138a37907a2a53c4b2

**Comment by dmk42** [comment]
One string type per program.

Possible character set conversion during I/O to be discussed at deep dive, probably resulting in an issue being filed.
