### ISSUE TITLE
string and bytes types in filesystem scenarios

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#12728]
This issue is related to #12726.

Here I'd like to discuss 3 designs:
 1. Separate `string` and `bytes` types, a-la-Python 3; paths are stored in either
 2. Paths are stored in `string` with escaped "invalid" bytes (Perl 6 calls this [UTF8-C8](https://docs.perl6.org/language/unicode) and Python 3 calls it `surrogateescape`).
 3. Paths are stored in `string` and `string` can store arbitrary bytes (but certain methods assume UTF-8).

The example program we will consider when evaluating these 3 designs will:
 * open a file "input.txt"
 * list a directory
 * open each file in the directory in turn

Here is the starting point for the example code:

``` chapel
proc processInput() {
  var f = open("input.txt", iomode.r);
  process(f);
}
proc processDirectory() {
  for filename in listdir() {
    var f = open(filename, iomode.r);
    process(f);

    writeln("Processed ", filename);
  }
}
```

#### Separate string and bytes types

Generally speaking, in a POSIX environment, recommended use of Python 3 is to store file paths as `bytes`.

``` chapel
proc processInput() {
  // The `open` call will accept either `string` or `bytes` for the path:
  // Here we demonstrate where the `open` call can accept `bytes`
  var f = open(b"input.txt", iomode.r);
  // Here we demonstrate where the `open` call can accept  a Unicode `string`.
  // The path actually given to the OS is the UTF-8 encoding of the string.
  var f = open("input.txt", iomode.r);
  process(f);
}
proc processDirectory() {
  for filename in listdir() {
    // `filename` is a `bytes` not a `string` according to this design
    // but the `open` call can accept a `bytes` so that is OK
    var f = open(filename, iomode.r);
    process(f);

    writeln("Processed ", filename);
    // It would either:
    //  1. Interpret this operation as binary I/O (and write the bytes unmodified), or
    //  2. Write the result of encoding the `bytes` into UTF-8 using escaping
  }
}
```

#### Path are stored in `string` with escaping

The idea here is that we can convert any `bytes` sequence into a valid UTF-8 representation that can be then re-converted to the `bytes` sequence.

In particular imagine using `\x` escapes for any byte that does not turn into valid UTF-8. But, since `\` might have other uses in the string, instead of `\` we use a private use code point to mark an escaped sequence.

``` chapel
proc processInput() {
  // Open accepts only a string. The "input.txt" is a valid string literal.
  // It doesn't contain any of the private use code point for escaping,
  // but if it did, it could store a binary file name.
  // Before passing a string path to the OS, `open` will un-escape any escape sequences.
  var f = open("input.txt", iomode.r);
  process(f);
}
proc processDirectory() {
  for filename in listdir() {
    // filename is a `string` which may have escape sequences
    // the open call will translate these back into their binary form
    var f = open(filename, iomode.r);
    process(f);

    // Results in the filename with escape sequences being printed out
    writeln("Processed ", filename);
  }
}
```

#### String can store arbitrary bytes

The idea here is that `string` is generally expected to store `UTF-8` but one can store arbitrary bytes in a `string` and only run into problems when doing certain operations. (For example, `isAlpha` might return garbage values, getting the next codepoint may throw, ...).

``` chapel
proc processInput() {
  // Open accepts only a string. The "input.txt" is a valid string literal.
  // It doesn't contain any non-UTF-8 byte sequences, but if it did, it could still
  // be passed to `open`. The byte sequence representing the string is passed unmodified
  // to the OS.
  var f = open("input.txt", iomode.r);
  process(f);
}
proc processDirectory() {
  for filename in listdir() {
    // filename is a `string` which could be UTF-8 or could contain arbitrary bytes.
    // The open call will pass it through unmodified.
    var f = open(filename, iomode.r);
    process(f);

    // Results in the bytes of the filename being printed out.
    // If the I/O system includes a character set conversion facility, and the conversion
    // is necessary, this operation would presumably do something with invalid UTF-8
    // (such as add a Unicode replacement character or throw an error).
    writeln("Processed ", filename);
  }
}
```

**Comment by e-kayrakli** [comment]
In preparation for 1.20 I put together an attempt where we took design 1. The
now-closed PR is here: https://github.com/chapel-lang/chapel/pull/13939

At this point, design 3 is out of the question, I think.

Design 2 seems to be the right approach to me. Going over the changes I made in
that closed PR I have few notes that I believe is important in choosing a
design.

- Using separate `string` and `bytes` interface for the library gets confusing.
  The main problem for me was choosing return types of the functions. I
  initially thought we can return `bytes` if the function was called with
  `bytes` arguments and vice versa. But what about functions that don't take
  arguments like `cwd()`? If we choose either `string` or `bytes` the user must
  be aware of that and must use the same type in calling other path/filename
  functions. Note that there is no implicit conversion between `string` and
  `bytes`. So there have been quite a few tests that I had to fix in a way that
  types were too explicit and easy to mess up.

  For example:

  ```chapel
  var fullPath = cwd() + "myFile.txt";
  ```

  wouldn't compile if `cwd()` returned `bytes`. 

  All in all, I think we should stick with one type and have those libraries use
  that type. Internally, we can use the other type as we see fit, of course.

- A small but important extension to the previous bullet is some of the
  constants in `Path` and/or `FileSystem` modules. For example we have

  ```chapel
  const pathSep = "/";
  ```

  This is used in application code. And its type is very important if we allow
  both `bytes` and `string` to be used.

- Being encoding-free, `bytes` seems a more reasonable type to do this but I
  don't like forcing users that they have to use `bytes` becuase the difference
  in literals is significant IMO. (I think @bradcray has also mentioned that we
  should have `string`-based interface available for convenience)

Given these concerns that I had while attempting to implement design 1, I think
we should go for design 2.

Implementation-wise design 2 can be a follow up to the UTF-8 validation effort.

@bradcray -- Under #14177 you said that you are against having back door for
users to work around UTF-8 validation (but you were supportive of having
prevalidated path for internal use). Does design 2 bother you in that context?

@mppf -- any thoughts?

**Comment by bradcray** [comment]
I'm open to approach 2, though I don't feel that I necessarily understand it well enough to understand all of the consequences.  So I may need (to do) more education here.

Another potential approach that I don't think we've discussed might be to have cases that you mentioned being ambiguous (like `cwd()`) take an option type argument indicating what kind of type they should return.  We could default these to `string` to handle the common case of UTF-8 compatible paths and filenames (we think it is, right?) while still giving users an option to write code that handles general bytes data.  For example:

```chapel
config type defaultPathType = string;

proc cwd(type retType = defaultPathType): retType where retType == string {
}

proc cwd(type retType = defaultPathType): retType where retType == bytes {
}
```

I think this has the upside of making the common case simple while supporting the general case.  But also the downside of requiring recompilation (and potentially other code changes) to support non-UTF-8 filenames and paths.  I don't know whether it's reasonable to have users anticipate those cases at compile-time vs. being able to handle them whenever they occur.

**Comment by mppf** [comment]
I like Option 2 for paths. I think it matches the common expectation (Filenames are UTF-8) and as a result makes writing code for it simpler under that expectation. At the same time, it supports weird non-UTF-8 filenames (with escaping).

@bradcray - regarding

> So I may need (to do) more education here.

The way I think of this is that just as you can have a string literal with escaping, e.g. `"\x00 hi"`, we can escape the invalid UTF-8 bytes. The difference from `\x` escaping is that since Unicode has a gazillion characters, we can have a special codepoint that means the equivalent of `\x` but that should not occur in otherwise legal UTF-8. The special codepoint is a "private use codepoint".

**Comment by bradcray** [comment]
OK, I feel pretty convinced by that argument, and I like that it keeps us in a strings world.

**Comment by mppf** [comment]
> lack of support for non-UTF-8 filenames and paths could be considered more of an unimplemented feature?

We could do that, yes. Putting it off that way might make a real show-stopper (e.g. for a program that walks a directory structure and takes action per file) if the files cannot be opened at all if the paths are not UTF-8.

**Comment by bradcray** [comment]
> Putting it off that way might make a real show-stopper

Isn't that the nature of any unimplemented feature that a given program needs, or is there something different in this case that I'm not understanding?

For context, do we know how common, in practice, non-UTF-8 filenames and pathnames are in practice?

**Comment by mppf** [comment]
> Isn't that the nature of any unimplemented feature that a given program needs, or is there something different in this case that I'm not understanding?

Yes, but in this case, I think our users will expect that they can write a Chapel program to process an (arbitrary) directory tree on a linux system. Just to reiterate though - we agree that putting it off is an option.

> For context, do we know how common, in practice, non-UTF-8 filenames and pathnames are in practice?

I don't know how to find that out, or if it is even possible to do so.

**Comment by e-kayrakli** [comment]
> For context, do we know how common, in practice, non-UTF-8 filenames and pathnames are in practice?

I am planning to test #14384 today. These tests and nightlies after it's merged *might* give an idea.
