### ISSUE TITLE
Inability to cast from `borrowed C` to `unmanaged C`

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#12730]
### Summary of Problem

Given a borrow that I know borrows from an unmanaged class, it would be beneficial to be able to cast it from `borrowed C` (say) to `unmanaged C`.  Today this doesn't work, yet we can cast it to simply `unmanaged`.  This feels like a non-orthogonality and therefore a bug (or, arguably, a feature request).

### Steps to Reproduce
**Associated Future Test(s):**
[`test/classes/delete-free/unmanaged/cast-to-unmanaged-to-free.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/classes/delete-free/unmanaged/cast-to-unmanaged-to-free.chpl
          ) #12683

### Configuration Information

- Output of `chpl --version`: `chpl version 1.20.0 pre-release (4d906d1)`

**Comment by dgarvit** [comment]
@bradcray I came up with a basic solution in #12750. It would be great if you could review it.

**Comment by bradcray** [comment]
Cool!  I think @mppf would be the most appropriate reviewer here, if he has the time.
