### ISSUE TITLE
Uses of Dimensional distribution leak memory

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#12732]
### Summary of Problem

Uses of the Dimensional2D distribution tend to leak memory related to the per-dimension descriptors.  Notably, this is the only remaining cause of leaks in the test/release/examples directory.  The following tests currently exhibit this problem:

- [ ] chplvis/benchmarks-hpcc/hpl-vdb.chpl
- [ ] distributions/dm/s7.chpl
- [ ] distributions/dm/s8.chpl
- [ ] distributions/dm/s9.chpl
- [ ] distributions/dm/t1.chpl
- [ ] distributions/dm/t2.chpl
- [ ] distributions/dm/t5a.chpl
- [ ] distributions/dm/t8.chpl
- [ ] distributions/dm/t9.chpl
- [ ] release/examples/benchmarks/hpcc/hpl.chpl
- [ ] release/examples/primers/distributions.chpl
- [ ] studies/hpcc/HPL/vass/bc.dim.chpl
- [ ] studies/hpcc/HPL/vass/bc.md.chpl
- [ ] studies/hpcc/HPL/vass/bl.dim.chpl
- [ ] studies/hpcc/HPL/vass/bl.md.chpl
- [ ] studies/hpcc/HPL/vass/hpl.chpl
- [ ] studies/hpcc/HPL/vass/schurComplement.chpl

### Configuration Information

- Output of `chpl --version`: `chpl version 1.20.0 pre-release (4d906d1)`

**Comment by e-kayrakli** [comment]
These leaks have been closed.

https://github.com/chapel-lang/chapel/pull/14079
https://github.com/chapel-lang/chapel/pull/14100
