### ISSUE TITLE
Streamline LLVM compilation by avoiding generation of C code

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#12738]
Compiling with `--llvm` generates some .c files that are then compiled. In particular the file `chpl_compilation_config.c` is generated and then compiled with a C compiler. It would require fewer steps, streamline the compiler, and possibly make it faster, to generate this information into the LLVM module containing all the other generated code.

For example, try:

`chpl --llvm --print-commands --savec=tmp hello.chpl`

`codegen_header_compilation_config` in `codegen.cpp` is one place to start looking at this.

**Comment by mnafees** [comment]
Can we close this now @mppf?

**Comment by mppf** [comment]
Closed by #13287 and  #13377. Thanks @mnafees !
