### ISSUE TITLE
Remove spec text saying exported functions can be prototyped

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#12740]
The spec section "Calling Chapel Procedures Externally" (currently 31.2.4) says that exported functions can be declared without a body.  This is not true in the current compiler and after consulting with Brad, we don't think we intend it to be true.  We should update the spec to reflect this

**Comment by bradcray** [comment]
PR #12741 offers a proposed fix for this.

**Comment by Shahwez-Ahmad** [comment]
I am  Beginner i  wanna work in this issue can you can you give me
