### ISSUE TITLE
Drop opaque domains/arrays from Chapel?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#12864]
As a Chapel implementer, I'm wondering whether we should drop opaque domains and arrays from the language due to lack of use and lack of confidence in the current implementation.  Their original inclusion in the language was motivated by wanting to support pointer-based structures using the domain/array notions.  However, in practice, such structures have typically assigned their own logical indices to such items and used rectangular, associative, or sparse domains and arrays instead.  Meanwhile, the opaque domain/array implementation has not been used much (in spite of having made users aware of it since Chapel's inception) and is not something we have much confidence in (e.g., see issue #12863).

As a result, this issue proposes dropping support for opaque domains and arrays.  We could always consider re-adding them later on if/when cases come up that would uniquely benefit from them.

**Comment by gbtitus** [comment]
I wouldn't personally miss these.  I've always had doubts we could implement support for them with performance good enough to attract programmers away from the purpose-built solutions you describe, which use logical indices and non-opaque domains and arrays.

**Comment by bradcray** [comment]
We have done this now.
