### ISSUE TITLE
Disable assignments from ranges to multidimensional arrays

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#12865]
The Chapel implementation currently permits assignments from ranges to multidimensional arrays.  This seems surprising to me and intuitively like something we should disallow (e.g. forcing users who want to do this to apply some sort of flatten() or reshape() transformation to one or the other to make them have compatible shapes).

Prototyping a check that would disallow this, it seems that just two groups of tests that use this as a convenience for filling arrays would fail if we made this change (i.e., there are no compelling use cases currently).

**Comment by bradcray** [comment]
Here's my branch that implemented this error: https://github.com/bradcray/chapel/tree/noArrRngAssigns

**Comment by vasslitvinov** [comment]
How would a user fill a multidimentional array if they cannot use `array = range;` ?

**Comment by bradcray** [comment]
As proposed in the issue, they could use a flattening iterator to view the array as a 1D value or a reshaping iterator to make the range act like a multidimensional value.  Or they could use a closed-form expression like:

```chapel
var A: [1..n, 1..n] real = [(i,j) in {1..n, 1..n}] lo + (i-1)*n + (j-1);
```

to achieve the equivalent of today's `var A: [1..n, 1..n] real = lo..hi;`.  That said, I don't believe that "today"'s behavior was particularly intended and believe it to be a corner case that wasn't guarded against.  I view it as being a shape mismatch that should be an error similar to how assigning a 1D array to a multidimensional array is.

To turn the question around, when is assigning a range to a multidimensional array particularly useful / meaningful?  The only cases I've seen are ones where the authors simply wanted to write some arbitrary data into the array, which I don't find particularly compelling (e.g., I'd just as soon fill the array with something like `[(i,j) in D] i*1000 + j;`).

**Comment by vasslitvinov** [comment]
If we do not consider `array = range;` an important functionality for filling an array, then I support this proposal.

BTW we could add a library function that fills an array with numbers in the order of a serial traversal of the array elements.

**Comment by ty1027** [comment]
> ... to achieve the equivalent of today's `var A: [1..n, 1..n] real = lo..hi;` ...

Just for my experience, I have tried it with chapel v1.19, but results in
a run-time error for multi-dimensional arrays ). Am I doing something wrong in the code (to reproduce the pattern discussed above)?

```
var n = 3;
var vec : [1..n] real = 1..n;
writeln( vec );  // 1.0 2.0 3.0

var mat : [1..n, 1..n] real = 1..n;
   // error: zippered iterations have non-equal lengths
//var mat2 : [1..n, 1..n] real = {1..n, 1..n};
  // error: type mismatch in assignment from 2*int(64) to real(64)
```
[(TIO version here)](https://tio.run/##dY3LDoIwEEX3/Yq7VKOgaFxA/BLjosERmsAUpxWjxm/Hgho2upjkzuOcyUvdUNV1rRYwdlhnSvW5pRwp9qso4gOEdBV2fZOpqxhPFU@Gk2kGxHHYLJGEWkfLN15r/8Xn@CHBgJGIlRR30zQkdEQQi/bGskOpWwJbXtD5EriKuPClUyqOP/rkj/8xzp79n/GNvzWE2rgA5yUMQztnCq6JPU5iayQzw36y3Uzh7aDrc9e9AA)

**Comment by bradcray** [comment]
You need to make sure the range has the same number of elements as the array.  E.g.,:

```chapel
var mat : [1..n, 1..n] real = 1..n**2;
```

**Comment by ty1027** [comment]
Ah I see... thanks!

While this seems very convenient for filling multi-dimensional arrays,  I am a bit afraid that
the meaning of assignment may become confusing depending on cases (though it may be
rare cases...)

```
var n = 3;
var vec: [1..n] real = 1..n;
writeln( "vec = ", vec );

var mat : [1..n, 1..n] real = 1..n**2;
writeln( "mat = \n", mat );

var rmat : [1..n, 1..n] range = 1..n**2;  // or an array of user-defined types that accepts a range?
writeln( "rmat = \n", rmat );
```
results:
```
vec = 1.0 2.0 3.0
mat = 
1.0 2.0 3.0
4.0 5.0 6.0
7.0 8.0 9.0
rmat = 
1..9 1..9 1..9
1..9 1..9 1..9
1..9 1..9 1..9
```

In the case of Python3, it seems that np.reshape() is needed on top of range():
```
import numpy as np
vec = np.zeros( 3 )
vec[:] = range( 3 )  # [ 0.  1.  2.]

mat = np.zeros((3, 3))
#mat[:,:] = range( 9 )
#mat[:] = range( 9 )
#-- error: "could not broadcast input array from shape (9) into shape (3,3)"

mat[:] = np.reshape( range( 9 ), (3,3) )
```
Personally, I would appreciate it if the filling of multi-dimensional arrays can be done
in a handy way for test scripts (like filling 1,2,...,n**2 above). Whichever of a reshape-based
or library-based approaches seem useful (but something shorter than [(i,j) in .....] ... approach).

> BTW we could add a library function that fills an array with numbers in the order of a serial traversal of the array elements.

**Comment by ben-albrecht** [comment]
>  they could use a flattening iterator to view the array as a 1D value or a reshaping iterator to make the range act like a multidimensional value

For archival purposes, would you consider the proposals in https://github.com/chapel-lang/chapel/issues/9693 or https://github.com/chapel-lang/chapel/issues/12222 as potential ways to provide a flattening iterator in the standard library or do you think this feature request deserves a standalone issue?

**Comment by bradcray** [comment]
I think they could serve that purpose, but for the common case of "make this variable a 1D linear sequence regardless of what it is", I think it might be more convenient to just have a general-purpose `flatten()` or `linearize()` iterator.  Specifically, I'm imagining that anything involving a reshape or reindex style interface would likely require some form of target indexing scheme whereas I think cases like this just want a "yield all the stuff as though it was a 1D sequence" type of interface.

**Comment by vasslitvinov** [comment]
Interesting: can we have lineralize() be a `ref` iterator so the user can do:
```chpl
var A: [1..n,1..m] int;
lineralize(A) = 1..n*m;
```

**Comment by bradcray** [comment]
Yeah, that's the idea.
