### ISSUE TITLE
chpl emits cstdlib-atomic errors in C99 mode during readExternC with CHPL_LLVM=system

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#12881]
### Summary of Problem
Bug report with 1.19.0 `chpl` compiler when compiling the following trivial program that uses HDF5 after building Chapel with various settings for `CHPL_HOST_COMPILER`, `CHPL_TARGET_COMPILER`, and `CHPL_LLVM`.
```chapel
// use_hdf5.chpl
use HDF5;
proc main() {}
```
My intent was to build a system-level LLVM package and use it with Chapel. It didn't work. When using `chpl` to build the trivial program above, the Bad builds in the table below all errored out during compilation step "readExternC" with a problem similar to:
```terminal
> chpl use_hdf5.chpl --print-commands --print-passes <HDF5_FLAGS>
    init
    parse
    checkParsed
    docs
<internal clang> ...
<chapel clang driver invocation> ...
<internal clang cc> ...
# parsing llvm command line options:  chpl-llvm-opts
In file included from $CHPL_HOME/runtime/etc/rtmain.c:23:
In file included from $CHPL_HOME/runtime/include/./stdchpl.h:42:
$CHPL_HOME/runtime/include/./atomics/cstdlib/chpl-atomics.h:66:15: error: unknown type name 'memory_order'
...
$CHPL_HOME/runtime/include/./atomics/cstdlib/chpl-atomics.h:67:10: error: use of undeclared identifier 'memory_order_seq_cst'
...
$CHPL_HOME/runtime/include/./atomics/cstdlib/chpl-atomics.h:72:3: warning: implicit declaration of function 'atomic_thread_fence' is invalid in C99 [-Wimplicit-function-declaration]
...
... more similar errors all related to C99 mode with C11's cstdlib atomics
...
fatal error: too many errors emitted, stopping now [-ferror-limit=]
11 warnings and 20 errors generated.
error: error running clang on extern block
```

### Results
To clarify, all of the builds except No.4 work for [almost] all programs that I fed to `chpl`, with the exception that the Bad builds emit the cstdlib atomics problem during step "readExternC".

Example: test/functions/promotion/promote-atomic-add-order.chpl compiles and runs successfully for Build No.{1..3,5,6}.

| Build | Status | `CHPL_LLVM` | LLVM Kind | `CHPL_HOST_COMPILER` | `CHPL_TARGET_COMPILER` |
| --- | --- | --- | --- | --- | --- |
| No.1 | Bad | `system` | 8.0.0 libc++ | `clang` | `gnu` |
| No.2 | Bad | `system` | 8.0.0 libstdc++ | `clang` | `gnu` |
| No.3 | Bad | `system` | 8.0.0 libc++ | `clang` | `clang` |
| No.4 | !Build | `llvm` | 8.0.0 libc++ | `clang` | `clang-included` |
| No.5 | Ok | `llvm` | N/A | `gnu` | `clang-included` |
| No.6 | Ok | `llvm` | N/A | `gnu` | `gnu` |

### Legend and Notes
- Using GCC 6.3.0
- Status
  - Ok
  - Bad = Build was successful. `chpl` works on almost all source file inputs, except this HDF5 program. The majority of this issue is devoted to this failure case.
  - !Build = Build was not successful. No.4 failed after building GMP, but I couldn't see any indications of what the actual issue was because GMP looked like it was built successfully. I didn't spend a lot of time debugging this configuration (and it should probably be its own bug report).
- LLVM Kind
  - 8.0.0 libc++ = My default build for LLVM is to use that project's libcxx and libcxxabi. It is possible that some other build configuration caused my LLVM build to not work correctly when used with Chapel.*
  - 8.0.0 libstdc++ = (No.2.) With the assumption that libc++ was causing the problem, I disabled it during the LLVM build process and used GCC's libstdc++ instead. It didn't work, so the problem is likely unrelated.

\* I haven't tried to use a distro-provided LLVM package if someone wants to give that a try and report back. I've basically given up at this point.

**Comment by ronawho** [comment]
I'm working on trying to reproduce this (no luck so far), but here's some maybe related thoughts:
 - https://github.com/chapel-lang/chapel/pull/12849 has removed HDF5's dependence on extern blocks, so this particular issue may not bite you anymore (but obviously we'd still like to get to the bottom of it.)
 - build` No. 4` may have been resolved with https://github.com/chapel-lang/chapel/pull/12611, which fixed some GMP cross-compilation issues.
 - In https://github.com/chapel-lang/chapel/pull/12079 (which made cstdlib atomics the default for llvm) I think I was assuming `CHPL_LLVM=llvm`. My assumption was if we have a host compiler that's new enough to build llvm then there should be system library support for cstdlib atomics (and we know our bundled clang-included has compiler support for them.) These assumptions may not  be true for `CHPL_LLVM=system` so we may need to do some more detection for whether cstdlib atomics are appropriate. I also did not think about extern blocks at all, and I'm not sure if that changes things

I think the core issue here is that the version of clang that's used to read extern blocks either does not support cstdlib atomics (or doesn't support them by default and maybe we need to throw a std flag.) Can you say a little more about how you built llvm and which compiler you used to build it?

Could you also run the preprocessor (cc -E) on the following program with the compiler used to build clang/llvm as well as clang-included? 
```c
__STDC_VERSION__
__STDC_NO_ATOMICS__
```

**Comment by BryantLam** [comment]
Notes to self. Clarifications tomorrow.
- Built Chapel master with `CHPL_LLVM=llvm`. Verified this build works correctly. Then took the internal LLVM build and subsequently built Chapel 1.19.0 with `CHPL_LLVM=system` using the internal LLVM build. Erroneous results replicated.
  - I don't think this is related to any host compilers. Preprocessor results will be provided anyway.
- Erroneous results also replicated for Hello World program when built with `chpl --llvm`. Original post's `use_hdf5.chpl` was a false lead and the two are related because they both used `<internal clang cc>` during readExternC (`use_hdf5.chpl`) or codegen (Hello World).

**Comment by mppf** [comment]
@BryantLam - could you check if your `$CHPL_HOME` that you built has the file `compiler/main/CLANG_SETTINGS` ? (It should not, and if it does, the question will be "how did it get there?").

**Comment by mppf** [comment]
> I haven't tried to use a distro-provided LLVM package if someone wants to give that a try and report back.

I do this all the time, on an Ubuntu 19.04 system. What I havn't tried is building my own LLVM (outside of `CHPL_LLVM=llvm`) and using that. I use the `apt-get` command show here: https://chapel-lang.org/docs/master/usingchapel/chplenv.html#chpl-llvm

**Comment by mppf** [comment]
Just to check, I went ahead and tried building the 1.19 release with CHPL_LLVM=system on the Ubuntu 19.04 system (with LLVM 7 and 8 packages installed already) and ran `chpl --llvm examples/hello.chpl`. Everything worked here for me without a hitch.

In Chapel 1.19, we are expecting `CHPL_LLVM=system` to use LLVM 7 (not 8). While some of us experiment with newer LLVMs and they may work, that could be part of the problem here.

Is there a particular reason you are using LLVM 8? Is there a particular reason not to use an OS packaged version of LLVM?

**Comment by mppf** [comment]
@BryantLam - I don't think I was ever able to reproduce this issue. Is it still a current problem? If so - we will need more information. If not, would you close it? Thanks.

**Comment by BryantLam** [comment]
Closing -- Not resolved, but irrelevant now. I stopped building with LLVM=system because of this bug, but I need to try again with the latest Chapel release when I have time.

**Comment by BryantLam** [comment]
Resolved. Tested with Chapel 1.25.1 and system LLVM 11.0.0 libc++ for:
```
CHPL_HOST_COMPILER=clang
CHPL_TARGET_COMPILER=llvm
CHPL_LLVM=system
```
Of note, this system LLVM is built to use libc++ by default, so I cannot use `CHPL_HOST_COMPILER=gnu`; `g++` does not know how to link against a different standard library like libc++.
