### ISSUE TITLE
Create perf tests to track distributed array creation

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#12930]
Create some comm-count and performance tests to track the amount of work that goes into setting up a distributed array. Today it's quite expensive and not an area we've spent much time optimizing with the thought that most distributed arrays will be long lived (and as a result we've spent our time optimizing operations on the arrays, not the creation itself.)

In some cases we've seen it's slower than we want (https://github.com/chapel-lang/chapel/issues/12926), and we have some UPC/SHMEM users who intuitively expect it to be less expensive than it is. We should improve our distributed array creation time, but before getting to that we should start tracking performance.

I think Block, Stencil, and Cyclic are the most important ones currently, but there may be others that are worth tracking. It's probably also worth having 2 variants for small (1M element) and large (1/4 mem) arrays.

__edit__:

 I don't see different comm counts between small and large arrays. 

It might be interesting to have comm counts for the array creation helpers like `newCyclicArr()` since they currently current a new dist domain per call.

**Comment by ronawho** [comment]
Not something for a nightly perf test, but here's a program that prints init/deinit counts for a dist domain and dist array:

```chpl
use CyclicDist, BlockDist;
use CommDiagnostics;
const size = {1..numLocales*here.maxTaskPar};

printDiags("", true);
startCommDiagnostics();
{
  //const D = size dmapped Block(size); // making param branch increases comm?
  const D = size dmapped Cyclic(startIdx=size.low);
  printDiags("dmap init");
  {
    var A: [D] int;
    printDiags("array init");
  }
  printDiags("array deinit");
}
printDiags("dmap deinit");

proc printDiags(str, header=false) {
  const d = getCommDiagnostics();
  const gets = +reduce (d.get + d.get_nb);
  const puts = +reduce (d.put + d.put_nb);
  const ons  = +reduce (d.execute_on + d.execute_on_fast + d.execute_on_nb);

  if header {
    writef("| %-15s | %-5s | %-5s | %-5s |\n", "config", "GETS", "PUTS", "ONS");
    writef("| %-15s | %-5s | %-5s | %-5s |\n", "-"*15, "-"*5, "-"*5, "-"*5);
  } else {
    writef("| %-15s | %5u | %5u | %5u |\n", str, gets, puts, ons);
  }
  resetCommDiagnostics();
}
```

`chpl dist-arr-comms.chpl --fast`

`chapcs11: chapel (master) $ ./dist-arr-comms -nl4`

| config          | GETS  | PUTS  | ONS   |
| --------------- | ----- | ----- | ----- |
| dmap init       |   561 |    15 |    48 |
| array init      |   114 |     3 |    12 |
| array deinit    |    12 |     0 |    12 |
| dmap deinit     |    12 |     0 |    21 |

`chapcs11: chapel (master) $ ./dist-arr-comms -nl32`

| config          | GETS  | PUTS  | ONS   |
| --------------- | ----- | ----- | ----- |
| dmap init       | 26909 |  1023 |  2232 |
| array init      |  4526 |    31 |   124 |
| array deinit    |   124 |     0 |   124 |
| dmap deinit     |   124 |     0 |   217 |

**Comment by bradcray** [comment]
It looks like my PR #13004 bumps down the number of gets slightly for the dmap init (which is really a dmap + domain init, right?), but doesn't change the other numbers:

`chapcs11: chapel (master) $ ./dist-arr-comms -nl4`

| config          | GETS  | PUTS  | ONS   |
| --------------- | ----- | ----- | ----- |
| dmap init       |   459 |    15 |    48 |
| array init      |   114 |     3 |    12 |
| array deinit    |    12 |     0 |    12 |
| dmap deinit     |    12 |     0 |    21 |

`chapcs11: chapel (master) $ ./dist-arr-comms -nl32`

| config          | GETS  | PUTS  | ONS   |
| --------------- | ----- | ----- | ----- |
| dmap init       | 22391 |  1023 |  2232 |
| array init      |  4526 |    31 |   124 |
| array deinit    |   124 |     0 |   124 |
| dmap deinit     |   124 |     0 |   217 |

Also interesting:  For the -nl 32 numbers, I see varying numbers of gets from one run to the next which seems surprising.

**Comment by e-kayrakli** [comment]
#14118 added a performance test, #14247 added a commcount test based on the first one. As per our offline discussion with @ronawho, I am closing this since we have a good amount of testing coverage in this area for now.

Any relevant performance discussion can go on under #14132

**Comment by ronawho** [comment]
@e-kayrakli I forgot about this before, but in #12926 we noticed that stencil had overheads compared to block. It may be worth adding a perf test for stencil too.

**Comment by e-kayrakli** [comment]
@ronawho -- will do
