### ISSUE TITLE
Always RVF indices from the Locales array

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#12933]
For patterns like `coforall loc in Locales do on loc` we should always be able to RVF loc because the Locales array is const. It's pretty natural to want then do something like `loc.id` instead of `here.id`, but if RVF is thwarted (because of a sync or something) you'll end up generating comm for that. This seems like a really common idiom that we should optimize.

In the example below there will be a get for each `loc.id` call, when we really don't want one. Switching to `here.id` eliminates the comm, but may not be as natural.

```chpl
use CommDiagnostics;

proc preventDCE(l) { }

startCommDiagnostics();
coforall loc in Locales do on loc {
    var s: sync int; s.writeEF(0); s.readFE(); // disables RVF for refs/const refs
    for 1..10 do preventDCE(loc.id); // should always be able to RVF loc
}
stopCommDiagnostics();
writeln(getCommDiagnostics());
```

In general we may want to have better analysis to be able to rvf the indices of any const array (or beef up RVF in general to not give up so easily in the presence of syncs) but iterating over the locales array is such a common idiom that it seems worth special casing if the general case is hard to solve now.

Related work in https://github.com/chapel-lang/chapel/pull/12932 / https://github.com/chapel-lang/chapel/issues/12920

**Comment by bradcray** [comment]
> we may way to have better analysis to be able to rvf the indices of any const array

I view the real action item here to have iterators of const arrays yield const indices back to the loop in which case it seems like this would just fall out.  Note that at present, iterations over arrays can be abused:

```chapel
const A: [1..3] real = [1.0, 2.0, 3.0];

for a in A do
  a = -a;

writeln(A);
```

I view this as being somewhat related to issue #10911.

**Comment by bradcray** [comment]
I added a new issue for the fact that iterators over arrays yield `ref`s to the array elements rather than `const ref`s in issue #12945.  That said, I'm having mild hesitations over whether that fix would be sufficient to RVF these values because I'm unsure whether we RVF things that are `const ref` rather than simply `const` today (but even if we don't, maybe we should define the language such that we could?).

**Comment by benharsh** [comment]
``const ref`` alone is not enough, I think we need to be sure it's "const ref to a const thing". If we're iterating over a truly ``const`` array of ``locale`` elements, then we're fine. We cannot perform this optimization if the array is just ``const ref`` (e.g. from a formal).

**Comment by ronawho** [comment]
@e-kayrakli resolved this by making the locales have value semantics (a record with always-rvf attached) in https://github.com/chapel-lang/chapel/pull/15149
