### ISSUE TITLE
Design: Domain vs. Range Slicing

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#12936]
As a Chapel language designer, in this issue I am proposing that we make a semantic distinction between range- and domain-based slicing in order to create a powerful and consistent array/domain algebra (albeit an arguably subtle one).

Specifically, I am proposing that an array expression sliced by a domain creates a new array expression whose domain is the slicing domain; while an array expression sliced by ranges creates a new array expression whose domain is the logical intersection of the ranges with the array's domain, inheriting the array's distribution.

Here are some behaviors that would be enabled by this proposal:

```chapel
// declare some local domains and arrays
const D = {1..n, 1..n};
const SubD = D[2..4, 2..4];
const SpsD: sparse subdomain(D) = ...;
var A: [D] real;
var ASps: [SpsD] real;

// declare some distributed domains and arrays
const DDist = newBlockDistDom(D);
const SubDist = DDist[2..4, 2..4];
const SpsDist: sparse subdomain(DDist) = ...;
var ADist: [DDist] real;
var ASpsDist: [SpsDist] real;

// slicing of local and distributed arrays using local and distributed domains
var B = ADist[SubD];  // B will be a local array with domain SubD
var C = ADist[SubDist];  // C will be a distributed array with domain SubDist
var E = A[SubD];   // E will be a local array with domain SubD
var F = A[SubDist];  // F will be a distributed array with domain SubDist

// slicing of local and distributed arrays using ranges
var G = A[2..4, 2..4];  // G will be a local array whose domain is {2..4, 2..4}
var H = ADist[2..4, 2..4];  // H will be a distributed array whose domain is {2..4, 2..4}

// slicing of sparse local and distributed domains using dense domains
var I = ASps[SubD];  // I will be a local dense array with domain SubD
var J = ASps[SubDist];  // J will be a distributed dense array with domain SubDist
var K = ASpsDist[SubD];  // K will be a local dense array with domain SubD
var L = ASpsDist[SubDist];  // L will be a distributed dense array with domain SubDist

// slicing of sparse local and distributed arrays using ranges
var M = ASps[2..4, 2..4];  // M will be a local sparse array whose domain is the intersection between SpsD and {2..4, 2..4}
var N = ASpsDist[2..4, 2..4]; // N will be a distributed sparse array whose domain is the intersection between SpsDist and {2..4, 2..4}
```

The things I like about this proposal are:

* like other cases in which a domain is used to drive a parallel expression (e.g., promotion by a domain), the resulting domain of the expression is the domain itself; this is consistent with the view of slicing as being like promoted indexing since `A[D]` viewed as a promotion essentially becomes `[i in D] A[i]` or `[i in D] A.this(i)`, which would be viewed as having `D` as its domain
* it provides ways to get either a dense or a sparse slice of a sparse array (whereas if domain slicing performed an intersection with the array's domain, we would always get a sparse slice)
* it provides ways to get either local or distributed results from a slice of an array (whereas if domain slicing always respected the array's domain / intersected with the array's domain, we would always get a result that matched the array
* I believe it optimizes for the common case (slicing with ranges) doing what you'd want expect

The main downsides of this proposal as I see it are:
* it's a rule to learn and understand / you can't be sloppy with domains
* it causes A[2..4, 2..4] and A[{2..4, 2..4}] behave differently which is subtle

That said, I think the power and consistency of the rule makes these downsides worthwhile.  Moreover, we could add a `--newbie` / `--perf-gotchas` mode in which the slice routines would give execution-time warnings about cases that seemed like likely user errors (e.g., "you're slicing this distributed 1..n, 1..n array by {2..n-1, 2..n-1} which will touch all of the locales and destroy your locality... are you sure you meant to do that?").

**Comment by bradcray** [comment]
Tagging @chapel-lang/perf-team because we've been discussing these semantic decisions a bit in our recent meetings.

**Comment by vasslitvinov** [comment]
I like having both options "retain the original distribution" and "switch to the slicing distribution".

I would suggest providing convenient syntax to "retain the original distribution" when slicing with a domain. With this proposal I'd have to write `A[(...D.dims())]`.

A convenience function, for example, would do it for me. Maybe we can even have one convenience function for each option, for the user to indicate their choice explicitly. Something like sliceRetainingOriginalDistribution and sliceSwitchingToSlicingDistribution, hopefully with shorter names.

**Comment by bradcray** [comment]
> With this proposal I'd have to write A[(...D.dims())].

Actually, for it to work with sparse/associative domains, you'd need to write `A[AD[D]]` (where I'm using `AD` as shorthand for A's domain).

I wouldn't object to supporting convenience functions, but think that's more of a library design issue than a language design issue (i.e., it's not something I'm interested in trying to solve here where my focus is really on how the language should be defined).  I'd also be inclined to wait until I had a compelling user-drive motivator rather than adding them just to have them.

**Comment by bradcray** [comment]
Belated thought that I should've listed in the original issue:  We've often described slicing as being similar to promoted indexing.  In that view, we could think of `A[D]` as meaning `[i in D] A[i]` or `[i in D] A.this(i)`.  Since promotions like this usually follow the domain doing the promotion, it's consistent that the domain of `A[D]` would be `D` rather than `A.domain[D]`.

**Comment by mppf** [comment]
> I believe it optimizes for the common case (slicing with ranges) doing what you'd want expect

I think that the compiler should just optimize statements like
``` chapel
A[i..j] = B[m..n]
```

to call some kind of `bulkTransfer` routine on the arrays without actually creating any slices at all. (And likewise for other assignment patterns like slice = array, array = slice).

I don't currently have an opinion about whether or not the other advantages you listed would make this change worthwhile.

**Comment by ben-albrecht** [comment]
> it's a rule to learn and understand / you can't be sloppy with domains

It's worth nothing that being sloppy with ranges vs domains can already result in performance hits today, due to overhead in domain creation.

> I'd also be inclined to wait until I had a compelling user-drive motivator rather than adding them just to have them.

While I don't have a specific example readily available, I think this would likely come up in graph applications. That said, I don't find the expression `A[(...D.dims())]` to be so bad. In fact, it's pretty intuitive once you understand the rules being proposed in this issue.

**Comment by bradcray** [comment]
> > I believe it optimizes for the common case (slicing with ranges) doing what you'd want expect
> 
> I think that the compiler should just optimize statements like
> 
> ``` chapel
> A[i..j] = B[m..n]
> ```
> 
> to call some kind of `bulkTransfer` routine on the arrays without actually creating any slices at all. 
> (And likewise for other assignment patterns like slice = array, array = slice).

Sorry if I was unclear, I don't literally mean "optimize" in the sake of "improve performance."  What I meant was "it makes what someone is arguably most likely to write (slicing by ranges) behave the way I think is most natural (it inherits the array's distribution rather than, say, creating a default rectangular domain from the ranges and then using that as the domain).

I don't disagree with your assertion, but I also think it's pretty unrelated to what I'm trying to nail down here (the semantics of slicing).  While I used assignments to variables in my examples (where you might say "who cares what domains/ownership these have because I think bulk transfer should just kick in and do the right thing"), the larger question is what should the behavior be for cases like the following:

```chapel
foo(A[D]);
foo(A[lo..hi]);

proc foo(X) {
  var Y: X.type;  // what type should Y have?
  var Z: [X.domain] real;  // what domain should Z have?
  forall x in X do  // which parallel iterator should be executed?
     sin(x);
}
```

This issue tries to answer those questions by defining the domain for both forms of slicing.

**Comment by vasslitvinov** [comment]
@bradcray do we have this on master now? i.e., should this issue be closed?

**Comment by bradcray** [comment]
It is on master now, in the sense that #12931 added it.  But note that this issue was opened after that PR in order to encourage discussion / make sure we agreed we did the right thing.  Personally, I believe that we did, and that we could close this issue, but I'm not certain whether there's consensus or even who has or has not thought about it.  I think it's appropriate for a "Are domains ready for 2.0" type of discussion, though it arguably isn't part of the library-based interface on domains.

(I also feel like there is some remaining TODO w.r.t. range-based slicing, but I can't recall what it was offhand.  It may have been a performance-related thing rather than a semantic thing).

**Comment by vasslitvinov** [comment]
An interesting aspect of the above straw-proposal is what to do when the user passes a range/ranges to `someArray.remapSlice()` . What is the behavior that one would expect intuitively?

**Comment by mppf** [comment]
@bradcray - I see the above comment / proposals A,B,C as exploring the tradeoffs between these three things:

1. consistency with a view of slicing being like promoted indexing
2. having `A[2..4, 2..4]` and `A[{2..4, 2..4}]` behave the same
3. the common case (slicing with ranges) perhaps doing what you'd want expect

Of these, I can understand why 1. and 2. are important. But it is not so clear to me why 3. is important. In particular, why would one would expect is that it would inherit the array's distribution rather than always being locally distributed? I was wondering if you could say more about your view on this consideration. Thanks.

**Comment by bradcray** [comment]
> In particular, why would one would expect is that slicing with ranges would inherit the array's distribution rather than always being locally distributed? I was wondering if you could say more about your view on this consideration. Thanks.

I generally think of slicing as "referring to data where it lives", so it would be odd to me if using the simplest form of anonymous slicing—applying ranges—caused the data to be localized.  I also think that it's better to mistakenly refer to a small slice where it lives, potentially inducing some unfortunate communication, than it is to mistakenly have a big slice be localized due to concerns like killing performance, hitting OOM errors, using one locale rather than all of them, etc.
