### ISSUE TITLE
`proc deinit` causes compile error "unable to resolve type"

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#12973]
### Summary of Problem
Related #12966 

Compiler `error: unable to resolve type` on Chapel 1.20 pre-release circa Apr 26, 2019.

The following code uses `owned A` and it works .. until I added `proc deinit`, and now it doesn't. Comment out `proc deinit` to get working behavior. Maybe the answer is a better compiler message because I have no idea what I did wrong.

### Steps to Reproduce
```chapel
// Basically a singly linked list.
class A {
  var x: int;
  var next: owned A; // <-- Error reported here.

  proc deinit() {
    while next {
      next = next.next;
    }
  }
}

proc test(type T) {
  var x = new T(1);
  var y = new T(2, x);
  var z = new T(3, y);
  writeln(z);
}

test(owned A);
```
```terminal
# Expected
{x = 3, next = {x = 2, next = {x = 1, next = nil}}}
```

**Edit:** Removed the irrelevant code for `proc clone`.

**Comment by bradcray** [comment]
OK, that's gotta be the weirdest bug I've seen in awhile.  Thanks for filing it.  @benharsh, @mppf: Any guesses why the presence of a deinit() would throw the compiler off for this program?
