### ISSUE TITLE
Update void variable documentation

### ISSUE THREAD

**Issue by daviditen** [chapel-lang/chapel#12991]
Once the `void` type is split into `void`/`nothing`/`none` in #12970 the doc/rst/technotes/voidVariables.rst document needs to be updated to reflect those changes.

**Comment by mppf** [comment]
Also reserved words in the spec for `nothing` and `none`

**Comment by mppf** [comment]
Also syntax highlighters

**Comment by bradcray** [comment]
I think it's time to merge the technote content into the spec now that we've gotten away from placeholder terms like `_void`.

**Comment by daviditen** [comment]
Closed with #13163.

**Comment by mppf** [comment]
@daviditen - I just noticed that we still have doc/rst/technotes/voidVariables.rst but now it's wrong. Does it just need to be deleted?

**Comment by daviditen** [comment]
Yes, it should be deleted, thanks for catching it. I can take care of that in a little bit.
