### ISSUE TITLE
Problems when using Chapel 1.19 along with GASNet PSM (OmniPath) substrate

### ISSUE THREAD

**Issue by carcarah** [chapel-lang/chapel#12990]
After Changing to version 1.19, but using Omnipath implementation, I'm randomly receiving the following error: `ERROR calling: gasnet_barrier_try(id, 0)`.

I know that the Omnipath implementation of GASNet is no longer supported by the current version of Chapel. However, I would like to use some features available only in version 1.19, and the cluster I use runs over an Omnipath network.

In order to use the PSM substrate (OmniPath), I proceed as suggested by Chapel's Gitter community:

`export CHPL_GASNET_ALLOW_BAD_SUBSTRATE=true`

`wget https://gasnet.lbl.gov/download/GASNet-1.32.0.tar.gz`

`tar xzf GASNet-1.32.0.tar.gz`

`rm -rf $CHPL_HOME/third-party/gasnet/gasnet-src`

`mv GASNet-1.32.0 $CHPL_HOME/third-party/gasnet/gasnet-src`

Then, I setup other variables:

`export CHPL_COMM='gasnet' export CHPL_LAUNCHER='gasnetrun_psm'` 
`export CHPL_COMM_SUBSTRATE='psm' export CHPL_GASNET_SEGMENT='everything'` `export CHPL_TARGET_CPU='native' export GASNET_PSM_SPAWNER='ssh'` 
`export HFI_NO_CPUAFFINITY=1`

Next, I build the runtime, etc.

However, when I run experiments, I randomly receive the following error:

`ERROR calling: gasnet_barrier_try(id, 0)`
 `at: comm-gasnet.c:1020`
 `error: GASNET_ERR_BARRIER_MISMATCH (Barrier id's mismatched)`

Which finishes the execution of the program.

I cannot find in GASNet documentation the reason for this error. I could only find a bit of information on GASNet's code.

This error is random. 

Do you know what's the cause of this problem?

Thank you all.

**Comment by ronawho** [comment]
As you know psm isn't officially supported in the 1.19 release. We also don't have access to any omnipath hardware to test on so unfortunately this might be hard to help with. 

What's the chapel program you're running when you hit this? Does it fail for a simple hello?

**Comment by carcarah** [comment]
I'm running a distributed branch-and-bound for solving permutation problems. It is a quite big program that also mixes c code.

Sometimes it also fails when running the distributed hello world. 

This error is quite random. The problem is that I launch a batch of tests, and then I have to re-run the ones that presented failures.

**Comment by ronawho** [comment]
Can you reproduce the issue with 1.18 and a hello world? Or is it specific to 1.19 with the old gasnet dropped in?

**Comment by carcarah** [comment]
I didnt face this problem when using 1.18. This problem started to happen when using 1.19 along with the old gasnet.

**Comment by ronawho** [comment]
Hmm, GASNet 1.32.0 is the version that was in Chapel 1.18 and I don't think there's anything in our shim to gasnet that would cause something like this. Can you verify that a hello seems to reliably work with 1.18 for the same setup? (I can't think of anything in the runtime that would have changed between 1.18 and 1.19 that would cause this, so I'm mostly just taking stabs in the dark.)

**Comment by carcarah** [comment]
Sure! The hello I use is the hello6 from the examples.

I received some warnings from the MPI as well. We could only find something
related to them on an Intel ominipath forum. So, I'm wondering whether
those problems are related to the network itself.

Em sex, 10 de mai de 2019 18:52, Elliot Ronaghan <notifications@github.com>
escreveu:

**Comment by carcarah** [comment]
Would it help if I could provide access to an Omnipath cluster? Best regards.

**Comment by ronawho** [comment]
Yeah, that'd be helpful

**Comment by carcarah** [comment]
Ok, I'll try to provide access for you.

**Comment by carcarah** [comment]
Hello Elliot.

Grid5000 agreed to grant you a guest access.

Could you send-me an e-mail to me, so we can manage the details?

**Comment by ronawho** [comment]
Not sure what email you want me to to use. Feel free to ping me at my github username @ gmail.com. It should be listed on my github profile too -- I'm never sure how careful to be with just listing my email publicly without some sort of obfuscation, but I get enough spam mail as it is, so I figured it can't hurt :)

**Comment by carcarah** [comment]
Ok, no problem! I'm contacting you via Gmail =)

**Comment by ronawho** [comment]
Alright, think we got this worked out. The summary is -- use ofi, not the psm conduit. Both ofi and psm are missing from the current release, however I think psm is dead and ofi is coming back in the next release or 2. From the GASNet 1.32 docs:

``` 
The psm-conduit is now DEPRECATED.
No further development of this conduit is anticipated.
It may be removed in a future release.

Users of Intel(R) Omni-Path Fabric are recommended to use ofi-conduit
```

I was able to reproduce the barrier issue with psm, but did not have much luck digging. It's possible there was a bug in the psm conduit so I switched to ofi (and then realized it was the recommended conduit for omnipath anyway.) That seems to be much more stable (1,000 trials of hello passed at 32 nodes, where 1/5 would fail with psm)

**Comment by ronawho** [comment]
For future references here's what I used to repro/build/reserved-nodes:

```bash
#!/usr/bin/env bash

# command to reserve nodes:
#   oarsub -q production -p "cluster='grvingt'" -l nodes=32 -t allow_classic_ssh -I

# setup env for Chapel 1.19 using ofi
setupChplenv() {
  module load gcc/6.4.0_gcc-6.4.0
  module load libfabric

  # Ignore our errors about ofi/psm not being supported
  export CHPL_GASNET_ALLOW_BAD_SUBSTRATE=true

  export CHPL_HOME=~/chapel-1.19.0
  if [ -d "$CHPL_HOME" ]; then
    CHPL_BIN_SUBDIR=`"$CHPL_HOME"/util/chplenv/chpl_bin_subdir.py`
    export PATH="$PATH":"$CHPL_HOME/bin/$CHPL_BIN_SUBDIR:$CHPL_HOME/util"
  fi

  # use gasnet-ofi -- from the psm docs "Users of Intel(R) Omni-Path Fabric are
  # recommended to use ofi-conduit"
  export CHPL_COMM='gasnet'
  export CHPL_COMM_SUBSTRATE='ofi'
  export CHPL_TARGET_CPU='native'
  export GASNET_QUIET=1

  # no idea if this is needed
  export HFI_NO_CPUAFFINITY=1

  # Use ssh spawning -- I couldn't get mpi spawner working
  export GASNET_OFI_SPAWNER='ssh'
}

downloadChpl() {
  setupChplenv

  if [ ! -d "$CHPL_HOME" ]; then
    cd ~/
    # Download Chapel 1.19
    wget https://github.com/chapel-lang/chapel/releases/download/1.19.0/chapel-1.19.0.tar.gz
    tar xzf chapel-1.19.0.tar.gz

    # Replace GASNet-EX with GASNet-1
    wget https://gasnet.lbl.gov/download/GASNet-1.32.0.tar.gz
    tar xzf GASNet-1.32.0.tar.gz
    rm -rf $CHPL_HOME/third-party/gasnet/gasnet-src
    mv GASNet-1.32.0 $CHPL_HOME/third-party/gasnet/gasnet-src
    setupChplenv
  fi
}

buildChpl() {
  setupChplenv
  downloadChpl
  cd $CHPL_HOME
  make -j `nproc`
  make test-venv
}

# run hello6 $NUM_TRIALS times using our start_test infrastructure
testChplHello() {
  export GASNET_SSH_SERVERS=$(uniq $OAR_NODEFILE | tr '\n' ' ')

  NUM_TRIALS=${1:-1}
  echo -e \#\#\# Running hello6 for $NUM_TRIALS trials \#\#\#
  loc=$(uniq $OAR_NODEFILE | wc -l)
  # update .numlocales and .good files for current number of nodes
  echo $loc > $CHPL_HOME/examples/hello6-taskpar-dist.numlocales
  rm -f ~/hello6-taskpar-dist.good
  for ((i = 0 ; i < $loc ; i++ )); do
    echo "Hello, world! (from locale $i of $loc)" >> ~/hello6-taskpar-dist.good
  done
  LC_ALL="" LC_COLLATE="C" LANG="en_US.UTF-8" sort ~/hello6-taskpar-dist.good > $CHPL_HOME/examples/hello6-taskpar-dist.good
  rm -f ~/hello6-taskpar-dist.good

  start_test $CHPL_HOME/examples/hello6-taskpar-dist.chpl --numtrials $NUM_TRIALS
}

setupChplenv
```

**Comment by ronawho** [comment]
My understanding for what works with 1.20 now:

```sh
#!/usr/bin/env bash

# command to reserve nodes:
#   oarsub -q production -p "cluster='grvingt'" -l nodes=32 -t allow_classic_ssh -I

# setup env for Chapel 1.20 using ofi
setupChplenv() {
  module load gcc/6.4.0_gcc-6.4.0
  module load libfabric

  # Ignore our errors about ofi/psm not being supported
  export CHPL_GASNET_ALLOW_BAD_SUBSTRATE=true

  export CHPL_HOME=~/chapel-1.20.0
  if [ -d "$CHPL_HOME" ]; then
    CHPL_BIN_SUBDIR=`"$CHPL_HOME"/util/chplenv/chpl_bin_subdir.py`
    export PATH="$PATH":"$CHPL_HOME/bin/$CHPL_BIN_SUBDIR:$CHPL_HOME/util"
  fi

  # use gasnet-ofi -- from the psm docs "Users of Intel(R) Omni-Path Fabric are
  # recommended to use ofi-conduit"
  export CHPL_COMM='gasnet'
  export CHPL_COMM_SUBSTRATE='ofi'
  export CHPL_TARGET_CPU='native'
  export GASNET_QUIET=1

  # no idea if this is needed
  export HFI_NO_CPUAFFINITY=1

  # Use ssh spawning (and avoid mpi) -- I couldn't get mpi spawner working
  export CHPL_GASNET_MORE_CFG_OPTIONS="--with-ofi-spawner=ssh --disable-mpi-compat"
  export GASNET_OFI_SPAWNER='ssh'
}

downloadChpl() {
  setupChplenv

  if [ ! -d "$CHPL_HOME" ]; then
    cd ~/
    # Download Chapel 1.20
    wget https://github.com/chapel-lang/chapel/releases/download/1.20.0/chapel-1.20.0.tar.gz
    tar xzf chapel-1.20.0.tar.gz

    # Replace GASNet-EX with GASNet-1
    wget https://gasnet.lbl.gov/download/GASNet-1.32.0.tar.gz
    tar xzf GASNet-1.32.0.tar.gz
    rm -rf $CHPL_HOME/third-party/gasnet/gasnet-src
    mv GASNet-1.32.0 $CHPL_HOME/third-party/gasnet/gasnet-src

    # Replace ofi launcher with older one (current version throws `-c 0`, which
    # isn't supported by older gasnets
    wget https://raw.githubusercontent.com/chapel-lang/chapel/release/1.19/runtime/src/launch/gasnetrun_common/gasnetrun_common.h
    mv gasnetrun_common.h $CHPL_HOME/runtime/src/launch/gasnetrun_common/gasnetrun_common.h

    setupChplenv
  fi
}

buildChpl() {
  setupChplenv
  downloadChpl
  cd $CHPL_HOME
  make -j `nproc`
  make test-venv
}

# run hello6 $NUM_TRIALS times using our start_test infrastructure
testChplHello() {
  export GASNET_SSH_SERVERS=$(uniq $OAR_NODEFILE | tr '\n' ' ')

  NUM_TRIALS=${1:-1}
  echo -e \#\#\# Running hello6 for $NUM_TRIALS trials \#\#\#
  loc=$(uniq $OAR_NODEFILE | wc -l)
  # update .numlocales and .good files for current number of nodes
  echo $loc > $CHPL_HOME/examples/hello6-taskpar-dist.numlocales
  rm -f ~/hello6-taskpar-dist.good
  for ((i = 0 ; i < $loc ; i++ )); do
    echo "Hello, world! (from locale $i of $loc)" >> ~/hello6-taskpar-dist.good
  done
  LC_ALL="" LC_COLLATE="C" LANG="en_US.UTF-8" sort ~/hello6-taskpar-dist.good > $CHPL_HOME/examples/hello6-taskpar-dist.good
  rm -f ~/hello6-taskpar-dist.good

  start_test $CHPL_HOME/examples/hello6-taskpar-dist.chpl --numtrials $NUM_TRIALS
}

setupChplenv
```
