### ISSUE TITLE
Get Instance of a class from its name

### ISSUE THREAD

**Issue by krishnadey30** [chapel-lang/chapel#13070]
I believe it will be very useful especially for the **unit test framework** if it were possible to get the instance of a class given its name as a string. This will help in calling the test methods of all classes in a suite.

```chapel
// Return the instance of methods in a class.
proc classInstance(string fname) var
  return __primitive("class instance", fname);
```

**Comment by lydia-duncan** [comment]
Whoops, should have mentioned - this is maybe not going to be possible without passing additional expected arguments to the init function for the class

**Comment by krishnadey30** [comment]
Yes, I forgot about that. We need to discuss this one again.
