### ISSUE TITLE
Specifying arguments with class type and any nilability?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#13088]
Should one be able to create a generic function argument that accepts both `MyClass` and `MyClass?`? Or `owned` and `owned?` ?

Currently, one can create functions generic on `owned`. When `owned` might be nilable or non-nilable, following the general strategy in #12614, `owned` will become "non-nilable owned" just as `MyClass` means "non-nilable MyClass".

I'm not sure if such functions will be generally important, but they are needed in the implementation of `owned` and `shared` and any user-provided memory management types.

**Comment by mppf** [comment]
Some possibilities:
 * if it only matters for the implementation of memory management, we could use type aliases and a convention like `_owned` is nilable or not, but `owned` is non-nilable
 * we could introduce syntax to mean "unknown nilability"
   * `owned??` `MyClass??`
   * `owned!?`
   * `nil? owned`

**Comment by mppf** [comment]
Arguably this can always be achieved with a `where` clause.

**Comment by bradcray** [comment]
> Should one be able to create a generic function argument that accepts both `MyClass` and `MyClass?`?

My intuition says "yes".

> Or `owned` and `owned?` ?

It seems like there are arguably three cases we might want to support:
* takes an owned nilable (but can be any class)
* takes an owned non-nilable (but can be any class)
* takes an owned class which can be either nilable or non-nilable
?

> `owned` will become "non-nilable owned" just as `MyClass` means "non-nilable `MyClass`".

This statement doesn't necessarily follow to me.  I could imagine an interpretation where `owned` says "owned nilable or non-nilable" and you'd have to say something like `owned ?C!` or `owned ?C?` to assert that it's an owned non-nilable or an owned nilable.

**Comment by mppf** [comment]
I probably should have said - `owned` is "non-nilable owned" just as `borrowed` is "non-nilable borrowed".

That is, in the implementation now, `arg:borrowed` will accept non-nilable classes of any type, and `arg:borrowed?` will accept nilable classes of any type. This seems reasonably intuitive to me, but we could also choose to make it so that `arg:borrowed` accepted nilable or non-nilable and `arg:borrowed!` accepted non-nilable while `arg:borrowed?` accepted nilable.

**Comment by bradcray** [comment]
It seems counterintuitive, or at least odd/surprising, to me that `owned` or `borrowed` would imply non-nilable in a generic context (why do I say that?  I guess because in a concrete context the `owned` keyword appears identically in `owned C` vs. `owned C?`, so if I dropped the class description to make it generic, it seems odd that `C` could be passed in but `C?` could not be).

What's the argument for the current interpretation beyond "that's what's implemented"?

**Comment by mppf** [comment]
> What's the argument for the current interpretation beyond "that's what's implemented"?

It started with `borrowed` and `borrowed?` which I justified to myself as analogous to `MyClass` and `MyClass?` - that is, the nilable version is decorated and the non-nilable version is what you get "without the question mark".

I felt I needed *some sort* of way to express these generic types in order to implement the various casts.

I'm open to switching to (say) `borrowed` (any borrow), `borrowed?` (any nilable borrow), and `borrowed!` (any non-nilable borrow) if that seems obviously better to you and @benharsh.

**Comment by bradcray** [comment]
I think your proposed switch seems reasonable and consistent with other things, and like that it provides support for the three choices rather than just two of them.

**Comment by mppf** [comment]
It sounds like @benharsh also supports that direction so I'll plan to migrate the implementation to it.

**Comment by mppf** [comment]
One problem with this is that `myClassVariable:borrowed!` might seem to be a cast to non-nil borrowed but it's actually casting to generic borrowed and then running `!` on the result.

**Comment by mppf** [comment]
I don't think that `owned!` is reasonable to mean a non-nilable `owned`. There are two reasons:
 1. `!` is a kind of mnemonic for "can halt" (e.g. `try!` and `myValue!`). But `someType!` can't halt and in fact makes the result safer (it can't be nil).
 2. `!` on types, if it exists at all, should return the same type as `!` on a value of that type. But `myOwned!` returns the borrow type - not the non-nilable owned type.

I am currently thinking that we should support `owned??` to mean generic-nilability owned, `owned` to mean non-nilable owned, and `owned?` to mean nilable-owned.

**Comment by mppf** [comment]
This post is based on a discussion I had with @benharsh 

This post assumes that the answer to #13161 is that `MyClass` means non-nilable and that the answer to #12917 is that `MyClass` means generic management.

Then, starting from https://github.com/chapel-lang/chapel/issues/13088#issuecomment-495762308 and elaborating a bit:


 * if you have

     ``` chapel
     owned MyClass
     owned MyClass?
     ```

     then the nilability goes next to the class type, rather than next to the owned (i.e. we don't write `owned? MyClass`).

 * So you might have functions like

     ``` chapel
     proc f(arg: owned MyClass)
     proc g(arg: owned MyClass?)
     ```

 * So if you wanted to make these generic on the class type, you might write

     ``` chapel
     proc h(arg: owned ?t)
    ```
    where you might expect `?t` to stand in for `MyClass` or `MyClass?`

 * But now, `?t` is merely giving a name to something, and if you didn't give the name to it, you'd expect it to be the same. As a result, you'd expect


     ``` chapel
     proc k(arg: owned)
     ```
     to accept `owned MyClass` as well as `owned MyClass?`.
 * As a result, it would be reasonable to expect `owned` is generic-nilabiilty. Ultimately, this comes from the role of `owned` as a class decorator, rather than as a class type itself.
 * The same argument applies to `shared` `borrowed` and `unmanaged`.


OK, so if `owned` is generic-nilability, I still have a pretty strong distaste for `owned!` at this point. What can we do about that?

First of all note that even though `owned?` has clear meaning, it might be better not to support that syntax at all, since we write `owned MyClass?` rather than `owned? MyClass`.

So, how can we express nilable `owned` on any class? Or not-nilable for that matter? @benharsh and I came up with two reasonable options that do not have the problems with `owned!`:

### Option 1: `class` token is a syntactic placeholder

Here we enable the use of `class` to mean "a class". To generalize a concrete declaration like `owned MyClass?`, we replace the concrete class name with literally `class`, so we get `owned class?`.

 * `proc f( arg: owned class )` accepts non-nilable owned any-class
 * `proc g( arg: owned class? )` accepts nilable owned any-class
 * `proc h( arg: owned )` accepts any-nilable owned any-class

We would probably want to further extend this idea to apply to accepting class-type arguments of generic management:
 * `proc a( arg: class )` accepts any-management non-nilable any-class
 * `proc b( arg: class? )` accepts any-management nilable any-class

### Option 2: `nonnil` and `nilable` type functions in the standard library

Here we add type functions to solve the problem. The rationale for using type functions instead of syntax is that this pattern has not come up that much (in my experience) outside of the implementation of `owned` and `shared` themselves.

 * `proc f( arg: nonnil(owned) )` accepts non-nilable owned any-class
 * `proc g( arg: nilable(owned) )` accepts nilable owned any-class
 * `proc h( arg: owned )` accepts any-nilable owned any-class

In this proposal, it would be reasonable to expect `nonnil` and `nilable` work for other types besides literally `owned` `shared` `unmanaged` `borrowed` (e.g. `MyClass`, `owned MyClass?`, etc). These might be useful when writing generic code.

**Comment by bradcray** [comment]
Taking @mppf's proposal just above outside of the management/nilability space for the time being and thinking of it in, say, a Chapel 1.16 context before these features were being pursued...  Have I got it right that the difference between, say:

```chapel
proc f( arg: class ) { ... }
```

and

```chapel
proc f(arg: object) { ... }
```

is essentially that the former is generic, so would get stamped out for any class type on which it's called whereas the latter is non-generic, so would just rely on dynamic dispatch for anything that happens within it (and, specifically, this probably means that not much can be done with it since `object` doesn't support many methods... whereas the former would support any `arg.foo` patterns that happened to resolve?)

If so, am I correct that we don't have any way to write such a pattern today short of making a routine very abstract and potentially filtering it with a where-clause?:

```chapel
proc f(arg) where isClassType(arg.type) { ... }
```

If so, that makes it seem reasonably attractive even before considering the potential benefits to nilability- / management-related issues (and similarly, I could imagine a `: record` constraint that ensured that a routine took a record).

Catching up with an earlier comment on the thread, Michael said:

> ! is a kind of mnemonic for "can halt" (e.g. try! and myValue!). But someType! can't halt and in fact makes the result safer (it can't be nil).

I don't disagree with this, but could imagine arguing that a `!` on a compile-time expression (like a type expression) was evaluated at compile-time and that any halting would occur there (i.e., a compiler error might occur if you violated the constraint).  So I don't know that this is inconsistent enough to give me much pause.

> But `myOwned!` returns the borrow type - not the non-nilable owned type.

This could just be vacation-brain talking, but why is this?

**Comment by mppf** [comment]
> If so...

I think you understand correctly. The only other thing to understand is that we have `borrowed` etc which are generic but for a specific management style.

> > But `myOwned!` returns the borrow type - not the non-nilable owned type.

> This could just be vacation-brain talking, but why is this?

We talked about it before - see https://github.com/chapel-lang/chapel/issues/12614#issuecomment-488006254 and the subsequent 3 comments.

It's very common to call methods on class-type variables, so you might have
``` chapel
proc f() {
  var x: owned MyClass? = ...;
   x.someMethod(); // Note here
   x.someOtherMethod();
}
```

But `x.someMethod()` is not allowed when `x` is nilable. So you have to write `x!.someMethod()`. But if `x!` on an owned resulted in an `owned MyClass` by value, we'd have ownership transfer. (It would return by value, not by reference, because `owned MyClass` and `owned MyClass?` are different types). Then after that `x` would store `nil` and the `x!.someOtherMethod()` call would fail...

I'm saying `x!` should return the same as `x.borrow()!` in this case because I think that's what's needed in the common case.

**Comment by mppf** [comment]
I think @bradcray  @benharsh and @mppf view the `:class` proposal from https://github.com/chapel-lang/chapel/issues/13088#issuecomment-515187152 as the best direction today.

We'd expect to generalize it to `proc f(arg:class)` `proc g(arg:record)` `proc h(arg:enum)`, and it also addresses the issue with `owned` variants.
