### ISSUE TITLE
Is string.length counting in codepoints or bytes?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#13087]
Right now, `string.length` returns the length of the string in bytes. At the same time, we've recently changed slicing, iteration, and character access to work with codepoints.

Should `string.length` return the number of bytes in a string or the number of codepoints?

(Note, this discussion moved here from #13084).

**Comment by mppf** [comment]
it seems to me that if indexing, iteration, and slicing use codepoint units by default, then so should `string.length`.

**Comment by mppf** [comment]
@bradcray said over at https://github.com/chapel-lang/chapel/pull/13084#issuecomment-495693575

> 
> I'm also surprised that string.length would return bytes rather than codepoints.  I imagine the main thing that something like string.length would be useful for would be:
> 
> for i in 1..mystring.length do
>   ...mystring[i]...
> 
> Since default indexing is in codePoints, I'd expect `s[4..#len]` to also want codePoints, not bytes (though I'd really expect to write such patterns as `s[start..]` so that it'd remain independent of whether the unit of start is a codePointIndex or a byteIndex).
> 
> What's the argument / use case for when it would prefer bytes?

**Comment by bradcray** [comment]
It occurs to me that if we made `.length()` a paren-ful function, we could have it take an argument to indicate which units to use, defaulting to codepoints as its units.  I thought of this offline and am bummed to see that it is paren-less currently (== more pain if we change its signature, so maybe we shouldn't).

**Comment by mppf** [comment]
@dmk42 - I just wanted to make sure you are aware of this issue.

**Comment by dmk42** [comment]
Yes, I am aware, thanks.  No matter which way this gets decided, 838 files will need to be inspected to see whether their use of string length fits whatever we decide.

**Comment by bradcray** [comment]
Given that we've only had ascii strings until recently, it seems almost certain that the bulk of those files will be fine and could just be verified by testing rather than through manual inspection?  (and even newer tests seem like they could be as well... if their use is wrong it seems like they'd either generate bad output or a valgrind error?).

**Comment by dmk42** [comment]
No, because there are some cases where using the wrong kind of length will work for now, but might break if anything gets modified in the future.

**Comment by mppf** [comment]
> No, because there are some cases where using the wrong kind of length will work for now, but might break if anything gets modified in the future.

I'd only be concerned about that for code in modules/ and not for code in test/. If the test/ code changes in the future, we'll fix it then.

**Comment by dmk42** [comment]
Certainly anything in release/examples will need to be fixed, since those are examples.

**Comment by mppf** [comment]
> It occurs to me that if we made .length() a paren-ful function, we could have it take an argument to indicate which units to use, defaulting to codepoints as its units. I thought of this offline and am bummed to see that it is paren-less currently (== more pain if we change its signature, so maybe we shouldn't).

I'd be open to making it paren-full.

Right now we also have string.size. Should that continue to be a synonym for string.length? We could keep string.size paren-less and make length paren-full.
