### ISSUE TITLE
forall loops over ranges / domains yield non-const indices

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#13091]
### Summary of Problem

When using a forall loop to iterate over a range or domain, the yielded indices should be `const` as with a for-loop, yet in practice they seem to be modifiable.

### Steps to Reproduce

**Associated Future Test(s):**
[`test/parallel/forall/const-indices.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/parallel/forall/const-indices.chpl
          ) #13090 
(moved to `test/parallel/forall/checks/const-indices-blc.chpl`)
`test/performance/vectorization/vectorizeOnly/constChecking/standaloneConstChecking.chpl`
`test/statements/elliot/loops/modifyIndicesStandalone.chpl`

### Configuration Information

- Output of `chpl --version`: `chpl version 1.20.0 pre-release (7eb486b)`

**Comment by vasslitvinov** [comment]
Not so surprising. With a for-loop, the AST contains:
```
move Symbol for user index variable, Symbol for compiler-introduced _indexOfInterest
```
Resolution of this CallExpr goes through `resolveMoveForRhsSymExpr()`,
the case where rhsSym->hasFlag(FLAG_INDEX_OF_INTEREST)
and lhsSym->hasFlag(FLAG_INDEX_VAR). There, it does lhsSym->addFlag(FLAG_CONST).

For a forall-loop over a standalone iterator, there is no compiler-introduced _indexOfInterest. The user index variable is used directly. So there is no `move` and resolveMoveForRhsSymExpr() is not invoked.

I suspect that a "maybe-parallel" `[]`-loop over a serial iterator has the same issue.

In the zippered / leader-follower case, the user index variable is used in the **follower** loop. A follower loop is a for-loop, so things work correctly I believe.

To fix the issue - for both the standalone and serial cases - we need to take this piece of resolveMoveForRhsSymExpr():
```C
      if (isReferenceType(rhsType)                == false &&
          isTupleContainingAnyReferences(rhsType) == false &&
          rhsType->symbol->hasFlag(FLAG_ARRAY)    == false &&
          rhsType->symbol->hasFlag(FLAG_COPY_MUTATES) == false) {
        // ... then mark LHS constant.                                                                    
=>      lhsSym->addFlag(FLAG_CONST);
      }
```

and copy it into `resolveIdxVar()`.

* We need to translate the above code from looking at `rhsType` to looking at the iterator yield type and return intent (both available in `resolveIdxVar()`),
* We should test corner cases, ex. the standalone iterator yielding arrays, tuples, ...

**Comment by bradcray** [comment]
Sounds like we've got the perfect person to improve this!  :)

I meant to note earlier, but this seems thematically related to #12944, though I'm fairly certain the work to fix that one is fairly different (and related to the fact that our iterators always yield `ref`s).
