### ISSUE TITLE
Configs incorrectly permitted in local scopes within modules

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#13108]
### Summary of Problem

The Chapel compiler currently permits `config` declarations in local scopes to a module, but I don't think that this is what's intended (based on the language specification, my sense of things, and my memory.  Rather, I think it should generate an error, similar to configs declared within a procedure.

### Steps to Reproduce

**Associated Future Test(s):**
[`test/compflags/configs/configNotModScope.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/compflags/configs/configNotModScope.chpl
          ) #13107

### Configuration Information

- Output of `chpl --version`: `chpl version 1.20.0 pre-release (f8efa5c)`

**Comment by DanilaFe** [comment]
This test passes on `main`, and config variables not at module scope are disallowed:

```
configNotModScope.chpl:5: error: configuration variables are allowed only at module scope
configNotModScope.chpl:10: error: configuration variables are allowed only at module scope
```

Closing as completed.
