### ISSUE TITLE
Design and implement `import` as alternative to `use`

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#13119]
As a Chapel programmer coming from Python who's sensitive to protecting my namespaces, I would like Chapel to support an `import` statement similar to Python's and opposite to Chapel's `use`.  That is, by default, no symbols would be available without full qualification by default.  Thus, `import M;` would be similar to `use M only;` or `use M except *;` in Chapel today.

**Comment by mppf** [comment]
I think that `public import` should make the module symbol itself visible in other modules while the a `public use` would only make the use'd symbols visible in other modules.

From https://github.com/chapel-lang/chapel/issues/13524#issuecomment-514639760

> We could also consider enabling this behavior for public use L only; but my concern with enabling it for public use L; or public use L only someFunction would be that those statements are trying to make available specific functions within L but not the fact that they are implemented in L itself. If we chose to make public use not make the module symbol itself re-exported, while import did, that seems like something that might be a useful difference between import and use. This seems pretty intuitive to me.

**Comment by bradcray** [comment]
@mppf: I'm not familiar enough with Python to know:  Does the behavior you propose for `import` match Python enough that it would seem natural to programmers coming from there?

**Comment by mppf** [comment]
@bradcray - I think this would be similar to Python's `import` statement. *However*, I don't know if there is a difference between a "public" import and a "private" one (or how to write that at all in Python). But, it does look like Python's `import` statement does seem to make the fact that the module was imported publicly visible by default:

Here is an example:
``` python
# mymodule.py

import othermodule

def myfn():
  print("myfn")

print ("Hello from mymodule")
```

``` python
# othermodule.py

def otherfn():
  print("otherfn")

print ("Hello from othermodule")
```

``` python
# program.py

import mymodule

mymodule.myfn()
mymodule.othermodule.otherfn()
```

```
$ python3 program.py 
Hello from othermodule
Hello from mymodule
myfn
otherfn
```

**Comment by mppf** [comment]
@bradcray - if it's not obvious, accepting my proposal would make moving to `use` and `import` be a breaking change compared to the current `use` world.

**Comment by lydia-duncan** [comment]
I just opened #13831

**Comment by bradcray** [comment]
Even though there's an issue remaining here, I think it's a relatively minor one that stands OK on its own, and that we can close this epic now.
