### ISSUE TITLE
Arrays of tuples of arrays result in nil dereferences

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#13149]
### Summary of Problem

Arrays of tuples of arrays don't seem to work as @ben-albrecht identified in issue #7628.  When we close this issue, we should also see whether we can close that one by testing some of the other patterns Ben identified to see if they work.

### Steps to Reproduce

**Associated Future Test(s):**
[`test/arrays/bugs/arrOfTupleOfArr.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/arrays/bugs/arrOfTupleOfArr.chpl
          ) #13148

### Configuration Information

- Output of `chpl --version`: `chpl version 1.20.0 pre-release (cabe0cc)`

**Comment by vasslitvinov** [comment]
The compiled code fails valgrind with "Conditional jump or move depends on uninitialised value(s)" in `chpl__buildArrayExpr2()`, prior to hitting the nil check. In case this helps when we investigate.

**Comment by bradcray** [comment]
#15759 seems related to this, maybe a duplicate though its future is more detailed.

**Comment by bradcray** [comment]
This was resolved by David Longnecker in #16802.  All hail @dlongnecke-cray, my new hero!
