### ISSUE TITLE
bool value does not match arg:bool(?w)

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#13142]
See test/types/bool/resolution/resolveQueryTypeW.chpl (added in PR #13143)

``` chapel
proc bar(const ref x: bool(?w)) {
  writeln("In bool(", w, ") version of bar()");
}

var b: bool;
bar(b);
```

fails to compile. After PR  #13133, a version with `bool(?)` rather than `bool(?w)` will compile. But that is unfortunate because the only difference between a `?` type query and `?w` is that `?w` is naming the size.

The reason it is this way is that the Chapel compiler doesn't currently have a way to detect the size of the C type `bool`. I suspect that this problem can be avoided under the LLVM backend.

**Comment by bradcray** [comment]
I think a more general way of stating this issue could be "the compiler should always expose the size of `bool` to the programmer as a `param` value."  (e.g., `param w = numBits(bool);` should also work).

That said, I consider both efforts to be reasonably low-priority in the grand scheme of things (I don't think users have been that hindered by not being able to `param`-know the width of `bool` relative to other things).

**Comment by bradcray** [comment]
If we were to pursue padding/alignment features (e.g., issues #12279 and #10771), I'd also propose removing the `bool(w)` variants of bools which would remove the need for the `bool(?w)` pattern.

**Comment by mppf** [comment]
@bradcray - I'm just coming across this issue again. I really like the idea of removing `bool(w)` variants of bools in favor of an alignment feature. However, doing so would be a breaking language change. Should we make `bool` with non-default width unstable for now, or something?

**Comment by mppf** [comment]
Or, maybe we could just implement `@aligned 64` etc since there is agreement that is a reasonable use of an attribute, and then deprecate `bool(w)`.

**Comment by mppf** [comment]
I've created #21002 to focus on the question of if we should deprecate `bool(w)`.
