### ISSUE TITLE
syntax error: near 'none'

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#13179]
Sometime between Chapel 1.19.0 and master as of May 28, this code no longer compiles:

```chapel
enum log_level {
  none = 0,
  debug = 1
}

proc main() {
  var e = log_level.debug;
  writeln(e);
}
```
```terminal
syntax error: near 'none'
```

I don't mind breaking changes at this moment, but this error is weird. I think either a new symbol for `none` was introduced somewhere in the standard libraries, or a new reserved keyword appeared, but shouldn't the compiler be smarter about when and where keywords can be allowed to appear, especially for a keyword-happy language like Chapel?

**Comment by mppf** [comment]
@daviditen - what do you think?

**Comment by bradcray** [comment]
@BryantLam : Sorry for the hassle.  `none` is now a reserved word in Chapel, used to represent the "unit type" notion of `void` #12970.

> shouldn't the compiler be smarter about when and where keywords can be allowed to appear, especially for a keyword-happy language like Chapel?

I'm not sure what you're looking for here.

**Comment by daviditen** [comment]
I agree the error could be nicer.  I think it should be able to have the same message as if you replaced `none` with `true` in the example code: `error: attempt to redefine reserved word 'none'`.

**Comment by BryantLam** [comment]
> 
> 
> I agree the error could be nicer. I think it should be able to have the same message as if you replaced `none` with `true` in the example code: `error: attempt to redefine reserved word 'none'`.

Maybe I'm barking up the wrong tree, but why wouldn't 'true' be valid either? I don't think the code I had is any more ambiguous had `none` been replaced with `true` because its use is protected through the enum `log_level` in the general case.

**Comment by BryantLam** [comment]
Never mind. I can see why that would be problematic for something like.
```chapel
class C {
  var true = false;
}
```
which would be very confusing in the long term. Carry on.

**Comment by bradcray** [comment]
Keep in mind that many of these things only recently (as of 1.19 in the case of `true`, `false`, `bool`, `int`, etc.) became reserved words whereas they had not been before.  We used to permit them to be redefined so that you could set true to false and the like, but recent feedback from users (and comparison to other languages) suggested we were better off reserving them and adding specialized error messages to avoid confusion.
