### ISSUE TITLE
`mason test` exit code

### ISSUE THREAD

**Issue by tjstavenger-pnnl** [chapel-lang/chapel#13207]
In Chapel 1.19.0, when `mason test` is run with test failures, the exit code is zero.

```
$mason test
...
--- Summary:  23 tests run ---
-----> 15 Passed
-----> 8 Failed
$ echo $?
0
```

It would be helpful in automated build systems to have a non-zero exit code in this case. Perhaps even just return the number of failed tests? 

Related to #7106

**Comment by bradcray** [comment]
@oplambeck: This should be an easy bug to pick up, either in your spare time this sprint or as a short task in the next.  Tagging @spartee / @ben-albrecht for reference.

**Comment by oplambeck** [comment]
Discussed this with @Spartee, wondering what exit codes we should provide instead. For an example that fails two tests, returning an exit code of 2 would conflict with the special exit code meaning (https://www.gnu.org/software/bash/manual/html_node/Exit-Status.html). 

In this case does it make sense to only return exit code 1 regardless of amount of tests that failed?
@bradcray @ben-albrecht

**Comment by bradcray** [comment]
My gut reaction was to use `1` regardless of the number of failures, but I have to admit to not being an expert at status codes, and have probably abused the standard ones lots in my life...

**Comment by oplambeck** [comment]
Should be fixed with PR #13208 I just opened.

**Comment by bradcray** [comment]
Speedy!

**Comment by oplambeck** [comment]
@tjstavenger-pnnl Issue has been resolved,  mason tests will now return exit code of 1 if any tests fail and 0 if all pass.
