### ISSUE TITLE
Improve testing coverage for the `list` type

### ISSUE THREAD

**Issue by dlongnecke-cray** [chapel-lang/chapel#13224]
Testing coverage for the new `list` type is far from perfect. In particular, here are some areas where testing should be improved:

- Classes, with particular care taken to differentiate/cover separately `owned, borrowed, unmanaged, shared`.
- Records containing lists.
- Nested list instantiations, IE `list(list(int))`.
- Testing for the `these` operator.

**Comment by bradcray** [comment]
One good way to add some more tests (which may or may not help with the list above) would be to add deprecation warnings for the current array-as-vec capabilities, run the testing system, and then rewrite any tests that encounter the warnings to use the new list type.  That would ensure that there is at least as much testing weight on the `list` type as there had been on the capability that it's replacing.

**Comment by dlongnecke-cray** [comment]
Closing this. We've got a myriad different tests at this point, and have improved support for (non-nilable) classes significantly.
