### ISSUE TITLE
function promotion prevents return value optimization

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#13234]
### Summary of Problem
Here's an unsophisticated reproducer that shows RVO not triggering when function promotion is used.
```chapel
var globalId: atomic int = 0;

record R {
  var id: int;

  proc postinit() {
    id = globalId.fetchAdd(1);
  }

  proc writeThis(f) {
    f <~> id;
  }
}

proc copyRhs(x: R, y: R): R {
  return y;
}

proc main() {
  var a: R;
  var b: R;
  var c = copyRhs(a, b);
  writeln((a, b, c));

  var aa: [1..4] R;
  var bb: [1..4] R;
  var cc = copyRhs(aa, bb);
  writeln((aa, bb, cc));
}
```
```terminal
(0, 1, 2)
(3 4 5 6, 7 8 9 10, 17 18 15 16)
```
`chpl version 1.20.0 pre-release`

The `cc` result isn't some permutation (due to a `forall`) of `11 12 13 14` as I'd expect but is instead some permutation of `15 16 17 18`.

I thought I'd point it out since RVO is pretty important in the case of large-array promotions.

**Comment by BryantLam** [comment]
Due to function promotion's use of `forall`, I suppose there's technically a data race on `globalId` that someone should fix.

**Comment by bradcray** [comment]
> The cc result isn't some permutation (due to a forall) of 11 12 13 14 as I'd expect but is instead some permutation of 15 16 17 18.

Is the correct output a permutation of 11 12 13 14 or of 7 8 9 10?  (I'm thinking the copy initializer should be invoked, not the default initializer, in which case the global atomic shouldn't come into play?)

@mppf / @benharsh: I'm curious whether you'd consider this a bug (something we believed we'd implemented that isn't working as expected) or an unimplemented feature (something that we knew still needs to be implemented).  Given the general state of arrays w.r.t. initializers, I'd guess the latter, but am not confident.

**Comment by mppf** [comment]
>  (I'm thinking the copy initializer should be invoked, not the default initializer, in which case the global atomic shouldn't come into play?)

I'd expect an `init=` to run a `postinit`.

I don't know offhand (without digging into the issue) if we would have expected this to be working. Would have to dig into the promotion code to understand more.

**Comment by benharsh** [comment]
I think this is another case where arrays default-initialize then use assignment. So the code is really more like:
```chpl
var cc : [1..4] R; // creates 11..14
cc = copyRHS(aa, bb); // overwrites with 15..18
```

I think it's likely that we can achieve the expected output with an array ``init=`` implementation for iterator records.

**Comment by bradcray** [comment]
> I'd expect an init= to run a postinit.

Oh, that's an interesting point.  I wrote up the array version manually and got 7 8 9 10, which is why I asked ([TIO](https://tio.run/##dZA9b4MwEIZ3fsU72hJCjdQJ0kodu6JuUQZjTLFEbGSctKhK/zo9LhClX4s53T3vg8@6Vb3ppumkAl47X6nuuc6hoj9YDesiHnBXJEkw2ocaJT4SYGYtUTSmEdAHr9H7IVpno5DMgAjKrsqsMVG3T3UtNrKg8fmaews2mpfWDqJZkw22n4@Uv4CEMqh9P5btIN5zlClGOmW@XCiYeAwOY/EXvNsv/FzIy@ef1EFZt9x/3lGRv1jq6qbWtNj6A5Wi4o14j84J7qTQUvLbsIdEu02W3e9vfNXvnv4mnj0/1dwjOdvP0/QF))  @benharsh, do `init=` routines call `postinit()` currently?  (it's not obvious to me whether or not they should... I feel like I hadn't really thought about the question before)

**Comment by benharsh** [comment]
``init=`` generally appears to be calling ``postinit()`` currently. I'm not sure why it doesn't happen in your TIO reproducer.
