### ISSUE TITLE
Deprecate calls to "array-as-vec" operations and replace with `list` calls where possible

### ISSUE THREAD

**Issue by dlongnecke-cray** [chapel-lang/chapel#13233]
The `list` type was introduced in #13173. The original goal motivating the development of the `list` type was the deprecation of "array-as-vec" methods on arrays such as `push_back`. Now that the `list` type is part of the standard library, follow through with the effort to deprecate such "array-as-vec" methods on arrays. Additionally, see how many such uses can be easily replaced by use of a `list` instead.

**Comment by dlongnecke-cray** [comment]
Just to get the ball rolling, I'm looking to deprecate the following array methods:

- push_front
- push_back
- pop_front
- pop_back
- insert
- remove
- clear

Any methods that modify the array's domain that I've missed?

**Comment by mppf** [comment]
I'd look for uses of `chpl__assertSingleArrayDomain` and deprecate any of those. (Although some are for array-as-map / domain-as-set which is presumably something you'll deprecate later).

**Comment by dlongnecke-cray** [comment]
The `test/library/packages/UnitTest` directory is proving difficult to deprecate due to how the `UnitTest` module works. I don't think it will be possible for the tests in this module to pass without rewriting `modules/packages/UnitTest.chpl` to avoid the use of "array-as-vec" operations.

I'll tackle this last.

**Comment by mppf** [comment]
@dlongnecke-cray - it may be reasonable to complete the deprecation and for these tests to include the deprecation warning in their .good files for the time being. Of course UnitTest.chpl will need to be updated at some point, but that does not necessarily need to block the rest of this effort.

**Comment by dlongnecke-cray** [comment]
Closed after discussion with @bradcray. The bulk of this effort can be considered complete.
