### ISSUE TITLE
Type alias from scoped type does not support new

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#13245]
I would expect the following program to compile and run without error.
However it produces an error about being unable to resolve `R.init`.
In my original use-case, R was also generic. However that does not seem to matter for this problem.

``` chapel
module A {
  record R {
    var field:int;
  }
}

module B {
  proc acceptsType(type t) {
    var x = new t();
    return x;
  }
}

module C {
  proc main() {
    var x = B.acceptsType(A.R);
    writeln(x, ": ", x.type);
  }
}
```

It's possible to workaround the problem with `use` statements.

**Comment by DanilaFe** [comment]
It's no longer possible to access sibling modules like without importing them or having them be nested in `C`. However, making those adjustments -- and adding a cast from `x.type` to string to satisfy `writeln` -- the programs compile fine.

Variant A:
```Chapel
module A {
  record R {
    var field:int;
  }
}

module B {
  proc acceptsType(type t) {
    var x = new t();
    return x;
  }
}

module C {
  import A;
  import B;

  proc main() {
    var x = B.acceptsType(A.R);
    writeln(x, ": ", x.type : string);
  }
}
```

Variant B:

```Chapel
module C {
  module A {
    record R {
      var field:int;
    }
  }

  module B {
    proc acceptsType(type t) {
      var x = new t();
      return x;
    }
  }

  proc main() {
    var x = B.acceptsType(A.R);
    writeln(x, ": ", x.type : string);
  }
}
```

Both compile and print `(field = 0): R`. I'll be opening a regression test PR and closing.
