### ISSUE TITLE
Single-locale interop: support exporting Chapel strings to Python

### ISSUE THREAD

**Issue by dlongnecke-cray** [chapel-lang/chapel#13266]
Breaking apart a bigger issue into smaller pieces, after we have support for interop between Chapel strings and C, we need to add support for Python.

Since the current strategy is to export Chapel strings to C as `const char*`, this may just fall out naturally.

**Comment by lydia-duncan** [comment]
Turns out due to the magic of Cython (which understands that `int8_t *` *can* be converted to Python's `bytes` type), this was already working.  Yay!

**Comment by bradcray** [comment]
So wait, you're saying that a 3-sprint old task has been done for that long?  Sigh...

Want to take on the multi-locale string interop story in this one's place?

**Comment by lydia-duncan** [comment]
Sure, but after going back to the launcher stuff.  It's entirely possible the multi-locale one will similarly fall out . . .

**Comment by bradcray** [comment]
I'm not holding my breath that it will (we don't even have multi-locale C-Chapel interop for strings yet, do we?)  But if I'm wrong about that, it seems like it'd be worth the 10 minutes it'd take to check given that this 2-point task turned out to be closer to 0?

**Comment by dlongnecke-cray** [comment]
Since, (much to my eternal shame) I am the reason this task took so long, I will take it upon myself to do a mockup right now (as soon as I finish reviewing `map`).

**Comment by dlongnecke-cray** [comment]
Update:

```
dlongnecke$ chpl --library --savec dump --dynamic Test.chpl --library-makefile
Test.chpl:8: error: Multi-locale libraries do not support return type: c_ptr(int(8))
```

Looks like it will require (as we speculated), at the very least adding support for `int8_t*` buffers.
