### ISSUE TITLE
Rebuild "libchpllaunch" as PIC when CHPL_LIB_PIC=pic

### ISSUE THREAD

**Issue by dlongnecke-cray** [chapel-lang/chapel#13263]
The Chapel runtime is automatically rebuilt as PIC when `CHPL_LIB_PIC=pic`, however "libchpllaunch" is not. Classically, there was never a need for this, but now multi-locale libraries must also link against "libchpllaunch". 

The "chpllaunch" library should be automatically rebuilt the first time the value of `CHPL_LIB_PIC` is changed to a new supported value, as is done for "chplrt".

**Comment by dlongnecke-cray** [comment]
A fix for this is ready https://github.com/chapel-lang/chapel/pull/13289, but I'm going to hold off on merging until after CHIUW.

**Comment by BryantLam** [comment]
Is there a downside to just always making libchplaunch be PIC? It doesn't seem performance critical.
