### ISSUE TITLE
internal error when incorrectly using init= on record with forwarded field

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#13277]
Bug. Low priority because it's code that shouldn't compile.

Internal compiler error.  Error messages.

The following code will correctly emit a compiler error if `forwarding` is omitted.

The code, as is, will instead emit an interal compiler error. If the `proc init=` is added, the code will compile successfully, so it's likely just an unhandled case in the compiler.

```chapel
record R {
  forwarding var i: int;
}

proc main() {
  var r: R = 5;
}
```
```terminal
internal error: UTI-MIS-0602 chpl version 1.20.0 pre-release
```

**Comment by bradcray** [comment]
Tagging @benharsh in hopes that this is a quick fix.

**Comment by DanilaFe** [comment]
This is no longer an internal error on main. I get:

```
issue-13277.chpl:7: In function 'main':
issue-13277.chpl:8: error: could not find a copy initializer ('init=') for type 'R' from type 'int(64)'
issue-13277.chpl:3: note: this candidate did not match: init=(this: R, other: R) [1110565]
issue-13277.chpl:8: note: because actual argument #1 with type 'int(64)'
issue-13277.chpl:3: note: is passed to formal 'other: R [1110570]'
issue-13277.chpl:8: note: unresolved call had id 530553
```

Closing.
