### ISSUE TITLE
internal error with generic function argument of array-of-generic-record

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#13279]
Bug. Internal compiler error.

I don't see why this code shouldn't work. You can tease these two functions into separate codes if desired, but they're related enough that I didn't want to file two separate issues.

```chapel
record R {
  param i: int;
}

proc f(
  const ref arr: [] R
)
{
  writeln(arr.eltType.i);
}
proc g(
  const ref arr: [] R(?i)
)
{
  writeln(i); // omit to get internal error
}

proc main() {
  var array: [1..8] R(10);
  f(array);
  g(array);
}
```

For `f`: `internal error: RES-CAL-NFO-0126 chpl version 1.20.0 pre-release`

For `g`: `internal error: RES-CAL-NFO-0078 chpl version 1.20.0 pre-release` if `writeln` is commented out.

```chapel
// Base case without array. This works on 1.19.0.
record R {
  param i: int;
}

proc f(
  const ref r: R(?i)
)
{
  writeln(i);
}

proc main() {
  var r: R(10);
  f(r);  
}
```
[TIO](https://tio.run/##RcwxDsIwEETRfk8xpbeDNim4Q26wMgZWSmxrsKBAObsxUFDPvB9vVtPaO1MsPGPBS4BqtA0@wXObZRepLBHXMKZY8r2B6QJOWMLJVVQ@5klvac3B9S828xz0m3wYf@J4GAeMGHUGZO/9DQ)

**Comment by bradcray** [comment]
I agree that the second case with g() should work, but am not completely surprised that it doesn't yet.  Note the relationship with that case and issue #13262.

The first case with f() is something that I think also should ultimately work.

**Comment by DanilaFe** [comment]
The first case works on main today, while the second gives a nicer error message. I can't find a specific issue for type query in array contexts, but that seems separate to this one. Opening a PR with regression tests.
