### ISSUE TITLE
internal compiler error with ternary-if to define generic array types.

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#13290]
Bug. Internal compiler error when using ternary-if expression to define generic array types. Code works if changed to not be arrays (i.e., remove `[1..2]`).

R1 should work. It is arguable whether R2 should work.

```chapel
class C {}

// internal error: PAS-NOR-IZE-0841 chpl version 1.19.0
record R1 {
    type T;
    var data: if isClass(T) then [1..2] owned T else [1..2] T;
}

// internal error: UTI-MIS-0602 chpl version 1.19.0
record R2 {
    type T;
    var data: [1..2] if isClass(T) then owned T else T;
}

proc main() {
    {
        var ri: R1(int);
        var rc: R1(C);
    }
    {
        var ri: R2(int);
        var rc: R2(C);
    }
}
```
Reproduces on 1.19.0 and 1.20.0 pre-release.

**Comment by bradcray** [comment]
I think both of these should work (or at least, don't have an argument as to why they shouldn't).

A workaround for people who run into this issue is to introduce a helper type function:

```chapel
class C {}

proc myType(type T) type {
  if isClass(T) then
    return owned T;
  else
    return T;
}

record R1 {
    type T;
    var data: [1..2] myType(T);
}


proc main() {
    {
        var ri: R1(int);
        var rc: R1(C);
    }
}
```

[[TIO](https://tio.run/##VY69CoMwFIX3PMUZk0Wwo46@QclWOoTkFgM2SpK2iPjsaYwK7XIvfOeHo3s10ZCSHlQI6LCsjE1@1HjOcp6Ix3wgBcpfGGAfsKHb3HzDPbkMAU/x5R3GjyMD2WZGQ6BfKcPc7UmP3uBalzLsvcUPvJWHUVE1uNVVdbmfG6Qo0WOXso6LI73fM@ttk4u5dVG0/4IuQnfgla0pfQE)]

**Comment by bradcray** [comment]
@benharsh: The assertion error that's being hit is in a routine that it looks like you've worked on most recently.  Any thoughts on what it would take to handle this case?  (I tried the "simple" thing of adding an `isLoopExpr()` case to the first condition in `normalizeIfExprBranch()`, but this caused something to choke further down the line (not surprisingly).

**Comment by benharsh** [comment]
I think you were right in trying to add ``isLoopExpr``, but an additional change is needed to hoist the generated loopexpr functions out of the scope of the field's DefExpr (like we do with ArgSymbols).

I have a quick set of changes on a branch that works for a fully concrete type in the R1 style. The generic style will require some more effort, but I think my recent type constructor work will help us here. I don't know about R2 yet.

**Comment by bradcray** [comment]
@benharsh: Did your set of quick changes pass testing?  Would it be worth merging to move the ball forward here, independently of the R2 case?
