### ISSUE TITLE
nil checking on error-handling

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#13307]
### Summary of Problem

Calling a method on a generic error within a catch block results in a nil-checking error.

### Steps to Reproduce

**Source Code:**

```chapel
proc hello() {
  try {
    writeln('hello');
  } catch e {
    writeln(e.message());
  }
}

hello();
```

```
nilCheck.chpl:1: In function 'hello':
nilCheck.chpl:5: error: attempt to dereference nil
nilCheck.chpl:2: note: this statement may be relevant
```

### Configuration Information

- Output of `chpl --version`: chpl version 1.20.0 pre-release (775dd4ff11)

**Comment by ben-albrecht** [comment]
@mppf - this is the error I was talking to you about offline.

**Comment by mppf** [comment]
See also #11918

**Comment by ben-albrecht** [comment]
This impacts some application code, but it is not a gating issue b/c a work-around exists:

```chpl
proc hello() {
  try {
    writeln('hello');
  } catch e {
    var error = e: Error;
    writeln(error.message());
  }
}

hello();
```

**Comment by mppf** [comment]
@ben-albrecht - I'm expecting @vasslitvinov's PR #13314 to fix it.

**Comment by vasslitvinov** [comment]
Right. See:
```
test/classes/nilability/catch-no-throw.chpl
```
