### ISSUE TITLE
defer with return statement

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#13310]
Feature request? Is this intended to be legal?

```chapel
proc fn(): int {
  var ret = 42;
  defer {
    return ret;
  }
}

fn();
```

**Comment by mppf** [comment]
When I compile it I get:

```
error: return cannot be used within a defer statement
```

I think this is working as expected. Return from `defer` is not intended to work, at least not right now.

(That's after I changed the `int ret` into `var ret` in the code).

**Comment by bradcray** [comment]
@BryantLam: Am I understanding that you want to request the ability to be able to do this as a feature?

**Comment by BryantLam** [comment]
Main reason I opened this issue was because I was testing in TIO and I didn't get an error message (but now I do because Michael fixed my code; thanks!).

It would be nice to have an RAII idiom for return statements because it's a pattern that I use often enough. That said, I don't think I care to push for this feature at the moment, so I'm okay closing this out.
