### ISSUE TITLE
Surprising(?) performance difference of slicing with a strided range

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#13318]
### Summary of Problem

More of a request for a sanity check than necessarily a problem,

I'm surprised in the performance difference between these two
expressions, where `Data` is an array over a non-stridable domain.
But only when buried inside something like `MergeSort._Merge`:

```chapel
var A1 = Data[lo..hi];
var A2 = Data[lo..hi by 1];
```

Further surprisingly, I can't reproduce the performance difference
except in situ, though I was able to whittle down the test case from
the starting point of `test/library/packages/Sort/performance` and
`Sort.chpl` to the 65 lines below, with all the sorting logic removed.

Is this expected?  (Does anyone else see this behavior?)

This is the performance issue I mentioned in #13196

### Steps to Reproduce

The `byOne` internal parameter controls which of those two cases is
active, and causes about a 6x slowdown.

```
fortytwo@magrathea:~/src/chapel-none (master)$ chpl --fast ../chapel/mergeslice.chpl
fortytwo@magrathea:~/src/chapel-none (master)$ ./mergeslice --recurse=true
noSort (seconds): 0.113146
noSort by one (seconds): 0.594217
```

The `--recurse=false` case is further surprisingly showing no
`byOne`-induced performance difference when the recursive calls to
`_NoSort` are replaced by 100 iterations of the function with the
slicing,

```
fortytwo@magrathea:~/src/chapel-none (master)$ ./mergeslice --recurse=false
noSort (seconds): 0.294969
noSort by one (seconds): 0.292263
```

(This was an attempt at producing a simpler test case.  But I still
don't understand why this doesn't have the same performance difference
as the `--recurse=true` case, so I'm leaving it in.)

**Source Code:**

```chapel
use Random;
use Time;

config const M: int = 24;                    // 2**M bytes
config var recurse = true;

// Array properties
config type T = int;                // Type of array

// Number of elements
const N: int = (2**M / numBytes(T)): int;

const D = {1..N};
var A: [D] T;
fillRandom(A, seed=42);

var t = new Timer();
{
  var B = A;
  t.start();
  noSort(B, false);
  t.stop();
  writeln('noSort (seconds): ', t.elapsed());
  t.clear();
}

{
  var B = A;
  t.start();
  noSort(B, true);
  t.stop();
  writeln('noSort by one (seconds): ', t.elapsed());
  t.clear();
}

proc noSort(Data: [?Dom] ?eltType, param byOne: bool, minlen=16) {
    _NoSort(Data, Dom.low, Dom.high, minlen, byOne);
}

private proc _NoSort(Data: [?Dom], lo:int, hi:int, minlen=16, param byOne: bool)
where Dom.rank == 1 {
  if (hi-lo < minlen) {
    // noop sort
    return;
  }
  const mid = (hi-lo)/2+lo;

  if recurse {
    _NoSort(Data, lo, mid, minlen, byOne);
    _NoSort(Data, mid+1, hi, minlen, byOne);
    _No(Data, lo, mid, hi, byOne);
  } else {
    // Just for timing purposes
    for i in 1..100 do
      _No(Data, lo, mid, hi, byOne);
  }
}


private proc _No(Data: [?Dom] ?eltType, lo:int, mid:int, hi:int, param byOne: bool) {
    var a1max = mid;
    var A1: [lo..(a1max)] eltType = if byOne then Data[lo..(a1max) by 1] else Data[lo..(a1max)];
    var a2max = hi;
    var A2: [mid..(a2max)] eltType = if byOne then Data[mid..(a2max) by 1] else Data[mid..(a2max)];
}
```

Guessing that maybe the reason for the no-change behavior in
`--recurse=false` was due to (somehow) reusing the slicing domains
from one iteration to the next, I tried with a mid arg of `mid + 50 - i`,
but that didn't affect anything.

These times are from a CHPL_COMM=none build.  With a gasnet -nl 1 run
on the same machine, the `--recurse=true` times are 2x longer, but the
`--recurse=false` times are only slightly longer (tending to .33-.35
instead of .28-.30)

(I had first tried building a reproducer from the ground up, but
couldn't get a performance difference.  Given the `--recurse=false`,
this is in retrospect not surprising.)

**Associated Future Test(s):**

### Configuration Information

```
chpl version 1.20.0 pre-release (5eda264)

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_LLVM: none
CHPL_AUX_FILESYS: none

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
```

**Comment by cassella** [comment]
Is there a way to write a performance future for this?

**Comment by bradcray** [comment]
@cassella : I don't believe we have ways to create performance future tests at present.  For some things (e.g., "too many communications are being generated") a correctness test future can be used, where it locks in the number of communications generated.  But for something like this that's just wallclock time... I'm less sure.

Also, I strongly suspect that this has been resolved now.  Specifically, this past year, @vasslitvinov introduced an enum of stride types representing "known positive", "known negative", "positive one", "negative one", and "could be anything".  For a range literal, the compiler infers the tightest category possible, so `by 1` results in a "positive one" stride kine, as does `lo..hi`.  The following test demonstrates that this is the case for your code:

```chapel
config const lo=1, hi=5;

var Data: [lo..hi] real;

var A1 = Data[lo..hi];
var A2 = Data[lo..hi by 1];

writeln(A1.dim(0).type:string);
writeln(A2.dim(0).type:string);
```

So perhaps this can be closed now, if you're able to verify that?

**Comment by cassella** [comment]
@bradcray Thanks!  I no longer see a performance difference here.

**Comment by bradcray** [comment]
Sweet!  Nice, unexpected side effect of Vass's efforts this past year!
