### ISSUE TITLE
replace c_nil with just nil

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#13326]
Right now, `c_nil` is the nil value for a `c_ptr` or `c_void_ptr`. But `nil` could work perfectly well in that role. This issue suggests that we deprecate `c_nil` and enable `c_void_ptr` to be initialized or assigned from `nil`.

**Comment by bradcray** [comment]
My intuition would be to not do this on the argument that `nil` is a value for classes in Chapel while `c_nil` is a C pointer's value, where that's more of a built-in external type + value in the language (though maybe it should be called `c_null` or `c_NULL`?).  Maybe put another way, it makes sense to me that the following declarations would be treated differently:

```chapel
var x = nil;
var y = c_nil;
```

whereas if `nil` is used for both cases, it potentially raises some question about what the type of `x` is...?

**Comment by mppf** [comment]
@bradcray - won't we infer `x` to be of type `nilType` today? If that's the case, I'm not sure the difference is useful.

**Comment by bradcray** [comment]
Yes, we do.

I'm just expressing my opinion:  Intuitively, Chapel's classes and C pointers feel like entirely different type 
"kinds" to me and having a value that works across both of them feels more surprising and chafing to me than natural.  Maybe another analogy would be if we chose to only support `0` and retired `0.0` (or retired both and just used `nil` for numeric zero values).

**Comment by mppf** [comment]
Even so, right now one can't do
```
var x: c_void_ptr = nil;
```

and instead one must write
```
var x: c_void_ptr = c_nil;
```

Here it seems that the nil / c_nil difference is not so important. Do you agree in that specific case? (If so, I'll update the issue description to ask for that).

**Comment by bradcray** [comment]
I don't have any strong opinion about that case (if I were writing it, I'd want to rely on the default initialization rather than specifying the c_nil value).  If it were me, I'd probably overload the former to generate a warning ("Did you mean c_nil?") rather than just having it pass through as a special case.

**Comment by mppf** [comment]
Closing because this asks the wrong question / has the wrong TODO. See #13520.
