### ISSUE TITLE
Improve mason update output when using multiple registries

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#13336]
When using multiple registries, the `mason update` command reports multiple redundant update messages:

```
Updating mason-registry
Updating mason-registry
```

It would probably be more informative to let users know which registries are currently being updated, e.g.

```
Updating mason-registry
Updating local-registry
```

**Comment by Aniket21mathur** [comment]
@ben-albrecht Can I work on this?

**Comment by ben-albrecht** [comment]
@Aniket21mathur - That'd be great. Let me know if you have any questions.

**Comment by Aniket21mathur** [comment]
> Let me know if you have any questions.

Sure. I have submitted a draft as #14881. Please review, I will post my queries there :smile: 

Thanks!
