### ISSUE TITLE
Allow setting project version number in chpldoc

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#13335]
Today, chpldoc generates a sphinx project which defaults to version `0.1.0`. It would be helpful for chpldoc to support something like a `--set-version` or `--project-version` flag that sets this version which gets displayed in the generated HTML.

Additionally, mason could use the mason package version to determine which flag value to pass when doing a `mason doc` call.

**Comment by lydia-duncan** [comment]
I'm the best suited for this task, but suspect I won't get to it for a while so would be happy for someone else to take it on when they have time.

**Comment by immadisairaj** [comment]
I suppose [this](https://github.com/chapel-lang/chapel/blob/9fa37c62959e5df0fbe69fb3a359d628ef7a2bc7/third-party/chpl-venv/chpldoc-sphinx-project/source/conf.py#L63) is where the version is hardcoded as 0.0.1 while using chpldoc.
I think we can pass an optional argument value and change the document version variable in the snippet linked above. Please correct me if I am wrong.

**Comment by lydia-duncan** [comment]
That sounds right, but note that since chpldoc is implemented in the Chapel compiler, any flag you add for setting it will need to be piped through [this file](https://github.com/chapel-lang/chapel/blob/master/compiler/main/docsDriver.cpp)
