### ISSUE TITLE
spike: can two-array sorts be the default?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#13348]
Follow-on to #180
Addressing this may resolve https://github.com/chapel-lang/chapel/issues/12607

Consider changing the default sort from MSBRadixSort. It might be a two-array sort, an in-place parallel bucketizer sort, and it might swap to/from sample sort.

**Comment by jabraham17** [comment]
@mppf, can this be closed since https://github.com/chapel-lang/chapel/pull/24147 has been merged?

**Comment by mppf** [comment]
Yes, good point, thanks for pointing it out. I will close it now.
