### ISSUE TITLE
Multi-locale libraries fail to compile due to types returned from exported functions in standard modules

### ISSUE THREAD

**Issue by dlongnecke-cray** [chapel-lang/chapel#13394]
```
$CHPL_HOME/modules/standard/IO.chpl:941: error: Multi-locale libraries do not support return type: syserr
```

MLL compilation has started to fail due to encountering unsupported types returned by functions exported in the Chapel standard modules.

What I am not sure of is the commit that introduced this failure.

This issue is blocking resolution of https://github.com/Cray/chapel-private/issues/278.

**Comment by bradcray** [comment]
This sounds potentially related to @lydia-duncan's #13372, but only because issue #13373 mentions related modules.  I don't know the code well enough to have a theory as to why it would matter, though...

**Comment by dlongnecke-cray** [comment]
I looked over the code for that PR and haven't the slightest idea how it might have induced this failure, but hopefully @lydia-duncan might have a more promising lead...

**Comment by bradcray** [comment]
There's always `git bisect`...

**Comment by dlongnecke-cray** [comment]
I'll give it a go. This will be fun!

**Comment by dlongnecke-cray** [comment]
Well that wasn't what I was expecting! Nothing to do with the PR of @lydia-duncan at all, but rather it looks like something to do with https://github.com/chapel-lang/chapel/pull/13327 from @mppf.

Investigating why now.

**Comment by dlongnecke-cray** [comment]
Ah. A rather silly logical error on my part. 

It seems I skip _internal_ modules with exported functions in my codegen, but not _standard_ modules. It looks like the IO plugins @mppf migrated to the standard modules ended up triggering this error.

**Comment by lydia-duncan** [comment]
Michael asked me about skipping the standard module functions, but I think he only saw the single locale case.

There are tests for MLL compilation, they just only run on Macs nightly due to #278 (which you are working on this sprint)

**Comment by lydia-duncan** [comment]
I wonder what it would take to allow functions that use extern types for their argument or return types to be exported . . . it shouldn't be bad in single locale but multilocale will for sure be tricky . . .
