### ISSUE TITLE
Adjust highlighters for lifetime keyword

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#13413]
There is now a `lifetime` keyword. The task here is to update syntax highlighters to recognize it.

**Comment by rahulghangas** [comment]
Was using pygments for rust and thought I might update it for Chapel since I saw this issue a while ago 
[Pull Request](https://github.com/pygments/pygments/pull/1357)

Also, I noticed that the [spec](https://chapel-lang.org/docs/_downloads/chapelLanguageSpec.pdf) if missing keyword 'prototype' in the Keywords section on page 24-25

**Comment by mppf** [comment]
Thanks @rahulghangas ! PR #14741 will add that keyword to the Keywords section of the spec.

I'm leaving this issue open because someone needs to check if the other syntax highlighters also need updating.

**Comment by rahulghangas** [comment]
#14764 along with [chapel-tmbundle PR 18](https://github.com/chapel-lang/chapel-tmbundle/pull/18) should cover all of them since chapel_listing.tex doesn't exist anymore. 

source-highlight, vim and emacs have already been updated by other people

**Comment by mppf** [comment]
@rahulghangas - great, thanks! We'll close this issue once those PR are merged. Have you been able to test those highlighters? It'd be nice to say in your PR message how you tested them.

**Comment by rahulghangas** [comment]
I've tested chapel-tmbundle and [highlight](https://gitlab.com/saalen/highlight) and added comments on respective PRs

**Comment by itss1ddhant** [comment]
@rahulghangas  @mppf  Is this Issue resolved or still needs work ? It's been a while and it has not been closed.

**Comment by mppf** [comment]
As far as I know the issue is resolved, thanks for asking. If somebody finds a highlighter that doesn't show `lifetime` as a keyword, we can make a new issue for it.
