### ISSUE TITLE
Overhaul the bookkeeping for number of nonzeroes in sparse domains

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#13410]
Sparse domains keep track of number of nonzero indices using the `nnz` field. This is defined in `BaseSparseDom` class. In the same class, there are `dsiNumIndices` and `dsiSize` methods that just returns `nnz`.This strategy works fine for non-distributed ones. 

However, in block-distributed sparse domains this strategy is broken because of privatization:

``` chapel
use BlockDist;

var space = {1..10};
var dom = space dmapped Block(space);
var spsdom: sparse subdomain(dom);

for i in 2..8 do
  spsdom += i;

for l in Locales do on l {
  writeln(here);
  writeln("Size: ", spsdom.size);
  writeln("NNZ: ", spsdom._value.nnz);
  writeln("NNZ locale: ", spsdom._value.nnz.locale);
}
```

prints out

```
LOCALE0
Size: 7
NNZ: 7
NNZ locale: LOCALE0
LOCALE1
Size: 0
NNZ: 0
NNZ locale: LOCALE1
```

because the `SparseBlockDom` objects are privatized, each copy have their own `nnz`s.

I propose the following solution:
- Remove `nnz` field from `BaseSparseDom`
- Add `nnz` parenthesesless method that just halts in `BaseSparseDom` a la pure virtual methods.
- For `DefaultSparse` and `LayoutCS` use a field like `_nnz` or something, which is returned by the `nnz` override.
- For `SparseBlock`, the `nnz` override just sums up `nnz`s of local sparse block domains.

Clearly there will be tiny bit of a performance overhead in distributed sparse domains, but I don't think this'll effect any real-world performance-critical application.

**Comment by e-kayrakli** [comment]
Similar scenarios should be considered if/when privatization support is improved.

**Comment by bradcray** [comment]
This sounds OK to me, and I agree that storing nnz in the abstract base class seems inappropriate (and that communicating when computing nnz for a distributed sparse domain is a reasonable approach; and definitely preferable to trying to keep a globally coherent nnz value through a sparse domain's lifetime).
