### ISSUE TITLE
proposal: do not include IO module by default but enable writeln

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#13448]
This issue started over on  #13373.

This issue proposes that we move the top-level free functions `writeln` and `write` to `ChapelIO.chpl` (which is an internal module that has its contents visible by default) and then that we make everything else that is in `IO.chpl` not be visible by default. Please note that these two functions do not throw (instead they halt by default). The channel type, `stderr`, stdout, methods on channels, file opening, etc. would not be included by default.

The idea here would be:
 1. Have programs indicate, with `use IO;` or similar, when they are making use of non-trivial I/O features
 2. Reduce namespace pollution for programs that only use writeln from IO.chpl
 3. Enable IO to make visible the errors in SysError that are thrown by it but without making SysError errors visible everywhere by default.

**Comment by bradcray** [comment]
Mentioned over on #13373:  It seems a bit odd / arbitrary to me to make `write` and `writeln` available by default but not `writef`.  Is the idea that `writef` is more likely to throw since it has to have matching format strings and types which we may not catch at compile-time (we definitely don't currently)?

**Comment by mppf** [comment]
I think it'd be totally reasonable to include `writef` in the included-by-default-set. The reason I didn't include it is that I tend to view `writef` as a more advanced/complex feature, rather than simply a programming-style alternative to `writeln`.

However the top-level`writef` also halts rather than throws and I think that's some indication it belongs in the set with `write` and `writeln`.
