### ISSUE TITLE
Feature Request: Use only one domain to create multiple Arrays.

### ISSUE THREAD

**Issue by krishnadey30** [chapel-lang/chapel#13465]
Currently for one of my code I am doing something like this:
```chapel
var testNamesMap: domain(string),
    failedTestsMap: domain(string),
    erroredTestMap: domain(string),
    testsLocalMap: domain(string),
    testsPassedMap: domain(string);
var testStatus: [testNamesMap] bool,
    testsFailed: [failedTestsMap] bool,
    testsErrored: [erroredTestMap] bool,
    testsLocalFails: [testsLocalMap] bool,
    testsPassed: [testsPassedMap] bool;

// Assume testSuite to be an array of FCF's.
for test in testSuite {
  testStatus[test: string] = false;
  testsLocalFails[test: string] = false;
  testsFailed[test: string] = false; // no tests failed
  testsErrored[test: string] = false;
}
```
If we use a single domain like this one
```chapel
var mapKey: domain(string);
var testStatus: [mapKey] bool,
    testsFailed: [mapKey] bool,
    testsErrored: [mapKey] bool,
    testsLocalFails: [mapKey] bool,
    testsPassed: [mapKey] bool;
```
we get the following error
```bash
error: halt reached - cannot implicitly add to an array's domain when the domain is used by more than one array
```
------
Rather than creating a domain for each array, we can support the functionality of using a single domain in multiple arrays when we add new keys.
------

**Comment by bradcray** [comment]
I'm not sure I'm understanding what this issue is requesting.  Are you asking for a change in the language of some sort (you should already be able to do what you want to here), or is this more like a personal TODO for a refactoring of the code you've written?

**Comment by krishnadey30** [comment]
I tried doing the second way i.e.
```chapel
var mapKey: domain(string);
var testStatus: [mapKey] bool,
    testsFailed: [mapKey] bool,
    testsErrored: [mapKey] bool,
    testsLocalFails: [mapKey] bool,
    testsPassed: [mapKey] bool;
```
and I got some errors. So I asked @ben-albrecht and @lydia-duncan  and they suggested me to open a feature request issue for the same. Is it possible to do this?

**Comment by bradcray** [comment]
It should work (the code above compiles and runs anyway).  An observation is that you'll need to add any new keys to `mapKey` first and then assign the corresponding values to the arrays at that index.  Or, if you could capture what you tried that did not work, that would be helpful.

**Comment by krishnadey30** [comment]
I want to add the keys dynamically later.
```chapel
// Assume testSuite to be an array of FCF's.
for test in testSuite {
  testStatus[test: string] = false;
  testsLocalFails[test: string] = false;
  testsFailed[test: string] = false; // no tests failed
  testsErrored[test: string] = false;
}
```

**Comment by krishnadey30** [comment]
I think I should have mentioned what I am using this for.

**Comment by bradcray** [comment]
Right, so the way you want to approach this is as I mentioned above:  When a domain is shared by multiple arrays, you need to add the key to the domain first, then assign to the arrays (in addition, the capability of extending an array with its own domain by writing to it will be going away very soon, probably in the next release).  So, for example, try the pattern:

```chapel
for test in testSuite {
  const testName = test: string;
  mapKey += testName;
  testStatus[testName] = false;
  testsLocalFails[testName] = false;
  testsFailed[testName] = false; // no tests failed
  testsErrored[testName] = false;
}
```

**Comment by krishnadey30** [comment]
It worked thanks, @bradcray.
