### ISSUE TITLE
bug: --verify fails on interop/C/multilocale/static/boolArgAndReturn.chpl

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#13461]
With CHPL_COMM=gasnet, I get:

```
$ chpl --verify --library --static $CHPL_HOME/test/interop/C/multilocale/static/boolArgAndReturn.chpl
internal error: MAI-CHE-CKS-0678 chpl version 1.20.0 pre-release (7c92698dcd)
```

The failure is in:
```cpp
// FLAG_EXTERN => FLAG_LOCAL_ARGS
INT_ASSERT(!fn->hasFlag(FLAG_EXTERN) || fn->hasFlag(FLAG_LOCAL_ARGS));
```

**Comment by vasslitvinov** [comment]
@dlongnecke-cray - since you are working in this area, could you see if it is easy to fix? Maybe we need to retire the assumption `FLAG_EXTERN => FLAG_LOCAL_ARGS` ?

**Comment by dlongnecke-cray** [comment]
Sure, I'll try and figure this out today. Do you think `--verify` is related to the linking errors that these tests are also experiencing?

**Comment by dlongnecke-cray** [comment]
Ah, I believe I may have found the culprit!

In `compiler/passes/buildDefaultFunctions.cpp`, the definition of `chpl_mli_smain is inserted into the AST and is given the flag `FLAG_EXTERN`, but it is not marked as `FLAG_LOCAL_ARGS`. I'll whip up a quick fix to see if this fixes the issue.

**Comment by vasslitvinov** [comment]
> Do you think --verify is related to the linking errors that these tests are also experiencing?

If you are talking about the linking errors in the quickstart configuration, then I expect them to be un-related.
