### ISSUE TITLE
Fix linking errors for multilocale libraries when CHPL_TASKS=fifo

### ISSUE THREAD

**Issue by dlongnecke-cray** [chapel-lang/chapel#13475]
Recent nightly testing failures revealed that mutlilocale library compilation doesn't play well with `CHPL_TASKS=fifo` for some reason. For now, suppress the failing tests, but eventually, we should get to the bottom of why linking fails.

Investigate `runtime/etc/Makefile.mli-static`. My first guess is that it is a GNU specific error (once again)!

**Comment by lydia-duncan** [comment]
The failure with gasnet.quickstart today was another instance of this, which I had forgotten about.  I think we should prioritize on this if possible

**Comment by dlongnecke-cray** [comment]
Ok, I'm looking into it. I'll post what I find.

**Comment by gbtitus** [comment]
@dlongnecke-cray I could take this one if you'd like -- my #15013 this morning has directly to do with it.

**Comment by dlongnecke-cray** [comment]
Thanks @gbtitus, that'd be great.

**Comment by gbtitus** [comment]
@dlongnecke-cray I'm testing a fix for this.  Can you tell me, under what conditions (which tests) do/would we use `runtime/etc/Makefile.shared`?  I've run tests and/or configurations that exercise all the other files my changes modify, but I'm not sure I've covered that one.

**Comment by dlongnecke-cray** [comment]
We use `Makefile.shared` for shared libraries on Darwin (C or Python, either would do fine).

**Comment by gbtitus** [comment]
So, which test(s) should I run there?

**Comment by lydia-duncan** [comment]
test/interop/C or test/interop/python (the latter if you have Python3, numpy and cython installed on your system)

**Comment by lydia-duncan** [comment]
Correction, you should run the multilocale subdirectory of the python set, forgot which issue we were looking at

**Comment by dlongnecke-cray** [comment]
I think anything in `test/interop/python` or `test/interop/C/multilocale` are good tests to run, you could start with `test/interop/C/multilocale/use_testing.ml-test.c` if you want to run a C test.
