### ISSUE TITLE
Proposed Changes to Precedence Tables

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#13482]
see #13480 #10012 #11463.

### examples
```
new C?();	? > new
new C()?;	? > new
new (expr)?()
new (expr)()?

new C()?!	these are not useful, likely unintended by the user
new C?()!
new C()??
new C?()?

new owned C?()	choose 'owned' vs. '?' ... does it matter?
new owned C()?
new owned (expr)?()
new owned (expr)()?

x: C?		? > :
x: C!		! > :        NB (prefix) unary-! vs. postfix-! are different things
x!: C		! > :
x!: C!
x!: C?

x: C()?
x: C?()
x!: C()?
x!: C?()

x: owned C	owned > :
x: owned C?	choose 'owned' vs. '?' and '!' ... does it matter?
x: owned C!
x!: owned C
x!: owned C?
x!: owned C!

x: class? : D	note ':' is left-associative
x: class? : owned D
x: class? : owned? D
x: class? : owned D?
x: class : owned D?
x: owned C: class?

new C() : unmanaged
new C?() : unmanaged
new C()? : unmanaged	new > :
new C()  : unmanaged?	? > :	what about 'unmanaged' ?

new borrowed C() : unmanaged	new > :
new borrowed C()? : unmanaged
new borrowed C() : unmanaged?
new borrowed C()? : unmanaged?

new C().m	new > .  DIFFERS from what we have now
new C()!.m	note: currently '.' has the highest precedence
          	not useful
new C()?.m	not useful

... same with parens, as in m() ...

owned C.m	note: currently '.' has the highest precedence
owned C().m
owned? C.m

... same with parens, as in m() ...


expr1 == expr2	currently '==' and '!=' have lower precedence
              	than the operations above, so no change is needed
```

**Comment by mppf** [comment]
`var x = new MyClass?()`
`var y = new MyClass()?`

I think we are imagining that the ? is binding more tightly than the `new` here

**Comment by mppf** [comment]
`var z = new MyClass()?!`

Supposing `!` on types exists (which isn't a given), is this
`(new ( MyClass?())!` or is it `new ( (MyClass?())! )` 

Or `new MyClass(int):unmanaged`. Is the cast applying to the type or the result of the new?

**Comment by vasslitvinov** [comment]
My proposal, based on the example I just put in the main text, are:

* give postfix-`!` and postfix-`?` higher precedence then prefix aka unary `!`
* retain the order of these: `.`, `()`, `new`, `:` -- primarily because it's late in the day
* put postfix and `owned`/etc. between `.` and `new`

so we get this order (I am including some ops with previously-determined precedence for reference):


| op | assoc |  |
| :-- | --: | --- |
| `.` `()` `[]` | left |  |
| postfix-`!`, `?` |  | new addition |
| `owned` etc. |  | new addition |
| new | | |
| `:` | left | |
| reduce | left | |
| unary `!` | right | |
| `+` et al. | | |
| `==` `!=` | left | |


P.S. I can go either way on allowing postfix-`!` on types. To me it is a useful counterpart of `?`.

**Comment by BryantLam** [comment]
> Supposing `!` on types exists (which isn't a given), is this
> `(new ( MyClass?())!` or is it `new ( (MyClass?())! )`

If `!` on types is supported, I'd lean towards the second choice only because the first choice doesn't seem useful. Am I missing a potential use case for it?

**Comment by mppf** [comment]
We do support `!` on types right now (it returns the type that `borrow()` aka `!` on a value would return).

**Comment by mppf** [comment]
I'm on board with @vasslitvinov 's suggestion above, with the exception that I think that we should change the precedence of `reduce` to be looser than `+`. That is discussed  in #11463.

AFAIK, besides that, the precedence of postfix-! is the main thing that is not working according to the table @vasslitvinov  created above.

**Comment by vasslitvinov** [comment]
> var z = new MyClass()?!

This is somewhat academic, however - currently parentheses `()` are required as a part of a `new` expression. If `?` follows the parens, it is also considered part of `new`. This is to support creating a class, yet treating it of a nilable type.

Therefore in this case everything from `new` to `?` must be a part of the `new` expression.

Given that we do not special-case for `new` with `!`, in this case `!` is applied last to the result of `new`. So a `borrowed MyClass` is produced.

To my surprise, the following seems to parse differently, producing `owned C` :
```chpl
var z = new owned MyClass()?!;
```

**Comment by mppf** [comment]
This issue has served its purpose and we have improved the precedence of ? ! unmanaged borrowed etc. The main open issue in my mind is #11463 but we will decide what to do there independently.
