### ISSUE TITLE
Remove deprecation warning and setsockopt from ZMQ module

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#13506]
We deprecated setsockopt, LINGER, SUBSCRIBE, and UNSUBSCRIBE in Chapel 1.20.  During the release cycle for 1.21 (or whatever the next version is), we should:
- [ ] remove setsockopt
- [ ] make LINGER, SUBSCRIBE, and UNSUBSCRIBE private to ZMQ
- [ ] remove test/deprecated/setSockoptSubscribe.*
- [ ] update the documentation to no longer refer to those symbols.

**Comment by Seenivasanseeni** [comment]
@lydia-duncan are you still working on this ?

**Comment by lydia-duncan** [comment]
This is not intended to occur until after the 1.20 release, which will be happening on Sept 19th (though we may have a branch available to perform it on shortly before that date).  A release has not occurred since the deprecation was put in place

**Comment by lydia-duncan** [comment]
Sorry for the confusing tenses in the original issue text :)

**Comment by Seenivasanseeni** [comment]
@lydia-duncan  no problem.

**Comment by bradcray** [comment]
A PR could be put together and then left open until after the release, though?

**Comment by lydia-duncan** [comment]
Resolved by #14548
