### ISSUE TITLE
explicitly generic type with nilable class type

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#13540]
This program ~does not compile (internal error)~ is one way to write it:

``` chapel
class C { var x; }

proc f(arg: C(?)?) {
  writeln(arg.type:string);
}

var x:owned C? = new owned C(1);
var b:C? = x.borrow();
f(b);
```

~Neither does this one (parse error)~ here is another:
``` chapel
class C { var x; }

proc f(arg: C?(?)) {
  writeln(arg.type:string);
}

var x:owned C? = new owned C(1);
var b:C? = x.borrow();
f(b);
```

Should both forms be supported?

**Comment by DanilaFe** [comment]
Both forms in the issue OP are supported. I think this issue is no longer a bug, though which one of the two forms (or both) we prefer is still up for discussion. Leaving this open, but removing the "bug" and "compiler" labels.

**Comment by mppf** [comment]
Since this area of the language is stable, I don't think we should keep this issue open. I'm closing it. I don't think "there should be one way to write it" is enough justification to make breaking changes in this area; but if others disagree they can make a new issue about that.
