### ISSUE TITLE
Complex division loses precision faster than expected

### ISSUE THREAD

**Issue by npadmana** [chapel-lang/chapel#13561]
Consider --
```chapel
writeln(1.0/1.3e150:complex,"=",1.0/1.3e150);
writeln(1.0/1.3e155:complex,"!=",1.0/1.3e155);
```

Running this gives --
```
7.69231e-151 - 0.0i=7.69231e-151
0.0 - 0.0i!=7.69231e-156
```

I'd guess that the algorithm for complex division is overflowing when trying to make the denominator real.

https://tio.run/##S85ILEjN@f@/vCizJDUnT8NQz0DfUM841dDUwCo5P7cgJ7VCR8lWSQdJXNOaC1O1KUK1IopyU03r//8B

**Comment by npadmana** [comment]
In `ChapelBase.chpl`, I see 

```chapel
inline proc /(a: real(?w), b: complex(w*2))
    return let d = b.re*b.re+b.im*b.im in
    (a*b.re/d, -a*b.im/d):complex(w*2);
```
which explains this.  Replacing with something along the lines of 

```chapel
proc divide(a : real, b : complex) {
  const absb = abs(b);
  return (a/absb)*(conjg(b)/absb);
}

writeln(divide(1.0,1.3e155:complex));
writeln(divide(1.0,1.0i*1.3e155:complex));
```
should fix this (although I haven't tested all edge cases).

**Comment by mppf** [comment]
@npadmana - want to make a PR with the better algorithm for complex division?

**Comment by npadmana** [comment]
Closing this since #13564 is now merged.
