### ISSUE TITLE
memory leak with coforall reducing an array

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#13569]
The following program leaks memory:

``` chapel
config const n = 100;
  
proc main() {
  var counts:[0..#n] int;
  var nTasks = 10;
  coforall tid in 0..#nTasks with (+ reduce counts) {
    counts[tid] += 1;
  }
}
```

This caused an increase in memory leaks in nightly:

https://chapel-lang.org/perf/chapcs/?startdate=2019/07/14&enddate=2019/07/28&graphs=memoryleaksforalltests

from the test test/library/packages/Sort/correctness/test-radix-bucketizer.chpl which calls SequentialInPlacePartitioning.bucketize which uses this pattern. (These were added in PR #13347).

**Comment by bradcray** [comment]
Thanks for picking this up, Vass.
