### ISSUE TITLE
Add overload of `string.join` for Chapel lists

### ISSUE THREAD

**Issue by dlongnecke-cray** [chapel-lang/chapel#13578]
It would be good to add an overload of `string.join` that accepts a `list` as an argument.

**Comment by Seenivasanseeni** [comment]
I am working on this. Overtake it if there is no update after 10 days.

**Comment by dlongnecke-cray** [comment]
Great, thanks!

**Comment by Seenivasanseeni** [comment]
@dlongnecke-cray  can you look at #13762.

**Comment by sriramsk1999** [comment]
@Seenivasanseeni can I work on this?

**Comment by Seenivasanseeni** [comment]
sure. go ahead.

**Comment by sriramsk1999** [comment]
Thanks! 🙂

**Comment by RisingGeek** [comment]
Can I work on this?

**Comment by sriramsk1999** [comment]
Sure. #14311 might be of some help :)

**Comment by dlongnecke-cray** [comment]
I'm going to go ahead and close this for now. After some discussion with @e-kayrakli it seems we might want to find a better place for the `string.join` overload to live than the internal modules. I think we'll let this one be demand driven 😄 .
