### ISSUE TITLE
Support `comm=none`-only configuration in UnitTest Launcher 

### ISSUE THREAD

**Issue by krishnadey30** [chapel-lang/chapel#13590]
Currently, the Unit Test launcher only supports a multi-local configuration and gives a `segmentation fault` in `comm=none`-only configuration.

I believe it will be good if it supports `comm=none`-only configuration as well.

**Comment by ben-albrecht** [comment]
Question: What happens if running a test file with unit tests that utilize `numLocales` requirements when only `CHPL_COMM=none` is built?

I think it'd be ideal for these tests to be skipped (with a warning of some sort), and allow for other single locale tests to be run.

**Comment by ben-albrecht** [comment]
#13642 merged
