### ISSUE TITLE
Missing nil checking upon ownership transfer

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#13600]
Related: we probably want to address #13704 on expiring values prior to enforcing this check.

The compiler should be issuing an error in the following code and it doesn't:

```chpl
class MyClass {var x:int;}

var c1 = new owned MyClass();
var c2 = c1; // error: 'c1' is left with 'nil' due to ownership transfer
```

The above error may disable code patterns that are actually desirable. Those are the cases where the source of the transfer, ex.`c1` above, is unused after the transfer. See https://github.com/Cray/chapel-private/issues/125 .

[ADDED:] Meanwhile, an obscure runtime error may occur when an invalid pattern is compiled with --no-legacy-nilable-classes, for example:

```chpl
var a = new owned C();
var b = a;   // this leaves 'a' storing 'nil'
writeln(a);  // at runtime, get "error: halt reached - argument to ! is nil"
             // where I'd expect it simply to print 'nil'
```

**Comment by mppf** [comment]
I'm working on adding the error checking while allowing ownership transfer from non-nil owned values that are expiring (per #13704). PR #14835 has the start of this work.

#14842 adds functions like `isCopyable` and `isAssignable` for use in `where` clauses with `list` `init=` and `=` functions. The idea would be to make calls to these functions result in errors when the list stores non-nilable owned.

But that brings up the question of how far we want to take the allow-transfer-from-expiring rule.

If I have two lists of non-nilable owned, should the compiler allow the ownership transfer?
``` chapel
{
  var x: list(owned C); // note, cannot store nil
  ... x.append ... // add some elements to x
  var y = x; // ownership transfer of elements, leaving elements in x storing nil
  // x not used again
}
```

Right now I am expecting to make this an error.

What about a record with default `init=` and `=`?

``` chapel
record R {
  var elt: owned C; // non-nilable
}
{
  var a = new R( new owned C());
  var b = a;
  // a not used again
}
```

If this code is allowed, then how could a user write an `init=` or `=` that would also allow it? Note that the fact that a record has an `owned C` field is - by itself - not enough by itself to trigger some behavior. It could have either of these copy initializers, for example:

``` chapel
  proc init=(ref rhs: R) {
    this.elt = rhs.elt; // ownership transfer that leaves rhs storing nil
  }

  proc init=(const ref rhs: R) {
    this.elt = new owned C(rhs.elt.x); // no ownership transfer here
  }
```

One of these creates a type that is copyable-from-const and the other creates a type that would require additional compile-time checking (like `owned C`).
