### ISSUE TITLE
What should 'new [flavor] C()?' mean?

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#13619]
What should `?` mean in a `new` expression? For example:

```chpl
  var o0 = new C()?;
  var o1 = new owned C()?;
  var o2 = new shared C()?;
  var o3 = new borrowed C()?;
  var o4 = new unmanaged C()?;
```

where `C` is either a class or a type alias.

Here are some options when `C` is a class:

**(A)** the same as `new` without `?`, except the result type is is nilalbe. For example:
```chpl
  var o0 = new C()?;             // owned C?
  var o1 = new owned C()?;       // owned C?
  var o2 = new shared C()?;      // shared C?
  var o3 = new borrowed C()?;    // borrowed C?
  var o4 = new unmanaged C()?;   // unmanaged C?
```

**(B)** the same as `(new [flavor] C()) ?`, that is, a borrow from the corresponding `new` without `?`, with a nilable borrowed type. For example:
```chpl
  var o0 = new C()?;             // borrowed C?
  var o1 = new owned C()?;       // borrowed C?
  var o2 = new shared C()?;      // borrowed C?
  var o3 = new borrowed C()?;    // borrowed C?
  var o4 = new unmanaged C()?;   // unmanaged C?  ('?' preserves 'unmanaged'-ness)
```

**(C)** disallow, to avoid confusion.

Options (A) and (B) would allow us to shorten some code modified in #13397:
```chpl
var x: unmanaged SomeClass? = new unmanaged SomeClass(....);  // after #13397
var x = new unmanaged SomeClass(....)?;                       // simpler
```

For example:
```
test/classes/deitz/infer/infer_field2.chpl
test/classes/delete-free/borrowed/borrowed-generic.chpl
test/classes/delete-free/lifetimes/lifetime-annotation-infer-like-swap.chpl
test/classes/delete-free/unmanaged/unmanaged.chpl
```

**Comment by vasslitvinov** [comment]
Today the compiler is a bit inconsistent:
```chpl
  var o0 = new C()?;             // owned C -- will be 'owned C?' after #13843
  var o1 = new owned C()?;       // owned C?
  var o2 = new shared C()?;      // shared C?
  var o3 = new borrowed C()?;    // owned C
  var o4 = new unmanaged C()?;   // unmanaged C
```

**Comment by bradcray** [comment]
My first instinct was to disallow because why would you do that?  But the shorten the code argument is actually pretty compelling.  That said, I'd probably put the `?` after the `C` rather than after its argument list.  I.e., `new C?()` since that's where it appears in other contexts and looks less like an operator being applied to a general expression (like `!` would be).

**Comment by mppf** [comment]
A related question is - how do you create a generic instantiation that is nillable ?

``` chapel
class C { type t; }

var x: C(int); // OK
var y: C(int)?; // This works today
var z: C?(int); // This does not work today
```

I'm not sure we made any design decision here, but I might've forgotten discussion.

If we made `new C?()` work, I'd expect `var z:C?(int)` to work as well.

**Comment by vasslitvinov** [comment]
It makes a good sense to start without `?` on values, i.e. for this release. Should I try it out on our test tree?
