### ISSUE TITLE
Design: support default intialization + assignment

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#13618]
While working on #13574, I came across a surprisingly high number of cases where the default initialization is immediately followed by an assignment, after which the variable is assumed to be non-nilable. A few of those cases are perhaps intentional for testing -- and/or are convertable to non-default initialization in a straightforward way. However, there are a couple of more interesting cases:

```chpl
  // users/npadmana/twopt/do_smu_soa.chpl
  var pp1, pp2 : owned Particle3D;
  if isPerf {
    pp1 = new owned Particle3D(nParticles, true);
    pp2 = new owned Particle3D(nParticles, true);
  } else {
    pp1 = readFile(fn1);
    pp2 = readFile(fn2);
    if !isTest {
      writef("Read in %i lines from file %s \n", pp1.npart, fn1);
      writef("Read in %i lines from file %s \n", pp2.npart, fn2);
    }
  }
```
```chpl
  // studies/bale/toposort/toposort.chpl
  var topoResult : shared TopoSortResult(D.idxType);

  select implementation {
    when ToposortImplementation.Serial {
       if !silentMode then writeln("Converting to CSC domain");

      var dmappedPermutedSparseD : sparse subdomain(D) dmapped CS(compressRows=false);
      dmappedPermutedSparseD.bulkAdd( permutedSparseUpperTriangularIndexList );

      if !silentMode then writeln("Toposorting permuted upper triangluar domain using Serial implementation.");
      topoResult = toposortSerial( dmappedPermutedSparseD );
    }
    ... other cases are similar ...
    otherwise {
      writeln( "Unknown implementation: ", implementation );
      exit(-1);
    }
  }
```
```chpl
// arrays/diten/timeVectorArray.chpl
// the following is a simplified version, where Runner1,2 are subclasses of Runner
var r: owned Runner;
r = new Runner1(); testme(r);
r = new Runner2(); testme(r);
... etc. ...
```

Should these be allowed?

**Comment by bradcray** [comment]
Personally, I worry about starting down a slippery slope here where the user writes increasingly complex patterns where they feel certain that a variable is assigned "soon enough" to be non-nilable but the compiler has an increasingly hard time telling.  For now at least, I'd not allow these and consider relaxing it later if we think we can draw a line somewhere that's helpful and clear.

I also think that by encouraging users to try and use non-nilable types, cleaner code could result in some code.  For example, in the first example you quote, if I were trying to wrestle it into a non-nilable world, it might encourage me to refactor all the duplicated code into a helper routine to avoid some redundancy (?):

```chapel
  var pp1: owned Particle3D = Particle3D.create(f1),
      pp2: owned Particle 3D = Particle3D.create(f2);

  // users/npadmana/twopt/do_smu_soa.chpl
  proc Particle3D.create(f) {
    if isPerf then
     retval = new owned Particle3D(nParticles, true);
    else {
      const retval = readFile(f);
      if !isTest then
        writef("Read in %i lines from file %s \n", retval.npart, f);
      return retval;
    }
  }
```

**Comment by mppf** [comment]
I am in agreement with @bradcray about this but I don't have a strong opinion. However it seems like something that we could allow in the future if we needed to. I think we should consider the answer to the question to be "No" for now and close this issue.
