### ISSUE TITLE
chpldoc has trouble with generic argument types with multiple fields

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#13626]
An argument of type `map(k,v)` is printed as `kmapv`. [Here](http://web.us.cray.com/~ekayraklio/map_api/modules/standard/Maps.html#Maps.map.init=) is an example from the `map` API proposal.

FWIW, there doesn't seem to be anything special about the word "map"

This issue should be resolved before the `map` type is merged as it causes some mess in the docs.

**Comment by lydia-duncan** [comment]
This looks to be resolved now

**Comment by lydia-duncan** [comment]
Err, looks like the map case was resolved but not the test I linked.  Interesting . . .

**Comment by cassella** [comment]
The `List` module's `extend()` function exhibits the problem in [the present docs](https://chapel-lang.org/docs/modules/standard/List.html)

```
 proc ref extend(other: eltTypelist?p)
```

instead of `extend(other: list(eltType, ?p)`

**Comment by cassella** [comment]
It's treating the expression as a binary operator, appending the three parts in infix order, in

```chapel
void AstToText::appendExpr(CallExpr* expr, bool printingType)
...
      // NOAKES 2015/02/09 Treating all calls with 2 actuals as binary operators
      // Lydia 2015/02/17 ... except homogeneous tuple inner workings.
      else if (expr->numActuals() == 2)
      {
        UnresolvedSymExpr* name     = toUnresolvedSymExpr(expr->baseExpr);
        if (printingType && strcmp(name->unresolved, "*") == 0)
        {
          // This is not a multiply, it's the symbol for a homogeneous tuple.
...
        }

        else
        {
          appendExpr(expr->get(1), printingType);
          appendExpr(expr->baseExpr, printingType);
          appendExpr(expr->get(2), printingType);
        }
      }

      else
        appendExpr(expr, fnName, printingType);
    }
```

As a bit of guess-and-check, I changed that triple-append stanza to

```chapel
        else
        {
          appendExpr(expr->get(1), printingType);
	  mText += "|";
          appendExpr(expr->baseExpr, printingType);
	  mText += "|";
          appendExpr(expr->get(2), printingType);
	  mText += " *** ";
	  appendExpr(expr, fnName, printingType);

        }
```

(grabbing that last `appendExpr` from the trailing else block,) which results in the correct type showing up after the `***`:

```
   .. method:: proc ref extend(other: eltType|list|?p *** list(eltType, ?p))
```
I guess this is another case that needs to be distinguished from a binary operator.  I don't know how to go about that.

**Comment by lydia-duncan** [comment]
That's concerning - it sounds like what you're saying is that any function call with just two arguments is getting treated like a binary operator?  If so, seems like the solution is to special case for the specific operators (since they should end up like PRIM_* or something if my memory serves) and treat everything else like a normal call.

**Comment by cassella** [comment]
I don't know the bounds of the cases where it happens, but I was able to reproduce it with just a function call instead of a generic type:

```chapel
proc foo(call = yoper(binar,ator)) {}
```
produces

```
.. function:: proc foo(call = binaryoperator)
```

**Comment by lydia-duncan** [comment]
Thanks for double checking!  That's quite concerning
