### ISSUE TITLE
Disappeared "note" in compiler output

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#13635]
The compiler no longer prints a supporting "note" for one of its errors, as a result of #13397, in the following test:

    test/classes/delete-free/lifetimes/bad-global-borrows-block.chpl

Correspondingly, that PR removed the last line from the .good file that used to be:
```
bad-global-borrows-block.chpl:7: error: Scoped variable globalBorrow would outlive the value it is set to
bad-global-borrows-block.chpl:6: note: consider scope of myOwned
bad-global-borrows-block.chpl:12: error: Scoped variable globalBorrow would outlive the value it is set to
bad-global-borrows-block.chpl:11: note: consider result here
```

We probably want to recover that "note".

**Comment by DanilaFe** [comment]
Michael's changes to https://github.com/chapel-lang/chapel/pull/21894 have restored the notes to this particular test. Is there a way to trigger this issue without an owned/shared temporary? If not, I think this issue can be closed.

**Comment by vasslitvinov** [comment]
I tried, however got all notes printed correctly. @DanilaFe feel free to close this issue.

### Details

Here is a transliteration of `bad-global-borrows-block.chpl` to using refs instead of owned/shared:
```chpl
ref x1;
{
  var y1 = 1;
  x1 = y1;
}

ref x2;
{
 var y2 = 1;
 ref z2 = y2;
 x2 = z2;
}
```

and the errors I get today, as of 26e8ae96c8, are:
```
t.chpl:4: error: Reference to scoped variable x1 reachable after lifetime ends
t.chpl:3: note: consider scope of y1
t.chpl:11: error: Reference to scoped variable x2 reachable after lifetime ends
t.chpl:9: note: consider scope of y2
```

**Comment by DanilaFe** [comment]
Yay! 🎉
