### ISSUE TITLE
Is the Reflection module the right place for lineNumber/fileName/etc.

### ISSUE THREAD

**Issue by daviditen** [chapel-lang/chapel#13681]
The `Reflection` module now has functions `lineNumber`, `fileName`, `functionName`, and `moduleName`. Is `Reflection` the right place for these functions to live?

**Comment by lydia-duncan** [comment]
I think it is :)

**Comment by mppf** [comment]
@daviditen - does this issue still represent an open question, or is there enough agreement?

**Comment by daviditen** [comment]
I think there is enough agreement.
