### ISSUE TITLE
Strange "unresolved" error in LCALS with --no-legacy-nilable-classes

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#13721]
Running this test:

    test/release/examples/benchmarks/lcals/LCALSMain.chpl

with `--no-legacy-nilable-classes` reports this "unresolved" error, even though the listed method should be applicable to the call:

```
LCALSMain.chpl:47: error: unresolved call 'initData(owned LCALS_Overlapping_Array_3D(real(64)), int(64))'
LCALSLoops.chpl:28: note: this candidate did not match: initData(ra: LCALS_Overlapping_Array_3D(real), id: int)
LCALSMain.chpl:47:  note: because call actual argument #1 with type owned LCALS_Overlapping_Array_3D(real(64))
LCALSLoops.chpl:28: note: is passed to formal 'ra: LCALS_Overlapping_Array_3D(real(64))'
LCALSLoops.chpl:16: note: candidates are: initData(ca: [] complex, id: int)
LCALSLoops.chpl:24: note:                 initData(ia: [] int, id: int)
                    note: and 1 other candidates, use --print-all-candidates to see them
```

#14166 works around this issue. When this issue is resolved, that change in `LCALSLoops.chpl` can be reverted.

**Comment by vasslitvinov** [comment]
Digging further, consider this program:
```chpl
record GR {
  param p;
}

proc getGeneric(dummyArg) type  return GR;

proc test1(ref fml1: GR) {
  compilerWarning("fml1: ", fml1.type:string);
}

proc test2(ref fml2: getGeneric(0)) {
  compilerWarning("fml2: ", fml2.type:string);
}

proc main {
  var act = new GR(5);
  test1(act);  // succeeeds
  test2(act);  // fails
}
```

At the point where test1/test2 calls are resolved, test1 is marked with FLAG_GENERIC whereas test2 is not. Therefore when resolving test2() ResolutionCandidate::isApplicable() chooses isApplicableConcrete, which does not allow for instantiating a formal, so returns false.

Here is some side-by-side comparison of the two cases:

|     | test1 | test2 |
| --- | --- | --- |
| normalize | hack_resolve_types() sets fml1->type to be GR | fml2->typeExpr is too complex, left as-is |
| resolution / markGenericFunctions | fml1->type is generic, so test1 is marked with FLAG_GENERIC | fml2->type is dtUnknown, not considered generic, so no FLAG_GENERIC for test2 |
| resolution / resolveNormalCall / gatherCandidates | test1 is found | test2 is found
| resolution / resolveNormalCall / filterCandidate, ResolutionCandidate::isApplicable | test1 is generic, invoke isApplicableGeneric | test2 is not generic, invoke isApplicableConcrete |
|  |  act matches fml1 | act does not match fml2 |

The only way to check generic-ness of an FnSymbol **correctly** is by resolving its formals. So the compiler should not do markGenericFunctions() at start of resolution. Or perhaps not do it at all. Instead it should do the work of resolving the formals whenever we inquire whether it is generic.

**Comment by benharsh** [comment]
I think it would be best to not let normalize try and reason about generic-ness of functions or their formals. I would argue for moving any relevant code (e.g. the where-clause creation for generic args) to function resolution.

**Comment by bradcray** [comment]
Thanks for looking into this, Vass!
