### ISSUE TITLE
Internal error from try { return; } in a loop

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#13739]
Here's a simple proc that hits an internal error, inspired by

https://github.com/chapel-lang/chapel/pull/13530#discussion_r310297536

### Steps to Reproduce

**Source Code:**

```chapel
proc catchy() throws {
  for i in 1..1 {
    try {
      return;
    }
  }
}

catchy();
```

```
catchy.chpl:3: internal error: did not find the insertion point [resolution/lowerIterators.cpp:1887]
```

Its name is out of date already, since the error still happens without the `catch e` from the original example.   It doesn't happen without the loop.

**Associated Future Test(s):**

None yet

### Configuration Information

```
chpl version 1.20.0 pre-release (e63dfaa)

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_LLVM: none
CHPL_AUX_FILESYS: none

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
```

**Comment by cassella** [comment]
On rereading, the above looks like pointless code that's written just to hit a bug.  The inspiring example did have code that could throw before the `return`, and a loop with more than one iteration, so wasn't pointless.

**Comment by cassella** [comment]
This is fixed now, git bisect says by 518175 (`Improve deinitializations for try+split init`) in #14814 (`Adjust split init to allow some try, if with returns`) in January.

I don't know why I didn't submit a future.  I'll submit a PR adding this as a test, since I don't see one quite like it.

I don't know if @dlongnecke-cray wants to revisit that change to UnitTest he was making that ran into this, per the inspiring comment.

**Comment by mppf** [comment]
I'm closing this issue since the problem it describes has been fixed.
