### ISSUE TITLE
SSCA2 build failures

### ISSUE THREAD

**Issue by PHHargrove** [chapel-lang/chapel#13738]
Using Xcode-11 Beta 5 on macOS 10.15 (also beta) I see the errors below building SSCA2 variants.

ssca2_rmat:
```
chpl -o SSCA2_main -M SSCA2_Modules SSCA2_Modules/SSCA2_kernels.chpl SSCA2_Modules/analyze_torus_graphs_stencil_rep_v1.chpl -sREPRODUCIBLE_PROBLEMS=true -sPRINT_TIMING_STATISTICS=true -sVALIDATE_BC=true -sDEBUG_NEIGHBOR_HISTOGRAM -sBUILD_RMAT_VERSION=true -sBUILD_1D_TORUS_VERSION=false -sBUILD_2D_TORUS_VERSION=false -sBUILD_3D_TORUS_VERSION=false -sBUILD_4D_TORUS_VERSION=false  SSCA2_main.chpl
In file included from /var/folders/nr/8p8gffgd1g51wkx7r_sx3mdm0000gn/T//chpl-phargrov-32127.deleteme/_main.c:54:
/var/folders/nr/8p8gffgd1g51wkx7r_sx3mdm0000gn/T//chpl-phargrov-32127.deleteme/SSCA2_kernels.c:52598:86: error: operand of type 'chpl____wide_Level_Set__domain_DefaultAssociativeDom_int64_t_T' (aka 'struct chpl_chpl____wide_Level_Set__domain_DefaultAssociativeDom_int64_t_T_s') where arithmetic or pointer type is required
chpl_macro_tmp_16411.addr = ((Level_Set__domain_DefaultAssociativeDom_int64_t_T_chpl)(*(call_tmp_chpl115)));
                                                                                     ^~~~~~~~~~~~~~~~~~~~~
/var/folders/nr/8p8gffgd1g51wkx7r_sx3mdm0000gn/T//chpl-phargrov-32127.deleteme/SSCA2_kernels.c:53046:86: error: operand of type 'chpl____wide_Level_Set__domain_DefaultAssociativeDom_int64_t_T' (aka 'struct chpl_chpl____wide_Level_Set__domain_DefaultAssociativeDom_int64_t_T_s') where arithmetic or pointer type is required
chpl_macro_tmp_16457.addr = ((Level_Set__domain_DefaultAssociativeDom_int64_t_T_chpl)(*(call_tmp_chpl115)));
                                                                                     ^~~~~~~~~~~~~~~~~~~~~
2 errors generated.
```

ssca2_1d (and same for _2d):
```
chpl -o SSCA2_main -M SSCA2_Modules SSCA2_Modules/SSCA2_kernels.chpl SSCA2_Modules/analyze_torus_graphs_stencil_rep_v1.chpl -sREPRODUCIBLE_PROBLEMS=true -sPRINT_TIMING_STATISTICS=true -sVALIDATE_BC=true -sBUILD_RMAT_VERSION=false -sBUILD_1D_TORUS_VERSION=true -sBUILD_2D_TORUS_VERSION=false -sBUILD_3D_TORUS_VERSION=false -sBUILD_4D_TORUS_VERSION=false  SSCA2_main.chpl
In file included from /var/folders/nr/8p8gffgd1g51wkx7r_sx3mdm0000gn/T//chpl-phargrov-32181.deleteme/_main.c:54:
/var/folders/nr/8p8gffgd1g51wkx7r_sx3mdm0000gn/T//chpl-phargrov-32181.deleteme/SSCA2_kernels.c:54312:86: error: operand of type 'chpl____wide_Level_Set__domain_DefaultAssociativeDom_int64_t_T' (aka 'struct chpl_chpl____wide_Level_Set__domain_DefaultAssociativeDom_int64_t_T_s') where arithmetic or pointer type is required
chpl_macro_tmp_12763.addr = ((Level_Set__domain_DefaultAssociativeDom_int64_t_T_chpl)(*(call_tmp_chpl115)));
                                                                                     ^~~~~~~~~~~~~~~~~~~~~
/var/folders/nr/8p8gffgd1g51wkx7r_sx3mdm0000gn/T//chpl-phargrov-32181.deleteme/SSCA2_kernels.c:54814:86: error: operand of type 'chpl____wide_Level_Set__domain_DefaultAssociativeDom_int64_t_T' (aka 'struct chpl_chpl____wide_Level_Set__domain_DefaultAssociativeDom_int64_t_T_s') where arithmetic or pointer type is required
chpl_macro_tmp_12813.addr = ((Level_Set__domain_DefaultAssociativeDom_int64_t_T_chpl)(*(call_tmp_chpl115)));
                                                                                     ^~~~~~~~~~~~~~~~~~~~~
2 errors generated.
```

**Comment by PHHargrove** [comment]
These are now appearing on multiple platforms.

**Comment by bradcray** [comment]
Hi Paul — Assuming you're seeing these only as of the last 24 hours or so, we're seeing this failure on our nightly testing as well and are working to address it.  Thanks for making sure we were aware of it.

**Comment by PHHargrove** [comment]
Yes, @bradcray, this was all within the past 24 hours.
It occurred first in my Xcode-11 testing, which is off-cycle with respect to the rest of our CI (thus testing a later commit on master) . So I initially made an incorrect assumption that the problem was specific to the back end compiler.

**Comment by bradcray** [comment]
Hi Paul —

This is looking resolved on our side now.  Let us know if that's not the case on yours.

Also, related to this, we've been discussing internally the notion of having a "good night" tag that could be used by external users / groups (or sensitive internal jobs) to identify snapshots of master that are expected to work well (by some definition of "well").  I imagine this might be of interest to you to avoid noise like this (?).  I think I heard that GASNet uses a separate branch for this, bringing it into sync when things are working well, is that right?  If you'd be willing to say, how has that approach worked for you and what led you to it rather than using tags, identifying SHAs, or other techniques?  Thanks!

**Comment by PHHargrove** [comment]
@bradcray The problem appears to be resolved as far as I can tell.

To respond to your question:

We keep a "stable" branch of GASNet which to which our "develop" branch is merged when things are both (a) in a good state for several consecutive days and (b) some non trivial improvement is available.  That allows down-stream developers to get the new features into use/testing more rapidly than waiting for a full release (for which we use "master"), but helps them avoid the risks of day-to-day regressions.  In some calendar quarters, it might only move once or twice between full releases.  Other times it might move every 10 or 14 days.

I believe the only meaningful difference from use a tag or published SHA1, is that using a branch for this purpose provides a history of past stable points, to which one can fall-back (e.g. use `stable^` if `stable` explodes).

Since I am the producer and not a consumer, I cannot comment on how well it works other than to say that at least the UPC++ and Legion developers use our "stable" and have very seldom reported bugs one would reasonably expect to be found in CI.

CC: @bonachea

**Comment by bradcray** [comment]
Thanks for confirming the resolution.  I'll close this as a result.

Thanks also for the notes on branching/SHAs/etc.  Am I correct in assuming that if we had such a mechanism, you'd likely use it rather than `master` to avoid noisy cases like this one?

**Comment by PHHargrove** [comment]
@bradcray Yes, I suspect we'd use such a mechanism.
