### ISSUE TITLE
Remove deprecated "List" module

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#13749]
The deprecated List module was replaced by LinkedLists, but the new Lists module's name is too close to it. The deprecated List module should be removed to avoid confusion.

**Comment by bradcray** [comment]
Or should the new module simply be named `List` rather than `Lists`?   What precedent do other languages take?

(For those not aware, note that `List` was deprecated in 1.19 to permit 1.20 to re-use the name `list` and potentially `List` if necessary).

More generally, we should review everything deprecated before this release cycle to see what can be removed before 1.20...

**Comment by BryantLam** [comment]
As a minor gripe, I don't like the plural form for the module names like `Barriers` or `LinkedLists`. I can't think of a language that does it either, (but I wouldn't be surprised if one existed). From a productivity standpoint, it's slightly harder for me to remember when a module name is a plural `LinkedLists` versus a non-plural `SysError`.

But I didn't really make a big stink about it because I'd rather the modules be de-pluralized when they're moved into their own `std` namespace https://github.com/chapel-lang/chapel/issues/12712.

**Comment by bradcray** [comment]
Following up on my comment above:
@benharsh: I believe that we deprecated `List` in part so that we could re-use that module name for the new `list` type, does that sound right?
@dlongnecke-cray: Was there any discussion of using `List` rather than `Lists` in implementing the new `list` type?

**Comment by benharsh** [comment]
I think that was the intention - I'm not sure how ``Lists`` came to be.

**Comment by dlongnecke-cray** [comment]
I am fine with changing the module to `List` (and we can do the same for `Sets` -> `Set` as well). I chose the name Lists because I recall (perhaps I am making this up) discussion about making module names be made plural. I just followed suit with what I thought the new convention would be.

**Comment by bradcray** [comment]
Thanks for the assist here, Bryant.
