### ISSUE TITLE
Retire string.length, range.length, domain.numIndices, array.numElements?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#13746]
Historically, Chapel had a number of distinct ways to ask about the arity of a collection via distinct methods/queries, such as:
* `string.length`
* `range.length`
* `domain.numIndices`
* `array.numElements`

But users requested a uniform way of making such queries more independently of the type and we settled on `.size` but didn't retire the original ways of doing so (the argument probably being that they were arguably a bit more descriptive and less likely to be confused with a memory-oriented query like C's `sizeof()`).

However, preserving two ways of making such queries can result in more confusion than benefit since having `string.length` and `string.size` suggests that there is a difference between them (e.g., maybe one returns codepoints while the other returns bytes?) when in fact there is not (both return codepoints).  It has also led to confusion at times, such as the case illustrated in issue #12448 (which itself is an instance of the bigger observation that promotion can sometimes catch people by surprise... but the fact that strings support .length while arrays don't is arguably the specific issue that led to so much confusion here).

For this reason, I propose we deprecate these routines for Chapel 1.20 and remove them in future versions of Chapel if there are no objections.

**Comment by e-kayrakli** [comment]
> the argument probably being that they were arguably a bit more descriptive and less likely to be confused with a memory-oriented query like C's sizeof()

I support this argument and am not too bothered by having multiple ways of doing the same thing in this context. However, I wouldn't mind if we are going in this direction. 

There is one thing I want to bring up, though. The difference between `.size` and `.numIndices` for sparse domains is significant IMHO. Currently they are doing the same thing, but `size` for a sparse domain more sounds like the size of the parent domain to me.

**Comment by vasslitvinov** [comment]
Deep inside I am neutral to this decision, as both sides of the argument have merits.

Teaching users to compute myArray.size is conceptually just as simple as teaching them to compute myArray.numElements (oh, and you can also say myArray.size).

See also #12736 . It is roughly about confusion (like compiler crash) from compiler behavior due to undefined paren-less method `length` in promoted context.

**Comment by bradcray** [comment]
I think the main argument for having one way of doing these things is that when reading through your code, I'll avoid the thought process of "Oh, I see you use string.size... I've always used string.length... I wonder what the difference between them is?  Maybe it's [insert favorite theory here]."  [goes and checks manual...]  "Wait, there's no difference?!?"

**Comment by bradcray** [comment]
@e-kayrakli: You've done a lot of string work recently and (I believe) have touched/added a lot of code that uses `.length` rather than `.size`.  Does that make you any more hesitant to standardize on `.size` and deprecate/retire `.length`?

**Comment by e-kayrakli** [comment]
@bradcray not really, no.

Slightly related to `string.length` deprecation, I'd probably want to see some refactor in the internal string implementation while we are doing this to rename the internal variables that keep track of the number of meaningful bytes in the buffer (`len`) and the capacity of the said buffer (`_size`).

[And after reading my comment from a month ago, I am still mildly hesitant about deprecating `domain.numIndices` and what it should mean for a sparse domain.]

**Comment by bradcray** [comment]
@mppf: I'm not very familiar with the Regexp.chpl module.  While grepping code, I see that the `reMatch` record has a `length` field.  Should this be replaced with a `size` field (and a 0-argument `length` method that gives a deprecation warning?

**Comment by mppf** [comment]
@bradcray - AFAIK yes

**Comment by bradcray** [comment]
@mppf: One other question:  Do you think that `file.length()` should be turned into `file.size` for consistency with other types?

**Comment by mppf** [comment]
@bradcray - I'm open to it, but the file size can change at any time (by other processes) whereas something like a string length will only change if you have a race condition. The counter-argument to that is that it's not necessarily useful to make that distinction in method names.

Another detail is that `file.length()` will generally make a system call and so is less property-like in terms of performance implications. Nonetheless it might be nice to have the same terminology...

**Comment by bradcray** [comment]
Sizes of arrays and ranges can change over time as well (as can the sizes of specific string or bytes variables, if they are reassigned), right?

**Comment by mppf** [comment]
Yes, but not due to activity outside of the Chapel program.

**Comment by bradcray** [comment]
Ah, I see.  I'd mentally substituted `tasks` for `processes` mistakenly.  This doesn't particularly give me pause.  You?

**Comment by mppf** [comment]
Like I said - I'm open to it. I was just bring up some considerations. I'd be fine either way.
