### ISSUE TITLE
Internal error for subclass array element returning instance in method

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#13778]
### Summary of Problem

The following code produces an internal error when compiled. I suspect further distillation is possible, but this is as far as I got in a reasonable amount of time. If anyone distills further, feel free to update issue title to be more descriptive.

### Steps to Reproduce

**Source Code:**

```chapel
proc main() {
  var fish: [1..0] owned Fish = [new owned Salmon()];
  fish[1].spawn();
}

class Fish {
  proc spawn(): owned Fish {}
}

class Salmon: Fish {
  override proc spawn(): owned Fish {
    var offspring = new owned Salmon();
    return offspring;
  }
}
```

**Compile command:**
`chpl test.chpl --devel`

```
internal error: no line number available [AST/baseAST.cpp:322]
```

### Configuration Information

- Output of `chpl --version`: `chpl version 1.20.0 pre-release (471709389f)`

**Comment by bradcray** [comment]
I've got a fix for this.  It's a super-easy one.
