### ISSUE TITLE
Request to `mason test` some not all

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#13786]
Feature request for `mason test [ModuleName]` or some syntactic variant to only test one|some, not all, of the tests.

Cargo 1.36.0 uses:
```terminal
USAGE:
    cargo test [OPTIONS] [TESTNAME] [-- <args>...]
OPTIONS:
        --test <NAME>...            Test only the specified test target
        --tests                     Test all tests # Not sure why this is needed. Isn't this default?
ARGS:
    <TESTNAME>    If specified, only run tests containing this string in their names
```

**Comment by ben-albrecht** [comment]
A similar feature request came in over the mailing list (from @tjstavenger-pnnl) and has been listed as a bullet in https://github.com/chapel-lang/chapel/issues/7106 -- I've added a cross-reference to this issue. Thanks for filing.

**Comment by krishnadey30** [comment]
Hey, @ben-albrecht this is pretty easy if we just run the tests which are passed as an argument.

**Comment by ben-albrecht** [comment]
@BryantLam - https://github.com/chapel-lang/chapel/pull/14037 allows passing tests to run:

```
mason test test/test1.chpl test/test2.chpl
```

Let me know if you think we can close this issue.

I think a future improvement could be supporting something like the substring matching:

```
If specified, only run tests containing this string in their names
```

We could leave this issue open to track that feature request or open a new issue about it (either way works for me).

**Comment by BryantLam** [comment]
Good enough for me right now. I would appreciate the substring-matching feature, though it makes sense to file it as its own issue.

**Comment by ben-albrecht** [comment]
Followed up here: https://github.com/chapel-lang/chapel/issues/15068
