### ISSUE TITLE
Missing newline at EOF in all Mason-generated files

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#13783]
### Summary of Problem
Minor annoyance. Easy.

New Mason projects are missing an end-of-file newline character for all files generated by `mason`. I think it's only the two files: ~~Mason.toml~~ .gitignore and src/((projectname)).chpl

**Comment by bradcray** [comment]
Tagging @oplambeck

**Comment by oplambeck** [comment]
@BryantLam Can you double check that `Mason.toml` is missing a newline character at the end when created by mason? I haven't been able to reproduce that. 

As far as src/((projectname)).chpl, Ill have a fix in soon.

**Comment by BryantLam** [comment]
@oplambeck -- Whoops. You're right. The other file is .gitignore, not Mason.toml.

**Comment by BryantLam** [comment]
Slight aside. What's with the newline at the start of file in .gitignore and Mason.toml, but oddly not the src/((projectname)).chpl file. It's easy enough to remove it since I can see it (unlike the missing newline) but it's still quirky. :)

**Comment by oplambeck** [comment]
@BryantLam Should all be fixed when PR #13791 goes in.

**Comment by BryantLam** [comment]
Cheers for working on this. Thanks!
