### ISSUE TITLE
Should "no line number" internal errors only fire in --devel / --verify modes?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#13792]
Issue #13778, ran into an internal error where the compiler detected a piece of AST
with no line number information.  I believe that this internal error was inserted to
help us be rigorous about ensuring that someone has thought about line numbers
in creating any new AST.

Thinking about it, though, I am wondering whether it is a good idea to handle such
cases via a user error given that it can prevent a user from writing and running code
that could otherwise be legal and reasonable.  My counterproposal would be to
do the check when running in `--devel` mode (to increase the chances that developers
hit such errors when they're writing new code) and `--verify` mode (so that nightly
testing will help keep us honest in other cases that slip through).  If neither of these
flags is on, why don't we just set the line number an obvious sentinel like 0 or -1 and
have users complain to us if/when they get error messages that are confusing to them
(but still valid) rather than when hitting internal errors that are our fault rather than theirs.

**Comment by bradcray** [comment]
@vasslitvinov (as the implementor), @ben-albrecht (as someone hit by it): What are your thoughts on this?

**Comment by vasslitvinov** [comment]
This is a good idea. I expect that the absence of line number info will not prevent the compiler from doing its job. So no need to crash in this case.

**Comment by bradcray** [comment]
A proposed implementation is in PR #13794.
