### ISSUE TITLE
Range passed to method with `in` intent is unexpectedly const

### ISSUE THREAD

**Issue by dlongnecke-cray** [chapel-lang/chapel#13797]
The `list.append` method has a single formal argument with the `in` intent. Because the argument has the `in` intent, I expect it to be mutable. The argument is passed to another routine that requires a mutable reference.

The code for `list.append` looks something like this:

```chapel

    pragma "no doc"
    proc _append_by_ref(ref x: eltType) {
      _maybeAcquireMem(1);
      ref src = x;
      ref dst = _getRef(_size + 1);
      _move(src, dst);
      _size += 1;
    }

    proc append(pragma "no auto destroy" in x: eltType) lifetime this < x {
      _enter();
      _append_by_ref(x);
      _leave();
    }
```

However when the element type of a list is `range`, a range argument given to `append` seems to be `const in` rather than just `in`:

```chapel

private use Lists;

proc main() {
  const foo: range(stridable=true);
  var lst: list(range(stridable=true));

  for i in 1..8 do
    lst.append(foo);

  return;
}
```

```
$CHPL_HOME/modules/standard/Lists.chpl:444: In function 'append':
$CHPL_HOME/modules/standard/Lists.chpl:446: error: const actual is passed to 'ref' formal 'x' of _append_by_ref()
$CHPL_HOME/modules/internal/ChapelRange.chpl:205: note: to formal of type range(int(64),bounded,true)
$CHPL_HOME/modules/internal/ChapelRange.chpl:205: note: id 1041314
$CHPL_HOME/modules/standard/Lists.chpl:431: note: to ref formal here
$CHPL_HOME/modules/standard/Lists.chpl:431: note: id 1048665
```

Earlier, @benharsh thought that https://github.com/chapel-lang/chapel/pull/8368 might be related to / the cause of this.

This issue is blocking the merge of https://github.com/chapel-lang/chapel/pull/13795 due to a failing test.

@mppf Might you have an idea of what is going on here? `compiler/passes/resolveIntents.cpp:286` is as far as I got before becoming lost.

**Comment by bradcray** [comment]
Which test is failing?

**Comment by dlongnecke-cray** [comment]
Ah, sorry, the test that is failing is `test/optimizations/bulkcomm/bharshbarg/stridedAssignDR.chpl` on this PR branch: https://github.com/chapel-lang/chapel/pull/13795

**Comment by mppf** [comment]
Here is a simpler reproducer:
``` chapel
proc f(in arg) {
  arg = 1..10;
  writeln(arg);
}

f(2..20);
```
