### ISSUE TITLE
Runtime type info of domains not initialized correctly when method has `in` intent

### ISSUE THREAD

**Issue by dlongnecke-cray** [chapel-lang/chapel#13808]
This bug was first discovered in the test `test/optimizations/bulkcomm/bharshbarg/stridedAssignDR.chpl`, on a branch where the method `list.append` was given the `in` intent.

When initializing a generic record with an _element type_ that is a domain, the next method manipulating members with that _element type_ (IE, a field) will trigger a segfault/nil error.

This only occurs when the record is default initialized. It does not occur when the record is initialized using a `new` expression.

The following code will segfault or throw a nil error: 

```chapel

record rec {
  type eltType;
  var x: eltType;

  proc set(in x: eltType) {
    this.x = x;
  }
}

proc main() {
  var dom = {1..10};
  var foo: rec(dom.type); // Instantiating this way fails.
  foo.set(dom);
}
```

However, by changing the initialization of `foo` to use a `new` expression instead, the runtime error goes away.

```chapel

record rec {
  type eltType;
  var x: eltType;

  proc set(in x: eltType) {
    this.x = x;
  }
}

proc main() {
  var dom = {1..10};
  var foo = new rec(dom.type); // This seems to work correctly.
  foo.set(dom);
}
```

It seems like there are two separate bugs at work here, no initialization of domain RTTI, and use of the `in` intent, though I don't know enough to say for sure.

**Comment by benharsh** [comment]
The example program here no longer appears to segfault, and was likely resolved by #19220.

**Comment by bradcray** [comment]
@benharsh : Do you think it'd be worthwhile to file a test with the code in the OP, to lock the current behavior in going forward, or do we already have equivalent tests?  (when in doubt, I usually just add the test because I don't think it's worth the time/effort to try and locate whether there are existing tests that subsume it... unless it's something easy/obvious to grep for).

**Comment by benharsh** [comment]
There are multiple futures in https://github.com/chapel-lang/chapel/pull/20499 which I believe subsume, either individually or in aggregate, the behavior described in this issue. That PR was opened as a follow-up from #19220.
