### ISSUE TITLE
`mason doc` only generates for main module

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#13812]
### Summary of Problem
I think `mason doc` only runs `chpldoc` on the main module. It needs to run `chpldoc --process-used-modules` instead.

https://github.com/chapel-lang/chapel/blob/8134ade67dd54cc2e9724eebf39436e22dd10867/tools/mason/mason.chpl#L130-L154

**Comment by bradcray** [comment]
Tagging @oplambeck
