### ISSUE TITLE
Passing `nil` to extern typdef'd int pointer types has regressed

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#13854]
### Summary of Problem

Passing `nil` to an external argument of type `c_ptr(size_t)` (say) worked a few days ago, but doesn't any longer.  @mppf believes that some of his recent work has broken it.

### Steps to Reproduce

**Associated Future Test(s):**
[`test/extern/nil/passNilToExtern.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/extern/nil/passNilToExtern.chpl
          ) #13853

**Comment by bradcray** [comment]
Note: This prevents arkouda from building on master with `--legacy-classes`.

**Comment by mppf** [comment]
This does not occur on my Ubuntu system, but it does occur on my Mac. I think the error is emitted by clang but not by GCC.
