### ISSUE TITLE
Make --library-python defaults more python-friendly

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#13880]
Compiling with `--library-python` today defaults to `lib/` as the target directory (following what `--library` does). Additionally, this `lib/` directory does not contain an `__init__.py` by default. As a result, users need to change directory into the `lib/` in order to use their python module, or add that `lib/` directory explicitly to their `PYTHON_PATH` to make it usable everywhere.

To get a more pythonic module structure, a user needs to add an additional flag, `--library-dir`, and create an `__init__.py` in the generated module directory:

```bash
chpl --library-python --library-dir Foo Foo.chpl
cat "from Foo.Foo import *" > Foo/__init__.py

# Now we can import:
python
> import Foo
```

Note that the contents of the `__init__.py` are derived from:

```python
from <library-dir>.<module-name> import *
```

It seems appealing to create an `__init__.py` and make the directory name default to the module name, so that creation of a python module could simply be:

```bash
chpl --library-python Foo.chpl

# Now we can import:
python
> import Foo
```

**Comment by dlongnecke-cray** [comment]
Let's say that we keep the default directory name the same (still just `lib`), but we go with the rest of the changes here. A consequence of this that all of our tests will have to be adjusted:

Instead of the following at the top of each test...

```python
import fooLibrary
```

We would write...

```python
from lib import fooLibrary
```

Else the new `__init__.py` will not take effect.

Are we OK with this? Is this the only option? A consequence of doing things like this is we no longer would need tests to set the `PYTHONPATH`.

**Comment by dlongnecke-cray** [comment]
Ah, maybe I'm misunderstanding and a simple...

```python
import lib
```

Will also suffice.

**Comment by lydia-duncan** [comment]
I think I would prefer continuing to put the `lib` directory in the `PYTHONPATH` to avoid having the user write `from lib import fooLibrary`.  What's the reasoning behind not changing the default directory name at the same time?

**Comment by dlongnecke-cray** [comment]
I can go with that. If I change the default directory name then it just means I'll have to touch N tests worth of cleanfiles.

For some reason, in my head, I seemed to think that we weren't certain about touching the default directory name but it seems I must have been imagining it...

**Comment by dlongnecke-cray** [comment]
Given that with this change the default Python output directory is the same as the Python module name, do we...

a) Want to force all `interop/python` tests to set their output directory as `--library-dir=lib`, and then adjust each to do `import lib as foo`?
b) For each test `foo.chpl`, add `foo/*` to the `.gitignore`, and make a `foo.cleanfiles` that contains `foo/*`?

**Comment by dlongnecke-cray** [comment]
I guess a third option is to keep all the existing tests the same and only add one new test for the new default directory / auto-cleanup at exit.

I just figured that we would like to incorporate these new features into existing tests.

**Comment by dlongnecke-cray** [comment]
I've decided to go with adding `--library-dir=lib` to compopts to avoid having to change existing tests at all for now. I'll add a test illustrating the new method of importing generated python modules.

**Comment by ben-albrecht** [comment]
> I've decided to go with adding --library-dir=lib to compopts to avoid having to change existing tests at all for now. I'll add a test illustrating the new method of importing generated python modules.

That sounds reasonable to me, to simplify the `CLEANFILES` implementation. 

We should also be sure to add a test for when the `__init__.py` already exists. Have we decided what that behavior should be?

**Comment by ben-albrecht** [comment]
Also, we could use the `__init__.py` doc string to put some useful build information, e.g. chapel compiler version and `printchplenv` settings.

**Comment by dlongnecke-cray** [comment]
Now that we're on the subject, I personally think it seems reasonable to treat `fooModule` as a build folder and just state in the docs that if there is an `__init__.py`, it will be overridden.
If we want, I can also just detect "if there's an `__init__.py`, don't write our version and emit a compiler warning".

Personally, though, I think the correct thing to do is to view the generated folder as a "bin folder", in which case users really shouldn't be putting their hand written code there and do so at their peril.

---

As for extras, those seem particularly easy to generate, so definitely make pull requests for them after the initial effort is merged.

**Comment by ben-albrecht** [comment]
> if there's an __init__.py, don't write our version and emit a compiler warning

I slightly prefer this approach, because it seems reasonable for a user to modify the generated `__init__.py`, e.g. to include documentation.

**Comment by dlongnecke-cray** [comment]
Sounds good. I'll proceed with that, then.
