### ISSUE TITLE
should `proc f( arg: ? x )` parse?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#13936]
Code using type query expressions tends to not leave a space between the `?` and the argument name, however this is legal according to the current parser:

``` chapel
proc f( arg: ? t ) {
  writeln(t:string);
}

f(1);
```

This variant looks even more confusing:

``` chapel
proc g( arg :? t ) { }
```

The ability to put an additional space seems to only allow patterns that might be more confusing (since it starts to look like `?` is a binary operator when in fact it is a way to modify a name). Nonetheless, we might imagine it is better this way, so the language can be more whitespace independent.

Should we:

  1. Continue to allow this case
  2. Change the parser to only accept type-query when there is no space (we would do this by making a new token like TIDENT and matching `?name` in the lexer).

**Comment by benharsh** [comment]
I vote for disallowing a space between ``?`` and the identifier. I don't think the flexibility of arbitrary whitespace is valuable and would probably only confuse readers as in this case it looks like an operator when it is not.

By disallowing this case, would we only lose ``?`` as a binary operator and as a unary prefix operator? Or are there other cases?

**Comment by bradcray** [comment]
I'd also be open to disallowing the space here.

**Comment by e-kayrakli** [comment]
@benharsh 

>By disallowing this case, would we only lose ? as a binary operator and as a unary prefix operator? Or are there other cases?

That sounds about right. 

After opening #14668, I got myself wondering about querying the type of an unmanaged nilable. It doesn't seem to work right now but:

```chapel
proc foo(arg: unmanaged ?t ?)
// or
proc bar(arg: unmanaged ?t?)
```
will probably be the way to go for that. Even with those, I think enforcing no space between prefix `?` and the identifier would be the right thing. I'd find the following significantly more confusing, for example:

```chapel
proc foo(arg: unmanaged ? t ?)
// or
proc bar(arg: unmanaged ? t?)
```
