### ISSUE TITLE
Inconsistent "duplicate decorators" error

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#13950]
With `!` binding more tightly than `owned` etc., the following lines should behave the same w.r.t. "duplicate decorators":
```chpl
// from test/classes/nilability/nilable-equalities.chpl
type ob = owned MyClass!;
type sb = shared MyClass!;
type bb = borrowed MyClass!;
type ub = unmanaged MyClass!;  // see z15c in
                               // test/parsing/precedence/bang-vs-new-etc.chpl
```

Incorrect "duplicate decorators" error in `new unmanaged C()?!`
  `test/parsing/precedence/new-mgmt-q-bang.chpl`
See also `z01c`, `z16c` in `test/parsing/vass/bang-vs-new-etc.chpl`

**Comment by mppf** [comment]
I've moved some of the original issue description here because PR #14298 will fix it:

In the following code:

```chpl
proc tm() type return object;

var o1 = new (owned tm())();
var o2 = new (owned tm())()?;
```

the `owned` is allowed for `o1` and causes error for `o2`.

I think it should be allowed in both cases. Short of that, disallowed in both cases.

**Comment by mppf** [comment]
@vasslitvinov - deprecating postfix `!` on types will render these patterns moot, right?

**Comment by vasslitvinov** [comment]
These patterns are indeed no longer legal. (They are deprecated for this release.) The compiler behavior in these cases is now correct. See also #14744.

Closing this issue.
