### ISSUE TITLE
What does `chpl --fast` do?

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#13964]
Related #13603

Feature request. Documentation; preferably in the compiler usage message or a man page.

What does `chpl --fast` do? The compiler's usage output simply states `Use fast default settings` but there's no mention of what the default settings are.

**Comment by bradcray** [comment]
Thanks for pointing out that the usage message is poor / confusing.  I think the man page is better:

```man
       --fast
          Turns  off  all runtime checks using --no-checks, turns on -O and
          --specialize.
```

https://chapel-lang.org/docs/usingchapel/man.html

**Comment by BryantLam** [comment]
Thanks! I think that's sufficient for me. I just need to remember to build the manpages..

**Comment by bradcray** [comment]
I still think the `--help` output could be improved.  Took a stab at it in #13966.
