### ISSUE TITLE
chpldoc renders some operator overloads incorrectly

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#13984]
chpldoc renders some operator overloads incorrectly. This is similar to #13983.

Operations that needed to be added to the [chapeldomain.py](https://github.com/chapel-lang/sphinxcontrib-chapeldomain/blob/master/sphinxcontrib/chapeldomain.py#L37-L49) regex include:

```chpl
proc  |()
proc |=()
proc &()
proc &=()
proc ^()
proc ^=()
```

Examples of these are in the [Map](https://chapel-lang.org/docs/master/modules/standard/Map.html) module..

**Comment by ben-albrecht** [comment]
FYI - @lydia-duncan

**Comment by lydia-duncan** [comment]
I have a vague memory that we don't document these sorts of functions for other types, so it could be that the solution is to either explicitly `pragma "no doc"` these guys or add a rule to chpldoc to skip documenting operator overloads

**Comment by ben-albrecht** [comment]
> I have a vague memory that we don't document these sorts of functions for other types, so it could be that the solution is to either explicitly pragma "no doc" these guys or add a rule to chpldoc to skip documenting operator overloads

I'd advocate for requiring an explicit `pragma "no doc"` to minimize surprises. It wouldn't hurt to add the regex patterns to the chapel domain in case some user really wanted these ops documented at some point.

I think we want to support  `|, &, ^` operations in the regex pattern matching regardless of our decision.

**Comment by lydia-duncan** [comment]
Paul mentioned this over on #17057.  I think I'd rather keep that one open than this one, let me know if you disagree!

**Comment by ben-albrecht** [comment]
Yeah, he seems to have dug a little deeper and has added more info. I'm happy to close this one as duplicate.
