### ISSUE TITLE
chpldoc renders ref procs incorrectly

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#13983]
chpldoc renders function signatures with a pattern of `proc ref f()` and `proc f() ref throws` in a different text style than other functions and does not generate a URL attached to the function.

Here are 2 examples of the pattern `proc ref f()` from the [LinkedList](https://chapel-lang.org/docs/master/modules/standard/LinkedLists.html) module:

```chpl
proc ref append(e: eltType)
proc ref remove(x: eltType)
```

Here is an example of the pattern `proc f() ref throws` from the [List](https://chapel-lang.org/docs/master/modules/standard/List.html) module:

```chpl
proc first() ref throws
```

It's worth mentioning that the pattern `prof f() ref` is rendered correctly, e.g. [list.last](https://chapel-lang.org/docs/master/modules/standard/List.html#List.list.last):

```chpl
proc last() ref
```

I'm pretty certain this is actually an issue in our [chapel sphinx domain](https://github.com/chapel-lang/sphinxcontrib-chapeldomain). I believe we need to update the [function regex pattern](https://github.com/chapel-lang/sphinxcontrib-chapeldomain/blob/master/sphinxcontrib/chapeldomain.py#L37-L49) to handle these cases.

**Comment by ben-albrecht** [comment]
This one is pretty minor IMO. Opening an issue to track it though.

**Comment by ben-albrecht** [comment]
FYI @lydia-duncan

**Comment by lydia-duncan** [comment]
#14794 had to work around this problem

**Comment by arezaii** [comment]
https://github.com/chapel-lang/sphinxcontrib-chapeldomain/pull/68 should fix the rendering of `proc ref foo()` and the missing links as well.

**Comment by lydia-duncan** [comment]
This was handled by #21195 and chapel-lang/sphinxcontrib-chapeldomain#68, closing
