### ISSUE TITLE
LCALS performance regression from #13840

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#14009]
There was a performance regression from "Task intents to operate on fields of this"  (https://github.com/chapel-lang/chapel/pull/13840) for LCALS.

Here's some [graphs](https://chapel-lang.org/perf/chapcs/?startdate=2019/08/13&enddate=2019/09/05&graphs=lcalsrawompshort,lcalsrawompmedium):

![image](https://user-images.githubusercontent.com/1588337/64374285-8069dc00-cff1-11e9-8f81-00f7d3b69e18.png)

![image](https://user-images.githubusercontent.com/1588337/64374294-8495f980-cff1-11e9-9139-f9e828b99b45.png)

**Comment by ronawho** [comment]
Here's a diff for just running "raw_omp, medium" for pressure_calc:


```diff
diff --git a/test/release/examples/benchmarks/lcals/LCALSConfiguration.chpl b/test/release/examples/benchmarks/lcals/LCALSConfiguration.chpl
index 9bc294cea7..6553b3bc88 100644
--- a/test/release/examples/benchmarks/lcals/LCALSConfiguration.chpl
+++ b/test/release/examples/benchmarks/lcals/LCALSConfiguration.chpl
@@ -24,9 +24,9 @@ module LCALSConfiguration {
   //
   // Loop lengths
   //
-  config const run_shortLoops  = true;
+  config const run_shortLoops  = false;
   config const run_mediumLoops = true;
-  config const run_longLoops   = true;
+  config const run_longLoops   = false;

   //
   // Loop Kernels
@@ -35,46 +35,46 @@ module LCALSConfiguration {

   // Loop Subset A: Loops extracted from LLNL app codes.
   config const runA_pressureCalc = true;
-  config const runA_energyCalc   = true;
-  config const runA_vol3DCalc    = true;
-  config const runA_delDotVec2D  = true;
-  config const runA_couple       = true;
-  config const runA_fir          = true;
+  config const runA_energyCalc   = false;
+  config const runA_vol3DCalc    = false;
+  config const runA_delDotVec2D  = false;
+  config const runA_couple       = false;
+  config const runA_fir          = false;

   // Loop Subset B: "Basic" Loops.
-  config const runB_init3     = true;
-  config const runB_muladdsub = true;
+  config const runB_init3     = false;
+  config const runB_muladdsub = false;
   // Unstable, see https://github.com/chapel-lang/chapel/issues/11336
   config const runB_ifQuad    = false;
-  config const runB_trapInt   = true;
+  config const runB_trapInt   = false;

   // Loop Subset C: Loops from older Livermore Loops in "C" suite.
-  config const runC_hydro1D      = true;
-  config const runC_iccg         = true;
-  config const runC_innerProd    = true;
-  config const runC_bandLinEq    = true;
-  config const runC_tridiagElim  = true;
-  config const runC_eos          = true;
-  config const runC_adi          = true;
-  config const runC_intPredict   = true;
-  config const runC_diffPredict  = true;
-  config const runC_firstSum     = true;
-  config const runC_firstDiff    = true;
-  config const runC_pic2D        = true;
+  config const runC_hydro1D      = false;
+  config const runC_iccg         = false;
+  config const runC_innerProd    = false;
+  config const runC_bandLinEq    = false;
+  config const runC_tridiagElim  = false;
+  config const runC_eos          = false;
+  config const runC_adi          = false;
+  config const runC_intPredict   = false;
+  config const runC_diffPredict  = false;
+  config const runC_firstSum     = false;
+  config const runC_firstDiff    = false;
+  config const runC_pic2D        = false;
   // Array OOB, see https://github.com/chapel-lang/chapel/issues/12806
   config const runC_pic1D        = false;
-  config const runC_hydro2D      = true;
-  config const runC_genLinRecur  = true;
-  config const runC_discOrd      = true;
-  config const runC_matXMat      = true;
-  config const runC_planckian    = true;
-  config const runC_impHydro2D   = true;
-  config const runC_findFirstMin = true;
+  config const runC_hydro2D      = false;
+  config const runC_genLinRecur  = false;
+  config const runC_discOrd      = false;
+  config const runC_matXMat      = false;
+  config const runC_planckian    = false;
+  config const runC_impHydro2D   = false;
+  config const runC_findFirstMin = false;

   //
   // Loop Variants
   //
-  config const run_variantRaw              = true;
+  config const run_variantRaw              = false;
   config const run_variantForallLambda     = false; // not implemented
   config const run_variantRawOmp           = true;
   config const run_variantRawSPMD          = false; // off by default because
```

Compile/run with:
```
chpl LCALSMain.chpl --fast --cc-warnings --legacy-classes -soutputFormat=OutputStyle.PERF_TEST --no-ieee-float
./LCALSMain
```

**Comment by ronawho** [comment]
And the kernel I've been focusing on is pressure_calc, but others were impacted too. Here's the kernel for reference:

https://github.com/chapel-lang/chapel/blob/818cc53d42f294df63458879b3d0e7aa7b60a381/test/release/examples/benchmarks/lcals/RunParallelRawLoops.chpl#L17-L43

**Comment by vasslitvinov** [comment]
When I restrict the implementation of "task intents for fields of this" in #13840 so it no longer applies to ranges, I observe recovered performance of the three kernels for raw,omp.

This came from the observation that the `range` standalone iterator, where the transformation applies to the `coforall chunk in ...` loop, now forwards the _low and _high fields.

Can user records be hit affected in the same way?

On the surface, no. Because ranges have the special feature of being passed by value by default. I.e. it is the only kind of type that is a record in compiler representation and has the `const in` default intent. Even if it is not the only one, it surely differs from user records, which are passed by `const in`.

With #13840 or without #13840, when a range is referenced in a task function as a whole, it is passed into the task function by default intent. This is the case in the standalone iterator's coforall, for example when calling `orderToIndex`, which passes `this` as the receiver.

Now with #13840, the range's individual fields are also passed into the task function, ex. `_low` and `_high`.

So either there are so many task functions that this is noticeable, or it throws off some optimizations. Or maybe something else altogether.

**Comment by bradcray** [comment]
I think this is resolved now based on last night's graphs.  @ronawho, do you agree?

**Comment by ronawho** [comment]
Agreed, resolved by https://github.com/chapel-lang/chapel/pull/14057
