### ISSUE TITLE
Returning from try block leaks memory

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#14058]
test/mason/publish-tests/packageName.chpl currently leaks because the
[getPackageName](https://github.com/chapel-lang/chapel/blob/master/tools/mason/MasonPublish.chpl#L351) returns from a try block. A simpler reproducer:

```chapel
class MyError : Error {
  var msg:string;
  proc init(msg:string) {
    this.msg = msg;
  }
  override proc message() {
    return msg;
  }
}

proc test() throws {
  try! {
    throw new owned MyError('Error msg');
    return 0;
  }
  catch {
    return 1;
  }
}

try! {
  test();
}
catch e: MyError {
  writeln(e.message());
}
```
The leak goes away if the returns in `proc test` are commented out

SHA: 3351818e8efca4558f542afcf88cdf036b2f3890

**Comment by bradcray** [comment]
Vaguely related (in that they relate to leaks within error handling patterns): #12092, #12511.

**Comment by e-kayrakli** [comment]
The test mentioned above and the reproducer no longer leaks. I don't know what fixed it, but recent work on memory management in the compiler is the likely reason. Closing.
