### ISSUE TITLE
Add --keep-going to docs build when sphinx 1.8+ supported

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#14085]
Add `--keep-going` flag to `SPHINXOPTS` in `Makefile.sphinx` when Sphinx 1.8+ is supported (we pin Sphinx 1.3.3 as of opening this issue). This will allow building with `-W`, but still getting the full report of all errors rather than failing immediately when a build fails, which is helpful when developing.

**Comment by ben-albrecht** [comment]
Blocked by interface changes needed to support a newer sphinx: https://github.com/chapel-lang/sphinxcontrib-chapeldomain/issues/29

**Comment by jabraham17** [comment]
Closing, `doc/Makefile.sphinx` has had `--keep-going` since https://github.com/chapel-lang/chapel/pull/17585
