### ISSUE TITLE
Problem with ! on unmanaged type

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#14092]
`!` on an unmanaged value results in the non-nilable unmanaged type.
But `!` on an unmanaged type results in the non-nilable borrowed type.

This is counter to expectations (I'm expecting `!` to leave the decorator the same in both cases, since `!` on types is intended to produce the same type as `!` on values).

Should `!` on the unmanaged produce the borrowed type or the unmanaged type?

I was initially expecting that `!` on unmanaged would always produce an unmanaged type.

**Comment by mppf** [comment]
In some off-line discussion, it's proposed to keep `!` on an unmanaged value giving unmanaged. However it's also proposed to deprecate `!` on types because it is confusing.

**Comment by vasslitvinov** [comment]
`!` on types is now deprecated. `!` on a value is [defined in the spec](https://chapel-lang.org/docs/master/language/spec/classes.html#nilable-class-types) to return a borrow except for an unmanaged.

Consider this issue resolved.
