### ISSUE TITLE
Unhelpful error message when swapping owned wrappers

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#14120]
### Summary of Problem
Swapping an owned wrapper generates an unhelpful error message.

### Steps to Reproduce

**Source Code:**

```chapel
class Dog { }

record DogOwner {
  var pet: owned Dog?;

  proc init() {
    this.pet = new owned Dog();
  }
}

var p1 = new DogOwner();
var p2 = new DogOwner();

p1 <=> p2;
```

**Compile command:**
```chpl
> chpl dog.chpl

$CHPL_HOME/modules/internal/ChapelBase.chpl:1914: error: const actual is passed to 'ref' formal '_arg2' of =
dog.chpl:3: note: to formal of type DogOwner
dog.chpl:4: note: to ref formal here
```

One can work-around this by defining a swap overload for their record:

```chpl
proc <=>(ref a: DogOwner, ref b: DogOwner) {
  var tmp = a;
  a = b;
  b = tmp;
}
```

### Configuration Information

- Output of `chpl --version`: `1.20.0.c97f29147e`

**Comment by bradcray** [comment]
I threw together a simple fix for this in #14123.  There may be a more elaborate / precise way to fix it, but I don't think this approach has significant downsides.
