### ISSUE TITLE
UnitTest chpldocs need improvement

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#14146]
Looking at chpldocs for UnitTest as of v. 1.20 and guessing the purpose of the methods and their arguments:

* I think the thrown exceptions are a mix of ones used internally in the implementation and ones that indicate user mistakes. The chpldocs need to describe the user-level ones and say something like "this method throws (or: also throws other) exceptions that are used internally in the implementation".

  For example, `UnexpectedLocales`is user-level, `DependencyFound` and `AssertionError` are for the implementation. (I am guessing here.)

* Replace `UnexpectedLocalesError` with `UnexpectedLocales` in chpldocs.

* If `TestIncorrectNumLocales` is for the implementation, it probably should represent the required locale(s) as numbers, not text. For example, be a union (yeah!) of a range (for min/maxLocales) and a set (for addNumLocales). If it is for the user, it needs a message that tells the user what went wrong and ideally how to fix it.

* For `addNumLocales`, I think it means "Indicate how many locales to run the test on." In the current text, "locale values" and "in which" are inappropriate.
  - Explain what happens when there are multiple arguments.
  - Explain how this relates to `maxLocales` and `minLocales`.
  - Looking at the code of this method, I do not see the meaning of "add" in the method name. Would be great if chpldoc were phrased so that the user understood what is being added. In terms of user experience, that is, not implementation details.

*  For `dependsOn`, I suggest `Indicates which tests need to run prior to the current test.`

* In `addNumLocales` and `dependsOn`, use plain-text `comma-separated`. The current typesetting does not read smoothly. I am assuming the audience will know what "comma-separated" means.

* Use smoother language in other cases as well.

* I'd prefer to remove `:type` annotations in those cases where the method signature already shows that formal's type. This avoids duplication of information that is unnecessary IMO. If they were to stay, remove the period that comes after the type -- that period is not appropriate in the spot where it occurs when viewed online.

**Comment by vasslitvinov** [comment]
@lydia-duncan @ben-albrecht fyi

**Comment by ben-albrecht** [comment]
Hi @vasslitvinov - thanks for the feedback. I think all of the thrown exceptions are intercepted by the unit test runner (`mason test`) and therefore the entire submodule can be nodoc'd.

I agree with the feedback on the `UnitTest` module itself.

FYI @krishnadey30 as well.
