### ISSUE TITLE
`proc type this`?

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#14153]
Feature request?

The following code works.

```chapel
record Add {
    // but is there an equivalent to `proc type this` ...
    proc type op(x, y) {
        writeln((("add", x, y), x + y));
    }
}
record Mul {
    proc type op(x, y) {
        writeln((("mul", x, y), x * y));
    }
}

proc main() {
    var x = 2;
    var y = 3;

    proc fn(type Op) {
        // ... so I could write `Op(x, y)` instead?
        Op.op(x, y);
    }

    fn(Add);
    fn(Mul);
}
```
```terminal
((add, 2, 3), 5)
((mul, 2, 3), 6)
```

**Comment by BryantLam** [comment]
I admit it's a bit magicky, so maybe this isn't a good idea just for the sake of learnability.

**Comment by mppf** [comment]
@BryantLam - it looks like this is an example relevant to another issue? I'm having trouble understanding if it's additionally requesting some particular feature on its own? I.e. it shows some code that works, so.... what would the next step be?

**Comment by bradcray** [comment]
From the comments, I interpret the request as being to support `proc type this()` overloads so that in `main()`, `fn()` could apply an access to a type directly without having to go through a named method.  Tagging @benharsh for his thoughts on this since it seems like it could either get confused with current type signature syntax, or possibly help them through unifying concepts?

**Comment by benharsh** [comment]
Thus far an expression like "TypeName(...)" has specified a type, and something like ``proc type this()`` would conflict with that notion. I think such a feature would be more appropriate as some kind of user-defined type constructor.

Does this pattern really just want decent first-class functions?

**Comment by BryantLam** [comment]
> Does this pattern really just want decent first-class functions?

Yeah, you're probably right.

I don't think this request merits the confusion it would cause to type-based initialization. The code I showed is probably good enough, especially since constrained generics would make it more well-formed. Closing.
