### ISSUE TITLE
Should we allow comparison between bytes and string values?

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#14160]
Currently one can compare a string to bytes:

```chapel
"foo" == b"foo"; // compiles and evaluates to true
```

Should we keep allowing this?

Yes: because if the internal buffers are identical (in `strcmp` returns 0 sense), then they are convertible to one another without any loss. (this is not the case today, but it'll be when there is UTF-8 validation for strings)

No: This hints that strings are coercible to bytes (which they are not), and such comparisons are only allowable if there is coercion.

**Comment by e-kayrakli** [comment]
FWIW, `"foo" == b"foo"` runs and evaluates to false in python.

**Comment by bradcray** [comment]
From a symmetry perspective, I'd be disinclined to support this, and to require one to be cast to the other.

> FWIW, "foo" == b"foo" runs and evaluates to false in python.

Huh... any idea why?  Does Python permit '==' between any two values and return false if they aren't the same type?  (asks the second-worst Python programmer (TM))

**Comment by e-kayrakli** [comment]
> Huh... any idea why? Does Python permit '==' between any two values and return false if they aren't the same type? (asks the second-worst Python programmer (TM))

:) Yes

**Comment by bradcray** [comment]
If anything, that strengthens my opinion.  If someone _really_ wanted to compare them without the cast, we could introduce a package module that supported the comparison directly, but I don't think I'd do it in the base language.

**Comment by mppf** [comment]
> No: This hints that strings are coercible to bytes (which they are not), and such comparisons are only allowable if there is coercion.

I agree with this. I don't think `"foo" == b"foo"` should work unless string can coerce to bytes. And it doesn't right now (I can't remember if we are still considering it.)
