### ISSUE TITLE
export Chapel `string` as Python `string` for interop

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#14189]
Currently, when Chapel strings are returned / passed back to Python through exported routines, they end up as Python's `bytes` type rather than `string`.  I think we should be preserving their string nature as originally proposed in issue #12892.

**Comment by bradcray** [comment]
@dlongnecke-cray: This is done now, right?

**Comment by dlongnecke-cray** [comment]
Closed via https://github.com/chapel-lang/chapel/pull/14592.
