### ISSUE TITLE
Make `use` statements `private` by default?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#14183]
This is split off from a comment by @BryantLam on issue https://github.com/chapel-lang/chapel/issues/13801#issuecomment-536192797

As a Chapel programmer, I'd like my module-scope `use` statements to be `private` by default so that (a) a `use` doesn't accidentally leak symbols outside of my scope that I did not intend it to, (b) compile-time isn't wasted searching for symbols that I didn't intend for clients of my interface to get at anyway.

(note that non-module-scope `use` statements are already private by nature since they're local to some other scope).

**Comment by bradcray** [comment]
In an experimental branch that applies this rule to user code, only ~200 tests failed, many of which were due to shared frameworks that relied on public/transitive use.  ~20 minutes of work reduced the number to ~60.

**Comment by mppf** [comment]
Note that this issue is related to #13978. In particular, one of the suggestions in that issue is to make qualified access from a `use` visible only in the module in which that `use` appears. Making the `use` private by default has a similar effect for `use` statements that have default visibility. However I think if we went with the change in #13978, a `public use Lib` within a module `M` would not enable a module that has `import M` to do `M.Lib.something`. (Vs it would, with this change alone).

**Comment by mppf** [comment]
@bradcray @lydia-duncan - what needs to be done to close this issue?

**Comment by bradcray** [comment]
IIRC, currently `use` statements in internal modules are still public.  I didn't want to close this one until all `use` statements are treated uniformly.  Unfortunately, the entanglement in internal modules made making their `use` statements private non-trivial last I tried (the approach I took was to manually convert `use` statements into `private use` as much as possible; then when all were `private use`, to flip the bit in the compiler that currently special-cases internal modules).

**Comment by mppf** [comment]
But since this issue is about changing the default, couldn't we make the internal module use statements explicitly `public` if they aren't currently `private`? Anyway there is not a rush on it, I was just wondering if it was done.

**Comment by bradcray** [comment]
Yes, I suppose so.  I guess I just found that unsatisfying and didn't expect the issue to linger this long.  Maybe put another way, I'd be happier if all the internal modules only relied on private uses.  I wouldn't object to taking the approach you propose, though (just don't have the cycles to do it myself right now, and it's not particularly user-facing, so it's not near the top of my list for others either).

**Comment by bradcray** [comment]
I believe this has long been complete now, so I'm closing it.
