### ISSUE TITLE
swapping two `writeln` incorrectly allows program to compile?

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#14185]
Bug. The following program does not compile; however, if you swap the order of the last two lines in `main`, the program compiles. Both programs should have the same behavior. From #14184, I think that means they shouldn't compile.
```chapel
module NewTypeMod {
    record NewType {
        var x: int;

        proc writeThis(f) {
            f <~> "NewType with " <~> x;
        }
    }
}

module Mod {
    private use NewTypeMod;

    proc makeNewType() {
        return new NewType(42);
    }
    proc wr(x: NewType) {
        writeln(x);
    }
}

module User {
    private use Mod;

    proc main() {
        var x = makeNewType();
        writeln(x);
        wr(x);
    }
}
```
```terminal
$CHPL_HOME/modules/standard/IO.chpl:3142: error: unresolved call 'NewType.writeThis(channel(true,dynamic,false))'
$CHPL_HOME/modules/internal/ChapelBase.chpl:2256: note: this candidate did not match: chpl_ModuleDeinit.writeThis(ch)
$CHPL_HOME/modules/standard/IO.chpl:3142: note: because method call receiver with type NewType
$CHPL_HOME/modules/internal/ChapelBase.chpl:2252: note: is passed to formal 'this: borrowed chpl_ModuleDeinit'
$CHPL_HOME/modules/internal/CString.chpl:205: note: candidates are: c_string.writeThis(x)
$CHPL_HOME/modules/internal/Bytes.chpl:306: note:                 bytes.writeThis(f)
```

If you reorder the last two lines in `main`, it compiles.
```chapel

    proc main() {
        var x = makeNewType();
        wr(x);
        writeln(x);
    }
```

`chpl version 1.21.0 pre-release (b2b1b701)`

_Originally posted by @BryantLam in https://github.com/chapel-lang/chapel/issues/14184#issuecomment-536868622_

**Comment by bradcray** [comment]
I suspect that the change in behavior due to the order of the two write calls is due to our current point-of-instantiation semantics. @mppf, would you agree?

**Comment by mppf** [comment]
Right, because the current compiler only uses one point-of-instantiation when computing a generic function. In this case, `writeln(arg: NewType)`. 

If you have 
```
        wr(x);
        writeln(x);
```

and `wr` calls `writeln` with a `NewType`, then `writeln(arg:NewType)` is instantiated at that point (which, notably, has visibility to see `NewType.writeThis` due to the use statement).

If the `wr(x)` call is omitted or put after `writeln(x)`, then the `writeln(arg:NewType)` call is resolved in `main` and it in turn tries to call `NewType.writeThis` but that fails because this function is not visible in scope (neither from writeln's point of definition or the point of instantiation here, which is `main`).

**Comment by bradcray** [comment]
@BryantLam: Note that this is something we aim to address (and were talking about earlier this week), not an assertion that things are as they should be.

**Comment by mppf** [comment]
Here is another example that demonstrates how the point-of-instantiation rule can be surprising. This is discussed in [CHIP 2](https://github.com/chapel-lang/chapel/blob/master/doc/rst/developer/chips/20.rst#duplicate-instantiations-in-different-scopes)

``` chapel
module LibraryOne {
  use GenericLibrary;
  proc foo(i: int) {
    writeln("LibraryOne.foo");
  }
  callFoo(1);
}
module GenericLibrary {
  proc callFoo(param x) {
    foo(x);
  }
}
module LibraryTwo {
  use GenericLibrary;
  proc foo(i: int) {
    writeln("LibraryTwo.foo");
  }
  callFoo(1);
}
module Application {
  use LibraryOne;
  use LibraryTwo;
  proc main() { }
}
```

**Comment by cassella** [comment]
The original program now compiles and produces the same output no matter the order of the last two statements in `main()` (after marking `writeThis()` as a throwing function).

**Comment by mppf** [comment]
I think this is due to changes @vasslitvinov made. @vasslitvinov - could you add two tests to make sure that the program above has the same behavior if the last two statements are swapped and then close this issue if everything looks OK?

**Comment by bradcray** [comment]
I needed a study break after a long week, so put this together here:  https://github.com/chapel-lang/chapel/pull/17292

**Comment by bradcray** [comment]
This is resolved due to Vass's POI changes (in the last release, I believe?)
