### ISSUE TITLE
compiler/main/CLANG_SETTINGS is not cleaned during clobber?

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#14197]
Bug. Build system?

I ran into the exact same error message from #12881, but on a completely different system environment.

### Comment from previous attempt to diagnose
From https://github.com/chapel-lang/chapel/issues/12881#issuecomment-491278788, @mppf said:

> could you check if your $CHPL_HOME that you built has the file compiler/main/CLANG_SETTINGS ? (It should not, and if it does, the question will be "how did it get there?").

In #12881, `CLANG_SETTINGS` was not present (as far as I remember). This issue, however, **did** have this file in my build.

### Environment
```terminal
CHPL_HOST_PLATFORM: linux64 *
CHPL_HOST_COMPILER: gnu
CHPL_HOST_ARCH: x86_64 *
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: system *
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_LLVM: llvm *
CHPL_AUX_FILESYS: none
CHPL_LIB_PIC: pic *
```

(This issue emits the error message even though `CHPL_HOST_COMPILER`, `CHPL_TARGET_COMPILER` and `CHPL_LLVM` are set to values that were okay in #12881 (No.6).)

### History
Some point in the past, this system used `CHPL_LLVM=none`.
Later, it switched to `CHPL_LLVM=llvm`.
And sometime afterward, there was one time that I `make clobber`'d it.

Clobbering doesn't delete the `CLANG_SETTINGS` file (wherever it came from). Is this intentional?

After I manually removed the `CLANG_SETTINGS` file and rebuilt, the error went away during app-compilation time.

If I restore the removed `CLANG_SETTINGS` file, then run the following, the app-compilations break again.
```terminal
cd compiler
make clobber
cd ../ && make
```

This issue is unfortunately just loose notes because I haven't been able to reproduce where the `CLANG_SETTINGS` file came from.

`chpl version 1.21.0 pre-release (b736500a)`

**Comment by mppf** [comment]
@BryantLam - From release-to-release, we don't expect the CHPL_HOME directory to be replaced in-place. In this case in a previous release, we moved the CLANG_SETTINGS file. So the only way it would end up in compiler/main/CLANG_SETTINGS is if you had been tracking master.

We could be satisfied that the problem will not occur in a release and expect people following master to find this issue (if they run into the problem).

Or, we could update the compiler to delete `compiler/main/CLANG_SETTINGS` on a `make clobber` even though the file at that path is never created with the current Makefiles.

**Comment by BryantLam** [comment]
Either approach is okay now that I know what the problem is. However, I'm more interested in understanding or resolving why this-file-that-cannot-be-created is actually affecting the compiler's behavior at all. (Is it like a manual override?) What's using this file? The build system? The compiler itself? Why not change the behavior to ignore the file regardless of whether it exists in this location?

**Comment by mppf** [comment]
@BryantLam - the file is `#include`d into the compiler source code and since we want to be able to have headers for the compiler in compiler/main (and do so) that directory needs to be in the include path.

**Comment by BryantLam** [comment]
Okay I see where it's used. I'm okay doing nothing, since the old file is at least detected as a git untracked file.

**Comment by bradcray** [comment]
Is there any chance #12881 was due to a similar stray file hanging around?

**Comment by BryantLam** [comment]
I need to go back and look. The problem with #12881 was sufficiently different (trying to use `CHPL_LLVM=system`) that when I initially saw the `CLANG_SETTINGS` comment, I think(?) I checked and ruled it out.
