### ISSUE TITLE
Should we deprecate c_string?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#14215]
Several of us are thinking it would be wise to deprecate `c_string` and instead rely on `c_ptr(c_char)` and related types. Since `c_string` actually refers to `const char*`, presumably it would be necessary to first solve #14214 to allow one to write something like `c_ptr_const(c_char)`.

Why deprecate `c_string` ?
 * C doesn't really have strings
 * It exists for historical reasons
 * It causes confusion about the ownership of `c_string` (e.g. one might assume that `myString.c_str()` should be freed, when in fact it just aliases the data)

**Comment by bradcray** [comment]
I think this issue should be retitled "How soon can we..."  :D

**Comment by e-kayrakli** [comment]
Just as a note, on an offline discussion @bradcray suggested that we can add a `--warn-unstable` warning in 1.21 if we don't get to deprecate the `c_string` type altogether.

**Comment by dlongnecke-cray** [comment]
I think that a good start for this is to deprecate support for `c_string` in our interop story. This would be quite feasible to do now that we have support for exporting both the `string` and `bytes` type.

**Comment by ben-albrecht** [comment]
To help port `c_string` codes to `c_ptr(c_char)`, there ought to be an easy way to get a `c_ptr(c_char)` from a Chapel string like we have for `string.c_str()` to get a `c_string`... or does something like this already exist?

**Comment by mppf** [comment]
I suspect we would simply have `string.c_str()` return `c_ptr(c_char)`.

Also, the issue description talks about `c_ptr_const` - so maybe `string.c_str()` would return `c_ptr_const`. At the very least that would indicate that users aren't supposed to modify the elements (even though they technically can, in the C type system...)

**Comment by mppf** [comment]
Or, maybe we would a method with a new name, like `string.ptr` or `string.c_ptr` or something.

**Comment by e-kayrakli** [comment]
> I suspect we would simply have string.c_str() return c_ptr(c_char)

Possibly. It may get a bit too tangled up and may require some effort, though. 

At times I wonder whether we can have `c_ptrTo(myString)` return the buffer pointer for strings. I am not sure whether we'd lose anything by not being able to get the address of the string record, though.

**Comment by mppf** [comment]
@e-kayrakli - I wouldn't like that for the same reasons I don't like `c_ptr(someArray)` returning a pointer to the first element. But it would be fine to separate the concerns into 2 different functions.

**Comment by bradcray** [comment]
It'd be interesting to look into having c2chapel generate `c_ptr(c_char)` instead of `c_string` since that's a purer representation of the code.  I do worry a little about const-ness issues due to issues like https://github.com/chapel-lang/chapel/issues/18790.  That said, I don't think that's a good reason to stick with `c_string`, and we should just improve our c_ptr story instead.

I think it'd also be reasonable to request convenience features that might make sense—w.r.t. the cast to bytes, can you use the createWith... routines to have a bytes wrap your buffer instead of a cast?  (which may be the better thing to do anyway... to me, a cast would probably want/need to create a deep copy of your buffer, which I'm guessing is not what you want?)

**Comment by bmcdonald3** [comment]
> a cast would probably want/need to create a deep copy of your buffer, which I'm guessing is not what you want?)

I actually do want a deep copy in this case because I am passing a pointer to C and then my C routine is allocating the memory, so I need to deep copy the values into a Chapel-allocated buffer, but, then I would think I could just use the `createWithNewBuffer` variant.

**Comment by bradcray** [comment]
I agree that casting could be an attractive shorthand for "copy into this new value" behavior if you want to feature request it (I'm trying to remember whether we've discussed it before...).

**Comment by arezaii** [comment]
`c_string` was deprecated in user facing modules in https://github.com/chapel-lang/chapel/pull/22622. It still exists in the compiler as `chpl_c_string` for now, but will be removed in a future PR.

**Comment by bradcray** [comment]
Hoorah!  A gargantuan effort.  I think you could close this issue based on the current status—I view the removal of `chpl_c_string` as being separate from the original issue here and more as a housekeeping item for developers than something as user-facing as the OP here.
