### ISSUE TITLE
Creating record-wrapped classes in a for expression causes compilation errors

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#14246]
The below snippet does not compile:

**Source Code:**

```chapel
class C {
  var x: int;
}

record R {
  var c: C?;

  proc init() { }

  proc init(val: int) {
    this.c = new C(val);
  }
}

var r = for i in 0..2 do new R(i);
writeln(r);
```

**Compiler output:**
`error: non-lvalue actual is passed to a 'ref' formal of chpl__initCopy()`

**Comment by e-kayrakli** [comment]
I played around with this a bit today. If the field `c` is unmanaged, this works. I think the problem is with the `owned`'s initCopy which needs to take rhs as `ref`. But here, the elements from the iterator expression are yielded as const. So, the error that we're getting comes from that constness mismatch.

**Comment by e-kayrakli** [comment]
@mppf -- this should work, right?

**Comment by DanilaFe** [comment]
A member of Iain's capstone team stumbled upon this bug and it turned out it was a relatively easy fix (thanks @vasslitvinov for doing much of the initial investigation). I'll be opening a PR shortly.
