### ISSUE TITLE
Make `<<` well-defined for signed integers

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#14305]
As a Chapel user, I'd like `<<` to be well-defined on signed integers so that I don't need to work around it for cases like this: 

```chapel
var shifted = (((mySignedInt): uint) << 1): int;
```

**Comment by dlongnecke-cray** [comment]
I think that this is already handled in `ChapelBase.chpl`? 

```chapel
  inline proc <<(a: int(?w), b: integral) return __primitive("<<", a, b);
  inline proc <<(a: uint(?w), b: integral) return __primitive("<<", a, b);
```

At least, this code compiled and ran without issue as of 61fb7d1:

```chapel
proc whatWeHave(): int(64) {
  var mySignedInt = 128;

  var shifted = ((mySignedInt:uint) << 1):int;

  assert(mySignedInt.type == shifted.type);

  writeln("Before shift: ", mySignedInt.type:string, ", ", mySignedInt);
  writeln("After shift: ", shifted.type:string, ", ", shifted);

  return shifted;
}

proc whatWeWant(): int(64) {
  var mySignedInt = 128;
  var shifted = mySignedInt << 1;

  assert(mySignedInt.type == shifted.type);

  writeln("Before shift: ", mySignedInt.type:string, ", ", mySignedInt);
  writeln("After shift: ", shifted.type:string, ", ", shifted);

  return shifted;
}

var a = whatWeHave();
var b = whatWeWant();

assert(a == b);
```

```
Before shift: int(64), 128
After shift: int(64), 256
Before shift: int(64), 128
After shift: int(64), 256
```

**Comment by bradcray** [comment]
I don't think there's any guarantee that just because the behavior's the same in one run that it's the same in every run.  I.e., we may just be getting lucky with a C compiler that does what we want.  I think you'd need to check the generated code to be sure.  If it's doing the casting to uint there, then we're probably good.  If it's not, then I think we need to codegen that case for signed ints to do the cast.

**Comment by dlongnecke-cray** [comment]
Ok so it looks like the codgen for `PRIM_LSH` doesn't do any casting to unsigned, it just does a raw C shift with the arguments, which would mean we are at the mercy of the C compiler.

It sounds like we want lshift for signed ints to be equivalent to "cast both arguments to uint, shift, cast back"? 

How do we want to handle undefined behavior in the C language, IE when the shift-by expression is negative? 

Either way, I'm guessing that it's probably easiest to implement this behavior in `ChapelBase.chpl` rather than try and muck with codgen for `PRIM_LSH`.

**Comment by dlongnecke-cray** [comment]
FWIW the spec says:

```
The type of the second actual argument must be any integral type.
The << operator shifts the bits of a left by the integer b. The new low-order bits are set to zero.
The >> operator shifts the bits of a right by the integer b. When a is negative, the new high-order bits are set to one;
otherwise the new high-order bits are set to zero.
The value of b must be non-negative.
```

**Comment by bradcray** [comment]
> It sounds like we want lshift for signed ints to be equivalent to "cast the first argument to uint, shift, cast back"?

I think that's what we agreed...  @mppf is that right?

> How do we want to handle undefined behavior in the C language, IE when the shift-by expression is negative?

Hmm... I don't think we discussed that... maybe compilerError when it's a param and is negative, halt when it's not a param and bounds checking is on, let it through otherwise (?).

> Either way, I'm guessing that it's probably easiest to implement this behavior in ChapelBase.chpl rather than try and muck with codgen for PRIM_LSH.

That sounds right to me.

**Comment by dlongnecke-cray** [comment]
That sounds reasonable. For the non-param version that halts, do we want that to be able to be turned off, i.e, with `--no-checks`?

**Comment by mppf** [comment]
> Either way, I'm guessing that it's probably easiest to implement this behavior in ChapelBase.chpl rather than try and muck with codgen for PRIM_LSH.

I think implementing it in ChapelBase is reasonable. For the LLVM backend could simply not supply `nsw` to get the 2-s complement behavior for signed integers. Even so, I expect that casting to `uint` will produce pretty much the same code in LLVM IR.

**Comment by mppf** [comment]
> > It sounds like we want lshift for signed ints to be equivalent to "cast the first argument to uint, shift, cast back"?
> 
> I think that's what we agreed...  @mppf is that right?

That will do it, as far as I know.

**Comment by dlongnecke-cray** [comment]
The standard mentions nothing about what to do when the second argument (the shift-by expression) is larger than the number of bits in the first argument.

I know that in i.e C++ that is undefined behavior.

Should I add an error check for this case as well, or just leave it up to the mercy of the C compiler?

**Comment by mppf** [comment]
@dlongnecke-cray - I think it would be nice to have a check for that within a boundsCheck conditional (so no additional checking happens with `--fast`). I'm expecting that it is Undefined Behavior, whether or not there is an error, though.
