### ISSUE TITLE
Should non-nilable to nilable count as a subtype relationship?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#14307]
This is a follow-up to #13541 which includes the idea that A is a subtype of B if A could be passed to a `const ref arg:B` argument.

This issue discusses this question specifically for non-nilable and nilable types, e.g. `isSubtype(C, C?)`, which, put another way, is whether we can pass an argument of type `borrowed C` to `proc f(const ref arg: C?)`. This was originally discussed in https://github.com/chapel-lang/chapel/issues/13541#issuecomment-517693254 :

> ### Nilability
> 
> In this context, we are talking specifically about coercions related to nilability. Those coercions are from a non-nilable actual to a nilable formal. E.g.
> 
> ``` chapel
> proc f(const ref arg: borrowed MyClass?) {
> }
> var x: borrowed MyClass = ...;
> f(x); // applies coercion from MyClass to MyClass?
> ```
> 
> Since all nilability for classes is removed before the aliasing rules apply, we could allow a `const ref` to point to something declared with the other nilability. However, for things like `int?` which we imagine are one day implemented as an `Optional`, the `Optional(int)` would contain the memory necessary to store the `int`, so it'd be possible to get a `const ref` to the `int` from an `int?`. However, one can't find an `int?` in the same memory as an `int`, which is the direction we want to go here.
> 
> As a result I would consider `something` -> `something?` to be a coercion and not subtyping.

There are two points to make here in favor of changing the current behavior to consider it subtyping:

1. Since nilable and non-nilable classes, and coercions between them, are relatively important language features, it would be better for `isSubtype(C,C?)` to return `true` and `C` be allowed to pass to a `const ref arg:C?` argument; even if this did not apply to `option(int)`. This is important to make `owned` and `shared` behave naturally.
2. Although one can't store an `int?` in the same memory as an `int`, one *can* store a `const ref arg: int` in the same memory as a `const ref arg: int?` since in the implementation, the nil value could be stored in the reference, rather than in the `int`. This last point could perhaps be used to allow, for a record R, a `R` to pass to a `const ref R?` argument.

Note: We won't be able to actually allow passing these subtypes by `const ref` until we solve #8489, potentially by migrating to the LLVM backend.

**Comment by vasslitvinov** [comment]
It is an interesting idea to represent a `const ref int?` formal by using a null pointer to indicate absence. If we do this, it will be a different representation than for a `ref int?` formal or variable. And perhaps even different than for a `const ref int?` local variable if it aliases an int? variable.

More importantly, this representation will have a different behavior than my second bullet above. That is, when an `int?` variable is passed to a formal of this representation, the "absence" property will be snapshot at the time of the call. The formal will no longer track concurrent changes to the "absence" property of the actual.

Because of these, I suggest we do not count on this representation.

**Comment by vasslitvinov** [comment]
The current choice is yes, to consider `C` a subtype of `C?`, separately for each memory management strategy, including generic strategy.

* See #14773 esp. the subsection for "owned C <= owned C?".

* The main downside of this choice is the different behavior from `int` vs. `int?`. However, integers and other non-class types are already substantially different from class type, for example `real` is not a subtype of `int` and `int(64)` is not a subtype of `int(8)`. So we accept the difference w.r.t. nilability/option behavior as well.
