### ISSUE TITLE
Support `bytes.format()`

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#14304]
As a Chapel user, I'd like a `bytes.format()` routine that serves the same role as `string.format()` in order to store arbitrary variables into a bytes variable as binary (or non-binary) data (given that such binary representations are not likely to be legal strings).

**Comment by e-kayrakli** [comment]
I am only confused about the word "array", are you proposing something more specific to arrays, or do you mean "byte array" as in something that is consecutive in memory.

In a more practical sense, we should still be able to use scalars with this, right? e.g. something like 

```chapel
b"My integer: %i".format(10)
```

**Comment by bradcray** [comment]
I'd like the feature generally, it's not specific to arrays.  I've tried to rephrase the original (quickly thrown together) request to indicate that.  I was imagining `b"My array's data: %|t".MyArray;` when I wrote it.  I've also removed the mention of 0 bytes to focus more generally on data that may not be legal UTF-8.
