### ISSUE TITLE
Managed classes break type queries

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#14314]
### Summary of Problem

While writing a type query that I believe we've supported for several releases, I found that it didn't work anymore as I'd expected (though  it looks like this has potentially been broken since 1.17.1).  

### Steps to Reproduce

**Source Code:**

```chapel
class Sender {
  type sendType;
}

class Receiver {
  type recvType1;
  type recvType2;
}

addEdge(new Sender(int), new Receiver(int, real));
addEdge(new Sender(int), new Receiver(real, int));

proc addEdge(s: Sender(?st), r: Receiver(?rt1, ?rt2)) {
  if (st == rt1 || st == rt2) {
    writeln("addEdge matches ", s.type:string, " and ", r.type:string);
  } else {
    compilerWarning(rt1:string);
    compilerError("bad addEdge match: ", s.type:string, " vs. ", r.type:string);
  }
}
```

**Compile command:**
`chpl foo.chpl`

**Output:**

```
foo.chpl:12: In function 'addEdge':
foo.chpl:12: error: invalid query -- queried field must be a type or parameter
foo.chpl:9: Function 'addEdge' instantiated as: addEdge(s: owned Sender(int(64)), r: owned Receiver(int(64),real(64)))
```

**Associated Future Test(s):**

Stay tuned...

### Configuration Information

- Output of `chpl --version`: 1.20.0

**Comment by bradcray** [comment]
@benharsh points out that managed class types are likely at fault.  Tagging @mppf for that reason.

**Comment by mppf** [comment]
I know of a variety of problems with type queries and managed classes, e.g. #10628  #10173

**Comment by bradcray** [comment]
Do you consider the others to also be breaking changes relative to prior releases?

**Comment by mppf** [comment]
Nope, but the root cause might be related. In this release we changed e.g. `Sender` to go from meaning `borrowed Sender` which the compiler represents most similarly to the old situation - to meaning `generic-management Sender` which is more similar to a decorated class type.
