### ISSUE TITLE
confusing error message upon 'this.complete;'

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#14319]
Right now `this.complete()` is legal, `this.complete;` is not. I propose to allow the latter as an alternative syntax for the former. I do not see downsides to that. The benefit is that if the user forgets to write parens, they do not need to go edit the file and recompile again.

Short of that, we need a better error message for paren-less `this.complete;`. Currently, when compiling the following:
```chpl
record MyRecord {
  var jjj: int;
  proc init=(other: MyRecord) {
    this.complete;             // error message is here
  }
}

var r1:	MyRecord;
var r2 = r1;
```
I get `error: cannot pass a record to a function before this.complete()`.
It would be nice to give a more direct indication of what needs to be fixed.

**Comment by bradcray** [comment]
It's hard to tell from the issue whether you know this, but the error relates to `this.complete()` not having parens after it.

**Comment by vasslitvinov** [comment]
Right. This is what I would like the error message to say.

Better yet, just allow `this.complete;` without `()`. That will make things even easier. I know we preferred the paren-ful option in the past. I think there is no downside allowing both syntaxes.

**Comment by vasslitvinov** [comment]
I repurposed this issue to propose allowing `this.complete;` without parens.

**Comment by BryantLam** [comment]
I'd prefer a compiler error that says "did you mean `this.complete()`?".

(I also personally think paren-less functions aren't desirable and wouldn't want to use them for anything other than properties of a type.)

**Comment by vasslitvinov** [comment]
If we had no paren-less functions in the language, then disallowing parens on `complete` would make more sense to me.

However, `complete` is neither a function/function call nor a property, it is a syntactic marker akin to a semicolon or a curly brace. So we need a different argument here.

**Comment by bradcray** [comment]
> However, complete is neither a function/function call nor a property, it is a syntactic marker akin to a semicolon or a curly brace.

This is true, but it was designed to be a syntactic marker that would look like a function call ("Please go do something for me and then return once you have completed it"), so I think it's reasonable to require the parenthesis and to generate a helpful warning if they're accidentally omitted.

**Comment by bradcray** [comment]
@vasslitvinov : I believe this can be closed now that @DanilaFe implemented `init this;` as the replacement for `this.complete();` in https://github.com/chapel-lang/chapel/pull/23283, so will close this issue.  Please re-open or let me know if you disagree.
