### ISSUE TITLE
init(vararg...) not to be considered for copy initialization?

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#14313]
When I write an initializer taking varargs, I am not intending it to be used as a copy initializer. Even though, by our resolution rules, it would be applicable for a copy-initialization call.
```chpl
record MyRecord {
  proc init(arg...) { /*create a record from whatever args come in*/ }
}

var r1 = new MyRecord(.......);
var r2 = r1;  // currently, warning: 'init' has been deprecated as the copy-initializer
```

I propose to exclude such init() method as a candidate for copy initialization.

**Comment by mppf** [comment]
@vasslitvinov  since now we write copy initializers at `init=` we can presumably close this issue?

**Comment by vasslitvinov** [comment]
Sounds good. Closing.
