### ISSUE TITLE
weird syntax error when attemping to use multiple inheritance non-feature

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#14357]
Bug. Does Chapel support multiple inheritance? I think the answer is no. This code attempts to use multiple inheritance and gets a weird syntax error.

```chapel
class Base1 {}
class Base2 {}
class Derived: Base1, Base2 {}

proc main() {
  var d = new Derived();
}
```
```terminal
# chpl version 1.20.0
error: can't omit initialization of field "super", no type or default value provided
```

**Comment by bradcray** [comment]
You're correct that, at present, there's no support for multiple inheritance (nor a plan to support it).

**Comment by DanilaFe** [comment]
The error message is now much better on `main`. From  `test/classes/figueroa/DestructorSubclassing2.good`, which locks this down:

```
error: invalid use of multiple inheritance in class 'C'; only single inheritance is supported
```
