### ISSUE TITLE
Weird string search regression from #14310

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#14376]
There was a performance regression from "Support the Chapel bytes type in single locale Python interop" (#14310) for the string search test. 

Here's a [graph](https://chapel-lang.org/perf/chapcs/?startdate=2019/10/18&enddate=2019/10/31&graphs=searchesovernstrings):

![image](https://user-images.githubusercontent.com/1588337/67993318-b785f380-fc16-11e9-8555-89ad5f1a76cb.png)

That PR should really only have impacted `--library` compilation so it's a little confusing. It did add a `use ByteBufferHelper;` to `ExportWrappers`, which is currently included from `ChapelStanard`, which results in `ByteBufferHelper`'s init getting called from `ChapelStandard`. 

The regression can be "resolved" by commenting out the call to `chpl__init_ByteBufferHelpers()` from `chpl__init_ChapelStandard()` in the generated code. `chpl__init_ChapelStandard()` is only called once at startup, so this really doesn't make sense so we're chalking it up to cache effects. 

We can avoid the `use ByteBufferHelper;`, which will resolve the regression but we don't really understand the root cause. Longer-term `ExportWrappers` probably shouldn't be part of ChapelStandard. Maybe the compiler could add the use for it like we do for ISO_Fortran_binding

**Comment by ronawho** [comment]
Misc other changes to the benchmark code also restore the old performance so I think this is just cache-effects on a microbenchmark and nothing to worry about. https://github.com/chapel-lang/chapel/pull/14377 seems like a nice cleanup and happens to resolve this so I think we're going to go ahead with that.

**Comment by bradcray** [comment]
> Longer-term ExportWrappers probably shouldn't be part of ChapelStandard. Maybe the compiler could add the use for it like we do for ISO_Fortran_binding

This is a really attractive idea, particularly given my current "We should stop including the world when compiling hello.chpl" mentality.  Tagging @dlongnecke-cray on this idea because I think this should be fairly easy and he was just musing about looking for something to do in his copious spare time.  :)
