### ISSUE TITLE
Trouble returning access of map

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#14370]
### Summary of Problem

While working with the map class with a valueType that's a managed class, I'm having trouble returning a borrow of an access of the map from a routine, getting the message "Scoped variable cannot be returned."  This seems to occur only when declaring a return type for the routine.  I think that this should be legal,right?

### Steps to Reproduce

**Source Code:**

```chapel
use Map;

class C	{
  var x: int;
}

var m: map(string, shared C);

m["hi"] = new shared C(42);

proc foo(): borrowed C {
  return m["hi"].borrow();
  // return m["hi"];  // this doesn't work either
}

writeln(foo());
```

**Compile command:**
`chpl foo.chpl`

### Configuration Information

- Output of `chpl --version`: 1.20.0

**Comment by bradcray** [comment]
Tagging @daviditen because of the use of `map`, though the core problem could be unrelated to map and more an issue with lifetimes and managed classes (or a misunderstanding of them on my part), so tagging @mppf and @vasslitvinov as well.

**Comment by bradcray** [comment]
As a workaround, if I write the function like this:

```chapel
proc foo(): borrowed C {
  ref mhi = m["hi"];
  return mhi;
}
```

it works.  But I don't think I should have to do this?

**Comment by bradcray** [comment]
Fiddling with this some more, I think that the issue is that the compiler changes `return m["hi"];` into:

```chapel
var tmp = m["hi"];  // tmp is a shared C
return tmp;
```

and thinks that you're returning a borrow of a local variable that's about to go out of scope.  But because the local is shared with a longer-lived variable (the entry within `m`), this shouldn't be an issue.  But should the compiler be able to figure this out without requiring me to insert a lifetime annotation?  It seems like it, and yet...

**Comment by mppf** [comment]
The compiler should be inferring the lifetime of `tmp` in the above to be `m` and so I would expect it to work. I think of this as a bug.
