### ISSUE TITLE
anymanaged class field with no object passed to default initializer -> internal error: Unhandled type in constIntentForType()

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#14379]
### Steps to Reproduce

**Source Code:**

```chapel
class Thing1 {
  var thing2: Thing2;
}

class Thing2 {}

var thing1 = new Thing1();

writeln(thing1);
```

```
$CHPL_HOME/modules/internal/ChapelIO.chpl:280: internal error: Unhandled type in constIntentForType() [passes/resolveIntents.cpp:63]
```

The nilability of `thing2` doesn't matter here.

If `thing1` is created as `new Thing1(new Thing2())`, it compiles and
runs fine.

If `thing2` is declared with a management class, it compiles and runs
fine if it's declared nilable, and gives an appropriate error if it's
non-nilable.  (I only tried `owned` and `unmanaged`.)  So it seems to
be specific to an `anymanaged` field.

This has a similar setup to #14378, but the symptom is different and
the code changes it's sensitive are different, so I opened this as a
separate issue.

**Associated Future Test(s):**
[`test/classes/delete-free/anymanaged/nilable-anymanaged-member-no-given-value.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/classes/delete-free/anymanaged/nilable-anymanaged-member-no-given-value.chpl
          ) #14382 
[`test/classes/delete-free/anymanaged/nonnilable-anymanaged-member-no-given-value.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/classes/delete-free/anymanaged/nonnilable-anymanaged-member-no-given-value.chpl
          ) #14382 

### Configuration Information

```
chpl version 1.21.0 pre-release (d010a3c)

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_LLVM: none
CHPL_AUX_FILESYS: none

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
```

**Comment by mppf** [comment]
This issue isn't just about anymanaged classes.

``` chapel
class Thing1 {
  var thing2: integral;
}

var thing1 = new Thing1();

writeln(thing1);
```

fails in a similar manner. In 1.19, this printed "error: unable to determine type of generic field", but we apparently had no tests of that error....
