### ISSUE TITLE
Design alternative to function overloads for deprecating non-function symbols

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#14396]
Context: I tried to add a deprecation warning for enums defined in the IO module in such a way that it only fired when the module was not explicitly used, and would not fire when an explicit use of IO was available to that scope.  I tried this by adding an argumentless function with the same name as the enum, which would warn and then return the IO module's type.  This kinda worked, but there were a few issues:
- We couldn't provide the same warning for the enum's constants, so it wasn't useful to warn because the program would just fail anyways
- While we always got the error when IO was not used, and never got the error when IO was used in an unlimited manner, `use IO only iomode;` did not allow us to access the enum and instead triggered the error message.  Similarly `IO.iomode.r` also triggered the error message.

Now, there's definitely some issues there about allowing functions to share the same name as types (and potentially variables, but that's another discussion), and potentially about how limitation clauses on use statements should respond even if we continue to allow that name sharing.  But given the other issue about not being able to warn for the enum's constants, and given that using a function in this case is kinda already a hack, maybe another solution could be used?

Brad suggested we extend "last resort" to apply to modules, and then use modules to provide deprecation warnings for things that functions can't support due to symbol conflicts.  This seems potentially tractable to me

**Comment by bradcray** [comment]
Thinking about this concept more on the way in, I was realizing that it isn't likely to work as well as I'd hoped yesterday.  Specifically, now that top-level modules have to be `use`d before they are referenced (and with it seeming increasingly likely that the same will apply to sub-modules), modules aren't as exchangeable with enums as they used to be.  So maybe instead what we should consider is a pragma- or otherwise language-based way of marking something as deprecated including a user-customizable error message so that one could simply slap a label onto an existing enum that it's going away rather than trying to come up with ways to pretend that it still exists through workarounds.

**Comment by lydia-duncan** [comment]
Aha!  It *was* due to using the symbols in the argument list, but kinda in a solvable way.

Basically, before I had this:
```chapel
pragma "last resort"
proc open(path:string, mode:iomode, hints:iohints=IOHINT_NONE,
          style:iostyle = defaultIOStyle()): file throws {
  compilerWarning("open will no longer be available by default,\nplease insert a use of the IO module to continue calling it.");
  return open(path, mode, hints, style);
}
```
And that triggered the warning because the deprecation functions were closer in scope to that function than to the IO symbols they were referring to.
But if I have this:
```chapel
pragma "last resort"
proc open(path:string, mode:iomode, hints:IO.iohints=IO.IOHINT_NONE,
          style:iostyle = defaultIOStyle()): file throws {
  compilerWarning("open will no longer be available by default,\nplease insert a use of the IO module to continue calling it.");
  return open(path, mode, hints, style);
}
```
I no longer get the deprecation message for IOHINT_NONE and iohints

**Comment by lydia-duncan** [comment]
(I updated the title to be less specific to the original proposal)

**Comment by lydia-duncan** [comment]
David Longnecker had to deprecate an enum in his #17070, which reminded me of this issue.  @bradcray and @mstrout - I think we should look into having someone flesh out a better way to deprecate non-function symbols in the next release cycle

**Comment by leekillough** [comment]
I like the idea of using `pragma "deprecated"` right before the declaration of a symbol to be marked as deprecated.

If `pragma` can support multiple arguments, a custom message could be optionally passed, as in:
```
pragma "deprecated" "reMatch is deprecated; use regexMatch instead"
type reMatch = regexMatch;
```
(https://github.com/chapel-lang/chapel/issues/17224)

If multiple `pragma` arguments are not supported, and it's not simple to add them, then we could look for the case-insensitive substring "deprecated" to mark the symbol as deprecated, and make the whole `pragma` argument the custom message.

**Comment by mstrout** [comment]
@lydia-duncan I put your suggestion on my list of things to discuss during our process deep dive.

**Comment by bradcray** [comment]
@mstrout: This feels to me less like a process question and more of a priorities / technical discussion topic (where the distinction to me is that priorities are about "What should we do?" and process more about "How should we do it?").

**Comment by lydia-duncan** [comment]
Pragmas don't currently support an additional string, but it does not seem like extending them to do so would be difficult if we want to go down that route, we'd just want to ensure it only applied to that particular pragma.

However, the use of a pragma for this would be a departure in another way: it would potentially be the first time a pragma would be intended for general use.  We've shied away from that in the past, is it worth doing for this case?

Other options off the top of my head:

-------

A deprecation block with a message.  E.g.
```chapel
deprecate {
  enum Foo { Bar, Baz};
} "This enum is deprecated, use enum Foo2 instead"
```
Or:
```chapel
deprecate "This enum is deprecated, use enum Foo2 instead" {
  enum Foo { Bar, Baz };
}
```

-------

A "deprecated" keyword that can be attached to any publicly visible symbol.  E.g.

```chapel
deprecate enum Foo {Bar, Baz};
```

Could use a message form as well/instead, e.g.

```chapel
deprecate "This enum is deprecated, use enum Foo2 instead" enum Foo {Bar, Baz};

deprecate "This enum is deprecated, use enum Blah2 instead"
enum Blah {x, y};
```

---------

An attribute syntax, as proposed by #14141
(Example from that issue adjusted):

```chapel
@attribute (deprecate)
enum Foo {Bar, Baz};
```

---------

Other ideas?

**Comment by bradcray** [comment]
> A "deprecated" keyword that can be attached to any publicly visible symbol.

This approach is where my intuition lies, though I'd probably use "deprecated" rather than "deprecate" (which is what you typed here, but the code examples use "deprecate").

**Comment by lydia-duncan** [comment]
Yeah, I don't feel strongly about whether it's "deprecate" or "deprecated" (but I meant to be consistent)

**Comment by e-kayrakli** [comment]
I really like

```chapel
deprecated "this enum is deprecated"
enum Foo {Bar, Baz};

deprecated "this proc is deprecated"
proc foo() { }
```

I'd like the keyword to be `deprecated` not `deprecate`.

---

Deprecation blocks are somewhat appealing for cases where what we are deprecating is not a symbol but some code block that executes under deprecated state/condition:

```chapel
proc foo(someArg) {

  if someParamFunctionThatReturnsBool(someArg) {
    deprecated "argument to foo where X, Y, Z is deprecated" {
       // do deprecated stuff
    }
  }
  else {
    // do new stuff
  }
}
```

but these cases can be refactored to use a deprecated proc, and we can think about adding this construct later on if there's enough motivating real use cases.

**Comment by mppf** [comment]
> ```
> pragma "deprecated" "Foo is deprecated; use Foo2 instead"
> enum Foo { Bar, Baz};
> ```

I'm not really in to this one. I think that if we want to have `pragma` do something other than set a flag, it's not `pragma` anymore and should be something else. In particular...

> An attribute syntax, as proposed by #14141

This is definitely my preference. I don't think we have to use `@attribute(deprecated)` specifically; that is an example attribute syntax meant to be a straw-person in #14141. There are a variety of ways we could write it.

> ```  chapel
> @attribute (deprecate)
> enum Foo {Bar, Baz};
> ```

``` chapel
@deprecated
enum Foo {Bar, Baz};
```

or even if we want to support a deprecation message

``` chapel
@deprecated
@replacement(Foo2)
enum Foo {Bar, Baz};
```

so that the compiler could suggest using Foo2 instead of Foo.

**Comment by mppf** [comment]
> This makes me prefer solutions that permit the person attaching the deprecation to specify the message rather than just specifying X and Y.

An attribute strategy can do this

``` chapel
@deprecated
@deprecationMessage("Some very long message")
proc = ( ref lhs: sync, rhs: sync) { ... }
```

(At this point I'm not trying to argue for specific attribute syntax or even specific ways to say the deprecation within it but hopefully the examples I've shown can be seen as straw proposals). 

I like the idea of `@replacement(Foo2)` for the cases where the error message is simple but it is not a big deal if we decide to only have a message.

**Comment by mstrout** [comment]
> However, the use of a pragma for this would be a departure in another way: it would potentially be the first time a pragma would be intended for general use. We've shied away from that in the past, is it worth doing for this case?

What is meant by a pragmas not being intended for general use?  In `chapel/modules/internal` I see >1500 uses of pragmas
```
pragma "no auto destroy"
pragma "order independent yielding loops"
pragma "aliasing array"
pragma "atomic module"
pragma "local fn" pragma "fast-on safe extern function"
pragma "no doc"
pragma "last resort"  // I have to admit being curious about what this one is about.
pragma "no copy"
...
```

So, I like @lydia-duncan 's suggestion to just extend the pragma.

The annotation idea is also interesting, but I would want to understand why we should add annotations to Chapel on top of pragmas.

**Comment by leekillough** [comment]
I have no preference on how this is implemented (pragma, attribute, block, declaration modifier, etc.).

About the objection to pragmas: I suggested it because usually pragmas are a "catch all" which can be used to handle these kinds cases without generating a lot of extra work for the compiler. If there is concern about documenting `pragma "deprecated"`, I was not proposing that; however if we rename symbols in the modules, thus deprecating them, we need a cleaner way of doing it than with wrapping `proc` with warnings around the uses of deprecated symbols.

**Comment by ben-albrecht** [comment]
Just adding that I like the attributes-based approach. Is there a running list of other feature requests that could benefit from attributes somewhere? We ought to make sure we're not excluding the ability to support those down the road in how we choose the attributes design.

> This makes me prefer solutions that permit the person attaching the deprecation to specify the message rather than just specifying X and Y.

It would be nice to support both if possible. Having a consistent standardized format of deprecation messages without having to go look up a reference will help both library authors and users interact with deprecation messages, and the "X replaced by Y" pattern accounts for the majority of deprecations.

**Comment by mppf** [comment]
> Just adding that I like the attributes-based approach. Is there a running list of other feature requests that could benefit from attributes somewhere?

Yes, it is the examples in issue #14141 (or at least I've been trying to update them when I find one; it's not necessarily complete)

**Comment by lydia-duncan** [comment]
It sounds like using attributes is the preferred strategy (though most of the people that support it also support a `deprecated` keyword, and that is the second top choice).  Thanks for the discussion, everyone!

**Comment by lydia-duncan** [comment]
Agreed.  I'll fully refresh my memory on the proposal and aim for having a deep dive in the next available slot.

**Comment by lydia-duncan** [comment]
In talking with Michelle and Brad after the fact, we feel that it's probably more effort than we want to spend right now to finalize attributes.  With that in mind, we're going to implement this using the keyword solution - while it will be unfortunate to remove the strategy when attributes come online, if we decide never to implement attributes later at least we won't have to also implement a more first-class, user-facing deprecation strategy regardless.

**Comment by mppf** [comment]
I'd don't really like the idea of making a user-facing language design choice (use a keyword for deprecation) based on the resourcing. If we need to make a resourcing choice like this then I think we should either put off this effort entirely until we have the resources to implement the preferred solution or we should create something that is not user-facing for our own use in the meantime.

**Comment by bradcray** [comment]
We could choose not to document for the user.  It would prevent them from using the identifier `deprecated`, but otherwise they'd be none the wiser.  I realize that may not make you any happier.

**Comment by bradcray** [comment]
(FWIW, I also think that we could get away without this feature for a good while longer yet as well)

**Comment by mppf** [comment]
> We could choose not to document for the user. It would prevent them from using the identifier deprecated, but otherwise they'd be none the wiser. I realize that may not make you any happier.

Actually this would make me happier. We can update the implementation into something attribute-y when we feel we have the cycles to do so and make it user facing at that time.
