### ISSUE TITLE
`Map` lacks function to unconditionally insert a key-value pair

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#14413]
Design discussion. `Map` has two functions to insert an element:
- `add` which fails if the key exists
- `set` which fails if key doesn't exist

What if I want to unconditionally insert? Today, I do this:
```chapel
use Map;

var m = new map(string, int);

proc always_set(ref map, key, value) {
  if map.add(key, value) == false {
    assert(map.set(key, value));
  }

  // Check my result:
  writeln(m);
}

always_set(m, "a", 1);
always_set(m, "a", 2);
always_set(m, "b", 11);
always_set(m, "b", 22);
always_set(m, "a", 3);
```
```terminal
{a: 1}
{a: 2}
{b: 11, a: 2}
{b: 22, a: 2}
{b: 22, a: 3}
```

This idiom requires worst-case two lookups per insert. Does Chapel want to provide some `always_insert` function? What to name this function to be unambiguous with `set`?

Aside: is there a difference between `update` and `+=`? I think `update` will replace the values of existing keys in `a` with `b`'s values whereas `+=` will not replace existing values in `a`.

**Comment by e-kayrakli** [comment]
I may be missing something but doesn't `proc this` do this? The following variation on your snippet gives the same output, for example:

```chapel
use Map;

var m = new map(string, int);

proc always_set(ref map, key, value) {
  m[key] = value;  // just assign to the key

  // Check my result:
  writeln(m);
}

always_set(m, "a", 1);
always_set(m, "a", 2);
always_set(m, "b", 11);
always_set(m, "b", 22);
always_set(m, "a", 3);
```

**Comment by BryantLam** [comment]
Ah dang. You're right. Thanks!
