### ISSUE TITLE
Use Github Actions?

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#14442]
Github actions is out of beta now -- https://github.com/features/actions

Github actions can provide CI testing (though it's not obvious to me yet if there's any concrete benefits to us over our current Travis-CI testing)

Beyond that, there are also "workflows", which seem interesting. There are workflows for "greeting" new contributors, auto-labeling PRs, marking stale issues, etc. https://github.com/actions/starter-workflows has those examples, and I suspect more will be added over time. I think https://github.com/actions is the repo to track

**Comment by lydia-duncan** [comment]
I think we could pretty easily automate most of the purple "area" labels

**Comment by bradcray** [comment]
> I think we could pretty easily automate most of the purple "area" labels

For issues that seems unlikely.  Do you mean for PRs?  My understanding is that we don't really expect purple labels to be applied to PRs, just to issues.

**Comment by lydia-duncan** [comment]
Yeah, I was referring to PRs but I'm probably the only person who adds it there

**Comment by ben-albrecht** [comment]
Using this as a place for GitHub automation feature requests:

- remove `stat: Waiting on Contributor` label when a commit is pushed to a PR

**Comment by ronawho** [comment]
We switched to github actions for CI testing in https://github.com/chapel-lang/chapel/pull/16227

I'm inclined to close this, and open new issues for other actions we'd like to add.
