### ISSUE TITLE
Missing config const inside a scope

### ISSUE THREAD

**Issue by npadmana** [chapel-lang/chapel#14440]
### Summary of Problem
If a `config const` is inside a scope, it appears to be hidden, unless it is of type string.

### Steps to Reproduce

**Source Code:**

```chapel
config const noFoo=false;

{
  config const noBar=10;
  config const help="";
}
```

**Compile command:**
`chpl foo.chpl`

**Execution command:**
`./foo --help` shows

```
foo config vars:
                      noFoo: bool
                       help: string
```
Note that `noBar` is missing.

### Configuration Information
chpl 1.20

**Comment by bradcray** [comment]
Hi Nikhil — Configs aren't intended to be supported at local scopes, but the compiler doesn't generate an error message for this as intended today (see issue #13108).  Is this an important pattern for you, or could the configs that led you to this issue just as easily be put at module scope?

**Comment by npadmana** [comment]
Hi Brad, Sorry for the slow response. This isn't an important pattern at all -- just happened to be how the code got written. Happy for you to close this as as a duplicate.

**Comment by bradcray** [comment]
Making it so.
