### ISSUE TITLE
Printing first-class functions and using scans on BlockDist don't mix

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#14467]
### Summary of Problem

When a program tries to both (1) print / stringify a first-class function and (2) compute a scan, problems occur due to arrays of sync variables used to implement the scan and a speculative attempt to resolve what writing those arrays out would do.

Specifically, I believe what's happening is that the compiler's dynamic dispatch machinery starts analyzing FCF->writeThis() which causes writeThis() to be considered / resolved for all classes / subclasses of object (or at least, more than just the first-class function).  The scan code contains an array of `sync bool` elements, and `sync`s don't support being written by default.  So if the scan code has been resolved, the compiler-generated writeThis() for the class implementing the array of bools is resolved as part of this dynamic dispatch processing, and we hit the error (even though no calls to write or stringify the array of sync bools are made).

I'm not sure how best to address this, but some thoughts I have offhand are:
* are we working too hard to resolve FCF->writeThis()?  Do we really need to be looking across so much of the object hierarchy for this case?  And/or could we save compile-time by not doing so?
* if we must do this resolution, it seems that we ought to be more resilient to resolution errors like this somehow—perhaps by ignoring them, or turning them into execution-time halts (?), particularly for compiler-generated routines?
* or maybe we could avoid creating compiler-generated writeThis() routines for types for which it would only be an error and have the error be manifested in another way if someone did try to write such a type out?

### Steps to Reproduce

**Source Code:**

```chapel
use BlockDist;

var A = newBlockArr({1..10}, real);
var B = + scan A;

proc foo() {
  writeln("In foo");
  return 42;
}

writeln("foo is: " + foo:string);
```

**Compile command:**
`chpl foo.chpl`

**Compiler output:**

(because I suspect that nobody will correlate this failure mode to this issue without it)

```
$CHPL_HOME/modules/standard/IO.chpl:3157: error: sync variables cannot currently be written - apply readFE/readFF() to those variables first
while processing the following Chapel call chain:
  $CHPL_HOME/modules/internal/ChapelSyncvar.chpl:178: _syncvar.writeThis(x) [internal module]
  $CHPL_HOME/modules/standard/IO.chpl:3157: _write_one_internal(_channel_internal: qio_channel_ptr_t, param kind: iokind, x, loc: borrowed locale?)
  $CHPL_HOME/modules/standard/IO.chpl:3201: channel.writeIt(x)
  $CHPL_HOME/modules/standard/IO.chpl:3235: <~>(ch: channel, x)
  $CHPL_HOME/modules/internal/DefaultRectangular.chpl:1616: recursiveArrayWriter(idx: 1*int(64), dim: int(64), last: bool) [internal module]
  $CHPL_HOME/modules/internal/DefaultRectangular.chpl:1774: chpl_serialReadWriteRectangularHelper(f, arr, dom) [internal module]
  $CHPL_HOME/modules/internal/DefaultRectangular.chpl:1575: chpl_serialReadWriteRectangular(f, arr, dom) [internal module]
  $CHPL_HOME/modules/internal/DefaultRectangular.chpl:1562: chpl_serialReadWriteRectangular(f, arr) [internal module]
  $CHPL_HOME/modules/internal/DefaultRectangular.chpl:1552: DefaultRectangularArr.dsiSerialReadWrite(f) [internal module]
  $CHPL_HOME/modules/internal/DefaultRectangular.chpl:1779: DefaultRectangularArr.dsiSerialWrite(f) [internal module]
  $CHPL_HOME/modules/internal/ChapelArray.chpl:2876: [].writeThis(f) [internal module]
  $CHPL_HOME/modules/standard/IO.chpl:3157: _write_one_internal(_channel_internal: qio_channel_ptr_t, param kind: iokind, x, loc: borrowed locale?)
  $CHPL_HOME/modules/standard/IO.chpl:3201: channel.writeIt(x)
  $CHPL_HOME/modules/standard/IO.chpl:3215: channel.readwrite(x)
  $CHPL_HOME/modules/internal/ChapelIO.chpl:281: writeThisFieldsDefaultImpl(writer, x, first: bool) [internal module]
  $CHPL_HOME/modules/internal/ChapelIO.chpl:337: writeThisDefaultImpl(writer, x) [internal module]
  $CHPL_HOME/modules/dists/ReplicatedDist.chpl:0: LocReplicatedArr.writeThis(f) [compiler-generated]
  $CHPL_HOME/modules/standard/IO.chpl:3151: _write_one_internal(_channel_internal: qio_channel_ptr_t, param kind: iokind, x, loc: borrowed locale?)
  $CHPL_HOME/modules/standard/IO.chpl:3201: channel.writeIt(x)
  $CHPL_HOME/modules/standard/IO.chpl:3235: <~>(ch: channel, x)
  $CHPL_HOME/modules/internal/DefaultAssociative.chpl:798: DefaultAssociativeArr.dsiSerialReadWrite(f) [internal module]
  $CHPL_HOME/modules/internal/DefaultAssociative.chpl:848: DefaultAssociativeArr.dsiSerialWrite(f) [internal module]
  $CHPL_HOME/modules/internal/ChapelArray.chpl:2876: [].writeThis(f) [internal module]
  $CHPL_HOME/modules/standard/IO.chpl:3157: _write_one_internal(_channel_internal: qio_channel_ptr_t, param kind: iokind, x, loc: borrowed locale?)
  $CHPL_HOME/modules/standard/IO.chpl:3201: channel.writeIt(x)
  $CHPL_HOME/modules/standard/IO.chpl:3215: channel.readwrite(x)
  $CHPL_HOME/modules/internal/ChapelIO.chpl:281: writeThisFieldsDefaultImpl(writer, x, first: bool) [internal module]
  $CHPL_HOME/modules/internal/ChapelIO.chpl:337: writeThisDefaultImpl(writer, x) [internal module]
  $CHPL_HOME/modules/dists/ReplicatedDist.chpl:0: ReplicatedArr.writeThis(f) [compiler-generated]
```

### Configuration Information

- Output of `chpl --version`: 1.20

**Comment by cassella** [comment]
If the array is not distributed, the error doesn't happen.  (`var A: [1..10] real;`)

The error happens with this writeln of an object instead of the FCF:

```chapel
var o: object = new object();
writeln("o is: " + o:string);
```

**Comment by bradcray** [comment]
Thanks Paul, I'd been wondering about that exact case over dinner tonight.  My guess is that we're storing the static type of FCF values as `object` rather than `the-specific-subclass-representing-the-FCF`, though that surprises me... I thought some change I'd made with FCF's recently suggested they were typed more specifically than that...

And the point about it being specific to BlockDist is a good one that I knew but didn't think to single out.  The arrays of bools are only allocated in the BlockDist's scan routines.  I'll edit the original description to be more precise.

**Comment by bradcray** [comment]
@mppf: When you're back from SC19, I'd be curious for your thoughts on this.

**Comment by buddha314** [comment]
Not sure if this is also related to this Arkouda issue I've come across https://github.com/mhmerrill/arkouda/issues/353

**Comment by cassella** [comment]
@buddha314 Did you mean to tag a different issue?

**Comment by bradcray** [comment]
@buddha314: Nope, there's no relation between these two issues.

**Comment by cassella** [comment]
Here's a simpler test case, no arrays or FCFs required.  Just having a class that contains a sync var does it:

```chapel
class C {
  var s$ : sync int;
}

var c: unmanaged C?;

var o: object = new object();
writeln("o is: " + o:string);
```

**Comment by bradcray** [comment]
I think I've got a strategy for fixing this.  Having @ronawho run into it again and thinking through it in the perf meeting today suggested a simple fix.

**Comment by bradcray** [comment]
My original strategy didn't work, but I came up with a different one which, though not as satisfying, seems better than the status quo.  Coming soon to a PR near you.

@casella, my PR will include your first test case, but not the second, because I _think_ your second is behaving as we'd want currently.  Specifically (unless I'm missing something), what happens is that the compiler generates default methods for classes that print themselves out when the user doesn't provide one, where that default method writes each field.  So it's reasonable that writing (or in this case, converting to string) a class that contains a sync would try to write that sync and hit the compilerError.  That said, I think we should define a default write() for syncs to make them less of an outlier, as discussed in issue #15891.

**Comment by cassella** [comment]
The second case writes only the object `o` that's actually an object.  class C is instantiated in the var `c`, but that variable isn't actually turned into a string.

**Comment by cassella** [comment]
> @ casella 
Sigh.

**Comment by bradcray** [comment]
Ah, so I was missing something!  Thanks for pointing that out.  And sorry once again to both cas[s]ellas for my misspellings (Italian ruined my ability to get single vs. double consonants correct).

**Comment by bradcray** [comment]
Thinking about it a bit more, I think the current behavior for that test is acceptable, however.  Without analysis, since `o` is statically typed as an `object`, dynamically, its type could be any other class type, so all dynamic dispatch options are safe bets.  With some flow-sensitive analysis, the compiler could determine that it'll always still be simply an `object` when it's printed out and not consider C's default writeThis() method, but without that analysis, I think the present behavior is reasonable.  That said, the better thing would still be to resolve #15891.

**Comment by cassella** [comment]
I think that analysis applies to the original scan/writeln(fcf) case, no?  They seem about equally acceptable to me.

The differences I can think of are that in the scan case, the `writeThis()` in question is compiler-generated, for internal-module code, so the user can't do anything about it.  And from the PR, I gather the compiler-generated `writeThis()` would never even be used even if the array/class were written.

**Comment by bradcray** [comment]
The root cause of the behavior is definitely the same in all these cases.  My point was that the compiler doesn't currently distinguish between:

```chapel
var o: object = new C();
```

and

```chapel
var o: object = new object();
```

so when you print out `o`, it's conceivable to the compiler that the compiler-generated writeThis() routine for `c` will be called, and that routine attempts to write a sync variable.  Moreover, the user could add an explicit writeThis() method to C to address the issue.

In contrast, with the code in the original bug (or your first variation), the user didn't refer to a sync variables, but did use the `scan` operator that we provide (which did), so it seems hard to consider it anything other than a bug on our part.

**Comment by casella** [comment]
@casella <> @cassella 😄 

Nice to meet you, anyway
