### ISSUE TITLE
Resolution error in try! expressions with default arguments that depend on other arguments

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#14465]
The problem is a corner case that is difficult to explain but the source code is below and much easier to understand:

```chapel
proc foo(a:int, b=a*2) throws {
    return a+b;
}
var x = try! foo(1);
```

This fails to compile with

```
../tryExpr.chpl:1: error: unresolved call 'foo_default_b()'
../tryExpr.chpl:1: note: this candidate did not match: foo_default_b(a: int(64)) [1035368]
../tryExpr.chpl:1: note: because call does not supply enough arguments
../tryExpr.chpl:1: note: it is missing a value for formal 'a: int(64)'
../tryExpr.chpl:1: note: unresolved call had id 1035394
```

It seems that for some reason the compiler is not passing the first argument in the call site when you put the function in a `try!` expression.

- It works without `try!`
- It works without `throws`
- It works when the default argument has some other default value (only tested immediates)

**Comment by e-kayrakli** [comment]
Putting the throwing function in a try/catch block also works.

**Comment by e-kayrakli** [comment]
I bumped into this again with string factory functions

**Comment by e-kayrakli** [comment]
Noting another incident while working on some regex operations.

**Comment by benharsh** [comment]
@psath just encountered this issue as well. I believe I have a handle on the problematic section in ``wrappers.cpp``, so I'll try to develop a fix.

**Comment by bradcray** [comment]
I threw a "user issue" label on here after the fact due to the last comment, and to get credit in our user issue tracking—please feel free to do the same in similar cases in the future.
