### ISSUE TITLE
Optimize indexing into distributed arrays with domain values

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#14480]
Currently, indexing into a distributed array always involves a locality check, but we should be able to optimize that out when accessing a value from the array's domain. For instance, we should optimize things like:

```chpl
var A = newBlockArr({1..m}, int);
forall i in A.domain do A[i] = i;
```

Here's a stream-variant that shows the overhead (and our current `localAccess` workaround):

```chpl
use BlockDist, Time;

const alpha = 3.0;
config const m = 10_000_000_000;

var D = newBlockDom({1..m});
var A, B, C: [D] real;
B = 1.0; C = 2.0;

proc timerWrite(name, ref t) {
  writef("%12s: %.2dr\n", name, t.elapsed()); t.clear();
}

// Warmup
A = B + alpha * C;

var t: Timer; t.start();
forall (a, b, c) in zip(A, B, C) do
  a = b + alpha * c;
timerWrite("zip arr", t);

forall i in D do
  A[i] = B[i] + alpha * C[i];
timerWrite("access", t);

forall i in D do
  A.localAccess[i] = B.localAccess[i] + alpha * C.localAccess[i];
timerWrite("localAccess", t);
```

Performance on 4 nodes of an XC:

| config      | time  |
| ----------- | ----- |
| zip arr     | 0.63s |
| access      | 1.21s |
| localAccess | 0.63s |

**Comment by ronawho** [comment]
Semi related to https://github.com/chapel-lang/chapel/issues/13037

**Comment by e-kayrakli** [comment]
@ronawho  -- I'm wondering whether something I have proposed way before for sparse arrays can work in this case. See [slides] 32-34. I can see two potential advantages over making compiler add calls to `localAccess`:

1. As proposed, it may be applicable to sparse arrays without any additional effort.
2. It can circumvent index flattening for multi dimensional arrays.

For example the "access" case above can translate into something like:

```chapel
if A.domain == D {
  __A_fast_access_ptr = A[A.domain.low]; 
}
else {
  __A_fast_access_ptr = nil;
}
// same thing for B and C


forall i in D {
  if __A_fast_access_ptr {
    __A_ref = *__A_fast_access_ptr;
    __A_fast_access_ptr += 1;
  } 
  else {
     __A_ref = this(A, i);
  }
  // same thing for B and C


  __A_ref = *__B_ref + alpha * *__C_ref
}
```

This should replace locality check and index flattening with a zero-check and pointer increment. Potentially can increase cache utilization, as well.

As with any other pointer trickery this may cause other issues that are easy to overlook.

**Comment by ronawho** [comment]
Interesting, yeah that could certainly help. In the ideal case I think we would eliminate the runtime check and detect at compile time that we're iterating over the array's domain.

I'd be curious to see how that example performs though. The branch should always get correctly predicted so there should be relatively little overhead there.

**Comment by ronawho** [comment]
Adding a variation like:

```chpl
const isLocal = A.domain == D && B.domain == D && C.domain == D;
forall i in D {
  if isLocal {
    A.localAccess[i] = B.localAccess[i] + alpha * C.localAccess[i];
  } else {
    A[i] = B[i] + alpha * C[i];
  }
}
timerWrite("localAccessB", t);
```

performance still lags pretty far behind the straight localAccess case:

```
     zip arr: 0.85
      access: 4.00
 localAccess: 0.85
localAccessB: 2.74
```

Where the only overhead should be from the branch. This might indicate we need to clone the loops instead trying to branch within it.

**Comment by e-kayrakli** [comment]
> we need to clone the loops instead trying to branch within it

It appears that way from your results, but that path is not clear to me for this idiom. I am not sure if there is a good way to check what is a domain of the array statically today and adding that may mean a big overhaul of the compiler. You can still make it a runtime decision and create many clones, but for the stream 2-liner, you'll have 6 clones.

We can get something working for an idiom like

```chapel
forall (i1,i2,i3) in zip(A.domain, B.domain, C.domain) {
   A[i1] = B[i2] + alpha * C[i3];
}
```

where the compiler can tell much easily that these indices are very regular. But OTOH, I don't know how realistic/common this idiom is..

I'll try a lower-level version of your sketch above to see whether using C pointers directly can give us an edge.

**Comment by e-kayrakli** [comment]
@ronawho -- For some reason I am unable to reproduce the results above. But here is something closer to what I have in mind written in Chapel:

```chapel
{
// is this an array that has the same domain as the loop iterExpr
const a_fast = canResolveMethod(A, "_dom") && A.domain == D;
const b_fast = canResolveMethod(B, "_dom") && B.domain == D;
const c_fast = canResolveMethod(C, "_dom") && C.domain == D;
forall i in D with (var a_p: c_ptr(A.eltType),
                    var b_p: c_ptr(B.eltType),
                    var c_p: c_ptr(C.eltType)) {

  // increment fast access pointer if _fast is set and we already have a pointer
  // otherwise set it to the current value
  if a_fast && a_p != nil { a_p += 1; } else { a_p = c_ptrTo(A[i]); }
  if b_fast && b_p != nil { b_p += 1; } else { b_p = c_ptrTo(B[i]); }
  if c_fast && c_p != nil { c_p += 1; } else { c_p = c_ptrTo(C[i]); }

  a_p[0] = b_p[0] + alpha * c_p[0];
}
timerWrite("localAccessLowLevel", t);
writeln(+ reduce A);
}
// below is the same thing. pass --enableFast=false to simulate the worst case
config const enableFast = true;
{

// is this an array that has the same domain as the loop iterExpr
const a_fast = enableFast;
const b_fast = enableFast;
const c_fast = enableFast;
forall i in D with (var a_p: c_ptr(A.eltType),
                    var b_p: c_ptr(B.eltType),
                    var c_p: c_ptr(C.eltType)) {

  // increment fast access pointer if _fast is set and we already have a pointer
  // otherwise set it to the current value
  if a_fast && a_p != nil { a_p += 1; } else { a_p = c_ptrTo(A[i]); }
  if b_fast && b_p != nil { b_p += 1; } else { b_p = c_ptrTo(B[i]); }
  if c_fast && c_p != nil { c_p += 1; } else { c_p = c_ptrTo(C[i]); }

  a_p[0] = b_p[0] + alpha * c_p[0];
}
timerWrite("localAccessLowLevel-worstCase", t);
writeln(+ reduce A);
}
``` 

Based on this I am getting the following on XC:
```
> ./streamTest -nl16 --m=20_000_000_000 --enableFast=false
     zip arr: 0.32
      access: 0.69
 localAccess: 0.40
localAccessLowLevel: 0.40
localAccessLowLevel-worstCase: 0.66
> ./streamTest -nl1 --m=1_000_000_000 --enableFast=false
     zip arr: 0.25
      access: 0.40
 localAccess: 0.31
localAccessLowLevel: 0.31
localAccessLowLevel-worstCase: 0.40
```

**Comment by bradcray** [comment]
I've said as much to Engin, but worry about idioms like:

```chapel
if a_fast && a_p != nil { a_p += 1; } else { a_p = c_ptrTo(A[i]); }
```

being embedded into the compiler rather than generated through the domain map code since it makes assumptions about array layout that may not always be true (e.g., would it be guaranteed to work for a stencil distribution?).  I like optimizing loops and accesses by moving pointers through memory efficiently (we did a lot of this in ZPL), but worry about having the compiler do such things directly rather than through domain maps for fear that it will assume too much and/or be too hard to modify.

**Comment by e-kayrakli** [comment]
@bradcray I think your concern is valid, I have been thinking of ways to mitigate your worry there. I have two potential directions (some I may have mentioned to you already):

1. We add a param `doiSomething` method to DSI that returns true if the consecutive indices yielded by the domain's `these` in a sequential context corresponds to data that are also sequentially laid out in the memory and that they are in the same order. We can add that to the checks done by the compiler. For most of our layouts/distributions this should return true and they would benefit from this optimization. Stencil is probably an example that would return false. 

2. (This one's still a bit vague) We move more of the logic to dmap code. There can be an overload of `_array.this` that has an additional argument that is inserted by the compiler upon detecting that this loop iterates over the domain of this array and that the particular call to `_array.this` uses the same index as the loop index. Then, this overload of `_array.this` could call several new dsi/doi methods to get to the pointer to the data needed. In this scenario, I would imagine the array classes in the dmaps retain a pointer that is initially `nil` and is managed by the `_array.this` overload and somehow reset by the compiler when the loop ends.

(1) is closer to what I propose above, probably easier to implement and design, but relies more on the compiler to do pointer acrobatics. (2) is a bigger design, and there are some parts that are not very clear to me how to do. but relies more on dmaps to run more of the logic. This last statement has the potential to make writing dmaps more difficult than they already are.

I like (1) better if it wasn't clear from my comment above :)

Would any of these approaches make you more comfortable? Do you have any worries that neither of these address adequately?
