### ISSUE TITLE
Python version impacts runtime checks (on Cray-CS only)

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#14514]
### Summary of Problem
Changing python versions results in a "runtime not built for this configuration" error. I have not been able to reproduce this anywhere except on Cray-CS machines so far.

### Steps to Reproduce

**Command line steps:**

```bash
> python --version
Python 2.7.5

# Build Chapel with Python 2.7.5
> cd $CHPL_HOME
> make -j 4
...

# Verify compiling test program works
make check
...

# Using pyenv to switch python versions
> pyenv shell anaconda3-5.2.0
> python --version
Python 3.7.5

# Compile test program
> make check
...
/home/users/user/lus/chapel/runtime/etc/Makefile.include:182: *** The runtime has not been built for this configuration. Check $CHPL_HOME/util/pr
intchplenv and try rebuilding with 'gmake' from $CHPL_HOME.  Stop.
error: compiling generated source
```

### Configuration Information

- Output of `chpl --version`: chpl version 1.20.1 (ce2f672)

- Output of `$CHPL_HOME/util/printchplenv --anonymize --all`:
```
CHPL_HOST_PLATFORM: linux64
CHPL_HOST_COMPILER: gnu
CHPL_HOST_ARCH: x86_64
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none *
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_LLVM: none
CHPL_AUX_FILESYS: none
CHPL_LIB_PIC: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: `gcc (GCC) 6.1.0 20160427 (Cray Inc.)`
- (For Cray systems only) Output of `module list`:
```
Currently Loaded Modulefiles:
  1) craype-network-infiniband   3) slurm/default
  2) craype-ivybridge            4) gcc/6.1.0
```

**Comment by ben-albrecht** [comment]
It appears that this issue stems from a difference of the default `CHPL_ATOMICS` value between the 2 versions. It could be a python 2/3 issue.

```diff
< CHPL_ATOMICS: intrinsics
---
> CHPL_ATOMICS: cstdlib
```

@ronawho points out that we choose `intrinsics` when using system gcc (4.8.5), which would imply that there may be an issue detecting the version of gcc for one of the pythons.

**Comment by bradcray** [comment]
Note that this is related to issue #5743 in that a fix for that issue would've simplified diagnosing this one.

**Comment by jabraham17** [comment]
Closing, this was Cray-CS specific and that system is retired
