### ISSUE TITLE
Request for more transparent error message with nilable class

### ISSUE THREAD

**Issue by npadmana** [chapel-lang/chapel#14532]
Consider the following code 
```chpl
use M;

var test = new Test();

class Test {
  var ffout : shared H5File?;

  proc init() {
    this.complete();
    ffout = createH5File();
    writeScalarAttribute(ffout);
  }
}

module M {

  // Basic file operations
  class H5File {
    var id : int;
  }

  proc createH5File() {
    var ret = new shared H5File();
    return ret;
  }

  proc writeScalarAttribute(loc) {
    var gg = loc.id;
  }

}
```
If I compile under 1.20,  I get the following error message --
```
09:32 shared-class$ chpl test.chpl
test.chpl:27: In function 'writeScalarAttribute':
test.chpl:28: error: unresolved call 'shared H5File?.id'
test.chpl:19: note: this candidate did not match: H5File.id
test.chpl:28: note: because method call receiver with type shared H5File?
test.chpl:19: note: is passed to formal 'this: borrowed H5File'
$CHPL_HOME/modules/internal/ChapelLocale.chpl:183: note: candidates are: locale.id: 
test.chpl:11: Function 'writeScalarAttribute' instantiated as: writeScalarAttribute(loc: shared H5File?)
```
The issue (thanks to @ronawho for pointing this out) is that `ffout` is nilable and so, needs to be guarded by `ffout!` in the call. It would be nice if the error message could advise the user of that.

To add to the confusion, if I remove the module and put everything in file-scope, it compiles just fine. This is because (again, thanks to @ronawho) in prototype and implicit modules, the compiler inserts a `!` into all nilable receivers. While the less work is nice, this behaviour is quite confusing (to me at least).

**Comment by vasslitvinov** [comment]
I believe we are going to make the case without the module work the way it does with the module. This should reduce confusion.

**Comment by vasslitvinov** [comment]
Related: #13875.
