### ISSUE TITLE
push_back warning is ambiguously worded

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#14533]
The current compiler warning for using array-as-vec `push_back` is poorly worded to imply that a one-to-one conversion is possible when what the warning is really suggesting is that the user should rewrite their array-as-vec declaration into a `list`.

```terminal
# chpl version 1.21.0 pre-release
warning: push_back is deprecated - please use list.append
```

**Comment by BryantLam** [comment]
Also, how do I selectively disable a warning like this one?

**Comment by dlongnecke-cray** [comment]
Is there a particular reason that you feel compelled to use array-as-vec instead of `list`, here?

I'm planning on removing those "array-as-vec" operations all together soon, so it's probably not worth the effort to reword the deprecation warnings.

**Comment by BryantLam** [comment]
No reason other than lack of time. If you plan to remove it altogether, that's fine too.

**Comment by bradcray** [comment]
> If you plan to remove it altogether, that's fine too.

To be clear, though, in removing the warning altogether, we'll be removing the functionality as well (i.e., you'll need to rewrite the previously written code at that time).

**Comment by dlongnecke-cray** [comment]
Just a heads up, @BryantLam, array-as-vec operations have been removed on master as of 630f06f. Hopefully this isn't too much of an inconvenience, but if it is I am available to help migrate code and resolve any other issues you might have.

**Comment by BryantLam** [comment]
Nah it's all good. Thanks!
