### ISSUE TITLE
bogus error upon 'use <a function name>'

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#14535]
When the compiler sees `use FN;` where FN is the name of a function, it rightfully complains `'use' of non-module/enum symbol FN`.

Turns out that the compiler also gives this error - now incorrectly - when:
* FN is the name of a **private** function in an implicitly-available standard module like `Math`
* FN is the name of a function in a standard module that is not available implicitly, like `Reflection`

Note that a program with such a `use FN;` may actually be legal if there is a sibling file FN.chpl.

Tests:
```
test/modules/vass/use-a-Math-function.chpl
test/modules/vass/use-a-Reflection-function.chpl
```

**Comment by cassella** [comment]
It does work with a module named the same as the function, in local scope in the same file:

```chapel
module Main {
  use fabs;

  module fabs {
    writeln("absolutely fabs");
  }
}
```

(It also works without the Main module, but there's a warning about the implicit module.)

I imagine if there were a public module in a "more distant" scope than the one containing the private function -- that is, one that would be shadowed by the function were the function not private -- you'd also want to reach that module?

**Comment by vasslitvinov** [comment]
Good question. I think issuing an error would be a good default in that situation.

**Comment by lydia-duncan** [comment]
> I imagine if there were a public module in a "more distant" scope than the one containing the private function -- that is, one that would be shadowed by the function were the function not private -- you'd also want to reach that module?

I agree with this.  Basically, private functions that aren't visible to the scope of the use shouldn't trigger the `'use' of non-module/enum symbol FN` message, the compiler should act as though they don't exist or if there are no other options, it should maybe mention that it found a private function with the same name.
