### ISSUE TITLE
Implementation-record fields countable with numFields ?

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#14546]
This came up in discussions with @ben-albrecht and @benharsh while reviewing #14534.

For the types that are implemented internally with records (or classes) yet are not user-level Chapel records, should their fields be visible using Reflection functions such as `numFields` and `getField` ? This applies to ranges, strings, syncvars, etc.

Pro: in general, if the user can access the field `x.foo` in user code, then `foo` should be exposed by `numFields` et al.

Con: we do not want to expose implementation details to the user, ex. that a given type is implemented internally as a record and so has fields.

**Comment by lydia-duncan** [comment]
The user could theoretically define an overload of these functions for their type, if they really wanted to change the answer it would give, right?  We also could make additional arguments to them to control what was returned.  I kinda suspect `numFields` and `getField` is more of a implementation-oriented function, though, since the number of fields used and their ordering could be changed without necessarily impacting the intended interface for clients of the type

**Comment by ben-albrecht** [comment]
> We also could make additional arguments to them to control what was returned.

I like this idea. Maybe something like this?

```chpl
numFields(t, private=true);
```

**Comment by lydia-duncan** [comment]
Probably with a slightly different name, since `private` is a keyword, but that's along the lines of what I was thinking :)

**Comment by dlongnecke-cray** [comment]
Bumping this as this could potentially change the signature of `numFields`.

Personally, I don't think that we should allow users to query the number of fields in language defined types that just so happen to be implemented by records.

The only uses of `numFields` I could find happened to be in IO and CommDiagnostics, which are standard modules. If we ever needed to do this sort of iteration internally I think we could probably use primitives.

I feel kind of hesitant about this notion of letting a user override the reflection properties of a type. In my mind this is something that `public`/`private` fields are better suited towards instead.

If we wanted to insert an error for builtin types, there is a spot in `preFold` that is probably most appropriate.

**Comment by vasslitvinov** [comment]
My suggestions:

* Users have no business reflecting on built-in types.
* Our modules want to do so, so give them their own non-user-facing function. Primitives could be OK too.
* If a field is not visible (due to `private` or whatever) at a given point in the source code, reflection functions should not expose it. For example they should not include such fields in the `numFields` count. This approach should provide consistency w.r.t. visibility rules.
