### ISSUE TITLE
Omit module in linked references in chpldoc

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#14555]
When you add reference to something that is in a different module, you do something like `String.string` in chpldoc. However, this seems to add the module in the rendered reference as well.

In the [bytes](https://chapel-lang.org/docs/master/builtins/Bytes.html) documentation, for example, this makes `string` references appear as "String.string" which is awkward. [IO](https://chapel-lang.org/docs/master/builtins/ChapelIO.html) is another example of that where very basic IO symbols are rendered as "IO.readline".

This behavior can be desirable in some cases, but there should be a way to avoid it.

**Comment by lydia-duncan** [comment]
You can do this by using `~` in the documentation.  This symbol causes only the name of the symbol to be included in the generated docs and for all the `.` portions to be skipped.  As an example, look at the .chpl file for URL.chpl and [the docs here](https://github.com/Cray/chapel-private/issues/605).  `~IO.iokind` is rendered as just `iokind`

**Comment by lydia-duncan** [comment]
(This is just something that Sphinx provides, iirc)

**Comment by e-kayrakli** [comment]
Fun story: while writing the issue I wrote it as `~String.string` then saw `String.string` in the Bytes module and said "hmm I am remembering it wrong".. Sometimes I should just trust my reflexes more...

I'll fix those instances before I forget.

Sorry about the noise and thanks @lydia-duncan !
