### ISSUE TITLE
Should we allow casting bytes to enum?

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#14553]
The `bytes` type was initially designed to be as close as possible the `string`
type. Design-wise this also included `bytes` to enum casts, because `string`
supports it. However, I cannot say that I thought much about this beyond that.

Currently, this is an unimplemented feature in the sense that we have **some**
support in the Bytes module, but the compiler does not support it. We also
briefly mention about that in the language spec.

The more I think about it, the more I find it wrong to be able to cast `bytes` to
enums because Chapel code is UTF8 and `bytes` can contain non UTF8 sequences.
However, removing that support will arguably widen the gap between Chapel `bytes`
and `strings`.

One important side issue here is enum to `bytes` casts. Currently, they are
supported and work out-of-the-box. I think whatever the decision is, these
should be symmetric. i.e. removing enum->`bytes` support would mean removing
`bytes`->enum support, as well.

**Comment by bradcray** [comment]
I don't know that I have a strong intuition here at present.  I don't think the "Can contain non-UTF-8 characters" is necessarily a reason to disallow these casts since strings can also contain symbols that aren't legal parts of enum identifiers (e.g., a space, or simply a letter that isn't in any of the enum's symbol names).  In the same way that an illegal string results in an error when it contains a value other than the enum, I could imagine doing the same for bytes.  But I also don't know that I have a strong need to convert bytes to enums in mind.

Do we support casting ints to bytes?  Bytes to ints?  This question seems symmetric to me.

**Comment by e-kayrakli** [comment]
@bradcray -- good point about not every string being valid enum name. I think I still fundamentally separate having illegal characters vs. bytes not being UTF8. Because I view casting something to enum akin to almost generating Chapel code. But maybe I am unnecessarily complicating things.

> Do we support casting ints to bytes? Bytes to ints? This question seems symmetric to me.

Yes, bytes to/from numeric casts are supported currently. Then, I am interpreting that you are for supporting `bytes`->`enum` casts, as well.

**Comment by bradcray** [comment]
Yeah, I think if we support bytes <-> scalar types, it makes sense to support bytes <-> enums as well for orthogonality / generality.

Here's a potential use case: I write some sort of file parser in which I read everything in as bytes values to be safe / general and then pull chunks out of the bytes and convert them to various types as I go.

That said, there's arguably a little bit of a question in my mind about whether, for an `enum color { red=1, green=2, blue=3 };` we should support `b"1":color` as well as `b"red":color` (and conversely, what `myColor: bytes` should generate.  I think the "orthogonality with strings" argument suggests that all conversions should be in terms of the enum's names.  But for compact representation as a bytes type, I'd typically really want to store an ordinal value (as we do when bytes are written to binary files at present).

Maybe the answer to that is also simple, though.  Does `42: bytes` result in `b"42"` or `b"0x2A"`? (I may not have the formatting correct there, but you probably get my meaning).

**Comment by e-kayrakli** [comment]
> I think the "orthogonality with strings" argument suggests that all conversions should be in terms of the enum's names.

I think this is the behavior that I'd like to see if/when we have bytes->enum casts implemented.

>  But for compact representation as a bytes type, I'd typically really want to store an ordinal value (as we do when bytes are written to binary files at present).
>
> Maybe the answer to that is also simple, though. Does 42: bytes result in b"42" or b"0x2A"? (I may not have the formatting correct there, but you probably get my meaning).

Today `42:bytes == b"42"`. But reading your comment, it seems like you wanted it to be `b"\x2A"`? And similarly you feel closer to supporting `b"1":color`? 

Note that I brought up `42:bytes` issue in the past in my original post in #13901 (see the last bullet). So, that issue might be a better place to discuss it.

**Comment by bradcray** [comment]
> But reading your comment, it seems like you wanted it to be...

Not necessarily... Consider it more thinking out loud and wondering how much to equate the bytes type with binary I/O representations.  It sounds like the answer is not to do so.  Thanks!

**Comment by e-kayrakli** [comment]
This issue was resolved via #14781.
