### ISSUE TITLE
Are DecodePolicy enum values misleading?

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#14554]
To convert a `bytes` to a `string`, one needs to call `bytes.decode()`. This
method takes an enum (`decodePolicy`) as an argument to determine what to do in
case the byte sequence is not valid UTF8. Copy/pasting descriptions from the
docs, this enum has the following values:

- `decodePolicy.strict`: raises an error
- `decodePolicy.replace`: replaces the malformed character with UTF-8
  replacement character
- `decodePolicy.ignore`: drops the data silently

This naming scheme is identical to [python's](https://docs.python.org/3/library/stdtypes.html#bytes.decode).
However, in the past, I confused myself thinking that `ignore` actually means
"keep using the bytes sequence even if it is illegal".

I also remember in a team meeting demo I made this confusion was mentioned by
someone (I am gonna say @vasslitvinov, but not 100% on that).

I personally lean a bit towards keeping things the same because:

- It doesn't have any surprises for someone who's comming from pythonland.
- With UTF8 validation, my wrong interpretation of `ignore` above does not make
  sense.
- My confusion is not strong enough to make a breaking change (Although I suspect
  the number of user codes to be affected by this change is close to 0)

That being said, I think this issue deserves some consideration and I am totally
open to changing `ignore` to something like `drop` or whatever else makes sense.

**Comment by vasslitvinov** [comment]
I can go with either the argument that `ignore` is confusing and we should switch to `drop` or that `ignore` has the advantage of being familiar to pythonians and its confusion is benign.

**Comment by bradcray** [comment]
I'm similarly split on this issue.  `drop` seems more descriptive to me and if I were on a desert island, I'd probably call it `drop`.  Yet not causing angst for Python programmers is also attractive.  Some other options that many would consider lame / coddling would be to support both and either (a) have both do the same thing (some hate duplicates more than me) or (b) having `ignore` generate an error or warning that in Chapel we call it `drop`.

**Comment by vasslitvinov** [comment]
+1 to provide both `ignore` and `drop`, with a warning to redirect from `ignore` to `drop`.

We can do better than Python, right? :)

**Comment by e-kayrakli** [comment]
Piggy-backing a separate quick question here: This argument is not `param`. Having a deprecation warning at compile time is tricky. I see two options:

- Make it `param`, too. -- I don't see any reason why not, or why a user might wanna change the policy at run time.
- Add no-doc'ed param overloads to capture only param values for deprecation warnings. -- requires no design API change. Arguably, not the ideal solution

**Comment by bradcray** [comment]
I don't have enough experience with these routines to know whether requiring the arguments to be param is too annoying.  I could imagine that the resulting code clones for a value that doesn't _need_ to be known at compile-time for performance/correctness reasons could be annoying.  So I guess I'd be inclined to leave them non-param (or rather, not to make them param simply for the purposes of getting a good deprecation warning).  Maybe put another way: If we didn't think they should be params from the start, let's not make them params for artificial reasons?

I wouldn't have any hesitation about adding the no-doc'd param overloads for deprecation warnings and then removing them in the next release.

**Comment by e-kayrakli** [comment]
Sounds reasonable to me
