### ISSUE TITLE
split initialization and nested functions

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#14621]
Continues #14271 

PR #14564 adds split initialization to the compiler. The initial implementation of split initialization uses a fairly broad rule to avoid problems with nested functions. This issue is to discuss how the combination of split initialization and nested functions should be handled.

For example, consider the following program:

``` chapel
proc main() {
  var x:R;
  f();
  x = new R(1);

  proc f() {
    writeln(x);
  }
}
```

It is important for memory safety that split initialization not apply to `var x:R`, even though the first place it is mentioned is an assignment. That is because the function `f` refers to it without passing it as an argument.

The implementation in PR #14564 simply disables split initialization for variables that are mentioned in nested functions. This makes such variables behave similarly to global variables with regard to split initialization. However a reasonable alternative would be to consider calls to inner functions as implicitly "mentioning" those outer variables that they refer to.

How should split initialization and nested functions interact?

**Comment by mppf** [comment]
@bradcray @vasslitvinov - do you have any thoughts about this question?

**Comment by mppf** [comment]
> However a reasonable alternative would be to consider calls to inner functions as implicitly "mentioning" those outer variables that they refer to.

I don't think that the alternative is reasonable given that we havn't established types by the type we figure out split-init ( and I don't think we want to - I think we want split-init rules to be type-independent). That means that we don't know which inner functions are called (in the event of multiple overloads, say). Additionally, we would have to worry about inner functions calling other inner functions.

So, I am currently happy with what is implemented now, which is "disables split initialization for variables that are mentioned in nested functions".

**Comment by vasslitvinov** [comment]
The only way to have any non-trivial consideration of nested functions is when we know how they are invoked. Since this is not known - and if it were, it can be complex, ex. in the presence of dynamic dispatch and FCFs - it makes a good sense to stay with the currently-implemented approach.

**Comment by bradcray** [comment]
I don't have any reservations about what we have here at present and agree with the challenges to being more aggressive that you guys are raising.

**Comment by mppf** [comment]
There seems to be agreement about the current behavior, so I will close this issue. It is already implemented. I will make a TODO to update the spec appropriately. https://github.com/Cray/chapel-private/issues/719 tracks that task.
