### ISSUE TITLE
IO symbols don't follow established conventions

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#14646]
There are still some open interface discussions about the IO module, so some of these should probably wait, but some examples of these are

- io* enums and params:
   `iokind`, `iostringformat` etc should be camelCase: `ioKind`, `ioStringFormat`
- some methods:
  `readstring`, `readbytes` etc should be camelCase `readString`, `readBytes`
- some UPPERCASE_UNDERSCORED constants
   To say the least, this casing is uncommon in Chapel module code.

Arguably, some of these discussions will depend on some of the discussions in #6698, but I think some of them are more or less agreed upon and changes should be straightforward.

**Comment by dlongnecke-cray** [comment]
Since I'm the most recent person to touch this code, I'd be willing to slog through it and clean it up. I also share your distaste!

I think the `IO` module in particular is a prime example of exactly why a style guide _is_ needed.

**Comment by bradcray** [comment]
> I think the IO module in particular is a prime example of exactly why a style guide is needed.

I don't think anyone's argued it's not needed, it's just that nobody ever volunteers to take the lead on creating one.

**Comment by e-kayrakli** [comment]
I brought this up to IO stabilization subteam. It looks like this is good to close.
