### ISSUE TITLE
Bad error message for defining list of generic class

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#14692]
### Summary of Problem
Defining a list of a generic class gives a bad error message / line of code.

### Steps to Reproduce

```chapel
use List;

var l: list(C);

class C { }
```

```
> chpl listnilable.chpl
$CHPL_HOME/modules/standard/List.chpl:151: In initializer:
$CHPL_HOME/modules/standard/List.chpl:154: error: Could not coerce 'nil' to '_ddata(_ddata(C))' in initialization
listnilable.chpl:3: Initializer instantiated as: init(type eltType = C, param parSafe = 0)
```

For reference, the array case gives a better error message:

```chpl
var x: [1..0] C;

class C { }
```

```
> chpl listnilable.chpl
listnilable.chpl:1: warning: creating an array with element type Container
listnilable.chpl:1: error: array element type cannot currently be generic
```

### Configuration Information

- Output of `chpl --version`: chpl version 1.21.0 pre-release (98ffc7ae59)

**Comment by ben-albrecht** [comment]
I'm calling this a user issue because @al-rigazzi  stumbled over this.

**Comment by ben-albrecht** [comment]
@benharsh - @mppf thought you'd be a good person to ping on this one.

**Comment by ben-albrecht** [comment]
@e-kayrakli - is this resolved in https://github.com/chapel-lang/chapel/pull/15368 ?

**Comment by e-kayrakli** [comment]
I believe so. Closing
