### ISSUE TITLE
Default type for regular expressions

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#14693]
#14686 will add support for `bytes` regular expressions. In order to do that it makes `regexp` record generic on `type exprType`. The meaningful concrete types in this scenario are `regexp(string)` and `regexp(bytes)`.

That PR does not assign a default value to `exprType`, but maybe it should. We have the following options:

1. No default type  -- it'd be nice to have regexp neutral. 
   This helps with some of the confusions I was having during the implementation of #14686. For example:

```chapel
class Message {
  proc parse(r: regexp) { /* bla */ }
}
```

if `regexp` doesn't have default type, then, `parse` can be used with both string and bytes regular expressions. Otherwise, we'd be stuck with `string` only, or change the prototype to `proc parse(r: regexp(?))`

This is also a breaking change, but probably not very impactful. Note that you can use regular expressions without using this type explicitly:

```chapel
var myRe = compile("regular expression string");
```
gives you a `regexp(string)`. If the literal was `bytes` then it would give `regexp(bytes)`

2. default value is `string`
    `string` should be the more common use for this class, and it might make sense to just make it default.

3. default value is `bytes` -- just for completeness. I don't think this is a real option

Even though #14686 chooses 1, I don't really have a preference between 1 and 2.

**Comment by BryantLam** [comment]
I would go with option 1: no default type. It's the least restrictive option between 1 and 2 if some person wants to make a custom string type for their use case.

**Comment by bradcray** [comment]
I think I said this elsewhere, but: I agree that it shouldn't have a default type.  I could imagine it having a default type with deprecation warning for the 1.21 release to help people transition their existing codes that relied on it being string-only.  I'm imagining this could be supported by having a 0-argument initializer that generated the warning and called a 1-argument initializer passing `string` in.
