### ISSUE TITLE
add map.keys()

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#14716]
I find myself trying to use `map.keys()` quite often, both because of the symmetry with `map.values()` and my python background leading me to expect a similar interface to `dict`. However, this results in a not-so-great error message, because `keys` is an array field, not a method:

```chpl
use Map;

var m: map(int, int);

m[1] = 2;

writeln(m.keys());
```

```
error: unresolved access of 'DefaultAssociativeDom(int(64),false)' by '()'
```

I am in favor of adding a `keys()` iterator to mirror the `values()` iterator. If not, we should at least add a better error message for this specific case.

**Comment by ben-albrecht** [comment]
Kind of a follow-on to https://github.com/chapel-lang/chapel/issues/14716 after having more map experience under my belt.

**Comment by e-kayrakli** [comment]
I think we should have `keys`.

Apparently, I said in #13624:

> What should these yield? I am going the python way again and making it yield
keys. And adding items iterator to yield k-v tuples, values iterator to
yield values.

Reading this again, I don't know why I didn't add `keys` in the first place. I think that it was an oversight on my part to not add an `iter keys()` that is identical to `iter these()`

**Comment by bradcray** [comment]
Only vaguely related, but recall that late discussion on issue #13624 also raised the question as to whether `these()` should behave more like `items()` and less like `keys()`.

**Comment by e-kayrakli** [comment]
@bradcray 

> Only vaguely related, but recall that late discussion on issue #13624 also raised the question as to whether these() should behave more like items() and less like keys().

I opened https://github.com/chapel-lang/chapel/issues/14718 to summarize the discussion under that closed PR.
