### ISSUE TITLE
Map of owned/borrowed type results in init= error

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#14712]
### Summary of Problem
Creating a map with values of owned or borrowed type results in a compiler error regarding the `init=` of the map type.

My current work-around is to stick to `unmanaged` for now. (`shared` has separate issues: https://github.com/chapel-lang/chapel/issues/14713)

### Steps to Reproduce

**Source Code:**

Borrowed example:

```chapel
use Map;

var nodes: map(int, borrowed Node?);

class Node { }
```

Error message:

```
$CHPL_HOME/modules/standard/Map.chpl:98: In function 'init=':
$CHPL_HOME/modules/standard/Map.chpl:107: error: Setting borrowed formal illegal without specifying formal lifetime constraint
$CHPL_HOME/modules/standard/Map.chpl:98: note: consider scope of other
```

Owned example:

```chpl
use Map;

var nodes: map(int, owned Node?);

class Node { }
```

Error message:

```
$CHPL_HOME/modules/standard/Map.chpl:98: In function 'init=':
$CHPL_HOME/modules/standard/Map.chpl:107: error: illegal lvalue in assignment
```

### Configuration Information

- Output of `chpl --version`: chpl version 1.21.0 pre-release (4f4e86253a)

**Comment by ben-albrecht** [comment]
FYI map enthusiast @dlongnecke-cray

**Comment by bradcray** [comment]
This seems potentially related to a number of other collection + managed class orthogonality issues:
* #14361
* #14367 
* #13096
* #14362
* #14423

I'm tracking this list in https://github.com/Cray/chapel-private/issues/643 and have added this issue to that list.

**Comment by ben-albrecht** [comment]
Thanks @bradcray  - I think there is sufficient overlap with #14361 to close this one as duplicate.
