### ISSUE TITLE
Should cast from domain to string promote?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#14721]
After #13281 and #13658, `string + domain` is no longer supported by the string type.

So, one might have had this:
``` chapel
var D = {1..10};
var s = "Domain: " + D;
```

which will no longer compile and one might put this:

``` chapel
var D = {1..10};
var s = "Domain: " + (D:string);
```

However this results in an array of strings rather than the string describing the domain.

Furthermore, the corresponding example with ranges, which are also subject to promotion, results in a single string describing the range:

``` chapel
var r = 1..10;
var ss = "Range: " + (r:string);
```

Results in `ss` being of type `string`.

Is this the right behavior for cast from a domain to a string?
Should there be a way to distinguish between "Cast the elements" and "Cast the domain/array"? Should domains and ranges behave the same in this regard?

**Comment by mppf** [comment]
This issue was originally reported by @LouisJenkinsCS - thanks Louis!

**Comment by bradcray** [comment]
I think that this is an oversight / bug, and that the cast should result in the string `{1..10}`.

Here's a TIO link showing the 1.20 behavior for Michael's examples:  https://tio.run/##S85ILEjN@f@/LLFIwUXBVqHaUE/P0KDWmgskUAwUUHLJz03MzLNSUFLQVtBwsSouKcrMS9e05iovyixJzcnTKAaywaqLgKrBuqGawbqDEvPSU6Gai7BoBur@/x8A

**Comment by bradcray** [comment]
I've got a quick fix for this testing.
