### ISSUE TITLE
Should last mention deinitialization point go inside blocks?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#14749]
#13704 proposes rules for when a value is dead if there is no potential capture of aliases:

> dead at the end of the last statement that mentioned that variable. Note that for an if conditional or a loop that contained a mention of the variable in its body, the variable would be dead after that if or the loop. 

It does not say what should happen if a variable is last mentioned in a nested block.

For example:

``` chapel
proc test() {
  var x: SomeRecord = new SomeRecord();
  {
     f();
     g(x);
     // point 1
     h();
   }
   // point 2
}
```

In this example, `g(x)` is the last mention of the variable `x` but it is within a nested block. `x` could be deinitialized at point 1 or at point 2.

PR #14691 takes the approach of deinitializing such a variable at point 2.

In favor of point 1:
 * memory that is not used could be cleaned up sooner

In favor of point 2:
 * the rule is simpler and has more in common with loops, conditionals; having the rule apply to plain blocks but not to loops is a kind of special case
 * users can use an inner block to indicate an outer variable should not be deinitialized within it

**Comment by mppf** [comment]
Note that changes to this behavior will arguably be breaking changes because programs can behave differently (if deinit prints out something or has other side effects).

**Comment by bradcray** [comment]
Deinitializing at point 2 seems more attractive to me from a K.I.S.S. perspective.

**Comment by mppf** [comment]
PR #15041 uses a simpler rule for deinit points making it even clearer that point 2 is the right answer for deinits. But, copy elision can go inside of a block (as of PR #15174).
