### ISSUE TITLE
Remove identical element type requirement from fast-followers

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#14763]
Fast followers optimize zippered iteration and promoted expressions over aligned distributed arrays. For example with stream:

```chpl
use BlockDist;
config type bcType = real;

var D = newBlockDom({0..#10});
var B, C: [D] bcType;
var A: [D] real;

A = B + 3.0 * C;
```

We know that A, B, and C have the same distribution/alignment so that means we can skip locality checks (because for any arbitrary element i, A[i]/B[i]/C[i] must live on the same locale.)

However, these checks currently require identical array types, which means that the element types must be the same. In the above example if the element type of B/C is changed from `real` to `int` the optimization will no longer trigger. 

I think we can relax this requirement. It's possible that a distribution could choose different alignment for different types, but Block and Cyclic don't and the distribution is the thing that defines whether fast followers are valid. 

Operations between different types occur in arkouda, especially between int/real, where the result is a real: https://github.com/mhmerrill/arkouda/blob/master/src/OperatorMsg.chpl

**Comment by bradcray** [comment]
@benharsh: Given your recent fast-follower fix, do you have a sense of whether this is a trivial or heavy lift?

**Comment by benharsh** [comment]
I don't recall seeing anything specifically about the element type - perhaps some other check is obfuscating that aspect. I doubt it's a large change regardless.

**Comment by ronawho** [comment]
It's the static check that currently rules different eltTypes out since it's doing `leadType == this.type`, and the element type is part of the array type. I think we need a "same type except eltType" check, but I'm not sure what that would look like.

**Comment by bradcray** [comment]
Where does that check appear in the code?

**Comment by ronawho** [comment]
https://github.com/chapel-lang/chapel/blob/2632825ae76b4ed143d7220066f9738a613de0d5/modules/dists/BlockDist.chpl#L1050-L1053

which is called through:

https://github.com/chapel-lang/chapel/blob/2632825ae76b4ed143d7220066f9738a613de0d5/modules/internal/ChapelIteratorSupport.chpl#L486-L488

**Comment by bradcray** [comment]
To preserve the current approach but relax the element type check, I think we'd just want to replace the first half of that conditional with "am I a BlockArr && are our ranks the same?"  Then I find myself trying to remember whether "am I a BlockArr"? can be written `this:BlockArr != nil` or whether we have to give a fully concrete type for BlockArr (in which case having an `isBlockArr()` utility function that answers the more general question is probably the way to go).

I also find myself thinking harder about when we could relax the static check further:  E.g., if the leader is a range whose indices are all locally owned by the current locale, should that be a candidate for the fast follower case as well?

**Comment by benharsh** [comment]
PR #15303 has resolved this for Block and Cyclic, but not for Stencil (yet).

**Comment by benharsh** [comment]
Stencil handled in #15306.
