### ISSUE TITLE
mason init

### ISSUE THREAD

**Issue by ankingcodes** [chapel-lang/chapel#14786]
@e-kayrakli had directed me to #7106 for improvements in Mason as I was interested for improving Mason as a part of a GSoC'20 project. An `init` command is required in mason for initialising a creating a project in an already existing directory. I am interested in implementing this feature for Mason.
The following is what I propose for this :

- User types command `mason init` inside a directory
- This begins an interactive session just like `npm init` or D lang's `dub init` asking for project name, author, description etc. (this can be dropped too, need suggestions regarding this)
- Mason creates `Mason.toml`, `Mason.lock`, `.gitignore` and other directories and files as generated by `mason new [project name]`

**Comment by ben-albrecht** [comment]
Thanks for kicking this off @ankingcodes.

> User types command mason init inside a directory

I think it's common to support passing a path as an argument as well, e.g. `mason init some/directory`
> This begins an interactive session just like npm init or D lang's dub init asking for project name, author, description etc. (this can be dropped too, need suggestions regarding this)

I would suggest initially supporting a non-interactive version that allows passing the configuration arguments as flags. We can then extend this to support an interactive version with an `--interactive` flag after the base implementation is complete.

> Mason creates Mason.toml, Mason.lock, .gitignore and other directories and files as generated by mason new [project name]

Note that `mason init` will have to respect the existing files, e.g. if the user has already created a git repository, then there's no need to do a `git init`, or if the user has already created a source file, there's no need to create a `src/<PkgName>.chpl`

We will want probably want to write a test for every case of pre-existing files.

**Comment by ankingcodes** [comment]
> I think it's common to support passing a path as an argument as well, e.g. `mason init some/directory`

@ben-albrecht  Cool ! I believe that would be the `root path`, i.e the directory where the project is created. If it doesn't exist we create that right.

>Note that mason init will have to respect the existing files, e.g. if the user has already created a git repository, then there's no need to do a `git init`, or if the user has already created a source file, there's no need to create a `src/<PkgName>.chpl`

Okay, so we need to check if a target directory is created or not, also we need to make sure that nothing is overwritten right ?

**Comment by ben-albrecht** [comment]
> I believe that would be the root path, i.e the directory where the project is created. If it doesn't exist we create that right.

Yes. If a path is given as an argument, use that, otherwise use the current working directory, e.g.

```
mason init # create package metadata in .
mason init packages/Pkg # create package metadata in packages/Pkg
```

> Okay, so we need to check if a target directory is created or not, also we need to make sure that nothing is overwritten right ?

That's correct, and we'll also want to validate the existing files in some way, e.g. if we find a `Mason.toml`, we should be able to parse it with the TOML reader and find a few key values like project name and version.
