### ISSUE TITLE
What should we name string.encode (and bytes.decode) arguments?

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#14796]
#14743 adds `string.encode` that creates a `bytes` from a `string`. In general
that PR will allow us to store non-UTF8 paths in strings. This is done by encoding
non-UTF8 bytes using special codepoints. So `encode` will be able to reconstruct
non-UTF8 bytes in the string.

However, the user may want to copy the data directly into `bytes` without trying
to recover those bytes. With #14743, these options are expressed as:

```chapel
myString.encode(errors=encodePolicy.pass)
myString.encode(errors=encodePolicy.unescape)
```

The argument name `errors` is kind of a misnomer, because any possible escaped
sequences in the string are technically not errors. However it is aligned with
Python's argument name. See
[`bytes.decode`](https://docs.python.org/3/library/stdtypes.html#bytes.decode)
and [`str.encode`](https://docs.python.org/3/library/stdtypes.html#str.encode)
interfaces for more.

What should we do for this argument's name? I see the following options:

1. Keep `errors`
2. Change `string.encode` argument to something more appropriate.
3. Do 2, but update `bytes.decode`'s argument, too.

Personally, 1 does not bother me and has the added benefit of similarity with
Python. But 3 can also be a good option. I don't like 2 that much because
I like the symmetry between `bytes.decode` and `string.encode`.

If we are changing argument name(s), all I can think of right now is `policy`.
It may be a bit repetitive, though. Because our enums for these "policies" are
`decodePolicy` and `encodePolicy`.

**Comment by e-kayrakli** [comment]
Somewhat related: #14554

**Comment by bradcray** [comment]
`policy` is where my head went too in thinking of better names (before seeing your proposal).  The repetition won't necessarily be there because a user could (a) not use name-based argument matching or (b) `use` the enum to avoid naming it at the callsite.

I'm not that familiar with these routines, so don't have a strong opinion about whether we should change this or not.  If I were naming it from scratch / Python didn't establish a precedent, I'd definitely use `policy`.  I'd also make string and bytes match.

**Comment by e-kayrakli** [comment]
On an offline discussion some time ago, @ben-albrecht said he'd prefer `policy` over `errors` but would be fine with `errors` if we don't want to have a breaking change. Overall, he wanted to keep them symmetrical.

Another argument for changing to policy is symmetry (distant) with [`compareExchange`](https://chapel-lang.org/docs/master/builtins/Atomics.html#Atomics.compareExchange) which has an argument `order` that takes an value of enum `memoryOrder`. So, `policy` argument taking an argument of `decodePolicy` or `encodePolicy` sounds better to me than it was when I opened this issue.
