### ISSUE TITLE
split init and conditionals that return or throw

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#14815]
Should a program using split-init such as the below be allowed?

``` chapel
proc test() {
  var a;
  if option then
    a = new R(1);
  else
    return;
  
  moreStatements(a);
}
```

PR #14814 implements this, but previous to that PR, this program would not compile, because the else branch of the conditional does not initialize `a`.

However it is not a problem for this program to compile as-is, because `moreStatements(a)` will always access an initialized `a`, and `a` will simply not be initialized (or deinitialized) if the else branch is taken.

This feature is motivated by an example using `try` inspired by Arkouda: https://github.com/chapel-lang/chapel/issues/14748#issuecomment-578287353 but if we allow this rule for `catch` clauses it would make sense to also allow for conditionals. (Issue #14748 discusses whether split-init should be allowed within `try` statements at all, but try/catch is notionally related to if/else and so we would probably make the same choice for return/throw).

**Comment by vasslitvinov** [comment]
I agree that such programs should be allowed.

**Comment by mppf** [comment]
There seems to be agreement that such programs should be allowed. PR #14814 implements it and updates the spec. So I am closing this issue.
