### ISSUE TITLE
deinit point and param conditionals

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#14817]
PR #14691 adjusts the deinitialization point according to expiring value analysis (which was discussed in  #13704). This issue asks if folded-out param conditionals should impact the deinitialization point.

Consider for example the following program:

``` chapel
proc test() {
  var r = new R(1);

  writeln(r);

  // point 1

  writeln("before param conditional");

  if false {
    writeln(r);
  }

  // point 2

  writeln("after param conditional");
}
test();
```

Should the record deinitializer for r be run at point 1 or point 2?

In favor of point 1:
 * The compiler knows that `r` is not actually used after this point so can deinitialize it early, and generally freeing memory earlier is better

In favor of point 2:
 * A human programmer will more easily be able to predict the deinitialization point if it does not rely on compile-time constant folding and param conditional folding.

The current implementation does point 1, but we could extend param conditional folding to adjust PRIM_END_OF_STATEMENT calls to change it to point 2.

Note that split-init rules, which are conceptually related, apply to the code before param conditionals are folded.

**Comment by vasslitvinov** [comment]
I support Point 2.

Given that our split-initialization detection is generally pre-resolution, we should stick with that in this case as well.

**Comment by bradcray** [comment]
I don't feel strongly about this, and am fine with sticking with the status quo.

**Comment by mppf** [comment]
There seems to be enough support for Point 2 so I am closing this issue. PR #14825 will make the change to the compiler. https://github.com/Cray/chapel-private/issues/690 tracks the TODO of updating the spec accordingly.
