### ISSUE TITLE
spec describes previous behavior of default record comparison

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#14833]
#14789 changed the behavior of the default record comparison operators, but the spec still describes the previous behavior.

**Comment by klakho0400** [comment]
hi is this a documentation related issue?

**Comment by klakho0400** [comment]
so we need to only add that the comparisons of record compares fields according to lexicographical order ?

**Comment by mppf** [comment]
@e-kayrakli - I think this is yours to fix

**Comment by klakho0400** [comment]
@mppf what I suggested is correct?
and if @e-kayrakli is fine can i contribute ? and make this my first pr

**Comment by mppf** [comment]
@klakho0400 - you will have to work that out with @e-kayrakli . If you are thinking of contributing though you'll need to create a contributor agreement - see https://github.com/chapel-lang/chapel/blob/master/doc/rst/developer/bestPractices/ContributorInfo.rst#get-set-up

**Comment by klakho0400** [comment]
@mppf i have filled the agreement and there has been no reply from cray.org

**Comment by mppf** [comment]
@klakho0400 - it can take a few days.

**Comment by e-kayrakli** [comment]
@klakho0400 -- in case you miss it, I [commented](https://github.com/chapel-lang/chapel/pull/14844#issuecomment-584289341) under the PR. We can discuss the specifics further under the PR.
