### ISSUE TITLE
isDefaultInitializable errors with record containing non-nilable owned

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#14854]
``` chapel
use Types;
class C { var x: int; }
record ContainingNonNilableOwned { var z: owned C; }
writeln(isDefaultInitializable(ContainingNonNilableOwned));
```

Produces a compilation error
```
x.chpl:3: error: Cannot default-initialize z: owned C
note: non-nil class types do not support default initialization
note: Consider using the type managed _owned(C)? instead
```

but instead `isDefaultInitializable` should just return `false`.

Associated future test:

  test/library/standard/Types/copyable-nonnilable-records.chpl

**Comment by vasslitvinov** [comment]
`isDefaultInitializable()` also does not work on domains.

**Comment by bradcray** [comment]
Something subtle but interesting about Michael's example above is that it's not the presence of the field that causes the problem, but the combination of the field and the lack of a default initializer, right?  I.e., a clone of the test which had `proc ContainingNonNilableOwned.init() { this.z = new C(); }` should return 'true' for isDefaultInitializable()?

(seems obvious, but just making sure we're all on the same page since the issue and future don't seem to call that out).

**Comment by mppf** [comment]
Well... the problem is that `isDefaultInitializable` is raising a compilation error but it should return `false` instead. But anyway yes the example you described should return `true`

**Comment by vasslitvinov** [comment]
Another issue is running it on a record that relies on the compiler-generated initializer and has a field that is not default-initializable, however has a default expression. Ex.
```chpl
record R {
  var c: unmanaged object = new	unmanaged object();
}
isDefaultInitializable(R) // returns 'false'
```

**Comment by ben-albrecht** [comment]
Including this here so it isn't forgotten after closing:

> Once #14854 is resolved, this check
for isNonNilableClass() should be updated to !isDefaultInitializable().

- [ ] Update conditional in ` modules/internal/ChapelArray.chpl` from [here](https://github.com/chapel-lang/chapel/pull/15571/files#diff-a0be501f0990849134d41079d80affd0R1421)

**Comment by mppf** [comment]
Still have problems with this case:

```
use Types;
proc test11() {
  var d = {1..10};
  assert(isDefaultInitializable(d.type));
  assert(isDefaultInitializable(d));
}
test11();
```

**Comment by mppf** [comment]
PR #15793 should help the domain case.

**Comment by mppf** [comment]
Closing because as far as I know PRs #15774 and #15793 resolved the issues with isDefaultInitializable. In addition, PR #15839 will remove workarounds.
