### ISSUE TITLE
[design] a solution to perennial inability to find methods and fields for black market classes

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#14864]
### Summary of Problem
Relates to #14407, #11868, #10397, #7857 (resolved), #14830, #14419, #14740, potentially others that I missed

Basically, we frequently encounter situations where a class or record has been obtained in a scope where its definition was not included.  We've had to explicitly let certain symbols be found, and have often run into additional cases that were missed.

This is because our resolution rules really only have two strategies: is it brought into scope?  Or is it accessed in a qualified manner?  Technically methods and fields are always accessed in a qualified manner, but that isn't the strategy used to find where the symbol lives - we don't go into the class/record scope and then out from there.

### Proposal
This issue proposes a new strategy for resolving methods and fields.

Basically, what I'd like to do is keep track of visible methods for a type from a particular scope, using a cache of scope->type->methods.  The computation of this will be slightly different from that of visible functions today, due to ignoring the limits given by `use ... only ...;`, `use ... except ...;` and `import ...`.  If there's a `use` or `import` statement in the chain that can go to that method definition, it is considered brought into scope, no ifs, ands or buts.  When resolving methods, we will access this cache based on the type being used.

### Potential tricky points
- Things that aren't methods that are necessary for the type (e.g. `_new`, `+`, etc.).  There's a list of some that are already covered, but we might still be missing others.  I propose that a list of known function names be maintained.  When building the cache, look for functions with these names that apply to the type and also store them.
- Inherited methods, and methods defined on child types.  We don't want to miss parent methods that weren't overridden.  There might be situations where we get an instance of a type, think it is a parent type when really it is a child type, and it would be valid to call a method only defined on the child type.  I'm not thinking of any right now, but I'd like someone else to double check me.
- maybe something to do with generic instantiations of methods?  Generic instantiations of functions that take these types won't be a problem, since they can be accessed with normal qualified naming (and so the user has to do that).

**Comment by mppf** [comment]
> Things that aren't methods that are necessary for the type (e.g. _new, +, etc.).

Would this include all operator overloads?

From an exchange I had with Brad in https://github.com/chapel-lang/chapel/issues/14407#issuecomment-551922459  -

> >  would your answer change for a secondary method?

> For the case you showed, my answer wouldn't change / I'd give the same answer. I think of secondary methods as largely being a syntactic variant of primary methods and don't think (?) we treat them differently in practice, nor do I think we should. If the secondary method was defined in a different module than the class itself, then I think it's a trickier question (but not the one I'm worried about here).

I think we need to think about secondary methods defined in a different module than the type itself. I don't know what the answer there is, but it might make sense for the rule to treat them differently. I think that topic needs its own issue.

**Comment by lydia-duncan** [comment]
> I think we need to think about secondary methods defined in a different module than the type itself. 

Yeah.  This design is mostly because of secondary methods in other modules, otherwise we could just hop into the type's scope and look at what's defined there.  Over in #7857, it sounded like we wanted secondary methods in other modules to be included if that other module was included in some form, but it's certainly reasonable for our thinking to have shifted since then

**Comment by lydia-duncan** [comment]
Another thing to ensure works: unprefixed method accesses in secondary methods
