### ISSUE TITLE
I/O using strings with escaped byte sequences

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#14879]
#14743 added support to escape non-UTF8 sequences while creating a string. The
main motivation for that was to support paths and file names in non-UTF8
systems (see #12728). The design and implementation choices for that support
was based on Python's [surrogate escapes](https://www.python.org/dev/peps/pep-0383/).

You can do pretty much everything you can with escaped strings in Chapel.
However, things get tricky when you attempt to do I/O:

```chapel
var b = b"\xff";
var s = b.decode(errors=decodePolicy.escape);

writeln("writeln output:");
writeln(s);

writeln("Textual writef output:");
writef("%s\n", s);

writeln("Binary writef output:");
writef("%|*s\n", 1, s);
```
On a UTF8 terminal, you get nothing in the first two outputs, and a
`SystemError: Value too large to be stored in data type: unexpected string
length` in the third one. For reference, the escaped byte is represented with a
2-byte codepoint that takes 3 bytes when encoded in UTF8. And increasing the
size of the writef allows it to execute (without showing anything on an UTF8
terminal)

Python does not allow escaped strings to be printed out directly:

```python
>>> b = b'\xff'
>>> s = b.decode(errors='surrogateescape')
>>> print(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcff' in position 0: surrogates not allowed
>>> print(repr(s))
'\udcff'
>>>
```

Should we also prevent such strings to be used with I/O? If so, should we allow
them to be printed out in some fashion using formatted I/O?

**Comment by bradcray** [comment]
Preventing such strings from being printed by default seems reasonable to me.  Having some way to print them may be reasonable, but could also be added later if/when someone requested it without breaking existing code, I believe.

**Comment by bradcray** [comment]
@e-kayrakli: Searching for something else, I just stumbled into a raft of issues like this that made me ask "can this be closed now?"

**Comment by e-kayrakli** [comment]
This one has slipped through the cracks :( it should be relatively easy to prevent such strings from being printed. I hope to squeeze this in this week. Let's keep it open until I get it fixed.
