### ISSUE TITLE
Need better error message on hidden backwards-breaking change to `regexp` record

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#14895]
### Summary of Problem
The `regexp` record's interface changed sometime between v1.20.0 and master v1.21.0 pre-release.

```chapel
// v1.20.0
 record regexp
    proc init()
    proc init=(x: regexp)
```
```chapel
// v1.21.0 pre-release
 record regexp
    proc init(type exprType)
    proc init=(x: regexp(?))
```

Looking at the source, `regexp` appears to now take a type parameter. Previously written code doesn't compile with cryptic error messages about `_ddata` in `list` even though the issue is wrong use of the now-changed `regexp` record.
```chapel
// v1.20.0
use List;
use Regexp;
var x = new list(regexp);
```
```chapel
// v1.21.0 pre-release
use List;
use Regexp;
var x = new list(regexp(string));
```

Can I get a better error message, or have a default initializer that sets the type parameter to `string` (if reasonable)?

**Comment by e-kayrakli** [comment]
This is one of the open issues that we hope to close by next release. Do you have a preference between an error message vs. making `string` the default type for regular expressions? See https://github.com/chapel-lang/chapel/issues/14693 for more detailed info about this.

**Comment by BryantLam** [comment]
I would prefer the error message. This case is probably one reason I wished some of the default modules had version numbers because then I could detect that module `Regexp` changed from say 1.4 to 2.0 to signify the break.

**Comment by bradcray** [comment]
Is it correct that the better error message would simply require having a 0-argument init() overload that issued a compilerError() updating the user that they have to specify a type?  If so, I think I'm in favor of that as well (i.e., keeping regexp neutral w.r.t. types by default).

If we wanted to ease the pain of transitioning from 1.20, we might also consider making the 0-argument init() case  default to string for now (for backwards compat with no code changes) but generate a compilerWarning() that the user should update their code to avoid facing an error later (and then change it to an error in the subsequent release).  This would have the benefit of requiring fewer changes to keep code working, while still making noise for users to encourage them to update (or warn them of the consequences if they don't).

> I wished some of the default modules had version numbers because then I could detect that module Regexp changed from say 1.4 to 2.0 to signify the break.

Yeah, and/or to move all modules under mason (which requires a better testing story for mason modules).

**Comment by e-kayrakli** [comment]
Fixing this is probably a 2-part effort:

- Add 0-arg init for `regexp` that gives a deprecation warning: #14693
- Have our data structures do something to detect generic types: #14974
