### ISSUE TITLE
cannot return array of non-nilable owned

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#14896]
After PR #14887, the compiler produces an error when returning an array of non-nilable owned.

``` chapel
class C { var x: int; }

proc makeArrayOwned() {
  var A: [1..3] owned C? = for i in 1..3 do new owned C?(i);
  var B: [1..3] owned C = A:owned C;
  return B;
}

proc main() {
  var arr = makeArrayOwned();
  writeln(arr);
}
```

**Associated Future Test(s):**
test/arrays/ferguson/array-of-owned-return.chpl

**Comment by mppf** [comment]
When this is resolved, we might want to revisit the chameneous tests adjusted in the commit titled "Adjust chameneous variants to work around issue #14896"

**Comment by BryantLam** [comment]
This issue is a blocker for me. The only workaround I know of is to change the type of the array to a nilable, but that's unworkable because it parasitically affects the remaining code.

**Comment by mppf** [comment]
I'll look at it. I might just swap the error message behavior. However I might be able to do something to get copy elision to fire in this case.
