### ISSUE TITLE
What is the default tuple argument intent? What about if an element is captured by const ref?

### ISSUE THREAD

**Issue by dlongnecke-cray** [chapel-lang/chapel#14947]
## What is the default tuple argument intent?

The `Tuple Argument Behavior` section of CHIP6 says the following:

```
A tuple argument to a function with blank intent will not make a copy of
the tuple elements and can accept a tuple expression.

A tuple argument with `ref` intent requires an `lvalue` argument - a variable
or returned tuple. In neither case does passing a tuple argument to a
function create a copy of the tuple.

A tuple argument declared with `const` intent will work similarly to one
with a `blank` intent, but contain `const` elements.
```

How am I supposed to interpret this? Is the default tuple argument intent `const ref`? If so, what does the last paragraph mean?

Since tuples are seemingly the only "record like type" to be able to capture elements by reference, should I interpret this last paragraph to mean something like "const ref const"?

To me, it seems like these paragraphs are saying the following:

- The _blank_ / _default_ tuple intent says that tuple _elements_ may be modified (?), but the tuple structure may _not_ be reassigned.
- The `ref` tuple intent says that tuple _elements_ may be modified, and the tuple structure may be reassigned.
- The `const` (`ref`?) intent says that tuple _elements_ may _not_ be modified, and the tuple structure may _not_ be reassigned.

## What if an element is captured by const ref?

After some discussion with @mppf, I've interpreted constness of tuple elements to mean something like this...

```
When a tuple element is captured by `ref` (based on the default argument
intent of its type), whether or not that reference is `const` depends on
the constness of the value that is captured, with respect to the current
scope.

For each tuple element to be captured by `ref`:

-  If the value to be captured is `const`, then the tuple element will
   be captured by `const ref`.
-  Otherwise, the tuple element will be captured by `ref`.
```

Can someone else familiar with the CHIP6 design clarify if this interpretation seems correct?

- If so, how does this interpretation interact with the above tuple argument intents? What if I pass a tuple expression that has captured a record by `const ref` to a routine with the _default_ tuple argument intent? Should I expect that particular call site to emit an error?
- If not, could you be so kind as to clarify what the expected semantics are, here?

**Comment by cassella** [comment]
FWIW, there are a few other open issues about tuple intents, such as 

is tuple default intent always const ref? #9610
fix the default intent for a tuple of ranges, ints #9104
What does passing a tuple by ref intent mean? #10742

**Comment by dlongnecke-cray** [comment]
Thanks @cassella! I'll look into those.

**Comment by dlongnecke-cray** [comment]
Closing this as we added a section to the spec...
