### ISSUE TITLE
Specify brick name in mason {new, init}

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#14955]
Follow-on to https://github.com/chapel-lang/chapel/issues/7961:

This feature request is to support `mason new --moduleName` to differentiate the directory name and the module name. For example:

```
mason new illegal-module-name --moduleName LegalModuleName
```

This could also be supported in `mason init`  when that is supported (https://github.com/chapel-lang/chapel/pull/14820). This should generate an error if running `mason init` in project with an existing brick name.

I see the tasks for this issue as:

1. Add the `—moduleName` flag to `mason new` (and `mason init` when that is merged)
2. Update the warning for when a user specifies an illegal name in `mason new <name>` to suggest using `—moduleName`
3. Update the help output and documentation

We may consider alternatives to `--moduleName`, such as`--name`, `--brickName`, `--projectName`, ...

**Comment by ankingcodes** [comment]
@ben-albrecht I think we should stick to `--moduleName` as its purpose is to simply change the module name of the library project. I'm working on it 👍 
Also , shouldn't there be an '=' in the command as in `--moduleName=LegalModuleName`

**Comment by ben-albrecht** [comment]
I think it should support both. I checked and `mason build --example`, and think that should be extended as well to support both styles as well:

```
# This works:
mason build --example foo
# This is an error:
mason build --example=foo
```

**Comment by ankingcodes** [comment]
> I don't think we should support a space between -- and the flag name (assuming that space was intentional in your example).

@ben-albrecht  oops, that was unintentional, what I meant to ask is that should we support both `--moduleName=foo` and `--moduleName foo` or either of them ?

**Comment by ben-albrecht** [comment]
yes, both. I have opened https://github.com/chapel-lang/chapel/issues/14989 to document the broader inconsistencies in mason.

**Comment by ben-albrecht** [comment]
I am requesting input from other Chapel developers on naming this flag, which lets the user specify a mason package name that differs from the directory name in `mason new`.

Options include:

1. `mason new foo-bar --moduleName=FooBar`
    -  specific
    -  originally proposed by @bryantlam in the suggestion that led to this feature ([comment](https://github.com/chapel-lang/chapel/issues/7961#issuecomment-349809540))
2. `mason new foo-bar --name=FooBar`
    - concise
3. `mason new foo-bar --projectName=FooBar`
    - also specific
    - arguably more accurate, since it impacts the module name _and_ the package name


For reference, the current `mason new` options are:

```
Usage:
    mason new [options] <project name>

Options:
    -h, --help                   Display this message
        --show                   Increase verbosity
        --no-vcs                 Do not initialize a git repository
```

**Comment by ben-albrecht** [comment]
:+1: for `--moduleName`

**Comment by ben-albrecht** [comment]
:+1: for `--name`

**Comment by ben-albrecht** [comment]
:+1: to vote for `--projectName`

**Comment by BryantLam** [comment]
I don't have a strong opinion, but other options like `--brickName` or `--packageName` could be considered more specific depending on how you define `brick` and/or `package` in the future.

**Comment by ankingcodes** [comment]
@ben-albrecht I think we should proceed with `--name` since it got max votes 👍

**Comment by ben-albrecht** [comment]
> @ben-albrecht I think we should proceed with --name since it got max votes 👍

@ankingcodes Sounds good!
