### ISSUE TITLE
Slight Mistake in Docs for Point.writeThis

### ISSUE THREAD

**Issue by CaptainLazarus** [chapel-lang/chapel#14962]
## 

Problem
In the docs (both online and offline), specifically in 
[Docs > Primer > Procedures](https://chapel-lang.org/docs/primers/procedures.html)

in the **overloading operators** section there is the following code.

![chapelOriginal](https://user-images.githubusercontent.com/35800668/75101034-9188c280-55fc-11ea-9761-d7f1881a57c2.png)

Actually compiling this gives us the following error

![chapelError](https://user-images.githubusercontent.com/35800668/75101058-de6c9900-55fc-11ea-80d1-df683602fc2d.png)

In the offline docs I changed it to how it was supposed to look (not the docs from the github repo, but from the latest release on the website). 

![chapelNew](https://user-images.githubusercontent.com/35800668/75101060-edebe200-55fc-11ea-91ad-228ee08c1a61.png)

The docs need to be **updated** to reflect the changes.

**Comment by ty1027** [comment]
@CaptainLazarus Did you possibly define a module explicitly and include the code into it? Something like...
```
module Test {
// the code in the Primer here
}
```
(I stumbled on a similar problem before, so wondering if the reason is the same.)

**Comment by ben-albrecht** [comment]
@ty1027 - I suspect you are right. The above code is tested nightly and works because it is in a "prototype module".

@CaptainLazarus - See the [error handling primer](https://chapel-lang.org/docs/master/primers/errorHandling.html#modules) for more info on prototype vs. explicit modules with strict error handling.

**Comment by mppf** [comment]
After PR  #14360, these writeThis methods should be marked `throws`

```
proc Point.writeThis(w) throws 
{
...
}
```

It would be appreciated if you can check if that resolves the issue for you and if so, make a PR against master making the change.

**Comment by bradcray** [comment]
Tagging @dlongnecke-cray since this is an area he's worked in recently.

**Comment by dlongnecke-cray** [comment]
Sounds like there's some doc work to do.

**Comment by CaptainLazarus** [comment]
> After PR #14360, these writeThis methods should be marked `throws`
> 
> ```
> proc Point.writeThis(w) throws 
> {
> ...
> }
> ```
> 
> It would be appreciated if you can check if that resolves the issue for you and if so, make a PR against master making the change.

I checked but I ran into a lot of other issues. One of the things is that the parameter I passed through was a Point, which is a record. I don't know how to check if its initialized or not (still searching). The other is that if we do that then we need to catch the throws whenever we use **writeln()** for a Point record, which to me seems very tedious. Any thoughts?

**Comment by CaptainLazarus** [comment]
> @CaptainLazarus Did you possibly define a module explicitly and include the code into it? Something like...
> 
> ```
> module Test {
> // the code in the Primer here
> }
> ```
> 
> (I stumbled on a similar problem before, so wondering if the reason for the error is the same.)

Did with and without module. Same error.

**Comment by bradcray** [comment]
> I don't know how to check if its initialized or not (still searching).

There shouldn't be a way for you to get access to an uninitialized record unless you're within an initializer routine itself.

**Comment by bradcray** [comment]
> If we do mark the function as throws then we need to catch whenever we use writeln() for a Point record, which to me seems very tedious. Any thoughts?

IIRC, a standalone writeln() ought to handle any thrown errors itself (by halting if they occur).  Only a `channel.writeln()` should actually throw the error back up to the user.

To avoid the tedium of putting a try on each channel.writeln(), you could also put one at an outer scope and catch any thrown errors that way.  But for the sake of conversation: how would you propose handling errors in I/O short of throwing them?

I still haven't been able to reproduce your original problem, though.  I tried taking the code from the OP and [compiling it with 1.20 which works](https://tio.run/##rZLLboMwEEX3fMUVK1AIeUjdNOo/dJE2W1wYBUuWbRknBEX9djqGvJC6yCJeIGZ8PWdeZS0sqb53VBpX4dNI7XHGUTicMnTvcCTUBr9RtFhgS0qhNi28gagq@NbAhhcNe/bka3I5nj2RdabELLGr9xGbwa4vv2l0jgAmflPpjQsw6aXRkBrreWNFSc@DrjxwLf7gNDS1I4bZ@Qkz5uZcLBvdaHTpJhorfukJAXeEUmgI1RiYIzllBPexJhRF66SnbS2bJC0KOHPwUge1UlThp8Nwr3Q@DfjaDIeZDL3J7@m0t3Hsgq@B9ODsIBoIlIb3RmrhCVbI5@fPAduRkcRJzA2/256h@WniijP8o@mmmjQe53ZpVBJ/NVLvYSw5Ebbo2m92BmXY8cq0Gh8PG7Fa5ssM/LkIwpuJYLifvw2CG2gIM7uKOdkHx4Mu3fT9Hw) and with master.  Can you provide more information on your environment and how to reproduce?

**Comment by CaptainLazarus** [comment]
Code's given below. @ty1027  was right. Putting it in a module was the problem.
```

**Comment by CaptainLazarus** [comment]
@ty1027 was right. Putting in a module was the problem.

The original code.
```
module Graph {
    record Point {var x,y: real;}

    proc +(p1: Point , p2: Point) {
        return new Point(p1.x + p2.x , p1.y + p2.y);
    }


    proc Point.writeThis(w) {   
        w.write("(");
        w.write(this.x);
        w.write(",");
        w.write(this.y);
        w.write(")");
    }

    proc main() {    
        writeln("Using operator overloading");
        var a,b : Point;
        a = new Point(1,2);
        b = new Point(4,5);
        writeln("Sum: " , (a+b));
        writeln();
    }
}
```

**Comment by ty1027** [comment]
@CaptainLazarus I think this is something that new users may come across when learning Chapel (like the case of mine and yours). So if possible, could you consider re-posting your original post above (in this thread) to StackOverflow, as a kind of question? (e.g., "why this error occurs?") I expect it would be useful for other people also.
https://stackoverflow.com/questions/tagged/chapel

**Comment by dlongnecke-cray** [comment]
Hi @CaptainLazarus, just wanted to reiterate what Michael said earlier here: https://github.com/chapel-lang/chapel/issues/14962#issuecomment-590331402

On `master` today, you should make sure that all your `readThis` and `writeThis` overloads have the `throws` tag. In the future, we might even add a compiler warning letting you know (getting an error from deep within the `modules/standard/IO.chpl` module is not very intuitive). 

For now, though, I'm just going to have to update the docs to avoid confusion.

As Brad said earlier:

> > If we do mark the function as throws then we need to catch whenever we use writeln() for a Point record, which to me seems very tedious. Any thoughts?
> 
> IIRC, a standalone writeln() ought to handle any thrown errors itself (by halting if they occur). Only a `channel.writeln()` should actually throw the error back up to the user.

The `writeln` routine will halt if an error gets thrown from the IO machinery. It's only the `channel.writeln` _method_ and friends that will `throw`.

If you make sure your `Point.writeThis` routine has the `throws` tag, your code will compile and run regardless of whether you're using a prototype module or a regular old module.
