### ISSUE TITLE
domain.ranges tuple index starts from 1, should start from 0?

### ISSUE THREAD

**Issue by Aniket21mathur** [chapel-lang/chapel#14963]
While compiling the following code
 
```
var Days = {1..10};
writeln(Days.ranges(0));
```
the following error is thrown

```
range.chpl:2: error: tuple index 0 is out of bounds
range.chpl:2: note: tuple elements start at index 1
```
Can we have the tuple index to also start from 0? As in other cases (Arrays and range), the standard starting index is 0.

**Comment by bradcray** [comment]
Ranges don't have a standard starting index in Chapel, both low and high bounds need to be specified.  The same is true for arrays with declared types, and those that don't have a declared type have started from 1 through Chapel 1.20.  Issue #12988 raises the question of whether Chapel should switch to 0-based indexing for tuples and other cases with implicit indexing (I'm closing this one as a duplicate), and PRs #14522, #14521, #14671, #14684, and #14800 get this mostly implemented.  Stay tuned.

**Comment by Aniket21mathur** [comment]
@bradcray thanks for updating. :smile:
