### ISSUE TITLE
Locale values should be values, not raw classes

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#14961]
Today, values of locale type expose the fact that they are represented in our implementation as classes.  I believe that locales ought to effectively have value semantics from the user's perspective, where the implementation is likely to use a record wrapping the current locale class such that they still take advantage of the "unique identity" aspect of classes.

Related issues: #7706, #13526, https://github.com/chapel-lang/chapel/issues/13602#issuecomment-585451841, https://github.com/Cray/chapel-private/issues/521

For the most part, I'd been thinking that the implementation of this would be fairly straightforward, though I think there is one non-trivial stumbling block:  `on loc` (where `loc` is a variable of type `locale`) ought to move a task to locale `loc` but the naive implementation using a record would move it to where the record lived; so it seems that something special will be required for on-clauses referring to expressions of locale type.  It may be that this isn't so different from some of the special-casing we have today, but it's at least slightly different in that a class-based locale type already has "go to where the object is located" semantics.

**Comment by mppf** [comment]
Can this be closed now that PR https://github.com/chapel-lang/chapel/pull/15149 is merged?

**Comment by bradcray** [comment]
Definitely!  Thanks Engin!
