### ISSUE TITLE
Improve error message for non-fully-instantiated types in standard data structures

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#14974]
Standard data structures should do a better job giving error messages when a
not-fully-instantiated type is used. Currently they propagate the error coming
from their internal implementation.

```chapel
use Map;

record R {
  type t;
}

var l: map(int, R);
writeln(l);
```

gives

```
$CHPL_HOME/modules/standard/Map.chpl:99: In initializer:
$CHPL_HOME/modules/standard/Map.chpl:74: warning: creating an array with element type R
$CHPL_HOME/modules/standard/Map.chpl:74: error: array element type cannot currently be generic
../listRegexp.chpl:10: Initializer instantiated as: init(type keyType = int(64), type valType = R, param parSafe = 0)
```

Whereas, `list` gives a more complicated error in the same scenario:
```
$CHPL_HOME/modules/standard/List.chpl:149: In initializer:
$CHPL_HOME/modules/standard/List.chpl:155: error: Could not coerce 'nil' to '_ddata(_ddata(R))' in initialization
../listRegexp.chpl:10: Initializer instantiated as: init(type eltType = R, param parSafe = 0)
```

I think both of these error messages should say something similar to what arrays
are doing `map/list element type cannot be generic` etc.

**Comment by e-kayrakli** [comment]
A spin-off from https://github.com/chapel-lang/chapel/issues/14895

**Comment by e-kayrakli** [comment]
Tagging @dlongnecke-cray and @daviditen

**Comment by dlongnecke-cray** [comment]
Would something like...

```chapel
if isGenericType(eltType) then
    compilerWarning("Generic element types are not supported");
```

As is done in `buildArray` in `modules/internal/ChapelArray.chpl` take care of things?

Or perhaps another overload with `isGeneric` in a where clause.

**Comment by e-kayrakli** [comment]
I don't know about isGenericType myself, but it looks like something that should work.

I am not sure what can the compiler do. A type field in a generic record/class can also be generic, right? So it seems to me that `list` and `map` should say that "hey, I don't like generic types".

**Comment by dlongnecke-cray** [comment]
Right, `isGenericType` is what arrays currently use to address this problem. To me, it feels like the initializer should just reject a type parameter if it's not fully instantiated, but there might be a good reason why we don't want to do that.

It just seems kind of ugly to have to have O(n) worth of `compilerErrors` to address the problem, is all.
