### ISSUE TITLE
Provide essential `export` examples in quickstart instructions

### ISSUE THREAD

**Issue by Rapiz1** [chapel-lang/chapel#14988]
I'm new to Chapel and just set up my installation. And I think we may add basic `export` examples of setting up Chapel for beginners.

Here's my experience: I followed the quickstart instructions and try to make the env setting up automatically every time I start a shell. Then I found that simply sourcing `util/setchplenv.fish` will slow down the startup of fish. So I looked into the script and found that it runs several python scripts, which may slow down the startup. And I realized that some of scripts are not necessary for   me. Furthermore, I read the Chapel env documentation and wrote up my own script to quickly set up just *basic* environment.

As for current `util/setchplenv`, it's good and considerate. But it's not suitable for startup configuration. Because the stuff of `fixpath` and checking seems to be overkilled.

So as far as I'm concerned, it will be much better that, a beginner like myself, can simply copy a few lines of provided `export` examples for quickstart, change the CHPL_HOME, and then get a functional environment, thus saving the effort to read the original script, and the env documentation, and write their own configuration.

The issue is my first attempt to contribute to the community. Also, I'm very willing to improve the documentation. Looking forward to your comments :)

**Comment by ben-albrecht** [comment]
One challenge with this is that the `PATH` value will depend on the user's configuration which is computed from `util/chplenv/chpl_bin_subdir.py`.

Other than that, I think the standard `setchplenv.*` functionality could be summarized in documentation as:

```sh
# bash
export CHPL_HOME=<path/to/chapel>
export PATH=`"$CHPL_HOME"/util/chplenv/chpl_bin_subdir.py`:$PATH
export MANPATH="$CHPL_HOME"/man:$MANPATH"
```

These settings are mentioned in [setting up your environment for chapel](https://chapel-lang.org/docs/master/usingchapel/chplenv.html?highlight=export%20chpl_home#recommended-settings) docs already. 

@Rapiz1 - do you have any specific suggestions for improving these docs / making them easier to find if you did not see them?

**Comment by Rapiz1** [comment]
> One challenge with this is that the `PATH` value will depend on the user's configuration which is computed from `util/chplenv/chpl_bin_subdir.py`.
> 
> Other than that, I think the standard `setchplenv.*` functionality could be summarized in documentation as:
> 
> ```shell
> # bash
> export CHPL_HOME=<path/to/chapel>
> export PATH=`"$CHPL_HOME"/util/chplenv/chpl_bin_subdir.py`:$PATH
> export MANPATH="$CHPL_HOME"/man:$MANPATH"
> ```
> 
> These settings are mentioned in [setting up your environment for chapel](https://chapel-lang.org/docs/master/usingchapel/chplenv.html#recommended-settings) docs already.
> 
> @Rapiz1 - do you have any specific suggestions for improving these docs / making them easier to find if you did not see them?

I have read this page and it looks good to me. But what I'm focused on is whether we can make  [Quickstart](https://chapel-lang.org/docs/master/usingchapel/QUICKSTART.html#chapel-quickstart-instructions) more user-friendly.

The three lines example is exactly what I propose to put in the quickstart instructions as a more straight forward solution to make Chapel relevant commands available every time a shell is open.
`setchplenv.*` is doing its good job helping beginners to run commands *once*. But few users would be satisfied with that. And they may have the same experience as me reading `setchplenv.*` and other scripts invoked to determine what should be kept and what shouldn't. And it will save this trouble if we can put the example in the quickstart.

Furthermore, we can even deliver a script that determines which shell is used and then adds `export` lines to the configuration file.

As for the old `CHPL_HOME` problem, I think we should warn users if old variables detected, and try to remove relevant lines in configuration if possible. If failed, prompt an error. Simply calling `fixpath.py` don't root the problem and may add to the complexity.

So there are two ways I think can make installation more user-friendly:
1. Add simple configuration examples and instructions in the quickstart.
2. Deliver a script that sets up everything. e.g. `install.sh`

Maybe the title of this issue should be changed to `make installation more user-friendly`

It would be great if we have this:
```
# Set environment variables to preferred configuration
source util/setchplenv.bash

# re-build Chapel
make

# make check is available but optional
make check

# compile a sample program
chpl -o hello examples/hello.chpl

# run the sample program
./hello

# Add environment variables to the rc file
./install.sh
```

**Comment by e-kayrakli** [comment]
There is this: https://github.com/chapel-lang/chapel/issues/10367

**Comment by bradcray** [comment]
> I followed the quickstart instructions and try to make the env setting up automatically every time I start a shell. Then I found that simply sourcing util/setchplenv.fish will slow down the startup of fish.

I think that most of the setchplenv.* files print out the settings that they are making as they're running.  If I wanted to automate this setup by putting it into my shell's dotfiles, I'd encourage putting the `export` commands that achieve these same settings into my dotfiles rather than sourcing the script each time.  Maybe the quickstart could suggest this route?  Maybe in this sentence "In particular, you might use a chplconfig file or set environment variables your in dot files or your own script."  (Wow, that's not even a valid English sentence...)

I think the constant tension with the quickstart file is to try not to have it say everything or teach everyone how to do things like edit dotfiles if they don't already know how to (and it's already feeling a bit long and verbose to me).  So I'd suggest trying to tweak this wording to have it describe the idea of adding commands to one's dotfiles to recreate the settings printed by the setchplenv.* file rather than expanding it to include sample export commands or the like...

Those are my quick thoughts anyway...

(I'd also be really happy if someone fixed the grammar of that sentence now that it's caught my eye)

**Comment by Rapiz1** [comment]
>At this point, you can choose to continue using setchplenv.bash. Or if you want to automate this setup, refer to [Recommended Settings](https://chapel-lang.org/docs/master/usingchapel/chplenv.html#recommended-settings) for essential variables that should be exported in your dotfiles. Also, you might use a [chplconfig](https://chapel-lang.org/docs/master/usingchapel/chplenv.html#readme-chplenv-chplconfig) file or set environment variables in your dotfiles or your own script.
See [chplenv.rst](https://chapel-lang.org/docs/master/usingchapel/chplenv.html#readme-chplenv) for a complete description of Chapel’s configuration variables, what they mean, and how they can be set.

What about changing like? @ben-albrecht

**Comment by ben-albrecht** [comment]
@Rapiz1 - That seems like a reasonable change to me. Would you be interested in opening a PR? We could fine tune wording in review if needed.

While we're at it, here are a few other suggestions / micro-optimizations for this part of the docs:

- Add a code block at the top (or bottom) or [Recommended Settings](https://chapel-lang.org/docs/master/usingchapel/chplenv.html#recommended-settings) that contains the snippet needed to copy/paste into a user's `bashrc`.
- Add a `.. note` to the [Quickstart Instructions](https://chapel-lang.org/docs/master/usingchapel/QUICKSTART.html#chapel-quickstart-instructions) to point out that these settings will be lost outside of this terminal session unless the user modifies their `bashrc` (or whatever shell they are using).
  - This is obvious to most, but we have seen many users not familiar with unix stumble over this in the past.
- Englishify this line: `In particular, you might use a chplconfig file or set environment variables your in dot files or your own script.`

**Comment by Rapiz1** [comment]
> @Rapiz1 - That seems like a reasonable change to me. Would you be interested in opening a PR? We could fine tune wording in review if needed.
@ben-albrecht Sure. https://github.com/chapel-lang/chapel/pull/15022
