### ISSUE TITLE
Consistent kwarg-parsing in mason

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#14989]
For any mason flags that accept a value (what I'm calling a keyword-arg (kwarg)), we should consistently:

1. support `--flag value` style
2. support `--flag=value` style
3. Include the value placeholder in the help output with the format: `--flag <value>`

Examples include:

```
mason build --example <example>
mason run --example <example>
mason test --setComm <comm>
mason external find -t <tags>
```

**Comment by ankingcodes** [comment]
@ben-albrecht Since I'm already working on a similar issue, I'll be taking this along with #14955

**Comment by ben-albrecht** [comment]
Thanks @ankingcodes. If possible, it would be best if you were able to separate fixing all mason kwargs (this issue) from adding `--moduleName` in 2 different PRs.

**Comment by ben-albrecht** [comment]
Stumbled across https://github.com/chapel-lang/chapel/issues/14990 while testing these out.

**Comment by ankingcodes** [comment]
@ben-albrecht Got it !

**Comment by ankingcodes** [comment]
@ben-albrecht can we add `mason search --show=packageName` to that list ?

**Comment by ben-albrecht** [comment]
`--show` is bool flag for `mason search` still. It requires the search query to return 1 package to work though.

**Comment by ankingcodes** [comment]
@ben-albrecht We can close this now. 
For archival purposes, `mason test` arg parsing was refactored to select style in this issue.

**Comment by ben-albrecht** [comment]
Closed in https://github.com/chapel-lang/chapel/pull/16098
