### ISSUE TITLE
mason update --help does not print help output

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#14990]
`mason update --help` and `mason update -h`  runs update rather than printing help output.

Similarly, running `mason update -h` outside of a mason package gives this error:

```
Mason could not find your configuration file (Mason.toml)
```

This is a bug in the `MasonUpdate` argument-parsing.

I suggest refactoring `MasonUpdate.chpl` to use the select-statement style of arg-parsing similar to what is used in `MasonModify.chpl` and `MasonExternal.chpl` while fixing this issue.

**Comment by ankingcodes** [comment]
I'd work on this 👍

**Comment by ben-albrecht** [comment]
@ankingcodes - thanks!

**Comment by ben-albrecht** [comment]
@ankingcodes - I would suggest refactoring `MasonUpdate` to use the select-statement style of arg-parsing similar to what I suggested in #14997 while fixing this.

**Comment by ankingcodes** [comment]
@ben-albrecht cool! Let's update this issue's heading and description ?

**Comment by ben-albrecht** [comment]
@ankingcodes - sounds good.

**Comment by bradcray** [comment]
@ben-albrecht: What remains here?

**Comment by ben-albrecht** [comment]
Should have been closed after https://github.com/chapel-lang/chapel/pull/16078 was merged.

Closing now (thanks @ankingcodes!).
