### ISSUE TITLE
it is possible to access a global in the code initializing it

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#15008]
It is possible for an initializer called when creating a global variable to refer to that global variable. The result is access to uninitialized memory, but at least the memory is zero'd by the C backend...

Here is an example with copy-init:

``` chapel
var otherGlobal: R;

proc returnOtherGlobalRef() ref : R {
  return otherGlobal;
}

var globalR: R = returnOtherGlobalRef();
writeln("globalR is ", globalR);

class C {
  var x: int;
}

record R {
  var x: int;
  var c: owned C;

  proc init() {
    this.x = 1;
    this.c = new owned C(this.x);
  }

  proc init=(other:R) {
    writeln("init=, globalR is ", globalR);
    this.x = other.x;
    this.c = new owned C(this.x);
  }
}
```

```
init=, globalR is (x = 0, c = x.chpl:24: error: halt reached - argument to ! is nil
```

Here is another example using virtual dispatch:

``` chapel
var otherGlobal: R;

proc returnOtherGlobalRef() ref : R {
  return otherGlobal;
}

var rfactory: RFactory = new MyRFactory();
var globalR: R = rfactory.makeR();
writeln("globalR is ", globalR);

class RFactory {
  proc makeR() : R {
    return new R();
  }
}

class MyRFactory : RFactory {
  override proc makeR() : R {
    writeln("in MyRFactory.makeR, globalR is ", globalR);
    return new R();
  }
}


class C {
  var x: int;
}

record R {
  var x: int;
  var c: owned C;

  proc init() {
    this.x = 1;
    this.c = new owned C(this.x);
  }

  proc init=(other:R) {
    writeln("init=, globalR is ", globalR);
    this.x = other.x;
    this.c = new owned C(this.x);
  }
}
```

```
in MyRFactory.makeR, globalR is (x = 0, c = y.chpl:19: error: halt reached - argument to ! is nil
```

The problem seems to be avoided in simple cases by the function resolution order. The cases above use elements of the compiler where resolution of a function body is put off for one reason or another.

Should the compiler be able to report these as errors at compile-time? Or are such programs invalid and the answer is "don't do that"?

**Comment by bradcray** [comment]
It definitely seems like it would be preferable for the compiler to generate errors for such cases if it could.

This seems somewhat related to the circularities that can occur when initializing module-scope variables via helper functions [TIO]( https://tio.run/##S85ILEjN@f@/LLFIocJKITOvRMFWIS0/X0PTmgskVgkTS0osAolxFRTlJ0MUKFRzKSgUpZaUFuUpVCpoKxhac9VC5cGKkeUroPL//wMA), though that case at least results in error messages (although not always the clearest ones).
