### ISSUE TITLE
Improve error message on Mason Run

### ISSUE THREAD

**Issue by ankingcodes** [chapel-lang/chapel#15009]
Currently, when we run `mason run --example someproject.chpl` , and if that has not been built , we get an error 

```
Mason failed to find and run compiled example: someproject.chpl
```

This error message should be more comprehensive and should tell the user to build the program first using 
`mason build --example someproject.chpl`

**Comment by ben-albrecht** [comment]
Here is my suggested wording:

```
Example has not been compiled: someproject.chpl
Try running: mason build --example someProject.chpl
         or: mason run --example someproject.chpl --build
```

**Comment by ben-albrecht** [comment]
Here is my suggested wording:

```
Example has not been compiled: someproject.chpl
Try running: mason build --example someProject.chpl
         or: mason run --example someproject.chpl --build
```

**Comment by klakho0400** [comment]
hey @ankingcodes I would like to work on it

**Comment by klakho0400** [comment]
hey i think there is one more problem in the MasonExample.chpl when i opened it in vscode
after the line 324) const t = example.strip().strip(' " '); all the following lines are shown as a part of a single string

**Comment by ben-albrecht** [comment]
> hey @ankingcodes I would like to work on it

I would wait to hear back from @ankingcodes to hear if he has started working on this already

> hey i think there is one more problem in the MasonExample.chpl when i opened it in vscode
after the line 324) const t = example.strip().strip(' " '); all the following lines are shown as a part of a single string

@klakho0400 - That is a syntax highlighting bug. You can file an issue on that if you are able to create a small reproducer. I believe the vs code syntax highlighting originates from the tmbundle syntax highlighting.

**Comment by ankingcodes** [comment]
hello @klakho0400 , thanks for your interest. 
@ben-albrecht I had raised this issue when I was working on #14989 , and I had made the change  locally. So, this issue would be covered when PR for #14989 is made and merged. 
Since, I haven't made a PR already and if this issue was supposed to be covered in a separate PR, I'd encourage @klakho0400 to go forward with it.

**Comment by klakho0400** [comment]
@ankingcodes I have raised a PR for the same
