### ISSUE TITLE
Should split-init and copy-elision apply to module-scope variables?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#15012]
This issue is a spin-off from #14271 ( in particular https://github.com/chapel-lang/chapel/issues/14271#issuecomment-591997457 and https://github.com/chapel-lang/chapel/issues/14271#issuecomment-592079992 )

The question here is whether or not split init and copy elision can apply to module-scope (aka global) variables. In this context, the concern is that both split-init and copy elision create some duration in the code where the module-scope variable is declared but not initialized (either because it was not initialized yet, in the case of split-init; or because its value is moved somewhere else, in the case of copy-elision). However, despite this concern, Chapel programmers often try writing Chapel code outside of functions and so it would be nice if such experimentation led one to learn about the same rules that apply within functions.

Here I know of 4 possibilities.

### 1. Do not apply split-init or copy elision to global variables

This is what we do today. Its main drawback is that users trying to experiment with the language will get different behavior at module-scope from in a nested block or function. That presents a barrier to understandability.

### 2. Allow split-init or copy elision if no calls to user functions while variable is dead

The idea here is to allow split-init or copy-elision if there are no calls to user code in the time period in which the variable is uninitialized/dead.

E.g. for split init this would allow
``` chapel
var globalR;
globalR = otherGlobal; // split init
```

but this program would result in compilation error ("globalR has no type and can't be split-inited"):

``` chapel
var globalR;
f(); // function call could refer to globalR!
globalR = otherGlobal; // split init
```

This would help with experimentation, but literally `var x; x = something;` is not a very compelling use case for split-init. As a result it might not actually help in practice for a user moving code between module scope and some inner scope.

### 3. Allow split-init or copy elision for module-scope variables not mentioned in inner functions

This rule is similar to the current rule for nested functions (#14621). The idea here is to allow split-init or copy-elision if there are no calls to user code that could refer to the variable in the time period in which the variable is uninitialized/dead.

E.g. for split init this would allow
``` chapel
var globalR;
f();
globalR = otherGlobal; // split init

proc f() {
  // body does not refer to globalR
}
```

but this program would result in compilation error ("globalR has no type and can't be split-inited"):

``` chapel
var globalR;
g(); // function call could refer to globalR!
globalR = otherGlobal; // not split init

proc g() {
  ... globalR ...
}
```

However if the global variable is declared with a type, the example below will compile. The compiler will choose default-init/assign rather than split-init in the `g` case:

``` chapel
var globalR: R;
g(); // function call could refer to globalR!
globalR = otherGlobal; // assignment - not split init

proc g() {
  ... globalR ...
}
```

A drawback of this is that it would require whole-program analysis - but as issue #15008 discusses - such analysis might be necessary anyway in order to ensure global variables are only accessed after they are initialized.

### 4. Allow split-init or copy elision for module-scope variables and rely on checking

The idea here is to always apply split-init and copy-elison to module-scope variables in the same way as for local variables; however make it a compilation error if the variable is potentially used before initialized or after it is dead. The idea here is that the analysis required for #15008 can be adjusted to take into account which functions are called before and during initialization (and after a copy is elided) and check that these cannot potentially refer to the variable.

E.g. for split init this would allow
``` chapel
var globalR;
f();
globalR = otherGlobal; // split init

proc f() {
  // body does not refer to globalR
}
```

but this program would result in compilation error ("g() uses globalR before it is initialized"):

``` chapel
var globalR;
g(); // error: function call could refer to globalR!
globalR = otherGlobal; // split init

proc g() {
  ... globalR ...
}
```

However if the global variable is declared with a type, the compiler will choose between default-init/assign and split-init. In this design, the compiler would always choose split-init if possible according to the normal split-init rules, and it would raise a compilation error if it's possible that `globalR` was used before being initialized. 

``` chapel
var globalR: R;
g(); // function call could refer to globalR! -> compilation error.
globalR = otherGlobal; // still split init

proc g() {
  ... globalR ...
}
```

If we chose this option, we would presumably also adjust split-init with nested functions to behave similarly.

**Comment by bradcray** [comment]
In discussing this with Michael, we talked about a few guiding principles in making these decisions that seemed attractive:

* when taking a piece of code from a function or block statement to the module scope (or vice-versa), it'd be nice for it to continue working as similarly and seamlessly as possible rather than requiring changes

* module-scope variables and references to them within procedures should be symmetrical with local variables and references to them within nested functions.

**Comment by mppf** [comment]
I am thinking that option 4 is the best answer. I have several reasons for that which I describe below.

First, we need option 3 or 4 to meet Brad's guiding principles above.

After that, the big difference between 3 and 4 is whether or not the compiler needs to do the analysis of called functions in order to make a determination about split init. In option 4, the compiler still needs to analyze called functions to look for misuse of global variables - but that can happen any time after split init analysis.

In some ways this situation is similar to recent choices in this area that choose to make the behavior simpler but add checking. Two specific examples are how split-init requires variables to be initialized in the same order across conditionals (#14747) and how it will be an error to use something referring to a copy-elided variable after the copy elision (#14874). The idea here is that the simpler behaviors are easier to understand and remember and the compile-time checking will prevent misuse.

This strategy has a few advantages.

First, even if the compile-time checking is not completely robust, programs making the error are still erroneous programs. In other words, improving the compile-time checking will not be a language stability issue but rather an ergonomics one.

Second, the option 4 strategy allows the checking to be performed at any point after resolution. In a separate compilation scenario, it might make sense to perform this checking at link-time (based on information collected during the compilation - namely, which global variables are referred to in which functions). In option 3, the checking cannot happen at link-time because it affects program behavior (and indeed, which functions are resolved and which compile-time errors occur). So option 3 would make separate compilation implementation harder (but not impossible).

**Comment by bradcray** [comment]
I'm cool with proceeding with option 4.

**Comment by mppf** [comment]
I don't think either 3 or 4 is reasonable for copy elision of public module-scope variables.

Suppose we have module `M`:
``` chapel
module M {
  public var x: SomeRecord;
  public var y = x; // is this copy elision?
}
```

Now suppose we have code in another module using M:
``` chapel
{
  use M;
  M.x;
}
```

If the copy elision is not allowed because of this access of `x`, then we have a situation where another module is affecting the behavior in M which isn't good (and might create "hijacking" situations).

If the copy elision is allowed and the access of `x` is to become an error, then we have a situation where the module declared a public variable that can never be used after the module init function finishes (so... basically it can never be used).

That implies that for copy elision specifically, the copy elision should not be allowed for public module variables.

But, even for private module variables, we could have the same situation with a nested module:

``` chapel
module MM {
  record SomeRecord { }
  private var x: SomeRecord;
  private var y:SomeRecord = x; // is this copy elision?

  module Inner {
    writeln(x);

    proc innerfn() { }
  }

  proc main() {
    Inner.innerfn();
  }
}
```

(This program does not compile right now due to a resolution order issue - `7: error: use of 'x' before encountering its definition, type unknown`).

However, because the nested module is likely to be by the same author, it might be reasonable to make this an error according to strategy 4.

Now, one of the motivations here (from https://github.com/chapel-lang/chapel/issues/15012#issuecomment-592160414) is that code at module scope behave similarly to code in a nested block with respect to split-init and copy elision.

Suppose we had
``` chapel
#13801

**Comment by mppf** [comment]
Note to self: I need to close this issue (after PR #15113) and make a new issue specifically about copy elision and global variables.

**Comment by mppf** [comment]
PR #15113 enabled split-init for module-scope variables.
Issue #15270 talks about copy elision (specifically) for module-scope variables.
