### ISSUE TITLE
Implement TimSort in Sort module

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#15045]
Implement [timSort](https://en.wikipedia.org/wiki/Timsort) as another sort option in the Sort module. (Spun off from https://github.com/chapel-lang/chapel/issues/5724)

The PR adding TimSort should include:

- Documentation
- Correctness tests in `test/library/packages/Sort/corrrectness`
- Performance tests in `test/library/packages/Sort/performance`
  - Comparable performance to existing sort routines

**Comment by rahulghangas** [comment]
Can I take this one?

**Comment by ben-albrecht** [comment]
@rahulghangas - I believe @RisingGeek is planning to work on it (https://github.com/chapel-lang/chapel/issues/5724#issuecomment-590525390).

**Comment by rahulghangas** [comment]
Cool, thanks for the update

**Comment by mukul-mehta** [comment]
If the issue is still open and no progress has been made so far, could I work on this issue?

**Comment by RisingGeek** [comment]
@mukul-mehta I am working on this issue. Feel free to work on this if you have a solution.

**Comment by ben-albrecht** [comment]
You are welcome to work together or separately on solutions. Contributing a performant timsort has stumped many Chapel contributors in the past :)

**Comment by omar-3** [comment]
I see that the issue is still open, is anyone working on it? could I work on it?

**Comment by ben-albrecht** [comment]
@omar-3 - @RisingGeek has an open PR in https://github.com/chapel-lang/chapel/pull/15236 but there has not been activity on it for ~3 weeks. I think it would be OK to work on it, but just be aware that we would only be merging one of the implementations.

**Comment by omar-3** [comment]
yea for sure

**Comment by Yudhishthira1406** [comment]
Hi, I want to confirm the issue is still open

**Comment by Yudhishthira1406** [comment]
Please review my PR

**Comment by ben-albrecht** [comment]
Closed in #16961
