### ISSUE TITLE
Assembler Output of individual code chunks - Desirable / Low Priority

### ISSUE THREAD

**Issue by damianmoz** [chapel-lang/chapel#15043]
To debug compiler peculiarities, evaluate how well one's code maps to what the hardware will execute, or to evaluate the deep-down issues in bottlenecks, it is desirable to be able to review the assembler created out of a piece of any language.

At the moment, the closest we get to this is the C-code out of Chapel. It can be read by looking at the code contained in the directory specified with the '-savec' option.

It would be highly advantageous to see the actual assembler without the rest of the stuff that gets pulled into an executable.

**Comment by mppf** [comment]
Note that `--llvm-print-ir` allows one to inspect the LLVM IR at different optimization stages when using the LLVM backend. While this does not come all the way to machine instructions, it is thematically related and might serve a similar purpose.

**Comment by bradcray** [comment]
@damianmoz: I'd expect that with the C back-end, any flag that the C compiler supports to look at generated assembly could be supplied through the Chapel compiler via `--ccflags` to see the assembly.  Does that get you where you want?

In suggesting that, I'm realizing I'm not sure I understand what you mean by "without the rest of the stuff that gets pulled into an executable."

**Comment by damianmoz** [comment]
I am open to anything that minimizes your work. I was unsure how to phrase it.

I really do not understand the phases of the compiler so I do not know how to answer the question.

**Comment by mppf** [comment]
@bradcray - I think the request is to dump just the assembly from one function. (Vs say saving all assembly from everything and then looking for your function). I don't know how to do that with C compiler flags but it would not be hard to script up. (E.g. objdump can do it easily enough).

**Comment by damianmoz** [comment]
Consider the following which is in a file called say 'max.chpl':
```chapel
// NaN safe version without the signed zero stuff

proc maximum(x : ?Real, y : Real) : Real
{
        return if x >= y then x else if x < y then y else x + y;
}

proc main
{
        const x = 10.0;
        const y = 25.0;

        writeln("maximum of ", x, " and ", y, " is ", maximum(x, y));
}
```
If I look in the --savec directory, I find 24000+ lines o C-code of which 67 lines are a file called 'max.c' where there are 4 static routines. The first and last are an initializer and entry, the other two correspond to my 'maximum' procedure and then 'main'. It is impossible to compile this file in a standalone fashion using
```
gcc -S -O3 max.c
```
to find out the assembler it will create because it is missing the include entries to pull in definitions like _real64.  Also, as the procedures are all defined as static, they get expanded in line.

In this case, I want to see what assembler is generated for the generic procedure maximum.  Sure, I can cut and past and fake up my own definitions in this simple case. But for a far more complex example, it becomes prohibitive. It would be nice to be able to do this transparently just as I can do now for every other compiled language with which I work. And yes, I know it is harder or generic routines. but I can sort that bit out by invoking it in an actual context.

Note that the use of 'objdump' is a bit of a sledge hammer and shows you the net result after linkage. Not really what I want. I want something with a bit more finesse.

Currently I am working on some 'sum-of-squares' routines and having to do testing in C to get an idea of optimal coding approaches. But the real target is Chapel as my eventual aim is to replace the Chapel norm routines which are inaccurate and very naively coded and far from a state-of-the-art algorithm for that operation.

**Comment by bradcray** [comment]
Got it, thanks for the clarification.  You're right that there's not a simple way to do this today; you would either need to look at the assembly for the whole program and hone in on some markers to find your routine of interest; or you would need to do surgery and/or massaging of the generated C to reduce it down to just the piece you need.

It feels like I got about 90% towards a successful surgery for your example, but not quite all the way there.  What I did:

1) Compiled max.chpl with a few extra flags:

```shell
$ chpl max.chpl --savec output --fast --ccflags -S
```

and ignored that it failed.

2) Edited `output/Makefile`, replacing `main.c` with `max.c`

3) Edited `output/max.c` to insert the lines:

```c
#include "chpl_str_config.c"
#include "chpl__header.h"
```

at the top

4) Did `make output/Makefile`

This got me through the compilation step with warnings, but ones that seemed OK to ignore.  The link step blew up, though, and I couldn't find my assembly file.  I think what's happening is that our normal compile step is renaming the assembly via `-o` (which it adds to name the .o file) and then it's proceeding to the linker step which is treating that as assembly.  So probably the next step is to chop up or clone `runtime/etc/Makefile.exe` to squash the link step and maybe drop the .o step?  But I'm timing out for tonight.

**Comment by mppf** [comment]
I tend to use the GCC flag `-save-temps` to do this sort of thing. It lets compilation proceed as usual and just creates some .S files. That doesn't address the problem of there being a lot of assembly to sort through to find the function.

> Note that the use of 'objdump' is a bit of a sledge hammer and shows you the net result after linkage. Not really what I want. I want something with a bit more finesse.

If objdump is used to show assembly for only one particular function after linkage - vs say dumping out everything - it seems to be more or less what you want. Am I wrong about that? Are you concerned about link-time optimization or something?

**Comment by mppf** [comment]
I've created PR #21076 to resolve this but would appreciate help in testing it.
