### ISSUE TITLE
Request: select-when with compound when clauses

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#15048]
Feature Request.

The goal is to reduce code duplication with select-when statements. Is there a way to do something like / is it reasonable to do:

```chapel
select myInt {
  when 42 { ... }
  when 1 || when 2 { ... }
  // Edit: ~~when 3 && when 4 { ... }~~ // This is wrong; this case can't ever fire.
  // etc.
}
```
without resorting to the equivalent if-statement expressions.

**Comment by bradcray** [comment]
I'm not finding or recollecting any capability like this, and agree that it's an oversight.

I understand the OP's proposal could be viewed as just a placeholder, but I'd be disinclined to use short-circuiting boolean operators for this purpose, I think.  Thinking out loud about potential alternatives:

commas (advantages: brief; disadvantages: potentially confusing?):

```chapel
select myInt {
  when 42 { ... }
  when 1, 2 { ... }
  when 3, 4 { ... }
  // etc.
}
```


or adjacent when-clauses without a body (advantage: clearer?  disadvantages: more verbose; maybe still unclear?):

```chapel
select myInt {
  when 42 { ... }
  when 1
  when 2 { ... }
  when 3
  when 4 { ... }
  // etc.
}
```

another variation (require colons for when clauses that are intended to stack:

```chapel
select myInt {
  when 42 { ... }
  when 1:
  when 2 { ... }
  when 3:
  when 4 { ... }
  // etc.
}
```

**Comment by BryantLam** [comment]
> another variation (require colons for when clauses that are intended to stack

Of the three options, I like this one the best.

That said, none of the three variations handle the OR-case; they all only do AND. This is fine if there was a good reason to preclude it, but I can't think of a reason.

**Comment by bradcray** [comment]
> none of the three variations handle the OR-case; they all only do AND.

Oh, you're right that I completely overlooked that.  I'm not understanding... how can `myInt` be both 3 and 4?

I meant to say in my original response, but forgot:  One of the things we very intentionally did in the select statement's original design was to avoid the C behavior of "fall through to the next case unless the user explicitly `break;`s", so something I hope to avoid in any extension to select is having a way of partially sharing the actions of a given case as in C.

**Comment by BryantLam** [comment]
Oh hah yeah that's a good point too. These should all be OR expressions. That does reasonably limit the choice of syntax.

**Comment by DanilaFe** [comment]
We now have this, and it's locked down in numerous places, including `test/trivial/deitz/statements/select1.chpl`. Commas are used to combine mulitple clauses.

```
var x : int = 12;

writeln(x);

select x {
  when 3, 4, 2 + 8 do writeln("failure");
  when 8 + 4 { writeln("success"); }
  otherwise writeln("otherwise");
}
```

Prints:

```
12
success
```
