### ISSUE TITLE
Implement Unrolled Linked Lists module

### ISSUE THREAD

**Issue by abhi170599** [chapel-lang/chapel#15064]
an unrolled linked list is a variation on the linked list which stores multiple elements in each node. It can dramatically increase cache performance, while decreasing the memory overhead associated with storing list metadata such as references.

I would like to extend the standard chapel library by adding Unrolled Linked Lists to it.

**Comment by ben-albrecht** [comment]
I think any effort related here should begin as a mason package. Whether or not these implementations should be in the standard library would be a separate discussion later down the road once the package is more mature.

**Comment by maheshkulkarni123OS** [comment]
#15064 regarding to this issue @ben-albrecht tell me how to write my chapel Unrolled Linked List Module's code in the format of mason package

**Comment by ben-albrecht** [comment]
@maheshkulkarni123OS - the relevant information can be found here: https://chapel-lang.org/docs/master/tools/mason/mason.html

**Comment by cassella** [comment]
An `UnrolledLinkedList` packages module was added by #16244.

**Comment by bradcray** [comment]
Thanks Paul.
