### ISSUE TITLE
Support git submodules for mason

### ISSUE THREAD

**Issue by ankingcodes** [chapel-lang/chapel#15076]
Supporting `git submodules` would mean adding an existing github repository as a dependency in our current Chapel library project. This would allow users to use a chapel library project which is not necessarily a part of Mason registry. I have a proposal for this feature : 
- Improve MasonModify to support commands such as `mason add <specific_giturl>`
- It would check the `Mason.toml` file at that `url` for `chplVersion` and `version` and decide whether the package is updated/deprecated. 
- if updated, it would add `projectName` from `Mason.toml` file to our current projects `Mason.toml` 
- Improve `mason update` to update a git submodule 
- If there's a function that fetches modules from mason registry, improve that for git submodules, else, think about creating one. 

@ben-albrecht what do you think about this feature ?

**Comment by ben-albrecht** [comment]
@ankingcodes - is there precedent for this feature in other package managers?

> adding an existing github repository as a dependency in our current Chapel library project.

This is possible today, but requires the user to:

(1) create a local registry
(2) add that github repo to their local registry as a package
(3) include that local registry in their `MASON_REGISTRY` env

I would personally like to see this workflow optimized to require minimal commands from a user. With that in mind, I am not sure how this git submodules proposal fits into the picture.

**Comment by ankingcodes** [comment]
>  is there precedent for this feature in other package managers?

@ben-albrecht yes, Dlang's DUB had a very similar issue sometime ago, where they discussed a similar approach to which I mentioned. I'm not sure if they have added that feature yet.

**Comment by ankingcodes** [comment]
Also, npm currently supports such a feature, which works in a similar fashion

**Comment by ben-albrecht** [comment]
@ankingcodes - OK, thanks. Would this provide any functionality beyond adding the repository to a local registry as described above (assuming this process was streamlined)?

**Comment by ankingcodes** [comment]
> Would this provide any functionality beyond adding the repository to a local registry as described above (assuming this process was streamlined)?

@ben-albrecht  I believe no. This issue would optimize the workflow you mentioned above, would update the dependencies table of  Mason.toml file, added to that would be the version checking. All that in a single command `mason add <git_url>`.

**Comment by ben-albrecht** [comment]
Alright. My preference is still to streamline the process in https://github.com/chapel-lang/chapel/issues/15076#issuecomment-594624541 over introducing a new mechanism of projects having dependencies. Managing dependencies is already a complicated process, so I strongly favor simplicity when possible.

**Comment by ankingcodes** [comment]
@ben-albrecht  Cool ! optimizing the process in [comment](https://github.com/chapel-lang/chapel/issues/15076#issuecomment-594624541) would be a good starting point. 
Do you have any ideas ?

**Comment by ben-albrecht** [comment]
It's an open design question. I have some rough ideas that may help us get started.

Would you like to open an issue for the overall goal and we can brainstorm some ideas in that issue over time?

**Comment by ben-albrecht** [comment]
@ankingcodes - I am tempted to close this issue for now, and we can re-open if we see an opportunity with this feature that can not be achieved in  #15079 -- what do you think?

**Comment by ankingcodes** [comment]
I'm okay with that 👍
