### ISSUE TITLE
Incorrect .rst rendering in docs

### ISSUE THREAD

**Issue by Rapiz1** [chapel-lang/chapel#15108]
In [this doc](https://chapel-lang.org/docs/master/primers/classes.html):

- - -
![image](https://user-images.githubusercontent.com/20105061/76058408-55b80a80-5fb7-11ea-8abc-fc56ce2579d8.png)
I think this intend an unordered list like this:
* use the borrow after whatever it is borrowed from goes out of scope
* use the borrow after the instance is deleted (for example if own is assigned to)
- - -

![image](https://user-images.githubusercontent.com/20105061/76058484-85671280-5fb7-11ea-9b33-4485233d617f.png)
Should be:
Note that when applied to an `owned` or `shared` variable, `!` will result in a borrow from that variable.
- - -

I open this issue to ensure these are mistakes and may post more if I can find anything else. 
A PR will soon follow.

**Comment by Rapiz1** [comment]
The first problem seems to be caused by rendering:
https://github.com/chapel-lang/chapel/blob/eab0615591f9f40cbf495d5db1e50e43492a14f4/test/release/examples/primers/classes.chpl#L119-L124
This grammar is correct but `*` is not considered as unordered-list by the renderer.

**Comment by ben-albrecht** [comment]
Thanks @Rapiz1! Are you interested in contributing a fix?

**Comment by Rapiz1** [comment]
@ben-albrecht Sure. The first problem is easy to fix and I can immediately open a PR. As for the second problem, I think further investigation into `chpldoc` is needed and I will give it a shot.
