### ISSUE TITLE
Revisit chpldocs for 'owned' and 'shared'

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#15114]
The chpldocs for `owned` and `shared` treats them as records, ex. by documenting individual initializers. This needs to be brought up to date with the language, which treats them as either annotations on class types or, when one of these keywords is used on its own, generic class types.

**Comment by lydia-duncan** [comment]
(Ran across this while looking for another issue) The documentation for these has been moved to the spec.  I think that means this can be closed, right Vass?

**Comment by vasslitvinov** [comment]
I still see the spec talking about `record owned`, its initializers, and links to it. So I do not see that this issue has been resolved.
