### ISSUE TITLE
The introduction to testing in docs of Mason is outdated

### ISSUE THREAD

**Issue by Rapiz1** [chapel-lang/chapel#15110]
Here in [Testing your package](https://chapel-lang.org/docs/tools/mason/mason.html#testing-your-package) presents an example:
```
use UnitTest;

config const testParam: bool = true;

proc myTest(test: Test) {
  test.assertTrue(testParam);
}
```
But this won't work with the current version. I tried adding the example above and got this:
```
$ mason test

Updating mason-registry

----------------------------------------------------------------------
No Tests Found
```
The solution is in [UnitTest](https://chapel-lang.org/docs/modules/packages/UnitTest.html#module-UnitTest). Previous example seems to be using the old grammar.

I think we can use this new example in the page of mason instead:
```
use UnitTest;

config const testParam: bool = true;

proc myTest(test: borrowed Test) throws{
  test.assertTrue(testParam);
}

UnitTest.main()
```

**Comment by ben-albrecht** [comment]
Thanks @Rapiz1 - would you be interested in opening a PR with the following?

1. A fix for the docs
2. An added test with the exact test from the docs (to help us identify if the test case from the docs breaks in the future)

**Comment by Rapiz1** [comment]
@ben-albrecht Sure. Sorry if I'm being naive, where can I start from to add a test for the docs?

**Comment by ben-albrecht** [comment]
I would put it in `test/library/packages/UnitTest/docs/`.

See here for docs on test system:

https://github.com/chapel-lang/chapel/blob/master/doc/rst/developer/bestPractices/TestSystem.rst#creating-a-simple-test

See other tests in `test/library/packages/UnitTest/` for examples to start from.

**Comment by Rapiz1** [comment]
Thanks. I will look into it soon.

**Comment by ben-albrecht** [comment]
Actually, this may make more sense to put into`test/mason/mason-test/docs`

**Comment by krishnadey30** [comment]
Thanks for pointing this out. I saw it earlier but forgot about it.
