### ISSUE TITLE
Resolution rules are confusing

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#15128]
Chapel 1.20.0.

```chapel
proc broken1() {
  var x = one;
}
```
[TIO ↑](https://tio.run/##S85ILEjN@f@/oCg/WSGpKD87Nc9QQ1OhmktBoSyxSKFCwVYhPy/Vmqv2/38A) versus [TIO ↓](https://tio.run/##S85ILEjN@f@/oCg/WSGpKD87Nc9QQ1OhmktBoSyxSKFCwVYhPy/VmquWiwusJDcxMw8kX/v/PwA)
```chapel
proc broken1() {
  var x = one;
}

proc main() {} // Added main!
```
both yield the same error message:
```terminal
error: 'one' undeclared (first use this function)
```

However, when you wrap it in a module, that error now goes away.
```chapel
module A {
  proc broken2() {
    var x = two;
  }
}
```
```terminal
error: 'two' undeclared (first use this function)
```
[TIO ↑](https://tio.run/##S85ILEjN@f8/Nz@lNCdVwVGhmktBoaAoP1khqSg/OzXPSEMTLKSgUJZYpFChYKtQUp5vDRSo5ar9/x8A) versus the variant with `main` that successfully compiles [TIO ↓](https://tio.run/##S85ILEjN@f8/Nz@lNCdVwVGhmktBoaAoP1khqSg/OzXPSEMTLKSgUJZYpFChYKtQUp5vDRSo5arl4gIrzE3MzAOpqv3/HwA):
```chapel
module A {
  proc broken2() {
    var x = two;
  }
}

proc main() {}

// This code compiles.
```
I think this is because the `A` module is the main module in the first variant, but the second variant with the explicit `main` function treats module `A` as unused. However, the `A.broken2()` is still malformed. The compiler should be checking all code when possible so that the user isn't surprised when they write some module, think it's okay, and then later use it to find out that module is broken and should have never "compiled". (Yes, it is technically dead code, but dead code should still be semantically correct.)

This problem would be important to remedy for libraries / packages. A test suite that uses the module would catch this case, but the fact that the compiler allows illegal code to compile feels incorrect and confusing.

**Comment by BryantLam** [comment]
OP is a specific case of the resolution rules being confusing. There's probably other instances that I'm trying to recall...

**Comment by bradcray** [comment]
Hi @BryantLam: Did something above get mis-transcribed or dropped?  It looks like there's supposed to be a code sample that doesn't generate an error, but all three shown here seem to (and it looks like you think they all do, which is what I'm seeing with 1.20 as well).

**Comment by BryantLam** [comment]
(Added it in.)

**Comment by bradcray** [comment]
> I think this is because the A module is the main module in the first variant, but the second variant with the explicit main function treats module A as unused.

This is an accurate description of what's going on.

> The compiler should be checking all code when possible so that the user isn't surprised when they write some module, think it's okay, and then later use it to find out that module is broken and should have never "compiled". (Yes, it is technically dead code, but dead code should still be semantically correct.)

I think we agree here.  Recall that we made a big push on this a year or so back, but then other things took priority before that effort successfully wrapped up:

https://github.com/chapel-lang/chapel/issues/10276
https://github.com/chapel-lang/chapel/issues/11182
https://github.com/chapel-lang/chapel/issues/11271

I'd be inclined to call this a duplicate of #10276, but let me know if you disagree.

Note that this change will have an adverse affect on compile-time, but that a flag could be used to opt back into the current behavior to reduce it again.

**Comment by BryantLam** [comment]
Yep! Looks like it is a duplicate.
