### ISSUE TITLE
Add an overload of String.split to return array

### ISSUE THREAD

**Issue by rapiz1** [chapel-lang/chapel#15142]
It can be useful to have an overload of `String.split` to return a list instead of an iterator. e.g. when dealing with tables we want to random access values of items.
BTW, I thought that a list could be initialized from an iterator but it couldn't. I think this can also be very useful.

**Comment by bradcray** [comment]
It is possible to use `String.split` to generate an array (as mentioned in your issue title).  I'm less certain about a list.  See [this example](https://tio.run/##S85ILEjN@f@/LLFIwVHBVkEpI1OhJCO1KFWhKLEgs8pQUUmvuCAns0RDSUFJ05qrvCizJDUnT8NRr6SyINWquKQoMy9d0/r/fwA) which demonstrates it.

**Comment by ben-albrecht** [comment]
In addition to @bradcray's suggestion, there is a feature request to explicitly convert an iterator to an array inline here: https://github.com/chapel-lang/chapel/issues/14364

Also there is a feature request for iterator-to-list assignment: https://github.com/chapel-lang/chapel/issues/14497

**Comment by Rapiz1** [comment]
Oh, why we can use the return value of `String.split` as an array? How does this work?
I didn't see anything about converting an iterator into an array in [primers/iterator](https://chapel-lang.org/docs/primers/iterators.html).
Have I missed something and how can I find the docs?

**Comment by bradcray** [comment]
Somewhat confusingly, and perhaps unfortunately, when an iterator is captured into an untyped variable, that variable is automatically treated as an array.  There have been arguments made that perhaps it should remain an unevaluated iterator.  This is an aspect of the language that I would not be surprised if it changed in the future, but it's where we are today.

**Comment by Rapiz1** [comment]
Well...That's really hard for a beginner like me to foresee until someone explains...
What can we do about it? Add examples in docs? Or just leave it there?

**Comment by ben-albrecht** [comment]
Adding an example for this to the iterator primer isn't a bad idea...

I think this is something that will improve as we add support for first class iterators (https://github.com/chapel-lang/chapel/issues/15058)

**Comment by arezaii** [comment]
This appears to be implemented or resolved as demonstrated in the example:

```chapel
use List;

var A = "hi there rapiz1!".split(" ");
var L = new list("hi there rapiz1!".split(" "));

writeln(A.type:string);
writeln(L.type:string);
```
...compiles, and when executed produces:
```
[domain(1,int(64),false)] string
list(string,false)
```

Additionally, iterators as arrays is now documented at https://chapel-lang.org/docs/master/language/spec/iterators.html#iterators-as-arrays

while using iterators to initialize lists can be found at https://chapel-lang.org/docs/master/modules/standard/List.html?highlight=list#List.list

**Comment by e-kayrakli** [comment]
I don't think we have the exact thing that the issue description asks for (i.e. `split` that returns a `list`). Though, I agree that we have ways of achieving the same thing using other features of Chapel.

@Rapiz1 -- Do you think we can close this?

**Comment by jabraham17** [comment]
I am closing this, as there are other ways of achieving the same thing in Chapel and there has been little activity on this issue.
