### ISSUE TITLE
Unnecessary return statements in MasonTest

### ISSUE THREAD

**Issue by rajshekhar7** [chapel-lang/chapel#15163]
https://github.com/chapel-lang/chapel/blob/f5b0f309ae954e5dd74ab36c715039c0dfe18c6f/tools/mason/MasonTest.chpl#L298

In this function, `if` and `else if` statements return the same list which is also returned at the end of the function.

**Comment by bradcray** [comment]
For simple cases like this, please feel free to just open a PR that addresses the issue (and then bring it to someone's attention) if it's not much harder than opening the issue itself.

**Comment by rajshekhar7** [comment]
Ok.
