### ISSUE TITLE
`chpl --ldflags` has different ordering between C and LLVM backends

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#15168]
When using `chpl --ldflags`, the ldflags are presented to the C and LLVM backends differently.

For example, when adding runpaths to the linker, the generated executable has a different RUNPATH load order depending on whether the executable was created with the C backend or the LLVM backend.

```terminal
# C backend
$ chpl --ldflags -Wl,-rpath,/some/path hello.chpl \
  && objdump -x hello | grep RUNPATH | awk '{print $2}' | sed 's/:/\n/g'

$CHPL_HOME/third-party/qthread/install/linux64-x86_64-native-gnu-pic-flat-jemalloc-hwloc/lib
$CHPL_HOME/third-party/jemalloc/install/linux64-x86_64-native-gnu-pic/lib
$CHPL_HOME/third-party/gmp/install/linux64-x86_64-native-gnu-pic/lib
$CHPL_HOME/third-party/hwloc/install/linux64-x86_64-native-gnu-pic-flat/lib
$CHPL_HOME/third-party/re2/install/linux64-x86_64-native-gnu-pic/lib
/some/path

# LLVM backend
$ chpl --ldflags -Wl,-rpath,/some/path hello.chpl --llvm \
  && objdump -x hello | grep RUNPATH | awk '{print $2}' | sed 's/:/\n/g'

/some/path
$CHPL_HOME/third-party/qthread/install/linux64-x86_64-native-clang-included-pic-flat-jemalloc-hwloc/lib
$CHPL_HOME/third-party/jemalloc/install/linux64-x86_64-native-clang-included-pic/lib
$CHPL_HOME/third-party/gmp/install/linux64-x86_64-native-clang-included-pic/lib
$CHPL_HOME/third-party/hwloc/install/linux64-x86_64-native-clang-included-pic-flat/lib
$CHPL_HOME/third-party/re2/install/linux64-x86_64-native-clang-included-pic/lib
```
`chpl version 1.21.0 pre-release (f5b0f309a)`

Notice that `/some/path` is either before or after the default runpaths provided by `chpl`.

For this specific example, I think the order used by the LLVM backend is probably more correct since it allows the user (or system) the opportunity to override `chpl`'s default runpaths from when it was built; e.g., the user or system admin can provide a bugfixed version of hwloc.

**Comment by bradcray** [comment]
@gbtitus: I think you've been looking at linker flags lately.  Does this fit naturally into your court at all?

Also tagging @mppf (because of LLVM) and @dlongnecke-cray (whose also done some stuff with the linker line recently).

**Comment by gbtitus** [comment]
@bradc possibly, since it's even about linker flag ordering, which was/were the problem(s) I was solving a few weeks ago.  I'm nearly done with my current release-related item and could jump to this one today unless someone else pipes up about wanting it.

**Comment by bradcray** [comment]
That'd be great.  I also think that this could be a code freeze task (i.e., I didn't mean to imply that we needed to jump on it right away; more like "if the iron is still warm-ish from that effort, maybe we should tackle this simultaneously...").
