### ISSUE TITLE
Cast between nilable- and non-nilable class types doesn't work?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#15184]
### Summary of Problem

I was told that `C: C?` or `C?: C` ought to work and be a way of casting between class types, but it seems that this doesn't work as intended.

### Steps to Reproduce

**Associated Future Test(s):**
[`test/classes/casts/class-type-cast2.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/classes/casts/class-type-cast2.chpl
          ) #15183

### Configuration Information

- Output of `chpl --version`: `chpl version 1.21.0 pre-release (0fabc0fc93)`

**Comment by mppf** [comment]
Would you expect `int : int` to result in `int` or in an error?

If the answer is "error", I'm not so sure we want to support `C : C` or `C : C?`.

**Comment by bradcray** [comment]
I don't have a strong opinion about self-casts, though I'd probably be inclined to have them work and return the type itself.  That said, I wouldn't object to an error (or warning) either.

I'm not tied up in `C: C?` either per se.  Was just trying to understand the ways that nilable and non-nilable types could be obtained from the other and was thinking this would work (where it's obviously more interesting if the LHS `C` was actually a type alias or a `myExpr.type` or something like that).
