### ISSUE TITLE
split-init and deinitialization point

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#15206]
PR #15041 adjusted the compiler to use a simpler rule for deinit points. The rule is this:

> A variable is dead:
>  * after copy elision if it occurred (after the last mention is
>    used to copy-initialize a variable or in intent argument)
>  * for the results of nested call expressions not involved in initializing
>    a user variable or reference after the end of the statement
>  * otherwise, at the end of the scope in which it is declared

> There are two important things to note about the above rule:
>  1. "involved in initializing a user variable or reference" includes
>     through split-init
>  2. the above rule applies to module-scope variables (aka global
>     variables) as well as local variables. For global variables

However this rule is not interacting as nicely as one would hope with split-init.

Consider for example the follow program:

``` chapel
class C { var x: int; }
  
config param useBorrow = true;

proc main() {
  var x;
  if useBorrow {
    x = (new owned C(1)).borrow();
  } else {
    x = new owned C(1);
  }
  writeln(x, " : ", x.type:string);
}
```

(I ran into this pattern and the issue with it when writing tests for #15205).

Now, `x` is initialized with split-init. A variable declaration like `var x = (new owned C(1)).borrow();` would work without issue. The temporary storing the result of `new owned C(1)` is deinitialized at the end of its block. That is also true when split-init is used - but in the specific case above, the end-of-block is inside the conditional. The result is nil-checker and lifetime checker errors.

It is intentional that the deinit point rule consider split-inits as initializations. Could it go further and also create the temporary variables at the same scope as the variable being initialized?

In the exact case of the above program, that would mean bringing the temporary storing the result of `new owned C(1)` into the function scope. But, this temporary is only initialized in one branch of the conditional. How will the compiler know to deinitialize it only if that branch is taken? Will it require run-time tracking of which such temporaries are initialized?

**Comment by vasslitvinov** [comment]
Leaving the behavior the way you are describing appeals to me because it keeps the rules simpler. If we can live with this behavior, I would choose this option.

In what situations do you think we will want to enable this scenario in user code?

**Comment by mppf** [comment]
I think it's useful to be able to opt-in to destroying temporaries used in initialization expressions by using split-init and a block.

**Comment by mppf** [comment]
I think the current situation is OK so I am closing this issue.
