### ISSUE TITLE
Consistent internal field names for string and bytes records

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#15219]
For example, [string field](https://github.com/chapel-lang/chapel/blob/master/modules/internal/String.chpl#L771-L779) names are all over the place, that adds some annoyance while playing with the string code. We should have more consistent names and capitalization. `buffSize`, `buffLen`, `buff`, `isOwned`, `hasEscapes` would be a good start.

I introduced a lot of `buf` in local variables. Those should probably change to `buff`, too.

**Comment by ankingcodes** [comment]
@e-kayrakli I'd like to work on this

**Comment by priyank23** [comment]
@e-kayrakli I am a beginner here. This issue would be a good start for me to contribute to chapel. I would like to work to on this issue.

**Comment by priyank23** [comment]
@e-kayrakli I have submitted a pull request for the issue stated. It would be very helpful if you could review the same and suggest some more modifications required.

**Comment by ankingcodes** [comment]
@priyank23 I was already working on this in my local branch. You should probably consider asking before submitting a PR. Anyways, I'll let you take this one since you already made a PR.

**Comment by Aniket21mathur** [comment]
@ankingcodes @priyank23 to avoid this type of confusion, I prefer submitting a draft pull request as soon as I start working on an issue. Later you can mark it ready for review once you are done.

Thanks :smile:

**Comment by priyank23** [comment]
@ankingcodes Extremely sorry for the confusion. I am new in contributing and still figuring out the proper ways to do it. I hope you'd understand. 
Thanks for the support.

**Comment by klakho0400** [comment]
@priyank23  are you working on this

**Comment by priyank23** [comment]
@klakho0400 Yes
