### ISSUE TITLE
Use explicit types in ByteBufferHelpers

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#15217]
`modules/internal/ByteBufferHelpers.chpl` is the low-level common module for `bytes` and `string` types.

The helpers here use implicit types a bit too much. This caused a linux32 error in the past. It'd be a good idea to revise all the helper functions and make sure that arguments are explicitly-typed to help with maintainability of `bytes` and `string` implementations

**Comment by Aniket21mathur** [comment]
@e-kayrakli I would like to work on this. I analyzed the `ByteBufferHelpers` file and I have drafted a pull request, I would like you to review it once, as I am not sure whether I am on the right path or not. Thanks! :smile:
