### ISSUE TITLE
[Feature] Array that supports both real and int type

### ISSUE THREAD

**Issue by Aniket21mathur** [chapel-lang/chapel#15227]
Currently, the arrays either support all real elements or all integer elements. This can be extended to support both real and int together.

Example:-

Currently,

```
var arr = [1.1, 2, 3];
```
return an error,

```
rndm.chpl:1: error: Array literal element 2 expected to be of type real(64) but is of type int(64)
```

but it should accept both the types together once this feature is implemented.

**Comment by bradcray** [comment]
Just to make sure I understand: Is your intention that the array would be inferred to be an array of real since ints can coerce to reals?  If so, I think this is a repeat of issue #13591.

**Comment by Aniket21mathur** [comment]
> Just to make sure I understand: Is your intention that the array would be inferred to be an array of real since ints can coerce to reals?

Yes.

> If so, I think this is a repeat of issue #13591.

Thanks, for pointing out, I am closing this issue.
