### ISSUE TITLE
Extend param loop unrolling for `lo..#size` ranges

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#15250]
At present, `for param i ...` loops only work for fully-bounded ranges like `lo..hi` where `lo` and `hi` are param values.  It would be useful in a 0-based indexing world to extend this support to loops of the form `lo..#size` where `lo` and `size` are params in order to support loops of the form `for param i in 0..#size` in cases that require unrolling.

**Comment by bradcray** [comment]
Note that, `for param i in 0..<size` does support param unrolling in PR #15038

**Comment by ram-nad** [comment]
Sir I would like to work on this issue.

**Comment by krishnadey30** [comment]
I don't think anyone is working on this one. You can work on it @ram-nad
