### ISSUE TITLE
copy elision and module-scope variables

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#15270]
Should copy elision be allowed for module-scope variables?

(Spin-off from issue #15012).

It does not seem tractable to allow copy elision for public module-scope variables. However we could consider allowing it for private module-scope variables. (The implementation does not allow it for any module-scope variables, currently).

Suppose we have module `M`:
``` chapel
module M {
  public var x: SomeRecord;
  public var y = x; // is this copy elision?
}
```

Now suppose we have code in another module using M:
``` chapel
{
  use M;
  M.x;
}
```

If the copy elision is not allowed because of this access of `x`, then we have a situation where another module is affecting the behavior in M which isn't good (and might create "hijacking" situations).

If the copy elision is allowed and the access of `x` is to become an error, then we have a situation where the module declared a public variable that can never be used after the module init function finishes (so... basically it can never be used).

That implies that for copy elision specifically (vs split-init), the copy elision should not be allowed for public module variables.

But, even for private module variables, we could have the same situation with a nested module:

``` chapel
module MM {
  record SomeRecord { }
  private var x: SomeRecord;
  private var y:SomeRecord = x; // is this copy elision?

  module Inner {
    writeln(x);

    proc innerfn() { }
  }

  proc main() {
    Inner.innerfn();
  }
}
```

(This program does not compile right now due to a resolution order issue - `7: error: use of 'x' before encountering its definition, type unknown`).

However, because the nested module is likely to be by the same author, it might be reasonable to make this an error.

Now, one of the motivations here (from https://github.com/chapel-lang/chapel/issues/15012#issuecomment-592160414) is that code at module scope behave similarly to code in a nested block with respect to split-init and copy elision.

Suppose we had
``` chapel
// MyModule.chpl
var x: SomeRecord;
var y:SomeRecord = x; // is this copy elision? It would be in a nested block.
```

as long as the default visibility is public (which is currently the plan per #13801), other code could `use MyModule` and then try to access `x`. The result is that this case cannot be consistent.

**Comment by bradcray** [comment]
Currently, I feel fine about not doing copy elision for module-scope variables.  I think I'd want a very compelling use case showing a huge amount of benefit in order to justify putting effort into it.

**Comment by mppf** [comment]
I'm closing this issue since there doesn't seem to be anyone arguing for copy-elision of module-scope variables.
