### ISSUE TITLE
Using 'use' to re-export

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#15282]
`use` statements don't currently allow providing an alternative path to a symbol for qualified access. This means that `use` wouldn't have the expected effect when used for re-exporting if the module is `import`d or `use only`d. Note though that these patterns are expected to be possible to write with import.

``` chapel
module A {
  var x: int;
}

module B {
  public use A;
}

module Program {
  import B; // or use B only;

  proc main() {
    //writeln(B.x); // does not work today
    //writeln(B.A.x); // does not work today
  }
}
```

I would expect the `B.x` or `B.A.x` calls above to function.

**Comment by BryantLam** [comment]
Do we want to allow `use` to re-export? It seems potentially unsafe to allow non-obvious / hidden symbol conflicts. (It doesn't help that Rust developers are familiar with `pub use` for re-exports.)

**Comment by mppf** [comment]
@BryantLam - since we have both `use` and `import` it seems that they ought to work together. You might imagine that one person wrote `module B` (as a library) and then a different group (which is less of a fan of `use`) is trying to use it in `Program`.

> It seems potentially unsafe to allow non-obvious / hidden symbol conflicts.

These would already be possible, even with import. People wanting to have more control of namespace will need to use `import`. This issue only affects whether e.g. `B.x` is available. If the author of `Program` wrote `use B;` then they could already write `x` (and x is already subject to symbol name conflicts).

**Comment by BryantLam** [comment]
Okay I understand now. This is okay. :+1:
