### ISSUE TITLE
import can't name a private parent module symbol

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#15308]
### Summary of Problem

It seems that `import` can't be used to name a private symbol in a parent module even though (currently) the symbol can be referred to directly.  This seems to be new as of a PR today.

### Steps to Reproduce

**Associated Future Test(s):**
[`test/visibility/import/importPrivateParentSym.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/visibility/import/importPrivateParentSym.chpl
          ) #15307

### Configuration Information

- Output of `chpl --version`: `1.21.0 pre-release (52b68d036f)`

**Comment by lydia-duncan** [comment]
I have a branch to fix this issue undergoing testing right now
