### ISSUE TITLE
Filter srun error messages by default in start_test/sub_test

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#15339]
Any test that halts and runs on XC configuration requires a `PREDIFF` to filter out the srun error message accompanied by the halt:

```
srun: error: nid00014: task 0: Exited with exit code 1
srun: Terminating job step 1613222.0
```

E.g. [`lulesh/PREDIFF`](https://github.com/chapel-lang/chapel/blob/master/test/release/examples/benchmarks/lulesh/PREDIFF)

This is a feature request for start_test/sub_test to filter these errors automatically without a PREDIFF.

**Comment by ben-albrecht** [comment]
@gbtitus reminded me that the following setting should filter  srun errors:

```sh
export CHPL_SYSTEM_PREDIFF=$CHPL_HOME/util/test/prediff-for-slurm-srun
```

We currently aim to include this in most XC testing, but may have missed some cases (e.g. llvm).

**Comment by gbtitus** [comment]
Yes, we should arrange to set `CHPL_SYSTEM_PREDIFF=$CHPL_HOME/util/test/prediff-for-slurm-srun` for any nightly testing that uses slurm-based launching.

**Comment by ben-albrecht** [comment]
I think we can close this with https://github.com/chapel-lang/chapel/pull/15346 unless @ronawho or @gbtitus disagrees.
