### ISSUE TITLE
Import statement todos

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#15351]
The following are things I'd like to accomplish on import statements:
- [ ] Merge more UseStmt and ImportStmt similar code into shared code
  - providesNewSymbols and applyOuter* might be good candidates (Engin suggested something like `std::vector<Symbol *> ImportStmt::differentSymbols(ImportStmt *)` and `intersectSymbols`)
- [ ] add more tests
  - [x] using renamed.oldname for single symbol unqualified access (should fail)
  - [x] repeating symbols in imports for multiple symbol unqualified access (should fail)
  - [x] renaming a symbol that was also included (`import M.{a, a as b}`)
  - [x] rename to name that was included already (`import M.{a, b as a}`) (should fail)
  - [x] trying to list a name you can't find in the unqualified access list (`import M.{bad_name}`) (should fail)
  - [x] bad symbol in a rename segment (`import M.{"foo" as baz()}`, etc.)
  - [ ] more importAnd* combos with renaming involved
  - [x] can't find old name in rename (`import M.{bad_name as foo}`)
  - [x] rename when the symbol being renamed was private
  - [x] unqualified access to a private symbol (both in list and single form)
  - [x] rename same symbol twice in a list (`import M.{a as b, a as c}`)
  - [x] rename chain in same import (`import M.{a as b, b as c}`) (should fail)
  - [x] renaming a symbol doesn't allow unqualified access to symbols not in the list
- [x] I remember there being code that specifically expected scopeResolve to make some uses.  Now that we have applyOuter* for imports, I should find that code and ensure it fires for imports as well (update: it looks like this code has already been updated to handle both UseStmts and ImportStmts)
- [x] AST viewer updates for the unqualified names and renamed lists
- [x] figure out why `lview` complains if you try to use it with a `const UseStmt*`
- [x] use the new providesUnqualifiedAccess method in more places.
- [x] #15308
- [x] #15309 
- [x] #15265 
- [x] #14971 
- [x] #15605
- [ ] find spot where I backed away from something being const because I didn't realize toConst* existed?

**Comment by bradcray** [comment]
Should/can issues #15308, #15309, https://github.com/cray/chapel-private/issues/886, #15265 be added to this list as well?

**Comment by lydia-duncan** [comment]
886 should be resolved when I merge my open PR after final testing comes back, but other than that, yup!

**Comment by lydia-duncan** [comment]
All of the linked issues have now been resolved.  I'm going to not complete the unchecked boxes and close the PR - I'm out of steam for refactoring and I feel confident on the testing to the point that I don't think the remaining edge cases are required
