### ISSUE TITLE
Mason Test not skipping tests with failed compilation 

### ISSUE THREAD

**Issue by ankingcodes** [chapel-lang/chapel#15403]
This was an issue discussed in Gitter by @omar-3. It has been found that Mason Test doesn't skip tests which fail to compile producing an error as follows: 
```
$CHPL_HOME/modules/packages/UnitTest.chpl:1160: error: testCount: can not capture overloaded functions as values
compilation failed for functionalTest.chpl
uncaught FileNotFoundError: No such file or directory (encountered when launching subprocess)
  ./MasonTest.chpl:513: thrown here
  ./MasonTest.chpl:234: uncaught here
```
We'd want to not run tests which have given compilation error and improve the error message displayed.

**Comment by omar-3** [comment]
Hi thank you for taking time and write the issue. 

Here is the [repo](https://github.com/omar-3/functional) it has only one function and one test to help you guys see the problem.

**Comment by Rapiz1** [comment]
@ankingcodes Hi. Are you working on this?

**Comment by ankingcodes** [comment]
@Rapiz1 Thanks for your interest ! Actually, I had been working on this on a local branch and hope to make a PR soon. I'm extremely burdened with university work right now, so feel free to take this up if I don't make a PR in 2-3 days.
