### ISSUE TITLE
string.getView(range) doesn't respect range's alignment

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#15408]
https://github.com/chapel-lang/chapel/blob/b46e81dc3f70fb1e0fdae574613a35431ad0640c/modules/internal/String.chpl#L1395

Shouldn't that be r1.alignedLow:int..r1.alignedHigh:int by r1.stride?

```chapel
var s = "123456789abcdef";
var sv = s[1:byteIndex..10:byteIndex by 2 align 2:byteIndex ];
writeln(sv);
```

produces `13579` not `2468a`.   (prior to the strings-index-from-0 pr)

**Comment by bradcray** [comment]
Thanks for reporting this, and the fix, Paul!
