### ISSUE TITLE
Update Sort keyPart method to be 0-based

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#15419]
The `.keyPart()` method in the Sort module numbers its "parts" from 1.  With the recent change to 0-based indexing by default for implicitly indexed things, it probably makes sense to have it be 1-based as well.

**Comment by bradcray** [comment]
@mppf: Does this change seem correct to you?  Any interest in taking it on as a study break?  (I couldn't get to it before the 1.22 release and am generally gun-shy about Sort.chpl after changing other aspects of it to be 0-based).

**Comment by mppf** [comment]
Yeah, it seems like it should be 0-based. I can look at it at some point but I'm not certain if I'll be able to this week.
