### ISSUE TITLE
Make getField() / getFieldRef() take 0-based indices

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#15427]
With implicitly indexed things in Chapel going to 0-based counting (well, other than line numbers in code... :P ), should getField() and getFieldRef() also count fields from 0 rather than 1?

**Comment by gbtitus** [comment]
If I squint right, the fields of a record seem rather like the components of a heterogeneous tuple. So I voted for making this change in 1.22.

**Comment by bradcray** [comment]
Based on Greg's comment, I put a PR together for this here:  https://github.com/chapel-lang/chapel/issues/15427#issuecomment-610049090
