### ISSUE TITLE
mason external: support version ranges

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#15421]
The `mason external` subcommand should support version ranges.

Below are a few examples I would expect to work:

### `Mason.toml`

```
[brick]
name = "toml"
version = "0.1.0"
chplVersion = "1.22.0"

[dependencies]

[external]
libtomlc99 = "0.2019.06.24:" # minimum version
```

```
[brick]
name = "toml"
version = "0.1.0"
chplVersion = "1.22.0"

[dependencies]

[external]
libtomlc99 = ":0.2019.06.24" # maximum version
```

```
[brick]
name = "toml"
version = "0.1.0"
chplVersion = "1.22.0"

[dependencies]

[external]
libtomlc99 = "0.2019.03.06 :0.2019.06.24" # version range
```

### `src/Pkg.chpl`

```chpl
/* Documentation for toml */
module Pkg {
  require "toml.h"; // Confirm mason has successfully built with the right `-I` flag
}
```

## Tasks

These cases should now work  after https://github.com/chapel-lang/chapel/pull/15436, so the remaining work for this issue is to:

- [x] give a better error message when a version is not found
  - E.g."Mason resolved <spec> to <pkg@version%compiler>, which could not be found."
- [x] add tests for this feature

**Comment by bradcray** [comment]
Does TOML have a precedent for using `:` to specify a version range rather than the more Chapeltastic (and, to my eye, visible / comprehensible) `..`?

**Comment by ben-albrecht** [comment]
Mason uses the Spack syntax for external package versions, so that they can be passed directly to the Spack backend.

This is different from the `..` syntax used for Mason packages and Chapel versions. We could potentially add support for the `..` syntax in the future and just do the`s/../:/` under the covers though.

**Comment by ben-albrecht** [comment]
This was discovered during https://github.com/chapel-lang/chapel/pull/15422 - and felt like too big of an issue to address during code freeze period.

**Comment by ben-albrecht** [comment]
This may be resolved in https://github.com/chapel-lang/chapel/pull/15436, but I would want to write some proper tests to confirm before checking this off.

**Comment by ben-albrecht** [comment]
I can confirm this has been resolved. For closing this issue, we need to do the following:

- give a better error message when a version is not found
  - Error should say something like "Mason resolved <spec> to <pkg@version%clang>, which could not be found."
- add tests for this feature
 
Related to this issue, I found that mason continues to build a package even if an external package is missing. (TODO: open an issue on that)

**Comment by ankingcodes** [comment]
@ben-albrecht I'd like to take this up, if its available.

**Comment by ben-albrecht** [comment]
@ankingcodes - yes it is. That's be great. Thank you!
