### ISSUE TITLE
Map routines return 1-based arrays

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#15431]
While grepping for remaining instances of "1-based", I noticed that `Map` defines some routines that return 1-based arrays.  Should these be updated to 0-based now?

**Comment by bradcray** [comment]
Attn: @daviditen, @dlongnecke-cray

**Comment by dlongnecke-cray** [comment]
I definitely think these should be updated.

**Comment by bradcray** [comment]
I doubt I'll get to it in one of the next few days the way triage has been going if someone else is able to grab it.

**Comment by daviditen** [comment]
I'll take it today.

**Comment by daviditen** [comment]
PR #15455 changes them to 0-based. @dlongnecke-cray mind reviewing it? It's pretty straightforward.

**Comment by daviditen** [comment]
PR #15455 is merged.
