### ISSUE TITLE
Making `mason` makes a lot of stuff

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#15430]
While doing a debug-of-mason cycle today, I found myself wondering why so much stuff is built when mason is.  `make mason` attempts to build the compiler and runtime multiple times, once each due to the Makefile's stated dependence on `comprt`, one compiler build for `chpldoc`, and then a third time for `mason-no-chpldoc`'s dependence on `comprt` again.  This seems excessive, and the reason for a dependence on chpldoc isn't clear to me.  Could we do more to pare it down?

**Comment by bradcray** [comment]
Attn: @ben-albrecht.

**Comment by ben-albrecht** [comment]
Thanks for reporting @bradcray - `mason` uses `chpldoc` for `mason doc` subcommand.

Should be fixed here: https://github.com/chapel-lang/chapel/pull/15454
