### ISSUE TITLE
Restore lost docs

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#15477]
The following modules lost documentation due to #14900 .  Some of these modules have been updated already (I believe String and Bytes are probably okay), but the rest need to be looked at.

- [x] diff -r docPostChange/builtins/Bytes.rst docPreChange/builtins/Bytes.rst
- [x] diff -r docPostChange/builtins/CPtr.rst docPreChange/builtins/CPtr.rst
- [x] diff -r docPostChange/builtins/ChapelArray.rst docPreChange/builtins/ChapelArray.rst
- [x] diff -r docPostChange/builtins/ChapelIteratorSupport.rst docPreChange/builtins/ChapelIteratorSupport.rst
- [x] diff -r docPostChange/builtins/ChapelRange.rst docPreChange/builtins/ChapelRange.rst
- [x] diff -r docPostChange/builtins/String.rst docPreChange/builtins/String.rst
- [x] diff -r docPostChange/packages/DistributedBag.rst docPreChange/packages/DistributedBag.rst
- [x] diff -r docPostChange/packages/DistributedDeque.rst docPreChange/packages/DistributedDeque.rst
- [x] diff -r docPostChange/packages/DistributedIters.rst docPreChange/packages/DistributedIters.rst
- [x] diff -r docPostChange/packages/FFTW.rst docPreChange/packages/FFTW.rst
- [x] diff -r docPostChange/packages/RecordParser.rst docPreChange/packages/RecordParser.rst
- [x] diff -r docPostChange/packages/Sort.rst docPreChange/packages/Sort.rst
- [x] diff -r docPostChange/packages/UnorderedCopy.rst docPreChange/packages/UnorderedCopy.rst
- [ ] diff -r docPostChange/standard/DynamicIters.rst docPreChange/standard/DynamicIters.rst
- [ ] diff -r docPostChange/standard/IO.rst docPreChange/standard/IO.rst
- [x] diff -r docPostChange/standard/LinkedLists.rst docPreChange/standard/LinkedLists.rst
- [x] diff -r docPostChange/standard/Regexp.rst docPreChange/standard/Regexp.rst

Here's the full diff
[output3.txt](https://github.com/chapel-lang/chapel/files/4451560/output3.txt)

**Comment by lydia-duncan** [comment]
Recommended strategy: Comment here saying what module(s) you will take.  Open .txt file and go to the diff for that module, then search for the lost output string in the appropriate modules file.  Move the interrupting single line comments

**Comment by lydia-duncan** [comment]
I'm going to start with Regexp and LinkedLists

**Comment by Aniket21mathur** [comment]
@lydia-duncan should I take up DynamicIters and IO?

**Comment by lydia-duncan** [comment]
That'd be awesome :)

**Comment by lydia-duncan** [comment]
I'm done with Regexp and LinkedLists, grabbing Sort and UnorderedCopy

**Comment by dlongnecke-cray** [comment]
I'll go for DistributedBag and DistributedDeque.

**Comment by gbtitus** [comment]
I have FFTW.

**Comment by e-kayrakli** [comment]
I am fairly certain I have fixed Bytes and String yesterday, but will check again a little later and take some of those if there is any left

**Comment by lydia-duncan** [comment]
Taking CPtr and ChapelArray next

**Comment by dlongnecke-cray** [comment]
ChapelIteratorSupport and ChapelRange.

**Comment by lydia-duncan** [comment]
RecordParser

**Comment by lydia-duncan** [comment]
ChapelRange, and I think that's everything that's unaccounted for.  Go ahead and open PRs when you're done :)

**Comment by dlongnecke-cray** [comment]
ChapelRange had one change to make but ChapelIteratorSupport was a false positive (from the looks of things).

**Comment by dlongnecke-cray** [comment]
Did anyone take DistributedIters?

**Comment by lydia-duncan** [comment]
Oh, I don't think so.  Well spotted!

**Comment by dlongnecke-cray** [comment]
I can take it.

**Comment by gbtitus** [comment]
I took my lead from @e-kayrakli's fix for chpldoc rendering yesterday and just merged without review; hope that's ok.

**Comment by e-kayrakli** [comment]
>ChapelRange had one change to make but ChapelIteratorSupport was a false positive (from the looks of things).

I fixed ChapelIteratorSupport yesterday, too

**Comment by e-kayrakli** [comment]
Bytes is good, missed one in String yesterday :( Just checked off both of them

**Comment by lydia-duncan** [comment]
That's everything, thanks everyone for helping out :)
