### ISSUE TITLE
Installation docs refer to bash script which DNE

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#15507]
Installing a new machine and following [these instructions](https://chapel-lang.org/docs/usingchapel/QUICKSTART.html#using-a-more-full-featured-chapel).  They ask you to `source util/setchplenv.bash` which is not in the current distribution (11 April 2020)

**Comment by ben-albrecht** [comment]
@buddha314 - are referring to the Chapel 1.21 release or something else?

I see the script when pulling the release tarball:
 
```sh
> wget https://github.com/chapel-lang/chapel/releases/download/1.21.0/chapel-1.21.0.tar.gz
> tar -xvf chapel-1.21.0.tar.gz
> ls chapel-1.21.0/util/setchplenv.*
chapel-1.21.0/util/setchplenv.bash 
chapel-1.21.0/util/setchplenv.csh  
chapel-1.21.0/util/setchplenv.fish 
chapel-1.21.0/util/setchplenv.sh
```

**Comment by buddha314** [comment]
i was doing it from source and i must have done something very wrong, but it is clearly there.  Tried pulling 3 times.
