### ISSUE TITLE
Mason test does not support test file names with a single character

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#15522]
### Summary of Problem

Putting tests in a filename with 1 character (not including file extension) results in an error for `mason test`. This is a result of a bug in `MasonUtils.stripExt()`, where the slice range becomes `..0` when the filename has 1 character:

https://github.com/chapel-lang/chapel/blob/master/tools/mason/MasonUtils.chpl#L87-L95

I expect addressing this edge case to be a pretty simple fix, so marking as `[easy]`.

### Steps to Reproduce

```sh
> mason new Foo
> cd Foo
> echo "use Foo;" > test/x.chpl
> mason test
Missing argument for flag: '--main-module' (use '-h' for help)
compilation failed for x.chpl
uncaught PermissionError: Permission denied (encountered when launching subprocess)
  ./MasonTest.chpl:530: thrown here
  ./MasonTest.chpl:246: uncaught here
```

### Configuration Information

- Output of `chpl --version`: `chpl version 1.23.0 pre-release (89fc2c6cb0)`

**Comment by ben-albrecht** [comment]
Discovered this when trying to reproduce https://github.com/chapel-lang/chapel/issues/15521

**Comment by Aniket21mathur** [comment]
@ben-albrecht I would like to take this up

**Comment by ben-albrecht** [comment]
@Aniket21mathur - OK thanks!

**Comment by cassella** [comment]
Why isn't `s[..0]` correct?  Shouldn't it just be `s[0]`, which would be correct?  `s[..1]` results in two characters:

```chapel
var s = "hello";

writeln(s[0]);
writeln(s[0..0]);
writeln(s[..0]);

writeln(s[1]);
writeln(s[0..1]);
writeln(s[..1]);
```

```
h


e
he
he
```

**Comment by ben-albrecht** [comment]
Thanks @cassella - I have created an issue for this.

I think the fix in this PR is still a valid work-around until this issue is resolved.
