### ISSUE TITLE
FileNotFoundError on importing a `src` module in mason `test`  

### ISSUE THREAD

**Issue by Aniket21mathur** [chapel-lang/chapel#15521]
### Summary of Problem
Importing a `src` module in a test file and running `mason test` results in a `FileNotFoundError` .

```bash
Updating mason-registry
/home/h4ck3y3/lib/protobuf/test/varinttest.chpl:1: error: Cannot find module or enum 'Protobuf'
compilation failed for varinttest.chpl
uncaught FileNotFoundError: No such file or directory (encountered when launching subprocess)
  ./MasonTest.chpl:514: thrown here
  ./MasonTest.chpl:235: uncaught here

``` 

Mason.toml

```toml
[brick]
name = "Protobuf"
version = "0.1.0"
chplVersion = "1.23.0"

[dependencies]

```

`tree` output for project:

```
├── example
├── LICENSE
├── Mason.lock
├── Mason.toml
├── README.md
├── src
│   └── Protobuf.chpl
├── target
│   ├── debug
│   ├── example
│   └── test
└── test
    └── varinttest.chpl
```

### Steps to Reproduce

**Source Code:**

A test file with below content would suffice to reproduce the error

```chapel
use Protobuf;
```
### Configuration Information

```bash
chpl version 1.23.0 pre-release (22dc508e76)

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_LLVM: llvm
CHPL_AUX_FILESYS: none
```

**Comment by ben-albrecht** [comment]
@Aniket21mathur - thanks for reporting. I actually _haven't_ reproduced this error yet. Trying to reproduce it now. I've also added some information from the GItter discussion to the issue description.

**Comment by ben-albrecht** [comment]
@Aniket21mathur - here was my attempt to reproduce:

```sh
> chpl --version
chpl version 1.23.0 pre-release (89fc2c6cb0)
> mason new Protobuf
> cd Protobuf
> echo "use Protobuf;" > test/varinttest.chpl
> mason test
Updating mason-registry
----------------------------------------------------------------------
Ran 1 test in 6.47565 seconds

OK (passed = 1 )
```

Can you see if these steps generate the error for you, and if not, help me figure out what _will_ generate the errors?

**Comment by ben-albrecht** [comment]
Looping @omar-3 into the issue since he claimed to have reproduced the error as well.

**Comment by Aniket21mathur** [comment]
> @Aniket21mathur - here was my attempt to reproduce:

@ben-albrecht this seems to work fine for me as well, also I have tried both cases `mason new` as well as `mason init`, both seem to work fine. Still in that particular project, I am facing this error. Is there anything we can do to reverse mason init, like removing .git for git?

**Comment by omar-3** [comment]
Here is what I have.

```tree``` output for the package:
```
.
├── Mason.lock
├── Mason.toml
├── README.md
├── src
│   └── functional.chpl
├── target
│   ├── debug
│   ├── example
│   └── test
└── test
    └── functionalTest.chpl
```
---
the content of ```Mason.toml```
```
[brick]
name = "functional"
version = "0.1.0"
chplVersion = "1.23.0"
```
---
the content of ```functionalTest.chpl``` is as minimal as it could get
```
Use UnitTest;
Use functional;

proc myTest(test: borrowed Test) throws {
    var result = 1;
    var expectedResult = 1;
    test.assertTrue(result == expectedResult);
}

UnitTest.main();
```
---
the error
```Updating mason-registry
/home/omar/functional/test/functionalTest.chpl:1: syntax error: near 'UnitTest'
compilation failed for functionalTest.chpl
uncaught FileNotFoundError: No such file or directory (encountered when launching subprocess)
  ./MasonTest.chpl:514: thrown here
  ./MasonTest.chpl:235: uncaught here
```

**Comment by ankingcodes** [comment]
>  Is there anything we can do to reverse mason init, like removing .git for git?

@Aniket21mathur  Reversing mason init would mean deleting `.git`, `src/packageName.chpl` , `Mason.toml` file.

**Comment by ben-albrecht** [comment]
@omar-3 - you are getting this error because there is a syntax error in your test:

```
/home/omar/functional/test/functionalTest.chpl:1: syntax error: near 'UnitTest'
```

```chpl
Use UnitTest;
Use functional;
```

should be:

```chpl
use UnitTest;
use functional;
```

Normally, I would suggest filing an issue for this bad error message, but I expect this error message to improve once https://github.com/chapel-lang/chapel/pull/15476/files is merged.

**Comment by ben-albrecht** [comment]
@Aniket21mathur - could you post the contents of `Protobuf.chpl` (maybe in a gist if it's large)?

**Comment by ankingcodes** [comment]
@Aniket21mathur I tried to reproduce the error using the same tree structure provided. Worked fine for me. Maybe adding the contents of `Protobuf.chpl` would help.

**Comment by Aniket21mathur** [comment]
@ben-albrecht @ankingcodes I made a new Mason package and pull the commits in from my GitHub repo, hence having the same code (same Protobuf.chpl content) in both the packages, `mason test` seems to work fine for this package but produces an error for the other.

Though I will also make the code available in a while.

**Comment by ben-albrecht** [comment]
@Aniket21mathur - OK, thanks for the update. Should we close this issue for now, and re-open if you (or someone else) identifies a reproducer?

**Comment by Aniket21mathur** [comment]
Sure, thanks :-)

**Comment by Aniket21mathur** [comment]
@ben-albrecht @ankingcodes one last query does changing the package name afterwards in Mason.toml and src can create issues?

**Comment by ankingcodes** [comment]
The name in Mason.toml should match with that of src/packageName.chpl

**Comment by Aniket21mathur** [comment]
> The name in Mason.toml should match with that of src/packageName.chpl

Yeah, that was taken care of, I was wondering it might affect some internal configurations.

**Comment by Aniket21mathur** [comment]
@ben-albrecht @ankingcodes [src](https://github.com/Aniket21mathur/Chapel-protobuf/blob/master/src/Protobuf.chpl) to the file.

**Comment by cassella** [comment]
@Aniket21mathur That link is to the version that works, right?

Does the directory where it doesn't work have any local changes?  e.g., does `git diff` show uncommitted changes, or does `git diff origin/master` show anything you've committed locally that you haven't pushed to github?

Or a regular `diff -ru` comparing the working and non-working directories?

**Comment by Aniket21mathur** [comment]
> @Aniket21mathur That link is to the version that works, right?

@cassella yes it works.

> Does the directory where it doesn't work have any local changes? e.g., does `git diff` show uncommitted changes, or does `git diff origin/master` show anything you've committed locally that you haven't pushed to github?
> 
> Or a regular `diff -ru` comparing the working and non-working directories?

I have tried that, the two directories seem to be exact copy of each other. I am also confused, why it is happening :-(

Thanks!
