### ISSUE TITLE
Create an alternative `range.isBounded()`

### ISSUE THREAD

**Issue by Aniket21mathur** [chapel-lang/chapel#15528]
The `isBoundedRange()` function follows the `isType(x)` function pattern and returns false if x is not the type being expected. For eg, giving a domain as an `arg` will return `false`. This might be misleading for a regular user. 

A good alternative is to create `range.isBounded()` method, that would only be allowed on range types.

**Comment by Aniket21mathur** [comment]
While working on a fix for this, I came to know that the `isBoundedRange()` function is used for 
`coforall` AST build up. [Code](https://github.com/chapel-lang/chapel/blob/master/compiler/AST/build.cpp#L1240). I need help in replacing this call with a call to the new function `range.isBounded`

**Comment by bradcray** [comment]
Regarding the phrasing of:

> Replace `isBoundedRange()` with `range.isBounded()`

It wasn't my intention that adding a `range.isBounded()` method would cause us to remove the existing `isBoundedRnage()` call which has value as well (in that it can be applied to anything).  I don't see any downside to having both (arguably doing so has less downside than supporting both `range.isBounded()` and `range.boundedType == BoundedRangeType.bounded` given that the two query routines have different behaviors, but the two ways to check if a range is bounded are essentially identical).

> I need help in replacing this call with a call to the new function range.isBounded

If we keep both functions, is there any need to replace it?

**Comment by Aniket21mathur** [comment]
> It wasn't my intention that adding a `range.isBounded()` method would cause us to remove the existing `isBoundedRnage()` call which has value as well

@bradcray thanks for clarifying.

> If we keep both functions, is there any need to replace it?

No, then there is no need to do that

**Comment by Aniket21mathur** [comment]
@bradcray @ben-albrecht that seemed to be a quick fix, I made it in #15569, please review.

Thanks!
