### ISSUE TITLE
Remove mason --list 

### ISSUE THREAD

**Issue by ankingcodes** [chapel-lang/chapel#15550]
When an user types `mason --list`(which is supposed to show a list of installed mason commands), we get an output as follows: 

![1](https://user-images.githubusercontent.com/40923324/79681087-951f7b00-8234-11ea-9bde-1f645f729cd2.PNG)

Two issues in this : 
- `mason init` command which was recently implemented is missing in this list. 
- The tabs or spaces before every command looks rather strange, so we can follow one of the following patterns to display the list : 
    - Remove spaces: 
       ```
        Installed Mason Commands: 
        add
        rm
        new
        update
        ...
        ...
       ```
    - Reduce number of rows : 
      ```
       Installed Mason Commands: 
       add    rm    new    update   build    run    test   external  
       search   env   clean   doc   help   version   system   publish       
      ```

UPDATE: After some discussion below, it has been decided to remove `mason --list` since it doesn't its purpose is fulfilled by `mason --help` and has no additional functionality.

**Comment by ankingcodes** [comment]
Tagging @ben-albrecht here and requesting other developers for insights so that I can work on this. 👍

**Comment by ben-albrecht** [comment]
> mason init command which was recently implemented is missing in this list.

👍 

> Remove spaces:

👍 

> Reduce number of rows

I feel mixed about this one, unless you can align the commands up in a grid so they are easier to read.


At a high-level, I wonder what is the advantage of this flag's output over the help output? I think it only includes`external` if spack is installed - but we could include something like that in the help output too maybe...

@Spartee may have thoughts as well.

**Comment by ankingcodes** [comment]
@ben-albrecht I agree to the fact that `--list` and `mason help` are similar but I believe `--list` is inspired from `cargo --list` which is used to show list of currently installed commands in a non-verbose manner. 

> I feel mixed about this one, unless you can align the commands up in a grid so they are easier to read.

I am more inclined towards using this. The output can be as follows:
```
Installed Mason Commands: 
 add         rm       new      update     build      run           test          external  
 search      env      clean    doc        help       version       system        publish   
```

**Comment by ben-albrecht** [comment]
> I am more inclined towards using this.

I'm OK with that.

>  I agree to the fact that `--list` and `mason help` are similar but I believe `--list` is inspired from `cargo --list` which is used to show list of currently installed commands in a non-verbose manner. 

Our current `--help` output isn't too verbose and there is only 1 command that can be "installed", so it is not _that_ useful today. It's probably fine to leave in today, anticipating more commands in the future, but I just wanted to point out that I think dropping that flag is something on the table for discussion.

**Comment by ankingcodes** [comment]
>  I think dropping that flag is something on the table for discussion.

@ben-albrecht Dropping the flag seems reasonable considering the fact that there are not much commands left to be implemented in the future. Also, it doesn't make sense to have two commands doing the same thing. 
According to me, most users tend to use `--help`  if they want to see available commands. Even I never used `--list` until now.

**Comment by ben-albrecht** [comment]
That sounds good to me. I'd like to give @Spartee a chance to weigh in when he gets a chance before proceeding, in case we're missing anything about the rationale for `--list`.

**Comment by Spartee** [comment]
I vote for dropping the flag, because I assume that most users will simply do a ``mason`` command without arguments to see what commands are available. This makes intuitive sense to me as it is what I do for other PMs e.g. ``pip``, ``npm``

**Comment by ben-albrecht** [comment]
Thanks @Spartee 

@ankingcodes - shall we consider the task for this issue to be removing `--list` flag?

**Comment by ankingcodes** [comment]
Thanks @Spartee and @ben-albrecht ! We shall go ahead with removing the flag then.

**Comment by ankingcodes** [comment]
Also, `mason init` is missing in the `--help` so adding there too is part of the issue
