### ISSUE TITLE
Mason Init Help message

### ISSUE THREAD

**Issue by ankingcodes** [chapel-lang/chapel#15551]
`mason init -h | --help` currently displays the `mason new` help message as follows : 
```
Usage: 
    mason new [options] <project name>

Options:
    -h, --help                   Display this message
        --show                   Increase verbosity
        --no-vcs                 Do not initialize a git repository
    --name <legalName>           Specify package name different from directory name
```
Although #14820 displays the correct help message, I assume this got replaced during follow up PRs.

**Comment by ankingcodes** [comment]
Awaiting confirmation on this from @ben-albrecht (whether this was done on purpose ?) before I fix this. 👍

**Comment by ben-albrecht** [comment]
Not intentional. Not sure how that happened..

Don't we have a test for the help output somewhere?

**Comment by ankingcodes** [comment]
@ben-albrecht Turns out `mason init -h` has not been included in test `masonHelpScope.chpl`, so adding it there will be part of this issue.
