### ISSUE TITLE
internal error for record field typed from enclosing function's generic formal param

### ISSUE THREAD

**Issue by gbtitus** [chapel-lang/chapel#15562]
### Summary of Problem

An internal error is reported on a field declaration in a record type definition, where the field's type is that of a generic formal parameter for the enclosing function.

### Steps to Reproduce

**Source Code:**

```chapel
proc foo(args) {
  record R {
    var x: args.type;
  }
}
```

**Compile command:**

Result of trying to compile the above:
```
gbtmp/tcw3.chpl:1: In function 'foo':
gbtmp/tcw3.chpl:3: internal error: AST-PRI-IVE-0234 chpl version 1.23.0 pre-release (3ce9d14a6a)

Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug --
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.
```

**Comment by jabraham17** [comment]
This is no longer an internal error, instead a user facing error is given

```
error: could not determine the concrete type for the generic return type '<any type>'
```

https://github.com/chapel-lang/chapel/pull/25476 will lock in a test for this

**Comment by jabraham17** [comment]
After discussion in #25476, I have opened https://github.com/chapel-lang/chapel/issues/25485 to capture some design discussion based on the code in this issue
