### ISSUE TITLE
chpldoc smushes the atomic qualifier into the type

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#15579]
### Summary of Problem
chpldoc loses the space between "atomic" and the remainder of the type when printing it out.  So instead of `atomic int(64)`, it looks like `atomicint(64)`.  You can see an example of this in [the atomics documentation](https://chapel-lang.org/docs/master/modules/packages/AtomicObjects.html?highlight=atomicvar#AtomicObjects.AtomicObject.atomicVar)

### Steps to Reproduce

**Source Code:**

```chapel
var x: atomic int;
```

**Compile command:**
`chpldoc foo.chpl`

**Associated Future Test(s):**
[`test/chpldoc/globals/atomics.doc.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/chpldoc/globals/atomics.doc.chpl) #15580

### Configuration Information

- Output of `chpl --version`: chapel 1.23.0 (pre-release)

**Comment by lydia-duncan** [comment]
I think this will be really easy to fix, just need to find where "atomic" is getting printed out and add a space.

**Comment by bradcray** [comment]
In this one, the link to the future works, but the PR number is wrong.

**Comment by lydia-duncan** [comment]
Thanks for pointing that out, forgot to update after creating the PR

**Comment by immadisairaj** [comment]
As this is a one line fix. I'll be sending a PR.
