### ISSUE TITLE
chpldoc prints iteration variable for forall expressions

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#15578]
### Summary of Problem
When documenting a variable created using a forall expression, chpldoc will also output the variable used in the forall expression, even though it is local to the expression and thus not something that can be referenced by those that `use` or `import` the module.

I think it would be appropriate for variables like this to be marked as "no doc" automatically by the compiler, but would like some insight from those that are more familiar with forall expressions.

### Steps to Reproduce

**Source Code:**

```chapel
/* This is an array created using the forall loop initialization */
var x = [i in 1..10] i;
```

**Compile command:**
`chpldoc foo.chpl`

**Associated Future Test(s):**
[`test/chpldoc/globals/arrayLiteral.doc.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/chpldoc/globals/arrayLiteral.doc.chpl) originally added in #6401, text updated in #15580

### Configuration Information

- Output of `chpl --version`: chapel 1.23.0 (pre-release)

**Comment by bradcray** [comment]
I suspect you're right, and was hoping to see what the bad output currently looks like to verify, but the issue doesn't say and the links to the future test and PR don't work.

**Comment by lydia-duncan** [comment]
Sorry about that, also forgot to update this guy.  It should be right now

**Comment by bradcray** [comment]
I agree that `i` should not get its own chpldoc entry.

**Comment by lydia-duncan** [comment]
They wouldn't be considered "compiler-generated", right, since technically the user has explicitly written them into existence?

**Comment by bradcray** [comment]
Right.
