### ISSUE TITLE
Extend `import` to support multiple comma-separated expressions

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#15583]
Related to issue #14971 

As a Chapel programmer, anytime I have to write:

```chapel
import expr1;
import expr2;
import expr3;
```

I find myself wanting to write it as:

```chapel
import expr1, expr2, expr3;
```

or:

```chapel
import expr1,
       expr2,
       expr3;
```

similar to what is supported by so many other Chapel statement forms (`use`, `var`, `delete`, ...).  One motivating example is to import from multiple modules within a single statement as in #14971, but another is when I want to import both a module and a symbol from within that module (e.g., `import M, M.x;`).

As a Chapel developer, it seems like this should be syntactically unambiguous and easy to implement.  As a reader of Chapel code, it seems fairly clear what is intended.

**Comment by bradcray** [comment]
@lydia-duncan: I think this can be closed now, right?

**Comment by lydia-duncan** [comment]
Yup!  I closed the other one but missed this guy.  Thanks!
