### ISSUE TITLE
Problem with re-exporting functions that share a name from two mods

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#15605]
### Summary of Problem
We could re-export multiple functions, and multiple functions with the same name
from the same module, but we currently experience an issue resolving functions when
two re-exported modules both provide overloads of the same function name.

The error given is:
```
multipleDef2Proc.chpl:18: In function 'main':
multipleDef2Proc.chpl:19: error: Symbol 'foo' undeclared in module 'C'
```

### Steps to Reproduce

**Source Code:**

```chapel
module A {
  proc foo(x: int, y: int) {
    writeln("A.foo", x, y);
  }
}
module B {
  proc foo(x: int) {
    writeln("B.foo ", x);
  }
}
module C {
  public import A.foo;
  public import B.foo;
}
module D {
  import C;

  proc main() {
    C.foo(10);
  }
}
```

**Compile command:**
`chpl multiDef2Proc.chpl`

**Associated Future Test(s):**
[`test/visibility/import/edgeCases/multipleDef2Proc.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/visibility/import/edgeCases/multipleDef2Proc.chpl) #15316 

### Configuration Information

- Output of `chpl --version`: 1.23.0 (pre-release)

**Comment by lydia-duncan** [comment]
The first issue is that `lookupPublicUnqualAccessSyms` does not return a value if all the symbols that matched were functions.  Second, even if we return an arbitrary function (with the expectation that function resolution will handle the rest), the module argument inserted into the parent call will always be the module with the last symbol we found that matched.  I believe this means we need to return to always passing the original module name as the module argument and adjust function resolution's response if the module provided does not immediately provide the symbol we are looking for.

**Comment by bradcray** [comment]
At a high level, this sounds like another scenario where some sort of concrete representation of "set of visible function overloads" in the IR would be beneficial?

**Comment by lydia-duncan** [comment]
I'm not sure, it'd probably depend on how we created it.  The trouble with this particular situation is that it's got a module prefix for the call (e.g. `C.foo` instead of `foo`).  So really it should only care about things defined in C, but because of re-exporting, we need a way to look beyond just that scope.

Looking at visible functions, when a module name is provided, we just grab the visibleFunctions map entry for the module's scope, so maybe the visible functions map needs to also follow public import statements.  However, we create the visible functions map by traversing all FnSymbols, meaning we're only looking at the scope in which the function is defined, not at the scopes that access that scope in any way.

**Comment by lydia-duncan** [comment]
I'm thinking I'll create a cache of FnSymbols that are available to a scope because of public import statements, and only populate it when we run into a case that needs it.

**Comment by lydia-duncan** [comment]
I think this will need to be separate from the visible functions map, or at least returned in a separate strategy from the way it normally gets symbols, since we also use it in situations where we explicitly follow use and import statements
