### ISSUE TITLE
Leak while creating an array of arrays using a for expression

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#15609]
Creating an array of arrays with a for expression that doesn't actually have
items leak:

```chapel
var AAA = for i in 1..0 do [1,2,3];  // this leaks a DefaultRectangularDom
writeln(AAA);

var BBB: [1..0][1..3] int;   // no leaks from BBB
BBB = for i in 1..0 do [1,2,3];
writeln(BBB);

var CCC = for i in 1..1 do [1,2,3];  // no leaks from CCC
writeln(CCC);

var DDD = for i in 1..0 do {1..10};  // no leaks from DDD
writeln(DDD);
```
I didn't see anything obvious in what I think was relevant code in ChapelArray
or DefaultRectangular, but didn't dig too deep.

Currently this is the cause of the leak in
```
arrays/ferguson/from/iterator/for-yields-no-arrays.chpl
arrays/shapes/skyline.when-empty.chpl
```

**Comment by bradcray** [comment]
It's not obvious that this is related, but in the recently-filed https://github.com/chapel-lang/chapel/issues/15588, I found that for loop initializers had some other odd behaviors which weren't shared by slight variations on the form.  The net result leaves me thinking that for-loop expressions may have some oddities that need to be addressed.
