### ISSUE TITLE
Reductions over for expressions that yield associative domains leak

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#15612]
(but maybe such idioms shouldn't be allowed?)

```chapel
var D: domain(int);

proc makeD(x:int) {
  var ret:domain(int);
  ret += x;
  return ret;
}

// this leaks
D = + reduce [i in 1..10] makeD(i);
writeln(D);

// this fails to compile with a clear error message
/*

   var assocDoms = [i in 1..10] makeD(i);
   D = + reduce assocDoms;

*/

// this doesn't leak
D = makeD(1)+makeD(2);
```

A supposedly similar code doesn't compile stating that this is not permitted.
So, maybe such reductions should be prohibited, too. Today we are allowing it
but leaking a `_ic_these_range_int64_t_bounded_F0`.

This is the cause of leaks in:
```
associative/ferguson/plus-reduce-assoc.chpl
associative/bharshbarg/domains/reduceArrOfAssocDom.chpl
```

**Comment by e-kayrakli** [comment]
I think the title of the issue should change but I am not sure how yet. The following snippet has no associative stuff in it but still has a similar behavior.

```chapel
var A : [1..5][1..3] real;
var B : [1..3] real;

// leaks
B = + reduce [i in 1..5] A(i);
writeln(B);

// doesn't compile
/*

var tmpArr = [i in 1..5] A(i);
B = + reduce tmpArr;

*/
```
This is the cause of leak in
```
trivial/sidelnik/reduction.chpl
```

**Comment by bradcray** [comment]
So basically, the message I'm getting is: if we eliminate for expressions from the language, we'll be leak-free (while also eliminating some bugs).  :D

**Comment by e-kayrakli** [comment]
OTOH they make finding the scapegoat for a memory bug pretty easy :)

**Comment by bradcray** [comment]
True!  Nicer to have one remaining cause of leaks than 25!

**Comment by e-kayrakli** [comment]
https://github.com/chapel-lang/chapel/pull/16518 fixed this.
