### ISSUE TITLE
Class allocations leak if they are not captured in a variable

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#15613]
```chapel
class FuncLevel {}
class ModuleLevel {}

new ModuleLevel();
proc main() {
  new FuncLevel();
}
```

Leaks both allocations. Being explicit about memory management type does not
help.

This is the cause of leaks in
```
classes/initializers/postInit/class-nongeneric.chpl
classes/initializers/postInit/class-generic.chpl
```

**Comment by cassella** [comment]
This looks like a dup of (or significant overlap with) #11101.

**Comment by e-kayrakli** [comment]
Thanks @cassella! I didn't look for reports before opening and I'd agree that they are duplicate. For now I'll keep it open and keep #11101 in mind until someone takes a closer look at this and decides to close this.

**Comment by bradcray** [comment]
I thought I remembered seeing this before, but @cassella  beat me to it.  :)
