### ISSUE TITLE
mason external --setup: Use spack master branch as registry

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#15616]
Mason currently pins the spack version to be installed when doing `mason external --setup`. This is important, because we want to pin the version of spack that has been tested and is known to work with mason. However, spack bundles the packages into the main repository as well. This means a mason-installed spack does not get the latest versions of packages.

I believe we should do the following:

- Clone the master branch of spack when setting it up through `mason external --setup`, but only use it as a [package repository](https://spack.readthedocs.io/en/latest/repositories.html)
- Add a command to update the spack registry, which will do a `git pull` from the package repository
  - e.g. `mason external --update`
- Download a pinned release tarball (instead of a git clone) for the spack command line tool to be used by Mason, to ensure API compatibility
  - This version should be updated semi-regularly, at least once a release (we have not been good about doing this so far)
  - Using a tarball should be faster than a clone

**Comment by ankingcodes** [comment]
@ben-albrecht I would like to suggest another option for this. We could do a "`shallow clone`" of the spack repository. A shallow clone of `spack` took 23 seconds on my pc. Also, I believe this would allow us to get the latest version (develop branch) of spack too. 

Read more about shallow clone [here](https://www.perforce.com/blog/vcs/git-beyond-basics-using-shallow-clones)

**Comment by ankingcodes** [comment]
The following was the result of running shallow clone on the test written at #15516 
```
[Elapsed execution time for "mason/mason-external/masonExternalRanges/mason-external-range (compopts: 1)" - 22.948 seconds]
```

**Comment by ben-albrecht** [comment]
@ankingcodes - Thanks for your input - that's a great idea. IIRC, shallow clone was considered in the past but ultimately put off as future work (I can't seem to find an issue with the discussion right now). I agree we should utilize a shallow clone for the spack repository.

Regarding the actual spack tool, how does a shallow clone compare to downloading/unpacking the release tarball? And do you know if we can do a shallow clone of a specific release tag?

**Comment by ankingcodes** [comment]
> Regarding the actual spack tool, how does a shallow clone compare to downloading/unpacking the release tarball?

@ben-albrecht  It's 24 seconds. Not much of a difference with shallow clone though. 

> And do you know if we can do a shallow clone of a specific release tag?

Yes, for spack v0.14.2 , we can do 
``` 
git clone --branch v0.14.2 --depth 1 https://github.com/spack/spack
```

**Comment by ben-albrecht** [comment]
Excellent, so we could use the following for our spack tool / repository:

```sh
# Install pinned version of spack for command line tool
git clone --branch v0.14.2 --depth 1 https://github.com/spack/spack $MASON_HOME/spack
# Clone spack master repository for latest packages
git clone --depth 1 https://github.com/spack/spack $MASON_HOME/spack-registry
```

**Comment by ankingcodes** [comment]
> git clone --branch v0.14.2 --depth 1 https://github.com/spack/spack $MASON_HOME/spack

small bug with this, we get a detached head after cloning. So we need to add a `-b` tag in there.

**Comment by ben-albrecht** [comment]
> small bug with this, we get a detached head after cloning.

I don't expect this to be too big of an issue. We will just need to make sure future updates can gracefully update the checkout with a detached head.
