### ISSUE TITLE
Certain imports in default-used modules produces compiler error

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#15639]
### Summary of Problem

Importing an identifier of certain modules from within certain standard/package modules produces a compiler error when compiling a program that _doesn't_ use the standard/package module.

It seems like this happens only when the standard/package module is used by default (such as `Random` or `Sort`), and only happens with certain imports e.g. `Set.set`, but not `List.list`.

I expect these imports to compile and run successfully, since they work in user programs as well.

We stumbled over this in #15154

### Steps to Reproduce

Add this to `Random.chpl`:

```chapel
import Set.set;
```

A program that does not `use Random` fails, such as the `make check` program:

```sh
> make check
$CHPL_HOME/modules/standard/Random.chpl:69: error: Cannot find symbol 'Set'
```

A program that does `use Random` succeeds:

```chpl
// foo.chpl
use Random;
writeln('success');
```

```sh
> chpl foo.chpl
> ./foo
success
```

### Other data points

These imports produce the error:

- `import Set.set;`
- `import Map.map;`

These imports do not produce the error:

- `import Set;`
- `import Map;`
- `use Set;`
- `use Map;`
- `import List.list;`

Adding the import to these modules produces the error:

  - `Random.chpl`
  - `Sort.chpl`

Adding the import to these modules does not:
  - `ZMQ.chpl`

### Configuration Information

- Output of `chpl --version`: chpl version 1.23.0 pre-release (15a0368beb)

**Comment by bradcray** [comment]
Just to make sure I'm on the same page as you:  It seems like this should cause an error in all cases, not just for programs that don't use `Random` (say).  Is that your sense as well?

**Comment by ben-albrecht** [comment]
>  It seems like this should cause an error in all cases, not just for programs that don't use Random (say). Is that your sense as well?

Sorry to not clarify (will update description) -- I think this _should_ work in all cases, since `import Set.set;` works fine in a user program.

**Comment by bradcray** [comment]
Maybe a question for @lydia-duncan: Is the rationale that although there's nothing in the code that introduces the symbol `Set`, we can find a module named `Set` by searching the standard module path?

**Comment by lydia-duncan** [comment]
Oh snap.  I think this is another instance of that bug we found with accessing nested standard modules in default programs

**Comment by lydia-duncan** [comment]
Brad, note that `import Set;` works just fine in the same context.

**Comment by lydia-duncan** [comment]
#15347 is the other issue I was thinking of

**Comment by bradcray** [comment]
> Brad, note that import Set; works just fine in the same context.

I couldn't remember whether I have to type `import Set;` to make the compiler aware that there is a module named `Set` before I `import Set.set;` or whether I could jump straight to `import Set.set;` and landed on the former when seeing that different cases were doing different things.  I defer to the expert, I'm still getting used to `import`.

**Comment by lydia-duncan** [comment]
You asking that question is the reason I made the connection between these two issues :)
