### ISSUE TITLE
Random.RandomStream cannot access module-level function when imported

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#15640]
# Summary of Problem

Calling a method on `Random.RandomStream` that calls a module-defined function produces an unresolved call error, when `Random` is imported instead of used. I would expect the imported version to compile and run as the `use` version does.

This almost certainly extends beyond just the Random module, but I was not able to identify a more general reproducer. It might be an issue specific to default-used modules such as Random and Sort. I can update the issue title as we learn more.

### Steps to Reproduce

**Source Code:**

```chpl
// use Random; works fine
import Random;

var arr: [1..6] int = 1..6;
var rs = Random.createRandomStream(int);

var result = rs.choice(arr, size=3, replace=false); // this calls Random._choice()
writeln(result);
```

```sh
> chpl import-random.chpl
// $CHPL_HOME/modules/standard/Random.chpl:988: In function 'choice':
// $CHPL_HOME/modules/standard/Random.chpl:991: error: unresolved call '_choice(borrowed PCGRandomStream(int(64),true), [domain(1,int(64),false)] int(64), size=int(64), replace=bool, prob=nothing)'
// $CHPL_HOME/modules/standard/Random.chpl:991: note: because no functions named _choice found in scope
// import-random.chpl:10: Function 'choice' instantiated as: choice(this: borrowed PCGRandomStream(int(64),true), arr: [domain(1,int(64),false)] int(64), size: int(64), prob: nothing)
```

This doesn't seem to impact user-defined modules, based on my attempt at a general reproducer:

```chapel
// This program compiles and runs fine
module Main {
  proc main() {
    import Foo;

    var f = new Foo.R(10);

    f.print();
  }
}

module Foo {
  record R {
    var x: int;

    proc print() {
      _print(x);
    }

  }

  proc _print(x) {
    writeln(x);
  }
}
```

### Configuration Information

- Output of `chpl --version`: chpl version 1.23.0 pre-release (15a0368beb)

**Comment by lydia-duncan** [comment]
This is due to #15312.  PCGRandom doesn't have a use of the parent module Random, which is where _choice is defined.  Adding a use allows the snippet to compile.  I think this means we didn't have a test involving choice before and I'm concerned we have other cases like this lurking in our code

**Comment by lydia-duncan** [comment]
The reason the use allowed us to find _choice was because of the point of instantiation - the point of instantiation for the method was in the user code and the user code had a use of Random so we could go inside it.  When the user code only had an import, we weren't able to go into Random directly - if the reference of _choice had been qualified, we would still have been fine but otherwise we weren't allowed to see into that scope from the point of instantiation either.

**Comment by lydia-duncan** [comment]
I've opened Cray/chapel-private#1119 to go through our other submodules and look for where they need a use/import of their parent module

**Comment by lydia-duncan** [comment]
Wow, okay, looks like I closed this without adding the use to *Random*, woof.

**Comment by lydia-duncan** [comment]
No, never mind.  Don't trust my emails over the history.  I am tired this morning
