### ISSUE TITLE
Compile failures with GCC-10.1

### ISSUE THREAD

**Issue by PHHargrove** [chapel-lang/chapel#15657]
GCC-10.1 (first release in the 10.x series) was released on May 7 and our nightly tests of GASNet-EX have begun using that new release.  When attempting to build Chapel master (at b28a36a0a) we are experiencing errors (warnings promoted by `-Werror`, to be more precise).  This is with `CHPL_COMM_DEBUG=1`, but I don't know if that is a requirement to reproduce the problem.  

I believe the necessary information is all in the transcript below.  Let me know if any other info is needed.

```

  Currently selected Chapel configuration:

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: unknown
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: ibv *
  CHPL_GASNET_SEGMENT: large
CHPL_TASKS: qthreads
CHPL_LAUNCHER: gasnetrun_ibv
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: none
CHPL_HWLOC: hwloc
CHPL_REGEXP: none
CHPL_LLVM: none
CHPL_AUX_FILESYS: none

  Selected installation options:

install to CHPL_HOME: /home/data2/upcnightly/dirac/EX-dirac-ibv-gcc_everything/work/dbg/chapel

  To change the selected Chapel configuration, set environment variables.
  See doc/rst/usingchapel/chplenv.rst
  To change installation options, see ./configure --help

  If the configuration above is appropriate, build Chapel with:

make

  and possibly install it with

make install

  Once Chapel is in your PATH, you can verify basic functionality with:

make check

$ env CHPL_COMM_DEBUG=1  make -j4 CHPL_GASNET_MORE_CFG_OPTIONS=" --with-mpirun-cmd=\"mpirun -np %N -map-by node %C\"  --with-ibv-physmem-max=2/3 --with-ibv-spawner=ssh --enable-debug" all
make[1]: Entering directory '/scratch/upcnightly/EX-dirac-ibv-gcc_everything/runtime/bld/dbg/chapel'
Making the compiler...
mkdir -p ../build/compiler/linux64/gnu/x86_64/llvm-none
echo > /scratch/upcnightly/EX-dirac-ibv-gcc_everything/runtime/bld/dbg/chapel/configured-prefix
Copying ./../build/compiler/linux64/gnu/x86_64/llvm-none/CONFIGURED_PREFIX.incoming to ./../build/compiler/linux64/gnu/x86_64/llvm-none/CONFIGURED_PREFIX
Making LLVM...
rm -rf /scratch/upcnightly/EX-dirac-ibv-gcc_everything/runtime/bld/dbg/chapel/third-party/llvm/install/none
cd llvm && /usr/local/pkg/gmake/newest/bin/make
make[5]: Nothing to be done for 'default'.
Copying ./../build/compiler/linux64/gnu/x86_64/llvm-none/CLANG_SETTINGS.incoming to ./../build/compiler/linux64/gnu/x86_64/llvm-none/CLANG_SETTINGS
***** adt/ *****
making ../../build/compiler/linux64/gnu/x86_64/llvm-none/adt subdirectory to store platform-specific files
g++ -c  -MMD -MP -g  -Wall -Werror -Wpointer-arith -Wwrite-strings -Wno-strict-aliasing -Wno-comment -Wmissing-declarations -I. -I../include/linux64 -I../include  -I../../build/compiler/linux64/gnu/x86_64/llvm-none -I../../runtime/include/encoding -I/scratch/upcnightly/EX-dirac-ibv-gcc_everything/runtime/bld/dbg/chapel/third-party/utf8-decoder   -DCOMPILER_SUBDIR=adt -o ../../build/compiler/linux64/gnu/x86_64/llvm-none/adt/bitVec.o bitVec.cpp
g++ -c  -MMD -MP -g  -Wall -Werror -Wpointer-arith -Wwrite-strings -Wno-strict-aliasing -Wno-comment -Wmissing-declarations -I. -I../include/linux64 -I../include  -I../../build/compiler/linux64/gnu/x86_64/llvm-none -I../../runtime/include/encoding -I/scratch/upcnightly/EX-dirac-ibv-gcc_everything/runtime/bld/dbg/chapel/third-party/utf8-decoder   -DCOMPILER_SUBDIR=adt -o ../../build/compiler/linux64/gnu/x86_64/llvm-none/adt/map.o map.cpp
g++ -c  -MMD -MP -g  -Wall -Werror -Wpointer-arith -Wwrite-strings -Wno-strict-aliasing -Wno-comment -Wmissing-declarations -I. -I../include/linux64 -I../include  -I../../build/compiler/linux64/gnu/x86_64/llvm-none -I../../runtime/include/encoding -I/scratch/upcnightly/EX-dirac-ibv-gcc_everything/runtime/bld/dbg/chapel/third-party/utf8-decoder   -DCOMPILER_SUBDIR=adt -o ../../build/compiler/linux64/gnu/x86_64/llvm-none/adt/vec.o vec.cpp
In file included from ../include/map.h:57,
                 from ../include/baseAST.h:41,
                 from ../include/misc.h:27,
                 from vec.cpp:53:
../include/vec.h: In instantiation of 'void Vec::copy(const Vec&) [with C = MapElem >; int S = 4]':
../include/vec.h:195:3:   required from 'Vec::Vec(const Vec&) [with C = MapElem >; int S = 4]'
../include/vec.h:256:14:   required from 'C* Vec::set_add(C) [with C = MapElem >; int S = 4]'
../include/map.h:242:25:   required from 'MapElem* Map::put(K, C) [with K = unsigned int; C = List]'
../include/map.h:383:42:   required from 'C ChainHash::put(C) [with C = char*; AHashFns = StringHashFns]'
../include/map.h:555:19:   required from here
../include/vec.h:336:11: error: 'void* memcpy(void*, const void*, size_t)' writing to an object of non-trivially copyable type 'class MapElem >'; use copy-assignment or copy-initialization instead [-Werror=class-memaccess]
  336 |     memcpy(e, &vv.e[0], sizeof(e));
      |     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../include/baseAST.h:41,
                 from ../include/misc.h:27,
                 from vec.cpp:53:
../include/map.h:73:35: note: 'class MapElem >' declared here
   73 | template  class MapElem {
      |                                   ^~~~~~~
In file included from ../include/map.h:57,
                 from ../include/baseAST.h:41,
                 from ../include/misc.h:27,
                 from vec.cpp:53:
../include/vec.h: In instantiation of 'void Vec::move_internal(Vec&) [with C = MapElem >; int S = 4]':
../include/vec.h:435:6:   required from 'C* Vec::set_add_internal(C) [with C = MapElem >; int S = 4]'
../include/vec.h:259:7:   required from 'C* Vec::set_add(C) [with C = MapElem >; int S = 4]'
../include/map.h:242:25:   required from 'MapElem* Map::put(K, C) [with K = unsigned int; C = List]'
../include/map.h:383:42:   required from 'C ChainHash::put(C) [with C = char*; AHashFns = StringHashFns]'
../include/map.h:555:19:   required from here
../include/vec.h:319:11: error: 'void* memcpy(void*, const void*, size_t)' writing to an object of non-trivially copyable type 'class MapElem >'; use copy-assignment or copy-initialization instead [-Werror=class-memaccess]
  319 |     memcpy(e, &vv.e[0], sizeof(e));
      |     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../include/baseAST.h:41,
                 from ../include/misc.h:27,
                 from vec.cpp:53:
../include/map.h:73:35: note: 'class MapElem >' declared here
   73 | template  class MapElem {
      |                                   ^~~~~~~
cc1plus: all warnings being treated as errors
make[4]: *** [../make/Makefile.compiler.foot:55: ../../build/compiler/linux64/gnu/x86_64/llvm-none/adt/vec.o] Error 1
make[3]: *** [make/Makefile.compiler.foot:29: adt.makedir] Error 2
make[2]: *** [Makefile:77: compiler] Error 2
make[1]: *** [Makefile:61: comprt] Error 2
make[1]: Leaving directory '/scratch/upcnightly/EX-dirac-ibv-gcc_everything/runtime/bld/dbg/chapel'
```

**Comment by bradcray** [comment]
Thanks for reporting this Paul!  As you can probably tell, we haven't done anything to start doing testing against gcc 10.x yet.  If this is a hassle for you in your test jig, I believe that you should be able to build Chapel with those warnings disabled using `make WARNINGS=0 ...`.

**Comment by PHHargrove** [comment]
@bradcray I've finally gotten around the adding `WARNINGS=0` to the `make` invocation and that resolves the initial problem.  However, it unfortunately just exposes the next problem.

I suspect you are not actively chasing GCC 10 yet, but when you do you are going to hit numerous multiply-defined symbols when linking applications.  This is because the GCC maintainers have lost their minds and abandoned the long tradition that the tentative definition `int i;` is a "common block" definition.  See "Default to -fno-common" near the start of https://gcc.gnu.org/gcc-10/porting_to.html
The solution is either `-fcommon` to restore the historically behavior, or eliminating tentative definitions where they are not required.  FWIW, we did the latter for GASNet, which was more work but leaves both options available to our clients like Chapel.

**Comment by bradcray** [comment]
Thanks for the notes, Paul.  You're correct that we haven't been able to turn our attention to gcc 10 yet, but these will undoubtedly be very helpful when we do.  I'm sorry to hear that the WARNINGS=0 approach wasn't sufficient (for both of our sakes).  Let us know if this is a blocking issue for you guys (or sufficiently annoying that we should treat it as one).

**Comment by bradcray** [comment]
@PHHargrove: From https://gcc.gnu.org/gcc-10/porting_to.html, I was thinking that I could start to work through these issues without installing a new version of gcc by compiling with gcc 9.x and `-fno-common`, but this doesn't seem to be resulting in the kinds of errors you reported above.  Thought I'd check with you before heading out for the day to see if you already grokked why this would be (i.e., have I misunderstood something, or does `-fno-common` behave that differently between gcc 9.x and gcc 10.x?).  Thanks.

**Comment by PHHargrove** [comment]
@bradcray I agree that gcc 9.x and `-fno-common` should have reproduced the errors.  I cannot account for why that is not sufficient.

For the time being, we continue to test Chapel with GASNet with Clang (LLVM and Apple) and Intel compilers, but have temporarily suspended testing w/ GNU compilers due to this issue.

**Comment by gbtitus** [comment]
While somewhat painful this is also really kind of amusing to me, because I first encountered this issue after SGI bought CRI in 1996 and we discovered that the SGI compilers we had to start using disagreed with the Sun compilers we had been using before about precisely this question of whether a C variable declaration at file scope without a storage-class specifier should be treated as `common` during linking.  No problem remains solved for long, apparently.

**Comment by PHHargrove** [comment]
@ronawho I will test #15763 as soon as I am able, ideally today.  
Would you prefer that I report the result in this issue or in that pull request?

**Comment by ronawho** [comment]
I'd keep it in this issue, but I don't have a strong preference. 

I'm pretty confident that PR will fix the issues you ran into, so if it's easier for you I can merge and we can handle any fallout if there's more cases to fix.

**Comment by PHHargrove** [comment]
Testing from the unmerged PR branch has begun...

**Comment by PHHargrove** [comment]
Tests have passed, but I realized too late that I still had `WARNINGS=0`
IOW: only on of the two commits in #15763 has been proven to resolve its target problem.  
I will requeue my tests w/o `WARNINGS=0` and report again later

**Comment by bradcray** [comment]
Ah, I think I see what I was doing wrong yesterday.  Since the original errors were in the compiler build, I was under the impression that I'd see errors when building the compiler after enabling to `-fno-common`, but after browsing Elliot's PR (and re-reading Paul's follow-up comments), I now understand that those errors only showed up after building the runtime and trying to compile a Chapel program.  And the link-time issues did show up with older versions of gcc as well.  That'll teach me to read a bit more carefully next time.

**Comment by PHHargrove** [comment]
@bradcray yes, that sounds consistent since the bcc-vs-common choice was made by the compiler when building the runtime lib(s), not when the app was compiled or linked.

**Comment by PHHargrove** [comment]
On a tangentially-related topic, ubuntu is pretty good about packaging GCC  snapshots well in advance of a major-numbered GCC release.  For instance, Ubuntu 20.04 has gcc-10 packages available in the default config (not required to enable a non-default package repository).

**Comment by PHHargrove** [comment]
Retesting w/o `WARNINGS=0` also PASSES.
I can now provide my un-qualified :+1: for  #15763

**Comment by ronawho** [comment]
Merged, thanks for reporting and testing.
