### ISSUE TITLE
Creating tuples of nothing type causes INTERNAL ERROR during compilation, in chpl version 1.22.0.

### ISSUE THREAD

**Issue by rchinmay** [chapel-lang/chapel#15650]
#### Summary of the Problem:
Since nothing is a valid data-type in chapel language, I tried to create a tuple of size 2, both elements of nothing type. When I tried printing the tuple using writeln, I got a compilation error.
While compiling it gives the following error: 

internal error: UTI-MIS-0691 chpl version 1.22.0

Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug --
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.

Just creating a tuple of nothing type elements(by commenting out the writeln() line) compiles and runs correctly. But passing the tuple containing nothing type causes an Error. 
I was expecting either to print the tuple like an empty tuple, or a compilation error which clearly says where nothing type variables could be used and where they cannot be. But, it gives an internal error, and so I think this is a bug. 

#### Steps to Reproduce:
The source code is given below:
1. var tuple_of_nothing:2*nothing;
2. writeln(tuple_of_nothing);

I compiled the code using: chpl Chapel_Program.chpl

After compilation the Error message that was shown:
internal error: UTI-MIS-0691 chpl version 1.22.0

Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug --
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.

#### Configuration Information:
Output of chpl --version: chpl version 1.22.0
Copyright 2020 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)

Output of $CHPL_HOME/util/printchplenv --anonymize:
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_LLVM: none
CHPL_AUX_FILESYS: none

Back-end compiler and version, e.g. gcc --version:
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by mppf** [comment]
@rchinmay - thanks very much for filing this issue

**Comment by vasslitvinov** [comment]
The code in the OP compiles successfully now.
#19704 adds a test, which passes.

@rchinmay if you are still observing this failure, please let us know / post here / reopen.

Meanwhile I am closing this issue.
