### ISSUE TITLE
Creating a List of a Chapel class

### ISSUE THREAD

**Issue by ahayashi** [chapel-lang/chapel#15661]
### Summary of Problem

Hello, I'm now trying to create a list of a Chapel class. However, I get a compilation error (see below) when I compile the following program. Would this be a known issue or is the code wrong?

### Steps to Reproduce

**Source Code:**

```chapel
use List;

class myClass {
 var prop1: bool;
}

proc main() {
 var ins1 = new myClass(true);
 var lst1: list(myClass) = ins1;
 writeln(lst1);
}
```

**Compile command:**

```
$ chpl mylist.chpl
mylist.chpl:7: In function 'main':
mylist.chpl:9: error: unresolved call 'list(myClass,false).init=(owned myClass)'
$CHPL_HOME/modules/standard/List.chpl:255: note: this candidate did not match: list.init=(other: list(this.type .eltType, ?p))
mylist.chpl:9: note: because call actual argument #1 with type owned myClass
$CHPL_HOME/modules/standard/List.chpl:255: note: is passed to formal 'other: list'
$CHPL_HOME/modules/standard/List.chpl:271: note: candidates are: list.init=(other: [?d] this.type .eltType)
$CHPL_HOME/modules/standard/List.chpl:293: note:                 list.init=(other: range(this.type .eltType, ?b, ?d))
```

@bradcray  suggested the following workaround and it works:
```chapel
use List;

class myClass {
  var prop1: bool;
}

proc main() {
  var ins1 = new myClass(true);
  var lst1: list(owned myClass);
  lst1.append(ins1);
  writeln(lst1); // [{prop1 = true}]
}
```

**Execution command:**
N/A

**Associated Future Test(s):**

N/A
### Configuration Information

- Output of `chpl --version`:
```
$ chpl --version
chpl version 1.22.0
Copyright 2020 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)
```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_LLVM: none
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
$ gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
- (For Cray systems only) Output of `module list`:
N/A

**Comment by bradcray** [comment]
Tagging @dlongnecke-cray due to his work on List.

**Comment by dlongnecke-cray** [comment]
Hi @ahayashi, the workaround suggested by @bradcray is the correct way to achieve your goal.

We don't have a `list.init=` that accepts a single element. Currently we only support init equals for arrays, ranges, and other lists.

As you've discovered, once you create a list, you can then `.append()` elements to it. This is the way you'll be adding most elements to your lists. If you want to append another collection, you can `.extend()` the list with the elements from the collection, but in general you'll be calling `.append()` most of the time.

**Comment by bradcray** [comment]
@dlongnecke-cray: I wonder if it would be possible/desirable to add an error-oriented overload for `list(t).init=()` that would give a helpful message along these lines (e.g., `lists of type 't' can only be initialized using lists, arrays, or ranges of type `t`...`), just to simplify having to interpret of the current general-purpose error message?

**Comment by dlongnecke-cray** [comment]
It might be possible. Another idea is to add an overload of `init=` that accepts a single element. However, I think the error message that is produced in this case seems to be quite straight forward as far as error messages go (it even lists all three possible initializers).

@ahayashi Can also consult the list primer https://chapel-lang.org/docs/primers/listOps.html for a quick tutorial on list usage.

**Comment by bradcray** [comment]
> Another idea is to add an overload of init= that accepts a single element.

Is there a precedent for doing so?

> It might be possible.

It's definitely possible:

```chapel
    pragma "no doc"
    pragma "last resort"
    proc init=(other) {
      compilerError("lists of type 't' can only be initialized by other lists, arrays, or ranges of type 't'");
      // this wouldn't be necessary if our compiler were better...              
      eltType = int;
    }
```

To me, it's the listing of all three initializers that makes the current error message not-so-straightforward.  It essentially requires anyone accidentally mis-using list to understand copy initializers in Chapel (and that lists are records).

The only downsides of adding a more direct / straightforward error message that I can think of are (a) a potential maintenance burden, if additional copy initializers are added in the future and (b) a slippery slope of always wanting to provide clearer and clearer error messages.  I think (b) is actually desirable, though, based on the error messages that are produced by clang or gcc today vs. gcc a decade ago, say.

**Comment by dlongnecke-cray** [comment]
It's (b) that I'm worried about.

It seems like that sets a precedent for us to special case our standard module containers instead of treating them like standardized versions of something any particular user might build (even if they require some workarounds _today_, they may not in a release cycle or two).

That list is a record isn't too hidden: https://chapel-lang.org/docs/modules/standard/List.html#List.list

As for needing to understand copy initializers, I agree that exposing their existence to a new user via a somewhat verbose error message might be a bit overwhelming. However...

a) New users are probably going to be exposed to the existence of copy initializers in this/a similar fashion regardless of whether or not we "soften the fall" for types like list or map.
b) As you mention, it starts a slippery slope of inserting more and more compiler errors into standard module code. Where do we draw the line between adding additional useful information and covering up deficiencies in compiler error reporting?

I think in this case, we should consider improving the compiler error that is produced to say something along the lines of i.e., _"No initializer equals accepting expression of `type owned C` found for `list(owned C)`"_. This way all init-equals that fail to resolve benefit from improved error reporting. It would make a new user aware that initialization is failing in the same fashion as the compiler error would.

**Comment by bradcray** [comment]
> I think in this case, we should consider improving the compiler error that is produced to say something along the lines of i.e., "No initializer equals accepting expression of type owned C found for list(owned C)". This way all init-equals that fail to resolve benefit from improved error reporting. It would make a new user aware that initialization is failing in the same fashion as the compiler error would.

I'd use a different wording (specifically, avoiding the phrase "initializer equals" as though it were a noun, but I'd definitely be down with this approach.

**Comment by ahayashi** [comment]
@bradcray @dlongnecke-cray Thank you very much for the suggestions. That's very helpful. Yes, it'd be great if you can somehow improve the error message!

**Comment by dlongnecke-cray** [comment]
@ahayashi Closing this as I assume your issue has been resolved.
