### ISSUE TITLE
Language Specification Render Problems

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#15662]
This is an open-ended mega-issue to track render problems that may have been introduced after the language spec was converted to restructured text (RST) (https://github.com/chapel-lang/chapel/pull/14165).

## Known render problems in the spec

- [x] code-block to function format (#15097)
- [x] Abstract intents table has "see" and "notes" text cut off ([link](https://chapel-lang.org/docs/1.23/language/spec/procedures.html#abstract-intents-table))

**Comment by ben-albrecht** [comment]
code-block to function format (#15097)

**Comment by ben-albrecht** [comment]
Abstract intents table has "see" and "notes" text cut off:

https://chapel-lang.org/docs/master/language/spec/procedures.html#abstract-intents-table

**Comment by bradcray** [comment]
Rather than having each individual observed item get noted in a separate comment, how about editing those into a checklist format?

**Comment by Shivansh-khare** [comment]
hello, I am a beginner how can I contribute in this issue.

**Comment by ben-albrecht** [comment]
I believe the 2 issues linked here have been addressed. I'm going to close this issue, but we can re-open and update the list as more render problems are observed.

@Shivansh-khare - separately, I suggest you start here for contributing if you haven't seen it yet: https://chapel-lang.org/contributing.html
