### ISSUE TITLE
List.remove() consecutive match problem

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#15694]
### Summary of Problem

List.remove(), when `count > 0` and there are consecutive items to be
removed, will fail to remove all of them.

```chapel
        for i in 0..#(_size - removed) {
          ref item = _getRef(i);

          if x == item {
            _destroy(item);
            _collapse(i);
            removed += 1;
          }

          if count > 0 && removed >= count then
            break;
        }
        
        _maybeReleaseMem(removed);
        _size = _size - removed;
        result = removed;
```

It removes the first one at idx `i`, then calls `_collapse(i)` to
shift the remaining entries left.  The element that was at index `i+1`
is now at index `i`.  Then the loop proceeds to index `i+1`, never
having examined the element that it shifted into index `i`.

Also, the loop bounds of `0..#(_size - removed)` is evaluated only on
entry to the loop, when `removed == 0`, so it can process the ghost
entries that prior calls to `_collapse()` have `_move()`d left but
remain off the end.

Since `_size` isn't adjusted until after the loop, `_getRef()` will
return those ghost entries once we get to them.  If these were
records, the `_destroy(item)` call would probably cause problems
destroying the ghosts of objects that have already been destroyed,
if the last element of the list were one that matched `x`.

### Steps to Reproduce

**Source Code:**

```chapel
use List;

config const testElem = 42;
config const testIters = 10;

type listType = int;
param listLock = true;

var lst: list(listType, listLock);
var elemCount = 0;

for i in 1..testIters {
  elemCount += 1;
  lst.append(testElem);
}
for i in 1..testIters {
  lst.append(testElem * 2);
}

var removed = lst.remove(testElem, 0);
writeln(removed);
writeln(lst);
```

That puts 10 42's on the list followed by 10 84's.  Then it tries to
remove all the 42's, which should return 10 and leave just the 84's.
But it skips every other 42:

```
fortytwo@magrathea:~/src/chapel $ ./foo -nl 1
5
[42, 42, 42, 42, 42, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84]
```

**Associated Future Test(s):**

None yet

`test/library/standard/List/remove/listRemoveMany.chpl` doesn't hit this,
because it sets up its list with alternating target elements and
non-target elements, so `remove()` never sees consecutive elements to
remove.

### Configuration Information

```
chpl version 1.23.0 pre-release (188e1b3772)

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_LLVM: none
CHPL_AUX_FILESYS: none

gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
```

**Comment by bradcray** [comment]
Attn: @dlongnecke-cray

**Comment by cassella** [comment]
Also, on master there's a valgrind error on 

```chapel
var slist: list(string, listLock);
for w in [ "do", "do", "de", "do" ] do
  slist.append(w);

removed = slist.remove("do", 0);
writeln(removed);
writeln(slist);
```

```
==16586== Thread 2:
==16586== Invalid read of size 1
==16586==    at 0x4C35E6A: bcmp (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==16586==  Address 0x7019430 is 0 bytes inside a block of size 8 free'd
==16586==    at 0x21047C: chpl_je_valgrind_freelike_block (valgrind.c:33)
==16586==  Block was alloc'd at
==16586==    at 0x1D7EBD: chpl_je_malloc (jemalloc.c:1650)
==16586== 
==16586== Invalid read of size 1
==16586==    at 0x4C35E85: bcmp (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==16586==  Address 0x7019431 is 1 bytes inside a block of size 8 free'd
==16586==    at 0x21047C: chpl_je_valgrind_freelike_block (valgrind.c:33)
==16586==  Block was alloc'd at
==16586==    at 0x1D7EBD: chpl_je_malloc (jemalloc.c:1650)
==16586== 
==16586== Invalid free() / delete / delete[] / realloc()
==16586==    at 0x21047C: chpl_je_valgrind_freelike_block (valgrind.c:33)
==16586==  Address 0x7019430 is 0 bytes inside a block of size 8 free'd
==16586==    at 0x21047C: chpl_je_valgrind_freelike_block (valgrind.c:33)
==16586==  Block was alloc'd at
==16586==    at 0x1D7EBD: chpl_je_malloc (jemalloc.c:1650)
==16586== 
3
[do]
```

(And it left one of the "do" and removed the "de", which I wasn't expecting.)

I have a branch in progress that fixes this too.
