### ISSUE TITLE
Confusing behavior overloading `=` for tuples.

### ISSUE THREAD

**Issue by npadmana** [chapel-lang/chapel#15717]
(This is on Chapel 1.21)

Consider the following code --
```chpl
config const x0 = 1;
proc =(ref y : 2*int, x : int)
  {
   for y1 in y do y1 = x;
  }

var t : 2*int = (2,1);
t = x0;
writeln(t);
```
This code compiles and runs just fine. However, the following modification results in a compile time error
```chpl
config const x0 = 1;
proc =(ref y : 2*int, x : int)
  {
   for y1 in y do y1 = x;
  }

var t : 2*int;
t = x0;
writeln(t);
```
Compiling this gives
```
test3.chpl:8: error: illegal lvalue in assignment
```
I believe the issue is because `t` is not properly initialized, since inserting a second `writeln(t)` before `t=x0;` has this working again. However, I'm not sure how to define an initializer `init=` for a tuple, or to force the compiler to use a compiler generated default initialization.

**Comment by cassella** [comment]
It looks like a split-init problem to me -- the compiler doesn't know how to take `t = x0` as initialization.

You can force `t` to be default initialized and thereby later trigger the regular assignment you've defined by writing 

```chapel
var t: 2*int;
t;
t = x0;
```

**Comment by bradcray** [comment]
@mppf: Tagging you on this since split initialization was mentioned.

**Comment by mppf** [comment]
This program compiles and runs on master:

``` chapel
config const x0 = 1;
proc =(ref y : 2*int, x : int)
  {
   for y1 in y do y1 = x;
  }

var t : 2*int;
t = x0;
writeln(t);
```

here `t` is being split-inited, but the compiler doesn't find a compatible `init=` and falls back on default-init / assign. This behavior might change in the future (since we have generally been trying to remove cases of default-init + assign and replace them with copy initialization).

**Comment by npadmana** [comment]
Great -- sorry, I should have checked if this remained an issue on master.

**Comment by mppf** [comment]
Re.

> This behavior might change in the future (since we have generally been trying to remove cases of default-init + assign and replace them with copy initialization).

#15838 brings up the language design options here that we are considering.
