### ISSUE TITLE
Rendering of `List.append()` documentation is off

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#15722]
While looking at the `List.append()` documentation today, I noticed that it's a bit off:  it's all bold and it doesn't contain a hyperlink:

<img width="737" alt="Screen Shot 2020-05-26 at 10 43 00 AM" src="https://user-images.githubusercontent.com/7536222/82932771-c8dd7700-9f3d-11ea-96c6-89acc147e2e2.png">

Looking at the source, I'm noting that the preceding line does not seem to be rendered (and maybe is not an appropriate tag for a procedure?  I can never keep chpldoc straight in my mind and forget where to read about what's legal or not), which may be the cause?

```rst
      :arg other: The range to initialize from.
      :type other: `range(this.type.eltType)`
      

   .. method:: proc ref append(in x: eltType)
```

**Comment by bradcray** [comment]
Tagging @dlongnecke-cray since I believe he wrote the documentation and @ben-albrecht and @lydia-duncan as my go-to chpldoc experts.

**Comment by ben-albrecht** [comment]
@bradcray  I think this is a duplicate of https://github.com/chapel-lang/chapel/issues/13983 -- could you confirm?

**Comment by bradcray** [comment]
Ah, I think you're right.  And now that you've pointed it out, I see now that the `type` tag that I was thinking wasn't being rendered is actually incorporated into the arg tag, so I was off-base there.  Thanks!
