### ISSUE TITLE
Creating arrays of tuples of arrays leads to segfaults

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#15759]
### Summary of Problem

In a program written by @dataPulverizer as part of the https://github.com/dataPulverizer/KernelMatrixBenchmark effort, once I'd worked past issue #15724, I received a seg fault related to trying to create arrays of tuples of arrays.  In trying to write this in various ways, I'm having problems getting any of them to work, receiving an execution-time segfault instead:

### Steps to Reproduce

**Source Code:**

```chapel
config param case = 1;

proc foo() {
  return ([1,2,3], [1.2,3.4,5.6]);
}

//                                                                              
// All of these should work, but currently none seem to                         
//                                                                              
proc main() {
  if case == 1 {
    var x = foo();
    type t = x.type;
    var A: [1..2] t;
    writeln(A);
  } else if case == 2 {
    var A: [1..2] ([1..3] int, [1..3] real);
    writeln(A);
  } else if case == 3 {
    type arrOfInt = [1..3] int;
    type arrOfReal = [1..3] real;
    type tupOfArrs = (arrOfInt, arrOfReal);
    var A: [1..2] tupOfArrs;
    writeln(A);
  } else if case == 4 {
    var A: [1..2] foo().type;
    writeln(A);
  } else if case == 5 {
    var A = [([1,2,3], [1.2,3.4,5.6]),
             ([1,2,3], [1.2,3.4,5.6]),
             ([1,2,3], [1.2,3.4,5.6])];
    writeln(A);
  }
}
```

**Compile command:**
`chpl testit.chpl`

### Configuration Information

- Output of `chpl --version`: `chpl version 1.23.0 pre-release (ece9ad948e)`

**Comment by mppf** [comment]
Not obvious to me, either.

I wonder if it's related to the domain-reference-counting related to chpl_incRefCountsForDomainsInArrayEltTypes and test/users/bugzilla/bug794133/. In particular, the code incrementing the inner domain reference count won't apply if the element type is a tuple of arrays. (But, perhaps that is an unrelated problem).

**Comment by bradcray** [comment]
Issue #13149 seems related / a duplicate.

**Comment by bradcray** [comment]
I'm replacing this issue with issue #17050 and the futures filed in PR #17051 to (a) capture the behaviors above as futures rather than just code in an issue and reflect that the behavior has changed from a segfault to a user-facing (runtime) error.
