### ISSUE TITLE
chpl fails to link with gcc 10.1.0

### ISSUE THREAD

**Issue by edeustua** [chapel-lang/chapel#15761]
### Summary of Problem
When compiling, `chpl` fails to link the final executable due to multiple definitions of a symbol. This issue can be bypassed by including `--ldflags -Wl,--allow-multiple-definition`.

### Steps to Reproduce
1. Compile `chpl` using the quick start method and gcc version 10.1.0.
2. Run `make check` or compile any example program directly. I used `chpl examples/hello.chpl` for testing.

**Source Code:**

```chapel
// Simple hello world
writeln("Hello, world!");    // print 'Hello, world!' to the console
```

**Compile command:**
`chpl examples/hello.chpl`

**Execution command:**
n/a

**Associated Future Test(s):**
All included tests fail to compile.

### Configuration Information

- Output of `chpl --version`:
```
chpl version 1.23.0 pre-release (ece9ad948e)
Copyright 2020 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)
```
I tried with version 1.22 as well.

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: fifo *
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: cstdlib *
CHPL_ATOMICS: cstdlib
CHPL_GMP: none *
CHPL_HWLOC: none
CHPL_REGEXP: none *
CHPL_LLVM: none *
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
gcc (GCC) 10.1.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
- (For Cray systems only) Output of `module list`: n/a

**Comment by bradcray** [comment]
Hi @edeustua — Thanks for reporting this.  A similar problem w.r.t. gcc 10.x was reported recently in issue #15657, but we haven't had time to address them yet.  I'd be curious what the output of your failed compile looks like if it would be easy to paste into this issue.

I don't have a copy of gcc 10.x handy (yet), but I'd be curious whether editing `$CHPL_HOME/make/compiler/Makefile.gnu` to add `-fcommon` to the lines defining DEBUG_CFLAGS and OPT_CFLAGS helps with the issue you're seeing (this isn't the approach that we're likely to ultimately take for gcc 10.x, but it may be the easiest way to get you up and running in the meantime.

**Comment by edeustua** [comment]
Hi @bradcray!

The output of the failed compile looks like this (I've added `--print-commands` for extra info):
```
# making temporary directory
mkdir -p /tmp/chpl-edeustua-81484.deleteme

# compiling generated source
make -f /tmp/chpl-edeustua-81484.deleteme/Makefile
gcc       -I/scratch/chapel/chapel/modules/standard -I/scratch/chapel/chapel/modules/packages -Wno-unused -Wno-uninitialized -Wno-pointer-sign -Wno-incompatible-pointer-types -Wno-tautological-compare -Wno-strict-overflow  -I/scratch/chapel/chapel/modules/internal  -c -o /tmp/chpl-edeustua-81484.deleteme/hello.tmp.o -I. -I/scratch/chapel/chapel/runtime/include/localeModels/flat -I/scratch/chapel/chapel/runtime/include/localeModels -I/scratch/chapel/chapel/runtime/include/comm/none -I/scratch/chapel/chapel/runtime/include/comm -I/scratch/chapel/chapel/runtime/include/tasks/fifo -I/scratch/chapel/chapel/runtime/include/threads/pthreads -I/scratch/chapel/chapel/runtime/include -I/scratch/chapel/chapel/runtime/include/qio -I/scratch/chapel/chapel/runtime/include/atomics/cstdlib -I/scratch/chapel/chapel/runtime/include/mem/cstdlib -I/scratch/chapel/chapel/third-party/utf8-decoder -I/scratch/chapel/chapel/runtime//../build/runtime/linux64/gnu/x86_64/arch-native/loc-flat/comm-none/tasks-fifo/tmr-generic/unwind-none/mem-cstdlib/atomics-cstdlib/none/none/fs-none/lib_pic-none/include   /tmp/chpl-edeustua-81484.deleteme/_main.c
g++  \
                 \
              -o /tmp/chpl-edeustua-81484.deleteme/hello.tmp /tmp/chpl-edeustua-81484.deleteme/hello.tmp.o  \
              /scratch/chapel/chapel/lib/linux64/gnu/x86_64/arch-native/loc-flat/comm-none/tasks-fifo/tmr-generic/unwind-none/mem-cstdlib/atomics-cstdlib/none/none/fs-none/lib_pic-none/main.o  \
              -L/scratch/chapel/chapel/lib/linux64/gnu/x86_64/arch-native/loc-flat/comm-none/tasks-fifo/tmr-generic/unwind-none/mem-cstdlib/atomics-cstdlib/none/none/fs-none/lib_pic-none -lchpl -lpthread -lm \

/usr/bin/ld: /scratch/chapel/chapel/lib/linux64/gnu/x86_64/arch-native/loc-flat/comm-none/tasks-fifo/tmr-generic/unwind-none/mem-cstdlib/atomics-cstdlib/none/none/fs-none/lib_pic-none/libchpl.a(chpl-comm.o):(.bss+0x10): multiple definition of `chpl_comm_diags_disable_flag'; /tmp/chpl-edeustua-81484.deleteme/hello.tmp.o:(.bss+0x58): first defined here
/usr/bin/ld: /scratch/chapel/chapel/lib/linux64/gnu/x86_64/arch-native/loc-flat/comm-none/tasks-fifo/tmr-generic/unwind-none/mem-cstdlib/atomics-cstdlib/none/none/fs-none/lib_pic-none/libchpl.a(chpl-comm.o):(.bss+0x20): multiple definition of `chpl_comm_diags_counters'; /tmp/chpl-edeustua-81484.deleteme/hello.tmp.o:(.bss+0x0): first defined here
/usr/bin/ld: /scratch/chapel/chapel/lib/linux64/gnu/x86_64/arch-native/loc-flat/comm-none/tasks-fifo/tmr-generic/unwind-none/mem-cstdlib/atomics-cstdlib/none/none/fs-none/lib_pic-none/libchpl.a(chpl-comm-diags.o):(.bss+0xc): multiple definition of `chpl_comm_diags_disable_flag'; /tmp/chpl-edeustua-81484.deleteme/hello.tmp.o:(.bss+0x58): first defined here
/usr/bin/ld: /scratch/chapel/chapel/lib/linux64/gnu/x86_64/arch-native/loc-flat/comm-none/tasks-fifo/tmr-generic/unwind-none/mem-cstdlib/atomics-cstdlib/none/none/fs-none/lib_pic-none/libchpl.a(chpl-comm-diags.o):(.bss+0x20): multiple definition of `chpl_comm_diags_counters'; /tmp/chpl-edeustua-81484.deleteme/hello.tmp.o:(.bss+0x0): first defined here
/usr/bin/ld: /scratch/chapel/chapel/lib/linux64/gnu/x86_64/arch-native/loc-flat/comm-none/tasks-fifo/tmr-generic/unwind-none/mem-cstdlib/atomics-cstdlib/none/none/fs-none/lib_pic-none/libchpl.a(chpl-comm-callbacks.o):(.bss+0x0): multiple definition of `chpl_comm_callback_counts'; /scratch/chapel/chapel/lib/linux64/gnu/x86_64/arch-native/loc-flat/comm-none/tasks-fifo/tmr-generic/unwind-none/mem-cstdlib/atomics-cstdlib/none/none/fs-none/lib_pic-none/libchpl.a(comm-none.o):(.bss+0x0): first defined here
/usr/bin/ld: /scratch/chapel/chapel/lib/linux64/gnu/x86_64/arch-native/loc-flat/comm-none/tasks-fifo/tmr-generic/unwind-none/mem-cstdlib/atomics-cstdlib/none/none/fs-none/lib_pic-none/libchpl.a(chpl-tasks-callbacks.o):(.bss+0x0): multiple definition of `chpl_task_callback_counts'; /scratch/chapel/chapel/lib/linux64/gnu/x86_64/arch-native/loc-flat/comm-none/tasks-fifo/tmr-generic/unwind-none/mem-cstdlib/atomics-cstdlib/none/none/fs-none/lib_pic-none/libchpl.a(tasks-fifo.o):(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [/scratch/chapel/chapel/runtime/etc/Makefile.exe:31: /tmp/chpl-edeustua-81484.deleteme/hello.tmp] Error 1
error: compiling generated source

# removing directory: /tmp/chpl-edeustua-81484.deleteme
rm -rf /tmp/chpl-edeustua-81484.deleteme
```
The issue seems to appear during the `g++` step, when the final binary is being linked.

Appending `-fcommon` to DEBUG_CFLAGS and OPT_CFLAGS did not fix the issue.

Best,

Emiliano

**Comment by bradcray** [comment]
Thanks for the quick response.  In reading your original issue, I think I misunderstood where things were going wrong for you due to assumptions from the other issue, sorry.  If you're interested in continuing to wrestle with this, after making that `Makefile.gnu` modification, see whether doing:

```shell
$ cd $CHPL_HOME/runtime
$ make clean all
```

and then recompiling your Chapel program improves the situation.

**Comment by bradcray** [comment]
OK, thanks for trying.  We'll work on reproducing here and stop taking stabs in the dark.

**Comment by edeustua** [comment]
No problem. Thanks for your help!

**Comment by edeustua** [comment]
I kept investigating, by trying to compile with `--savec` using my version and the one in the official docker image, and found the following:
- My version using the `gcc` 10.1.0 backend, produces the object file `hello.tmp.o`, right after the `gcc` step with the symbols listed in the error output shown above being flagged as belonging to the `.bss` section (e.g., the output of `objdump -t` looks like `0000000000000058 g     O .bss   0000000000000002 chpl_comm_diags_disable_flag`).
- The docker version, after `gcc`, produces, again, the object file `hello.tmp.o`, which this time has the failing symbols  flagged as `*COM*` instead (e.g. `0000000000000002       O *COM*  0000000000000002 chpl_comm_diags_disable_flag`).

So, my guess is that maybe there are some private/global variables that are not being properly recognized by `gcc`.

**Comment by ronawho** [comment]
I believe https://github.com/chapel-lang/chapel/pull/15763 will fix this. (Gcc 10 made `-fno-common` the default, and some of our global declarations were relying on the old behavior.)

**Comment by edeustua** [comment]
Using commit `ad1aa0b5515ce4ffdb37c71e163cad8b62c2ea47` from the gcc-10-compat branch on @ronawho repository fixes the issue. Let me know if you want me to run any further tests.

Thanks a lot!

**Comment by ronawho** [comment]
I don't think you need to run further tests. Thanks for checking!
