### ISSUE TITLE
Drop support for c_string to string assignments

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#15775]
You can assign to a Chapel `string` from a `c_string`. Currently, this causes a
bug where the user can sneak in an unvalidated buffer into a Chapel `string`.

```chapel
var s = "";

s = c"\xff";
```

We should either:
1. Validate buffer there, and make that assignment a throwing assignment.
2. Deprecate this support. Users can still create a Chapel `string` from a
   `c_string` by using factory functions:

```chapel
var s = "";

s = createStringWithNewBuffer(c"my C string");
```
    
where this particular overload of `createStringWithNewBuffer` is already
    throwing. This might result in doing an extra copy, but I think benefits of it
    outweighs that.

If we are deprecating, my main worry is still having Chapel strings that are not
UTF-8. Our implementation relies on strings being always valid in several places
for performance reasons, and I don't want to change that. So do we:

   a. Fix the bug and make the assignment a throwing assignment.
   b. Fix the bug by halting if the `c_string` is not UTF-8.

I am strongly for 2, among "a" and "b", I am for "b". As I don't know the
implications of having a throwing overload of `proc =` for `string=c_string` and
non-throwing for `string=string`. And it doesn't seem right to have a throwing
assignment, in general (?).

**Comment by e-kayrakli** [comment]
Unless anyone objects I'll fix this soon by doing the proposal 2b, which is:

- Deprecate assigning and copy-initing a Chapel string from a c_string
- "Fix" the deprecated support by halting if the buffer is not a valid UTF-8 buffer.

**Comment by tmacd8** [comment]
Is there a proposed workaround for the problem code you found?

**Comment by e-kayrakli** [comment]
The best way to create a Chapel string from a c_string is via factory functions (they exist in the interface already):

```chapel
var myStr: string = createStringWithNewBuffer(myCStr);    // create a new buffer and own it: delete when out of scope
var myStr: string = createStringWithOwnedBuffer(myCStr);  // own myCStr's buffer: delete when out of scope
var myStr: string = createStringWithBorrowedBuffer(myCStr);  // use but don't own the buffer: don't delete when out of scope
```

You can also cast a c_string to a string:

```chapel
var myStr: string = myCStr:string;
```

which calls `createStringWithNewBuffer` under the hood. But, I'd recommend factory functions as they feel more forward-compatible to me, considering plans to drop/reduce the prevalence of c_string type (#14215)
