### ISSUE TITLE
DateTime.datetime.now():string with some optimizations disabled results in a halt

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#15776]
# Summary of Problem

I had disabled some optimizations to improve compilation speed when compiling in debug mode for Cray HPO and encountered the following bug: `Datetime.datetime.now():string` gives a runtime halt when compiled with `--no-copy-propagation --no-loop-invariant-code-motion`.

@daviditen suggested that this may be due to `gettimeofday()`  not returning a usec value between `0..1e6`. However, when adding print statements to verify this, the error no longer occurs.

### Steps to Reproduce

**Source Code:**

```chapel
use DateTime;

proc f() {
  var timestamp = datetime.now():string;
}

f();
```

**Compile command:**
```
> chpl repro.chpl --no-copy-propagation --no-loop-invariant-code-motion
```

**Execution command:**
```
> ./repro
repro.chpl:4: error: halt reached - microsecond out of range
```

### Configuration Information

- Output of `chpl --version`: chpl version 1.23.0 pre-release (ece9ad948e)

**Comment by cassella** [comment]
FWIW, this compiles with those options and runs fine for me on master and on ece9ad9 on Linux.

**Comment by ben-albrecht** [comment]
@cassella - interesting. I just pulled latest master (6dcf09128fab4fe3ca30) and tried again on OS X -- still getting same error

Could be darwin-related maybe. There is a `if CHPL_TARGET_PLATFORM == "darwin"` check in `DateTime.chpl`

**Comment by bradcray** [comment]
Might be worth a valgrind run?

**Comment by jabraham17** [comment]
Closing, this program no longer fails on MacOS for me. I also tried it with valgrind on linux and everything came back clean.
