### ISSUE TITLE
Improve current `mason search` implementation

### ISSUE THREAD

**Issue by ankingcodes** [chapel-lang/chapel#15788]
Currently, if we search for a keyword as follows:
![ba](https://user-images.githubusercontent.com/40923324/84065591-3c719080-a9e2-11ea-8e0b-89e3f6df1991.PNG)

We observe that the results are not in correct proper order. It simply looks for a regex match in
all package names and shows them in the default a sorted alphabetical order. 

This issue aims to improve the mason search command such that, the package names starting with the given query shows up first. For example, 
```
$ > mason search lo
LocalAtomics (0.1.0)
Logging (0.1.0)
Gnuplot (0.1.0)
```

**Comment by ben-albrecht** [comment]
Should there be a flag to enable alphabetical ordering? I lean towards no. I checked a few package managers and did not see something like that supported elsewhere.

**Comment by ankingcodes** [comment]
I can't think of an use-case for alphabetical ordering.
