### ISSUE TITLE
Interactive feature for mason init

### ISSUE THREAD

**Issue by ankingcodes** [chapel-lang/chapel#15780]
This issue came up during the development of #15748, where we added an interactive way to create a Mason project. After the merge of that PR, users can use `mason new` to create a project by giving inputs to queries through a console. Although, we wanted `mason init` to use this feature, we encountered design issues. `mason init` was designed in a way that it shouldn't allow overwriting of already present files in a project directory. However, the interactive feature allows overwriting of Mason.toml file and module name, by taking input from user. This clash in design between the two features has prevented incorporating interactive into `mason init`. 
Read detailed discussion [here](https://github.com/chapel-lang/chapel/pull/15748#discussion_r435533353).

**Comment by ankingcodes** [comment]
@ben-albrecht Some possible solutions for this issue are : -
1. If a `Mason.toml` file and `src/module.chpl` file is not found, proceed with interactive mode. Else initialise files like `mason init` normally does.
2. When user types `mason init`, we present a message with two options to choose from - either interactive mode, or simple initialisation. For the overwriting problem, we make a separate function for `mason init` which would overwrite the previous `Mason.toml` and `src/module.chpl` with the values given during interactive session. 
3.  `mason init` : starts an interactive session 
`mason init -d | --default` : skip the interactive session and initialise project using default values. 
If a `Mason.toml` file & `src/module.chpl` file exists, and user types `mason init`, we have two options: 

       a. Either show an error message and request user to use `mason init -d` 
       b. Use method explained in (2) and overwrite the files.

**Comment by ben-albrecht** [comment]
I think the following properties will help keep `mason init` behavior predictable and intuitive:

a. The behavior of interactive vs. non-interactive does not depend on files existing (or not existing)
b. Interface does not deviate too much from `mason new`
c. Interactive and non-interactive modes available (continuation of (b))

Of the solutions listed above, I think solution (3.b) fulfills these properties best.

I'll toss out another solution, that is derived from (3):

4. `mason init` : starts an interactive session
  
    `mason init -d | --default` : skip the interactive session and initialise project using default values. 

    If a `Mason.toml` file & `src/module.chpl` file exists, and user types `mason init`, an interactive session begins where the default values are inherited from any existing files. If `mason init -d` is used with pre-existing files, the defaults are also inherited from existing files, meaning that no existing values or files will be rewritten.

    A few implementation details:

    - Because an existing `Mason.toml` may contain other information not typically generated (such as dependencies), we should read that `Mason.toml` file in, modify the TOML object values, then rewrite it - preserving any data not associated with `mason init`.
        - I think any TOML comments would be lost in this process, but that's OK.
    - If the project name is _changed_ during `mason init`, we will need to move the `src/<Project.chpl>` file to `src/<NewProject.chpl>` in addition to updating the `Mason.toml` project name.

    > mason init was designed in a way that it shouldn't allow overwriting of already present files in a project directory. 

    It's worth mentioning (4) deviates from this original design, but I am personally OK with that.

**Comment by ankingcodes** [comment]
Sounds good ! I'll proceed with implementation in a separate PR.
