### ISSUE TITLE
Follower iterators don't appear to be visible when importing a type

### ISSUE THREAD

**Issue by dlongnecke-cray** [chapel-lang/chapel#15823]
### Summary of Problem

While adding new tests for the `set` leader/follower iterator used in parallel `zip`, I decided to use the `import` directive instead of `use`. Many tests for containers such as `list` opt to use a directive such as `import List.list;` to bring the type `list` from the `List` module into scope.

With such a directive a call to a leader iterator defined over the type will resolve fine, but when the zippered iterator tries to resolve a call to the follower, it appears not to be in scope.

### Steps to Reproduce

**Source Code:**

```chapel
module TestImportTheseFollower {
  // Import the type `set` from the submodule `MySet`.
  import this.MySet.set;

  proc test() {
    var s1 = new set();
    var s2 = new set();

    forall (x, y) in zip(s1, s2) do
      var tmp = x + y;

    return;
  }
  test();

  module MySet {

    // Define a simple "set" type.
    record set {
      iter these() { for i in 0..#100 do yield i; }

      iter these(param tag) where tag == iterKind.leader {
        var space = 0..#100;
        for followThis in space.these(tag) do yield followThis;
      }

      iter these(param tag, followThis) where tag == iterKind.follower {
        for idx in followThis(0) do yield idx;
      }
    }
  }
}
```

**Comment by dlongnecke-cray** [comment]
Summoning the import master @lydia-duncan 🙏and the iterator guru @vasslitvinov

**Comment by lydia-duncan** [comment]
It looks like this is a bug in determining whether to use method resolution or function resolution.  The "methodToken" argument is inserted as a named expression rather than a SymExpr, so it isn't matched the way it should.  I think this will be an easy fix?

**Comment by lydia-duncan** [comment]
Okay, not easy.  The method token argument is being set by passing an outer method token argument instead of gMethodToken directly

**Comment by vasslitvinov** [comment]
> The method token argument is being set by passing an outer method token argument instead of gMethodToken directly

I believe that we have this convention within the compiler. To test whether something is a method token, we compare its type against dtMethodToken rather than the symbol against gMethodToken. Maybe there is a spot where we compare against gMethodToken directly?

**Comment by lydia-duncan** [comment]
Yeah, I figured that out and it allowed the program to compile.  I'm now looking into if we already have a way to detect if a call is a method call using this strategy, since reimplementing that check in other places seems fraught

**Comment by lydia-duncan** [comment]
Okay, I'm running testing over [this branch](https://github.com/chapel-lang/chapel/compare/master...lydia-duncan:fixImportIteratorBug) now.  Does it allow you to do more of what you were originally intending to do?

**Comment by dlongnecke-cray** [comment]
Hi, I will check out the branch now. Thanks!
