### ISSUE TITLE
proc _checkType(type eltType) in docs of List

### ISSUE THREAD

**Issue by Rapiz1** [chapel-lang/chapel#15836]
### Summary of Problem
![image](https://user-images.githubusercontent.com/20105061/84585653-99d36a80-ae44-11ea-873d-9e0a44648a16.png)
I see this in docs of `List`. I suppose it shouldn't be documented and introduced to users? If it should be, then what's the heading underscore for?

Confirmed on both 1.22 and master.

**Comment by Rapiz1** [comment]
@ben-albrecht I also opened a PR. If it's intended to be documented then feel free to close it.

**Comment by bradcray** [comment]
I agree that this routine isn't meant to be user-facing and suspect that this was an oversight on @ben-albrecht's part in PR #15370.
