### ISSUE TITLE
Instantiating generic fields with different signatures fails

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#15830]
### Summary of Problem

When instantiating a generic field twice in a program with different signatures each time, the second instantiation fails because it seems to believe the field's type to be that of the first instantiation.

### Steps to Reproduce

**Associated Future Test(s):**
[`test/types/records/generic/allParamMultiInst.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/types/records/generic/allParamMultiInst.chpl
          ) #15829

### Configuration Information

- Output of `chpl --version`: `chpl version 1.23.0 pre-release (006649d5a3)`

**Comment by bradcray** [comment]
@benharsh: Here's that initializer issue I poked you about yesterday.  I mentally assumed that this was related to your generic initializer work, but I guess I'm not confident that's the case.

**Comment by cassella** [comment]
```chapel
var myS1: S = makeS(1, 2, 3);
compilerWarning(myS1.type:string);
var myS2: S = makeS(4, 5, 6);
```
```
allParamMultiInst.chpl:30: warning: S(3)
allParamMultiInst.chpl:14: In initializer:
allParamMultiInst.chpl:15: error: cannot assign expression of type R(4,5) to field 'r' of type R(1,2)
allParamMultiInst.chpl:26: Initializer instantiated as: init(param x = 4, param y = 5, param z = 6)
```

Making the field `r` a pure generic `var r;` changes the reported type of `myS1`, and compiles and runs:

```
fortytwo@magrathea:~/src/chapel (master)$ chpl allParamMultiInst.chpl 
allParamMultiInst.chpl:30: warning: S(R(1,2),3)
fortytwo@magrathea:~/src/chapel (master)$ ./allParamMultiInst -nl 1
1.2.3
4.5.6
```
