### ISSUE TITLE
Can't init a shared nilable field in a generic record or class...

### ISSUE THREAD

**Issue by GordonBGood** [chapel-lang/chapel#15846]
### Summary of Problem

As the title says and as per the source code below.

### Steps to Reproduce

**Source Code:**

```chapel
class C {  }

record Test { // generic; could also be class...
    type rslttype;
    var rt: rslttype? = nil: rslttype?; // same error for default case!
}

var tst = new Test(shared C); // compiler bug/error for shared!!!

// need to use unmanaged and convert it to shared using shared.create() later!!!!!
// var tst = new Test(unmanaged C); // this works
writeln(tst);
```

Error on compilation for the "shared" case:
BUG.chpl:5: internal error: AST-EXP-0433 chpl version 1.22.0

Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug --
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.

Run output with the work-around of using "unmanaged":
(rt = nil)

Note, to use this ability currently, I am making the type of the generic to be an "unmanaged" and converting the field to a "shared" using `shared.create()`, but it is more awkward and there is a significant chance that if one forgets or does it incorrectly, there will be a memory leak.  For instance, one can not designate the return types of some methods due to this and must allow them to be inferred from the instanciated type.

**Compile command:**

With the test file named "bug.chpl", compile with `chpl bug.chpl`.

**Execution command:**

`./bug` when it compiles, but the problem is with compilation...

### Configuration Information

- Output of `chpl --version`:  chpl version 1.22.0
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
CHPL_TARGET_PLATFORM: cygwin64 +
CHPL_TARGET_COMPILER: gnu +
CHPL_TARGET_ARCH: x86_64 +
CHPL_TARGET_CPU: native +
CHPL_LOCALE_MODEL: flat +
CHPL_COMM: none +
CHPL_TASKS: fifo +
CHPL_LAUNCHER: none +
CHPL_TIMERS: generic +
CHPL_UNWIND: none +
CHPL_MEM: cstdlib +
CHPL_ATOMICS: cstdlib +
CHPL_GMP: gmp +
CHPL_HWLOC: none +
CHPL_REGEXP: re2 +
CHPL_LLVM: none +
CHPL_AUX_FILESYS: none +
- Back-end compiler and version, `gcc --version``:  gcc (GCC) 9.3.0

**Comment by mppf** [comment]
hi @GordonBGood - thanks for filing this issue. I've been able to reproduce the problem and I'm investigating.

**Comment by bradcray** [comment]
@GordonBGood: This is completely off-topic, but I'm not sure I have a better way to contact you:  A colleague pointed out your Nim and Chapel comparison this morning, and I posted some follow-up questions and comments on it, but they haven't gotten through the moderator queue last I checked.  I'll leave it at that for now, but if they don't show up in a few days, maybe I could get a copy of them to you over Gitter or by email (?).

**Comment by GordonBGood** [comment]
That was fast, thank you.

**Comment by GordonBGood** [comment]
Hi Brad, I was hoping to be able to get in more direct contact with you
eventually; happy the the occasion is now.  Pleased to meet you.

If you have discussion related to my post on the Nim forum related to any
errors or omissions on my part (which I would be happy to correct), that is
the better place to post them, but as you say, there is a day of a day or
two in joining the forum, so meanwhile we can correspond and I'll correct
anything glaring on your behalf.

I am reluctant to post my email address in a public place such as this, but
I am active on StackOverflow (where I see you are too) and RosettaCode so
you could have contacted me through talk pages there.  However, I see your
email address at hpe and will contact you through that.  There will be some
delay in discussions with you in Seattle, most of the Nim people in Europe,
and me in Thailand, but we'll get it done.

I will be most interested to see your comments and questions on my Nim
forum post.  In the meantime, you might like to look at some Chapel code I
posted on RosettaCode re Hamming Numbers sequence:
http://rosettacode.org/wiki/Hamming_numbers#Chapel and the Sieve of
Eratosthenes:
http://rosettacode.org/wiki/Sieve_of_Eratosthenes#A_Multi-Threaded_Page-Segmented_Odds-Only_Bit-Packed_Version.
This last is a bit long for posting there, but I wanted to show Chapel's
strength in efficiently running things in parallel.

I'll be in touch.
