### ISSUE TITLE
IO reader shows unexpected behaviour for a byte stream

### ISSUE THREAD

**Issue by Aniket21mathur** [chapel-lang/chapel#15844]
### Summary of Problem
I wrote a byte stream to a file using IO writer, the length of the byte stream was 23. On reading the bytes from the file, the IO reader only reads first 9 bytes. It might be possible because of some specific bytes present in the byte stream. 

### Steps to Reproduce

**Source Code:**

`write.chpl`
```chapel
use IO;

var s:bytes = b"\x08\x96\x01\x10\xC0\x84=\x18\xDC\x0B \xA0\x8D\x06(\x020\x90N8\x03@d";

var file = open("out", iomode.cw);
var writingChannel = file.writer();
writingChannel.write(s);
writeln(s.size); //23
```
`read.chpl`
```chpl
use IO;

var file = open("out", iomode.r);
var readingChannel = file.reader();

var s:bytes;
readingChannel.read(s);
writeln(s.size); //9 expecting it to be 23 
```

### Configuration Information

```
chpl version 1.23.0 pre-release (82f040414e)
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_LLVM: none *
CHPL_AUX_FILESYS: none
```

**Comment by e-kayrakli** [comment]
I don't think there is a bug.

@Aniket21mathur -- the `bytes` you write to the file contains whitespace characters. I can see a space and a `\x0b` which is a tab character. The default IO style makes such reads stop at whitespace characters. See https://chapel-lang.org/docs/master/modules/standard/IO.html#IO.iostringformat if you can adjust the style better for your needs.

Please let me know if I am missing something.

**Comment by mppf** [comment]
Maybe you want to be using `readBytes` - https://chapel-lang.org/docs/master/modules/standard/IO.html#IO.channel.readbytes

**Comment by mppf** [comment]
The misunderstanding about `read(s)` is discussed in #14107 and it's a common "gotcha".  I think we should consider fixing it.

**Comment by Aniket21mathur** [comment]
@e-kayrakli @mppf thanks for clarifying.

> Maybe you want to be using `readBytes`

Yes, it works for me.

Should I close this issue now?
