### ISSUE TITLE
Semantics of a method on a type alias

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#15866]
Should a method defined on a type alias (MTA) apply to a call whose receiver has the aliased type?

### Proposed choices

**(A)** an MTA applies only when the receiver's type is that type alias
**(B)** an MTA is equivalent to a method defined on the aliased type

### Discussion

The following is a partial summary of the discussion in #11646 and #15825.

#### (A) an MTA applies only when the receiver's type is that type alias

This introduces a powerful tool for a Chapel user to enforce semantic differences between uses of the same underlying type.

For example, one could differentiate between integers used for counting someone's age vs. height, as in [this example](https://github.com/chapel-lang/chapel/pull/15825#issuecomment-643447379). Without this tool, the user would have to resort to wrapping an integer in a record.

#### (B) an MTA is equivalent to a method defined on the aliased type

This is consistent with how type aliases behave in other cases and is the semantics intuitively assumed by users.

Other uses of type aliases:
* the type of a formal vs. the type of an actual
* a variable declaration
* type equality
* `new` expression, see #11656

Users assumed equivalence in reporting bugs in #5143 and #11646 .

**Comment by bradcray** [comment]
My quick answer to this question is that (B) seems most consistent with how type aliases work today (as you note), so is probably what we should do for Chapel as currently defined.

That said, I'll say that I've long wished for a way to create a type alias that is a distinct type, like `newtype age = int;` where that type could have its own methods, operator overloads, casts and/or coercions, etc.  Currently this can be achieved by creating a `record age` that wraps an `int` and providing a bunch of methods and overloads on it, but that feels heavyweight in terms of user effort, making me wish for another way of doing it.  Another example where it might be applicable would be our `index(D)` types which are currently an alias to the Domain's `idxType` but may be more powerful / convenient if they were a distinct type.

So I think the desire for (A) is understandable, but I'm not convinced that our current type aliases are the way to get them into the language without completely redefining their behavior in all other contexts.

**Comment by mppf** [comment]
I think we should do (B) and generally agree with @bradcray's comment.

**Comment by vasslitvinov** [comment]
We have agreed to proceed with (B). Closing.
