### ISSUE TITLE
Issue with importing reexported symbols across file boundaries

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#15915]
### Summary of Problem
A nested reference to a reexported symbol from another file fails to resolve, saying there is no symbol with that name in that scope.  I believe this is due to the AST id being lower for the dependent import than for the import in the dependency, meaning we try to resolve the dependent import before the scope in the dependency knows it has an import statement.

### Steps to Reproduce

**Source Code:**

separateFile2.chpl
```chapel
module separateFile2 {
  import separateFile.Inner; // This is the import that fails to resolve

  proc main() {
    writeln(Inner.innerX);
  }
}
```

separateFile.chpl
```chapel
module separateFile {
  public import separateFileSrc.Inner; // This is the import that causes the problem
  // Note that if the above import is a single top-level symbol from another file, we
  // don't encounter any issue (e.g. if we were importing separateFileSrc directly).
}
```

separateFileSrc.chpl
```chapel
module separateFileSrc {
  module Inner {
    var innerX: bool = false;
  }
}
```

**Compile command:**
`chpl separateFile2.chpl`

**Associated Future Test(s):**
I've written a test but I may choose to resolve it at the same time it is added rather than committing it first

### Configuration Information

- Output of `chpl --version`: chapel 1.23.0 (pre-release)

**Comment by lydia-duncan** [comment]
I've been thinking of a few different ways of dealing with this, but they feel fairly drastic.  I'm not sure if there's a way to resolve the issue that isn't drastic, though.

Current strategies:
1. Make some sort of dependency graph for the use and import statements, follow to leaves and resolve backwards from there, instead of going in order from the top level module
2. insert symbols from a file earlier in the AST (aka, altering the file module's insertion into theProgram->block->body), prior to the file that triggered its parsing
3. Mark scopes with a progress enum or something indicating whether the scope has finished resolving its imports and uses ("not started", "in progress", "complete" as potential stages).  Any time we would search a scope not marked as complete, pause and finish going through its imports and uses either until it is complete or until we reach a circular dependency.

I think 2 is pretty easy to do.  I could add an alternative version of addTopLevelModule that takes in the module or defExpr it should be defined prior to.

**Comment by lydia-duncan** [comment]
@mppf - I'd be curious to hear your thoughts on this.  I think 1 and 3 are maybe more appropriate for a compiler rewrite than the current compiler, but I'm worried 2 is too much of a bandaid and suspect there are other ideas I'm not thinking of

**Comment by mppf** [comment]
3 sounds the most reasonable of those options to me. I'd generally expect that the issue can be solved by processing the imports and uses in a recursive manner. I agree that circular dependencies are a tricky part.

One idea that's perhaps a simpler version of (1) is to create a different AST representation for the resolved imports - kindof like useList stores some of these relationships. But it'd still be necessary to track when this new structure has been formed, so maybe (3) is still necessary.
