### ISSUE TITLE
Improved caching of generic instantiations for POI - Strategy A

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#15922]
Main issue: #6252. Strategy B: #15923

We would like to resolve #6252 by making the choice of POI deterministic and specific to each (static) call. The straightforward implementation attempted in #15872 proved prohibitive in terms of compilation time, see https://github.com/chapel-lang/chapel/issues/15872#issuecomment-645768702.

Here we examine one optimization strategy that retains the semantics.

Currently caching of generic instantiations conceptually uses the key that contains:
* the FnSymbol of the function being instantiated,
* the tuple of type and param values for which that FnSymbol is instantiated.

This strategy A adds one more component to the key:
* the POI scope for which the function is instantiated.

More precisely, consider the `call` for which the function is being instantiated. For the key, use the nearest enclosing scope that defines visible functions, see `visibleFunctionMap`.

If `call` is within an instantiation of a generic function and such nearest enclosing scope is outside the instantiation, use the body of the instantiation, fn->body, for the key.

Also "scope collapsing": if the POI's visible-function-defining scope is a module that is also visible from the function being instantiated, ignore that scope.

We can also omit the module scopes for the modules that are always visible. I.e. ChapelStandard - in user code only.

While there are a lot of technicalities here, they are for implementation only. The semantics presented to the user remains simple.

**Comment by lydia-duncan** [comment]
To make sure I'm fully understanding, when you say:

> use the nearest enclosing scope that defines visible functions,

do you mean the nearest scope that **already** defines visible functions?  Or the nearest scope that **can** define visible functions?

**Comment by vasslitvinov** [comment]
I mean the one that already defines them.

**Comment by lydia-duncan** [comment]
I'm realizing now that the call will always be in a function of some kind, so the nearest scope that already defines a function will at least be the scope that defines the function with the call, so the distinction won't be an issue.  Sorry for the confusion

**Comment by vasslitvinov** [comment]
I have a prototype implementation of this approach here:
https://github.com/chapel-lang/chapel/compare/master...vasslitvinov:prototype-poi-Strategy-A

Lessons learned:

* Hit a snag where an `instantiationLimitMap` entry is not decremented when it should, resulting in early exit from compilation.
  I started fixing it, need more time to complete.

* To reduce the number of unnecessary instantiations, need to implement various optimizations, such as scope collapsing and ignoring the functions that do not make any named calls.

* Also, do a better job of trimming the visibility scope for a given CallExpr. For example, (a) when the POI scope is contained in the lexically-enclosing scope, use the lexically-enclosing scope; (b) when the nearest scope containing visible functions does not contain any functions with the name of the called function, can we skip that scope?

**Comment by vasslitvinov** [comment]
Strategy B #15923 has been implemented instead
as discussed in https://github.com/chapel-lang/chapel/issues/6252#issuecomment-700422786
