### ISSUE TITLE
Improved caching of generic instantiations for POI - Strategy B

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#15923]
Main issue: #6252. Strategy A: #15922

We would like to resolve #6252 by making the choice of Point of Instantiation (POI) deterministic and specific to each (static) call. The straightforward implementation attempted in #15872 proved prohibitive in terms of compilation time, see https://github.com/chapel-lang/chapel/issues/15872#issuecomment-645768702.

Here we examine another optimization strategy that retains the semantics.

Currently a cached generic instantiations is looked up with the key containing:
* the FnSymbol of the function being instantiated,
* the tuple of type and param values for which that FnSymbol is instantiated.

This strategy B allows multiple instantiations for the same key, differentiated by the additional information stored with each instantiation. In the existing implementation, a cache lookup returns either 1 instantiation or none. Now it can return 0, 1, or several instantiations. A previously-created instantiation is used as the resolution target for a new call only when it is **applicable** to this call based on the additionally-stored information.

The following goes into details. While there are a lot of technicalities, they are for implementation only. The semantics presented to the user remains simple, as if no caching is done at all.

#### Calls TO vs. IN a generic function

Here are the the key "participants" for these rules:
```chpl
// CTF: a call TO the generic function
// it can be within another generic function or in a non-generic context
// it is the Point of Instantiation (POI) for a GI (see below)
gf(...);

// GF: the generic function that is the resolution target of the CTF
// its body is not resolved directly
proc gf(...) {
  ...
}

// GI: an instantiation of GF; its body gets resolved
// it is a clone of the GF, created for a specific CTF
// key question: can it be reused for another CTF ?
proc gf(...) {
  otherFun(...);  // CIF: a call INSIDE the generic function instantiation / GI
                  // key concern: correctness of the set of visible functions
                  // when resolving this call
}
```

#### The additionally-stored information

To differentiate between the instantiations (GIs) for a given cache key, associate the following info with each GI:

(B1) A set of FnSymbols such that (i) they are the resolution targets or other visible candidates of the CIF calls in this GI, and (ii) they are visble only via POI(s) of this GI. These POI(s) are determined by the CTF call for which this GI was created.

or 

(B2) A summary of the above, consisting of (i) the set of inner-most scopes that define the above set, and (ii) the set of those functions' names.

#### Applicability criterion: definition

If both checks below pass, the GI instantiation is considered **applicable** to a CTF call.

* (Check1) All FnSymbols associated with the GI as resolution targets are visible from the CTF.

* (Check2) No functions with those names are visible from the CTF, other than those associated with the GI as resolution targets or other visible candidates.

#### Applicability criterion: how it works

Let CTF-1 be the call for which the GI was created. Let the "applicability" check pass when considering the GI for a call CTF-2.

Applicability guarantees that set of visible functions / applicable candidates for each CIF call within GI is the same whether GI was created/resolved for CTF-1 or for CTF-2. Therefore if we were creating a GI-2 specifically for CTF-2, all resolution outcomes within GI-2 would be the same as their counterparts within GI. So, GI and GI-2 are equivalent and GI can be used instead of GI-2.

The reason for same-ness of the visible function sets relies on an additional Overload Sets check for POIs, currently in the works. Recall that the set of visible functions for a given CIF call consists of (a) those visible from the scope of this CIF, and (b) those visible at this GI's POI(s). The check requires that the applicable candidates for the CIF either all come from (a) or all come from (b).

If they all come from (b) when handling CTF-1, they must come from (b) when handling CTF-2, that is they must be visible from CTF-2. This is ensured by the applicability criterion.

**TODO** need to ensure that CTF-2 does not define any functions that could interfere with those in (a).

Compared to Strategy A, this Strategy B leads to more work per function brought from a POI. My expectation that a generic instantiation usually brings only a small number of functions from POIs, so overall the amount of work here may be lower than under Strategy A.

**Comment by vasslitvinov** [comment]
Additional considerations:
* "scope collapsing", discussed in #15922
* certain functions to be resolved without POI and retaining the existing single-instantiation-per-key discipline, such as field accessors and functions with only __primitive operations in the body
* special methods such as init, deinit, perhaps also assignment - see `typeHelperNames` in the compiler - should probably be required to be 1:1 with their types and so excluded from CIF treatment; otherwise the number of cases where applicability checking passes - and more instantiations are required - will be greatly reduced

**Comment by vasslitvinov** [comment]
I keep circling back to how to handle fields and perhaps methods. See also #15938.

My concern is that if the target of a CIF call is a method or field `R.foo`, then the presence of other functions called `foo` affects "applicability" for the enclosing GI only when they are methods on the same `R`. If we take into account all functions called `foo`, we will make GI not applicable more often than necessary, increasing the number of instantiations we stamp out.

This worries me particularly for things like `init` and `writeThis`, which are going to be defined in virtually any scope with a record/class declaration. Maybe this is handled by my `typeHelperNames` proposal above?

Perhaps the answer here is to consider this an optimization, rather than affecting the semantics.

**Comment by lydia-duncan** [comment]
I think we should definitely consider other functions with the same name, but definitely not methods defined on other types, that seems like it would be a backwards step

**Comment by vasslitvinov** [comment]
Good point. To rephrase, instead of recording/comparing just the name, use the pair (name, receiver type) if it is a method. I expect that this will relieve my concern.

What I am unclear about is how about methods whose `proc` declaration uses an expression for the receiver type. For example:
```chpl
proc (myFun()).myMethod() .....
proc myFun() type { return something }
```

Are we going to know what type to associate myMethod() with, in time for resolving a call? In particular, when resolving a call before the "resolution order" reaches the code in this snippet.

**Comment by vasslitvinov** [comment]
Here is a manual analysis of a variation of the code in `test/functions/generic/poi/hashed-dist-with-mapper.chpl`
It does not use Lydia's above proposal to record the method receiver as well (because it was written earlier).

application code:

```chpl
use ChapelArray, HashedDist;

record MyMapper { }

proc this(this:MyMapper, ind, targetLocs) {
  return targetLocs[ind % targetLocs.size];
}

add(D, "zero");  // Call-1 --> GI-1
```

module ChapelStandard / ChapelArray:

```chpl
// generic function
proc add(D, elm) {
  // return this._value.dsiAdd(elm);
  var temp1 = _value(D);
  var temp2 = dsiAdd(temp1, elm);
}

// instantiation GI-1 <-- Call-1
/*
additional caching information:

  calls resolve to int/std modules: <none>
    plus calls required for GI-2:   this

  calls resolve to enclosing scope: _value [module ChapelArray]
    plus calls required for GI-2:   dist, indexToLocaleIndex, locDoms,
                                    add, mapper, targetLocales [module HashedDist]

  calls resolve to POI:             dsiAdd [Call-1]
    plus calls required for GI-2:   this   [Call-1]

enclosing scope is ~part of int/std modules scope
*/
proc add(D: _domain(HashedDomain(MyMapper)), elm: string) {
  var temp1 = _value(D);           // 
  var temp2 = dsiAdd(temp1, elm);  // Call-2 --> GI-2
                                   // visible at POI via 'use HashedDist'
}

// generic function, does not use POI, single instantiation per key
proc _value(D) {
  return primitive field access;
}
```

module HashedDist:

```chpl
// generic function
proc dsiAdd(this: HashedDomain, ind) {
  //return this.locDoms(this.dist.indexToLocaleIndex(ind)).add(ind);
  var t1 = dist(this);
  var t2 = indexToLocaleIndex(t1, ind);
  var t3 = locDoms(this);
  var t4 = this(t3, t2);
  var t5 = add(t4, ind);
  return t5;
}

// instantiation GI-2 <-- Call-2
/*
additional caching information:
  calls resolve to int/std modules: this
    plus calls required for GI-3:   <none>
  calls resolve to enclosing scope: dist, indexToLocaleIndex, locDoms, add [module HashedDist]
    plus calls required for GI-3:   mapper, targetLocales [module HashedDist]
  calls resolve to POI:             <none>
    plus calls required for GI-3:   this [Call-1]

GI-3's enclosing scope == GI-2's enclosing scope
*/
proc dsiAdd(this: HashedDomain(MyMapper), ind: string) {
  var t1 = dist(this);
  var t2 = indexToLocaleIndex(t1, ind); // Call-3 --> GI-3
  var t3 = locDoms(this);
  var t4 = this(t3, t2);  // array indexing, ignore its needs for now
  var t5 = add(t4, ind);  // assoc domain addition?, ignore its needs for now
  return t5;
}

// generic function
proc indexToLocaleIndex(this: Hashed, ind) {
  // return this.mapper(ind, this.targetLocales);
  var t1 = mapper(this);
  var t2 = targetLocales(this);
  var t3 = this(t1, ind, t2);
  return t3;
}

// instantiation GI-3 <-- Call-3
/*
additional caching information:
  calls resolve to int/std modules: <none>
  calls resolve to enclosing scope: mapper, targetLocales [module HashedDist]
  calls resolve to POI:             this [Call-1]
*/
proc indexToLocaleIndex(this: Hashed, ind) {
  // return this.mapper(ind, this.targetLocales);
  var t1 = mapper(this);            // field Hashed.mapper
  var t2 = targetLocales(this);     // field Hashed.targetLocales
  var t3 = this(t1, ind, t2);       // this() on caller-provided mapper
  return t3;
}
```

**Comment by lydia-duncan** [comment]
> Are we going to know what type to associate myMethod() with, in time for resolving a call? In particular, when resolving a call before the "resolution order" reaches the code in this snippet.

That seems like something that would need to be known ahead of time, right?  Otherwise we wouldn't be able to resolve the call?

**Comment by vasslitvinov** [comment]
My prototype implementation of Strategy B is here: https://github.com/vasslitvinov/chapel/compare/prototype-new-poi-rule...vasslitvinov:prototype-poi-Strategy-B

Status as of 396f8db8d7 :

* first cut on the specifics of what data to store for a cached instantiation and what data to use when checking applicability of that instantiation

* first implementation of these rules

* for now, the implementation treats methods and "type helpers" (assign, init, etc.) the old way
  because visibility rules for those are different than for regular functions

* not yet implemented the case where a CallExpr already has its `baseExpr` point to a FnSymbol at start of resolveNormalCall(); the problem is that it does not invoke getVisibleFunctions() which I am relying on; in this case I fall back on the old rules

The current implementation hits the problem of distinct instantiations of a function returning distinct types, in my case domain runtime types, which later do not match. Under the old rules there would be just a single instantiation returning the same runtime type, so it would match itself. This is akin to https://github.com/chapel-lang/chapel/issues/15807, with design discussion in https://github.com/chapel-lang/chapel/issues/15818

**Comment by vasslitvinov** [comment]
This strategy has been implemented
as discussed in https://github.com/chapel-lang/chapel/issues/6252#issuecomment-700422786
