### ISSUE TITLE
Set &= is wrong

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#15958]
### Summary of Problem

In #15644 I broke the `set` `&=` operator in the "don't use a temporary" case:

```chapel
    } else {
      if lhs.parSafe && rhs.parSafe {
        forall x in rhs do
          lhs.remove(x);
      } else {
        for x in rhs do
          lhs.remove(x);
      }
    }
```
That's `lhs -= rhs`, not `lhs &= rhs`

### Steps to Reproduce

**Source Code:**

```chapel
// Please provide source code that will reproduce the problem.
// You can insert your code inline if it's not too long.
// Otherwise, you can attach it as a file or provide a URL to it.
// To the extent possible, providing simplified programs demonstrating the
// problem will be appreciated.
// You can also replace this section with "Associated Future Test(s)" below.
```

**Compile command:**

**Execution command:**

**Associated Future Test(s):**

### Configuration Information

- Output of `chpl --version`:
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
- (For Cray systems only) Output of `module list`:

**Comment by cassella** [comment]
I'll try to fix it this evening, or this weekend.

I'm planning to just drop the attempt to not use a temporary in this case.

**Comment by dlongnecke-cray** [comment]
Thanks Paul! Just using the temporary is fine for now. I think we'll optimize this case by just touching the underlying hashtable directly in the future.

**Comment by dlongnecke-cray** [comment]
Could you also add a test that captures the correct behavior of `&=` while you're here?

**Comment by cassella** [comment]
There is a test of `&=`, but it only hit the "use a temporary" case.  And now that'll be the only case.

But I guess that means I should add more tests for the other operators that still have multiple cases.

**Comment by dlongnecke-cray** [comment]
Only as many as you feel like snagging, you can leave a TODO for the rest :).
