### ISSUE TITLE
bash completion script for mason commands

### ISSUE THREAD

**Issue by ankingcodes** [chapel-lang/chapel#16014]
This is a feature request to have command completion for the Mason commands, making it easier and faster for Chapel developers to work with Mason. A preview of what it should look like is as follows:
```
$ mason <tab>
new  init  add  rm  update  run  search  test  
...
$ mason in<tab>  
$ mason init    
$ mason init | new | build <tab>
   a.chpl  b.chpl  src/  test/  example/
```

**Comment by ankingcodes** [comment]
@ben-albrecht please add a Gsoc label here

**Comment by ronawho** [comment]
https://github.com/chapel-lang/chapel/issues/5348 may have some useful references for how we implemented bash completion for other tools

**Comment by ankingcodes** [comment]
@ronawho  - @ben-albrecht had done some previous work on this, and he mentioned about handling subcommands. Could you clarify that further ? By handling subcommands, did he mean, autocompletion for options for a particular subcommand ?

**Comment by ronawho** [comment]
I would imagine he was talking about doing tab completion for things like `mason init <tab>`. 

I think he was basically doing `mason --help` to get the list of supported commands (that's how we turn the compiler flags into bash completion scripts so we don't have to maintain the list manually -- https://github.com/chapel-lang/chapel/blob/master/util/devel/gen-chpl-bash-completion.py) and then was mentioning that we'd have to do something different to automatically generate options for subcommands like new/init/build.
