### ISSUE TITLE
compiler assertion error due to reduction of forall expression of promoted expression

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#16027]
### Summary of Problem

When reducing a forall loop whose body is a promoted expression (e.g., `[i in 1..10] i * Arr`), we hit a compiler assertion error (`internal error: RES-FUN-ION-10082`) due to the `chpl__sumType()` routine in ChapelReduce.chpl apparently trying to create a default-initialized variable of the iterator expression's type (issue #16026).  I believe the reduction itself ought to be legal and that the quick fix would be to have `chpl__sumType()` handle the case of an iterator expression more explicitly / precisely rather than solving #16026.

### Steps to Reproduce

**Associated Future Test(s):**
[`test/reductions/reduceLoopOfPromoted.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/reductions/reduceLoopOfPromoted.chpl
          ) #16025

### Configuration Information

- Output of `chpl --version`: `chpl version 1.23.0 pre-release (1032009515)`

**Comment by bradcray** [comment]
@vasslitvinov: I suspect you'd be able to get this one working without too much effort.

**Comment by vasslitvinov** [comment]
@bradcray @mppf (or anybody) I am looking for help here. Leaving alone the question of default-initializing a variable of an "iterator record" type...

What is the input type in this reduction, in other words what are the things being added to each other?

```chpl
var A: [1..3] real = [1.0, 2.0, 3.0];
var z = + reduce ([i in 1..3] (10 * A));
```

If it is an iterable i.e. a promoted or forall expression, how do I compute an identity element of this type?

**Comment by bradcray** [comment]
I'd expect the output here to be `[30.0, 60.0, 90.0]`, so as you suggest, I think the literal element type would be an iterator expression.

Ideally, we'd have a way to query the type yielded by an iterator expression (similar to how you added an ability to query the shape of one?).  I don't know offhand whether that already exists, or whether it would need to be added (or whether a trick could be used to compute it without evaluating it... looks like [this trick](https://tio.run/##VY0xC8IwFIT3/IqjUyMSWt0MIi04uLuJQ6kPWyhteH3ViPjbYzI4uNxx3PFd2zWOhhAcTy16IT56x@eXo9xrSHS8FfBoGBX28DaGJ8fdMObZaYZ0/Qzy1C5Ct0OmU88kC4@oDA2SSFZ9lEqEOhIupSnW2CTZmuJqlfrh/s7LAivUejcL9@Nd2xC@) might get it done if we don't have a better way?)

**Comment by mppf** [comment]
We have `iteratorIndexType` in the module code and `IteratorInfo->yieldedType` in the compiler.

**Comment by vasslitvinov** [comment]
Thank you Brad and Michael.

Do you see the result of such a reduction being an iterable, like its input?

Thinking ahead - once I have the identity element for the original promoted expression's element type, I will need to make an iterable out of it, to serve as the identity element for the promoted expression as a whole. I have an idea about that.

**Comment by bradcray** [comment]
> Do you see the result of such a reduction being an iterable, like its input?

Uh, that's a good question.  I'm definitely imagining `z` to be an array, but I suppose that means that the reduction expression could be an iterable and is only manifest as an array when it's assigned to the array.  But I'd be very comfortable having the reduction expression generate an array as well given that I think we imagine reductions to be proactive evaluations of things rather than lazy creations of larger and larger iterator expressions to be resolved.
