### ISSUE TITLE
Restore Chapel grammar to spec in online version

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#16082]
When it was in LaTeX form, the Chapel language specification had some auto-generated appendices specifying the grammar.  These seem to have gotten lost in the conversion to rst / www, and should be reinstated (mostly for the reader, but in part because they also helped keep the grammar fragments in the spec coherent with respect to each other, IIRC).

**Comment by dlongnecke-cray** [comment]
This is fixed by https://github.com/chapel-lang/chapel/pull/16697. Check out the pre-release syntax page: https://chapel-lang.org/docs/master/language/spec/syntax.html
