### ISSUE TITLE
AST-LOO-XPR-0508 when referring to same-module symbol via explicit module in for/forall expression

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#16093]
### Summary of Problem

**Source Code:**

```chapel
module foo {
  var x: int;

  writeln(foo.x);

  var A = for i in 1..10 do foo.x;
  writeln(A);
}
```

The same thing happens if `A` is initialzied with a `forall` expression.

It's not clear to me that code in `module foo` should be able to refer to its variables with this module-prefixed form without an `import`.  But without the two lines about `A`, it compiles and runs, writing `0`, so the `writeln(foo.x)` can.

**Compile command:**
`chpl foo.chpl`

```
foo.chpl:6: internal error: AST-LOO-XPR-0508 chpl version 1.23.0 pre-release (26243a990a)
```
Or, in devel mode,
```
foo.chpl:6: internal error: assertion error [AST/LoopExpr.cpp:508]
```
which is

```c++
static bool isGlobalVar(Symbol* sym) {
  Symbol* parent = sym->defPoint->parentSymbol;

  ...

  if (ModuleSymbol* moduleParent = toModuleSymbol(parent)) {
    // Until normalized, only system symbols are under a ModuleSymbol.
    INT_ASSERT(normalized || moduleParent == rootModule);
    return true;
  }
```

**Associated Future Test(s):**

None yet

### Configuration Information

```
chpl version 1.23.0 pre-release (26243a990a)

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_LLVM: none
CHPL_AUX_FILESYS: none

gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
```

**Comment by cassella** [comment]
May be related to #16043.  At least, the setup and sensitivity to being in a for or forall expression is similar.

**Comment by cassella** [comment]
The original code compiles and runs fine now.  I don't know if there's an existing test locking it in.  I'll leave this issue open to confirm one exists or to write one.

**Comment by vasslitvinov** [comment]
Closing as resolved, as the original code compiles and runs fine now. A test was added in #21317.
