### ISSUE TITLE
where clause in Map.chpl seems to be wrong

### ISSUE THREAD

**Issue by rapiz1** [chapel-lang/chapel#16116]
https://github.com/chapel-lang/chapel/blob/20f9b00d61bd6f9c204de275519e555c84059423/modules/standard/Map.chpl#L295-L300
Shouldn't it be ` where isNilableClass(valType) `?

@daviditen

**Comment by ben-albrecht** [comment]
@dlongnecke-cray may be able to get to this sooner since @daviditen is out right now. Could it be that the error message is wrong instead?

**Comment by dlongnecke-cray** [comment]
Yeah the error message is wrong. It should say "non-nilable class", thanks @Rapiz1!

**Comment by lydia-duncan** [comment]
This where clause and error message combo look to be no longer present, closing
