### ISSUE TITLE
Self-assigning `shared`s leaks or causes the instance to be `nil`

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#16121]
A small and contrived example:

```chapel
class C { var x = 10; }

var x: shared C?;

x = new shared C(20);
x = x;
writeln(x); // prints nil and leaks for `shared`, `unmanaged` works fine
```

More realistic use case is when you're trying to swap the first and the last
element of an array of `shared`s but the array is of size 1, effectively making
the swap a noop:

```chapel
class C { var x = 10; }

var a: [0..0] shared C?;
a[0] = new shared C(20);

a[0] = a[a.size-1];  // leaks

writeln(a);
```

The actual case where we bump into this is
https://github.com/chapel-lang/chapel/pull/15997 where the proposed heap
implementation uses `list` under the hood, and this swapping the first and the
last element is an essential operation for popping elements out of the heap.
Here is another snippet that is closer to what the leaky heap test was doing:

```chapel
private use List;

class T { var value = 0; }

record heap {

  var _data: list((shared T, shared T));

  proc push(in element) {
    _data.append(element);
  }

  proc pop() {
    _data(0) <=> _data(_data.size-1);
    var ret = _data.pop();
    return ret;
  }
}

var l = new heap();
l.push((new shared T(1), new shared T(2)));
//l.push((new shared T(3), new shared T(4))); // uncomment and leak goes away


writeln(l.pop());

```

In any case, the workaround is to assign the rhs to another variable first.

**Comment by e-kayrakli** [comment]
@mppf -- this felt like something we can handle in the `SharedObject` module where we can avoid doing anything if lhs/rhs instances are identical for `=` (and `init=`?). What do you think?

**Comment by mppf** [comment]
@e-kayrakli - such reference counting scenarios commonly use a retain-then-release pattern to avoid this problem. SharedObject is doing that but the problem here is that doClear is setting chpl_p = nil and chpl_pn = nil. It would be simple enough to adjust `proc =` to store `rhs.chpl_p` and `rhs.chpl_pn` in local temporary variables before running `doClear` and then the lhs fields from these.
