### ISSUE TITLE
Refactor Sys*.chpl / C type modules?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#16131]
This issue asks whether we should refactor / combine the Sys*.chpl modules in some manner as we work on stabilizing the standard libraries.  Specifically:

* It seems odd to me that `c_float` and `c_int` are defined in distinct modules, and now that re-exporting can be done in a more solid manner, it seems like we could combine them into a single module even if the implementation is split across multiple files or modules (though we may wish for a way to "re-export" documentation as well if we do that).  (For the historical perspective, I believe the reason they're different is that we generate the module defining `c_int` and friends dynamically, but `c_float` doesn't require that sort of types.

* I keep getting surprised that `syserr` is defined in `IO.chpl` rather than `SysError.chpl`

* More generally, I find I don't have much intuition as to what I should expect to find in the various `Sys*` modules.

[edit: If we were to combine `c_*` types into a single module, say `CTypes`, I'd propose we put `CPtr` types into the module as well]

**Comment by mppf** [comment]
I'm certain that they should be refactored.

**Comment by lydia-duncan** [comment]
@bradcray - was this finished with #19262?

**Comment by bradcray** [comment]
I don't know that it's finished since SysBasic still exists, but I agree we're in a much better position now and that it's not clear that this issue is going to remind us to do anything that we wouldn't through continuing the review and improvements of SysBasic, Sys, and SysError, so agree it could be closed.  Thanks!
