### ISSUE TITLE
compiler incorrectly accepts single-nibble hex literal for a byte?

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#16159]
The following string is supposed to have 11 characters like `a` and `b`. I typo'd `b` in `x` and got what looks like a malformed string with the wrong size. Is this a bug? Should this be a compiler error because my hex literal only has one nibble?
```chapel
proc write(s) { writeln((s, s.size)); }

var a = "Hello World";
write(a);
var b = "Hello\x00World";
write(b);

var x = "Hello\x0World";
write(x);
var y = "Hello\x1World";
write(y);
var z = "Hello\x2World";
write(z);
```
Due to choice of `\x00` in `b`, I can't easily copy/paste the output on my computer. Here's one interpretation of output on my terminal emulator:
```terminal
(Hello World, 11)
(HelloWorld, 11)
(HelloWorl, 10)
(HelloWorl, 10)
(HelloWorl, 10)
```
Here's [TIO](https://tio.run/##ZcqxCoMwFAXQ3a@4OCk8RF2le//AxeWlBhQeWlLRJD8f6dCSkDOf18JvLSGcbMB4oHxqkR3jbmQuh@Iy66FlqyomcPNZva7rofhm9c@TbdvsK4JKvo1/1i3BJt1Fvcu6I7ik@6j3WfcE/@sh3A). The wrong strings `x`, `y`, and `z` are all the same output and have size 10 instead of the correct 11.

`chpl version 1.23.0 pre-release (a25ae3153)`

(I could be mistaken because I don't read lexer grammar that easily.) Is the language specification ill-specified? The only mention of this syntax is for "hexadecimal-escape-character" in [lexical structure: literals](https://chapel-lang.org/docs/master/language/spec/lexical-structure.html#literals) but it doesn't mention how many digits are allowed after the escape token.

The syntax used by RegExp seems interesting if you need to specify more than one escape byte; e.g., `\x{10FFFF}   hex character code`.

**Comment by mppf** [comment]
It appears that C compilers allow strings like "Hello\x1World". The problem here is a bug that PR #16161 will fix.

> The syntax used by RegExp seems interesting if you need to specify more than one escape byte; e.g., \x{10FFFF} hex character code.

That would be a fine feature request but can we put it into another issue?

**Comment by mppf** [comment]
I created #16162 about the design question.
