### ISSUE TITLE
Chapel's `list` type should support initialization from an iterator expression

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#16166]
It seems like it would be convenient / natural to have Chapel's `list` type support initialization from an initializer expression as follows:

```chapel
var l: list(t) = myIterYieldingTypeT();
```

Is there a reason we wouldn't want to that I'm not seeing?

If not, this seems as though it could be implemented by defining an `init=` for list taking an `_iteratorRecord`?

**Comment by mppf** [comment]
After PR https://github.com/chapel-lang/chapel/pull/16180 we could alternatively adjust ` proc init=(other: [?d] this.type.eltType) ` to use the `in` intent which should also allow it.

**Comment by bradcray** [comment]
Would that have the effect of manifesting the array in memory prior to assigning it to the list?  (where I'm guessing it would be cheaper to just traverse the iterator and insert the elements one by one?)

**Comment by mppf** [comment]
@bradcray - yes it would - as a result I would agree that the `_iteratorRecord` would be better for performance.

**Comment by mppf** [comment]
> Would that have the effect of manifesting the array in memory prior to assigning it to the list? (where I'm guessing it would be cheaper to just traverse the iterator and insert the elements one by one?)

Actually, using the `in` intent would solve #13583. However the array copy involved is probably not desired.

**Comment by mppf** [comment]
PR #16708 adds the overload for `init=`. (We don't have the corresponding `proc =` overload yet and issue #16714 asks if `list` should allow cross-type assignments).
