### ISSUE TITLE
Should Chapel support indexing into bytes/strings literals?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#16165]
It seems that indexing into a string/bytes literal like:

```chapel
writeln("Brad"[2]);
```

currently results in a syntax error in Chapel (verified in Chapel 1.20.0 through `1.23.0 pre-release (40d70cf924)`.  This was news to me, and I'm not seeing an obvious reason that we couldn't / wouldn't support this (i.e., if there's a syntactic ambiguity, I'm not picking up what it would be).  I think more likely, our grammar just needs to be refactored to support this.

In the meantime, users running into this can work around it using parenthesization:

```chapel
writeln(("Brad")[2]);
```

**Comment by rahulghangas** [comment]
I have a quick fix [here](https://github.com/rahulghangas/chapel/commit/10c097fade8c8213a8dc64d3de818705f6802d7f) if we do want this feature

**Comment by e-kayrakli** [comment]
@rahulghangas -- Thanks! Assuming you have run simple tests on this (`make -C compiler parser` runs successfully, `make compiler` runs successfully, `make check` runs successfully, given snippet compiles and runs successfully), feel free to open a PR and we can discuss the details there.
