### ISSUE TITLE
Underscore nomenclature

### ISSUE THREAD

**Issue by damon-kwok** [chapel-lang/chapel#16219]
Use underscore nomenclature to replace variable and method names with `littlecamel-case` nomenclature.
The pony code on the right is more beautiful. See:

![chapel_screenshot](https://user-images.githubusercontent.com/1702133/89759370-9bf03780-db1c-11ea-85a6-33cf246a668f.png)

**Comment by bradcray** [comment]
Hi @damon-kwok — Would you clarify what you are proposing we do here in order to address and close this issue?

**Comment by damon-kwok** [comment]
@bradcray If possible, add naming constraints to the chapel compiler.

**Comment by bradcray** [comment]
It's possible, but not something I think we would turn on by default.  Personally, at least, I'm not a big fan of having languages impose naming constraints, as I think it's something a project's authors should decide for themselves given that different programmers prefer different styles (obviously).  Where things get trickier is with the standard libraries where, as you've probably seen, we've been using camelCase fairly consistently, and I think it would be too difficult/painful for users if we were to change now.  So I suspect that the best bet here would be to have the compiler support style flags like `--enforce-underscore-style` or `--enforce-camelCase-style` that would be applied to all user modules (we also talk about other styles that one may want to enforce through compiler flags like "force me to give types to my procedure's arguments" or "force me to avoid using `try!`".

See also issues #6698 and #7417, which are related.

**Comment by damon-kwok** [comment]
@bradcray Sound good!  THANKS~

**Comment by bradcray** [comment]
If you would like to open an issue specifically requesting such style-enforcement flags, please feel free to.
