### ISSUE TITLE
No rule to make target `../../COPYRIGHT', needed by `COPYRIGHT'.  Stop.

### ISSUE THREAD

**Issue by alvaradoo** [chapel-lang/chapel#16269]
### Summary of Problem
When running `make`, errors are returned saying:
***** main/ *****
make[3]: *** No rule to make target `../../COPYRIGHT', needed by `COPYRIGHT'.  Stop.
make[2]: *** [main.makedir] Error 2
make[1]: *** [compiler] Error 2
make: *** [comprt] Error 2

### Configuration Information

- Output of `chpl --version`:
chpl version 1.22.1
Copyright 2020 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: clang
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: fifo *
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: cstdlib *
CHPL_ATOMICS: cstdlib
CHPL_GMP: none *
CHPL_HWLOC: none
CHPL_REGEXP: none *
CHPL_LLVM: none *
CHPL_AUX_FILESYS: none

- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by alvaradoo** [comment]
Did normal source download without using brew install version and it built correctly. Closing issue.

**Comment by bradcray** [comment]
@alvaradoo : Back from vacation and curious about this even though you self-resolved it:  Was the idea that you did `brew install chapel` and then tried to do a `make` of the source as well? (which shouldn't be necessary with the homebrew installation).  If so, is there anything in the documentation that you think could/should be clarified to prevent other users from going down this path?  Thanks!

**Comment by alvaradoo** [comment]
Hi, no the idea is exactly what you had mentioned. I tried to do a ```make``` of the source after doing a ```brew install chapel```. I now realize that brew already builds chapel during installation. 

I think my confusion arose from following the instructions [here](https://chapel-lang.org/install-mac.html), which has the [quickstart document](https://chapel-lang.org/docs/usingchapel/QUICKSTART.html) in the fourth item, and, after clicking on the quickstart document, thinking I had to rebuild chapel when reading through those instructions.

**Comment by bradcray** [comment]
Thanks for that feedback.  So perhaps if the Mac-specific installation instructions only pointed to the Mac-specific documentation (since it in turn points to the Quickstart instructions) while also updating the Mac-specific docs to clarify that you can either install from homebrew _or_ build from source, we'd prevent others from tripping over this.  Does that sound right?

**Comment by alvaradoo** [comment]
Yes, that sounds perfectly right. I believe that would prevent others from committing the same mistake I did.

**Comment by bradcray** [comment]
Hi @alvaradoo: I ended up doing a bigger change than I'd intended, but I think the net result is still better than what we had before.  Would you take a look at the screenshots at https://github.com/chapel-lang/chapel/pull/16327 and see whether you think they're a step forward and would've helped with this confusion?  Thanks!

**Comment by alvaradoo** [comment]
Hi @bradcray. I just took a look at it, and I think that's good! That's much clearer and helps distinguish the Homebrew install & source install as two totally separate entities.

**Comment by bradcray** [comment]
Great, thanks for the quick response!  I'll get someone else on the team to review it tomorrow and then merge.  Thanks for helping us catch this potential for confusion.
