### ISSUE TITLE
Compiler seg fault with --minimal-modules with string

### ISSUE THREAD

**Issue by daviditen** [chapel-lang/chapel#16276]
### Summary of Problem
The compiler currently seg faults if using --minimal-modules on a program that includes a string.

### Steps to Reproduce

```chapel
var s = "hi";
```

**Compile command:**
chpl --minimal-modules str.chpl

### Configuration Information
chpl version 1.23.0 pre-release (21e8b99cff)
chpl version 1.22.0.0

**Comment by bradcray** [comment]
I agree with @vasslitvinov's perspective here and would suggest we close this issue.

**Comment by daviditen** [comment]
I guess I was just surprised that writing a literal of a primitive type caused a segfault. I'll go ahead and close this then.
