### ISSUE TITLE
Compiler-generated initializers do not copy domain formals when assigning to fields

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#16290]
In the code below, `c.D = {1..5}` assignment changes the domain of `arr`. We
expect that to be a constant domain.

```chpl
  class MyClass {
    var D;
    var A: [D] int;

    /*
    // uncomment this to get the desired behavior
    proc init(d) {
      this.D = d;
    }
    */
  }

  var arr = [1,2,3];
  var c = new MyClass(arr.domain);
  c.D = {1..5};

  writeln("These should be different:");
  writeln(c.A.domain);
  writeln(arr.domain);
```

Some notes:
- Having a user-defined initializer is the work-around.
- Same issue with compiler-generated record initializers
- The problem is exacerbated with https://github.com/chapel-lang/chapel/pull/16218, because after that we recognize `arr.domain` as constant, and thwart tracking arrays for that domain (and therefore `c.D`, because it is not a copy of `arr.domain)

**Future**:[`test/classes/initializers/compilerGenerated/copyDomainFormal.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/compilerGenerated/copyDomainFormal.chpl)

**Comment by bradcray** [comment]
For those who skip past most GitHub-generated notes and don't have access to our chat, @mppf is working on a branch that should resolve this (fingers happily crossed).
