### ISSUE TITLE
default forall intent allows modification of inout argument

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#16301]
The following program compiles even though I would expect a `with (ref D)` task intent on the `forall` in order for it to compile.

``` chapel
config const n = 1;
  
proc main() {
  var D = {1..3};

  foo(D);
}

proc foo(inout D: domain(1)) {

  forall i in 1..n { // task intent required?
    D = {2..4}; // race if n > 1
  }
}
```

**Comment by mppf** [comment]
Note that PR 16180 will resolve this.

**Comment by bradcray** [comment]
I agree that a ref intent should be required to modify the domain within the forall loop since default task intents should match default argument intents and domains are passed by `const ref` by default.
