### ISSUE TITLE
What domain should be used for a variable created from an iterator expression over reindexed arrays?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#16300]
Consider the following example program which creates a variable initialized from a promoted expression from a reindexed array.

What domain should the domain of the new array be?

``` chapel
var A: [1..10] int = [i in 1..10] i;
  
var B = A.reindex(0..9) + 1;
writeln(B.domain._value.type:string);
```

Currently this program prints out the reindexed domain. However, since the iterator expression is being stored into a new array, my intuition is that the new array should not have a view domain. In that event, it would print out DR domain. (Or whatever the reindexed domain would be, when stored into a user variable).

The test test/arrays/shapes/tmacd-promotion.chpl will change output if this behavior is changed.

**Comment by bradcray** [comment]
In general, given an expression:

```chapel
var B = MyArray + 1;
```

B shares MyArray's domain rather than getting its own domain which is a copy of MyArray's.  For that reason, I'd expect B in your example to use the reindexed domain rather than a new DR domain.

**Comment by mppf** [comment]
>  For that reason, I'd expect B in your example to use the reindexed domain rather than a new DR domain.

My main concern about this approach is that the compiler uses the type (of iterator records / array slices / other array views) to know that meaningful action must take place upon assigning to a user variable.

E.g. 
``` chapel
var X = A.reindex(0..9); // we are expecting compiler to copy the result of A.reindex in the process of creating X
                         // it knows to copy based upon the type of the RHS (it is an array view)
```

Now, if `var B = A.reindex(0..9) + 1;` creates a `B` with `B.domain` being a reindexed domain, then isn't `B` necessarily a reindexed array? And, in that event, isn't the compiler going to add lots of unnecessary copies of it?

E.g.
``` chapel
proc f() {
  var B = A.reindex(0..9) + 1;
  return B; // unnecessary copy here: can't return array view
}
var Y = f(); // another unnecessary copy here: new array can't alias old one
```

**Comment by mppf** [comment]
> My main concern about this approach is that the compiler uses the type (of iterator records / array slices / other array views) to know that meaningful action must take place upon assigning to a user variable.

(also from https://github.com/chapel-lang/chapel/issues/16275#issuecomment-685015642)

If `var B = A.reindex(0..9) + 1;` needs to have the reindexed domain, it could have a new array type e.g. ReindexedArrayCopy, which would have a reindexed domain but own its elements (i.e. not be a "view"). This would prevent the unnecessary copies.

**Comment by bradcray** [comment]
> it knows to copy based upon the type of the RHS (it is an array view)

In general, `var B = MyArrExpr;` creates a copy.  Is the case where it wouldn't that you're thinking of one in which `MyArrExpr` is an array, but one at the end of its lifetime (so stealable rather than needing to be deep-copied)?

**Comment by mppf** [comment]
> In general, `var B = MyArrExpr;` creates a copy.

I don't think about it that way. I wouldn't say `var B = functionReturningArrayByValue()`copies. I use the terms [copy and move](https://github.com/chapel-lang/chapel/blob/master/doc/rst/developer/chips/13.rst#copy-and-move-concepts) rather than deep-copy and shallow-copy. Nonetheless it is true that `var B = ....` can result in a copy depending on what is in the `....` which might have been all you were saying.

> Is the case where it wouldn't that you're thinking of one in which MyArrExpr is an array, but one at the end of its lifetime (so stealable rather than needing to be deep-copied)?

Yes, that is what I was trying to show in the last code example [here](https://github.com/chapel-lang/chapel/issues/16300#issuecomment-685004206). Note that I tend to view variable declaration, `in` intent, and returning by value as having the same rules for whether to copy or not. However with copy elision we can construct cases simply with variable declarations.
