### ISSUE TITLE
nested call in function call returning runtime type executes twice

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#16316]
Consider the statement `type t = returnsArrayType(makeArray());` in the below. How many times should `makeArray()` be called?

``` chapel
proc returnsArrayType(arg) type {
  return arg.type;
}

proc makeArray() {
  writeln("in makeArray()");
  var A:[1..10] int;
  return A;
}

proc test() {
  type t = returnsArrayType(makeArray());
}
test();
```

The program prints out
```
in makeArray()
in makeArray()
```

I would expect it to only print `in makeArray()` once.

**Comment by bradcray** [comment]
Once definitely seems right to me.  Do you know what's causing the second call?

**Comment by mppf** [comment]
The two calls appear in normalize.

* both calls are added in `insertCallTempsWithStmt` when handling `makeArray` in `returnsArrayType(makeArray())`
  * first call is inside the DefExpr for `t` which contains `returnsArrayType(makeArray())` as the `init`
  * second call is inside a move setting `t`

**Comment by mppf** [comment]
`resolveTypeAlias` in function resolution seems to be relying on the alias's DefExpr having an init, which is part of the reason for the duplication.
