### ISSUE TITLE
Problem with definedConst analysis

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#16354]
PR #16218 added definedConst analysis for domains. This issue is noting a problematic case.

See https://github.com/chapel-lang/chapel/pull/16180#discussion_r484950549 for another potential test case.

``` chapel
config const option = true;
var A:[1..10] int;

proc makeDomain() {
  const D = {1..2};
  writeln("in makeDomain, D.definedConst=", D._value.definedConst);
  return D;
}

proc test1() {
  writeln("test1");
  var D = makeDomain();
  writeln("in test, D.definedConst=", D._value.definedConst);
  writeln("D. is ", D);
  D = {2..2};
  writeln("D is now ", D);
}
test1();
```

This program prints out:
```
test1
in makeDomain, D.definedConst=true
in test, D.definedConst=true
D. is {1..2}
D is now {2..2}
```

Which doesn't seem right. Maybe we need to set `definedConst=false` for domains that are move'd into `var` variables?

**Comment by e-kayrakli** [comment]
I expect this will cause serious issues if the domain was used to define an array and then is resized. The fact that we report `var D` in `test1` means that it's arrays will never be resized.

**Comment by bradcray** [comment]
> The fact that we report var D in test1 means that it's arrays will never be resized.

I don't understand this sentence.  Are you saying that the analysis isn't whether or not D is const / won't change; it's whether or not there's the potential for it to cause arrays to be resized?  (such that if there are no arrays declared over it, it can't cause arrays to be resized?)

**Comment by e-kayrakli** [comment]
No, we will never resize the arrays declared over `D` even if `D` is reassigned, because we think `D` is constant.

**Comment by bradcray** [comment]
OK.  I'm still not understanding this phrase, though: "The fact that we report var D in test1 means..."  Should it say "The fact that we report var D _is const_ in  test1 means..."?

**Comment by e-kayrakli** [comment]
Oh, now I see why you were confused. Yeah, that's what I meant fixing the comment now. Sorry about the confusion
