### ISSUE TITLE
Task private variables create more vars than tasks

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#16366]
I couldn't figure out how to word this well in the title, but when using task private vars I see variables being created for things other than each task. For a simple case of iterating over a range, I see an extra variable being created. 

```chpl
var a: atomic int;
record R {
  proc init() { a.add(1); }
}

forall i in 1..here.maxTaskPar with (var r = new R()) { }

writeln(here.maxTaskPar);
writeln(a); // expecting maxTaskPar but is maxTaskPar+1
```

For the actual code I was using when I ran into this I see 2 extra variables being created, and I'm creating aggregators that allocate local and remote memory, which is expensive.

**Comment by bradcray** [comment]
This sounds like a question for @vasslitvinov.

For your "actual code" case, did it happen to be a forall that uses a nested coforall to implement itself?  (e.g., a forall over a Block-distributed domain or array)  I'm specifically wondering whether there's one extra variable for the outer coforall and one for the inner (though it'd probably be more natural fo there to be one for the outer and one per locale in the inner?  But maybe you were running on one locale?)

**Comment by vasslitvinov** [comment]
We create one TPV at the top level of the parallel iterator. This is the TPV that gets used in the loop body when the iterator has a `yield` outside any parallel construct.

**Comment by bradcray** [comment]
Could we do this conditionally only when the iterator has such a yield?

**Comment by vasslitvinov** [comment]
> Could we do this conditionally only when the iterator has such a yield?

Absolutely yes. Here are some reasons why we haven't yet:

* less importantly, the implementation effort and compilation time to detect when the outer TPV is not needed

* more importantly, consistency with shadow variables of `in` intent and `reduce` intent, ex. a `reduce` intent needs something outside of the tasks created by the iterator to combine into
* see also #5363

**Comment by ronawho** [comment]
> For your "actual code" case, did it happen to be a forall that uses a nested coforall to implement itself? (

My code is a very stripped down version of arkouda's sort that just has an inner forall so i'm not sure where the 2nd TPV is coming from:

```chpl
coforall loc in Locales do on loc {
  forall a in A.localSlice(A.localSubdomain()) with (var agg = newDstAggregator(int)) {
    agg.copy(B[a], a);
  }
}
```

The actual arkouda sort is pure spmd (coforall-on + local-coforall) so there aren't any task intents. However, gather, scatter, and many other arkoura operations are using per-task aggregators declared while iterating over block distributed arrays/domains, so there will be the 2 levels.

**Comment by ronawho** [comment]
Probably obvious, but I'm in favor of not creating the TPV if there's no yield outside parallel constructs. Creating an extra aggregator is very expensive both in terms of memory and time since it creates numLocales local allocations and 1 allocation on each remote locale.

**Comment by vasslitvinov** [comment]
> I'm in favor of not creating the TPV if there's no yield outside parallel constructs

I am game for that. I assigned this issue to myself for now.

Are we OK to add scanning parallel iterators for yields? I would expect this to be a negligible increase in compilation time.

**Comment by ronawho** [comment]
That seems fine with me. We already (or at least used to) scan for loops that yield in parallel iterators to mark them as order-independent and i don't remember that increasing compilation time by a noticeable amount. (Not that I think you'd be able to reuse that code, just noting that don't expect it to impact compilation time.)
