### ISSUE TITLE
Sparse domain assignment should do parent domain bounds checking

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#16385]
### Summary of Problem

When assigning between sparse domains, bounds checking isn't done against the LHS domain's parent domain, which can cause problems downstream when trying to use the RHS indices to index into a sparse array declared over the LHS domain.

### Steps to Reproduce

**Associated Future Test(s):**
[`test/path/to/foo.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/sparse/domains/sparseDomAssignOOB.chpl
          ) #16384 

### Configuration Information

- Output of `chpl --version`: `chpl version 1.23.0 pre-release (3a9b53685d)`

**Comment by bradcray** [comment]
@e-kayrakli : I fear that this might be yours... hopefully an easy fix?  Came up in a more complex example on gitter today.

**Comment by bradcray** [comment]
(or it could be a longstanding issue in code that you've just worked in most recently...)

**Comment by e-kayrakli** [comment]
Do we want to check whether parent domains have the same bounds, or whether the parent domain of the RHS is fully contained in the LHS's parent? (I prefer the former)

Do we also check whether parents' distributions are aligned? (I prefer we don't)

Do we also disallow `+=` where the RHS's parent domain is larger? Or do we only add the indices in the part that parents overlap? (I don't remember the current behavior offhand for bulk adding OOB indices, but this feels analogous to that. Although `+=`ing a domain can be different in terms of error behavior? I don't have an opinion on this yet)

**Comment by bradcray** [comment]
I think of domain assignment as being "assign the index set described by one domain to another" without worrying overmuch about relationships between the other information that is associated with domains like their distributions, parent domains, number or identity of arrays declared over the domains, etc.  To that end:

* I don't think there should be any constraints on the relationships between the LHS and RHS parent domains (beyond that the indices being assigned are within both of them; they should already be guaranteed to be in the RHS's parent domain if we've done our job right).  Of course, in certain cases, (e.g., LHS parent domain is a superset of the RHS parent domain) we could skip the per-index bounds checks.  But assigning {3} with a parent domain of {1..100} to a sparse subdomain of {1..10} ought to be legal since `3` is within bounds for each.

* I don't think there should be any expectation that the distributions are aligned (just as DR `{1..n}` can be assigned to a block-distributed domain).

* For `+=`, I believe that all RHS indices should put into the LHS if they're in-bounds for the parent domain or generate an OOB error if they aren't.

I was worried that other bulk index addition operations would have similar OOB issues, but wasn't able to come up with one quickly that did.  But I also didn't try very hard.
