### ISSUE TITLE
Should we remove the optional argument to `.elapsed()` in `Timer`/`stopwatch`?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#16396]
The current `Timer` type has an `elapsed()` method that takes an optional argument returning the units that the elapsed time should be reported in, defaulting to seconds.  This issue asks whether that argument should be deprecated...
- for simplicity in the interface and implementation
- since another routine could always be used to convert from seconds to some other time unit
- because we suspect it's never used in practice in the field

**Comment by vasslitvinov** [comment]
I do not see downsides in keeping the optional argument. Furthermore when we add a `Duration` datatype, that optional argument can be extended to offer "return a Duration".

So I vote for keeping the optional argument.

**Comment by bradcray** [comment]
> I do not see downsides in keeping the optional argument.

I think arguable downsides include the requirement of supporting an enum to specify it, and the related decision about whether to unify it with an existing `DateTime` enum or keep one that's specific to the `stopwatch` type.  If nobody ever used anything other than `seconds`, it also adds unnecessary complexity to what is otherwise a fairly simple and straightforward type and interface.

**Comment by lydia-duncan** [comment]
I like the idea behind `TimeUnits` (the type of the optional argument), so I wouldn't necessarily argue for removing the argument on that grounds.  But I'm ambivalent to the optional argument itself.

**Comment by e-kayrakli** [comment]
This is probably not a problem for today but, is there a chance we might lose a very short duration because we always return seconds and the return type may not be that sensitive.

I think in the typical scenario, we can measure down to nanoseconds, and return a 64-bit real, which should cover the precision easily when we return in seconds. But should we consider different systems where Chapel is run with much lower precision where this becomes an issue? In such a scenario, asking `elapsed` to return the time in nanoseconds could help, maybe.

If we didn't have the argument and we were considering adding it, I wouldn't think that this is enough motivation for addition. But it is already there, removing it is breaking, its maintenance doesn't sound too big a deal to me. So, I'd vote for no change.

**Comment by daviditen** [comment]
Language comparison:

Chapel:
```chapel
stopwatch.elapsed(unit: TimeUnits = TimeUnits.seconds): real
```

Python:
```python
# No stopwatch timer - need to subtract two times from functions like:
monotonic():float or monotonic_ns():int
perf_counter():float or perf_counter_ns():int
process_time():float or process_time_ns():int
time():float or time_ns():int
```

Rust
```rust
let instant = Instant::now()
instant.elapsed() -> Duration
Duration.as_secs() returns number of seconds as an integer(64)
Duration.as_millis() returns number of milliseconds as integer(128)
Duration.as_micros() returns number of microseconds as integer(128)
Duration.as_namos()  returns number of nanoseconds as integer(128)
```

```chapel
// How it's used in Chapel:
use Time;

var sw = new stopwatch();
sw.start();
// Do something that takes some time
// Currently using TimeUnits
writeln("milliseconds elapsed: ", sw.elapsed(TimeUnits.milliseconds));
// Proposed
writeln("milliseconds elapsed: ", sw.elapsed() * 1_000);
```

Pros to keeping it:
* It makes conversions between time units easier - e.g. you don't need to know
  how many nanoseconds are in a second.
* Other functions also use a 'unit' argument: getCurrentTime, sleep

Cons to keeping it
* It always returns a real and doesn't actually add precision - it just
  multiplies the seconds by the appropriate constant.
* For non-second versions other languages have a different function and return
  the time as an integer
* It adds a bit of complexity
* We suspect it's never actually used

**Comment by daviditen** [comment]
The design subteam reached consensus that we should deprecate the `TimeUnits` type and its use in arguments. It doesn't add precision, would need to be renamed anyway, and a similar effect can be accomplished by a simple multiplication. So let's deprecate it and add a feature request issue for a good nanoseconds timer.

**Comment by daviditen** [comment]
https://github.com/chapel-lang/chapel/pull/21826 implemented that decision.

**Comment by redhatturtle** [comment]
Well I guess it's to late but I was a fan of this feature.

**Comment by bradcray** [comment]
@redhatturtle : Can you say more about what you liked about it?  One of the reasons we deprecate before removing is to give people a chance to argue that we were wrong.  

There's also the potential opportunity to re-instate it later.  In this case, we would've had to rename the enum (which is to say, deprecate the old enum and replace it with one with an initial lowercase name) to meet our standard module naming guide anyway, so it would've had to change in one way or another.
