### ISSUE TITLE
Stabilize standard library modules ("lib 2.0")

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#16392]
As we get closer to successfully stabilizing the core Chapel language features ("Chapel 2.0" — issue #8614), we also need to turn our attention to stabilizing the standard library modules since changing the interface of a key I/O or math routine can be as impactful to code / frustrating to a user as changing a language feature.

**Comment by riftEmber** [comment]
@bradcray it looks like this was supplanted by https://github.com/Cray/chapel-private/issues/1447 and then https://github.com/Cray/chapel-private/issues/3800, can it be closed?

**Comment by bradcray** [comment]
Yep, thanks.
