### ISSUE TITLE
What module should define the `stopwatch` type?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#16394]
As part of issue #16393, we are renaming the `Timer` type to `stopwatch` for clarity; and as a larger issue, we're reconsidering the contents of the `Time` module, as there is significant overlap with `DateTime`.  This issue asks what module should define the `stopwatch` type where some options are:

- fold it into `DateTime` (rationale: it relates to time)
- rename `DateTime` to `Time` and fold it into there (rationale: simpler name, and dates inherently relate to time)
- keep it in `Time` but remove other stuff that's redundant or should be elsewhere (rationale: stopwatches are more about durations and measurement than dates and clocks)
- put it in a new module where options are:
  a new top-level module with the name...
  - `Timing[s]` (rationale: `DateTime` is more about reasoning about dates and times whereas stopwatch is more about timings / durations)
  - `Duration` (rationale: see previous)
  - `Stopwatch` (rationale: obvious choice; anti-rationale: one-type module?)

  e.g., a new sub-module of some sort of umbrella module?
  - e.g., `Diagnostics.Timings` (rationale: could be used to group related things like Memory, CommDiagnostics)

  (also should this be a package rather than standard module?)

**Comment by lydia-duncan** [comment]
My personal preference is (in order of most preferred to least):

1. rename `DateTime` to `Time` and fold it in there
2. keep it in `Time` but remove other stuff that's redundant
3. Put it in a new module named either `Timing[s]` or `Duration`
4. Fold it into `DateTime`
5. Put it in a new module named `Stopwatch`

I would be okay with any of the first four options.  I dislike the idea of it being in its own module with nothing else.

**Comment by e-kayrakli** [comment]
> rename DateTime to Time and fold it in there

Revisiting this after a while, this option is the clear choice for me.

**Comment by king-11** [comment]
@bradcray I would like to work on this issue, I am also in the favour of renaming the DateTime module to Time and merging things but which will be a breaking change so how do we deal with such changes?

**Comment by bradcray** [comment]
Hi @king-11 — I'm not sure I would recommend diving into this issue because we're in the process of reviewing standard modules, and haven't gotten to `DateTime` yet, and I worry a bit about proceeding with this before that occurs.  Specifically, we could change the `Time.Timer` type into `DateTime.stopwatch` and deprecate `Time.Timer`, but it might be wiser to bring all of `DateTime` directly over to `Time` and deprecate `DateTime.*` if that's the way we're going to go.  But I feel nervous about doing that without removing more of the current capabilities from `Time` that I believe are being deprecated.  All of this makes me nervous about making these changes until we've had the time to discuss `DateTime` further.

If you wanted to help move this along, however, you could post a design issue on Discourse asking whether people object to the general approach of (a) defining `stopwatch` within `DateTime` and (b) renaming `DateTime` to `Time` over time to see whether we're reaching consensus there.  Those who've weighed in on this issue definitely seem to be leaning that way, but I suspect most core developers haven't seen this issue.

**Comment by king-11** [comment]
Sure @bradcray I will post the design issue in Discourse

**Comment by bradcray** [comment]
We ended up deciding to merge the DateTime features into Time (@daviditen did this in #20382), so Timer can be renamed to stopwatch where it stands, closing this issue.  https://github.com/chapel-lang/chapel/issues/16393 is where that work is currently being tracked.

**Comment by daviditen** [comment]
The `Timer` is now `stopwatch` in the `Time` module.
