### ISSUE TITLE
Can we remove the reliance on ioLiteral/ioNewline type?

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#16449]
Today, we have bunch of module code that uses `ioLiteral` in their
`readThis`/`writeThis`/`readWriteThis` implementation. The benefit of doing that
is, it'll allow more uniform style in reading/writing with different IO styles.
For example, `ioLiteral`s aren't surrounded with `""`, whereas strings are in
some IO configurations.

These IO types are mentioned here: https://chapel-lang.org/docs/master/builtins/ChapelIO.html#the-readthis-writethis-and-readwritethis-methods

The problem with that is many of our modules `use IO` only for `ioLiteral` and
some of those modules are internal and pretty low-level. Coming up with an
approach where we don't `use IO` in some of those modules can help reduce the
module initialization and resolution order complications we encounter pretty
frequently while playing around with internal/standard modules.

### I see the following alternatives if we want to remove those types from user-facing API:

1. Make `param` strings behave identical to `ioLiteral` behavior today, and use
   `param` strings and/or literals in places we use `ioLiteral`

   Clean implementation. Codes would look much cleaner in many cases, can be
   confusing in some.

2. Make string literals behave the same way as `ioLiteral` and strictly use
   string literals instead of `ioLiteral`

   Not-so-clean implementation (probably some special casing in the compiler is
   needed).

### If we want to keep the types, and feel that it would be nice to remove `use IO` as much as possible especially in the internal modules:

3. Move `ioLiteral` and `ioNewline` somewhere else (e.g. ChapelIO)

   Not much room for confusion for the user and no change from where we are
   today except that those symbols will be available by default. And that may be
   against the direction we are trying to take.

4. Replace all `ioLiteral`s in our modules with a call to `readWriteLiteral` on
   the channel.

   Only solution I can think of without any change in design

### Want to get fancy?

5. Intorduce new syntax: `io""` etc..

Related: https://github.com/chapel-lang/chapel/issues/7954

**Comment by bradcray** [comment]
> Move ioLiteral and ioNewline somewhere else 

Or a new `IOLiteral` module?

**Comment by mppf** [comment]
I think that we should deprecate ioLiteral/ioNewline and replace these with methods, e.g. `matchLiteral` / `readLiteral`

**Comment by mppf** [comment]
See also:
 * #19487

**Comment by lydia-duncan** [comment]
I think #22992 resolved this, closing
