### ISSUE TITLE
Function expecting param argument can be passed a non-param value

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#16478]
### Summary of Problem
A function expecting a `param` argument can be passed a non-`param` value.

I would expect the following program not to compile, because `parSafe` is not a param when passed to `R.init`.

``` chapel
use List;

record R {
  type eltType;

  param parSafe = false;

  proc init(type eltType, bub: eltType, param parSafe = false) {
    this.eltType = eltType;
    this.parSafe = parSafe;
  }
}


proc makeThing(const ref x: list(?t), bub: x.type, parSafe: bool = false) {
  var x: t;
  var h = new R(t, x, parSafe);
  return h;
}

var l:list(int) = [2, 1, 3];
var h = makeThing(l, l);
writeln(h);

```

### Steps to Reproduce

**Associated Future Test(s):**
[`test/functions/resolution/error-expected-param-missing2.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/functions/resolution/error-expected-param-missing2
          ) (PR #16479)

test/functions/resolution/error-expected-param-missing2.chpl is a similar case that PR #16479 gets to have an error as expected.

**Comment by cassella** [comment]
This seems similar to #15928.

**Comment by mppf** [comment]
So true!

Actually the bug seems to have to do with the type of the `param` argument not being established early enough.

**Comment by bradcray** [comment]
That's really odd.  It looks like it may be specific to methods?  I was hoping it was specific to initializers, but seemed to get the same behavior for methods as well.  But not standalone functions.

**Comment by mppf** [comment]
I believe the problem has to do with this code in ResolutionCandidate.cpp:

```

bool ResolutionCandidate::checkGenericFormals(Expr* ctx) {
  int coindex = 0;

  for_formals(formal, fn) {
    if (formal->type != dtUnknown) {
```

In certain situations, `formal->type` will still be unknown by the time `checkGenericFormals` runs.

**Comment by mppf** [comment]
It would seem to be easy enough to migrate some of the checks in checkGenericFormals that are type-independent (such as param-formal-needs-param-actual) to run before checking if the type is established.
