### ISSUE TITLE
Bug: infinite loop or recursion in the compiler

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#16489]
This code throws the compiler into an infinit loop or recursion, all along throwing INT_FATAL at AggregateType.cpp:1961 :
```chpl
module Lib {
  class MyRecord { }
  var myR = new shared MyRecord()?;

  proc libFun(myArg) {
    var myRec = myArg: class;
  }
  proc main {
    libFun(myR);
  }
}
```

Tests: none, I do not see how to fit this kind of failure in the test system. Might be easier just to fix it.

Chapel default configuration, chpl version: `1.23.0 pre-release (1b513e2cda)`

**Comment by mppf** [comment]
I am seeing this
```
$ chpl vass.chpl --devel
vass.chpl:5: In function 'libFun':
vass.chpl:6: error: call to throwing cast without throws, try, or try! (relaxed mode)
```

with or without `--devel`. Did the bug go away or are is it sensitive to compiler configuration or something?

**Comment by vasslitvinov** [comment]
I can't reproduce this either.
Closing.
