### ISSUE TITLE
Support comparisons between version numbers and floating point params

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#16498]
In #15911, @mppf proposed that supporting comparisons between floating point values and version values would probably avoid most cases that would need to use `createVersion()`, which seemed promising.  For example, imagine supporting `if chplVersion > 1.23 then ...`.

**Comment by bradcray** [comment]
@e-kayrakli : Can you double-check me on the first bullet above?

**Comment by e-kayrakli** [comment]
> casting a param real to a param string (or bytes) which it looks like we don't support (?)

We do support this via prefolding those casts and not via param overloads of `_cast`:

https://github.com/chapel-lang/chapel/blob/master/compiler/resolution/preFold.cpp#L2177

This works as you'd expect:
```chapel
param r = 1.23;
param s = r:string;
compilerWarning(s);
writeln(s);
```

**Comment by bradcray** [comment]
Hmm, OK, I'll push harder then.  I was trying to do `r:string.size` which didn't seem to be working, but after grepping the modules and not finding param overloads, gave up and didn't think too hard about the error.  Let me try some more.

**Comment by e-kayrakli** [comment]
That's an operator precedence mistake. It'll try to call `size` on the `string` type. You need `(r:string).size`

**Comment by bradcray** [comment]
Huh, that must've been it.  I'd added the parentheses (they're on my branch above :) ), but then apparently went right to grepping and gave up without trying it.  Thanks!

**Comment by bradcray** [comment]
In my attempt to implement this, I believe I'm running into an issue related to floating point accuracy / roundoff errors, which I'd worried might be an issue.  Given a floating point version `2.3`, my logic for converting it into major and minor versions is:

```chapel
    param major = v:int;
    param diff = v-major;
    param diffstrsize = (diff:string).size;
    param minor = diff * (10**(diffstrsize-2));
    param minorAsInt: minor: int;
```

and find that for a floating point value `2.3` or `2.8`, I'm getting `2.2` or `2.7` as the major.minor version.  This suggests to me that the right way to do this is to convert the whole floating point value to a string and then pick the string apart, but when I think about doing that, I imagine either having `split` type functionality on param strings (which I don't think we have) or else looping over the bytes and computing the values iteratively (which would require modifiable params to achieve).  So I'm feeling slightly stuck here, though my start at it is [here](https://github.com/bradcray/chapel/tree/compareVersionToReal).

**Comment by e-kayrakli** [comment]
Offhand, I can't think of a good way of doing what you need through param strings :(

**Comment by bradcray** [comment]
Thanks for the reassurance that I wasn't missing something obvious.  I can think of ways to do it, but they're pretty special-purpose (e.g., creating a primitive that chops a param string into two param ints).  This may warrant it since the `Version` module is already fairly tied to the Chapel compiler (it exposes the compiler's version, e.g.), but I can't imagine getting it done tonight in a sane way.

**Comment by mppf** [comment]
This works for me:

``` chapel
config param v = 2.3; 


param epsilon = 0.00001;

param major = (v+epsilon):int;
param diff = v-major;
param diffstrsize = (diff:string).size;
param minorReal = diff * (10**(diffstrsize-2));
param minor = (minorReal+epsilon): int;

compilerWarning("major=" + major:string + " minor=" + minor:string);
```

But the main problem with all of this is with a version number like `1.20` - any floating point representation will view as `1.2` - but that is a different version number. So I think we'd have to use param strings for the version numbers.

**Comment by bradcray** [comment]
Oh right, duh.  Closing this based on that observation.

**Comment by mppf** [comment]
We have enough compile-time support for `param` strings to do this, but it would be nicer if there were a param substring or param split.

``` chapel
param dotChar = ".".toByte();
param zeroChar = "0".toByte();

proc paramfirst(param s:string, param i) param {
  if i >= s.size {
    return "";
  } else if s.byte(i) == dotChar {
    return "";
  } else {
    return (s.byte(i) - zeroChar):string + paramfirst(s, i+1);
  }
}
proc paramsecond(param s:string, param i) param {
  if i >= s.size {
    return "";
  } else if s.byte(i) == dotChar {
    return paramfirst(s, i+1);
  } else {
    return paramsecond(s, i+1);
  }
}

config param v:string = "1235.200";
param major = paramfirst(v, 0);
param minor = paramsecond(v, 0);
compilerWarning("major=" + major:string, " minor=", minor:string);

```

But I think we could use the above to have comparisons with version strings like "1.23" without modifying the compiler if we want to.

**Comment by bradcray** [comment]
(Belated thought:  We could just refuse to make any releases with trailing zeroes in their version numbers... :D ).
