### ISSUE TITLE
Add more math operations for DateTime types

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#16552]
Feature request for adding more math operation combinations for addition and subtraction of the types: `date`, `time`, and `datetime`.

For example, in switching from `Time.getCurrentTime()` to using the `DateTime` module, one must write:

```chpl
(datetime.now() - datetime.now().replace(hour=0,minute=0,second=0,microsecond=0)).total_seconds()
```

whereas it'd be nice to do something like:

```chpl
(datetime.now() - date.today()).total_seconds()
```

**Comment by ben-albrecht** [comment]
Previously discussed with @daviditen.

I also wonder if it would make sense to add some form of `getCurrentTime()` to `DateTime` to make the conversion even easier.

**Comment by gaurav-singh1998** [comment]
Hi, @ben-albrecht I would like to take this issue. Thanks.

**Comment by king-11** [comment]
@ben-albrecht if the issue is still available I would like to work on it

**Comment by ben-albrecht** [comment]
@gaurav-singh1998 && @king-11 - no one is working on this to my knowledge. I expect the changes to involve:

- Adding `+` and `-` operators for datetime objects
- Adding documentation for these operators
- Adding tests for these operations (think about edge cases / tricky scenarios that might open more design questions)

**Comment by king-11** [comment]
@ben-albrecht I didn't get the example that you mentioned although to me it seemed like we are looking for adding functional abstraction as well, should it also be included ?

> whereas it'd be nice to do something like:
> 
> ```chapel
> (datetime.now() - date.today()).total_seconds()
> ```

**Comment by king-11** [comment]
Also I guess the ```-``` operator has already been implemented for the ```datetime``` objects [link](https://github.com/chapel-lang/chapel/blob/1108202e645de1bcbfe7d3a5130799d5c01c8ad8/modules/standard/DateTime.chpl#L1351) So is there any change in that or is it just ```+``` operator with similar operation providing the timedelta 🤔  or should it be something else ?

**Comment by ben-albrecht** [comment]
@king-11 - That's true. I haven't thought about this feature in a while and am now wondering if this feature request is outdated or misguided.

Ultimately, I think https://github.com/chapel-lang/chapel/issues/16733 is more important / helpful in allowing us to deprecate the datetime-ish features in the `Time` module.

I am tempted to close this feature request. @daviditen - do you agree, or am I missing something?

**Comment by daviditen** [comment]
I think the idea was to have a `proc -(lhs: datetime, rhs: date)` where the fields that don't exist in the `date` are treated as zeros.

And also add other combinations of the `date`, `time`, and `datetime` types as they make sense.

**Comment by king-11** [comment]
@daviditen those methods have already been implemented for the ```datetime```, ```date``` and ```timedelta``` objects so I believe the work on this issue is already completed.

**Comment by daviditen** [comment]
@king-11 the original comment in this issue was asking for the ability to do:
```chapel
(datetime.now() - date.today()).total_seconds()
```

That is, a mixed type subtraction between a `datetime` and a `date`. That is not currently defined.

**Comment by king-11** [comment]
@daviditen now I got it 😅 sorry for not keenly observing the ```date``` in your comment. So now will be having 2 more combinations i.e. ```date - datetime``` & ```time - datetime``` and the alternates of these two I will start working on this is there something else you did like to add to that ?

**Comment by daviditen** [comment]
I think we would always want the `datetime` to be the LHS of the subtraction. @ben-albrecht is there anything else you were wanting with this issue?

**Comment by king-11** [comment]
@daviditen I also found a missing feature which should be needed if we are to move forward with mixed operators. Currently ```date.today()``` doesn't consider the localtime while ```datetime.today``` does which can be an issue is someone tries out 

```(datetime.now() - date.today()).total_seconds()```

**Comment by king-11** [comment]
@daviditen if there is something wrong in the PR can you please tell 😓 ?

**Comment by daviditen** [comment]
As a point of comparison, python doesn't support the `datetime - date` operation. That doesn't mean we shouldn't, and the team seems generally receptive to it.
