### ISSUE TITLE
getHDF5Type should not halt on unsupported HDF5 datatype

### ISSUE THREAD

**Issue by hokiegeek2** [chapel-lang/chapel#16587]
### Summary of Problem
The getHDF5Type function halts a Chapel program if the Chapel data type is unsupported in HDF5:

![image](https://user-images.githubusercontent.com/10785153/96137752-03cf4f80-0ecb-11eb-9568-9e227194f43b.png)

I recommend changing the halt clause to a throws clause

**Comment by bradcray** [comment]
It seems to me as though this actually could/should be a compile-time error (`compilerError()`) since it's reasoning about types.  @daviditen ?

**Comment by daviditen** [comment]
I opened #16590 about changing it to a `compilerError`.

**Comment by bradcray** [comment]
That seems at least a little redundant with this one?  :)  I was hoping #16590 was going to be the PR itself.

**Comment by bradcray** [comment]
See #16635 for the five-minute fix (TM) and test.

**Comment by bradcray** [comment]
@hokiegeek2 — This is not resolved, thanks for making the request.
