### ISSUE TITLE
Call to imported function within a generic function fails to resolve

### ISSUE THREAD

**Issue by dlongnecke-cray** [chapel-lang/chapel#16597]
While writing some code, I needed to use the `Reflection` module to conditionally call a function. What I found is that when I imported a single function from `Reflection`, it failed to resolve when I called it.

This is a simplified reproducer of what I was attempting to do. It fails to resolve the call to `canResolve`:

```chapel
proc foo() {
  writeln('foo');
}

proc test(param x=1) {
  import Reflection.canResolve;
  if canResolve('foo') then
    foo();
}
test();
```

```
TestImportFailure.chpl:5: In function 'test':
TestImportFailure.chpl:7: error: unresolved call 'canResolve("foo")'
TestImportFailure.chpl:7: note: because no functions named canResolve found in scope
```

This alternative way of writing it does work, but isn't ideal because it imports all of `Reflection`:

```chapel
proc foo() {
  writeln('foo');
}

proc test(param x=1) {
  import Reflection;
  if Reflection.canResolve('foo') then
    foo();
}
test();
```

**Comment by bradcray** [comment]
This one is weird to me.  Any idea whether it's specific to `Reflection` or that's just the case where a bug was hit and it applies to other overload situations as well?  Or what characterizes the failure mode?

**Comment by lydia-duncan** [comment]
The function itself is fine if the arguments are not generic, having a generic argument causes us to fail to find the function we've imported.  It might be that something is not getting copied when we instantiate the function

**Comment by lydia-duncan** [comment]
It appears to be specific to function calls, but not to importing from the Reflection module.

This code also fails in the same way:
```chapel
module callInGeneric {
  proc foo() {
    writeln('foo');
  }

  proc test(param x=1) {
    import this.Other.blah;
    if blah() then
      foo();
  }
  test();

  module Other {
    proc blah() {
      return true;
    }
  }
}
```

But this one is fine:
```chapel
module callInGeneric {
  proc foo() {
    writeln('foo');
  }

  proc test(param x=1) {
    import this.Other.blah;
    if blah then
      foo();
  }
  test();

  module Other {
    var blah = true;
  }
}
```
