### ISSUE TITLE
Trouble building Chapel 1.23

### ISSUE THREAD

**Issue by hpbrewton** [chapel-lang/chapel#16601]
I downloaded Chapel 1.23. Following the install instructions, I ran `source util/quickstart/setchplenv.bash`. This failed however, as the quickstart directory is missing. I also went through the fully-featured Chapel build, and after running `source util/setchplenv.bash`, I got that `chapel-1.23.0/util/config/fixpath.py` is not found.

It seems there is either an error in the new Chapel 1.23 package, or there is an error in the build instructions for it.

**Comment by ben-albrecht** [comment]
@hpbrewton - Which link did you use to download the release?

For example, the following should work:

```sh
wget https://github.com/chapel-lang/chapel/releases/download/1.23.0/chapel-1.23.0.tar.gz
tar xf chapel-1.23.0.tar.gz
cd chapel-1.23.0
source util/quickstart/setchplenv.bash
make
make check
```

**Comment by bradcray** [comment]
I just checked my download, and it has these files as well.  In addition to Ben's question wondering how you downloaded it, I'd be curious what toolchain you used to unpack it?

**Comment by hpbrewton** [comment]
I grabbed it from the Chapel home page, but used different flags for `tar`, which I suspect to be my problem.

Either way, I was able to get `chapel` up and running. Thank you for the help.

**Comment by bradcray** [comment]
Glad you were able to get past this, and thanks for letting us know.
