### ISSUE TITLE
Wrapping an iterator into an array crashes the compiler

### ISSUE THREAD

**Issue by pintarj** [chapel-lang/chapel#16621]
### Summary of Problem

``` console
$CHPL_HOME/modules/internal/ChapelBase.chpl:983: internal error: RES-FUN-ION-9910 chpl version 1.22.1
Note: This source location is a guess.

Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug -- 
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.
```

### Steps to Reproduce

Just compiling it.

**Source Code:**

```chapel
const result = ["hello".items()];
```

**Compile command:**
```bash
chpl src/chapel-bug.chpl
```

### Configuration Information

- Output of `chpl --version`:
```console
chpl version 1.22.1
Copyright 2020 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)
```

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:

```console
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: none
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_LLVM: llvm
CHPL_AUX_FILESYS: none
```

- Back-end compiler and version, output of `gcc --version`:

```console
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by e-kayrakli** [comment]
Hi @pintarj -- what is the behavior you want to get from that code? If it is to store each yielded item in an array like `["h", "e", "l", "l", "o"]`, then what you need is:

```chapel
const result = "hello".items();   // no need for square brackets
                                 // just assigning an iterator to a `var` or `const` will create an array
```

If you want a different behavior, could you clarify? I can think of few alternative behaviors (array-of-array literals where inner arrays are captured from an iterator or creating an iterator array) but none is supported AFAIK, at least not today. 

I agree that, at the very least, the compiler should have produced a better error message in your case.

**Comment by pintarj** [comment]
Hi @e-kayrakli, my original problem was exactly what you firstly guessed, reading the documentation I already found out the solution you posted, but I decided to open an issue because the compiler wrote _"We would appreciate your reporting this bug"_.

And yes, I was also wondering if there is a way of creating an array of iterators, thank you for clarifying that.

**Comment by e-kayrakli** [comment]
Thanks for checking @cassella! I also just confirmed that it works as expected today. I am closing this issue.

@pintarj Thanks for filing the bug report!

**Comment by cassella** [comment]
@e-kayrakli Do you know if there's a test locking it in?

**Comment by e-kayrakli** [comment]
@cassella -- Not off the top of my head. But it is a good idea to add the code in the OP as a test.
