### ISSUE TITLE
how should copy-initializing a list infer parSafe?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#16707]
When copy-initializing a list, should `parSafe` always be `false` if it is not set on the LHS? Or, should it be inferred from the RHS?

Currently it is inferred from the RHS in some cases but not others:

``` chapel

use List;

var y:list(parSafe=true, int);
y.append(1); y.append(2);
writeln("y:", y.type:string, " = ", y);

var d: list = y; // currently, infers parSafe=true from RHS
writeln("d:", d.type:string, " = ", d);

var g = y; // currently, infers parSafe=true from RHS
writeln("g:", d.type:string, " = ", g);

var i:list(int) = y; // currently, sets parSafe=false from list's default
writeln("i:", i.type:string, " = ", i);
```

Note that `parSafe` is a field with a default value.

Is the above behavior correct?

**Comment by dlongnecke-cray** [comment]
I think we should try to infer `parSafe` whenever possible, and if there are cases where we don't then it's probably due to an error on my part.

If enough people disagree with that interpretation I'd also be fine with just setting `parSafe` to `false` if it is not explicitly initialized.

**Comment by mppf** [comment]
I'm not quite sure how to implement infering it in the `var i:list(int) = y` case because of the way generics with defaults work, `list(int)` is a concrete type with `parSafe=false`. AFAIK we could continue to infer it for `var i:list(int, ?) = y` though.

**Comment by mppf** [comment]
Another question - since list has both `list.init(otherList)` and `list.init=(otherList)` - should we be inferring from the RHS list when the copy is made in a `new` ?

i.e.

``` chapel
use List;

var y:list(parSafe=true, int);
y.append(1); y.append(2);
writeln("y:", y.type:string, " = ", y);

var z = new list(y); // currently uses default argument parSafe=false. Should it infer instead?
writeln("z:", z.type:string, " = ", z);
```

**Comment by lydia-duncan** [comment]
Since we've decided to replace parSafe with a separate parallel list implementation, I'm inclined to close this.  But we could also leave it open until that replacement implementation is online, to make sure we remember.  Thoughts?

**Comment by mppf** [comment]
The corresponding question is, should the future parallel list be initializable from the serial list. I don't think that needs its own issue. I'll close this one.
