### ISSUE TITLE
Add datetime type method to get time since Unix epoch

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#16733]
We would like to deprecate `Time.getCurrentTime()` for `DateTime` functionality. However, there are 2 common use-cases of `getCurrentTime()` and one of them does not translate well to `DateTime`:

1. `getCurrentTime()` to get the hour, minute or seconds of the current time since midnight in local timezone. This required some additional effort on the user as pointed out in https://github.com/chapel-lang/chapel/issues/14571. `datetime.now()` should be much better for this use-case.

2. `getCurrentTime()` to get timestamps throughout a program for timing purposes. This is not recommended, because `getCurrentTime()` is time since midnight and the time could roll into the next day between time stamps. However, many codes use it for this purpose. One can translate their `getCurrentTime()` call to `(datetime.now() - datetime.now().replace(hour=0,minute=0,second=0,microsecond=0)).total_seconds()` in the DateTime module, but this is (1) much more verbose, and (2) still prone to the day roll-over issue.

To better support use-case (2), I propose we add a DateTime function (perhaps a datetime type method) that returns the time since Unix epoch:

```chpl
// a better name might exist...
var t = DateTime.timeSinceEpoch();
writeln(t); // 1605632958
```

This feature is already available in the DateTime internals, but simply needs to be exposed through a nice interface.

Eventually, we'd want a true monotonically increasing clock feature (https://github.com/chapel-lang/chapel/issues/7536). However, this will likely be a longer term effort.

**Comment by GGSheridan** [comment]
Should this issue be labeled as Good First Issue?

We are doing research about how to help newcomers onboarding in an open source project and how to accelerate the issue resolving process.
We have developed a tool to automatically label the Good First Issue (GFI), i.e., the issue which is good for newcomers. 
We first extract 72 features from different dimensions of issue reports, such as readability, semantic meaning, associated code snippets, etc, and experimentally investigate to what extent these features correlate with GFI. Results turn out that a large portion of these features do have a medium to large correlation with GFI. 
We then build a machine learning model based on these features to predict GFI. The experiments on a dataset of 12k issues from Github show that 0.90 AUC can be achieved. 

Our tool shows that this issue has a very large possibility to be a GFI. 
Could you please tell us whether it should be labeled as a GFI?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.

**Comment by bradcray** [comment]
@GGSheridan: Interesting project!

I think that this could conceivably be considered a "good first issue", though one subtlety which may be challenging for some first-time contributors is that it involves a design discussion.  That is to say, @ben-albrecht has proposed something here that others may agree or disagree with, and the first step to tackling this issue would be to ensure there's sufficient consensus for proceeding with the proposed design (which involves kicking off a discussion and getting people involved in it).  For some, this is not a challenge; for others just looking for some code to write and put into a PR, it may prove daunting.  I suspect that this is why @ben-albrecht didn't apply the label from the outset, but am uncertain.  Ben?

**Comment by ben-albrecht** [comment]
Assuming buy-in from core devs on the design, this could be considered a good first issue or easy/straightforward. I've pointed @king-11 here, so they may take a shot at it if they are interested.

**Comment by king-11** [comment]
@ben-albrecht Yeah I will start working on this issue

**Comment by ben-albrecht** [comment]
@king-11 - Sounds great. As a pointer, there are several uses of unix epoch time within the DateTime module already, so this task should mostly be a matter of building a clean interface (as described in the issue) to that functionality.

**Comment by ben-albrecht** [comment]
I'll also ping @daviditen (DateTime module author), in case he has any suggestions or if questions come up that he is better equipped to answer than myself.

**Comment by king-11** [comment]
@ben-albrecht is there something wrong with the PR I made 😓  ?

**Comment by daviditen** [comment]
As a point of comparison, in python this functionality is implemented as a method on a datetime object and returns the time since Unix epoch that that object represents.

```python
>>> dt = datetime.datetime.now()
>>> dt.timestamp()
1616617831.382333
```

**Comment by king-11** [comment]
attaching it with ```datetime``` object will be more useful as for current  ```datetime.now()``` will be there to return ```timeSinceEpoch```.
