### ISSUE TITLE
Module-scope variables are not shadowed consistently

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#16743]
As @vasslitvinov pointed out in [this comment](https://github.com/chapel-lang/chapel/issues/16716#issuecomment-729290517) on issue #16716, we currently don't introduce shadow variables for module-scope variables for `coforall` loops as we do for `forall` loops.  Here's the test he used to demonstrate this:

```chapel
module Lib {
  var globalLib = 10;
  proc updateLib() { globalLib += 1; }
}

module Main {
  use Lib;
  var s$: sync int;
  var globalMain = 20;
  proc updateMain() { globalMain += 1; }

  proc main {
    coforall 1..2 {
      s$ = 1; // grab the lock
      writeln("globaLib   = ", globalLib);
      writeln("globalMain = ", globalMain);
      updateLib();
      updateMain();
      s$;
    }
  }
}
```

where the output is:

```
globaLib   = 10
globalMain = 20
globaLib   = 11   // should be 10
globalMain = 20
```

However, if the `coforall` is changed to `forall`, we get the expected result.

**Comment by bradcray** [comment]
@vasslitvinov: It didn't occur to me to ask this earlier, but:  Do you know why it is that `forall` and `coforall` behave differently in this respect?  Does `forall` use something other than `isOuterVar()`?

**Comment by vasslitvinov** [comment]
> Does forall use something other than isOuterVar()?

Right now we have four versions of isOuterVar(). Task-parallel constructs use the one in createTaskFunctions.cpp. Foralls use the one in implementForallIntents.cpp, called isOuterVarNew. The latter does not have the flaw present in the former.

**Comment by vasslitvinov** [comment]
I have a fix for this issue.

Unfortunately, some "locale private" variables now become shadowed, resulting in remote locales accessing the value on the original locale and so breaking the intention of the "locale private" pragma.

I can merge my fix right away, adjusting it to exclude locale-private variables. Once we resolve #14143, we can modify this fix as needed.

Alternatively we can resolve #14143 first, then merge my fix.

Suggestions?

**Comment by bradcray** [comment]
> Right now we have four versions of isOuterVar().

Is this because they need to differ from one another in some way, or because we've accidentally written the same logic four times?  Does your fix merge any that can be?

> I can merge my fix right away, adjusting it to exclude locale-private variables.

If that fixes the user-facing behavior and doesn't break other cases, I think that sounds like a worthwhile improvement without settling #14143.
