### ISSUE TITLE
Build failure in third-party/libfabric with Apple Xcode 12.x

### ISSUE THREAD

**Issue by PHHargrove** [chapel-lang/chapel#16759]
In Xcode 12.x, Apple has decided to default to `-Werror=implicit-function-declaration`, making the C compiler behave as strictly a C++ compiler would when calling an unprototyped function.  This behavior is contributing to the following build failure on master at e27061cf

```
/[path redacted]/chapel/third-party/libfabric/libfabric-src/prov/util/src/util_shm.c:81:8: error: implicit declaration of function 'ofi_process_vm_writev' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        ret = ofi_process_vm_writev(peer_smr->pid, &local_iov, 1,
              ^
1 error generated.
make[7]: *** [prov/util/src/src_libfabric_la-util_shm.lo] Error 1
```

See [this page](https://upc-bugs.lbl.gov/upc_tests/showlog.php?date=2020-11-19&config=EX-catalina-smp-clang-pthr&opt=dbg&log=chapel) for more details about the failing build.

CC: @bonachea

**Comment by ronawho** [comment]
Thanks @PHHargrove. I think we introduced a bug this week where libfabric is getting built all the time, even though it should only be with `CHPL_COMM=ofi`.

cc @gbtitus because the build failure is interesting and is something I think we want to fix for CHPL_COMM=ofi builds. (I'll see if I can repro and will see if upgrading libfab versions resolves this)

cc @daviditen for the bug with building libfabric when we shouldn't be.

**Comment by gbtitus** [comment]
Although we shouldn't be building libfabric in the configuration at hand, in addition to working around the failure in the libfabric build we should open a libfabric Issue for it.

**Comment by ronawho** [comment]
I'll check if the latest libfab versions have already fixed this before filing an issue.

**Comment by ronawho** [comment]
@daviditen has the issue with building libfabric when we shouldn't be been resolved?

**Comment by daviditen** [comment]
Yes, the issue about building libfabric when we shouldn't should be resolved.

**Comment by bradcray** [comment]
Looking through open issues from @PHHargrove, I came across this.  @gbtitus and @jhh67, has your recent portability work on Macs (or mine) indicated that we're past this now, thanks to libfabric upgrades?

**Comment by gbtitus** [comment]
> ... has your recent portability work on Macs (or mine) indicated that we're past this now, thanks to libfabric upgrades?

I'll defer to @jhh67 on this, since he's working on the upgrade to libfabric 1.12.

**Comment by jhh67** [comment]
> > ... has your recent portability work on Macs (or mine) indicated that we're past this now, thanks to libfabric upgrades?
> 
> I'll defer to @jhh67 on this, since he's working on the upgrade to libfabric 1.12.

Libfabric 1.12.1 fixes this build problem, but it introduces other problems that I need to solve.

**Comment by ronawho** [comment]
@jhh67 was the issue that ofi was finding your touchbar from https://github.com/chapel-lang/chapel/pull/18241? If so, can this be closed now?

**Comment by jhh67** [comment]
Libfabric 1.12.1 fixed the problem with the implicit function declaration.
