### ISSUE TITLE
file.getParentName should be renamed

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#16755]
In the Path module we have `file.getParentName` and `dirname` that are
functionally the same. We should rename `file.getParentName` to `file.dirname`.

Note that we might want to hold off on this until we reach a consensus on
https://github.com/chapel-lang/chapel/issues/16748

**Comment by king-11** [comment]
@e-kayrakli I think consensus was reached on #16748 so can we work on this now?

**Comment by e-kayrakli** [comment]
In #18009, we have deprecated `file` methods in the `Path` module in favor of free functions that take `file` arguments. However, getParentName is completely deprecated, and the users can use `dirname(realPath(file))` etc to achieve the same behavior.
