### ISSUE TITLE
Should we add replacement functions to the Path module?

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#16767]
The Path module has functions to make basic low-level transformations on paths. However, there's no function for replacing parts of a path string, and the user would have to use string functions (slice, concat etc) to achieve that.

Python's `os.path` doesn't have such functions, but higher-level `pathlib` does have some methods to call on Path objects: https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.with_name

I think we should add some replacement functions to the Path module. I suggest the following:

- `replaceDirname(path, newDirname)` (or `replaceDirName`: see https://github.com/chapel-lang/chapel/issues/16764)
- `replaceBasename(path, newBasename)` (or `replaceBaseName`: see https://github.com/chapel-lang/chapel/issues/16764)
- `replaceExt(path, newExt)` (see https://github.com/chapel-lang/chapel/issues/16766)

One design question about them would be what happens if the path doesn't have dirname, basename, or extension. We can adopt pathlib's naming scheme, e.g. `withDirname`, `withBasename` etc, that would add the given part if it doesn't exist and replace if it does.

**Comment by king-11** [comment]
@e-kayrakli I would like to work on this issue is no one else is currently working on it .

**Comment by king-11** [comment]
I had a basic implementation of ```replaceDirname``` and ```replaceBasename``` ready but for ```replaceExt``` I was using ```splitExt``` but am getting an undefined call to function 🤔 not able to proceed further because of it.

**Comment by e-kayrakli** [comment]
Hi @king-11 -- Thanks for the effort! Few things to note:

- We are in the process of getting our next release out the door, so it is a bit busy for the developers these days.
- I would like to get more consensus from other developers, too, before adding this to the Path module. Though, I don't see too much controversy here (having a thumbs-up from @lydia-duncan is a good sign :) ). There might be some questions as to whether this needs to go to the standard Path module or should it be in a Package/Mason module that has more "advanced" operations on paths. I'd be happy to bring this to rest of the team's attention sometime next week when things are a bit calmer.
- As for the `splitExt` issue, are you using the `master` branch? `splitExt` is a function that was added very recently: https://github.com/chapel-lang/chapel/pull/17247

**Comment by king-11** [comment]
Yes I have update my branch with master 
```chapel
import Path.{splitPath,joinPath,splitExt};

writeln(splitExt("/bar/foo/"));
```
I am getting this error even though I checked the ```Path``` Module and ```splitExt``` is present in it synced with master.
```error: Bad identifier, no known 'splitExt' defined in 'Path'```

**Comment by lydia-duncan** [comment]
Does your $CHPL_HOME match the repository where you pulled in the new changes to master?

**Comment by lydia-duncan** [comment]
At least one of the versions you wrote in your comment is covered by a test in the testing system, so I think this is likely to be a configuration issue on your end.

**Comment by king-11** [comment]
@lydia-duncan I will try configuring my Chapel again and let you know with the implementation might have messed up the config I guess 😅

**Comment by king-11** [comment]
Got It working after a bit of cleanup I had a doubt about ```replaceExt``` shall we raise an error in absence of file/extension in the original Path because for the other two functions we can just join the paths as said by @e-kayrakli and replace or add the new dirname/basename

**Comment by e-kayrakli** [comment]
As I have alluded to in the OP, we might want to have `withExt` instead of `replaceExt` to make any behavior around those edge cases cleaner:

> One design question about them would be what happens if the path doesn't have dirname, basename, or extension. We can adopt pathlib's naming scheme, e.g. withDirname, withBasename etc, that would add the given part if it doesn't exist and replace if it does.

As you suggest we might want to have `replace*` but in case the relevant part doesn't exist throw.

There's also a solution in between these two: name the functions `replace*`, but make them add the relevant part if it doesn't exist.

**Comment by king-11** [comment]
So in the case of ```replaceDirname``` and  ```replaceBasename``` we can add the relevant part if it doesn't exist or replace it if it does and in case of ```replaceExt``` in absence of a basename we throw but if we have a basename then we either add the ext or replace. 

I will start on this implementation any changes that you might want to suggest @e-kayrakli @lydia-duncan .

**Comment by e-kayrakli** [comment]
I haven't really considered the case with `replaceExt("/foo/bar/", "txt")` where there's no basename. What you suggested makes sense to me but it requires more discussion, that I doubt will happen today because of the release crunch, as I mentioned :) I'm planning to follow up on those details some time next week.

**Comment by king-11** [comment]
😁 sure got the point I will be patient and till then work on other semantics

**Comment by king-11** [comment]
@e-kayrakli I have created a Draft PR can you please provide the design changes needed whenever you get time so I can change it to PR for Review.

**Comment by king-11** [comment]
@e-kayrakli any further updates on this 😓 hope am not being impatient.

**Comment by e-kayrakli** [comment]
@king-11 -- thanks for reminding me this.

In the OP I proposed we add the following:

- `replaceDirname(path, newDirname)` (or `replaceDirName`: see https://github.com/chapel-lang/chapel/issues/16764)
- `replaceBasename(path, newBasename)` (or `replaceBaseName`: see https://github.com/chapel-lang/chapel/issues/16764)
- `replaceExt(path, newExt)` (see https://github.com/chapel-lang/chapel/issues/16766)

This comment asks specific design questions and proposes answers.

### 1. Function names

#### 1.a. The action: `replace` vs `with`
The main inspiration for these is from Python's [pathlib](https://docs.python.org/3/library/pathlib.html). But there, the names are `with_basename`, `with_dirname` and `with_suffix`. Where "with" signifies that it can also add the relevant part to the path if it doesn't exist (at least that's my interpretation)

I propose we use "replace". I like that it is a verb. In cases where the relevant part doesn't exist we can think of these function as if they are replacing an empty string (see question 2). I don't feel too strongly about this, however.

#### 1.b. The name: `Ext` vs `Suffix` vs `Extension`
I propose we use `Ext` as short for "extension". We already have a `splitExt` based on `os.path`'s `splitext`.

### 2. Behavior if the part doesn't exist

I propose these functions should add that part as it would make them more useful in general. That behavior could be interpreted as replacing an empty string.

Specifically, I propose:
```chapel
replaceBasename("/foo/bar/", "baz");   // the original path doesn't have a basename. returns "/foo/bar/baz"
replaceDirname("foo", "bar"); // the original path doesn't have a dirname. returns "bar/foo"
replaceExt("foo", ".txt"); // the original path doesn't have an extension. returns "foo.txt"
```

### 3. Should `replaceExt` require "." in the extension argument?

I propose it shouldn't. pathlib's `with_suffix` requires the argument to have "." and throws an error if it doesn't. It may have something to do with OS portability. I am not sure if we should follow that precedent.

```chapel
replaceExt("foo.bar", "txt");  // I think this should be fine and should return "foo.txt"
```

### 4. `replaceExt` behavior if there's no basename

I propose it should throw.

```chapel
replaceExt("/foo/", "txt");  // this should throw an error.
```

The alternative would return `/foo/.txt` in the case above, which isn't a file a with `.txt` extension.

**Comment by king-11** [comment]
@e-kayrakli for the ```replaceBasename``` and ```replaceDirname``` I did implement the functions work as you suggested. Regarding the ```replaceExt``` should it throw an error if the extension is something like ```.txt```.

**Comment by e-kayrakli** [comment]
> @e-kayrakli for the replaceBasename and replaceDirname I did implement the functions to work as you suggested. Regarding the replaceExt should it throw an error if the extension is something like .txt.

I think that should also work fine and replace the extension as expected. I updated my detailed proposal above. (See question 3)

**Comment by mppf** [comment]
@e-kayrakli I'm happy with the proposal above with one exception

> 1.a. The action: replace vs with

I am a bit worried about `replace` because it makes it sound like it modifies the path in-place (rather than returning a new string). On the other hand, we already have `string.replace` which works this way.

**Comment by e-kayrakli** [comment]
> I am a bit worried about replace because it makes it sound like it modifies the path in-place (rather than returning a new string). On the other hand, we already have string.replace which works this way.

I haven't thought about it and it is a good point. I personally think following the precedence of `string.replace` is the right direction for this design even if it might be somewhat misleading.

**Comment by king-11** [comment]
@mppf that certainly seems so and to end-user it might seem like a function with ref intent but  can we think of a better suitable name for the current implementation stands the question because something like ```amend``` or ``update``` would come under similar ideas as ```replace``

**Comment by bradcray** [comment]
I'm coming at this with no experience with the relevant Python routines and am generally on-board with the proposal.  In this example from Engin's comment:

> ```chapel
> replaceDirname("foo", "bar"); // the original path doesn't have a dirname. returns "bar/foo"
> ```

...what is it that makes "foo" get interpreted as an extension-free filename rather than a filename-free relative path?  Is the convention that any final name in the string is a filename if it isn't followed by "/"?

**Comment by e-kayrakli** [comment]
> Is the convention that any final name in the string is a filename if it isn't followed by "/"?

That's right.

```chapel
import Path;

writeln("dirname(foo): ", Path.dirname("foo"));
writeln("basename(foo): ", Path.basename("foo"));
writeln("dirname(foo/): ", Path.dirname("foo/"));
writeln("basename(foo/): ", Path.basename("foo/"));
```

prints out:

```
dirname(foo):
basename(foo): foo
dirname(foo/): foo
basename(foo/):
```
