### ISSUE TITLE
Suffix function(s) in the Path module

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#16766]
Currently the Path module doesn't have a support for querying the suffix of a file. At least we should have a function that returns the suffix from a path.

Python's `os.path` has `splitext`:

```python
>>> from os.path import splitext
>>> splitext("foo")
('foo', '')
>>> splitext("foo.tmp")
('foo', '.tmp')
>>> splitext("bar/foo.tmp")
('bar/foo', '.tmp')
>>> splitext("bar/foo.tmp.tmp2")
('bar/foo.tmp', '.tmp2')
```

Following the `os.path` naming and our camelCasing for most of the inherited function names, we should probably add something like `splitExt`.

**Comment by bradcray** [comment]
I was wondering about this as well yesterday, but didn't bring it up since we were already overtime and it's not a breaking change.

**Comment by lydia-duncan** [comment]
I definitely like `splitExt` better than `splitext`, I didn't even know how to divide that word

**Comment by Yudhishthira1406** [comment]
@e-kayrakli I would like to work on this issue.
Thanks!
