### ISSUE TITLE
Examples compilation failures on master

### ISSUE THREAD

**Issue by PHHargrove** [chapel-lang/chapel#16778]
Somewhere between success on master at 2b7fddc5 and a recent failure at 65f97bca, something changed to produce the following messages when building examples:

```
cd /home/data2/upcnightly/dirac/EX-dirac-ibv-clang_CX5/work/dbg/chapel && . util/setchplenv.bash && cd /home/data2/upcnightly/dirac/EX-dirac-ibv-clang_CX5/work/dbg/gasnet/tests/upcr-harness/external-chapel && \
  env PATH=$PATH CHPL_COMM_DEBUG=1  \
    /usr/bin/gmake -C /scratch/upcnightly/EX-dirac-ibv-clang_CX5/runtime/bld/dbg/chapel/examples hello6-taskpar-dist CHPL_FLAGS+="" 2>&1
Setting CHPL_HOME to /home/data2/upcnightly/dirac/EX-dirac-ibv-clang_CX5/work/dbg/chapel
Updating PATH to include /home/data2/upcnightly/dirac/EX-dirac-ibv-clang_CX5/work/dbg/chapel/bin/linux64-x86_64
                     and /home/data2/upcnightly/dirac/EX-dirac-ibv-clang_CX5/work/dbg/chapel/util
Updating MANPATH to include /home/data2/upcnightly/dirac/EX-dirac-ibv-clang_CX5/work/dbg/chapel/man
gmake[3]: Entering directory `/scratch/upcnightly/EX-dirac-ibv-clang_CX5/runtime/bld/dbg/chapel/test/release/examples'
chpl -o hello6-taskpar-dist hello6-taskpar-dist.chpl
/home/data2/upcnightly/dirac/EX-dirac-ibv-clang_CX5/work/dbg/chapel/make/Makefile.base:183: /home/data2/upcnightly/dirac/EX-dirac-ibv-clang_CX5/work/dbg/chapel/third-party/llvm/Makefile.include-none: No such file or directory
make[4]: *** No rule to make target `/home/data2/upcnightly/dirac/EX-dirac-ibv-clang_CX5/work/dbg/chapel/third-party/llvm/Makefile.include-none'.  Stop.
error: compiling generated source
gmake[3]: *** [hello6-taskpar-dist] Error 1
```

Log of last known-good configure/build/install: [here](https://gasnet-bugs.lbl.gov/upc_tests/showlog.php?date=2020-11-20&opt=dbg&config=EX-dirac-ibv-clang_CX5&log=chapel)  
Log of first known-bad configure/build/install: [here](https://gasnet-bugs.lbl.gov/upc_tests/showlog.php?date=2020-11-22&opt=dbg&config=EX-dirac-ibv-clang_CX5&log=chapel)  

cc: @bonachea

**Comment by bradcray** [comment]
Thanks for making sure we were aware of this Paul—we're seeing similar failures in our nightly testing.  Most of the team (including those who merged and reviewed the PR that broke it) are out this week and those of us who remain have been wrestling with what's breaking and why.  We believe that it should be fixed as of https://github.com/chapel-lang/chapel/pull/16779 (our testing resolved) but please let us know if you find that not to be the case.

**Comment by PHHargrove** [comment]
Thanks, @bradcray.  
Indeed our tests last night ran against c5ea3fae (the merge commit of #16779) without problems.

**Comment by bradcray** [comment]
Thanks for confirming, and again for making sure we were aware of this.
