### ISSUE TITLE
Tasks assigned in standalone forall loop when number of tasks is more than probSize (in the code attached) is highly biased, since only one task gets assigned with full problem set and the rest of the tasks do not get anything assigned to them.

### ISSUE THREAD

**Issue by rchinmay** [chapel-lang/chapel#16795]
### Summary of Problem

In the Parallel iterators primers, the example of count iterator using standalone approach are explained. I was trying some variants of the code given in that section. I fixed numTasks=4 which was equal to here.maxTaskPar value, and then tried different values of probSize. It works very well for probSize>=numTasks. For example when numTasks=4 and probSize=15, then the output on my device looks like:
In count() standalone, creating 4 tasks
task 3 owns 10..15
task 0 owns 1..3
task 1 owns 4..6
task 2 owns 7..9
But when numTasks>probSize, then only one task gets assigned with full probSize and the rest of the tasks do not get anything assigned. I do not feel this is the right way. I know that some of the tasks created can go empty, but others tasks should own problem size of 1. For example, when numTasks=4 and probSIze=3, the output on my device looks like:
In count() standalone, creating 4 tasks
task 3 owns 1..3
task 0 owns 1..0
task 2 owns 1..0
Also, when numTasks=10 and probSize=5, by compiling using the command $chpl Chapel_Program.chpl -snumTasks=10 -sprobSize=5, then the output looks like:
In count() standalone, creating 10 tasks
task 1 owns 1..0
task 0 owns 1..0
task 9 owns 1..5
task 2 owns 1..0
task 4 owns 1..0
task 6 owns 1..0
task 3 owns 1..0
task 7 owns 1..0
task 8 owns 1..0
I feel the best way is to give (numTasks-probSize) tasks as empty and the rest each owning 1 problem of the probSize. But if my opinions and suggestions are wrong, then please inform me.

### Steps to Reproduce:
I used chpl version 1.22.0, and have not shifted to chpl version 1.23 yet. If this does not produce such behaviour in the newer versions, then it is not a problem.
** Source Code **
[Chapel_Program.txt](https://github.com/chapel-lang/chapel/files/5614831/Chapel_Program.txt)

** Compilation Command **
chpl Chapel_Program.chpl 

** Execution Command **
./Chapel_Program

###Configuration Information:
Output of chpl --version: chpl version 1.22.0
Copyright 2020 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)

Output of $CHPL_HOME/util/printchplenv --anonymize:
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: fifo *
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: cstdlib *
CHPL_ATOMICS: cstdlib
CHPL_GMP: none *
CHPL_HWLOC: none
CHPL_REGEXP: none *
CHPL_LLVM: none *
CHPL_AUX_FILESYS: none

Back-end compiler and version, e.g. gcc --version:
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by bradcray** [comment]
@rchinmay — To make sure I'm understanding properly, it seems as though this is an issue with the logic of the `computeChunk()` routine in your code / the parIters primer rather than anything in the definition of parallel iterators or the implementation of the language itself, is that right?  That is, if computeChunk() were written to return different ranges for the cases when the number of tasks exceeded the number of iterations, the behavior would be as expected?

I agree that an implementation of computeChunk in which each task got 1 or 0 iterations would be more intuitive when the number of tasks exceeded the number of iterations.

**Comment by rchinmay** [comment]
@bradcray I now understand that the skewed assignment to parallel tasks was because of the computeChunk() procedure. I tried to modify it a bit and understood that my desired output is achievable. I replaced the computeChunk() function with the code below and it works fine. 
```
proc computeChunk(r: range, myChunk, numChunks) where r.stridable == false {
  const numElems = r.size;
  const elemsperChunk= numElems/numChunks;
  const rem= numElems%numChunks;
  var mylow= r.low;
  if(myChunk<rem){
    mylow+=(elemsperChunk+1)*myChunk;
    return mylow..#(elemsperChunk + 1);
  }
  else{
    mylow+=((elemsperChunk+1)*rem + (elemsperChunk)*(myChunk-rem));
    return mylow..#elemsperChunk;
  }
} 
```
It works fine with almost equal division of problem size to each task. I understand that this is not a bug in the language or the parallel iterators primer. This computeChunk() method seems more intuitive to me, but the one given in primer is simpler.  Since there were no changes to be made in docs or the source code, I am closing this issue. 
Thanks.

**Comment by bradcray** [comment]
Great, thanks for confirming, @rchinmay!

I was thinking more about how `computeChunk()` might be re-written to address your concern last night and came up with something very similar to your approach.  If you'd like to submit your change as a PR against the primer to avoid that corner case for future readers, I think that'd be a nice change (be sure to read https://github.com/chapel-lang/chapel/blob/master/.github/CONTRIBUTING.md if you are interested in contributing it and aren't already familiar with its contents).  If not, I'll try to find the time to add my own version.

**Comment by rchinmay** [comment]
@bradcray I will be very happy to contribute. This is the first time I am opening PR, so it may take some time for me to understand the processes involved. Positively, by tomorrow, I will open a PR and tag it here. Also, should I reopen this issue or will we continue any further discussion in the PR?
Thanks

**Comment by bradcray** [comment]
We can just focus on the PR, thanks.  And no need to rush on my account.

**Comment by rchinmay** [comment]
I am extremely sorry for the delayed PR. Please review the changes.
Thanks.

**Comment by bradcray** [comment]
Hi @rchinmay — There's no need to apologize for voluntarily contributing code!  I'm afraid that we are all on a shutdown for the holidays right now, but we'll take a look in the new year.  Thanks!

**Comment by rchinmay** [comment]
@bradcray, Thanks for confirmation. I am fine if the PR gets reviewed after the new year. 
Thanks.
