### ISSUE TITLE
Feature request : should/Could Chapel support atomic(complex)?

### ISSUE THREAD

**Issue by npadmana** [chapel-lang/chapel#16793]
Currently, Chapel does not appear to support atomic complex variables 
```
var x : atomic(complex);
```
fails with 
```
foo.chpl:1: error: Unsupported atomic type: complex(128)
```
Would it be possible to extend Chapel to support complex atomic variables?

**Comment by ronawho** [comment]
This is an interesting idea, but would be hard to implement efficiently. What types of atomic operations would you want to be supported? Do you have a more concrete example to look at?

There's some prototype work in https://github.com/chapel-lang/chapel/blob/master/modules/packages/AtomicObjects.chpl to support 128-bit atomics, but generally speaking not all CPUs support 128-bit atomics, and most NICs do not. Even if the CPU supports 128-bit atomics I think it's usually just CAS, so we'd have to implement any other operations with a CAS-loop. And if the CPU doesn't support 128-bit ops you're falling back to a lock.

Our atomics are heavily modeled after C11/C++11, and they do not support this. C++20 added support for
arithmetic operations on float/double (which we have had, but C++ did not), but I don't remember seeing any discussion about adding atomic complex in the proposals for that. That said I don't keep up with C++ that well, but at least in the few proposals I read for adding atomic floats, I didn't see anything about adding complex too. 

Probably obvious, but I'm not enthusiastic about adding atomic complex. That said I would be interested in the use-case/motivation to see if that changes my stance.

**Comment by bradcray** [comment]
Beyond the 128-bit issues Elliot points out (which wouldn't apply to a `complex(64)` value), there's a related question in my mind about the granularity of atomicity given that complex is effectively a two-field value and some operations (e.g., `*` and `/`) rely on multiple reads/writes of the real and imaginary portions to modify each.  Which is not to say that it's not possible or attractive, simply that it'd be fairly different than atomic operations on singleton values like `int` or `real`.  These issues make me nervous about supporting these as well, but like Elliot, I'm open to convincing.

**Comment by npadmana** [comment]
Thanks! I think both @ronawho and @bradcray's arguments largely convinced me that the answer here is no. The particular use case I had was accumulating (adding) from a complex grid onto an array, which is just as easy to do by separately keeping track of the real and imaginary parts (which is what I did).

**Comment by npadmana** [comment]
What might be more attractive as a generic feature would be the equivalent of OpenMP's critical blocks, which would avoid the user having to write manual locks. I think this existed in an early version of the Chapel spec (as an `atomic` block), although I don't think it ever was implemented. I'm not sure I know the arguments for/against this, but that discussion is orthogonal to this.

**Comment by bradcray** [comment]
Yeah, the more general `atomic` block concept (or maybe even a simpler "critical section" block?) would be other ways to tackle this.  Getting general atomic blocks working properly is a pretty heavily lift.  A critical section block is a lighter lift, but has the potential to cause deadlocks if not used appropriately (e.g., if one were to block on something within a critical section).
