### ISSUE TITLE
Sort only accepts arrays with domains defined by int(64) types

### ISSUE THREAD

**Issue by redhatturtle** [chapel-lang/chapel#16801]
### Summary of Problem
Calling the sort procedure on an array with an associated domain defined by int(32), uint(64), etc results in compilation error.
Changing the the variable size type to int(64) or casting it explicitly at the array declaration solves the issue.

### Steps to Reproduce

**Source Code:**

```chapel
proc main(){
  import Sort.sort;

  var size : uint(32) = 3;
  var array : [1..size] real = [3,1,2];

  sort(array);
  writeln(array);
}
```

**Error Message**

```
chpl test.chpl
$CHPL_HOME/modules/packages/Sort.chpl:455: In function 'sort':
$CHPL_HOME/modules/packages/Sort.chpl:459: error: unresolved call 'unmanaged DefaultAssociativeDom(uint(32),true).dsiLow'
$CHPL_HOME/modules/internal/DefaultRectangular.chpl:577: note: this candidate did not match: DefaultRectangularDom.dsiLow
$CHPL_HOME/modules/internal/ChapelArray.chpl:1770: note: because method call receiver with type unmanaged DefaultAssociativeDom(uint(32),true)
$CHPL_HOME/modules/internal/DefaultRectangular.chpl:150: note: is passed to formal 'this: domain'
$CHPL_HOME/modules/internal/ChapelDistribution.chpl:616: note: candidates are: BaseSparseDom.dsiLow
  test.chpl:7: called as sort(Data: [DefaultAssociativeDom(uint(32),true)] real(64), comparator: DefaultComparator)
note: generic instantiations are underlined in the above callstack

```

**Comment by bradcray** [comment]
Hi @redhatturtle — Thanks very much for reporting this.  I've taken a quick look to see whether it's a 1-2 line change to fix, and it's not, though I haven't run into any significant issues other than making the routines more generic so far.  I'd be curious to know whether this is a blocking issue for you, or something that you just happened to run into and report.  Thanks again.

**Comment by bradcray** [comment]
Following up, it wasn't too much more work to get things working.  Here's a branch that fixes your small test case.  If you have more significant code that this was approximating, I'd be curious whether you see any additional issues:  https://github.com/chapel-lang/chapel/pull/16803

**Comment by redhatturtle** [comment]
Hey @bradcray, thank for the fast response. It's not a blocking issue and I was fine with bypassing it with some extra casting in one or two places.
Anyway it seems to be working on all the cases in the original code too for now. Again, thanks a lot!

**Comment by bradcray** [comment]
Thanks for verifying, @redhatturtle!  I'm going to keep this open until the PR is merged, just to avoid losing sight of it if something goes wrong with the PR in review and testing.

**Comment by bradcray** [comment]
@redhatturtle — Thanks again for reporting this.  The fix is merged to master now.

**Comment by redhatturtle** [comment]
Ah, thanks for letting me know and for the fix!
