### ISSUE TITLE
Should halt, exit, and assert be in a module named by topic?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#16808]
For https://github.com/Cray/chapel-private/issues/1215

Today:
 * `halt` is in "IO Support"
 * `exit` is in `Builtins`
 * `assert` is in `Builtins`

Should we migrate these to a new module that has a name based on this functionality, e.g. `ProgramTermination` or `Halts` ?

**Comment by bradcray** [comment]
One other routine that I mentally associate with this family is "warning()".  It's obviously slightly different in that, unlike these three, it doesn't terminate program execution.  But it does seem similar in that, when dealing with an erroneous condition, I typically go through a mental hierarchy of "is this something to warn about and then proceed in spite of, or something that should generate an error and cause the program to halt?"

**Comment by bradcray** [comment]
Brainstorming additional names:

* `Reporting`?
* `Diagnostics`?
* `WarningsErrorsExits`?
* `ErrorMessagesAndEarlyExits`?

I'm definitely flashing back to how we ended up with `Builtins`...  :)

Interestingly, if we were to remove `exit()` from this group, I think it'd be slightly easier to come up with a name that covers `warning`/`error`/`assert`.

As a minor observation, assuming this module continues to be auto-available (which I think we're in agreement on), we can give it a fairly ridiculous name and nobody will ever have to type it outside of the documentation.

**Comment by mppf** [comment]
> Interestingly, if we were to remove exit() from this group, I think it'd be slightly easier to come up with a name that covers warning/error/assert.

What names would these be? Maybe they are good enough, even though they don't describe exit exactly.

**Comment by bradcray** [comment]
Well things like `ErrorConditions` or `ErrorReporting` or `ErrorMessages` all describe those three pretty well where `exit` doesn't obviously fit in that category (unless you consider any form of early exit in Chapel to be an indication that something has gone differently than planned).

**Comment by mppf** [comment]
Could we put these things in `Errors` ?

**Comment by bradcray** [comment]
I'd been shying away from that because they felt of a fairly different "kind" than the contents of `Errors` today and I was worried that `Errors` was already a pretty huge file—but I think I was getting mixed up with `SysError`.  Opening it up, it doesn't seem like as bad an idea as I was imagining.

Do you consider the contents of `Errors` to be part of the language or the standard library?

**Comment by mppf** [comment]
> Do you consider the contents of Errors to be part of the language or the standard library?

Language, in my view.

**Comment by bradcray** [comment]
> Language, in my view.

So in the "plan A" doc refactoring, would you put all of these things in the spec?  (and if so, would you put all current auto-available standard library symbols there?)

**Comment by mppf** [comment]
> So in the "plan A" doc refactoring, would you put all of these things in the spec? (and if so, would you put all current auto-available standard library symbols there?)

Since we have an Error Handling chapter I think it would be reasonable to include the documentation contents of Errors.chpl there. It would make sense to me if that also included halt/exit/assert and compilerError etc. if these continue to be auto-available. It would also be OK to link to a module with the documentation if we have a reason to do so.

I don't think the spec needs to cover all auto-available standard library symbols, but we could take the approach that it should, in which case we would be able to pretty much ignore the names of the auto-included modules.

My own opinion is that Math and Types are relatively well defined (in terms of topic) and not so closely connected to questions the Spec talks about. As a result it makes sense to me to keep these two modules (at least) documented as "standard modules that are included by default".

**Comment by e-kayrakli** [comment]
If we move `halt` to a module, should that module also subsume the contents of `HaltWrappers`?

**Comment by bradcray** [comment]
That seems potentially attractive.  It's never been terribly clear to me whether HaltWrappers is intended for end-users, or was more like a helper module for our own sake to use consistent messages and such for things that are "provided".

**Comment by mppf** [comment]
FWIW I think it was intended to be something for our own use (so we can know that halts in the standard modules fit into acceptable categories). However I think it makes sense to expose it to users because it would be useful for people writing data structures with a low-level buffer etc.

**Comment by mppf** [comment]
I think my current favorite strategy is to move exit somewhere else (e.g. IO, POSIX, Core, CLibrary, ?) and then put everything else (compilerError/Warning/Assert, halt, warning, assert) into the existing Errors module.

**Comment by mppf** [comment]
In a separate conversation, we developed a plan to move these to an Errors module (along with halt, warning, assert, exit, and the current contents of ChapelError).
