### ISSUE TITLE
incremental docs build

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#16826]
Running `make docs` currently takes some time. However it's possible for it to be updated to be incremental.

`sphinx-build` is supposed to already be incremental by default with the version we have.

We generate `rst/{modules,builtins}` using chpldoc, then we copy in an index file from `rst/meta/{modules,builtins}`. These copies prevent `sphinx-build` from being incremental (since the files have been modified).

We could change these to a copy-only-if-modified strategy. But, then we'd still run chpldoc. We could update the chpldoc build to only update modules that were modified first if the chpldoc command is taking up a significant amount of time in `make docs`.

**Comment by mppf** [comment]
Perhaps `util/config/update-if-different` could help here.

It looks to me like by far most of the `make docs` build is in the `sphinx-build` (vs chpldoc).

**Comment by lydia-duncan** [comment]
> We could update the chpldoc build to only update modules that were modified first if the chpldoc command.

I think you missed something at the end of this sentence

**Comment by mppf** [comment]
thanks, fixed

**Comment by bradcray** [comment]
This sounds like a dream come true.

**Comment by mppf** [comment]
PR #16835 will do it but we need a change to sphinxcontrib-chapeldomain https://github.com/chapel-lang/sphinxcontrib-chapeldomain/pull/45
