### ISSUE TITLE
DateTime.strftime ignoring `%f` modifier

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#16834]
As [reported on Discourse](https://chapel.discourse.group/t/f-format-does-not-seem-to-work-with-datetime/2212), our `strftime()` routine does not recognize `"%f"` even though our pointer to the Python documentation implies that it probably should.  For example:

```chapel
use DateTime;
var now = datetime.now();
writeln(now.strftime("%H:%M:%S.%f"));
writef("%06i\n",now.microsecond);
```

prints:

```
18:47:11.%f
```

**Comment by bradcray** [comment]
@daviditen: @leekillough is looking for a bug to fix.  If you aren't working on this one, what would think about having him pick it up?

**Comment by daviditen** [comment]
> what would you think about having him pick it up?

Sounds good. Let me know if you have any questions about it @leekillough.

**Comment by bradcray** [comment]
@daviditen : Something I was wondering on the Discourse conversation:  Is the _implementation_ (rather than just the interface) of Chapel's DateTime module based on Python's?  And do you know whether Python's implementation is also built upon C functions or whether it's native Python?

**Comment by daviditen** [comment]
Parts of the `DateTime` implementation were based on Python's implementation. `strftime` was not. 

Python implements part of the conversion (%f, %z, %Z) in Python, then calls out to a C function that ends up calling the C `strftime` function.

https://github.com/python/cpython/blob/4b37228823fecb73fe70dc009e696a7805b0833f/Lib/datetime.py#L200
https://hg.python.org/cpython/file/429acfbef89c/Modules/timemodule.c#l569

**Comment by leekillough** [comment]
Right now Chapel's `datetime` does not have milliseconds or microseconds. Its granularity is one second. The same is true of the C `struct tm` which is passed to C's `strftime`.

So we'd have to extend Chapel's `datetime` to support milliseconds/microseconds. Would this break existing code?

**Comment by bradcray** [comment]
> Right now Chapel's datetime does not have milliseconds or microseconds. Its granularity is one second.

Really?  How was the user getting a non-zero value for `now.microsecond` in their OP then?  E.g., if I run their code multiple times, I get different non-zero values for `now.microsecond` each time, which is what made me assume it did:  https://tio.run/##S85ILEjN@f@/tDhVwSWxJDUkMzfVmqsssUghL79cwVYhBShWAhTTA3I1NK25yosyS1Jz8jSAXL3ikqI0kJyGkqqHlaqvlWqwnmqakiZMVRpQ3MAsMyZPSQekOjczuSi/ODU5Py8FqCK1IrNEw0DT@v9/AA

**Comment by leekillough** [comment]
See [here](https://github.com/chapel-lang/chapel/blob/b11259faa329f88db86388445ba26d3864c8ec80/modules/standard/DateTime.chpl#L323) and [here](https://github.com/chapel-lang/chapel/blob/b11259faa329f88db86388445ba26d3864c8ec80/modules/standard/DateTime.chpl#L419).

Or is that the wrong place to be looking -- is that a legacy module which was replaced with one with Python functionality and a smaller granularity?

**Comment by bradcray** [comment]
You're in the right module, but those look like the methods on the `date` type, where this issue is about the `datetime` type.  Try https://github.com/chapel-lang/chapel/blob/b11259faa329f88db86388445ba26d3864c8ec80/modules/standard/DateTime.chpl#L843
