### ISSUE TITLE
defining arrays as borrowed gives poor user feedback from chpl.

### ISSUE THREAD

**Issue by ahysing** [chapel-lang/chapel#16860]
When defining an array in a record, setting the ownership of the array to `borrowed`, and not explicitly setting the array domain one ends up with an error **AST-LOO-XPR-0201**

### Summary of Problem

I have created my own [key comparator for sorting](https://chapel-lang.org/docs/1.23/modules/packages/Sort.html#the-key-method). My can sort one array based on values in a diffrent array `fScore`.

I want to be explicit that fScore is an array. The array is owned outside the record. The array will outlive the record. The domain of the array is defined in a different scope, and is not available.

As new to the language it feels natural to define this as an `var <variablename> : borrowed [..] real;`.

One expects the program to compile, but this causes error listed below. This user feedback is rather poor on what causes the problem.

```bash
internal error: AST-LOO-XPR-0201 chpl version 1.23.0

Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug --
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.
```

I are two solutions to this problem.

#### Removed borrowed

On line 2. By changing the record type from `  var fScore : borrowed [..] real;` to `  var fScore : [..] real;` the program compiles without an error.

#### Skip the array type

On line 2. By changing the record type from `  var fScore : borrowed [..] real;` to `  var fScore;` the program compiles without an error.

### Steps to Reproduce

**Source Code:**

In chapel file FScoreComparator.chpl
```chapel
record FScoreComparator {
  var fScore :  borrowed [..] real;
  proc init(fScore : borrowed [..] real) {
    this.fScore = fScore;
  }
}

proc FScoreComparator.key(i) {
  var D = this.fScore.domain;
  if D.contains(i) then
    return this.fScore[i];
  else
    return max(real);
}
```

**Compile command:**
`chpl FScoreComparator.chpl`

**Comment by ahysing** [comment]
As I have allready found two different solutions to this problem I am not blocked by this issue. This issue is adressed as constructive feedback to the chapel developers.

**Comment by bradcray** [comment]
Hi @ahysing — Thanks for reporting this.  Unfortunately, Chapel does not currently have a way of making a record field refer to an array (or other value type) declared outside of the array.  We anticipate supporting this by adding support for `ref` fields within objects, similar to how a top-level declaration `ref myArrRef = myArr;` will result in a reference to the original array rather than a deep copy of it (see, e.g., https://github.com/chapel-lang/chapel/issues/8481, though this issue focuses more on a specific case than the general concept).  Obviously, we should be generating a useful error message for attempting to apply `borrowed` to an array rather than an internal error, so appreciate the report (and are glad you've been able to work around the error for the time being).

**Comment by bradcray** [comment]
I've got a "fix" that generates a better error for your original code here: https://github.com/chapel-lang/chapel/pull/16863  Need to run testing on it and get it reviewed before merging, though.

**Comment by ahysing** [comment]
I am amased by the speed of support. Thank you.

from what I have just learned record FScoreComparator will be quite costly affair. Copying arrays around sounds like I need to go back to the drawing board.

**Comment by bradcray** [comment]
> I am amased by the speed of support. Thank you.

We try to be responsive, but you may just be catching us on a quiet week.  :)  Response times are about to get super-slow with the holidays approaching...

> I have just learned record FScoreComparator will be quite costly affair. Copying arrays around 

I was wondering about this as well...  I assume that there are many potential `fScore` arrays in your computation such that you can't just make this a non-local access to a module-scope array or something like that?  In the absence of good compiler support for fields referring to pre-existing arrays, my head goes to possibly using some sort of `map` from integers (say) to arrays where you can use an integer field as a proxy for the array?  Another (nearly equivalent) approach would be to push each array into its own class object and have the comparators store a reference to that class object.

Tagging @mppf and @ben-albrecht on this issue who I believe have done a lot more with comparators in Chapel than I have to see whether they have any additional ideas.

**Comment by mppf** [comment]
In theory it should be possible to create a comparator record that refers to a global variable or even to an outer variable. However, as far as I recall, we don't support defining records within functions very well right now.

Here is a sketch of how you could use @bradcray's idea of storing the array in a class object:

``` chapel
