### ISSUE TITLE
should someArray.targetLocales() return a reference?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#16873]
The `array.targetLocales()` function invokes `dsiTargetLocales()` on the array implementation class. However, all of the implementations of this function return an existing array (`**` except for DefaultRectangular etc that return an array with the current locale). Current array return semantics are that in this situation a copy of the array is made.

Should `array.targetLocales()` (as well as other targetLocales funtions and the DSI functions) be adjusted to instead return by `const ref` to avoid unnecessary copying?

I observed this issue while investigating #16872.

**Comment by ronawho** [comment]
Hmm, seems like it should be `const ref` to me. 

cc @bradcray and @e-kayrakli

**Comment by bradcray** [comment]
I don't have a strong opinion here.  Is the tension essentially "cost of making an array copy" vs. "potential to have a `ref` that outlives the thing it's referring to?"

**Comment by mppf** [comment]
I'm not actually aware of any downside of returning a `const ref` - it's just not what we do now. I.e. I don't know of a tension / tradeoff.

(Other language elements should prevent us from keeping a ref that outlives the thing it refers to).

It is possible that the targetLocales being copied at this point might reduce communication (if the `const ref` version is always returning something remote), but I am doubtful that will come up in practice. (If the `const ref` version is always returning something remote then we have a problem with privatization, don't we?)

**Comment by mppf** [comment]
(Note that it's likely that at the time these functions were written, arrays returned by ref "by default")

**Comment by e-kayrakli** [comment]
> It is possible that the targetLocales being copied at this point might reduce communication (if the const ref version is always returning something remote), but I am doubtful that will come up in practice. (If the const ref version is always returning something remote then we have a problem with privatization, don't we?)

That sounds right to me: The privatized instances also store their own `targetLocales` array. So, `dsiTargetLocales` should always return a local DR array. And I don't see any particular reason to return a copy of it at the moment. `const ref` makes the most sense to me.

**Comment by mppf** [comment]
> I'm not actually aware of any downside of returning a const ref - it's just not what we do now. I.e. I don't know of a tension / tradeoff.

Oh, I need to correct myself. If it returns by `const ref` then it won't be possible for the implementation to compute a new one on the fly each time. I'm not worried about that in this case since it seems pretty fundamental to what a distributed array is.

**Comment by mppf** [comment]
E.g. if we wanted dsiTargetLocales on a slice to compute some sort of intersection each time. (It could store such a thing and return a ref to it though).

**Comment by mppf** [comment]
For DefaultRectangular we have
``` chapel
    proc dsiTargetLocales() {
      return [this.locale, ];
    }
```

so we'd have to store than in a field or something.

**Comment by bradcray** [comment]
> so we'd have to store than in a field or something.

That feels heavyweight to me to store in every rectangular domain given that this query isn't made much on non-distributed domains anyway.  In the "or something" category, we could have each locale store a private, local, 1-element array storing its locale and have this routine return it?

Or, we could have the `targetLocales()` query have distinct overloads for local vs. distributed cases with different return intents.

(I'm not crazy about either of these approaches, but prefer them to making DR domains larger).

**Comment by mppf** [comment]
Yeah. I was thinking about having the private 1-element arrays (that are globals) for each locale.

**Comment by mppf** [comment]
I've created a draft PR which makes handles the DefaultRectangular case by having each locale store a singleton array containing itself.

**Comment by mppf** [comment]
PR #16874 does this and passes gasnet testing. Is there enough agreement to proceed with it?

**Comment by bradcray** [comment]
No objections here.
