### ISSUE TITLE
can the comm counts from CommDiagnostics include cache hit/miss information?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#16884]
Since we are planning to enable `--cache-remote` by default, it would be useful to make information about how effectively it is performing available along with the CommDiagnostics counters we already have.

Although the cache is per-pthread, that can be viewed as an implementation detail. In this issue we are proposing having per-locale atomic counters. This will make average program behavior easy to see and is similar to how we already handle GET counts in CommDiagnostics.

Further, this issue is suggesting that the additional cache counters be enabled by the CommDiagnostics counting (just as we count GETs). The [chpl_commDiagnostics](https://chapel-lang.org/docs/master/modules/standard/CommDiagnostics.html#CommDiagnostics.chpl_commDiagnostics) record which is returned by `getCommDiagnostics` will be extended to include new fields.

These counters are very useful for discovering how effective the cache is - especially for GETs.

I think we could add the following fields to `record chpl_commDiagnostics`:
 * For GETs
   * the number of GET requests attempted through the cache
   * the number of "hits" where these requests did not require any comms
     * note that a request spanning multiple pages can have some pages be a hit and others be a miss; in that case we would call it a miss for the purposes of the counters
 * For PUTs
   * the number of PUT requests attempted through the cache
   * the number of "hits" where the request did not require any additional comms
     * for PUTs, we would count it as a "hit" when writing to a page that already has dirty bits. That is because these often don't require additional comms beyond the comm needed to for the pending write represented by the dirty bit. (This is a simplification because it assumes that the dirty regions are adjacent to each other and can be combined. It would be possible to compute if the new data is adjacent to existing dirty data).
 * For cache fences
   * the number of cache fences (could separate acquire/release fences if we wanted to)
 * For prefetches
   * the number of explicitly requested prefetches
   * the number of automatic prefetches invoked by the cache

**Comment by mppf** [comment]
@gbtitus @ronawho - I'm interested in your thoughts on this, thanks

**Comment by thomasrolinger** [comment]
I would be very interested in this capability. I had @mppf help me put together a rough outline of these counters so they can be directly printed from `chpl-cache.c` and I think they will prove to be very helpful for my studies. Having them integrated into the CommDiagnostics module would be even better.

**Comment by mppf** [comment]
If we do this, we should update `test/optimizations/cache-remote/ferguson/reduces_comm/ra_prefetch.chpl` so that it can check the number of cache hits is increased by doing the prefetching.

**Comment by gbtitus** [comment]
Yes, I think this would be a very good idea. With comm-caching enabled there's something of a disconnect between what the code seems like it ought to be doing with respect to remote references, when you read it, and what the actual network traffic is. Counting and reporting cache hits and misses will help explain what's going on.

**Comment by mppf** [comment]
@thomasrolinger - fyi PR #16905 adds hit/miss counters for PUT and GET. But, please note that a prefetch that is too late to matter (and that causes the GET to wait) will still count as a "miss" due to an approximation made in the counting here.
