### ISSUE TITLE
Indexing a param string/bytes with a param int should return a param

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#16895]
```chapel
param s = "chapel";
param i = 1;
param ss = s[i];   // this is not a compile time operation
compilerWarning(ss);
```

The above snippet should work but it doesn't today. On master similar issue happens when indexing literals like `("chapel")[1]`. https://github.com/chapel-lang/chapel/pull/16879 will make `"chapel"[1]` parsable, but it'll still remain an execution time operation.

It'd be nice to make these operations at compile time. One  question is whether we can make similar slicing a param operation, but maybe we need to figure out param ranges before we think about that.

**Comment by bradcray** [comment]
> but maybe we need to figure out param ranges before we think about that.

I think that's right:  param ranges would be the most straightforward way to support slicing.  For some historical context here, the million dollar question w.r.t. param ranges is whether we teach the compiler a bunch of things that are specific to ranges or whether we support general param records (and/or classes) and simply apply them to the record that implements ranges.
