### ISSUE TITLE
chpldoc doesn't like 'docs' as a directory name for '--save-sphinx'

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#16904]
When trying to debug a problem in the `.rst` generated by `chpldoc` (as part of working through #16903), my instinct was to use the `--save-sphinx` flag, and for whatever reason, the first directory name that came to mind for me was `docs`.  However, when using `--save-sphinx docs` results in:

```bash
Warning, treated as error:
html_static_path entry '_static' is placed inside outdir
error: building html output from chpldoc sphinx project
```

It took me awhile to realize that `docs/` is a special name for `chpldoc` and that that was the cause of the problem.  Better would be to have `chpldoc` report an error when trying to use this directory name with the `--save-sphinx` flag.

**Associated Future Test(s):**
[`test/chpldoc/compflags/folder/save-sphinx/saveSphinxInDocs.doc.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/chpldoc/compflags/folder/save-sphinx/saveSphinxInDocs.doc.chpl
          ) #16906

**Comment by bradcray** [comment]
@lydia-duncan / @ben-albrecht : Let me know if you disagree with the proposal here (and/or the green labels I've attached to this).

**Comment by lydia-duncan** [comment]
That seems like a good proposal to me and I agree with the labeling

**Comment by cassella** [comment]
FWIW, `--save-sphinx docs` can be used when `--no-html` is also used, and is so used in a number fo existing tests

```
fortytwo@pop-os:~/src/chapel (master)$ grep -r "save-sphinx docs" test/chpldoc/
test/chpldoc/errhandling/CHPLDOCOPTS:--no-html --save-sphinx docs
test/chpldoc/module/CHPLDOCOPTS:--no-html --save-sphinx docs
test/chpldoc/nodoc/CHPLDOCOPTS:--no-html --save-sphinx docs
test/chpldoc/basics/CHPLDOCOPTS:--no-html --save-sphinx docs
test/chpldoc/include/CHPLDOCOPTS:--no-html --save-sphinx docs --process-used-modules
test/chpldoc/types/arguments/CHPLDOCOPTS:--no-html --save-sphinx docs
test/chpldoc/types/config/CHPLDOCOPTS:--no-html --save-sphinx docs
test/chpldoc/types/returns/CHPLDOCOPTS:--no-html --save-sphinx docs
test/chpldoc/types/CHPLDOCOPTS:--no-html --save-sphinx docs
test/chpldoc/types/fields/CHPLDOCOPTS:--no-html --save-sphinx docs
test/chpldoc/linkage-spec/CHPLDOCOPTS:--no-html --save-sphinx docs
test/chpldoc/enum/CHPLDOCOPTS:--no-html --save-sphinx docs
test/chpldoc/compflags/externs/CHPLDOCOPTS:--no-html --save-sphinx docs --no-externs
test/chpldoc/compflags/comment/CHPLDOCOPTS:--no-html --save-sphinx docs
test/chpldoc/CHPLDOCOPTS:--no-html --save-sphinx docs
test/chpldoc/classes/CHPLDOCOPTS:--no-html --save-sphinx docs
test/chpldoc/extensions/CHPLDOCOPTS:--no-html --save-sphinx docs
test/chpldoc/globals/CHPLDOCOPTS:--no-html --save-sphinx docs
```

I don't know if it's worth preserving that behavior, or fixing up all those tests (and their foo.catfiles and CLEANFILES, etc.) to use a different directory.

**Comment by lydia-duncan** [comment]
Since I think the main problem is using the same directory for multiple stages of the output, I think it would be okay to allow `--save sphinx docs` in that case.  Thanks for noticing it!
