### ISSUE TITLE
tests in library/packages/ProtobufProtocolSupport fail under gasnet

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#16908]
These tests are skipped in most nightly testing configurations (because protoc-gen-chpl is not built) but they fail under gasnet. Do they need to be adjusted in some way?

**Comment by bradcray** [comment]
Sounds like a question for @lydia-duncan ?

**Comment by lydia-duncan** [comment]
What's the output they fail with?

**Comment by mppf** [comment]
```
$ cat test/library/packages/ProtobufProtocolSupport/anyRunner.exec.out.tmp 
error: Specify number of locales via -nl <#> or --numLocales=<#>
error: Specify number of locales via -nl <#> or --numLocales=<#>
error: Specify number of locales via -nl <#> or --numLocales=<#>
Traceback (most recent call last):
  File "endToEnd/any/read.py", line 6, in <module>
    file = open("out", "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'out'
error: Specify number of locales via -nl <#> or --numLocales=<#>
```

Presumably they just need `-nl` arguments when they run built Chapel programs.

**Comment by mppf** [comment]
maybe @Aniket21mathur can help with it?

To reproduce just run these tests in a Chapel configuration with `export CHPL_COMM=gasnet` and `export GASNET_SPAWNFN=L`.

**Comment by Aniket21mathur** [comment]
Hello everyone! A very Happy new year to all :)

Hii @mppf , thanks for asking.

> Presumably they just need `-nl` arguments when they run built Chapel programs.

Yes, you are right. The `endToEndRunnerUtils.chpl` execute chapel binaries through `spawnshell` and we need to pass the number of locales or `-nf` flag to make them run over `gasnet`. I successfully tested the change locally.

How should we handle it? So that it works for both with and without `gasnet`.

**Comment by lydia-duncan** [comment]
Did you build protoc-gen-chpl with gasnet or was it relying on a previously built version?

It seems to me like there's potentially two things to watch out for:
1. the protoc-gen-chpl program being built for multilocale and potentially not being called properly by protoc itself
2. the test programs not adjusting to pass a numlocales argument when the .chpl files are built for multilocale.

The former seems like potentially more work to fix if it is happening (which, it probably would happen if we add a `make protoc-gen-chpl` call to gasnet testing), while the latter is annoying but not particularly tricky (I'd imagine you just have to add a check against CHPL_COMM != none in the test runner program and adjust the arguments passed in that case - we were thinking of moving the ChapelEnv module to no longer be included by default, so it might be good to put an explicit use into those tests in anticipation of that change)

**Comment by lydia-duncan** [comment]
Alternatively for #2, we could add a SKIPIF file for the directory for gasnet and make a separate copy of the tests that only runs with CHPL_COMM != none

**Comment by mppf** [comment]
> How should we handle it? So that it works for both with and without gasnet.

You can pass `-nl 1`. This should work for both gasnet and local configs.

> the protoc-gen-chpl program being built for multilocale and potentially not being called properly by protoc itself

This is not possible since protoc-gen-chpl is a C++ program not a Chapel one.

> the test programs not adjusting to pass a numlocales argument when the .chpl files are built for multilocale.

AFAIK this is the only problem.

> I'd imagine you just have to add a check against CHPL_COMM != none in the test runner program and adjust the arguments passed in that case

AFAIK you can pass `-nl 1` even in the `CHPL_COMM=none` configuration so no checking is required.

**Comment by Aniket21mathur** [comment]
> Did you build protoc-gen-chpl with gasnet or was it relying on a previously built version?

Yes..I build protoc-gen-chpl with gasnet.

> 2\. the test programs not adjusting to pass a numlocales argument when the .chpl files are built for multilocale.

I think this is the only reason the tests are failing, I added the `-nl 1` flag and tested the changes locally, tests are passing for both  `CHPL_COMM=gasnet` and `CHPL_COMM=None`.

**Comment by Aniket21mathur** [comment]
@lydia-duncan @mppf please see #16924. Thanks!
