### ISSUE TITLE
Add "community mason package" placeholder page to docs hierarchy

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#16913]
This issue proposes (at user request) adding a placeholder page to the Chapel documentation hierarchy (say just under "standard modules" and "package modules" items on the sidebar) that would:

* serve as a placeholder for describing and advertising the concept of community mason packages
* give status of where the effort stands today and what steps remain to get it up to speed
* provide any caveats about the current status that are necessary to keep us from feeling too embarrassed

**Comment by ben-albrecht** [comment]
I think we should include a link to https://github.com/chapel-lang/mason-registry/ from this page. While it's not a great way to browse packages, it's at least _a_ way to see what packages are available on the web.

Beyond this initial task, we should invest some cycles into building a proper user-facing package registry web page (https://github.com/chapel-lang/chapel/issues/10618), where https://github.com/chapel-lang/chapel/pull/10795 provides a good starting point.

**Comment by burnerlee** [comment]
@bradcray can I please work on this issue, please assign it to me

**Comment by ben-albrecht** [comment]
Hey @burnerlee, thanks for your interest. I am going to work this issue shortly. While it's `[easy / straightforward]`, it's not a great issue for a first time contributor because it will mostly be about fine-tuning the format and wording of the document.

**Comment by burnerlee** [comment]
hey @ben-albrecht, thanks for the prompt reply. I understand your point. It would be great if you could assign me some other issue to work on the project. I'm looking forward to it. Thanks

**Comment by ben-albrecht** [comment]
@burnerlee - Issues with the [`Good first issue`](https://github.com/chapel-lang/chapel/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) label are your best bet. Don't be discouraged by issues that have previous activity. Many times, a contributor will start working on an issue then disappear for a while without completing the issue.

(I am going to mark this as off-topic, but you can expand to read it).
