### ISSUE TITLE
Proposal: "operator" keyword for operator functions and methods

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#16929]
This proposal is a slightly more polished version of the discussion that occurred via email and starting from [this comment](https://github.com/chapel-lang/chapel/issues/16730#issuecomment-748289279), as originally proposed by Engin and discussed with Brad and Michael.  It is intended to bring more eyes to the idea by giving it its own topic, and hopefully reach a final decision.

Operators have traditionally been implemented as stand-alone functions, distinguishable from regular functions largely by their name ("+", etc.).  We're moving towards also allowing operators to be explicitly associated with the types on which they are defined (again, see discussion on #16730), and expect to continue to do so.  This issue proposes that we also move to make operators more explicitly distinguishable from other functions and methods, by using a new keyword `operator`.  E.g., rather than writing:

```chapel
record R {
  // primary operator
  proc type +(lhs: R, rhs: R) { ... }
}

// secondary operator
proc type R.-(lhs: R, rhs: R) { ... }

// standalone operator
proc *(lhs: R, rhs: S) { ... }
```

We would instead write:

```chapel
record R {
  // primary operator
  operator +(lhs: R, rhs: R) { ... }
}

// secondary operator
operator R.-(lhs: R, rhs: R) { ... }

// standalone operator
operator *(lhs: R, rhs: S) { ... }
```

This would make a special cased style of function more explicitly recognizable.  It would be great as part of the implementation to move some of the compiler special-casing for operators to be triggered by the operator keyword (but that's an implementation detail).

Note that I would expect this to be a breaking change.  If we do not immediately drop support for operators without the keyword, I would expect us to do so within a few releases.

Names
-------

As part of this issue, I propose at least initially limiting the names used for operators to only those already known to the Chapel language.  For instance, the following definitions would be allowed because Chapel already is aware of the "+" and "-" operators:

```chapel
operator +(lhs: R, rhs: R) { ... }
operator R.-(lhs: R, rhs: R) { ... }
```

but the following definition would cause a compilation error, because Chapel is not aware of an operator "$%&":

```chapel
operator $%&(lhs: R, rhs: R) { ... }
```

We can choose to allow the operator keyword to define new operators in the future, but I'd rather we stick to supporting what is already supported for now.  If we are able to tie operator functionality more generally to the keyword, that could make such support more feasible in the future.

Operator Iterators
------------------

Though today it is possible to define an operator as an iterator, in our discussions we found this support surprising and unintentional.  I propose that we choose not to allow such cases until such time as they are explicitly requested.  Engin suggested in [this comment](https://github.com/chapel-lang/chapel/issues/16730#issuecomment-754113978) that if we decide to allow operator iterators, we make the syntax `operator iterator` and allow  `operator proc`, but assume that `operator` without either defaults to `operator proc`.  I think this is a good plan.

**Comment by bradcray** [comment]
Something to think about if we go this route is how `operator` methods interact with forwarding.  A downside of the current standalone operator functions approach is that forwarding doesn't apply (where I think we'd like the ability to forward methods when wrapping types; so I'd expect/hope that operators would be able to forward like other methods do).
