### ISSUE TITLE
datetime.strptime() should support %f

### ISSUE THREAD

**Issue by leekillough** [chapel-lang/chapel#16922]
Similar to #16834, `datetime.strptime()` should support `%f`.

It is much harder to implement than `strftime()`, since it needs to parse strings with the `%f` specifier at an arbitrary location in the format.

[Python implementation](https://github.com/python/cpython/blob/63298930fb531ba2bb4f23bc3b915dbf1e17e9e1/Lib/_strptime.py)

**Comment by king-11** [comment]
@leekillough I would like to work on this issue if no one else is currently. It will help if you can provide more details as to what needs to be implemented

**Comment by leekillough** [comment]
> @leekillough I would like to work on this issue if no one else is currently. It will help if you can provide more details as to what needs to be implemented

`strptime()` needs to be totally reimplemented to support parsing the `%f` format. Right now Chapel's `strptime()` is based on C's `strptime()`, which does not support `%f`. In #16384 it was easy to handle `%f`, since we only had perform in-place expansion of `%f` and pass the rest of the formatting to C `strftime()`. In `strptime()`, all of the formatting parsing has to be reimplemented, because `%f` can occur anywhere in the format string, and you need to parse an arbitrary string based on an arbitrary format. See the Python and C documentation for `strptime()`. Python's `strptime()` implements `%f`, but C's does not.

**Comment by bradcray** [comment]
@leekillough : I think you know this due to your work on #16384: Is the Python implementation of `strptime()` open-source, and could it be used as a model for Chapel's implementation?

**Comment by leekillough** [comment]
> @leekillough : I think you know this due to your work on #16384: Is the Python implementation of `strptime()` open-source, and could it be used as a model for Chapel's implementation?

[Link to the Python source code](https://github.com/python/cpython/blob/63298930fb531ba2bb4f23bc3b915dbf1e17e9e1/Lib/_strptime.py) is in the OP.

It is fairly complex regular expression pattern matching, which probably wouldn't run very fast on Chapel as things sound now. We also have to deal with `string` vs `byte`, Unicode, etc.

IANAL, so I don't know whether the [license](https://github.com/python/cpython/blob/63298930fb531ba2bb4f23bc3b915dbf1e17e9e1/LICENSE) allows it.

It might be easier to write a C function for `strptime()` and call that the way that we current call C's `strptime()`.

**Comment by bradcray** [comment]
> Link to the Python source code is in the OP.

D'oh!  So it is, sorry about that.

**Comment by king-11** [comment]
> It is fairly complex regular expression pattern matching, which probably wouldn't run very fast on Chapel as things stand now. We also have to deal with `string` vs `byte`, Unicode, etc.
> It might be easier to write a C function for `strptime()` and call that the way that we currently call C's `strptime()`.

@leekillough I looked a python's implementation it does look very complex a right now looking to implement similar in C haven't worked with ```strptime``` before so will probably take a day or two for me to understand to get a raw implementation working

**Comment by king-11** [comment]
@leekillough the current ```tm``` won't be able to store microseconds returned from the new c function so what shall we do abt it? what I thought the implementation could be we call a new C function which parses ```%f``` for us into a structure and we can then pass the same structure to C's ```strptime```

**Comment by leekillough** [comment]
Unfortunately:
* We need to parse the source string according to the format sequentially from the beginning of the source string, so we have to write our own parser to parse all of the formats in C's `strptime()` in order to find the position in the source string where `%f` would be expected and parsed. We cannot know where in the source string to parse `%f` without scanning the source string and format from the beginning, because that position is variable, and depends on the previous formats and the previous parts of the source string.
* If C's `strptime()` encounters `%f` in the format, it will return `NULL` and we won't know anything about the position in the source string that it was at when it encountered `%f` in the format.
* Even if we knew the position(s) in the source string where the `%f` is expected to be parsed, C's `strptime()` would not understand `%f` or the 6 digits it expects when it saw them, so we would need to delete the `%f` format and the corresponding 6 characters in the source string before passing them to `strptime()`. But as said above, we cannot really determine the location in the source string corresponding to `%f` without writing our own parser.

There are BSD-licensed versions of `strptime.c`. One of them could be cloned and modified to support `%f`, taking an extra `unsigned*` parameter to store the microseconds into, since `struct tm` does not have microseconds.

**Comment by leekillough** [comment]
See [here](https://cgit.freebsd.org/src/tree/lib/libc/stdtime/strptime.c?h=stable/13), [here](http://cvsweb.netbsd.org/bsdweb.cgi/src/lib/libc/time/strptime.c?annotate=1.63&only_with_tag=HEAD) and [here](https://github.com/openbsd/src/blob/master/lib/libc/time/strptime.c).

I would clone one of those `strptime.c` files, rename `strptime()` to `chpl_strptime()`, add the `unsigned long* us` parameter, add `%f` to the `switch` statement, storing microseconds in `*us`, and then call `chpl_strptime()` from Chapel `datetime` instead of `strptime()`.

**Comment by leekillough** [comment]
To choose the `strptime.c` that you will use, read the license language carefully. Look for any excess stuff like handling esoteric architectures which we never will need to support, or copyright strings injected into the binary. Try to choose one with the least restrictions, the least esoteric cases handled, and the least fluff (like binary copyright messages).

By that criteria, my choice would be the NetBSD version.

**Comment by king-11** [comment]
@leekillough I was trying to do changes as you provided in the OP but am having issues with the header files which am not able to resolve ```#include <sys/localedef.h>``` can you help a bit here I asked in gitter channel too 😓

**Comment by leekillough** [comment]
> `#include <sys/localedef.h>`

Sometimes these files like `strptime.c` are part of a larger library with its own paths to headers, independent of any standard ANSI C/C++ headers. You should replace these library-specific header paths with standard headers.

You can try to remove the `#include` and see if the file still compiles. For something named `localdef.h` I would try adding `#include <stddef.h>`, especially if the undefined symbols are things like `size_t`.

I would try including the following headers, after removing any library-specific includes which are causing problems:

```C
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <sys/time.h>
```

**Comment by king-11** [comment]
@leekillough I am done with the implementation I used the NetBSD version.

If you can tell me how to include the C File in the build process and in which dir to commit it so that will do the job.

**Comment by leekillough** [comment]
> @leekillough I am done with the implementation I used the NetBSD version.
> 
> 
> 
> If you can tell me how to include the C File in the build process and in which dir to commit it so that will do the job.

Sorry for the delay. There is a `runtime/` subdirectory with `include` and `src` subdirectories, and it can go in there (you probably only need a `.c` file, not a `.h` file). You can update the Makefile in there to add the compiled `.o` to the runtime library. The datetime module file needs to declare the `chpl_strptime` function in Chapel using C-like syntax.

**Comment by leekillough** [comment]
I can walk you through it and help you add unit tests if they don't exist already.

**Comment by leekillough** [comment]
@king-11: if you push your branch to your repo, I will look and it and quickly come up with a solution which I will submit as a PR to your PR. That's probably quicker than walking you through the steps, although I can walk through the changes after they are done.

**Comment by king-11** [comment]
@leekillough I will push by changes to branch soon found some issues which am currently resolving that's why the delay.

**Comment by bradcray** [comment]
Re-opening this — see #18359 for details.
