### ISSUE TITLE
Resolution failures should not show standalone function/method candidates that don't apply

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#16928]
As a Chapel programmer, I believe that the compiler's resolution error messages would be clearer to understand if they did not list method candidates for a callsite that is necessarily a standalone function; nor standalone method candidates for a callsite that is necessarily a method call.  For example, in issue #16917, @rchinmay's call to `write()` lists various `.write()` methods on atomic types as candidates even though the call was standalone.  I find that in most cases, such candidates make the compiler's error messages less clear rather than more.

To that end, I'd be inclined to say:

* for a call `myExpr.foo()`, we only list methods named `foo()` as candidates (or maybe better, only methods named `foo()` that are within the class hierarchy of `myExpr`'s static type?)
* for a call `foo()` that is being made outside of a method context, we only list standalone routines as candidates
* for a call `foo()` that is being made within a method context, we list both method and standalone candidate routines (where any filtering for "which methods" in bullet 1 above would apply)

If there were concern that this swept too much under the rug (e.g., maybe the user wrote `foo()` but meant to type `x.foo()`?), perhaps the compiler could support a flag like `--print-all-candidates` that would override this filtered behavior (and perhaps the default error message could refer to the flag?  though I probably wouldn't do that until we knew it was causing programmers to miss things).

**Comment by vasslitvinov** [comment]
This is a good idea.

I suggest we do not wait for users to start missing things. It is easy to add counts of the not-shown candidates, ex. "also NN other methods and MM standalone functions, use --print-all-candidates to see them". Users might already expect that, given that we already print a total count of candidates when there are too many to show.

> we only list module-scope routines as candidates

You probably meant "standalone", not "module-scope".

**Comment by bradcray** [comment]
> You probably meant "standalone", not "module-scope".

Good point, I've fixed that.

**Comment by lydia-duncan** [comment]
I have a vague memory of Ben Harshbarger adding something along these lines

**Comment by lydia-duncan** [comment]
Ah, looks like what he added was specific to "init", "deinit" and "_new" but has room for expanding to other methods (see #9864 and #10069)

**Comment by bradcray** [comment]
I took a stab at this as a study break this week and got a promising start on it.
