### ISSUE TITLE
Improve error message when passing `type` argument to (value) varargs formal

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#16932]
Currently, when passing a `type` argument to a (value) varargs formal, the error message looks something like this:

```bash
foo.chpl:8: error: unresolved call 'foo("int", type real(64))'
foo.chpl:1: note: this candidate did not match: foo(x ...)
foo.chpl:8: note: because type call actual argument #2
foo.chpl:1: note: is passed to non-type formal '_e1_x'
```

which is a bit unfortunate in that (a) it reveals an internal symbol name (the expansion of the varargs formal) and (b) doesn't particularly clearly state that a type can't be passed to a (value / non-type) varargs formal.

In this issue, I'm proposing we improve this error message.  My current proposal is:

```bash
foo.chpl:8: error: unresolved call 'foo("int", type real(64))'
foo.chpl:1: note: this candidate did not match: foo(x ...)
foo.chpl:8: note: because actual argument #2 is a 'type'
foo.chpl:1: note: so cannot be passed to a non-type varargs formal
```

This was split off from user issue #16917.

**Comment by bradcray** [comment]
My implementation of this is here:  https://github.com/bradcray/chapel/tree/specialize-resolution-error-for-varargs

(though I'm saving the removal of "call" in "call actual argument" for a separate PR because of the number of affected tests).

**Comment by vasslitvinov** [comment]
> because actual argument #2 is a 'type'
> so cannot be passed to a non-type varargs formal

I suggest changing the last line to "is passed" :
```
because actual argument #2 is a 'type'
but is passed to a non-type varargs formal
```

This way it stays with the theme of describing what is going on, rather than what the rule is.

**Comment by vasslitvinov** [comment]
P.S.1 We tend to use quotes around names in our error messages. I suggest not using them around "type".

P.S.2 For extra coolness, include the varargs formal's name.

For example:
```
because actual argument #2 is a type
but is passed to a non-type varargs formal 'x'
```

**Comment by vasslitvinov** [comment]
I support removal of "call" and adding single quotes as you are proposing in https://github.com/chapel-lang/chapel/pull/12958#issuecomment-758220008

**Comment by bradcray** [comment]
Thanks for the comments Vass.  I agree with your feedback.  I'm going to put off the removal of "call" until another PR because its impacts are broader.
