### ISSUE TITLE
chpldoc printing of default value expression can omit needed parens

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#16939]
### Summary of Problem

chpldoc drops the parens around `3+4` here, which changes the value of the expression from 15 to 11:

**Source Code:**

```chapel
proc foo(arg=1+2*(3+4)) {}
```

**Compile command:**

`chpldoc --no-html --save-sphinx docs foo.chpl`

`cat docs/source/modules/foo.rst`

```
.. function:: proc foo(arg = 1+2*3+4)
```

**Associated Future Test(s):**

[` test/chpldoc/functions/functionArgDefaultWithParens.doc.chpl`](
     https://github.com/chapel-lang/chapel/blob/master/test/chpldoc/functions/functionArgDefaultWithParens.doc.chpl) #16893

### Configuration Information

```
chpl version 1.24.0 pre-release (5f95c6d1d0)

gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: none
CHPL_HWLOC: bundled
CHPL_REGEXP: re2
CHPL_LLVM: none
CHPL_AUX_FILESYS: none
```

**Comment by lydia-duncan** [comment]
Ohhh, interesting.  I think that'll be trickier to resolve, I don't know as much about how we represent enclosing statements in parentheses.

**Comment by cassella** [comment]
Also unary operators, and unary operators distributed over binary operators:

```chapel
var z = -(-(-(a)));
var zz = -(a + b);
```

```rst
.. data:: var z = ---a    // legal Chapel, actually.

.. data:: var zz = -a+b
```

Modifying `appendExpr()`'s binary operator case to add parens around both operands of all binary operators produces:

```chapel
var x = a + b + c + d;
var y = (a + b) + (c + d);
```


```rst
.. data:: var x = (((a)+(b))+(c))+(d)

.. data:: var y = ((a)+(b))+((c)+(d))
```
which is objectively too many parenthesis.

Instead adding parens around every binary operator expression does a little better


```rst
.. data:: var x = (((a+b)+c)+d)

.. data:: var y = ((a+b)+(c+d))
```

To do better, I think you'd have to do something like look at each binary/unary operator node and its children to add parentheses around only children that are themselves binary operators with a lower precedence than the operator in the current node.
