### ISSUE TITLE
chpldoc doesn't format a 1-tuple correctly

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#16940]
### Steps to Reproduce

**Source Code:**

```chapel
proc tuple1Default(arg=(x,));
proc tuple2Default(arg=(x,y));
proc tuple3Default(arg=(x,y,z));
```

**Compile command:**

`chpldoc --no-html --save-sphinx docs foo.chpl`

`cat docs/source/modules/foo.rst`

```
.. function:: proc tuple1Default(arg = (x))

.. function:: proc tuple2Default(arg = (x, y))

.. function:: proc tuple3Default(arg = (x, y, z))
```

The first one should be `(x,)`, not `(x)`.

**Associated Future Test(s):**

[`test/chpldoc/functions/functionArgDefaultOneTuple.doc.chpl`]( 
    https://github.com/chapel-lang/chapel/blob/master/test/chpldoc/functions/functionArgDefaultOneTuple.doc.chpl) #16893

### Configuration Information

```
chpl version 1.24.0 pre-release (5f95c6d1d0)

gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: none
CHPL_HWLOC: bundled
CHPL_REGEXP: re2
CHPL_LLVM: none
CHPL_AUX_FILESYS: none
```

**Comment by lydia-duncan** [comment]
I'm actually more okay with this and would be curious if others like @bradcray agree

**Comment by bradcray** [comment]
For precision, I think we should output the one-tuple with comma (because `(x)` is typically the same as `x` in an expression context when other operator precedence rules aren't involved).

**Comment by lydia-duncan** [comment]
That's fair.  I've added the bug label.  Like #16939, I suspect this will be trickier than the other chpldoc issues we've found.
