### ISSUE TITLE
chpldoc doesn't format correctly a variable initialized to nil

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#16941]
### Steps to Reproduce

**Source Code:**

```chapel
class C {}
var q:C? = nil;
```

**Compile command:**

`chpldoc --no-html --save-sphinx foo.chpl`

`cat docs/source/modules/foo.rst`

```
.. data:: var q: nilable C =
```

**Associated Future Test(s):**

[` test/chpldoc/functions/functionArgDefaultNil.doc.chpl`](
    https://github.com/chapel-lang/chapel/blob/master/test/chpldoc/functions/functionArgDefaultNil.doc.chpl) #16893

### Configuration Information

```
chpl version 1.24.0 pre-release (5f95c6d1d0)

gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: none
CHPL_HWLOC: bundled
CHPL_REGEXP: re2
CHPL_LLVM: none
CHPL_AUX_FILESYS: none
```

**Comment by lydia-duncan** [comment]
Hmm.  I had thought we had a test locking in that nil worked already.
