### ISSUE TITLE
Range.low, high - should be aligned?

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#17130]
Stridable ranges have the "alignment" property, because of which the "low bound" may differ from the "aligned low" bound, which is the first or the last index in the corresponding sequence.

Traditionally, `range.low` and `range.high` were not necessarily aligned. This works fine in most cases until the user hits a case where alignment matters and has to spend time investigating an issue.

We propose to re-purpose `range.low` and `range.high` to return the aligned bounds, which are less error-prone, and provide separate methods to return raw bounds.

Pros: reduce user surprises and debugging time.

Con 1: it is challenging to transition from the current meaning of the low/high methods.
One possible direction: deprecate range.low/range.high for a release or two, then reinstate with the new meaning.
Another possibility: go ahead and assign them the new meanings. Although this would break user functions that do something similar to the built-in `range.exterior()`.

Con 2: it is unintuitive for the user to create a range with the low bound X and have `low` return something other than X.

**Comment by bradcray** [comment]
I like the proposal to have `.low` and `.high` be aligned by default, and suspect it would reduce the number of surprises we have in code when we first run it with strided ranges.  I mostly only worry about the pain of transitioning in a manner that minimizes frustration and surprises.  If we could snap our fingers and rewrite history to do this, I would.  We'd also need to come up with ways of querying the current notions of `.low`/`.high` (I think Michael proposed something like `.lowBound`, `.highBound`?).

**Comment by vasslitvinov** [comment]
If we make any changes here, we will need to duplicate them for `domain`, as the latter has low/high and alignedLow/alignedHigh.

**Comment by vasslitvinov** [comment]
As a data point, forcing `.low` and `.high` return their aligned counterparts outright causes 88 paratest failures. The ones I looked at failed because the ranges were printed with their aligned bounds, ex. `-5..#12 by 2` was printed as `-5..5 by 2`. This is probably not a printing issue (which I adjusted), rather it the range was actually represented that way.

<details>
<summary>list of failures</summary>

arrays/bradc/localSlices/localsliceOOB2.chpl
arrays/bradc/localSlices/localsliceOOB.chpl
arrays/bradc/slices/fftSlice.chpl
arrays/bradc/slices/sliceStridedArray.chpl
arrays/deitz/stride/test_stride1.chpl
arrays/deitz/stride/test_stride2.chpl
arrays/diten/assignBlockSlice.chpl
arrays/sparse/stridedBaseDom.chpl
arrays/userAPI/reindexOps2D.chpl
arrays/userAPI/unsignedOps.chpl
arrays/vass/iterations-over-weird-ranges-1.chpl
arrays/waynew/init2.chpl
distributions/bharshbarg/stridedBoundingBox.chpl
distributions/diten/Dimensional.chpl
distributions/diten/testCyclic.chpl
distributions/dm/t2.chpl
distributions/dm/t5a.chpl
distributions/dm/t8.chpl
distributions/dm/t9.chpl
distributions/robust/arithmetic/reindexing/test_strided_reindex1.chpl
distributions/vass/densify-1-self.chpl
distributions/vass/densify-2-toUnitStride.chpl
domains/bradc/slices/sliceDomain.chpl
domains/bradc/slices/sliceStridedDomain.chpl
domains/bradc/splitdomain.chpl
domains/diten/assignStridedRangeTupToDom.chpl
domains/diten/castAwayStridableDomain.chpl
domains/diten/sliceStridedByNon.chpl
domains/operators/domainAlign.chpl
domains/shannon/by4Dtuple.chpl
domains/userAPI/test2Ddomain.chpl
domains/userAPI/testEnumDomain.chpl
domains/vass/aligned-domain-forall.chpl
functions/diten/overloadBy.chpl
functions/diten/refIntents-workaround.chpl
io/bradc/printArrWithUnalignedBounds.chpl
library/standard/LinkedLists/bradc/degenseq.chpl
library/standard/LinkedLists/deitz/test_aseq4.chpl
library/standard/LinkedLists/deitz/test_aseq5.chpl
optimizations/bulkcomm/alberto/Block/1dStrideBlock.chpl
optimizations/bulkcomm/alberto/Block/2dBDtoDRTest.chpl
optimizations/bulkcomm/alberto/Block/2dDRtoBDTest.chpl
optimizations/bulkcomm/alberto/Cyclic/1dStrideCyclic.chpl
optimizations/bulkcomm/alberto/Cyclic/2dDRtoCyTest.chpl
optimizations/bulkcomm/alberto/Cyclic/BlockToCyclic.chpl
optimizations/bulkcomm/alberto/Cyclic/CyclicToBlock.chpl
release/examples/primers/learnChapelInYMinutes.chpl
release/examples/primers/ranges.chpl
release/examples/spec/Ranges/rangeByOperator.chpl
release/examples/spec/Ranges/rangeCountOperator.chpl
release/examples/spec/Ranges/rangeSlicing.chpl
release/examples/spec/Ranges/rangeVariable.chpl
types/range/bradc/needAlignment/alignedOp2.chpl
types/range/bradc/needAlignment/wantsAlignment.chpl
types/range/bradc/rangeMath.chpl
types/range/bradc/splitrange.chpl
types/range/bradc/strideRangeSlice2.chpl
types/range/bradc/strideRangeSlice.chpl
types/range/claridge/expand_strided_range.chpl
types/range/claridge/strided_range_constructor.chpl
types/range/count/countZeroElems.chpl
types/range/deitz/test_range_index3.chpl
types/range/deitz/test_range_index.chpl
types/range/diten/castAwayStridableRange.chpl
types/range/diten/rangeSlice.chpl
types/range/diten/testRangeSlice2.chpl
types/range/diten/testRangeSlice3.chpl
types/range/diten/testRangeSlice.chpl
types/range/enum/basicEnumRangeTest.chpl
types/range/enum/enumRangeStrided.chpl
types/range/ferguson/range-generic-default3.chpl
types/range/ferguson/range-split-inits.chpl
types/range/hilde/align.chpl
types/range/hilde/by.chpl
types/range/hilde/count.chpl
types/range/memberDiffStrides.chpl
types/range/nonIntTypes/byteRange.chpl
types/range/nonIntTypes/codepointRange.chpl
types/range/userAPI/byteRangeTest.chpl
types/range/userAPI/codepointRangeTest.chpl
types/range/userAPI/simpleRangeTest.chpl
types/range/vass/offset-1.chpl
types/range/vass/writeranges-1.chpl
</details>

**Comment by mppf** [comment]
I'm for the change and I think we can manage it with two phases of deprecation.
 1. Deprecate `low` / `high` in favor of `lowBound` /`highBound`, leaving `alignedLow`/`alignedHigh` for now. Adjust code to use `lowBound` /`highBound` / `alignedLow`/`alignedHigh` for now, to avoid the deprecation warning
 2. After we have had a release with them being deprecated, make `low` and `high` behave as `alignedLow`/ `alignedHigh` and then deprecate `alignedLow` / `alignedHigh` (since these are now better referred to as `low` / `high`).
 
If that seems like it's too annoying in the short term, we can add a `chpl` flag to step 1 that opts in to the behavior in step 2 instead of getting the deprecation warning.

**Comment by bradcray** [comment]
> we can add a chpl flag to step 1 that opts in to the behavior in step 2 instead of getting the deprecation warning.

This is where my mind went as well: Seems like it'd be attractive to have the ability to move all the way into the new world and out of the warnings by throwing a config or something like that.

**Comment by vasslitvinov** [comment]
I am game with Michael's suggestion, including a compiler flag (along with an environment variable).

In the long term, the win is worth the hassle.

**Comment by bradcray** [comment]
I've opened #19836 to flesh out the proposed approach here in more detail and #19820 to implement it
