### ISSUE TITLE
missing structure padding with LLVM backend

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#17141]
### Summary of Problem

The LLVM backend isn't currently emitting structure padding. I would expect it to emit padding in a manner similar to a C compiler as this probably represents a performance best practice.

### Steps to Reproduce

Compile a test with a record with unaligned fields using `--llvm` and inspect the generated LLVM IR. It should also be observable when querying the size of such a structure.

**Associated Future Test(s):**
[`test/llvm/alignment/check-align-padding.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/llvm/alignment/check-align-padding.chpl
          ) #17138

**Comment by bradcray** [comment]
That's... surprising.

**Comment by mppf** [comment]
I'm closing this issue since we 1) know that the issue is specific to aligned extern types and 2) have the error for misalignment in the release 1.24.

https://github.com/Cray/chapel-private/issues/1802 covers the remaining work.
