### ISSUE TITLE
Is writeln supposed to return bool?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#17179]
I was surprised to learn that `writeln()` (from ChapelIO.chpl) does not return anything:

https://github.com/chapel-lang/chapel/blob/fc00057e01d274d9cf6f63aec9db95f299feea5b/modules/standard/ChapelIO.chpl#L841-L843

I was expecting it to return `bool` (where it would return `false` for whatever reason `channel.writeln()` from IO.chpl can return `false`):

https://github.com/chapel-lang/chapel/blob/fc00057e01d274d9cf6f63aec9db95f299feea5b/modules/standard/IO.chpl#L4042-L4044

It appears that the top-level (non-method) `write` and `writeln` do not return a value while `writef` does.

**Comment by 12mohaned** [comment]
I believe the only case `channel.writeln()` would return false is to try to write on a read-only channel, else it would return true, I suspect it is an easy fix, It will test further and push changes.

**Comment by mppf** [comment]
@12mohaned - it should throw in that case. It should only be returning `false` when the file reaches end of file and nothing is read.

**Comment by vijaya-bhargavi** [comment]
stdout.writeln returns bool. So does it mean that the writeln function should return the output of stdout.writeln?

**Comment by mppf** [comment]
@vijaya-bhargavi - yes, that is what I would expect.

**Comment by 12mohaned** [comment]
There is something, I believe should be further investigated or I do not understand Its design rationale enough, the docs state that 

> Since channels operate independently, concurrent I/O to the same open file is possible without contending for locks. Furthermore, since the channel (and not the file) stores the current file offset, it is straightforward to create programs that access the same open file in parallel.

But when I tried writing to the same file with different channels, only the first channel write to file succeed, so it is either I do not understand the design rationale behind channels or there is a problem, I used the below code to test my findings.

`var myWritingChannel1 = myFile.writer();
var myWritingChannel2 = myFile.writer();

var x: int = 17;
var y: int = 19;
myWritingChannel1.write(x);
myWritingChannel2.writeln(y);`

**Comment by mppf** [comment]
@12mohaned - your two channels are writing to the same region of the file. The docs you quoted is really about supporting parallel access to different regions in the same file. It can be hard to write some of those with systems that use a "seek" call to set the file position.

**Comment by 12mohaned** [comment]
Okay, I got it but do I have to specify the location?, for example, explicitly stating where I wish to write to (end of the file or the beginning) or it is automatically specified based on the current empty positions.

**Comment by lydia-duncan** [comment]
We've adjusted the channel.write family of methods to no longer return a bool, so the answer to this issue is "no"
