### ISSUE TITLE
Intermittent segfault in Cron llvm testing

### ISSUE THREAD

**Issue by daviditen** [chapel-lang/chapel#17185]
### Summary of Problem
The test:
test/studies/dedup/dedup-externblock.chpl

Segfaults in the "Cron llvm" configuration approximately 1/1000 times it is executed. I verified that it fails in this intermittent way at least as far back as 2/1/2021.

### Steps to Reproduce

**Source Code:**
test/studies/dedup/dedup-externblock.chpl

**Compile command:**
chpl --cc-warnings --llvm dedup-externblock.chpl

**Execution command:**
./dedup-externblock dedup-test

### Configuration Information
% chpl --version
chpl version 1.24.0 pre-release (4ded86dee5)
  built with LLVM version 11.0.1
Copyright 2020-2021 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)

% printchplenv --anonymize
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: none *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_REGEXP: re2
CHPL_LLVM: system *
CHPL_AUX_FILESYS: none

% gcc --version
gcc (GCC) 8.3.0

**Comment by daviditen** [comment]
Dropping the `--llvm` argument so we use the C backend also segfaults. The segfault is happening deep in the OpenSSL library starting from the `SHA1` call in the test. If I change the main `forall` loop into a `for` loop it appears to always work. It seems we have a problem with calling SHA1 in parallel.

https://www.openssl.org/docs/man1.0.2/man3/threads.html
> OpenSSL can generally be used safely in multi-threaded applications provided that at least two callback functions are set, the locking_function and threadid_func.

I don't think we've done anything to set those callback functions. I don't know if there are reasonable defaults if you don't explicitly set them.

**Comment by bradcray** [comment]
Nice sleuthing!  Tagging @mppf on this as the author of the test in case he didn't end up subscribing of his own accord.

**Comment by mppf** [comment]
I think this is actually the same problem as #11366 but the steps to fix it are different. (Here, modify the test; on the other issue, modify the Crypto module).

**Comment by bradcray** [comment]
Thank you, Michael!
