### ISSUE TITLE
Add fullmatch method to regexp

### ISSUE THREAD

**Issue by leekillough** [chapel-lang/chapel#17216]
Python 3.4 adds `fullmatch` to its `re` module.

`fullmatch` or `fullMatch` should be added to the Chapel `regexp`, supplementing `search` and `match`.

Chapel and its RE2 interface already has support for specifying no anchor, a beginning anchor, or a beginning and ending anchor.

**Comment by leekillough** [comment]
There is the start of an implementation (in code comments) in #17209 .

Do we consistently use `camelCase` starting with lowercase for methods, in which case we should use `fullMatch`, or do we allow multi-word names without camelCase, such as `fullmatch`? In Python, it's called `fullmatch`.

**Comment by bradcray** [comment]
> Do we consistently use camelCase starting with lowercase for methods, in which case we should use fullMatch, or do we allow multi-word names without camelCase, such as fullmatch? In Python, it's called fullmatch.

We try to be fairly consistent about using camelCase, where the argument for an exception would be that the two/multiple words are sufficiently compound / technical / hyphenated / thought of as one word to warrant being thought of as one.  Given that rule of thumb, I'd say that `fullMatch` makes more sense for Chapel than `fullmatch`.
