### ISSUE TITLE
Set 

### ISSUE THREAD

**Issue by zhihuidu** [chapel-lang/chapel#17214]
### Summary of Problem

What behavior did you observe when encountering this issue?
When I use set to keep the frontier vertices in  breadth first search (BFS) algorithm, for a special line graph, the program with 2 locales will break down. However, When I use Domain or DistBag to keep the vertices, no errors happen.

The  delaunay benchmark will cause the same error too. 
https://sparse.tamu.edu/DIMACS10/delaunay_n17
 

### Steps to Reproduce

**Source Code:**
The BFS codes can be accessed here
https://github.com/Bader-Research/arkouda/blob/graph-multilocales/src/SegmentedMsg.chpl#L2357

```chapel
// Please provide source code that will reproduce the problem.
// You can insert your code inline if it's not too long.
// Otherwise, you can attach it as a file or provide a URL to it.
// To the extent possible, providing simplified programs demonstrating the
// problem will be appreciated.
// You can also replace this section with "Associated Future Test(s)" below.
```
**Execution command:**
The server side will start an arkouda like this
./arkouda_server -nl 2

the client side is like this
python bfs.py nodexx 5555

If an input file is required, include it as well. -->
The line graph is just like this 
0 1
1 2
2 3
3 4
4 5
5 6
...
999 1000

**Comment by bradcray** [comment]
@dlongnecke-cray : Tagging you on this as the original Set author.  I'm not sure what your bug/code freeze week looks like, but it'd be interesting to know if you can reproduce this / see an easy fix.  (I was able to reproduce it in an early version of the code, but didn't dig into it enough to determine the cause).

**Comment by bradcray** [comment]
(PS — If you don't have time to take it on, maybe we could find someone else to pick it up).

**Comment by dlongnecke-cray** [comment]
Hi, I could take on a point or two to look into this, but I suspect my first goal would be to find a simpler reproducer.

**Comment by bradcray** [comment]
I agree that that's the right first step, and don't think it would be too hard to divorce the algorithm in question from Arkouda.

**Comment by zhihuidu** [comment]
It seems that two cases can trigger the error: (1) many times of set assignments/add  will be done (the line graph case); (2) many vertices will be added to the set (the delaunay case).  Please let me know if you need more information.

**Comment by bradcray** [comment]
Yeah, rather than boiling the code down to a reproducer, it might be worth just creating some stress tests that push hard on set operations in parallel (assuming we don't already have them; if we do, it may be possible to determine the differences between them and the algorithms here by inspection).

**Comment by dlongnecke-cray** [comment]
What is the error? Is it a runtime error? A race condition?

**Comment by bradcray** [comment]
Segfault-ish.  See: https://gitter.im/ArkoudaProject/community?at=601c9400063b6c68d53d3913

**Comment by bradcray** [comment]
(Also, note that this is in a multi-locale setting;  @zhihuidu, have you tried running your algorithms with a single locale to see if the problem persists or goes away?)

**Comment by zhihuidu** [comment]
*** Caught a fatal signal (proc 0): SIGSEGV(11)
NOTICE: Before reporting bugs, run with GASNET_BACKTRACE=1 in the environment to generate a backtrace.
NOTICE: We recommend linking the debug version of GASNet to assist you in resolving this application issue.
Segmentation fault
@bradcray I just run it again with a single locale, no error

**Comment by zhihuidu** [comment]
This is the erro information with 4 locales.
current locale=LOCALE0 has elements ={}
current locale=LOCALE2 has elements ={}
current locale=LOCALE3 has elements ={}
current locale=LOCALE1 has elements ={475}
SetCurF= {475} SetNextF={476} level 477 numCurf=1
*** Caught a fatal signal (proc 0): SIGSEGV(11)
NOTICE: Before reporting bugs, run with GASNET_BACKTRACE=1 in the environment to generate a backtrace.
NOTICE: We recommend linking the debug version of GASNet to assist you in resolving this application issue.
Segmentation fault

**Comment by dlongnecke-cray** [comment]
Thanks, I'll start by writing a comm stress test for `set`.

**Comment by zhihuidu** [comment]
This is the error if I use 3 locales.

current locale=LOCALE0 has elements ={}
current locale=LOCALE2 has elements ={}
current locale=LOCALE1 has elements ={557}
SetCurF= {557} SetNextF={558} level 559 numCurf=1
*** Caught a fatal signal (proc 0): SIGSEGV(11)
NOTICE: Before reporting bugs, run with GASNET_BACKTRACE=1 in the environment to generate a backtrace.
NOTICE: We recommend linking the debug version of GASNet to assist you in resolving this application issue.
Segmentation fault

**Comment by dlongnecke-cray** [comment]
Initial observation...

```chapel
use Set;

class C { var x = 0; }

record r {
  var c = new shared C(-1);

  proc init(id: int) {
    this.c = new shared C(id);
  }

  proc init(other: r) {
    this.c = other.c;
  }

  proc init=(rhs: r) {
    this.c = rhs.c;
  }
}

proc =(ref lhs: r, rhs: r) {
  lhs.c = rhs.c;
}

proc test1() {
  writeln('T1');
  var st = new set(r);

  for loc in Locales do on loc {
    var x = new r(here.id);
    st.add(x);
  }

  writeln(st);
}
test1();
```

I consistently get a segfault on `-nl 12` or higher.

Bug on resize? Let's see...

**Comment by zhihuidu** [comment]
how about you replace 
for loc in Locales do on loc
with
coforall loc in Locales 
so we can check what happens when add in parallel?

**Comment by zhihuidu** [comment]
use Set;
use Random;
proc test2() {
  writeln('T2');
  var st = new set(int,parSafe = true);

  var R = new owned RandomStream(int, 1);
  coforall loc in Locales  with (ref st){
    on loc {
        coforall i in 0..(R.getNext())% 100     with (ref st) {
            st.add(here.id*R.getNext());
        }
    }
  }

  writeln(st);
}
test1();
test2();
@dlongnecke-cray Based on your test code test1(). I write test2() and it will generate the same error when nl >1

**Comment by zhihuidu** [comment]
proc test2() {
  writeln('T2');
  var st = new set(int,parSafe = true);

  var R = new owned RandomStream(int, 1);
  coforall loc in Locales  with (ref st){
    on loc {
        coforall i in 0..max((R.getNext())% 10,5)     with (ref st) {
            st.add((here.id+1)*(R.getNext()%100));
            writeln("My locale=",here.id," i=",i, "  set=",st);
        }
    }
  }

  writeln(st);
}

node678-71 examples >: ./set -nl 2
T1
{(c = {x = 1}), (c = {x = 0})}
T2
My locale=0 i=0  set={-3, -21}
My locale=0 i=3  set={-24, -3, 23, -21}
My locale=0 i=5  set={-24, -3, 23, -21}
My locale=0 i=1  set={-24, -3, 23, -21}
My locale=0 i=4  set={-24, -3, 23, -21, 64}
My locale=0 i=2  set={-94, -24, -3, 23, -21, -37, 64}
My locale=1 i=0  set={-58, -80, -94, -24, -3, 23, -36, -21, -37, 64}
My locale=1 i=5  set={-58, -80, -94, -24, -3, -144, 23, -36, -21, -37, 64}
My locale=1 i=1  set={-21, -36, -24, -80, -37, -144, -3, -94, -58, 64, 23, -10}
My locale=1 i=2  set={-21, -36, -24, -80, -37, -144, -3, -94, -58, 64, 23, -10}
My locale=1 i=3  set={-21, -36, -24, -80, -37, -144, -3, -94, -58, 64, 23, -10}
My locale=1 i=4  set={-21, -36, -24, -80, -37, -144, -3, -94, -58, 64, 23, -10}
{-21, -36, -24, -80, -37, -144, -3, -94, -58, 64, 23, -10}
*** Caught a fatal signal (proc 0): SIGSEGV(11)
NOTICE: Before reporting bugs, run with GASNET_BACKTRACE=1 in the environment to generate a backtrace.
NOTICE: We recommend linking the debug version of GASNet to assist you in resolving this application issue.
*** Caught a fatal signal (proc 1): SIGSEGV(11)
NOTICE: Before reporting bugs, run with GASNET_BACKTRACE=1 in the environment to generate a backtrace.
NOTICE: We recommend linking the debug version of GASNet to assist you in resolving this application issue.
Segmentation fault
__________________
I update the test2 and the outpput is given as above.

**Comment by zhihuidu** [comment]
login-1-56 examples >: ./set -nl 16
T1
{(c = {x = 5}), (c = {x = 0}), (c = {x = 2}), (c = {x = 13}), (c = {x = 7}), (c = {x = 11}), (c = {x = 15}), (c = {x = 9}), (c = {x = 6}), (c = {x = 1}), (c = {x = 8}), (c = {x = 3}), (c = {x = 14}), (c = {x = 12}), (c = {x = 10}), (c = {x = 4})}
T2
the up bound =14
My locale=0 i=1 add 62  set={-6, 28, 62}
My locale=0 i=12 add -6  set={-6, 28, -75, 62}
My locale=0 i=7 add -75  set={-6, 28, -75, 62}
My locale=0 i=2 add 53  set={-6, 28, -75, 62, 53}
My locale=0 i=9 add 39  set={-6, 28, -75, 62, 53, 39}
My locale=0 i=10 add 28  set={-6, 28, -75, 62, 53, 39}
My locale=0 i=4 add 79  set={79, -6, 28, -75, 62, 53, 39}
My locale=0 i=11 add -95  set={79, -95, -6, 28, -75, 62, 53, 39}
My locale=0 i=3 add -62  set={79, -95, -6, 28, 16, -62, -75, 62, 53, 39}
the up bound =5
the up bound =7
the up bound =5
My locale=0 i=0 add 16  set={79, -95, -6, 28, 16, -62, -75, 62, 53, 39}
the up bound =5
the up bound =10
the up bound =27
the up bound =5
My locale=2 i=3 add 90  set={79, -95, -6, 28, 16, 90, -62, -75, 62, 53, 39}
<internal>: error: Out of memory allocating "tasking layer unspecified data"
@bradcray when I use more locales, it has another error.

**Comment by zhihuidu** [comment]
proc test2() {
  writeln('T2');
  var st = new set(int,parSafe = true);

  var R = new owned RandomStream(int, here.id);
  coforall loc in Locales  with (ref st){
    on loc {
        var num=max((R.getNext())% 30,5);
        writeln("the up bound =", num);
        coforall i in 0..num     with (ref st) {
            var x=(here.id+1)*(R.getNext()%100);
            st.add(x);
            writeln("My locale=",here.id," i=",i, " add ",x, "  set=",st);
        }
    }
  }

  writeln(st);
}

**Comment by dlongnecke-cray** [comment]
@bradcray So adding an `on` block to `set.add()` will fix the issue, but it causes an extra copy to be made every time something is added to a set.

The same issue exists for `map` as well.

In order to fix this, we would have to support: https://github.com/chapel-lang/chapel/issues/15808

Alternatively, for the time being we could either:

- Just introduce the extra copy
- Add a halt that suggests the user migrate to `this` first?

**Comment by bradcray** [comment]
Does adding the `on` cause the copy to always happen, or to happen only when the `Set` is remote?  If "always", would putting the on-clause into an "if local ... else handle the remote case..." conditional get rid of the copy for the local case?  (i.e., would the copy happen locally to the else-clause, or would it happen always because the compiler would have to be conservative about the conditional?)

Tagging @mppf on this due to his involvement on #15808.

> Add a halt that suggests the user migrate to this first?

To me, this seems approach seems counter to Chapel's global address space philosophy (as does the segfault :) ).

**Comment by mppf** [comment]
@dlongnecke-cray - can't we use the https://chapel-lang.org/docs/master/modules/standard/Memory/Initialization.html#Initialization.moveInitialize and friends to do this? I think the problem in issue #15808 is just that we probably want the library author to have to opt in to it. And Memory.Initialization allows that today, doesn't it?

**Comment by dlongnecke-cray** [comment]
I tried your suggestion and rewrote `_addElem` to make use of `moveToValue`:

```chapel
    // Returns true if the key was added to the hashtable.
    pragma "no doc"
    proc _addElem(pragma "no auto destroy"
                  pragma "error on copy" in elem: eltType): bool {
      import Memory.Initialization.moveToValue;

      var result = false;

      on this {
        var moved = moveToValue(elem);
        var (isFullSlot, idx) = _htb.findAvailableSlot(moved);
        if !isFullSlot {
          // I still see an init= call occurring right here:
          _htb.fillSlot(idx, moved, none);
          result = true;
        }
      }

      return result;
    }
```

But I still see an `init=` call occurring for the actual of the `_htb.fillSlot()` call.

**Comment by dlongnecke-cray** [comment]
I made https://github.com/chapel-lang/chapel/issues/17307 to capture the copy elision problems I'm experiencing.

**Comment by dlongnecke-cray** [comment]
Hi @zhihuidu, #17346 should hopefully have fixed your issue. If it has not, feel free to open this issue back up and ping me.

**Comment by zhihuidu** [comment]
@dlongnecke-cray thanks and the latest version can run the test successfully.
