### ISSUE TITLE
Should tertiary methods be defined for regex?

### ISSUE THREAD

**Issue by leekillough** [chapel-lang/chapel#17226]
Should tertiary methods be defined for `regexp`?

| Method                                                       | Description                            |
| :---                                                           | :---                                   |
| `proc string.search(needle: string, ignorecase=false):reMatch` | Search for needle regexp in string     |
| `proc bytes.search(needle: bytes, ignorecase=false):reMatch`   | Search for needle regexp in bytes      |
| `proc string.search(needle: regexp(string)):reMatch`           | Search for a compiled regexp in string |
| `proc bytes.search(needle: regexp(bytes)):reMatch`             | Search for a compiled regexp in bytes  |
| `proc string.match(pattern: regexp(string)):reMatch`           | Match a regexp to string               |
| `proc bytes.match(pattern: regexp(bytes)):reMatch`             | Match a regexp to bytes                |
| `proc string.match(pattern: regexp(string), ref captures ...?k):reMatch` | Match a regexp in string, returning captures |
| `proc bytes.match(pattern: regexp(bytes), ref captures ...?k):reMatch`   | Math a regexp in bytes, returning captures |
| `iter string.split(pattern: regexp(string), maxsplit: int = 0)` | Split string with regexp |
| `iter bytes.split(pattern: regexp(bytes), maxsplit: int = 0)`   | Split bytes with regexp |
| `iter string.matches(pattern:regexp(string), param captures=0, maxmatches:int=max(int))` | Returns matches and captures on string |
| `iter bytes.matches(pattern:regexp(bytes), param captures=0, maxmatches:int=max(int))` | Returns matches and captures on bytes |

- Do we want to define tertiary methods which operate on `string` and `bytes`, or should we keep the number of interfaces smaller, and only provide methods on `regexp` class? \
\
The methods on `regexp` are generic, and work for either `string` or `bytes`, while the tertiary methods have to be defined for `string` and `bytes` separately, but they are usually just wrappers to the generic `regexp` methods.

- Do we want to provide methods which compile regular expressions "on the fly" (caching the compiled result), or should we require the user to [compile the regexp](https://github.com/chapel-lang/chapel/issues/17187) separately?

**Comment by lydia-duncan** [comment]
I think we should keep the tertiary methods

**Comment by bradcray** [comment]
> I think we should keep the tertiary methods

@lydia-duncan: Can you say more about why?

> The methods on regexp are generic, and work for either string or bytes, while the tertiary methods have to be defined for string and bytes separately, but they are usually just wrappers to the generic regexp methods.

I understand that the tertiary methods don't add new power relative to the more general methods, but how much convenience do they add?  Could someone supply an example of a code snippet comparing code with the tertiary methods vs. without?

Engin's point the other day about `"Bradford".search("Brad")` looking a lot like a substring find method rather than indicating anything about regular expressions being involved or compiled left an impression on me.  Nothing in that expression makes me think it's any different from `"Bradford.find("Brad")` (which I think relates to Lee's question about:

> should we require the user to compile the regexp separately?

)

**Comment by lydia-duncan** [comment]
It's more I'm not convinced there's a problem with having them so why take the effort to remove them?  They seem useful.  I think the burden of proof should be more on why they should be removed.

**Comment by bradcray** [comment]
For me, it's the point I attributed to Engin above.  Nothing about the calls make it obvious that it's regex-related.  And maybe what convenience they provide is minimal compared to the alternatives (which is why I've been curious to see a comparison of the two approaches).

**Comment by lydia-duncan** [comment]
> Nothing about the calls make it obvious that it's regex-related.

That seems easily solved by renaming rather than removing.  Is the functionality not valuable?  I can see "maybe this isn't valuable enough to discuss a new name" but it seems like there's a pretty obvious change (add Regex or regex to the name) so I would argue that adding a deprecation warning and remembering to eventually remove the function is more time consuming.

**Comment by leekillough** [comment]
I think we should should add a `regex_` prefix to these methods if we keep them. I agree with Brad and Engin that nothing in `"Bradford".search("Brad")` indicates it's a regex search. `"Bradford".regex_search("Brad")` would be more clear. I don't mind having to go through the deprecation process.

**Comment by e-kayrakli** [comment]
I still feel the same way as Brad described above. But maybe a different way to look at the same argument is that these are methods on strings (or bytes) that take string (or bytes) arguments. So, why are they in the Regex module? The fact that they use regular expressions as internal machinery is not a strong enough motivation for an interface decision to me.

> That seems easily solved by renaming rather than removing. Is the functionality not valuable? I can see "maybe this isn't valuable enough to discuss a new name" but it seems like there's a pretty obvious change (add Regex or regex to the name) so I would argue that adding a deprecation warning and remembering to eventually remove the function is more time consuming.

From the user's perspective, I would argue that renaming and removing are equally breaking and as such, if we break the status quo, we should be fine with just removing the functionality. Then, this discussion is akin to whether we should add `string.regexMatch(string)` method or not. In that scenario my vote would be "no" again without a compelling use case.

Lee's argument about asking for pre-compiled regular expression is another interesting direction. But then, I don't see too much value in the resulting function(s) `string.match(regex)` because we already have `regex.match(string)` and all the other ones, if I'm not mistaken.

**Comment by e-kayrakli** [comment]
Note that there are also string/bytes slicing based on `regexMatch` values. [Documented here.](https://chapel-lang.org/docs/master/modules/standard/Regex.html#Regex.string.this)

While my opinions are not changed, I think there are three separate categories of tertiary methods in question:

(I only use `string` for brevity below. Everything applies to `bytes` as well)

## Tertiary methods on `string` that takes `string` arguments

| Method                                                       | Description                            |
| :---                                                           | :---                                   |
| `proc string.search(needle: string, ignorecase=false):reMatch` | Search for needle regexp in string     |


I feel pretty strongly that these should go away. Nothing in the interface tells me that this uses regular expressions. This is pretty close to `string.find`. If you want something more regular expression based, you should create a compiled regular expression and use `regex.search`.

We can argue whether we should make both of these methods named `find` or `search`, though.

## Tertiary methods on `string` that takes `regex` arguments

| Method                                                       | Description                            |
| :---                                                           | :---                                   |
| `proc string.search(needle: regexp(string)):reMatch`           | Search for a compiled regexp in string |
| `proc string.match(pattern: regexp(string)):reMatch`           | Match a regexp to string               |
| `proc string.match(pattern: regexp(string), ref captures ...?k):reMatch` | Match a regexp in string, returning captures |
| `iter string.split(pattern: regexp(string), maxsplit: int = 0)` | Split string with regexp |
| `iter string.matches(pattern:regexp(string), param captures=0, maxmatches:int=max(int))` | Returns matches and captures on string |

I am more open to these, but don't see much benefit from them. Note that for all method that looks like `string.foo(r:regex)`, there's a corresponding `regex.foo(s:string)`. Which, to me, is much more intuitive. I also believe this is a case where we just clutter the interface by providing multiple ways of doing the same thing. 

## Tertiary `string` slicer

| Method                                                       | Description                            |
| :---                                                           | :---                                   |
| `proc string.this(m: regexMatch)` | extracts the part of a string matching a regular expression or capture group     |

This is not noted in the OP. I think this is the most appealing tertiary method in the Regex module.

```chapel
use Regex;

var s = "bar 123 bar";
var r = compile("[0-9]+");

var match = r.search(s);
writeln(s[match]);
```

is pretty neat and can be useful. If we were to remove this, we'd have to do:

```chapel
writeln(s[match.offset..#match.size]);
```


---

@lydia-duncan, you said

>  I think the burden of proof should be more on why they should be removed.

I am not ready to buy this argument. I think we need to scrutinize the existing interfaces as if we are creating them from scratch. I'd buy the argument in the post-2.0 world. A slightly related argument could be, "it is a breaking change, and thus we should avoid it". But I think it is a different argument which should be supported by some real code that would break significantly by the change.

As for your suggestion for renaming them to have `regex` in them, my argument against it is still

> From the user's perspective, I would argue that renaming and removing are equally breaking and as such, if we break the status quo, we should be fine with just removing the functionality. Then, this discussion is akin to whether we should add string.regexMatch(string) method or not. In that scenario my vote would be "no" again without a compelling use case.

**Comment by mppf** [comment]
FWIW I am relatively convinced by @e-kayrakli's arguments above and am leaning towards removing all of them other than the string/bytes slicing by regexMatch.

**Comment by lydia-duncan** [comment]
> From the user's perspective, I would argue that renaming and removing are equally breaking and as such, if we break the status quo, we should be fine with just removing the functionality.

I don't think that's true.  Yes, both cases will result in a user having to update their code, but the update is much more drastic in the case of removal - now the user has to think about how to implement something they were relying on someone else implementing, potentially resulting in a performance hit if the function was optimized in some non-obvious way or bugs to their program later if they weren't good about testing their new solution.  Whereas in the case of a renaming they could easily write a script that updates their program to use the new name and are unlikely to have to think about the change again in the future.

**Comment by e-kayrakli** [comment]
> Tertiary methods on string that takes string arguments

This "group" is discussed under https://github.com/chapel-lang/chapel/issues/18960

---

> Tertiary methods on string that takes regex arguments

We like the functionality this category has, but we don't like the interface. We are going to make this category more like the next one -- mostly identical to base string interface, only taking regex arguments. Specifically:

#### `proc string.search(needle: regexp(string)):reMatch`

Will be replaced with `proc string.find(needle: regexp(string)):byteIndex`. We can also add other arguments of `string.find` here. There's also `rfind`, which I am not sure if it is easy to implement. I think any of these can come as a follow up.

Note also that [we don't love the argument name `needle`](https://github.com/chapel-lang/chapel/issues/18264).

#### `proc string.match(pattern: regexp(string)):reMatch`

We will replace this with `proc string.startsWith(needle: regexp(string)):bool`. We will deprecate other versions of `match` (the one that "returns" captures, and `matches`)

#### `iter string.split(pattern: regexp(string), maxsplit: int = 0)`

This was supposed to be in the third category. However, we should rename the argument `pattern` to `sep` and potentially add `ignoreEmpty` argument.

---

> Tertiary string slicer

We are happy with this category, and will add more methods like this. See above.

**Comment by slnguyen** [comment]
Summarizing the above comments, I plan to make the following changes:

 1. Replace:
`proc string.search(pattern: regex(string), ref captures ...?k): regexMatch` and
`proc bytes.search(pattern: regex(bytes), ref captures ...?k): regexMatch`
with:
`proc string.find(pattern: regexp(string)):byteIndex`
`proc bytes.search(pattern: regexp(bytes)):byteIndex` 

2. Replace
`proc string.match(pattern: regex(string), ref captures ...?k): regexMatch` and
`proc bytes.match(pattern: regex(bytes), ref captures ...?k): regexMatch`
with:
`proc string.startsWith(pattern: regexp(string)):bool` and
`proc bytes.startsWith(pattern: regexp(bytes)):bool`

3. Remove 
`iter string.matches(pattern: regex(string), param captures = 0, maxmatches: int = max(int))` and
`iter bytes.matches(pattern: regex(bytes), param captures = 0, maxmatches: int = max(int))`

4. Rename `pattern` to `sep` argument for split function, i.e.
Rename:
`iter string.split(pattern: regexp(string), maxsplit: int = 0)` and
`iter bytes.split(pattern: regex(bytes), maxsplit: int = 0)`
to:
`iter string.split(sep: regexp(string), maxsplit: int = 0)` and
`iter bytes.split(sep: regex(bytes), maxsplit: int = 0)`

**Comment by lydia-duncan** [comment]
With #19622 merged, this can now be closed
