### ISSUE TITLE
Should Regexp be a standard module or a package?

### ISSUE THREAD

**Issue by leekillough** [chapel-lang/chapel#17220]
Should `Regexp` module be a standard module as it is today, or should it be a package?

Should it be bound to the RE2 library, or should other regular expression libraries be allowed?

Is there a certain common denominator set of regular expression features which should be supported, such as Basic or Extended POSIX regular expressions, Perl-Compatible Regular Expressions (with many variants, such as RE2, PCRE, etc.)?

**Comment by bradcray** [comment]
My opinion here isn't strong, but here's what it is:

>Should Regexp module be a standard module as it is today, or should it be a package?

* I think that many programmers consider regex matching to be a fairly core feature of a language, so would be inclined to have an official/standard Regex capability within Chapel, just as a "batteries included" type of feature.

> Should it be bound to the RE2 library, or should other regular expression libraries be allowed?

* If we support a standard Regex capability, as in the previous bullet, I don't think that should preclude the introduction of other regex package libraries to support other approaches.

* I don't know enough about various regex libraries to know whether RE2 is the best choice for our standard approach or not.  If we think RE2 is an ideal solution for us, I think we should make it our standard implementation; if we don't, I'd be inclined to make it a package module, rename it something more like RE2, and keep the standard module slot open for some other technology to fit into.

> Is there a certain common denominator set of regular expression features which should be supported, such as Basic or Extended POSIX regular expressions, Perl-Compatible Regular Expressions (with many variants, such as RE2, PCRE, etc.)?

I don't know enough to have an opinion here, but to the extent that there are agreed upon standards that we can conform to, that seems attractive.

**Comment by leekillough** [comment]
I think that unless we use POSIX regular expressions, we are going to bound to the syntax and features of whichever library we choose, and will be locked into supporting them. I don't think we can simply "import" an RE package and have it work with a universal interface and syntax in Chapel.

POSIX extended regular expressions are only slightly "extended" from POSIX basic regular expressions, by swapping things like `(` and `)` with `\(` and `\)` and adding support for `+`, `?` and `|`.

POSIX extended regular expressions don't have as much power as RE2's Perl-compatible regular expressions, in that they don't support captures or lookahead/lookbehind assertions, and they don't support short-named character classes like `\w`, `\d` and `\s`, and you instead have to use long names like `[[:alnum:]_]`, `[[:digit:]]` and `[[:space:]]`, respectively.

POSIX "enhanced" extended regular expressions support back-references (like `(this):\1`) which RE2 doesn't support, but I don't consider back-references to be quite as essential as capturing, which POSIX regular expressions don't support. Back-references allow the matching of something captured earlier in the same regular expression, but they don't take the place of actually supporting captures which can be extracted later from a match.

If RE2 is stable, license-compatible, and close enough to Python's `re` module, I think we should stick with it.

**Comment by leekillough** [comment]
It looks like we will keep `Regex` as a standard module. Unless there is a need to keep this discussion going, I can close this issue.
