### ISSUE TITLE
Should the Regexp module and regexp record be renamed Regex and regex, respectively?

### ISSUE THREAD

**Issue by leekillough** [chapel-lang/chapel#17222]
`Regexp` and `regexp` are less common spellings than `Regex` and `regex`, and are harder to pronounce.

Here are some examples of regular expressions in several languages:

| Language | Module / Package / Header | Regexp Class / Record | Match Class / Record | 
| :-- | :-- | :-- | :-- |
| Chapel | `Regexp` | `regexp` | `reMatch` |
| C++11 | `<regex>` | `std::regex` | `std::match_results` |
| Python | `re` | `Pattern` | `Match` |
| Java | `java.util.regex` | `Pattern` | `Matcher` |
| Perl | _(built-in)_  | n/a | n/a |
| Ruby | _(built-in)_ | `Regexp` | `MatchData` |
| JavaScript | _(built-in)_ | `RegExp` | n/a |
| C# | `System.Text.RegularExpressions` | `Regex` | `Match` |

[Here is a humorous take on Regex vs other spellings](http://www.rexegg.com/regex-vs-regular-expression.html)

Google search results (case-insensitive, searching for whole words):

| Regex | Regexp | Re | Regexpr | 
| :-- | :-- | :-- | :-- |
| 20M | 5.65M | 3.39M | 42600 |

**Comment by bradcray** [comment]
I find `Regex` much more straightforward to type / think about / pronounce than `Regexp` and am in favor of this change, barring a compelling argument for why `Regexp` is preferable.

**Comment by leekillough** [comment]
What is the process for renaming modules or types?

With types we cannot mark them as deprecated right now ( https://github.com/chapel-lang/chapel/issues/14396 ), but we can use type aliases to keep the old name around, as in:
```chpl
   record regex { 
   // ...
   }

   type regexp = regex;  // deprecated name
```

Is there a way to mark a module as an alias of another module, or to export all symbols in one module inside another? Because I don't think this will work:
```chpl
module Regexp {
   use Regex;
 }

use Regexp;
```
All of `Regex`'s public symbols will be imported into `Regexp`, but they will not be imported by `use Regexp`.

If we follow deprecation practices, we would need to write all of `Regex`'s functions as wrappers in `Regexp` along with deprecation warnings.

**Comment by bradcray** [comment]
Others are probably more experienced here than I am, but to get a quick response out:  To deprecate a module, I'd probably just do a code clone and then add a `compilerWarning()` to the old module's top-level statement list that refers to the new module.

To deprecate a type, I believe you can create a paren-less type function that returns the new type and generates a deprecation warning:

```chapel
proc oldTypeName: type {
  compilerWarning("...");
  return newTypeName;
}
```

**Comment by lydia-duncan** [comment]
Probably not an identical case, but I added deprecation warnings for the IO module when we made it no longer included by default.  Here's the PR that removed those (which I found faster than the one that added them): https://github.com/chapel-lang/chapel/pull/15500

**Comment by leekillough** [comment]
> To deprecate a module, I'd probably just do a code clone and then add a compilerWarning() to the old module's top-level statement list that refers to the new module.

Could you use `config` variables to do something like preprocessing, ala:
```
Regexp.chpl:

#define REGEX Regexp
#include "regex.inc"

Regex.chpl: 

#define REGEX Regex
#include "regex.inc"
```
Could some config variable be used to create the two modules from the same source?

**Comment by bradcray** [comment]
Chapel doesn't have textual substitution as part of the pre-processor.  But if you want to avoid the code clone, I believe that you should be able to re-export a module's symbols by doing:

```chapel
module Regexp {
   public use Regex;
  compilerWarning("...deprecation warning here...");
 }
```

**Comment by leekillough** [comment]
Thanks; that's much better than cloning code.
