### ISSUE TITLE
core dump when passing a slice to a generic inout formal

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#17241]
The compiler is creating code that seg-faults at runtime when passing a slice to a generic inout formal.

### Steps to Reproduce

**Source Code:**

```chapel
proc f(inout arg) {
  writeln("in f, arg= ", arg);
  arg = 1;
}
{
  var A:[1..10] int;
  ref slice = A[1..3];
  f(slice);
  writeln(slice);
  writeln(A);
}
```

In 1.22, the program runs cleanly under valgrind and prints:

```
in f, arg= 0 0 0
1 1 1
1 1 1 0 0 0 0 0 0 0
```

In 1.23, the program segfaults.

The issue started with 8ef988d2fbf01dc865f0be921e19d1f66f2e363e / PR #16143 and was not resolved in PR #16180.

**Associated Future Test(s):**
[`test/functions/intents/inout/in-conversion-inout-slice-formal-generic.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/functions/intents/inout/in-conversion-inout-slice-formal-generic.chpl
          ) #17231

**Comment by bradcray** [comment]
The role of slices in this issue catches my attention.  Let me know if it's something that would benefit from my help.

**Comment by mppf** [comment]
In 1.22, the formal is a ref to a slice array, and the formal-tmp is a DR array.
But now, the formal-tmp (at the call site) is a DR array but the formal in f is a slice array. We need to arrange for the formal to be a DR array.
