### ISSUE TITLE
Update Types.chpl to have isNothing in addition to isNothingType

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#17254]
Most of the functions in Types.chpl have variants along the lines of `isRecord()` that work for both types and values.

However we have `isNothingType` but not `isNothingValue` or `isNothing`.

I find `isNothingValue` a bit strange but would at least expect Types.chpl to include `isNothing`.

**Comment by mppf** [comment]
@daviditen - do you know of a reason we don't have `isNothing` today?

**Comment by daviditen** [comment]
> do you know of a reason we don't have `isNothing` today?

No I don't. I think it should be fine to add it.

**Comment by 12mohaned** [comment]
I pulled an open request [here](https://github.com/chapel-lang/chapel/pull/17286).
