### ISSUE TITLE
Local blocks thwart copy elision

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#17272]
In https://github.com/chapel-lang/chapel/pull/17258#pullrequestreview-598571497, @mppf points out that copy elision is currently thwarted by local blocks (for `--no-local` compilations) in a way that compound statements are not, and that the two should be treated more similarly.  The following test exhibits this:

```chapel
record R {
  var x:int;
  proc init() {
    writeln("in R.init");
    this.x = 1;
  }
  proc init=(other: R) {
    writeln("in R.init=");
    this.x = other.x;
  }
}

proc test1() {
  writeln("test1");
  var x = new R();
  {
    var y = x; // should copy elide
    writeln(y);
  }
}
test1();

proc test2() {
  writeln("test2");
  var x = new R();
  local {
    var y = x; // should copy elide
    writeln(y);
  }
}
test2();
```

The action here is to update the compiler's copy elision analysis to treat local blocks more similarly to compound statements, potentially using the code in PR #17258 as a guide.

**Comment by mppf** [comment]
I've created PR #17285 to fix this but it still needs testing.
