### ISSUE TITLE
Support for C unions by c2chapel

### ISSUE THREAD

**Issue by souris-dev** [chapel-lang/chapel#17278]
Currently, the `c2chapel` tool does not recognize a C union while converting definitions in C headers to Chapel extern definitions.
On experimentation, it was found that C unions can indeed be treated in a similar way as C structs are treated while working with C interoperability.

Hence, this code, where the C union is treated as a struct (example given by @bradcray) runs as expected:

**File**: *testit.h*
```c
typedef union _u {
  int x;
  unsigned y;
} u;

extern void setX(int x);
extern int getX(void);
extern unsigned getY(void);
```

**File**: *testit.c*
```c
#include "testit.h"

u myU;

void setX(int x) {
  myU.x = x;
}

int getX() {
  return myU.x;
}

unsigned getY() {
  return myU.y;
}
```

**File**: *testit.chpl*
```c
use SysCTypes; // get definitions of c_int, c_uint                              

require "testit.h", "testit.c"; // C code defining union                        

// reflect C code here                                                          
extern record u {
  var x: c_int;
  var y: c_uint;
}
extern proc setX(x: c_int);
extern proc getX(): c_int;
extern proc getY(): c_uint;

// create and modify union from Chapel:                                         
var myChplU: u;

myChplU.x = -3: c_int;
writeln(myChplU.x);
writeln(myChplU.y);

// create and modfiy C union through routines:                                   
setX(-3);
writeln(getX());
writeln(getY());
```

As the union shows the expected behavior of a C union (confirmed by experimentation), it should be good to be added as a recognized node in the `c2chapel` tool.

**Comment by souris-dev** [comment]
This seems fairly implementable to me, so I'm currently giving it a try. Will open a PR when finished.

**Comment by bradcray** [comment]
Great, thanks @souris-dev!  If you run into challenges, let us know and we'll try to find someone to help.

**Comment by souris-dev** [comment]
@bradcray I opened a PR a few days back (I wasn't sure if I should be mentioning it here separately, thanks for letting me know about this), would appreciate feedback! Thanks!
