### ISSUE TITLE
Docs for interoperability should include C unions

### ISSUE THREAD

**Issue by souris-dev** [chapel-lang/chapel#17294]
While reading up on support for C unions for C interoperability in Chapel, I found that the docs at https://chapel-lang.org/docs/language/spec/interoperability.html mention how C structs are to be treated, but do not mention anything about how C unions should be treated.
On experimentation, it was found that they can be treated the same way as C structs (by declaring an `extern record` for the C union), as noted in issue #17278.

I think it would be a good addition to the documentation. If this is agreed upon, I can get to it.

**Comment by bradcray** [comment]
@souris-dev: This sounds good to me.
