### ISSUE TITLE
Cast operator methods get confusing error about number of formals

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#17325]
### Summary of Problem

Attempting to make use of the new cast operator support in combination with the new operator method capability, I wrote the following program:

```chapel
record R {
  var x: sync int;

  proc init=(x: int) {
    this.x = x;
  }

  operator :(x: int, type t: R) {
    return new R(x);
  }
}

var myR: R = 3;
```

which generates the following error message:

```bash
testit.chpl:8: error: cast function should have two formals
```

which is confusing since it does have two formals.  Moving the cast operator to a standalone operator (rather than a method) solves the problem, but prevents the cast from being associated with a type.

### Steps to Reproduce

**Associated Future Test(s):**

TODO

### Configuration Information

- Output of `chpl --version`: `chpl version 1.24.0 pre-release (ce03a6ea8a)`

**Comment by bradcray** [comment]
@lydia-duncan: In case you're not already aware of this case...

**Comment by lydia-duncan** [comment]
I was not aware of it.  I wonder if it is because technically the function now has four formals (due to the inserted method token and "this" arguments)

**Comment by bradcray** [comment]
Could be, though wouldn't that apply to all operator methods?  (or do we not check argument counts for other operator methods?)

**Comment by lydia-duncan** [comment]
I don't think we do, but I could be wrong.
