### ISSUE TITLE
internal error when defining a secondary initializer on missing type

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#17323]
### Summary of Problem
We see an internal error with the below code but it should rather be a user-facing one.

### Steps to Reproduce

**Source Code:**

```chapel
proc R.init(arg: int) { } // internal error
//proc R.foo() { }  error: 'R' undeclared (first use this function)
```

```
$ chpl bb.chpl 
bb.chpl:1: internal error: 'this' argument has unknown type [passes/normalize.cpp:4473]
```

**Associated Future Test(s):**

none yet

**Comment by mppf** [comment]
Noting that the internal error is the same one as in #15718.

**Comment by lydia-duncan** [comment]
That's very disappointing, but hopefully an easy fix?

**Comment by lydia-duncan** [comment]
It looks like this has now been resolved, so I'll add a test and close it
