### ISSUE TITLE
`use ... only BaseClass` prevents resolution of base's fields on unmanaged instances of a child type

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#17362]
If you have a `BaseClass` on its own file:

```chapel
class BaseClass {
  var baseField = 20;
}
```

and a `ChildClass` that inherits it from a different file, but limits the `use`
statement to have `only BaseClass`:

```chapel
use BaseModule only BaseClass;
// use BaseModule;   // this `use` works

class ChildClass: BaseClass {
  var x = 10;
}

{ // compiles
  var c: owned ChildClass? = new owned ChildClass();
  writeln(c!.baseField);
}

{ // compiles
  var c: shared ChildClass? = new shared ChildClass();
  writeln(c!.baseField);
}

{ // doesn't compile with `use BaseModule only BaseClass`
  //var c: unmanaged ChildClass? = new unmanaged ChildClass();
  //writeln(c!.baseField);  // cannot resolve this
}

{ // compiles
  var c: owned ChildClass = new owned ChildClass();
  writeln(c.baseField);
}

{ // compiles
  var c: shared ChildClass = new shared ChildClass();
  writeln(c.baseField);
}

{ // doesn't compile with `use BaseModule only BaseClass`
  //var c: unmanaged ChildClass = new unmanaged ChildClass();
  //writeln(c.baseField);   // cannot resolve this
}
```

unmanaged instances of the `ChildClass` cannot resolve the field inherited from
the `BaseClass`.

It works if:

- the instances are owned or shared
- the file is `use`d as a whole
- you use Chapel 1.23.0 (I am using bb2a7770869e78be9f42cc62d113de476db60a8c)

**Comment by shubhamkmr04** [comment]
The following issue is not appearing in my local. Can you please check the attached files or did I do something wrong?
![Screenshot from 2021-03-07 12-10-41](https://user-images.githubusercontent.com/50761978/110231562-7a362200-7f3e-11eb-8246-4013f547a649.png)
![Screenshot from 2021-03-07 12-10-43](https://user-images.githubusercontent.com/50761978/110231567-7bffe580-7f3e-11eb-9196-45e8d765e351.png)
![Screenshot from 2021-03-07 12-11-02](https://user-images.githubusercontent.com/50761978/110231568-7c987c00-7f3e-11eb-8eec-fb2a9d3d58d4.png)

**Comment by lydia-duncan** [comment]
Huh, that's weird.  I wouldn't expect unmanaged to fail if the other cases work.  Weird.  I'll add this to my todo list.

> @shubhamkmr04 - it looks like maybe you're working from the 1.23 release?  This may be a bug introduced to master since then.

**Comment by e-kayrakli** [comment]
I confirm that my code in the OP works on 1.23. I updated the post.

@shubhamkmr04 -- note that you also have some differences from the code that I have posted above (can see an `import`, a module level variable in `BaseModule`). While I can't say how they can change the behavior, but by definition bugs are generally weird edge cases, and small changes can impact the behavior unexpectedly.

**Comment by shubhamkmr04** [comment]
> Huh, that's weird. I wouldn't expect unmanaged to fail if the other cases work. Weird. I'll add this to my todo list.
> 
> @shubhamkmr04 - it looks like maybe you're working from the 1.23 release? This may be a bug introduced to master since then.

Yes @lydia-duncan , I am using the 1.23 release.

**Comment by shubhamkmr04** [comment]
> I confirm that my code in the OP works on 1.23. I updated the post.
> 
> @shubhamkmr04 -- note that you also have some differences from the code that I have posted above (can see an `import`, a module level variable in `BaseModule`). While I can't say how they can change the behavior, but by definition bugs are generally weird edge cases, and small changes can impact the behavior unexpectedly.

@e-kayrakli My code is giving the same output after not using an import

**Comment by lydia-duncan** [comment]
It looks like this has since been resolved again.  I'll add in a test to ensure it continues to work going forward
