### ISSUE TITLE
online man page renders double-dash (`--`) options using n-dash

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#17385]
It seems that the process which converts our man page into an HTML page converts `--` options into an n-dash, a la LaTeX.  This seems potentially very confusing since it looks to a reader like the flags are single-dash flags.  For example:

<img width="678" alt="Screen Shot 2021-03-09 at 11 23 02 AM" src="https://user-images.githubusercontent.com/7536222/110525827-e85b2000-80c9-11eb-8972-6c4d4b702d2e.png">

would be better if it looked more like `--baseline` (two hyphens or two n-dashes).

Note that a (hopefully minor?) challenge here is the need to preserve the output of `man chpl` as well where the double-dashes are rendered properly.

**Comment by bradcray** [comment]
I'm half tempted to put easy / good first issue on here because I suspect that the fix will be something fiddly, but reasonably straightforward and independent of the majority of our code base.  But I also am not sure I know enough to lead it effectively.

**Comment by shubhamkmr04** [comment]
@bradcray I would like to work on the issue. I have installed Chapel in my local but I can't figure out how can I open the Chapel's official website in my localhost. Can you guide me through it?

**Comment by bradcray** [comment]
@shubhamkmr04 : If I'm understanding your question, once you have a working installation of Chapel, you should be able to do: `make docs` and then point your web browser at `$CHPL_HOME/doc/html/usingchapel/man.html` to see the web-rendered man page (which should look something like this:  https://chapel-lang.org/docs/usingchapel/man.html).  For example, on my Mac, I can just do: 

```bash
$ cd $CHPL_HOME
$ make docs
$ open doc/html/usingchapel/man.html
```

If you're working from the 1.23 release rather than the main development branch at GitHub, you may also need to do `make man` for this to work (I believe the `make docs` target only started building the man page recently).

If you're asking something else, and it's more general about how to do something with your Chapel installation, it may make sense to take the question to our Gitter channel or Discourse website (each of which are linked to from the main Chapel webpage in the sidebar icons or the user/developer resources links).

**Comment by bradcray** [comment]
[for those subscribed to this issue: I've made an edit to the OP to note something that I hadn't thought of in the original statement of it which is that we need to ensure that the solution continues to render properly from the command-line's `man chpl` perspective as well].

**Comment by shubhamkmr04** [comment]
@bradcray I am currently using the 1.23 release. I am getting some error on the "make docs" command. I have asked it on gitter. I would try to solve this issue as soon as I resolve the error.

**Comment by bradcray** [comment]
@shubhamkmr04: Since any code contributions you make for this project will require a PR against the development branch (`master`), I'd suggest cloning that branch and working from there rather than the 1.23 release.  Starting from an official release is a good way to get familiar with Chapel, but once you're ready to do some coding, it only really makes sense to start from the current development branch.

**Comment by Venkatavaradan-R** [comment]
Found the culprit!

Sphinx has a configuration option called `html_use_smartypants` that causes this behavior. It's been set to False in [doc/rst/conf.py](https://github.com/chapel-lang/chapel/blob/master/doc/rst/conf.py) line 195.

The problem was being caused because `html_use_smartypants` is now deprecated and has been replaced with `smartquotes` hence making that one change in the file fixes the problem.

**Comment by shubhamkmr04** [comment]
Hey @Venkatavaradan-R, I was working on this issue. I have already got my PR ready

**Comment by Venkatavaradan-R** [comment]
That's fine by me, I'm not making a PR. I was just trying to help out :)

**Comment by shubhamkmr04** [comment]
![Screenshot from 2021-03-14 15-36-54](https://user-images.githubusercontent.com/50761978/111064691-71fc5a80-84db-11eb-9a7b-b03b9a301c89.png)
@bradcray  Can you help me with this? Why am I not able to create pull request?
