### ISSUE TITLE
Errors within internal modules don't result in `--print-callstack-on-error` callstacks?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#17406]
When we generate a compiler error in an internal operator overload, it doesn't seem to result in a callstack that includes the internal module function calls even in `--devel` mode (it's not surprising that it wouldn't in `--no-devel` / default mode, as we try to paper over internal module errors, often unsuccessfully).  Unfortunately, because this is specific to internal modules, it (a) only affects developers and advanced users, and (b) is difficult to reproduce in a standalone test.  Here's how I'm reproducing:

1) Drop some routines like the following into ChapelBase.chpl:

```chapel
  proc int_bar(x: int, y: uint) {
    var z = x + y;
  }

  proc int_foo() {
    int_bar(1, 1);
  }
```

2) Compile the following program using `--print-callstack-on-error --devel`

```chapel
proc main() {
  bar();
}

proc bar() {
  foo();
}

proc foo() {
  int_foo();
}
```

The result lists the stack frames in the user code, but not the internal modules:

```bash
testit.chpl:9: In function 'foo':
testit.chpl:10: error: illegal use of '+' on operands of type uint(64) and signed integer
  testit.chpl:6: called as foo() from function 'bar'
  testit.chpl:2: called as bar() from function 'main'
```

where I thought that the `--devel` flag was supposed to print all frames including the ones from internal modules.

**Comment by bradcray** [comment]
Wait wait wait...

**Comment by bradcray** [comment]
I was sprinting too fast to reproduce this in a standalone program and messed up.  The error seems specific to the operator being called from an internal module (or, at least, a non-user module).  Unfortunately, this makes it harder to create a reproducer for since it requires modifying an internal module...

**Comment by bradcray** [comment]
I verified that this behavior was specific to internal, not standard, modules, and updated the OP with instructions to reproduce.  Sorry for those who got a completely broken version of this issue in their inboxes.  I've been meaning to capture this for a week now, and didn't take as much time to get my test right as I should've before opening it.

**Comment by lydia-duncan** [comment]
If you wanted to add a test to the testing system of this, test/modules/paths/checkNestedModule.chpl or checkReexported*.chpl in the same directory would be a good template iirc

**Comment by bradcray** [comment]
Ooh, sneaky!

**Comment by mppf** [comment]
Maybe isInternalFunction is returning true and that's squelching it? Does `--preserve-inlined-line-numbers`  change the behavior? I suspect that findLocationIgnoringInternalInlining or findNonTaskFn is hiding it, because otherwise I'd expect an "In function" line referring to the internal module.

**Comment by bradcray** [comment]
> Maybe isInternalFunction is returning true and that's squelching it?

From what I can see, it isn't called when `--devel` is thrown.

> Does --preserve-inlined-line-numbers change the behavior?

Not in the cases I've seen.  I usually throw `--no-inline` to try and minimize the impact of inlined procedures.
