### ISSUE TITLE
set intersection

### ISSUE THREAD

**Issue by zhihuidu** [chapel-lang/chapel#17401]
I declair three sets A,B,C as follows
var A= new set(int,parSafe = true);
var B= new set(int,parSafe = true);
var C= new set(int,parSafe = true);

When I do set intersection

C=A&B;

the compiler will give the following compiling errors. 
$CHPL_HOME/modules/standard/Set.chpl:198: In method 'init=':
$CHPL_HOME/modules/standard/Set.chpl:200: error: Cannot replace an instantiated param field with another value
$CHPL_HOME/modules/standard/Set.chpl:200: note: field 'parSafe' has value 'false' but is set to 'true'
  $CHPL_HOME/modules/standard/Set.chpl:669: called as (set(int(64),false)).init=(other: set(int(64),true)) from function '&'
  set.chpl:97: called as &(a: set(int(64),true), b: set(int(64),true))
note: generic instantiations are underlined in the above callstack

However, if I declair A, B, and C as follows,

var A= new set(int);
var B= new set(int);
var C= new set(int);
the compliler can pass it .
If I declair A, B without  parSafe = true, does it mean that parallel element adding will have problem? for example

Forall i in X with (ref A) {
     A.add(i);
}

**Comment by zhihuidu** [comment]
@dlongnecke-cray

**Comment by bradcray** [comment]
@zhihuidu : This looks like a bug on our part.  I'm able to reproduce it but not explain it.  Question for @mppf: It appears that we're using `init=` on line 7 (`C = A&B;`), but since `C` is initialized at its declaration point, I wouldn't expect this.  Do you see why it would be?

**Comment by mppf** [comment]
It looks to me like it is a problem with this:

https://github.com/chapel-lang/chapel/blob/ad2226bb0a9d9c91821752a81f665067f9de6112/modules/standard/Set.chpl#L643-L644

Here, because `parSafe=false` by default, this function always returns a `parSafe=false` set, by converting from `result`. But, what was the point of computing the type `set(t, (a.parSafe || b.parSafe))` if we were not going to return it? Removing the declared return type from this function allows the compilation to get further but leads to const-checking errors related to the `forall`.

This patch fixes these:

<details>

```
diff --git a/modules/standard/Set.chpl b/modules/standard/Set.chpl
index 0d3f6512d7..08c61ad5a5 100644
--- a/modules/standard/Set.chpl
+++ b/modules/standard/Set.chpl
@@ -640,13 +640,13 @@ module Set {
     :return: A new set containing the intersection of `a` and `b`.
     :rtype: `set(t)`
   */
-  proc &(const ref a: set(?t, ?), const ref b: set(t, ?)): set(t) {
+  proc &(const ref a: set(?t, ?), const ref b: set(t, ?)) {
     var result: set(t, (a.parSafe || b.parSafe));
 
     /* Iterate over the smaller set */
     if a.size <= b.size {
       if a.parSafe && b.parSafe {
-        forall x in a do
+        forall x in a with (ref result) do
           if b.contains(x) then
             result.add(x);
       } else {
@@ -656,7 +656,7 @@ module Set {
       }
     } else {
       if a.parSafe && b.parSafe {
-        forall x in b do
+        forall x in b with (ref result) do
           if a.contains(x) then
             result.add(x);
       } else {
```

</details>

I used this complete program to reproduce:

<details>

``` chapel
use Set;

var A= new set(int,parSafe = true);
var B= new set(int,parSafe = true);
var C= new set(int,parSafe = true);

C=A&B;
```

</details>

**Comment by mppf** [comment]
I created PR #17403 with the change - I expect to get to finishing it after the release freeze.

**Comment by dlongnecke-cray** [comment]
Good catch with the return type not matching the result type. Clearly didn't think that one through, thanks!

**Comment by bradcray** [comment]
Thanks Michael!

> It looks to me like it is a problem with this:

Ah, so was I misdiagnosing by thinking that the `init=` was complaining about `C` when it was actually referring to a variable inside the function?  (I was admittedly going fast trying to get through the weekend's email accumulation).

> Clearly didn't think that one through, thanks!

Are there potentially other cases like this lurking that additional testing would reveal?  E.g., searching the file, I'm seeing other cases that have a declared return type like that.

**Comment by dlongnecke-cray** [comment]
> Are there potentially other cases like this lurking that additional testing would reveal? E.g., searching the file, I'm seeing other cases that have a declared return type like that.

Probably. I can go ahead and write some more tests/cleanup other operators in conjunction with the PR from @mppf.

**Comment by mppf** [comment]
@dlongnecke-cray - if you want to grab the changes in #17403 & build on it please feel free to open your own PR and we can close mine.
