### ISSUE TITLE
chpldoc formats `typeexpr` differently for `type t = typeexpr` and `var x: typeexpr`

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#17414]
chpldoc formats `typeexpr` differently for `type t = typeexpr` and `var x: typeexpr` for some `typeexpr`s.  This is because `printingType` is false for the former, but true for the latter.  This results in

```chapel
type t = 2*int;
var x: 2*int;

param w = 32;
type t2 = int(w/2);
var x2: int(w/2);
```

being formatted

```rst
.. type:: type t = 2 * int

.. data:: var x: 2*(int)

.. data:: param w = 32

.. type:: type t2 = int(w / 2)

.. data:: var x2: int(w/2)
```

I think the type expressions in the `type` lines should be formatted the same as the ones in the `var`  lines.

_Originally posted by @cassella in https://github.com/chapel-lang/chapel/issues/17372#issuecomment-792564967_

**Comment by piyush0411** [comment]
Also, can you please direct me to the files that need to be changed, I mean the ones where these two types - `type` and `var` are defined. I went through the codebase but couldn't find the right ones.

Thanks :)

**Comment by lydia-duncan** [comment]
> @lydia-duncan - Will passing the parameter `printingType` as `true` for the first case solve this issue?

I suspect only in certain cases.  You'll want to do an analysis of when printingType is set to each value and what the impact of that is.  I suspect it is still the right choice in many of the calls but that there is probably someplace where we should determine which is used via an if statement.

> Also, can you please direct me to the files that need to be changed, I mean the ones where these two types - `type` and `var` are defined. I went through the codebase but couldn't find the right ones.

`type` and `var` symbols are both defined as VarSymbols in the AST, which are defined in compiler/include/symbol.h and compiler/AST/symbol.cpp.  The difference between the two is handled by the presence of a flag, and can be determined by calling the `isType()` method on a particular VarSymbol instance.

**Comment by piyush0411** [comment]
@lydia-duncan - How are the different `expr` classes like `DefExpr`, `SymExpr` etc are defined in the `expr.cpp` files? Could you point me to some documentation for this.

**Comment by lydia-duncan** [comment]
Generally in our compiler, if the declaration isn't in the file itself, you can find it in a similarly named header file in the `compiler/include` directory

**Comment by piyush0411** [comment]
Could you please tell me what the input file should look like for the changes I have made?
If I run the command `make docs`, I am encountering the following error.
```
Creating symlinks
ln: failed to create symbolic link 'rst/tools/chpldoc/man.rst': File exists
make[2]: *** [Makefile:111: symlinks] Error 1
make[2]: *** [Makefile:171: error_docs] Error 1
make[1]: *** [Makefile:58: docs] Error 2
make: *** [Makefile.devel:26: docs] Error 2

```
Could you please see to this?

**Comment by lydia-duncan** [comment]
> Could you please tell me what the input file should look like for the changes I have made?

The input file should match what is described at the beginning of this issue.

> If I run the command `make docs`, I am encountering the following error.
> 
> ```
> Creating symlinks
> ln: failed to create symbolic link 'rst/tools/chpldoc/man.rst': File exists
> make[2]: *** [Makefile:111: symlinks] Error 1
> make[2]: *** [Makefile:171: error_docs] Error 1
> make[1]: *** [Makefile:58: docs] Error 2
> make: *** [Makefile.devel:26: docs] Error 2
> ```
> 
> Could you please see to this?

That's interesting and unexpected but based on the output, I kinda suspect you ran `make docs` in the doc directory?  Does it behave correctly when you run from $CHPL_HOME?

**Comment by piyush0411** [comment]
> Does it behave correctly when you run from $CHPL_HOME?

Actually, I am running it from the  $CHPL_HOME only.
I have built chapel from the source. So I run the following commands
```
cd chapel
make chpldoc
make check-chpldoc
```
These commands run perfectly fine and I receive the following output in the terminal.
```
Running the chpldoc tests found in: /home/piyush/chapel/test/release/examples
Testing /home/piyush/.chpl/chapel-test-me7KY/chpldoc.doc.chpl ... 
[done]
chpldoc installation works as expected!
```
However, when I run the `make docs` command, I encounter the error
```
Creating symlinks
ln: failed to create symbolic link 'rst/usingchapel/man.rst': File exists
make[2]: *** [Makefile:110: symlinks] Error 1
make[2]: *** [Makefile:171: error_docs] Error 1
make[1]: *** [Makefile:58: docs] Error 2
make: *** [Makefile.devel:26: docs] Error 2
```
Is there any error in the above commands?

**Comment by lydia-duncan** [comment]
> Is there any error in the above commands?

I don't think so, but that's also a different error than the one you reported before

**Comment by piyush0411** [comment]
>I don't think so, but that's also a different error than the one you reported before

Yes, I noticed it too. Could you please tell me how to resolve this?

Also regarding this issue, I think solving this issue, I think the following change might help.
```
{
      mText += expr->sym->name;
      if (expr->exprType) {
        mText += ": ";
        appendExpr(expr->exprType, true);
      }
      if (expr->init) {
        mText += " = ";
        if (SymExpr* sym = toSymExpr(expr->init))
          appendExpr(sym, true, true);
        else
          appendExpr(expr->init, true);
      }
    }
```
I have changed the arguments in [L1627](https://github.com/chapel-lang/chapel/blob/master/compiler/AST/AstToText.cpp#L1627) and [L1629](https://github.com/chapel-lang/chapel/blob/master/compiler/AST/AstToText.cpp#L1629) of [AstTpText.cpp](https://github.com/chapel-lang/chapel/blob/master/compiler/AST/AstToText.cpp).
I think this should work but I couldn't test them due to the error.

**Comment by cassella** [comment]
Based on the error and the lines in `doc/Makefile` that create those symlinks, I'm thinking you have a `doc/rst/usingchapel/man.rst` symlink that points to a file that doesn't exist.  (That would cause the `-e path` to fail, so it'll try to create a new symlink.  Then that fails because there already is a symlink by that name and the `-f` option isn't given.)  Possibly from a previous run of `make docs` without `$CHPL_HOME` set?

If so, I'd try removing them.  There may be a lot in different directories (given the other error in a different directory), so it may be easiest to try a `make clobber` or a `git clean` if you're comfortable with that.  (If you haven't used `git clean` before, be sure to read the man page as it may delete files you don't want it to if you don't tell it not to.)

**Comment by piyush0411** [comment]
Thanks @cassella - I was able to produce the docs using the above steps.
