### ISSUE TITLE
[Website] "Chapel by Example: Image Processing" link is broken

### ISSUE THREAD

**Issue by ayuagrawal** [chapel-lang/chapel#17435]
Please visit the https://chapel-lang.org/learning-read.html, click on "I like to read." 
Link under "I'd like to read an example-oriented introduction to Chapel." is Try [Chapel by Example: Image Processing](http://www.primordand.com/chapel_by_ex.html) by Greg Kreider (PMVS). But this is redirecting to wrong page. Currect page should be http://primachvis.com/html/imgproc_chapel.html. It may also good to mention that unfortunately this pdf book work only for version below 1.18.

**Comment by bradcray** [comment]
@ayuagrawal : Thanks for pointing this out, which obviously escaped me.  You've also made me curious what it would take to upgrade the code to work with Chapel again; I suspect it would not be terribly painful and that the authors just wasn't sufficiently motivated to do it.  Could be a fun spare-time activity...

**Comment by bradcray** [comment]
@ayuagrawal : I believe I've fixed the broken links now, and have fired off the question about upgrading the code to Chapel 1.24 as its own issue in https://github.com/chapel-lang/chapel/issues/17436.  Thanks again for reporting this.

**Comment by ayuagrawal** [comment]
Thank @bradcray for updating link. 

At some point chapel community may also want to open source website code.

**Comment by bradcray** [comment]
I made a push to open-source the website over the past few months, but the challenge is that it is larger than a free GitHub repository permits.
