### ISSUE TITLE
Implement a parallel Chapel pidigits implementation

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#17441]
Chapel once held the land-speed record for the Computer Language Benchmarks game for [pidigits](https://benchmarksgame-team.pages.debian.net/benchmarksgame/performance/pidigits.html), but has recently fallen behind other implementations.  It seems that the current best entry, written in C++, is parallel given its CPU load (100% 100% 98% 100%).  This raises the question: What would a port of this approach look like in Chapel, and how competitive would it be?

**Comment by bradcray** [comment]
(I labeled this as a good first issue, though that probably only applies to someone who is familiar with C++ and parallel programming...)

**Comment by niralii** [comment]
How about we use CHPL_GMP and CHPL_ATOMICS as defaults since C++ has used that?

**Comment by bradcray** [comment]
Chapel's [`BigInteger` module](https://chapel-lang.org/docs/modules/standard/BigInteger.html) is defined in terms of GMP, provides a cleaner interface to bigint computation, and is used by our other implementation, so I'd use that instead of the GMP module.  And CHPL_ATOMICS isn't really a user-facing feature in and of itself, it's just a specification of how Chapel's [`atomic` types](https://chapel-lang.org/docs/builtins/Atomics.html#:~:text=Atomic%20variables%20are%20variables%20that,named%20order%20of%20type%20memoryOrder%20.) are implemented.

I'd use both our [cleanest Chapel version](https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/pidigits-chapel-2.html) and the [parallel C++ version](https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/pidigits-gpp-6.html) as references and try to come up with a solution that tries to combine the best of both worlds: the clarity of the Chapel version with the parallelism of the C++ version written using Chapel's language concepts for parallelism and synchronization.

**Comment by rivalq** [comment]
I have written the "line by line" chapel version of the given [C++ code](https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/pidigits-gpp-6.html).  It is exactly the same implementation using chapel and its functions.
You can find the code [here](https://github.com/chapel-lang/chapel/files/7117075/code.chpl.zip)

I have compiled the code using the following command
```bash
chpl code.chpl --fast
```

I have run it for N = 10000 and it takes around 0.5 seconds on my local system

I am quite new to the chapel and parallel programming, In fact, the first time I wrote some parallel algorithm code.

I  used the **begin** statement for achieving parallelism. As of right now, I don't know much about the chapel's features and hence believe there is a large room of improvement.

**Comment by rivalq** [comment]
I have written the **line by line** chapel version of the given [C++ code](https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/pidigits-gpp-6.html).  It is exactly the same implementation using chapel and its functions. code is present [here](https://github.com/chapel-lang/chapel/files/7117184/code.chpl.zip)
 
I have compiled the code using the following command
```bash
chpl code.chpl --fast
```

I have run it for N = 10000 and it takes around 0.4 - 0.5 seconds on my local system

I am quite new to the chapel and parallel programming, In fact, the first time I wrote some parallel algorithm code.

I  used the **begin** statement for achieving parallelism. As of right now, I don't know much about the chapel's features and hence believe there is a large room for improvement.

**Comment by bradcray** [comment]
Hi @rivalq — Sorry for the delayed response here, and thanks for taking a look at this!  I'm afraid we're a bit underwater at present trying to get our fall release ready to go out the door, but I hope to look at your code when I get the chance to catch my breath again.

**Comment by bradcray** [comment]
@rivalq — Still completely underwater, and would completely enjoy looking at this more than anything else I have to do this week.  Just wanted you to know that I haven't forgotten.

**Comment by rivalq** [comment]
Yeah, its fine

**Comment by bradcray** [comment]
Hi @rivalq —

Finally found a little bit of time to start taking a look at this.  Running it on my Mac in our performance testing system, I'm seeing times of 0.78–0.84 seconds for your version on a problem size of 10,000 relative to 0.61–0.74 seconds for the Chapel versions that are already submitted to the shootout site.  Of course, this may or may not be meaningful, since the official site runs on a different system than I am.

So, I think there are a few ways we could proceed here (where these aren't mutually exclusive in any way):
1) I/we could review the code in more detail, comparing to the C++ version, to see whether we see obvious ways of improving it
2) I could review the code from a "Chapel coding style" perspective
3) you could open a PR adding your version to our repository, where we could enable it to be tested on all the platforms where we run these benchmarks to see if we see different results than I'm seeing on my Mac
4) you could submit your version to the CLBG site, see if it is accepted, and see what kind of results it gets on the actual HW / in the actual framework

Let me know if any of these appeal to you, and we can figure out next steps.

I think a few changes will be necessary before submitting it to either the official site or ours:
* rename `num_digits` to simply `n` (which I believe his Chapel scripts/Makefiles use `n` for the problem sizes of all the benchmarks)
* remove the timer/timing code (CLBG uses an external timer to time programs and diffs the output against what's expected, so taking an internal time and printing it is both redundant and will lead to a mismatch)

**Comment by rivalq** [comment]
Hi @bradcray 

I can review the C++ code and try to break the code into simpler parts to see why it is too fast. I don't know much about the chapel's functions for parallelism, In C++ the threads are mapped to functions at starting to the program, I tried to do the same thing using begin statement, maybe there we can improve.

Before submitting on the CLBG site, I think we should test the program on some other platforms as well.

**Comment by bradcray** [comment]
@rivalq: 

> I can review the C++ code and try to break the code into simpler parts to see why it is too fast.

I think that could be interesting: use sub-timers to see how much time various aspects of the program take / what rates they're going at, etc. and how the C++ and Chapel versions differ.

> I don't know much about the chapel's functions for parallelism, In C++ the threads are mapped to functions at starting of the program, I tried to do the same thing using begin statement, maybe there we can improve.

That seemed OK to me in the sense that it should spawn off some concurrent tasks at the beginning of the program / outside of the main loops.  So if the goal is to have four tasks (3 begins and the original) computing for the duration of the program, I think you've done the right thing.

One thing that I noticed yesterday but figured was intentional was that if I removed the `exit()` from the main task, the program did not terminate.  I was thinking that this was by design, but today I'm seeing that each of the thread routines seems to have a return in it, which makes me think that logic may not be working right?  (though I'm also noticing that I think nothing ever writes to `finish`, so it's not surprising that they keep running forever?).  Does the C++ version rely on an exit to tear down threads as well, or do they quit by themselves?  Note that I don't expect this to affect performance, but was just noticing it as being slightly odd.

Also, does the C++ version busy-wait on the atomics like this (simple while loop, reading until the value changes) vs. doing something different?  Given the small number of threads and the fact that each should have a core, I wouldn't expect this to affect things, but was just curious (I still haven't spent much time with the C++ version if you can't tell).

> I think we should test the program on some other platforms as well.

In that case, I think a good thing to do would be to open a PR that submits this as a performance test to our test system.  Specifically, I'd create a new directory called `test/studies/shootout/pidigits/[some new identifier—could be your userID or a description of the version, like `cpp6` or whatever]/` and then add your code there as a .chpl file (e.g., `pidigits-rivalq.chpl` or `pidigits-cpp6.chpl`.  Then I'd take all the files for a working version of the code like `test/studies/shootout/submitted/pidigits2.*` or `pidigits3.*` and make copies of them into your directory using the same base filename as your `.chpl` file.  (so, e.g. `cp .../pidigits2.good .../pidigits-[basename].good` or whatever).  Once you've done that, try doing `start_test pidigits-[basename].chpl` to see if that passes, and adjust the `.good` files if it doesn't.  Then try `start_test -performance pidigits-[basename].chpl` to see whether it works as a performance test as well.  Hopefully by basing your test off of pre-existing ones, this will be fairly easy to do, but documentation on the test system is available [here](https://github.com/chapel-lang/chapel/blob/main/doc/rst/developer/bestPractices/TestSystem.rst) or just feel free to ask questions.

Once you've got a draft that seems to be working, open a PR using the information [here](https://github.com/chapel-lang/chapel/blob/main/doc/rst/developer/bestPractices/ContributorInfo.rst), where the most important step to get right is to make sure your git commits are signed w.r.t. [the DCO](https://github.com/chapel-lang/chapel/blob/main/doc/rst/developer/bestPractices/DCO.rst).

Then, once it's merged (and with a minor adjustment to our graph files, which I'll take care of, we should start getting nightly results of the test on various platforms displayed on graphs like these: https://chapel-lang.org/perf/chapcs/?graphs=pidigitsvariations,submittedpidigitsshootoutbenchmark

Oh, and there are a few spelling errors in the code that it would be good to correct as well:  `multplierThread` -> `multiplierThread` and `exractThread` -> `extractThread`.

**Comment by rivalq** [comment]
@bradcray:
Sorry for the late reply, I got busy with my exams.
> One thing that I noticed yesterday but figured was intentional was that if I removed the exit() from the main task, the program did not terminate

I fixed this bug, threads were actually waiting inside the while loop at the line `extractCalculating.waitFor(true)`. So I just make these atomic variables true, and the program automatically exits.

> Also, does the C++ version busy-wait on the atomics like this (simple while loop, reading until the value changes) vs. doing something different?

In the C++ program, there is `stopThreads` function, which sets the value to `finish` to true and waits for all the 3 threads to get executed completely by the `join` method.

And for the PR, I followed your instructions. It passed the normal tests. But in the performance test, it shows below error
```bash
[Error matching performance keys for studies/shootout/pidigits/rivalq/pidigits-rivalq]
```

I looked into the `.perfkeys` file, In the first line `real` is written, so I found the line corresponding to it in the output of performance test and found this `Looking for real...didn't find it`. I am not sure what it means.

Also one more thing, at the compilation of program I got below warning:
```bash
warning: bigint.div_q using Round is deprecated, use bigint.divQ with round instead
```
so I replaced the `div_q` method with `divQ`. and also removed that warning part from `*.good` files.

**Comment by bradcray** [comment]
> And for the PR, I followed your instructions.

Cool!

> It passed the normal tests. But in the performance test, it shows below error

Aha, I forgot one step, sorry.  Try copying the `PERFTIMEEXEC` file from `test/studies/shootout/submitted` over to your directory as well.  This essentially says that the performance testing system should use an external timer to time the whole program execution, similar to the CLBG site itself, and will result in the `real` line in the output.  I believe that this should resolve the failure in performance testing that you were seeing.

**Comment by rivalq** [comment]
> Try copying the PERFTIMEEXEC file from test/studies/shootout/submitted over to your directory as well.

It worked , Although there is one warning related to performance graphs

**Comment by bradcray** [comment]
> Although there is one warning related to performance graphs

That is probably OK (and was going to be something I was going to fix up on our end after merging), but just to make sure:  What does the warning say?

**Comment by bradcray** [comment]
Ah, that one can definitely be ignored—don't worry about it.

**Comment by bradcray** [comment]
@rivalq: Thanks again for your efforts here.  The final version of the benchmark that we submitted is now ranked #2 on the site (!):  https://benchmarksgame-team.pages.debian.net/benchmarksgame/performance/pidigits.htm
<img width="887" alt="Screen Shot 2022-02-14 at 3 29 38 PM" src="https://user-images.githubusercontent.com/7536222/153964361-62bd1065-b3e3-4bb1-8c03-f9a16e2155ed.png">
l

**Comment by rivalq** [comment]
Wow, That is really Great. I don't know why we were getting different results on local system.
