### ISSUE TITLE
Add support for ranges over enums with a single value

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#17464]
### Summary of Problem

Given an enum with a single value:

```chapel
enum color { red };
```

ranges over that enum don't currently work:

```chapel
const r = color.red..color.red;
```

The root cause of this is that we don't have a good way to represent an empty range over the enum type since we usually use two distinct values to represent the empty range (e.g., `[the 1st element in the enum]..[the 0th element in the enum]`).

In this issue, I'm proposing that we should support such ranges, where the big question is what to do about default values.  Depending on how ranges are implemented, one could imagine either arguing that the default value of such a range is:
* an empty range that has no well-defined low/high bounds; or 
* the single-index range (e.g., `color.red..color.red` above) since that is the only value the range could use as its bounds

In our current implementation of ranges, the second option is easiest to achieve, though it has the slight downside of making the default value have a size of 1 where every other default range value has a size of 0.  If we wanted to keep option 1 open, we could have the language spec say that the language does not currently define the default value for such ranges; or we could lock the semantics of the current implementation in (which are implementable for any range representation).

**Associated Test(s):**
[`test/types/range/enum/singleValEnum.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/types/range/enum/singleValEnum.chpl
          ) #13655
[`test/types/range/enum/singleValEnum2.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/types/range/enum/singleValEnum2.chpl
          ) #13655
[`test/types/range/enum/singleValEnum3.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/types/range/enum/singleValEnum3.chpl
          ) #TODO

### Configuration Information

- Output of `chpl --version`: `chpl version 1.25.0 pre-release (cf3ecc7466)`

**Comment by bradcray** [comment]
Related: #13650

**Comment by bradcray** [comment]
Implementation in: https://github.com/chapel-lang/chapel/pull/17511

**Comment by vasslitvinov** [comment]
I like making ranges over `color` non-default-initializable.

This range, however:
```chpl
const r = color.red..color.red;
```

needs to work.

**Comment by bradcray** [comment]
> I like making ranges over color non-default-initializable.

Can you give a rationale for that stance?  (my counterargument would be "there are reasonable default values to select from; any time we have a type with no default-initial value it results in challenges like the ones we've recently been wrestling with, so the fewer the better.")

From a practical standpoint, making that choice would also make it challenging to support arrays or domains over such enum ranges without a major revamping of our module code because of the way we currently rely on default initialization for such types (e.g., `A[color.red..color.red]` relies on default initialization today of `range(color)` types today, so would be challenging to support as requested in #13650 without significant effort).

**Comment by vasslitvinov** [comment]
Here is my thinking. I see that we are choosing between:
(a) disallowing default and empty ranges over `color`,
(b) giving these ranges undefined bounds, and
(c) having the default range be non-empty.

I don't like (c) because it is inconsistent with other ranges.

Choosing between (a) and (b), I prefer "disallowing" because it puts the problem explicitly in front of the user, rather than doing something unusual silently.

OTOH if (a) would cause us undue hardship in our own code, then there is a good chance that it would for users, too. So maybe it is an argument against that option.

**Comment by bradcray** [comment]
> I don't like (c) because it is inconsistent with other ranges.

For me, when a type only has a single legal value it can store, it makes sense to have its default value be that value.

**Comment by dlongnecke-cray** [comment]
In my gut, it feels like the default value for an enum range should span the entire enum, but that's probably beyond the scope of this issue.

With that being said, I feel like:

> (c) having the default range be non-empty

Is the right thing to do both to avoid adding more non-default-initializable cases to the language and because it stays consistent with my gut feeling.

**Comment by vasslitvinov** [comment]
I am fine with whatever choice others think is right.

**Comment by dlongnecke-cray** [comment]
> I am fine with whatever choice others think is right.

You can't say that @vasslitvinov, that's my line!

**Comment by bradcray** [comment]
> it feels like the default value for an enum range should span the entire enum, but that's probably beyond the scope of this issue.

That's an interesting perspective.  It would address @vasslitvinov's asymmetry concern by treating all enum ranges the same.  But it may make him unhappy by making all enum ranges different from integer ranges.

I'm disinclined to go that direction for a few reasons:
* I think default values should generally be something like a "zero" value for the type, and an empty range feels more like a "zero" than a fully populated range does.  For that reason, I'd make the asymmetry here be between ranges over single-element enums and multi-element enums rather than between ranges over enums and ranges over anything else.
* we used to have associative domains over enums (`domain(myEnum)`) default to "contains all indices" because it seemed like the common / useful case, but eventually moved away from it after several years so that it wouldn't be different from other [associative] domains in this respect (i.e., domains default to the empty set).  This feels similar such that I feel if we took this approach for ranges, we'd need to re-reverse our decision on associative domains of enums—and that's a decision I haven't ever second-guessed.

That said, I agree that this is mostly a topic for another issue if you want to propose it (I'm not going to :) ).

**Comment by mppf** [comment]
> an empty range that has no well-defined low/high bounds; or

I favor this approach but I understand it is harder to do.

It seems to me that any default-initialized range should be an empty range.

Anyway, isn't this related to the problems with maximal uint ranges? E.g. 0..255 on `range(uint(8))` ? For example, if we were to adjust the range implementation to differentiate between open and closed upper bounds, wouldn't both of these be relatively straightforward to handle?

**Comment by BryantLam** [comment]
> In our current implementation of ranges, the second option is easiest to achieve, though it has the slight downside of making the default value have a size of 1 where every other default range value has a size of 0

I'm against this approach because it breaks consistency. Some language features may want to break consistency because it's natural to do, but IMO having to remember the behavior of ranges between different types is not one of them.

**Comment by BryantLam** [comment]
(Deleted my previous comment. I misread the proposal.)

I'm okay with the second option to allow a range syntax on single-value enums. It seems natural to allow a range syntax over an enum with a single value insofar as it's what would similarly happen with any runtime container with a single element.

**Comment by BryantLam** [comment]
> > I don't like (c) because it is inconsistent with other ranges.
> 
> For me, when a type only has a single legal value it can store, it makes sense to have its default value be that value.

At the risk of derailing, what's the behavior / why doesn't this happen with enums with more than one value? I agree with @vasslitvinov  and would err on the side of consistency.

**Comment by bradcray** [comment]
> why doesn't this happen with enums with more than one value?

If you have enums with more than one value, you can define an empty range using `myEnum.value1..myEnum.value0` to create a situation where the low bound is > the high bound.  If you have enums with just one value, there are no distinct low and high bounds that can be used to represent the range.

> isn't this related to the problems with maximal uint ranges?

To me, it seems related, but distinct.  `0..max(uint)` has other challenges such as how to represent its size, for example.

> For example, if we were to adjust the range implementation to differentiate between open and closed upper bounds, wouldn't both of these be relatively straightforward to handle?

If we changed our implementation of ranges, then there are a number of ways we could represent this case.  The main question that comes out of that approach to me is what `r.low` and `r.high` would return (e.g., maybe one would return the enum value and the other would halt?).

**Comment by mppf** [comment]
>      If we changed our implementation of ranges, then there are a number of ways we could represent this case. The main question that comes out of that approach to me is what r.low and r.high would return (e.g., maybe one would return the enum value and the other would halt?).

Well we have unbounded ranges, so I'd expect it'd do whatever we do for `(1..).high`. It looks like today that returns `0` which doesn't make any sense to me either. (Not sure I like halt better though). In the specific single element enum case, the corresponding thing would be for `const r: range(idxType=color);` to produce a range with size 0 and both of `low` and `high` are `color.red`.

I think it'd be better for `(1..).high` to not return `0` but I'm not sure what it should do instead. But it seems reasonable to me for it to correspond to this enum case.

**Comment by bradcray** [comment]
> Well we have unbounded ranges, so I'd expect it'd do whatever we do for (1..).high. It looks like today that returns 0 which doesn't make any sense to me either.

This sounds like an oversight in the implementation, or like someone accidentally broke it at some point and testing didn't catch it.  `.hasHighBound()` returns param `false` for upper-unbounded ranges, and I would've expected `range.high` to lean on that query to generate a compilerError() for `(1..).high`.  However, I'd expect `.hasHighBound()` to return `true` for open-interval ranges.  

More generally, I wouldn't expect a range's open- or closed interval-ness to be part of its static type information.  That is, I think we should be able to do:

```chapel
var r = 1..10;
r = 1..<10;
var r2 = 1..<10;
r2 = 1..10;
```

> and both of low and high are color.red.

I don't think that `1..10` and `1..<10` should both return 10 as their high bound because then code has to be sensitive to what kind of range it's looping over when doing something like:  `for i in r.low..r.high by 2` (and it's a fairly huge breaking change to the current range definition and implementation).

**Comment by mppf** [comment]
Right.


> 
> > and both of low and high are color.red.
> 
> I don't think that `1..10` and `1..<10` should both return 10 as their high bound because then code has to be sensitive to what kind of range it's looping over when doing something like:  `for i in r.low..r.high by 2` (and it's a fairly huge breaking change to the current range definition and implementation).

I'm not sure I follow what the implication for the enum case is.

Say we have `const r: range(idxType=color);`. Then we have a few questions:
(a) what is `r.size` and what does `for i in r` do?
(b) what does `r.low`, `r.high`, and `for i in r.low..r.high` do?

In the original post we have 2 strategies

1. an empty range that has no well-defined low/high bounds

  * for (a), `r.size` is 0 and `for i in r` would run the loop 0 times
  * for (b), maybe `r.low` and `r.high` are `color.red` or maybe they are some sort of runtime error.
  
2. the single-index range (e.g., color.red..color.red above) since that is the only value the range could use as its bounds

  * for (a), `r.size` is 1 and `for i in r` would run the loop 1 times
  * for (b), `r.low` and `r.high` are `color.red`.

My point in all of this is that I care about the difference between 1. and 2. only for (a). I don't really care about what (b) does. (So we could have `r.low` and `r.high` both be `color.red` but still have the range have 0 elements; or it could be an error. In the event it's not an error though you could argue that `for i in r` and `for i in r.low..r.high` should do the same thing but then I'd argue back that it already doesn't for unbounded ranges).

**Comment by bradcray** [comment]
> > > and both of low and high are color.red.
> ...
> I'm not sure I follow what the implication for the enum case is.

It sounds like I misunderstood your point.  I thought you were saying that we'd represent the empty range as `color.red..<color.red` and that in general for an open-interval range `lo..<hi`, you'd define `r.low == lo` and `r.high == hi`.  But from your follow-up comment, I now infer that in general you'd agree that `r.high` should be `hi - 1`, but that for an empty enum range over an enum with a single element, it would be `r.high` as a special case (because what else could it be?), but that you'd also be OK with it being some sort of error as well.

My preference is still to make the default value for this case store the single range value that's legal to store for such a type and break the symmetry there rather than at `r.high` (or, symmetrically, `r.low`).  For example, I'm imagining the module/domain/array code that we have today which reasons about low and high bounds, and am wondering how it would have to be rewritten to deal with this case correctly treat it as an empty range.  I'm also imagining that users don't typically rely heavily on default range values being empty, and that even those who do aren't likely to be too terribly surprised or bitten by this decision (as I don't expect it to come up often), aside from possible momentary surprise at the asymmetry.  I.e., I don't imagine users writing code like:

```chapel
var r: range(mySingleEnum);
doSomethingThatAssumesRangeIsEmpty(r);
```

nearly so often as:

```chapel
var r: range(...) = initialRangeValue;
doSomethingWithRange(r);
```

**Comment by bradcray** [comment]
In retrospect, I probably should've approached this design issue this way:

"A type I'm working with has a single possible value.  What should we use as the default value for a variable declared over that type—the singleton value? or something else?"

:D

**Comment by mppf** [comment]
Right, I think the question here is whether such a range should have 2 legal values ("empty" and containing the element) rather than 1. If we have for some reason decided that "empty" can never be a value for such a range then the answer is indeed obvious. However I don't think that's the case.

**Comment by bradcray** [comment]
> However I don't think that's the case.

OK, then I either need more help understanding how you're imagining we'd accomplish this (I haven't yet from the comments above), or I can keep taking guesses at it.  Here's my next guess:

* all single-value-enum ranges store an "i'm empty" bit as part of their implementation, which is set to true whenever the range is storing a default value.  This bit could also be stored for all ranges and set whenever low > high, but this seems unnecessary / redundant given that it's not required today.
* when present, range assignments would copy this "i'm empty" bit along with all the other range values
* the .size query would check this "i'm empty" bit and return 0 if it's set; otherwise it would use the current logic
* .high/.low queries on ranges that are empty only by virtue of the "i'm empty" bit can't be relied upon to return anything useful, but if we only rely on the bit for this case, then for most cases, they can behave as they do today
* the formal definition of ranges in the spec gets updated from defining ranges in terms of (low, hide, stride, alignment) to (low, hide, stride, alignment, empty)

Is that closer to what you're thinking?

**Comment by mppf** [comment]
Yes, in order to implement an idea of "empty" for such ranges, we'd need to add such an "I'm empty" bit (or else something about open/closed low/high bounds). I think you convinced me earlier that such information shouldn't be `param` but I don't think we've ruled out storing it at runtime.

**Comment by bradcray** [comment]
OK, I can try to prototype that.  My main concern is that it seems like a lot of work for a case that doesn't seem particularly well-motivated (both in the sense that ranges over single-element enums don't seem all that interesting, even though users obviously want them; and in the sense that it's difficult for me to imagine what kind of code one would have to write to get bitten by the default value for such a range being non-empty).  So I'll see how much work it is to get running, and if it seems like a crazy amount, I'll come back and stand my ground some more.

**Comment by vasslitvinov** [comment]
Reading the above, I think the key semantic questions are:

* Is a single-element-enum range allowed to be empty, and
* if it is, what are its high and low bounds.

Implementation-wise, such a range can be implemented with just a single bit, with all other `range` fields being `nothing`.

Alternatively, we could introduce a dummy enum element whose sole use would be to aid in representing an empty range. The tricky part would be to handle enums declaring their single element to be `max(int)` or `min(int)`, however we can surely outlaw such enums.

**Comment by bradcray** [comment]
I got a good start on the "store an empty bit (really bool) for range types whose idxTypes only have a single element, and it's tractable, though it's not particularly pretty.  To me, the major risk is introducing a non-continuity into what's generally been a fairly straightforward algebra such that most any operation on ranges has to potentially be aware of it (namely "the range's low/high bounds may not be valid values of type `idxType`, so watch out for that case").  Put another way, I'd feel much more confident that ranges over singleton enums were correct (or as correct as ranges generally are) in the other approach.  Here, I feel as though every corner case I test creates a new conditional I need to insert into the code, so while I've tested a bunch of them, there are probably more remaining:   https://github.com/bradcray/chapel/tree/support-one-enum-ranges-default-empty  (there's definitely more cleanup that would need to be done on this branch to make it a candidate PR; this just captures the sprinting on the effort that I tried to do last night).

**Comment by bradcray** [comment]
I've continued to hear from people that (a) they'd prefer consistency across range types and (b) they'd like a way to create an empty range over singleton enums, so am going to push on with this effort, though I haven't had time to work on it at all this week.  However, the previous attempt and the break have given me a new idea for how to handle it, without introducing any additional storage, where the crux of the idea is to represent such empty ranges as `color.red..<color.red` by creating a new initializer for Chapel's use only that accepts the internal integer values used to represent the range rather than values of `idxType`.  This will simplify the code I had previously written by not needing to always take `low` and `high` bounds as `color.red` and looking for the special case of an empty range.  It should also simplify some other common code paths to avoid conversions back and forth from internal values to user-facing values.

**Comment by leekillough** [comment]
I favor allowing a +1 value for enums, analogous to the "pointer 1 element past the end of the array" in C/C++.

That way `(color.red+1)..(color.red)` or `(enum.last+1)..(enum.first)` can represent an empty range regardless of the enum size.

That is, I prefer the "unspecified empty default range" for all sized enums.

See also [C++20 ranges](https://en.cppreference.com/w/cpp/header/ranges) and [std::ranges::end](https://en.cppreference.com/w/cpp/ranges/end)

**Comment by bradcray** [comment]
I've got a better implementation of this now in #17596 which doesn't introduce the new field and passes testing.  It could stand to be cleaned up, though, as could our range initializers in general, so I'm doing some refactoring on it to get it to a better pride level.

**Comment by bradcray** [comment]
For anyone still paying attention to this, it may be worth reading the OP on #17596 which describes what I've implemented in case there are remaining design concerns.
