### ISSUE TITLE
Should/could `List.append()` return the index of the element that was inserted?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#17466]
### Summary of Problem

As a Chapel programmer, it seems that it would be convenient for `List.append()` to return the list index where the element was inserted, particularly in the case of multiple tasks inserting items into the list simultaneously (such that querying the list's size before or after insertion wouldn't be guaranteed to be atomic w.r.t. the appended element).

### Steps to Reproduce

**Source Code:**

```chapel
use List;
var l: list(int);
var i = l.append(42);
writeln(l[i]);
```

**Compile command:**
`chpl testit.chpl`

### Configuration Information

- Output of `chpl --version`: `1.24.0`

**Comment by bradcray** [comment]
I put the "easy / straightforward" and "good first issue" labels on this because the coding part is, but note that this issue involves getting consensus that this design change is a worthwhile change to make, which requires interacting with people, not just code.  For that reason, I'm tagging @dlongnecke-cray, @mppf, @ben-albrecht, and @vasslitvinov here since I think of them as being most involved in the design of the list type (right or wrong).

**Comment by vasslitvinov** [comment]
If this piece of functionality does not add runtime cost, the proposal makes sense. Otherwise I suggest to introduce it in a separate function, or with a param formal.

**Comment by lkmeta** [comment]
I am trying to write the code to make ```List.append()``` return the inserted index of the list and I figured out that we have to return the new size of the list (because when we insert in the list the inserted index is at the end of the list) from this function by changing [L706](https://github.com/chapel-lang/chapel/blob/master/modules/standard/List.chpl#L706) with ```return _size;```. I am facing some errors in updating the modules and testing this functionality but I am thinking that by changing this one we have to update all the rest of the code which uses this function, so maybe it's better to introduce this one as a separate function. Maybe there is another better solution that I haven't find out about so far.

**Comment by mppf** [comment]
It is fine with me for it to return `int`. I don't know of any problems that would cause (performance or API-wise). IMO it would be alternatively be reasonable to return the new size (where the size is just the index + 1). Anyway I think the index might generalize better to other data structures (maps? 2D things?) but I am not really sure.

**Comment by ben-albrecht** [comment]
I agree this feature would be useful.

I think this motivation can also be applied to some other list methods such as `remove` and `extend`. `extend`  returns nothing currently. `remove` currently returns the number of elements removed, so I guess you'd have to use other means (such as a lock) to safely determine the array size after removal in a parallel context. 

> IMO it would be alternatively be reasonable to return the new size (where the size is just the index + 1). Anyway I think the index might generalize better to other data structures (maps? 2D things?) but I am not really sure.

Another advantage to returning the size is that it naturally extends to the `extend()` method where we are appending multiple elements at once. Although, we could also return the index of the last element added in `extend()` to help stay consistent across data structures such as maps and N-dimensional things, as @mppf points out.

**Comment by bradcray** [comment]
> I think this motivation can also be applied to some other list methods such as remove and extend. ...

In the case of remove(), I'm not sure I agree.  To me, the value of having `List.append()` return the index where the element is stored is that you then have a handle on that element that can get you back to it quickly.  And that index is going to be true for that element subject to the operations that I believe already have caveats about their impact on list stability (e.g., removing an element before that one in the list).  Without having list.append() return an index, you'd have to search the list to find it again, or something expensive like that. In contrast, with remove, knowing the size of the resulting list isn't something that it feels like it benefits from being intrinsically tied to the operation (to me).  That is, I could query `list.size` right after the remove, and it would be nearly as accurate or inaccurate a description of the list's size as if remove() returned the size itself.  I.e., if remove() were to atomically return the size of the list after the remove was completed, what could/would I do with it that I couldn't do by calling `.size()` immediately afterward?  In a parallel context, either is likely to become out-of-date as soon as I asked the question.  (if remove didn't already return something, I wouldn't be opposed to having it return the size, because why not, so I guess I'm really arguing that I don't think it's worth complicating the interface over).

**Comment by bradcray** [comment]
> I am facing some errors in updating the modules and testing this functionality but I am thinking that by changing this one we have to update all the rest of the code which uses this function, so maybe it's better to introduce this one as a separate function. 

@lkmeta : Can you give an example of the sort of ripple effect that this change has had on other parts of the code?  (my intuition would've been that since values returned by functions can be ignored, it wouldn't have much of an impact; but I haven't tried it, and could obviously be overlooking something).

**Comment by dlongnecke-cray** [comment]
Hi, I'm OK with having `list.append()` return an `int`.

**Comment by bradcray** [comment]
> I think this motivation can also be applied to some other list methods such as remove and extend. 

(I'd also be inclined not to slow down this specific user request over the other routines if there's sufficient buy-in to proceed with it.  Changes to other routines can be forked off to its own issue if someone wants to champion it).

**Comment by ben-albrecht** [comment]
> In the case of remove(), I'm not sure I agree. To me, the value of having List.append() return the index where the element is stored is that you then have a handle on that element that can get you back to it quickly. And that index is going to be true for that element subject to the operations that I believe already have caveats about their impact on list stability (e.g., removing an element before that one in the list). Without having list.append() return an index, you'd have to search the list to find it again, or something expensive like that. In contrast, with remove, knowing the size of the resulting list isn't something that it feels like it benefits from being intrinsically tied to the operation (to me). That is, I could query list.size right after the remove, and it would be nearly as accurate or inaccurate a description of the list's size as if remove() returned the size itself. I.e., if remove() were to atomically return the size of the list after the remove was completed, what could/would I do with it that I couldn't do by calling .size() immediately afterward? In a parallel context, either is likely to become out-of-date as soon as I asked the question. (if remove didn't already return something, I wouldn't be opposed to having it return the size, because why not, so I guess I'm really arguing that I don't think it's worth complicating the interface over).

That's a good point. The motivation seems less relevant when parallel removes are involved. I think `extend` could still benefit from returning a size or index for the same reasons `append` does, but that can be tackled separately.

> (I'd also be inclined not to slow down this specific user request over the other routines if there's sufficient buy-in to proceed with it. Changes to other routines can be forked off to its own issue if someone wants to champion it).

Totally agree. I didn't intend to resolve those broader design decisions here, just wanted to make sure they were recognized and considered before making a decision here.

**Comment by mppf** [comment]
We don't have to decide on `extend` here but IMO if we do this change we'd make `extend` return the index of the first element added (or a "Who Cares!" value if extend is adding 0 elements).

**Comment by bradcray** [comment]
> we'd make extend return the index of the first element added

I had the same thought.

**Comment by lkmeta** [comment]
> > I am facing some errors in updating the modules and testing this functionality but I am thinking that by changing this one we have to update all the rest of the code which uses this function, so maybe it's better to introduce this one as a separate function.
> 
> @lkmeta : Can you give an example of the sort of ripple effect that this change has had on other parts of the code? (my intuition would've been that since values returned by functions can be ignored, it wouldn't have much of an impact; but I haven't tried it, and could obviously be overlooking something).

@bradcray I messed up because I didn't know that we can ignore the returned values.

**Comment by strikeraryu** [comment]
Is this issue has been resolved? If not then ill work on it.

**Comment by bradcray** [comment]
@strikeraryu : Good question.  From context, it seems that @lkmeta has been working on it, so let's check with them?

**Comment by strikeraryu** [comment]
@lkmeta any updates on this issue?

**Comment by lkmeta** [comment]
I tried to find a solution but still I haven't figured out how to solve this issue. @strikeraryu Ofc you can also work on it and if I have any important updates I will share them.

**Comment by strikeraryu** [comment]
Are we concerned with ```_appendByRef()``` related to this change?

**Comment by bradcray** [comment]
`_appendByRef()` isn't user-facing, so I think it can change in any way we want (or not) to solve this issue.

**Comment by strikeraryu** [comment]
I think these changes will do the work, I stored the value before we release lock, so the value doesn't get affected.
``` chapel
proc ref append(pragma "no auto destroy" in x: this.eltType) : int
    lifetime this < x {
      _enter();

      //
      // TODO: Can't use on statement here without getting a memory leak on
      // gasnet/multilocale configurations.
      //
      _appendByRef(x);
      var insertedElementIndex = _size - 1;
      _leave();
      return insertedElementIndex;
    }
```

for serial check I performed normal test and for parallel, I performed this
``` chapel
coforall i in 0..10 with (ref l){
    var ind = l.append(i);
    writeln(ind, " ", i);
}
writeln(l);
```
please suggest if there is some issue with this.

**Comment by bradcray** [comment]
@strikeraryu : At a glance, this looks like the sort of thing I'd expect, but I'm not very familiar with our List implementation.  Let me tag @dlongnecke-cray, who's far more familiar with it to see if he can take a look.

**Comment by dlongnecke-cray** [comment]
That looks fine to me.

As always, when I read these sorts of codes that return `size` I get that fear of "what if another operation invalidates that index?", but I suppose that's necessarily the user's problem.

**Comment by bradcray** [comment]
> but I suppose that's necessarily the user's problem.

I share the concern, but my thinking here is that the current general caveat about "no guarantees that your element will stay in the same place in the face of removes, etc." would apply here.  But in a PR adding this feature, it'd be worth checking to see that that wording makes sense for this case, or adjust it if not.

**Comment by strikeraryu** [comment]
What are the other files I need to update with this change?

**Comment by dlongnecke-cray** [comment]
Go ahead and open a pull request and ping me and I can help you.
