### ISSUE TITLE
The documentation for `Error.message()` doesn't indicate its return type

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#17469]
### Summary of Problem

As a Chapel programmer interested in creating my own Error classes, I'm observing that the required signature for `Error.message()` is not indicated very clearly in its documentation.  E.g., does it return a `string` or ...?

### Configuration Information

- Output of `chpl --version`: 1.24.0

**Comment by bradcray** [comment]
@mppf: Before putting the "easy / straightforward" label on here, I wanted to check and see whether this was intentional for reasons I'm not picking up on?

**Comment by mppf** [comment]
I don't think it's intentional - it should be documented to return `string`.

**Comment by shubhamkmr04** [comment]
hey @bradcray i would like to work on the issue

**Comment by shubhamkmr04** [comment]
@bradcray I would like to work on this issue.

**Comment by shubhamkmr04** [comment]
![Screenshot from 2021-03-27 11-54-33](https://user-images.githubusercontent.com/50761978/112712138-7c631f00-8ef3-11eb-91a3-b25a7d043c8a.png)
![Screenshot from 2021-03-27 11-53-23](https://user-images.githubusercontent.com/50761978/112712149-900e8580-8ef3-11eb-8237-b0d0b3710c47.png)

I read the module/internal/ChapelError.chpl , proc message() does return a string so I made these changes to the comments explaining this.

**Comment by bradcray** [comment]
Hi @shubhamkmr04 : I think this is a good start, but I'd also consider:

* adding an explicit `: string` return type indicator in the code itself, which will make the intent manifest to anyone only looking at the code (either in the module file or the chpldoc output)
* optionally (or alternatively) using `chpldoc`'s `:rtype:` tag to document the return type in the documentation itself.

If you run `make docs` from `$CHPL_HOME` you should be able to browse the output of these changes by pointing a web browser to `doc/html/builtins/ChapelError.html` which is a good way to preview what the real documentation will end up looking like:  https://chapel-lang.org/docs/builtins/ChapelError.html

**Comment by shubhamkmr04** [comment]
Okay, thanks @bradcray , I mentioned `:string` in the `module/internal/ChapelError.chpl` itself. So finally the file is looking like this.
![Screenshot from 2021-03-30 10-59-56](https://user-images.githubusercontent.com/50761978/112938540-6d74aa80-9147-11eb-897e-bec3a28cf117.png)
Talking about mentioning `chpldoc`'s `:rtype:` in the documentation, does these changes looks right in `ChapelError.rst` ?
![Screenshot from 2021-03-30 11-19-03](https://user-images.githubusercontent.com/50761978/112939969-0ad0de00-914a-11eb-8dc8-a2beea2b9d5b.png)
But there's one problem, whenever I change something in `ChapelError.rst` and run `make docs` , the changes in the file 'ChapelError.rst' just reverts back to what it was before so I can't see my changes in `ChapelError.html`

**Comment by bradcray** [comment]
Hi @shubhamkmr04 — The ChapelError.rst is created by the `chpldoc` tool from `ChapelError.chpl`, so you should only be editing ChapelError.chpl (and include your `:rtype:` tag there).  Do `cd $CHPL_HOME/modules && git grep rtype` to see example use cases in other modules.

**Comment by shubhamkmr04** [comment]
> Hi @shubhamkmr04 — The ChapelError.rst is created by the `chpldoc` tool from `ChapelError.chpl`, so you should only be editing ChapelError.chpl (and include your `:rtype:` tag there). Do `cd $CHPL_HOME/modules && git grep rtype` to see example use cases in other modules.

@bradcray got it. I linked a PR #17497 for this issue, please review.
