### ISSUE TITLE
Update Chapel Quick Reference to include try...catch

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#17468]
It was pointed out that the [Quick Reference sheet](https://chapel-lang.org/docs/language/reference.html?highlight=quick%20reference) hasn't been updated to include `try...catch` (which will be an interesting challenge because last I looked, it was short on free space).

[This makes me wonder what else has been introduced in recent releases, but is not represented on the Quick Reference].

**Comment by lkmeta** [comment]
Hey, @bradcray I would like to work on the issue if nobody is working on it. I already made a pull request for the ```try...catch``` statement, can you review it? Thanks in advance.

**Comment by bradcray** [comment]
@lkmeta : Thanks for jumping on this!

@vasslitvinov, I believe you were the last person to work on the Quick Reference sheet.  Would you have time to review this PR?

**Comment by vasslitvinov** [comment]
One thing not in Quick Reference right now is open ranges.

**Comment by lkmeta** [comment]
> One thing not in Quick Reference right now is open ranges.

@vasslitvinov On the second page of the document, it is included the following subsection. Should we have to introduce something else for 'open ranges'?  I am also thinking about range comparison ```proc==(r1: range(?), r2: range(?)): bool```, should this be introduced?  

![image](https://user-images.githubusercontent.com/74689374/113951413-cca38080-9813-11eb-94bf-7a24e48c7f8d.png)

**Comment by vasslitvinov** [comment]
@lkmeta you are right, they are there, I overlooked.

I suggest we add `..<` to the Precedence table in the middle of Page 1, next to `..` .

**Comment by lkmeta** [comment]
> I suggest we add `..<` to the Precedence table in the middle of Page 1, next to `..`.

I can do it if we decide that it should be introduced. 
@bradcray any thoughts about it?

**Comment by bradcray** [comment]
Makes sense to me, thanks @lkmeta!

**Comment by lkmeta** [comment]
> I suggest we add `..<` to the Precedence table in the middle of Page 1, next to `..`.

@vasslitvinov I included the open range construction in the table like this. Shall I open a new PR?  

![image](https://user-images.githubusercontent.com/74689374/114197250-70934600-9952-11eb-9f31-f8b92cbec653.png)

**Comment by vasslitvinov** [comment]
@lkmeta sure, unless there is another way to get it on master.

**Comment by lkmeta** [comment]
> @lkmeta sure, unless there is another way to get it on master.

@vasslitvinov Okay done, thank you! #17552
