### ISSUE TITLE
.low/.high on unbounded ranges shouldn't return values

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#17526]
### Summary of Problem

In https://github.com/chapel-lang/chapel/issues/17464#issuecomment-813501792, @mppf noted that `(0..).high` returns a value rather than generating a compiler error, which seems preferable—and possible, given that the unbounded-ness of a range is part of its static type information.  This issue proposes that we make it a compiler error if possible.

### Steps to Reproduce

**Source Code:**

```chapel
writeln((10..).high);
writeln(..10).low);
```

**Compile command:**
`chpl testit.chpl`

**Execution command:**
`./testit`

### Configuration Information

- Output of `chpl --version`: 1.24.0

**Comment by bradcray** [comment]
I've implemented this in #17532

**Comment by vasslitvinov** [comment]
#17532 sounds good.

I suspect there are also cases where the presence of a high/low bound is not known at compile time, for example for a bounded range with undefined alignment and a nontrivial stride. Seems like they should not affect #17532, where the behavior remains "undefined" in those cases.

**Comment by bradcray** [comment]
> for example for a bounded range with undefined alignment and a nontrivial stride.

I'm not able to think of a case where such a range would not have a low or high bound.  I thought the only cases that had undefined alignment were unbounded ranges that stride from their unbounded side since the application of a stride starts counting from one end or the other?  But even in those cases, I'd think it's the first/last whose presence would be unknown statically, not the low/high...  Are you seeing a case I'm missing?

**Comment by vasslitvinov** [comment]
@bradcray you are right, it may be something other than low/high bounds.
