### ISSUE TITLE
Solved Error page

### ISSUE THREAD

**Issue by strikeraryu** [chapel-lang/chapel#17524]
## Summary of Problem
As currently there are not a lot of people using chapel so major online discussion forums didn't have that much content. So people might find it hard to look for the issues. Keeping track of issues on gitter or finding a specific issue is not easy if people are trying to look for a solution. 

## Solution
We can either post all the errors and solutions on a chapel page or we can start posting errors on StackOverflow and then link it in gitter ( + we can post a question and then answer it by ourselves if we already have a solution), So the solution is widely available for the user to find.

**Comment by bradcray** [comment]
In my opinion, posting to StackOverflow is the best way to capture questions and answers in Chapel, when it's an issue that other users are likely to have and search for.  The reason being that for most developers, it's the definitive source of information when troubleshooting issues.  Note that this can be done after the fact as well—i.e., SO encourages users to post questions and answer them as a means of capturing knowledge... there's no need to only post questions to which you don't know the answer.  So however an answer is arrived at, capturing it at SO can be helpful to others (again, assuming it's a problem that others will potentially run into).

**Comment by strikeraryu** [comment]
Yeah, I also believe this will be very helpful, But how can we promote this as we can't say to everyone to post their errors on StackOverflow, and even if they post somewhere else we cant just point that out... we will just try to solve there issue. So If somehow this can be pointed to everyone at once using some means, then this can change how the community handles errors right now.

**Comment by bradcray** [comment]
We strive to make it clear where people can ask questions and get answers here:  https://chapel-lang.org/community.html

It's difficult for me to imagine creating a (useful) compendium of all known problems and solutions without a human being involved, and that's a long-term commitment that I'd be reluctant to ask of anyone.

**Comment by strikeraryu** [comment]
Yeah I understand your point, so should I close this issue? or keep it open If anyone has a good suggestion that might be helpful, then they can post it here.

**Comment by bradcray** [comment]
It'd be fine with me to leave it open for awhile and see what suggestions people have, but if we didn't get any over some period of time, I'd be inclined to close it.

**Comment by strikeraryu** [comment]
@bradcray This issue can be closed.
