### ISSUE TITLE
Should `read()` be available for all programs? otherwise, a doc bug

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#17525]
This issue suggests that `read`-ing values from stdin is a basic functionality like math functions and should not require `use`-ing any modules.

For example:
```chpl
var x: int;
var y: real;

/* reading into variable expressions, returning
   true if the values were read, false on EOF */
var ok:bool = read(x, y);

/* reading via a single type argument */
x = read(int);
y = read(real);

/* reading via multiple type arguments */
(x, y) = read(int, real);
```

If we stick with the status quo, we need to fix online docs.

The [online docs for ChapelIO](https://chapel-lang.org/docs/master/modules/standard/ChapelIO.html) has the following claims prior to the above code:

* "All Chapel programs automatically use this module by default. An explicit use statement is not necessary." and
* "This section describes automatically included basic types and routines"

Yet, currently that code requires `use IO`, so users are surprised by a compiler error when trying it out.

**Comment by mppf** [comment]
I think it was intentional for `read` not to be included by default (see #14145, #13448, #13373). As a result I think this is a doc bug. (However I am open to revisiting if there is a better motivation than that the docs were not updated properly).

**Comment by lydia-duncan** [comment]
I think I just overlooked that section when updating

**Comment by leekillough** [comment]
I overlooked `ChapelIO` when editing https://github.com/chapel-lang/chapel/pull/17448. Maybe I should make a second pass and examine `ChapelIO`.
