### ISSUE TITLE
Error Message: Should operator method calls look the same as standalone operator calls?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#17539]
Today if a call fails and reports the call stack involving an operator method, we'll report it as, e.g.:

```
foo.chpl:n: called as MyRecord.=(lhs: MyRecord(0), rhs: MyRecord(0))
```

Vass points out that we can't explicitly write a call like that today.  Should we modify the message when the function called is an operator method so that it doesn't include the type prefix?  E.g.
```
foo.chpl:n: called as =(lhs: MyRecord(0), rhs: MyRecord(0))
```

**Comment by bradcray** [comment]
That seems attractive to me.  Or even `called as '(lhs: MyRecord(0)) = (rhs: MyRecord(0))'` to reflect the infix nature?
