### ISSUE TITLE
should RandomStream.getNth() and skipToNth() accept any integral type?

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#17568]
Right now the classes `PCGRandomStream` and `NPBRandomStream` declare these methods with generic `integral` formals:
```chpl
proc skipToNth(n: integral): void throws {...}
proc getNth(n: integral): eltType throws {...}
```

However, the current implementation adds the `n` formal onto `PCGRandomStreamPrivate_count` or NPBRandomStreamPrivate_count`, which are declared with the type `int`. So:

* It does not compile if my actual argument is a `uint`.
* It does not offer me any savings benefits if my actual argument is a smaller int or uint.

For example:
```chpl
use Random;

var stream = new PCGRandomStream(eltType=real);  // or NPBRandomStream(eltType=whatever)
stream.getNth(8:uint);       // error in Random.chpl
stream.skipToNth(8:uint);    // error in Random.chpl
```

If it is important for us to support the `uint` use case, we should parameterize these classes by the count type.

Otherwise I suggest to streamline the interface by switching the `n` formals to the type `int`.

**Comment by bradcray** [comment]
I think it would definitely be convenient to be able to pass a `uint` to these routines, to avoid forcing the user to explicitly downcast, but rather than making the classes generic w.r.t. count type, I'd either just change them to use uint internally for such purposes (since negative numbers aren't valid input I think?) or use a .safeCast() on the `uint` input argument and document that only uint values between 0 and max(int) are supported currently.

**Comment by vasslitvinov** [comment]
@bradcray what do you suggest for the type of the formal? Keep it `integral`?

How about this twist on your proposal: we represent the count internally as a `uint` and indicate that these routines do not support negative counts. This restriction would be enforced at runtime unless `--fast` or similar.

**Comment by bradcray** [comment]
I think that's what I meant by my first option:

> I'd either just change them to use uint internally for such purposes...

**Comment by jeremiah-corrado** [comment]
As a part of the Random module stabilization effort, we decided to deprecate `getNth`, and rename `skipToNth` to `skipTo` with an `int` formal. This was discussed [here](https://github.com/Cray/chapel-private/issues/5604#issuecomment-1917829324) and implemented in https://github.com/chapel-lang/chapel/pull/24379.
