### ISSUE TITLE
isSubtype() returns false when parent class is generic

### ISSUE THREAD

**Issue by AsianIntel** [chapel-lang/chapel#17572]
### Summary of Problem

While working on a library, I seem to have encountered an issue where the `isSubtype` function returns `false` when the parent class is generic. The expectation is it should be returning `true`.

### Steps to Reproduce

**Source Code:**

```chapel
class GenericParentClass {
  type t;

  proc init(type t) {
    this.t = t;
  }
}
class ChildClass: GenericParentClass {}

class ParentClass {}
class ChildClass2: ParentClass {}

writeln(isSubtype(ChildClass, GenericParentClass)); // -> returns false
writeln(isSubtype(ChildClass2, ParentClass)); // -> returns true (as expected)
```

**Compile command:**
`chpl test.chpl`

**Execution command:**
`./test`

### Configuration Information

- Output of `chpl --version`: `chpl version 1.24.0`
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_REGEXP: re2
CHPL_LLVM: none
CHPL_AUX_FILESYS: none
```

**Comment by lydia-duncan** [comment]
Interestingly, it seems to behave correctly when the child class is concrete.  E.g. if you change `writeln(isSubtype(ChildClass, GenericParentClass));` to `writeln(isSubtype(ChildClass(int), GenericParentClass));`, it will print true.

**Comment by AsianIntel** [comment]
I guess I could try to use this as a temporary workaround

**Comment by AsianIntel** [comment]
I thought I could use this as a workaround, but I don't think it's possible when a type is passed as a function argument for the type to be used in `isSubype` while making it concrete

**Comment by lydia-duncan** [comment]
Yeah, definitely.  I'm looking at what it would take to fix this

**Comment by lydia-duncan** [comment]
#17581 should fix the issue when it gets merged

**Comment by AsianIntel** [comment]
Alright, thank you so much
