### ISSUE TITLE
What does CHPL_HOST_COMPILER=clang-included do?

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#17584]
Documentation in 1.24 for [CHPL_*_COMPILER](https://chapel-lang.org/docs/1.24/usingchapel/chplenv.html#chpl-compiler) could be more clear about how `CHPL_HOST_COMPILER=clang-included` behaves.

This value doesn't make sense to me because `clang-included` doesn't exist until is built by `clang-included`.

Actually trying it out seems to have it behave like `clang`. I think the implementation needs to catch this and throw a build error. How does it actually behave and why?

**Comment by bradcray** [comment]
@daviditen — Do you happen to know the answer to this?

(I have to admit that this discussion, and [this one](https://chapel.discourse.group/t/build-process-for-variants-of-llvm-dependency/4554) make me wonder whether the user-level COMPILER setting should simply be `clang`, where it defaults to the system clang if `CHPL_LLVM=system` and the included version if `CHPL_LLVM=bundled`).

**Comment by daviditen** [comment]
Not off the top of my head, but I tried it out.
With `CHPL_HOST_COMPILER=clang-included` and `CHPL_LLVM=none` `make` gets malformed compile lines and errors.
With `CHPL_HOST_COMPILER=clang-included` and `CHPL_LLVM=system` `make` uses the system LLVM/clang++ to build the compiler.
With `CHPL_HOST_COMPILER=clang-included` and `CHPL_LLVM=bundled` `make` attempts use the bundled clang++, but quickly errors out.

I'm not sure what we should expect it to do with these settings.

**Comment by BryantLam** [comment]
I don't think `CHPL_HOST_COMPILER=clang-included` is legal and would argue for it to be disallowed.

**Comment by bradcray** [comment]
@mppf: I think that you intended for this to be closed with #17800, but that either GitHub doesn't permit chaining of auto-resolves, or the syntax wasn't quite right, is that correct?

**Comment by mppf** [comment]
Yes, I meant to close this with #17800, thanks for pointing it out.
