### ISSUE TITLE
Adding support for context managers

### ISSUE THREAD

**Issue by dlongnecke-cray** [chapel-lang/chapel#17592]
This issue proposes to add _context managers_ to Chapel, and suggests a potential implementation that can be used as a starting point for discussion.

Tests and motivating examples for my current prototype can be seen here: https://github.com/dlongnecke-cray/chapel/tree/add-context-manager/test/statements/manage

## Child issues

- #17809
- #17965

## Introducing the context manager

A _context manager_ is a syntactic construct that makes a series of actions occur at the beginning and end of a block. It can be used to:

- Control access to a resource (e.g. a critical section)
- Create and clean up a resource (e.g. a file)
- Introduce scope-bound state changes (e.g. context sensitive parsing)

The context manager from Python looks like this:

```python

# If our context manager does not return a resource, or we do not care about what it returns,
# we can drop the resource instead of binding it to a name.
with createAContext():
  do_something()

# Many times, the manager will return a resource. In that case, we can bind the resource to
# a name so that we can use it within the scope of the managed block.
with createAContext() as handleToResource:
  handleToResource.do_something()
```

A first-pass translation of this construct to Chapel might look like:

```chapel
manage createAContext() {
  do_something();
}

manage createAContext() as handleToResource {
  handleToResource.do_something();
}
```

The keyword `manage` was chosen to avoid confusing context managers with task and forall intents. If we want to avoid adding new keywords to the language, we could use:

```chapel
with createAContext() {
  do_something();
}

with createAContext() as handleToResource {
  handleToResource.do_something();
}
```

As an alternative, but I worry about potential confusion (though to the parser, the syntax is quite clear, as managers will likely only appear at the statement level).

## Requirements for a type to be used as a context manager

To be used as a context manager, a type must define two methods. The first method is called upon entry to the managed block. It may or may not return a value. The second method is called upon exiting the managed block. It does not return a value.

```python
class MyContextManager(object):
  # In Python, the magic method __enter__ is called on entry to a block.
  def __enter__(self):
    return 1
  # The magic method __exit__ is called upon exiting a block.
  def __exit__(self):
    pass
```

A first-pass translation of these methods to Chapel might look like:

```chapel
record myContextManager {
  proc enterThis() { return 1; }

  proc leaveThis() {}
```

The names `enterThis` and `leaveThis` were chosen due to symmetry and because other magic methods tend to append "this" such as `readThis`, `writeThis`, and `readWriteThis`.

Alternatively, the names from Python could be used instead:

```chapel
record myContextManager {
  proc enterThis() { return 1; }

  proc exitThis() {}
```

## What does the desugared form of the context manager look like?

Regardless of the chosen syntax, the desugared form of the context manager will probably end up looking like:

```chapel
manage new myContextManager() as x {
  x.doSomething();
}
```
Desugars to...

```chapel
{
  ref manager = new myContextManager();
  var x = manager.enterThis();

  {
    x.doSomething();
  }

  tmp.leaveThis();
}
```

## What is the variable declaration type of the managed resource?

Given the current proposal:

```chapel
manage someContext() as resource {
  resource.doSomething();
}
```

The variable declaration type of `resource` is not specified. It could be `var` or `ref` and potentially `const`.

As long as there are not multiple overloads of `enterThis()` that vary only by return intent, the variable declaration type of `resource` could probably be determined by the return intent of `enterThis()`.

```chapel

record storeNumber {
  var x = 0;
  proc enterThis() ref { return x; }
  proc leaveThis() {}
}

var myManager = new storeNumber();

// Here `number` will be `ref`
manage myManager as number {
  number = 5;
}
writeln(myManager.x); // OK, prints '5'
```

## Dealing with overloaded return intents for `enterThis()`

In Chapel, return intents are considered when selecting which overload of a function to call.

Consider the following:

```chapel

record storeNumber {
  var x = 0;
  proc enterThis() { return x; }
  proc enterThis() ref { return x; }
  proc leaveThis() {}
}

var myManager = new storeNumber();
manage myManager as number {
  number = 5;
}
writeln(myManager.x); // What does this print?
```

- Which overload of `enterThis()` is called?

One option is to require the user to specify the variable declaration type of the managed resource.

If we wanted the `ref` overload of `enterThis()` to be preferred, we could declare `number` as `ref`:

```chapel
var myManager = new storeNumber();
manage myManager as ref number {
  number = 5;
}
writeln(myManager.x); // Prints '5'
```

And if we wanted the `var` overload of `enterThis()` to be preferred, we could declare `number` as `var`:

```chapel
var myManager = new storeNumber();
manage myManager as var number {
  number = 5;
}
writeln(myManager.x); // Prints '0'
```

We could require the variable declaration type to be specifically stated, or we could assume some sort of reasonable default (below we assume `var`):

```chapel
var myManager = new storeNumber();
manage myManager as number {
  number = 5;
}
writeln(myManager.x); // Prints '0'
```

Another option is to disallow overloading the return intent of `enterThis()`. This way, the variable declaration type of `number` is obvious, because there is nothing to disambiguate.

```chapel

record storeNumber {
  var x = 0;
  proc enterThis() { return x; }
  proc enterThis() ref { return x; }
  proc leaveThis() {}
}

var myManager = new storeNumber();

// Error: call to 'proc storeNumber.enterThis()' is ambiguous due to multiple return intents
manage myManager as number {
  number = 5;
}
writeln(myManager.x);
```
```chapel

record storeNumber {
  var x = 0;
  proc enterThis() ref { return x; }
  proc leaveThis() {}
}

var myManager = new storeNumber();

// Here `number` will be `ref`
manage myManager as number {
  number = 5;
}
writeln(myManager.x); // OK, prints '5'
```

## Alternative syntax that could support overloaded return intents for `enterThis()`

Here is an alternative syntax that would also allow disambiguating calls to `enterThis()`:

```chapel
record storeNumber {
  var x = 0;
  proc enterThis() { return x; }
  proc enterThis() ref { return x; }
  proc leaveThis() {}
}

var myManager = new storeNumber();

manage ref number = myManager {
  number = 5;
}
writeln(myManager.x);
```

This could work, however I worry that `ref number = myManager` is mistakenly seen as taking a reference to `myManager`, when in fact, its meaning is `ref number = (myManager).enterThis()`.

**Comment by mppf** [comment]
> As an alternative, but I worry about potential confusion (though to the parser, the syntax is quite clear, as managers will likely only appear at the statement level).

I think this is an interesting question.

I would sortof expect syntax like `with var something = createAContext()` / with const something = createAContext()` but the `as` business is also ok.

But anyway regarding `with` I think the problem isn't specifically at the context manager block but rather that it might lead to misinterpretation of `forall` intents, e.g.

``` chapel
forall i in 1..n with (var x = createAContext()) {
}
```

probably would not do what somebody was expecting if they thought with/var was for context managers, since the forall intent won't call enter/leave. (Would it be better if it did call enter/leave? Would a `forall` using a context manager just say `forall i in 1..n with (createAContext())` to create a context manager per task? Or something?

**Comment by vasslitvinov** [comment]
Syntax-wise, I prefer the chapel-erific alternative for the variable declaration, i.e.
```chpl
manage [var|const|ref|const ref] varname = expression { ... }
```

I agree that `varname` could be mistaken for a reference or copy of the manger itself. To me, the `as` in python syntax has the same issue so would not be an improvement. Instead how about using something like:
```chpl
manage x in myManager { ... }
```

Separately, it would inconvenience me if I had to type `new` when creating the manager instance, so I'd rather make it implicit:
```chpl
manage myContextManager() { ... }   // implicitly 'new myContextManager()'
```

however this is similar to what we do for the `dmap` clause and the implicit `new` in that context makes it a bit weird to my eye. So maybe we shouldn't use that approach here.

**Comment by dlongnecke-cray** [comment]
I really love the syntax `manage [var|const|ref|const ref] <ident> in <expression> { ... }`. I actually think it reads much more naturally than the Python syntax. 

W.r.t. `new` I think it might be important to just take an expression there instead of doing something implicitly. Just for the sake of consistency.

**Comment by mppf** [comment]
Regarding `new`, I am expecting that almost all of the time, there is some function that returns the context manager that is called. Along those lines, I think it would be interested @dlongnecke-cray to think about some common Python idioms using context managers to check that similar things can work for us to. Usually when doing language design like this I think it's helpful to have a suite of 3-12 small motivating examples. In particular I don't think we've discussed the context-manager-managing-open-file idom that is common in Python.

**Comment by dlongnecke-cray** [comment]
Sure, I'll work to try and build a few more examples today.

**Comment by dlongnecke-cray** [comment]
One thing that @bradcray indicated he was interested in seeing if it was possible to use multiple context managers, e.g. if you wanted to start a timer and turn on comm counting at the same time.

Python3 does support this, and the syntax looks like:

```python
# Here expr1 offers a resource in A, expr2 offers no resource, and expr3 offers C
with expr1 as A, expr2, expr3 as C:
  A.do_something()
  C.do_something()
```

In the current prototype that syntax would be translated to:

```chapel
manage expr1 as var A, expr2, expr3 as var C {
  A.do_something();
  C.do_something().
}
```

Or in the syntax suggested by Vass:

```chapel
manage var A in expr1, expr2, var B in expr3 {
  A.do_something();
  C.do_something();
}
```

**Comment by dlongnecke-cray** [comment]
When we have a compound management statement, what would we expect the order of evaluation for management expressions to be?

Given the following program:

```chapel
use TrackingRecord;

proc r.enterThis() {
  writeln('entering');
}

proc r.leaveThis() {
  writeln('leaving');
}


proc test() {
  manage new r(), new r(), new r() {
    writeln('in block');
  }
}
test();
```

Would we expect the output:

```
default-init: (ptr = {x = 0})
entering
default-init: (ptr = {x = 0})
entering
default-init: (ptr = {x = 0})
entering
in block
leaving
leaving
leaving
deinit: (ptr = {x = 0})
deinit: (ptr = {x = 0})
deinit: (ptr = {x = 0})
```

Or would we expect:

```
default-init: (ptr = {x = 0})
default-init: (ptr = {x = 0})
default-init: (ptr = {x = 0})
entering
entering
entering
in block
leaving
leaving
leaving
deinit: (ptr = {x = 0})
deinit: (ptr = {x = 0})
deinit: (ptr = {x = 0})
```

That is, would we expect all the expressions to be evaluated first and then have each call `enterThis()`, or are we happy with evaluating and calling `enterThis()` one at a time?

**Comment by dlongnecke-cray** [comment]
Tests and and motivating examples for my current prototype can be seen here: https://github.com/dlongnecke-cray/chapel/tree/add-context-manager/test/statements/manage

**Comment by bradcray** [comment]
> When we have a compound management statement, what would we expect the order of evaluation for management expressions to be?

Hi David — I don't have a strong opinion here.  My gut reaction was the former, but I'm not convinced that's right.  Specifically, if I were using one of these to say "I want to time, mem-track, and comm-track this block of code", I probably don't want to measure the time, mem, or comms from the other trackers, just the block itself.  So that suggests the latter seems preferable to me.  This also has the advantage of being similar to evaluating the actuals of a function before calling the function (where I could imagine the compiler implementing `manage` using a function under the hood.

I also take some comfort in knowing that, whichever we pick, the opposite is available (by nesting `manage` blocks or by hoisting the `new r()` expressions out of the manage block.  So I think focusing on whichever is most convenient for the user is probably the right thing to do, which again suggests the latter to me.

**Comment by dlongnecke-cray** [comment]
Closing this as we've added a prototype version of the context manager to the language in the form of the `manage` statement.

See the technote: https://chapel-lang.org/docs/technotes/manage.html

Some followup issues:

- https://github.com/chapel-lang/chapel/issues/18190
- https://github.com/chapel-lang/chapel/issues/18242
- https://github.com/chapel-lang/chapel/issues/17965
