### ISSUE TITLE
bug capturing outer variables passed to cobegin

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#17623]
This issue came up in the development of PR #17293.

The compiler includes a pass that adds outer variables referenced in an inner function as reference arguments. However this seems to not work with a `cobegin`. See the below example. I am expecting it to compile and to print out `1` twice. Instead, it results in C compilation errors with `fooVariable_chpl` being undefined in the cobegin function.

``` chapel
proc genericFunction(callable) {
  cobegin {
    callable.function();
    callable.function();
  }
}

proc foo() {
  var fooVariable = 1;
  record R {
  }
  proc R.function() {
    writeln(fooVariable);
  }
  var r = new R();
  genericFunction(r);
}

foo();
```

**Comment by bradcray** [comment]
Do you know: Is this issue specific to `cobegin`?  (vs. `coforall` or `forall`, say?)

**Comment by mppf** [comment]
Haven't tried coforall but the bug came about when we changed a forall to a cobegin (meaning it almost certainly works with forall).

**Comment by e-kayrakli** [comment]
That's fine, thanks for looking! I don't know much about that part of the compilation to say anything half intelligent on the matter.

Do you think we should revert https://github.com/chapel-lang/chapel/commit/453aefc46348b281f092cc20e81dcc69c5a47fb0 ?

**Comment by mppf** [comment]
It would be fine to revert it if it matters to somebody but this seems like a bug we should fix.

**Comment by e-kayrakli** [comment]
Let me put it another way: if this is too hard that we can't get to it feasibly in this release, I think we should revert that commit.

**Comment by mppf** [comment]
Here is an even simpler reproducer

``` chapel
proc genericFunction(param p) {
  proc innerf() {
    fooFunction();
  }
  innerf();
}

proc foo() {
  var fooVariable = 1;
  proc fooFunction() {
    writeln(fooVariable);
  }
  genericFunction(1);
}

foo();
```
