### ISSUE TITLE
`import Regex` breaks ability to write `if myre.match(...)`

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#17633]
### Summary of Problem

As a user who prefers `import` to `use`, compiling and running the following program:

```chapel
import Regex;

var myre=Regex.compile("hello[0-9]");
if myre.match("hello0") then writeln("Yes!");
```

results in an error:

```
testit.chpl:4: error: type 'regexMatch' used in if or while condition
```

This is because, in the current compiler and language definition, support for using an arbitrary type in a conditional is implemented using a (not user-facing) standalone `_cond_test()` routine that is used in conditionals to convert types into booleans.  The nature of this failure is that `_cond_test(:regexMatch)` is implemented in `Regex` and is not brought in by the `import` statement, breaking the conditional statement.

Resolving this issue may involve further design and discussion about how (and whether) users can permit arbitrary types to be used in conditional contexts; potentially converting `_cond_test()` to a user-facing feature.  It feels related to recent discussions on implicit conversions and operator methods.

**Comment by bradcray** [comment]
@mppf / @lydia-duncan : I'd be curious what your thoughts are here given the relationship to type conversions and operators.

**Comment by mppf** [comment]
Yeah, if we continue to support`_cond_test` in any form I would expect it to become an operator.

**Comment by bradcray** [comment]
Maybe a different version of the question focused more on the design of the Regex module:  Is it appropriate that a user be able to write the conditional above, or should we remove the `_cond_test` and require an explicit conversion to `bool`?  Tagging @leekillough on this due to his recent work on Regex.

**Comment by lydia-duncan** [comment]
I think having regexMatch be treated like a bool in this context would be reasonable.  At least, it seems like it could functionally mean that.  One thing that occurred to me: would it make sense for `_cond_test` to be provided via an interface?

**Comment by lydia-duncan** [comment]
The ability to be used in a conditional seems like it could be considered a property of a type and interfaces are how we should check if such properties are defined going forward.

**Comment by mppf** [comment]
Right, but the same could be said of something like "able to be added with `+`". Meaning, we need the `operator` idea even if we have interfaces. (Put another way, an interface can specify it is required, but how do you implement the equivalent of `_cond_test` when it is required? We need to know the name that needs to be defined for it.)

**Comment by bradcray** [comment]
Lydia's point about interfaces makes me realize belatedly:  Given that it's not (explicitly) user facing at the callsite (like operators are), is there any reason not to change _cond_test to a method (e.g., it could still be named _cond_test), in which case, having an object of that type would be sufficient to resolve the method due to our rules?  That seems like we could do that quite simply today and since it's not a user-facing feature, wouldn't even need to worry about deprecation.

**Comment by mppf** [comment]
Yes I agree a short-term fix would be to make `_cond_test` always a method. (I think we could come up with a user-facing name for it but it is also OK to separate that work).

**Comment by bradcray** [comment]
It seems so obvious now in retrospect...

**Comment by lydia-duncan** [comment]
> It seems so obvious now in retrospect...

I almost said it myself XD But yeah, I think making it a method would be fine, assuming we don't have the compiler explicitly look at "argument 1" and "argument 2" to determine what to do with it

**Comment by lydia-duncan** [comment]
(Because as a method, it will have a new "_this" and method token argument when the compiler tries to resolve it)

**Comment by bradcray** [comment]
I'm pretty sure that the current implementation is as simple as having the front end insert a `_cond_test()` call for every conditional and while loop, and everything downstream is ignorant of it, but I'll have to double-check that.

**Comment by bradcray** [comment]
I've got a five-minute fix (TM) for this specific bug and will open an issue about the larger question if we don't have one already.
