### ISSUE TITLE
`.size` should return `int` by default

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#17643]
This issue proposes that `.size` queries on various types and collections should return an `int` value by default, on the argument that:

* `int` is the default integer value in Chapel (e.g., `42` is inferred to be of type `int`)
* while `uint` is arguably a more logical type (since sizes can't typically be 0)...
  * ...`uint`s are more awkward to work with in Chapel due to the previous rule and the errors that `int` op `uint` cases generate
  * ...it's rare in practice that one creates something of size larger than `2**63`
  * ...using `int` has the slight benefit that one could utilize negative numbers as sentinel values

Furthermore, for those types and collections that may potentially have sizes larger than 2**63, this issue proposes that we:

* have bounds checks (which can be turned off) to avoid accidentally returning negative numbers in such cases
* support a `.sizeAs(type t: integral)` query so that one can query the size as a `uint`

We may optionally want to also support `.sizeAs(type t: integral)` queries for other types where users may want to get the result as a smaller integer size (and get the similar bounds-checking benefits.

The main case that this change affects is the family of ranges, domains, and arrays, each of which has typically returned an integer whose width and sign correspond to their `idxType`.  (e.g., `range(int(8))` returns an `int(8)` for its `.size` query).  This was originally done in order to keep operations on these types "closed" with respect to their `idxType`.  However, it is a problematic choice given that a large `range(int(8))` can contain more than `2**7` elements, and a 3D array of `int(8)` certainly can.

Making this change should help resolve some existing issues such as:
* https://github.com/chapel-lang/chapel/issues/7530
* https://github.com/chapel-lang/chapel/issues/17264

**Comment by mppf** [comment]
I'm happy with this direction but I think that we should immediately add `.sizeAs(type t: integral)` (or something along those lines) along with the change.

**Comment by bradcray** [comment]
That's the plan—and it essentially has to be because otherwise all of our internal modules that use `.size()` generate user-level warnings that a change is going to come.  Current sketch is here:  https://github.com/chapel-lang/chapel/pull/17628
