### ISSUE TITLE
Should type and non-type "overloads" of functions in the Types module have the same names?

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#17642]
In the [Types](https://chapel-lang.org/docs/master/modules/standard/Types.html) module, we have several functions like

```chpl
proc isBoolType(type x) param {}
proc isBool(x) param {}
```

should these versions have the same name and be more proper overloads of the same function? e.g.:

```chpl
proc isBool(type x) param {}
proc isBool(x) param {}
```

I think they should. I don't think the `Type` suffix adds much value to the interface and feel like the user should be able to just use `isBool` and be able to pass whatever they like to it.

**Comment by bradcray** [comment]
Without looking, I thought we had the pattern `isX()` (works with either types or values), `isXType()` (works with types only), `isXVal[ue]()` (works with values only) so that if you wanted to be precise ("I only want to check for types or values and don't want to accidentally pass the wrong thing in") you could be.

**Comment by e-kayrakli** [comment]
Ah, I think you are right. It is also stated in the documentation that `isBool` et al can accept type or value. So, it is my bad.

One missing piece is to finalize the `*Value` functions. They are there but not documented. It goes back to your comment here: https://github.com/chapel-lang/chapel/pull/212#issuecomment-53961433

I'll create a spinoff issue for it

**Comment by bradcray** [comment]
Hmm, I had completely forgotten about that comment (and that they were undocumented).

Having lost the "we should really rename `param` to `value`" fight (where I still think we should've :) ), I feel less strongly about the "value vs. variable" argument I was making in that comment today.  If I were forced to come up with names today, I'd leave the Value versions are they are and consider adding `isXParam` cases for types that support params.  Though arguably, this is not so different from `isXValue(x) && isParam(x)`.
