### ISSUE TITLE
Document `isXValue` functions in the Types module, (or implement alternatives?)

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#17644]
This has spun off from https://github.com/chapel-lang/chapel/issues/17642

We have functions like `isBoolValue` (alongside `isBool` and `isBoolType`) in the `Types` module, but they are no-doc'ed. I think we should document them.

The reason they are no-doc'ed goes back to https://github.com/chapel-lang/chapel/pull/212#issuecomment-53961433. But @bradcray sounded more OK with adding them to the interface today here: https://github.com/chapel-lang/chapel/issues/17642#issuecomment-833107858. Just to echo some of his thoughts under both comments, I see some value in differentiating params/literals from variables. But `isBoolValue(x) && isParam(x)` etc. feels expressive and concise enough to me.

**Comment by e-kayrakli** [comment]
Yes. They're in `modules/standard/Types.chpl`.

I would like to ping the developers to make sure that they're aware of this as this is a change in our standard libraries. I will do that Monday.

**Comment by bradcray** [comment]
A difference between the routines is that `isBoolValue(bool)` would return false whereas `isBool(bool)` would return true.

**Comment by mppf** [comment]
Yes, that is a difference, but does it matter? Could somebody wanting that instead write `isBool(x) && !isType(x)` e.g. ?

**Comment by strikeraryu** [comment]
> They could, but the convenience of not having to do that / ability to be more precise about the question being asked is why we've supported isXType, isXValue, and isX() for a type X.

In addition to @bradcray point, we are also not adding anything new to the module, we are just mentioning that we have these proc also.

**Comment by e-kayrakli** [comment]
> In addition to @bradcray point, we are also not adding anything new to the module, we are just mentioning that we have these proc also.

Technically we are adding them to the module *interface*. They have not been in the interface because they were undocumented, which is to say, a user's only way of finding out about them was to check out the module implementation and find out about them. So, a user code that uses these are not sticking to "legal" Chapel interface and using some internal functions that we never promised to be in the Chapel interface. This enables us to change those functions pretty much willie-nillie for internal purposes.

But now, if we document them, that means we are adding them to the user interface. So, we are promising that we support and maintain that interface. If; down the road, we want to change them, we should consider the possibility that any change we make can break user code that used to be valid/legal. In other words, once we document these functions, it'll be much harder for us to make changes on their interface and behavior.

**Comment by strikeraryu** [comment]
Ohh good to know, I never looked it that way. Thanks for mentioning it.

**Comment by strikeraryu** [comment]
Is the issue still under review, or can I work on it?

**Comment by e-kayrakli** [comment]
@strikeraryu -- Sorry, I let this fall through the cracks.

Yes. It'd be great if you can prepare a PR for it. This'll involve:

- Replace `pragma "no doc"` on top of relevant functions with short-and-sweet documentation.
  - The documentation should be very similar to `is*Type` and `is*` family of functions
- Run `make docs` and check the documentation locally
- Create a PR. (I think you have done this before, but let me know if you need any assistance there)

Thanks!!

**Comment by strikeraryu** [comment]
There are few procs that are defined elsewhere ( into their respective class ) like isTupleValue, etc. so that will be also documented?

**Comment by strikeraryu** [comment]
I have created the PR for this.
