### ISSUE TITLE
[Library Stabilization] order of get_d_2exp return values in BigInteger module

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#17696]
`bigint.get_d_2exp()` returns a tuple `(exp, d)` (which represents the number in the form `d * 2^exp`),  I assume because the exponent is passed back through a return argument in the original function while the double is returned directly.  It seems to me like the order of those values should be reversed - d is listed first in the name of the function and if you're trying to print the result in a human readable way, you'll list it first.

Michael agrees with this.

**Comment by bradcray** [comment]
It looks like this routine currently returns a `uint(32)` which seems to build an assumption into our code that C's integers are a certain size?  (also, checking the GMP documentation, it looks like it uses a `signed long` instead?  These observations make me wonder whether we should just make it a `uint` or `int` (where my quick look suggests `int` would be more correct)

**Comment by lydia-duncan** [comment]
That seems reasonable to me

**Comment by lydia-duncan** [comment]
In the module re-review, we decided to change the order of arguments to match the name

**Comment by bradcray** [comment]
Not directly related to this issue, but I'm not finding another with this function name in its title:  Have we discussed renaming this routine?  Do we know what we'd name it to?

**Comment by lydia-duncan** [comment]
I don't think we have discussed renaming it, no.  I think it didn't bother me because it "does what it says on the tin" - while it's not descriptive of the situations where you'd want to use it, it at least does describe what it returns.

**Comment by lydia-duncan** [comment]
> @lydia-duncan : Vaguely related to this: In reviewing pidigits codes today in the perf meeting, it was noted that divQR() is another BigInt function that logically returns two arguments, but currently does it through a `this` and a `ref` argument. This seems like another case where the clean way to do it would be to return a tuple of results (or to have a version that could do that at least). I didn't find any issues mentioning divQR, but wanted to ask whether that had been considered?

Oh, that's a good question.  I hadn't considered it, tbh - my initial reaction is that the other division methods store their result into `this` so it makes sense for divQR to use that format to match the others, but I would not be opposed to forms that return the result as an alternative.
 
> And re-reading your last response, I'm realizing I didn't understand it the first time around. I was asking about renaming in the sense of "it uses underscores... is that what we want?" not the identifiers per se. I.e., should it be something like getD2exp()? Or do the underscores imply something here like a subscript?

Oh, oops.  I was just assuming we were going to get rid of the underscores since we'd talked about doing so more broadly, so I thought you were asking about the identifiers.  I was thinking it would be `getD2Exp`.
