### ISSUE TITLE
[Library Stabilization] bigint size and sizeinbase questions

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#17693]
`bigint.size()` returns `size_t` but `bigint.sizeinbase()` returns `uint`.  Both call down to mpz wrapper functions that return `size_t` but they declare different return types (and the return value gets cast by the compiler to `uint` as a result).  Should these return the same type?  If so, should it be `size_t` or `uint` or `int`?  (I lean towards "yes" and "uint", but I'm okay with returning "int")
 
I don't think there's a scenario where these return the same value.  `bigint.size()` returns the "number of limbs" used to store the number while `bigint.sizeinbase()` returns the number of digits that would be used to express that number in the given base.

If we decide to continue returning `size_t` from `bigint.size()`, does this mean we should make the use of SysCTypes in the BigInteger module public?

Brad says:
> I'd be inclined to have [these both] return `int` along with our discussion with the range module to have all `.size()` routines return default int (I don't interpret this as a "hard and fast" decision yet, but I think it got a lot of positive support and makes sense for our language; we can have a `.sizeAs(type t)` routine if/when someone needs it returned as a different type, but I'm not sure I'd worry about that until then.

Michael initially went for `uint` as well but is mostly more in favor of using Chapel types over C types (which I agree with)

**Comment by bradcray** [comment]
Something that I missed in my original comments:  This `.size()` routine is paren-ful where most of our `.size` queries (on strings, ranges, domains, etc.) are paren-less.  I also missed that it was returning the number of limbs, where most of our `.size` queries return the number of things in the collection or the length of something.

For those reasons / differences, I'd be inclined to just deprecate this routine and have people who want this functionality use whatever hook we provide to get at the internal mpz_t type and then call mpz_size() on that.  Specifically, I don't see that there's great need for getting the number of limbs from a `bigint` for anyone who isn't interested in the details of the implementation.  And I don't think this `size()` corresponds well to the others that we support.  If we wanted to continue providing it, I'd probably call it `numLimbs()` or something like that, but it still falls into that "I'm a GMP expert implementer, not a user of big numbers in math" role that I think we're trying to minimize in the `BigInteger` module going forward.

For `.sizeinbase()`, I'd use `int` as the return type for the reasons we've discussed in other contexts https://github.com/chapel-lang/chapel/issues/17643  And this does seem like something that's useful for someone who's thinking about the mathematical value (e.g., "If I were to print this out, how much space would it take up?"), so I'd preserve it.  And change it to sizeInBase().
