### ISSUE TITLE
[Library Stabilization] What should we do about bigint.mpz and mpzStruct()?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#17694]
We currently document the `mpz` field in the `bigint` type and define a method `bigint.mpzStruct()` which returns an instance of `__mpz_struct` (which comes from the GMP module).  Both of these are implementation details potentially unsuited for what is intended to be more of a Chapel type than a type that is tied to GMP.  However, this information could be useful to users.

We could potentially "no doc" both of these symbols.  We could also choose to move `mpzStruct()` to the GMP module, ensuring that it relies on the BigInteger module.

Brad says:
> I feel like maybe we should just leave them where they are and mark them as being part of an "expert / could potentially change" interface / maybe add a --warn-unstable warning for them. Specifically, I think that—as part of our multiresolution strategy—there ought to be some way of dropping into the guts of the GMP type to get at the underlying data (similar to how one might want to poke into the guts of the array implementation and get the C pointer to the buffer(s) implementing their array). So I'd be inclined not to no doc it.
>
> Another approach would be to rename mpzStruct() to something like getImplDetails() or getGuts() and note that the behavior depends on the implementation of bigint (noting that, in our current GMP-based implementation, it will return an mpz structure). That would make it less GMP-specific without taking away the ability to get at the field.

If we do not "no doc" both of these symbols or move `mpzStruct()`, we should make the use of GMP public since they are provided by its interface.

**Comment by bradcray** [comment]
I'd missed that we are documenting the `mpz` field.  I think we should definitely stop doing that.

Summarizing my quoted text from the OP, for the `bigint.mpzStruct()` query, I'm open to any of the following (ranked mildly by preference):
* keep it in BigInteger but rename it as `bigint.getImpl()` or `bigint.getImplementation()` and document it as returning an implementation-specific type (with a note that, in our current implementation, it returns an `__mpz_struct`.
* keep it in BigInteger as-is but label it as being an expert / potentially unstable interface
* break BigInteger + GMP into three modules: BigInteger, GMP, C_GMP and move it into `GMP`
* create a GMP submodule of BigInteger and put it in there, labeling the submodule as being expert / potentially unstable

I think the strength of the first is that it's the smallest delta that makes BigInteger less GMP-centric.  The second is a smaller delta, but lets GMP peek through more than ideal/necessary.  The third and fourth feel clean, but I have a sense that that `GMP` module may not contain much other than this single routine in the short-term which makes it feel like overkill.  Ultimately, the GMP module could contain a complete Chapeltastic interface to `GMP_C`, but I don't know that there's a lot of desire or appetite for that (people who want something clean should be happy with BigInteger; people who want something expert probably won't be put off by the C-level GMP routines?).

> we should make the use of GMP public since they are provided by its interface.

I either don't agree with this or don't understand it.  I think it's fine for a module to return an instance of a type from another module without re-exporting all other symbols from that module (which is what this sounds like it's proposing?).  I.e., I don't think `use BigInteger;` should also inject all of GMP's symbols into my scope as well.

**Comment by lydia-duncan** [comment]
> > we should make the use of GMP public since they are provided by its interface.
> 
> I either don't agree with this or don't understand it. I think it's fine for a module to return an instance of a type from another module without re-exporting all other symbols from that module (which is what this sounds like it's proposing?). I.e., I don't think `use BigInteger;` should also inject all of GMP's symbols into my scope as well.

I'd be okay with publicly re-exporting the type that is returned and only including the rest privately (though it may be that my position on publicly using types hasn't yet adjusted for the newer reality where a type's primary and secondary methods can be accessed from anywhere regardless of if the scope defining them is visible)

**Comment by bradcray** [comment]
> I'd be okay with publicly re-exporting the type that is returned

I wouldn't even go that far where I'm trying to be pure ("you didn't ask for a GMP type when `use`ing BigInteger, so why would we give you access to one?") and brave w.r.t. the new world you're referring to here:

> it may be that my position on publicly using types hasn't yet adjusted for the newer reality where a type's primary and secondary methods can be accessed from anywhere regardless of if the scope defining them is visible)

where my thinking is:
* If the user never calls that routine, they don't have an unnecessary name in their namespace
* If they do call the routine, they can still call methods on the result
* but most likely, if they call the routine and want to call GMP routines, they'll likely `use` or `import` GMP and get whatever they need that way

**Comment by lydia-duncan** [comment]
Conclusions from the re-review:
- Okay to document that function returns the specific type as long as we indicate it may change later
- Use `getImpl` as new name
- Stop documenting field
