### ISSUE TITLE
[Library Stabilization] What to do about "limbs" in BigInteger?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#17695]
A limb is a concept from GMP representing the portion of a multi-precision number that fits in a single machine word (which can vary in number of bits used) and one that we explain nowhere in our own documentation (not even in our GMP documentation). Should we provide this information at all via the `bigint.numLimbs` and `bigint.get_limbn()` methods? It seems like potentially an implementation detail, but I could also see it being relevant to people using the type, especially if they are trying to use it in a performant way.  If we do decide to keep it in, we definitely need to explain it.

Brad says (in https://github.com/chapel-lang/chapel/issues/17616#issuecomment-839210987):
> I feel like maybe we should just leave them where they are and mark them as being part of an "expert / could potentially change" interface / maybe add a `--warn-unstable` warning for them. Specifically, I think that—as part of our multiresolution strategy—there ought to be _some_ way of dropping into the guts of the GMP type to get at the underlying data (similar to how one might want to poke into the guts of the array implementation and get the C pointer to the buffer(s) implementing their array). So I'd be inclined not to no doc it.

Another approach from Brad (depending on how we handle `mpzStruct`, see #17694):
> If the numLimbs call can be made using the GMP module on the results of mpzStruct() directly, I'd just deprecate it from BigInteger and have people call the GMP routine when they want that information.

**Comment by bradcray** [comment]
Yeah, I'm definitely leaning more towards deprecating this and requiring people to get at it by requesting the mpz type from their bigint and calling into the GMP interface.  At least, I don't have a scenario in mind where someone using `bigint` to compute math / integers with would want this capability.
