### ISSUE TITLE
[Library Stabilization] Value of bigint stored after `bigint.invert()` fails is undefined

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#17708]
If the return value is 0 then the value stored in `this` is undefined.  That seems fraught with peril to me, does that worry anyone else?

**Comment by bradcray** [comment]
This doesn't particularly worry me since GMP has set the precedent.

What would we do instead?
* halt (wouldn't let someone write code that checks whether something is invertible)
* throw (increases annoyance when making well-behaved calls; other bigint routines don't throw?)
* store some other arbitrary value into `this` (may be expensive?)
* ...something else...?

If we leave it undefined for now, and store some other value into it later, it's at least not a breaking change?

**Comment by lydia-duncan** [comment]
I think part of what bothers me about it is the fact that it's a method that overwrites its value, going back to the weirdness in #17699.

I wouldn't worry about it if the code looked like `proc invert(out val: bigint, const ref a: bigint, const ref b: bigint): int`, the out argument having an undefined value when the return value is a certain way seems fine.

Heck, I'd probably be okay with it if `this` was one of the values operated on as part of the change (e.g. `proc bigint.invert(const ref op2: bigint): int`.  The fact that `this` stores a potential result and is left in a weird state sometimes just feels subtle to me and so more dangerous.

But maybe someone that's used to working with GMP or the other routines in this module will just be sufficiently used to the `this` receiver being overwritten that it isn't as bad as I'm worried about

**Comment by lydia-duncan** [comment]
In the module re-review, the lean was conclusively towards throwing.

**Comment by lydia-duncan** [comment]
I marked this as ready to implement, but in starting to do so, I'm realizing that there's a question about **what** should be thrown.  Some options I came up with:

**1. IllegalArgumentError**
---------------------------
- Pros:
  - Already exists
  - Indicates source of problem
  - Commonly accessible from the Errors module, included by default
- Cons:
  - Typically used when the argument itself is bad, but the problem in this function is the combination of arguments that lead to the throw, and really, it's hard to know it would be bad without calling the method anyways


**2. ArgumentError (from ArgParser)**
---------------------------------------
- Pros:
  - Already exists
  - Indicates source of problem
- Cons:
  - Defined in the ArgumentParser package module, so would add a dependency on something that might move to a mason package
  - Similarly to IllegalArgumentError, typically used when the argument itself is bad, but the problem in this function is the combination of arguments.

**3. Error (no subclass)**
--------------------------
- Pros:
  - Doesn't create a new subclass, so no need for further design discussions
  - Situation is likely to be a one off in this module
- Cons: 
  - Distinguishing between an error thrown by this method and another Error requires the other error to be its own subclass or requires examining the result of `message()`
  - If we add an invert function to, say, the Math module, we'd just duplicate the message.  Could add a subclass of Error then, but old user code would still rely on checking the message explicitly

**4. new subclass of Error created for this case**
-------------------------------------------------
- Pros:
  - Fits the situation accurately and can make the catch clause more self-descriptive
  - Easily distinguishable from other Error subclasses, allowing users to write a specific catch clause that will only trigger for this case
  - If we later add an invert function to the Math module, can use the same Error subclass there, too
- Cons:
  - May not be relevant to other library or user code, making it a one-use subclass
  - Requires additional design work to come up with a good name (maybe InversionError?  Open to other suggestions), determine where it should live (should it be in BigInteger, or maybe in Errors since Math or a matrix library might add their own use of it)

**Comment by lydia-duncan** [comment]
It's a little too close to the release for what feels like a relative minor design discussion, so I think I'll probably punt on it until after and look at the remaining BigInteger issue I had marked as "ready"

**Comment by lydia-duncan** [comment]
I think in exploring the pros and cons of each option, I'm inclined to rank them: 4, 3, 1, 2 (in order of preference) but 3 and 4 are fairly close to me.

**Comment by mppf** [comment]
FWIW I think that 2 and 3 do not make sense. In particular I don't understand why we would use an error from ArgumentParser in the BigInteger module. And throwing a general Error makes the situation opaque without much benefit. 1 or 4 both see OK to me though.

**Comment by e-kayrakli** [comment]
I am for 4. Specific Errors make more sense to me.

> May not be relevant to other library or user code, making it a one-use subclass


Can we not add this error to the BigInteger module? It can help with this concern.

**Comment by lydia-duncan** [comment]
We absolutely can, but if it ends up being useful for other libraries like Math or a matrix library then that might justify putting it in Errors instead

**Comment by e-kayrakli** [comment]
Oh, right. FWIW, I would still consider putting it somewhere other than `Error`, like Math. This feels a bit too esoteric to go to Errors module. But this is not a strong opinion.

**Comment by lydia-duncan** [comment]
Okay, it sounds like a new Error subclass is the agreed upon choice.  Now we need to think of a name and decide where to put it.

I propose `InversionError` as the name, but I'm open to other suggestions.

In terms of where to put it, that I'm a little less certain about.  I think there's three options:
1. Errors
  - Pros: Allows it to be used more generally if it ends up being applicable in other places 
  - Cons: Might not be applicable in other places
2. BigInteger
  - Pros: Where the Error subtype will be used, so no need to clutter up other namespaces
  - Cons: If it does end up being needed elsewhere, now that code needs a use of BigInteger, which relies on GMP (which is less than ideal)
3. Math
  - Pros: More generally available place than BigInteger if it does end up being useful there.  Logically, a less niche place to look for the Error subclass
  - Cons: if we don't end up having an invert function in the Math module, would be odd to have it live there and not be used by the code near where it lives.

Vote here:
😄 - Errors
🎉 - BigInteger
❤️ - Math

**Comment by e-kayrakli** [comment]
I voted for `BigInteger`, with the thinking that we might move it to more general locations if/when needed.

**Comment by lydia-duncan** [comment]
Do you have a preference on the name?

**Comment by mppf** [comment]
I voted for BigInt but don't have a strong preference. One potential name is `DivideByZeroError`. That could go into Errors or Math, at the risk of hinting that we actually throw this error in non-bigint divide by 0...

**Comment by lydia-duncan** [comment]
Resolved by #19990
