### ISSUE TITLE
[Library Stabilization] Should `bigint.gcdext()` return a tuple of values?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#17707]
Seems like we could return s and t as a tuple of values like `bigint.get_d_2exp()` does (though that arguably does fall under the performance question in #17699 )

**Comment by bradcray** [comment]
I assume that performance would be the reason not to do this.  `get_d_2_exp()` has the benefit of only returning primitive types.  We could always add a "takes two args / returns 2-tuple" version later without it being a breaking change.

**Comment by lydia-duncan** [comment]
#17731 also deals with this function.  I'm not sure if having them separate was the right choice but didn't think of it before making the #17731

**Comment by lydia-duncan** [comment]
In the module re-review meeting, it sounded like we were going to move this method to being an overload of gcd, with the extra arguments as the distinguishing factor.  With that in mind, returning a tuple of values is not reasonable
