### ISSUE TITLE
[Library Stabilization] Should `bigint.probab_prime_p()` return an enum instead?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#17706]
We could potentially return an enum value that better documents the state (but it would only matter for this function, I think)

Michael thinks this is reasonable

**Comment by bradcray** [comment]
I could go either way on this, where the main tension seems to be increased clarity vs. potential learning curve for GMP-savvy programmers.  Having the enum share the same 0, 1, 2 values we currently return would help a bit, but not completely (e.g., `if (myBigint.probab_prime_p() == 1) { ... }` wouldn't compile...).

**Comment by lydia-duncan** [comment]
Resolved by #18855
