### ISSUE TITLE
[Library Stabilization] Should these BigInteger methods return booleans?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#17701]
There are a number of methods on the `bigint` type that return 0 or some other value.  It seems to me like these methods are a result of booleans being in a weird state for C where they can be used but aren't necessarily used extensively when they could be.  In Chapel, it seems more appropriate to return a bool where possible.

Affected methods:
- `bigint.divisible_p()`
- `bigint.divisible_2exp_p()`
- `bigint.perfect_power_p()`
- `bigint.perfect_square_p()`
- `bigint.congruent_p()`
- `bigint.congruent_2exp_p()`
- `bigint.even_p()`
- `bigint.odd_p()`

I would probably rename these functions to something like `isDivisible` or `isDivisibleBy`, etc. while there, and drop the p (I have no idea why they end in p - maybe it stands for precision?)

Some of these at first glance seem like they would make sense to return something other than a bool, but seem to only return 0 or 1 today, so I think using them in this manner is appropriate (and there's probably something that can be done to ensure they always return the "right" bool value even if the underlying implementation changes (which seems unlikely at this point but is something to watch out for).

**Comment by lydia-duncan** [comment]
Note that there are also six `fits_*` methods that probably should also return a bool, but I think these functions need additional adjustments (see #17702)

**Comment by bradcray** [comment]
I'm not familiar enough with these to feel confident, but I generally agree with your proposals here: returning bools and making their names more `isProperty()`-ish.  I think it'd be worth understanding what the `_p` denotes (my guess: "predicate"—something that returns true/false).

**Comment by tiger-yash** [comment]
Hey @lydia-duncan, @bradcray!  
I would like to work on this as well 😁!

**Comment by tiger-yash** [comment]
> Go for it! You'll probably want to keep work on the divisible and congruent methods to that PR where you were adjusting the argument names for them to avoid merge conflicts, but other than that I don't foresee any issues

Yes Thank you, I plan to base this one on that same branch instead of making changes to that same PR so that it is easier to review.
Is it alright?

**Comment by lydia-duncan** [comment]
Ugh, thought I changed it so that PR wouldn't close this issue.  Oh well

**Comment by lydia-duncan** [comment]
Remaining methods, which will be updated in #18784:
- `bigint.divisible_p()`
- `bigint.divisible_2exp_p()`
- `bigint.congruent_p()`
- `bigint.congruent_2exp_p()`
