### ISSUE TITLE
[Library Stabilization] Implementation details involving casts and stability in BigInteger module

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#17710]
We do a lot of casts to C types, but we use the GMP module.  Should we be casting to its types instead where applicable?  That seems more stable in case they change the type they represent under the covers (though it does seem unlikely that they will make changes like that frequently)

**Comment by bradcray** [comment]
I'm not familiar enough with the code to have a sense of what the options are here—can you give a motivating example?  Does this have an impact on the end-user / library stabilization?

**Comment by lydia-duncan** [comment]
I might have gotten confused.  It looks like we do cast to `mp_bitcnt_t` when we call functions that take it rather than `unsigned long int`.  I think I saw a `c_ulong` cast and assumed we were doing that everywhere.  Closing
