### ISSUE TITLE
[Library Stabilization] Should BigInteger bit manipulation methods still take ints?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#17711]
`bigint.setbit()`, `bigint.clrbit()`, `bigint.combit()` and `bigint.tstbit()` all take integrals as their index arguments to adjust portions of the integer.  Should they just take uints?  A negative value doesn't make sense to me and we cast the argument to c_ulong in the body of the function . . .

**Comment by lydia-duncan** [comment]
Brad says:
> Wouldn't this make it annoying to pass in an int? (since the compiler can't determine that it's not negative, so will require a user cast?). Could we rely on a `.safeCast()` within the routine to take any integral and make it what we need? (this was probably written before we had `.safeCast()`).

And Michael says:
> It's common in Chapel for people to use `int` generally, and the type system doesn't allow these to be implicitly converted to `int`, which is why we have choices like this. I'd probably leave them taking `integral` but I don't think it's a big deal either way.

**Comment by vasslitvinov** [comment]
We had a similar discussion for {PCGRandomStream,NPBRandomStream}.skipToNth() and getNth(), which currently accept any kind of int, whereas a `uint` formal would suffice. Brad's reasoning won.

**Comment by lydia-duncan** [comment]
In the module re-review, we decided these method arguments should be left as-is
