### ISSUE TITLE
[Library Stabilization] Rename BigInteger `powm` method to `powMod`?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#17729]
The m stands for mod and it was named this to more closely match the GMP function `mpz_powm`.  However, since we are not tying `bigint` as closely to GMP's conventions, I think it makes sense to rename this method to `bigint.powMod` to be more clear.

Note: also add documentation for this method at the same time

**Comment by bradcray** [comment]
My feelings here are similar to https://github.com/chapel-lang/chapel/issues/17724#issuecomment-840803765 (positive, with some means for GMP programmers to map from one to the other).
