### ISSUE TITLE
[Library Stabilization] Should the argument names for these BigInteger methods be longer?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#17727]
The arguments for `divexact`, `divisible_p`, `divisible_2exp_p`, `congruent_p` and `congruent_2exp_p` are a single character long.  The letter used is descriptive (n for numerator, d for divisor and denominator, c for congruent, b for base), but it seems like having a longer argument name would be more friendly.

Do others agree?

If so, I'd like to propose:
- `bigint.divexact(numer, denom)` (To avoid confusion with num for number)
- `bigint.divisible_p(div)`
- `bigint.divisible_2exp_p(exp)`
- `bigint.congruent_p(con, mod)`
- `bigint.congruent_2exp_p(con, modExp)`

You can find these function descriptions here: https://gmplib.org/manual/Integer-Division

(We talk about the names of the methods themselves in #17724 so I'm not going to have those changed here for clarity)

**Comment by tiger-yash** [comment]
hello @lydia-duncan! 
I would like to work on this issue.

**Comment by lydia-duncan** [comment]
Hi @tiger-yash - that'd be great!  You'll want to make sure there's a deprecation warning for the old version of the functions and a test that tracks that warning in `test/deprecated`.  You can find tips on how to do that at the following link: https://chapel-lang.org/docs/main/developer/bestPractices/Deprecation.html#best-practices-deprecation

Definitely let me know if you have questions!

**Comment by tiger-yash** [comment]
Thank you @lydia-duncan!
Please Correct me if I am wrong, but Since we are only altering the function variables and basically the functions from inside, do we need to place deprecation warnings?

**Comment by bradcray** [comment]
> do we need to place deprecation warnings?

@tiger-yash : We do because Chapel supports pass-by-keyword argument passing, so given:

```chapel
proc foo(x: int) { ... }
```

a user can call:  `foo(x=42)` and if we change the name of `x` we will break their code.

**Comment by tiger-yash** [comment]
@bradcray @lydia-duncan 
I have created a PR #18784, for resolving this issue. Please review!
