### ISSUE TITLE
[Library Stabilization] Change BigInteger module method names

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#17724]
Some methods use camelCase, some use all lower case, some use snake case.  These should all be unified to use camelCase per the standard module guidelines.

I also think all "p"s at the end of method names should be dropped

**Comment by bradcray** [comment]
I also wonder whether we should use better/different names (ones that are more Chapeltastic / Pythonic / less C-like).  E.g., is `.sgn()` really preferable to `.sign()`?  `clrbit()` preferable to `clearBit()`?

**Comment by bradcray** [comment]
Something else we might think about is looking for other cases where a language has wrapped GMP (e.g., does Python?) and see what they did in terms of making routine names more descriptive?

**Comment by lydia-duncan** [comment]
> I also wonder whether we should use better/different names (ones that are more Chapeltastic / Pythonic / less C-like). E.g., is `.sgn()` really preferable to `.sign()`? `clrbit()` preferable to `clearBit()`?

Heh, I was going to call those out in separate issues

**Comment by lydia-duncan** [comment]
It looks like the Python GMP package also drops the `_p` and uses `is_odd` instead of `odd_p`: https://gmpy2.readthedocs.io/en/latest/mpz.html#mpz-methods

**Comment by tiger-yash** [comment]
Hey @lydia-duncan, I would Like to work on this along with #17730

**Comment by lydia-duncan** [comment]
I sorta view this as a bit of a meta issue - you're making great progress on the BigInteger issues, but I don't want to lock us into having to finish the updates to this module if it's more than we can do for the next release cycle and updating every method's name in one PR would do that.  So I recommend keeping it in mind for #17730 but not viewing it as something you have to finish at the same time.  I think working on #17730 would be great (but be sure to take a look at #17706 at the same time!)

Or was that basically what you were asking?

**Comment by tiger-yash** [comment]
Yes actually there are very few method names left to change so I thought to work on `bigint.probab_prime_p()` issues along with this one, and I guess that is what you also mean..

**Comment by tiger-yash** [comment]
Hello @lydia-duncan @bradcray! Please help me out with some details here,
* For the `bigint.fits_ulong_p` and its other types, should I also change the return type to `bool`? 
[As in the case the value is not fitting in the given range it returns 0(false) and any non-zero value(true) in other cases.]
* Do `bigint.fitsUlong` type names sound good for these? or should i make  it `bigint.isUlong`?

**Comment by lydia-duncan** [comment]
Let's move discussion about `fits_ulong_p` over to #17702

**Comment by jabraham17** [comment]
Starting a list of methods that need to be examined for renaming

- `mul_2exp` -> `mul2Exp`
- `setbit` -> `setBit`
- `combit` -> `comBit`
- `rootrem` -> `rootRem`
- `sqrtrem` -> `sqrtRem`
- `nextprime` -> `nextPrime`
- `addmul` -> `addMul`
- `submut` -> `subMul`
- `popcount` -> `popCount`
- `hamdist` -> `hamDist` or lengthen the name?

Note: two other `*bit` functions are mentioned in #17735 to both lengthen and camelCase their names

**Comment by jabraham17** [comment]
In a recent discussion (https://github.com/Cray/chapel-private/issues/4969), we decided on the following renamings
- `rootrem`/`sqrtrem` -> `rootRem`/`sqrtRem`
- `nextprime` -> `nextPrime`
- `addmul`/`submul` to `addMul`/`subMul`
- `popcount` to `popCount`
- `hamdist` -> `hammingDistance` and marking it as unstable


We also decided to deprecate `get_str` in favor of using a cast to a string.
