### ISSUE TITLE
[Library Stabilization] Potential changes to BigInteger's `bigint.gcdext()`?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#17731]
This method computes the greatest common denominator and also returns the coefficients that when multiplied with the `a` and `b` arguments produce the greatest common denominator (see https://gmplib.org/manual/Number-Theoretic-Functions for the full definition)

I find it difficult to read as is and would be inclined to at least rename it to `bigint.gcdExt()`.  It seems like there could potentially be a better name for the function and for the arguments.  Maybe `bigint.gcdAndCoefficients(arg1, arg2, ref arg1Coeff, ref arg2Coeff)`?  (Note that this also rearranges the argument order)

**Comment by lydia-duncan** [comment]
See also #17707

**Comment by lydia-duncan** [comment]
In the module re-review meeting, it was suggested that this be changed to an overload of `gcd` that takes in extra arguments (which would be the return value).  It sounded like this will be the plan.

**Comment by bradcray** [comment]
I'm cool with this plan.  This is one case that seems as though it _may_ have an analog in "normal" math libraries.

**Comment by lydia-duncan** [comment]
I did a search on just that name, it looks like it's only related to GMP, at least on the first page of google results.
