### ISSUE TITLE
[Library Stabilization] Should we rename BigInteger's `bigint.probab_prime_p()`?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#17730]
Aside from the `_p` question which will be discussed in #17724, are there other improvements we can make to this method name?  I don't have any suggestions myself, it just seems weirdly truncated but also too long to me.

The corresponding GMP function is defined here: https://gmplib.org/manual/Number-Theoretic-Functions

**Comment by lydia-duncan** [comment]
Note that we're discussing other changes to the function in #17706

**Comment by bradcray** [comment]
I'd probably call this `probablyPrime()`?
