### ISSUE TITLE
[Library Stabilization] Should we lengthen these BigInteger method names?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#17735]
The following method names seem unnecessarily shortened, since they just lose one or two letters.  Should we lengthen them?

- `bigint.clrbit()` to `bigint.clearBit()`
- `bigint.tstbit()` to `bigint.testBit()`
- `bigint.sgn()` to `bigint.sign()`

**Comment by lydia-duncan** [comment]
Looks like `sgn` is specified in the ISO 80000-2 standard and is listed as a common abbreviation for it in Wikipedia, we should probably not muck with that for `BigInteger` or `Math`.  I think the other two are fair game, though.

**Comment by jabraham17** [comment]
Related to these methods are `setbit` and `combit`, which if these methods change should also be changed to `setBit` and `comBit`

**Comment by lydia-duncan** [comment]
Also related is #22008

**Comment by jabraham17** [comment]
In a recent discussion (Cray/chapel-private#4969), we decided on the following renamings
- `setbit` -> `setBit`
- `clrbit` -> `clearBit`
- `tstbit` -> `getBit`
- `combit` -> `toggleBit`
- `sgn` is left alone

**Comment by lydia-duncan** [comment]
I believe we were also going to reference the equivalent GMP function names so that users doing a search for those names would find the new function names
