### ISSUE TITLE
[Library Stabilization] Should we rename BigInteger's `bigint.remove()` method?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#17732]
This method name does not really seem clear to me.  The function removes all instances of the factor (`f`) arg from the other arg (`a`), storing the result in `this` and returning the number of times the factor was removed.  I think "remove" conflicts pretty regularly with other remove methods.  Maybe `bigint.removeFac()` would be better?  I'm open to other suggestions as well

This function is defined here: https://gmplib.org/manual/Number-Theoretic-Functions

**Comment by tiger-yash** [comment]
Hey!
I would like to work on this issue if there is no one already working on it.

**Comment by lydia-duncan** [comment]
That'd be great, though this issue is a little less certain on what the new name should be.  Do you think `removeFac` is a good name?  Do you have a better suggestion?  It might be good to send an email to the developers mailing list in https://chapel.discourse.group/ to make sure people have a chance to object to the new name.  That email should follow the guidance at https://chapel-lang.org/docs/main/developer/bestPractices/ContributorInfo.html#creating-a-design-issue in the last bullet (since this issue would be considered the design issue, you mostly would need to find other people to have an opinion and I can help lean on people if no one is volunteering).

**Comment by tiger-yash** [comment]
> That'd be great, though this issue is a little less certain on what the new name should be. Do you think `removeFac` is a good name? Do you have a better suggestion?

Yes, I think removeFac does seem like an appropriate name and also renaming would indeed make it more descriptive.

> It might be good to send an email to the developers mailing list in https://chapel.discourse.group/ to make sure people have a chance to object to the new name. That email should follow the guidance at https://chapel-lang.org/docs/main/developer/bestPractices/ContributorInfo.html#creating-a-design-issue in the last bullet (since this issue would be considered the design issue, you mostly would need to find other people to have an opinion and I can help lean on people if no one is volunteering).

Sure! I'll send the mail.

**Comment by bradcray** [comment]
Unless `fac` is already used heavily in BigInteger, I'd be inclined to go with `removeFactor`.  It's only slightly longer and, I think, lots less ambiguous.  When getting an email notification of Lydia's comment above, I found myself wondering whether `Fac` meant `Face`, `Facet`, `Factor`, `Factorial`, or something else that I couldn't guess.

**Comment by tiger-yash** [comment]
Well yes @bradcray, Now that you pointed it out, I too would feel confused on coming across `Fac` the first time. `removeFactor` really does seem like the better name.

Also I have sent out the [email](https://chapel.discourse.group/t/should-bigintegers-bigint-remove-be-renamed/8519?u=tiger-yash) as @lydia-duncan asked, so maybe it might help out more in making a final decision.

**Comment by lydia-duncan** [comment]
I'm good with `removeFactor` :)

**Comment by tiger-yash** [comment]
@lydia-duncan @bradcray I have created the PR for the issue, please review.
