### ISSUE TITLE
[Library Stabilization] Should we rename the BigInteger `bigint.ior()` method?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#17737]
The "i" stands for "inclusive" to distinguish from `xor`, but I don't recall seeing that anywhere else in our modules.  I'd be inclined to rename this to `bigint.or()`

**Comment by jabraham17** [comment]
In a recent discussion (Cray/chapel-private#4969), we decided to rename `ior` to `or`
