### ISSUE TITLE
[Library Stabilization] Should we rename the BigInteger lucnum* methods?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#17733]
`bigint.lucnum()` and `bigint.lucnum2()` are short for Lucas Number.  I think we should rename these methods to `bigint.lucasNum()` and `bigint.lucasNum2()`.

Note - the functions on which they are based are defined here: https://gmplib.org/manual/Number-Theoretic-Functions

**Comment by lydia-duncan** [comment]
Note that these methods are also relevant to #17697

**Comment by lydia-duncan** [comment]
Michael indicated support of this renaming

**Comment by bradcray** [comment]
The 2 just means "give me two of them?"  Should we call it `lucasNums`?  :)

**Comment by lydia-duncan** [comment]
I think an "s" hides a little more in a name than a "2" does so left to my own devices, I'd probably stick with the 2 version, but I don't have a problem with going the other way :)

**Comment by bradcray** [comment]
We could also provide two overloads with the same name since we're not C; or create a single varargs routine that does any number of them.

**Comment by jabraham17** [comment]
In a recent discussion (Cray/chapel-private#4969), we decided to rename `lucnum`/`lucnum2` to `lucNum`/`lucNum2`, and we will mark them unstable
