### ISSUE TITLE
Should LLVM-based compiles be indicated through CHPL_TARGET_COMPILER rather than `--llvm`?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#17795]
Traditionally, `CHPL_TARGET_COMPILER` has been used to indicate which C compiler should be used to compile the C code generated by the `chpl` compiler as well as the runtime and third-party libraries that we link that code against.  However, when using the LLVM back-end (by building with `CHPL_LLVM!=none` and compiling with `--llvm`, we tend to essentially ignore `CHPL_TARGET_COMPILER`, using `clang-included` when `CHPL_LLVM == bundled` and `clang` when `CHPL_LLVM=system`.  This can potentially lead to confusion due to having too many options that specify how code is generated and compiled depending on the relative settings of `CHPL_TARGET_COMPILER`, `CHPL_LLVM` and the `--[no-]llvm` flag arguably leading to sources of confusion as have been noted in [this Discourse thread](https://chapel.discourse.group/t/build-process-for-variants-of-llvm-dependency/4554) or issues https://github.com/chapel-lang/chapel/issues/17606, https://github.com/chapel-lang/chapel/issues/17598, and https://github.com/chapel-lang/chapel/issues/17584

In this issue, I'm proposing that we unify these settings as follows:
* `CHPL_TARGET_COMPILER`:
  * setting this to `gnu`, `intel`, `clang`, etc. would indicate that the C back-end should be used with the specified compiler
  * setting it to `llvm` would indicate that the LLVM back-end should be used
    * when C code needs to be compiled (e.g., the runtime, third-party libraries, or any `.c` files specified on the `chpl` command line or the code's `require` statements), `clang` will be used.  Similar to today, the bundled version of clang will be used when `CHPL_LLVM=bundled` and the version in the user's path when `CHPL_LLVM=system`

This would effectively eliminate the need for the `--[no-]llvm` flag since the `--target-compiler` flag would essentially give the same control while reducing confusion about the meaning of `CHPL_TARGET_COMPILER` in an LLVM-based compilation, as well as the need for `clang` vs. `clang-included` as user-facing settings.

* `CHPL_LLVM`: this would now say where to get LLVM from in the event that it's needed
  * `system`: use the system-installed version
  * `bundled`: use the bundled version
  * `none`: this would effectively result in an error if `CHPL_TARGET_COMPILER` were set to `llvm`
  * `unset`: similar to today, would be a sentinel value indicating that the user didn't set it and we don't know what to set it to

This would also have the effect of making the `CHPL_LLVM` flag slightly more like the current `CHPL_RE2` and `CHPL_GMP` variables in the sense of "Someone has requested LLVM (via their `CHPL_TARGET_COMPILER` or `--target-compiler` setting), so where should I get it from?"

**Comment by bradcray** [comment]
This approach generally resonates well with me.  The main question it leaves me with is what default values we should use.  Here's a proposal:

* `CHPL_LLVM`:
  * defaults to `system` if we detect that a suitable system-installed LLVM is present
  * defaults to `none` if we are on a system where we know the LLVM back-end won't work (e.g., `linux32` today)
  * defaults to `unset` otherwise
* `CHPL_TARGET_COMPILER`:
  * defaults to `llvm` if `CHPL_LLVM=bundled` or `system`
  * complains if `CHPL_LLVM=unset`, requiring CHPL_TARGET_COMPILER or CHPL_LLVM to be explicitly set
  * otherwise uses today's defaults

**Comment by bradcray** [comment]
@BryantLam: I'd be curious to get your reactions to this proposal, given the issues you've filed recently regarding confusion about the relationship between enabling LLVM and the host/target compilers.

**Comment by mppf** [comment]
This proposal sounds good to me. There is one thing I am uncertain about, however.

Is it useful to be able to have `CHPL_LLVM=bundled` or `CHPL_LLVM=system` and then generate C and compile it with the clang compiler selected by `CHPL_LLVM`? I am thinking it might be nice to have an easy way to toggle between the C and LLVM backends without changing other configuration. If so, we might want to have `CHPL_TARGET_COMPILER=llvm-clang`. But, I think that this feature seems to be inherently confusing (and in fact it's similar to "clang-included").

A related wrinkle is that today we have a bunch of tests that use `--no-llvm`. With this proposal, these tests will need to be updated to do one of:
 * skipif for `CHPL_TARGET_COMPILER=llvm`
 * select a C compiler - `CHPL_TARGET_COMPILER=gnu`. To do that we have to predict which C compiler the runtime is built. Maybe the answer is always `gnu` in our testing.

**Comment by bradcray** [comment]
In the proposal above, I was imagining that setting `CHPL_TARGET_COMPILER=clang` or `--target-compiler=clang` with `CHPL_LLVM=bundled` or `CHPL_LLVM=system` would generate C code and use the bundled or system clang to build it.

> today we have a bunch of tests that use --no-llvm

My hope is that the number of these tests gets much smaller over time (e.g., to those that are explicitly testing things about the C back-end) and can either be put into their own "c-back-end" test directory which is skipif'd for llvm, or can use `target-compiler=clang` if we adopt the approach just above.

> can we stop building the runtime twice?

I think / hope so.

**Comment by mppf** [comment]
Related to this:

> In the proposal above, I was imagining that setting `CHPL_TARGET_COMPILER=clang` or `--target-compiler=clang` with `CHPL_LLVM=bundled` or `CHPL_LLVM=system` would generate C code and use the bundled or system clang to build it.

Suppose we have `CHPL_LLVM=bundled` and `CHPL_HOST_COMPILER=clang`. Should we use the bundled version of `clang` to build the Chapel compiler itself in that event? Or, is that a bad idea because we use `CHPL_HOST_COMPILER` to build the bundled LLVM and so it is a kind of circular dependency? (We could consider checking that the bundled clang is built to break the circularity)

**Comment by bradcray** [comment]
Good question.  Maybe we always interpret `clang` as "system clang" if `CHPL_HOST_COMPILER=clang` to break the dependency?  (and if you don't have a system clang, you shouldn't have set it?)

**Comment by mppf** [comment]
> In the proposal above, I was imagining that setting `CHPL_TARGET_COMPILER=clang` or `--target-compiler=clang` with `CHPL_LLVM=bundled` or `CHPL_LLVM=system` would generate C code and use the bundled or system clang to build it.

> Good question.  Maybe we always interpret `clang` as "system clang" if `CHPL_HOST_COMPILER=clang` to break the dependency?  (and if you don't have a system clang, you shouldn't have set it?)

If both of these combine, wouldn't that mean that on Mac OS X somebody would be unable to compile with the bundled clang? Because `CHPL_HOST_COMPILER=clang` and then we assume that `clang` in `CHPL_TARGET_COMPILER=clang` refers to the system one?

Oh, did you mean: 

Maybe we always interpret `clang` as "system clang" *in* `CHPL_HOST_COMPILER=clang`

?

**Comment by bradcray** [comment]
Yes, though this didn't occur to me in my original proposal, in response to your previous question, I was thinking that:

CHPL_HOST_COMPILER=clang == "always use system clang" (the clang that's "in your path")
CHPL_TARGET_COMPILER=clang == "use bundled clang if LLVM=bundled, use system clang otherwise"

Is anything lost?  Let's say a person doesn't have a system clang, but really wants to use clang as the host compiler...  Maybe they could build the bundled llvm manually / first, and then manually add that path to their shell's path so that it becomes their "system clang" if you will?  (though they'd still want to set CHPL_LLVM=bundled for everything else to work appropriately?  though I suppose they could set their CHPL_LLVM_PREFIX and such to point to the bundled version if they wanted to for some reason...?)

**Comment by mppf** [comment]
Yeah, I think that would work. It's sortof a weird thing to do anyway (using the bundled llvm/clang as the host compiler) and setting `CHPL_LLVM_PREFIX` to the bundled version seems acceptable.

**Comment by mppf** [comment]
I have a start at implementing this in #17800.

**Comment by bradcray** [comment]
I told Michael that I think we have consensus on this based on the thumbs-ups, advertisement of the principle in meetings and Discourse, and lack of objections raised.

**Comment by mppf** [comment]
PR #17800 implemented this and I've merged it and handled some follow ups. So I'm closing this issue.
