### ISSUE TITLE
[Feature Request]  Database module

### ISSUE THREAD

**Issue by 12mohaned** [chapel-lang/chapel#17803]
I suggest building a database module in Chapel that support database operations. For the sake of motivation,  it can be something similar to [cdo](https://github.com/chapeldev/cdo) which supports several databases through using connecting with an API. I would suggest developing the module on top of ODBC architecture.

I am willing to collaborate on this module.

**Comment by ben-albrecht** [comment]
Hi @12mohaned, are there specific features that you are looking for that cdo does not support? I encourage you to suggest those features as issues on the cdo repository, or start a new odbc-specific database module as a mason package if you're interested in a different approach to database API overall.

For archiving purposes, I want to close this issue as a duplicate with https://github.com/chapel-lang/chapel/issues/6800, but we can continue discussion here or over on the other issue.
