### ISSUE TITLE
Allow mason to use other fields other than the version

### ISSUE THREAD

**Issue by AsianIntel** [chapel-lang/chapel#17818]
Taken straight from the gitter chat,
It should be possible for Mason to be able to use the HEAD (among other options) of a git repository while building a project.

Options that could also maybe be supported:
i. Using the HEAD of a git repository
ii. Using the HEAD of a certain branch of a git repository
iii. Using the commit hash of a git repository
iv. Mix of 2 & 3
v. Local path to another mason project (I think you can do this already by specifying `compopts`) 

And as @ben-albrecht said, it shouldn't be possible for packages with such "git-specified" dependencies to be published to the registry.

**Comment by bmcdonald3** [comment]
Hi there! Just wanted to let you know that I have taken on this task and made some good progress, but am heading out on vacation for ~2 weeks and should have it complete shortly after that.

Would having the ability to specific a git repo and branch name be enough for you on this issue?

For example, would having the ability to write:
```
[dependencies]
myRepo = { git = <git-repo>, branch = <branch> }
```
where the repo would be pulled down and use the `<branch>` specified be enough, or are all of the things mentioned in this issue required for this to be useful to you? Thanks!

**Comment by AsianIntel** [comment]
Yes, that would be perfect and enough for this issue. Thank you so much for picking this up.

**Comment by bmcdonald3** [comment]
Hi @AsianIntel, just wanted to let you know that PR #20261 has now been merged and this functionality is now supported.

There is a section of the docs that outlines usage, but git dependencies can now be specified by adding a line to the `[dependencies]` section in your TOML file like this:
```
HelloWorld = { git = "https://github.com/bmcdonald3/HelloWorld", branch = "master" }
```
The branch is not required, but will assumed as master if none is provided.

Now, when running `mason build`, the git repo will be pulled down, the branch specified by the `branch` key will be checked out and then the repo will be included just like any other dependency.

Please let me know if this solves your problem and if there is anything else related to this that would be useful to you! Thank you.

**Comment by bradcray** [comment]
Thanks Ben for jumping into this this past month, and @AsianIntel : As Ben notes, please let us know whether you have the chance to try this and have any feedback on it.

**Comment by AsianIntel** [comment]
I apologize for the delay in my answer. I just recently moved halfway across the world and haven't been able to get to this. I will check it out in the next few days and thank you so much for adding this feature so quickly.
