### ISSUE TITLE
`make check` with CHPL_LLVM=system reports the wrong backend

### ISSUE THREAD

**Issue by PHHargrove** [chapel-lang/chapel#17823]
I am working from the `master` branch at 7e877bf8f9.  
When running `make check` with a build using `CHPL_LLVM=system` the logic in `util/test/checkChplInstall` appears to be using the out-of-date variable `$CHPL_LLVM_CODEGEN` leading to an incorrect report:
```
[Info] Compiling with C backend
```

**Comment by bradcray** [comment]
Tagging @mppf and @ronawho on this, simply because when I search for commits that mention CHPL_LLVM_CODEGEN, your names come up, and @daviditen for his recent work in enabling LLVM support by default.

**Comment by daviditen** [comment]
Yes, I believe @mppf's recent change that you mentioned fixed the bad output.

```
[Info] Compiling with CHPL_TARGET_COMPILER=llvm
```

**Comment by PHHargrove** [comment]
Fix confirmed.  Surveying the builds I have easily on hand, I see one of the following three as appropriate to the build:
```
[Info] Compiling with CHPL_TARGET_COMPILER=gnu

[Info] Compiling with CHPL_TARGET_COMPILER=clang

[Info] Compiling with CHPL_TARGET_COMPILER=llvm
```
Where the first two are both from `CHPL_LLVM=none` builds and the last from a `CHPL_LLVM=system` build.

**Comment by mppf** [comment]
thanks @PHHargrove and the behavior described in your last comment is what I would expect
