### ISSUE TITLE
gather-cray-prgenv-arguments.bash not installed on Cray XC

### ISSUE THREAD

**Issue by PHHargrove** [chapel-lang/chapel#17856]
I am seeing a new failure mode in our CI testing on on NERSC's Cray XC, Cori.  This was first seen with commit 7e877bf8f9 on May 26.  The previous CI run was a success about 2 weeks earlier on May 13 (the big gap due to an extended system maintenance).  I am not aware of anything relevant that changed in our CI scripts, but due to the NERSC center maintenance I cannot claim that nothing changed on the system.

From the output below, it looks to me like a key script is not getting copied by `make install`.  The `utils/config` dir has _some_ files, but not the one in the error messages.

```
$ chpl -o fft --ieee-float fft.chpl
sh: /[INSTALL_PREFIX]/util/config/gather-cray-prgenv-arguments.bash: No such file or directory
sh: /[INSTALL_PREFIX]/util/config/gather-cray-prgenv-arguments.bash: No such file or directory
internal error: LLV-CLA-TIL-3851 chpl version 1.25.0 pre-release (0)
Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug -- 
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.
```

**Comment by bradcray** [comment]
Thanks for reporting this, Paul.  `make install` is unfortunately not one of the things we use much ourselves internally, and our testing of it is not as watertight as I'd like, as cases like this show.

I'm tagging @mppf and @lydia-duncan on this, who've done the most with the `install.sh` script that determines what should be copied where for a `make install` command to see whether we could/should just copy all of `util/config/` over into the installation directory.

**Comment by mppf** [comment]
@bradcray - thanks for the suggestion. I've made PR #17858 to adjust install.sh to copy all of util/config.

**Comment by bradcray** [comment]
@PHHargrove : Thanks for reporting this.  This should get you past the immediate error you were hitting, but please let us know if that's not the case, or if there are any others lurking behind it.

**Comment by PHHargrove** [comment]
Today's runs on the XC system at NERSC confirms this is resolved for me.

**Comment by bradcray** [comment]
Thanks Paul!  Thanks Michael!
