### ISSUE TITLE
driver.cpp build warnings with Apple Clang 9 (fatal when CHPL_DEVELOPER=1)

### ISSUE THREAD

**Issue by PHHargrove** [chapel-lang/chapel#17860]
Since May 28  when commit e7de784 on master was tested, our nightly CI of GASNet + Chapel has been failing to compile `driver.cpp` with old Apple Xcode 9.2 compilers: `Apple LLVM version 9.0.0 (clang-900.0.39.2)` .   The previous test (successful) of this target was almost one week earlier: May 22 on commit 1f3bfc5 .

Our CI rotation has not attempted Xcode newer than 9.2 since this was first observed.  I will update this issue as soon as I have data for something newer (hopefully I get an off-cycle run in later today).  IFF this turns out to be an issue _only_ with this ancient compiler, I'll be fine if you want to simply disclaim support for it (I believe Apple already has).

I believe this is, in part, due the use of `-Werror` in our builds with `CHPL_COMM_DEBUG=1  CHPL_DEVELOPER=1`

```
In file included from driver.cpp:51:
In file included from ../next/include/chpl/queries/Context.h:23:
In file included from ../next/include/chpl/queries/Context-detail.h:23:
In file included from ../next/include/chpl/queries/ErrorMessage.h:23:
In file included from ../next/include/chpl/queries/Location.h:23:
In file included from ../next/include/chpl/queries/UniqueString.h:28:
../next/include/chpl/queries/UniqueString-detail.h:119:16: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
      return { nullptr };
               ^~~~~~~
               {      }
../next/include/chpl/queries/UniqueString-detail.h:129:16: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
      return { (const char*) val };
               ^~~~~~~~~~~~~~~~~
               {                }
../next/include/chpl/queries/UniqueString-detail.h:133:14: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
    return { s };
             ^
             {}
3 errors generated.
```

Full output from our first observation of this issue is available [here](https://gasnet-bugs.lbl.gov/upc_tests/showlog.php?date=2021-05-28&config=EX-sierra-smp-clang-pshm&opt=dbg&log=chapel#bottom), but is slightly muddled by `make -j4`.

**Comment by PHHargrove** [comment]
As I had hoped, there is no issue with `Apple LLVM version 10.0.0 (clang-1000.11.45.5)`, nor with `Apple clang version 12.0.5 (clang-1205.0.22.9)`.  
So I am fine with "too old -- won't fix" if that is your decision.

**Comment by bradcray** [comment]
@PHHargrove : Thanks for reporting this.
@leekillough : These errors all seem to be coming from lines that you touched last.  Will you take a look?  Thanks.  Tagging @mppf as well, as the reviewer.

**Comment by bradcray** [comment]
@PHHargrove: Thanks again for reporting this.  Please let us know if this doesn't resolve your build issue.

**Comment by PHHargrove** [comment]
I've rerun the impacted tester against your current master (commit b6aca69c) and can confirm this issue has been resolved.

**Comment by bradcray** [comment]
Great, thanks Paul!
