### ISSUE TITLE
Design: domain.isSubset(), domain.isSuper()

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#17907]
Background: these two methods compute the subset relationship between two domains, producing a compilation error for the cases when this operation is not supported or does not make sense.

Subset/containment, as well as intersection, operations on domains should be consistent with those on ranges, which are discussed in #17125.

### Proposal 1: replace with an overload `domain.contains(anotherDomain)`

With this proposal, `d1.isSubset(d2)` will be written as `d2.contains(d1)`; `d1.isSuper(d2)` will become `d1.contains(d2)`, assuming these are semantically equivalent.

Motivation: we prefer to have fewer functions with wider coverage, rather than a larger number of more-specialized functions. Also, the name "contains" is nice and sleek, whereas isSubset/isSuperset look clunky.

Q: Are there cases where `d1.isSubset(d2)` is more efficient to compute than `d2.contains(d1)` ? If so, is that a good reason to keep isSubset/isSuperset ?
A: T.B.D.

Q: Does it mean that we will not be able to have a promoted `domain.contains()` when applied to another domain?
A: Nope! thanks to Chapel's named actual arguments. If the formal for the single-index overload is `idx` and that for the domain overload is `dom`, `d1.contains(idx=d2)` results in promoting the former.

To consider also: distinguish between an operation that works on domains of similar representation vs. cross-representation? Ex. can an associative domain be a subset or superset of a rectangular domain? `contains` could be the efficient version and isSubset/isSuperset the general versions.

To consider also: distinguish between comparing just the high/low bounds vs. comparing the index sets, as in #17125.

### Proposal 2: rename to `isSubsetOf`, `isSupersetOf`

This proposal applies if we decide to keep isSubset/isSuper.

Given the expressions `d1.isSubset(d2)` and `d1.isSuper(d2)`, it is unclear what is the direction of containment that is being tested. The names isSubsetOf and isSupersetOf make it clear.

**Comment by bradcray** [comment]
I'm a fan of proposal 1, but am willing to be convinced otherwise.  In particular, Shreyas's comment about which domain was a superset/subset of which resonated with me a bit in the current scheme, whereas `contains()` seems short, sweet, and unambiguous.

**Comment by mppf** [comment]
I'd also like to go with Proposal 1, FWIW.

**Comment by bradcray** [comment]
We discussed this a bit more in the range review (part 2) today, and there seemed to be general consensus to use `.contains()` for both domains and ranges instead of `.isSubset()`, `.isSuper()` or the like.
