### ISSUE TITLE
Should we retire `domain.dim(d)`?

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#17917]
The considerations in this issue are dependent on the resolution of #17916.

This issue was raised during our domain module review on 6/10.

Proposal: remove `domain.dim(d)`. Instead, users will pick the i-th component from the tuple returned by `domain.dims`.

Arguments in favor of dropping `dim(d)` method:

* This will reduce the number of functions in domain's public interface.

Arguments in favor of keeping `dim(d)`:

* If `domain.dims()` remains parenthesized, then picking its i-th component will require two sets of parens, which is inelegant.

* It does not hurt anything to have `domain.dim()` in addition to `domain.dims`. If we remove it, we and users will need to change code, which is not worth it.

* When `domain.dims` requires building a tuple on the fly, it does not make sense to do that just to drop all of it except for one dimension.

* `dim(d)` reads nicely. Related - another singular vs. plural tension: `Locales` is nice when talking about the whole array; `Locale[i]` would be nicer when talking about a single locale. Thankfully, with dims, we can have both, unlike with the Locales array. [But don't we want to have uniformity here? -ed.]

We also had a proposal to allow paren-less vs. paren-ful overloads, ex.:
```chpl
proc domain.dims return <a tuple with all dimensions>;
proc domain.dims(d) return <the range for d-th dimension>;
```
This has been tried before without success, so we will not go there again.

**Comment by bradcray** [comment]
As on #17916, I prefer the status quo here.

> When domain.dims requires building a tuple on the fly, it does not make sense to do that just to drop all of it except for one dimension.

It was pointed out that this is a case where better compiler optimizations of tuples may help out but... it still feels to me like a case of a heavyweight baseline operation ("build a tuple, then tear it back down") when I want to do a simple query ("just tell me that one range please").

> This has been tried before without success, so we will not go there again.

Just to capture why, if I have:

```chapel
proc R.foo return [1, 2, 3];
proc R.foo(i: int) return i + 1;
```

then it's ambiguous whether `R.foo(i)` says "Call the paren-less foo and index into the result" or "Call into the paren-ful foo."  We could break the tie arbitrarily, but it's not clear that the subtlety is worth it (and, generally, we don't support overloading a variable/field and a function/method, where paren-less methods are essentially treated like variables/fields in the language).

**Comment by e-kayrakli** [comment]
My argument for retiring this was based on dropping parentheses from `dims()`. But if we aren't doing that (which seems to be where we are heading today), I think we should keep `dim(d)` as-is today.

**Comment by lydia-duncan** [comment]
Similarly, I view the resolution of #18085 as meaning that we consider this question resolved already
