### ISSUE TITLE
Should `domain.dims()` be paren-less?

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#17916]
This issue was raised during our domain module review on 6/10.

Arguments in favor of `dims` being paren-less:

* This follows our [library style guidelines](https://github.com/chapel-lang/chapel/blob/master/doc/rst/developer/bestPractices/StandardModuleStyle.rst) because:
  - it is a "property" of a domain
  - it could be (and is, in some cases) implemented as a field
  - its name does not start with "is" or "has"

Arguments in favor of keeping `dims` parenthesized:

* `dims()` requires some work to compute, so parens are OK.
* `dims()` is not ugly. We wouldn't want to impose on users the burden of switching to paren-less `dims`.

**Comment by bradcray** [comment]
> dims() is not ugly. We wouldn't want to impose on users the burden of switching to paren-less dims.

This is where I stand.  To me, the status quo isn't sufficiently distasteful or wrong to be worth the change (for us as implementers; for users to have to adapt to).

I also think supporting both `.dims` and `.dim(d)` seems more obviously redundant, and am not a big fan of writing `D.dims(i)` rather than `D.dim(i)`.  (but I also realize that in many cases, this is an unsolvable problem.  For example, I like saying `for loc in Locales` but hate saying `on Locales[i]` rather than `on Locale[i]`).

**Comment by e-kayrakli** [comment]
> - dims() requires some work to compute, so parens are OK.
> - dims() is not ugly. We wouldn't want to impose on users the burden of switching to paren-less dims.

I was feeling more for making `dims()` parenless. But after discussions, above two points resonate with me, and I am OK with the status quo.

**Comment by vasslitvinov** [comment]
To me personally it does not matter which way we go.
I am curious how we reconcile having paren-ful `dims` with the style guide.

**Comment by e-kayrakli** [comment]
While having the style guide is great, it is still in a very early stage and I don't think we should force ourselves to create an interface based on that document. Instead, we should try to make that document more precise, or edit it in a way that results in better user interfaces based on discussions such as this.

With that:

> Use parentheses-less methods only for returning properties that could be reasonably implemented as fields.

This statement from the style guide is too open for interpretation, maybe. I can argue that `dims` cannot be reasonably implemented as fields. In a block domain implementation, for example, I don't really feel the need to store a tuple of ranges. And feel that such a field would be redundant.

> Many paren-ful methods take some notable action. Try to make these methods method names be a verb. In particular, a method that modifies an argument in-place should be a verb.

If we were to follow this, we might consider `getDim` and or `getDims`.

**Comment by vasslitvinov** [comment]
> I can argue that dims cannot be reasonably implemented as fields.

This is why I don't like having a rule that defines something (in this case, parenful-ness) based on how something is implemented. Because it will leave users guessing how something is implemented. Which makes such a rule useless. "I think the rule tells me it is this way, however I have to check the documentation to make sure."

Ironically, despite people claiming that `dims` cannot be reasonably implemented as fields, the majority of our domain maps DO store a tuple of ranges in a field. (Aside: so `dims` could return a ref to a range tuple.) The one that computes it on the fly is PrivateDist, and there it is just a 1-tuple of a "simple range", i.e. two numbers (low,high). Which is very cheap to compute and does not, in itself, justify adding parentheses and `get` to the method name.

> I don't think we should force ourselves to create an interface based on that document.

I agree, we should not FORCE ourselves to do that. However, we created it with a purpose and it took some work to get there, right? In this case it is almost like we are ignoring it.

> Instead, we should try to make that document more precise, or edit it in a way that results in better user interfaces based on discussions such as this.

A very good point, thank you Engin. To me this means we should revisit the definition of a "property" in that document to make it easier for ourselves to decide.

**Comment by bradcray** [comment]
> If we were to follow this, we might consider getDim and or getDims.

I'd be open to `.dim(i)` and `.getDims()`, though I still worry that the level of work required to get there is out of proportion to the benefit / "problem" that currently exists.

> The majority of our domain maps DO store a tuple of ranges in a field.

Vass, when you say "DO store" do you mean directly or indirectly?  E.g., I don't think `BlockDom` stores a tuple of ranges as a field, but it stores `whole` which is a record that points to a class that stores such a tuple.

FWIW, personally, I don't feel as though `.dims()` or `.dim` should return a [const] reference any more than I think `.rank` should return a reference to an integer rather than just the integer value.  I think of these things as saying "tell me something about yourself and give me a value I can do whatever I want with", not "point me to where you're storing this information."

**Comment by lydia-duncan** [comment]
I tend to like `getX()` names.  I'd rather `dim` and `dims` be symmetrical (either both with `get` or both without).



> FWIW, personally, I don't feel as though `.dims()` or `.dim` should return a [const] reference any more than I think `.rank` should return a reference to an integer rather than just the integer value. I think of these things as saying "tell me something about yourself and give me a value I can do whatever I want with", not "point me to where you're storing this information."

I agree with this

**Comment by bradcray** [comment]
> I'd rather dim and dims be symmetrical (either both with get or both without).

FWIW, I don't go this far.  The ability to say `myDomain.dim(i)` seems natural, invaluable, and property-like to me.  `myDomain.getDim(i)` feels unnecessarily verbose / clunky.

**Comment by vasslitvinov** [comment]
> Vass, when you say "DO store" do you mean directly or indirectly? E.g., I don't think BlockDom stores a tuple of ranges as a field, but it stores whole which is a record that points to a class that stores such a tuple.

@bradcray indeed I meant indirectly - it takes hopping through a couple of pointers to get there. Still, `dims` sounds like a "property" to me for the purposes of the style guide.

Let me reiterate that by requesting to drop parens from `dims` I am pushing for consistence with our action in other cases even when that has come at a cost to users and ourselves. I do not view parenthesized dims() as a problem any more than a name with underscores where the style guide calls for camel case.

> I don't feel as though .dims() or .dim should return a [const] reference any more than I think .rank should return a reference to an integer rather than just the integer value. I think of these things as saying "tell me something about yourself and give me a value I can do whatever I want with", not "point me to where you're storing this information."

I don't have a strong preference and my suggestion of returning a const ref may be hard to implement in practice (because we still need to support the case of computing dims on the fly). Just for a record, my motivation is that returning by const ref will allow the creation of a copy to be done at the callsite instead of in the callee. Therefore in some cases the creation of a copy can be avoided altogether. This is the same reasoning as with our switch (some time ago) from handling in-intents at the callsite instead of in the callee.

**Comment by vasslitvinov** [comment]
Another argument for dropping parens in `dims()` is to make it uniform with the queries `.shape` and `.indices` on domains and other iterables (#19263). So if we were redoing it from scratch, it is obvious to me that we wouldn't use parens.

Now, we got a code base, with 80 uses of dims() in the modules and 136 uses in tests. I did not see any in Arkouda and I don't know about other user codes. Yet, I am personally unexcited about leaving future Chapel users with this exception because we have had it since before the style guide.

**Comment by lydia-duncan** [comment]
I'm sorta feeling like we're retreading old ground here.  #18085 resulted in adding these routines in their current form to arrays.  I think we felt fine with them in their current form, so I would lean towards closing this issue

**Comment by mppf** [comment]
I think we should adjust `.dims()` to be `.dims` to be more consistent with `.shape` which is very nearly the same operation (see table in #19263). AFAIK this is not a major burden to users since `.dims()` is used relatively infrequently.

**Comment by bradcray** [comment]
I still feel pretty much like I did [in my original comments](https://github.com/chapel-lang/chapel/issues/17916#issuecomment-860931312):  That we have major, impactful feature changes queued up that people use frequently which really ought to be addressed (e.g., changing stridable from a bool to an enum, changing the names of boundedness enums) and that this one falls way below my level of concern in terms of priorities or something that will eat at me five years from now.  Where Vass takes a "the style guide clearly says this should be paren-less" attitude, it's more on the borderline for me, and Engin's point about "maybe the style guide just needs to be refined" holds for me as well.

[This comment](https://github.com/chapel-lang/chapel/issues/17916#issuecomment-860931312) also still holds up for me as well—that having both `.dim()` and `.dims` without parens feels pretty silly from the perspective of `.dim(i)` and `.dims(i)` now being synonyms.  When would a user choose one over the other?  Whereas `.dim(i)` and `.dims()(i)` are more clearly distinguishable, and suggest to me that the latter should be rewritten as `.dim(i)`.

**Comment by vasslitvinov** [comment]
Given the above discussion, I consider this issue resolved to keeping the status quo. Closing.
