### ISSUE TITLE
Should most Reflection functions be methods instead?

### ISSUE THREAD

**Issue by dlongnecke-cray** [chapel-lang/chapel#17984]
Should most Reflection functions be methods instead?

Related: #7650

When reviewing the `Reflection` module, the question was raised as to
whether functions like `numFields()` would be better off as generic
methods instead.

Some functions in the Reflection module act on types, and others
(such as `getField`), act on instances of a type.

So instead of writing:

```chapel
use Reflection;

record r { var x = 0; }

proc test() {
  assert(numFields(r) == 1);
  assert(getFieldName(r, 0) == 'x');
  assert(getFieldIndex(r, 'x') == 0);
  assert(hasField(r, 'x'));
  var r1 = new r();
  assert(getField(r1, 0) == 0);
  getFieldRef(r1, 0) = 1;
  assert(getField(r1, 'x') == 1);
}
test();
```

A user would write:

```chapel
use Reflection;

record r { var x = 0; }

proc test() {
  assert(r.numFields() == 1);
  assert(r.getFieldName(0) == 'x');
  assert(r.getFieldIndex('x') == 0);
  assert(r.hasField('x'));
  var r1 = new r();
  assert(r1.getField(0) == 0);
  r1.getFieldRef(0) = 1;
  assert(r1.getField('x') == 1);
}
test();
```

If we decide to introduce value overloads of functions as suggested
 in #7650, the new overloads should arguably follow the same
precedent, so they would be generic type/instance methods as well.

**Comment by lydia-duncan** [comment]
I'm open to either leaving as is or making this change :)

**Comment by dlongnecke-cray** [comment]
A major question here is whether or not we should provide both type methods and value methods for functions like:

- numFields
- getFieldName
- getFieldIndex

For the `getField` and `getFieldRef` functions, it obviously only makes sense to have those be value methods that operate on an instance.

At first thought, my inclination would be to support both value and type overloads for these functions that formerly operated only on types. Reading back in my notes, it seems like @bradcray had some reservations about e.g. `numFields()` being a value method, mainly due to potential confusion between the static/dynamic type of the value.

I think that hesitation warrants some consideration, but it does mean that we would only have type methods and so would have to write something like `foo.type.numFields()` instead of `foo.numFields()`.

Personally, I tend to see something like `foo.numFields()` as shorthand for `foo.type.numFields()`, so I wouldn't be too bothered by having both value and type methods as long as we document that the `numFields()` is based off the static type of the receiver.

**Comment by lydia-duncan** [comment]
I believe we received negative feedback from users on this approach, so won't do it, closing

**Comment by bradcray** [comment]
I think that's true, where the concern was that it became another form of "special method" that invasively touched every type.  As interfaces come online, there may be a way to call into such special methods on a type via an interface, but without that, I don't think we can go down this road (without making users grumpy at us for ignoring them, anyway).
