### ISSUE TITLE
Port MiniBUDE to Chapel

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#17992]
Simon McIntosh-Smith's team at U/Bristol tends to do in-depth performance portability studies, focusing primarily on intra-node concerns, particularly in a GPU-enabled world.  [MiniBUDE](https://github.com/UoB-HPC/miniBUDE) is a computationally intensive mini-app that they have been using to evaluate performance portability—and to a certain extent, productivity—in various programming models such as OpenMP, OpenCL, OpenACC, SYCL, Kokkos, etc.  Their work was named "best paper" at ISC 2021 this year.

It would be interesting to do a Chapel port to see how we compare in terms of performance and productivity to other solutions, and to raise the chances that we might be included in such future studies.  This effort could focus on single-node / multi-core performance in the short-term, possibly with a side exploration of whether a multi-locale version would be trivial as well.  As our GPU support matures, this would be a good point of comparison to other GPU programming approaches.

**Comment by jabraham17** [comment]
This has been done: https://github.com/milthorpe/miniBUDE/tree/master/chapel. It is tested in our nightly tests

**Comment by bradcray** [comment]
> It is tested in our nightly tests

@jabraham17 : Is there more you can say (here) about how this nightly testing is done/where one would look for the results?

**Comment by jabraham17** [comment]
This is tested by the files in `test/gpu/native/studies/minibude`. The SKIPIF in that directory clones `https://github.com/milthorpe/miniBUDE.git` and applies any patches as needed. Then `test/gpu/native/studies/minibude/Bude.chpl` is a symlink into the cloned repo which allows the test system to find the repo. There are also `Bude.gpu-*` files which run this test in our nightly performance testing.

**Comment by bradcray** [comment]
Thanks!
