### ISSUE TITLE
Should Reflection functions prefixed with `get` drop the `get`?

### ISSUE THREAD

**Issue by dlongnecke-cray** [chapel-lang/chapel#18006]
Should Reflection functions prefixed with `get` drop the `get`?

This issue proposes dropping `get` prefixes from all functions in the
Reflection module.

So the following functions:

```chapel
use Reflection;

record r { var x = 0; }

proc test() {
  assert(getFieldName(r, 0) == 'x');
  assert(getFieldIndex(r, 'x') == 0);
  var r1 = new r();
  assert(getField(r1, 0) == 0);
  getFieldRef(r1, 0) = 1;
  assert(getField(r1, 'x') == 1);

  // These free functions query properties about the current scope.
  var currentLine = getLineNumber();
  var fileName = getFileName();
  var currentFn = getRoutineName();
  var currentMod = getModuleName();
}
```

Would become:

```chapel
proc test() {
  assert(fieldName(r, 0) == 'x');
  assert(fieldIndex(r, 'x') == 0);
  var r1 = new r();
  assert(field(r1, 0) == 0);
  fieldRef(r1, 0) = 1;
  assert(field(r1, 'x') == 1);

  // These free functions query properties about the current scope.
  var currentLine = lineNumber();
  var fileName = fileName();
  var currentFn = routineName();
  var currentMod = moduleName();
}
```

In #17984 the question is raised as to whether many of these functions
should be methods instead. If you'd be more likely to consider
dropping the `get` from these functions if they were methods instead,
consider commenting in #17984 as well (if this is your position, then
you'd probably like the `get` to stay for functions such as
`getLineNumber`).

**Comment by lydia-duncan** [comment]
My thoughts from the old issue so they are publicly visible:

I prefer the get form. It's more a personal preference than anything else, the most convincing argument I can come up with is "just because it seems implied to us as seasoned programmers, doesn't mean it will be obvious to new programmers" (but I recognize that's not super convincing)

> Is this something that documentation could potentially fix?

Depends. If someone knows about the function and doesn't know what it does, yes. If someone knows what they want to do and doesn't know what it's called, having the function name start with get might prevent them from dismissing it while looking for what they want (but they'll probably still find it anyways). Again, not a super convincing argument

**Comment by dlongnecke-cray** [comment]
My position here is that I think regardless of the outcome of #17984, we should drop the `get` from these functions.

Perhaps this owes to my time programming in Java, but I'm used to things being prefixed with `get` being implied to be "lightweight accessors". That is, they don't do much or any computation, and return a value.

Following that idea further, I don't think we want to imply the amount of computation that a method may perform. Only in exceptional cases (when computation is very slow), should we draw attention to that fact, and we can do so by prefixing the method with something (e.g. `compute`). Of course, this logic only holds if you buy into `get` being used to mark lightweight accessors.

A second reason is that when I tend to look up a method, I start with the concept/term itself and then follow the language naming convention to get the method name I would expect. @gbtitus gave a good example of `getpid()` in a previous thread. In my head, first I would have to think to myself "I need the PID", and then (owing to the POSIX naming convention) I would know to put `get` in front and end up searching for `getpid()`. Because the naming convention is kind of a "whole language property" (as far as the standard modules are concerned), as long as we are consistent about dropping `get` everywhere, I think it's reasonable to expect that users can end up at something like `field()` or `fieldName()` and then search for that in the documentation.

**Comment by dlongnecke-cray** [comment]
Bumping this - revisiting issues spawned from the Reflection module review.

Checking my notes it looks like we did have a vote at some point that was 9/3/1 in favor of dropping `get` from `getFieldName`, with 1 abstaining/do not care.

I imagine that we'll want to follow suit with the other field related functions prefixed with `get`? I am not 100% sure about functions like `getModuleName`, but I imagine we would drop `get` even there just for the sake of consistency.

**Comment by jabraham17** [comment]
Based on offline discussion (https://github.com/Cray/chapel-private/issues/5022#issuecomment-1631431593), we decided to not drop the `get` and to actually add it to `numFields` (so now `getNumFields`) for consistency.
