### ISSUE TITLE
Using List and Map of user classes in a Record fails to compile 

### ISSUE THREAD

**Issue by arezaii** [chapel-lang/chapel#18005]
### Summary of Problem

Using both `Map` and `List` in a `record`, without specifying deallocation strategy keywords `owned` or `shared` for user classes, results in a compilation error.

### Steps to Reproduce

**Source Code:**

```chapel
use List;
use Map;

class A {
  var msg:string;
}

class B {
  var name:string;
}

record R {
  var foo: list(A);
  var bar: map(string, B);
}
```

**Compile command:**
`chpl exampleCode.chpl`

**Output**
```shell
exampleCode.chpl:13: In method 'foo':
exampleCode.chpl:13: internal error: invalid attempt to get reference type [AST/primitive.cpp:235]
```

**Note**
Curiously, the code above compiles if either `map` or `list` is omitted, but not when both are present in the `record`. I would expect to see similar behavior to the above in either of these cases.

so changing the example code to either of the below examples will result in successful compilation:
```chapel
record R {
  var foo: A;
  var bar: map(string, B);
}
```
OR
```chapel
record R {
  var foo: list(A);
  var bar: B;
}
```

Alternatively, specifying a deallocation strategy for user classes `A` and `B` will successfully compile, e.g:
 ```chapel
record R {
  var foo: list(owned A);
  var bar: map(string, shared B);
}
```

### Configuration Information

- Output of `chpl --version`: `chpl version 1.25.0 pre-release (75a0eeea87)`
- Output of `$CHPL_HOME/util/printchplenv --anonymize`: 
```shell
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: clang
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: none *
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```shell
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: x86_64-apple-darwin20.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by mppf** [comment]
I think this is a case where the program shouldn't compile but we need a better error message.

With this version, I see the same (unhelpful) error message with both foo and bar fields or either one commented out.

``` chapel
use List;
use Map;

class A {
  var msg:string;
}

class B {
  var name:string;
}

record R {
  //var foo: list(A);
  var bar: map(string, B);
}

var x = new R();
writeln(x);
```

The problem here is that `A` and `B` refer to the classes with generic management. As a result, `list(A)` and `map(string, B)` are generic types. Which is probably not what you intended.

It might be possible or reasonable to make list/map issue an error if the element type is generic. However this might go against some partial instantiation scenarios (maybe I want to say `var x: list(SomeGenericType) = constructTheList;` as a way to be clearer about the type without specifying everything, say).

**Comment by arezaii** [comment]
today this provides a much nicer, helpful error message that helped me change the code to compile, so I will close this as it seems addressed.

**Comment by bradcray** [comment]
@arezaii : Would you consider filing a test locking this behavior in (if there isn't obviously one already)?

**Comment by arezaii** [comment]
I found the test `partial-no-q-warning` covers this type of problem (partial instantiation of a generic without a `?`) and demonstrates the warning/error that I get from this example now, but for completeness I added this example in https://github.com/chapel-lang/chapel/pull/25493
