### ISSUE TITLE
[Library stabilization] Should the BigInteger division methods throw an error when dividing by zero?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#18007]
In writing the documentation for `bigint.divQ()`, I noticed that the GMP documentation says:
> Division is undefined if the divisor is zero. Passing a zero divisor to the division or modulo functions (including the modular powering functions mpz_powm and mpz_powm_ui), will cause an intentional division by zero. This lets a program handle arithmetic exceptions in these functions the same way as for normal C int arithmetic.

Since the BigInteger module is intended to be more independent of the C API, I don't think it's appropriate to reference C in the documentation for these modules.  We've also received feedback in the past that libraries should not cause user programs to abruptly terminate.  Does that imply that our implementations for these functions should check for division by 0 and throw an error when it would happen?

**Comment by dlongnecke-cray** [comment]
I think I am fine with adding such checks as long as they can be disabled by `--fast`.

**Comment by bradcray** [comment]
As another model to look to, what does the C++ interface to GMP do?

> I think I am fine with adding such checks as long as they can be disabled by --fast. 

I think it is challenging to make a function throw vs. not-throw depending on whether or not `--fast` is used?  Or at least, I'm not sure we have a precedent for that in other situations, currently.  I'm imagining it would have to be done by providing two versions of the function with a where clause to select between them?

Note that an impact of taking such an approach is that if I developed a code using `--fast` and then gave it to you and you compiled it without `--fast`, you might have to insert try blocks that I'd never bothered inserting.

**Comment by dlongnecke-cray** [comment]
> I'm imagining it would have to be done by providing two versions of the function with a where clause to select between them?

Wouldn't we just say that the function will never throw if `--fast` is used? I'm not sure that we necessarily need to provide a second overload that removes the `throws` tag. It seems like that is one way to avoid the "I used `--fast` so don't have try blocks" problem.

Or perhaps your point is that if we always require try blocks, then we've negated the performance benefit of turning off the checks...

**Comment by bradcray** [comment]
Oh, I see, so statically speaking, the function always has `throws` on it, but dynamically it would never throw.  That's interesting, and I hadn't thought about that...

Would this actually make anything faster with `--fast`, though?  Isn't the overhead of a throwing function more that it may throw than whether or not it does throw?  Or have I got that wrong?  I guess it's not clear to me what the behavior and benefit would be if I used `--fast` in your proposal...?  (back to a halt?  nondeterministic behavior?)

**Comment by dlongnecke-cray** [comment]
Right, I think we'd end up with minor/no performance benefit because we've removed the branch for the div-by-zero throw but still have branches in the caller for the try/catch. We might be able to optimize away the branch for the try/catch if we can statically determine that a called function marked `throws` never throws, though (we may already do this today, not sure). However I'm guessing that the `divQ` method might throw for other reasons, in which case we can't do that.

**Comment by mppf** [comment]
I haven't read all of the discussion yet but my 2¢ is -- don't make it throw -- and make it do the same thing that happens for regular `int` division by 0. I'm not sure what exactly that does but I'm pretty sure it won't throw.

**Comment by dlongnecke-cray** [comment]
I mistakenly thought that the `divQ` was already throwing. If it is not, I think we should just mirror the behavior for normal int division (including `--no-div-by-zero-checks`).

**Comment by lydia-duncan** [comment]
Here's the code from ChapelBase's implementation of normal int division:
```chapel
  inline operator /(a: int(?w), b: int(w)) {
    if (chpl_checkDivByZero) then
      if b == 0 then
        halt("Attempt to divide by zero");
    return __primitive("/", a, b);
  }
```
So, that's a halt and an explicit computation added by Chapel - there's definitely something that needs to be done so that the bigint division methods generate this error message appropriately, but you're right that it isn't a thrown error.

**Comment by lydia-duncan** [comment]
In the module re-review, we were strongly in favor of adding the same check to the division methods (and either adding that check to the bigint operator or having it call the division method and thus get the same behavior for free)
