### ISSUE TITLE
Proposed / potential changes to `c_ptrTo()`

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#18016]
A few unrelated changes have been proposed for discussion to `c_ptrTo()` that I'm lumping together for convenience:

* Currently `c_ptrTo()` is special-cased for arrays that are contiguous in memory to return a pointer to the array's buffer.  This is a bit special/confusing and prevents the ability to take a pointer to the array descriptor itself for low-level programmers who want to do that.  It's also a little weird in that an array of arrays would return a pointer to an array descriptor (so it's not as though we've completely hidden the array descriptors away by doing this).  The proposal is to deprecate this behavior and support an `array.c_buffer()` method or the like to get at the array's elements.  Thus `c_ptrTo()` on arrays would begin to return a pointer to the array descriptor instead.  Vote :+1: if you like this idea, :-1: if not.

* Is `c_ptrTo()` the right name for this?  In describing it as "similar to `&`" the phrase "`c_addressOf()` or `c_addrOf()`" like more direct translations.  Vote :heart: if you prefer the status quo, :tada: if you prefer `c_addressOf()`, 🚀  if you like `c_addrOf()`
  * arguments in favor of :heart:
    * shorter and sweeter
    * doesn't require any changes to current code
    * returns a `c_ptr()`, so mnemonic in that sense
  * arguments in favor of :tada: / :rocket: 
    * closer match to C's description of operator

* the current formal argument name in the routine is `x` which seems very nondescriptive.  Should we give it a better name?  If so, what?

**Comment by mppf** [comment]
> the current formal argument name in the routine is x which seems very nondescriptive. Should we give it a better name? If so, what?

Maybe we could name it `_arg` (per the proposal in #11069) so it is not part of the interface for this function. I think `arg`, `value`, `memory` are all reasonable alternatives

**Comment by gbtitus** [comment]
I voted :tada: for `c_addressOf()` both because mnemonically "getting the address of" is what you're doing, and because it should be maximally obvious in the code that you're now entering into the dangerous world of C pointers.

> the current formal argument name in the routine is x which seems very nondescriptive. Should we give it a better name? If so, what?

`thing` (seriously)

**Comment by bradcray** [comment]
> Maybe we could name it _arg (per the proposal in #11069) so it is not part of the interface for this function.

Is the goal here to:
* disable pass-by-keyword
* squash the formal name from showing up in the documentation
* give us the opportunity to keep renaming the formal in the future (because we don't trust that we'll choose a good one now)
* something else?

**Comment by mppf** [comment]
I was thinking of

> give us the opportunity to keep renaming the formal in the future (because we don't trust that we'll choose a good one now)

but I think you are getting at the fact that we'd probably like a good name for documentation purposes (it's just if we use `_arg` then the name doesn't have to impact module stability).

**Comment by bradcray** [comment]
Mostly, I hadn't thought about the concept that a formal argument with the "my name is inconsequential" bit set (however we specify it) might be squashed out of the documentation before this, such that the documentation might render it as something like:

```chapel
proc c_ptrTo( : ?t) { ... }
```

or:

```chapel
proc c_ptrTo(_: ?t) { ... }  // where the user couldn't write `_=x`
```

and I find I have mixed feelings about it.  It seems like it makes the documentation less clear (e.g., the routine's chpldoc description would need to be careful to say things like "the first argument" rather than "`_arg`"); but also it's nice that it doesn't tell you the name of this argument whose name you shouldn't rely on (because you have a harder time trying to rely on it if you don't know its name).  Anyway, my quick decision would be to document such arguments.

And then if the argument name did show up in the docs as `proc c_ptrTo(_arg: ?t) { ... }`, it feels like it's a less compelling use case since we've still had to choose a user-visible name for the argument and it's not a case where we're likely to have overrides/overloads occurring.  I.e., maybe we're putting off a decision that shouldn't be all that hard to "just make" for poor reasons.

**Comment by npadmana** [comment]
Just a user perspective here (and an explanation of my downvote) - I find myself using the `c_ptrTo(array)` option very frequently when needing to interact with C libraries that expect an array as input, and I very much appreciated the shorter version when it got introduced. I used to write c_ptrTo(array.first) which got tiresome quickly. So returning a pointer to the array descriptor would break code in a fairly large number of places.

**Comment by npadmana** [comment]
I should add that I would worry that this would silently break code (since in many cases, the C type might be void *, and so it would happily gobble up a pointer to the array descriptor). If we did the change, I'd hope we could add in a compiler warning that would detect any `c_ptrTo(array)` and emit a warning (by default in the beginning) that this might not be what one would want to do.

**Comment by mppf** [comment]
@npadmana - I'm not sure if it came through clearly enough but the proposal is that we'd provide the same functionality with `array.c_buffer()` and we'd have a deprecation from `c_ptrTo(array)` for a release to help you (and others) adapt. It didn't sound like you had an objection to `array.c_buffer()` on its own - did you?

> I should add that I would worry that this would silently break code (since in many cases, the C type might be void *, and so it would happily gobble up a pointer to the array descriptor).

We'd be deprecating it, so any code using `c_ptrTo(array)` would get a deprecation warning for a release, and the fix would be to change to `array.c_buffer()`. Once that change is made, there won't be any silent breaking of code, and we will be keeping `array.c_buffer()` as a stable feature.

I'm not entirely convinced that people in the future will write `c_ptrTo(array)` thinking it's a pointer to the first array element (for one thing we'll be adjusting the documentation to indicate not to do that). But if you feel differently about that please say more.

**Comment by npadmana** [comment]
I got confused by the comment that `c_ptrTo(array)` would start to return a pointer to an array descriptor, and wasn't sure exactly how the current behavior was going to be deprecated. 

No, I don't have a fundamental objection to `array.c_buffer()` or something similar. That said, I don't really trip over `c_ptrTo(array)`, in part because I think of the array as the data, not the descriptor to the data. And I personally prefer the "operator" nature of `c_ptrTo()` over a method call, but that could just be the similarity to using `&` in C. 

All of this could be just years of conditioning. So my noise here could just be a resistance to change :-).

**Comment by bradcray** [comment]
Though I felt pretty on-board with the proposed change to `c_ptrTo(array)` when posting this issue, Nikhil's comment here resonates with me:

>  don't really trip over c_ptrTo(array), in part because I think of the array as the data, not the descriptor to the data.

because when talking to users and defining the language, we have typically talked about the array's value being "the collection of elements it represents" rather than anything relating to the descriptor.  For example `const A: [1..n] real;` doesn't say that the array descriptor can't be modified, it says that the array elements can't be.  That suggests that the status quo may be more appropriate for the typical end-user and that the reason many of us on the development team balk at it is that we "know too much" about how arrays work under the hood.  I think that's worth stewing on a bit more before proceeding.

Even with that interpretation, though, I still worry a bit that in a case like this, we're inconsistent today:

```
var A: [1..n] [1..m] real;
```

Specifically, something like `c_ptrTo(A)` will essentially return a pointer to an array descriptor (the one representing `A[1]`'s `[1..m] real;` array, where the "an array is its elements" interpretation might suggest this is inconsistent.  That said, I'm not sure what it should point to given that all of A's elements aren't contiguous in memory.  It could arbitrarily point to `A[1][1]`.  Or it could be an error to apply `c_ptrTo()` to an array whose elements were arrays (similar to how I think it should generate an error if the array's elements aren't contiguous in memory for other reasons).

**Comment by npadmana** [comment]
A slightly more detailed argument here - consider a C function

 ```
cfunc(int* scalar, double* array)
``` 

From an end-user's perspective, I like the simplicity and uniformity that writing
 ```
cfunc(c_ptrTo(chplScalar), c_ptrTo(chplArray))
``` 
has, as compared to 
```
cfunc(c_ptrTo(chplScalar), chplArray.c_buffer)
``` 
or even the previous 
```
cfunc(c_ptrTo(chplScalar), c_ptrTo(chplArray.first))
``` 

I say this fully understanding the low-level asymmetry between the scalar and array case, and that this is largely an artifact of how C defined arrays. My argument here would be that `c_ptrTo` is in the language to facilitate interacting with C APIs, and that the most common case (based admittedly on a sample of one) is that one would want to pass in the array data and not the Chapel descriptor. Ultimately, this is a preference for the higher level symmetry at the cost of a lower level asymmetry in how `c_ptrTo` behaves. And as Brad noted, I think the lower level asymmetry highlights an implementation detail that should be hidden from the end-user. For instance, if Chapel chose to box all its integers, I would still want to write `c_ptrTo(int)` when calling a C function.

Brad's case above is an interesting one and resonates with me about guarantees of contiguity of storage. I would be happy if `c_ptrTo` didn't work if a type couldn't indicate that its data was not contiguous.

**Comment by bradcray** [comment]
I think an extension of Nikhil's argument would be that `c_ptrTo()`, when applied to `string` and `bytes` types in Chapel should return a pointer to the buffer used to implement the types.

**Comment by mppf** [comment]
> This is a bit special/confusing and prevents the ability to take a pointer to the array descriptor itself for low-level programmers who want to do that.

Arguably we just need a different low-level-pointer facility that is not focused on C interoperability and then using that would have a clear behavior here. (Of course we can worry about array -> low level pointer -> c pointer having a confusing result, though).

**Comment by king-11** [comment]
>I think an extension of Nikhil's argument would be that c_ptrTo(), when applied to string and bytes types in Chapel should return a pointer to the buffer used to implement the types.

Would we require that currently, it creates malformed data if you create `c_ptrTo(bytes)` but we already have `bytes.c_str()` similarly for strings too which necessarily return the pointer to the buffer.

**Comment by mppf** [comment]
> A slightly more detailed argument here - consider a C function
> 
>  ```
> cfunc(int* scalar, double* array)
> ``` 
> 
> From an end-user's perspective, I like the simplicity and uniformity that writing
>  ```
> cfunc(c_ptrTo(chplScalar), c_ptrTo(chplArray))
> ``` 

Yet, I don't think this is the best way to write it. If we take the time to write our own version of the `extern proc` for this function (and @npadmana I know you use `extern` blocks and as a result this is not necessarily an easy task) then it would be better to expose `cfunc` as `extern proc cfunc(ref scalar: int, array: c_ptr(c_double))`. That makes it clear that only `*scalar` is used in the function, and not, say, `scalar[100]`. (Unfortunately, it's not really possible to make this determination in an automated way with c2chapel or with extern blocks because the information isn't in the C type system. But, these tools could create multiple overloads - e.g. it could generate both `extern proc cfunc(ref scalar: int, array: c_ptr(c_double))` and `extern proc cfunc(scalar: c_ptr(int), array: c_ptr(c_double))` - but there might be challenges in doing that).

So, while I don't think my counter-argument is super strong (because it's not yet practical to apply as a best practice for a big library when using c2chapel / extern blocks) I'm still thinking I'd rather have consistency in behavior for `c_ptrTo`.

But if we can agree that both behaviors are needed, then this discussion is really about what they are named. E.g.
 1. `c_ptrTo(array)` ->  pointer to first element but `ll_ptrTo(array)` (or something) -> pointer to array record vs
 2. `array.c_buffer()` -> pointer to first element but `c_ptrTo(array)` -> pointer to array record vs
 3. `c_ptrToElt(array)` -> pointer to first element but `c_ptrTo(array)` -> pointer to array record
 
Note that the solutions where we make a change don't necessarily mean that pointer-to-scalar and pointer-to-array in @npadmana's example above are different. For example, if we take the last example from the bullets above, we can define `c_ptrToElt(scalar)` to just return the pointer to the scalar value for any non-array type (and also `c_ptrToElt(mybytes)` would return the same pointer as `mybytes.c_str()`).

Now, it's my opinion that it's better for `c_ptrTo` to have the low level behavior, and to have something with a different name (e.g. `c_ptrToElt`) for the higher level behavior. However I'm not quite sure why it is I think that. I think it has to do with the way that I expect I can sortof project Chapel types into C. (Another reason - in option 3., `c_ptrTo` is arguably simpler than `c_ptrToElt` - which can be described as a combination; in contrast in option 1., it is hard to think of good names for `ll_ptrTo` since it is subtracting a feature from `c_ptrTo`).

Anyway, I would be interested to know what others think about this question about what they should be named, supposing we support both.

**Comment by npadmana** [comment]
> Yet, I don't think this is the best way to write it. If we take the time to write our own version of the extern proc for this function (and @npadmana I know you use extern blocks and as a result this is not necessarily an easy task) then it would be better to expose cfunc as extern proc cfunc(ref scalar: int, array: c_ptr(c_double)). That makes it clear that only *scalar is used in the function, and not, say, scalar[100]. (Unfortunately, it's not really possible to make this determination in an automated way with c2chapel or with extern blocks because the information isn't in the C type system. But, these tools could create multiple overloads - e.g. it could generate both extern proc cfunc(ref scalar: int, array: c_ptr(c_double)) and extern proc cfunc(scalar: c_ptr(int), array: c_ptr(c_double)) - but there might be challenges in doing that).

I have a slightly different perspective here. I agree with @mppf that the way I called into C was not the "best" way from a Chapel perspective. However, I think of Chapel interfaces to C code as being a two-step process. The first is a literal translation of the C API into Chapel (C type system warts and all), with the second step being a more Chapel-rrific wrapper. The literal translation means that I can simply refer to the C documentation for how to call functions, and while it may be "ugly", it requires very little thought on my end. That's one of the reasons I've appreciated `extern` blocks not trying to be clever with converting pointer arguments to `refs` (`c2chapel` tried to do this with two versions, but the challenge quickly becomes distinguishing between when a pointer is an array, versus just a scalar). 

If you buy the above argument, then I think it is nice from a user's perspective to have a common function that will convert a type into an appropriate (where possible) C pointer -- i.e. `c_ptrTo(array)` returning a pointer to the first element etc. Of course, it doesn't need to be called `c_ptrTo` (I secretly hope for a unary form of `*`, just as in C).

**Comment by mppf** [comment]
Right, the above explanation makes sense to me.

On this point -

> Of course, it doesn't need to be called `c_ptrTo` (I secretly hope for a unary form of `*`, just as in C). 

I think our `c_ptrTo` is more similar to `&` in C, but `c_ptr()` on a type would translate to `*` in C.

How do you feel about `c_ptrToElt` and `c_ptrTo` as proposed above? Does it seem reasonable to have 2 different functions here? Are there other names you would like better?

**Comment by npadmana** [comment]
> I think our c_ptrTo is more similar to & in C, but c_ptr() on a type would translate to * in C.

Doh! Yes, of course... 

I do like the idea of two forms, although I might suggest that the names be sufficiently distinct to avoid confusion. For instance, `addressOf` or `c_addressOf` as contrasted to `c_ptrTo` feels better than `c_ptrToElt` vs `c_ptrTo`. I don't have a strong preference on the particular name, although selfishly, I'd prefer if `c_ptrTo` maintained its current behavior.

**Comment by bradcray** [comment]
Just a quick note here that, assuming we support both things, I think the more common case for typical users will be to want a pointer to the array's first element / string's first byte.  So that would suggest choosing names that streamline common cases for such users rather than optimizing for what I'd call the more developer-oriented perspective ("no, I really want a pointer to Chapel's internal meta-data").  That might suggest choosing the simpler / shorter name to have the current behavior (which _might_ suggest keeping `c_ptrTo()` as is, and adding something different for developers).

**Comment by bradcray** [comment]
I just re-read this issue top to bottom and find Nikhil's last comment, or at least my interpretation of it, to be pretty appealing:

* `c_addressOf()` — a new routine, heavily similar to `&` including returning a pointer to an array descriptor when applied to `A: [1..10] real`, to the record representing a string or bytes in those cases, etc.  Potentially used primarily by Chapel developers and power users.
* `c_ptrTo()` — more Chapeltastic routine that gives a pointer to the "logical value" of the thing in Chapel in a way that is designed to be most useful to C (e.g., the array's buffer for an array with a single contiguous buffer; the buffer storing the data of a `string`/`bytes`).  For scalar values, would be equivalent to `c_addressOf()`.

Advantages of this approach:
* Doesn't break existing code (...at least as much?)
* Makes the C-like behavior use the verbalization that I think we'd typically use when reading &x in C
* Keeps the Chapeltastic version (which I expect to be the common case) shorter-and-sweeter
* Potentially lets us retire `c_str()` on strings (related to https://github.com/chapel-lang/chapel/issues/18266)

Disadvantages:
[you tell me]

Also, with respect to the c_ptrTo() on an array-of-arrays case I mentioned above:  Belatedly, it occurs to me that we could just refuse to support `c_ptrTo()` in this case on the argument that it doesn't have an obvious C interpretation / that the array data is not consecutive in memory (at least in today's implementation / domain maps).  And if we had `c_addressOf()`, we'd still have a way to get a pointer to the inner-array descriptor for someone who really wanted it.

**Comment by bradcray** [comment]
In a meeting today, we discussed the proposal just above and there were no general disagreements with proceeding with it, where the preferred choice for the "literally point to this variable" approach was `c_addrOf()` (rather than `c_addressOf()`; `c_literalPtrTo()` was also proposed as an option.

Other notes:
* it was pointed out that these routines are not particularly self-descriptive in terms of saying what they do in the cases where the behavior differs.  From Nikhil's comments above, I took it that he preferred a short form of this (since he already has to type more than just `&`) and gave my opinion that not every routine needs to say everything about itself in its name—that we can rely on documentation and tool tips for that sort of thing
* a question came up about how a user writing their own data structure could opt into supporting `c_ptrTo()` for it, if desired (say, I'm creating the Chapel version of the C++ vector type).  Michael proposed that a special method could be used to provide the implementation for a given user type, and that our standalone `c_ptrTo()` routine could call into that.
* a question came up over whether, for a user-defined type that had not opted into this behavior, applying `c_ptrTo()` to it should not be supported or should fall back to `c_addrOf()`.  From the opinions I heard, it sounded like falling back to `c_addrOf()` would probably be preferred, but that should potentially be double-checked before we proceed with this.

**Comment by riftEmber** [comment]
Getting around to implementing this. Compiling all the decisions in one place for approval before proceeding:

- `c_addrOf()` will return a pointer to the beginning of the variable in memory (array descriptor etc). This is the current behavior of `c_ptrTo()` in non-specialized cases.
- `c_ptrTo()` will return a pointer to the data buffer of the supplied variable. It will support this behavior for arrays, `string`, and `bytes`. If given a variable of another type, it will fall back to `c_addrOf()`.
- The `c_str()` methods on `string` and `bytes` will be deprecated, with deprecation message suggesting use of the revamped `c_ptrTo()` function.
  - For now, `c_ptrTo()` on a `string` or `bytes` will return a `c_string`. After https://github.com/chapel-lang/chapel/issues/14215 is resolved and `c_string` has a robust replacement, `c_ptrTo()` should return that instead in this case.
- Create a post-2.0 task to enable user types to provide an implementation of a `c_ptrTo()` special-case for the type (as suggested above), but do nothing on this now.

Please let me know if any of this implementation proposal is objectionable; I will implement it Soon:tm: depending on if there are any changes suggested.

**Comment by bradcray** [comment]
The first two bullets match my understanding.  A minor point, but note that for an array whose elements aren't all stored contiguously in memory (like a block-distributed array), `c_ptrTo()` should return a compile-time error saying something like how it's not possible to return a single pointer to the array's elements.  I'd need to refresh my memory to remember what the current best way to determine this is.

My preference would definitely be to have `c_ptrTo()` on `string` and `bytes` return something like `c_ptr(char)` and `c_ptr(uint(8))` respectively.  Specifically, if we return `c_string`, that feels like something we'd need to fix before 2.0 in order to stabilize it.  Is the challenge to doing so today that it won't work with the C back-end due to the `const char*` issue (#14214)?

I'd also like to make sure @e-kayrakli is in agreement on the deprecation of `c_str()` methods since I think he's most familiar with those.

**Comment by riftEmber** [comment]
My leaning towards `c_string` was just because that's the current behavior. I think the types you suggested would be more correct modulo the constness issue you linked. I don't understand what the repercussions would be of returning a `c_ptr(char)`.

**Comment by e-kayrakli** [comment]
> My preference would definitely be to have c_ptrTo() on string and bytes return something like c_ptr(char) and c_ptr(uint(8)) respectively. Specifically, if we return c_string, that feels like something we'd need to fix before 2.0 in order to stabilize it. Is the challenge to doing so today that it won't work with the C back-end due to the const char* issue (https://github.com/chapel-lang/chapel/issues/14214)?

That would be my guess. i.e. can you pass `c_ptrTo(myString)` to an extern C function that expects a `const char *` if it returned `c_ptr(c_char)`?

> I'd also like to make sure @e-kayrakli is in agreement on the deprecation of c_str() methods since I think he's most familiar with those.

I am definitely game.

**Comment by riftEmber** [comment]
I realize we also seem to not have a final decision on what the argument name should be, so here's a quick poll.
- 🦑 : x (current)
- 🐙 : thing
- 🐟 : _arg (reasoning discussed starting in https://github.com/chapel-lang/chapel/issues/18016#issuecomment-872271619)
- 🦀 : arg
- 🦭 : value
- 🧜 : memory

**Comment by riftEmber** [comment]
It looks like we have consensus on proposed changes besides the question of what to return as a pointer to a `string` -- a const pointer to `c_char` would be ideal. I will look into [const pointers](https://github.com/chapel-lang/chapel/issues/14214) first and revisit this.

**Comment by riftEmber** [comment]
As for the name of the argument to `c_ptrTo`, internal poll results were:

- 7 for `x` (leave as-is) (counting myself)
- 1 for `value`
- 2 for `expr`

Unless anyone has strong feelings against it, I will go ahead and leave the name `x` intact.

**Comment by bradcray** [comment]
@riftEmber : While reviewing Scott's blog posts today, I tried writing a cute idiom in which I took `c_ptrTo()` a `k*type` tuple, but rather than getting a `c_ptrTo(type)` as I was hoping, I got a `c_ptrTo(k*type)` which wasn't very useful since C doesn't know about our tuples.  I suspect that this is just a case that hasn't been tried before, but wanted to mention it since you're working in this area.  I suspect the quick fix would be to write an overload of c_ptrTo() that takes a homog. tuple, then returns `c_ptrTo(theTupleArg(0))`.

**Comment by mppf** [comment]
@bradcray - but, our tuples are not necessarily stored in contiguous memory, if the tuple is a stack local variable. Does `c_ptrTo(myTuple)` meaning `c_ptrTo(myTuple(0))` come to close to problems in that area? FWIW, my expectation has been that we will ask people to use `c_array` when they need such interoperability.

**Comment by bradcray** [comment]
> but, our tuples are not necessarily stored in contiguous memory, if the tuple is a stack local variable. 

They're not?  When?  Are you think of cases like tuples of arrays or tuples of classes?  If so, I'd ammend my previous comment to say something like "homogeneous tuples of sufficiently POD type"

I think a significant downside to requiring users to use `c_array()` for such cases is that it forces them to use an interoperability type when arguably all they wanted to do was use a Chapel type and pass a pointer to its buffer of memory off to C.

**Comment by riftEmber** [comment]
Another potential special-case for differing behavior between `c_ptrTo` and `c_addrOf` is class types, for which a user might desire either a pointer to the pointer to the object, or a pointer to the object on heap itself. Currently `c_ptrTo` gives a pointer to the pointer, and the way to get a pointer to the object is by casting to `c_void_ptr`. It would make a lot of sense to me if `c_ptrTo` gave a pointer to the object, and `c_addrOf` gave a pointer to the pointer.

I'm suggesting this based on discussion at [this discourse thread](https://chapel.discourse.group/t/1-29-0-cannot-deref-a-c-ptrto-unmanaged-class-instance-comm-none-assertion-node-0-failed/19696), particularly the distinction made between these two things in [this reply](https://chapel.discourse.group/t/1-29-0-cannot-deref-a-c-ptrto-unmanaged-class-instance-comm-none-assertion-node-0-failed/19696/6).

**Comment by bradcray** [comment]
> I propose that we make c_ptrTo return a pointer to the object, and c_addrOf return a pointer to the pointer.

This matches my intuition, and feels congruent to other cases like arrays to me.

**Comment by bradcray** [comment]
> If I generate the C code, I can see that the later tuple elements aren't even code generated.

I'm feeling shocked and confused by this...  I guess we do some form of tuple->scalar optimization that I'd forgotten about?  (followed by dead-code elimination?).  Doesn't feel right to me...

**Comment by riftEmber** [comment]
The proposed changes as summarized in https://github.com/chapel-lang/chapel/issues/18016#issuecomment-1387583577 have been implemented by @jeremiah-corrado. The [CTypes design subteam](https://github.com/Cray/chapel-private/issues/4824) decided to add another special case for `c_ptrTo` for class types as described in https://github.com/chapel-lang/chapel/issues/18016#issuecomment-1448790729. This is with the added clarification that `c_addrOf` will not always return a pointer to the heap pointer, but just a pointer to whatever the representation of the class type on the stack is (which is a record for `owned`/`shared`). This new special case has yet to be implemented.

**Comment by riftEmber** [comment]
With https://github.com/chapel-lang/chapel/pull/22367 merged all the settled on `c_ptrTo` changes are implemented.
