### ISSUE TITLE
Should we unify C type naming convention?  How?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#18012]
Currently most C types that our modules define for the purposes of interoperability use type names like `c_int`, `c_float`, etc.  However `ssize_t` and `size_t` are outliers.  In discussions, we have generally shown interest in unifying these to a single scheme, where the two main proposed courses of action are:

* unify on the `c_` prefix and change `ssize_t` and `size_t` to `c_ssize_t` and `c_size_t` for consistency (please vote this option with :+1:)
* drop the `c_` prefix and put these symbols into a module named `C` such that one would type things like `C.int` and `C.size_t` rather than `c_int` and `c_size_t` (please vote this option with :heart:)
* something else?

Arguments in favor of :+1:
* though `c_` is not particularly Chapeltastic, these identifiers are C identifiers, and `c_` is a reasonable naming scheme for C identifiers
* the use of the somewhat ugly / clunky `c_` prefix serves as a disincentive for using these broadly in Chapel code, where the preferred approach would be to keep them constrained to C interop situations, at which point they should be translated to/from Chapel types
* it clearly marks them for what they are with no way around it

Arguments in favor of :heart:
* it is more Chapeltastic in terms of naming by avoiding underscores (apart from `ssize_t` and `size_t`, I suppose)
* it leverages Chapel's modules' namespaces rather than naming conventions to distinguish these symbols

**Comment by bradcray** [comment]
I tried to keep it out of the OP largely, but I feel pretty strongly opposed to :heart: because I feel like it tries to make things more Chapeltastic by creating or requiring a bunch of special cases (which makes the overall proposal seem less Chapeltastic to me).  Specifically, my summary of last week's conversation was something like:

me: "`int` is a reserved word in Chapel, so we'd have to do something special to support it as a symbol in this module."

me: "if I `use C;` rather than `import C;`, and then just type `int` it becomes ambiguous which I'm referring to
response: We could disallow `use C;`
rebuttal: A user could still `import C.int;` to get the same effect
possible response: We could outlaw that as well

Beyond that, I'm not all that convinced that `C.int` is more attractive to type or read than `c_int` (but maybe I've just become too used to the latter).

**Comment by mppf** [comment]
While I brought up the "Put it all in a module called C proposal" and I like that in some ways, I can see the downsides and I'm not particularly opposed to the current names either. As a result I'm currently abstaining from the poll.

**Comment by bradcray** [comment]
I think we've now agreed that `c_` is a reasonable prefix for the C types and applied it more consistently to our major C type aliases, as defined in the new 'CTypes' module, so I'm closing this.
