### ISSUE TITLE
Retire `is_c_nil()`?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#18015]
This issue proposes we retire `is_c_nil(myPtr)` on the argument that it's just as easy and clear (if not moreso) to write `myPtr == c_nil` (or whatever we call `c_nil`—see issue #18014).  In discussions, this proposal was largely reviewed positively by the team, so this issue is here to see if there are any objections before proceeding.

**Comment by lydia-duncan** [comment]
This has been deprecated, closing
