### ISSUE TITLE
C Types: Bring into a single module, but where?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#18013]
Currently in Chapel's standard modules, what we might think of as core C types are scattered across different modules:
* `c_int` is defined in `SysCTypes`
* `c_float` is defined in `SysBasic`
* `c_ptr` is defined in `CPtr`

The net result is that things are spread out in a nonintuitive way and several modules need to be used if a variety of C types need to be used.

There is a general consensus on the team to bring these together into a single module.  The main questions are what that module should be called and what it should contain.  Leading contenders are:

## a `CTypes` module
This would define everything in `SysCTypes` today plus `c_float`, `c_double`, `c_ptr()`, `c_void_ptr` (assuming it doesn't go away with #18011), and `c_array`

## a `CInterop` module (potentially using a different name)
This would define everything in the previous proposal plus other capabilities that felt closely related, like potentially those currently defined in `CPtr`:  `c_*alloc`, `c_mem*`, etc.

## in a submodule of a `C` module hierarchy
For example, imagine that `C.Types` contains everything in the `CTypes` proposal above, and that `CMemory` contains everything else in the `CInterop` proposal

## in a module named `C`, in which the `c_` prefixes would be dropped
The idea here would be that one could say `C.int` or `C.ptr` rather than `c_int` or `c_ptr` when using a fully qualified style.  See issue #18012 for more on this idea.

## something else?

I'm not putting voting options on this issue (yet) because I'd like to see more discussion on it first and to see how #18012 evolves.

**Comment by bradcray** [comment]
I currently have mixed feelings about the first three options.  The fourth I don't like for reasons expressed on #18102.

* the first seems simple and clean and nearly faultless other than the fact that it leaves an open question about "where to put that other stuff?"
* the second seems a bit attractive in the "put all the C stuff into a single module" sense, but it's not clear to me precisely what "all the C stuff" entails or what the name should be.
  * For example, while `c_memset()` is a C routine, I don't think of it as being particularly related to interop, so putting it in a module named `CInterop` seems weird to me.  Maybe there's some other unifying name I'm not thinking of?
  * I suppose it could be simply `C`, without renaming `c_int` to `int`, but `C.c_int` reads a little odd to me.
  * It's not clear to me in what way `c_memset()` deserves to be part of this "module of C stuff" where other C routines in FileSystem or POSIX or whatever are not.  What would the rule be for what gets into this module?
* the third option returns to the things I found attractive in the first, just in a different guise but raises the classic "when are nested modules attractive vs. overkill?" question for me.

**Comment by lydia-duncan** [comment]
My preferred order on these is probably first "CInterop module" (naming pending), then "submodule of a C module hierarchy", then "CTypes module" and I would really rather not drop the "c_" prefixes.

I like having the types and other C functions together as much as possible because I think it's most likely that they would be used in tandem.  I don't see a situation where a module with the C functions doesn't use the CTypes module.  And given the principle I like to follow of "if you rely on a type from another module in a public interface, it should be publicly used", it seems like the C functions module should re-expose the CTypes module's contents and most people would only end up using the C functions module in practice.

Having it be a submodule probably still runs into that situation as most of the functions we'd expose would rely on these types, but it does still allow people to only bring in the types if they really really just want the types.  To me, having them be in a submodule for that situation to some extent reflects that we think it's unlikely to come up often in practice but still could.

**Comment by gbtitus** [comment]
I hadn't happened to ponder the topic before, but while thinking about this issue I found myself wondering how/whether the ISO C and POSIX standards differed. A web search led to [a stackoverflow question](https://stackoverflow.com/questions/9376837/difference-between-c-standard-library-and-c-posix-library) and, more authoritatively, [a section of the POSIX standard](https://pubs.opengroup.org/onlinepubs/9699919799/functions/V2_chap01.html#tag_14_01). Both of these seem to me to say that the POSIX standard is a superset of the library part of the ISO C standard. If that's so, then at least on POSIX-compliant target platforms we really only need a module to supply the C types. The `POSIX` module we're discussing separately could supply the C library functions.

This still leaves the question of what to do on non-POSIX target platforms. I'm guessing the Windows Bash Shell environment might fall into this category, though I don't know enough about it to be sure.

If we don't need to support non-POSIX target platforms then I think the first alternative would be sufficient, with the `POSIX` module supplying the C library. If we do, or as an alternative even if we don't, then either separate `CTypes` and `CLib` modules or a single `C` module with `Types` and `Lib` submodules are okay with me, with the `CLib` or `C.Lib` module simply re-exporting the `POSIX` module on POSIX-compliant platforms and needing a separate implementation on non-POSIX ones. I have a slight preference for the `C` module + submodules style, but either would be okay.

Wherever these are defined, I prefer they retain their `c_` prefixes. That's just the right amount of obvious/obnoxious for me. Having to type the uppercase and punctuation for something like `C.int` would just be too much, so I'm not at all fond of the fourth alternative (see #18012).

**Comment by bradcray** [comment]
Replying to Lydia's [comment above](https://github.com/chapel-lang/chapel/issues/18013#issuecomment-872349224):

> I like having the types and other C functions together as much as possible because I think it's most likely that they would be used in tandem.  I don't see a situation where a module with the C functions doesn't use the CTypes module.

I agree and disagree with this in some ways.  I agree that if you're using things like `c_malloc` or `c_memset`, you're likely to use at least some of the `CTypes` module, but probably not most of it.

Reversing your example, I think there are likely to be many cases in which one uses the `CTypes` module (or types from it) without wanting or needing the other memory-focused routines.  For example, I've written a lot of interop code in Chapel that wants to refer to C types, but virtually no code that calls c_malloc, c_memset, and the like.  As another example, I think if we looked across all of our C-level modules, we'd find many other routines that had similar relationships with `CTypes` (they want to accept and return CTypes) where we wouldn't want to put them into a monolithic `CInterop` module.

So if I were arguing for the first option (distinct modules for CTypes vs. other C memory routines), I'd say that the `CMemory` module (or whatever it's called) might re-export `CTypes.c_ptr`. It might also _possibly_ re-export `c_int` or `c_ssize_t` or the like, though I'm realizing that with the current interfaces (which are more Chapeltastic than I realized in the module review, taking `integral` rather than `c_int`), this isn't particularly necessary—I could just use Chapel types (unless we change that).

That said, I'd also be curious to see what would happen if `CMemory` didn't re-export `c_ptr` under our new method / operator lookup rules.  I.e., if I leaned on type inference and never typed `c_ptr` in my code, then maybe there isn't any real need or benefit to having `CMemory` re-export it(?).

> And given the principle I like to follow of "if you rely on a type from another module in a public interface, it should be publicly used"

When you say "publicly used", if the only symbol required by clients of `CMemory` was `c_ptr` would you literally `public use CTypes;` or would you use one of `public import CTypes.c_ptr;` or `public use CTypes only c_ptr;`?

**Comment by lydia-duncan** [comment]
> For example, I've written a lot of interop code in Chapel that wants to refer to C types, but virtually no code that calls c_malloc, c_memset, and the like. As another example, I think if we looked across all of our C-level modules, we'd find many other routines that had similar relationships with `CTypes` (they want to accept and return CTypes) where we wouldn't want to put them into a monolithic `CInterop` module.

Your experience is a reasonable counter-example.

> > And given the principle I like to follow of "if you rely on a type from another module in a public interface, it should be publicly used"
> 
> When you say "publicly used", if the only symbol required by clients of `CMemory` was `c_ptr` would you literally `public use CTypes;` or would you use one of `public import CTypes.c_ptr;` or `public use CTypes only c_ptr;`?

I'd go for as minimal as possible.  With the limitation that the only symbol required by clients was `c_ptr`, I would definitely lean more towards the import or `use ... only` of `c_ptr` itself rather than the whole module.

**Comment by king-11** [comment]
`CTypes` sounds better to me because the discussion in #18017 seems to be that we create `c_` prefixless procedures then creating a `CInterop` won't be required a naming it `CTypes` would be more intuitive.

**Comment by mppf** [comment]
FWIW I had been imagining that we'd have `CTypes` containing the types described above as well as functions like `c_malloc`. I guess I would rationalize this as the module being "C types and the basic functions you need to operate on them". In the same way that a module defining a type would normally include a initializers and other methods on that type.

**Comment by bradcray** [comment]
It looks like we're settling on `CTypes` as the answer here, based on discussions here and on the internal team slack.  I'm implementing in that direction.
