### ISSUE TITLE
Should / could `c_void_ptr` be replaced with `c_ptr(void)`

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#18011]
While reviewing the `CPtr` module from a language stabilization perspective, it was noted that we could probably replace `c_void_ptr` with `c_ptr(void)` to unify the two flavors of pointers into one.  This issue asks whether anyone would object to doing so (assuming no show-stoppers present themselves in attempting it).

We believe that we got into the current state by virtue of initially supporting a type alias representing `void*` as a distinct concept prior to any support for the generic `c_ptr(void)`.  It also seems likely that we hadn't really solidified our `void` vs. `none`/`nothing` features yet at the time we were introducing `c_ptr()`.

Note that this issue interacts slightly with #18010.

**Comment by lydia-duncan** [comment]
I'm tentatively in favor of this, but am worried there's something I'm missing that makes the current state more valuable

**Comment by king-11** [comment]
I am more in favour of keeping them because just defining and typecasting to void pointer wherever required seems cleaner with `c_void_ptr` type instead of calling in a type constructor every time I need which probably would make some users declare `c_void_ptr` again inside their program/module as `type c_void_ptr = c_ptrTo(void)`.

I was hoping we can keep `c_void_ptr` and use `c_ptrTo(void)` to declare it for the user instead.

**Comment by bradcray** [comment]
@king-11: Thanks for weighing in.

I suppose I agree that typing `c_void_ptr` is somehow more attractive to type and/or read than `c_ptr(void)` (note: _not_ `c_ptrTo(void)`) if for no other reason than that it trades a pair of parenthesis for an underbar.  But I think a similar argument could be made in other cases (e.g., "I'd like to type `c_int_ptr` rather than `c_ptr(c_int)` because I use it a lot") and I'm not sure that's a reason to special-case `c_void_ptr`.  Unless we think it's just inherently more used/useful in C and therefore warrants a special case, which I believe in some contexts, though maybe not enough...

In most other respects it seems preferable to me to have symmetric syntax for `c_ptr(t)` regardless of whether `t` is `void`, `c_int`, `int` or whatever (to reflect that it's symmetrically `t*` for all cases in C).

I'm not sure I completely buy the "calling a type constructor" argument in any deep sense, since it's resolved at compile-time and (in a good compiler implementation) shouldn't actually add significant compile-time overhead; so I view the overhead as being primarily syntactic.

I think the strongest argument against the status quo is that we have typically tried to avoid having two "official" ways to write the same thing to avoid questions like "This code uses `c_void_ptr` and this other code uses `c_ptr(void)`... what's the difference?"  So if the two were equivalent ("Oh, nothing?"), that can make a language harder to learn or code written in the other style harder to read.  Whereas if your code chooses to use the typedef as you propose (or imports it from a module defining the typedef), then anyone reading the code can see the equivalence in the source.

**Comment by king-11** [comment]
I think the issue with `c_int_ptr` won't be an issue because we have `ref` intents for its purpose. That is what makes `c_void_ptr` different, in my opinion, the need for explicit typecasting while other types can easily work with ref intents. I think the idea of using symmetric syntax sounds good to me but as a user, I will certainly bring `c_void_ptr` back as typedef to prevent non-DRY code.

**Comment by bradcray** [comment]
There's definitely a style question here, but ever since `c_ptr()` was introduced, I've started writing ptr-to-int patterns as `x: c_ptr(c_int)` rather than `ref x: c_int` simply because it seems like a more precise description of what the C interface is and avoids questions that always plague me when using `ref` (perhaps to knowing too much about Chapel for my own good) where my mind starts thinking things like "Could this be a reference to an integer on a remote locale?").  I'm fairly certain it can't be and that the implementation won't permit it to be, but using `c_ptr` removes those questions for me, which is why I prefer it.

**Comment by bradcray** [comment]
Only tangentially related to this, but #18747 contains a program that segfaults with `c_ptr(void)` yet works with `c_void_ptr`.  That doesn't suggest anything about the direction proposed in this issue, but was intriguing to me because (a) I didn't know whether `c_ptr(void)` would even make it through the compiler or not (it doesn't for LLVM) and (b) it suggests that they get treated differently at some key point(s) in compilation even though the generated C types seem to be equivalent (note that the LLVM back-end won't even accept `c_ptr(void)` today).

**Comment by riftEmber** [comment]
The [CTypes design subteam](https://github.com/Cray/chapel-private/issues/4824) has decided to deprecate `c_void_ptr` in favor of `c_ptr(void)`, notwithstanding any unresolvable implementation issues. I will plan on leaving this issue open until implementation is done.

**Comment by riftEmber** [comment]
This replacement has been done in PR https://github.com/chapel-lang/chapel/pull/22637
