### ISSUE TITLE
Have gasnet use our bundled hwloc

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#18050]
In https://github.com/chapel-lang/chapel/pull/18049 I disabled gasnet's use of hwloc because our bundled version of hwloc has a prefix that was causing link time name mismatches with the system version gasnet detected. I just disabled as a quick fix, but we should probably just tell gasnet to use our hwloc longer term.

For qthreads we needed https://github.com/Qthreads/qthreads/pull/87 to tell configure about our prefix, so I'm not sure if we'll need something similar for gasnet. With a quick test it looks like gasnet won't require this, but I want to check more before PR'ing. Here's the quick patch I tested:

```diff
diff --git a/third-party/gasnet/Makefile b/third-party/gasnet/Makefile
index 75cf0615de..08293503ae 100644
--- a/third-party/gasnet/Makefile
+++ b/third-party/gasnet/Makefile
@@ -86,7 +86,9 @@ GASNET_CFLAGS += $(SHARED_LIB_CFLAGS)
 MPI_CC += $(SHARED_LIB_CFLAGS)
 endif
 
-CHPL_GASNET_CFG_OPTIONS += --disable-hwloc
+ifeq ($(CHPL_MAKE_HWLOC),bundled)
+CHPL_GASNET_CFG_OPTIONS += --with-hwloc-home=$(HWLOC_INSTALL_DIR)
+endif
 
 CHPL_GASNET_ENV_VARS:= CC='$(CC)' CXX='$(CXX)' MPI_CC='$(MPI_CC)' CFLAGS='$(GASNET_CFLAGS)' CXXFLAGS='$(GASNET_CFLAGS)'
 
```

It looks like hwloc is only used for ibv multirail support, which we don't current support so I don't think this is particularly pressing.

**Comment by ronawho** [comment]
cc @PHHargrove

**Comment by bonachea** [comment]
@jhh67 and @PHHargrove : As of today Chapel `main` branch is still passing `--disable-hwloc` to GASNet configure. This will effectively disable the GASNet code that [Paul is currently working on](https://bitbucket.org/berkeleylab/gasnet/pull-requests/635/hwloc-distance-part-1-of-2?link_source=email) to add more intelligence to GASNet (and {ofi,ibv} conduits in particular) to automatically select appropriate "nearby" NICs in multi-NIC nodes based on node topology.

At some point soon (probably after the 2.1 release) we should apply @ronawho 's patch above to ensure that GASNet can use the same hwloc the rest of the Chapel runtime is using. IIUC it should really be as simple as that.
