### ISSUE TITLE
"error: This compiler was built without LLVM support" could be clearer

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#18073]
As an experienced Chapel user, I had some confusion yesterday when I started getting errors of the form:

```
error: This compiler was built without LLVM support
```

for anything I tried to do with my install.  It turns out that the source of the problem was that I indeed had built my compiler with `CHPL_LLVM=none`, but that in my current working environment, I had `CHPL_LLVM=system` set.  I understand now that this means that I was requesting a configuration that the compiler doesn't support, but I don't think this will be particularly clear to a typical / novice end-user given how much it gave me pause.  Something like:

```
error: You have requested a 'CHPL_LLVM=system' compilation, but this compiler was built without LLVM support.  Either set `CHPL_LLVM=none` or re-build your compiler with LLVM enabled
```

(where obviously it would use `bundled` rather than `system` if that's what I had set it to.

**Comment by mppf** [comment]
I agree that this error message isn't particularly easy to understanding in the llvm-by-default mode we are in now.

The proposed error message improvement works for me.
