### ISSUE TITLE
Design for Apache Arrow Arrays and Record Batches

### ISSUE THREAD

**Issue by ShreyasKhandekar** [chapel-lang/chapel#18074]
Parent Issue: #18127

This issue is meant to generate discussion about the design for the high level interface of [Apache Arrow](http://arrow.apache.org/) in Chapel which will be built on top of the Low Level Chapel interface.

We aim to make things less verbose and more abstract while still retaining all functionality and ability to control what we do.
One of the pivotal aspects of designing the Module is for us to be able to create Arrow Data Structures in a succinct manner.

Currently creating an Arrow Record batch (the smallest useful data structure; essentially a table) is very tedious and involves building up arrays element by element and putting them together using a schema that we build in a similar fashion.

This whole ordeal take ~200 lines of Chapel code (transliterated from the C interface of Apache Arrow which also takes the same amount of code). 
A primary goal with this design is to get that number down to 5 lines or less in a way that does not compromise usability and clarity.

The [PyArrow](http://arrow.apache.org/docs/python/index.html) Python interface is a major source of inspiration for the design of this Chapel Module.

Here are some of the ideas I have:

## Creating Arrays

Ways we should be able to create arrow arrays.

### From Chapel Arrays

We take a Chapel array and use it to create an arrow
array by mapping it down to
(garrow_(inferred_type_array_builder_append_values)
to append values.
We might also use an optional validity argument which can
describe the NULL Values till we allow null values in
Chapel Arrays.

That argument need not be a complete array with booleans
for each item.
It could be an array of indices which are NULL.
It could be a bitvector as well.
Option 1:
ex:

```chapel
Arrow.array([1,2,3,4]);
```
Option 1.1
or

```chapel
Arrow.array(["foo", "bar", "baz", "invalid"], validity = [3]);
```
Option 1.2
or

```chapel
Arrow.array(["foo", "bar", "baz", "invalid"], validity = 1110);
```

We don't technically have to pick one, but we should have
a single way to do something.

If we want to not infer types too much, we should instead
use more functions so that the user will have to specify
the type of the array.

ex:
Option 2
```chapel
var intArray = Arrow.int32Array([1,2,3,4]);
```

or
Option 2.1
```chapel
var stringArray = Arrow.stringArray(["foo", "bar", "baz", "invalid"], validity = [3]);
```

or
Option 2.2
```chapel
var boolArray = Arrow.boolArray([true, false, true, false], validity = 1011);
```

Optionally, we could also overload the `array()` function
to accept a (mandatory?) type argument as well.

## Creating Schemas

A schema is basically metadata about a record batch which tells us what 
the names and types of the columns of a record batch are.
Giving direct access to arrow types is important so that
we can actually build a schema.

We could use an array of tuples like pyarrow

```chapel
Arrow.schema([("field0", Arrow.int32()),
            ("field1", Arrow.string()),
            ("field2", Arrow.bool())]);
```

## Creating Record Batches

We can use the arrays we created above to create Record
batches.
We can put these arrow arrays inside a Chapel Array to
put them together so they may be passed as one argument.

We can pass another argument specifying the schema.
See how to create a schema [above](#creating-schemas).

Say we put the above 3 arrays is an outer array called
`data` and put the above schema in a variable called
`schema` as follows:

```chapel
var data = [intArray, stringArray, boolArray];
var schema = Arrow.schema([("field0", Arrow.int32()),
            ("field1", Arrow.string()),
            ("field2", Arrow.bool())]);
```
Where intArray, stringArray, and boolArray can be put together in the same array as they share a common base type which is `GArrowArray`.

We can put then together in a record batch as follows:

```chapel
Arrow.recordBatch(data, schema);
```

Here too, if we are more inclined to infer types we can
just pass in the titles of the columns instead of a
schema.

Please feel free to suggest other ways of doing this or modifying any of the above options to make more sense.

#### Note

There are other topics that deal with some of the later steps in developing this module and though comments and feedback on it is welcome, I would appreciate if we were able to hash out a preference for 
- Creating Arrow Arrays of different types
- Creating Schemas
- Creating Record Batches

before moving on to the other topics like IO, IPC and Dealing with Parquet Files

**Comment by mppf** [comment]
> `chplarrow.array([1,2,3,4]);`

Inferring types here sounds like a good idea.

I'm not so sure if `chplarrow` is the module name? Module names are Uppercase and I wouldn't expect the Chapel module needs to include `chpl` in the name. Maybe it should just be called `Arrow`?

> `chplarrow.array(["foo", "bar", "baz", "invalid"], validity = 1110);`

Unlike in Python, the Chapel default sized integers cannot be of arbitrary size. They are 64-bits. Additionally if you really wanted to store a bit vector in an integer, you would write e.g. 0b1110. The issue with the integers just being 64-bits is that this approach is limited to 64 element arrays.

Of course you could still have an array of `bool`s to indicate validity. That is probably what I would think of as the most obvious.

> `ca.schema([("field0", ca.int32()), ("field1", ca.string()), ("field2", ca.bool())]);`

Here I assume that `ca.int32()` etc are returning some kind of type internal to Arrow that represent a type? And that all of these have the same compile-time Chapel type?

> `ca.recordBatch(data, schema);`

It would be nice if the issue included an example of what `data` might be when using this function.

**Comment by ShreyasKhandekar** [comment]
I've changed the original Issue to call the module as `Arrow`

Currently I am having some trouble accurately representing the Arrow Data types like `GArrowInt32DataType` or `GArrowStringDataType` which are the data types that ought to be returned when calling `Arrow.int32()` and `Arrow.string()` respectively. But since they are currently opaque types which are just `c_void_ptr`s, they cannot be differentiated. A full implementation of the GLib wrapper might help us here because it would have the `garrow_data_type_equal()` function. But I can still use them in function calls as usual.

> Of course you could still have an array of `bool`s to indicate validity. That is probably what I would think of as the most obvious.

A whole array of bools seems verbose and very annoying for large, dense arrays. That is why I though to use an array which represents only the `false` indices.

> It would be nice if the issue included an example of what `data` might be when using this function.

I do not have code that creates data because I say the following:
>Say we put the above 3 arrays is an outer array called
`data` and put the above schema in a variable called
`schema`.

I did not have that in there because it seemed pretty trivial. Do you think it would be helpful to add that code?

**Comment by mppf** [comment]
> I did not have that in there because it seemed pretty trivial. Do you think it would be helpful to add that code?

Yes, if it really is trivial it should only take you 5 minutes :)

**Comment by ShreyasKhandekar** [comment]
It seems that there is support for building arrays using options 1 and 1.1 in the original post where we use an optional validity array to denote the items that are null.
This can obviously still change.

After hearing some ideas from the team, about making record batches, it seems we do not want to ask the user to build an explicit schema to pass into the record batch function and would rather infer types from the arrays passed to us.

### Other ideas for building Record Batches

Here are some other ideas related to how we might build record batches that don't really need us to build an independent schema.

#### Inferring Types

Here too, if we are more inclined to infer types we can just pass in the titles of the columns instead of a
schema.

```chapel
Arrow.recordBatch(data, ["field0", "field1", "field2"]);
```

Though it is important to note that it might be hard to infer types here because the elements of Data are of type `GArrowArray` and thus it might be hard to extract the actual types. The `garrow_array_get_value_data_type ()` function can be used here to make it easier.

#### Variadic args function

Instead of putting our data in an array, we could use a variadic arguments function which will take our arrays and their names.

We could use tuples to group the arrays and their column headers/titles as follows:

```chapel
Arrow.recordBatch(
    ("field0", intArray), 
    ("field1", stringArray), 
    ("field2", boolArray));
```

Or we could alternate between array title and array without any grouping using tuples and allow the function to interpret that.

```chapel
Arrow.recordBatch(
    "field0", intArray, 
    "field1", stringArray, 
    "field2", boolArray);
```

This approach might make it easier to interpret the actual types of the arrays.

Out of these three options, there seems to be soft preference for the last one with a flat list.
Again there has not been a formal agreement on this, and thus we can change this if needed.

I have made rough versions of both the array and record batch functions and they work with what we have right now.

**Comment by mstrout** [comment]
In #18094, it looks like you prototyped the flat alternating column name and array.
```
Arrow.recordBatch(
    "field0", intArray, 
    "field1", stringArray, 
    "field2", boolArray);
```
That looks good to me for an interface for creating those.

**Comment by lydia-duncan** [comment]
> > Of course you could still have an array of `bool`s to indicate validity. That is probably what I would think of as the most obvious.
> 
> A whole array of bools seems verbose and very annoying for large, dense arrays. That is why I though to use an array which represents only the `false` indices.

One thing to keep in mind is how this will impact determination of whether an index is invalid or not.  Having a compressed array of the invalid indices is handy when you want to traverse the array as a whole and see which ones are invalid, but it makes it harder to determine if an individual index is invalid as you don't know immediately which index to look at in the validation array to determine it.  If the validity array is sorted, this could be a binary search.  If it's not, you have an O(num invalid indices) operation.  Both of these are worse than what would have been an O(1) operation.

**Comment by bmcdonald3** [comment]
I agree that the flat, alternating argument list is my favorite:
```
Arrow.recordBatch(
    "field0", intArray, 
    "field1", stringArray, 
    "field2", boolArray);

**Comment by arezaii** [comment]
> One thing to keep in mind is how this will impact determination of whether an index is invalid or not. Having a compressed array of the invalid indices is handy when you want to traverse the array as a whole and see which ones are invalid, but it makes it harder to determine if an individual index is invalid as you don't know immediately which index to look at in the validation array to determine it. If the validity array is sorted, this could be a binary search. If it's not, you have an O(num invalid indices) operation. Both of these are worse than what would have been an O(1) operation.

Could one solution take the best of both worlds? From the user's perspective, they only provide the invalid index values, but behind the scenes we build a full array of `true` values and just update the ones they indicate to `false`? That would add a little overhead when creating the array, but queries would still be O(1). 

Also, may we want a way to specify which value we want an index to specify in the case that we have a dense array of invalid data as opposed to a valid data? 

something like 1.1, but with an optional boolean to assign default validity.

for a dense valid array:
`Arrow.array(["foo", "bar", "baz", "invalid"], validity=[3]);`

for a dense invalid array:
`Arrow.array(["invalid", "invalid", "invalid", "foo"], validity=[3], default=false);`

**Comment by ShreyasKhandekar** [comment]
> Could one solution take the best of both worlds? From the user's perspective, they only provide the invalid index values, but behind the scenes we build a full array of `true` values and just update the ones they indicate to `false`? That would add a little overhead when creating the array, but queries would still be O(1).

This is exactly what the function does right now. Because the C implementation wants a full array of `bool`s, we must be giving that to the C function. 

I like adding an argument change the default validity for dense invalid arrays as well.

**Comment by ShreyasKhandekar** [comment]
Tables are a larger collection of data in Arrow, meant to be larger than either record batches or arrays.
They are primarily what we write to parquet files.

How to build a table is an issue we must discuss.
The preferred way to build them is through record batches:
ex:
Say if we created a record batch from the arrays described in the earlier posts above and put it in a record batch as follows:

```chapel
var rcbatch = Arrow.recordBatch(
                             "field0", intArray, 
                             "field1", stringArray, 
                             "field2", boolArray); 
```

we can then put one or more record batches in a chapel array and put them together in a table as follows:

```chapel
var table = Arrow.table([rcbatch, rcbatch]);
```

OR we could go the same way we build record batches with a flat list using variadic arguments:
```chapel
var table = Arrow.table(rcbatch, rcbatch);
```

Please also vote on your preferences or ideas on this :)

**Comment by mstrout** [comment]
What symbols do you want us to use to vote?

For the recordBatch, we went with the variadic flat parameter list to obtain type information.  Would the list of recordBatches all need to have the same type?  If so, then I vote for the list approach.

**Comment by bmcdonald3** [comment]
I agree, the flat list seems to make more sense to me and I could see how using the Chapel array variant could impose some additional type restraints based on the implementation that we end up going with for the record batch. 

That being said, I don't have a strong opinion either way really.

**Comment by ShreyasKhandekar** [comment]
> What symbols do you want us to use to vote?

I just updated the post with the symbols. Sorry about that.



> For the recordBatch, we went with the variadic flat parameter list to obtain type information. Would the list of recordBatches all need to have the same type? If so, then I vote for the list approach.

A couple of things regarding this:
1. We actually did not need to use the variadic argument list in the `recordBatch` function to obtain type information. There is a function within the C implementation called `garrow_array_get_value_data_type()` which determines the type of an array for us.
2. The record Batches all need to have the same schema. Which means the columns of each recordbatch need to have a one-to-one correspondence of types (the first column of all recordBatches must all be of the same type, the second columns must all be of the same type but can be different than the first etc.)

I hope this clarifies some things about which types need to be the same.

In order to compare the recordBatch's schemas, we could use two functions: `garrow_record_batch_get_schema()` to get the schema from the record batch and `garrow_schema_equal()` to compare schemas. So we can put all recordBatches inside an array with no issues whatsoever regarding out ability to get their "types" i.e. schemas.

But technically the GLib implementation will provide us with an error if the schemas don't match so we don't even need to do this schema checking.

I am not sure if this changes what you were recommending.

**Comment by ShreyasKhandekar** [comment]
Personally I have a slight inclination to chose the array parameter for the slight flexibility an array provides the user trying to build the table.
The array can be built up by some code with recordBatches being appended to it or not following whatever logic the user wants to use. And then the final array which contains all the data the user wants to put into a table can be used by the `table` function together.
The flat list would take away from this ability to build up an array following some logic.

For example, if the user wanted to receive data from the IPC format, it can only be done so in recordBatches. Maybe they are receiving those one by one and want to eventually put them all in a table. Using the array approach they can put them in an array that they build up over time and once they are done they pass that array to the `table` function.

**Comment by lydia-duncan** [comment]
> ```chapel
> var rcbatch = Arrow.recordBatch(
>                              "field0", intArray, 
>                              "field1", stringArray, 
>                              "field2", boolArray); 
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> we can then put one or more record batches in a chapel array and put them together in a table as follows:
> ```chapel
> var table = Arrow.table([rcbatch, rcbatch]);
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> OR we could go the same way we build record batches with a flat list using variadic arguments:
> ```chapel
> var table = Arrow.table(rcbatch, rcbatch);
> ```

I think this general path is fine.  I have a slight preference for the unwrapped form of creating a table, it seems like it requires less work on the user's part - however, I can see it being handy when you already have an array.  Would it be problematic to provide both of these?

**Comment by mppf** [comment]
It feels to me a bit like having `list` have initializers to create a `list` from an array, or another list, or a tuple. These seem reasonable to me.

Separately, it seems like a bunch of functions in your proposal are top-level in `Arrow`. When creating something in Chapel it would be more typical to use `new`, or even `init=`. For example, today you have

``` chapel
var rcbatch = Arrow.recordBatch(
                             "field0", intArray, 
                             "field1", stringArray, 
                             "field2", boolArray); 
```

There are many other stylistic options. We could rename it to be `Arrow.createRecordBatch` or `Arrow.newRecordBatch`. Or we could change it to:
``` chapel
var rcbatch = new recordBatch("field0", intArray, 
                              "field1", stringArray, 
                              "field2", boolArray)
```

or even


``` chapel
var rcbatch: recordBatch = ("field0", intArray, 
                            "field1", stringArray, 
                            "field2", boolArray)
```

**Comment by bmcdonald3** [comment]
I agree with Michael's comments, that seems to be more consistent to me.

Additionally, after talking with Shreyas and considering the suggestions from Ahmad above, we were thinking it could make sense to provide both `validindices` and `invalidIndices` keyword arguments to the function, so the user could have the flexibility to easily create both a sparse and dense array. Also, in my opinion, these names make more sense and are more descriptive than just `validity`, so I am in favor of `validindices` and `invalidIndices` instead.

This could look something like this:
```
Arrow.array(["invalid", "invalid", "invalid", "foo"], validIndices=[3]); // only the last element is valid
Arrow.array(["foo", "bar", "baz", "invalid"], invalidIndices=[3]); // only the last element is invalid
```

It would likely require more reading of the docs, but I think I prefer this to the other suggestions based on readability.

**Comment by ShreyasKhandekar** [comment]
I agree with Michael's idea too. I think we would want to put these types
inside a record each in order to define the `init` or `init=` functions on
them. Which is actually not a bad idea independently either. It would mean we
don't have to expose the C types directly to the user and it will grant us more
control and possibly enable us to write safer code.

One thing that I am thinking of which is limited by my knowledge of Chapel, is
that we would still need to have a class hierarchy for things like Arrays, or
Streams in arrow. This means that we would need to use classes instead of
records. Which in turn means we can not use the `init=` syntax.
Please do correct me if I'm mistaken on this.

I'm thinking maybe we can define a simple class as follows within the Arrow
module:

```chapel
class Array{
var arr: GArrowArray;
}
```

and

```chapel
class RecordBatch {
var rcbatch: GArrowRecordBatch
}
```

and then the `init` or function can call into the functions we were
using earlier to create these Arrays and RecordBatches.

One thing I am not sure about is that how this would affect Chapel's memory
management since technically the memory would still be allocated and belong to
the C process.

**Comment by mppf** [comment]
> One thing that I am thinking of which is limited by my knowledge of Chapel, is
that we would still need to have a class hierarchy for things like Arrays, or
Streams in arrow. This means that we would need to use classes instead of
records. Which in turn means we can not use the init= syntax.
Please do correct me if I'm mistaken on this.

It is accurate that classes can't have `init=`. Why are you thinking that Arrays or Streams will need to be represented with classes?

> I'm thinking maybe we can define a simple class as follows within the Arrow

You can make a similarly simple `record Array`. One thing worth considering is adding a `type eltType` to it. Also, you probably shouldn't name it just `Array` but that is debateable.

``` chapel
record arrowArray {
  type eltType;
  var arr: GArrowArray;
}
```

You can use this `type eltType` to reason about the types at compile time within Chapel, if that is useful.

> One thing I am not sure about is that how this would affect Chapel's memory
management since technically the memory would still be allocated and belong to
the C process.

Whether using a Chapel record, a Chapel class, you will need to adjust that type to inform the GArrow implementaiton when something is no longer needed. You would most likely do this by writing `deinit` functions.
