### ISSUE TITLE
Array module review followup: Throw an exception if you try and do a "Chapel Style" print out of a multidimensional array.

### ISSUE THREAD

**Issue by stonea** [chapel-lang/chapel#18090]
This is a followup item for the [Array module review](https://github.com/Cray/chapel-private/issues/2241).

Since we haven't yet determined what the syntax for initializing multi-dimensional arrays should be, we wanted to ensure that if you try and print out a multidimensional array in "Chapel style" we get some kind of error
message.

**Comment by mppf** [comment]
Here is an example of the current behavior:

``` chapel
var A:[1..2, 1..2] string = "hi";

writef("%ht\n", A);
```

```
[
 ["hi", "hi"],
 ["hi", "hi"]
]
```

**Comment by e-kayrakli** [comment]
Current behavior seems wrong, and I am for preventing Chapel style IO for multidimensional arrays until we have a better strategy for it.
