### ISSUE TITLE
Retire `list.extend` in favor of new `list.append` overloads

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#18098]
The `list` type has an `append` method that adds a new element at the end of the list. Whereas, `extend` is used for the same purpose but for adding more than one element (accepts lists, ranges or arrays as argument). This is based on Python's `list`. However, this is probably because Python has a weaker type system than Chapel's and we should be able to achieve all this by having a single method with different overloads.

This issue proposes that we deprecate/remove `list.extend` and add `list.append` overloads instead. One little hiccup there is that `append` returns the index at which the element is added. This may not make much sense for non-scalar appends. So, I also propose that we make `append` not return anything.

I don't have strong opinions beyond having a single method. `append` vs `extend` or whether `append`/`extend` returns something does not matter as much to me.

**Comment by ty1027** [comment]
I also imagined that the functionality of `.append()` and `.extend()` could be overloaded to just `.append()` (i.e., if the argument if an array etc, all the elements are appended to the list). One concern is that this eliminates the ability to add an array etc as a single entity to the list (e.g. like in Python's append() in the following page), but it is probably not a problem for lists in Chapel (if the elements must be of a single uniform type)?

append() and extend() in Python
https://www.geeksforgeeks.org/append-extend-python/

**Comment by lydia-duncan** [comment]
> One little hiccup there is that `append` returns the index at which the element is added. This may not make much sense for non-scalar appends. So, I also propose that we make `append` not return anything.

By non-scalar appends, do you mean when the values being added are not scalars, or when the indices are not scalars?  The former doesn't seem like a problem to me, while I wouldn't expect "append" to work in the latter case.  Couldn't you just return a range of indices that were newly created for the elements that have been appended?

**Comment by lydia-duncan** [comment]
I'm otherwise fine with using `append` and dropping `extend`

**Comment by e-kayrakli** [comment]
> By non-scalar appends, do you mean when the values being added are not scalars, or when the indices are not scalars?

The former. I don't think I understand what the latter is exactly.

But, yeah. I think it can return a range. Or it can still return the index at which the first element of the argument was added at. I wouldn't object to that. Above all else, I think I prefer consistency that all `append`s return something related or nothing at all.

**Comment by bradcray** [comment]
My head also went to the "returns a range of indices" solution that Lydia proposes.  My guess is that most people drop the returned value of append on the floor anyway, so it's probably not a big deal that the two overloads wouldn't have the same return type.

When you say:

> So, I also propose that we make append not return anything.

Do you mean "both overloads" or "just the array overload?"

**Comment by e-kayrakli** [comment]
> Do you mean "both overloads" or "just the array overload?"

I mean all overloads. That's what I'd do left to my own devices. But that's because I am not seeing too much value in learning the index that I just added to, as you also implied, I think.

In general, my only preference is that they either all return something that is notionally related (even if they're different types), or they all return nothing.

**Comment by bradcray** [comment]
> I mean all overloads. That's what I'd do left to my own devices. But that's because I am not seeing too much value in learning the index that I just added to, as you also implied, I think.

Keep in mind that this was just added recently by user request:  https://github.com/chapel-lang/chapel/issues/17466

For that reason, I'd be inclined to have the scalar version return a scalar, and the multi-element version return a range.  Worst-case, the callee doesn't want it and drops it on the floor.

**Comment by e-kayrakli** [comment]
> For that reason, I'd be inclined to have the scalar version return a scalar, and the multi-element version return a range. Worst-case, the callee doesn't want it and drops it on the floor.

I think that's a good reason to keep returning indices, then. Thanks for the context!
