### ISSUE TITLE
Design for Parquet Files in Apache Arrow

### ISSUE THREAD

**Issue by ShreyasKhandekar** [chapel-lang/chapel#18128]
Parent Issue #18127

Personally I think the GLib implementation is not so bad for reading parquet files, maybe we can add better error handling. But there is still work to be done here.

## Reading and writing quickly

If we want we can consolidate creating a file reader and reading from it into a single function.

```chapel
Arrow.readParquetFileToTable("example.parquet");
```

```chapel
Arrow.writeTableToParquetFile(table, "example.parquet");
```

## Finer reading and writing

We should still allow the `GParquetArrowFileReader` type or make a new `ParquetFile` type to allow finer grained reading and writing of Parquet files.
Writing a record batch should not be allowed (as is the case with other implementations) rather, we must have a table which we write.

The reason I still want the `ParquetFile` type is because it is not always that we want to read the whole table at once. Operations like `getSchema()` and `readColumnData()` should be allowed on a `ParquetFile`

So maybe we also allow:

```chapel
var pf: ParquetFile = Arrow.parquetFile("example.parquet")
```

to just create a ParquetFile object with which we do as we please.

### Note

We would have to figure out a way to combine the GLib types `GParquetArrowFileReader` and `GParquetArrowFileWriter` so that a single `ParquetFile` Object can do both reading and writing.

We might also want to have some classes which define these types so that we may put related functions in it to make naming easier and have some notion of function scope back.

**Comment by ShreyasKhandekar** [comment]
I have tried to make a working `readParquetFileToTable` function as an addition to this PR https://github.com/chapel-lang/chapel/pull/18094.
A working `writeTableToParquetFile` is to follow in order to allow you to see both of these in action.

Please vote on the above designs:
- Please vote with 👍 if you like it.
- Please vote with 👎 if you would like to suggest an alternative

I would also appreciate any thoughts on my proposal of creating a `ParquetFile` class in order to have finer grained reading and writing.

**Comment by bmcdonald3** [comment]
In regards to the ParquetFile class, I think think that is a good idea, but my initial hesitancy is that you may not be able to read/write a file at the same time, which would account for why it is currently split up in the GLib implementation (e.g., if a file is opened up for reading, it may not be able to also be opened up for writing). I don't see anything in the docs about that, but as you know the docs are a bit sparse, so I would need to actually try running some code, which I hope to do soon. I am likely wrong though, so let me know if you know that not to be the case.

**Comment by ShreyasKhandekar** [comment]
I agree, we need to check to see if we can read and write to a file at the same time.

One thing I forgot was in the critical path of building Parquet files is the fact that only tables can be written, therefore we need to ability to build tables first. I think since tables are just a larger collection of record batches (can also be a larger collection of arrays), the place to have the discussion about how to build tables is this issue about arrays and record batches: https://github.com/chapel-lang/chapel/issues/18074
