### ISSUE TITLE
Support renaming extern types

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#18173]
Most Chapel `extern` declarations support a means of giving the C name of the symbol a separate identifier from the Chapel name, which is particularly useful with the C name isn't a legal Chapel identifier.  For instance:

```chapel
extern "domain" var c_domain: c_int;
```

However, it appears that `extern type` declarations don't support this today.  I think they should for completeness and orthogonality, and that this is just an oversight / a case that nobody has tackled yet.  I also believe this would be a relatively straightforward project for someone new to the code base and interested in modifying the compiler (and would be happy to advise / assist).

**Comment by bradcray** [comment]
@bmcdonald3 : Capturing the observation we were making yesterday.  Also, I'm realizing that the case I was thinking of in which a `"struct foo"` string could be used was for an `extern record` declaration, so I'm glad to have solved that gap in my memory.

**Comment by MayukhSobo** [comment]
@bradcray does this still require a PR? I am new to the repo and I am very keen to contribute. As far as I understood, this issue is about

> There is no support for extern declaration of variables with renaming in Chapel and we need to have it for sake of completeness as it is present for function and structs.

Please correct me if I am wrong.

**Comment by cassella** [comment]
Hi @MayukhSobo , the example code written in this issue is of declaring an `extern var` with a different name in Chapel than the variable is named externally.  This case works already as you noted in gitter.  The issue is asking for the same capability for `extern type` declarations, referencing an external type with a different name in Chapel than the type has externally.

For example the requested feature would let you define the Chapel type `c_fpos_t` referring to the C `fpos_t` using:

```chapel
extern "fpos_t" type c_fpos_t;
```

(Although there's not the same reason to as for the `domain` case above since `fpos_t` isn't reserved in Chapel.  It's just an example of the requested feature.)

**Comment by MayukhSobo** [comment]
@cassella Thanks a lot for the clarification. Can you point me to any similar existing PR so that I can take some inspiration. Sorry for asking this as I am new to this repo..Thanks.

**Comment by cassella** [comment]
@MayukhSobo I think the PR you mentioned in gitter, #11760, is pretty close.  I'm not at all familiar with the code, but I think you'd want to start with `chapel.ypp` -- as that PR added the `opt_expr` to the `extern var` declaration (in addition to refactoring it somewhat), you'd want to add an `opt_expr` to the syntax of the `extern type` declaration.

I see that PR added a `cnameExpr` argument to `buildVarDecls()`, so you'll probably have to do something like that for whatever function is called for `extern type`s, and probably handle it similarly.

I'm guessing flex/bison pass the first token matching the line as `$1`, and the second as `$2`, etc.  Beyond that I'd need to check the flex/bison documentation.  Maybe @bradcray has better advice?

I do know the `bison-chapel.cpp` and `bison-chapel.h` files are generated by the build process -- you don't need to update those yourself.

You might actually want to start by adding a `typedef` to the `ccode.h` file in that PR, and add a test with `require "ccode.h'` using the new feature.  It won't work until you're done, but it's nice to have the test written down concretely so you can see the progress you're making as you get through parsing.

**Comment by MayukhSobo** [comment]
> I do know the bison-chapel.cpp and bison-chapel.h files are generated by the build process -- you don't need to update those yourself.

Thanks for this @cassella. I have fundamental understanding in compiler design but this information was highly needed.

**Comment by thegeekymuggle** [comment]
Hi, I would like to contribute to this issue. Can someone help me on how to proceed further? I am new to open source contributions.

**Comment by rinkydevi** [comment]
i can contribute in this issue, can i proceed if it don't have any PR?

**Comment by rinkydevi** [comment]
@lydia-duncan I can contribute to this issue, please confirm if i can proceed

**Comment by lydia-duncan** [comment]
I would give @thegeekymuggle a chance to speak on if they are still trying to implement this.  If they don't respond in a couple of days, go for it!
