### ISSUE TITLE
`chpl` built with `CHPL_LLVM=none` may default to `CHPL_LLVM!=none`

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#18197]
At present, our chplenv scripts infer the value of CHPL_LLVM based on what's available on the system:
* if the bundled version of llvm has been built, CHPL_LLVM defaults to bundled
* if a compatible version of llvm is installed on the system, CHPL_LLVM defaults to system

This causes a problem when a version of `chpl` has been built with no LLVM support.  This might happen when:
* neither of the above conditions held at the time the compiler was built
* the compiler was explicitly built with CHPL_LLVM=none
Specifically, the compiler uses the script's value of CHPL_LLVM and then complains that LLVM was requested but not supported.

This behavior is particularly annoying or confusing when someone is using the `chpl` compiler with nothing set in their environment.  They haven't explicitly requested anything outside of the default, but the compiler is refusing to do anything until they do set something (to tell it something it already should know).

A potential fix would be to have the compiler always use CHPL_LLVM=none when it is built without LLVM support, which seems reasonable.  But how would this be accomplished?

* Could it just hard-code CHPL_LLVM=none regardless of what our chplenv scripts say?  This doesn't seem like it would work because it wouldn't know what to use for CHPL_TARGET_COMPILER (the scripts would say `llvm`)
* Could it set CHPL_LLVM=none in the environment before running the chplenv scripts if it isn't already set?  This seems like it could work, but would have the strange property that `util/chplenv` and `chpl --print-chpl-settings` would differ (but maybe that's acceptable)
* Could our scripts run the compiler to see whether it was LLVM-enabled or not in determining the default value of CHPL_LLVM?  This seems confusingly cyclical (esp. given that we run the scripts in the compiler and when building the compiler)
* Could building the compiler with LLVM enabled/disabled drop that bit of information somewhere where the scripts would have access to them?

**Comment by e-kayrakli** [comment]
If we had what's proposed in https://github.com/chapel-lang/chapel/issues/5743, it feels like that might help with this situation.

**Comment by bradcray** [comment]
I'm not sure I agree.  If we decide that the status quo is appropriate (that is, "If the chplenv scripts infer that you should be using llvm but your compiler wasn't built with it, you should get an error"), then I think it's easy enough to generate that error (which is what I view #5743 as being about).  And PR #18194 does that.  For me, the question is more "Should our compiler ever even be inferring that it should use the llvm back-end if it wasn't built with the back-end?"

Put another way, if a user came to us and said "I typed `chpl hello.chpl` and the compiler said I was wanting to use the non-existent LLVM back-end when I said nothing of the sort," I think I'd share their frustration and am not sure how I'd rationalize our current behavior.

**Comment by mppf** [comment]
> Could it just hard-code CHPL_LLVM=none regardless of what our chplenv scripts say? This doesn't seem like it would work because it wouldn't know what to use for CHPL_TARGET_COMPILER (the scripts would say llvm)

Actually I think this would work. The flow is like this:
 * user has no environment variables set, beyond perhaps having `chpl` in PATH and CHPL_HOME
 * `chpl` binary runs and makes adjustments to an environment to prepare to call `printchplenv`. When it does so, it sets `CHPL_LLVM=none` if it was built without LLVM support. 
 * `chpl` binary runs `printchplenv` with the environment including `CHPL_LLVM=none` and learns the final configuration values from it
 
 
Note that we already needs to do this kind of thing to support setting configuration with command like variables (e.g. `--host-compiler=gnu` would cause the target compiler to be inferred to `gnu` using the code in `printchplenv` / `chplenv` ).

**Comment by mppf** [comment]
Oh, I think perhaps what I am describing is this other option

> Could it set CHPL_LLVM=none in the environment before running the chplenv scripts if it isn't already set? This seems like it could work, but would have the strange property that util/chplenv and chpl --print-chpl-settings would differ (but maybe that's acceptable)

I think it's OK in this case for the settings to differ provided that we emit a warning from the `chpl` compiler when that happens. (We could just emit the warning immediately in the compiler when it sets `CHPL_LLVM=none` when the compiler is built without LLVM support and `CHPL_LLVM` was not already set in the environment)

From https://github.com/chapel-lang/chapel/pull/18194#issuecomment-896303448 -- 

> Thinking about this a few minutes more, I don't think it would work, or at least not easily.  Specifically, in addition to setting CHPL_LLVM=none, it would have to infer a reasonable back-end compiler because the scripting will tell it `llvm` as the back-end compiler.  And that feels more difficult to drag from the scripts into the compiler.  Unless we were to set `CHPL_LLVM=none` in the environment if (a) if it is unset and (b) before we even call the scripts in the event that the compiler was built without LLVM support (?).

It can use the run of `printchplenv` it already does to infer the backend compiler. It's my understanding that in the use case you are after, you just want the default. And as I described above, the compiler already runs `printchplenv` to do these things (and it already adjusts the environment before doing so).

**Comment by bradcray** [comment]
@mppf: That's the option I was leaning towards as well, thanks.

**Comment by bradcray** [comment]
I've now implemented this in #18194.
