### ISSUE TITLE
Should context managers accept thrown errors when cleaning up?

### ISSUE THREAD

**Issue by dlongnecke-cray** [chapel-lang/chapel#18190]
Should context managers accept thrown errors when cleaning up?

Q: If an error is thrown in a managed block, should the manager pass
the error to `leaveThis()` when cleaning up?

---

The `manage` statement allows a type to be used as a context manager
provided it defines two special methods:

- `enterThis()`: Called when entering the managed scope
- `leaveThis()`: Called when leaving the managed scope

Expressions inside of a context manager can throw:

```chapel
var m = new myManager();

manage m as val {
  try {
    val = somePotentiallyThrowingOperation();
  }
}
```

I think that at a baseline the manager will clean up after itself
even if `somePotentiallyThrowingOperation()` throws (feel free to
argue if you disagree, though).

Beyond that: if an error is thrown, should the error be passed to
`leaveThis()` when cleaning up?

The `leaveThis()` method for a given type `foo` currently looks like:

```chapel
proc foo.leaveThis(in err: owned Error?) {
  doSomeCleanUp();
  if err then halt(err);
}
```

It takes an Error by `in` intent, to let the user decide if they want
to rethrow it or not.

Do we want this behavior? Or should the type of `leaveThis()` be:

```chapel
proc foo.leaveThis() {
  doSomeCleanUp();
}
```

## What does Python do?

The `__exit__` method in Python takes the following arguments:

```python
# Takes the type of the exception, an exception value, and an exception
# traceback message.
def __exit__(self, exc_type, exc_val, exc_tb):
  if exc_val != None:
    respondToError()
  cleanup()
```

The user is free to throw new exceptions within the cleanup method,
and the passed in exception can be suppressed by returning
`True`.

## Benefits of passing thrown error to `leaveThis()`

In PEP343, there is a little paragraph explaining why the `__exit__`
method takes the exception as an argument instead of nothing (or a
`bool` flag):

https://www.python.org/dev/peps/pep-0343/

```
The template in that example must commit or roll back the [database]
transaction depending on whether an exception occurred or not. Rather
than just having a boolean flag indicating whether an exception
occurred, we pass the complete exception information, for the benefit
of an exception-logging facility for example...
```

So in some scenarios like a database transaction, it can be helpful
to know what the error was so that you can know whether or not you
need to roll back the transaction or not (in other words, take
specific actions while cleaning up).

The rationale also illustrates that the author may want to log the
error to some sort of facility.

I have struggled to find some database-centric `__exit__` methods
in Python code, but this PEP convinces me that they do exist.

## Benefits of not accepting an error at all

It seems like most context managers would not care about specific
errors occurring. In which case, we may not need to pass an error
to the cleanup function at all.

## Trapping exceptions and the type of the cleanup method

This section is potentially only relevant if we decide we want to
pass thrown errors to the cleanup method.

Right now the `leaveThis()` method takes the thrown error by `in`
intent.

The problem with this is that it becomes very easy for a naive user
to accidentally suppress exceptions that ought to be propagated
upwards:

```chapel
proc foo.leaveThis(in err: owned Error?) {
  cleanup();
  // What about the error?
}
```

In order to propagate the exception with the current model, the user
must attach the `throws` tag:

```chapel
proc foo.leaveThis(in err: owned Error?) throws {
  cleanup();
  if err then throw err;
}
```

And remember to `throw` the error if it exists.

---

In Python, the implementor of the `__exit__` method cannot rethrow
the passed in exception - if they want to suppress it they must
have `__exit__` return a truthy value. Because a "void" function in
Python returns `None`, which evaluates to `False`, this means that
void `__exit__` methods "do the right thing" and propagate the
exception.

What if we were to do that?

```chapel
proc foo.leaveThis(err: borrowed Error?): bool {
  cleanup();
  return false; // The manage statement will propagate `err`
}
```

This seems to work, but the problem is that the caller is now throwing
the exception instead of the method itself, which leads to confusing
error messages today. This is an implementation quirk that will have
to be ironed out.

An upside of this approach is that requiring a `bool` return value
makes the required behavior more explicit: users will naturally
wonder about the consequences of returning `true` or `false`, and
this will likely lead them to doing the right thing.

However a downside is in Chapel an explicit `return true` would be
required.

---

Finally, another option is to pass in the error that occurred, but
prevent the user from suppressing it. This runs into the same
implementation quirks as the previous option.

A benefit of this is that it is impossible for the user to
accidentally suppress the exception.

However some patterns may want to speculatively attempt an action
but then continue execution if it were to fail. This route would
more tightly couple such patterns because it would require the
exception handling logic to appear outside of the cleanup method:

```chapel

var f = new foo();
try {
  manage f as bar do bar.someOperationThatMayThrow();
} except e: SomeFooError {
  f.rollback();
}
```

So this seems to suggest that being able to suppress exceptions in
some cases is a useful behavior.

**Comment by dlongnecke-cray** [comment]
Some additional thoughts.

I think that when we design the type/semantics of `leaveThis`, we
should try to do so in a way that makes it easily constrained by
an interface in the future.

So my idea of:

```chapel
proc leaveThis(err: borrowed SpecificError?): bool;
proc leaveThis(err: borrowed Error?): bool;
```

May not be the best idea, because it seems like it's impossible to
express the additional overloads in an interface.

So that leads me to something like:

```chapel
proc leaveThis(type errT, err: borrowed Error?): bool;
```

[As an aside, I wondered how to constrain the type `errT` such that it
could only be a subtype of `Error`, that will get a discussion issue
soon.]

This seems OK, if a bit unwieldy. I immediately asked the question "do
we even need `errT` at all?

If we have `errT` we can do a select:

```chapel
select errT {
  when SpecificError do ...;
  otherwise ...;
}
```

Without it we'll have to extract out the dynamic type:

```chapel
// Note that the user has to remember to write the '?'
if var downcast = err:SpecificError? {

} else { ... }
```

Another option could just be to leave `err` partially or completely
generic. But then we'd probably want one or more `where` clauses to
help constrain it a bit.

**Comment by dlongnecke-cray** [comment]
Another question is how to handle different versions of `leaveThis`
that may or may not throw. I'm not sure how to capture that in an
interface (as a throwing function must annotate that with `throws`).

**Comment by mppf** [comment]
> In Python, the __exit__ method takes some additional arguments which
allow it to interact with the thrown error...

I think my main question is - how and why is this feature used by Python programs? Do commonly used context managers (e.g. the one for an open file) make use of the feature? To what end?

**Comment by dlongnecke-cray** [comment]
I'm going to spend some effort to find out how Python uses this feature (intercepting exceptions in the `__exit__` method), and focus a bit more on some alternatives. For example, on the extreme end of the spectrum, we need not even intercept exceptions at all, only guarantee that we will call `leaveThis` even if an exception is thrown.

**Comment by dlongnecke-cray** [comment]
I've opted to rewrite the OP of this thread to focus more specifically on the issue instead of opening a new thread.

**Comment by mppf** [comment]
One potential design would be to have `leaveThis` accept the `in err: owned Error?` argument and return an `owned Error?`. To propagate the error, the `leaveThis` body just needs `return err`. This seems to me to be both simpler than the idea of returning true/false and also still would encourage people to remember to do something with the error (since if they forget completely, `leaveThis` won't return anything, presumably).

> This seems to work, but the problem is that the caller is now throwing
> the exception instead of the method itself, which leads to confusing
> error messages today. This is an implementation quirk that will have
> to be ironed out.

It seems to me that all of the "leaveThis handles errors" designs will run into this issue. Do you know of a reason I am wrong about that? Anyway it seems like something we can handle in the implementation of the manage statements.

**Comment by bradcray** [comment]
I'm not keen on the "return a bool" approach because it seems too disconnected from what the user actually wants to do.  The "return the error" approach seems slightly better (in that it keeps an error in the mix, and permits a different error to be "thrown" than was received.  But mostly, I liked the `throws` + `throw` approach in that it seems to be most compatible with the way Chapel is defined ("if I want to throw something, I mark my procedure as `throws` and use the `throw` statement to do so") and doesn't require any special explanations (e.g., "here's what the special meaning of returning an error from a `leaveThis()` means...") while leaning the most on existing language concepts.

> And remember to throw the error if it exists.

I don't see this as any harder / different than remembering to re-throw an error in any other context (e.g., a catch block), and am not sure users need to be protected from there own mistakes here particularly.  If it became an issue in practice, we could potentially generate a warning if a `leaveThis()` has a `throws` yet doesn't contain any `throw` statements (though that may cause problems in a class hierarchy setting with overrides?)

**Comment by dlongnecke-cray** [comment]
Closing. A few releases ago we decided the answer to this was yes, pass in a `in error: borrowed Error?`.
