### ISSUE TITLE
Compiling chapel programs problem: hwloc library picked up from wrong place

### ISSUE THREAD

**Issue by tonycurtis** [chapel-lang/chapel#18202]
### Summary of Problem

Built with bundled hwloc, but got a link error from the bundled gasnet because a libhwloc was being picked up due to either `LD_LIBRARY_PATH` or `pkg-config` from one or both of system-supplied packages already in my environment (hwloc and openmpi).  The API change from `hwloc_obj_type_sscanf` to `hwloc_type_sscanf` made things blow up:

```
$ chpl locales.chpl
/.../chapel/chapel-1.24.1/third-party/gasnet/install/linux64-aarch64-unknown-gnu-none/substrate-ibv/seg-fast/lib/libgasnet-ibv-par.a(gasnet_hwloc.o): In function `gasneti_getenv_hwloc_withdefault':
gasnet_hwloc.c:(.text+0x39c): undefined reference to `hwloc_type_sscanf'
gasnet_hwloc.c:(.text+0x720): undefined reference to `hwloc_type_sscanf'
collect2: error: ld returned 1 exit status
gmake: *** [/.../chapel/chapel-1.24.1/runtime/etc/Makefile.exe:31: /tmp/chpl-...-47532.deleteme/locales.tmp] Error 1
error: compiling generated source
```

Chapel needs to make sure the linked hwloc is indeed the bundled version

### Steps to Reproduce

**Source Code:**

```chapel
// Please provide source code that will reproduce the problem.
// You can insert your code inline if it's not too long.
// Otherwise, you can attach it as a file or provide a URL to it.
// To the extent possible, providing simplified programs demonstrating the
// problem will be appreciated.
// You can also replace this section with "Associated Future Test(s)" below.
```

**Compile command:**

`chpl locales.chpl` from `examples/primer`

**Execution command:**

**Associated Future Test(s):**

### Configuration Information

- Output of `chpl --version`:

```
chpl version 1.24.1
Copyright 2020-2021 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)
```

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: aarch64
CHPL_TARGET_CPU: unknown
CHPL_LOCALE_MODEL: numa +
CHPL_COMM: gasnet +
  CHPL_COMM_SUBSTRATE: ibv +
  CHPL_GASNET_SEGMENT: fast +
CHPL_TASKS: qthreads
CHPL_LAUNCHER: gasnetrun_ibv +
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: none
CHPL_HWLOC: bundled
CHPL_REGEXP: none
CHPL_LLVM: none
CHPL_AUX_FILESYS: lustre +
```

- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:

```
gcc (GCC) 11.1.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

(for a64fx support)

- (For Cray systems only) Output of `module list`:

**Comment by ronawho** [comment]
I believe this has been resolved on main with https://github.com/chapel-lang/chapel/pull/18049. With 1.24.1 you should be able to work around this by building gasnet without hwloc support with the following:

```
cd $CHPL_HOME
export CHPL_GASNET_MORE_CFG_OPTIONS=--disable-hwloc
touch touch third-party/gasnet/Makefile
make
```

**Comment by ronawho** [comment]
Sounds good, I believe this can be closed then?

FWIW just wanted to note that your environment has `CHPL_LOCALE_MODEL=numa` and generally speaking that is more experimental, and will have worse performance than the `flat` locale model so if you're doing any performance comparisons I'd recommend using flat.

**Comment by tonycurtis** [comment]
I'm testing things out on an a64fx cluster where NUMA/CMG can be really important.  Advice noted, though.
