### ISSUE TITLE
`range` should be a reserved word in Chapel, shouldn't it?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#18216]
Initially, Chapel avoided reserving type names as much as possible, but over time, we've swung the other direction and have reserved the vast majority of type names that we use (`int`, `complex`, `bool`, `string`, `bytes`, `domain`, `locale`, ...).  

While preparing slides last night, I realized that it seems we didn't reserve `range` (?), and it's the only case I've b een able to come up with that we seem to have missed.  I think this was probably just an oversight and that we should reserve it, but wanted to confirm with others before taking any action.

**Comment by bradcray** [comment]
I took a quick swipe at this and it wasn't quite as easy as I'd hoped, to some extent because of `range` being a fully-qualified type, which broke things like `rank*range` expressions (where, note that `rank*domain` today is a syntax error).  These could be rewritten as `rank*range()` instead, but... that feels like a bigger change than we'd want to make in our code (and it could affect users as well).  It also suggests to me that this might be tangled up in #18215 (or at least that we'd want to handle that one first since it seems like low-hanging fruit).  Note that in doing this, I tried to take the approach of renaming the range record to `record _range`, which required changing all of the `proc` declarations to be `_range.foo()`, which made me wonder how we'd keep the documentation links working, etc., etc.

I think the next way I'd attempt this would be to see what it would take to support `range` being supported in the parser as a general identifier, and then to prevent it from being used to define anything other than `record range` in an internal module or something like that.

**Comment by stonea** [comment]
> I think the next way I'd attempt this would be to see what it would take to support range being supported in the parser as a general identifier, and then to prevent it from being used to define anything other than record range in an internal module or something like that.

I have something along these lines in this PR: https://github.com/chapel-lang/chapel/pull/23115

**Comment by bradcray** [comment]
🎵 "Did you ever know that you're my hero..." 🎵

**Comment by lydia-duncan** [comment]
@stonea - we can close this issue now, right?

**Comment by stonea** [comment]
> @stonea - we can close this issue now, right?

Yep, submitted in: https://github.com/chapel-lang/chapel/pull/23115
