### ISSUE TITLE
`private module` observed through `use`

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#18257]
Bug. `ExternalLib1.Details` is `private`, but `use ExternalLib1` seems to incorrectly put the symbol into the current unqualified scope even though it can't be accessed. This creates a conflict with a same-named module that was intended to be accessed.

```chapel
module ExternalLib1 {
  private module Details {}
}

// My library's implementation details.
module Details {
  proc do_my_impl() {}
}

module SomeOtherFile {
  proc main() {
    {
      use ExternalLib1;
      import Details;
      Details.do_my_impl(); // compile-error
    }
    {
      import ExternalLib1; // Okay
      import Details;
      Details.do_my_impl();
    }
  }
}
```
```terminal
chpl version 1.25.0 pre-release (aa8f9f979)
In function 'main':
error: Symbol 'do_my_impl' undeclared in module 'Details'
```

To work around the issue,
- change `use ExternalLib1` to `use only` or `import` (as in the follow-on code block)
- reverse the import order and bring `Details` in before `ExternalLib1`

Future: test/visibility/private/moduleSymbols/importPrivateSubmodule.chpl, added in #18277

**Comment by lydia-duncan** [comment]
Yeesh.  I don't think it always behaved this way and I'm honestly surprised there wasn't a test already to prevent it.  Thanks for reporting!

**Comment by lydia-duncan** [comment]
My expectation would have been that it would have seen the private module first, tucked it away and ignored it (or yelled because that was the closest version)
