### ISSUE TITLE
Should the type `codepointIndex` be deprecated?

### ISSUE THREAD

**Issue by arezaii** [chapel-lang/chapel#18265]
During module review we decided to explore the impact of removing the `codepointIndex` type. 

This type is used within the `string` module, and string documentation indicates that:

> Passing a codepointIndex has the same behavior as passing an integral type. See `this` for an example.

We would like to open discussion W.R.T removing `codepointIndex` and simply using integral types for most cases, or `byteIndex` if speed is the primary concern.

Are you using `codepointIndex` in your code? Would you notice or care if it went away?

**Comment by lydia-duncan** [comment]
We decided to keep this after discussion, closing
