### ISSUE TITLE
Add unstable warning to string and byte `.c_str()` method

### ISSUE THREAD

**Issue by arezaii** [chapel-lang/chapel#18266]
Review of the string and bytes modules brought up a point about the `.c_str()` method and how it relates to the broader issue of C interoperability. 

The idea is that when discussion around #18016 is resolved, we may be able to do away with `.c_str()` and rely on a common `c_ptrTo()` or similar method. 

This issue is here to:
- [x] Add an unstable warning to the `.c_str()` method

and track any conversation specific to the possible deprecation of `.c_str()` in favor of something more universal, as discussed in #18016

**Comment by bradcray** [comment]
> we may be able to do away with .c_str() and rely on a common c_ptrTo() or similar method.

A benefit to this that appealed to me was that it seems to avoid questions about whether Chapel `string` (a built-in type) should support a method that returned a `c_ptr` (a module-supplied type) or whether we should make this a tertiary method in a `CTypes`, `CInterop` module (my preference, though some aren't crazy about tertiary methods in general, or in standard modules specifically).

**Comment by arezaii** [comment]
When implementing the warnings, I found that we make extensive use of `string.c_str()` internally, which causes a lot of unnecessary output when a user compiles with `--warn-unstable`. It's been suggested by @mppf that we wait until we have a replacement in place and have changed our internal code to use the replacement, then move directly to deprecating `string.c_str()`, rather than adding the unstable warning at this time. 
Unless there is strong opposition to this plan, I would propose delaying this task until we have a plan for `c_str()`'s replacement.

**Comment by bradcray** [comment]
Looking at this a year later, and having heard similar things from other efforts, I'm wondering:
* Can we squash unstable warnings for our modules by default?  (https://github.com/chapel-lang/chapel/issues/20541)
* If not, can we have a non-documented `c_str()` replacement and use that in our modules instead of the public/warning-generating version?

**Comment by bradcray** [comment]
Since my earlier comment today, I re-read #18016 and am wondering whether we should focus there first since, if we could resolve it, we could potentially just deprecate `.c_str()` rather than needing to mark it unstable (not that I'm looking for more excuses for us to put off #20541, which I think would be a valuable change).

**Comment by arezaii** [comment]
In the process of deprecating `c_string` I have found myself longing for the simplicity of `.c_str()` and would like to suggest we move it to the `CTypes` module as a tertiary method on `String`/`Bytes` and mark it unstable until we get the localize and null terminate functionality designed. 

My reasoning is that it seems like the most appropriate place for it to be defined, and having a convenient way to return a `c_ptrConst(c_char)` is quite important, as that is the most common need when trying to match a C signature for `const char*`. 
While we can't guarantee that every string created in Chapel is null terminated, in practice, our string buffers almost always are.
Also, I believe that the motivation for deprecating `.c_str()` is contained in this thread and I read it today as more of a "it might be nice to ..." rather than "we really should ...". It also seems like some of the attention `.c_str()` got was because of its location in `String`/`Bytes`, and this would force a user to bring in `CTypes` to do `.c_str()`, which I think makes sense.

**Comment by mppf** [comment]
> *edit2: One issue with this idea is that during the deprecation of `c_string` it creates ambiguity between `.c_str()` that returns a `c_string` and the one I'm proposing here. One option is to utilize a compiler flag to opt into the new method, similar to how we opt into the new behavior of `c_ptrTo` for strings. Another option would be to use a different name entirely (maybe `asConstCharPtr`), or change it from being a tertiary method to a procedure in `CTypes`

I would think that `c_ptrConst(c_char)` and `c_string` are the same type, and as a result you could just update the return type of `.c_str()`. Or if they are different types, maybe we could implicitly convert between them?

If the `c_string` deprecation requires some compiler flag to opt in, maybe we could have the same flag choose between `c_str` versions?

Separately, I'm trying to understand what the alternatives would be. I can think of a few:
 * If we have in mind to make changes to `.c_str`, why not make it unstable where it is?
 * Is it realistic to try to build the new feature for the Fall release?

**Comment by bradcray** [comment]
I like [this proposal](https://github.com/chapel-lang/chapel/issues/18266#issuecomment-1633318802) and it's the sort of thing I'd do as well, but I remain unclear on how we can pursue it without deciding on some of the tough challenges around nil termination and ownership of the buffer.  Specifically, it seems that even while it is an unstable feature, we'd need to take a stance on who is responsible for cleaning up any new buffer that's created (or assert that no new buffer is created and ensure that any strings it's applied to are already null-terminated?).

**Comment by bradcray** [comment]
Your questions are ones I chew on as well.  I guess my general concern is that if we don't have a well-established way to pass `const char*` to C routines that expect NULL-terminated strings in the 2.0 timeframe (or even a plan/story for what we're going to build longer-term), that it will be considered a pretty major lack in the language.  So while I think you're technically right that we could just mark it as unstable, I worry that might be considered a reason that we're not 2.0-ready, particularly if unstable warnings are on by default.

In the category of "usually does in practice", I also worry about [this case](https://ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuhY37UqLUxWcQyoLUoutubhSK0pSi_IUCoryk4FEZl5JmkaFJlAcylbySM3JyVfwzQQakpqjqKRpDTEFahjMUAA):

```chapel
use CTypes;

extern proc printf(x);

printf("Hello Michael!");
```

which doesn't include an explicit call to `.c_str()` but works today and would be nice to have continue working.  Yet it's hard to rationalize why it works / how it would in a 2.0 timeframe.

**Comment by mppf** [comment]
> In the category of "usually does in practice", I also worry about [this case](https://ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuhY37UqLUxWcQyoLUoutubhSK0pSi_IUCoryk4FEZl5JmkaFJlAcylbySM3JyVfwzQQakpqjqKRpDTEFahjMUAA):

That's handled by a special case in `ResolutionCandidate::computeSubstitution` and we can do that either way. The compiler code implementing it only fires for string literals. IMO the main concern with that continuing to work is that it implies that `extern` means "for interoperability" but in previous discussions I've understood that isn't necessarily what we need or want (i.e., it wouldn't make sense to do this if the `extern proc` were somehow referring to a compiled Chapel library). That said, I'm comfortable declaring that `extern` and `export` are for interoperability.



> Your questions are ones I chew on as well. I guess my general concern is that if we don't have a well-established way to pass `const char*` to C routines that expect NULL-terminated strings in the 2.0 timeframe (or even a plan/story for what we're going to build longer-term), that it will be considered a pretty major lack in the language. So while I think you're technically right that we could just mark it as unstable, I worry that might be considered a reason that we're not 2.0-ready, particularly if unstable warnings are on by default.

I agree that being able to do this is convenient and useful, but I think it would be OK if we never provided a way to do that. (You would have to pass pointer + length to C functions; or else manually construct a `const char*` copy).

> or even a plan/story for what we're going to build longer-term

I'm pretty happy with the direction of using a `manage` statement for it, see https://github.com/Cray/chapel-private/issues/5017#issuecomment-1614910681 . This is already implemented (in a prototype way) and AFAIK the main barrier there is completing the design review on it.

**Comment by bradcray** [comment]
Michael, I was mulling over your previous response about marking `.c_str()` unstable (before seeing your most recent comment) and had a follow-up question:  Is your expectation that we would not only mark it unstable (in the "this may change or go away" sense), but also document it as not particularly guaranteeing anything?  (i.e., it'll return a `c_ptrConst(c_char)` to your string and you won't need to manage the memory, but you can't really be guaranteed anything about it, like that it's NULL-terminated).  And if so, is that any different than `c_ptrTo()` for strings?  (and if not, does that suggest just deprecating `c_str()` rather than marking it as unstable?

**Comment by mppf** [comment]
> Is your expectation that we would not only mark it unstable (in the "this may change or go away" sense), but also document it as not particularly guaranteeing anything? 

Yes, we could document that it is unstable, and the string returned is not necessarily null terminated in the right place, but it usually is.

> And if so, is that any different than `c_ptrTo()` for strings? (and if not, does that suggest just deprecating `c_str()` rather than marking it as unstable?

It is different from deprecating `c_str()` and having code use `c_ptrTo()` for two reasons:
 1. `.c_str()` has been working for a lot of cases (despite the various issues) and so code using it can continue using it for now. Leaving it unstable will avoid changing that code twice -- it can go directly from `.c_str()` to whatever the replacement is that handles localizing and null-terminating.
 2. `c_str()` might return a different type from `c_ptrTo()`. `c_ptrTo(myString)` and `c_ptrToConst(myString)` return `c_ptr(c_uchar)` and `c_ptrConst(c_uchar)`, respectively. In contrast, `c_str()` will return whatever the replacement for `c_string` is, which I expect will be `c_ptrConst(c_char)`, which will be the same type or a different type depending on if `char` is signed or unsigned. (See also PR #22622). (FWIW, I'm not very confident in our choices here with the two differing in terms of `c_uchar` vs `c_char`.)

**Comment by arezaii** [comment]
https://github.com/chapel-lang/chapel/pull/22622 adds the unstable warning to `.c_str()` to satisfy the original request in the OP

**Comment by arezaii** [comment]
https://github.com/chapel-lang/chapel/pull/23220 creates `c_str()` as unstable, tertiary methods that live in `CTypes` and marks the `c_str()`s in `string`/`bytes` as deprecated. 

That should (finally) satisfy the OP.
