### ISSUE TITLE
Try running GPU example on different machines

### ISSUE THREAD

**Issue by stonea** [chapel-lang/chapel#18283]
We're able to run all the `gpu/native` tests on Osprey. Just to make sure that we haven't hardcoded anything making it Osprey specific, I want to verify that these will work on another machine with NVIDIA GPUs.

**Comment by ronawho** [comment]
Just FYI when we first added GPU testing I was able to run on the GPUs nodes of jupiter. https://github.com/Cray/chapel-private/issues/1082 has generic jupiter instructions for running on non-GPU nodes. I think the only difference for running on GPU nodes is loading `cudatoolkit` and I needed to use a different `CHPL_LAUNCHER_CONSTRAINT`. I think https://github.com/chapel-lang/chapel/pull/17145 has instructions I used before.

**Comment by stonea** [comment]
After fiddling around a bit I'm able to get Chapel generated GPU code to work on Jupiter.   Some changes I had to hack to get this to work:

* I have to modify `runtime/make/Makefile.runtime.include` to use `opt/nvidia/cudatoolkit10.2/10.2.89_3.28-7.0.1.1_2.1__g88d3d59/include` as the path to the cuda include files rather than `/usr/local/cuda/include`
* I had to modify `ptxCmd` and `fatbinaryCmd` in `clangUtil.cpp` to use `sm_35` and `compute_35` rather than `sm_60` and `compute_60`
  * It looks like Jupiter uses GPUs that use CUDA Compute Capability 3.5 rather than 6.0
* I set the following environmental variables:
  * `export CHPL_LAUNCHER_CORES_PER_LOCALE=1`
  * `export CHPL_RT_NUM_THREADS_PER_LOCALE=1`
  * `export CHPL_LAUNCHER_CONSTRAINT=K20XIV10`

I've also run into issues using start_test to try and run our demo:

`chpl dependencies are missing - try make test-venv`

If I execute `make test-venv` I get a bunch of errors referring to missing Python modules.
<details>
<pre>
...
    ERROR: Command errored out with exit status 1:
     command: /lus/scratch/stonea/chapel/third-party/chpl-venv/build/build-venv/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/lus/scratch/tmp/pip-install-60tpgkm3/pycparserext_0f565901a9e146978e06924d56118aaa/setup.py'"'"'; __file__='"'"'/lus/scratch/tmp/pip-install-60tpgkm3/pycparserext_0f565901a9e146978e06924d56118aaa/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /lus/scratch/tmp/pip-pip-egg-info-ucqgr6e4
         cwd: /lus/scratch/tmp/pip-install-60tpgkm3/pycparserext_0f565901a9e146978e06924d56118aaa/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/lus/scratch/stonea/chapel/third-party/chpl-venv/build/build-venv/lib64/python3.6/site-packages/setuptools/__init__.py", line 15, in <module>
        from six import PY3, string_types
    ModuleNotFoundError: No module named 'six'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/be/30/7efc7ef861db3d5b3f0434efc5035cc11eeab5d3f41c3ffa7c67c08ddd22/pycparserext-2020.1.tar.gz#sha256=58b6e69e8f20138c853c23f1cfcc18904b7088cdeefe44da661c9b644918da56 (from https://pypi.org/simple/pycparserext/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pycparserext-2019.1.tar.gz (9.4 kB)
    ERROR: Command errored out with exit status 1:
     command: /lus/scratch/stonea/chapel/third-party/chpl-venv/build/build-venv/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/lus/scratch/tmp/pip-install-60tpgkm3/pycparserext_2f71131c3cec4a0c8de1dbab12f96f74/setup.py'"'"'; __file__='"'"'/lus/scratch/tmp/pip-install-60tpgkm3/pycparserext_2f71131c3cec4a0c8de1dbab12f96f74/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /lus/scratch/tmp/pip-pip-egg-info-t0hz7vw2
         cwd: /lus/scratch/tmp/pip-install-60tpgkm3/pycparserext_2f71131c3cec4a0c8de1dbab12f96f74/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/lus/scratch/stonea/chapel/third-party/chpl-venv/build/build-venv/lib64/python3.6/site-packages/setuptools/__init__.py", line 15, in <module>
        from six import PY3, string_types
    ModuleNotFoundError: No module named 'six'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/3e/58/7a4b37732315d47512a33a6a162a8c5fb211f7b7ba237da8b85f80ed93d4/pycparserext-2019.1.tar.gz#sha256=06d1f72d3ac51d9669341fbf1a516f010bdd2148611c37379afceb716447b991 (from https://pypi.org/simple/pycparserext/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pycparserext-2016.2.tar.gz (8.6 kB)
    ERROR: Command errored out with exit status 1:
     command: /lus/scratch/stonea/chapel/third-party/chpl-venv/build/build-venv/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/lus/scratch/tmp/pip-install-60tpgkm3/pycparserext_de6050f99b324252b2ef900954cae547/setup.py'"'"'; __file__='"'"'/lus/scratch/tmp/pip-install-60tpgkm3/pycparserext_de6050f99b324252b2ef900954cae547/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /lus/scratch/tmp/pip-pip-egg-info-dhc7og1e
         cwd: /lus/scratch/tmp/pip-install-60tpgkm3/pycparserext_de6050f99b324252b2ef900954cae547/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/lus/scratch/stonea/chapel/third-party/chpl-venv/build/build-venv/lib64/python3.6/site-packages/setuptools/__init__.py", line 15, in <module>
        from six import PY3, string_types
    ModuleNotFoundError: No module named 'six'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/c5/7f/dfce1acc78177b232c8388c8d0a8e7cd782a26c647095c5530043c1702bc/pycparserext-2016.2.tar.gz#sha256=fd04164f39f3af8704d2f537b7931e0c86d26ae4efe4b16fecde2ed8519045b7 (from https://pypi.org/simple/pycparserext/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pycparserext-2016.1.tar.gz (8.1 kB)
    ERROR: Command errored out with exit status 1:
     command: /lus/scratch/stonea/chapel/third-party/chpl-venv/build/build-venv/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/lus/scratch/tmp/pip-install-60tpgkm3/pycparserext_394eabcfc1434e71b54d9e128d395165/setup.py'"'"'; __file__='"'"'/lus/scratch/tmp/pip-install-60tpgkm3/pycparserext_394eabcfc1434e71b54d9e128d395165/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /lus/scratch/tmp/pip-pip-egg-info-aspxitxx
         cwd: /lus/scratch/tmp/pip-install-60tpgkm3/pycparserext_394eabcfc1434e71b54d9e128d395165/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/lus/scratch/stonea/chapel/third-party/chpl-venv/build/build-venv/lib64/python3.6/site-packages/setuptools/__init__.py", line 15, in <module>
        from six import PY3, string_types
    ModuleNotFoundError: No module named 'six'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/8c/71/2553eef8cd9b2e497824ae31f674afda79d47800f51cbef68b2386d6de59/pycparserext-2016.1.tar.gz#sha256=5851c131aa999e9297ee6881e7911027d7bf126b7a5f9c1c7d7b8884ff29dc7a (from https://pypi.org/simple/pycparserext/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pycparserext-2015.1.tar.gz (7.4 kB)
    ERROR: Command errored out with exit status 1:
     command: /lus/scratch/stonea/chapel/third-party/chpl-venv/build/build-venv/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/lus/scratch/tmp/pip-install-60tpgkm3/pycparserext_576ba44688ca4408baada67b5fd267f1/setup.py'"'"'; __file__='"'"'/lus/scratch/tmp/pip-install-60tpgkm3/pycparserext_576ba44688ca4408baada67b5fd267f1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /lus/scratch/tmp/pip-pip-egg-info-gzmw8hrj
         cwd: /lus/scratch/tmp/pip-install-60tpgkm3/pycparserext_576ba44688ca4408baada67b5fd267f1/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/lus/scratch/stonea/chapel/third-party/chpl-venv/build/build-venv/lib64/python3.6/site-packages/setuptools/__init__.py", line 15, in <module>
        from six import PY3, string_types
    ModuleNotFoundError: No module named 'six'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/91/b0/00047de6b14b16f43aca4225f2629d99fcac83f83b1a39947b068c45f514/pycparserext-2015.1.tar.gz#sha256=f4ea9d62480fc025e9cae0ad8a1038fce64dccab360888243ce537fd39fd2cee (from https://pypi.org/simple/pycparserext/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pycparserext-2013.2.tar.gz (7.2 kB)
    ERROR: Command errored out with exit status 1:
     command: /lus/scratch/stonea/chapel/third-party/chpl-venv/build/build-venv/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/lus/scratch/tmp/pip-install-60tpgkm3/pycparserext_b9ee8fc2484b483abd3228ea4d84a012/setup.py'"'"'; __file__='"'"'/lus/scratch/tmp/pip-install-60tpgkm3/pycparserext_b9ee8fc2484b483abd3228ea4d84a012/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /lus/scratch/tmp/pip-pip-egg-info-sl0swk_d
         cwd: /lus/scratch/tmp/pip-install-60tpgkm3/pycparserext_b9ee8fc2484b483abd3228ea4d84a012/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/lus/scratch/stonea/chapel/third-party/chpl-venv/build/build-venv/lib64/python3.6/site-packages/setuptools/__init__.py", line 15, in <module>
        from six import PY3, string_types
    ModuleNotFoundError: No module named 'six'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/9a/04/1a3b2c028ce0d83a66e2fd2e30d7ada521c357311cf4af3483d1170aa255/pycparserext-2013.2.tar.gz#sha256=c436bea37ddc7bafa34fae3a510465ac1ae32807f3c1e8891039845953c95096 (from https://pypi.org/simple/pycparserext/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pycparserext-2013.1.tar.gz (11 kB)
    ERROR: Command errored out with exit status 1:
     command: /lus/scratch/stonea/chapel/third-party/chpl-venv/build/build-venv/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/lus/scratch/tmp/pip-install-60tpgkm3/pycparserext_fd6dd0b1c2be4227bf69472bc91aacdc/setup.py'"'"'; __file__='"'"'/lus/scratch/tmp/pip-install-60tpgkm3/pycparserext_fd6dd0b1c2be4227bf69472bc91aacdc/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /lus/scratch/tmp/pip-pip-egg-info-kuoukpdy
         cwd: /lus/scratch/tmp/pip-install-60tpgkm3/pycparserext_fd6dd0b1c2be4227bf69472bc91aacdc/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/lus/scratch/stonea/chapel/third-party/chpl-venv/build/build-venv/lib64/python3.6/site-packages/setuptools/__init__.py", line 15, in <module>
        from six import PY3, string_types
    ModuleNotFoundError: No module named 'six'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/a3/8b/dc133d491b38bca95bb389ef1d32d00a27492819026489df968a38a6c387/pycparserext-2013.1.tar.gz#sha256=96cbeda695258a2be2ad37bbd55c8011193e18a42396cc05a23efa940dafd2d9 (from https://pypi.org/simple/pycparserext/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pycparserext (from versions: 2013.1, 2013.2, 2015.1, 2016.1, 2016.2, 2019.1, 2020.1)
ERROR: No matching distribution found for pycparserext
make[2]: *** [Makefile:70: /lus/scratch/stonea/chapel/third-party/chpl-venv/install/chpldeps/__main__.py] Error 1
make[1]: *** [Makefile:85: test-venv] Error 2
make: *** [Makefile:111: third-party-test-venv] Error 2
</pre>
</details>

**Comment by bradcray** [comment]
The `chpl dependencies are missing - try make test-venv` message is standard for any fresh installation of Chapel (e.g., you must've done it in your main repos that you work from, but just forgotten if it seems unfamiliar?).

The nightly testing we do relies on `start_test` on XC systems I'm almost certain, so there must be a way to get this working (where I'm personally hopeless at debugging Python environment issues).  @ronawho and @gbtitus have the most experience running on XCs, though I don't know how much they rely on `start_test` when doing so.

**Comment by ronawho** [comment]
I use paratest/start_test a lot on jupiter and I was able to do a `make test-venv` just now. @stonea do you have anything in a ` ~/.pip/` directory?

And can you get the output for:
```
which python3
python3 --version
```

**Comment by stonea** [comment]
I'm going to move the discussion over to: https://github.com/Cray/chapel-private/issues/2480
