### ISSUE TITLE
Stop communicating from read-only memory

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#18284]
Currently, things like our string literals are placed on read-only memory and that has caused a number of issues:
 - https://upc-bugs.lbl.gov/bugzilla/show_bug.cgi?id=3338
 - https://upc-bugs.lbl.gov/bugzilla/show_bug.cgi?id=4009
 - https://upc-bugs.lbl.gov/bugzilla/show_bug.cgi?id=4008 / #18245
 - https://upc-bugs.lbl.gov/bugzilla/show_bug.cgi?id=4046
 - https://upc-bugs.lbl.gov/bugzilla/show_bug.cgi?id=4179

We've also been seeing issues when trying to experiment with gasnet-ibv segment everything that we believe are caused by doing GETs from read-only memory.

Some of these issues have been in gasnet, but others are lower in the software stack. We're the only gasnet client that communicates from read-only memory and I'm starting to think we should just stop doing that.

**Comment by ronawho** [comment]
Here's a prototype I was using to copy our literals into new strings. This seems to help for the gasnet-everything case, but I'm not sure if we place anything else in rodata. 

```diff
diff --git a/modules/internal/String.chpl b/modules/internal/String.chpl
index 7c8a1b4dd0..45ffdb5b01 100644
--- a/modules/internal/String.chpl
+++ b/modules/internal/String.chpl
@@ -606,10 +606,13 @@ module String {
     // NOTE: This is a "wellknown" function used by the compiler to create
     // string literals. Inlining this creates some bloat in the AST, slowing the
     // compilation.
-    return chpl_createStringWithBorrowedBufferNV(x:c_ptr(uint(8)),
+    var ret = chpl_createStringWithNewBufferNV(x:c_ptr(uint(8)),
                                                  length=length,
                                                  size=length+1,
                                                  numCodepoints=numCodepoints);
+    // Undiagnosed double-free without this for tests like recordio.chpl
+    ret.isOwned = false;
+    return ret;
   }
 
   /*

```

**Comment by ronawho** [comment]
I believe this is done with https://github.com/chapel-lang/chapel/pull/18307. I added some hooks to warn when we do out-of-segment comm and for all multi-locale tests the only time we do this is when communicating some globals.

**Comment by mppf** [comment]
> the only time we do this is when communicating some globals.

and is that only happening during program start up? (I think so, just checking).

**Comment by ronawho** [comment]
> and is that only happening during program start up? (I think so, just checking).

Correct
