### ISSUE TITLE
Should `OrderedSet` and `OrderedMap` be named `SortedSet` and `SortedMap`?

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#18449]
We have `OrderedSet` and `OrderedMap` package modules that provide `orderedSet` and `orderedMap` data structures that are basically a set and a map, but store the items in a sorted order. To sort the items, their initializers accept a comparator object that is used to compare two items, similar to the routines in the `Sort` module.

However, the word "ordered" can mean that items are stored in the order that they were added, which is not the case.

So, should we rename those modules and the corresponding data structures to make this clear?

**Comment by e-kayrakli** [comment]
Pinging @rapiz1 as the contributor of these data structures, @krishnadey30 and @cassella as the other mentors of the project.

**Comment by rapiz1** [comment]
Makes sense to me.

**Comment by mppf** [comment]
I'd be fine with renaming them to say something like "sorted set" but it is the way I was interpreting "ordered set" already. (But I understand that might confuse someone who wants something that preserves insertion order).

**Comment by bradcray** [comment]
I thought `ordered` meant "preserve iteration order" and had been advertising it as such in the release notes (which may be why you opened this?), so clearly misunderstood the current name.  I believe that `sorted` would not have caused the same misunderstanding for me.
