### ISSUE TITLE
Support sync/single types of non-nilable classes

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#18458]
As a Chapel programmer, I would ideally like to be able to create sync/single variables of
non-nilable class type.  So, effectively:

```chapel
class C {
  var x: int;
}

var s: sync(owned C) = new C(42);
writeln(s.readFF());
```

**Comment by bradcray** [comment]
I took a stab at this in https://github.com/bradcray/chapel/tree/non-nilable-sync-class but ran into an issue
in the readFF() routine (and friends) where we declare a local variable of the sync type that's default initialized,
which causes problems for non-nilables since they don't have defaults.

Reflecting on it further, though, I'm realizing that such sync variables would not be particularly well-defined
in terms of what they would store when "empty".  One solution would be to implement them as nilable
classes in the _synccls() implementation, which would permit them to store `nil` when nobody's looking.
Of course, one could use `readXX()` to abuse the type and peek in on it when it's empty, but we could
arguably make that case halt() or throw an exception when the result would be nil.

So maybe the fix is just to have the `getSyncClassType()` turn any non-nilable classes into nilable, and
then do some casting at return points for that case?

**Comment by mppf** [comment]
@bradcray - I already implemented this in https://github.com/chapel-lang/chapel/pull/18379 -- perhaps you could look at that PR and see if the direction is OK with you?

**Comment by bradcray** [comment]
Sweet!  Reading the PR's OP, the direction generally looks good to me.  The notion of having readXX() be a compiler error rather than what I was proposing here seems attractive.  I almost started arguing "but what if I really wanted to do a `readXX()` because I was convinced it was going to be valid?" but I suppose I should just use a `readFF()` in that case and all will be fine and that getting a halt() isn't really attractive compared to a compiler error.  I suppose it might prevent some sort of generic programming situation, but let's consider that case if/when it actually comes up.
