### ISSUE TITLE
chpldoc doesn't render return intents very well

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#18469]
Currently, chpldoc seems to render return intents immediately after a procedure's argument list with no spaces (either between the arguments and return intent, or within the return intent itself).  This seems incorrect and looks a bit sloppy:

<img width="700" alt="Screen Shot 2021-09-27 at 11 54 04 AM" src="https://user-images.githubusercontent.com/7536222/134968057-ec16d6df-e8b1-4a7d-a749-189ac96689a9.png">

https://chapel-lang.org/docs/1.25/builtins/ChapelArray.html#ChapelArray.targetLocales

[it seemed likely that an existing issue already mentions this, but I didn't see one]

**Comment by lydia-duncan** [comment]
Huh.  It looks like the problem doesn't exist for Firefox but does for Chrome.  This is probably a Sphinx or readthedocs issue

**Comment by bradcray** [comment]
Oh, that's interesting and didn't occur to me (that it could be browser-specific).

Here's the raw html:

```html
targetLocales</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span> <span class="pre">const</span> <span class="pre">ref</span>
```

**Comment by lydia-duncan** [comment]
This seemed pretty harmless, but a user just ran into a case where it wasn't - paren-less functions.  Specifically, looking at the documentation for `INFINITY` with this bug tricked them into thinking it was called `INFINITYparam`

**Comment by lucaferranti** [comment]
yes I was looking for `Math.INFINITY` documentation and on chrome it was displayed as follows

![image](https://user-images.githubusercontent.com/49938764/172230845-443c0537-be8a-4d36-80b5-06e5a4edf1e1.png)

the source html is

```html
<dt class="sig sig-object chpl" id="Math.INFINITY">
  <em class="property">
    <span class="pre">proc</span>
  </em>
  <span class="sig-name descname">
    <span class="pre">INFINITY</span>
  </span>
  <span class="pre">param:</span>
  <span class="pre">real(64)</span>
  <a class="headerlink" href="#Math.INFINITY" title="Permalink to this definition">¶</a>
</dt>
```

that was looking like the name was INFINITYparam, which was pretty strange so at some point I had come to the erroneous conclusion that the doc entry was a typo and was supposed to be `param INFINITY`.

If I had to throw a wild guess, my first try would be to start from the css of the classes `sig-name` and `descname`, but might be far fetched.

**Comment by lucaferranti** [comment]
changing in the chrome console the above mentioned html to
```html
<dt class="sig sig-object chpl" id="Math.INFINITY">
  <em class="property">
    <span class="pre">proc</span>
  </em>
  <span class="sig-name descname">
    <span class="pre">INFINITY</span>
  </span>
  <span class="sig-name descname">
    <span class="pre">param:</span>
  </span>
  <span class="pre">real(64)</span>
  <a class="headerlink" href="#Math.INFINITY" title="Permalink to this definition">¶</a>
</dt>
```

seems to fix the problem, but that's automatically generated html, not sure how easy it is to implement that (nor that it's the correct way to fix it)

![image](https://user-images.githubusercontent.com/49938764/172233495-5441942a-0cfc-4147-b2d6-c11b049220bd.png)

**Comment by bradcray** [comment]
Nice find, Luca!  I'd tried to brave looking at the generated rst at one point, but didn't see anything obviously wrong, and didn't think to look at the html.  My guess is that there's something within our [sphinx support](https://github.com/chapel-lang/sphinxcontrib-chapeldomain) which mis-attributes the `param` keyword, though I'm not savvy enough about sphinx without learning more to know just what.  It does seem suspicious, though, that it is given the same decorators as the `INFINITY` identifier itself.

**Comment by jabraham17** [comment]
This will be fixed after merging https://github.com/chapel-lang/sphinxcontrib-chapeldomain/pull/88 and https://github.com/chapel-lang/chapel/pull/24517
