### ISSUE TITLE
I/O module: Consistency between use of + and - in format strings

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#18495]
One might expect `%-6i` and `%+6i` to influence similar parts of the formatted string output, given that `+` and `-` are generally paired.

However, `%-6i` influences whether the padded integer is left or right justified, e.g. whether the result is 
`5_____` versus `_____5` ("_" inserted to maintain blank spaces on Github).  Meanwhile, `%+6i` influences whether positive numbers are printed with a preceding `+`, e.g. `_____5` versus `____+5`

Both pieces of functionality are useful, and individually it makes sense that each means what it does, but taking a big picture stance it seems a little odd that `-` and `+` influence separate, unrelated things.  Are there better symbols to use for one or the other?

**Comment by lydia-duncan** [comment]
I realized we didn't have a slide covering this for discussion, and in the process of making one have looked up additional language behavior.  Putting it here for posterity:

- We get this behavior from C ([source](https://linux.die.net/man/3/printf))
- Rust uses `<`, `^` and `>` like Python does, doesn't provide `-`, and `+` indicates that the sign should be printed ([source](https://doc.rust-lang.org/std/fmt/))
- Julia provides a library that just does C's printf.  It's not clear to me if there are other format strategies in Julia ([source](https://docs.julialang.org/en/v1/stdlib/Printf/))
- Swift doesn't seem to support either of these ([source](https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFStrings/formatSpecifiers.html), linked to from [their string documentation](https://developer.apple.com/documentation/foundation/nsstring/1407827-init))

**Comment by lydia-duncan** [comment]
Correction on the Swift comment: the link provided also links to the [IEEE printf specification](https://pubs.opengroup.org/onlinepubs/009695399/functions/printf.html), so it supports the same behavior as C and Julia.

**Comment by lydia-duncan** [comment]
Prep for an upcoming ad-hoc sub-team discussion:

### 1. What is the API being presented?

`%-6i` influences whether the padded integer is left or right justified, e.g. whether the result is 
`5_____` versus `_____5` ("_" inserted to maintain blank spaces on Github).  Meanwhile, `%+6i` influences whether positive numbers are printed with a preceding `+`, e.g. `_____5` versus `____+5`

This is a bit weird because you'd expect `+` and `-` to impact what is printed in similar ways.

### How is it being used in Arkouda and CHAMPS?

Arkouda does not use `%+` and doesn't use `%-` in format strings itself, it only alters some behavior in the Time compatibility module based on its presence [here](https://github.com/Bears-R-Us/arkouda/blob/9449193c681c0dc558ce98ed0ceaec3c84b49865/src/compat/e-130/ArkoudaTimeCompat.chpl#L1411)

CHAMPS has no uses of `%+` and 33 uses of `%-`

### 2. What's the history of the feature, if it already exists?

It was added with `readf`/`writef` support in 2013 and has mostly been unchanged since then.

### 3. What's the precedent in other languages, if they support it?

We get this behavior from C.  It's part of the IEEE printf specification and Julia and Swift also follow that same pattern.

Python and Rust, however, use `<`, `^` and `>` to influence alignment.  Python uses `+` to indicate the sign of positive and negative numbers should be printed, and `-` to indicate the sign of negative numbers should be printed (though `-` is the default behavior so it doesn't need to be provided).  Rust doesn't provide `-` but uses `+` the same way.  Note that we did use `<` and `>` as format specifiers in Chapel for endianness specification but that we have deprecated that support so using them would be fair game (though we probably should remove the deprecated support for a release or two).

### 4. Are there known Github issues with the feature?

This is difficult to search for, unfortunately, as Github wouldn't even turn up this issue which CLEARLY has `%+` and `%-` in it.  But I don't think there are other issues related to it.

### 5. Are there features it is related to?

It's related to the format type specifiers it impacts.  E.g. `%+i` or `%-16s`

### 6. How do you propose to solve the problem?

Option A. We could leave things as is
  - Pros:
    - Less work
    - Aligns with C, Julia, Swift and the IEEE printf standard, so has strong precedent behind it
  - Cons:
    - The inconsistency could be a bit confusing to new users that haven't had a background in the other languages

Option B. We could remove the deprecated endianness specifiers, replace `%-` with `%<` and add `%^` and `%>` to go with it, following Python and Rust's lead.
  - Pros:
    - Matches Python and Rust (though more Rust since Python still has `-`)
    - No inconsistency between two symbols that are usually paired.
    - Gives more alignment options when fully implemented
  - Cons:
    - Differs from C, Julia, Swift and the IEEE printf standard
      - But we don't perfectly follow them to begin with for other format specifiers
    - Probably should remove the deprecation for a release or two to be safe, which would be tight timeline-wise

Option C. We could deprecate `%-` and/or `%+` in favor of an argument to the format call itself.
  - Pros:
    - No inconsistency between two symbols that are usually paired
    - Could give more alignment options
  - Cons:
    - Differs from all 5 languages and the IEEE printf standard
    - Would probably result in more granular `writef` calls, though we could mitigate that somewhat if we allow the new argument(s) to apply to all `%` replacements, which CHAMPS could benefit from in a couple of places.

Option D. We could deprecate `%-` and/or `%+` in favor of a Serializer/Deserializer that gives their equivalent behavior.
  - Pros:
    - No inconsistency between two symbols that are usually paired
    - Could give more alignment options
  - Cons:
    - Differs from all 5 languages and the IEEE printf standard
    - Would probably result in more granular `writef` calls when you want to mix and match, though there are some calls in CHAMPS that would be able to stay unchanged and benefit from it.
    - This is probably the option that involves the most work, due to writing a full serializer/deserializer
      - Though if someone wanted to include that in one of their personalized serializer/deserializer, they would have an easy template to do so.

I would prefer option B.  I'd be open to C and D, but dislike A (though I'd accept it).

**Comment by lydia-duncan** [comment]
In our ad-hoc sub-team meeting today, we decided to follow option B by a strong margin.  In a prior IO sub-team discussion, we convinced ourselves that it was okay to not have an intervening release where `%<` was not possible as its old behavior has been deprecated for a year without complaint.

**Comment by lydia-duncan** [comment]
In [this comment from Damian](https://github.com/chapel-lang/chapel/issues/19016#issuecomment-1643267204), he mentions we don't indicate that reals support `%+` in our documentation but that they do.  This seems worth a documentation update

**Comment by bradcray** [comment]
The change in @jeremiah-corrado's #22969 escaped me until now, but I really like the mnemonics of `%<`, `%^`, and `%>` for justification!  (realizing as I scan the issue that we don't get the credit for inventing them... :) )
