### ISSUE TITLE
I/O module: deprecate binary conversions in format strings 

### ISSUE THREAD

**Issue by jhh67** [chapel-lang/chapel#18503]
Chapel format strings currently allow writing arguments in binary. This adds to the excessive complexity of the format strings. In particular, it confuses the goals of format strings since they would be simpler to explain if they are only about text formatting. This format string functionality should be deprecated and replaced with channel methods that implement the same functionality, e.g. `writeBigEndian()`.

**Comment by lydia-duncan** [comment]
This is listed as done in the IO module slides - John, should it be closed?
