### ISSUE TITLE
Internal compiler error because of _wide_make

### ISSUE THREAD

**Issue by twesterhout** [chapel-lang/chapel#18511]
### Summary of Problem

Trying to use `_wide_make` results in internal error.

### Steps to Reproduce

**Source Code:**

```chapel
use CPtr;
use SysCTypes;

export record WidePtr {
  var ptr: c_void_ptr;
  var loc: chpl_localeID_t;
}

class Foo {
  var bar: int;
}

export proc create(ref widePtr: WidePtr, bar: int) {
  var foo = new unmanaged Foo(bar);
  widePtr.ptr = __primitive("_wide_get_addr", foo);
  widePtr.loc = __primitive("_wide_get_locale", foo);
}

proc toFoo(ref widePtr: WidePtr) {
  return __primitive("_wide_make", unmanaged Foo, widePtr.loc, widePtr.ptr);
}

export proc destroy(ref widePtr: WidePtr) {
  var foo = toFoo(widePtr);
  delete foo;
}
```

**Compile command:** `chpl -o error error.chpl`

### Configuration Information

- Output of `chpl --version`: 1.24.1
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: unknown
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: smp *
  CHPL_GASNET_SEGMENT: fast
CHPL_TASKS: qthreads
CHPL_LAUNCHER: smp
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_REGEXP: re2
CHPL_LLVM: none
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: gcc 10.3.0

The idea of this whole procedure is to be able to export `Foo` to C as an opaque struct (in the simple example above this could've been achieved with extern record, but I'm interested in a more general case which (currently) cannot be handled by extern record).

Pinging @bradcray, because this issue was discovered after our conversation on Gitter. The only difference with the [code you provided](https://matrix.to/#/!PBYDSerrfYujeStENM:gitter.im/$9oAZwRdLpdDTUgGvPUzqqnJmAZD80T2vJoH3-ZKHk5o?via=gitter.im&via=matrix.org) on Gitter is that I'm storing both pointer and locale id in a struct, rather than storing locale id in a global variable.

**Comment by twesterhout** [comment]
As a workaround, rewriting `toFoo` as follows fixes the problem:
```
proc toFoo(ref widePtr: WidePtr) {
  const loc = widePtr.loc;
  return __primitive("_wide_make", unmanaged Foo, loc, widePtr.ptr);
}
```

**Comment by mppf** [comment]
@twesterhout - yes, I just arrived at the same conclusion.

I wrote

``` chapel
proc toFoo(ref widePtr: WidePtr) {
  var loc = widePtr.loc;
  var ptr = widePtr.ptr;
  return __primitive("_wide_make", unmanaged Foo, loc, ptr);
}
```

As it stands though these primitives aren't really user-facing and we need some a more supportable API for this functionality. (Not sure if there is an issue about that).

Anyway, in the meantime, I've created #18514 to fix this problem specifically, which I plan to merge if testing is OK.

**Comment by bradcray** [comment]
Semi-related to this issue:  In my original draft of the solution I posted to gitter that led to this code, I tried just using `here.id` or `here` in the locale field of the `"wide_make"` field, but neither seemed to work (generating internal errors in the compiler, IIRC).  I was short on time that day, so rather than trying to understand better what the primitive was looking for and why neither of those expressions worked (where I'd expected the first to), I just lamely captured the value in a global variable as Tom notes, and hoped to come back to it later.

@mppf, I'm curious whether you think your PR would also enable `here.id` to work or, if not, whether it's more obvious to you than it was to me why it didn't.

**Comment by mppf** [comment]
@bradcray - I don't think that PR would make `here.id` work. I think the problem there is that the primitive is expecting something of type `chpl_localeID_t` but `here.id` is an `int`. These kind of things are pretty easy to solve though if we actually create a real API for this functionality (because we can update the module code implementing it to call the primitive the way the compiler likes while accommodating a few different patterns that come up like wanting to use `here.id` or any integral locale ID).

**Comment by mppf** [comment]
@twesterhout - if you need to use the workaround, I think that making temporaries for both components as in https://github.com/chapel-lang/chapel/issues/18511#issuecomment-933525699 is important. If you can use `main`, I will get your original code working soon with my PR.

**Comment by twesterhout** [comment]
@mppf thanks for the quick response! I don't have anything against the workaround at the moment, but have no trouble switching to main if need arises.
What I could gather from your PR is that primitives in Chapel take something like universal references in C++ (`T&&`) rather than actual values (`T`). In other words, `_wide_make` is not declared internally as something like `proc _wide_make(type, loc: chpl_localeID_t, ptr: c_void_ptr)` such that when I passed `widePtr.loc` to it the reference-to-value conversion didn't happen. Does what I'm saying make sense and is my understanding correct?

@bradcray I also wanted to use `here` locale but didn't immediately find a function which could convert locale ID (`int`) to `chpl_localeID_t`. Functions which I saw required both node ID and index on node, and I'm not sure how locale ID maps to those (and this is probably an implementation detail which I shouldn't rely upon).

**Comment by mppf** [comment]
@twesterhout - yeah, I think you understand it correctly (the primitive implementation was getting confused by the use of the reference).

> I also wanted to use here locale but didn't immediately find a function which could convert locale ID (int) to chpl_localeID_t.

https://github.com/chapel-lang/chapel/blob/8741da4159401da7a363f66831f495f614f50985/modules/internal/ChapelLocale.chpl#L127 maybe you can use `here.localeid` and https://github.com/chapel-lang/chapel/blob/8741da4159401da7a363f66831f495f614f50985/modules/internal/ChapelLocale.chpl#L818 shows you could use `chpl_getLocaleID` to get the current one.

All of these are not user facing, and we need some API design to get something that is.
