### ISSUE TITLE
Redesign of GPU locale model

### ISSUE THREAD

**Issue by stonea** [chapel-lang/chapel#18529]
When `CHPL_LOCALE_MODEL=gpu` Chapel will use a locale model where the GPU is accessed using `here.getChild(n)` where n > 0; `here.getChild(0)` will return the locale for the CPU. This means that there is no real difference between `on Locale[i]` and `on Locale[i].getChild[0]`, which is kind of bizarre.

Maybe we should avoid having a sublocale 0 refer to the CPU? Or at least we should change the function to something like: `here.getGpu(0)`?

This also raises interesting questions if we want to have a NUMA aware locale model as well as GPUs (sub)locales. One option would be to have the locale consist of a list of CPU sublocales followed by GPU sublocales. If there's a natural association of GPUs to CPUs we could also imagine having multiple levels to the hierarchy where GPU sublocales could be references form CPU sublocales.

Here's an illustration of these different options:

![image](https://user-images.githubusercontent.com/2591890/136294956-a68c14dc-11c0-4784-8903-8c2065b9bd99.png)

I'm not sure why we have the current design we do, but I imagine it follows from our implementation of wide pointers (see `wide_ptr_s` in `runtime/include/chpltypes.h` and `chpl_localeID_t` in `runtime/include/localeModels/gpu/chpl-locale-model.h') where we specify locales by a node ID and sublocale ID. Of course we can change this design if we want to or we could have the locale interface presented to the user abstract these details away.

## Related work to consider

We also may want to look at \ do something like this locale model for AMD's Accelerated Processing Unit (APU) (see https://github.com/chapel-lang/chapel/pull/7152):

```chpl
on Locale[0].GPU { /* GPU code */ }
```

It might also be worth reviewing the KNL locale model (created in https://github.com/chapel-lang/chapel/pull/5555, later removed in https://github.com/chapel-lang/chapel/pull/15832).

Finally, we have a tech note that discusses the NUMA aware locale model (and compares it to the default flat model): https://chapel-lang.org/docs/technotes/localeModels.html

**Comment by mppf** [comment]
FWIW I have been expecting that a Block array distributed over NUMA sublocales for sockets (what @gbtitus called a "flat" version) will work just fine and give acceptable performance. Here I am imagining that the comm layer will use a faster implementation for comms within a node (like gasnet does with pshm) and I don't think that is too much to ask of the comm layer implementation.

At the higher level though I think we need the locale model to reflect the architecture but only to a degree. The basic reason for that is that I expect diminishing returns for performance from a more detailed model while at the same time the additional detail adds complexity for programming and challenges to portability (across different locale models). Of course these downsides can be somewhat addressed by careful design of:
 a. a strategy that locale models always follow for breaking up resources - e.g. we could say that sibling locales never refer to the same resources - so that diving work among the sibling locales will never oversubscribe something
 b. calls one can make on any locale model to generically get the appropriate resources - e.g. "get the data parallel sublocales"

And those points hopefully bring us back to the question of "How should users working with GPU systems interact with the locale model there?"

**Comment by stonea** [comment]
Hi all,

We've been having a number of internal discussions recently (at least among the developers focusing on GPU support) about locale models.

In terms of the models discussed on this Github issue (or at least the non-numa related ones) we're arriving at a consensus that we prefer the illustration as shown in the upper right (Locale for CPU; sublocales for GPU).  In other words, I'm suggesting we eliminate the illustration as shown in the upper-left (in the original post for this issue) from consideration.  If you do feel that upper-left locale model would be preferable to the upper-right one, please speak up.

**So why eliminate that top-left locale model?**

As of today, (at least in the GPU and NUMA locale models) Chapel allows a task to run on either a locale or sublocale.  What this means is it's perfectly legal to have code run `on Locale[i]` or `on Locale[i].getChild[0]` and if you query `here` under each you would get a different result (one that returns the locale and the other that returns the sublocale).  However, as described in the original problem statement (in today's GPU locale model) there's no real different in terms of execution behavior between the two. This (at least to me and I think to other as well) seems bizarre and confusing.

Given that I think we should eliminate the CPUs sublocale and just use the locale itself for expressing CPU-based computation and doing CPU-local memory management.

I could imagine there being value in a having separate CPUs sublocale if running on the locale itself represented something different (for example: that we should span computation across all the sublocales -- the GPUs and CPUs in tandem).  But this would be pretty different from what it means to run on a locale today (and would likely cause a lot of backwards incompatibility headaches for existing code that does things like `coforall loc in Locales on loc do ...`).

In cases where we would want computation to span across CPUs and GPUs I think other mechanisms\abstractions would be a better approach (like the `GPUIterator` presented in this work: https://github.com/ahayashi/chapel-gpu).

For now, I'll leave aside issue of how this all ought to glue with NUMA aware locale models (though I'm also considering this), but in the meantime please let me know if you do see value in having a separate CPUs sublocale as illustrated in the upper-left diagram.

**Comment by stonea** [comment]
As of 1.27 we've modified the locale models for GPUs to be something akin to what we have in the top-right corner of the illustration I have on the issue summary.

That is to say: top-level locales represent CPUs and sublocales are for GPUs.

We no longer expect `getChild()` to be used as a user-level interface.  Rather all the GPU sublocales are gathered together in a `gpus` array accessible off of a locale.  This means to create a loop that does something on the first GPU of the current node you'd do something like this:

```chpl
on here.gpus[0] {
  foreach i in range do
    // GPUized loop
}
```

To query the number of GPUs on a given locale instead of doing `here.getChildCount()` do `here.gpus.size`

We're also encouraging users to not think of sublocales as representing pieces of hardware but rather as indicating particular policies.

For more details see slides 101 - 108 in the "Ongoing Efforts" slides for the 1.26 release (https://chapel-lang.org/releaseNotes/1.26/06-ongoing.pdf).  Note these slides are somewhat out of date in that we hadn't settled on using a `gpus` array to store gpu sublocales at the time but the broader points about getting rid of `getChild` and having a "conceptual shift" as described in slide 105 still hold.

I'm going to close this issue as I think the original question of how to arrange sublocales (for GPUs) has been settled.
