### ISSUE TITLE
[mason]  Update mason/toml printer to sort by keys

### ISSUE THREAD

**Issue by arezaii** [chapel-lang/chapel#18526]
As mentioned in https://github.com/chapel-lang/chapel/pull/18525, update mason/toml printer to sort by keys so the output of mason tests does not need to change if the key order changes as it did with PR #18427

**Comment by arezaii** [comment]
The simple fix for this is to sort all the keys when printing TOML, but this would enforce ordering on all users of the TOML module and I'm not sure that is what @mppf had envisioned with this change request, is it? Although it does look like we've put some custom ordering of the tables (root is prioritized to the top), so I'm not sure how general purpose the module is intended to be right now.

**Comment by mppf** [comment]
I think it's better to have all users of the TOML module get keys in a sorted order then for them to get them in an arbitrary and implementation-defined order.

**Comment by arezaii** [comment]
Just so I am clear on my end, we are ok if a user reads in their TOML file and we write it back out in a different order?
 
I suppose this was already happening if a user had placed a table named `root` somewhere in their file, we would always re-write that as the first entry. 
Also, I think you are saying the the existing implementation might do the same thing since there is no guarantee of the order we return elements from the map, is my understanding correct?

**Comment by mppf** [comment]
Yes, I think that's OK, because we were already doing that, AFAIK.
