### ISSUE TITLE
Spike: Investigate allowing simple function calls from GPU kernels

### ISSUE THREAD

**Issue by daviditen** [chapel-lang/chapel#18520]
It would be useful to allow calling other simple functions from GPU kernels. As a start we could allow calling functions that are themselves as simple as the current GPU kernels e.g. no further function calls and only "fast" and "local" primitives.

**Comment by mppf** [comment]
We use a particular LLVM linkage type for the kernels we launch and this will need to change for a function called from a kernel.

**Comment by daviditen** [comment]
I have a basic function call from a kernel working on my [gpu-kernel-fn-call](https://github.com/daviditen/chapel/tree/gpu-kernel-fn-call) branch.

I added a new compiler FLAG that is added to functions that are simple enough for us to handle that are called from outlined kernels. These functions are code-generated for both CPU and GPU. Avoid setting the linkage type to kernel for the GPU versions of these functions.
