### ISSUE TITLE
Should a load factor setter for map be added?

### ISSUE THREAD

**Issue by bmcdonald3** [chapel-lang/chapel#18548]
## Summary
Exposing a `maxLoadFactor` (name chosen to be consistent with other languages, open for discussion) to allow users to decide when is best for their `map` to grow can help improve both performance and memory in specific cases. Choosing a higher load factor can help save memory on unnecessary map allocations if memory is a concern. Choosing a lower load factor can help improve performance because it can reduce the number of slots probed when there are collisions.

### Proposal 1: Setter with fractional argument
```chpl
var m = new map(int, int);
m.setMaxLoadCapacity(0.75);
```

### Proposal 2: Setter with integer argument
```chpl
var m = new map(int, int);
m.setMaxLoadCapacity(2);
```

### Proposal 3: Keyword argument for map constructor 
```chpl
var m = new map(int, int, maxLoadCapacity=.75);
```

### Pros/cons of proposals
1. Setter with fractional argument
  a. Accepting a fraction is easy to understand IMO (table can be this % full)
  b. Setter method won't make constructors more complicated for something most users won't use
  c. Not consistent with the C++ implementation
2. Setter with integer argument
  a. Consistent with C++ implementation
  b. Confusing to wrap your head around IMO (table can be 1/value full -- hard to intuit)
  c. Limiting in what can be achieved
3. Keyword argument for map constructor 
  a. Doesn't require adding another method
  b. Consistent with Java implementation
  c. Fixed for life of `map`

### C++ unordered_map
```c++
std::unordered_map<std::int, std::int> m;
m.max_load_factor(2); // map can now be up to 50% full (numslots/loadfactor)
```
### Java Hashtable
```Java
Hashtable<int, int> m = new Hashtable<int, int>(10, 0.50); // initial capacity 10, table can be up to 50% full
```

### Other languages
- Rust doesn't have a concept of a `loadFactor`, but instead allows setting of an initial capacity, which may have the same effect in many cases
- Python, Julia, etc., do not have a concept of this, just like our `map` now

## Links to related information
Motivated by: https://github.com/chapel-lang/chapel/pull/18427 and https://github.com/Cray/chapel-private/issues/2536
PR with proposal 1: https://github.com/chapel-lang/chapel/pull/18523
C++ load factor: https://en.cppreference.com/w/cpp/container/unordered_map/max_load_factor
Java hashtable: https://docs.oracle.com/javase/8/docs/api/java/util/Hashtable.html
Rust hashmap: https://doc.rust-lang.org/std/collections/struct.HashMap.html

**Comment by e-kayrakli** [comment]
All of Brad's points make sense to me. The name I was thinking while reading OP was `expansionThreshold`, but `resizeThreshold` sounds good, too.

FWIW, I don't think this is a common feature in any language, and we wouldn't offend anybody if we choose a unique name for it. Especially if we can find something that's more descriptive and accurate.

**Comment by bmcdonald3** [comment]
Closing as this was added in https://github.com/chapel-lang/chapel/pull/18523
