### ISSUE TITLE
Make inline markup filtering in deprecation message more sophisticated

### ISSUE THREAD

**Issue by stonea** [chapel-lang/chapel#18549]
In https://github.com/chapel-lang/chapel/pull/18540 we add a filtering mechanism for inline syntax in deprecation messages from the `deprecated` keyword.

This means that given the following, the generated documentation will have the documentation for 'x' link to 'y', and in the generated compiler warning we will replace `` :var:`y` `` with just `y`.

```chpl

deprecated "x is deprecated - please use :var:`y` instead."
var x;

var y;

x;
```

Inline syntax includes a number of features beyond simple linking, see https://chapel-lang.org/docs/latest/tools/chpldoc/chpldoc.html#inline-markup-2

We've added the following TODO items in Symbol::getSanitizedDeprecationMsg:

```C++
  // TODO: Support explicit title and reference targets like in reST direct hyperlinks (and having only target
  //       show up in sanitized message).
  // TODO: Allow prefixing content with ! (and filtering it out in the sanitized message)
  // TODO: Allow prefixing content with ~ (and having it only display last component of target)
```

**Comment by Mashijams** [comment]
@stonea 
Has anyone worked on it?
If not I would like to work on this.

**Comment by stonea** [comment]
> We have a PR open that will handle !, but not ~. I'll let Andy speak more about if he had other things in mind

Looks like this is the PR for adding !: https://github.com/chapel-lang/chapel/pull/18796

But yeah, it looks like we still haven't implemented behavior for ~ or (I think more importantly) the ability to give a specific title; described in the doc like this:

> You may supply an explicit title and reference target, like in reST direct hyperlinks: :role:`title <target>` will refer to target, but the link text will be title.

So if you want, feel free to go for it. Thanks!

**Comment by pree-T** [comment]
May I work on this? Can someone help me as I am new to open source contribution?

**Comment by lydia-duncan** [comment]
I don't think we've heard anything from @Mashijams on their progress, so if they don't respond in a week, I'd say go for it.  If you haven't found it already, https://chapel-lang.org/contributing.html should be helpful in getting started for contributing (and definitely let us know if you find anything confusing)

**Comment by Mashijams** [comment]
Sorry for late reply, I got caught up with my university exams which are currently still ongoing so in the meantime if anyone wants to work on this could definitely do so :)
Second task is done, so just make sure if there is an existing PR handling first and third tasks.
Thanks!

**Comment by airpods69** [comment]
if @pree-T doesnt respond
then can i work on this?? might need some amount of guidance later though

**Comment by lydia-duncan** [comment]
Sure, just be sure to mention when you start (and give them a couple more days to respond)

**Comment by airpods69** [comment]
sure thing

just realised i'd have to learn and understand first which is gonna take a while haha

**Comment by rinkydevi** [comment]
i can contribute in this issue, how can i proceed?

**Comment by lydia-duncan** [comment]
I'm concerned that we've now had three other people ask to work on this issue and then disappear.  This makes me think that maybe it is not a good entry point for new contributors.

**Comment by stonea** [comment]
> I'm concerned that we've now had three other people ask to work on this issue and then disappear. This makes me think that maybe it is not a good entry point for new contributors.

Fine by me, maybe it's difficulty with regular expressions? Those can be kind of esoteric.

I'll leave a couple notes just in case someone does want to take a crack at this (if you get stuck feel free to ping me by adding a comment with `@stonea`).  Again, I think the main challenge is having familiarity with regular expressions and knowing how to apply them with C++.

Here's a sample program to get started with the deprecates a function `foo`:

```chpl
deprecated "foo is deprecated consider using :proc:`~BarPackage.bar` instead"
proc foo() { }
foo();
```
Notice that when you compile this you'll get this warning:

```
foo.chpl:3: warning: foo is deprecated consider using :proc:`~BarPackage.bar` instead
````

This is showing that the filtering doesn't kick in when that tilde (~) is there. If you change line 1 and remove the tilde you can see the filtering kick in:

`foo.chpl:3: warning: foo is deprecated consider using BarPackage.bar instead`

But what we'd like to do is allow the tilde to be in and if it's there only show the last component of the target. In other words we want the original example to output this message:

`foo.chpl:3: warning: foo is deprecated consider using bar instead`

The rewrites we're doing are all driven by the following regexp in `Symbol::getSanitizedDeprecationMsg`:

```
static const auto reStr = R"(\B\:(mod|proc|iter|data|const|var|param|type|class|record|attr)\:`([\w\$\.]+)`\B)";`
```

which matches the Sphinx markup and captures the stuff in the backticks.  We then pass it to `std::regex_replace` like this:

`msg = std::regex_replace(msg, std::regex(reStr), "$2");`

which says "lets replacethe entire matching expression with just the stuff we "captured" in the second group (second set of things in parantheses).  We'll need to update the regexp to (optionally) match a tilde as the first character between the backticks and then we'll also need to update the rewrite to somehow recognize if the tilde is there and if so only output the last component.

There's probably a few different ways to do this, but the approach I would take:

- updating the regexp to have another "group" that matches optionally matches the tilde character. I think this would look something like this: `(\~?)` (I think we'll need to "escape" the tilde character because otherwise it gets confused and thinks this is the tilde operator in regexp)
- use `std::regex_match` to see if have a legal sphinx directive
- If we match:
  - Set some temporary variable `replaceTo` to the contents of the third group (that is the stuff between the backticks for the sphinx directive minus the tilde). See the "Finding a Regex Match" content here (https://www.regular-expressions.info/stdregex.html) for more info.
  - See if the second group matched as a tilde (and not a blank string) if so then:
    - Do some string processing to change `replaceTo` to only include the last component (only the stuff after the last period)
  - use std::regex_replace to replace the entire sphinx directive with the stuff we stored in `replaceTo`
