### ISSUE TITLE
Improper node allocation using PBS

### ISSUE THREAD

**Issue by rj-jesus** [chapel-lang/chapel#18567]
### Summary of Problem

I'm using Chapel on a system that uses PBS Pro.

When running a program on multiple locales, instead of allocating multiple nodes and running one locale per node, Chapel allocates a single node and runs all the locales on that node.

The problem seems to be at [the PBS GASNet launcher](https://github.com/chapel-lang/chapel/blob/release/1.25/runtime/src/launch/pbs-gasnetrun_ibv/launch-pbs-gasnetrun_ibv.c), namely `determineQsubVersion` does not identify the PBS version the system I'm using has, and `genNumLocalesOptions` does not generate a proper node allocation specification.

I can fix the problem by patching `genNumLocalesOptions` to generate the proper specification, namely by issuing `fprintf(pbsFile, "#PBS -lselect=%d\n", numLocales);`, but I don't know what's the best way to incorporate this into the existing code.

For reference, here's the output of `qsub --version`
```
pbs_version = 19.2.6.20200311140837
```

### Steps to Reproduce

**Source Code:**

```chapel
use Memory.Diagnostics;

coforall loc in Locales {
  on loc {
    writeln("locale #", here.id, "...");
    writeln("  ...is named: ", here.name);
    writeln("  ...has hostname: ", here.hostname);
    writeln("  ...has ", here.numPUs(), " processor cores");
    writeln("  ...has ", here.physicalMemory(unit=MemUnits.GB, retType=real),
        " GB of memory");
    writeln("  ...has ", here.maxTaskPar, " maximum parallelism");
  }
}
```

**Compile command:**
`chpl -o foo foo.chpl`

**Execution command:**
`./foo -nl 4`

### Configuration Information

```
$ chpl --version
chpl version 1.25.0
  built with LLVM version 11.0.0
Copyright 2020-2021 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)
```
```
$ $CHPL_HOME/util/printchplenv --anonymize
CHPL_TARGET_PLATFORM: hpe-apollo
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: aarch64
CHPL_TARGET_CPU: native +
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet
  CHPL_COMM_SUBSTRATE: ibv
  CHPL_GASNET_SEGMENT: large
CHPL_TASKS: qthreads
CHPL_LAUNCHER: pbs-gasnetrun_ibv +
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: system +
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: system +
CHPL_AUX_FILESYS: none
```
```
$ clang --version
clang version 11.0.0
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: <...>/llvm/11.0/bin
```
```
$ module list
Currently Loaded Modulefiles:
 1) cpe-cray   2) cce-sve/10.0.1(default)   3) craype/2.7.0(default)   4) craype-arm-nsp1   5) craype-network-infiniband   6) cray-libsci/20.09.1.1(default)   7) openmpi/4.1.0/gcc-11.0   8) gcc/10.3.0   9) llvm/11.0  
```
(It's an HPE system.)

**Comment by ronawho** [comment]
Yes, but let's discuss that internally

**Comment by jabraham17** [comment]
https://github.com/chapel-lang/chapel/pull/23134 resolved this issue, but this was never closed
