### ISSUE TITLE
Have homebrew formula use homebrew GMP, delete bundled sources

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#18608]
This issue is forked off from https://github.com/chapel-lang/chapel/issues/17428 where
it has been the last remaining TODO that we consider to be low-hanging fruit since 1.25.0.
It proposes that we switch over to using homebrew's version of GMP rather than our
bundled version, to be a better player in the homebrew space, reduce our image size,
and benefit from any work done in support of GMP on homebrew.  As @carlocab points
out in https://github.com/chapel-lang/chapel/issues/18600#issuecomment-949418822
it would also insulate us from dealing with portability challenges ourselves.  ~The only
downside I'm aware of is that we might lose a bit of performance because we won't be
building homebrew with jemalloc anymore, but since we generally consider the homebrew
release of Chapel to be more about ease of installation than performance, this seems
like an acceptable tradeoff.~  [edit: Never mind this, Elliot and Michael corrected me below
that this enabled at link-time, not build-time].

**Comment by ronawho** [comment]
I _think_ we're using system gmp on mac now (at least my brew install is saying it's using system gmp) but it would be great if somebody else could confirm.

**Comment by mppf** [comment]
Yes - see e.g. https://github.com/Homebrew/homebrew-core/pull/91257/files#diff-0c9742fd008239155d7d6c8acb7ba65f603920010e388b6fe5c80e32e631d91bR27
