### ISSUE TITLE
`Regex.matches` infinitely loops with patterns that match the empty string

### ISSUE THREAD

**Issue by pierce314159** [chapel-lang/chapel#18639]
### Summary of Problem

When calling `Regex.matches` with `pattern`s that match the empty string, ` ((matched = true, offset = 0, size = 0))` is returned infinitely many times. I expect the return to be `str.size + 1` matches

### Steps to Reproduce

**Source Code:**

```chapel
use Regex; 

var myRegex = compile("");
var str = "one";
writeln(myRegex.matches(str));
```

**Compile command:**

` chpl RegexExample.chpl -o regex`

**Execution command:**

`./regex`

### Configuration Information

- Output of `chpl --version`: 
```
chpl version 1.25.0
built with LLVM version 11.0.1
```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: bundled
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: `gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0`

**Comment by aconsroe-hpe** [comment]
Fixing `iter matches` was  quick fix and `iter split` took me a bit longer but I have a PR open that addresses both of them. Just waiting on some more testing and review.

**Comment by bradcray** [comment]
Great, thanks!

**Comment by aconsroe-hpe** [comment]
I've merged a fix for this issue, closing issue.
