### ISSUE TITLE
Change argument names of set methods to `element`

### ISSUE THREAD

**Issue by bmcdonald3** [chapel-lang/chapel#18651]
Currently, `add()`, `contains()`, and `remove()` in set all use `x` as the argument name. To be consistent with the set type declaration of `eltType` and also be more descriptive, it has been proposed to change those argument names to `element`.

The naming of `item` was also discussed, but the name of `element` was decided upon due to how sets are talked about online (source: Wikipedia). Map uses `item`, but there they have `keyType` and `valType`. A discussion around unifying these argument names for all data structures could be necessary.

**Comment by shalearkane** [comment]
Hii, I would like to work on this issue if there is no one working on it. Could you please assign this issue to me?

**Comment by bmcdonald3** [comment]
Unfortunately, this task is already complete and just waiting to be merged (see #18797)
