### ISSUE TITLE
Similar ordered sets with different comparators

### ISSUE THREAD

**Issue by rj-jesus** [chapel-lang/chapel#18656]
I might be doing something wrong, but it seems I can't have two similar ordered sets using different comparators. For example, consider the following code:
```chapel
use OrderedSet;

enum E { A = 0, B, C, D, };

record R1 { proc key(a) return  a:int; };
record R2 { proc key(a) return -a:int; };

const comp1: R1, comp2: R2;

var v1 = new orderedSet(E, false, comp1);
var v2 = new orderedSet(E, false, comp2);

for l in E {
  v1.add(l);
  v2.add(l);
}

writeln(v1);  // [ A B C D ]
writeln(v2);  // [ D C B A ]
```

I'd expect it to produce the two sets I've indicated in the comments. However, it doesn't compile:
```
$CHPL_HOME/modules/packages/OrderedSet.chpl:64: In initializer:
$CHPL_HOME/modules/packages/OrderedSet.chpl:69: error: Cannot replace an instantiated field with another type
$CHPL_HOME/modules/packages/OrderedSet.chpl:69: note: field 'instance' has type 'treap(E,false,R1,unmanaged _treapNode(E)?)' but is set to 'treap(E,false,R2,unmanaged _treapNode(E)?)'
  zzz.chpl:164: called as orderedSet.init(type eltType = E, param parSafe = false, comparator: R2)
note: generic instantiations are underlined in the above callstack
```

Indeed, the code works fine iff only one of `v1` and `v2` exists.

**Comment by bradcray** [comment]
Definitely sounds like a bug on our / the library's part, @rj-jesus , thanks for filing this.

**Comment by e-kayrakli** [comment]
Thanks for the bug report @rj-jesus!

OrderedSet implementation is hitting a compiler bug, I think. The workaround is pretty easy and I am testing a branch that does that. I'll keep you posted here.

The compiler bug itself is not in my wheelhouse though. (For the developers) Here's the reproducer:

```chapel
class Outer {
  param flag;

  // this def is problematic:
  var partialGenericField: Inner(flag);

  // the following works:
  //var partialGenericField: Inner(flag,?);
  //var partialGenericField: Inner;

  proc init(param flag, val) {
    this.flag = flag;
    this.partialGenericField = new Inner(flag, val);
  }
}

class Inner {
  param flag;
  var fullyGenericField;

  proc init(param flag, val) {
    this.flag = flag;
    this.fullyGenericField = val;
  }
}

var o1 = new Outer(false, 5);
// now we've instantiated Inner(bool, int) and Outer(bool, Inner(bool, int))


// here the compiler falsely expects the `partialGenericField` of Outer
// to be Inner(bool,int)
var o2 = new Outer(false, "five");

writeln(o1);
writeln(o2);
```

I believe the gist is: when there are generic classes with partially generic fields wrap one another, we instantiate the inner type correctly the first time we encounter a fully-specified type. But for subsequent definitions, we do not instantiate new inner types, but instead expect them to be always equal to the very first instantiation we create.

Among the already-open issues https://github.com/chapel-lang/chapel/issues/16508#issuecomment-721270436 comes close to this bug, but I can't tell for sure. @mppf, what do you think? 

---

I am not sure the snippet above should be legal. Maybe we should require such fields to use `?` for the generic field?

**Comment by mppf** [comment]
@e-kayrakli - could you make a new issue for this problematic program and link to it from a comment in #16508?

The documentation we do have about partial instantiations is here: https://chapel-lang.org/docs/technotes/partialInstantiations.html and that's clearly showing uses of partial instantiations without requiring the `?`. However I think that's something we should consider and it has certain advantages. Would you mind making  design issue about it?

**Comment by rj-jesus** [comment]
@e-kayrakli Thanks, your workaround does indeed work (at the time I'd also worked around the problem by removing the type specification of `instance` from orderedSet, which in my case was enough to make it work).

**Comment by rj-jesus** [comment]
@mppf The technical note you linked reminded me of the initial problem that initially led me to this issue, and that I forgot to mention before. Something like this
```chapel
use OrderedSet;
enum E { A = 0, B, C, D, };
type t = orderedSet(E);
```
results in a compiler bug
```
$CHPL_HOME/modules/packages/OrderedSet.chpl:55: In method 'instance':
$CHPL_HOME/modules/packages/OrderedSet.chpl:55: internal error: AST-PRI-IVE-0235 chpl version 1.25.0

Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug -- 
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.

  $CHPL_HOME/modules/packages/OrderedSet.chpl:102: called as (orderedSet(E,false)).instance from method 'init='
  zzz.chpl:1: called as (orderedSet(E,false)).init=(other: orderedSet(E,false))
note: generic instantiations are underlined in the above callstack
```

**Comment by e-kayrakli** [comment]
@rj-jesus -- when I merged my PR to fix the bug you originally reported here, this issue is closed automatically. Rather than reopening it, would you be up for creating a different issue for the last bug you reported? They could be related, but it deserves its own issue, I think.

**Comment by rj-jesus** [comment]
@e-kayrakli I just checked and your PR also fixes the last bug I mentioned. If you still think it's useful to open a new issue just let me know.

**Comment by e-kayrakli** [comment]
Ah, I see. Good to hear that.

I'll try to create something based off of my reproducer then. Thanks
