### ISSUE TITLE
Should we require `?` for partially instantiated field types?

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#18665]
This spun off from https://github.com/chapel-lang/chapel/issues/18656.

Currently, the following is OK:

```chapel
class C {
  var d: D(int);  // d.y is generic
}

class D {
  type t;
  param y;
}
```

should we require `d` to be declared with no instantiated fields (`D`), or non-instantiated fields to be denoted explicitly (`D(int, ?)`)?

Note that there's a bug at the moment around this matter: https://github.com/chapel-lang/chapel/issues/18664

**Comment by e-kayrakli** [comment]
@mppf -- feel free to edit if I mischaracterized something.

**Comment by mppf** [comment]
I can think of some Pros and Cons:

In favor of requiring `D(int, ?)` above:
 * makes it clear that the type is generic even though it might look instantiated
 * there might be generic code that wants to instantiate a type in the same way whether the result is generic or concrete
     * I don't have an example in mind - it's just a possibility
      
Arguments against:
 * it is a breaking change from what we allow today
 * we don't label generic types today - e.g. we just write `integral` and not say `integral(?)`

**Comment by e-kayrakli** [comment]
> we don't label generic types today - e.g. we just write integral and not say integral(?)

Is there some magic behind `integral` here? In other words, we aren't actually thinking of disallowing `var d: D;` above, right?

To me this is appealing in the sense that the rule kind of becomes simpler: "You either use a fully generic type, explicitly tell which fields you want to leave generic". That being said, I am slightly worried about the clutter that this may create in the code.

I don't have a preference either way at the moment.

**Comment by mppf** [comment]
Nothing special about integral, and I don't think we're proposing here that `var d: D` would stop working to declare a generic field.

**Comment by mppf** [comment]
FWIW I have been thinking about this related to type construction in the compiler rework and I think the proposed change would make the language more consistent. In particular, usually for a call, like `D(int)` above, for any formal arguments that don't have a matching actual, the formal has to have a default value. (But that's not the case here). I think this would be less weird with `D(int, ?)` because the `?` is (arguably) acknowledging that there are other arguments that we know we aren't providing (and we want them to remain uninstantiated in the resulting type).

**Comment by bradcray** [comment]
I'm open to this proposal.  As with most breaking changes, my main reaction is "What would the effect on our current code base be?" because I think seeing the diff that would be required would help either make me feel better about the direction or more hesitant about it.

A question related to the OP that maybe I should already know the answer to.  If my type had been:

```chapel
class D {
  type t;
  param y;
  param z;
}
```

would I type `D(int, ?, ?)` or would `D(int, ?)` suffice?  (where I can't remember whether `?` means "and there's some other stuff too" or needs to be a 1:1 matching for each other field.  I recall discussing this with BHarsh, but can't recall where we left it.

And then, also, to make sure I'm following, if the type had been:

```chapel
class D {
  type t;
  param y = 0;
  param z = 1;
}
```

then I could still write `D(int)` and that would mean `D(int, 0, 1)`, right?  What would `D(int, ?)` or `D(int, ?, ?)` each mean?

**Comment by mppf** [comment]
> would I type `D(int, ?, ?)` or would `D(int, ?)` suffice?  (where I can't remember whether `?` means "and there's some other stuff too" or needs to be a 1:1 matching for each other field.  I recall discussing this with BHarsh, but can't recall where we left it.

Just `D(int, ?)`. `?` means "there's other stuff too".  Per https://chapel-lang.org/docs/main/technotes/partialInstantiations.html

> There are some restrictions that accompany the ? argument. First is that ? may only appear once in a type constructor call. ... Furthermore, once ? appears in a type constructor call all later arguments in the same call must used named expressions. This restriction emphasizes that ? may not be used as a positional argument. 

> 
> And then, also, to make sure I'm following, if the type had been:
> 
> ```chapel
> class D {
>   type t;
>   param y = 0;
>   param z = 1;
> }
> ```
> 
> then I could still write `D(int)` and that would mean `D(int, 0, 1)`, right?  What would `D(int, ?)` or `D(int, ?, ?)` each mean?

Yes, `D(int)` would mean `D(int, 0, 1)` per our usual type-with-defaults rules. `D(int, ?)` would mean `t=int` but `y` and `z` are uninstantiated still. `D(int, ?, ?)` is an error (per above).

**Comment by e-kayrakli** [comment]
@mppf -- I wanted to make sure that [this comment](https://github.com/chapel-lang/chapel/issues/18664#issuecomment-959835112) is seen before making a decision here. We may lose some expressibility if we go with the proposal here.

---

Specifically, my current [workaround](https://github.com/chapel-lang/chapel/pull/18661) on orderedSet caused `var oset: orderedSet(int);` to stop working, where the solution is to have `var oset = new orderedSet(int)`. I can't tell whether this is a different bug, or a limitation added by the explicit `?`.

**Comment by mppf** [comment]
@e-kayrakli - I don't think that is related to this issue. In the orderedSet situation, `comparator` is not specified in the treap, so the type `orderedSet(int)` is still generic. Which should mean that `var oset: orderedSet(int)` results in a compilation failure. (Unless split init is applying).

The solution is not `?` (although it may well address compiler bugs) but rather to make it say something like `record treap { ...; type comparatorType = Sort.DefaultComparator; var comparator: comparatorType; }` if default init is desired here.

**Comment by mppf** [comment]
Here is a hacky patch to try to establish how much impact changing this will have

<details>

```
diff --git a/compiler/AST/AggregateType.cpp b/compiler/AST/AggregateType.cpp
index 6f47a56995..5cc9309a5c 100644
--- a/compiler/AST/AggregateType.cpp
+++ b/compiler/AST/AggregateType.cpp
@@ -939,7 +939,7 @@ AggregateType* AggregateType::generateType(CallExpr* call, const char* callStrin
 
   AggregateType* ret = this;
 
-  bool evalDefaults = true;
+  bool foundQuestionMarkArg = false;
 
   // Separate named and positional args, storing named-exprs in a map
   SymbolMap map;
@@ -958,7 +958,7 @@ AggregateType* AggregateType::generateType(CallExpr* call, const char* callStrin
     } else {
       SymExpr* se = toSymExpr(actual);
       if (se->symbol() == gUninstantiated) {
-        evalDefaults = false;
+        foundQuestionMarkArg = true;
       } else {
         notNamed.push(toSymExpr(actual)->symbol());
       }
@@ -975,6 +975,7 @@ AggregateType* AggregateType::generateType(CallExpr* call, const char* callStrin
 
   INT_ASSERT(notNamed.size() == 0);
 
+  bool evalDefaults = !foundQuestionMarkArg;
   ret = ret->generateType(map, call, callString, evalDefaults, getInstantiationPoint(call));
 
   if (ret != this) {
@@ -983,6 +984,46 @@ AggregateType* AggregateType::generateType(CallExpr* call, const char* callStrin
     resolveConcreteFields(ret, call, callString);
   }
 
+  // update the type's generic-ness
+  bool anyGeneric = false;
+  //bool anyNonDefaultedGeneric = false;
+  for_fields(field, ret) {
+    /*Symbol* subst = ret->substitutions.get(field);
+    if (subst != nullptr) {
+      // OK, we have a substitution, so decide based upon that
+      // whether it is generic.
+      if (subst->getValType()->symbol->hasFlag(FLAG_GENERIC))
+        anyGeneric = true;
+    } else {
+      bool hasDefault = false;
+      if (ret->fieldIsGeneric(field, hasDefault)) {
+        anyGeneric = true;
+        if (hasDefault == false)
+          anyNonDefaultedGeneric = true;
+      }
+    }*/
+    Type* t = field->getValType();
+    if (t == dtUnknown || t->symbol->hasFlag(FLAG_GENERIC)) {
+      anyGeneric = true;
+    }
+  }
+  if (anyGeneric) {
+    ret->markAsGeneric();
+    //if (anyNonDefaultedGeneric == false)
+    //  ret->markAsGenericWithDefaults();
+  }
+
+  // check that:
+  //  * if '?' was passed, the result is generic
+  //  * if '?' was not passed, the result is not generic
+  if (foundQuestionMarkArg) {
+    if (anyGeneric == false)
+      USR_FATAL(call, "type constructed not generic but ? was provided");
+  } else {
+    if (anyGeneric == true)
+      USR_FATAL(call, "type constructed was generic so ? is required");
+  }
+
   return ret;
 }
 ```
 
</details>

I haven't run it through testing yet.

**Comment by mppf** [comment]
So for other reasons I was just looking at the spec in this area. 

In https://chapel-lang.org/docs/main/language/spec/generics.html#generic-classes-and-records , the spec says a generic field is:

>   *  a specified or unspecified type alias,
>   *  a parameter field, or
>   *  a var or const field that has no type and no initialization expression.

Notably absent from this is "a var or const field that is declared with a generic type" even though it is how the compiler is behaving today. So, however we resolve this question, I think we will need to update the spec.

**Comment by mppf** [comment]
Regarding the history & documentation in this area -- see also PRs #9355 #9489 and #11004.

**Comment by mppf** [comment]
From https://github.com/chapel-lang/chapel/issues/18665#issuecomment-956485200

> ... I don't think we're proposing here that `var d: D` would stop working to declare a generic field.

In #19120, I am proposing that you would have to write `var d:D(?)` to declare a generic field if `D` is a generic type.

**Comment by mppf** [comment]
@DanilaFe suggested yesterday that partial instantiation only be allowed with keyword arguments, which is a kind of alternative to the proposal here, of requiring a trailing `?` argument if partial instantiation is occuring.

**Comment by mppf** [comment]
I've created a better patch to try it out in https://github.com/mppf/chapel/tree/warn-partial-instantiation-no-q . I'm trying out making it a warning rather than an error. The newer patch resolves the problem with the distributions primer.

**Comment by benharsh** [comment]
Adding a warning that suggests using ``?`` in partial instantiations sounds good to me.

**Comment by mppf** [comment]
To further discussion on the language design direction, I've created a draft PR to warn for partial instantiations that do not include `?` -- #21410. There it is possible to see the impact of the warning on tests.
