### ISSUE TITLE
`external inline proc` leads to wrong output

### ISSUE THREAD

**Issue by rj-jesus** [chapel-lang/chapel#18672]
I think the Chapel compiler has problems with the `inline` keyword in external function declarations.

This code
```chapel
use SysCTypes;

extern "strlen"        proc f1(c_string): size_t;
extern "strlen" inline proc f2(c_string): size_t;

writeln(f1("what's the length of this?"));
writeln(f2("and of this?"));
```
outputs
```
26
0
```
, which doesn't seem right.

Chapel's [language specification on external procedures](https://chapel-lang.org/docs/language/spec/interoperability.html) doesn't seem to mention the `inline` keyword, so I assume the snippet above is actually illegal. If this is the case, I think there should be an error signalling it at compile time (when I first hit this bug it did make me scratch my head a couple of times before understanding what was going on).

**Comment by mppf** [comment]
hi - thanks for the bug report. I agree that for now we should emit an error for `extern inline`.

Note that you *can* arrange for an extern function to be inlined. But, you need to put the inline hint on the C code rather than on the Chapel code.

**Comment by mppf** [comment]
In PR #18673 I've adjusted it to warn and ignore the `inline` keyword for extern procs.

**Comment by rj-jesus** [comment]
Hi @mppf , thanks, that's what I figured after stumbling upon this issue (in fact the `inline` keyword was already in the C code, I was just hoping that by having it on the Chapel side as well I would get Chapel's inline semantics). Thanks once again.
