### ISSUE TITLE
Compiler bug with lambdas capturing variables defined inside functions

### ISSUE THREAD

**Issue by rj-jesus** [chapel-lang/chapel#18703]
It seems there's a compiler bug with lambdas that implicitly capture variables scoped inside functions. For example, the code below
```chapel
proc f() {
  // if this is moved to outside of `f' (above it), `g1' works
  var x = 1.0;

  // with `x` defined inside `f`, this raises a compiler bug
  var g1 = lambda(i: int) { return i:real+x; };
  writeln(+reduce g1(0..9));

  // this works, the result is 55.0
  //var g2 = lambda(i: int, x: real) { return i:real+x; };
  //writeln(+reduce g2(0..9, x));
}

f();

// this also works fine
//var x = 1.0;
//var g3 = lambda(i: int) { return i:real+x; };
//writeln(+reduce g3(0..9));
```
results in
```
zzz.chpl:208: internal error: RES-ADD-LLS-0803 chpl version 1.25.0
```

As mentioned in the comments, if `x` is moved to outside of `f`, the code compiles fine. Alternatively, if `x` is passed to the lambda as an explicit argument, as in `g2`, the code also works fine. If everything is defined outside of `f`, as in `g3`, everything also works as expected.

**Comment by bradcray** [comment]
@rj-jesus — Thanks for filing this.  I'm not sure whether you're already aware of this or not, but Chapel's support for first-class functions / lambdas is considered unstable / incomplete at present, so this isn't completely surprising even though it's frustrating.  We're hoping to improve the situation in this coming release cycle.

I'm tagging @dlongnecke-cray on this who's done the most analysis of where current support lies to see if he has anything smarter than that to say about this specific behavior.

**Comment by dlongnecke-cray** [comment]
Hi @rj-jesus, everything Brad has said still holds, but in your specific case:

```chapel
proc f() {
  var x = 1.0;

  proc g1(i: int) {
    return i:real+x;
  }

  writeln(+reduce g1(0..9));
}
f();
```

You can define `g1` as a nested function and get the behavior you want. It's true that you can't refer to it by name and pass it around, but for simple cases this might help you.

**Comment by rj-jesus** [comment]
Hi @dlongnecke-cray , thanks, indeed your solution suffices for my use case.

**Comment by jabraham17** [comment]
The internal error is gone on main, instead there is an error as follows
```
foo.chpl:6: error: cannot capture proc because it refers to outer variables
foo.chpl:6: note: such as 'x', here
```
We have a number of tests of this error, so I am just going to close this
