### ISSUE TITLE
Error: command not found .../clang --gcc-toolchain=/usr

### ISSUE THREAD

**Issue by jlbyrne-hpe** [chapel-lang/chapel#18741]
When trying to build/run chapel compiler branched from main commit 8bb386b27 (the branch is for a couple of modules I'm working on, so no changes to the compiler itself)

CHPL_TARGET_COMPILER=clang
CHPL_TARGET_CPU=native
CHPL_COMM=none
CHPL_RE2=bundled
CHPL_LLVM=bundled

 I got errors throughout the build output: 

Error: command not found: /home/jbyrne/chplnone/third-party/llvm/install/linux64-x86_64-gnu/bin/clang --gcc-toolchain=/usr

but nothing obviously failed. 

I identified the problem as having to my PATH having a non-standard gcc in my path, so I changed my build script to set my PATH and built and I thought all would be well, but when I tried to compile, the same error was output, but the compiler didn't stop executing. Again, resetting the PATH eliminated the problem.

There's a clear workaround, but the errors are really annoying and it isn't clear how serious it is because things don't stop. 

jbyrne@eleven:~/chplnone$ ( . ~/bin/chplnone.sh ; chpl --version )
Setting CHPL_HOME to /home/jbyrne/chplnone
Updating PATH to include /home/jbyrne/chplnone/bin/linux64-x86_64
                     and /home/jbyrne/chplnone/util
Updating MANPATH to include /home/jbyrne/chplnone/man

Error: command not found: /home/jbyrne/chplnone/third-party/llvm/install/linux64-x86_64-gnu/bin/clang --gcc-toolchain=/usr
chpl version 1.26.0 pre-release (f3661ac307) 
  built with LLVM version 11.0.1
Copyright 2020-2021 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)

**Comment by bradcray** [comment]
@mppf: I think I'm going to need your help with this one.  I'm guessing that the `clang --gcc-toolchain` commands that are being complained about are from our Python scripts around setting up the right clang command lines rather than our Makefiles, because I'm fairly certain the Makefiles would error out if they hit a problem like this.  Could it be the case that the scripts are running a clang command and not checking the error code if the command is not found?  Or is it more like our Makefile structure calls the scripts and stores the result into a variable, but doesn't trigger an error because it's just a variable evaluation rather than a command required to build a target?

I could look at this more, but would benefit from some help understanding where the link between the Python scripts and the Makefiles are.  And/or a tip about how to reproduce the issue for myself.

**Comment by mppf** [comment]
@jlbyrne-hpe - can you send us the output of `./util/printchplenv --all --internal` and in particular I'm wondering if the error shows up with that command? Also you may have said this but does `/home/jbyrne/chplnone/third-party/llvm/install/linux64-x86_64-gnu/bin/clang` refer to a file you can run?

**Comment by jlbyrne-hpe** [comment]
I was a bit lazy when I filed this. I originally thought it was just a build problem and debugging that looked painful, but given that it is now easily reproduced by "chpl --version", I can strace it and see where things happen. So, it looks like printchplenv.py is the problem child. 

1077  execve("/usr/bin/python3", ["python3", "/home/jbyrne/chpltest/util/chplenv/printchplenv.py", "--all", "--internal", "--no-tidy", "--simple"], 0x557a2dfcdda8 /* 48 vars */) = 0

forks clang with a malformed execve:

1082  execve("/home/jbyrne/chpltest/third-party/llvm/install/linux64-x86_64-gnu/bin/clang --gcc-toolchain=/usr", ["/home/jbyrne/chpltest/third-party/llvm/install/linux64-x86_64-gnu/bin/clang --gcc-toolchain=/usr", "-E", "-x", "c", "-"], 0x7\

The immediate problem looks to be in compiler_utils.py has_std_atomics() which assumes the compiler command string has no arguments. I don't know if any other places are lurking about. I'd be tempted to put code into run_command() to either fix the problem or detect it and die in a usefully verbose manner.

**Comment by mppf** [comment]
@jlbyrne-hpe - I'm having trouble reproducing this issue. What is the output of `./util/config/find-python.sh ` and what Python version does that refer to?

**Comment by mppf** [comment]
@jlbyrne-hpe - I've created PR #18745 to fix it and since I can't reproduce it would be good to know if that solves the issue for you.

**Comment by mppf** [comment]
> @jlbyrne-hpe - I've created PR #18745 to fix it and since I can't reproduce it would be good to know if that solves the issue for you.

Nevermind let me get CI testing working with it before you try it.

**Comment by jlbyrne-hpe** [comment]
The compiler was fixed by #18745 and no longer generates the error.  However, as I recall, there are 3 command not found errors during the build because the bundled compiler isn't built when printchplenv is called. This is a bit unfortunate, but I don't think it affects anything.

**Comment by bradcray** [comment]
@jlbyrne-hpe : Thanks for the update.  If you see those command-not-found errors again and could snapshot them (or provide instructions for reproducing), I agree that they'd be nice to address.
