### ISSUE TITLE
Compiler internal error with `twoArrayRadixSort` on non-homogeneous tuple

### ISSUE THREAD

**Issue by reuster986** [chapel-lang/chapel#18775]
### Summary of Problem

I was attempting to add Chapel's `twoArrayRadixSort` as an algorithmic option to [arkouda](github.com/Bears-R-Us/arkouda) and trying to handle some tricky type issues. For example, when arkouda calls `argsort` on a `float64` array, the Chapel code has to sort a tuple of `(real, int)`, but the default comparator used by `twoArrayRadixSort` does not support non-homogeneous tuples. 

To address this, I tried write a comparator that would fall back to `defaultComparator.keyPart` where there was an instantiation, and would do the right thing when called on a non-homogeneous tuple. However, when I tried to compile, I got an internal error from the compiler.

### Steps to Reproduce

**Source Code:**

The code I'm attempting to add to arkouda can be found [here](https://github.com/Bears-R-Us/arkouda/blob/chapel-sort/src/ArgSortMsg.chpl). 

For a simplified reproducer, attempting to compile the code below triggers the internal error on my laptop:
```chapel
use Sort;

import Reflection.canResolveMethod;
record ContrivedComparator {
  const dc = new DefaultComparator();
  proc keyPart(a, i: int) {
    // Fall back to DefaultComparator implementation where possible
    if canResolveMethod(dc, "keyPart", a, 0) {
      return dc.keyPart(a, i);
    } else if isTuple(a) {
      // DefaultComparator does not handle non-homogeneous tuples
      return tupleKeyPart(a, i);
    } else {
      compilerError("No keyPart method for eltType ", a.type:string);
    }
  }

  proc tupleKeyPart(x: _tuple, i:int) {
    // This is the same as DefaultComparator.keyPart() for homogeneous tuple
    const (_, part) = dc.keyPart(x(i), 1);
    if i >= x.size {
      return (-1, 0:part.type);
    } else {
      return (0, part);
    }
  }
}

const myDefaultComparator = new ContrivedComparator();

var A: [0..#10] (real, int) = for i in 0..#10 do ((10-i):real, i);
// Using the twoArrayRadixSort generates internal error
TwoArrayRadixSort.twoArrayRadixSort(A, comparator=myDefaultComparator);
// Using the regular sort instead does not
sort(A);
```

*Note that when the `twoArrayRadixSort` call is commented out, the program compiles and runs fine.*

**Compile command:**
`chpl foo.chpl`

**Execution command:**
`./foo`

**Associated Future Test(s):**

### Configuration Information

- Output of `chpl --version`: 
`chpl version 1.25.0`
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: unknown
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: smp *
  CHPL_GASNET_SEGMENT: fast
CHPL_TASKS: qthreads
CHPL_LAUNCHER: smp *
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: none *
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
`gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609`
- (For Cray systems only) Output of `module list`: 
N/A

**Comment by bradcray** [comment]
With a quick look, I'm seeing that the source of the internal error relates to the compiler finding itself
in an indexing code path that expects a homogeneous tuple, but the type it's indexing into is not a
homogeneous tuple, stemming from line 20 of your reproducer.

**Comment by bradcray** [comment]
(oh, and wild guessing, I suspect it may have something to do with `x(i)` in that, if `x` is a heterogeneous tuple, `i` must be a `param` in order for the indexing expression to be legal.  Otherwise, Chapel can't know what type the result will be.  This should show up as a user error as in [this case](https://tio.run/##S85ILEjN@f@/LLFIoUTBVkHDUEfBSM9Y05orOT8vLTNdASSRCZQwsOYCMSuAzBKNTE3r//8B), but presumably it dodged past it somehow?)

**Comment by reuster986** [comment]
Ah, that makes sense @bradcray - thanks! I can try special-casing for `(real, int)` tuples without any indexing, which might be enough, considering that @ronawho wrote code for coargsort that already handles non-homogeneous arrays.

**Comment by mppf** [comment]
@reuster986 - the keyPart method is documented in https://chapel-lang.org/docs/modules/packages/Sort.html#the-keypart-method (if you haven't found that already).

In this case the tricky thing is that you need to arrange for keyPart to always return the same type for the tuple elements, even though the tuple contains more than one type. Fortunately we know how to convert real numbers and ints into uints in a way that preserve the sort order (which I think maybe you were already trying to do by calling the default comparator).

This version does that and works for me:

``` chapel
use Sort;

record ContrivedComparator {
  proc keyPart(x: _tuple, i:int) {
    const defaultCmp:DefaultComparator;
    var part: uint(64);
    for param j in 0..<x.size {
      if i == j {
        // get the part, ignore the section
        const p = defaultCmp.keyPart(x(j), 0)(1);
        // assuming result of keyPart is int or uint <= 64 bits
        part = p:uint(64); 
        // If the number is signed, invert the top bit, so that
        // the negative numbers sort below the positive numbers
        if isInt(p) {
          const one:uint(64) = 1;
          part = part ^ (one << 63);
        }
      }
    }
    if i >= x.size {
      return (-1, 0:uint(64));
    } else {
      return (0, part);
    }
  }
}

const myDefaultComparator = new ContrivedComparator();

var A: [0..#10] (real, int) = for i in 0..#10 do ((10-i):real, i);
var B = A;

TwoArrayRadixSort.twoArrayRadixSort(A, comparator=myDefaultComparator);
writeln(A);
writeln();

sort(B);
writeln(B);
writeln();
```

**Comment by reuster986** [comment]
excellent, thanks @mppf ! This code compiles and runs correctly for me; now to try it in arkouda. That `for param` is handy...

By the way, I would have just asked this question on gitter or slack, but the compiler message on internal error says you all would like to see a bug report -- is that still true? Should I keep this issue open, or close it since it was more a matter of me not knowing the right pattern?

**Comment by bradcray** [comment]
I _believe_ that the reason we didn't get the user-facing error is that we're in a part of the compiler where it's trying to determine the type of the `x(i)` expression in a slightly speculative manner, and in that speculative mode, we ignore user-facing errors because... well, it's speculative, so not necessarily the user's fault.  But then in this case, we hit an internal error along that speculative path which we can't really recover from.  If that's correct, the fix is presumably to catch this case higher in the callchain earlier and either flagging it as an error or not going down the speculative path at all (in which case the user-facing error would show up later).

This feels thematically related to the kinds of questions I was recently wrestling with in https://github.com/chapel-lang/chapel/pull/18757 in that it's another case of querying the type / qualType of something.

[Actually, in the time it took me to hit "comment" here, I got a PR that does make it a user-facing error: https://github.com/chapel-lang/chapel/pull/18776 though it still needs testing]

**Comment by bradcray** [comment]
Oops, didn't see Bill's comment before posting mine.  Bill, we'll treat this issue as the bug report (so let's keep it open even though you may be off and running again).

**Comment by reuster986** [comment]
sounds good :)

**Comment by bradcray** [comment]
@reuster986 : Thanks again for reporting this, it felt nice to get it in in time for 1.25.1.

**Comment by reuster986** [comment]
@bradcray sure thing! thanks for addressing it so quickly!
