### ISSUE TITLE
Increased Arkouda compilation times from Chapel 1.24.1 to Chapel 1.25.0

### ISSUE THREAD

**Issue by alvaradoo** [chapel-lang/chapel#18789]
### Summary of Problem
We recently made changed our Arkouda research environment from (https://github.com/zhihuidu/arkouda/tree/streaming) to (https://github.com/zhihuidu/arkouda/tree/Graph). We also switched from using Chapel 1.24.1 to Chapel 1.25.0 with our new branch. 

Prior to the change, our streaming branch with Chapel 1.24.1 and Arkouda server version 2020.07.07 took anywhere from 8-10 minutes to compile. Now, with our update, with Chapel 1.25.0 and Arkouda server version 2019.12.10 it takes anywhere from 15-17  minutes or more to compile. Now, I am unsure if our regression in the Arkouda server version is the culprit (I am also not sure why the Arkouda server version degraded -- have to look into this), or if the issues lies with our upgrade to Chapel 1.25.0. 

### Steps to Reproduce

**Source Code:**
Contained in our files in the GitHub repos linked above. 

**Compile command:**
Just running `make` within the main Arkouda directory. 

**Execution command:**
`./arkouda_server -nl 2`

#### "streaming" Branch Environment 
- Output of `chpl --version`:
```
chpl version 1.24.1
  built with LLVM version 11.0.1
```

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: ibv *
  CHPL_GASNET_SEGMENT: large
CHPL_TASKS: qthreads *
CHPL_LAUNCHER: gasnetrun_ibv *
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc *
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: bundled *
CHPL_HWLOC: bundled *
CHPL_REGEXP: re2
CHPL_LLVM: bundled *
CHPL_AUX_FILESYS: none
```

- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
gcc (GCC) 10.2.0
```

#### "Graph" Branch Environment 
- Output of `chpl --version`:
```
chpl version 1.25.0
  built with LLVM version 11.0.1
```

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: ibv *
  CHPL_GASNET_SEGMENT: large
CHPL_TASKS: qthreads *
CHPL_LAUNCHER: gasnetrun_ibv *
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc *
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: bundled *
CHPL_HWLOC: bundled *
CHPL_RE2: bundled
CHPL_LLVM: bundled *
CHPL_AUX_FILESYS: none
```

- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
gcc (GCC) 10.2.0
```

**Comment by alvaradoo** [comment]
After carefully inspecting both Makefiles in that issue, I realized that we had added 
```
define ARKOUDA_QUICK_COMPILE
CHPL_FLAGS += --no-checks --no-loop-invariant-code-motion --no-fast-followers --ccflags="-O0"
endef
```
into the Makefile of our streaming branch. This now explains the slowdown in compilation times. I had totally missed this, sorry for the wild goose chase!

**Comment by ronawho** [comment]
Just for the record, here's the build times I see on Sherlock. This is with Chapel 1.24.1 and 1.25.0 w/ c-backend (default in 1.24.1) and llvm. Backend C compiler is gcc 10.2 and this is with Arkouda from today (https://github.com/Bears-R-Us/arkouda/commit/20906e9)

| Config              | Build Time |
| ------------------- | ---------: |
| 1.24.1 c-backend    | 907.4s     |
| 1.25.0 c-backend    | 965.2s     |
| 1.25.0 llvm-backend | 929.9s     |

I see a slight compilation regression between 1.24.1 and 1.25.0, but nothing major and could be within the noise on a busy-ish system.
