### ISSUE TITLE
Adding an overload to `map.getValue()` to avoid halting

### ISSUE THREAD

**Issue by bmcdonald3** [chapel-lang/chapel#18786]
## Summary
The `getValue()` map method halts if the value is not found today and this can cause problems in a parallel context, where wrapping the `getValue()` check in a `if myMap.contains(val)` can still halt if the value has been removed in the time from the contains call and the using of `getValue()`. This can be avoided by adding an overload to `getValue()` to take a "sentinel" value that will be returned if the value is not found, rather than halting.

### Proposal 1: Add an overload to `getValue()` to return a "sentinel" value
```
proc map.getValue(key) { ... }    // current getValue(), halts if 'key' is not found
proc map.getValue(key, sentinel) { ... }  // returns 'sentinel' if the key is not found
```
Usage:
```
var value = map.getValue(key, 0) + 1; // never halts; value either 1 or key+1
```

### Proposal 2: Switch to throw instead of halt to allow catching the error
```
proc map.getValue(key) throws { ... } 
```
Usage:
```
var value: int;
try {
  value = map.getValue(key) + 1;
} catch {
  value = 1;
}
```

### Proposal 3: New function that returns a sentinel and boolean false if key not found
(the name would definitely need some rethinking...)
```
proc map.getValue(key) { ... } 
proc map.didGetValue(key, sentinel) { ... }
```
Usage:
```
var (value, found) = map.didGetValue(key, 0); // if 'key' not found then 'value'=0 and 'found'=false
```

## Previous discussion
See the original user issue: https://github.com/chapel-lang/chapel/issues/17498
Arguments against proposal 1:
- `getReference`/`getBorrowed` don't have as clear of a solution, making some assymetry
- the syntax isn't particularly elegant and could be better (e.g., `var v = try m.getValue(0) else 1;`, but something like this wouldn't work today and would be a bigger change)

**Comment by mppf** [comment]
My 2 cents: I like Proposal 2. It is wordy today but in the future I think we can and should make idioms like `var v = try m.getValue(0) else 1;` mentioned above work to make it less wordy

**Comment by aconsroe-hpe** [comment]
I like Proposal 2. Proposal 2/3 can be implemented in terms of each other but Proposal 1 is less capable (you may not always have a value that is distinguishable as a sentinel).

**Comment by bmcdonald3** [comment]
Experimenting with each of these in Chapel, I agree with you guys that proposal 2 seems to be the best of the proposed solutions here in terms of flexibility and not locking us into a strange method for 2.0 that we aren't happy with. Where I would push against that proposal in favor of proposal 1 is:
1. All of the map methods use the halting format rather than the throwing format today, so changing this would make it inconsistent with the rest of the module, implying to me that if we choose that here, we would probably want to refactor the entire module to match that format
    - setting this precedence here seems to imply that we should rework the other modules like Heap, List, etc. that do the same thing to match this format
2. Performance could get worse from switching from halting -> throwing for the map module, since bounds check halts are folded out with `--fast`
    - don't have real numbers for this, could collect if they would be valuable

> you may not always have a value that is distinguishable as a sentinel
Wouldn't the regular method that exists be better suited for this case then? If you don't have a suitable sentinel, you probably have different concerns than what the sentinel solution proposes.

**Comment by aconsroe-hpe** [comment]
> setting this precedence here seems to imply that we should rework the other modules like Heap, List, etc. that do the same thing to match this format
This is a great point. I'm not sure it makes me want proposal 1, but it does give me pause about making this change in isolation. Maybe we need to consider this in the ongoing discussion on containers and parallel safety etc

**Comment by bradcray** [comment]
Is there a proposal 1.5, in which we would support:

```chapel
proc map.getValue(key) throws { ... } 
proc map.getValue(key, sentinel) { ... }
```

This seems like it would have the advantage of making the default getValue() safe/comprehensible/halt-free, while also giving people the ability to avoid the `try` if they do have a good sentinel and this simplifies their computation by letting it just plug along.  For example:  `const numBrads = MyHist.getValue("Brad", 0);` seems much simpler than having a try...catch to get the equivalent.

The fact that two distinct users have requested the sentinel value makes me hesitant to drop it on the floor (and it seems like an obvious value-add).

**Comment by bradcray** [comment]
I didn't notice the thumbs-ups until now, so wanted comment here in case @bmcdonald3 didn't either (knowing that he felt a little stuck on this yesterday).  It sounds like we have the green light to go with proposal 1.5 from those who've commented on this.  Though Lydia reacted to one of the previous proposals and not this one—and it'd be good to have her on-board since she's working on parallel-safe collections.  I can't recall whether there's been a broader design announcement about this (ever / recently), and if not, we should probably make sure others are good with it as well.

FWIW, the rules of thumb that I'm taking from this / like about this is:

* things that are likely to be called in parallel contexts and to be race-y (like `getValue()`) generally shouldn't halt—instead, should either throw or return a bool or a sentinel (this one can't cleanly return a bool b/c it has to return the value, and there may not be an obvious sentinel)
* For something that throws, I like having an option that's perhaps a bit more involved / less general that doesn't throw, like the sentinel-accepting getValue() here.

**Comment by mppf** [comment]
> things that are likely to be called in parallel contexts and to be race-y (like getValue()) generally shouldn't halt—instead, should either throw or return a bool or a sentinel (this one can't cleanly return a bool b/c it has to return the value, and there may not be an obvious sentinel)

For me, it being possible to call it in a parallel context doesn't have anything to do with why I don't think it should halt. It's more that normal usage of a map/set involves working with keys that might not be present (vs what I view as the typical usage of arrays where it is a program error for there to be out of bounds access). At the same time, halting is a pretty limiting strategy for error handling, so we should only be using it we're pretty sure that it's not reasonable for the code to respond to the error somehow (in other words, when we use a halt, we are saying that the only explanation for the error condition is if there is a bug in the program, but I don't feel that way about the operation of getting a value from a map).

**Comment by bmcdonald3** [comment]
@lydia-duncan are you OK with moving forward with Brad's proposal of both a `throws` method and a `sentinel` method for now? 

Also, I will be moving some of the discussion here about parallel safety over to https://github.com/chapel-lang/chapel/issues/18825 to keep track of that on the more central parSafe issue, unless anyone has any objections.

**Comment by bradcray** [comment]
> It's more that normal usage of a map/set involves working with keys that might not be present (vs what I view as the typical usage of arrays where it is a program error for there to be out of bounds access).  [and rest of this paragraph]

I buy that distinction, and would say that that better describes what was in the back of my mind.

**Comment by lydia-duncan** [comment]
Thanks for the ping!  I had read through the issue and reacted, but hadn't turned notifications back on so I missed updates.  I like the direction proposed
