### ISSUE TITLE
Bug in bigint.remove 

### ISSUE THREAD

**Issue by tiger-yash** [chapel-lang/chapel#18794]
### Summary of Problem

The purpose of the bigint.remove function is to remove all instances of the factor (f) arg from the other arg (a), storing the result in this and returning the number of times the factor was removed. 
But when `a` is arg(f) raised to the power some  positive integer `q>1`, then in that case the function returns `1` for all such `q>1`.

### Steps to Reproduce

**Source Code:**

error.chpl
```chapel
use BigInteger;

var a=new bigint();
var b = new bigint(16);
var c=new bigint(4);

a.remove(f=c,a=b);
writeln(a);
```

**Compile command:**
`chpl error.chpl`

**Execution command:**
 `./error`

### Configuration Information

- Output of `chpl --version`: 1.26.0 pre-release
- Output of `$CHPL_HOME/util/printchplenv --anonymize`: 
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none +
CHPL_TASKS: fifo +
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: cstdlib +
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled *
CHPL_HWLOC: none
CHPL_RE2: none +
CHPL_LLVM: none +
CHPL_AUX_FILESYS: none
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

**Comment by tiger-yash** [comment]
I would also like to try and fix it along with(or after) issue #17732

**Comment by lydia-duncan** [comment]
I think the method is actually working as intended.  Try running the following modification:
```chapel
use BigInteger;

var a=new bigint();
var b = new bigint(16);
var c=new bigint(4);

writeln(a.remove(f=c,a=b)); // This line is different - it prints the return value
writeln(a);                             // This line prints the remainder after removing the factor
```
The output of that program is
```
2
1
```
which I believe is correct - the return value of the function is the number of times the factor was removed (2, since 16 is 4^2), and the value stored in a is the remainder after removing 4 twice (`(16 / 4) / 4 = 1`).  Does that make sense?

**Comment by tiger-yash** [comment]
Oh, I got a little different impression on how the function works after reading the definition. Sorry, my bad.

**Comment by lydia-duncan** [comment]
No worries, it happens :)
