### ISSUE TITLE
Gratuitous errors during compiler build

### ISSUE THREAD

**Issue by jlbyrne-hpe** [chapel-lang/chapel#18806]
### Summary of Problem

@bradcray: as requested

When building the compiler  with CHPL_LLVM=bundled and CHPL_TARGET_COMPILER=clang, 3 error messages --- 
Error: command not found: /.../third-party/llvm/install/linux64\ -x86_64-gnu/bin/clang--- from
printchplenv are output during the early build process before the bundled compiler is built. It just takes a few seconds.

The first two errors are from the printchpenv commands in the top-level configure script; the the third is from the
"export CHPL_MAKE_CHPLENV_CACHE" in make/Makefile.base script. 

I don't know of actual issue resulting from the errors, but any error messages are a source of  potential concern and confusion. 

### Steps to Reproduce

Start with a clean Chapel source tree:
./configure
make

### Configuration Information

- Output of `chpl --version`:
-chpl version 1.26.0 pre-release (d850c491a1)
  built with LLVM version 11.0.1
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: clang *
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: fifo *
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: cstdlib *
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled
CHPL_HWLOC: none
CHPL_RE2: bundled *
CHPL_LLVM: bundled *
CHPL_AUX_FILESYS: none

**Comment by aconsroe-hpe** [comment]
Can't reproduce this, but noticed that the error message you posted

> third-party/llvm/install/linux64\ -x86_64-gnu/bin/clang

includes a backslash escape for a space. Just want to double check that is from the actual error message? There shouldn't be a space in in `linux64-x86_64-gnu` so that could be a good clue if you are seeing a space.

**Comment by bradcray** [comment]
> Just want to double check that is from the actual error message? 

I'm guessing that's from a shell copy-paste...?

**Comment by jlbyrne-hpe** [comment]
From the copy-paste, sorry. I thought I had cleaned it up.

@aconsroe-hpe: as to not being able to reproduce it, can you do a "git clean -xdf" on the current main and do a printchplenv? On my system, without a chplconfig, the defaults show the problem.

**Comment by aconsroe-hpe** [comment]
Ahh got it now. Before LLVM bundled has been built, `third-party/llvm/install/linux64-x86_64-gnu/bin/clang` doesn't exist so something in printchplenv must be complaining it can't find clang
```
→ CHPL_LLVM=bundled CHPL_TARGET_COMPILER=clang printchplenv

Error: command not found: /home/andrew/Repos/chapel/third-party/llvm/install/linux64-x86_64-gnu/bin/clang
machine info: Linux localhost.localdomain 5.15.5-100.fc34.x86_64 #1 SMP Fri Nov 26 00:52:21 UTC 2021 x86_64
...
```

**Comment by aconsroe-hpe** [comment]
The message is from `has_std_atomics` in `util/chplenv/compiler_utils.py` trying to determine if the target compiler supports std atomics. It defaults to `False` which is why the `princhplenv` succeeds even though executing the command doesn't work (as mentioned, that is because LLVM hasn't been built yet).

I'm not sure the right course of action here:
1) Issue a warning instead here
2) Handle the bundled LLVM case here specially

**Comment by bradcray** [comment]
Thanks for running with this, @aconsroe-hpe .  Let's check with @mppf to see whether he has any guidance here because (a) he seems to be one of the few devs with active code in that routine, (b) he's well familiar with bundled LLVM, and (c) I feel as though he solved a thematically similar error recently.

**Comment by mppf** [comment]
I think it'd be reasonable to adjust `chpl_atomics.py` `get` always use `cstdlib` atomics for `CHPL_LLVM=bundled CHPL_TARGET_COMPILER=clang. That is the shortest and least disruptive.

Today, it seems that we only check `has_std_atomics` for `clang`.
(I'm not quite sure why that is. A guess is that it might have to do with the way that clang relies on GCC / glibc headers for some features).
It might be possible to change it into something we require (i.e, we still check `has_std_atomics`, but issue an error if it is false).

**Comment by jabraham17** [comment]
I've opened https://github.com/chapel-lang/chapel/pull/25477 to implement @mppf's suggestion
