### ISSUE TITLE
What should the special methods for context managers be named?

### ISSUE THREAD

**Issue by dlongnecke-cray** [chapel-lang/chapel#18811]
What should the special methods for context managers be named?

The `manage` statement requires a type to define two special methods
in order to be used as a manager:

`enterThis()` - Called upon entry, and can return a resource
`leaveThis()` - Called upon exit

The current names are a combination of my personal preference
as well as existing convention for special methods (specifically
the `This` suffix).

However the names are just placeholders. Below are some options.

For these options, I think we should focus on the _base_ name of the
options rather than any specific decoration (e.g. given the name
`foo`, focus on `foo` rather than `fooThis` or `__foo__`).

This is because naming conventions for special methods are still
under discussion, see comments in: https://github.com/chapel-lang/chapel/issues/18340

## 😄   `enter` / `exit`

- These are the names that Python uses
- I scrolled through PEP343 and some earlier drafts of the Python
  `with` statement but wasn't able to see why these names were
  settled on in particular

## 🚀  `enter` / `leave`

- The names we currently use, I like them because they are symmetrical
- Entirely a personal preference on my part

## 👀 : `setup` / `cleanup`

- I think these names might be more descriptive w.r.t. what is
  happening, I realized that I often found myself describing `exit`
  as the "cleanup" method
- The previous pairs of names make me think of critical sections
  rather than preparing a context

---

Let me know if you have other proposals.

**Comment by bradcray** [comment]
enter/exit seem more like naturally opposing / related words than enter/leave to me.

That said, `exit()` has the slight downside of being used as a standlone "exit the program" routine, which sets up a synonym situation which may not be ideal (I think there's no technical conflict, just the potential for confusion).  Of course, if it were `exitThis()` or `@exit()` or `exitMgmt()` or `exitManage()` or some other marking, then that problem would go away.

**Comment by dlongnecke-cray** [comment]
I just realized that you can't respond with 🌵 to a post, I'll change the emote tags.

I kind of find myself in the opposite camp, personally I've found `enter` and `leave` to be more naturally opposing (in addition to having the same length, which is very appealing to me).

I wanted this thread to focus on the base name rather than the method of namespacing (no matter what the namespace might be), but you're right that the means of namespacing can influence the decision somewhat.

**Comment by mstrout** [comment]
I prefer `enter` and `exit` due to its use in physical signs in buildings and their historical use in Python.

One thing I like about `writeThis`, `readThis`, and potentially `hashThis` is that `this` is a self reference to an object instance and those methods act on the object.  For context managers, I don't think we should use the `This` postfix.  Instead I like `exitCtx` or `exitMgmt` or something that indicates what is being entered and exited.

**Comment by dlongnecke-cray** [comment]
Make sure to vote for `enter` / `exit`! 😄

**Comment by cassella** [comment]
None of the options so far really suggest to me what the thing returned from "`enter()`" is.  But I don't have a suggestion that does.

**Comment by bradcray** [comment]
> None of the options so far really suggest to me what the thing returned from "enter()" is. But I don't have a suggestion that does.

Paul's comment resonates with me a bit as well.  I think due to not having written any of these, and not reading the documentation, I find myself wondering "Are we entering/leaving a management region for ourself?  (`this`)  Or are we essentially a context management factory that's creating and returning something to be managed that we'll then reclaim/destroy on the exit?"

**Comment by dlongnecke-cray** [comment]
The manager expression (the `foo` in `manage foo`) can have its "enter context" method return anything. Any type, with any storage (`ref`/`const ref`/`var`).

What I'm getting from discussion so far is that perhaps a more verbose name is appropriate. And since this method is not intended to ever be called by a user directly (and it would be very strange to see such code), I think this is a time where perhaps a more verbose method name is appropriate.

The problem is finding a name that doesn't sound clunky or ridiculous. `enterContextAndMaybePrepareResource`? That's a _terrible_ name!

**Comment by mppf** [comment]
enterContext isn't bad, though

**Comment by bradcray** [comment]
Or something along the lines of `genManaged[Value]` or `getManaged[Value]` or `newContext`/`createContext` to focus more on the fact that the routine is generating something and less on the enter/exit?  (Or... can an enter method _not_ return something?  I suppose it could if it's just printing something on enter and exit?).

**Comment by dlongnecke-cray** [comment]
Yeah it's also possible for the enter method to return nothing at all. I like the idea of `enterContext`, that notion is what made me gravitate towards something like `setup`.

- `enterContext`
- `setupContext`
- `prepareContext`

**Comment by bradcray** [comment]
@dlongnecke-cray / @DanilaFe : I'm closing this now as we've decided to stabilize these on `enterContext()` and `exitContext()`.  Let me know if you disagree.
