### ISSUE TITLE
test/regex/ferguson/readfre.chpl fails on OSX

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#18821]
I think there are two issues with the test, that have snuck in while OSX testing has been offline

This test uses a helper file defined in the same directory with the name regex.chpl.  Because OSX doesn't care about capitalization in its file names, this conflicts with the standard module Regex.chpl and we get the message:
```
> warning: Ambiguous module source file -- using ./Regex.chpl over $CHPL_HOME/modules/standard/Regex.chpl
```
I believe this test used to pass when the standard module was named Regexp, it seems to be an older test.

We also get the message
```
> ./Regex.chpl:3: error: ambiguous config name (t)
> readfre.chpl:4: note: also defined here
> readfre.chpl:4: note: (disambiguate using -s<modulename>.t...)
```
and I'm not sure when that error snuck in, I think it didn't happen at the same time.

**Comment by lydia-duncan** [comment]
Logging this in case anyone else runs into it.  I don't know that I'll have time to track it down this sprint, I noticed it when I was working on the iostyle deprecation

**Comment by bradcray** [comment]
Proposed fix in https://github.com/chapel-lang/chapel/pull/18823.
