### ISSUE TITLE
`DateTime` module stabilization - removing ambiguous functions

### ISSUE THREAD

**Issue by aconsroe-hpe** [chapel-lang/chapel#18834]
As part of the `DateTime` module review, we identified three functions that seem ambiguous and eligible for deprecation and ultimately removing. They are:

* `datetime.today` - This function refers to `today` for a `datetime`, where the `time` portion is ambiguous what the user desires. 
  * Suggested to replace uses with `datetime.now` or `date.today`
* `operator datetime.-(dt: datetime, d: date):timedelta` - the `date` gets promoted to `datetime` with time `00:00:00`.
  * Suggested to replace uses with `dt.date - d` or `dt - new datetime(d, new time())` (with a new `datetime` init overload)
* `proc type datetime.timeSinceEpoch():real` - This function is a `proc type` on datetime to return a real and doesn't pertain to a `datetime` in any way
  * Suggested to remove altogether or move `timeSinceEpoch` as a free function in the module

**Comment by aconsroe-hpe** [comment]
Just noting that `datetime.timeSinceEpoch` is interlinked with stabilizing `Time` module so this is an ongoing discussion.

For the other two, I still feel good about deprecating these after seeing these with a fresh mind.

**Comment by ben-albrecht** [comment]
@aconsroe-hpe - I split off the `timeSinceEpoch` discussion into https://github.com/chapel-lang/chapel/issues/18834.

**Comment by daviditen** [comment]
Closed with https://github.com/chapel-lang/chapel/pull/19934
