### ISSUE TITLE
`DateTime` module stabilization - add formal types to `proc init` formals

### ISSUE THREAD

**Issue by aconsroe-hpe** [chapel-lang/chapel#18832]
As part of the module review for `DateTime`, we'd like to add formal types to the `init` proc's. This change applies to each `date`, `time`, `datetime`, and `timedelta`.

The proposed signature changes would look like:

## date

 `proc date.init(year, month, day)`
->
`proc date.init(year:int, month:int, day:int)`

## time

`proc time.init(hour=0, minute=0, second=0, microsecond=0, in tzinfo: shared TZInfo? = nil)`
->
`proc time.init(hour:int=0, minute:int=0, second:int=0, microsecond:int=0, in tzinfo: shared TZInfo? = nil)`

## datetime

```
  proc datetime.init(year, month, day,
                     hour=0, minute=0, second=0, microsecond=0,
                     in tzinfo: shared TZInfo? = nil)
```
->
```
  proc datetime.init(year:int, month:int, day:int,
                     hour:int=0, minute:int=0, second:int=0, microsecond:int=0,
                     in tzinfo: shared TZInfo? = nil)
```

## timedelta

`proc timedelta.init(days=0, seconds=0, microseconds=0, milliseconds=0, minutes=0, hours=0, weeks=0)`
->
`proc timedelta.init(days:int=0, seconds:int=0, microseconds:int=0, milliseconds:int=0, minutes:int=0, hours:int=0, weeks:int=0)`

**Comment by bradcray** [comment]
This mostly seems like a no-brainer to me.  One thing that gives me pause here that I hadn't noticed during the discussion is:  Why is the `tzinfo` argument a `shared` rather than a `borrowed` (say)?  And is the implication that the only tzinfo values I'll be able to send into this/these routines is a shared one?  With a `borrowed`, I believe that the actual could be any of the four types.  Or should we just not mention the management type?  (in which case, I'm forgetting whether that means `borrowed` or "generic w.r.t. the class management type).

**Comment by aconsroe-hpe** [comment]
> Why is the tzinfo argument a shared rather than a borrowed (say)? 

I've put off trying to answer this because timezones are in flux (see #18941).

Would it be wise to move forward by adding a new typed init method that doesn't mention timezones at all? Today, we can make that change and have the tzinfo be nil. So we would have

```chapel
proc date.init(year:int, month:int, day:int) {}
proc time.init(hour:int=0, minute:int=0, second:int=0, microsecond:int=0) {}
proc datetime.init(year:int, month:int, day:int, hour:int=0, minute:int=0, second:int=0, microsecond:int=0)) {}
```

Though now in looking at this again, my two thoughts were:
1)  Why give `hour` etc default values 0"
  * `microsecond` is the only one that "feels" like it could be default but I think that's a gut reaction and arbitrary
2) Why have the `datetime.init` at all instead of only `datetime.init(d: date, t: time)`?

**Comment by bradcray** [comment]
> Why give hour etc default values 0"

My guess: "Because midnight is a reasonable default time?"

> microsecond is the only one that "feels" like it could be default but I think that's a gut reaction and arbitrary

Depending on what I was using it for, I could imagine not having to want to specify seconds either.  ("e.g., the meeting starts on Monday at 8:30am")

> Why have the datetime.init at all instead of only datetime.init(d: date, t: time)?

Any reason not to have both?

**Comment by aconsroe-hpe** [comment]
So then would it make more sense to default all fields to 0 instead of picking and choosing?

> Any reason not to have both?

Not that I can think of
