### ISSUE TITLE
`DateTime` module stabilization - C interop functions

### ISSUE THREAD

**Issue by aconsroe-hpe** [chapel-lang/chapel#18833]
As part of the module review for `DateTime`, we identified a list of methods that are closely tied to their C counterpart. With the intention of not locking in this behavior or constraining our implementation to always stay tied to C, we'd like to move, remove, rename, or mark as unstable.

One proposal might be to keep them in their current place (same module and as methods) with an added prefix `c_`, like we have for `c_str` on a string.

| from                 | to                     | notes
|----------------------|------------------------|--------------------|
| `date.timetuple`     | `date.c_timetuple`     | returns a `struct tm`
| `datetime.timetuple` | `datetime.c_timetuple` | returns a `struct tm`
| `datetime.strptime`  | `datetime.c_strptime`  | parses a string as in `strptime(3)`
| `datetime.strftime`  | `datetime.c_strftime`  | parses a string as in `strftime(3)`
| `date.ctime`         | `date.c_ctime`         | gives the date as in `ctime(3)` eg `"Wed Jun 30 00:00:00 1993\n"`
| `datetime.ctime`     | `datetime.c_ctime`     | gives the datetime as in `ctime(3)` eg `"Wed Jun 30 21:49:08 1993\n"`

This relates to:
  * Potential new home for `struct tm`: #18012
  * Potential new home for C interop: #18013

**Comment by aconsroe-hpe** [comment]
I don't think we should keep them with an alternate spelling like `c_timetuple` because I don't know of any necessity for interop (whereas something like `string.c_str()` is necessary for interop and can't be easily implemented by the user).

**Comment by bradcray** [comment]
> because I don't know of any necessity for interop

We could also add that capability later if/when the need arose...

**Comment by daviditen** [comment]
Here's some example usage of these:
```chapel
use Time;

var thisDay = date.today();
var thisMoment = datetime.now();

var tmDay = thisDay.timetuple();
var tmMoment = thisMoment.timetuple();

writeln("date.timetuple: ", tmDay.tm_mon, "/", tmDay.tm_mday, "/", tmDay.tm_year);
writeln("datetime.timetuple: ", tmMoment.tm_hour, ":", tmMoment.tm_min, ":", tmMoment.tm_sec);

writeln("date.ctime: ", thisDay.ctime());
writeln("datetime.ctime: ", thisMoment.ctime());

var dt = datetime.strptime("12:59:59.008000", "%T.%f"); // create a datetime

var dt2 = new datetime(2004, 12, 31, 6, 22, 33);
assert(dt2.strftime("%m %d %y %S %M %H %j") == "12 31 04 33 22 06 366");
```

These were modeled after Python, so Python has these exact same functions.

Rust doesn't have matching functions, but has struct types to provide the functionality.
`TimeTuple` and `StrftimeItems`.

Pros to keeping as-is
* Matches the behavior of Python

Cons to keeping as-is
* Is pretty low-level compared to other date/time/datetime things
  - Essentially just calling into C functions

Pros to renaming them with a prefix 'c_':
* Makes it clear that they are calls into underlying C functions

Cons to renaming them with 'c_' prefix:
* Ugly, uses an underscore

Pros to marking them unstable:
* There is some b uy in from team leadership for doing this
* Gives us more time to decide what to do with them while allowing us to declare the Time module stable

Cons to marking unstable:
* Kicks the can down the road

I propose marking these functions unstable.

**Comment by daviditen** [comment]
The design subteam has reached consensus that these functions should be marked unstable.

If we were to keep them we should add 'c_' prefix to make it clear that these are shims to C. We would prefer to instead have a higher level replacement, but it is not a breaking change to add that at a later date. Instead, we will mark these as unstable in order to allow Time/DateTime stabilization to proceed. We suspect that when we have high-level replacements we will want to remove these, so we don't want to call them stable at this point which would require them to stay at a later date.
