### ISSUE TITLE
const in task intent applied to arrays breaks the compiler

### ISSUE THREAD

**Issue by twesterhout** [chapel-lang/chapel#18851]
### Summary of Problem

Using `const in` task intent with an array results in `internal error: OPT-REM-ING-0380 chpl version 1.25.0` 

### Steps to Reproduce

**Source Code:**

```chapel
proc main()
{
  var xs : [0 ..# 3] int = [1, 2, 3];
  coforall loc in Locales with (const in xs) do on loc {
    writeln(xs);
  }
}
```

**Compile command:**

chpl -o error error.chpl

### Configuration Information

- Output of `chpl --version`: 1.25.0

**Comment by bradcray** [comment]
Als, @twesterhout : I'm finding that while the compiler does throw an internal error (and shouldn't), if I use `--ignore-errors`, the program compiles and runs (though it'll still print the error).

I'll see whether I can remove the error (which, at first glance, appears to be an overly aggressive assertion) without anything bad happening.

**Comment by twesterhout** [comment]
@bradcray thanks for looking into it. I haven't tried compiling with `--ignore-errors`. I'm afraid the code where I initially encountered the error is way too unstable to detect whether the program generated with `--ignore-errors` behaves correctly (it's just as likely that it'll behave incorrectly because of some other bug of mine).

**Comment by bradcray** [comment]
OK.  From what I've seen so far, you should be able to use `const in` intents like this with `--ignore-errors` to work around the internal error without penalty.  Or you could grab https://github.com/chapel-lang/chapel/pull/18852 which essentially removes the assertion in question.  My testing is still running, but if there are no surprises, I plan to get that reviewed and merged today.

**Comment by bradcray** [comment]
@twesterhout: You probably got a notification from GitHub, but just to close the loop, the fix for this has been merged to `main` now, and thanks again for letting us know about this bug.
