### ISSUE TITLE
Barrier module stabilization - waiting policy

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#18864]
Today the barrier initializer has a barrierType argument.

```chpl
proc init(numTasks: int, barrierType: BarrierType = BarrierType.Atomic, reusable: bool = true)
```

This lets users select between atomics or syncs to implement the atomic. The reason we care is that atomics will spin wait and will likely have lower latency, but use more CPU and syncs will have higher latency but use less CPU.

I think keeping this concept about active waiting vs blocking is important in the longer term, but I'm not sure we should make the enum about the implementation details. I wonder if this could instead be a "waiting policy" enum or something more generic that describes the intent rather than the implementation. If we keep an enum of sorts to control this behavior, I think we should make it param. It being non-param currently requires dynamic dispatch to select the implementation and I think we need barriers to have as little overhead as possible. I also wonder whether we need this control for the initial stabilization effort. It would seem easiest to get rid of the waiting policy for now, stabilize, and then we can add it back in later as we need it and have time to optimize.

**Comment by daviditen** [comment]
Looking at a few other languages:

C++ and Rust don't appear to have a policy choice, but Julia supports several types of barriers implemented as different types.

C++: https://en.cppreference.com/w/cpp/thread/barrier
Rust: https://doc.rust-lang.org/std/sync/struct.Barrier.html
Julia: https://juliaconcurrent.github.io/SyncBarriers.jl/dev/

I like Elliot's suggestion of removing the policy choice for now and potentially adding it back later if necessary.

**Comment by mppf** [comment]
Supposing that we remove the waiting policy for now -- is it clear that having `atomic` be the only behavior is OK? In particular, is `atomic` acceptable for most of the use cases of barriers that we have?

**Comment by daviditen** [comment]
Searching in our tests I only see 'Atomic' barriers except for a few tests that are specifically testing the barriers. I'm not aware of anything currently intentionally using `Sync`.
