### ISSUE TITLE
Barrier module stabilization - method names

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#18862]
Once a barrier is created, the interface is pretty simple. You can either do a single-phase `barrier()` call or you can do a split-phase barrier with `notify()` and `wait()`. These are pretty standard and the wait/notify is simply an optimization to allow you to do some work while waiting for other tasks to arrive.

We also have `check` and `reset` calls. `check` just lets you ask if the barrier is complete and `reset` is a way to change the number of tasks participating in the barrier. Arguably instead of doing a `reset` you could just destroy the barrier and create a new one, but that's potentially expensive so I think `reset` is also an optimization of sorts. I'm not sure the name is particularly intuitive though. I don't personally know of any use cases for `check`, but you could imagine combining it with a split-phase barrier to see if you should keep doing some work on your own or if others have completed the barrier. I'm not sure if `check` has any implications for potential implementations (i.e. does it force you into specific implementations that might not be needed if you didn't support it.)

See https://github.com/chapel-lang/chapel/issues/18860 for comparisons to other languages.

---

Here's some trivial examples just to demonstrate what the methods may look like in practice:

Simple barrier:
```chpl
var b = new barrier(10);

coforall 1..10 {
  updateMyPortionOfSharedData();
  b.barrier();
  readOtherPortionsofSharedData();
}
```

Split-phase barrier:
```chpl
var b = new barrier(10);

coforall 1..10 {
  updateMyPortionOfSharedData();
  b.notify();
  updatePortionOfLocalData();
  b.wait();
  readOtherPortionsofSharedData();
}
```

Split-phase barrier with check:
```chpl
var b = new barrier(10);

coforall 1..10 {
  updateMyPortionOfSharedData();
  b.notify();
  while !b.check() {
    doBackgroundTask();
  }
  readOtherPortionsofSharedData();
}
```

Contrived reset:
```chpl
var b = new barrier(10);

for nTasks in 1..10 by -1 {
  b.reset(nTasks);
  coforall 1..nTasks {
    updateMyPortionOfSharedData();
    b.barrier();
    readOtherPortionsofSharedData();
  }
}
```

**Comment by e-kayrakli** [comment]
> Arguably instead of doing a reset you could just destroy the barrier and create a new one, but that's potentially expensive so I think reset is also an optimization of sorts. I'm not sure the name is particularly intuitive though.

`reset` sounds more like "Oh, I said `notify`, but I realized I've got more work to do, so please `reset` my state." I don't know whether anybody ever needs that, but I agree that the name is not intuitive.

It is funny, though. Looks like Java also calls it `reset` where they have `getNumberWaiting` instead of `check`. That's inconsistent verbosity to me. Feels like they should have `setNumberParticipating` or something :)

But joking aside, I think we can go for a more verbose method name if we decide to keep the functionality. `setNumTasks`, maybe?

**Comment by ronawho** [comment]
In discussions we decided we're happy with `wait()`, `notify()`, and `barrier()`. 

There was some discussion about whether we'd consider using `arrive` instead of `wait` to match java/c++, but none of us really like that name and much preferred notify.

We also had some discussion about whether `barrier()` should be `notifyAndWait()`, but also weren't fond of that and believe `barrier()` is clear and likely the common use case so no need to make it more verbose.

**Comment by ronawho** [comment]
We continue to want a better name for `check()` assuming we keep the functionality (may reconsider if we determine implementing it would limit implementation efficiency). While brainstorming we put together the following list (comments are my thoughts and may not reflect the groups, and other suggestions are welcome, I just wanted to capture all the ideas we tossed out):

```
- `pending`/`isPending`
- `allNotified`
- `canProceed`
- `willWait`
- `ready`
- `converged`                // feels to math-y to me
- `done`/`isDone`            // might imply that barrier can't be used afterwards?
- `complete(d)`/`isComplete` // similar to done and also conflates with this.complete()?
- `notified`                 // feels like a query on just the current task, not all
```


I also personally think I'd like something that could be cleanly used in a while loop without negating. e.g. prefer something like:

```chpl
while b.pending() { }
```

over:

```chpl
while !b.ready() { }
```


That said, even though it would be a negation, I find `allNotified` interesting since it reuses "notify". While typing this up I thought of writing something like `while b.waiting()`, which also has nice symmetry, but I'm not sure yet if I like it or not.

**Comment by e-kayrakli** [comment]
> `while b.waiting()`

This describes something else though, right? `willWait`/`wouldWait` would be the right thing to use.

>  I find allNotified interesting since it reuses "notify". 

I agree that `allNotified` is the most descriptive among the alternatives. I am not against it but I still prefer `pending` over it because, (1) it is one word, (2) typical use-case doesn't need negation.

**Comment by lydia-duncan** [comment]
This was resolved in the discussion in May
