### ISSUE TITLE
Barrier module stabilization - should re-usability be selectable

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#18865]
Today the barrier initializer has a reusable argument:

```chpl
proc init(numTasks: int, barrierType: BarrierType = BarrierType.Atomic, reusable: bool = true)
```

If the barrier doesn't need to be reusable, we can optimize a little bit of work out.  It's not obvious to me how much time this saves in practice, and we don't have any current non-reusable use-cases.

Other languages (C++, Java) have different types called latches. If we want to keep this non-reusable optimization I think it's an open question for whether it should be a different type or just a `param` argument. Other languages don't have params so in order to actually optimize any branches out they need a different type, but we don't have to do that ourselves.

So the open question here is if we want to keep the non-reusable optimization in and if so how do we expose that to users. My preference for stabilization would be to just remove the feature for now and it can always be added back in as a different type or an optional argument. I would like to do a survey of use-cases for latches in other languages before making any final calls here.

**Comment by e-kayrakli** [comment]
FWIW, I find the discussion here a bit similar to data strucutre implementation discussions. The reusability *almost* calls for a different type to me based on the direction we are going with data structures.

**Comment by ronawho** [comment]
During the last review of the barrier module I think we discussed this a little bit (as well as should local vs. distributed barriers be different types) and I think the general sentiment was that for data structures we're only talking about having different types because the API would be different but here the API would be the same.

And while other languages use a different type for latches, I think this is at least partially because they don't have constructs like params so if they want latches to be faster than have to be different types to do compile time specialization. Granted it's possible a different type is still the answer, I'm just saying I don't think other languages have a choice, but we do.

**Comment by bradcray** [comment]
> The reusability almost calls for a different type to me based on the direction we are going with data structures.

Not taking a side, but I think this is still an ongoing discussion and exploration, and also agree with Elliot:

> we're only talking about having different types because the API would be different but here the API would be the same.

One other reason we've discussed is that the implementations are so different that it adds annoyance to the implementation effort.  Of course, it would be nicer to manage four distinct implementations of the same interface if we had interfaces implemented.

**Comment by e-kayrakli** [comment]
Hmm, those are good points.

**Comment by daviditen** [comment]
C+pthread: pthread_barrier_wait(pthread_barrier_t*) is reusable: "When the required number of threads have called pthread_barrier_wait()...the barrier shall be reset to the state it had as a result of the most recent pthread_barrier_init() function that referenced it."
MPI: The second answer here https://stackoverflow.com/questions/13305814/when-do-i-need-to-use-mpi-barrier demonstrates that MPI barriers are reusable
OpenMP: There is just a single global barrier that is reusable: "#pragma omp barrier".

It seems that the standard is barriers are always reusable and it is not configurable. There are three obvious directions here:

1. Reusability is configurable on a per barrier object basis. Status quo.
2. All barriers are reusable. Matches the precedent from MPI, OpenMP and Pthreads
4. No barriers are reusable.

**Comment by ronawho** [comment]
I agree that barriers are reusable in other languages. Other languages (if they support them) tend to use "latch" to describe non-reusable barriers. I think the reason it's not obvious to me which direction to go is because most other languages don't have a compile-time means of changing the behavior of the type so reusability would require an execution-time check, which would eliminate some if not all the optimization benefit of a latch but Chapel could use a param.

Maybe said a different way if the choice was between `latch` and `barrier` vs `barrier(param reusable)` it's not obvious which is preferable in Chapel and that's just not a choice in other languages. 

But given the IMO limited use-cases of a latch, I'd start with just removing `reusable` and later on we could add a new type or add the param selection in without breaking anything.

**Comment by lydia-duncan** [comment]
It looks like we've deprecated the `reusable` argument, does that mean this issue can be closed?
