### ISSUE TITLE
Warn if CHPL_TASKS=fifo with CHPL_RT_NUM_THREADS_PER_LOCALE=n

### ISSUE THREAD

**Issue by aconsroe-hpe** [chapel-lang/chapel#18867]
I ran into a program hang when using `CHPL_TASKS=fifo` with `CHPL_RT_NUM_THREADS_PER_LOCALE=1`. This makes sense in hindsight but had me head-scratching for a bit. I do see [the docs](https://chapel-lang.org/docs/usingchapel/tasks.html#id2) are pretty clear in this regard, but I'm wondering if we could issue a warning when `CHPL_TASKS=fifo` and `CHPL_RT_NUM_THREADS_PER_LOCALE` is set. The example of `=1` in my case is extreme, but hangs can also occur with higher limits depending on the program.

There has been some early discussion and we may want to also introduce an env var like `CHPL_RT_FIFO_THREADS_NO_WARN=yes` (or similar) to disable this warning.

**Comment by ronawho** [comment]
It's unlimited by default (well sometimes is limited by the comm layer, but in general it's whatever limit the system supports)

> we may want to also introduce an env var like CHPL_RT_FIFO_THREADS_NO_WARN=yes

Typically we do this with `<FEATURE>_QUIET` style. So `CHPL_RT_THREAD_LIMIT_QUIET` or maybe `CHPL_RT_NUM_THREADS_PER_LOCALE_QUIET` to match the main env var.

**Comment by bradcray** [comment]
> It's unlimited by default (well sometimes is limited by the comm layer, but in general it's whatever limit the system supports)

Oh yeah... I've clearly been living in the Qthreads for too long now.  Nevermind.

**Comment by aconsroe-hpe** [comment]
Took a stab in [this branch](https://github.com/chapel-lang/chapel/compare/main...aconsroe-hpe:warn/fifo-threads-limit?expand=1)

I think I would have rather done the check in `chpl_task_getenvNumThreadsPerLocale` so that we could tell if there was a limit set that wasn't the max limit. Here my warning is a bit of an over-approximation because if you set `MAX_LOGICAL` the warning doesn't make much sense

**Comment by ronawho** [comment]
Can you open that as a draft PR so I can add some comments to it?

**Comment by aconsroe-hpe** [comment]
@ronawho opened #18871 thansk
