### ISSUE TITLE
Barrier module stabilization - module and type names

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#18861]
The barrier module is named `Barriers`, where the plural aspect always strikes me as a bit odd. For history: `Barrier` -> `Barriers` renaming was done for https://github.com/chapel-lang/chapel/issues/6979 because the module name conflicted with the constructor. Since then, we changed from constructors to initializers and replaced the class with a record-wrapped class, but the record is still named `Barrier`. I think we've typically been going with lower case for records, so this is an exception to that rule.

Could we go back to a `Barrier` module with a `barrier` record at this point?  Would it make more sense to put this into a more general `Collectives` module?  Within the team there has been preference for `Collectives` module and `barrier` type. Note that we discussed why plural `Collectives` feels right but `Barriers` doesn't and the general sentiment is that there will be multiple collectives, but the plural form is also just the expected term. I think of it as "Collective Operations" shortened to just "Collectives".

**Comment by daviditen** [comment]
A slight problem with renaming the type from `Barrier` to `barrier` is that it has a method named `barrier` and so gets errors like:

```
$CHPL_HOME/modules/standard/Collectives.chpl:159: note: Constructors have been deprecated as of Chapel 1.18. Please use initializers instead.
$CHPL_HOME/modules/standard/Collectives.chpl:159: error: Type 'barrier' defines a constructor here
```

Should we rename the method? Should we enable methods that are named the same as their associated class/record now that constructors have been removed for several years?

**Comment by ronawho** [comment]
A DM I have from @mppf from a while ago:

"""
```diff
diff --git a/compiler/passes/normalize.cpp b/compiler/passes/normalize.cpp
index c29862984f..15d4d564cf 100644
--- a/compiler/passes/normalize.cpp
+++ b/compiler/passes/normalize.cpp
@@ -68,7 +68,7 @@ static bool        includesParameterizedPrimitive(FnSymbol* fn);
 static void        replaceFunctionWithInstantiationsOfPrimitive(FnSymbol* fn);
 static void        fixupQueryFormals(FnSymbol* fn);
 
-static bool        isConstructor(FnSymbol* fn);
+//static bool        isConstructor(FnSymbol* fn);
 
 static void        updateInitMethod (FnSymbol* fn);
 
@@ -117,7 +117,7 @@ static void        updateVariableAutoDestroy(DefExpr* defExpr);
 
 static TypeSymbol* expandTypeAlias(SymExpr* se);
 
-static bool        firstConstructorWarning = true;
+//static bool        firstConstructorWarning = true;
 
 /************************************* | **************************************
 *                                                                             *
@@ -163,7 +163,7 @@ void normalize() {
     } else {
       fixupQueryFormals(fn);
 
-      if (isConstructor(fn) == true) {
+      /*if (isConstructor(fn) == true) {
         Type* ct = fn->_this->getValType();
         if (firstConstructorWarning) {
           USR_PRINT(fn, "Constructors have been deprecated as of Chapel 1.18. Please use initializers instead.");
@@ -171,7 +171,7 @@ void normalize() {
         }
         USR_FATAL_CONT(fn, "Type '%s' defines a constructor here", ct->symbol->name);
 
-      } else if (fn->isInitializer() || fn->isCopyInit()) {
+      } else*/ if (fn->isInitializer() || fn->isCopyInit()) {
         updateInitMethod(fn);
       }
     }
@@ -4482,7 +4482,7 @@ static void addToWhereClause(FnSymbol*  fn,
 *                                                                             *
 ************************************** | *************************************/
 
-static bool isConstructor(FnSymbol* fn) {
+/*static bool isConstructor(FnSymbol* fn) {
   bool retval = false;
 
   if (fn->numFormals()       >= 2 &&
@@ -4492,7 +4492,7 @@ static bool isConstructor(FnSymbol* fn) {
   }
 
   return retval;
-}
+}*/
 
 static void updateInitMethod(FnSymbol* fn) {
   Type* thisType = fn->_this->type;
```

With that, this compiles and runs

```chpl
record barrier {
  proc barrier() {
    writeln("in barrier.barrier()");
  }
}

var x: barrier;
x.barrier();
```

(otherwise you get an error about proc barrier() being a deprecated constructor)
"""

Personally, I think we could/should remove the constructor warning since it's been so long.

**Comment by bradcray** [comment]
> Personally, I think we could/should remove the constructor error since it's been so long.

I definitely agree with this and would say "should" of those two options.
