### ISSUE TITLE
Let's rename the 'ChapelEnv' module - what should it be called?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#18879]
The 'ChapelEnv' module is a bit clunky in name and contents.  As part of the library stabilization
effort, we are discussing revamping both.  Some of the reasons that we're not excited about
the current name include:

* It implies it's talking about the environment for Chapel (the `CHPL_*` variables printed by
  `printchplenv`, say), but these settings can also be made through `.config` files, `chpl`
  command-line flags, or inferred.  I.e., they're typically not obtained through the environment.
  And other things that are in the environment are not available.
* We rarely type out 'Chapel' in full in code, and typically when we do for a module prefix, the
  implication is that it's an internal module (where Lydia correctly points out this module used
  to be internal; but that it didn't get renamed when it was promoted)
* It's auto-used, so the name hasn't really mattered in user code (notably, its name doesn't show
  up in the standard module docs sidebar or index page either)

This issue is focused on what the name of this new module should be, where leading contenders include:

* :+1: **Configuration-based proposals:** ChplConfig, ChplConfiguration
* :heart: **Compilation-based proposals:** ChplCompiler, ChplCompilation, Compiler, or Compilation
* :tada: **both at once:**: CompilerConfig, CompilerConfiguration
* :rocket: **Settings-based proposals:** ChplSettings
* :smile: **Reflection-based proposals:** ChplReflection, ChplQueries, CompilerReflection, Introspection
  * or, roll these capabilities into the existing Reflection module?
    * counterargument: Reflection seems to be more about code reasoning about itself than reflecting more generally on things that the compiler might happen to know;  "Did the user throw `--no-bounds-checks` seems out-of-place
    * counter-counterargument: "code reasoning about itself"-Isn't that "SelfReflection", not "Reflection"?
* :confused: **Something else?** (put your idea in the comments)

Add emoji to this OP with one or more of the families of names you prefer (and if you like a specific option or options from the family best, feel free to mention it in the comments below).

Options that were considered but not championed:

* ~Chapel[mumble]~  : again, we don't typically spell Chapel out in code, these capabilities seem more to be reasoning about the `chpl` compiler than the Chapel language, see previous note about this typically being an "I'm an internal module" prefix
* ~Settings / Configuration:~ felt too general-purpose and likely to be used by users to consider
*

**Comment by bradcray** [comment]
Based on the way things are trending so far, it looks like `ChplConfig` or `ChplConfiguration` are the leading proposals (note that Lydia voted for two, so I'm not counting her :rocket: vote above as opposition to those options).

Diving into that option a bit more, should we use `ChplConfig` :tada: or `ChplConfiguration` :heart: ?

I'll gently advocate for `ChplConfig` because I think it's sufficiently clear what `Config` stands for and we use that abbreviation in other places (like the `chplconfig` file).

I'll also note—in case anyone wonders or balks at it—that I think `Chpl` is a reasonable abbreviation rather than using `ChapelConfig` (say) because in essence it's the `chpl` compiler's configuration that we're reasoning about here.

**Comment by gbtitus** [comment]
We're also reasoning about the runtime's configuration but surely `chpl` works equally well there as an abbreviation, so your point stands.

**Comment by bradcray** [comment]
> We're also reasoning about the runtime's configuration

Spoken like a runtime developer!  In the context of the module, I think of it as "which of all these (hopefully pre-existing) runtime configurations should I, as the compiler, deign to target?"  :D  :D  :D

**Comment by gbtitus** [comment]
"One ring to rule them all, ..."     😉
