### ISSUE TITLE
Using require on a Chapel file only works if in the module with the main function

### ISSUE THREAD

**Issue by bmcdonald3** [chapel-lang/chapel#18883]
### Summary of Problem
Trying to `require` a module in a Chapel file besides the file with the `main()` function does not bring in the `require`d file. It seems that putting a `require` for a Chapel module in any included module should work as if it were in the `main` module in the project hierarchy, as it does with non-Chapel module `require` statements.

### Steps to Reproduce

`A.chpl` with main function
```
module A {
   proc main() {
      use B;
      test();
   }
}
```
`B.chpl` with require (in same directory as A)
```
module B {
  require '../C.chpl';
  public use C;
}
```
`C.chpl` with function to call (up one directory from modules A and B):
```
module C {
  proc test() {
    writeln("In module C");
  }
}
```
And this is the error that you see compiling with `chpl A.chpl`: `error: Cannot find module or enum 'C'`

Moving the `require '../C.chpl'` to module A and the code compiles and runs as expected.

**Comment by bmcdonald3** [comment]
Here is a comment from Brad:


> what I think is happening is: (1) we parse all modules that obviously need to be (e.g., those listed on the command-line) (in this case, A.chpl) (2) we look for and parse any that they require, through use or import or require (in this case B.chpl)
But then rather than iterating in that last step transitively to find that there are additional modules required, like C, we go on to subsequent stages of compilation. I.e., I think if we put the second bullet above into a logical "While we continue discovering new modules that we require..." loop, but don't have it in one today. It's definitely worth more investigation in any case, even if I don't have that quite wrong, as it looks like it should work.

**Comment by bradcray** [comment]
This feels as though it ought to be relatively straightforward to fix, though I didn't have time to give it a quick try this year to determine whether or not that's the case.  I think the loop that _ought_ to be causing `C.chpl` to be parsed is one of the ones like this:

```c
parser/parser.cpp:  while ((inputFileName = nthFilename(fileNum++))) {
```

and that the first step would be to see whether C.chpl is added to this list of filenames and that the while loop is not reaching it, or whether it's not being added for some reason.  I'd expect it to be added in build.cpp:

```c
bool processStringInRequireStmt(const char* str, bool parseTime,
```

specifically, in this conditional:

```c
    if (isChplSource(str)) {
      if (parseTime) {
        addSourceFile(str, NULL);
        return true;
```

**Comment by bmcdonald3** [comment]
I tried tracing this with `printf`s but wasn't able to make much progress. It seemed that the `C.chpl` module was being seen by the parser, but I wasn't able to find out why it wasn't being treated as such. 

I'd be interested in talking through this with others in hopes to learn more about the compiler and hopefully come up with the fix with some help in the New Year, though, I will almost surely have no memory of this then.

**Comment by bradcray** [comment]
I think I've got a fix for this, though I may time out before getting it onto a branch today.

**Comment by bradcray** [comment]
Draft PR here that still needs to be tested:  https://github.com/chapel-lang/chapel/pull/18912
