### ISSUE TITLE
different error message for missing configuration by changing CHPL_TARGET_COMPILER

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#18904]
`chpl version 1.25.1`

`chpl` takes a different error path when checking for built configurations for (at least) `CHPL_TARGET_COMPILER` vs. other environment variables.

----

I built Chapel successfully for `CHPL_LLVM={llvm, system}` (--> `CHPL_TARGET_COMPILER=llvm`). I then set `CHPL_TARGET_COMPILER=gnu`, a configuration that I had not built and knew would not work.

Usually, this error message would be reported (by e.g., changing `CHPL_TARGET_CPU`):
```terminal
chpl hello.chpl
error: The runtime has not been built for this configuration. Check $CHPL_HOME/util/printchplenv and try rebuilding with $CHPL_MAKE from $CHPL_HOME.
```

But instead, the error path resulted in a different, more confusing error message:
```terminal
chpl hello.chpl
error: Could not find module 'SysCTypes', which should be defined by '<CHPL_HOME>/modules/standard/gen/linux64-x86_64-gnu/SysCTypes.chpl'
```
(That directory does not exist because the configuration was not built.)

**Comment by mppf** [comment]
@BryantLam - thanks for reporting this issue. I have a PR in progress that adjusts some of the related code so I will see if I can fold a fix into that PR. It is #18880.
