### ISSUE TITLE
In NUMA locale model 'On' clause to parent locale does not move execution to parent locale

### ISSUE THREAD

**Issue by stonea** [chapel-lang/chapel#18948]
In the following example:

```chpl
var A = [1, 2, 3];

writeln("here = ", here);
writeln("A.locale = ", A.locale);
on here.getChild(1) {
  writeln("on here.getChild(1) {");
  writeln("  here = ", here);
  writeln("  A.locale = ", A.locale);
  on A {
    writeln("  on A {");
    writeln("    here = ", here);
    writeln("  }");
  }
  writeln("}");
}
```

I would expect the final `writeln` of `here` inside of the `on A` block to print out that we're on `LOCALE0` (that is on `A.locale`) but we end up still on the sublocale: `LOCALE0.ND1`.  Specifically, this is the output I get:

```
here = LOCALE0
A.locale = LOCALE0
on here.getChild(1) {
  here = LOCALE0.ND1
  A.locale = LOCALE0
  on A {
    here = LOCALE0.ND1
  }
}
```

Maybe there's some argument for disallowing "moving up" to the parent locale in the numa model but I'm not sure what that is, so this looks like a bug to me.

I created this issue while investigating this one: https://github.com/Cray/chapel-private/issues/2849
Which really spawned off as an investigation into trying to figure out how to fix this test failure: https://github.com/chapel-lang/chapel/issues/18856

We may want to come back to investigating the test failure if we solve this issue (that is the on clause to a parent locale not working issue).

**Comment by jabraham17** [comment]
The numa locale model is deprecated [and will be removed](https://github.com/chapel-lang/chapel/issues/25211). Closing
