### ISSUE TITLE
Should we have a `string.findRegex(s:string)`?

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#18960]
Currently we have a [`string.search(s:string)`](https://chapel-lang.org/docs/master/modules/standard/Regex.html#Regex.string.search) tertiary method documented in the Regex module. However, that method [doesn't work](https://github.com/Cray/chapel-private/issues/2884). We have to do something.

Even if it was working fine, we've had two opinions expressed about it:

1. We should rename it to make it clear that it uses regular expressions under the hood. `findRegex` is the best option I can think of here. (We'll change other parts of the interface to use the word "find" for similar functionality instead of "search")
2. We should remove this function.

---

I am for (2).

I don't see this method very appealing as the alternative would be just `myString.find(compile("foo*"))` and in [the initialier-based regex creation world](https://github.com/chapel-lang/chapel/issues/17187#issuecomment-1010218618), it'll be `myString.find(new regex("foo*"))`. You can also do `myString.find("foo*":regex)`. I don't think any of these are complicated enough to warrant this sugar.

Moreover, the current defunct interface has an `ignorecase` argument. Which brings up the question about flags that need to be used while creating the compiled regular expression. We either shouldn't use any of those flags, limiting functionality, or add all of them, complicating the interface.

**Comment by slnguyen** [comment]
Regarding module stabilization I think we should remove this function since it currently doesn't work. We can add it post module stabilization if necessary.
