### ISSUE TITLE
Math module - should we rename cproj?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#19011]
We inherit this name from C.  The "c" in the name stands for "complex" but this is confusing because we frequently use "c" for the C language in our naming scheme.

I propose renaming it to `riemannProj`, because it is a projection of the argument on a Riemann sphere.  However, there are probably other good options as well

**Comment by damianmoz** [comment]
No. Keep it the same.

The language is Chapel, one of its basic types, not just an identifier, is **complex**(w). That "c" stands for complex should be the default and should trump any name chosen to interface to some other language like **C**.

I think that name has been around in formal standards for over 20 years, and for longer than that in Working Groups and people experimenting with pre-releases.

**Comment by lydia-duncan** [comment]
It sounds like we will keep `cproj`

**Comment by lydia-duncan** [comment]
Based on Damian's comment on the `conjg` issue (#19010), we'll take a look at whether to rename this function in the sprint starting August 8th.  However, we might run out of time, in which case we may mark it unstable and revisit post 2.0 to determine a better name.

Here's the prep work for that ad-hoc subteam (sorry for the short turnaround).

### 1. What is the API being presented?

```chapel
  /* Returns the projection of `z` on a Riemann sphere. */
  inline proc cproj(x: complex(?w)): complex(w) { … }
```

### How is it intended to be used?

cproj is intended for use in complex math.  Specifically, it projects the value onto a model of the extended complex plane, which includes a point at infinity in addition to the normal complex plane.  The C++ documentation page states that it should be used prior to operations that might give spurious results for other infinities, because cproj will unify all infinities to one.

Wikipedia also says that the extended complex plane is useful for complex analysis because it allows for division by zero in some circumstances (https://en.wikipedia.org/wiki/Riemann_sphere)

### How is it being used in Arkouda and CHAMPS?

Not used in Arkouda or CHAMPS, so far as we can tell.

### 2. What's the history of the feature, if it already exists? 

Added in 2016 alongside a few other functions focused on complex numbers.  In the initial PR, was named proj but a reviewer asked to change the name to avoid potential conflicts with other names.  Since the symbol is included in all user programs by default, this is still a consideration. 

Had a bug fix in 2022 to the return type, enabling it to return complexes instead of reals.

### 3. What's the precedent in other languages, if they support it?

a. Python

I’m not seeing an equivalent to this function in Python.  I do see equivalents to other complex number functions, but nothing near them.

b. C/C++

C/C++ provides `cproj`, `cprojf` and `cprojl` for the various sizes of complex numbers it supports (https://en.cppreference.com/w/c/numeric/complex/cproj).  This is where we get the function name from.

c. Rust

I’m not seeing an equivalent in Rust.

d. Swift

I’m not seeing an equivalent in Swift

e. Julia

I’m not seeing an equivalent in Julia

f. Go 
I’m not seeing an equivalent in Go, though there does seem to be a project called Riemann (that doesn’t seem relevant otherwise)

### 4. Are there known Github issues with the feature?

- Impacted by the argument renaming PR that recently went in. 

### 5. Are there features it is related to? What impact would changing or adding this feature have on those other features?

- Related to complex numbers, carg, and conjg (soon to be renamed to conj).  There are other functions that are defined on complex numbers as well as other numbers, but abs has a distinct definition in the context of complex numbers.  Changing cproj's name might imply carg also should change, but likely wouldn’t impact any of these other functions. 

### 6. How do you propose to solve the problem? 

A. Leave as is
- Pros:
    - Less implementation effort (though not much to begin with)
    - Less effort for users (though not much to begin with)
    - Easier to search for, for users coming from C/C++ looking for it.
- Cons:
    - Not as descriptive as it could be
    - Don’t tend to include types in the naming of functions otherwise, so “c” standing for “complex” is a departure from that
    - Doesn’t follow our standard module style guide

B. rename to cProj
- Pros:
    - Follows standard module style guide on capitalization
    - More recognizable for users coming from C/C++
- Cons:
    - Not as descriptive as it could be
    - Don’t tend to include types in the naming of functions otherwise, so “c” standing for “complex” is a departure from that

C. rename to riemannProj
- Pros:
    - Follows standard module style guide on capitalization
    - More descriptive
    - No inclusion of types in the function name
- Cons:
    - Not the name used by C so not as easy to search for (though we can fix that by referencing the C name in the docs)
    - Longer

D. rename to proj
- Pros:
  - Short
  - Doesn't have to worry about capitalization
  - Relatively close to the C name, though dropping the first letter is probably not what users will do first when trying to search for the Chapel equivalent.
  - Doesn't include the type in the function name
- Cons:
  - Because this function is included in all user programs by default, could conflict with user names.  There are other projections that a user could try to represent themselves, or they could name a variable instance representing a project.  Some indication of the projection being represented would help avoid such conflicts.

E. Rename to projection
- Pros:
  - Less likely to conflict with user symbols due to its length
  - Includes the majority of the C name, so a search could plausibly still bring it up (though again, dropping the first letter is probably not what the users will do first when trying to search for the Chapel equivalent)
  - Doesn't include the type in the function name
- Cons:
  - When embedded in equations, would make the equations a lot less readable due to its length
  - Vague about *what* projection is used (though the documentation will help with that)

F. Some other name?

G. Mark it unstable without renaming it, revisit post 2.0
- Pros:
  - Gives more time for coming up with a better name
- Cons:
  - Including an unstable symbol in all user programs by default is not great (but at least the current name is less likely to conflict with anything the user has defined).
  - Might make the 2.0 story for complex numbers feel less complete (though the fact that it was only present in C/C++ amongst the languages I surveyed means this argument might not hold much weight).

I think we should rename it to riemannProj.

**Comment by lydia-duncan** [comment]
In our discussion today, we considered an additional name, `riemProj`, and decided that was the name we preferred.

Discussion notes:
- Jade asked if there was meaning for the function on argument types other than complex.
  - We think the answer is yes, but suspect that they are handled by coercing such arguments to a complex with `0.0i`.
