### ISSUE TITLE
Math module - unify truncation or lack thereof for `isfinite` and `isinf`

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#19017]
It's inconsistent for one not to truncate and the other to truncate when they relate to the same concept and are roughly similar in length.  This issue proposes renaming them.

We should also camelCase them while here.

Vote:
🎉 - `isFin` and `isInf`
🚀 - `isFinite` and `isInfinite`

I don't expect other suggestions but am certainly willing to consider them.

**Comment by damianmoz** [comment]
Are you really trying to re-write history?

These names have been around for 35+ years.

I prefer `isInf()` and `isFinite()`. Lots of code uses the symbol `inf` or `Inf` to be a correctly typed value INFINITY (which in theory should be the smallest floating point type supported by the compiler).

I often see isFin meaning Is Finished.

**Comment by lydia-duncan** [comment]
Prep for an upcoming ad-hoc sub-team discussion on this topic:

### 1. What is the API being presented?

```chapel
/* Returns `true` if the argument `x` is a representation of a finite value;
     `false` otherwise. */
  inline proc isfinite(x: real(64)): bool
  /* Returns `true` if the argument `x` is a representation of a finite value;
     `false` otherwise. */
  inline proc isfinite(x: real(32)): bool

/* Returns `true` if the argument `x` is a representation of *infinity*;
     `false` otherwise. */
  inline proc isinf(x: real(64)): bool
/* Returns `true` if the argument `x` is a representation of *infinity*;
     `false` otherwise. */
  inline proc isinf(x: real(32)): bool
```

### How is it intended to be used?

To check if INFINITY has or has not been passed to it.  Pretty straight-forward

### How is it being used in Arkouda and CHAMPS?

In Arkouda:

- isfinite is not used
- isinf is used twice in https://github.com/Bears-R-Us/arkouda/blob/eebf62436a5d37110a0975cc4db8481207e52484/src/BinOp.chpl#L22 to check whether INFINITY is used in the numerator or denominator when performing floor division

In CHAMPS:
- isfinite and isinf are not used

### 2. What's the history of the feature, if it already exists? 

These functions were added to the Math module in 2011.  They were originally extern functions, and when extern functions started generating prototypes, needed `pragma “no prototype”` to avoid errors due to the C support using macros.

Their implementation was adjusted in 2012 to avoid using `pragma “no prototype”` and support them naturally in Chapel, even though we are relying on macros in C under the covers.  This transformed them into inline functions that wrap runtime calls.

Documentation for these functions was added in 2015.

There was an attempt to unify the overloads of each into a single function, but this was thwarted by promotion.

Were moved to AutoMath.chpl when the split happened so that they could continue to be included in user programs by default.

### 3. What's the precedent in other languages, if they support it?
a. Python

Python provides `isfinite` (https://docs.python.org/3/library/math.html#math.isfinite) and `isinf` (https://docs.python.org/3/library/math.html#math.isinf).

b. C/C++

C/C++ provides `isfinite` (https://en.cppreference.com/w/c/numeric/math/isfinite) and `isinf` (https://en.cppreference.com/w/c/numeric/math/isinf) and is the source of our names for these functions).

c. Rust

Rust provides `is_finite` (https://doc.rust-lang.org/std/primitive.f64.html#method.is_finite), and `is_infinite` (https://doc.rust-lang.org/std/primitive.f64.html#method.is_infinite)

d. Swift

Swift defines these as properties of doubles, `isFinite` (https://developer.apple.com/documentation/swift/double/isfinite) and `isInfinite` (https://developer.apple.com/documentation/swift/double/isinfinite)

e. Julia

Julia provides `isfinite` (https://docs.julialang.org/en/v1/base/numbers/#Base.isfinite), and `isinf` (https://docs.julialang.org/en/v1/base/numbers/#Base.isinf)

f. Go

Go only provides `IsInf` (https://pkg.go.dev/math#IsInf), so doesn’t run into the truncation inconsistency. 

### 4. Are there known Github issues with the feature? 

- https://github.com/chapel-lang/chapel/issues/19005 talks about argument names with all the Math functions (but these functions already use the name we decided to go with for arguments)

### 5. Are there features it is related to? What impact would changing or adding this feature have on those other features? 

- Related to INFINITY, which will be talked about in the same meeting.  The naming for these functions and that paren-less function are not currently in sync, but it might be nice to have that happen.

### 6. How do you propose to solve the problem?  

A. Camelcase only (`isFinite` and `isInf`)
- Pros:
    - More consistent with the naming schemes of Python, C/C++, and Julia, so more familiar for users
- Cons:
    - Not a consistent naming scheme

B. Rename to `isFin` and `isInf`
- Pros:
    - Is a consistent naming scheme
    - Compatible with Go’s decision (but mostly because Go doesn’t provide an equivalent for `isfinite`)
- Cons:
    - `isFin` is maybe too short a name
    - could be confused with “isFinished” (or a user could write a function with that name and have it conflict)
    - Not consistent with Python, C/C++, Rust, Swift, or Julia

C. Rename to `isFinite` and `isInfinite`
- Pros:
    - Is a consistent naming scheme
    - Consistent with Rust and Swift’s names
- Cons:
    - Not consistent with Python, C/C++, Julia, or Go
    - longer names

I’d do C, personally.

**Comment by damianmoz** [comment]
Impressive. I am curious if you get feedback via Github from others.

That said, **INFINITY** and **NAN** are related to **isinf**() and **isnan**(). See my soon-to-be-uploaded comments in #19016

**Comment by lydia-duncan** [comment]
In our discussion today, we decided to rename these to `isInf` and `isFinite`.

This was decided by looking at the combinations of these names and the name options for INFINITY.  The decision for that has already been posted to #19016 

Key points from the discussion:
- What is the difference between what `isfinite` and `isinf` checks?
  -  `isfinite` also checks against `nan`.
- Could we remove `isfinite`?
  - This seemed unlikely to be tractable, especially given that it has slightly different behavior in what it checks
- What about renaming `isfinite` to something like `isNum`?
  - That'd be confusing with the `numeric` generic type and associated check
  - There are situations where might want to consider infinity a number
- We definitely didn't like the shortened form of `isfinite`
- The unified longer forms were a close second option

We are willing to meet again if new counterpoints are presented.
