### ISSUE TITLE
Math module - adjustments to isclose

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#19025]
`isclose` should be camelCased.  Also, we should document that the argument `rtol` is for relative tolerance and the argument `atol` is for absolute tolerance.

**Comment by lydia-duncan** [comment]
Michael pointed out in the module review meeting that `isclose` makes him think of `isclosed`, which is not the same thing.  He suggested `withinEpisilon` as an alternative name but felt that with more discussion we could potentially come up with a better name

**Comment by lydia-duncan** [comment]
We discussed this issue in a small subgroup today.

We considered having the two tolerances be handled by separate functions.  It seemed odd to us that if both an absolute tolerance and a relative tolerance were provided, only one had to be fulfilled for the function to return true.

We went back and forth on if we thought absolute tolerance or relative tolerance would be more commonly used.  It seemed like it was useful for some situations and not others (where comparing small values benefits more from relative tolerance)

I have some action items as a result of the discussion:
- how frequently is `isclose` used with anything other than reals today?  Should the types be concrete?
- Is there a particular meaning for the value of rtol today?  Rust looks like it uses a similar check (though this is with real(32), does that make a difference?)

`areClose` was suggested as an alternative name, since it is not a method on the first argument, so it makes sense to describe it by talking about the two things being compared rather than from the perspective of both.

Voting:
- keep `isclose` same as today (have both an `atol` and `rtol` argument and if any one of the checks are true then return true): 0/5 were in favor of this
- Make absolute tolerance take precedence (and error if both `atol` and `rtol` are overridden): 0/5 were in favor of this
- Make relative tolerance take precedence (and error if both `atol` and `rtol` are overridden): originally 0/5, but ended with 1/5
- Make relative tolerance and absolute tolerance checked by two separate functions: originally 5/5, but ended with 4/5

Suggestions for names (in addition to `isClose` and `withinEpisilon`):
- `realEqAbs` and `realEqRel`
- `realEq` and `withinDelta`
- `areAbsolutelyClose` and `areRelativelyClose`
- `areClose` for both but have a single tolerance argument and use a boolean to switch between what is compared
  - (or enum, in case we want to include a third tolerance style in the future, see https://jtempest.github.io/float_eq-rs/book/background/float_comparison_algorithms.html#units-in-the-last-place-ulps-comparison)
  - (e.g. `areClose(x, y, tolerance, toleranceStyle=absolute)` or something like that)

The action items will drive this discussion forward (and I think there still might be a better name out there)

**Comment by e-kayrakli** [comment]
Just noting the design discussion under https://github.com/chapel-lang/chapel/issues/13898 (which shouldn't impact much, but just for context) and pinging @npadmana as a user involved in the initial design.

**Comment by bradcray** [comment]
> Michael pointed out in the module review meeting that isclose makes him think of isclosed, which is not the same thing.

This happened to me a couple of times this week as well, perhaps because we just discussed that method recently in the IO deep-dive.  I like the notion of picking a different name on that basis (but don't feel insistent about it).

As is often the case, I wonder what other modern languages do about these queries as well (and I like Engin's idea of getting Nikhil's input).

**Comment by npadmana** [comment]
I'm just catching up on this, but I would be fine with the rename to `isApprox`, leaving the functionality the same. If we keep the `rtol` and `atol` parameters, then I don't think you would need separate versions.

**Comment by bradcray** [comment]
A few other naming ideas if we were to move away from `isClose()`:
* `withinEpsilon()`: says fairly directly what it means and will show up in searches on epsilon (though of the documentation for any of these routines mentions epsilon, they should as well)
* `approxEquals()`: the other popular choice of name at https://rosettacode.org/wiki/Approximate_equality other than `isClose()` (of course, this could just be a matter of some entries following the lead of others, or the same person writing the codes.

**Comment by lydia-duncan** [comment]
Other ideas tossed around when discussing whether to include this symbol by default (amongst Brad, Jade and myself):
- Could make it a method on the first argument, though if we did so we would probably want to change the name to `isCloseTo`
- We could add a new operator to accomplish this (though that would be a post-2.0 addition and wouldn't necessarily mean this version would need to go away)

Regardless, we wanted to note that the function should probably limit itself to only take `real`, `imag` and `complex` arguments, and enable more only if requested in the future.

**Comment by lydia-duncan** [comment]
Ad-hoc subteam discussion prep:

### 1. What is the API being presented?

```
proc isclose(x, y, rtol = 1e-5, atol = 0.0): bool
```

It is used to compare two numbers and determine if they are close enough together.  The arguments are currently generic, but probably should be limited to `real`, `imag` and `complex`.

### How is it being used in Arkouda and CHAMPS?

It is not used in Arkouda (though its numpy counterpart is used in several places)

It is not used in CHAMPS

### 2. What's the history of the feature, if it already exists?

We developed this feature based on Python's isclose in 2019 ([discussion here](https://github.com/chapel-lang/chapel/issues/13898)).  We considered numpy's version, Python's math version, and Julia's isapprox, as well as the potential for an operator.  We ended up following the argument names of numpy/isapprox but following the implementation of Python's math.isclose, with a tweak to the computation provided by Nikhil.

We did talk about camelCasing it at the time but shied away from it because other functions in the module weren't camelCased :(

### 3. What's the precedent in other languages, if they support it?

a. Python

As mentioned above, Python has two versions: the one in the [math library](https://docs.python.org/3/library/math.html#math.isclose) and the [numpy one](https://numpy.org/doc/stable/reference/generated/numpy.isclose.html).  The numpy version takes array arguments and provides an additional `equal_nan` argument.  The PEP discussion of [math.isclose](https://peps.python.org/pep-0485/) is quite detailed and interesting.

b. C/C++

Boost has a few versions along these lines: https://www.boost.org/doc/libs/1_35_0/libs/test/doc/components/test_tools/floating_point_comparison.html

c. Rust

Rust provides an [is_close crate](https://docs.rs/is_close/latest/is_close/) based strongly on Python's isclose.

d. Swift

Swift has a few overloads of [isApproximatelyEqual](https://github.com/apple/swift-numerics/blob/Quaternions/Sources/RealModule/ApproximateEquality.swift), some of which involve absolute tolerance, some of which involve relative tolerance and a norm.

e. Julia

As mentioned above, Julia uses [isapprox](https://docs.julialang.org/en/v1/base/math/index.html#Base.isapprox), but also provides the ≈ and ≉ operators, which are the same as calling `isapprox` or `!isapprox` using the default tolerance values, where `atol` defaults to 0 and `rtol`'s default depends on the type of the arguments.

f. Go

I'm not finding an equivalent in Go

### 4. Are there known Github issues with the feature?

- https://github.com/chapel-lang/chapel/issues/19005 (talking about argument names in the Math and AutoMath modules in general)

### 5. Are there features it is related to?

Obviously, strongly related to real/imag/complex and the equality operators.

### 6. How do you propose to solve the problem?

We should at least camelCase this function.

Other renaming options:
- withinEpsilon
- isApprox
- isApproximatelyEqual
- approxEquals
- isCloseTo (and make it a method on the first argument)

We'll talk about the argument names in #19005, which will be discussed in the same meeting.

We do want to limit the types accepted for x and y to `real`, `imag` and `complex`.

**Comment by lydia-duncan** [comment]
Summary: In our meeting today, we decided to rename `isclose` to `isClose` but not change the name otherwise.  We also decided to limit the types accepted for `x` and `y` to `real`, `imag` and `complex`.
