### ISSUE TITLE
Math module - rename lgamma and tgamma

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#19022]
I don't find these names particularly clear - it is difficult to guess what `l` stands for without reading the documentation, and even with the (C) documentation, I'm not sure what the `t` is for.  This issue proposes renaming `lgamma` to `logAbsGamma` to more accurately represent its functionality (while maintaining the C name in the documentation so that users looking for that name can find it), and renaming `tgamma` to `gamma` since it seems to just be the gamma function? (ditto comment about documenting old name)

Note that #18998 also impacts tgamma

**Comment by damianmoz** [comment]
The reason that you might be finding the names confusing is that the gamma function and its logarithm (useful when the function itself grows too large) has has a checked history in its naming.

Are you trying to resolve 45+ years of history over this weekend?

**Comment by lydia-duncan** [comment]
Wikipedia states (without sources) that the log gamma function is frequently named `lgamma` or `lngamma` in programming environments.

According to a [Linux man page](https://man7.org/linux/man-pages/man3/gamma.3.html), the "t" stands for "true".  The page references historical differences between various systems where some would refer to lgamma as gamma and attempts to move away from that so that gamma could again be used - however, it states that it took too long and so "tgamma" became the standard.

**Comment by lydia-duncan** [comment]
It sounds like if C could start from scratch, it probably would use "gamma" instead of "tgamma".  I think one could argue that, being a language developed long after systems were more unified in this way, it would be reasonable to start from this position.  However, there is again the familiarity argument.

So, looking at other languages:
- Both Python's scipy library and math library uses `gamma`.  Math uses `lgamma` while scipy uses `gammaln`.
- There is a Rust crate scilib that [provides a `gamma` function](https://docs.rs/scilib/0.4.3/scilib/math/basic/fn.gamma.html), which seems to be consistent with `tgamma` rather than `lgamma`.  It does not seem to yet provide `lgamma` and I'm uncertain how well used it is, but it seems quite extensive.
- Swift has a [numerics library](https://www.swift.org/blog/numerics/) implemented by one of the language's developers that provides `gamma`, `logGamma`, and `signGamma`

That seems like a strong precedent for using `gamma` over `tgamma` in modern languages, and some precedent for using `lgamma`, though there is wiggle-room there.

**Comment by lydia-duncan** [comment]
Prep for an upcoming ad-hoc subteam (scheduled for the two week sprint starting August 8th)

### 1. What is the API being presented?

```chapel
  /* Returns the natural logarithm of the absolute value
     of the gamma function of the argument `x`.
  */
  inline proc lgamma(x: real(64)): real(64) { … }
  inline proc lgamma(x : real(32)): real(32) { … }

  /* Returns the absolute value of the gamma function of the argument `x`. */
  inline proc tgamma(x: real(64)): real(64) { … }
  inline proc tgamma(x : real(32)): real(32) { … }
```

The t stands for “true”, due to historical differences between systems where some would refer to lgamma as gamma and attempts to move away from that so that gamma could again be used (source: https://man7.org/linux/man-pages/man3/gamma.3.html).

### How is it intended to be used?

According to Wikipedia (https://en.wikipedia.org/wiki/Gamma_function), the gamma function is “a commonly used extension of the factorial function to complex numbers. […]  It is a component in various probability-distribution functions, and as such it is applicable in the fields of probability and statistics, as well as combinatorics.”

“Because the gamma and factorial functions grow so rapidly for moderately large arguments, many computing environments include a function that returns the natural logarithm of the gamma function (often given the name lgamma or lngamma in programming environments […]); this grows much more slowly, and for combinatorial calculations allows adding and subtracting logs instead of multiplying and dividing very large values.”

###  How is it being used in Arkouda and CHAMPS?

Neither tgamma nor lgamma are used in Arkouda or CHAMPS.

### 2. What's the history of the feature, if it already exists? 
The 64 bit versions of lgamma and tgamma were originally added in 2006 along with several other math functions.  tgamma was removed shortly thereafter and restored in 2007 due to not being supported on the Sun platform (when it was re-added, it was prevented from running there).

The 64 bit versions predate using “real” as the name for the type, it was originally “float”.

The 32 bit versions were added in 2007, along with 32 bit versions of other functions in that module.

The 64-bit functions were originally pure extern wrappers around the C functions and predated the extern keyword.  The 32-bit versions were always wrappers around their C counterpart so that they could share the same name, and predated the inline keyword.  Both versions predate the proc keyword.

Documentation was added to these functions in 2015.

There was an attempt in 2015 to unify the two overloads of these functions into a single overload, but it was thwarted by promotion at the time.

They were recently updated to no longer be included in user programs by default.

### 3. What's the precedent in other languages, if they support it?
a. Python

Python provides `gamma` (https://docs.python.org/3/library/math.html#math.gamma) and `lgamma` (https://docs.python.org/3/library/math.html#math.lgamma).

Note that Python also uses `log` as its name for the natural logarithm function, so `l` instead of `ln` is in keeping with that.

The scipy library for Python also provides `gamma` (https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.gamma.html), but it provides `gammaln` (https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.gammaln.html) instead of `lgamma` (and says it is the same function as the Python Math version).  Scipy also provides `loggamma` (https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.loggamma.html#scipy.special.loggamma), which is specifically for complex numbers.  Scipy also does not provide its own log functions (aside from `log1p`), so it is interesting that they chose to deviate from Python’s math library and use `ln` instead of `log`, but only some of the time.

b. C/C++

C/C++ provide three versions of `tgamma` (`tgamma`, `tgammaf`, and `tgammal` for the various argument sizes used, https://en.cppreference.com/w/c/numeric/math/tgamma).  It calls out the existence of a non-standard function named gamma in various implementations, but that its definition is inconsistent (see note about the “t” in `tgamma` in the first section of this comment).

It also provides three versions of `lgamma` (`lgamma`, `lgammaf`, and `lgammal` for the various argument sizes used, https://en.cppreference.com/w/c/numeric/math/lgamma).  There is a note in this documentation that says the POSIX version is not thread-safe (!!) - do we test this?  Does this mean that our `pragma “fn synchronization free”` pragma is incorrectly applied?  This is something for me to investigate.

Note that C/C++ uses `log` as their name for the natural logarithm function, so `l` instead of `ln` is in keeping with that.

c. Rust

There is a Rust crate scilib that [provides a gamma function](https://docs.rs/scilib/0.4.3/scilib/math/basic/fn.gamma.html), which seems to be consistent with `tgamma` rather than `lgamma`. It does not seem to yet provide `lgamma` and I'm uncertain how well used it is, but it seems quite extensive.

d. Swift

Swift has a [numerics library](https://www.swift.org/blog/numerics/) implemented by one of the language's developers that provides `gamma` and `logGamma`.

Note that since Swift uses `log` as the natural logarithm, `logGamma` is in keeping with that naming scheme.

e. Julia

Julia does not seem to define these functions, so far as I could tell

f. Go

Go defines `Lgamma` (https://pkg.go.dev/math#Lgamma), which returns the sign of gamma as well as the natural logarithm (instead of the absolute value like the other languages do).  It also defines `Gamma` (https://pkg.go.dev/math#Gamma) 

### 4. Are there known Github issues with the feature? 

- https://github.com/chapel-lang/chapel/issues/18998 calls out that `tgamma` says it returns the absolute value, but that’s not in keeping with C’s documentation of the function and it doesn’t look like we do anything to change that ourselves.
- It’s mentioned in https://github.com/chapel-lang/chapel/issues/19005 (unifying the Math argument names), but will not need to changes as a result of that decision.
- Not yet supported on AMD GPUs https://github.com/chapel-lang/chapel/issues/22587

### 5. Are there features it is related to? What impact would changing or adding this feature have on those other features? 

Because the gamma function is an extension of the factorial function, it is related to:
- mpz_fac_ui, mpz_2fac_ui, and mpz_mfac_uiui in the GMP module
- The standalone `fac` function in the BigInteger module (which implements factorial)

But I don’t anticipate changing the gamma functions to impact these features.

lgamma is related to the natural logarithm, so related to the constants `ln2` and `ln10`, and the function `ln`, as well as the intended log overload with a default base of `e`.  (See discussion in https://github.com/chapel-lang/chapel/issues/18995 for the naming decision there).  While our decision here should not change the decision with those symbols, if we rename `lgamma` it probably should be consistent with those symbols in some way.

### 6. How do you propose to solve the problem? 

For tgamma:

A. camel case to tGamma
- Pros:
    - follows our camel case strategy
    - Consistent with C/C++
- Cons:
    - Not consistent with Python, Rust, Swift, or Go
    - Using naming scheme that was developed as a result of C/C++ churn - we don’t have to be beholden to their history when it sounds like the preference would have been to use `gamma` all along

B. Rename to just “gamma”
- Pros:
    - Consistent with Python, Rust, Swift and Go
    - Doesn’t use weird name that came about as a result of C/C++ churn and inconsistency
- Cons:
    - Not consistent with C/C++


For lgamma:

A. camel case to lGamma
- Pros:
    - Consistent with Python, C/C++, and Go
    - Follows our camelCase strategy
- Cons:
    - Not consistent with Swift
    - Relies on `l` -> `log` connection when `log` is the natural logarithm.
        - However, one could argue that it’s not confusing, because new users will probably look up what the l stands for rather than guessing it means “log base 10” and anyone looking for this function specifically because they want to use it will already know that it uses the natural logarithm.
    - Personal opinion: I think following lower case L with a capital letter makes it more confusing than following it with a lower case letter.  Mentally, I just assuming it’s lower case L in the latter situation, while the former makes me jump to capital i.

B. leave as is
- Pros:
    - Less implementation work (though there shouldn’t be much)
    - Less work for users (though again, it shouldn’t be much)
    - Quicker search for users coming from Python and C/C++
    - Personal opinion: I think following lower case L with a capital letter makes it more confusing than following it with a lower case letter.  Mentally, I just assuming it’s lower case L in the latter situation, while the former makes me jump to capital i.
- Cons:
    - Doesn’t follow our camelCase strategy
    - Not consistent with Swift
    - Relies on `l` -> `log` connection when `log` is the natural logarithm.
        - However, one could argue that it’s not confusing, because new users will probably look up what the l stands for rather than guessing it means “log base 10” and anyone looking for this function specifically because they want to use it will already know that it uses the natural logarithm.

C. Rename to lnGamma
- Pros:
    - A common name according to Wikipedia (though none of the languages I looked at used it)
    - In keeping with our camelCase strategy
    - In keeping with our using “ln” for the natural logarithm (though we will still provide log that defaults to a base of `e`)
    - (More) obvious what the function will do without reading the documentation for it
- Cons:
    - Not consistent with Python, C/C++, Swift, or Go

D. Rename to logGamma
- Pros:
    - Consistent with Swift
    - (More) obvious what the function will do without reading the documentation for it
- Cons:
    - Not consistent with Python, C/C++, or Go
    - Relies on `log` being interpreted as the natural logarithm
        - We’re trying to move away from that, though we will still provide `log` with a default base of `e`.
        - Naive new programmers may assume it refers to `log` with a base of 10, not knowing that `log` is typically the natural logarithm in programming

E. Rename to gammaLn
- Pros:
    - Consistent with name in Python’s scipy library
    - Same meaning as `lngamma` or `lgamma`, but ensures that it will be alphabetically sorted near `gamma`.
    - Consistent with our camelCase strategy
    - (More) obvious what the function will do without reading the documentation
    - In keeping with our using “ln” for the natural logarithm (though we still provide log that defaults to a base of `e`)
- Cons:
    - Might imply “gamma of log” instead of the other way around
        - I don’t actually know if that order matters for this particular operation
    - Not consistent with Python’s Math library, C/C++, Swift, or Go

I think we should:
- rename tgamma to gamma
- rename lgamma to lnGamma
    - I’m supportive of gammaLn, and could live with the rest.  lGamma is probably my least favorite.

**Comment by damianmoz** [comment]
Sorry, I am not doing justice to your thorough document. I personally think that the error function, gamma and Bessel functions belong in a module `SpecialMath` and their names need a lot more thought before being locked in stone with Chapel 2.0. But ignore my rambling on that topic.

Allow me to fill in a few tiny gaps in your discussion:

Given the result of some fictitious infinite precision **tgamma** function
```chapel
tg = tgammaInfinitePrecision(x)
```
then writing
```chapel
const log_abs_tg = log(abs(tg))
const sgn_tg = sgn(tg);
```
you can assert very loosely (because there is lots of roundoff)  
```chapel
tg = sgn_tg * exp(log_abs_tg)
```
Now, the C routine **lgamma**() returns _log_abs_tg_ but it also scribbles over a global variable **signgam** to give you the sign. Hence it is thread unsafe. Naughty.

There has been a threadsafe C library routine **lgamma_r**() around for a while, which if used in some C code might look like
```Chapel
int sgn_lg;
double log_abs_tg = lgamma_r(x, &sgn_tg);
```
Feel free to call the Chapel routine **lgamma**() or whatever in Chapel but please call the low level thread safe version of the C routine and return both bits of the breakdown, i.e. do not throw away potentially valuable information.

My 2c. Hopefully my comments are not too incomplete.

**Comment by lydia-duncan** [comment]
Oh, I'd thought we were going to consider the names for the error functions and Bessel functions stable for 2.0.  I'm definitely okay with marking them unstable, and discussing them and their location more, though.  Just probably on a separate issue.

Your pointer on the alternative to lgamma and the additional information is really helpful, thanks!  We'll have to check its general availability before relying on it, but I suspect it'll at least be involved in any adjustments we make

**Comment by damianmoz** [comment]
Sorry, I was not suggesting you mark those _special function_ names as unstable and make more work for yourself. I was more putting them into context. I was also giving you the hint of an _out clause_ if you wanted to kick the can down the road to save yourself work. I will note that each of those functions employs a different abbreviation technique to its mates which I have always found weird. I have no idea why those function are called _special functions_ but Wayne Fullerton used the name in his SFUN
library dating from the 1970s.

Before I suggest more work for anybody, I might consult the memory of those who were around when those three special functions, and only those three (because there are heaps more), found their way into the C mathematical library. They are certainly not part of the IEEE 754 standard's list of recommended functions.

**Comment by lydia-duncan** [comment]
In our discussion today, we decided to:
- rename `tgamma` to `gamma`
- rename `lgamma` to `lnGamma`

Some discussion notes:
- Jade: likes lgamma more than lGamma, doesn't like the capital G.  Leans towards lnGamma
- Jeremiah: doesn't like log gamma.  Kinda against gammaLn, not convinced the operation is commutative
