### ISSUE TITLE
Math module - rename ldexp

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#19021]
I have no idea what this function does based on its name.  It is inherited from C, so should at least mention that name in its documentation, but I believe we should find a better name.

The documentation says:
> Multiply by an integer power of 2. Returns x * 2**n.

I'm at a loss for how to rename this function, though.  Michael says this is useful for recombining a mantissa and an exponent and so is useful for low-level float manipulation, maybe that can help with finding a new name?  Very open to suggestions.

**Comment by damianmoz** [comment]
I gave up on this ages ago and now I use a method on a **real**(w). Given a floating point typed `x` and an integral type `n`, then
```chapel
x.scale(n)
```
returns `x * 2**n` where the computations of `2 **n` is done optimally and avoids spurious underflow and overflow.

I will post the module that does this soon(ish) when I find the time to finish the QA on the module.

**Comment by lydia-duncan** [comment]
Would that potential suggest deprecating `ldexp` in favor of it?  Or do you think it's useful to still provide it for other cases?

**Comment by mppf** [comment]
Something along the lines of a `scale` method sounds better to me than naming it `ldexp`.

**Comment by lydia-duncan** [comment]
Prep notes for an upcoming adhoc subteam discussion (scheduled for the 2-week sprint starting August 8th)

### 1. What is the API being presented?

```chapel
  /* Multiply by an integer power of 2.
     Returns x * 2**n.
     */
  inline proc ldexp(x:real(64), n:int(32)):real(64) { … }
  inline proc ldexp(x:real(32), n:int(32)):real(32) { … }
```

This function name is not clear, but if we rename it, we should mention the C name in the documentation so people that look for it can find it.

The C documentation of the function with the same name says that it is short for “load exponent”.  It also says that `frexp` is its counterpart, but we don’t provide that.

### How is it intended to be used?

When I originally discussed this method, Michael said it is useful for recombining a mantissa and an exponent and so is useful for low-level float manipulation.

### How is it being used in Arkouda and CHAMPS?

Not used in Arkouda or CHAMPS

### 2. What's the history of the feature, if it already exists? 
It was added in 2015 to support the PCG Random number generator in the Random module.

We recently stopped including it in all programs by default.

### 3. What's the precedent in other languages, if they support it?
a. Python

Python provides it with the same name (https://docs.python.org/3/library/math.html#math.ldexp), calling it out as the inverse of `frexp`

b. C/C++

C/C++ provides three versions for various sizes (ldexp, ldexpf, ldexpl, https://en.cppreference.com/w/c/numeric/math/ldexp).  This is likely to be where we got the function name from.

It also provides `frexp`.

c. Rust

Rust does not seem to provide this function or `frexp`.

d. Swift

Swift did provide it as `ldexp`, but it’s deprecated now (https://developer.apple.com/documentation/coregraphics/1454868-ldexp/).  It does not seem to provide `frexp`, either.

e. Julia

Julia provides it as `ldexp` (https://docs.julialang.org/en/v1/base/math/#Base.Math.ldexp).  It’s also linked to from the `<<` definition, and Julia provides `frexp` (https://docs.julialang.org/en/v1/base/math/#Base.Math.frexp), though `frexp` does not seem to be linked to from anywhere in the Math page (which makes sense, because unlike `ldexp`, it returns a pair of numbers).

f. Go

Go provides it as `Ldexp` (https://pkg.go.dev/math#Ldexp).  Go also provides `Frexp` (https://pkg.go.dev/math#Frexp). 

### 4. Are there known Github issues with the feature?

- Will have one of its argument names updated as part of https://github.com/chapel-lang/chapel/issues/19005
- Not yet supported by the GPU effort: https://github.com/chapel-lang/chapel/issues/22587  

### 5. Are there features it is related to? What impact would changing or adding this feature have on those other features?

We do have `<<` operator definitions, but only for ints, uints and bigints (and tuples and syncs).  Changing ldexp would not impact those operators.

Similarly, we have `mul_2exp` defined on bigints, which results in the same answer but obviously will handle it in a slightly different way under the covers due to type differences.  We have `shiftLeft` defined on bigints and intend to make it public for 2.0.  The naming interaction is interesting to consider.  (will update with decisions from that discussion)

### 6. How do you propose to solve the problem? 
A. Camel case it but otherwise leave it as is (to `ldExp`, because `ld` is short for “load”)
- Pros:
    - More easily found when looking for the equivalent to the C function
- Cons:
    - The name does not make it clear what the function does

B. Rename it to `scale`
- Pros:
    - Somewhat clearer what it’s trying to do
- Cons:
    - Not necessarily clear how (maybe incorrectly implies power of 10 to a casual user?)
    - Name Damian’s already using for his equivalent, might result in conflicts and annoyance rather than helping

C. Rename it to `loadExponent`
- Pros:
    - Actually descriptive if you don’t already know what it does, or at least less obfuscated.
- Cons:
    - longer

D. Rename it to `shiftLeft`
- Pros:
    - Actually descriptive
    - Matches proposed name of what seems to be a similar operation in the BigInteger module
- Cons:
    - Implies we should add a `shiftRight`, which is not the `frexp` equivalent.
    - Potentially implies bit manipulations, when that wouldn’t be the case for reals due to how they are represented under the covers and how ldexp functions.

E. Mark it unstable until we can figure out a name we like better
- Pros:
    - Relatively easy to do
    - The function doesn’t seem to be heavily used
- Cons:
    - Are we any more likely to figure out a better name later?

Other ideas are welcome.

Of these options, I think we should rename it to `loadExponent`.  I’m not fond of `ldExp`, even though I do prefer it to `ldexp`.

**Comment by damianmoz** [comment]
What **ldexp** does is not a shift so it is a _jump too far_ to think of using >> or << operators.

One can say that **ldexp**() scales a floating point number by an integral power of the _RADIX_. This is implicitly by multiplying by an integral power of the radix but if the absolute value of the second argument is large enough,  it will need more than a single multiplication. So, the language used (for better or worse) is that it _scale_s its argument. The internals minimize the number of multiplications needed to perform the computation and in most practical cases, will restrict the number of multiplications to a single multiplication.

In our now _on-ice_ replacement mathematical library project, we had a routine called _scale_ which could be thought of as
```chapel
inline proc scale(x : real(64), n : int(32)) do return ldexp(x, n);
inline proc scale(x : real(32), n : int(32)) do return ldexpf(x, n);
```
We wrote ours in pure Chapel and these days, it would use the _.transmute_() method of @bradcray seen in #21813.  There are arguments for and against having it **inline**. Ours was generic.

This could cause name clashes but that can be avoided by making it a method on a **real**(_w_) number. If you can live with the possible name clash, using **scale**() to rename **ldexp**() better reflects what it is doing. In some C libraries, the **ldexp**() function just calls **scalbn**().

You could also make  a version with _n_ as a **param** so that the compiler can warn the programmer that instead of
```chapel
scale(x, 463);
```
they should use the far simpler and more optimal expression `x * 0x1.0p+463`. One of the benefits of Chapel.

My 2c. The above is far too brief and does not match your thorough documentation standards but I have a meeting soon (Friday morning here) and I am trying to get it out before 6pm Washington-time for those who are working late. I can elaborate on this over my weekend but I need to go now. Customers!! Sorry.

We also had a **split**() routine which was an improved (and effectively a replacement for) **frexp**(). Again, pure Chapel. And generic.

**Comment by lydia-duncan** [comment]
> What **ldexp** does is not a shift so it is a _jump too far_ to think of using >> or << operators.

Sorry, I was not intending to imply that we would use anything other than `ldexp` under the covers to implement it.  I was more trying to point out that from a perspective that doesn't look at the implementation, what `<<` and `shiftLeft` return for the same arguments would be the same and thus that they should be considered related to the functionality, to help others understand the broader picture and maybe enable someone to come up with a better name as a result.  I was hoping that lines like:

> [...] but obviously will handle it in a slightly different way under the covers due to type differences.

and 

> Potentially implies bit manipulations, when that wouldn’t be the case for reals due to how they are represented under the covers and how ldexp functions.

would indicate that.  But it's good having the details you've added as part of the conversation regardless.

Anyways, on the other aspects of your comment, it sounds like you're not as worried about `scale` becoming a naming conflict?  Or is that something that may worry you more when the implementation happens?  My main concern about the naming conflict was whether it would cause problems for you.  But it's not a symbol that's included by default any more so there's definitely more ways to deal with that possibility than there were in the past.

The alternate name for an `frexp`-like counterpart is good to note as well.  I'll probably spin that off into an issue so we don't forget about it if we go looking to add `frexp` functionality in the future, especially if we do go with renaming to `scale` here.

**Comment by damianmoz** [comment]
I think there are a gazillion routines called **scale** in the world. But, the chance of any being so simple as to have just a **real**(w) and an **int**(32) as as arguments is pretty remote. But I could be very wrong. The more commonly used name for that functionality in the C library is **scalbn**

Hopefully I added some value to the conversation.

**Comment by lydia-duncan** [comment]
In our discussion today, we decided to rename it to `ldExp`

We additionally considered the names:
- loadExp (as a shorter version of the long form loadExponent)
- mul2Exp (to match the function name in BigInteger)

Discussion key points:
- Jade: naturally thinks of `ld` as "load" because of assembly, but would understand not everyone thinks of that
- Jeremiah: would use language precedence as tie breaker
- Jade: mul2Exp is more descriptive, but it's so different from other languages.
