### ISSUE TITLE
Should we change `proc this` into an operator?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#19037]
When we introduced `proc this()` as a means of permitting user-defined types to be indexable, we chose it because we didn't want to reserve a user identifier for this, `this` was already a reserved word, and it felt syntactically appropriate to use `this()` as the way to say "you can call into / index into `this`".

However, since that time, we've introduced operators into the language, which represent another compelling way to represent this since it could be viewed as the application of `[...]` or `(...)` to the `this` argument.  Some minor challenges to taking an operator-based approach include:
* what would we call it?
* since `[...]` and `(...)` are interchangeable in Chapel, how would we indicate that this operator supports both?
* since none of our operators so far have a `this` argument, presumably `this` would need to be taken in as the first formal argument explicitly?  E.g., to support a call on type `R` that takes a single `int`, it seems like we'd write `operator R.whateverItsCalled(r: R, i: int) { ... }` rather than simply `operator R.whateverItsCalled(i: int) { ... }`?

As far as names go, here are some initial brainstorms:
* `operator R.this(...)`
* `operator R.call(...)`
* `operator R.index(...)`
* `operator R.access(...)`
* `operator R.[](...)`  // relies on understanding that defining this operator also defines paren-access
* `operator R.[(...)`   // ditto: express the operator as a single square bracket rather than a pair
* `operator R.[(...)]`  // put the formals where they fall syntactically?  (but maybe explicit `this` breaks this anyway)
* `operator R.(...)`  // no operator name => the direct accessor operator

Or, given the caveats/compromises above and that `this` is reserved, are these changes a marked improvement over the status quo?

**Comment by ronawho** [comment]
See also https://github.com/chapel-lang/chapel/issues/18263

**Comment by bradcray** [comment]
D'oh!  You won't believe that I actually looked for this and failed to find it, will you?  (I did).

**Comment by dlongnecke-cray** [comment]
I posted my thoughts in #18263. Not sure if we want to close this thread in favor of that one.

**Comment by bradcray** [comment]
Closing this in favor of https://github.com/chapel-lang/chapel/issues/18263 which I've updated to reflect some new ideas here.
