### ISSUE TITLE
build system should produce a better error message if CHPL_LAUNCHER is invalid

### ISSUE THREAD

**Issue by jhh67** [chapel-lang/chapel#19063]
```
bash-3.2$ export CHPL_LAUNCHER=foo
bash-3.2$ make
...
Makefile.help:61: src/launch/foo/Makefile.include: No such file or directory
make[3]: *** No rule to make target `src/launch/foo/Makefile.include'.  Stop.
```
It should tell me that `CHPL_LAUNCHER` is invalid and if possible list the valid launchers.

**Comment by mppf** [comment]
@jhh67 - I agree - I just wanted to mention that in fact we have this problem for quite a few of the settings printed by `printchplenv`.
