### ISSUE TITLE
Stabilization of timeSinceEpoch

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#19098]
(split off from https://github.com/chapel-lang/chapel/issues/18834)

## Background on `timeSinceEpoch`

In the stabilization of the `Time` module (https://github.com/Cray/chapel-private/issues/1320), we decided that we would deprecate [getCurrentTime](https://chapel-lang.org/docs/master/modules/standard/Time.html#Time.getCurrentTime) since similar functionality is available in the `DateTime` module: `datetime.now()`.

However, there were 2 issues with this replacement:

1. Getting the DateTime version to output the same format our `getCurrentTime` required a more complicated replacement:

```
(datetime.now() - datetime.now().replace(hour=0,minute=0,second=0,microsecond=0)).total_seconds()
```

2. `getCurrentTime` gets the time since midnight, which isn't generally useful (https://github.com/chapel-lang/chapel/issues/14571).

Therefore, it was proposed that we support a more useful "time since unix epoch" function, which should still effectively act as a drop-in replacement for the deprecated `getCurrentTime`. This was added as [`datetime.timeSinceEpoch`](https://chapel-lang.org/docs/master/modules/standard/DateTime.html#DateTime.datetime.timeSinceEpoch) in Chapel 1.25.

## Proposed changes

Later on in the stabilization review of `DateTime`, it was agreed that `timeSinceEpoch` is a proc type on `datetime` to return a real and doesn't pertain to the `datetime` type in any way. Therefore, the following has been proposed:

1. `timeSinceEpoch` be separated out into a standalone function
2. `timeSinceEpoch` be moved to another module, such as the module that contains `Stopwatch` 
   - name being discussed here: https://github.com/Cray/chapel-private/issues/1322

**Comment by ben-albrecht** [comment]
My initial thoughts:

1. I agree that `timeSinceEpoch` would make more sense as a standalone function, because it has a very loose association with `datetime` and would have a neater call signature as a standalone function than as a proc type.
2. I think this decision depends on what we call the module that holds `Stopwatch`, but if the current leading name of `Timers` is chosen, then I think `timeSinceEpoch` fits appropriates in that module because it is another mechanism available for timing programs.

**Comment by bradcray** [comment]
I also agree with point 1, and think that in more recent discussions, we've been favoring standalone methods over type methods, on the argument that `import` provides sufficient namespacing safety without requiring a user who likes full qualification to write `DateTime.datetime.timeSinceEpoch()` or `dt.datetime.timeSinceEpoch()`, say.

On point 2, I don't think I understand why `timeSinceEpoch` doesn't belong in `DateTime`.  That seems like the most reasonable place for it to me — measure the time that's passed since this specific date/time.

**Comment by ben-albrecht** [comment]
Another thought: `timeSinceEpoch` can be viewed as a shortcut to computing the difference between `datetime.now()` and `unixEpoch()`, which both live in `DateTime`. Under that perspective, it makes sense to keep it in `DateTime`.

**Comment by mppf** [comment]
I think `timeSinceEpoch` should be a standalone function in DateTime.

**Comment by daviditen** [comment]
Closed with https://github.com/chapel-lang/chapel/pull/19934 which made it a standalone function in DateTime that returns a timedelta.
