### ISSUE TITLE
Should `ref` arguments be permitted to take non-lvalue default values?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#19116]
### Summary of Problem

While working on an Advent of Code problem, I was writing a recursive procedure, and found myself wanting to have a `ref` argument (because I wanted changes to it to be reflected up and down the callchain) but also wanted it to have a default value (because I didn't want to require the original caller to require it), where my default value was a literal expression.  Today, the compiler complains:

```
error: const actual is passed to 'ref' formal 'argName' of fnName()
```

I can see why it might say this—we consider the literal expression to be `const`/`param` and to not have an l-value.  Yet it would also be very convenient to support such patterns, and I'm not immediately seeing a downside to permitting it.

[edit: Paul @cassella did, however, in [his comments below](https://github.com/chapel-lang/chapel/issues/19116#issuecomment-1053912110), and I think his points stick for me.  I also like his notion of writing `new int(0)` to get the behavior I wanted that motivated me to post this... once we have that form for scalar values anyway].

(I know there've been long-term discussions throughout the project about cases similar to this—whether languages have traditionally conflated constants and refs and l-valueness more than they should, and whether we should balk that trend.  I think we do in some cases, but not this one).

### Steps to Reproduce

**Associated Future Test(s):**
[`test/studies/adventOfCode/2021/bradc/futures/day18-defaultRefVar.chpl`](
           https://github.com/chapel-lang/chapel/blob/main/test/studies/adventOfCode/2021/bradc/futures/day18-defaultRefVar.chpl
          ) #19028 

### Configuration Information

- Output of `chpl --version`: `chpl version 1.26.0 pre-release (b94e1c4598)`

**Comment by bradcray** [comment]
Tagging @cassella on this because his #7924 had a similar case (now marked as "resolved" since it's generating the behavior described here rather than an internal error), though perhaps he was simply looking for internal errors and corner cases rather than wanting this feature?  Also tagging @mppf since his PR resolved that case.

**Comment by mppf** [comment]
I agree that it wouldn't be particularly worrying to allow this specifically for arguments like `proc f(ref arg = 1)`, where the compiler would just generate a tmp containing `1` if a value for arg isn't passed.

I think the only concern is whether or not that makes the language harder to predict (i.e. is it a special case that will confuse people into thinking that we allow `1` to be passed to a `ref` argument more broadly?)

**Comment by bradcray** [comment]
> (i.e. is it a special case that will confuse people into thinking that we allow 1 to be passed to a ref argument more broadly?)

I suppose it could, but I still think I find the feature more attractive than I fear the potential for confusion.

**Comment by cassella** [comment]
My thinking in #7924 was that all those cases should be errors, for lvalue reasons. I was taking `ref foo = 7` literally (as well `out` and `inout`) -- all of those cases taken as written would seem to mean storing to `7`.  (When the proc with the ref arg stores to the arg.)

Having the compiler instead insert a temporary makes sense (as a language convenience enhancement, not as a natural interpretation of the spec as it stands).

I'd also be concerned about confusion between

```chapel
proc foo(ref a = someParam, ref b = someGlobal)
```

where those would be somewhat different things.  (The behavior of the latter at least today is to make `b` a reference to `someGlobal`.)

Would `ref c = someGlobalConst` be given this convenience treatment of a new temporary with the value of the constant, or continue to be an error?  I think the suggestion above is  the former.  I'd be concerned that a reader of the function wouldn't know if the function has an effect on the named default value without tracking down its definition.

It could be made explicit (letting the author be clear that this is what they want, and letting the reader know it's happening) with some syntax, maybe

```chapel
proc countDown(x: int, ref pos = new int(0))
```

This would also let you opt in to this behavior when the thing you want to use as the starting value of your temp is a regular variable,


Would this extend to records and classes as well?  

```chapel
proc foo(ref r = new SomeRecord(a,b), ref c = new SomeClass(x,y))
```

**Comment by bradcray** [comment]
Those are good points, Paul, particularly the difference between using something that "obviously" doesn't have an l-value / can't be modified (like `0` in my future) and something that may be less obvious like a named param, constant, or global.  I also really like your `new int(0)` counterproposal which is something I already want to do anyway (create new scalar values that way) and feels like less of a problem.  I.e., if we had that (and it had occurred to me), I would have happily used that and not filed this.  I'll update the OP to mention it (and improve the title, which I'm realizing is vague).

**Comment by cassella** [comment]
One downside is that it's harder to have the type of the argument be inferred from the default value's this way,

```chapel
proc foo(ref r = new someGlobal.type(someGlobal))
```
?

**Comment by bradcray** [comment]
Hi Paul — I don't think I'm following.  Harder in what sense?

Oh, do you mean "it's more typing for the user to get this behavior?"

And presumably `someGlobal` here would need to be `const` or `param` for me to write it this way rather than simply `= someGlobal`?

**Comment by cassella** [comment]
I'd meant the more typing in this new case of a ref-tmp, and also wasn't expecting that syntax to compile.  Now that I've tried with a record type, I see it does compile.  (I'm glad I didn't suggest the syntax `ref pos = new 0`.)

As to the other, maybe it's my turn to not follow.  If it's a regular `var someGlobal`, and you write `proc foo (ref r = someGlobal)`, today you get an actual ref to `someGlobal`.  So if you want a temp instead of a ref, you'd need to do something in that case.  (Unless you're proposing changing the existing behavior.  Making that a ref-tmp would avoid the ambiguity, but IMO be a less intuitive thing for this case to mean.)  But in my proposal, you could write it this way to get a ref-tmp for `const`, `param`, or `var` globals.  And in order to get the ref-tmp, you'd have to: to avoid the regular ref case for `var`, or as the only way to compile for the other two cases.  The "downside" was just about having to hardcode the type of the argument, or having to do all that kinda-ugly typing now, and then having to read it forevermore.  But I feel like I'm missing your point.

I suppose as a countercounterargument, if you really want your function's argument to be whatever the type of the global is, and not have that long `new` type name, you could declare a type alias for it explicitly and use that in any ref-tmp `new` calls.

(You might not even be able to reasonably hard-code the type if it's dependent on a `config param`, e.g. `var someGlobal = if someParam 1 else 1.0`.)

**Comment by bradcray** [comment]
> I'd meant the more typing in this new case of a ref-tmp

I see.  That doesn't really worry me because I'm imagining that, as the author of foo(), I probably have a pretty good sense of what I want `r`'s type to be and therefore could just name it directly.  In cases where the type of the default would vary depending on a config param, I'd tend to imagine that my routine would already have logic to handle both cases of the config param anyway, that I'd probably introduced a little type procedure that returned int vs. real for the two cases, etc.  So I think the cases where I'd be motivated to do the "more typing" approach are rare and don't undermine your proposal for me.


> So if you want a temp instead of a ref

OK, I didn't understand that's what you were trying to write.  I do now.

I think I'm inclined to close this issue in favor of a new one requesting the ability to write `new int()` if you still feel good about that approach for getting this pattern.
