### ISSUE TITLE
Should `string.strip` take an array of characters, instead of a string that represents that?

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#19126]
[... and extrapolation of that question on `bytes`]

In https://github.com/chapel-lang/chapel/issues/19119#issuecomment-1022550934, @bradcray  implied that the argument to `string.strip` shouldn't be interpreted as an array of characters. Which makes good sense to me.

I feel like there are other linux and/or python interfaces that also takes a string but interpret that string as an array of characters. The `-d` argument to `cut`, maybe? So, there may be some precedence to what we have today. But I think it is a worthy discussion whether we want to stick to it or change it.

**Comment by e-kayrakli** [comment]
@arezaii -- Tagging you because of your work in string/bytes stabilization.

**Comment by arezaii** [comment]
I just went through this with Python's `strip` family of methods, which take a string as input, but treat them as an array of chars to match on. My expectation was that I need to match the string pattern to strip, but when that failed, I had to return to the docs, where it is explained that the string is treated as an array (list). That's probably where our design originated from, but I do think it's confusing and would probably prefer our `strip` it to not hide the fact that it treats the string as an array of chars.

**Comment by ben-albrecht** [comment]
I would argue that the behavior of `string.strip()` should stay as is since the alternative use-case of removing a substring from a string can already be achieved with `string.replace()`. Switching the behavior of `strip` would result in (1) two ways to do the same thing and (2) make it less ergonomic to strip an array of characters from a string, e.g. it'd require multiple calls to `string.replace()`

**Comment by e-kayrakli** [comment]
@ben-albrecht 

`strip` and `replace` are different things, though. `strip` only looks at the ends of the string. So they are different.

> make it less ergonomic to strip an array of characters from a string, e.g. it'd require multiple calls to string.replace()

What do you mean by this?

**Comment by ben-albrecht** [comment]
Whoops, I misremembered how strip works in our library. I was thinking that it stripped a character from the entire string. Disregard the first paragraph of my previous comment 😄

**Comment by bradcray** [comment]
> support stripping substrings, like @bradcray originally expected.

This isn't an accurate portrayal of my expectations — I didn't/don't have any expectation for what `myString.strip("moreThanOneCharString")` would or should do and don't object to the current behavior.  In the comment Engin quotes, I was only objecting to Engin's suggestion that maybe `myString.contains("substring")` should treat its argument as a strip-like "array of characters" rather than a substring as with `find()`.

**Comment by ben-albrecht** [comment]
> > support stripping substrings, like @bradcray originally expected.
> 
> This isn't an accurate portrayal of my expectations — I didn't/don't have any expectation for what `myString.strip("moreThanOneCharString")` would or should do and don't object to the current behavior. In the comment Engin quotes, I was only objecting to Engin's suggestion that maybe `myString.contains("substring")` should treat its argument as a strip-like "array of characters" rather than a substring as with `find()`.

Thanks for the clarification, I'll remove that statement from my above comment.

**Comment by lydia-duncan** [comment]
@arezaii, @e-kayrakli - do either of you know the status of this one w.r.t. 2.0?  Did we decide to just add an overload that takes an array of strings later or did we just not discuss this in one of the 2.0 meetings?  I'm not finding any further resolution beyond Ben's comment

**Comment by arezaii** [comment]
I don't think we decided to add or change anything for 2.0. I don't have it in my notes, but I believe we wanted to stay in line with other languages for the single string overload, and figured that if we do later decide to add an array overload it would be non-breaking.

**Comment by arezaii** [comment]
Closing since we settled on 'no' to answer the original question and a new issue can be made to ask for an overload for this functionality.
