### ISSUE TITLE
Mark Array.equals() as being unstable.

### ISSUE THREAD

**Issue by stonea** [chapel-lang/chapel#19140]
This is fallout from the Array Module re-review (https://github.com/Cray/chapel-private/issues/2955)

We're thinking long term we'll have a standalone `equal` function that has an array overload and a generic overload that calls ==. In the meantime we'll should have Array.equals() marked as unstable.

**Comment by bradcray** [comment]
As part of this, it'd be interesting to review where .equals() is used today.
