### ISSUE TITLE
Docker Hub releases and tags are inconsistent, add ARM64 Docker support...

### ISSUE THREAD

**Issue by GordonBGood** [chapel-lang/chapel#19151]
### Summary of Problem

The [README.md file](https://hub.docker.com/r/chapel/chapel) used for the Docker Hub overview is not consistent with the most recent releases leading to the current stable version 1.25.1, still listing version 1.24.0 as latest, also, this is not consistent with the [Docker Hub "Tags" field](https://hub.docker.com/r/chapel/chapel/tags), which lists versions 1.24.1, 1.25.0, and 1.25.1 as being available.  The version 1.25.1 DockerFile availability is not consistent with this repo in that the [DockerFile linked to the tagged version 1.25.1 release](https://github.com/chapel-lang/chapel/blob/1.25.1/util/dockerfiles/Dockerfile) has an internally coded version of 1.25.0 not 1.25.1.

Finally, with the trending greatly increased use of ARM64 architectures, Docker images for the Chapel compiler supporting this tag type and architecture should be made available from the Docker Hub.

### Configuration Information

This is a "Meta" problem not related to the actual use of the compiler...

**Comment by bradcray** [comment]
Hi @GordonBGood — First, thanks very much for filing this issue and bringing it to our attention.  With respect to the items identified in this issue:

* I believe that we've been doing a better job of keeping the README versions up-to-date in this calendar year's releases, including today's 1.28.0 release.

* As part of today's release prep, @bhavanijayakumaran made improvements to the Docker image to address arm portability issues that she was seeing.

* The version inconsistency you note between the Docker formula in a given Chapel release and the release itself is an offshoot of the order in which we've done operations in the release and, to my knowledge, should not be problematic even though it is surprising and inconsistent-seeming.  We'd noted this ourselves today and started a discussion about trying to update the formula earlier for the next release to avoid an apparent mismatch

If you had time to verify that the first two bullets are as you'd expect and that we could close this issue, that would be great.  If the third bullet has more significance than I'm giving it, please let me know.

If you're not able to check this, I'll probably close the issue based on my understanding of the status, and we can re-open it or start a new issue if there are lingering issues that we've missed.

Thanks again!

**Comment by bradcray** [comment]
Based on my understanding, I'm marking this as resolved.  But again, if @GordonBGood or others think that's wrong, we can either re-open it or spawn any remaining threads off into new issues.  Thanks again for bringing this to our attention!

**Comment by GordonBGood** [comment]
@bradcray, I had intended to update to the latest version 1.28.0 and then comment on that basis of that experience; however, I've been deep into another project and didn't get to this in time.

As the purpose of filing this issue was just to give you contributors a "heads-up" on the possible perceived inconsistencies between the various sources so in light of your response here, it looks like attention has been given to this and its purpose has been served.

Thus, I agree that the issue should be closed (at least for now)...

**Comment by bradcray** [comment]
Thanks for the comment Gordon, and no worries.  I closed it as much to remove any time-sensitive pressure from you as anything.  If/when you do get a chance to try 1.28.0, let us know if you find any additional/missed inconsistencies (though note that the dockerfile on GitHub under the 1.28 tag will refers to 1.27... we didn't catch that one in time and are trying to resolve it for the next release.  In fact, I think this PR does that:  https://github.com/chapel-lang/chapel/pull/20705
