### ISSUE TITLE
What should we call the user-facing replacements for common CHPL_* checks?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#19188]
In reviewing the ChapelEnv.chpl module, soon to become the ChplConfig.chpl module, we decided to add support for common queries using a nicely named user-facing routine rather than having users compare against CHPL_* environment variables.  Based on the experience of https://github.com/chapel-lang/chapel/pull/19162, the most common queries are:

* `CHPL_COMM=="none"` (or !=):  "Is this program being compiled for a single locale only, or for multiple locales?"
* `CHPL_COMM=="ugni"` or `CHPL_NETWORK_ATOMICS!="none"`: "Is this program being compiled for a configuration that supports network atomics?"

This issue asks for proposals as to what we should call such queries.  So far, I've only thought of ideas I don't like, so I'm not seeding the conversation with any proposals.

**Comment by ronawho** [comment]
> Is this program being compiled for a configuration that supports network atomics?"

FWIW in the near-ish future I expect network atomics to just be part of the standard comm API and not optional, so this query might not be interesting anymore. There may still be related questions like is this atomic implemented natively in hardware, but I don't think we need to standardize queries like that anytime soon.

**Comment by riftEmber** [comment]
In the [ChplConfig design discussion](https://github.com/Cray/chapel-private/issues/4809) we decided to add just one query for 2.0: `compiledForSingleLocale()`, which will return true if the user's program is being compiled for a single locale only. Implementation issue: https://github.com/Cray/chapel-private/issues/5019

@bradcray, do you think this issue should be closed? We have settled on the queries that will make it in to 2.0, but I could also see one wanting to keep this open for future post-2.0 discussion.

**Comment by bradcray** [comment]
It'd be fine with me to close this and re-open more specific issues once we have additional specific queries we want to design and add.
