### ISSUE TITLE
Can we simplify the function disambiguation rules?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#19195]
This issue is about the algorithm for function disambiguation / overload resolution / computing the most specific candidates.

What we have today is described in the language specification here:

https://chapel-lang.org/docs/language/spec/procedures.html#determining-more-specific-functions

These rules are fairly complex. The implementation of these rules is here: https://github.com/chapel-lang/chapel/blob/main/compiler/resolution/functionResolution.cpp#L5377 .

This issue is asking a few questions about the algorithm and the related rules.

### Does function disambiguation use a partial order? Should it?

This is especially related to https://chapel.discourse.group/t/overload-resolution/10252 and #19167.

We have a compareSpecificity function that returns -1/0/1 to indicate fn1 is more specific; they are the same level of specificity; or fn2 is more specific. 

https://github.com/chapel-lang/chapel/blob/bf9f12a25b155e77c5f61b16b025a7761a83db26/compiler/resolution/functionResolution.cpp#L5469-L5487

However we have seen some hints that there are problems in this area. Commit aebdceb23e28fd834ee2b071047aad8064240ca2 addressed one surprising behavior (where the order of candidates mattered). Additionally, while I was developing PR #7659, I remember encountering situations where compareSpecificity is not transitive and seeing unexpected ambiguity in that event.

One immediate question is this -- does `0` from compareSpecificity mean "the same specificity" or "these are incomparable"? If it means "these are incomparable" then probably the change in commit aebdceb23e28fd834ee2b071047aad8064240ca2 is not quite right.

See also this comment added in aebdceb23e28fd834ee2b071047aad8064240ca2:

https://github.com/chapel-lang/chapel/blob/bf9f12a25b155e77c5f61b16b025a7761a83db26/compiler/resolution/functionResolution.cpp#L5438-L5442

A further question is, suppose that compareSpecificity is not transitive. What harm will come of it? Is it always unexpected ambiguity? Or is it possible for the process to choose something that is a worse match than another candidate?

A next step here would be to add some experimental checking to the compiler to understand more about what cases are currently non-transitive, if any:
 * For a given set of candidates that we see in disambiguateByMatch, check that compareSpecificity is transitive, and report the non-transitive case if not (and bring it up here for discussion)
 * For all types at the end of function resolution, check that `moreSpecific` is transitive and report any cases that are not (and bring them up here for discussion) https://github.com/chapel-lang/chapel/blob/bf9f12a25b155e77c5f61b16b025a7761a83db26/compiler/resolution/functionResolution.cpp#L1797
 
### Could we remove some of the complexity of these?

IMO before PR #7659, the function disambiguation rules were already pretty complex, and that PR added the 3 levels of preference which made them even more so. Here we are considering what we might be able to do in order to make the rules less complex.

One idea is to remove most/all of the additional complexity in PR #7659 and instead have the compiler directly handle things like `+` on integers. At the moment, AFAIK it won't be possible for a user to add their own `+` on integers that participates in the same disambiguation process due to the overload sets checking. And the more complex disambiguation rules from PR #7659 exist so that we can determine an appropriate type for param expressions such as `1:uint(8) + 32` (with rules that effectively choose the overload that returns the type we want). But it might well be simpler for the language and for the implementation if these cases are handled directly by the compiler, since a user can't add more `param` types and can't currently add any more implicit conversions (but see #16729 for proposals in that area).

I have occasionally wondered if it would be possible to remove the "prefer int to uint" rule. Also, in my experience, the rules we need here to enable programs that we want to work depends on the set of implicit conversions allowed. For example in #19194 we are discussing removing int -> real implicit conversions. Perhaps we can simplify these rules more if we remove some implicit conversions.

**Comment by mppf** [comment]
FWIW I looked up the C# rules and they are described here https://docs.microsoft.com/en-us/dotnet/visual-basic/reference/language-specification/overload-resolution -- which has much more examples than the section in the Chapel specification but is also quite a bit longer. Even so, we could probably improve on the structure of our disambiguation process to make the process more understandable, if if there remain a lot of individual rules.

**Comment by mppf** [comment]
In conversation with @bradcray we are thinking:
 * we should try to improve the situation here
 * one approach that might make sense is to have a policy where we drop all less-visible candidates if there is any more-visible candidate. This fits with the overload sets/overload group idea.

One thing that is interesting to consider is if we could have even more aggressive shadowing that happens while getting visible functions. But this needs to be evaluated with some test cases. See https://github.com/chapel-lang/chapel/issues/19167#issuecomment-1036591239 .

**Comment by mppf** [comment]
In my earlier post, the reason to drop all less-visible candidates if there is a more-visible candidate is that it allows some flexibility in implementing numeric conversions (partly for the strategy I am leaning to for #19194). In particular:
 * the library could implement say `operator +(a: numeric, b: numeric)` and have it be a `compilerError` in cases where the types aren't compatible enough
 * a different module like `MoreImplicitNumericConversions` could completely re-implement `operator +` on numeric types using a different strategy (say, it might have 4 overloads instead of 1; or it might continue to be generic in the same way).
 * the fact that we could implement `operator +(a: numeric, b: numeric)` and `operator +(param a: numeric, param b: numeric)` means that some of the squirrely disambiguation rules from PR #7659 would not be necessary and instead these can be handled in module code inside of these functions.

I am uncertain to what extent we need other functions, like `proc myAdd(param a, param b)`, to try to choose the overload that probably has the return type we want based on weaker/weakest preferred etc. In particular, if using something along the lines of `operator +(param a: numeric, param b: numeric)` works for the standard library then I think a user wanting to make `myAdd` could use a similar technique.

**Comment by bradcray** [comment]
> the library could implement say operator +(a: numeric, b: numeric) and have it be a compilerError in cases where the types aren't compatible enough

I feel a little bit on the fence about this approach (but didn't get the chance to say so when we were talking last week).  But truly in the "on the fence / unsure in the middle" sense, not in the "I'm opposed to it, but don't want to say so" sense.

The reason I say that is that if you gave me the choice between chpldoc-based documentation of our `+` overloads that enumerated all of the signatures that we supported today, and I could see cases like "int(x) + int(x) => int(x)" clearly, that seems far preferable to a single + overload that had a lengthy English description trying to describe what happens in every combination of numeric values.  Similarly, I like the idea of a language where a user could create their own procedure-based operator for a variety of types, param-ness, etc. and come up with something as rich/flexible as our `+` without having to combine all numeric cases into a single overload.

That said, I also realize that the number of overloads is very confusing (i.e., while "int(x) + int(x) => int(x)" may be clear in the docs, it probably is not as clear what all the overloads are for and why they exist).  And I also realize that the disambiguation rules for all of the overloads are part of the reason that disambiguation is so complicated and that such heavily-overloaded cases don't come up all that often for someone not trying to create a new operator-like thing.

To that end, I find myself curious how much of the disambiguation complexity is due to + specifically vs. other similar cases that exist throughout our library code; and whether there's more that could be done to reduce the complexity of the `+` overloads without reducing them all to a single routine.

**Comment by mppf** [comment]
> one approach that might make sense is to have a policy where we drop all less-visible candidates if there is any more-visible candidate. 

Today, I don't think we do anything special for methods in disambiguation. I thought a bit about if we would need to, in order to do this.

The overloads sets checking already has a special rule class methods (see [overloadSets.rst)](https://chapel-lang.org/docs/technotes/overloadSets.html):

>    If it is a method call on a class, the best candidate is defined in the same module as the class of the receiver actual argument.

I wrote an example where to explore "more visible" vs "more specific" for some methods on some integer types. But, I didn't come away from it feeling like we need to do anything special for methods for the rule proposed above. In particular, there have to be implicit conversions for there to be two methods in the overloads set from different modules.

<details>

``` chapel

module M1 {
  proc (int(16)).f(arg: int)    { writeln("M1 int(16).f(arg: int)"); }
  proc (int(32)).f(arg: string) { writeln("M1 int(32).f(arg: string)"); }

  proc test() {
    var x:uint(8) = 1;
    x.f(1);    // M1 int(16).f(arg: int)
    x.f("hi"); // M1 int(32).f(arg: string)
  }

  proc callF(b) {
    // POI not consulted because candidates are found without POI
    b.f(1);    // M1 int(16).f(arg: int)
    b.f("hi"); // M1 int(32).f(arg: string)
  }
}

module M2 {
  use M1;

  proc (int(32)).f(arg: int)    { writeln("M2 int(32).f(arg: int)"); }
  proc (int(16)).f(arg: string) { writeln("M2 int(16).f(arg: string)"); }

  proc main() {

    M1.test();

    var x:uint(8) = 1;
    M1.callF(x);

    // overload set error - want to use int(16).f(1) since it is more
    // specific, but it is further away.
    x.f(1); // w/out overload sets checking -- M1 int(16).f(arg: int)

    // choosing the more visible one anyway, so no overload set error
    x.f("hi"); // M2 int(16).f(arg: string)
  }
}

```

</details>

**Comment by mppf** [comment]
I have instrumented disambiguation in the production compiler to print out when the relationship among candidates is not transitive in https://github.com/mppf/chapel/tree/check-partial-order .

When compiling a few example programs I am seeing many failures related to int -> real/complex conversions and also bool -> int/uint conversions.

```
transitivity fail : i < j and j < k but not i < k
actuals: (CHPL_RT_MD_STR_COPY_DATA : int(16), <temporary> : int(16))
i: -(a: real(32), b: complex(64)) [454047]
j: -(a: complex(128), b: real(64)) [454177]
k: -(a: complex(64), b: real(32)) [454137]
...
transitivity fail : i < j and j < k but not i < k
actuals: (false : bool, false : bool)
i: |(a: int(32), b: int(32)) [460073]
j: |(a: uint(64), b: uint(64)) [460183]
k: |(a: uint(8), b: int(8)) [460205]
...
transitivity fail : i < j and j < k but not i < k
actuals: (true : bool, true : bool)
i: &(param a: int(32), param b: int(32)) [1351859]
j: &(param a: uint(64), param b: uint(64)) [1351944]
k: &(param a: int(16), param b: uint(16)) [1352046]
```

The good news though is that, at least based on the small number of programs I tried, the non-partial-order cases are falling into just a few patterns.

**Comment by bradcray** [comment]
A question triggered by the first of these three cases:  I think in our recent discussions with Damian, you and I have both been coming to the conclusion that perhaps int(w) should only coerce to real(w) for w=32,64, at least.  What does that imply for int(16) and int(8)?  That it should never coerce to a real?  Or that it should coerce to the smallest float (real(32) currently).

I'm also curious how these experiments influence your thinking.  E.g., would we want to check for these intransitive cases and always consider them an ambiguity (e.g., "something about these is non-linear, so rather than picking one surprisingly, we'll alert the user and force them to choose"?).  Or is doing the transitivity checks more O(n**2) than we'd like?

**Comment by mppf** [comment]
> A question triggered by the first of these three cases: I think in our recent discussions with Damian, you and I have both been coming to the conclusion that perhaps int(w) should only coerce to real(w) for w=32,64, at least. What does that imply for int(16) and int(8)? That it should never coerce to a real? Or that it should coerce to the smallest float (real(32) currently).

Right, int(8) and int(16) already coerce to real (because they are small enough to fit in the "mantissa" / significand). I have been thinking of that conversation as adding that int(32) can coerce to real(32) but leaving int(8) / int(16) coercing to real(32) (because I think these implicit conversions should be transitive).

If we were to add real(16), I would expect int(8) and int(16) to coerce to it as well as real(32) / real(64); but disambiguation would prefer real(16) to real(32) or real(64) due to the "can dispatch" rule "If there is an implicit conversion from T_X to T_Y, then M_X is more specific."

> I'm also curious how these experiments influence your thinking. E.g., would we want to check for these intransitive cases and always consider them an ambiguity (e.g., "something about these is non-linear, so rather than picking one surprisingly, we'll alert the user and force them to choose"?). Or is doing the transitivity checks more O(n**2) than we'd like?

Mainly I am trying to come up to an adjustment to the rules that avoids the non-transitive cases. I am viewing them as a case we would like to improve. The transitivity checks are `O(n**3)` and so I'd be hesitant to have them on all the time, but perhaps one day we could have them on with `--verify`; or perhaps we could find a lighter weight check that still adds value. But for now I am just focused on coming up with a proposal to adjust the disambiguation rules.

**Comment by bradcray** [comment]
:+1: to everything you wrote above, except for:

> because I think these implicit conversions should be transitive

I realize we're on a sidebar to the issue at hand here, but I still don't think I agree with this (or else would need more convincing).  E.g., I think it's reasonable for bools to coerce to ints, and ints to reals, and reals to complexes, but I don't think that means that bools should coerce to complexes.

**Comment by mppf** [comment]
One thing we can do, for the built-in numeric types anyway, is to adjust the rules to say something like "bool is a better match than int/real/complex". We can do such a thing to make the "more specific formal type" relation transitive even if the implicit conversions are not. However this particular case did not appear as problematic in my experiments, so maybe it is moot.
