### ISSUE TITLE
Support standalone readline() routine?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#19229]
[splitting this off from #18849]

Our main I/O routines (`read()`, `readf()`, `readln()`, `write()`, `writeln()`) can be called as methods on a channel, or as standalone routines.  In the standalone form, they are equivalent to being applied to the `stdin` and `stdout` channels by default (respectively for input vs. output routines).

The `readline()` method currently only supports being called on a channel, requiring a user who wants to read lines from `stdin` to call `stdin.readline()` rather than simply `readline()`.  In this issue, I'm proposing that we support a standalone `readline()`, for symmetry with the `read()` and `readln()` routines.

In https://github.com/chapel-lang/chapel/issues/18849, @mppf argued that perhaps we should consider removing the standalone forms of the other `read()`, `readln()` routines instead, and require them to be called on `stdin`, but I'm not a champion of that proposal, so am only listing it here for completeness, not because I'm advocating for it.

**Comment by mppf** [comment]
Would the standalone `readline` throw or halt if there is an error reading? I am assuming you would have it return `false` or maybe even `""` for EOF. Anyway, I am not comfortable having a non-method `readline` that halts.

Note that this is among the routines we will discuss as part of upcoming I/O review and I already have some proposals in this area that haven't made it to issues.

**Comment by bradcray** [comment]
> Would the standalone readline throw or halt if there is an error reading?

I was not intending to make `readline(...)` any different than `stdin.readline(...)` in this regard.

**Comment by dlongnecke-cray** [comment]
What is the difference between `readln` and `readline`? To my (haven't checked the docs yet) eyes, they both seem like different names for the exact same thing.

**Comment by bradcray** [comment]
> What is the difference between readln and readline? 

This classic question is discussed here (and I'm hoping to consider it independent of this issue's question):  https://github.com/chapel-lang/chapel/issues/14107

The short answer is that readln() was designed to be the dual of writeln() for read() ("read all this stuff and then skip to the next linefeed") whereas readline() is designed to literally "read one line".

**Comment by dlongnecke-cray** [comment]
Thanks Brad!

Given that this is well established ground, I'll 👍 supporting a standalone `readline()` and go take my disgruntled musings to #14107.
