### ISSUE TITLE
Deprecate `vectorizeOnly()` in favor of `foreach`

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#19238]
The `vectorizeOnly()` iterator has been mentally deprecated among the team for some time now, but we hadn't officially deprecated it because we didn't really have an alternative to suggest instead (i.e., "Would we breathe new life into it over time?").  Now that we have `foreach` loops, it seems high time to deprecate it, and its module, referring users to `foreach` instead.

The one part about this plan that makes me slightly nervous is that `foreach` doesn't really feel completely ready for prime-time, due primarily to its lack of shadow variables and task intents (#18500).  That said, it still seems to be in strictly better condition than `vectorizeOnly()` is and steering people away from `vectorizeOnly()` seems like the right thing to do in any case.  Also, I feel confident that `foreach` will get better over time, and don't expect that to happen with `vectorizeOnly()` at this point.

**Comment by bradcray** [comment]
I marked this as a user issue because a user's attempt to use it this week and our manually referring them to `foreach` prompted this issue.

**Comment by mppf** [comment]
I'm not certain, but I think it is possible to write a `forall a in vectorizeOnly()` loop with forall intents / reductions etc. What I don't know is whether or not this does something reasonable today.

**Comment by bradcray** [comment]
I agree you could write it and that it would behave correctly, but my guess was that it wouldn't do anything particularly reasonable/constructive/well-defined today.  But am I wrong about that?  (particularly with the LLVM back-end?  I.e., do we convey vectorizeOnly() calls through to the LLVM back-end?).

**Comment by mppf** [comment]
> do we convey vectorizeOnly() calls through to the LLVM back-end?

Yes but we also do that for `foreach`. I am not sure what the LLVM IR we are generating looks like for a forall + vectorizeOnly + reduction, say. It's possible it's doing something useful today. But I also think it's unlikely we have people doing that / relying on that pattern.

**Comment by bradcray** [comment]
OK, so this conversation makes me think "We should still deprecate", but then maybe not remove as aggressively, at least until `foreach` is a bit more complete since it sounds like `vectorizeOnly()` has been maintained better than I'd been assuming.  How does that sound to you?

**Comment by mppf** [comment]
Sounds good

**Comment by bradcray** [comment]
I opened up PR #19419 to do this, and it mostly was a simple textual update except that LCALS (which is in the release directory) still relies on `vectorizeOnly()` since it would want to use reduction intents on a `foreach` which we don't support yet (#18500).  Alternatively, we could write the foreach to do a manual `+=` within the body of the loop, though we were feeling un-confident that such patterns should be legal in https://github.com/chapel-lang/chapel/issues/19153

So some options here are:
1) Do nothing with the PR, leaving vectorizeOnly() undeprecated until we support task intents
2) Merge the PR as-is, with LCALS generating a warning
3) Change LCALS to use the += form of the reduction since "it seems to work" today and then once we have shadow variables and task intents, it'll become an error and we can update it then
4) Something else I haven't thought of.

Tagging @daviditen and @chapel-lang/perf-team because of the role of LCALS here, and @e-kayrakli because of the interaction with `foreach`.

**Comment by ronawho** [comment]
I don't think we saw any performance benefit from the vectorizeOnly version of LCALS and we don't currently run those variants. I'd be fine with having LCALS warn or even just removing those variants if we wanted.

**Comment by e-kayrakli** [comment]
I'm good with deprecating `vectorizeOnly`. I don't have any strong opinions as to how LCALS should be updated to handle that. Just accepting warnings sounds good for now, though.

**Comment by bradcray** [comment]
I just asked on chat, but if any of you who've commented on this issue would consider reviewing #19419, I'd appreciate it.  I'd failed to notice that nobody had reviewed it earlier, just the concept here.
