### ISSUE TITLE
Compiler aborts on "this argument has unknown type"

### ISSUE THREAD

**Issue by aconsroe-hpe** [chapel-lang/chapel#19280]
When modifying a program, I had switched something to the effect of renaming `record R` to `record _R` without changing the init methods. This currently aborts in the normalize pass:

```chapel
proc R.init() {}
```

```
chpl test/segfault.chpl
```

```
../chapel2/test/segfault.chpl:6: internal error: PAS-NOR-IZE-4531 chpl version 1.26.0 pre-release (2005de5b22)
```

```
chpl --devel test/segfault.chpl
```

```
test/segfault.chpl:6: internal error: 'this' argument has unknown type [passes/normalize.cpp:4533]
```

Today, that is:

https://github.com/chapel-lang/chapel/blob/275f4fe65997bca8cbdba6079a37ccc7157f5676/compiler/passes/normalize.cpp#L4518-L4538

Reproduced on 1.25.1 and main.

In this case, the `--devel` error message might be suitable to show the user because even though they both contain the file and line number, the `--devel` gives more info. Or maybe its best handled with a check earlier in the pipeline (like "unknown record/class `R`")

**Comment by bradcray** [comment]
@aconsroe-hpe : I've had a tab open to this with the intention of "maybe I should just fix this real quick" since it seems trivial, but didn't want to step on your toes if you're doing/thinking the same thing, so am checking for the lock.

**Comment by aconsroe-hpe** [comment]
Lock is free, I was planning on tackling later (issues week likelye) b/c I didn't have an immediate clear plan
