### ISSUE TITLE
I/O module: deprecate channel.binary?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#19317]
This method is for checking if the channel's style is binary.  The style handling will be replaced by the encoder/decoder strategy.

The IO subteam thinks it is likely this method will be replaced by an equivalent for the encoder/decoder

**Comment by mppf** [comment]
> The IO subteam thinks it is likely this method will be replaced by an equivalent for the encoder/decoder

I'm not quite sure what you mean here. I think the way I'd put it is that the Encoder/Decoder proposal will allow one to create a channel that has a binary Encoder or Decoder and that will allow `read` / `write` calls to work in binary. Outside of that strategy, each I/O call will either indicate (in the documentation) whether it with text or binary data.
