### ISSUE TITLE
should it be possible to define a module that shadows an automatically included symbol?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#19312]
This is a spin-off from https://github.com/chapel-lang/chapel/issues/19167#issuecomment-1046246622

The automatic modules are implicitly `use`d at the start of each module. Should it be possible to create a module that shadows something from these automatic modules?

Here is an example (Note that today, Math is an automatic module and defines `param e`):

``` chapel
module ReplaceE { param e = 10; }
module Program {
  // use AutomaticModules / use Math; is effectively here but implicit
  use ReplaceE;
  e; // should this refer to ReplaceE.e or be ambiguous?
}
```

Another use case would be to have a module that one could `use` to give `+` (or other numeric operators) different behavior in terms of how different types combine. E.g. we could imagine making `operator +(x: numeric, y: numeric)` that gives `compilerError` if the type of `x` differs from the type of `y`.

I think that the main argument that I know of in favor of allowing shadowing here is that we would like to be able to add automatically-included functions and variables without breaking programs.

Here is a story about how that could come up. Suppose we have this:

``` chapel
module AutomaticModules { }
module DefinesFoo { var foo = 10; }
module Program {
  // use AutomaticModules; is effectively here but implicit
  use DefinesFoo;
  foo; // OK, refers to DefinesFoo.foo
}
```

Now suppose that in `StandardLibrary`, we add a `const foo`:

``` chapel
module AutomaticModules { var foo = 20; }
module DefinesFoo { var foo = 10; }
module Program {
  // use AutomaticModules; is effectively here but implicit
  use DefinesFoo;
  foo; // Is this now an ambiguity?
}
```

Do we want the above program to continue to compile? I would suppose so - because I'd think that adding a top-level variable to the automatic modules should be a non-breaking change.

I think another viewpoint on this issue is - suppose everybody were using `import`, what would happen? It would get the user's `foo` and not give an ambiguity error. Here is an example:

``` chapel
module AutomaticModules { ... }
module DefinesFoo { var foo = 10; }
module Program {
  import AutomaticModules;
  import DefinesFoo.foo;
  foo; // always refers to DefinesFoo.foo even if AutomaticModules adds a foo
}
```

So, if we arrange for `foo` to always refer to `DefinesFoo.foo` even in the `use` statement case above, we are making the situation more consistent with what we would regard as the good behavior from `import`.

The counter-arguments to the above are:
 * that an ambiguity error would make it easier to detect problems along these lines more quickly. 
 * that we intend to add less and less automatically included symbols over time
 * that a library could "hijack" code in a program relying on an automatically included module (see https://github.com/chapel-lang/chapel/issues/19312#issuecomment-1054918065 for an example)

I think the main alternative to this strategy is to avoid adding symbols to the set of automatically-included symbols and to consider it a breaking change when we do.

**Comment by bradcray** [comment]
My intuition here is "ambiguity" because if we imagine a use of `DefinesFoo` where the standard module defines bar() as follows:

```chapel
module AutomaticModules { proc bar() { writeln("In bar"); }
module DefinesFoo { var foo = 10; }
module Program {
  // use AutomaticModules; is effectively here but implicit
  use DefinesFoo;
  writeln(foo);
  bar();
}
```

and the author of `DefinesFoo()` is evil and modifies it as follows:

```chapel
module DefinesFoo { var foo = 10;  proc bar() { removeAllYourFiles(); } }
```

haven't we essentially let the library hijack somethig the user's program was relying upon?  Whereas if we make it an ambiguity, the user grumbles at us for introducing new symbols into the automatic modules when we do so (which hopefully happens less and less as time passes), but at least they go into the changes with their eyes open?

**Comment by mppf** [comment]
I think that if the answer is "ambiguity" we would then rely on:
 * #19313

to have a way of opting out of certain symbols.

I think your hijacking scenario is pretty compelling & I'll update the top of the issue to include it.

**Comment by mppf** [comment]
> I think the main alternative to this strategy is to avoid adding symbols to the set of automatically-included symbols and to consider it a breaking change when we do.

Another alternative would be to say that programs and libraries with `use` will sometimes stop compiling even with non-breaking changes to the dependencies; and that relying only on `import` addresses this problem.

**Comment by mppf** [comment]
After PR #19306, I think the answer to "should it be possible to define a module that shadows an automatically included symbol?" is "No, at least not with 'use'". However I left this issue open because I have some uncertainty about that choice.

From PR #19306 :

### Less Shadowing of Symbols from the Automatic Standard Library

This issue discusses whether or not it should be possible to allow shadowing of a symbol from the automatic standard library:
 * #19312 

This issue discusses a specific case of a symbol conflict that comes up when such shadowing is not allowed:
 * #19303 

Another case that comes up in testing not allowing such shadowing is the ChapelEnv -> ChplConfig move now leads to multiply defined symbols. I resolved that in this PR by adjusting scopeResolve to consider `pragma "last resort"`.

This PR does not allow such patterns (since that was easier to implement). I do not expect that allowing such shadowing would present any significant problems. Nonetheless we should decide what we want to do in this area.

This PR does allow shadowing of symbols from the automatic standard library in the following ways:
 * defining the symbol (e.g. `var e: int`) in the module
 * importing something with that name (e.g. `import Constants.e`)
 * `public use` of a module that defines that name (e.g. `public use Constants`)

However, compared to the other choices in this proposal, I am relatively less confident of this one.

Pros/Cons of no longer allowing a `use` to shadow an automatically included symbol:

Pros:
 * language definition is simpler
 * ambiguity error helps to identify the problem if the ambiguity is in fact an issue
 
Cons:
 * modules intended to be `use`d will generally need to avoid naming conflicts with automatically-included modules if they want to be user-friendly
 * harder to argue that we can add symbols to automatically-included modules as a non-breaking change

**Comment by lydia-duncan** [comment]
As a result of the discussion in Cray/chapel-private#5163, I believe the decision is that we will not make changes here and as a result this can be closed.
