### ISSUE TITLE
I/O module: what should be done about the "kind" field on channels?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#19314]
The kind field on channels is used to indicate the default endianness.  It is param today to give the compiler hints that might potentially help with performance, but it's unclear if there are actually any benefits from it.  It is only useful when performing binary IO.

What should we do about this field?  Should we replace it with a binary encoder/decoder?  If we keep it, we should probably give it a better name, maybe "endianness"?  If we keep it, it could be used as the default value for the related argument to readBinary and writeBinary.

**Comment by mppf** [comment]
In terms of performance, the case I worry about is something like `ArrayLikeType.writeThis`  - we would like to be able to compile a single loop that folds in whatever endianness conversion is occurring. *However* I am also expecting that we are going to replace `ArrayLikeType.writeThis` with `ArrayLikeType.encodeTo` and that the `encodeTo` call will be using virtual dispatch. In which case the level of optimization I wanted above is not possible anyway.

So my conclusion is -- if we want to optimize loops doing `encodeTo` calls for arrays (e.g.) then we will need to have some optimization intelligence in the compiler to enable that. As a result relying on a `param endianness` for it does not seem so important.

**Comment by benharsh** [comment]
https://github.com/chapel-lang/chapel/pull/23007 has deprecated the ``kind`` field and ``iokind`` type in favor of serializers and deserializers.

**Comment by bradcray** [comment]
Hooray!
