### ISSUE TITLE
Add support for `foreach` loop expressions

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#19336]
While writing a vectorizeable expression last night, I was surprised to
find that we don't support `foreach` loops at the expression level.
For orthogonality with other for-loop forms, it seems like we should
provide these.

As a motivating example, it seems like it would be nice to be able to write:

```chapel
var sum = + reduce (foreach i in 1..n do (A[i,0] * v[j]);
```

as a way of asserting that the loop is parallel-safe without having to
introduce tasks.

**Comment by bradcray** [comment]
In writing this up, it occurs to me that in order to make my example above
work, we _may_ need to implement task intents on foreach loops as well
(which we want to do anyway—#18500) since I believe we rewrite reductions
using task intents(?).

**Comment by e-kayrakli** [comment]
I added "GPU Support" label as `foreach` is closely associated with GPU and/or vector execution. To me this falls under "let's make GPU features more integrated into the rest of the language" umbrella, which is one of the top-level targets for the near future.

**Comment by bradcray** [comment]
It seems like this may be an easy task as well.  At least, the parsing aspect should be easy, and I'd like to think that whatever we do downstream for `for` and `forall` expressions can be leveraged/mimicked without creating much new content (?).  Could be a useful task for someone on the Dyno team to pick up.

**Comment by e-kayrakli** [comment]
You've already set this in your follow up comment, but the example in the OP may have multiple blockers, only one of which is the lack of support for `foreach` expressions. For anyone working on this issue, the main task is to get the following to work

```chapel
var MyArr = foreach i in 1..5 do i;
writeln(MyArr); // 1 2 3 4 5
```
