### ISSUE TITLE
Should we have: isXType, isXValue, and isX functions for all types or just have one of these for every X?

### ISSUE THREAD

**Issue by stonea** [chapel-lang/chapel#19361]
This is something that came up during the types module review (https://github.com/Cray/chapel-private/issues/3034)

In our types module we have documented "three flavors" of several type\value query functions:

```
  proc isNothingType(type t) param      proc isNothingValue(e) param      proc isNothing(e) param
  proc isBoolType(type t) param         proc isBoolValue(e) param         proc isBool(e) param
  proc isIntType(type t) param          proc isIntValue(e) param          proc isInt(e) param
  proc isUintType(type t) param         proc isUint(e) param              proc isUintValue(e) param
  proc isRealType(type t) param         proc isRealValue(e) param         proc isReal(e) param
  proc isImagType(type t) param         proc isImagValue(e) param         proc isImag(e) param
  proc isComplexType(type t) param      proc isComplexValue(e) param      proc isComplex(e) param
  proc isStringType(type t) param       proc isStringValue(e) param       proc isString(e) param
  proc isBytesType(type t) param        proc isBytesValue(e) param        proc isBytes(e) param
  proc isEnumType(type t) param         proc isEnumValue(e) param         proc isEnum(e) param

  proc isPrimitiveType(type t) param    proc isPrimitiveValue(e) param    proc isPrimitive(e) param
  proc isNumericType(type t) param      proc isNumericValue(e) param      proc isNumeric(e) param
  proc isIntegralType(type t) param     proc isIntegralValue(e) param     proc isIntegral(e) param
  proc isFloatType(type t) param        proc isFloatValue(e) param        proc isFloat(e) param
```

The first set of functions deal with individual types themselves, second set deal with kinds of types (e.g. numeric type can be a uint, an int, a real, etc.).

For other functions we only provide one generic type:

```
  proc isClass(e) param
  proc isRecord(e) param
  proc isUnion(e) param
  proc isTuple(e) param
  proc isRange(e) param
  proc isDomain(e) param
  proc isArray(e) param
  proc isDmap(e) param
  proc isSync(e) param
  proc isSingle(e) param
  proc isAtomic(e) param
```

In practice we also have the other two "flavors" of functions for these queries as well (we just nodoc them).

We also have `proc isVoidType(type t) param`, there is no such thing as a void value so it makes sense that we don't have that function (although maybe it would be better to just have 'isVoid').

Anyway, maybe it would be better if we had more consistency and either had isXType, isXValue, and isX functions for all types or just had one of these queries for all types.

During the types module review meeting people seemed to think this would be a good idea to have consistency but there wasn't agreement on what that consistency should be. We ran a stroll poll asking what people thought, these were the results:

  Should we keep all three "flavors" if functions or just keep one of the flavors:

    Votes: Option:
    * 5    all three
    * 5    isX query only
    * 0    isXType query only
    * 3    isXValue query only

**Comment by bradcray** [comment]
I agree that we should be consistent.  My preference is to keep/expose all three flavors of each because I don't see any significant downside to it and like the ability to be precise when desired `isIntegralType(x.type)` or relaxed when not `isIntegral(someExpr)`.

**Comment by lydia-duncan** [comment]
> The first set of functions deal with individual types themselves, second set deal with kinds of types,

Looks like you missed finishing this sentence, as a heads up

**Comment by lydia-duncan** [comment]
My order of preference is:
1. All Three
2. isX query only
3. isXType query only

I am strongly opposed to keeping only isXValue - it is much easier to go from a value to its type than it is to go from a type to a relevant value, so I think we would find ourselves missing the isXType versions if we went this route.

**Comment by stonea** [comment]
> Looks like you missed finishing this sentence, as a heads up

Looks like I was copy and pasted it from the module review and intended to change that comma to a period but forgot to (in the module review I give a little bit more detail about the different kinds of types but I don't think its needed here). Anyway I updated it, thanks for the heads up.

**Comment by stonea** [comment]
My preference is having all three as well (especially since we have and use undocumented versions of all three anyway).

**Comment by stonea** [comment]
We talked about this in one of the "break out" sessions of the Module Review Meeting on 5/9.  To summarize some of the things the were brought up during the discussion:

- Someone asked about what is value of having separate isType methods when you could just do `x.type == something`:
  - consider `x.type == bool`, there are many different kinds of bools of varying bitwidths, we would want a generic "is this any bool type" function and that would get covered by `isBoolType` and not with `== bool`.

- There was some thought that having these specific query functions could lead to better compile times or be useful things to have for some program analyzers.

- We already have a lot of legacy code that uses these three versions. It doesn't seem worthwhile to update this code and ask users to refactor their code unless there's a very compelling reason to.

- Imagine a tuple that consists of both types and values that we want to pattern match on: having functions that make it easy to do this kind of fine grained checking would be helpful.  This kind of checking may also come up when processing varargs.

- Having more specific query functions makes it more likely that users will be more precise in what they specify gets passed to a generic function with a `when` clause that makes use of these queries.

- The people who were voting for only having `isX()` either didn't feel strongly about it or didn't find their objections to outweigh the cost of refactoring to get rid of the other two versions.

Unless I hear otherwise I'm going to proceed with having all "three flavors" of functions for each type.
