### ISSUE TITLE
I/O module: should channel.flush be available for a reader channel?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#19489]
Today we have this:

``` chapel
proc channel.flush() throws
```

Flushes the channel’s buffered data to the OS when writing. The documentation does not say what it does when reading.

**Proposal:**

Keep it as-is but include an explicit void return type
``` chapel
proc writer.flush() : void throws
```

Furthermore, we will deprecate the ``flush`` method on a ``fileReader``.

**Comment by bradcray** [comment]
> Should flush be available on ‘reader’? What should it do?

In terms of stabilization, I'd be inclined not to support it until someone requests it with a good rationale.

> but include an explicit void return type

Almost tangential to this issue, but given the choice between `proc foo(): void` and `proc foo()` in the documentation, I prefer the latter in terms of being less verbose / cluttered / technical (doesn't require understanding what `void` is).  The argument I can see for putting it is "If we don't say `: void` then the reader won't know whether we just failed to document the return type" but I'd rather document all non-void return types and have lack of a return type imply nothing than make inferred return types be the norm in documentation.  We will also have the lack of a "Returns" section in such documentation which also re-enforces that nothing is returned.

**Comment by mppf** [comment]
@bradcray - regarding the `void` return type, perhaps we could have the documentation tool either:
 1. Warn if the return type is not void but not declared; or
 2. Show the computed return type (for concrete functions, at least) in the generated docs
 3. Show that a return type is computed, for functions without a declared return type, without saying what it is
 
I find 2 a bit worrying in that it would not be possible to do for generic functions. In fact, 1 also has potential problems with generic functions. E.g., you could have a generic function that, for some instantiations, doesn't return (i.e. `void`), and  in other cases, returns something.

3 doesn't have that problem but it might lead to "ewww".

Anyway we should probably create a separate issue for discussing that further. My viewpoint is that we should either add `void` all over the place or add some tooling to check that we aren't creating documentation that is misleading, in terms of return type.

**Comment by bradcray** [comment]
> Warn if the return type is not void but not declared; or

Since I don't want to see `void` in the documentation I'd rather have the tool/linter do the opposite:  Generate warnings for routines in library modules that contain `return` statements but no declared return type.

**Comment by mppf** [comment]
Right that's actually what I meant with that (I was talking about the return type being inferred to be something other than `void` by the resolver - but your rewording makes it a bit more obvious that it can be done by something pre-resolution)

**Comment by bradcray** [comment]
> Right that's actually what I meant with that

Oops, I think I must've missed a "not" in the double negative of point 1.  Let me edit that to seem less oblivious and still put in the "pre-resolution" observation, which also made me happy.

**Comment by benharsh** [comment]
Offline we have decided to deprecate ``flush`` on a ``fileReader``.

**Comment by lydia-duncan** [comment]
This was deprecated when the deprecated channel type was removed
