### ISSUE TITLE
I/O module: return value of write and writeln methods

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#19490]
Today we have these:

``` chapel
proc channel.write(const args ...?k) : bool throws
proc channel.writeln() : bool throws
proc channel.writeln(const args ...?k) : bool throws.
```

Currently, these return ‘bool’ to be symmetric to ‘read’/’readln’. In practice a failure to ‘write’ is probably an erroneous situation; vs with ‘read’ where EOF is a case most patterns need to consider.

**Proposal:**

* Just adjust to return ‘void’ and throw if EOF occurs

``` chapel
proc writer.write(const args ...?k) : void throws
proc writer.writeln() : void throws
proc writer.writeln(const args ...?k) : void throws
```

* Ditto for other writing functions (e.g. ‘writef’, ‘writebits’, ‘writeBinary’, …)

* This includes write/writeln/writef in ChapelIO as well (where currently writef returns bool)

**Comment by bradcray** [comment]
I'm on-board with this if we don't come across compelling examples in the existing code that rely on this.
