### ISSUE TITLE
I/O module: readf adjustments

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#19502]
* Per #19498, want to change some read calls to use out intent
* This will not be possible for readf because arguments can be input to the function for some formats
  * E.g. field width or precision in argument

**Proposal:**
 * ‘readf’ will only work for default-initializeable types
 * ‘readf’ will continue to accept its arguments by ‘ref’ but can allocate class instances and copy

**Comment by lydia-duncan** [comment]
Closing, in the IO subteam meeting today we thought this is handled for the serializers that are written and future ones can make their own decision.
