### ISSUE TITLE
mason test failures

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#19517]
### Summary of Problem

When I run `start_test mason`, I get three failures:

```
[Error matching program output for mason/env/mason-registry]
[Error matching program output for mason/mason-external/libtomlc99/mason-external]
[Error matching program output for mason/mason-external/masonExternalRanges/mason-external-range]
[Summary: #Successes = 88 | #Failures = 3 | #Futures = 0 | #Warnings = 0 ]
[Summary: #Passing Suppressions = 0 | #Passing Futures = 0 ]
```

The first looks like a git thing.  The third is a python-looking error, maybe from spack?  I don't know about the second one.

```
[Executing diff mason-registry.good mason-registry.exec.out.tmp]
7a8,17
> hint: Using 'master' as the name for the initial branch. This default branch name
> hint: is subject to change. To configure the initial branch name to use in all
> hint: of your new repositories, which will suppress this warning, call:
> hint:
> hint:         git config --global init.defaultBranch <name>
> hint:
> hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
> hint: 'development'. The just-created branch can be renamed via this command:
> hint:
> hint:         git branch -m <name>
```

```
[Executing diff mason-external.good mason-external.exec.out.tmp]
2,5c2
< Skipping registry update since no dependency found in manifest file.
< Compiling [debug] target: CToml
< Build Successful
<
---
> Package could not be installed
```

```
[Executing diff mason-external-range.good mason-external-range.exec.out.tmp]
2,5c2,6
< Skipping registry update since no dependency found in manifest file.
< Compiling [debug] target: masonExternalRanges
< Build Successful
<
---
> ==> Error: Failed to install libtomlc99 due to AttributeError: 'NoneType' object has no attribute 'replace'
> ==> Error: 'NoneType' object has no attribute 'replace'
> uncaught MasonError: Package could not be installed
>   $CHPL_HOME/tools/mason//MasonExternal.chpl:606: thrown here
>   mason-external-range.chpl:14: uncaught here
[Error matching program output for mason/mason-external/masonExternalRanges/mason-external-range]
```

### Configuration Information

```
chpl version 1.26.0

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: none
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: none *
CHPL_AUX_FILESYS: none

gcc (Ubuntu 11.2.0-7ubuntu2) 11.2.0

git version 2.32.0

Python 3.9.7

/etc/lsb-release
DISTRIB_ID=Pop
DISTRIB_RELEASE=21.10
DISTRIB_CODENAME=impish
DISTRIB_DESCRIPTION="Pop!_OS 21.10"
```

`test/mason/mason-external/masonExternalRanges/mason_home/spack` ended up with 0.15.4 checked out.

**Comment by cassella** [comment]
This isn't blocking me at all except in tracking down what the `mason-external.prediff` file is doing in `test/mason/mason-external/masonExternalRanges`, since it doesn't match either test name there.  But it's identical to the `mason-external.prediff` file in the sibling dir `libtomlc99`, which does have a matching test.  But the one it's closest to matching in the first dir and the one it matches in the second are two of the tests that fail for me, so I can't tell what's going on with it.

**Comment by arezaii** [comment]
I have been able to reproduce these three failures on `Ubuntu 21.02` with `git 2.32.0`. 

For the `mason-registry` test:

Adding `-q` to the `git init` command in the test allows the test to pass.

edit:
```
test/mason/env/mason-registry.chpl
```

Change line 51:
```chapel
runCommand("git init -q", true);
```

I am still troubleshooting why `spack install libtomlc99` is failing in this environment.
The reported error is:
```
==> Installing libtomlc99
==> Error: Failed to install libtomlc99 due to AttributeError: 'NoneType' object has no attribute 'replace'
==> Error: 'NoneType' object has no attribute 'replace'
```

**Comment by bmcdonald3** [comment]
The root cause of this has recently been identified as a Python versioning issue.

The spack version that we are using is spack 0.15.4 (and we have not updated due to some compatibility issues with the newer version), and this version of spack only supports Python 3.5 - 3.8 (https://spack.readthedocs.io/en/v0.15.4/getting_started.html) and will hit the errors that you are seeing when running with Python 3.9.

**Comment by mppf** [comment]
I just ran into this issue on an Ubuntu 22.04 system (which has Python 3.10).
