### ISSUE TITLE
need better error message when CHPL_TASKS is invalid

### ISSUE THREAD

**Issue by jhh67** [chapel-lang/chapel#19533]
### Summary of Problem
The build doesn't display a helpful error message if `CHPL_TASKS` is invalid. Instead you get this:
```
Makefile.help:58: src/threads//Makefile.include: No such file or directory
make[3]: *** No rule to make target 'src/threads//Makefile.include'.  Stop.
```
It would be nice if it instead told you that `CHPL_TASKS` is set to an invalid value, and preferably list the possibilities.

### Steps to Reproduce

**Source Code:**
```
export CHPL_TASKS=foo
make
```
**Compile command:**
NA
**Execution command:**
NA

**Associated Future Test(s):**
None

### Configuration Information

- Output of `chpl --version`:
```
chpl version 1.26.0
Copyright 2020-2022 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)
```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: hpe-cray-ex
CHPL_TARGET_COMPILER: cray-prgenv-gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: x86-rome
CHPL_LOCALE_MODEL: flat
CHPL_COMM: ofi
  CHPL_LIBFABRIC: system *
CHPL_TASKS: foo *
CHPL_LAUNCHER: slurm-srun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: ofi
CHPL_GMP: bundled
CHPL_HWLOC: none
CHPL_RE2: bundled
CHPL_LLVM: none *
CHPL_AUX_FILESYS: none
```

**Comment by ronawho** [comment]
(Removed post-release since that's meant for PRs)

To me this feels like a dupe of https://github.com/chapel-lang/chapel/issues/19063. 

For both I appreciate the desire for better error messages, but I don't like the idea of having to maintain a list of supported values. I'd prefer just error'ing with something like "CHPL_TASKS=foo is not supported" and not mention legal values.

**Comment by jhh67** [comment]
I forgot about #19063. Maybe just make one issue for all such error messages. Couldn't the list of supported values be determined dynamically?

**Comment by ronawho** [comment]
> Couldn't the list of supported values be determined dynamically?

Oh, yeah that's a good idea -- we should just be able to look at the directory structure to figure out the names.

**Comment by jhh67** [comment]
Closing this, it's duplicative of #19063.
