### ISSUE TITLE
Contribute Chapel to "Attempt This Online (ATO)" (a TIO alternative)

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#19542]
Try it Online (TIO) has been an extremely valuable resource for the Chapel community, but unfortunately has not been maintained, so is now several versions behind Chapel's most recent releases.  I've recently found [Attempt This Online](https://ato.pxeger.com/about), which seeks to play a similar role, and am curious whether we could submit a Chapel option to it without much work.  Instructions for doing so are [here](https://github.com/attempt-this-online/attempt-this-online/blob/main/docs/contributing.md) and seem to take a very Docker-based approach, which may make things fairly easy for us.

**Comment by bradcray** [comment]
On #20731, I asked about the relationship between the AUR packages @ghbrown is making and this effort, given that I saw a mention of Arch there.  Gabriel posted some notes that I wanted to link to here:  https://github.com/chapel-lang/chapel/pull/20731#issuecomment-1261520043

**Comment by bradcray** [comment]
It's been pointed out that [Compiler Explorer](https://github.com/compiler-explorer/compiler-explorer) could be another such place to support Chapel compilations online, though its aim and approach are a bit different (and deeper?) than TIO/ATO, for better or worse.  OTOH, the docs provide instructions for adding a new language, new compiler, etc. so it's not as though it's a non-starter.

**Comment by riftEmber** [comment]
Made the two requisite PRs to get this in:

- https://github.com/attempt-this-online/languages/pull/24
- https://github.com/attempt-this-online/attempt-this-online/pull/102

Will follow them to merge and then test on the live site.

**Comment by riftEmber** [comment]
This work is merged, confirmed by maintainer to work on staging server, and awaits deployment to production on the next ATO release. Considering this done unless I hear back that it is broken or am asked to modify it further.

**Comment by bradcray** [comment]
@riftEmber : Still catching up on mail from the past few weeks and had completely missed that you'd already taken care of this.  Thanks very much!  In your interactions, did you get any sense of when the next release would be?  Checking the past ones (assuming GitHub releases are the right unit), it looks like every ~3 months, which would suggest that we're due for one...

**Comment by riftEmber** [comment]
My sense of when came from extrapolating the ~3 month cadence as well, plus [this comment](https://github.com/attempt-this-online/attempt-this-online/pull/102#issuecomment-1290267894); I think it'll just be when the maintainer has the time to spare for it.

**Comment by bradcray** [comment]
It's so hard to be patient sometimes!  :D
