### ISSUE TITLE
allow changing job name prefix via CHPL_LAUNCHER_NAME_PREFIX

### ISSUE THREAD

**Issue by jhh67** [chapel-lang/chapel#19600]
Chapel launchers currently prefix the job name with `Chpl-` or `CHPL-`. This makes it difficult to distinguish jobs on systems in which everyone shares the same user name.  We should allow the job prefix to be changed via a `CHPL_LAUNCHER_NAME_PREFIX` environment variable.

**Comment by bradcray** [comment]
And/or the job name as a whole?  (i.e., not just the prefix?)

**Comment by gbtitus** [comment]
Yes, similarly I was thinking maybe something like `CHPL_LAUNCHER_JOB_NAME` to just set the whole job name.

**Comment by jhh67** [comment]
The nice thing about the prefix is I can have two different applications I'm switching between, say `foo` and `bar` and I don't have to set the `CHPL_LAUNCHER_JOB_NAME` variable as I switch between them. I do this a lot when comparing the behavior of two different implementations of something. However, I don't see why we can't have both with `CHPL_LAUNCHER_JOB_NAME` taking precedence over `CHPL_LAUNCHER_NAME_PREFIX` (`CHPL_LAUNCHER_JOB_PREFIX` is probably better in that case).
