### ISSUE TITLE
Random's default seed generator naming and implementation

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#19608]
We have decided to provide the default seed generator as a public function in the Random module.

Should it be a standalone function or a type method? We are leaning to a standalone function.

What to name this function? Some ideas:
* getRandomSeed()
* defaultSeed() - con: does not sound like it will vary (which it should)
* Random.seed() - NB [Python's random.seed()](https://docs.python.org/3/library/random.html#random.seed) does something else

For the implementation, we have decided to switch from time-of-day to a hardware or OS source, akin to `/dev/urandom` or Python's [os.urandom](https://docs.python.org/3/library/os.html#os.urandom). This is tracked in #12540.

For now, we are not committing to a particular implementation of this function as part of its public interface/documentation.

**Comment by bradcray** [comment]
I really like just having a single default seed generator that's based on some well-defined practice outside of Chapel, like `/dev/urandom`.

It's not clear to me that we need to expose the name of this routine to a user.  Specifically, I'd think this would be the default seed we'd provide if the user didn't pass one in, such that they wouldn't need to call it explicitly or know its name (?).

**Comment by vasslitvinov** [comment]
> It's not clear to me that we need to expose the name of this routine to a user.

My take-away from the Random module review is that we want the user to be able to invoke it by itself, in addition to its being used as the default in various module functions.

**Comment by bradcray** [comment]
OK.  Though that could also be a non-breaking / post-Chapel 2.0 change if need be.

**Comment by vasslitvinov** [comment]
Removing the Chapel-2.0 label for now.

**Comment by jeremiah-corrado** [comment]
When stabilizing the Random module, we [decided](https://github.com/Cray/chapel-private/issues/5604#issuecomment-1883773167) to remove the public interface for generating a seed. Instead, the `randomStream` type has two initializers, one that accepts a user-provided seed, and another that generates a psuedo-random seed based on a [variety of factors](https://github.com/chapel-lang/chapel/pull/24273).
