### ISSUE TITLE
Random: need parSafe?

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#19607]
We raised this question during the Random module review: do we need `parSafe` at all?

Pro: we want to keep Random in line with whatever solution the standard collections end up with.

Con: it is not obvious that `parSafe` is needed. For example, `fillRandom` and `iterate` ensure internally-concurrent operation safety without locking. If the user needs a parallel random stream, they can do their own locking.

**Comment by mppf** [comment]
My own slight lean is to remove `parSafe` from Random streams.

**Comment by lydia-duncan** [comment]
Random is no longer a candidate for 2.0, removing the tag

**Comment by jeremiah-corrado** [comment]
In stabilizing the random module, we decided to remove the `parSafe` field from `randomStream`. Note that there was discussion of eventually adding something like a global random number generator to the Random module which would need to be parallel safe; however we decided that this feature was necessary for the `randomStream` type.
