### ISSUE TITLE
Random skipToNth, getNth - needed? good names?

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#19606]
Background: today `skipToNth(n)` advances or rewinds the stream to the n-th position; `getNth(n)` combines that atomically with getting the next element.

### Do we want to keep these methods?

`getNth`:
* pro: provides an atomic combination

`skipToNth` and `getNth`:
* con: we want to steer users away from using this often, as it is much slower than `getNext()`

### If we keep these, what are good names for them?

`skipToNth` - rename to one of:
* `advance` ? cons: it can also rewind
* `reposition` ?
* `skipTo` ?

`getNth` - rename to:
* `fetchAdvance` - emphasizes atomicity; should it be 'advanceFetch' ?
* `skipFetch` ?

**Comment by vasslitvinov** [comment]
Idea: Instead of these methods, can we just index into a random stream? Ex. associate a domain with a stream that defines a set of its indices?

Reflection: this would be unsatisfactory because:
* a random stream is conceptually infinite, should not be limited to a domain
* indexing into a stream arbitrarily is much slower than advancing it by 1; we do not want to  encourage users to do arbitrary indexing

**Comment by bradcray** [comment]
Having just spent time reviewing the IO module, I wonder whether we could change skipToNth() to seek() and drop getNth().  (or, more generally, use the same method name as for a channel to advance/rewind our notion of the cursor).

**Comment by lydia-duncan** [comment]
Random is no longer intended for 2.0, removing the tag

**Comment by jeremiah-corrado** [comment]
This was resolved by https://github.com/chapel-lang/chapel/pull/24379
