### ISSUE TITLE
RandomStream class and interface -- what to call them?

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#19601]
We would like PCGRandomStream to be THE random number generator in the standard library. As such, what should it be called? See also #19602

Also, what will we call the random generator interface when interfaces reach production quality? Footnote: if I am writing a library that needs a random generator, however does not care which one to use, it would be generic over the type that implements the interface.

Python: the type name is Random, see https://docs.python.org/3/library/random.html

Rust: has some random number generators and also a trait/interface.  All RNGs implement the RngCore trait, as a consequence of which the Rng extension trait is automatically implemented. Secure RNGs may additionally implement the CryptoRng trait.  Some generators are OsRng, ThreadRng, StdRng, SmallRng.

`Random` or `random` for the class name is acceptable to several core devs.

**Comment by lydia-duncan** [comment]
Random is no longer intended for 2.0, removing the tag

**Comment by jeremiah-corrado** [comment]
In stabilizing the random module, we made `randomStream` (implemented via the PCG algorithm) the only random number generator and deprecated the `RandomStream` base-class / interface. This strategy was intended to leave the possibility of one or more rng interfaces to be added in the future (`randomStream` could be one of multiple types that implement such an interface).
