### ISSUE TITLE
I/O module: channel.advancePastByte and channel.advancePastNewline

### ISSUE THREAD

**Issue by jhh67** [chapel-lang/chapel#19610]
- Should we keep `channel.advancePastByte`?
    - If so, what should its name be and how should it be spelled?
- Should we add `channel.advancePastNewline`?
    - If so, what should its name be and how should it be spelled?
- Currently, `advancePastByte` throws if the byte is not found. Is this the desired behavior for both, or would it be better to either return true/false or perhaps the offset at which the byte was found (negative if it's not found)?

**Comment by mppf** [comment]
#19769 proposes a readUntil that has similar capabilities but reads until that byte and stores it in a string/bytes.

As part of that I think it'd be nice to have consistent naming between the two, but `past` is not working for me with the `readPast` variation. Should these advance functions be called `advanceUntil` (and documented as "until and including"?). Maybe it could be advanceAfterByte and advanceAfterNewline. But `readAfter` doesn't make sense to me either.

**Comment by jeremiah-corrado** [comment]
During a recent ad-hoc design discussion about `readThrough` and `readTo`, summarized here: https://github.com/chapel-lang/chapel/issues/19769#issuecomment-1450914871, we decided to deprecate `advancePastByte` and replace with `advanceThrough`. 

The new `advanceThrough` method will also accept multi-byte separators, but will still use the fast `qio_advance_past_byte` implementation for single-byte separators.

We did not bring the `advancePastNewline` topic into that discussion. (However, for the sake of consistency we may want to consider `advanceThroughNewline` for the name of that method).

**Comment by lydia-duncan** [comment]
I believe this was implemented in #21703, closing

**Comment by jeremiah-corrado** [comment]
The `advancePastNewline` part has not been implemented yet. Should I spawn that off to a separate issue @lydia-duncan?

**Comment by lydia-duncan** [comment]
Oh, yeah, good point.  I think either that or reopening this issue but removing the 2.0 tag would be appropriate (since advancePastNewline is purely additive, right?)
