### ISSUE TITLE
I/O module: channel.seek changes

### ISSUE THREAD

**Issue by jhh67** [chapel-lang/chapel#19612]
Currently, `channel.seek` is used to change the offset at which the next I/O on the channel will occur. Implicitly this changes the start of the file region that the channel can access. Optionally, an `end` parameter can be used to also change the end of the file region. 

Issues:
- Should setting the file region be done via a separate method?
- Should it be possible to query the region associated with a channel?
- `seek` throws if the channel is not seekable. Is this desirable?
- Should it be an error if `start` >= `end`?

**Comment by bradcray** [comment]
Can you say more about what a file region is and how other operations on channels interact with it?

Without knowing the answer, my intuition would be to express a file region using a range, as though you were providing a "slice" of the file, which might also suggest that start >= end should simply be an empty region.

**Comment by mppf** [comment]
Right, a channel has a start and end position, and it begins I/O at the start position and considers it EOF when the end position is reached. In the description above this is called the file region. If we wanted to have a file region be represented as a range in `seek` maybe we would want that as well for the methods creating a channel where you can specify start and end today as separate arguments.

**Comment by bradcray** [comment]
I think ranges are a natural/preferable way to represent start/end conditions.  And unbounded ranges can be a way to say "start here, but I don't have a specified endpoint in mind.

**Comment by mppf** [comment]
Right. I think that a common case is to want to specify the start position but not the end. Then it comes down to preference between:

``` chapel
myreader.seek(17);
myreader.seek(start=17);
myreader.seek(17..);
```

Here I feel it would be odd to always require a range. So we could add an overload that accepted only a number and left the end unbounded. Or, we could require a range, on the argument that it makes it clearer that seek can adjust the end point.

Note that for the methods that create a `reader`/`writer`, the position is always optional, and then the story is slightly different:

``` chapel
var r = myfile.reader(start=17);
var r = myfile.reader(17..);
```

For these I am more comfortable having a range always be required if any start/end is specified at all.

**Comment by lydia-duncan** [comment]
I think using ranges is more Chapel-rific, so definitely think it's appropriate to support an overload that takes ranges.

I'm more unsure about having both that and a version with a separate start and end argument.  I think my position is "well, we already have it, so it would break code to remove it and that seems unnecessary".  I suspect telling people not to use that version is more the job of a linter - it could key off of separate "start" and "end" arguments and suggest to users that they want a range instead

**Comment by lydia-duncan** [comment]
Seek has been changed to only have a region argument.  This was a result of a decision we made in a group meeting to not support both.  Closing
