### ISSUE TITLE
Filesystem module: should methods also take arguments of type file

### ISSUE THREAD

**Issue by jhh67** [chapel-lang/chapel#19659]
Arguments to `Filesystem` methods that represent paths (file names) are currently passed as strings for all methods except for `sameFile` which also take them as type `file`. Should all or some of the other methods do the same, or should this feature of `sameFile` be removed?

**Comment by daviditen** [comment]
Python's `samefile` takes two string path arguments.
Rust's `is_same_file` takes two string path arguments.
Julia's `samefile` doesn't appear to be documented, but can take two string path arguments or two `struct stat` type arguments.


I think we should remove the `sameFile` procedure that takes `file` arguments for consistency with the rest of the `FileSystem` procedures, as well as for consistency with other languages.

If later decide we want these procedures to operate on `file` arguments that can be done post 2.0 in a non-breaking way.

**Comment by lydia-duncan** [comment]
I think it'd be nice to keep both versions, but I won't stand in the way of removing the file version.
