### ISSUE TITLE
Filesystem module: rename getFileSize to getSize

### ISSUE THREAD

**Issue by jhh67** [chapel-lang/chapel#19657]
Not restricted to files.

**Comment by lydia-duncan** [comment]
I would worry that getSize would then accidentally be called with things that aren't referring to files/directories/etc.  But I'm okay with being overruled

**Comment by bradcray** [comment]
I liked the argument that, in the documentation we should understand "file" to be a shorthand for "file" or "link" or "fifo" or ...  If we went that route, I think we could use that same shorthand in routine names like this one.

Case in point: The module is called FileSystem not FileLinkFifoEtcSystem.  :)

**Comment by jhh67** [comment]
I'm going to push back on this a bit. I think if the method name contains "file" then it applies to files specifically, e.g. `isFile`, and `copyFile`. I wouldn't expect `isFile` to return `True` for everything in the file system, nor `copyFile` to make a copy of something other than a file. In this case `getSize` can be used on anything in the file system, although for some things the size may not make sense e.g. a named pipe.

**Comment by mppf** [comment]
@jhh67 - what could you call `getSize` / `getFileSize` on that isn't a file where it would have a meaningful result?

**Comment by jhh67** [comment]
@mppf I think `getSize` should return the size of the object when that is a  meaningful attribute, otherwise it should throw.

**Comment by daviditen** [comment]
In https://github.com/Cray/chapel-private/issues/3924 we agreed that both of these (findFiles and getFileSize) should keep the word File in their names.
