### ISSUE TITLE
Filesystem module: rename findfiles to findFiles

### ISSUE THREAD

**Issue by jhh67** [chapel-lang/chapel#19670]
Fix camel case.

**Comment by bradcray** [comment]
Based on the [other discussion we were having about `Files` literally meaning "files" when used in the name of the routine](https://github.com/chapel-lang/chapel/issues/19657#issuecomment-1103240339), should this be renamed to simply `find`?

**Comment by jhh67** [comment]
Yes, `find` seems consistent with the other discussion.

**Comment by daviditen** [comment]
In https://github.com/Cray/chapel-private/issues/3924 we agreed that both of these (findFiles and getFileSize) should keep the word File in their names.

Closed with.
https://github.com/chapel-lang/chapel/pull/20931
