### ISSUE TITLE
Deprecate SysBasic errno.h symbols in favor of OS.POSIX versions

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#19755]
In reviewing #19703, @mppf pointed out that most of the error aliases in SysBasic are now implemented in OS.POSIX, suggesting that they could be deprecated in favor of the POSIX module symbols.  Since not much will remain in SysBasic after they're removed, it probably makes sense to deprecate the module as a whole as long as the other contents are also available elsewhere, or can be made to be.

**Comment by lydia-duncan** [comment]
Is this done?  It looks like there's a fair number of deprecation warnings in SysBasic for symbols that now live in OS.POSIX

**Comment by bradcray** [comment]
Mmmmaybe.  There are still the error aliases that are non-POSIX, but provided by Linux or other *nix flavors.  That said, I don't feel as though keeping this issue open is likely to add to our incentive to (re)move them, so it would be fine with me to close it.

**Comment by lydia-duncan** [comment]
I think I'll close it for now and open specific issues for the remaining categories of error aliases
