### ISSUE TITLE
Should our `./configure` create the directory if it doesn't exist?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#19762]
A user trying to install Chapel using the `./configure` script got an error in which the build complained if the directory did not already exist.  Should we be creating it for them, or just being more tolerant of it not existing in some way?  Would this be more consistent with `autoconf`-based `./configure` behavior?

**Comment by brandonneth** [comment]
Just did a configure and install for integer set library (first autoconf using tool I could think of) and it created the prefix directory for me.

**Comment by bradcray** [comment]
Thanks for confirming!  Are you interested in picking up the task to make our `./configure` create the directory similarly?  I think (a) it should be pretty easy and that (b) we don't have a most-logical owner of that script to ask to tackle this (it was written rapidly be @mppf and @ben-albrecht years ago I think, but has barely been touched since, I think (?)).  So I'm guessing anyone looking at it afresh would be as capable of tackling this as anyone.

**Comment by mppf** [comment]
FWIW I would expect it to amount to making adjustments to this code:

https://github.com/chapel-lang/chapel/blob/90966bb3479d12d2a505c6f476106e707a54f88d/util/buildRelease/install.sh#L39-L49

**Comment by brandon-neth** [comment]
Shouldn't the change be in configure? I was thinking that we should create the directory after normalizing the prefix path, here-ish: https://github.com/chapel-lang/chapel/blob/4a33db858ef856d3633953a313d0cb82edde7aa3/configure#L94

**Comment by brandon-neth** [comment]
When I run paratests after using configure to set the prefix, the tests for `chpl --print-chpl-home` fail because the prefix directory is included in the output. Those tests are here: https://github.com/chapel-lang/chapel/blob/main/test/compflags/ferguson/home/sub_test

I figured out that it has to do with the `configured-prefix` file thats created by running `./configure`. When that file is deleted and I call `make` again, the tests pass. 

It shouldn't be too hard to fix those tests to ignore the line with the prefix, I'll try to get that finished before the end of the day today.

**Comment by bradcray** [comment]
I may not have seen this fast enough, but...  I don't think there's any current assumption that paratest will be error free when using an installed version of chpl.  And I don't think you necessarily need to make it the case that they do.  So I wouldn't let that hold up this PR if you'd like to move on rather than clean house behind others.  At the same time, if the fix is easy and makes life better for others going forward, that's a noble action and follows the "leave your campsite better than you found it" rule.  Just wanted to make sure you knew that I'd call it above and beyond the call rather than something that's necessarily on you to fix.

**Comment by bradcray** [comment]
@brandon-neth : I think this is complete now, right?  It looks like GitHub doesn't auto-close issues linked with the term "Completes", though it does for "Resolves" (and a few other words that I'm not remembering offhand).

**Comment by brandon-neth** [comment]
It is! I'll make sure to say Resolve instead
