### ISSUE TITLE
I/O module: readline vs readLine

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#19768]
This is a spin-off from #19495.

Discussion on #19495 is heading towards keeping something called readline to read a line into a string/bytes/array (and removing readln). However one choice that is pretty separable is whether to spell the name of that routine `readline` or `readLine`

In favor of `readline`
 * it is the name in Python

In favor of `readLine`
 * it better matches our camelCase convention since `read` and `line` are different words

**Comment by bradcray** [comment]
I don't find either option offensive, but would probably go with `readLine` for consistency with other `read*` routines we're discussing as being supported (e.g., `readAll`, `readBinary`, `readUntil`, ...).

**Comment by bradcray** [comment]
I think this was resolved through conversation and implemented in #19937.
