### ISSUE TITLE
Support `-g` with GPU support

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#19774]
**This is moved from https://github.com/Cray/chapel-private/issues/2718.** 

These are all my notes trying to get debugging support right:

---

Currently we can't compile with `-g` because LLVM generates DWARF lines that are not compatible with `ptxas` until version 7.5.  The incompatible lines cause syntax errors while running `ptxas`. As a long shot, I tried to change the dwarf language we use from C99 to C89 to see if it helps, but it doesn't.

See "PTX ISA Notes" [in section 11.5.2 of PTX ISA reference](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#debugging-directives-section), we need both `label1-label2` syntax and negative numbers to be able to compile with `-g`.

---

#### Notes about tools:

- `cuda-memcheck` is deprecated and `compute-sanitizer` is the replacement for it.
- We need `--report-api-errors no` to suppress warnings from failed API calls. There are some that are supposed to fail and we handle their errors in the runtime.
- `cuda-gdb` can use the `memcheck` tool with `set cuda memcheck on`. You need to also do `set cuda api_failures hide` for the same reason as above.
- We can improve these and turn them into an individual note once we have a better story for debugging.

---

Hmm looks like PTX supports DWARF2: https://docs.nvidia.com/cuda/ptx-writers-guide-to-interoperability/index.html#generation-of-debug and https://lists.llvm.org/pipermail/llvm-dev/2017-November/118859.html

The default DWARF for LLVM is 4. I wonder if we can drop that.

---

I think the statement that the debug info are standard DWARF2 is a bit misleading. Because going back to the link in the OP, it clearly says that negative numbers are supported in PTX 7.5. 

And my initial attempt to fall back to C89 was right, because apparently C89 uses DWARF2. [Here is the DWARF version](https://github.com/chapel-lang/chapel/blob/main/third-party/llvm/llvm-src/include/llvm/BinaryFormat/Dwarf.def#L675). But it doesn't help.

**Comment by stonea** [comment]
Would it be possible to limit this to just the non-kernel parts of the code (so that what gets passed to `ptxas` doesn't have those DWARF lines)?  I guess we wouldn't be able to use the debugger in the kernel then but it's better than nothing?

**Comment by e-kayrakli** [comment]
At a high-level, that sounds useful and probably easy short-term solution. I don't have any off-hand pointers as to how one would implement that though.

**Comment by stonea** [comment]
Wouldn't it just a matter of turning off whatever setting tells LLVM to insert debugging information when we do our fork and call `codegenPartTwo` with `gCodegenGPU == true`?  I assume this information is getting added when we call out to `clang` right?  So just don't pass `-g` if `gCodegenGPU == true`.

Maybe I'm missing something. Well I can give it a try.

**Comment by e-kayrakli** [comment]
This should be about the IR/PTX LLVM emits, and not clang, right? We don't really run clang beyond linking for GPU part of the story.

**Comment by stonea** [comment]
> This should be about the IR/PTX LLVM emits, and not clang, right? We don't really run clang beyond linking for GPU part of the story.

I see. On a superficial glance it looks like we're doing the emission somewhere here:

https://github.com/chapel-lang/chapel/blob/815c267fdd4d0bca7d0c30bf3cf9c4e68d633842/compiler/codegen/codegen.cpp#L2569

But I'd have to dig in a little bit more to be sure.

**Comment by bradcray** [comment]
This question seems like something that the dyno team or @daviditen might have more information about if it would be helpful (I wouldn't be surprised if none of them were subscribed here, but won't tag all of them in case you've already reached out).

**Comment by stonea** [comment]
@DanilaFe and @e-kayrakli, is this issue still relevant?

It looks like since https://github.com/chapel-lang/chapel/pull/21480 we've been able to run GPU support with `-g` and get meaningful information in Nsight. Does that mean this is supported now or is there something else that's missing?

**Comment by e-kayrakli** [comment]
Yeah, let's close this. `-g`. For posterity, proper profiling (not debugging) and line numbers requires `--gpu-ptxas-enforce-optimization` which is a very patchy flag. We need to overhaul `-g` for llvm to get rid of that, but that's different than what this issue asks.
