### ISSUE TITLE
What should import do when a submodule made visible has the same name as a top-level module?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#19782]
### Summary of Problem
Today, the submodule will take precedent over the top-level module, because we find it by traversing use statements in the closer scope.  However, import does not go up scopes beyond a module boundary and automatically can find any top-level module.  Does this mean it should consider top-level modules as conflicting with modules brought in by use and import?  Or should it only wait to go looking for top-level modules until it has exhausted the use and import statements from the scopes it is allowed to look in (as it does today)?

### Steps to Reproduce

**Source Code:**

```chapel
module ExternalLib1 {
  module Details {}
}

// My library's implementation details.
module Details {
  proc do_my_impl() { writeln("whatev"); }
}

module SomeOtherFile {
  proc main() {
    {
      use ExternalLib1;
      import Details;       // Should this find the public module?
      Details.do_my_impl(); // currently: compile-error
    }
    {
      import ExternalLib1;
      import Details;       // Resolves fine
      Details.do_my_impl();
    }
  }
}
```

**Compile command:**
`chpl foo.chpl`

**Execution command:**
N/A

**Associated Future Test(s):**
[`test/visibility/import/submoduleCloser.chpl`](https://github.com/chapel-lang/chapel/blob/main/test/visibility/import/submoduleCloser.chpl) #TBD

### Configuration Information

- Output of `chpl --version`: chpl 1.27.0 (pre-release)
- Output of `$CHPL_HOME/util/printchplenv --anonymize`: N/A
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: N/A
- (For Cray systems only) Output of `module list`: N/A

**Comment by mppf** [comment]
Right, I can see these possible behaviors:
 * import prefers something brought in by earlier use/import, if available
 * import prefers top-level modules, if they exist
 * ambiguity

One interesting element here is that we actually don't know if a top level module exists until we try to read a file with the matching name from the module path. Another way to put that is - if we used "prefer top-level", then we would potentially have a scenario where `use Something; import SomethingElse` is working but then if somebody adds an unrelated `SomethingElse.chpl` in a directory in the module path, it would stop working. Arguably, even adding an ambiguity error in that case would be surprising.

So that leads me towards thinking that we should keep the current behavior.

**Comment by lydia-duncan** [comment]
I could also see treating module-scope use/import statements as conflicting with top level module names, but not causing conflicts for inner scope use/import statements (but that's probably too tricky to think about/implement)

**Comment by bradcray** [comment]
> if we used "prefer top-level", then we would potentially have a scenario where use Something; import SomethingElse is working but then if somebody adds an unrelated SomethingElse.chpl in a directory in the module path, it would stop working. Arguably, even adding an ambiguity error in that case would be surprising.

I'm not seeing why the opposite is not equally true:  That I have a `SomethingElse.chpl` on my module search path, and then some other module that I'm `use`-ing inserts a submodule: `module Something Else` and my code starts referring to it instead.  Is that correct?  If so, it seems like, in both cases, it's a case of "Don't use `use` if you're worried about surprises" which makes me think maybe an ambiguity is the better choice, to at least point out the potential for surprise.

Another potential option: In some cases (module searches in which we find multiple files with the name), we have an "I see an ambiguity, but am choosing this one" warning—would there be a benefit to taking that approach here?

**Comment by mppf** [comment]
PR #23511 adds a warning for this case. Is that sufficient to close this issue?

**Comment by lydia-duncan** [comment]
Seems reasonable to me, but I'd update the test listed when doing so
