### ISSUE TITLE
Add support for free-standing fillRandom() with bounds

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#19790]
PR #19540 added support for fillRandom() that takes bounds, but only as
a method on a random stream, not as a standalone routine.  For consistency
with other random routines, it seems as though we ought to support a
standalone version as well.

**Comment by brandonneth** [comment]
Random streams:
- PCGRandomStream
- NPBRandomStream

NPB doesn't have a bounded fillRandom implementation, likely because its already bounded to (0,1), so the only option for the stream to use in the standalone function is the PCGRandomStream.

This suggests to me that this function doesn't need the `param algorithm=RNG.PCG`, because that's the only option. 

`seed` has a default, so it should go at the end, so we have:

```
proc fillRandom(arr: [], min: arr.eltType, max:arr.eltType, seed: int(64) = SeedGenerator.oddCurrentTime)
```

Body will use the same pattern as the regular fillRandom, but with the min and max arguments as well.

For testing, I'm going to add to the existing fill random test.

**Comment by bradcray** [comment]
@brandonneth : Thanks for taking a look at this! 

For a bit of context not obvious in this issue: We're in the process of removing NPBRandomStream from the Random module and just focusing on PCG (among some other restructurings), so focusing solely on PCG makes complete sense here for multiple reasons I think.

Your approach generally sounds good to me.

Also, not to suggest your decision to put seed at the end is wrong (it's what I'd do), but in case there's any misunderstanding, note that Chapel doesn't require arguments with defaults to be at the end of the argument list (as C++ does, or used to at least?).  Though that is certainly the most common case for the obvious reasons.

**Comment by brandonneth** [comment]
Awesome, good to know! 

Re defaults, how does chapel resolve the following?
```
proc foo(arg1: int(32) = 1, arg2: int(32) = 2) {...}
foo(3);
```

Does it use 3 for arg1 and leave arg2 to its default?

**Comment by bradcray** [comment]
It does.  But you could also call it as `foo(arg2=3)` and get the opposite behavior or `foo(arg2=3, 4)` which would pass the 4 to `arg1` (keyword-based arguments are matched first, and then the remainder are matched positionally.

So you could also define foo as:

```chapel
proc foo(arg1: int(32) = 1, arg2: int(32)) { ... }
```

which would require calling as `foo(arg2=3)` to get the default for arg1 (and `arg2` would need to be supplied in any case).

Not claiming these are best practices by any means, but good to understand how things work...

**Comment by brandonneth** [comment]
Definitely! Okay, last question before I open a pull request. In the documentation for the function, I'm trying to say "using a new PCGRandomStream created specifically for this call" and have it render the PCGRandomStream as a reference to the definition. 

My raw text in the documentation is:

```
in parallel using a new :class:`PCGRandomStream` created 
specifically for this call. 
```

which mimics the raw text for the original fillRandom:

```
a new stream implementing :class:`RandomStreamInterface` created specifically for this call
```

However, when I generate the docs, the RandomStreamInterface renders as a link, but the PCGRandomStream doesn't. My hypothesis is that its bc PCGRandomStream is documented on another page, but I'm not sure. 

Is it possible to render it as a link like the other references to classes?

**Comment by bradcray** [comment]
> However, when I generate the docs, the RandomStreamInterface renders as a link, but the PCGRandomStream doesn't. My hypothesis is that its bc PCGRandomStream is documented on another page, but I'm not sure.
> 
> Is it possible to render it as a link like the other references to classes?

Hmm...  I don't do chpldoc-umentation often enough to be really good at debugging when things don't go as I'd expect (where here, my guess was that your link would work.  Specifically, I thought that cross-module / page links worked out just fine, but maybe I'm misremembering.

What I usually do in cases like this are (a) look at the generated .rst files to see whether the tags I'm expecting to link to are there (after a `make docs` step, these should appear in `doc/rst/modules/standard/*.rst` for this module, (b) re-read the [chpldocs docs](https://chapel-lang.org/docs/tools/chpldoc/chpldoc.html) to see what I might be forgetting, (c) ask someone who's better at chpldoc than me (where @lydia-duncan ) is a frequent target.

**Comment by lydia-duncan** [comment]
Yeah, I think you need to list the module where the class lives if it's different than where you are currently (since `PCGRandomStream` lives in the `PCGRandom` module, you'll need to write `PCGRandom.PCGRandomStream` or `~PCGRandom.PCGRandomStream` if you want to hide the module path in the link text and just display `PCGRandomStream`).

**Comment by bradcray** [comment]
That sounds familiar.  I think vanilla sphinx/rst tags are more global, but that something about the path that chpldoc takes to enable these semantic tags is more particular, and that I can't keep them straight (and work more with the vanilla sphinx/rst docs than chpldoc, so internalize the global nature of its labels (?)).

**Comment by bradcray** [comment]
Thanks for taking care of this, Brandon!
