### ISSUE TITLE
I/O module: allow channel.mark() to be called with locking channels

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#19827]
Today, channel.mark() requires the channel is created with `locking==false`.  This doesn't seem entirely necessary, it's probably sufficient to document what would happen.

**Comment by mppf** [comment]
There are a bunch of other methods with the same constraint.

It might be necessary to relax this when we remove the `_mark` etc methods because otherwise one would have to create a no-locking version of the same channel (which is possible but not that easy today).
