### ISSUE TITLE
I/O module: skipField method

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#19832]
We have this method
``` chapel
proc channel.skipField() throws
```

documented here -- https://chapel-lang.org/docs/modules/standard/IO/FormattedIO.html#FormattedIO.channel.skipField

With the Encoders/Decoders design in #18499, the Decoder has the ability to read fields out of order, but I'm not sure how a skipField method would help, so probably we should remove it from the channel. If it is needed, it should probably be added as a method on the particular Decoder (e.g. JsonDecoder) that accepts the reader channel as an argument.

**Comment by lydia-duncan** [comment]
Resolved by Ben's #23001, closing
