### ISSUE TITLE
Design for querying range low / high bounds in aligned and unaligned ways, including transition

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#19836]
[This is an expansion on #17130 ]

Context
======

Given a strided range like `1..10 by 2`, we can think of it as having two notions of a "high bound":

* "pure": '10' because that's given as the literal upper bound of the range
* "practical": '9' because the range only represents odd elements, so 9 is the last value represented

The dual issue can occur with low bounds for ranges with negative strides like `1..10 by -2`.  Strided rectangular domains also share this issue where the bounds are represented by tuples for arrays > 1D.  Note that unit-stride ranges and domains don't have this issue because the two bounds are one and the same.

Today, the `.low` and `.high` queries represent the "pure" bounds, while `.alignedLow` and `.alignedHigh` represent the practical ones.

Motivation for Change
================

In practice, what we've found is that code is often written using `.low` and `.high` for convenience and only focuses on / tests using unit-stride ranges.  Then, if the code is sufficiently generic and strided ranges are passed in later, things start to break.  As a simple example, consider the expression `A[A.domain.high]`.  By contrast, user code rarely seems as interested in the pure bounds, which seem to be used primarily when defining operators on ranges that create new ranges.

The Proposed Change
================

For this reason, we've discussed changing things so that:

* `.low`, `.high` would return the practical bounds
* `.lowBound`, `.highBound` would return the pure bounds
* `.alignedLow`, `.alignedHigh` will eventually be removed

Generally, this proposal has been positively reviewed so far, though there is still time to disagree with it.

How to Make the Change
==================

Assuming we proceed, a second challenge is how to make the transition given that the definition of `.low` and `.high` will be changing.  Here's the approach I'm proposing:

In this release:

* Implement `.lowBound` and `.highBound` which don't exist today
* Rewrite all module code that we own to use either `.lowBound`/`.highBound` or `.alignedLow`/`.alignedHigh`
* Have `.low` and `.high` warn by default for strided ranges, making the user aware of the forthcoming change, yet still give the traditional behavior to avoid breaking code
* Support a `config param` that lets a user opt into the new behavior today and makes the warning go away

In the next release:

* Remove the warning from `.low` and `.high`, changing them to return the practical bounds
* Rewrite module code that calls `.alignedLow`/`.alignedHigh` to use `.low`/`.high` instead
* Deprecate `.alignedLow`, `.alignedHigh`

And then in the following release:

* Remove `.alignedLow`, `.alignedHigh`

Fine-grain Details
=============

In even more detail, in my current work:

* the name of the config that opts into the new behavior is `alignedBoundsByDefault`
* the warnings are:

```
The '.low' query on ranges is in the process of changing from returning the pure low bound to the aligned low bound (e.g., from '1' to '2' for '1..10 by -2').  Update to the '.lowBound' query if you want to retain the old behavior, or recompile with '-salignedBoundsByDefault=true' to opt into the new behavior.
```

and

```
The '.high' query on ranges is in the process of changing from returning the pure high bound to the aligned high bound (e.g., from '10' to '9' for '1..10 by 2').  Update to the '.highBound' query if you want to retain the old behavior, or recompile with '-salignedBoundsByDefault=true' to opt into the new behavior now and avoid this warning.
```

**Comment by benharsh** [comment]
The general design and strategy here looks good to me.

Should ``range.first`` and ``range.last`` be part of this discussion? Personally, I tend to use those over any methods with the words "low" or "high" in them, largely due to the verbosity of "aligned*" and the sometimes-unhelpful result of the 'pure bounds' methods. Should they perhaps be deprecated as well?

Ranges are mentioned most here, but will this change also apply to the domain type? Domains also support ``first`` and ``last``, fwiw.

**Comment by bradcray** [comment]
I think first and last have a different and useful-to-important role for ranges (and think that's where the consensus was when we last reviewed ranges as well)—i.e., for `1..9 by 2` vs. `1..9 by -2`, `low` and `high` are always 1 and 9 respectively, but first and last will swap from 1 and 9 depending whether the stride is positive or negative.

And yeah, the intention is that the changes in the OP would be applied to ranges and rectangular domains simultaneously.

Meanwhile, for dense multidimensional domains, I can't recall what our last discussion of first and last was...  They're still well-defined and different from low/high, but also seem less useful / valuable somehow in the multidmensional setting?  But I'm not sure I'd throw them out over that due to orthogonality...    https://github.com/chapel-lang/chapel/issues/17327 proposes getting rid of them for sparse domains, which I'm in favor of, and I don't think we support them on associative (or should if we do).
