### ISSUE TITLE
Arrays of `sortedSet`s don't compile

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#19872]
This is an extension of https://github.com/chapel-lang/chapel/issues/18664 and https://github.com/chapel-lang/chapel/issues/18665.

The following code doesn't compile, because `sortedSet` has an explicitly generic field. (I am not sure what the right term is, but the field in question is `var instance: treap(eltType, parSafe, ?). Background on why that's what that field looks like is: https://github.com/chapel-lang/chapel/issues/18656 where the solution was https://github.com/chapel-lang/chapel/pull/18661.

```chapel
use SortedSet;

var a: [1..10] sortedSet(int);

/* this doesn't work either

use Treap;
var a: [1..10] sortedSet(int, false, treap(int, false, defaultComparator.type));

*/

writeln(a);
```

The error message is:

```
$CHPL_HOME/modules/internal/ChapelArray.chpl:263: In function 'chpl__buildArrayRuntimeType':
$CHPL_HOME/modules/internal/ChapelArray.chpl:264: warning: creating an array with element type sortedSet(int(64),false)
$CHPL_HOME/modules/internal/ChapelArray.chpl:264: error: array element type cannot currently be generic
  $CHPL_HOME/replSortedSet.chpl:3: called as chpl__buildArrayRuntimeType(dom: domain(1,int(64),false), type eltType = sortedSet(int(64),false))
note: generic instantiations are underlined in the above callstack
```

AFAIK, this is an issue for porting CHAMPS to 1.26.

**Comment by bradcray** [comment]
It's hard for me to link this to any changes we've made recently, but presumably this worked in... what...  1.25.1?

**Comment by e-kayrakli** [comment]
My guess is that I broke it with https://github.com/chapel-lang/chapel/pull/18661. I even vaguely remember discussing this case with array initialization, but can't find any written record of it on a quick look.

**Comment by e-kayrakli** [comment]
Apparently I had sent the CHAMPS team a patch that fixed the issue in the past. It still seems to be working:


```diff
diff --git a/modules/packages/SortedSet.chpl b/modules/packages/SortedSet.chpl
index e2f3b8e6a4..252a7e2aac 100644
--- a/modules/packages/SortedSet.chpl
+++ b/modules/packages/SortedSet.chpl
@@ -50,9 +50,11 @@ module SortedSet {
     /* If `true`, this sortedSet will perform parallel safe operations. */
     param parSafe = false;
 
+    var comparator = defaultComparator;
+
     /* The underlying implementation */
     pragma "no doc"
-    var instance: treap(eltType, parSafe, ?);
+    var instance: treap(eltType, parSafe, comparator.type);
 
     /*
       Initializes an empty sortedSet containing elements of the given type.
```

We should run some testing with that patch, and merge if it doesn't break anything.

**Comment by e-kayrakli** [comment]
The patch above breaks the test https://github.com/chapel-lang/chapel/blob/main/test/library/packages/SortedSet/partialGenericFieldWorkaround.chpl

**Comment by bradcray** [comment]
How bad is the breakage, and do you have any clarity what would be required for the fix?

**Comment by e-kayrakli** [comment]
Not really. Poking around type definitions, I couldn't come up with an easy one. I was hoping to address this before the release with some help from Michael, but I couldn't get to it with other CHAMPS-related priorities.

**Comment by e-kayrakli** [comment]
https://github.com/chapel-lang/chapel/pull/20158 will fix the issue. It looks like the underlying compiler issue has been fixed in the dyno resolver already: https://github.com/chapel-lang/chapel/issues/18664#issuecomment-1171618053
