### ISSUE TITLE
Should we change the default CHPL_LIB_PIC setting?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#19898]
Today, the default setting for `CHPL_LIB_PIC` is `none`. However, I've noticed (when investigating problems with LLVM 14 on Ubuntu 22.04 and problems on Arch linux) that some systems default to position-independent code, even for executables. On those systems `gcc` or `clang` from a system package will generate position-independent code by default, even if `-fPIC` is not provided. As a result, on those systems, when Chapel is built with `CHPL_LIB_PIC=none`, it will produced position-independent code (and, if it does not, there will be linker errors, which I think are due to the fact that the libraries linked are position independent and can't be compiled otherwise).

Given that, on some systems, `CHPL_LIB_PIC=none` produces position independent code, should we change the name of the default setting `none`? Or do something else to make it less confusing?

See also:
 * #19894
 * #19785

**Comment by lydia-duncan** [comment]
Maybe `default` would be a better name for it?

There's a part of me that thinks we should also add a setting for explicitly turning position independent code off, but I also suspect that actually using that setting would lead to problems so it doesn't seem like it provides value other than the illusion of completeness.

**Comment by bradcray** [comment]
I like this idea.  We could follow the approach with `CHPL_LLVM` of having it default to `unset`, though I'd be good with Lydia's choice of `default` (or `system`) as well.

I was imagining we'd have "on", "off" and "whatever the system default is" settings (which feels similar to what we do w.r.t. --static vs. --dynamic vs. whatever your compiler's default is).  But Lydia's response makes me think I'm missing something.  Is there no `-fno-PIC` style setting?  (with a quick google search, I'm seeing `--no-pie`, but am not quickly groking how pie and pic relate to one another on a Friday afternoon).

**Comment by mppf** [comment]
In a quick experiment, this command compiles something on a system that is pic/pie by default: `clang -fno-PIC -fno-pie test.c -Wl,-no-pie`. I'm not sure why a separate argument for the linker is necessary, nor am I sure if both `-fno-PIC` and `-fno-pie` have an impact. So I think it might be possible to generate position dependent code but I don't understand why one would want to do that on a system that defaults to pic/pie.

FWIW pie is "position independent executable".

**Comment by bradcray** [comment]
> but I don't understand why one would want to do that on a system that defaults to pic/pie.

I thought that it could be seen to result in a performance boost in some cases?

**Comment by mppf** [comment]
For one thing though, if the default ends up being position-independent code on some common platforms, then even if we end up with weird errors from `CHPL_LIB_PIC=static` (or whatever) then presumably those would be easier to ascribe to changing that setting?

**Comment by lydia-duncan** [comment]
Easier, sure, but I think it's still pretty easy to forget that you set that environment variable if it didn't cause problems immediately.  I'd like us to be better about detecting when it would cause problems and giving a good warning in that case instead of the errors we get today, but I strongly suspect that's difficult to do

**Comment by mppf** [comment]
A hypothesis of mine is that the errors we have been seeing come about when the compiler/linker use a --enable-pie flag of one sort or another (possibly from flags determined by how clang was built). That's presumably something we could detect and warn about. But actually doing it successfully is another matter.

**Comment by marshallward** [comment]
Hi, I was prompted by @bradcray to comment here, since I also had this issue on my Arch machine.

I was looking at ways to detect whether gcc was built with PIE enabled, and it looks somewhat platform-dependent problem, but the following does work for me:
```
$ cat main.c
int main(){};

$ gcc -pie main.c && file a.out
a.out: ELF 64-bit LSB shared object, x86-64, ...

$ gcc -no-pie main.c && file a.out
a.out: ELF 64-bit LSB executable, x86-64, ...
```
If you want to get lower level, you can inspect byte 0x10; 3 is shared library and 4 is executable (assuming ELF format).  There are also similar methods looking at `FLAGS` or `FLAGS_1`.  (I guess all of this could be done with `readelf` if it's available.)

Another more explicit test was recommended here:

https://stackoverflow.com/a/51308031/317172

but it requires running the program through GDB and inspecting the program counter over multiple runs, which might be a bit overkill.  (There is also a step requiring root, but that is for ASLR and can probably be skipped.)

**Comment by mppf** [comment]
In working on PR #22339 I've come to understand that there are some differences between `-fPIC` and `-fPIE`. As far as I understand, systems aren't defaulting to `-fPIC` but they are defaulting to `-fPIE` (to enable ASLR). `-fPIC` has additional implications, beyond making the code relocatable, in the form of indirect calls & tables. Also, in some ways, LLVM 15 makes the situation easier to understand, because it defaults to `-fPIE` on all linux platforms.

Anyway, given all of that, I think that it might be smart to adjust the documentation to be slightly more nuanced:

(from https://chapel-lang.org/docs/usingchapel/chplenv.html#chpl-lib-pic if you want to see it in context)

```
pic   build position independent code
none  use the system default, which might be
      position independent or position dependent
```

->

```
pic   build position-independent code suitable for a shared library
none  use the system default, which might not be position-independent, or might be position-independent but not suitable for a shared library
```

But perhaps that's just making it too complicated.

**Comment by lydia-duncan** [comment]
Hmm, that feels a little like it's intended as a complete list (but isn't, so far as I understand).  What about:
```
pic   build position-independent code suitable for a shared library
none  use the system default, which might be
      position-independent or position-dependent, or even
      position-independent but not suitable for a shared library
```
?
(I'm not sure if the hyphen use is appropriate or not and didn't go looking)

**Comment by mppf** [comment]
AFAIK systems aren't defaulting to `-fPIC` just `-fPIE` which means that AFAIK no system has the default of "position independent and suitable for a shared library" which is what that change adds (arguably).

**Comment by mppf** [comment]
Since #22555 updated the documentation to better describe that CHPL_LIB_PIC is about position-independent code for dynamic libraries (vs position-independent executables), I'm closing this issue.
