### ISSUE TITLE
Should `sourceVersion` continue to prepend `version ` when cast to string?

### ISSUE THREAD

**Issue by arezaii** [chapel-lang/chapel#19928]
In the process of trying to add a non-param type that supports reasoning about program versions at runtime (https://github.com/chapel-lang/chapel/issues/19201), I have proposed removing the `version ` that gets prepended to the output when casting an object of this type to a string. 

For example, a `sourceVersion` of `1.2.3` will print `version 1.2.3` when cast to a string.

The rationale for removing this are:

1. Including it forces the user to remove `version ` and replace it with something else rather than append it only when needed. For example, if my program needed to output its version information like `v1.2.3` instead, I'd have to do the cast and then do a replacement.
e.g.,
```chapel
// if we leave version in the output
writeln((v1_2_3:string).replace("version ","v"));
// instead of 
writeln("v" + v1_2_3:string);
```
2. I am not sure what precedence there is for including additional information when casting simple types to string. Do we have other simple types that also do this? Is `sourceVersion` special enough to warrant always adding text information to the casted output?

**Comment by arezaii** [comment]
During our module re-review on 8/4/2022 our break-out-group agreed that `version ` should not be part of the output when casting a `sourceVersion` to string. 

Unless someone voices opposition to removing it, we will drop it from the output in a future PR. 

I'm not sure if it needs to be deprecated or marked for change, or if we can just remove it note the change in the docs/changes.md

**Comment by bradcray** [comment]
> I'm not sure if it needs to be deprecated or marked for change, or if we can just remove it note the change in the docs/changes.md

I don't think any special care in changing the behavior is required.  It could catch some users/use cases by surprise, but I don't think the effort to try and change the behavior more gradually is worth it because I expect the number of such cases to be near-zero.

**Comment by arezaii** [comment]
I put up a PR to make this change over at https://github.com/chapel-lang/chapel/pull/20415

**Comment by bradcray** [comment]
I think this can be closed now?

**Comment by arezaii** [comment]
Yes, it was addressed in https://github.com/chapel-lang/chapel/pull/20415
