### ISSUE TITLE
Large if-then-else statements cause parsing challenges

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#19921]
### Summary of Problem

As pointed out by a user on gitter, very large if-then-else statements cause problems in our parser, manifesting as a memory exhausted error (in the old parser), or a syntax error (in the new one).

[edit: As a workaround for this in the case that each condition is of the form `testExpr = ...`, a large `select` statement can be used instead without problems.  My guess is that we treat chained if-then-else statements as nested scopes and are blowing past some limit due to the recursive nature.]

### Steps to Reproduce

**Source Code:**

```chapel
if (test1) then
else if (test2) then
else if (test3) then
// for dozens of times
```

**Associated Future Test(s):**
[`test/parsing/bigifthenelse.chpl`](
           https://github.com/chapel-lang/chapel/blob/main/test/parsing/bigifthenelse.chpl
          ) #19920

### Configuration Information

- Output of `chpl --version`: `1.26.0` or `chpl version 1.27.0 pre-release (76edbd2d53)`

**Comment by cassella** [comment]
Here's a simpler test:

```
$ perl -e 'print "{\n"x210' > bracing.chpl
$ chpl bracing.chpl
bracing.chpl:198: syntax error: near '{'
$ chpl --no-dyno bracing.chpl
bracing.chpl:198: memory exhausted: near '{'
```

The dyno parser seems to ignore `--parser-debug`, but with `--no-dyno`
it runs down to

```
...
Reading a token: Next token is token TLCBR (197.0: )
Shifting token TLCBR (197.0: )
Entering state 105
Return for a new token:
Reading a token: Next token is token TLCBR (198.0: )
Shifting token TLCBR (198.0: )
Entering state 105
bracing.chpl:198: memory exhausted: near '{'
Stack now 0 2 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105 105
Cleanup: popping token TLCBR (198.0: )
Cleanup: popping token TLCBR (197.0: )
...
```

**Comment by bradcray** [comment]
> Here's a simpler test:

Simpler, but not really as compelling, right?  (i.e., I could imagine a user wanting to do a large if-then-else statement, but I have a harder time imagining a user wanting to create a 210-deep compound statement—and might be less inclined to help that user's code work :) ).

That said, it'd be nice to get a nicer error in either case if we could anticipate this was happening.  And in the if-then-else case, it seems likely that there's a solution given that it doesn't require having the parser treat it as a deeply-nested construct (I think?)—that's probably just the approach we happen to take (?).

**Comment by daviditen** [comment]
Bison's initial stack size for shifted tokens [defaults to 200](http://fog.misty.com/perry/osp/references/bison/by-chapter/bison_8.html#Memory-Management), and it won't grow from there if there are any types involving non-trivial C++ copy-constructors.

Adding:
```C
#define YYMAXDEPTH 25000
#define YYINITDEPTH 20000
```

To `dyno/lib/parsing/chpl.ypp` and `compiler/parser/chapel.ypp` would increase the limit by 100x and require a program with nesting about 100x larger to run into this issue. It would still be possible, but pretty unlikely to be done by a human author at least.

**Comment by bradcray** [comment]
Thanks for that insight, David!  Do you (or does anyone) have any insight into what was an almost reasonable error message in the old parser (about memory being exhausted) becomes a syntax error in the dyno parser?

**Comment by cassella** [comment]
With the latest main, dyno reports memory exhaustion too, though phrases it differently:

```
$ chpl bracing.chpl
bracing.chpl:198: syntax error: memory exhausted
$ chpl --no-dyno bracing.chpl
bracing.chpl:198: memory exhausted: near '{'
```

**Comment by daviditen** [comment]
I don't see anything jumping out. I might have guessd that it could be that dyno tries to continue after a syntax error, but I don't think that's it. The difference I'm seeing is:
dyno:
```bash
bigifthenelse.chpl:100: syntax error: memory exhausted

--no-dyno:
```bash
bigifthenelse.chpl:100: memory exhausted: near 'name'
```

Which seems relatively minor.

**Comment by dlongnecke-cray** [comment]
After making sure we can resize, I can parse up to 2500 branches deep on my machine before we run out of memory with the default stack size. Does that seem reasonable?
