### ISSUE TITLE
No compile time warning/error for missing brace

### ISSUE THREAD

**Issue by ghbrown** [chapel-lang/chapel#19938]
### Summary of Problem
Failure to detect missing loop closure `}` at compile time. Executable "runs" but does nothing.

### Steps to Reproduce

```chapel
for 1..5 {
    writeln('is this an error?');
}
```

Compile and execute code as-is to demonstrate that it is in good working condition.

Remove line `}` closing the loop and compile (note the lack of errors or warnings) and run (note no output). This is not just limited to for loops, it at least extends to ifs. It also extends to the case of nested loops where all the closing braces are missing.

I'm pretty sure this only crops up when the closing braces are in the last line of the file, but I don't think it's possible to even check this because of the nesting property above.

**Compile command:**
`chpl <name>`

**Execution command:**
`./<name>`

### Configuration Information

- Output of `chpl --version`: `chpl version 1.27.0 pre-release (cb4a7da0a0)
  built with LLVM version 13.0.1`
- Output of `$CHPL_HOME/util/printchplenv --anonymize`: using packaged version (I worked on the packaging of the version I'm using, but not sure what you'd like people to do if they are using packaged versions, as `${CHPL_HOME}` doesn't seem to be defined and the source gets hidden.)
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
clang version 13.0.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by bradcray** [comment]
@ghbrown: Thanks for reporting.  I'm fairly certain this was part of the fallout of switching to our new parser and that it was fixed in #19923.  I've so far failed to figure out where the SHA version you report fits into the history (maybe just due to it being a Friday), but would you mind pulling 19923 or `main` into your copy of the compiler and see whether that fixes things?  Thanks.

**Comment by ghbrown** [comment]
@bradcray Yes, I'm sure you're right about the source of this error. Apologies for the false alarm, I didn't do my full diligence to check open issues, but glad it's already been caught and fixed.
The current source for the package I'm using is an unmerged PR branch from Michael (#19913), which I assume is behind that fix (and why you couldn't find it in history?).
I'll close, thanks for the quick response.

**Comment by bradcray** [comment]
> Apologies for the false alarm, I didn't do my full diligence to check open issues, but glad it's already been caught and fixed.

No problem, we'd rather get duplicate errors of problems than to not hear about them at all (and they're particularly fun to get when we've already resolved the error :) ).

> The current source for the package I'm using is an unmerged PR branch from Michael (https://github.com/chapel-lang/chapel/pull/19913), which I assume is behind that fix (and why you couldn't find it in history?).

OK, that was my guess as well, but I didn't dig deeper to try and find out.
