### ISSUE TITLE
Should operators called on bool(8) result in bool?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#19976]
Consider the following program that calls `^` with two `bool` values of nonstandard bool size:

``` chapel
var b16 : bool(16)  = true;
writeln("b16 = ", b16, " : ", b16.type:string);

var z = b16 ^ b16;
writeln("x ^ y = ", z, " : ", z.type:string);
```

This program currently has this output:
```
b16 = true : bool(16)
x ^ y = false : bool
```

Meaning, that `b16 ^ b16` results in a `bool` (of default size) rather than a `bool(16)`.

Do we want this behavior? Or do we want `x ^ y` to result in `bool(16)` in this case?

Either way, at a glance, it didn't look to me like the spec discusses this. E.g. I would expect https://chapel-lang.org/docs/language/spec/types.html#the-bool-type to bring it up (and for that matter, the title can't be "the bool type" if we have many bool types).

**Comment by bradcray** [comment]
I think that having it preserve the width of the input bools would make the most sense.  I don't recall a reason we chose the current behavior.

**Comment by mppf** [comment]
One rationale for the current behavior would be if we thought that the default `bool` size is the right size to compute on and the `bool(16)` etc is useful only as a field or array element type for padding/alignment reasons.

**Comment by bradcray** [comment]
Perhaps...  Still, seems like if you've gone to the trouble to specify a size and used it consistently with both arguments, preserving is probably more useful / less surprising.

**Comment by mppf** [comment]
See also https://github.com/chapel-lang/chapel/issues/13142#issuecomment-497892272 and https://github.com/chapel-lang/chapel/issues/13142#issuecomment-1298683404 -- perhaps we could deprecate `bool(w)` in favor of an `@align` attribute (#20945).
