### ISSUE TITLE
chpldoc installation

### ISSUE THREAD

**Issue by lucaferranti** [chapel-lang/chapel#19992]
### Summary of Problem

Similar to what described for mason in #19910, doing

```
./configure
make chpldoc
make install
```

does not place `chpldoc` into the `/usr/local/bin` folder (or whatever folder the user set with `./configure`), I think it would be good to  do something similar to #19911. Furthermore, after manually moving chpldoc to `/usr/local/bin` while trying to use it yesterday, I got the error

```
cannot stat '/usr/local/share/chapel/1.26/third-party/chpl-venv/chpldoc-sphinx-project/*
```
after some digging I fixed this by manually copying `chapel-1.26.0/third-party/chpl-venv` into `usr/local/share/chapel/1.26`. Is this something that `make install` should also take care of?

### Configuration Information

- Output of `chpl --version`:
```
chpl version 1.26.0
  built with LLVM version 12.0.0
Copyright 2020-2022 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)
```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: system
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
- (For Cray systems only) Output of `module list`:

**Comment by mppf** [comment]
@lucaferranti - I've merged https://github.com/chapel-lang/chapel/pull/20020 to address this issue. Would you be able to check if it works in your environment and if so close this issue? Thanks.

**Comment by lucaferranti** [comment]
@mppf I've build it from the source code on main with the following

```
./configure --chpl-home=~/chpl_tmptest
make
make chpldoc
make mason
sudo make install
```

and it seemed to work (binaries and chpldoc-sphinx-projec/ placed where expcted), so happy to close this. Thanks for the quick fix, I think you can now tick another box in #7574 :)
