### ISSUE TITLE
chpldoc: private use causes empty documentation for next function

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#20005]
### Summary of Problem
A ``private use`` can result in documentation output being discarded for the function immediately following the ``private use``.

### Steps to Reproduce

**Source Code:**

```chapel
module M {

  private use IO;

  /* Can you see me? */
  proc helloWorld() {
    writeln("Hello, world!");
  }

  /* This is definitely visible */
  proc fantasticFunction() {
    return 42;
  }

}
```

At the time this issue was filed, the generated .rst will be missing the text "Can you see me? ".

**Associated Future Test(s):**
[`test/chpldoc/functions/privateUseBug.doc.chpl`](
           https://github.com/chapel-lang/chapel/blob/main/test/chpldoc/functions/privateUseBug.doc.chpl)

**Comment by benharsh** [comment]
I haven't had the time yet, but we should check to see whether this is silently affecting any module documentation.

**Comment by bradcray** [comment]
Weird...  Thanks for noting it!

**Comment by lydia-duncan** [comment]
I think I have a fix, and after adding more testing, I think this was coming from all import and use statements, not just private ones.  It looks like it was removing the documentation of every symbol after a use/import statement in our documentation, yikes

**Comment by lydia-duncan** [comment]
Correction: all explicitly public and private use and import statements.  But the default privacy ones weren't fixing it, either, so the end result for our online documentation ended up being about the same
