### ISSUE TITLE
channel.read(type T) not throwing EOF

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#20030]
### Summary of Problem
Currently ``channel.read(type T) : T`` does not throw an EOF error. I believe this is an oversight due to the method's currently trivial implementation where we simply invoke ``channel.read(val)`` and ignore the returned result. While there is ongoing discussion about the design of ``channel.read`` in general, I see no reason that this method in particular should not throw an EOF error at this time.

### Steps to Reproduce

**Source Code:**

```chapel

use IO;
var f = openmem();
var r = f.reader();
var x = r.read(int);
writeln(x);
```

This program prints "0".

**Comment by mppf** [comment]
Yes I agree it should throw on EOF

**Comment by bradcray** [comment]
If this is as easy to fix as I suspect, it'd be great to get it resolved for code freeze.

**Comment by benharsh** [comment]
I'll try and get something going on that today. I'll also update the readln version at the same time.

Is there an issue discussing whether we can remove the ``channel.read(type T)`` method in favor of the varargs version?

**Comment by mppf** [comment]
> Is there an issue discussing whether we can remove the channel.read(type T) method in favor of the varargs version?

Which varargs version are you talking about here? Are you talking about the `type t ...` version? That one returns a tuple so IMO wouldn't make sense as a replacement for this one.
