### ISSUE TITLE
Should file.lines be an iterator, or return an iterable object?

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#20059]
Our current ``file.lines`` signature:

```chpl
proc file.lines(param locking:bool = true,
                start:int(64) = 0,
                end:int(64) = max(int(64)),
                hints:iohints = IOHINT_NONE) throws
```

This **method** returns an iterable object (an ItemReader) that will yield lines from the file. Is that desirable, or should this simply be an iterator?

By returning an object the caller can lazily evaluate the results, though one could potentially argue that such functionality should be available with normal iterators as well.

In considering this design issue, consider that the original purpose of ``file.lines`` is to support distributed and/or parallel iteration over a file. Is there an advantage in returning an object in those cases? Does robust support for a distributed/parallel ``file.lines`` suggest what the signature should be, and does that indicate a preference between an iterable and an iterator? See #4959 for relevant discussion on parallel ``file.lines``.

**Comment by mppf** [comment]
AFAIK it is just an implementation oddity that it returns an iterable object and it could be an iterator that iterates over that same object.

**Comment by bradcray** [comment]
My instinct here matches yours—"an iterator seems more straightforward", but your point about distributed execution gave me pause...  (parallel doesn't because we could presumably write parallel iterator overloads for `file.lines`).  Not enough pause to give up on the iterator approach, but just to wonder if there might've been a deeper motivation than I'm currently seeing.

> one could potentially argue that such functionality should be available with normal iterators as well.

:+1: :tada:

This has been a long-term request from users, though not frequent enough or from important enough ones to get much attention yet...

**Comment by lydia-duncan** [comment]
In the IO module re-review on October 4th, we decided to deprecate this function.  The vote was 6 in favor, no opposed

If we decided to go back on that decision for some reason, here were the other votes:
- make file.lines an iterator: 4
- add keepNewLine arg: 4

**Comment by bradcray** [comment]
Just to capture the rationale for the deprecation:  Because it was the only case we could think of where one could read/write directly from/to a file without going through a channel/reader/writer.

**Comment by mppf** [comment]
> Just to capture the rationale for the deprecation: Because it was the only case we could think of where one could read/write directly from/to a file without going through a channel/reader/writer.

And, additionally, today it doesn't offer any benefit over using the channel/reader/writer version.

**Comment by lydia-duncan** [comment]
I believe this has been fully implemented, closing
