### ISSUE TITLE
Should ranges/domains be able to be counted using any integral type?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#20085]
Today, when applying `#` to a range of integers, the count argument is expected to be an `int` or `uint` of matching width (or something that can coerce to that width).  This can be particularly annoying when using a range of small ints but applying a count of default int type, e.g.:

```chapel
config const n = 10;
var i8: int(8) = ...;
var r = 0..i8;  // r describes int(8) values
...r # n...   // Doesn't work today since `n` is int(64) which won't coerce to int(8) or uint(8)
```

In this issue, I'm proposing that `#` really shouldn't care about the integral type being passed in, only its value.  I.e., if `n` was set to 1000 above, that should be a problem because it's too large, but the fact that `n` _can_ take on larger values (but doesn't when it's 10) shouldn't be one.

I think the main historical argument for this was that if we think of `#` as being a binary operator then, like `+`, we'd define its arguments for similar types, where (a) we treated the range's idxType as the lhs type and (b) we extended the rhs to support signed and unsigned for convenience.  But even ignoring those asymmetries, I don't think this rationale really holds up since (a) we don't have param ranges, which would be necessary to make them similarly flexible as `+` is today, and (b) `#` isn't a particularly symmetrical operation.  Where it may make sense for `+` to end up generating the "greater" type of its two arguments (when one exists), for `range op integral` cases, I think it makes the most sense for the range's type to dominate, particularly given the prevalence of default integers in Chapel code (so their likelihood to be applied via a `#` operator.  As a specific example, I don't think it makes sense to convert a `range(int(8))` into a `range(int(64))` just because an `int(64)` count is applied to it.

To me, this seems like a no-brainer, but I'm opening this for discussion to make sure others agree before proceeding.

Domains (and arrays) currently don't assert any type constraint on the integers applied to them with `#`,  but accept any integral and pass it downstream, so enabling this behavior on ranges would also permit it for domains and arrays.

This issue was forked off from a conversation starting here:  https://github.com/chapel-lang/chapel/issues/19958#issuecomment-1154670991

**Comment by bradcray** [comment]
I'm also thinking we should permit `by` to be similarly flexible in this way, focusing more on its dynamic value than on the values its static type _could_ store, though I'm going to save that as a separate follow-on issue.

**Comment by vasslitvinov** [comment]
My justification for this proposal is that `#` and `by` produce a subset of the lhs range. Therefore expanding the idxType of the lhs range is not necessary / does not buy us anything, regardless of the rhs.

**Comment by bradcray** [comment]
> Therefore expanding the idxType of the lhs range is not necessary / does not buy us anything, regardless of the rhs.

Just to play devil's advocate, it could buy something if the program went on to assign that range a different range value going forward that the original range type couldn't store.  But I'm not suggesting this is likely/good/a rationale for keeping the current behavior or having it take on the "max" type of the two sides.
