### ISSUE TITLE
Check for incompatible CUDA versions

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#20086]
https://github.com/chapel-lang/chapel/pull/20016 suppressed the incompatible CUDA version warning emitted by clang. This is fine because we are using a very limited/core part of the CUDA Driver API. However, we want to be more principled here. We should improve our chplenv scripts to compare the Clang and CUDA versions to:

- Error at build time if CUDA is too old (we do that for things like system LLVM, hwloc etc)
- Warn at build time if CUDA is too new (where my hope is that Clang doesn't fall too behind CUDA such that we'd be using something that's removed in a non-backwards-compatible way)

**Comment by stonea** [comment]
I have a PR for this here: https://github.com/chapel-lang/chapel/pull/22170

Although this will error out if CUDA is too new (>= 12) but can be turned into a warning by setting an environment variable that's suggested in the error message.
