### ISSUE TITLE
[feature request] `mason test` should print the error when fails to compile

### ISSUE THREAD

**Issue by lucaferranti** [chapel-lang/chapel#20083]
`mason` is already a great tool to develop packages. One thing that I find slows down my productivity a little is that if `mason test` fails to compile the tests, either for compilation error in the package under development or tests itself, it just prints "compilation failed" and I need to manualy run `chpl test/mytestfile.chpl -M src/` to actually get the error message and debug the code. 

As a demo, if I have the following file under my tests

```chpl
use UnitTest;

proc test_simple(test : borrowed Test) throws {

    test.assertEqual(1, 1) // note semicolon missing
}

UnitTest.main();
```

`mason test` will print

```
Skipping registry update since no dependency found in manifest file.
compilation failed for test_example.chpl

======================================================================
ERROR test_example.chpl: test_example
----------------------------------------------------------------------
test_example.chpl failed to compile
----------------------------------------------------------------------
Ran 1 test in 0.350362 seconds

FAILED (errors = 1)
```

I think it would be more useful to report the actual compilation error.

**Comment by lucaferranti** [comment]
Another nice-to-have feature would be the following. Currently, if I have something like

```chpl
use UnitTest;

proc test_simple(test : borrowed Test) throws {

    test.assertEqual(1, 2); // note semicolon missing
}

UnitTest.main();
```

`mason test` produces

```
Skipping registry update since no dependency found in manifest file.

======================================================================
FAIL test_example.chpl: test_simple()
----------------------------------------------------------------------
AssertionError: assert failed - '1' != '2'

----------------------------------------------------------------------
Ran 1 test in 13.1385 seconds

FAILED (failures = 1 )
```

I think it would be great to also print the line in the test file where the assertion failure happened, this would allow to identify the broken test more easily.

Arguably, this would not be needed if one wrapped every single test in its own proc, but I would think of those procs as "tests blocks", where each proc is related to a specific feature / operation and contains several tests for that functionality. Is this how procs-as-testblocks how `UnitTest` was envisioned to be used, or was the original design that each assertion would be wrapped in its own proc?

**Comment by bradcray** [comment]
Hi @lucaferranti — Focusing just on the OP: In #19989, @arezaii extended `mason test` to give a hint about the `--show` flag when a test fails.  For example, running your example on `main` today (which will become 1.27.0 later this week), I see:

```
$ mason test
Skipping registry update since no dependency found in manifest file.
compilation failed for testit.chpl

======================================================================
ERROR testit.chpl: testit
----------------------------------------------------------------------
testit.chpl failed to compile
Try running 'mason test --show' for more details
----------------------------------------------------------------------
Ran 1 test in 1.30748 seconds

FAILED (errors = 1 )
```

on my first compile, and then taking the hint, see:

```
$ mason test --show
Skipping registry update since no dependency found in manifest file.
/Users/bradc/chapel/HelloPackage/test/testit.chpl:6: syntax error: near '}'
compilation failed for testit.chpl

======================================================================
ERROR testit.chpl: testit
----------------------------------------------------------------------
testit.chpl failed to compile
Try running 'mason test --show' for more details
----------------------------------------------------------------------
Ran 1 test in 1.3619 seconds

FAILED (errors = 1 )
```

(note to @arezaii : It seems like it would make sense to squash the `--show` hint when the flag is actually used.

@lucaferranti : Can you let us know whether this serves your need?  I think the reason the output isn't shown by default is that it might get quite verbose in the presence of many tests (?).

W.r.t. your second issue, yeah, let's branch that off to a separate issue, if you would.

**Comment by bradcray** [comment]
Also, I meant to say, but:  I'm fairly certain the change in behavior above was motivated by our experience during your CHIUW 2022 coding day experience.  So not as coincidental in time as it might appear to an outside observer.  :)

**Comment by arezaii** [comment]
PR #20088 quiets the `--show` hint when `--show` was used

**Comment by lucaferranti** [comment]
@bradcray just upgraded to chapel 1.27 and played a little with mason, yes I think this issue is now solved.

> I'm fairly certain the change in behavior above was motivated by our experience during your CHIUW 2022 coding day experience.

cool! I also remembered we discussed something like this issue on the coding day, which is why I opened the issue, very cool you fixed it even before I opened it though

**Comment by arezaii** [comment]
Just commenting here that PR https://github.com/chapel-lang/chapel/pull/23713 implements the reporting of `UnitTest` file and line information during an assertion failure, a feature requested by @lucaferranti [in a comment in this thread](https://github.com/chapel-lang/chapel/issues/20083#issuecomment-1166286620).
