### ISSUE TITLE
Update sync/single primer

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#20097]
I think https://chapel-lang.org/docs/main/primers/syncsingle.html needs to be updated with the types that are supported by syncs/singles now (I think we recently expanded that) and to remove the `$` suffix convention since I think we're moving away from that.

I believe it was already updated to get rid of the implicit read/write semantics, but I didn't look at the comments closely to see if any of them still talk about that feature.

**Comment by ronawho** [comment]
FYI @bradcray

**Comment by bradcray** [comment]
This relates to https://github.com/chapel-lang/chapel/issues/19152

**Comment by ronawho** [comment]
Feel free to close this as a duplicate. I guess there's a little new info with the types, but it seems close enough to a dupe to me if you want to consolidate.
