### ISSUE TITLE
SysBasic module: should we continue to support 'syserr'?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#20119]
It can be used to represent C error codes and some error codes of our own devising for use in the runtime.

With the advent of error handling and the Error subclasses currently defined in SysError, we expect the preferred way to interact with error conditions to be either those subclasses (for Chapel code) or symbols defined in OS and OS.POSIX (for C interoperability).

Some version of this symbol will probably be useful for internal purposes, but we're currently leaning towards deprecating the version that lives in SysBasic and not exposing its replacement to users.

**Comment by mppf** [comment]
Yes it's currently involved in improving some error message from I/O code in the runtime. Of course there are many other ways of doing that but we can leave it there for internal use while improving the API.

**Comment by lydia-duncan** [comment]
Closing, Brad pointed out this was resolved by #20538
