### ISSUE TITLE
Should formal arguments of `integral` type accept bool actuals?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#20125]
The following program demonstrates that while a routine that accepts `int(?w)` can be passed bools, one that accepts `integral` currently cannot.  While I understand the argument for this might be (e.g., "integral describes our integer types, int and uint, and bool is not that"), it also seems asymmetric to me in that they each seem like a way of saying "I accept a generic int-like argument."  So it seems as though it would be more consistent if they either both accepted bool or both didn't (where I'd lean more towards "both accepted, because I find the coercions from bools to ints to be more convenient than annoying).

```chapel
proc foo(x: int(?w)) {
  writeln("In foo, x is ", x.type:string);
}

proc foo(x: uint(?w)) {
  writeln("In foo, x is ", x.type:string);
}

proc bar(x: integral) {
  writeln("In bar, x is ", x.type:string);
}

config var flag = true;

foo(flag);
bar(flag);
```

I think that the practical reason for why these act differently relate to how we implement `int(?w)`, where we don't think of this as a "can pass any int to this routine" but instead stamp it out as each of the int widths, `int(8)`, `int(16)`, `int(32)`, `int(64)` and then determine that which is the best match for the coercing `bool`.  This has always seemed a little unfortunate to me in that it's not something a user can write themselves (i.e., "when instantiating `foo(r: R(?))`, stamp out calls for it for each of these instantiations of `R`"), so feels a bit too special.  That suggests that ultimately, we should treat this more like an `integral && isSigned()` constraint and expand both cases to support `bool` if we want to preserve the current behavior and extend it to `integral`.

Alternatively, we could go what I'd call the lamer route and treat `x: integral` as "stamp this out for all types that integral describes", which I suspect would make these cases behave more similarly today.

Note that this relates to #20114 and #20111 because it was a rewrite of the `#` operator from `int(?w)`/`uint(?w)` overloads to `integral` overloads that caused `#` accepting bools to stop working inadvertently.

**Comment by mppf** [comment]
AFAIK this issue asks the same question as #20011.

**Comment by bradcray** [comment]
Good point.  I did have a vague memory of it, and did a quick search for it, but made the mistake of including 'integral' in my search criteria, which was not mentioned there...

**Comment by bradcray** [comment]
The more I've thought about this issue since filing it, the more I think that I like the current behavior for `integral` and `bool` and am not advocating for change here.  Specifically, if I write a routine that expects an `int` or `uint` of any size using `integral`, it seems unlikely that I would necessarily have (or want to have) `bool`s in minds when writing it.  More specifically, I would not want it to be instantiated for `bool`, nor would I want the `bool` to implicitly convert to an `int(8)`, which seem like the two most reasonable behaviors.  As a specific example, the `by` operator could be written to take an `integral` argument, but `bool` is not a particularly interesting value to pass to it, and not one that I'd want to have be implicitly permitted without opting into it as the routine's operator.

W.r.t. the asymmetry for the `int(?w)` arguments, I think we should address that by closing that loophole, probably by not having `int(?w)` stamp out all legal instantiations.

**Comment by mppf** [comment]
> Specifically, if I write a routine that expects an `int` or `uint` of any size using `integral`, it seems unlikely that I would necessarily have (or want to have) `bool`s in minds when writing it. More specifically, I would not want it to be instantiated for `bool`, nor would I want the `bool` to implicitly convert to an `int(8)`, which seem like the two most reasonable behaviors.

Well, AFAIK, if you made a bunch of overloads for all int/uint types, then you would end up calling the `int` version when passing a bool. So I would expect an `integral` formal to lead to the same behavior.

> W.r.t. the asymmetry for the `int(?w)` arguments, I think we should address that by closing that loophole, probably by not having `int(?w)` stamp out all legal instantiations.

This is more the topic of #20011, but if `int(?w)` is interpreted as a generic type for `int` of any width then we would not be able to pass `bool` to it, with the current rules. Do you think that `bool` should pass to `int(?w)` formals?

IMO we should either allow instantiating these with `int` when passing a `bool`; or we should remove `bool` to numeric implicit conversions. I think it's important that 

```
proc f(arg: int(?w))
```

and

```
proc f(arg: int(8))
proc f(arg: int(16))
proc f(arg: int(32))
proc f(arg: int(64))
```

behave the same in terms of what types can be passed to them. But, perhaps I am too stuck in the "how it has been working" view and it is good enough to replace `int(?w)` in the standard library with multiple overloads for the specific concrete types & to disallow implicit conversions for `int(?w)` formals.

**Comment by bradcray** [comment]
> Do you think that bool should pass to int(?w) formals?

No, not particularly (at this moment).  Basically, I'm reading `int(?w)` as "I can take any int."  Bool is not an int, so it's not surprising that it can't be passed in.
