### ISSUE TITLE
IO module: replace start and end arguments with range argument

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#20133]
There are six functions which take a `start` and `end` argument in the IO module.  Conceptually, it makes sense for Chapel to provide a `region` argument of `range` type instead, since those functionally represent the same thing.

We believe a range argument would help make it obvious to users that the result of the function will operate over that specific section of the file.

We'll want to generate an error if a strided range is provided, as channels do not support strided traversal of files today (nor do we expect them to).  We'll also want to be careful that providing a default value for the region argument does not force it to be bounded or unbounded. 

The six functions are:
- `openreader`
- `openwriter`
- `file.reader`
- `file.writer`
- `channel.seek`
- `file.lines`

And we'd expect the argument to look something like `region: range(?) = 0..`

**Comment by mppf** [comment]
When we discussed this off-issue, the proposal to use only have range versions (vs having a range version and also a start/end version) had a lot of support and nobody in that setting was opposed.

**Comment by lydia-duncan** [comment]
This ended up taking closer to 3 points, both because I needed to add tests of the functionality for some of them and because of the bugs with `openwriter`.  That function will be handled in a separate way, the rest are in chapel-lang/chapel#20475
