### ISSUE TITLE
IO module: proposed changes to iomode enum

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#20134]
The `iomode` enum is used with all the `open*` standalone functions in the IO module to specify what kind of file to open.

It currently has the following definition:
```
enum iomode { r = 1, cw = 2, rw = 3, cwr = 4 }
```

The languages we looked at tend to use strings with similar values to these enum constants instead of defining an enum.

The IO subteam thinks we should rename the enum.  At the very least it should be camelcased `ioMode`, but we could consider naming it something else like `access` (note: `mode` is the name used for the argument to the functions it is used in and that matches other languages).

We could also consider adding an overload for these functions with a param string argument instead of an argument of this enum type, or relying solely on that string argument.  But we don't think it's a problem the way it is now.

The documentation for this enum also has a TODO for supporting four more modes:
- "a" - open the file for appending, creating if it does not already exist
- "ar" - open the file for appending and reading
- "cwx" - open the file for writing, throwing an error if the file already exists
- "cwrx" - open the file for reading and writing, throwing an error if the file already exists.
If we choose to add these after the other enum constants, it would not be a breaking change.  However, if we felt it was better to add them interspersed among the already existing ones (seems unlikely), that would be a breaking change and we would want to do that before 2.0.  It would also not be a breaking change if we had replaced the enum with strings and added them as string options.

The "x" in the last two new modes stands for "exclusive" and is useful for security purposes.  There's a note on `opentmp` that it would maybe like to switch its default behavior to use one of them (see #20147)

**Comment by bradcray** [comment]
> The languages we looked at tend to use strings with similar values to these enum constants instead of defining an enum.

I have to say that I'm not a huge fan of using strings for things that only support a fixed set of choices—it feels overly general and heavyweight for what's required to me.

I'd probably stick with an enum, but if we went with the record-based solution Engin proposed for iohints today, I wonder whehther that would apply here (given that most of the strings read something like the "or" of a bunch of features?)

I think the main downside to an enum is that it's more typing if fully qualified, and we've been reluctant to make any enums auto-used by their defining module so far.  I keep wishing for a context-sensitive way to pass an enum to an argument that is known to be enum, but when I wrestle with it, it feels pretty iffy w.r.t. evaluating arguments prior to determining which visible functions are candidates.

We could also consider having a utility routine that converts strings used by other languages into the appropriate enum.

As other names for the type:`fileMode`?  `fileAccessMode`?

**Comment by lydia-duncan** [comment]
That's a possibility, but I think would require more care than the iohints case.  If my understanding is right, "appending" and "writing" are mutually exclusive options - if you want to add to a file, you either want it to be appending or writing, but both doesn't make sense (because then that's just appending, right?).  And the "exclusive" case wouldn't work with "appending" either, since appending implies the file is already present but exclusive would want to error in that case.

So if we did want to enable combining, we'd want to have error checking when combinations are made that we don't expect to support.  It's probably just simpler to strictly control the combinations we do want, though.

**Comment by mppf** [comment]
Note that we currently have `enum iomode { r = 1, cw = 2, rw = 3, cwr = 4 }`.

Yes in this specific case I prefer having enum values for the combinations that make sense / are supported. Also it would be my preference to enable a param string version in addition to the enum version, FWIW. The reason I would like the param version is that `open("path", "r")` is shorter / easier to remember how to type than `open("path", ioMode.r)` in my opinion. Anyway, I think limiting it to param strings reduces the bad aspects of using strings there.

**Comment by bradcray** [comment]
I'm still generally not a fan of the "support string arguments" direction, mostly due to the "two ways to say the same thing" concern.

**Comment by lydia-duncan** [comment]
In the IO module re-review on Oct 4th, we decided to rename this enum to ioMode and not to make other changes to it (though adding additional modes is fair game post-2.0):

 Voting:
    - leave as-is: 8
    - add overload for param strings: 3
    - replace enum with strings:

    - rename to 'access': 1
    - rename to 'fileMode': 2
    - rename to 'fileAccessMode':
    - rename to 'ioMode': 7
