### ISSUE TITLE
IO module: what should we do about openfd?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#20143]
openfd is defined like this:
```chapel
proc openfd(fd: fd_t, hints: iohints = IOHINT_NONE): file throws
```
It creates an open `file` object that points to the provided file descriptor `fd` argument.  The docs suggest that it can be obtained by calling [sys_open](https://chapel-lang.org/docs/latest/modules/standard/Sys.html#Sys.sys_open) or [sys_connect](https://chapel-lang.org/docs/latest/modules/standard/Sys.html#Sys.sys_connect)

There are a few issues with this function that should be addressed.  First, should we keep it?  #20128 proposes removing the type used to define its `fd` argument, does that imply that it should also be removed?  We could replace the type with `c_int` since that is the equivalent type, but `c_int` is more low-level than most of the other parts of the IO module interface.

Does that imply it should live somewhere other than the IO module, if we do decide to keep it?  It does create a `file` type, which is defined in the IO module, and is in a similar vein to `open` and other similarly named functions, which we have no reason to believe will live anywhere other than the IO module.

If we do decide to keep it, we should probably rename it.  Some options we've thought of include:
- openFD
- openFd
- openFileDesc
- openFileDescriptor
- make it a factory function on the `file` type, e.g. `file.fromFD` or `file.fromFileDesc`, since it's likely already open as a result of the two suggested ways to obtain it?
- make it an initializer on the `file` type, for a similar reason?

And if we do decide to keep it, it should have similar documentation updates to `open`, see #20139 

So, the questions:
- Should we keep this function?
  - If so, should it live in the IO module or somewhere else?
  - And if we should keep it, what should we rename it to?

Edit: note that #20430 will also impact this function

**Comment by mppf** [comment]
I don't understand how to implement new features such as the Sockets module without this function.

**Comment by lydia-duncan** [comment]
I've added a third option for "keep but don't make it user facing"

**Comment by jeremiah-corrado** [comment]
> It creates an open file object that points to the provided file descriptor fd argument. The docs suggest that it can be obtained by calling [sys_open](https://chapel-lang.org/docs/latest/modules/standard/Sys.html#Sys.sys_open) or [sys_connect](https://chapel-lang.org/docs/latest/modules/standard/Sys.html#Sys.sys_connect)

The `Sys` module deprecation (in its current state) removes `sys_open` and `sys_connect`: https://github.com/chapel-lang/chapel/pull/20126

Should these also be kept around if `openfd` is not deprecated? If so, would the IO module be a good place to put them?

**Comment by mppf** [comment]
Maybe we need something like a new submodule `IO.LowLevelIO` or something for `openfd` and `openfp` (whatever we end up calling them).

**Comment by mppf** [comment]
In terms of naming, what bugs me about `openfd` (and `openfp`) is that they don't actually open anything at all. They just create a Chapel `file` that refers to a C or OS file. So I don't think they should have `open` in the name.

**Comment by lydia-duncan** [comment]
If my memory serves, the `sys_*` wrappers tend to be wrappers around actual system calls.  I suspect `OS` would be an appropriate place for declarations of them.  I could see putting `openfd` in `OS` as well (especially since `OS` would probably be less commonly used than `IO`)

**Comment by mppf** [comment]
> The `Sys` module deprecation (in its current state) removes `sys_open` and `sys_connect`: #20126
> 
> Should these also be kept around if `openfd` is not deprecated? If so, would the IO module be a good place to put them?


I don't we need to keep `sys_open` etc if we keep `openfd` in some form because somebody can always write their own `extern proc` to get these. Anyway if we want C's `open` available, then it should end up in `OS.POSIX`.

**Comment by jeremiah-corrado** [comment]
Ok, sounds good!

> in terms of naming, what bugs me about openfd (and openfp) is that they don't actually open anything at all. They just create a Chapel file that refers to a C or OS file. So I don't think they should have open in the name.

That makes me think @benharsh's idea about a factory function naming-style makes more sense then: https://github.com/chapel-lang/chapel/issues/20147#issuecomment-1172698066

Maybe something like: 
```chapel
file.getFromDescriptor(fd: fd_t, hints: iohints = IOHINT_NONE): file throws
```

**Comment by jeremiah-corrado** [comment]
> How about making fd_t a magic enum that has an enum const for any possible fd value

Isn't the number of allowed file descriptors system dependant? And it can be changed by another system call during program execution?

**Comment by mppf** [comment]
> This way we will not be passing around naked ints that we want to mean file descriptors.

But part of the purpose of this function is to support interoperability. For example, we don't have `pipe` call in Chapel modules, nor do I expect we will be adding it soon. (https://linux.die.net/man/2/pipe). So a user who wishes to work with it in Chapel can call the C function and will get back C file descriptors which are just ints. Then the call `new file(myFileDescriptor)` to get a Chapel file from one of these.

IMO wrapping the C file descriptor in a Chapel record first just adds noise & I don't think there is much benefit because, if you aren't doing C interoperation, I wouldn't expect you to ever use the `new file(myFileDescriptor)` functionality at all.

**Comment by lydia-duncan** [comment]
Voting from the IO module re-review on Oct 4th:

What to do with the function itself
- Leave as-is:
- initializer on a file: 10
- type method on a file:
- rename the function:

What to do with the argument
- rename 'fd' to 'fileDesc': 1
- rename 'fd' to 'fileDescriptor': 7
