### ISSUE TITLE
IO Module: Name of method that indicates a closed/open/valid 'file'

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#20153]
We intend to deprecate the ``file.check`` method. The purpose of this method is to determine whether a file is closed, or if its internal pointer is null. The pointer may be null if the file was default-initialized, or if an error occurred in the runtime.

There were three options proposed:

```chpl
proc file.isClosed() : bool { } // returns true if file was closed or if pointer is null

proc file.isOpen() : bool { } // returns true if the file pointer is not null and if the file is still open
proc file.isValid() : bool { } // same as isOpen
```

### Precedence

In Chapel:
- isClosed: only ``channel.isClosed`` exists today
- isValid: in the Futures module

Other languages:
- I don't think rust allows for closed or invalid files to be accessible
- C# doesn't seem to have a 'file' type like this, and its StreamReader seems to use ``null`` to determine validity
- python has a paren-less ``closed`` property: ``myFile.closed``, where ``myFile`` was created from a call to ``open``
- Julia: uses ``isopen``

**Comment by benharsh** [comment]
I personally don't like ``isValid`` because a previously opened file that is now closed feels to me like a valid state.

Between ``isOpen`` and ``isClosed``, I suppose that I don't have a particularly strong opinion. In googling around to see what other languages do, I have seen people asking how to determine if a file is opened by something else. Is there potential confusion due to assumptions users might make about what ``isOpen`` indicates?

Taking a step back for a moment, I think the general usage here would be from users wondering whether they can use a file or not. From the user's perspective, that question will probably be more related to "can I read this file?" or "can I write this file?". I would still want some kind of ``isOpen`` or ``isClosed`` method, but if we had a way of answering these more relevant questions I wouldn't care as much what we decide here.

I don't think we have a way of querying a file's iomode today. If that's of interested, I can create a separate issue.

**Comment by mppf** [comment]
> I personally don't like `isValid` because a previously opened file that is now closed feels to me like a valid state.

👍

**Comment by bradcray** [comment]
I understand that they're trivially redundant, but I'd probably support both `isOpen()` and `isClosed()`.  That avoids having to decide which is the more likely thing someone would want to write...

**Comment by lydia-duncan** [comment]
In the IO module re-review, the team decided to only add `file.isOpen()`

Voting:
    - isOpen: 10
    - both isOpen and isClosed : 4

**Comment by bradcray** [comment]
Capturing some of the rationale that stuck for me:  If a file isn't open, it may be that it was opened then closed, was never opened, somehow isn't a valid file, etc.  So `isClosed()` felt like it might be a bit more ambiguous as to what question it was answering relative to `isOpen()`.
