### ISSUE TITLE
IO module: Should we keep (and rename) openreader/openwriter?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#20150]
```chapel
proc openreader(path:string,
                param kind=iokind.dynamic, param locking=true,
                start:int(64) = 0, end:int(64) = max(int(64)),
                hints:iohints = IOHINT_NONE)
    : channel(false, kind, locking) throws

proc openwriter(path:string,
                param kind=iokind.dynamic, param locking=true,
                start:int(64) = 0, end:int(64) = max(int(64)),
                hints:iohints = IOHINT_NONE)
    : channel(true, kind, locking) throws
```

These two functions are for creating a file and returning a reading/writing channel on that file (respectively).  They are equivalent to calling `open` followed by `file.reader` or `file.writer` as the case may be, and are provided as a convenience.

Should we keep these functions?

If we keep them, we should probably rename them to `openReader` and `openWriter`.

#20133 talks about replacing their `start` and `end` arguments with a single `region` argument.  Their arguments that are based on channel fields should also get updated to match any changes to them.

Should we error if an invalid region was specified?  E.g. starting earlier than 0, ending before it starts, etc.

If we keep them, we should also update their documentation to reflect the same errors as `open` (see #20139)

**Comment by lydia-duncan** [comment]
Vote here for if we should we keep these functions (👍🏻 👎🏻 )

**Comment by bradcray** [comment]
I feel pretty neutral about these, which goes against the way the voting is so far.  Are there compelling uses of them in practice that would make me a believer?

**Comment by lydia-duncan** [comment]
It looks like they're used in the labelprop benchmark, a number of TOML and CSV tests where the point is to test the functionality of those modules and not openreader, and Nikhil's test/users/npadmana/twopt/do_smu_soa.chpl, of the slightly more interesting cases.  I don't personally know if `open(...).reader(...)` is bad but it seems like a personal preference thing (where I think two sets of parentheses is a bit more of a headache to look at, especially given that both `open` and `file.reader` have 2+ arguments).

**Comment by lydia-duncan** [comment]
From the meeting on Tuesday:

openreader:
 * should we keep this function - 6
 * should we remove this function - 0

openwriter:
 * we should keep this function - 8
 * we should remove this function -0

With that in mind, they will both be renamed to use camelCase.

For openreader, file.reader and file.writer, we've voted on some potential edge cases and whether to make them be explicit errors:

Poll:
 * should we error if `region.low < 0` - 10
 * should we not error in that case

Poll:
 * we should error if `region.high < region.low` - 2 (Lydia, John)
 * we should not error in that case - 7

Meeting discussion about those polls:

[Anna's Comment in chat: "Can someone explain to me why we would error for `region.low < 0` but not for `region.high < region.low?` Those seem inconsistent to me as two kinds of degenerate ranges"]

Brad: w.r.t. to Anna's comment: to create a range with negative indices, you have to take some action to make that happen. I can't think of any case where it would be powerful/useful to specify a negative region of a file. But in the empty case, it makes sense to get an empty range as the result of some computation

Daniel: In the negative case, there is no way for that to be valid. But in the empty case, that is a valid yet-degenerate portion of a file. I.e., it doesn't feel ostensibly erroneous to have an empty file range.

Engin: The direction that the vote is going is the same behavior that we have in string slicing today. If you give a negative index, we error at runtime.
