### ISSUE TITLE
How to efficiently store distributed arrays in classes?

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#20164]
This is based off of Arkouda's SymEntry class, which is a wrapper around arrays. In working on https://github.com/Bears-R-Us/arkouda/issues/1398 I found that there was a surprising amount of communication to privatize and reprivatize when creating a new SymEntry from an existing array.

The SymEntry class looks roughly like:

```chpl
proc makeDistDom(size:int) {
  use BlockDist;
  return {0..#size} dmapped Block(boundingBox={0..#size});
}

proc makeDistArray(size:int, type etype) {
  var a: [makeDistDom(size)] etype;
  return a;
}

class SymEntry {
  type etype;
  const size: int;
  const aD: makeDistDom(size).type;
  var a: [aD] etype;

  proc init(size: int, type etype) {
    this.etype = etype;
    this.size = size;
    this.aD = makeDistDom(size);
    // this.a uses default initialization
  }

  proc init(a: [?D] ?etype) {
    this.etype = etype;
    this.size = a.size;
    this.aD = D;
    this.a = a;
  }
}
```

Where ideally creating a new SymEntry will result in privatization for the distribution, domain, and array just once each. And for creating a SymEntry from an existing array I think we'd like to reuse the existing distribution and domain and only create and privatize a new array. Even more ideally if `a` was dead after passing it to the initializer it'd be great to just steal the array/memory and avoid having to create anything new.

Today though when creating a SymEntry from an existing array, I believe we're creating a new domain/distribution and privatizing from the `const aD: makeDistDom(size).type;` then `this.aD = D;` results in reprivatization and so does `this.a = a;`

---

There are some other quirks we've found here. In some places Arkouda creates a distributed SymEntry from a local DefaultRectangular array and it's not obvious how that works today. In trying to optimize out some of the array creation I was looking to stop storing the domain and just have `var a = makeDistArray(size, etype);`, but this broke the cases where a non-block array was passed to the initializer. For some reason changing that to `var a: makeDistArray(size, etype).type;` resolved it, but it's not obvious if that's for any good reason or we're just missing checks for that type of declaration.

And in other cases for arkouda segmented strings that are composed of two Arrays/SymEntrys tuples are often returned and passed in so https://github.com/chapel-lang/chapel/issues/18077 is likely important for reducing additional copies.

**Comment by ronawho** [comment]
Here's the start of a performance test I've been using:

<details>

```chpl
module SymArrayDmap {
  proc makeDistDom(size:int) {
    use BlockDist;
    return {0..#size} dmapped Block(boundingBox={0..#size});
  }

  proc makeDistArray(size:int, type etype) {
    var a: [makeDistDom(size)] etype;
    return a;
  }
}

module MultiTypeSymEntry {
  use SymArrayDmap;
  class SymEntry {
    type etype;
    const size: int;
    const aD: makeDistDom(size).type;
    var a: [aD] etype;

    proc init(size: int, type etype) {
      this.etype = etype;
      this.size = size;
      this.aD = makeDistDom(size);
      // this.a uses default initialization
    }

    proc init(a: [?D] ?etype) {
      this.etype = etype;
      this.size = a.size;
      this.aD = D;
      this.a = a;
    }
  }
}

module Diags {
  use List, Time, IO, CommDiagnostics;

  config const printDiags = false;
  config const printTime = true;

  record orderedMap {
    type keyT, valueT;
    var keys: list(keyT);
    var vals: list(valueT);

    proc this(k: keyT) ref {
      if !keys.contains(k) {
        keys.append(k);
        var defValue: valueT;
        vals.append(defValue);
      }
      return vals[keys.find(k)];
    }
    iter items() {
      for (k, v) in zip(keys, vals) do yield (k, v);
    }
  }

  record Diags {
    var t: Timer;
    var d: [LocaleSpace] commDiagnostics;

    proc startStop() {
      if t.running {
        t.stop();
        if printDiags {
          stopCommDiagnostics();
          d = getCommDiagnostics();
          // TODO, append not override
        }
      } else {
        t.start();
        if printDiags {
          resetCommDiagnostics();
          startCommDiagnostics();
        }
      }
    }
  }

  var diags: orderedMap(string, Diags);
  proc deinit()  {
    const maxLen = max reduce for k in diags.keys do k.size;
    for (k, v) in diags.items() {
      try! writeln("%s %s: %.2drs".format(k, " "*(maxLen-k.size), v.t.elapsed()));
      // TODO summery
      if printDiags { writeln(v.d); }
    }
  }
}

module SymEntryTest {
  use SymArrayDmap, MultiTypeSymEntry, Diags;

  config const n = 10;
  config const trials = 250;

  proc main()  {

    var D = makeDistDom(n);
    var A: [D] int;
    var S = new SymEntry(n, int);
    for 1..trials {
      diags["Creating array from existing domain"].startStop();
      {
        var A2: [D] int;
      }
      diags["Creating array from existing domain"].startStop();

      diags["Creating array from new domain"].startStop();
      {
        var A2 = makeDistArray(n, int);
      }
      diags["Creating array from new domain"].startStop();

      diags["Creating SymEntry from existing array"].startStop();
      {
        var A2 = new SymEntry(A);
      }
      diags["Creating SymEntry from existing array"].startStop();

      diags["Creating new SymEntry"].startStop();
      {
        var A2 = new SymEntry(n, int);
      }
      diags["Creating new SymEntry"].startStop();

      diags["Creating array from existing SymEntry"].startStop();
      {
        var A2: [S.aD] int;
      }
      diags["Creating array from existing SymEntry"].startStop();
    }
  }
}
```

</details>

And results on 16-node-cs-hdr:

```
chpl SymEntryTest.chpl --fast --no-cache-remote
./SymEntryTest -nl 16

Creating array from existing domain   : 0.12s
Creating array from new domain        : 0.64s
Creating SymEntry from existing array : 0.91s
Creating new SymEntry                 : 1.37s
Creating array from existing SymEntry : 0.12s
```

Where my main takeaway is that creating a new SymEntry seems more expensive than it should (seems like it should be the same speed as creating an array from a new domain) and creating a SymEntry from an existing array also seems slower than it should.

And note that none of these cases have been written with stealing the original array in mind.

**Comment by bradcray** [comment]
Note that this pattern ("I want to refer to some other array, not copy it into my object" is one that @twesterhout has wanted recently, and that others have wanted over the course of the project.

To the question in this issue's title, my answer would be "We should introduce `ref` fields into records and classes and then have them refer to the existing domain/array/etc."  This does have the slight challenge of making sure that the original array lives in a scope where it won't get de-allocated before the object is—is that an issue for this case in Arkouda, do you think?

(if it is, another direction to go would be to create a notion of arrays whose memory is owned vs. borrowed vs. shared...)

**Comment by ronawho** [comment]
I'm not sure `ref` fields help here. When creating a `SymEntry` from an existing array the existing array usually doesn't live much longer (it's normally dead after putting it into a `SymEntry`) and in the case of creating a new `SymEntry` from scratch there's no other array to refer to.

**Comment by mppf** [comment]
@bradcray - with `ref` interpreted as it is today, simply adding `ref` fields is not good enough, since it would not be possible to support the `proc init(size: int, type etype)` `SymEntry` because the newly created domain would be a local variable and be destroyed when the initializer exists (and only a reference to that garbage memory would be left). In principle we could add another field for this case but that would interfere with Elliot's performance goals.

If we had `ref x: domain` as a field mean "make a separate `_domain` value that is a shallow copy", it might work, but it wouldn't always be a shallow copy, because sometimes we want to own and sometimes we want to borrow. So I guess I'm saying that path is a bit fraught and something we'd want to think through before committing to it.

**Comment by mppf** [comment]
Another totally half-baked and maybe too out there idea I had would be to allow people to talk about `owned domain` / `shared domain` etc as a way of disambiguating the sharing/borrowing/owning situation. In particular if we were writing `var x: shared domain` it would not be surprising at all to see reference count bumps.

**Comment by vasslitvinov** [comment]
Another optimization for Arkouda is caching+reuse of distributed domains. That is, have `makeDistDom()` return a previously-created domain of the same size, if there is one. The challenges I see here are * to ensure that the returned domains is const, and * to be able to do this at user level, without relying on the internals.

**Comment by ronawho** [comment]
I have an old branch that tries to cache domains at https://github.com/Bears-R-Us/arkouda/compare/master...ronawho:arkouda:cache-dist-domains?w=1. I never quite got it working, but I can't remember details at the moment.

**Comment by vasslitvinov** [comment]
A related idea is to let users share the identity of an array or domain among multiple variables. For an array, this will be analogous to creating an array slice, except without the special "copy into a fresh array upon return" semantics.
```chpl
var A = createAnArray();
var B = A.share();     // A and B have the same elements and the same meta-data
var B = A: shared;     // an alternative way we could write it
```
Now we can reference an existing array or domain in a non-ref field:
```chpl
record R {
  var D2;
  proc init(const ref D: domain) {
    this.D2 = D.share();
  }
}
```

**Comment by vasslitvinov** [comment]
Elsewhere Engin and Elliot looked at overheads due to privatization, ex. https://github.com/chapel-lang/chapel/issues/20197#issuecomment-1188456538

Here I am looking at overheads due to runtime types. Start with the existing code structure:

```chpl
class SymEntry1 {
  const aD: makeDistDom(size).type;
  var a: [aD] etype;

  proc init(...) {
    this.aD = ...;
    this.a = ...;
  }
}
```

* `const aD: makeDistDom(size).type;` invokes makeDistDom() at runtime because we need to extract the runtime type from its result. Then it throws away that result, i.e., the domain that it produces, and keeps only the distribution object. The initializer will create a new domain using that distribution object. In other words, we get two Block domains instead of just one.

* `var a: [aD] etype;` obligates the field `a` to be an array over the specific domain `aD`. This is what that runtime type means. Therefore the initializer will always create a new array over `aD`. It will never initialize `a` using an existing array.

A simple way out is to declare `a` generic and do away with the `aD` field altogether. Then in the initializer `a` can take over the ownership of another array:

```chpl
class SymEntry2 {
  var a;

  proc init(in a: []) {
    this.a = a;
  }
}
```

I note that in the context of Arkouda this approach will not increase the number of instantiations of the `SymEntry` class. It will make the C names of these instantiations much longer, however.

Turns out we can have both benefits: short C names and taking over the ownership:

```chpl
class SymEntry3 {
  var a = makeDistArr(size);

  proc init(in a: []) {
    this.a = a;         // does not invoke makeDistArr()
  }
}
```

All in all, [this gist](https://gist.github.com/vasslitvinov/6566eb3035151f3314a8f23e2e6eb413) contains two patches that implement this change in Arkouda.

**Comment by mppf** [comment]
> A related idea is to let users share the identity of an array or domain among multiple variables. 

I think it would even be possible to have `=` and copy-initialization of these share the same variable and then replace that variable when it is modified (i.e. use a copy-on-write strategy). The copy-on-write idea is a bit complicated to implement, though, so we could start by just applying this "sharing" optimization to domains that cannot be modified.

**Comment by ronawho** [comment]
@vasslitvinov your gist is similar to optimizations I'm working on. I didn't want to use pragmas, so I removed the `aD` proc and updated the callsites to just call `a.domain`. 

https://github.com/Bears-R-Us/arkouda/compare/master...ronawho:arkouda:remove-aD3 captures this, where the first commit converts callsites to `a.domain`, the second stops storing the domain, and the 3rd switches to using `in` intent to steal. I

**Comment by ronawho** [comment]
Arkouda has been updated in https://github.com/Bears-R-Us/arkouda/pull/1921 to just store the distributed array and not the domain. With that there is no overhead for `SymEntry` creation compared to the underlying Chapel array.
