### ISSUE TITLE
[Feature Request] Method to get underlying type for atomics

### ISSUE THREAD

**Issue by thomasrolinger** [chapel-lang/chapel#20182]
This is a feature request that would allow users to "extract" the underlying type from an atomic type.

For example, if we have `type t = atomic int`, we could determine that the underlying type is `int`. The `isIntType()` procedure currently returns `false` when given `atomic int`. So that could be modified to return `true` in the case of `atomic int`. Another possibility is a separate `isAtomicInt()` procedure, or just a procedure on atomics to return the underlying type

As @lydia-duncan mentioned on Gitter, we can currently do:
```chpl
var x : atomic int;
writeln(x.T : string); // prints int(64)
```
but it was noted that it may not be recommended for production code (i.e., too much in the weeds of implementation).

For my own use case, I would prefer something that would be given the atomic type and returned the underlying type (i.e., `type s = getBaseType(atomic int)`), but I could make due with any of the possibilities mentioned above.

**Comment by cassella** [comment]
You can also get the type out of `x.read().type`.  Maybe there's a way to get at that via `Reflection` without having to instantiate the type?

**Comment by cassella** [comment]
I don't see a way to do it via the `Reflection` module.

If you're willing to use the `T` field, you can do it without instantiating a variable since `T`, a type field, is available directly in the concrete type you're interrogating:

```chapel
writeln(t.T:string);
```
(It seems as reasonable to me to expose that type through a real interface as for arrays to expose `eltType`.)

You'd mentioned in gitter the possibility of running over all atomic types, I imagine like

```chapel
if t == atomic int(64) { ... }
else if t == atomic uint(16) { ...
else if t == atomic real(32) { ...
}
```

I think that would all be determined at compile time, and so be folded away.  You could also write that in your own `getBaseType()` which would probably be easily replaced if one of these features is added.  (Or a family of functions using pattern matching,

```chapel
type t = atomic int(32);

proc getBaseType(type t: atomic int(32)) type { return int(32); }
proc getBaseType(type t: atomic int(64)) type { return int(64); }
/* ... */

writeln(getBaseType(t):string);
```
)

Alas, it doesn't seem like you can query it; `proc getBaseType(type t: atomic ?b) type { return b;}` doesn't compile.

**Comment by thomasrolinger** [comment]
Thanks for the suggestions! I think for my purposes now, I will just make a wrapper around “t.T” where t is a type, since that does what I want.

**Comment by e-kayrakli** [comment]
Is `eltType` an appealing interface here? You can do `.eltType` on an array to get its element type. This is sufficiently similar in my view.

**Comment by lydia-duncan** [comment]
To me, `eltType` implies that it's a collection of things sharing a type.  But it would be nice to have a similar interface

**Comment by bradcray** [comment]
Reading the OP more carefully, I think it's appropriate that isIntegerType() currently returns `false` for `atomic int`.  While it has an integral aspect to its nature, it isn't a plain-old `int(?w)`/`uint(?w)`, which is what I think of that query as telling us.  By analogy, a record with a single integer field has an integer-like nature (and arguably even more of an integer-like nature than atomics), but wouldn't return true for these queries.

As a specific example for why I think the current behavior is appropriate, if I wrote a routine `proc foo(x) where isIntegral(x)`, I think I'd be surprised/frustrated as the author if I had to worry about handling arguments of atomic type to make my routine work properly given that they support different operations.  I also think it's more reasonable to add clauses when such cases are desired (`isAtomic(x) && isIntegral(x.baseType)`) than to have to filter out atomic and sync types from all cases where they're not (e.g., `isIntegral(x) && !(isAtomic(x) || isSync(x))`  I also think there's a reasonable rationale to the user for why it doesn't return true ("it isn't merely an integer").

**Comment by ronawho** [comment]
As part of atomic stabilization for Chapel 2.0 the `T` field is being renamed and stabilized to `valType` in https://github.com/chapel-lang/chapel/pull/22859. This was chosen to match syncs and be similar to `eltType` for arrays and `idxType` for ranges/domains and is expected to be the stable way query the underlying value/base type.

> Alas, it doesn't seem like you can query it; proc getBaseType(type t: atomic ?b) type { return b;} doesn't compile.

This was interesting/surprising to me. I forked this off to https://github.com/chapel-lang/chapel/issues/22860

**Comment by bradcray** [comment]
Just to make sure the net result here is clear to others following this issue, now that #22859 has been merged, you can now query an atomic variable's base type using `x.valType` where `x` is a variable of atomic type, as in the OP.  Thanks for filing this, @thomasrolinger!
