### ISSUE TITLE
`ChapelLocale` module: Deprecate the NUMA LocaleModel

### ISSUE THREAD

**Issue by jeremiah-corrado** [chapel-lang/chapel#20220]
The NUMA Locale Model implementation is unstable and no longer supported. Should it be removed along with related methods in the `locale` interface?

This came up in a recent module review because the `locale.getChildCount()` method (originally created for the NUMA Model) does not mesh with the sub-locale design that is currently being used for gpu's. (i.e. to query the number of gpu's on a locale, one would use `here.gpus.size` instead of `here.getChildCount()`. 

In the future, if a new NUMA Locale model were developed, it would likely do something similar: `here.regions.size` instead of using `getChildCount()`.

**Comment by bradcray** [comment]
At the very least, it should probably be marked unstable.  But most people never throw the `--warn-unstable` flag, so that wouldn't actually help many people avoid it.

**Comment by e-kayrakli** [comment]
For similar things, we thought about issuing a warning at build time, but that might be too transient. We can issue a warning when `printchplenv` is run, or report some things like:

```
CHPL_LOCALE_MODEL: numa (unstable)
```

All that being said, I think we should remove it.

**Comment by jeremiah-corrado** [comment]
Forgot to close this earlier. Was resolved by https://github.com/chapel-lang/chapel/pull/20428
