### ISSUE TITLE
`ChapelLocale` module: Improve the documentation for `locale.hostname` and `locale.name`

### ISSUE THREAD

**Issue by jeremiah-corrado** [chapel-lang/chapel#20223]
The `locale` type provides two methods to query the name of the locale: [`hostname`](https://chapel-lang.org/docs/language/spec/locales.html#ChapelLocale.locale.hostname) and [`name`](https://chapel-lang.org/docs/language/spec/locales.html#ChapelLocale.locale.name); however their difference in behavior is not well documented. 

This can be improved by providing some examples of how each method will behave when used in a few different environments/contexts. For example: oversubscribing on a laptop vs. running on a cluster with various configurations.

**Comment by e-kayrakli** [comment]
We seem to be using `name` in `writeThis`, which makes perfect sense. But do we ever need the string returned by `name` as a Chapel string? Maybe `name` should turn into a non-user-facing helper that `writeThis` uses. I also wonder whether the new IO design will have a way to use `writeThis` or the equivalent that's coming to print things on a string, like `sprintf`. If so, I'd be even more supportive of removing `name` from the Locale interface.

**Comment by jeremiah-corrado** [comment]
Good point, I can't imagine a case where you would be doing anything with that string other than printing it out to the console. So I'd also be in favor of deprecating it and moving towards using IO functionality to get the same information.

Although I'm not sure if `locale.name` is currently the thing being used in locale's writeThis() implementation. 

I'm getting the following behavior on my system:
```chapel
writeln(here.hostname); // Jeremiahs-MacBook-Pro.local
writeln(here.name); // Jeremiahs-MacBook-Pro.local
writeln(here); // LOCALE0
writeln(IO.stringify(here)); // LOCALE0
```

**Comment by bradcray** [comment]
I think of the difference as primarily showing up when there are sublocales.  E.g., I think in the NUMA locale model, `hostname` would always give the UNIX-y thing whereas `name` would give strings like `hostname-0`, `hostname-1`, etc.?  And I think that distinction is interesting enough to potentially be worth preserving rather than deprecating anything.

I realize that GPUs aren't particularly well-suited to string manipulation, but does `name` give anything useful for a GPU sublocale today?

**Comment by e-kayrakli** [comment]
Yeah, `node0-GPU0` is an example.

**Comment by jeremiah-corrado** [comment]
`name` and `hostname` also behave differently for oversubscribed execution. 

For example, running the following with 2 Locales on a single desktop:
```chapel
writeln((Locales[0].name, Locales[1].name));
writeln((Locales[0].hostname, Locales[1].hostname));
```
prints:
```
(machine-name.local-0, machine-name.local-1)
(machine-name.local, machine-name.local)
```

I think this is good reason to keep both for now. Although w.r.t. Engin's comment:
> I also wonder whether the new IO design will have a way to use `writeThis` or the equivalent that's coming to print things on a string, like `sprintf`

Eventually, it would be really nice to provide a formatting option for the `locale` type to select between the above behaviors (in `sprintf` or whatever the function is called). Something like:
```chapel
const name_and_id = sprintf(here, LocaleFmts.name);
const host_name_only = sprintf(here, LocaleFmts.hostname);
```
Which might be cause for deprecating one/both of these functions at that point.

**Comment by bradcray** [comment]
> Which might be cause for deprecating one/both of these functions at that point.

I'm not sure I agree with that.  The routines and their definitions seem pretty short/simple/sweet/straightforward to me ("tell me this specific string-based property of the locale"), whereas requiring a user to use an sprintf equivalent to get at the same information seems pretty roundabout/complex by comparison.

**Comment by bradcray** [comment]
If people were _really_ opposed to keeping both, we could unify on a single `name()` routine that took additional/optional arguments like whether to just give the hostname or the uniquified name, etc.  But personally, I'm not sure the pain of transitioning from a paren-less method/field to a paren-ful method is worth the "gain".  I.e., this feels like an ain't broke / don't fix interface to me (that said, I'm also pretty clearly in the camp of not being offended by the current routines).  I'm definitely on-board with improving the docs as proposed in the title of this issue, though).

**Comment by jeremiah-corrado** [comment]
I'm not opposed to keeping both. I thought it might simplify the interface from a user perspective and get rid of the "why is there a `name` **and** a `hostname` method?" question. But better documentation will also solve that problem.

As a side-note, in [this hypothetical world](https://github.com/chapel-lang/chapel/issues/19893#issuecomment-1168822148)  with a top-level format-to-string function, I think I *would be* in favor of deprecating these methods -- and methods in general -- that return a string with some information about the type (and replacing them with a writeThis/formatThis implementation). This would be for the sake of uniformity across the standard library.  But I guess that point is not super relevant to this discussion, I just thought I'd include it because it relates to Engin's comment about how this interface might evolve with the new IO design.

**Comment by e-kayrakli** [comment]
An alternative: Should `locale.hostname` be deprecated in favor of a standalone `hostname` function in `OS`? It could have the signature:

```chapel
proc hostname(loc=here): string
```

**Comment by bradcray** [comment]
That alternative seems a bit roundabout to me in that (currently, at least) most aspects of introspecting about the system resources associated with a locale are currently through methods on the locale type.  It also makes me worry that people would switch to using `this.name` with various strip/split post-processing to try and determine the hostname if the only thing they saw in the locale module about hostnames was in the name documentation.

Given that I missed the meeting, can someone give me more context:  Was everyone waving pitchforks and torches at these routines?  To me, they seem very innocuous and non-controversial, so in the philosophy of "Let's minimize work for ourselves and changes for our users by not spending effort on things that are good, or at least non-offensive", I'm not seeing a big motivation for changing them.  I'm not even entirely sure how this issue evolved from the title and OP of "let's improve the documentation" to "these routines are in significant need of change."

**Comment by jeremiah-corrado** [comment]
I don't think there was much or any opposition to the current design of these methods during the meeting. If I remember correctly, most of the discussion was aimed at how they should behave when called on a sublocale, or specifically when called on a gpu locale. And I think that discussion ended with the conclusion that the current behavior is ok, but we need to document it more clearly.

> I'm not seeing a big motivation for changing them. I'm not even entirely sure how this issue evolved from the title and OP of "let's improve the documentation" to "these routines are in significant need of change."

I am totally ok with keeping both and just updating the documentation. Most of my thoughts about changing the interface were theoretical and contingent on future changes to the IO design. Apologies if that was not clear or if it muddied the discussion too much.

**Comment by e-kayrakli** [comment]
[Jeremiah said similar things as I was about to click "comment"]

> these routines are in significant need of change.

This is definitely not what I am implying by my comments. But re-reading I realize that my previous comment is too terse and ignores your points above. It was more like a "a-ha I have an idea!" type comment that was clearly rushed. My apologies.

> If people were really opposed to keeping both, we could unify on a single name() routine that took additional/optional arguments like whether to just give the hostname or the uniquified name, etc. But personally, I'm not sure the pain of transitioning from a paren-less method/field to a paren-ful method is worth the "gain".

I agree that this is not the right direction.

---

I don't recall too much of a discussion around this during the meeting. Reading this issue, and bumping into some `.name` implementation issues with the GPU locale model (after the module review meeting) made me think about `hostname` vs `name` is all. I find them a little bit redundant, but not strong enough to argue for interface changes there. Your "Let's minimize work for ourselves and changes for our users by not spending effort on things that are good, or at least non-offensive" is good enough for me to move on.

**Comment by jeremiah-corrado** [comment]
Forgot to close this earlier. Was resolved by: https://github.com/chapel-lang/chapel/pull/20332
