### ISSUE TITLE
Should Chapel require a newer GCC version to build the compiler?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#20232]
The Chapel compiler currently uses C++14 but only GCC 5 is required in [prereqs.rst](https://chapel-lang.org/docs/usingchapel/prereqs.html).

This creates a recurring problem with `dyno` when using enum types (see PRs #20231  #18161  #18133 #19586 #18723 #18722). The problem is that `std::hash` is not defined for enum types in GCC 5.4. This issue [was fixed in C++14](https://www.open-std.org/jtc1/sc22/wg21/docs/lwg-defects.html#2148) but the [GCC documentation](https://gcc.gnu.org/projects/cxx-status.html#cxx14) indicates that only GCC 6.1 or newer has non-experimental C++14 support. We see this problem arise in nightly testing in testing GCC 5.4 or for testing a recent clang when using the GCC 5.4 version of the c++ standard library.

Note that the LLVM project also requires C++14. However [LLVM requires a newer compiler](https://llvm.org/docs/GettingStarted.html#host-c-toolchain-both-compiler-and-standard-library) — in particular, it requires one of these compiler versions:

>  * Clang 5.0
>  * Apple Clang 9.3
>  * GCC 7.1
>  * Visual Studio 2019 16.7

So, should the `prereqs.rst` list a version newer than GCC 5 as the minimum required? If so, should it list GCC 6.1 or GCC 7.1?

**Comment by mppf** [comment]
In terms of OS distributions, since now cmake is required (as of #19565), some older OSes are not that easy to work with since they require a newer cmake. From #20216 :
 >  the main cases here of potential concern are Amazon Linux 2 (EOL June 2023) and Ubuntu 18.04 "Bionic Beaver" (EOL April 2023)

Meanwhile:
 * Ubuntu 18.04 "Bionic Beaver" has GCC 7.5.0
 * Amazon Linux 2 has GCC 7.3.1

So, at a glance, it does not seem to be much more problematic to require GCC 7.1 in order to build the Chapel compiler.

**Comment by mppf** [comment]
@ronawho - I'm interested in your thoughts on this, thanks.

**Comment by bradcray** [comment]
I'm also interested in Elliot's input since he does a lot of portability-related work on systems that may have older gcc's.  But absent that information, it wouldn't make me nervous to bump to something newer than gcc 5, and following LLVM's guidance seems reasonable to me (and also represents a fairly modest change).

**Comment by mppf** [comment]
Just noting that we might be able to use C++17 features in the compiler if we required GCC 7.1 and clang 5 to match LLVM:
 * https://clang.llvm.org/cxx_status.html shows that clang 5 has C++17 support
 * https://gcc.gnu.org/projects/cxx-status.html#cxx17 shows that GCC 7.1 has nearly complete C++17 support (it looks like just one row, "Template argument deduction for class templates", needs GCC 8).

**Comment by ronawho** [comment]
I'm not strongly opposed to bumping to gcc 7. By and large the HPC systems I tend to run on either only have one really old gcc version or there are fairly new versions that can be brought in with modules. It's pretty rare to be on a system that only has moderately old versions.

I expect our other prereqs (in particular requiring a newer cmake) either means users will already have a newer gcc or they'll have figured out some way to install software themselves. (Just anecdotally it's the cmake requirement that made things more inconvenient for me. For most external systems I just defaulted to `CHPL_LLVM=none` before and it was pretty rare to find a system that I couldn't build out of the box on. Nowadays I almost always end up just spack installing prereqs. It's mildly annoying to have to wait and usually fix some spack issue, but I think we're making the right choice between enabling features we want/need to develop vs making things more burdensome to build.)

I guess personally I'd lean towards matching the prereqs llvm requires and if/when this becomes a burden for users we can focus more on binary releases or spack formulae to build or something.

**Comment by DanilaFe** [comment]
In #20452, we updated the prerequisites documentation to require GCC 7.1 / Clang 5.0 / Apple Clang 9.3 to match LLVM. We don't strictly enforce these requirements anywhere, nor do we use newer features from these compilers (like C++17). However, after 1.28 we expect to be more strict about the dependency.
