### ISSUE TITLE
I/O module: deprecating ioBits

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#20258]
This issue is about this IO module type `ioBits`:

``` chapel
record ioBits {
  /* The bottom 'nbits' of v will be read or written */
  var v:uint(64);
  /* How many of the low-order bits of 'v' should we read or write? */
  var nbits:int(8);
}
```

This type can currently be used with read/write/<~> to read or write a particular number of bits as binary data.

The proposal here is to deprecate this type favor of the existing `readbits` and `writebits` methods which are more obvious. (see the documentation for these at https://chapel-lang.org/docs/modules/standard/IO.html#IO.channel.readbits ).

**Comment by bradcray** [comment]
For anyone else for whom it gave pause, note that read/writebits are likely to change to read/writeBits:  https://github.com/chapel-lang/chapel/issues/19494

**Comment by lydia-duncan** [comment]
In the IO re-review on Oct 4th, we decided to deprecate this type in favor of the readBits and writeBits methods:

Voting (replace ioBits with new routines):
    - 10 in support
