### ISSUE TITLE
I/O module: replacing ioChar with writeCodepoint etc

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#20257]
This issue is about this IO module type

``` chapel
record ioChar {
  /* The codepoint value */
  var ch:int(32);
}
```

Currently, this type can be used with read/write/<~> to read or write a particular Unicode codepoint.

The proposal here is to deprecate this type in favor of the following new routines which are more obvious:

``` chapel
// note: all of these routines will ignore the channel’s Encoder/Decoder

proc writer.writeCodepoint(codepoint: int) throws
proc reader.readCodepoint(): int throws
proc writer.writeByte(byte: uint(8)) throws
proc reader.readByte(): uint(8) throws
```

These are a bit redundant with writeBytes/writeString etc. but would perform much better. (But, that could be less important if we have the short-string optimization #11221).

**Comment by bradcray** [comment]
I'm not necessarily opposed to this proposal, but grepping the tests, `ioChar` doesn't seem to be in much use currently.  Should we consider just deprecating it and keeping the option open to add these later on demand (or to do the short-string optimization at that point?)

**Comment by mppf** [comment]
They are trivial to implement because the C code implementing Qio already has them. And I don't think that the names are so contentious that we need to put off adding them because it would be to hard to do the API design... Anyway I think that having *some way* to read or write a byte or codepoint is something people will expect of a complete I/O system (especially for people coming from C). AFAIK we can use readf/writef with `%c` to read/write Unicode characters and `readbits` / `writebits` to read/write a byte (by specifying 8 bits) but both of those functions are way more complicated than needed for this use case (so, I expect, would have poor performance in comparison to something more direct).

**Comment by bradcray** [comment]
> They are trivial to implement because the C code implementing Qio already has them. And I don't think that the names are so contentious that we need to put off adding them because it would be to hard to do the API design

This part of the argument doesn't quite hold up to me because anything we can do to reduce the amount of code we need to write, support, and document seems attractive, even if the code already exists.  I agree that the names seem obvious/straightforward.

> Anyway I think that having some way to read or write a byte or codepoint is something people will expect of a complete I/O system

This holds up better for me, though I'm not in the target audience, so would just have to take your word for it.

**Comment by lydia-duncan** [comment]
In the IO module re-review on October 4th, the team decided to replace ioChar with those new routines:

Voting (replace ioChar with new routines):
    - 11 in support

**Comment by jabraham17** [comment]
Based on discussion offline in slack, the team will also implement
```chapel
proc fileReader.readCodepoint(ref c: int):bool throws
proc fileReader.readByte(ref b: uint(8)):bool throws
```
This matches other fileReader functions which have methods which either return a value or set a ref variable
