### ISSUE TITLE
I/O module: file.close

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#20254]
This issue is about this existing IO module method:

``` chapel
proc file.close() throws
```

The proposal here is to keep it as-is but this issue is the place to discuss any changes to it.

**Comment by mppf** [comment]
should it throw?
 * if you need to know your data made it to disk you have to call file.fsync anyway
 * not really clear how one could respond to a failure to close a file

However, the underlying C calls / system calls can return errors. So having it continue to be able to throw seems the most faithful to that.

**Comment by mppf** [comment]
What errors can the `file.close` system call throw? Here is some information about what the underlying C / OS calls do

```
(fclose) EBADF The file descriptor underlying stream is not valid.
(fclose calling write or fflush) many errors
(close) EBADF fd isn't a valid open file descriptor.
(close) EINTR The close() call was interrupted by a signal; see signal(7).
(close) EIO An I/O error occurred.

```

**Comment by benharsh** [comment]
After some discussion the IO subteam has decided that ``file.close`` is now stable. We believe the only outstanding issue can be considered a bug or request for improving an error message, which is now tracked here: https://github.com/chapel-lang/chapel/issues/22280
