### ISSUE TITLE
I/O module: file.fsync

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#20255]
This issue is about this IO module method

``` chapel
proc file.fsync() throws
```

The proposal here is to keep it as-is but this issue is the place to discuss any changes to it.

**Comment by mppf** [comment]
In terms of the name `fsync`, this is the name that C uses for the operation, and it's fairly low level so keeping that name seems OK.

**Comment by lydia-duncan** [comment]
I think it's reasonable to close this issue now, since there hasn't been further discussion on it
