### ISSUE TITLE
Methods can be defined on variables

### ISSUE THREAD

**Issue by ghbrown** [chapel-lang/chapel#20259]
### Summary of Problem
Methods can be defined on variable instances of records, but you should only be able to define them on types.

### Steps to Reproduce
Brad's minimal working/failing example given on the Discourse:
```chapel
record R {
}

var myR: R;

// this is OK, since R is a type
proc R.foo() {
  writeln("In foo()");
}

// this shouldn't be OK, myR is a value
proc myR.bar() {
  writeln("In bar()");
}

myR.foo();
myR.bar();
```

**Compile command:**
`chpl`

### Configuration Information
using packaged version on Arch
```
chpl version 1.28.0 pre-release (c95e180325)
built with LLVM version 14.0.6
```

**Comment by bradcray** [comment]
Thanks for filing this, @ghbrown!

**Comment by bradcray** [comment]
I've got an attempted fix for this that I'm currently putting through testing.

**Comment by ghbrown** [comment]
Awesome, thanks for the support and quick turnaround!
