### ISSUE TITLE
I/O Module: Deprecate ``file.check`` in favor of isClosed/isOpen

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#20266]
This issue concerns the method ``file.check``:

```chpl
proc file.check() throws
```

This method is mostly used internally at the beginning of methods to throw an error if the file is closed or in an invalid state. In practice, users are more likely to desire a boolean-returning method that indicates whether the file is open or closed.

We should deprecate this method in favor of a boolean-returning method [once we decide on a name](https://github.com/chapel-lang/chapel/issues/20153).

**Comment by lydia-duncan** [comment]
In the IO module re-review, the team decided to deprecate this function and replace it with `file.isOpen()`

Voting:
    - isOpen: 10
    - both isOpen and isClosed : 4

**Comment by lydia-duncan** [comment]
This was resolved by #21435
