### ISSUE TITLE
no-local GPU: Can't compile select statements with module-scope bytes constants as cases

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#20276]
This is probably too much of an edge case for our GPU support as of today. However, it prevents bare-bones Arkouda compilation with GASNet and most likely other comm layers, too.

Here's a reproducer:

```chpl
const b1 = b"foo";
const b2 = b"bar";

config var b = b1;

select b {
  when b1 do
    writeln("b1");
  when b2 do
    writeln("b2");
}
```

With CHPL_COMM=none, this compiles. It fails if I throw in `--no-local`.

What's curious is that there is nothing asking for GPUs or kernel launches here.

**Comment by e-kayrakli** [comment]
To add more in the direction of how one might attempt to fix this: It looked too similar to some of the linkage issues we wrestled with in https://github.com/chapel-lang/chapel/pull/20016, in that there were missing symbols in `lvt`. That made me wonder, whether there are issues with the [`shouldHandleDecl`](https://github.com/chapel-lang/chapel/blob/main/compiler/llvm/clangUtil.cpp#L1309-L1319) logic or the places where it is used.

A good first step can be to change that function to always return `true` and see if the behavior changes. If it does, we need to figure out why that function returns `false` for those module-scope constants.

**Comment by stonea** [comment]
This is erroring out on the GPU invocation of `codegenPart2`. Specifically erroring with this stack trace:

```
llvm::Value::getType Value.h:246
llvm::IRBuilderBase::CreatePointerCast IRBuilder.h:2204
genGlobalSerializeTable codegen.cpp:1418
codegen_defn codegen.cpp:1474
codegenPartTwo codegen.cpp:2645
codegen codegen.cpp:2726
runPass runpasses.cpp:212
runPasses runpasses.cpp:174
main driver.cpp:1885
__libc_start_main 0x00007fffef236083
_start 0x00005555555b110e
````

The `genGlobalSerializeTable` is processing this CallExpr:

```
(1766759 CallExpr
  (1766760 SymExpr 'fn chpl__broadcastGlobal[1596820]:void[4]')
  (1766761 SymExpr 'const-val b1[182636]:bytes[24]')
  (1766762 SymExpr 0 'val _literal_1[37]:int(64)[13]'))
```

`b1` has cname `b1_chpl` and for whatever reason that's not in the `lvt`.

In the PR to enable GASNET with `CHPL_LOCALE_MODEL=gpu` (https://github.com/chapel-lang/chapel/pull/19857) we exempted the generation of the "broadcastTable". See here: https://github.com/chapel-lang/chapel/blob/0085fba89a2160b9c2383613c4687f659cb6d50e/compiler/codegen/codegen.cpp#L1968

Should we do the same here?  The program will pass and work if I apply this easy "fix", of changing the call to `genGlobalSerializeTable(info);` in `codegen_defn` (in `codegen.cpp`) to:

```C++
  if(!gCodegenGPU) {
    genGlobalSerializeTable(info);
  }
```

@e-kayrakli can you remind me what the "broadcast table" is and comment on if you think we'll need to enable it in the GPU invocation of `codegenPartTwo` in the long run?

**Comment by e-kayrakli** [comment]
My understanding of the broadcast table is that it is a per-locale table that stores some "global" variables copied across locales. And the serialize table is... for non-POD things that we broadcast through serialization/non-serialization, ie string/bytes (?).

Your quick fix sounds reasonable to me with the same motivation that we hope that we won't need to serialize/deserialize things inside GPU kernels but rather `on` statements that target GPU sublocales (which will be done by the CPU). I am not super-confident in this assessment, but if adding that check looks quite similar to what we have already, and if it passes testing I am fine with that solution for the time being.

**Comment by stonea** [comment]
I'll pick this up to apply the "quick" fix.

> My understanding of the broadcast table is that it is a per-locale table that stores some "global" variables copied across locales. And the serialize table is... for non-POD things that we broadcast through serialization/non-serialization, ie string/bytes (?).

I want to understand what this broadcast/serialize tables are a little bit more though (just in case there's some other issue I should be spawning off from this).

When you say "global" variables are you referring to user (say module level) variables or are these some kind of special variables introduced by the compiler?

If you modify one of these variables won't you need to re-broadcast it everywhere, how do we prevent race conditions?  I guess the idea is these are things that are frequently read but rarely written to?

Any suggestions on how to reach out to if I have more questions (@bradcray or @mppf I guess?)

**Comment by e-kayrakli** [comment]
Probably @ronawho and @benharsh knows about this better than I do.

**Comment by benharsh** [comment]
I'd have to check, but I suspect that we're mainly broadcasting wide pointers to mutable globals. If those globals are constant, then we can probably use the serialization tables (if the type supports serialization).

**Comment by stonea** [comment]
> I'd have to check, but I suspect that we're mainly broadcasting wide pointers to mutable globals. If those globals are constant, then we can probably use the serialization tables (if the type supports serialization).

I see.  If that's the case then I suppose with something like this:

```chpl
var myGlobalVariable = new MyClass();
const myGlobalConst = MyRecord(...)

proc main() {
  on Locales[1].gpus[0] {
    foreach i in 0..0 {
      use(myGlobalVariable);
      use(myGlobalConst);
    }
  }
}
```

Where the body of that `foreach` loop is going to be converted into a GPU kernel we would also want to get that wide pointer for `myGlobalVariable` broadcasted to the GPU and the serialized version of `myGlobalConst` as well?

I suppose as of today we currently don't support the use of global variables/consts in the GPU anyway so exempting `genGlobalSerializeTable` when `gCodegenGPU==true` should be a safe thing to do until we want to lift that restriction.

**Comment by bradcray** [comment]
> I'd have to check, but I suspect that we're mainly broadcasting wide pointers to mutable globals. If those globals are constant, then we can probably use the serialization tables (if the type supports serialization).

I'm pretty sure that, for module-scope constants (or possibly "module-scope constants of sufficiently simple type"?), we broadcast the value of the constant to each locale after program initialization so that no communication is required to look at it.  I don't remember what the role of a table was for this feature, though (but could look more if/when needed).

Also, to your question about "global" in this context:  I think most of us use that term colloquially to refer to module-scope variables (and the code base may as well), but I think "module-scope" is a better term in most contexts.  I'm hard pressed to come up with any variables in Chapel that are truly global (though arguably, for cases defined in an internal or always-`use`'d module, perhaps nobody would be able to tell the difference...?).
