### ISSUE TITLE
Should classes be `shared` rather than `owned` by default?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#20278]
In recent discussions, users (and developers) have expressed that `owned`
can be a confusing default for classes relative to `shared` from a productivity
perspective given their ownership transfer nature, lifetime checking, etc.  We
discussed and dismissed this idea when introducing the class management
flavors, but  ended up shying away from it due to performance concerns.
However, with additional time and reflection, it occurs to me that it wouldn't be
the first instance in which Chapel would be easy to use by default, and requires
more expertise to get better performance (the `--fast` flag and its implications
relative to the default being a similar, but different, theme).

This issue asks: Should we reconsider this decision prior to Chapel 2.0?

**Comment by mstrout** [comment]
In a January 10, 2023 module re-review meeting, the team voted 15 to 0 to keep `owned` as the default memory management strategy.  Below are some notes about this.

Based on a recent hackathon within the team, we found ...

- ‘owned’ is noticeably faster than ‘shared’ even in a non-parallel setting
- ‘shared’ can lead to memory leaks in the presence of cycles
- Many team members felt ‘owned’ and ‘shared’ had similar usability 

Recent comments from Brad

- People were able to use 'owned' without too much difficulting
- Difficulties were relatively independent of 'owned'
  - E.g., needing 'in' intent to give a class to an initializer [and to transfer ownership]
- Rule of thumb: don't use generic class form for fields
- Increased awareness of performance impact of 'shared' and the fact that cycles aren't handled with 'shared'
