### ISSUE TITLE
TaskErrors docs examples don't work

### ISSUE THREAD

**Issue by bmcdonald3** [chapel-lang/chapel#20289]
In https://chapel-lang.org/docs/language/spec/error-handling.html#coforall-and-cobegin, the code snippet for `coforall` `TaskErrors` does not run.

With a slight modification (so we don't need `DemoError`:
```
try! {
  writeln("before coforall block");
  coforall i in 1..2 {
    coforall j in 1..2 {
      throw new owned Error();
    }
  }
  writeln("after coforall block");
} catch errors: TaskErrors {
  for e in errors {
    writeln("Caught task error e ", e.message());
  }
}
```

Results in:
```
asd.chpl:12: error: unresolved call 'owned Error?.message()'
```

And a `!` needs to be added to `e.message()` to get it to run.

Edit: just noting that this was causing confusion for a user (and myself)

**Comment by bradcray** [comment]
@bmcdonald3 : By any chance are you implementing a fix to this?  (he asked hopefully).

**Comment by bmcdonald3** [comment]
@bradcray sure, I can fix this today.
