### ISSUE TITLE
Map module - should we rename the set method?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#20323]
The current `set` method on the map type is implemented like this:
```chapel
/*
  Sets the value associated with a key. Method returns `false` if the key
  does not exist in the map.

 :arg k: The key whose value needs to change
 :type k: keyType

 :arg v: The desired value to the key ``k``
 :type k: valueType

 :returns: `true` if `k` was in the map and its value is updated with `v`.
           `false` otherwise.
 :rtype: bool
*/
proc set(k: keyType, in v: valType): bool {
  _enter(); defer _leave();
  var (found, slot) = table.findAvailableSlot(k);
  if !found {
    return false;
  }

  table.fillSlot(slot, k, v);

  return true;
}
```
I was expecting the map to be updated at `k`, and that the boolean would indicate whether the element already existed.  However, it looks like in the discussion [in this thread](https://github.com/chapel-lang/chapel/pull/13624#discussion_r310325123) it was intentional that we distinguished it from the behavior of `[k] =` (though that's less strong of an argument, since the latter is currently not supported in a parallel context).  In [this comment](https://github.com/chapel-lang/chapel/pull/13624#issuecomment-517490461) which lists some precedent for the type in other languages, it looks like it is equivalent to Java's `replace` method.  I think `replace` would be a better name for what it is currently doing.

Note that the `list` type also has a `set` method that behaves similarly, though in that case the failure is due to updating outside of the current bounds so it is a bit more expected imo.  Still, for consistency, I would be willing to argue for renaming it to `replace` there, too.

**Comment by bradcray** [comment]
I agree that `replace` or `update` seems a little more intuitive of a name for this behavior that won't do anything if the element doesn't already exist.  I.e., my intuition would also be that `set` would add it if it doesn't exist rather than just giving up and returning false.  I looked briefly at the linked issue, but didn't come away with a clear view of what Python, Swift, Julia, or Rust would call this method, if they have it.

**Comment by lydia-duncan** [comment]
In our meeting on Tuesday, we votes on whether to rename this method.  The vote was
- 5 in favor of renaming to replace 
- 0 in favor of leaving it as is
