### ISSUE TITLE
Memory.Initialization: moveInitialize function signature

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#20328]
The current signature of ``moveInitialize`` is:

```chpl
proc moveInitialize(ref lhs,
                     pragma "no auto destroy"
                     pragma "error on copy" in rhs)
```

There are a couple of changes we should consider making here:

### Formal Names: src/dst

We are currently using the formal names ``lhs`` and ``rhs``, but this seems inconsistent with the choice of ``src`` and ``dst``/``dest`` elsewhere. Should we make this change here as well?

### Two functions for better error messages

Currently the formals for this function are fully-generic. ``moveInitialize`` will compare the static types and if they differ will issue a ``compilerError`` with a nice message. The documentation says:

```
:arg lhs: A variable to move-initialize, whose type matches ``rhs``
```

But that text might be easy to gloss over, and a user might expect the function signature to present that information.

One way of dealing with this issue could be to create two separate functions: one with type constraints and one without. The fully-generic function would always issue a compilerError, relying upon function resolution to know that the types are mismatched:

```chpl
pragma "no doc"
proc moveInitialize(ref lhs,
                     pragma "no auto destroy"
                     pragma "error on copy" in rhs)

proc moveInitialize(ref lhs : ?T,
                     pragma "no auto destroy"
                     pragma "error on copy" in rhs : T)
```

I would recommend no-doc-ing the compilerError version.

Alternatively, we can try to invest some time in getting the compiler to generate a nicer error message for simple cases like this one that involve type queries...

### "error on copy"

This pragma exists to capture the case where the compiler inserts a copy for the ``rhs`` argument, when what we really want is for the compiler to have 'moved' the argument in for us. This is useful behavior that can prevent problems for the user, but this behavior is currently undocumented.

How should we go about explaining the behavior here when the cause (the pragma) is invisible in documentation? Should 'chpldoc' do something for us? Or is it enough to mention some special compiler-assisted error checking?

### Return type

We should specify the return type as ``void``.

**Comment by vasslitvinov** [comment]
I propose the following for the public interface:
```chpl
proc moveInitialize(ref dest : ?T, in src: T): void
```
with chpldoc explaining that copying the `src` argument at the callsite causes a compilation error, hopefully with a brief rationale.

Implementation-wise, creating an error overload that catches the case dest.type != src.type is a good idea.

Let us think whether we want to allow moveInitialize() to be amenable to promotion. Having a catch-all error overload would interfere with that. (potentially related: #16216 #19261)

**Comment by mppf** [comment]
> One way of dealing with this issue could be to create two separate functions: one with type constraints and one without. 

Works for me

> How should we go about explaining the behavior here when the cause (the pragma) is invisible in documentation? Should 'chpldoc' do something for us? Or is it enough to mention some special compiler-assisted error checking?

I think it's enough to simply state in the chpldoc for moveInitialize that the compiler does this check for calls to the function.

**Comment by bradcray** [comment]
> We are currently using the formal names lhs and rhs, but this seems inconsistent with the choice of src and dst/dest elsewhere. Should we make this change here as well?

This sounds good to me.  I'd personally probably choose `dst` over `dest` for symmetry and because `src` similarly compresses out the initial vowels, so it seems symmetrical in length and approach.  I.e., why not use `sorc` or `sourc`?  :D  That said, I'm not deeply against `dest` and am not actually proposing we use something other than `src`.

> One way of dealing with this issue could be to create two separate functions: one with type constraints and one without.

Like others, I'd be fine with this and generally appreciate when we do generate such error overloads.  That said, your point about investing more effort in compiler errors also resonates with me from the perspective of "We could spend lots of time creating wonderful error overloads... where to stop?"

**Comment by benharsh** [comment]
If we use a type-query to constrain the formals here, would we run into issues with coercions? Especially user-defined coercions? Is possible for the ``src`` to coerce to the ``dst`` type in a way that makes move-ing invalid? I'm struggling to think of a practical example at the moment, but I still think this could be an issue (unless we have some way of specifying that the actual should not coerce to the formal type).

By accepting the formals as fully-generic there will be no coercion and we can do a compile-time check of the original static types.

**Comment by bradcray** [comment]
Those are interesting questions and I don't feel like I know the answer offhand, though my guess is that you're correct.  Is it the case that we always want the two types to match exactly, or are there some cases where slight mismatches are OK? (e.g., child/parent class?  or is moveInitialize simply overkill for that case and so shouldn't be supported?)

By "fully generic" I assume you mean we could write something like:

```chapel
proc moveInitialize(ref lhs : ?T,
                     pragma "no auto destroy"
                     pragma "error on copy" in rhs : ?T2) where T1 == T2
```

or perhaps:

```chapel
proc moveInitialize(ref lhs,
                     pragma "no auto destroy"
                     pragma "error on copy" in rhs) where lhs.type == rhs.type
```

is that right?  If so, I still have a slight preference for the type query form, but either is still acceptable to me.

Could we change the `rhs` to `const ref` to avoid the coercion, or do we need it to be `in` to imply that it's consuming the value in some way?  (sorry, I feel like I'm shooting in the dark here a bit due to lack of expertise with the routines, but don't want to leave you hanging).

**Comment by benharsh** [comment]
Either the query-form or the ``.type`` form would work, I think.

We want the ``rhs``/``src`` to be 'in' to take advantage of the compiler's innate ability to move expiring values when passed to an in-intent. There's also some nice error checking that the "error on copy" pragma provides in this case.

**Comment by mppf** [comment]
Supposing it was passed two different types that did an implicit conversion, the operation could still work, but where it would be confusing is that `moveInitialize` would do more than just move initialize and you might end up with something like a copy (because a lot of the implicit conversions create a copy of the value). So, I think trying to make sure that the types match exactly when calling this function is appropriate. I don't have any strong preference for how to go about doing that.

**Comment by benharsh** [comment]
Thanks for the input! I'm going to propose the following:

```chpl
proc moveInitialize(ref dst : ?DT,
                    pragma "no auto destroy"
                    pragma "error on copy" in src : ?ST) where DT == ST
```

Summary:
- formal names become ``dst``/``src``
- Use type queries and where-clause to constrain, as opposed to internal compiler error
- Documentation for this function will explain the "error on copy" behavior

Please vote 👍 to indicate support, and 👎 if you think there are other questions to resolve.

-----

With a relatively simple signature/where-clause like this, I believe we could still issue some nicer error messages. A similar function named foo, given an int and a real, would incur a resolution error like this in the production compiler:
```
foo.chpl:7: In function 'main':
foo.chpl:10: error: unresolved call 'foo(int(64), real(64))'
foo.chpl:2: note: this candidate did not match: foo(ref dst: ?DT, in src: ?ST)
foo.chpl:2: note: because where clause evaluated to false
```

I think it would be possible to add an extra line about the expectation that ``DT`` and ``ST`` should match.

Some follow-up questions/observations:
- chpldoc does not appear to include where-clauses today: should it? Do we have an issue for this already?
- Should we have a way for formals to indicate that coercion is not permitted? Arguably this is a rather special case, so I'm fine with not having that functionality.
- Should we provide a way for function authors to provide some nicer error message when a where-clause does not match? I have no idea what that would look like, but the compiler isn't going to be smart enough to handle everything. An alternative would be to make where-clauses more publicly visible, both in chpldoc and in compiler error messages.

**Comment by mppf** [comment]
> chpldoc does not appear to include where-clauses today: should it? Do we have an issue for this already?

I think it should. I don't know of an issue off-hand. For now you can describe the constraint in words in the docs comment.

> Should we have a way for formals to indicate that coercion is not permitted? Arguably this is a rather special case, so I'm fine with not having that functionality.

I don't think that's necessary (or, at least, not necessary yet).

> An alternative would be to make where-clauses more publicly visible, both in chpldoc and in compiler error messages.

IMO this would be fine. It could add something like this:
```
foo.chpl:2: note: because where clause evaluated to false
foo.chpl:2: note: where clause was DT == ST with DT=int and ST=real
```

**Comment by lydia-duncan** [comment]
> * chpldoc does not appear to include where-clauses today: should it? Do we have an issue for this already?

#5950

**Comment by bradcray** [comment]
@benharsh : What do you think about changing the type queries from DT and ST to dt and st?  (rationale:  we don't use many all-caps names in Chapel; they're not well-established abbreviations like IO or OS; they're more likely to be records/values than classes (right?), and records are usually lowercase in Chapel)

**Comment by benharsh** [comment]
I have a slight preference for capitalization in this case, but I don't feel strongly about it and would be fine changing to lowercase if that had more consensus.

My slight preference is entirely subjective here, preferring ``T`` to ``t`` in general. I don't have any justification here, just personal preference.

**Comment by mppf** [comment]
Seems like something we could establish a convention for in the standard module style guide: `proc f(argument: ?t)` vs `proc f(argument: ?T)`. It might seem trivial but I think it'd be worth spinning off to its own issue.

**Comment by vasslitvinov** [comment]
> `proc moveInitialize(ref dst : ?DT, in src : ?ST) where DT == ST`

How about dropping the where clause and instead reporting a compilerError in the body of `moveInitialize` ?

```chpl
proc moveInitialize(ref dst : ?DT, in src : ?ST) {
  if DT != ST then compilerError("'dst' and 'src' must be of the same type");
  ......
}
```

**Comment by vasslitvinov** [comment]
Do we want to introduce an overload where `src` is passed by `[const] ref` ?
```chpl
proc moveInitialize(ref dst : ?DT, in src : ?ST) {...}
```
Or is it important to have the user add an explicit `moveFrom` at the callsite?
```
moveInitialize(lhs, moveFrom(rhs));  // why not just moveIniitalize(lhs, rhs) ?
```

**Comment by mppf** [comment]
> Do we want to introduce an overload where `src` is passed by `[const] ref` ?
> 
> ```chapel
> proc moveInitialize(ref dst : ?DT, in src : ?ST) {...}
> ```
> 
> Or is it important to have the user add an explicit `moveFrom` at the callsite?
> 
> ```
> moveInitialize(lhs, moveFrom(rhs));  // why not just moveIniitalize(lhs, rhs) ?
> ```

This function has `pragma "no auto destroy" pragma "error on copy" in rhs` and the purpose of this is to have the compiler check that the RHS/src is something that is already a dead value. If we combine the two, we will lose the ability to do that checking.

**Comment by benharsh** [comment]
> > `proc moveInitialize(ref dst : ?DT, in src : ?ST) where DT == ST`
> 
> How about dropping the where clause and instead reporting a compilerError in the body of `moveInitialize` ?
> 
> ```chapel
> proc moveInitialize(ref dst : ?DT, in src : ?ST) {
>   if DT != ST then compilerError("'dst' and 'src' must be of the same type");
>   ......
> }
> ```

I suppose part of the error message text will be the compiler informing the user whether a call resolved or not.

Are we only supposed to use where-clauses in cases where something else could/should resolve? Should we always be able to resolve ``moveInitialize`` with two types, and then issue a compilerError for incorrect usage of the function? Feels like a stylistic choice here...

**Comment by benharsh** [comment]
> Seems like something we could establish a convention for in the standard module style guide: `proc f(argument: ?t)` vs `proc f(argument: ?T)`. It might seem trivial but I think it'd be worth spinning off to its own issue.

Opened here: #20444

**Comment by bradcray** [comment]
> Feels like a stylistic choice here...

I tend to agree that this feels like a stylistic choice where tradeoffs include:
* code maintenance issues (preferring multiple shorter routines vs. one more monolithic routine)
* documentation approaches (though it seems we often "no doc" additional overloads when using where clauses, particularly if they're for errors)
* potential compilation time tradeoffs

Generally speaking, I think I tend to prefer a single routine containing cases over multiple overloads with where clauses, but not enough to insist everyone do it or that it's best for all cases (and am confident I've written plenty of both).

**Comment by benharsh** [comment]
In returning to this issue I find myself leaning more towards the ``compilerError`` approach. At the moment we do not have the nicer errors for the ``where``-clause-only case. We aren't currently generating ``chpldoc`` for where-clauses either, which mitigates the usefulness of the multiple-overloads case.

We might have these things someday, and may develop a general stylistic rule for situations like this. In the meantime I think it's more useful to get the formal name changes in and simply add a ``.. note::`` to the chpldoc for this function to clarify the relationship between the ``dst`` and ``src`` types. Otherwise, unless I'm mistaken, the where-clause business will only affect the error text that the user sees if invoking this function incorrectly. If we change to where-clauses later, it should not affect how users interact with this function beyond improving errors and documentation.

I feel like we can open a separate issue to discuss our conventions in this regard.

-----

And so, I propose the following:
- Add chpldoc to clarify that ``dst`` must equal ``src``
- Add chpldoc to explain "error on copy" behavior
```chpl
proc moveInitialize(ref dst : ?dt, 
                    pragma "no auto destroy"
                    pragma "error on copy" in src : ?st) {
  if dt != st then compilerError("'dst' and 'src' must be of the same type");
  ......
}
```

Issues to decide later (pre-2.0):
- Capitalization of "dt" and "st"
- General conventions for compilerErrors vs where-clauses.

Please vote 👍 if you support this plan.
Please vote 👎 if you support something else (e.g. where-clauses)
Please vote 🚀 if you want to see a dedicated issue for compilerErrors vs where-clauses.

**Comment by vasslitvinov** [comment]
I agree that we can start with the "compiler error" version and switch to the "where clause" version later. Especially given that chpldoc does not show where-clauses. Which it probably shouldn't, as we sometimes use where-clauses as an implementation strategy rather than an interface matter.

I prefer T over t for a type variable, perhaps with the rationale that lower-case variables are for values whereas upper-case variables are for types. However given the trend to the lower case in cases like this one, I am OK with it as well.

**Comment by mppf** [comment]
> And so, I propose the following:
> 
>     * Add chpldoc to clarify that `dst` must equal `src`

I think you mean to say that they must have the same types?

>     * Add chpldoc to explain "error on copy" behavior
> 
> 
> ```chapel
> proc moveInitialize(ref dst : ?dt, 
>                     pragma "no auto destroy"
>                     pragma "error on copy" in src : ?st) {
>   if dt != st then compilerError("'dst' and 'src' must be of the same type");
>   ......
> }
> ```

I don't understand why the signature needs `?dt` and `?st` at all. The check could use `dst.type != src.type`. That would remove the need to figure out this:

> Issues to decide later (pre-2.0):
> 
>     * Capitalization of "dt" and "st"

It seems reasonable for `chpldoc` to print out `where` clauses, if we have a way to opt in / opt out. But, I think that is definitely a separate issue.

**Comment by benharsh** [comment]
Resolved by https://github.com/chapel-lang/chapel/pull/21087
