### ISSUE TITLE
Memory.Initialization: moveSwap function signature

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#20334]
The current signature of ``moveSwap`` is:

```chpl
proc moveSwap(ref lhs: ?t, ref rhs: t)
```

There are some minor issues regarding the function signature:

### Return Type

We should explicitly state the return type is ``void``.

### Formal Names

``lhs`` and ``rhs`` Don't really make sense in this context, as they somewhat imply a direction. Rust uses ``x``/``y`` for its swap functions formal names, and C++ uses ``a``/``b`` in ``std::swap``. I propose using ``x``/``y``.

### Error message

We could use a similar tactic as proposed in (#20328) where we have a second generic ``moveSwap`` function that accepts fully-generic arguments and issues a ``compilerError``. At this point though, I wonder if we could do something a bit nicer within the compiler itself for trivial cases like ``X : ?T, Y : T``.

**Comment by vasslitvinov** [comment]
I vote for `proc moveSwap(x: ?T, y: T)`

Interesting thought about compiler support for cases like this. Maybe what we have is already sufficient and we indeed do not need the catch-all error overload?

```chpl
proc moveSwap(x:?t, y:t){}

var a: uint(8);
var b: int;
moveSwap(a,b);
```
gives me:
```
error: unresolved call 'moveSwap(uint(8), int(64))'
note: this candidate did not match: moveSwap(x: ?t, y: t)
note: because actual argument #2 with type 'int(64)'
note: is passed to formal 'y: uint(8)'
```

This does not affect our interface discussion, however.

**Comment by benharsh** [comment]
Huh.. I thought I checked and received a less helpful error. Perhaps I was on an experimental dyno branch?

It still might be useful to say something a bit more natural like "formals 'x' and 'y' must have the same type".

**Comment by bradcray** [comment]
I agree that `lhs` and `rhs` are a bit weird for a non-infix case.  If we were talking about an overload of `<=>`, say, I'd find them to be just fine since they do appear on the specified side of the operator.

If you forced me to choose between `x` and `y` and `a` and `b`, I'd definitely choose the former.

If you forced me to come up with some other names, I might use `arg1` and `arg2` or `expr1`/`expr2` or `val1`/`val2` (or `obj1`/`obj2` if we decided to use `obj` for other calls (noting my previous hesitancy about using it if it were intended for non-record/class types)).

**Comment by benharsh** [comment]
I feel that we should go with ``x`` and ``y`` over something with numbers in the name like ``val1``/``val2``. I think the numbers-option is a little uglier (to me) and is somewhat prone to confusing typos. ``x`` and ``y`` aren't immune to this, but the distance between those keys is greater (at least on my keyboard).

**Comment by benharsh** [comment]
I also think my comment from #20328 concerning coercion may be applicable here as well.

**Comment by bradcray** [comment]
> I think the numbers-option is a little uglier (to me) and is somewhat prone to confusing typos. 

I'm open to that argument.

**Comment by benharsh** [comment]
I think this comment from #20328 is also relevant here: https://github.com/chapel-lang/chapel/issues/20328#issuecomment-1215496163

> I suppose part of the error message text will be the compiler informing the user whether a call resolved or not.
> 
> Are we only supposed to use where-clauses in cases where something else could/should resolve? Should we always be able to resolve moveInitialize with two types, and then issue a compilerError for incorrect usage of the function? Feels like a stylistic choice here...

I think we should do the same thing in both cases. For ``moveSwap`` this means either:
1) using fully-generic arguments and a ``compilerError`` internally so that the function always resolves
2) or using the type-constraints so that the compiler will issue a nice-looking error about a resolution failure

**Comment by benharsh** [comment]
After some time has passed, I believe I'm content to let the errors here be different from the ``moveInitialize`` case. I find Vass' example error to be sufficient, and we can improve the error without changing the way users interact with this function.

I propose the following, which changes only the formal names:
```chpl
proc moveSwap(ref x: ?t, ref y: t)
```

Please vote 👍 or 👎 to indicate support.

**Comment by benharsh** [comment]
Resolved by https://github.com/chapel-lang/chapel/pull/21087
