### ISSUE TITLE
Extend Chapel compiler's `TAGS`/`tags` support to include `dyno`

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#20379]
While trying to find my way around the `dyno` sources, I tried using the existing tags support for `CHPL_DEVELOPER=true` to jump to the definition of a class (e.g., `MaybeNamedActualList`) or routine (e.g., `makeSpannedLocation`), but didn't get any hits.  Checking with the `dyno` team, it seems that there hasn't been any investment in ensuring that `dyno` supports tags, so this issue is proposing we put in the effort to do so, which seems like it should be minimal for someone who knows their way around the dyno sources.

Specifically, the Makefiles have indications that it should be close to working, but may just be missing some header files and/or directories?  For example, our TAGS command is based on `ALL_SRCS`, which is currently defined as follows:

```
$ make print-ALL_SRCS
ALL_SRCS is adt/*.cpp AST/*.cpp backend/*.cpp codegen/*.cpp llvm/*.cpp main/*.h main/*.cpp dyno/lib/immediates/*.cpp dyno/lib/parsing/*.cpp dyno/lib/framework/*.cpp dyno/lib/resolution/*.cpp dyno/lib/types/*.cpp dyno/lib/uast/*.cpp dyno/lib/util/*.cpp optimizations/*.cpp parser/*.cpp passes/*.cpp resolution/*.cpp util/*.cpp
```

Yet a `git grep` for the symbols I was looking for suggests they're defined in `dyno/lib/parsing/*.h`.  So probably we just need to modify the dyno-specific rules that modify `ALL_SRCS` to include `.h` files and their containing directories (?).

**Comment by mppf** [comment]
Note to self: to enable TAGS for me in vim, I did:
 * install universal-ctags
 * set CHPL_EDITOR=vim
 * add this to my .vimrc
   ```
   " enable tags files
   :set tags=./tags;
   ```
 * get chpl to relink
 * search online for buttons to press in vim to use the tags (Control-] being the main one)

Regarding the problem in this issue, I have a pretty simple fix for it that adjusts the tags generation command. Will PR shortly.

**Comment by mppf** [comment]
@bradcray - could you let me know if #20386 solves the problem for you?

**Comment by bradcray** [comment]
> Note to self: to enable TAGS for me in vim, I did:

Not entirely related, but after having three reasonably distinct tags-related conversations this week, I'm planning on demoing the wonders of tags on Monday because I can't imagine emacs/vim developers not using them.
