### ISSUE TITLE
`here.numPUs()` returns zero when compiling with CHPL_LOCALE_MODEL=gpu

### ISSUE THREAD

**Issue by jeremiah-corrado** [chapel-lang/chapel#20370]
The following program prints "0":
```chapel
writeln(here.numPUs());
```
when compiling with `CHPL_LOCALE_MODEL=gpu`

It should have the same behavior as the flat locale model (i.e. it should print out the number of cpus available on the locale).

**Comment by bradcray** [comment]
What was the underlying reason for this?  I.e., I would've expected it to be something like an "unresolved call" rather than just returning a 0...?

**Comment by bradcray** [comment]
Great, thanks for the explanation!
