### ISSUE TITLE
Make LLVM support library more explicit/configurable in chplenv/chplconfig settings

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#20380]
( branched off from https://github.com/chapel-lang/chapel/issues/20273#issuecomment-1190531590 )

Now that we're relying on the LLVM support library within the compiler, even when `CHPL_LLVM=none`, we're relying on LLVM to build the compiler, which seems potentially confusing / inconsistent.  This issue proposes introducing a `CHPL_LLVM_SUPPORT` environment variable that would only support `system` and `bundled` as options such that the involvement of LLVM would be more explicit and a user could query / choose where that LLVM support was coming from.

Related, today my understanding is that, today, when `CHPL_LLVM=none`, `CHPL_LLVM_SUPPORT` will effectively default to `bundled` even if there is a reasonable system implementation of LLVM available to use.  It would be nice to have this variable default to `system` in such cases to avoid needing to build the bundled LLVM.  This could be split off into its own issue if it's too hard to get working along with the support for adding the variable and explicitly choosing between the options (but I put it here, optimsitically).

I'm marking this as "high priority" because it feels to me like it would be a shame to have 1.28 introduce the reliance on the LLVM support libraries without this support.

**Comment by bradcray** [comment]
@mppf: Since I was already filing issues, I added this one as well.  I was tempted to assign it to you, though maybe you have someone you could convince to pick it up (?).

**Comment by mppf** [comment]
I've made an initial attempt at addressing this in PR #20396.

**Comment by mppf** [comment]
I'm closing this issue because PR #20396 added CHPL_LLVM_SUPPORT as a printchplenv var.
