### ISSUE TITLE
Memory.Initialization: needsDeinit function signature and value version

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#20411]
The current signature of ``needsDeinit`` accepts a type argument and returns a param bool:

```chpl
proc needsDeinit(type t) param
```

There are two topics I would like to discuss:

### Return Type

We should specify the return type is ``bool``.

### Duplicate that accepts a value

Many of our functions in the standard ``Types`` module have a type version and a value version. I propose we add a duplicate for ``needsDeinit`` in the same spirit:

```chpl
proc needsDeinit(e) param : bool
```

**Comment by bradcray** [comment]
This sounds great to me!

**Comment by benharsh** [comment]
It should be noted that we are discussing the naming of this function over here: https://github.com/chapel-lang/chapel/issues/20410

**Comment by benharsh** [comment]
Resolved by https://github.com/chapel-lang/chapel/pull/21757

Future work: introduce a value version, potentially post-2.0
