### ISSUE TITLE
How to handle `QIO_HINT_OWNED` in the IO module?

### ISSUE THREAD

**Issue by jeremiah-corrado** [chapel-lang/chapel#20430]
Per some discussion on [this](https://github.com/chapel-lang/chapel/issues/20346) thread, it was decided that we probably don't want to include `QIO_HINT_OWNED` in the `ioHintSet` type. 

For background, this hint is used to indicate to the runtime that the relevant `_file` or `fd_t` should be closed when the associated chapel `file` is closed. (someone please correct me if I have that backwards). 

Instead of adding to `ioHintSet`, we may want to add an additional boolean argument to `openfd` and `openfp` to toggle this feature. The new headers for these methods might look something like this: 
```chapel
proc openfd(fd: fd_t, hints = ioHintSet.empty, owner = false):file throws { ... }
proc openfp(fp: _file, hints = ioHintSet.empty, owner = false):file throws { ... }
```

The specific name and default value of the "owner" argument would need to be decided (keeping in mind that `owned` is a reserved word and cannot be used here).

**Comment by lydia-duncan** [comment]
This is connected to #20143 and #20146

**Comment by jeremiah-corrado** [comment]
Following a recent IO module review discussion, we decided that we should go ahead with the proposal of adding an optional argument to `openfp` and `openfd` to control whether the resultant file object takes the responsibility of destroying the file when it is deinitialized. 

`openfp` and `openfd` are going to be deprecated and replaced by initializers on the `file` type in the near future (see https://github.com/chapel-lang/chapel/issues/20143 and https://github.com/chapel-lang/chapel/issues/20146). As such, the "owner" flag will be added to those initializers instead of these procedures.

**Comment by jeremiah-corrado** [comment]
The name of this flag still needs to be decided. Please vote on the following options:
- 👍 - `owner`
- 😄 - `own`
- 🎉 - `takeOwnership`
- ❤️ - `willClose`
- 👀  something else

**Comment by lydia-duncan** [comment]
I'd suggest `shouldClose` or `mustClose` over `willClose`.  That said, I think I probably still prefer `own` over both of those

**Comment by dlongnecke-cray** [comment]
I'd prefer "closeUnderlyingFile" / "closeUnderlyingDescriptor" or something more explicit. If not, then probably just `own`, because users are going to have to read the documentation to have any clue what that formal does, anyway.

**Comment by jeremiah-corrado** [comment]
Thanks for the suggestions @lydia-duncan and @dlongnecke-cray! I've added those to the poll (they are grouped together currently but we'll vote on a more specific option if one of those wins).

**Comment by bradcray** [comment]
A counterproposal to David's "let's be more verbose/complete" suggestion might be `closeOnDeinit`.  `closeUnderlyingFile=true` as an argument name to a routine suggests to me that maybe that routine should take that option.

**Comment by lydia-duncan** [comment]
`file.deinit` does not explicitly close the file, you have to call `file.close` yourself.  When the wrapper of `file`s that take file descriptors or file pointers has `close` called on it, it will care about whether it owns the file or not.  So I don't think it would be appropriate to indicate that deinit would do anything here

**Comment by mppf** [comment]
When the last `file` referring to an OS file is closed, the `file.deinit` will close the file. (It is just using reference counting). It's a good idea to call `file.close` to get error information back that might not be available otherwise. For these reasons, I `closeOnDeinit` is a reasonable name.

**Comment by jeremiah-corrado** [comment]
> A counterproposal to David's "let's be more verbose/complete" suggestion might be closeOnDeinit.
Good idea! I added `closeOnDeinit` as an option above (unfortunately 😕 was the only emoji left...)

**Comment by dlongnecke-cray** [comment]
I'm not sure I vibe with `closeOnDeinit` because, to me that implies that "closing the underlying file" is going to happen immediately with that file's deinit call. But according to Michael's comment whether or not the underlying file gets closed is subject to reference counting.

**Comment by bradcray** [comment]
> I'm not sure I vibe with closeOnDeinit because, to me that implies that "closing the underlying file" is going to happen immediately with that file's deinit call. But according to Michael's comment whether or not the underlying file gets closed is subject to reference counting.

@dlongnecke-cray : If I'm understanding, could your same concern apply to our `.close()` method on files today?  I.e., `.closeIfRefcountIsZero()` might be a better name if we were trying to make names as accurate as possible.  But if `.close()` inherently means that on a Chapel file, then maybe `closeOnDeinit()` gets to inherit that meaning?

**Comment by dlongnecke-cray** [comment]
Yeah, I'm not suggesting we rename `.close()` or anything. I just think it might be impossible to convey the true meaning of the formal through its name, at least not without an over-abundance of words. So I think we should probably just choose a nice simple name that sounds good and rely on the documentation to describe...

Hmmm, could we call it `callCloseOnDeinit`, then? 😄

Honestly I'm more happy with `closeOnDeinit` now that it's been framed in terms of "calling close". I didn't interpret it to mean that at first.

**Comment by bradcray** [comment]
I might prefer the simpler names + documentation approach as well.  I was just trying to come up with a longer name that seemed more accurate to me than yours if the vote trended in that direction.

**Comment by jeremiah-corrado** [comment]
I'm preparing another poll with a reduced set of options:

@lydia-duncan, can you say why you prefer `shouldClose` or `mustClose` over `willClose`?

@dlongnecke-cray, are you okay with removing the `closeUnderlyingFile` option given the discussion above?

**Comment by lydia-duncan** [comment]
To me, `willClose` implies that it's an action that will be taken as part of the immediate call - I could see expecting the process of making the file wrapper to clean the file pointer up right away, but that's not what happens.  `shouldClose` or `mustClose` to me still imply that the action will happen in the future, but not the imminent future.

**Comment by dlongnecke-cray** [comment]
Yes I'm OK with removing `closeUnderlyingFile`.

**Comment by jeremiah-corrado** [comment]
Thanks everyone for the good discussion! Since several options were added, and some were combined, I think we can go ahead with another poll with some of the less popular options removed:

- 👍 - `closeOnDeinit`
    - pro: succinct description of the behavior
    - con: potentially misleading: the OS file might not close if multiple `file`'s reference it — see this [comment](https://github.com/chapel-lang/chapel/issues/20430#issuecomment-1414246913), and the following comment
- 😄 - `own`
    - pro: vague/simple enough that users will likely read the docs to find out what it does
- 🎉 - `willClose`
     - con: might imply that the initializer will take the action immidately instead of on deinit
- 😕 - `shouldClose`
     - pro: might imply that the closing action will be taken in the future
- ❤️ - `mustClose`
     - pro: might imply that the closing action will be taken in the future
- 🚀 - `takeOwnership`
- 👀 something else, or one of the options from above

I've included some pros and cons from the discussion above. Please feel free to add/suggest more.

**Comment by bradcray** [comment]
As a gentle 'con' for "shouldClose" it could be interpreted as "You ought to close this, but who knows whether you will..."  (in the sense of "we can all fail at even our best intentions..." / "I should skip dessert, but will I...?").

**Comment by jeremiah-corrado** [comment]
It looks like everyone who voted was okay with `own` as the argument name, so I say we go ahead with that proposal.

With this addition, and the other changes discussed in the relevant issues, the file initializers replacing `openfp` and `openfd` will have the following signatures:
```chapel
proc file.init(fileDescriptor: c_int, hints=ioHintSet.empty, own=false) throws { ... }

proc file.init(fp: c_FILE, hints=ioHintSet.empty, own=false) throws { ... }
```

The `QIO_HINT_OWNED` flag will remain as an undocumented/hidden constant in the IO module used to implement this feature.
