### ISSUE TITLE
`Regex.matches` infinitely loops when searching `""` with patterns that match `""`

### ISSUE THREAD

**Issue by pierce314159** [chapel-lang/chapel#20441]
### Summary of Problem

When calling `Regex.matches` on `""` with `pattern`s that match the empty string (`""`, `"$"`, `"^"`, `"|"`,...), `((matched = true, byteOffset = -1, numBytes = 0),)` is returned infinitely many times. I expect the return to be 1 match. Potentially related to #18639

### Steps to Reproduce

**Source Code:**

```chapel
use Regex; 

var myRegex = compile("^$");  // same issue with "", "$", ...
var str = "";
writeln(myRegex.matches(str));
```

**Compile command:**

```
chpl PlayingAround.chpl -o playing
```
**Execution command:**

```
./playing
```

### Configuration Information

- Output of `chpl --version`:
chpl version 1.27.0
  built with LLVM version 14.0.0
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled *
CHPL_LLVM: bundled *
CHPL_AUX_FILESYS: none
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

**Comment by bradcray** [comment]
Thanks for filing this @pierce314159!  Would you let us know whether this is a major problem or blocking issue for you, or whether it's something you stumbled across and are filing out of a sense of good citizenship?

**Comment by pierce314159** [comment]
> Thanks for filing this @pierce314159! Would you let us know whether this is a major problem or blocking issue for you, or whether it's something you stumbled across and are filing out of a sense of good citizenship?

Of course! I came across this while doing some edge case testing for https://github.com/Bears-R-Us/arkouda/issues/1613, adding back in support for patterns which match the empty string now that the original fix is in our least supported chapel version.

I don't consider this a major problem, since I imagine this case will be quite rare. We're just now adding back in support for any patterns that match the empty string (without anyone having asked for it), so I don't see an issue with leaving out this case for a while longer. I don't have a workaround for this, so for the time being I'm raising a `ValueError` for any regex operations where `pattern=""` and Strings contains `""`.

**Comment by bradcray** [comment]
@vasslitvinov : Thanks for taking care of this!  @pierce314159 : Thanks for reporting it, and please let us know if you run into other issues.
