### ISSUE TITLE
Chapel (1.27.0) build with System LLVM 14.0.6 Linker Error

### ISSUE THREAD

**Issue by kwaters4** [chapel-lang/chapel#20454]
### Summary of Problem

I am building Chapel with the system LLVM (version 14.0.6) and I am receiving a clang-14 linker command failed error with respect to the std library. 

I was able to build it with LLVM 11.0.0, 12.0.1, and the bundled 14.0.0 on the same system. However, I have not had the same luck with 14.0.6. I was wondering if anyone else has run into this issue or has been able to build Chapel with LLVM 14.0.6. 

If the issue is not reproducible with the limited information let me know and I can dig deeper into it. 

### Configuration Information
Chapel = 1.27.0 
GCC = 11.2.0 
LLVM  = 14.0.6

**Comment by Ethan-DeBandi99** [comment]
@kwaters4 - depending on the type of machine you are on, you may need to resort to building Chapel from source. I had a similar issue after updating to `1.27.0` using `brew` on a Mac with the M1 chip.

**Comment by bradcray** [comment]
Thanks for reporting this, @kwaters4.  @mppf filed a PR recently to address some issues like the brew update on M1 case that @Ethan-DeBandi99 mentions.  I'm not certain whether this would affect a built-from-source version, however.  As I understand it, most of the existing issues we've hit have been due to our embedding a path to LLVM into our configuration only to have that path change out from under us, but it doesn't seem as though that should affect a fresh build from source.  What I'm less sure of is whether—if your other successful LLVM builds used system versions from the same installation—whether they could interfere with each other in some way?

Let's see what Michael says tomorrow.

**Comment by bradcray** [comment]
Also, wild guess based on another user report recently:  Do you have LD_LIBRARY_PATH set in your environment at all, by any chance?  And are you getting the linker error upon building Chapel or trying to compile a Chapel program?  (and are you able to capture the output here?)

**Comment by kwaters4** [comment]
@bradcray It is in compiling Chapel itself. I will try to reproduce the error in a different environment and see if it reproducible. My initial assumption was that it was something silly that I was doing, which still may be the case.

**Comment by mppf** [comment]
@kwaters4 - can you share the OS version? Is it a linux system? Which distribution and which version? Thanks.

**Comment by kwaters4** [comment]
@mppf CentOS 7.6

**Comment by mppf** [comment]
OK. How have you installed GCC and LLVM? Are they installed from source or from rpms?

Issues with installing on CentOS 7 have come up before and we understand it's hard. But we haven't made a document just about it yet.

See also:
 * https://github.com/mppf/chapel/commit/d1cedf8bbca8cc04d3fc4e9a321f4406ee7e31a5#r70177509
 * https://chapel.discourse.group/t/build-of-1-25-1-with-bundled-llvm-on-system-with-multiple-gcc-g-installed/11179

I'd also be interested to know if `export CHPL_LLVM_GCC_PREFIX=/opt/rh/devtoolset-11/root/usr` (or something like that) helps you at all.

> If you have the devtoolset loaded and you run ./util/printchplenv --all and look at CHPL_TARGET_CC -- there is e.g. a --gcc-toolchain=/some/path/to/gcc-8.3.0/x86_64 and that value after the = is what you should set CHPL_LLVM_GCC_PREFIX to.

**Comment by bradcray** [comment]
@kwaters4 : Just pinging here to see if there are any updates, and to make sure you'd seen these questions since you weren't @-tagged in that last comment.

**Comment by kwaters4** [comment]
@bradcray Thanks for the ping. This is something I still need to track down, it may take a couple of weeks.

**Comment by bradcray** [comment]
No rush!

**Comment by kwaters4** [comment]
I am going to close this issue, I have not been able follow-up.
