### ISSUE TITLE
spike: resolve operator overloads in dyno

### ISSUE THREAD

**Issue by riftEmber** [chapel-lang/chapel#20488]
Ensure that Dyno resolver can resolve operator overloads, and add testing for a variety of different operators.

Goals:

- [x] Set up tests for resolving cast operator (see example program below)
- [ ] Get cast operator working
- [ ] Test resolving additional operators, adjusting resolver implementation if necessary

<details><summary>Sample program for cast operator from @mppf </summary>

```chpl
module M {
  record R {
    var field: int;

    // primary operator method 
    operator :(x: R, type t: int) { return x.field; }
  }

  // secondary operator method
  // operator R.:(x: R, type t: int) { return x.field; }

 
  // non-method operator
  // operator :(x: R, type t: int) { return x.field; }


  var myR: R;
  var z = myR : int;
}
```

</details>

Note this is my first task, so feel free to be very nitpicky about process and code.

**Comment by mppf** [comment]
@riftEmber - in terms of nit-picking, it would be good for this issue to have a bit more detail about which things you are going to try to do in which order. IIRC, the email I sent you had an example program to check if it works, and suggested you start with a particular operator. That would be good to put in the issue.

**Comment by riftEmber** [comment]
Update: tests for cast operator done. Out of the three versions only the non-method operator overload works in Dyno, the others erroring with `Cannot resolve call: no matching candidates`. Working on figuring that out now

**Comment by mppf** [comment]
Can you make a PR for the case that's working and maybe commit commented out code (or something) for the cases that don't work yet? Would be good to get that 1st PR in.

**Comment by riftEmber** [comment]
Progress in this sprint:

- Learned the dyno testing system and wrote tests for the cast operator, merged in https://github.com/chapel-lang/chapel/pull/20552. Some tests are currently commented due to failing when they shouldn't.
- Learned about the dyno resolver, including screenshare with Michael as well as a lot of exploring around running my test with lldb and reading code.
- Discovered that in the failing test cases (in which the operator is defined as a method), the `CallInfo` constructed for the call has `isMethodCall_` false, which affects call resolution and is what I'm looking into next.

I'm closing this issue and will create another for further work in the next sprint. I realized after creating it that this issue should have been private, so the next will be.
