### ISSUE TITLE
Should user-defined field-accessors be deprecated?

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#20509]
Currently I can write my own field-accessor for fields in a composite type:

```chpl
record R {
  var x : int;

  proc x ref {
    writeln("R.x accessor");
    return x;
  }
}

var r : R;
r.x = 5; // prints "R.x accessor" to stdout
```

This functionality was met with some surprise/unease over on #20472, which contains some discussion concerning the value of this feature (or lack thereof).

**Should we deprecate this functionality?**

A few points made on that issue:
- ``proc x ref`` seems like something that would incur a "multiple definitions" error
- Such a method seems more appropriate to "hide" a field (e.g. ``_x`` and ``x``).
- At one time, this may have been considered a logical conclusion to the implementation of compiler-generated field-accessors, and how we resolve field accesses

Some relevant issues:
- https://github.com/chapel-lang/chapel/issues/18177
- https://github.com/chapel-lang/chapel/issues/19474
  - https://github.com/chapel-lang/chapel/pull/19505

**Comment by benharsh** [comment]
For anyone interested, a useful small-ish task would be to implement an error for this case and see what tests in our suite fail.

**Comment by mppf** [comment]
Just copying my comment on the other issue here where it is more relevant https://github.com/chapel-lang/chapel/issues/20472#issuecomment-1225851857 :

> @benharsh - you might want to look at the PR message for https://github.com/chapel-lang/chapel/pull/19505 and be aware of issue https://github.com/chapel-lang/chapel/issues/19474 which it resolves. The reason that I bring these up is that there was some discussion about the purpose of parenless procs. I would summarize my own understanding after that discussion as "Parenless procs should allow a user to replace a field with something else, to keep code using the type working as it was without modification". I do not think that this purpose for parenless procs justifies in any way having a field and parenless proc of the same name. I think it is reasonable to require users wishing for that pattern to rename their field.

**Comment by mppf** [comment]
Just making a note (since I was looking at related areas of the spec). If this changes, we will need to update https://chapel-lang.org/docs/1.28/language/spec/classes.html#field-accesses and https://chapel-lang.org/docs/1.28/language/spec/records.html#field-getter-methods

**Comment by lydia-duncan** [comment]
Is this something we should be scheduling time to discuss?

**Comment by mppf** [comment]
In https://github.com/Cray/chapel-private/issues/5163, we decided that these should be a re-declaration error:

> Example 5' should be a redeclaration error
> Example 5'' should be a redeclaration error as well (shouldn't be able to make a parenless proc with the same name as a field whether primary, secondary, or tertiary)

<details>

``` chapel
// Example 5' from 21668 née 15937
record R {
  proc field { return 1; }
  var field = 2;

  proc foo() { writeln(field);} // calls the parenless proc
}

var r: R;
r.foo();
```

``` chapel
// Example 5'' from 21668 née 15937
module Main {
  use Library;
  proc R.field { compilerWarning("In R.field"); return 8; }

  proc main() {
    var myR: R;
    myR.method();
  }
}

module Library {
  record R {
    var field = 77;
    proc method() { writeln(this.field); } // currently, error: unresolved call
  }
}
```

</details>

PR #22917 will make the program from the top post of this issue, as well as Examples 5' and 5'', fail to compile with redeclaration errors. I'll close this issue when merging that PR.
