### ISSUE TITLE
`-INFINITY` and `-0.0` raised to `0.5` don't match `sqrt`

### ISSUE THREAD

**Issue by pierce314159** [chapel-lang/chapel#20542]
### Summary of Problem

`(-INFINITY)**0.5` doesn't return `nan` and `(-0.0)**0.5` doesn't return `-0.0`. I would expect this to behave the same as `sqrt`. It seems other negative floats and positive `INFINITY` match

### Steps to Reproduce

**Source Code:**

```chapel
writeln("(-0.0)**0.5:");
writeln((-0.0)**0.5);
writeln("(-INFINITY)**0.5:");
writeln((-INFINITY)**0.5);
writeln();
writeln("sqrt(-0.0):");
writeln(sqrt(-0.0));
writeln("sqrt(-INFINITY):");
writeln(sqrt(-INFINITY));
```

**Compile command:**

`chpl PlayingAround.chpl -o playing`

**Execution command:**

```
$ ./playing
(-0.0)**0.5:
0.0
(-INFINITY)**0.5:
inf

sqrt(-0.0):
-0.0
sqrt(-INFINITY):
nan
```

### Configuration Information

- Output of `chpl --version`: 
```
chpl version 1.27.0
  built with LLVM version 14.0.0
```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled *
CHPL_LLVM: bundled *
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
```

**Comment by pierce314159** [comment]
looking into it a bit more, it seems numpy has variation here too, so I apologize if there's a good reason and I jumped the gun
```python
>>> n = np.array([-0.0, -7, -np.inf])
>>> n**0.5
array([-0., nan, nan])

>>> np.power(n, 0.5)
array([ 0., nan, inf])

>>> np.sqrt(n)
array([-0., nan, nan])

>>> n**(1/3)
array([ 0., nan, inf])

>>> np.power(n, 1/3)
array([ 0., nan, inf])

>>> n**(1/4)
array([ 0., nan, inf])

>>> np.power(n, 1/4)
array([ 0., nan, inf])
```

**Comment by bradcray** [comment]
Hi @pierce314159 : `**` in Chapel is typically implemented using C's `pow()` routine, which seems to generate similar results if I make calls to it from Chapel:

```chapel
extern proc pow(x: real(64), y: real(64)): real(64);
                
writeln("(-0.0)**0.5: ", (-0.0)**0.5);
writeln("pow(-0.0, 0.5): ", pow(-0.0, 0.5));
writeln("(-INFINITY)**0.5: ", (-INFINITY)**0.5);
writeln("pow(-INFINITY, 0.5): ", pow(-INFINITY, 0.5));
writeln();
writeln("sqrt(-0.0):", sqrt(-0.0));
writeln("sqrt(-INFINITY):", sqrt(-INFINITY));
```

```
(-0.0)**0.5: 0.0
pow(-0.0, 0.5): 0.0
(-INFINITY)**0.5: inf
pow(-INFINITY, 0.5): inf

sqrt(-0.0):-0.0
sqrt(-INFINITY):nan
```

I'm not enough of a floating point expert to be able to explain why it behaves as it does, though.  If there's something we should be doing differently in mapping `**` to it and/or calling it, that would be interesting to understand.

**Comment by bradcray** [comment]
@pierce314159: I did a bit of Googling about this to see if I could learn more quickly, and found the following comment on a SO post that recommends using `sqrt()` when what you really want is a square root:

https://stackoverflow.com/questions/70793490/how-do-i-calculate-square-root-in-python#comment125162326_70793491

Let me know whether you'd like to argue for changes of some sort here, or whether you're OK with closing this.  Now that I've caught up with your most recent comment, I think Chapel, C, and NumPy are all symmetrical w.r.t. the cases in the OP?  (where my guess would be that NumPy is wrapping the C math library, similar to Chapel?)

**Comment by pierce314159** [comment]
Yeah I agree! I think being in line with `C` and `numpy` is as good a design choice as any. I am down with closing this issue -- thanks for looking into it!
