### ISSUE TITLE
what should we do with owned.create and shared.create?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#20648]
Today we have these functions:

``` chapel
proc type owned.create(in take: owned) // Case 1
proc type owned.create(p : unmanaged)  // Case 2

proc type shared.create(in src: shared) // Case 1
proc type shared.create(p : unmanaged)  // Case 2
proc type shared.create(in take: owned) // Case 3
```

These were added in PR #15119 to replace even stranger syntax.

They fall into 3 cases:

1. Using `create` to make a copy of an `owned`/`shared` value. This is the same as copy initializing e.g. with `var x = myOwned`. This form is arguably redundant and confusing.
2. Using `create` to make an `owned`/`shared` that manages an unmanaged pointer. As far as I know, there is no other way of writing this today.
3. Using `create` to create a `shared` from an `owned` that takes the responsibility for managing that memory. This can be done with a cast today (with some limitations -- see #20647). Previously, it could also be done in initialization or assignment (e.g. `var x: shared MyClass = myOwned`). However, that was removed in PR #20492 since it was deemed to be too subtle.

In some previous discussion about this, it was argued that we should remove `create`. One reason for doing so is to enable authors of classes to make their own type method called `create` and then call it on owned/shared types (e.g. `(owned MyClass).create()`). See also issue #20336. However, I have not yet seen discussion about how to handle case (2) above if `owned.create(myUnmanagedPtr)` / `shared.create(myUnmanagedPtr)` are not the way.

**Comment by bradcray** [comment]
I like the idea of dropping case 1 and 3 in favor of initializers and casts.  For case 2, would `myUnmanagedClass: owned` (or `: owned C`) be an alternate way of expressing this?  (similar to how `unmanaged C: owned` results in `owned C`, I believe?)

**Comment by mppf** [comment]
> I like the idea of dropping case 1 and 3 in favor of initializers and casts. For case 2, would `myUnmanagedClass: owned` (or `: owned C`) be an alternate way of expressing this? (similar to how `unmanaged C: owned` results in `owned C`, I believe?)

It could be, but it doesn't seem appealing to me. The reason is that it's effectively saying "I want you to take over `delete`ing this pointer" but a `:` operator call seems like a weird way to do that to me. (In particular if I were looking at some code I'm not sure I would pick up on this just from a `:`). I would prefer `shared.create(myUnmanagedPtr)` instead since I view it as more clear.

**Comment by lydia-duncan** [comment]
I think I mentioned it somewhere but I don't see it here, so I'll repeat it.  I would be in favor of renaming them to `createOwned` and `createShared`.  I think the redundancy of `owned.createOwned` is useful here because it avoids taking `create` away from the underlying class definition and is unlikely to be a name that users would want themselves

**Comment by lydia-duncan** [comment]
I know @dlongnecke-cray at least has balked at `<type>.create<Type>` in the past, but I think it would be fair for this to be an exception

**Comment by mppf** [comment]
> it avoids taking `create` away from the underlying class definition and is unlikely to be a name that users would want themselves

I might be missing something but since these are type methods I'm not seeing the issue here. Isn't a user free to create an instance method `proc create` and call that for owned/shared instances? And also to create `proc type create` on their own type and then call that from `MyType.create` etc?

Are you supposing that somebody wants to call `(owned MyClass).create()` and have that call a user-defined `proc type MyClass.create()` ? Regardless of what that does today, I see it as a pretty minor issue. (I.e. if it doesn't work, I don't have a problem asking them to write `MyClass.create()` instead. But to be clear, I have not checked).

**Comment by lydia-duncan** [comment]
> Are you supposing that somebody wants to call `(owned MyClass).create()` and have that call a user-defined `proc type MyClass.create()` ? Regardless of what that does today, I see it as a pretty minor issue. (I.e. if it doesn't work, I don't have a problem asking them to write `MyClass.create()` instead. But to be clear, I have not checked).

I'm confused, your original post mentions this case, so I was proposing a solution since it seemed like you didn't want the functions to go away

**Comment by mppf** [comment]
> I'm confused, your original post mentions this case, so I was proposing a solution since it seemed like you didn't want the functions to go away

So it does. I had not remembered that. I'd still probably pick "live with it" as I outlined in my last comment, though.

**Comment by bradcray** [comment]
> I would prefer shared.create(myUnmanagedPtr) instead since I view it as more clear.

Whenever I review these `create()` calls for owned/shared, I always find myself wondering things like "Is it doing a deep copy of the class and creating a owned/shared version of it?" or something else?  (answer: something else).  For that reason, I wonder whether `adopt()` would be a better term for this.  To me, that makes it more clear that it's taking over the management of the object.  There may be other synonyms that say that equally well—create() just isn't one for me, as it sounds more like "make something new".

**Comment by mppf** [comment]
> I'm confused, if we have a class `C` and we define `create` on `owned`, is the issue that `owned.create()` also enables `C.create()` and takes `create()` from the namespace of the type `C`?

I think it would only be "stealing" from the namespace if you wanted `(owned C).create()` to call the user-defined function.

> Because if `owned.create()` does _not_ steal from `C`, then I don't see a problem with keeping around `owned.create(x: unmanaged ?T)` if there's no other way to handle that case. I just thought we wanted to get rid of `create` for the class managers because it was redundant with casts.

`create` is redundant with the casts in Case 3 but not for Case 2 (cases from the OP).

FWIW I would also be happy to switch to `owned.adopt` or some other name. (not so sure `owned.createOwned` is it, though).

**Comment by dlongnecke-cray** [comment]
Ok, I'd advocate that we deprecate case 1 and 3, and support case 2 by adding `owned.adopt()` and `shared.adopt()`. I agree with Brad that `adopt` is a better name for communicating that the manager is assuming control over the lifetime of the memory.

**Comment by mstrout** [comment]
Subsumed by #21372, so go there to see conclusion.
