### ISSUE TITLE
IO module: region arguments should encapsulate whole area of channel covered

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#20672]
When we replaced the `start` and `end` arguments with the `region` argument, we changed all calls from `start=x, end=y` to `region=x..y`.  However, `end` in the old world was the first index to not be covered.  It makes less sense for the last number in the region argument to be treated differently than all the other numbers in it, what we should have done is changed the calls to `region=x..(y-1)` and allowed the whole range to be accessible.

This impacts:
- openreader
- file.reader
- file.writer
- file.lines
- channel.seek

Brad and I noticed this as part of #20670

**Comment by bradcray** [comment]
I've marked this as high priority because I think it's something we should resolve before the next release (or sooner, on the offchance that we need to do a point release for any reason).

**Comment by lydia-duncan** [comment]
I would like to be convinced otherwise, but I'm kinda thinking we need multiple flags for this.  It seems like it will be a potential source of confusion if one flag changes the behavior of five functions.  Since these are warning messages, a user should see them all at once but it seems pretty likely that they'd go and resolve the first error they see and then not notice that other calls were affected by the solution.  Arguably this could happen for multiple calls to the same function but I suspect it's easier to think "oh, I should update all calls to x" than it is to notice that x, y, z all print the same message and so would be impacted by the same flag.

The interaction between openreader and file.reader is a little tricky in that case, but I think it's still doable with care

**Comment by mppf** [comment]
I'm wondering if we can get away with not really deprecating it, but rather issuing a warning or something if the end is not unbounded? E.g. an unstable warning?

**Comment by lydia-duncan** [comment]
I don't think unstable is appropriate if we are actively changing the behavior and don't intend to change it back

**Comment by mppf** [comment]
Unstable can mean either:
 * it was recently changed (so beware!)
 * it is expected to change in the future

It was originally added for the 1st of these but we have been leaning more on it for the 2nd lately. But in slides etc. I think it describes both.

**Comment by lydia-duncan** [comment]
But that was before deprecation was supported properly.  The behavior for this change will be subtle, I think it's important that the notification of it changing not be similarly subtle (which a warning that is not on by default would be).

**Comment by bradcray** [comment]
> The behavior for this change will be subtle, I think it's important that the notification of it changing not be similarly subtle (which a warning that is not on by default would be).

I agree with this.

**Comment by mppf** [comment]
I'm still confused about what the question above was.

My starting point is that I'm expecting we're going to emit a *run-time* warning for cases where the provided range has an upper bound. (Most code does not do this, anyway).

> I would like to be convinced otherwise, but I'm kinda thinking we need multiple flags for this. It seems like it will be a potential source of confusion if one flag changes the behavior of five functions.

@lydia-duncan - are you talking here about a flag that disables the above run-time warning (for people who have already migrated their code)? It seems to me that one flag would be sufficient because I'm not expecting there will be a lot of code calling these functions and providing an upper bound. So the user's process would be:
 * compile and run
 * observe warnings in program output
 * fix all of these, but still see warnings in program output
 * turn off these warnings in a flag since they are no longer useful for this application

**Comment by lydia-duncan** [comment]
`range.hasHighBound` is a param function, so I was detecting it at compilation time and using that to determine whether a warning should be generated.

I'm definitely happy to use one flag for all five functions, I just know that I personally handle errors in-order and re-run, especially if there are a lot.  So if solving one error made others go away, I'm more likely to assume it was solved by the first fix rather than expecting I needed to make other changes
