### ISSUE TITLE
updates for compatibility with newer PBS

### ISSUE THREAD

**Issue by sdbachman** [chapel-lang/chapel#20685]
This update enables CHPL_LAUNCHER=pbs-gasnetrun_ibv to be compatible with PBS version 2021.1.3.20220217134230.  

It just involves a few changes to /runtime/src/launch/pbs-gasnetrun_ibv/launch-pbs-gasnetrun_ibv.c :

```diff
107,108c107
<     fprintf(pbsFile, "#PBS -l mppwidth=%d\n", numLocales);
<     fprintf(pbsFile, "#PBS -l mppnppn=%d\n", procsPerNode);
---
>     fprintf(pbsFile, "#PBS -l select=%d:ncpus=%d:", numLocales, procsPerNode);
110c109
<       fprintf(pbsFile, "#PBS -l mppdepth=%d\n", numCoresPerLocale);
---
>       fprintf(pbsFile, "mpiprocs=%d\n", numCoresPerLocale);
```

**Comment by mppf** [comment]
@sdbachman - I edited your post to fix the formatting. But, FWIW, this kind of thing makes more sense to me as a Pull Request (it can be a Draft PR if you are looking for feedback on the approach).
