### ISSUE TITLE
`gcc -v` used to determine `CHPL_LLVM_GCC_PREFIX` fails on Cheyenne

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#20696]
I'm seeing failures in chplenv when trying to compute the GCC prefix. This is on NCAR Cheyenne, but I don't think there's necessarily anything machine specific about it. The lines that are failing are: 

https://github.com/chapel-lang/chapel/blob/3034ab7500e0813d4df2fb99a36fa42786d22732/util/chplenv/chpl_llvm.py#L471-L473

fail with:

```
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/glade/u/apps/ch/opt/gnu/10.1.0/libexec/gcc/x86_64-pc-linux-gnu/10.1.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../configure --prefix=/glade/u/apps/ch/opt/gnu/10.1.0/ --enable-languages=c,c++,fortran,lto --enable-threads --disable-multilib
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 10.1.0 (GCC)
COMPILER_PATH=...
LIBRARY_PATH=...
COLLECT_GCC_OPTIONS=...

/usr/bin/ld: /usr/lib/../lib64/crt1.o: in function `_start':
/home/abuild/rpmbuild/BUILD/glibc-2.22/csu/../sysdeps/x86_64/start.S:114: undefined reference to `main'
collect2: error: ld returned 1 exit status
```

So it seems like gcc is trying to actually compile, which causes it to see there's no main defined.

From https://gcc.gnu.org/onlinedocs/gcc/Overall-Options.html#Overall-Options I see:

> -v   Print (on standard error output) the commands executed to run the stages of compilation. Also print the version number of the compiler driver program and of the preprocessor and the compiler proper.
>
> -###   Like -v except the commands are not executed and arguments are quoted unless they contain only alphanumeric characters or ./-_. This is useful for shell scripts to capture the driver-generated command lines.

Which makes me think we should be using `-###`, but I don't know for sure and didn't check how long that option has existed for.

I can work around this by manually setting `CHPL_LLVM_GCC_PREFIX` for the time being.

**Comment by mppf** [comment]
AFAIK GCC has always had `-###` and we use it in other places. I do not remember why this code is used `-v` rather than `-###`.

**Comment by mppf** [comment]
Anyway that logic was added in PR #18551 which isn't new in 1.28, anyway.

**Comment by ronawho** [comment]
I no longer see this on cheyenne, it looks like `gcc -v` behaves differently now.


```sh
eronaghan@cheyenne6:~/chapel> gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/glade/u/apps/ch/opt/gnu/10.1.0/libexec/gcc/x86_64-pc-linux-gnu/10.1.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../configure --prefix=/glade/u/apps/ch/opt/gnu/10.1.0/ --enable-languages=c,c++,fortran,lto --enable-threads --disable-multilib
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 10.1.0 (GCC)
```
