### ISSUE TITLE
Single-statement routines and the `return` exception

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#20703]
Today, Chapel doesn't support single-statement routines without `{...}` in general because of syntactic ambiguities—primarily due to the heavy overloading of square brackets making it unclear sometimes where a routine's header stops and its body starts.  We've had one exception since the dawn of time for `return` statements, such that rather than writing:

```chapel
proc square(x) {
  return x*x;
}
```

you could write:

```chapel
proc square(x)
  return x*x;
```

I believe the rationale for this was that it was syntactically unambiguous and trivial to parse while also supporting a common case (short, simple, single-statement procedures).

I have to admit that this singleton exception has always made me a little uneasy because it seems like such an exception.  But at the same time, I've been reluctant to make a breaking change, to need to update all our code that relies on it, etc.

This came up in discussion today, making me think I should create an issue for it rather than having it continue to quietly eat at me.  The main questions as I see it are:

* should we continue to support this exception for `return` statements?
* should we introduce a more general option for having single-statement procedures, where a leading contender might be to use `do` as a separator, similar to what we use for single-statement loop forms?

(where we could do both, one, or neither of these).

Let's put some votes on these:

:-1: preserve the current exception for `return`
:+1: remove the current exception for `return`
:rocket: introduce `do` to support any single-statement procedure body
:eyes: don't introduce `do` form of single-statement procedures
:tada: do something else (say what in the comments

**Comment by bradcray** [comment]
Vaguely related to this issue is: https://github.com/chapel-lang/chapel/issues/19181

**Comment by mppf** [comment]
My own opinion is that I'm not sure the ability to skip `{ }` saves much. It is just two characters. Maybe the way it helps is more conceptual? I'm not sure that's a win, since it's an exception...

**Comment by bradcray** [comment]
I agree it doesn't save much, though when writing a one-line form, I think I'd prefer one of:

```chapel
proc square(x) return x*x;
proc square(x) do return x*x;
```

over:

```chapel
proc square(x) { return x*x; }
```

(Arguably, the "it's just two characters" also applies to the loop and conditional forms that support keyword-based single-statements, and those I'd be much more opposed to getting rid of).

**Comment by damianmoz** [comment]
I would vote for the status quo although my own coding style outlaws single statement loops. So I am not sure my reasoning for keeping the status quo is rigorous. I will leave my vote as is but you are making me think hard so I might get back to you.

**Comment by damianmoz** [comment]
I just looked at some very recent work I did on #20390.

Very quickly, a one liner becomes a two liner very quicklyeven with mild complexity and suddenly you have lost that edge.

If a **return** is the only exception to the rule, get rid of the exception.

**Comment by damianmoz** [comment]
<begin-background-noise>
I lament the loss of the pure Backus Naur statement. I think that happened in the early 70s - before my time.
<end-background-noise>

**Comment by bradcray** [comment]
> If a return is the only exception to the rule, get rid of the exception.

It is, currently (excerpting from [chpl.ypp](https://github.com/chapel-lang/chapel/blob/main/compiler/dyno/lib/parsing/chpl.ypp#L2601-L2604):

```bison
function_body_stmt:
  block_stmt_body   { ... }
| return_stmt       { ... }
;

```

But if we were to add the ability to use `do` while removing the exception, then your #20390 one-liners could remain one-liners as:

```chapel
inline proc min(x: real(?w), y: real(w)) do return if (x < y) | isnan(x) then x else y;
```

I'll have to leave the question of whether you're being inconsistent in your personal style choices to you.  :)

**Comment by bradcray** [comment]
@benharsh: I wanted to tag you on this to see whether I captured your thinking from yesterday correctly, and to see whether I was reading you right in the meeting that you would disable the special-case for `return` and add `do` as a more general way to do this for any routine?

**Comment by benharsh** [comment]
I would disable the special-case for ``return``, and add ``do`` as a more general way for support this pattern (assuming that we still believe that it's worth supporting).

**Comment by bradcray** [comment]
For those following this, I've added some voting options to the OP.

**Comment by bradcray** [comment]
@lydia-duncan : Since you're an outlier on both axes currently, would you give a rationale for your position (if you care enough to defend it)?

**Comment by lydia-duncan** [comment]
I think enabling longer statements without surrounding curly braces would make things more confusing.  I never use that form for loops and if statements myself due to personal preference.  The combination of allowing them and those statement already having a do form means that it's possible to have much longer bodies for these functions.  At that point, it would be easy for someone to think it was okay to add another statement to the body without realizing that would put the statement actually outside it, and I suspect the error message in that case is not super clear.  Visually, it's harder to notice that two characters are missing when there's multiple lines involved.

I also wonder at the point of enabling it for something other than if statements and loops.  If it's a single statement, why aren't you making that function call directly?

I feel less strongly about keeping the return exception.  It's been handy for quick little functions and methods, but I don't think I've ever written one myself and can find it a little jarring when I run across a function that uses it.  However, I do still notice the curly brackets are missing when I look at them because of its size, so it doesn't run into the same issue as the other statements would.  I suspect if I started the language from scratch I wouldn't implement it, but I don't think it's terrible since it already exists.

**Comment by bradcray** [comment]
> If it's a single statement, why aren't you making that function call directly?

My answer would be that it gives the ability to change that single statement once and have it be reflected in multiple places without having to change each of those places individually.  E.g.

```chapel
proc debugPrint(x, y, z) do writeln("My old debug format: ", (x,y,z));
```

changes to:

```chapel
proc debugPrint(x, y, z) do writeln("my new debug format: x is: ", x, " y is: ", y, " and z is: ", z);
```

> At that point, it would be easy for someone to think it was okay to add another statement to the body without realizing that would put the statement actually outside it, and I suspect the error message in that case is not super clear. Visually, it's harder to notice that two characters are missing when there's multiple lines involved.

This is a place where I'd hope editor modes would step up.  E.g., I'd find Python pretty unusable without editor support, and this seems similar to me.

**Comment by damianmoz** [comment]
I should say I find the single statement extremely useful. I use it for practically everything in my IEEE854 module.

**Comment by dlongnecke-cray** [comment]
I am still partial to `proc (x, y) => x + y` as a short form for returning a value. I think it would come in handy when writing small in-line lambdas (perhaps it should apply only to them). While I think we should allow `do ...;` for any statement, I don't think we should get rid of the `return` only form. This is not such a weird thing to leave in even if we had both.

I enjoy having the `return ...` syntax and would enjoy having `do`. I think the ability to write one-liners while omitting curly braces is elegant and makes the code easier to read.

**Comment by bradcray** [comment]
> I don't think we should get rid of the return only form. This is not such a weird thing to leave in even if we had both.

To me it seems weird to support a special-case for `return` in procedure declarations but not other contexts where keywords are required for single-statement forms.  For example, today we require you to write:

```chapel
if test then
  return x;
```

rather than permitting:

```chapel
if test
  return x;
```

So I don't have a rationale for why `return` should be special in the procedure body case; nor for why other (unambiguous) single-statement forms don't get similar treatment.

To me, requiring `do` and applying it to all single-statement procedure bodies seems like the shortest path to consistency.

**Comment by dlongnecke-cray** [comment]
> So I don't have a rationale for why return should be special in the procedure body case;

Just would be nice to save the two characters, at least one user likes it, and we wouldn't have to go change a bunch of code. New code could write `do return` if users prefer that.

> nor for why other (unambiguous) single-statement forms don't get similar treatment.

FWIW I would be quite happy with that.

I also like the idea of `if test return x;`.

I agree with adding more statements to expand the functionality, though. Unambiguous statements could drop the `do`, while ambiguous would require `do`.

**Comment by redhatturtle** [comment]
I think it's worth keeping single statement procedures even though I rarely use them since it can make some modules incredibly easy to read.

As to how to achieve consistent syntax I don't have any strong feelings. Using the "do" keyword seems like the solution that breaks less existing code.

**Comment by bradcray** [comment]
I've got a draft PR that shows the impact of requiring `do` on single-statement `return` procedure bodies available here, for those who  might be interested:  https://github.com/chapel-lang/chapel/pull/21632

**Comment by bradcray** [comment]
In our subteam discussions, nobody had any qualms about this change.

In previous full-team and community discussions, there was slight regret at losing the ability to write `proc foo() return x;`, but generally a stronger sense that the non-orthogonality and special-case for `return` were not worth the convenience.  We also discussed the possibility of not requiring `do`/`then` for any single-statement bodies (of procedures, control flow, etc.) that didn't require it for disambiguation, but left that for someone else to champion in the future, likely post-2.0.
