### ISSUE TITLE
Links to MKL reference BLAS gone bad

### ISSUE THREAD

**Issue by ghbrown** [chapel-lang/chapel#20736]
It seems the [BLAS module documentation](https://chapel-lang.org/docs/modules/packages/BLAS.html) used to link to MKL's Fortran BLAS documentation and implementation, but it seems the links are broken and now lead to [a generic landing page](https://www.intel.com/content/www/us/en/homepage.html?ref=https://www.intel.com/content/www/us/en/develop/documentation/mkl-developer-reference-fortran/top/pblas-routines/pblas-level-2-routines/p-syr2.html).

**Comment by damianmoz** [comment]
Not for me. When I go to the BLAS module documentation, and click on the MKL link, it does to
```
https://www.intel.com/content/www/us/en/develop/documentation/onemkl-developer-reference-fortran/top.html
```
Do you want to try it again?

**Comment by ghbrown** [comment]
I should have been more specific, it's the links for the actual routines/routine families. Try for example, SYR2.

**Comment by bradcray** [comment]
Thanks for pointing this out @ghbrown.  For your example of SYR2, does it seem correct we'd now want to use:

https://www.intel.com/content/www/us/en/develop/documentation/onemkl-developer-reference-fortran/top/blas-and-sparse-blas-routines/blas-routines/blas-level-3-routines/syr2k.html

If so, maybe fixing them is a matter of query-replacing the base URL with this new one and making sure we get the correct level of BLAS in the link?

**Comment by bradcray** [comment]
(and/or: Is it lame that we're relying on a vendor's man pages at all...  are there community / open BLAS documentation pages we could be using instead?  Or are these routines MKL-specific in some way?)

**Comment by ghbrown** [comment]
I'm not as much of a BLAS-head as I'd like to be, but that new page is definitely in the right ballpark. Even if there are minor changes, it probably suffices to link to any BLAS doc page that's "close enough", since Chapel's BLAS module wraps up some of the arguments for convenience and things will never be 1 to 1 anyway.


>Is it lame that we're relying on a vendor's man pages at all... are there community / open BLAS documentation pages we could be using instead?

I wouldn't say lame, but I was a bit surprised to see Intel in the URL. If OpenBLAS had their own docs I would definitely suggest using those, but it seems they refer users to the [Netlib BLAS docs](https://netlib.org/lapack/explore-html/db/dc9/group__single__blas__level3_ga6ee4760a413296c246b1ecbc1ac985a0.html).

If I had to make a partially educated guess, I suspect the person who set the old URLs did it because the Intel website is/was a bit more modern and easier on the eyes (though it lacks some of the depth Netlib provides).


>Or are these routines MKL-specific in some way?

Not that I know, but I try to use OpenBLAS where possible. As I understand it, BLAS is almost as much a standard as it is a library these days, so vendors probably aren't straying too far from the norm (pun intended). But I could see Intel providing some extra functionality, etc.

**Comment by ghbrown** [comment]
I'm working on fixing this now, but and stumbled upon this in the first couple sentences of the BLAS module docs (somehow missed it before):

> While [netlib](https://www.netlib.org/blas/#_documentation) provides the official reference version of BLAS, this documentation refers to the [MKL BLAS](https://software.intel.com/en-us/mkl-developer-reference-fortran) documentation, due to interface similarities.

The choice to make is:
- Netlib: old school looking website, Fortran source code given, call graph to other BLAS and LAPACK given, different page for each data type (real, complex, etc.), open source
- MKL: more modern website with inline rendered mathematics, no source code, no call graphs, single page for each data type (for example `?gemm` for matrix multiplication), closed source

Noting that there is already a link to the official Netlib docs at the very top of the page, I don't mind using MKL so much and it does provide some tangible benefits.

@bradcray I'll fix it with proper MKL links for now since that's how it was, but let me know if you all prefer Netlib.

**Comment by bradcray** [comment]
@ghbrown : Thank you for jumping on this!  I've been buried in release notes, so haven't had the time to give it another thought since you originally filed it.  Though the "official" label on netlib sounds appealing, I think I'd go with the MKL as well after weighing the tradeoffs, as you did, and for much the same reasons.  I suppose we could offer both links, which would also give us some redundancy, but...  let's leave that for future efforts to consider.  Esp. since MKL points to Netlib.
