### ISSUE TITLE
Codec Support

### ISSUE THREAD

**Issue by Ethan-DeBandi99** [chapel-lang/chapel#20754]
An Arkouda user request support for being able to `encode`/`decode` between varying codecs. The Arkouda issue is [#1799](https://github.com/Bears-R-Us/arkouda/issues/1799) for reference.

The user is requesting Python like `encode`/`decode` support for Arkouda `Strings` objects. Currently, we would need at least the ability to go between `idna`, `ascii` and `utf-8` in Chapel.

I looked through the documentation and saw that Chapel has support for `encode`/`decode`, but not in the way we would need here. From what I am seeing, we are only able to `encode` UTF-8 to bytes and decode bytes to UTF-8.

If I missed something and this is already possible, please point me in the right direction.

**Comment by bradcray** [comment]
@jhh67 / @mppf: Is the plan for new encoder/decoder features likely to help with this scenario?

**Comment by mppf** [comment]
AFAIK, no. I think this is a lower level request about encoding UTF-8 strings into other encodings. I poked around online a little bit to learn a little about idna (as I was unfamiliar) and the most helpful reference I found was this: https://unicode.org/faq/idn.html . I would imagine that the way to implement UTF-8 -> IDNA support would be by calling an existing C implementation. But, I don't know what existing C implementations there are that we could use or recommend.

**Comment by bradcray** [comment]
Ah, _that_ form of encoding/decoding, got it.  Seems so obvious now that you've said it, I think wishful thinking just made me leap before thinking very carefully.

**Comment by bradcray** [comment]
Tagging @bmcdonald3 and @ronawho here, due to the Arkouda angle.

**Comment by ronawho** [comment]
FWIW I know virtually nothing about encodings, so not sure how helpful I can be here.

**Comment by ronawho** [comment]
Support for IDNA and some other encodings was added to arkouda in https://github.com/Bears-R-Us/arkouda/pull/1897. @Ethan-DeBandi99 @bmcdonald3 is this done now, or is there something we'd like to to in Chapel that we'd like to keep this open for?
