### ISSUE TITLE
Ability to specify job name when launching SLURM task

### ISSUE THREAD

**Issue by Ujustwaite** [chapel-lang/chapel#20764]
SLURM job name (-J) appears to be configured in the appropriate

```
runtime/src/launch/
```
file for the compiled scheduler (sbatch / srun command). Would it be possible / feasible to make this job name user configurable or set by argument without the need to recompile?

**Comment by ronawho** [comment]
I believe this was done in https://github.com/chapel-lang/chapel/pull/19750, though it was originally for internal usage so I don't think it has any user-facing documentation at the moment.

`CHPL_LAUNCHER_JOB_PREFIX` should allow you to set a job prefix (where the suffix is the executable name) and `CHPL_LAUNCHER_JOB_NAME` should let you set the job name.

Does one of those work for you?

cc'ing @jhh67

**Comment by Ujustwaite** [comment]
@ronawho @jhh67 

That may work, thank you. Let me see if we can set those in our launch context here.

**Comment by Ujustwaite** [comment]
This worked perfectly. Thank you!

**Comment by bradcray** [comment]
@ronawho: This issue reminds me:  While helping @sdbachman get ramped up on his multi-locale runs, I found myself looking through the launcher source code to find `CHPL_LAUNCHER_*` environment variable names and then searched docs to see if I was missing mentions of them, but didn't get hits.  Would you agree that this is a gap in our documentation currently?  (in which case, I'll open an issue).

**Comment by ronawho** [comment]
You're right that many env var options to the launchers aren't documented well. This is a gap in the docs for sure, but I'm not sure the right fix is to just document everything we have. Some options aren't particularly stable or well thought out and were just whatever we needed at the time to test on a system and others might have different names across launchers and it'd be great to unify them. And in some cases it really seems like we should have command line and env var methods for setting options.

Maybe the right stepping stone would be to document what we have now with a disclaimer about stability for most options?

**Comment by bradcray** [comment]
> Maybe the right stepping stone would be to document what we have now with a disclaimer about stability for most options?

Yeah, that's what I was imagining.  And maybe not _everything_ we have right now, but those components that seemed most valuable or FAQ'd.  I'll open an issue.
