### ISSUE TITLE
LinearAlgebra.Matrix doesn't support strided ranges

### ISSUE THREAD

**Issue by ghbrown** [chapel-lang/chapel#20789]
### Summary of Problem
The docs for `LinearAlgebra.Matrix` say one version of the function takes in two ranges and returns an allocated matrix of given element type. However, while attempting to write an index neutral linear algebra routine I discovered that strided arrays seem to cause issues.

To properly support index neutral linear algebra, I'd like to be able to specify multidimensional indices using the `Matrix` routine.

(I looked for duplicate issues and notes about this limitation in the documentation but found nothing.)

### Steps to Reproduce

**Source Code:**

```chapel
M = Matrix(0..1,0..1,eltType=real); // compiles
M = Matrix(0..1 by 1, 0..1 by 1, eltType=real); // fails to compile
```

**Compile command:**
`chpl`

**Execution command:**
`./<executable>`

### Configuration Information
```
chpl version 1.29.0 pre-release (8c86ba7079)
  built with LLVM version 14.0.6
```

**Comment by bradcray** [comment]
@ghbrown: It's a common oversight in Chapel to write a routine for the unstrided range case and not consider the strided range case (either not to preclude it or not to support it properly, depending on the situation).  This is part of what has been leading us to investigate changes to the range type in the language such as https://github.com/chapel-lang/chapel/issues/17122 and https://github.com/chapel-lang/chapel/issues/18215.

In this case, the specific issue is that those overloads of `Matrix` take an argument of type `range` which today means "must have `int` indices, unit stride, and both bounds".  If we go the other extreme and let those routines take any `range` type:

```patch
--- a/modules/packages/LinearAlgebra.chpl
+++ b/modules/packages/LinearAlgebra.chpl
@@ -551,13 +551,13 @@ proc Matrix(rows, cols, type eltType=real) where isIntegral(rows) && isIntegral(
 
 
 /* Return a square matrix (2D array) over domain ``{space, space}`` */
-proc Matrix(space: range, type eltType=real) {
+proc Matrix(space: range(?), type eltType=real) {
   return Matrix({space, space}, eltType);
 }
 
 
 /* Return a matrix (2D array) over domain ``{rowSpace, colSpace}`` */
-proc Matrix(rowSpace: range, colSpace: range, type eltType=real) {
+proc Matrix(rowSpace: range(?), colSpace: range(?), type eltType=real) {
   return Matrix({rowSpace, colSpace}, eltType);
 }
```

then your code compiles without complaint.  Whether there will be further problems downstream, I haven't investigated (yet, at least).

**Comment by ghbrown** [comment]
Thanks for the clarification, that's more subtle than I expected, but a good fact to know going forward.

I definitely got caught in the "ranges can be anything that looks like a range from the range documentation" trap. Even after looking them over again it seems the docs imply `range` is generic (only hiding `range(?)` away in a helper function at the end). Especially if this is where `range`s are heading I think this style is probably good, but a warning at the top (or just not the bottom) with a two line example *may* have saved me.

As for the linked efforts, I think I agree on the ease of use (and documentation) and consistency fronts, though I don't know the performance implications.

As for `LinearAlgebra.Matrix` specifically, something may need to be done with the routines that take `range` if we're going to achieve index neutrality a la #17624 (if we decide index neutrality encompasses non-unit stride).

**Comment by bradcray** [comment]
I agree that #17624 in its purest form would want to accept strided ranges.  I ran a patch in which I changed all `: range` arguments to `: range(?)` and nothing broke.  But of course, that doesn't mean that nothing will break if strided ranges are passed into these routines, say—it just means that permitting them to take strided ranges doesn't break any existing tests.

**Comment by ghbrown** [comment]
Closing in light of #20810 and discussion therein.

**Comment by ghbrown** [comment]
Closing in light of #20810 and discussion therein.
