### ISSUE TITLE
Proposal: Unary negation on unsigned integers should give an error

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#20807]
In https://github.com/chapel-lang/chapel/issues/20629, we have been wrestling with what `-myUint32` should do specifically, and what applying `-` to a `uint(w)` should mean more generally.  The current leading proposal is to make this an error for all uint widths since:

* uints can't support negative numbers, so the operator can't return a `uint(w)`
* the current behavior of promoting up to the next signed integer size, `int(w*2)` when possible, erroring otherwise, makes it hard to compute at a given bit-width
* making it an error may help users catch unintentional mistakes in their code
* making it an error permits us to change the behavior in the future if we think it's compelling, whereas choosing another approach does not

Please give this issue a thumbs-up if you agree with the proposed direction, or add a comment if you do not and/or would like to propose another approach.

**Comment by lydia-duncan** [comment]
I believe this was resolved by #20805, closing
