### ISSUE TITLE
should split init and copy elision work with a sync block?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#20974]
Currently:
 * the spec indicates that split init and copy elision do not consider/go in to `sync` blocks
 * however, the implementation currently allows copy elision across a sync block (but not split init)

Complete example:

<details>

``` chapel
class C { }
record R {
  var x: int = 0;
  var ptr: owned C = new owned C();
  proc init() {
    this.x = 0;
    writeln("init");
  }
  proc init(arg:int) {
    this.x = arg;
    writeln("init ", arg);
  }
  proc init=(other: R) {
    this.x = other.x;
    writeln("init= ", other.x);
  }
}
operator R.=(ref lhs:R, rhs:R) {
  writeln("= ", lhs.x, " ", rhs.x);
  lhs.x = rhs.x;
}


proc syncSplitInit() {
  writeln("syncSplitInit");
  var x: R;
 
  sync {
    x = new R(1); // split init not applying to sync blocks
  }
}
syncSplitInit();

proc fOut(out arg: R) {
  arg = new R(2);
}

proc syncSplitInitOut() {
  writeln("syncSplitInitOut");
  var x: R;
 
  sync {
    fOut(x);
  }
}
syncSplitInitOut();


proc syncCopyElide() {
  writeln("syncCopyElide");
  var x = new R(1);
 
  sync {
    var y = x; // copy elision applies to sync blocks
  }
}
syncCopyElide();
```

Current output:
```
syncSplitInit
init
init 1
= 0 1
syncSplitInitOut
init
init 2
= 0 2
syncCopyElide
init 1
```

</details>

I think that split init and copy elision across a `sync` block are harmless, if not frequently needed. We certainly can't do split init or copy elision with a `begin`, and `sync` is frequently combined with `begin`, but the same could be said for `serial`, and we allow copy elision there.

Which should we do?
1. Allow copy elision and split init for sync blocks? (updating the spec and the split init implementation).
2. Don't allow copy elision or split init for sync blocks (updating the copy elision implementation to disallow it)

**Comment by bradcray** [comment]
I agree that if there's no inherent reason not to allow it for both, that would be attractive.

**Comment by lydia-duncan** [comment]
Looking at the spreadsheet of topics, this looks to be below the bar but also like you two are on the same page on the direction (which is update the spec).  Does that make this an action item?  Should it be discussed?

**Comment by mppf** [comment]
I'm not sure we have time/space for the implementation effort here in the next few weeks, but I suppose we could update the spec. However, I'd expect we'd need more buy-in on the decision before we can do that. Maybe it could be a quick topic?

**Comment by lydia-duncan** [comment]
Sure, can you send me and Michelle a message with the intro to the topic you'd use and the proposal (and the context that you would like this to be a quick topic since I doubt Michelle is reading this issue on her own)?
