### ISSUE TITLE
isCopyableType with a sync type argument is triggering a sync deprecation warning for unclear reasons

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#20984]
### Summary of Problem
The following code triggers the warning:
```
$CHPL_HOME/modules/standard/Types.chpl:267: warning: Initializing a type-inferred variable from a 'sync' is deprecated; apply a 'read??()' method to the right-hand side
```
This seems wrong to me - we should have replaced uses of this deprecated functionality internally and it seems like the error should only matter for instances of the type rather than for interactions with the type itself.  As a caller, I would not expect `isCopyableType` to need to make an instance and so run into this error.

In looking briefly at the compiler handling, it kinda looks like the `init=` is getting inserted into the code calling `isCopyableType` but I'm not sure why and it seems to happen at a point in resolution after preFolding the primitive away.  My guess was something to do with the argument, but passing `sync string` as a type argument to an ordinary function didn't seem to trigger it.

`isCopyableType` itself is "no doc"ed, but is used in our array implementation and the implementation of our collection types.  I discovered this when making a record with an array of arrays of syncs and not explicitly doing anything with the field in the initializer.  It seems rarer that a user will run into it themselves but if they do, I'm not entirely certain what they would do to squash the warning.

### Steps to Reproduce

**Source Code:**
Direct way to trigger the warning:
```chapel
var x: sync string;
writeln(isCopyableType(x.type));
```

Way I encountered the warning in the wild (generalized):
```chapel
record Foo {
  var x: [0..3][0..3] sync string;
  var otherField: int;

  proc init(val: int) {
    otherField = val;
  }
}

proc main() {
  var f = new Foo(3);
  writeln(f.otherField);
}
```

**Compile command:**
`chpl foo.chpl`

**Execution command:**
N/A

**Associated Future Test(s):**
[`test/library/standard/Types/copyable-sync-string.chpl`](https://github.com/chapel-lang/chapel/blob/main/test/library/standard/Types/copyable-sync-string.chpl) #20986 
[`test/types/sync/lydia/arrayOfArrayOfSyncsInField.chpl`](https://github.com/chapel-lang/chapel/blob/main/test/types/sync/lydia/arrayOfArrayOfSyncsInField.chpl) #20986

### Configuration Information

- Output of `chpl --version`: 1.29.0 pre-release
- Output of `$CHPL_HOME/util/printchplenv --anonymize`: N/A
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: N/A
- (For Cray systems only) Output of `module list`: N/A

**Comment by lydia-duncan** [comment]
(Note: on main when this issue is opened, the location of the error message just points into ChapelSyncvar, but adjusting the deprecation message to use the deprecated keyword instead of a compilerWarning points to the Types module trigger)

**Comment by mppf** [comment]
isCopyableType calls `__primitive("is copyable type", t)`. The compiler implements that primitive by trying to resolve an `init=` (copy initializer). But for sync/single, that copy initializer produces a warning.

**Comment by lydia-duncan** [comment]
In the compiler code I was looking at, it seemed like it just did the comparison itself to start during preFold and replaced the primitive call, which is why I got confused why it was adding the `init=` later

**Comment by mppf** [comment]
@lydia-duncan - it's unclear to me why this is marked Chapel 2.0. If it's a bug we could fix it, right? And if it is not, is there an alternative design proposed that we know will break programs?

**Comment by lydia-duncan** [comment]
It is causing a function we intend to support for 2.0 to generate a deprecation warning that the user has no control over.

I view bugs that generate unnecessary and confusing deprecation warnings as needing to be resolved before 2.0.  If we don't resolve them, the user will start to not trust deprecation warnings and that will defeat their purpose, making 2.0 more shaky as a result.

**Comment by mppf** [comment]
We could adjust the implementation of `isCopyableType` to return `false` for `sync` and `single`. Not sure if that will get us into other problems though.

**Comment by mppf** [comment]
This issue reminded me of some open questions around canResolve that I didn't see issues for, so I created #21324, but I think that is only tangentially related to this issue since here it is about a warning.
