### ISSUE TITLE
How should arguments to attributes be passed?

### ISSUE THREAD

**Issue by arezaii** [chapel-lang/chapel#20994]
We are discussing options for arguments to attributes (`@unstable`, for example). Currently, the limited set of attributes we have each take one argument, e.g., `@unstable "this feature is not yet stable"`. 

We envision a future where an attribute takes multiple (possibly optional) arguments, and we want to decide a few things regarding the syntax for adding attributes. 
@mppf has suggested answering the following questions to begin with:

 * Do we want all attributes to use parentheses? (this would cause breakage for current `@unstable "bla"` usages since they would have to change to `@unstable("bla")`, but arguably that is OK since we're the only ones using `@unstable` so far. Arguably, the parentheses make the syntax less error-prone to use.)
 * Do we want multiple-argument attributes to use parentheses or just add a comma? (i.e., `@unstable("Message", newFeature)` vs `@unstable "Message", newFeature`).
 * If parentheses are not required for single or multiple argument attributes, do we want to allow them in case a user wishes to write the attribute that way?

The goal here is to pick an acceptable/preferred syntax for attributes and their arguments.

**Comment by arezaii** [comment]
> Do we want all attributes to use parentheses? (this would cause breakage for current @unstable "bla" usages since they would have to change to @unstable("bla"), but arguably that is OK since we're the only ones using @unstable so far. Arguably, the parentheses make the syntax less error-prone to use.)

I think this would be my choice if I was to make the decision alone. I like that it's consistent with expectations most people would have for arguments, and the breaking change would be pretty easy to fix. I count 61 locations within `modules/` and another 19 or so in `test/`.

**Comment by mppf** [comment]
Arguably the parentheses form would make syntax similar to named argument passing less strange. E.g. `@unstable(message="Bla", kind=prototype)`. Vs `@unstable message="bla", kind=prototype` feels more like new and strange syntax.

**Comment by bradcray** [comment]
No parens for multiple arguments seems worrisome to me from a "Where do we stop parsing the attribute?" perspective so I'd prefer to use parens in those cases.  Like Ahmad, I'd likely choose to require parens in the single-argument case as well for consistency.  And making them look a bit more like subroutine calls / argument passing also seems attractive to me.

If we had a 0-argument attribute, I probably wouldn't require parens to be used with it and might think of it more like a paren-less procedure.

**Comment by arezaii** [comment]
> If we had a 0-argument attribute, I probably wouldn't require parens to be used with it and might think of it more like a paren-less procedure.

I like this as well I think it makes a lot of sense for attributes without arguments. 
```
@attributeName
//vs.
@attributeName()
```

To me, the paren-less syntax is more appealing in the attributes use case

**Comment by bradcray** [comment]
@arezaii : A question related to our last exchange that occurred to me after your recent demo:  I think `@unstable` currently takes a single string argument.  In your current work, are you turning that into a single parenthesized argument?  Or do single-argument attributes not require parens?  Or is this all still TBD / up for design discussion?

**Comment by arezaii** [comment]
It remains to be decided which way to proceed there, I just wanted to show what was possible with the demo. 

The initial work I have done attempts to ease the transition by maintaining support for `@unstable <string-arg>`. As a side effect, that enables the use of _any_ attribute which requires a single string argument to be written without parens. 

So in the branch I have today, both `@unstable("message")` and `@unstable "message"` are supported, but I don't think that's what we want in the long-term. 

The same question will probably arise for `deprecated` (which I am hoping we can all agree to replace with `@deprecated`), which supports no args or a single string arg today, and I expect that we'd want them both to behave alike.
  

Again, the decision remains to be made one way or the other on this (I don't have an issue for it yet), but I wanted to show that we could keep that support if there was a desire for it.

**Comment by arezaii** [comment]
> ```chapel
> @attributeName
> //vs.
> @attributeName()
> ```
> To me, the paren-less syntax is more appealing in the attributes use case

Revisiting this after trying to implement it because allowing attributes without requiring parens leads to parser conflicts when trying to enable attributes on all stmts.

To be clear, if we require parens on attributes, the conflict goes away.

I am not sure how to resolve the conflict and could use some help deciding if it's worth pursuing a resolution over just requiring empty parens on attributes with no arguments. In brief conversations with Michelle and David L, it appears to be a difficult, if not unresolvable conflict.

Is it acceptable to require the parens after attributes?

**Comment by mppf** [comment]
Oh, and one more idea. Would it be possible to not require parens for attributes applied to symbols, but to require the parens when they appear in more places within the parser? Is that a reasonable approach? Arguably the common case with these attributes (at least, today) is to apply them to a `proc` or `var` or `class` etc.

**Comment by arezaii** [comment]
> To be clear, I think you are talking specifically about attributes that take no argument, right?

Correct, here I am proposing we would require parens in all cases, where as previously I was advocating for omitting them in the empty/zero argument case. 

For attributes with 1 or more arguments, I maintain that we require parens, which is only a departure for current `@unstable` and `deprecated`, and there's a separate issue for that question in #21487

**Comment by lydia-duncan** [comment]
I think it would be handy to allow argument-less attributes to be used without parentheses, but since it is causing problems, I am okay with not allowing it.  I'd rather it be consistent than depend on where the attribute was attached - I think it will be confusing for users otherwise

**Comment by arezaii** [comment]
> Would it be possible to not require parens for attributes applied to symbols, but to require the parens when they appear in more places within the parser? Is that a reasonable approach?

I think it would be possible, but I believe (without trying it) it would require creating duplicate production rules for attributes. As a user, I think it would be confusing to be use `@attribute` in one place and `@attribute()` in another, but it's something we could consider.

**Comment by bradcray** [comment]
@arezaii : I'm also a fan of requiring parens for all arg-taking attributes.  I liked the idea of not having to use them for 0-arg attributes.  Do you have an example in-hand as to why it is a conflict for certain statement types?  I was expecting that the `@` was going to be so unique that it wouldn't lead to conflicts or ambiguities.

**Comment by dlongnecke-cray** [comment]
I like the idea of requiring parens in all cases. I'd take it a step further and just require the attributes to be terminated with a semi-colon. I think that's consistent with the rest of the language. But that's just my take, and it sounds like it might not be very popular.

If there are parsing issues, e.g., a shift-reduce conflict with something like:

```chapel
@attribute
(x, y) = foo();
```

I think we solve that by preferring the assignment.

Another trick that we've used in the past for `proc` expressions is that we actually use a token like `attribute(`. I think that is effectively just preferring the attribute instead of the assignment, though.

I don't like the idea of allowing no parens for symbols but requiring them elsewhere. I think we should be consistent everywhere.

**Comment by lydia-duncan** [comment]
> I'd take it a step further and just require the attributes to be terminated with a semi-colon. I think that's consistent with the rest of the language (and in that case you can easily make zero-arg parens optional).

I would compare attributes less to a completed call (like I think you're implying here) and more like a property of the statement they are attached to.  With that in mind, I would view what you are suggesting as akin to writing:
```chapel
proc;
foo(x: int): int { ... }
```

or
```chapel
forall; x in arr { ... }
```
So I'd prefer we not go that far :) To put it another way, attributes don't have a meaning on their own, their only meaning is relevant to the symbol or statement to which they are applied.

**Comment by arezaii** [comment]
I am far from an expert in reading bison output, but the example @dlongnecke-cray presents is similar to the one I was imagining. 

I believe there is ambiguity as to whether the parser should treat `(x,y)` as arguments to the `@attribute` or the receiver for the call to `foo()`

It's possible I misinterpreted the output from Bison, which is a motivating factor for asking for more help deciding how to proceed.

If it's something we can address with precedence, I'm happy to explore that route before shelving parenless-attributes.

**Comment by bradcray** [comment]
> I believe there is ambiguity as to whether the parser should treat (x,y) as arguments to the @attribute or the receiver for the call to foo()

That's a good example, thanks!

A few alternatives we could consider:
* only permit attributes to be attached to statements that begin with a keyword (and, possibly, compound statements if that's too onerous)—I think most of the cases we've discussed we would want to attach to a declaration or a loop...?
* have attributes be whitespace-sensitive (e.g., they must end with a newline; or the arguments must immediately follow the attribute name with no space; or the arguments' opening paren must start on the same line as the attribute name itself)

**Comment by mppf** [comment]
> only permit attributes to be attached to statements that begin with a keyword

I like this idea but it actually might be even easier. Maybe we can just prevent attributes from applying to a parenthesized group.

In other words,

```
(x, y) // tuple expression

// what if I add an attribute?
@attribute
(x, y)
// that leads to an error
```

(it would parse as @attribute(x,y) but then find that isn't a legal attribute), as would

```
myfunction(arg1, arg)

// what if I add an attribute?
myfunction @attribute (arg1, arg2)
// that leads to an error (similarly)
```

Point being, I don't think it's actually useful to have `@attribute` available in literally every place in the parser. I think we only have motivating examples for attributes on loops, in addition to symbols (proc / var / class / module / etc).

**Comment by arezaii** [comment]
> I think we only have motivating examples for attributes on loops, in addition to symbols (proc / var / class / module / etc)

What about callsites? I thought one of the motivating reasons for this was the desire to suppress warnings from library code at the point of use. Would we just change that to blocks and suggest people wrap the callsite in a block with whatever attribute suppresses the specific warning?

**Comment by mppf** [comment]
IMO that would be OK in the near term, but I also expect that we could extend to calls specifically without running into the patterns I described above (that I would expect are the sources of the ambiguity).

Of course, all that said, updating the parser can be unpredictable. I just want to be sure we are not trying too hard to solve problems that don't need to be solved in the near term.

**Comment by arezaii** [comment]
Ok, with some changes I was able to allow attributes on loops, blocks, and decls, and allow attributes without parens, without parser conflicts. There's nothing right now to build the attribute nodes on the loops or blocks, but they parse. The changes are now in the draft PR https://github.com/chapel-lang/chapel/pull/21425

**Comment by arezaii** [comment]
I attempted to allow named arguments to attributes and had some initial success with this on updated PR #21425.

**Comment by arezaii** [comment]
Closing as https://github.com/chapel-lang/chapel/pull/21425 implements attributes that accept arguments with optional names, in parentheses. (There is a deprecation for `@unstable "msg"` that still allows a single string literal argument without parens, but this will be removed in the next release cycle)
