### ISSUE TITLE
should we deprecate bool(w)?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#21002]
Today most uses of `bool` are just `bool`. But it's possible to specify a particular width with `bool(8)`, `bool(64)`, etc.

However there are a number of bugs / odd behaviors related to this:
 * #19976
 * #13142

One way that `bool(w)` is particularly odd is that there is no `w` where `bool == bool(w)` unlike the pattern for e.g. `int` being `int(64)`.

It has been proposed that once we have an alignment attribute (#20945) we might be able to deprecate `bool(w)`.

Should we try to deprecate `bool(w)` in favor of using an alignment attribute?

**Comment by bradcray** [comment]
I'm generally very in favor of replacing `bool(w)` with an alignment capability.  I'd even be comfortable with deprecating and getting rid of `bool(w)` before we had an alignment capability (as I don't think it's been used in practice enough to require an alternative if we were to deprecate it).

Something not entirely clear to me when you say things like:

> One way that bool(w) is particularly odd is that there is no w where bool == bool(w) unlike the pattern for e.g. int being int(64).

is whether you're proposing...  oh wait, now I'm seeing #21003, that's what I'm wondering about.
