### ISSUE TITLE
should we adjust lifetime of call-expression temporaries?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#21001]
Today, we compute deinitialization point of a temporary as:
 * the end of the block, if the temporary is in a variable initialization (including split init)
 * the end of the statement, otherwise
 
See also
 * https://chapel-lang.org/docs/language/spec/variables.html#deinit-points
 * https://chapel-lang.org/releaseNotes/1.21/01-language.pdf slide 73

Here is a code sample showing how different cases behave:

``` chapel
record R {
  proc deinit() {
    writeln("R.deinit()");
  }
}

proc returnAnR() {
  return new R();
}

proc g(arg) { return 1; }

proc notSplitInit() {
  writeln("starting notSplitInit");
  var x = g(returnAnR()); // currently, the R is deinited at end of block
  writeln("ending notSplitInit");
}
notSplitInit();
writeln();

proc splitInit() {
  writeln("starting splitInit");
  var x;
  x = g(returnAnR()); // currently, the R is deinited at end of block
  writeln("ending splitInit");
}
splitInit();
writeln();

proc assign() {
  var x = 1;
  writeln("starting assign");
  x = g(returnAnR()); // currently, the R is deinited just after this statement
  writeln("ending assign");
}
assign();
writeln();

proc notInit() {
  writeln("starting notInit");
  g(returnAnR()); // currently, the R is deinited just after this statement
  writeln("ending notInit");
}
notInit();
writeln();
```

Recently, some users brought up the concern that it might be confusing that the lifetime of a subexpression (such as `returnAnR()` in the example or something like `new shared C()`) is different if it's used in an initialization context or not.

The reason that we have the current rules are
 1. To support slicing, where `ref slice = A[1..10];` e.g., creates a temporary that needs to live to the end of the block;
 2. To support a pattern like `f.writer().write(A)` where the temporary channel is closed at the end of the statement.

There were two alternatives proposed:
 1. To change the rule to only be end-of-block if the temporary is used in `ref` initialization. This would make the rule more focused and perhaps more similar to C++ rules.
 2. To change the rule to apply to anything that is syntactically `=` whether assignment or initialization. There is some concern that this would keep values alive unnecessarily.
 
Since then, we also have identified a variant: Option 1a is like Option 1 but only extends the lifetime of the temp that we take the reference of. See https://github.com/chapel-lang/chapel/issues/21001#issuecomment-1477174420

#### What do other languages do here?

C++ deinitializes at the end of the statement for a function call used as a statement

<details>

``` c++
#include <cstdio>

struct mystruct {
  int x = 0;
  ~mystruct() {
    printf("in destructor\n");
  }
};

mystruct returnit() {
  return mystruct();
}

int acceptit(const mystruct& arg) {
  return 1;
}

void note(int arg) {
  printf("in outermost call\n");
}

int main() {
  {
    printf("entering block 1\n");
    note(acceptit(returnit()));
    printf("exiting block 1\n");
  }
}
```

</details>

It does so even if the call is nested in an initialization expression for a reference:

<details>

``` chapel
#include <cstdio>

struct mystruct {
  int x = 0;
  ~mystruct() {
    printf("in destructor\n");
  }
};

mystruct returnit() {
  return mystruct();
}

int acceptit(const mystruct& arg) {
  return 1;
}

int global = 10;

int& note(int arg) {
  printf("in outermost call\n");
  return global;
}

int main() {
  {
    printf("entering block 1\n");
    int& x = note(acceptit(returnit()));
    printf("x is %i\n", x);
    printf("exiting block 1\n");
  }
}
```

</details>

Python an Swift do not have the same kind of destroyed-at-end-of-block local objects.

Also, none of the usual languages we study have runtime types for array types, and so the details of this issue are a bit unique to Chapel.

**Comment by bradcray** [comment]
The user concern resonated with me, and I find the alternatives intriguing/attractive, particularly the first.

**Comment by mppf** [comment]
I've created an initial patch to try Option 1, but I'm running into the problem that temporaries that support array type expressions are destroyed too early.

e.g. 

``` chapel
var A1: [1..5] int;
A1 = 3;
```

the compiler implicitly inserts a domain construction `{1..5}` and this domain is being destroyed before the array is split-initialized with `A1 = 3`. I suppose that we can make an exception for the runtime components of array type expressions, but this additional complexity might make Option 2 more appealing.

**Comment by bradcray** [comment]
Bummer.

**Comment by mppf** [comment]
I have also tried to implement Option 2. 

Testing revealed a few tests that will need to be investigated / adjusted

<details>

```
[Error matching program output for arrays/ferguson/array-initialization-patterns/array-initialization-patterns-dists (compopts: 1)]
[Error matching program output for arrays/ferguson/array-initialization-patterns/array-initialization-patterns-dists (compopts: 2)]
[Error matching program output for arrays/ferguson/array-initialization-patterns/array-initialization-patterns-dists (compopts: 3)]
[Error matching program output for arrays/ferguson/array-initialization-patterns/array-initialization-patterns-dists (compopts: 5)]
[Error matching program output for arrays/ferguson/array-initialization-patterns/array-initialization-patterns-dists (compopts: 6)]
[Error matching program output for arrays/ferguson/array-initialization-patterns/array-initialization-patterns]
[Error matching compiler output for classes/delete-free/lifetimes/borrow-escapes]
[Error matching compiler output for classes/delete-free/lifetimes/errors-dead-early]
[Error matching program output for classes/errors/warn-misleading-new]
[Error matching program output for compflags/ferguson/disable-init-deinit (compopts: 2)]
[Error matching program output for types/records/expiring/deinit-point-stmt-exprs]
[Error matching compiler output for types/records/expiring/ex-errors]
[Error matching program output for types/records/expiring/more-deinit-points]
[Error matching program output for types/records/intents/inout-intent-order]
[Error matching program output for types/records/intents/inout-intent]
[Error matching program output for types/records/intents/out-intent]
[Error matching program output for types/records/split-init/split-init-array]
[Error matching program output for types/records/split-init/split-init-try-more]
```

</details>

here is the patch I used

<details>

```
diff --git a/compiler/resolution/resolveFunction.cpp b/compiler/resolution/resolveFunction.cpp
index daba6db20a..0e9f1a5c9c 100644
--- a/compiler/resolution/resolveFunction.cpp
+++ b/compiler/resolution/resolveFunction.cpp
@@ -1384,7 +1384,13 @@ static void markTempsDeadLastMention(std::set<VarSymbol*>& temps) {
         } else if (isInitOrReturn(call, lhsSe, subCall)) {
           // call above sets lhsSe and initOrCtor
         } else if (call->resolvedOrVirtualFunction()) {
-          subCall = call;
+          if (call->isNamedAstr(astrSassign)) {
+            // consider '=' also as setting a user variable
+            lhsSe = toSymExpr(call->get(1));
+            subCall = toCallExpr(call->get(2));
+          } else {
+            subCall = call;
+          }
         }
 
         // returning into a user var?
```

</details>

**Comment by bradcray** [comment]
> the main issue I see that doesn't look like noise is Fannkuch-Redux "Brad compact version"

Interesting...  On the plus side, that's not a case we care about very much (being the slowest one of the suite).  On the other hand, given that it's so compact and clean, it'd be a great case to study to understand how the approach slowed it down.

**Comment by mppf** [comment]
Regarding performance differences with Option 2: I've spent a little bit of time this morning investigating the performance difference in `test/studies/shootout/fannkuch-redux/bradc/fannkuch-redux-blc-compact.chpl`. I think that the performance difference we are seeing is due to cache behavior. I can observe a minor difference on chapcs07 (although it is smaller than in the nightly performance runs, for some reason). However, on my own PC it is comparable within the noise, and on chapdl-intel, the branch is actually faster than `main` (but not by much). These two systems have significantly more cache than the chapcs system does. At the same time, it stands to reason that if we put off deinitializing something used in an `=` call to the end of a block, that we will be allowing more time for that temporary to fall out of cache. I have not yet figured out specifically which temporary had its deinitialization moved for this benchmark.

**Comment by mppf** [comment]
Off-issue, @bradcray noticed the performance differences shown in the url below for Option 2, but he did not find these differences too worrisome:

https://chapel-lang.org/perf/chapcs/temp-assign-lifetime/?startdate=2023/02/13&enddate=2023/03/13&graphs=ssca2kernel4tepsscale8,ssca2kernel4scale8,ssca2graphconstructionscale8,ssca2scale8,luleshbradcstudyversion,submittedpidigitsshootoutbenchmark,fastareduxshootoutbenchmarkn25000000,parboilhistoserialexecutiontime,nasparallelbenchmarkscgtimingssizea,npbmgsizes,npbmgsizeb

**Comment by mppf** [comment]
Based on discussion, I'm going to next investigate Option 1 more. At first, I will try making the rule have a carve-out for arrays / runtime types and see if I can get that to pass testing.

**Comment by bradcray** [comment]
I definitely prefer option 1 from a user standpoint, so agree with spending more time there.  Capturing some other notes:

If we were to proceed with option 2, I proposed that it could be interesting to see how and when the high-water mark memory uses changed for the tests that changed in performance testing in order to:
* identify idioms in pre-existing codes that result in more memory being used
* brainstorm what a user could/would need to do to mitigate those changes, if there were any (i.e., it wasn't all testing noise)
* capture such idioms in order to advertise the kinds of things impacted by the change and available workarounds.

One thing I didn't say in the meeting is that it would also be nice to understand the impact of option 2 on Arkouda and CHAMPS given their uses of large arrays and sensitivity to memory usage.

I also wondered about the degree to which option 2 paints us into a naive corner from a language design perspective, and what/whether we could change to option 1 later either without it being a breaking change (Michael argued "no" because records could be used as a locks, which sounds right), or by enabling optimizations (e.g., "the language says I need to keep this big array of integers around, but surely I can compile that away without the user being at all unhappy about it").  This led to a question about what it would take for such optimizations to fire, the degree to which they could apply to user code (e.g., a linked list of integers), and the degree to which this would complicate the language design (maybe even more than option 1 if we can land it).

**Comment by mppf** [comment]
I have a version of Option 1 passing primers testing. It uses some special logic to use "end of block" for call-expression temporaries initializing types (as well as some other cases that are more about how the production compiler works than the language).

One thing that I am observing is that code like

``` chapel
var x: borrowed C = (new owned C(1, 10)).borrow();
```

no longer works (it generates a compile-time error "Scoped variable x would outlive the value it is set to"). This does not concern me and seems like a straightforward implication of Option 1.

Such code will need to be changed to:

``` chapel
var xTmp = new owned C(1, 10);
var x: borrowed C = xTmp.borrow();
```

**Comment by bradcray** [comment]
I'm comfortable with that change, which seems like better / less ambiguous style to me anyway.

**Comment by mppf** [comment]
The mason tests are failing with lifetime errors, but this is fixable. I've created this little example program to show the issue:

``` chapel
class C { var field: int; }

var globalOwn = new owned C(10);
var globalBorrow = globalOwn.borrow();

record myRecord {
  var b: borrowed C;
  proc init(in myInstance) /*lifetime return globalBorrow */ {
    b = globalBorrow;
  }
}


proc main() {
  // works
  var cc = new C(20);
  var x = new myRecord(cc);
  writeln(x);

  // leads to error today if no lifetime annotation is used
  class C { var field: int; }

var globalOwn = new owned C(10);
var globalBorrow = globalOwn.borrow();

record myRecord {
  var b: borrowed C;
  proc init(in myInstance) /*lifetime return globalBorrow */ {
    b = globalBorrow;
  }
}


proc main() {
  // works
  var cc = new C(20);
  var x = new myRecord(cc);
  writeln(x);

  // leads to error today if no lifetime annotation is used
  var y = new myRecord(new C(30));
  writeln(y);
}
;
  writeln(y);
}
```

Now that `var y = new myRecord(new C(30))` leads to the `new C(30)` having a smaller lifetime (to end of statement), the lifetime checker is inferring that `y` has a lifetime to the end of the statement. This can be fixed with a lifetime annotation on the initializer and it's possible that the lifetime checker could be adjusted to fix the issue as well (since the initializer is consuming `new C(30)` through the `in` intent, why does the lifetime of the actual matter?).

**Comment by mppf** [comment]
Another case I am seeing:

``` chapel
  var A : [1..1] borrowed C = [new C(1), ];
  writeln(A);
```

At present, this leads to the `C` instance being deinitialized before `A` is printed, and there is no lifetime checker error. I think the behavior change makes sense for Option 1 but we will have a TODO to look into getting a compile-time error for it.

**Comment by mppf** [comment]
At present, my draft implementation of Option 1 in PR #21894 passes testing except for 12 tests (details in details!)

<details>

```
[Error matching program output for arrays/ferguson/choose-array/choose-array5]
[Error matching program output for distributions/vass/changeBoundingBox]
[Error matching program output for library/packages/Futures/futures-doc-chaining1]
[Error matching program output for library/packages/Futures/futures-waitall]
[Error matching .bad file for library/standard/Set/types/testOwnedRemove]
[Error matching compiler output for parallel/forall/task-private-vars/local-slice]
[Error matching program output for performance/sparse/domainAssignment-dissimilar]
[Error matching program output for performance/sparse/domainAssignment-similar]
[Error matching .bad file for types/tuple/ferguson/const-ref-tuple-decl]
[Error matching compiler output for users/aroonsharma/LinearAlgebra/2mm]
[Error matching compiler output for users/aroonsharma/correlation]
[Error matching compiler output for users/aroonsharma/covariance]
[Summary: #Successes = 14705 | #Failures = 12 | #Futures = 905]
```


- choose-array5.chpl -- is it a problem with the lifetime checker?
- changeBoundingBox.chpl -- some kind of latent bug in BlockDist?
- futures-chaining1.chpl,futures-waitall.chpl -- problem with futures implementation or maybe with lambdas?
- local-slice.chpl -- looks like new behavior is not working for a task private var
- domainAssignment-dissimilar.chpl,domainAssignment-similar -- unknown issue with sparse domains
- types/tuple/ferguson/const-ref-tuple-decl.chpl -- change in .bad behavior
- users/aroonsharma/{correlation.chpl,covariance.chpl,LinearAlgebra/2mm.chpl} unknown issue with zippering over slices

</details>

These failures look like implementation things to adjust. Similar to https://github.com/chapel-lang/chapel/issues/21001#issuecomment-1472582922 though, it does look like there are a few cases where the new behavior makes the lifetime checker more picky. That is the most concerning thing I have seen so far, but it seems manageable.

**Comment by vasslitvinov** [comment]
I propose a modification of Option 1: in the case of a `ref` declaration, still use the "end of statement" lifetime except for the temp that will be aliased. If the lifetime of the alias ends before the end of the block for whatever reason, the temp's lifetime should end there as well.

> since the initializer is consuming new C(30) through the in intent, why does the lifetime of the actual matter?

I agree it should not matter. The lifetime of the actual should not matter when the formal has the [const] in intent regardless of the type of the data being passed.

**Comment by mppf** [comment]
> The lifetime of the actual should not matter when the formal has the [const] in intent regardless of the type of the data being passed.

I don't think that's quite right, because it could be a class containing only 1 field which is a borrow, and that borrow could refer to something in the actual's scope that will be going out of scope soon.

**Comment by vasslitvinov** [comment]
Here is my proposal for defining Option 1 in the spec:

#### Common preamble

The compiler adds temporary local variables, or _temporaries_, to contain the results of nested call expressions, such as the call `g()` in the statement `f(g());` . The call expressions that are the initialization expressions or arguments to assignments and other operator expressions are also treated as nested calls for this purpose.

A temporary is generally deinitialized at the end of its containing statement.

#### Rule 1 continuation

If the containing statement is a declaration or split initialization of a `ref` variable, such as `ref r = f(g());` , the temporary is deinitialized at the end of its containing block.

#### Rule1a continuation

If the containing statement is a declaration or split initialization of a `ref` variable, the temporary being aliased by this variable is deinitialized at the end of its containing block, such as the temporary for the result of the call to `f` in `ref r = f(g());` .

**Comment by bradcray** [comment]
@mppf: What does "earlier" and "later" mean above?

**Comment by mppf** [comment]
I had been working with an earlier revision of Arkouda, but when I updated to the current version, the patch was no longer necessary (in fact it made it not compile).

**Comment by bradcray** [comment]
Sorry, I was trying to ask "how old / which revision?"  (to understand how recently the change was made and potentially why).

**Comment by mppf** [comment]
It's from https://github.com/Bears-R-Us/arkouda/pull/2202 which changed e.g. `users.getValue(name)` to `users[name]` within MetricsMsg.chpl. `map.this(key)` with a non-nilable class type value, returns a borrow. (FWIW, I was expecting it to return a `const ref` in that case).

**Comment by mppf** [comment]
I've created an implementation of Option 1a & I see 48 failures. Many have to do with tuples. Here is a small reproducer:

``` chapel
proc makeTuple() {
  var s = "hello"*2;
  return (0,s);
}

proc acceptsTuple(tup) { }

proc main() {
  acceptsTuple(makeTuple());
}
```

```
$ chpl cc.chpl  
cc.chpl:8: In function 'main':
cc.chpl:9: error: Reference to scoped variable read_x0 reachable after lifetime ends
cc.chpl:9: error: Reference to scoped variable read_x1 reachable after lifetime ends
```

**Comment by mppf** [comment]
Another case that Option 1a causes to fail is this

``` chapel
  const ref r = if option then makeR() else makeR();
```

**Comment by mppf** [comment]
I am also seeing a failure with Option 1a in the following case:

``` chapel
proc getArrayCopy(A) {
  var AA = A;
  return AA;
}

proc main() {
  var A: [1..10] int = for i in 1..10 do i;

  var BDom = {0..<10};
  ref B = getArrayCopy(A).reindex(BDom);

  writeln(B[1]);
}
```

This is a reduced form of the TestMatrix failure.

**Comment by mppf** [comment]
Here is another program that runs into a problem with Option 1a:

test/types/records/expiring/deinit-point-order-multiple.chpl 

``` chapel
  const ref v = choose(new R(1), new R(2), new R(3), new R(4), new R(5),
                       new R(6), new R(7), new R(8), new R(9), new R(10));
```

**Comment by mppf** [comment]
This snippet from test/distributions/vass/changeBoundingBox.chpl does not work with Option 1 in my draft PR

``` chapel
var D: domain(1) dmapped new dmap(dist);
```

This adjustment gets it working
``` chapel
var dmap = new dmap(dist);
var D: domain(1) dmapped bla;
```

I am thinking of just adjusting the compiler to make `new dmap` create something that is end-of-block, but I am open to other suggestions as well. I just don't want to do a side-quest on how `dmapped` is implemented, if I can avoid it.

**Comment by mppf** [comment]
We've reached consensus to proceed with Option 1. (https://github.com/Cray/chapel-private/issues/4544 includes some details, for those who can see it). I have implemented this in #21894 which passes testing, and earlier versions of that same change worked with Arkouda and CHAMPS.

Option 1 is:

> To change the rule to only be end-of-block if the temporary is used in `ref` initialization. This would make the rule more focused and perhaps more similar to C++ rules.

Here are some before/after examples:

### Behavior stays the same for nested call expressions not in a variable inititialization expression

Behavior in this case is not changing.

``` chapel
{
  a(b());
  ... // other statements in a block
}
// compiler translates into
{
  var bResult = b();
  a(bResult);
  destroy bResult; // nested call expression temporary not in var/ref init destroyed at end of statement
  ... // other statements in block
}
```

### Behavior stays the same for `ref` and `const ref` declarations

The example below shows `ref` but it would be the same with `const ref`. This behavior is not changing.

``` chapel
{
  ref x = d(e());
  ... // other statements in a block
}
// compiler translates into
{
  var eResult = e();
  ref x = d(eResult);
  ... // other statements in block
  destroy eResult; // nested call expression temporary in ref init is destroyed at end of block
}
```

### Behavior changes for `var` and `const` declarations

The example below shows a `const` declaration but `var` declarations are similar.

Here is the *before* behavior:

``` chapel
{
  const y = f(g());
  ... // other statements in a block
}
// compiler translates into
{
  var gResult = g();
  const y = f(gResult);
  ... // other statements in block
  destroy gResult; // nested call expression temporary in var init is destroyed at end of block
}
```

Here is the *after* behavior:


``` chapel
{
  const y = f(g());
  ... // other statements in a block
}
// compiler translates into
{
  var gResult = g();
  const y = f(gResult);
  destroy gResult; // nested call expression temporary destroyed at end of statement just like outside of variable declaration contexts
  ... // other statements in block
}
```

**Comment by mppf** [comment]
One late-breaking issue with this is that it breaks the `var locStr = myString.localize().c_str();` pattern, because the result of `localize()` will be destroyed at the end of the statement, but `.c_str()` might return a string borrowing its buffer. However, AFAIK, we are leaning towards deprecating that pattern & my own expectation is that we will end up with a single function to do both of these steps.

**Comment by vasslitvinov** [comment]
Meanwhile we could replace `var locStr` with `const ref locStr`.

**Comment by mppf** [comment]
Yes that is what PR #22630 does, among other things.
