### ISSUE TITLE
Should c2chapel generate `c_ptr(c_char)` rather than `c_string`?

### ISSUE THREAD

**Issue by bmcdonald3** [chapel-lang/chapel#21053]
In https://github.com/chapel-lang/chapel/issues/14215, there has been talk of deprecating `c_string` for `c_ptr(c_char)`, so should c2chapel be updated to instead use `c_ptr(c_char)` to encourage the change to `c_ptr(c_char)`?

It seems likely we would first want to bring `c_ptr(c_char)` up to the same functionality as `c_string` prior to making this change (see https://github.com/chapel-lang/chapel/issues/21052).

**Comment by mppf** [comment]
Our `extern` block support is similarly converting `const char*` into `c_string`. It's my own opinion that we need to solve #14214 before migrating c2chapel and extern block support to remove `c_string`, but perhaps things would work well enough if that is ignored. At the very least, we would change the type twice if we don't solve #14214 first, which might be annoying to adapt code to.

**Comment by bradcray** [comment]
I was expecting #14214 to prevent Ben from using `c_ptr(c_char)` in the recent example that made me aware of this, but it seemed to work well enough for him to my surprise.  I hear the "potentially annoying to change the type twice" comment, but am not sure I want to keep leaning on `c_string` if it won't cause things to blow up on users (and if ceasing to use it does, that'll provide some additional incentive to solve #14214 :) ).

**Comment by mppf** [comment]
> I was expecting #14214 to prevent Ben from using `c_ptr(c_char)` in the recent example that made me aware of this, but it seemed to work well enough for him to my surprise.

Not sure of the exact details but I would expect errors along these lines to only come up with the C backend. The LLVM backend does not represent `const` pointers in the type system and so doesn't care so much if we are turning `const char*` into `char*` etc.

**Comment by bradcray** [comment]
Ah, that might be exactly why I was surprised.  @bmcdonald3 : Not a priority, but before it gets too stale, would you try compiling the example where `c_ptr(c_char)` was working for you with the C back-end to see if it breaks the C compilation step?

**Comment by bradcray** [comment]
> The LLVM backend does not represent const pointers in the type system

@mppf: Slightly off-topic, but it seems as though this could potentially have performance implications?  Or does the LLVM IR not support representing them?  (I read your comment as suggesting it could but that we don't take advantage of it?)

**Comment by mppf** [comment]
> Or does the LLVM IR not support representing them?

Yes, they aren't represented directly in the LLVM IR. (They *can* be represented with TBAA (Type-Based Alias Analysis) metadata, and doing that or not doing that can indeed have performance implications).

**Comment by bmcdonald3** [comment]
> Ah, that might be exactly why I was surprised. @bmcdonald3 : Not a priority, but before it gets too stale, would you try compiling the example where `c_ptr(c_char)` was working for you with the C back-end to see if it breaks the C compilation step?

I was able to successfully compile with the C backend as well, not seeing any problems with the `c_ptr(c_char)` variables (though, I had added generic `extern` functions like `extern proc idn2_to_ascii_lz(a,b,c):c_int;`. where those variables are `c_string`s, I'm not sure if that is cheating? It does not work if I don't add those generic externs for either C backend or LLVM). I am getting some warnings about some other C type conversions, but none related to strings.

**Comment by mppf** [comment]
Maybe we are squashing them for GCC ? https://github.com/chapel-lang/chapel/pull/14446

**Comment by bradcray** [comment]
Just noting that we're probably closer to being able to do this now that https://github.com/chapel-lang/chapel/pull/21913 has been merged.

**Comment by riftEmber** [comment]
Closing as this was implemented in https://github.com/chapel-lang/chapel/pull/22622 ([diff](https://github.com/chapel-lang/chapel/pull/22622/files#diff-ec8cd4b09a0c4bf4e2b96dface140b4bda7f9c128df6cafcd1fb5c4ae294c3bfR273-R276))
