### ISSUE TITLE
[Spike] Investigate and propose ideas for unstable warnings

### ISSUE THREAD

**Issue by arezaii** [chapel-lang/chapel#21050]
We would like a proposal for adding attributes that better describe the reason for unstable warnings. 
Additionally, we want some flexibility to suppress some warnings.

see https://github.com/Cray/chapel-private/issues/3974 for tracking of the discussion of this topic.

**Comment by arezaii** [comment]
During this sprint we discussed some attribute ideas for adding new attribute behavior through arguments, and adding an attribute to suppress that behavior when desired. 
We mostly agreed that attribute arguments should be placed in parens, with the exception that attributes without arguments should not need parens. 
We also discussed the possibility of using a special attribute to mark something as stable, which would supplant the previously described suppression attribute.

**Comment by bradcray** [comment]
Fastest 2-point task ever!  (four minutes between opening and closing)  :D

**Comment by arezaii** [comment]
I should have added that this task replaces the previous (now backing issue) that was here, and is just to serve as documentation for the past sprint.

**Comment by lydia-duncan** [comment]
> Fastest 2-point task ever! (four minutes between opening and closing) :D

Nah, I'm sure Elliot's got one that was under a minute XD (I recommended Ahmad do this so that Cray/chapel-private#3974 could stay open)

**Comment by bradcray** [comment]
A two point one, though?

My guess was that it was it was meant to be a private issue and got closed quickly as a "whoops!"

**Comment by arezaii** [comment]
> My guess was that it was it was meant to be a private issue and got closed quickly as a "whoops!"

😬 

I've made a huge mistake
