### ISSUE TITLE
Errors Module: the `Error` base class

### ISSUE THREAD

**Issue by jeremiah-corrado** [chapel-lang/chapel#21067]
### Background

The `Error` class is the base class for all other Error types in Chapel.

It has two initializers and one method:
```chapel
proc init()
proc init(msg: string)
proc message():string
```

A variety of error types in the package modules also inherit from `Error`

### Suggestions/Questions

- Should it also provide a varargs initializer that constructs the message by writing the arguments to a channel and constructing a string:
    ```chapel
    proc init(args ...?k)
    ``` 
    - The `halt`, `warning`, and `assert` procedures also provide this
- Should `message` be a paren-less method?
    - To me, it sounds and feels more like a field than a method (but we still want the ability to override it), so it seems like a perfect candidate to be a parenless method.

**Comment by mppf** [comment]
> Should `message` be a paren-less method?
> 
>     * To me, it sounds and feels more like a field than a method (but we still want the ability to override it), so it seems like a perfect candidate to be a parenless method.

I think that's true from a matter of style. However, it's in a class heirarchy, and we can't have virtual dispatch if it's parenless and we override it in child classes. I would expect that having virtual dispatch available for it is more important than having it be parenless. In particular, without virtual dispatch for `proc message()`, subtypes will have to compute the string message when constructing the error, which might be more overhead than is really necessary.

We could alternatively make a parenless function that calls another paren-ful function to enable virtual dispatch, at the risk of complicating matters a bit.

**Comment by jeremiah-corrado** [comment]
> we can't have virtual dispatch if it's parenless and we override it in child classes.

Ok, I was unaware of that. In that case, I'd personally be fine with keeping it as is. 

I'd also be open to the idea of calling a paren-ful function from a parenles function if there is buy in from others.

**Comment by bradcray** [comment]
> Should it also provide a varargs initializer that constructs the message by writing the arguments to a channel and constructing a string:

I'd say "no".  You could imagine, by extension, that anything that takes a string should have a varargs-based implementation, and I don't think that's something we should promote.  If I were to see `new Error(1, 2, 3);` in the code, nothing about it suggests to me that it will result in the message "123".  Also, we have lots of good ways to create strings from arguments in Chapel (like `1:string + 2:string + 3:string`).

**Comment by e-kayrakli** [comment]
Should `message` be replaced with `writeThis` or its upcoming equivalent? I didn't see this coming up in the Error module review notes on a quick search, but it'd be interesting to think about.

It looks like we do have no-doc'ed [`override proc Error.writeThis`](https://github.com/chapel-lang/chapel/blob/main/modules/standard/ChapelIO.chpl#L720-L727) today that's in ChapelIO. That implementation doesn't seem to be doing much special and just generating a string that's passed to `f.write`.

Is there a special need for Errors to be represented as strings? Is that special need more than another type that just has `writeThis` instead? Should we be able to cast Errors to strings instead of having `proc message(): string`? In any case, what we are doing for Error types here doesn't seem very consistent with what we do for other types when it comes to generating strings.

**Comment by jeremiah-corrado** [comment]
In a recent design discussion on this topic, @mstrout, @dlongnecke-cray, and I unanimously decided to keep the `message` method as-is on the `Error` base class.

Our reasoning was that the `message()` method is essentially an accessor for a field on `Error` (see: https://github.com/chapel-lang/chapel/issues/9584), while `Error.writeThis`/`Error.serialize` both provide more of a debugging/io-centric functionality where the Class name and line numbers are also printed out. Because these these are distinct functionalities which are both found in user code, we thought it would be best to keep them both.

The question of whether `Error.writeThis`'s exact behavior should be changed also came up. We decided that this is a non-2.0-issue and that the behavior could evolve in the future if needed.

**Comment by lydia-duncan** [comment]
@jeremiah-corrado - I think this can be closed, is that correct?
