### ISSUE TITLE
Alternative design for type/param fields with initialization expressions

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#21075]
This issue proposes an alternative design for type/param fields with initialization expressions.

### Background: Example of Current Behavior

I will show the current situation with an example.

``` chapel
record R {
  type elementType = int;
  var element: elementType;
}
```

R is *generic-with-defaults* since `type elementType` makes it generic but that field has an initialization expression.

``` chapel
var x: R; // OK, this is creating x with type R(int), using the default
var y: R(real); // OK, this using the generic nature of R

proc f(arg: R) { } // this is a concrete function accepting R aka R(int)
proc g(arg: R(?)) { } // this is a generic function accepting any R
```

### Problems with the Current Behavior

Over time, I have become less comfortable with this generic-with-defaults idea. I have mainly two concerns.

First, I created #19120 asking if the language needs to be clearer about which types are generic and which are not. I created that issue after realizing that the compiler had some quite complicated code to determine if a type is generic. At the same time, what you can do with a type is very different if it is generic or not generic. So I think Chapel programmers need to be aware of whether or not types they are working with are generic. This issue is particularly confusing for fields because of the way that errors with field declarations lead to compilation errors in other areas of the code, such as code using or defining an initializer.

Some of the proposals in #19120 involve decorating types that are generic (e.g. using `R(?)`) to make it clearer when a generic type is intended. There are enough challenges / open questions with that approach that I think it's unlikely we will use that approach.

As a result, the situation is that *for a given type name*, a Chapel programmer needs to be able to know if it is generic or not generic, in order to communicate their intent in their source code (e.g. when creating a record or class using that type as a field). The problem I have with the current generic-with-defaults behavior is that it creates types that are neither generic nor not generic. So it is a third category that programmers need to be aware of. Furthermore, I don't think that the source code clearly indicates what is going on for generic-with-defaults in a way that teaches the language. Rather, I think it adds confusion. Seeing something like `var x: R; writeln(x);` working leads one to believe that R is concrete; but it is not.

The second problem is that the current behavior interprets what appears to be a type alias in a confusing way, especially for programmers familiar with C++. Issue #12613 brought up a case where a user wanted to create a type alias within a generic class or record. However, as discussed above, in Chapel as it is currently defined, writing a record like `record R { type t = map(int, string); }` creates a record that is generic-with-defaults, so that other types can be provided for `t`, but if none was specified, `map(int, string)` will be used. But, in the case of that particular issue, all that was desired was to make a shorthand for another type.

A related point here is that, for a formal, using `=` allows one to provide a default:

``` chapel
proc h(arg: int = 4) { }
h(); // calls h with arg=4
```

That seems reasonable and intuitive. However, the field declarations use different syntax such as `type t = map(int, string);`. It's a statement & more similar to a variable declaration than a formal. I think that the current behavior treats fields with defaults like these formals, which in my opinion only really makes sense to somebody who is thinking about how the fields impact the compiler-generated initializers.

Finally, we have a related issue #18214 which points out a case where it isn't so obvious how generic-with-defaults fields should behave when one of the fields is generic without a default.

### Alternative Design Proposal

Here the alternative design proposal is to completely remove the generic-with-defaults behavior. Instead, a `type` or `param` field with an initialization expression would become simply a shorthand name for a type or param value. That would make it more similar to C++ and make the case in #12613 easy to express.

So, let's revisit some examples with this proposal:

``` chapel
record MapHelper {
  type mapType = map(int, string);
  // mapType is just shorthand for another type.
  // Declaring it does not make MapHelper generic. 
  
  var theMap: mapType;
}
```

``` chapel
record R {
  type elementType = int;
  // this is just renaming a type, like type aliases do.
  // R is not generic
  
  var element: elementType;
}

// such code that needs to continue to create a generic type would
// need to migrate to:

record R {
  type elementType;
  // now R is generic and it is clear that it is, at a glance
  
  var element: elementType;
}
```

If users desire a way to have defaults for a type constructor, I'd rather provide a way that they can create a custom type constructor. Perhaps that could be created with some sort of `proc type this() type` method. See also https://github.com/chapel-lang/chapel/issues/18817#issuecomment-989887010 which discusses this idea.

However, the main case that I am aware of that needed or wanted generics-with-defaults is `range`, but over in #17122 we are thinking that it is better to make `range` generic.

**Comment by benharsh** [comment]
Do you have a particular deprecation strategy in mind?

Generally speaking this proposal appeals to me, but I need to think about it some more.

**Comment by mppf** [comment]
> Do you have a particular deprecation strategy in mind?

* 1.29 deprecates fields like `type t = <expr>` and `param p = <expr>` (i.e. generic fields with defaults) & asks people to use custom initializers for most cases where this changes record/class behavior
* 1.30 introduces the new behavior for `type t = <expr>` and `param p = <expr>` (where they are not considered generic but rather just convenient names for expressions).

**Comment by mppf** [comment]
I have been thinking about this a bit more and am currently thinking that the proposal in this issue isn't a good idea.

The main problem is that, if we change the interpretation of a field like `record R { type myTypeField = int; }`, then we will lose the ability to easily influence the default values for the generated type constructor. I think it is a good thing that our fields can have default values that impact the generated initializer and the generated type constructor. So it would seem a bit too much to me to completely remove that feature.

However, there is one element here that I will still argue for. That is, for a type that is generic-with-defaults, I don't think you should be able to get the default version just with the type name. Since `range` is that way today, I will use it as an example. I think that `range` should refer to the generic type and `range()` should refer to the type with the defaults applied. I think this syntax makes it clearer that 1) the type is generic and 2) that more arguments could be provided to select something other than the default.

Another note, with the current situation, if a user thinks they are writing something with the C++ behavior, but end up making something that is generic-with-defaults, the program will compile and run. That is both good and bad. It's good because we'd like things to be easy. It's bad because it misses an opportunity to educate the user about how Chapel isn't the same as C++ in this way.

Now, it has been suggested that the current behavior is motivated by a desire to allow users to create something like `int` where `int` is the same as `int(64)` and `int(16)` etc is also available. But, personally, I don't think about this as a generic type at all (because `int` is not generic). I think of it as a `type` returning `type` method available on `int`. Today, `type t = int; writeln(t(32):string);` does not compile, but arguably it should compile. I think if it does compile, that would also mean that `type t = int(64); writeln(t(32):string);` would compile, because the compiler doesn't know that `type t = int` is referring to `int` in its generic capacity. I suppose we could use `type t = int(?)`, but then `t` would lose its default nature?

Anyway that's a bit rambly but the point is that I don't think of `int` as a record at all and so I'm not really convinced by the analogy. If `int(32)` isn't just provided by a type method on `int`, `int` could arguably be a `typeclass` with a default.

**Comment by bradcray** [comment]
I'm finally finding more time to catch up on email from the Thanksgiving/AoC timeframe, and read this thread for the first time today as part of that.

> there is one element here that I will still argue for. That is, for a type that is generic-with-defaults, I don't think you should be able to get the default version just with the type name. Since range is that way today, I will use it as an example. I think that range should refer to the generic type and range() should refer to the type with the defaults applied. I think this syntax makes it clearer that 1) the type is generic and 2) that more arguments could be provided to select something other than the default.

Possibly obvious, but #21455 was written as my response to this part of the proposal (after hearing about it in a deep-dive).  The idea of having to put `()` after fully-defaulted/concrete types wasn't all that appealing to me, where the dual approach felt more attractive, particularly since we already use `(?)` or `(..., ?)` to refer to partially instantiated types:
* It would continue to permit fully-defaulted generic types to be written as `range`, `int`, `R` as though they were concrete (because if they're fully-defaulted and if the user doesn't want to override those defaults, they may as well be)
* Require non-concrete types (generics without defaults or partial instantiations) to be written as `R(?)` or `R(some, args, ?)` to leverage the existing syntax and make the generic cases stand out visually
In proposing that, I'm postulating that end-users who are using a fully-defaulted generic type doesn't particularly need to know that it was generic—e.g., if I only ever wanted bounded, unit-stride ranges of ints, the fact that `range` supports other signatures isn't important to me (?).

I'm sad to hear that you don't think of "writing `int` as a record" isn't compelling to you anymore, because I think you're the one who first planted the idea in my mind, and it's only become more and more appealing to me over time to get to a point where one _could_ write int in the language even if we never did ourselves.  Specifically, I've been mentally imagining it to be written as something like:

```chapel
record int {
  param bitWidth = 64;
  var bytes: c_array(uint(8), bitWidth/8));  // or maybe `var bytes: __primitive("get C int type", bitWidth);

  proc init() {
    if bitWidth != 8 && bitWidth != 16 && bitWidth != 32 && bitWidth != 64 then
      compilerError("`int` does not support " + bitWidth:string + "-bit values");
    }
  }
}
```

with respect to this:

> Today, type t = int; writeln(t(32):string); does not compile, but arguably it should compile. I think if it does compile, that would also mean that type t = int(64); writeln(t(32):string); would compile, because the compiler doesn't know that type t = int is referring to int in its generic capacity.

My intuition is where you ended up—that if you wanted the alias to be the generic type, you'd write:

> I suppose we could use type t = int(?), but then t would lose its default nature?

Would it need to lose its default nature?  Could `t = int(?)` imply the completely generic version of `int`, including the defaults, such that `proc t.init(bitWidth=64) type` was the signature of `t`'s type constructor/initializer?

Related:  Today, given `proc foo(type t) { ... }`, I don't think we can pass `int` in and write `t(32)` within the routine, nor pass `int(?)` in and write `t` or `t(32)`.  Though maybe we should be able to do one or both of these (where, of the two, the latter makes the most sense to me).

**Comment by mppf** [comment]
> I'm sad to hear that you don't think of "writing `int` as a record" isn't compelling to you anymore

That's not the position I was trying to argue here. Rather, that `int` is a concrete type with a `proc type int.this(param bits) type` function that constructs related types. This pattern can be repeated with a concrete record.

As we discussed, that means that it does not support `int(?)`. We could have a different type name for the generic variant. Or use some as-yet-to-be-designed type class feature.

Anyway, these directions got very little support in discussion, so I will close this issue.

**Comment by mppf** [comment]
Closing this issue since the main proposal here was discussed and rejected (as Approach C in https://github.com/chapel-lang/chapel/issues/19120#issuecomment-1412839803 ).

The variation to require `()` for generic-with-defaults types, e.g. `range()` had some support but also some significant detractors. At the present time, that proposal does not have an issue of its own.
