### ISSUE TITLE
Errors Module: `halt`, `warning`, and `assert`

### ISSUE THREAD

**Issue by jeremiah-corrado** [chapel-lang/chapel#21071]
### Background:

The Errors module supports two overloads of the `halt`, `warning` and `assert` procedures. One which emits a generic message and line number information, and another that emits a custom message with line number information.

There are also the analogous `compilerError`, `compilerWarning` and `compilerAssert` procedures.

### Suggestions/Questions:

- As alluded to in [this issue](https://github.com/chapel-lang/chapel/issues/18024): should `halt`/`warning`/`assert` be unified with `compilerError`/`compilerWarning`/`compilerAssert`?
    - i.e., can the same methods somehow support both compile-time and runtime invocations?
- I think we should change the naming in definitions slightly, from : `halt(args ...?numArgs)` to `halt(args ?...k)` to match the simpler style (used in the IO module for example).
- Should these always report source locations? See: https://github.com/chapel-lang/chapel/issues/15794

**Comment by lydia-duncan** [comment]
> * I think we should change the naming in definitions slightly, from : `halt(args ...?numArgs)` to `halt(args ?...k)` to match the simpler style (used in the IO module for example).

I don't think the queried portion impacts what the user passes in to call the function, but I think it is clearer to use `numArgs` or `n` if we want to use a single character.

For the other questions - I personally don't have a problem with `halt`/`warning`/`assert` being separate functions and don't object to them having a way to toggle whether the source location is reported

**Comment by mppf** [comment]
> * I think we should change the naming in definitions slightly, from : `halt(args ...?numArgs)` to `halt(args ?...k)` to match the simpler style (used in the IO module for example).

Did you mean `halt(args ...?k)` ? It could just be `halt(args...)`. The `k` can be queried with `args.size`. I don't think `k` or `numArgs` is helpful to people reading chpldoc since it is just another name for `args.size` for use within the function's body.

**Comment by jeremiah-corrado** [comment]
> It could just be `halt(args...)`

That works too. I'm mainly just concerned with the inconsistency of style within the module itself, i.e. `assert(test: bool, args ...?numArgs)` vs. `compilerError(param msg: string ...?n)`. 

If we used the same name for the length query —or no name at all— for all the symbols in Errors, I think the documentation would look much nicer.

**Comment by bradcray** [comment]
I also like the "no names at all" approach given that it isn't relevant for the user.

**Comment by jeremiah-corrado** [comment]
To summarize, it sounds like the current proposal for these symbols is to change the varargs headers of `halt`, `warning`, and `assert` (as well as `compilerError`, `compilerWarning`, and `compilerAssert`) to omit the query for the number of arguments. I.e., they would be changed from `halt(args ...?numArgs)` to `halt(args...)`.

Other than that, there are no proposed changes to `halt`, `warning` and `assert` for stabilization purposes.

(Note that there is a separate issue: https://github.com/chapel-lang/chapel/issues/18025, discussing whether the `compiler[Error/Warning/Assert]` procedures should be renamed, so I would not yet consider those symbols stable after making this change).

**Please vote on this proposal:**

👍 - Go ahead with the proposed varargs change
🎉 - Do something else with the varargs overloads (ex: `halt(args...?k)`)
👀 - Propose some other stabilization change (ex: a name change, additional arguments, etc.)

**Comment by bradcray** [comment]
@lydia-duncan , can you say what your :tada: vote represents here?  (i.e., what the something else is?)  Is it just the keeping the query but renaming it that you mention above?  And of your two votes is one stronger than the other?

**Comment by lydia-duncan** [comment]
The "something else" is renaming the portion getting the size to be consistent across the module itself.  It doesn't actually impact the user's interface to the function but it would be nice to have it consistent if it did exist.  I would say the vote for removing it entirely is slightly stronger, but I'm mostly ambivalent between the two.
