### ISSUE TITLE
Document `ch.write[ln]` throwing behavior for EOF

### ISSUE THREAD

**Issue by jeremiah-corrado** [chapel-lang/chapel#21102]
Before https://github.com/chapel-lang/chapel/pull/20941, it looked like the `fileWriter`'s writing methods returned false on EOF (wasn't actually true, but that's what it looked like). Now that the return value has been removed, it is not clear how to detect an EOF from one of these methods.

I'll add a `throws UnexpectedEofError` line to the documentation on the relevant methods.

- [x] put in PR to update docs before doc-freeze

**Comment by bradcray** [comment]
Likely a naive question, but:  Writing to a file can result in an EOF?  How does that happen?

**Comment by jeremiah-corrado** [comment]
I believe this can happen when the upper bound on the channel's range is exceeded. This is probably rare in practice, since that range defaults to `0..`

**Comment by jeremiah-corrado** [comment]
resolved by PR #21120
