### ISSUE TITLE
Support multi-enum declarations?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#21144]
In Chapel, when declaring things like variables and constants, multiple declarations can share a single keyword, such that rather than typing:

```chapel
const x: int;
const y: real;
```

you can write:

```chapel
const x: int,
    y: real;
```

While this is not a huge deal, it makes the language feel less clunky and pedantic.

This issue asks whether we should extend the same sort of support to enums, such that rather than writing:

```chapel
enum color {red, green, blue};
enum size {small, medium, large};
```

you could write:

```chapel
enum color {red, green, blue},
     size {small, medium, large};
```

To me, this seems like a no-brainer.  It's similar to other short declaration forms and should be trivial to implement.

(I will also say, though, that I would strongly oppose doing the same for `record`, `class`, `proc`, and `iter` declarations.  In part because they tend to involve multi-line declarations by nature, so the savings aren't as great, the interpretation would be less clear, and the chance of mistakes seems higher).

**Comment by mppf** [comment]
My own opinion on this matter is that it's not common enough to want to write multiple `enum`s in a row to justify this language feature. It only improves the situation by removing a single keyword, which doesn't seem like enough improvement to be worthwhile given that it won't come up frequently.

**Comment by bradcray** [comment]
If it were at all difficult to implement, I might agree with you, but given that it seems like it should be a piece of cake (at least in the old parser, I think I could do it in 15 minutes...  I guess I can't speak to dyno), it seems silly not to.  For reference, the motivation on this was: Having just written a blog article about how nice it is that you don't have to do the numbingly repetitive:

```chapel
const pi = 3.14;
const mst = "hello";
const n = 10;
```

it seemed silly to write one the following day with:

```chapel
enum outcome {lose=0, draw=3, win=6};
enum shape {rock=1, paper, scissors};
enum entry {A=rock:int, B, C,
            X=rock:int, Y, Z};
```

and not be able to make the same claim.  Subjectively, I think:

```chapel
enum outcome {lose=0, draw=3, win=6},
     shape {rock=1, paper, scissors},
     entry {A=rock:int, B, C,
            X=rock:int, Y, Z};
```

reads strictly better, and ought to be available as an option.

The `const`/`var`/`param`/`type` cases are similarly "just one keyword" but you'd have a hard time convincing me to ever get rid of supporting them.  They make code look so much less 1980.

**Comment by bradcray** [comment]
(Writing the day 3 blog today, I'm realizing `use` is another such case where I'm glad I don't have to write:

```chapel
use IO;
use Set;
```

Granted, since enums are more verbose than enums, the savings is more notable here, but for me it remains an orthogonality argument as much as anything.

**Comment by damianmoz** [comment]
There is a typo in the last paragraph of that last post.

I am all for orthogonality.

What is 1980s coding style?

**Comment by bradcray** [comment]
> There is a typo in the last paragraph of that last post.

Fixed, thanks!

> What is 1980s coding style?

To me, very ponderous, keyword-heavy programming with lots of repetition and short phrases.  E.g.,

```chapel
var zero = 0;
var total = 0;
var numFound = 0;
var one = 1;
const message = "hello";
const pi = 3.14159265;
```

While Chapel is definitely a keyword-driven programming style (relative to C or Perl, say), I like that we permit chaining of these declaration styles to amortize the use of the keywords when desired.  E.g.,

```chapel
var zero, total, numFound = 0,
    one = 1;
const message = "hello",
      pi = 3.14159265;
```

(while still permitting the previous approach).

**Comment by damianmoz** [comment]
So, does
```chapel
var zero, total, numFound = 55,
```
initialize all 3 of those variables to 55.

My experience is that the 1980s style
```chapel
const x = .expression; // comment
const y = expression; // comment
const z  = expression; // comment
```
is the best way, at least when using C or C++, to get the most compact (and fastest) code, especially for things like elementary functions and even numerical algorithms. Very clear.

That said, one could use the 1970s Wirth (Pascal) approach in my example
```chapel
const
    x = expression, // comment
    y = expression, // comment
    z = expression; // comment
```
to achieve the same sort of thing and have something that is less keyword heavy.

But at least with allowing multiple **enum**s and **use**s, Chapel allows both styles across pretty well most of the declarative keywords for which mulktiple things makes sense.

**Comment by damianmoz** [comment]
Interesting initialization syntax. I had never realised that. I need to read the manual more deeply as this was never obvious to me.

I think the flexibility in styles that this enhancement brings is great. And, as I said, I like orthogonality.

**Comment by damianmoz** [comment]
Sorry. I am trying to see what occurs here to test my email system. I will delete this shortly.

**Comment by mppf** [comment]
> If it were at all difficult to implement, I might agree with you, but given that it seems like it should be a piece of cake (at least in the old parser, I think I could do it in 15 minutes... I guess I can't speak to dyno), it seems silly not to.

My concern is not difficulty of implementation. It's that it makes the language more complicated in service of a problem that comes up very rarely.

> (I will also say, though, that I would strongly oppose doing the same for `record`, `class`, `proc`, and `iter` declarations. In part because they tend to involve multi-line declarations by nature, so the savings aren't as great, the interpretation would be less clear, and the chance of mistakes seems higher).

I don't think we're adding orthogonality / generalizeable / "obvious" rules if we are doing it for `enum` and not `record` and not `proc`.

A further concern I have is that `enum` is not even syntactically the same type of statement as `var`. 

As you said, if you had:

``` chapel
const x: int;
const y: real;
```

you can replace it with

``` chapel
const x: int,
      y: real;
```

Here I can imagine "Yeah, you can replace the semicolon with a comma and omit the variable kind". The variable declarations require a semicolon (at least, when they are not part of one of these multi-decl lists).

But, for enums, the semicolons in your previous example are superfluous in Chapel (but not in C). I think the shortest way to write your example today is actually this:

``` chapel
enum color {red, green, blue}
enum size {small, medium, large}
```

And now there is no more "replace semicolons with commas" idea.

The point is, an `enum` is a completely different kind of statement from a variable declaration. So I don't think it would be in any way obvious that you could apply the same shortcut declaration style to it.

**Comment by vasslitvinov** [comment]
@bradcray for future Chapel archaeologiests, how was this issue resolved?

**Comment by bradcray** [comment]
Good point Vass.  I was reasonably convinced by Michael's argument that enums aren't statement declaration forms like `const`, `var`, or `param` and were more like block declaration forms like `record`, `class`, or `proc` and that the analogy I was trying to draw didn't really hold up as well as I thought.  Though I still might argue that they should be an exception, I didn't feel strongly enough about the OP's proposal to bother fighting further for the issue or keeping the issue open.
