### ISSUE TITLE
bug with right shift on `bigint`

### ISSUE THREAD

**Issue by pierce314159** [chapel-lang/chapel#21206]
### Summary of Problem

When right shifting a `bigint`, I seem to always get `0` as the result. I think this is because `c` is double defined, so the changes never make it to the one in the outer scope
https://github.com/chapel-lang/chapel/blob/da619d9d8b252056704dd73e0608d2f7f794947f/modules/standard/BigInteger.chpl#L1310-L1315

### Steps to Reproduce

**Source Code:**

```chapel
use BigInteger;
writeln(4:bigint>>1);
```

**Compile command:**

```
chpl PlayingAround.chpl -o playing
```

**Execution command:**

```
./playing
```

**Associated Future Test(s):**

### Configuration Information

- Output of `chpl --version`:
```
chpl version 1.28.0
  built with LLVM version 14.0.6
```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: arm64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: fifo
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: cstdlib
CHPL_ATOMICS: cstdlib
CHPL_GMP: system *
CHPL_HWLOC: none
CHPL_RE2: bundled *
CHPL_LLVM: system *
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
Homebrew clang version 14.0.6
Target: arm64-apple-darwin22.1.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm@14/bin
```

**Comment by pierce314159** [comment]
This seemed like a good first chapel issue for me, so I tried my hand at fixing it in PR #21207 

@mppf @bradcray @ronawho if any of you mind giving it a review, I'd appreciate it!

**Comment by ronawho** [comment]
@pierce314159 I know you have the fix up for this, but I'm thinking about workarounds until you can rely on a chapel version that includes the fix. It looks like only the `int` version had this bug. Is casting to a `uint` a viable workaround for you? For example:

```chpl
use BigInteger;
writeln(4:bigint>>1:uint);
```
