### ISSUE TITLE
Should the `size` field/query of a parallel safe datatype be atomic

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#21249]
While working with `parSafe=true` lists, I introduced a subtle race in my program in which a query to `myList.size` was giving me a stale answer since there had not been any operations that result in memory fences since the last time I'd queried that field.  This makes me wonder whether the `size` fields or queries of a parallel-safe collection should use atomics / memory fences to always return an accurate result and reduce the chances of bugs.

**Comment by bradcray** [comment]
@lydia-duncan: food for thought

**Comment by mppf** [comment]
I think it's reasonable to assume that `.size` is parallel-safe; however keep in mind that since you would generally store it into a variable, the value in the variable might not be accurate any longer by the time you use it. E.g.

``` chapel
if myList.size() == 0 {
  myList.append(1);
  assert(myList.size() == 1); // might fail: another task could have appended after the condition was checked
}
```

**Comment by ronawho** [comment]
Getting the size is guarded by a lock today and should have appropriate memory fences (enter/leave are the lock wrappers when parSafe)

https://github.com/chapel-lang/chapel/blob/c1904398f76b4838247baa69f9a238d62a68fa24/modules/standard/List.chpl#L1816-L1829

**Comment by bradcray** [comment]
Huh...  well now I have no idea why I was seeing an apparent race in my code then.  I'm going to leave this open for the time being (including in a tab on my browser) in hopes of spending a bit more time on it before the holidays.

For anyone else trying to reproduce this later, what I found was that in my day11-par.chpl 2022 Advent of Code case, if I flipped the conditions in this while loop to the opposite order:

```chapel
while (canPause.readXX() != id || Items[current].size > 0) {
```

I'd get a race condition.  My theory was that the readXX()'s memory fence was forcing my code to go back and read .size again, but with Elliot's observation, that can't be the case.

Oh, but maybe Michael's observation is the real answer?  That size might have changed to a non-zero value between the time I read it and checked the .readXX?  That seems plausible and is a much simpler and more satisfying explanation...    Let me stew on it a bit more and see if it sticks.

**Comment by ronawho** [comment]
> That size might have changed to a non-zero value between the time I read it and checked the .readXX? That seems plausible and is a much simpler and more satisfying explanation... Let me stew on it a bit more and see if it sticks.

Especially since `readXX` does a task yield

**Comment by bradcray** [comment]
I may have been unclear (or else am misinterpreting your comment).  The `while` I showed above is the one that works.  It was flipping it to check the list size first that didn't.

**Comment by bradcray** [comment]
Walking through the bug in my code in the article, I convinced myself that Michael's explanation was the right one, and that this is not an issue as I feared (whew!)
