### ISSUE TITLE
Strange behavior with `int - bigint`

### ISSUE THREAD

**Issue by pierce314159** [chapel-lang/chapel#21290]
### Summary of Problem

I ran into some weirdness with `int - bigint`. It works fine if I cast the `int` to a `bigint` first

### Steps to Reproduce

**Source Code:**

```chapel
use BigInteger;

writeln(-10 - 0:bigint);
writeln(-10:bigint - 0:bigint);
```

**Compile command:**
```
chpl PlayingAround.chpl -o playing
```

**Execution command:**
```
./playing                         
10
-10
```
If an input file is required, include it as well. -->

**Associated Future Test(s):**

### Configuration Information

- Output of `chpl --version`:
```
chpl version 1.28.0
  built with LLVM version 14.0.6
```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: arm64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: fifo
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: cstdlib
CHPL_ATOMICS: cstdlib
CHPL_GMP: system *
CHPL_HWLOC: none
CHPL_RE2: bundled *
CHPL_LLVM: system *
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
Homebrew clang version 15.0.5
Target: arm64-apple-darwin22.1.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm/bin
```

**Comment by pierce314159** [comment]
It seems to me that maybe this line was meant to be `if b >= 0`
https://github.com/chapel-lang/chapel/blob/ae52de5bbc5f1149cc5626277babe1f235f243de/modules/standard/BigInteger.chpl#L907

**Comment by pierce314159** [comment]
It looks like when `a` is negative, the code does `b + -a` instead. I think we only need the code from the ` if a >= 0` case

https://github.com/chapel-lang/chapel/blob/ae52de5bbc5f1149cc5626277babe1f235f243de/modules/standard/BigInteger.chpl#L922-L934

**Comment by bmcdonald3** [comment]
Thanks for pointing this out Pierce, I'll plan to to take a look at this soon.
