### ISSUE TITLE
Odd developer-mode internal error file path

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#21291]
### Summary of Problem

In developer mode, the filename reported for location of the internal error is a big munged.

E.g., for the error in #21265,

```
$CHPL_HOME/modules/internal/ChapelArray.chpl:3399: internal error: assertion error [resolution//home/fortytwo/src/chapel/compiler/resolution/cleanups.cpp:792]
```

I think it should just be `resolution/cleanups.cpp`, or maybe `compiler/resolution/cleanups.cpp` if it needs disambiguation from `frontend/`.

This looks like an absolute path passed where a relative path was expected.  Maybe related to the cmake changes?

### Steps to Reproduce

**Source Code:**

```chapel
proc main() {
  const bs = f();
  for b in bs {
      writeln(b);
  }
}

iter f() {
}
```

(Until that's fixed.)

**Associated Future Test(s):**

Nope.

### Configuration Information

```
chpl version 1.30.0 pre-release (b'179b81edd3')
  built with LLVM version 14.0.0

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: none
CHPL_LLVM: system
CHPL_AUX_FILESYS: none

gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

Ubuntu clang version 14.0.0-1ubuntu1
```

**Comment by mppf** [comment]
Thanks for noticing the problem @cassella. I've created PR #21310 to fix it.
