### ISSUE TITLE
IO.fileWriter Parameters Error

### ISSUE THREAD

**Issue by kwaters4** [chapel-lang/chapel#21300]
### Summary of Problem
The problem arose when updating code from Chapel 1.28.0 to Chapel 1.29.0. Changing ```IO.channel``` takes three arguments. With the update to ```IO.fileWriter``` the [documentation](https://chapel-lang.org/docs/modules/standard/IO.html#IO.fileWriter) reflects the same 3 inputs are allowed. In the IO module (line 2175 for Reader and line 2209 for Writer) only 2 are allowed, if I understand the syntax correctly. I believe the intention was to make the writing parameter default and pass kind and locking? I think this is what is going on.

The workaround currently is to continue to use the deprecated function ```IO.channel``` over the new ```IO.fileWriter```.
### Steps to Reproduce

**Source Code:**

Working version for Chapel 1.28.0:
```chapel
import IO;

record foo{
      var bar : IO.channel(writing=true, kind = IO.iokind.little, locking = false);
}
```
Updated version with issues for Chapel 1.29.0:
```chapel
import IO;

record foo{
      var bar: IO.fileWriter(writing=true, kind = IO.iokind.little, locking = false);
}
```

**Compile command:**
``` chpl foo.bar``` 

**Output**
```
foo.chpl:4: error: invalid type specifier 'fileWriter(writing=1, kind=iokind, locking=0)'
foo.chpl:4: note: type specifier did not match: (null)
foo.chpl:4: note: type was specified with 3 arguments
$CHPL_HOME/modules/standard/IO.chpl:2111: note: but type 'fileWriter' only has 2 generic fields
```

### Configuration Information

- Output of `chpl --version`:
```
chpl version 1.29.0
  built with LLVM version 14.0.0
````
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: bundled
CHPL_AUX_FILESYS: none
```

**Comment by cassella** [comment]
> In the IO module (line 2175 for Reader and line 2209 for Writer) only 2 are allowed, if I understand the syntax correctly. I believe the intention was to make the writing parameter default and pass kind and locking? I

Hi @kwaters4 .  In this case, I believe the

```chapel
type fileWriter;
fileWriter = _channel(writing=true, ?);
```
is not setting a default value, but is creating `fileWriter` as an alias of this partial instantiation of `_channel`.  The `writing=true` is implied by using the type alias `fileWriter`, and (evidentally) can't be specified again.

When I remove the `writing=true` from your code, it does compile.

**Comment by kwaters4** [comment]
@cassella Thanks for the response, yes that does work. I am not sure if that is the intended way to use it or the documentation needs to be updated. It was a bit confusing so I put my best step forward in trying to describe the behavior I thought it was supposed to have. 

I think the channel type was just abstracted away from the user API and fileWriter/Reader was put in place with the split being made by the ```writing``` variable under the hood. I think I understand that, but the documentation indicates otherwise. I am always open to having missed all the warning signs!

**Comment by mppf** [comment]
Yes this is a case where the documentation needs to be updated but there is so much I/O documentation relating to `channel` that we didn't get to it yet.

**Comment by mppf** [comment]
In other words in your example, it should be

```
      var bar: IO.fileWriter(kind = IO.iokind.little, locking = false);
```

**Comment by lydia-duncan** [comment]
I believe this was resolved a few releases ago.  There don't seem to be any remaining references to the old writing field.  Closing
