### ISSUE TITLE
owned and shared API questions

### ISSUE THREAD

**Issue by mstrout** [chapel-lang/chapel#21372]
Proposal for 2/7/23 module re-review discussion

- should we deprecate the .borrow() method? **probably not**
- should we make release a type method? **yes**
- how can we have consistency between casting and adopt (a type method that is planned to replace `owned.create`and `shared.create`)?
  - I recommend using type methods `shared.adopt()` and `owned.adopt()` instead of casting from `unmanaged` or `owned` to `owned` or `shared`.
  - For getting from `unmanaged`, `owned`, or `shared` to `borrowed`, I propose keeping all three mechanisms: casting, `.borrow()` instance method, and implicit coercion.

Proposed implementation tasks
- create type methods `adopt` and `release` for `shared` and `owned`
  - for @jeremiah-corrado, have `shared.release()` match the behavior of `owned.release`

- deprecate `retain()` and `clear()`
  - instead of `retain` can use `adopt`
  - instead of `clear` can use `release`
  - see https://github.com/Cray/chapel-private/issues/1609 for more background

- deprecate `owned.create` and `shared.create`
  - alternative is `adopt`

- deprecate casting from `owned` to `shared`
  - instead require a `shared.adopt` call

- put in a compiler error when there is casting from `unmanaged` to `borrowed` or `shared`.  Programmer should instead use appropriate `adopt`.

-  Remove all of the unnecessary `.borrow()` calls when the implicit coercion is working.
  - fix `var s: single borrowed C? = new owned C()` split init case where warning of `new owned` to `borrowed` isn't happening.  `./parallel/single/waynew/simple0b.chpl`

-------------------------------------------
From original OP just after 1/10/23

This issue subsumes the following questions brought up in the 1/10/23 module re-review.
- should we deprecate the .borrow() method?
- should we make release a type method
- how can we have consistency between casting and adopt (a type method that is planned to replace `owned.create`and `shared.create`)

We can break off specific github issues once we have settled on an overall approach that impacts all of these.  The key questions are (1) to cast or not to cast and (2) if we are not casting, there are a host of questions about the procedures involved.

Call to action: please share your thoughts on these questions and proposals.  Our goal is to stabilize on something by early Fall.

(1) to cast or not to cast
  - where are we currently using casting: int to string, other stuff to string?, owned to shared
  - in what cases are we currently not using casting
    - `create` could be replaced with a cast even with `unmanaged` to `owned` or `shared`.  However, @mppf would compiler have to handle `unmanaged` to `owned` or `shared` casts?
    - `foo = ownvar.release` on an `owned`, could be replaced with
      - `foo = ownvar : foomanagetype` // this should result in ownvar losing ownership, similar to an owned being cast to a shared
      - `bar = sharevar.release` on a shared, EGADS the return type for release on a shared is a tuple with the strong and total counts, maybe part of weakptr prototype @jeremiah-corrado?

  - cases where we don't have either option currently available
    - going from `owned` to `unmanaged`, https://github.com/chapel-lang/chapel/issues/18164
    - The language spec indicates we should be able to cast to nilable, but when casting from an `owned` to a `shared` the issue https://github.com/chapel-lang/chapel/issues/20647 points out we can't.  The github issue also points out upcasting and downcasting aren't possible.

  - impacts of casting
    - doesn't necessarily match the idea of casting just changing a type like in up and down casting since bits are actually being changed and/or things are being wrapped
    - would need to enable casting from unmanaged to shared or owned
		
  - impacts of not casting
    - we have to consider which method names are being taken out of the user-defined class namespace
    - would need to take away that newly added cast from owned to shared and replace with adopt calls
    - would we need to take away all the implicit casting from shared, owned, and unmanaged to borrowed?  it seems like this would be especially painful in instance method calls because the receiver this is a const in borrowed

(2) when not casting,
  - when should it be a type method instead of an instance method?  I propose we have one type method, `adopt()`.
    - In https://github.com/chapel-lang/chapel/issues/20648, adopt( ) is converged on.  adopt( ) would be a type method like the create( ) it would replace.
    - In 1/10/23 module re-review, @mppf suggested we look into having release( ) be a type method instead of an instance method.  See minimal functionality bullet below where I propose we use adopt to implement release as well as all other function names in the owned and shared APIs.
    - one disadvantage of this is that @bradcray  and @DanilaFe both felt a .borrow method was the clearest way to do a borrow, in other words, instead of a type method and I am predicting using the term adopt instead of borrow would cause confusion because a borrow is more a fostering (to abuse the analogy somewhat)

  - minimal functionality could be `adopt` , `adopt` would directly replace `create` and `borrow` (an alternative would be to keep `borrow` or just have it done with casts either implicitly or explicitly)
    -  `other = obj.release()` can be replaced with the following
       * `other = adopt( obj );`
       * `obj = adopt(nil);` if obj was shared and if the assignment of adopt(nil) to a shared or owned was allowed, which it currently isn't 

    - `obj.clear()` could be replaced by 
      - `obj = adopt(nil);` // if obj was shared and if the assignment of adopt(nil) to a shared or owned was allowed, which it currently isn't
 
    - Note: as of 1/16/23, `foo = nil` and `foo = owned.adopt(nil)`, neither of these work, right now have to use clear() method.  (@mppf, this doesn't seem like it is on purpose, https://github.com/Cray/chapel-private/issues/1609)

  - since methods will impact all user-defined classes, they are related to special method names (https://github.com/chapel-lang/chapel/issues/19050, https://github.com/chapel-lang/chapel/issues/19285)
    - which category?  from slide 72 of https://chapel-lang.org/releaseNotes/1.26/06-ongoing.pdf, these methods on owned and shared seem to be similar to the special methods for I/O, context management, and hashing in that they are specific to a key aspect of the implementation.  The difference being that these owned and shared methods only impact classes, those that are user-defined and those in standard libraries.
    - proposal for naming them: Above I propose just having the type method adopt for owned and shared and maybe the borrow method (instance or type method)

### Public issues that have been subsumed by this one and thus closed and they point to this one.
  - https://github.com/chapel-lang/chapel/issues/20648, This issue converged to replacing the owned and shared type method create() with adopt() instead of using casting.
  - Owned/Shared module - are we okay with clear being taken out of the user's namespace control? chapel-lang/chapel#20336

### Private issues that have been subsumed by this one and thus closed and they point to this one.
  - Should retain() and/or clear() be deprecated in the shared module Cray/chapel-private#1609

**Comment by jeremiah-corrado** [comment]
> bar = sharevar.release on a shared, EGADS the return type for release on a shared is a tuple with the strong and total counts, maybe part of weakptr prototype @jeremiah-corrado?

Yeah the total-count return value was added as a part of the `weakPointer` prototype. Originally, this method just returned the "strong" reference count.

This is just a method on the internal `ReferenceCount` object though, and I don't believe it's publicly documented or accessible. So perhaps we want to add a `release` method to `shared` that calls the internal reference counter's `release` and then returns the internal pointer — to match the behavior of `owned.release`?

**Comment by mppf** [comment]
> `foo = ownvar.release` on an `owned`, could be replaced with
> 
>     * `foo = ownvar : foomanagetype` // this should result in ownvar losing ownership, similar to an owned being cast to a shared

Did you mean `foo = ownedvar : unmanaged` ? I don't think we should do that, because it looks like a way to get an unmanaged pointer that aliases the owned pointer, which you should be able to do. But it does not do that - instead it clears out the owned pointer.

**Comment by mppf** [comment]
> * Note: as of 1/16/23, `foo = nill` and `foo = owned.adopt(nil)`, neither of these work, right now have to use clear() method.  (@mppf, this doesn't seem like it is on purpose,

You'd have to show a code example. I suspect it is not working because your variable is non-nilable and this would store `nil` into it. I do not remember if `clear` worked for non-nilable (but I'm guessing it does?).

Anyway, even if that is the case, maybe we should just use other features to do it:
 * `{ var x = ownedToConsume; }` -- it would transfer ownership to the local x which is then destroyed
 * https://chapel-lang.org/docs/main/modules/standard/MemMove.html#MemMove.explicitDeinit -- arguably `explicitDeinit` should do the job as well

**Comment by mppf** [comment]
> * since methods will impact all user-defined classes, they are related to special method names

We can debate whether `.borrow` is a special method or needs to have special method namespacing (see my post above about that).

However, specifically for the type methods proposal for `adopt` and `release`, if we have `shared.adopt(myUnmanaged)` and `shared.release(myShared)`, I don't see any meaningful way that we are taking method names away from the user.

**Comment by mstrout** [comment]
Put at top of OP: Proposal for 2/7/23 module re-review discussion

- should we deprecate the .borrow() method? **probably not**
- should we make release a type method? **yes**
- how can we have consistency between casting and adopt (a type method that is planned to replace `owned.create`and `shared.create`)?
  - I recommend using type methods `shared.adopt()` and `owned.adopt()` instead of casting from `unmanaged` or `owned` to `owned` or `shared`.
  - For getting from `unmanaged`, `owned`, or `shared` to `borrowed`, I propose keeping all three mechanisms: casting, `.borrow()` instance method, and implicit coercion.

Proposed implementation tasks
- create type methods `adopt` and `release` for `shared` and `owned`
  - for @jeremiah-corrado, have `shared.release()` match the behavior of `owned.release`

- deprecate `retain()` and `clear()`
  - instead of `retain` can use `adopt`
  - instead of `clear` can use `release`
  - see https://github.com/Cray/chapel-private/issues/1609 for more background

- deprecate `owned.create` and `shared.create`
  - alternative is `adopt`

- deprecate casting from `owned` to `shared`
  - instead require a `shared.adopt` call

- put in a compiler error when there is casting from `unmanaged` to `borrowed` or `shared`.  Programmer should instead use appropriate `adopt`.

-  Remove all of the unnecessary `.borrow()` calls when the implicit coercion is working.
  - fix `var s: single borrowed C? = new owned C()` split init case where warning of `new owned` to `borrowed` isn't happening.  `./parallel/single/waynew/simple0b.chpl`

**Comment by vasslitvinov** [comment]
Do we allow assignment `myShared = myOwned;` ?

If so, we should not be providing `shared.adopt(arg: owned)`. This is by analogy to using `myOwned2 = myOwned1;` instead of `owned.adopt(myOwned1)`.

**Comment by jabraham17** [comment]
Looks like PR #20492 previously deprecated `myShared = myOwned`

**Comment by lydia-duncan** [comment]
@jabraham17 - what's the status of what this issue tracks?

**Comment by jabraham17** [comment]
I had some notes to close this, it should be good to go ahead and just close
