### ISSUE TITLE
Proposal: replace `isAnyCPtr()` with type checking functions similar to those of other types

### ISSUE THREAD

**Issue by riftEmber** [chapel-lang/chapel#21386]
This proposal is to replace `isAnyCPtr()` with new functions `isCPtr()`, `isCPtrType()`, and `isCPtrValue()` to match what we provide for built-in types in the `Types` module.

This was proposed in the `CPtr`/`SysCTypes` module review but the notes do not reveal if consensus was reached on doing this or not. Additionally, I am unsure if we would want this implemented in `CTypes` (where `isAnyCPtr()` is now) or in `Types` (where similar functions live).

Poll:
- 🚀 : implement the new functions in `CTypes`
- 🎉 : implement the new functions in `Types`
- 😕 : do not add the new functions
- ❤️ : do something different (please specify in reply)

**Comment by bradcray** [comment]
A question for those who voted :rocket: (so far, @mppf and @lydia-duncan).  That vote was my first impression as well.  Then I found myself wondering whether we're going down an unattractive slippery slope here, in the following sense:

* Should this module also be expected to define `isC_int[type|value]()` `isCintegral[type|value](), `isC_float[type|value]`, `isC_char[tyoe|value]`, etc. for all types and/or type classes that it supports?
* Should a user module I write defining a record `R` be expected to support `isR[type|value]`?  Or maybe only if it's generic?

Given that `c_ptr(?)` is a pretty reasonable type query to write when needing this kind of constraint today, this makes me wonder whether we don't actually need to add these queries (or could add them later if/when motivation comes up) and could just deprecate the current query.  That said, the answer to that may depend heavily on what we do with respect to `c_void_ptr`.  In particular, this query is more useful given that it doesn't fit the `c_ptr(?)` mould, but if we were to start writing that as `c_ptr(void)` then the utility of it goes away significantly.

Based on this thought process, I think my current leaning would be to rewrite `c_ptr(void)` and then consider deprecating this routine without replacing it, checking what the impact is on existing test code.  But I don't feel strongly enough about that at this point to vote :heart:, so decided to kick off this discussion instead.

**Comment by mppf** [comment]
I agree that we probably don't need `isAnyCPtr` at all if we don't have `c_void_ptr`.

**Comment by lydia-duncan** [comment]
I don't think adding this necessitates a slippery slope.  I think it's perfectly reasonable to just stop until someone requests more.  I also wouldn't view this as _requiring_ a user defining `R` to need to add `isR[type|value]` unless they find it useful for them - after all, we add plenty of types in other standard modules and haven't felt the need to add such checks (nor do I find this motivating to consider doing so).

To me, the difference here is that a `c_ptr` has two pieces of information that could be cared about - the pointer itself and the type it wraps.  It seems reasonable to want to get both, and more difficult conceptually to get the former without an explicit call available.  An `isCPtr` function is the first thing I'd search for if I wanted that information, and if it wasn't available, I'm not sure how I'd find that I should be writing `c_ptr(?)`

**Comment by bradcray** [comment]
> I don't think adding this necessitates a slippery slope. I think it's perfectly reasonable to just stop until someone requests more.

Fair enough.  But why support the query out of the gate for 2.0 rather than removing it and waiting to see whether people request it?  Particularly given how rarely it's currently used and how none of the other types in this module have such queries?  (setting up an asymmetry).

**Comment by lydia-duncan** [comment]
I think the main reason for me to provide it is that I'm not personally sure how I would write such a check if it wasn't available.  So it seems like since we have the capability currently and it'll be difficult for someone to write on their own (unless I'm missing something), we should continue to provide it rather than having to reinvent the wheel if someone was relying on it.  Having to write it again later also exposes us to loss of lessons from the original, potentially reintroducing bugs that were solved in the previous version.

**Comment by mppf** [comment]
Seems to me we could make it unstable or no-doc'd to address those concerns.

**Comment by bradcray** [comment]
> Having to write it again later also exposes us to loss of lessons from the original

I think of the repository history and this issue as being useful in this regard.  But also, comparing the first commit to the current one, it looks like the only change that's been made is to change from `where` clauses to type constraints (presumably to accelerate compilation), so there's not much in the way of evolution or lessons learned.

> I'm not personally sure how I would write such a check if it wasn't available

I was imagining:

```chapel
proc isCPtr(type t: c_ptr(?)) param { return true; }
proc isCPtr(type t) param { return false; }
proc isCPtr(p: c_ptr(?)) param { return true; }
proc isCPtr(p) param {return false; }
```

(and then similarly for the type-/value-specific versions.  In these versions, I'm assuming that we end up rewriting `c_void_ptr` as `c_ptr(void)` though that's not guaranteed yet).

Just to reiterate why I'm proposing deprecating/removing/destabilizing these:   It's mostly the asymmetry of "Why does this module support these queries, but not queries for the other types it introduces?" combined with a general sense of "the less we have to stabilize for 2.0 the better" and "there don't seem to be many uses of this...".

**Comment by riftEmber** [comment]
The [CTypes design subteam](https://github.com/Cray/chapel-private/issues/4824) has decided to remove `isAnyCPtr` (and not add any similar or replacement function) from CTypes' public interface for 2.0. If need for these arises they may be reintroduced in some form in the future. I have created https://github.com/Cray/chapel-private/issues/4869 to track implementation.
