### ISSUE TITLE
Hide implementation of `c_ptr` and `c_array` from docs

### ISSUE THREAD

**Issue by riftEmber** [chapel-lang/chapel#21385]
Currently these are both implemented as classes in `CTypes`, and are `chpldoc`'d normally. They may in future become record or other types, and in any case the user does not need to and should not know that they are Chapel classes. This issue is to hide the underlying class from docs, create a type alias which is documented, and document its methods as secondary methods without revealing the underlying class.

**Comment by riftEmber** [comment]
I've run into a lot of implementation problems with this and am inclined to say it is not worth the effort that would be required to do this. Here's what I've tried:
- Implementing `c_ptr` under a hidden secret name, then using the compiler to map that implementation name to `c_ptr`. This was attempting to model after what we do for `string` and `bytes`. I ran into the problem that this compiler name mapping would make `c_ptr` a built-in type, which we do not want `c_ptr` to be.
- Putting `c_ptr` under a hidden implementation name (`_c_ptr`) that is no-doc'd, plus a type alias `type c_ptr = _c_ptr`. This leads to a pretty nice looking type header with documentation, and methods can be moved into secondary methods to be separately documented. There is a small downside that the hidden name is printed in the type header in the docs, but that isn't so bad. However, this causes test failures as the name of the type when printed (including in error messages) is `_c_ptr`.
  - Using split-init for the type alias can hide the name of the internal type from the docs, but does not fix the other issues.
- No-doc'ing `c_ptr`, but creating a `.. type:: c_ptr` entry in a comment for chpldoc to pick up on and generate documentation of. When that entry is in the comment before `c_ptr`, it doesn't work since `c_ptr` is no-doc'd, so it doesn't get picked up. I tried instead putting it at the top of the module, so it would get picked up on as part of generating the module-level documentation. This caused the entry to be generated, but is pretty hacky and also gives poor control over the order the entry shows up in with others. Particularly, there doesn't seem to be any way to put the documentation of its methods immediately after it. Another problem is that the fields of the class (`eltType`) do not have any documentation generated for them, nor is there a way I can think of to make that happen short of just writing about `eltType` in the `c_ptr` docs blurb.

I think to get things to work properly, we would need modifications to `chpldoc` itself. We could allow some way to manually specify that a `class` or `record` will simply be doc'd as a `type`. We could also allow `.. type::` entries to be free-standing and not attached to any symbol that is getting `chpldoc`'d otherwise. I think the first of these two would be less of a shift in how `chpldoc` does things.

I think the amount of work to do this is not worth putting on the 2.0 critical path and should be left to the future.

**Comment by bradcray** [comment]
> I think to get things to work properly, we would need modifications to chpldoc itself. We could allow some way to manually specify that a class or record will simply be doc'd as a type. We could also allow .. type:: entries to be free-standing and not attached to any symbol that is getting chpldoc'd otherwise. I think the first of these two would be less of a shift in how chpldoc does things.

That's an intriguing idea and feels like potentially a good use of an attribute (which might also be low-hanging fruit to implement).  E.g.,

```chapel
@chpldoc.hideType
class c_ptr { ... }
```

could potentially be generated as:

```
type c_ptr;
```

?

**Comment by riftEmber** [comment]
@bradcray That makes a lot of sense -- I was thinking of some kind of annotation inside the doc comment, which would probably be a lot more difficult to implement. I will try out the attribute and see how that goes

**Comment by riftEmber** [comment]
Given the time design discussion would take I would like to leave this off for post-2.0 work. For future reference, I prototyped the annotation route on my branch https://github.com/riftEmber/chapel/tree/wip-hide-cptr. I generated the docs locally and it looks like it works as desired.
