### ISSUE TITLE
proposal: don't use ref-maybe-const in production modules

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#21399]
This issue proposes that ref-maybe-const be less available in non-prototype modules as a solution to some of the problems identified in #21398.

### Background on Prototype Modules

Chapel has two different types of modules in order to support different language rules for quick programming and more production-oriented programming. We can call these prototype modules and production modules. Note that `.chpl` files without an outer `module` declaration end up with an implicit `prototype module`. Currently, the only difference is that errors do not need to be caught in prototype modules (instead, the program will halt if an error is encountered). See also https://chapel-lang.org/docs/language/spec/modules.html#prototype-modules . 

### Proposals

Both of these problems solve the Documentation and API Stability problem brought up in #21398. Additionally, they would arguably reduce the cases where these features are depended upon in a deep way since they will only really be available in prototype modules. As such, they could help with the Compiler Architecture, Interfaces, and Universal Method Call Syntax issues by making special behavior for those cases (namely: errors for recursive functions, different intent within interfaces, and weirdness of 1st argument, respectively) less worrying.

#### Proposal 1: Production modules don't use ref-maybe-const 

Within a production module, instead of ref-maybe-const intent for array formals and record `this` formals, the default intent would be `const ref` in these cases.

Would the default task/forall intent for arrays in production modules also be `const ref`? Or would it stay ref-maybe-const? Note that the task/forall intent does not pose inter-procedural / library API challenges in the same way as the intent for all function formals. We can imagine either changing the task/forall intent for arrays to be `const ref` in production modules; or we can imagine keeping them as ref-maybe-const.

If the task/forall intent becomes `const ref`, then `forall` loops etc. modifying arrays would need to have add e.g. `with (ref myArray)` in production modules.

If the task/forall intent remains ref-maybe-const, then it would be a way in which task/forall intent differs from default argument intent. But, code changes would be focused on the function signature for functions working with arrays in parallel.

Pros:
 * Blank intent still has useful meaning in production code
 
Cons:
 * This would be a breaking language change. It is unknown how much application code or test code would need to change.

#### Proposal 2: Production modules warn for ref-maybe-const

Within a production module, when the compiler encounters a formal that has ref-maybe-const intent, it would warn and ask the user to use `const` or `ref` intent. A refinement on this idea is that it could warn specifically only in the case that the blank intent is inferred to be `ref`. The idea of a warning here is that it's something that might work OK but would communicate better with people if it is adjusted.

Pros:
 * We could argue that this approach would not be a breaking language change since it is only a warning.

Cons:
 * For certain types, blank intent might have no useful meaning in production code

**Comment by jabraham17** [comment]
Closing this, as we decided to deprecate and remove ref-maybe-const. See https://github.com/chapel-lang/chapel/issues/21398
