### ISSUE TITLE
Readline with custom newline

### ISSUE THREAD

**Issue by pierce314159** [chapel-lang/chapel#21392]
We are in the process of adding a CSV reader to arkouda. We want to support custom row delimiters (this is captured in https://github.com/Bears-R-Us/arkouda/issues/2065) and are finding ourselves reaching for a way to read line-by-line in chapel with a custom line delimiter. Something similar to:
```chapel
reader.lines/read_line(delimiter="my_delimiter")
```

It's completely possible that this functionality is already available in the language, but we were struggling to find the appropriate function after digging a bit in the documentation/issues. It seems like these issues might be relevant?
https://github.com/chapel-lang/chapel/issues/19769
https://github.com/chapel-lang/chapel/issues/14107#issuecomment-531816523

based on the related issues it seems @mppf might be most involved with this / most likely to know of a good workaround
tagging @Ethan-DeBandi99 who is leading this effort

Somethings we have tried:
```chapel
// using readf
myFile.readf("%s\r", myString);

// read with new ioLiteral
read(myString, new ioLiteral("|")
```
We have a workaround for this, but it would require us to read the whole file in multiple times, which is not ideal

**Comment by mppf** [comment]
@pierce314159 - I agree that using #19769 for this is a good goal, but that doesn't exist yet.

In the meantime, here is a prototype that reads strings separated by semicolon.

``` chapel
use IO;
import OS.EofError;

proc main() {
  var f = openTempFile();

  f.writer(locking=false).write("1 2 3; 4 5 6; 7");

  var r = f.reader(locking=false);

  var sepByte: uint(8) = ";".toByte();
  var s: string;
  while readSep(r, sepByte, s) {
    writeln("READ '", s, "'");
  }
}

proc readSep(reader: fileReader,
             sepByte:uint(8),
             ref result:string): bool throws {
  var reachedEof = false;
  // note the current fileReader position and mark
  var start = reader.offset();
  reader.mark();
  // advance to just after the requested byte 
  try {
    reader.advancePastByte(sepByte);
  } catch e: EofError {
    // it's OK if EOF is reached; just track it
    reachedEof = true;
  }
  // note the current fileReader position and go back
  var end = reader.offset();
  if !reachedEof then end -= 1; // don't include separator in output
  reader.revert();
  // now read the data and advance past the separator
  reader.readBinary(result, maxSize=end-start);
  if !reachedEof then reader.advance(1); // pass separator byte
  // return 'true' if something was read, 'false' on EOF
  return end > start || !reachedEof;
}
```

If you need something fancier, it is in principle possible to build it by combining mark/revert with reading one byte at a time.

**Comment by Ethan-DeBandi99** [comment]
@mppf - Thanks for the quick response. This should be very helpful. I think in the interest of getting the base functionality in, I am going to do an initial implementation on supporting `\n` and then update it to leverage this for custom delimiters. Thanks!

**Comment by bradcray** [comment]
@mppf: Capturing my take on a question posed in a meeting today:  Are there any significant barriers to getting `readUntil()` into the IO module for 1.30, say, apart from getting it onto someone's short list of priorities?  E.g., would it be as easy as getting a developer to pick up your code above and turn it into our official `readUntil()`, or are there reasons other than resourcing that would cause us to want to wait on that?  Thanks!

**Comment by lydia-duncan** [comment]
We still have some design thoughts on it that need resolving, but those are on the docket for the IO re-review next Tuesday

**Comment by mppf** [comment]
@bradcray - I don't know of any other barriers, beyond what @lydia-duncan and the resourcing part.

**Comment by bradcray** [comment]
OK, thanks, I had forgotten there were still outstanding design questions, but see them now (assuming we're talking about the 2x2 matrix of possible behavior options at the end of #19769).  FWIW, it sounds as though if we were able to get it in for 1.30, it would be appreciated by the Arkouda devs.

**Comment by bradcray** [comment]
@pierce314159 and @Ethan-DeBandi99 : In your use cases, which behavior would you want of the choices listed in https://github.com/chapel-lang/chapel/issues/19769#issuecomment-1123770587?

Reordering/rephrasing them here, and eliminating one option:
1. consume the delimiter and return it in the string
2. consume the delimiter, but return the string without it
3. leave the delimiter unconsumed (it'll be the next thing to be read from the file)
4. leave the delimiter unconsumed (it'll be the next thing to be read from the file), but also return it in the string

**Comment by pierce314159** [comment]
@Ethan-DeBandi99 can correct me if i'm wrong, but I think option 2 (consuming the delim and not returning it) is what we'd prefer for this use case

**Comment by bradcray** [comment]
Thanks for filing this issue @pierce314159 and for the new routines, @jeremiah-corrado !
