### ISSUE TITLE
Design of new array.find() method

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#21423]
In discussing #18089, one of the conclusions was that while array.find() was useful, if retained, its interface should be more similar to that of string.find() and bytes.find().  This led to array.find() being marked unstable in #20562.  In this issue, I'm proposing what the new definition of array.find() should be in hopes of deprecating the existing version sooner and moving to the new signatures in time for Chapel 2.0.

My proposal involves two overloads of `.find()`:

* one designed to work for any array type
* the other designed to work for rectangular domains of integers, where there's an "obvious" sentinel value to return if the value is not found.

Here's my current draft of these routines, where `chpl__fullIdxType` is meant to be a stand-in for `rank*idxType` for a multidimensional rectangular array and `idxType` for a 1D rectangular array or associative array:

```chapel
    /*                                                                          
                                                                                
      Search an array for ``val``, returning whether or not it is               
      found.  If the value is found, the index storing it is returned           
      in ``idx``.  If it is not found, the final value of ``idx`` is            
      unspecified.                                                              
                                                                                
    */
    proc find(val: this.eltType, ref idx: chpl__fullIdxType): bool {

    /*                                                                          
                                                                                
      Search a rectangular array with integral indices for ``val``,             
      returning the index where it is found.  If the array contains             
      multiple copies of ``val``, the lexicographically earliest index          
      will be returned.  If ``val`` is not found,                               
      ``domain.lowBound-1`` will be returned instead.                           
                                                                                
      Note that for arrays with ``idxType=int(?w)`` (signed ``int``             
      indices), if the low bound in a dimension is ``min(int(w))``,             
      the result will not be well-defined.                                      
                                                                                
    */
    proc find(val: this.eltType): chpl__fullIdxType {
```

Some rationale for the decisions:
* For the case of rectangular arrays with integral idxType, I believe `array.domain.lowBound - 1` should be returned (where, for multidimensional arrays, this is shorthand for `array.domain.lowBound - (1, 1, 1, ...)` for a 1-tuple of the appropriate rank.
  * In the case of searching a 0-based 1D array, this has the benefit of returning -1, making it symmetric with `string.find()` and `bytes.find()`.
  * My reason for choosing `.lowBound` rather than simply `.low` is because:
    * (a) in most common cases they're one and the same, so it's a wash
    * (b) when they do differ, it seems less error-prone to count down from the value that's on the boundary of the array's "bounding box" rather than its lowest represented index.  For example in an array over `{1..10 by 2 align 2}`, `.low` is 2 where `.lowBound` is 1, and it seems like it could be confusing to return `1` yet see it in the domain's index set.
    * (c) though I don't think we've committed to our definitions of `.low` and `.lowBound` on sparse domains, I could imagine `.low` _potentially_ being viewed as the lowest represented index in the sparse domain, whereas there's not likely to be a question that the bounding box's low bound is the true `.lowBound`.
* For associative arrays or rectangular arrays of bool/enum idxType (say), it's harder to return a sentinel index, since:
  * there's no obvious low bound for associative arrays, and no easy way to find an index that isn't in its domain
  * given the finite (and typically modest-sized) bool/enum idxTypes, the array could easily span all indices, leaving no legal value to return
  * for this reason, we return a bool saying whether or not we found the value and "return" the index through a `ref` argument
    * I used `out` rather than `ref` since it's not obvious what we would set the value to if we didn't find the value
    * (I also imagined that maybe the user would want to pass a sentinel value in and check for it, though I haven't currently guaranteed we won't modify the value)
* In the event that multiple copies of the value are found, the one whose index is lexicographically lowest will be returned (similar to `maxloc` reductions, which also suggests an implementation approach)

This is drafted in #21429

**Comment by bradcray** [comment]
I implemented a draft of this over the weekend and have captured the slightly polished version here:  https://github.com/bradcray/chapel/tree/new-array-find

**Comment by bradcray** [comment]
@e-kayrakli and @stonea : I'd be particularly grateful for your thoughts here given your past participation in discussions on array.find() (and Engin's likely experience with string.find() and bytes.find()).

**Comment by stonea** [comment]
Seems like it works nicely for 0-based 1-dimensional arrays which is probably the common case.

I can't think of any alternative that I like better; these alternatives being:

- Keeping the inconsistent behavior we had (have array.find return a tuple everything else return -1 if not found)
- Changing `find` for string, bytes, and list so they return a tuple like we did for arrays
- Having `find` for all versions throw an exception if an element isn't found
- Having `find` take an output parameter to return the index if found and return a bool to indicate if it was found or not

Given your suggested design, I imagine (out of laziness or whatever) if I was working outside this particular case I'd probably end up writing code like this:

```
idx = A.find(someVal);
if(A.domain.contains(idx)) { /* process value */ }
```

Rather than explicitly checking to see if `idx` were exactly equal (or not equal) to `A.domain.lowBound - 1*A.domain.rank`

**Comment by bradcray** [comment]
Thanks for taking a look, Andy!  (and for the notes).  Going out of order:

> if I was working outside this particular case I'd probably end up writing code like this:

I was similarly imagining people would lean on `.contains()` in cases where they didn't want to hard-code their array's low index into the code.  Or, another approach is to write `if myArray.find(x) >= myArray.low`  That said, if I knew I was working with 0-based or 1-based arrays, I think I'd also often be very willing to compare against the literal values directly, e.g.: `-1`/`(-1,-1)`/... or `0`/`(0,0)`/..., respectively.  These all seem pretty reasonable to me.

With respect to the other alternatives you suggest, having spent lots of time with `.find()` since New Year's Eve:

* I think the ability to have a single returned value to compare against is important/convenient for the sake of putting `find()`s into `if` or `while` loops, which I expect to be a common case.  So that's my main argument against continuing to return a tuple.
* The same reason is also motivation to not have it throw by default (though I could imagine another method with a different name or signature that would throw for people who preferred that interface)
* In the cases I was looking at, I considered the `find()` logic to be a small/sidebar part of a much larger and more interesting computation, yet the find() had an oversized impact on performance.  That makes me reluctant to add any unnecessary overhead, where throwing might do so?
* I suppose returning a bool and then passing the found index out through an out argument could be a variant that would still work in an if/while scenario; and interestingly, we could support that signature as well for people who preferred it since it would have a different signature / overload from this proposal.  But I don't think that I'd only support that signature, primarily because I think the string/bytes.find() interface is so familiar from other settings.  So my proposal would be to start with this interface and file that one away as a potential future thought if someone requested it / we found a killer use-case for it.

**Comment by stonea** [comment]
> I suppose returning a bool and then passing the found index out through an out argument could be a variant that would still work in an if/while scenario; and interestingly, we could support that signature as well for people who preferred it since it would have a different signature / overload from this proposal. But I don't think that I'd only support that signature, primarily because I think the string/bytes.find() interface is so familiar from other settings.

I'm not particularly a fan of output parameters either but I am a fan of being able to write one-liners; I think it makes sense to wait until we have a use-case but as long as we're brainstorming let me throw out a wild suggestion, why not take a note from C (or apparently Python with its "Walrus operator" https://realpython.com/python-walrus-operator/) and have assignment expressions who's value equals whatever the RHS evaluates to?

```chpl
if((const idx = A.find(needle)) != -1) { /* process idx */ }
```

**Comment by vasslitvinov** [comment]
I empathize with the intention. Alas, as discussed above, the proposed solution has limited applicability. It is not available when the array's domain:
* has idxType=uint, lowBound==0 // although, OK, we can say that `0:uint - 1` is well-defined
* has idxType=bool or an enum, esp. a single-value enum
* is an associative domain, e.g., domain(int), where any int can be a legal index
  * finding an int NOT in this associative domain, to return as a sentinel, may be costly

About throwing: having find() throw for some arrays and do something else for other arrays will make it hard to use in generic code that accepts all arrays. Also might make such generic code slower by imposing exception handling for DefaultRectangular instantiations where it is not needed.

What to do, then?

I propose:

* define the index-or-sentinel-returning find() ONLY for those cases where it makes sense / is easy to use
* provide something else for the general case, for example see next
* provide `array.contains()` that returns a bool directly, avoiding the round-about "get an index then compare it against a sentinel"
* provide an overload of `array.contains()` with an extra `out` argument for the index

For the latter:
* this is my tweak on a `find` overload discussed above, whereby...
* the name `contains` makes more sense and results in a more consistent interface than `find`
* should this extra argument be `out` or `inout` ?
  * `out` allows the actual to be split-initialized, whereas
  * `inout` allows the user to provide the default value

Other options:
* `find(needle=..., returnTuple=true)` (discussed above, available for any array)
* `find(needle=..., returnMode=indexOrSentinel | whetherFound | tuple)`

**Comment by e-kayrakli** [comment]
I am in support of the original proposal.

Can we resolve the issue with associative arrays by providing an additional `sentinel` argument to `find`, where the user can provide a value to represent the not-found case? This argument can be defaulted for cases where there's a clear sentinel, while also providing the user the opportunity to provide their own sentinels. That can help with the cases where a domain can be resized and the returned value from a prior unsuccessful `find` is no longer an invalid index to an array. But that may be too contrived of a use-case.

On a quick thought, this can allow generic programming between rectangular and associative cases. But I may be overlooking details. It wouldn't offend me if we would need to do the same thing for string and bytes.

**Comment by bradcray** [comment]
@stonea : W.r.t. your walrus-operator suggestion:

> why not take a note from C (or apparently Python with its "Walrus operator" https://realpython.com/python-walrus-operator/) and have assignment expressions who's value equals whatever the RHS evaluates to?

I don't want to have to make a language change in order to support array.find() before 2.0.  We can consider that change on its own merits if you want to champion it, though—on a separate issue.  I just don't want to gate support for array.find() over it.

As background, Chapel intentionally hasn't supported `=` as an expression or `==` as a statement, in order to avoid C-style mix-ups (which, I have to admit with some shame, I find I still sometimes make today).  Making a distinct operator, as it sounds like Python has done, or making this an extension to newly declared variables/constants in control flow both seem potentially viable to me if there's appetite for it (though I suspect there'd be more after 2.0 than before).  I know at least one user who would be happy to see a `:=` assignment operator in Chapel, particularly if it was supported at both the statement and expression level.

(don't answer this here, but do you know why Python didn't support it as a statement-level operator?  Was it simply to strictly adhere to the "no two ways of writing something" principle?  (even though parenthesizing it seems is a simple workaround for that, unless I've misunderstood something?))

**Comment by bradcray** [comment]
@stonea , @e-kayrakli , @vasslitvinov : I'm re-pinging for reactions to the revised approach [in the comments two above](https://github.com/chapel-lang/chapel/issues/21423#issuecomment-1411314175), from "Full speed ahead" to feedback to "We really need to talk about this".

**Comment by e-kayrakli** [comment]
I have no problem with that proposal.

The `ref` argument overload is a bit clunky, but I understand the issues with the enum/bool case and it looks like a good solution for that.

**Comment by stonea** [comment]
I think your revised approach is good.

I'm assuming for the simpler interface you still plan on returning `array.domain.lowBound - 1` when the element isn't found? If I had to come up with a concern it would be: "what if `array.lowbound == min(array.idxType)`"? Would it be a runtime error, compile-time error, exception, or a silent wrong answer if they used the simple interface? Maybe it's too corner-casey but I don't think it's that inconceivable that someone would use 0-based indexing and uints for `idxType`.

**Comment by bradcray** [comment]
> I'm assuming for the simpler interface you still plan on returning array.domain.lowBound - 1 when the element isn't found? If I had to come up with a concern it would be: "what if array.lowbound == min(array.idxType)"? Would it be a runtime error, compile-time error, exception, or a silent wrong answer if they used the simple interface? Maybe it's too corner-casey but I don't think it's that inconceivable that someone would use 0-based indexing and uints for idxType.

That's correct, and I addressed this in an earlier draft of my last proposal, but it must not have survived the edit cycle.  My current thinking is that in both cases, we return `lowBound-1` and let the result be as well- or poorly-behaved as it is on the integers themselves.  Thus, the 0-based uint case, would wrap around to `max(uint(w))` since integer wraparound is well-defined on uints; and in the `min(int(w))` case where wraparound isn't well-defined, we just say that the result isn't well-defined (and expect that people either aren't creating `min(int(w))`-based arrays very often or will turn to the other signature in such cases).

**Comment by bradcray** [comment]
Thanks!  I've updated the OP with the revised proposal.

I'm also hiding the comments so far since they're resolved by the revised proposal, so that if others comment, they won't think they need to read the full history before doing so.

**Comment by bradcray** [comment]
Intriguingly, and much to my surprise, our latest/fast revcomp is actually much cleaner with the two-argument form of `find()`.  That doesn't change my mind about the current proposal, but does make me feel even more positively about it.
