### ISSUE TITLE
Compiler seg fault calling `gpu allocShared` with const variable.

### ISSUE THREAD

**Issue by DanilaFe** [chapel-lang/chapel#21422]
### Summary of Problem
Calling the `gpu allocShared` primitive with size dictated by a product of a const variable and a call to `numBytes`, I get an internal error (segfault). I would have expected it to just allocated the correct number of bytes.

```
transpose-bug1.chpl:7: internal error: seg fault [util/misc.cpp:1037]
Note: This source location is a guess.
```

### Steps to Reproduce

**Source Code:**

```chapel
use CTypes;

pragma "codegen for GPU"
pragma "always resolve function"
export proc transposeMatrix() {
  const localBlockSize = 16;
  var smVoidPtr = __primitive("gpu allocShared", localBlockSize*numBytes(int));
  var smArrPtr = smVoidPtr : c_ptr(int);
  smArrPtr[0] = 0;
}
```

**Compile command:**
```
chpl transpose-bug1.chpl
```
### Configuration Information
```
chpl version 1.30.0 pre-release (14ad4dca7b)
  built with LLVM version 14.0.0
Copyright 2020-2023 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
```

```
CHPL_TARGET_PLATFORM: cray-cs *
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: gpu *
CHPL_COMM: none *
CHPL_TASKS: qthreads
CHPL_LAUNCHER: slurm-srun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: bundled *
CHPL_AUX_FILESYS: none
```

```
Currently Loaded Modulefiles:
  1) cce/15.0.1                  3) craype-broadwell            5) cray-mvapich2/2.3.6         7) perftools-base/23.02.0      9) rocm/4.2.0                 11) cudatoolkit/11.0
  2) craype/2.7.15               4) craype-network-infiniband   6) cray-libsci/20.03.1         8) PrgEnv-cray/8.3.3          10) gcc/8.1.0
```

**Comment by stonea** [comment]
Note that the size for `gpu allocShared` needs to be a compile-time constant. Seems like this example is something that would have been constant folded before we process the primitive, but maybe this issue has something to do with that?

**Comment by bradcray** [comment]
Changing `const localBlockSize = 16;` to `param localBlockSize = 16;` would guarantee that the constant folding would take place before the primitive was evaluated.  If the primitive is one that's implemented in our compiler (vs. resulting in a codegen'd pattern), it's unlikely to happen in time.  If it results in a codegen'd pattern, it would be relying on the back-end compiler to fold the operation.

**Comment by DanilaFe** [comment]
With the new `createSharedArray` proc, this issue is largely not a problem:

```Chapel
use CTypes;

pragma "codegen for GPU"
pragma "always resolve function"
export proc transposeMatrix() {
  const localBlockSize = 16;
  var smVoidPtr = __primitive("gpu allocShared", localBlockSize*numBytes(int));
  var smArrPtr = smVoidPtr : c_ptr(int);
  smArrPtr[0] = 0;
}
```

Produces the following error:
```
seg.chpl:6: In function 'transposeMatrix':
seg.chpl:8: error: unresolved call 'createSharedArray(type int(64), int(64))'
$CHPL_HOME/modules/standard/GPU.chpl:191: note: this candidate did not match: createSharedArray(type eltType, param size) [181952]
seg.chpl:8: note: because non-param actual argument #2
$CHPL_HOME/modules/standard/GPU.chpl:191: note: is passed to param formal 'param size [181956]'
seg.chpl:8: note: unresolved call had id 178835
```

The segfault while using the primitive remains, but since we don't expects users to be writing the primitive, I'd personally be fine with it remaining.

**Comment by stonea** [comment]
> The segfault while using the primitive remains, but since we don't expects users to be writing the primitive, I'd personally be fine with it remaining.

I agree, I'd say this issue can be closed.
