### ISSUE TITLE
using proto-interfaces for special method naming

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#21431]
This issue is a spin-off from https://github.com/chapel-lang/chapel/issues/19050#issuecomment-1375836834 . It is a proposed approach to #19038.

It is arguably duplicative of #19074, however this issue has a different focus. It is focused on how we can use interfaces for namespacing even if most constrained generics/interfaces features are not yet implemented.

### The idea

The idea is to basically use the interface being implemented as a way to namespace certain methods. To do that, we need to be able to:
 1. Indicate when defining a method (or, potentially at a later point), that the method should be "namespaced" to the interface.
 2. Call a method from a specific interface

Here is a straw-person proposal for both of these steps:

``` chapel
// In a user module:
// define a hash method for MyRecord that the standard library
// (or anything working with the Hashable interface) can use
MyRecord implements Hashable {
  proc MyRecord.hash() { ... }
}

// In the standard library:
// call a hash method on a type through a specific interface
// Note: this is assuming that the function is not a
// constrained-generics function but rather a traditional generic
proc someGenericFn(arg) {
  // call the hash method for MyRecord's implementation of Hashable
  var h = (arg:Hashable).hash();
  ...
}
```

Later sections will discuss each of these portions in more detail (including alternatives).
 
### Why does it help with the special method naming?

We have these two motivators from #19038:
 1. How can I be alerted that I'm opting into a special method rather than happening to use a name that Chapel gives special meaning to?
 2. How can I ensure that my code will not break if/when more special methods are added over time?

For 1., it is clear that the hash implementation above is defining something for the Hashable interface (by virtue of being within `implements Hashable`). You have to associate it with the interface for the special meaning to take effect.

For 2. the key is that the standard library indicates it is looking for a hash function from the Hashable interface. We cannot find a plain `proc MyRecord.hash` from such a call. That way, if we add a new interface and new special method (say, interface Fooable and `proc foo()`), standard library code will not call a pre-existing function named `proc MyRecord.foo()`. Calling such a function as part of `Fooable` has to be opted in to. In other words, you can have methods with the same name as new special methods as long as you don't associate them with the interface.

One implication of the above is that we would have to allow `hash` to be defined both as one implementing the interface Hashable and as a different method. This could be confusing, but it's essential to provide the property that we can add special methods even if a user was using the name.

What all of this does is move the naming conflict from the method to the interface name. Naturally, now we have the question, "What if I was using the interface name Hashable, and then the standard library introduces Hashable?" I think that this problem can be solved by `import` and qualified naming (so you might have `ChapelStandard.Hashable` which is different from `MyModule.Hashable`).

### What interface features are required?

A key question here is: do we have time before we need to stabilize this to implement enough of the interfaces functionality? In this issue, I'm proposing that we implement "proto-interfaces" to support the special method naming. These will need to be stable before all of our interfaces functionality, and we will want them to be compatible with whatever we define for interfaces in the future. However I think implementing these quickly and making the future interfaces work compatible with them is achievable.

What would the short implementation be?

``` chapel
MyRecord implements Hashable {
  proc MyRecord.hash() { ... }
}
// compiler could think of this as defining both
// MyRecord.hash as well as something named "(ChapelStandard.Hashable).hash"
```

``` chapel
(element:Hashable).hash()
// compiler could think of this as calling something named "(ChapelStandard.Hashable).hash"
```

As far as the definition of the Hashable interface itself in the standard library, that would not be stable (and in fact it could be undocumented). However, I expect it to look something like this:

``` chapel
interface Hashable {
  proc Self.hash(): uint;
}
```

Now, we can adjust the definition of `Hashable` over time as the definition of interfaces evolves. However, we will need it to insist on certain properties of the provided `hash` method and that part needs to be stable.

So, what elements of the interface design need to be stable?
 1. will the interface require particular formal names? Or will there be a way of opting in or out of that? (#17895)
 2. will the interface require particular intents? (#16988)

A straw-person answer to the above is 1) yes we will be strict about formal names and 2) yes the special methods will have to use explicit intents that match the signature in the interface.

What elements of the interface design would need to be implemented?
 * checking that the provided `hash` method implements the interface
   * this could be more strict that we expect for general interfaces (using, say, an pragma on the standard library interfaces used for this purpose)
     * as I described above, we could require the signature match exactly with concrete intents for all of the formals and exactly the same formal and return types
     * in the future, I would expect implicit conversions to be allowed (for passing and returning), but we may wish to be strict here to allow room for the interfaces implementation to evolve

An alternative to the above would be to create a special different kind of `interface` that is used for namespacing only and avoids all such checking (say, with a pragma). That could be plan B, but I think the solving the above is achievable, and it sets us up for using constrained generics in the standard library in the future. (Vs, with a namespace-only interface, user code would have to switch to the real interface if the standard library migrates).

### Alternative ways to specify the special method

The example above is based upon the [CHIP 2 syntax](https://github.com/chapel-lang/chapel/blob/main/doc/rst/developer/chips/2.rst#example-4):

``` chapel
MyRecord implements Hashable {
  proc MyRecord.hash() { ... }
}
```

That seems acceptable to me.

I think it should be possible to omit the inner `MyRecord` and use `Self` instead:

``` chapel
MyRecord implements Hashable {
  proc Self.hash() { ... }
}
```

I'm not sure if that is implemented or if we have an issue about it.

Earlier versions of this proposal included a form omitting the type name from `implements` but I'm not sure if that is compatible with our longer-term interface goals:

``` chapel
implements Hashable {
  proc MyRecord.hash() { ... }
}
```

Also, in the long term (after 2.0), people should probably be able to write:

``` chapel
proc MyRecord.hash() { ... }
MyRecord implements Hashable;
```

Lastly, it is important to note that this approach relies on *not* implicitly inferring when a type implements an interface. We had started with such inference but backed away from it in 1.25 (see https://chapel-lang.org/releaseNotes/1.25/01-language.pdf slide 39 which says "inference of implicit 'implements' statements is now off by default"). If such a feature is re-enabled, it will have to be disabled for the interfaces used for special method namespacing.

### Alternative ways to indicate the call should use the interface

This one has its own issue: #21343. One thing to note is that to use interfaces as proposed in this issue, we probably don't want to use the constrained-generic wrapper method approach, since we would like to avoid requiring parts of the standard library be implemented with constrained generics before 2.0

**Comment by lydia-duncan** [comment]
Was this syntax part of the original interface proposal?
```chapel
implements Hashable {
  proc MyRecord.hash() { ... }
}
```
It seemed unfamiliar to me as compared to the other syntax but it could be that I didn't remember the proposal clearly.  And I'd be especially curious to hear from @vasslitvinov how much of the interface implementation we'd want for this is already supported, given that there was some prototypical work that occurred

**Comment by mppf** [comment]
It was in the original proposal but with slightly different syntax:

https://github.com/chapel-lang/chapel/blob/main/doc/rst/developer/chips/2.rst#example-4

> ``` chapel
> int implements Semigroup {
>   proc binary_op(x : int, y : int):int { return x + y; }
> }
> ```

So the corresponding thing for Hashable would be

``` chapel
MyRecord implements Hashable {
  proc MyRecord.hash() { ... }
}
```

I will note the variation from the CHIP in the section about the implements part.

**Comment by lydia-duncan** [comment]
I'm curious why we'd differ from that?  It seems like if we're adding partial interface support to accomplish this, what we add should be following the interface proposal so that we make less work for ourselves and users when full interface support is added.

**Comment by mppf** [comment]
Using the CHIP 2 syntax would be fine with me & I consider it a mutable detail of this proposal. The general direction is still the same.

**Comment by mppf** [comment]
Also, I had thought that the `implements Interface { }` thing is from Rust, but it looks like [what Rust has](https://doc.rust-lang.org/book/ch10-02-traits.html#implementing-a-trait-on-a-type) is more like the CHIP 2 proposal:

``` rust
impl Summary for NewsArticle {
  fn summarize(&self) -> String { ... }
}
```

Based upon that I will change the top post to lead with the CHIP 2 syntax and show the shorter form as a potential alternative.

**Comment by dlongnecke-cray** [comment]
For proto interfaces, I was thinking we could use the `prototype` keyword to indicate that the interface is just acting as a namespace shield, without doing advanced checking, e.g.,

```chapel
prototype interface Summary {}
```

I think we could use this as a mechanism to only add what we need to get this sort of namespacing off the ground.

---

I'm at the point where I'm stuck in a loop.

```chapel
module M {
  record r {}
  r implements Hashable { proc self.hash() { return 0; } }
}
module Map {
  record map {
    type T implements Hashable;
    proc doSomething() {
      var x: T;
      const n = x.as(Hashable).hash();
   }
}
```

We've got a `map` that calls `Hashable.hash()`. If I'm some other module `Consumer`, how do I tell the map that I want a different implementation of `Hashable` to be used than the one in module `M`? (Would we even allow more than one implementation of an interface? It seems valuable to me if a user wanted to override some behavior, but...)

I think for this problem to truly be solved we need a way to tell `map` what interface implementation we want it to use when we create a map instance.

Is the answer that we have to create a `Hasher` interface and take a type that implements that (a la' C++)?

```chapel
interface Hasher {
  type T;
  proc hash(x: T) { ... }
}

record map {
  type K implements Hashable;
  type V;
  type H implements Hasher(K) = Map.DefaultHasher; // Imagine Map.DefaultHasher lives somewhere...
}
```

We end up in a bit of a weird spot where even if you want to use your own hasher, you have to implement `Hashable`, but I think that's OK.

This can work, but I still feel like it would be cool to be able to just tell the type where to look when we create the instance or something:

```chapel
var m: map(int, int, Hashable.from(Consumer));
```

**Comment by vasslitvinov** [comment]
This is a neat proposal and looks doable. @lydia-duncan neither of its two key features are available today: a block stmt that goes with an implements statement and casting of a value to an interface: `(arg: Hashable)`. However, having thought (perhaps too much) through this proposal and some alternatives...

I am thinking "oh gosh, this is complicated. It is much simpler to just do `arg.chpl_hash()` and `proc myType.chpl_hash()` ."

**Comment by bradcray** [comment]
We've effectively decided to user interfaces for special methods that aren't defined using reserved words, and have started doing so for the hashing, IO, and context management special methods in Chapel 1.32.  I'm going to close this issue as a result, because I think of it as having staked out a position on https://github.com/chapel-lang/chapel/issues/19038 which has now been adopted even though more implementation remains to make it more and more robust.
