### ISSUE TITLE
Only build TAGS/BROWSE for compiler and runtime with CHPL_DEVELOPER set

### ISSUE THREAD

**Issue by riftEmber** [chapel-lang/chapel#21432]
A todo mentioned on [this docs page](https://chapel-lang.org/docs/1.29/developer/bestPractices/CHPL_DEVELOPER.html) suggests we should avoid building `TAGS` and `BROWSE` files for the compiler and runtime when `CHPL_DEVELOPER` is not set:
> Builds an emacs TAGS and BROWSE file for the compiler and a TAGS file for the runtime. (Note: it seems we currently do this whether or not `CHPL_DEVELOPER` is set, though this seems inappropriate… We should fix this).

**Comment by bradcray** [comment]
@riftEmber : I'm surprised by that documentation, though it looks like I wrote it?  Specifically, in the 1.29.0 sources, I'm seeing:

```makefile
ifeq ($(CHPL_DEVELOPER), 0)
OPTIMIZE=1
else
DEBUG=1
WARNINGS=1
TAGS=1
# always enable assertions in CHPL_DEVELOPER/debug mode
DYNO_ENABLE_ASSERTIONS=1
endif
```

which looks as though TAGS is only set if CHPL_DEVELOPER is set, and then in `compiler/Makefile`, I'm seeing:

```makefile
ifeq ($(TAGS), 1)
TAGS_COMMAND=-@(which $(CHPL_TAGS_UTIL) > /dev/null 2>&1 && echo "Updating TAGS\
..." && $(CHPL_TAGS_UTIL) $(CHPL_TAGS_FLAGS) $(ALL_SRCS) $(ALL_HEADERS)) || ech\
o "$(CHPL_TAGS_UTIL) not available"
EBROWSE_COMMAND=-@(which ebrowse > /dev/null 2>&1 && echo "Updating BROWSE..." \
&& ebrowse $(ALL_SRCS) $(ALL_HEADERS)) || echo "ebrowse not available"
endif
```

which looks like it should guard it appropriately.  And in my (non-developer) build of 1.29.0, I'm not seeing compiler/TAGS.  So could it be that the documentation is just out-of-date?

(All that said, I'm also not clear on how the move to cmake may have changed this...)

**Comment by riftEmber** [comment]
With a fresh non-developer build I see no `compiler/tags` or `compiler/BROWSE` but I do get `runtime/tags`, so that might be the only thing left to change for this issue (as well as removing that todo note from the docs).

**Comment by bradcray** [comment]
Huh...  In the aforementioned non-devel build of 1.29.0, I'm not seeing a runtime/TAGS file, as I do in my developer build, and the Makefiles look similarly appropriately guarded:

runtime/Makefile.help:
```makefile
ifeq ($(TAGS), 1)
TAGS_COMMAND=-@(which $(CHPL_TAGS_UTIL) > /dev/null 2>&1 && echo "Updating TAGS\
..." && $(CHPL_TAGS_UTIL) $(CHPL_TAGS_FLAGS) $(ALL_SRCS) $(CURDIR)/include/*.h)\
 || echo "$(CHPL_TAGS_UTIL) not available"
endif
```

runtime/make/Makefile.runtime.head:
```makefile
ifdef CHPL_DEVELOPER
DEBUG=1
WARNINGS=1
TAGS=1
else
OPTIMIZE=1
endif
```

**Comment by riftEmber** [comment]
Hm, with a completely clean build and fresh shell I got a non-developer build that didn't generate any `tags`. I must have missed something previously, maybe something cached. I thought perhaps it might be system specific (especially since I seem to get lower-case `tags` on my Mac but upper-case `TAGS` on Linux), but it appears on either system with completely fresh setup this is working properly.

In that case, this issue is moot except for removing that documentation note, which I'll do now.

**Comment by bradcray** [comment]
> especially since I seem to get lower-case tags on my Mac but upper-case TAGS on Linux

I believe this is the difference between vim tags and emacs TAGS and you're probably suffering from the fact that it defaults to emacs (b/c it was originally written by emacs developers?).  E.g., could have have CHPL_EDITOR set to `vim` on your Mac, but not Linux?

**Comment by bradcray** [comment]
BTW, a good follow-up to this would be for us to remove that TODO from the CHPL_DEVELOPER docs.  As its author, I can do so if you haven't already (catching up on the past few hours of mail).

**Comment by riftEmber** [comment]
@bradcray I removed it in PR https://github.com/chapel-lang/chapel/pull/21442

**Comment by bradcray** [comment]
Thank you!!!
