### ISSUE TITLE
Build docker image with c-backend

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#21449]
Motivated by https://github.com/chapel-lang/chapel/issues/20845#issuecomment-1278120945, we'd like to be able use the c-backend in the docker image.

I believe the docker image takes a long time to build today. Instead of building the runtime/third-party a second time with gnu, I was wondering if we can just use what used to be "clang-included" as the c compiler (basically use the clang we bundle and avoid having to rebuild the third-party/runtime.)

**Comment by ronawho** [comment]
Whoops, missed that Brad beat me to this in https://github.com/chapel-lang/chapel/issues/21448

**Comment by bradcray** [comment]
Sorry about the confusion!  I thought you were already gone for the day, so thought I was doing you a favor.
