### ISSUE TITLE
Can we replace `deprecated` with the attribute `@deprecated`?

### ISSUE THREAD

**Issue by arezaii** [chapel-lang/chapel#21486]
With the potential changes in https://github.com/chapel-lang/chapel/pull/21425 to allow enable more attributes, can we deprecate `deprecated` in favor of the attribute `@deprecated`?

I would like to propose converting `deprecated` to `@deprecated` which would also allow us to drop the specific token `deprecated` from the lexer. 

In https://github.com/chapel-lang/chapel/issues/14141#issuecomment-1273791742 we mention `deprecated` as a candidate for attributes. Is their still consensus that it would be OK to deprecate the use of the raw token and replace it with `@deprecated()` (or `@deprecated`, depending on the resolution of https://github.com/chapel-lang/chapel/issues/20994#issuecomment-1409735935)?

currently we indicate deprecations with the keyword `deprecated` with an optional message and no parentheses. 
```chapel
deprecated "oldFeature is deprecated, please use newFeature"
proc oldFeature() { }

```

this proposal would convert all the current uses of the `deprecated` keyword to `@deprecated` attributes, so the above would become:
```chapel
@deprecated("oldFeature is deprecated, please use newFeature")
proc oldFeature() { }

```

**Comment by jeremiah-corrado** [comment]
I'm in favor of this change; it feels much cleaner than the current syntax.

To throw out an additional suggestion, I've noticed that Rust has a version number argument in their `deprecated` annotation. Example:
```
#[deprecated(
        since = "1.24.0",
        note = "use the `sign_plus`, `sign_minus`, `alternate`, \
                or `sign_aware_zero_pad` methods instead"
    )]
```

I wonder if adding a version number to our deprecations might be helpful for us to keep track of when symbols can be removed from the library? Particularly if we were to create a simple compiler-enabled tool to request the names of all the symbols deprecated in a particular version.

(It would be a lot of work to add version numbers to all of our deprecations, but potentially helpful)

**Comment by bradcray** [comment]
> (It would be a lot of work to add version numbers to all of our deprecations, but potentially helpful)

If there were support for the proposal, it could be an optional argument to avoid adding past "since" entries.

**Comment by arezaii** [comment]
Closing since the keyword `deprecated` was replaced with the attribute `@deprecated` in https://github.com/chapel-lang/chapel/pull/21425
