### ISSUE TITLE
Can we require `@unstable` and `@deprecated` to use parens with arguments?

### ISSUE THREAD

**Issue by arezaii** [chapel-lang/chapel#21487]
With potential changes to attributes that would come with https://github.com/chapel-lang/chapel/pull/21425, `@unstable` would convert to an attribute I have opened design discussions related to converting `deprecated` to an attribute. Because both of these currently accept a single string argument with no parenthesis, I would like to discuss potentially requiring parenthesis around their arguments. This would bring them into alignment with other attributes and provide more consistency. 

Alternatively, allowing them to continue to exist with a single string argument and no parens would bring up another design issue regarding allowing all attributes to follow that pattern, or restricting it to just `@unstable` and `@deprecated`. 

Assuming we adopt the changes to `deprecated` proposed in https://github.com/chapel-lang/chapel/issues/21486, I would like to propose we deprecate using `@unstable` and `@deprecated` without parens, and begin requiring parens when there are arguments. 

edit to add examples:

today, before any changes, we can write chapel code like this:
```chapel
deprecated "deprecation message"
proc supersededFunction() { }

@unstable "this code will change in the future"
proc notSureAboutThisName() { }

```

With the changes that come in https://github.com/chapel-lang/chapel/pull/21425, we would be able to write:
```chapel
@deprecated "deprecation message"
proc supersededFunction() { }

@unstable "this code will change in the future"
proc notSureAboutThisName() { }

```

And in this issue I'm proposing that we require parens for these, like this:
```chapel
@deprecated("deprecation message")
proc supersededFunction() { }

@unstable("this code will change in the future")
proc notSureAboutThisName() { }

```

**Comment by bradcray** [comment]
If I'm remembering correctly, I think that today, if no string is supplied (to `deprecated` only, maybe?), the compiler generates a default message.  Would this still be supported by writing `@deprecated()`?  (admittedly, I don't know that we actually rely on that capability much because people would usually prefer to customize the message, so maybe it's not all that important).

**Comment by lydia-duncan** [comment]
That's correct and unstable also generates a default message if one is not provided

**Comment by arezaii** [comment]
> That's correct and unstable also generates a default message if one is not provided

And I expect that behavior would continue with this proposal, at least, I'm not proposing we change that.

**Comment by arezaii** [comment]
After https://github.com/chapel-lang/chapel/pull/21425 and https://github.com/chapel-lang/chapel/pull/21822, use of `@unstable "msg"` is deprecated in favor of requiring parens, e.g., `@unstable("msg")`
