### ISSUE TITLE
Fix Arkouda horizon test run to sync up performance data

### ISSUE THREAD

**Issue by bhavanijayakumaran** [chapel-lang/chapel#21504]
Address the issue with nightly arkouda performance test run discussed in this slack thread.
Per the most recent comment on https://jira-pro.its.hpecorp.net:8443/browse/HPCDC-7896 — we need either to stop using ssh to manage syncing graph data from horizon to [tower.dreamhost.com]

(http://tower.dreamhost.com/)https://cray.slack.com/archives/CGSFYJN86/p1674666139365359

**Comment by bmcdonald3** [comment]
The graphs were generated last night with the old method, so I was able to compare them to our new graphs. The only difference is the title, which is being set with `--alttitle "Arkouda Performance Graphs"`. 

I'll add that onto the script, then everything should be back to the way it was.

**Comment by bmcdonald3** [comment]
Merged https://github.hpe.com/hpe/hpc-chapel-code/pull/558 and https://github.hpe.com/hpe/hpc-chapel-ci-config/pull/949 to get back to the new job. Firing off a manual run to see if it worked.

**Comment by bmcdonald3** [comment]
Alright, had to made a couple of other changes, but is all good now: https://chapel-lang.org/perf/arkouda/16-node-xc/?graphs=all

**Comment by bmcdonald3** [comment]
Merged https://github.com/chapel-lang/chapel/pull/21489, so we should see this sync the data automatically tonight and I expect the Arkouda XC jobs to resolve tonight now.
