### ISSUE TITLE
`ioHintSet`: how to reduce confusion with `mmap` and `noMmap` hints

### ISSUE THREAD

**Issue by jeremiah-corrado** [chapel-lang/chapel#21508]
## Background

The `ioHintSet` type is used to pass various hints to the runtime indicating how IO operations should be executed.

It supports the following type methods which are used to construct an `ioHintSet` corresponding to the given hint:

* `empty` (this is the default for procedures that take an ioHintSet as an argument)
* `sequential`
* `random`
* `prefetch`
* `mmap`
* `noMmap`

As an example, one could create a `fileReader` with the `random` hint as follows:

```chapel
use IO;

var r = openreader("path/to/file.txt", hints = ioHintSet.random);
```

Set operations for combining and comparing `ioHintSet`'s are also supported.

## Problem

During a recent IO module review, it was pointed out that it may be confusing to support the `mmap` and `noMmap` type methods.

Because their names are opposites, users might conclude that one of these hints (whichever corresponds to the default) doesn't actually do anything, while the other indicates that the non-default behavior should be used. 

We currently support both because the default mmap behavior is situation dependant (it's affected by other hints, as well as the system configuration). So in a situation where mmap would be used for file access by default, the `noMmap` hint could be used to opt out of it. Alternatively, if it is off by default, then `mmap` can be used to opt in.

So, we'd like to support hints for both opting in and opting out; however, we may want to do something to alleviate the potential confusion with the current design.

## Proposed Solution

Deprecate the `noMmap` method and add a boolean argument to the `mmap` method to toggle between the opposing hints. This would allow the following:

```chapel
// construct an mmap hint
var h = ioHintSet.mmap(true);

// construct a "noMmap" hint
var h = ioHintSet.mmap(false);
```

This proposal has the benefit of unifying the `mmap` related hints under one method. I.e., it makes it feel like a single hint with two possible modes.

**Comment by bradcray** [comment]
I haven't used the new hint forms enough to feel very confident in my opinion, but this approach seems attractive to me relative to the status quo if it doesn't feel like too big of a stretch or too asymmetric w.r.t. the other hints.  As an example of how unfamiliar I am with the new ioHintSet:  If I were to apply 2-3 hints, with this being one of them, is there anything about the argument-taking hint that would make the proposal not work or awkward?

**Comment by jeremiah-corrado** [comment]
>  If I were to apply 2-3 hints, with this being one of them, is there anything about the argument-taking hint that would make the proposal not work or awkward?

I don't think it changes too much or makes it awkward. See the following two examples:

```chapel
var h = ioHintSet.random | ioHintSet.noMmap,
    r = openreader("path/to/file.txt", hints=h);
```

vs.

```chapel
var h = ioHintSet.random | ioHintSet.mmap(false),
    r = openreader("path/to/file.txt", hints=h);
```

**Comment by jeremiah-corrado** [comment]
Resolved by: https://github.com/chapel-lang/chapel/pull/21707
