### ISSUE TITLE
Record Storage Allocation should detail what portions of complex types are stored

### ISSUE THREAD

**Issue by psath** [chapel-lang/chapel#21523]
https://github.com/chapel-lang/chapel/blob/d6aafd1a42c9612b3cf8621fe848dd39985d4732/doc/rst/language/spec/records.rst#L182-L186

Coming from C, the above reads like it would store the raw data for an array just like C structs do. But per Gitter discussion it only statically stores the array _descriptor_. This should be clarified for Arrays and other complex types

**Comment by arezaii** [comment]
The documentation was updated with this suggestion in PR https://github.com/chapel-lang/chapel/pull/21897
