### ISSUE TITLE
Array Primer is unclear that arrays' .domain method is read-only access

### ISSUE THREAD

**Issue by psath** [chapel-lang/chapel#21521]
https://github.com/chapel-lang/chapel/blob/d6aafd1a42c9612b3cf8621fe848dd39985d4732/test/release/examples/primers/arrays.chpl#L103
could be interpreted as R/W, which isn't clarified until
https://github.com/chapel-lang/chapel/blob/d6aafd1a42c9612b3cf8621fe848dd39985d4732/test/release/examples/primers/arrays.chpl#L342-L344

**Comment by bradcray** [comment]
@psath : Thanks for filing this issue and #21522.  I've just filed a (long-stalled-out) update to the arrays primer that addresses these issues and takes a pass over the entire content for clarity.  Hopefully we've left things in a better state for future users overall as a result of your suggestions and the ensuing efforts.
