### ISSUE TITLE
More detail in how to explicitly-specialize generic records to different widths of primitive types 

### ISSUE THREAD

**Issue by psath** [chapel-lang/chapel#21524]
https://github.com/chapel-lang/chapel/blob/c7172cd3a476d35e62aefbca62c3bc52b0395c61/doc/rst/language/spec/generics.rst#parameters-in-generic-types

It would be nice to include an explicit example here of how to instantiate different widths of members within a class/record. Similar to an example given on the Gitter:

```
record R {
  param width: int;
  var D = {1..n};
  var A: [D] int(width);
  ...
  bool big;
  ....
  if (big) {
    R(64);
  } else {
    R(32);
  }
}

**Comment by arezaii** [comment]
The docs are updated with this suggestion in https://github.com/chapel-lang/chapel/pull/21902
