### ISSUE TITLE
Proposals for indicating stability in Chapel

### ISSUE THREAD

**Issue by arezaii** [chapel-lang/chapel#21531]
## Overview

We would like to revisit our current `@unstable` attribute. Today we have only one attribute to indicate stability/instability and a user is required to read the (optional) message left by the developer to understand why the feature is marked unstable.

## Goals for revised stability attribute(s)

1. a better description of the reason something is unstable
2. ability to selectively hide or display unstable warnings
3. ability to note a feature as stabilized

After some internal discussion on the topic in https://github.com/Cray/chapel-private/issues/3974, @mppf identified three different proposals we could offer. 

There is some preliminary work to enable prototyping any of these proposals in draft PR #21425. It should be noted that this work removes the requirement to adapt the parser for every new attribute name, so it will be relatively simple to add additional attributes as we see fit.
 
We'll label these proposals 1, 2, 3 for now, and I'll add a running pros/cons list to each proposal, adding items as they are identified.

## EDIT
The first three proposals did not generate a lot of enthusiasm. Partly based on feedback from @dlongnecke-cray [below](https://github.com/chapel-lang/chapel/issues/21531#issuecomment-1430323538), I am adding a fourth proposal option to model our stability attributes similar to how Rust does.  

### What if we have stable and unstable annotations?

E.g.

* `@stable(1.28)`
* `@unstable(draft, "message")`
* `@unstable(experimental, "message")`
* `@unstable(toBeDeprecated, "message")`

Pros:
* only 1 new attribute
* lends itself to a natural way to suppress all unstable warnings, or specific types

Cons:
* places meaning of the attribute in argument

### What if we had annotation that indicated the stability level?

E.g.

* `@stability(stable, 1.28)`
* `@stability(draft, "message")`
* `@stability(experimental, "message")`
* `@stability(toBeDeprecated, "message")`

Pros:
* 1 new attribute, but would likely replace `@unstable` that we have today, leaving net 0 new attributes
* single attribute name for indicating stability

Cons:
* places meaning of the attribute in argument

### What if we had different annotations for each stability level?

E.g.

* `@stable(1.28)`
* `@draft("message")`
* `@experimental("message")`
* `@toBeDeprecated("message")`

Pros:
* meaning of attribute is in the name

Cons:
* introduces 4 new attributes, although `@unstable` would likely be replaced, leaving net 3 new attributes

### What if we have stability attributes similar to Rust's?

E.g.

* `@stable(since=1.28)`
* `@unstable(category="draft", issue=12345, message="some explanation")`
* `@deprecated(since=1.29, note="no one liked this API" suggestion="use the other thing"`)

Note that the names in this proposal are placeholders, it's not decided if all these fields are required or which are required, and it's not decided if we should _require_ named arguments or just allow them.

Pros:
* brings `@deprecated` into stability discussion scope
* named args provide more information about stability
* allows for flexibility in how much/little information to place in an attribute

Cons:
* adds some complexity to attribute handling

[rust stability attributes](https://rustc-dev-guide.rust-lang.org/stability.html) for reference

## Proposal questions

* are we generally happy with the stated goals? Should other goals should be included, or the listed goals modified?
* any other pro/con items to add to each proposal?
* any specific use case you'd like to see an example of (based off changes in PR #21425?)

**Comment by e-kayrakli** [comment]
For Proposal 1: does this mean we'll have to put `@stable` on all methods/modules/etc that is not unstable? That's a very big con to me if that's the expectation.

**Comment by arezaii** [comment]
> does this mean we'll have to put @stable on all methods/modules/etc that is not unstable?

I don't believe that's the intention, rather, it would be an option to use `@stable` to indicate that we (or library devs) believe some API to be stable, and as such, it would serve to squash unstable warnings that bubble up from within.

**Comment by mppf** [comment]
> For Proposal 1: does this mean we'll have to put `@stable` on all methods/modules/etc that is not unstable? That's a very big con to me if that's the expectation.

See also #20911 where I argued that we should be able to indicate in which versions a function appeared and how it changed & I showed how that kind of information appears in the Python documentation. (And, even potentially allow the compiler to check that your code could work with a previous version of Chapel). My opinion is that we should be able to use attributes to convey this kind of information. Of course, we might wish to avoid marking things as "stable in version XYZ" or "added in version ABC" for the near future.

In any case, I think that in making decisions around the unstable attribute, we should be aware that we might wish to add this additional information.

**Comment by dlongnecke-cray** [comment]
I like proposal 3. Maybe we could have 3 categories, `stable`, `unstable`, and `deprecated`. I don't have discussions loaded in the mental cache but am not sure what `toBeDeprecated` means. It seems like that is just another way of saying `unstable`.

**Comment by lydia-duncan** [comment]
I think I prefer proposal 1 - while I appreciate being able to distinguish between different forms of unstable, it seems like it would also be beneficial to be able to handle them all at once.  In this scenario, I'd expect to be able to turn off all unstable warnings, or just the particular category of unstable warnings I care about.  I think such functionality is most naturally supported by proposal 1 or 2, though obviously it is still possible in proposal 3.

**Comment by arezaii** [comment]
> not sure what toBeDeprecated means.

I think `toBeDeprecated` is a place-holder for "we're going to remove this, but we don't know what to replace it with yet". All of these are potentially just another way to say "unstable", one of the goals is to increase the granularity in unstable messages to indicate the nature of the instability.

I am seeing limited support for any single proposal, with one person favoring 3, and what seems like two people favoring 1. I'm curious if @dlongnecke-cray would be OK with choosing proposal 1 over proposal 3.

**Comment by dlongnecke-cray** [comment]
If you're asking me if I can live with 1, then yes I can (grumpily), but I think at this point I'd much prefer proposal 3. Here are some more arguments as to why I think it might be better:

I think `toBeDeprecated` is a bit too much granularity. I don't think we need to say something is `toBeDeprecated` - if we need, we could have a string field named `replacement` or `alternative` or something. And if that is empty then it means the thing is deprecated without replacement.

IMO if we want to say something is `toBeDeprecated`, really that means we need to have more discussion and then decide to mark the thing as `deprecated`. We don't need to modify the code to reflect the status of our internal decision making across releases.

I checked out the Rust deprecation strategy and it seems like they only really have 3 categories. Something is `stable`, `unstable`, or `deprecated`. That was the basis for my suggestion, and it seems like the right balance.

What I noticed Rust does that we are not (or at least not talking about yet), is that you can shove a bunch more fields into a deprecation or unstable attribute. You can recommend a replacement, provide a "reason" for the deprecation, point to a public issue number, another URL, `since=1.29`, etc. I think those extra fields are what we need to give us our granularity, not more categories.

If we ignore `toBeDeprecated` and just look at the other forms, I think `@stability(deprecated` is a bit too verbose. Seems a bit more ergonomic to just use the actual states as the attribute names.

**Comment by dlongnecke-cray** [comment]
It has occurred to me that really my vote could be for either proposal 1 or proposal 3. I just think we should have 3 categories total: `@stable`, `@unstable`, and `@deprecated`. So arguably none of the proposals fit my wishlist (or both of them?).

I guess you could say that I'd take proposal 1, but drop the first argument (`experimental` / `draft` / etc) and add some different arguments instead.

**Comment by arezaii** [comment]
> I checked out the Rust deprecation strategy and it seems like they only really have 3 categories. Something is stable, unstable, or deprecated. That was the basis for my suggestion, and it seems like the right balance.

This makes me wonder if we could do something like the rust implementation. We could have the three categories you name and also provide named arguments to attributes. The named arguments would allow to express these and other attributes in a way that gives them clear meaning, and potentially points to an issue, or provides an alternate suggestion.

For reference, here's what our attributes could look like if we followed the rustacean path:

```chapel

@unstable(reason="we hope to improve the API", issue=12345)
proc foo(){}

@deprecated(since=1.29, note="it was a found to be redundant", suggestion="use M.baz")
proc bar() {}

@stable(since=1.30) 
proc baz() {}
```

Rust stability attributes also include a `feature` field which is used to prevent use of an unstable feature without explicitly opting in through the use of another attribute (named `feature`). It might look like:
```chapel
@unstable(reason="we hope to improve the API", issue=12345, feature="foo")
proc foo(){}

@feature("foo")
module M {
  foo();
}
```

I don't know if enabling `feature` to prevent the use of unstable items is something we want to explore enforcing in the compiler right now, but we could include some identifier like `feature` and use it to target `@unstable` items.

**Comment by mppf** [comment]
FWIW, in terms of improvements to the attribute syntax, I would much rather take named arguments with literals (a-la Rust as shown in the previous comment) than the adjustment to accept any Identifier (like Proposal 1 and Proposal 2 have).

Also, supposing we do want to distinguish 4 categories of stability, we can easily do that with named arguments that could be interpreted by the compiler / tools (or, if that is not necessary, use the string description to say it for humans). Here is an example using named arguments that could be interpreted by the compiler:
 * "stable": `@stable` (where at least we want an optional version)
 * "draft": `@unstable(category="draft")`
 * "experimental": `@unstable(category="experimental")`
 * "toBeDeprecated": `@unstable(category="to be deprecated")`;

This seems like a pretty robust strategy to me & it's the direction I think we should go. Note, I am not saying that we necessarily need all 3 categories of unstable -- that is a separate question. I'm just saying that, for as many categories of unstable that we need, it can fit into this framework. If we have no immediate need for categories that are machine readable, we can consider the category argument optional (or, put off adding support for it entirely, until such a need arises).

As far as - why have the different categories, I think that came from a remark I made earlier off-issue:

> I would imagine that users might want warnings when using one of the cases and not the others. If we end up in that situation, we'd want to distinguish them by more than just the `@unstable` string.

But, that is only a hypothetical at this point.

**Comment by arezaii** [comment]
> As far as - why have the different categories, I think that came from a remark I made earlier off-issue:
>> I would imagine that users might want warnings when using one of the cases and not the others. If we end up in that situation, we'd want to distinguish them by more than just the `@unstable` string.

Do you think this could be done by including the `feature` concept from rust, so that instead of ignoring whole categories of unstable, you ignore the warning using the specific list of `feature`s you intend to use in your module?

One concern I had about blanket suppression of unstable warnings by category is that you could inadvertently silence warnings that were added after you suppressed the whole category.

**Comment by lydia-duncan** [comment]
Proposal 4 looks good to me!

**Comment by bradcray** [comment]
I thought I'd said this here, but apparently it was only in other contexts.  I feel uncertain about `@stable`, in the sense that I wouldn't want to have to label everything as being stable, unstable, or deprecated.  I'd prefer for the lack of `@unstable` and `@deprecated` to imply `@stable`.  I think I've heard people say "Of course everything doesn't have to be labeled with these three things", but that leaves me uncertain when `@stable` would be useful / considered a best practice to apply.

**Comment by mppf** [comment]
@bradcray - AFAIK `@stable` in this discussion is motivated by having a similar capability to Python's docs where you can see in the documentation for a function which versions it was new or changed in. A simpler form of that would be to simply say, in which version of Chapel, something became stable. I think this is not particularly interesting today in our 2.0 push, because everything not marked unstable will (ideally) be stable in the 2.0 release (so the fine-grained information is not so useful). But, after that point, we will be adding functionality, and the documentation for this new functionality could reasonably indicate which Chapel version is required to use it. (See also #20911).

**Comment by arezaii** [comment]
In addition to what @mppf said above, when I was considering `@stable` I imagined two hypothetical scenarios:

1.) a library uses a standard module procedure internally that is labeled unstable, but the API of the library is considered stable by the author and the author doesn't want their users bothered by warnings they can't control. They can apply `@stable` to their procedure to prevent these warnings.

2.) some module contains lots of procedures, most of which are unstable. There are maybe one or two procedures that have been stabilized. The author can put `@stable` on those so that anyone who directly imports them would not be bothered by unstable warnings. Then they can put an unstable warning on the module and avoid having to put it on each of the unstable procedures individually. 

It's likely that both these use cases would require additional work in the compiler, but I thought I'd offer them here to see if either was something we'd like to support.

**Comment by arezaii** [comment]
since https://github.com/chapel-lang/chapel/pull/21425 was merged, I consider the initial proposal stage complete
