### ISSUE TITLE
A stance for `?` on partially instantiated / incomplete vs. complete types

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#21574]
Here's an attempt to capture in one place a series of related opinions w.r.t. making generic or incomplete type signatures clearer and more consistent, spanning multiple issues, such as #21572, #21455, #19120, #18665, #17122, #18214.  

* generic types whose generic fields are not fully defaulted should need to be written as `R(?)` rather than `R`
  e.g., given:
  ```chapel
  record R {
    type t;
  }
  ```
  I would need to write `var r: R(?)` and could not write `var r: R;`.  The rationale for this is that it makes the fact that the type is not completely specified self-evident in the code and prevents any misunderstanding that it is a concrete or fully specified type.
* partially instantiated generic types should require a `?` to indicate that they are not fully instantiated
  e.g., given:
  ```chapel
  record R {
    type t;
    param p;
  }
  ```
  I'd need to write:
  ```chapel
  var r: R(int, ?);
  ```
  rather than:
  ```chapel
  var r: R(int);
  ```
  Rationale: Similar to the previous bullet, this is a clear visual indicator that the type specification is not complete. and that other elements are missing.
* generic types whose generic fields are fully defaulted can be written as `R`
   e.g., given:
  ```chapel
  record R {
    type t = int;
  }
  ```
  I can write:
  ```chapel
  var r: R;
  ```
  rationale: Since `R` needs no more arguments to fully specify it, it can act as a concrete type and doesn't need to be distinguished from one.
* generic domain constraints should be written as `domain(?)` rather than `domain`.  Rationale: domains aren't fully defaulted, so this is just a case of bullet 1 above.
* array types should syntactically require an element expression rather than omitting it.  That is, rather than writing:
  ```chapel
  proc foo(x: [1..3]) { ... }
  ```
  I would need to write one of:
  ```chapel
  proc foo(x: [1..3] t) { ... }
  proc foo(x: [1...3] ?t) { ... }
  proc foo(x: [1..3] ?) { ... }
  ```
  Rationale: This helps distinguish an array type from an array literal and keeps the visual pattern of the signature complete, making it more obvious that something is missing.

**Comment by vasslitvinov** [comment]
Related: Michael's analysis of where we may not want `?`, ex. in `new` expressions: https://github.com/chapel-lang/chapel/issues/21455#issuecomment-1406632430
