### ISSUE TITLE
Chapel is not currently working on ATO (Attempt This Online)

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#21588]
For the past week+, Chapel has stopped working on ATO (Attempt this Online) after working quite well for the month previous.  This issue is here to note that we are aware of this for end-users.

I'm not currently certain what we could do to get it working again.  The behavior seems similar to what we saw when Chapel support was originally added, which was resolved in https://github.com/attempt-this-online/attempt-this-online/issues/110 by raising the memory limit.  In asking about it [here](https://chat.stackexchange.com/transcript/message/62932305#62932305), it sounded like the memory limit had since been removed altogether, which had caused a process to run away with all the memory and was attributed as being at fault.  Yet even after killing that process, things seem not to have returned to working again.  I've been quietly hoping that the next reboot / reinstall of ATO might just fix things, but...

**Comment by kwaters4** [comment]
@bradcray It looks like ATO is working again.

**Comment by bradcray** [comment]
Oh thank goodness!  I like it so much!

I'm closing this for now, but will try to remember to re-open it later if/when we notice it stops again.
