### ISSUE TITLE
Replace `string`/`bytes` standalone factory functions with type methods

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#21589]
This comes up in different contexts, but we haven't captured it.

- In the root issue where I proposed and added these functions, type methods didn't come up as an alternative: https://github.com/chapel-lang/chapel/issues/13818
- One of the most prominent places where this comes up is under https://github.com/chapel-lang/chapel/issues/14291.

We are in general agreement that the factory functions need not be type methods or standalone functions. Implementers can decide based on the specific of their case.

To me, `string`/`bytes` factory functions should be type methods. I feel strongly for this. My main reason is we want to promote generic programming between string and bytes. However, we have too many examples of things like the following in our standard/internal modules.

```chapel

if t==string then
  createStringWithNewBuffer(...);
else
  createBytesWithNewBuffer(...);
```

this pattern can much easily be implemented with

```chapel
t.createWithNewBuffer(...);
```

If we had factory functions that are type methods.

EDIT: Apparently, I have brought this up in the past but it got lost: https://github.com/chapel-lang/chapel/issues/14291#issuecomment-956497361

**Comment by bradcray** [comment]
> My main reason is we want to promote generic programming between string and bytes.

I think that's the best argument for a type method that I've heard in any of our discussions on the topic.

**Comment by mppf** [comment]
I'm supportive of this change, but I also think the current situation is OK (if we feel we cannot change it, for some reason).

I like that `string.createWithNewBuffer` leaves fewer symbols included by default from the standard library, but I acknowledge that it's not a big issue either way.

**Comment by lydia-duncan** [comment]
> * In the root issue where I proposed and added these functions, type methods didn't come up as an alternative

But it was brought up as a topic for discussion in the design re-review that occurred on Nov 1st, 2022, and type methods were mentioned there.  The result of that was recorded [here](https://github.com/Cray/chapel-private/issues/3921#issuecomment-1298957502) and in `notes/moduleReviews` in our internal notes repository

However, the generic programming point you've brought up is new, so it seems worth reconsidering on that grounds

**Comment by e-kayrakli** [comment]
Ah, thanks for finding that @lydia-duncan. I looked at [this one](https://github.com/Cray/chapel-private/issues/2410), but it didn't have the conclusion.

**Comment by bradcray** [comment]
I'm currently planning on skipping this subteam here, but am currently generally in favor of Engin's proposal due to the generic programming benefits it supports (where I think keeping generic code working as well as possible for strings vs. bytes is an importan goal).  Feel free to recruit me to the team if things stalemate or that position is losing and someone wants me to weigh in or consider the counterarguments.
