### ISSUE TITLE
Design of const C pointers

### ISSUE THREAD

**Issue by riftEmber** [chapel-lang/chapel#21597]
# Design of const C pointers

Ad-hoc subteam for Feb 21 - Mar 7 sprint. Members:
- Anna (driver)
- Brad
- Engin
- Michael

## Background

In [Should there be const pointer types for interoperability?](https://github.com/chapel-lang/chapel/issues/14214) there was support for adding a way to represent `const` C pointers[^1], as currently our `c_ptr` always corresponds to a non-`const` C pointer.

(For information about C pointers and interoperability in Chapel, see [C interoperability technote](https://chapel-lang.org/docs/technotes/extern.html) and [CTypes module](https://chapel-lang.org/docs/modules/standard/CTypes.html).)

### Motivation

- [Deprecate `c_string` type](https://github.com/chapel-lang/chapel/issues/14215) -- could instead use `c_constPtr(c_char)`.
- Represent a wider range of potential extern functions from C code, which may have const pointer arguments or return values. Currently const correctness is not preserved across the foreign function interface.

[^1]: Note this is in reference to pointers to const data (`const char *`), not const pointers to {mutable,const} data (`[const] char * const`). The latter is discussed beginning at [this comment](https://github.com/chapel-lang/chapel/issues/14214#issuecomment-538512373), but in any case is not in scope for this issue.

## Discussion issues

We need to decide how to represent a const C pointer, as well as how to get an instance of that representation. Here are the potential options for each:
- Representing a const C pointer
  1. Expand `c_ptr` to represent either const or non-const pointers, via a `param` flag for constness or some other mechanism.
  2. Have separate `c_ptr` and `c_constPtr` (name up for debate) types.
  3. Something else?
- Making a const C pointer
  1.  Allow creating both const and non-const pointers with `c_ptrTo` as proposed [here](https://github.com/chapel-lang/chapel/issues/14214#issuecomment-1382615125). While potentially convenient to read/write, as far as we could tell in discussion on that issue, this would require overloading based on argument intent, which Chapel [currently does not have](https://chapel-lang.org/docs/language/spec/procedures.html#better-argument-mapping).
  2. Have separate `c_ptrTo` and `c_ptrToConst` (name up for debate) functions.
  3. Something else?

Some additional questions:
- Should we add a const version of `c_void_ptr`? (interacts with  https://github.com/chapel-lang/chapel/issues/18011)
- What casting/conversions should we allow between these, and with `c_void_ptr`?
- Should we add a const version of `c_array`?
 
## Driver Straw Proposal

My **updated** proposal is to choose option (ii) for representation and (ii) for getting a pointer. This translates to:
- Non-const pointers are created with `c_ptrTo`, same as currently, and const pointers are created with a separate `c_ptrToConst` (this is my proposed name for this function as well).
- `c_ptrTo` returns a `c_ptr` and `c_ptrToConst` returns the new type `c_constPtr` (my proposed name) analogously.
- No code changes to `c_ptr` are required, but its documentation will make it explicit that it is a pointer to mutable data. `c_constPtr` has the same methods as `c_ptr` but preserves const correctness, e.g. `deref()` returns a chpl `const ref`.

Proposed answers to additional questions:
- Do not add a const `c_void_ptr` due to the implementation burden and potentially made moot by [supporting c_ptr(void)](https://github.com/chapel-lang/chapel/issues/18011).
- A `c_ptr` can be implicitly converted (or explicitly casted) to the more strict `c_constPtr`, but not vice-versa. `c_void_ptr` gains no new interactions -- one cannot cast `c_void_ptr` directly to `c_constPtr`, this would require one cast to add type and one to add constness.
- Do not add a const version of `c_array` to avoid implementation complexity -- users can make `c_constPtr`s to `c_ptr`s (or whatever other composition they desire) to achieve this.

<details>
<summary>Previous proposal</summary>

My proposal is to choose option (i) for representation and (ii) for getting a pointer. This translates to:
- Non-const pointers are created with `c_ptrTo`, same as currently, and const pointers are created with a separate `c_ptrToConst` (this is my proposed name for this function as well).
- `c_ptr` has a new `param bool constData` flag which is true for a const pointer. `c_ptrTo` returns a `c_ptr` with this flag set false, and `c_ptrToConst` returns a `c_ptr` with this flag true.
- Methods on `c_ptr` are adjusted to give const-correct values based on the `constData` flag. For example, `c_ptr.deref` currently returns a `ref`. It will be return-intent-overloaded so that if this is a `const` pointer, the method returns a `const ref`.

</details>

## Code examples
- Future https://github.com/chapel-lang/chapel/blob/main/test/extern/ferguson/externblock/struct-fn-ptr.chpl demonstrates that we are currently able to pass a const pointer argument to a non-const pointer formal without warning or error.
- Options (i) and (i):
   ```chapel
	const x : c_int = 5;
	var xp : c_ptr(c_int, constData=true) = c_ptrTo(x); // would require argument intent overloading
	xp.deref() = 3; // compilation error
  ```
- Options (i) and (ii):
   ```chapel
	const x : c_int = 5;
	var xp : c_ptr(c_int, constData=true) = c_ptrToConst(x);
	xp.deref() = 3; // compilation error
  ```
- Options (ii) and (i):
   ```chapel
	const x : c_int = 5;
	var xp : c_constPtr(c_int) = c_ptrTo(x); // would require argument intent overloading
	xp.deref() = 3; // compilation error
  ```
- Options (ii) and (ii):
   ```chapel
	const x : c_int = 5;
	var xp : c_constPtr(c_int) = c_ptrToConst(x);
	xp.deref() = 3; // compilation error
  ```

## Other languages
- Python
  - [ctypes](https://docs.python.org/3.11/library/ctypes.html) module -- No representation of const pointers. Only has `char`, `wchar`, and `void` pointer types.
- Rust
  - C types corresponding to Rust types defined in [libc crate](https://docs.rs/libc/0.2.139/libc/#types).
  - Specific representation of [CString](https://doc.rust-lang.org/std/ffi/struct.CString.html)s allows getting a `const char*` from a C-safe Rust representation of a string.
  - As far as I can tell, there is no representation of *specifically C's const pointers*. However [this page on pointers](https://doc.rust-lang.org/std/primitive.pointer.html#4-get-it-from-c) demonstrates that one can represent a const pointer directly in Rust, including one derived from external C code. This is something we do not want an equivalent of in Chapel for the time being as we do not expose Chapel pointers to the user.

**Comment by mppf** [comment]
I am expecting that we will adjust the compiler to support implicit conversion from `c_ptr(t)` to `c_ptr_const(t)` (whatever the names are). I think that behavior will be hard to describe and hard to implement if we represent constness with a `param` in `c_ptr` so I would lean against having separate names.

Is there an advantage to having a `param` field that the two names approach does not provide?

**Comment by riftEmber** [comment]
@mppf My inclination towards having a `param` was to avoid repetition in creating a second type that is almost identical to the current `c_ptr`; that's pretty much it. After coming up with some code examples yesterday I did notice it was pretty unwieldy and potentially less clear. I have some more due diligence to do today for a more informed opinion. Particularly, if it's difficult to implement different behavior based on the `param`, that would defeat a lot of the advantage for me.

**Comment by riftEmber** [comment]
## Preliminary closing comment
Note these decisions are pending input from @bradcray and resolution of any discussion arising therefrom, and are not yet ready for general team review.

### Meeting Notes
Engin took notes for our meeting today (2/23) [here](https://github.hpe.com/hpe/hpc-chapel-docs/blob/main/notes/moduleReviews/2023-02-23-c-ptr-const.md) (thanks!)

### Decisions for 2.0
- _Representing const C pointers_: Const C pointers will be represented by a new `c_ptrConst` type.
- _Creating const C pointers_: Const C pointers will be created via a new `c_ptrToConst` function or new `c_addrOfConst` function (following implementation of addrOf per https://github.com/chapel-lang/chapel/issues/18016), both of which will return a `c_ptrConst`.
- _Const c void pointers_: We will not add a const version of `c_void_ptr` for 2.0, nor is it scheduled post-2.0 (potential additive-only change).
- _Casting/conversions_:
  - Non-const pointers may be implicitly converted (or explicitly casted) to const pointers of the corresponding type. Const pointers may be explicitly casted, but not implicitly converted, to non-const pointers of the corresponding type.
  - `c_void_ptr` may be explicitly casted to a non-const (current behavior) or const C pointer. Vice versa, a const or non-const C pointer with a type may be explicitly casted to `c_void_ptr`. No implicit conversion behavior is added for `c_void_ptr`.
  - The issue of casting between pointers pointing to different types spawned a side discussion (see notes, grep `aliasing`). We recommend this behavior be made unstable for now.
    - As far as constness is concerned, if it is possible to cast from a `c_ptr` of one pointee type to `c_ptr` of another pointee type, then it will also be possible to cast from a `c_ptr` of one pointee type to a `c_ptrConst` of another pointee type, and vice versa.
- 	_Const `c_array`_: We will not add a const version of C array for 2.0, nor is it scheduled post-2.0 (potential additive-only change).

### Considerations not in original proposal
- See mention above of casting between `c_ptr`s of different pointee types. Anna will be making a separate issue for this and tracking it as a CTypes 2.0 issue.
- The `c_addrOf` function pending implementation (see https://github.com/chapel-lang/chapel/issues/18016) was not considered in the original proposal. We discussed it during the meeting and decided that it will remain unchanged, but a new `c_addrOfConst` function will be added which is just like `c_addrOf` but returns a `c_ptrConst` instead of `c_ptr`.
- While discussing the possibility of a const `c_array` analogous to `c_ptrConst`, we realized there is no way to set non-default values in a `const c_array` (that is using Chapel's `const`) except copy-initialization from another `c_array`. Refer to https://github.com/Cray/chapel-private/issues/4353 for `c_array` stabilization concerns.

### Notes/considerations
- We were not able to come up with any name scheme that any one of us was entirely happy with. We settled on the naming above as mutually least objectionable but do not have strong attachment to it and expect further discussion.

**Comment by riftEmber** [comment]
Re potential naming options, here is a little comparison of options we came up with during our meeting for easier review. The names of the existing `c_ptr` and `c_ptrTo` are implicated in this discussion for consistency, as well as of the [pending `c_addrOf` function](https://github.com/chapel-lang/chapel/issues/18016). In the below table, `-` denotes an existing symbol whose name is proposed unchanged.

<table>
<tr>
    <td>
	<td> Original straw proposal
	<td> Invert to `c_ptrConst` (currently weakly preferred)
	<td> "get" prefixes
	<td> Adopt C decl ordering
<tr>
	<td> Existing c pointer creator `c_ptrTo`
	<td> -
	<td> -
	<td> `c_getPtrTo`
	<td> -
<tr>
	<td> Existing c pointer type `c_ptr`
	<td> -
	<td> -
	<td> -
	<td> -
<tr>
	<td> Const pointer type
	<td> `c_constPtr`
	<td> `c_ptrConst`
	<td> `c_getPtrToConst`
	<td> `c_constPtr`
<tr>
	<td> Function to create const pointer
	<td> `c_ptrToConst`
	<td> `c_ptrToConst`
	<td> `c_getPtrToConst`
	<td> `c_constPtrTo`
<tr>
	<td> Const version of addrOf
	<td> n/a
	<td> `c_addrOfConst`
	<td> `c_getAddrOfConst`
	<td> `c_constAddrOf`
</table>

**Comment by mppf** [comment]
I have been thinking about the naming question a bit. The thing I am asking myself is, why do we need or want two names? Today for regular C pointers, we have `c_ptrTo(x)` to get a pointer value and `c_ptr(int)` to get a pointer type. But, in Chapel we can have overloaded functions, so we could arrange for `c_ptrTo(x)` to get a pointer value and `c_ptrTo(int)` to get a pointer type. The implication would be that we could use `c_ptrToConst` (which IMO is our best name option) for both the value (`c_ptrToConst(x)`) and the type (`c_ptrToConst(int)`).

Why do we have two names at all? I think the reason for it is that we are implementing C pointers with a `class c_ptr` with a bunch of special pragmas. But at that point it's pretty much "compiler magic" and the fact that we can't have the same class name as a function name seems neither here nor there. In practice, if we go with `c_ptrTo(int)` to name the type, we could rename this class to some internal name and adjust the compiler's printing of types to print out things like `c_ptrTo(int)`. Or, of course, we could move away from having it be implemented as a class at all.

**Comment by bradcray** [comment]
[with the caveat that I'm not completely caught up on this thread, but Michael's latest comment caught my eye]:

For me, the arguments against expressing the type as `c_ptrTo(int)` are:

* both `c_ptrTo()` and `c_addrOf()` will return values of this type, so linking the type name more strongly to one of the queries than the others seems unnecessarily asymmetrical
* makes a short type name even longer (where I expect C programmers may already bristle at having to type more than `*`
* requires changes to existing code and deprecations that otherwise wouldn't be necessary

**Comment by bradcray** [comment]
OK, now that I'm caught up, I'm going to walk back my comments slightly, but with the admission that I'm a bit uncertain:
* of the four columns of proposals, I like the weakly preferred solution the best
* my main reaction to that column was "it seems like the type name for the const case should be called `c_ptrToConst()` which I now better understand to have been the likely motivation for Michael's previous comment, and I don't feel opposed to using the same name for both the type and the routine
* but I still feel resistant to changing `c_ptr(int)` to `c_ptrTo(int)`, but am not sure it's well-founded and may just be a case of having lived with the old world too long
  * I still think that the asymmetry with `c_addrOf()`, `c_addrOfConst()` is unfortunate, but I prefer the name `c_ptrToConst(int)` enough to not let that me stop me in that case; so maybe it shouldn't for `c_ptrTo(int)` either?
  * I still think making it a longer name is unfortunate
  * I still think the need to make changes will be annoying
  * but maybe the symmetry between the pointer-to-const and pointer-to-non-const cases is strong enough to outweigh those reservations?

**Comment by riftEmber** [comment]
## Closing comment

The subteam met a second and final time this morning (Mar 2) with all members and have settled all remaining questions. 

Our discussion particularly covered the potential naming schemes in more detail today, including the comments on this thread that occurred between the two meetings. This topic was eventually settled with Anna and Engin in favor of the weakly preferred naming scheme, while Michael and Brad were okay with either that or the original naming scheme and did not have a strong preference between the two.

We have received no input from the wider Chapel team since sharing this issue out, and interpret that as no objection to our proposed direction.

### Decisions
All decisions from the [above "current direction" comment](https://github.com/chapel-lang/chapel/issues/21597#issuecomment-1442467536) stand unaltered, including using our weakly preferred naming scheme from the table in [this comment](https://github.com/chapel-lang/chapel/issues/21597#issuecomment-1444174173). 

### Implementation

After implementation, creating a const pointer will look like the following:
```chapel
 const x : c_int = 5;
 var xp : c_ptrConst(c_int) = c_ptrToConst(x);
```

Anna will begin implementation of the decisions this sprint, as time allows.

∎
