### ISSUE TITLE
IO Serializers Meta-Issue

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#21624]
This is the meta-issue collecting the various related issues to the design of the "Encoders and Decoders" feature set of the standard IO module.

The initial prototype PR: https://github.com/chapel-lang/chapel/pull/21586

Interfaces:
- Encoder interface and 'encodeTo' method: https://github.com/chapel-lang/chapel/issues/21625
- Decoder interface, 'decodeFrom', and reader-initializers: https://github.com/chapel-lang/chapel/issues/21626
- Naming of Encoders and Decoders: https://github.com/chapel-lang/chapel/issues/21627
- channel methods in support of Encoders/Decoders: https://github.com/chapel-lang/chapel/issues/21628

Migrating old code to new features:
- How should 'readThis' and 'writeThis' interact with Encoders and Decoders initially? : https://github.com/chapel-lang/chapel/issues/21629

Miscellaneous:
- https://github.com/chapel-lang/chapel/issues/21942
- https://github.com/chapel-lang/chapel/issues/22588

Binary IO:
- https://github.com/chapel-lang/chapel/issues/21996
- https://github.com/chapel-lang/chapel/issues/21997

Future work:
- Binary IO
- Formatter interface for arrays, maps, and/or general collections
- Interaction with "%t" format specifier
- _more to come..._

Historical:
- Original design proposal: https://github.com/chapel-lang/chapel/issues/18499
- Relationship between Encoder/Decoder and channel (still possibly relevant?): https://github.com/chapel-lang/chapel/issues/18504

**Comment by lydia-duncan** [comment]
Okay to close this issue?

**Comment by benharsh** [comment]
I've gone through and closed the other issues mentioned here after confirming they have been settled elsewhere.
