### ISSUE TITLE
IO Decoder interface

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#21626]
Decoders are expected to be records that implement the following methods:

```chpl
proc decode(reader: fileReader, type readType) : readType throws

proc readField(reader: fileReader, name: string, type T) : void throws

proc readTypeStart(reader: fileReader, type T) throws

proc readTypeEnd(reader: fileReader, type T) throws
```

At this time, the formal names are unspecified.

Decoders that can be default-initialized can be used with the version
of ``fileReader.withFormatter`` method that accepts a type, rather than a
value.

Decoders have the option of initializing a type with a "reader
initializer", which accepts a ``fileReader`` as an argument. For example,
given a type ``readType``:

```chpl
proc decode(reader: fileReader, type readType) where isRecord(readType) {
  return new readType(reader);
}
```

These reader initializers might be user-defined, or might be generated by the
compiler. Generic types will have type and param arguments for the reader
initializer that preceed the ``fileReader`` argument in the initializer
signature. The compiler is expected to generate these reader-initializers
for records and classes, provided that none of the fields are fully or
partially generic (e.g. "var x;", or "var x : integral;"). The bodies of these
initializers will roughly match the following pseudocode:

```
proc MyType.init(r: fileReader) {
  ref fmt = r.formatter;
  fmt.readTypeStart(r, MyType);
  <call super.init(r) if applicable>
  for each field:
    this.field = fmt.readField(r, field_name, field_type);
  fmt.readTypeEnd(r, MyType);
}
```

Note that in order to handle inheritance, Decoders will need to manage some
internal state in order to track the current "position" within a type.

Decoders may also attempt to invoke the type method 'decodeFrom',
which allows user-defined types to initialize a type in some other way
that might not involve an initializer (e.g. for extern types). 'decodeFrom'
is not generated by the compiler by default. The 'decodeFrom' type method
may be invoked with a ``fileReader``:

```chpl
  proc type MyType.decodeFrom(reader: fileReader) throws
```

**Comment by mppf** [comment]
Question for discussion: should the reader-initializers use named argument passing, so that e.g. `proc MyType.init(decodeFrom: fileReader)` is considered a reader-initializer but `proc MyType.init(x)` is not?
