### ISSUE TITLE
IO Encoders and Decoders naming/terminology

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#21627]
The feature currently known as "Encoders and Decoders" was proposed some time ago. Do we want to stick with these names? The terms "encode" and "decode" might be more strongly related to certain kinds of IO operations in users' minds rather than general behavior.

Some alternative names, or terms:
- Formatters, FormatReaders, FormatWriters
- from python: pickle and unpickle
- serialize and deserialize
- Swift has a "Codable" interface, which represents both Encodable and Decodable

**Comment by mppf** [comment]
> The terms "encode" and "decode" might be more strongly related to certain kinds of IO operations in users' minds rather than general behavior.

in particular, in the context of I/O, people might think of character set encodings (UTF-8, UTF-32, EBCDIC) etc.

I think one challenge with the terminology is that we need both noun and verb forms in both directions:
 * encoder ; encode
 * decoder ; decode

That leads to the main uncertainty I have with "formatter" as the terminology:
 * FormatWriter / formatter ; writeFormatted? / format?
 * FormatReader / unformatter ; readFormatted? / unformat?

**Comment by lydia-duncan** [comment]
The IO subteam did some brainstorming on potential alternate names, here they are

[2023-03-01-encoder-name-brainstorm.xlsx](https://github.com/chapel-lang/chapel/files/10865659/2023-03-01-encoder-name-brainstorm.xlsx)
