### ISSUE TITLE
IO Serializers interaction with readThis/writeThis?

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#21629]
As this feature comes online, how should Serializers and Deserializers interact with the long-existing ``readThis`` and ``writeThis`` methods available in many existing programs?

**Comment by mppf** [comment]
To outline some options:
 1. we could deprecate `readThis` and `writeThis` and ask for people to write the new forms (reader initializer / decodeFrom & encodeTo -- names TBD)
 2. we could have a transition period where the readThis / writeThis are automatically used during encoding/decoding, one way or another, but warn; and then in a future release insist on 1.
 3. we could automatically use readThis / writeThis during encoding/decoding for the long term
 4. we could decide that readThis / writeThis and the encoder/decoder support methods have different use cases and support both indefinately

**Comment by lydia-duncan** [comment]
I'm pretty against 4 and would probably lean towards 1 given the choice, but am not strongly opposed to the other options
