### ISSUE TITLE
Unclear semantics of Promotion in spec

### ISSUE THREAD

**Issue by jabraham17** [chapel-lang/chapel#21649]
Given the following code, my intuition is that "IN INIT" should be called three times.
```chapel
class Stack {
  proc init() {
    writeln("In INIT");
  }
}
var stacks: [1..3] owned Stack = new Stack();
```
However the above does not compile with error 'const actual is passed to 'ref' formal 'src' of init=()'. From discussions with @bmcdonald3, I understand the above code to be attempting to fill the array with references to the same Stack object.

To get this to give my expected output requires changing the last line to
```chapel
var stacks: [1..3] owned Stack = [1..3] new Stack();
```

To my understanding, this does not match the spec

> If the original function returns a value or a reference, the corresponding promoted expression is an iterator yielding each computed value or reference.

Is this something missing from the spec that needs to be added or is this unexpected behavior?

**Comment by bmcdonald3** [comment]
Noting this is very similar to what I previously ran into in https://github.com/Cray/chapel-private/issues/3681#issuecomment-1230440328, where I was seeing an array of unmanaged classes only referring to a single object, which was confusing to me, something like:
```
var myArr: [0..2] unmanaged MyClass = new unmanaged MyClass();
```
So, I didn't get an error like Jade ran into here, but all 3 instances of the array referred to the same object, which was confusing to me.

**Comment by lydia-duncan** [comment]
What happens if you make it a record?

**Comment by jabraham17** [comment]
Making it a `record` gives similar behavior, without the error. 

In the first case, relying on promotion, "In INIT" is printed once.
```chapel
var stacks: [1..3] Stack = new Stack();
// prints once
```

In the second case, explicitly expanding to an array operation, "In INIT" is printed three times.
```chapel
var stacks: [1..3] Stack = [1..3] new Stack();
// prints three times
```

**Comment by bradcray** [comment]
I think this behavior is correct, in that I think that `myArray = myElem;` is equivalent to promoting:

```chapel
operator =(ref lhs:myElemType, rhs: myElemType);
```

which would be equivalent to:

```chapel
forall lhs in myArray do
  lhs = myElem;
```

Specifically, if I said `myArray = computeRandomNumber();` there should only be one call to computeRandomNumber(), not one per array element.  In the example in the OP only one new owned class is created, but it can't be assigned to three things because that would be three ownership transfers.

The quoted section of the spec looks to me not to apply here because I think what it is describing is that in a case like:

```chapel
proc inc(x) { return x + 1; }
```

the expression `inc(myArray)` will act like an iterator yielding the returned values (so `[a in myArray] inc(a)`).  But since `=` doesn't return anything, that clause doesn't apply.

None of this is to say that the spec couldn't make something clearer, though.

**Comment by mppf** [comment]
FWIW, we discussed this behavior in #7904. As I noted at the end of that issue:

> It appears that this decision isn't recorded in the language specification https://chapel-lang.org/docs/language/spec/data-parallelism.html#promotion . I think that section should be updated to say something about nested call expressions.

I think improvements to the spec in this area would be very welcome.

**Comment by lydia-duncan** [comment]
Minor correction, but I think `init` is being called once and `init=` is being called three times, not `=` (based on the error message).

**Comment by jabraham17** [comment]
> Specifically, if I said `myArray = computeRandomNumber();` there should only be one call to computeRandomNumber(), not one per array element

Based on this, would it be fair to equate this case to
```chapel
var tmp = computeRandomNumber();
myArray = tmp;
```

In #7904, the semantics differ as the default argument function is called multiple times. If I understand correctly, it is the difference between operator promotion and function promotion?

```chapel
myArray = foo(); // operator promotion, eval once and promote assignment
bar(myArray);  // function promotion, promote function
```

If the above is a good interpretation, I will draft an update to the spec to attempt to make it more clear.

**Comment by bradcray** [comment]
> Based on this, would it be fair to equate this case to

For this example, yes.  Note the similar comment on https://github.com/chapel-lang/chapel/issues/7904#issuecomment-531863465 (I'm glad to find I'm consistent in this regard!)

> If I understand correctly, it is the difference between operator promotion and function promotion?

I don't think that's right.  Specifically, I don't think we want operator and procedure promotion to behave differently.  And my takeaway from #7904 is that we ended up deciding it was appropriate to only call the function `makeIt()` once despite calling `foo()` multiple times, which seems to be what happens as of Chapel 1.29:  https://ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuhY3-wuK8pMVchOzUzNLNDQVqrkUFMqLMktSc_I0lDz9oBJKmtZA8aLUktKiPAVDa65aLi6wtrT8fI0Kq8y8Eh2FShAF0Q9VV6FdCVZZllik4KhgqxBtqGOkY6xjomOqY6ZjrmOhYxlrzQUywVEHbr-mNcRZUNfBXAkA

In your pair of examples:

```chapel
myArray = foo(); // operator promotion, eval once and promote assignment
bar(myArray);  // function promotion, promote function
```

I'd say that the first is (effectively) rewritten to:
```chapel
var tmp = foo();  // assuming foo() is myArray's element type, it is not promoting the operator, so only call it once
forall a in myArray do
  a = tmp;
```

and the second is being rewritten to:

```chapel
forall a in myArray do
  bar(a);
```

The more interesting case would be:

```chapel
baz(myArray, foo());
```

which, based on the #7904 conclusion would get rewritten as:

```chapel
var tmp = foo();
forall a in myArray do
  baz(a, tmp);
```

(again, assuming that foo()'s return type matched the second argument of baz() exactly).

So, summarizing, I'd say the behavior is:
* compare all arguments sorting them into two categories:
  * those that match the formal—these will not cause promotion, so evaluate them once
  * those that are a collection (array, iterator expression) whose element type matches the formal—these will cause promotion, so will part of the (zippered) loop that calls the promoted array.

**Comment by jabraham17** [comment]
> I'd say that the first is (effectively) rewritten to:
> ```chapel
> var tmp = foo();  // assuming foo() is myArray's element type, it is not promoting the operator, so only call it once
> forall a in myArray do
>   a = tmp;
> ```
>   
> and the second is being rewritten to:
> ```chapel
> forall a in myArray do
>   bar(a);
> ```

This makes significantly more sense to me. I think these code samples are very helpful in understanding the promotion and should be included in the documentation.

One thing that is still confusing to me is the default arguments. Based upon the documentation and #7904, I would expect "IN makeit" to print multiple times in the following example.
```chapel
proc makeit():int {
  writeln("IN makeit");
  return 1;
}
proc foo(y:int = makeit()) {
  return 2+y;
}
foo();
```
However it only prints once. This contradicts (the documentation)[https://chapel-lang.org/docs/language/spec/data-parallelism.html#default-arguments], which says "the default argument expression can be evaluated many times" and provides a code sample which DOES print multiple times for a default argument.

---

As a side note to the above confusion on default arguments: while exploring this issue I wrote the following code which fails to compile with an internal error
```chapel
proc makeit():int {
  writeln("IN makeit");
  return 1;
}
proc foo(x:int, y:int = makeit()) {
  return x+y;
}
var A = [1,2,3,4,5,6,7,8,9];
foo(A, makeit()); // successfully calls foo and prints makeit once
foo(A); // internal error: number of actuals (1) does not match number of formals (2) in foo() [resolution/resolveFunction.cpp:1332]
```
I don't see why this should not compile and if it should not compile it should have a nicer user facing error.

**Comment by lydia-duncan** [comment]
> One thing that is still confusing to me is the default arguments. Based upon the documentation and #7904, I would expect "IN makeit" to print multiple times in the following example.
> 
> ```chapel
> proc makeit():int {
>   writeln("IN makeit");
>   return 1;
> }
> proc foo(y:int = makeit()) {
>   return 2+y;
> }
> foo();
> ```

This example looks serial to me and I would expect it to print once.  Is there a typo?

**Comment by lydia-duncan** [comment]
Your final example does seem like it should compile

**Comment by bradcray** [comment]
> This example looks serial to me and I would expect it to print once. Is there a typo?

I agree, though I'd describe it as "nothing is promoting foo(), so this is just a normal procedure call" rather than bringing serial/parallel into the mix.  If you add an argument `x: int` and pass it an array of `int` and you didn't get multiple calls, that would be the contradiction.  But I guess that's the case where you're getting an internal error (and I agree with you and Lydia that you should not).

**Comment by jabraham17** [comment]
> Is there a typo?

Yes. This was a reduced example of my final example which doesn't compile and it's behavior surprised me. I see now I reduced the test case so much I removed the promotion, we can disregard this.

**Comment by jabraham17** [comment]
Sounds like the example which doesn't compile is a genuine bug, I will create a separate issue for it and link it here for completeness.

**Comment by bradcray** [comment]
I was surprised that this bug wasn't familiar, and then thought it did seem vaguely familiar, but couldn't find an existing issue for it with a quick check.  You might double-check me on that before proceeding.  It'd be great to file a future test against this with the issue.  My mildly optimistic reaction is that dyno will just make that test start passing as it takes over resolution.

**Comment by jabraham17** [comment]
There is a similar issue, #11225, which deals with promotion and named arguments.  It's a different assertion being triggered and seems to be caused by something else.

**Comment by bradcray** [comment]
I'm also not seeing a `.bad` file with that error, which makes it seem unlikely that we already have a future covering it (and therefore less likely that there's an issue for it... though not all issues have futures even when they should).

**Comment by jabraham17** [comment]
On closer inspection, I have a smaller reproducer that looks even less like the previously mentioned issue.

```chapel
config param which = 1;

proc foo(x:int, y:int = 7) {
  return x+y;
}
var A = [1,2,3,4,5,6,7,8,9];

if which == 1 {
  foo(A);
}
else if which == 2{
  var x = foo(A);
}
else if which == 3 {
  var x = foo(A);
  foo(A);
}
else if which == 4 {
  foo(7);
}
```

The first test, `which == 1`, fails with an internal compiler assertion (from resolution/resolveFunction.cpp:1332). All others compile as expected. So this is being triggered by the edge case when a function with a default argument is promoted AND the result is unused. But if the function is called capturing the result and then the function is used again where the result is unused the compiler accepts it as valid (test case `which == 3`). Presumably this is because it has already resolved the function, although I am just speculating

**Comment by bradcray** [comment]
Fascinating...  I never would've guessed that lack of using the return value would've been a contributing factor to the internal error, not that the earlier call that used it would fix things.

Tagging @mppf on this, not to stress him out in any way, but just because I know he's been working on resolution in dyno and it seems likely that the dyno resolver would just get this right from the start as it comes online (if it hasn't already :) ).

**Comment by bradcray** [comment]
@jabraham17 : I just happened to stumble across this issue while looking for another one and was curious whether the docs improvements you've made feel as though they're sufficient to close this or if more is needed?  (and if "more", what more that might be).  Thanks!

**Comment by jabraham17** [comment]
I mostly kept this open because of the subsequent errors I found. I think we have resolved my concerns regarding the documentation so I would be ok with closing this, but I would want to capture the bugs listed as separate issues.

**Comment by bradcray** [comment]
Ah, OK, I may have been reading too fast then—I thought it had said you already had.

**Comment by jabraham17** [comment]
I have opened #22573 to capture the bug described here, this can be closed now
