### ISSUE TITLE
labeled continue within a coforall within the labeled loop causes compiler crash: pure virtual method call

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#21651]
### Steps to Reproduce

**Source Code:**

```chapel
label outerer for qq in 1..3 do {

coforall loc in Locales[0..0] do on loc {
  coforall tid in 0..<1 {
    var j = 0;
    label outer while j < 10 {
      var i = 1;
      do {
        writeln((i, j));
        if i == 3 then
          continue outerer;
        i += 1;
        j += 1;
      } while (i < 100);
    }
  }
}

}
```

**Compile command:**

```
fortytwo@enodia:~/src/chapel (main)$ chpl llwnc.chpl
pure virtual method called
terminate called without an active exception
Aborted (core dumped)
```

This is a slightly modified version of @bradcray's test in #21635 :

```diff
fortytwo@enodia:~/src/chapel (main)$ diff -u test/statements/loops/labeledLoopWithinNestedCoforall2.chpl llwnc.chpl
--- test/statements/loops/labeledLoopWithinNestedCoforall2.chpl 2023-02-21 17:01:14.165715491 -0800
+++ llwnc.chpl  2023-02-21 17:17:47.222764388 -0800
@@ -1,3 +1,5 @@
+label outerer for qq in 1..3 do {
+
 coforall loc in Locales[0..0] do on loc {
   coforall tid in 0..<1 {
     var j = 0;
@@ -6,10 +8,12 @@
       do {
         writeln((i, j));
         if i == 3 then
-          continue outer;
+          continue outerer;
         i += 1;
         j += 1;
       } while (i < 100);
     }
   }
 }
+
+}
```

The same thing happens with a labeled `break` .

I expect this should be a compilation error as is produced for a return statement in that same location (when the whole thing is in a `proc`).

**Associated Future Test(s):**
[`test/statements/loops/labeledLoopBreakWithoutNestedCoforall.chpl`](
           https://github.com/chapel-lang/chapel/blob/main/test/statements/loops/labeledLoopBreakWithoutNestedCoforall.chpl
          ) #21666 
[`test/statements/loops/labeledLoopBreakWithoutOnStatement.chpl`](
           https://github.com/chapel-lang/chapel/blob/main/test/statements/loops/labeledLoopBreakWithoutOnStatement.chpl
          ) #21666 
[`test/statements/loops/labeledLoopContinueWithoutNestedCoforall.chpl`](
           https://github.com/chapel-lang/chapel/blob/main/test/statements/loops/labeledLoopContinueWithoutNestedCoforall.chpl
          ) #21666
[`test/statements/loops/labeledLoopContinueWithoutOnStatement.chpl`](
           https://github.com/chapel-lang/chapel/blob/main/test/statements/loops/labeledLoopContinueWithoutOnStatement.chpl
          ) #21666

### Configuration Information

```
chpl version 1.30.0 pre-release (a88a9508ff)
  built with LLVM version 14.0.0

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: none
CHPL_LLVM: system
CHPL_AUX_FILESYS: none

gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

Ubuntu clang version 14.0.0-1ubuntu1
```

**Comment by cassella** [comment]
With `--verify`, both forms report a more useful error:

```
llwnc.chpl:1: In function 'foo':
llwnc.chpl:13: internal error: goto label is in a different function than the goto [AST/stmt.cpp:1126]
```

I can write a future for that.

**Comment by DanilaFe** [comment]
PR #21664 seems to resolve this issue (no more internal errors are issued).

**Comment by cassella** [comment]
Heh, funny how that works.  :smile:  Thanks!
