### ISSUE TITLE
Apparent memory leak when launching GPU kernels

### ISSUE THREAD

**Issue by stonea** [chapel-lang/chapel#21689]
Based off this review comment https://github.com/chapel-lang/chapel/pull/21644#discussion_r1116231931 from @DanilaFe I think we have a memory leak with `was_memory_dynamically_allocated_for_kernel_param`.

See: https://github.com/chapel-lang/chapel/blob/main/runtime/src/gpu/cuda/gpu-cuda.c#L216

When updating this also check the AMD version of the runtime for the same issue.

**Comment by stonea** [comment]
I have a draft PR for this here: https://github.com/chapel-lang/chapel/pull/22592

**Comment by e-kayrakli** [comment]
@stonea -- It looks like the PR was in a good shape last time we looked at it. Are you considering rebasing at merging it soon?

**Comment by stonea** [comment]
Yep, it's merged now: https://github.com/chapel-lang/chapel/pull/22592
