### ISSUE TITLE
Strange error message, but no meaningfull ones

### ISSUE THREAD

**Issue by PGDataHome** [chapel-lang/chapel#21710]
### Summary of Problem
What behavior did you observe when encountering this issue?
Strange messages error

What behavior did you expect to observe?
More meaningfull error message

Is this a blocking issue with no known work-arounds?
Not a blocking issue

### Steps to Reproduce

**Source Code:**
```chapel
module my_freader {
use IO;
    class P {
            var size: int = 0;
            var buffer : [] bytes;

            proc init() {
                    var f = open("freader.chpl",ioMode.r);
                    var ch = f.reader();

                    size = f.size;
                    buffer = new bytes[size];

                    ch.read( buffer, size );

                    writeln( buffer:string, size );
            }

    }

    proc main() {
            var p: P;
    }
}
```

```bash
my_freader.chpl:6: error: unresolved call 'chpl__buildArrayRuntimeType(nil, type bytes)'
$CHPL_HOME/modules/internal/ChapelArray.chpl:222: note: this candidate did not match: chpl__buildArrayRuntimeType(dom: domain, type eltType)
my_freader.chpl:6: note: because actual argument #1 with type 'nil'
$CHPL_HOME/modules/internal/ChapelArray.chpl:222: note: is passed to formal 'dom: _domain'
```

**Compile command:**
chpl my_freader.chpl

**Execution command:**
./my_freader

### Configuration Information

- Output of `chpl --version`:
chpl version 1.30.0 pre-release (7992bd3e51)
  built with LLVM version 14.0.6
Copyright 2020-2023 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: system
CHPL_AUX_FILESYS: none

- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
- (For Cray systems only) Output of `module list`:

**Comment by bradcray** [comment]
@dlongnecke-cray : With Chapel 1.29.0, I'm getting a syntax error on the field `var buffer : [] bytes;` which is slightly better than the error message reported here, making me think that your #21584 (which I'm a big fan of) may have made the error message more confusing here.  Would it be possible/easy to drop some sort of post-process-check into the compiler to catch this case and say something like "Variables/fields of array type must be defined over a domain expression" or the like?

**Comment by dlongnecke-cray** [comment]
I've opened https://github.com/chapel-lang/chapel/pull/21720 which improves coverage of my initial checks for array types, and special cases the message for something like `var x: [] bytes`.

**Comment by bradcray** [comment]
Awesome, thanks for the quick response here, David!  (and for bringing this to our attention and filing it, @PGDataHome!)

**Comment by dlongnecke-cray** [comment]
The PR I just merged will improve the error message so you're not seeing something arcane. As Brad and I discussed, at a future point we'll improve the error message so that you understand it's the lack of domain expression which is potentially the problem.

Thanks for filing this bug!
