### ISSUE TITLE
Create linter for standard module naming

### ISSUE THREAD

**Issue by DanilaFe** [chapel-lang/chapel#21864]
It would be nice to have a Dyno-based linter that can detect improper naming in module code (e.g., if someone added a function called `MyFunction` instead of calling it `myFunction`). The standard library has exceptions, so it might be useful to have an exception mechanism. This could possibly be accomplished via tool-namespaced attributes, for example:

```Chapel
@chplcheck.permitEnumsInitialCaps()
enum myEnum {
  IStartWithACaptialLetter
}
```

Jade writes:
> Perhaps something akin to the Python PEP philosophy. The linter has a series of rules it applies and for each rule it applies, there is an attribute to change the default

We'd want at least the following constraints on this new linter:
* not applying it to private/no doc symbols
* not applying to OS or OS.POSIX

**Comment by bradcray** [comment]
This is a nit, but I think the title here should be about "standard module naming" in that the internal modules aren't intended to be user-facing (other than by implementing the language), so aren't really subject to these questions.

Another easy restriction here would be to only focus on user-facing symbols and names in the standard modules:  Like if an implementer wanted to use a different naming scheme for their local variables or private declarations, that would be nice to have the tool look past without requiring annotations.

**Comment by jabraham17** [comment]
I would also add another similar tool to this for C/C++, clang-format, which is a little less strict than Python PEP.

PEP takes the approach of "there is one way and only one way"

clang-format has different default styles that apply a series of formatting rules, but those styles can be tweaked. And within the code, the style can be ignore with a comment `// clang-format off`. clang-format is a blind formatting tool that doesn't do as much work as a proper linter might, but it does provide good defaults with flexibility.

**Comment by DanilaFe** [comment]
The `chplcheck.py` script in https://github.com/chapel-lang/chapel/pull/23489 can do this and more.

**Comment by jabraham17** [comment]
[`chplcheck`](https://chapel-lang.org/docs/tools/chplcheck/chplcheck.html) fully implements this request, and more
