### ISSUE TITLE
Should timedelta be camelcase?

### ISSUE THREAD

**Issue by bmcdonald3** [chapel-lang/chapel#21863]
While looking into the usage of `timeSinceEpoch()` for the `Time` module stabilization, the team noticed that `timedelta` is all lowercase, where camelcase would be in line with our style guides.

It was also suggested that we should double check the rest of this module to make sure that the naming is in line with the 2.0 style guides.

**Comment by bradcray** [comment]
My instinct here is that it should be `timeDelta`, but Michael's mention of `datetime` as a case that we may have intentionally left as-is to ... [match Python | reflect someone's preferred style | something] makes me want to check the notes to see whether we discussed this.

[checks notes]

Having checked the notes, I'm not seeing any indication that we discussed it, and am also seeing this about `datetime`:

> maybe datetime can stay instead of dateTime
>   * w/ the module name as DateTime it would be good to do dateTime

Then going to look for issues, I'm seeing this issue that reviews casing:  https://github.com/Cray/chapel-private/issues/2750 and which includes:

> `record datetime` → `dateTime`

**Comment by mppf** [comment]
The camel case oddities I'm aware of here are `timedelta` `datetime` and `tzname`.

**Comment by daviditen** [comment]
The Time module stabilization subteam reached consensus that we should make the following changes to make this module match the [style guide](https://chapel-lang.org/docs/developer/bestPractices/StandardModuleStyle.html):

```
timedelta -> timeDelta
datetime -> dateTime
enum Day -> enum day
datetime.getdate -> dateTime.getDate
datetime.gettime -> dateTime.getTime
tzname -> mark unstable
```
