### ISSUE TITLE
Compile-time error when using extern C function with `CHPL_LOCALE_MODEL=gpu`

### ISSUE THREAD

**Issue by Guillaume-Helbecque** [chapel-lang/chapel#21905]
### Summary of Problem
When compiling a Chapel program in which an external C function is declared, used, and correctly linked, I get the following error:
```chapel
/opt/apps/resif/iris-rhel8/2020b/gpu/software/binutils/2.35-GCCcore-10.2.0/bin/ld: /tmp/chpl-ghelbecque.deleteme-RveJuA/chpl__module.o: in function `chpl_gen_main':
root:(.text+0x5c490): undefined reference to `hello_world()'
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
error: Make Binary - Linking
```
This happens using the environment below, targeting GPUs (`CHPL_LOCALE_MODEL=gpu`). I know that the use of most extern functions within a GPU eligible loop is not supported, but there is no GPU features (`here.gpus`) in this toy-code. Moreover, this code works fine setting the default value of `CHPL_LOCALE_MODEL` and LLVM enabled.

Did I miss something or is this a bug ?

(In practice, there is no point in using `CHPL_LOCALE_MODEL=gpu` if there is no GPU functionality in the code, but this report simply reproduces an error I had in a more complex case.)

### Steps to Reproduce

**Source Code:**
Assume that we have the following files in the same directory:

`extern_c_test.h`:
```c
#ifndef __EXTERN_C_TEST_H_
#define __EXTERN_C_TEST_H_

void hello_world(void);

#endif
```
`extern_c_test.c`:
```c
#include <stdio.h>
#include "./extern_c_test.h"

void hello_world()
{
  printf("hello world from C");
}
```
`main.chpl`:
```chapel
module extern_c
{
  require "extern_c_test.c", "extern_c_test.h";
  extern proc hello_world(): void;
}

module main
{
  use extern_c;

  proc main(): int
  {
    writeln("hello world from chpl");
    hello_world();

    return 0;
  }
}
```

**Compile command:**
`chpl test.chpl -o test.o --fast`

**Execution command:**
`./test.o`

### Configuration Information

- Output of `chpl --version`: 
```chapel
chpl version 1.29.0
  built with LLVM version 14.0.0
```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```chapel
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: gpu *
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: none
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: bundled *
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: `gcc (GCC) 10.2.0`

**Comment by e-kayrakli** [comment]
Thanks for the bug report @Guillaume-Helbecque!

In fact, just yesterday we were discussing our extern support with the GPU locale model among the GPU subteam. This is a good data point and motivator to tighten things up there. I will give it a quick look and report back if there's any quick workaround.

Meanwhile, in your real use case, are you planning to call an extern function from inside a GPU kernel (with the assumption that that extern will have `__device__`), or this is a regular function that's to be called from the CPU?

**Comment by e-kayrakli** [comment]
There is a workaround here, and probably we'll need to fix something with `require` statements or `.c` files passed to the compiler.

The workaround is to separately compile your `.c` file with C++ linkage where the easiest solution is just `g++ -c`, and then change your `require` statement to use the generated `.o` instead.

The root cause is that in a nutshell we compile everything basically like `clang -x cuda` which implies C++ linkage. But for some reason, the `require` statement isn't causing that to happen.

--- 

Note that I created https://github.com/chapel-lang/chapel/issues/21906 that shows a similar problem when calling extern functions from inside GPU kernel, which is a bit more complicated but that's where you may be heading at the moment. Please let us know if that's a feature that you'll need soon (commenting under that issue would be ideal), so we can see if we can fix it soon.

**Comment by Guillaume-Helbecque** [comment]
Many thanks for this workaround @e-kayrakli ! I confirm that it solves the problem.

For the moment I simply want to call external C functions as regular ones that are called from the CPU, but at some point I will need to call functions from inside a GPU kernel so it would be great if this feature was supported.

**Comment by tcarneirop** [comment]
Im facing the same issue here, but the more simple version of it -- calling a C function from a CPU-only Chapel function.

**Comment by bradcray** [comment]
@tcarneirop : Does Engin's workaround above help in your case?

Engin, do you have a sense of how hard this would be for us to fix?

**Comment by tcarneirop** [comment]
@bradcray Yes! I'm in touch with Andy and Engin. I still have to see if the workaround helps in my case. Thanks!

**Comment by e-kayrakli** [comment]
@Guillaume-Helbecque / @tcarneirop -- this issue is closed with the PR linked above.

When/if you get the chance, it'd be great if you can check if it does help with your real use-case as well.

**Comment by Guillaume-Helbecque** [comment]
It looks good for me, thanks @e-kayrakli !

**Comment by tcarneirop** [comment]
Ok! I'll test it and send a feedback.

Thanks!

Em sex., 28/04/2023 às 10:19, Guillaume Helbecque ***@***.***>
escreveu:
