### ISSUE TITLE
Compiler breaks when `return` within `foreach`-loop while `CHPL_LOCALE_MODEL=gpu`

### ISSUE THREAD

**Issue by Guillaume-Helbecque** [chapel-lang/chapel#21924]
### Summary of Problem
Compiler breaks (see below) when a `foreach`-loop contains a `return` statement and `CHPL_LOCALE_MODEL=gpu`. This does not happen usign the default value of `CHPL_LOCALE_MODEL` and LLVM enabled.

```
internal error: OPT-GPU-RMS-0713 chpl version 1.29.0
Note: This source location is a guess.

Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug --
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.
```

### Steps to Reproduce

**Source Code:**

```chapel
proc return1(): int
{
  foreach 1..1 do return 1;
  return 0;
}

proc main(): int
{
  writeln(return1());
  return 0;
}
```

**Compile command:**
`chpl test.chpl -o test.o --fast`

**Execution command:**
`./test.o`

### Configuration Information

- Output of `chpl --version`: 
```chapel
chpl version 1.29.0
  built with LLVM version 14.0.0
```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```chapel
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: gpu *
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: none
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: bundled *
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: `gcc (GCC) 10.2.0`

**Comment by Guillaume-Helbecque** [comment]
Same thing happens using `break` instead of `return`, but using `continue` it's OK.

**Comment by e-kayrakli** [comment]
I had attempted to fix this via https://github.com/chapel-lang/chapel/pull/21620, but I got bogged down while trying to get label's work right. In that effort, I was focusing on `break`. `return` is probably a bit more complicated, though.

That being said, @Guillaume-Helbecque would it be too limiting for you if `return` inside `foreach` was not allowed at all? Note that that's the case for `forall`s today.

**Comment by bradcray** [comment]
>  if return inside foreach was not allowed at all?

This is where my head started as well...  Would the presence of returns or breaks within foreach statements make them unable to be vectorized/GPU-ized, making a for-loop just as good and less misleading?  I'm not enough of a vectorization or GPU expert to happen to know...

**Comment by e-kayrakli** [comment]
Speaking from GPU-only perspective: You can `return` from a CUDA kernel. It'll end that specific threads execution, while the others will finish normally. That's most easily represented with a `break` in a `foreach`/`forall` in Chapel.

Note that a `return` in a GPU-eligible `foreach`/`forall` doesn't have a corresponding feature/semantic in CUDA. It'd be something like returning from the function that called the kernel or something.

So, in the short term, we can allow `break`s in `foreach`es that are GPU-eligible. Note that the compiler is OK with it today, because internally `foreach`es are `for`s with a flag set. `forall`s are much more complicated, but maybe this can be the forcing function to make some progress on that in general: https://github.com/chapel-lang/chapel/issues/12700

**Comment by Guillaume-Helbecque** [comment]
I would say that my hopes regarding a `break`/`return` in a `foreach`-loop would be a eureka-like event for all tasks, for the same reason that @bradcray pointed out: it is more similar to what `for` would do.

**Comment by e-kayrakli** [comment]
> I would say that my hopes regarding a break/return in a foreach-loop would be a eureka-like event for all tasks

How would you implement that in CUDA or some other GPU programming API? It sounds like it requires the ability for one CUDA thread to end execution of all other CUDA threads. That's not supported AFAIK.

**Comment by e-kayrakli** [comment]
Maybe something with cooperative groups? https://docs.nvidia.com/cuda/cuda-c-programming-guide/#cooperative-groups

**Comment by Guillaume-Helbecque** [comment]
If I could answer this question I would be happy to help you. Unfortunately, I'm not a CUDA expert.

**Comment by bradcray** [comment]
Engin, probably obvious given my previous comments, but my takeaway here would be that we should prohibit `break`/`return` in `foreach` loops until such time as we can support it in a way that would mean the eureka-style exit; and then investigate some other syntax for doing the "break my thread, but let others proceed" approach (where the error for the former could potentially point to the latter as a possibility, letting users choose whether it's right for them).

For vectorized foreach loops, I wonder whether we'd need to prohibit break/return within the loops, or could just codegen them and let the vectorizer do what it will with them (where I'm not sure what that would be, but it might simply be to say "I can't vectorize this loop, so I'll execute it serially").  That said, I'd have no problem with disallowing it in those cases as well for uniformity (with GPU foreach loops and forall loops) until someone argues that they want/need it badly enough.

And if your cooperative groups idea is workable longer-term, we can relax the restriction.

**Comment by e-kayrakli** [comment]
> Engin, probably obvious given my previous comments, but my takeaway here would be that we should prohibit break/return in foreach loops until such time as we can support it in a way that would mean the eureka-style exit; and then investigate some other syntax for doing the "break my thread, but let others proceed" approach (where the error for the former could potentially point to the latter as a possibility, letting users choose whether it's right for them).

Yeah, I am with you. I wasn't thinking about the eureka pattern while I started working on the PR I referred to above. Note that this came up in a user code, which had other issues that we worked around now. So, I am a little curious and trying to remember what iterator that was causing hitting `break` in a gpu-eligible loop. I'll prepare a branch with a blanket error for `break` and `return` for `foreach` and see if it breaks a test.

> For vectorized foreach loops, I wonder whether we'd need to prohibit break/return within the loops, or could just codegen them and let the vectorizer do what it will with them (where I'm not sure what that would be, but it might simply be to say "I can't vectorize this loop, so I'll execute it serially"). That said, I'd have no problem with disallowing it in those cases as well for uniformity (with GPU foreach loops and forall loops) until someone argues that they want/need it badly enough.

There might be something funky we can do with vector masks, but in all likelihood we'll need to disallow this as well, at least for the short term. Though, note that the midway between where we are and this could be "break/return make a loop gpu-ineligible". Pinging @mppf to see if he has any input on this, especially from the vectorization perspective.

> And if your cooperative groups idea is workable longer-term, we can relax the restriction.

Yes. And to echo/emphasize what you've already said; if it is, it is definitely a long-term thing.


---

Thinking about this more... I said:

> Speaking from GPU-only perspective: You can return from a CUDA kernel. It'll end that specific threads execution, while the others will finish normally. That's most easily represented with a break in a foreach/forall in Chapel.

When I think about it now, this pattern is actually `continue`. When a CUDA thread hits `return`, it'll finish executing but other threads will go on normally. The returned thread will just be masked out of execution, IOW, it'll wait at the end of the kernel for other threads to finish. A CUDA thread's execution is analogous to a single iteration of the loop in our model. To have a similar effect as `return` in kernel, you'd need to end the current iteration. And that's what `continue` does. 

@Guillaume-Helbecque this is a bit tangent to your original question, but it's been a nice discussion. To summarize where we are going with this, your code in the OP will be disallowed. I'd be interested in seeing the real use case for wanting to return a scalar from a gpu-eligible loop, is it a reduction of sorts? Note that you can return from CUDA kernels, but you can't return values from them -- they have to be `void` functions. Typically kernels write to global memory which is then read by the host when they are done as opposed to kernels returning scalars.

**Comment by bradcray** [comment]
> I'll prepare a branch with a blanket error for break and return for foreach and see if it breaks a test.

That'd be great, thanks!

(if it's trivial to make foreach variables also subject to normal shadowing / intent rules while you're there, even better!  :D  https://github.com/chapel-lang/chapel/issues/19153   https://github.com/chapel-lang/chapel/issues/18500)

**Comment by e-kayrakli** [comment]
@Guillaume-Helbecque -- With #22167 merged, I am seeing `error: 'return' is not allowed in a 'foreach' statement` in your code, much earlier in the compilation. This is aligned with the discussion above.

I am adding two tests in https://github.com/chapel-lang/chapel/pull/22169 that locks in the behavior that you've observed -- things work with `continue`. As per my previous comment above, if you want to end the current thread's execution in a kernel (which is not exactly what you have in the OP) `continue` is the way to go.

With these two, I think we can close this issue. What do yo think?
