### ISSUE TITLE
chpldoc is not deleting its temporary directories

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#21927]
### Summary of Problem

It appears that chpldoc never deletes its temporary directories.

### Steps to Reproduce

```
$ chpldoc > /dev/null
$ ls /tmp | wc -l
15
$ chpldoc > /dev/null
$ ls /tmp | wc -l
16
$ chpldoc > /dev/null
$ ls /tmp | wc -l
17
```

### Configuration Information

pre-release 1.30

**Comment by mppf** [comment]
Note, I have also noticed that `chpl` is not always cleaning up its temporary directory, but I do not know what situations cause that to happen.

**Comment by mppf** [comment]
I am looking at some changes that arrange to have `Context` manage the temp directory.

**Comment by bradcray** [comment]
Noticing the large number of chpldoc directories I've created while paratesting made me come looking for this.  I'm happy to see there's a PR open to resolve it and look forward to it being merged.
