### ISSUE TITLE
Promote `--print-chpl-home` to a user flag and split it into multiple flags

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#21929]
In https://github.com/chapel-lang/chapel/issues/21622, it was pointed out that the definition of `CHPL_HOME` can be vague to a user making use of a `make install` version of Chapel.  PR #21867 took a step toward making it better by updating the documentation to describe the interpretation of `CHPL_HOME` in these settings, but is the sort of documentation someone might forget, or never read (particularly if they are using an installation of Chapel).

In this issue, I'm proposing addressing this by making `--print-chpl-home` into a user-facing flag so that it shows up in the `chpl --help` output and man page for someone trying to understand its value.  I believe that these changes would be sufficient to close #21622.

At present, the developer version of the flag prints out not just `CHPL_HOME`, but also the path to `chpl` (after a tab) and — if `./configure --prefix` was used at any point in the repo and was not cleaned up afterwards — the configured prefix location (on its own line with a comment prefix).

In this issue, I'm also proposing splitting this into multiple flags to clarify / simplify the output.  Specifically:

* `--print-chpl-home` will be a user flag that just prints out $CHPL_HOME
* `--print-chpl-loc` will be a developer flag that just prints out the path to `chpl`
* for now I'm not planning on preserving the query of the prefix location because it's not something that I think I'd find useful as a user, and I couldn't find any tests or code that made use of it; we could always add it later as a user or developer flag if/when needed

**Comment by bradcray** [comment]
A draft of this is implemented in #21930

**Comment by mppf** [comment]
`--print-chpl-loc` seems of more interest to our testing than to a user. Do you plan to make it a develope flag?

**Comment by bradcray** [comment]
I hadn't, but I'm definitely open to that proposal.  I was thinking we might want a user to send us the output of it in some situations, but of course it need not be a user flag to do this... I think I put them adjacent to one another in my draft PR just because that's where I was doing the editing...

**Comment by bradcray** [comment]
@mppf: I've updated the OP to reflect that design, which I agree is preferable.
