### ISSUE TITLE
Proposal for exposing `shared` and `weak` to users

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#21951]
At present, `shared` classes are considered part of the language, while `weak` references to them are considered part of the standard library through the `WeakPointer` module.  This gives me pause in a few ways:

* Since `shared` and `weak` go hand-in-hand, even if the latter is a more expert feature, it seems like they should be exposed together in the same way as well
* I'm not a fan of `WeakPointer` as a module name, since we tend not to talk about pointers much in the language (and may want to introduce them in another form later on)
* It seems odd that `WeakPointer` is exposed in the documentation as a standard module but is implemented as part of an internal module

Here's a proposal that I currently like:
* Move `shared` out of the language and into a library-based type, defined by a standard module named `Shared` or `SharedClass`, say
* Move `weak` into that module as well
* Ideally/ultimately, retire `shared` as a built-in keyword;

A key advantage of this proposal to me is that it reduces the number of built-in class management types from four to three.  While it would be ideal to have just one language-based class management type, this doesn't seem feasible to me, since:
* `owned` is our default, `owned` and `borrowed` go hand-in-hand, and the compiler needs to know about them to do lifetime checking
* `unmanaged` feels like a fundamental building block as well
Yet having three built-in class styles feels strictly better than four.

This proposal also is attractive in that we've discussed providing the ability for end-users to define their own class-management styles down the road, and it would be cool if `shared` could be the first example of that.

That said, I worry a little bit that parsing user-defined class management styles will be a challenge due to the need to support `TIDENT TIDENT` as a legal syntax, and my fear that it will lead to conflicts.  In the short-term, we could move to the organization above by continuing to reserve `shared` as a keyword, and complaining if it's used in a context where the `Shared` module is not appropriately `use`d/`import`ed to give access to the symbol.  However, if we were unable to parse `TIDENT TIDENT` down the road, it's not clear how we would release `shared` as a keyword or make it symmetrical with other types.

Despite that misgiving, I generally feel as though having `shared` logically defined by a module, even if it enjoyed special syntactic support for the foreseeable future feels more attractive than having it remain built into the language for the reasons expressed above:  fewer built-in class types, a more natural pairing of shared and weak, and a better module name / normal standard module for `weak` to live in.

**Comment by mppf** [comment]
Works for me.

> it reduces the number of built-in class management types from four to three. 

Am I correctly understanding that a further implication is that users who want to use `shared` would need to `use Shared` ?

**Comment by bradcray** [comment]
> Am I correctly understanding that a further implication is that users who want to use shared would need to use Shared ?

Yes.  And I'm imagining that even if/while `shared` remains a keyword for the time being, that it's a keyword that would generate an error if `Shared.shared` wouldn't be visible (if `shared` were literally defined in `Shared`).  Thus, a `use Shared;` or `imposrt Shared.shared;` would be necessary.

**Comment by jabraham17** [comment]
In an offline discussion (https://github.com/Cray/chapel-private/issues/5169), we decided to not change how shared is included.

Closing, as #20956 tracks where we should put `weak`

**Comment by bradcray** [comment]
:'(
