### ISSUE TITLE
AMD GPU Support unable to find oclc_isa_version bitcode file for certain architectures (e.g. gfx90a)

### ISSUE THREAD

**Issue by stonea** [chapel-lang/chapel#21964]
When using `CHPL_GPU_CODEGEN=rocm` (that is for AMD GPU support) and `CHPL_GPU_ARCH` is something that isn't just `gfx + a number` you may get this error (e.g. this fails with gfx90a):

`error: Unable to find or open ROCM device library file /opt/rocm/amdgcn/bitcode/oclc_isa_version_90.bc`

This is because Chapel needs to read in the right `oclc_isa_version_*.bc` file for your architecture and we try and automatically deduce this based off the value of `CHPL_GPU_ARCH` by using a regex in this function:

https://github.com/chapel-lang/chapel/blob/df14e46a9c65e1e1d0b2d1cda602cfa512ca8ce6/compiler/llvm/clangUtil.cpp#L3852

An easy fix would be to update the regex but basing this off of regexp is in itself kind of brittle.

Perhaps we should have an environment variable to set this (say `CHPL_GPU_OCLC_LIB_PATH` or something). We could still have `chplenv` try and automate finding this using an approach similar to what we do now but it would be good to have a workaround in case some future architecture doesn't fit whatever pattern we come up with. Even better would be to see if we could deduce this some other way.

**Comment by e-kayrakli** [comment]
This is not exactly related, but arguably something that can be fixed as part of this and not sure if it deserves its own issue just yet:

https://github.com/chapel-lang/chapel/blob/main/compiler/llvm/clangUtil.cpp#L4178

has `gfx906` hardcoded. It should use `CHPL_GPU_ARCH`.

**Comment by stonea** [comment]
Closing with this PR: https://github.com/chapel-lang/chapel/pull/22263
