### ISSUE TITLE
IO Serializers: Should endianness be part of binary serializer types?

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#21996]
For the purposes of this issue, let's consider two hypothetical ``BinarySerializer`` and ``BinaryDeserializer`` types.

Should endianness be part of a Binary(De)Serializer's type, as opposed to being a runtime value? For example, you could constrain an implementation to only support little-endian binary IO:

```chpl
record BinarySerializer {
  param endian : IO.ioendian;
  // vs.
  // const endian : IO.ioendian;
  ...
}

proc T.serialize(writer: fileWriter(serializeType=BinarySerializer(ioendian.little))) throws { ... }
```

Is this a valuable property to know at compile time? Should there be a default (e.g. ``ioendian.native``)?

**Comment by bradcray** [comment]
At a sniff, this seems attractive and valuable to me.  Is the alternative to only support native endianness?

Knowing it at compile-time doesn't seem obviously valuable, unless it takes a branch out of an inner loop (which I suppose it might?).

**Comment by benharsh** [comment]
I think I was a bit unclear initially. It has been my expectation that our standard binary format ([whatever that may be](https://github.com/chapel-lang/chapel/issues/21997)), would support different endian configurations. The main question I was trying to ask was whether we should know this at compile-time, or if a runtime value was suitable. I've updated the issue to hopefully reflect that.

**Comment by bradcray** [comment]
Got it, thanks for clarifying.

**Comment by mppf** [comment]
The compile-time vs run-time question here I think depends on the performance implications so I'm not sure how to answer that without some performance experiments.

**Comment by benharsh** [comment]
The eventual decision here was to use a runtime value for endianness with a default of ``endianness.native``. At one point I ran some performance experiments with some of the shootout benchmarks that rely on binary IO and saw only a minor performance regression (e.g. ~5%) from usage the runtime value. At the time I also noted that we could match the old performance by calling the QIO runtime methods directly with the runtime value.
