### ISSUE TITLE
Add mode to report on all gpu eligible and ineligible loops in a program

### ISSUE THREAD

**Issue by stonea** [chapel-lang/chapel#22009]
It would be nice if there was some flag we could pass to `chpl`, say `--report-gpu-transformations` that could be used to discover:

* All the forall/foreach loops in a program that are eligible for GPU execution, and
* All the forall/foreach loops in a program that are found ineligible for GPU execution

One possible way to do the second of these goals would be to implicitly add `assertOnGpu()` to all such loops.

This issue was created as a response to the comment here: https://github.com/chapel-lang/chapel/issues/22007#issuecomment-1489425416 and its followup conversation.

**Comment by stonea** [comment]
I'm undecided if this should display the information for all the loops within standard modules or if that should only occur when `CHPL_DEVELOPER=true`.

**Comment by e-kayrakli** [comment]
> I'm undecided if this should display the information for all the loops within standard modules or if that should only occur when CHPL_DEVELOPER=true.

Given this flag is for users to find how we transform their loops, I think that should only occur with `--devel` or `CHPL_DEVELOPER=true`, if it ever does.
