### ISSUE TITLE
Improve gpuAssert error messages to always note line in kernel making it ineligible

### ISSUE THREAD

**Issue by stonea** [chapel-lang/chapel#22007]
If I compile the following:

```chpl
use GPU;

var x : int;
proc bar() { return x; }
proc foo() { return bar(); }

on here.gpus[0] {
  var A : [0..0] int;
  foreach i in 0..0 {
    assertOnGpu();
    A[i] = foo();
  }
}
```

I'll get the following error letting me know that the loop is ineligible for GPU execution:

```
foo.chpl:1: In module 'foo':
foo.chpl:9: error: Loop containing assertOnGpu() is not eligible for execution on a GPU
foo.chpl:5: note: call has outer var access
```

This is expected and it's nice that the error message points out that the call that has var outer access is the call to `bar()` being invoked by `foo()`.  I think it would be even better if the error message also indicated that the line in the kernel that led to this was the call to `foo()` (on line 11).

In this particular example it's not too hard to see what's going on but this can be especially confusing the more convoluted the call-chain gets, especially if the issue ultimately ends up being in standard module code.

As a general principle it would nice if all the `assertOnGpu()` error message had a note indicating the line in the loop that was responsible for the error.

**Comment by bradcray** [comment]
Only loosely related to this issue:

Reading the conversation that led to this issue, made me think it could be attractive to have a `--print-gpu-thwarters` (wow, that's a terrible name) flag in the compiler that would effectively add an `assertOnGPU()` to every parallel loop that _might_ conceivably run on a GPU as a way of learning which are not eligible for GPUs and why without source code modifications.  For a large enough code, that seems preferable to adding `assertOnGPU()` calls to each loop manually or maintaining them over time.  It also seems like it could potentially improve reporting for some idioms—like promotion—that aren't very amenable to accepting `assertOnGPU()` calls...?

**Comment by e-kayrakli** [comment]
We have `--report-xyz` type flags. `--report-gpu-transformations` could be a good name for such a flag.

**Comment by stonea** [comment]
> Reading the conversation that led to this issue, made me think it could be attractive to have a --print-gpu-thwarters (wow, that's a terrible name) flag in the compiler that would effectively add an assertOnGPU() to every parallel loop that might conceivably run on a GPU as a way of learning which are not eligible for GPUs and why without source code modifications.

Yeah I think this would be useful to add. I think it would also want to see the list of loops that are found to be eligible for GPU execution.  I don't know if it'd be best to literally show the error message `assertOnGpu` would produce or have the information summarized in some other form (a table or whatever).

Somewhat tangentially: I'm quite curious how often we end up generating code for gpuized loops that will never actually be executed on the GPU, and this tool would be a useful thing to help us explore that.

**Comment by stonea** [comment]
I forked a followup issue for the `--print-gpu-thwarters`/`--report-gpu-transformations` idea here: https://github.com/chapel-lang/chapel/issues/22009

**Comment by e-kayrakli** [comment]
Another thing the code in OP brings up is the call stack leading to the error. In 10 lines of code, it is easy to what calls what, but it'd be also nice if the chain from loop body->`foo`->`bar`->global `x` is somehow reported.
