### ISSUE TITLE
More reliable way for finding GPU SDK roots?

### ISSUE THREAD

**Issue by DanilaFe** [chapel-lang/chapel#22057]
Currently, we try to find the SDK root for a particular GPU by running the corresponding compiler command, and going up a certain number of directories from that. However, this has proven unreliable; a recent ROCm update, for instance, moved the `bin` folder one directory closer to the root, and we failed to find the ROCm SDK path. It might be worth doing something other than searching for a compiler (perhaps `ROCM_PATH` in the AMD case, a `_PATH` in general?)

**Comment by e-kayrakli** [comment]
> perhaps ROCM_PATH in the AMD case

If there's such a thing that'd be great.

Spelling out some ideas that may be obvious to others:

- we can also prune the path until we hit `rocm-x.y.z` which may be more standard,
- we can walk up the dir chain and test every level to see if we can find everything relative to that location (not great),
- this is somewhat related to https://github.com/chapel-lang/chapel/issues/21964, in the sense that maybe our env scripts should do more than string processing and actually confirm that what we need is actually in the path that it computed.
