### ISSUE TITLE
chpldoc should automatically nodoc symbols starting with `chpl_`

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#22081]
Currently, our documentation has stray symbols in it that are prefixed with `chpl_` and intended not to be user-facing.  This issue requests that chpldoc not document such symbols (by default anyway).

(While here, we may also want to turn the warning of user declarations of symbols named `chpl_` from an unstable warning to a simple warning (?).

**Comment by bradcray** [comment]
@arezaii : I was going to ask whether you thought this would be easy or hard, and then decided to open chpldoc and whether if I could do it in a few minutes or not.  The answer turned out to definitely be "not" where, as far as I can tell, there isn't a uniform way, in a place like `isNoDoc()`, to find the name of a symbol and look for the `chpl_` prefix.  I suppose an alternate approach would be to have the parser itself attach the `chpldoc.nodoc` attribute to things as it parses them, but I'm not sure whether that'd be another case of having lots of cases to analyze or whether it could be done in a centralized-ish way (e.g., on the `identifier` rule).  Anyway, curious if you have any insights here that I'm missing.

**Comment by arezaii** [comment]
Hmm...my first thought is similar, I would think we could just check in `isNoDoc()` by attempting to cast to a `NamedDecl` and see if it starts with `chpl_`. 
something like:
```
  if (auto namedDecl = e->toNamedDecl()) {
    if (namedDecl->name().startsWith(UniqueString::get(gContext, "chpl_"))) {
      return true;
    }
  }
```

Could you give me an example that's in the docs today so I can test it?

**Comment by bradcray** [comment]
> Is this an example of a bad entry you are wanting to eliminate?

Yep, exactly!

> it does break some links in the docs for BigInteger... so may require some more thought than I put in so far.

I don't think this is anything wrong with your branch, but more a question of whether these routines should have these names / be documented / be linkable within the docs.  My guess is that the `chpl_` prefix here is meant to be less "This is an internal name" and more a way of indicating that these aren't typical methods on GMP types.

Looks like @mppf may have done some of this early groundwork (and that @lydia-duncan has touched those routines since), so it might be useful to get their feedback on this issue's proposal more generally...  I think the use of `chpl_` as an "for internal use" prefix has grown in popularity in more recent years, where we were much more seat-of-the-pants in the early days when these routines were introduced.

**Comment by lydia-duncan** [comment]
Looking at the routines in the GMP module, it looks like the `chpl_` prefix there was to distinguish between routines directly supported by GMP and routines we added that seemed useful.  That might argue for adding a "please doc" attribute to opt-in to documenting functions that would otherwise be suppressed, at least until we've had a chance to go through the GMP interface and adjust it.

I'd be okay with removing the deprecated functions that trigger this doc warning - they've been deprecated for more than a year now, we only left them because work was continuing to be done on the BigInteger module as a whole but I don't envision a world where we restore them (especially since no one has complained about their deprecation in that time).

**Comment by arezaii** [comment]
> I'd be okay with removing the deprecated functions that trigger this doc warning

sounds reasonable, we'd still need the attribute to force docs for the replacement functions, so perhaps `@chpldoc.yesdoc` or `@chpldoc.dodoc` or `@chpldoc.plz2doc` 😹

**Comment by lydia-duncan** [comment]
Some other names:

- `@chpldoc.forceDoc`
- `@chpldoc.enableDoc`

**Comment by bradcray** [comment]
You two are so fancy!  I was just imagining `@chpldoc.doc`.  That said, I'm working on generating a diff to see whether the net win of ceasing to document things we shouldn't be seems worth ceasing to document GMP routines before such an attribute comes online.

**Comment by mppf** [comment]
`chpl_gmp_mpz_nlimbs` seems potentially useful as a low-level routine but I think we could rename it. At a quick glance, I'm not seeing `gmp_mpz_nlimbs` in GMP documentation, but I could be missing something. Anyway, even if the concept of the name is right (which I am not so sure of today) we could easily use names like `chapel_gmp_mpz_nlimbs` or `gmp_mpz_nlimbs_chpl`.

**Comment by bradcray** [comment]
> chpl_gmp_mpz_nlimbs seems potentially useful as a low-level routine

I didn't mean to suggest otherwise if I did.

> I think we could rename it.

This would be my preference.

**Comment by arezaii** [comment]
In https://github.com/chapel-lang/chapel/pull/22494, I added functionality to suppress docs for symbols that begin with `chpl_`, a pragma to override that behavior, and also removed redundant `@chpldoc.nodoc` attributes from existing symbols named `chpl_*`

Follow-up work remains to go over symbols with the new `pragma "chpldoc ignore chpl prefix"` and rename them or remove the pragma as seen fit. There is an issue to capture this at https://github.com/Cray/chapel-private/issues/4938

**Comment by arezaii** [comment]
This feature was implemented in https://github.com/chapel-lang/chapel/pull/22494.

Unless the symbol has `pragma "chpldoc ignore chpl prefix"`, `chpldoc` will now ignore symbols with that begin with `chpl_`
