### ISSUE TITLE
Can't open a file for append.

### ISSUE THREAD

**Issue by stevenrbrandt** [chapel-lang/chapel#22084]
I had written a simple benchmark code and wanted to append timing results to a csv file. I discovered that there's no way to do this.

It would be good to have the ability to open files for append, possibly adding ioMode.a for this purpose.

**Comment by Guillaume-Helbecque** [comment]
I encountered this as well. My workaround was to invoke an external C function.

**Comment by ronawho** [comment]
A workaround I've used is to open the file and "seek" to the end. Something like:

```chpl
var writer;
if exists(filePath) {
    var aFile = open(filePath, ioMode.rw);
    writer = aFile.writer(region=aFile.size..);
} else {
    var aFile = open(filePath, ioMode.cwr);
    writer = aFile.writer();
}

writer.write(...);
```

I'm not very familiar with the effort, but there is some design work around I/O interfaces related to this in https://github.com/chapel-lang/chapel/issues/20134, and an older user issue requesting and append mode in https://github.com/chapel-lang/chapel/issues/9992

**Comment by bradcray** [comment]
@stevenrbrandt : I believe the support for an append mode that @jabraham17 added in #22643 today should be sufficient for the type of file writing you requested here.  Specifically, it's currently limited to files that only have a single writer, so doesn't support parallel IO (which leads to challenges getting all of the writers to agree where the end of the file is); but I think you were only interested in writing from a single writer anyway in your code?  Let us know whether you agree.  Thanks!

**Comment by stevenrbrandt** [comment]
I have not tested it, bit `ioMode.a` was exactly what I wanted. Thanks.

**Comment by bradcray** [comment]
I'm going to close this based on the sense that we've done what was originally needed, though more could still be done.  If/when people need more general support in their append mode than what we have today, we can open new issues for it.
