### ISSUE TITLE
Chapel 1.30.0 issues with ZMQ and HDF5

### ISSUE THREAD

**Issue by compiling-is-winning** [chapel-lang/chapel#22082]
Since the Chapel 1.30.0 update, I'm now getting the following error when running `make check-zmq` prior to building Arkouda:

```
Checking for ZMQ
In file included from <built-in>:5:
In file included from /home/firang/Code/Chapel/chapel-1.30.0/modules/packages/ZMQHelper/zmq_helper.h:26:
In file included from /home/firang/Code/Chapel/chapel-1.30.0/runtime/include/qio/qio.h:26:
In file included from /home/firang/Code/Chapel/chapel-1.30.0/runtime/include/qio/qbuffer.h:52:
In file included from /home/firang/Code/Chapel/chapel-1.30.0/runtime/include/atomics/cstdlib/chpl-atomics.h:26:
In file included from /home/firang/Code/Chapel/chapel-1.30.0/runtime/include/chpl-tasks.h:30:
/home/firang/Code/Chapel/chapel-1.30.0/runtime/include/tasks/qthreads/chpl-tasks-impl.h:37:10: fatal error: 'qthread.h' file not found
#include "qthread.h"
         ^~~~~~~~~~~
1 error generated.
error: error running clang during code generation

ERROR: Please ensure that dependencies have been installed correctly (see -> https://github.com/Bears-R-Us/arkouda/blob/master/pydoc/setup/BUILD.md)

/home/firang/Code/Arkouda/arkouda//dep/check-zmq -nl 1
make: /home/firang/Code/Arkouda/arkouda//dep/check-zmq: No such file or directory
make: *** [Makefile:219: check-zmq] Error 127
```  

For a bit of context, this specific error showed up after resetting CHPL_HWLOC from 'bundled' to 'none'.  Prior to that change, I got errors to this effect:

`internal error: topo-hwloc.c: 333: !((pusPerCore == 0) || (pusPerCore == numPus))`

when running the zmq check prior to compiling Arkouda and also in a standalone Chapel program that I wrote located here:

https://github.com/compiling-is-winning/arkouda-contrib/blob/main/arkouda_cws_hashing/test/cws_unit_test.chpl

After changing the HWLOC environment variable, my standalone program runs fine.  However, the ZMQ check for Arkouda does not.  I also get the following error (seemingly unrelated to that specific environment variable) when running `make check-hdf5`:

```
Checking for HDF5
In file included from <built-in>:4:
/home/firang/Code/Chapel/chapel-1.30.0/modules/packages/HDF5Helper/hdf5_helper.h:55:31: error: incompatible pointer types passing 'unsigned long long *' to parameter of type 'hsize_t *' (aka 'unsigned long *') [-Werror,-Wincompatible-pointer-types]
                              (unsigned long long*)dims,
                              ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/firang/Code/anaconda3/envs/arkouda-dev/include/H5LTpublic.h:591:84: note: passing argument to parameter 'dims' here
H5_HLDLL herr_t H5LTget_dataset_info(hid_t loc_id, const char *dset_name, hsize_t *dims,
                                                                                   ^
In file included from <built-in>:4:
/home/firang/Code/Chapel/chapel-1.30.0/modules/packages/HDF5Helper/hdf5_helper.h:69:27: error: incompatible pointer types passing 'unsigned long long *' to parameter of type 'const hsize_t *' (aka 'const unsigned long *') [-Werror,-Wincompatible-pointer-types]
                          (unsigned long long*)dims,
                          ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/firang/Code/anaconda3/envs/arkouda-dev/include/H5LTpublic.h:190:96: note: passing argument to parameter 'dims' here
H5_HLDLL herr_t H5LTmake_dataset(hid_t loc_id, const char *dset_name, int rank, const hsize_t *dims,
                                                                                               ^
In file included from /home/firang/Code/Chapel/chapel-1.30.0/runtime/etc/rtmain.c:24:
In file included from /home/firang/Code/Chapel/chapel-1.30.0/runtime/include/stdchpl.h:43:
In file included from /home/firang/Code/Chapel/chapel-1.30.0/runtime/include/atomics/cstdlib/chpl-atomics.h:26:
In file included from /home/firang/Code/Chapel/chapel-1.30.0/runtime/include/chpl-tasks.h:30:
/home/firang/Code/Chapel/chapel-1.30.0/runtime/include/tasks/qthreads/chpl-tasks-impl.h:37:10: fatal error: 'qthread.h' file not found
#include "qthread.h"
         ^~~~~~~~~~~
3 errors generated.
error: error running clang during code generation

ERROR: Please ensure that dependencies have been installed correctly (see -> https://github.com/Bears-R-Us/arkouda/blob/master/pydoc/setup/BUILD.md)

/home/firang/Code/Arkouda/arkouda//dep/check-hdf5 -nl 1
make: /home/firang/Code/Arkouda/arkouda//dep/check-hdf5: No such file or directory
make: *** [Makefile:226: check-hdf5] Error 127
```

My Chapel environment when last building Chapel 1.30.0 is as follows:

```
CHPL_HOME: /home/firang/Code/Chapel/chapel-1.30.0 *
script location: /home/firang/Code/Chapel/chapel-1.30.0/util/chplenv
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled
CHPL_HWLOC: none *
CHPL_RE2: bundled
CHPL_LLVM: system
CHPL_AUX_FILESYS: none
```

I also did some futzing around with my gcc version that I can describe if needed, since I was initially worried that this was a gcc issue.

**Comment by cassella** [comment]
In [this discourse topic](https://chapel.discourse.group/t/help-needed-1-30-make-check-fails-on-one-of-my-machines/20630) it was suggested that the topo-hwloc.c internal runtime error could have to do with heterogeneous nodes, cpu/thread/core-count-wise.  
Does that seem likely to describe your hardware?

Though you've already tried the workaround presented there of HWLOC=none.


What does printchplenv report (particularly about qthreads) in the configuration where you got the `qthread.h` error?

(Lacking any better ideas, I might try a `make clobber` and retry that configuration, if you haven't already.)

**Comment by bradcray** [comment]
@jhh67 : Tagging you on this since it looks similar to what you were helping with in https://chapel.discourse.group/t/help-needed-1-30-make-check-fails-on-one-of-my-machines/20630/6  I'm also thinking we should create a public issue for this internal error given that two users have hit it now—both to capture the desire to improve the situation for 1.31 (or wait, I've lost track... have we already?) and to help those who hit it figure out how to work around it and feel reassured that it's known and/or fixed.  I'd write it up, but don't have a firm enough grasp on the issue to do it justice.

@compiling-is-winning : Would you be able to validate Paul's guess that there might be something heterogeneous w.r.t. your processor architecture?

@cassella : Thanks for noting the similarity to the Discourse thread!

**Comment by jhh67** [comment]
I created issue https://github.com/chapel-lang/chapel/issues/22109 for this bug. As I mentioned in that issue, I'd like to get user feedback on the user interface for controlling which cores the runtime uses.

**Comment by compiling-is-winning** [comment]
@bradcray yup, it is likely that this is due to a distinction in different core types as described in the issue above, given that my home system uses Alder Lake CPU's
