### ISSUE TITLE
Are we able to reliably use multiple GPUs within one locale concurrently?

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#22128]
I am filing this issue on behalf of @tcarneirop who has reported it via email.

When using an idiom like:

```chapel
forall gpuId in 0..#numGpus {
  on here.gpus[gpuId] {
    foreach ....
  }
}
```

he was observing that in around 30% of the runs, GPU 0 would wait for the other GPUs to finish before starting work, degrading overall performance.

Two screenshots from nvidia-smi shows that similar amounts of memory were allocated on the GPUs, but GPU 0 ran separately where we'd expect it to run concurrently.

<img width="721" alt="Screen Shot 2023-04-19 at 5 05 54 PM" src="https://user-images.githubusercontent.com/4141670/233225021-e52a1b1d-45dc-4266-9aef-3651ed4e2ed6.png">
<img width="725" alt="Screen Shot 2023-04-19 at 5 06 17 PM" src="https://user-images.githubusercontent.com/4141670/233225024-262e7cc7-3b42-40ba-8a1c-9217d964af59.png">

Things to explore:
- Does `coforall` instead of `forall` make a difference? I expect not, but `forall` is the path less travelled, if any.
- Is the behavior same with arbitrarily long kernel executions? Some tasks might stall a bit more to reach the kernel launch code. That doesn't mean that it is not an issue, but a different one than some sort of inadvertent serialization/synchronization.
- Is the behavior same with AMD? There could be two main sources for this:
  - Some sort of serialization or contention at Chapel tasks level, which would also impact AMD
  - A similar problem but in how we interact with the CUDA Driver API or how we configure it, which shouldn't impact AMD (I say shouldn't because the HIP layer was implemented pretty similarly to the CUDA layer, so it might have inherited the same issue, if there is one)

**Comment by tcarneirop** [comment]
Hello Engy,

in this case, maybe I said wrong --

In 30% of the executions this issue happens.

Em qui., 20 de abr. de 2023 às 02:12, Engin Kayraklioglu <
***@***.***> escreveu:

**Comment by bradcray** [comment]
Looking at this briefly today, I wanted to mention that it feels similar to the performance bug in https://github.com/chapel-lang/chapel/issues/22132 where some locales were gated by other locales' ability to service their tasks.  I can't think of any reason that that would be a factor for GPU-based computing, but wanted to mention the similarity just in case it led to any "Aha!" moments.

**Comment by tcarneirop** [comment]
As soon as I come back from my holidays I'll add some timers to verify if the slowdown comes from the CPU or GPU part of the code.

**Comment by tcarneirop** [comment]
I git pull from the main this week and it looks like the issue is no longer there

**Comment by bradcray** [comment]
@e-kayrakli : Given Tiago's comment, is there value in keeping this issue open?  (i.e., are the directions mentioned in the OP things you wanted to look into in any case?)

**Comment by e-kayrakli** [comment]
Thanks for checking @tcarneirop, closing.
