### ISSUE TITLE
Request to join vcpkg

### ISSUE THREAD

**Issue by RainbowTaro2022** [chapel-lang/chapel#22133]
我看到你们是编程语言，我觉得会对vcpkg有所帮助，求加入vcpkg

**Comment by bradcray** [comment]
Since nobody has stepped in to tell me I'm wrong about vcpkg being for C++ libraries, and since we are not a C++ library, I'm closing this.  If someone has information suggesting I'm wrong in my interpretation of Chapel's suitability within vcpkg, please comment here and we can re-open this.
