### ISSUE TITLE
Limit `extern` blocks to module scope

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#22150]
While experimenting with `extern` blocks yesterday, I was surprised to find that, wherever they are defined, the symbols they define are made available at module scope.  This matches what the documentation advertises, but still seems at odds with other elements of the language with respect to lexical scoping.  In this issue, I'm suggesting that we limit extern blocks to module scope, at least for the time being.  Alternatively / longer-term, we could look into supporting them at local scope and having the symbols they introduce be contained within that scope as well (I'm not sure whether the choice of global scope today is one of expediency, or whether something about the way we leverage clang essentially requires it).

Here's an example that demonstrates this:

```chapel
proc bar() {
  extern {
    #include <stdio.h>
    extern void foo(void);
    void foo(void) {
      printf("In foo()\n");
    }
  }
}

foo();
```

**Comment by bradcray** [comment]
I labeled this 2.0 because I think people could interpret the documentation as saying that the current behavior is as expected.  An easy fix for 2.0 would be to update the documentation and just call this a bug, but I suspect that the fix for issuing an error would be quite straightforward as well, hopefully particularly with dyno owning the front-end.

**Comment by mppf** [comment]
Because it was easy/fun I went ahead and prototyped adding such an error in https://github.com/chapel-lang/chapel/pull/22202

**Comment by bradcray** [comment]
Great, thanks Michael!
