### ISSUE TITLE
Provide atomic operation wrappers to be used in GPU kernels

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#22155]
Spin-off from https://chapel.discourse.group/t/mixing-atomic-add-with-non-atomic-read-and-towards-gpu-atomics/21350

This issue asks for a short-term solution for atomics support in GPU kernels. Particularly, wrapping functions like `atomicAdd` via a standalone function in the GPU module would go a long way for supporting different idioms. Note that, what those functions will provide is atomic operations on non-atomic types. We have a general desire to support that and vice versa in the language. But that's a post 2.0 effort and we should not wait for that. Maybe what we learn from GPU programming can help steer the design for that feature down the road. @ronawho will capture his thoughts on the general matter soon.

Another related question in my mind is: what does/should happen with `atomic` types in GPU kernels as they exist today?

**Comment by stonea** [comment]
This PR implements atomic wrapper functions: https://github.com/chapel-lang/chapel/pull/22241
