### ISSUE TITLE
[BigInteger module] cmp and cmpabs argument name

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#22161]
While the whole BigInteger module might not get stabilized before 2.0 due to running out of time, there are key aspects of it we're going to prioritize getting in.  One of those key aspects is `cmp` and `cmpabs`.

1. What is the API being presented?

    `cmp` and `cmpabs` are defined like this:
<img width="378" alt="Screen Shot 2023-04-25 at 9 50 16 AM" src="https://user-images.githubusercontent.com/2454710/234347438-d72ccd0a-b8e6-4f58-8e24-4f08215c6688.png">

Of particular note for this discussion is the argument name `b`.  I believe this is because the argument is the second involved in the comparison, as other functions in this module use `a` and `b` as the argument names.

   - How are they intended to be used?
      - They are used for comparing the `bigint` used as the `this` argument to a second `bigint`, the `b` argument, to determine which is larger or if they are the same.  This is useful for things like sorting and priority queues.

   - How are they being used in Arkouda and CHAMPS?
      - They are not used in Arkouda
      - They are not used in CHAMPS

2. What's the history of the feature, if it already exists?
    They are based off `mpz_cmp*` and `mpz_cmpabs*` in the GMP library: https://gmplib.org/manual/Integer-Comparisons.  Those functions use `op1` and `op2` for the argument names, but since the first argument would be named `this` in our version, using `op2` for the other might look a little weird.  They've been in the current form mostly unchanged since they were first added.  The type was originally defined in the GMP module as a class in 2012, extending the GMP support to include the type which was more Chapel-like.  `cmp` itself as a name is also pretty similar to the assembly instruction of the same name.

3. What's the precedent in other languages, if they support it?
     a. Python
         - Uses `x` and `y` for the names ([cmp link](https://gmpy2.readthedocs.io/en/latest/mpfr.html#gmpy2.cmp), [cmpabs link](https://gmpy2.readthedocs.io/en/latest/overview.html#gmpy2.cmp_abs))
     b. C/C++ (see GMP library above)
     c. Rust
         - Uses `self` (`this` equivalent) and `other` ([link to Rust doc](https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html#tymethod.cmp))
     d. Swift
         - The SwiftMP package doesn't seem to provide `cmp`, only the operator versions.
     e. Julia
         - Julia seems to use `a` and `b` ([link to Julia source code](https://github.com/JuliaLang/julia/blob/master/base/gmp.jl#L238))
     f. Go
        - Go seems to use `x` and `y` ([link to Go code](https://go.dev/misc/cgo/gmp/gmp.go))

4. Are there known Github issues with the feature? Issues posted by users are most relevant, but issues encountered by developers trying to use the feature are also valuable.
    - Didn't see any

5. Are there features it is related to? What impact would changing or adding this feature have on those other features? Others features can live in the same module, but they can also live in other modules (e.g. a find method on arrays should keep the find method on strings and bytes in mind; the interface for maps should keep in mind other collection types likes lists, sets, heaps and arrays, etc.)
    - They're used to implement the comparator operators on the bigint type (e.g. `<`, `>=`, etc).  The argument names are similar to a lot of other functions in the bigint module (see the API section above).

6. How do you propose to solve the problem? Try to have multiple ideas and a recommendation of what we should do.
  
### Option 1: Rename it to `other` (this is my preferred option)
    - Pros:
      - Matches Rust
      - Clearly indicates its role in the call
      - Doesn't rely on a (missing) argument name to make sense
      - We already use `other` as an argument name for 112 functions.
        - Around half of those are in `init` or `init=`, but the other half are named functions.  Not all of these functions are 2.0 stabilized
        - These uses are spread across 37 modules, showing broad leaning toward this name when appropriate.
        - I don't have data on when we use something else instead (and `a`/`b` are pretty annoying to search for)
    - Cons:
      - Doesn't currently match the rest of the BigInteger module (but we could change that)
      - Would involve updating the function

### Option 2: Leave it as is
    - Pros:
      - Less work
      - Matches Julia
      - Consistent with rest of BigInteger module
    - Cons:
      - Not descriptive of its role in the function call
      - No visible "a"
      - Could be mistaken as using a name to reflect the type "bigint", even though all overloads with various types use the same argument name

### Option 3: Rename it to `y`
    - Pros:
      - Matches Python and Go
    - Cons:
      - Would involving updating the function
      - No visible "x"
      - Doesn't currently match the rest of the BigInteger module (but we could change that)

**Comment by bradcray** [comment]
I'm not particularly wild about `b` or `y`.  I'm OK with `other` (though I think `that` is a cuter counterpart to `this` while also being more succinct).  If I were on a desert island, I probably would've called it `x`.

If we had the (proposed but not yet designed or implemented) feature to be able to declare an argument as not being able to be mentioned by name at the callsite, I'd probably use it here (in which case, this decision would go away since we could change it at any time without breaking code).
