### ISSUE TITLE
BitOps.clz not leveraging optimal intrinsic

### ISSUE THREAD

**Issue by kwaters4** [chapel-lang/chapel#22171]
### Summary of Problem
I am not sure if this is due to the build process that I am using, but I have found some performance issues with the "count leading zeroes" ```BitOps.clz```function in the BitOps module. I have a suspicions something similar is occurring with and other functions in the BitOps library. I am still working on that.

I was looking deep into ```chpl-bitops.h``` and have not finished dissecting it just yet, but I think there are performance issues as shown below. I will continue looking at the issue, but enough information is here to reproduce the problem. There are some notes mentioning being off by a factor of 2 in the software implementation. It may be a simple as a build issues on my part, outside of having the correct ```CHPL_TARGET_ARCH``` and ```CHPL_TARGET_CPU``` set correctly I am not sure what the next step would be.

To show this I made a small basic benchmark. I used the BitOps module in Chapel and called into C to compare it to ```_lzcnt_u64```. The ```_lzcnt_64``` instruction along with many the Bit Manipulation Instruction sets should be available to reproduce on most modern x86 hardware I believe. I have looked at the C code standalone and found the ```lzcnt``` instruction, but I could not find it in the Chapel assembly. I felt like I should have found it within in ```extern``` function, but I was unable to find it.

### Steps to Reproduce

**Source Code:**

clz.chpl (Main Chapel Program)
```chapel
import BitOps;
require "clz.c";
use Time;

extern proc c_clz(iterations:int);

proc chapel_clz(iterations) {

    var x : uint;
    for i in {0..iterations} {
        x += BitOps.clz(i);
    }
    writef("%i\n", x);
}

proc main() {
    var chapel_time = new stopwatch();
    var c_time = new stopwatch();

    var iterations:int = 10000000;

    chapel_time.start();
    chapel_clz(iterations);
    chapel_time.stop();

    c_time.start();
    c_clz(iterations);
    c_time.stop();

    writeln("Chapel : ", chapel_time.elapsed(), " seconds");
    writeln("C      : ", c_time.elapsed(), " seconds");
}
```

clz.h (C header)
```C
#include <x86intrin.h>

void c_clz(int iterations);

```

clz. c (C function)
``` C 
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>

#include "clz.h"

void c_clz(int iterations) {

    int i;
    uint x = 0;
    for (i = 0; i <= iterations; i++) {
        x+= (_lzcnt_u64(i));
    }
    printf("%i\n", x);
}
```

**Compile command:**
chpl clz.chpl clz.c clz.h --fast

**Execution command:**
./clz. -nl 1

### Output
The values of the evaluations come first with the times of the Chapel and C functions.
```
416777255
416777255
Chapel : 0.004536 seconds
C      : 0.001871 seconds
```

### Configuration Information

- Output of `chpl --version`:
 ```
 chpl version 1.30.0
  built with LLVM version 14.0.6
Copyright 2020-2023 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
```

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp *
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: system
CHPL_AUX_FILESYS: none
```

**Comment by bradcray** [comment]
@kwaters4 : I'm not all that familiar with the BitOps module, and the developer who probably knows it best is out sick today.  Here's a quick test I did locally to bring myself a little bit up to speed:

1) I shortened your test down to:

```chapel
import BitOps;

extern proc c_clz(iterations:int);

proc chapel_clz(iterations) {

    var x : uint;
    for i in {0..iterations} {
        x += BitOps.clz(i);
    }
    writef("%i\n", x);
}


var iterations:int = 10000000;
chapel_clz(iterations);
```

2) I made the following changes to `runtime/include/chpl-bitops.h`:

```diff
diff --git a/runtime/include/chpl-bitops.h b/runtime/include/chpl-bitops.h
index b2fe2ad2b4..7c34750f1d 100644
--- a/runtime/include/chpl-bitops.h
+++ b/runtime/include/chpl-bitops.h
@@ -109,10 +109,12 @@ MAYBE_GPU static inline uint32_t chpl_bitops_clz_32(unsigned int x) {
 
 MAYBE_GPU static inline uint64_t chpl_bitops_clz_64(unsigned long long x) {
 #if !defined(CHPL_BITOPS_C) && (RT_COMP_CC & (~RT_COMP_PGI))
+#warning "Using intrinsic version of clz_64()"
   // - Assumes 'long long's are 64bit
   // - Same as above, __builtin_clzll(0) is undefined, return 64 when 0
   return x ? __builtin_clzll(x) : 64;
 #else
+#warning "Using C version of clz_64()"
   // - This works the same as for 32bits, we just need one more shift. See above
   //   for an example.
   x |= (x >> 1);
```

3) I compiled the program and got:

```chapel
/path/to/chapel/runtime/include/chpl-bitops.h:112:2: error: "Using
      intrinsic version of clz_64()" [-Werror,-W#warnings]
#warning "Using intrinsic version of clz_64()"
 ^
```

So that's a little bit reassuring.  A few other notes:
* I didn't use any compiler flags like `-O` or `--fast`
* I do have `CHPL_TARGET_ARCH` set to `x86_64` and `CHPL_TARGET_GPU` set to `native`, but looking at the sources, I'm skeptical either of those is relevant here
* I'm using the C back-end

If you're up for it before someone more knowledgeable chimes in, it might be interesting to have you apply the same patch as above and see which branch is taken for your code.

**Comment by kwaters4** [comment]
@bradcray Thanks I will take a look at it soon again. I was not sure if I should label the issues as "best" intrinsic or no intrinsic. The performance delta is concerning me.

**Comment by bradcray** [comment]
Yeah, that's where I was about to confess the limits of my knowledge as well:  Is there a difference between `_lzcnt_u64` and what we'll get from `__builtin_clzll(x)`?  I don't know and may look into this more tomorrow if someone more expert doesn't swoop in.  Meanwhile, it's dinnertime here.  :)

**Comment by jabraham17** [comment]
> Is there a difference between `_lzcnt_u64` and what we'll get from `__builtin_clzll(x)`

`_lzcnt_u64` is a vendor specific intrinsic (in this case, Intel) which always will emit the `lzcnt` instruction. If the CPU does not support it or the proper compilation flag isn't passed, it will fail to compile. `__builtin_clzll(x)` is a compiler builtin which will compile to something no matter the arguments. On x86 without enabling the `lzcnt` feature, it will emulate the instruction. Enabling the feature instructs the compiler that it can safely emit `lzcnt`. 

As a test, I can enable the feature for a specific function (this is clang specific, but there is something similar for gcc)

```c
#pragma clang attribute push (__attribute__((target("lzcnt"))), apply_to=function)
MAYBE_GPU static inline uint64_t chpl_bitops_clz_64(unsigned long long x) {
#if !defined(CHPL_BITOPS_C) && (RT_COMP_CC & (~RT_COMP_PGI))
...
#endif
}
#pragma clang attribute pop
```

This does result in `lzcnt` being emitted. This can also be done at the command line on a per file basis with `-mlzcnt`.


While I am here, I will note that if this is an issue with `lzcnt`, there is likely similar issues with the other builtins like `__builtin_popcount`, which requires `-mpopcnt`.

**Comment by kwaters4** [comment]
@bradcray I see similar error message as you, good start.

@jabraham17 I added the ```#pragma``` statement, recompiled with the same ```chpl clz.chpl clz.c clz.h --fast``` and did an ```objdump -S ``` on the chapel executable and do not see the ```lzcnt``` instruction. Could you provide a few more details in case I am missing something else? Thanks!

Are you seeing the convergence of the performance as well for your fix? 

Exploring my options here for a short-term and long-term solution. The easiest and hacky solution right now is to write C-extern function and use the intrinsic in the C-code as is done in the issue example. Is the reasonable to ask for a Chapel BitOps in identifying the specific instruction set and enabling a more granular set of optimizations? 

I am not sure what the best path forward is, but wanted to start the brain storm.

**Comment by bradcray** [comment]
I view the role of the `BitOps` module as being to map these down to efficient implementations, so I think it is definitely reasonable to ask for and expect the best performance.  We initially took it off the Chapel 2.0 stabilization list due to fear that it was not doing so and concern that we didn't have the time to get it over the hump.  This issue will be a good motivator for us to dig into its performance more, where my hope is we can change our code and Makefiles to "do the right thing" without the user being any the wiser.  I think the immediate next step is to try and get your observations and Jade's into sync.  But if we could then use those observations to improve the routines and Makefiles for 1.31, that would be ideal.

**Comment by jabraham17** [comment]
When I compile without `--fast`, `lzcnt` is emitted. In this case, the C code errors with `always_inline function '_lzcnt_u64' requires target feature 'lzcnt', but would be inlined into function 'c_clz' that is compiled without support for 'lzcnt'`. This hints to me that `--fast` is enabling `-mlzcnt` somewhere which may be useful information when fixing this. I was able to test without `--fast` by using `--ccflags='-mlzcnt'`. 

 Compiling with `--fast` does not emit `lzcnt` for the Chapel code. However, If I removed `main()` from the code it does generate`lzcnt`. But with or without `lzcnt` the performance for the Chapel code stays the same. I am not sure why having an explicit `main` changes the way the code is optimized, I am hoping someone can answer that

```chapel
import BitOps;
require "clz.c";
use Time;

extern proc c_clz(iterations:int);

proc chapel_clz(iterations) {
    var x : uint;
    for i in {0..iterations} {
        x += BitOps.clz(i);
    }
    writef("%i\n", x);
}
var chapel_time = new stopwatch();
var c_time = new stopwatch();

var iterations:int = 10000000;

chapel_time.start();
chapel_clz(iterations);
chapel_time.stop();

c_time.start();
c_clz(iterations);
c_time.stop();

writeln("Chapel : ", chapel_time.elapsed(), " seconds");
writeln("C      : ", c_time.elapsed(), " seconds");
```

As an interesting side note, I noticed that the C code is using `int`, which on my test machine is 32 bits and generates the `lzcnt` using 32 bit registers. Changing the does have an affect on the performance. Increasing to 64 bits for the C code slows it down to the original Chapel version. Forcing the Chapel version to use 32 bits does speed it up, but only slightly.

```
Chapel 32: 0.00824 seconds
Chapel 64: 0.009381 seconds
C 32     : 0.003969 seconds
C 64     : 0.009377 seconds
```

**Comment by jabraham17** [comment]
Following this up, changing the Chapel code to the following gives comparable performance for both Chapel and C.

```chapel
proc chapel_clz(iterations) {
    type t = iterations.type;
    var x : uint(numBits(t));
    // var x : uint;
    for i in {0..iterations} {
        x += BitOps.clz(i:t);
    }
    writef("%i\n", x);
}
```

And now when compiled with `--fast` (with and without the explicit `main()`) I get:

```
Chapel 32: 0.003783 seconds
Chapel 64: 0.009401 seconds
C 32     : 0.003714 seconds
C 64     : 0.00939 seconds
```

My assumption is that the conversion between int(32) and int(64) was slowing down the Chapel code.

When compiling with an explicit `main()`, I still do not get the `lzcnt instruction`, but I get the same performance. From what I can tell in the assembly, the compiler in both cases is vectorizing the loop and is emulating `lzcnt` with SIMD instructions. Running in a debugger with a breakpoint on the `lzcnt` instructions shows that it is only executed once and that the majority of the computation is done in vectorized code.

**Comment by kwaters4** [comment]
> As an interesting side note, I noticed that the C code is using `int`, which on my test machine is 32 bits and generates the `lzcnt` using 32 bit registers. Changing the does have an affect on the performance. Increasing to 64 bits for the C code slows it down to the original Chapel version. Forcing the Chapel version to use 32 bits does speed it up, but only slightly.

That is the user error I was looking for, I see similar performance when I give the right type (either 32 or 64 bit here) to the variable ```i``` in the C code example. Thanks for working through that with me, sorry about the mistake! 

This something I been stumbling into a bit with the C-interoperability. Silly mistakes where:
```Chapel
var c: uint; //Chapel
```
is not the same as
``` C 
c: uint; //C
```
