### ISSUE TITLE
Compiler Internal Error: AST-DEC-YPE-0246 chpl version 1.30.0

### ISSUE THREAD

**Issue by kwaters4** [chapel-lang/chapel#22186]
### Summary of Problem
Issue when using full name for CTypes in an ```extern proc``` (i.e. ```CTypes.c_ptr```). This problem does not exist if the user uses ```use CTypes``` and only uses ```c_ptr``` in the extern proc. 

ATO is currently running 1.29.0, but the same internal error was discovered in 1.30. Please let me know if any more information is required.

### Steps to Reproduce
[ATO Link](https://ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuhY3QzNzC_KLShScQyoLUoutubhKgLRCSWpxSXyJgq1CaWZeiYaZiaY1V2pFSWpRnkJBUX6yQnI8SIFGohVUm15yfEFJkQZElyZQMcRwqB0wuwA)
**Source Code:**

```chapel
import CTypes;

type test_t = uint(64);
extern proc c_test(a: CTypes.c_ptr(test_t));
```

**Compile command:**
chpl foo.chpl

**Comment by bradcray** [comment]
`c_ptr` is a slightly special type in Chapel, as currently implemented, and I wonder whether this might be the reason for the bug.  Thanks for reporting it, and please let us know whether this is a blocker for you, or whether the workaround above is sufficient for now.  Note that a slightly more "locked down" workaround (in terms of namespace) would be to `import CTypes.c_ptr;` like so:  [ATO](https://ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuhY3QzJzC_KLShScQyoLUov1kuMLSoqsubhKgDyFktTikvgSBVuF0sy8Eg0zE01rrtSKktSiPIWCovxkheR4kAKNRCsFsC4NiHJNoCqI2VArYFYBAA)

```chapel
import CTypes.c_ptr;

type test_t = uint(64);
extern proc c_test(a: c_ptr(test_t));
```

**Comment by kwaters4** [comment]
This was friendly reporting. I try to only use import statements, but with CTypes it can make sense to only use ```use CTypes```. All CTypes are prefaced with ```c_``` so it is straightforward where they are coming from.

**Comment by jabraham17** [comment]
Closing this as it was resolved by #22324, the code in the OP now works on main.

**Comment by lydia-duncan** [comment]
@jabraham17 - it doesn't look like #22324 added a test or resolved a future.  We should have a test to lock in that the behavior doesn't regress in the future

**Comment by jabraham17** [comment]
https://github.com/chapel-lang/chapel/pull/24329 adds a test to lock this in
