### ISSUE TITLE
Should our distributions like Block, Cyclic, etc. support a `createDistribution()` factory?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#22219]
In recent work in #21567, @stonea renamed the long-term Block/Cyclic routines from `new*()` names to use `create*()` instead.  This has been nice in that it's let me write more and more code avoiding `dmapped` in many cases, which is a language feature that I feel a bit "meh" about when it comes to 2.0 stabilization.

In writing recent tests that require distributions that are independent of domains and arrays, I realized that a routine that would flesh out this story well would be `Block.createDistribution()` (or `createDist()` or `createDomainMap()`), which would give me another chance to avoid `dmapped` in addition to the even less desirable `dmap` type.

Having such routines seems as though it could permit us to mark `dmapped` and `dmap` as unstable for Chapel 2.0, and to lean much  more heavily on the factory methods, buying us more time to wrestle with `dmap[ped]`.

**Comment by bradcray** [comment]
Also tagging @vasslitvinov on this, as I believe he's leading a deep-dive on questions related to this in the near future.

**Comment by bradcray** [comment]
A related idea we discussed was just to make the distribution types, like `Block` and `Cyclic` into records rather than classes, which would eliminate (or possibly reduce) the need for this issue's feature request.  That desire is captured in https://github.com/chapel-lang/chapel/issues/22428 and I've got a start on the implementation in https://github.com/chapel-lang/chapel/pull/22657

**Comment by vasslitvinov** [comment]
The set of 2.0-stable factory functions is discussed in #22427.

**Comment by lydia-duncan** [comment]
@bradcray - I believe you've made a lot of progress on making the distribution types into records.  Does that mean this issue can be closed?

**Comment by bradcray** [comment]
Yes, I think that'd be reasonable.  More needs to be done to get all distributions to records, but I think we've got the main 2.0-related ones done, and the need for this factory definitely goes away with these changes.  Thanks!
