### ISSUE TITLE
Dyno's filter and exclude flags can result in broken lookup for identifiers

### ISSUE THREAD

**Issue by DanilaFe** [chapel-lang/chapel#22217]
Consider the following piece of Chapel code:

```Chapel
module TopLevel {
    module XContainerUser {
        public use TopLevel.XContainer; // Will search for public, to no avail.
    }
    module XContainer {
        private var x: int;
        record R {} // R is in the same scope as x so it won't set public

        module MethodHaver {
            use TopLevel.XContainerUser; // (*) look at me!
            use TopLevel.XContainer;
            proc R.foo() {
                return x;
            }
        }
    }
}
```
The general gist of the lookup process for `x` will be as follows:

* the scope of `R` is searched with `{METHODS_OR_FIELDS}`
* The scope of `R`’s parent (`XContainer`) is searched with `{METHODS_OR_FIELDS}`
    * At this point, the search system records that `XContainer` has been searched with `{METHODS_OR_FIELDS}`, and will limit subsequent searches to `{NOT_METHOD_OR_FIELDS}`.
* The scope of `XContainerUser` is searched with `{PUBLIC}`
* The scope of `XContainer` is searched with `{PUBLIC}` (via the `public use`)
    * At this point, the “exclude flags” indicate that we are searching for `{NOT_METHOD_OR_FIELD}`
    * The search system records that `XContainer` has been searched with restrictions `{METHODS_OR_FIELDS} ∩ {PUBLIC} = ∅`, aka no restrictions.
    * So the scope resolver thinks `XContainer` has been searched completely
* The scope of `XContainer` searched for with no filters via the second use; but the stored filter is {}, so the lookup returns early, not finding `x`.

This leads to the paradoxical observation that adding an empty `use` statement (indicated by the `(*)` in the above example) hides `x` from the results of the search. 

We were previously aware that the include/exclude flags are an approximation; the following comment describes a very similar setup.

https://github.com/chapel-lang/chapel/blob/7eb3be964b7792eb5fa7c0ceca8280e2b38adf14/frontend/lib/resolution/scope-queries.cpp#L937-L947

However, until now, we believed this wasn't an issue. However, this bug confirms that the flags lead to issues in actual code.

**Comment by mppf** [comment]
Maybe we just need basically a vector of flag combinations that have been searched & when searching we rule out anything that would have been found by any of the flag combinations in the vector? Maybe we can have the vector have 1 element in common cases when we can use `|` etc to represent what was searched in terms of a bit set?

**Comment by DanilaFe** [comment]
My only problem with this is that BorrowedIdsWithName and OwnedIdsWithName will need to have a reference to this vector, which feels quite expensive. But this is the idea that I had, too.

**Comment by DanilaFe** [comment]
This is tested as of #22220, and works fine.
