### ISSUE TITLE
Replace `assertOnGpu` with first-class Chapel features

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#22268]
Spun off from @stonea's [comment](https://github.com/chapel-lang/chapel/pull/22172#discussion_r1185295947):

> - For a compile time check make assertOnGpu an attribute on the loop. Maybe something like @assertGpuEligible or @assertGpuizable.
> - Tell users if you want a runtime check to do: assert(here.isGpu()) and get it so that here.isGpu() doesn't make things not GPUizable.

I like both ideas and would like us to move towards those. Commenting on them individually:

> - For a compile time check make assertOnGpu an attribute on the loop. Maybe something like @assertGpuEligible or @assertGpuizable.

I like the term "gpuizable", but I may not have enough support :) `assertGpuEligible` is definitely a viable alternative. One interesting question is whether there should be a way to make this a compile-time warning only by passing an argument. A related sub-proposal would be:
- add `--report-gpu` to the compiler, which is something we discussed already.
- also add `@reportGpu` and (maybe an inverse like `@noReportGpu`) to selectively report compiler's GPU transformation analysis for particular loops
- make `assertGpuizable` always assert at compile time

Another interesting question for this potential annotation is whether you can use it on any statement or subroutine. You can put it on a `proc` to make sure that there is nothing in the body that breaks GPU offload, for example. It is a bit tricky if the proc isn't called from an already gpuized loop. Though I think it can be an interesting idea to explore.

> - Tell users if you want a runtime check to do: assert(here.isGpu()) and get it so that here.isGpu() doesn't make things not GPUizable.

This is as elegant as they come.

But as Andy alluded to, `here` throws off GPU transformations today (https://github.com/chapel-lang/chapel/issues/22147). It might also be ideal if https://github.com/chapel-lang/chapel/issues/18024 is addressed first so that the `assert(here.isGpu())` can be put inside a param conditional. Note that `assert` is just a function in Chapel as opposed to C's macro-based assert. That implies that its arguments will be evaluated even if the assertion is disabled internally inside the `assert` call. That argument evaluation could throw off GPU performance significantly in some cases.

**Comment by e-kayrakli** [comment]
Recording a slack discussion with @stonea -- It might be interesting to think about a `forceNoGpuization` or something that would thwart an otherwise GPU-eligible loop's gpu execution.

**Comment by e-kayrakli** [comment]
I went back-and-forth whether we should keep this open or close it. Because `@assertOnGpu` is pretty first-class. But, I am keeping it open as we still can use better execution time assertions than the assertOnGpu attribute.

**Comment by stonea** [comment]
> I went back-and-forth whether we should keep this open or close it. Because `@assertOnGpu` is pretty first-class. But, I am keeping it open as we still can use better execution time assertions than the assertOnGpu attribute.

It seems like maybe there's more work you think we should do, but it's a little unclear what that should be just from reading the OP given that we now have `--report-gpu` and `@reportGpu`.

(assuming the runtime assertion issue is all that remains) I'm thinking maybe we should close this issue and create a new issue that proposes:

- getting `assert(here.isGpu())` to work as a runtime check?
- removing the existing `assertOnGpu` function.

**Comment by stonea** [comment]
> but I'd expect something like that to return true inside of an `on here.gpus[0]` including inside the kernel. We also probably need... something else that would return `true` only inside a kernel.

Ah good point.  It looks like it works when on a gpu and outside a kernel today:

```
$ cat foo.chpl
config const useGpu = true;

var loc = here;
if useGpu then loc = here.gpus[0];
on loc do writeln(here.isGpu());

$ ./foo --useGpu=true
true

$ ./foo --useGpu=false
false
```

And we have an existing issue about getting `here` to work on a gpu kernel (https://github.com/chapel-lang/chapel/issues/22147). I imagine if we resolved that having `here.isGpu()` would work in the kernel as well.

> I think you mean the function that Daniel deprecated already, right? I consider it "removed" anyways, it'll go away as part of the standard deprecation process.

Oh, I didn't realize it was deprecated. Ok then yes that part is already in motion then.

I almost wonder if we just keep `assertOnGpu` around as a true "assert I'm in a gpu kernel" runtime check, and maybe renaming it to something like `assertInKernel` or `assertOnGpuDevice`? Alternatively, maybe we could have a `here.isOnDevice()` or `here.isInKernel()` function? Probably I should fork another issue to discuss that and then we can close this one.

**Comment by stonea** [comment]
Ok, I've created <https://github.com/chapel-lang/chapel/issues/23688> and I'll close this issue (reopen if you think I'm being too hasty).
