### ISSUE TITLE
Better error message when `createSharedArray` is used with a type that doesn't have `numBytes` overload

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#22309]
```chapel
module Test {
  use GPU;

  record myRecord {
    var x: real(32);
    var y: real(32);
  }

  proc main() {
    on here.gpus[0] {
      foreach i in 0..<1024 {
        ref A = createSharedArray(myRecord, 16).deref();
      }
    }
  }
}
```

gives

```
$CHPL_HOME/modules/standard/Types.chpl:763: In function 'numBytes':
$CHPL_HOME/modules/standard/Types.chpl:763: error: unresolved call 'numBits(type myRecord)'
$CHPL_HOME/modules/standard/Types.chpl:711: note: this candidate did not match: numBits(type t)
$CHPL_HOME/modules/standard/Types.chpl:711: note: because where clause evaluated to false
$CHPL_HOME/modules/standard/Types.chpl:763: note: other candidates are:
$CHPL_HOME/modules/standard/Types.chpl:715: note:   numBits(type t)
$CHPL_HOME/modules/standard/Types.chpl:717: note:   numBits(type t)
```

This is because `createSharedArray` requires knowing the size of the allocation at compile-time. In turn, this comes from inherent GPU requirements. So, that's not something we are planning to address, at least in the short term.

However, we should provide a more helpful error message in this case.

**Comment by DanilaFe** [comment]
We can probably use reflection and `canResolve` (or something -- I know we have a function like this!) to make the overload nice. Let me see if I can't come up with something nice :)

**Comment by DanilaFe** [comment]
Per Andy's recommendation, I've opened https://github.com/chapel-lang/chapel/issues/22368 to track being able to use `createSharedArray` without needing a `numBits` implementation.
