### ISSUE TITLE
Chapel program hangs, sometimes.

### ISSUE THREAD

**Issue by kwaters4** [chapel-lang/chapel#22331]
### Summary of Problem
I do not have a reproducer yet, but this has occurred to me on and off when running Chapel programs and I wanted to see if this was affecting other users as well. When submitting a Chapel program via slurm (I believe this has happened to me locally as well) the program will "complete" and then hang and not finish breaking down and the terminal is still busy. This has occurred in select programs where I have been able to toggle it on and off using ```exit()```, so I believe some specific is happening.

This easy solution is placing an ```exit()``` at the end of ```proc main()```, but I am curious if this is behavior that has been seen before by others or if I should pursue a definitive reproducer. I am initially looking for if anyone has an "easy" suggestion/solution for what I am doing wrong.

**Comment by jhh67** [comment]
Please post the output of `printchplenv`. Thanks.

**Comment by bradcray** [comment]
This does not sound familiar to me offhand.  By any chance does the program contain `begin` statements?

**Comment by kwaters4** [comment]
It appears to be a user error, still diagnosing it, but it is on my end, sorry about that. Just wanted to get an initial impression.

**Comment by ronawho** [comment]
FYI we've had the "opposite" problem, where calling `exit(0)` could hang under ugni (https://github.com/chapel-lang/chapel/issues/7521) but I don't know of any regular instances where normal termination/shutdown would hang.

Even if it's user error, feel free to bounce ideas off us here. The configuration information (even just broad strokes if you can't share chplenv) and whether you're using any begins would be helpful.
