### ISSUE TITLE
Should we deprecate support for casts from class variables to `c_void_ptr`?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#22341]
In a recent discussion on the `CTypes` subteam, we have agreed to have `c_ptrTo()` on a class variable return a pointer to the object on the heap to be consistent with its use with other types (which is to say, it returns the address of the "logical" value of the variable where `c_addrOf()` returns the literal address of the variable itself).

At present, this can also be accomplished by using a cast to `c_void_ptr`, [as shown here](https://ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuhY3L5YWpyo4h1QWpBZbcyXnJBYXKzgrVNdycZUlFikkK9gq5KWWK-SX56WmKDhraFqDhVOgwsUZiUXI4qlQ8dK83MS8xHRkqTSgVLJeUn5RUX45SKy8KLMkNSdPI9kqOb4sPzMlvqCkCEk4BbtwKnbhNBRhiMeg_oP5EwA):

```chapel
use CTypes;

class C {}

var c = new owned C();
var d = new shared C();
var e = new unmanaged C();
var f = c.borrow();

writeln(c:c_void_ptr);
writeln(d:c_void_ptr);
writeln(e:c_void_ptr);
writeln(f:c_void_ptr);
```

In the discussion, we wondered whether we should deprecate the cast-based form.  Some arguments for doing so would be:

* it represents two ways of doing the same thing, where the cast-based approach is arguably a bit more obscure
* if one wanted a `c_void_ptr` pointing to their class `c`, they could use `cPtrTo(c): c_void_ptr`
* the cast is also a little "fancy" in that it's not just taking the class variable (which may be a wide class reference or the record involved in managing an `owned` or `shared`) and interpreting it as a `void*`, but is digging into the implementation of the variable and pulling out the appropriate pointer field, returning that as a `void*`.  I.e., its implementation is a bit fancier than traditional value-based casting.

**Comment by mppf** [comment]
I think it's important to be able to get a `c_void_ptr` pointing to a class instance. However it's not important to me how it is done. `c_ptrTo(myObject)` seems reasonable to me as does `myObject:c_void_ptr`. I am OK with deprecating the cast form if that's what others prefer.

**Comment by jabraham17** [comment]
I would advocate for deprecating the cast for the stated reasons. Particularly that it feels a little hand wavy and does more than a user might expect a cast to do.

**Comment by mppf** [comment]
> the cast is also a little "fancy" in that it's not just taking the class variable (which may be a wide class reference or the record involved in managing an owned or shared) and interpreting it as a void*, but is digging into the implementation of the variable and pulling out the appropriate pointer field, returning that as a void*. I.e., its implementation is a bit fancier than traditional value-based casting.

In this way it seems very similar to a cast of `myOwnedC : unmanaged C`. I do not remember off-hand if we are keeping those, but maybe we could make it consistent between the two situations?

**Comment by bradcray** [comment]
Semi-related to this:  On Gitter this week, Tom Westerhout has been requesting the ability to pass a pointer to a Chapel class to C, and then have C pass it back to Chapel treating it as a class again.  So whatever we do here, we should be sure to retain that ability (which is what Michael was asserting above as well... not to imply in posting this that Michael's word wasn't good enough for me).

**Comment by bradcray** [comment]
I've admittedly lost track of where this stands.  Does the OP still represent the status on `main`?

I added the 2.0 label when filing this issue because if we support both ways of getting the pointer-to-object and neither generates an unstable warning, then I think we're committed to supporting both through 3.0 (?).

**Comment by riftEmber** [comment]
> Does the OP still represent the status on `main`?

Yes, but with `c_void_ptr` replaced by `c_ptr(void)`. [Your test for this behavior](https://github.com/chapel-lang/chapel/blob/main/test/classes/cast/castClassPtr.chpl) is still around locking this in for `c_ptr(void)`.

I just remembered Jade volunteered to pick up this issue as part of [their owned/shared discussion](https://github.com/Cray/chapel-private/issues/5169), so we'll probably have an answer from that.

**Comment by jabraham17** [comment]
In an offline discussion (https://github.com/Cray/chapel-private/issues/5169), we decided to deprecate the cast to void pointer in favor of just using `c_ptrTo`
