### ISSUE TITLE
comm-ofi: support registration of Chapel heap for HPC communications libraries.

### ISSUE THREAD

**Issue by jlbyrne-hpe** [chapel-lang/chapel#22384]
@jhh67 If Chapel is built with OFI support (and qthreads and jemalloc, I believe), at startup the Chapel runtime can allocate and register a heap which will contain all Chapel objects and data, allowing the most efficient RDMA possible with OFI. If the application is using an RDMA communication library itself, it is advantageous to for it to register the entire heap for its own communication and it is possible to find the size of the heap using the undocumented internal routine chpl_comm_regMemHeapInfo(). However, note the use the word "can". There are other conditions, but the most obvious reason that the runtime won't define a heap is because Chapel is running as a single locale and ordinary Chapel applications have no need for the overhead (and memory footprint) of creating a heap if they aren't going to be communicating via OFI. 

I would like be able to force the heap allocation for our use case, but there is no reason Chapel to incur the additional overhead of memory  registration if it doesn't require it. Since the heap allocation occurs before any user code is executed, either a launcher argument or environment variable would be required. Also, it would be good to document the chpl_comm_regMemHeapInfo() routine. The patch below works well enough for me at the moment, but it looks like it could easily break with a different OFI provider. More thought is required to make a solid patch.
```
diff --git a/runtime/src/comm/ofi/comm-ofi.c b/runtime/src/comm/ofi/comm-ofi.c
index d841caaf17..26a9e6bb60 100644
--- a/runtime/src/comm/ofi/comm-ofi.c
+++ b/runtime/src/comm/ofi/comm-ofi.c
@@ -2129,7 +2129,9 @@ struct fi_info* getBaseProviderHints(chpl_bool* pTxAttrsFo
rced) {
   // be sharing the node with other processes, in which case we can't size
   // the fixed heap correctly.

-  if (chpl_numNodes > 1 && envMaxHeapSize != 0 && !envOversubscribed) {
+  if ((chpl_numNodes > 1 ||
+       chpl_env_rt_get_bool("COMM_OFI_NEED_HEAP", false)) &&
+      envMaxHeapSize != 0 && !envOversubscribed) {
     hints->domain_attr->mr_mode |= FI_MR_ALLOCATED;
   }

```

**Comment by bradcray** [comment]
@jhh67 : Curious for your thoughts here.

**Comment by jhh67** [comment]
If I understand correctly, you want to:

1. Force the creation of a fixed heap when comm=ofi even when the Chapel runtime doesn't require one
2. Use a documented API to get the base address and size of the fixed heap

Assuming that's correct, I don't think either these things would be terribly difficult. The fixed-heap code is kind of convoluted but it should be doable. I'm not sure how difficult it would be with other comm layers, but it sounds like you don't need that.

**Comment by jlbyrne-hpe** [comment]
Those are my requirements. I don't see any need to support it for other comm layers at this time. I just found out the slurm plugin doesn't create CXI services for a single node job and fi_domain will fail, so you can't try to register the memory in that case and it looks like you won't since init_ofi() won't be called. The convoluted code is worrisome. 

Actually, my patch doesn't work. I foxed myself somehow.

**Comment by jhh67** [comment]
I work with those requirements. I believe if you set `SLURM_NETWORK=single_node_vni` the CXI services will be created even if you are using a single node.

**Comment by jlbyrne-hpe** [comment]
[From ALT-423](https://jira-pro.it.hpe.com:8443/browse/ALT-423) : "Try using the --network=single_node_vni option. Note, that won't work unless single_node_vni=user is set in SwitchParameters in slurm.conf"

I haven't tried yours, but the above option works on Sawmill. I'm arguing the single node case should print a warning to tell people what the fix is. I consider the behavior mysterious.

**Comment by bradcray** [comment]
@jlbyrne-hpe / @jhh67 : GC-ing mail this evening, I wanted to check in and see where this stood.  Like JohnB, is this holding you up?  Do you have a deadline you need it by?

**Comment by jlbyrne-hpe** [comment]
I have a patch I like at this point, so it isn't blocking me. I can post it as  a PR if you'd like.

**Comment by bradcray** [comment]
Thanks for the update, John.  That sounds reasonable to me, but I'll defer to @jhh67 and @ronawho to make sure it isn't wasted effort.

**Comment by jhh67** [comment]
@bradcray Where is the proper place to document the `chpl_comm_regMemHeapInfo` routine?

**Comment by bradcray** [comment]
I don't know enough about it to know the answer to that.  If we were proposing exposing it to (power) end-users, I'd think we'd want to make an unstable standard module that exposed it through a Chapel procedure with a better name, and then chpldoc that module.
