### ISSUE TITLE
Problem with array formal with generic element type

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#22450]
### Summary of Problem

It seems that it should be possible to pass an array using an instantiated type to a formal that specifies the array element type as the generic type.

### Steps to Reproduce

**Source Code:**

``` chapel
module M1 {
  record R {
    type T;
    var x: T;
  }

  proc jvp(x: [] R) {
    writeln("in jvp");
    writeln(x);
  }

  proc main() {
    var A: [1..10] R(real);

    jvp(A);
  }
}
```

**Compile command:**

```
$ chpl aa.chpl --main-module=M1
aa.chpl:29: In function 'main':
aa.chpl:32: error: unresolved call 'jvp([domain(1,int(64),false)] R(real(64)))'
aa.chpl:24: note: this candidate did not match: jvp(x: [] R)
aa.chpl:24: note: because an argument was incompatible
```

**Context:**

I'm filing this issue on behalf of @lucaferranti.

This came about in the context of changing a type from being concrete to generic. Below I show the concrete version and then a generic version using a workaround.

```chapel
module M0 {
  record R {
    var x: real;
  }

  proc jvp(x: [] R) {
    writeln("in jvp");
    writeln(x);
  }

  proc main() {
    var A: [1..10] R;

    jvp(A);
  }
}
```

``` chapel
module M2 {
  record R {
    type T;
    var x: T;
  }

  proc jvp(x: [] ?T) where isSubtype(T, R){
    writeln("in jvp");
    writeln(x);
  }

  proc main() {
    var A: [1..10] R(real);

    jvp(A);
  }
}
```

```
chpl aa.chpl --main-module=M0 # OK
chpl aa.chpl --main-module=M1 # fails to compile
chpl aa.chpl --main-module=M2 # workaround works
```

**Associated Future Test(s):**

TODO

### Configuration Information

Problem occurs on `main`

**Comment by dlongnecke-cray** [comment]
At candidate collection time, here's what `jvp` looks like:

```chapel
proc jvp(x: _array) where true && x.eltType == R(?) {}
```

I bet that's failing because `R(?) != R(real)`. We need a different operation here - what to do?

**Comment by dlongnecke-cray** [comment]
No, that's right. At candidate filtering time, `jvp` is not applicable because the `where` clause evaluation fails.

I'd like to rewrite the expression in the `where` to be something like `x.eltType == R || chpl_isInstantiationOf(x.eltType, R)`. The `chpl_isInstantiationOf` does not exist as far as I can tell, but I'd go ahead and add it or at least a primitive version of it.
