### ISSUE TITLE
make install misses c2chapel

### ISSUE THREAD

**Issue by twesterhout** [chapel-lang/chapel#22472]
### Summary of Problem

`make install` does not install `c2chapel` even if `c2chapel` has been built.

### Steps to Reproduce

If I do `configure --prefix=... && make -j` to build the compiler followed by `make c2chapel -j` and `make install`, the `c2chapel` executable is not installed.

I believe that the relevant code is here: https://github.com/chapel-lang/chapel/blob/main/util/buildRelease/install.sh#L242. `chpl` and `chpldoc` are the only binaries that get installed and they are both installed via CMake (which would not apply for c2chapel). Skimming that file further, I see no mentions of the `tools/` folder that contains the underlying Python scripts for c2chapel. In other words, I think the `tools/` folder should also be copied, but it is not.

### Configuration Information

- Output of `chpl --version`: 1.31.0 (commit 0630fe92c5416dec8236c63f6eebc1c470b5bbc3)

Pinging @bradcray and @lydia-duncan as they kindly reacted to this issue on Gitter.

**Comment by bradcray** [comment]
Oh, I misunderstood what you were saying on gitter, and thought that you were saying that `make install` was complaining in the event that `c2chapel` was _not_ built (but, like you, I didn't see it mentioned in the install.sh script, so was confused by that... probably just due to reading too fast).

@bmcdonald3 and @benharsh, I think you've done the most in-depth work with `c2chapel` over its lifetime, what are your thoughts on this, and particularly what challenges it being a python-based tool might entail?

**Comment by twesterhout** [comment]
For my use case I ended up writing a manual installation script for c2chapel. It consists of a few parts:

1. During the installation, I cannot download anything from the Internet. Feel free to ignore this part if that's not the case for you.

To prevent the creation of virtual environments, I'm doing the following:

```bash
substituteInPlace Makefile \
  --replace 'c2chapel: third-party-c2chapel-venv FORCE' 'c2chapel: FORCE'
substituteInPlace tools/c2chapel/Makefile \
      --replace 'c2chapel: c2chapel-venv $(FAKES)' 'c2chapel:'
```

but then I have to manually create the fake headers:

```bash
    pushd tools/c2chapel
    mkdir -p install/fakeHeaders
    # Instead of downloading from the internet, copy from a local folder:
    cp --no-preserve=mode -r \
      ${c2chapel-fake-headers}/utils/fake_libc_include/* \
      install/fakeHeaders/
    # This part is important!
    # Note how I'm passing utils/custom.h instead of $(PWD)/utils/custom.h, because
    # during the make install we want to be able to copy files and the symbolic link thus needs to be
    # relative.
    ./utils/fixFakes.sh install/fakeHeaders utils/custom.h
    mkdir -p install/fakeHeaders/utils
    cp utils/custom.h install/fakeHeaders/utils/
    popd
```

2. As my install step, I'm then doing the following:

```bash
    mkdir -p $out/tools/c2chapel
    cp tools/c2chapel/c2chapel* $out/tools/c2chapel/
    cp -r tools/c2chapel/install $out/tools/c2chapel/

    makeWrapper $out/tools/c2chapel/c2chapel.py $out/bin/c2chapel \
      --prefix PYTHONPATH : "${pycparser}/${python3.sitePackages}" \
      --prefix PYTHONPATH : "${pycparserext}/${python3.sitePackages}"
```

`$out` here refers to the prefix that is passed to Chapel's `./configure` as `--chpl-home=$out`. We're simply copying all the required files.
The `makeWrapper` part makes the `pycparser` and `pycparserext` available to c2chapel since we're not relying on a virtual environment.

All of this is, of course, not generic enough to be upstreamed, but I'm hoping that my investigation might help in case somebody decides to address the make install issue.

**Comment by bmcdonald3** [comment]
Thanks for the notes here, glad you were able to figure out a work around to the issue. Installing Python-based tools with `make install` is not something that anyone on our team has tackled as of yet, so the work you've done here constitutes uncharted territories for me at least and so, unfortunately, I don't have much to add at the moment. I've taken note to further investigate this.

Am I understanding correctly that you've got things working as you were hoping with your workaround for now or is this still a blocker for you? Just want to make sure you aren't being held up before we get around to implementing something akin to this in upstream Chapel.

**Comment by twesterhout** [comment]
@bmcdonald3 Thanks! And you're right, I have indeed managed to work around the issue, so it's not a blocker for me.

**Comment by bradcray** [comment]
@DanilaFe : #24492 references this issue and sounds like it addresses it, but didn't close it.  Was that an oversight, or is there still more to do here?

**Comment by DanilaFe** [comment]
I believe it was an oversight -- `make install` should put in `c2chapel` if it's invoked with `make c2chapel`.
