### ISSUE TITLE
Possible replacement operators for `proc this(...)` (take 2)

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#22510]
This issue asks roughly the same question as https://github.com/chapel-lang/chapel/issues/18263 but focusing in on `operator`-based approaches and approaches that seemed most popular on that issue (in truth, I wrote it up before remembering we had #18263, but felt the commentary on that issue was long enough that it would be daunting to tack it on there or try to retroactively edit it into the OP.  In addition, I think one of the contributions of this new issue is showing what various approaches might look like in a simple example.

Currently, Chapel provides the ability to index into / call an object by defining a method named `proc this()` on it.  The rationale for this choice was that we were defining a procedure whose behavior was like applying the parentheses/brackets to `this` directly, so we chose the name `this` both because it was a reserved word (so couldn't conflict with a user method name) and because it mnemonically sits in the position of the `this` receiver that is invoked with the call.

With the advent of operators in Chapel, it's been proposed that we should replace this procedure method with an operator instead.  The following are some potential signatures that could be used in doing so.  Each of the following lines is intended as a candidate, and I'm working under the assumption that any of these proposals would support the ability to invoke the object using either parentheses or square brackets (i.e., I'm not proposing we change that aspect of the language in considering this change).

```chapel
// imagine one of these would be defined within the context of a `record R { ... }` declaration
operator this(<args>) { ... }  // similar to what we have today, just replacing `proc` with `operator`
operator this[<args>] { ... }  // similar, but using square brackets to support the "common case" / emphasize the operator that's being defined
operator [](<args>) { ... }  // make it more like our normal operator calls where `[]` is the operator and it applies to an implicit `this` argument, making it like a normal method procedure
operator [](this: R, <args>) { ... }  // take the thing to which the brackets/parens are being applied as an explicit `this` argument
operator [](expr: R, <args>) { ... } // same as the above, but don't require / permit the expression to be named `this` but permit it to be named whatever you want
operator index(<args>) { ... }  // use another (currently) reserved word that describes the operation (could also take `this` as an explicit argument, use square brackets)
operator access(<args>) { ... }  // use some other non-reserved word that describes the operation(could also take `this` as an explicit argument, use square brackets)
```

Alternatively, here are those same overloads defined as secondary/tertiary operators:

```chapel
operator R.this(<args>) { ... }
operator R.this[<args>] { ... }
operator R.[](<args>) { ... }
operator R.[](this: R, <args>) { ... }
operator R.[](expr: R, <args>) { ... }
operator index(<args>) { ... }
operator access(<args>) { ... }
```

As a specific example, imagine a was defining a matrix record as follows:

```chapel
record Matrix {
  const m, n: int;
  var buff: [0..m*n] real;

  operator this(i: int, j: int) ref {
    return buff[i*m + j];
  }

  operator this[i: int, j: int) ref {
    return buff[i*m + j];
  }

  operator [](i: int, j: int) ref {
    return buff[i*m + j];
  }

  operator [](this: Matrix, i: int, j: int) ref {
    return this.buff[i*m + j];  // note that the 'this' would be required here, but was not above
  }

  operator [](expr: Matrix, i: int, j: int) ref {
    return expr.buff[i*m + j];  // note that 'expr' would be required here
  }

  operator index(i: int, j: int) ref {
    return buff[i*m + j];
  }

  operator access(i: int, j: int) ref {
    return buff[i*m + j];
  }
}
```

or:

```chapel
record Matrix {
  const m, n: int;
  var buff: [0..m*n] real;
}

operator Matrix.this(i: int, j: int) ref {
  return buff[i*m + j];
}

operator Matrix.this[i: int, j: int) ref {
  return buff[i*m + j];
}

operator Matrix.[](i: int, j: int) ref {
  return buff[i*m + j];
}

operator Matrix.[](this: Matrix, i: int, j: int) ref {
  return this.buff[i*m + j];
}

operator Matrix.[](expr: Matrix, i: int, j: int) ref {
  return expr.buff[i*m + j];
}

operator index(i: int, j: int) ref {
  return buff[i*m + j];
}

operator access(i: int, j: int) ref {
  return buff[i*m + j];
}
```

any of which would permit me to write something like:

```chapel
var M = new Matrix(m=5, n=10);
M[3, 5] = 2.3;
```

Breaking these questions down into options, I think the questions are:
* pass the thing being indexed in explicitly as an argument, or have it be an implicit `this` argument?
  * if passing it in, should a specific name be required, and if so, what? 
* define the operator using symbolic notation like `[]` or an identifier?
  * if an identifier, should it be `this`, `index`, `access`, or something else?
* should square brackets be used to introduce the argument list instead of parens?

**Comment by dlongnecke-cray** [comment]
I think between the three terms I like the most, `index`, `access`, and `call`, that `access` wins out because it's truly `(` or `[` neutral. If you say `index` I think of array subscripting `[`. If you say call I think of parens `(`.

However, I am really intrigued about the ideas from Swift that Michael is bringing up, particularly how the subscript operator takes in the value to set. I think this solves a longstanding problem for our collections where by returning a reference we make it very difficult to avoid causing reference invalidation.

**Comment by riftEmber** [comment]
In the [`this`/`these` design discussion](https://github.com/Cray/chapel-private/issues/5077) we decided to stick with `proc this()` as-is, not changing its name or making it an operator.
