### ISSUE TITLE
Compiler error using ```--no-dead-code-elimination```

### ISSUE THREAD

**Issue by kwaters4** [chapel-lang/chapel#22560]
### Summary of Problem
When compiling any(?) Chapel program with the ```--no-dead-code-elimination``` it produces the following error:

``` 
error: Could not find C variable none_chpl - perhaps it is a complex macro?
```

### Steps to Reproduce

**Source Code:**

```chapel
config const numMessages = 100;
forall msg in 1..numMessages do
  writeln("Hello, world! (from iteration ", msg, " of ", numMessages, ")");
```

**Compile command:**
``` chpl foo.chpl --no-dead-code-elimination```

### Configuration Information

- Output of `chpl --version`:
```
chpl version 1.30.0
  built with LLVM version 14.0.6
Copyright 2020-2023 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm *
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: unknown *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: bundled *
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled *
CHPL_HWLOC: bundled
CHPL_RE2: bundled *
CHPL_LLVM: system *
CHPL_AUX_FILESYS: none
```

**Comment by bradcray** [comment]
Thanks for reporting this Kevin.  Apparently, we **really** like eliminating dead code.  :D 

We admittedly do not have regression testing for individual flags like this, though we do test an umbrella flag (`--baseline`) that ought to include this one.  Curious that we're not seeing this failure in that mode.

Is this holding you up in any way?

**Comment by kwaters4** [comment]
I do not think it is, I am fighting an overzealous Chapel compiler trying to benchmark a function right now and I was looking through the options that I had at my disposal. I am still getting correct results, but the compiler is optimizing my benchmarking loop away, much more forcefully than the equivalent in gcc or clang (no issues there). I am not getting an apples to apples comparison.  A win for Chapel, but a loss for me. I have found a work around, but it is making me duplicate and modify code, not unreasonable the compiler is doing the right thing.

The documentation is not great and/or outdated for some of the flags, this one included. I am not sure if this is what I need or not.  Is this flag removing unreachable code, reachable ones that are not later used, or both (it appears to be both)? I am printing the variable at the end of the loop, so maybe this is not what I want? I am not sure if this would prevent the loop from being optimized away from my final Chapel binary or not. Depending on how "excited" the team is, I can try to create a reproducer.

**Comment by kwaters4** [comment]
Once I peeled back enough layers the compilers converged. There is a subtlety in the chapel compiler that is able to optimize a little more aggressively around the surrounding code. No reproducer today.

**Comment by dlongnecke-cray** [comment]
Quick rundown of what's happening here:

- An inline function returns `none`.
- During post-resolution cleanup where `nothing` values are folded away, the `return none` is not cleaned up.
- Later during inlining, the `return none` is cloned and then the `return` is folded away, leaving us just with the statement `none`.
- Normally, this statement would be code-eliminated, but here it persists until `codegen`.
- When generating the inlined block we encounter the `SymExpr*` to `none`, and try to generate it. That's when we crash.

We could potentially have `codegen` just ignore this sort of expression. We could also adjust `prune` to clean it up. Does that count as "code-elimination"? IDK, maybe not if it's required for correctness.
