### ISSUE TITLE
Should we automatically `borrow` when casting to an `unmanaged`

### ISSUE THREAD

**Issue by jabraham17** [chapel-lang/chapel#22574]
Recently we have run into some situations where the compiler special cases casts to `unmanaged`. When casting from a managed to an `unmanaged`, the compiler inserts a `.borrow()` call at the call site. This is currently undocumented and is only noted in a comment in the compiler.

This comment in `functionResolution.cpp` for `adjustClassCastCall(...)` describes the behavior.
> // Now, do a borrow if it's a cast from managed to not managed.
    // (Note, this assumes that managedType.borrow() does not throw/halt
    //  for nilable managed types storing nil. If that changed, we'd
    //  need another method to call here to get the possibly nil ptr).

This transforms `myOwned:unmanaged` to `((myOwned.borrow()):unmanaged)`.

The following example showcases the issue:
```chapel
class MyClass { var field: int; }
operator MyClass.: (x: MyClass, type t: int) {
  writeln("In cast, x.type is ", x.type:string);
  return x.field;
}
operator MyClass.: (x: MyClass, type t: shared) {
  writeln("In cast, x.type is ", x.type:string);
  return x.field;
}
operator MyClass.: (x: MyClass, type t: unmanaged) {
  writeln("In cast, x.type is ", x.type:string);
  return x.field;
}
proc main() {
  var x = new MyClass(1);
  writeln(x : int);
  writeln(x : shared);
  writeln(x : unmanaged); // compiler transforms to `(x.borrow()) : unmanaged`
}
```
This will print as
```
In cast, x.type is owned MyClass
1
In cast, x.type is owned MyClass
1
In cast, x.type is borrowed MyClass
1
```

Do we want to maintain this behavior? We recently deprecated internal casts to `unmanaged`, but there is nothing that says a user can't try to do this and they may be surprised by the result.

Proposals
- Leave the behavior as is, but document it
- Remove the behavior, the replacement being requiring an explicit `.borrow()` if this behavior is desired
- Remove the behavior, but bless the internal modules and allow them to use the behavior

**Comment by mppf** [comment]
I'd lean towards the 2nd or 3rd option, depending if we need the compiler special case in order to implement the casts we have.

**Comment by jabraham17** [comment]
In an offline discussion (https://github.com/Cray/chapel-private/issues/5169), we determined that we believe this to be a bug and will fix it.
