### ISSUE TITLE
Missing support for certain 64-bit math functions with AMD GPU support

### ISSUE THREAD

**Issue by stonea** [chapel-lang/chapel#22587]
As mentioned on the [GPU support technote](https://chapel-lang.org/docs/main/technotes/gpu.html#known-limitations):

> Certain 64-bit math functions are unsupported. To see what does and doesn’t work see [this test](https://github.com/chapel-lang/chapel/blob/release/1.30/test/gpu/native/math.chpl) and note which operations are executed when excludeForRocm == true.

This list includes:

```
acos(r64)
acosh(r64b)
asin(r64)
asinh(r64)
atan(r64)
atan2(r64,r64)
atanh(r64)
cbrt(r64)
cosh(r64)
erf(r64)
erfc(r64)
ldexp(r64,i32)
lgamma(r64)
log1p(r64)
sinh(r64)
tan(r64)
tanh(r64)
tgamma(r64)
```

**Comment by e-kayrakli** [comment]
https://rocm.docs.amd.com/projects/HIP/en/latest/reference/math_api.html

I spot-checked that some of the functions in your list is reported as supported here. Is this only a matter of going to a higher version of ROCm?

**Comment by stonea** [comment]
> I spot-checked that some of the functions in your list is reported as supported here. Is this only a matter of going to a higher version of ROCm?

I'm guessing not, although I haven't tried it on a higher version.

On my system it shows I'm using `hipcc --version` 4.4. I'm assuming (hoping) this stays in sync with the ROCm version. I can find old doc on their GH page, they don't have a commit tagged for 4.4 but they do for 4.3 and if I look there (https://github.com/ROCm-Developer-Tools/HIP/blob/rocm-4.3.x/docs/markdown/hip-math-api.md) it shows (among other things) that this as supported:

`__device__ double acos(double x);`

**Comment by stonea** [comment]
For the following

```chpl
proc foo() {
  var r32: real(32) = 0.1;
  var r64: real(64) = 0.1;

  on here.gpus[0] {
    foreach i in 0..0 {
      acos(r32);
      acos(r64);
    }
  }
}

foo();
```

When I run it through `chpl` I get:

```
lld: error: undefined hidden symbol: acosf
>>> referenced by /tmp/chpl-stonea.deleteme-Qyqgco/chpl__gpu.o:(std::acos(float))
>>> referenced by /tmp/chpl-stonea.deleteme-Qyqgco/chpl__gpu.o:(std::acos(float))
```

I would expect these to come in through the `/opt/rocm-4.5.2/amdgcn/bitcode/ocml.bc` file that we're "linking".

If I run `llvm-nm ocml.bc | grep "acos"` (`ocml.bc` is where I would expect to find the symbol for this) I get:

```
---------------- W __ocml_acos_2f16
---------------- W __ocml_acos_f16
---------------- W __ocml_acos_f32
---------------- W __ocml_acos_f64
---------------- W __ocml_acosh_2f16
---------------- W __ocml_acosh_f16
---------------- W __ocml_acosh_f32
---------------- W __ocml_acosh_f64
---------------- W __ocml_acospi_2f16
---------------- W __ocml_acospi_f16
---------------- W __ocml_acospi_f32
---------------- W __ocml_acospi_f64
---------------- W __ocml_cacos_f32
---------------- W __ocml_cacos_f64
---------------- W __ocml_cacosh_f32
---------------- W __ocml_cacosh_f64
````

`__ocml_acos_f64` looks like what we should be linking to.

To try and unerstand what should happening if I comment out the `acos(r64);` line (leaving the `acos(r32) line`), if I look at the LLVM IR (by passing `chpl` `--llvm-print-ir chpl_gpu_kernel`) I see:
 
```ptx
%29 = call contract float @acosf(float noundef %28) #4
```

Which is interesting because it doesn't seem to be calling `__ocml_acos_f32`, at least not directly. If I look at the generated assembly I see:

```s
s_add_u32 s4, s4, __ocml_acos_f32@rel32@lo+4
```

so it looks like at some point `acosf` lowers to `__ocml_acos_f32`. Maybe `acosf` is some kind of wrapper function. Where is that coming from?

**Comment by stonea** [comment]
This page looks like it might be relevant: https://github.com/RadeonOpenCompute/ROCm-Device-Libs/blob/amd-stg-open/doc/OCML.md

It mentions a "wrapper” bitcode library that you have to link to that "denotes a thin library responsible for mapping language specific mangled built-in function calls as produced by clang to the OCML API."

Could it be that we're not linking to the right set of these wrappers? This section discusses it in more detail https://github.com/RadeonOpenCompute/ROCm-Device-Libs/blob/amd-stg-open/doc/OCML.md#controls

**Comment by stonea** [comment]
Ok, so after adding some debugging code to see what function we return from the lvt when codegen'ing the call for `acos` in the kernel it looks like it returns the one in `/usr/include/c++/7/cmath` instead of what I want which is in `llvm-project/clang/lib/Headers/__clang_hip_math.h`.  This version in `cmath` looks like this:

```c
inline _GLIBCXX_CONSTEXPR float
  acos(float __x)
  { return __builtin_acosf(__x); }
```

The version in `clang_hip_math.h` looks like this:

```c
__DEVICE__ double acos(double __x) { return __ocml_acos_f64(__x); }
```

What I find confusing is why don't we see this same issue with NVIDIA?

**Comment by stonea** [comment]
Looking at this some more, it seems strange that we would be seeing the `acos` from `project/clang/lib/Headers/__clang_hip_math.h` during the gpu compilation at all.

In CCodeGenConsumer::shouldHandleDecl we should be filtering out all functions that aren't marked with `__device__` from consideration when doing the gpu pass of codegen:

https://github.com/chapel-lang/chapel/blob/35b62e53c04fd6dae97122493f4c0975c7bb6859/compiler/llvm/clangUtil.cpp#L1319

And indeed, if (in the gCodegenGPU branch) I add the following to force filtering out the relevant acos functions (atleast w/ specific machine/environment I have):

```C++
if(s == "/usr/lib64/gcc/x86_64-suse-linux/7/../../../../include/c++/7/cmath:86:3" ||
   s == "/usr/lib64/gcc/x86_64-suse-linux/7/../../../../include/c++/7/cmath:90:3") {
  return false;
}
```

If I print out the attributes on the decl doing something like this, I will see that indeed the acos from cmath is the 'device' attribute.

```C++
for(size_t i = 0 ; i < d->getAttrs().size(); i++) {
  PrintingPolicy print_policy(gGenInfo->clangInfo->Ctx->getLangOpts());
  std::string expr_string;
  llvm::raw_string_ostream stream(expr_string);
  d->getAttrs()[i]->printPretty(stream, print_policy);
  std::cout << "\tATTR: " << expr_string << std::endl;
}
```

This is all super confusing. How in the world is the function getting the `__device__` attribute?

I'm not totally sure where we should go from here. Some ideas:

* One thing that might be worth trying is to see what acos resolves to when `CHPL_GPU=NVIDIA`. To do this you can insert the following code into `getClangABIInfo` after the `clang::FunctionDecl* FD = llvm::dyn_cast_or_null<clang::FunctionDecl>(cValue);` line:

```C++
  if(!strcmp(fn->cname, "acos")) {
    SourceManager& srcm = gGenInfo->clangInfo->Ctx->getSourceManager();
    std::cout << "acos is coming from: " << fn->cname << " " << FD-getSourceRange().getBegin().printToString(srcm) << std::endl;
  }
```

* Perhaps this is a matter of ordering what we include (like maybe the cmath acos is getting included before or after the HIP version and we just need to reorder how we process these files). I'm not sure what would be dictating this but there must be some way to figure out what is including <cmath>.
* Another thing would be to try and understand when the __device__ attribute is getting applied to that Decl. Maybe we can build clang with debug symbols and put a breakpoint at some strategic location?

**Comment by stonea** [comment]
I'm closing this given this submission: https://github.com/chapel-lang/chapel/pull/22791

(we now have parity in these math functions).
