### ISSUE TITLE
"Silent" failures in cpu-as-device mode on GPUs when using `fifo` tasks 

### ISSUE THREAD

**Issue by DanilaFe** [chapel-lang/chapel#22598]
It's a known issue (https://github.com/Cray/chapel-private/issues/3645, [tech note](https://chapel-lang.org/docs/technotes/gpu.html)) that `CHPL_TASKS=fifo` doesn't launch GPU kernels, because the request locale computation is incorrect. However, the error presents quite mysteriously when using cpu-as-device: all the code works (because the CPU loops are always run) but all the GPU diagnostics break. This means a fair share of GPU tests work, even though they aren't behaving correctly. 

Since `fifo` doesn't work with `CHPL_LOCALE_MODEL=gpu`, it's probably best to make `printchplenv` complain when the two are used in combination. This way, users (like me!) wouldn't run into these rather confusing errors.

**Comment by bradcray** [comment]
I got bit by this today as well (since M1 Macs default to `fifo`).
