### ISSUE TITLE
Add support for a `--report-vectorize` flag?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#22596]
When using the LLVM back-end, would there be a way for us to propagate information from it about what it could or could not vectorize back to the user's console such that they'd get a sense of whether their loops vectorized as expected or hoped for?  

Chapel 1.29.0 added the ability [to inspect the assembly generated for a given routine](https://chapel-lang.org/docs/1.29/technotes/llvm.html#inspecting-the-generated-code), but inspecting assembly is more than a typical user would want to do.  In the vein of `--report-gpu`, would there be some way to leverage existing LLVM features to report vectorization actions taken by the back-end in terms of the Chapel source line numbers?

**Comment by jabraham17** [comment]
I am currently working on a slightly more general version of this which exposes LLVM opt remarks.

**Comment by jabraham17** [comment]
I just merged #22642 which implements this using llvm opt remarks.

To report all vectorization remarks from LLVM, compile with `--llvm-remarks='vector'`. This reports results for both the `slp-vectorizer` pass and the `loop-vectorize` pass. 

To report only for a function named `myFunc`, compile with `--llvm-remarks='vector' --llvm-remarks-function='myFunc'`.
