### ISSUE TITLE
Symbol resolution not considering forwarding within secondary/tertiary methods

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#22656]
### Summary of Problem

When dyno is resolving symbols in secondary or tertiary methods, it does not seem to be considering the possibility of forwarding as a means of finding where the symbol is defined.

### Steps to Reproduce

**Source Code:**

As an example, [this doesn't work](https://ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuhY3y4tSk_OLUhSCFaq5FBTKEosUKhRsFUyMrLlqubigckFgubT8ovLEopTMvHSwsmIrhWCwooKi_GSFIL20_HwNTbDC8qLMktScPI0KTbA8SHFuZZCVQpA1F5CGKLSGWA91Bcw1AA), generating `error: 'x' undeclared (first use this function)`:

```chapel
record S {
  var x = 42;
}

record R {
  forwarding var s: S;
}

proc R.foo() {
  writeln(x);
}

var myR: R;
myR.foo();
```

yet, if the body of R.foo() is changed to: `writeln(this.x);` then it [works as expected](https://ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuhY3a4pSk_OLUhSCFaq5FBTKEosUKhRsFUyMrLlqubigckFgubT8ovLEopTMvHSwsmIrhWCwooKi_GSFIL20_HwNTbDC8qLMktScPI2SjMxivQpNsCKQjtzKICuFIGsuIA1RbQ1xA9QpMCcBAA).

**Associated Future Test(s):**
[`test/types/records/bugs/forwarding-field-access.chpl`](
           https://github.com/chapel-lang/chapel/blob/main/test/types/records/bugs/forwarding-field-access.chpl
          ) #???

### Configuration Information

- Output of `chpl --version`: `chpl version 1.31.0`

**Comment by bradcray** [comment]
`--no-dyno` doesn't help with this, so I removed 'Dyno' from the subject line.  I jumped to conclusions because I was changing code from one that worked to one that didn't and mistakenly blamed dyno along the way.

**Comment by bradcray** [comment]
I feel as there are some cases in which this sort of pattern works (in the sense that I feel confident I've seen it before).  Yet I haven't been able to determine when that is.  Maybe for parenthesized members only?  Though I could've sworn I'd seen this applied to fields or zero-paren methods in the past at some point...

**Comment by mppf** [comment]
@bradcray - I think this might be a duplicate of #5979. Note that we also have problems with the implicit `this` in methods like `proc (R(int)).bar()`.

**Comment by bradcray** [comment]
I think you're right, thanks for the reminder.  Do you mind if I rename the title of that issue to make it more about the symptom and less about the compilation approach?

**Comment by mppf** [comment]
>  Do you mind if I rename the title of that issue to make it more about the symptom and less about the compilation approach?

Not at all, please feel free to edit it (or any issue of mine I am not actively updating).
