### ISSUE TITLE
Return a generic type by `ref` causes internal error

### ISSUE THREAD

**Issue by jabraham17** [chapel-lang/chapel#22686]
### Summary of Problem

Compiling the following program causes an internal error.
```chapel
record R {
  type t;
  var x: t;
}
var val: R(?);

proc foo() ref {
  return val;
}
var a = foo();
writeln(a);
```
If I change `foo()` to return by value (removing `ref`), I correctly get an error `could not determine the concrete type for the generic return type 'R'`. But the code above gives the following internal error.

```
test3.chpl:8: internal error: invalid attempt to get reference type [AST/primitive.cpp:238]
```

I would expect that this code to give the same error message as returning by value.

### Steps to Reproduce

**Source Code:**
See above

**Compile command:**
`chpl test.chpl`

### Configuration Information

- Output of `chpl --version`: chpl version 1.32.0 pre-release (0400cad5a6)
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: arm64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: fifo
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: cstdlib
CHPL_ATOMICS: cstdlib
CHPL_GMP: system *
CHPL_HWLOC: none
CHPL_RE2: bundled
CHPL_LLVM: system *
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
  -  LLVM version 15.0.7 
  - Apple clang version 13.1.6 (clang-1316.0.21.2.5)

**Comment by bradcray** [comment]
Huh, I wonder how this slips through...  Checking where the error message is coming from, I see:

```
  if (fn->retTag != RET_TYPE && retType->symbol->hasFlag(FLAG_GENERIC))
    // The compiler should have reported an error earlier. If it has not,       
    // give user-friendly error here - avoid potential confusion at callsite.   
    USR_FATAL(fn, "could not determine the concrete type"
              " for the generic %s type '%s'",
              isIterator ? "yielded" : "return", toString(retType));
```

Oh, maybe it's because the ref type wraps the generic type, so hides the flag?  I wonder whether `retType->symbol->getValType()->hasFlag(FLAG_GENERIC)` would do it...

**Comment by jabraham17** [comment]
Sadly, this fires too late to catch the error

in `void resolveFunction(FnSymbol* fn, CallExpr* forCall)`
```c++
insertUnrefForArrayOrTupleReturn(fn); // the internal error comes from here

Type* yieldedType = NULL;
resolveReturnTypeAndYieldedType(fn, &yieldedType); // error message comes from here
```

To the uninitiated observer these appear independent so I tried reversing their order and the assert still fired from inside `returnInfoRef`.

I think adding a similar check for `FLAG_GENERIC` to `returnInfoRef` will fix it?
```c++
...
  if(t->symbol->hasFlag(FLAG_GENERIC))
    USR_FATAL(call, "invalid attempt to get a reference type for a generic type");
...
```

It at least works for this test case, I will test the whole test suite on this tomorrow

**Comment by cassella** [comment]
As a member of the even-less-initiated, I would expect an error about `val` itself.  For example, with a `writeln(val)` before the proc definition,

```
foo.chpl:1: In module 'foo':
foo.chpl:5: error: cannot default-initialize a variable with generic type
foo.chpl:5: note: 'val' has generic type 'R'
foo.chpl:5: note: cannot find initialization point to split-init this variable
foo.chpl:6: note: 'val' is used here before it is initialized
```

But with the `writeln(val)` after the existing `writeln(a)`, I get the same internal error as above.


Taking the above error's advice,

```chapel
record R {
  type t;
  var x: t;
}
var val: R(?);

proc foo() ref {
  return val;
}
val = new R(int);

var a = foo();
writeln(a);

writeln(val, ": ", val.type:string);
```

compiles:

```
(x = 0)
(x = 0): R(int(64))
```

But moving the initialization of `val` down after the `writeln(a)` produces the same internal error.

(I haven't experimented with any of the proposed compiler changes.)

**Comment by jabraham17** [comment]
My paratest came back clean, I have opened #22694 to fix this
