### ISSUE TITLE
Feature Request: Linear Algebra `isZero` and `isEye` functions

### ISSUE THREAD

**Issue by kwaters4** [chapel-lang/chapel#22682]
### Summary of Problem
A couple of quality of life functions for the LinearAlgebra module would be a `isZero` or `isEye` functions. This functions would return a bool and be able to take a Matrix as an argument. Similar to the following functions:

[proc isDiag](https://chapel-lang.org/docs/modules/packages/LinearAlgebra.html?highlight=linearalgebra#LinearAlgebra.isDiag) -Return true if matrix is diagonal.

[proc isHermitian](https://chapel-lang.org/docs/modules/packages/LinearAlgebra.html?highlight=linearalgebra#LinearAlgebra.isDiag) - Return true if matrix is Hermitian

[proc isSymmetric](https://chapel-lang.org/docs/modules/packages/LinearAlgebra.html?highlight=linearalgebra#LinearAlgebra.isSymmetric) - Return true if matrix is symmetric

Maybe there is a quick way to do it already, but it was not obvious to me, outside of creating another identity or zero Matrix. Writing some loops would work as well. There could be some performance issues either approach. But in the end this would be a quality of life feature for users. 

Not a blocking issue.

**Comment by bradcray** [comment]
@Iainmon : I believe you added the requested routines in #22695 (thanks!).  Could this issue be considered resolved by that PR, or do you consider there to be more to do here before closing the issue?
