### ISSUE TITLE
Can't cast directly from `bool` to `bigint`

### ISSUE THREAD

**Issue by pierce314159** [chapel-lang/chapel#22715]
### Summary of Problem

This isn't a huge deal at all, but it would be nice have to avoid having to special case for this specific data type. There are a few places where we want to convert from a bool to a bigint (mostly for binary ops or other functions that operate on pdarrays of any dtype). There is a simple workaround of casting to `int` first: `myBool:int:bigint`. I totally understand if this intentionally off limits since intuitively a bigint seems like overkill for storing a single bit

### Steps to Reproduce

**Source Code:**

```chapel
use BigInteger;
var ex = true:bigint;
```

**Compile command:**

```
chpl PlayingAround.chpl -o playing
PlayingAround.chpl:3: error: illegal cast from bool to bigint
```

### Configuration Information

- Output of `chpl --version`:
```
chpl version 1.31.0
  built with LLVM version 15.0.7
  available LLVM targets: xcore, x86-64, x86, wasm64, wasm32, ve, systemz, sparcel, sparcv9, sparc, riscv64, riscv32, ppc64le, ppc64, ppc32le, ppc32, nvptx64, nvptx, msp430, mips64el, mips64, mipsel, mips, lanai, hexagon, bpfeb, bpfel, bpf, avr, thumbeb, thumb, armeb, arm, amdgcn, r600, aarch64_32, aarch64_be, aarch64, arm64_32, arm64
```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: arm64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: fifo
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: cstdlib
CHPL_ATOMICS: cstdlib
CHPL_GMP: system *
CHPL_HWLOC: none
CHPL_RE2: bundled *
CHPL_LLVM: system *
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by bmcdonald3** [comment]
Thanks for opening this Pierce, I've opened up a PR to add this here: https://github.com/chapel-lang/chapel/pull/22717

**Comment by bmcdonald3** [comment]
In the short term, this could also be worked around in Arkouda by adding a manual cast operator, something like 

```chpl
  inline operator bigint.:(src: bool, type toType: bigint): bigint throws {
    return new bigint(src:int);
  }
```
would do the trick I think.

**Comment by pierce314159** [comment]
Sweet!! Thanks ben!
