### ISSUE TITLE
chpl_library_finalize() should not hardcode the exit status

### ISSUE THREAD

**Issue by twesterhout** [chapel-lang/chapel#22739]
### Summary of Problem

Two problems:

- A call to `chpl_library_finalize()` forces the exit status of the process to be `0` which, I believe, it should not do.
- The very fact that `chpl_library_finalize()` invokes `exit()`. I think, one should be able to shut down the Chapel runtime and then still have a chance to finalize other runtimes / resources. 

### Details

[`chpl_library_finalize()`](https://github.com/chapel-lang/chapel/blob/9f04fa098706b6267ef4e60bafb4e99227703499/runtime/src/chpl-init.c#L416) calls [`chpl_rt_finalize()`](https://github.com/chapel-lang/chapel/blob/9f04fa098706b6267ef4e60bafb4e99227703499/runtime/src/chpl-init.c#L305) passing it `0`. Then `chpl_exit_all()` is invoked, and then [`chpl_exit_common()`](https://github.com/chapel-lang/chapel/blob/9f04fa098706b6267ef4e60bafb4e99227703499/runtime/src/chplexit.c#L34) calls `exit(0)`.

<br />

This is currently messing up my test suite, so a workaround would be appreciated :) I'm thinking of just removing `exit(status)` from `chpl_exit_common`, but that would probably mean that then my Chapel-only programs will start returning zero exit codes in case of failures...

**Comment by twesterhout** [comment]
And a side note, I believe that the fact that the process returns `0` is a bug. For instance, if I write

```python
def main():
  chpl_library_init()
  some_function_using_chapel()
  try:
    save_results()
  except:
    print("error")
    chpl_library_finalize()
    exit(1)
  print("success")
  chpl_library_finalize()
```

I think it's very confusing that the process can print "error" but will nonetheless return `0` as the exit code. Even worse is that the process has no way to return `1` if it intends to properly finalize the runtime.

**Comment by bradcray** [comment]
Hi Lydia —

I'm definitely sensitive to Tom's rationale that this call shouldn't be calling `exit()` (i.e., should not require itself to be the last thing to happen in a correct program).  The documentation even suggests that the program will continue running in the examples at https://chapel-lang.org/docs/technotes/libraries.html?highlight=chpl_library_finalize#initializing-your-library and hhttps://chapel-lang.org/docs/primers/interopWithC.html?highlight=chpl_library_finalize#using-the-chapel-library by showing a return statement occurring after the call.

> by allowing the program to continue after the chpl_library_finalize() call, we set up a situation where a user may try to restart the library again later

I'm not sure I buy this argument.  Specifically, a user could already call `chpl_library_init()` twice, and we don't do anything to protect them from themselves in that case, so why should we need to do it if they've already called `chpl_library_finalize()`?  That makes me think we could replace the `chpl_exit_all(0)` with an all-locales barrier (or even just make it into a no-op?) and then update the docs to assert that calling the init twice isn't legal and leave it at that.

Or, we could add a static C bool that indicates whether `chpl_library_init()` has been called or not and issue an error if it's called a second time, which both protects against the case you're worried about while also preventing other erroneous behaviors.

(Or both).
