### ISSUE TITLE
Should we add/rename BigInteger `shift` functions

### ISSUE THREAD

**Issue by jabraham17** [chapel-lang/chapel#22731]
## Summary

In a recent offline discussion (Cray/chapel-private#4969), we renamed `mul_2exp` to `mul2Exp`. This brought up a discussion on if we should have a better name for this function (and similar functions) that better describe what they do.

We currently support the following functions in BigInteger. These functions have similar names to the GMP functions they are based on.
```chapel
proc divQ2Exp(ref result: bigint, const ref numer: bigint, exp: integral, param rounding = round.zero)
proc divR2Exp(ref result: bigint, const ref numer: bigint, exp: integral, param rounding = round.zero)
proc mul2Exp(ref result: bigint, const ref a: bigint, b: integral)
```
When thinking about a `bigint` it is not immediately clear what a divide/multiply by a power of two is useful for, but they are used to do bit shifting. The remainder of a divide by a power of two is a bitmask of `exp` bits for the least significant bits.

Other languages which support BigInteger types such as Julia, Rust, and Go all support either operator shifts (`<<`/`>>`) or function shifts (`Lsh`/`Rsh` or `shl`/`shr`), and of the three only Julia supports the `div` and `mul` names.

In the past, Chapel has maintained both operators and functions for BigInteger as a performance optimization, and this is true for most operations. Bit shifts are an exception, where Chapel provides `<<` and `>>` but no `shift*` function. Instead we have `divQ2Exp(..., round.down)` and `mul2Exp`

<details>
<summary>Performance Optimization</summary>
The reason we provide both the operator and function is to prevent extra allocations. The functions all take a `ref` argument where the result is stored, whereas the operators always construct and return a new `bigint`. 
</details>

This leads me to the conclusion that we should either provide the shift names as an alternative to the divide/multiply interface, or rename them entirely. The reason I included `divR2Exp` is that currently it has a nice symmetry with `divQ2Exp`, and if we remove `divQ2Exp` then it may not make much sense on its own.

### Option 1

Just rename these functions to match the style from the recent BigInteger discussion (Cray/chapel-private#4969).

Rename
- `divQ2Exp` -> `div2Exp`
- `divR2Exp` -> `rem2Exp`
- `mul2Exp` -> `mul2Exp`

With this decision, we would probably want to call out in the documentation what these functions semantically do.

#### Option 2a

Completely remove `divQ2Exp`, `divR2Exp`, and `mul2Exp` from the public interface, and instead expose a bit shift interface. Note that this entirely drops the `rounding` argument and removes `divR2Exp` entirely

New functions
```chapel
proc shiftLeft(ref result: bigint, const ref a: bigint, b: integral)
proc shiftRight(ref result: bigint, const ref a: bigint, b: integral)
```

`shiftLeft` and `shiftRight` are my preferred names for this proposal. Other options could be `leftShift`/`rightShift` or `shl`/`shr`.

#### Option 2b

In addition to the above proposal, to keep some of the functionality provided by `divR2Exp`, we could introduce a `maskLower` function (straw person proposal for the name)

New function
```chapel
proc maskLower(ref result: bigint, const ref a: bigint, b: integral)
```

#### Option 3a

A combination of 1 and 2. This would involve applying the renames from Option 1, and then adding the shift functions as alternative names. This keeps all the functionality of the divide and multiply versions with the rounding argument, while providing a simpler shift interface.

Rename
- `divQ2Exp` -> `div2Exp`
- `divR2Exp` -> `rem2Exp`
- `mul2Exp` -> `mul2Exp`

New functions
```chapel
proc shiftLeft(ref result: bigint, const ref a: bigint, b: integral) do mul2Exp(result, a, b);
proc shiftRight(ref result: bigint, const ref a: bigint, b: integral) do div2Exp(result, a, b, round.down);
```

#### Option 3b

In addition to the above proposal, we could also add `maskLower` as an alternative name.

New function
```chapel
proc maskLower(ref result: bigint, const ref a: bigint, b: integral) do rem2Exp(result, a, b);
```

**Comment by jabraham17** [comment]
My preferred option is to just do Option 2a. I think this gives us the most flexibility while providing a clean interface to users. If we need to later add the divide version with rounding later, adding it is a non-breaking change.

**Comment by lydia-duncan** [comment]
I'm strongly in favor of exposing `shiftLeft` and `shiftRight` (and prefer those names over the others suggested).

I'm relatively ambivalent to whether we also keep `divQ2Exp`, `divR2Exp` and `mul2Exp`, but agree that if we do, they should have the proposed new names.  My main points of concern are:
- the loss of `divR2Exp`'s functionality
- the loss of the rounding argument for the `div` versions

I'm not sure how valuable they are today, so would probably be inclined to mark them unstable, do the rename, and add documentation to them, until we can determine if they are valuable.

**Comment by e-kayrakli** [comment]
No strong opinions as I am not a `bigint` user myself. But I wanted to say that adding a function like `maskLower` feels wrong to me. I don't see the benefit of having "lower" in the name, but beyond that, if anything we should have and/or functions so that people can do whatever masking they want.

This also feels in line with where the discussion is going w.r.t the other changes where we are adding functions with the bitwise operation names and considering removing others that have the potential use in their names ("shift" doesn't necessarily mean "div", "and" doesn't necessarily mean "mask" etc.).

This is probably my ignorance, but "masking" could also use bitwise-or in my view however uncommon it maybe. IOW, "mask" doesn't necessarily mean bitwise-and to me.

**Comment by jabraham17** [comment]
> I'm not sure how valuable they are today, so would probably be inclined to mark them unstable, do the rename, and add documentation to them, until we can determine if they are valuable.

I like this approach

> if anything we should have and/or functions so that people can do whatever masking they want.

We already support `and`, `or`, and `com`, which allow a user to construct whatever mask they wish. I agree, I don't think this specialized `mask` adds anything.

**Comment by jabraham17** [comment]
Based on the input received here and in the interest of trying to move this forward, I propose the following

- Rename `divQ2Exp` to `div2Exp`
- Rename `divR2Exp` to `rem2Exp`
- Mark `div2Exp`, `rem2Exp`, and `mul2Exp` as unstable
- Add `shiftLeft` and `shiftRight`

**Comment by lydia-duncan** [comment]
One thing that just occurred to me: should the result of `shiftLeft` and `shiftRight` depend on the endianness of the system?

**Comment by jabraham17** [comment]
I think this would be a departure from the operator names. `shiftLeft` matches nicely with `<<`. I think this would be a departure from the operator semantics.

But this makes me question if our current `bigint` shift operators do the right thing on systems with a different endianness.

**Comment by lydia-duncan** [comment]
Matching the operator names is probably the right call, that makes me feel better.

I do think we should test the different endianness, but I don't actually know that we have systems with unusual defaults to test on . . .
