### ISSUE TITLE
For various `chpl` environment variables `CHPL_NO_X=y` surprisingly, keeps the feature on

### ISSUE THREAD

**Issue by stonea** [chapel-lang/chapel#22804]
For various --no-X flags, setting CHPL_NO_X=y isn’t the same as passing in the flag (CHPL_NO_X=n is).  IOW I would expect `chpl --no-checks foo.chpl` and `CHPL_NO_CHECKS=y chpl foo.chpl` to do the same thing. But they don’t.

In a simlar vein, it looks like `CHPL_DISABLE_WARNINGS=n` is, confusingly, equivalent to `--no-warnings`.

Anyway, I'd propose we avoid the whole double-negative thing by getting rid of `_NO_` versions of all the environment variables, IOW change:

```
CHPL_NO_CHECKS --> CHPL_CHECKS 
CHPL_NO_BOUNDS_CHECKING --> CHPL_BOUNDS_CHECKING
CHPL_NO_NIL_CHECKS --> CHPL_NIL_CHECKS 
CHPL_NO_CODEGEN --> CHPL_CODEGEN
CHPL_NO_COMPILE_TIME_NIL_CHECKS --> CHPL_COMPILE_TIME_NIL_CHECKS 
CHPL_DISABLE_WARNINGS --> CHPL_WARNINGS
```

**Comment by mppf** [comment]
> Anyway, I'd propose we avoid the whole double-negative thing by getting rid of `_NO_` versions of all the environment varaibles...

here here!

**Comment by stonea** [comment]
I brought this up during our team meeting on 8/14/2023 and we have consensus for me to proceed with this.
