### ISSUE TITLE
Relationship between M1/M2 Macs, GPUs and `fifo`/`qthreads`

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#22895]
The [known limitations section of the GPU documentation](https://chapel-lang.org/docs/main/technotes/gpu.html#known-limitations) currently says:

> `CHPL_TASKS=fifo` is not supported. Note that [fifo tasking layer](https://chapel-lang.org/docs/main/usingchapel/tasks.html#chpl-tasks-fifo) is the default in only Cygwin and NetBSD.

But `fifo` is also currently the default on M1/M2 Macs (see https://github.com/Cray/chapel-private/issues/3531), so it should be mentioned here.  Since this is an important platform for us and our users, I'd also hoist the bullet much higher in the list of limitations (since it takes a certain amount of dedication to get through a list of 9).

Alternatively, since it's possible to manually set `CHPL_TASKS=qthreads` on Macs and have it work, we should consider pointing this out to users in the GPU docs.  Or perhaps even have `CHPL_TASKS` default to `qthreads` on M1/M2 Macs when `CHPL_LOCALE_MODEL=gpu`?  Or have `printchplenv` note the conflict and potential and make the suggestion (related to issue #22598).

**Comment by e-kayrakli** [comment]
> Or perhaps even have CHPL_TASKS default to qthreads on M1/M2 Macs when CHPL_LOCALE_MODEL=gpu

This is my first choice at least by initial reflex.

If you're using a Mac with the GPU support enabled, you must be using cpu-as-device mode where you can't do much when it comes to performance analysis and optimization. So, slowness of `qthreads` shouldn't be an issue.

I'd probably issue warning, though.

Based on what we choose to do for the default behavior, I agree that we can adjust the documentation with the consideration that `fifo` is the arm-based Mac default.

**Comment by bradcray** [comment]
> This is my first choice at least by initial reflex.

Mine as well.  Seems most likely to be useful/least likely to be annoying.

@ronawho, do you have any different thoughts here?

**Comment by ronawho** [comment]
Defaulting to qthreads for gpu locale model makes sense to me and I agree with the tradeoffs and not worrying about the perf hit.

**Comment by e-kayrakli** [comment]
I am thinking we should do this for 1.32. Please speak up if you have any concerns.

**Comment by ronawho** [comment]
The qthreads 1.19 release came out sooner than I expected, and that will allow us to use qthreads on Mac arms by default. I should be done with that today or tomorrow, and that should resolve this by making qthreads the default in all cases.
