### ISSUE TITLE
`printchplenv` should print `CHPL_GPU` setting when `CHPL_LOCALE_MODEL` is `gpu`

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#22894]
In this issue, I'm proposing that `printchplenv` should print the setting of `CHPL_GPU` when `CHPL_LOCALE_MODEL` is set to `gpu` by default, similar to how it prints some key communication settings when `CHPL_COMM` is set to something other than `none`.  In the gpu locale model, the `CHPL_GPU` setting seems core/crucial enough to print by default and not require `--all` or one of the other flags to see.

**Comment by mppf** [comment]
Do you think it should show `CHPL_GPU` literally nested within `CHPL_LOCALE_MODEL` ? Or just include `CHPL_GPU` when it is relevant based upon `CHPL_LOCALE_MODEL` ?

**Comment by e-kayrakli** [comment]
My preference is to show it nested under `CHPL_LOCALE_MODEL` when it is set to `gpu`.

**Comment by bradcray** [comment]
That's what I was imagining as well.  Like:

```
CHPL_LOCALE_MODEL: gpu
  CHPL_GPU: cpu
```
