### ISSUE TITLE
Potential wildcard-based `this.complete()` replacement: `this.* = ...;`

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#22977]
As noted elsewhere (https://github.com/chapel-lang/chapel/issues/21335, https://github.com/Cray/chapel-private/issues/5239), `this.complete()` is a feature we like, but one that is sometimes considered badly expressed in the code since it looks so normal and unassuming, yet has such powerful (and arguably surprising) properties and impacts.  Basically, for the casual reader, its impact is more significant than its syntax lets on.

In discussing this today, @benharsh proposed an idea that intrigued several of us that I wanted to capture in its own issue.  The idea would be to use more of a stylized syntax like:

```chapel
this.* = init;
```

or:

```chapel
this.* = default;
```

as a replacement for `this.complete();`.  The idea is that `*` would read as a wildcard character across fields, and that `init` or `default` (which we'd reserve, if chosen) would indicate that the fields should be initialized by the compiler.

Note that, like `this.complete()`, this syntax form would only initialize any remaining fields that had not previously been initialized implicitly or explicitly—i.e., all those following the last explicitly-initialized field.  So the `*` isn't a true wildcard ("all fields") but has to be understood to be the trailing set of them.

Despite that subtlety, this seems fairly attractive.  It's new syntax, so doesn't share the problem of `this.complete();` of making something notable and unique look too plain.  It's unique enough that it should be easy to find in documentation if one were to search for it (assuming that searching for `*` doesn't break the search string).  A new user may even be able to intuit what it does.  And we expect it would also be easy to parse without conflicts with other things.

Here are some tradeoffs about the idea altogether, without worrying about which of the two rhs keywords from above to use:

Pros:
* unique syntax with reasonably intuitive meaning
* potentially symmetric with proposed syntax to bring in all tertiary methods, if we were to adopt https://github.com/chapel-lang/chapel/issues/22761

Cons:
* `*` isn't a true "all fields" wildcard in this context, which could be confusing and/or limit the use of this syntax in other contexts
* so long as `this.complete()` is required (see #22975) to use `this` post-initialization, in cases where all fields have been explicitly initialized, this syntax seems somewhat less intuitive than `this.complete()`.  I.e.,
  ```chapel
  record R {
    var x: int;
    proc init() {
      this.x = 42;
      this.* = init;  // today this would be required even though we know that all fields are initialized
      this.foo();
  }
  ```
  Compared to the status quo, `this.complete();` could be read as an assertion ("I have completed initialization!") in addition to a request ("please complete initialization for me").  

If we chose to adopt #22975, this second concern would be reduced (you could still type it as a catch-all / cover since "empty set" is a reasonable wildcard match; but you wouldn't need to if you didn't want to raise "What do you think you're initializing here?" types of questions among naive readers of your code who can see all fields are initialized).

We also discussed that this pattern of a wildcard over fields _may_ have applicability elsewhere; though it's also worth noting that in other contexts, it probably wouldn't/couldn't have this "all remaining fields" interpretation, which would result in an asymmetry.

We also discussed that it might suggest supporting `this.x = init;` or `this.x = default;` for specific fields in an initializer as a way of saying "use the field initializer (if it has one) or the type's default value (otherwise)" rather than relying on the compiler to implicitly insert such initializers.  And we could describe any field initializations that the compiler introduced in these terms.  Moreover, for a user trying to reproduce the compiler-generated initializer, they could potentially write:

```chapel
proc R(in x: int = init, in y: [D] real = init) { ... }
```

rather than trying to reproduce the default value for the field in question (?).

Turning to the specific choices of `init` vs. `default`:

`init` Pros:
* already (intended to be) a reserved word, so no new lexer changes required
* arguably symmetric with `= noinit` as an initializer expression

`init` Cons:
* potentially not verb-y enough?

`default` Pros:
* arguably a little more straightforward to read?

`default` Cons:
* requires reserving a new word
* may not be very useful in other contexts (so could be overkill to introduce it just for this one?)

With respect to the last bullet, we discussed whether `default` would be applicable/useful in other non-initializer contexts.  In such cases, like this example:

 ```chapel
var x = expr;
...
x = default;
```

my assumption is that it would/could not mean "re-assign x to its declared default value" since the assignment statement could occur in a scope where the declaration wasn't visible or no longer made sense.  And if we were to interpret it as meaning "assign `x` its type's default value", I'd much rather see that expressed more explicitly using a syntax like `x.type.default` or `defaultOf(x.type)`.  Specifically, I think such type->default routines are much more generally useful than a sugar to assign a variable its type's own default value (e.g., I might want to pass `defaultOf(t)` into a type argument of a procedure).

**Comment by bradcray** [comment]
Of the choices mentioned here, I find `this.* = init;` most compelling due to the pros mentioned above.  I might even be a fervent champion of it if we were to adopt https://github.com/chapel-lang/chapel/issues/22975.

For the time being, I would not do any generalizations of it to other context (e.g., `this.x = init;` or supporting `init` as a default argument in initializers) until we found ourselves wanting such features more badly than I think we do today.

**Comment by bradcray** [comment]
Wondering briefly whether there were other things we could use than `*` to try and better distinguish "all remaining fields" from "all fields" while sticking with the general `= init;` theme, I riffed on the following, in case they catch anyone's eye:

```chapel
this.? = init;          // still mnemonic, but maybe doesn't imply "all fields" as much as `*` does?
this... = init;         // a little vaguer but also maybe implies "that which remains"?
this.otherwise = init;  // `otherwise` intending to imply "any other fields"
this.type = init;       // could be read as "this type is initialized" — of course, it's really the value that's initialized, so maybe not so good
this.var = init;        // meaning "this variable is initialized"?  (of course, it may be a const object...  but aren't consts just like special variables?
this.use = init;        // meaning "this is ready to be used"
```

Of these, I think only the first three are potentially viable, and maybe really only the first two, since they rely less on giving a second meaning to a keyword.

**Comment by e-kayrakli** [comment]
> Of the choices mentioned here, I find this.* = init; most compelling due to the pros mentioned above. 

Seeing `init` in a method, I would think of it as the initializer as an FCF. My reflex as a user reading that line would be "I am capturing the initializer in... something?", which is way off from what that line actually does. it feels a bit like abusing the keyword to me.

---

In general, the idea remains interesting to me; but I am not too wild about moving forward with it before finding a more general meaning for the syntactic recipe we're developing here. That makes me a bit skeptical about the proposal discussed here landing before 2.0.

**Comment by lydia-duncan** [comment]
I'm divided on whether I like this approach.  On the one hand, I agree with what Engin's saying about it looking too much like a FCF.  On the other hand, Ben's point about potential symmetry with `noinit` did resonate with me.  I do think that I prefer `init` to `default` because the former feels more clear that it could take the field's declared value, where just seeing "default" to me feels more like it favors the type's default.

I'm not a huge fan of the `.*` portion, either.  It makes the statement feel more in flux to me, where `this.complete()` feels like it has a clear meaning.  Though maybe that's because I'm more used to `this.complete()`.

**Comment by bradcray** [comment]
>  would think of it as the initializer as an FCF
> I agree with what Engin's saying about it looking too much like a FCF

The FCF concern doesn't give me much pause because (a) `init` is (will be) a keyword, so will be special and highlighted differently anyway and (b) we don't actually permit `init` to be named or invoked directly anywhere outside of initializers (and wouldn't permit it to be captured as an FCF within initializers), so it's far from a normal function and ` = init;` wouldn't be interpreted as an FCF capture in other contexts anyway.

To me, making the choice to not generalize the syntax could potentially be one of its strengths in that it would be a special/notable pattern that stands out and is unique.  So where a complaint with `this.complete();` is that it looks too unassuming, a syntax like this would be unlikely to slip by unnoticed (while still not being so strange or unintuitive to seem arbitrary).

**Comment by lydia-duncan** [comment]
> (b) we don't actually permit `init` to be named or invoked directly anywhere outside of initializers

Given that the intended usage is inside an initializer, potentially on the line immediately following a `super.init()` or `this.init()` call, this doesn't hold much weight for me.

**Comment by benharsh** [comment]
Another possible alternative to using ``.*`` could be:
```chpl
this = init;
```

**Comment by bradcray** [comment]
@DanilaFe implemented `init this;` as the replacement for `this.complete();` in https://github.com/chapel-lang/chapel/pull/23283, resolving this issue.
