### ISSUE TITLE
`complete;` as a possible replacement for `this.complete();`

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#22990]
In a recent brainstorming session, @mppf and I proposed that to address potential concerns with `this.complete();`, we might consider using `complete;` instead.

Our intention was not to consider it a reserved word, but simply to give it special behavior when used in this way within an initializer.  Essentially, if it resolved to our built-in `complete` symbol, it would have the same behavior as today.  If it resolved to a user initializer, we could consider generating a warning letting them know that in case they were confused, it was serving a special purpose here.

Alternatively, we could deprecate support for `ident;` as a legal statement form, which I believe is no longer necessary now that we have deprecated support for implicit reads of sync vars as a means of getting their state (yes, this could be a call to a paren-less procedure or method; but we don't encourage such cases to be non-field like, so if it's not interesting or worth supporting for a normal variable, it arguably isn't for a parenless procedure either).

Alternatively, we could reserve it where the main downside would be preventing users from using it themselves (where our sense is that it is likely to be a commonly desired identifier relative to many other keywords).

The idea behind the proposal was to make it look more like a special statement form yet without taking an identifier away from the user.

Pros:
* arguably conveys the same thing as `complete();`, and nearly the same thing as `this.complete();`
* looks slightly less like "just another method call" [and in a place where we can't legally make method calls yet
* users who balked at `this.complete();` were more in favor of this

Cons:
* Doesn't necessarily "pop" syntactically, similar to `this.complete();`, which was considered a demerit of that approach
  * Though it would pop more if we disallowed `ident;` statements other than `complete;`
* Isn't really a sibling with other single-keyword statement forms (`return;`, `break;`, `continue;`) which all imply discontinuous, non-returning control flow
  * Daniel argued that this is going off and doing some interesting things and then continuing here, but that feels more like a procedure call than a discontinuity in control flow to me.

**Comment by lydia-duncan** [comment]
With Daniel's implementation of `init this`, I think we can close this, right?

**Comment by bradcray** [comment]
@DanilaFe implemented `init this;` as the replacement for `this.complete();` in https://github.com/chapel-lang/chapel/pull/23283, resolving this issue.
