### ISSUE TITLE
Reposition location of deprecation warning messages in chpldoc?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#23018]
While browsing some chpldocumentation today, I became confused about whether the deprecation notes applied to the routine preceding or following the warning due to the similarity of the names of the routines and my own guess as to where the deprecation warning would fall for a given routine.  Here's a snapshot of the [page in question](https://chapel-lang.org/docs/1.31/language/spec/strings.html#String.createStringWithBorrowedBuffer):

<img width="749" alt="Screen Shot 2023-08-21 at 4 38 18 PM" src="https://github.com/chapel-lang/chapel/assets/7536222/d0501065-0575-4c94-af48-71fa5bb080dc">

(granted, the names differ in this case, so with a more careful reading, I was able to sort it out, but I could imagine other cases where adjacent routines might share the same name, where one was deprecated and the other not).

This made me wonder whether the deprecation warning would be more effective and easy to match to its routine by moving it just under the routine's declaration line and before its description started.  Basically, in this screenshot, swapping the blue and orange boxes.

**Comment by lydia-duncan** [comment]
That seems like a reasonable adjustment to me, and I don't think should be too difficult
