### ISSUE TITLE
Chapeltastic alternatives to `new file(0)`/`(1)`/`(2)`

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#23082]
Recent updates to the IO module have generally resulted in nice cleanups and simplifications to the shootout benchmarks.  When reviewing some of @benharsh's recent changes today, the main thing that I balked at was the ongoing use of `new file(0)`/`new file(1)` to get variations on `stdin`/`stdout`, particularly to get non-locking versions of them.

This issue asks for brainstorming on how we could express this more clearly and attractively to the user, with less of an emphasis on OS-level details of the relationship between these integers and the channels.

If non-locking were all we cared about, we could potentially just introduce new readers/writers that had that property.  Alternatively, we could create ways to clone an existing reader/writer and change some property or properties of it.  E.g., somehow create a clone of `stdout` that is non-locking.  `stdout.nonLockingCopy()` being a lame attempt.

**Comment by mppf** [comment]
> Alternatively, we could create ways to clone an existing reader/writer and change some property or properties of it. E.g., somehow create a clone of stdout that is non-locking. stdout.nonLockingCopy() being a lame attempt.

In some earlier work, I enabled `init=` to support initializing a channel with different locking. Presumably that's still possible with a `fileWriter` but I haven't checked.

**Comment by mppf** [comment]
AFAIK this pattern does 2 things for us:
 1. Turn off locking in a new fileWriter
 2. Use only Chapel's I/O buffering, instead of both Chapel's I/O buffering and the `FILE*` C buffering

But so far we've only been talking about the locking aspect

**Comment by bradcray** [comment]
Closing this as a duplicate of #24730 (which is newer, but I like its phrasing better and will be more likely to find it on a search... e.g., this one failed to mention stdin/stdout/stderr).
