### ISSUE TITLE
Unstable `config`s generate an unstable warnings even without the `--warn-unstable` flag

### ISSUE THREAD

**Issue by ShreyasKhandekar** [chapel-lang/chapel#23248]
### Summary of Problem

When a certain `config var` or `config const` is marked as unstable, we expect it to be excluded from `--help` messages and generate an unstable warning when the flag is passed at runtime.

Surprisingly this warning is generated even without the `--warn-unstable` flag being passed, but only when we set these flags using the `-s` option at compile time. If I set these configs at runtime, then the warning is not generated.

### Steps to Reproduce

**Source Code:**

```chapel
@unstable("Hey it's unstable!")
config var myUnstableConfig = 0;

writeln(myUnstableConfig);
```

**Compile command:**
`chpl foo.chpl -smyUnstableConfig=12`
Output:
```
warning: Hey it's unstable!
note: 'myUnstableConfig' was set via a compiler flag
```

**Execution command:**
`./foo`

### Impacted tests

While unstabilizing many configs in https://github.com/chapel-lang/chapel/commit/762f5d4ac4f3fc11ade005596a9a559ba982859e I ran into two tests that were impacted by this.

- ~test/statements/manage/WarnUnstable.chpl~
- test/distributions/robust/arithmetic/reindexing/simple-alias-mem-use.chpl
- test/distributions/bharshbarg/fastFollowerEquality.chpl

**Comment by jabraham17** [comment]
Note: if you take this test case and pass `--warn-unstable`, you get duplicate warnings as both dyno and the production compiler will warn. The dyno warning is the one that is being printed no matter what.

This also does not respect the flag `--no-warnings`(`@deprecated` on a `config` as well)

**Comment by lydia-duncan** [comment]
test/statements/manage/WarnUnstable.chpl explicitly sets `--warn-unstable`, so it is appropriate that it generates a warning

**Comment by e-kayrakli** [comment]
Ugh... this is probably my bug. I suspect we need to check `--warn-unstable` here: https://github.com/chapel-lang/chapel/pull/22849/files#diff-4bc768768f97a657d960b495210597a781db6a7fa2eec694607d43c49601ed46R476

**Comment by lydia-duncan** [comment]
> Note: if you take this test case and pass `--warn-unstable`, you get duplicate warnings as both dyno and the production compiler will warn.

They're actually not duplicate warnings - one's for the config getting set on the command line, the other is for the use on line 4
