### ISSUE TITLE
printchplenv showing "none" for unwind despite chplconfig setting

### ISSUE THREAD

**Issue by tonycurtis** [chapel-lang/chapel#23262]
### Summary of Problem

I set

```
CHPL_UNWIND=bundled
```
in `~/.chplconfig` as indicated in documentation:

https://chapel-lang.org/docs/usingchapel/chplenv.html?highlight=unwind#chpl-unwind

When I do `printchplenv` that line is always shown as

```
CHPL_UNWIND: none +
```

Is this correct?

Rest of output:

```
CHPL_TARGET_PLATFORM: hpe-apollo
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: aarch64
CHPL_TARGET_CPU: native +
CHPL_LOCALE_MODEL: flat +
CHPL_COMM: gasnet +
  CHPL_COMM_SUBSTRATE: ibv +
  CHPL_GASNET_SEGMENT: fast +
CHPL_TASKS: qthreads +
CHPL_LAUNCHER: slurm-gasnetrun_ibv
CHPL_TIMERS: generic
CHPL_UNWIND: none +
CHPL_MEM: jemalloc +
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: bundled +
CHPL_HWLOC: bundled +
CHPL_RE2: bundled +
CHPL_LLVM: bundled +
CHPL_AUX_FILESYS: lustre +
```

**Comment by bradcray** [comment]
@tonycurtis : You're correct that this setting in your `.chplconfig` file should typically get picked up by `printchplenvconfig`.  The `+` next to your entry:

```
CHPL_UNWIND: none +
```

indicates that it is getting its value from _a_ `chplconfig` file making me wonder whether you might have multiple `chplconfig`/`.chplconfig` files and the wrong one is being used (?).  Based on the information [in the docs](https://chapel-lang.org/docs/usingchapel/chplenv.html?highlight=unwind#search-paths-and-file-names) it looks like the most likely possibility is having a file named `~/chplconfig` or having `$CHPL_CONFIG` set to point to a specific directory location (?).

It looks like numerous entries from your `printchplenv` output are taking their values from a `chplconfig` file.  Are you setting those other things in `~/.chplconfig`, or is that an additional indicator that there is another file that's being used instead of it?

**Comment by tonycurtis** [comment]
hey brad, this is from a brand-new source directory.  I don't asee any other `chplconfing` file.  I checked for that.  If I set `CHPL_UNWIND=bundled` in my environment before `printchplenv` the "+" becomes a "*" but still iisted as "none".

**Comment by tonycurtis** [comment]
oooh, wait: there's a `CHPL_UNWIND=none` in the 1.310 release source directory.  I assume that is over-riding things?  I have no particular need to unwind, BTW, I was just fiddling with things...

**Comment by bradcray** [comment]
> If I set CHPL_UNWIND=bundled in my environment before printchplenv the "+" becomes a "*" but still iisted as "none".

OK, now that is just bizarre...  The `*` means "inferred from your environment", which is encouraging, but I don't have a guess as to why it would still be listed as `none`, and that definitely suggests "bug".

> oooh, wait: there's a CHPL_UNWIND=none in the 1.31.0 release source directory.

I'm not following...  what do you mean by "in the source directory"?

In any case, I'm not sure this is a good explanation—the environment variable should "win" and the fact that you're seeing a `*` next to that entry suggests that it should be, but isn't...?

Are your observations very specific to the `CHPL_UNWIND` option?  (I.e., are other settings in `~/.chplconfig` or your environment similarly not seeming to match?)  If so, that also suggests "bug" to me.

**Comment by tonycurtis** [comment]
I am currently playing with the 1.31.0 source release.  This contains a `chplconfig` file with `CHPL_UNWIND=none` in it.  But if I set `CHPL_UNWIND=bundled` in `~/.chplconfig` *or* in my environment, `printchplenv` still thinks the "none" value is in effect

**Comment by bradcray** [comment]
Oh, weird...  This seems to have something to do with `hpe-apollo` being set...(?!?).  Or, checking the sources, maybe more accurately something like having CHPL_TARGET_PLATFORM be set/inferred to something other than linux or osx...

And I think this is the fix:

```patch
diff --git a/util/chplenv/chpl_unwind.py b/util/chplenv/chpl_unwind.py
index 45dd0ed772..b41591dd91 100755
--- a/util/chplenv/chpl_unwind.py
+++ b/util/chplenv/chpl_unwind.py
@@ -23,8 +23,10 @@ def get():
                   "\nUse CHPL_UNWIND=system instead.", ValueError)
         elif val == 'system':
             return 'system'
-    return 'none'
-
+    elif val != None:
+        return val;
+    else:
+        return 'none'
 
 @memoize
 def get_uniq_cfg_path():
```

Thanks for reporting this!  I've put details about how I reproduced it below 

With respect to this:

> I am currently playing with the 1.31.0 source release. This contains a chplconfig file with CHPL_UNWIND=none in it.

The sources shouldn't ship with a `chplconfig` file, and I just downloaded a fresh copy of the release to verify that they don't seem to:
<img width="232" alt="Screen Shot 2023-09-07 at 6 44 17 PM" src="https://github.com/chapel-lang/chapel/assets/7536222/cacee2ea-35b3-4e52-bbbc-ca9917e528d9">

However, running `./configure` does create a `chplconfig` file, so I'm guessing/hoping that's where yours came from.



<details>

First, I tried and failed to reproduce the behavior you're describing on my linux box, where everything worked as expected:

```bash
$ printchplenv | grep UNWIND   # lack of any settings to see what the default is
CHPL_UNWIND: none
$ echo "CHPL_UNWIND=none" > chplconfig  # set default in local chplconfig and see that it gets picked up
$ printchplenv | grep UNWIND
CHPL_UNWIND: none +
$ export CHPL_UNWIND=bundled   # override default in env and see that it wins
$ printchplenv | grep UNWIND
CHPL_UNWIND: bundled *
$ echo "CHPL_UNWIND=bundled" > ~/.chplconfig   # set default in `~/.chplconfig` and see that it doesn't win
$ printchplenv | grep UNWIND
CHPL_UNWIND: bundled *
$ export -n CHPL_UNWIND  # unset env. var. and see that `~/.chplconfig` wins 
$ printchplenv | grep UNWIND
CHPL_UNWIND: bundled +
$ rm ~/.chplconfig   # remove it and see that chplconfig wins again
$ printchplenv | grep UNWIND
CHPL_UNWIND: none +
$ rm chplconfig   # remove it and see that the default returns
$ printchplenv | grep UNWIND
CHPL_UNWIND: none
```

However, then I set `CHPL_TARGET_PLATFORM=hpe-apollo` and start to see the strangeness you describe:

```bash
$ export CHPL_TARGET_PLATFORM=hpe-apollo
$ echo "CHPL_UNWIND=none" > chplconfig
$ printchplenv | grep UNWIND  # this is OK
CHPL_UNWIND: none +
$ export CHPL_UNWIND=bundled   # this is weird, though
CHPL_UNWIND: none *
$ export -n CHPL_UNWIND
$ echo "CHPL_UNWIND=bundled" > ~/.chplconfig  # as is this
CHPL_UNWIND: none +
```

</details>
