### ISSUE TITLE
Have `make install` rather than `configure` create the installation directory

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#23271]
In https://github.com/chapel-lang/chapel/issues/23264, @tonycurtis points out that Chapel's configure + make install steps deviate from autoconf in that our `./configure` step makes the directories in question if they don't exist rather than the `make install` step doing so.  Doing a quick test, I verified that (in the package I tested) making the directory was among the first things that `make install` does, suggesting we should follow that pattern as well to reduce surprises and differences.  @mppf points out that an advantage of this change is that it would permit whatever permissions are required to create the directory to only exist at the `make install` step and not at the `./configure` step (or, potentially, the `make` step if that's done separately).

**Comment by ShreyasKhandekar** [comment]
I was looking into this and to me it seems the only reason we create the directory in the `./configure` step is in order to normalize the path passed in either via `--prefix` or `--chpl-home`

If we move normalization into the make install script as well, we can get away with not creating the directories in the `./configure` step. The only question is if any other script/step requires that these paths be normalized/verified to exist before the `make install` step can do that for us.
From a cursory investigation, the answer to that seems - no, we can safely wait til `make install` to normalize the paths and create the directories.

I can make this change if no one has picked it up.

**Comment by mppf** [comment]
Interesting. I think that the `make` process with the compiler also uses the path (It sets CMAKE_INSTALL_PREFIX & cmake fills in include/chpl/config/config.h.cmake based on it). I do not recall off-hand why we are normalizing the path at all here, but what would make sense to me would be to normalize the path in a way that does not depend on it existing. (The replacing of `~` for example works this way already). Calling out to Python `os.path.realpath` should work and won't require that the path exist. It'd be reasonable to use `os.path.expanduser` first, as well, to move the `~` handling to something more tested than what we have.

<details>

A search finds this S.O. post https://stackoverflow.com/questions/284662/how-do-you-normalize-a-file-path-in-bash which suggests using Python to call `os.path.realpath`. We can do that. 
</details>

**Comment by bradcray** [comment]
> I can make this change if no one has picked it up.

I don't believe anyone has.  On one hand, I don't consider this the most important issue; on the other hand, it seems like it should be fairly straightforward, and I don't see any reason not to make it.

Does who normalizes the path matter very much?  I.e., somehow `./configure` hands the path off to `make install`, right?  If it retained ownership of the normalization step, could it pass off that normalized path to `make install`?  (mabye this is what Michael is saying).  That said, I don't see any obvious downside in waiting to have `make install` normalize the pth either...  Keeping it in `./configure` would just keep it more similar to what we have today (so a smaller change, potentially).

I suppose the other thing to check would be whether in autoconf one or the other obviously does the normalization script, since a desire to conform to autoconf is arguably what led to this issue.

**Comment by ShreyasKhandekar** [comment]
>somehow ./configure hands the path off to make install, right? 

`./configure` saves the normalized paths in text files named `configured-prefix` or `configured-chpl-home` depending on what was configured.

`os.path.realpath` as Michael suggested can do the normalizing for us even if the path doesn't exist, it would be a little weird to call out to python inside a bash script for just this purpose, but I think its fine. Plus we get the added benefit of not needing special privileges to `mkdir` before the `make install` as Michael said earlier too.

**Comment by bradcray** [comment]
> it would be a little weird to call out to python inside a bash script for just this purpose

It's more work than this issue intended, but `./configure` could presumably be rewritten as a Python script if that helped.

Thinking more about this:

> I suppose the other thing to check would be whether in autoconf one or the other obviously does the normalization script, since a desire to conform to autoconf is arguably what led to this issue.

I'm wondering how one would determine this.  Maybe it'd just be a matter of using an obviously non-normalized path as the prefix and then seeing what's saved in autoconf's configure output?  When I was comparing our current behavior to autoconf, I just configured one of the third-party packages we bundle to determine how it behaved.

**Comment by ShreyasKhandekar** [comment]
Is there someplace where I can learn how to use autoconf with chapel? I'm not super familiar with the tool, but I can look into what it does for us in this case.

**Comment by mppf** [comment]
I don't think we want to start to use autoconf with Chapel. I think Brad was just suggesting to look at how software using autoconf handles the issue here. Most of the things in the third-party/ directory use autoconf and it's very common, broadly speaking, for source distributions of linux tools. 

I tried it out quickly with [femto](https://github.com/femto-dev/femto) which uses automake.
 * `./configure --prefix=/tmp/foo` did not create `/tmp/foo`
 * `make` did not create `/tmp/foo`
 * `make install` did create `/tmp/foo`

I am still recommending the Python path normalization strategy.

**Comment by bradcray** [comment]
I'd already done this experiment, which is what led me to open this issue:

> I tried it out quickly with [femto](https://github.com/femto-dev/femto) which can use automake.
> 
> ./configure --prefix=/tmp/foo did not create /tmp/foo
> make did not create /tmp/foo
> make install did create /tmp/foo

My most recent question above was whether we could determine whether autoconf did normalization of path names at the configure or make install step so that we could follow its precedent.

**Comment by mppf** [comment]
Oh, right, I knew that, but forgot it.

One form of normalization is to expand `~`. The autoconf based configure does not do that:
```
./configure --prefix=~/tmp/foo
configure: error: expected an absolute directory name for --prefix: ~/tmp/foo
```

Another form of normalization is to remove `..` in paths. When I use `--prefix=`/tmp/foo/../foo`, it appears in the `make install` log, to make it clear that it is just never normalized.

So, I think an alternative to the "Normalize in Python" approach is "Never normalize and give errors if it would be problematic". IMO normalizing away `..` and handling `~` is nice, though.

**Comment by tonycurtis** [comment]
Not expanding "~" here is to do with shell tokenization?

**Comment by mppf** [comment]
Ah, yes, `./configure --prefix ~/tmp/foo` does expand it, because the shell handles it on the way in to `configure`. Presumably something about `./configure --prefix=~/tmp/foo` leads the shell not to expand it.

**Comment by tonycurtis** [comment]
The "=' immediately before the "~" wouldn't tokenize "~" into being recognized as "home directory (of some user)".  But using a space does do that.

**Comment by tonycurtis** [comment]
However, `--prefix=$HOME/....` does expand as expected.  Shell bug?

**Comment by bradcray** [comment]
@tonycurtis : I meant to ask a few hours ago but then got distracted (so, unrelated to your latest comment):  On the question of whether or not it would be nice for `./configure` to normalize the path, do you have an opinion on that?

(Without more data and/or expert opinions, I'd be inclined to have configure not normalize the path out of a combination of the K.I.S.S. principle and autoconf not doing it.  That said, I don't have a case in mind that would matter, unless...  would a normalized path convert symbolic links into their targets?  If it did, maybe the right thing to do is to not normalize it in case the symbolic link changes what it's pointing to between configure and make install time?)

**Comment by tonycurtis** [comment]
I hink you should do whatever the GNU configure does, if you want to call your script `./configure`.  That's what everyone is going to think.  So, basically, leave it alone and assume the user is saying what they want

**Comment by ShreyasKhandekar** [comment]
>Never normalize and give errors if it would be problematic

It seems that this is the strategy we would be going for if we want to copy what autoconf does.
@mppf Could you expand on what cases would be problematic and we should give out errors for?

**Comment by mppf** [comment]
I was just expecting to match autoconf in that `--prefix` needs to be given an absolute path (i.e. one starting with `/`).
