### ISSUE TITLE
Feature request: developer documentation of all the various .good files we support

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#23285]
There's a number of different `.<prefix>`es we support for .good files in our testing system.  `.comm-none.good` is a common one.  But I find it difficult to remember exactly which ones we do or don't support.  It'd be nice to have a place developers could reference to see which ones are supported, even if it ends up out of date.

It looks like https://github.com/chapel-lang/chapel/blob/main/util/test/sub_test.py#L553 is where we define which ones are meaningful.  Probably any documentation update should leave a note there indicating that the documentation should be updated for any changes.

**Comment by bradcray** [comment]
https://chapel-lang.org/docs/developer/bestPractices/TestSystem.html would be a natural place for this.  In fact, it has such a section currently, though it may be out of date: https://chapel-lang.org/docs/developer/bestPractices/TestSystem.html#testing-different-behavior-in-different-settings

**Comment by lydia-duncan** [comment]
D'oh!
