### ISSUE TITLE
Update beginner/user-facing docs that rely on `dmapped`

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#23329]
Since we won't have a stable update for `dmapped` going into this fall's release, we discussed a push to update user-facing docs, particularly ones aimed at beginners, to avoid the reliance on `dmapped`.  Proposed docs needing updates included:

- [ ] spec
- [x] primer examples
- [x] users guide
- [x] module documentation (?)

**Comment by bradcray** [comment]
Oops, this probably should've been more of a private issue since it's more about task-tracking.  I don't feel strongly enough to convert it though, but have at it if you'd like to.

**Comment by jeremiah-corrado** [comment]
I'm good keeping it public. Thanks!
