### ISSUE TITLE
Unstable warning about identifiers starting with `_` shouldn't apply to `_` itself

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#23430]
In Chapel, the identifier `_` has the special meaning "drop / ignore" when used in contexts like de-tupling:

```chapel
for (_, a, i) in zip(myDom, MyArr, 1..) do ...
```

Yet the `--warn-unstable` flag currently has the behavior that it warns about such uses:

```bash
warning: symbol names with leading underscores (_) are unstable
```

we should special-case the warning to not warn about identifiers named `_`.

**Comment by lydia-duncan** [comment]
It looks like every single instance of this warning in `release/examples` is because of this scenario

**Comment by bradcray** [comment]
@lydia-duncan : I keep toying with fixing this, which seems it should be trivial (add a "and doesn't have length 1" check to https://github.com/chapel-lang/chapel/blob/main/frontend/lib/uast/post-parse-checks.cpp#L1256), but then not finding the time.

Are you thinking about it?  If not, would any of @dlongnecke-cray, @DanilaFe, @riftEmber have time to fix it (as those who added/updated this check?)

**Comment by riftEmber** [comment]
I can pick this up real quick

**Comment by lydia-duncan** [comment]
Thanks, Anna!

**Comment by riftEmber** [comment]
PR'd at https://github.com/chapel-lang/chapel/pull/23456

**Comment by DanilaFe** [comment]
Woah, I was avoiding "good first issue"-tagged issues because I assumed (?) that we might want to save them for external contributors. But I suppose that's silly coming up on the release...

**Comment by riftEmber** [comment]
@DanilaFe Yeah, I usually do as well, but did this one since Brad asked about it.

**Comment by bradcray** [comment]
Thanks for the quick response, Anna!  And sorry to throw people off by using those tags.  If we hadn't gotten to it this week, I didn't want this to get lost, but am definitely happier we won't ship with that warning triggering.

**Comment by damianmoz** [comment]
Does that mean any internal variable beginning with an underscore is going to be marked as unstable.

In algebraic expressions, one often has variables like `n'` or _n-prime. I understand these are too hard to implement as variable names, but some people use `_n` or `n_` as an alternative.

Does that mean that when such a variable is used with a very local scope, at most within a small routine or module, that the compiler will complain with such messages? What is the instability? Using a leading underscore for something with global scope is fraught with danger so I can understand the message in those scenarios.

**Comment by bradcray** [comment]
> Does that mean any internal variable beginning with an underscore is going to be marked as unstable.

Depends on what you mean by "internal variable".  Variables that are part of Chapel's internal modules are not subject to this rule.  All user variables (currently) are, whatever their scope.  Like all unstable warnings, these warnings currently will only appear if compiling with `--warn-unstable` (which is designed to alert users to aspects of their programs that could change over time).  In this case, the warning is to give us the ability to reserve identifiers starting with underscores for our own implementation purposes.

`n_` will not get marked unstable, but `_n` would be.  

I think it could be reasonable to file a feature request issue asking whether local variables could not trigger this warning.  I'd have to think harder about what the implications would be.

**Comment by damianmoz** [comment]
Let me know if you think it is reasonable. If it is too hard, I can live with the warnings. It is not a big issue. Thanks.

**Comment by lydia-duncan** [comment]
Not having it trigger for local variables was also something that occurred to me as valuable, so it'd be good if we could investigate how tractable that would be
