### ISSUE TITLE
Launching multi-locale applications seems to choke in some circumstances when environment variables contain whitespace or newlines

### ISSUE THREAD

**Issue by psath** [chapel-lang/chapel#23536]
### Summary of Problem
I'm on a Slurm cluster that only has an ethernet interconnect so I am using GASNet-over-UDP with the `amudprun` launcher. I am trying to convert a successful `srun`-based interactive launch to an `sbatch`+SSH-based batch job, but my application launch on the worker nodes is failing due to unrecognized arguments, which originate from environment variables/functions that contain either spaces or newlines.

I'm not sure why the interactive `srun` configuration worked and the batch didn't, this is my first foray into multi-locale runs. But the resource is too contended to run all my tests in interactive mode so I have to utilize batch jobs.

Essentially
`amduprun -np 1 my_wrapper.sh my_application_real <my args> <lots of -E variables> -E LESSOPEN=||/usr/bin/lesspipe.sh %s  <more -E variables>`
gives
`<command-line arg>:317: error: Unexpected flag:  "%s"`

Problem variables:
```
echo $LESSOPEN
||/usr/bin/lesspipe.sh %s
declare -pf | grep "^module (" -A3
module ()
{
    eval $($LMOD_CMD bash "$@") && eval $(${LMOD_SETTARG_CMD:-:} -s sh)
}
declare -pf | grep "^ml (" -A3
ml ()
{
    eval $($LMOD_DIR/ml_cmd "$@")
}
```

Workaround: If I add the following to both `my_wrapper.sh` (before `$@`) and `my_job.sh` (before the launch of `my_application`) to forcibly unset the bad variables, then I can successfully run. 
```
unset LESSOPEN
export -nf module
export -nf ml
```

However, whatever is generating the `-E` flags to both `amudprun` and `my_application_real` should really handle space- and newline-bearing environment variables gracefully as they are a known issue with newer versions of BASH (mine seem to be specifically coming from Module/Lmod identical to here: https://github.com/systemd/systemd/issues/14878), and deleting them is a fragile workaround.

### Configuration Information

Working srun configuration:
```BASH
export CHPL_COMM=gasnet
export CHPL_LAUNCHER_ACCOUNT=<redacted>
export CHPL_LAUNCHER_PARTITION=<redacted>
export CHPL_COMM_SUBSTRATE=udp
export GASNET_SPAWNFN=C
export GASNET_CSPAWN_CMD="srun --verbose --gres=gpu:1 -A $CHPL_LAUNCHER_ACCOUNT -p $CHPL_LAUNCHER_PARTITION --exclusive -N%N %C"
export CHPL_LAUNCHER=amudprun
export CHPL_LAUNCHER_REAL_WRAPPER=/path/to/my_wrapper.sh
```

Broken sbatch configuration:
```BASH
export CHPL_COMM=gasnet
export CHPL_LAUNCHER_ACCOUNT=<redacted>
export CHPL_LAUNCHER_PARTITION=<redacted>
export CHPL_COMM_SUBSTRATE=udp
export GASNET_SPAWNFN=S
export GASNET_SSH_SERVERS=`scontrol show hostnames | xargs echo`
export CHPL_LAUNCHER=amudprun
export CHPL_LAUNCHER_REAL_WRAPPER=/home/sath6220/arcChapelWorkspace/Chapel-Examples/jaccard/infer_wrapper.sh
```

Launch command
```BASH
sbatch -N1 --gres=gpu:2 --export=NONE,NUM_PARTS=1,NUM_LOCS=1,NUM_GPUS=2 my_job.sh
```

my_job.sh (working)
```BASH
#!/bin/bash
#SBATCH --exclusive
#SBATCH -A <redacted>
#SBATCH -p <redacted>

#expect NUM_GPU NUM_PARTS and NUM_LOCS to be provided by an --export flag to sbatch

export GASNET_SPAWNFN=S
  # Specify the list of nodes to use
export GASNET_SSH_SERVERS=`scontrol show hostnames | xargs echo`

module reset
source /path/to/my_modules.sh
unset LESSOPEN
export -nf module
export -nf ml
for file in `ls /path/to/datasets/`
do
  /path/to/my_application --inFile=/path/to/datasets/"$file" --outFile=/path/to/results/locs"$NUM_LOCS"-parts"$NUM_PARTS"-gpus"$NUM_GPUS"-"$file" <my arguments --numParts="$NUM_PARTS" --numLocales="$NUM_LOCS" --verbose &>/path/to/results/locs"$NUM_LOCS"-parts"$NUM_PARTS"-gpus"$NUM_GPUS"-"$file".log
  md5sum /path/to/results/locs"$NUM_LOCS"-parts"$NUM_PARTS"-gpus"$NUM_GPUS"-"$file"
done

```

my_wrapper.sh (working)
```BASH
#!/bin/bash
module reset
source /path/to/my_modules.sh
unset LESSOPEN
export -nf module
export -nf ml
$@

```

my_modules.sh (already working)
```BASH
#!/bin/bash
module load CUDA/11.7.0
module load GCC/11.2.0
module load CMake/3.22.1-GCCcore-11.2.0
module load ncurses/6.2-GCCcore-11.2.0
export CHPL_COMM=gasnet
export CHPL_LAUNCHER_ACCOUNT=<redacted>
export CHPL_LAUNCHER_PARTITION=<redacted>
export CHPL_COMM_SUBSTRATE=udp
export CHPL_LAUNCHER=amudprun
export CHPL_LAUNCHER_REAL_WRAPPER=/path/to/my_wrapper.sh
```

```
bash --version
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
...
uname -a
Linux <hostname Redacted> 3.10.0-1160.90.1.el7.x86_64 #1 SMP Thu May 4 15:21:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core
```

**Comment by bradcray** [comment]
Thanks for filing this, @psath!

For developers who might look into this, and to the question about what is generating the `-E` flags, for the `amudprun` launcher, I believe it's this code:

https://github.com/chapel-lang/chapel/blob/6c7c7873f552473ba36f8cdc036caa3a28641e7f/runtime/src/launch/amudprun/launch-amudprun.c#L63-L68

Interestingly, the launchers have not been refactored to share this logic between all our launchers that propagate environment variables in this way, so I'm not sure whether all launchers share this behavior of losing whitespace, or whether some do a better job of it than others.  For example, here's where the similar code is in the slurm-based launchers, which have definitely been exercised much harder than `amudprun` in our own work:

https://github.com/chapel-lang/chapel/blob/6c7c7873f552473ba36f8cdc036caa3a28641e7f/runtime/src/launch/slurm-gasnetrun_common/slurm-gasnetrun_common.h#L166-L177

**Comment by psath** [comment]
Hmmm even the workaround is fragile

When `GASNET_SSH_SERVERS` contains more than one, then it also becomes a breaking variable.

**Comment by bradcray** [comment]
That seems odd...  in that I'm fairly confident people have used GASNET_SSH_SERVERS in the field before...  Let me see if I can reproduce locally...

**Comment by bradcray** [comment]
@psath: 

executive summary: I believe if you change the line of your wrapper script that invokes `$@` to:

```bash
"$@"
```

the whitespace will be preserved and things should work as expected.  Let me know if this is not the case.

In more detail:

I did a test that makes me more confident that we are preserving whitespace properly in the `-E` arguments we create within our `amudprun` launcher code, so that was a relief.  That made me think that the problem is not in the code I pointed to above, but in some bad interaction with slurm or your shell script.

Digging into the shell script theory, I was able to reproduce the behavior you saw and fix it as follows.  First, the test I wrote and ran to convince myself that amudprun itself was working correctly:

**testit.chpl:**
```chapel
use CTypes;

extern proc getenv(str: c_ptrConst(c_char)): c_ptr(c_char);

coforall loc in Locales {
  on loc {
    var s = string.createBorrowingBuffer(getenv("FOO"));
    writeln(s);
  }
}
```

and an execution demonstrating it:

```bash
$ export FOO="Hi PSath!"
$ chpl testit.chpl
$ export GASNET_SSH_SERVERS="[redacted] [redacted] [redacted] [redacted]"
$ export GASNET_SPAWNFN=S
$ ./testit -nl 4
Hi PSath!
Hi PSath!
Hi PSath!
Hi PSath!
```

Then, I found if I added a simple wrapper script like yours:

**my_wrapper.sh**
```bash
#!/bin/bash

$@
```

I'd get problems similar to yours:

```bash
$ export CHPL_LAUNCHER_REAL_WRAPPER=/data/cf/chapel/bradc/chapel/my_wrapper.sh
$ ./testit -nl 4

<command-line arg>:41: error: Unexpected flag:  "PSath!"
<command-line arg>:41: error: Unexpected flag:  "PSath!"
<command-line arg>:41: error: Unexpected flag:  "PSath!"
<command-line arg>:41: error: Unexpected flag:  "PSath!"
```

However, once I changed the script to:

```bash
#!/bin/bash

"$@"
```

then things worked as expected again:

```bash
$ ./testit -nl 4
Hi PSath!
Hi PSath!
Hi PSath!
Hi PSath!
```

**Comment by bradcray** [comment]
Also, reviewing our slack conversation, I'm realizing that this is arguably on me / us for sending you a sample script without quotes.  (In my defense, I'm not familiar with this feature and was just passing along what I was sent... :) ).  I've edited the slack conversation to include the quotes for posterity.

**Comment by psath** [comment]
Doh! I glossed right over the field splitting happening in the wrapper's pass-through.

The opacity of what-launches-what on which node got the better of me. Thanks for your diligence in follow-up. I can now run an sbatch on multiple nodes, so I think we can safely close this as "Resolved, no error".

**Comment by bradcray** [comment]
Great, thanks for confirming, and I'm glad that the cause of the problem wasn't something deeper in our source code.
