### ISSUE TITLE
Use-before-def problem in queried argument values (when array types are involved?)

### ISSUE THREAD

**Issue by damianmoz** [chapel-lang/chapel#23533]
Please update the heading/title I have given this if it is imprecise or just plain wrong.

The following complains
```chapel
proc primefactorsfill(f : [?D] uint(?w), r : [D] uint(w))
{
    ...
}
```
It says that _w_ is used before being defined.

**Comment by damianmoz** [comment]
This works:
```chapel
proc fftplanfactors(n : uint(?w), ufr : [?uD] uint(w))
{
   // use uint(w) within the routine
...
}
```
This fails:
```chapel
proc fftplanfactors(ufr : [?uD] uint(?w), n : uint(w))
{
   // use uint(w) within the routine
...
}
```
Hope this helps.

**Comment by dlongnecke-cray** [comment]
It looks like `fixupArrayFormal` in `normalize` is just straight up deleting the type query?! What the heck...

**Comment by dlongnecke-cray** [comment]
It's kind of silly, but I'm just going to extend the current cloning we do today to apply to `[?d] int(?w)` as well.

**Comment by bradcray** [comment]
Thanks for filing this @damianmoz, and for improving the state of things, @dlongnecke-cray!  Damian, if you get a chance to try out the fix in your code, please let us know if you're seeing the expected behavior now.

**Comment by damianmoz** [comment]
Next week. Thanks
