### ISSUE TITLE
Nested function bug

### ISSUE THREAD

**Issue by damianmoz** [chapel-lang/chapel#23560]
I have attached a piece of chapel.
```chapel
proc _fftfactors(...)
{
}
proc fftfactors(...)
{
   ... return _fftfactors(...);
}
```
works.

The scope of _fftfactors() is only within fftfactors(). But if you move the first routine inside the second, ...
```
bug-pf.chpl:44: internal error: AST-EXP-0312 chpl version 1.31.0

Internal errors indicate a bug in the Chapel compiler,
and we're sorry for the hassle.  We would appreciate your reporting this bug --
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.
```
Working and buggy routine attached. Sorry for my earlier fat fingers.

Note my updated code.

[bug-pf.chpl.txt](https://github.com/chapel-lang/chapel/files/12776276/bug-pf.chpl.txt)
[pf.chpl.txt](https://github.com/chapel-lang/chapel/files/12776277/pf.chpl.txt)

**Comment by damianmoz** [comment]
I have attached a piece of chapel.
```chapel
proc _fftfactors(...)
{
}
proc fftfactors(...)
{
   ... return _fftfactors(...);
}
```
works.

The scope of _fftfactors() is only within fftfactors(). But if you move the first routine inside the second, ...
```
bug-pf.chpl:44: internal error: AST-EXP-0312 chpl version 1.31.0

Internal errors indicate a bug in the Chapel compiler,
and we're sorry for the hassle.  We would appreciate your reporting this bug --
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.
```
Working and buggy routine attached. Sorry for my earlier fat fingers.
[pf.chpl.txt](https://github.com/chapel-lang/chapel/files/12776101/pf.chpl.txt)
[bug-pf.chpl.txt](https://github.com/chapel-lang/chapel/files/12776102/bug-pf.chpl.txt)

**Comment by jabraham17** [comment]
Here is a small reproducer. The problem seems to originate from nested functions with type queries and is dependent on order. In the below example, switching the type of `x` and `y` compiles. And making both queries on `uint` or both queries on arrays works.

```chapel
proc foo(x: uint(?w)) {
  proc bar(y: [?D]) {}
}
foo(10:uint(32));
```

**Comment by bradcray** [comment]
Thanks for filing this @damianmoz, and for the quick look @jabraham17!  I've moved the content of Damian's first post into the OP, just for convenience for people coming back to this issue later.

Note the thematic relationship to other recently opened issues from Damian: https://github.com/chapel-lang/chapel/issues/23533 and https://github.com/chapel-lang/chapel/issues/23302

**Comment by damianmoz** [comment]
Next week. Thnks
