### ISSUE TITLE
Bad error message when casting to a generic class type

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#23623]
### Summary of Problem

When casting a superclass to a generic class type, we get a fairly inscrutible error message from within the internal modules rather than something user-facing suggesting that casting to a generic type is not meaningful/supported (which I think is our intention?).

### Steps to Reproduce

**Source Code:**

```chapel
class C {
}

class D: C {
  type t;
}

var myC: C = new shared D(int);
writeln(myC: shared D);
```

Today generates:

```bash
$CHPL_HOME/modules/internal/ChapelBase.chpl:2344: In function ':':
$CHPL_HOME/modules/internal/ChapelBase.chpl:2350: error: cannot default-initialize a variable with generic type
$CHPL_HOME/modules/internal/ChapelBase.chpl:2350: note: '<temporary>' has generic type 'unmanaged D'
$CHPL_HOME/modules/internal/ChapelBase.chpl:2350: note: cannot find initialization point to split-init this variable
testit.chpl:9: note: '<temporary>' is used here before it is initialized
  $CHPL_HOME/modules/internal/SharedObject.chpl:647: called as :(x: unmanaged C?, type t = unmanaged D)
  within internal functions (use --print-callstack-on-error to see)
note: generic instantiations are underlined in the above callstack
```

**Compile command:**
`chpl testit.chpl`

### Configuration Information

- Output of `chpl --version`: `chpl version 1.32.0`

**Comment by mppf** [comment]
I think we do support some forms of casting to a generic type. These work:

``` chapel
writeln(myC: borrowed);
writeln(myC: class?);

var myD: shared D(int) = new shared D(int);
writeln(myD: C);
writeln(myD: shared C);
```

That leads me to think:
 1. That I intended for this case to work (although we have been removing some of these)
 2. The problem here is specific to class downcasting.

**Comment by bradcray** [comment]
@dlongnecke-cray : I'm wondering how confident you are that your PR should've closed this issue.  Specifically, @mppf seemed to suggest above that this behavior should potentially ultimately be supported.  Did you conclude that it should not be?  (or maybe "should not be in cases like the one in the OP?").

**Comment by dlongnecke-cray** [comment]
I'm not sure how downcasting to a generic subclass without defaults or subs is supposed to work. Is there a way to support it? I'll open a followup issue if so.

**Comment by mppf** [comment]
I think it could work in either of these cases:
 * the cast is to an instantiation e.g. `myC: shared D(int)`
 * the generic part is in the parent class e.g. `class CC { type t } class DD: CC { }` `myCC: shared DD;`

**Comment by dlongnecke-cray** [comment]
I think those cases are both supported today, and I feel like we'd all agree that we want them to remain supported. In that case, do we still need a followup issue?

```chapel
class C1 {}
class D1 : C1 { type T; var x: T; }
class C2 { type T; }
// Could specify 'int' instead of '?' or when initializing super.
class D2 : C2(?) {}

proc main() {
  // Cast to an instantiation.
  var c1: owned C1 = new owned D1(int);
  var d1 = c1 : owned D1(int);

  // Generic part is in the parent class.
  // Subclass could also instantiate directly to get rid of the (int) in the cast.
  var c2: owned C2(?) = new owned D2(int);
  var d2 = c2 : owned D2(int);
}
```

**Comment by bradcray** [comment]
I agree that if cases we'd want to support work today, there's no need for a follow-up issue.
