### ISSUE TITLE
Which device properties should we expose to the user?

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#23638]
GPUs have several characteristics that can be queried by the application. But [there a lot of them](https://docs.nvidia.com/cuda/cuda-runtime-api/structcudaDeviceProp.html#structcudaDeviceProp), and most of them should be irrelevant to the user. Which ones are important and should be exposed to the user?

The following can help with the application logic:
- `multiProcessorCount`
- `maxThreadsPerBlock`
- `warpSize` (but I think we can do this without asking the device, see https://github.com/chapel-lang/chapel/issues/23599)

Maybe the following can help with diagnostics:
- `memoryBusWidth`/`memoryClockRate`

**Comment by e-kayrakli** [comment]
I imagine we can expose them as methods/fields in the locale type. Currently, we can't do `here` in GPU kernels, so it may require us to do an interim solution first. (https://github.com/chapel-lang/chapel/issues/22147)

**Comment by razoumov** [comment]
I would add a variable identifying the device, e.g. something like "Tesla P100-PCIE-12GB" returned by `nvidia-smi` -- this would be very useful on a heterogeneous HPC cluster with multiple GPU types. Not sure if `char cudaDeviceProp::name` returns that information, but something along those lines.
