### ISSUE TITLE
Internal error when var is undefined and passed to zip

### ISSUE THREAD

**Issue by mstrout** [chapel-lang/chapel#23653]
### Summary of Problem
While putting together the index gather story for the tutorial, I got an internal compiler error.  Below is a reproducer.

### Steps to Reproduce

**Source Code:**

```chapel
use BlockDist;
//use CopyAggregator;

config const numUpdates = 10;
var Src = [1, 2, 3, 4, 5];
var Dest: [0..<numUpdates] int;

{
  const D = blockDist.create({0..numUpdates-1});
  var Inds: [D] int;

  forall (d, i) in zip(Dst, Inds) with (var agg = new SrcAggregator(int)) do
    agg.copy(d, Src[i]);
}
```

**Compile command and error:**
```
chpl replicate.chpl 
replicate.chpl:12: internal error: OPT-FOR-ONS-1181 chpl version 1.32.0
Note: This source location is a guess.

Internal errors indicate a bug in the Chapel compiler,
and we're sorry for the hassle.  We would appreciate your reporting this bug --
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.
```

### Configuration Information

Homebrew on an Intel Mac.

**Comment by ronawho** [comment]
Don't think this is aggregator specific since it fails without aggregators too:

```chpl
  forall (d, i) in zip(Dst, Inds) do
    d = Src[i];
```

If you give it an empty loop:

```chpl
 forall (d, i) in zip(Dst, Inds) { }
```

I get the right error message that `Dst` is undeclared (typo, should be `Dest`).

Note also that `blockDist.create` should be `blockDist.createDomain`

**Comment by mstrout** [comment]
>I get the right error message that Dst is undeclared (typo, should be Dest).

@ronawho is right.  Fixing the typo makes the internal error go away.  So it isn't aggregation.  Instead it is probably the compiler doing something strange when attempting to resolve an undefined symbol `Dst` when in a call to `zip`?
