### ISSUE TITLE
Querying sublocale ID with the GPU locale model

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#23650]
There's no user-facing way to query a device's ID today. The device ID is important when doing a static work distribution to compute the chunk of data that needs to be processed by a specific GPU.

The non-user-facing way is as follows:

```chpl
on Locales[1].gpus[0] {
  writeln(here);     // LOCALE1-GPU0
  writeln(here.id);  // 1  [this is the locale ID]
  writeln(((here._instance):GPULocale).sid);  // 0  [this is the sublocale ID]
}
```

What should be the interface for this?

### Option 1. `locale.sid` ("s" for sublocale)

- PRO: short and sweet
- CON: too short, not self-documenting

### Option 2. `locale.sublocId`

- PRO: More self-documenting
- CON: Too long (?)

### Option 3a. Make `locale.id` return a tuple in a sublocale

- PRO: Notionally, ID consists of the parent's ID and the sublocale ID. Captures that well.
- CON: Might be an overkill
- CON: `here.id[1]` is not very self-documenting 
- CON: Have to build a tuple for `here.id` instead of just returning an int

### Option 3b. Make `locale.id` return a record in a sublocale

- PRO: Same as 2a
- PRO: More self-documenting
- CON: Have to build a record for `here.id` instead of just returning an int

**Comment by stonea** [comment]
I have a PR for that here: https://github.com/chapel-lang/chapel/pull/25943

I don't think we should change the behavior of `id` (especially post Chapel 2.0). Realistically GPUs are the only thing using sublocales these days and I don't think there's a need or benefit to try and generalize.
