### ISSUE TITLE
Loops with zero trip count trigger an internal error when run on the GPU 

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#23658]
```chpl
on here.gpus[0] {
  var Arr: [1..10] int;
  foreach i in 1..0 do {
    Arr[i] = i;
  }
  writeln(Arr);
}
```

results in

```
internal error: gpu-nvidia.c:247: Error calling CUDA function: invalid argument (Code: 1)
```

during execution. This is because we compute number of threads to be 0, and use a grid with dimensions `(0,1,1)` which is not supported, at least by CUDA.

We should not try to launch kernels if number of threads is <=0.

A question that we should answer is whether GpuDiagnostics should register a loop like that as a kernel launch, or not. My initial reflex was that "Yes, it should." Because we wouldn't really special case this case if the underlying driver was accepting our arguments. So, if we are excluding this case from GpuDiagnostics' counting, we'd be exposing an implementation detail to the user in ways that can be confusing.

Thinking about that more, I am more on the fence. Imagine a hypothetical scenario where we may choose between GPU/CPU execution based on some loop characteristic either statically or dynamically potentially as an optimization. In such a scenario, I would want GpuDiagnostics to reflect the actual behavior. The question here doesn't feel much different, so, maybe the loop in the snippet above should *not* register as a launch?

**Comment by ShreyasKhandekar** [comment]
I have the PR linked above that adds an if statement to avoid the kernel launch. I did not make any changes to the GPU diagnostics yet.

**Comment by stonea** [comment]
> A question that we should answer is whether GpuDiagnostics should register a loop like that as a kernel launch, or not. My initial reflex was that "Yes, it should."

My initial reflex would be the opposite. If we're not launching a kernel then why would we count it as a kernel launch?

**Comment by e-kayrakli** [comment]
I agree with Andy and Brad -- it should not count as a launch.

My point in the OP:

> Imagine a hypothetical scenario where we may choose between GPU/CPU execution based on some loop characteristic either statically or dynamically potentially as an optimization. In such a scenario, I would want GpuDiagnostics to reflect the actual behavior.

Resonated more and more over time for me. My slightly more practical thought experiment for this case was: imagine we have an optimization where we don't fire kernels for loops that trip less than 10 times. What do you expect GpuDiagnostics to do in that case? My answer to that is very clear and that it should not count that as a launch.
