### ISSUE TITLE
`--detailed-errors` requests

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#23706]
The `--detailed-errors` flag is great, but would be even better if:

* it were a user-facing flag (rather than a `--devel` flag) so that it would show up in `man` page and the typical user's `--help` output
* it had an environment variable that could be used to set it for someone who wanted it on by default (in general, most flags—and particularly most user-facing flags—should have an environment variable, by convention)

**Comment by DanilaFe** [comment]
Both of these things were accomplished in #23715. Closing the issue; feel free to re-open if something was missing.
