### ISSUE TITLE
Extern blocks fail to link with `CHPL_GPU=amd` and `CHPL_LLVM=bundled`

### ISSUE THREAD

**Issue by jabraham17** [chapel-lang/chapel#23735]
When compiling code for the GPU locale model with `CHPL_GPU=amd` and using the bundled LLVM, the code fails to link.

This occurs in our test suite, in `test/gpu/native/extern/main.chpl`. This test compiles and runs fine with the flat locale model and in the gpu locale model with `CHPL_GPU` set to `nvidia` or `cpu`. It only fails with amd

### Steps to Reproduce

```
export CHPL_GPU=and
export CHPL_LOCALE_MODEL=gpu
chpl test/gpu/native/extern/main.chpl
```

### Error

```
clang-15: error: unable to execute command: Executable "lld" doesn't exist!
clang-15: error: amdgcn-link command failed with exit code 1 (use -v to see invocation)
error: Compile C File
```

### Configuration Information

- Output of `chpl --version`: chpl version 1.33.0 pre-release (e20c63f134)
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: gpu *
  CHPL_GPU: amd *
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: bundled
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: LLVM version 15.0.7, gcc version 7.5.0

**Comment by e-kayrakli** [comment]
It looks like we are getting by in our nightly testing for this test. I wonder how that could be.

In any case, for linking we need to use the lld that's bundled with the ROCm installation we use. I bumped into this in my effort to wrap some reduction libraries. Even though I backed away from supporting AMD there, I left the fix for this in https://github.com/chapel-lang/chapel/pull/23689/files?diff=unified&w=0#diff-32227b333833b287cbe3c32f2ac41d8689fb69236c82f321fa039155c4cd5d09. So, that PR might fix this issue.

**Comment by jabraham17** [comment]
> It looks like we are getting by in our nightly testing for this test. I wonder how that could be.

 I suspect because we don't test bundled LLVM with the GPU locale model.

> So, that PR might fix this issue.

I pulled out the relevant fix, appending `-B path/to/amd/llvm`. That helps slightly, in that now there is a different error.

```
clang-offload-bundler: Unknown command line argument '-input=/dev/null'.  Try: '/opt/rocm-4.5.2/llvm/bin/clang-offload-bundler --help'
clang-offload-bundler: Did you mean '--inputs=/dev/null'?
clang-offload-bundler: Unknown command line argument '-input=/tmp/extern_c_test-ffbfb7/extern_c_test-gfx908.out'.  Try: '/opt/rocm-4.5.2/llvm/bin/clang-offload-bundler --help'
clang-offload-bundler: Did you mean '--inputs=/tmp/extern_c_test-ffbfb7/extern_c_test-gfx908.out'?
clang-offload-bundler: Unknown command line argument '-output=/tmp/extern_c_test-5b1e27.hipfb'.  Try: '/opt/rocm-4.5.2/llvm/bin/clang-offload-bundler --help'
clang-offload-bundler: Did you mean '--outputs=/tmp/extern_c_test-5b1e27.hipfb'?
clang-offload-bundler: for the --inputs option: must be specified at least once!
clang-15: error: amdgcn-link command failed with exit code 1 (use -v to see invocation)
error: Compile C File
```

**Comment by e-kayrakli** [comment]
> I suspect because we don't test bundled LLVM with the GPU locale model.

On our typical nightly testing system, we do use bundled. But maybe we don't use it on the system you ran this?

> I pulled out the relevant fix, appending -B path/to/amd/llvm. That helps slightly, in that now there is a different error.

Huh... that's very strange. That's the reverse of the deprecation warning I'd expect as noted in https://github.com/chapel-lang/chapel/issues/23480.

This feels like a version mismatch of sorts.. We use a different clang-based compiler (newer versions have `-input`) to compile the extern code vs ours (older versions have `-inputs`, as used by our compiler today) maybe?

**Comment by e-kayrakli** [comment]
Thematically related to https://github.com/chapel-lang/chapel/issues/23542. Not sure if they can be both resolved in the same effort, though. This one feels a bit more esoteric.
