### ISSUE TITLE
Bad compiler behavior when two files define the same module

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#23775]
While compiling a program that defines the same module name in two distinct files, I am seeing:

```
internal error: UTI-MIS-1041 chpl version 1.32.0

Internal errors indicate a bug in the Chapel compiler,
and we're sorry for the hassle.  We would appreciate your reporting this bug --
please see https://chapel-lang.org/bugs.html for instructions.

make: *** [Makefile:340: arkouda_server] Error 1
make: Leaving directory '/home/duzh/tmp/arkouda'
```

Using the debugger as a Chapel developer, I'm finding that this is due to the line:

```chapel
      CHPL_ASSERT(realPath == realGotPath);
```

which @DanilaFe let me know indicates that two Chapel files defined a module with the same name.  Once I realized that and jumped into the debugger/modified the compiler to let me know about such cases, I was able to get past the assertion.

This issue asks two questions:
1) Can we turn this from an internal assertion error into a nice user-facing error message?
2) When compiling in non-developer mode, should our `CHPL_ASSERT()` mechanism generate something that is more specialized / specific to the assertion or assertion's location than simply a segfault?  E.g., As a developer, it took me awhile to determine that the segfault was due to this assertion (and the user was never able to when trying to lead them through it).  If instead the internal error's encoding had pointed me to the assertion's location itself, it would've been much faster to get to the heart of the issue.

### Steps to Reproduce

**Source Code:**

testit.chpl:
```chapel
module M { }
```

testit2.chpl:
```chapel
module M { }
```

**Compile command:**
`chpl testit.chpl testit2.chpl`

**Associated Future Test(s):**

### Configuration Information

- Output of `chpl --version`: `chpl version 1.32.0`

**Comment by DanilaFe** [comment]
Just noting here that this issue / gotcha (not being able to load files with the same module) has come up when using the Python bindings, where we specifically use a different `Context` for different files to avoid hitting this bug. 

https://github.com/chapel-lang/chapel/blob/55543983e5ffc0c8a9efdd337643ffcc0e306a7d/tools/chapel-py/chapel/__init__.py#L225-L233

**Comment by bradcray** [comment]
I'm looking into whether I can put a fix in for question 1 with minimal effort.  Question 2 is likely to need to be owned by someone more familiar with the dyno architecture than I am.

**Comment by bradcray** [comment]
#23780 resolves the main issue that I opened this issue for.  I was keeping it open to wrestle with question 2 or fork it off to its own issue, but have been unable to reproduce it well enough to do so.  Specifically, what a user reported seeing was:

```
internal error: UTI-MIS-1041 chpl version 1.32.0

Internal errors indicate a bug in the Chapel compiler,
and we're sorry for the hassle.  We would appreciate your reporting this bug --
please see https://chapel-lang.org/bugs.html for instructions.

make: *** [Makefile:340: arkouda_server] Error 1
make: Leaving directory '/home/duzh/tmp/arkouda'
```

which essentially is a standard seg fault.  I thought that I had reproduced this as well which is what caused me to file question 2.  However, today, I'm unable to.  Either I'm in developer mode and get a reasonable printout from the assertion followed by an abort trap.  Or I'm in user mode and we skip past the assertions.  I've tried recompiling with various ASSERTS=1, DYNO_ENABLE_ASSERTIONS=1, etc. combinations but can't figure out how a user (and potentially I) got a segfault from an assertion...  Hmmm...
