### ISSUE TITLE
Stabilizing Associative Domains and Arrays

### ISSUE THREAD

**Issue by ShreyasKhandekar** [chapel-lang/chapel#23842]
# Stabilizing Associative Domains

Preparing for the discussion about unstable domains and making them stable.

### What is the API being presented?

Associative Domains are commonly used to represent arbitrary sets or to represent a set of keys for a dictionary/hash table.
Arrays defined over an Associative Domain is an Associative Array and is used to provide map-like functionality to the language.

Both Associative domains and arrays were marked unstable in 1.32 and need improvements before they can be marked stable.

### How is it intended to be used?

Currently, stable Map and Set-like functionality is being provided using `Set` and `Map` modules. Associative domains and arrays are meant to support similar functionality.

There is a question as to why we would want to support both the `map` and `set` types as well as associative domains and arrays if they are intended to provide the same functionality.

### How is it being used in Arkouda and CHAMPS?

In Arkouda:
Associative Domains are used just in `src/In1d.chpl:43`
- To convert an array to a set
- It uses `parSafe=false` (This is relevant since `parSafe` was a motivating factor in marking associative domains as unstable, more on this later)
- https://github.com/Bears-R-Us/arkouda/blob/02c3a04a173028dc9e9c3d6c327cf39826488431/src/In1d.chpl#L43

In CHAMPS:
- 1 instance

In `release/examples`:
- 16 instances

### What's the history of the feature, and why is it unstable?

Associative domains have been around since 2006 in `_chpl_adomain.chpl` which was renamed `_Arrays.chpl` in 2007 and then `ChapelArray.chpl` and finally refactored into `ChapelDomain.chpl` in 2021.

The ways to create an associative domain have also evolved over the years to use different arguments, but currently, there are two ways to create an associative domain:
1. Using domain literals : `var x = {"a", "b"}`
2. Using domain types    : `var x = domain(string)`

Both of these ways to create associative domains were marked as being unstable in https://github.com/chapel-lang/chapel/pull/23117

The reason we marked associative domains as unstable:
1. `parSafe` is an issue (From the release slides):
    1. They rely on a global lock for parallel safety, which encourages non-scalable coding practices. For example, this would not scale well in a scenario where an associative domain is built concurrently by adding individual elements.
    See [this comment](https://github.com/chapel-lang/chapel/issues/21330#issuecomment-1668787373).
    2. The setting `parSafe=true` leaves some cases where parallel safety is still not ensured:
        ```chapel
        var Keys: domain(int);
        var Counts: [Keys] atomic int;
        forall key in someInput with (ref Keys, ref Counts) {  
          Keys.add(key);         //This update in Task 1 can cause resizing+rehashing of ‘Counts’ and ... 
          Counts[key].add(1);    // invalidate this ref to ‘Counts[key]’ in Task 2, leading to a lost increment  
        }  
        ```
    4. See https://github.com/chapel-lang/chapel/issues/8339

2. During a weekly meeting, Vass pointed out some inconsistencies between binary operations on ranges and domains vs on associative domains. 
    1. These are operations like `(range) * (range)` and `(range) (+ or ** or -) (integral)`
    2. See https://github.com/chapel-lang/chapel/issues/19254 and https://github.com/chapel-lang/chapel/issues/17101
    3. See Vass' demo on Sep11,2023: https://github.hpe.com/hpe/hpc-chapel-docs/blob/main/notes/weeklyMeetings/2023-09-11-weekly-meeting-notes.txt
         * These are considered unstable for 2.0 
3. Casting from associative domains on strings relies on IO.
    1. See https://github.com/chapel-lang/chapel/issues/23385

Other than the issues listed, I could not find discussion notes where any votes were cast regarding this topic or indicating any consensus was ever reached.

### Are there known Github issues with the feature?

Issues related to the stability of the feature:

1. uniform handling of supported vs unsupported operations on domains https://github.com/chapel-lang/chapel/issues/19093
2. Supporting non-nilable types https://github.com/chapel-lang/chapel/issues/17720
3. Default task intents https://github.com/chapel-lang/chapel/issues/17221
5. Fix how {MyDomain} is interpreted https://github.com/chapel-lang/chapel/issues/15629
    * Related: https://github.com/chapel-lang/chapel/issues/7723
7. Printing associative arrays https://github.com/chapel-lang/chapel/issues/11455 and domains https://github.com/chapel-lang/chapel/issues/11568
8. Syntax for creating associative arrays is over-sugared? https://github.com/chapel-lang/chapel/issues/11380
9. Resizing arrays https://github.com/chapel-lang/chapel/issues/22770

Many other issues relate to associative domains but they seem more along the lines of memory management or other things that are only tangentially related to associative domains and unrelated to their stability.

### A special look into Python dictionaries

Python has dictionaries that provide map-like functionality as a feature built into the language itself rather than a separate library. They share the following characteristics with associative arrays in Chapel:

1. Python's dictionaries and associative arrays share the fact that they are a language feature rather than a module/library.
2. They both support creating a pre-populated map with syntax like:
    ```chapel
    var DaysInMonth = ["June" => 30, "January" => 31, "September" => 30];
    ```
3. They support adding keys/value pairs to the dictionary/associative array implicitly with syntax like:
    ```chapel
    DatsInMonth["May"] = 31;
    ```
    With a few exceptions in Chapel when we have multiple arrays over the same *named* domain which takes away the ability to modify the domain like this. Although maps also support the overload of the `[]` operator
3. They both support operations like reductions or sorting

But the dictionaries and sets also share a resemblance to the `map` and `set` types in Chapel due to the following reasons:

1. The fact that they are separate entities in Python; whereas we define our associative arrays over associative domains so they are closely coupled.
2. When creating an associative array over a domain, we have a key-value pair where the value is default-initialized based on the type. Whereas in Python it seems we have to explicitly provide key-value pairs which is the same case in our `map` type.

 ### Why do we have both Map and Set types along with associative arrays and domains?

The following are thoughts from Lydia when presented with the above question:

1. Associative arrays can be created with a fully populated domain from the start, generating a default value for any corresponding values. But I could see adding an “addKey” method to `map`s that does the same thing.
2. The ability to use it with the normal domain syntax gives a generality when writing arrays, regardless of their index type. Some of this can be available for maps, we do overload the `[]` operator, but the domain declaration is pretty unique to arrays and efficiently creates a data structure that is ready to use (the domain). 

3. We could maybe make a method on maps called `addKeys`, but that will still have paid the cost of creating the domain or bundling the collection of keys all at once before using it in the map itself. Additionally, having a domain created in this way allows easy and efficient reuse for multiple arrays, as well as enabling easy comparison between associative arrays and other types of arrays if you swap out the domain, assuming you’ve written your code generally enough. 
    
    E.g.
    ```
    var d = { "apples", "oranges", "raspberries"};
    var a: [d] int;

    forall i in a.domain {
    writeln(a[i]);
    }
    ```
    can be changed to use an entirely different style of domain just by changing “d” to be something else, without having to update the array or the forall traversing it. 
4. Changing a map would more frequently be burdensome (though with an `addKeys`, it could get closer to that ease).
The ability to use the `=>` syntax when defining an associative array literal is also helpful. This involves compiler support, which we enable because arrays are a foundational part of the language, while maps and sets are much more of a library construct and so wouldn’t necessarily be as tied to the compiler implementation. This is partially because we want users to be able to write their own collections in the future, using as little compiler magic as possible. There may be ways that we could enable users to opt into such functionality for their types, though (but that’s probably too much of a side tangent).

I think what I’d boil it down to is:
1. Associative arrays and domains are important because they are arrays and domains.
    - They can rely on the same syntax as other arrays and domains in many cases, making a “plug and play” style of programming more possible
    - They benefit from the compiler knowing and defining parts of their existence in ways that we don’t want to do for maps and sets so that other collection types can be developed in the future without the compiler having to know any details about them
    - As a result, they are better fits for use cases that feel like other arrays, for experimentation with different associations between what is stored in the array. When the mapping between keys and values is more obvious or strict, a map is probably the better tool.
2. Over time, the differences between `map`s/`set`s and associative arrays and domains may become more blurred, and that may cause us to want to replace associative arrays/domains with maps and sets. But design work would be needed to provide the same functionality in maps/sets, and it would require us to have confidence that users won’t have any more new map/set ideas, or at least have a way to generally enable the same functionality.

It also might be worth investigating the “array-as-vec” effort and why we moved away from that.

From what Lydia said above, to me it seems that associative arrays and domains cover almost all the use cases (or are intended to cover all use cases) where one might consider using `map`s or `set`s. 
- So we must ask in what sorts of programs would you encourage using associative arrays and domains over maps/sets? Vice versa? 
- Would we even want to use the map or set functionality if associative arrays and domains always cover what we need? And if so does it make sense to have both?

### Are there features it is related to? What impact would changing or adding this feature have on those other features?

Some of the listed issues do affect arrays as a whole, but the `parSafe` issues are isolated to just associative domains and arrays. Some issues (like binary ops) affect ranges as well, but they are also unstable so we can change those as we wish for now.

Other than that I'm not sure of the scope to which this could affect other features.

### How do you propose to solve the problem?

Million dollar question.

**Comment by bradcray** [comment]
w.r.t.

> 6. Syntax for creating associative arrays is over-sugared? https://github.com/chapel-lang/chapel/issues/11380

I just verified that this has already been resolved and that I apparently had forgotten to close the issue due to it being a duplicate of #18887.  So that one doesn't require any more attention.

**Comment by ShreyasKhandekar** [comment]
From our discussions we came up with two conclusions:
1. To make progress on removing the blanket unstable warning from associative domains/arrays, focus on making parSafe itself unstable as follows:
    * Work towards flipping the default to `parSafe=false` with a gentle path for those relying on the default make any use of `parSafe` as unstable
    * In addition, we will improve the documentation of `parSafe` to clarify what it does or does not cover.
 2. For printing associative domains and arrays we decided that the default format of associative arrays and domains is unstable, along with other things like arrays, records, classes, etc. Because these haven't received any review. Another sub team should be put together to review these output as well as decide how to communicate to users that they are unstable.

Other issues were considered to not be relevant for stabilizing associative domains and arrays today.

**Comment by ShreyasKhandekar** [comment]
Note that another action item that was beyond the scope of this ad hoc sub team is to discuss what our strategy is regarding the fact that we have both maps and sets and associative arrays and domains. The notes and this issue have some healthy discussion about the unique functionality of both and why we want to keep them both. However a user story of what kind of cases ask for which feature is what we need. In short:

> So we must ask in what sorts of programs would you encourage using associative arrays and domains over maps/sets? Vice versa?

Is still unanswered.

**Comment by ShreyasKhandekar** [comment]
With the PR https://github.com/chapel-lang/chapel/pull/24352. Associative Domains are stable, this should have been closed automatically.
