### ISSUE TITLE
Clarify documentation around profiling based on user feedback

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#23858]
[This user interaction in gitter](https://matrix.to/#/!PBYDSerrfYujeStENM:gitter.im/$4uNFo8brXXcRa-IGXUtHeAGzPasQZlSz3YZHobxGxr0?via=gitter.im&via=matrix.org&via=gnome.org) suggests that our profiling documentation isn't particularly up-to-date w.r.t. the LLVM back-end coming online, and checking a few key documents, it looks like other clarifications are possible as well (like that building with PROFILE=1 or similar options only affects the runtime and third-party code, not the Chapel installation as a whole).

**Comment by psath** [comment]
The settings I was able to get gprof working on both 1.31 and 1.32 were as follows:
Runtime/compiler built with:
```
CHPL_GPU=cpu
CHPL_LOCALE_MODEL=flat
CHPL_HOST_COMPILER=gnu
CHPL_TARGET_COMPILER=gnu
DEBUG=0
OPTIMIZE=1
PROFILE=1
```

User code built with:
```
--fast --ccflags -pg --ldflags -pg
```
(GPU loops were manually refactored to run on CPU to steer clear of #23859)
