### ISSUE TITLE
Separate compilation serialization hitting an internal error

### ISSUE THREAD

**Issue by jeremiah-corrado** [chapel-lang/chapel#23929]
When running separate compilation serialization on a module that uses both the `Set` module and the new `NPBRandom` package module (added in https://github.com/chapel-lang/chapel/pull/23752), the compiler hits an internal error.

**Steps to reproduce:**

A) see the future under: `test/separate_compilation/serialization/`**
or
B) add `use Set;` to the `Random` module and run the `test/separate_compilation/serialization/testGenLib` test. It will fail in the fourth configuration with:
```
[Error matching compiler output for separate_compilation/serialization/buildAll]
[Compiler output before prediff was as follows:]
1 { loadLibraryFileQuery (testGenLib.dyno) hash: 0xadde0481aa70f1a8
1   loadLibraryFileQuery UPDATED }
0 SETTING FILE PATH FOR MODULE testGenLib -> testGenLib.chpl
1 { loadLibraryFileQuery (MyMod.dyno) hash: 0x702f7fe6cc3e657
1   loadLibraryFileQuery UPDATED }
0 SETTING FILE PATH FOR MODULE MyMod -> MyMod.chpl
1 { loadLibraryFileQuery (OtherMod.dyno) hash: 0xc2faaf1aab2f8afd
1   loadLibraryFileQuery UPDATED }
0 SETTING FILE PATH FOR MODULE OtherMod -> OtherMod.chpl
1 { loadLibraryFileQuery (chpl_standard.dyno) hash: 0x35c24d1675155f7e
1   loadLibraryFileQuery UPDATED }
internal error: UTI-MIS-1041 chpl version 1.33.0 pre-release (48835239d0)

Internal errors indicate a bug in the Chapel compiler,
and we're sorry for the hassle.  We would appreciate your reporting this bug --
please see https://chapel-lang.org/bugs.html for instructions.
```
Note that in this configuration, the library is compiled with `chpl_standard.dyno` (unlike the first three configs of this test which only include dyno files from some adjacent modules).

This bug was discovered while moving the `NPBRandom` module from a sub-module of `Random` to a separate package module which is `public import`ed in `Random`. As a work around, the use of a `set` in Random was replaced with an associative domain.

**Comment by mppf** [comment]
I've created PR #24032 to fix this.
