### ISSUE TITLE
Serial user loops can result in kernel launch / order-independence when the iterator has a nested loop

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#23993]
```chpl
use GpuDiagnostics;

var counter = 0;

config const runOnGpu = true;

on if runOnGpu then here.gpus[0] else here {
  var A: [0..100] int = 1;

  startGpuDiagnostics();
  for i in myIter() {  // Loop A
    A[i] += A[i+1];
  }
  stopGpuDiagnostics();
  writeln(A);
}

iter myIter() {
  foreach myI in 0..9 {  // Loop B
    for myJ in 0..9 {    // Loop C
      counter += 1;  // to make sure that this is not a trivial `for`
      yield myI*10+myJ;
    }
  }
}

writeln(getGpuDiagnostics());
```

Here, the user loop running `myIter` is not order-independent, and as such `foreach` is not used. However, when we inline the iterator, we only adjust the order independence of the yielding loop in the iterator. However, the order independence can be impacted by the outer loop if that exists.
Note that when inlined, the code looks like:

```chpl
startGpuDiagnostics();
foreach myI in 0..9 {  // Loop B
  for myJ in 0..9 {    // Loop C (order independence is determined by A and C)
    A[myI*10+myJ] += A[myI*10+myJ+1];
  }
}
stopGpuDiagnostics();
```

While generating that, we should also negate the order independence of B as A is not order independent.

Currently, this can result in unexpected races and kernel launches. @jabraham17, @stonea and I discovered this while working on https://github.com/chapel-lang/chapel/issues/23574. So, I expect this to be a problem when multidimensional domains are iterated with a `for` inside an `on here.gpus[0]`.

**Comment by e-kayrakli** [comment]
I can't pursue this further, but the simple case above can be fixed with

```diff
diff --git a/compiler/resolution/lowerIterators.cpp b/compiler/resolution/lowerIterators.cpp
index ed91c059eb..fec5c12ecd 100644
--- a/compiler/resolution/lowerIterators.cpp
+++ b/compiler/resolution/lowerIterators.cpp
@@ -1508,7 +1508,9 @@ static void markLoopProperties(ForLoop* forLoop, BlockStmt* ibody,

   for_vector(CallExpr, call, callExprs) {
     if (call->isPrimitive(PRIM_YIELD)) {
-      if (LoopStmt* loop = LoopStmt::findEnclosingLoop(call)) {
+      LoopStmt* loop = LoopStmt::findEnclosingLoop(call);
+      while (loop) {
+        std::cout << loop->id << std::endl;
         if (loop->isCoforallLoop() == false) {
           // If the for loop is not order independent, neither
           // should be the one we are replacing it with.
@@ -1523,6 +1525,9 @@ static void markLoopProperties(ForLoop* forLoop, BlockStmt* ibody,

           loop->setAdditionalLLVMMetadata(llvmAttrs);
         }
+        loop = LoopStmt::findEnclosingLoop(loop->prev);
+        if (loop && !ibody->contains(loop))
+          loop = nullptr;
       }
     }
   }
```

which walks out of the iterator's loop nest, marking everything based on the user loop's order independence. I haven't tested this patch on any other code.

**Comment by e-kayrakli** [comment]
One of the ideas that came up was whether `foreach` loops should be used sparingly. I don't agree with that -- I think if you're writing a loop and consider it to be an order-independent one, you should use a `foreach` instead of a `for`. This could give the compiler some optimization opportunities depending on the invocation site.

Although, I do understand that it can be a bit of a slippery slope where the iterator implementor's code can be executed on the GPU without careful consideration by them. But that's a very abstract concern.

Another idea was whether there should be an additional flavor of iterator to differentiate between non-task-parallel, order-dependent and non-task-parallel, order-independent execution.

**Comment by jabraham17** [comment]
> which walks out of the iterator's loop nest, marking everything based on the user loop's order independence.

This makes me a little nervous of `foreach` becoming too transparent. Right now, if you use `foreach` you are asserting that whatever body of code executes will be order independent. But now we need code checking the users assertion? I'd rather flag to the user "hey you are misusing order-independant loops" than transparently fix their code for them. Maybe fix their code for them and produce a warning, so the user knows what happened?

The specific code we ran into with https://github.com/chapel-lang/chapel/issues/23574 was `these_help` in `DefaultRectangular`. I think we could argue that `foreach` was incorrectly used here since a serial iterator gets invoked by both order-independent `foreach` loops and order-dependent `for` loops.

> Another idea was whether there should be an additional flavor of iterator to differentiate between non-task-parallel, order-dependent and non-task-parallel, order-independent execution.

I would be more in favor of this option, possibly with compiler errors/warnings if you use a `foreach` in an order-dependent iterator.

**Comment by e-kayrakli** [comment]
> if you use foreach you are asserting that whatever body of code executes will be order independent

To me, this is an oversimplification. Irrelevant of who "you" is in this statement, `foreach` only asserts that the loop's body is order-independent. It doesn't guarantee order-independent execution in any way. Both the user loop and the iterator needs to be order-independent for the resulting loop to be order-independent.

One can argue that the rule can be confusing for the user. My stance: I am happy where we are, however, we probably need to do some improvements w.r.t. documenting iterator's order-independence somehow, or provide additional compiler capabilities for users to understand order-independent execution. Arguably `--report-gpu` is a step towards that, but I don't think it'd help here.
