### ISSUE TITLE
`Math` may not (currently) be re-exported

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#24010]
### Summary of Problem

While working on a demonstration of publicly re-exporting symbols, I tried putting a `public use Math;` into a program and got a number of errors about symbols defined twice:

```
testit.chpl:1: error: 'e' has multiple definitions in this scope
testit.chpl:1: note: it was first defined through the 'use' of 'Math' here
$CHPL_HOME/modules/standard/Math.chpl:188: note: leading to the definition here
testit.chpl:1: note: redefined through the 'use' of 'Math' here
$CHPL_HOME/modules/standard/Math.chpl:181: note: and then through the 'use' of 'AutoMath' here
$CHPL_HOME/modules/standard/AutoMath.chpl:94: note: leading to the definition here
```

(and similarly for a number of other symbols).  I believe that this is due to the current structure of `Math` and "`AutoMath`".

I suspect that any proper fix for this that doesn't involve removing the deprecated symbols will be more work than it's worth.  But it might suggest removing the deprecated symbols sooner than we might otherwise (?).

### Steps to Reproduce

**Source Code:**

```chapel
public use Math;
```

**Compile command:**
`chpl testit.chpl`

### Configuration Information

- Output of `chpl --version`: `chpl version 1.33.0 pre-release (03e122cda3)`

**Comment by bradcray** [comment]
@lydia-duncan / @jabraham17 : Tagging you not because I'm deeply worried about this, but just because you're the two people who probably know the details best.

**Comment by jabraham17** [comment]
This seems to have been introduce with #23254, which changed `private use AutoMath` to `public use AutoMath` in `Math.chpl`, to allow qualified access of `AutoMath` symbols with the `Math` prefix. A possible solution may be to do `public use AutoMath only list,all,symbols`, and list the symbols we want to include.

Changing the line in `Math.chpl` to be as follows works.
```chpl
public use AutoMath only
  cbrt,sqrt,ceil,floor,round,trunc,conj,phase,riemProj,inf,nan,isFinite,isNan,max,min,isClose,sgn,signbit,abs,mod;
```

This workaround should only be necessary until we remove the deprecations.

**Comment by bradcray** [comment]
Ooh, I both love and hate that workaround!  (love that it works; hate its length.  But not enough to sit on it).  And thanks for the (super-)quick look!  Want to PR that?  Then we can see whether Lydia considers it acceptable and like a bug fix that could go in this week.

**Comment by jabraham17** [comment]
I can do that. Sadly I think that the actual list in a PR may be longer. That list doesn't include renamed symbols like `carg`. Which only exist in `AutoMath` and need to be in the list.

**Comment by bradcray** [comment]
Good point.  And that may be a reason not to do it since it could introduce unintended consequences if we miss something.  

Would an `except` list of the deprecated things work and be shorter/simpler?

All that said, this really isn't pressing to me (in the sense that it was a pre-existing condition, nobody has hit it other than me that we're aware of, and I think we could remove the deprecations right after this release (?).

**Comment by bradcray** [comment]
OK, thanks for the try.  I'm leaning even more to the "just live with this for now" direction based on this, assuming I'm right that these are due for removal after 1.33.  And if I'm not, it may warrant an accelerated removal.
