### ISSUE TITLE
Should `otherwise` blocks be allowed anywhere in `select` statements?

### ISSUE THREAD

**Issue by brandon-neth** [chapel-lang/chapel#24030]
While working on eliminating dead code paths in `select` statements, I discovered that according to the current [documentation](https://chapel-lang.org/docs/language/spec/statements.html#the-select-statement), "There may be at most one `otherwise` statement and its location within the select statement does not matter." 

I propose that we require `otherwise` statements, if present, to be the last in a select statement rather than allowing them to appear anywhere.

#### Supporting Reasons
1. Matches "control transfer to first match" rule
The order of branches of a `select` statement is semantically relevant. When multiple `when` clauses match, control is transferred to the first and the rest are skipped. See [this example](https://ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuhY3ZxUU5ScrpOXna2gqVHMpKBSn5qQmlygYGoB5CgrlGal5IF5KvkJ5UWZJak6ehpJbZlFxiYJvYklyhpKmNU5lwanJ-XkpqOrySzJSi8ozi1MRyvzykZXUctVycYGdYw1xIdShMAcDAA). Applying this rule to the situation where `when` statements follow an `otherwise`, the `when` statements will never be reached because the `otherwise` branch always matches. Requiring that `otherwise` statements appear only at the end resolves this contradiction.

2. Matches the natural language analogy
The syntax of the blocks within a `select` statement is based on an analogy to natural language. When giving a series of conditions and how to respond to them, the response of last resort (the `otherwise`) is always provided at the end. It's for the same reason that it doesn't make sense to put the final `else` block of an `else if` chain anywhere but the end.

3. Simplicity of compiler implementation
`select` statements need to be treated differently in the compiler based on whether an `otherwise` block is present. [For example](https://ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuha3GGULivKTFYpTc1KTSxxzyhMri4NSS0qL8oo1KqwUMvNKNBWquRSg8goVYI6CQnlGap6CoUJKvkIRWLGCgTVC3AhJ3BAinl-SkVpUnlmciiSlC5ar5arl4kJygkt-anEeikOo545aINbXhxqRArJIvQSmIDMNaGhmsYIdUFt-kYKNgqEeyGWQUIIGFizQAA), determining if a `select` statement is known to always return or throw. Allowing an `otherwise` statement to appear anywhere amongst the `when` statements complicates analysis, especially when `when` and `otherwise` statements are treated different.

#### Opposing Reasons
1. Breaking change
This is technically a breaking change, as previously valid programs will no longer be valid. However, no `select` statements in the Chapel test directory place an `otherwise` block anywhere but the end.

#### Impacts
- No select statements within the test directory or Arkouda have a `when` statement after an `otherwise` statement

**Comment by bradcray** [comment]
This change makes sense to me and seems close to a no-brainer.  I haven't been able to come up with any historical reason for why the spec would permit it to be elsewhere and the phrase has been in there [since the original draft](https://github.com/chapel-lang/chapel/blame/3d1bfbbd5e3d5bb23aff02954dddddb9c6a9ade7/spec/Statements/The_Select_Statement.tex).  The best guess I had was that it was a mis-application of the principle of permitting declarations to (generally) come in any order when the project was still just finding its footing.
