### ISSUE TITLE
question about implication of `const` intent on finding applicable candidates

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#24075]
After issue #21499 and some discussion, we updated the spec to leave more room for the implementation in deciding the meaning of the `const` and default intent. See https://chapel-lang.org/docs/language/spec/procedures.html#the-const-intent .

Something occurs to me though, which is that we allow implicit numeric conversions when using `in` / `const in` but not when using `const ref`. (For `const ref` we allow only subtype conversions). See also https://chapel-lang.org/docs/language/spec/procedures.html#legal-argument-mapping if you want to see the details.

At the same time, in the spec we documented, as an implementation note, that for the current numeric types, `const` means `const in`.

So, that gets to my current question.

Right now, we are are saying that whether or not the following program compiles is implementation-dependent, but that it will compile in the current implementation:

``` chapel
proc foo(arg: int(64)) { }

var myInt16: int(16);
foo(myInt16);
```

In particular, if some implementation had the default intent for `arg` mean the same as `const ref`, then this program would not compile.

Meanwhile, part of the motivation for the changes to the `const` intent in #21499 came from a desire  for better support for large integer sizes. In particular, we would like a very large integer to avoid copies when it is passed by default intent. For example:

``` chapel
proc bar(arg: int(4096)) { }

var myInt4k: int(4096);
bar(myInt4k); // desire for no copies, therefore implement with 'const ref'
```

But, by using 'const ref' to avoid copies, we also preclude the implementation from allowing implicit conversion. That means that the following program would not be legal:

``` chapel
proc bar(arg: int(4096)) { }

var myInt16: int(16);
bar(myInt16); // cannot implicitly convert for 'const ref'
```

Is this situation acceptable? If so, are we comfortable disallowing implicit conversions for calling functions for larger integers? If not, what should we do about it?

**Comment by bradcray** [comment]
Interestingly, I hit a case very similar to this this week in which I had:

```chapel
extern proc foo(const ref x: int(32));

foo(42);
```

which would not compile until I did:

```chapel
foo(42: int(32));
```

This didn't deeply distress me, but made me wonder whether permitting the coercion in this case would have any downsides.  I haven't been able to come up with any, but also haven't thought about it too hard.

**Comment by mppf** [comment]
AFAIK, the main downside is that `const ref` is less valuable in indicating that it refers to the actual. In particular, if we do an implicit numeric conversion, the `const ref` will refer to some compiler-introduced temporary. That said, I don't yet see a practical problem with allowing such implicit conversion, other than of course that it would be a language change.

Actually, I think it'd have more impact on the spec / the way that `const ref` is identified with subtyping.

One breadcrumb from the past is #14773, which says:

> When invoking proc p(const ref arg: t2) on x of the type t1:
> * if t1 <= t2 then the formal tracks concurrent changes to the actual, if any;
> * if t1 is coersible to t2, the formal is a reference to a temp that snapshots the value of the actual at the time of the call.
>    We can report a compile-time error in some cases to prevent user surprises / unintuitive behavior.

Another breadcrumb is that in issue #17195 we decided that it's OK to pass a `param` to a formal using `const ref` intent. This is arguably a case where `const ref` does not imply a reference to the actual (because we can't make a reference to literal `1`; we have to put it in a variable first). Note that 17195 was concerned only with the case of the type matching.

**Comment by bradcray** [comment]
> the const ref will refer to some compiler-introduced temporary

Yeah—that doesn't seem so different than permitting it to be passed a param to me, though, so doesn't give me any further pause than what we've done already.

**Comment by mppf** [comment]
I went ahead and created an experimental PR that changes it so that implicit conversions can work with `const ref`. I'm only seeing test failures from tests of `const ref` formals. 

PR #24083.

**Comment by dlongnecke-cray** [comment]
It seems acceptable to me to have allow implicit conversions for `const ref`, and to implement it by passing a reference to a temporary. I feel like we already do something similar today mechanically when we pass in literals by `const ref`.

**Comment by vasslitvinov** [comment]
This does not seem like a major issue to me, however the proposed change to allow implicit conversions looks like a nice improvement. Potential reservations:

* This is inconsistent with the behavior for classes, where the original formal is passed in, not a converted temporary. I am OK with this inconsistency though.
* It is instructive to see what C++ does about it. I do not think we need to consult other languages.

**Comment by mppf** [comment]
> This is inconsistent with the behavior for classes, where the original formal is passed in, not a converted temporary. I am OK with this inconsistency though.

In the long term I would agree with you for `owned` and `shared` (but passing a subclass to a `const ref` for these does not currently compile). Even today, I think the `borrowed` and `unmanaged` cases are probably better thought of as passing in a copy of the pointer (by default, anyway, since the default for these is `const in` for the pointer itself). In that case implicit conversion is unsurprising. So, my point is, if we restrict our thinking to what works today, there is no issue here.

> It is instructive to see what C++ does about it. I do not think we need to consult other languages.

It allows it. 

<details>

``` c++
#include <cinttypes>
#include <cstdio>

void fInt64Value(int64_t arg) { printf("in fInt64\n"); }

void fInt64ConstRef(const int64_t& arg) { printf("in fInt64ConstRef\n"); }

void fInt64RvRef(const int64_t&& arg) { printf("in fInt64RvRef\n"); }

int main() {
  int16_t i16 = 0;
  fInt64Value(i16); // calls fInt64Value with implicit conversion, no surprise

  fInt64ConstRef(i16); // calls fInt64ConstRef with implicit conversion

  fInt64RvRef(i16); // calls fInt64RvRef with implicit conversion
}
```

</details>

**Comment by mppf** [comment]
@bradcray and @DanilaFe and I talked through some of the implications here and have reached this direction:
1. allow implicit numeric conversions for blank or const intent (whether it turns into const ref or not). This is different from the earlier proposal because it allows `const ref` to still be a way out of the potential implementation-dependent copies that default intent / `const` intent give.
2. extend param value-based narrowing/downcasting to const ref cases. This follows naturally from the idea that we can pass a `param` to a `const ref` at all, since we can’t really refer to a `param` at all anyway and will help with a Fortran interop case.

### Rationale for (1)

We felt that it was important to address the current situation where it is implementation dependent whether or not this program from the O.P. compiles:

``` chapel
proc foo(arg: int(64)) { }

var myInt16: int(16);
foo(myInt16);
```

We feel that this program should compile and that fact shouldn't be implementation-dependent.


The choice on the 1st bullet here was driven by this code example:

``` chapel
var global: int(16) = 1;

f(global);

proc f(const ref g: int) {
  global = 5;
  writeln(g);
}
```

Here, it seems that `g` should refer to the same memory as `global` or be an error; but if the implicit numeric conversion is allowed for `f(global)` to convert from `int(16)` to `int(64)`, then it will not. We'd like for `const ref` to be a way out from implicit copies in any case where that is needed.

In contrast, if the example used `const` or default intent, the situation is different:

``` chapel
var global: int(16) = 1;

g(global);

proc g(x: int) {
  global = 5;
  writeln(x);
}
```

Here, it's already the case (with the `const [cvref]` idea) that the compiler can introduce a copy if it wishes in the process of passing to `x`, and in fact it is a program error if there is indirect modification as there is in this example. Point being, the fact that the implicit conversion introduces a new and different value to pass does not make the program behave any differently.

As far as the case of implicit conversion for `int(4096)` shown here:

``` chapel
proc bar(arg: int(4096)) { }

var myInt16: int(16);
bar(myInt16);
```

in the future if/when `int(4096)` is added, we will need to decide if implicit conversion from `int(16)` to `int(4096)` is allowed. If it is, then this program should compile. If not, it should not compile.


### Rationale for (2)

The code @bradcray brought up earlier

``` chapel
extern proc foo(const ref x: int(32));

foo(42);
```

came up in exploring some Fortran interoperability that a user is thinking about relying upon.

We're not aware of any particular reason why this example should not compile, since we can already pass a `param` to a `const ref`, and in doing so, the implementation has to make a temporary storing the `param` (because `param`s don't exist as regular variables at runtime). Since it already has to make such a temporary and there doesn't seem to be the potential for confusion in this case, we'd like to allow narrowing param conversions in this case.
