### ISSUE TITLE
libChplFrontendShared.so contains a reference to the build folder in its RPATH

### ISSUE THREAD

**Issue by twesterhout** [chapel-lang/chapel#24084]
I'm trying to get Chapel 1.33 to compile under Nix, and it seems that after running `make install`, `libChplFrontendShared.so`'s RPATH refers to `lib/compiler/linux64-x86_64` from the build directory. It makes sense, because that's the folder that contains `libChplFrontend.so`, but I think that it should instead refer to `libChplFrontend.so` via `'$ORIGIN'`.

Why is this a problem? Nix builds fail because `nix` detects that there are references to folders outside of the installation folder, i.e. that isolation is broken.

My current fix is to do something like this (`$out` is my installation prefix):

```bash
    ... after make install ...
    # libChplFrontendShared.so contains a reference to lib/compiler/linux64-x86_64 in its RPATH.
    # This folder contains libChplFrontend.so, but libChplFrontend.so has also
    # been installed to $out/lib/compiler/linux64-x86_64. Remove the temporary
    # build folder and instead add $ORIGIN to RPATH
    rm -r lib/compiler/linux64-x86_64
    patchelf --add-rpath '$ORIGIN' $out/lib/compiler/linux64-x86_64/libChplFrontendShared.so
```

For reference, here's the ouput of `ldd` before applying the hack:

```bash
chapel> ldd $out/lib/compiler/linux64-x86_64/libChplFrontendShared.so
chapel>         linux-vdso.so.1 (0x000015555551f000)
chapel>         libChplFrontend.so => /build/source/lib/compiler/linux64-x86_64/libChplFrontend.so (0x0000155554c00000)
chapel>         libclang-cpp.so.15 => /nix/store/3ybpyfjvknmh0pyqzi1asclz5vc2f20f-clang-15.0.7-lib/lib/libclang-cpp.so.15 (0x0000155551000000)
chapel>         libLLVM-15.so => /nix/store/nm7al9rc9a81q5y7p942xh96n2smbg1j-llvm-15.0.7-lib/lib/libLLVM-15.so (0x0000155549000000)
chapel>         libm.so.6 => /nix/store/ld03l52xq2ssn4x0g5asypsxqls40497-glibc-2.37-8/lib/libm.so.6 (0x0000155555439000)
chapel>         libpthread.so.0 => /nix/store/ld03l52xq2ssn4x0g5asypsxqls40497-glibc-2.37-8/lib/libpthread.so.0 (0x0000155555432000)
chapel>         libstdc++.so.6 => /nix/store/xq05361kqwzcdamcsxr4gzg8ksxrb8sg-gcc-12.3.0-lib/lib/libstdc++.so.6 (0x0000155548c00000)
chapel>         libgcc_s.so.1 => /nix/store/xq05361kqwzcdamcsxr4gzg8ksxrb8sg-gcc-12.3.0-lib/lib/libgcc_s.so.1 (0x0000155555411000)
chapel>         libc.so.6 => /nix/store/ld03l52xq2ssn4x0g5asypsxqls40497-glibc-2.37-8/lib/libc.so.6 (0x0000155548a1a000)
chapel>         /nix/store/ld03l52xq2ssn4x0g5asypsxqls40497-glibc-2.37-8/lib64/ld-linux-x86-64.so.2 (0x0000155555521000)
chapel>         libffi.so.8 => /nix/store/35badg7gpxkhyzcrdyh2dfi9wfd43phz-libffi-3.4.4/lib/libffi.so.8 (0x0000155555402000)
chapel>         librt.so.1 => /nix/store/ld03l52xq2ssn4x0g5asypsxqls40497-glibc-2.37-8/lib/librt.so.1 (0x00001555553fd000)
chapel>         libdl.so.2 => /nix/store/ld03l52xq2ssn4x0g5asypsxqls40497-glibc-2.37-8/lib/libdl.so.2 (0x00001555553f8000)
chapel>         libz.so.1 => /nix/store/ig0kkzw4n2pws12dj7szjm71f1a43if6-zlib-1.3/lib/libz.so.1 (0x00001555553da000)
chapel>         libncursesw.so.6 => /nix/store/d48d0ppksa6gwxjlkwf2i93rilyv9jvq-ncurses-6.4/lib/libncursesw.so.6 (0x0000155554b8c000)
chapel>         libxml2.so.2 => /nix/store/ks4msz5hmdvivf9fm84m1hzqw32swb89-libxml2-2.11.5/lib/libxml2.so.2 (0x0000155548e9f000)
```

Feel free to close this as "won't fix" if you think it's Nix-specific. I think that something similar will happen outside of Nix as well, if one tries `./configure && make && make install` instead of the standard `make`.

**Comment by bradcray** [comment]
@twesterhout : Thanks for making us aware of this.  I think you've had Chapel working in Nix in the past, so does this represent a change in behavior from previous releases?  And which was the last to work?  Or were your past uses of Chapel in Nix simply Chapel-generated executables rather than the Chapel compiler itself?

**Comment by twesterhout** [comment]
@bradcray I think this is something that's changed in 1.33 compared to 1.32. I see here https://github.com/chapel-lang/chapel/commit/1438e47064ecbff32d8ed47b8bed9fc94f40b69e that libChplFrontendShared.so didn't exist in 1.32, so...

**Comment by bradcray** [comment]
Ah, I wasn't distinguishing between LibFrontendShared.so and LibFrontend.so.  In that case, let's ask @DanilaFe to take a look at this, as the implementer of https://github.com/chapel-lang/chapel/pull/23843.

**Comment by DanilaFe** [comment]
Yep, that's on me. I'm taking a look now, but I'm not certain it's an easy fix: I would imagine that building with shared linking even without `LibFrontendShared.so` (only considering `LibFrontend.so`) would create a similar problem. I'm not sure if you can get that to happen in Nix though -- @twesterhout, is the nixpkgs version of LLVM that you use built for shared or static linking? i.e. what's the output of `llvm-config --shared-mode`?

**Comment by twesterhout** [comment]
Thanks for taking a look @DanilaFe. `llvm-config --shared-mode` returns "shared". I'm not a CMake expert, but could we draw some inspiration from https://github.com/chapel-lang/chapel/blob/8371b2af80f82b6e2d3dc734e9dc69be4712d561/CMakeLists.txt#L391C5-L394C63 ? Might this work for the FrontendShared target as well?

**Comment by DanilaFe** [comment]
That might work, but I'm not familiar enough with how we handle `RPATH` in general to be certain. I tried patching that line directly:

```path
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 4042f8e1ec..f4d342846b 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -388,7 +388,7 @@ else()
       set(CHPL_INSTALL_RPATH "@executable_path/../../lib/compiler/${CHPL_HOST_BIN_SUBDIR}")
     endif()
 
-    set_target_properties(chpl chpldoc
+    set_target_properties(chpl chpldoc ChplFrontendShared
                           PROPERTIES
                           BUILD_WITH_INSTALL_RPATH TRUE
                           INSTALL_RPATH ${CHPL_INSTALL_RPATH})
```

Which makes the `RPATH` entry be:

```
@executable_path/../../lib/compiler/darwin-arm64 (offset 12)
```

I believe `@executable_path` is the macOS equivalent of `$ORIGIN`. I will see if this breaks tests in other LLVM configurations.

**Comment by bradcray** [comment]
@DanilaFe : Prepping for next week's user issues roundup, I wanted to see whether you were able to complete your investigation here.  (I could also imagine filing the PR and letting nightly testing tell us if you've done the basics).

**Comment by DanilaFe** [comment]
I haven't found any issues locally and on one test machine. I will open a PR and let nightly testing check the more esoteric configurations.

**Comment by bradcray** [comment]
Thanks Daniel!  And thanks for informing of this Tom!  Please give a shout if you don't see it resolved after you've updated past this PR.
