### ISSUE TITLE
feature request: abs for param complex

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#24125]
### Summary of Problem
`abs` on a param complex number does not produce a param, but I would expect it to.

In order to implement this, we will a need param-time `sqrt` for `real` numbers. That should also be available to users.

### Steps to Reproduce

**Source Code:**

```chapel
param c:complex(128) = 1.0i;    
param x = abs(c); // error: Initializing parameter 'x' to value not known at compile time
```

**Associated Future Test(s):**

[`test/library/standard/AutoMath/absparamscomplex.chpl`](
           https://github.com/chapel-lang/chapel/blob/main/test/library/standard/AutoMath/absparamscomplex.chpl
          ) #24127

**Comment by damianmoz** [comment]
Not urgent.
