### ISSUE TITLE
c2chapel does not respect CHPL_DONT_BUILD_C2CHAPEL_VENV

### ISSUE THREAD

**Issue by twesterhout** [chapel-lang/chapel#24128]
### Summary of Problem

It seems that `make c2chapel` does not respect the `CHPL_DONT_BUILD_C2CHAPEL_VENV=1` setting.  I'm working around the issue by patching "tools/c2chapel/Makefile", but since `CHPL_DONT_BUILD_C2CHAPEL_VENV` exists, it'd be great if I didn't have to patch anything.

Current solution:

```
    substituteInPlace tools/c2chapel/Makefile \
      --replace 'c2chapel-venv $(FAKES)' '$(FAKES)'
```

### Steps to Reproduce

Run `make c2chapel` while offline -- `pip` will complain.

**Comment by bradcray** [comment]
@twesterhout : Thanks for reporting this!  Would you check whether the following patch resolves this issue for you:

```diff
diff --git a/third-party/Makefile b/third-party/Makefile
index d8168d1d44..d862fe38b4 100644
--- a/third-party/Makefile
+++ b/third-party/Makefile
@@ -88,7 +88,9 @@ chpldoc-venv: FORCE
        cd chpl-venv && $(MAKE) chpldoc-venv
 
 c2chapel-venv: FORCE
-       cd chpl-venv && $(MAKE) c2chapel-venv
+       @if [ -z "$$CHPL_DONT_BUILD_C2CHAPEL_VENV" ]; then \
+       cd chpl-venv && $(MAKE) c2chapel-venv; \
+       fi
 
 chapel-py-venv: FORCE
        cd chpl-venv && $(MAKE) chapel-py-venv
```

**Comment by twesterhout** [comment]
@bradcray yes, that seems to work!
