### ISSUE TITLE
Make `c_fn_ptr` comparable to `nil`

### ISSUE THREAD

**Issue by twesterhout** [chapel-lang/chapel#24164]
### Summary of Problem

Currently, we can check whether a `c_ptr` is NULL by saying `ptr == nil`: https://github.com/chapel-lang/chapel/blob/9c7ab5c44e514f2929a331c565497eca3c9a4d32/modules/standard/CTypes.chpl#L675

It'd be great to be able to do the same with a `c_fn_ptr` without a (semantically incorrect) casting to `c_ptr` first.

### Possible implementation

Add these to the CTypes module?

```chapel
  @chpldoc.nodoc
  inline operator ==(a: c_fn_ptr, b: _nilType) {
    return a:c_ptr(void) == b;
  }
  @chpldoc.nodoc
  inline operator ==(a: _nilType, b: c_fn_ptr) {
    return b == a;
  }
  @chpldoc.nodoc
  inline operator !=(a: c_fn_ptr, b: _nilType) {
    return !(a == b);
  }
  @chpldoc.nodoc
  inline operator !=(a: _nilType, b: c_fn_ptr) {
    return b != a;
  }
```

**Comment by bradcray** [comment]
@twesterhout : Thanks for filing this, which feels like a no-brainer to me (particularly if your proposed implementation works, which is what I was going to suggest when reading the title in my inbox).  I'm guessing this was just an oversight in the original implementation.  @mppf and @riftEmber: Do you see any reason we would not want these?

Just so we're all on the same page, note that `c_fn_ptr` is currently unstable and has some known deficiencies (https://github.com/chapel-lang/chapel/issues/9411, https://github.com/chapel-lang/chapel/issues/17994).  I currently view it as a stopgap that can work and help in some cases, but expect it to fall apart in more extensive ones.

**Comment by riftEmber** [comment]
These seem fine to add to me.

**Comment by mppf** [comment]
> These seem fine to add to me.

Ditto

**Comment by bradcray** [comment]
@twesterhout : Would you be interested in contributing this change back to the project as a PR?

If you were to do it, the steps would essentially be:
* add the lines to CTypes.chpl
* add a .chpl test and .good file of the new capabilities to the test system (probably within `test/extern/fnPtrs/`)
* make sure the test passes when running `start_test test/path/to/myTestName.chpl`
* make sure your commits sign off on the CLA

**Comment by lydia-duncan** [comment]
(while catching up on my emails, I noticed that Tom did open #24168, in case someone here would be a good reviewer)

**Comment by bradcray** [comment]
Oh, I hadn't seen that, thanks Lydia!
