### ISSUE TITLE
c2chapel silently skipping structs if a forward declaration is present

### ISSUE THREAD

**Issue by twesterhout** [chapel-lang/chapel#24167]
### Summary of Problem

Putting `struct bar;` into a C file confuses c2chapel, and it skips the subsequent definition.

Pinging @bradcray as he expressed interest in this issue :)

### Steps to Reproduce

test.h:
```c
#pragma once

struct bar;

typedef struct bar { int x; float y; } bar;

void foo(bar const*);
```

Now, let's generate test.chpl:
```console
$ c2chapel test.h > test.chpl
```

It looks like this:
```chapel
// Generated with c2chapel version 0.1.0

// Header given to c2chapel:
require "test.h";

// Note: Generated with fake std headers

use CTypes;

extern proc foo(const ref arg0 : bar) : void;

extern proc foo(arg0 : c_ptrConst(bar)) : void;
```

The declaration of `struct bar` is missing from test.chpl and invoking `chpl` on returns an error:

```console
$ chpl test.chpl
test.chpl:10: In function 'foo':
test.chpl:10: error: 'bar' undeclared (first use this function)
```

### Configuration Information

- Output of `chpl --version`:
```
chpl version 1.33.0
  built with LLVM version 15.0.7
```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`: 
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: none *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none *
CHPL_TIMERS: generic
CHPL_UNWIND: system *
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: system *
CHPL_HWLOC: bundled
CHPL_RE2: bundled *
CHPL_LLVM: system *
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
- (For Cray systems only) Output of `module list`:

**Comment by bradcray** [comment]
@bmcdonald3 / @riftEmber / @benharsh : Tagging you as those most familiar with `c2chapel`...  What level of effort would it take to determine whether this is an "us" problem or a "pycparser" problem?

**Comment by riftEmber** [comment]
> What level of effort would it take to determine whether this is an "us" problem or a "pycparser" problem?

Probably relatively mild. I imagine we could see if the visitor in `c2chapel` is hitting the AST node for either or both declarations; if it is but not generating code for them, it's probably an "us" problem, if it's not hitting them it's a "pycparser" problem or a problem with how we invoke it.

**Comment by dlongnecke-cray** [comment]
Two issues that we have to fix here. It's a problem on our end.
- When we encounter a forward declaration, we have to mark it so that we can resolve it to its declaration later.
- When we look for the followup declaration, we have to check both `typedef` and naked declarations.

**Comment by bradcray** [comment]
Thanks for fixing this, David, and thanks for reporting it, @twesterhout!  Please let us know if you run into any other issues with this.

**Comment by twesterhout** [comment]
This is great, thanks @dlongnecke-cray! I quickly tested `c2chapel` on the HalideRuntime.h header, and the issue seems fixed. I'll report back if my initial impression turns out to be incorrect.
