### ISSUE TITLE
`on` statements targeting variables doesn't work correctly with the GPU locale model

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#24259]
Consider the following code that does an `on` statement to `i` vs `i.locale` from a GPU sublocale:

```chpl
proc main() {
  var i = 10;
  writeln(i.locale);

  on here.gpus[0] {
    writeln("\ton here.gpus[0]:", here);
    on i {
      writeln("\t\ton i:", here);
    }
  }

  writeln();

  on here.gpus[0] {
    writeln("\ton here.gpus[0]:", here);
    on i.locale {
      writeln("\t\ton i.locale:", here);
    }
  }
}
```

This generates

```
LOCALE0
        on here.gpus[0]:LOCALE0-GPU0
                on i:LOCALE0-GPU0       # incorrect

        on here.gpus[0]:LOCALE0-GPU0
                on i.locale:LOCALE0     # correct
```

This is because the first case is done with a direct-on:

```chpl
  on here.gpus[0] {
    // this is what we do for `on i`:
    writeln("Direct `on i`? ",
            chpl_doDirectExecuteOn(__primitive("_wide_get_locale", i)));

    // this is what we do for `on i.locale`:
    writeln("Direct `on i.locale`? : ",
            chpl_doDirectExecuteOn(i.locale.chpl_localeid()));
  }
```

Generates:

```
Direct `on i`? true
Direct `on i.locale`? : false
```

And I think this boils down to the fact that for variables that are in the parent locale, we get the sublocale id `c_sublocid_any`. An `on` statement from an "any" sublocale to a non-negative one results in a direct on.

I never really understood the purpose of `c_sublocid_any`, maybe we need while creating tasks where we can't know the sublocale ID? In any case, the direct-on logic doesn't seem particularly worrisome to me. The solution is to use `c_sublocid_none` for most things instead of `c_sublocid_any`. Today, the situation is reverse: I see about 150 uses of `c_sublocid_any` vs 24 `c_sublocid_none`s.

**Comment by bradcray** [comment]
Woohoo!
