### ISSUE TITLE
Confusing behavior of c_array -> c_ptr casts

### ISSUE THREAD

**Issue by twesterhout** [chapel-lang/chapel#24318]
### Summary of Problem

Consider the following piece of code:
```chapel
proc bar(x : c_ptr(int)) {
  x[0] = 10;
}

proc main() {
  var raw : c_array(int, 5);
  writeln(raw);
  bar(raw);
  writeln(raw);
}
```
It's quite clear what should happen: the first element of `raw` becomes 10. This is what happens in practice as well.

Now, let's add one level of indirection:
```chapel
proc bar(x : c_ptr(int)) {
  x[0] = 10;
}

record Foo {
  var xs : c_array(int, 5);
}

proc main() {
  var foo = new Foo();
  writeln(foo.xs);
  bar(foo.xs);
  writeln(foo.xs);
}
```
and the code now prints
```
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
```
So the array `foo.xs` is unmodified.

I think this behavior is very confusing (or potentially even incorrect). I understand that `c_array` has value semantics, so if it's copied, the whole array is copied rather than just a pointer, but I'm wondering why `foo.xs` returns a copy rather than a reference. E.g., if I had declared a member variable `y : int`, then doing `foo.y` would return a reference to `y` rather than copying it, right, such that I could do `foo.y += 10`?
And the second aspect of it is that if `foo.xs` does return a copy, shouldn't it be forbidden to cast an rvalue to a `c_ptr`? I.e., wouldn't the pointer be immediately invalid because the rvalue had been deallocated?

Oh and finally, to make it even more confusing, let's do this:
```chapel
proc main() {
  var foo = new Foo();
  writeln(foo.xs);
  bar(foo.xs:c_ptr(int)); // explicit cast
  writeln(foo.xs);
}
```
the program now prints
```
[0, 0, 0, 0, 0]
[10, 0, 0, 0, 0]
```

I hope I've managed to convince you that something fishy is going on here :)

(I was bitten by this behavior yesterday, and it took me a while to realize that adding an explicit cast would magically fix my code) 

### Configuration Information

- Output of `chpl --version`: 1.34.0-pre
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: none *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: smp *
  CHPL_GASNET_SEGMENT: fast
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none *
CHPL_TIMERS: generic
CHPL_UNWIND: none *
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: system *
CHPL_HWLOC: bundled
CHPL_RE2: bundled *
CHPL_LLVM: none *
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: GCC 13.2.0

**Comment by bradcray** [comment]
@twesterhout : This is counterintuitive and surprising to me as well.  @mppf, it looks like you've at least glanced at this, and I know you have some familiarity with these types.  My best guess is that the field accessor for a `c_array` type should be returning a `ref` to the field but is returning a copy instead.  Does that seem likely?

Here's a version of the test that prints out the addresses of the pointer and initial array element, showing that they diverge:

```chapel
use CTypes;

proc bar(x : c_ptr(int)) {
  writeln(x);
  x[0] = 10;
}

record Foo {
  var xs : c_array(int, 5);
}

proc main() {
  var foo = new Foo();
  writeln(foo.xs);
  writeln(c_addrOf(foo.xs[0]));
  bar(foo.xs);
  writeln(foo.xs);
}
```

**Comment by twesterhout** [comment]
> My best guess is that the field accessor for a c_array type should be returning a ref to the field but is returning a copy instead. Does that seem likely?

@bradcray I had this theory as well, but then why would explicit casting to `c_ptr(int)` fix it...?

**Comment by mppf** [comment]
It looks to me like `addArgCoercion` from `wrappers.cpp` needs to have some special handling for this case because, unlike most types, we can implicitly convert from `c_array` to `c_ptr` by creating a pointer to the first `c_array` element. What it is doing now is copy-initializing but I don't think that's actually useful here.
