### ISSUE TITLE
Edge case where compiler inserts unneeded array copy with the `in` intent

### ISSUE THREAD

**Issue by jeremiah-corrado** [chapel-lang/chapel#24330]
Consider the following program with an array-wrapper type whose initializer takes an array argument by `in` intent. By inspection, it looks like the variable `a`, created in main, should be passed into the `ArrayWrapper` initializer without being copied because it isn't used again in that scope:

```chapel
proc main() {
    var a: [0..<10] int;
    var aw = new ArrayWrapper(a);
    writeln(aw.a);
}

record ArrayWrapper {
    type etype;
    param rank: int;
    var shape: rank*int;
    var a = makeDefaultArray(shape, etype);
}

proc ArrayWrapper.init(in a: [?d] ?t) {
    this.etype = t;
    this.rank = d.rank;
    this.shape = d.shape;
    this.a = a;

    writeln(d); // <- commenting this line out removes the extra copy
}

proc makeDefaultArray(shape: ?N*int, type t) {
    var rngs: N*range;
    for param i in 0..<N do rngs[i] = 0..<shape[i];
    var a: [{(...rngs)}] t;
    return a;
}
```

However, in the generated `c` code, `a` is copied:
```c
a_chpl2 = chpl__initCopy2(&_formal_tmp_a_chpl, UINT8(false));
(this_chpl8)->a = a_chpl2;
```

The copy can be removed by removing the reference to `d` after all fields are initialized. In other words, without the `writeln(d)`, the `in` intent behaves as expected:
```
a_chpl2 = _formal_tmp_a_chpl;
(this_chpl8)->a = a_chpl2;
```

More generally, it appears that any use of the array or its domain after the type instance is fully initialized will cause the compiler to make a copy of `a` during initialization. This makes sense given that, in general, there could be operations that require another copy of `a` after initialization is complete, like passing `a` into a separate function that also takes it by `in` intent.

However, for this case, namely referencing the array's domain after initialization, the extra copy isn't needed. Adjusting the `in` intent logic to remove the copy would be an improvement, and would help users avoid a potential performance pitfall.

**Comment by mppf** [comment]
In terms of what ought to happen, IMO the original case should not get the extra copy:

``` chapel
proc ArrayWrapper.init(in a: [?d] ?t) {
    this.etype = t;
    this.rank = d.rank;
    this.shape = d.shape;
    this.a = a;

    writeln(d); // it's not referring to 'a' so 'a' should be copy elided
}
```

In contrast, this pattern should disable copy elision:


``` chapel
proc ArrayWrapper.init(in a: [?d] ?t) {
    this.etype = t;
    this.rank = d.rank;
    this.shape = d.shape;
    this.a = a;

    writeln(a.domain); // it's mentioning 'a' so should disable copy elision for 'a'
}
```

I suspect that the current situation here is largely due to how the production compiler represents `d` in this function.

**Comment by benharsh** [comment]
This appears to be related to an intersection between the "normalization" of ``d`` and our split-init implementation.

The ``writeln(d)`` call is transformed during normalization into a call to ``a._dom``, which from the compiler's perspective is indistinguishable from a user-specified reference to ``a``.

The ``elideCopies`` mini-pass in ``splitInit.cpp`` is the part that's actually responsible for getting rid of the extra init-copy for the array ``a``. When it sees the reference to ``a`` after the init-copy, it gives up and decides not to remove the copy. For some more context, the line for ``this.a = a`` looks more like:

```
var a_temp = formal_a;
move(a, a_temp);
```

@mppf , do you have any insight as to how we might make this work within the rules of split init?

**Comment by mppf** [comment]
@benharsh - one way would be for the normalization to introduce `const ref tmp = a._dom` near the beginning of the function, since it's using it to replace something from a formal.

Another strategy would be to wait for the dyno implementation of split init / copy elision, which will happen pre-normalization.

**Comment by benharsh** [comment]
I believe I have a solution here: https://github.com/chapel-lang/chapel/pull/24416
