### ISSUE TITLE
Invalid warning about missing `contextManager` 

### ISSUE THREAD

**Issue by jeremiah-corrado** [chapel-lang/chapel#24408]
In the following program, the class `thing` implements the `contextManager` interface and is annotated as such. However, the compiler still generates a warning indicating that the annotation should be added to the class declaration.

```chpl
class thing: contextManager {
  type T;
  var n: T;

  proc enterContext(): T {
    return this.n;
  }

  proc exitContext(in err: owned Error?) {
    if err then halt(err!.message());
  }
}

var x = new thing(int, 5);

manage x as n {
  writeln(n);
}
```

The warning is:
```
warning: owned thing(int(64)) is being used in a 'manage' statement via its 'enterContext' and 'exitContext' methods. However, owned thing(int(64)) does not implement contextManager. In the future, this will result in an error.
```

This only appears to be a problem for generic classes. Removing the `type T`, and making `n` an integer for example prevents the warning from being emitted.

**Comment by bradcray** [comment]
Tagging @DanilaFe on this in case he hasn't seen it.
