### ISSUE TITLE
Dial down "implicit module for file-scope code" warnings for main modules

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#24437]
At present, a Chapel file like this:

```chapel
proc main() {
  use M;

  foo();
}

module M {
  proc foo() {
    writeln("In M.foo()");
  }
}
```

when compiled as follows generates our warning:

```bash
$ chpl testit.chpl
testit.chpl:1: warning: an implicit module named 'testit' is being introduced to contain file-scope code
```

This feels like a reasonable, and reasonably common, pattern to me—to have a single file that serves as the main module (either by defining `main()` or by being the only module defined on the `chpl` command-line) contain both top-level code and a module definition.  It also seems evident that a user would not be facing the kind of confusion that this warning was designed to circumvent.  As a result, in this issue, I'm proposing we squash the warning in such cases.

**Comment by bradcray** [comment]
I'd hoped this would be trivial to implement—not even worth filing an issue over—but unfortunately, we generate the warning before we reach the point that `ModuleSymbol::mainModule()` can be called (the one way I know of to determine what the main module is).  If any Dyno experts have suggestions or want to pick this up, that'd be great.

**Comment by DanilaFe** [comment]
I can take a look in the coming sprint.

**Comment by bradcray** [comment]
Thanks for jumping on this, Daniel!
