### ISSUE TITLE
problem with --llvm-print-ir on newer LLVMs

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#24448]
### Summary of Problem

I'm seeing a lot of superflous symbols in `--llvm-print-ir` with LLVM 17

I see the output I would expect with LLVM 15 and LLVM 16 but there are pages and pages of output with LLVM 17. Plus, it segfaults with LLVM 17.

### Steps to Reproduce

**Source Code:**

```chapel
proc foo() { }
foo();
```

**Compile command:**
`chpl aa.chpl --llvm-print-ir foo`

**Comment by jabraham17** [comment]
Looks like this was a simple one line omission when upgrading llvm versions. Should be fixed by https://github.com/chapel-lang/chapel/pull/24460
