### ISSUE TITLE
sincos

### ISSUE THREAD

**Issue by damianmoz** [chapel-lang/chapel#24489]
Would it be possible to get access to `sincos`. It is available in _clang_. I assume its interface would be something like
```chapel
proc sincos(x : real(?w)) : (real(w), real(w))
{
   return (sinx, cosx);
}
```
The C compilation does demand _GNU_SOURCE be defined although the routines were written at SUN Microsystems and are technically not GNU. It is neither a C standard function nor an IEEE 754 mandated routine.

I can provide the interface. I am trying to figure out al the rules for
```chapel
_chpl_??????
```
style routines that go in AutoMath.chpl or runtime/include/chpltypes.h. Are they documented somewhere? I cannot find an example which returns its result by address from a C routine. Thanks

Or, I can do my own thing. Thanks again.

**Comment by lydia-duncan** [comment]
We're not as strict about `chpl_` routines, but I'd probably just mimic the set up of something similar (though it sounds like there's not a 1:1 that already exists).  I doubt there's a specific document with rules for it.  In general, I'd say our policy for the Math routines is: if it's possible to write an extern call for it that works generally, wrap that - if not, that's when it's necessary to add something to the runtime.  In other words, lean more on the side of Chapel code as much as possible.

I'd probably put sincos in Math.chpl near the `sin` or `cos` routines.  The interface seems about what I would expect, the main question is how portable supporting it would be, as you're alluding to.

**Comment by damianmoz** [comment]
Thanks.  I cannot find a `chpl_WHATEVER` routine which returns the result by address.  Am I not looking hard enough?

Both `sin(x)` and `cos(x)` each do argument reduction (which is over half of the work) and then an evaluation of a Remez polynomial.  By doing a single argument reduction and then evaluating the two separate Remez polynomials, `sincos` saves heaps of work - 30% -50%. I can write `sincos` so that it is totally portable using
```chapel
config param sincosAvailable = false;
```
and the person building the library can then choose to pull in something from `libm` if it is available at compile time by adding an argument to the compiler.

I think the time will come when there will be Chapel implementations of all the elementary functions, if only because people will eventually realise that a language like Chapel is a superior (a.k.a. clear, concise and readable) language in which to elucidate the underlying algorithm. But we will all have a few more wrinkles before that day arrives. It most certainly will not be in the near term.

**Comment by lydia-duncan** [comment]
There is `chpl_task_getInfoChapel()`, though it's in the internal modules so could be relying on some additional compiler magic to do what it's accomplishing.  Plus it's returning a `c_ptr` and we'd probably want to have the return value for `sincos` be a normal Chapel type, so there may be some conversion needed and I'm not sure if that would end up impacting the performance.

**Comment by damianmoz** [comment]
Thanks. Seems messy. I will just put together a readable but sub-optimal routine in pure Chapel. It will suffice for now.
