### ISSUE TITLE
Behavior of Binary Serializer when writing non-local array arguments

### ISSUE THREAD

**Issue by jeremiah-corrado** [chapel-lang/chapel#24480]
The IO module's binary serializer exposes a [`writeBulkElements` ](https://chapel-lang.org/docs/modules/standard/IO.html#IO.ArraySerializer.writeBulkElements) procedure that writes a given number of bytes from a `c_ptr`.

The default rectangular array implementation [uses](https://github.com/chapel-lang/chapel/blob/a667b2567b6ad2c1c85b1d8a96dcf0b7db828b9f/modules/internal/DefaultRectangular.chpl#L1843-L1846) `writeBulkElements` to serialize arrays when available; however, the array's locale is not checked before creating a c_ptr to it's first element. So, attempting to serialize a non-local array with the binary serializer currently results in an invalid memory access.

**Example:**

Running the following program on two locales with checks enabled,

```chapel
use IO;

var f = openTempFile();

on Locales[1] {
  var fw = f.writer(locking=false, serializer = new binarySerializer());
  var a: [1..1000] int;

  fw.write(a);
}
```

produces the following error:
```
bug.chpl:9: error: references to remote data cannot be passed to external routines like 'c_pointer_return'
```

Where the call to `c_pointer_return` originates in DefaultRectangular's call to `writeBulkElements` (src linked above). Without checks enabled, running the above program will either result in a segfault or print garbage values to the file.

Note that this issue applies to serializing arrays with any serializer that uses `writeBulkElements`, but AFAIK, the binary serializer is currently the main use case.

**Potential solutions:**

1. Make a local copy of the array under the hood (i.e., in DefaultRectangular, add a check for the array's location before creating a c_ptr; if non-local create a copy of the array first). This approach has the obvious drawback of incurring a potentially very large communication cost without alerting the user
2. Throw an error in DefaultRectangular if the array is non-local before attempting to create a c_ptr.

The first approach is similar to [how strings/bytes are treated](https://github.com/chapel-lang/chapel/blob/a667b2567b6ad2c1c85b1d8a96dcf0b7db828b9f/modules/standard/IO.chpl#L8568) in direct calls to `fileWriter.writeBinary`, whereas the second approach is more similar to [how arrays are treated](https://github.com/chapel-lang/chapel/blob/a667b2567b6ad2c1c85b1d8a96dcf0b7db828b9f/modules/standard/IO.chpl#L8664-L8666) in `writeBinary`.

**Comment by benharsh** [comment]
For anyone following along, it looks like this has been an issue since the 1.26 at the least, and probably for a lot longer.

**Comment by benharsh** [comment]
Resolved by https://github.com/chapel-lang/chapel/pull/24589

**Comment by bradcray** [comment]
Thanks for jumping on this one quickly, @benharsh !

**Comment by bradcray** [comment]
@jeremiah-corrado : I'm trying to remember... did this come out of the recent PSath thread on gitter, or something you were doing yourself?  (just realizing that it doesn't have a "user issues" tag on it if so).

**Comment by jeremiah-corrado** [comment]
It was spawned off of this discussion with PSath, sorry I forgot to add the label.

**Comment by bradcray** [comment]
Tagging @psath  in case this improvement is of interest to him.
