### ISSUE TITLE
internal compiler error: PAS-CON-AST-4802 chpl version 1.33.0

### ISSUE THREAD

**Issue by lucaferranti** [chapel-lang/chapel#24493]
I started upgrading ForwardModeAD to chapel 1.33, but I am getting an itnernal compiler error in the tests

> internal error: PAS-CON-AST-4802 chpl version 1.33.0

Internal errors indicate a bug in the Chapel compiler,
and we're sorry for the hassle.  We would appreciate your reporting this bug --
please see https://chapel-lang.org/bugs.html for instructions.

unfortunately no further info is given. I suspect this has again something to do with my fancy use of lambda functions. 

## Steps to reproduce

- You can see the logs [here](https://github.com/lucaferranti/ForwardModeAD/actions/runs/8077291249/job/22067294077#step:4:136)

- To reproduce locally, clone [ForwardModeAD](https://github.com/lucaferranti/ForwardModeAD) and run `mason test --show test_differentiation.chpl`

**Comment by lucaferranti** [comment]
fwiw, changing `lambda` -> `proc` did not fix the issue.

**Comment by bradcray** [comment]
@dlongnecke-cray : Given the mention of lambda/proc, would you have time to give this a quick look and see what you can determine?

**Comment by dlongnecke-cray** [comment]
Taking a look, thanks Luca!

**Comment by dlongnecke-cray** [comment]
Bug is in `convert-uast.cpp` something to do with a bad fixup for the type `dual`. 

So your guess is probably right, Luca. We're translating the formal type `dual` of that anonymous procedure incorrectly when we lower to our old AST (my current hunch).

**Comment by dlongnecke-cray** [comment]
I think that #24498 should fix this, though note that I only edited the code of your `test_differentiation.chpl` until I got all those tests to compile. I'll leave the followup to you 😄.

**Comment by bradcray** [comment]
Hi @lucaferranti — Thanks for reporting this, and if you're able to test the fix (either by pulling `main` or this PR, or after the March release goes out), please let us know if you see remaining issues.

@dlongnecke-cray : Thanks for the quick response here!

**Comment by lucaferranti** [comment]
@bradcray @dlongnecke-cray thanks for the quick help! I'll check if it works with main (so that I can catch other potential issues before the release ;) ).

**Comment by lucaferranti** [comment]
Yes! Mutatis mutandis all tests pass on main! :tada:

**Comment by bradcray** [comment]
Great, thanks for checking, @lucaferranti!
