### ISSUE TITLE
`mason search` broken

### ISSUE THREAD

**Issue by lucaferranti** [chapel-lang/chapel#24495]
both in 1.33 and on main

```
❯ mason search
Updating mason-registry
MasonUtils.chpl:255: error: zippered iterations have non-equal lengths
```

**Comment by lucaferranti** [comment]
implementing my suggestion does indeed confirm what I was thinking

```
❯ bin/linux64-x86_64/mason search
Updating mason-registry
MasonUtils.chpl:256: error: assert failed - Invalid version Mason
```

but I am still unsure where the `Mason` comes from. Is there a way to get mason to print the whole call stacktrace when it hits an error

**Comment by bradcray** [comment]
@lucaferranti : Answering your last question, would `CHPL_UNWIND` help here?  https://chapel-lang.org/docs/usingchapel/chplenv.html#chpl-unwind

**Comment by lucaferranti** [comment]
figured out the issue!

The incriminating package in the mason registry is [Codecs](https://github.com/chapel-lang/mason-registry/tree/master/Bricks/Codecs) because for that one the file is called `Mason.toml` instead of `x.y.z.toml`. This causes issues beause `findLatest` in `MasonUtils.chpl` currently does

```chapel
    const end = manifest.size - suffix.size;
    const ver = new VersionInfo(manifest[0..<end]);
    if ver > ret then ret = ver;
```

so as you can see it assumes that the toml file is named after the version, which breaks for `Codecs`.

A quick fix is to patch the toml file name for codecs. However in general I think `mason-registry` have a bash (or chapel :) ) script checkign that the toml file is named properly (from what I can say, this is not the case atm) as well as other sanity checks.

**Comment by arezaii** [comment]
I have merged https://github.com/chapel-lang/mason-registry/pull/70, which should resolve the broken search feature. @lucaferranti, if you'd like to file a PR to update the `init` proc you identified here I would be happy to merge it on your behalf.

**Comment by lucaferranti** [comment]
Yes, the init change I suggested above would make the error message more informative  but not fix the issue if an incorrectly named file occurs. I think this can be closed for now, I can open a PR with the slight improvement in the init handling later this week
