### ISSUE TITLE
Should we make mixed comparisons between bool / int an error?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#24505]
### Summary of Problem

Recently, in #24155, we made comparison operators non-associative to avoid confusion about what `a < b < c` means as well as other coding errors.  The result of writing such patterns today is a syntax error.

Rust has similarly made `a < b < c` an error to avoid confusion, but generates better error messages ([TIO](https://tio.run/##KyotLvn/Py1PITcxM09BQ1OhmouLMye1RCFRwVbB1BrCTgKyzaDsZCDb3BqoKDNNQSNRwUYhSRNIJAP1cXIWFGXmleTkKWooeaTm5OQrhOcX5aQoKmkCtdZCdIA1EKm@9v9/AA), [ATO](https://ato.pxeger.com/run?1=m72kqLS4ZMGCpaUlaboWN1PT8hRyEzPzFDQ0Faq5uDhzUksUEhVsFUytIewkINsMyk4Gss2tgYoy0xQ0EhVsgJI2CskgfZycBUWZeSU5eYoaSh6pOTn5CuH5RTkpikqaQK21XLUQy6B2wuwGAA), in part by outlawing comparisons that mix between bool and integer types (though they also have an error message specifically about chained operators requiring parens).

This issue asks whether we could improve upon today's syntax error by outlawing mixed int/bool comparisons (while still supporting int/int and bool/bool comparisons).  This seems like it would have also helped with other erroneous cases that #24155 revealed, like `a == b | c == d`.

**Comment by mppf** [comment]
I think that part of the reason this is tricky is that `bool` implicitly converts to `int`, so outlawing mixed int/bool comparisons isn't as simple as a module change.

That said, we can investigate adjusting the compiler to warn or error about such cases. Should it apply to all functions that mix int/bool actuals? only functions named `==` etc? only certain functions in ChapelBase?

**Comment by mppf** [comment]
Ah, yes, I think that could work. Sometime in the past, adding such an overload caused differences in behavior for things that you wouldn't think would call it. Hopefully those days are behind us now, though.

**Comment by mppf** [comment]
Instead of making a breaking language change here, we'll just focus on improving the error message from the compiler when you do something like `if a < b < c`.

**Comment by bradcray** [comment]
Closing this based on that discussion.  For those coming here from discussions about `a < b < c` or the like, we'll be looking into specializing the front-end to generate a better error message for such cases.
