### ISSUE TITLE
CUDA 12: Misaligned address issues with types which aren't 64 bits

### ISSUE THREAD

**Issue by ShreyasKhandekar** [chapel-lang/chapel#24602]
### Summary of Problem

When using CUDA 12 in the following pattern we get the error:
```
internal error: gpu-nvidia.c:292: Error calling CUDA function: misaligned address (Code: 716)
```

Workaround:
Change `proc foo(..)` to be `inline proc foo(...)`

### Steps to Reproduce

**Source Code:**

```chapel
on here.gpus[0] {
  var a: [1..10] uint(32);
  @assertOnGpu
  foreach chunk in 0..1 {
    foo(a);
  }
}

 proc foo(ref arr : [] uint(32)) {
  var sum : uint(32);
  var temp : uint(32) = arr[1];
  arr[1] = sum;
  sum += temp;
}
```

Output from compiling and running:
```
me@pinoa:~/chapel> chpl test/gpu/native/studies/sort/repro.chpl && ./repro
warning: The prototype GPU support implies --no-checks. This may impact debuggability. To suppress this warning, compile with --no-checks explicitly
internal error: gpu-nvidia.c:292: Error calling CUDA function: misaligned address (Code: 716)
```

**Associated Future Test(s):**
`test/gpu/native/studies/sort/cuda12_misaligned.chpl`

### Configuration Information
<details> <summary> Show </summary>
- Output of `chpl --version`:

```
warning: The prototype GPU support implies --no-checks. This may impact debuggability. To suppress this warning, compile with --no-checks explicitly
chpl version 2.0.0 pre-release (719155d0d3)
  built with LLVM version 17.0.6
  available LLVM targets: amdgcn, r600, nvptx64, nvptx, aarch64_32, aarch64_be, aarch64, arm64_32, arm64, x86-64, x86
Copyright 2020-2024 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)
```

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:

```
CHPL_TARGET_PLATFORM: hpe-cray-ex
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: x86-rome
CHPL_LOCALE_MODEL: gpu *
  CHPL_GPU: nvidia *
CHPL_COMM: none *
CHPL_TASKS: qthreads
CHPL_LAUNCHER: slurm-srun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: bundled *
CHPL_AUX_FILESYS: none
```

- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:

```
gcc (SUSE Linux) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

- (For Cray systems only) Output of `module list`:

```
Currently Loaded Modules:
  1) craype-x86-rome                         8) cray-dsmml/0.3.0
  2) libfabric/1.15.2.0                      9) cray-mpich/8.1.29
  3) craype-network-ofi                     10) cray-libsci/24.03.0
  4) perftools-base/24.03.0                 11) PrgEnv-gnu/8.5.0
  5) xpmem/2.6.2-2.5_2.27__gd067c3f.shasta  12) cray-pmi/6.1.14
  6) gcc-native/13.2                        13) cudatoolkit/23.3_12.0
  7) craype/2.7.31                          14) cray-python/3.11.7
```

</details>

**Comment by ShreyasKhandekar** [comment]
This first arised in `gpuScan`. See the patch in https://github.com/chapel-lang/chapel/pull/24600

This is also related to https://github.com/Cray/chapel-private/issues/5919 which has the same error being produced, although the cause could be different.

We should close https://github.com/Cray/chapel-private/issues/6052 since it ended up not being a sporadic after all.

**Comment by vasslitvinov** [comment]
I have a patch that simply changes the offending LLVM instructions:
```llvm
%6 = alloca %chpl____wide__ddata_uint32_t, align 4
store %chpl____wide__ddata_uint32_t zeroinitializer, ptr %6, align 8
```
so that the store's align is 4 instead of 8. This passes the standard and gasnet paratests. CUDA testing t.b.d.
```diff
--- a/compiler/codegen/cg-symbol.cpp
+++ b/compiler/codegen/cg-symbol.cpp
@@ -1031,8 +1031,8 @@
          ctype->symbol->hasFlag(FLAG_WIDE_REF) ||
          ctype->symbol->hasFlag(FLAG_WIDE_CLASS)) {
         if(isFnSymbol(defPoint->parentSymbol)) {
-          info->irBuilder->CreateStore(
-              llvm::Constant::getNullValue(varType), varAlloca);
+          info->irBuilder->CreateAlignedStore(
+              llvm::Constant::getNullValue(varType), varAlloca, alignment);
         }
       }
     }
```

How should we think about the alignment in the general case?  Especially looking at `helpGetAlignment()` in clangUtil.cpp.
* If the type is extern, we consult `clangInfo->Ctx->getTypeAlignIfKnown(qType)`. Hopefully this works.
* If the type is purely Chapel, we do not impose any alignment, i.e., alignment=1 for C codegen and `llvm::MaybeAlign()` for LLVM.
* The trouble comes when we have a Chapel record wtih extern type(s) in it. Then, `helpGetAlignment()` returns the biggest of the alignments of the extern types and we pass it to LLVM.

This latter caused the misaligned address issue in the OP, which the above patch will hopefully fix. However, how well does this work in general? Maybe it works well enough? If we do not pass this alignment to LLVM, we get a failure in `test/llvm/alignment/check-align16.chpl` where it crashes when executing `movaps 0xc8(%rsp), %xmm0`.

Aside: do we really need that store of getNullValue()? Don't we have this initialization in our AST already?

**Comment by mppf** [comment]
The change to use `CreateAlignedStore` there sounds good to me. I suppose that in this case, the extern type that has an alignment from C is `chpl_localeID_t` ?

> If the type is purely Chapel, we do not impose any alignment, i.e., alignment=1 for C codegen and llvm::MaybeAlign() for LLVM.

We might be better off changing this in the future (e.g. making `uint(32)` loads be 4-byte aligned) but I am uncertain of the tradeoffs. I would expect that a C compiler would give alignment hints for such cases.

**Comment by vasslitvinov** [comment]
I am shooting to resolve this issue by the upcoming feature freeze. My branch is almost ready for review.
