### ISSUE TITLE
Resolve dyno documentation warnings so we can resume validating links again

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#24630]
#24201 updated the version of `breathe` we rely on to build the online documentation, because otherwise we wouldn't be able to use `chpldoc` at all (due to relying on old Python dependencies).  However, the dyno compiler docs currently generate a lot of warnings with this version of `breathe`:

<details>

/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/base.rst:20: WARNING: cpp:identifier reference target not found: TraceElement
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/libraries.rst:11: WARNING: undefined label: '_library_file_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/libraries.rst:11: WARNING: undefined label: '_library_file_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/libraries.rst:11: WARNING: undefined label: '_library_file_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/libraries.rst:11: WARNING: undefined label: '_library_file_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/libraries.rst:11: WARNING: undefined label: '_library_file_writer_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/libraries.rst:11: WARNING: undefined label: '_library_file_writer_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/parsing.rst:11: WARNING: undefined label: '_file_contents_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/parsing.rst:11: WARNING: undefined label: '_parser_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: 'resolution-types_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: 'resolution-types_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: 'scope-types_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: 'scope-types_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: 'resolution-types_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: 'resolution-types_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: 'resolution-types_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: 'scope-types_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: 'resolution-types_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: 'resolution-types_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: 'scope-types_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: 'scope-types_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: 'scope-types_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: 'resolution-types_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: 'resolution-types_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: '_resolved_visitor_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: 'resolution-types_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: 'scope-types_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: 'resolution-types_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: 'scope-types_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: 'resolution-types_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: 'resolution-types_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: 'resolution-types_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: 'resolution-types_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: 'scope-types_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: '_resolved_visitor_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: 'scope-types_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: cpp:identifier reference target not found: VisibilitySymbols::REGULAR_SCOPE
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: cpp:identifier reference target not found: VIS_USE
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: 'scope-types_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: 'resolution-types_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: 'resolution-types_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/resolution.rst:11: WARNING: undefined label: 'scope-types_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/types.rst:11: WARNING: undefined label: '_any_class_type_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/types.rst:11: WARNING: undefined label: '_any_type_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/types.rst:11: WARNING: undefined label: '_array_type_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/types.rst:11: WARNING: undefined label: '_basic_class_type_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/types.rst:11: WARNING: undefined label: '_bool_type_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/types.rst:11: WARNING: undefined label: '_builtin_type_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/types.rst:11: WARNING: undefined label: '_class_type_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/types.rst:11: WARNING: undefined label: '_class_type_decorator_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/types.rst:11: WARNING: undefined label: '_complex_type_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/types.rst:11: WARNING: undefined label: '_composite_type_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/types.rst:11: WARNING: undefined label: '_c_string_type_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/types.rst:11: WARNING: undefined label: '_domain_type_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/types.rst:11: WARNING: undefined label: '_erroneous_type_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/types.rst:11: WARNING: undefined label: '_imag_type_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/types.rst:11: WARNING: undefined label: '_int_type_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/types.rst:11: WARNING: undefined label: '_manageable_type_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/types.rst:11: WARNING: undefined label: '_nil_type_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/types.rst:11: WARNING: undefined label: '_nothing_type_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/types.rst:11: WARNING: undefined label: '_param_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/types.rst:11: WARNING: undefined label: '_primitive_type_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/types.rst:11: WARNING: undefined label: '_qualified_type_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/types.rst:11: WARNING: undefined label: '_real_type_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/types.rst:11: WARNING: undefined label: '_record_type_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/types.rst:11: WARNING: undefined label: '_tuple_type_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/types.rst:11: WARNING: undefined label: '_type_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/types.rst:11: WARNING: undefined label: '_uint_type_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/types.rst:11: WARNING: undefined label: '_union_type_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/types.rst:11: WARNING: undefined label: '_unknown_type_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/types.rst:11: WARNING: undefined label: '_void_type_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_aggregate_decl_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_anon_formal_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_array_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_as_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_ast_list_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_comment_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_ast_node_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_attribute_group_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_begin_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_block_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_bool_literal_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_bracket_loop_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: 'uast_2_break_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_builder_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_builder_result_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_bytes_literal_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_call_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_catch_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_class_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_cobegin_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_coforall_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_comment_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_conditional_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_continue_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_c_string_literal_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_decl_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_defer_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_delete_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_domain_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_dot_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_do_while_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_empty_stmt_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_enum_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_enum_element_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_erroneous_expression_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_extern_block_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_fn_call_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_for_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_forall_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_foreach_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_formal_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_forwarding_decl_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_function_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_function_signature_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_identifier_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_imag_literal_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_implements_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_import_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_include_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_indexable_loop_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_init_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_interface_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_int_literal_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_label_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_let_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_literal_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_local_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_loop_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_manage_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_module_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_multi_decl_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_named_decl_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_new_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_numeric_literal_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_on_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_op_call_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_prim_call_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_range_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_real_literal_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_record_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_reduce_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_reduce_intent_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_require_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_return_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_scan_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_select_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_serial_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_simple_block_like_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_string_like_literal_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_string_literal_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_sync_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_task_var_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_throw_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_try_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_tuple_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_tuple_decl_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_type_decl_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_type_query_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_uint_literal_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_union_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_use_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_var_arg_formal_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_variable_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_var_like_decl_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_visibility_clause_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_when_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_while_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_with_clause_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_yield_8h'
/Users/lydia/Documents/Repositories/chapel/doc/rst/developer/compiler-internals/uast.rst:11: WARNING: undefined label: '_zip_8h'

</details>

So that PR also turned off warnings for bad links.  Our intention was for this to be a short term fix, as we want our links to work and to find out quickly if they don't.  Unfortunately, we forgot and it led to accidentally introducing some broken links (which #24629 will fix).

We would like to resolve these dyno warnings in some way so that we can restore link checking and avoid accidentally introducing more bad links that users may stumble across

**Comment by mppf** [comment]
I didn't see these on my system when exploring updating all of these dependencies to the latest versions in PR #24612. Is it possible that updating doxygen will resolve the issue?

**Comment by mppf** [comment]
PR #24612 includes fixes for these.

**Comment by jabraham17** [comment]
Closing, I believe this issue was resolved by https://github.com/chapel-lang/chapel/pull/24612 and just not closed
