### ISSUE TITLE
homebrew install of chapel doesn't install chpldoc

### ISSUE THREAD

**Issue by arezaii** [chapel-lang/chapel#24639]
### Summary of Problem
when doing a `brew install chapel`, `chpl` and `mason` get built and installed but `chpldoc` is built and not installed. 

### Steps to Reproduce

```bash
brew install chapel
```

**Execution command:**
```
which chpldoc
```

### Configuration Information

macOS
Chapel version 1.33

**Comment by bradcray** [comment]
Based on https://github.com/chapel-lang/chapel/issues/9153, it sounds as though this is a change in behavior?

**Comment by mppf** [comment]
It was this way with the most recent release — Chapel 1.33 — and testing earlier versions is a bit tricky.

**Comment by bradcray** [comment]
@arezaii : I think from slack contexts, you were capturing this after hitting it for future reference.  Having just emerged from homebrew-world for the release, is it clear to you what would need to be done to enable chpldoc to be included?

**Comment by arezaii** [comment]
it's not clear at the moment, `chpldoc` is being built currently, but it doesn't end up installed. I thought this might be caused by the `make clean-all` happening before the install, but changing that order of operations did not fix the problem and local testing doesn't indicate `chpldoc` should be deleted by the `clean-all`. I thought maybe we were dropping the `chpldoc` in an unexpected location for the install, but I see it alongside `chpl` and `mason`, which both end up installed. 
The next step is to better understand the homebrew commands in this part of the formula:
```ruby
    bin.install libexec.glob("bin/#{platform}/*")
    bin.env_script_all_files libexec/"bin"/platform, CHPL_HOME: libexec
```
to understand why `mason` and `chpl` are picked up but not `chpldoc`

**Comment by arezaii** [comment]
this should be resolved with https://github.com/Homebrew/homebrew-core/pull/168831

**Comment by bradcray** [comment]
Great, thanks!
