### ISSUE TITLE
Homebrew on Mac M1/M2 systems computes misleading `here.maxTaskPar` values

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#24655]
While testing `writeln(here.maxTaskPar);` on my M1 Mac using homebrew, I was surprised to see it report `10` as the result rather than `8`.  I do see `8` when using a compiler built from source.

My understanding is that this is because:

* the Mac has 8 performance cores and 2 efficiency cores
* homebrew is currently built without `hwloc` support, so we don't distinguish between them as we do when `hwloc` is enabled

And for additional context:
* `hwloc` defaults to `none` when using `CHPL_TASKS=fifo`
* the explanation for why we use `fifo` by default is given here:  https://github.com/chapel-lang/chapel/pull/23415
* Elliot tried to enable system versions of `hwloc` in the homebrew environment in https://github.com/chapel-lang/chapel/pull/23409

**Comment by jhh67** [comment]
This is a nit, but I don't think `here.maxTaskPar` is misleading as `fifo` will use all 10 cores.

Is there a reason why we shouldn't use the bundled `hwloc` and `jemalloc` in `hombrew`?

**Comment by bradcray** [comment]
> This is a nit, but I don't think here.maxTaskPar is misleading as fifo will use all 10 cores.

That's a great point of clarification.  Still, I'm concerned about our using all 10 cores (in the sense that it seems certain to result in a load imbalance).  I.e., I think the hwloc-oriented behavior is preferable if we could duplicate that in a homebrew install.

> Is there a reason why we shouldn't use the bundled hwloc and jemalloc in hombrew?

That was my instinct as well.  Elliot's main reaction (where I should've captured both here) was that we don't have any testing of fifo+bundled hwloc, so he was nervous about the notion of shipping such a configuration as the 2.0 release this week (say).  I filed this issue independently of the 2.0 release, though, and we could look into that going forward (or look more into enabling qthreads).

The one other reason to consider not doing this is that the homebrew maintainers like us to use external packages rather than bundled ones (not surprising since they're in the package management and interdependence business).

I think it was both of these things that motivated Elliot to make the attempt in the third/final bullet of the OP.

**Comment by damianmoz** [comment]
Most programs that I use and algorithms that are written by people I know assume that all cores are the same speed. I share Brad's caution at having a load imbalance.

**Comment by jabraham17** [comment]
Merging https://github.com/chapel-lang/chapel/pull/25145 should resolve this issue, which allows homebrew to build with hwloc. This means a homebrew install will report only the performance cores for `writeln(here.maxTaskPar);` (on my Mac, 8).

The above PR modifies our in tree version of the chapel formula and should propagate to the official homebrew formula during our normal release procedures for 2.1
