### ISSUE TITLE
Improve "Missing or wrong version for clang" error message

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#24669]
[forking this off from #24644]

When our scripts are determining which version of `clang` to use, when comparing the version number to `llvm-config`'s version, we generate the error message "Missing or wront version for clang" if there is a mismatch or we can't find `llvm-config`.

When a user hits this error in the field, it can be hard for them to know the cause, or for us to help them debug the issue, due to the lack of information, such as:
* was the problem that `llvm-config` couldn't be found or that the version numbers didn't match?
* if the version numbers didn't match, what versions were found?
* what paths were used for the `llvm-config` and `clang` version queries?

Moreover, when this error is printed, it also prevents `printchplenv` from being run (because it generates the same error message) which makes it challenging to determine some of this information (notably, the location of `llvm-config`) using the typical mechanisms.

When working through an issue of this on Ookami last week, I was ready to send a patch to the existing Python files to determine what was going wrong, which felt like an unhealthy step to take.

**Comment by jabraham17** [comment]
I think there is two separate things than can be improved here, and I have opened PRs for both.

https://github.com/chapel-lang/chapel/pull/24687 improves the error messages when the clang and llvm-config version numbers don't match. This change also prints what clang/llvm-config was used, as well as the versions (where applicable)

https://github.com/chapel-lang/chapel/pull/24688 adds a new flag for `printchplenv`, `--continue`, which lets users opt in to continuing to run `printchplenv` after an error. This is useful when trying to diagnose errors, users can see what the values of the chpl config variables are as well as the error message

**Comment by lydia-duncan** [comment]
@jabraham17 - I think the PRs you mentioned above resolved this issue.  Is that correct, or should it stay open?

**Comment by jabraham17** [comment]
Yes, I think we can close this now
