### ISSUE TITLE
[Feature Request]: Simpler way to access `Sphinx` and `sphinxcontrib-chapeldomain` versions

### ISSUE THREAD

**Issue by Guillaume-Helbecque** [chapel-lang/chapel#24676]
### Summary of Feature

**Description:**
Working on #22935, we note with @lydia-duncan that there is no trivial way for users and developers to get the `Sphinx` and `sphinxcontrib-chapeldomain` versions built with `chpldoc`. Such information could be of interest when reporting issues with `chpldoc` itself for example.

**Is this a blocking issue with no known work-arounds?**
No; low priority feature. Current work-around consists in calling `grep -E "^Sphinx" $CHPL_HOME/third-party/chpl-venv/chpldoc-requirements2.txt` for example.

### Code Sample

These information could come with `chpldoc --version` for example, as the LLVM version with `chpl --version`:

```chapel
>>> chpldoc --version
chpldoc version 2.1.0 pre-release (9234bd977f)
   Sphinx version X.X.X
   sphinxcontrib-chapeldomain version Y.Y.Y
Copyright 2020-2024 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)
```

**Comment by lydia-duncan** [comment]
Thanks for opening the issue, Guillaume :)

I suspect this would increase in priority if we move to separate `chpldoc`'s release cycle more from the Chapel compiler's
