### ISSUE TITLE
[Feature Request]: Make reader()/writer() methods default to `locking=false`

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#24732]
This is a request that, once we've lived with the requirement that `reader()` and `writer()` methods require a `locking` argument to be passed in for long enough (presumably a release or two), we make them default to `locking=false` to capture what we increasingly think of as being the appropriate default (as reflected by other interfaces such as the random number generators, associative domains, and openReader()/Writer() routines).

**Comment by bradcray** [comment]
@jeremiah-corrado : I can't remember whether this was a proposal that you (or others?) were opposed to or uncertain about, but reading @stonea 's 1BRC blog made me think of it again because he starts with a serial version that explicitly throws `locking=false` which (putting myself in the position of a new-to-Chapel-from-Python programmer) feels a bit like "What is this and why do I need to do it?"

If it was uncontroversial, this feels like an easy one for someone to knock out during issues week.  :)

**Comment by jeremiah-corrado** [comment]
I've also found myself getting annoyed with needing to type `locking=false` every time I create a reader/writer. As far as I remember, changing the default to false wasn't controversial among the people participating in the initial discussion (you, me, @mppf, and @lydia-duncan).

I'd be happy to make the change this week unless there are any objections from those tagged here.

**Comment by bradcray** [comment]
Thanks for the quick turnaround!  @stonea, if you could help me remember, it'd be cool to update your blog article's code to simplify this after 2.2 is released.
