### ISSUE TITLE
Should omitting the `new` in a `dmapped` expression be legal

### ISSUE THREAD

**Issue by jeremiah-corrado** [chapel-lang/chapel#24756]
Currently, the syntax around `dmapped` supports two ways of creating a distributed domain from an anonymous Distribution:

```chapel
var D = {1..n} dmapped new blockDist({1..n});
var D = {1..n} dmapped blockDist({1..n});
```

The first option accepts a distribution instance on the right of the `dmapped`. This is more consistent with something like:
```chapel
var myBlockDist = new blockDist({1..n});
var D = {1..n} dmapped myBlockDist;
```

The second option is essentially syntactic sugar for the first, where the `new` is implied. 

The fact that the language allows omitting the `new` could potentially be confusing for a few reasons:
* this is the only place, other than in a `new` expression itself, where an initialization expression (like: `blockDist({1..n})`) is accepted as such
* in all other contexts `blockDist({1..n})` would be treated as a call to a type constructor
  * even more confusing here because: `type t = domain(1) dmapped blockDist(...)` is the syntax for creating a distributed domain type.

**Comment by bradcray** [comment]
Jeremiah already knows this, but I believe strongly that the `new`-less version should be deprecated and removed for the reasons given in the OP (and I believe he feels similarly though he did an admirable job of phrasing this issue very neutrally :) ).

**Comment by jeremiah-corrado** [comment]
In an offline design discussion, we decided to make omitting the `new` keyword illegal in these expressions.
