### ISSUE TITLE
[Bug]: Need better error message for `const` passed to `c_ptr`

### ISSUE THREAD

**Issue by Guillaume-Helbecque** [chapel-lang/chapel#24797]
### Summary of Problem

Hello, while updating some 1.33.0 code to 2.0.0, I faced something curious. Here is the reproducer:

```chapel
use CTypes;

record R {
  var arr: c_array(c_int, 10);
}

proc foo(const a: c_ptr(c_int)) {
  writeln("say hello");
}

proc main() {
  const r = new R();

  foo(r.arr);
}
```

This piece of code compiles and runs for 1.33.0, but fails to compile using 2.0.0 with the following error (which, by the way, seems incomplete):

```
sandbox.chpl:11: In function 'main':
sandbox.chpl:14: error: const actual is passed to a 'ref' formal of :
```

Using `foo(const a: c_array(c_int))` instead of `foo(const a: c_ptr(c_int))` makes things work (for both versions), but this looks strange to me because `c_array` can coerce with `c_ptr`. In addition, the reason why I use `c_ptr(c_int)` instead of `c_array(c_int)` is that my real code is a bit more complicated: the `foo` procedure is declared in an external C library, and when I import it using `extern proc foo(const a: c_array(c_int));`, I get the following error (which I don't get using `c_ptr(c_int)`):

```
sandbox.chpl:4: error: a concrete intent is required for the extern function formal 'a' which has record type 'c_array(int(32),10)'
```

**Is this a blocking issue with no known work-arounds?**
No, some work-arounds exist.

### Steps to Reproduce

**Compile command:**
`chpl foo.chpl`

**Execution command:**
N/A (compile-time error)

**Associated Future Test(s):**
N/A
### Configuration Information

- Output of `chpl --version`: 2.0.0 
- Output of `$CHPL_HOME/util/printchplenv --anonymize`: 
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: 
- (For Cray systems only) Output of `module list`:

**Comment by Guillaume-Helbecque** [comment]
This issue has already been discussed in the Chapel's gitter, and here are the first thoughts:

From @bradcray: 

> That error message is certainly problematic.
> 
> I believe that the complaint here is that the compiler is trying to insert a `c_ptrTo()`-style call in order to do the conversion from `c_array` to `c_ptr`, but running into troubles because `r` is `const` which means that its `arr` field is `const`, which is problematic because we can't take a non-`const` pointer to a `const` thing. Replacing the `foo(r.arr);` with `foo(c_ptrTo(r.arr));` gives a similar, but more detailed error.
> 
> I think the fix here is to declare `r` to be `var` rather than `const`. This will make `r.arr` also be variable, and permit the `c_ptrTo()` (whether explicit or implicit) work correctly.
> 
> (Note that, in Chapel, a `const` record is one in which its fields cannot be re-assigned, so it's effectively as though they were all declared `const`).
> 
> I wasn't aware of a specific change from 1.33 to 2.0 that would have caused this change in behavior, but it seems to me that the current choice to issue an error is more correct, though the error message definitely needs to be fixed. My guess is that when we did another change (likely the elimination of copies when converting `c_array`s to `c_ptr`s?), we inadvertently changed the behavior here as well.

From @ShreyasKhandekar: 

> Changing the type signature of `foo` to `proc foo(const a: c_ptrConst(c_int))` makes this compile. This way it works in both cases where `r` is a `var` or `const`. It might, however, restrict what you can do inside `foo` because the type of the argument has changed (but maybe this is what you intended to express?)

**Comment by mppf** [comment]
IMO the right solution here is to use `proc foo(const a: c_ptrConst(c_int))`. I think that the earlier releases of Chapel compiled it without error due to some missing const checking.

However, the error message issue still stands, so I will change this issue to be tagged with "Error Message".

**Comment by vasslitvinov** [comment]
@Guillaume-Helbecque for your real code with `extern proc foo(const a: c_array(c_int));` -- I think the error message "a concrete intent is required" is reasonable. It asks you to indicate explicitly whether you want the actual argument passed by reference or by value. "By value" means it will be copied into the formal argument.

So, what do you think about changing the `const` to `const ref` in your `extern` declaration? Or to `const in` if that is your intention?

**Comment by vasslitvinov** [comment]
So what should be the error message in this case?

Option 1: the candidate `proc foo(a: c_ptr(c_int))` does not match because a CONST `c_array` is passed to `c_ptr` argument. The implication is that this allows user to have a second overload accepting a `c_ptrConst(c_int)` that will NOT be ambiguous for a const actual argument.

Option 2: the candidate `proc foo(a: c_ptr(c_int))` matches, however it is an error to pass a const `c_array` to this formal. This error is akin to passing a `const` actual to a `ref` formal, for example, here:
```chpl
proc foo(ref x: int) { }
const y = 5;
foo(y);     // error: const actual is passed to 'ref' formal
```

**Comment by riftEmber** [comment]
> So what should be the error message in this case?

I'm weakly in favor of option 2. I think option 1 is more technically correct because the formal and actual types don't match and can't be coerced to match. However, given that the coercion is behind-the-scenes magic to the user, the mismatch as far as they're concerned is a lot closer to a "const actual to ref formal" mistake.

**Comment by mppf** [comment]
IMO Option 1 would be heading towards #22809. The main issue with that is figuring out how to handle it along with language stability. As a result, I think the near-term solution should be Option 2; and that if/when we do #22809, we move it to Option 1.

**Comment by vasslitvinov** [comment]
While #25343 resolves this issue technically speaking, the design question "Option 1 or Option 2 in https://github.com/chapel-lang/chapel/issues/24797#issuecomment-2181140104" remains open. We will continue discussing it on #22809 .

Beware that #22809 talks about `ref` vs. `const ref` formals whereas this issue #24797 is concerned with passed-by-value `c_ptr` vs. `c_ptrConst` formals.
