### ISSUE TITLE
dyno: can't write (secondary) generic initializers for non-special types

### ISSUE THREAD

**Issue by DanilaFe** [chapel-lang/chapel#24811]
Consider the following code:

```Chapel
record myRange {
  type idxType = int;
  type anotherType = bool;
}

proc myRange.init(type idxType, type anotherType) {
  this.idxType = idxType;
  this.anotherType = anotherType;
}

proc myRange.init(type idxType) {
  this.idxType = idxType;
}

var rng1 = new myRange(bool, int);
var rng2 = new myRange(bool);
```

Here, `myRange` (so named because I discovered the bug while working on ranges) is a generic-with-defaults type. What do you expect the types of `rng1` and `rgn2` to be?

Well, they're both `myRange(int, bool)`! 

The reason for this is that when writing secondary methods like this, we typecheck the receiver. In doing so, observing that it's generic-with-defaults, we fully instantiate it. Thus, the functions we're actually writing are:

```Chapel
proc (myRange(int, bool)).init(type idxType, type anotherType) {...}
```

The `InitResolver` notes that the field types are already initialized, and doesn't override them. Notably, this works in production -- methods written on `myRange` are considered to be over the generic / root `myRange`

Two things, then:
* Somehow, we need to make sure that methods written this way are not considered to be methods on the concrete type, but on its generic version.
* We should probably issue errors when trying to set fields of a concrete type, so if the user writes:
  ```Chapel
  proc (myRange(int, bool)).init(type idxType, type anotherType) {
    this.idxType = string;
  }
  ```
  The program is rejected.

**Comment by bradcray** [comment]
> We should probably issue errors when trying to set fields of a concrete type, so if the user writes:
> ```chapel
> proc (myRange(int, bool)).init(type idxType, type anotherType) {
>   this.idxType = string;
> }
> ```

I'd propose going a step further and saying that it's not legal to write initializers that are specific to a given instantiation.  I.e., since initializers are written in the form `new myRange(args, to, initializer)`, I don't think there's any way for a user to say "please invoke the `myRange(int, bool)` initializer, is there?  (he asked, hopefully)

Or wait, maybe one can get there through type aliases?  E.g.,

```chapel
record R {
  type t = int;
  var x: t;
}

proc R.init(type t, x: t) {
  this.t = t;
  this.x = x;
}

proc (R(string)).init(x: string) {
  this.x = x;
}

var myR = new R(real, 1.2);
writeln(myR, ": ", myR.type:string);

type Rstring = R(string);
var myR2 = new Rstring("hi");
writeln(myR2, ": ", myR2.type:string);
```

(though this doesn't work today, causing the compiler to segfault).

**Comment by DanilaFe** [comment]
Yes, I followed the same train of thought. IMO, it should be acceptable to write initializers for concrete instantiations, with the understanding that invoking them would require a type alias. I believe on top of my most recent PR, this works (or works modulo some troubles with nested calls to `init`) in Dyno. I also see no (moral) reason to disallow this if we can support it.

**Comment by bradcray** [comment]
> I also see no (moral) reason to disallow this if we can support it.

Seems worth opening and sponsoring a design issue on, at any rate.

**Comment by mppf** [comment]
IMO the reason not to support it is that we already have a strategy for communicating type information from a type alias to an initializer: passing named arguments with the type/param information. So I view this proposal to allow things like `proc (R(string)).init(x: string)` as unnecessarily introducing another way to do something (where IMO the current way is `proc init(type eltType, value: eltType) where eltType == string`).

I don't view this as a super strong argument but I wanted to mention that I lean towards not doing this proposal.

Of course, we have to fix the generic-ness of `myRange` in `proc myRange.init` in dyno.

**Comment by DanilaFe** [comment]
I guess I'd argue by symmetry. If I do:

```Chapel
record notGeneric { var r: int; }
type notGenericAlias = notGeneric;
proc notGenericAlias.init() { ...}
```

That works, but if `notGenericAlias` comes from an instantiated generic type:

```Chapel
record generic { var r; }
type notGenericAlias = generic(int);
proc notGenericAlias.init() { ...}
```

I'd expected it to work as well. But the latter boils down to `proc (generic(int)).init`. 

I know Chapel type aliases aren't opaque, but the less that you have to worry about how a Chapel type alias is defined, the better IMO. I can lift this into a design discussion, though.
