### ISSUE TITLE
[Feature Request]: improve UnusedLoopIndex chplcheck warning

### ISSUE THREAD

**Issue by jabraham17** [chapel-lang/chapel#24838]
The UnusedLoopIndex warning should consider an empty tuple as being unused as well

For example
```chapel
for (_, _) in zip(1..10, 1..10) {}
```

This should be a lint warning for UnusedLoopIndex and the rule should provide a fixit for this to remove `(_, _) in`.

Furthermore, if a fixit will cause this case to occur, the fixit should just remove the index

```chapel
for (i, _) in zip(1..10, 1..10) {}
```

The fixit for the above example should entirely remove `(i, _) in`, instead of just changing it to `(_, _)`

**Comment by DanilaFe** [comment]
It introduces another click, but this could be an instance of a "useless pattern matching rule" -- if a tuple pattern is just the identifier "_" over and over, it can be replaced with `_`.

**Comment by DanilaFe** [comment]
Using the `variables` function already defined in `rules.py`:

```Python
        def variables(node):
            if isinstance(node, Variable):
                if node.name() != "_":
                    yield node
            elif isinstance(node, TupleDecl):
                for child in node:
                    yield from variables(child)
```

One could write:

```Python
@basic_rule(TupleDecl)
def UnusedDestructuring(arg: TupleDecl) -> bool:
    vars = set(variables(arg))
    if len(vars) == 1 and "_" in vars:
        return False
    return True
```
