### ISSUE TITLE
Update homebrew formula to use CHPL_HWLOC!=none, CHPL_TASKS=qthreads and CHPL_MEM=jemalloc

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#24931]
Our homebrew formula, at least on Mac, currently is using CHPL_HWLOC=none, CHPL_TASKS=qthreads, and CHPL_MEM=jemalloc.  One downside of this is that it isn't using our preferred configuration, which can result in negative performance results.  Another is that it [results in using both the efficiency and performance cores for computations](https://github.com/chapel-lang/chapel/issues/24655), which seems likely to cause a load imbalance and isn't how we prefer to use such systems.

This issue proposes that we put in the effort to enable these settings to give Mac users now only a simple way to get started with Chapel, but one that matches the way it'd work when building from source, and that we'd want it to work.

Related issues/PRs:
* https://github.com/chapel-lang/chapel/pull/23409
* https://github.com/chapel-lang/chapel/pull/23366
* https://github.com/chapel-lang/chapel/issues/24655

**Comment by jabraham17** [comment]
Noting here that https://github.com/chapel-lang/chapel/pull/25148 will switch the homebrew formula copy we have in tree to use `CHPL_HWLOC=system`, which allows us to use `CHPL_TASKS=qthreads` (the default). This should propagate to the official homebrew formula with the 2.1 release as a part of our normal release procedures.

This does not fully resolve this issue as we still need to handle `CHPL_MEM=jemalloc`.

**Comment by bradcray** [comment]
@jabraham17 : 2.1 is coming up plenty soon, but if we wanted to get this into users' hands even earlier, would it just be a matter of publishing the updated homebrew formula and getting it through CI and the review, or does it depend on changes to `main` or other things that I'm not anticipating?

**Comment by jabraham17** [comment]
This depends on a number of fixes to our config scripts for the build system (https://github.com/chapel-lang/chapel/pull/25145), so it has to wait for 2.1

**Comment by jabraham17** [comment]
I have updated https://github.com/chapel-lang/chapel/pull/25148 to include using `CHPL_MEM=jemalloc`, and so merging it should actually resolve this issue
