### ISSUE TITLE
nicer error message for out-of-place `_`

### ISSUE THREAD

**Issue by DanilaFe** [chapel-lang/chapel#25001]
Today, writing `for _ in 1..10` will lead to a generic "syntax error". This is not an ideal error message, but seems like it ought to be easy enough to _make_ it a nice error message. For instance, it would be nice to note that `_` can only be used in declaration context like `var _ = ...` and loop tuple-expressions.

**Comment by bradcray** [comment]
> it would be nice to note that _ can only be used in declaration context like var _ = ...

Note that it's currently a syntax error in this context as well, e.g.

```chapel
var _ = 42;
```

gives:

```console:
testit.chpl:1: syntax error: near '_'
```

I believe that today it's only permitted in de-tupling declaration contexts like:

```chapel
var (first, _) = myTupleExpr;
```
