### ISSUE TITLE
[Bug]: BUI-0906 internal build error on single variable discard in for-loop

### ISSUE THREAD

**Issue by etscheelk** [chapel-lang/chapel#25000]
### Summary of Problem

**Description:**

Attempted to discard single loop variable like `(_)` results in build error BUI-0906. Expected it to behave like how you can discard a variable in a tuple iterators, e.g. `(x, _) in ...`
```
repeat.chpl:15: internal error: BUI-0906 chpl version 2.0.0
Note: This source location is a guess.

Internal errors indicate a bug in the Chapel compiler,
and we're sorry for the hassle.  We would appreciate your reporting this bug --
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.
```

**Is this a blocking issue with no known work-arounds?**

Yes (besides not trying to discard variable)

### Steps to Reproduce

**Source Code:**

```chapel
for (_) in 1..4 {}
```

**Compile command:**

`chpl rp.chpl`

**Execution command:**

N/A

**Associated Future Test(s):**

No.

### Configuration Information

- Output of `chpl --version`:
```
chpl version 2.0.0
  built with LLVM version 12.0.0
  available LLVM targets: xcore, x86-64, x86, wasm64, wasm32, systemz, sparcel, sparcv9, sparc, riscv64, riscv32, ppc64le, ppc64, ppc32le, ppc32, nvptx64, nvptx, msp430, mips64el, mips64, mipsel, mips, lanai, hexagon, bpfeb, bpfel, bpf, avr, thumbeb, thumb, armeb, arm, amdgcn, r600, aarch64_32, aarch64_be, aarch64, arm64_32, arm64
Copyright 2020-2024 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)
```

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: system
CHPL_AUX_FILESYS: none
```

- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
```
clang version 10.0.0-4ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by bradcray** [comment]
@etscheelk : Thanks very much for filing this, as it definitely should not be giving you an internal error as it is!

The way we currently write this pattern in Chapel is to drop any mention of an index variable at all, using `for 1..4 {}`.

There was recently a brief discussion about whether Chapel should permit `for _ in 1..4 {}` in https://github.com/chapel-lang/chapel/issues/24149.  If you'd be a proponent of supporting that, that'd be interesting to know, and potentially worth opening a feature request issue for (depending on how strongly you feel about it).

**Comment by DanilaFe** [comment]
I will take a look at why this is an internal error.

**Comment by DanilaFe** [comment]
I've opened https://github.com/chapel-lang/chapel/pull/25003 to fix this issue. Like Brad said, `for _` is not valid in Chapel (https://github.com/chapel-lang/chapel/issues/24149 notwithstanding), so a syntax error is emitted.

**Comment by etscheelk** [comment]
> If you'd be a proponent of supporting that, that'd be interesting to know

I think this would provide some parity between the methods of ignoring the iterating variable. 
While `for 1..10` is nifty, if I know about the tuple component dropping, that's where my mind goes first. I believe rust allows dropping variables like this too. 

At any rate, glad to get it converted to a syntax issue for the immediate future.
