### ISSUE TITLE
Proposal: Disallow spaces after @ for attributes

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#25020]
It's currently legal to write an attribute with a space between the `@` and the attribute. I would like to propose removing this capability. If we remove this capability, we will be able to use `@` as an operator (potentially for matrix multiplication).

For example, this currently parses:

``` chapel
@ chpldoc.nodoc proc foo() { }
```

Note that, we already require no space for a type query formal as in `proc f(arg: ?t)` -- it cannot be `proc f(arg: ? t)`. 

As far as I know, it just happened to be implemented this way, and there is no particular reason that we need to allow the space. Furthermore, I don't know of any Chapel code that uses a space after the `@` for an attribute. It does not occur in the `test/` directory, for example. As a result, 1) I think we could consider this change a bug fix (assuming it was not intended) and 2) it's very unlikely to cause problems for existing Chapel code.

**Comment by lydia-duncan** [comment]
I'm more than okay with removing the ability to put a space between `@` and the attribute.

**Comment by bradcray** [comment]
I'm also a big supporter of this proposal; I hadn't realized that we permitted the space today, and would prefer disallowing it.

I don't know how attributes are documented, but we should weigh whether we're breaking backwards compatibility in considering this change.

**Comment by mppf** [comment]
@arezaii indicated to me that he thinks that such whitespace was mistakenly allowed in in the initial implementation.

**Comment by mppf** [comment]
> I don't know how attributes are documented, but we should weigh whether we're breaking backwards compatibility in considering this change.

They are documented in [a technote](https://chapel-lang.org/docs/main/technotes/attributes.html#attributes-in-chapel). It says

> Generally, an attribute in Chapel is specified above a symbol declaration with an @ followed by an identifier that specifies the attribute name. 

IMO it's reasonable to interpret this as not allowing a space, because an identifier can't contain spaces. On the other hand, if you have a flex+bison mindset, you might interpret these statements as talking about tokens, which is how it is implemented now and allows whitespace.

However, none of the examples in this file show a `@` followed by whitespace.

I think we should just clarify the sentence above to indicate a space is not allowed between `@` and the identifier.

**Comment by mppf** [comment]
I've created PR #25022 to make this change.

**Comment by bradcray** [comment]
I agree that it'd be reasonable to interpret that wording as being that our intention was to not permit a space and that we can categorize this as a bug fix—thanks!
