### ISSUE TITLE
[Feature Request]: GMP Module gmp_printf does not accept vars

### ISSUE THREAD

**Issue by s-timcheck** [chapel-lang/chapel#25089]
### Summary of Feature

**Description:**
The `gmp_printf` function in the GMP module does not accept vars and returns an error requiring an intent for the argument(s).  This is specifically tested with type `mpf_t`, but is probably an issue with `mpz_t` as well.  An example is below:
```
var x:mpf_t;
mpf_init(x);
mpf_set_d(x, 1.234567);
gmp_printf("%.4Ff\n", x);  //Print a formatted string with 4 decimal places
```

Which should output:

`1.2346`

But instead throws an error during compilation:

`GMP.chpl:1123: error: a concrete intent is required for the extern function formal '_e0_arg' which has record type '1*__mpf_struct'`

**Is this a blocking issue with no known work-arounds?**
Yes, you can work around this by re-defining `gmp_printf` to use `const ref` args like so:

`extern proc gmp_printf(fmt: c_ptrConst(c_char), const ref arg...);`

I do not know if the above work-around should replace the current implementation in the GMP module?

**Comment by lydia-duncan** [comment]
It looks as though testing of `gmp_printf` is limited to `test/library/standard/GMP/studies/gmp-simple-long-inout.chpl`.  The code there seems to use `c_ptrTo` to access the first element of an array of `mpz_t`s

**Comment by lydia-duncan** [comment]
I'm not sure whether we should document that the function expects `c_ptr`s or whether we should update the function to use the `ref` intent instead.  I lean slightly towards the latter, but it merits further discussion imo.

**Comment by bradcray** [comment]
I'll try to take a look at this along with #25082.

**Comment by bradcray** [comment]
It's looking to me as though adding the `in` intent to `arg` is working, and that seems like an appropriate choice to me (in the sense that C will take each of these arguments by shallow copy-in).  I should do some additional testing and valgrind testing before drawing any firm conclusions there, though.

**Comment by bradcray** [comment]
I believe #25127 should resolve this, but am curious for Michael's feedback as it looks like he considered, but shied away from, this change in an early PR.
