### ISSUE TITLE
[Bug]: CLS does not treat negative numbers and complex numbers as literals

### ISSUE THREAD

**Issue by jabraham17** [chapel-lang/chapel#25115]
The following code, when using the resolver, should show a call inlays for `a`.

```chapel
proc foo(a) {}
foo(-10); // missing `a = `
foo(3i+10); // missing `a = `
```

The reason is that from the point of view of the language server, `3i+10` is a param expression which does not get a call inlay, only literals do. However, dyno (and the chapel language) does consider this a single identifier.

Note this also affects negative numbers like `-10`, because `-10` is a param unary expression, not a single identifer.

At a minimum, there should be call inlays for these cases. But more generally, the language server should treat these as literals.

**Comment by jabraham17** [comment]
> Jade, what do you mean when you say that Chapel considers this a single identifier? I don't think of Chapel as supporting a complex literal, which is how I interpret it, but maybe you mean something different?

In the sense that in Dyno, there are multiple representations of a Param. There are int params, string params, etc. There is also a Complex param, which I interpret as a "literal". From the point of view of the parser/ast, `10i+1` is an add expression, but I interpret semantically this is a single complex literal.

From a language design perspective I think this is certainly up for interpretation. That said, for this particular issue I think the language server should treat it as a "literal".

As an aside, while doing some poking at the compiler to answer this question, I found further issues with complex numbers and literals:

![Screenshot 2024-05-24 at 12 31 43 PM](https://github.com/chapel-lang/chapel/assets/15747900/dd48f9ac-7b2f-4619-aa7e-420f1746e52e)

Code:
```chapel
param a = 10i+1;
param b = 10i+1.0;
param c = 10i;
param d = c + 1;
param e = c + 1.0;
```

All of these params should have both type inlays and param value inlays.

**Comment by damianmoz** [comment]
I have not tested the combinations thoroughly but
```chapel
param a = 10:imag(32) + 1;
param b = 10i + 1:real(32);
param f = 10 + 1:real(32);

assert(a.type != b.type);
```
I would have thought that the type of _b_ was **complex**(64). It is not. It is **complex**(128). Note that the type of _f_ is **real**(32) which is expected.

Interesting.

**Comment by mppf** [comment]
@damianmoz - that is odd and arguably goes against some of our design goals. I suspect that it has to do with the fact that `10i` is viewed as equivalent to `10.0i`, where `10.0` has type `real(64)`. I think it deserves its own issue. Would you be able to create one? Thanks.

**Comment by jabraham17** [comment]
Noting that this issue also affects negative numbers like `-10`, and I have updated the title and OP accordingly.
