### ISSUE TITLE
Dyno asserts when casting a param string to bytes

### ISSUE THREAD

**Issue by jabraham17** [chapel-lang/chapel#25154]
The following code asserts when run in `testInteractive`

```
var a = "":bytes;
```

This is currently causing the language server to crash with `--resolver` enabled. This asserts when resolving `modules/internal/String.chpl`.

**Comment by bradcray** [comment]
Is it when casting any string, or specifically the empty string, or perhaps specifically a param string?

**Comment by jabraham17** [comment]
> Is it when casting any string, or specifically the empty string, or perhaps specifically a param string?

It is specifically a `param` string. For example:
```chapel
param str = "hello";
var a = str:bytes;
```
