### ISSUE TITLE
chpl__init_ModuleName(int64_t _ln, int32_t _fn) has mystery parameters

### ISSUE THREAD

**Issue by tpn** [chapel-lang/chapel#25174]
For a library generated via `$CHPL_BIN --library --debug --dynamic --library-cmakelists --savec lib.c udf.chpl`, the resulting `udf.h` file contains a `chpl__init_ModuleName(int64_t _ln, int32_t _fn)` function stub requiring two int parameters as input.

However, this doesn't match the docs (libraries.rst), which say you can just call your init function like so: `chpl__init_ModuleName()`.

And according to @bradcray, apparently the existing tests pass in two integers.

So either the docs need updating if the parameters are used, or the parameters probably need to be removed if they're not used for anything.

**Comment by bradcray** [comment]
Thanks for filing this, @tpn.  I think some of the history here is that the arguments _are_ used when it is Chapel that's calling the init routines from a normal Chapel program, and so the easy / short-term fix is to update the docs to just suggest users pass in 0's as a placeholder.  But longer-term, it'd be better for us to distinguish between the user-facing and internal versions of these routines and not have the arguments for the user-facing versions  (or…  maybe the compiler doesn't really need to be passing these arguments in for its cases either?  Not sure about that…).

Thanks again!

**Comment by lydia-duncan** [comment]
@tpn - I made #25263 to address this issue.  Do you think my proposed changes would have helped you?  Happy to make any additional improvements if you'd like me to!

**Comment by tpn** [comment]
Hi @lydia-duncan, that looks fine to me, thanks for fixing so quickly!
