### ISSUE TITLE
Add chpl-language-server documentation for vim and emacs

### ISSUE THREAD

**Issue by jabraham17** [chapel-lang/chapel#25189]
We have documentation for chpl-language-server that explains how to set it up for only 2 editors
- [neovim](https://chapel-lang.org/docs/main/tools/chpl-language-server/chpl-language-server.html#neovim)
- [VSCode](https://chapel-lang.org/docs/main/tools/chpl-language-server/chpl-language-server.html#vscode)

We support more editors than this and our documentation should reflect that. Furthermore, having simple instructions (hopefully with copy-paste-able instructions) will make getting started with CLS even easier

We should have specific configs for vim and emacs

**Comment by DanilaFe** [comment]
I'll take Vim, but someone else should probably take Emacs.

**Comment by mppf** [comment]
IMO the highlight/ directory should at least have pointers to these other docs for vscode and neovim

**Comment by lydia-duncan** [comment]
I'm poking Emacs, but if someone actually knows what they're doing, I'd welcome the assist

**Comment by bradcray** [comment]
I will happily be a guinea pig for the emacs docs when they exist.

**Comment by lucaferranti** [comment]
I still haven't looked into setting up the language server for my vim setup, so once the doc is ready happy to guinea-pig if I can follow and reproduce

**Comment by lydia-duncan** [comment]
The emacs docs were merged today!
