### ISSUE TITLE
[Documentation]: Should we move the documentation on syntax highlighting into the online documentation?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#25197]
### Summary of Problem

**Description:**

I noticed this when adding documentation about installing the language server and linter for emacs - the documentation for installing syntax highlighting for emacs and other editors is not a page in the online documentation.  There's a chart in https://chapel-lang.org/docs/main/usingchapel/QUICKSTART.html#what-s-next that just points to the README in the highlight directory.  I think it would be nice to instead have a documentation page that readers can search.

If/when this gets done, the reference to the README I added in #25196 should be updated as well

**Comment by lucaferranti** [comment]
imho this would indeed be a nice addition.

I think it would be nice to have a section titled "Workflow tips" covering things like syntax highlight, language server etc. (although not sure what is left for etc.)

The section could maybe fit under "Users guide"?
