### ISSUE TITLE
Include `CHPL_COMM_OFI_OOB` in printchplenv and unique'd library paths

### ISSUE THREAD

**Issue by jabraham17** [chapel-lang/chapel#25236]
Currently we have `CHPL_COMM_OFI_OOB` which allows selecting between different out-of-band communication primitives. It has a similar relationship to `CHPL_COMM=ofi` as `CHPL_COMM_SUBSTRATE` and `CHPL_GASNET_SEGMENT` have to `CHPL_COMM=gasnet`, but is not included in all the same places.

I think this should be included in `printchplenv` (and by extension `chplconfig`), as well as apart of unique library paths (as this changes the runtime files that are compiled)

**Comment by jhh67** [comment]
See https://github.com/Cray/chapel-private/issues/5501 also.
