### ISSUE TITLE
[Bug]: incorrect error: illegal use of function that does not return a value, involving parenless proc

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#25266]
### Summary of Problem

**Description:**
I'm seeing a surprising error message when a parenless proc is called from an iterator:

```
aa.chpl:25: error: illegal use of function that does not return a value: 'inc1i'
```

`inc1i` does not return a value but it should be callable anyway. The compiler is having trouble because it's not resolved. I ran into this when investigating a failure in `parallel/forall/may-vs-must-par/promo-use-standalone.chpl` for PR #25125, so the code below is a shorter version of that test.

This error goes away if I change `inc1i` to have parentheses (i.e. to no longer be a parenless proc). I suspect that the issue is that the dyno scope resolver is causing the production resolver to see an already-resolved call & then it does not try to resolve the function.

**Is this issue currently blocking your progress?**
no

### Steps to Reproduce

**Source Code:**

```chapel
config const ni = 2;
const RNGi = 1..ni;

proc inc1i { }

iter iter1par() {
  writeln("iter1par serial");
  for idx in RNGi do
    yield idx;
}
iter iter1par(param tag) where tag == iterKind.standalone {
  writeln("iter1par standalone");
  for idx in RNGi.these(tag) do
    yield idx;
}
iter iter1par(param tag) where tag == iterKind.leader {
  writeln("iter1par leader");
  for idx in RNGi.these(tag) do
    yield idx;
}
iter iter1par(param tag, followThis) where tag == iterKind.follower {
  inc1i;
  for idx in RNGi.these(tag, followThis) do
    yield idx;
}

proc multiply(arg1: int, arg2: int)   { writeln("mul=", arg1*arg2); }

multiply([ IND in iter1par() ] IND, 0);
```

**Associated Future Test(s):**
TODO

**Comment by bradcray** [comment]
> However inc1i does return a value.

In your example above, it doesn't seem to return one.  But I suspect the point is that it shouldn't matter whether it returns a value or not—you should be able to call it anyway, right?

**Comment by mppf** [comment]
> > However inc1i does return a value.
> 
> In your example above, it doesn't seem to return one. But I suspect the point is that it shouldn't matter whether it returns a value or not—you should be able to call it anyway, right?

Yes, thanks, that was a typo/thinko, I've corrected the issue description.
