### ISSUE TITLE
[Feature Request]: Remote variables: allow non-locale arguments to `on`.

### ISSUE THREAD

**Issue by DanilaFe** [chapel-lang/chapel#25287]
Chapel allows `on` clauses to accept non-locale arguments:

```Chapel
on someVar do ...
/* same as...*/
on someVar.locale do ...
```

However, this doesn't currently work with remote variables:

```Chapel
on Locales.last var x = 42;
on x var y = 42;
```

The resulting error is not the best:

```
onremotevar.chpl:2: error: unresolved call 'chpl__buildRemoteWrapper(int(64), 42)'
$CHPL_HOME/modules/internal/ChapelRemoteVars.chpl:39: note: this candidate did not match: chpl__buildRemoteWrapper(loc: locale, type inType)
onremotevar.chpl:2: note: because actual argument #1 with type 'int(64)'
$CHPL_HOME/modules/internal/ChapelRemoteVars.chpl:39: note: is passed to formal 'loc: locale'
onremotevar.chpl:2: note: other candidates are:
$CHPL_HOME/modules/internal/ChapelRemoteVars.chpl:45: note:   chpl__buildRemoteWrapper(loc: locale, in value: ?t)
$CHPL_HOME/modules/internal/ChapelRemoteVars.chpl:57: note:   chpl__buildRemoteWrapper(loc: locale, value: _iteratorRecord)
$CHPL_HOME/modules/internal/ChapelRemoteVars.chpl:50: note:   chpl__buildRemoteWrapper(loc: locale, type inType, in value: inType)
```

This could probably be fixed by adding more overloads of `chpl__buildRemoteWrapper`.

**Comment by bradcray** [comment]
@DanilaFe : Reading the summary, PR #25276 seems to lock in that this works, yet this issue seems to suggest that it doesn't.  I'm sure I'm missing something simple by not spending enough time looking into the details, but what is it?  Thanks!

**Comment by DanilaFe** [comment]
@bradcray: remote variables can be used as targets for `on` __statements__ (`on myRemoteVar do ...`) but regular variables can't be used as targets for `on` __variables__, because the standard library code supporting remote vars is written with a `locale` first formal.

**Comment by bradcray** [comment]
Aha, that's what I was missing—thanks!
