### ISSUE TITLE
[Bug]: GPU codegen fails with ROCm 5.4.3 with --devel

### ISSUE THREAD

**Issue by milthorpe** [chapel-lang/chapel#25295]
### Summary of Problem

**Description:**

Compiling GPU code with `--devel` on AMD MI60 or MI100 with ROCm 5.4.3 results in an internal LLVM codegen error. Without `--devel`, GPU code compiles without issue.

**Is this issue currently blocking your progress?**

No, this is low priority as it only affects developer mode.

### Steps to Reproduce

**Compile command:**

```
$ CHPL_LOCALE_MODEL=gpu CHPL_GPU=amd CHPL_GPU_ARCH=gfx908 chpl --devel $CHPL_HOME/test/gpu/native/jacobi/jacobi.chpl
warning: The prototype GPU support implies --no-checks. This may impact debuggability. To suppress this warning, compile with --no-checks explicitly
Stored value type does not match pointer operand type!
  store i8* null, %chpl_Error_chpl_object** %124, align 8
 i8*internal error: LLVM function verification failed [codegen/cg-symbol.cpp:3026]
```

### Configuration Information

- Output of `chpl --version`:
```
chpl version 2.1.0 pre-release (52469575ad)
  built with LLVM version 15.0.0git
  available LLVM targets: x86-64, x86, amdgcn, r600
Copyright 2020-2024 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)
```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: none
CHPL_HWLOC: bundled
CHPL_RE2: none
CHPL_LLVM: unset
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
AMD clang version 15.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-5.4.3 23045 a29fe425c7b0e5aba97ed2f95f61fd5ecba68aed)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm-5.4.3/llvm/bin
```

**Comment by e-kayrakli** [comment]
Thanks for the bug report, @milthorpe!

@riftEmber and @jabraham17 -- I believe this is pretty much the same issue we faced before, which I noted here: https://github.com/Cray/chapel-private/issues/5916#issuecomment-2137932570. This was a bit of a hindrance for me. I wonder if this new data point helps figure out the issue. @riftEmber also noted that this may be a bug on ROCm's LLVM: https://github.com/chapel-lang/chapel/pull/24461. If that's the case, this is yet another story where we really need to ramp up our ROCm 6 support (but those still use non-version LLVMs...)

**Comment by jabraham17** [comment]
I think this is definitely a problem with the ROCm LLVM, but I think we can work around this one pretty easily.

LLVM 15 switched the default for pointers to be opaque (`ptr` vs `i8*`), and much of our codegen depends on that. However, I think the ROCm LLVM still has the default of typed pointers. And since we set `HAVE_LLVM_TYPED_POINTERS` based on the LLVM version, that causes issues with `--verify` (enabled by `--devel`). This causes a problem in `compiler/codegen/cg-expr.cpp:463` where there is block for `HAVE_LLVM_TYPED_POINTERS`.

One option is to move `if (!isOpaquePointer(adr->getType()))` outside the `ifdef`. Another is to explicitly enable opaque pointers with LLVM 15.

This diff fixes the reproducer for me
```
--- a/compiler/codegen/codegen.cpp
+++ b/compiler/codegen/codegen.cpp
@@ -3354,6 +3354,8 @@ GenInfo::GenInfo()
 #if HAVE_LLVM_VER >= 150 && HAVE_LLVM_VER < 160
   llvmContext.setOpaquePointers(false);
 #endif
+#else
+  gContext->llvmContext().setOpaquePointers(true);
 #endif
 }
```
I need to tweak this ifdef to work for all LLVM versions (setOpaquePointers only existed for a brief period of time) and test it fully.

**Comment by e-kayrakli** [comment]
@jabraham17 Thanks for the quick response! Do you think this could also enable us to use the compiler driver? Or is that a completely separate issue?

**Comment by jabraham17** [comment]
> Do you think this could also enable us to use the compiler driver? Or is that a completely separate issue?

I suspect fixing this will enable us to use the compiler driver

**Comment by lydia-duncan** [comment]
It looks like @jabraham17's #25312  resolved this issue.  Thanks for resolving it, Jade, and thanks for reporting Josh!

**Comment by milthorpe** [comment]
I'm not sure if I should raise as a separate issue, or if it's related to this one: although `--devel` is now working with ROCm 5.4.3, and `-g` by itself also works, combining the two flags fails with a LLVM error:
```
cousteau:~$ CHPL_LOCALE_MODEL=gpu CHPL_GPU=amd CHPL_GPU_ARCH=gfx908 chpl -g --devel $CHPL_HOME/test/gpu/native/jacobi/jacobi.chpl
warning: The prototype GPU support implies --no-checks. This may impact debuggability. To suppress this warning, compile with --no-checks explicitly
MDNode incompatible with Debug Info Version
!DIExpression()
4
debug intrinsic incompatible with Debug Info Version
  call void @llvm.dbg.declare(metadata ptr addrspace(5) %5, metadata !3072, metadata !DIExpression()), !dbg !3073
4
debug intrinsic incompatible with Debug Info Version
  call void @llvm.dbg.declare(metadata ptr addrspace(5) %5, metadata !3086, metadata !DIExpression()), !dbg !3087
4
debug intrinsic incompatible with Debug Info Version
  call void @llvm.dbg.declare(metadata ptr addrspace(5) %9, metadata !3110, metadata !DIExpression()), !dbg !3156
4
debug intrinsic incompatible with Debug Info Version
  call void @llvm.dbg.declare(metadata ptr addrspace(5) %10, metadata !3111, metadata !DIExpression()), !dbg !3156
4
...
cousteau:~$ chpl --version
chpl version 2.2.0 pre-release (612e2aec46)
  built with LLVM version 15.0.0git
  available LLVM targets: x86-64, x86, amdgcn, r600
Copyright 2020-2024 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)
```

**Comment by jabraham17** [comment]
> I'm not sure if I should raise as a separate issue, or if it's related to this one: although --devel is now working with ROCm 5.4.3, and -g by itself also works, combining the two flags fails with a LLVM error:

This does not surprise me at all. We don't generate great debug info for LLVM to begin with, and in some cases produce invalid debug info because of it. The reason you are seeing failures with `--devel` is that it turns on LLVM IR verification, which is flagging the bad debug code.

I think this is definitely worth its own issue.

**Comment by milthorpe** [comment]
Raised as issue #25481

**Comment by bradcray** [comment]
Thanks, Josh!
