### ISSUE TITLE
Update Quick Reference doc to use `new blockDist()`

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#25346]
While proofreading CHANGES.md for 2.1, @dlongnecke-cray noticed that the QuickRef document uses `dmapped blockDist()` where recent changes implemented by @jeremiah-corrado deprecated this form in favor of `dmapped new blockDist()`.  It's not surprising the QuickRef was missed since it's not a plain text file, but having noted this, I wanted to create an issue capturing the need for an update.

**Comment by bradcray** [comment]
Also tagging @jabraham17 and @vasslitvinov who I believe have done the most recent edits to the doc.

**Comment by jeremiah-corrado** [comment]
Thanks for pointing this out, should be addressed by: https://github.com/chapel-lang/chapel/pull/25348

**Comment by vasslitvinov** [comment]
Thanks Jeremiah! This slipped past me when I was reviewing/editing the document recently.
