### ISSUE TITLE
[Bug]: No ambiguity between formals and nested procs of same name

### ISSUE THREAD

**Issue by riftEmber** [chapel-lang/chapel#25376]
### Summary of Problem

**Description:**
No ambiguity/redeclaration error is emitted when a proc contains both a formal and a nested parenless proc with the same name. Instead it just resolves to the nested proc without error. This occurs for both method and non-method procs.

I would expect these to emit an error as we do for a conflict between an automatic variable and a nested parenless proc of the same name.

### Steps to Reproduce

**Source Code:**

```chapel
// method version
record r { }
proc r.test(foo: int) {
  // var foo: int; // this would trigger ambiguity error
  proc r.foo { }
  foo;
}

// non-method version
proc test(foo: int) {
  // var foo: int; // this would trigger ambiguity error
  proc foo { }
  foo;
}
```

**Associated Future Test(s):**
none

### Configuration Information

- Output of `chpl --version`:
```
chpl version 2.2.0 pre-release (260b90bee0)
  built with LLVM version 18.1.8
```

**Comment by mppf** [comment]
@riftEmber I'm not seeing that this is a dyno bug. On `main` with `chpl`, I am not seeing an ambiguity error in this case:

``` chapel
proc test(foo: int) {
  var foo: int; // this does not trigger an ambiguity error
  //proc foo { }
  return foo;
}

var x = test(1);
writeln(x);
```

I think that we view the formals to be in a scope just outside of the function body. So `var foo` in this case is closer than the formal `foo: int`.

The part I am not following is when these code patterns do emit an ambiguity error.

**Comment by riftEmber** [comment]
> I'm not seeing that this is a dyno bug. On main with chpl, I am not seeing an ambiguity error in this case
> I think that we view the formals to be in a scope just outside of the function body

Oh, whoops. I guess it's fine then.

> The part I am not following is when these code patterns do emit an ambiguity error.

This does it:
```
record r { }
proc r.test() {
  var foo: int;
  proc r.foo { }
  foo;
}
```

Except I'm realizing now that https://github.com/chapel-lang/chapel/pull/25231 unintentionally changed this from an ambiguity error to a redeclaration error. I thought about that and had meant to avoid it, but I also don't know if it matters too much either way.

**Comment by riftEmber** [comment]
> Right. If it were proc foo then I would think it should be a redeclaration error; otherwise ambiguity. (But I wouldn't view a redeclaration error in this case as particularly bothersome; just conceptually it should be an ambiguity error because proc r.foo is adding something within record r which isn't in the same scope as var foo.

Okay, that makes sense.

> IMO it'd be reasonable to make an issue about the deficiency and move on to the next thing.

Since I'm already warmed up on this I figured it would take about the same amount of time to just fix it as to make an issue, so I did: https://github.com/chapel-lang/chapel/pull/25407

**Comment by riftEmber** [comment]
Closing as not a bug
