### ISSUE TITLE
Prepare and pursue Chapel's application to E4S

### ISSUE THREAD

**Issue by bonachea** [chapel-lang/chapel#25396]
Now that Chapel finally has a [high-quality Spack package](https://packages.spack.io/package.html?name=chapel), the next logical step is to pursue Chapel membership in the [E4S Programming Model SDK](https://e4s-project.github.io/DocPortal.html).

[E4S](https://e4s-project.github.io/about.html) is a DOE ASCR product that provides [pre-built container images](https://e4s-project.github.io/download.html) with selected Spack packages for a variety of systems, and (perhaps more importantly) professionally managed [deployments on DOE production HPC centers](https://e4s-project.github.io/Deployments.html). Getting Chapel into E4S is a relatively low-effort approach to have it incorporated into the modules installed across a large set of important systems.

You can read about the [E4S membership criteria here](https://e4s-project.github.io/policies.html). Off-hand I suspect that Chapel already roughly meets *many* of the required criteria, but a few (notably including P2 and P5) will probably require some minor additional effort. It's worth noting that many of these criteria come down to a judgement call. As such, I suggest it's in Chapel's best interest to ensure we're prepared to make a strong and coordinated case for how Chapel fulfills each of the required criteria, _before_ proceeding with an application for E4S membership.

I'd like to be involved in this process.

**Comment by arezaii** [comment]
I took a preliminary pass at comparing the requirements to the project's state. Here is what I think we're starting from, roughly:

- [x] P1 Spack-based Build and Installation - Our spack package builds and installs the compiler and runtime, with several variants for configuring the installation.
- [ ] P2 Minimal Validation Testing - TBD - basically contributing a test for the Chapel spackage to the [e4s testing repo](https://github.com/E4S-Project/testsuite).
- [x] P3 Sustainability - The Chapel sources for the spackage are the same as Chapel's normal release and shares a release cycle cadence of once every 3 months.
- [x] P4 Documentation - The Chapel project documentation is available at https://chapel-lang.org/docs/
- [ ] P5 Product Metadata - TBD - need to provide some brief info to populate the fields on this table (https://e4s-project.github.io/DocPortal.html) 
- [x] P6 Public Repository - Chapel sources are available from the public repository github.com/chapel-lang/chapel
- [ ] P7 Imported Software - TBD - we mostly accomplish this by providing spack variants for hwloc, llvm, jemalloc, etc
- [x] P8 Error Handling - Chapel provides helpful error messages
- [x] P9 Test Suite - Chapel provides support for `make check` through `spack test run chapel` (need more tests than that)

**Comment by bonachea** [comment]
PRs against E4S repositories associated with P2 and P5 above are now merged, and Chapel now appears in the [online E4S product list](https://e4s-project.github.io/DocPortal.html) as a "Member Product".

![image](https://github.com/user-attachments/assets/6c562e06-b096-4eff-b32e-c098043a9aaf)

Our understanding is that Chapel builds should first appear in the E4S 24.11 release that will be packaged in November.

I concur with @arezaii that P7 is also _mostly_ accomplished, as the Spack package variants currently allow swapping in alternative versions of the following bundled third-party dependencies: 

* gasnet
* gmp
* hwloc
* jemalloc
* libfabric
* libunwind
* llvm

This list includes all the dependencies for which the Chapel build system currently documents support for `=system` settings.

Dependencies currently missing `=system` build system support and variants in the `chapel` spackage include:

* qthreads
* re2

Both of these are available in Spack, and could be added as variants with additional effort. However it appears bundled versions of both libraries include some Chapel-specific patches, so vanilla versions might not function correctly without additional Spack-driven patching.

**Comment by bradcray** [comment]
Of those two packages, the re2 patches are necessary for using re2 with Chapel's IO features, and we were unsuccessful in getting them accepted back upstream when we tried (many years ago now, admittedly).

qthreads feels like a package where we'd have a much better chance of using the official Spack formula—I believe that most qthreads patches have traditionally been bug fixes that we've applied before they were available in an official release, though I know we added one recently to work around a C/C++ issue (https://github.com/chapel-lang/chapel/pull/25507 which _may_ be addressed in future qthreads releases, though I don't think we know yet).  And we also recently updated our bundled version to match Qthreads' latest release, which I believe removed the need for any previous bug fix patches (https://github.com/chapel-lang/chapel/pull/25210).  @jabraham17 would be the expert on the latter, and would also know whether we carried forward the patch from #25507.

**Comment by jabraham17** [comment]
Yes we did carry forward the patch from #25507, and currently that is the only patch applied to qthreads on main today.

**Comment by bonachea** [comment]
With the merge of [Spack PR 45659](https://github.com/spack/spack/pull/45659), Chapel is now officially part of the [E4S CI that runs in GitLab](https://gitlab.spack.io/spack/spack/-/pipelines/790685),  [periodically validating](https://github.com/spack/spack-infrastructure/blob/main/docs/deferred_pipelines.md) the develop branch of the Spack repository. After some prodding, Chapel has now finally appeared in the official [Spack build cache](https://cache.spack.io/package/develop/chapel/specs/), a binary mirror used to accelerate builds of Spack packages.
IIUC this was effectively the "final hurdle" to get Chapel accepted into the E4S portfolio, and should ensure the Chapel Spackage continues to be tested and maintained as part of E4S builds going forward. 

There may be further polishing work to be done before the E4S release in November to ensure everything goes smoothly with container packaging (and we should be sure to engage with the E4S folks at that time), but I think we can probably "declare success" on this issue.

The side-discussion above regarding potential new Chapel support for swapping out the qthreads or re2 libraries still seems valuable, but I think it's orthogonal to E4S acceptance.
