### ISSUE TITLE
Bulk transfer between two remote-declared GPU arrays segfaults

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#25431]
```chpl
config const n = 100;

on here.gpus[0] var Arr1: [1..n] int;
on here.gpus[0] var Arr2: [1..n] int;

Arr2 = 1;  // this is run by host using unified addressing (https://github.com/chapel-lang/chapel/issues/25351)

Arr1 = Arr2;  // expect to see a bulk transfer initiated by the host

writeln(Arr1[42]);
```

results in a segfault.

Compiling with `-sdebugBulkTransfer` and running with `--debugGpu`, I see

```
operator =(a:[],b:[]): in chpl__bulkTransferArray
operator =(a:[],b:[]): attempting doiBulkTransferFromKnown
In DefaultRectangular._simpleTransfer(): Alo=(1,), Blo=(1,), len=100, elemSize=8
Copying 800 bytes from device to device
[1]    120042 segmentation fault (core dumped)  ./remoteTransfer --debugGpu
```

which looks right to me. There might be something wrong with the pointers we pass to `chpl_gpu_copy_device_to_device`.

**Comment by DanilaFe** [comment]
I've just validated that the pointers we pass are correct (the same ones that are allocated). The error code I see on `chapdl` is:

```
internal error: gpu-nvidia.c:347: Error calling CUDA function: context is destroyed (Code: 709)
```

Looking into it.

**Comment by Iainmon** [comment]
Could this be related to the auto generated init= for _remoteVarWrapper?

**Comment by e-kayrakli** [comment]
> internal error: gpu-nvidia.c:347: Error calling CUDA function: context is destroyed (Code: 709)


First, my mind went to the fact that we pick CUDA/HIP contexts based on the sublocale you're running on. And the fact that we are not running on any sublocale is the issue here. However, it looks like our device-to-device copy is actually picking (or trying to at least) [the context of the destination](https://github.com/chapel-lang/chapel/blob/main/runtime/src/chpl-gpu.c#L1224). That looks OK to me, but there might be something off there.

**Comment by DanilaFe** [comment]
> First, my mind went to the fact that we pick CUDA/HIP contexts based on the sublocale you're running on. And the fact that we are not running on any sublocale is the issue here.

This was my guess as well, though my (very cursory) reading of the code suggested we pick up the device from the source or destination pointer.

> However, it looks like our device-to-device copy is actually picking (or trying to at least) [the context of the destination](https://github.com/chapel-lang/chapel/blob/main/runtime/src/chpl-gpu.c#L1224).

Yes, that was my impression too.

**Comment by jabraham17** [comment]
I am seeing a similar issue when copying to a remote declared GPU from the host

```
const D = {1..10};
const D2 = D.expand(1);

on here.gpus[0] var A: [D2] int;
var B: [D] int;
A[D] = B; // this segfaults

// this also segfaults without the slice
// var B: [D2] int;
A = B;
```

I compiled with `-sdebugBulkTransfer` and got the following
```
operator =(a:[],b:[]): in chpl__bulkTransferArray
operator =(a:[],b:[]): attempting doiBulkTransferFromKnown
operator =(a:[],b:[]): in chpl__bulkTransferArray
operator =(a:[],b:[]): attempting doiBulkTransferFromKnown
In DefaultRectangular._simpleTransfer(): Alo=(1,), Blo=(1,), len=10, elemSize=8
```

The reverse direction (copying to the host from the GPU) works fine
