### ISSUE TITLE
[Bug]: Failing to capture a returned object from a throwing function causes destructors to not be called

### ISSUE THREAD

**Issue by jabraham17** [chapel-lang/chapel#25548]
### Summary of Problem

**Description:**
When returning an object from a throwing function, the destructors are not called. This occurs with both records and classes. With managed classes, this causes memory to leak.

### Steps to Reproduce

**Source Code:**

```chapel
record R {
  proc deinit() do writeln("deinit");
}
class C {
  proc deinit() do writeln("deinit");
}

config type T = R;

proc get() throws {
  var a = new T();
  return a;
}

proc main() {
  var a = try! get();
  try! get();
}
```

**Compile command:**
`chpl foo.chpl -sT=R`
`chpl foo.chpl -sT='owned C'`
`chpl foo.chpl -sT='shared C'`

**Execution command:**
./foo

**Expected output:**
```
deinit
deinit
```
**Actual output:**
```
deinit
```

**Future test**
test/classes/deinitializers/deinit-from-throws.chpl

### Configuration Information

- Output of `chpl --version`: chpl version 2.2.0 pre-release (705c12edfb)
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: arm64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: system *
CHPL_HWLOC: system *
CHPL_RE2: bundled *
CHPL_LLVM: system
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: LLVM 18

**Comment by DanilaFe** [comment]
I'm working on a fix.
