### ISSUE TITLE
[Bug]: error compiling slice assignment with `--baseline`

### ISSUE THREAD

**Issue by jeremiah-corrado** [chapel-lang/chapel#25570]
In the baseline config, the following program fails to compile:

```chapel
var a1: [1..10] real;

const d = 1..2;
var a2: [d] real;

a1[d] = a2[d];
```

The following error occurs during codegen (with clang as the backend): 
```
/var/folders/5c/dmr73nx964q0w4025lvywb5c0000gp/T//chpl-jcorrado.deleteme-wzTaze/CTypes.c:36:34: error: no member named 'eltType' in 'struct chpl__array_DefaultRectangularArr_1_int64_t_one__real64_int64_t_chpl_s'
call_tmp_chpl10 = (this_chpl35)->eltType;
                  ~~~~~~~~~~~~~  ^
1 error generated.
```

With the llvm backend, an internal compiler error is emitted from `CTypes.chpl:114` (where `c_ptr` is defined).

**Comment by e-kayrakli** [comment]
I am unfamiliar with this (Sorry if I missed a triage email). But this looks like it is on me and from https://github.com/chapel-lang/chapel/pull/24390.

`--no-array-view-elision` is the short term workaround. I think the solution here is to disable AVE with `--baseline`.

**Comment by jeremiah-corrado** [comment]
Okay thanks, that makes a lot more sense, I was wondering how this bug didn't already have an issue (didn't think to check other PRs from the same day that could of caused because the [new tests ](https://github.com/chapel-lang/chapel/pull/22391) failed the first night they were merged, so I figured it was an old issue uncovered by the tests).

The two failing tests are being skipped in baseline now, and I added a [future](https://github.com/chapel-lang/chapel/pull/25571/files#diff-957a96a96f42529e5c1b2e6d19f3277d31efedbb478e4c165a1e6c4a35a765c0) to track this bug. Do you think it makes sense to keep the future around until this is resolved (by disabling AVE for baseline or something else)?

**Comment by e-kayrakli** [comment]
Oh, I already filed https://github.com/chapel-lang/chapel/pull/25587 for a fix. I'll readjust your tests in that PR. That PR is almost trivial, but I'll ask a review from you once I fixed the tests.

**Comment by e-kayrakli** [comment]
> Okay thanks, that makes a lot more sense, I was wondering how this bug didn't already have an issue (didn't think to check other PRs from the same day that could of caused it because the https://github.com/chapel-lang/chapel/pull/22391 failed the first night they were merged, so I figured it was an old issue uncovered by the tests).

I see. Unfortunate timing, then.
