### ISSUE TITLE
[Bug]: qualified access with inheritance makes for a bad error message

### ISSUE THREAD

**Issue by jabraham17** [chapel-lang/chapel#25830]
In the following program, a class is inherited from but it is not in scope

```chapel
  module Other {
    class CC {}
  }
  module M {
    class C: CC {}
  }
```

Compiled with `chpl foo.chpl --main-module M`, this results in the following error

```
foo.chpl:5: error: unable to find parent class named 'CC'
```

However, if the program uses qualified access for `CC`, a confusing error message is emitted
```chapel
  module Other {
    class CC {}
  }
  module M {
    class C: Other.CC {}
  }
```
```
foo.chpl:5: error: Illegal super class
```

This case should give the same error message, "unable to find parent class".

**Comment by DanilaFe** [comment]
There is a way to improve this, but the most principled way would be something relatively invasive and will have to wait until after code freeze.
