### ISSUE TITLE
[Bug]: `const` attached to vararg formal arguments allows their modification

### ISSUE THREAD

**Issue by ty1027** [chapel-lang/chapel#25858]
### Summary of Problem

**Description:**

The following code receives multiple arguments as a tuple (`args`) and attempts to modify
the 1st element of the tuple. ([ATO](https://ato.pxeger.com/run?1=ZZBNDoIwEIXjxkVPMWFFCZYfN0bCHdwbF4gtkgBtyhBDjCdxw0YP5Wks_hFwVpN537zJvOs9PSaKF113a1AsVo_Z3PNAaZlC2W50XmFR2YnOasYYBSPZTkDJRE9lVSOMqZCSMwE46Ry5QayXiq3i0FcMlgu_0bpG45TRaLoA9p4LqTkdFgxkqL7b-jtwYgj8CPqTpTzkogVsVMHJv1EikOuxz4WQ4YfAhZAtXbCEbLRFo3ccn1S-6TwB))

```chapel
// proc myPrintln(args...) // (*1)
proc myPrintln(const args...) // (*2)
{
  writeln("args.type     = ", args.type:string);
  writeln("args (before) = ", args);

  args[0] *= 10;  // modify tuple (just for test)

  writeln("args (after) = ", args);
}

myPrintln(1, 2.3, "four");
```

With no `const` attached (as in Line (*1)), the code prints
```
args (after) = (10, 2.3, four)
```
as expected. On the other hand, if I attach `const` to `args` (as in Line (*2)),
the code still prints the same result, so allowing the modification of `args`.

I posted the above code in the Chapel Discourse (in this [thread](https://chapel.discourse.group/t/const-attached-to-vararg-formal-argument/36578)), and Brad suggests that it may be a compiler bug
(based on another example code for tuples). Please take a look at the above
Discourse page for Brad's test code and explanations.

**Is this issue currently blocking your progress?**
No. (I happened to observe this behavior when playing with `vararg` for practice).

### Steps to Reproduce
I tested the code with the above ATO site.

**Comment by bradcray** [comment]
Thanks for filing this, @ty1027 !

**Comment by lydia-duncan** [comment]
Ooooh, apparently fixing this catches some actual bugs.  That's fun.

**Comment by lydia-duncan** [comment]
Thanks for the report!  Luckily, this turned out to be a very quick fix, which has now been merged.

**Comment by ty1027** [comment]
Thanks very much! It is surprising that the fix was already finished... (in one day!)

**Comment by bradcray** [comment]
@lydia-duncan : Do you happen to know whether your PR fixed the case when default intent was used as well?  (the `*1` version in the OP?)  I could imagine it might if it runs after we've resolved blank intents, but am not sure from checking the diff whether we have or not (and haven't updated any of my clones to include this PR yet).

**Comment by lydia-duncan** [comment]
I thought the *1 version was running as expected?

**Comment by bradcray** [comment]
[It wasn't in 2.0](https://ato.pxeger.com/run?1=ZZBNDoIwEIXjtgdw_cKKEgTRjZFwB_fGBWKrGKCkDDHEeBI3bPRQnsbiH1Fn08n0e2_ad74mu7gUWdteapKj2W0wLLVKkDcLnRaUFXast5XneRy-D9sJODPnD5KooiJ8gxPOjgw46JSEQazHLTWlQFcRLBef0bwi47Tl4a8A9lpIpQXvBQYyVNctxys4EYJxiG5lrjapbEB1mQnY-9q8yEhBoiLO_o1jSUJ_-54Y6_8UuJh4UxeWVLW2ePiM55XSO607), but maybe it depends on what you expect.  :D  

Re-reading the Discourse thread, I don't think I was being as clear there as I thought/hoped I was, but I think that we've generally said tuple components should get the same default as if they were passed independently, such that blank intent should generate an error like const intent for simple types like int, real, string.

**Comment by bradcray** [comment]
It'd be interesting to see whether extending your test to include `INTENT_BLANK` along with `INTENT_CONST` would cause the case in the OP to work, and what impacts it might have on existing code.  I believe it would technically be incorrect because a tuple element that was an array, sync, or atomic (passed by ref by default) should be modifiable with blank intent; but I feel like that'd be a worthwhile bug tradeoff to make in the short-term since it'd be overly strict rather than letting illegal stuff get through.  (in addition, I also imagine that people don't rely on the default ref-ness of these types in a varargs context much).

I think we should either re-open this due to the blank intent case, or fork that off to an issue of its own.

One other belated thought that my first sentence above triggered for me:  Does your checking for `INTENT_CONST` on that PR suggest that if I used an explicit `const in` or `const ref` intent (rather than simply `const`), I'd be back to the original behavior as well?

**Comment by lydia-duncan** [comment]
Okay, so the trouble is that they're not getting transformed into a tuple *arg*, they're getting transformed into individual arguments and placed into a tuple *local variable* for accesses like this.  So the accesses that are problematic are happening to the tuple local variable.

> It'd be interesting to see whether extending your test to include INTENT_BLANK along with INTENT_CONST would cause the case in the OP to work, and what impacts it might have on existing code. I believe it would technically be incorrect because a tuple element that was an array, sync, or atomic (passed by ref by default) should be modifiable with blank intent; but I feel like that'd be a worthwhile bug tradeoff to make in the short-term since it'd be overly strict rather than letting illegal stuff get through. (in addition, I also imagine that people don't rely on the default ref-ness of these types in a varargs context much).

Yeah, I think that would behave how you're describing.  I'm also currently at a loss for how to approach it otherwise without adjusting the handling to make the varargs into a tuple arg instead of individual args.

> I think we should either re-open this due to the blank intent case, or fork that off to an issue of its own.

I'm planning on doing that if I can't fix the issues by the end of the week, yeah

> One other belated thought that my first sentence above triggered for me: Does your checking for `INTENT_CONST` on that PR suggest that if I used an explicit `const in` or `const ref` intent (rather than simply `const`), I'd be back to the original behavior as well?

Oops, probably!  I knew there was a case I was missing ...

**Comment by lydia-duncan** [comment]
> > It'd be interesting to see whether extending your test to include INTENT_BLANK along with INTENT_CONST would cause the case in the OP to work, and what impacts it might have on existing code. I believe it would technically be incorrect because a tuple element that was an array, sync, or atomic (passed by ref by default) should be modifiable with blank intent; but I feel like that'd be a worthwhile bug tradeoff to make in the short-term since it'd be overly strict rather than letting illegal stuff get through. (in addition, I also imagine that people don't rely on the default ref-ness of these types in a varargs context much).
> 
> Yeah, I think that would behave how you're describing.

Oh.  It does generate the error, but the error would absolutely be confusing for users - it mentions `const` but they haven't declared anything explicitly as `const`.  So we'd want something more specialized anyways.  Standby.

> > One other belated thought that my first sentence above triggered for me: Does your checking for `INTENT_CONST` on that PR suggest that if I used an explicit `const in` or `const ref` intent (rather than simply `const`), I'd be back to the original behavior as well?
> 
> Oops, probably! I knew there was a case I was missing ...

Adding a check against `INTENT_CONST_IN` works, but for some reason adding a check against `INTENT_CONST_REF` in the same spot does not.  Are we certain we actually check that we don't modify the contents of `const ref` arguments versus just the memory they point to?

**Comment by bradcray** [comment]
>Oh. It does generate the error, but the error would absolutely be confusing for users - it mentions const but they haven't declared anything explicitly as const. So we'd want something more specialized anyways. Standby.

That sounds [consistent with what we normally do](https://ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuhY3lQuK8pMV0vLzNSo0Faq5FBQqFLRtFQytuWq5uECihgaa1hClUB0wnQA)—not to say it couldn't be improved/clarified, but no reason to handicap this effort over it?

> Are we certain we actually check that we don't modify the contents of const ref arguments versus just the memory they point to?

[Reasonably confident?](https://ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuhY3LQqK8pMV0vLzNZLz84pLFIpS0xQqNBWquRQUKhS0bRUMrblqubjKEosUMhVsFUyMrLlAajM1rSH6ocbAjAMA)

**Comment by lydia-duncan** [comment]
I've opened #25901 for the `const ref` case.  I'm currently testing the behavior for the default intent with atomics/syncs/arrays to see if an issue is needed for them after #25887.  Atomics at least seems to work okay.

**Comment by lydia-duncan** [comment]
Syncs and atomics work, arrays don't.  Probably due to the need to call methods in order to modify syncs and atomics.  Will submit tests demonstrating all three later.  Opened #25903 for arrays
