### ISSUE TITLE
[Bug]: ignoring the yielded values from an interator results in leaked memory

### ISSUE THREAD

**Issue by jabraham17** [chapel-lang/chapel#25893]
### Summary of Problem

**Description:**
Ignoring the values yield by an iterator results in the memory of those object's being leaked (because the `deinit` is not invoked). However, capturing the result in dummy variable allows the deinit to be invoked.

This is highly related to https://github.com/chapel-lang/chapel/issues/25548, where that focused on throwing functions and the issue here is iterators

**Is this issue currently blocking your progress?**
no

### Steps to Reproduce

**Source Code:**

This program will fail to invoke the deinit. if `foo();` is replaced with `var a = foo();`, then the deinit does get invoked

```chapel
record R {
  proc deinit() {
    writeln("deinit");
  }
}

iter foo() {
  yield new R();
  yield new R();
}

foo(); // var a = foo();
```

If the objects yielded are heap memory, then a memory leak occurs

```chapel
record C {
  proc deinit() {
    writeln("deinit");
  }
}

iter foo() {
  yield new C();
  yield new C();
}
iter bar() {
  yield "foo";
  yield "bar";
}

// This leaks memory
foo();
// This also leaks memory
bar();
```

The same solution as before works, introducing a dummy variable causes the deinit to be invoked

**Compile command:**
`chpl foo.chpl`

**Execution command:**
./foo --memLeaks

**Comment by DanilaFe** [comment]
Going to see if this is an easy fix for code freeze.

**Comment by DanilaFe** [comment]
For the first program in the issue OP, `deinit` does not seem to invoked because the entire code to `foo` is gone after resolution (because it's dead?). This doesn't seem correct; I'll try with side effects. On main today (54fd90dc7829dd8f9e75cea8a41eba7b202a6edf),
 the `foo` in the second program does not leak memory, likely for the same reason.
