### ISSUE TITLE
[Bug]: Can't modify an array passed as a part of a vararg with default intent

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#25903]
### Summary of Problem

**Description:**
This issue is to track a bug introduced as part of the effort to stop allowing the modification of `const` arguments.  The default intent for most types is `const`, so it was deemed appropriate in #25887 to apply const to the tuple local variable used to support accesses to the components of a varargs with blank intent.  However, the default intent for an array is instead `ref`, so modification to it should be permitted.

Given that there are very few types where this is true, it seems unlikely that users will try to modify what has been passed to them via varargs, so fixing this is low priority until we hear otherwise.

I suspect it may take some more significant refactoring of how varargs are handled in the compiler for this to be possible without also permitting the modification of other actuals passed to the varargs.

**Is this issue currently blocking your progress?**
No, just tracking it.

### Steps to Reproduce

**Source Code:**

```chapel
proc myPrintln(args...)
{
  writeln("args.type     = ", args.type:string);
  writeln("args (before) = ", args);

  args[0][0] *= 10;  // should not be allowed

  writeln("args (after) = ", args);
}

var arr: [0..2] int = [1, 2, 3];
myPrintln(arr, 2.3, "four");
```

**Compile command:**
`chpl foo.chpl`

**Execution command:**
N/A

**Associated Future Test(s):**
[`test/functions/varargs/varargsModArray.chpl`](https://github.com/chapel-lang/chapel/blob/main/test/functions/varargs/varargsModArray.chpl) #25904 

### Configuration Information

- Output of `chpl --version`: 2.2.0 pre-release
- Output of `$CHPL_HOME/util/printchplenv --anonymize`: any
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: any
- (For Cray systems only) Output of `module list`: N/A

**Comment by lydia-duncan** [comment]
Note that compiling this program without the modification additionally gives a deprecation warning about inferring the intent of the array.  That will probably change between now and when this issue is resolved

**Comment by lydia-duncan** [comment]
Actuallllllly.  This might be due to being on a not clean branch, since the test runs fine with a fresh checkout.  Will come back to this later

**Comment by jabraham17** [comment]
I don't believe this is a bug. The default intent for arrays passed to functions is `const`. Compiling and running this code on main compiles with the correct deprecation warning and has the correct output

```
foo.chpl:1: warning: inferring a default intent to be 'ref' is deprecated - please use an explicit 'ref' intent for the argument 'args'
args.type     = ([domain(1,int(64),one)] int(64),real(64),string)
args (before) = (1 2 3, 2.3, four)
args (after) = (10 2 3, 2.3, four)
```

So this has the correct behavior, you can modify an array with the default intent and get the proper compiler warning that that is deprecated.

**Comment by bradcray** [comment]
> I don't believe this is a bug. The default intent for arrays passed to functions is const.

Oh, right…  I am still living in the past here, and have not done a good job of internalizing the arg vs. parallel intent bifurcation on arrays.  Thanks for setting us straight, Jade!

Since Lydia's on vacation and I'm the one who set her off on the wrong path here, I'm going to close this issue.  I'll also make a note on the draft PR #25904 that the array case there should be changed from a future to a non-future.
