### ISSUE TITLE
[Bug]: writeRange

### ISSUE THREAD

**Issue by tkphd** [chapel-lang/chapel#25940]
### Summary of Problem

**Description:**

I would like to use `writeRange` to print the values in a range.
With Chapel 2.1.0, the primer code [`ranges.chpl`](https://github.com/chapel-lang/chapel/blob/main/test/release/examples/primers/ranges.chpl) fails to compile.

### Steps to Reproduce

**Source Code:**

```chapel ranges.chpl
const r = 1..10;
writeRange(r);
```

**Compile command:**

```console
$ chpl ranges.chpl -o rangetest.o
ranges.chpl:2: error: unresolved call 'writeRange(range(int(64),both,one))'
ranges.chpl:2: note: because no functions named writeRange found in scope
```

### Configuration Information

- Output of `chpl --version`:
  ```console
  $ chpl --version
  chpl version 2.1.0
    built with LLVM version 14.0.6
    available LLVM targets: m68k, xcore, x86-64, x86, wasm64, wasm32, ve, systemz, sparcel, 
    sparcv9, sparc, riscv64, riscv32, ppc64le, ppc64, ppc32le, ppc32, nvptx64, nvptx, msp430, 
    mips64el, mips64, mipsel, mips, lanai, hexagon, bpfeb, bpfel, bpf, avr, thumbeb, thumb, armeb, 
    arm, amdgcn, r600, aarch64_32, aarch64_be, aarch64, arm64_32, arm64
  Copyright 2020-2024 Hewlett Packard Enterprise Development LP
  Copyright 2004-2019 Cray Inc.
  (See LICENSE file for more details)
  ```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
  ```console
  $ /usr/share/chapel/2.1/util/printchplenv --anonymize
  CHPL_TARGET_PLATFORM: linux64
  CHPL_TARGET_COMPILER: llvm
  CHPL_TARGET_ARCH: x86_64
  CHPL_TARGET_CPU: native
  CHPL_LOCALE_MODEL: flat
  CHPL_COMM: none
  CHPL_TASKS: qthreads
  CHPL_LAUNCHER: none
  CHPL_TIMERS: generic
  CHPL_UNWIND: none
  CHPL_MEM: jemalloc
  CHPL_ATOMICS: cstdlib
  CHPL_GMP: none
  CHPL_HWLOC: bundled
  CHPL_RE2: none
  CHPL_LLVM: system
  CHPL_AUX_FILESYS: none
  ```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
  ```console
  $ gcc --version
  gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
  $ clang --version
  Ubuntu clang version 14.0.0-1ubuntu1.1
  Target: x86_64-pc-linux-gnu
  Thread model: posix
  InstalledDir: /usr/bin
  ```

**Comment by jabraham17** [comment]
Hi @tkphd, [`ranges.chpl`](https://github.com/chapel-lang/chapel/blob/main/test/release/examples/primers/ranges.chpl) compiles for me fine with Chapel 2.1.

Just to make sure I understand, are you literally compiling this source file, or trying to use `writeRange(r);` in your own source file?  I think its the latter, in which case that is expected. [`writeRange`](https://github.com/chapel-lang/chapel/blob/main/test/release/examples/primers/ranges.chpl#L392) is a helper function defined inside of the source file for that primer, not a standard library function. If you want to make use of that function, you will need to copy it to your application.

If you are just trying to print out the range, you can use Chapel's normal `writeln` function

**Comment by tkphd** [comment]
ah-HA!! Coming from C & Python, I expected function declarations at the top, and missed this one. Thanks!
