### ISSUE TITLE
[Bug]: `--print-chpl-settings` does not pick up changes from the compiler arguments

### ISSUE THREAD

**Issue by jabraham17** [chapel-lang/chapel#25958]
Users currently have a number of ways to select compiler configurations with Chapel environment variables. They can set the environment variables, they can write a `chplconfig` file, or they can change the variable with a command line flag.

For example, `CHPL_GMP=none chpl ...` and `chpl --gmp=none ...` are equivanelt.

However, when printing out the current compiler configuration using `--print-chpl-settings`, these are not equivalent. `CHPL_GMP=none chpl --print-chpl-settings` shows the current compiler configuration with `CHPL_GMP: none *`, while `chpl --gmp=none --print-chpl-settings` shows whatever the default was.

This does not impact the correctness, as `--gmp=none` still works as far as selecting the right runtime build. But it can be confusing that `--print-chpl-settings` does not match.

**Comment by bradcray** [comment]
I'm really curious what the source of this turns out to be (particularly if I'm responsible… 😬 )

**Comment by mppf** [comment]
The compiler has a map of such environment variables. However, it doesn't look like we `setenv` on all of them. We do `setenv` on a few specific ones in `compiler/main/driver.cpp`. I imagine we could `setenv` these within `setChapelEnvs`.

**Comment by jabraham17** [comment]
Calling `setenv` in `setChapelEnvs` results in all environment variables being set explicitly, which means all environment variables have the little `*` after them when printed, making it meaningless. However, I think the adding `setenv` to `setEnv` should solve the problem, so `setenv` is only called when it is actually overriden

**Comment by mppf** [comment]
do us all a favor and rename `setEnv` so it's not confused with `setenv` :)
