### ISSUE TITLE
When using bundled LLVM and checking out older Chapel versions I get LLVM version mismatch error on 'make clobber'

### ISSUE THREAD

**Issue by stonea** [chapel-lang/chapel#26064]
I have Chapel built using the bundled LLVM. When I checkout an older version of Chapel (for example `git checkout release/1.32`) and try and run `make` or even `make clobber` I'll get errors like this:

```
Error: Problem with llvm-config at /home/users/stonea/chapel/third-party/llvm/install/hpe-cray-ex-x86_64/bin/llvm-config -- LLVM version 18 is not one of the supported versions: 15, 14, 13, 12, 11
/lus/bnchlu1/flash/stonea/chapel/make/Makefile.base:106: *** error running util/printchplenv -- please see error above.  Stop.
make: *** [Makefile:200: clobber] Error 2
```

Ideally in this situation our build system would recognize we have a newer LLVM, would clobber it, and build the older one in place. It's particularly annoying that this happens when running `make clobber`.

It's not too hard to work around it (just manually delete /home/users/stonea/chapel/third-party/llvm/install/hpe-cray-ex-x86_64/).

I get that it may be impossible to solve this for old versions of Chapel, and I haven't verified if this issue still exists in our latest version (I'm not sure how I would?). But it would be good to fix this going forward.

**Comment by mppf** [comment]
I think this is a duplicate of #24421. Also, I seem to recall some change we made in the last few releases to fix problems with `make clobber` and `llvm-config` but I can't find that at a glance.

**Comment by stonea** [comment]
Yes, looks like this is a dup. I'll close it in favor of the older one.
