### ISSUE TITLE
Configure documentation inconsistent with behavior for `--prefix`?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#26107]
I've been trying to use configure when setting up distribution of a Chapel library compiled into a Python package.  In the [documentation for configure](https://chapel-lang.org/docs/latest/usingchapel/building.html#installing-chapel), it says:

> `--prefix=/dir/for/install/` causes the Chapel compiler, libraries, and supporting code to be installed into the directories:
> 
>     `/dir/for/install/bin`
> 
>     `/dir/for/install/lib`
> 
>     `/dir/for/install/share`
> 
> This technique is designed to install Chapel using a standard directory structure for the purposes of integrating it into a standard location that is already in your path, such as `/usr/local/` or `~/`.

To me, this indicated that `~/` was a valid value to use.  But if I use `./configure --prefix=~/`, then I get the following message:

```
error: expected an absolute directory name for --prefix: ~/
```

Was that an incorrect expectation to have?  Is this a bug?  Or is this a sign we should adjust our documentation to not imply that?

**Comment by jabraham17** [comment]
This is possibly a bug introduced by https://github.com/chapel-lang/chapel/pull/23576, where it looks like the code that explicitly handled `~/` was removed?

**Comment by jabraham17** [comment]
I guess that makes it clear we should address this by fixing the docs, not changing `configure`

**Comment by mppf** [comment]
From https://github.com/chapel-lang/chapel/issues/23271#issuecomment-1743478469

> Ah, yes, `./configure --prefix ~/tmp/foo` does expand it, because the shell handles it on the way in to `configure`. Presumably something about `./configure --prefix=~/tmp/foo` leads the shell not to expand it.

So, the documentation could suggest `./configure --prefix ~/`.

(BTW, I would myself not use `~/` as a prefix; instead I would use something like `~/sw`; but this is a matter of personal preference).

**Comment by lydia-duncan** [comment]
I was not having luck with `--prefix ~/` (it gave me help output, oddly enough), so I think I'll just remove the mention of `~` and leave it at that

**Comment by lydia-duncan** [comment]
PR is [here](https://github.com/chapel-lang/chapel/pull/26112), if I could get a review for it :)
