### ISSUE TITLE
[Bug]: Stringification of generic type seems incorrect/misleading

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#26141]
### Summary of Problem

Given a fully-defaulted generic type, like:

```chapel
record R {
  param x: int = 42;
}
```

we typically treat `R` as a "complete" type, which is to say, nothing more is unbound or generic about it, equivalent to `R(42)`.  However, today I was finding that when printing out such a type using code like:

```chapel
type t = R(?);
writeln(t: string);
writeln(R(?): string);
```

it would print as `R` rather than `R(?)`.  This seems confusing/misleading given that, in the code, `R` would mean the non-generic form of the type.  For that reason, I believe it should print out as `R(?)` instead.

### Steps to Reproduce

**Associated Future Test(s):**

[`test/types/records/generic/typeAliasFullyDefaultedGeneric2.chpl`](
      https://github.com/chapel-lang/chapel/blob/main/test/types/records/generic/typeAliasFullyDefaultedGeneric2.chpl
      ) #26137

### Configuration Information

- Output of `chpl --version`: `chpl version 2.2.0

**Comment by DanilaFe** [comment]
Going to take a look and see if there's an easy fix possible.
