### ISSUE TITLE
[Bug]: Compiler can't seem to resolve `param`-passing procedure within `param` bool loop

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#26142]
### Summary of Problem

While writing a test today, I was finding that within the context of a `param` bool loop over `false..true`, I couldn't call to a procedure that accepted a variable whose type was defined using the `param` index variable as an argument.  For example,

```chapel
record R {
  param flag = true;
}

proc bar(x: R(true)) {
  writeln("In bar: ", x.type:string);
}

proc bar(x: R(false)) {
  writeln("In bar: ", x.type:string);
}

for param flag in false..true {
  var r = new R(flag);
  bar(r);
}
```

resulted in the output:

```console
testit.chpl:15: error: unresolved call 'bar(R(false))'
testit.chpl:5: note: this candidate did not match: bar(x: R(true))
testit.chpl:15: note: because actual argument #1 with type 'R(false)'
testit.chpl:5: note: is passed to formal 'x: R(true)'
testit.chpl:15: note: other candidates are:
testit.chpl:9: note:   bar(x: R(false))
```

Interestingly, if rewriting the loop to be a param int loop that casts to bool, it works:

```chapel
for param i in 0..1 {
  param flag = i: bool;
  var r = new R(flag);
  bar(r);
}
```

as does manually expanding the param bool loop into the two cases with hard-coded true/false values.

I do not have a guess as to what's going wrong here.

### Steps to Reproduce

**Associated Future Test(s):**

[`test/types/records/generic/dispatchWithinParamLoop.chpl`](
      https://github.com/chapel-lang/chapel/blob/main/test/types/records/generic/dispatchWithinParamLoop.chpl
      ) #26137

### Configuration Information

- Output of `chpl --version`: `chpl version 2.2.0`

**Comment by DanilaFe** [comment]
Easy fix. Previously, `new_BoolSymbol` created new constants for `true` and `false` each time, which meant that different `true`s could create different instantiations. In fact, this causes a decent amount of problems, including duplicate instantiations for `param true` and `param false`. I think we should be able to just use `gTrue` and `gFalse` instead of creating fresh symbols. This matches the caching behavior for `new_IntSymbol`.

**Comment by bradcray** [comment]
Oh wow, thanks for taking a look!  Are you running with that solution, or just pointing the way for me to try?

**Comment by DanilaFe** [comment]
I'm running with the solution -- see #26144 :)
