### ISSUE TITLE
Applying parens to `.re`/`.im` results in an internal error

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#26263]
### Summary of Problem

**Description:**

When calling `.re` or `.im` on an expression with type `complex`, an internal error is generated.  A user-facing error should presumably be generated instead.

```chapel
var c: complex = 1.2 + 3.4i;

writeln(c.re());  // generates an internal error
```

In developer mode, the internal error is of the form:

```
internal error: Cannot call insertAfter on Expr not in a list [AST/expr.cpp:404]
```

Interestingly, this doesn't happen for user-defined paren-less methods, suggesting it's something special about complexes or these methods, as built-ins:

```
record R {
  proc foo {   // similar result whether this is returning a literal, as here, or a ref or const ref to a field
    writeln("In R.foo");
    return 4.2;
  }
}

var myR = new R();
writeln(myR.foo());  // generates a user-facing error as expected
```

### Steps to Reproduce

**Associated Future Test(s):**
[`test/types/complex/parenfulReIm.chpl`](
      https://github.com/chapel-lang/chapel/blob/main/test/types/complex/parenfulReIm.chpl
      ) #26262

### Configuration Information

- Output of `chpl --version`: `chpl version 2.3.0 pre-release (10cc4042fd)`

**Comment by jabraham17** [comment]
I can replicate this with a user defined parenless method. Having two overloaded parenless methods with differing return intents seems to be the root cause.

```chapel
record R {}
var r = new R();
var myConstant = 1.0;

proc R.foo {
  return myConstant;
}
proc R.foo ref {
  return myConstant;
}

r.foo();
```

**Comment by bradcray** [comment]
Aha, thanks for that insight, Jade!  I thought I was being very clever for thinking of return intents at all, but gave up too soon…

**Comment by DanilaFe** [comment]
Taking look as a little treat for myself :)

**Comment by bradcray** [comment]
Thanks Daniel!  I can just close my PR is you prefer.
