### ISSUE TITLE
Should up/down casting a uint(16) to an int work?

### ISSUE THREAD

**Issue by jabraham17** [chapel-lang/chapel#26301]
With the upgrade to LLVM 19, I came across the following frustrating bug. `test/studies/parboil/SAD/sadSerial.chpl` started to fail when run with `--fast`. I tracked this down to a single line of code

```chapel
sad += abs(a:int - b:int):uint(16); // danger, need these casts
```

Essentially what was occurring is that with LLVM 19, the vectorizer was much more aggressive and would optimize away the cast to `int` (specifically, this was the `slp-vectorizer` pass). This in turn meant that the math was incorrect and could have underflow, if `a` was smaller than `b`.

Replacing this code with `sad += if a > b then a - b else b - a;` resolved the issue. But should that even have been required?

As far as I can tell, we generate nearly identical code as LLVM for this cast+abs logic.

In Chapel
```chapel
proc doit(a: uint(16), b: uint(16)) {
  return abs(a:int - b:int):uint(16);
}
```
```llvm
define internal i16 @doit_chpl(i16 %0, i16 %1) #0 {
  %3 = zext i16 %0 to i64
  %4 = zext i16 %1 to i64
  %5 = sub nsw i64 %3, %4
  %6 = tail call i64 @llvm.abs.i64(i64 %5, i1 true)
  %7 = trunc nuw i64 %6 to i16
  ret i16 %7
}
```

Here is a short gadget in C that has the same sort of casts
```c
#include <stdint.h>
#include <stdlib.h>
#include <math.h>
uint16_t doit(uint16_t x, uint16_t y) {
    return (uint16_t)labs((int64_t)x - (int64_t)y);
}
```
```llvm
define dso_local i16 @doit(i16 noundef %x, i16 noundef %y) local_unnamed_addr {
entry:
  %conv = zext i16 %x to i64
  %conv1 = zext i16 %y to i64
  %sub = sub nsw i64 %conv, %conv1
  %0 = tail call i64 @llvm.abs.i64(i64 %sub, i1 true)
  %conv2 = trunc nuw i64 %0 to i16
  ret i16 %conv2
}

declare i64 @llvm.abs.i64(i64, i1 immarg) #1
```

So I don't think this is due to us generating incorrect LLVM IR. It could be a bug in `slp-vectorize` pass, but I have not dug deep enough into it to determine that.

**Comment by bradcray** [comment]
In case it's unclear from the issue title + context, `a` and `b` in the original line of code are of type `uint(16)`.

IIRC, signed integer underflow/wraparound is not well-defined in C (and we inherit that behavior), so if we're relying on it here, that could definitely be problematic.

unsigned integer wraparound is well-defined, though.  Does casting to `uint` work?  (checking, I think the answer is "no"?)

**Comment by jabraham17** [comment]
Casting to `uint` does not work.

```chapel
sad += abs(a:uint - b:uint):uint(16); // danger, need these casts
```

The vectorizer has the same behavior on this and results in the casting being optimized away.

**Comment by bradcray** [comment]
Sorry, thinking about this more and re-reading more carefully, I think you're saying the underflow only occurs when the casts are removed.  Which makes sense since there shouldn't be any values if uint(16) that, when cast to int and subtracted, result in an underflow.  (I think I mistakenly thought we were relying on underflow on the ints).

This does make it seem like a bug to remove the casts to me.  I can't see a justification that an optimizer could legally do that.

**Comment by damianmoz** [comment]
What happens when you do either/both of
```
/* C-code */
sad += (short) abs(((int) a) - (int) b));
sad += (short) abs(a - (int) b));
```
using **clang19**.

They should behave as I read the C standard.

**Comment by jabraham17** [comment]
This definitely appears to be a LLVM bug

The following is in the minimum reproducer in LLVM IR

```llvm
target datalayout = "e-m:o-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "arm64-apple-macosx13.0.0"

define i64 @chpl_gen_main(i16 %0) {
chpl__init_repro.exit:
  %1 = zext i16 %0 to i64
  %2 = or i64 0, %1
  %3 = tail call i64 @llvm.abs.i64(i64 %2, i1 true)
  %4 = trunc i64 %3 to i16
  %5 = zext i16 0 to i64
  %6 = or i64 0, %5
  %7 = tail call i64 @llvm.abs.i64(i64 %6, i1 true)
  %8 = trunc i64 %7 to i16
  %9 = or i16 %8, %4
  %10 = zext i16 0 to i64
  %11 = or i64 0, %10
  %12 = tail call i64 @llvm.abs.i64(i64 %11, i1 true)
  %13 = trunc i64 %12 to i16
  %14 = or i16 %9, %13
  %15 = zext i16 0 to i64
  %16 = or i64 0, %15
  %17 = tail call i64 @llvm.abs.i64(i64 %16, i1 true)
  %18 = trunc i64 %17 to i16
  %19 = or i16 %14, %18
  %20 = zext i16 0 to i64
  %21 = or i64 0, %20
  %22 = tail call i64 @llvm.abs.i64(i64 %21, i1 true)
  %23 = trunc i64 %22 to i16
  %24 = or i16 %19, %23
  %25 = zext i16 0 to i64
  %26 = or i64 0, %25
  %27 = tail call i64 @llvm.abs.i64(i64 %26, i1 true)
  %28 = trunc i64 %27 to i16
  %29 = or i16 %24, %28
  %30 = zext i16 0 to i64
  %31 = or i64 %30, 0
  %32 = tail call i64 @llvm.abs.i64(i64 %31, i1 true)
  %33 = trunc i64 %32 to i16
  %34 = or i16 %29, %33
  %35 = zext i16 0 to i64
  %36 = or i64 0, %35
  %37 = tail call i64 @llvm.abs.i64(i64 %36, i1 true)
  %38 = trunc i64 %37 to i16
  %39 = or i16 %34, %38
  %40 = zext i16 0 to i64
  %41 = or i64 0, %40
  %42 = tail call i64 @llvm.abs.i64(i64 %41, i1 true)
  %43 = trunc i64 %42 to i16
  %44 = or i16 %39, %43
  %45 = zext i16 0 to i64
  %46 = or i64 %45, 0
  %47 = tail call i64 @llvm.abs.i64(i64 %46, i1 true)
  %48 = trunc i64 %47 to i16
  %49 = or i16 %44, %48
  %50 = zext i16 0 to i64
  %51 = or i64 0, %50
  %52 = tail call i64 @llvm.abs.i64(i64 %51, i1 true)
  %53 = trunc i64 %52 to i16
  %54 = or i16 %49, %53
  %55 = zext i16 0 to i64
  %56 = or i64 0, %55
  %57 = tail call i64 @llvm.abs.i64(i64 %56, i1 true)
  %58 = trunc i64 %57 to i16
  %59 = or i16 %54, %58
  %60 = zext i16 0 to i64
  %61 = or i64 %60, 0
  %62 = tail call i64 @llvm.abs.i64(i64 %61, i1 true)
  %63 = trunc i64 %62 to i16
  %64 = or i16 %59, %63
  %65 = zext i16 0 to i64
  %66 = or i64 0, %65
  %67 = tail call i64 @llvm.abs.i64(i64 %66, i1 true)
  %68 = trunc i64 %67 to i16
  %69 = or i16 %64, %68
  %70 = zext i16 0 to i64
  %71 = or i64 0, %70
  %72 = tail call i64 @llvm.abs.i64(i64 %71, i1 true)
  %73 = trunc i64 %72 to i16
  %74 = or i16 %69, %73
  %75 = zext i16 0 to i64
  %76 = or i64 %75, 0
  %77 = tail call i64 @llvm.abs.i64(i64 %76, i1 true)
  %78 = trunc i64 %77 to i16
  %79 = or i16 %74, %78
  store i16 %79, ptr null, align 2
  ret i64 0
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i64 @llvm.abs.i64(i64, i1 immarg) #0

; uselistorder directives
uselistorder ptr @llvm.abs.i64, { 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0 }

attributes #0 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
```

Running `opt --passes='slp-vectorizer'` on this, with LLVM 19 the `zext`/`trunc` code is removed. With LLVM 18 it is preserved. This can be seen in [godbolt](https://godbolt.org/z/zof5rrxze).

I will open an LLVM issue shortly.

For reference, this is how I got this reproducer.

I compiled this Chapel code with `--fast --llvm-print-passes --print-commands --savec tmp`
```chapel
proc main() {

  var refImage = getRandImage();
  var curImage = getRandImage();

  var withAbsRes = getSads(true, refImage, curImage);
  var withoutAbsRes = getSads(false, refImage, curImage);

  for i in withAbsRes.domain {
    if withAbsRes[i] != withoutAbsRes[i] {
      writeln("Mismatch at index ", i, ": ", withAbsRes[i], " != ", withoutAbsRes[i]);
    }
  }


}

param MAX_POS = 1089;
param MAX_POS_PADDED = 1092;
param SEARCH_RANGE = 16;

record image {
  var width, height: uint(16);
  var Dom: domain(1);
  var data: [Dom] uint(16);
}


proc getSads(param useAbs: bool, refImage, curImage) {
  const imageSizeBytes: int = refImage.width * refImage.height * 2;
  const imageWidthMacroblocks: int = refImage.width / 16;
  const imageHeightMacroblocks: int = refImage.height / 16;
  const imageSizeMacroblocks: int = imageWidthMacroblocks * imageHeightMacroblocks;

  var sadsComputed: [0..#(41 * MAX_POS_PADDED * imageSizeMacroblocks)] uint(16);

  sad4CPU(useAbs, sadsComputed, curImage.data, refImage.data, refImage.width/16, refImage.height/16);

  return sadsComputed;
}


proc getRandImage() {
  use Random;
  var width, height: uint(16);
  width = 176;
  height = 144;

  var img = new image(width, height, {0..#width*height});

  fillRandom(img.data);
  return img;
}

param SAD_TYPE_7_CT = 16;
proc SAD_TYPE_7_IX(imageSize) do return imageSize * (25 * MAX_POS_PADDED);


proc sad4CPU(param useAbs: bool, ref blkSad: [] uint(16), frame: [] uint(16), reference: [] uint(16), width: int, height: int) {
  for (mby, yoff) in zip(0..#height, 0.. by 256*width) {
    for mbx in 0..#width {
      ref blkOff = blkSad[(SAD_TYPE_7_IX(width*height) + (mby*width + mbx) * (SAD_TYPE_7_CT * MAX_POS_PADDED))..];
      const ref frameOff = frame[(yoff + mbx*16)..];
      sad4OneMacroblock(useAbs, blkOff, frameOff, reference, mby*16, mbx*16, width, height);
    }
  }
}

proc sad4OneMacroblock(param useAbs: bool, ref macroblockSad: [] uint(16), frame: [] uint(16), reference: [] uint(16), framey: int, framex: int, mbWidth: int, mbHeight: int) {
  var pos = 0;
  var width = mbWidth * 16;
  var height = mbHeight * 16;
  const mlow = macroblockSad.domain.low;
  const flow = frame.domain.low;
  const rlow = reference.domain.low;
  for posy in -SEARCH_RANGE..SEARCH_RANGE {
    for posx in -SEARCH_RANGE..SEARCH_RANGE {
      for blky in 0..#4 {
        for blkx in 0..#4 {
          var sad: uint(16);
          for y in 0..#4 {
            for x in 0..#4 {
              var refx = min(width - 1, max(0, framex + posx + blkx*4 + x));
              var refy = min(height - 1, max(0, framey + posy + blky*4 + y));
              var b = reference[rlow + refy*width + refx];
              var a = frame[flow + (blky*4 + y) * width + (blkx*4 + x)];
              if useAbs then
                sad += abs(a:int - b:int):uint(16);
              else
                sad += if a > b then a - b else b - a;
            }
          }
          macroblockSad[mlow + MAX_POS_PADDED*(4*blky + blkx) + pos] = sad;
        }
      }
      pos += 1;
    }
  }
}
```

I ran `opt` on `tmp/chpl__module-nopt.bc` using the module pipeline printed by `--llvm-print-passes`, recompiled the resulting bitcode into an object file using `llc`, and used the `--print-commands` output to reconstruct an executable. I then could manipulate the optimization pipeline and recompile Chapel code by hand. I confirmed that just removing `slp-vectorizer` from the optimization pipeline was enough to make the behavior bug go away. Then, working with LLVM IR optimized without `slp-vectorizer`, I ran the following `llvm-reduce` command

`llvm-reduce --test reduceScript.sh out_no_slp.ll`

Where `reduceScript.sh` is as follows
```bash
opt -S --passes='slp-vectorizer' $1 | grep '@llvm.abs.v16i16'
```

**Comment by jabraham17** [comment]
LLVM issue: https://github.com/llvm/llvm-project/issues/118410

**Comment by bradcray** [comment]
Great, thanks for reproducing and filing the issue, Jade!

**Comment by jabraham17** [comment]
Noting that this appears to be fixed on main with https://github.com/llvm/llvm-project/commit/709abacdc350d63c61888607edb28ce272daa0a0. If I change [compiler explorer](https://godbolt.org/z/W5W6jPMGd) to LLVM trunk, the regression is fixed. I don't think this made it into 19.1.4, but it looks like it is being backported to the as-yet-unreleased 19.1.5

**Comment by bradcray** [comment]
Do you we should consider applying that patch to our bundled copy of LLVM 19?  😬   (assuming it applies cleanly…   I realize we're bundling 19.1.3 currently).

**Comment by jabraham17** [comment]
I applied the patch to our bundled LLVM and confirmed it fixes things. I would semi-advocate we do this patch to our bundled LLVM, simply because there is a small possibility a user could hit it and break their code. However, I suspect this is an obscure enough issue and few enough people are using the bundled LLVM that there may not be much utility to doing that. However, if others feel more strongly that we should patch our bundled LLVM I can open a PR tomorrow.

```diff
﻿﻿diff --git a/third-party/llvm/llvm-src/lib/Transforms/Vectorize/SLPVectorizer.cpp b/third-party/llvm/llvm-src/lib/Transforms/Vectorize/SLPVectorizer.cpp
index ab2b96cdc42..746ba51a981 100644
--- a/third-party/llvm/llvm-src/lib/Transforms/Vectorize/SLPVectorizer.cpp
+++ b/third-party/llvm/llvm-src/lib/Transforms/Vectorize/SLPVectorizer.cpp
@@ -15440,9 +15440,25 @@ bool BoUpSLP::collectValuesToDemote(
                 MaskedValueIsZero(I->getOperand(1), Mask, SimplifyQuery(*DL)));
       });
     };
+    auto AbsChecker = [&](unsigned BitWidth, unsigned OrigBitWidth) {
+      assert(BitWidth <= OrigBitWidth && "Unexpected bitwidths!");
+      return all_of(E.Scalars, [&](Value *V) {
+        auto *I = cast<Instruction>(V);
+        unsigned SignBits = OrigBitWidth - BitWidth;
+        APInt Mask = APInt::getBitsSetFrom(OrigBitWidth, BitWidth - 1);
+        unsigned Op0SignBits =
+            ComputeNumSignBits(I->getOperand(0), *DL, 0, AC, nullptr, DT);
+        return SignBits <= Op0SignBits &&
+               ((SignBits != Op0SignBits &&
+                 !isKnownNonNegative(I->getOperand(0), SimplifyQuery(*DL))) ||
+                MaskedValueIsZero(I->getOperand(0), Mask, SimplifyQuery(*DL)));
+      });
+    };
     if (ID != Intrinsic::abs) {
       Operands.push_back(getOperandEntry(&E, 1));
       CallChecker = CompChecker;
+    } else {
+      CallChecker = AbsChecker;
     }
     InstructionCost BestCost =
         std::numeric_limits<InstructionCost::CostType>::max();

```

**Comment by bradcray** [comment]
I could go either way.  On the "merge" side, it feels low-risk, like a fair bug fix for code freeze, and is something we'll presumably eventually release when we upgrade to a newer LLVM anyway.  On the "meh" side, I agree with you that the chances are low that users will both (a) be affected by this and (b) benefit from the patch.  Back on the "merge" side, I imagine if we do find users who hit it with their system version, we could suggest they use the bundled version and seem like we're on our game.

I'd suggest either following your instinct or polling the team, or @mppf specifically since he raised the concern today, if you feel on the fence.

**Comment by mppf** [comment]
I'd lean towards including the patch (basically on the principle that we should fix bugs if we can & that especially applies to bugs that cause miscompilation / wrong answers). I think not including it is also reasonable (it takes time, users might not run into it, future LLVMs should fix it & the fix should be available when using the system LLVM).
