### ISSUE TITLE
Improve the error message for when `-j` is used with the LLVM backend

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#26326]
The LLVM backend doesn't support parallel compilation because parallel compilation relies on `--incremental`. AFAIK, `--incremental` is not supported with the LLVM backend, because we generate a big blob of LLVM IR, rather than separate LLVM modules for separate Chapel modules. In any case, the current error message for `-j` with LLVM backend is misleading and should be improved:

```
> chpl -j12 test/release/examples/hello.chpl
error: Incremental compilation is not yet supported with LLVM
```

**Comment by bradcray** [comment]
@e-kayrakli : Taking a quick stab at this, are you calling it misleading because someone using `-j` may not see the connection between `-j` and the mention of "Incremental compilation"?  If so, how do you feel about:

```
Chapel does not currently support '-j'/'--parallel-make' or '--incremental' compilation when using the LLVM back-end
```

If not, can you say more about what you're looking for?

**Comment by e-kayrakli** [comment]
Yep, that's the reason. Your message sounds good to me. If I was doing this, I probably wouldn't have even thought of adding `or --incremental` to the message, but I feel neutral towards it after seeing it.

**Comment by bradcray** [comment]
It's a developer flag, so I was tempted not to mention it; but then I noticed that `-j` and `--parallel-make` are also developer flags, so…
