### ISSUE TITLE
record list does not include a record destructor or = overload

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#4956]
The List standard module includes a record list type. One would expect this type to include a destructor that frees the list nodes.

This is not currently the case because of the use of record list in (array, domain, distribution) memory management. However recent changes to array memory management might mean that adding a destructor and = overload is now possible for record list.

**Comment by sagar-sam** [comment]
I would like to work on this issue if the issue is still open, I build the code successfully and found the List standard module.

**Comment by lydia-duncan** [comment]
Can this issue be closed?

**Comment by mppf** [comment]
No, list still doesn't have = overload.

**Comment by cassella** [comment]
PR #5632 added this:

```chapel
proc =(ref l1: list(?t), const ref l2: list(?t2)) {
...
```

Is something else needed?

**Comment by mppf** [comment]
@cassella - thanks for pointing that out. I'm closing the issue now.
