### ISSUE TITLE
cannot use begin in an overridden method

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#4957]
The following program core dumps on master now:
```
class Parent {
  proc runTask() {
  }
}

class Child : Parent {
  proc runTask() {
    begin {
      writeln("IN TASK");
    }
  }
}


proc run() {
  sync {
    var obj:Parent = new Child();
    obj.runTask();
  }
}

run();
```

The problem is that the virtual-method call obj.runTask is passed 1 argument:

  ((void(*)(Parent_chpl))chpl_vmtable[((INT64(5) *
_virtual_method_tmp__chpl) + INT64(1))])(call_tmp_chpl4);

but the invoked function expects 2 arguments:

static void runTask_chpl2(Child_chpl this_chpl,
chpl___EndCount_atomic_int64_int64_t _endCount_chpl)

I think we need to investigating adding the endCount to task-local storage since it is not generally practical to modify all virtual children.

**Comment by cassella** [comment]
The writeln()s in the example seem to think they're in a cobegin.

**Comment by ronawho** [comment]
@mppf resolved this with https://github.com/chapel-lang/chapel/pull/6765, which also added the above example to the test infrastructure: https://github.com/mppf/chapel/blob/576a90d637/test/parallel/syncStmt/ferguson/end-count-virtual.chpl
