### ISSUE TITLE
printchplenv should infer CHPL_HOME similar to chpl binary

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#4982]
### Summary of Problem

The `chpl` binary can infer the path of `CHPL_HOME` if it is not set based on a variety of checks defined in `compiler/driver.cpp`. `printchplenv` does not have the equivalent checks, and therefore can lead to disagreement between the two, when `CHPL_HOME` is being inferred. 

### Proposed Solution

`printchplenv` should use the same rules that the compiler uses to infer `CHPL_HOME` when it is not set.

### Example

```bash
unset CHPL_HOME

# CHPL_HOME is inferred using the rules defined in compiler/driver.cpp:
>chpl --print-chpl-home
/path/to/CHPL_HOME /path/to/chpl


# CHPL_HOME is empty, and confusingly labeled with a '*'
# which is intended to mean the default value has been overridden (which it hasn't in this case):
>printchplenv --anonymize
machine info: ...
CHPL_HOME:  *
script location: /path/to/CHPL_HOME/util/
CHPL_TARGET_PLATFORM: darwin
...
```

**Comment by bradcray** [comment]
In the interest of coming up with common understandings of labels: this seems more like a feature request (or enhancement) than a bug to me...?
