### ISSUE TITLE
Check annotations file as part of the smoke test

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#4998]
Check the [ANNOTATIONS.yaml](https://github.com/chapel-lang/chapel/blob/master/test/ANNOTATIONS.yaml) file as part of the smoke test.

We often get the syntax wrong as seen in https://github.com/chapel-lang/chapel/pull/4828, https://github.com/chapel-lang/chapel/pull/3911, https://github.com/chapel-lang/chapel/pull/4997, and many others. 

Should be relatively simple to do: I think we just need to add a list of valid configs to [annotate.py](https://github.com/chapel-lang/chapel/blob/master/util/test/annotate.py) and then have a self check mode that reads through all the annotations and validates that they're formatted corrected. 

Bonus points for going through the PR numbers and making sure that we annotated the dates correctly.

Note that this would require that the smoke test has PyYAML available, so to start we could just make this a developer only tool that perf team members would run.

**Comment by lydia-duncan** [comment]
Would a reasonable alternative be having Travis run "start_test -generate-graphs"?

**Comment by ronawho** [comment]
I don't think so. The problem with that (and why we often don't catch this issue before merging) is because gengraphs (and thus start_test) will only pull annotations for days that it has data and will leave the other annotations unparsed. 

We want something that force parses all annotations and it'd be nice to check that configs listed are valid by storing a list of all our valid configs (chapcs, Single node XC, 16 node XC, etc)

**Comment by ronawho** [comment]
We should also warn when there's no .graph file for a given annotation to avoid "losing" annotations from .graph splits or similar changes. For example we "lost" lcals annotations like https://github.com/chapel-lang/chapel/commit/8f730c2c when https://github.com/chapel-lang/chapel/commit/16614a7a2 went in

**Comment by ronawho** [comment]
We also lost annotations when we switched xc-* to ml-* (#5191). Fixed in #5525 along with a typo that would have caught with a "warn when there's no.graph file" check

**Comment by ronawho** [comment]
Added a basic checker with #5538. It should catch syntax errors, invalid 'config' names ('1 node XC' instead of 'Single node XC'), and using the commit date as the annotation date. It also warns when there's no .graph for a given annotation. 

The script isn't super pretty, but I'm pretty happy with it overall. I think we should try it out manually for the next few weeks, and if all goes well add it to the smoke test.

**Comment by ronawho** [comment]
Running as part of travis testing with #6917

**Comment by ben-albrecht** [comment]
> Bonus points for going through the PR numbers and making sure that we annotated the dates correctly.

Note that Travis CI does a `git clone --depth 50` so this check only works on recently merged PRs, and is otherwise ignored.

We can update our `.travis.yaml` to increase the commit depth if we find `50` to be insufficient.

**Comment by ronawho** [comment]
https://github.com/chapel-lang/chapel/pull/7158 bumps the depth to 100,000 (effectively a full clone) for the annotation checker. It only adds ~45 seconds for that config, so it should still finish well before the `make check` and `make check docs` configs
