### ISSUE TITLE
comm=ugni internal error (transfer too large?)

### ISSUE THREAD

**Issue by gbtitus** [chapel-lang/chapel#5003]
### Summary of Problem

An internal user (Chapel team member) reports an internal error in a system library called from the ugni comm layer, in a program that attempts to transfer 10\*\*30 ints between top-level locales in a single operation.  The root cause has not yet been diagnosed, but it wouldn't be a bit surprising if this larger transfer needed to be broken up into smaller chunks, for the network to be happy.

### Steps to Reproduce

**Source Code:**

Use the existing Chapel ISx test with large enough parameters, on a Cray XC with CHPL_COMM=ugni and a craype-hugepages module loaded.  The heap has to be on hugepages because if it is not, there is already code to do the transfer using bounce buffers, breaking it up as needed, and the bounce buffers are much smaller (megabytes) and already known to work.

**Comment by mppf** [comment]
@gbtitus - was this fixed by PR #5009?

**Comment by gbtitus** [comment]
No, one can still build a program that has the problem -- you just need the array big enough that it uses eough of the heap to span the boundary at which we did an mprotect().  I'll fix this remnant problem later.

**Comment by mppf** [comment]
That's technically true but I'm not sure it's true in practice. In particular, a Chapel user doesn't know how much of the Chapel heap is used by the runtime. So the program might fail if you get within 8MB of the total heap to be allocated, either way.
That's assuming that the last 8MB in the heap is allocated when the rest is, which isn't necessarily true...

**Comment by gbtitus** [comment]
If the registered heap spans more than one kernel memory segment, and thus more than one kGNI memory segment, and thus more than one uGNI memory region, then it CAN happen that a comm-ugni transfer spans a region boundary.  Since we know this is possible and an internal error will result, it's appropriate to have an issue for it.

**Comment by ronawho** [comment]
We think the heap spanning multiple kernel memory segments was resolved with dynamic registration, right?

There's still an issue where we're not breaking up large puts/gets into FMA allowable bite chunks

Here's a simple reproducer (which I'll add as a future soon):

```chapel
use Memory;

type elemType = uint(8);
config const memFraction = 3;
config const numMB = here.physicalMemory(unit = MemUnits.MB) / memFraction;

const n = (numMB * 1024 * 1024) / numBytes(elemType);


var A: [1..n] elemType;
on Locales[1] {
  var B: [1..n] elemType;
  B = A;
}
```

```
chapel (master) $ ./f -nl2 --numMB=128
chapel (master) $ ./f -nl2 --numMB=256
chapel (master) $ ./f -nl2 --numMB=512
chapel (master) $ ./f -nl2 --numMB=1024
chapel (master) $ ./f -nl2 --numMB=2056
internal error: 1:comm-ugni.c:6517: internal error: PostFMA() failed
srun: error: nid00077: task 1: Exited with exit code 2
slurmstepd: error: *** STEP 3690844.0 ON nid00076 CANCELLED AT 2017-08-08T14:05:10 ***
srun: error: nid00076: task 0: Killed
```

**Comment by gbtitus** [comment]
No, thinking about it some more, I don't believe the heap spanning multiple kernel memory regions is necessarily fixed.  I believe that the current code that figures out the heap page size can still fragment the heap into multiple segments.  If any heap allocation spans that segment boundary and then we try to transmit to or from that allocation, we'll run across this problem.  It could even be just a 16-byte object.  Moving the fragment boundary to near the end of the heap has made it much less likely that we'll run into this, but it still can happen.

**Comment by ronawho** [comment]
@gbtitus this seems like a pretty embarrassing bug to me, that should be fixed for 1.16. I added 1.16 milestone to it, but let me know if you disagree

**Comment by gbtitus** [comment]
Have we ever seen this in a program that wasn't written (and/or run) specifically to cause it?

**Comment by ronawho** [comment]
Didn't ISx run into this at larger problem sizes?

Any program that does a decent sized bulk transfer could run into it

**Comment by gbtitus** [comment]
Yeah, I understand "could run into it", I was just wondering about "did run into it", as input to answering whether to do this for 1.16.  If ISx runs into it at realistic scales then we should do it for 1.16.  (It's not hard, by the way.  I should be able to get it done in addition to the jemalloc chunk_alloc work.)

**Comment by ronawho** [comment]
Clarified this on chat -- but I meant for this to be a "bug-fix" week item, not something that would interfere with the dynamic registration work
