### ISSUE TITLE
Reuse of strided put/get code from CHPL_COMM=none

### ISSUE THREAD

**Issue by sungeunchoi** [chapel-lang/chapel#5023]
It'd be nice to be able to reuse the CHPL_COMM=none code that does the local strided puts and gets in other comm layers when the put/get is found to be local (or even some of the logic for the remote case).

Currently the gasnet comm layer calls gasnet_[gets|puts]_bulk in all cases.  It's possible the library does the *right* thing here, but the comm statistics are not consistent with the way they are reported in the other functions.

**Comment by ronawho** [comment]
I believe this is done with https://github.com/chapel-lang/chapel/pull/11197. That moved the strided get/put code into a common file that is used for comm none, ugni, and ofi, with the gasnet shim still calling the specialized GASNet functions. @gbtitus feel free to reopen if you think there's more to do here.
