### ISSUE TITLE
Remove node == chpl_nodeID branches from executeOn code

### ISSUE THREAD

**Issue by sungeunchoi** [chapel-lang/chapel#5025]
These branches are now taken care of by the locale model, and so the branches should have been removed with #4074.  Replace with `assert(node != chpl_nodeId)`.

**Comment by mppf** [comment]
@sungeunchoi - could you say which file you're talking about here?

**Comment by sungeunchoi** [comment]
comm-gasnet.c

**Comment by mppf** [comment]
I'm closing this issue because comm layers currently have an assert(0) in these branches and a note to say that the locale model takes care of that case.
