### ISSUE TITLE
Stop .notest`ing multilocale/lydia/checkNumTasks

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#5028]
multilocale/lydia/checkNumTasks is currently racey, so I .notest'ed it with #5029

It basically does: 

```chapel
coforall loc in Locales do on loc {
  num.add(here.runningTasks());
}
```

which is transformed into something like (some pseudocode + manually inlining functions):

```chapel
endCount = endCountAlloc()
for loc in Locales {
  ...
  // runtime call to startMovedTask will bump here.runningTasks
  spawn_task_to_loc(loc, num.add(here.runningTasks()) 
}

/* snippet of inlined waitEndCount below: */

// Remove the task that will just be waiting/yielding in the following
// waitFor() from the running task count to let others do "real" work.
here.runningTaskCntSub(1); 

endCount.waitFor(0);

// re-add the task that was waiting for others to finish
here.runningTaskCntAdd(1);
```

Technically there will be 2 tasks running on locale 0, but we lie and decrement the runningTasks counter since the spawning task will just we waiting/yielding and not doing any real work or using up many cycles if there are other tasks running.

However, this the original task on locale 0 and the task spawned to locale 0 doing the here.runningTasks() query can run in either order, so we have a race for the call to here.runningTasks() is racey.

Applying #5018 to coforall+on constructs will resolve this race, because we'll adjust the runningTasks counter before creating any tasks. Until that's in I'm just .notest'ing this test to avoid noise in nightly testing.

**Comment by ronawho** [comment]
https://github.com/chapel-lang/chapel/pull/6419 applied the "bounded" coforall optimization for coforall+on constructs, so this test could be run again. 

That said, I think the new task counting tests in https://github.com/chapel-lang/chapel/pull/7193 are more reliable and cover this case. Specifically this test will fail for --baseline because the `num.add(here.runningTasks());` will spawn a new task to locale 0 if optimizeOnClauses doesn't turn it into fast-on

@lydia-duncan any objections to retiring this test?

**Comment by lydia-duncan** [comment]
No objections, it sounds like its purpose is fulfilled in a better manner now
