### ISSUE TITLE
Add a standard iterator that chunks a range in a round-robin fashion

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#5036]
An idiom that seems reasonably familiar to me (and came up recently for me in test/release/examples/benchmarks/shootout/fasta.chpl) is chunking a range up by a given chunk size in a block-cyclic manner.

For example, fasta contains:

    for i in tid*chunkSize .. n-1 by numTasks*chunkSize {
      const bytes = min(chunkSize, n-i);

where tid ranges from 0 to numTasks.  The 'bytes' variable essentially asks "how large is my chunk".  The loop itself is somewhat ugly looking.  Could/should we come up with a better interface (as part of the RangeChunking module, e.g.) that would permit something more like:

    for chunk in greatIteratorName(0..#n, chunkSize, tid, numTasks) {
      const bytes = chunk.size;

where the yielded 'chunk' is a range?  ('greatIteratorName' is a placeholder because I don't have a great name for this in mind right now).

**Comment by daviditen** [comment]
I've been working with @abhi-rao on this.  I think it's nearly ready, but we need to choose a name that works for everybody.  It is currently named `iter roundRobinBasedChunkOfBlocks(r: range,  blockSize, idx, numChunks)` in PR #5928.

**Comment by daviditen** [comment]
Maybe: `blockCyclicChunks(r: range, blockSize, idx, numInds)`

Some possible names for the last two arguments:
```
(tid, numTasks) // The names from the first comment in this issue
(rank, numRanks)
(idx, numInds)
```

**Comment by psahabu** [comment]
Even though it takes a second for me to get what is meant by `idx`, `(idx, numInds)` fits best with the rest of the library and I support that choice.

**Comment by rahulghangas** [comment]
Here's something I whipped up quickly (would be cleaned properly written later) if this is still not implemented (it hasn;t been in RangeChunk.chpl). Ignore the mix of snake and camel case

```chapel
iter rr(r, blockSize, idx, numInds){
  
  var range_stride = r.stride;
  var block_stride = blockSize * range_stride;
  var low = r.low;
  var high = r.high;
  var first_block_start = (if range_stride > 0 then r.low - 1 else r.high + 1) + block_stride * (idx + 1);
  if first_block_start > r.high || first_block_start < r.low then return;

  var stride_to_next_block = block_stride * numInds;
  
  if range_stride > 0 {
    for block_start in first_block_start..high by stride_to_next_block {
      var block_end = min(high, block_start + block_stride - 1);
      yield block_start..block_end by range_stride;
    }
  }else{
    for block_end in low..first_block_start by stride_to_next_block {
      var block_start = max(low, block_end + block_stride + 1);
      yield block_start..block_end by abs(range_stride);
    }
  }
}

writeln("1: ", rr(1..100, 3, 3, 5));
writeln("2: ", rr(-7..25, 3, 3, 5));
writeln("3: ", rr(25..50, 3, 3, 5));
writeln("4: ", rr(0..99 by 2, 3, 3, 5));
writeln("5: ", rr(1..100 by 3, 3, 3, 5));
writeln("6: ", rr(3..30 by -2, 3, 3, 5));
writeln("7: ", rr(0..1 by -1, 1, 0, 2));
```

Outputs

```
1: 12..14 27..29 42..44 57..59 72..74 87..89
2: 4..6 19..21
3: 36..38
4: 23..28 by 2 53..58 by 2 83..88 by 2
5: 36..44 by 3 81..89 by 3
6: 3..7 by 2
7: 1..1
```

**Comment by rahulghangas** [comment]
@daviditen  should I open a new PR since the old one has been stagnant for a while?

**Comment by daviditen** [comment]
@rahulghangas Yes, sounds good. Thanks!

**Comment by cassella** [comment]
Did #15109 fully implement the request here?

**Comment by daviditen** [comment]
Yes, I think so. Thanks!
