### ISSUE TITLE
Support initialization of atomic variables

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#5037]
At present, atomic variables can't be initialized:

    var myAtomic: atomic int = 42;

The historical reason for this is that we haven't distinguished initialization from assignment (though that's changing!) and don't permit direct assignment to atomics.  This idiom comes up reasonably frequently and is painful to code around, so it'd be really nice to enable it as soon as we can.

(Note that some have argued that we should also support direct assignment to / reads from atomics.  I'm not advocating for that here, and would to keep that potential issue separate from this one.  I think the initialization case is more of a no-brainer because it's obvious that there could be no race-y reads/writes in the initialization context).

**Comment by bradcray** [comment]
Tagging @lydia-duncan on this topic simply because she's the person most likely to recognize when we distinguish initialization from assignment enough to make this change (if we don't already).

**Comment by lydia-duncan** [comment]
Hmm, that is an interesting idea!  I'll assign myself to it for now

**Comment by bradcray** [comment]
Just a quick note to point out that support for this would permit our chameneos entries to be more elegant by avoiding the need for `this.complete()` calls and `state.write()` calls to initialize the atomic field.  Also noting the relationship to issue #8242 w.r.t. support for assignment-based initialization.

**Comment by bradcray** [comment]
I believe this is now implemented as part of @benharsh's PR #12387 and so can be closed.
