### ISSUE TITLE
declaration lists break 'config type'

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#5039]
### Summary of Problem

It seems that config type statements that define multiple symbols don't work.  See test/types/config/twoConfigsOneDecl.chpl for an example.

### Steps to Reproduce

**Source Code:**

```chapel
config type randType = uint(32),
            char = int(8);
```

**Compile command:**
`chpl twoConfigsOneDecl.chpl`

**Execution command:**
N/A (gets internal error)

### Configuration Information

- Output of `chpl --version`: 1.14.0.7f81ddd
- Output of `$CHPL_HOME/util/printchplenv --anonymize`: N/A
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: N/A
- (For Cray systems only) Output of `module list`: N/A

**Comment by daviditen** [comment]
Fixed by PR #7637.
