### ISSUE TITLE
Investigate apparent loss of FFT performance

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#5055]
As shown on the graph linked to below, on November 26-27 2016, 16-node HPCC FFT performance got significantly better in the ugni+qthreads configuration.  Then on December 7th, the allocation of args on the stack rather than the heap set these timings back.  Some of the performance was recovered on December 14th, but it looks like it did not fully recover.

This issue is meant to capture a desire to understand whether there are further improvements that could/should be made to recover the previous performance.  In this morning's performance meeting, it was suggested that the right time to investigate this might be after Qthreads is using Chapel's memory management for its stacks.

http://chapel.sourceforge.net/perf/16-node-xc/?startdate=2016/10/31&enddate=2016/12/15&graphs=hpccfftperfgflopsn220

**Comment by bradcray** [comment]
Tagging @mppf on this to make sure he was aware of it and @chapel-lang/perf-team as a follow-up to today's meeting.

**Comment by ronawho** [comment]
This has been resolved by allocating qthread stacks out of our heap (#5637). The test was pretty noisy with just that PR, but bumping the QT_SPINCOUNT on crays (#5646) has stabilized it to ~.9 Glop/s (50%) faster than ugni-muxed:

http://chapel.sourceforge.net/perf/16-node-xc/?startdate=2017/02/25&enddate=2017/04/15&graphs=hpccfftperfgflopsn220
