### ISSUE TITLE
slurm-srun launcher should calculate CHPL_LAUNCHER_CORES_PER_LOCALE accurately

### ISSUE THREAD

**Issue by awallace-cray** [chapel-lang/chapel#5095]
Chapel's slurm-srun launcher should be able to accurately calculate CHPL_LAUNCHER_CORES_PER_LOCALE internally (based on calls to Slurm sinfo), even if CHPL_LAUNCHER_CONSTRAINT is defined. 

Ideally, similar Chapel launchers (slurm-gasnet-ibv) should be reviewed for the same problem. 

At present, if CHPL_LAUNCHER_CONSTRAINT is used to select a subset of available compute nodes, but CHPL_LAUNCHER_CORES_PER_LOCALE is undefined, the slurm-srun launcher's internal calculation will likely be inaccurate because sinfo does not accept Slurm constraints as a command line arguments. 

The desired code change would rewrite lines 129-151 of chapel/runtime/src/launch/slurm-srun/launch-slurm-srun.c:
```   112	// Get the number of locales from the environment variable or if that is not 
   113	// set just use sinfo to get the number of cpus. 
   114	static int getCoresPerLocale(void) {
   115	  int numCores = -1;
   116	  const int buflen = 1024;
   117	  char buf[buflen];
   118	  char partition_arg[128];
   119	  char* argv[8];
   120	  char* numCoresString = getenv("CHPL_LAUNCHER_CORES_PER_LOCALE");
   121	
   122	  if (numCoresString) {
   123	    numCores = atoi(numCoresString);
   124	    if (numCores > 0)
   125	      return numCores;
   126	    chpl_warning("CHPL_LAUNCHER_CORES_PER_LOCALE must be > 0.", 0, 0);
   127	  }
   128	
   129	  argv[0] = (char *)  "sinfo";        // use sinfo to get num cpus
   130	  argv[1] = (char *)  "--exact";      // get exact otherwise you get 16+, etc
   131	  argv[2] = (char *)  "--format=%c";  // format to get num cpu per node (%c)
   132	  argv[3] = (char *)  "--sort=+=#c";  // sort by num cpu (lower to higher)
   133	  argv[4] = (char *)  "--noheader";   // don't show header (hide "CPU" header)
   134	  argv[5] = (char *)  "--responding"; // only care about online nodes
   135	  argv[6] = NULL;
   136	  // Set the partition if it was specified
   137	  if (partition) {
   138	    sprintf(partition_arg, "--partition=%s", partition);
   139	    argv[6] = partition_arg;
   140	    argv[7] = NULL;
   141	  }
   142	
   143	  memset(buf, 0, buflen);
   144	  if (chpl_run_utility1K("sinfo", argv, buf, buflen) <= 0)
   145	    chpl_error("Error trying to determine number of cores per node", 0, 0);
   146	
   147	  if (sscanf(buf, "%d", &numCores) != 1)
   148	    chpl_error("unable to determine number of cores per locale; "
   149	               "please set CHPL_LAUNCHER_CORES_PER_LOCALE", 0, 0);
   150	
   151	  return numCores;
   152	}
```

* Replace the existing call to sinfo, above, with an sinfo call like this:
`sinfo --exact --format="%c %f" --sort="+=#c" --noheader --responding`

* Instead of just reading the first line from the sinfo output, as above, the code change should 
  * examine env variable CHPL_LAUNCHER_CONSTRAINT, which (in Slurm) can be a complex expression including Slurm Feature names, numerical counts, and logical operators
  * extract some or all of the Features contained in this expression
    * a workaround recently implemented in a Cray internal build script, simply preserves any/all tokens matching regex `^[A-Za-z][A-Za-z0-9_]*$` (assuming such tokens are all Slurm Feature names), and discards anything else. 
    * That regex was a guess: I could not find any support for it in Slurm documentation. 
    * The idea to just match on any Feature name seen in the CHPL_LAUNCHER_CONSTRAINT expression was just a guess.  However, if a user ever did craft some complicated CHPL_LAUNCHER_CONSTRAINT expression that was incompatible with this simple scheme, that user could override the implementation by defining env var CHPL_LAUNCHER_CORES_PER_LOCALE, as we are doing now.  
    * An ideal implementation would detect CHPL_LAUNCHER_CONSTRAINT expressions that were too-complicated to evaluate, and emit an error message. 
  * select the first line from the sinfo output where the second token on the line (%f, Feature) matches any of the CHPL_LAUNCHER_CONSTRAINT Feature names
  * return the first token on that line (%c, CPUs) as the value of CPUs per node.

**Comment by awallace-cray** [comment]
Here is a snippet of shell script, showing how CHPL_LAUNCHER_CORES_PER_LOCALE is calculated externally.

```
# select desired compute nodes by Slurm constraint expression
export CHPL_LAUNCHER_CONSTRAINT="IV24|BW28|K20XIV10|K20XSB8"
```

```
# we provide env variable CHPL_LAUNCHER_CORES_PER_LOCALE here, so getCoresPerLocale
# (in slurm-srun launcher) will not need to call sinfo

if test "$CHPL_LAUNCHER" = slurm-srun -a "$CHPL_LAUNCHER_CONSTRAINT" != ""; then
    export CHPL_LAUNCHER_CORES_PER_LOCALE=$(
        sinfo --exact --format="%c %f" --sort="+=#c" --noheader --responding | \
            awk -v "regex=|$CHPL_LAUNCHER_CONSTRAINT|" \
'BEGIN {
    gsub( /[A-Za-z][A-Za-z0-9_]*/, "|&|", regex )
    gsub( /[^A-Za-z0-9_]+/, "|", regex )
    gsub( /\|[0-9_]*\|/, "|", regex )
    gsub( /(^\|)|(\|$)/, "", regex )
}
$1 ~ /^[0-9]+$/ && $2 ~ regex {
    print $1
    exit
}'
    )
    log_info "Setting CHPL_LAUNCHER_CORES_PER_LOCALE to: ${CHPL_LAUNCHER_CORES_PER_LOCALE}"
fi
```

**Comment by jabraham17** [comment]
This was resolved by https://github.com/chapel-lang/chapel/pull/22119, closing
