### ISSUE TITLE
BlockCycDist.chpl:1115: error: halt reached - array index out of bound

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#5097]
### Summary of Problem

The program below hits an error,

    $CHPL_HOME/modules/dists/BlockCycDist.chpl:1115: error: halt reached - array index out of bounds: (288)

while processing `A_bs2`.  There are no problems with the very similar `A_bs`.

It hits the error for index (7,7,1) when run with -nl 1, and for index
(5,7,1) when run with -nl 8.  It runs to completion with -nl 4.

### Steps to Reproduce

**Source Code:**

```chapel
use BlockCycDist;

// works
var Space = { 1..8, 1..4, 1..9};
var D_bs = Space dmapped BlockCyclic(startIdx=Space.low, blocksize=(2,2,3));

// doesn't work with -nl 1, -nl 2, -nl 8.  works with -nl 4.
var Space2 = { 1..8, 1..9, 1..4 };
var D_bs2 = Space2 dmapped BlockCyclic(startIdx=Space2.low, blocksize=(2,3,2));


proc show_array_locality(ref A: [?D]) {
  var L: [D] int;
  for ij in D {
      L[ij] = A[ij].locale.id;
  }
  writeln(L);
}

writeln("A_bs");
var A_bs: [D_bs] int;
show_array_locality(A_bs);

writeln("A_bs2");
var A_bs2: [D_bs2] int;
show_array_locality(A_bs2);
```

**Compile command:**
`chpl --devel blockcycind.chpl -o blockcycind`

**Execution command:**
`./blockcycind -nl 1`

In `BlockCycDist.chpl`, I uncommented the writeln() in
`LocBlockCyclicArr.this(i)`, and enabled (and enhanced) the debugging
for the problematic indices in `LocBlockCyclicArr.mdInd2FlatInd(i: ?t)`

The `-nl 1` run ends with

```code
...
(7, 6, 3)->268
(7, 6, 3)->268
(7, 6, 4)->269
(7, 6, 4)->269
0:d = 1
0:blksize = 2
0:ind0 = 6
0:blkNum = 3
0:blkDimOff = 0
0:
0:d = 2
0:blksize = 3
0:ind0 = 6
0:blkNum = 2
0:blkDimOff = 0
0:
0:d = 3
0:blksize = 2
0:ind0 = 0
0:blkNum = 0
0:blkDimOff = 0
0:
0:blockmults = 12 6 2
0:numblocks = 4 3 2
0:(7, 7, 1)->
0:numwholeblocks = 24
0:blkOff = 0
0:total = 288
(7, 7, 1)->288
$CHPL_HOME/modules/dists/BlockCycDist.chpl:1115: error: halt reached - array index out of bounds: (288)
```

The -nl 8 run ends with

```code
...
(5, 6, 2)->17
(5, 6, 2)->17
(5, 6, 3)->16
(5, 6, 3)->16
(5, 6, 4)->17
(5, 6, 4)->17
0:d = 1
0:blksize = 2
0:ind0 = 4
0:blkNum = 1
0:blkDimOff = 0
0:
0:d = 2
0:blksize = 3
0:ind0 = 6
0:blkNum = 1
0:blkDimOff = 0
0:
0:d = 3
0:blksize = 2
0:ind0 = 0
0:blkNum = 0
0:blkDimOff = 0
0:
0:blockmults = 12 6 2
0:numblocks = 2 2 1
0:(5, 7, 1)->
0:numwholeblocks = 4
0:blkOff = 0
0:total = 48
(5, 7, 1)->48
$CHPL_HOME/modules/dists/BlockCycDist.chpl:1115: error: halt reached - array index out of bounds: (48)
```

### Configuration Information

```code
chpl Version 1.14.0.b95b65c

Copyright (c) 2004-2016, Cray Inc.  (See LICENSE file for more details)
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_MAKE: make
CHPL_ATOMICS: intrinsics
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_WIDE_POINTERS: struct
CHPL_AUX_FILESYS: none

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
```

**Comment by bradcray** [comment]
@cassella : Could you file this as a future as well?  (if you did and I missed it, let me know)

**Comment by cassella** [comment]
The debugging output I enabled above was removed in pr #5139

**Comment by benharsh** [comment]
If no-one objects, I'd prefer to close #5121 and create a more robust test once I understand the problem more. I'd rather figure out what it is about this domain that causes problems and generate others like it.

**Comment by cassella** [comment]
I don't object.

**Comment by benharsh** [comment]
Offline, @bradcray mentioned he didn't object either. I'll close the PR in a moment.

**Comment by benharsh** [comment]
Well, so much for that idea. I can't wrap my head around the existing indexing logic well enough to understand exactly **why** it's failing, so I'm having a hard time figuring out what the precise issue is.

I'll include a shortened version of the original code submission in my PR that resolves the bug.

**Comment by benharsh** [comment]
If either of you are interested, I believe #5229 will resolve this issue.

**Comment by benharsh** [comment]
With #5229 merged, this issue is now resolved. Thanks for reporting, @cassella !
