### ISSUE TITLE
Cyclic arrays and vector operations

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#5163]
### Summary of Problem
Do we desire or expect vector operations (e.g. push_back) to work on Cyclic (or Block) distributed arrays? Currently those operations are not supported and the compiler error is not helpful. We should either support this function, or print a better error message than we do today.

### Steps to Reproduce

**Source Code:**

```chapel
use CyclicDist;

var Space = {1..10} dmapped Cyclic(startIdx=1);
var A : [Space] int;
A.push_back(1);
```

**Compile command:**
`chpl foo.chpl`

**Output**
```
$CHPL_HOME/modules/internal/ChapelArray.chpl:2369: In function 'push_back':
$CHPL_HOME/modules/internal/ChapelArray.chpl:2375: error: unresolved call 'CyclicArr(int(64),1,int(64),false).dataAllocRange'
$CHPL_HOME/modules/internal/ChapelArray.chpl:2375: note:   instantiated from push_back
$CHPL_HOME/modules/internal/DefaultRectangular.chpl:793: note: candidates are: dataAllocRange _mt: _MT, this: DefaultRectangularArr [641848]
$CHPL_HOME/modules/internal/ChapelArray.chpl:2375: error: unresolved call had id 1327198
```

### Configuration Information

This problem has existed since at least v1.14.

**Comment by benharsh** [comment]
@daviditen or @bradcray  might be interested.

**Comment by bradcray** [comment]
I wonder whether adding support for dataAllocRange() (and potentially other routines that were added in the array-as-vec work) to BaseArr which contained compilerError()s saying "push_back() is not currently supported on arrays of this type" would do the trick, or whether we'd run afoul of resolution of virtual functions issues for real array-as-vec codes?  (in which case a halt would likely work but wouldn't generate an error until compile-time).

**Comment by cassella** [comment]
Have array-as-vec operations been sufficiently removed that this issue is moot?

**Comment by bradcray** [comment]
Yes, I think so, thanks!
