### ISSUE TITLE
Example of extern blocks with GSL (in test/users/npadmana) no longer compiles

### ISSUE THREAD

**Issue by npadmana** [chapel-lang/chapel#5166]
## Bug Report

The test of extern block support using GSL test/users/npadmana/gsl_demonstration no longer compiles (I've looked back as far as 1.14 here). This test completely relies on chapel to parse the GSL header files, and exercises the extern block support.

### Summary of Problem

I believe there are two separate issues here.

* On an Ubuntu 16.04 machine, with the stock GCC (GCC 5.4) and GSL packages, chpl immediately complains of missing symbols (eg. "gsl_sf_result"), even those these are correctly defined in the included header files. If I drop down to Ubuntu 14.04 (with GSL 1.16), it correctly gets the definitions from the header files (but see below). I believe (but will verify) that the GSL headers are unchanged from the 16.04 and 14.04 cases, so I think this is an issue with the compiler interacting with the chapel-packaged version of clang. [EDIT : I did verify that this failure seems to be associated with the GCC version, and not GSL].

* Even in this case, the "gsl_spline" case fails with the following error --

error: unresolved call 'gsl_interp_type.initmeme=gsl_interp_type'
note: candidates are: gsl_interp_type.init(name: c_string, min_size: c_uint, alloc: c_fn_ptr
, init: c_fn_ptr, eval: c_fn_ptr, eval_deriv: c_fn_ptr, eval_deriv2: c_fn_ptr, eval_integ: c_fn_ptr, free: c_fn_ptr)

I think this is coming from trying to pass in an external const pointer to a C-struct into a function. I believe this previously worked because the structure was being treated as opaque.

### Steps to Reproduce

The test case in the repository should work, on a system with GSL installed and $GSL_DIR set. The current compopts file assumes that the gsl header and library files are in $GSL_DIR/include and $GSL_DIR/lib respectively (if not in some standard system location.

If it is useful, I could package the two cases up in docker files to reproduce.....

### Configuration Information

Tested on Chapel 1.14, built with CHPL_LLVM=llvm.

**Comment by bradcray** [comment]
@mppf is likely to be interested in this one.  Possibly @ben-albrecht as well.

I frequently point people to this test as a good exercise of extern blocks (did so yesterday in fact) which makes me wonder:  What would it take for us to get regular, nightly testing of this going?

**Comment by mppf** [comment]
I've been able to reproduce but havn't diagnosed the issue yet.

**Comment by mppf** [comment]
I believe that PR #5205 will fix the underlying issue and that #5212 will get gsl_demonstration to run in nightly testing.

**Comment by mppf** [comment]
Correction: we'll need to adjust/add a Jenkins configuration to test test/users/npadmana/ with a CHPL_LLVM=llvm build. As far as I can tell, all our nightly testing tests only a subset with --llvm. Of course we could add this test to the subset, but we ought to be testing it with and without --llvm.

**Comment by bradcray** [comment]
Can a .compopts file be used to have it test with and without --llvm when CHPL_LLVM is set?

**Comment by mppf** [comment]
@bradcray - sure, but the first problem is that as far as I know this directory is not tested in *any* configuration that has CHPL_LLVM set. (The second problem is that our test system scripts always combine setting CHPL_LLVM=llvm and passing --llvm - but these have pretty different impact).

**Comment by bradcray** [comment]
I understood your previous comment that we'd have to add this test to the subset.  Clarifying my previous comment, can the compopts file throw --llvm and --no-llvm?  Or is there some reason that that wouldn't work?

**Comment by mppf** [comment]
Let's talk about the CHPL_LLVM=llvm testing issue here: issue #5214.

As far as I know we can have a compopts file that throws --llvm and --no-llvm, but I haven't yet tried it.

**Comment by mppf** [comment]
About the .compopts idea - the main issue with it is that we'd have to do it on a test-by-test basis which might take more effort than simply adding CHPL_LLVM=llvm --no-llvm testing.
