### ISSUE TITLE
domain.shape && array.shape

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#5178]
I propose to add a parenthesis-less `.shape` method to domains and arrays, which returns a tuple of the number of elements per dimension. This is particularly useful in linear algebra codes where checking against matrix dimensions is a common test.

The feature is inspired by NumPy's [ndarray.shape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html#numpy.ndarray.shape) member.

An implementation and usage might look like the following:

```chapel

  /* Return shape of domain as a tuple */
  proc _domain.shape {
    var shape: this.rank*(int);
    for (i, r) in zip(1..shape.size, this.dims()) do
      shape(i) = r.size;
    return shape;
  }

  /* Return shape of array as a tuple */
  proc _array.shape {
    return this.domain.shape;
  }


// Usage example:

var A41: [{1..4, 1..1}] real,
    A14: [{1..1, 1..4}] real,
    A1:  [{1..1}] real,
    A44: [{1..4, 1..4}] real;

writeln(A41.shape); // outputs: (4, 1)
writeln(A14.shape); // outputs: (1, 4)
writeln(A1.shape);  // outputs: (1)
writeln(A44.shape); // outputs: (4, 4)
writeln(A41.domain.shape) // outputs: (4, 1)
writeln(A14.domain.shape); // outputs: (1, 4)
writeln(A1.domain.shape);  // outputs: (1)
writeln(A44.domain.shape); // outputs: (4, 4)
```

### Details
(some discussed in comments below)

- Sparse arrays and domains return the shape of their parent domain
- `.shape` should always refer to the entire array/domain (locale-independent)
- Associative arrays and domains behave in a similar way as 1D arrays
- To be implemented using `where` clauses to designate array and domain variations 
  - e.g. `where isAssociativeArr(this)`
  - a `where`-less  method will return a compiler error to catch any unimplemented cases.

**Comment by benharsh** [comment]
Would these only be supported on rectangular arrays (e.g., default, block, sparse)? If not, what would they mean for something like an associative array?

**Comment by bradcray** [comment]
Can _array.shape simply 'return this.domain.shape' to reduce future code maintenance?

**Comment by ben-albrecht** [comment]
@benharsh -- It should have the same behavior for sparse arrays and all distributions. I don't think associative arrays have a well-defined shape and should just throw a compiler error.

**Comment by ben-albrecht** [comment]
@bradcray -- Makes sense.

**Comment by e-kayrakli** [comment]
@ben-albrecht , @benharsh -- I just wanted to note that the "shape" of a sparse domain can be confused with more algebraic properties of it such as being symmetrical, banded, skyline etc.. Alternatively users can be forced to use parent domain to query the "shape" of a sparse domain.

**Comment by bradcray** [comment]
Associative domains _could_ have a .shape that's similar to a 1D array with a given number of elements.  But that's effectively their .size, so I don't know if it adds value.  (Though I guess the same could be said for 1D arrays themselves...?)

**Comment by ben-albrecht** [comment]
@e-kayrakli -- I was planning to have the shape of a sparse domain simply return the shape of the parent domain as a convenience, again following the convention of SciPy. Do you think this would be too confusing?

**Comment by e-kayrakli** [comment]
@ben-albrecht  -- No, I am OK with it. Especially if it is a common practice.

**Comment by ben-albrecht** [comment]
>  But that's effectively their .size, so I don't know if it adds value

Well, you could argue that the value it provides is in the consistency of the interface, being that domains and arrays of any variation always have a .shape method.
