### ISSUE TITLE
Implement initializers, based on CHIP 10

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#5198]
For reference, see:
- [CHIP 10](https://github.com/chapel-lang/chapel/blob/master/doc/rst/developer/chips/10.rst)
- [Release notes](http://chapel.cray.com/releaseNotes.html)
  - for Chapel 1.14, see the Language and Compiler Improvements deck, slides 28-40
  - for Chapel 1.13, see the Ongoing Efforts deck, slides 5-23

### Summary
This work seeks to improve the support of classes and records, by replacing our old-style constructors with a more principled strategy of initialization, dubbed "initializers".  When initializers are viewed as sufficiently stable, constructors will begin generating a deprecation message, and will be removed the following release.  Details on what initializers entail may be found in the references listed above.

Tests of this feature live in the directory test/classes/initializers.  Some of those tests pass today and some do not - some tests that pass today are hiding portions that have not been implemented for initializers (for instance, those that rely on generating proper default initializers work, but default initializers are not implemented).  Some of the tests that fail today are not necessarily expected to be fixed by the initializers work, but needed to be migrated to the initializers directory instead of left forgotten in the constructors directory.  Before this feature is complete, we will revisit these tests and take a full appraisal.

Currently, developer resources are being spent on generic initializers and fixing known bugs.  Once generic initializers are complete, it is expected that resources can be placed on generating initializers by default, migrating our library types to use initializers, and implementing more of the checks.  The first two rely on the completion of generic initializers before reasonable progress can be made.

# Remaining TODOs

- [x] generic initializers
  - [x] with type fields
  - [x] with param fields
  - [x] with generic var/const fields
  - [x] for records
  - [x] instance declarations
- [ ] generate initializers by default, instead of constructors
  - potential issues here are runtime types and array alias fields
- [ ] move all library types to using initializers instead of constructors
- [ ] noinit
- [ ] finish implementing Phase 1 and Phase 2 checks, including:
  - [ ] detecting the presence of multiple `.init()` calls in a single control flow path
  - [x] recognizing and generating an error when a field is accessed before it is initialized
  - [x] detecting `const` modification in Phase 2
  - [x] generating an error when field initializations occur before a `this.init()` call
  - [x] recognizing and generating an error when a field initialization or `.init()` calls are in parallel statements
  - [x] detecting and generating an error when `type` and `param` fields are updated in Phase 2
- [ ] fix known bugs, including:
  - [x] accidentally inserting initialization of omitted fields when `this.init()` calls are present in the initializer
  - [x] appropriately handle `super.init()` with records
  - [x] issue with accessing fields in omitted initialization when the field accessed has already been set
  - [x] issue with default values for arguments of initializers defined on generic types
- [ ] recognize and respond appropriately to field initialization or `.init()` calls within conditionals statements (not required for feature completeness, but would be nice)
- [x] de-initializers (thanks, Vass!)

**Comment by lydia-duncan** [comment]
Discussion on de-initializers is occurring in #5201, with a PR on it in #5200

**Comment by lydia-duncan** [comment]
I investigated the possibility of generating type specifiers based on the initializers defined for a generic class or record in #6138.  While it was pretty easy to do part of it and I suspect the remainder would fall out, we would need a way to limit its impact should the user create a set of initializers that would lead to ambiguity on the type specifiers created.  The code remains should we wish to revisit this implementation

**Comment by lydia-duncan** [comment]
Brad suggested that we alter omitted field initialization to instead be inserted just after the last explicit field initialization we saw, rather than just before the next encountered field initialization.  This would allow code like the following to work, when today (I believe) it doesn't:

```chapel
proc init() {
    numProbSizes = 3;
    for n in N do n = 10; // N doesn't get initialized until right after this statement today.
    // The above proposal would allow it to be initialized prior to the for loop, making the for
    // loop valid (instead of forcing it to be a Phase 2 operation).
    super.init();
}
```

**Comment by lydia-duncan** [comment]
Reminder that we should have a discussion on the expected behavior and strategy to support a sync/single field being updated in Phase 1 of an initializer, either explicitly or via omitted initialization

**Comment by mppf** [comment]
Can we close this issue and use other issues to track remaining work?

**Comment by lydia-duncan** [comment]
Seems reasonable to me
