### ISSUE TITLE
approach for #5217: specialize-blank

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#5220]
This issue describes a possible approach to solve the problems in #5217.

The particular approach under consideration here is that blank intent be `ref` or `const ref` for arrays, where the compiler will specialize a function with a blank intent array formal argument based upon whether the calling context had a constant array or not.

blank intent depends on how it is used. The compiler specializes functions based upon which arguments are immutable-const. Blank intent for arrays means "elements are mutable unless they came from a const array".

Put another way, array formal arguments would use:
* `const ref` intent if the actual array is `const`
* `ref` intent otherwise

Pros:
* Similar to generic specialization, which compiler and programmer may be familiar with
* This generic specialization could apply to task functions to implement task/forall intents.

Cons:
* More complicated in concept than current rules
* More complicated to implement than current rules
* Might lead to a lot of code duplication during the compilation process
* Changing how a function is called might lead to new errors in the function's body
* Almost certainly will need to explicitly choose `const` or `ref` for array formals in extern procs.
* Not so clear what to do if the actual argument is a call to a ref-pair function

## What if the actual argument is a call to a ref-pair function?

Here is an example:

```

	proc foo(X) { ... }

	var A: [1..n] [1..3] real;

	foo(A[i]);
```

In this case, should the compiler:
* choose the `const ref` return version ("getter")?
* choose the `ref` return version ("setter")?
* analyze the body of `foo` and decide if the formal `X` is modified
* raise an error due to ambiguity.

**Comment by bradcray** [comment]
Just to tie this up, on email, I suggested that I preferred option 3, which caused this proposal to merge in my mind with issue #5219 and to subsume it ("we'll do everything in #5219 and we'll look at the actual argument as well!").  But this led to the question as to what would be gained by looking at the actual.  In the comments in #5219, I argue to myself that not much is, so am considering the evolution of this approach not just to have subsumed #5219, but to have been absorbed and beaten by it.
