### ISSUE TITLE
Throw '-h error_on_warning' for CCE

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#5246]
The CCE compiler (cray-prgenv-cray) recently added a flag, -h error_on_warning, similar to gcc's -Werror.  I think we should look into whether we could add this when in CHPL_DEVELOPER mode, as we do for gcc, with the goal of keeping our code as clean as possible across as many compilers as we can.  Making the change to the Makefiles is easy... the real question is the level of effort required to get the code through the compiler with the flag on.

OTOH, since we typically (only?) compile the compiler with g++ on Crays, it's only the runtime we're talking about, which may not be too bad.

**Comment by ronawho** [comment]
Just wanted to note that CCE is typically pretty warning happy, and I don't think most of the warnings are all that useful.

We'd also need a way to check the compiler version so we didn't through -herror_on_warning to a version that didn't support it.

**Comment by bradcray** [comment]
W.r.t. version, since it'd only happen with CHPL_DEVELOPER on (and when building from source), I don't think that's a big concern.

If we were to decide that the warnings are ones that we don't care about improving upon, we could either squash those cases (reduce their level of severity) or else not throw -h error_on_warning.

(I'm mostly trying to convert from using my inbox as my TODO list into using GitHub issues :) ).

**Comment by ronawho** [comment]
gotcha, just wanted to share my experience from when I was doing things like getting jemalloc/qthreads/hwloc to build with cce. I ended up turning off warnings because they were so prolific and I didn't find them useful

**Comment by bradcray** [comment]
I think we're on the same page, but in case it wasn't clear, I wasn't proposing we do it on third-party packages, just our code.  (That said, I guess our code #includes their headers so may inherit some of their warnings...?).  Having said that I guess I'm not sure... when we build with gcc do our third-party builds inherit our use of -Werror, or do we similarly not throw it there?  (my money's on "we don't").

**Comment by ronawho** [comment]
Yup, we're on the same page. I didn't think you wanted to turn it on for third-party codes, that's just where I had experience with CCE warnings 

And no, we make sure to note throw -Werror and siblings to third-party

**Comment by bradcray** [comment]
Checking the nightly logs for the CCE build of the runtime, it looks like there aren't too many warnings (though with the  make -j output, I'm not 100% confident I'm seeing everything).  It looks like there are a few we might want to squash or ignore; but then there are a few that look a little intriguing in qio_formatted.c, chpl-cache.c.  Tagging @mppf in case he wants to look at them (not at all a priority).

**Comment by ronawho** [comment]
This will be closed by https://github.com/chapel-lang/chapel/pull/15495, which switches to supporting the clang based cce. clang-cce supports the normal -Werror, which will be enabled since we're just including the clang makefile.
