### ISSUE TITLE
Set --log-ids to true when --log is thrown

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#5260]
### Summary of Problem
I've been finding that most of the time when I want to use --log, I invariably look at the output and curse myself for not throwing --log-ids, and then have to rerun my compilation command again.  If others are having the same issue, I would like us to set --log-ids to true by default when --log is thrown.

**Comment by ronawho** [comment]
Couldn't you just set CHPL_LOG_IDS in your env?

**Comment by bradcray** [comment]
I don't use --log-ids, but wouldn't object to it being thrown by default either.  Note that a way to set this by default that doesn't require any code changes is to set the environment variable backing the flag in whatever "set up my Chapel environment" scripts you use (this is also how I'll turn it off if the IDs are too distracting for me).

Note that if --log-ids has no impact when thrown by itself (and I'm not sure of that), you could just set it to true always rather than making it dependent on --log being thrown -- would be much simpler to implement.

**Comment by lydia-duncan** [comment]
@ronawho - I wasn't aware of that environment variable.  But in principle, I don't think we should rely on an environment variable in this case.  This seems like reasonable behavior to expect of the compiler.  If people object to this change occurring, I will set up my environment as you suggest, but otherwise I think we would be in a better state for development if we didn't have to.

**Comment by lydia-duncan** [comment]
"Do it, but not right now" is also an acceptable answer

**Comment by ronawho** [comment]
I personally use `--log` without `--log-ids` most of the time, and only rarely use `--log-ids`, but I'm not writing compiler code that much anymore so if you and Ben and others who do a lot of compiler debugging prefer it, then I'll just set the env var to off in my env

**Comment by noakesmichael** [comment]
I always use the AstDumpToNode format when I do logging and it always prints
node ids.  I can’t imagine looking at AST without  the IDs.



On Jan 26, 2017, at 3:57 PM, Elliot Ronaghan <notifications@github.com<mailto:notifications@github.com>> wrote:


I personally use --log without --log-ids most of the time, and only rarely use --log-ids, but I'm not writing compiler code that much anymore so if you and Ben and others who do a lot of compiler debugging prefer it, then I'll just set the env var to off in my env

**Comment by bradcray** [comment]
Elliot's latest response could've been my own.

**Comment by lydia-duncan** [comment]
Having the log ids around is really helpful, especially for coupling with --break-on-id, --break-on-resolve-id, --break-on-delete-id during debugging.  If you aren't using it, I suggest doing so, especially if you're working in function resolution.  It really makes life so much easier.

**Comment by bradcray** [comment]
It's funny, I rely on IDs all the time in the debugger and in list_view/print_view, yet I've never missed them in --log.  I think I must only use --log to look at coarse structure, not at specific IDs.
