### ISSUE TITLE
inconsistency for record blank intents, this, and const

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#5266]
Right now, records have inconsistent blank intents. The `this` formal is passed by `ref` by default for record methods and const checking here is not done right.

Consider this code:

``` chapel
record R {
  var i:int;
  proc foo() {
    i = 3;
  }
}


const r = new R();
r.foo();
writeln(r);
```

This example compiles and runs now but should be a compilation error. Arguably, modifying record fields in methods is a convenience of a similar type to being able to modify array elements from a blank intent formal.

Here are the options we are considering:

1) Change default intent for 'this' records into 'const ref' always and require the user to create 'ref' methods for things that should actually modify the record.

 * Pro: makes default intents consistent for 'this' and non-'this' arguments
 * Pro: makes treatment of records more consistent with scalars (our other main value types)
 * Con: adds some syntactic/programmer overhead to the (arguably common) case of defining record methods that modify fields

2) Keep the current default intent for 'this' records as 'ref' but do a better job of const-checking such methods when called on const records.

* Pro: supports the common case of record methods that modify fields
* Con: makes default intents inconsistent between 'this' and non-'this' arguments [blc edit: This used to say "Pro", but should be "Con" right?]
* Con: adds some syntactic/programmer overhead to the (arguably common) case of supporting read-only record methods on constant records.
 * Con: 'this' default intent does not match default argument intent.
 * Con: ref-pair surprises with record methods

3) Make the default intent for 'this' records be 'const ref' or 'ref' based on whether the method is read-only or read-write for the record. (ref-if-modified on this formal only).

 * Pro: permits most record methods to not declare "this intents"
 * Con: 'this' default intent does not match default argument intent.

4) Make the default intent for all record arguments be 'ref' or 'const ref' based on whether the method is read-only or read-write for the argument (i.e. ref-if-modified #5219 for records in addition to arrays).

 * Pro: makes default intents consistent between 'this' and non-'this' arguments
 * Pro: arguably supports "my record should be array-like" cases well
 * Con: arguably doesn't support "my record should be int-like" cases well
 * Con: may feel surprising to C programmers

5) Provide some mechanism for saying what blank intent should mean for a record. Users can select between "ref-if-modified" and "const ref" for blank intent. The 'this' intent matches the blank intent.

 * Pro: makes default intents consistent between 'this' and non-'this' arguments
 * Pro: flexible -- supports array-like and int-like records
 * Con: requires creating the syntax for such a mechanism
 * Con: records that opt-in to "ref-if-modified" may feel surprising to C programmers. Knowing something is a record is no longer sufficient for knowing what blank argument intent means; instead one has to also know if the record opted-in to ref-if-modified or const-ref blank intent.

6) Make the default intent for 'this' records be 'const ref' or 'ref' based on whether the method is read-only or read-write for the record. (ie ref-if-modified on this formal only). Additionally, provide some mechanism to change the blank intent for a record from `const ref` to ref-if-modified.

 * Pro: permits most record methods to not declare "this intents"
 * Pro: flexible -- supports array-like and int-like records
 * Con: 'this' default intent does not match default argument intent.
 * Con: requires creating the syntax for such a mechanism
* Con: records that opt-in to "ref-if-modified" may feel surprising to C programmers. Knowing something is a record is no longer sufficient for knowing what blank argument intent means; instead one has to also know if the record opted-in to ref-if-modified or const-ref blank intent.

**Comment by mppf** [comment]
Here is my thought in favor of option 4:

First, in certain cases, we might have a record containing an array (for example, that is one way we might make a Matrix type). In those cases, I think they will be more intuitive if they can match the array argument behavior.

Second, one reason for 'const' intent being the default for scalar types is so that C and Fortran programmers are less likely to be confused (since these languages have basically opposite behaviors for modifying formals). But, for records, it seems to me that C/C++ programmers normally pass structs by pointer/reference. For that reason I don't think it would be as surprising if a record formal can modify the passed actual. Note that in C/C++ when passing by pointer/reference the default is that the record is mutable.

**Comment by mppf** [comment]
@bradcray was saying this, in the other issue (before we moved the conversation here):

> 
>     Note that in C/C++ when passing by pointer/reference the default is that the record is mutable.
> 
> But it's a "copy in" that's mutable, right? In that respect, they're just like ints (where we chose to make them const so that there wasn't any confusion about whether you were modifying a local copy vs. the actual).

**Comment by benharsh** [comment]
Another motivating example:
```chpl
record R {
  var i : int;
  proc print() {
    writeln(i);
  }
}

const foo = new R(42);
foo.print(); // passing const to 'ref this'?
```

Should this compile?

**Comment by bradcray** [comment]
> in certain cases, we might have a record containing an array (for example, that is one way we might make a Matrix type). In those cases, I think they will be more intuitive if they can match the array argument behavior.

This feels like a slippery argument to me.  If we had a record that wrapped an 'int' or was intended to be 'int'-like (e.g., a bigint record?), a similar argument would say we'd want it to be passed by 'const'.  This might suggest a fifth option (which I think @vasslitvinov has espoused before):

5) Provide some mechanism for saying what blank intent should mean for a record.

**Comment by bradcray** [comment]
This is my attempt to try and list pluses and minuses of the five approaches.  Feel free to suggest others:

1) Change default intent for 'this' records into 'const ref' always and require the user to create 'ref' methods for things that should actually modify the record.

+ makes default intents consistent for 'this' and non-'this' arguments
+ makes treatment of records more consistent with scalars (our other main value types)
- adds some syntactic/programmer overhead to the (arguably common) case of defining record methods that modify fields (however, note that getting it wrong will result in an error at method declaration time)

2) Keep the current default intent for 'this' records as 'ref' but do a better job of const-checking such methods when called on const records.

+ supports the common case of record methods that modify fields
- makes default intents inconsistent between 'this' and non-'this' arguments
- adds some syntactic/programmer overhead to the (arguably common) case of supporting read-only record methods on constant records (and note that getting it wrong won't result in an error until someone tries to call the method on a const record -- i.e., the issue could go unnoticed in developing a library until a user happened to call it on a const record).

3) Make the default intent for 'this' records be 'const ref' or 'ref' based on whether the method is read-only or read-write for the record.

+ permits most record methods to not declare "this intents"
- makes default intents inconsistent between 'this' and non-'this' arguments  

4) Make the default intent for all record arguments be 'ref' or 'const ref' based on whether the method is read-only or read-write for the argument.

+ makes default intents consistent between 'this' and non-'this' arguments
+ arguably supports "my record should be array-like" cases well
- arguably doesn't support "my record should be int-like" cases well

5) Provide some mechanism for saying what blank intent should mean for a record.

+ most flexible -- supports array-like and int-like records
- requires creating the syntax for such a mechanism
~ doesn't really address the scenario in which one might want default intents to mean something other than 'this' intents (for better or worse)

**Comment by bradcray** [comment]
> 
> > Note that in C/C++ when passing by pointer/reference the default is that the record is mutable.
> 
> But it's a "copy in" that's mutable, right? In that respect, they're just like ints (where we chose to make them const so that there wasn't any confusion about whether you were modifying a local copy vs. the actual).

I missed the "passing by pointer/reference" part of this clause, and was thinking you were talking about being able to modify the record when passing it in directly -- sorry.

Personally, I think we should avoid suggesting that:

    proc function(a: R) { ... }  // R is a record type

is equivalent to the C prototype:

    int function( struct mystruct* a )

Instead, I think we should say that that C code is similar to one of:

    proc function(a: C) { ... }       // C is a class type
    proc function(ref a: R) { ... }  // R is a record type

I.e., assuming we continue to say "records are like structs; classes are like pointers to structs", it would seem surprising to me (as a C programmer) to have passing the record behave as though we were passing via a pointer.

**Comment by mppf** [comment]
@bradcray - thanks for the summary of pros and cons. I've updated the issue description to include some form of it.

I have two points to bring up though:

a) For options 1 and 2, you distinguished between compilation error at method declaration time vs error at method call time. But, depending on how the compiler is implemented at the moment, we won't necessarily see errors at method declarations unless that method is called. (ie resolution won't even visit concrete functions unless they are called). We might fix that one day, but I think it makes it less of an argument in favor of 1 today. (For this reason, I didn't distinguish these in the updated issue header).

b) Option 2 seems to me to be really problematic for the same reasons we saw with ref blank array intent and ref-pairs. E.g.
```
record R {
  var i : int;
  proc print() {
    writeln(i);
  }
}
var D = {"one", "two"};
var A:[D] R;
A["three"].print(); // expecting out-of-bounds error, but prints 0 instead
```

**Comment by mppf** [comment]
I've updated Option 5 in the PR description to be a version of that option that actually solves the problem we're discussing. Of course, if others want to create a different combination of Option 5 with the other options... just say so (or create an Option 6 yourself).

**Comment by mppf** [comment]
On the issue of how confused we can make C programmers:

> Personally, I think we should avoid suggesting that:
> 
>     proc function(a: R) { ... }  // R is a record type
> 
> is equivalent to the C prototype:
> 
>     int function( struct mystruct* a )
> 
> Instead, I think we should say that that C code is similar to one of:
> 
>     proc function(a: C) { ... }       // C is a class type
>     proc function(ref a: R) { ... }  // R is a record type
> 
> I.e., assuming we continue to say "records are like structs; classes are like pointers to structs", it would seem surprising to me (as a C programmer) to have passing the record behave as though we were passing via a pointer.

But a record *is* passed in by reference by default - and just like an array, I think that property is important for Chapel programmers to know. In particular, for records that do something when copied (such as strings, GMP bigint, etc), a Chapel programmer isn't paying for the copy by passing them to a function. Additionally, since the record is passed by reference, it could be modified somehow other than by modifying the formal (e.g. by modifying a global aliasing the formal).

Now, I've historically argued that small records should pass 'const in' and big records should be passed 'const ref'. My current viewpoint is that we should only consider changing POD records to be 'const in' by default, since the size of a record has nothing to do with how much work is in its copy-initialization function. Anyway, if all records had ref-if-modifed blank intent, we could still pass those small POD records that weren't modified by 'const in' if it turned out to be important for performance.

Other than enabling 'const' to mean 'const ref' or 'const in' for small POD records, I don't understand why we should shy away from directly describing the behavior as by-reference argument passing. Especially once copy-initialization is involved, I think knowing the difference between `in` and `ref`/`const ref` is pretty fundamental.

**Comment by bradcray** [comment]
> a) For options 1 and 2, you distinguished between compilation error at method declaration time vs error at method call time. But, depending on how the compiler is implemented at the moment, we won't necessarily see errors at method declarations unless that method is called. (ie resolution won't even visit concrete functions unless they are called). We might fix that one day, but I think it makes it less of an argument in favor of 1 today. (For this reason, I didn't distinguish these in the updated issue header).

I don't think this is a fair criticism.  It is true that non-called functions are not checked, but that's an issue that's independent of this feature.  My thinking was that if you define the method and test it *anywhere* (which, arguably, you should do whenever you're building a new library routine, though we've been remiss in this before...), the compiler will catch the const-vs-ref error for you and the routine should be good w.r.t. that issue for all time.  Whereas in option 2, you could've intended to make 'this' 'const' for a read-only method, forgotten to, only tested it with variables, and then blown up someone's code when they try to call it on a const.

> b) Option 2 seems to me to be really problematic...

Personally, I'm not a fan of option 2, just listed it as a possible option to consider.

**Comment by bradcray** [comment]
On the new option 5:

> Provide some mechanism for saying what blank intent should mean for a record. Users can select between "ref-if-modified" and "const ref" for blank intent. The 'this' intent matches the blank intent.

I could also imagine someone wanting to select 'const in' as a third option.

w.r.t. this con:

> Con: records that opt-in to "ref-if-modified" may feel surprising to C programmers

While I've argued along these lines in some cases before, I wouldn't hold this argument against this proposal because I think record authors who are opting into this feature are no longer creating "plain old structs" but rather special types that are probably intended to be more like black boxes to the end-user and just happen to use records as their implementation mechanism (as we do for arrays, syncs/singles, etc.).

**Comment by bradcray** [comment]
Noting that the current sync var implementation uses a "default intent is ref" pragma, which I believe was one of the small number of things that made it "not a typical record."  I.e., if this were promoted to a language concept as in option 5, it would no longer be an outlier.

**Comment by mppf** [comment]
I have two notes to add:

1) The spec is fairly clear that the default intent for `this` matches blank intent. I think that should be what the implementation does as well - and we'll have that with Options 1, 4, or 5.

2) Brad and I were discussing how you'd indicate a type opt-in to ref-if-modified under Option 5. I think a generalized attribute syntax, for advanced & little-used language features, would be useful there.

    We identified the following possible uses for such an attribute syntax:
    * indicate a type is ref-if-modified
    * indicate a loop is SIMD
    * indicate a loop should be unrolled
    * allow lhs = rhs for a particular type to turn into destroy(lhs); lhs = initCopy(rhs); (see CHIP 16)

    As a straw-man proposal, for this exact case it could be
    ```
    @ref-if-modified
    record R { }
    ```

**Comment by bradcray** [comment]
Of the five options, I currently like 1, 3, and 5 the best, with 1 being my least favorite of the three and 3 perhaps becoming my most favorite of the three (or maybe an option 6 that's a hybrid of options 3+5... see below).

For me, the relative merits of 5 vs. 3 come down to "need for new syntax / language concepts" (in 5) vs. "not" (in 3).

Though option 3's introduction of asymmetry between the default 'this' intent and argument intent for a type seems a little funny, I don't find it inherently off-putting nor particularly surprising in the examples I've thought through, and I think it can be rationalized by virtue of 'this' being a fairly special argument.  I don't think citing the spec is the right argument against it in any event -- the spec can be updated.  Maybe there are examples that would illustrate problems with it that I haven't seen or thought of yet, but without such examples it doesn't strike me as unpalatable or untenable.

I think a major downside to 1 in addition to likely requiring extra typing in a common cases for users is that I suspect we'd have to make a lot of updates to tests and module code to get it to conform.  Belatedly, it's occurring to me that this would be a downside of 5 as well (right?) which is part of why it's dropped in favor for me over the course of the day.

This makes me wonder if there's a hybrid between option 3 and 5 in which the default for records would be 3 and one could opt into a "ref-arg-if-modified" mode.

**Comment by vasslitvinov** [comment]
It bothers me a bit that the default intent for a record is different for 'this' vs. other arguments. We do not make that difference for arrays, right? OTOH while it is unfortunate, there are advantages of taking this route, of which I see backward compatibility is the key.

**Comment by mppf** [comment]
As of today, the plan is option 3. We will consider configuring default intent for records another time.
