### ISSUE TITLE
Upgrade GMP versions

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#5270]
We're currently a couple of releases behind. The latest version is 6.1.2 and we're on 6.0.0

We should upgrade and switch to the new third-party directory structure like we've done for qthreads(#4498), hwloc(#3453), jemalloc(#3424), and gasnet(#3914).

We should also track when new GMP releases come out and upgrade as appropriate. GMP isn't released nearly as often as hwloc/jemalloc/gasnet, so it shouldn't be too much work.

**Comment by ronawho** [comment]
Pinging @chapel-lang/perf-team because upgrading could result in some performance benefits for the shootouts on newer architectures.

Currently I own qthreads/hwloc/jemalloc upgrades and Greg does gasnet upgrades. I wouldn't be opposed to taking on GMP upgrades too, but wanted to check if anybody else was interested first.

**Comment by ronawho** [comment]
I'll upgrade to 6.1.2 soon. 

Some other things to look at: 
 - use `--enable-fat` to get a fat binary on x86 architectures. "Using --enable-fat selects a “fat binary” build on x86, where optimized low level subroutines are chosen at runtime according to the CPU detected. This means more code, but gives good performance on all x86 chips"
 - consider running the "tuning" script -- https://gmplib.org/manual/Performance-optimization.html#Performance-optimization
 - consider adding support for mini-gmp? (It's just a .c and .h file that offer some (slow) gmp functionality w/o a configure/install step) https://gmplib.org/repo/gmp/file/tip/mini-gmp/README

**Comment by ben-albrecht** [comment]
> We should also track when new GMP releases come out and upgrade as appropriate. GMP isn't released nearly as often as hwloc/jemalloc/gasnet, so it shouldn't be too much work.

👍 

Quick question: What's our claim w.r.t.`CHPL_GMP=system` support? Should it work with any version or only 6+? Should this be documented in the [GMP module docs](http://chapel.cray.com/docs/master/modules/standard/GMP.html#using-the-gmp-module) or [CHPL_GMP docs](http://chapel.cray.com/docs/master/usingchapel/chplenv.html#chpl-gmp) ?

**Comment by ronawho** [comment]
GMP goes to great lengths to maintain compatibility. We should work with 3.X or newer: https://gmplib.org/manual/Compatibility-with-older-versions.html#Compatibility-with-older-versions
