### ISSUE TITLE
Upgrade re2 versions, try to contribute patches upstream

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#5271]
Our "version" of re2 is about 3 years old. I don't track re2 development myself, so I'm not sure what all has gone in since then, but it seems likely that it's worth upgrading. If/when we do upgrade, we should also switch over to the new third-party directory structure like we've done for qthreads(#4498), hwloc(#3453), jemalloc(#3424), and gasnet(#3914).

It also think we should try to use pkg-config to determine the link args instead of always throwing `-lpthread`

Like our other third-party libraries (qthreads/hwloc/jemalloc/gasnet) it might be worth finding an owner for upgrading versions.

We also have patches we apply to re2 to "allow regular expressions in the format
string for Chapel's readf() for searching on QIO channels." It'd be nice if we could contribute that upstream and use a clean/non-patched version of re2, especially if we start upgrading regularly. 

 - [X] switch re2 dir structure over to re2-src
 - [X] find an owner to update re2 (@mppf)
 - [X] document how to upgrade version (how to upgrade and apply our patches)
 - [X] try to contribute our re2 patches upstream? (tried unsuccessful, see https://github.com/chapel-lang/chapel/issues/5271#issuecomment-320268636)
 - [X] use pkg-config to determine the link args instead of always throwing `-lpthread`? (punting based on https://github.com/chapel-lang/chapel/issues/5271#issuecomment-321720595)

**Comment by ronawho** [comment]
@mppf I assigned to you since you added the original support for re2, but I don't think you necessarily have to own this. I wouldn't mind adding this to the list of 3rd party libs I upgrade, although I don't know anything about the patches we apply, so I wouldn't feel comfortable trying to contribute those upstream.

**Comment by ronawho** [comment]
#6024 upgraded to the latest re2 version, switched dir structure over to re2-src, and added upgrading documentation 

Thanks @mppf!

**Comment by ronawho** [comment]
@mppf completely naive (probably stupid) question: do we _need_ to patch re2? Could we accomplish the same thing at a higher level? I'm assuming we could, but that it would come at a significant performance penalty. Is that accurate, or does it have to be done in re2?

Anyways, not super important. It'd be nice if we could contribute things upstream. Not a big deal if we can't. It'd be a nice fallback to implementing what the patches achieve at a higher level, but also not a big deal if we can't. re2 isn't making very many dramatic changes anymore, so I don't think it'll be hard to maintain our patches going forward.

**Comment by mppf** [comment]
To answer your question on the issue about whether or not patches against RE2 are really necessary... 

These RE2 patches originated when I was building the formatted I/O system. Where scanf includes %[ to match against a string containing only particular characters, the Chapel formatted I/O system generalizes that to %/ which works with a regular expression instead of a simple set of characters.

I can see 3 ways to get the I/O functionality we want with RE2.

1) What we have now (we patch RE2 to support a 'FilePiece' using call-backs to get characters)
2) RE2 could support executing an NFA/DFA against a buffer and saving the NFA/DFA state, to enable continued search when another buffer is provided.
3) RE2 could make more of its internal headers part of its public API, so that we could have our own NFA execution implementation that shared RE2's parser and internal regexp representation. We could do this while using private RE2 headers now instead of having a patch, if we want.

And there is this non-option:

4) We could copy the data to a string and search that with RE2, but in some use cases (such as "find the next occurrence of this pattern in the channel"), we'd be repeatedly reading and copying and searching (i.e. it would be O(n^2)). So I don't consider that an option.

**Comment by mppf** [comment]
There are regular expression libraries that we might consider switching to that offer an API that we would not need to modify as far as I can tell.
 * https://01.org/hyperscan -- see http://01org.github.io/hyperscan/dev-reference/api_files.html#c.hs_scan_stream  (requires C++11, depends on Boost, Ragel; BSD)
 * TRE -- see https://laurikari.net/tre/documentation/reguexec/ (C, BSD)
 * http://www.pcre.org/ -- see http://pcre.org/original/doc/html/pcrepartial.html (C, BSD)
 
We could even consider using a different regexp library to implement the scanning on files. Of course, then we have to worry about to what extent the syntaxes are compatible.

Here is a page comparing the performance of TRE, PCRE, and RE2:
 * http://sljit.sourceforge.net/regex_perf.html

Other regexp libraries I don't think would help us:
 * lightgrep http://strozfriedberg.github.io/liblightgrep/ - lg_search can search a buffer (requires C++11, depends on Boost and ICU; GPL) - GPL isn't compatible with our Apache license
  * oniguruma https://github.com/kkos/oniguruma C, BSD but looks like it is unlikely to support streaming/resuming.

**Comment by ronawho** [comment]
The re2 maintainers opted not to take our patches (re2 is mostly in maintenance mode and the features we're adding don't align with their goals.) See https://groups.google.com/d/msg/re2-dev/gyZ6ukLJm30/25AaeH2BDgAJ for more info.

**Comment by ronawho** [comment]
For using pkg-config to figure out the link args: our custom `install-static` target doesn't install the .pc file, so we'd have to do that. 

Also @mppf is the install-static mod really needed? Can't we just use the regular install target and just explicitly link against the static lib? (-llibre2.a instead of -lre2)?

**Comment by mppf** [comment]
@ronawho - I don't think I tried that - you are welcome to give it a shot. I remember encountering some odd build problems on Mac OS X though so make sure to try it there.

**Comment by ronawho** [comment]
I tried using pkg-config with https://github.com/chapel-lang/chapel/pull/6989. That ultimately switched out `-lpthread` for `-pthread`, which unfortunately causes clang to bark with `clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]` (like what we saw in https://github.com/chapel-lang/chapel/pull/6919 as well.)

This seems like more trouble than it's worth, and re2's link args are unlikely to change, so I think we should punt on this.
