### ISSUE TITLE
What should enum comparisons do?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#5282]
While looking through the param folding code for enums, @ronawho  and I found that enum equality was implemented by comparing the enums' integer values.  That is, given enums:

    enum color { red, green, blue };
    enum day { sunday, monday, tuesday };

the param comparison:

    if (color.green == day.monday) then ...

folds to true because green and monday both have the same integer value.  This struck me as surprising because many of our param enum cases are designed to see if the enum is the same symbol.  For example, when checking to see whether an iterator has the 'standalone' tag, it isn't our intention to see if the argument is some other enum or integer whose value happens to equal 'standalone'.  On the other hand, if you view enums less as "new values" and more as "convenient aliases for integer values" maybe the current behavior is less surprising.

I was thinking this was specific to params, but in digging a bit deeper, it turned out that this is what happens for execution-time enum comparisons as well, apparently based on the fact that both enums coerce to integers and then match the integer comparison operators.

To that end, the questions I'm interested in addressing in this issue are:

1) Do we want to support inter-enum comparisons, or should we only support such comparisons within:
    a) a given enum type
    b) enum/integral pairs
    c) never (a user would have to cast the enums to ints in order to do any comparisons on them.

2) Is the above decision only for == and != or for <, <=, >, >= as well?

**Comment by bradcray** [comment]
PR #5276 contains my start at trying to improve the param enum case for == and !=, but I closed it in favor of this issue upon realizing that the behavior is not specific to params.

**Comment by lydia-duncan** [comment]
I don't think we should support any comparison between two different enum types.

I am inclined to support a) and b) but perhaps as a more modern language, we shouldn't encourage that behavior?

**Comment by bradcray** [comment]
The current thinking based on user feedback and reflection is to stop permitting enums to coerce to ints which will stop these cross-enum comparisons from occurring.  At present the thought is that only == and != would be supported by default within an enum.   I think it remains a reasonable question whether we should support inequalities as well, but at present the plan is not to.

PR #9192 implements this.
