### ISSUE TITLE
Bug: Recursive iterator inlining

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#5311]
### Summary of Problem
I have so far been unable to create a small reproducer program of this issue, but can outline how to expose the bug by making a small change to DefaultOpaque.

In the destructor for DefaultOpaqueDom, iterate over ``adomain`` and print out indices (the work done inside the loop does not matter). Then compile and run the following test:
arrays/opaque/bradc/opaqueIterate.chpl

You will see the following error message at execution-time:
``compiler generated error``

#### More Detail

The bug can be avoided by compiling with the flag ``--no-inline-iterators``. If support for inlining recursive iterators is disabled, 11 tests in the entire suite fail.

The problem appears to be that we create a loop-body-function that still contains a PRIM_YIELD. The PRIM_YIELD is left in the tree, and at the end of ``lowerIterators`` is replaced with PRIM_INT_ERROR.

The compiler thinks that the "these" iterator(s) in DefaultAssociativeDom are recursive because of a potential loop like this:
1. DefaultAssociativeDom.these creates a DefaultRectangular temporary
2. When done, calls _delete_dom on the temporary DR domain
3. DR is passed to _delete_dom as a BaseDom
4. ``delete`` the BaseDom
5. virtual method dispatch sees ~DefaultOpaqueDom as a possibility
6. ~DefaultOpaqueDom calls DefaultAssociativeDom.these
7. back to where we started

#### Possible workaround
Some initial testing indicates that we may be able to work around this issue by:
1. having ``_delete_dom`` accept a generic argument
2. not implementing dsiDestroyDom as a virtual method

This is unsatisfactory, and doesn't actually fix the bug. I will continue to try and create a small reproducer program.

#### Configuration / Compilation 
This bug appears to exist in any configuration that compiles with the flag ``--inline-iterators``, which is on by default.

**Comment by benharsh** [comment]
@ronawho : Here's the issue for the bug we discussed. For now I plan to work around the issue by making a module-level change in the array-views dev branch.

**Comment by ronawho** [comment]
To see the history of this work -- a25c2fb2 originally added support for recursive leader iterators

**Comment by ronawho** [comment]
Here's the test that fail with [recursive iterator inlining removed](https://github.com/chapel-lang/chapel/compare/master...ronawho:no-inline-recursive-iters)


```
[Error matching compiler output for chplvis/tree]
[Error matching compiler output for functions/deitz/iterators/leader_follower/test_recursive_leader]
[Error matching compiler output for functions/deitz/iterators/leader_follower/test_recursive_leader1]
[Error matching compiler output for functions/deitz/iterators/leader_follower/test_recursive_leader2]
[Error matching compiler output for functions/deitz/iterators/leader_follower/test_recursive_leader3]
[Error matching compiler output for functions/deitz/iterators/leader_follower/test_recursive_leader4]
[Error matching compiler output for modules/standard/FileSystem/bharshbarg/filer]
[Error matching compiler output for modules/standard/FileSystem/filerator/bradc/findfiles-par]
[Error matching compiler output for modules/standard/FileSystem/filerator/bradc/walk-par]
[Error matching compiler output for multilocale/vass/recursive-iterator-twice-multiloc]
```

None of them fail if --no-inline-iterators is thrown, so I think we're still inlining part of the recursive loop, and we should still be able to remove recursive iterator inlining once we flag those cases and prevent them from being inlined too

**Comment by ronawho** [comment]
Some old notes from Steve: 

```
Implemented recursive leader iterators to support tree-based spawning
across locales rather than doing it serially.  Yet, even on 2048 nodes
we never saw an improvement due to this optimization, so most of our 
leader iterators still use serialized coforalls.
- it's implemented but not optimized
- the tricky part was that because of the 'on' we have to pass a
  bundle of arguments off to the iterator class on the remote locales
```

To me this indicates that recursive iterator inlining was only added as an optimization, and we should be able to remove it.

I do think it's an interesting use-case though, and long term we probably do need to do something smart to support tree/cube based spawning, but for the time being the code we have is too fragile.

**Comment by benharsh** [comment]
@vasslitvinov appears to have fixed this issue in #5556. Thanks!

**Comment by ben-albrecht** [comment]
I noticed a couple of references to this issue in TODOs within [`ChapelDistribution`](https://github.com/chapel-lang/chapel/blob/master/modules/internal/ChapelDistribution.chpl#L919).

Maybe these work-arounds are no longer needed?

**Comment by vasslitvinov** [comment]
@ben-albrecht would you like to try removing them and seeing what happens?

**Comment by ben-albrecht** [comment]
I am not exactly sure what the non-work-around code should look like. Would it just be the removal of the `Reflection` calls?

I don't think this is urgent - just wanted make sure we didn't lose track of the TODOs
