### ISSUE TITLE
Document CHPL_RT_UNWIND

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#5320]
Apparently, Chapel supports a CHPL_RT_UNWIND environment variable that, if set to 0/false/no, squashes the output that would normally be generated on halt()s when CHPL_UNWIND is set to something other than "none."  This variable is pretty hidden, though -- you'd never guess it exists by grepping the documentation or code for its name.  Seems like we should document this, maybe in:  http://chapel.cray.com/docs/master/usingchapel/chplenv.html#readme-chplenv-chpl-unwind

**Comment by tushargoyl123** [comment]
hi I am tushar and i want to work on this issue Can u guide me through

**Comment by KishkinJ10** [comment]
I am a beginner can i work on this??

**Comment by bradcray** [comment]
Hi @KishkinJ10 — Sorry for the delayed response, it's a busy few weeks.  You're definitely welcome to work on this.  The approach I would take would be to:

Get familiar with CHPL_UNWIND and CHPL_RT_UNWIND:
* try creating a Chapel build with CHPL_UNWIND set to [one of its legal values ](https://chapel-lang.org/docs/usingchapel/chplenv.html#readme-chplenv-chpl-unwind).
* write, compile, and run a Chapel program that generates an error and generates a stack track when run, for example:
```
var A: [1..3] real;
A[5] = 1.0;
```
* experiment with CHPL_RT_UNWIND to understand how it squashes these stack traces (where my OP above gives my impression from a few years ago)

Document the variable:
* edit the CHPL_UNWIND section in `doc/rst/usingchapel/chplenv.rst`, which forms the sources to the webpage listed in the OP, writing a description of the variable
* do `make docs` from `$CHPL_HOME`
* open `docs/html/usingchapel/chplenv.html` in a web browser to see if it turned out as you'd expect.

**Comment by aconsroe-hpe** [comment]
Added docs in #18590
