### ISSUE TITLE
Consider removing the inlineSingleYieldIterator() optimization and supporting code

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#5357]
`inlineSingleYieldIterator()` was originally added af0e77e1, a commit that added initial/prototype GPU support. 

Most of that code was later removed in 60c2580, though inlineSingleYieldIterator remained. I'd like to remove this code because I don't believe it's well understood by anybody currently on the team, and it doesn't seem like it has much value. I'd imagine it could have been useful for the initial GPU work, but I don't think it provides much functionality today.

As far as I can tell, the only thing it does is inline zippered iterators that yield a single value. It does not inline iterators that have loops, or ones that have more than one yield, so in effect it only inlines iterators that yield one, and only one value, and I don't think there's any compelling cases where we do that. i.e. it allows:

```chapel
iter myIter() { yield 1; }
for (i, j) in zip(myIter(), myIter()) do writeln(i, " ",  j);
```

to be generated as

```c
writeln_chpl2(INT64(1), INT64(1));
```

and without this optimization we generate some ugly code: 

```c
  _ic__chpl = chpl_here_alloc(sizeof(chpl__ic_myIter_chpl_object), INT16(31));
  (_ic__chpl)->more_chpl = INT64(1);
  _ic__chpl2 = chpl_here_alloc(sizeof(chpl__ic_myIter_chpl_object), INT16(31));
  (_ic__chpl2)->more_chpl = INT64(1);
  advance_chpl(_ic__chpl);
  advance_chpl(_ic__chpl2);
  for (; (tmp_chpl = (_ic__chpl)->more_chpl,tmp_chpl); ) {
    writeln_chpl2((_ic__chpl)->value_chpl, (_ic__chpl2)->value_chpl);
    advance_chpl(_ic__chpl);
    advance_chpl(_ic__chpl2);
  }
  chpl_here_free(_ic__chpl);
  chpl_here_free(_ic__chpl2);
```

While the optimization clearly allows that code to be generated much more elegantly/cheaply, this code pattern (zippered iterating over a single yield) is almost never used. There are only 3 tests that run into it: functions/iterators/bradc/zipIteratorsRef.chpl, statements/vass/index-variable-accesses.chpl, and studies/glob/test_glob.chpl. 

The only potentially interesting case that comes to mind is that it allows zippered followers that only yield a single value to be optimized, and that seems like a far more interesting case than zippered serial iterators, but I'm not sure it's worth keeping the extra code around for.

**Comment by ronawho** [comment]
@vasslitvinov and @daviditen I'm curious if either of you are more familiar with `inlineSingleYieldIterator` and if you see any value in keeping it.

**Comment by ronawho** [comment]
And for context I'm working on https://github.com/chapel-lang/chapel/issues/5311, and I ran into this code again while trying to wrap my head around some other iterator code. IMO `inlineSingleYieldIterator` adds unnecessary code complexity/logic to lowerIterators, which is already complicated enough without adding any real value.

**Comment by daviditen** [comment]
I'd be OK with removing it.

**Comment by vasslitvinov** [comment]
I am OK either way.

**Comment by ronawho** [comment]
Just FYI, here are the tests that currently trigger this optimizations:

```
functions/iterators/bradc/zipIteratorsRef
statements/vass/index-variable-accesses
studies/glob/test_glob
```

none of them are compelling reasons to keep the optimization.


In a meeting, perf-team has also ok'd getting rid of this optimization. I'll probably open a PR to do so in the next few days.
