### ISSUE TITLE
Communication overhead when declaring arrays over remote const domains

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#5378]
The ISx benchmark spawns a task per core per locale and declares arrays over a global const domain. Our current ``BaseDom`` implementation uses an on-statement to add a ``BaseArr`` to the domain's list of arrays, which can be expensive as the program scales.

### Solutions?

My understanding of the ``_arrs`` list is that it is used to update arrays if the domain is resized and to determine when the domain should be destroyed. Since this is a global const domain:
- I don't think we need to have the resizing support
- as far as I know, an array cannot outlive its domain if that domain is global

If that's true, we may be able to simply RVF the domain and perhaps (will the help of a compiler param) avoid the on-statement in the ``BaseDom`` implementation.

### Futures
domains/bharshbarg/remote-dom-comms.chpl

**Comment by vasslitvinov** [comment]
A separate scenario where multiple locales access the same domain while accessing their respective arrays is here: #6381

**Comment by benharsh** [comment]
A possible solution to this problem is described in #6995

**Comment by benharsh** [comment]
@bradcray (or anyone else): Do you think this issue can be closed now?

**Comment by bradcray** [comment]
Seems like it but I think you'd know best.  :)

**Comment by benharsh** [comment]
#7050 implemented serialization for records across locales.

Further discussion can be found in #7115
