### ISSUE TITLE
count() on arrays is serial

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#5402]
Browsing the sources today, I was noting that the count() method on arrays is serial, which seems surprising for a parallel language (and will likely die, performance-wise, on a distributed array).  While we might ultimately want some clever heuristics to decide how much parallelism to use in various cases, it seems like we should use parallelism (a reduction) by default, as a parallel language.

**Comment by sagar-sam** [comment]
I would like to work on the issue if the issue is still open. I build the code and get familiarize myself with the chapel, I am new to chapel, please guide me solving the issue.
Thank you

**Comment by bradcray** [comment]
Hi sagar-sam -- It is still open.  I'd suggest reading about Chapel's data parallel features (http://chapel.cray.com/docs/master/users-guide/index.html#data-parallelism) and looking at the definition of 'proc count()' in $CHPL_HOME/modules/internal/ChapelArray.chpl as starting points.

**Comment by sagar-sam** [comment]
Hello @bradcray 
I converted total variable of type sync and used a forall loop instead of a for loop.
Is it beneficial??

**Comment by bradcray** [comment]
Hi @sagar-sam --

Yes, you should definitely create a pull request to start discussing the code itself.  And you'll need to sign a contributor's agreement in order to have the PR be merged.  Using a sync var and forall is a legal way to solve this problem, but probably not the most efficient, since it will require every iteration to access the same variable which could cause a bottleneck when the array is distributed across a large number of locales.  To avoid this, you'd want to use Chapel's 'reduce' expression or a 'reduce' task intent on the forall loop.

Unfortunately, I'm seeing from @lydia-duncan's tag above that someone else has submitted a PR with a reduce-related solution...  But I think it'd still be worth comparing the performance of the two approaches as part of your continuing introduction to the language...

**Comment by sagar-sam** [comment]
Thanks @bradcray
