### ISSUE TITLE
Scoping for enums

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#5414]
### Summary of Problem

Declaring and using enums inside of functions that take compile-time arguments such as params or types results in compilation error due to the enum type being unknown.

### Steps to Reproduce

**Source Code:**

`param` case:

```chapel
enumScopeTest(2);

proc enumScopeTest(param x) {
  enum Numbers {one, two, three};
  writeln(Numbers.one); // error: use of 'one' before encountering its definition, type unknown
}
```

`type` case:

```chapel
enumScopeTest(int);

proc enumScopeTest(type t) {
  enum Numbers {one, two, three};
  writeln(Numbers.one); // error: use of 'one' before encountering its definition, type unknown
}
```

working case:

```chapel
enumScopeTest(2);

proc enumScopeTest(x) {
  enum Numbers {one, two, three};
  writeln(Numbers.one); // prints '1'
}
```

**Associated Future Test(s):**

[`test/types/enum/scope.chpl`](https://github.com/chapel-lang/chapel/tree/master/test/types/enum/scope.chpl) #6207

[`test/types/enum/scope-type.chpl`](https://github.com/chapel-lang/chapel/tree/master/test/types/enum/scope-type.chpl)

### Configuration Information

- Output of `chpl --version`: `chpl Version 1.14.0.8dc84bd` (master)

**Comment by lydia-duncan** [comment]
I'd be tempted to grab this one next, assuming you aren't already looking at it

**Comment by ben-albrecht** [comment]
It's all yours!

**Comment by lydia-duncan** [comment]
As an update, I'm not seeing the "working" case work, but if I make the argument concrete it does:

```chapel
enumScopeTest(2);

proc enumScopeTest(x: int) { // Making this concrete enables the program to work
  enum Numbers {one, two, three};
  writeln(Numbers.one);
}
```

It may have broken since this issue was filed
