### ISSUE TITLE
Casting enums with explicit types and offsets

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#5416]
### Summary of Problem

Enums with explicit element types and an offset (not starting at 1) do not account for the offset during a value -> enum cast.

Furthermore, the error message for many of these compilation errors points to the enum declaration rather than the enum cast line, which is not entirely helpful.

This issue exposes a bug in the "working" case from #5412.

### Steps to Reproduce

**Source Code:**

```chapel
type t = int;
enum Numbers {two=2: t};

// Fails to compile
//  line 2: error: halt reached - enumerated type out of bounds
var x = 2: t;
var y = x:Numbers;
writeln(y);
```

```chapel
type t = int;
enum Numbers {two=2: t};

// Fails to compile
//  line 2: error: halt reached - enumerated type out of bounds
var x = 2;
var y = x:Numbers;
writeln(y);
```
```chapel
type t = int;
enum Numbers {two=2: t};

// Fails to compile, but at least we get the right line number!
// line 6: error: enum cast out of bounds
var y = 2:Numbers;
writeln(y);
```

```chapel
type t = int;
enum Numbers {two=2: t};

// Works as expected
//  prints '2'
var y = Numbers.two:t;
writeln(y);
```

```chapel
type t = int;
enum Numbers {two=2: t};

// Expected to fail with enum cast out of bounds error, but compiles
//  prints nothing
var x = 1: t;
var y = x:Numbers;
writeln(y);
```

**Associated Future Test(s):**

[`test/types/enum/typed-offset.chpl`](https://github.com/chapel-lang/chapel/tree/master/test/types/enum/typed-offset.chpl) #6207

### Configuration Information

- Output of `chpl --version`: `chpl Version 1.14.0.8dc84bd` (master)

**Comment by bradcray** [comment]
This issue was closed by PR #8563
