### ISSUE TITLE
Bug: Compile-time failure with reduction over iterator with multiple yields

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#5428]
### Summary of Problem
I was writing a standalone iterator that itself iterated over another standalone iterator. My iterator had two yields in it. When I performed a reduction over this iterator, I encountered a compile-time assertion failure. The comments in the ``propagateThroughYield`` function in the ``implementForallIntents.cpp`` file suggest that multiple yields are not yet handled all that well.

### Steps to Reproduce

**Associated Future Test(s):**
See the .future added in #5426 

### Configuration Information
Breaks on any configuration.

**Comment by cassella** [comment]
The future added for this issue in that PR, `test/functions/iterators/bharshbarg/multipleYieldStandalone.future`, was retired by #12131 commit 3971a3bb
