### ISSUE TITLE
Consider removing copy propagation

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#5440]
Copy propagation has been a pretty frequent source of bugs:
 - https://github.com/chapel-lang/chapel/commit/26df870e4382c478c3c1de13c74b9b9bcd17d03c
 - https://github.com/chapel-lang/chapel/commit/6e620fd72d319f1fb4bd018b8f2b6da135c18c1f
 - https://github.com/chapel-lang/chapel/commit/1430bb86cfbe78662fac8cde52014c3fcfff4bba
 - https://github.com/chapel-lang/chapel/commit/b7c49638ff9b9fd7a39c69d88f13ba3fe622caeb
 - https://github.com/chapel-lang/chapel/commit/ec113373d8fc079faebed5b1bc5ee87bbfd4bf37
 - https://github.com/chapel-lang/chapel/commit/a07bcf1eec61181b1381512a77636407482a5263
 - https://github.com/chapel-lang/chapel/commit/9f11885f5fee10c1c7c8244a40f1b4ec2600ee41

Because of all the recent issues, several of us have been wondering if it's worth keeping copy propagation around. However, we were concerned that removing it could have a negative impact on execution performance, compiler performance, and readability of the generated code.

I ran some experiments and here's what I found: 

There's not a huge slowdown for compiler performance. Things are definitely slower, but only by about 3% for the "average" program, and 10% for examples programs. There might be a few performance regressions for array vector ops, lcals, and string temp copies but it could also just be machine noise.  I didn't see any comm count differences for multilocale. I think the biggest downside is how much harder the generated code is to read.

Compiler performance: 
 -  [chap01(default)](http://chapel.sourceforge.net/perf/chap01/?startdate=2016/12/13&enddate=2017/02/26&graphs=topaveragetotalcompilationtime,timespentcompilingvstesting)
  - [chap12(--fast)](http://chapel.sourceforge.net/perf/chap12/?startdate=2016/12/13&enddate=2017/02/26&graphs=topaveragetotalcompilationtime,timespentcompilingvstesting)

Execution performance: 
 - possible minor regressions for [array-vector-ops, lcals, and string-temp-copies](http://chapel.sourceforge.net/perf/chapcs/noCopyProp/?graphs=arrayvectoroperations,minimdljsize10time,compilationtime,jacobiemittedcodesize,stringtemporarycopies)

I think the biggest downside is the impact of generated code readability

For a simple serial stream-like code

```chapel
var A, B, C: [1..10] real;
for (a, b, c) in zip(A, B, C) do a = b + c;
```

with copy-prop
```c
for (_ic__F5_i_chpl = call_tmp_chpl6,_ic__F5_i_chpl2 = call_tmp_chpl10,_ic__F5_i_chpl3 = call_tmp_chpl13; (tmp_chpl13 = (_ic__F5_i_chpl <= _ic__F1_high_chpl),tmp_chpl13); tmp_chpl14 = _ic__F5_i_chpl,tmp_chpl14 += _ic__F2_stride_chpl,_ic__F5_i_chpl = tmp_chpl14,tmp_chpl15 = _ic__F5_i_chpl2,tmp_chpl15 += _ic__F2_stride_chpl2,_ic__F5_i_chpl2 = tmp_chpl15,tmp_chpl16 = _ic__F5_i_chpl3,tmp_chpl16 += _ic__F2_stride_chpl3,_ic__F5_i_chpl3 = tmp_chpl16) {
  call_tmp_chpl16 = (coerce_tmp_chpl + _ic__F5_i_chpl3);
  call_tmp_chpl17 = (coerce_tmp_chpl2 + _ic__F5_i_chpl2);
  call_tmp_chpl18 = (coerce_tmp_chpl3 + _ic__F5_i_chpl);
  *(call_tmp_chpl18) = (*(call_tmp_chpl17) + *(call_tmp_chpl16));
}
```

without copy-prop:
```c
for (_ic__F6_low_chpl = _ic__F0_low_chpl,_ic__F5_i_chpl = _ic__F6_low_chpl,_ic__F6_low_chpl2 = _ic__F0_low_chpl2,_ic__F5_i_chpl2 = _ic__F6_low_chpl2,_ic__F6_low_chpl3 = _ic__F0_low_chpl3,_ic__F5_i_chpl3 = _ic__F6_low_chpl3; (tmp_chpl16 = (_ic__F5_i_chpl <= high_chpl),tmp_chpl16); tmp_chpl17 = _ic__F5_i_chpl,tmp_chpl17 += stride_chpl,_ic__F5_i_chpl = tmp_chpl17,tmp_chpl18 = _ic__F5_i_chpl2,tmp_chpl18 += stride_chpl2,_ic__F5_i_chpl2 = tmp_chpl18,tmp_chpl19 = _ic__F5_i_chpl3,tmp_chpl19 += stride_chpl3,_ic__F5_i_chpl3 = tmp_chpl19) {
  tmp_chpl10 = _ic__F5_i_chpl3;
  call_tmp_chpl16 = (coerce_tmp_chpl + tmp_chpl10);
  tmp_chpl12 = _ic__F5_i_chpl2;
  call_tmp_chpl17 = (coerce_tmp_chpl2 + tmp_chpl12);
  tmp_chpl14 = _ic__F5_i_chpl;
  call_tmp_chpl18 = (coerce_tmp_chpl3 + tmp_chpl14);
  call_tmp_chpl19 = (*(call_tmp_chpl17) + *(call_tmp_chpl16));
  *(call_tmp_chpl18) = call_tmp_chpl19;
}
```

**Comment by ronawho** [comment]
@mppf and @benharsh based on these results I'm pretty neutral about removing copy prop. What do you think?

**Comment by ronawho** [comment]
Oh and FWIW I tried reviving the old copy propagation implementation. I was able to get it to build without too much work, but there were ~20 failures on master. I have no idea how much work it would take to fix those or if using the old implementation would be "better", but figured I share the info anyways.

**Comment by bradcray** [comment]
I'm surprised that denormalization isn't doing a better job with the generated code in your simple example.  Is it clear to anyone why it isn't / (or inherently couldn't)?

I was mostly joking about dredging the old copy prop implementation back up, but 20 failures is surprisingly small.  How did the generated code look?  If similarly bad (and/or there was a way to get denormalization to cover over the differences with neither), seems like we might just want to forgo it.

**Comment by mppf** [comment]
@ronawho - re the generated code example, I'm not reproducing your result with --fast. I run the program you showed with `chpl --savec=tmp test.chpl --no-copy-propagation --fast` and the loop looks more like the 1st case than the 2nd. Without `--fast`, I see a lot of array bounds checks etc that aren't in your examples.

(In other words I'm not seeing that the generated code is so bad with --no-copy-propagation).

**Comment by mppf** [comment]
Either way, I'm for removing this copy propagation implementation. I think we can improve denormalize to cover any cases we want to simplify the C code for. I'd prefer to limit our "optimizations" that just clean up C code and I think denormalize can cover these cases.

**Comment by ronawho** [comment]
My generated code is with `chpl f.chpl --savec lookHere --fast` and I just have copyPropagation return since `--no-copy-propagation` actually turns off copy propagation and ref propagation 

With `--no-copy-propagation`  the generated code looks even worse for me: 

```c
  for (_ic__F6_low_chpl = _ic__F0_low_chpl,tmp_chpl31 = _ic__F6_low_chpl,_ic__F5_i_chpl = tmp_chpl31,tmp_chpl33 = _ic__F0_low_chpl2,tmp_chpl32 = tmp_chpl33,_ic__F5_i_chpl2 = tmp_chpl32,_ic__F6_low_chpl2 = _ic__F0_low_chpl3,tmp_chpl34 = _ic__F6_low_chpl2,_ic__F5_i_chpl3 = tmp_chpl34; (tmp_chpl35 = (_ic__F5_i_chpl <= high_chpl),tmp_chpl35); tmp_chpl36 = _ic__F5_i_chpl,tmp_chpl36 += call_tmp_chpl58,_ic__F5_i_chpl = tmp_chpl36,tmp_chpl37 = _ic__F5_i_chpl2,tmp_chpl37 += call_tmp_chpl59,_ic__F5_i_chpl2 = tmp_chpl37,tmp_chpl38 = _ic__F5_i_chpl3,tmp_chpl38 += call_tmp_chpl60,_ic__F5_i_chpl3 = tmp_chpl38) {
    _yieldedIndex_chpl = _ic__F5_i_chpl3;
    i_chpl = _yieldedIndex_chpl;
    ret_chpl49 = (coerce_tmp_chpl + i_chpl);
    ret_chpl46 = ret_chpl49;
    tmp_chpl25 = ret_chpl46;
    _index_chpl = tmp_chpl25;
    i_chpl2 = _ic__F5_i_chpl2;
    ret_chpl53 = (coerce_tmp_chpl2 + i_chpl2);
    ret_chpl50 = ret_chpl53;
    tmp_chpl27 = ret_chpl50;
    tmp_chpl28 = tmp_chpl27;
    _yieldedIndex_chpl2 = _ic__F5_i_chpl;
    i_chpl3 = _yieldedIndex_chpl2;
    ret_chpl56 = (coerce_tmp_chpl3 + i_chpl3);
    ret_chpl54 = ret_chpl56;
    tmp_chpl30 = ret_chpl54;
    c_chpl = _index_chpl;
    b_chpl = tmp_chpl28;
    a_chpl = tmp_chpl30;
    ret_chpl57 = (*(b_chpl) + *(c_chpl));
    *(a_chpl) = ret_chpl57;
  }
```

your `--no-copy-propagation --fast` is effectively `--fast` you would need to do `--fast --no-copy-propagation` instead

**Comment by mppf** [comment]
Ah, thanks for pointing out the problem. Anyway, I think we could probably get denormalize to cover most of these cases.

**Comment by ronawho** [comment]
Ok. My personal preference would be to leave things as they are for this release, and to retire copyprop and improve denorm for next release. I could pretty easily be convinced otherwise though.

 And FWIW copy prop also made it so that other optimizations had less work to do, so it wasn't strictly an "improve generated code" optimization

**Comment by benharsh** [comment]
I agree with Elliot that we should wait until post-release for this kind of change.

**Comment by bradcray** [comment]
I'm also in favor of holding off and living with it more if we don't have anything currently breaking due to it.

OTOH, if we think there is fragility w.r.t. user, rather than developer code (i.e., how easily could a user write code that copy propagation would do something illegal with?), that might be a reason to get rid of it sooner.  I think we still have time to shake out any issues...

**Comment by mppf** [comment]
Some grepping revealed these 2 futures:
[test_nested_var_iterator3.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/deitz/nested/test_nested_var_iterator3.chpl)
[cp-problem1.chpl](https://github.com/chapel-lang/chapel/blob/master/test/optimizations/copyPropagation/cp-problem1.chpl)

I think both could be written by users. I think it wouldn't be that hard to imagine a user writing the 2nd one if they felt aware of const ref and ref intents.

**Comment by mppf** [comment]
I also backed away from fixing a longstanding bug in use/def analysis because I was unwilling to fix copy propagation. (The bug is it doesn't consider PRIM_SET_SVEC_MEMBER and PRIM_SET_MEMBER to be "defs" for the tuple/record in question).

**Comment by ronawho** [comment]
FWIW [expressions/ferguson/if-expr/ifi.chpl](https://github.com/chapel-lang/chapel/blob/master/test/expressions/ferguson/if-expr/ifi.chpl) also passes with copy propagation disabled.

I'm still leaning towards waiting until post-release since those are relatively long-standing bugs, but again I could be swayed if these futures convince Bharsh and/or Brad that we should move sooner

**Comment by bradcray** [comment]
Normally when we're shy about taking on a feature going into a release, it's for fear of adding potential problems to the user experience without having the time to shake them out properly.  In this case, that would seem not to be the case -- it seems likely we'd only make the user experience more stable.  And while the bugs are longstanding, that's not a particularly compelling reason to continue to live with them if we have a fix.

The generated code size growth is more likely to impact developers than users, and developers will work on master, so the release cycle isn't likely to impact them terribly (though if making developers' jobs harder between now and the release interfered with landing other priorities, that would be a good reason to wait.

For those reasons, the potential performance slips are the things which seem most concerning to me given all the work that's gone into improving performance for this release.

Do we think that denormalize improvements would help with both the generated code improvements and the performance differences?

**Comment by bradcray** [comment]
Garbage collecting email, I came back across this change that we discussed last release but shied away from due to the timing.  I'm wondering if we should resurrect it now that we've got a long lead time before 1.16?

**Comment by ronawho** [comment]
Not that it matters at this point anyways, but I ended up punting on making this change for last release because I was worried about it exposing bugs in later optimization passes. i.e. I was concerned that not running copy prop could expose a bug in LICM or something along that lines. 

Agreed that we should get back to this soon, while it's still early in the release cycle

**Comment by mppf** [comment]
I still think we should remove copy propagation, but I don't think I'm the right person to do it.

**Comment by ronawho** [comment]
>I still think we should remove copy propagation, but I don't think I'm the right person to do it.

Whoops sorry @mppf, I accidentally added you as an assignee. In my mind I still "own" removing copy-prop though some collective "we" will want to improve denormalize or something else to maintain the readability of the generated code
