### ISSUE TITLE
Add a multi-locale performance playground

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#5453]
Our single locale performance playgrounds are invaluable for determining the impact of long-lived branches or experimental changes before merging to master.

It'd be great to have a similiar playground for multi-locale. The current XC multi-locale framework makes this non-trivial, but I think it could be done.

Alternatively we could wait until we have multi-locale testing on our cluster, and just setup a playground there.

I think there'd still be value in an XC multi-locale playground but a cluster and/or XC multi-locale playground would be a great addition.

**Comment by mppf** [comment]
I think I'll need something like this in the near term, to make progress on --cache-remote.

**Comment by gbtitus** [comment]
👍

**Comment by gbtitus** [comment]
I would definitely find this handy from time to time, though I think I'd probably want multilocale XC (the harder case) nearly as often as I'd want multi-locale linux64.

**Comment by ronawho** [comment]
So the hard part about a 16-node-xc playground is that if we want to test compiler/runtime/module changes, we need to build a second cray-module. That's pretty involved, both in terms of time to build the module, and time to update our infrastructure to support a different module.

What might be easier to do in the short term is to make a script that will test a single config (e.g. gnu+ugni+qthreads) against two different branches and produce graphs comparing those branches. This would allow somewhat easy testing of master compared to changes and is a more automated version of what I end up doing (I run master vs. a branch and just look at the .dat file manually for differences.) We'll still need to be careful to use some of the internal scripts to get the right compiler/module versions and other things, but I think that's more doable.

**Comment by gbtitus** [comment]
Is there a strong technical reason why we can't build from one or two branches of source for XC-16 playground testing, or is it just that doing so would take too long?

**Comment by ronawho** [comment]
Nope, that's exactly what I'm talking about doing in https://github.com/chapel-lang/chapel/issues/5453#issuecomment-305272532 (`"might be easier to test a single config against to different branches..."`). 

Now that ugni is open-source is should be pretty easy to just build from source and not have to build a separate module for testing a single config. That said, there is still some non-trivial work to re-use some internal parts like build/compiler_versions.bash, build/perf-graphs/, and a few other things, but I think it's a lot easier than trying to hook into the existing cray perf testing.

**Comment by ronawho** [comment]
It's pretty rare that we use the single-locale perf playground anymore. We tend to either do spot checks pre-merge or merge and then triage afterwards. I think there could still be value in this at some point, but I don't find myself actively wanting it that often so am going to close for now.

**Comment by gbtitus** [comment]
🎉     😁 

(I still receive notifications on issues I've participated in, though it's becoming less frequent as they close.)

**Comment by ronawho** [comment]
Hi Greg. Miss you!
