### ISSUE TITLE
Reduce size of release tarball

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#5457]
Our release tarball is getting pretty big. It's been over 40MB for a while, but it's climbed to over 50MB with 1.14

```sh
cd /data/cf/chapel/chapel-tarballs/
find . | grep tar.gz |xargs du -hs

41M	./1.10.0/chapel-1.10.0.tar.gz
40M	./1.11.0/chapel-1.11.0.tar.gz
46M	./1.12.0/chapel-1.12.0.tar.gz
49M	./1.13.0/chapel-1.13.0.tar.gz
49M	./1.13.1/chapel-1.13.1.tar.gz
53M	./1.14.0/chapel-1.14.0.tar.gz
```

I'm not sure if there's an easy way to see what files take up the most space inside of the tarball, but for an unpacked 1.14 we have:

```sh
du -hs * |sort -hr |head

87M	third-party
17M	examples
14M	doc
4.5M	modules
4.5M	compiler
2.3M	runtime
740K	util
328K	tools
292K	CHANGES.md
180K	make
```

For third-party -- we have: 

```sh
du -hs third-party/* |sort -hr |head

23M	third-party/llvm
16M	third-party/hwloc
15M	third-party/gasnet
13M	third-party/massivethreads
7.7M	third-party/qthread
4.8M	third-party/fltk
2.8M	third-party/jemalloc
2.4M	third-party/re2
2.3M	third-party/gmp
1.1M	third-party/libunwind
```
There's not much we can do for llvm, except for having the Makefile download the llvm and clang tars instead of bundling them ourselves, but that's probably not a real option. hwloc is mostly tests and docs, and massivethreads is mostly docs so we could save some space there. gasnet has ~1MB of docs, but the rest is source and a surprisingly large 4MB configure script.

For examples: it's almost entirely lulesh files that take up the space, so it seems like it'd be really easy to get some space back by removing them:

```sh
find examples -type f| xargs du -hs |sort -hr |head

9.8M	examples/benchmarks/lulesh/lmeshes/sedov45cube.lmesh
1.4M	examples/benchmarks/lulesh/lmeshes/sedov45oct.lmesh
336K	examples/benchmarks/lulesh/lmeshes/sedov15cube.lmesh
252K	examples/benchmarks/shootout/fasta-knucleotide.small
152K	examples/programs/prodCons.good
136K	examples/benchmarks/lulesh/lulesh-sedov15cube.good
100K	examples/benchmarks/shootout/fasta-regexdna.small
 80K	examples/benchmarks/lulesh/lmeshes/sedov15oct.lmesh
 52K	examples/start_test
 52K	examples/benchmarks/lulesh/lulesh.chpl
```
For doc: A lot of the space is taken up by the spec and then the copy of the online docs:

```sh
find doc -type f| xargs du -hs |sort -hr |head

996K	doc/html/_downloads/chapelLanguageSpec.pdf
996K	doc/chapelLanguageSpec.pdf
532K	doc/html/modules/packages/LAPACK.html
368K	doc/html/genindex.html
284K	doc/html/_static/fonts/fontawesome-webfont.svg
280K	doc/html/_static/jquery-1.11.1.js
264K	doc/html/modules/standard/IO.html
264K	doc/html/_sources/modules/packages/LAPACK.txt
236K	doc/html/searchindex.js
168K	doc/html/_static/fonts/RobotoSlab-Regular.ttf
```

Where is seems like we have 2 copies of the spec, and possibly some intermediate files as well as the final generated html. For this I think we need to make sure we delete intermediate docs steps, but I also question the value of including all the docs in the release, especially as our online docs continue to get larger and larger.

**Comment by ben-albrecht** [comment]
For the spec copies: We could add a release-only step to the docs build to symlink the spec rather than keep 2 copies floating around. 

For providing the docs: I believe the argument for shipping the docs with the release has always been that we want users with limited internet connectivity to have full access to the documentation while offline.

**Comment by ronawho** [comment]
@ben-albrecht this was migrated from an old jira issues, so it's possible the docs stuff has changed pretty drastically as a result of the changes you've made during this release.

**Comment by ben-albrecht** [comment]
Following up on this -- After #5838 is merged, the release will still have 2 copies of the pdfs:

```
> cd doc && find . -name "*.pdf"
./html/_downloads/chapelLanguageSpec.pdf
./html/_downloads/quickReference.pdf
./rst/language/chapelLanguageSpec.pdf
./rst/language/quickReference.pdf
```

After #5838 is merged, I can add a post-processing step to `gen_release` to delete the pdf copies in `html/` and turn them into symlinks to `rst/`, which should drop the release size by ~1MB.

**Comment by daviditen** [comment]
One option is to change compression technology.  The downside is it adds a requirement for people who download the release to have a matching decompression tool available.

I tried a few out by generating a release .tar.gz file with gen_release, and then unzipping it and using other tools to re-compress it.

chapel.tar (uncompressed) 125 MB
gzip - (current practice) 55 MB
gzip --best - 55 MB (about 100KB smaller)
bzip2 - 52 MB
7zip - 45M

Exact commands used:
`gzip -6 chapel.tar`
`gzip -9 chapel.tar`
`bzip2 chapel.tar`
`7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on chapel.tar.7z chapel.tar`

**Comment by bradcray** [comment]
@ronawho: How are you feeling about this one these days?  I feel tempted to close it from the perspective of not being aware of anyone having seriously complained about it, but maybe I'm being too brazen.

**Comment by ronawho** [comment]
This was partially related to https://chapel.atlassian.net/browse/CHAPEL-267 (minimize the size of the Cray module)

I guess it can be closed, and if it becomes an issue in the future we can just reopen it

**Comment by bradcray** [comment]
Thanks.  And oops... I didn't mean to hit "close and comment", just "comment" (if it seemed weird that I was asking you but then just did it).

**Comment by ronawho** [comment]
Yeah, I had misinterpreted the accidental closing, this is not that important and would certainly be something for the icebox, though I'm opposed to just keeping it closed at this point either
