### ISSUE TITLE
Generate emails for new github issues

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#5458]
We have no good/easy way to get notified when new github issues are filed. Particularly for user issues, we really need some way of getting notified about new issues so we can triage (and potentially fix) them as quickly as possible.

My preferred solution would be to have 2 mailing lists that notifications get sent to. One that notifications for new user issues get sent to, and one that notifications for all new issues (user + core team) issues go to.

That way everybody on the core team could subscribe to the "user" list, and only people who really wanted to could get pinged about every new issue could subscribe to the "all" list 

Here's an (awful) link that we've been using to see user issues: https://github.com/search?utf8=%E2%9C%93&q=repo%3Achapel-lang%2Fchapel+is%3Aissue+-author%3Aawallace-cray+-author%3Aben-albrecht+-author%3Abenharsh+-author%3Abradcray+-author%3Adaviditen+-author%3Admk42+-author%3Agbtitus+-author%3Alydia-duncan+-author%3Amppf+-author%3Anoakesmichael+-author%3Apsahabu+-author%3Aronawho+-author%3Asungeunchoi+-author%3Atmacd9+-author%3Avasslitvinov&type=Issues&ref=searchresults

and one for "un-triaged/new" user issues: https://github.com/search?utf8=%E2%9C%93&q=no%3Alabel+repo%3Achapel-lang%2Fchapel+is%3Aissue+-author%3Aawallace-cray+-author%3Aben-albrecht+-author%3Abenharsh+-author%3Abradcray+-author%3Adaviditen+-author%3Admk42+-author%3Agbtitus+-author%3Alydia-duncan+-author%3Amppf+-author%3Anoakesmichael+-author%3Apsahabu+-author%3Aronawho+-author%3Asungeunchoi+-author%3Atmacd9+-author%3Avasslitvinov&type=Issues&ref=searchresults

But that's still a "pull" model and really we want something notifying us when there's new issues.

I have no idea what would be required to setup something that polls the issues and sends emails, but I can't imagine it's that hard.

**Comment by daviditen** [comment]
I think this issue can be closed now thanks to @tmacd9's issue emailer.

**Comment by ronawho** [comment]
Agreed that @tmacd9's script is doing a great job, so I'm not opposed to closing this. I do think it'd be nice to track potential future improvements somewhere though


Potential improvements that come to mind are:
 - Short term: commit the script that generates the emails and have the chapel group account run it
 - Longer term: maybe switch over to Heroku to match [what we do with commit messages](https://github.com/chapel-lang/github-email-notifications) (which would also have the side affect of not relying on a particular user having to run whatever script currently generates the mails)
