### ISSUE TITLE
ref-pair .locale problem

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#5468]
Right now, cullOverReferences includes a special case to make a .locale query use the "setter" version. This was added in commit d6bb7fe8.

This special case is problematic. I think it trades one bug for another.

Consider the following program:

``` chapel
const ParentDom = {0..10};
var SparseDom: sparse subdomain(ParentDom);
var A:[SparseDom] int;

proc f(const ref x)
{
  writeln(x.locale.id);
}

for i in ParentDom {
  f(A[i]); // appears to work
}

for i in ParentDom {
  writeln(A[i].locale.id);  // error: halt reached - attempting to assign a 'zero' value in a sparse array: (0)
}
```

Along with other work I'm doing in cullOverReferences, I'm able to remove this special case. However, that makes programs such as the following no longer work as expected:

``` chapel
use BlockDist;

var Space = {1..10};
var D = Space dmapped Block(Space);
var A:[D] int;

for i in D {
  writeln(A[i].locale.id); // prints only 0 if workaround in cullOverReferences is disabled
}
```

The reason this program no longer works is that the array accessor uses a value-return `proc this` for POD types (including integers which are used in the example). So without the workaround, the .locale query is getting the locale of a stack-local variable, which is always local.

However, the workaround in cullOverReferences doesn't extend to this program:

``` chapel
use BlockDist;

var Space = {1..10};
var D = Space dmapped Block(Space);
var A:[D] int;

proc f(const ref x)
{
  writeln(x.locale.id);
}

for i in D {
  f(A[i]); // prints only 0 with or without workaround in cullOverReferences
}
```

Are these programs erroneous? It seems to me that the first should run without error and the second should print out the locale on which A[i] is stored (and not just Locale 0).

**Comment by mppf** [comment]
I can think of the following long-term solutions:
* set PODValueAccess = true
   (is there a simple compiler optimization that can recover any performance gap?)
* support a 3-way "ref-pair"; the compiler would put select between value/ref/const ref based on the way the call is used.  It would put 3 calls into the ContextCallExpr and select the 'const ref' instead of the 'value' one if:
     - the value is used as a const ref
     - the value has its locale queried
  and otherwise proceed as it does now.

**Comment by mppf** [comment]
@bradcray - I'm interested in your thoughts on this. I already talked to @daviditen and @benharsh about it and they seemed to agree with my expectations that the programs should work as one would expect and that the 3-way "ref-pair" was the most appealing solution.

Without a fix here, the new late const-checking will have problems with several tests, including test/studies/hpcc/PTRANS/jglewis/ptrans_2011-blkcyc.chpl.

**Comment by bradcray** [comment]
I think I'm OK with the 3-way ref-pair solution.  I'm trying to think a bit about what makes .locale special in this regard and whether there are other things that should similarly trigger this behavior (e.g., would a user ever want to be able to tap into that same condition?)

Using A[i] in an on-clause would be an obvious additional case where we'd similarly want the 'const ref' version, but I'm guessing that works out automatically because we translate such cases into A[i].locale, is that right?

**Comment by mppf** [comment]
Passing to a `const ref` intent formal seems to me to require us to preserve identity - that is, use the `const ref` return array accessor if available. Users can and will make use of that in a call like f(A[i]) where f is declared with `const ref` formal intent.

AFAIK we translate data-driven on clauses to a .locale query, yes.

**Comment by bradcray** [comment]
Belated realization: Can we simply re-implement how .locale works to leverage 'const ref' intents so that it's less of a special-case?  E.g., if .locale translated into:

````chapel
proc chpl_determine_locale(const ref ) { ... } 
````

would that get us onto firm footing without a special-case?

**Comment by mppf** [comment]
@bradcray - no, the `const ref` intent doesn't work the way you'd expect now. It gets the value-version for POD type (e.g. integers) and then passes a ref to a stack-local temporary variable.

**Comment by bradcray** [comment]
Maybe my question wasn't clear:  In the proposed new 3-way ref pair world, would an implementation of .locale like the one I'm proposing make things simply work out as desired without requiring a separate "use const ref if the locale is queried" rule?  That's the special case I was trying to get rid of in the proposal.

**Comment by mppf** [comment]
@bradcray - yes, although in the near term I might opt to leave in the special case for expedience.

**Comment by bradcray** [comment]
OK, I'm 100% comfortable with the proposal in a world where the special case can cease to be one even if it's not on day one.

**Comment by mppf** [comment]
As of today, the 3-way "ref pair" is the agreed-upon plan.
