### ISSUE TITLE
Array view PR breaks replicated distribution tests

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#5472]
In late testing on the array view branch, we ran into a number of failures for the replicated distribution-specific testing configuration.  These fell into three categories:

~~1) "Internal error: compiler generated error":  Based on past experience, we believe that these are due to compiler bugs w.r.t. nontrivial iterators (e.g., see #5311 ).~~

- [x] distributions/robust/arithmetic/basics/test_array_of_distributed_array1.chpl
- [x] distributions/robust/arithmetic/basics/test_array_of_distributed_array2.chpl
- [x] distributions/robust/arithmetic/basics/test_distributed_array_of_array2.chpl
- [x] distributions/robust/arithmetic/basics/test_dd_array1.chpl
- [x] distributions/robust/arithmetic/basics/test_distributed_array_of_record2.chpl

1)(bis) This test exhibits a new failure mode as of 3/9 - "array index out of bounds":

- [ ] distributions/robust/arithmetic/basics/test_distributed_array_of_distributed_array1.chpl
  for which Valgrind reports:
```
Conditional jump or move depends on uninitialised value(s)
Use of uninitialised value of size 8
```

2) Getting incorrect results (believed to be due to domains not retaining locality information -- issue #5473 ):
- [ ] distributions/robust/arithmetic/modules/test_module_Norm.chpl
- [ ] distributions/robust/arithmetic/modules/test_module_Random.chpl
- [ ] distributions/robust/arithmetic/reindexing/test_array_alias2.chpl
- [ ] distributions/robust/arithmetic/reindexing/test_strided_reindex1.chpl
- [ ] distributions/robust/arithmetic/reindexing/test_strided_reindex2.chpl
- [ ] distributions/robust/arithmetic/slicing/test_array_slicing1.chpl
- [ ] distributions/robust/arithmetic/slicing/test_strided_slice2.chpl

3) Higher communication counts (also believed to be due to domains not maintaining locality info -- issue #5473):
- [ ] distributions/robust/arithmetic/performance/multilocale/alloc.chpl
- [ ] distributions/robust/arithmetic/performance/multilocale/alloc_all.chpl
- [ ] distributions/robust/arithmetic/performance/multilocale/assignAlias.chpl
- [ ] distributions/robust/arithmetic/performance/multilocale/assignSlice.chpl
- [ ] distributions/robust/arithmetic/performance/multilocale/reduceAlias.chpl
- [ ] distributions/robust/arithmetic/performance/multilocale/reduceSlice.chpl

**Comment by vasslitvinov** [comment]
@bradcray I updated the list above with (1)bis - based on last night's test results.

**Comment by bradcray** [comment]
Working on this in #5933.

**Comment by benharsh** [comment]
@bradcray : Should this issue be closed now that your Replicated work has been merged?

**Comment by bradcray** [comment]
Yes, thanks.  I've been hoping to sweep the array view issues (and all that I own/filed) once the dust settles on the release, but no such time yet...
