### ISSUE TITLE
Reindex/Rank Change array views don't maintain locality information on their domains

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#5473]
The current array view work loses locality information for rank change slices and reindexing if the view's domain is queried -- rather than maintaining the original array's distribution, it's as though the domain is completely local to a single locale.  This behavior can be seen in test/arrays/views/viewPreserveDist.chpl.

The fix is to create domain and distribution views for these operations that will similarly translate indices down to the underlying domain/distribution of the original array.

**Comment by bradcray** [comment]
PR #5694 got locality preserved for rank-change array views.

**Comment by bradcray** [comment]
PR #5757 is a start at doing the same for reindex array views (not yet merged).

**Comment by benharsh** [comment]
@bradcray : This issue can be closed now, right?

**Comment by bradcray** [comment]
Yes, thanks!
