### ISSUE TITLE
Be more principled about initializing and destroying atomics used in the runtime 

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#5482]
Our atomics implementation has init and destroy functions. We're good about calling these from module code, but we're not consistent about calling the init or destroy routines from runtime code (particularly for ugni.)

For CHPL_ATOMICS=intrinsics, init and destroy are no-ops so we don't usually get bitten by this, but for CHPL_ATOMICS=locks, it's really important that we actually initialize the atomic.

**Comment by ronawho** [comment]
One idea to track this down would be to stuff some extra bits into the locks implementation to track whether a lock has been initialized, and just error out in the atomic ops if it hasn't. This isn't perfect, because our canary value could happen to be set, but in practice that's unlikely

**Comment by ronawho** [comment]
We should also add an init and destroy interface to network atomics.

**Comment by gbtitus** [comment]
It's worth noting that, as it is currently coded, comm=ugni wouldn't work at all with CHPL_ATOMICS=locks  because it does at least one `atomic_init` operation in `chpl_comm_init()`, which is before the tasking layer is initialized and thus not a point at which one can be certain that sync variables will even work.  To some extent this highlights a problem that has always been present with the runtime atomics interface, which is that while it was introduced to support the semantics of Chapel atomics, it was quickly co-opted to also support mutual exclusion in the runtime.  But at least the "locks" implementation of runtime atomics is not actually suited to the latter, since a sync variable based approach can't necessarily be used before the tasking layer is initialized or within the tasking layer sync var implementation itself, and its performance for things like managing runtime counters would probably be very poor.  Probably the runtime should define a separate interface for its own internal atomics.

**Comment by ronawho** [comment]
Ensuring that we init atomic variables will also be important as we start considering making `CHPL_ATOMICS=cstdlib` the default on more platforms: https://github.com/chapel-lang/chapel/issues/11029

**Comment by gbtitus** [comment]
> I think this is outdated now that we use pthread_mutexes instead of sync variables to protect access fo the `CHPL_ATOMICS=locks` implementation (#10305)

I agree, but would note that our doing so has created another quirk with regard to using atomics in the runtime, which is that there is no inherent detection or prevention of tasking switching causing us to try to lock the same mutex more than once from a single thread.  There is a comment near the top of `include/atomics/locks/chpl-atomics.h` saying that no code currently yields from a critical section, but there's no guarantee that comment will be read, understood, or followed in the future, nor that code which does not task-switch within a critical section will forever continue not to do so.  And as we introduce more asynchronous behavior into the runtime it will probably get harder to guarantee this.  A separate Issue that seeks a principled solution to this might be wise.  One possibility would be to explicitly set the `mutexattr` type of atomic lock mutexes to `PTHREAD_MUTEX_ERRORCHECK` when initing them, for example. This would result in error returns for recursive lock attempts.  It might also be slower, though, so if performance is important for lock-based atomics we might want to make this switchable.

**Comment by ronawho** [comment]
>> I think this is outdated now that we use pthread_mutexes instead of sync variables to protect access fo the CHPL_ATOMICS=locks implementation (#10305)

> I agree, but would note that our doing so has created another quirk with regard to using atomics in the runtime, which is that there is no inherent detection or prevention of tasking switching causing us to try to lock the same mutex more than once from a single thread. There is a comment near the top of include/atomics/locks/chpl-atomics.h saying that no code currently yields from a critical section, but there's no guarantee that comment will be read, understood, or followed in the future, nor that code which does not task-switch within a critical section will forever continue not to do so. And as we introduce more asynchronous behavior into the runtime it will probably get harder to guarantee this. A separate Issue that seeks a principled solution to this might be wise. One possibility would be to explicitly set the mutexattr type of atomic lock mutexes to PTHREAD_MUTEX_ERRORCHECK when initing them, for example. This would result in error returns for recursive lock attempts. It might also be slower, though, so if performance is important for lock-based atomics we might want to make this switchable

Just to be clear the critical section here is the atomic op. It doesn't matter what the callsite does, so long as no code in the locks chpl-atomics.h file does a task yield while holding the lock on the mutex. I think that is incredibly unlikely to change in the future

**Comment by gbtitus** [comment]
> Just to be clear the critical section here is the atomic op. It doesn't matter what the callsite does, so long as no code in the locks chpl-atomics.h file does a task yield while holding the lock on the mutex. I think that is incredibly unlikely to change in the future

Oh, darn it, of course.  Never mind what I said ...

**Comment by ronawho** [comment]
Closing, I think we properly initialize all atomics in the runtime now
