### ISSUE TITLE
Have start_test -valgrind[exe] flag exit for bad configs

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#5492]
valgrind doesn't work particularly well when using qthreads or jemalloc, which are part of our default settings.  Unfortunately, I never remember this very quickly, so inevitably waste a fair amount of time when doing valgrind testing before I get everything set up correctly.

This issue proposes that we have the start_test script halt after parsing arguments and setting up if the -valgrind or -valgrindexe flags are thrown and CHPL_TASKS=qthreads or CHPL_MEM=jemalloc with an message indicating that you should use CHPL_TASKS=fifo and/or CHPL_MEM=cstdlib instead.

I was initially tempted to say that this should just print a warning, but my suspicion is that I wouldn't see them, hence I'm suggesting a halt instead.  My assumption is that developers who really want to push through this issue could comment out the halt for a short-term workaround.  If this was common behavior, we could have a way of disabling the halt via a flag, but that feels like overkill in the first draft solution to me.

**Comment by ronawho** [comment]
Just a nit: as of jemalloc 4.4.0 CHPL_MEM=jemalloc should work just fine with valgrind. jemalloc 5.0 will remove valgrind support, so I never bothered to convert nightly testing back to using jemalloc.

👍  for this idea overall though

**Comment by bradcray** [comment]
Thanks for the reminder, I'd forgotten that.  I was testing with 1.14.0 which is pre 4.4.0, which is why I got bitten by this...

**Comment by ronawho** [comment]
re2 dropped support for valgrind (https://github.com/google/re2/commit/ce6f2884c4), so we lost re2 valgrind support when we upgraded to the latest re2 in https://github.com/chapel-lang/chapel/pull/6024. 

We'll want to add CHPL_REGXP to the list of things to check.

**Comment by ronawho** [comment]
Added https://github.com/chapel-lang/chapel/issues/6158 to track adding address sanitizer testing, which might be a better long term option instead of trying to continue to support valgrind testing. I haven't used any sanitizers myself, but that seems to be what all the cool kids are using.

**Comment by psahabu** [comment]
I just got bit by this really hard when testing #7622, and didn't realize it because I had a prediff that was slicing out the "hwloc x86 backend" error. This caused the test to fail inexplicably, making me think I wrote the prediff wrong instead of running on a bad config.

👍 on this proposal
