### ISSUE TITLE
Add support for multi-line string literals

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#5501]
(* "easy" if you're comfortable working in flex I suspect...)

In C, one can split a string literal across multiple lines simply by closing and re-opening it:

````
printf("Hi there "
       "from C!");
````

Chapel doesn't currently support this, but I don't believe there's any deep reason it can't/shouldn't; and it would be a nice convenience feature to have.  This issue proposes adding such support to our lexer.  I don't think the parser would need to be involved or any the wiser.

**Comment by xSooDx** [comment]
Hi @bradcray 
I would like to help out with this issue.

From what I have understood, I need to alter the processStringLiteral() function in the /compiler/parser/chapel.lex file.

However I am having trouble navigating the files. I cannot find  the definition for the astr() function.
Could you help me out with this?

Thank You

**Comment by bradcray** [comment]
Hi @xSooDx --

Yes, I believe that that routine would be a valid place to implement this feature.  Another option would be to combine STRINGLITERAL tokens in the chapel.ypp bison file.

One tip because I always forget it:  Our Makefiles don't rebuild the parser automatically when chapel.lex or chapel.ypp are modified.  To do that you have to do 'make parser' and then 'make compiler' or 'make all'.  (In one command, you could do 'make parser compiler').

astr() is defined in compiler/util/stringutil.cpp / compiler/include/stringutil.h.  That said, there's no requirement to use it in this context unless it's useful (astr(), in general, both serves as a string concatenation helper and as a string uniquifier -- that is, if there are two strings "foo" in the compiler, they will share the same storage, permitting pointer comparison to be used to compare them rather than more expensive strcmp()s).

As a general tip, if you use emacs or vim as an editor, you might look into its support for 'tags' as a means of jumping from uses of variables/functions to their definitions.  If the compiler is built with CHPL_DEVELOPER set to true in your environment, you should get a TAGS file in your compiler/ directory that emacs can use to jump you to a symbol's definition.  If you use vim, set CHPL_EDITOR to 'vim' in your environment, and I believe you'll get a vim-oriented 'tags' file (I'm not a vim user).

One other good tool to know about is 'git grep' -- if you were to 'git grep astr' you'd see both the uses and definitions of astr, but if you then filter those results further (e.g., grep for .h files only to find the signature), you can often distinguish the definition from the uses.

**Comment by bradcray** [comment]
Oh, one other thought:  I filed this away on a whim because I often wonder about it.  Before you dive too far into it, you might send a mail to one of the chapel-user or chapel-developers mailing lists checking to see that there's broad support for the feature (since it represents a language change).  Sending mail to either of these lists requires subscribing to them.

**Comment by bradcray** [comment]
(or, you can try to implement the feature first and then get support for it... the only downside is wasted work if people aren't broadly supportive of it; but it still might be an interesting/educational project... :)  ).

**Comment by bradcray** [comment]
In PR #5497 (which led me to file this issue), @daviditen made the following observation:

> I don't think the current Chapel way of breaking up strings across lines is particularly bad.  If the same call were written in Chapel, I would have suggested:
> 
> ```
>   USR_WARN(expr, "support for '=>' in constructor argument lists is" +
>                  " deprecated as of chpl version 1.15 and is unlikely to" +
>                  " work as well as it used to.  If you rely on this feature," +
>                  " please let the Chapel team know.");
> ```
> 
> Sure, it doesn't become a single string until function resolution vs. in the lexer, but I don't think that's a big deal.
> 
> I don't have a problem with adding the C-style way, I just don't think we're in a bad place without it.

**Comment by bradcray** [comment]
On chapel-developers, @mppf made the same observation as @daviditen's above, adding:

> This is how you'd do it in Java so I don't think it's ridiculous or anything. Param string folding should take care of it.

Damian McGuckin followed up with:

> I agree. This is a lot more consistent.
> 
> As long as it is treated as a 'param', won't this get done at compile-time, and not run-time?

It is correct that param string-folding will take care of this case.  My thinking for adding the C-like support as an alternative was:

* it appends the strings much earlier in compilation and in a lower-level fashion (i.e., it's more efficient, though it's hard to imagine this mattering much for real programs).
* it provides a familiar feature to the C programmer without introducing an ambiguity in Chapel

But if those advantages seem too weak or like the feature would add unnecessary ugliness to the language, I'm not going to fight hard for it.

**Comment by bradcray** [comment]
On email, @tmacd9 said:

> The one disadvantage I've encountered in C is an example like:
>
> ````c 
>    const char *a_s[] = {
>       "abc",
>       "def"
>       "ghi"
>    }
> ````
> 
> The missing comma in the initializer list is not diagnosed but causes an unwanted initialization.
> 
> In Chapel:
>
> ````chapel 
>   var a_s  = [
>      "abc",
>      "def"
>      "ghi"
>   ];
> ````

This is the kind of "this feature is potentially dangerous" type of war story that I was curious about (and could imagine falling prey to).  I think based on this, and the generally negative tone to the responses people have given so far, we should probably not implement this feature and close the issue.  If anyone feels differently, please speak up.

@xSooDx, thanks for your willingness to implement it and for kicking off the email conversation about the topic.
