### ISSUE TITLE
Cleanup and simplify Cray platform README once muxed is retired

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#5523]
doc/platforms/cray.rst is pretty long and IMO overly specific. It could use some cleanup, but since a fairly large portion of it is dedicated to the muxed tasking layer, I don't really want to clean it up before muxed is retired. 

This issue is just a placeholder so I don't forget to clean it up after the 1.15 release.

**Comment by ronawho** [comment]
#5975 removes muxed, once that is merged, I think we can/should overhaul cray.rst

**Comment by ronawho** [comment]
@gbtitus I think we should get to this during doc-freeze, especially since there will probably be dynamic registration related things to document

**Comment by gbtitus** [comment]
This might be done now, but someone (you know who you are) should take a run through it to make sure.

**Comment by ronawho** [comment]
Between https://github.com/chapel-lang/chapel/pull/7419 and https://github.com/chapel-lang/chapel/pull/7438 this is done
