### ISSUE TITLE
LLVM performance with -use-cfl-aa

### ISSUE THREAD

**Issue by coodie** [chapel-lang/chapel#5533]
This is place to discuss the last point in issue #5043 (" try -mllvm -use-cfl-aa for clang with --llvm-wide-opt.").

In general I noticed no difference between --llvm-wide-opt and --llvm-wide-opt with -use-cfl-aa.

Here are the details:

Effect of running printchplenv:
```
machine info: Linux goovie-ThinkPad-T430 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64
CHPL_HOME: /home/goovie/Dokumenty/Repozytoria/chapel/ *
script location: /home/goovie/Dokumenty/Repozytoria/chapel/util
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: none *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_MAKE: make
CHPL_ATOMICS: intrinsics
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: none
CHPL_WIDE_POINTERS: node16 *
CHPL_AUX_FILESYS: none
```

Tests I used were the one in test/performance/ferguson/. What I did was run command (for file in the directory):
```
chpl --fast --llvm --llvm-wide-opt --ccflags -mllvm --ccflags -use-cfl-aa file.chpl -o file-cfl
chpl --fast --llvm --llvm-wide-opt file.chpl -o file-nocfl
```
and then
```
./file-cfl -nl 2 > cfl.out
./file-nocfl -nl 2 > nocfl.out
diff cfl.out nocfl.out
```

The diff command showed no difference for any file in that directory, thus I assume that in case of these tests cfl-aa has no improvement.

**Comment by ben-albrecht** [comment]
@mppf may be interested in this as the author of #5043.

It's not clear to me how you're doing performance testing here without collecting timings, either manually or with `start_test --performance ...`, unless I'm missing something.

**Comment by coodie** [comment]
@ben-albrecht 
As far as I understood the purpose of this task was to check how does playing with different options in LLVM optimizer affects number of get/put operations (in general: communication), more details on how does llvm backend is supposed to optimize is here: http://ahayashi.blogs.rice.edu/files/2013/07/Chapel_LLVM_camera_ready-q6usv4.pdf. 

Each of these tests has `startCommDiagonstics()/getCommDiagnostics()` pair around code tested for communication, and number of put/get is printed by the program itself. This isn't supposed to measure time (because it's difficult to do that well, and I only have gasnet which i can run locally, which is very slow and is performance bottleneck), so this test is supposed to be performed in inidividual way.

**Comment by mppf** [comment]
@coodie - cool, thanks for making this issue about your experiment. Can you, with a limited amount of effort, figure out if the reason --use-cfl-aa has no effect is trivial ? E.g. is that alias analysis pass running in LLVM in your experiment at all? Is our generated LLVM IR including the information it needs to do its job? Is the LLVM IR output different with --use-cfl-aa ? (You can use --savec=tmp and that will produce two .bc files, one for before opts run, one for after).

**Comment by mppf** [comment]
Closing this now that it's linked from the LLVM issues issue.
