### ISSUE TITLE
KNL locale model post-commit TODOs

### ISSUE THREAD

**Issue by dmk42** [chapel-lang/chapel#5569]
This issue tracks any items that need to be addressed after the KNL locale model PR #5555  is committed.

More sophisticated method of choosing memory kinds:
It would be nice to be able to specify more than one property.  What if we had a function
  locale.selectCharacteristics(args...)
where each argument is a set of available sublocales?  The sets could be created by functions like
  memoryPerSublocale(s: int)
  highBandwidth()
  lowLatency()
and they return a set of the memory kinds that match that characteristic.  The selectCharacteristics function intersects the sets in order, excluding any that cause the resulting set to become empty.

Non-KNL issues uncovered by the PR, to be addressed later:
* In modules/internal/defaultRectangular.chpl, dataParIgnoreRunningTasks is set to false for the flat locale model, which could cause heavy oversubscription.  More thought should be given to this.  See [720c769](https://github.com/chapel-lang/chapel/commit/720c769658358e406745ed8dc11160dd9e61e023) for more info.
* Overall, as more locale models are added, we will need to take a closer look at the prediff and skipif files to make sure we apply tests to the right locale models.  Some tests have been converted from ==numa to !=flat, and that may need to be revisited if locale models with completely different characteristics are added.

**Comment by dmk42** [comment]
I'm deleting the following from the list, which has now been done:

---

The following files need additional documentation on the KNL locale model.

* doc/technotes/localeModels.rst
* doc/platforms/knl.rst

**Comment by ronawho** [comment]
KNL locale model was removed in https://github.com/chapel-lang/chapel/pull/15832
