### ISSUE TITLE
Automatically rebuild third-party dependencies when they change

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#5577]
We have good dependency checking for the compiler and runtime, but not for third-party libraries. 

i.e. when we upgrade qthreads/hwloc/jemalloc/gasnet versions we don't automatically rebuild. Additionally, we don't rebuild when breaking makefile changes are made (like with #5566.)

This is really a developer-only problem, but even those of us on the core team are often caught off-guard by breakages that result from these sorts of things.

**Comment by ronawho** [comment]
Relatively simple idea might be to compute the checksum of the the third-party source and our Makefiles, and use that checksum as a dependency

**Comment by upcrob** [comment]
I just got burned by #5566 when I tried to build today as well.  I imagine more thought should go into this than I've put into it, but the following worked for me:

```
diff --git a/Makefile b/Makefile
index 8aed32c..664e809 100644
--- a/Makefile
+++ b/Makefile
@@ -58,6 +58,7 @@ all: comprt
 
 comprt: FORCE
 	@$(MAKE) compiler
+	@$(MAKE) jemalloc
 	@$(MAKE) third-party-try-opt
 	@$(MAKE) always-build-test-venv
 	@$(MAKE) always-build-chpldoc
@@ -83,6 +84,11 @@ runtime: FORCE
 third-party: FORCE
 	cd third-party && $(MAKE)
 
+jemalloc: FORCE
+	-@if [ "$(git show | grep \"third-party/jemalloc\" | wc -c)" != "0" ]; then \
+	cd third-party/jemalloc && $(MAKE); \
+	fi
+
 third-party-try-opt: third-party-try-re2 third-party-try-gmp
 
 third-party-try-re2: FORCE
```

It's a little (a lot?) naive and hacky, especially since it will always result in a third-party rebuild from that commit, but for simple scenarios it seems to work.

**Comment by ronawho** [comment]
@upcrob interesting idea. That'll only work if the last commit involved a change to jemalloc though, right? At least for me `git show` just shows the last commit. If you pulled in 20 commits, and the middle one was the jemalloc upgrade I think it would be missed. 

Still we could do something along those lines -- maybe store the sha at the time a 3rd party was built, and do a diff against the current one checking for changes to third-parties. I worry about the time that would add to a no-op build since git operations can be slow, especially on non-local filesystems.

I had originally been thinking we'd want a solution that didn't rely on git for people using the tarball, but we probably only have to be concerned about this for developers that are using the git repo.

**Comment by ronawho** [comment]
Maybe something like:

```sh
git ls-files -s third-party/jemalloc > je-sha && shasum je-sha > $JEMALOC_BUILD_HASH && rm je-sha
```

basically collect the git SHAs of all files in third-party/jemalloc in a file, and then hash that file and store it in the jemalloc build dir. Then check if the current hash is different than the one from build time to decide if we need to rebuild.

That seems to run pretty fast -- ~.1 seconds even on a really slow nfs mount.

**Comment by upcrob** [comment]
Yep, you're right about what I had proposed.  It might work with a `git diff --stat` instead of `git show`, but you would still run into the rebuild issue.

You're proposal seems to make sense.  Overall, would it look something like this?

```
get sha of versioned jemalloc files, store in tmp-je-sha
if je-sha does not exist or if tmp-je-sha does not match je-sha
    build jemalloc
    rename tmp-je-sha to je-sha
```

Alternatively, if you would like to avoid git for tarballs, you could probably do a `find` in the third-party directory instead for relevant source/Makefiles, though I could see that being somewhat brittle.

**Comment by ronawho** [comment]
My initial thought was to use `find` and compute the shas ourselves, but it's pretty slow (~5 seconds) to compute the sha of all the files in some of our larger third-party directories. Git stores the computed shas for us, so it's a lot faster to just use those values, and only have to hash once ourselves.

**Comment by upcrob** [comment]
Here's another diff of what I've done, based on what you've suggested.  It appears to work in my smoke tests:

```
diff --git a/.gitignore b/.gitignore
index 50f1da1..f8799c4 100644
--- a/.gitignore
+++ b/.gitignore
@@ -459,6 +459,7 @@ tags
 /test/users/thom/returnGenericLineno/strassen
 
 # Third party ignores.
+*-sha
 /third-party/**/build
 /third-party/**/install
 /third-party/gmp/gmp-6.0.0
diff --git a/Makefile b/Makefile
index 8aed32c..cd8a400 100644
--- a/Makefile
+++ b/Makefile
@@ -58,6 +58,7 @@ all: comprt
 
 comprt: FORCE
 	@$(MAKE) compiler
+	@$(MAKE) jemalloc
 	@$(MAKE) third-party-try-opt
 	@$(MAKE) always-build-test-venv
 	@$(MAKE) always-build-chpldoc
@@ -83,6 +84,16 @@ runtime: FORCE
 third-party: FORCE
 	cd third-party && $(MAKE)
 
+jemalloc: FORCE
+	git ls-files -s -m third-party/jemalloc | sha1sum > .tmp-je-sha
+	-@diff .tmp-je-sha .je-sha 1>/dev/null 2>/dev/null; \
+	if [ $$? != 0 ]; then \
+		cd third-party/jemalloc && $(MAKE) && cd ../.. && mv .tmp-je-sha .je-sha; \
+	else \
+		rm -f .tmp-je-sha; \
+	fi
+
+
 third-party-try-opt: third-party-try-re2 third-party-try-gmp
 
 third-party-try-re2: FORCE
@@ -148,6 +159,7 @@ cleanall: FORCE
 	if [ -a doc/Makefile ]; then cd doc && $(MAKE) cleanall; fi
 	rm -f util/chplenv/*.pyc
 	rm -rf build
+	rm -f *-sha
 
 cleandeps: FORCE
 	cd compiler && $(MAKE) cleandeps
```

**Comment by ronawho** [comment]
Cool!

I'm caught up in some stuff for our upcoming release, but I'll try to look at this soon. Ping me if you don't hear back from me in the next few days. 

And just fyi: github will give you colored diffs if you do: 

    ```diff
    ```

**Comment by upcrob** [comment]
Thanks, good to know!  I'm in no hurry, so that's fine by me.

**Comment by ronawho** [comment]
Misc thought -- I wonder if using git submodules or something would make this any easier?

It seems like there should already be a solution for this, surely we aren't the only ones who bundle 3rd party libraries in our repo.

**Comment by upcrob** [comment]
I've never used git submodules, so I can't really speak to that, though they do look like they were designed for this sort of problem from a versioning standpoint.  Would we still be left with the issue of deciding when to build third party libraries (i.e. keeping track of the most recent version that was built)?

**Comment by ronawho** [comment]
I've never used submodules either, so it's not obvious to me if they would actually make things easier.

It just seems like there has to be an existing solution, so I mostly wanted to note that so I don't forget to take a look at what other projects do.

**Comment by ronawho** [comment]
This ended being a lot simpler than I thought it would be. With help from @dmk42 I have an initial prototype: https://github.com/chapel-lang/chapel/compare/master...ronawho:auto-rebuild-3rd-party

Using jemalloc as an example it basically just does: 

```sh
find third-party/jemalloc/jemalloc-src third-party/jemalloc/Makefile*
```
and uses that list of files as makefile dependencies. If we upgrade sources, or change how we build a 3rd party package, make will detect the files changed and will trigger a rebuild.

**Comment by ronawho** [comment]
https://github.com/ronawho/chapel/tree/auto-rebuild-3rd-party-2 is my current prototype, but unfortunately that's not quite good enough.

It works well for a single-config but it causes unnecessary rebuilds across multiple configs. i.e. if you build for comm=none and then for comm=gasnet we'll rebuild hwloc and qthreads. This is because we touch some autoconf files as part of the hwloc and qthreads build, which causes the sources to look newer. 

I think we either need to exclude the files we touch from the `find` or we just need to use a sentinel file that we change whenever we do upgrades.

**Comment by ronawho** [comment]
https://github.com/chapel-lang/chapel/issues/7004 is my current approach. To avoid the problems with gasnet/qthreads/hwloc bootstrapping I'm just only depending on C/C++ source files instead.

**Comment by ronawho** [comment]
https://github.com/chapel-lang/chapel/issues/7004 has been merged. We should auto-rebuild on version upgrades and whenever our third-party/*/Makefiles change. 

Since we're doing `find` on large third-party dirs this adds a little bit of time to a no-op top-level `make`, but in my experience it's not noticeable. If it becomes an issue we can implement one of the ideas discussed in https://github.com/chapel-lang/chapel/pull/7004#discussion_r132974774

**Comment by upcrob** [comment]
Thanks!
