### ISSUE TITLE
Move performance graphs off of sourceforge

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#5593]
Our performance graphs are currently hosted at sourceforge: http://chapel.sourceforge.net/perf/

We could move our graphs to github pages. Sourceforge has a lot of downtime than github, and all the rest of our development has moved to github. One slightly tricky part is that github pages are for static content only, which means we can't use PHP. The main perf landing page was copied from the chapel.cray.com site, so it does use PHP, but it should be easy enough to get rid of it. github pages also use a git repo, so we'd have to change our synctoSourceforge script to `git commit` instead of `rsync`

**edit**:

Alternatively, now that chapel-lang.org is up (instead of chapel.cray.com) we might be able to move the graphs there instead. That way we could still rsync and keep most of our current infrastructure. We didn't use chapel.cray.com because IT didn't want us to in the past. I think they didn't want us rsyncing 100s of MB nightly, and it probably would have been pretty slow to use since I don't think the backing server was replicated across different areas (i.e. load times from the east coast might have been slow or something). We now have a real hosting service, so we should do some comparisons to see if chapel-lang.org or github pages will be faster

**Comment by ronawho** [comment]
Sourceforge is down again :(

**Comment by ronawho** [comment]
Since we post perf graph links in public pretty often, we'll want to make sure the old SF links forward to the new github pages.

**Comment by ronawho** [comment]
https://ronawho.github.io/perf/ was an initial test I did a few months ago. Note that it looks different than http://chapel.sourceforge.net/perf/ because github pages don't support php (as noted in the description.) The actual graph pages work fine though -- https://ronawho.github.io/perf/chap04

**Comment by mppf** [comment]
Re it looking different on github vs sourceforge. Can we use an iframe to host the github perf links page from chapel.cray.com? Or just host the /perf landing page entirely on chapel.cray.com and rely on direct links to the perf graph pages?

**Comment by ronawho** [comment]
@mppf I'm not following what you're suggesting. Are you saying we should host the perf graphs on chapel.cray.com, or just the perf landing page and leave the actual graphs on github pages?

My preference would be to just transition the perf landing page to use sphinx like http://chapel.cray.com/docs/latest/ and keep it all on github. There's very little content on chapel.sourceforge.net/perf/ (I think I put it together in a few hours), so it shouldn't be much effort 

Some historical context: when we originally started hosting the graphs externally, IT did not want us to put the graphs on chapel.cray.com because of how much data we'd be moving nightly (currently we move around 1GB per night.) Granted that was when chapel.cray.com was hosted by an internal server so maybe things have changed now that we have a real provider.

**Comment by mppf** [comment]
> @mppf I'm not following what you're suggesting. Are you saying we should host the perf graphs on chapel.cray.com, or just the perf landing page and leave the actual graphs on github pages?

I'm suggesting to host the landing page on chapel.cray.com, or make it appear to be hosted there with an iframe. The other option would be fine with me too, if we decided it was workable.

**Comment by bradcray** [comment]
Do @ronawho and/or @awallace-cray have the knowledge they'd need to attempt syncing these to chapel-lang.org at this point? (where something would still have to be done on my end to have a URL point to the result).

**Comment by awallace-cray** [comment]
Yes, how about I push graphs next to the online docs, then you can review and place the link.
/Tony

**Comment by bradcray** [comment]
Sounds great!

**Comment by awallace-cray** [comment]
Today's perf graphs are live on chapel-lang.org.  
Once PR #7667 is merged, Jenkins will start pushing updates there for all builds that get this PR when they git fetch origin master - no sooner than tomorrow morning's perf builds, probably.

**Comment by ronawho** [comment]
Closed by https://github.com/chapel-lang/chapel/pull/7667 (perf on dreamhost seems fine and for the most part seems more reliable than sourceforge)
