### ISSUE TITLE
remove tryToken aka chpl__tryToken

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#5595]
We have been wanting for a while to get rid of tryToken because it is too big of a hammer and has hidden errors in Chapel code. As of this writing, tryToken is used:

* when choosing between standalone and leader/follower for forall statements/expressions
* when choosing between standalone, leader/follower, and serial for reduce expressions
* when choosing between parallel and serial implementation of array assignment

Some of these can be addressed by changing the language semantics to allow forall loops and forall expressions to invoke the serial iterator if no suitable parallel iterator is found.

The following is relevant if we do not take the above language-semantics-change route.

The following code in ChapelArray.chpl / `chpl__transferArray()` is executed for some assignments to an array:

```Chapel
    if chpl__tryToken then
      forall (aa,bb) in zip(a,b) do aa = bb;
    else
      for (aa,bb) in zip(a,b) do aa = bb;
```

where tryToken helps choose between serial and parallel implementation.

What if, instead of tryToken, we put some code to determine whether a parallel iterator is available. For example:

```Chapel
proc canZipForall(ref a: [], const ref b) param {
  if canResolveMethod(a._value, "these", iterKind.leader) {
    var followThis: iteratorIndexType(a._value.these(iterKind.leader));
    if canResolveMethod(a._value, "these", iterKind.follower, followThis) &&
       canResolveMethod(b._value, "these", iterKind.follower, followThis)
    then return true;
  }
  return false;
}
```

The challenge there is what if `b` is a for or forall expression? then the `b` formal is an IR i.e. _iteratorRecord, for the **serial** iterator. To make the above scheme work, we need to write a check whether there is a follower iterator for it. How to write it?

**Comment by npadmana** [comment]
Following a discussion with @mppf and @e-kayrakli  on IRC, I'll note here that I might have tripped over this bug in the wild. 

```
iter localArrays() ref {
  halt("Dummy serial iterator");
}

iter localArrays(param tag: iterKind) where (tag==iterKind.standalone) {
  coforall locid in 0.. #numLocales {
    yield locid;
  }
}

forall a1 in localArrays() {
  /* Changing this to real has this working */
  var tmp : [0..5] real(32);
  tmp = 2*tmp-1;
}
```

fails to compile with 
```
foo.chpl:11: error: unresolved call 'localArrays(tag=iterKind)'
foo.chpl:1: note: candidates are: localArrays()
foo.chpl:5: note:                 localArrays(param tag: iterKind)
```

The real issue here is the line `tmp = 2*tmp-1;`, which has a type mismatch --- but this gets obscured by the compiler error.

**Comment by bradcray** [comment]
It seems that all uses of tryToken have now been removed, so all that remains is to clean its definition out of the compiler as well!  (?)

**Comment by vasslitvinov** [comment]
I have verified that all uses of tryToken have been removed. It is a good idea to remove its definition from the compiler as well. After the release we can also remove the supporting machinery like tryStack and tryFailure.

**Comment by bradcray** [comment]
@vasslitvinov: Stumbled across this and was surprised it was still open.  Looks like there was some follow-on cleanup you'd hoped to do after the (last) release if you need a study break.

**Comment by vasslitvinov** [comment]
All cleanup is complete. Closing.
