### ISSUE TITLE
GSoC Contribution Help

### ISSUE THREAD

**Issue by AnshulMalik** [chapel-lang/chapel#5611]
Hi, 
I am a student from India. Earlier, I haven't heard of chapel :P, but now I realize, it's really cool.

I wish to contribute to chapel with "Distributed Data Structures Library". But I am new here so would like some guidance regarding chapel environment.

@e-kayrakli , can you provide me with some headstart :P, point me in a direction and I'll find the rest of the path. Because right now, I am just trying to understand the codebase.

Thanks

**Comment by bradcray** [comment]
GitHub issues are not intended as a means of conversing between Chapel contributors.  Please use the chapel-developers mailing list or IRC channel for inter-personal communications.  For more details, see:

http://chapel.cray.com/developers.html
