### ISSUE TITLE
ref-pair precedence question

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#5614]
### Summary of Problem

Currently, ref-pairs are resolved regardless of other precedence choices. This might be confusing.

After PR #5561, the behavior of this program changed, because const ref vs value return is now included in ref-pair calculations in resolveNormalCall. However, the issue started with the first versions of ref-pair support in the compiler.

The question is - if normal resolution rules would select the ref/const ref/value version in preference to the other version, should that always be used? Should ref-pair behavior only be triggered if there would otherwise be an ambiguity? It's not currently the case as this test demonstrates.

One reason the answer to this question isn't entirely obvious is that generic functions with a matching `where` clause are normally selected in favor of generic functions without a `where` clause. That pattern comes up in the array accessor methods, where the `ref` return version does not have a `where` clause but the value or const ref return versions do.

### Steps to Reproduce

In the below program, one might expect the child name functions to always return "Child" but they do not currently.

**Source Code:**

```chapel
var parentName = "Parent";
var childName = "Child";

class Parent {
  // ref + const ref
  proc name const ref return parentName;
  proc name2 ref return parentName;

  // const ref + value
  proc name3 const ref return parentName;
  proc name4 return parentName;

  // ref + value
  proc name5 return parentName;
  proc name6 ref return parentName;
}


class Child : Parent {
  // ref + const ref
  proc name ref return childName;
  proc name2 const ref return childName;

  // const ref + value
  proc name3 return childName;
  proc name4 const ref return childName;

  // ref + value
  proc name5 ref return childName;
  proc name6 return childName;
}


writeln("Calling child name functions");
var c = new Child();
writeln(c.name);
writeln(c.name2);
writeln(c.name3);
writeln(c.name4);
writeln(c.name5);
writeln(c.name6);

writeln("Calling parent name functions");
var d = c:Parent;
writeln(d.name);
writeln(d.name2);
writeln(d.name3);
writeln(d.name4);
writeln(d.name5);
writeln(d.name6);
```

**Associated Future Test(s):**
test/functions/ferguson/ref-pair/across-scopes.chpl

**Comment by benharsh** [comment]
Would this case work correctly if we required overriding functions to have the same return-intent(s)?

**Comment by mppf** [comment]
Parentheses-less methods aren't overridden or subject to virtual dispatch. So this case is more about coecing from Child to Parent.

**Comment by benharsh** [comment]
Also, it seems that ``name5`` and ``name6`` always return ``parentName``. Why doesn't Child's name5/6 try to return ``childName``?

**Comment by mppf** [comment]
Right, that's an Oops... I'll fix.

**Comment by bradcray** [comment]
Intuitively, my sense is "only if there is otherwise an ambiguity" is the right way to go.  In the accessor case you describe, could the where clauses be pushed into the body of the accessors (as to-be-folded param conditionals) in order to make the overloads more symmetrical?

Maybe put another way:  When writing routines that are subject to the ref-pair (ref-triple?) rules, it seems like it would be good practice to write the signatures to be identical other than the return intent in order to cause them to "truly" be signatures.  It sounds like the accessors aren't this way at present, in which case I wouldn't do what seems like the more intuitive thing simply because of current code.

(This is a pretty quick reaction, though, not a well-thought-out one).

**Comment by mppf** [comment]
Thanks for the sanity check... I think I was confusing myself. It turns out this was a fairly simple bug. I've fixed it in PR #5619.

**Comment by mppf** [comment]
I think the remaining open semantic issue is - should we do this ref-pair thing when we have a value return and a const ref return?

I'm not to worried about it right now (which is why it doesn't have its own issue) but we can make an issue about that if anybody has a strong opinion.

Right now, ref-pair behavior requires 2 or 3 fns where 1 of them has ref return intent.

**Comment by bradcray** [comment]
What happens today if you only define the const ref and value overloads?  An ambiguity?  Or does it just always pick a certain one of them?

**Comment by mppf** [comment]
@bradcray - I think right now we always pick the value one, but I don't think that's what it should do. I think it should either be:

1) choose between value and const ref version depending on how the expression is used
2) make it a failure to resolve due to ambiguity

There are some other issues with ambiguity & ref pairs that stem from the fact that disambiguateByMatch returns NULL for both 0 matches and also for ambiguity. That means that e.g. declaring 2 ambiguous ref-return functions will disable ref-pair functionality rather than raise an error. We've lived with this for some time now, but I'm hoping to fix that (possibly after feature freeze).

**Comment by bradcray** [comment]
@mppf: Should we branch this sub-issue into its own issue, or are you far enough along with a fix that it won't get forgotten?

**Comment by mppf** [comment]
@bradcray - I moved that question to issue #5656. thanks.
