### ISSUE TITLE
Failure for timezone handling in the Cray PrgEnv

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#5645]
### Summary of Problem
The test test/modules/standard/datetime/testTime.chpl is experiencing an issue in the Cray PrgEnv due to the DateTime module implementation w.r.t. timezones.

It generates the following output:
```> CC-513 craycc: WARNING File = /tmp/chpl-chapelu-15201.deleteme/DateTime.c, Line = 1928
>   A value of type "c_ptr_int8_t" cannot be assigned to an entity of type
>           "const char *".
>
>   (&timeStruct_chpl)->tm_zone = ((c_ptr_int8_t)(((c_string)(((c_void_ptr)((&call_tmp_chpl11)->buff))))));
>                               ^
>
> CC-513 craycc: WARNING File = /tmp/chpl-chapelu-15201.deleteme/DateTime.c, Line = 1941
>   A value of type "c_ptr_int8_t" cannot be assigned to an entity of type
>           "const char *".
>
>   (&timeStruct_chpl)->tm_zone = ((c_ptr_int8_t)(""));
>                               ^
>
> Cray C : Version 8.4.6 (20160328193024_838fea6bbef776e483380a4ecf458b3dff303cd0)
> Total warnings detected in /tmp/chpl-chapelu-15201.deleteme/_main.c: 2
```

### Steps to Reproduce
Run test/modules/standard/datetime/testTime.chpl in the appropriate configuration set up.

**Compile command:**
`chpl testTime.chpl --cc-warnings -o testTime`

**Execution command:**
./testTime

### Configuration Information

- Output of `chpl --version`: latest master
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```CHPL_TARGET_PLATFORM: cray-xc *
CHPL_TARGET_COMPILER: cray-prgenv-cray
CHPL_TARGET_ARCH: x86-64
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none *
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_MAKE: gmake
CHPL_ATOMICS: intrinsics
CHPL_GMP: system
CHPL_HWLOC: hwloc
CHPL_REGEXP: none
CHPL_WIDE_POINTERS: struct
CHPL_AUX_FILESYS: none
```
- Cray PrgEnv:
PrgEnv-cray/5.2.78

**Comment by daviditen** [comment]
The basic problem here is that on OSX, the field `tm_zone` in `struct tm` is a `char*`, not a `const char*`, so I made the extern declaration for it look like `var tm_zone: c_ptr(c_char)`.  This required a cast from a `c_string` to `c_ptr(c_char)` when assigning a `c_string` to the `tm_zone` field to drop the const qualifier that `c_string`s have.

PrgEnv-cray declares the `tm_zone` field as `const char*`, and doesn't think that our `c_ptr_int8_t` is the same type.

**Comment by daviditen** [comment]
PR #5825 should fix this.
