### ISSUE TITLE
return intent overload and ambiguity

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#5656]
What happens today if you only define the const ref and value overloads?  An ambiguity?  Or does it just always pick a certain one of them?

After PR #5561, the compiler always chooses the value one. Before that, it would have been an ambiguity error. Note that this problem existed for duplicate ref versions starting with the first ref-pair support in the compiler.

As far as what should happen, I think it should either be:

1) choose between value and const ref version depending on how the expression is used
2) make it a failure to resolve due to ambiguity

There are some other issues with ambiguity & ref pairs that stem from the fact that disambiguateByMatch returns NULL for both 0 matches and also for ambiguity. That means that e.g. declaring 2 ambiguous ref-return functions will disable ref-pair functionality rather than raise an error.

It seems clear to me that duplicate `ref` return versions should create a failure to resolve rather than silently preventing the usual ref-pair behavior. That's a bug, but we have to choose between 1 and 2 above for the value/const ref variant.

**Comment by benharsh** [comment]
I'm leaning towards option 1 where we would decide based on how the expression is used. Otherwise it may be costly (in terms of performance) to create read-only interfaces.

**Comment by bradcray** [comment]
I'm also in favor of 1.

**Comment by mppf** [comment]
@vasslitvinov - waiting to hear from you on this issue.

**Comment by vasslitvinov** [comment]
Option 1 for me, too.
