### ISSUE TITLE
Close leaks caused by arrays-of-arrays

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#5660]
The following Chapel program leaks memory, but shouldn't:

````chapel
var A: [1..10] [1..3, 1..3] real;
````

PR #5654 makes a good start at closing the leaks for this case, but fails in valgrind testing for a handful of tests, yet to be diagnosed.  See the comments on the PR for the list of tests.

**Comment by ronawho** [comment]
@mppf noted this in https://github.com/chapel-lang/chapel/pull/5654, but it seems that only module level array-of-arrays (where the inner array is anonymous leaks):

```chpl 
var a = {1..1};
var b = {1..1};

  var arr1: [1..1] [1..1] int; // leak
  var arr2: [a]    [1..1] int; // leak
  var arr3: [1..1] [b]    int; // no leak
  var arr4: [a]    [b]    int; // no leak

proc main() {
  var arr5: [1..1] [1..1] int; // no leak
  var arr6: [a]    [1..1] int; // no leak
  var arr7: [1..1] [b]    int; // no leak
  var arr8: [a]    [b]    int; // no leak
}
```

**Comment by ronawho** [comment]
And possibly related, it looks like module level anonymous array type aliases also leak: 

```chpl 
var a = {1..1};

  type vec1 = [1..1] int; // leak
  type vec2 = [a]    int; // no leak

proc main() {
  type vec3 = [1..1] int; // no leak
  type vec4 = [a]    int; // no leak
}
```

**Comment by bradcray** [comment]
@vasslitvinov , @mppf: In reviewing memory leaks for the 1.18 release notes, I was reminded of this case which seemed plausibly (though not necessarily directly related) to some of the array-of-array stuff we were discussing in the planning meeting today.  Just pointing it out in case it's an opportunity to get two birds with one (or 1-1/2) stones.

**Comment by bradcray** [comment]
It may not be higher priority than other tasks for the next sprint, but I just wanted to point it out since it seemed likely to be related to the code paths in question.

**Comment by bradcray** [comment]
Thinking about this case for a bit, I have a vague recollection of there being, some time ago at least, some games that we had to play with reference counting on arrays of arrays to prevent the inner domains from being freed prematurely.  E.g., in an array `[D] [1..10] real;` where D is `{1..0}` there aren't any outer arrays that need the inner domain at the time being; yet if the D was resized, the inner domain would definitely be needed.  So we can't free the inner domain just because it's not currently in use, but have to keep it alive due to the outer array referencing it.  This was always somewhat tangled and confusing logic.  I wonder whether something about it could simply not be firing correctly in the global context that is in the local context... (?).
