### ISSUE TITLE
Add some missing testing for the Cray module

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#5675]
Some test configurations that are missing for the cray module:

 - [ ] Add minimal registration testing for ugni
 - [ ] Beef up llvm testing
 - [ ] Add --dynamic correctness testing

**Comment by ronawho** [comment]
We should also add some testing with `--dynamic` to ensure https://github.com/chapel-lang/chapel/pull/3541 doesn't break. (Currently it's broken for gasnet-aries because we're not brining in udreg)

**Comment by bradcray** [comment]
@ronawho: Can you give me a sense of where this one stands / how important you think it is?  (I'm having trouble even parsing it).  Thanks.

**Comment by ronawho** [comment]
I updated the summary -- we still don't have testing for these configurations, but I guess you can close it if you want.

More llvm testing will fallout when we work towards making it the default, and minimal NIC registration isn't terribly important. `--dynamic` testing would be nice to make sure we're not breaking things, but `--static` is the default at most sites, so we could continue to punt on it

**Comment by bradcray** [comment]
I'm not looking to close it per se, more like trying to understand how important we consider it (e.g., should it be in the backlog (do sooner) or icebox (do later).

**Comment by ronawho** [comment]
Ah ok, I had misinterpreted the accidental closing of https://github.com/chapel-lang/chapel/issues/5457 to mean "we're trying to close unimportant issues" -- icebox for sure

**Comment by ronawho** [comment]
I'm going to close this -- we have a few tests that run without hugepages, and I think that's enough of a sanity check fo that configuration. Dynamic linking is now the default on crays, so I think that's covered too. 

We have other efforts to beef up llvm testing and make it the default so I don't think we need to track that here.
