### ISSUE TITLE
Implicit no-test detection in testing

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#5679]
Many tests use helper-modules that do not require direct compiling/executing/diffing, and consequently require a `.notest`. 

I think it would be nice to detect this automatically when a `.good` file and `.perfkeys` are not found for a given `.chpl` file, rather than require an explicit `.notest`.

**Comment by bradcray** [comment]
@ben-albrecht : While I understand what you're asking for here, given the frequency with which people check in parts of new tests while forgetting to git add other files required to run them, I worry that this would be more likely to lead to confusion ("What do you mean my test wasn't running?... oops, forgot to git add the .good file") then benefit.  I also think the cleaner solution to lots of .notest files is to put such tests into a single NOTEST directory which reduces the O(n) behavior of the testing.  I'm going to close this, though you can fight to bring it back if you find some friends to support it.

**Comment by ben-albrecht** [comment]
> While I understand what you're asking for here, given the frequency with which people check in parts of new tests while forgetting to git add other files required to run them, I worry that this would be more likely to lead to confusion ("What do you mean my test wasn't running?... oops, forgot to git add the .good file") then benefit.

That makes sense. I'm ok with keeping the existing behavior under this rationale.

>  also think the cleaner solution to lots of .notest files is to put such tests into a single NOTEST directory which reduces the O(n) behavior of the testing.

This usually bites me when I split a test out into a common module + multiple tests, and forget to add a `.notest` for the common module. If I don't end up running `start_test .` for the full directory, I won't catch that error before merging.

I do still think this is an issue, but the solution should probably be handled by the CI testing rather than changing the behavior. I will add that to #6758 and leave this closed.

**Comment by bradcray** [comment]
Or #4951 as the more specific issue...
