### ISSUE TITLE
Maintain chpl_arch.py better

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#5686]
[util/chplenv/chpl_arch.py](https://github.com/chapel-lang/chapel/blob/master/util/chplenv/chpl_arch.py) maintains a mapping of architectures to cpu ISA targeting. e.g. setting `CHPL_TARGET_ARCH=broadwell` will result in targetting `core-avx2` under intel and either `core2`, `core-avx2`, or `broadwell` under gnu (depending on the gcc version)

Unfortunately, we haven't done a good job of maintaining these mappings. For example, we're missing mappings for newer gcc's and we're missing mappings for KNL, the latest AMD chips, and probably some other things. 

For more info see the original commit that added architecture specialization: 1c3bf118717110672d4965ee0eb5ec9fc28a7c90

**Comment by ronawho** [comment]
@ben-albrecht can we add an `area: chplenv` label?

**Comment by ben-albrecht** [comment]
Seems oddly specific, but might be valuable. Are there other issues that would fit it? 

Will have to discuss with the **@chapel-lang/labels-team**

**Comment by ronawho** [comment]
Wow.. I didn't realize we had a labels team.

**Comment by ronawho** [comment]
I'd also be ok with something more generic like `util` to cover things like chplenv scripts, util/config stuff, buildRelase stuff, etc. I don't think we have a good label to characterize those things now. 

But TBH I'm not interested in starting another labels discussion, so if there's any opposition, I'll just drop it.

**Comment by ronawho** [comment]
Actually, I don't know what I was thinking by asking for a new label -- gonna delete all my comments in hopes that nobody else sees them :)

**Comment by ronawho** [comment]
@dmk42 I think you follow gcc releases and upcoming architectures pretty closely. Is this something you'd be interesting in maintaining?

**Comment by dmk42** [comment]
@ronawho You're right, I pretty much have to keep up with that information anyway, so I would be a logical person to maintain that file.  I'm willing to sign up for that.

**Comment by dmk42** [comment]
This was addressed in #9013 .
