### ISSUE TITLE
Array subscripting ambiguities

### ISSUE THREAD

**Issue by tmacd9** [chapel-lang/chapel#5688]
I've done some thinking and wonder what others think. This all started when I discovered that:

  `var A: [1..3, 1..3][0..1] int;`

  `A[1..3, 1..3][0] = 4;`

does not behave like:

```
  forall (i,j) in {1..3, 1..3} {
    A[i,j][0] = 4;
  }

```
instead:

  `A[1..3, 1..3][0] = 4;`

gives a compile time error:

error: unresolved access of '[domain(2,int(64),false)] [domain(1,int(64),false)] int(64)' by '[0]'

See the following issue for background.

  https://github.com/chapel-lang/chapel/issues/5568

So, I think this is about ambiguity in that, in this case, there's an ambiguity with the

  `[0]`

subscript operator. It could either bind with the slice expression

  `A[1..3, 1..3]`

to access a single element (however `[0]` is an incorrect subscript for a 2D array - thus the error) or it could subscript the inner array since the inner array has a `0..1` index set.  If it binds to the inner array then every element in the outer array is accessed, and the behavior is the same as the `forall` mentioned above.

The current default behavior is that the compiler binds the  ` [0]` subscript operator to the slice (outer array).  Thus, there's a difference between the `A[1..3, 1..3][0] = 4` statement and the corresponding `forall` statement mentioned above.

I did some experimenting.  Consider an array of records with two fields.

```
  record R {
    var m1: int;
    var m2: int;
  };

  var AR : [1..3] R;

  AR.m1 = 4;
```

The `m1 `field of each element of `AR `is modified.  This is expected and not surprising.

Consider tuples with two components.

`var tup = 2*int;`

It's possible to create arrays with elements that are tuples.  Consider the following two arrays of tuples:

```
var At : [1..3] tup;          // 1D array of tuples
var A2t : [1..3, 1..3] tup;   // 2D array of tuples
```

```
// no error - component 1 of all tuple elements assigned the value 9
A2t(1) = 9;

//error: type mismatch in assignment from int(64) to 2*int(64)
At(1) = 9;
```

It seems surprising that the 2D array of tuples example behaves as expected. This modifies every tuple element in the array.  The 1D array example gives an error even though it is a similar statement as the 2D array statement.  Since the () operator can also be a subscript operator, there is an ambiguity.  With a 2D array the compiler determines that

 ` (1)`

cannot be a subscript into `A2t `(thus accesses all tuple components) but with the 1D array the

  `(1)`

is treated as a subscript operator and gives an error.  The error occurs because the

  `9`

is not a tuple and is incompatible with the element type.  The compiler does not treat the access 

  `At(1)`

as accessing all elements in the array.  However, with

  `A2t(1)`

every element in `A2t `is modified.

As mentioned in the beginning, there is also an ambiguity when the element type is itself an array type, as in:

  `type inner = [0..1] int;`

To me, this seems surprising, but I do not have a solution.  In every example the element of the array is an object that has two values (record fields, tuple components, and array elements).  Yet it feels like there is a lack of closure in the language as the behavior of similar 'look-n-feel' expressions is different.

At one point I considered the following for tuples and arrays:

```
  A.(2)
  A.[0]

```
to mimic records.  I admit I have not given this idea enough consideration.  The` . ` specifies using every element in the array.

**Comment by bradcray** [comment]
Hi @tmacd9 -- At a glance, it looks like this should be attached as a follow-on to issue #5568 which I mentioned that I'd opened in response to your March 8th email query.  Would it be possible for you to file this as part of the discussion on that issue rather than creating this new one?

**Comment by tmacd9** [comment]
Moved to issue #5568
