### ISSUE TITLE
Semantic: Iterators that yield void values vs. yield nothing

### ISSUE THREAD

**Issue by daviditen** [chapel-lang/chapel#5697]
### Summary
What should happen with an iterator that does not yield anything?  It is currently a compiler error: "illegal use of a function that does not return a value".  With PR #5681 it turns into the error: "cannot iterate over values of type void".  It could be treated as if it yields a single void value.  @bradcray has suggested that void iterators should work as in this example:

```
iter yieldTenVoids() {
  for i in 1..10 do
    yield _void;
}

iter yieldAVoid() {
  yield _void;
}

iter yieldNothing() {
  writeln("In my iterator!");
}

for v in yieldTenVoids() do
  writeln("Got a void!");    // should print this message ten times

for v in yieldAVoid() do
  writeln("Got a void!");    // should print this message one time

for v in yieldNothing() do
  writeln("Got a void!");    // should not print the loop body's message at all, but should still print the iterator's message
```

**Comment by bradcray** [comment]
When I first thought about this (and commented on the PR), I thought it should collapse the loop into a no-op, but now I think it should invoke the iterator but not the loop body (as in the third iterator / loop example above).  I've edited the text in the issue description slightly to clarify this.

My personal compiler may currently just be a mess, but it seems like if I comment out the yieldNothing()-related code above and compile it today, I get an internal error...?

**Comment by vasslitvinov** [comment]
What is the motivation to allow non-yielding iterators? Would it result in allowing subtle bugs like "I meant to put a yield and forgot" or "I expect my loop body to be executed at least once and it wasn't" ?

**Comment by daviditen** [comment]
IMO the motivation is mostly orthogonality.  It is fine to write and use an iterator that doesn't yield anything dynamically, but we currently require it to have an unused yield statement:

```
iter sometimesYieldNothing(doYield: bool) {
  writeln("in sometimesYieldNothing");
  if doYield {
    yield 1;
  }
}

for i in sometimesYieldNothing(true) {}  // OK
for i in sometimesYieldNothing(false) {} // OK

iter neverYield() {
  writeln("in neverYield");
}

for i in neverYield() {} // not OK
```

I think the `neverYield()` case is analogous to the `sometimesYieldNothing(false)` case, and it seems natural to want them to be equivalent.  It's even more equivalent if the `doYield` argument is a param, so there really isn't a yield when it's false.

I don't think "I forgot to yield from my iterator" is particularly subtle, but if it turns out that it really is, maybe a warning would be better than completely disallowing non-yielding iterators?

**Comment by vasslitvinov** [comment]
@daviditen - good rationale. I am fine with it.

**Comment by daviditen** [comment]
PR #6117 was merged yesterday.
