### ISSUE TITLE
Explore ways to improve gasnet-aries performance

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#5703]
__edit__

`CHPL_COMM=ugni` is our preferred/recommended configuration for Crays, but we have been curious why gn-aries lags. https://github.com/chapel-lang/chapel/issues/5703#issuecomment-383251070 has a good summary of the currently known differences.

---

Our ugni comm layer significantly outperforms gasnet-aries for most of our multi-locale benchmarks. Here's a few [demonstrative graphs](http://chapel.sourceforge.net/perf/16-node-xc/?startdate=2017/03/12&enddate=2017/05/31&graphs=hpccfftperfgflopsn220,hpcchplhpccversionperfgflopsn22knb200,hpccptransperfgbsecn2000nb100,hpccrarmoperfgupsn233nu10m,sscassca2kernel4secsize2224vertices,doeluleshdensetimesecsedov15oct,doeminimdtimesecsize20). It's a little surprising how significant the performance advantage is sometimes, and I wonder if there's simple changes we could make to improve gasnet's performance (i.e. configure options, env vars, etc.)

Known TODOs 

- [x] try `--enable-gni-multi-domain` with `GASNET_DOMAIN_COUNT=<~numCores>`
- [ ] use network AMOs when they come online (noted in https://github.com/chapel-lang/chapel/issues/5796#issuecomment-289111820)
- [ ] improve affinity (for ugni we achieved this with dynamic registration)
- [ ] reduce contention from the polling thread (#9067)

Misc things to experiment with (from http://legion.stanford.edu/gasnet/):
- [ ] try using --with-segment-mmap-max=<#>GB
- [ ] experiment with `GASNET_NETWORKDEPTH`, `GASNET_NETWORKDEPTH_TOTAL`, `GASNET_GNI_NUM_PD` , and `GASNET_GNI_MEMREG`?

**Comment by ronawho** [comment]
@gbtitus just fyi for now. post-release I'll do some performance experiments.

**Comment by ronawho** [comment]
Should also look into `--enable-gni-firehose`

**Comment by ronawho** [comment]
Huh, and it looks like gasnet 1.26.2 had a lot of gemini/aries improvements. Cool! I should follow their release notes more carefully:

```
----------------------------------------------------------------------
05-12-2016 :  Release 1.26.2

* Cray uGNI (gemini- and aries-conduits)
  - Allow configure and build without use of the Cray wrapper compilers
  - Use Cray's UDREG library to ammortize cost of dynamic registration
  - Maximum supported process count doubled to 2^24 (16 million)
  - Maximum AM Medium payload increased from 960 to 4032 bytes without
    a corresponding increase in the buffer allocation footprint
  - Maximum AM Long payload raised to 8MB on Aries (still 1MB on Gemini)
  - Multiple changes to reduce startup overheads
  - Fixes for C99 code compilance

```

**Comment by ronawho** [comment]
I took a quick look at `--enable-gni-multi-domain`for ra-rmo. It actually has a really significant performance impact. I see up to a 15X improvement for ra-rmo, which puts it around 1/2 as fast as ugni currently is. 

With just `--enable-gni-multi-domain` there's a 75% slowdown, but then bumping GASNET_DOMAIN_COUNT we see significant improvements: 


```
# Date  Execution time =        Performance (GUPS) =    Validation:

# default
03/22/17        3.65028         0.00273951      SUCCESS
03/22/17        3.7682          0.00265379      SUCCESS
03/22/17        3.71216         0.00269385      SUCCESS

# --enable-gni-multi-domain
03/22/17        5.03811         0.00198487      SUCCESS
03/22/17        5.06251         0.00197531      SUCCESS
03/22/17        5.10423         0.00195916      SUCCESS

# --enable-gni-multi-domain (GASNET_DOMAIN_COUNT=14)
03/22/17        0.396523        0.0252192       SUCCESS
03/22/17        0.369807        0.0270411       SUCCESS
03/22/17        0.43501         0.022988        SUCCESS

# --enable-gni-multi-domain (GASNET_DOMAIN_COUNT=28)
03/22/17        0.280913        0.0355982       SUCCESS
03/22/17        0.319765        0.031273        SUCCESS
03/22/17        0.28043         0.0356595       SUCCESS

# --enable-gni-multi-domain (GASNET_DOMAIN_COUNT=31) -- match ugni
03/22/17        0.254694        0.0392628       SUCCESS
03/22/17        0.264881        0.0377528       SUCCESS
03/22/17        0.249612        0.0400622       SUCCESS

# --enable-gni-multi-domain (GASNET_DOMAIN_COUNT=56) -- doesn't add much
03/22/17        0.303831        0.032913        SUCCESS
03/22/17        0.306379        0.0326393       SUCCESS
03/22/17        0.239301        0.0417884       SUCCESS
```

**Comment by ronawho** [comment]
At some point I'll do a full multi-locale perf run with `--enable-gni-multi-domain` and add a summary of what I find.

**Comment by gbtitus** [comment]
Maybe we should have our comm=gasnet layer set GASNET_DOMAIN_COUNT=numThreadsPerLocale itself.  This is effectively the same thing we do in comm=ugni when we select the number of comm domains, and equivalent to how we parameterize Qthreads by setting its env vars to drive its behavior.

It might also be worthwhile to consider if we could co-design and contribute a network atomics capability to GASNet, and then relieve ourselves of the burden of maintaining comm=ugni (though that may have a limited remaining lifespan anyway due to network hardware evolution, so perhaps putting too much explicit effort into retiring it would be a mistake).  Or contribute more directly to Sung's libfabric-based Chapel comm layer so as to be sure that it can provide both performance and network atomics.

**Comment by ronawho** [comment]
Agreed about setting GASNET_DOMAIN_COUNT=numThreadsPerLocale in our shim.

Unfortunately setting GASNET_DOMAIN_COUNT isn't always a win. I did a full run and there were some significant regressions for a lot of tests too

Regressions:
 - lulesh is 4X slower
 - fft is 3X slower
 - hpls are 3X slower 
 - ra-atomic and ra-on are 2X slower
 - SSCA is 50% slower

Improvements:
 - ra-rmo is 15X faster
 - ptrans is 4X faster
 - MiniMD is 3X faster 
 - stencil-prk is 2X faster

**Comment by ronawho** [comment]
Some misc other configure options/ env vars to try out:
 - avoid `--disable-aligned-segment` on crays
 - add `--with-segment-mmap-max=<#>GB`
 - try `GASNET_NETWORKDEPTH `, `GASNET_NETWORKDEPTH_TOTAL`, `GASNET_GNI_NUM_PD` , `GASNET_GNI_MEMREG`

Based on what legion recommends: http://legion.stanford.edu/gasnet/

**Comment by ronawho** [comment]
I added a central list of TODOs to the issue description. It includes the ones mentioned in comments as well as a note to checkout GASNet's network AMOs as they come online.

@PHHargrove thanks for the pointer to the AMO work. I'm curious how "experimental" the `--enable-gni-multi-domain` support is. Would you avoid using it in production, and if so is there any future work planned to make it non-experimental?

**Comment by PHHargrove** [comment]
The `--enable-gni-multi-domain` feature (to be renamed `--enable-{gemini,aries}-multi-domain` in the next GASNet release), is stable (ready for production), but as seen in this Issue its performance is not always an improvement over the default (thus it remains OFF by default).

It should worth use in production for workloads dominated by Put and Get traffic, for which it can reduce injection overhead by reducing pthread mutex contention in the critical path.  However, for AM-dominated workloads there is a performance regression due to the  way the domains share the AM path.

The performance of AM-heavy workloads *might* be improved by adjusting the value of the following env var:
```
   GASNET_AM_DOMAIN_POLL_MASK
   This value controls how often threads in domains other than the
   first poll for arrival of Active Messages (threads in the first
   domain poll on every call to gasnet_AMPoll).  Since all Active
   Message traffic arrives via the first domain, polling by more than
   one thread will increase lock contention, but a total lack of
   polling by threads in other domains can lead to deadlock in some
   circumstances.
   A value of 0 will result in polling for Active Messages on every
   call (explicit or implicit) to gasnet_AMPoll().
   Values of 1, 3, 7, 15, etc. will result in progressively lower
   average frequencies (1 in (n+1)).
   The default is 255 (1 in every 256 polls by threads outside the
   first domain will poll for AM arrivals).
```

It is also worth noting that if `GASNET_DOMAIN_COUNT` is less than the number of threads, then the threads will be placed "round robin" into the domain by default.  Since the threads in a given domain share a pthread mutex, this may mean distant cores.  So, one might also want/need to set `GASNET_GNI_PTHREADS_PER_DOMAIN` to threads/domains if one wants "blocked" layout to get sharing of the mutex among _consecutively_ numbered cores.

**Comment by PHHargrove** [comment]
In my previous comment I neglected to answer Elliot's question regarding plans to make multi-domain support non-experimental:

We are working on getting the first Beta of GASNet-EX out the door by the end of June.  While it won't appear in _that_ release, one of the big changes in GASNet-EX is the concept of multiple "endpoints" which will allow each thread to have an individual communications context *at the GASNet-EX API level*.  This will subsume the current under-the-covers multi-domain support, but reuse much of the implementation.  The current bottleneck for AM communication will be greatly reduced, or eliminated entirely, in that design because each thread will be able to have an independent AM channel, rather than a shared one.

While I cannot promise, that "multi-endpoint" work _may_ be available for Aries in the Dec 2017 timeframe.  However, I should warn you that GASNet-EX is a new API - not just extensions to GASNet.  So, some "porting" work will be required.  Since the new API is "a semantic superset" of GASNet-1, no major redesign will be needed on the Chapel side until/unless one wants to use new features (like per-locale endpoints).  Additionally, all but a few uncommonly-used features of GASNet-1 are implemented in terms of GASNet-EX by a shim layer we are providing to enable conversion of GASNet-1 clients to the GASNet-EX API _incrementally_ (supporting a mix of calls to the two APIs).

**Comment by ronawho** [comment]
Great, thanks @PHHargrove!

Do you have any interest in getting follow-ups for ugni vs gasnet-aries performance comparisons (either now or if/when we switch to the GASNet-EX API?)? i.e. are ugni vs. GASNet performance comparisons useful/interesting to you?

**Comment by PHHargrove** [comment]
@ronawho, In the near-term we are focusing nearly all our effort on getting a _correct_ implementation of GASNet-EX, that won't even be feature-complete for a while yet.  So, performance optimization is not a top priority at the moment.

However, we will definitely want to understand the **sources** of the performance differences.  If they are due entirely to the generality of GASNet, as opposed to a tailored-specificially-for-chapel runtime then there is not likely much we can do to close the performance gap.  However, to the extent that your ugni backend may have been written by folks with better knowledge of the API (or better access to those with the knowledge), there could be much for us to learn from the differences.  *That* is something that we should examine while our implementation work is still fluid enough to change.

So, I guess the question I should ask first is: do you have profiling info that can show where in GASNet's aries-conduit most of "lost time" lives, when compared to similar operations using your native ugni backend?  In other words: "do you know yet _why_ GASNet is slower?"

**Comment by ronawho** [comment]
ATM, we don't have useful stats for you as far as why GASNet is slower. As part of this effort to explore improving gasnet-aries performance I'm hoping to gather that sort of information, and I was trying to get a sense of whether that'd be useful and worth reporting back to you or if you're busy with other work.

So I'll plan on exploring some of these improvements and digging into profiling differences, and if I find anything that might be interesting or could lead to performance insights in GASNet I'll @mention you just as a light-weight heads up, but don't feel the need to follow this thread otherwise.

**Comment by ronawho** [comment]
`GASNET_DOMAIN_COUNT=<num_cores+1> GASNET_AM_DOMAIN_POLL_MASK=3` seems to be pretty close to the sweet spot for us. I still see significant improvements for ra-rmo, and most benchmarks that were regressing with just GASNET_DOMAIN_COUNT (lulesh, fft, hpl) are performing much better than master

Regressions:
 - fft is 50% slower (down from 3x slower w/o GASNET_AM_DOMAIN_POLL_MASK) 
 - ra-atomic and ra-on are 50% slower (down from 2x slower w/o GASNET_AM_DOMAIN_POLL_MASK)

Improvements:
 - hpl is 2X faster
 - lulesh is 2.5X faster
 - miniMD is 3.5X faster
 - ptrans is 4X faster
 - ra-rmo is 20X faster

some of the improved cases now perform on par with ugni, though there are still cases where ugni significantly outperforms gasnet-aries

**Comment by ronawho** [comment]
Parking the main process (https://github.com/chapel-lang/chapel/pull/8533) instead of having it spin in a `chpl_comm_barrier()` significantly helped some benchmarks for gn-aries: https://chapel-lang.org/perf/16-node-xc/?startdate=2018/02/12&enddate=2018/03/01&graphs=hpccptransperfgbsecn2000nb100,hpccrarmoperfgupsn233,doeminimdtimesecsize20

**Comment by ronawho** [comment]
Contention/interference from the polling thread was increased with specte/meltdown patches: https://chapel-lang.org/perf/16-node-xc/?startdate=2018/02/22&enddate=2018/03/10&configs=gnugasnetaries,gnugasnetmpi&graphs=npbepperfmopssized,hpccrarmoperfgupsn233,hpccglobalstreamperfgbsn5723827200,prkstencilvariationsperf,emptyremotetaskspawntime

For `CHPL_COMM=ugni` we resolved this by using a blocking CQ for the progress thread. https://github.com/chapel-lang/chapel/issues/9067 is still open to track coming up with a solution for gasnet.

**Comment by ronawho** [comment]
Here's my current understanding of why gasnet-aries lags behind ugni:

* Lack of network atomics (should fallout with a real EX upgrade):
   * impacts RA-atomics, and remote-atomic microbenchmark: [graphs](https://chapel-lang.org/perf/16-node-xc/?startdate=2018/02/18&enddate=2018/04/20&graphs=hpccraatomicsperfgupsn233,remoteamoperformance)


- Contention from polling thread: 
  - impacts NPB EP, RA-rmo, HPL (close to ugni before spectre/meltdown): [graphs](https://chapel-lang.org/perf/16-node-xc/?startdate=2018/02/18&enddate=2018/04/20&graphs=npbepperfmopssized,hpcchplreleaseperfgflopsn255nb32,hpccrarmoperfgupsn233)
  - impacts fast-on microbenchmark (code executed in AM handler vs. forked task): [graphs](https://chapel-lang.org/perf/16-node-xc/?startdate=2018/02/18&enddate=2018/04/20&graphs=remoteexecuteonperformance,remotefastexecuteonperformance)


* poor affinity (because we run 1 client per node, and all memory is alloc/pinned/registered at start):
   * impacts Stream, ISx, PRK-Stencil: [graphs](https://chapel-lang.org/perf/16-node-xc/?startdate=2017/07/03&enddate=2018/04/20&graphs=hpccstreamepperfgbsn5723827200,hpccglobalstreamperfgbsn5723827200,hpccpromotedstreamperfgbsn5723827200,prkstencilvariationsperf)
   * ugni performance for these benchmarks was equally slow before dynamic registration


- Slower AMs:
  - impacts RA-on, and on-stmt microbenchmarks: [graphs](https://chapel-lang.org/perf/16-node-xc/?startdate=2018/02/18&enddate=2018/04/20&graphs=hpccraonperfgupsn233,remoteexecuteonperformance,remotefastexecuteonperformance)
  - not sure what root cause is, gasnet AM code grabs a mutex, but probably more to it than that

I am pretty confident about the above differences. There are a few benchmarks where I don't completely understand the root cause (mostly because I don't understand the benchmarks well enough to be able to characterize them): 
 - lulesh, ssca2, fft: [graphs](https://chapel-lang.org/perf/16-node-xc/?startdate=2018/02/24&enddate=2018/04/27&graphs=hpccfftperfgflopsn220,sscassca2kernel4secsize1624vertices,doeluleshdensetimesecsedov15oct)

I think fft is on-stmt heavy, though I'm not positive. lulesh and ssca2 were hurt by the spectre/meltdown update, so presumably resolving interference from the progress thread would restore a little performance there. SSCA may also benefit from network atomics? SSCA benefitted from a change that increased at AM rate, so I would guess faster on-stmts/AMs would help.

**Comment by PHHargrove** [comment]
Thank you very much @ronawho  
That information will be quite valuable to us.

**Comment by ronawho** [comment]
Closing, XC is effectively in maintenance mode at this point now that we're shifting our focus to EX and I don't think we'll have much time or motivation to look into this more (note that we're still interested in these types of comparisons like say native `CHPL_COMM=ofi` vs `CHPL_COMM=gasnet` with the ofi conduit on SS11, it's just for XC specifically that I don't think we'll continue to investigate.
