### ISSUE TITLE
Scripting to help understand/manage configurations

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#5743]
At present, when compiling for a 'chplenv' configuration that the runtime was not built for, the user gets a message like:

````
/Users/bradc/chapel/runtime/etc/Makefile.include:127: *** The runtime has not been built for this configuration. Check $CHPL_HOME/util/printchplenv and try rebuilding with 'make' from $CHPL_HOME.  Stop.
````

It'd be nice to improve this situation in a few ways:

* provide a script that characterizes which runtime configurations are currently built.  Ideally, this might provide an ASCII-based tree view of the current configuration choices.

* provide a second script that could "diff" your current configuration and those that are available and say something about where the  mismatches occur and/or what "close" configurations are to the one you currently have.

* make use of these scripts in the Makefile above to provide more context in the error message than we currently do.

**Comment by bradcray** [comment]
I find myself wanting this whenever helping a user debug this error message.  Today it came up when trying to figure out why the Cray module didn't work on a non-Cray whitebox and trying to understand the differences between my printchplenv and what the Cray module provides.

**Comment by bradcray** [comment]
@awallace-cray: This is the issue that I was thinking of in our discussion about helping users / sysadmins reason about "missing" or "mismatched" configurations today.

**Comment by awallace-cray** [comment]
CHPL_DEVELOPER already gets the missing lib path. This would show it to non-developers too.
```
diff --git a/runtime/etc/Makefile.include b/runtime/etc/Makefile.include
index 983eccc136..d1ac4879a2 100644
--- a/runtime/etc/Makefile.include
+++ b/runtime/etc/Makefile.include
@@ -150,9 +150,7 @@ printclangcxx:
 
 checkRtLibDir:
 ifeq ($(wildcard $(CHPL_RT_LIB_DIR)),)
-ifdef CHPL_DEVELOPER
-       $(warning Expected runtime library in $(CHPL_RT_LIB_DIR))
-endif
+       $(warning *** Missing runtime library:$(subst $(CHPL_HOME),.,$(CHPL_RT_LIB_DIR)))
 ifeq ($(CHPL_MODULE_HOME),$(CHPL_HOME))
        $(error The requested configuration is not included in the module. \
                Please send the package maintainer the output of \
```

**Comment by bradcray** [comment]
I don't have an opinion about this proposed change, other than not considering it satisfactory for the typical user or for closing this issue.

**Comment by bradcray** [comment]
I'm going to close this due to recent awesome work by @jhh67, though I do still hope it will get integrated into `printchplenv` rather than being its own script (#19020).
