### ISSUE TITLE
use-only statement support for generic functions

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#5833]
The following program fails to resolve the generic function `bar(x)`:

```chapel
use B only foo;
foo('hello');

module B {
  proc foo(x) {
    bar(x);
  }
  proc bar(x) {
    writeln(x);
  }
}
```

However, the non-generic equivalent works as I would expect:

```chapel
use B only foo;
foo('hello');

module B {
  proc foo(x: string) {
    bar(x);
  }
  proc bar(x: string) {
    writeln(x);
  }
}
```

```bash
> chpl a.chpl && ./a.out
hello
```

**Comment by lydia-duncan** [comment]
As Ben points out, the problem is that we are creating a generic instantiation for foo at the location of the call and trying to resolve the call to bar from there, when bar is not visible from that code location.  This is an issue with our "point of instantiation" rules.

**Comment by benharsh** [comment]
The first program appears to be working (not sure what enabled it) - can either of you confirm?

**Comment by ben-albrecht** [comment]
Confirmed. Think it's worth checking in a test for this?

**Comment by benharsh** [comment]
Yeah, I'll add one if I can't find a pre-existing test.
