### ISSUE TITLE
Type function that returns a tuple type from a condional expression gets compiler error

### ISSUE THREAD

**Issue by daviditen** [chapel-lang/chapel#5835]
### Summary of Problem
A type function that returns a tuple type from a conditional expression gets compiler errors  about values where types are expected.

### Steps to Reproduce

**Source Code:**
```chapel
param useInt = false;

proc getType(type t) type {
  return if useInt then int else t;
}

var a: getType(2*int);
writeln(a.type:string);
```

**Compile command:**
```
chpl tupleTypeInParamCondExpr.chpl
tupleTypeInParamCondExpr.chpl:3: In function 'getType':
tupleTypeInParamCondExpr.chpl:4: error: illegal return of value where type is expected
```

**Associated Future Test(s):**
test/functions/diten/tupleTypeInParamCondExpr.chpl

**Comment by daviditen** [comment]
@mppf notes that this code works:

```chapel
param useInt = false;

proc getType(type t) type {
  return if useInt then int else 2*int;
}

var a: getType(2*int);
writeln(a.type:string);
```

So the problem is related to returning a tuple _argument_ from a conditional expression, not just any tuple.

**Comment by daviditen** [comment]
A simplification - any type alias used in a type-cond-expr causes an equivalent failure:

```
param useInt = false;
type t = real;
type t2 = if useInt then int else t;
```

`typeCond.chpl:3: error: illegal assignment of value to type`

Returning the cond-expr from a function instead of assigning it to a type variable results in the original error.

**Comment by daviditen** [comment]
This worked in 1.14, so I did a binary search for the PR that it started failing after. It started failing after `a9a5e95` PR #4762 .

**Comment by mppf** [comment]
Right, I had to change some things to do with if-exprs to get them to work with arrays.

**Comment by DanilaFe** [comment]
The following programs both compile on `main` today:

```Chapel
param useInt = false;

proc getType(type t) type {
  return if useInt then int else t;
}

var a: getType(2*int);
writeln(a.type:string);
```

```Chapel
param useInt = false;
type t = real;
type t2 = if useInt then int else t;
```

And `test/functions/diten/tupleTypeInParamCondExpr.chpl` passes (is not a future). Closing as completed.
