### ISSUE TITLE
Update third-party/utf8-decoder

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#5897]
Trivial in both effort and impact, but it's worth noting that an update was published in 2010: 
http://bjoern.hoehrmann.de/utf-8/decoder/dfa/

**Comment by ben-albrecht** [comment]
@ronawho points out that the latest version is actually a variation on the original decoder, so it's not 100% clear whether or not we want to use the improved variation.

**Comment by ronawho** [comment]
Like ben mentioned the 2010 update was to a "variation", not the main implementation. 

The variation "may" be every so slightly faster, but the current version has served us well for years, so I don't really want to change it to a variation that hasn't been as tested.
