### ISSUE TITLE
Improve Pygments Support

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#5900]
This issue is meant to track bugs in pygments / chpl-doc html-ifying in RST containing
```
.. code-block:: chapel
```

**Comment by mppf** [comment]
I noticed that this doesn't get highlighted:
```
.. code-block:: chapel

  proc f() ref {
    return A;
  }
```



and it does if I make the name longer (f -> returnsArrayByRef e.g.)

**Comment by ben-albrecht** [comment]
@mppf  - note that GitHub also uses pygments, so this can be better demonstrated by just code-blocking the snippet:

```chapel
proc f() ref {
  return A;
}
```

**Comment by ben-albrecht** [comment]
Also, here's [Chapel's Pygments lexer](https://bitbucket.org/birkenfeld/pygments-main/src/7941677dc77d4f2bf0bbd6140ade85a9454b8b80/pygments/lexers/chapel.py?at=default&fileviewer=file-view-default) for reference.

**Comment by mppf** [comment]
but... it highlights in github but not in the rst.

**Comment by ben-albrecht** [comment]
I was mistaken, GitHub uses [linguist](https://github.com/github/linguist) for syntax detection which ends up using our [tmBundle](https://github.com/chapel-lang/chapel-tmbundle/).

What about the original code snippet doesn't get highlighted correctly? Trying with the latest release of pygments (2.2.), I get different highlighting on the function name and the ref for `pygmentize -l chapel f.chpl` in:

```chapel
proc f() ref { // ref is not colored, f is colored
  return A;
}
```

vs.

```chapel
proc ff() ref {  // ref is the same color as proc, ff is not colored
  return A;
}
```

**Comment by mppf** [comment]
Needs owned/shared/unmanaged/borrowed/override

**Comment by mppf** [comment]
So, https://bitbucket.org/birkenfeld/pygments-main/pull-requests/735/updating-chapel-highlighter/ is updated to close this issue, but that PR has been open for more than a year.

Asking on the recommended IRC channel, they say "contributing doesn't often go anywhere ... There is a single maintainer and he doesn't seem to be doing much with the project."

**Comment by mppf** [comment]
pygments-main PR 735 has been merged, so I'm closing this issue.
