### ISSUE TITLE
Problems with conditional expressions in initializers

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#5935]
### Summary of Problem

I expected that conditional expressions would be supported in phase I of initializers since they don't introduce control flow that would confuse whether or not the field is being initialized.  However, instead they result in an error message and one that isn't clearly related to the conditional expression:

````
error: initializers cannot return a value
````

My wild guess is that we implement the conditional expression as a nested function and that the compiler is incorrectly assuming that the return within that nested function implies that there's a return in phase I.  If so, this may be a five-minute fix.

### Steps to Reproduce

**Source Code:**

```chapel
class C {
  const x: real;

  proc init(flag: bool) {
    x = if flag then 1.2 else 3.4;
    super.init();
  }
}
```

**Compile command:**
``chpl foo.chpl -o foo``

**Associated Future Test(s):**
``test/classes/initializers/initViaConditional.chpl``

### Configuration Information

- Output of `chpl --version`: 1.15.0.6a45818

**Comment by bradcray** [comment]
Here's another code that runs into similar issues:

````chapel
  proc init(colors: [?colorSpace]) {                                            
    chameneos = for i in colorSpace do new Chameneos(i, colors[i]);             
  }                                                                             
````

(probably for similar reasons)

**Comment by bradcray** [comment]
@lydia-duncan : This seems like a potential candidate for a five-minute fix...  Have you had a chance to look into it at all?  I seem to keep running into it when I write initializers.

**Comment by lydia-duncan** [comment]
My gut says that this won't be too hard to fix, either, but I haven't taken a deep look at what it would take to solve it yet.  Sorry you keep running into it, I'll bump it up my queue if Mike doesn't get to it first!
