### ISSUE TITLE
Querying compile-time properties of types

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#5937]
Should the following be valid Chapel?

```chpl

class X {
  type eltee;
  param strided;
  param rank;
}

proc printer(type T) {
  writeln(T.eltee:string);
  writeln(T.strided);
  writeln(T.rank);
}

proc main() {
  var A : X(int, false, 1);
  var B : X(int, true, 3);

  printer(A.type);
  printer(B.type);
}
```

There are places in our internal modules where we create temporaries from a type argument to get information that we could have known at compile-time. For example, we have an array helper routine that increments domain ref counts for inner arrays. It looks a bit like this:
```chpl
proc incRefHelper(parentArr, type eltType) {
  if isArrayType(eltType) {
    var temp : eltType; // potentially expensive!
    temp.domain._ref_count_helper();
    incRefHelper(parentArr, temp.eltType);
  }
}
```

It would be nice if we could just say ```eltType.eltType``` at the end, instead of relying on a temporary. I'd also argue that in the case of arrays we should be able to query the domain from the type, but that's probably best for a separate discussion.

**Edit**: updated code to cast type to string

**Comment by mppf** [comment]
A related case is querying for a tuple size:
``` chapel
proc getSize(type t) param {
  return t.size;
}

param sz = getSize( 2*int );
writeln(sz);
```

results in a compilation error currently but it seems that it ought to work.

**Comment by lydia-duncan** [comment]
I support the ability to access compile time fields in a manner similar to the accessing of other fields.

**Comment by mppf** [comment]
AFAIK these ought to be 'type methods' but type fields / param fields pre-date the type method. I'd look in to if the element accessor methods for these generated in buildDefaultFunctions can be changed to type methods.

**Comment by bradcray** [comment]
I have a vague memory that @lydia-duncan may have filed some feature request futures against this while working on noinit / default values some time ago...

**Comment by lydia-duncan** [comment]
Yup!  I think Michael's PRs are fixing them
