### ISSUE TITLE
Chpldoc accidentally associates a multiline comment with a symbol preceded by a single line comment

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#5943]
### Summary of Problem
Multiline comments are always considered relevant to the next symbol which follows them, even if there is a single line comment in between the multiline comment and the symbol in question. Ideally, the presence of an interrupting non-documentation comment would cause the documentation comment to be ignored.

### Steps to Reproduce

**Source Code:**

```chapel
/* This long comment shouldn't get attached to foo, because there is a single
   line comment in the way */

// Blocking!
proc foo() {

}
```

**Compile command:**
`chpldoc foo.chpl`

**Associated Future Test(s):**
test/chpldoc/basics/interruptingSingleComment.doc.chpl

### Configuration Information

- Output of `chpl --version`:
Chapel 1.13.0 and on (still present in Chapel 1.15.0)

**Comment by immadisairaj** [comment]
Hello, I tried to reproduce this issue and think this issue is still there. I would like to work on this issue. Can I get some tips from where to start with this issue to solve.

**Comment by lydia-duncan** [comment]
That'd be great!  I think you want to look at processSingleLineComment and processBlockComment in compiler/parser/chapel.lex.

Note that you'll need flex installed on your system and to call `make parser` followed by `make compiler` to see the result of changes to this file.  This will cause `flex-chapel.cpp` and likely `bison-chapel.cpp` (depending on your version of bison installed) to be updated, which the parsing pass in compilation relies on.

**Comment by immadisairaj** [comment]
Hello,
After vigorously searching the code base I found where the description of a module is taken. It is being taken by using the comments which comes before any modules. So, the problem was the latest comment just takes only block comments and leaves single line comments.
The code for that is [here](https://github.com/chapel-lang/chapel/blob/134c66c23e4fdff781b0da5c708030dacaf53a29/compiler/parser/parser.cpp#L608).

So, a solution can be to also track single line comments along with block comments. I've tried it and it worked fine. I wanted to know if there are any cases that are going to be failed with this solution.

**Comment by lydia-duncan** [comment]
I don't think that's the solution we want to follow.  See the [chpldoc primer](https://chapel-lang.org/docs/latest/primers/chpldoc.doc.html)

**Comment by immadisairaj** [comment]
Then maybe we can make the 'latestComment' to plain text whenever we encounter a single line comment as single line comments are not used in documentation right.

I've tried with all the methods in the chpldoc primer and it worked fine.

**Comment by lydia-duncan** [comment]
> Then maybe we can make the 'latestComment' to plain text whenever we encounter a single line comment as single line comments are not used in documentation right.

You mean, we clear out the latestComment field when we encounter a single line comment, right?  I think that would work.  Have you tried running all the tests under test/chpldoc?

**Comment by immadisairaj** [comment]
> Have you tried running all the tests under test/chpldoc?

Yeah I have tried testing and all the tests were passing as expected
