### ISSUE TITLE
Split 'ReplicatedDist' primer into its own file

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#5955]
In reviewing ReplicatedDist and its primer today, I think it ought to be split into its own primer separate from distributions (and perhaps DimensionalDist should as well, though I'm uncertain and didn't review that part).  ReplicatedDist is sufficiently different and unique from things like Block, Cyclic, and Block-Cyclic that I think breaking it out would be beneficial.  I'd call the primer replication.chpl and have it cover UtilReplicatedVar as well.  I'd have the distributions.chpl primer cross-reference it so that readers would be aware of it, but that it wouldn't bog down the distributions primer (as it feels like it currently does).

**Comment by bradcray** [comment]
(This effort should not be undertaken before PR #5933 is merged due to certain conflicts...)

**Comment by cassella** [comment]
This was done in #6682 though the primer's named `replicated.chpl`, and it has no mention of UtilReplicatedVar.

**Comment by bradcray** [comment]
Thanks Paul!  (the lack of documentation on UtilReplicatedVar was intentional...).
