### ISSUE TITLE
Internal error from insertWideReferences and task intents

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#5957]
### Summary of Problem

While working on improving the implementation of ReplicatedDist, I ran into an internal error in the insertWideReferences pass related to task intents for a code pattern that seemed fairly innocuous.  I haven't determined whether ReplicatedDist itself plays a role in this bug or not.

### Steps to Reproduce

**Source Code:**

The key idiom is:

```chapel
coforall loc in Locales do
  on loc do
    forall ra in RA do
      ra = here.id;
```

where ``RA`` is an array distributed by ReplicatedDist, but see the future for a complete example.

**Compile command:**
``chpl foo.chpl -o foo``

**Associated Future Test(s):**
``test/distributions/replicated/repl-int-error.chpl``

### Configuration Information

- Output of `chpl --version`: 1.15.0.54e8a05

**Comment by bradcray** [comment]
@vasslitvinov (and possibly @benharsh):  Based on a quick glance, this seems likely to be something you'd be able to diagnose better than I have.

**Comment by benharsh** [comment]
This is almost certainly on me, I'll start looking into it.

**Comment by benharsh** [comment]
The compile-time error should be fixed by #5967 , but I was getting a .good mismatch during testing. @bradcray , did you create the .good file when on your replicated-rework branch?

**Comment by bradcray** [comment]
> did you create the .good file when on your replicated-rework branch?

Yeah, I noted in the PR that the .good was designed for the new replicated dist world (I was betting I'd get my PR in first, but it seems I was being naive...).  Staging your PR after mine might be simplest.

**Comment by benharsh** [comment]
Merging after the replicated changes go in sounds fine to me.

**Comment by benharsh** [comment]
#5967 has been merged and this issue is now resolved.
