### ISSUE TITLE
Bump release number just after a release, not just before it

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#5963]
This issue is designed to capture our longstanding intention to bump release numbers just after making a release, and not just before it.  The goal of doing so is to make intermediate versions of Chapel that people build from GitHub look more like a logical step between releases and not a version of the last public release.  In doing so, we also want to clearly mark such version numbers as being "pre-release" versions -- i.e., not to be confused with the official release to come.

What do we need to change in order to reach this point?
- [x] compiler should have the capability of printing "(pre-release)" after the --version output when appropriate (prototyped in PR #5962)
- [x] docs/master/ should similarly have its version number documented as "(pre-release)" and/or not use a version number at all and use a different tag like "master"
- [x] what READMEs / rst's should be similarly decorated and updated?
- [ ] ...?

**Comment by bradcray** [comment]
Attn: @awallace-cray -- let's land this one this time

**Comment by bradcray** [comment]
@ben-albrecht: May need your help with the documentation piece.

**Comment by awallace-cray** [comment]
Though simple enough in principle, there are a lot of details left to decide, many of which will need to be verified: (builds and test scripts work? cray.chapel.com links? Cray modules?)

I think a good approach would be a feature branch on my chapel fork, using a sandbox Jenkins instance.

**Comment by ben-albrecht** [comment]
Just a quick thought on building the docs: 

Since the docs-build requires chpldoc, and chpldoc requires the Chapel compiler to be built, both the docs Makefile and `conf.py` could rely on calling `chpl --version` to get the string to display for version number, and could behave different if the string has `pre-release` in it.

Off the top of my head, the docs-dependencies on release version are:

- `doc/Makefile` : `CHPL2RSTOPTS*`
    - should be `release/<version>` for releases and `master` for pre-releases
    - we could potentially put these values into a sphinx variable so that the Makefile doesn't have to query the release version
- `doc/rst/conf.py`: `shortversion` (this is the string displayed in top-left), `release`
- `chplenv.rst` and `QUICKSTART.rst` use the current version number, but these should depend on the sphinx variables rather than be hard-coded...

**Comment by bradcray** [comment]
> there are a lot of details left to decide

My goal in opening this issue was to start identifying and making those decisions rather than putting them off for another release cycle (which is what the '...?' in the issue was meant to cover).  That said, I don't understand what they are from your description:

> builds and test scripts work? cray.chapel.com links? Cray modules?

Can you provide more detail on what you're anticipating?  Thanks.

**Comment by awallace-cray** [comment]
Ben's comment is a great example. Anyway, my comment was not meant to put anything off. On the contrary, starting on an actual implementation seems a concrete way to reach your goal.

**Comment by bradcray** [comment]
> Ben's comment is a great example.

Ben's comment addresses an item already in the TODO list (#2 concerning tagging chpldocs).  I'm wondering what else is missing from the TODO list (you seemed to have some things in mind)

> starting on an actual implementation seems a concrete way to reach your goal.

For pieces that don't require modifying the compiler or chpldocs, I'd ideally like this to be your goal/issue rather than mine.  In PR #5962 I've prototyped the compiler's piece of it.

Other than wondering what we're missing, we need to construct the list of READMEs/rsts that we'd want to maintain a '(pre-release)' tag on which will require revving them twice as often: Once just after the release to add the tag and bump the version number; once just before the release to remove the '(pre-release)' tag.  This is presumably some subset of the files touched in #5775.  Should it be all of them?  (I haven't taken the time to go through them yet to form an opinion, but if either of you do...).

**Comment by ben-albrecht** [comment]
For #5775, I think everything should be updated to 1.16.0, except:

- `conf.py` : `shortversion = 1.16.0 pre-release`
    - This should be parsed from `chpl --version` if possible
- `QUICKSTART.rst` & `chplenv.rst`
    - Updating the version here would point users to a tarball that doesn't exist... Maybe this should stay 1.15.0
    - To reduce maintenance, we could add a `|lastversion|` sphinx-var, so that this consistently points to the previous version
- `man/conf*.rst`: these should be `1.16.0 pre-release`
    - It would be nice if the Makefile parsed `chpl --version` and set these automatically
- `README.testing` should continue to point to last release.
    - Once developer documentation is rendered online, we can point to the `latest` version there.

**Comment by ben-albrecht** [comment]
@awallace-cray - I can handle the stuff inside `doc/` if you'd like. I think I can have the `conf.py` parse the version from `chpl --version` and plug it into what I was earlier calling sphinx variables, but have now learned are called rst substitutions, with the syntax:

```rst
.. |lastversion| replace:: 1.14

Check out a release for |lastversion|.
```

**Comment by awallace-cray** [comment]
I am working on it, but am having a problem w BUILD_VERSION in the tarball.  So if you come up with a PR for that part (even if we don't ever merge it, as such), I will happily just use your changes instead of mine.

**Comment by ben-albrecht** [comment]
`BUILD_VERSION` maintains the git SHA, right? Does that need to be modified?

**Comment by bradcray** [comment]
In the release tarball, I believe BUILD_VERSION should always be "0".  Did I do something in my mod to break that?

**Comment by awallace-cray** [comment]
No. Trouble seems to be Jenkins scripts that call gen_release.

**Comment by awallace-cray** [comment]
@ben-albrecht, I'm not sure we want embedded refs to docs on master branch pointing to "the last release".  I'm thinking of that last time you reorganized the docs; after you inserted that "rst" directory level, none of those links would work if they pointed to release/1.14 or release/1.15. 

Hopefully there could be a variable and/or rst substitution (or some other redirections), which could point either to "master" or "release/something" - set it to "master" while on master, and reset it to "release/something" when the RB is created. CHPL2RSTOPTS looks like that.

**Comment by awallace-cray** [comment]
PR #5992 is work-in-progress.

**Comment by ben-albrecht** [comment]
> Hopefully there could be a variable and/or rst substitution (or some other redirections), which could point either to "master" or "release/something" - set it to "master" while on master, and reset it to "release/something" when the RB is created

If we parsed the output from `chpl --version` in `conf.py`, we could discern the release-status by the presence of the `pre-release <SHA>` in the output. However, there are some complications in doing substitutions within URLs / code-blocks. Let me tackle this in a follow-up PR. It will come down to either using a new sphinx-extension or running a sed command over the docs upon building.

**Comment by awallace-cray** [comment]
PR #5992 just merged.

**Comment by awallace-cray** [comment]
TODOs (preceded by who said it, as best I know; not who agreed to do it): 
* bradcray - Possibly remove GOALS.md altogether 
* ben-albrecht
  - `doc/rst/conf.py`
    `shortversion = 1.16.0 pre-release` # should be parsed from `chpl --version` if possible
  - `man/conf*.rst`
    It would be nice if the Makefile parsed `chpl --version` and set these automatically
  - `QUICKSTART.rst` & `chplenv.rst`
    To reduce maintenance, we could add a `|lastversion|` sphinx-var defined in `conf.py`, so that references to "release tarball" consistently point to the previous version
* awallace-cray
  * `docs/...` - Hopefully there could be a variable and/or rst substitution (or some other redirections), which could point either to "master" or "release/something" - set it to "master" while on master, and reset it to "release/something" when the RB is created. 
    CHPL2RSTOPTS looks like that.
    - ben-albrecht: If we parsed the output from `chpl --version` in `conf.py`, we could discern the release-status by the presence of the `pre-release <SHA>` in the output. However, there are some complications in doing substitutions within URLs / code-blocks. Let me tackle this in a follow-up PR to #5992. It will come down to either using a new sphinx-extension or running a sed command over the docs upon building.

**Comment by ben-albrecht** [comment]
I think the core piece of this issue is resolved. There are some potential next steps that could be split off into a separate issue, i.e. reducing number of places with hard-coded versions using variable substitutions, but they are not high priority nor high impact at the moment.

Any objections to closing this one?

**Comment by bradcray** [comment]
I stumbled across this one yesterday and planned to say something similar.

**Comment by ben-albrecht** [comment]
The next steps are documented in #8004
