### ISSUE TITLE
Add support for slicing of associative domains

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#6004]
In the new array view world, it seems as though we ought to be able to support slicing of associative domains for the first time with no problems.  For instance, I'm imagining something like:

````chapel
const ProgModels = {"C", "Chapel", "MPI", "OpenMP"};
const Languages = {"C", "Chapel"};

var LinesOfCode: [ProgModels] int = ...;

for loc in LinesOfCode[Languages] do
  writeln(loc);
````

However, because our current implementation of slicing an array with a domain is tailored to rectangular arrays, it calls getIndices() to expand the domain into a tuple of indices, which isn't supported (and doesn't really make sense) for the associative case.  Getting this working seems as though it ought to be a simple matter of being more careful about the architecture of those routines in ChapelArray.chpl.  Maybe even in the rectangular case, we should/could move away from expanding the domain into its component ranges in the array view world?

**Comment by redhatturtle** [comment]
First of all +1 for this feature. But I'm really here because I just bumped into this limitation and had a hard time figuring out what was the problem. 

While the compiler error messages pointed in the direction of some operation only being supported for rectangular arrays it wasn't clear to me what operation was the issue. Furthermore I couldn't find any reference in the language specification that array slicing was only supported for rectangular arrays.

I'm attaching the relevant code and error message in case it's of any help but I'm curious about the problems of implementing this feature in the past. While it would make for very clear and concise code in my application I was never quite sure it was the "right way" of doing things. Luckily it isn't a performance critical function so clarity seemed more important.

Also, it's counter intuitive that `for i in (xi.domain - k) do`  works while `x[xi.domain - k]`. Is this because in the first case the operation promotes into an iterable?

**The problematic code:**
```chapel
  proc eval_LagrangePoly1D(x : real, k : int, xi : [] real) : real
  {
    // Evaluate the k-th basis vector of the 1D Lagrange basis defined by the set of nodes xi[] at the point x.
    //
    //               nfp
    //              _____
    //               | |     x  - xi(i)
    //    L_k (x) =  | |  -------------
    //               i=1  xi(k) - xi(i)
    //              i/=k
    //
    //  x  : Coordinate at which to evaluate the k-th Lagrange basis polynomial
    //  k  : Index of the basis vector being evaluated
    //  xi : Array of all the interpolation nodes coordinates
    //
    // The k-th basis vector of a Lagrange basis is a polynomial function that evaluates to 0 at all nodes xi[] except
    // at xi[k] where it evaluates to 1.

    var return_value : real = 1;

    for i in (xi.domain - k) do
      return_value *= (x-xi[i]) / (xi[k]-xi[i]);

    return return_value;
  }

  proc eval_DLagrangeDx(x : real, k : int, xi : [] real) : real
  {
    // Evaluate the derivative of the k-th basis vector of the 1D Lagrange basis defined by the set of nodes xi[] at the
    // point x.
    //
    //                    nfp                  nfp
    //                    ___                 _____
    //     d              \          1         | |     x  - xi(j)
    //    -- [L_k (x)] =  /__  -------------   | |  -------------
    //    dx                   xi(k) - xi(i)   j=1  xi(k) - xi(j)
    //                    i=1                 j/=i
    //                   i/=k                 j/=k
    //
    //  x  : Coordinate at which to evaluate the derivative of the k-th Lagrange basis polynomial
    //  k  : Index of the basis vector being evaluated
    //  xi : Array of all the interpolation nodes coordinates

    var evalDLagrangeDx : real = 0.0;

    for i in (xi.domain - k) do
      evalDLagrangeDx += eval_LagrangePoly1D(x, k, xi[xi.domain - i]) / (xi(k)-xi(i));

    return evalDLagrangeDx;
  }
```

**The compiler error:**
```bash
src/interpolation.chpl:155: In function 'eval_DLagrangeDx':
src/interpolation.chpl:184: error: unresolved call 'DefaultAssociativeDom(int(64),true).dsiDims()'
$CHPL_HOME/modules/internal/DefaultRectangular.chpl:558: note: this candidate did not match: DefaultRectangularDom.dsiDims()
$CHPL_HOME/modules/internal/ChapelArray.chpl:2618: note: because method call receiver with type 'DefaultAssociativeDom(int(64),true)'
$CHPL_HOME/modules/internal/DefaultRectangular.chpl:150: note: is passed to formal 'this: domain'
src/interpolation.chpl:184: note: other candidates are:
$CHPL_HOME/modules/internal/ChapelDistribution.chpl:637: note:   BaseSparseDom.dsiDims()
  src/interpolation.chpl:202: called as eval_DLagrangeDx(x: real(64), k: int(64), xi: [domain(1,int(64),false)] real(64)) from function 'eval_DLagrangeDx_array'
  src/interpolation.chpl:95: called as eval_DLagrangeDx_array(x: real(64), xi: [domain(1,int(64),false)] real(64)) from function 'init_sp2spDeriv'
  src/interpolation.chpl:326: called as init_sp2spDeriv(minOrder: int(64), maxOrder: int(64), cellTopos: set(int(64),false))
note: generic instantiations are underlined in the above callstack
```

**Comment by bradcray** [comment]
Hi @redhatturtle — Thanks for expressing your interest in this feature.  As mentioned in the OP, I don't believe this would be particularly difficult to implement, but it's been on the back-burner waiting for someone to advocate for prioritizing it.  At the very least, I agree with you that the error message could/should be better (and that much, at least, ought to be a five-minute fix (TM)).  

I think the spec is intentional about not saying that slicing is limited to rectangular arrays because the intention was never to limit it in that way; and we've typically tried to have the spec describe the language as intended rather than the current implementation status, relying on issues like this to explain the delta.

I was just trying to decide what my next spare-time coding project would be, so why don't I see whether I can put my money where my mouth was and get this running in short order; and if not, I'll update this issue to say why I underestimated the effort, and at least add the clearer error message.

**Comment by bradcray** [comment]
@redhatturtle : OK, well this is embarrassing how close this was to already working.  The code in the OP actually works as-is if you fill in the `...` and compile with `--no-checks` to turn off bounds checking (and getting it working with bounds checking was a five-minute fix (TM)).  I'm doing some other tests to make sure it's robust before filing a PR with my changes and was curious whether you'd be able to give me a driver for your sample code above so that I can make sure your case works before proceeding.

**Comment by bradcray** [comment]
@redhatturtle : And now I've got an implementation that I feel pretty good about (but still need to test and get through a review) here:  https://github.com/chapel-lang/chapel/pull/17610

**Comment by bradcray** [comment]
Testing came back reasonably clean (a few issues now resolved)

**Comment by redhatturtle** [comment]
Hi @bradcray thanks for working this out on such a short time. Also, I completely agree with your point about the standard.

I intend on compiling your implementation and exploring more thing and I'll update this thread if I find anything else relevant. Anyhow here's a simple driver for testing those functions.
```chapel
proc main()
{
  var nodesDom    : domain(int) = 0..4;
  var nodes       : [nodesDom] real;
  var xTarget     : real = 1.0;

  for i in nodes.domain do
    nodes[i] = -cos( half_pi * (2*i+1)/nodes.size )/2;

  for k in nodes.domain do
    writeln("Interpolation weight for node ", k,": ", eval_DLagrangeDx(xTarget, k, nodes));
}
```

**Comment by bradcray** [comment]
@redhatturtle : Thanks for providing this.  It exposed a simple-to-fix bug in my PR that I hadn't yet picked up on otherwise.

**Comment by bradcray** [comment]
@redhatturtle : I've done a fair amount a testing on the PR now, and have asked for a review on it, but definitely let me know if you try it out and find any other issues with it.

**Comment by bradcray** [comment]
@redhatturtle : This has been merged to the development branch now.  Hope it works well for you, and please let us know if you find other issues with it.
