### ISSUE TITLE
Path library - add support for absPath

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#6005]
Back in late 2014, we started undertaking the implementation of the FileSystem and Path libraries, with input from the user community ([start of thread](https://sourceforge.net/p/chapel/mailman/message/32800541/), [mail with updated proposal after feedback](https://sourceforge.net/p/chapel/mailman/message/32902710/)) Much progress has been made in getting the support onto master, but 10 functions still remain unimplemented due to the youth of our string implementation at the time.  With our string implementation in a good state, these functions should be returned to and implemented

This issue is for the function/file method pair, `absPath`.

Here is the expected documentation and declaration:
```chapel
/* Creates an absolute version of the path specified.  Equivalent to the call
   :proc:`normPath`(:proc:`joinPath`(:proc:`cwd`(), name)) when the path is not
   already absolute and returns the original string otherwise.

   :arg name: the path whose absolute path is desired.
   :type name: `string`

   :return: An absolute version of the path specified
   :rtype: `string`
*/
proc absPath(name: string): string;

/* Create an absolute version of the path in this :type:`~IO.file`.  Equivalent to the call
   :proc:`normPath`(:proc:`joinPath`(:proc:`cwd`(), :proc:`file.path`)) when the path
   is not already absolute and returns the original :proc:`file.path` otherwise.

   :return: An absolute version of the path for this file
   :rtype: `string`
*/
proc file.absPath(): string;
```

This implementation will likely depend upon or be tied to the implementation for `isAbsPath` (#6010), `normPath` (#6015), and `joinPath` (#6012)

**Comment by lydia-duncan** [comment]
Tests will need to be written for this feature.

**Comment by victor-ludorum** [comment]
@lydia-duncan  Hello I want to work on this issue . kindly suggest me how to start .

**Comment by dlongnecke-cray** [comment]
So it looks like calls to locale.cwd() in FileSystem can throw. Should the signature of absPath be changed to indicate as much (ie, add a throws)?

The locale.cwd() function is also not parallel safe, so should that warning propagate to absPath as well?

Not sure yet how to document a throwing function.

**Comment by lydia-duncan** [comment]
Yes to both of those questions :) 
#11374 is a good example of how to document a function that throws

**Comment by dlongnecke-cray** [comment]
Great, thanks!

**Comment by dlongnecke-cray** [comment]
Another problem I'm facing is how to figure out exactly what errors `locale.cwd()` can throw. I know that there's an open issue about updating the documentation for throwing functions.

I'm currently going down a rabbit hole looking for what subclasses are being thrown by the runtime function `chpl_get_cwd()`, and even though I've kind of figured out what is going on, what I end up with is that `locale.cwd()` can throw a SystemError. 

That's not very specific. 

All the raw C runtime error codes run through `SystemError.fromSyserr`, which returns a type. On top of that not all the C runtime error codes are represented there.

Am I missing something? Should I just say that `locale.cwd()` throws a SystemError?
