### ISSUE TITLE
Path library - add support for getParentName

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#6006]
Back in late 2014, we started undertaking the implementation of the FileSystem and Path libraries, with input from the user community ([start of thread](https://sourceforge.net/p/chapel/mailman/message/32800541/), [mail with updated proposal after feedback](https://sourceforge.net/p/chapel/mailman/message/32902710/)) Much progress has been made in getting the support onto master, but 10 functions still remain unimplemented due to the youth of our string implementation at the time.  With our string implementation in a good state, these functions should be returned to and implemented

This issue is for the `file` method `getParentName`.

Here is the expected documentation and declaration:
```chapel
/* Returns the parent directory of the :type:`~IO.file` record.  For instance, a file
   with path `/foo/bar/baz` would return `/foo/bar`

   :return: The parent directory of the file
   :rtype: `string`
*/
proc file.getParentName(): string;
```

This implementation will likely depend on the Path function `dirname` (already implemented)

**Comment by lydia-duncan** [comment]
Tests will need to be written for this feature

**Comment by saru95** [comment]
Hi. I'd like to take this on. I'll be submitting a PR shortly.

**Comment by saru95** [comment]
Should this function support both the following cases?

1.  `/foo/bar/baz/` gives `/foo/bar` [for directories]

2. `/foo/bar/baz/a.txt` gives `/foo/bar/baz` [for files]

**Comment by saru95** [comment]
PR: https://github.com/chapel-lang/chapel/pull/6200
