### ISSUE TITLE
Path library - add support for commonPrefix

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#6007]
Back in late 2014, we started undertaking the implementation of the FileSystem and Path libraries, with input from the user community ([start of thread](https://sourceforge.net/p/chapel/mailman/message/32800541/), [mail with updated proposal after feedback](https://sourceforge.net/p/chapel/mailman/message/32902710/)) Much progress has been made in getting the support onto master, but 10 functions still remain unimplemented due to the youth of our string implementation at the time.  With our string implementation in a good state, these functions should be returned to and implemented

This issue is for the function `commonPrefix`.

Here is the expected documentation and declaration:
```chapel
/* Determines and returns the longest common path prefix (taken character-by-character) of
   all the string pathnames provided. If no arguments are specified, returns
   the empty string.

   :arg paths: Any number of paths
   :type paths: `string`

   :return: The longest common path prefix
   :rtype: `string`
*/
proc commonPrefix(paths: string ...?n): string;
```

**Comment by lydia-duncan** [comment]
Open question: would a version of this function which takes an array argument be useful or desired?

**Comment by lydia-duncan** [comment]
Tests will need to be written for this feature

**Comment by Unnati-P** [comment]
Hi @lydia-duncan! 
My partner and I want to apply for RGSoC in your organization and I would like to work on this feature.
I feel implementing the function by taking an array of strings as argument would be useful.

**Comment by lydia-duncan** [comment]
Hi @Unnati-P!  I'm still digging my way out of email from the holiday weekend, I will try to get back to you soon!

**Comment by lydia-duncan** [comment]
Sorry about the delay.  It would be great to have you and your partner work on this feature!  I'm happy to provide guidance (though I may be a bit slow to respond at times, sorry :().

**Comment by Unnati-P** [comment]
Hi @lydia-duncan !
We have worked out a possible solution for implementing this feature and created a process commonPrefix. We have not done a character-by-character comparison, as the feature involves finding common prefix of paths rather than strings.
```javascript
proc commonPrefix(paths: []): string {

var prefix: string = "";    // result string
var itr: string;
var inputLength = paths.size;   // size of input array
var shortestPath = paths[1];
var i: int = 1;
var ind: int = 1;
var delimiter: string;
var shortestPathIndex: int = 1;
var prefixArray:[1..1] string;    // array of resultant prefix string

// if input is empty, return empty string.
// if input is just one string, return that string as longest common prefix path.

if inputLength==0 then {
  return prefix;
} else if inputLength==1 then{
  return shortestPath;
}

// finding delimiter to split the paths.

if shortestPath.find("\\",1..shortestPath.length)==0 then {
  delimiter = "/";
} else {
  delimiter = "\\";
}

paths.remove(shortestPathIndex);
inputLength-=1;

// making array of the shortest path (prefixArray).

for itr in shortestPath.split(delimiter,-1,false) do {
  prefixArray.insert(ind,itr);
  ind+=1;
}

// split all other paths using delimiter and check for common prefix. Update prefixArray at every iteration.
for i in 1..inputLength do {
ind=1;
  for itr in paths[i].split(delimiter,-1,false) do {
    if ind<=prefixArray.size then {
      if itr!=prefixArray[ind] then {
          prefixArray.remove(ind,prefixArray.size-ind+1);
          writeln(prefixArray);
          break;
        }
      }
      ind=ind+1;
  }
}

// join the prefixArray with delimiter

prefix = delimiter.join(prefixArray);
if prefixArray.size>0 then {
  prefix+=delimiter;
}

return prefix;
}
```
```javascript
Sample input array: ["/Users/templates/examples","/Users/template/"]
output: "/Users/"
```
Please review the code and guide us further.

**Comment by lydia-duncan** [comment]
Hi @Unnati-P!  This generally seems like a reasonable approach.  I have some suggestions based on my language knowledge, and some more general comments.

Minor, meta comment: feel free to open a pull request against the feature, even if it isn't "ready to be submitted yet".  Github's review feature is pretty nice and would allow me to make inline comments on the code itself rather than copy+pasting it around in comments or referring to line numbers and positions.  You'll need to make one anyways, but I would definitely understand not wanting to do so until you feel more ready.

General suggestions:
- I see you have a `paths.remove` call after determining the delimiter.  Be sure to write a test to ensure you aren't mutating the array of paths you are being passed!  I expect that sort of behavior would surprise the user.
- I notice you have a `writeln` in the middle of the nested `for` loop.  I expect it's for debugging purposes, but be sure to remove that before your final submission!
- Minor nit: you've named the path used for the prefixArray as "shortestPath", but haven't done analysis to ensure it is the shortest path of those provided.  I think it's fine to not do that preprocessing analysis and to just use the first path, removing bits as you see fit, but it would be clearer if you labeled it as "first" instead of "shortest" to avoid confusion for maintainers.  It would also allow you to remove some aspects of your code (like the removal I mentioned earlier - you could just start your iteration from the second index, e.g. `for i in 2..inputLength do {`)
- I like that your test example covers similar appearing directories.  That's a good edge case.  But I will definitely need to see a lot more tests before accepting the code.  What other cases can you come up with?

Language familiarity suggestions:
- Iterators are fun and can be used to create an array directly.  I think the following should work:
`prefixArray = shortestPath.split(delimiter, -1, false);`
- It looks like you only use `i` for the nested `for` loop.  You ought to be able to get away with just having the loop create it for you, instead of declaring it at the beginning of the function.  The same could also be done for `itr`.
- I think you could use the `joinPath` function to join the prefixArray at the end?
- I would suggest using zippering for your inner `for` loop instead of resetting `ind` for each iteration of the outer `for` loop.  You would get the value for each iteration using a `range` created from the prefixArray's current length, allowing you to avoid that first `if` statement.  This would look like
```chapel
for ind, itr in 1..prefixArray.size, paths[i].split(delimiter,-1,false) do {
```
- I might send in another `range` when removing from the end of the prefixArray, from the current index to the index of the last element, but that's up to you.
- The original specification asked for a different function declaration than the one you're using - it allows a varying number of arguments ("varargs" for short).  That specification would allow calls like `commonPrefix("/a/b/c")`, `commonPrefix("/a/b", "/a/b/c")`, etc. without having the user create an array themselves (the compiler would allow you to access all the arguments provided as if a `tuple` was specified).  I think it's fine to have both options, but would like to see the varargs version as well.  How would that change your implementation?
