### ISSUE TITLE
Path library - add support for isAbsPath

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#6010]
Back in late 2014, we started undertaking the implementation of the FileSystem and Path libraries, with input from the user community ([start of thread](https://sourceforge.net/p/chapel/mailman/message/32800541/), [mail with updated proposal after feedback](https://sourceforge.net/p/chapel/mailman/message/32902710/)) Much progress has been made in getting the support onto master, but 10 functions still remain unimplemented due to the youth of our string implementation at the time.  With our string implementation in a good state, these functions should be returned to and implemented

This issue is for the function `isAbsPath`.

Here is the expected documentation and declaration:
```chapel
/* Determines whether the path specified is an absolute path and returns
   that information

   :arg name: the path to be checked.
   :type name: `string`

   :return: `true` if `name` is an absolute path, `false` otherwise
   :rtype: `bool`
*/
proc isAbsPath(name: string): bool;
```

This function will probably be used in the implementation of `absPath` (#6005)

**Comment by lydia-duncan** [comment]
Tests will need to be written for this feature

**Comment by victor-ludorum** [comment]
Hello @lydia-duncan  I have worked on this issue and made an **isAbsPath function** .
``
proc isAbsPath(name: string): bool {
  
     if name.isEmptyString() {
	    return false;
	 }
  
     const len: int = name.length ;
  
    /*
	First, there will be a check that
	whether first character of name 
	are '/' or '\'. If it is then it 
	is Absolute .
	*/
	
    var str: string = name[1];
    if (str == '/' || str == '\\') {
      return true;
    }

	/*
	Then , there will be a check that
	whether the name will be like "C:\\"
	or "D:/" or "c:/" . So, we first check for
	alphabets (capital & small) letters . Then, 
	check ':' character and lastly checking
	has been done for  '/' or '\' .
	*/

	else if str.isAlpha() {
      // Possible device root

      if len > 2 && name[2] == ':' {
        var strp: string = name[3];
        if (strp == '/' || strp == '\\') {
          return true;
		}  
      }
    }
    return false;
}
``
Kindly check it and suggest the necessary changes that should be done .

**Comment by lydia-duncan** [comment]
I'm going to focus on other work for the rest of today, but will be sure to review this tomorrow!

**Comment by victor-ludorum** [comment]
Okay Mam No problem 😊 !!

**Comment by lydia-duncan** [comment]
Support was added for this function for linux and OSX, but not for cygwin

**Comment by lydia-duncan** [comment]
Resolved by @dlongnecke-cray
