### ISSUE TITLE
Path library - add support for joinPath

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#6012]
Back in late 2014, we started undertaking the implementation of the FileSystem and Path libraries, with input from the user community ([start of thread](https://sourceforge.net/p/chapel/mailman/message/32800541/), [mail with updated proposal after feedback](https://sourceforge.net/p/chapel/mailman/message/32902710/)) Much progress has been made in getting the support onto master, but 10 functions still remain unimplemented due to the youth of our string implementation at the time.  With our string implementation in a good state, these functions should be returned to and implemented

This issue is for the function `joinPath`.

Here is the expected documentation and declaration:
```chapel
/* Join and return one or more paths, putting precedent on the last absolute
   path seen.  Return value is the concatenation of the paths with one
   directory separator following each non-empty argument except the last.
   Examples:

   `joinPath("/foo/bar", "/baz")` will yield `"/baz"`

   `joinPath("/foo", "./baz")` will yield `"/foo/./baz"`

   `joinPath("/foo/", "", "./baz")` will also yield `"/foo/./baz"`

   :arg paths: Any number of paths
   :type paths: `string`

   :return: The concatenation of the last absolute path with everything following
            it, or all the paths provided if no absolute path is present
   :rtype: `string`
*/
proc joinPath(paths: string ...?n): string;
```

This function will probably be used in the implementation of `absPath` (#6005)

It should also be used to expand the support of `FileSystem.copy` to allow the `dest` argument to be a directory

**Comment by lydia-duncan** [comment]
Tests will need to be written for this feature

**Comment by victor-ludorum** [comment]
@lydia-duncan  Hello I want to work on this issue . Please guide me in this .

**Comment by lydia-duncan** [comment]
Hi @victor-ludorum!  A good way to start would be to look at the code already in the [Path module](https://github.com/chapel-lang/chapel/blob/master/modules/standard/Path.chpl), and try to mimic its style and implementation.  The declaration I have described above is the expected interface for clients of the function, so you should write it like this:
```chapel
proc joinPaths(paths: string ...?n): string {
  ... // implementation goes here
}
```
with the documentation preceding the function.

I recommend writing some test Chapel code, to nail down your expectations for how this function will work.  You may want to take a look at how Python has implemented their corresponding function (though if you base your work off of it, be sure to cite your sources!)

If you haven't already, also be sure to read through our [Contributor Info documentation](https://github.com/chapel-lang/chapel/blob/master/doc/rst/developer/bestPractices/ContributorInfo.rst) and [Test System documentation](https://github.com/chapel-lang/chapel/blob/master/doc/rst/developer/bestPractices/TestSystem.rst).  Let us know if you have questions about them - we'd love to know if something is unclear so we can improve it!

Thanks again for your interest in Chapel!

**Comment by victor-ludorum** [comment]
Thanks @lydia-duncan  for you suggestion . I will first study path module and if I will found any problem. I will ask you .
