### ISSUE TITLE
Path library - add support for normPath

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#6015]
Back in late 2014, we started undertaking the implementation of the FileSystem and Path libraries, with input from the user community ([start of thread](https://sourceforge.net/p/chapel/mailman/message/32800541/), [mail with updated proposal after feedback](https://sourceforge.net/p/chapel/mailman/message/32902710/)) Much progress has been made in getting the support onto master, but 10 functions still remain unimplemented due to the youth of our string implementation at the time.  With our string implementation in a good state, these functions should be returned to and implemented

This issue is for the function `normPath`.

Here is the expected documentation and declaration:
```chapel
/* Collapse paths such as `foo//bar`, `foo/bar/`, `foo/./bar`, and 
   `foo/baz/../bar` into `foo/bar`.  Warning: may alter meaning of paths
   containing symbolic links.  Similar to :proc:`normCase`, on Windows will replace
   forward slashes.

   :arg name: a potential path to collapse, possibly destroying the meaning of the
             path if symbolic links were included.
   :type name: `string`

   :return: the collapsed version of `name`
   :rtype: `string`
*/
proc normPath(name: string): string;
```

It is expected that this function will be used in the implementation of `absPath` (#6005)

**Comment by lydia-duncan** [comment]
Tests will need to be written for this feature

**Comment by pachchi** [comment]
Hello @lydia-duncan , I and my colleague worked on this issue and made this normpath function.
```
proc normPath(name: string): string
{
   if name.isEmptyString()
      {
	    return name;
      }
  
     const len: int = name.length ;
     /*stores the length of input string*/

  	var t = name.split('/', len, true);
	/*splits the input sring with delimiter '/'*/
	
  	var l = t[1];
	/*stores the very first string excluding the backslash character*/
	
  	var r : string;
  	for i in t
	{
  		r = i;
  	}
  	/*stores the last string excluding the backslash character*/
	
  	var str = "";
  	str = '/'.join(l, r);
	/*joins first and last string part with a backslash in between*/

    return str;

}

writeln(normPath(stdin.read(string)));
```
kindly go through the code.

**Comment by lydia-duncan** [comment]
Hi @pachchi.  What test cases have you examined?  To me, it looks like this code splits the path and then rejoins it without examining if "." or ".." are present in the contents it is rejoining.

**Comment by MuskaanJain** [comment]
Hello @lydia-duncan, I am the colleague of @pachchi.
If final strings have strings like "." or ".." it means folder name includes that character, then it should return a final string with that character included, correct if I am wrong?

We have tested for all the cases mentioned in the above documentation.

**Comment by lydia-duncan** [comment]
> Collapse paths such as `foo//bar`, `foo/bar/`, `foo/./bar`, and 
   `foo/baz/../bar` into `foo/bar`.  Warning: may alter meaning of paths
   containing symbolic links.

This specification indicates that the purpose of this function is to remove extraneous `/`, to remove `/./`, and when `/../` is specified to also remove the directory specified prior to it.

We base a lot of the intended behavior for these functions off the similar function in the Python modules.  [Python's normpath](https://docs.python.org/3/library/os.path.html#os.path.normpath) also claims to remove those structures, so I suspect you will find your implementation gives different behavior to Python's normpath for paths with those characters.

**Comment by lydia-duncan** [comment]
(also, should say: thanks for your interest in this project!  Please forgive me if I come off as curt sometimes, it can be difficult to communicate nuance in a text only format)

**Comment by MuskaanJain** [comment]
Thanks, @lydia-duncan, we get it now, correctly. Soon, we will correct our implementation.
