### ISSUE TITLE
Path library - add support for relPath

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#6017]
Back in late 2014, we started undertaking the implementation of the FileSystem and Path libraries, with input from the user community ([start of thread](https://sourceforge.net/p/chapel/mailman/message/32800541/), [mail with updated proposal after feedback](https://sourceforge.net/p/chapel/mailman/message/32902710/)) Much progress has been made in getting the support onto master, but 10 functions still remain unimplemented due to the youth of our string implementation at the time.  With our string implementation in a good state, these functions should be returned to and implemented

This issue is for the functions and file methods `relPath`.

Here is the expected documentation and declaration:
```chapel
/* Creates a relative path to the named path from the current directory.
   The filesystem is not accessed to verify the existence of the named path.

   :arg name: a path which the caller would like to access from the current
              directory.
   :type name: `string`

   :return: The relative path to `name` from the current directory
   :rtype: `string`
*/
proc relPath(name: string): string;

/* Returns a relative path to the named path from the specified `start` directory.
   The filesystem is not accessed to verify the existence of the named path or
   the specified starting location.

   :arg name: a path which the caller would like to access.
   :type name: `string`

   :arg start: the location from which access to name is desired.
   :type start: `string`

   :return: The relative path to `name` from the current directory
   :rtype: `string`
*/
proc relPath(name: string, start: string): string;
```

There should also be two methods on a file record with the same purpose
and which use the record's filename in place of the first argument in the
two versions of relpath listed above:
```chapel
proc file.relPath(): string;
proc file.relPath(start: string): string;
```

**Comment by lydia-duncan** [comment]
Tests will need to be written for this feature

**Comment by dlongnecke-cray** [comment]
With the existence of default parameter values, can we merge these two function prototypes into one?

**Comment by lydia-duncan** [comment]
Hmm, that's a good question.  I'd experiment with it a bit - my main worry is whether the default value would get computed too early, so you'd want to test the behavior before and after changing the current working directory.  But if that turned out to be fine, I would not object to only having one version of the function
