### ISSUE TITLE
Can't call .domain within record initializer (phase 2)

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#6034]
### Summary of Problem

It seems that I'm unable to call .domain in phase 2 of a record's initializer...  I can in a record constructor and, IIRC, I either can in a class initializer, or the error is completely different (maybe worth trying a valgrind run on the compiler?).

### Steps to Reproduce

**Associated Future Test(s):**

``test/classes/initializers/initCallsDom.chpl``

**Compile command:**
``chpl initCallsDom.chpl``

### Configuration Information
- Output of `chpl --version`: ``1.16.0 pre-release (21b160d)``

**Comment by bradcray** [comment]
Future filed in #6031

**Comment by lydia-duncan** [comment]
This was resolved with Mike's #6492
