### ISSUE TITLE
Semantic: Functions that return void values vs. return nothing

### ISSUE THREAD

**Issue by daviditen** [chapel-lang/chapel#6049]
Should functions that do not return a value be equivalent to functions that explicitly return a void value?

```
proc f1() {
  writeln("f1");
  // no return
}

proc f2() {
  writeln("f2");
  return; // 0-argument return
}

proc f3() {
  writeln("f3");
  return _void;
}

var v1 = f1();
var v2 = f2();
var v3 = f3();
```
Should all three of the variable assignments be allowed?  Currently all of them are allowed because a function that has no return statement and a function that has a 0-argument return are considered equivalent to a function that returns the value `_void`. I think only the explicit `_void` return should really be allowed in this way.

This is similar to issue #5697, which asks a similar question but about iterators.

**Comment by bradcray** [comment]
I tend to agree with David -- that only a function that returns an expression of void type should be able to be assigned to a variable (or used in a context that needs an expression).  I'm not whether the other cases should generate an error or a warning -- I just don't think they should be silently allowed.  A case that I ran into recently looked something like this:

````chapel
proc foo() {
  ...compute something...
  // meant to return something here but forgot to
}

writeln(foo());
````

compiled and ran but generated no output which puzzled me for awhile.  If non-returning functions used in such cases generated a warning or error, I would've caught my mistake much sooner.

**Comment by noakesmichael** [comment]
I agree with David and Brad.

On Apr 18, 2017, at 2:56 PM, Brad Chamberlain <notifications@github.com<mailto:notifications@github.com>> wrote:


I tend to agree with David -- that only a function that returns an expression of void type should be able to be assigned to a variable (or used in a context that needs an expression). I'm not whether the other cases should generate an error or a warning -- I just don't think they should be silently allowed. A case that I ran into recently looked something like this:

proc foo() {
  ...compute something...
  // meant to return something here but forgot to
}

writeln(foo());

compiled and ran but generated no output which puzzled me for awhile. If non-returning functions used in such cases generated a warning or error, I would've caught my mistake much sooner.

**Comment by bradcray** [comment]
The thing I'm wrestling with is whether an error or warning is more appropriate.  Here are some sub-questions:

* Should we think of these different cases as defining functions with different type signatures?  Or do we think of them as simply different flavors of void functions?
* Maybe the same question in a slightly different way: If the user were providing fully typed signatures for these functions, would they all be of return type ': void' or would the two cases be different?
* If we think of them as being the same types / being declared the same way, can we make it an error to distinguish these cases?  Or would that suggest all three should be treated the same, but that an implementation like ours offers a warning for some of the cases which seem more likely to be user error?
* How do these choices interact with our interoperability with C functions that have 'void' return type?

Just to give my gut reactions:

* I'm inclined not to have the different cases be declared differently, but that may simply be because I haven't come up with any proposals that I like for what a fully-typed "return nothing" would look like?
* That suggests to me that perhaps a warning is most appropriate even though I think I'd really prefer for such cases to generate errors
* I strongly suspect that C 'void' functions should behave like "return nothing" cases in Chapel.

**Comment by daviditen** [comment]
> * Should we think of these different cases as defining functions with different type signatures? Or do we think of them as simply different flavors of void functions?

My current direction is to treat the type signatures the same.  I could be convinced that they should have different signatures since one returns "nothing" and the other returns "something nothing-like", but I my gut reaction is to leave the declared types the same.

> * Maybe the same question in a slightly different way: If the user were providing fully typed signatures for these functions, would they all be of return type ': void' or would the two cases be different?

The way I currently am leaning is that both are ': void', but one is more of a 'void' concept, while the other is a concrete 'void' value.

> * If we think of them as being the same types / being declared the same way, can we make it an error to distinguish these cases? Or would that suggest all three should be treated the same, but that an implementation like ours offers a warning for some of the cases which seem more likely to be user error?

The cases can be distinguished and can be made into either an error or a warning.  My thinking has changed since doing the initial first-class void work, and I now feel it should probably be an error to use a non-value-returning function in a context that requires a value of some sort.

> * How do these choices interact with our interoperability with C functions that have 'void' return type?

I'd consider these to be in the category of non-value-returning function, so an error if you try to use them in a way that expects a value.

**Comment by vasslitvinov** [comment]
I can see David's proposal as a good near-term solution, until we have experience or users suggesting something else.

Just in case, my understanding of the proposal is that the two kinds of functions have the same user-level signature, however are distinguished internally in the compiler. Non-returning functions can't be assigned to anything, as has always been the case.

I suggest that, for this purpose, a function is examined for having a `return` **after** param folding of conditionals/loops. Sort-of analogously to how a function signature is decided after generic instantiation. However... I also suggest that iterators are examined for having a `yield`, for error reporting discussed in #5697, **before** resolution. I am unclear why my preferences are different for these two cases.

**Comment by daviditen** [comment]
@vasslitvinov, yes, I think you understand the proposal.  Functions that return the `_void` value and functions that don't return anything have the same signature, but the compiler treats them differently so only the first is assignable to variables.

The error for incorrectly used non-returning functions seems to fit best late in function resolution, which matches your intuition about putting it after param folding.

**Comment by daviditen** [comment]
PR #6091 is merged.

**Comment by ben-albrecht** [comment]
>Should functions that do not return a value be equivalent to functions that explicitly return a void value?

This can come into play for some FCF use-cases, e.g. Python-like decorator functions:

```chpl
var value = decorate(foo);
writeln(value);

proc foo() { }

proc decorate(fn) {
  var ret = fn();
  return ret;
}
```

(@daviditen - the above code compiles and runs with master right now... Is this intended to work?)

This came up in my development of a unit-test library that would call arbitrary methods on an object. The example above fails as expected if `fn` is a method, which was my particular use-case.

**Comment by daviditen** [comment]
I would expect that to produce an error along the lines of:

```
dec.chpl:6: In function 'decorate':
dec.chpl:7: error: illegal use of function that does not return a value: 'fn'
```

**Comment by ben-albrecht** [comment]
Me too.. Perhaps there is an implementation error?

Bug aside, I originally commented to point out an example where implicit `_void` return would be useful.

**Comment by bradcray** [comment]
> For example, the ability to inspect if the function has a return-type or not

I thought @nspark  had already implemented this.  See commit 4411855.  I'd imagine you'd want to write something like:

```chapel
  if fn.retType == void
```

**Comment by ben-albrecht** [comment]
```chpl  
 if fn.retType == void 
```

@bradcray  - Cool! 

Does this work if `fn` does not have a return? What about the case where `fn` takes args?

**Comment by bradcray** [comment]
I've already told you all I think I know.  See the PR for details or experiment with it.  I don't think it matters whether the function takes arguments or not (don't see why it would anyway -- note that fcf's can't be generic).

**Comment by ben-albrecht** [comment]
>  note that fcf's can't be generic

... or overloaded, which addresses all my questions for now - thanks.
