### ISSUE TITLE
Rename the void value currently named "_void"

### ISSUE THREAD

**Issue by daviditen** [chapel-lang/chapel#6077]
There is currently a "value" named `_void` that has type `void`.  We can't name both the value and the type the same thing, and don't want to continue using the leading underscore.

This value will probably be most frequently used in variable or field declarations, but can be used in some other places as well:

```
var myRemovableVar: void = _void;
var debugString = if debug then "print me" else _void;

writeln(_void); // prints a blank line
```

Brainstorming a few possibilities:
* `empty`
* `nothing`
* `unused`
* `none` // I believe python uses `none` for a similar idea

I'm happy to take other suggestions, as none of those seem great to me.

**Comment by gbtitus** [comment]
nil?

**Comment by daviditen** [comment]
I'm not sure how `nil` would work since it already stands for an unassigned class value.  When you assign `nil` to a variable, do you want an unassigned variable of type `object`, or a removable `void` thing?

`var myRemovableVar = nil;  // object or void?`

**Comment by gbtitus** [comment]
Ah, yes, that wouldn't work.  Okay, how about "aught"?   :-)

**Comment by daviditen** [comment]
Another idea, we could use something like an empty tuple/domain/array:

```
()
{}
[]
```

**Comment by mppf** [comment]
I like the idea of using `()` for this and also considering 0-length tuples to be the same type. My main hesitation in that area is that it might be more common to want to return a 0-length tuple than a `void` value and I'm not totally certain that our `void` return rules would be enough. Even so, I think it's worth a try and/or checking to see if common patterns will work with 0-length tuples being conflated with void.
