### ISSUE TITLE
[Jira-197] Support for conditional operators.

### ISSUE THREAD

**Issue by awallace-cray** [chapel-lang/chapel#6083]
[[Jira-197]](https://chapel.atlassian.net/browse/CHAPEL-197)
<p>Readability is improved in situations where some simple conditions need to be tested if the conditional operator is available.</p>

<p>Example: <br/>
proc max(a:int, b:int): int</p>
{
	return (a > b) ?  a : b;
}

<p>Also, defining constants becomes possible with conditional statements because the value of a const all has to be assigned within that single statement.</p>

<p>Example:<br/>
const max_num:int = (a > b) ? a : b;</p>

<p>The conditional operator may even help the programmer avoid unnecessary null checks for object references. </p>

<p>var obj: MyClass  = (old_obj == null) ? null : old_obj.attribute1;</p>

<p>Support for this in Chapel will help the programmers in writing better readable code and will also help write compact code.</p>
<i>[CHAPEL-197] created by rohanbadlani</i>

**Comment by mppf** [comment]
Chapel already supports conditional operators using if-expressions.

What you would write with the ternary operator in C is written with `if A then B else C` in Chapel. For your particular example:
``` chapel
proc max(a:int, b:int): int
{
  return if a > b then a else b;
}
```
