### ISSUE TITLE
Internal compiler error with --library and main

### ISSUE THREAD

**Issue by TartanLlama** [chapel-lang/chapel#6106]
### Summary of Problem

The compiler ICEd when I gave it code with `main` in a module and compiled with `--library`

### Steps to Reproduce

**Source Code:**

```chapel
module Hello {
    proc main() {
    }
}
```

**Compile command:**
`chpl --library test.chpl`

### Output

production.chpl:2: internal error: BUI0469 chpl Version 1.15.0

Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug -- 
please see http://chapel.cray.com/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.

### Configuration Information

- Output of `chpl --version`: chpl Version 1.15.0
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:

```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_MAKE: make
CHPL_ATOMICS: intrinsics
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_WIDE_POINTERS: struct
CHPL_AUX_FILESYS: none
```

- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by lydia-duncan** [comment]
Thanks for reporting!  Turns out the internal compiler error is actually an error we would like to expose to the user, so it's an easy fix.
