### ISSUE TITLE
should comm counts test be perf tests?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#6136]
We have lots of multi-locale comm counts tests that run as part of the correctness suite. But these are unnecessarily fragile:

 * require updating when comm counts go down
 * make us less likely to improve comm-counting module b/c of all the test updates
 * cause what appear to be correctness failures with non-standard multilocale optimization levels (e.g.-no-rvf, --no-loop-invariant-code-motion, toggling --cache-remote)

The comm counts tests largely pre-dated the performance testing framework. Perhaps we should move the majority of these comm counts tests to become perf tests?

**Comment by ronawho** [comment]
Closing in favor of https://github.com/chapel-lang/chapel/issues/6137
