### ISSUE TITLE
CHPL_WIDE_POINTERS: node16 not currently working

### ISSUE THREAD

**Issue by coodie** [chapel-lang/chapel#6149]
### Summary of Problem
There is LLVM assertion in compiler when  compiling with LLVM for multilocales (setting CHPL_COMM makes this work fine).

Here is message of assert:
```
chpl: /home/goovie/Dokumenty/Repozytoria/coodie_chapel/third-party/llvm/install/linux64-gnu/include/llvm/IR/Instructions.h:823: llvm::Type* llvm::checkGEPType(llvm::Type*): Assertion `Ty && "Invalid GetElementPtrInst indices for type!"' failed.
```

I did git bisect with hope of fixing this bug by myself and following commit introduces it:
[https://github.com/chapel-lang/chapel/commit/7af9b09aadb4c992051f0027a5a956d3c5648e90](url)

### Steps to Reproduce

**Source Code:**

```chapel
writeln(1000);
```

**Compile command:**
chpl test.chpl --llvm -o test

### Configuration Information

- Output of `chpl --version`:
chpl Version 1.14.0.7af9b09
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
HPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: none *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: cstdlib *
CHPL_MAKE: make
CHPL_ATOMICS: intrinsics
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_WIDE_POINTERS: node16 *
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by mppf** [comment]
@benharsh - I'm not sure if this will be up to you or me to fix but I wanted you to be aware of it.

**Comment by mppf** [comment]
I'm looking in to this issue. It seems that it's not occurring with master with a non-debug build of LLVM. I'll check to see if it comes up in a debug build.

**Comment by mppf** [comment]
Ah, I see. The problem is with `CHPL_WIDE_POINTERS=node16`. Since I'm hoping to retire that feature, I'll look at doing that first.
