### ISSUE TITLE
Associative arrays too conservative in locking

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#6223]
While debugging a nondeterministic number of communications in PR #6221, I was surprised to find that we were taking a lock (via an atomic) in order to do a read-only access to an associative array (see the discussion between @benharsh and myself in the comments section of that PR for details).  This issue is designed to capture an action item that I think we should not be taking these locks for array accesses.

This conservatism w.r.t. locking seems to have originally stemmed from a concern that someone may be resizing the associative array as we're reading from / writing to it. -- however, this risk is true of any of our domains and arrays.  E.g., resizing the domain of a 1D rectangular array while someone is reading from / writing to it could have similarly disastrous consequences.  For this reason, we've traditionally said "don't do that," and the burden is on the user not to do so to avoid having to lock every read/write.  While we could reconsider that position or have a way to opt into something safer, that's not what I'm interested in here.

Initially, I was thinking that we should continue taking the lock for write accesses in order to guard against the event that the write could resize in the array (which is only supported when the associative array and its domain have a 1:1 relationship).  However, upon exploring the implementation and thinking about it a bit more, it seems that even locking in that case is not particularly well-motivated.  I was originally thinking that it would help with cases like this:

```chapel
forall key in collection do
  A[key] += 1;
```

by permitting multiple accesses to associative array `A` to occur simultaneously, potentially growing it.  But @benharsh pointed out that after the dsiAccess() returns the reference to the array element it computes, another task could resize `A` before the += operator had the opportunity to update the array element.  So locking in this case does not seem particularly well-motivated either (see the discussion on outdated code diffs in PR #6244 for further wrestling with this question).

**Comment by mppf** [comment]
I think this is a reasonable approach but I'm not so sure we document the "don't do that" anywhere yet. We might want to check / improve the documentation in this area as part of this effort.
