### ISSUE TITLE
Codegen to LLVM gets internal compiler error on casted extern constant

### ISSUE THREAD

**Issue by dmk42** [chapel-lang/chapel#6231]
### Summary of Problem

When a C header file defines a macro as a casted integer constant, and the macro is used by a Chapel program as an `extern const`, the Chapel program compiles and runs when using the C back end, but the Chapel compiler's codegen gets an internal error when using the LLVM back end.

This problem was originally encountered when trying to compile lcals/Timer.chpl on Ubuntu, where the `CLOCKS_PER_SEC` macro is defined as a casted integer constant.  The source code below has been simplified so Ubuntu is no longer necessary to reproduce the problem.

The following error is observed when attempting to use the LLVM back end.  This message is generated with `CHPL_DEVELOPER=true` for extra detail.
```
cps.chpl:5: internal error: Could not code generate MY_CLOCKS_PER_SEC - perhaps it is a complex macro? [symbol.cpp:517]
Note: This source location is a guess.
```

### Steps to Reproduce

This problem has been reproduced under the following conditions.

* Either clang or gcc as the host/target compiler
* WIth or without `CHPL_DEVELOPER=true`
* `CHPL_LLVM=llvm`
* On either Linux or a Mac

**Source Code:**

cps.h:
```c
#define MY_CLOCKS_PER_SEC ((long) 1000000)
```
cps.chpl:
```chapel
require "cps.h";

extern const MY_CLOCKS_PER_SEC: int(64);

writeln(MY_CLOCKS_PER_SEC);
```

**Compile command:**

Working:
```
chpl cps.chpl
```
Nonworking:
```
chpl --llvm cps.chpl
```

**Execution command:**

Working:
```
a.out
```
Nonworking:
None available because the compiler aborts.

**Associated Future Test(s):**
N/A

### Configuration Information

- Output of `chpl --version`:
```
chpl Version 1.16.0 pre-release (0aab9c3)
Copyright (c) 2004-2017, Cray Inc.  (See LICENSE file for more details)
```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_MAKE: make
CHPL_ATOMICS: intrinsics
CHPL_GMP: none *
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_WIDE_POINTERS: struct
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
gcc (Ubuntu 6.2.0-3ubuntu11~16.04) 6.2.0 20160901
```
```
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
- (For Cray systems only) Output of `module list`:
N/A

**Comment by mppf** [comment]
Presumably, we'd need to adjust `handleMacro` to fix this. One thing I had thought about doing when I first added this code was to have our compiler automatically create `static inline` wrapper functions for these macros. The problem is that it can be non-trivial to get the return type out of the macro expressions. (But maybe there is a way to get the included clang to do that).
