### ISSUE TITLE
chpldoc generates internal error on module deinit()

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#6240]
### Summary of Problem

If a module-level deinit() routine is not marked "no doc", then chpldoc generates an internal error.

### Steps to Reproduce

**Associated Future Test(s):**
[`test/chpldoc/module/modDeinit.doc.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/chpldoc/module/modDeinit.doc.chpl
          ) #6238 

### Configuration Information

- Output of `chpl --version`: 1.16.0 pre-release (f9db00e)

**Comment by bradcray** [comment]
Note that I think the cause of this internal error is that when deinit() was first introduced, it was only supported for classes and so, presumably, gets some treatment based on that assumption.  Now that it's used for modules, that assumption seems to be breaking (note that even if it weren't used for modules, it'd be unfortunate if a user-level standalone procedure named "deinit" had caused this behavior).

**Comment by bradcray** [comment]
I was going to tag this as @lydia-duncan and @ben-albrecht as the two main chpldoc-ers and @vasslitvinov for owning deinit(), but if I was reading right, it also looked like the internal error was in code that @noakesmichael touched last.

**Comment by lydia-duncan** [comment]
This seems like something that is reasonable for me to own

**Comment by ben-albrecht** [comment]
Duplicate of #5791 ?

**Comment by bradcray** [comment]
Oops, yes.  I didn't think I could have forgotten about an open issue so early in our use of them!  I updated that issue to mention my future and am closing this one.

**Comment by bradcray** [comment]
(PS -- Note that the previous issue had some intriguing breadcrumbs about FLAG_DESTRUCTOR being applied to the module-level deinit(), perhaps inappropriately...)

**Comment by lydia-duncan** [comment]
I had kinda assumed that meant the appropriate action was to remove the flag, but no one else responded to that . . .
