### ISSUE TITLE
New label for needing a CLA

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#6253]
I'd like to propose a new label to identify PRs that are waiting for an external contributor to submit a contributor license agreement (CLA).

Some examples of PRs that would have or still could benefit from this label:
- #5928
- #5926 
- #5843

I'd like to propose the label text: `stat: Needs CLA`

**Comment by bradcray** [comment]
For simplicity: Why not simply "waiting on contributor" and then having the final comment in the stream indicate that the CLA is what we're waiting on?

**Comment by ben-albrecht** [comment]
That's a fair point. I think of this as another way to succinctly show the next step in the PR to the contributor and other developers (from browsing the PR list) in the same way that the `Needs Code Review`, `Needs Design Review`, `Needs Testing` stat labels do. 

I've only listed a few examples of open PRs that could use this label, (not wanting to spend too much time digging through older PRs), but I think this situation comes up frequently enough to justify adding a label.

Also, it just occurred to me that this label could serve as a nice interface for the CLA-checking bot to tag PRs as needing a CLA (#5574).

@ronawho originally proposed this label offline - he may have more to add on this when time permits.

**Comment by ben-albrecht** [comment]
After some time, I've mustered up the courage: pinging @ronawho  && @bradcray for additional comments

**Comment by ronawho** [comment]
I'm still very much in support a "needs CLA" label. 

We (or at least I) tend to use the "waiting on contributor" as a sign that code changes are needed and I'll remove it when the code is ready to merge without thinking about the CLA. 

I think a CLA label is also a useful reminder to users that they need to sign/submit a CLA. In the past we've had commits where the code is ready, and then we're waiting several weeks for the CLA to makes its way to us (especially for folks that need to get a group CLA submitted)

**Comment by bradcray** [comment]
If I ran the world, I'd still consider it overkill, but I don't object to it either.  BTW, I added another label request on the original label discussion issue recently ("gating issue") -- dunno if closed issues generate notifications for those who were subscribed to them or not.

**Comment by ben-albrecht** [comment]
I have created this label.
