### ISSUE TITLE
rename FLAG_COMPILER_GENERATED

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#6296]
The flag FLAG_COMPILER_GENERATED really means that it's a function available as a last-resort in resolution. Any functions not marked in this way is preferred.

We should use a new flag, FLAG_LAST_RESORT (or something) and use FLAG_COMPILER_GENERATED to indicate that a symbol is actually created automatically by the compiler.

**Comment by bradcray** [comment]
I like this and find "last resort" to be intuitive.  If it seemed to colloquial, other options might be "fallback" or "fallback overload" or "error overload" which tend to be how it's used in practice.

**Comment by victor-ludorum** [comment]
Hello @mppf  I want to work on this issue . As per your explanation I have understood that you want to replace the flag name **"FLAG_COMPILER_GENERATED"** in [functionresolution.cpp] (https://github.com/chapel-lang/chapel/blob/master/compiler/resolution/functionResolution.cpp) with **FLAG_LAST_RESORT** . Am I correct ??  But I don't understand the second thing i.e. the use of ** FLAG_COMPILER_GENERATED** again . Please guide me for this and suggest the resources needed for the work ..

**Comment by mppf** [comment]
closing this issue since PR #6783 added FLAG_LAST_RESORT.
