### ISSUE TITLE
errors with subclasses that throw errors

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#6315]
### Summary of Problem

The following program produces:

    subclass-throws.chpl:13: internal error:
    number of actuals does not match number of formals in foo() [callDestructors.cpp:1302]

I expected

```
C.foo()
D.foo()
D.foo()
Fini
```

### Steps to Reproduce

**Source Code:**

```chapel
class C {
  proc foo() throws { writeln("C.foo()");}
}

class D : C {
  proc foo() throws { writeln("D.foo()"); }
}

var c = new C();
var d = new D();
var dc:C = new D();

try { c.foo(); } catch { writeln("c.foo threw"); }
try { d.foo(); } catch { writeln("d.foo threw"); }
try {dc.foo(); } catch { writeln("dc.foo threw"); }

delete c;
delete d;
delete dc;

writeln("Fini");
```

Curiously, though the error is reported on the line calling c.foo(),
if I remove from the program everything having to do with class D, var
d, and var dc, it compiles and executes the c.foo() line.

The `class D` code is there because this is slightly simplified from a
test I expected to fail to compile, but which does compile but
segfaults when run.  If the `throws` is removed from `C.foo()`, and
`D.foo()` is changed to `throw new Error();` after its `writeln()`, the
program compiles and runs, but segfaults:

```
fortytwo@magrathea:~/src/chpl$ chp subclass-throws.chpl
C.foo()
D.foo()
D.foo()
*** Caught a fatal signal: SIGSEGV(11) on node 0/1
NOTICE: Before reporting bugs, run with GASNET_BACKTRACE=1 in the environment to generate a backtrace. 
```

Curiously, `d.foo threw` wasn't printed, and the segfault was between
the second `D.foo()` and the `Fini`.

(The gasnet backtrace doesn't look interesting to me, but I can provide it.)

I expected this to be a compilation failure because `D.foo()`
shouldn't be allowed to throw when `C.foo()` doesn't.  And that's
because since `C.foo()` doesn't throw, the call to `dc.foo()`
shouldn't be able to.  (IMO)

**Compile command:**
chpl subclass-throws.chpl -o subclass-throws

**Execution command:**
./subclass-throws -nl 1

**Associated Future Test(s):**
None yet

### Configuration Information

```
fortytwo@magrathea:~/src/chpl$ chpl --version
chpl Version 1.16.0 pre-release (23d7df3)
Copyright (c) 2004-2017, Cray Inc.  (See LICENSE file for more details)
fortytwo@magrathea:~/src/chpl$ printchplenv --anonymize
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
  CHPL_JEMALLOC: jemalloc
CHPL_MAKE: make
CHPL_ATOMICS: intrinsics
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_WIDE_POINTERS: struct
CHPL_AUX_FILESYS: none
fortytwo@magrathea:~/src/chpl$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
```

**Comment by ben-albrecht** [comment]
Probably of interest to @psahabu

**Comment by psahabu** [comment]
Thanks @cassella! We've known that dynamic dispatch doesn't work with error handling at the moment, the goal is to get this fixed by the next release.

**Comment by cassella** [comment]
Ah, ok.  I'd looked over the "Implement an error handling model" issue for "class", "subclass", and "method".  Feel free to close this issue if you're tracking it elsewhere.
