### ISSUE TITLE
Improve affinity when NIC registering memory

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#6320]
Under comm ugni we grab a large chunk of memory from the system for our heap, and then register it all with the NIC. Then any allocations from the chapel allocator come out of this registered heap. This has the benefit of ensuring all allocations are registered, so we don't have to trampoline/bounce communication through a registered segment. Unfortuantely, registering touches pages, so we with first-touch page placement all pages have affinity for NUMA domain 0. This kills performance for things like stream and prk-stencil, where we want want large arrays to be spread across numa domains.

We need to figure out a good story here, and it looks like CHPL_LOCALE_MODEL=numa/multi-ddata isn't going to get us what we want, so perhaps we need to investigate dynamic registration so that we only register memory after we have the affinity we want. Dynamic registration has other costs associated with it so we'll need to experiment. Doing dynamic registration would also eliminate the need to set a fixed heap size, and it would improve startup times (#5680)

**Comment by ronawho** [comment]
@gbtitus This is a quickly thrown together issue just to start tracking this work. Feel free to update/improve the issue description as you see fit.

**Comment by ronawho** [comment]
Doing interleaved page placement instead of using first-touch shows some nice improvements for stream and the prk-stencil, but obviously that's not optimal.

Here's some results for 16 node ugni+qthreads with
```sh
export CHPL_LAUNCHER_REAL_WRAPPER="numactl --interleave=all"
```

| stream-ep       | Perf    |
| --------------- | ------- |
| u+q first-touch | 40 GB/s |
| u+q interleaved | 70 GB/s |
| gn-mpi          | 98 GB/s |

| stencil-opt     | Perf             |
| --------------- | ---------------- |
| u+q first-touch | 195,000 MFlops/s |
| u+q interleaved | 275,000 MFlops/s |

for stencil-opt, gn-mpi gets poor performance, because there's actually communication

**Comment by gbtitus** [comment]
Just clarifying -- for the 16-node ugni+qthreads stream-ep results you quoted above, you must have been running localeModel=flat or else localeModel=numa but with the multi-ddata feature turned off, right?  (Had it been localeModel=numa with multi-ddata turned on we should have seen something like 96 GB/s.)  Also, presumably this was with the `stream-ep.ml-execopts` setting of `--m=357739200`?  And, which `craype-hugepages` module were you using?

**Comment by ronawho** [comment]
Yeah, I'm running with `CHPL_LOCALE_MODEL=flat`, the default multi-locale problem size(`--m=357739200`), and the "default" huge pages (16M)

**Comment by benharsh** [comment]
@gbtitus : should this issue be updated/closed now that we have dynamic registration?

**Comment by gbtitus** [comment]
@benharsh : it's better but not completely done yet.  With the advent of #6947 and follow-ons we're doing fine based on first-touch for arrays of POD types, but we could do better for non-POD arrays, such as the atomic array elements in ra-atomics.  For those, with NIC registration we're still getting all the memory on NUMA node 0.  There are kernel fixes on the way that will help, but once they arrive we'll need to do some work to take advantage of them.

**Comment by ronawho** [comment]
IMO this issue is done, and we now have https://github.com/chapel-lang/chapel/issues/6949 to track future work

**Comment by gbtitus** [comment]
Well, I definitely agree it's better to have one open issue than two, and #6949 certainly seems more alive at this point.  So if you want to kill off this one that's okay with me.  Is there any benefit to duplicating the mention of interleaved memory affinity into #6949?  I.e., are there situations or apps where that can do us more good than setting locality in a more principled way?  If so then some mention should be dragged over there.

**Comment by ronawho** [comment]
This was resolved with dynamic registration for ugni with https://github.com/chapel-lang/chapel/pull/6947. Followups are being tracked in https://github.com/chapel-lang/chapel/issues/6949
