### ISSUE TITLE
Move --no-local performance testing from 1-node-xc to chapcs

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#6321]
1-node-xc (--local vs. --no-local as well as gcc vs. cce vs. icc) performance testing isn't very reliable/stable, so we often ignore it during  performance triage. We had some surprising --no-local performance regressions last release, so we want to track it better in the future. Move --no-local performance testing to the chapcs cluster to make it more reliable.

**Comment by lydia-duncan** [comment]
Also, revcomp can't run on Crays, so this will enable us to have --no-local data for it at all (or if it doesn't, we should take the additional steps to get --no-local data for it)
