### ISSUE TITLE
bad error for bad invocation of parallel iterator

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#6342]
### Summary of Problem

The compiler generates an internal error if a user makes a bad invocation of a parallel iterator.  It seems as though this internal error could be changed to a user error as a starting point (it's not a terrible error message, but it doesn't get printed out since it's internal), but I couldn't quickly figure out where that was happening.  Better would be to give the user a more specific error message pointing out that they don't need to / can't supply the iterKind argument -- that the compiler will fill that in.  But that's extra credit only.

### Steps to Reproduce

**Associated Future Test(s):**
      [`test/functions/iterators/errors/badArgs.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/functions/iterators/errors/badArgs.chpl
          ) #6341 -->

### Configuration Information

- Output of `chpl --version`: 1.16.0 pre-release (b99bdb1)

**Comment by bradcray** [comment]
@vasslitvinov -- this seems like it would be an easy one but I couldn't figure out where in the stack trace the internal error was being generated.  Want to take a look?

**Comment by vasslitvinov** [comment]
This condition is very specific to the situation where our compiler goes from the serial iterator - which is legitimately `myiter(param tag: iterKind, r: range)` at Line 6 - to its standalone counterpart, sought by adding `tag=iterKind.standalone` to the iterator call's actuals.

My proposed error message is something like this:
```
in a forall loop, the iterable expression cannot resolve to an iterator with a 'tag' formal
```

@bradcray - are you OK with that?

We could also nod towards the zippered case, where it would be **an** iterable expression. If so, how?

**Comment by bradcray** [comment]
It'd be a step forward since it'd be a user error, but I'm not sure that message would help me determine what's wrong.  What about something simply like:

``unable to resolve iterand expression``

(assuming we use that term elsewhere?).

Even better would be if we could print out the iterand that's failing to resolve (I think you're saying it'd be something like ``myiter(iterKind.standalone, 1..10, tag=iterKind.standalone)``?).  And even better would be if we could print out the candidate matches as with any other failed resolved function call.

**Comment by vasslitvinov** [comment]
The message `unable to resolve iterand expression` is likely to leave the reader wondering "why", given that there is an `iter` declaration that matches the iterable expression perfectly.

Or maybe "cannot resolve" is ambiguous in the message that I wrote. How about this:

```
badArgs.chpl:11: error: in a forall loop, it is not supported for the iterable expression to resolve to an iterator with a 'tag' formal
badArgs.chpl:6: note: the iterable expression resolves to the iterator here
```

?

**Comment by bradcray** [comment]
> The message unable to resolve iterand expression is likely to leave the reader wondering "why"

That's why I was proposing showing the signature that failed (which would show the two tag arguments) and the candidate signatures as with other unresolved functions, for uniformity.  Is that not possible (or not easily possible?)

> How about this:

If we're going to specialize the error message to the presence of the 'tag' argument, why don't we just say something like "user invocations of iterators should not supply tag arguments -- the compiler will provide them."

I was thinking that other argument errors might result in a similar error message, which is why I was suggesting making it more like a conventional unresolved call error message.

**Comment by vasslitvinov** [comment]
> That's why I was proposing showing the signature that failed (which would show the two tag arguments) and the candidate signatures as with other unresolved functions, for uniformity. Is that not possible (or not easily possible?)

> I was thinking that other argument errors might result in a similar error message, which is why I was suggesting making it more like a conventional unresolved call error message.

Currently detection of duplicate actuals happens right after parsing. The failed signature is created during forall-specific processing done in preFold(). If we simply show that signature to the user, they are likely to wonder "where does that come from".

We can detect the duplicate "tag" arguments right there in preFold() (which is my proposal). Or -- we can add generally-applicable code to resolution, perhaps at the expense of slightly slowing the compiler and leaving the unanswered question "where did that call come from".

Re candidate functions: there would not be any applicable candidates, given two "tag" arguments.
I could produce a list of all visible candidates. I doubt that would add value compared to simply pointing to the iterator that has an inappropriate tag formal.

> If we're going to specialize the error message to the presence of the 'tag' argument, why don't we just say something like "user invocations of iterators should not supply tag arguments -- the compiler will provide them."

Sure, I can do that.

**Comment by vasslitvinov** [comment]
I got a fix. Will merge after #7147.
