### ISSUE TITLE
Refresh parIter.chpl primer

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#6343]
Looking at the parIter primer while looking at issue #6337, it seems to me that we should improve it in the following ways:

* describe the definition of standalone iterators prior to leader-follower.  They're strictly simpler to write and understand, and more likely to be understood and defined by someone trying to write their first parallel iterator.

* clearly state the current requirement that to resolve parallel iterators, the user must provide a serial iterator as well (something that I hope we'll be able to relax over time -- see issue #6339).

There may be other things that should be improved as well -- these were just two that jumped out at me.  (edit: See also the notes in issue #8364).

**Comment by ben-albrecht** [comment]
@bradcray - removing `[good first issue]` label here because this task requires an deeper understanding of parallel iterators in Chapel than I'd expect a first-time contributor to know. Let me know if you disagree.
