### ISSUE TITLE
Feature request : a better error message for task-intent errors?

### ISSUE THREAD

**Issue by npadmana** [chapel-lang/chapel#6344]
The following code produces an error ``illegal lvalue in assignment`` ---
```
record Rec {
  var arr: [1..10]real;
}

var r: Rec;

// This version yields an illegal lvalue
cobegin {
  r.arr[1]=1;
  r.arr[10]=10;
}
```
Would it be possible for the compiler to provide some more information here -- ideally hinting that the default task-intent here makes ``r`` a constant? For some reason, it always takes me way too long to realize what is going on here.

This case got more confusing for me because the following **does** work ---
```
record Rec {
  var arr: [1..10]real;
}

var r: Rec;

// This version works
ref A = r.arr;
cobegin {
  A[1] = 1;
  A[10] = 10;
}
```
That is, pulling out a reference to the underlying array changes the default task intent assigned. Is this expected behavior, or a lucky work-around?

**Comment by jabraham17** [comment]
https://github.com/chapel-lang/chapel/pull/24089/ added nicer error messages for task intent errors with records. I think `test/parallel/taskPar/taskIntents/errorAccessRecordField.chpl` is a test that already exists that should cover the cases in the OP.
