### ISSUE TITLE
Remove chpl_comm_make_progress

### ISSUE THREAD

**Issue by sungeunchoi** [chapel-lang/chapel#6349]
There are no more call sites for this function.  It was apparently used in the comm caching code but is no longer needed.

**Comment by bradcray** [comment]
Your chance for a 1.16 contributor credit?  :)

**Comment by AnubhavUjjawal** [comment]
@ronawho @sungeunchoi  As much as I could understand, we would need to keep the inline `chpl_comm_make_progress ` and its references in  `runtime/src/comm/ofi/comm-ofi.c` and remove it from other places??

**Comment by gbtitus** [comment]
> [...] keep the inline `chpl_comm_make_progress ` and its references in `runtime/src/comm/ofi/comm-ofi.c` and remove it from other places??

That, and make it file static because now it would be private to comm=ofi, and remove the leading `chpl_comm_` in its name, since that implies it's part of the public runtime comm layer interface.

**Comment by gbtitus** [comment]
@AnubhavUjjawal note that comm=ofi is still somewhat in initial development and not fully supported yet, plus this is really just a bookkeeping/clerical change.  If you're looking for things to do which will have a real impact I'd skip this one.   :-)
