### ISSUE TITLE
make check doesn't work with ./configure

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#6352]
Running the following sequence, without any Chapel environment variables set, results in a failed `make check`:

``` bash
./configure
make
make check
```

The `./configure` step prints out this:
```
  If the configuration above is appropriate, build Chapel with:

make
make check

  and possibly install it with

make install
```

But `make check` fails in that order like so:
```
$ make check
[Info] Running minimal test script: $CHPL_HOME/util/test/checkChplInstall
[Fail] chpl not found. Make sure it available in the current PATH.
Makefile:179: recipe for target 'check' failed
make: *** [check] Error 1
```

We need to do either or both of:

a) Update `./configure` to suggest running `make check` after `make install` and point out that chpl must be in your path at that point
b) Update `make check` to auto-detect the location of the built chpl to run

**Comment by mppf** [comment]
@ben-albrecht - I'm interested in any thoughts you have about how to handle this. Thanks.

**Comment by ben-albrecht** [comment]
Option b seems less fragile.

**Comment by mppf** [comment]
Right, but I presume that currently `make check` works this way because we intend it to work with an already installed `chpl` (e.g. with the module?). Am I wrong about that?

**Comment by bradcray** [comment]
I'm not that familiar with Chapel's ``configure`` yet...  If you're not going to ``make install``, does ``configure`` have a purpose?  If not, I'd simply reorder the instructions as proposed in (a).

**Comment by mppf** [comment]
@bradcray - `configure` doesn't add any functionality we were missing *except* for enabling `make install`.

However, I'd like new Chapel users to be able to run
```
  ./configure
  make
```

just like they do with most other *nix source tarballs...

I think some of those people will try to use Chapel without installing it. But, we could decide that's not something we want to support. (After all, they can install it to ~/bin e.g.).

Even so, if we were pursuing (a) (changing the suggested next steps printed by `configure`), I don't think it would be too hard to indicate that they must add `chpl` to their path before `make check` will work.

`configure` lets you set the configuration (including e.g. `CHPL_TASKS`) and destination directory for installation. But, unlike the usual Chapel way, these settings are stored in a file instead of in environment variables. (And the PATH is not updated, in particular).

**Comment by bradcray** [comment]
That makes me think that approach (a) seems both appropriate and simple to implement.

**Comment by ben-albrecht** [comment]
I take back my original comment. I don't think it's unreasonable to expect users to add the install path to their `$PATH` before trying `make check` after a `make install` -- it even says this in the error message:

```
[Fail] chpl not found. Make sure it available in the current PATH.
```

It might be worth noting this caveat in the build instructions, if we think users will stumble across it.
