### ISSUE TITLE
Implement "bounded-coforall" optimization for remote coforalls

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#6357]
https://github.com/chapel-lang/chapel/pull/5018 implemented an optimization for local bounded-coforalls that limited how much we manipulated the EndCount for coforalls whose trip-count can be determined before execution (i.e. optimized coforalls over ranges, domains, and arrays.)

We should do a similar optimization for remote coforalls such as:

```chapel
coforall loc in Locales do on loc { }
```

We weren't sure how much of an impact this would have because we figured the cost of manipulating the EndCount was probably small compared to the cost to do a remote fork, but the performance differences seen in https://github.com/chapel-lang/chapel/issues/6356 indicate that this optimization is probably worthwhile.

**Comment by ronawho** [comment]
Here's a first attempt at this optimization: https://github.com/ronawho/chapel/tree/bounded-remote-coforall-opt

It's admittedly hard to read/follow and we could use some helper function for building the coforall innards, but it seems to work (passes full gasnet testing).

Here's some perf numbers:

For the `coforall loc in Locales do on loc {}` microbenchmark in https://github.com/chapel-lang/chapel/issues/6356#issuecomment-305323307, this takes 16 node from 7.25 seconds down to 2.7 for network atomics, while processor atomics go from 3.15 seconds to 2.95 seconds, so network atomics seem like the right choice for remote coforalls after this optimizations goes in. Here's the full table for -nl1 through -nl32 showing that as we get to higher locale counts, network atomics pay off more and more:

| -nl | u+q AMO | u+q procssor | u+q opt AMO | u+q opt processor |
| --- | ------- | -------------| ----------- | ----------------- |
| 1   |  .13s   |  .13s        |  .13s       |  .13s             |
| 2   | 1.11s   |  .48s        |  .67s       |  .47s             |
| 4   | 2.02s   |  .84s        |  .95s       |  .80s             |
| 8   | 3.75s   | 1.59s        | 1.55s       | 1.51s             |
| 16  | 7.25s   | 3.15s        | 2.69s       | 2.95s             |
| 32  | 14.6s   | 6.35s        | 5.05s       | 5.99s             |


Impact on actual benchmarks looks good too:

| Benchmark   | u+q AMO      | u+q optimized |
| ----------- | ------------ | ------------- |
| lulesh      | 3.2s         | 2.2s          |
| stencil prk | 98 GFlops/s  | 104 GFlops/s  |
| stencil-opt | 193 GFlops/s | 237 GFlop/s   |
| prom stream | 440 GB/s     | 645 GB/s      |

**Comment by ronawho** [comment]
@benharsh any thoughts on merging that branch as-is vs. cleaning it up prior to merging?

My preference would be to merge something very close to that branch to start getting the performance benefits and just make a new issue to track the cleanup. Granted I was supposed to do cleanup on the local coforall version of this optimization too and I haven't gotten around to that yet, so I could easily be convinced to make cleanup a precondition to merging as a forcing function to do the cleanup.

**Comment by benharsh** [comment]
I'd probably lean towards using this as a forcing function to do some cleanup.

**Comment by ronawho** [comment]
Ok, works for me. I'll add the microbenchmark today or tomorrow to the 16 perf testing, and work on cleaning up the branch for a PR after I get back next week.

**Comment by ronawho** [comment]
https://github.com/ronawho/chapel/tree/bounded-remote-coforall-opt-2 is the cleaned up version of this optimization. It's not passing full testing yet, but I wanted to check in and see if you're happy with its cleanup/readability

**Comment by benharsh** [comment]
Much nicer, thanks!
