### ISSUE TITLE
Inline proc : making return optional with exit()

### ISSUE THREAD

**Issue by TomsyPaul** [chapel-lang/chapel#6374]
In an inline proc that returns something, the return statement is compulsory in every branch, even in one which uses exit(). It would be better and more appropriate, to make return optional for such branches. 

https://sourceforge.net/p/chapel/mailman/message/35874026/

**Comment by lydia-duncan** [comment]
I added some futures and regular tests to track this in #6377

**Comment by lydia-duncan** [comment]
On the mailing list, @bradcray pointed out that "halt()" does not trigger the same error message, implying that this might be an easy fix.  I may try to get to that in the next couple of days

**Comment by TomsyPaul** [comment]
Just to mention - An iterator has no issues with exit().

**Comment by daviditen** [comment]
PR #6403 was merged today and should do what you expect.  I'm going to leave this issue open until it has been through nightly testing tonight.

**Comment by TomsyPaul** [comment]
Just to mention - An iterator has no issues with exit().

**Comment by daviditen** [comment]
Nightly testing is looking good, so I think this can be closed now.
