### ISSUE TITLE
In "-f<filename>" , <filename> should allow for comments

### ISSUE THREAD

**Issue by npadmana** [chapel-lang/chapel#6398]
It is often very useful to start a Chapel program passing `config` arguments in a file via ``-f<filename>``. However, this file currently doesn't allow for comment lines -- but this would be very useful to document the various options for an end-user (who is just running the code, but isn't going to read it).

**Comment by ben-albrecht** [comment]
This is an easy fix, and makes sense to me. I see no reason not to make this change. What style of comments should be supported? `//` only or `/* */` comments as well?

**Comment by npadmana** [comment]
I  was originally just thinking of lines beginning with `#` for simplicity, but I have no strong preferences here.

**Comment by ben-albrecht** [comment]
I also have no strong opinion on the comment character(s).

**Comment by tmacd9** [comment]
I also think lines starting with # is the right way to go.

**Comment by ben-albrecht** [comment]
Related: Is this feature documented anywhere besides the `--help` output of a Chapel program?

**Comment by vasslitvinov** [comment]
What Tom said.

**Comment by ben-albrecht** [comment]
> I was originally just thinking of lines beginning with `#` for simplicity

> I also think lines starting with # is the right way to go.

>What Tom said.

👍  Works for me!

**Comment by mppf** [comment]
I don't think I was aware we supported this. Anyway, I think `#` is the appropriate comment character in this case & that it's worth supporting comments in such files.

**Comment by bradcray** [comment]
I also agree with the feature proposal and the use of `#` as the delimiter.

To @ben-albrecht's question about documentation, I was expecting to find it [in the executing Chapel programs insturctions here](http://chapel.cray.com/docs/latest/usingchapel/executing.html#setting-configuration-variables) but did not.

**Comment by ben-albrecht** [comment]
Implemented in #6583
