### ISSUE TITLE
DGEMM PRK performance rate computation is incorrect

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#6413]
Only `iterations-1` trials are actually timed, but the computation still does `t.elapsed()/iterations`

Instead of `for niter in 0..#iteration` I think it should be `for niter in 0..iteration` to match the reference and the rest of our PRK implementations. There may be some places that need to be changed from `iterations` to `iterations+1` then, but you should be able to remove the `iterations==1` checks from the trial loops.

I was doing 3 iterations while debugging and 20 iterations while getting ready to report numbers for #6388 and for some reason I was seeing very different performance rates.

**Comment by ronawho** [comment]
@ben-albrecht and/or @e-kayrakli mind taking a look at this?

**Comment by e-kayrakli** [comment]
:( I'm on it. It looks like the same bug is there at least in the SERIAL version in the base PRK repo

**Comment by ronawho** [comment]
Thanks @e-kayrakli. 

I think this inflates our performance compared to the OpenMP version, which is probably why your `Chapel Carr` version was slightly outperforming OpenMP.

**Comment by e-kayrakli** [comment]
Yes, makes sense. I wonder what would the comparison look like with #6414. I'll try to that but not today.

**Comment by ben-albrecht** [comment]
#6414 merged - thanks @e-kayrakli !
