### ISSUE TITLE
Check .graph/GRAPHFILES as part of a smoke test

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#6422]
We have some code in start_test that validates that all .graph files in the test directory are listed in a *GRAPHFILES file and that for each file listed in the *GRAPHFILES files, there is a corresponding .graph file in the test directory. i.e. we ensure there is a 1:1 mapping of .graph files that exist and that are listed in one of the GRAPHFILES. 

We should pull this code out into a helper script and run it as some sort of smoke test or linter or something since it's easy to get this wrong and have a bunch of nightly jobs mail warnings (#6421, and several other cases.)

It's the code inside of [start_test::check_for_duplicates()](https://github.com/chapel-lang/chapel/blob/main/util/test/start_test.py#L1187)

Edit: we'd probably add a call to this helper script in a new entry under jobs in [this file](https://github.com/chapel-lang/chapel/blob/main/.github/workflows/CI.yml).  To test that works, it should trigger a 7th "check" when opening a PR on the repo (remembering that sometimes it takes a second for the non-DCO checks to turn up)

**Comment by Shivansh-khare** [comment]
if I can help in this issue...

**Comment by pree-T** [comment]
Is this issue still open?

**Comment by lydia-duncan** [comment]
I believe so, yes
