### ISSUE TITLE
Modifying Set Operators + and &

### ISSUE THREAD

**Issue by TomsyPaul** [chapel-lang/chapel#6438]
Dear all,

The set operators for Union and Intersection are now + and & respectively. I suggest \\/ and /\ respectively.

Pros:
1. Resemblance to the original mathematical set operators.
2. Both are Lower letters in keyboard (no need of using shift) and are located nearby, so easy to type.

Cons:
Please discuss..

**Comment by bradcray** [comment]
Personally, I feel disinclined to add new operators to Chapel at this stage of the game, particularly ones that don't have a precedent (that I'm aware of) in other languages.  At times, we've discussed possible ways to permit users to create their own operators in future drafts of the language (some versions of which would permit users to define operators like this themselves), but that feature is pretty far off in the future at present.

**Comment by bradcray** [comment]
Closing this because I don't think it has resonated with others.
