### ISSUE TITLE
Parallel Algorithms using domain maps

### ISSUE THREAD

**Issue by Praveenv98** [chapel-lang/chapel#6454]
Hi
I'm new to Chapel language i find it during my GSoC proposal time. I have a doubt regarding using domain maps in parallel algorithms,  "Using domain maps in parallel algorithms, the programmers don't have to worry about their initial placement of data in the global address space" what this sentence means exactly. I have understand what domain map are ? And how to use it. But i didn't find meaning for this sentence clearly. Whether domain is for only linear data structures or it can be used for any user-defined data type ?
Thank You so much

**Comment by bradcray** [comment]
Hi @Praveenv98 : What is the context of the sentence you quote?

> "Using domain maps in parallel algorithms, the programmers don't have to worry about their initial placement of data in the global address space"

**Comment by Praveenv98** [comment]
Hi @bradcray 
https://github.com/STEllAR-GROUP/hpx/wiki/GSoC-2017-Project-Ideas#distributed-component-placement
I find it in this link..

**Comment by bradcray** [comment]
That page was created by the Ste||ar group, not the Chapel group, so I think you'd need to ask them what they mean by it.  Otherwise, I'd just be guessing.

**Comment by Praveenv98** [comment]
Okay I will..
Thank You so much @bradcray
