### ISSUE TITLE
Calling constructor of a class within a module requires explicit importing of the module

### ISSUE THREAD

**Issue by saru95** [chapel-lang/chapel#6483]
Calling constructor of a class within a module requires explicit importing of the module. It should work without importing the module as both the module and the code using it is present within the same file.

Snippet 1:

```chpl
module M {
         class A {
                 proc A(a: int) {
                         writeln("hello");
                 }
         }
 }
 var obj = new M.A(23);
```

Snippet 2:

```chpl
module M {
 	class A {
 		proc A(a: int) {
 			writeln("hello");
 		}
 	}
 }
 use M;
 var obj = new M.A(23);
```

Running Snippet 1 gives the error `"error: unresolved call 'A.init(23)` whereas Snippet 2 runs fine.

**Comment by lydia-duncan** [comment]
This was resolved with #6810 and friends last month (thanks Mike!)
