### ISSUE TITLE
Convert random number generators to record-wrapped classes

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#6493]
It seems unfortunate that our random number generators are raw classes and require explicit user deletes.  Is it time to make them record-wrapped classes, as a case of using Owned/Shared?

**Comment by bradcray** [comment]
@mppf: As the most recent author of RNG stuff and the author of Owned/Shared, what do you think about this?

**Comment by mppf** [comment]
Mainly, I suspect we might run into compiler bugs if/when we try to make appropriate type aliases.
But I don't see any problem with attempting it. I suspect we'd need to make e.g. RandomStream be a record that contains an Owned(RandomStreamImpl) or a Shared(RandomStreamImpl). The odd thing here is that I'm not sure I can justify choosing Owned or Shared. Perhaps we need RandomStream and SharedRandomStream? Or maybe it is really better to have users wrap with Owned/Shared? (e.g. new Owned(new RandomStream(...)) ).

**Comment by cassella** [comment]
Does the delete-free support obviate the need to do anything here?

**Comment by mppf** [comment]
I think it's reasonable for users to write `owned RandomStream` etc. However others might disagree.

**Comment by bradcray** [comment]
I agree and will close this, thanks!
