### ISSUE TITLE
Should virtual methods disable ref-if-modified?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#6497]
(Continues issue #5219).

Reading about some conceptually similar inference in D made me wonder if we should require 'ref' or 'const ref' be specified for array arguments on overridden functions. Or if we should handle this case some other way.

In particular, if there are two classes, Parent and Child, where Parent : Child, that both supply 'method' taking in a single array argument, what if Parent modifies 'method' but Child doesn't? Or vice versa?

Here is a specific example:

``` chapel

class Parent {
  proc method( a: [] ) {
    // 'a' not modified, so a will be inferred to be 'const ref' intent
  }
}

class Child : Parent {
  proc method( a: [] ) {
    // 'a' is modified, so 'a' is inferred to be 'ref' intent
     a = 1;
  }
}

var x: Parent = new Child();
const A:[1..2] int;
x.method( A );
writeln(A);
```

compiles and runs with master currently but modifies a `const` variable.

Possibilities:
 * error if virtual method has different inferred 'ref' vs 'const ref' for an argument
 * error if virtual method has 'ref' when overridden method has 'const ref' inferred
 * default not available for virtual method array arguments (must specify 'ref' or 'const ref')
 * default for virtual method array arguments is 'const ref'
 * ?

**Comment by mppf** [comment]
tagging @benharsh, @bradcray, and @vasslitvinov since we had the discussion about ref-if-modified.

**Comment by mppf** [comment]
D answers "no" to an attribute inference question when:
 * function could be linked externally
 * function is possibly recursive (through other functions potentially)
 * function attempts to test that attribute

**Comment by bradcray** [comment]
My instinct would be to permit such argument intents to be inferred as usual, but to complain if the intents (whether specified or inferred) don't match across a set of overrides.

While arrays arguably exacerbate this issue due to the ref-if-modified interpretation of blank intents, the question seems more general to me -- i.e., "What should happen if a chain of virtual method overloads disagree in argument intent?"  The following code suggests that currently a difference in intents does not result in a compiler error, but does cause surprising execution-time behavior:

```chapel
class C	{
  proc foo(in x: int) {
    x += 1;
    writeln(x);
  }
}

class D: C {
  proc foo(ref x: int) {
    x += 2;
    writeln(x);
  }
}

var myC	= new C();
var myD	= new D();
var myC2: C = new C();
var myD2: C = new D();

var x =	1;
myC.foo(x);
writeln(x);
myD.foo(x);
writeln(x);
myC2.foo(x);
writeln(x);
myD2.foo(x);
writeln(x);
```

Whereas changing both intents to either `in` or `ref` seems to lead to a better result.

**Comment by mppf** [comment]
@bradcray - it took me a minute to figure out what was going on in your example, but I see now that `myD2.foo(x)` seems to be calling the version of `foo` in C. In that example, that might be surprising, but it's consistent with an interpretation that functions with different intents are different functions... because they could be possibly called in different contexts.
That made me wonder how virtual method calls interact with return intent overloading... and the answer is assertion errors in the compiler! For example:
``` chapel
class C {
  proc foo(ref x) ref {
    writeln("C.foo(ref) ref");
    return x;
  }
  proc foo(x) {
    writeln("C.foo()");
    return x;
  }
}

class D: C {
  proc foo(ref x) ref {
    writeln("D.foo(ref) ref");
    return x;
  }
  proc foo(x) {
    writeln("D.foo()");
    return x;
  }
}

var myC = new C();
var myD = new D();
var myC2: C = new C();
var myD2: C = new D();

var x = 1;
var y = 0;
writeln("y = myC.foo(x)");
y = myC.foo(x);
writeln("myC.foo(x) = y");
myC.foo(x) = y;
writeln("y = myD.foo(x)");
y = myD.foo(x);
writeln("myD.foo(x) = y");
myD.foo(x) = y;
writeln("y = myC2.foo(x)");
y = myC2.foo(x);
writeln("myC2.foo(x) = y");
myC2.foo(x) = y;
writeln("y = myD2.foo()");
y = myD2.foo(x);
writeln("myD2.foo() = y");
myD2.foo(x) = y;
```

Anyway, if that example is to work, we need to put the return intent overloads of `foo` into different "slots". However I believe it's sufficient to do so based upon the return intent (and with no regard to the argument intents).

That leads me to agree with you that there should be a compilation error if the intents on a virtual method override differ. (We could allow a `ref` argument method to be overridden by a `const ref` one but that seems like a language tweak to leave for later; and anyway it's arguably better to insist they are the same).

**Comment by bradcray** [comment]
> That leads me to agree with you that there should be a compilation error if the intents on a virtual method override differ.

Cool.  Let me know if you'd like me to file my test as a future (+ issue?) or if you will.

**Comment by vasslitvinov** [comment]
Return intent overloads being "different functions" is definitely a concept that we should publicize among Chapel users.

Require the same argument intents in overriding methods is a fine solution. I do think that the ideal language would allow const ref overriding of ref intent.

**Comment by mppf** [comment]
It appears that this is still a problem - the below program (from the OP, but with the minor addition of `override`) modifies a `const` array:

``` chapel
class Parent {
  proc method( a: [] ) {
    // 'a' not modified, so a will be inferred to be 'const ref' intent
  }
}

class Child : Parent {
  override proc method( a: [] ) {
    // 'a' is modified, so 'a' is inferred to be 'ref' intent
     a = 1;
  }
}

var x: Parent = new Child();
const A:[1..2] int;
x.method( A );
writeln(A);
```

**Comment by jabraham17** [comment]
I think this can be closed since we are deprecating `ref-maybe-const` and plan to remove it
