### ISSUE TITLE
Add Chapel support to Google prettify

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#6501]
As I understand it from [StackOverflow's markdown help page](https://stackoverflow.com/editing-help#syntax-highlighting), if we were to add Chapel support to [Google's prettify](https://github.com/google/code-prettify), we'd get syntax highlighting for code on StackOverflow which seems very attractive.

TODO:
- [x] verify that the above is true
- [ ] create and submit Chapel support to prettify

**Comment by ronawho** [comment]
Related to #5908

**Comment by victor-ludorum** [comment]
@bradcray Hello!! I want to work in this issue . Kindly guide me ..

**Comment by bradcray** [comment]
Hi @victor-ludorum : I'd be very happy to see this done, but I don't know enough about Google prettify to be able to provide very deep guidance beyond some simple pointers.  However, they look like they have pretty good documentation about how to add new languages in their [README](https://github.com/google/code-prettify), and a common approach is to find an existing language that is sufficiently similar to Chapel and follow its example.  That's how I'd start into this anyway.  It may also be useful to look at other tools that support Chapel highlighting, several of which are noted in issue #5908.

**Comment by victor-ludorum** [comment]
Thanks sir for your suggestion 😊 .

**Comment by bradcray** [comment]
Hi @victor-ludorum : Thanks for [your PR for](https://github.com/google/code-prettify/pull/518) this.  I'm not sure what it will take for it to be merged to Google prettify—they seem to have quite a backlog.  Have you come across any documentation indicating steps that should be taken to get PRs to their repository reviewed and merged?

**Comment by victor-ludorum** [comment]
@bradcray  Yes sir , I have signed Google  Contributor License Agreement (CLA) as mentioned there .

**Comment by aditmehta9** [comment]
@victor-ludorum Hey friend, I think you have missed the keyword 'sync'. I've reviewed that in your PR.

**Comment by victor-ludorum** [comment]
Thanks @aditmehta9  for specifying . I have added it 😊

**Comment by krishnadey30** [comment]
@bradcray I checked the google prettify github. They also say prettify is used by Stackoverflow. I would like to take this issue.

**Comment by krishnadey30** [comment]
@bradcray I have created a PR https://github.com/google/code-prettify/pull/588

**Comment by bradcray** [comment]
Hi @krishnadey30 : Unfortunately, there's already a PR for this as noted, albeit somewhat subtly, in a [comment above](https://github.com/chapel-lang/chapel/issues/6501#issuecomment-352645604):

https://github.com/google/code-prettify/pull/518

Unfortunately, it's been open for over a year now with no action on it.  I'm not sure how to get the process unstuck, so filed an issue requesting Chapel support to the code-prettify repo recently:

https://github.com/google/code-prettify/issues/587

But that hasn't resulted in any action either.  It might be worth comparing your implementation to the previous to see how they compare.

I mostly don't know how to move this forward if the code-prettify maintainers don't choose to act on it.

**Comment by krishnadey30** [comment]
@bradcray  Sorry for not checking the message properly. I checked it now. I went through the PR and found that some changes are needed.
For eg: null is used instead of nil. Keywords and types are mixed. 
@victor-ludorum It will be good if you can update the PR.

Shall I close my PR?

**Comment by bradcray** [comment]
I think we should do what we can to only have one best PR open so that reviewers on the code-prettify team who don't know Chapel will not have to choose between them and guess which is better; but it doesn't really matter to me which one is open.  I would guess that we've added some keywords to the language since Victor opened his, so imagine that the best PR might be a blend of the two?

**Comment by krishnadey30** [comment]
@bradcray I will once check @victor-ludorum PR properly and will update my files if I missed something.

**Comment by krishnadey30** [comment]
Hey @ben-albrecht I will try to modify the PR

**Comment by bradcray** [comment]
It looks as though SourceForge has moved away from Google Prettify due to lack of support and active development (as we've experienced).  So I'm closing this issue in favor of #16454.

**Comment by bradcray** [comment]
Thanks to @victor-ludorum and @krishnadey30 for wrestling with this, and sorry to set you up for frustration (I'm frustrated by it as well).
