### ISSUE TITLE
Alternative design for ambiguity in return intent overloads

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#6510]
This issue exists to document a language design alternative, instead of storing that information in the language specification. This issues is a follow-on to PR #6435.

If you have
``` chapel
var g = 1;
proc f() ref { return g; }
proc f() ref { return g; }
proc f() const ref { return g; }
writeln(f());
```

the current language design/compiler implementation is to raise an ambiguity error immediately. A reasonable design alternative might be to allow that program to compile and run but to raise an ambiguity error when that return intent overload is used:

``` chapel
var g = 1;
proc f() ref { return g; }
proc f() ref { return g; }
proc f() const ref { return g; }
f() = 3;
```

**Comment by mppf** [comment]
I think that the current behavior is better because I think it's better not to be surprised by compilation errors for code that isn't called yet. (And yes I think we should type-check functions that are not called).

If the `f() ref` overloads in the example were not meant to be called, why are they defined at all?

**Comment by mppf** [comment]
tagging @vasslitvinov - in case you want to document your viewpoint for the other design.

**Comment by vasslitvinov** [comment]
If we have two function declarations that are ambiguous and are never invoked, they are not flagged as an error:

``chpl
proc g() {}
proc g() {}
f();
```

By Michael's argument, "if they were not meant to be called, why are they defined at all?"

OTOH the ambiguous decls could be not entirely dumb. Ex. they could result from importing modules or where-clauses being true under the same conditions that guide param IFs the other way. Admittedly, such a scenario is much less likely to occur.

**Comment by mppf** [comment]
Since this is a language design alternative that is not what we went with, I'm going to close this issue. The information here will remain available.

Also, if we decide to allow some return intent cases that are currently an error, that would be non-breaking.
