### ISSUE TITLE
Convert tests from using explicit constructors to initializers

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#6530]
Here are all the tests that rely on explicit constructors that don't have an
equivalent in the initializers directory (as of June 21, 2017,  there are
132 of these tests).  These should be updated to use initializers.  That
may not be possible yet for all of them; if so, it is sufficient to note *why*
they couldn't be updated yet and come back to them when that issue is
resolved.

If a constructor is converted that could trivially be Phase 1 (but isn't
because that would require writing super.init() at the end of the body),
please mention it at [this url](https://gist.github.com/lydia-duncan/5842808446e845218646ca3fe5acfada).

If a constructor is converted that could benefit from param and type fields
being "phase independent", please mention it at [this url](https://gist.github.com/lydia-duncan/11f694326f7f9036518c3aa1a2ca4b08).

If a constructor is converted that could benefit from const fields being
reassignable in Phase 2, please mention it at [this url](https://gist.github.com/lydia-duncan/5943b5225dfe57a51e299cece39f13f3)

Note, this list does not include futures.

Known failure categories (i.e., if a test cannot use initializers because of
these reasons, just mark it and move on):
- nested records and classes (mostly just when generics are involved)
  - [ ] test/studies/amr/lib/amr/BergerRigoutsosClustering.chpl
- secondary initializers
- inheritance when both parent and child define a zero-argument initializer
- inheritance when any class in the tree does not explicitly define an initializer
  - but only when --force-initializers is not thrown (though there are some limits
    there as well, so it might be best to punt anyways.  Ask me if you want to try
    anyways)
    - [ ] distributions/bradc/assoc/userAssoc-domain-priv-check
    - [ ] distributions/bradc/assoc/userAssoc-array-domain-zipper
    - [ ] distributions/bradc/assoc/userAssoc-array-noelt
    - [ ] distributions/bradc/assoc/userAssoc-array-priv-check
    - [ ] distributions/bradc/assoc/userAssoc-basic-array
    - [ ] distributions/bradc/assoc/userAssoc-basic-domain
    - [ ] distributions/bradc/assoc/userAssoc-dom-operations
    - [ ] studies/labelprop/labelprop-tweets (depends on the userAssoc helper module)
- not yet supporting certain error handling statements
  - [ ] test/studies/comd/llnl/utils/forceeam.chpl
- using nil as the default value of an argument for a class initializer
  - [ ]  test/users/shetag/objRefAsFormArg.chpl
- inserting calls to zero arg initializers when none is defined (should one be defined or should it not be generating this call?)
  - [ ] test/users/vass/km/array-of-records-crash-2.chpl
  - [ ] test/users/vass/km/array-of-records-crash-2.explicit-type.chpl

Tests to update:
---------------------
- [x] arrays/vass/const-checking.fields
  - but we might need to improve the phase 2 const checking
- [x] classes/bradc/test-class-init-blc
  - will want to update again, either with noinit or if the insertion of omitted fields changes
- [x] classes/bradc/bitOpOnClass
  - ditto to classes/bradc/test-class-init-blc
- [x] classes/claridge/baseConstructorCall
- [x] classes/constructors/arrayField-userCtor
- [x] classes/forwarding/dynDispatchVsForward
- [x] classes/deitz/constructors/test_construct1
- [x] classes/deitz/constructors/test_construct2
- [x] classes/deitz/constructors/test_generic_construct1
- [x] classes/deitz/constructors/test_generic_construct2
- [x] classes/dinan/override_default_constructor
- [x] classes/diten/test_destructor
- [x] classes/diten/test_destructor2
- [x] classes/diten/test_destructor4
- [x] classes/ferguson/const-override-bug
- [x] classes/figueroa/RecordConstructor1
- [x] classes/hilde/callUserDefaultConstructor
- [x] classes/hilde/inheritance/constructors-simple
- [x] classes/hilde/inheritance/fields
- [x] classes/stonea/recordConstructor
- [ ] classes/vass/old-destructor-name (**skip for now**)
 - this test is testing the old destructor name; let it test the old constructor name as well; we can remove it altogether when constructors are phased out
- [ ] compflags/lydia/noUseNoinit/noinitSkippedCase (compopts: 1) (**skip for now**)
- [ ] compflags/lydia/noUseNoinit/noinitSkippedCase (compopts: 2) (**skip for now**)
- [ ] compflags/lydia/noUseNoinit/noinitSkippedCase (compopts: 3) (**skip for now**)
- [ ] compflags/lydia/noUseNoinit/recordHasClassField (**skip for now**)
  - skip the above four tests until noinit has been implemented for initializers
- [x] distributions/diten/testCyclic
- [x] domains/vass/assoc-idxtype-error-2
- [x] exercises/boundedBuffer/solutions/boundedBuffer-atomic
- [x] functions/bradc/namedArgs/forceNamedArgs-createdummy
- [x] functions/bradc/namedArgs/forceNamedArgs
- [x] functions/hilde/defaultOf/precedence
- [x] functions/iterators/bradc/iterWithOnInGenericConstr
- [x] functions/iterators/claridge/recursiveIterTypeBug
- [x] functions/nspark/generic-varargs1
- [x] functions/vass/ref-intent-bug-2big
- [x] modules/standard/datetime/testDatetimeTZ
- [x] modules/standard/datetime/testTimezone
- [ ] modules/standard/datetime/testTimezoneConversions (**can't convert because of default initializer issue**)
- [x] multilocale/vass/this-in-taskfns-in-ctors
- [x] optimizations/bulkcomm/asenjo/stencilDR/v2/stencil
- [x] parallel/forall/vass/alist-error
- [x] parallel/sync/bradc/syncArrInit (**skip for now**)
  - triggers an issue in the type constructor because the field type is the generic version of range while we try to initialize it with an instantiation.
- [x] parallel/sync/bradc/syncArrInit2
- [x] parallel/taskPar/rachels/Barrier
  - Just removed, since it didn't seem to be doing anything much
- [x] reductions/bradc/manual/threeclasstypes-construct
- [x] reductions/bradc/manual/threeclasstypes-construct2
- [ ] reductions/diten/deleteReductionClass (**skip: issue with default initializer in parent class**)
- [x] release/examples/benchmarks/lcals/LCALSMain
- [x] release/examples/benchmarks/miniMD/miniMD (compopts: 1)
- [x] release/examples/benchmarks/miniMD/miniMD (compopts: 2)
- [x] release/examples/benchmarks/miniMD/explicit/miniMD
- [x] release/examples/benchmarks/shootout/chameneosredux
- [x] release/examples/benchmarks/shootout/chameneosredux-fast
- [x] release/examples/benchmarks/ssca2/SSCA2_main (compopts: 1)
- [x] release/examples/benchmarks/ssca2/SSCA2_main (compopts: 2)
- [x] release/examples/benchmarks/ssca2/SSCA2_main (compopts: 3)
- [x] release/examples/benchmarks/ssca2/SSCA2_main (compopts: 4)
- [x] release/examples/benchmarks/ssca2/SSCA2_main (compopts: 5)
- [x] release/examples/primers/learnChapelInYMinutes
- [ ] release/examples/spec/Classes/simpleConstructors (**skip: there are no initializers in the spec right now**)
- [ ] release/examples/spec/Generics/constructorsForGenericFields (**skip: ditto**)
- [ ] release/examples/spec/Records/recordCreation (**skip: ditto**)
- [ ] release/examples/spec/Records/recordDeinitializer (**skip: ditto**)
- [x] studies/590o/alaska/graph
- [x] studies/amr/advection/amr/AMR_AdvectionCTU_driver
- [x] studies/amr/advection/grid/Grid_AdvectionCTU_driver
- [x] studies/amr/advection/level/Level_AdvectionCTU_driver
- [x] studies/amr/diffusion/grid/Grid_DiffusionBE_driver
- [x] studies/amr/diffusion/level/Level_DiffusionBE_driver
- [x] studies/graph500/v2/main
- [x] studies/hpcc/STREAMS/bradc/stream-block1dpar-arr
- [x] studies/hpcc/STREAMS/bradc/stream-block1dpar
- [x] studies/hpcc/common/bradc/unit/multipleDomains
- [x] studies/madness/aniruddha/madchap/test_diff
- [x] studies/madness/aniruddha/madchap/test_gaxpy
- [x] studies/madness/aniruddha/madchap/test_likepy
- [x] studies/madness/aniruddha/madchap/test_mul
- [x] studies/madness/aniruddha/madchap/test_showboxes
- [x] studies/madness/aniruddha/madchap/mytests/par-compress/test_compress
- [x] studies/madness/aniruddha/madchap/mytests/par-reconstruct/test_reconstruct
- [x] studies/madness/aniruddha/madchap/mytests/par-refine/test_refine
- [x] studies/matrixMult/stonea/distributed/luLike
- [x] studies/matrixMult/stonea/distributed/simpleBlockDist
- [x] studies/parboil/BFS/bfs
- [x] studies/shootout/chameneos-redux/bradc/chameneosredux-blc
- [x] studies/shootout/chameneos-redux/elliot/chameneosredux-ejr
- [x] studies/shootout/chameneos-redux/hannah/chameneos-redux-cas
- [x] studies/shootout/chameneos-redux/hannah/chameneos-redux-v1
- [x] studies/shootout/chameneos-redux/hannah/chameneos-redux
- [x] studies/shootout/chameneos-redux/lydia/chameneos-redux-lydia
- [x] studies/shootout/chameneos-redux/lydia/chameneos-redux-waitFor
- [x] studies/shootout/chameneos-redux/lydia/chameneos-redux-yield
- [x] studies/shootout/spectral-norm/lydia/spectral-norm-barrier
- [x] studies/shootout/spectral-norm/sidelnik/spectralnorm
- [x] studies/shootout/submitted/chameneosredux
- [x] studies/ssca2/rachels/SSCA2_test (compopts: 1)
- [x] studies/ssca2/rachels/SSCA2_test (compopts: 2)
- [x] studies/ssca2/rachels/SSCA2_test (compopts: 3)
- [x] studies/ssca2/rachels/SSCA2_test (compopts: 4)
- [x] studies/ssca2/rachels/SSCA2_test (compopts: 5)
- [x] studies/ssca2/test-rmatalt/nondet
- [x] types/records/const-checking/constructors
- [ ] types/records/const-checking/modifies-const-fields-of-this
  - **SKIP** not valid in the initializer world
- [x] types/records/const-checking/tuples-and-records
- [ ] types/records/ferguson/copy-init/old-ctor-concrete
  - **SKIP** this is explicitly testing old behavior.  We'll likely want to just remove this test when constructors are deprecated
- [x] types/records/hilde/callConstructorThruTypeFn
- [x] types/records/hilde/callConstructorThruTypeVar
- [x] types/records/hilde/newUserDefaultCtor
- [x] types/records/hilde/newUserDefCtorInFn
- [x] types/records/hilde/sharedRefCount2
- [x] types/records/hilde/callUserDefaultConstructor
- [x] types/records/kbrady/record-in-global-tuple
- [x] types/records/noakes/return
- [x] types/records/sungeun/classInRecord
- [x] types/records/sungeun/constructor1
- [x] types/records/sungeun/ctorWithOnFn
- [x] types/typedefs/lydia/def-new-on-type-alias
- [x] types/void/void-variable-def
- [x] users/bugzilla/bug794133/bug794133
- [x] users/ferguson/refcnt
- [x] users/ferguson/recordConstructor
- [x] users/npadmana/twopt/do_smu_aos
- [x] users/npadmana/twopt/do_smu_soa
- [x] users/shetag/tensor-workaround

**Comment by bradcray** [comment]
I'll take the SSCA2 tests next.

**Comment by bradcray** [comment]
Actually, @daviditen ended up fixing the SSCA2s by rewriting them to use the standard Barrier rather than a specialized one in #6666.  Thanks David!

**Comment by bradcray** [comment]
I'm grabbing another batch of tests that I have some stake in and/or others don't:
* users/npadmana/*
* studies/shootout/*
* studies/amr/*

**Comment by bradcray** [comment]
Here's a proposed work partitioning for many of the remaining tests in the issue above, designed in part with the goal of getting many developers to try initializers out:

* @daviditen: \*diten\*, \*datetime\*, \*parboil\*, \*types\void\*
* @mppf: \*ferguson\*
* @vasslitvinov: \*vass\*
* @bradcray: \*bradc\*, exercises/boundedBuffer, \*hilde\*
* @benharsh: \*miniMD\*

My proposed approach is to write the initializer the way you would prefer to for the test, and if anything is non-trivial, to loop @lydia-duncan in.

**Comment by lydia-duncan** [comment]
This seems reasonable to me.  Be sure to check the list of known failure modes when something doesn't work out - I'd like to know about it anyways (it will help prioritize which bugs to fix first), but if there's an easy categorization, that'd be helpful.

**Comment by bradcray** [comment]
@lydia-duncan , @noakesmichael : As a heads-up, I started looking at doing some (simple) conversions of modules/ from constructors to initializers last night, having (mostly) run out of tests to convert.

**Comment by mppf** [comment]
I covered the *ferguson* ones listed in the main issue message and also  types/records/const-checking/*. See PR  #6743.

**Comment by bradcray** [comment]
Over [here](https://github.com/chapel-lang/chapel/issues/8301#issuecomment-372789330) is a list of the tests that I find to be failing if I have the compiler complain about all constructors and filter out cases in the $CHPL_HOME/modules directory that we know still exist.
