### ISSUE TITLE
Problem deinitializing local iterator variables

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#6540]
When an iterator contains local variables, and the loop invoking the iterator includes a `break`, not all iterator-local variables are deinitialized.

**Associated Future Test(s):**

test/types/records/ferguson/leak-futures/iterate-loop-break.chpl
test/types/records/ferguson/leak-futures/iterate-loop-break2.chpl
test/types/records/ferguson/leak-futures/iterate-twice-break.chpl

2019-05-23 update: the following tests now pass and do not leak due to #12963:

test/types/records/ferguson/deinit/break-in-for-iter1.chpl
test/types/records/ferguson/deinit/break-in-for-iter2.chpl

**Comment by cassella** [comment]
@mppf Is this done now?

**Comment by mppf** [comment]
yes, thanks
