### ISSUE TITLE
Error compiling code using UtilReplicatedVar

### ISSUE THREAD

**Issue by npadmana** [chapel-lang/chapel#6578]
### Summary of Problem
The code below fails to compile with the following error message ---
```
$CHPL_HOME/modules/standard/UtilReplicatedVar.chpl:126: In function 'rcReplicate':
$CHPL_HOME/modules/standard/UtilReplicatedVar.chpl:132: error: invalid ref return pair: mixing proc and iter
$CHPL_HOME/modules/internal/ChapelArray.chpl:2069: error: here
$CHPL_HOME/modules/standard/UtilReplicatedVar.chpl:132: error: here
$CHPL_HOME/modules/internal/ChapelArray.chpl:2078: error: here
```

Commenting out the line ``var D: domain(1);`` prevents the error, as does putting the definition of ``R`` into the main module.

### Steps to Reproduce

**Source Code:**

```chapel
use UtilReplicatedVar;
use Utils;

module Utils {

  record R {
    /* Note that the issue appears to be related to the domain.... if
       we comment this line out, it works again...

       Although defining R in the main module also works
    */
    var D: domain(1);
    var x : int;

    // Old-style constructor
    proc R() {
    }

    // No checks
    inline proc this(x: real): real {
      return 0.0;
    }
  }
}

proc setup() {
  return new R();
}

proc main() {
  var a : [rcDomain] R;
  rcReplicate(a, setup());
}
```

**Compile command:**
`chpl foo.chpl`

### Configuration Information
Fails on version 2659cc6b6aef4a623fbee, but I believe it works on 492429969fae6e26

**Comment by bradcray** [comment]
I took a look at this, but couldn't figure it out nor make sense of the error message.  Looks like a job for @mppf to at least interpret for us.

**Comment by mppf** [comment]
I believe PR #6585 will fix this issue. I havn't tried to explain what's going wrong in much detail, but I could do so if it matters to anybody. I expect to commit the fix soon in any case.
