### ISSUE TITLE
Compiler assertion failure for named arguments in initializers

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#6588]
### Summary of Problem
Calling a function or initializer from an initializer with a named argument results in a compile-time assertion failure.

See tests added in #6587

**Comment by benharsh** [comment]
@lydia-duncan and @noakesmichael : pinging to make sure you're aware of this.

**Comment by lydia-duncan** [comment]
Thanks, Ben!  Mike, I suspect this is the same sort of "AST not handled" issue we encountered for 'new' calls earlier.  Does that seem reasonable?

**Comment by lydia-duncan** [comment]
Resolved by #6596
