### ISSUE TITLE
Multi-threaded FFTW does not speed-up when running on qthreads

### ISSUE THREAD

**Issue by npadmana** [chapel-lang/chapel#6610]
### Summary of Problem
I noticed that when calling out to FFTW, we see only marginal improvements running under `CHPL_TASKS=qthreads` compared with `CHPL_TASKS=fifo`. We're using the FFTW pthreads threading support here, and other than changing `CHPL_TASKS`, we're running identical codes.

A summary of the timing results for `fifo` --
```
nthreads =   1, avg time to FFT =      3.297 (s)
nthreads =   2, avg time to FFT =      1.744 (s)
nthreads =   4, avg time to FFT =      0.934 (s)
nthreads =   8, avg time to FFT =      0.690 (s)
nthreads =  16, avg time to FFT =      0.377 (s)
nthreads =  32, avg time to FFT =      0.217 (s)
nthreads =  44, avg time to FFT =      0.223 (s)
```

while a similar summary for `qthreads` --
```
nthreads =   1, avg time to FFT =      2.849 (s)
nthreads =   2, avg time to FFT =      2.819 (s)
nthreads =   4, avg time to FFT =      2.850 (s)
nthreads =   8, avg time to FFT =      2.860 (s)
nthreads =  16, avg time to FFT =      2.892 (s)
nthreads =  32, avg time to FFT =      2.863 (s)
nthreads =  44, avg time to FFT =      2.512 (s)
```

### Steps to Reproduce

**Source Code:**
```chapel
use FFTW;
use FFTW_MT;
use Time;
use Random;

config const niter=10;
config const Ng=512;
const norm = 1.0/(Ng**3);
const D = {0.. #Ng, 0.. #Ng, 0.. #(Ng+2)};
const Dre = D[..,..,0.. #Ng];


proc main() {
  for ithread in [1,2,4,8,16,32,44] {
    run_one(ithread);
  }
}

proc run_one(nthreads: int) {
  var tt: Timer;
  plan_with_nthreads(nthreads);

  var AA, BB : [D] real;
  var fwd = plan_dft_r2c(Dre, AA, FFTW_MEASURE);
  var rev = plan_dft_c2r(Dre, AA, FFTW_MEASURE);
  fillRandom(AA);
  BB = AA;

  var tot = 0.0;
  for iiter in 1..#niter {
    tt.clear(); tt.start();
    execute(fwd);
    execute(rev);
    tt.stop();
    AA *= norm;

    if (iiter > 1) then tot += tt.elapsed();
    writef("Iteration %3i time %10.3dr (s)\n",iiter, tt.elapsed());

    // Verify
    const diff = max reduce abs(AA[Dre]-BB[Dre]);
    if (diff > 1.0e-13) then writeln("Max diff exceeded ", diff);
  }

  cleanup_threads();
  writef("nthreads = %3i, avg time to FFT = %10.3dr (s)\n", nthreads, tot/(niter-1));
}
```

**Compile command:**
```
CHPL_COMM=none CHPL_TASKS=fifo chpl -O --fast -o fftw-mt-fifo.x fftw-mt.chpl -lfftw3_threads -lfftw3 
CHPL_COMM=none CHPL_TASKS=qthreads chpl -O --fast -o fftw-mt-qthreads.x fftw-mt.chpl -lfftw3_threads -lfftw3 
```

### Configuration Information
```
CHPL_TARGET_PLATFORM: cray-xc
CHPL_TARGET_COMPILER: cray-prgenv-intel
CHPL_TARGET_ARCH: broadwell
CHPL_LOCALE_MODEL: flat
CHPL_COMM: ugni
CHPL_TASKS: qthreads
CHPL_LAUNCHER: aprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_MAKE: gmake
CHPL_ATOMICS: intrinsics
  CHPL_NETWORK_ATOMICS: ugni
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_WIDE_POINTERS: struct
CHPL_AUX_FILESYS: none
```

**Comment by npadmana** [comment]
@ronawho --- you might find this interesting -- another case where qthreads seems to collide with something.

@ben-albrecht -- tagging you on this as well, since this is the current slow step in our code.

**Comment by npadmana** [comment]
I'll also add that I'm puzzled by the significant difference between the timings between `qthreads` and `fifo` for 1 FFTW thread. There appears to be some significant overhead difference in calling out to C in both of these cases....

**Comment by ronawho** [comment]
Huh.. that's weird. I'll start digging into this in the next day (just got back from vacation and am still catching up on some other threads)

**Comment by npadmana** [comment]
After a little poking around in dark, musty corners, I discovered that setting `QTHREAD_AFFINITY=no` fixes this problem.

New timing results with this --
```
nthreads =   1, avg time to FFT =      2.875 (s)
nthreads =   2, avg time to FFT =      1.520 (s)
nthreads =   4, avg time to FFT =      0.797 (s)
nthreads =   8, avg time to FFT =      0.430 (s)
nthreads =  16, avg time to FFT =      0.261 (s)
nthreads =  32, avg time to FFT =      0.216 (s)
nthreads =  44, avg time to FFT =      0.186 (s)
```

@ronawho -- are there some hidden side-effects waiting to bite using this flag? I'll run this on my test program and report any issues....

**Comment by ronawho** [comment]
`QTHREAD_AFFINITY=no` should just disable pinning the underlying pthreads to cores.

So presumably FFTW is creating its own threads, which are then contending with qthreads underlying pthreads?

We've seen this sort of behavior before, when trying to interop chapel+qthreads with OpenMP code. Pinning gives threads priority scheduling, which means they'll heavily contend with other threads, even if the qthreads aren't doing any work.

**Comment by ronawho** [comment]
That said, if fftw is creating the threads, then I'm surprised that the tasking layer choice has any perf impact on the application

**Comment by npadmana** [comment]
Yes, FFTW is creating its own set of threads here. So I'm guessing those are contending with the underlying Chapel pthreads....

I'll note that the aprun launcher is starting the program with `-cc none` -- is that possibly doing something different for different tasking layers?

**Comment by ronawho** [comment]
`-cc none` just says "don't do any pinning", because we do it ourselves in qthreads.

**Comment by ronawho** [comment]
And under fifo, we just don't do any pinning at all

**Comment by npadmana** [comment]
Ok, at least for my larger test program, `QTHREAD_AFFINITY=no` did not degrade performance elsewhere, and significantly sped up the FFTW part. 

I'm happy to close this, unless you think there is a mystery that still remains....

**Comment by ronawho** [comment]
I think we can close this issue, though I'll probably open up a general issue about qthreads interop with external threading/tasking packages since we've run into this in other places, and it seems like there should be a way to have the qthreads "de-pin" or something when they're idle for long enough.
