### ISSUE TITLE
Proposal: Delete a substantial fraction of insertDynamicDispatchCalls()

### ISSUE THREAD

**Issue by noakesmichael** [chapel-lang/chapel#6615]
@benharsh recently introduced a future for initializers that demonstrates
that even a trivial use of derived classes fails.  The problem turned out to be in

void insertDyanmicDispatchCalls() in resolution/virtualDispatch.cpp

That code is somewhat convoluted and it, in turn, produces convoluted AST / C code
in certain circumstances.

I identified a simple "band-aid" that will resolve this future but will leave the problematic
code in place.  This band-aid will need to be extended to resolve a comparable problem
for uses of this.init().

I am reluctant to simply patch this code and move on although that is an option.
My preference is to delete the majority of the current implementation and revisit
it in the future if that is found to be necessary.  The alternative is to fix the current
code but I am disinclined to do that unless someone wants to defend the current
code.

The function in question runs relatively late during the "resolve" pass.
Earlier passes have implemented method calls "as if" method dispatch for classes
rely on static dispatch.  This function scans every call and converts those calls
to class methods that have overrides in derived classes to be dynamic.

This function implements dynamic-dispatch using one of two possible strategies.
There is a compiler configuration flag that has an impact on which strategy is
selected.  By default the primary strategy is "always" selected but, obviously the
parameter can be changed so that the alternative strategy may be selected.
It is possible to set the parameter so that the alternative code is, in practice,
always selected.

I did some spelunking through the Repo and, if I understand correctly, this logic
was essentially unchanged from at least 2008 until the summer of 2016 other than
some simple re-packagings.  Lydia detected an issue for super.init() in July of last
year and made a change that caused uses of super.init() to start using the alternative
code for certain derived classes.

Lydia mentioned that she had some trouble trying to modify the alternative code
and ultimately made the smallest change she could for the super.init() problem
she was handling.

I bumped the compiler configuration to lean in to the alternative path and studied
the resulting AST/C code.  As always I may be missing something but I am pretty
sure the generated code "usually works" but "doesn't make sense".  However I know
that 67 single-locale tests fail with this configuration.  I haven't determined why
yet.

I think the best course of action is to simply delete the alternative path for now
and develop an alternative implementation if performance profiling demonstrates
a need.

The alternatives are to apply band-aids and move on, or try to fix the current
implementation.

If there is easy consensus on this then I will act quickly on that consensus.
If there is debate then I will wait until Tuesday Jul 11 and then act appropriately.

**Comment by benharsh** [comment]
For reference, I added the future in #6603

**Comment by mppf** [comment]
I think - but I'm not sure - that you're talking about deleting the implementation of dynamic dispatch with a series of conditionals. We would only do dynamic dispatch with method tables. I think that would be fine. IIRC some of the first-class-functions code relies on the series-of-conditionals case though. But maybe it doesn't anymore? Do you know that removing the "alternative path" will pass testing now?

I expect we'll need to have insertDynamicDispatch continue to transform appropriate method calls into PRIM_VIRTUAL_METHOD_CALL.

**Comment by bradcray** [comment]
Oh, I read this the opposite way: That you were going to preserve the version that used conditionals and remove the version that used vtables.  But re-reading, I'm realizing it's not clear to me either.

**Comment by mppf** [comment]
I don't support the idea of only using the conditionals version. The generated code can get unreasonably big with that path.

**Comment by noakesmichael** [comment]
Sorry for confusion.

The virtual table path is about 6 lines of code and it's pretty clear how it works.  The code that emits
conditional expressions is about a page of code and it's much less obvious what it does and how it
works.  The proposal is to delete the code that emits nested conditionals.

There are currently tests that fail if the compiler is configured to use the code more often.  There are
also currently tests that would fail if the code were simply deleted but the ones I know of are for
initializers.  Attempting to use that code path for initializers caused the simple failure mode that BenH
reported.  It appears to me that no other tests will fail if the code is simply deleted but i have yet to
do a paratest with the path gone.

**Comment by bradcray** [comment]
My impression is that there were cases where our execution times (or compile-times?) were much better when using the conditional-based code for dynamic dispatches.  That makes me a little reluctant to throw it away, but if we aren't putting any weight on it at present then maybe my reluctance is over-cautious.

**Comment by noakesmichael** [comment]
I believe there is the potential for the conditional code to be faster; I think that's the motivation
for having developed it.  However the current implementation is whack.  It pains me to simply
add another band-aid around it but it's a valid option.  It's tempting to fix it but that will take
time and that wouldn't be a good investment in time without evidence that there is a test that
we care about that a) uses this path (presumably with a comp-opt b) see a performance boost.

If I am reading things correctly then the code doesn't get invoked with the default config expect
for the error-case with uses of super.<method>().  But I am going to do some combination of
scan comp-opts and use paratest to understand if/which tests actually try the path.

**Comment by vasslitvinov** [comment]
I am sure that performance advantage of conditionals over vtable (in some cases) will eventually come to light when users start leaning on Chapel's OO heavily.

Between now and then, it makes sense to focus on making the vtable path work well/correctly in all cases and discard the other option.

**Comment by noakesmichael** [comment]
A scan of compopts suggested that studies/comd/llnl/CoMD.chpl would be the only test that
triggered the conditional path on a branch that steers super.method() away from it.  This seems
to be verified by a paratest run.  @benharsh has been kind enough to evaluate the performance
impact of trimming the comp-opt

**Comment by benharsh** [comment]
After testing just now I have not observed a performance regression on single-node or 16-node-xc for CoMD.

**Comment by noakesmichael** [comment]
There appears to be consensus on dropping the current broken code.
Closing.
