### ISSUE TITLE
tailor generic initialization error messages to note phase 2

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#6632]
### Summary of Problem

In writing a naive initializer that tried to initialize a generic field (a `type` field), I failed to use `super.init()` to ensure that the field was initialized in phase 1.  The error message that is generated:

```
can't omit initialization of field "t", no type or default value provided
```

suggests that I omitted the initialization of `t` when it appears to me (as a pretending-to-be-naive) user that I have done so.  What the error message really should be doing is either complaining about `t` being initialized in phase 2 or about it not being initialized in phase 1.

[Even better, though, perhaps we should permit compile-time fields to be initialized in either phase for convenience since they will be interpreted at compile-time rather than execution-time (and therefore are something of a phase 0 in either case).  It seems like this could "just fall out" without much effort, though I could be wrong).]

### Steps to Reproduce

**Associated Future Test(s):**
[`test/classes/initializers/generics/genericInitError.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/generics/genericInitError.chpl
          ) #6613

### Configuration Information

- Output of `chpl --version`: `chpl Version 1.16.0 pre-release (9957bd8)`

**Comment by lydia-duncan** [comment]
An alternate, alternate path would be to have Phase 1 be the default, then we wouldn't complain about the type field initialization being missing in Phase 1!

(I think all options are worth thinking about, but didn't want us to forget about this one :) )

**Comment by bradcray** [comment]
That's true.

**Comment by benharsh** [comment]
Can this issue be closed now? I may be missing something, but the existing [.bad](https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/generics/genericInitError.bad) file seems to have the kind of output requested in the issue.

**Comment by bradcray** [comment]
Yeah, I think that the issue can be closed and the future retired.  I think this issue/future became moot when we switched to phase 1 by default.
