### ISSUE TITLE
Disambiguation of Partially Generic Arguments

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#6641]
Consider the following program:

``` chapel
proc test(arg:[]) where true {
  writeln("generic [] version");
}
proc test(arg:[] int) where true {
  writeln("[] int version");
}

var A:[1..100] int;

test(A);
```

What should this program do? The argument expression `arg:[] int` declares a generic argument that has an integer element type. It could still have any domain type. That might be called a partially generic argument.

The language specification describes how the best function is chosen from a series of overloads in 13.13.3 Determining More Specific Functions. However, it considers only totally generic and totally concrete arguments. It does not consider partially generic arguments.

Nonetheless the compiler supports partially generic arguments. However, it currently does so by adding a `where` clause to the function. Which seems to work on the surface, but it changes the way the function will be selected in an un-principled way (and in particular this is the reason the code listing at the top of this issue results in ambiguity even though the `arg:[] int` argument is *more concrete*).

I think that we should:
 a) Extend the compiler to directly prefer partially generic arguments over fully generic arguments
 b) Update the language specification to consider partially generic arguments

In particular, I think that the program above should result in output:
```
[] int version
```

**Comment by bradcray** [comment]
This sounds reasonable and natural to me.

**Comment by ct-clmsn** [comment]
@bradcray would this be related to the generics code that I've been putting around?

**Comment by ben-albrecht** [comment]
>a) Extend the compiler to directly prefer partially generic arguments over fully generic arguments
>b) Update the language specification to consider partially generic arguments

I am in favor of both of these proposals.

As you mentioned, `proc test(arg:[] int) { }` is implemented under the hood using `where` clauses. Does the term "partially generic argument" also extend to arguments whose types are specified by `where` clauses in the first place?

For example,

```chpl
// Partially generic?
proc test(x) where isNumeric(x) {
  return x+1;
}

// Generic
proc test(x) {
  return x;
}

// Resolves to former test(x)
test(41);
// Resolves to latter test(x)
test('foo');
```

Do we consider the former `proc test(x) where isNumeric(x)` partially generic?

I think the spec should provide a clear definition for  "partially generic arguments", however we define that.

**Comment by mppf** [comment]
@ben-albrecht - no, in your `isNumeric(x)` example, `x` is not *partially generic*.

PR #6659 updates the spec but uses the term *partially concrete*.  @lydia-duncan and I think it's is clear enough for now but of course you are welcome to give it a read & suggest improvements if you wish to.

**Comment by bradcray** [comment]
@ct-clmsn: I don't think this would have an effect on the codes you were trying to write -- at least, not that I'm anticipating.

**Comment by ben-albrecht** [comment]
@mppf  - hadn't updated my spec! That makes more sense - thanks.
