### ISSUE TITLE
Proposed TOML interface

### ISSUE THREAD

**Issue by Spartee** [chapel-lang/chapel#6654]
Here's the proposed interface for Chapel's TOML library

Node is a placeholder name for the data structure that holds the parsed toml.
Could be named something else more related to toml? e.g. -> tomlTable

Will list a few example use-cases once interface is finalized.

```chpl 
/* Chapel's Library for `Tom's Obvious, Minimal Language (TOML) <https://github.com/toml-lang/toml>`_.

This module provides support for parsing and writing toml files.
*/

/*
Receives a channel to a TOML file as a parameter and outputs an associative
array Node.
*/
proc parseToml(input: channel) : Node {}

/*
Receives a string of TOML format as a parameter and outputs an associative
array Node. 
*/
proc parseToml(input: string) : Node {}


/*
Receives an output channel and an instance of Node representing an associative
array of the parsed channel. The format for writing into the file is toml.
*/
proc writeToml(arr: Node, output: channel) {}`

**Comment by mppf** [comment]
These look pretty good to me but I think the `Node` part is still a big mystery.

If `Node` is going to be TOML AST, maybe there is a better way to structure this.

What if instead of `Node` we had a record (or a class) called `Toml` and `parse` was a `type method` on it (ie akin to a C++ static method)? Then `write` would simply be a method. And then, at that rate, why wouldn't `write` just be an implementation of the standard `writeThis` method, so that `writeln(myTomlNode)` will do the right thing?

**Comment by Spartee** [comment]
@mppf those changes have been incorporated. ```writeln(Node)``` was the right way to go. While its not reflected in the current code as I am waiting on channel.lines the interface will look like this 

```chpl
/*
Receives a channel to a TOML file as a parameter and outputs an associative
array Node.
*/
proc parseToml(input: channel) : Node {}

/*
Receives a string of TOML format as a parameter and outputs an associative
array Node. 
*/
proc parseToml(input: string) : Node {}
```

**Comment by ben-albrecht** [comment]
I think the user-facing methods and fields on the `Node` class need to be exposed in this interface documentation, e.g. `writeThis(f)`, `toString()`, `these()`, `this(i)`, ...

Here's my take on names:

- `module Toml -> module TOML`
  - following the convention that modules named after acronyms are all caps, e.g. `BLAS`, `LAPACK`, `FFTW`, `HDFS`, `GMP`, ...
- `class Node -> class Toml`
  - This is the primary type users will interact with in the library.`Toml` is simple, easy to remember, and describes the data it holds (TOML file contents).
- leave `parseToml` as is

**Comment by mppf** [comment]
Did you consider and reject the *type method* approach? I get the sense that comment of mine was ignored / not understood.

**Comment by ben-albrecht** [comment]
@mppf - to clarify, you're proposing the type method:

```chpl
proc type Toml.parse(input: channel) : Toml { }
```

as a cleaner interface than the function:

```chpl
proc parseToml(input: channel) : Toml { }
```

I don't have a strong preference towards one way or another.

**Comment by Spartee** [comment]
The following names have been changed as per BenA suggestions:
- module Toml -> module TOML
- class Node -> class Toml

The Interface including the user-facing methods of the Toml Class as of now:
```chpl
/*
Receives a channel to a TOML file as a parameter and outputs an associative
array.
*/
proc parseToml(input: channel) : Toml { }

/*
Receives a string of TOML format as a parameter and outputs an associative
array. 
*/
proc parseToml(input: string) : Toml { }

/*
For the user to write values of a Toml class instance.
  e.g. Toml[key].toString()
*/
proc Toml.toString() : string { }


/*
Takes a table path and returns the index of the leaf table of that path.
This is an example of indexing into a Toml object and adding a Toml instance.
 e.g.  Toml.getIdx("A.B")["C"] = new Toml(tbl);
*/
proc Toml.getIdx(tablepath: string) ref : Toml { }
```

**Comment by Spartee** [comment]
@ben-albrecht Updated UI of Toml library

```chpl
/*
Receives a channel to a TOML file as a parameter and outputs an associative
array.
*/
proc parseToml(input: channel) : Toml { }

/*
Receives a TOML file as a parameter and outputs an associative
array.
*/
proc parseToml(input: file) : Toml { }

/*
Receives a string of TOML format as a parameter and outputs an associative
array. 
*/
proc parseToml(input: string) : Toml { }


/*
Indexing now works as expected 
 e.g.  Toml["A.B"]["C"] = new Toml(tbl);
*/

/*
For the user to write values of a Toml class instance.
  e.g. Toml[key].toString()
*/
proc Toml.toString() : string { }

```
