### ISSUE TITLE
There is "nil type"

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#6665]
Currently the "nil type" is accessible by the user in Chapel programs. The "nil type" is the type of the `nil` value that's not any other class type.

For example, users can make variables and formals of "nil type":

```chpl
var myNil = nil;
writeln(myNil.type:string);

proc passNil(arg) { writeln("got nil"); }
passNil(nil);
```

and can pass "nil type" around just like any other type:

```chpl
type nilt1 = nil.type;
type nilt2 = typeOf(nil);
proc typeOf(arg) type return arg.type;

proc acceptNils(arg1:nilt1, arg2:nilt2) { writeln("got nils"); }
acceptNils(nil, nil);
```

**Comment by vasslitvinov** [comment]
@bradcray could you rationalize what's wrong with "nil type" and suggest compiler output for the above examples?

**Comment by bradcray** [comment]
No -- I haven't suggested anything is wrong with any of the above.

**Comment by vasslitvinov** [comment]
Oops my misunderstanding. Nevermind, I am closing this.
