### ISSUE TITLE
Internal Error: Trying to obtain autoCopy for [...], which defines none

### ISSUE THREAD

**Issue by nspark** [chapel-lang/chapel#6687]
### Summary of Problem
In exploring the idea of an `Option` wrapper type in Chapel, I encountered the following error:
> test1.chpl:1: internal error: Trying to obtain autoCopy for the type 'Option(int(64))', which defines none [functionResolution.cpp:458]

By chance, I tried implementing the record using old-style constructors and the error went away.

### Steps to Reproduce

**Source Code:**

test1.chpl:
```chapel
record Option {
  type eltType;
  var state: bool;
  var value: eltType;

  proc init(value: ?eltType) {
    this.eltType = eltType;
    this.state   = true;
    this.value   = value;
    super.init();
  }
}

proc Some(value: ?eltType) {
  var opt = new Option(value);
  return opt;
}

assert(Some(42) == Some(42));
```

test2.chpl:
```chapel
record Option {
  type eltType;
  var state: bool;
  var value: eltType;

  proc Option(value: ?T, type eltType = T) {
    this.state = true;
    this.value = value;
  }
}

proc Some(value: ?eltType) {
  var opt = new Option(value);
  return opt;
}

assert(Some(42) == Some(42));
```

**Compile command:**
```bash
$ export CHPL_DEVELOPER=1

$ chpl test1.chpl # produces internal error
test1.chpl:1: internal error: Trying to obtain autoCopy for the type 'Option(int(64))', which defines none [functionResolution.cpp:458]

$ chpl test2.chpl # does not produce internal error
```

**Execution command:** `./a.out`

**Associated Future Test(s):** Not that I am aware of.

### Configuration Information

- Output of `chpl --version`:
```
chpl Version 1.16.0 pre-release (74220c9fb6)
Copyright (c) 2004-2017, Cray Inc.  (See LICENSE file for more details)
```

**Comment by lydia-duncan** [comment]
Thanks for reporting!  Unfortunately, this is a known issue.  We need to perform a more principled effort to remove bits of the pass insertAutoCopyCalls.  I think I have a future for it, let me look around a bit more.

**Comment by lydia-duncan** [comment]
With @noakesmichael's work on copy initialization, this test now fails in the same manner as #6688.  I'm going to close this issue and note in the other one that both:
```chapel
proc Some(value: ?eltType) {
  var opt = new Option(value);
  return opt;
}
```
and 
```chapel
proc Somevalue: ?eltType) {
  return new Option(value);
}
```
run into that issue

**Comment by lydia-duncan** [comment]
(I was accidentally running the wrong version of this code, so mistakenly thought it was failing in the other way.  It actually works correctly now)
