### ISSUE TITLE
Unexpected compiler error: Illegal use of function that does not return a value

### ISSUE THREAD

**Issue by nspark** [chapel-lang/chapel#6688]
### Summary of Problem
In exploring the idea of an `Option` wrapper type in Chapel, I unexpectedly encountered the following compiler error:
> test1.chpl:15: error: illegal use of function that does not return a value: 'init'

As with #6687, I tried implementing the record using old-style constructors and the error went away.

### Steps to Reproduce

**Source Code:**

test1.chpl:
```chapel
record Option {
  type eltType;
  var state: bool;
  var value: eltType;

  proc init(value: ?eltType) {
    this.eltType = eltType;
    this.state   = true;
    this.value   = value;
    super.init();
  }
}

proc Some(value: ?eltType) {
  return new Option(value);
}

assert(Some(42) == Some(42));
```

test2.chpl:
```chapel
record Option {
  type eltType;
  var state: bool;
  var value: eltType;

  proc Option(value: ?T, type eltType = T) {
    this.state = true;
    this.value = value;
  }
}

proc Some(value: ?eltType) {
  return new Option(value);
}

assert(Some(42) == Some(42));
```

**Compile command:**
```bash
$ export CHPL_DEVELOPER=1

$ chpl test1.chpl # produces compiler error
test1.chpl:14: In function 'Some':
test1.chpl:15: error: illegal use of function that does not return a value: 'init'

$ chpl test2.chpl # does not produce compiler error
```

**Execution command:** `./a.out`

**Associated Future Test(s):** Not that I am aware of.

### Configuration Information

- Output of `chpl --version`:
```
chpl Version 1.16.0 pre-release (74220c9fb6)
Copyright (c) 2004-2017, Cray Inc.  (See LICENSE file for more details)
```

**Comment by lydia-duncan** [comment]
Thanks for reporting!  I don't think we knew about this one before, I'll be sure to take a look

**Comment by lydia-duncan** [comment]
I've fixed a version of this for concrete records, but haven't fixed the generic records issue yet.  Stay tuned!

**Comment by lydia-duncan** [comment]
```chapel
proc Some(value: ?eltType) {
  var opt = new Option(value);
  return opt;
}
```
also encounters this error, now (instead of failing in a different way)
