### ISSUE TITLE
Extend parallel array initialization support to all types

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#6689]
Currently we only support array initialization for POD types. 

Ideally we want to be able to do parallel initialization for all types, but we're currently blocked by an issue with arrays of arrays and thus arrays of aggregate types where at least one field is an array. The issue is basically that an array's domain stores a linked list of all its arrays and removal becomes expensive when addition and removal occur in different orders.

Long term we probably want to store the domain's arrays as an associative domain or some data structure with < log(n) find/add/remove times. Currently we can't do that because the domain's arrays are part of the base domain, so we have a circular reference.

 - [x] enable parallel init for POD types (#6675)
 - [ ] enable parallel init for some "well-known" types (atomics, sync, single, string, etc)
 - [ ] enable parallel init for all types including arrays-of-arrays

**Comment by mppf** [comment]
PR #15739 factors a hashtable out of DefaultAssociative that could be used.
