### ISSUE TITLE
Improve tmbundle support

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#6690]
This issue is meant to track Chapel syntax that isn't highlighted properly by tmbundle which, as I understand it, is what GitHub uses for syntax coloring.

* It seems that `ref` is not highlighted as being a keyword, for example in:

```chapel
var y = 10;
ref x = y;
```

**Comment by lydia-duncan** [comment]
I think GitHub doesn't use tmbundle anymore, I never saw the "in", "throws", etc. changes turn up even though I updated the repo and it looked like they were referencing the chapel-lang one instead of the bholt one.

**Comment by ronawho** [comment]
Related to https://github.com/chapel-lang/chapel/issues/5908. And I agree with lydia, I think github moved to something else. Linguist or something like that?

**Comment by ben-albrecht** [comment]
@ronawho && @lydia-duncan -- linguist still uses Chapel's [tmbundle](https://github.com/chapel-lang/chapel-tmbundle), as shown [here](https://github.com/github/linguist/blob/8d178bfaed6003928d5bb0d54ce049cb395ea86a/vendor/README.md)

**Comment by cassella** [comment]
Looking at linguist's collection of tmbundle grammars,

https://github.com/github/linguist/tree/master/vendor/grammars

it looks like each grammar is imported as a submodule, including
chapel-tmbundle.  Submodules link by a specific commit -- I think
it'll take a PR against linguist to change which chapel-tmbundle
commit linguist should use.

**Comment by lydia-duncan** [comment]
From the README on Linguist: 

> If you experience an issue with the syntax-highlighting on GitHub, please report the issue to the upstream grammar repository, not here. Grammars are updated every time we build the Linguist gem and so upstream bug fixes are automatically incorporated as they are fixed.

That seems to imply to me that they should get fixes automatically.

**Comment by lydia-duncan** [comment]
That's not to say that @cassella's interpretation is incorrect, just that maybe they should know about it and update their documentation if it is.

**Comment by bradcray** [comment]
> That seems to imply to me that they should get fixes automatically.

Is there any way to determine when Linguist was last rebuilt and which version GitHub is using -- essentially see whether it's been updated since our last edits to tmbundle?

**Comment by ben-albrecht** [comment]
> Is there any way to determine when Linguist was last rebuilt and which version GitHub is using -- essentially see whether it's been updated since our last edits to tmbundle?

They update every release, and their last release was on May 25th:

https://github.com/github/linguist/releases

Here's the PR that updates submodules: 

https://github.com/github/linguist/pull/3642/files

**Comment by lydia-duncan** [comment]
That would explain it, my changes were in June.

**Comment by cassella** [comment]
Progress!  linguist 5.1.0 includes the latest chapel-tmbundle,

https://github.com/github/linguist/pull/3725/files

That picks up the exception handling keywords, but chapel-tmbundle
doesn't include "ref" yet.

```chapel
proc tically(in solvent, out rageous, ref lective, var nish, inout terspace) throws {
     try { ptophan(); }
     catch n: ReleaseError {
     	 throw n;
     }
}
```

**Comment by victor-ludorum** [comment]
@bradcray  Hello , I have worked on **"Incorrect Syntax Highlighting For Escaped Character '\"' #6899 "** . So, I think I can  work on this . Please suggest me only **"ref"** keyword is not there or any other keywords are too not present in the chapel tmbundle which should be added .

**Comment by bradcray** [comment]
Hi @victor-ludorum : I'm not aware of keywords other than 'ref' that are missing, though I wouldn't be surprised if there are some.  I'm not sure what people would consider the most definitive list of Chapel keywords these days.  Anybody else on this thread have a suggestion?

**Comment by victor-ludorum** [comment]
@bradcray  I have figured out some missing keyword from the Chapel tmbundle from the [link](https://github.com/chapel-lang/chapel/blob/master/highlight/highlight/langDefs/chpl.lang) 
These are **inout, out , ref, subdomain , sync and opaque** .  Suggest if anymore keyword are missing

**Comment by bradcray** [comment]
I believe those should be highlighted, thanks Victor!

**Comment by victor-ludorum** [comment]
@bradcray  Okay sir I will submit a PR resolving this issue .
