### ISSUE TITLE
Undocumented support for multi-line string literals

### ISSUE THREAD

**Issue by noakesmichael** [chapel-lang/chapel#6697]
On Mar 3, 2017 @bradcray opened issue #5501 to consider supporting multi-line string
literals in Chapel.  One obvious approach was to adopt one of the schemes C uses for this;
a translation phase in which adjacent string-literals are automatically concatenated.

Please refer to that issue for a discussion on this.  In the end Brad closed the issue.

I recently tripped over the fact that Chapel does implement a solution for multi-line
string literals. This solution is currently undocumented.  One can break a string-literal
with a backslash followed by a newline.  Any leading whitespace on the next line is ignored.

Two examples of this can be seen in the method BaseSparseDomImpl.bulkAdd_prependInds()
in ChapelDistribution.chpl.

A quick-dirty evaluation of Chapel modules/tests identified two instances of this feature
in module code, one more instance in each of two app-level tests, a few instances each in
two internal tests that are hard to classify,  and then a few more uses in tests that are designed
to lock-in the current mechanism.

Chapel's approach is a variation on a similar mechanism offered in ANSI-C. 
However in ANSI-C any leading whitespace in the next line becomes part of the string literal.
This implementation choice may explain why this mechanism is not widely used.  I had forgotten
it existed and even @dmk42 had to pause to recall the details.  The expected behavior
is defined in a precise way by the ANSI-C standard but different C compilers may generate
warnings around near-misses of this feature.

The question is whether we should remove this mechanism or make it be a defined 
feature in Chapel and document it in the specification.

**Comment by bradcray** [comment]
Based on the discussion in #5501 (disinclination to support C-style string literal splitting amongst most of the team), I'd be inclined to remove this support unless any strong champions step forward.  I was not aware of C having such a feature (and apparently forgot that Chapel did) and associate continuing lines with backslashes more with the C pre-processor or scripting languages than with C or Chapel.

If this did have a strong champion and we kept it, it would make me think that (a) we should reconsider the decision in #5501 (support the more commonly known means of splitting C lines and (b) consider making this feature more conforming with ANSI C w.r.t. leading whitespace.

@noakesmichael : If you have it at-hand, could you add the list of current occurrences of the feature to this issue?  Thanks.

**Comment by noakesmichael** [comment]
I implemented a quick-dirty, and possibly incomplete, list of uses of this feature to help to scope
this issue.  While it is possible that this list is incomplete I believe it is sufficiently accurate for
evaluation purposes.

2 cases:  modules/internal/ChapelDistribution.chpl
          proc bulkAdd_prepareInds(inds, dataSorted, isUnique);


// Two tests that use it in a trivial way
line  68: test/release/examples/primers/distributions.chpl
line  85: test/studies/prk/Synch_p2p/p2p-serial-fast.chpl


// Lock	in the behavior
line   1: test/parsing/vass/line-numbers-after-newline-in-string.chpl
line   2: test/parsing/vass/newline-in-string-compiletime-1.chpl
multiple: test/parsing/vass/newline-in-string-good-1.chpl


// Unclear to me what the status is here
line   9: test/chplenv/chplconfig/warnings/notfound.chpl
line  11: test/chplenv/chplconfig/warnings/warnings.chpl

**Comment by noakesmichael** [comment]
For the record, I am also in favor of removing this support and I am willing to do the work.

**Comment by dmk42** [comment]
The Chapel situation is different from C, for two reasons.
1.  In C, backslash-newline removal happens in translation phase 2, before tokens are recognized.  That is why C cannot ignore leading white space on the continuation line of a string literal.
2.  C does not have an explicit string concatenation operator, only implicit concatenation by placing two string literals next to each other.

Backslash-newline continued string literals look ugly in C because they break the program's indentation.  As a result, nearly everybody has moved to using implicit concatenation in C.  The result looks quite good in code.

In Chapel, as long as explicit string concatenation on two param strings still yields a param string, the exact same thing can be achieved without special syntax, and looks just as good in code.  It also avoids the problem with missing commas that C has.  Consequently, I don't see a need for a backslash-newline continued string literal in Chapel, even if white space is ignored at the beginning of a continuation line.  Chapel already has a better way to do it.

**Comment by bradcray** [comment]
Of these examples that currently use it, most of them don't change my opinion, though the last two gave me slight pause.

Specifically, while I don't know why @ben-albrecht chose to write these tests this way, it demonstrates that one could effectively copy and paste lines of text into a source file and have it become a string reasonably easily.  That said, it still requires some edits (adding backslashes to each such line), so it's not as though it provides an edit-free way of pasting files into source and having them become strings -- so maybe this is not that much better/different than what one would have to do without the feature (i.e., wrap each such line in quotes and add a `+`).

It looks like the most recent uses of these feature are from @ben-albrecht and @benharsh while @vasslitvinov looks like an early proponent / implementer, so ideally I'd like to hear from them before giving up on the feature.

**Comment by benharsh** [comment]
I had also forgotten that Chapel supported this feature, and do not have a strong opinion either way.

**Comment by ben-albrecht** [comment]
> it demonstrates that one could effectively copy and paste lines of text into a source file and have it become a string reasonably easily. That said, it still requires some edits (adding backslashes to each such line), so it's not as though it provides an edit-free way of pasting files into source and having them become strings

I'm sure that's why I wrote the tests that way - copy & paste == less work to get the newlines correct for my `.good` file.

>so maybe this is not that much better/different than what one would have to do without the feature (i.e., wrap each such line in quotes and add a +).

Wouldn't you need to add `\n`s in the `+` concatenation case?

I think a multi-line string literal syntax would be useful, but I don't think the syntax in my test is the right way to support it.

**Comment by dmk42** [comment]
Oh, that's a difference that I missed.  In C, backslash-newline means "delete both the backslash and the newline, and paste the result together," but in Chapel string literals, backslash-newline means "delete the backslash but put a newline in the string."  I would not have guessed that Chapel worked that way, though it makes sense given when it's parsed in Chapel.

**Comment by vasslitvinov** [comment]
I do not have a preference either way.

I personally would prefer no backslashes at the end of each line for my multi-line string literals. (Although this syntax would make user error more likely.)

Do we have a special syntax for "literal" string literals, including no backslash requirement, from KyleB era? I tried ''' and c' and r' and none worked.

**Comment by noakesmichael** [comment]
Curiouser and curiouser.

I had completely missed that Chapel is replacing \<newline> with a newline.  I assumed it was a
"better" version of the C feature.  Note that Chapel includes C-style escapes like '\n'.

I wrote a quick test with two strings; one with the current syntax and one with a longer string,
no newlines, and conventional '\n' syntax and was able to match the output.


This intensifies my preference to eliminate this.

**Comment by dmk42** [comment]
I note that an argument for keeping the current backslash-newline behavior is that it makes it easy to cut and paste the contents of a file.  However, if the file has any lines that begin with white space, the current backslash-newline syntax will not preserve it in the string.

**Comment by buddha314** [comment]
Implementation aside, I often use multi-line strings for SQL queries.  Python's implementation is very convenient.

```
q = """
SELECT thing
FROM table t
WHERE lamp = 'is dusted'
   AND endtable is not 'is not dusted'
GROUP BY {finger}
conn.execute(finger='thumb')
```

This allows me to cut/paste SQL between the psql shell and the code, so I can test it first.  Of course, that inspires a new ticket...

**Comment by buddha314** [comment]
What is the status of this ticket?  Are you going to include multi-line strings?

**Comment by bradcray** [comment]
I'm finding the rationale for supporting some sort of edit-free multi-line literal increasingly compelling particularly given Python's precedent for it.

**Comment by buddha314** [comment]
Just a little bump, now that I get to use the [CDO](https://github.com/marcoscleison/cdo/issues) library, I'm using a lot more SQL.  This mean very long strings.

**Comment by bradcray** [comment]
Just to check my assumption, it's actually the feature request in #7867 that you're hoping to bump, right?  (this issue is a bit more exploratory and, if we pursued and achieved #7867, might put this one to rest.  Thanks.

**Comment by buddha314** [comment]
Ah, yes.  I'm interested in the feature.  I don't care if you close this one.

**Comment by ben-albrecht** [comment]
Migrated to #7867
