### ISSUE TITLE
GitHub label: "gating issue"

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#6703]
I've been thinking recently that we should add a "gating issue" label to our list such that issues filed by users or developers that are holding up crucial work (i.e., don't have a workaround, or at least a satisfactory one) can be sorted separately from other issues.  Ideally, each gating issue would quickly get an assignee and the number of open gating issues at any time would be close to zero.  If a satisfactory workaround was developed for the issue, the "gating issue" label could be removed.

To me, this has value independently of "user issue" because (a) it could be applied to developer issues and (b) it would distinguish between "this came from a user yet is not holding them up" vs. "this needs to be addressed in short order."

If we went with this proposal, we might want to add a "is this a gating issue" field to the standard bug report template.

**Comment by ben-albrecht** [comment]
I support this proposal.

**Comment by mppf** [comment]
Works for me. I wonder if we should use this as developers, when creating an issue reflecting a design decision that must be completed in order to make further progress?

**Comment by ben-albrecht** [comment]
> I wonder if we should use this as developers, when creating an issue reflecting a design decision that must be completed in order to make further progress?

I think this would be useful in a general context for users and developers. If it ends up getting used too frequently, we may reconsider this decision in the future.

Anyways, I've gathered that the rest of the team supports this label and am going to create it. I'm going with `user issue`-yellow for now, but feel free to update the color to something else if you'd prefer, @bradcray.

**Comment by bradcray** [comment]
I'd be tempted to reverse the colors of "post-release" and "gating issue" so that gating issue gets a somewhat more urgent color and post-release a somewhat less urgent one.  Any thoughts on that?
