### ISSUE TITLE
Adding tio.run Chapel instance to the docs

### ISSUE THREAD

**Issue by saru95** [chapel-lang/chapel#6718]
https://tio.run/# is a website that became quite popular recently for supporting online interpreters/compilers for a bunch of languages. I got Chapel added to it (https://tio.run/#chapel). I think this could prove to be quite useful when debugging small fragments of code. I was hoping if the link to this could be added to the docs at chapel.cray.com.

**Comment by bradcray** [comment]
We were pointed to this on Twitter over the weekend, and it was great to see it up and running!  From what I could tell, it looks like the executions are completely sequential (e.g., the iterations of a large forall loop always came out in the serial order).  Is that accurate?  I'd like to link to it from chapel.cray.com too (and would own that task), just have to figure out where to feature it.

**Comment by ben-albrecht** [comment]
@saru95 - thanks for submitting Chapel to https://tio.run/# !

@bradcray - Do we already point to  http://cyber-dojo.org/  from chapel.cray.com somewhere?

Once we have a home-grown tool similar to https://play.golang.org/ or https://play.rust-lang.org/, it will seem natural to direct all users to that. Until then, I'm fine letting community-managed projects like [awesome-chapel](https://github.com/marcoscleison/awesome-chapel) maintain a curated list to third-party tools such as [tio](https://tio.run/#) and [cyber-dojo](http://cyber-dojo.org/).

**Comment by mppf** [comment]
I'm excited that tio.run is available with Chapel, thanks!

I just noticed that it is in fact possible to generate a link with some particular code for tio.run to show, by clicking on the chain-looking icon at the top. For example, I made this https://tio.run/##S85ILEjN@f@/LLFIocJKITOvxJqrvCizJDUnT0OpQiGzWEFJR6FC0/r/fwA as a demonstration that we could link a code sample (this one is from http://chapel.cray.com/docs/latest/users-guide/base/vars.html ) to tio.run. Do you know if there is a way to generate such URLs automatically?

My next question is whether or not it would be possible to have a GASNet configuration in tio.run. Do you know?

**Comment by mppf** [comment]
I spent (too long) poking at try-it-online and figuring out how to generate a URL from a Chapel source code file. Here is what I produced:
``` javascript
// npm install btoa
// npm install pako
//
// run with
//   nodejs writeit.js file.chpl
var fs = require('fs');
var pako = require('pako');
var btoa = require('btoa');

var input=process.argv[2]

var header="chapel\xff\xff"
var footer="\xff\xff"

var code = fs.readFileSync(input)

var precompress = header + code + footer

// These functions copied from Try It Online's usr/share/tio.run/frontend.js
function iterate(iterable, monad) {
        if (!iterable)
                return;
        for (var i = 0; i < iterable.length; i++)
                monad(iterable[i]);
}

function deflate(byteString) {
  return pako.deflateRaw(byteStringToByteArray(byteString), {"level": 9});
}

function byteStringToByteArray(byteString) {
  var byteArray = new Uint8Array(byteString.length);
  for(var index = 0; index < byteString.length; index++)
    byteArray[index] = byteString.charCodeAt(index);
  byteArray.head = 0;
  return byteArray;
}

function byteArrayToByteString(byteArray) {
  var retval = "";
  iterate(byteArray, function(byte) { retval += String.fromCharCode(byte); });
  return retval;
}

function byteStringToBase64(byteString) {
    return btoa(byteString).replace(/\+/g, "@").replace(/=+/, "");
}


var result = "##" + byteStringToBase64(byteArrayToByteString(deflate(precompress)));
process.stdout.write("https://tio.run/" + result + "\n");
```

We could use this script to generate URLs that the documentation could refer to, so people could use Try It Online with Chapel examples from the user's manual (say).

I'm having trouble understanding why we need to wait for a homegrown tool to link documentation to try-it-online or any other similar website.

**Comment by bradcray** [comment]
@saru95 : As a starting point, I just tweeted/facebooked a post pointing people to the TIO support.  Still thinking about where to add it to chapel.cray.com.  I'm still curious about whether the implementation is known to be serial / single-threaded and/or whether there's anything we might be able to do to change that.

**Comment by saru95** [comment]
@bradcray It seems to be serial for now. I'll try talking to Dennis (he's the one who runs tio.run) and figure something out. If you'd like to engage with him, you can find him here https://chat.stackexchange.com/rooms/44255/talk-tryitonline-net

**Comment by bradcray** [comment]
@saru95: As you've seen, I joined your chat.

Answering some of the questions we've been asking above:

* the servers used to run TIO codes are single-core, which is why we're getting serial execution by default.  My current thought about how to address this would be to set an environment variable in the script that compiles + runs Chapel programs to override the default of "1 task per core".

* the servers are not able to talk to each other, so a multi-locale execution would not be possible at this time (though I suppose we might be able to emulate it by oversubscribing if we thought that was of sufficient value).

**Comment by mppf** [comment]
@bradcray - I was thinking of oversubscription, simply as a way people could try out multi-locale examples. I have real trouble believing somebody using an online Chapel program execution environment like this actually cares about performance. It's a learning tool - but for learning Chapel, I think it helps to be able to have > 1 locale.

**Comment by bradcray** [comment]
OK, thanks for clarifying.  I'm going to try and focus on the multi-threaded version first, and then will look at the multi-node run.  Downsides to multi-locale via oversubscription would include longer compile times and even more oversubscription of the 1 core.  Would those downsides warrant adding a 'Chapel-multinode (simulated)' environment as a second option, or is that just confusing?

**Comment by mppf** [comment]
The web interface lets you put in compile options. Can't we select CHPL_COMM with a compiler option now? Not sure we'd need a different environment.

**Comment by bradcray** [comment]
That's a great point.  We would need to have them build it with GASNet configured, though.

**Comment by ben-albrecht** [comment]
> I'm having trouble understanding why we need to wait for a homegrown tool to link documentation to try-it-online or any other similar website.

For maintaining a list of external tools like try-it-online: I'm fine with doing so. I predict it will become cumbersome overtime, but we can react to that, and stop maintaining the list if/when it becomes too cumbersome.

For linking try-it-online code snippets from within documentation: Sounds like a good idea, as long the URL-generating script is modular enough to support switching to other websites down the road (e.g. when we have a homegrown play.chapel-lang.org)

**Comment by bradcray** [comment]
Update: We've now got multi-tasking parallelism within a single locale and are working on comm=none | gasnet configurations + oversubscription next.

@saru95 : I was originally thinking you'd contributed the Chapel-related stubs to tio, but given your mention above about discovering it's open source, I'm now thinking you may have just been the bug in Dennis's ear that caused him to give it a try himself, is that right?  In either case, thanks -- I think this is very exciting.

**Comment by bradcray** [comment]
I've now added to chapel.cray.com:

* a TIO icon at the bottom of the sidebar
* a mention of TIO in the "What's Hot?" list
* a new "Try it Now" link on the sidebar just below the "Download" link pointing to a new page listing both TIO and Cyber-dojo.org

Feedback welcome, including "Great!  Go ahead and close the issue!"

**Comment by bradcray** [comment]
> We would need to have them build it with GASNet configured, though.

This ended up getting tripped up by issue #6749

**Comment by saru95** [comment]
@bradcray Yep. :) I asked Dennis to include it in his platform. This was something that Chapel was missing. :)

**Comment by bradcray** [comment]
Closing this issue.  Sounds like people are satisfied.  Work remains to further improve our use of TIO (make it support multi-locale; figure out how to have our examples link to it), but those are separate issues.
