### ISSUE TITLE
Reductions should perform a final combination with the initial value of the variable...

### ISSUE THREAD

**Issue by npadmana** [chapel-lang/chapel#6738]
(Prompted by the following exchange on stackoverflow:
   https://stackoverflow.com/questions/45111312
)

Currently Chapel reductions ignore the external value of the variable being reduced  when setting the initial value of the reduction and they overwrite the variable on completion (instead of combining with this value). While the former behavior make sense, the latter can result in surprising results. For instance, the following code
```chapel
var x = 5;
for i in 1..3 {
  forall j in 1..10 with (+ reduce x) {
    x += 1;
  }
}
writeln(x);
```
returns 10, instead of 35. By contrast, a similar loop in OpenMP (thanks @bradcray) does return 35.
```c
#include <stdio.h>
#include <omp.h>

int main(int argc, char* argv[]) {
  int tot = 5;
  for (int i=0; i<3; i++) {
  #pragma omp parallel for reduction(+:tot)
    for (int j=0; j<10; j++) {
      tot += 1;
    }
  }
  printf("tot is: %d\n", tot);
}
```

This issue suggests that Chapel reductions should accumulate against the final value as a final step.

**Comment by bradcray** [comment]
@vasslitvinov: I meant to point you to the StackOverflow post the other day that led to this issue but forgot since it was the weekend.  I recall us discussing that each task should get its copy of the reduction variable initialized to the identity, but don't recall whether the choice to ignore the initial value (rather than combine it into the results or vice-versa) is something we explicitly decided not to do or not.  Do you?  If we wanted to make this change, can you give a sense of where it falls on the easy->hard 7-point scale?  Thanks.

**Comment by vasslitvinov** [comment]
Yes, the current choice was explicit. @e-kayrakli expressed preference for the opposite, too. Implementation would be at 3 out of 7, and should probably go together with changing our reduction interface.

There is a design issue with incorporating the initial value. Let's say we are doing MyOp-reduction into the outer variable x:

```chpl
forall... with (MyOp reduce x) do ...
```

Think about our reduction interface: would we "accumulate" the initial x onto the result? "combine" onto it? If the input/state/output types are all different, neither operation will apply. (Recall the type of x is the output type for the reduction, according to our current design.)

It may be that the new reduction interface will include the operation "Create a reduction op object, incorporating this initial value of the outer variable."

**Comment by bradcray** [comment]
> "combine" onto it?

I was thinking combine, yes.  Good point about the case of output and state types being different.  Maybe this is the motivation for getting rid of the notion of a distinct output type as some have called for?  I'll chew on that some more.

> It may be that the new reduction interface will include the operation "Create a reduction op object, incorporating this initial value of the outer variable."

OK.  In any case, I think we should chew on this feature request more—it does seem like an obvious thing to do in hindsight.
