### ISSUE TITLE
Homebrew installer for PyChapel

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#6763]
Support installation of PyChapel via `pip` or homebrew: https://brew.sh/  

Then wait for my PyChapel requests to go nuclear.

**Comment by ben-albrecht** [comment]
PyChapel is currently available via `pip`: https://pypi.python.org/pypi/pyChapel/0.1.17

PyChapel-related issues can be posted to [chapel-lang/pychapel/issues](https://github.com/chapel-lang/pychapel/issues)

**Comment by lydia-duncan** [comment]
Though I should note that some of the changes on that repo are not in the latest release yet.

**Comment by buddha314** [comment]
in order to use `pych`, I think you need to do the installation from source.  Should I move this issue to pychapel? apologies.

**Comment by buddha314** [comment]
Let's close this one, I opened it more specifically here: https://github.com/chapel-lang/pychapel/issues/75
