### ISSUE TITLE
chpl2rst drops multi-line comments in code blocks / learnChapelInYMinutes.chpl

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#6766]
As of Chapel 1.15's documentation, the learnChapelInYMinutes.chpl primer online documentation isn't rendering properly due to its attempt to render multi-line comments not working with chpl2rst.  This was noted in the PR that originally added it (#4653), but didn't seem to get filed as an issue, so I'm doing that here.  It currently renders something like this:

> Comments are C-family style
> 
> ```
> // one line comment
> 
>  multi-line comment
>  ```

(i.e., the /* and */ tokens are missing on the multi-line comment).

**Comment by ben-albrecht** [comment]
I think this could be implemented pretty easily - we just need to come up with a syntax we'd like to use.

**Comment by ShreyasKhandekar** [comment]
This was fixed by #17820

**Comment by bradcray** [comment]
Thanks @ShreyasKhandekar!
