### ISSUE TITLE
Plain on statements and initializers

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#6774]
Within an on statement that is not within a parallel or loop context, should we allow:
- field initialization in Phase 1?
- super.init()/this.init() calls?

Relevant context:
- Parallel statements are not allowed to contain these operations already
- Neither are loops
So if those operations are in parallel or loop statements within an on statement, or an on statement is in a parallel or loop statement and contains these operations, then that is already an error

I'm going to disallow these cases for now, but I think this is worth discussing as it
may impact the implementation of:
- types with distributed array fields
- arrays, domains, and distributions

**Comment by lydia-duncan** [comment]
I don't think it makes sense for an on statement to wrap the field initialization when the type is a primitive, but more complicated types seem reasonable to me.  Thoughts?

**Comment by mppf** [comment]
The main case that I know of for caring about this is when creating a class instance, e.g.
``` chapel
proc MyType.init(targetLocale:locale) {
  on targetLocale {
    myField = new SomeClass();
  }
  super.init();
}
```

However that case is easy enough to work around:
``` chapel
proc MyType.init(targetLocale:locale) {
  var tmpMyField:SomeClass;
  on targetLocale {
    tmpMyField = new SomeClass();
  }
  myField = tmpMyField
  super.init();
}
```

(assuming I am not missing something that would disallow the workaround).

Separately, I don't favor allowing any complicated constructs around super.init()/this.init(); these are really a marker and should pretty much be at the top level of the init function in my view (with a possible exception for param conditionals).

**Comment by vasslitvinov** [comment]
super/this.init() should indeed not be inside complicated constructs.

Field initializations either, except here the "complicated" bar is lower. For a field initialization, I think the requirement is that the compiler must be able to reason whether it does or does not happen.

In particular, initalizing within an on statement should be fine.

**Comment by lydia-duncan** [comment]
So that's two :+1:  for plain on around field initialization and two :-1: for plain on around super.init()/this.init()?

**Comment by mppf** [comment]
@lydia-duncan - more or less on my part - I'm OK either way for on around field init especially for now.

**Comment by bradcray** [comment]
I'm just catching up on this issue and think I'm OK with the trending agreement.
