### ISSUE TITLE
Support Vundle for vim-chapel plugin

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#6788]
[Vundle](https://github.com/VundleVim/Vundle.vim), the popular vim plugin manager, only supports installing vim plugins from a git repository, e.g. [vim-fugitive](https://github.com/tpope/vim-fugitive).

To support this, we could host a repository containing the contents of `chapel/highlight/vim/` so that users could install Chapel vim support with the following in their `~/.vimrc`:

```vim
Plugin 'chapel-lang/vim-chapel'
```

One obvious downside of this is the maintenance issue, as we'd need to propagate updates from `chapel-lang/chapel` to `chapel-lang/vim-chapel` on a per-release granularity.

**Comment by ben-albrecht** [comment]
The lack of Vundle support was brought up in #6785

**Comment by psahabu** [comment]
@ben-albrecht should we knock this out?

**Comment by psahabu** [comment]
@dmk42 making sure you can see this issue, I'm planning to knock it out soon unless there are objections

**Comment by dmk42** [comment]
No objections here, thanks.

**Comment by psahabu** [comment]
The team has decided that this project would be best handled by a member of the community using a repository outside the `chapel-lang` namespace.

When such a repository is created and usable by Vundle, directions for installation should be included in the main repo.

- [ ] create a new repository for Vundle users to enable Chapel highlighting
- [ ] update `highlight/vim/README.rst` with Vundle instructions

**Comment by ben-albrecht** [comment]
We could actually support Vundle by adding `.git` information to `highlight/vim/` so that it is able to `git clone $CHPL_HOME/highlight/vim`.

We wouldn't want to check this `.git` directory into our repository a git submodule, so we'd keep it packed up, and instruct users to unpack it if they want to use Vundle.

I doubl check that this works [here](https://github.com/chapel-lang/chapel/compare/master...ben-albrecht:vundle-support?expand=1), but am not sure if it's a direction we want to take. I haven't heard any requests for Vundle support since @buddha314 asked (which inspired me to open this issue), and he has since found the light and moved on to `vim-plug` 👍

**Comment by psahabu** [comment]
If Vundle is getting supplanted by `vim-plug`, I would support closing this issue.

**Comment by ben-albrecht** [comment]
Thank you @rj-jesus! I am closing this issue, since your repository will enable Vundle support.

Anyone stumbling across this issue in the future can add the following code in their `.vimrc` (after [Vundle](https://github.com/VundleVim/Vundle.vim) setup) to get Chapel highlighting in Vundle:

```vim
Plugin 'rj-jesus/chapel.vim'
```
