### ISSUE TITLE
./configure + make install for gasnet tries to use launcher from build directory

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#6793]
If configuring and installing a GASNet-enabled Chapel build, as in issue #6749, the launcher tries to refer to binaries in the original build directory such that, if it has been cleaned up, the launch will fail (at least for the amudp launcher, I have not tried others).  E.g., when running a multi-locale program from a gasnet installation of Chapel, I get:

```
./a.out -nl 5 --verbose
$CHPL_HOME/third-party/amudprun/install/darwin-clang/nodbg/bin/amudprun  -np 5 ./a.out_real -nl 5 --verbose
```

where `$CHPL_HOME` refers to the original Chapel directory where I did the `make`, not the installation location.  If that directory has not been removed / clobbered, the installation works fine.  If it has been, the result is:

```
internal error: execvp() failed: No such file or directory
```

This suggests that `make install` is still not working correctly for GASNet.

**Comment by bradcray** [comment]
Tagging @mppf and @ben-albrecht since they were involved with the previous issue.  Like that issue, this one was surfaced by trying to enable GASNet support on TIO.

**Comment by bradcray** [comment]
I think [this line in amudprun's Makefile.share](https://github.com/chapel-lang/chapel/blob/master/runtime/src/launch/amudprun/Makefile.share#L25) is the problem child.  @mppf, based on the edits you did yesterday is the fix obvious?  (I didn't review yesterday's patch and wanted to pick your brain before the weekend if possible).

**Comment by bradcray** [comment]
I poked into this a bit more and think it's a different kind of bug to fix than yesterday's in that the paths in question are determined at build-time and baked into the runtime library binaries (where yesterday's were paths at compile-time)

**Comment by mppf** [comment]
See #6795 which should fix it.

**Comment by bradcray** [comment]
#6795 fixes amudprun, but we'll need the equivalent fix to other GASNet launchers (e.g., gasnetrun_ibv) for them to work in a make install step.  Leaving this issue open for now to remember it (I didn't have cycles to pursue this today).
