### ISSUE TITLE
Implement elapsed time feature

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#6798]
Extremely helpful feature to time processes.  Julia has [tic()](https://docs.julialang.org/en/release-0.4/stdlib/base/#Base.tic), toc() which produce the elapsed time.

**Comment by Spartee** [comment]
I believe what your looking for is timer.start(), timer.stop(), and timer.elapsed() in our [Time standard module](http://chapel.cray.com/docs/latest/modules/standard/Time.html)

**Comment by buddha314** [comment]
Thanks! I don't see an example in the docs.  Would you be able to provide one?  You're probably right, I'll close this once I try it out.

**Comment by buddha314** [comment]
In a tribute to Chapel, even a more like me can figure it out:

```
use Time;
var timer: Timer;

timer.start();
writeln("hey");
timer.stop();
writeln(timer.elapsed());
```

**Comment by daviditen** [comment]
Here's a link to the Timers primer: [http://chapel.cray.com/docs/latest/primers/timers.html](http://chapel.cray.com/docs/latest/primers/timers.html).

**Comment by buddha314** [comment]
Thanks!  I think it may be useful to include a complete example, including how to create the variable `timer`.  I'm fairly new to Chapel and I didn't know that `Timer` is a class type as in `var timer: Timer;`

**Comment by daviditen** [comment]
The primers you can reach from the [primers page](http://chapel.cray.com/docs/latest/primers/index.html) are actually all complete, runnable examples.  They are generated from the `.chpl` files in `$CHPL_HOME/test/release/examples/primers/`.

One small correction - Timer is actually a record, not a class, so you don't need to `new` or `delete` it - it's default initialized just by declaring it.
