### ISSUE TITLE
use LinearAlgebra fails on OS X

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#6799]
### Summary of Problem
On OS X with `openblas` installed via brew.  Pulled `main` branch of Chapel from github and did a clean installation.

### Steps to Reproduce

**Source Code:**

```chapel
use LinearAlgebra;
```

**Compile command:**
`chpl -o linalg linalg_101.chpl`

**Error**
```
In file included from /var/folders/g5/4zwyfk513hd94tjs1fm5mdq00000gn/T//chpl-buddha-9685.deleteme/_main.c:2:
/var/folders/g5/4zwyfk513hd94tjs1fm5mdq00000gn/T//chpl-buddha-9685.deleteme/chpl__header.h:5:10: fatal error: 'cblas.h' file not found
#include "cblas.h"
         ^
1 error generated.
make: *** [/var/folders/g5/4zwyfk513hd94tjs1fm5mdq00000gn/T//chpl-buddha-9685.deleteme/linalg.tmp] Error 1
error: compiling generated source
```

**Comment by buddha314** [comment]
My fault again, apparently.  I'll need to look into the Chapel build system.

```
chpl -I/usr/local/Cellar/openblas/0.2.19/include \
  -L/usr/local/Cellar/openblas/0.2.19/lib -o d6matrix linalg_101.chpl
```

**Comment by ben-albrecht** [comment]
Hey @buddha314 - glad you figured this out in the documentation. I hope that we can include a BLAS/LAPACK distribution in the Chapel installation some day, as noted in #5753.

**Comment by buddha314** [comment]
I have to research `make` or other build systems with Chapel.  Also, will the sparse matrix stuff happen in the LinearAlgebra package or be an pass-through to BLAS/LAPACK?

**Comment by ben-albrecht** [comment]
`make` is what most Chapel developers use today. The Linear Algebra test directory includes an example Makefile for MKL. It used to be for OpenBLAS, so you could check the git history to get the version you need.
