### ISSUE TITLE
Type method with a param-typed return-type

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#6837]
### Summary of Problem

A class with a `type method` that returns a type that depends on a `type` or `param` argument of the method, results in an error (shown below).

### Steps to Reproduce

**Source Code:**

```chapel
class Sandwich {
  type eltType; // Same thing occurs if this is a 'param' instead

  proc type make(type t): Sandwich(t) {
    return new Sandwich(t);
  }
}


var realSandwich = Sandwich.make(real);
```

Compile output:

```
sandwich.chpl:10: error: unresolved type specifier 'Sandwich()'
sandwich.chpl:1: note: candidates are: Sandwich(type eltType)
```

**Associated Future Test(s):**
*TODO*

### Configuration Information

- Output of `chpl --version`: `chpl Version 1.16.0 pre-release (a110861)`

**Comment by ben-albrecht** [comment]
@noakesmichael was interested in this.

**Comment by ben-albrecht** [comment]
This came up when discussing alternatives to the `QueueFactory` class in #6812  with @LouisJenkinsCS

**Comment by cassella** [comment]
I think this has to do with calling a ``type method`` on a generic
class. not with what the ``type method`` returns or depends on.

I get the same error with this:

```chapel
class Sandwich {
  var filling;
  proc type eat() {
    writeln("Mmm");
  }
}

Sandwich.eat();
```


But it works with the last line changed to

```chapel
Sandwich(string).eat();
```

And conversely, a non-generic class with a ``type method`` that
returns a type that depends on a ``type`` argument of the method
works:

```chapel
class Soup {
  type eltType;
}

class Sandwich {
  proc type make(type t) {
    writeln("Out of sandwiches.  Have some ", t:string, " soup!");
    return new Soup(t);
  }
}

var s = Sandwich.make(string);
writeln(s);
delete s;

**Comment by cassella** [comment]
I don't know what the ``QueueFactory`` was going to look like, but I
modified my last example and sudo made you a sandwich factory,
which works for me:


```chapel
class Sandwich {
  type eltType;
}

class SandwichFactory {
  proc type make(type t) {
    return new Sandwich(t);
  }
}

var s = SandwichFactory.make(string);
writeln(s.type:string);
delete s;
```

**Comment by cassella** [comment]
Is this not-a-bug?

**Comment by bradcray** [comment]
Doesn't seem like it, does it?  @ben-albrecht?

**Comment by ben-albrecht** [comment]
Agreed. Thank you for @cassella
