### ISSUE TITLE
Provide (or expose) Cholesky Decomp in LinearAlgebra modules

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#6846]
It appears there are tests around [Chapel's Cholesky Decomposition](https://github.com/chapel-lang/chapel/blob/master/test/users/aroonsharma/LinearAlgebra/cholesky.chpl) but it is not documented within the [LinearAlgebra[(http://chapel.cray.com/docs/1.15/modules/packages/LinearAlgebra.html) package.  Please provide something akin to [SciPy's implementation](https://www.quantstart.com/articles/Cholesky-Decomposition-in-Python-and-NumPy)

**Comment by buddha314** [comment]
Thanks @daviditen I can't add labels to the tickets.

**Comment by daviditen** [comment]
PR #8346 added a Cholesky decomposition function to the [LinearAlgebra](https://chapel-lang.org/docs/master/modules/packages/LinearAlgebra.html#LinearAlgebra.cholesky) module.
