### ISSUE TITLE
error handling and sync blocks

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#6853]
If you have a 'sync' block, it's supposed to track errors created by any task that might have been spawned within the 'sync' block and 'throw' them at the conclusion of the 'sync' block.

That's fine, but how does the compiler know if error handling was required?

E.g.
``` chapel
sync {
  someFunction();
}
```

Since tasks created in `begin` statements within `someFunction` might throw, `sync` might also throw. Should the user be required to handle the potential for errors from a `sync` in strict error handling mode?

I can see these options:
 1. The compiler assumes that `sync` can `throw` and user's just live with that
 2. The compiler tries to do analysis to find the `sync` blocks that should `throw`. Note that this would complicate separate compilation because the compiler has to know both
 
     a) which functions can (transitively) create use `begin`
     b) which of those `begin` blocks can create tasks that might throw
 3. `sync` can `throw` but the user isn't required to handle it. (a.k.a. "unchecked throws").

**Comment by mppf** [comment]
Based upon discussions with @psahabu and @bradcray, I'm initially trying to implement option 1 above.

**Comment by mppf** [comment]
We discussed this in a meeting but some team members had reservations about the approach.

**Comment by lydia-duncan** [comment]
My understanding of the current approach is that sync blocks must always be either in a throwing function or surrounded by a `try` block in strict/pedantic mode.

This makes me uneasy, but that might stem from a misunderstanding of strict/pedantic mode as they stand today.

As an example, consider the following program (apologies if the syntax is incorrect):
```chapel
proc beginThatThrows () {
  begin functionThatThrows();
}

proc syncFn () {
  sync {
    beginThatThrows();
  }
  sync {
     functionThatDoesNotThrow();
  }
}
```
My understanding of the current proposal is that there is a mode where both `sync` blocks would be marked as needing a `try` or `try!`.  My instinct is that we would only want to require that of the first `sync` block, and only if the functions it calls are marked `throws`.  But I also think that if a function has a `begin` block that might throw and is not surrounded by a `sync` and error handling, it would have to be marked as `throws` since the throwing call might outlive the scope of the function.  I think it would be inappropriate and confusing for a `sync` block to be treated differently than the functions it called in this manner.

Is that consistent with the current strategy?  Is there an issue with my understanding of `begin`/`sync`?

**Comment by mppf** [comment]
> My instinct is that we would only want to require that of the first sync block, and only if the functions it calls are marked throws.

The issue is not whether or not the functions called directly in the sync block throw. E.g. in this case, I don't think we care if `beginThatThrows` is marked throws or not. It doesn't itself throw. It creates a task that throws.

> But I also think that if a function has a begin block that might throw and is not surrounded by a sync and error handling, it would have to be marked as throws since the throwing call might outlive the scope of the function.

That doesn't make any sense to me. It's true that the "throwing call might outlive the scope of the function". But what does that have to do with marking the function as `throws` ?

Conversely, if I had this - even in strict/pedantic mode - what should it do?
``` chapel
proc beginThatThrows() throws {
  begin functionThatThrows();
}
proc syncTest() {
  sync {
    try! beginThatThrows();
  }
}
```

Here I've marked the beginThatThrows function as throwing and wrapped the call in a `try!`. The point is that the error from `begin functionThatThrows()` has nothing to do with the call site of `beginThatThrows` - it only matters where we wait for the task that threw the error to complete.

**Comment by lydia-duncan** [comment]
Maybe I'm misunderstanding the point of marking a function as `throws`.  It seems to me that if a call to a function may result in an error being thrown, whether immediately in the call or later due to it having started a task that throws via `begin`, that should be indicated.  Regardless of whether `beginThatThrows` has completed or not before the error is thrown, the call to `beginThatThrows` is still what is responsible for the error getting thrown.

Your point about the `try!` not being sufficient to catch the error is interesting, though that seems like it would be very confusing to the user - how are they going to track down the task that gave the error if it turns up after they expected to see it run?  Should the `try!` apply to tasks spawned within the statement it enclosed?  Does it make equal sense for the following to have `try!` not apply?
```chapel
proc tryAroundBegin() {
  try! {
    begin functionThatThrows();
  }
}
```
Maybe this implies I should have paid more attention to the implementation of `try`/`try!` for `begin` statements - sorry.

**Comment by lydia-duncan** [comment]
How are you supposed to catch errors from `begin` blocks if they pass through the scope in which they were defined, regardless of whether they are enclosed in a `try` block?  If the task created happens to run during a portion that has a `catch` block, should it fall into that one?  That seems wrong to me.
```chapel
proc tryAfterBegin() {
  begin functionThatThrows();
  try {
     someOtherFun(); // what happens if the begin block executes during here?
     // It shouldn't get caught by this block, right?
  } catch {
     ...
  }
```

**Comment by lydia-duncan** [comment]
My point is that I think the scope in which the `begin` block is defined knows best about how errors related to it should be handled, rather than whatever level of outer scope happens to have a `sync` within it.

**Comment by buddha314** [comment]
You go, @lydia-duncan !  Stand up to this b.s. patriarchy!!!

**Comment by lydia-duncan** [comment]
lol, not sure what the patriarchy has to do with this :p

**Comment by buddha314** [comment]
me neither... just felt fun to say

**Comment by mppf** [comment]
Answering a few questions:
>      someOtherFun(); // what happens if the begin block executes during here?
>     // It shouldn't get caught by this block, right?

Nope, I can't even imagine how to implement that... We only know the `begin` threw an error when we wait for the task that was running it.

> My point is that I think the scope in which the begin block is defined knows best about how errors related to it should be handled, rather than whatever level of outer scope happens to have a sync within it.

right, if the code in the `begin` block knows how to handle the error, it should just use `try` and `catch` around the body of the `begin`.

The pattern of handling errors in another task is to support a different sort of pattern. Consider a program that farms out work processing individual files to `begin` blocks. If any of these tasks die with an error, the program farming out the work might have an intelligent strategy to respond:
 * report the error to the user
 * ignore the file
 * retry the file (maybe with a slower / more complete processing function).

**Comment by mppf** [comment]
@lydia-duncan and I had a conversation about this and hashed through several design alternatives. The alternatives we brought up are:
1. `begin` blocks can never throw (ie users would have to use try/catch or try! in each begin block calling throwing code)
2. users explicitly mark functions that can create `begin` blocks that aren't in a `sync` within that function with some new keyword, say "beginthrow" as a strawman
3. compiler analysis determines when a `sync` block doesn't need to throw
4. `sync` blocks are always considered to throw.

Each of these has some drawbacks. Probably the best way to view the current solution (4) is that it's the strategy we use in the absence of better compiler analysis, and that we can hope to improve upon the analysis in the future. In terms of a language design choice that leaves room for future improvement/growth as we gain experience, the most conservative strategy here is 1 or 4.

Here are the drawbacks of each approach:
1. `begin` never throws would require users to add code for error handling to each `begin` but it's almost certainly the case that there are more `begin` than there are `sync`.
2. About explicitly marking with say "beginthrow", adding a keyword like that seems like a lot to do to support one of the lesser used features of the language (begin and sync). But at the same time, users might need to know if a function that is called can create a task and leave it running at all. It's unclear how much this should be a language-supported syntax kind of thing vs. a documentation issue. Generally, we prefer a strategy that allows programmers to leave out such details that would make the program more verbose - as with not requiring type declarations everywhere. So we'd probably want the compiler to figure it out most of the time, which leads in to the next one...
3. Compiler analysis would be great to do this, but it's unclear how hard it would be when we have separate compilation. It depends on the details of the separate compilation strategy how realistic this is.
4. if `sync` block always throws, it might be annoying to have to wrap it in `try` in pedantic mode; on the other hand if it's defined to always throw, we could relax that `try` requirement for `sync` specifically.

**Comment by psahabu** [comment]
Of the four options, a relaxed form of (4) seems ideal. Maybe `sync` could be handling-optional, where unhandled errors continue rather than halt?

I could also be convinced of (1). I agree with @mppf that (2) and (3) seem like overkill for this corner of the language.

**Comment by psahabu** [comment]
@mppf, @lydia-duncan: should we consider this issue closed or are there tasks remaining for it?

**Comment by lydia-duncan** [comment]
I think I would be interested in seeing 3 eventually if possible, but I suspect that is long down the road if it is even feasible.  I would be tempted to leave this open for now, and am now wondering if it is something that should be discussed at the review when we get to the error handling slides

**Comment by psahabu** [comment]
It's worth a brief mention in the error handling slides, when `sync` comes up. The current implementation is (4), right?

**Comment by lydia-duncan** [comment]
Yeah, I think it is (4)

**Comment by mppf** [comment]
I think we should close this issue, since the issue is addressed enough for the current error handling scheme. I think it'd be reasonable to create a feature-request issue for "compiler analysis determines when a sync block doesn't need to throw" but I think this issue has served its purpose and future work should be driven by a new issue. This issue was created to discuss/get consensus, and it did that. Other issues can still refer to it, and we could even potentially re-open it in the future.
