### ISSUE TITLE
error handling: groups of errors

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#6854]
[CHIP 8](https://github.com/chapel-lang/chapel/blob/master/doc/rst/developer/chips/8.rst) includes the idea that tasks can raise errors, and if they do, the errors will be propagated to the parent task at a *task join point* (such as a the end of a `sync`, `cobegin`, or `coforall` statement).

Let's consider a `coforall` for a minute. A `coforall` could create an error for each task - and so the *task join point* might have to handle many errors. How do we represent these errors?

CHIP 8 describes an Error subtype called `AsyncErrors`. 

My implementation work has started with an error subtype called `ErrorGroup`. Either way, we need to decide upon the API for this collection of errors and also how they behave with `catch` blocks.

So, here are the questions I'd like to answer in this issue:

 1. What is the name of the Error subtype that collects multiple errors? (currently `ErrorGroup`)
 2. If there happened to be just one error thrown from a sub-task, should we raise that error directly instead of raising an `ErrorGroup` containing a single error? (currently: no)
 3. If there happened to be just one class of error (e.g. `IoError`), should a catch block for that type of error catch the entire list? And then each `Error` subtype would have a way to enumerate multiple errors encountered? (currently: no)
 4. When nesting is used, as with a `coforall` within a `coforall`, does that result in an `ErrorGroup` containing an `ErrorGroup`? Or a single `ErrorGroup` containing all of the errors? (currently: no)
 5. Should we provide methods on `ErrorGroup` that
    a) indicate if a particular type of error is present in the list? (currently: yes)
    b) allow retrieving the errors by type? (currently: yes)
 6. Should printing out an `ErrorGroup` with `writeln` e.g.
     a) Print out every contained error? (currently: no)
     b) Print out some kind of summary of the contained errors? (currently: yes)
     c) Print out a fixed number of errors (using numbers to indicate how much wasn't printed)? (currently: yes)
     d) Print out one error of each error type encountered? (currenly: no)
 7. Based upon the above, what should be the user-facing API for `ErrorGroup` ?
      Currently, we have
      ``` chapel
      class ErrorGroup : Error {
        /* yield the errors contained in this group */
        iter these();
        /* Write a summary of the errors contained in this group.
           The summary attempts to use limited space. In particular,
           it prints only a constant number of errors, using
           numbers to indicate how many other errors there are.
         */
        proc writeThis(f);
        /* Iterate only errors that are a subtype of the passed type */
        iter filter(type t);
        /* Returns `true` if this group contains any errors that
           are a subtype of the passed type */
        bool contains(type t);
      }
      ```

**Comment by mppf** [comment]
Regarding 2,3,4, I think the answer to all of these should be *no* because I think to do otherwise would be confusing. In particular, for 2 and 3, programmers would have to write catch blocks that handled errors in 2 places - directly for particular sub-types and also as part of a list of errors.
In contrast, if errors thrown by sub-tasks are always raised in an `ErrorGroup`, it is explicit that multiple errors are possible (and the user is expected to handle these in a `for` loop). Additionally, constructs that contain only tasking operations probably have the only meaningful errors being ones that come from the sub-tasks, so looping over the errors in `ErrorGroup` would be *the* place to handle such errors. Lastly, how a task responds to an error it rasied might be different from how it responds to an error in a child task. For example, the child task might represent a computation that could be restarted - but an error in the *leader* task doling out work might be fatal.

@psahabu indicated to me that the answer to 2 should be *no*.
@bradcray indicated to me that the answer to 5a and 5b is *yes* and seemed to believe my argument about 2,3,4.

**Comment by psahabu** [comment]
I agree with the decisions that have been made so far. In my view, `ErrorGroup` should be used when an error on a thread could impact coordination, whereas errors affecting a single thread should be handled by that thread.

**Comment by mppf** [comment]
I'm currently leaning towards changing 4 to yes so that we don't make ErrorGroups of ErrorGroups. Also, a reasonable name for ErrorGroup might be SubTaskErrors.

**Comment by mppf** [comment]
See also #7046.

**Comment by mppf** [comment]
As of today, the consensus direction is to rename ErrorGroup to TaskErrors. We will consider possibly retaining ErrorGroup as a superclass of TaskErrors.

**Comment by psahabu** [comment]
@mppf should we close this issue seeing as we already have TaskErrors, or leave it open to discuss if we also want ErrorGroup?

**Comment by mppf** [comment]
This issue has been addressed enough to be closed. See PR #7211 and #7127.
