### ISSUE TITLE
Provide eigenvalue/vector methods for Hermitian matrices

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#6855]
Another key building block of ML is eigenvector analysis.  SciPy has a [nice set of eigenvalue routines](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.eig.html#scipy.linalg.eig)

Am I driving you nuts yet?

**Comment by ben-albrecht** [comment]
Even though this one came first,  #7260 requested the more general feature of eigenvalue/vector solvers. Let's use that one going forward.
