### ISSUE TITLE
Support HDF5 for storage

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#6901]
This was mentioned on the [GSOC page](http://chapel.cray.com/gsoc/ideas.html) but I don't see a status. This could be very useful in addition to other data layers like SQL and will help with Python integration.  This is a detail relating https://github.com/chapel-lang/chapel/issues/6850

**Comment by mppf** [comment]
We received a lot of excellent GSoC proposals this year and unfortunately weren't able to accept the HDF5 one with the mentoring resources and GSoC slots we had available. The work you are pointing to was done during the GSoC proposal period.

**Comment by buddha314** [comment]
Thanks!  Is it on the calendar for the internal team to handle?

**Comment by mppf** [comment]
I don't think there's a specific timeline for completing it, no.

**Comment by daviditen** [comment]
HDF5 has been supported for some time now. Its documentation is [here](https://chapel-lang.org/docs/modules/packages/HDF5.html).
