### ISSUE TITLE
Design questions about `chplconfig` files, `./configure` and `printchplenv`

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#6972]
* It seems that when doing a `./configure` and then `make install` the `chplconfig` file that's created is left in the original copy of the source tree, affecting future uses of it until it's manually removed or another `./configure` step is run.  Is this intentional?  Desirable?

* When using a `chplconfig` file and `printchplenv`, settings that are established by the `chplconfig` file are marked with a `*` similar to those set via environment variables.  This confused me for awhile because I checked my environment and saw that I had not set them myself explicitly (which is what I think of the `*` as indicating).  Should they be marked with some second, distcint symbol?  (or not marked at all?)

**Comment by bradcray** [comment]
Tagging @mppf, @ben-albrecht, and maybe @ronawho as maybe being interested in this.

**Comment by mppf** [comment]
For the first point, it's typical for a `./configure` based project to have that behavior. The way to avoid it is to use out-of-tree builds - where you configure in say `$CHPL_HOME/../mybuild` and then run `make` in that directory. We don't support out-of-tree builds right now. One goal of our `./configure` support is to make Chapel fit in a bit more with the build (and install) behavior people are used to. So I'm not sure we should try to change it directly, but we could seek to support out-of-tree builds (say).

For the second, I think it'd be great to have an alternative to `*` to mean "it came from config file".

**Comment by bradcray** [comment]
On the first point, I'm OK leaving it as-is (and am not particularly excited about having any of us put in the effort to support out-of-tree builds at this point).  It would also seem natural to me to have `make install` `mv` the `chplconfig` file rather than copying it, based on an assumption that once people do `make install` they wouldn't necessarily care whether it was still there or not, but maybe there's a use case I'm not anticipating.

For the second, I took a tab at this in PR #6991.

**Comment by mppf** [comment]
I like the idea of separating but I think `+` would be a better marker than `*` since the environment variables take precedence over the file values (i.e. they bind more tightly). But it's mostly arbitrary.

**Comment by vasslitvinov** [comment]
Sounds good to me. I don't have a preference for the character.

**Comment by ronawho** [comment]
I also have a slight preference for `+`, but I don't feel strongly about it either

**Comment by bradcray** [comment]
PR #6991 addressed item 2 above.  Though I think item 1 still has merit, it didn't gain much support this time around, so I'm closing this issue until someone else gets bitten by it.

**Comment by ben-albrecht** [comment]
> Though I think item 1 still has merit

I agree - something still doesn't sit right with me about the current behavior...

> For the first point, it's typical for a `./configure` based project to have that behavior. The way to avoid it is to use out-of-tree builds - where you configure in say `$CHPL_HOME/../mybuild` and then run `make` in that directory. 

@mppf - Is it typical for the configuration to outlive a `make clean` or `make clobber`? I believe a user needs to manually delete their `chplconfig` in order to undo the effects of calling `./configure`.

**Comment by mppf** [comment]
@ben-albrecht - it's typical that `make clobber` removes the configuration information and I don't see any reason we couldn't have `make clobber` clear out `chplconfig` - but I suppose in that setting we might worry about deleting a manually authored one (so should we have two different chplconfig files? or just warn that make clobber deletes it? or move it rather than deleting?).

**Comment by ben-albrecht** [comment]
>  so should we have two different chplconfig files? 

That's an interesting idea. We could utilize the existing `chplconfig` variants, e.g. `./configure` will (over)write `chplconfig`, and `make clobber` will remove `chplconfig`, but they will both ignore `.chplconfig`. They could still emit a warning about an existing `.chplconfig` too:

```

> ./configure
...
warning: $CHPL_HOME/chplconfig has been created and will take precedence over existing $CHPL_HOME/.chplconfig

> make clobber
...
rm $CHPL_HOME/chplconfig
warning: $CHPL_HOME/.chplconfig still exists and may impact Chapel configuration. 
         See printchplenv output for more information.
```


> just warn that make clobber deletes it?

Interactive warnings in make targets don't seem like a good idea.

> move it rather than deleting

This also sounds reasonable, but it doesn't seem like a typical behavior.

**Comment by mppf** [comment]
> >    just warn that make clobber deletes it?
> Interactive warnings in make targets don't seem like a good idea.

I meant warn about it in the chplconfig documentation.

**Comment by ben-albrecht** [comment]
> I meant warn about it in the chplconfig documentation.

Ah, well regardless of our decision, we should warn users about this caveat in the documentation.
