### ISSUE TITLE
Rename Barrier module

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#6979]
### Summary of Problem
The `Barrier` module has a record named `Barrier` and its constructor `proc Barrier`. This creates major issues as can be seen in the source code sample. Although this brings up the possibility of user writing such a module and trying to use it in this fashion, I think the Barrier module should be renamed until the fundamental issue is fixed in a more principled way.

### Steps to Reproduce

**Source Code:**

```chapel
module Foo {
  use Barrier;
}
use Foo;
use Barrier;
```

**Compile command:**
`chpl foo.chpl`

Results in:

```
foo.chpl:2: error: 'use' of non-module/enum symbol Barrier
$CHPL_HOME/modules/standard/Barrier.chpl:68: error: Definition of symbol Barrier
```

### Configuration Information

- Output of `chpl --version`:
`chpl Version 1.16.0 pre-release (a9493a6b17)`

**Comment by e-kayrakli** [comment]
@lydia-duncan helped me figure out the issue offline.

It appears that the issue happens when there is even only a class/record with the same name as the module but it can be worked around as such:

```chapel
module Foo {
  use Barrier only Barrier as MyBarrier;
}
use Foo;
use Barrier;
```

Note that this fix doesn't help as `use Barrier` also brings in `proc Barrier`.

**Comment by lydia-duncan** [comment]
I mentioned to Engin that this behavior is currently intended, as Chapel is a single namespace language, so we would have conflicts for a Barrier module and class with the same reachability at the point where the use statement was made.  It is possible that we should rethink whether use statements even consider symbols that are not enums or modules, but I agree that for now the best path forward is to rename the enclosing module

**Comment by bradcray** [comment]
How about renaming the record type to `barrier` (lowercase)?  Tagging @daviditen who I think wrote this code (?).

**Comment by e-kayrakli** [comment]
> How about renaming the record type to barrier (lowercase)? 

I like this idea as it would be similar to `module List` / `record list`. However, wouldn't it create a conflict btw the actual `barrier` method and the constructor?

**Comment by bradcray** [comment]
That's a good point.  Though if we rewrote the barrier type to use initializers rather than constructors, we'd probably be back on firm ground again (and I suspect that initializers are far enough along that this could be done today).

**Comment by daviditen** [comment]
Switching the record to be named `barrier` and changing the constructor to an initializer, we still get into trouble with the `barrier()` method because the compiler thinks it's a constructor:

`$CHPL_HOME/modules/standard/Barrier.chpl:116: error: Definition of both constructor 'barrier' and initializer 'init'.  Please choose one.`

What about making the module name plural `Barriers` under the argument that there are currently two types (atomic-based and sync-based) and could potentially be more in the future?

**Comment by bradcray** [comment]
We could also rename the method to something like 'join()' or 'waitForAll()' or ...  (and then rename it back once constructors are no longer supported! :) ).

**Comment by e-kayrakli** [comment]
> What about making the module name plural Barriers under the argument that there are currently two types (atomic-based and sync-based) and could potentially be more in the future?

This sounds good to me. On my fork I just changed it to `BarrierModule`.

> We could also rename the method to something like 'join()' or 'waitForAll()' or ... (and then rename it back once constructors are no longer supported! :) ).

`join()` sounds a bit misleading, doesn't it? `waitForAll` sounds OK. Maybe `notifyWait`?

**Comment by daviditen** [comment]
PR #7035 makes the module name change from `Barrier` to `Barriers`.  @bradcray, @e-kayrakli, Does this work for both of you?

**Comment by bradcray** [comment]
Since this is a breaking change, I think the PR needs to continue to support a `Barrier` module for the 1.16 release that `use`s `Barriers` and contains a deprecation warning (along with a test in `test/deprecated` to help us remember to remove it in 1.17).  Since this is a naming design decision, I think it should be put in front of the team for consideration before merging (along with the other alternatives that were considered).

**Comment by e-kayrakli** [comment]
@daviditen -- I am OK with this.

**Comment by mppf** [comment]
Barrier -> Barriers is OK with me but I think a reasonable alternative would be to name the module TaskBarrier or something like that to elaborate on what kind of barrier it is.

**Comment by bradcray** [comment]
@mppf: I sortof feel like, if anything, maybe we should do the opposite.  If we anticipate multiple types of barriers, keep the module name more general and have the type names reflect the specific flavors.

**Comment by daviditen** [comment]
Consensus across the team, as well as the people who commented here is that renaming the module to `Barriers` works.

I've modified PR #7035 to add back a deprecated `Barrier` module and a test in `test/deprecated`.

**Comment by daviditen** [comment]
#7035 is merged and looks to be in good shape.  The `Barrier` module is now named `Barriers`.

**Comment by BryantLam** [comment]
Why was renaming chosen as the solution rather than outright forbid the module identifier to be the same as the class/record identifier?

**Comment by bradcray** [comment]
@BryantLam: Are you asking "Why didn't we change the language to disallow using identifiers within a module that match the module's name?"  This seems heavy-handed and special-case-y to me (e.g., would we also disallow local variables that match the name of a procedure they're defined within or module-scope variables that match their module's name?).  I think having a type named after a module isn't inherently broken or not useful, it's just a potential source of confusion.  For example, the following code works:

```chapel
module C {
  record C {
  }
}

use C;
var myC = new C.C();
```

but that doesn't mean I'd recommend it as a preferred style.
