### ISSUE TITLE
LLVM progression plans

### ISSUE THREAD

**Issue by dmk42** [chapel-lang/chapel#6993]
As worked out in the discussion of #6962 , the following are planned for LLVM.

- [ ] Between releases 1.16 and 1.17, switch to LLVM-is-the-default.
- [x] After LLVM 5.0 is working with Chapel (but not necessarily included), remove support for LLVM < 4.  The purpose is to keep the source as clean as possible consistent with leaving enough history there to make future edits easier.
- [x] Remove autotools-build support for LLVM at one of the times above, as LLVM >= 4 will only build with cmake.
- [ ] When we upgrade to LLVM 5.0, switch to an llvm-src strategy instead of tarballs.

**Comment by mppf** [comment]
@dmk42 - I think we should close this issue (we have other ways to track LLVM is default).
