### ISSUE TITLE
Remote Serialization for Records

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#6995]
Remote Serialization For Records
================================

The current ``remoteValueForwarding`` pass attempts to reduce communication for
variables passed to on-statements by bit-copying them into the arg bundle.
Bit-copying is effective for Plain-Old Data types, but is insufficient for
more complex types (e.g. a record-wrapped class). We would prefer to have a
deep copy of the record-wrapped class on the destination locale.

Today's ``parallel`` pass attempts to reduce communication by broadcasting
const globals to other locales. This is also done by bit-copying and shares
the same disadvantages as RVF where record-wrapped classes are concerned.

I am proposing an optional interface on records that the compiler can use
for serialization/deserialization across on-statements and for global
broadcasting. I also propose a new compiler flag, ``--[no-]remote-serialization``,
to enable/disable this functionality.

The Interface
-------------------------------
Users can implement two methods on a record that the compiler will use for
serialization.

```chpl
proc chpl__serialize() : ??
```

This method accepts no arguments and must return something (i.e. not ``void``).
For now, I recommend that we restrict the returned type to either primitive types
or types that can be auto-destroyed. I believe this will make it easier to avoid
leaks.

If we wanted to allow classes to be returned, we could add an additional method
like:

```chpl
proc chpl__destroySerializedData(data) : void
```
To keep things simple, I think we should stick to records and primitive types for now.

-------------

```chpl
proc type T.chpl__deserialize(data) : T
```

This is a type method that accepts a single argument and returns a record with the
same type as its parent record. If a ``chpl__serialize`` method is found without
a matching ``chpl__deserialize`` method, the compiler will emit a warning and will
not attempt serialization for that record.

Program Execution
---------------------------
If the compiler decides to forward a variable in ``remoteValueForwarding``, it will
insert a call to ``chpl__serialize`` before each call to the on-statement. The result
will replace the variable in the on-statement's formals and in the arg bundle.

The compiler will then insert a call to ``chpl__deserialize`` at the beginning of the
on-statement and pass the serialized data formal as an argument. The result will be
used in place of the original record throughout the on-statement.

The serialized data will be destroyed at the end of the on-statement, followed by
the result of ``chpl__deserialize``.

Here is an example of some AST before ``remoteValueForwarding``:

```
// on-statement call-site
call on_fn tmp myRecord;

function on_fn(const in dummy_locale_arg, const ref myRecord : Foo) {
  call writeln myRecord;
}
```

After RVF, the AST would look more like this for a record that returns
a ``3*int`` as its serialized data:

```
var myRecord_data : 3*int;
call chpl__serialize myRecord myRecord_data;
call on_fn tmp myRecord_data

function on_fn(const in dummy_locale_arg, const myRecord_data : 3*int) {
  var myRecord : Foo;
  call chpl__deserialize myRecord_data myRecord;
  call writeln myRecord;
  call chpl__autoDestroy myRecord_data;
  call chpl__autoDestroy myRecord;
}
```

Broadcasting Globals
--------------------------
If the compiler finds a serialize/deserialize method pair we can use those
methods to better broadcast const globals. Instead of a call to the
``PRIM_PRIVATE_BROADCAST`` primitive, the compiler will insert a call to an
internal-module function named ``chpl__broadcastGlobal``. This function will
take two arguments:
- A ref to the global to be broadcasted
- An unique integer ID representing the global

The unique ID will be used to index into a table of void pointers on each locale,
where each entry is a pointer to the local global data. This function will be
responsible for calling ``chpl__serialize`` and moving the result of ``chpl__deserialize``
into the local global data.

If an autoDestroy is available for a broadcasted global, the compiler will insert
a call to ``chpl__destroyBroadcastedGlobal`` before the original global is destroyed.
This function is responsible for calling ``chpl__autoDestroy`` on the serialized
globals on other locales. This function will accept two arguments:
- a ref to the global to be destroyed
- a unique integer ID

My initial attempt at this functionality uses a simple ``coforall loc in Locales``
pattern, but would probably be faster with a tree-spawning pattern.

Implementation
-----------------------------------
I have an initial implementation of this proposal here:

https://github.com/benharsh/chapel/tree/remote-serialization

Testing
-----------------------------------

Performance testing (better or same):
- [x] ISx (can now use a const global domain without loss of performance)
- [x] miniMD

Correctness Testing:
- [x] full local
- [x] full no-local
- [x] full gasnet
- [x] gasnet-llvm
  - [x] examples/
  - [x] optimizations/remoteValueForwarding/serialization/

**Comment by mppf** [comment]
Cool! I'm generally on board with this plan but I have a few notes/questions.

 0. It's not clear to me if chpl__serialize and chpl__deserialize are good names for this, but I don't immediately have better names. I do think it should be a more user-facing name though. So far, methods the compiler calls on your type (that we publicize) all have short, simple names, like 'init', 'these', 'this', ... I also wonder if we should include in the name somehow the idea that we're serializing for the purposes of copying across locales, rather than for doing I/O (which uses the same term sometimes). Perhaps 'marshal' and 'unmarshal' would be better, more specific, terms.
 1. I think it's worth covering the example of RVF'ing a string. We talked about this before - the idea is that returning a record is acceptable because if the string is big enough, we'll want to GET the string data in the deserialize method. But if the string is small, it can fit inside some fixed-size buffer in the record.
 2. Quite some time ago, I was thinking about how the compiler could keep record types informed when they move across locales. I determined that a serialization strategy like this was the only one I could see working with non-blocking on statements. Is it your intention that *any time the compiler moves an object across locales* it will use the serialize/deserialize methods if they are provided? In other words, if I implemented a record with a "home locale" in it (like string has now), and updated that to the new locale in deserialize, could we rely on myrecord.homelocale == myrecord.locale always?
 3. For the unique integer IDs in broadcasting globals, are you talking about using the current chpl-privatization.h mechanism to manage the mapping from privatized id -> object?
 4. chpl_broadcastGlobal " will be responsible for calling chpl__serialize and moving the result of chpl__deserialize into the local global data." -- how does this interact with heap promotion? Does chpl_broadcastGlobal itself manage allocating heap memory and memcpy'ing the record to it?

**Comment by benharsh** [comment]
0) I'm unenthusiastic about the names as well. I'd be tempted to keep some kind of ``chpl__`` prefix for 1.16 and give it a more user-friendly name later if we feel good about the feature.

1) That's a good point. I'll spend some cycles attempting this. We don't have any way of creating a record with a fixed-size buffer today, right?

2) My intention is that the compiler will only use the serialize/deserialize methods when it determines that the record can be RVF'd. It should not invoke serialization for non-const things.

3) I will use a table like chpl_private_broadcast_table, just with a different name.

4) ``chpl__broadcastGlobal`` will not do anything for heap-allocated globals, at least for now. It will basically replace PRIM_PRIVATE_BROADCAST, which is not used with heap-allocated globals.

**Comment by mppf** [comment]
Re 4. but you still have to copy it to the heap, right? How does that work?

**Comment by bradcray** [comment]
I'm generally enthusiastic about this direction.  The use of the 'chpl__' prefix was the main thing that stuck out for me as well in reading it (i.e., I was going to say "why not just use serialize/deserialize?") but now that I've read the comment stream above, I'd also be OK with keeping the prefixes until we were more confidently wed to making the approach and names user-facing.

**Comment by benharsh** [comment]
@mppf : string serialization went fairly smoothly. See the last few commits on the linked branch that allow for serialization of strings, and include a short string optimization.

**Comment by benharsh** [comment]
Another reason to avoid using ``serialize`` and ``deserialize`` as method names is that remote serialization might not be the same kind of serialization required in other contexts. For example, a string serialized into a file requires all of the string's bytes. Remote serialization technically just needs a pointer and a locale ID.

Another example can be found in #7008

**Comment by mppf** [comment]
@benharsh - about the naming, how do you feel about marshal / unmarshal ?

**Comment by benharsh** [comment]
Lukewarm, but probably better than reserving ``serialize`` in general.

**Comment by mppf** [comment]
What about `pack` and `unpack` ?

**Comment by benharsh** [comment]
I like those slightly more. Anyone else have an opinion?

**Comment by bradcray** [comment]
If we're keeping them internal for draft 1, I'm not too worried about what we call them for now, though we will need to decide eventually.

I wonder if we should say something about the context of the copy/serialization in the name and whether that would help.  E.g., things like serializeForRemoteLocale or packForRemoteLocale or packForOn come to mind as being clear about why the serialization is happening (whereas I can imagine it'd be confusing if we had "serialize" mean "for I/O" and "pack" mean "for on-clauses" and "marshall" mean "for ZMQ".

Alternatively, we could pick a simpler name like serialize or pack and then have it take some sort of argument / where clause stating what the context is...

**Comment by benharsh** [comment]
Hearing no objections, I have opened PR #7050 and will do another round of testing after having merged with master.
