### ISSUE TITLE
High Memory Usage in Cyclic domain maps 

### ISSUE THREAD

**Issue by Praveenv98** [chapel-lang/chapel#7005]
Hi
locales = /* A 3 Dimensional arrangement of localities */
1    2     3  
4    5     6    
7    8     0

For const Mas = new dmap(new Cyclic (startIdx = (1,1,1), targetlocales = locales) );
const       distributed_domain = {1..100,1..1000,1...50} dmapped Mas
As I find in your research paper "Authoring user defined domain maps in chapel" local descriptors for this domain will hold many 3D indexes like (1,1,1) to (x,y,z) for some random x,y,z. I think it will cause more memory usage to represent these individual indexes(3D). why can't it be a index to locale index mapping in runtime, so we can limit the more memory usage, without holding each individual indexes in local descriptors. I think it's issue, So I don't post this in stack-overflow.

**Comment by Praveenv98** [comment]
Did keeping the indexes local to the locales have any advantage over mapping at runtime ?. I found a similar solution in DASH C++ template library for distributed data structures , they use mapping at runtime. 
Thanks 
Praveen

**Comment by benharsh** [comment]
Have you actually observed unnecessarily high memory usage, or are you just speculating?

We do not store each individual index separately in CyclicDist. We use a strided domain to represent the indices owned by each locale. For example, consider the following program:

```chpl
use CyclicDist;

config const n = 10;

proc main() {
  const Dom = {1..n, 1..n};
  const Space = Dom dmapped Cyclic(Dom.low);
  var A : [Space] int;

  for loc in Locales do on loc {
    writeln(A.localSubdomain());
  }
}
```

The ``A.localSubdomain`` call will map down to this line:

https://github.com/chapel-lang/chapel/blob/master/modules/dists/CyclicDist.chpl#L1177

The ``myBlock`` field is a strided domain stored for each locale. If you run this program with 4 locales, you would see the following output:
```
{1..9 by 2, 1..9 by 2}
{1..9 by 2, 2..10 by 2}
{2..10 by 2, 1..9 by 2}
{2..10 by 2, 2..10 by 2}
```

**Comment by benharsh** [comment]
We also do currently map indices to locales at runtime with the ``targetLocsIdx`` method:

https://github.com/chapel-lang/chapel/blob/master/modules/dists/CyclicDist.chpl#L378

**Comment by Praveenv98** [comment]
@benharsh 
Since I don't have sufficient resources (clusters) on my desk. I'm speculating based on what brad has told me on stack-overflow. 

https://stackoverflow.com/questions/45642821/continuation-on-how-do-dmapped-domains-in-chapel-language-get-actually-mapped

https://stackoverflow.com/questions/45578634/how-do-dmapped-domains-in-chapel-language-get-actually-mapped-onto

https://stackoverflow.com/questions/45554812/how-domain-maps-map-indexes-to-target-locales-array-in-multi-dimension-case

I want to implement a way for distributing data over localities in a c++ library, I find chapel domain maps is very much appealing from the library. So I'm looking for implementing domain maps in C++. I have watched some couple of videos about chapel. But still can't able to a way to do this, that was the saddest part of the story : (.  I clearly lost when I come to "How the three Global descriptors interact ?" & " how these are interacting with efficiency in mind " ?
@benharsh  Could you please share your thoughts on how domain maps can be implemented with efficiency ? I will be thankful to you. 
Thanks
Pree
I still have some queries so I close this when I got cleared :)

**Comment by Praveenv98** [comment]
I know c++ standard library containers and iterators are very much different from what chapel arrays are and iterators over domains. I think it is one of the most limiting factor. I think that chapel get it's super efficiency by doing everything (data access and operation mapping) based on domain maps, whether this is correct ?
Thanks

**Comment by benharsh** [comment]
Just so you know, you don't actually need a cluster to run Chapel. You can run Chapel in an oversubscribed mode on a desktop/laptop by using the GASNet UDP conduit. You can read more about the UDP conduit here:

http://chapel.cray.com/docs/latest/platforms/udp.html

I think the question you're asking is difficult to answer, as it depends heavily on the manner in which data is distributed. Also, Chapel's PGAS nature makes communication easy, but in C++ you will need to use something like MPI to send/receive information about your distribution.

A good starting point might be to try and implement something like BlockDist in C++. The BlockDIst code isn't very elegant, but it's the easiest distributed domain map we have:

https://github.com/chapel-lang/chapel/blob/master/modules/dists/BlockDist.chpl

A good way to understand BlockDist would be to actually use it and possibly add some debugging writelns in places you don't understand.

**Comment by benharsh** [comment]
I'm going to close this because we don't intend GitHub issues to be a forum for "how do I do X?" kinds of questions. The chapel-developers mailing list would probably be a better place for questions about domain map implementations. More information here:

http://chapel.cray.com/developers.html
