### ISSUE TITLE
error handling: errors in foralls may or may not be in ErrorGroup

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#7046]
Consider a program like forall-range-throws.chpl:
``` chapel
config const n = 1000;

proc test() {
  try {
    writeln("before forall block");
    forall i in 1..n {
      if i == 1 then
        throw new Error("test error");
    }
    writeln("after forall block");
  } catch errors: ErrorGroup {
    for e in errors {
      writeln("Caught group error e ", e);
    }
  } catch e {
    writeln("Caught other error ", e);
  }
}

test();
```

Are the errors thrown in the body of the forall in an ErrorGroup? Or not? Or nested in two ErrorGroups?

Currently, it depends on the implementation of the iterator that is being invoked by the forall statement. If it does not create any tasks / include coforall/cobegin, it won't use an ErrorGroup.

The test forall-range-throws.chpl is skipped in the NUMA configuration due to this issue.

What should we do?

**Comment by mppf** [comment]
@psahabu what do you think?

**Comment by bradcray** [comment]
My intuition is that the forall should always use an ErrorGroup for consistency from the user's perspective.  What would the downsides of that approach be?

**Comment by psahabu** [comment]
I'm with Brad, for consistency I think it's best if an ErrorGroup was always used, but there may be implementation or design issues making that difficult.

**Comment by mppf** [comment]
Right, consider this example:
``` chapel
 forall i in 1..n {
    throw new Error("test error");
  }
```

as compared to this example 
``` chapel
forall i in 1..n {
   coforall j in 1..m {
        throw new Error("test error");
   }
}
```

Should the 1st case throw an ErrorGroup of Errors, but the second case throw an ErrorGroup of ErrorGroups? If so, we'll have to distinguish between whether a coforall in a forall is from an iterator or from the body of the loop.

**Comment by mppf** [comment]
My current favorite strategy for this issue is to do the following two things:
 1. make ErrorGroups not support nesting. Adding an ErrorGroup A to an ErrorGroup B will add the contents of B to A.
 2. Adjust the compiler to add a call to ensure that any Error returned by a forall is in an ErrorGroup

I discussed this with @psahabu and we're on the same page. We don't think that supporting nesting in ErrorGroups adds much value, and this strategy greatly reduces the complexity of the adjustment the compiler needs to make for forall statements to be more uniform in what they can throw.

**Comment by bradcray** [comment]
This plan matches my intuition as well.

**Comment by mppf** [comment]
As of today, the consensus direction is to go with the favorite strategy above (flatten, add errorgroup for forall).
