### ISSUE TITLE
error handling: modes and fine-grained selection

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#7055]
Currently, one can choose between strict and relaxed errors using the compiler flag `--no-strict-errors` or `--strict-errors`. But that doesn't make so much sense because code itself should be making this selection. For example, a library author should be the one to decide whether their library works with strict error handling or not. Additionally, it should be possible to compile a library using a strict mode from code that is prototypical and in relaxed mode.

So, we need a way to select the error-handling mode in a more fine-grained way. Additionally, this is a good time to adjust the set of modes that are available. Right now we have "default mode" and "strict mode". In order to discuss what the modes do, we'll use the terminology in issue #6566: relaxed try, relaxed throws, or relaxed try!.

At a minimum any such strategy should allow selecting the error handling strategy at a module scope level.

Here is one proposal:
 * A `use` of a special module at the top-level within another module adjusts the error handing strategy
 * The available use statements to do this are:
     * `use RelaxedErrors` which corresponds to the current "default mode": relaxed try and relaxed try!
     * `use StrictErrors` which is a slight relaxation of the current "strict mode": relaxed try but not relaxed try!
     * `use PedanticErrors` which matches the current "strict mode" and offers no relaxation
 * If no such declaration is present, an explicit module declaration will work as if it contained `use StrictErrors` but code in an implicit file-name-based module will work as if it contained `use RelaxedErrors`

The design space for this question seems to be something like this:
 * How does one choose the error handling mode for a module? (The proposal overloads 'use' statements, but we could invent other new syntax).
 * Should it be possible to change the selection of strictness in an inner scope, say in a function? (The proposal allows this syntactically without issue)
 * What is the set of available error handling modes? Should we add relaxed-try? What about relaxed-throws? (The proposal adds relaxed-try but leaves out relaxed throws for now)
 * What is the default? (The proposal makes it relaxed in code not in a explicit module and relaxed-try in code inside a module - but these can be easily overridden if the default is not desired)

**Comment by bradcray** [comment]
My intuition on this topic, from a KISS perpsective, has been that we might decorate the `module` keyword itself.  Say, something like:

```chapel
relaxed module M { ... }
strict module M2 { ... }
```

where the default for a conventional `module M` declaration would be `strict` and the default for an implicit, file-based module declaration would be `relaxed`.  This doesn't permit finer-grained control like the `use`-based proposal in this issue, but has the benefit of simplicity.  I suppose I'm curious for realistic motivating examples for a library module that wanted a mixture of strictness modes before going down a finer-grain control path.  I could also imagine these modes controlling things other than simply error-handling semantics, such as whether symbols are public or private by default, default warning levels, etc.

If we do ultimately think we need/want finer-grain control, I think the `use`-based approach is appropriate and have imagined using it for other things like providing int+uint overloads that result in int vs. uint.  Though I think a difference here is that these `use`s are accessing pseudo-modules that just change compiler-behavior rather than actual code modules?

**Comment by mppf** [comment]
I think the main question I have about decorating module declarations with `relaxed` or `strict` is whether or not `relaxed` or `strict` refer only to error handling. Vs `use StrictErrors;` which only refer s to error handling and makes it clear.

Would a "relaxed module" disable performance warnings, say? Or take some other action to make it more relaxed? If not, would users be confused that `relaxed` and `strict` are about error handling, even though these terms don't refer to any existing error handling terms? (I.e. there was presumably a reason we called the compiler flag `--strict-errors` rather than just `--strict`).

**Comment by lydia-duncan** [comment]
Considering our default (and currently only) mode for `use` statements is for them to be transitive, the idea of utilizing `use` statements for this level of control makes me very nervous.  It also seems somewhat strange to me for the presence of one `use` statement versus another to impact the behavior of *keywords* present in the code.  Conceptually, the idea of a decorator on the module declaration seems much more naturally aligned with what we are trying to accomplish here (though Michael's point about whether `relaxed` only applies to errors is a good one)

**Comment by mppf** [comment]
As of today, there is consensus on some but not all of this topic.
1. Consensus to have relaxed/strict/pedantic modes, but some reservation about these terms (some don't like the term pedantic)
2. Consensus to have the default error handling mode for a module be relaxed for code only in an implicit module but strict or pedantic for a user-written module declaration. Open questions remain about behavior of nested modules.
3. We don't yet have consensus on the how to syntactically specify the mode for a module, but some possibilities include
``` chapel

// strategies with explicit annotation

relaxed module M { }

@attribute errors=relaxed
module M { }

module M(errors=relaxed) { }

module M with errors=relaxed { }

// use-like strategies

module M { with RelaxedErrors; }

module M { use RelaxedErrors; }

// strategies that don't invent new syntax

module M { param errorHandling = relaxed; }

module M { module.errorHandling = relaxed; }

module M { proc ErrorHandling() { return relaxed; } }

proc moduleInit() { errorHandling = relaxed; }

```

**Comment by ben-albrecht** [comment]
Did any syntax(es) emerge as victors from the meeting today?

**Comment by psahabu** [comment]
We all decided to stew on it for a bit, but we may just use pragmas as a placeholder for this release. This idea was bolstered given the sensible default checking for implicit (fatal) and explicit (relaxed) modules, minimizing the use of the pragmas.

#7244 and #7245 implement the pragma strategy and the defaults.

**Comment by mppf** [comment]
There are a lot of questions here. There is the philosophical question of whether or not the feature should have new syntax. Then there are questions about "What else would go there?".

One thing we identified in yesterday's meeting is that the near-term requirement is really to opt-in to halt-on-unhandled-errors for a module. Everything else is extra checking that isn't too unreasonable to use a pragma for now.

Brad's initial proposal of a `relaxed module` declaration is intended to be an easy way to request a lot of language feature adjustments. I'm currently thinking of this as `prototype module`. The idea is that it's one big switch. Note that a user of a module might very well care if it is "prototype" or not. What might the compiler treat differently about prototype code vs "production" module code? (these may or may not be good ideas):
 * errors are fatal if not handled
 * possibly, functions that are not called are not type checked vs type-check all non-generic functions for "production modules" (note that the current compiler never type checks functions that aren't called, but this is undesireable for library authors)
 * possibly, be less strict about implicit numeric conversions that lose precision
 * possibly, make all module members be public by default, vs private by default for "production" modules (note module members are currently always public by default)


The selection of "pedantic" mode (or, compile error if control flow is not clear with try) is more of an implementation concern of the module and indicates how it should be implemented/maintained. In a way, that is more similar to selecting compiler warnings on a per-module basis. Perhaps a user-facing attribute/pragma is reasonable here. What else might we want to select per-module? (these may or may not be good ideas):
 * turn on bounds checks / nil checks etc even in --fast
 * turn on/off warnings about failure to parallelize or vectorize
 * turn on/off warnings about old language features, or other warnings
 * turn on/off IEEE floating point code
 * opt-in to overflow checking for signed integers

**Comment by mppf** [comment]
I've updated my last comment with some additional information, including an earlier gathered collection of uses for an attribute syntax.

**Comment by bradcray** [comment]
I continue to like the notion of prototype vs. production modules and beyond its role in error-handling semantics, particularly like the idea of:

* making members "public by default" for prototype modules, and "private by default" for production modules
* doing lazy ("if called") type checking for prototype modules and proactive ("if public and non-generic") type checking for production modules

I think the main downside to such an approach is that it (potentially) rolls a bunch of behaviors into a single switch.  But the upside is simplicity and supporting what I hope can be thought of as common cases.

**Comment by mppf** [comment]
@bradcray - you've more or less convinced me of this; moreover that it is reasonable for it to be just before the `module` keyword; so all that is left to do is to agree upon a keyword for it (e.g.`prototype module`).

**Comment by psahabu** [comment]
I like `proto` and `prod`, but those might be too terse to distinguish.

**Comment by bradcray** [comment]
> I like proto and prod, but those might be too terse to distinguish.

I was thinking that we'd probably only need one new keyword to get explicit modules out of the default mode.

**Comment by mppf** [comment]
That's my view as well. We might want a way to select stricter checking, but that's more like warning control than anything else.

**Comment by lydia-duncan** [comment]
How does it apply to nested modules?  Will the outer module "give" its checking mode to any inner modules?  If so, we would need the second keyword to undo that behavior

**Comment by bradcray** [comment]
Good question.  I think you're positing a case where I'd want to say:

chapel```
prototype module M {
  production module S {
  }
}
```
(because I think all other cases are covered).  In order to save a keyword, I'd be willing to either simply not support this case or to not have submodules inherit the parent module's behavior.

**Comment by mppf** [comment]
I think it'd be OK if you just couldn't do that. After all, the inner module is less production-worthy in that it can refer to lexically scoped things in the outer module. And anyway, I don't plan to have this inherit-the-parent-mode behavior for implicit modules (we don't now, but we do inherit the mode for explicit modules). So a user in that situation might be able to make module M in Brad's example be an implicit module.

I wouldn't have a problem dropping the parent-module-sets-default behavior though.

**Comment by lydia-duncan** [comment]
That seems reasonable to me :)

**Comment by psahabu** [comment]
While it'd be pretty weird for an inner module to be production while the outer module is a prototype, it's weirder to have the parent set the default behavior. `prototype` should be opt-in, not opt-out, so having inner modules ignore their parent's behavior is sensible.

An added benefit is that it's consistent with the interaction between implicit and explicit modules, with the inner explicit module wholly independent from the prototype implicit module.

**Comment by mppf** [comment]
@bradcray @lydia-duncan @psahabu - how do you feel about literally `prototype module` being the syntax? Are we in agreement on that part, at least among the 3 of us? If so, perhaps it would be reasonable to try to do this for the release?

I don't think this keyword needs to be particularly short (so I wouldn't opt for `proto`).

**Comment by lydia-duncan** [comment]
I like that as a syntax.

**Comment by lydia-duncan** [comment]
One other edge case question, though - should you write `prototype private module M` or `private prototype module M` (where `private` means that the module M is not accessible outside of the scope in which it is defined, but says nothing about whether the symbols within its bounds are `private` or `public` by default)?

**Comment by psahabu** [comment]
I agree on the syntax and think we should move forward on it for this release.

`private prototype module M` sounds more natural to me.

**Comment by bradcray** [comment]
I like it too, but would want to make sure others on the team had a chance to gripe given the late date.  That said, I think it'd be at least as nice to give users a "may go away or change" keyword in 1.16 rather than a "may go away or change" pragma.  (I was opposed to more substantial syntax changes at this point, but a prefix keyword is not as scary to me... I just didn't think I was winning that argument when we met on Monday).

**Comment by mppf** [comment]
I'm going to close this issue with PR #7311. Issues #7355 and #7354 will cover further work in this area.
