### ISSUE TITLE
`domain` and `index` should not be reserved words

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#7059]
Given that most of our types (like `int`) are not reserved, it seems that these types should not be either.  Reserving them leads to some weird special cases in the compiler (like supporting `myArray.domain` queries) and also inconsistencies (e.g., places where `this.domain...` is a legal expression but `domain` is not).

**Comment by vasslitvinov** [comment]
@bradcray is this resolved now? Otherwise I suggest to label this as a Chapel-2.0 issue, given the impact that such a change may have.

**Comment by bradcray** [comment]
Yeah, I think it is resolved.  Specifically, we have now reserved other types like `int`, so I think reserving these is now consistent.  Meanwhile, there are other cases that we don't reserve type names where we should (e.g., #18216).  Thanks!

(all that said, wouldn't un-reserving a reserved word not be a breaking change anyway?)
