### ISSUE TITLE
Docs unclear with respect to support status of ofi and psm conduits

### ISSUE THREAD

**Issue by PHHargrove** [chapel-lang/chapel#7061]
In the [docs for CHAPEL_COMM_SUBSTRATE](http://chapel.cray.com/docs/1.15/usingchapel/multilocale.html#set-comm-conduit) I find ofi and psm conduits listed (among others).  
However, they do not appear in the [table of default CHPL_LAUNCHER values](http://chapel.cray.com/docs/1.15/usingchapel/launcher.html#currently-supported-launchers).  
So, I am left uncertain if Chapel intends to  
  1. support these two conduits, but w/o a default launcher.
  1. not support these two conduits, but has listed them in the substrate list for completeness.

**If (and only)** if you wish to consider psm-conduit as supported, then I noticed a `runtime/src/launch/gasnetrun_psm` which appears unused in master.  I think one just needs a couple more lines in util/chplenv/chpl_launcher.py` to make it the default for psm-conduit.

**If (and only)** if you wish to consider ofi-conduit as supported, then you need pretty much the same logic as for psm-conduit, which in turn is more or less identical to ibv-conduit.  I *have* actually tested this, FWIW.

Let me know if you need help testing.

Related:   
I am at least 90% sure that `gasnetrun_mpi` is a very good default for pami-conduit, and that it will work for many (most?) configurations using portals4 or shmem.  However, I have not tested those 3 conduits (yet?).

**Comment by ben-albrecht** [comment]
Hey @PHHargrove  -- thanks for reporting this. I think @gbtitus, @ronawho, (or maybe @bradcray) might be the right people to respond to this. They are currently unavailable, but we'll get you a response when they get back.

**Comment by ronawho** [comment]
`runtime/src/launch/gasnetrun_psm` was added by an external user with: https://github.com/chapel-lang/chapel/pull/5843. The docs you linked to are from 1.15, gasnetrun_psm is actually documented in the master (future 1.16 docs): http://chapel.cray.com/docs/master/usingchapel/launcher.html#currently-supported-launchers

That said, you're right that we don't currently default to gasnetrun_psm in `util/chplenv/chpl_launcher.py`.  This is because we don't have a machine to test on, so we weren't confident enough to make it the default launcher.

For ofi -- are you saying we could create a gasnetrun_ofi launcher, that's similar to the psm/ibv launchers?

**Comment by PHHargrove** [comment]
With respect to psm: the system I mainly use for testing psm-conduit is unavailable currently.  However, when it returns I can test if that may help you upgrade the status of psm-conduit.

With respect to ofi: YES. A launcher for ofi differs from the one  for ibv in exactly the same way psm-conduit does. It is a simple enough different that my test infrastructure is scripting its creation.

**Comment by ronawho** [comment]
Ok, I could take on making a gasnetrun_ofi launcher, but I also don't have a system to test that on.

**Comment by PHHargrove** [comment]
@ronawho
FYI in case you do have a desire to test ofi-conduit:  
Libfabric (the ofi comms library) includes a "sockets provider" that should run anywhere that GASNet's udp-conduit does.  It is available in many Linux distros and builds from source on Mac OSX (or available pre-built from homebrew).

**Comment by ronawho** [comment]
Ah cool. I didn't know that, thanks!

**Comment by bradcray** [comment]
Catching up on this thread...  @PHHargrove, is there any reason to believe that libfabric over sockets would be a better "portable default" for Chapel than using the udp conduit?  (e.g., in terms of performance or stability?  Not that we've had stability problems with the udp conduit).

**Comment by PHHargrove** [comment]
@bradcray 
No, on the contrary ofi-conduit over libfabric's sockets provider is slower and less reliable than udp-conduit.

**Comment by ronawho** [comment]
@PHHargrove I'm adding an ofi launcher and setting default launchers for ofi/psm in https://github.com/chapel-lang/chapel/pull/7679. I think that covers this issue, but let me know if not.
