### ISSUE TITLE
Support protobuf at least as far as ZeroMQ messages

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#7071]
Allow protobuf for messages over ZeroMQ, not sure what else to say about it...

**Comment by nspark** [comment]
This is bigger than the `ZMQ` module in that one could use protocol buffers for any number of de/serialization purposes.

This is mostly a thought experiment, but I think that protobuf support in Chapel would mean needing a proto2/3-to-Chapel compiler -- which might be able to leverage [protobuf-c](https://github.com/protobuf-c/protobuf-c) -- but would ultimately be generating Chapel source for a given protocol format. (My guess is that Chapel would have trouble linking to the generated code from the official C++ `protoc` compiler.)

This sounds like a cool-but-nontrivial project, for sure.

**Comment by cassella** [comment]
Is this satisfied by `module/packages/ProtobufProtocolSupport.chpl`, added in #16105?

**Comment by lydia-duncan** [comment]
I think so, but I'll wait to close until Brian or Nick weigh in

**Comment by buddha314** [comment]
I probably won't have a chance to test it, so if the Chapel team is confident, I believe them.
