### ISSUE TITLE
I/O formatting for c_ptr and c_void_ptr

### ISSUE THREAD

**Issue by nspark** [chapel-lang/chapel#7097]
### Feature Request

When dealing with C interoperability, I often find it helpful to print out pointers as hexadecimal values. In C, I can use the `%p` format specifier, but Chapel does not have that feature. This issue requests the addition of an explicit `%p` format specifier (and equivalent `%t`) for formatted I/O on `c_ptr` and `c_void_ptr` types.

**Comment by nspark** [comment]
An interim (or likely totally-sufficient) solution would be to add the following to `CPtr.chpl`:

```chapel
inline proc _cast(type t, x) where t:uint(64) && x.type:c_ptr {
  return __primitive("cast", t, x);
}

proc c_ptr.writeThis(ch) {
  if this == c_nil then
    ch.writef("(nil)");
  else
    ch.writef("0x%xu", this.uint(64));
}

/* ...and similarly for c_void_ptr... */
```

Using this, the following test code does what I'd want:
```chapel
var mem = c_malloc(uint(64), 1024);
writeln("mem = ", mem);
writef("mem = %t\n", mem);
c_free(mem);
```

The only notable difference is that the C programmer in me needs to default to `%t` instead of `%p`.

**Comment by nspark** [comment]
Unfortunately, the interim solution above produces an "attempt to dereference nil" runtime error with the following test:

```chapel
inline proc _cast(type t, x) where t:uint(64) && x.type:c_ptr {
  return __primitive("cast", t, x);
}

proc c_ptr.writeThis(ch) {
  if this == c_nil then
    ch.writef("(nil)");
  else
    ch.writef("0x%xu", this.uint(64));
}

record Foo {
  var mem = c_nil:c_ptr(uint(64));
}

var foo: Foo;
writeln(foo);
```

Does this come up because `writeln` calls `foo.writeThis`, which calls `foo.mem.writeThis` and `foo.mem` is nil?

**Comment by nspark** [comment]
Oddly, the case for `c_nil` and `c_void_ptr`-typed objects does not cause such an error:

```chapel
inline proc _cast(type t, x) where t:uint(64) && x.type:c_void_ptr {
  return __primitive("cast", t, x);
}

proc c_void_ptr.writeThis(ch) {
  if this == c_nil then
    ch.writef("(nil)");
  else
    ch.writef("0x%xu", this:uint(64));
}

record Bar {
  var mem = c_nil;
}

var bar: Bar;
writeln("c_nil = ", c_nil); // output: c_nil = (nil)
writeln("  bar = ", bar);   // output:   bar = (mem = (nil))
```

**Comment by mppf** [comment]
Hi -
> Does this come up because writeln calls foo.writeThis, which calls foo.mem.writeThis and foo.mem is nil?

Probably; there is code in the default writeThis that is generated to check if a field's value is 'nil' and it might not be firing for some reason.

I was able to "fix it" with this patch:

```
diff --git a/modules/standard/IO.chpl b/modules/standard/IO.chpl
index 2ac682f..d756ca5 100644
--- a/modules/standard/IO.chpl
+++ b/modules/standard/IO.chpl
@@ -3018,7 +3018,7 @@ private inline proc _write_one_internal(_channel_internal:qio_channel_ptr_t,
   // to stop writing if there was an error.
   qio_channel_clear_error(_channel_internal);

-  if (isClassType(t) || chpl_isDdata(t)) && x == nil {
+  if (isClassType(t) || chpl_isDdata(t) || isAnyCPtr(t)) && x == nil {
     // future - write class IDs, have serialization format
     var st = writer.styleElement(QIO_STYLE_ELEMENT_AGGREGATE);
     var iolit:ioLiteral;
```

However if this is not necessary the approach in your PR is probably better.
