### ISSUE TITLE
Deprecation syntax in chpldoc

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#7120]
It would be useful for the Chapel team and users of Chapel to support a deprecation syntax for symbols, such that the symbol is clearly marked as deprecated in the documentation.

This could be expressed in a variety of ways:

- role: `:deprecated:`
- directive: `.. deprecated::`
- pragma: `pragma "deprecated"` (yuck)

**Comment by lydia-duncan** [comment]
With the deprecated keyword being converted to an attribute, I think this can be closed, even though attributes are still unstable
