### ISSUE TITLE
Support iterating over reverse domains

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#7138]
You can iterate forward over a domain, but not backwards.  For instance

revdom.chpl
```
var v = {1..8};

for w in v {
  writeln(w);
}

// poops
for w in reverse(v) {
  writeln(w);
}

// also poops
for w in v.reverse() {
  writeln(w);
}
```

I don't have a preference for syntax.

**Comment by ben-albrecht** [comment]
I think what you want to accomplish can be done by iterating over `v` with a stride of `-1`:

```chpl
// does not poop
for w in v by -1 {
  writeln(w);
}
```

More on that in the [Ranges Primer](http://chapel.cray.com/docs/master/primers/ranges.html#operators).

Let me know if this did not address your suggestion.

**Comment by buddha314** [comment]
wha...? Thought I tried that one.  Okay, I'm going to [SO](https://stackoverflow.com/questions/45911989/iterate-a-domain-in-reverse-in-chapel) it anyway if you want more points.

**Comment by buddha314** [comment]
I know this is closed, but I have a follow up question.  I have a set of objects `var Players: [domain] Player` and I'd like to iterate over the objects in reverse order.  Something like

```
for p in Players by -1 {
   writeln(p.name);
   writeln("I was the %i to last player added".format(p.pid)")  // pid corresponds to domain index.
   p.shoeSize = 1.5*p.shoeSize
}
```  

And I want to make sure the shoe size updates.

**Comment by ben-albrecht** [comment]
For anyone following along, the last question was also taken to [SO](https://stackoverflow.com/questions/45923527/how-to-iterate-over-objects-indexed-by-a-domain-in-chapel).
