### ISSUE TITLE
Issues packaging Chapel for a distro

### ISSUE THREAD

**Issue by Azphreal** [chapel-lang/chapel#7185]
I'm using Chapel for a course this semester and thought I might as well take the opportunity to contribute to [Solus](https://solus-project.com). All test attempts were simply to compile "hello parallel world":

```chapel
config const numMessages = 100;
forall msg in 1..numMessages do
  writeln("Hello world (from iteration ", msg, " of ", numMessages, ")");
```

All build steps (sans patching) followed the path of:

```
./configure --prefix=/usr
make -j6
make -j6 install DESTDIR=$fakeroot_packaging_dir
```

My first efforts were using 1.15 as this is the current stable release. After some fruitless efforts (ending at the same point as later efforts, mind you), I found [PR 6063](https://github.com/chapel-lang/chapel/pull/6036) which actually introduced `make install` to the Makefile.

I initially tried patching in the contents of the PR to the stable 1.15; no luck, probably because of the other commits between the release of 1.15 and the merge. The compiler complained that `CHPL_HOME` was not set. Set it to `/usr/share/chapel/1.15`, and instead had errors that `libunwind`'s makefile wasn't found. I now can't reproduce that. Same result from just packaging up the fork and trying to use it.

In a fit of frustration, I've built the current git version (which wouldn't be accepted into the repos, but at least it'd build when 1.16 comes out). Instead I get errors saying [that it can't find hwloc or qthread](https://gist.github.com/Azphreal/e1ca7b241cfea5ca15835daf556ccbd3). This is likely due to the [stripping process involved in the build tool](https://gist.github.com/Azphreal/225ee3b56f84f32d3a0d1a928b3d71f9), but I'm not sure I can disable that. Removing the static dependencies might be a fix for that.

I'm not sure how high-priority making Chapel integrable into a system is at the moment, but I thought I'd just put my experiences here for if it gets revisited.

**Comment by mppf** [comment]
@Azphreal - over at https://github.com/chapel-lang/chapel-packaging we have our current effort to create a Debian package. (There is also an ubuntu directory there but you should assume it is out of date). We'd appreciate any help you can offer in packaging Chapel up for any OS distribution that we run on.

One challenge we have been encountering with the Debian package is that Chapel uses several third-party packages that don't already have their own Debian packages. It's likely that it's a similar case for other OSes. For that reason, we recommend starting by creating a package for the quickstart configuration (`source util/quickstart/setchplenv.bash`). That should allow you to avoid almost all of the code in third-party/. I bet that simply changing to the quickstart configuration will allow you to get a Solus package started.

It's very unlikely that Solus has a package for qthread. hwloc is more likely, but not a given. The quickstart config will not need either of these.

Thanks!

**Comment by Azphreal** [comment]
@mppf 

Hey, thanks. Didn't see the repo; mind you, didn't go looking either. I'll have a look around and see what other people have done and see if I can't get something working.
