### ISSUE TITLE
Unexpected "linux32-gnu-unknown" on ppc64

### ISSUE THREAD

**Issue by PHHargrove** [chapel-lang/chapel#7191]
I am testing chapel master with a current GASNet and am unexpectedly seeing the following install directory on both big and little-endian PPC64 systems (power7 and power8, respectively).
```
third-party/gasnet/install/linux32-gnu-unknown/seg-everything/debug
```
I particular note the system tuple "linux32-gnu-unknown" is definitely not what I would expect on a little-endian PowerPC64 lacking a 32-bit toolchain!

Likely related is the following seen while building gmp:
```
configure: error: Oops, mp_limb_t is 64 bits, but the assembler code
in this configuration expects 32 bits.
You appear to have set $CFLAGS, perhaps you also need to tell GMP the
intended ABI, see "ABI and ISA" in the manual.
```

While they disagree about the details, both GASNet and gmp have better info than "linux32-gnu-unknown".  Here is what the little-endian Power8 says:
```
[phargrov@gcc2-power8 chapel]$ ./third-party/gmp/gmp-src/config.guess
power8-unknown-linux-gnu
[phargrov@gcc2-power8 chapel]$ ./third-party/gasnet/gasnet-src/config-aux/config.guess
powerpc64le-unknown-linux-gnu
```

And, of course:
```
[phargrov@gcc2-power8 chapel]$ ./util/chplenv/chpl_platform.py
linux32
```

I will proceed with CHPL_TARGET_PLATFORM=linux64, but figured I should report this in case you wanted to improve the default on this platform.

In case it helps:
```
[phargrov@gcc1-power7 log]$ uname -a
Linux gcc1-power7.osuosl.org 3.10.0-514.26.2.el7.ppc64 #1 SMP Mon Jul 10 02:26:53 GMT 2017 ppc64 ppc64 ppc64 GNU/Linux
```
```
[phargrov@gcc2-power8 chapel]$ uname -a
Linux gcc2-power8.osuosl.org 3.10.0-514.10.2.el7.ppc64le #1 SMP Fri Mar 3 16:16:38 GMT 2017 ppc64le ppc64le ppc64le GNU/Linux
```

**Comment by PHHargrove** [comment]
I forgot to mention that for gmp the platform mis-identification is fatal:
```
checking size of mp_limb_t... 8
configure: error: Oops, mp_limb_t is 64 bits, but the assembler code
in this configuration expects 32 bits.
You appear to have set $CFLAGS, perhaps you also need to tell GMP the
intended ABI, see "ABI and ISA" in the manual.
gmake[5]: *** [/home/phargrov/upcnightly/EX-ppc64-smp-gcc-pshm/runtime/bld/dbg/chapel/third-party/gmp/install/linux32-gnu-unknown/include/gmp.h] Error 1
gmake[4]: *** [/home/phargrov/upcnightly/EX-ppc64-smp-gcc-pshm/runtime/bld/dbg/chapel/third-party/gmp/install/linux32-gnu-unknown/include/gmp.h] Error 2
gmake[3]: [try-gmp] Error 2 (ignored)
```

**Comment by PHHargrove** [comment]
Of course I meant CHLP_HOST_PLATFORM, above, not CHPL_TARGET_PLATFORM.

**Comment by ronawho** [comment]
We parse `uname` to determine architecture, but it looks like this is an unhandled case, so we mistakenly/stupidly assume linux32

I think https://github.com/chapel-lang/chapel/blob/master/util/chplenv/chpl_platform.py#L44 just needs to be updated to special case powerpc.

If it's not obvious, we don't have any powerpc machines in-house, so this is a config that we don't test on yet.

**Comment by ronawho** [comment]
I'll see if I can get a QEMU image up and running today to test out ppc

**Comment by ronawho** [comment]
I'm having a pretty hard time getting a qemu image for 64 bit ppc.

I don't think powerpc is an important platform for us ATM, so I think I'll leave this issue open, but punt on trying to fix it for now.

**Comment by PHHargrove** [comment]
@ronawho No push-back from me view if you "punt".  
I will continue to use CHPL_HOST_PLATFORM=linux64.

FWIW: your second link is ancient.   
I suspect the C++ compilers in a 2009 QEMU image are not up to the task of building Chapel and/or it's third-party dependencies.

**Comment by ronawho** [comment]
>FWIW: your second link is ancient. I suspect the C++ compilers in a 2009 QEMU image are not up to the task of building Chapel and/or it's third-party dependencies.

Yeah, the blog is old, but the actual images are debian_squeeze and debian_wheezy. I was able to get a 32-bit wheezy build working with gcc 4.9, which is new enough for us.

**Comment by PHHargrove** [comment]
A *32-bit* wheezy is "linux32", and thus not necessarily what you want for this issue, right?  
I can certainly test a PR on multiple PPC systems if that becomes necessary.

**Comment by ronawho** [comment]
Well, I wanted 32 and 64 bit ppc (big and little endian) to come up with a patch, but 32-bit is the only one I could get working. Though in hindsight, 32bit ppc probably doesn't matter at all.

I was going to do something like:

```diff
diff --git a/util/chplenv/chpl_platform.py b/util/chplenv/chpl_platform.py
index a07d9dfafb..94d23489c9 100755
--- a/util/chplenv/chpl_platform.py
+++ b/util/chplenv/chpl_platform.py
@@ -47,7 +47,18 @@ def get(flag='host'):
         platform_val = uname[0].lower().replace('_', '')
         machine = uname[4]
         if platform_val == 'linux':
-            if machine == 'x86_64':
+            if 'ppc' in machine:
+                if 'le' in machine:
+                    if '64' in machine:
+                        platform_val = 'linux_ppc_le64'
+                    else:
+                        platform_val = 'linux_ppc_le32'
+                else:
+                    if '64' in machine:
+                        platform_val = 'linux_ppc64'
+                    else:
+                        platform_val = 'linux_ppc32'
+            elif machine == 'x86_64':
                 build_64_as_32 = os.environ.get('CHPL_BUILD_X86_64_AS_32')
                 if build_64_as_32 == "1":
                     platform_val = "linux64_32"
```

But then I couldn't get any 64-bit qemu images to work, and I noticed that we check for `plaoform_val == 'pwr{5,6}' and `platform_val.startswith('pwr')` in some of our chplenv scripts and quickly realized that even if I could get the platform name right, testing on qemu system wouldn't allow me to determine good defaults for chpl_launcher or comm-substrate, so I decided to punt.

**Comment by ronawho** [comment]
Stumbled across an interesting article for ppc 8 VMs: https://developer.ibm.com/recipes/tutorials/how-to-get-free-access-to-power8-virtual-machines/

**Comment by PHHargrove** [comment]
@ronawho 

I can confirm correct detection of linux_ppc32, linux_ppc64 and linux_ppc_le64 based on the patch of Sep 6.

I don't have access to any means to test "linux_ppc_le32".

I don't know enough about the chplenv to comment on automatic launcher or substrate, other than to say "Yes, GASNet works there" :grin:

**Comment by ronawho** [comment]
Alright, I'm going to go head and merge a cleaned up version of that patch in https://github.com/chapel-lang/chapel/pull/7689

It doesn't do anything other than fix the platform detection, but I think that's at least a step in the right direction since `linux32` was really wrong.
