### ISSUE TITLE
Initializing sync fields with an empty sync variable in Phase 1 of initializers

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#7230]
Initializing a sync field with an empty sync during Phase 1 of an initializer results in a deadlock today.  Is this acceptable, or should the sync argument be copied/transfer ownership to the sync field?

Default initializers run into this when the sync field has no declared initial value and the new call relies on the default value for the corresponding argument.  It seems obvious that default initializers should just take ownership of the sync argument (as default constructors do), but should Phase 1 of explicit initializers mimic this behavior, since Phase 1 is initialization of the field?

### Steps to Reproduce

**Source Code:**

```chapel
class Foo {
  var s: sync int = 4;

  proc init(val: sync int) {
    writeln("inside the initializer");
    s = val;
    super.init();
  }
}

var outersync: sync int;
var foo1 = new Foo(outersync);
writeln(foo1.s.isFull);
delete foo1;
```

**Compile command:**
`chpl foo.chpl`

**Execution command:**
`./foo`

**Associated Future Test(s):**
[`test/classes/initializers/compilerGenerated/syncFieldTypeOnly.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/compilerGenerated/syncFieldTypeOnly.chpl) #7229
[`test/classes/initializers/phase1/syncFieldTypeAndInitSyncArg.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/phase1/syncFieldTypeAndInitSyncArg.chpl) #7229
[`test/classes/initializers/phase1/syncFieldTypeOnlySyncArg.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/phase1/syncFieldTypeOnlySyncArg.chpl) #7229

### Configuration Information

- Output of `chpl --version`: 1.16.0 (pre-release)

**Comment by lydia-duncan** [comment]
The implementation of the default initializer solution will depend on whether we unify the approach or not.  I've marked this post-release, since the discussion shouldn't take priority over other release priorities.  I'll re-ping after the freeze

**Comment by lydia-duncan** [comment]
(post release is only for PRs)

**Comment by bradcray** [comment]
My intuition is that for a user sync variable like this, it seems appropriate that the initializer blocks in phase 1 when trying to read `val` (`outersync`) since it's empty.  By analogy, if someone were to write:

```chapel
var outersync2 = outersync;
```

that would block too, right?

If I'm understanding, this suggests we need to do something special for compiler-generated initializers for sync fields with no initial values (?).

**Comment by lydia-duncan** [comment]
Now that things have settled down a bit, do others have an opinion?  I don't feel strongly one way or the other, so would probably go with Brad's intuition if left to my own devices.

**Comment by vasslitvinov** [comment]
It makes sense to have initializers have special treatment for sync variables. If the user passes a sync variable as an actual to the initializer, they mean "make the field look like this" (esp. w.r.t. full/empty). If the user wants simply to set the initial value for the sync variable, they can pass a value of the base type, not a sync. (Something needs to be done with the formals to make this happen.)

**Comment by vasslitvinov** [comment]
>  If the user passes a sync variable as an actual to the initializer, they mean "make the field look like this" (esp. w.r.t. full/empty).

That's for the default initializer. For a user-defined initializer, it may be unexpected/error-prone to have a special behavior of `myField = another sync var;` in Phase 1. I think this is what Brad says, too.

However, we want the user to be able to do what the default initializer does, i.e. "make the field look like this sync var". So maybe we can allow something like `myField.initFrom(another sync var)`  in Phase 1 as an alternative way to initialze `myField` ?

**Comment by vasslitvinov** [comment]
While there, if the default initializer is passed a "full" sync variable to initialize the corresponding field, should that sync variable come out empty as a result of the initialization?

**Comment by mppf** [comment]
> It makes sense to have initializers have special treatment for sync variables.

I disagree. I think Chapel programmers should explicitly program setting the sync variable state etc. in an initializer if it's complex in any way (say, creating an "empty" one with a particular value). Other than that, I think treating it the same as a variable initialization is the right move here.

I think that means I'm agreeing with Brad.

**Comment by lydia-duncan** [comment]
> While there, if the default initializer is passed a "full" sync variable to initialize the corresponding field, should that sync variable come out empty as a result of the initialization?

I think it would be confusing to have different behavior for what the user sends in depending on if the initializer is a default initializer versus an explicit one.  However, we need to allow the argument default value case to work for the default initializer.  Does that imply that we should change our behavior when a sync argument has a default value in general? (which is probably the more relevant question, though this discussion is also interesting).

**Comment by bradcray** [comment]
I don't think I agree with what Vass says here:

> If the user passes a sync variable as an actual to the initializer, they mean "make the field look like this" (esp. w.r.t. full/empty). 

Given a class like:

```chapel
class C {
  var field1: type1 = init1;
  var field2: type2 = init2;
  var field3: type3 = init3;
  ...
}
```

I imagine the default initializer being declared like this:

```chapel
proc init(formal1: type1 = init1, formal2:type2 = init2, formal3:type3 = init3, ...) {
  field1 = formal1;
  field2 = formal2;
  field3 = formal3;
  ...
  super.init();
}
```

in which case I don't think of the compiler-generated initializer as meaning "make this field like this actual argument expression" but rather "assign this expression to this field to initialize it."

Let's make some concrete examples:

```chapel
class S {
  var x: sync int;
  var y: sync int = 42;
}

var emptySync: sync int;
var fullSync: sync int = 12;
var val = 33;

var S1 = new S();             // x is empty, y is full and 42
var S2 = new S(x=emptySync);  // x blocks on read of emptySync until something else fills it
var S3 = new S(x=fullSync);   // x is full and 12, y is full and 42, fullSync is empty
var S4 = new S(x=val);        // x is full and 33, y is full and 42
var S5 = new S(y=emptySync);  // x is empty, y blocks on read of emptySync until something fills it
var S6 = new S(y=fullSync);   // x is empty, y is full and 12, fullSync is empty
var S7 = new S(y=val);        // x is empty, y is full and 33
var S8 = new S(x=fullSync, y=fullSync);   // x is full and 42, y blocks on read of fullSync until ...
var S9 = new S(x=emptySync, y=emptySync); // each initialization will block (requires 2 fills to complete)
```

**Comment by vasslitvinov** [comment]
@bradcray - this is a great example. The two issues that it raises are:

(a) According to the general form of the default initializer, its x and y formals have a sync type. Right now we can't pass scalars where a sync is expected. So new S(x=val) and similar would not resolve.

(b) What should be the default value for the x and y formals of the default initializer? Whatever you make them, `x` is not going to remain empty when the default initializer is executed (unless it blocks forever).

**Comment by lydia-duncan** [comment]
> (b) What should be the default value for the x and y formals of the default initializer? Whatever you make them, x is not going to remain empty when the default initializer is executed (unless it blocks forever).

Today the default constructor leaves x empty and y full and set to 42.  I would be inclined to continue this behavior for default initializers

**Comment by vasslitvinov** [comment]
We want to allow a slight deviation from Brad's universal skeleton of the default initializer. If the field's type is a sync/single, the corresponding formal's type should be the base type of that. This will allow all cases from Brad's `class S` example except when we want to keep the `x` field empty at the end of the initializer.

To handle that case, we need a kind of a formal that can be either passed an actual argument or be left without an actual. Plus a way in the initializer body to tell which it is. Maybe this?

```chpl
proc S.init(xArg: int = noinit, yArg = 42) {
  if
    isNoinit(xArg)  // option 1
    xArg == noinit  // option 2
  then ; // 'x' stays empty
  else x = xArg;

  y = yArg;
}
```

BTW do we want the default and/or user initializer to be able to say "make this field empty"? In Brad's scheme/example that's not possible. Ex.

```chpl
  if yArg == noinit // or whatever
  then y.readXE();
  else y.writeXF(yArg);
```

It would be cool to allow the isNoinit() or "== noinit" test to be computable at compile time.

**Comment by lydia-duncan** [comment]
That's an interesting idea.  I think my main concern about it is it hangs the support of sync fields in those situations on the implementation of noinit, which had been fairly independent of other initializers support before (and thus has been considered a "last step" that wouldn't prevent us from making the switch to initializers over constructors should the rest of the functionality be done first)

I would like to see the noinit operations occur at compile time.

**Comment by bradcray** [comment]
> We want to allow a slight deviation from Brad's universal skeleton of the default initializer.

In case it wasn't clear in my last response, I wasn't proposing this (at least, not yet).  For now, I'd propose taking the approach of the universal initializer until such time as we have compelling use cases that wanted/needed something different.

**Comment by lydia-duncan** [comment]
We do have a longstanding future that proposes basically what Vass was proposing about the argument for the sync field, see [this future](https://github.com/chapel-lang/chapel/blob/master/test/classes/hannah/coercingIntToSyncIntOnConstructor.future)

**Comment by vasslitvinov** [comment]
Oh I see. If the initializer takes an int and is passed a sync, waiting for the sync to become full occurs before the initializer is invoked. Whereas if the initializer takes a sync, the waiting occurs at the point where the sync field is being initialized. Choose your poison. :)

My motivation was that making the formal be of the base type is simpler than making it be generic then handling the two cases where the actual is the base type vs. the sync type.

**Comment by lydia-duncan** [comment]
With the default initializers progress on syncs in general, I think this issue is capable of being closed.  Let me know if you disagree
