### ISSUE TITLE
LLVM 5.0.0 issues

### ISSUE THREAD

**Issue by dmk42** [chapel-lang/chapel#7246]
This issue tracks the current items to be addressed with LLVM 5 as a Chapel target.

- [x]  LLVM 5 currently only works with `CHPL_LLVM_DEVELOPER` set due to the following problem.
Chapel with LLVM 5 gets an undefined symbol `llvm::Value::dump()` in the link step because the new version of the LLVM file `lib/IR/AsmWriter.cpp` wraps the implementation of that method with the following.
```c
#if !defined(NDEBUG) || defined(LLVM_ENABLE_DUMP)
```
I have not yet found a way to get cmake to pass `LLVM_ENABLE_DUMP` through to the LLVM build.  Currently a debug version of LLVM must be built so that `NDEBUG` will not be defined and `llvm::Value::dump()` will be compiled in.

- [ ]  When `--llvm --fast` is used, Chapel with LLVM 5 fails some fft tests with anomalous numeric results.  This may be due to aggressive optimization.  The tests pass without `--fast`.  The tests that fail with optimization turned on are as follows.
* `release/examples/benchmarks/hpcc/fft`
* `chplvis/benchmarks-hpcc/fft-vdb`
* `performance/compiler/bradc/fft-timecomp` (program times out)
* `studies/hpcc/FFT/fft-testPow4` (program times out)
* `studies/hpcc/FFT/diten/fft`

**Comment by mppf** [comment]
Re. the aggressive optimization, I wonder if these settings are too much:
https://github.com/chapel-lang/chapel/blob/master/compiler/util/clangUtil.cpp#L1204
But for the first fft test, it passes `--ieee-float`. Perhaps we are not properly respecting this flag?

**Comment by mppf** [comment]
- [ ] with commit updating master to use LLVM 5, be sure to update third-party/llvm/README

**Comment by dmk42** [comment]
We have avoided this issue by skipping LLVM 5 and going straight to LLVM 6.  I'm closing this now.
