### ISSUE TITLE
Long shutdown times for gasnet-aries with multi-domain enabled

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#7251]
GASNet 1.30.0 included a gemini/aries update to "Improve robustness of exit
code". It appears that the improved robustness in combination with re-enabling
GASNet's multi-domain feature in #6893 has resulted in significantly higher
exit times.

Currently working around this for now with https://github.com/chapel-lang/chapel/pull/7241

**edit**

based on discussion with the GASNet team below, there wasn't actually a regression in shutdown time between 1.28.2 and 1.30.0, it's just that the final exit now has an `alarm()` watchdog. With that in mind, I'm happy with our current work-around in https://github.com/chapel-lang/chapel/pull/7241.

**Comment by ronawho** [comment]
Copying comments from https://github.com/chapel-lang/chapel/commit/552763d:

>>>>>>This increase in exit times in the presence of multi-domain is not something we would have expected. However, looking over the multi-domain code I have identified a possible cause.
>>>>>>
>>>>>>I hope to investigate this more on Friday.
>>>>>>
>>>>>>It would help if you can confirm that Chapel might call gasnet_exit() from a thread other than the first one. That is a pre-condition for the possible cause I've identified (and something I know we don't test often, if ever). However, if you were to tell me that can never happen then I'll dismiss that theory and look elsewhere.
>>>>>
>>>>>init and exit should be called from the same thread, unless there's an abnormal exit, but the regressions I'm seeing are for clean exits with just a basic hello.chpl
>>>>>
>>>>>Although, we do a gasnet_exit() from each locale after doing a barrier(https://github.com/chapel-lang/chapel/blob/master/runtime/src/comm/gasnet/comm-gasnet.c#L1056-L1058).
>>>>
>>>>>I'm not confident on how gasnet_exit works, but it's my understanding that if you exit on one node, it will try to shutdown the others too, so maybe a non-0 locale is doing the exit first, propagating the exit to other nodes, and the AM handler on locale 0 is doing an exit instead of the main thread? (it's getting late, and I'm not confident in anything I just said, so don't quote me on any of that)
>>>>
>>>>I will see what I can reproduce w/ hello.chpl w/o too many assumptions about the behavior of Chapel. Can you give me an idea of the scale of the run necessary to reproduce? Any special conditions?
>>>>
>>>
>>>I'm running into this with just 4 nodes. I see it 50% of the time on a 28 core broadwell, and every time with a 68 core KNL (we set GASNET_DOMAIN_COUNT to num_physical_cores)
>>
>>
>>I tried hello.chpl last night with up to 15 nodes of Haswell (32 cores) and did not reproduce anything that seemed abnormal. Just now I've tried 15 KNL nodes (68 core) with nothing abnormal.
>>
>>I do normally set GASNET_MAX_SEGSIZE to reduce the startup time, but that is not critical.
>>
>
>are you running with 663c829, or right before that? 663c829 is the workaround for the timeouts, so I would expect it to run just fine.

**Comment by ronawho** [comment]
From @PHHargrove:

@ronawho Yes I am running with the work-around, but the times don't seem to be abnormal.

To be more certain of what I am seeing, I've just tried at ed33c58 (before your work-around) and still don't see anything abnormal on 68-core KNL nodes.

When running "(./hello -nl [N]; echo DONE)" piped to a utility that timestamps the lines of output, I see approximately 2s between "Hello" and "DONE" (the difference between the 2 timestamps):

```
{hargrove@nid02306 chapel}$ for ((n=1;n<16;++n)); do echo "With $n locales:"; ( env GASNET_MAX_SEGSIZE=1G ./hello -nl $n; echo DONE) | timestamp; done
With 1 locales:
    3.304       Hello, world!
    5.144       DONE
With 2 locales:
    4.160       Hello, world!
    6.150       DONE
With 3 locales:
    3.441       Hello, world!
    5.473       DONE
With 4 locales:
    3.300       Hello, world!
    5.352       DONE
With 5 locales:
    3.901       Hello, world!
    5.954       DONE
With 6 locales:
    4.828       Hello, world!
    6.885       DONE
With 7 locales:
   22.817       Hello, world!
   24.911       DONE
With 8 locales:
    4.062       Hello, world!
    6.035       DONE
With 9 locales:
    3.844       Hello, world!
    5.961       DONE
With 10 locales:
    6.439       Hello, world!
    8.456       DONE
With 11 locales:
    6.357       Hello, world!
    8.489       DONE
With 12 locales:
    4.518       Hello, world!
    6.568       DONE
With 13 locales:
    3.772       Hello, world!
    5.853       DONE
With 14 locales:
    3.886       Hello, world!
    6.078       DONE
With 15 locales:
    4.666       Hello, world!
    6.755       DONE
```

**Comment by ronawho** [comment]
I'm not seeing timeouts with 15 nodes, so presumably the scaling factor for the exit time is enough. 4 nodes times out 50% of the time with 28-core broadwell, and almost 100% of the time with 68-core knl:

On a 68-core knl system using slurm:
```
avalon: chapel ((ed33c583fd...)) $ chpl test/release/examples/hello.chpl
avalon: chapel ((ed33c583fd...)) $ ./hello -nl4
Hello, world!
srun: error: nid00011: task 3: Alarm clock
srun: error: nid00009: task 1: Alarm clock
srun: error: nid00010: task 2: Alarm clock
srun: error: nid00008: task 0: Alarm clock
```

```
avalon: chapel ((ed33c583fd...)) $ env|grep -e CHPL_ -e GASNET_
CHPL_COMM=gasnet
CHPL_COMM_SUBSTRATE=aries
```

Is that timestamp utility a script you made that you could share or is it just a tool installed on the system?

**Comment by PHHargrove** [comment]
Here is my timestamp utility:
```
#!/usr/bin/perl
use Time::HiRes qw/time/;
$start=time();
$| = 1;
while (<>) { printf "%9.3f\t$_", (time()-$start); }
```

**Comment by ronawho** [comment]
I also don't see the regressions if I set `export GASNET_MAX_SEGSIZE=1G`

Here's the timestamps I see w/ `GASNET_MAX_SEGSIZE=1G`:
```
avalon: chapel ((ed33c583fd...)) $ for ((n=1;n<5;++n)); do echo "" && echo "With $n locales:"; ( env GASNET_MAX_SEGSIZE=1G ./hello -nl $n; echo DONE) | ./timestamp; done;

With 1 locales:
    2.993	Hello, world!
    7.059	DONE

With 2 locales:
    2.572	Hello, world!
    6.678	DONE

With 3 locales:
    4.911	Hello, world!
    8.901	DONE

With 4 locales:
    2.298	Hello, world!
    6.503	DONE
```

and without it:
```
avalon: chapel ((ed33c583fd...)) $ for ((n=1;n<5;++n)); do echo "" && echo "With $n locales:"; ( ./hello -nl $n; echo DONE) | ./timestamp; done;

With 1 locales:
   15.551	Hello, world!
srun: error: nid00008: task 0: Alarm clock
   22.046	DONE

With 2 locales:
   15.165	Hello, world!
srun: error: nid00009: task 0: Alarm clock
srun: error: nid00010: task 1: Alarm clock
   21.823	DONE

With 3 locales:
   17.420	Hello, world!
srun: error: nid00012: task 1: Alarm clock
srun: error: nid00013: task 2: Alarm clock
srun: error: nid00011: task 0: Alarm clock
   24.062	DONE

With 4 locales:
   17.376	Hello, world!
srun: error: nid00014: task 0: Alarm clock
srun: error: nid00016: task 2: Alarm clock
srun: error: nid00015: task 1: Alarm clock
srun: error: nid00017: task 3: Alarm clock
   24.068	DONE
```

**Comment by PHHargrove** [comment]
Hmm.   There should be no connection between the size of the segment and shutdown that I can think of.  I was setting GASNET_MAX_SEGSIZE only to reduce startup times.  
I will run some more experiments w/o and get back to you.

**Comment by PHHargrove** [comment]
If I don't set GASNET_MAX_SEGSIZE then the Hello-DONE interval with 4 KNL locales grows from about 2s to nearly 5s (transcript below).  As I said in my previous comment, I don't know why segment size and exit timeout would be related other than by the sorts of things than happen *after* entering `_exit()`.  However, this does at least give me a direction to investigate in more detail.

The lack of SIGALRM in my runs means that we are still w/i the default exit timeout.  However, I think the remaining difference between your failures and my successes could be as simple as your nodes having more memory (thus larger default segment size). Do you perhaps have time to try reproducing on NERSC's Cori?


```
{hargrove@nid02307 chapel}$ for ((n=0;n<5;++n)); do (./hello -nl4; echo DONE) 2>&1 | timestamp ; done
   19.155       Hello, world!
   24.058       DONE
   19.080       Hello, world!
   24.031       DONE
   22.681       Hello, world!
   27.657       DONE
   19.222       Hello, world!
   24.198       DONE
   23.050       Hello, world!
   28.028       DONE
```

**Comment by ronawho** [comment]
I have time, but I don't have an account or Cori

**Comment by ronawho** [comment]
FYI both machines I'm running on have 128 GB compute nodes

**Comment by PHHargrove** [comment]
@ronawho Several members of the Chapel team have NERSC accounts, but I see you are not among them.  I will follow-up with you on that via email.

FWIW: I've been testing on Haswell with 128GB and KNL with 96GB DDR4 + 16G MCDRAM (quad,cache mode).

**Comment by PHHargrove** [comment]
@ronawho I want to take a look at this issue from another (additional) direction now.  
When you say this a regression, I am uncertain what/when you are comparing to.  

For instance, I suspect that GASNet 1.28.2 w/o multi-domain was free of the timeouts.  
However, with the merge of GASNet 1.30.0 and (re)enable of multi-domain so close in time, I don't know if you had a "baseline" taken between those two changes.

**Comment by PHHargrove** [comment]
FYI: 10-for-10 on four 128GB Haswell nodes:
```
{hargrove@nid00011 chapel}$ for ((n=0;n<10;++n)); do (./hello -nl4; echo DONE) 2>&1 | timestamp ; done 2>&1 | tee log
   26.312       Hello, world!
   30.026       DONE
   36.042       Hello, world!
   39.370       DONE
   25.499       Hello, world!
   29.404       DONE
   26.099       Hello, world!
   29.412       DONE
   26.570       Hello, world!
   29.874       DONE
   26.235       Hello, world!
   29.580       DONE
   24.167       Hello, world!
   27.485       DONE
   25.457       Hello, world!
   28.911       DONE
   37.298       Hello, world!
   40.656       DONE
   26.156       Hello, world!
   29.451       DONE
```

**Comment by ronawho** [comment]
FWIW we've seen that de-registration from the aries NIC can be quite slow: https://github.com/chapel-lang/chapel/issues/5680#issuecomment-289899882

We believe de-registration happens implicitly at exit, and a larger heap size would certainly increase the amount that has to be de-registered. multi-domain (at least in our ugni comm layer) registers the same memory multiple times, and also increases the amount of de-registration that has to be done.

**Comment by ronawho** [comment]
By regression I really just meant a "test failure" for us.

It's possible the shutdown times are the same between 1.28.2 and 1.30.0, but that the improved exit code is now setting a shorter alarm or something.

1.28.2 with multi-domain did not hit any timeouts, but the alarm was disabled https://github.com/chapel-lang/chapel/blob/e97675f09206/third-party/gasnet/gasnet-src/gemini-conduit/gasnet_core.c#L1032

Here's what i'm seeing 1.28.2 right before the 1.30.0 upgrade (so 1.28.2 with multi-domain):

```
avalon: chapel ((e97675f092...)) $ for ((n=0;n<5;++n)); do (./hello -nl4; echo DONE) 2>&1 | ./timestamp ; done 2>&1
   17.499	Hello, world!
   24.040	DONE
   17.317	Hello, world!
   24.121	DONE
   17.510	Hello, world!
   24.141	DONE
   17.447	Hello, world!
   24.249	DONE
   17.551	Hello, world!
   24.483	DONE
```

And with 1.30.0 with multi-domain re-enabled and `GASNET_EXITTIMEOUT_MIN=5.0`

```
avalon: chapel ((59d40a08a1...)) $ for ((n=0;n<5;++n)); do (./hello -nl4; echo DONE) 2>&1 | ./timestamp ; done 2>&1
   17.680	Hello, world!
   24.646	DONE
   17.727	Hello, world!
   24.622	DONE
   15.223	Hello, world!
   21.837	DONE
   17.699	Hello, world!
   24.299	DONE
```

**Comment by ronawho** [comment]
So for both 1.28.2 and 1.30.0 the shutdown time is around 6-7 seconds for this test. Which I think just means that 1.30.0 is setting a shorter alarm (no longer doing that `alarm(0)`)

**Comment by PHHargrove** [comment]
@ronawho I agree with what you are saying about the deregsitration cost, but we deregister explicitly prior to exit and I have just confirmed via git-blame nothing that has changed in the related code between GASNet 1.26.2 (May 2016) and 1.30.0.
That does contradict my statement that nothing segment-size-dependent happens prior to `_exit()`.  So, I'll replace that with "nothing segment-size-dependent has changed in the past 3 releases".

I am still hoping we can understand what has changed.  
The result may be an endorsement of your original assessment that our improvement to exit handling has increased exit time.

Also, fwiw, we don't register the segment multiple times due to multi-domain since registration is global across all Cdm handles created with the same (ptag,cookie) pair.

**Comment by PHHargrove** [comment]
@ronawho Thanks for the retesting w/ older GASNet.  

I want to look deeper but I think you may be right that part of the "exit-robustification" was to subject more of the exit process to the "watchdog" of an alarm timer.  If that is the case, then (as you say) even if the exit times did not get longer the code became more sensitive to them.

**Comment by ronawho** [comment]
And with 1.30.0 with multi-domain re-enabled and `GASNET_DOMAIN_COUNT=1`:

```
avalon: chapel ((59d40a08a1...)) $ for ((n=0;n<5;++n)); do (./hello -nl4; echo DONE) 2>&1 | ./timestamp ; done 2>&1
   17.458	Hello, world!
   20.727	DONE
   17.387	Hello, world!
   20.655	DONE
   17.449	Hello, world!
   20.685	DONE
   17.325	Hello, world!
   20.636	DONE
   17.398	Hello, world!
   20.644	DONE
```

So ~3 seconds with `GASNET_DOMAIN_COUNT=1` as opposed to ~7 second with `GASNET_DOMAIN_COUNT=68`

**Comment by ronawho** [comment]
@PHHargrove 

Given that we're seeing similar shutdown times between 1.28.2 and 1.30.0, I'm happy with our current "workaround" of just increasing the min exit time if we're using multi-domain. 

Obviously faster shutdown times would be nice, so I'm happy to let you look deeper if you want (and I'm curious why multi-domain would increase exit times), but I don't consider this a blocking item for us so don't feel any need to prioritize this.

**Comment by PHHargrove** [comment]
For the record, and the benefit of anybody reading this later, we are talking about the following change to `gemini-conduit/gasnet_gemini.c` between the 1.28.2 and 1.30.0 releases:
```diff
@@ -1025,11 +1018,14 @@ extern void gasnetc_exit(int exitcode) {

       /* Death of any process by a fatal signal will cause launcher to kill entire job.
        * We don't use INT or TERM since one could be blocked if we are in its handler. */
+      gasnetc_sys_fini();
       raise(SIGALRM); /* Consistent */
       gasneti_killmyprocess(exitcode); /* last chance */
     }
   }
-  alarm(0);
+
+  alarm(2 + gasnetc_shutdown_seconds);
+  gasnetc_sys_fini();

 #if GASNETC_GNI_FIREHOSE
   if (gasnetc_did_firehose_init && !gasnetc_exit_in_signal) {
```

In that change (part of a larger commit) the disarm of the alarm timer was replaced by *restarting* the alarm timer before calling a new `gasnetc_sys_fini()` function that is intended to (among other things) ensure we don't shutdown GNI before it has actually sent the exit coordination messages.

A result (possibly intentional / possibly not) of that change is that the remaining portions of the function `gasnetc_exit()` that previously ran without any watchdog timer are now subject to one.  So, even though the increase in exit time due to `gasnetc_sys_fini()` should be negligible (especially w/o PSHM enabled) the system(s) Elliot is testing on is now getting SIGALRM (though Paul never has on Edison, Cori or Titan).

I am not opposed to the current work-around.  
The only "ill effect" it may have is that **abnormal** exits will be slower by as much as a factor of 4x (due to changing the exit timeout scaling from 1/8s to 1/2s).

Based on the timings seen so far I don't think GASNet-1.30.0 introduced a "regression" in the time spent on exit so much as it exposed the fact that exit times were already running pretty close to the default limits.   However, getting SIGALRM by default is not a desirable behavior.

The fact that the final steps of the shutdown are now covered by a watchdog timer is a generally good thing, if not for the fact that it is leading to SIGALRM in normal execution.  So, I want to think (and perhaps experiment) more before I'd be willing to recommend the following in production.  However, @ronawho, if you could please try the following patch to restore the previous behavior of disarming the watchdog timer before the final exit steps (instead of raising the EXITTIMEOUT env vars).  That should confirm that what I've described above is an accurate understanding of the "proximal cause" of the SIGARLM.
```diff
diff --git a/gemini-conduit/gasnet_core.c b/gemini-conduit/gasnet_core.c
index 187669b..5334421 100644
--- a/gemini-conduit/gasnet_core.c
+++ b/gemini-conduit/gasnet_core.c
@@ -1027,6 +1027,8 @@ extern void gasnetc_exit(int exitcode) {
   alarm(2 + gasnetc_shutdown_seconds);
   gasnetc_sys_fini();

+  alarm(0);
+
 #if GASNETC_GNI_FIREHOSE
   if (gasnetc_did_firehose_init && !gasnetc_exit_in_signal) {
     /* Note we skip firehose_fini() on exit via a signal */
```


FWIW: I do still want to understand what aspect of multi-domain is responsible for such a strong increase in exit time as the domain count is increased, but agree that doing so is not a blocker for a release of Chapel with GASNet-1.30.0.  So, I'll plan to pursue that [in our own Bugzilla](https://upc-bugs.lbl.gov/bugzilla/show_bug.cgi?id=3621).

**Comment by ronawho** [comment]
Confirmed that adding the `alarm(0);` back to gets rid of the SIGALRMs

**Comment by ronawho** [comment]
I've subscribed to your bugzilla issue.

If I get a chance I'll see if I can repro once I get access to cori.

I'm going to close this for now, since I'm happy with the current workaround.

**Comment by PHHargrove** [comment]
> Confirmed that adding the `alarm(0);` back to gets rid of the SIGALRMs

Thanks.  I now have a high confidence that our combined analysis of the cause of the SIGALRM was correct: replacement of the `alarm(0)` with a restarted alarm timer.
