### ISSUE TITLE
Provide eigenvalue / vector solver

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#7260]
Believe it or not, I have a matrix A and I want to know the top n eigenvectors and values.  SciPy provides [this interface](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.linalg.eigvals.html) for doing so.  Please provide something similar in Chapel.  To get you started, here are some [iterative methods](https://en.wikipedia.org/wiki/Eigenvalue_algorithm#Iterative_algorithms) for doing so.

**Comment by bradcray** [comment]
Potentially revealing my atrophied math muscles:  Does this issue differ from #6855?

**Comment by buddha314** [comment]
Not strictly, no.  I thought this issue existed but couldn't find it again.  #6855 is confined to Hermitian matrices, which is a more restricted class.  Use either ticket as you like.

**Comment by daviditen** [comment]
PR #8346 added an eigenvalue/eigenvector function to the [LinearAlgebra](https://chapel-lang.org/docs/master/modules/packages/LinearAlgebra.html#LinearAlgebra.eigvals) module.
