### ISSUE TITLE
error handling: returning errors from writeThis

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#7261]
The `writeThis`, `readWriteThis`, and `readThis` methods can be provided on a type to implement how that type is written or read.

As part of the error handling effort for Chapel 1.16, many I/O functions now are marked `throws`. Some of these might be called by the above methods like `writeThis`.

Currently, if there is an error performing I/O in support of `writeThis`/..., an error code is saved in the relevant channel. Then, subsequent attempts to do I/O on that channel as part of `writeThis` will instead do nothing and preserve the error.

This method of saving an error code in the channel doesn't fit with the `throws` style errors that we'd like to be able to use, however. In particular, one might imagine wanting to have a `writeThis`/... that can throw an arbitrary user error.

At the time of this writing, `channel.writef` or `channel.write` are marked `throws`, but the I/O operator `<~>` is not. Instead, the I/O operator always saves the "error" state in to the channel. For this reason, PR #7245 changes several calls to `write` to calls to `<~>` as a workaround for this issue. Longer term though, I think we want `<~>` to be equivalent to `channel.write`.

We could:
1. make writeThis/... throws, and save the error state in the channel record. This strategy has the advantage of allowing arbitrary exceptions to be thrown by writeThis/..
2. make writeThis/... optionally return an error code
3. expect writeThis/... authors to manage explicitly setting an error code on the channel if an error is encountered

**Comment by BryantLam** [comment]
Just ran into this again (because I keep forgetting). Tried to do the equivalent of `try! f <~> data`.

**Comment by BryantLam** [comment]
>     3. expect writeThis/... authors to manage explicitly setting an error code on the channel if an error is encountered

This is the status quo today and I haven't internalized the implications until now. Using the `<~>` operator seems somewhat problematic in that if the channel ever hits an error, all subsequent writes to it silently fail. (RIght?..) While I've not seen stdout/stderr fail before, I won't rule it out in an e.g., long-running job that suddenly stops writing to stdout/stderr/some log file vs. throwing an exception which has to be handled (but maybe the application is safe even if these writes silently fail?..).

**Comment by mppf** [comment]
> Using the <~> operator seems somewhat problematic in that if the channel ever hits an error, all subsequent writes to it silently fail

It's possible to clear the error. Also I'm not sure I'd call it "silently failing". It's just within a `write` call that the error is hidden, and I/O calls ignored, until the `write` call retrieves the saved error and then `throws`.

In other words, the current status quo puts off handling the error until the outmost `write` call doing a `writeThis` completes; at which point it throws. It does that today with an error code, but in the future it could save an `Error` object. I think it could do it whether or not other I/O calls are ignored while the error is set.

**Comment by mppf** [comment]
@dlongnecke-cray - is this one done now?

**Comment by dlongnecke-cray** [comment]
Resolved by merge of https://github.com/chapel-lang/chapel/pull/14739.
