### ISSUE TITLE
Error in documentation (or unclear) of triu in Linear Algebra

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#7275]
Source code

```
/*
chpl -I/usr/local/Cellar/openblas/0.2.20/include -L/usr/local/Cellar/openblas/0.2.20/lib -lblas tr.chpl
 */
use LinearAlgebra;
var A: [{1..4,1..4}] real = (
  (4, -30, 60, -35),
  (-30, 300, -675, 420),
  (60, -675, 1620, -1050),
  (-35, 420, -1050, 700)
  );
writeln("k=-1\n", triu(A, k=-1));
writeln("k=0\n", triu(A, k=0));
writeln("k=1\n", triu(A, k=1));
```

Produces 

```
k=-1
4.0 -30.0 60.0 -35.0
-30.0 300.0 -675.0 420.0
0.0 -675.0 1620.0 -1050.0
0.0 0.0 -1050.0 700.0
k=0
4.0 -30.0 60.0 -35.0
0.0 300.0 -675.0 420.0
0.0 0.0 1620.0 -1050.0
0.0 0.0 0.0 700.0
k=1
0.0 -30.0 60.0 -35.0
0.0 0.0 -675.0 420.0
0.0 0.0 0.0 -1050.0
0.0 0.0 0.0 0.0
```

Setting `k=1` excludes the diagonal and that makes sense.  However, the [documentation](http://chapel.cray.com/docs/master/modules/packages/LinearAlgebra.html?highlight=upper#LinearAlgebra.triu) seems to suggest it does not.  I could see an argument both ways since the `u` in `triu` implies "upper". Perhaps an example in the docs would be useful.

**Comment by ben-albrecht** [comment]
You're absolutely right. That is an error in the documentation. I will fix this shortly.

Thanks for reporting.
