### ISSUE TITLE
Interpretation / representation of alignment

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#7290]
This issue raises some questions about what range alignment means and how it should be represented.

Intuitively, I've always thought of a range alignment value of `a` for a range of stride `s` as meaning "all indices within the bounds that are equivalent to `a` mod `s`."  In this interpretation, `lo..hi by 2 align 1` and `lo..hi by 2 align 3` would be equivalent since 1 and 3 are equivalent mod 2.  This also suggests that alignments are pointless for unstrided ranges since all integers are equivalent mod 1.

One outcome of this interpretation might be to store all range alignments as a value in `0..#s` rather than as the alignment value provided by the `align` operator (e.g., in the first example above, both alignments of 1 and 3 could be stored as 1).  Another outcome is that alignments would not need to be stored for unstrided ranges which is attractive (unstrided ranges could simply be a low and high bound).

This question raised in this issue is whether anyone would object to this interpretation.

**Comment by bradcray** [comment]
Tagging @npadmana on this issue because we discussed topics related to this recently when he was feeling confused about the behavior of certain cases.

**Comment by vasslitvinov** [comment]
Interpreting all alignments as equivalent mod stride sounds good.

**Comment by vasslitvinov** [comment]
We have agreed to this proposal in a design discussion https://github.com/chapel-lang/chapel/issues/19717#issuecomment-1277035912 and implemented it in https://github.com/chapel-lang/chapel/pull/22225 .
