### ISSUE TITLE
Create Language Server

### ISSUE THREAD

**Issue by marcoscleison** [chapel-lang/chapel#7295]
It is interesting to have a Language Server for Chapel. With a language server, we could use it to make the Chapel based development faster with integrations with IDE.
Editors such as Vim, Neo Vim, Atom and vsCode can communicate with server protocol allowing code navigation,  refactoring, code completion and so on.

My suggests would be:
1) Dump  AST or part of it as JSON, or XML format to stdout in order to feed the language server. 
Or:
2) Provide a LL grammar version in ANTLR format.

As well as I know the grammar in the language specification is LR and not LL (Am I right?, I am not sure). 
With the grammar in LL format allows us to create plugins to IDE like Eclipse and Itellij IDEA.

References:
[Language Server Protocol](http://langserver.org/)
[ANTLR](http://www.antlr.org/)

**Comment by mppf** [comment]
ANTLR seems intriguing to me. I found this tutorial on it: https://tomassetti.me/antlr-mega-tutorial/

**Comment by ben-albrecht** [comment]
A few more resources I am aware of:

- tree parser generator: https://github.com/tree-sitter/tree-sitter
- MS server protocol: https://github.com/microsoft/language-server-protocol

**Comment by mppf** [comment]
> tree parser generator: https://github.com/tree-sitter/tree-sitter

Might be excellent but doesn't have C/C++ support which would limit reuse of a parser in the compiler itself.

**Comment by mppf** [comment]
Looks like tree-sitter creates a C API for the parser at this point, at least. (Maybe I was wrong before).

**Comment by lydia-duncan** [comment]
We have a language server now, see https://chapel-lang.org/docs/latest/tools/chpl-language-server/chpl-language-server.html

**Comment by marcoscleison** [comment]
@lydia-duncan This is a huge step. I will test the functionality as soon as possible.
Thank you very much to put an effort on this!
A shoutout for the entire team!
