### ISSUE TITLE
Compress zeroes out of comm diagnostic counts

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#7296]
When we print out communication counts for a multilocale program, the output typically looks like this:

```
(get = 0, get_nb = 0, put = 0, put_nb = 0, test_nb = 0, wait_nb = 0, try_nb = 0, execute_on = 8, execute_on_fast = 0, execute_on_nb = 6) (get = 101, get_nb = 0, put = 1, put_nb = 0, test_nb = 0, wait_nb = 0, try_nb = 0, execute_on = 4, execute_on_fast = 2, execute_on_nb = 0) (get = 101, get_nb = 0, put = 1, put_nb = 0, test_nb = 0, wait_nb = 0, try_nb = 0, execute_on = 0, execute_on_fast = 2, execute_on_nb = 0) (get = 101, get_nb = 0, put = 1, put_nb = 0, test_nb = 0, wait_nb = 0, try_nb = 0, execute_on = 0, execute_on_fast = 2, execute_on_nb = 0)
```

which makes it hard to compare across two outputs or to find key values of interest.  In this issue, I'm proposing that we drop all 0 values for a more compact and readable output, like:

```
(execute_on = 8, execute_on_nb = 6) (get = 101, put = 1, execute_on = 4, execute_on_fast = 2) (get = 101, put = 1, execute_on_fast = 2) (get = 101, put = 1, execute_on_fast = 2)
```

I think we should also print out something in the event that all values are 0, like:

```
(<no communication>)
```

**Comment by ronawho** [comment]
👍  for this. 

FWIW `git diff --word-diff` can make the diffs a little easier to read for things like this (if you have a shell that supports colors)

**Comment by gbtitus** [comment]
I spazzed my addition of a thumbs-up and it appears in doing so erased the one from @ronawho .

**Comment by mppf** [comment]
My work on making comm-counts tests into perf tests is certainly related to this. See PR #6604.

**Comment by bradcray** [comment]
@mppf: Just wanted to check and make sure you didn't object to the direction here for tests that haven't been converted away from using printing of comm diagnostics?

**Comment by mppf** [comment]
Nope, it's just fine.
