### ISSUE TITLE
Remove explicit -o flags in start_test?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#7362]
Now that compiling testit.chpl results in a binary named `testit` by default, it seems we could/should remove the use of explicit `-o` flags in Chapel testing by default (?).

**Comment by bradcray** [comment]
Tagging @mppf on this since he implemented the behavior in question.  (I thought I'd already seen that `-o`s had been removed, but now think I must've been hallucinating).

**Comment by mppf** [comment]
I don't think so, because it would break start_test for programs with modules with names different from the outer .chpl file.

**Comment by bradcray** [comment]
Oh, good point.  Duh.
