### ISSUE TITLE
Request to apply a GASNet bug fix for aries

### ISSUE THREAD

**Issue by PHHargrove** [chapel-lang/chapel#7436]
After the release of GASNet-1.30.0, and due our new CI testing with Chapel 'master', the GASNet team has discovered (and fixed) a bug in the multi-domain initialization code in aries-conduit.

This issue is to strongly suggest that Chapel apply GASNet's commit [ed2fd98](https://bitbucket.org/berkeleylab/gasnet/commits/ed2fd98eb1840080254efd39a76d4db74a752fd0) (or [raw](https://bitbucket.org/berkeleylab/gasnet/commits/ed2fd98eb/raw)) for inclusion in your 1.16 release.  

Full details are in GASNet's [Bug 3632](https://upc-bugs.lbl.gov/bugzilla/show_bug.cgi?id=3632) - aries-conduit SEGV at startup with multi-domain  
Here is a summary of the problem, quoted from that Bugzilla entry:
>This bug regards a "sometimes" crash at startup in aries-conduit (and probably gemini).
>The crash occurs if a particular stack variable in the multi-domain code is
>aligned on a particular boundary.  So, a given libgasnet with multi-domain
>support either fails every run or succeeds every run.

The "signature" of the problem is a persistent SEGV at startup, attributed to `_gasneti_lifo_pop()` if  backtrace is available.  As noted above, a build impacted by the issue will show it persistently while (most?) other builds will show no problem at all.  

cc: @bonachea

**Comment by ronawho** [comment]
Thanks for the heads up @PHHargrove!  I don't think we've run into this, but I'll apply this today or tomorrow.
