### ISSUE TITLE
Transpose (seems to) fail on DefaultSparseArr

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#7440]
Example source

```
use MatrixMarket,
    LinearAlgebra,
    LayoutCS,
    Time;

var t: Timer;
t.start();
var CCM = mmreadsp(real, 'data/condition_cui.txt');
writeln("CCM.shape ", CCM.shape);
writeln(CCM.type:string);
var CtC = CCM.T;
t.stop();
writeln("elapsed time ", t.elapsed());
```

Results in the error

```
In function 'T':
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:348: error: unresolved call 'transpose(_array(DefaultSparseArr(real(64),2,int(64),DefaultSparseDom(2,int(64),_domain(DefaultRectangularDom(2,int(64),false))))))'
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:348: note:   instantiated from T
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:301: note: candidates are: transpose(D: domain(1)) [199558]
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:306: note:                 transpose(D: domain(2)) [199576]
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:313: note:                 transpose(A: [?Dom] ) [199610]
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:331: note:                 transpose(A: [?Dom] ?eltType) [199668]
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:348: note: unresolved call had id 1851176
make: *** [core] Error 1
```

The array `CCM` is built by the `mmreadsp()` routine, so may be returning the wrong type for `A.T` to handle.  Dunno.

`type` produces `_array(DefaultSparseArr(real(64),2,int(64),DefaultSparseDom(2,int(64),_domain(DefaultRectangularDom(2,int(64),false)))))` 

```
chpl --version
chpl Version 1.16.0 pre-release (6b9e4c825c)
Copyright (c) 2004-2017, Cray Inc.  (See LICENSE file for more details)
```

**Comment by ben-albrecht** [comment]
> The array CCM is built by the mmreadsp() routine, so may be returning the wrong type for A.T to handle.

That's correct - `LinearAlgebra.Sparse` only supports `CSR`, but also not that you'll need to `use LinearAlgebra.Sparse` to expose it's symbols, i.e. CSR-supported transpose, to your code.

**Comment by bradcray** [comment]
> That's correct - LinearAlgebra.Sparse only supports CSR, but also not that you'll need to use LinearAlgebra.Sparse to expose it's symbols, i.e. CSR-supported transpose, to your code.

For the code @buddha314 's trying to write, this suggests filing a feature request against MatrixMarket.chpl permitting it to use CS* layouts, either by default or by requesting it via an argument (I think we could hack a use of CS* into it for the sake of his ability to make progress, but it'd be nice to make it part of the official interface as well).  Tagging @ct-clmsn on this since it involves MatrixMarket again.

**Comment by buddha314** [comment]
Could you be a bit more specific when you get a sec?   Perhaps an example matrix markets -> sparse matrix transpose?  Thanks!

**Comment by buddha314** [comment]
Oh, looks like Brad is suggesting it cannot currently be done.

**Comment by buddha314** [comment]
Hold the phone! So what should I do about getting data into a sparse matrix?

**Comment by bradcray** [comment]
1) File the feature request against MatrixMarket.chpl as suggested above
2) Apply the following patch to your copy of MatrixMarket to work around its lack of CS support for the time being:

```
diff --git a/modules/packages/MatrixMarket.chpl b/modules/packages/MatrixMarket.chpl
index 316647c..ff0a8ee 100644
--- a/modules/packages/MatrixMarket.chpl
+++ b/modules/packages/MatrixMarket.chpl
@@ -363,8 +363,10 @@ class MMReader {
        (nrows, ncols, nnz) = read_matrix_info();
      }
 
+     use LayoutCS;
+
      Dtoret = {1..nrows, 1..ncols};
-     var spDom : sparse subdomain(Dtoret);
+     var spDom : sparse subdomain(Dtoret) dmapped CS();
      var toret : [spDom] eltype;
 
      if finfo.mm_types == MMTypes.Real { assert(eltype == real, "expected real, data in file is not real"); }
```

**Comment by bradcray** [comment]
(Another way to work around the issue would be to read in using MatrixMarket, then slosh the sparse domain/array it reads into a new sparse domain/array that uses CS storage... but that's pretty wasteful as compared to getting it into the format you want from the start).

**Comment by buddha314** [comment]
We should consider re-opening this, because we are back to not being able to us `.T` on a matrix generated by `MatrixMarket` and we don't know if the solution is to add `dmapped CS()` or not.

**Comment by buddha314** [comment]
Just got word this has been fixed in a PR somewhere.  That's great news!  I'll look forward to it.

**Comment by bradcray** [comment]
SInce `.T` can only be applied to `CS`-mapped matrices, it seems that it needs to be part of the solution.  I don't think MatrixMarket is a factor here.  My guess is that non-square sparse matrices have problems in tranpose.  E.g., I"m guessing this test would fail to work:

```chapel
use LinearAlgebra.Sparse;
use LayoutCS;

const D = {1..10, 1..20};
var SD: sparse subdomain(D) dmapped CS();
var A: [SD] real;
SD += (2,3);
SD += (5,2);
writeln(SD);

var B = A.T;

writeln(B);
```
But I don't have cblas, so can't compile it currently.

**Comment by buddha314** [comment]
I'll take your hint and do it right now.

**Comment by buddha314** [comment]
Using the modified `MatrixMarket.chpl`

brad-test.chpl
```
use LinearAlgebra.Sparse;
use LayoutCS;

const D = {1..10, 1..20};
var SD: sparse subdomain(D) dmapped CS();
var A: [SD] real;
SD += (2,3);
SD += (5,2);
writeln(SD);
var B = A.T;
writeln(B);
```
Produces

```
make brad
chpl -M../src -M/Users/buddha/github/buddha314/numsuch/src -I/usr/local/Cellar/zeromq/4.2.2/include -I/usr/local/Cellar/openblas/0.2.20/include -L/usr/local/Cellar/zeromq/4.2.2/lib -lzmq -L/usr/local/Cellar/openblas/0.2.20/lib -lblas --devel -o brad-test brad-test.chpl
./brad-test
{
 (2, 3)
 (5, 2)
}

0.0
0.0

```

With the original `MatrixMarket.chpl`

```
make brad
chpl -M../src -M/Users/buddha/github/buddha314/numsuch/src -I/usr/local/Cellar/zeromq/4.2.2/include -I/usr/local/Cellar/openblas/0.2.20/include -L/usr/local/Cellar/zeromq/4.2.2/lib -lzmq -L/usr/local/Cellar/openblas/0.2.20/lib -lblas --devel -o brad-test brad-test.chpl
./brad-test
{
 (2, 3)
 (5, 2)
}

0.0
0.0
```

Is that useful?  Seems like it worked both ways.  Need me to try another?

**Comment by buddha314** [comment]
Okay, you were right but the example was not.  Add

```
SD += (9,15);
```
to the matrix and get

```
make brad
chpl -M../src -M/Users/buddha/github/buddha314/numsuch/src -I/usr/local/Cellar/zeromq/4.2.2/include -I/usr/local/Cellar/openblas/0.2.20/include -L/usr/local/Cellar/zeromq/4.2.2/lib -lzmq -L/usr/local/Cellar/openblas/0.2.20/lib -lblas --devel -o brad-test brad-test.chpl
./brad-test
{
 (2, 3)
 (5, 2)
 (9, 15)
}

$CHPL_HOME/modules/internal/ChapelDistribution.chpl:583: error: halt reached - Sparse domain/array index out of bounds: (15, 9) (expected to be within {1..10, 1..20})
make: *** [brad] Error 1
```

I think Ben feels he has a solution to this one in a PR.

**Comment by bradcray** [comment]
Ah, yes, you're right — I should've included an index that was outside of the square portion to show the issue.  Thanks!

**Comment by buddha314** [comment]
New Results

With the edits Brad suggested to `MatrixMarket.chpl` and Ben's brand new PR https://github.com/chapel-lang/chapel/commit/4b828c43404a9fb17f6268a42d3048ae92452825 both of these tests WORK for me.  First, just defining the matrix

```
use LinearAlgebra.Sparse;
use LayoutCS;

const D = {1..10, 1..20};
var SD: sparse subdomain(D) dmapped CS();
var A: [SD] real;
SD += (2,3);
SD += (5,2);
SD += (9,15);
writeln(SD);

var B = A.T;

writeln(B);
```

And using a matrix from `mmreadsp()`

```
use MatrixMarket,
    LinearAlgebra.Sparse,
    LayoutCS,
    Time;


var t: Timer;
t.start();
var CCM = mmreadsp(real, 'data/condition_cui.txt');
writeln("CCM.shape ", CCM.shape);
writeln(CCM.type:string);
var CtC = CCM.T;
t.stop();
writeln("elapsed time ", t.elapsed());
```

However, when I revert the changes to `MatrixMarket.chpl` the second still fails with

```
core-test.chpl:13: error: unresolved call '_array(DefaultSparseArr(real(64),2,int(64),DefaultSparseDom(2,int(64),_domain(DefaultRectangularDom(2,int(64),false))))).T'
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:1295: note: candidates are: _array.Twhere [208078]
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:348: note:                 _array.Twhere [199837]
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:375: note:                 _array.Twhere [200023]
core-test.chpl:13: note: unresolved call had id 194608
```

**Comment by ben-albrecht** [comment]
What is the output of `writeln(CCM.type:string);` if you remove the transpose line and recompile?

**Comment by buddha314** [comment]
With the original MatrixMarket.chpl

```
_array(DefaultSparseArr(real(64),2,int(64),DefaultSparseDom(2,int(64),_domain(DefaultRectangularDom(2,int(64),false)))))
elapsed time 2.24322
```

**Comment by ben-albrecht** [comment]
> With the edits Brad suggested to `MatrixMarket.chpl`

What about with the edits that should return a CS array?

**Comment by buddha314** [comment]
This version

```
 23   use IO;
 24       //LayoutCS;
...
368      var spDom : sparse subdomain(Dtoret);
369      //var spDom : sparse subdomain(Dtoret) dmapped CS();
```

creates the error above.  Will invert them and get the writeln in a sec.

**Comment by buddha314** [comment]
Inverted to

```
 23   use IO,
 24       LayoutCS;
...
368      //var spDom : sparse subdomain(Dtoret);
369      var spDom : sparse subdomain(Dtoret) dmapped CS();
```

```
CCM.shape (60563, 569425)
_array(CSArr(real(64),2,int(64),CSDom(2,int(64),_domain(DefaultRectangularDom(2,int(64),false)),true)))
elapsed time 319.83
```

Weird, it takes 319s with this version as opposed to the 2s without LayoutCS

**Comment by ben-albrecht** [comment]
> Weird, it takes 319s with this version as opposed to the 2s without LayoutCS

I might be lost, but I believe the `DefaultSparse` version did not compute the transpose, because `LinearAlgebra.Sparse` does not support `DefaultSparse`, whereas the `LayoutCS` version did..

Are you comparing the matrix-read + transpose time for `LayoutCS` to the matrix-read time for `DefaultSparse`?

**Comment by buddha314** [comment]
I removed `transpose` for both of these to make sure it will compile.  If I have `LayoutCS` in MM.chpl, it takes 319s.  Without, 2s.

But the real concern for me is that `.T` doesn't work without editing the `MatrixMarket.chpl` file (f you loaded the matrix from `mmreadsp()` )

**Comment by ben-albrecht** [comment]
> But the real concern for me is that .T doesn't work without editing the MatrixMarket.chpl file (f you loaded the matrix from mmreadsp() )

Right, `LinearAlgebra.Sparse` only support `LayoutCS`, and `MatrixMarket.chpl` does not yet support `LayoutCS`, so those interoperating will depend on [this feature request](https://github.com/ct-clmsn/MatrixMarket/issues/4) being implemented.


>  If I have LayoutCS in MM.chpl, it takes 319s.

I see... Perhaps there is a more efficient way to read in CSR matrices (`LayoutCS`). That's something that should be considered when adding `LayoutCS` support to `MatrixMarket`.
