### ISSUE TITLE
MatrixMarket Package should support CS* layouts

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#7448]
As discussed in #7440 the MatrixMarket format does not support the new sparse layouts.  The loaded matrices therefore have very little analytic support, including transpose.

@bradcray suggests this sort of work-around for starters. 

```
diff --git a/modules/packages/MatrixMarket.chpl b/modules/packages/MatrixMarket.chpl
index 316647c..ff0a8ee 100644
--- a/modules/packages/MatrixMarket.chpl
+++ b/modules/packages/MatrixMarket.chpl
@@ -363,8 +363,10 @@ class MMReader {
        (nrows, ncols, nnz) = read_matrix_info();
      }
 
+     use LayoutCS;
+
      Dtoret = {1..nrows, 1..ncols};
-     var spDom : sparse subdomain(Dtoret);
+     var spDom : sparse subdomain(Dtoret) dmapped CS();
      var toret : [spDom] eltype;
 
      if finfo.mm_types == MMTypes.Real { assert(eltype == real, "expected real, data in file is not real"); }
```

**Comment by buddha314** [comment]
If possible, it would be nice to get an estimate on this as it is right in my way.  Thanks!

**Comment by bradcray** [comment]
>  it is right in my way

Does this imply that applying and using the workaround patch is not working?

**Comment by buddha314** [comment]
I haven't tried it yet, and I haven't had much experience with the new CS layouts nor the DefaultSparse, so that seems like I will be spending time learning the interfaces of two packages and how they play with each other instead of running the calculations I was hoping to get to today.

I like your new title better!

**Comment by bradcray** [comment]
You should simply be able to apply the patch, add the missing `use` that @ben-albrecht pointed out on issue #7440, recompile and be on your way.  I don't think you'll need to learn anything to get that program compiling.

One of the reasons I'm proposing the workaround is that this package is externally contributed by @ct-clmsn and I can't speak to how quickly he'll be able to make a change to it.

**Comment by ben-albrecht** [comment]
I think this should an issue (or PR if you implement that patch :) ) on https://github.com/ct-clmsn/MatrixMarket rather than chapel.

**Comment by buddha314** [comment]
Oh man, move it again?  Looking more and more like I'm S.O.L. on this one..  I'll try the patch myself, but that means re-doing it every time I pull

**Comment by bradcray** [comment]
I don't think you should have to re-apply the patch on pulls...  It might be a hassle if MatrixMarket changes, but hopefully any conflicting change there would just remove the need for the patch.

**Comment by bradcray** [comment]
> Oh man, move it again?

And my apologies on the duplicated effort... In suggesting to file the issue, I didn't think to check whether issues were enabled on Chris's github repo (didn't even think about his repo at all).

**Comment by bradcray** [comment]
Closing this issue in favor of https://github.com/ct-clmsn/MatrixMarket/issues/4
