### ISSUE TITLE
chpl_memalign() should check for out-of-memory.

### ISSUE THREAD

**Issue by gbtitus** [chapel-lang/chapel#7484]
### Summary of Problem

`chpl_memalign()` and probably a few other Chapel runtime memory allocation functions don't do out-of-memory checking.

### Steps to Reproduce

Run the `users/shetag/fock/fock-3.chpl` test on linux32 in the default configuration with 8mb call stacks.  After about 150 runs it will segfault.  If you rebuild Qthreads with `--enable-debugging --enable-asserts` you can collect a core file and observe that a stack memory pool allocation has failed.  Qthreads doesn't notice this normally (without `--enable-asserts`) and tries to dereference the pointer, causing the segfault. Despite that Qthreads calls the Chapel runtime memory layer for pool memory, the expected error halt in the Chapel allocator for out-of-memory doesn't happen, because the runtime function Qthreads calls to get more memory is `chpl_memalign()` and that was not coded to check for allocation failure.  It should be.

This is the cause of the segfault (which should instead be an out-of-memory halt) described in [CHAPEL-316](https://chapel.atlassian.net/browse/CHAPEL-316).

**Comment by gbtitus** [comment]
@mppf (originator of `chpl_memalign()`) and @ronawho (Qthreads, jemalloc, runtime in general), you might be interested in this.  I've assigned it to myself and am intending to do the work, though, so only looking for commentary and not actual help.

**Comment by gbtitus** [comment]
Yes, it is still available and that would be great!  You can look at the other functions in the chpl_mem layer of the runtime to see what they do for out-of-memory.  (Basically at present it is just reported as an internal error.)

**Comment by bradcray** [comment]
We had a user run afoul of this today, so I'm noting it here to give this a bump and also tagging it as a user issue.
