### ISSUE TITLE
What is single-threading parallel execution with comm-ugni dynamic registration?

### ISSUE THREAD

**Issue by gbtitus** [chapel-lang/chapel#7493]
### Summary of Problem

(Thanks to @benharsh for the original report and the fun discussion that led to this issue!)

`ISx` on 64 nodes of an XC30 runs in 19 seconds with no remote serialization and no dynamic registration. With either remote serialization or dynamic registration, but not both, it runs in 12 seconds. But with both remote serialization and dynamic registration it still runs in 12 seconds; it doesn't speed up any more.  Why not?

Without remote serialization, all the tasks in the program get single-threaded in the domain update on node 0 when they create their local arrays over the same domain. With remote serialization they not only avoid the on-stmt to node 0 to update the single copy of the domain, they also get single-threaded only within their own node, updating the node-local copy of the domain.  That reduces the wait time for the lock needed in the domain update by a factor of 64, improving performance.

Without dynamic registration, all the task-local arrays on every node end up on (architectural) NUMA domain 0, because of the way the Aries network registration localizes the registered heap. Thus half the tasks (cores) on every node are working with poor NUMA affinity for their local references to their own arrays. With dynamic registration all the task-local arrays are also NUMA-local, improving performance.

After a longish discussion we came up with the following experiment. @benharsh put an atomic timer around the lock acquisition spin-wait in the domain code, added up all the time we spent waiting on the lock, and reported it at the end of execution. He ran with without remote serialization, both with and without dynamic registration.  The sum of the wait times across all `64 * numCores` tasks without dynamic registration was 15,000 seconds while the sum of the wait times with dynamic registration was 3.6 seconds.

Our hypothesis is that with dynamic registration, we don't see any additional benefit from remote serialization because the reduction in single-threading due to the latter is offset by single-threading that occurs in the former.  That is, single-threading somewhere in the dynamic registration path forces all the cores on each node out of lockstep with each other, so that when they reach the domain update they're already out of step and don't have to wait nearly as much.  The result is that remote serialization can't save us any additional time.

(An additional, side effect hypothesis is that the on-stmt wasn't actually costing us much in the first place. It was the wait time on the domain update locking that really hurt.  In the wall clock sense, remote serialization divides that wait time by the node count since each node gets its own domain, so that's where the savings occurred.)

This issue exists as a reminder that we need to (1) confirm the first hypothesis by figuring out which part of dynamic registration is single-threading our parallelism, and (2) see if there anything we can do to fix that.

**Comment by gbtitus** [comment]
@benharsh , I assigned you but just as an FYI; I think the next step is definitely mine.  Would you give it a quick read to make sure I got everything right about our discussion?

**Comment by benharsh** [comment]
Looks good, thanks!

**Comment by gbtitus** [comment]
I'm closing this because I think #8625 addresses it adequately.
