### ISSUE TITLE
should Chapel modules provide C errno?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#7499]
`errno` is used in system-facing C proramming, but since `errno` is usually a macro, it doesn't actually work to declare it as an `extern var errno:int` with `--llvm`.

Should the Chapel standard library provide an `errno` definition that does work, either in a new module (e.g. `SysErrno`) or part of an existing one (e.g. `SysBasic`) ?

Note that `errno` should only be expected to be valid right after a call to a C language function that sets it. Since Chapel tasks are multiplexed across pthreads, and errno is pthread-local, there will be strange and unexpected behavior if a task yield occurs between where the errno is set and where it is checked. This is true whether or not `errno` is provided by the Chapel interoperability modules.

See also commit 01b95f0a76b7d15bc2d663bcfb1fd9d78f323901 in PR #7487.

**Comment by bradcray** [comment]
I'm not sure I'm understanding this.  Is it essentially an interoperability question (should we give Chapel modules the ability to inspect C `errno`) or something else?

As I understand it, `errno` is historically pretty problematic in parallel programs since it's essentially global, shared state.  Is there reason to believe it would be particularly helpful in parallel Chapel programs?  Has it become more parallel safe since I formed that impression?

**Comment by mppf** [comment]
It's an interoperability question.

In modern C libraries, `errno` is actually thread-local. (So it's more parallel safe). General C libraries (including system calls, printf, and it turns out ZMQ) use it, so I think it'd be useful as an interopoerability feature.

**Comment by gbtitus** [comment]
This could be difficult to get right.  Taking the various standards (ISO C, POSIX) together, `errno` is a thread-local modifiable lvalue which may be implemented in terms of a macro.  The problematic part of that is the thread-local aspect.  For any tasking layer where a Chapel task can switch threads between when it does something that sets `errno` and when it reads it, this means the `errno` value that is read might not be the one that was set.

The [POSIX errno(3) man page](http://man7.org/linux/man-pages/man3/errno.3.html) says that `errno` "is set by POSIX syscalls and some library functions". With a task-local `errno` and a sufficiently rich module interface to those syscalls and library functions we could have a trustworthy `errno`.  However, that seems like overkill unless creating that interface produces other benefits in addition.

**Comment by mppf** [comment]
@gbtitus - right, but since we don't have preemptive task scheduling, isn't it sufficient to know that no task yield occurs between the call setting `errno` and the call using it?

**Comment by bradcray** [comment]
> but since we don't have preemptive task scheduling

None of our current tasking layers do; can we assume no future ones will?  (i.e., I don't think the Chapel language says much about pre-emption of tasks or not, nor that it should)

**Comment by gbtitus** [comment]
@mppf: Determining that "no task yield occurs between the call setting `errno` and the one using it" will be hard unless we add restrictions.  It should be safe if we say that programmers have to read `errno` immediately after making the call.  (And then of course, authors of modules and libraries and packages that want their users to be able to access meaningful `errno` codes have to make sure they don't do anything that might change it, between doing something that sets it and returning to their caller.)

**Comment by mppf** [comment]
> And then of course, authors of modules and libraries and packages that want their users to be able to access meaningful errno codes have to make sure they don't do anything that might change it, between doing something that sets it and returning to their caller.)

I disagree. We're just talking about interoperability here - so the story is that there's an existing C library that sets errno that someone wants to use from Chapel. If that library gets Chapel-ized, the Chapel module version wouldn't use errno (since it's a C idea rather than a Chapel one).

I think it'd be sufficient to say something like "Errno is only valid immediately after a C extern call".

**Comment by gbtitus** [comment]
@bradcray: No current tasking layer is preemptive.  But a thread-local `errno` would certainly not be safe with a preemptive tasking layer.  So if we want to say with assurance that thread-local `errno` is accurate we have to rule out preemptive switching of tasks on threads in tasking layers. (I don't think this would be harmful or limiting.)

**Comment by gbtitus** [comment]
@mppf: If we're only talking about interoperability here then yes, `errno` will be accurate right after a call to a POSIX syscall or library function that can set it.  (That limitation isn't stated in the issue text.)

**Comment by mppf** [comment]
@gbtitus - that's true whether or not we provide an `errno` as a standard interoperability feature or if users use the interoperability features to get at it themselves (as happened with ZMQ.chpl).

Anyway I'll update the issue text to say something about this limitation.

**Comment by dmk42** [comment]
This exact issue is causing a major headache in C itself and the eventual outcome may be to reduce the number of cases where `errno` is provided.  Here's the situation, which relates pretty closely to what could possibly occur in Chapel.

In C, `errno` is thread local, as was mentioned before.  However, C is in the process of defining tasks, via the C Parallel Language Extensions (CPLEX).  A task may migrate among threads, invalidating `errno`.  The CPLEX group has already ruled out making `errno` meaningful across the spawning or joining of a task.  Even making `errno` valid strictly within a task requires some kind of task-local storage, and some would rather punt and say that `errno` doesn't work inside a task.

It is not yet clear whether there will be any kind of support for `errno` within a C task.  Many in the C community have wanted to deprecate `errno` for years.  We can't do it yet, but support for it is definitely waning.

That situation might inform how much effort Chapel wants to incur to support `errno`.

**Comment by lydia-duncan** [comment]
@mppf - it looks like Greg added errno in #19632, does that mean this can be closed?

**Comment by mppf** [comment]
Yes, and thanks for noticing. Closing.
