### ISSUE TITLE
Ability to disambiguate nested module for --main-module flag

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#7510]
### Summary of Problem
If there are multiple modules with the same name that define a main function,
we should allow the user to specify which module they meant to use. Right now,
providing X.M to disambiguate from Y.M won't resolve to a symbol - likely
because we treat the period as part of the name instead of a CallExpr(".") like
we do with `enum` or `type` accesses.

### Steps to Reproduce

**Source Code:**

```chapel
module X {
  module M {
    proc main() { writeln("X.M"); }
  }
}

module Y {
  module M {
    proc main() { writeln("Y.M"); }
  }
}
```

**Compile command:**
`chpl foo.chpl --main-module X.M`

**Associated Future Test(s):**
[`test/modules/cassella/ambigmodmain.mainModule.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/modules/cassella/ambigmodmain.mainModule.chpl)

### Configuration Information

- Output of `chpl --version`: 1.16.0 (pre-release)

**Comment by lydia-duncan** [comment]
This might be easy, but I am not certain

**Comment by bradcray** [comment]
Another way to "solve" this would be to disallow nested modules from being the main module.

**Comment by noakesmichael** [comment]
This is a repetition of #7511. Closing this one.

**Comment by lydia-duncan** [comment]
I thought they were likely to be linked but separate issues.  Is that not the case?

**Comment by noakesmichael** [comment]
Issue 7511 has three futures for the obvious variations.
These expose two different bugs; one in buildDefaultFunctions
and one in deadCodeElimination.




On Nov 2, 2017, at 1:05 PM, Lydia Duncan <notifications@github.com<mailto:notifications@github.com>> wrote:


I thought they were likely to be linked but separate issues. Is that not the case?
