### ISSUE TITLE
Compiler failure in main module naming conflict

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#7511]
### Summary of Problem
A user discovered that when two inner modules are provided with the same name
and both define a main, if the ambiguous name is specified with the
--main-module flag then the compiler will arbitrarily choose the later module
as the desired module and, in deadCodeElimination, have an issue with cleaning
up the module whose main was not used. Though the bug gets tickled at
deadCodeElimination, the theory is that this is related to resolution of the
main function and potentially a bug in scope resolve's resolution of module
names - ideally, we would like to see an error because M is ambiguous instead
of arbitrarily choosing one or the other.

This relates to #7510 

### Steps to Reproduce

**Source Code:**

```chapel
module X {
  module M {
    proc main() { writeln("X.M"); }
  }
}

module Y {
  module M {
    proc main() { writeln("Y.M"); }
  }
}
```

**Compile command:**
`chpl --main-module M foo.chpl`

**Associated Future Test(s):**
[`test/modules/cassella/ambigmodmain.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/modules/cassella/ambigmodmain.chpl)
[`test/modules/cassella/ambigmodmain.unnested.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/modules/cassella/ambigmodmain.unnested.chpl)
[`test/modules/cassella/ambigmodmain.unnested2.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/modules/cassella/ambigmodmain.unnested2.chpl)

### Configuration Information

- Output of `chpl --version`: 1.16.0 (pre-release)

**Comment by noakesmichael** [comment]
This is just a mess with two different bugs.

1) An early part of the compiler will make an "arbitrary"
choice of the 'M' to use without regard to nesting.

2) Depending on details of the ordering of top level
modules on files and nesting, the compiler may then
get an internal error in dead code elimination.


Problem (1) can be solved by requiring that the "main module"
be a top level module or allowing the --main-module command
to accept a path.  These are equally easy to implement and so
Brad proposed interpreting --main-module as a path.

We've seen variations of (2) before.  I will solve this once we can
pick modules reliably.

proposed

**Comment by lydia-duncan** [comment]
Okay, sounds good to me, just as long as we don't forget about the other part (which your comment should prevent)

**Comment by noakesmichael** [comment]
I’ve already fixed bug 1 and am now working on bug 2



On Nov 2, 2017, at 1:26 PM, Lydia Duncan <notifications@github.com<mailto:notifications@github.com>> wrote:


Okay, sounds good to me, just as long as we don't forget about the other part (which your comment should prevent)

**Comment by noakesmichael** [comment]
PR #7736 resolves this issue
