### ISSUE TITLE
ugni hangs when calling exit(0)

### ISSUE THREAD

**Issue by gbtitus** [chapel-lang/chapel#7521]
### Summary of Problem
(Credit to @benharsh for this issue.)

A simple program like this will hang when compiled with CHPL_COMM=ugni :

```chapel
config const n = 1;

if n == 0 then exit(0);
```

I have tried running this program on both slurm and qsub/aprun XC40s. I can see the program in a "running" state in the queue, but it takes longer than 10 minutes to finish. This leads me to believe that the program is hanging.

I have confirmed that this issue is not present with gn-aries (on either launcher).

Calling with `exit(1)` will cause the program to exit in a timely fashion.

### Steps to Reproduce

Compile the above program and run with `--n=0`.

### Configuration Information

Cray X* system, CHPL_COMM=ugni.

**Comment by gbtitus** [comment]
The solution would be something like what GASNet does, basically set a "terminate now" flag on all the nodes before doing a unilateral `exit(0)`, so that all the other nodes know to terminate also.

**Comment by gbtitus** [comment]
I just tried the given test case on XC systems using the `slurm-srun` and `aprun` launchers, with and without `--n=0`, and it didn't hang in any of the four cases.  I'm not sure what resolved it.  It may have been https://github.com/chapel-lang/chapel/pull/8533.  In any case, closing this.

**Comment by ronawho** [comment]
I still see this with `--n=0` and I don't think #8533 would resolve this. I have an old branch lying around that's newer than that PR -- https://github.com/chapel-lang/chapel/compare/main...ronawho:chapel:ugni-exit-0 though I can't remember if it needed more work (presumably or I would have PR'd it back then.)

**Comment by ronawho** [comment]
I believe this only occurs with `slurm`. `aprun` will kill all processes when any of them exits, but slurm only does that with non-zero exit codes (assuming you throw `--kill-on-bad-exit`, which we do).

The main problem is that when we do an `exit(0)` now, only the calling node (if its node 0) will actually stop running, but the others will continue running and slurm doesn't kill them. gasnet has a pretty extensive and complicated shutdown implementation to try to exit when shutdown is initiated by a single process, but our uncoordinated shutdown in ugni is quite simplistic.

I think we can improve this simple case of `exit(0)` when no other comm is occurring (basically exit from locale 0), but don't think it's worth the time to implement more comprehensive uncoordinated shutdowns.
