### ISSUE TITLE
"Maximal" arrays are not initialized

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#7531]
### Summary of Problem
Arrays like `[0:uint(8)..255:uint(8)] int` are not initialized because of
overflow. Currently range.length is passed in as the size of the array to be
initialized, but range.length overflows for maximal uint arrays so it uses a
size of 0.

I think the correct behavior is to either properly initialize maximal arrays or
to report an error about not supporting maximal arrays, similar to what we do
for iterating over ranges that will overflow.

When this bug is resolved, the test for the .future should be updated with a description and be
made more like the nearMaxmialUintArray test.

Related to https://github.com/chapel-lang/chapel/issues/7530

**Associated Future Test(s):**
[`test/arrays/elliot/maximalUintArray.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/arrays/elliot/maximalUintArray.chpl)

**Comment by bradcray** [comment]
Would a fix be to have `.length` always return `int` rather than `idxTpe`?

**Comment by ronawho** [comment]
Possibly, that was what I was thinking in #7530

>I'm not sure if there's actually anything we can do about this issue over
>having range.length returning uint(64)/int(64) instead of the index type but
>that only masks the problem for some ranges.

**Comment by benharsh** [comment]
This has apparently been passing for quite some time, but the associated future was still relying on ``_defaultOf`` and lacked a .bad file so we never realized. I've de-futurized this test in #22616.
