### ISSUE TITLE
Pool qthread guard pages

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#7533]
Qthreads uses memory pools to avoid concurrent calls to malloc for performance reasons. These pools are used for some internal book keeping structures and for task stacks. While the actual memory for stacks is pooled, guard pages are not.  As a result, there are 4 mprotect() calls per task (2 on allocation, 2 on de-allocation.) This is relatively expensive on normal processors, but on Xeon Phi concurrent mprotect() calls are particularly expensive. I believe this is some combination of the hardware and more likely the OS/software stack.

For more information on this cost see https://github.com/chapel-lang/chapel/pull/2849#issuecomment-155183504 and https://github.com/chapel-lang/chapel/pull/2849#issuecomment-155523708.

Same issue in the qthreads repo: https://github.com/Qthreads/qthreads/issues/45

**Comment by dmk42** [comment]
This issue also affects arm-thunderx (96 cores per locale) and arm-thunderx2 (64 cores per locale) - see #10530 .

On arm-thunderx2, it appears to be more than just a performance problem.  Intermittently, lulesh can hang indefinitely with all but two of its threads in `mprotect()`.  This may indicate a kernel or hardware issue that should be investigated.

**Comment by ronawho** [comment]
We disabled guard pages on thunderx in https://github.com/chapel-lang/chapel/pull/11049 and Xeon Phi is dead. This might still be nice, but incredibly low priority and there's an existing issue against qthreads so I don't see a reason to keep this open.
