### ISSUE TITLE
multi-locale support for TIO (try it online)

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#7569]
As a background task for awhile now, I've been working on enabling multi-locale support for Chapel on the TIO website, hitting and addressing various stumbling blocks.  The current one is that TIO's sandbox doesn't support sockets.  I thought we could work around this by using `--enable-pshm` in GASNet, but it turns out that the udp conduit still uses sockets to bootstrap in that case.  Paul Hargrove tells me that the smp conduit may represent a path forward, but that doesn't work with Chapel out of the box (seems likely to require a new launcher and/or some new runtime code):

```
mbp-bradc (master)$ printchplenv --anonymize
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: clang
CHPL_TARGET_ARCH: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: smp *
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: system *
CHPL_MEM: jemalloc
CHPL_MAKE: make
CHPL_ATOMICS: intrinsics
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none
mbp-bradc (master)$ chpl test/release/examples/hello6-taskpar-dist.chpl 
mbp-bradc (master)$ ./hello6-taskpar-dist -nl 4
Hello, world! (from locale 0 of 4 named brads-workstation)
Hello, world! (from locale 0 of 4 named brads-workstation)
Hello, world! (from locale 0 of 4 named brads-workstation)
Hello, world! (from locale 0 of 4 named brads-workstation)
```

**Comment by ronawho** [comment]
I'm pretty confident that smp doesn't require a launcher. From the [docs](https://github.com/chapel-lang/chapel/blob/master/third-party/gasnet/gasnet-src/smp-conduit/README#L17-L18): 
>smp-conduit jobs can be launched directly in the same manner as normal POSIX executables - ie on the command line, no spawner script required.


I would guess that this fails because we explicitly throw --disable-pshm. Here's a hacky patch that seems to work for me. I can take a stab at a cleaner patch if it works for you too. It will basically let gasnet detect pshm support, and won't set a segment since I don't think segments make sense for pshm. (gasnet complains if you throw `--enable-segment-everything` and `--enable-pshm`)


```diff
diff --git a/third-party/gasnet/Makefile b/third-party/gasnet/Makefile
index 3b2a719f5e..3bdce28efd 100644
--- a/third-party/gasnet/Makefile
+++ b/third-party/gasnet/Makefile
@@ -6,6 +6,8 @@ export CHPL_COMM=gasnet
 CHPL_MAKE_HOST_TARGET = --target
 include $(CHPL_MAKE_HOME)/make/Makefile.base

+# Don't set segment or pshm for smp
+ifneq ($(CHPL_MAKE_COMM_SUBSTRATE),smp)
 CHPL_GASNET_CFG_OPTIONS += --enable-segment-$(CHPL_MAKE_COMM_SEGMENT) --enable-allow-gcc4

 # pshm can only be used with CHPL_GASNET_SEGMENT={fast,large} and the
@@ -18,6 +20,7 @@ CHPL_GASNET_CFG_OPTIONS += --enable-pshm
 else
 CHPL_GASNET_CFG_OPTIONS += --disable-pshm
 endif
+endif

 ifneq ($(CHPL_MAKE_COMM_SEGMENT),everything)
 CHPL_GASNET_CFG_OPTIONS += --disable-aligned-segments
```

You'll also have to set `export GASNET_PSHM_NODES=<numLocales>`. I tried automatically setting that in our runtime code, but we don't parse `--numLocales/-nl` until after we init the comm layer so we might need a launcher just to set `GASNET_PSHM_NODES`

**Comment by ronawho** [comment]
https://github.com/chapel-lang/chapel/compare/master...ronawho:fix-gasnet-smp-support adds the above patch and a simple smp launcher that effectively just sets `GASNET_PSHM_NODES`. It seems to work for me (passes the hellos)

Remaining questions: 
 - is there a clean way to parse the number of locales prior to comm-init so we don't need an smp launcher? (maybe not important)
 - should we default to `CHPL_GASNET_SEGMENT=none` for smp, and should we hide `CHPL_GASNET_SEGMENT` in printchplenv for smp?

**Comment by bradcray** [comment]
Got some release note slides to put off?  :)

> should we hide CHPL_GASNET_SEGMENT in printchplenv for smp?

I'd say yes.  

With respect to your other questions, I have no informed opinion about the value of CHPL_GASNET_SEGMENT and don't object to having a launcher to avoid needing to re-order the bootstrapping code.
