### ISSUE TITLE
Build connector to Apache Jena

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#7595]
Turns out the Cray Graph Engine is compatible with [Apache Jena](https://jena.apache.org/) so a connector to Jena would connect to the CGE.  How convenient is that?

**Comment by buddha314** [comment]
I no longer really need this.  Should we close it?

**Comment by bradcray** [comment]
I think that'd be good.  If someone else finds they want/need it down the road, we can re-open.  Thanks for helping us garbage collect stale issues!
