### ISSUE TITLE
Build errors w/ icc-18 and CHPL_DEVELOPER=1

### ISSUE THREAD

**Issue by PHHargrove** [chapel-lang/chapel#7608]
Since upgrades of three systems (two Cray XC systems and an Linux cluster) from icc-17.x to icc-18.x I can no longer compile Chapel with `CHPL_DEVELOPER=1`.

When I `make -j4` I am hitting the following errors, or similar ones on various files (depending on which instance the parallel make reaches first):
```
bulkget.c(78): error #279: controlling expression is constant
    MAYBE_STACK_ALLOC(struct iovec, num_parts, iov, iov_onstack);
    ^

compilation aborted for bulkget.c (code 2)
```
```
CollapseBlocks.cpp(410): error #279: controlling expression is constant
    INT_ASSERT("Defer statement discovered in CollapseBlocks");
    ^

compilation aborted for CollapseBlocks.cpp (code 2)
```

At least on the XC systems, the following is sufficient to resolve the problem:
```diff
--- make/compiler/Makefile.intel~       2017-10-17 21:26:41.990418470 -0700
+++ make/compiler/Makefile.intel        2017-10-17 21:27:55.952334682 -0700
@@ -102,6 +102,7 @@
 #
 # Warnings squashed for compiler/runtime C/C++ code
 #
+#  279 : controlling expression is constant
 #  304 : requires inherited classes to specify access control (e.g. public)
 #  593 : variable was set but never used
 #  810 : numeric conversion may lose significant bits (e.g., long double->float)
@@ -119,7 +120,7 @@

 # 10121 : something to do with setenv?

-WARN_CXXFLAGS = -Wall -Werror -diag-disable remark -wr304,593,810,869,981,1572,1599
+WARN_CXXFLAGS = -Wall -Werror -diag-disable remark -wr279,304,593,810,869,981,1572,1599
 WARN_CFLAGS = $(WARN_CXXFLAGS)
 WARN_GEN_CFLAGS = $(WARN_CFLAGS)
 SQUASH_WARN_GEN_CFLAGS = -wr111,174,177
```

cc: @bonachea

**Comment by bradcray** [comment]
Hi Paul -- Others will better be able to confirm tomorrow, but my guess is that we're behind you on icc versions we're testing against tomorrow.

**Comment by ronawho** [comment]
Like Brad said, we're only testing with icc 17. Curiously, none of our internal systems even have 18. We're usually pretty bleeding edge internally, so I'm a little surprised your Crays have 18 before ours.

I'll hop onto cori and verify/test. 

Thanks for reporting and for the patch

**Comment by ronawho** [comment]
@PHHargrove and @bonachea should be fixed. Thanks again
