### ISSUE TITLE
Possible timestamp issues on GPFS and Lustre

### ISSUE THREAD

**Issue by PHHargrove** [chapel-lang/chapel#7613]
Sorry this issue is going to be a bit less "solid" than my normal standard.

I seem to have frequent (but not always) failures building Chapel on certain systems.  The failure mode is that one of the third-party packages (usually hwloc or qthreads) wants to rerun aclocal-1.15 despite the effort your Makefiles go through to touch files to prevent that:
```
cd /gpfs/jlse-fs0/users/hargrove/chapel/third-party/qthread/build/linux64-intel-native-flat && make
CDPATH="${ZSH_VERSION+.}:" && cd /gpfs/jlse-fs0/users/hargrove/chapel/third-party/qthread/qthread-src && /bin/sh /gpfs/jlse-fs0/users/hargrove/chapel/third-party/qthread/qthread-src/config/missing aclocal-1.15 -I config
/gpfs/jlse-fs0/users/hargrove/chapel/third-party/qthread/qthread-src/config/missing: line 81: aclocal-1.15: command not found
WARNING: 'aclocal-1.15' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
```

I have observed that I experience this failure only where the build is on GPFS or Lustre.   
I have one system where I can very reliably reproduce the problem on GPFS. 
My best guess is that the steps to touch files is simply running too fast relative to the resolution of timestamps on GPFS and Lustre - but this is only a guess.

Does this sound like something you are already aware of?  

CC: @bonachea

**Comment by PHHargrove** [comment]
Following up on my suspicions, I have determined that the following seems to allow me to reliably build on the one GPFS-based system where I was reliably failing before.  I doubt all 4 sleeps are needed in each Makefile, but have not tried to narrow down what is actually necessary.
```diff
diff --git a/third-party/hwloc/Makefile b/third-party/hwloc/Makefile
index 668a1e5..a8dc4d7 100644
--- a/third-party/hwloc/Makefile
+++ b/third-party/hwloc/Makefile
@@ -61,9 +61,13 @@ hwloc-config: FORCE
 # Qthreads release
 #
        cd $(HWLOC_SUBDIR) && touch -c configure.ac
+       sleep 1
        cd $(HWLOC_SUBDIR) && find . -name "*.m4" | xargs touch
+       sleep 1
        cd $(HWLOC_SUBDIR) && touch -c aclocal.m4
+       sleep 1
        cd $(HWLOC_SUBDIR) && touch configure
+       sleep 1
        cd $(HWLOC_SUBDIR) && find . -name "*.in" | xargs touch
 #
 # For reasons not yet understood, our use of a separate build dir breaks
diff --git a/third-party/qthread/Makefile b/third-party/qthread/Makefile
index 69f0cf9..8169743 100644
--- a/third-party/qthread/Makefile
+++ b/third-party/qthread/Makefile
@@ -112,9 +112,13 @@ qthread-config: FORCE
 # Qthreads release
 #
        cd $(QTHREAD_SUBDIR) && touch -c configure.ac
+       sleep 1
        cd $(QTHREAD_SUBDIR) && find . -name "*.m4" | xargs touch
+       sleep 1
        cd $(QTHREAD_SUBDIR) && touch -c aclocal.m4
+       sleep 1
        cd $(QTHREAD_SUBDIR) && touch configure
+       sleep 1
        cd $(QTHREAD_SUBDIR) && find . -name "*.in" | xargs touch

 #
```

**Comment by dmk42** [comment]
It is possible that this relates to a problem we have seen.  Does make ever give you the message that there was clock skew detected?

**Comment by ronawho** [comment]
@dmk42 I'm pretty confident this isn't a clock skew issue.

@PHHargrove. I just ran into this myself on edison yesterday. I'll start digging into it. 

We store our third-party sources untarred, which when committed and checked out from our git repo means all the original timestamp information is lost. As you know, for gasnet we use your bootstrapping  to avoid rebuilding. For hwloc/qthreads we have tried to emulate the bootstrapping with the `touch` commands you listed above, but we can never seem to get it quite right for all systems.

We had been trying to avoid adding `sleep` to avoid increasing the build times, but maybe that was naive.

**Comment by PHHargrove** [comment]
@dmk42 I looked for clock-skew messages first, suspecting that myself.  However, they do not appear.

@ronawho I have seen this issue on Edison and Cori, but could not reproduce last night when typing up this issue.  If "speed" is a factor, then I suspect that the loads on both the node and the f/s need to be fairly low.

**Comment by ronawho** [comment]
@PHHargrove sorry for the long delay on this one -- testing out a fix now with https://github.com/chapel-lang/chapel/pull/7664. Adding sleeps isn't a very satisfying fix so I also opened https://github.com/chapel-lang/chapel/issues/7665 

I can reproduce this consistently on my GPFS home dir on Edison. I'm going to run a build loop for a while as a sanity check for that PR.

```bash
#!/usr/bin/env bash

cd "${CHPL_HOME}"

for i in `seq 100`; do
  rm -rf third-party/qthread third-party/hwloc
  git co third-party/qthread third-party/hwloc
  make
  if [[ ${?} -ne 0 ]]; then
    break
  fi
done
```

**Comment by ronawho** [comment]
Build loop came back clean, #7664 has been merged. Let me know if you continue to see this
