### ISSUE TITLE
size method does not resolve for type tuples

### ISSUE THREAD

**Issue by nspark** [chapel-lang/chapel#7614]
### Summary of Problem
The Chapel compiler cannot resolve the call to `type <tuple of types>.size`.

### Steps to Reproduce

**Source Code:**

```chapel
proc test(type eltTypes) {
  writeln(eltTypes.size);
}
test((int, string, real));
```

**Compile command:**
`chpl test.chpl`

**Execution command:**
`./test`

**Actual output:**
```
test.chpl:1: In function 'test':
test.chpl:2: error: unresolved call 'type (int(64),string,real(64)).size'
[...]
```

**Expected output:**
`3`

### Configuration Information

- Output of `chpl --version`: 1.16.0 

### Miscellaneous

I know that an alternative form of this example could work:
```chapel
proc test(type eltTypes...) {
  writeln(eltTypes.size);
}
test(int, string, real);
```

However, this pattern does not fit my actual use-case.

**Comment by benharsh** [comment]
This issue is related to #5937, which concerns the general case of invoking param/type methods on a type.
