### ISSUE TITLE
Resolution failure for field with type from other module when nested record is present

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#7616]
### Summary of Problem
The compiler fails to resolve the type of a class field when the following conditions are all true:
- the field's type is an alias defined in another module
- the class contains a nested record

### Steps to Reproduce

**Source Code:**

```chapel
module MyTypes {
  type Foo = real;
}

module MyModule {
  use MyTypes;
  class Bar {
    var thing : Foo;
    record myR {
      var x : int;
    }
  }
}
proc main() { }
```
Fails to resolve the type of field ``thing``.
```
nestedRecordInClass2.chpl:8: error: unable to resolve type
```

**Compile command:**
`chpl foo.chpl`

**Associated Future Test(s):**
[types/records/bharshbarger/nestedRecordInClass2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/types/records/bharshbarger/nestedRecordInClass2.chpl)

### Configuration Information

All configurations, present since 1.7

**Comment by cassella** [comment]
This future was retired by #10459.

**Comment by lydia-duncan** [comment]
I think it would be reasonable to close the issue, but I'll let @benharsh make the call in case there's something I'm missing
