### ISSUE TITLE
Compiler fails to emit error about yield outside of iterator at module scope

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#7617]
### Summary of Problem
The compiler will fail with an internal error for yields outside of an iterator at module scope. While this is certainly an invalid program, we should emit a better error message.

### Steps to Reproduce

**Source Code:**

```chapel
for i in 1..10 do yield i;
```
Output of `chpl foo.chpl`
```
internal error: CHE0564 chpl Version 1.17.0 pre-release (...)
...
```

**Compile command:**
`chpl foo.chpl`

**Associated Future Test(s):**
  [`functions/iterators/bharshbarg/moduleYield.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/functions/iterators/bharshbarg/moduleYield.chpl
          )

### Configuration Information

All configurations, likely present since Mesozoic Era.

**Comment by bradcray** [comment]
Does this deserve the 'easy' tag?

**Comment by benharsh** [comment]
Hard to say. I think it would be relatively easy for someone who knows the compiler front-end, but if we're using 'easy' to attract new developers I don't think it would apply here.
