### ISSUE TITLE
Bessel functions

### ISSUE THREAD

**Issue by SolidTux** [chapel-lang/chapel#7646]
It would be great to have the bessel functions available in the math module.

**Comment by bradcray** [comment]
Seems like this should be fairly easy to add -- a good [c2chapel](http://chapel.cray.com/docs/1.16/tools/c2chapel/c2chapel.html) test?

**Comment by ben-albrecht** [comment]
@bradcray - were you thinking of using c2chapel to wrap [GSL's Bessel functions](https://www.gnu.org/software/gsl/manual/html_node/Bessel-Functions.html)?

**Comment by bradcray** [comment]
That's what I thought we'd need to do at first, but then I started to convince myself that they may simply be in -lmath based on https://www.gnu.org/software/libc/manual/html_node/Special-Functions.html and the man page on my Mac.  Granted, it was early in the morning, though.

**Comment by nimitbhardwaj** [comment]
Hello, may I start contributing in making Bessel function, it would be my first contribution in Chapel, and as per CONTRIBUTING.md, I sent my details of CLA  and Github ID, please provide me some guide if I’m struck.

**Comment by bradcray** [comment]
@nimitbhardwaj : I don't believe anyone currently owns this and we'd be happy to have you work on it if you're able.  Definitely give a shout if you have any questions (here or on IRC or email).  Thanks!

**Comment by nimitbhardwaj** [comment]
OK, thanks, I am working now

**Comment by nimitbhardwaj** [comment]
One more thing, as in previous comment, should I use c2chapel or have to implement them from scratch, as they are already there by GNU, we can use them, but the concern that they are in -lmath, I didn't get it much.

**Comment by ben-albrecht** [comment]
> should I use c2chapel or have to implement them from scratch, as they are already there by GNU, we can use them, but the concern that they are in -lmath, I didn't get it much.

I would use `c2chapel` to wrap the routines in `math.h`, which includes `j0`, since Chapel compiles with `-lmath` by default.

Here's a simple example of what `c2chapel` might generate:

```chpl
extern proc j0(x: real(32)): real(32);
```

An open question: Do we intend to provide all of `-lmath` functionality in [Math.chpl](https://chapel-lang.org/docs/latest/modules/standard/Math.html), or just add the bessel functions requested in this issue?

**Comment by bradcray** [comment]
You've both used `-lmath` in your text, but do you mean `-lm` (and `math.h`)?

> Do we intend to provide all of -lmath functionality in Math.chpl, or just add the bessel functions requested in this issue?

For this issue, let's start with the Bessel functions, but I think a broader review of what we're missing is probably in order as well.

I forgot about the fact that the bessel functions have such commonplace names relative to variable names that users might use for variables.  That may be part of the reason we skipped over them the first time around.  If Python or other libraries suggested names that might be more descriptive, we might consider using them.  Hopefully even names like `j0` won't cause problems if we've got our scoping rules correct, though.

**Comment by ben-albrecht** [comment]
> You've both used -lmath in your text, but do you mean -lm (and math.h)?

Whoops . Corrected my comment above.

> If Python or other libraries suggested names that might be more descriptive, we might consider using them

Python uses the same names. It appears this naming schemes is fairly standardized, and it would be unfortunate to steer too far away from it. Some languages use a `bessel` prefix - that seems like a good option.

**Comment by bradcray** [comment]
OK, I think if C and Python both use those names, we should too.  If it breaks existing code (I've got to think we have code that uses those variable names), that'll be worth understanding better.  Again, my hope is that our scoping rules will be such that it doesn't.  If it does, we could consider pushing them into a non-auto-`use`d `Bessel` module or sub-module.

**Comment by nimitbhardwaj** [comment]
Oks, got it and make the PR correct
