### ISSUE TITLE
module and file scope 'defer'

### ISSUE THREAD

**Issue by psahabu** [chapel-lang/chapel#7653]
Currently, if a user attempts to use `defer` at the scope of a file or module, the following error is produced:

```
scope-defer.chpl:2: error: defer can only be used within a function
```

The reasoning behind this error is that `defer` does not have clear module scope semantics given its existing function scope semantics. There are two reasonable interpretations:

1) Module scope code falls under module initialization, which is a function. Hence `defer` could run at the exit of initialization rather than at the module's deinitialization.

2) Module scope variables are not considered local to the initialization scope, persisting until the module's deinitialization. Hence it could be sensible for `defer` to persist similarly.

Given that module deinitialization and `defer` were developed concurrently, it was more expedient to emit the error. Further discussion is needed before moving forward with either set of semantics.

**Comment by psahabu** [comment]
@bradcray @mppf: Does this seem like a fair summary of the discussion?

**Comment by bradcray** [comment]
Is this not a repeat of #7589?

**Comment by psahabu** [comment]
@bradcray Ah my bad, I missed that you had filed that one.
