### ISSUE TITLE
Should we allow nil or c_nil to be passed to c_string?

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#7693]
The following code will fail to compile due to unresolved calls to ``nullStringChecker``:
```chpl
extern proc nullStringChecker(x : c_string) : bool;

// Both lines fail to compile
nullStringChecker(nil);
nullStringChecker(c_nil);
```
If a user encountered this, they might then try to declare a variable with ``c_string`` type and leave it uninitialized. However, ``c_string`` is default-initialized with ``c""``:
```chpl
var x : c_string;
writeln(nullStringChecker(x)); // false, but one might expect 'true'
```
Yet we can declare a ``c_string_copy``, which will be initialized to ``_nullString``:
```chpl
var y : c_string_copy;
writeln(nullStringChecker(y)); // true
```

Should we allow ``nil`` and/or ``c_nil`` to coerce to ``c_string``?

**Comment by mppf** [comment]
See also Should we deprecate c_string? #14215

**Comment by benharsh** [comment]
We are currently in the process of deprecating ``c_string`` in favor of ``c_ptrConst(c_uchar)``, so this issue is no longer relevant.
