### ISSUE TITLE
Implement isEmpty() on domains

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#7721]
### Summary of Problem
We already support ``isEmpty()`` on ranges and arrays, so it seems like we ought to implement ``isEmpty()`` on domains as well.
```chpl
var D : domain(3);
writeln(D.isEmpty()); // true
```

**Associated Future Test(s):**
 [`test/domains/claridge/DomainIsEmpty.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/domains/claridge/DomainIsEmpty.chpl
          )

**Comment by RajatGarg97** [comment]
Hi,
May I resolve this issue @benharsh ?

**Comment by benharsh** [comment]
Absolutely! Make sure you read the [contributing doc](https://github.com/chapel-lang/chapel/blob/master/.github/CONTRIBUTING.md).

You can assign the PR to me once it's opened and I can review + test it.

**Comment by nimitbhardwaj** [comment]
I made the PR for the issue please have a check if I am correct
