### ISSUE TITLE
Modifying an array's domain and iterating simultaneously

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#7727]
### Summary of Problem
Informally we have said that modifying an array's domain while iterating over the array is undefined behavior. This leads to surprising behavior and/or surprising error messages. Similar to #7720, can we generate a better error message for this pattern? Can we at least state this clearly in the language spec?

**Associated Future Test(s):**
[`test/domains/diten/domainReassignNoAlias.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/domains/diten/domainReassignNoAlias.chpl
          )

**Comment by bradcray** [comment]
I'd be inclined to just merge these two issues.  They seem sufficiently related to me.
