### ISSUE TITLE
Calling clear() on associative domain does not reset associative array values

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#7728]
### Summary of Problem
Calling ``clear()`` on an associative domain does not reset the corresponding values in related associative arrays to their default value. This is surprising as ``remove(idx)`` will reset the value.

**Associated Future Test(s):**
[`test/domains/sungeun/assoc/clear.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/domains/sungeun/assoc/clear.chpl
          )

**Comment by bradcray** [comment]
This seems related to my recently merged PR #7555 and seems as though it may be low-hanging fruit?

**Comment by daviditen** [comment]
Fixed by clearing array elements as indices are added to the domain in PR #7828.
