### ISSUE TITLE
Sporadic failures with gasnet udp segment everything

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#7737]
Originally from https://chapel.atlassian.net/browse/CHAPEL-154 (internal)

For our udp-everything testing, we often seen nightly failures with one of the following error messages:

```
*** FATAL ERROR(Node 1): recursive failure in AMUDP_SPMDShutdown
```

```
*** FATAL ERROR(Node 1): slave got an unknown command on coord socket: ~
```

```
*** GASNET ERROR(Node 1): got exn while reading exit code: connection closed on recv() in recvAll() (45:Operation not supported)
```

This is for tests that use 2 or more locales and `halt()` on a non-0 locale.  Here's the simplest reproducer we have:

```chpl
extern proc chpl_comm_exit(s: int, a: int);
on Locales[1] {         // works fine for Locales[0]
  chpl_comm_exit(0, 0); // thin wrapper over gasnet_exit()
}
```

Here's the little bash script I'm using to repro to compile and run the above example a bunch of times (it fails 1/100 times for me): 

```bash
#!/usr/bin/env bash

rm -f gn gn_real
chpl gn.chpl

NUM_TRIALS=${NUM_TRIALS:-1000}

for i in `seq ${NUM_TRIALS}`; do
  output=$(./gn -nl2 2>&1)
  if [ "${output}" != "" ]; then
    echo "Trial ${i} failed:"
    echo "${output}"
    exit
  fi
done

echo "No failures after ${NUM_TRIALS} trials!"
rm -f gn gn_real
```

Note that it sporadically fails for udp with segment everything, but not with segment large/fast. I think that's just because we build large/fast with pshm support. If I build segment large/fast with `--disable-pshm`, then I see the same errors. I have not been able to reproduce this with the mpi, ofi, or ibv conduits though.

Some env that might be relevant:
```sh
printenv | grep -E 'CHPL|GAS|QT'
GASNET_ROUTE_OUTPUT=0
CHPL_GASNET_SEGMENT=everything
CHPL_COMM=gasnet
CHPL_QTHREAD_ENABLE_OVERSUBSCRIPTION=1
GASNET_SPAWNFN=L
```

**Comment by ronawho** [comment]
@PHHargrove and/or @bonachea I'm wondering if you guys have any insight here. 

Specifically, is it ok to just call `gasnet_exit()` on a single node and expect it to shut things down without error messages like we're seeing?

For a normal no-error shutdown, we do a barrier and then `gasnet_exit()` on all nodes while no communication is happening. Here we're doing a `gasnet_exit()` on node 1 inside an AM that node 0 initiated.

We don't care a lot about this from a user-perspective since this only occurs for abnormal exits, but it does cause a fair amount of noise in our nightly testing

**Comment by PHHargrove** [comment]
@ronawho We do support `gasnet_exit()` called by a single node and make a "best effort" to ensure that non-collective exits of this sort will not leave behind any "orphan" processes.  Where necessary, we've made the choice to favor a reliable shutdown of the parallel job over "cleanliness" of the output.

That is just a statement of our design philosophy for exit-handling.  
I suspect @bonachea may be able to share insight into the specific messages you report seeing.  

FWIW: those messages are definitely specific to udp-conduit (having been issued by the amudp layer).

**Comment by bradcray** [comment]
Got another one of these in testing last night:

```
[Executing diff extern_class_nl_extern_proc.good extern_class_nl_extern_proc.exec.out.tmp]
Binary files extern_class_nl_extern_proc.good and extern_class_nl_extern_proc.exec.out.tmp differ
[Executing binary diff extern_class_nl_extern_proc.good extern_class_nl_extern_proc.exec.out.tmp]
2a3
> *** FATAL ERROR(Node 0): slave got an unknown command on coord socket: ~
[Error (possible JIRA 154) matching program output for extern/sungeun/classes/extern_class_nl_extern_proc]
```

**Comment by ronawho** [comment]
We're not seeing this much since upgrading to GASNet-EX, and I can no longer reproduce with the simple case in the issue description. We've only seen failures for test/multilocale/local/diten/test_local2.chpl, which has a nested on-stmt:

https://github.com/chapel-lang/chapel/blob/0970418666a740befb74d1c81a0d244c242c0af0/test/multilocale/local/diten/test_local2.chpl#L2-L15

We always get our expected error message for this test, we just occasional get extra messages from gasnet. I'm just going to add a prediff for this test to filter these out, and I don't think this will cause anymore noise in nightly testing -- https://github.com/chapel-lang/chapel/pull/12937

**Comment by bmcdonald3** [comment]
This popped up again on 12/21/2022. Should we reopen?

**Comment by ronawho** [comment]
No, just add a prediff for the failing test.
