### ISSUE TITLE
sub-pass timing

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#7743]
We'd like to collect timing information inside passes. Timing information per-pass is already available with the `--print-passes` command line option. However it's useful for profiling / diagnosing issues purposes to have more fine-grained timing.

This issue is proposing that we:
 1. Collect timing information for certain key parts of passes. Interesting examples:
     * executing another process
     * running LLVM optimizations
 2. Include the sub-pass timing in the --print-passes report (possibly when another flag is provided)

**Comment by mppf** [comment]
I briefly looked at this enough to notice that we have a Timer and also a PhaseTracker already in the compiler. The way I'd like to propose we proceed is that the PhaseTracker add the ability to accumulate sub-pass timings, keyed of a string. For example, if we are to treat PhaseTracker as a global variable (there is only 1 of them but it's not currently a global), we could add these functions:
```
void startSubpass(const char* subPass);
void stopSubpass(const char* subPass);
```

I think it's likely that there's a more object-oriented design that would also be reasonable.

The idea would be to accumulate any time spent in a subpass with a given name within each pass. (So if we run "LLVM Optimizations" twice, say, the resulting time would be the sum of these).

**Comment by mppf** [comment]
@dataPulverizer - this issue is to discuss the design of sub-pass timing tracking.

**Comment by dataPulverizer** [comment]
Okay, I have had some time to review the code. Here is a quick outline suggestion. I am assuming that you want start/stopSubPass to be callable from any function in `clangUtil.cpp`.

We could build a SubPass class that represents each sub pass `const char*` string:

```
class SubPass{
  public:
    int numPass;
    Timer time;
};
```

Then a SubPassList class:

```
class SubPassList{
  SubPassList();
  std::unordered_map<const char*, SubPass> subPasses;
};

static SubPassList GlobalSubPassList = new SubPassList();
```

Functions getSubPasses, and start and stops
```
SubPass getSubPass(const char* name){
  //... check if name exists in GlobalSubPassList and create it if it doesn't
  return subPasses[name];
}
/* These functions need to be able to be called from anywhere in the compiler before the class is instantiated */
void startSubPass(const char* name){
  SubPass sp = getSupPass(name);
  sp.numPass++;
  sp.Timer.Start();
}
void stopSubPass(const char* name){
  SubPass sp = getSupPass(name);
  sp.Timer.Stop();
}
```

**Comment by mppf** [comment]
@dataPulverizer - can you add a little bit to your sketch? I can think of two things that I'd like the sub-pass timing to handle:
 1. Sub-passes that are in different Passes of the compiler (such as resolution vs codegen) should have different Sub-pass lists. That way, we'll be able to make standard subpasses for things like "system commands". To do this, you'd include SubPassList or something like it somewhere in the existing PhaseTracker.
 2. I'd really like to be able to create arbitrarily nested Sub-passes. This doesn't come up that much in clangUtil.cpp but it does in other places in the compiler. For example, during function resolution, I'd like to time both evaluateWhereClause and resolveFunction. But these are mutually recursive. So, can you think of a way to allow that, where each subpass timing construct can actually report two numbers: a) the total time spent in any subpass between start/end for that particular subpass; b) the time spent between start/end for that particular subpass that isn't accounted for in another subpass  (or sub-sub-pass, if you will).

Beyound that, I think we should view this as extending PhaseTracker, and the global startSubPass/stopSubPass functions should be easy to swap out for methods on PhaseTracker if we decide to do that.

**Comment by mppf** [comment]
I wrote up the resolution case I'm interested in timing in issue #7750 - I refer to it here mainly for a concrete case that would use nesting in sub-passes.

**Comment by dataPulverizer** [comment]
Okay, some points I need clarified:

1. Currently the passes are being processed in **runpasses.cpp** which uses the `RUN` macro and creates a list `sPassList` that is subsequently processed by `runPass` and `runPasses`. I need clarification on how you envisage the `subPasses` to fit into this process structure.

2. On your second point regarding nested sub-passes you mention two mutually recursive functions `evaluateWhereClause` and `resolveFunction` I cannot find `resolveFunction` anywhere in the code and `evaluateWhereClause` implemented in `generics.cpp` does not call resolve `function`. Can I assume that you mean functions like this:

```
void topFunction()
{
  //... some code
  subFunction1();
}

void subFunction1()
{
  //..... some code
  if(someCondition)
    return;
  subFunction2();
}

void subFunction2()
{
  //... some code
  if(someCondition)
    return;
  subFunction1();
}
```

In this case the output would look something like:
```
Pass       Name                                              Time
----       -------                                  ...      -------
  4     topFunction                              ...           2
  5     topFunction:subFunction1       ...         0.5
  7     topFunction: subFunction2      ...         0.7
```

**Comment by mppf** [comment]
> Okay, some points I need clarified:
> 
> 1. Currently the passes are being processed in **runpasses.cpp** which uses the `RUN` macro and creates a list `sPassList` that is subsequently processed by `runPass` and `runPasses`. I need clarification on how you envisage the `subPasses` to fit into this process structure.

I don't think sPassList is important here. See for example https://github.com/chapel-lang/chapel/blob/master/compiler/main/runpasses.cpp#L195 which passes a PhaseTracker to run the pass and calls StartPhase on it. I'm just talking about extending the timing functionality that already exists in PhaseTracker. `sPassList` and `runPass` are actually running passes (and we're not talking about changing how that works, other than possibly passing the PhaseTracker along here https://github.com/chapel-lang/chapel/blob/master/compiler/main/runpasses.cpp#L207

> 2. On your second point regarding nested sub-passes you mention two mutually recursive functions `evaluateWhereClause` and `resolveFunction` I cannot find `resolveFunction` anywhere in the code and `evaluateWhereClause` implemented in `generics.cpp` does not call resolve `function`.

First, the function I was talking about is `resolveFns`, not `resolveFunction`.

They really are mutually recursive, but not in a simple manner. But let's not let function resolution distract us from improving timing capabilities.

In any case, it is true that one of them always runs first (and no I don't remember which it is).

Regarding the output, I've personally been imagining:
 1) That the sub-pass timing would integrate with the existing `--print-passes` and fit in with its first section of output at least.
 2) That the sub-pass timing would measure time in each sub-pass spent only in that sub-pass and also time spent in that pass plus nested sub-passes. I believe this is a relatively normal idea for profilers.

For example (and please don't ready anything into my poor manual spacing):

```
# assuming we added a new flag to trigger the behavior:
chpl hello.chpl  --print-subpasses
                            init :   0.030 seconds
                           parse :   0.198 seconds
[...]
                 checkNormalized :   0.020 seconds
           buildDefaultFunctions :   0.267 seconds
             createTaskFunctions :   0.036 seconds
                         resolve :   2.956 seconds
                                    isApplicable:  ### s (### s self)
                                    resolveFns: ### s (### s self)
                                    disambiguateByMatch: ### s (### s self)
                  resolveIntents :   0.008 seconds
                   checkResolved :   0.009 seconds
[...]
               optimizeOnClauses :   0.018 seconds
                    addInitCalls :   0.005 seconds
               insertLineNumbers :   0.022 seconds
                     denormalize :   0.061 seconds
                         codegen :   0.116 seconds
                                         llvm opts: ### s (### self)
                      makeBinary :   1.122 seconds
                                         llvm opts 1: ### s (### self)
                                         llvm opts 2: ### s (### self)
                                         mysystem: ### s (### self)
                   driverCleanup :   0.000 seconds
                      total time :   7.752 seconds
```

(If/when it's time to add a new flag I can quickly help you do that).

**Comment by dataPulverizer** [comment]
I'll need more time to study the PhaseTracker

**Comment by mppf** [comment]
I'm closing this issue since we are working on migrating resolution to an incremental framework as part of the dyno effort and this issue doesn't really make sense anymore as worded. We do have some timing facilities in dyno already.
