### ISSUE TITLE
Spinwaiting in I/O lock can significantly degrade performance under qthreads

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#7748]
By default our I/O is parallel-safe and to implement the parallel-safety we use a lock. qio_lock ends up using chpl_sync_lock, which under qthreads spinwaits, which can lead to significant performance degradation for concurrent I/O on a busy machine.

The following code runs in ~.1 second on chapcs if the machine is empty, but if you run 2 concurrent instances of this test (or even just other non-chapel applications) it can take ~40 seconds or more:

```chpl
use Barriers;

config const numTasks = here.maxTaskPar;
var barrier = new Barrier(numTasks);

config const writesPerTask = 100;

coforall t in 1..numTasks {
  barrier.barrier();
  for i in 1..writesPerTask do writeln(t, ": " , i);
}
```

What ends up happening is that all tasks are spinning on an atomic, but only about half of the pthreads hosting the tasks are running for each program. So we're spinnwaiting but most of the tasks aren't making any progress, and the 1 that can will have to wait for its pthread to get rescheduled. On chapcs we essentially end up with 96 pthreads (48 per process) spinwaiting and contending with each other preventing the 1 thread that can actually grab the lock from making progress.

In order to solve this we should really do some sort of adaptive-locking, where we spin for a little while and then go to sleep.

Here's the bash script i'm using to reproduce this:

```bash
#!/usr/bin/env bash

NUM_TRIALS=${NUM_TRIALS:-20}
START_INSTANCE_TWO_TRIAL=${START_INSTANCE_TWO_TRIAL:-5}
WRITES_PER_TASK=${WRITES_PER_TASK:-100}

PRG_NAME=${PRG_NAME:-io-slowdown}
EXEC_CMD=${EXEC_CMD:-"./${PRG_NAME} --writesPerTask ${WRITES_PER_TASK}"}
EXEC_CMD2=${EXEC_CMD2:-${EXEC_CMD}}

# ensure spawned instances get killed if we ctrl-c
trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM

# Compile
echo "Compiling program"
rm -f ${PRG_NAME}
chpl ${PRG_NAME}.chpl -o ${PRG_NAME} || exit
echo "Compiled program"

# For qthreads use all cores and disable internal spinwaiting/pinning
if [ `$CHPL_HOME/util/chplenv/chpl_tasks.py` == "qthreads" ]; then
  echo "Using qthreads, setting some env vars"
  # ensure we're using all "cores" to increase contention
  export CHPL_RT_NUM_THREADS_PER_LOCALE=${CHPL_RT_NUM_THREADS_PER_LOCALE:-MAX_LOGICAL}

  # Note that this has nothing to do with qthreads pinning or spinwating.
  export QT_AFFINITY=${QT_AFFINITY:-no}
  export QT_SPINCOUNT=${QT_SPINCOUNT:-300}
fi


# print clock time, potentially with a prefix to differentiate instances
myTime () {
  cmd=${1}
  print_prefix=${2}
  realTime=`/usr/bin/time -f%e ${cmd} 2>&1 >/dev/null`
  echo "${print_prefix}${realTime}"
}

# main stuff, run concurrent instances of program
printed=false
echo "Starting first instance of '${EXEC_CMD}'"
for i in `seq ${NUM_TRIALS}`; do
  myTime "${EXEC_CMD}" "" &
  if [ ${i} -ge ${START_INSTANCE_TWO_TRIAL} ]; then
    if [ ${printed} = false ]; then
      echo "Starting second concurrent instance of '${EXEC_CMD2}'"
      printed=true
    fi
    myTime "${EXEC_CMD2}" "        " &
  fi
  wait
done
```

Sample output:

```
Starting first instance of './io-slowdown --writesPerTask 100'
0.22
0.12
0.07
0.16
Starting second concurrent instance of './io-slowdown --writesPerTask 100'
36.77
        36.77
40.27
        40.27
0.29
        0.32
```

We can also change out the second instance with a non-chpl program and see similar results. A lot of concurrent compiles will also slow it down, so will the below omp application that just spin-waits on all cores for 20s:

```c
#include <omp.h>

int main() {
  double start_time = omp_get_wtime();
  #pragma omp parallel for
  for (int i=0; i<omp_get_num_threads(); i++) {
    while(omp_get_wtime() - start_time < 20.0) { }
  }
}
```

**Comment by mppf** [comment]
@ronawho - thanks for narrowing down the issue! Great work. Do you think you might try to change the implementation to use a better "lock" ?

**Comment by mppf** [comment]
@ronawho - just wondering if you still plan to fix this issue. I think it would help if you or somebody could point out what the I/O code should be using as its "lock". Thanks.

**Comment by ronawho** [comment]
Plan is a strong word. It's on my list, but it's not something I plan to look at in the near-term since we don't have any I/O heavy benchmarks that really depend on this (and the system has to be pretty busy with other applications for this to have a big impact)

What we want is an adaptive hybrid spin-lock, that does a few spinwaits, then chpl_task_yield, and then puts the task to sleep.

sync vars are supposed to be the way to put a task to sleep, and that's what the I/O code is currently using, but unfortunately it's not working as it's supposed to because our chpl_sync_ wrappers for qthreads end up doing a spinwait while trying to acquire the sync var lock, before actually waiting on a native qthreads sync var, which will remove a task from the scheduler.

**Comment by ronawho** [comment]
And to put more meat on that response: 

Spinwaiting (our current scheme) is slow under heavy contention, but sync vars are slow under low contention, so you want some sort of lock that uses spinwaiting initially, only switching to a sync var to put the task to sleep after some amount of time. This gets a little tricky, because if possible you want to avoid touching the sync var at all under the low-contention case. Here's some simple timings for pure syncvar vs pure spinwait (using the below reproducer):

| contention | spinwait | sync var | no lock  |
| ---------- | -------- | -------- | -------- |
| 1          |     .015 |      .15 |    .0015 |
| 2          |     .03  |      .25 |          |
| 4          |     .25  |      .25 |          |
| 12         |     .45  |      .20 |          |
| NUM_CORES  |     .82  |      .20 |          |

contention is just `CHPL_RT_NUM_THREADS_PER_LOCALE`, which will influence `here.maxTaskPar`, which is used to throttle the amount of parallelism using in the forall. 

Short summary is for the serial case spin-waiting is 10x slower than no-lock, and the sync var is 10x slower than spinning. Under high contention though the sync var ends up being 4x faster. The test below is pretty dumb, but I think it shows the tradeoff

So what we're looking for is a hybrid lock that will spin initially, and then transition to a sync var. And the adaptive part is that we don't want to hardcode the number of spins, because the ideal number of spins depends on how long the critical section takes.


```bash
#!/usr/bin/env bash

CONTENTION_LEVELS=(1 2 4 12 MAX_PHYSICAL)
LOCK_STYLES=(SyncAuxLock QthreadNativeLock)
NUM_TRAILS=${NUM_TRIALS:-3}

for lock in ${LOCK_STYLES[@]}; do
  chpl locks.chpl --fast --static -ssyncType=${lock} -o ${lock} || exit
  for contention in ${CONTENTION_LEVELS[@]}; do
    export CHPL_RT_NUM_THREADS_PER_LOCALE=${contention}
    for trial in `seq ${NUM_TRAILS}`; do
      "./${lock}"
    done
    echo ""
  done
    echo ""
    echo ""
done
```

```chpl
use SyncVarRuntimeSupport;
/* Currently implemented as a atomic spin-lock */
record SyncAuxLock {
  var syncAux: chpl_sync_aux_t;

  proc init() { chpl_sync_initAux(syncAux); }
  proc deinit() { chpl_sync_destroyAux(syncAux); }

  proc lock() { chpl_sync_lock(syncAux); }
  proc unlock() { chpl_sync_unlock(syncAux); }
}

use AlignedTSupport;
/* Currently implemented as qthread_syncvar_readFE/qthread_syncvar_fill. */
record QthreadNativeLock {
  var syncAux: aligned_t;

  proc lock() {
    extern proc qthread_lock (ref a : aligned_t): c_int;
    qthread_lock(syncAux);
  }
  proc unlock() {
    extern proc qthread_unlock (ref a : aligned_t): c_int;
    qthread_unlock(syncAux);
  }
}

record NoLock {
  proc lock() { }
  proc unlock() { }
}


use Time;

config const numIters = 1000000;
config const workPerIter = 100000;

config type syncType = SyncAuxLock;

proc main() {
  var syncLock: syncType;
  var i = 0;

  var timer: Timer; timer.start();
  forall 1..numIters with (ref i, ref syncLock) {
    syncLock.lock();
    for 1..workPerIter do i += 1;
    syncLock.unlock();
  }
  timer.stop();

  var desc = syncType:string + " with contention=" + here.maxTaskPar;
  writeln(desc + " took : ", timer.elapsed(), " seconds");

  assert(i == numIters * workPerIter);
}
```

**Comment by ronawho** [comment]
For the io-slowdown program in the original description here is the performance I see on master: 

```
Starting first instance of './io-slowdown --writesPerTask 100'
0.12
0.09
0.30
0.07
Starting second concurrent instance of './io-slowdown --writesPerTask 100'
7.97
        7.97
13.68
        13.68
```

And with https://github.com/chapel-lang/chapel/pull/10133: 

```sh
0.07
0.07
0.06
0.03
Starting second concurrent instance of './io-slowdown --writesPerTask 100'
        0.27
0.28
        0.18
0.18
0.35
        0.35
        0.30
0.30
        0.23
```

So we see that when just the first program is running parallel I/O is now faster, and once the second instance starts there is still a slowdown (to be expected since we're oversubscribing the hardware) but the slowdown is nowhere near as bad as it used to be. Used to see a ~150X slowdown, and now we only see a 4x slowdown.
