### ISSUE TITLE
Record leaks when yielded from forall loops with const-ref forall-intents

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#7765]
### Summary of Problem
A record yielded from a forall loop can be leaked if another record (type does not matter) is passed to the forall loop by default intent (const ref). If the outer record is passed by ref, there will be no leaking. A simple example for strings and associative domains:
```chpl
var A = {"a", "b", "c", "d", "e", "f"};
var B = {"b", "d", "f"};
const C = A - B;
writeln(C);
```
This program leaks 6 "string copy data" items, one for each element in ``A``. This is because the implementation of ``-`` between associative domains uses a forall loop and an associative domain passed by default intent.

### Steps to Reproduce
One can write a simpler reproducer that does not rely on strings or associative domains:
```chpl

class C { var x : int; }

record R {
  var c : C;
  proc length return c.x;
  proc deinit() { delete c; }
}

pragma "init copy fn"
proc chpl__initCopy(other : R) {
  pragma "no auto destroy"
  var ret : R;
  ret.c = new C(other.length);
  return ret;
}

record D {
  proc member(i) {
    return i >= 50 && i <= 100;
  }
}

iter foo() {
  var A : [1..10] R;
  for a in A do a.c = new C(5);

  for a in A do yield a;
}

iter foo(param tag:iterKind) where tag == iterKind.standalone {
  var A : [1..10] R;
  for a in A do a.c = new C(5);

  for a in A do yield a;
}

proc main() {
  var x = new D();
  // changing this to 'ref' eliminates/avoids the leaks!
  forall f in foo() with (const ref x) {
    writeln(x.member(f.length));
  }
}
```

**Comment by buddha314** [comment]
In conversation with BHarsh, it seems the [symmetric difference](https://chapel-lang.org/docs/master/technotes/sets.html?highlight=symmetric#symmetric-difference) operator may also create the same issue.  And, of course, that's what I need right now.

**Comment by buddha314** [comment]
In conversation with BHarsh, it seems the [symmetric difference](https://chapel-lang.org/docs/master/technotes/sets.html?highlight=symmetric#symmetric-difference) operator may also create the same issue.  And, of course, that's what I need right now.

**Comment by benharsh** [comment]
Note that this can also be triggered with leader/follower iterators:
```chpl
iter foo(param tag:iterKind) where tag == iterKind.leader {
  var A : [1..10] R;
  for a in A do a.c = new C(5);
  for a in A do yield a;
}
iter foo(param tag:iterKind, followThis) where tag == iterKind.follower {
  yield followThis;
}
```

**Comment by vasslitvinov** [comment]
Note that at present the variables passed by `ref` intent bypass altogether the implementation machinery of forall intents. (We may want to eliminate this special case.)

**Comment by mppf** [comment]
The examples in the PR message no longer leak. I believe my PR #8073 resolved these.
