### ISSUE TITLE
memory leak when promoting nested forall expression

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#7773]
The this test leaks memory.

test/trivial/deitz/statements/nested_fors.chpl, also shown below:

``` chapel
var x = [1..2] (3 + ([4..5] 6));
writeln(x);
```

**Comment by bradcray** [comment]
This looks like it's no longer leaking so I think this can be closed.  @mppf can you double-check me?

**Comment by mppf** [comment]
Yep, thanks for noticing.
