### ISSUE TITLE
Initializing a variable from forall expressions is serial

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#7777]
For example:

``` chapel
config const n = 20;

proc notparallel() {
  var x = [i in 1..n] i;
  writeln(x);
}

proc parallel() {
  var x:[1..n] int;

  forall i in 1..n {
    x[i] = i;
  }

  writeln(x);
}

notparallel();
parallel();
```

By setting a breakpoint on chpl_task_addToTaskList I can observe that no tasks are created in `notparallel`.

The issue here is that the initCopy from an iterator to create an array uses a `for` loop to enumerate the yielded elements and add them to the array. To do better, it would need the array's bounds... or possibly a very clever strategy.

**Comment by bradcray** [comment]
This seems somewhat related to #5958 (having sizes of arrays inherit the domain when initialized with a promoted expression) to me.

**Comment by mppf** [comment]
@bradcray - I agree. One way to interpret this issue is indication that lack of a solution to #5958 is both a productivity and a performance issue.

**Comment by vasslitvinov** [comment]
notparallel() now executes in parallel, according to the chpl_task_addToTaskList() check.

Due presumably to #11501.

Closing this as resolved.

**Comment by bradcray** [comment]
Awesome!
