### ISSUE TITLE
Method not found when has no argument or typed argument when using forwarding.

### ISSUE THREAD

**Issue by marcoscleison** [chapel-lang/chapel#7783]
### Summary of Problem

I have three classes A, B and C:
```chapel
class A{
  forwarding var driver: B;
}

class B{

proc foo1(){
   return this;
}

proc foo2(args2:string){
    return this;
}

proc foo3(args3, args4:string){
    return this;
}
proc foo4(arg){
   return this;
}

}

class C:B{

}


```
### Steps to Reproduce

The code below cannot compile:

```chapel
var c = new A(new C());
c.foo1();
```
Cannot compile with the compiler message:
```bash
error: unresolved call 'A.foo1()'
 note: candidates are: A.foo1()
 note:                          B.foo1()
```
The same error occurs for:

```chapel
var c = new A(new C());
c.foo2("Teste");
```
But for :

```chapel
var c = new A(new C());
c.foo3("Test", "Test");
```
and

```chapel
var c = new A(new C());
c.foo4("Teste");
```
It compiles well.

I suspect that error occurs when we have, no argument or the explicit type of all arguments, but when we have at least one non-typed argument it compiles well. 

### Configuration Information

- Output of `chpl --version`
chpl Version 1.16.0.e43acc7b31

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: clang
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: fifo *
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: cstdlib *
CHPL_MAKE: make
CHPL_ATOMICS: intrinsics
CHPL_GMP: none *
CHPL_HWLOC: none
CHPL_REGEXP: re2 *
CHPL_WIDE_POINTERS: struct
CHPL_AUX_FILESYS: none

- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
gcc (Ubuntu 7.2.0-8ubuntu3) 7.2.0

**Comment by mppf** [comment]
This might be the same issue as this future:
 test/classes/forwarding/forwardGenericVirtual.chpl

**Comment by mppf** [comment]
I havn't been able to reproduce this issue, but I might have pasted the examples together differently. Could you make a code sample that includes the whole file at once and fails to compile?

**Comment by marcoscleison** [comment]
Just an update. I made more experiment in my code motivated by the results obtained by @mppf . 

I realized that I made a mistake on declaring a type inside class definition.

The code above does not reproduce the compilation error, but if in the class B, I write a type definition:

```chapel
class B{

type MyType = 3*string; //This makes the compiler not find the overridden methods.

var x:MyType;

proc foo1(){
   return this;
}

proc foo2(args2:string){
    return this;
}

proc foo3(args3, args4:string){
    return this;
}
proc foo4(arg){
   return this;
}

}
```

The solution is making type declaration outside class definition such as: 
```chapel
type MyType = 3*string; //Make this outside class declaration.

class B{

var x:MyType;

proc foo1(){
   return this;
}

proc foo2(args2:string){
    return this;
}

proc foo3(args3, args4:string){
    return this;
}
proc foo4(arg){
   return this;
}

}
```
Now I see how silly was my mistake.

Thanks!
