### ISSUE TITLE
PRK stencil performing poorly under ugni

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#7830]
The optimized PRK stencil (and the below simplified reproducer) perform poorly under ugni if `QT_SPINCOUNT` is high, but performance is largely unaffected with gasnet-mpi. The reproducer is effectively just `A += 1` over a distributed array.

Note that this is part of the cause for ugni losing to gn-mpi in the nightly prk stencil [graphs](https://chapel-lang.org/perf/16-node-xc/?startdate=2017/11/03&enddate=2017/11/17&configs=gnuugniqthreads,gnugasnetmpi&suite=prkperf)

Here's a look at the perf for the reproducer (ugni is 2x slower with a high spin count):

| spin        | ugni   | gn-mpi |
| ----------- | ------ | ------ |
| 300         |   .43s |   .45s |
| 300,000,000 |   .89s |   .48s |

I haven't had much luck narrowing down the cause of this. Initially I thought that ugni's progress-thread might be getting starved somehow because the spinwaiting was preventing it from running, but that doesn't seem to be the case. Giving the progress thread a dedicated core didn't change the overall result, and doing an empty task spawn across all tasks performs much better with a high spincount, and I would guess that would slowdown if the progress-thread was being starved:

```chpl
coforall loc in Locales do on loc 
  do coforall 1..here.maxTaskPar {}
```

The below reproducer shouldn't be doing much communication during the timed section beyond the initial `coforall loc in targetLocs` in the distribution to spawn across locales, so it's not obvious to me why the comm layer matters:

```chpl
use Time;
use StencilDist;
use BlockDist;

config const iterations: int = 3;
config const order: int = 128000;

config param useStencilDist = true;

proc main() {
  // setup a block or stencil dist array
  const localDom = {0.. # order, 0.. # order};
  const inputDom = if useStencilDist then new dmap(new Stencil(localDom))
                   else new dmap(new Block(localDom));
  const Dom = localDom dmapped inputDom;
  var input: [Dom] real;


  // time adding 1 to each element in the array
  var timer: Timer;
  timer.start();

  for 1..iterations {
    forall i in input do i += 1.0;
  }

  timer.stop();
  writeln(timer.elapsed());
}
```

The other (maybe related) thing that hurts prk-stencil is that ugni seems to spawn more tasks or something, which messes up the round-robin scheduling qthreads does and results in worse affinity between consecutive iterations. 

My [experimental task-resetting](https://github.com/chapel-lang/chapel/compare/master...66095dd) combined with a low spincount results in the reproducer and prk-stencil performing better under ugni than gn-mpi

**Comment by ronawho** [comment]
Here's an even smaller reproducer that's just using a 1D blockdist:

```chpl
use Time, BlockDist;

config const iterations: int = 3;
config const order:      int = 128000;

var A: [{1..order**2} dmapped Block({1..order**2})] int;


var timer: Timer; timer.start();

for 1..iterations do
  forall a in A do a += 1;

writeln(timer.elapsed());
```

**Comment by ronawho** [comment]
https://github.com/chapel-lang/chapel/pull/7831 is a closed PR that has the experimental task-resetting code I've been using to debug

**Comment by gbtitus** [comment]
Using the shorter 2nd reproducer running on 16 BW28 nodes, I'm seeing a reported time of 0.59 secs for `QT_SPINCOUNT=300 `and 0.90 secs for `QT_SPINCOUNT=300000000`. However, I'm not seeing any significant difference in comm load. There are the same number of `PUTs`, `AMOs`, and `executeOns` of all kinds for both.  Summed across the entire 16-node program there are ~100k `GETs` (~1m bytes) for the former and ~300k `GETs` (~2m bytes) for the latter, but the network is capable of hundreds of times this level of traffic, so that difference is of no consequence.  I'll look at task counts next.

**Comment by gbtitus** [comment]
(To some extent I'm talking to myself here, but I need somewhere to put the data so this will have to do.)

The number of tasks created and run is exactly the same for `comm=gasnet-mpi` and `comm=ugni`.  But the number of yields differs quite a bit.

Here are some measurements, again just for the timed region.  The first number in each box is the number of calls to `chpl_task_yield()`, the second number is the reported execution time in seconds, and the third is the derived number of yields per second:

QT_SPINCOUNT | gasnet-mpi | ugni
---- | ---- | ----
300 | 20m, 0.45, 44m yields/sec | 33m, 0.48, 69m yields/sec
300m | 19m, 0.45, 42m yields/sec | 55m, 0.90, 61m yields/sec

Having said this, though, I believe that the large number of yields is actually an effect of the longer execution time rather than a cause of it, because the `comm=ugni` internal statistics seem to be saying that most of these yields are the main threads on the non-0 nodes waiting at the comm exit barrier while the program progresses.  I'll need to gather more information before concluding this for sure, however.

**Comment by ronawho** [comment]
I was trying to get per-locale timings to see if one locale is computing a lot slower and I ran into an interesting case where if I added some work right before starting the local computation (originally to gather start times before starting the per-locale work) then the whole computation finishes faster.

Here's my new repro (it's similar to the minimal reproducer but instead of a forall over the distributed array, it a `coforall loc in Locales` and then a forall over the local default rectangular array):

```chpl
use Time, BlockDist;

config const iterations: int = 3;
config const order:      int = 128000;

var A: [{1..order**2} dmapped Block({1..order**2})] int;

var timer: Timer;
var timers: [0..#numLocales] Timer;
var startTimes: [0..#numLocales] real;
var origTime = getCurrentTime();

enum Delay {none, taskYield, storeStartTime}; use Delay;
config const delay = none;

proc delayIt() {
  select delay {
    when none do
      ;
    when taskYield do
      for 1..1000 do chpl_task_yield();
    when storeStartTime do
      startTimes[here.id] = getCurrentTime();
  }
}

timer.start();
for it in 1..iterations {
  coforall loc in Locales do on loc {
    delayIt();

    timers[loc.id].start();
    forall a in A.localSubdomain() do A.localAccess[a] += 1;
    timers[loc.id].stop();
  }
}
timer.stop();

if delay == storeStartTime then
  writeln("Start time:        ", startTimes - origTime, new iostyle(precision=2));
writeln("Total time:        ", timer.elapsed(), new iostyle(precision=2));
writeln("Per locale timers: ", timers.elapsed(), new iostyle(precision=2));
```

With a high spincount (I'm actually building without  `--enable-condwait-queue` so infinit spin) I see:

```
jupiter: chapel (master) $ ./f -nl16 --delay=none
Total time:        0.91
Per locale timers: 0.46 0.45 0.45 0.45 0.45 0.45 0.45 0.45 0.45 0.46 0.45 0.45 0.46 0.45 0.45 0.45

jupiter: chapel (master) $ ./f -nl16 --delay=taskYield
Total time:        0.47
Per locale timers: 0.47 0.45 0.45 0.44 0.45 0.46 0.45 0.45 0.45 0.45 0.45 0.45 0.45 0.45 0.46 0.45

jupiter: chapel (master) $ ./f -nl16 --delay=storeStartTime
Start time:        0.31 0.31 0.31 0.31 0.31 0.31 0.31 0.31 0.31 0.31 0.31 0.31 0.31 0.31 0.31 0.31
Total time:        0.46
Per locale timers: 0.46 0.45 0.45 0.45 0.46 0.46 0.45 0.45 0.45 0.46 0.45 0.45 0.45 0.46 0.45 0.45
```

or summarizing:

| delay=none | delay=taskYield | delay=storeStartTime |
| ---------- | --------------- | -------------------- |
|       .91s |            .45s |                 .45s |

But each local computation is only taking ~.45 seconds (even for the slow case) so the actual local computation heavy part is equally fast on all locales

**Comment by ronawho** [comment]
So switching the last example to only do `delayIt()` on locale 0 also works, and spawning to the locales in reverse also resolves the performance issue (i.e. instead of spawning to 0, 1, 2, .. numLocales-1, spawn to numLocales-1, numLocales-2,... 2, 1, 0)

What we discovered is that the ugni code that does a remote fork, ends up doing a `chpl_task_yield()` while waiting for an ack back from the remote locale. This yield allows the tasks scheduled on locale 0 for the array "kernel" to run to completion before the remote-spawning task is run again. Effectively we were doing a local-spawn to locale 0, doing a remote spawn to locale 1, yielding on locale 0, doing the main computation on locale 0 and 1, and then spawning to the other locales and doing computation on them.

This explains why this only impacted ugni, and not gn-mpi (gasnet isn't doing a chpl_task_yield after forking), and also explains why the time was roughly doubled with a high spincount. Having a low spincount caused the tasks on locale 0 to have a slower startup time, which just happened to be enough time for the main task to finish spawning to remote locales.

We're going to try removing that chpl_task_yield for the fork code. That code is shared with the amo/get/put code paths, so we're going to try and leave the yield for those paths since the task_yield enables comm/compute overlap.

Removing the yield resolves the performance for the microbenchmarks as well as stencil prk. I'm going to do a full perf run next.

**Comment by bradcray** [comment]
> So switching the last example to only do delayIt() on locale 0 also works, and spawning to the locales in reverse also resolves the performance issue (i.e. instead of spawning to 0, 1, 2, .. numLocales-1, spawn to numLocales-1, numLocales-2,... 2, 1, 0)

Does this suggest that I get partial credit for my lunchtime suggestion?  :)

**Comment by ronawho** [comment]
>Does this suggest that I get partial credit for my lunchtime suggestion? :)

Yup, Greg and I were already going split credit for the 1 line removal, so we can add you to that :) I figure greg gets credit for removing `local_`, I'll take `yield` and we can put you down for `();`
