### ISSUE TITLE
Improve Channel Formats

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#7846]
Today, channel formats are handled through type specifiers in `writef` calls or the `style` (format) argument:

```chpl
writef('%...', foo);

// or

var c = open('foo.txt', iomode.r).reader(style=...);
```

The main problems with this approach are:
 1. How would a more extensive/invasive format be implemented, say one that allow the serialization of circular object structures / graphs?
 2. Why is '%j' supported in the format strings and not any other common format (TOML, YAML, Google Protocol Buffers, ...)
 3. The style is currently implemented as a structure in the QIO C code. That's reasonable for numeric formats (since there are relatively few of these) but probably isn't reasonable for things like json/toml/serialization schemes. That causes code using these patterns to use constants like QIO_STYLE_ELEMENT_STRING.

There are 2 dimensions to what we might want a channel IO to support: *formats* and *types*.

```
 formats (json, toml, yaml, ...)
 ^
 |
 |
 |
  ------>
  types (array, int, string, ...)
```

Here are some sketches of possible directions to move towards:

```chpl
// e.g. json format
json.writeln(r, f);
f.writeln(r, formatter=json);
writef('%c', (json, r));
```

**Comment by ben-albrecht** [comment]
This issue came out of a discussion with @mppf when trying to determine the Chapel idiomatic way to read/write JSON and TOML for the TOML module.

**Comment by mppf** [comment]
The swift 'encodable' interface seems interesting prior work here. https://developer.apple.com/documentation/swift/encodable

**Comment by benharsh** [comment]
I believe this has been handled with the advent of the ``%?`` format specifier when combined with serializers and deserializers.
