### ISSUE TITLE
captured promotion of function returning void is not an error

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#7866]
The following program compiles and executes but I would have expected it to result in compilation error, since the commented out section at the end results in compilation error.

``` chapel
proc ref int.foo() { // returns void
  this += 1;
}

var A = [1,2,3,4,5,6,7,8,9];
writeln(A);

var B = A.foo();  // shouldn't this be an error?
writeln(B.type:string);
writeln(B);


//var C = A[1].foo();  // this is an error
//writeln(C.type:string);
//writeln(C);
```

**Comment by mppf** [comment]
@daviditen - I'm curious of your opinion of this issue

**Comment by daviditen** [comment]
I agree that the assignment to `B` should cause a compiler error.  I suspect that the promotion is throwing off the void checking.

**Comment by daviditen** [comment]
@mppf could you please take a look at #7878?
