### ISSUE TITLE
default argument value for overridden methods

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#7880]
(This issue is a split-out version of a comment by @cassella from issue #7868).

@cassella says:

Besides visibility, scoping, and promotion, what about virtual functions with different default values for an argument?  For example,

```chapel
class C {
  proc foo(x = 10) { writeln("C.foo:", x); }
}

class D : C {
  proc foo(x = 20) { writeln("D.foo:", x); }
}

var d = new D();
d.foo();

var c: C = new D();
c.foo();
```

master currently prints

```
D.foo:20
D.foo:10
```

It's surprising me that the second call is being dynamically dispatched to ``D.foo()`` but picking up ``C.foo()``'s default value.

I think this is the behavior that the proposed change would require, since it'd have to evaluate the default value where the call is made, so the base class's method is the only one it knows about there.  But I'm wondering if that's really what should happen.

FWIW, the spec (16.2.5) says methods can be overridden and virtually dispatched if they have identical signatures.  But then it lists what's required to be considered identical: "names, types, and order".  It doesn't include default values.  (Or intents, for that matter.)  If the default value should be part of the identicalness, I'd think it either shouldn't compile, or shouldn't virtually dispatch in this case.

**Comment by cassella** [comment]
FWIW, the behavior on master when the signature isn't identical is to not dynamically dispatch the call.

With

```chapel
  proc C.bar(x: int) { writeln("C.bar:", x); }
  proc D.bar(x: real) { writeln("D.bar:", x); }
```

``d.bar(5)`` prints ``D.bar: 5.0`` and ``c.bar(5)`` prints ``C.bar: 5``.  (Where ``c`` is the ``var c:C = new D()`` from above.)

**Comment by mppf** [comment]
@cassella - what is happening there is that in virtual method dispatch, each different method signature gets its own "slot" - so `bar(x:int)` and `bar(x:real)` are basically treated as though they had different method names.
