### ISSUE TITLE
First-class functions leak

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#7890]
### Summary of Problem
First class functions always leak:
```chpl
proc bar() {
  writeln("in bar!");
}

proc foo(f) {
  f();
}

foo(bar);
```
```
> ./a.out --memLeaksByType
in bar!

====================
Leaked Memory Report
==============================================================
Number of leaked allocations
           Total leaked memory (bytes)
                      Description of allocation
==============================================================
1          4          _chpl_fcf_0_bar
==============================================================
```

List of tests that leak primarily due to first-class function usage:
- [x] [fun_as_value.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/fun_as_value.chpl)
- [x] [fun_as_value.chpl](https://github.com/chapel-lang/chapel/blob/master/test/trivial/jturner/fun_as_value.chpl)
- [x] [fun_ret_class.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/fun_ret_class.chpl)
- [x] [spec-test_dropWhile.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/spec-test_dropWhile.chpl)
- [x] [spec-test_foldLeft.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/spec-test_foldLeft.chpl)
- [ ] [Grid_DiffusionBE_driver.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/amr/diffusion/grid/Grid_DiffusionBE_driver.chpl)
- [ ] [AMR_AdvectionCTU_driver.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/amr/advection/amr/AMR_AdvectionCTU_driver.chpl)
- [ ] [spec-test_map.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/spec-test_map.chpl)
- [ ] [fun_type_annot_int_void.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/fun_type_annot_int_void.chpl)
- [ ] [fun_as_value_multiarg_mixed.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/fun_as_value_multiarg_mixed.chpl)
- [ ] [exitWithNoCall.chpl](https://github.com/chapel-lang/chapel/blob/master/test/exits/albrecht/exitWithNoCall.chpl)
- [ ] [passFnsToCChapel2x.chpl](https://github.com/chapel-lang/chapel/blob/master/test/extern/fnPtrs/passFnsToCChapel2x.chpl)
- [ ] [Level_AdvectionCTU_driver.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/amr/advection/level/Level_AdvectionCTU_driver.chpl)
- [ ] [spec-test_filter.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/spec-test_filter.chpl)
- [ ] [fun_type_annot_single.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/fun_type_annot_single.chpl)
- [ ] [Level_DiffusionBE_driver.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/amr/diffusion/level/Level_DiffusionBE_driver.chpl)
- [ ] [fun_tuple_arg.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/fun_tuple_arg.chpl)
- [ ] [fcf-rettype-void.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/nspark/fcf-rettype-void.chpl)
- [ ] [spec-test_takeWhile.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/spec-test_takeWhile.chpl)
- [ ] [exitWithNoParensNoArgs.chpl](https://github.com/chapel-lang/chapel/blob/master/test/exits/sungeun/exitWithNoParensNoArgs.chpl)
- [ ] [fun_as_value_crossmodule.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/fun_as_value_crossmodule.chpl)
- [ ] [passFnsToCChapel2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/extern/fnPtrs/passFnsToCChapel2.chpl)
- [ ] [storeFnsThenPass2x.chpl](https://github.com/chapel-lang/chapel/blob/master/test/extern/fnPtrs/storeFnsThenPass2x.chpl)
- [ ] [fun_duplicate_values.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/fun_duplicate_values.chpl)
- [ ] [storeFnsThenPass.chpl](https://github.com/chapel-lang/chapel/blob/master/test/extern/fnPtrs/storeFnsThenPass.chpl)
- [ ] [fcf-defaultInit.chpl](https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/compilerGenerated/fcf-defaultInit.chpl)
- [ ] [retType.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/sungeun/retType.chpl)
- [ ] [fun_as_value_default.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/fun_as_value_default.chpl)
- [ ] [spec-test_foldRight.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/spec-test_foldRight.chpl)
- [ ] [fun_as_value_multiarg.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/fun_as_value_multiarg.chpl)
- [ ] [passFnsToCChapel.chpl](https://github.com/chapel-lang/chapel/blob/master/test/extern/fnPtrs/passFnsToCChapel.chpl)
- [ ] [futures-doc-taskfn.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/packages/Futures/futures-doc-taskfn.chpl)
- [ ] [lambda_const_ret_type.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/lambda_const_ret_type.chpl)
- [ ] [Grid_AdvectionCTU_driver.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/amr/advection/grid/Grid_AdvectionCTU_driver.chpl)
- [ ] [futures-waitall.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/packages/Futures/futures-waitall.chpl)
- [ ] [futures-doc-waitall.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/packages/Futures/futures-doc-waitall.chpl)
- [ ] [futures-doc-chaining2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/packages/Futures/futures-doc-chaining2.chpl)
- [ ] [futures-doc-simple.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/packages/Futures/futures-doc-simple.chpl)
- [ ] [futures-simple.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/packages/Futures/futures-simple.chpl)
- [ ] [futures-task-function.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/packages/Futures/futures-task-function.chpl)
- [ ] [futures-doc-chaining1.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/packages/Futures/futures-doc-chaining1.chpl)
- [ ] [futures-chaining1.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/packages/Futures/futures-chaining1.chpl)
- [ ] [futures-doc-validity.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/packages/Futures/futures-doc-validity.chpl)
- [ ] [futures-chaining2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/packages/Futures/futures-chaining2.chpl)
- [ ] [return_first_class_function.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/return_first_class_function.chpl)
- [ ] [common_fp_idioms.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/common_fp_idioms.chpl)
- [ ] [lambda_simple.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/lambda_simple.chpl)
- [ ] [lambda_assign.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/lambda_assign.chpl)
- [ ] [fun_type_annot_void.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/fun_type_annot_void.chpl)
- [ ] [fun_as_value_crossmodule2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/fun_as_value_crossmodule2.chpl)
- [ ] [fun_parent_test.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/fun_parent_test.chpl)
- [ ] [fun_type_annot.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/jturner/fun_type_annot.chpl)
- [ ] [fcf-rettype.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/nspark/fcf-rettype.chpl)
- [ ] [fcf-argtypes.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/nspark/fcf-argtypes.chpl)

**Comment by nimitbhardwaj** [comment]
Perhaps the cause of this memory leak is assignment, I tried this code,
```
proc hello() {
  writeln("Hello World");
}
var f = hello;
```
on `./a.out --memLeaksByType`
```
====================
Leaked Memory Report
==============================================================
Number of leaked allocations
           Total leaked memory (bytes)
                      Description of allocation
==============================================================
1          4          _chpl_fcf_0_hello
==============================================================

```
I expected it, because when we are calling a function by passing another function to it then it is a pass by value there i guess, so assignment of functions cause the memory leak.
One more important thing when we do, 
```
proc hello() {
  writeln("Hello World");
}
var f = hello;
delete f;
```
no memory leak is recorded, so I think f is becoming a class which is not deleted afterwords.
I would like fix this bug, but I need some help, like in the compiler section which code governs assignment, and other data what can be done.
