### ISSUE TITLE
Dist/domain/array leaks

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#7891]
This issue exists to track distribution, domain, and array leaks. Hopefully we can split this into separate issues as we begin to understand the cause of the leaks. Until then, let's use a single issue because dists/domains/arrays are closely linked and a bug in one type can lead to leaks in the others.

I have attempted to create some rough categories below, but there are likely multiple issues involved in each area.

DefaultRectangular arrays/domains:
  - [x] [arrayOfArrayArg-inferred.chpl](https://github.com/chapel-lang/chapel/blob/master/test/arrays/bradc/arrayOfArrayArg-inferred.chpl)
  - [x] [array_init_should_copy.chpl](https://github.com/chapel-lang/chapel/blob/master/test/arrays/bradc/array_init_should_copy.chpl)
  - [x] [matrix.chpl](https://github.com/chapel-lang/chapel/blob/master/test/arrays/deitz/matrix.chpl)
  - [x] [test_array_of_array2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/arrays/deitz/part2/test_array_of_array2.chpl)
  - [x] [test_array_of_array_assignment.chpl](https://github.com/chapel-lang/chapel/blob/master/test/arrays/deitz/part4/test_array_of_array_assignment.chpl)
  - [x] [test_array_of_array_assignment2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/arrays/deitz/part4/test_array_of_array_assignment2.chpl)
  - [x] [test_array_of_array_init_via_tuple.chpl](https://github.com/chapel-lang/chapel/blob/master/test/arrays/deitz/part4/test_array_of_array_init_via_tuple.chpl)
  - [x] [test_array_of_array_of_array.chpl](https://github.com/chapel-lang/chapel/blob/master/test/arrays/deitz/part4/test_array_of_array_of_array.chpl)
  - [x] [test_array_of_array_of_array_assign.chpl](https://github.com/chapel-lang/chapel/blob/master/test/arrays/deitz/part4/test_array_of_array_of_array_assign.chpl)
  - [x] [test_array_type_alias.chpl](https://github.com/chapel-lang/chapel/blob/master/test/arrays/deitz/part4/test_array_type_alias.chpl)
  - [x] [test_assoc_of_arith.chpl](https://github.com/chapel-lang/chapel/blob/master/test/arrays/deitz/part5/test_assoc_of_arith.chpl)
  - [x] [test_major_nesting_of_arrays.chpl](https://github.com/chapel-lang/chapel/blob/master/test/arrays/deitz/part5/test_major_nesting_of_arrays.chpl)
  - [x] [test_multi_array_of_array.chpl](https://github.com/chapel-lang/chapel/blob/master/test/arrays/deitz/part5/test_multi_array_of_array.chpl)
  - [x] [test_multi_array_of_array2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/arrays/deitz/part5/test_multi_array_of_array2.chpl)
  - [x] [test_class_array3.chpl](https://github.com/chapel-lang/chapel/blob/master/test/arrays/deitz/part6/test_class_array3.chpl)
  - [x] [test_generic_record_of_array.chpl](https://github.com/chapel-lang/chapel/blob/master/test/arrays/deitz/part7/test_generic_record_of_array.chpl)
  - [ ] [test_array_type1.chpl](https://github.com/chapel-lang/chapel/blob/master/test/arrays/deitz/runtime_types/test_array_type1.chpl)
  - [ ] [test_array_type2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/arrays/deitz/runtime_types/test_array_type2.chpl)
  - [ ] [test_array_type3.chpl](https://github.com/chapel-lang/chapel/blob/master/test/arrays/deitz/runtime_types/test_array_type3.chpl)
  - [ ] [test_array_type4.chpl](https://github.com/chapel-lang/chapel/blob/master/test/arrays/deitz/runtime_types/test_array_type4.chpl)
  - [x] [simple-4.chpl](https://github.com/chapel-lang/chapel/blob/master/test/arrays/jplevyak/simple-4.chpl)
  - [x] [vectorMethods.chpl](https://github.com/chapel-lang/chapel/blob/master/test/arrays/methods/vectorMethods.chpl)
  - [x] [cast-to-array-type.chpl](https://github.com/chapel-lang/chapel/blob/master/test/arrays/vass/cast-to-array-type.chpl)
  - [x] [assocArrayOfArithArray.chpl](https://github.com/chapel-lang/chapel/blob/master/test/associative/diten/assocArrayOfArithArray.chpl)
  - [ ] [genericClassArray-anon.chpl](https://github.com/chapel-lang/chapel/blob/master/test/classes/bradc/arrayInClass/genericClassArray-anon.chpl)
  - [x] [genericClassArray-named.chpl](https://github.com/chapel-lang/chapel/blob/master/test/classes/bradc/arrayInClass/genericClassArray-named.chpl)
  - [x] [deleteArrays.chpl](https://github.com/chapel-lang/chapel/blob/master/test/classes/deleting/deleteArrays.chpl)
  - [x] [default_initializer.chpl](https://github.com/chapel-lang/chapel/blob/master/test/classes/dinan/default_initializer.chpl)
  - [x] [array-field-not-in-call2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/compilerGenerated/array-field-not-in-call2.chpl)
  - [x] [test_array_of_distributed_array2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/distributions/robust/arithmetic/basics/test_array_of_distributed_array2.chpl)
  - [x] [test_distributed_array_of_array1.chpl](https://github.com/chapel-lang/chapel/blob/master/test/distributions/robust/arithmetic/basics/test_distributed_array_of_array1.chpl)
  - [x] [test_distributed_array_of_array2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/distributions/robust/arithmetic/basics/test_distributed_array_of_array2.chpl)
  - [x] [test_module_Norm.chpl](https://github.com/chapel-lang/chapel/blob/master/test/distributions/robust/arithmetic/modules/test_module_Norm.chpl)
  - [x] [rankOnArrayOfArrays.chpl](https://github.com/chapel-lang/chapel/blob/master/test/domains/stonea/rankOnArrayOfArrays.chpl)
  - [x] [multiLocaleTaskParallelMonteCarloPi.chpl](https://github.com/chapel-lang/chapel/blob/master/test/exercises/MonteCarloPi/deitz/MonteCarloPi/multiLocaleTaskParallelMonteCarloPi.chpl)
  - [x] [sparse-ref-return.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/bharshbarg/sparse-ref-return.chpl)
  - [x] [followFlexType.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/iterators/bradc/leadFollow/followFlexType.chpl)
  - [x] [localfollow.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/iterators/bradc/leadFollow/localfollow.chpl)
  - [x] [localfollow2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/iterators/bradc/leadFollow/localfollow2.chpl)
  - [x] [yield-arrays-var-nonvar.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/iterators/vass/yield-arrays-var-nonvar.chpl)
  - [ ] [type-and-param-function-arg-conversions.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/vass/type-and-param-function-arg-conversions.chpl)
  - [x] [ri-7-initAccum.chpl](https://github.com/chapel-lang/chapel/blob/master/test/parallel/forall/reduce-intents/ri-7-initAccum.chpl)
  - [x] [ri-a1-ident-ref-ret.chpl](https://github.com/chapel-lang/chapel/blob/master/test/parallel/forall/reduce-intents/ri-a1-ident-ref-ret.chpl)
  - [x] [array-reduce-intents.chpl](https://github.com/chapel-lang/chapel/blob/master/test/parallel/forall/vass/array-reduce-intents.chpl)
  - [x] [array-reduce-intents2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/parallel/forall/vass/array-reduce-intents2.chpl)
  - [x] [reduce-fatter-with-forall-in-par-iter.chpl](https://github.com/chapel-lang/chapel/blob/master/test/parallel/forall/vass/reduce-fatter-with-forall-in-par-iter.chpl)
  - [x] [yield-arrays-in-task-funs.chpl](https://github.com/chapel-lang/chapel/blob/master/test/parallel/taskPar/vass/yield-arrays-in-task-funs.chpl)
  - [ ] [testSerialReductions.chpl](https://github.com/chapel-lang/chapel/blob/master/test/reductions/diten/testSerialReductions.chpl)
  - [ ] [isx.chpl](https://github.com/chapel-lang/chapel/blob/master/test/release/examples/benchmarks/isx/isx.chpl)
  - [ ] [meteor-fast.chpl](https://github.com/chapel-lang/chapel/blob/master/test/release/examples/benchmarks/shootout/meteor-fast.chpl)
  - [ ] [meteor.chpl](https://github.com/chapel-lang/chapel/blob/master/test/release/examples/benchmarks/shootout/meteor.chpl)
  - [ ] [arrays.chpl](https://github.com/chapel-lang/chapel/blob/master/test/release/examples/primers/arrays.chpl)
  - [ ] [opaque-domains.chpl](https://github.com/chapel-lang/chapel/blob/master/test/release/examples/primers/opaque-domains.chpl)
  - [ ] [decl-with-anon-domain.chpl](https://github.com/chapel-lang/chapel/blob/master/test/release/examples/spec/Arrays/decl-with-anon-domain.chpl)
  - [ ] [typeAliases.chpl](https://github.com/chapel-lang/chapel/blob/master/test/release/examples/users-guide/base/typeAliases.chpl)
  - [ ] [CoMD.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/comd/llnl/CoMD.chpl)
  - [ ] [stream-block1dclass.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/hpcc/STREAMS/bradc/stream-block1dclass.chpl)
  - [ ] [isx-bucket-spmd.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/isx/isx-bucket-spmd.chpl)
  - [ ] [isx-hand-optimized.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/isx/isx-hand-optimized.chpl)
  - [ ] [isx-no-return.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/isx/isx-no-return.chpl)
  - [ ] [isx-per-task.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/isx/isx-per-task.chpl)
  - [ ] [kmeans-blc.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/kmeans/kmeans-blc.chpl)
  - [ ] [labelprop-tweets.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/labelprop/labelprop-tweets.chpl)
  - [ ] [lulesh-eof.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/lulesh/bradc/tests/lulesh-eof.chpl)
  - [ ] [lulesh-eof2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/lulesh/bradc/tests/lulesh-eof2.chpl)
  - [ ] [chameneosredux-blc.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/shootout/chameneos-redux/bradc/chameneosredux-blc.chpl)
  - [ ] [meteor-implicit-domain.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/shootout/meteor/kbrady/meteor-implicit-domain.chpl)
  - [ ] [meteor-parallel.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/shootout/meteor/kbrady/meteor-parallel.chpl)
  - [ ] [meteor.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/shootout/meteor/kbrady/meteor.chpl)
  - [ ] [meteor.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/shootout/submitted/meteor.chpl)
  - [ ] [meteor2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/shootout/submitted/meteor2.chpl)
  - [ ] [tupleOfArrayReturnType.chpl](https://github.com/chapel-lang/chapel/blob/master/test/types/tuple/diten/tupleOfArrayReturnType.chpl)
  - [ ] [zip_forall.chpl](https://github.com/chapel-lang/chapel/blob/master/test/types/tuple/sungeun/iteration/zip_forall.chpl)
  - [ ] [runtime-type-global-literal2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/types/type_variables/ferguson/runtime-type-global-literal2.chpl)
  - [ ] [simple-3deep.chpl](https://github.com/chapel-lang/chapel/blob/master/test/users/bugzilla/bug794133/simple-3deep.chpl)
  - [ ] [simple-breaks.chpl](https://github.com/chapel-lang/chapel/blob/master/test/users/bugzilla/bug794133/simple-breaks.chpl)
  - [ ] [simple-noresize.chpl](https://github.com/chapel-lang/chapel/blob/master/test/users/bugzilla/bug794133/simple-noresize.chpl)
  - [ ] [simple-reresize.chpl](https://github.com/chapel-lang/chapel/blob/master/test/users/bugzilla/bug794133/simple-reresize.chpl)
  - [ ] [simple-workaround2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/users/bugzilla/bug794133/simple-workaround2.chpl)
  - [ ] [simple.chpl](https://github.com/chapel-lang/chapel/blob/master/test/users/bugzilla/bug794133/simple.chpl)

Private:
  - [ ] [SSCA2-with-Private-1.chpl](https://github.com/chapel-lang/chapel/blob/master/test/modules/vass/SSCA2-with-Private-1.chpl)
  - [ ] [SSCA2-with-Private-2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/modules/vass/SSCA2-with-Private-2.chpl)
  - [ ] [private.chpl](https://github.com/chapel-lang/chapel/blob/master/test/parallel/taskPar/sungeun/private.chpl)

DefaultDist:
  - [ ] [equality1.chpl](https://github.com/chapel-lang/chapel/blob/master/test/distributions/sungeun/equality1.chpl)
  - [ ] [equality2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/distributions/sungeun/equality2.chpl)

DefaultAssociative arrays/domains:
  - [ ] [plus-reduce-intent-assoc.chpl](https://github.com/chapel-lang/chapel/blob/master/test/associative/ferguson/plus-reduce-intent-assoc.chpl)
  - [ ] [histogram-1.chpl](https://github.com/chapel-lang/chapel/blob/master/test/reductions/vass/histogram-1.chpl)
  - [ ] [histogram-2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/reductions/vass/histogram-2.chpl)
  - [ ] [runtime-type-global-call.chpl](https://github.com/chapel-lang/chapel/blob/master/test/types/type_variables/ferguson/runtime-type-global-call.chpl)
  - [ ] [runtime-type-global-literal.chpl](https://github.com/chapel-lang/chapel/blob/master/test/types/type_variables/ferguson/runtime-type-global-literal.chpl)
  - UserMapAssoc:
    - [ ] [userAssoc-array-domain-zipper.chpl](https://github.com/chapel-lang/chapel/blob/master/test/distributions/bradc/assoc/userAssoc-array-domain-zipper.chpl)
    - [ ] [userAssoc-array-priv-check.chpl](https://github.com/chapel-lang/chapel/blob/master/test/distributions/bradc/assoc/userAssoc-array-priv-check.chpl)
    - [ ] [userAssoc-basic-array.chpl](https://github.com/chapel-lang/chapel/blob/master/test/distributions/bradc/assoc/userAssoc-basic-array.chpl)
    - [ ] [userAssoc-basic-domain.chpl](https://github.com/chapel-lang/chapel/blob/master/test/distributions/bradc/assoc/userAssoc-basic-domain.chpl)
    - [ ] [userAssoc-dom-operations.chpl](https://github.com/chapel-lang/chapel/blob/master/test/distributions/bradc/assoc/userAssoc-dom-operations.chpl)
    - [ ] [userAssoc-domain-priv-check.chpl](https://github.com/chapel-lang/chapel/blob/master/test/distributions/bradc/assoc/userAssoc-domain-priv-check.chpl)

Block arrays/domains:
  - [ ] various SSCA2
  - [ ] [graph500](https://github.com/chapel-lang/chapel/blob/master/test/studies/graph500/)
  - [ ] [leadFollowOpt.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/hpcc/common/bradc/unit/leadFollowOpt.chpl)
  - [ ] [parBlock1D.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/hpcc/common/bradc/unit/parBlock1D.chpl)
  - [ ] [graphio.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/ssca2/graphio/graphio.chpl)
  - [ ] [nondet.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/ssca2/test-rmatalt/nondet.chpl)
  - [ ] [reproduc.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/ssca2/test-rmatalt/reproduc.chpl)
  - [ ] [arrayTypedef.chpl](https://github.com/chapel-lang/chapel/blob/master/test/types/typedefs/bradc/arrayTypedef.chpl)

Array Views:
  - [ ] [ref-intent-bug-2big.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/vass/ref-intent-bug-2big.chpl)

Sparse arrays/domains:
  - [ ] [correctness.chpl](https://github.com/chapel-lang/chapel/blob/master/test/chplenv/chplconfig/correctness/correctness.chpl)
  - [ ] [spsBlk](https://github.com/chapel-lang/chapel/blob/master/test/distributions/bradc/spsBlk/)
  - [ ] [clearSparseBlock.chpl](https://github.com/chapel-lang/chapel/blob/master/test/distributions/sparseBlock/clearSparseBlock.chpl)
  - [ ] [correctness.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/packages/LinearAlgebra/correctness/correctness.chpl)
  - [ ] [correctness.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/packages/Search/correctness.chpl)
  - [ ] [correctness.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/packages/Sort/correctness/correctness.chpl)
  - [ ] [correctness.chpl](https://github.com/chapel-lang/chapel/blob/master/test/sparse/CS/correctness.chpl)
  - [ ] [correctness.chpl](https://github.com/chapel-lang/chapel/blob/master/test/sparse/CS/multiplication/correctness.chpl)
  - [ ] [dsiFuncs.chpl](https://github.com/chapel-lang/chapel/blob/master/test/sparse/engin/dsiFuncs.chpl)
  - [ ] [dsiFuncsSpsBlk.chpl](https://github.com/chapel-lang/chapel/blob/master/test/sparse/engin/dsiFuncsSpsBlk.chpl)
  - [ ] [nnzCounting.chpl](https://github.com/chapel-lang/chapel/blob/master/test/sparse/engin/nnzCounting.chpl)
  - [ ] [sparse_bulk](https://github.com/chapel-lang/chapel/blob/master/test/users/engin/sparse_bulk/)
  - [ ] [sparse_bulk_dist](https://github.com/chapel-lang/chapel/blob/master/test/users/engin/sparse_bulk_dist/)
  - [x] [sparse.chpl](https://github.com/chapel-lang/chapel/blob/master/test/arrays/sparse/sparse.chpl)
  - [x] [layoutEquality2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/distributions/bradc/layoutEquality2.chpl)
  - [x] [spsblkAssignment.chpl](https://github.com/chapel-lang/chapel/blob/master/test/distributions/engin/SparseBlock/spsblkAssignment.chpl)
  - [x] [test_generic_class_of_sparse_domain.chpl](https://github.com/chapel-lang/chapel/blob/master/test/domains/deitz/test_generic_class_of_sparse_domain.chpl)
  - [x] [cg-sparse.chpl](https://github.com/chapel-lang/chapel/blob/master/test/npb/cg/bradc/cg-sparse.chpl)
  - [x] [cg-sparse-timecomp.chpl](https://github.com/chapel-lang/chapel/blob/master/test/performance/compiler/bradc/cg-sparse-timecomp.chpl)
  - [x] [sparse.chpl](https://github.com/chapel-lang/chapel/blob/master/test/release/examples/primers/sparse.chpl)
  - [x] [performance.chpl](https://github.com/chapel-lang/chapel/blob/master/test/sparse/CS/multiplication/performance.chpl)
  - [x] [performance.chpl](https://github.com/chapel-lang/chapel/blob/master/test/sparse/CS/resize/performance.chpl)
  - [x] [sparse.chpl](https://github.com/chapel-lang/chapel/blob/master/test/sparse/bradc/CSR/sparse.chpl)
  - [x] [sparse-csr-iter-dom-arr-zipper.chpl](https://github.com/chapel-lang/chapel/blob/master/test/sparse/parallel/sparse-csr-iter-dom-arr-zipper.chpl)
  - [x] [sparse.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/prk/Sparse/sparse.chpl)

Stencil arrays/domains:
  - [ ] [stencil.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/prk/Stencil/stencil.chpl)

DimensionalDist:
  - [ ] [hpl-vdb.chpl](https://github.com/chapel-lang/chapel/blob/master/test/chplvis/benchmarks-hpcc/hpl-vdb.chpl)
  - [ ] [s7.chpl](https://github.com/chapel-lang/chapel/blob/master/test/distributions/dm/s7.chpl)
  - [ ] [s8.chpl](https://github.com/chapel-lang/chapel/blob/master/test/distributions/dm/s8.chpl)
  - [ ] [s9.chpl](https://github.com/chapel-lang/chapel/blob/master/test/distributions/dm/s9.chpl)
  - [ ] [t1.chpl](https://github.com/chapel-lang/chapel/blob/master/test/distributions/dm/t1.chpl)
  - [ ] [t2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/distributions/dm/t2.chpl)
  - [ ] [t5a.chpl](https://github.com/chapel-lang/chapel/blob/master/test/distributions/dm/t5a.chpl)
  - [ ] [t8.chpl](https://github.com/chapel-lang/chapel/blob/master/test/distributions/dm/t8.chpl)
  - [ ] [t9.chpl](https://github.com/chapel-lang/chapel/blob/master/test/distributions/dm/t9.chpl)
  - [ ] [distributions.chpl](https://github.com/chapel-lang/chapel/blob/master/test/release/examples/primers/distributions.chpl)
  - [ ] [bc.md.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/hpcc/HPL/vass/bc.md.chpl)
  - [ ] [bl.md.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/hpcc/HPL/vass/bl.md.chpl)
  - [ ] [bug.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/hpcc/HPL/vass/bug.chpl)
  - [ ] [hpl.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/hpcc/HPL/vass/hpl.chpl)
  - [ ] [schurComplement.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/hpcc/HPL/vass/schurComplement.chpl)

**Comment by ben-albrecht** [comment]
The following program demonstrates a leak that likely explains majority of the `layoutCS`-related leaks:

```chpl
use layoutCS;

var dom = {1..100, 1..100};
var csrDom: sparse subdomain(dom) dmapped CS();
```

```
./leak --memLeaks
=================================================================================================================
Allocated Memory (Bytes)         Number   Size     Total    Description                      Address
=================================================================================================================
leak.chpl:4                      1        144      144      DefaultSparseDom(2,int(64),domain(2,int(64),false))0x00007faab1c03d40
leak.chpl:4                      1        112      112      [domain(1,int(64),false)] 2*int(64)0x00007faab1c03e80
leak.chpl:4                      1        80       80       domain(1,int(64),false)          0x00007faab1c03e00
leak.chpl:4                      1        96       96       domain(2,int(64),false)          0x00007faab1c03f70
leak.chpl:4                      1        24       24       listNode(BaseArr)                0x00007faab1c03f20
=================================================================================================================
```

**Comment by ben-albrecht** [comment]
> Nice minimal example! It appears that neither DefaultSparse.chpl nor LayoutCS.chpl contain any of the dsiDestroy*() routines, which could definitely explain that...

I observed this as well. However, the following the example does *not* leak:

```chpl
var dom = {1..100, 1..100};
var sparseDom: sparse subdomain(dom);
```

**Comment by bradcray** [comment]
Oh, that is weird.  @benharsh also noted that he didn't think it was so surprising that these didn't have destroy calls because everything should be cleaned up automatically (or, at least, it's plausible that they would be...).  I was thinking that because DefaultRectangular had them, others likely should as well, but he noted that DefaultRectangular's implementation is more primitive (it has to allocate/free ddatas).

**Comment by benharsh** [comment]
I think the leak is coming from here:

https://github.com/chapel-lang/chapel/blob/master/modules/internal/ChapelArray.chpl#L771

Here we create a temporary that is never destroyed. I think what we really want is to access the runtime type information of ``domainType`` directly, instead of creating a temporary. If I manually edit the generated code to do so the leak goes away (very limited use-case though).

**Comment by benharsh** [comment]
To avoid duplication of effort: I think I have a branch that fixes this sparse leak. It adds a compiler primitive that can get a field from the runtime type struct, and is used in the module code instead of a temporary:

https://github.com/benharsh/chapel/tree/dev-runtime-type-field

I'm seeing a complete reduction in leaks for ``npb/cg/bradc/cg-sparse.chpl``. I'm also seeing a major reduction in leaks for ``library/packages/LinearAlgebra/correctness/no-dependencies/correctness.chpl`` -- 26K to 480B.

I'm going to run this through memleaks and valgrind to see what comes back.

**Comment by benharsh** [comment]
Opened #11140 that significantly reduces the number of sparse-related leaks. With this branch I observed zero leaks of DefaultSparseDom.

**Comment by bradcray** [comment]
I split the Dimensional and Private cases out into their own issues (#12731 and #12732) because they seem relatively straightforward and separable from this bigger issue.  I also started going through to see which of these are still open, but timed out before completing.

**Comment by e-kayrakli** [comment]
As far as I can see, only a small portion of these leaks remain and they are due to https://github.com/chapel-lang/chapel/issues/15611

https://github.com/chapel-lang/chapel/issues/15623 has the summary of all memory leaks we have as of today.
