### ISSUE TITLE
Remaining string leaks

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#7892]
The following tests still leak string data. Some of the causes are likely related to records in general.

**Update**: Going into 1.20 (sha 44e05a0) we have two outstanding tests that leak string data:

- [x] [tuple-string-bug-noparens.chpl](https://github.com/chapel-lang/chapel/blob/master/test/types/tuple/ferguson/tuple-string-bug-noparens.chpl)
  (Resolved via #14102)
- [x] [packageName.chpl](https://github.com/chapel-lang/chapel/blob/master/test/mason/publish-tests/packageName.chpl)
  (The underlying issue is coming from error handling and captured in https://github.com/chapel-lang/chapel/issues/14058)

Fixed tests:

- [x] [test_glob.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/glob/test_glob.chpl)
- [x] [c_string-to-string.chpl](https://github.com/chapel-lang/chapel/blob/master/test/associative/thomasvandoren/c_string-to-string.chpl)
- [x] [genericArrayInClass-otharrs.chpl](https://github.com/chapel-lang/chapel/blob/master/test/classes/bradc/arrayInClass/genericArrayInClass-otharrs.chpl)
- [x] [associative.chpl](https://github.com/chapel-lang/chapel/blob/master/test/release/examples/primers/associative.chpl)
- [x] [findfiles-par.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/standard/FileSystem/filerator/bradc/findfiles-par.chpl)
- [x] [string-cast-leak.chpl](https://github.com/chapel-lang/chapel/blob/master/test/types/string/ferguson/string-cast-leak.chpl)

Following tests were testing a developer feature with leaky implementation. The feature and the tests are removed with #14067 :

- [x] [ref2string.chpl](https://github.com/chapel-lang/chapel/blob/master/test/trivial/bradc/ref2string.chpl)
- [x] [classRef2string.chpl](https://github.com/chapel-lang/chapel/blob/master/test/trivial/diten/classRef2string.chpl)
- [x] [wideref2string.chpl](https://github.com/chapel-lang/chapel/blob/master/test/trivial/bradc/wideref2string.chpl)

**Comment by cassella** [comment]
Only four of these tests (the first and the last three) still leak
when I tried them, all "string copy data":

{noformat}
tuple-string-bug-noparens.chpl
ref2string.chpl
classRef2string.chpl 
wideref2string.chpl
{noformat}

The rest didn't leak when I tried.


The last three use the function `chpldev_refToString()`.  The only
other tests that invoke this function are

``test/multilocale/deitz/needMultiLocales/test_chpldev_refToString_on_class.chpl``

which also leaks "string copy data", and

``test/trivial/diten/domArrRef2String.chpl``

which is presently a non-compiling future.

**Comment by cassella** [comment]
The last three can be considered to no longer leak as #14067 removed them, as well as the other two I mentioned above.

**Comment by e-kayrakli** [comment]
Thanks @cassella! I have updated the original post with what we have currently on master.

**Comment by e-kayrakli** [comment]
We don't have any string (or bytes) leaks remaining. Closing.
