### ISSUE TITLE
Iterator class memory leaks

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#7897]
This issue exists to track and discuss the leaking of iterator classes (`_ic_chpl_*`):

- [x] [nested_fors.chpl](https://github.com/chapel-lang/chapel/blob/master/test/trivial/deitz/statements/nested_fors.chpl)
- [x] [nested_fors2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/trivial/deitz/statements/nested_fors2.chpl)
- [x] [diffDomZip.chpl](https://github.com/chapel-lang/chapel/blob/master/test/associative/bharshbarg/arrays/diffDomZip.chpl)
- [x] [test_domain_follower.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/deitz/iterators/leader_follower/test_domain_follower.chpl)
- [ ] [plus-reduce-assoc.chpl](https://github.com/chapel-lang/chapel/blob/master/test/associative/ferguson/plus-reduce-assoc.chpl)
- [ ] [reduceArrOfAssocDom.chpl](https://github.com/chapel-lang/chapel/blob/master/test/associative/bharshbarg/domains/reduceArrOfAssocDom.chpl)
- [ ] test/trivial/sidelnik/reduction.chpl
- [x] [LeakedMemory6.chpl](https://github.com/chapel-lang/chapel/blob/master/test/memory/figueroa/LeakedMemory6.chpl)
- [x] [jacobi-unoptimized.chpl](https://github.com/chapel-lang/chapel/blob/master/test/arrays/deitz/jacobi-unoptimized.chpl)
- [x] [jacobi-no-inline.chpl](https://github.com/chapel-lang/chapel/blob/master/test/arrays/deitz/jacobi-no-inline.chpl)
- [x] test/library/packages/VectorList/test-pariter.chpl

**Comment by bradcray** [comment]
This may relate to work that @mppf is pursuing w.r.t. iterator record cleanup.

**Comment by e-kayrakli** [comment]
#15612 seems to be the cause of the remaining leaks today.

#15623 has the summary of all memory leaks we have as of today.
