### ISSUE TITLE
Leaks in tests due to user error

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#7898]
This issue exists to track and discuss tests that leak because the user did not delete a class. In some of these cases the solution is obvious: just add a delete. In other cases it is not easy to add a delete without potentially changing the behavior of the test (e.g. ``new C().foo()``). If a test is intended to leak, we should be skipping it under memleaks testing.

- [x] [partial_reduction_support/](https://github.com/chapel-lang/chapel/blob/master/test/users/engin/partial_reduction_support/)
- [x] [class-alias-generic-arg-concrete.chpl](https://github.com/chapel-lang/chapel/blob/master/test/classes/ferguson/class-alias-generic-arg-concrete.chpl)
- [x] [across-scopes.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/ferguson/ref-pair/across-scopes.chpl)
- [x] [forallPromotes2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/promotion/forallPromotes2.chpl)
- [x] [test_block_array_of_ints_assigned_class_field.chpl](https://github.com/chapel-lang/chapel/blob/master/test/arrays/deitz/test_block_array_of_ints_assigned_class_field.chpl)
- [x] [modifyReturnedClass.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/bradc/retConstness/modifyReturnedClass.chpl)
- [x] [all_precedence_levels_in_a_single_expression.chpl](https://github.com/chapel-lang/chapel/blob/master/test/trivial/deitz/expressions/all_precedence_levels_in_a_single_expression.chpl)
- [x] [forallPromotes3.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/promotion/forallPromotes3.chpl)
- [x] [tup-primitive.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/standard/Types/tup-primitive.chpl)
- [x] [recursive-iter-works.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/iterators/recursive/recursive-iter-works.chpl)
- [x] [itoverride.chpl](https://github.com/chapel-lang/chapel/blob/master/test/users/thom/itoverride.chpl) (check with --baseline)
- [x] [test_dd4.chpl](https://github.com/chapel-lang/chapel/blob/master/test/classes/deitz/dispatch/test_dd4.chpl)
- [x] [forwarding-generic-default.chpl](https://github.com/chapel-lang/chapel/blob/master/test/classes/forwarding/forwarding-generic-default.chpl)
- [x] [test_class_of_distributed_array.chpl](https://github.com/chapel-lang/chapel/blob/master/test/distributions/robust/arithmetic/basics/test_class_of_distributed_array.chpl)
- [x] [learnChapelInYMinutes.chpl](https://github.com/chapel-lang/chapel/blob/master/test/release/examples/primers/learnChapelInYMinutes.chpl)
- [x] [ra.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/hpcc/RA/diten/ra.chpl)
- [x] [CoMD.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/comd/elegant/arrayOfStructs/CoMD.chpl)
- [x] [dynamicDispatchIterator3Levels.chpl](https://github.com/chapel-lang/chapel/blob/master/test/functions/iterators/diten/dynamicDispatchIterator3Levels.chpl)
- [x] [linkedList.chpl](https://github.com/chapel-lang/chapel/blob/master/test/release/examples/programs/linkedList.chpl)
- [x] [tdata-test.chpl](https://github.com/chapel-lang/chapel/blob/master/test/runtime/ferguson/tdata-test.chpl)
- [x] [gmp_random.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/standard/GMP/ferguson/gmp_random.chpl)
- [x] [c-ray.chpl](https://github.com/chapel-lang/chapel/blob/master/test/exercises/c-ray/forStudents/c-ray.chpl)
- [x] [cyclicOnEvenNumLocales.chpl](https://github.com/chapel-lang/chapel/blob/master/test/distributions/jglewis/cyclicOnEvenNumLocales.chpl)

**Comment by bradcray** [comment]
Maybe the right way to handle these cases efficiently would be to identify obvious "owners" for each of these and have people work them as a background task (while testing runs, e.g.).

I'd be happy to take any tests that are "mine" in this list (where one obvious one jumps out based on looking for my name: modifyReturnedClass.chpl).  I'd also be willing to help out with tests be people who are no longer members of the team.

**Comment by bradcray** [comment]
From what I'm seeing, none of these tests are leaking anymore (as of some of today's merged PRs).  I've also scanned all of the leaking cases and believe I've eliminated most cases that are obviously user leaks.  I'll take another pass looking for user leaks after tomorrow's leak tests come in, but believe that we're far enough along with the effort that this issue can be closed for now.
