### ISSUE TITLE
Miscellaneous record leaks

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#7899]
The following tests are suspected to be leaking due to incorrect/incomplete record semantics (e.g. copying).

- [x] [list-scoped-no-use.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/standard/List/list-scoped-no-use.chpl)
- [x] [list-scoped-use.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/standard/List/list-scoped-use.chpl)
- [x] [test_typevar_record3.chpl](https://github.com/chapel-lang/chapel/blob/master/test/types/type_variables/deitz/part2/test_typevar_record3.chpl)
- [x] [test_typevar_record4.chpl](https://github.com/chapel-lang/chapel/blob/master/test/types/type_variables/deitz/part2/test_typevar_record4.chpl)
- [x] [test_typevar_record5.chpl](https://github.com/chapel-lang/chapel/blob/master/test/types/type_variables/deitz/part2/test_typevar_record5.chpl)
- [x] [test_typevar_record6.chpl](https://github.com/chapel-lang/chapel/blob/master/test/types/type_variables/deitz/part2/test_typevar_record6.chpl)
- [ ] [classInRecord.chpl](https://github.com/chapel-lang/chapel/blob/master/test/types/records/sungeun/classInRecord.chpl)
- [ ] [expiring-value-alias.chpl](https://github.com/chapel-lang/chapel/blob/master/test/types/records/ferguson/expiring-value-alias.chpl)
- [x] [newInit-record-class.chpl](https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/generics/phase1/newInit-record-class.chpl)

Failure to deinit:
- [x] [bfs.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/parboil/BFS/bfs.chpl)

**Comment by e-kayrakli** [comment]
`classInRecord.chpl` is the only remaining leak and will be closed via https://github.com/chapel-lang/chapel/pull/15614
