### ISSUE TITLE
Close known compiler/library memory leaks

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#7900]
This is a meta issue intended to be used as an index into other memory leak issues:

- Distributions, domains, and arrays #7891
- First-class functions #7890 
- Strings #7892 
- IO #7893 
- Standard/package modules
  - DateTime #7894 
- Reductions #7896 
- Iterator classes #7897 
- Records #7899 
- User-error #7898

**Comment by e-kayrakli** [comment]
The story on memory leaks is much better today. #15623 is a meta-issue that links to particular bug reports that cause known leaks.
