### ISSUE TITLE
Copy initializers with extra optional arguments aren't considered

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#7932]
### Summary of Problem

A copy initializer that has additional optional arguments (with default values) is not considered as it seems it should be.

### Steps to Reproduce

**Associated Future Test(s):**
[`test/types/records/init/copy/copyWithDefaultArgs.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/types/records/init/copy/copyWithDefaultArgs.chpl
          ) #7920

### Configuration Information

- Output of `chpl --version`: `chpl Version 1.17.0 pre-release (6c08a44)`

**Comment by bradcray** [comment]
We use this pattern in the string module currently, so to convert it from constructors to initializers in the most obvious way, we'd need to resolve this.

**Comment by bradcray** [comment]
I hadn't realized until just now when I was taking stock of things, but... it looks like this has been resolved and can be closed?  (@lydia-duncan?)

**Comment by lydia-duncan** [comment]
Yup!  I'll take care of it (I meant to earlier, but wanted to make sure testing didn't blow up)
