### ISSUE TITLE
Fields with conditional fields / initializers break initializers

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#7933]
### Summary of Problem

When the field of a record uses a conditional expression to define its type of its field initialization expression, it causes problems in compilation.

### Steps to Reproduce

**Associated Future Test(s):**
[`test/types/records/init/condFieldInit.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/types/records/init/condFieldInit.chpl
          ) #7921
[`test/types/records/init/condFieldType.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/types/records/init/condFieldType.chpl
          ) #7921

### Configuration Information

- Output of `chpl --version`: `chpl Version 1.17.0 pre-release (6b9b3b7)`

**Comment by bradcray** [comment]
We use this pattern in the range module currently, so to convert it from constructors to initializers in the most obvious way, we'd need to resolve this.

**Comment by lydia-duncan** [comment]
Should be resolved by #8033
