### ISSUE TITLE
Internal error: CAL0120

### ISSUE THREAD

**Issue by nspark** [chapel-lang/chapel#7937]
### Summary of Problem

The included source produces the `CAL0120` internal error. Though not a user-facing feature, setting `CHPL_DEVELOPER=1` and recompiling doesn't help isolate the error. (This error was encountered when the function was defined in separate module file, which made it less obvious to spot.)

### Steps to Reproduce

**Source Code:**

```chapel
proc oops(A, B) {
  return A + B;
}
writeln("oops = ", oops);
```

**Compile command:**
`chpl error.chpl`

### Configuration Information

- Output of `chpl --version`: 1.16.0

**Comment by ben-albrecht** [comment]
Interestingly, making the return-type concrete results in the correct error message:

```chpl
proc oops(A, B) {
  return 1;
}
writeln("oops = ", oops);
```

```bash
oops.chpl:4: error: Generic functions can't be captured as values
```
