### ISSUE TITLE
should Chapel support promotion caused by a default argument?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#7940]
Consider the test here: test/functions/deitz/test_default_promote_instantiate.chpl, a simplified version of which is reproduced below:

 ``` chapel
proc foo(x: int = 1..3) {
  writeln(x);
}

foo();
```

This test relies on the default-argument-wrapper behavior of master (before #7858, at least) and the .good file expects the default argument to cause the zero-argument call to `foo` to be a promoted call like `foo(1..3)`.

My mental model for how promotion and default arguments interact involves two conceptual transformations, from the discussion over on #7889. My understanding from that issue is that we imagine doing the promotion transformation (i.e. turn it in to a forall loop) before doing the default arguments transformation (i.e. supply arguments with the default expressions). But that model doesn't allow the functionality that this test checks for:

 * original program
    ```chpl
    foo();
    ```
 * after promotion transformation (there is no promotion if there are no arguments, right?)
   ```chpl
   foo();
   ```
 * after default argument transformation
    ```chpl
   foo(1..3); // error: can't call foo(integral) with 1..3
    ```

Hence I am advocating that we make this test result in compilation error.

**Comment by ronawho** [comment]
I'm in favor of making it a compiler error too. 

To me this is no different from trying to do:

```chpl
var i: int = 1..3;
```

**Comment by bradcray** [comment]
I agree that a formal's default value should not be allowed to promote the argument.  (and with what Elliot said as I was typing this).

**Comment by vasslitvinov** [comment]
This existing behavior could be defensible if there were a compelling use case.
In its absence I will be happy to see it go.
