### ISSUE TITLE
Feature request: Inbuilt JSON parser

### ISSUE THREAD

**Issue by saru95** [chapel-lang/chapel#7949]
A JSON parser built into the Chapel standard library could really help out with a lot of things such as HTTP Server, serde, etc.

eg.

```chpl

use chplJSON;

var x = "{ 'a': 1, 'b': 2 }"'

var y = JSON.parse(x, 'RFC4627'); //2nd argument is optional (may contain RFC7159, ECMA-404, and other standards)

writeln(y.domain); // gives ['a', 'b']
writeln(y); // gives [1, 2]
```

If this is of some interest, I could also look into developing a Chapel binding for Google's GSON.

In addition, we could also have a common module which parses various files such as csv, tsv, json, etc.

Another option would be to parse JSON into a class:

eg. 

```chpl
use chplJSON;

class DemoClass {
  var a: int;
  var b: int;
}
var x = "{ 'a': 1, 'b': 2 }"'

var y = JSON.parse(x, objectHook=DemoClass);

writeln(y.a); // gives 1
writeln(y.b); // gives 2
```

**Comment by ben-albrecht** [comment]
This is currently supported in the [IO module](https://chapel-lang.org/docs/master/modules/standard/IO/FormattedIO.html#general-conversions) with the `%jt` (json) type specifier in formatted read/write, e.g.

```chpl
class DemoClass {
  var a: int;
  var b: int;
}

// Writing to a memory buffer instead of a file...
var mem = openmem();

// Writer
var w = mem.writer();

// DemoClass instance to write
var x = new DemoClass(1, 2);

// Writes:
// {"a":1, "b":2}
w.writef("%jt\n", x);

// Reader
var r = mem.reader();

// DemoClass instance to read
var y = new DemoClass();

// Populates values
r.readf('%jt', y);

writeln(y.a); // gives 1
writeln(y.b); // gives 2

// Clean up
delete(x);
delete(y);
w.close();
r.close();
mem.close();
```

That said, there is still an open question as to whether or not we should continue along the route of formatted IO to handle other formats such as csv, tsv, etc, or pursue something different, such as a module-per-format such as you've proposed for `JSON`.

#7846 is intended to explore this open question.
