### ISSUE TITLE
param argument with value default results in internal error

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#7956]
The following program results in an internal error but should result in a user-facing one.

```chapel
var globalOne = 1;

proc param_notparam(param x = globalOne) {
}

param_notparam();
```

**Associated Future Test(s):**
test/functions/default-arguments/default-argument-param-not.chpl

**Comment by cassella** [comment]
#8254/#8272 added a user-facing error for this problem, but not the one in this future's .good file.

I opened #14168 to remove this future as those PRs also added a test that duplicates it and locks in the user error.

**Comment by cassella** [comment]
I believe this issue can be closed now.
