### ISSUE TITLE
Internal error in initializer resolution

### ISSUE THREAD

**Issue by nspark** [chapel-lang/chapel#7960]
### Summary of Problem

When compiling a generic record that calls `this.init(...)`, I see an internal error (`INI0061`) in initializer resolution.

### Steps to Reproduce

**Source Code:**

```chapel
// bug.chpl
record Foo {
  type idxType;
  var D: domain(1, idxType);
  proc init(type idxType, space: range) {
    this.idxType = idxType;
    this.D = space;
    super.init();
  }
  proc init(type idxType, size: idxType) {
    this.init(idxType, 0..#size);
  }
}
var foo = new Foo(int, 10);
```

**Compile command:**
`chpl bug.chpl`

**Futures**
[test/classes/initializers/records/generics/siblingCall-generic.chpl](https://github.com/chapel-lang/chapel/tree/master/test/classes/initializers/records/generics/siblingCall-generic.chpl) #7969 
[test/classes/initializers/records/generics/siblingCall-moreComplex.chpl](https://github.com/chapel-lang/chapel/tree/master/test/classes/initializers/records/generics/siblingCall-moreComplex.chpl) #7969

### Configuration Information

- Output of `chpl --version`: 1.17.0 pre-release (febd6ff)

**Comment by lydia-duncan** [comment]
At a guess, this is a bug with our handling of range declarations, or range declarations of that form.  I'll look into this shortly, thanks for reporting!

**Comment by lydia-duncan** [comment]
Oh, weird.  This seems to be limited to records only.  The same code works just fine for classes.
