### ISSUE TITLE
Create a canonical set of chapel vs. reference performance graphs

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#7967]
Create a canonical set of performance/scalability graphs for comparing to reference versions and make it easier to gather/graph them. 

We have a lot of nightly performance testing, but we mostly just compare Chapel performance. At release time we then gather reference timings and create graphs to compare Chapel against reference versions. This gathering and graph compilation is still somewhat manual. 

We end up using these graphs in talks, but the graphs end up being pretty inconsistent because they often show different chpl versions, use different colors schemes, and some are generated with gnuplot while others are made with excel. It'd be nice to present more consistent graphs and make the performance gathering and graph generation more automated.

Here's the current list of graphs I think we want to be able to easily gather:
 - stream (global and ep) vs reference
 - ra atomics (w/ and w/o oversubscription) vs ref w/ and w/o bucketing
 - ISX vs reference 
 - Stencil PRK vs reference

**Comment by bradcray** [comment]
I don't know how hard this is to do, but a lot of the graphs I show from MS reports put the legend down below the x-axis in a horizontal sequence of keys.  To me, this makes the key hard to see and obscures the clarity of the x-axis label.  When creating graphs manually using Powerpoint or Google sheets, I tend to put the legend to the right of the graph or (ideally) somewhere in a box on the graph itself with the entries in a vertical stack.

**Comment by ronawho** [comment]
I believe this is done now. It's still not quite fully automated, but we can create the set of lcals, stream, ra, prk-stencil, and isx graphs pretty easily now.

![lcals-ser-time-excel](https://user-images.githubusercontent.com/1588337/41611532-fc0e6bfa-73a4-11e8-8211-c807e9f09d36.png)

![stream-perf](https://user-images.githubusercontent.com/1588337/41611500-e49c3420-73a4-11e8-9074-7867235c5529.png)

![ra-perf](https://user-images.githubusercontent.com/1588337/41611495-e1d69fdc-73a4-11e8-97b5-b16b1d8520af.png)

![prk-stencil-perf](https://user-images.githubusercontent.com/1588337/41611493-df436426-73a4-11e8-8e39-61c5b507c71e.png)


![isx-time](https://user-images.githubusercontent.com/1588337/41611491-dd4f29d4-73a4-11e8-92b3-fe3979054c5d.png)
