### ISSUE TITLE
Useless promoted cast to enum causes illegal cast error

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#7991]
Normally, a cast of a type to itself does nothing. Furthermore, a cast can be promoted when provided with an array element. But, a useless promoted cast to an enum type causes an internal compiler error when it should do nothing.

``` chapel
enum myenum {
  ONE=1,
  TWO=2,
  THREE=3
}
use myenum;

var A:[1..3] myenum = [ONE, TWO, THREE];
writeln(A);

var B = A:int;
writeln(B);

var C = B:int; // this useless cast is promoted, makes C = B.
writeln(C);

var D = C:myenum; // demonstrating cast to enum can be promoted
writeln(D);

var F = A:myenum; // results in compilation error
writeln(F);
```

causes error
```
useless-promoted-cast.chpl:20: error: illegal cast from [domain(1,int(64),false)] myenum to myenum
```

**Comment by bradcray** [comment]
While working on issue #9221, I was curious about this one so wanted to see what I could learn in 10 minutes or so.  Everything similar that I tried seemed to work, which led me to the solution in PR #10379.  Testing now.
