### ISSUE TITLE
extern types don't have default values

### ISSUE THREAD

**Issue by psahabu** [chapel-lang/chapel#7992]
I was ambushed by this while working on #7908. In `IO.chpl`, my function `file.check(out error: syserr)` was causing `hello.chpl` to segfault. The generated code was not default initializing the `syserr` formal, leading to garbage memory in the `out error` and cascading failures after that.

While I've managed to create a workaround for this issue, we should still consider giving default values to extern types such as `syserr`. Here's an example:

``` chapel
proc test() {
  var x:syserr;
  writeln(x:int);
}

test();
```

output:
```
Segmentation fault: 11
```

**Comment by bradcray** [comment]
This seems like a language design issue, true?
Shot in the dark, but would defining a `proc syserr.init()` help with this at all?

**Comment by mppf** [comment]
@bradcray - I believe we can make a _defaultOf for syserr, which makes sense because that's an internal type. I think Preston is going to try that.

For general extern types, I think we should 'memset' them to 0, but I agree that is a language design question.

**Comment by bradcray** [comment]
OK, thanks.  `_defaultOf` is the old world, though, right?  (i.e., expected to go away with constructors)

**Comment by mppf** [comment]
@bradcray - maybe, I don't personally know the answer to that. Do we plan to deprecate it for say providing the default value of `int`? (I.e. we don't normally talk about initializers for non-class non-records).

**Comment by psahabu** [comment]
@bradcray, @mppf: Unfortunately it was not straightforward to add `_defaultOf` for `syserr`. My guess is that may be due to the fact that `syserr` gets resolved or otherwise modified to an `int(32)` at some point during compilation, which may be preventing `_defaultOf` from acting in time.

I've stashed my changes locally until I have more time to investigate.

**Comment by bradcray** [comment]
Tagging @lydia-duncan on this due to her involvement in both `_defaultOf` and initializers (noting that it's not a gating issue).

**Comment by lydia-duncan** [comment]
We would like to get rid of or change _defaultOf into something that isn't so hokey, but that will likely be an additional step after deprecating constructors.  And Michael's point about `int` is a good one - I think we originally discussed initializers on primitive types but it wasn't as high a priority as getting them to work for classes/records

I would have to dive through old notes to remember our exact plan for _defaultOf going forward, though

**Comment by mppf** [comment]
I ran into this issue again (when working on improving out intents). AFAIK it's not possible for users to write an initializer for an extern type today. However the compiler doesn't raise an error when declaring a variable of extern type. It's simply just not initialized.

**Comment by bradcray** [comment]
Refreshing my memory on the past discussion around this issue, I'd be open to memsetting declarations of variables of extern types to 0 if that's tractable and not too large of an effort.  My instinct for how this should be supported within the language remains "via initializers."  E.g., I'd expect users to be able to write something like the following:

```chapel
extern type float;
proc float.init() {
  this = 9.9;
}
var x: float;
writeln(x);
```

**Comment by mppf** [comment]
To be clear - it's not blocking me - I've found a way around it for the moment.

>  I'd be open to memsetting declarations of variables of extern types to 0

I don't think this would be particularly hard at it seems reasonable to me.

> My instinct for how this should be supported within the language remains "via initializers."

The main hiccup here is that today we don't have any concept for initializers for non-record non-class types. That isn't necessarily a large conceptual issue but it's likely to require a bunch of compiler effort.

**Comment by mppf** [comment]
Here is an example using an extern record:

``` chapel
extern {
  struct mystruct {
    int x;
  };
}

proc test1() {
  var st: mystruct;
  writeln(st.x);
}
test1();
```

**Comment by bradcray** [comment]
I think it'd be acceptable if this example printed out whatever happened to be in `st.x`'s memory on the argument that it's an extern record type and C doesn't say anything about how structs are initialized.  I think it might be nicer to have any Chapel-declared variables of extern record type have their memory memset to 0 for safety/consistency reasons (and it happens to match the default values for most/all our POD types?).  Ultimately, I could imagine it being attractive to permit someone to write `proc mystruct.init()` to attach a default initializer with different behavior to an external record (with the understanding that it would only fire for new instances of that record created by Chapel).
