### ISSUE TITLE
Confusion on Chapel inheritance and overrriding class methods

### ISSUE THREAD

**Issue by nspark** [chapel-lang/chapel#8062]
### Summary of Problem

I was trying out class inheritance in Chapel and was surprised by one case, shown below.

### Steps to Reproduce

**Source Code:** (also on [Try It Online](https://tio.run/##jY1BDsIgFET3nGLSFWzsvo1x4QW8AqEkkCAlUGVhenZEfmvqzr@cefO@MjJoV4pyMiXcZNR@wYsBIc4K2czybrloCZCjXbTzvCOuE2ONV7YyRvOrsW4a/rY0/CB5ygj1yXCG15l0vPYtPO2aEd/re4IYb8hAn8UBrQS/iM2QHkHHX0/taVTKGw))

```chapel
class Parent {
  proc whoami() {
    writeln("Parent");
  }
}

class Child: Parent {
  proc whoami() {
    writeln("Child");
  }
}

var child = new Child();
child.whoami();          // Child
(child:Parent).whoami(); // (?)
child.super.whoami();    // Parent
```

**Execution output:**
```
Child
Child
Parent
```

I was surprised that calling `(child:Parent).whoami()` did not invoke `Parent.whoami()`, but rather `Child.whoami()`. Is this expected behavior? If so, is the only way to access a parent method via `super()`?

### Configuration Information

- Output of `chpl --version`: `chpl Version 1.17.0 pre-release (-999)` (from tio.run)

**Comment by mppf** [comment]
> I was surprised that calling (child:Parent).whoami() did not invoke Parent.whoami(), but rather Child.whoami(). Is this expected behavior? If so, is the only way to access a parent method via super()?

I'm surprised that `child.super.whoami()` runs the Parent version - or that it can be run outside of a method at all. I'd expect that `child.super` only work in the body of a method. @lydia-duncan - thoughts?

As far as  (child:Parent).whoami(), that is equivalent to
``` chapel
var asParent:Parent = child;
asParent.whoamai()
```

Either way, what's happening is that child:Parent or the creation of the `asParent` variable in my example create the same class instance pointer as `child` but store it in a value of type `Parent`. Since `whoami` is subject to virtual dispatch (it's overridden, and we're talking about classes), calling that method on that instance (whether the instance is stored in a variable of type Parent or Child) results in virtual dispatch which uses the run-time type information (i.e. that it's pointing to a Child) to determine which method to run.

**Comment by lydia-duncan** [comment]
I don't think we've ever inserted explicit checks that `super` is only used within a method.  That seems like a reasonable TODO, though.

**Comment by noakesmichael** [comment]
I don’t completely understand the status of “super” in Chapel
but I can see an argument for treating “super” as an effective
field of any class instance and hence accepting accepting
child.super.whoami().


This view is partly supported by my poor understanding of
“super” in Java.








On Dec 18, 2017, at 2:56 PM, Lydia Duncan <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't think we've ever inserted explicit checks that super is only used within a method. That seems like a reasonable TODO, though.

**Comment by mppf** [comment]
Re. what `super` does in Java, I created this experiment:

``` java
// Parent.java
public class Parent {
   public void hello() {
      System.out.println("in Parent.hello");
   }
}
```

``` java
// Child.java
public class Child extends Parent {
   public void hello() {
      super.hello();
      System.out.println("in Child.hello");
   }

   public static void main(String[] args) {
      Child aChild = new Child();
      System.out.println("aChild.hello");
      aChild.hello();
      System.out.println("((Parent)aChild).hello");
      ((Parent)aChild).hello();
      Parent asParent = aChild;
      System.out.println("asParent.hello");
      asParent.hello();

      // Question: can super be used outside of a method?
      // aChild.super.hello();
   }
}
```

``` sh
$ javac Parent.java Child.java
$ java Child
aChild.hello
in Parent.hello
in Child.hello
((Parent)aChild).hello
in Parent.hello
in Child.hello
asParent.hello
in Parent.hello
in Child.hello
```

(In other words, in Java, the equivalent of `(child:Parent).whoami();` returns `Child`).

If I uncomment out the ` aChild.super.hello();`, the javac command gives this error:
```
Child.java:18: error: cannot find symbol
      obj.super.hello();
      ^
  symbol:   class obj
  location: class Child
1 error
```

I don't think it makes sense to support `super` on anything other than `this` (or the implicit `this` field). Java doesn't.

**Comment by nspark** [comment]
@noakesmichael said (via email):

> I am surprised that you are surprised and so I wonder what you are seeing that I am missing?

After reading your email and the thread here, I'm a bit surprised that I'm surprised too! Honestly, I'm not deeply steeped in OOP, so that's likely the main source of my confusion.

> I don't think we've ever inserted explicit checks that `super` is only used within a method. That seems like a reasonable TODO, though.

@lydia-duncan I figured I would try it and was surprised that it worked. I understand if it's not _intended_ to work, though.

> (In other words, in Java, the equivalent of `(child:Parent).whoami();` returns `Child`).

@mppf @noakesmichael Maybe Java is more the OO model of Chapel than C++? I haven't worked with Java enough (or in long enough) to know how it's different from C++. When I first tried this Chapel example (and was surprised), I wrote what I thought was an equivalent version in C++ and got what I expected (also on [Try It Online](https://tio.run/##nZDBSsQwEIbv8xTDCkt70PXc1r34Aj6AIHFS7ECbhiZVRPrsdZrZsO5hUcwhGfrP900T8v6WeuPe1vWGHfWzbbHhMcSpNcMRQLIQ8MlMrYv4BX5@7ZkqQHwf2eJHN5qBi60uJUVZIdqqonGO2DS4U/DZ7WoJF1jqbHzsuLcVqu///qS50CfOcvAmUlecxHsRqUCKu5O1rGEBYIkHw06HwNaTpEjbvnmzw@v5kBOJUnX24ZV1OKhTCJX8igihYwWxn0566YVMiI1@3R@LNLr8IbpA8v21609TMqJ/eI05I8JMbZwnh/fykOv6DQ)):

```c++
#include <iostream>

class Parent {
public:
  void whoami(void) {
    std::cout << "Parent\n";
  }
};

class Child: public Parent {
public:
  void whoami(void) {
    std::cout << "Child\n";
  }
};

void dispatch(Parent &who) {
  who.whoami();
}

int main(void)
{
  Child child;
  Parent &parent = child;

  child.whoami();                        // Child
  parent.whoami();                       // Parent
  dynamic_cast<Parent&>(child).whoami(); // Parent
  dispatch(child);                       // Parent
  dispatch(parent);                      // Parent

  return 0;
}
```

It's only if I add:

```c++
void dispatch(Parent &who) {
  who.whoami();
}
```

that `dispatch(child);` will print `Child`.

**Comment by mppf** [comment]
@nspark - that C++ example should be using 'virtual' to be the equivalent of the Chapel example.

[TIO](https://tio.run/##nZDBSsQwEIbv8xTDCkt70PXc1r34Aj6AIHFS7ECbhiZVRPrsdZrZsO5hUcwhGfrP900T8v6WeuPe1vWGHfWzbbHhMcSpNcMRQLIQ8MlMrYv4BX5@7ZkqQHwf2eJHN5qBi60uJUVZIdqqonGO2DS4U/DZ7WoJF1jqbHzsuLcVqu///qS50CfOcvAmUlecxHsRqUCKu5O1rGEBYIkHw06HwNaTpEjbvnmzw@v5kBOJUnX24ZV1OKhTCJX8igihYwWxn0566YVMiI1@3R@LNLr8IbpA8v21609TMqJ/eI05I8JMbZwnh/fykOv6DQ)

Chapel is different from C++ in that any overridden method in a class will be virtually dispatched. In C++ you have to request that with `virtual`.

**Comment by nspark** [comment]
Thanks, @mppf!

**Comment by lydia-duncan** [comment]
I opened #8069 to track the `super` functionality @nspark pointed out.

**Comment by bradcray** [comment]
> Maybe Java is more the OO model of Chapel than C++?

I think that's accurate.  For a long time we've said "Think of Chapel records as C++ structs and Chapel classes as Java classes."  Though I'm sure we could find ways in which we differ from Java as well.
