### ISSUE TITLE
Is it okay to use autoCopyMap for the implementation of copy initializers, for now?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#8066]
Currently, the implementation of copy initializers inserts a call to a copy initializer as the sole contents of the initCopy generated for the type.  It does this during resolution (prior to when we know a copy is needed), resolves it, and stores that function into autoCopyMap.  This can lead to errors at function resolution if what is recognized as a copy initializer is not actually a copy initializer or if the copy initializer is missing. Ideally, if no copies will be made of the type, errors with the copy initializer won't be reported.

Is it acceptable - for the near term - to continue to use a map of copy initializers in order to reduce the effort of implementing copy initializers compiler? In particular this means that the compiler will try to resolve copy initializers in some cases where they might not actually be called.

**Comment by lydia-duncan** [comment]
@mppf - did I capture this correctly?

**Comment by bradcray** [comment]
I don't have an informed opinion on how it's implemented as long as we can write the code that we want/need to.  That said, "the compiler will try to resolve copy initializers in some cases where they might not actually be called" suggests that not all cases might work as expected/desired?

**Comment by mppf** [comment]
> That said, "the compiler will try to resolve copy initializers in some cases where they might not actually be called" suggests that not all cases might work as expected/desired?

Yes, that's right. But the cases that won't work as expected/desired will involve types that intentionally don't have a copy initializer. Right now `Owned` is that way, but it might not be in the future, and in any case it's a pretty weird thing to do for a record. It would be doubly-weird if we generate a "last resort" copy initializer for records (which is what I think we are leaning towards in #8065).

**Comment by lydia-duncan** [comment]
Closing, general consensus seems to be okay with this direction for now
