### ISSUE TITLE
dsiAssignDomain missing from Domain Map Standard Interface documentation

### ISSUE THREAD

**Issue by ian-bertolacci** [chapel-lang/chapel#8080]
dsiAssignDomain is a method required by the DSI, but is not described in the [DSI](https://chapel-lang.org/docs/latest/technotes/dsi.html) documentation.
It's also not mentioned [anywhere else](https://chapel-lang.org/docs/latest/search.html?q=dsiAssignDomain&check_keywords=yes&area=default) in the documentation site.

It looks like this is a recent change (080417e17098d0cc3fbadfbf86240ffc511984d7) but has not made it's way into the documentation, or the latest build of the documentation site.

**Comment by ian-bertolacci** [comment]
Hm. This is odd. The cited commit (080417e17098d0cc3fbadfbf86240ffc511984d7) does actually add a bit about dsiAssignDomain to doc/rst/technotes/dsi.rst (see [this](https://github.com/chapel-lang/chapel/commit/080417e17098d0cc3fbadfbf86240ffc511984d7#diff-557ca0d9e98ce0b26315044e79538d4cR239)), but the HEAD version of doc/rst/technotes/dsi.rst does not have that at all.

It looks like this file has a short history, but this commit is not part of it.
The earliest commit on doc/rst/technotes/dsi.rst is e2473776ad0aa8dca4412c03e6e001aea6fae396, but thats in March and 080417e17098d0cc3fbadfbf86240ffc511984d7 is in January.
e2473776ad0aa8dca4412c03e6e001aea6fae396 looks like some kind of move that moved doc/technotes/dsi.rst to doc/rst/technotes/dsi.rst (github says "without changes").
Did something get borked?
Could other documents affected?

**Comment by cassella** [comment]
git log --graph --oneline shows (in part)

```
* | | | | | | 1f7e117 Merge pull request #6722 from daviditen/update-pr-5296
|\ \ \ \ \ \ \
| |_|_|/ / / /
|/| | | | | |
| * | | | | | d0df714 Call dsiAssignDomain and _reprivatize with _instance, not _value
| * | | | | | 1d27529 Call dsiAssignDomain through _value, not through _instance
...
| * | | | | | 9f22125 Update ArrayViewRankChangeDom to remove common params and add dsiAssignDomain
| * | | | | |   4738132 Update PR #5296 to the current sources
| |\ \ \ \ \ \
| | * | | | | | a86e855 fix tabs
| | * | | | | | 78ca3cd always use _instance when calling dsiAssignDomain
| | * | | | | | 0992a74 Revert "Remove call to _reprivatize from domain assignment"
| | * | | | | | c65e0c1 Remove call to _reprivatize from domain assignment
| | * | | | | |   de8dc89 Merge remote-tracking branch 'upstream/master' into irregular-domain-assign
| | |\ \ \ \ \ \
| | * | | | | | | 253a1fc Prefix assignDomain... helper fns with chpl_
| | * | | | | | | fb8e373 Update comments
...
| | * | | | | | | e1a7c88 Fix problem with addAllToVirtualMaps
| | * | | | | | | a15c19c Non-working prototype
| | * | | | | | | 080417e Allow domain implementations to write domain assignment.
```

The last commit there, 080417e, is the one that added the note.  By
inspection, it survived through (a86e855 fix tabs), but disappeared
after the merge from master that included the rename (4738132
Update...), before the branch was merged to master.  The note never
made it to master.

**Comment by benharsh** [comment]
@daviditen or @mppf might be able to help.

**Comment by daviditen** [comment]
I just merged PR #8104 to add this documentation to the DSI technote.  Thanks @ian-bertolacci and @cassella for catching this and tracking it down.

**Comment by ian-bertolacci** [comment]
When will the documentation website (chapel-lang.org/docs) be rebuilt with this?

**Comment by daviditen** [comment]
It is available now on the [master](https://chapel-lang.org/docs/master) documentation branch which corresponds to the newest source.  The [chapel-lang.org/docs](https://chapel-lang.org/docs) link lists available documentation versions before forwarding to [latest](https://chapel-lang.org/docs/latest) which is tied to the latest release, currently 1.16.0.  Here's the a link to the [master DSI technotes](https://chapel-lang.org/docs/master/technotes/dsi.html).
