### ISSUE TITLE
Short config names for KNL testing mails

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#8101]
A few years back, we worked on changing subject lines for cron mails from saying everything about a configuration to saying a small number of strings that could be used to focus in on the most unique aspects of the configuration.  The current KNL testing doesn't follow this principle, making it hard to get a quick sense of what configurations failed, for example here is a sampling of subject lines:

```
Cron xc-loc-knl-CLE_quad_flat.mpi.gnu.aprun                                                                           
Cron xc-loc-knl-CLE_quad_flat.none.cray.aprun                                                                         
Cron xc-loc-knl-CLE_quad_flat.mpi.cray.aprun                                                                          
Cron xc-loc-knl-CLE_quad_flat.aries.gnu.aprun                                                                         
Cron xc-loc-knl-CLE_quad_flat.aries.cray.aprun                                                                        
Cron xc-loc-knl-CLE_quad_flat.aries.intel.aprun                                                                       
Cron xc-loc-knl-CLE_quad_flat.none.intel.aprun                                                                        
Cron xc-loc-knl-CLE_quad_flat.mpi.intel.aprun                                                                         
Cron xc-loc-knl-CLE_quad_flat.ugni-qthreads.gnu.aprun                                                                 
Cron xc-loc-knl-CLE_quad_flat.ugni-qthreads.cray.aprun                                                                
Cron xc-loc-knl-CLE_quad_flat.ugni-qthreads.intel.aprun                                                               
Cron xc-loc-knl-CLE_quad_flat.none.gnu.aprun                                                                          
Cron xc-loc-knl-CLE_snc4_flat.ugni-qthreads.cray.aprun                                                                
Cron xc-loc-knl-CLE_snc4_flat.none.intel.aprun                                                                        
Cron xc-loc-knl-CLE_snc4_flat.ugni-qthreads.gnu.aprun                                                                 
Cron xc-loc-knl-CLE_snc4_flat.aries.cray.aprun                                                                        
Cron xc-loc-knl-CLE_snc4_flat.mpi.cray.aprun                                                                          
Cron xc-loc-knl-CLE_snc4_flat.ugni-qthreads.intel.aprun                                                               
Cron xc-loc-knl-CLE_snc4_flat.mpi.intel.aprun                                                                         
Cron xc-loc-knl-CLE_snc4_flat.aries.gnu.aprun                                                                         
Cron xc-loc-knl-CLE_snc4_flat.mpi.gnu.aprun                                                                           
Cron xc-loc-knl-CLE_snc4_flat.aries.intel.aprun                                                                       
Cron xc-loc-knl-CLE_snc4_flat.none.cray.aprun                                                                         
Cron xc-loc-knl-CLE_snc4_flat.none.gnu.aprun                                                                          
```

For this set of configurations, it seems like we could say a lot less and convey a lot more (e.g., `knl-`[`quad`|`snc4`]-[`ugni`|`aries`|`mpi`| (_nothing_) ]-[`gnu`|`intel`|`cray`]

Typing this out, I also find myself wondering if we need to test all 4 comm layers and all 3 compilers for this configuration.

**Comment by awallace-cray** [comment]
@bradcray, you've asked for shorter and simpler KNL test config names. 

This is to ask if you wanted me to work on another set of test config names that could be made shorter:

	xc.ugni-qthreads.*

could be shortened to

	xc.ugni.*

because nowadays we only run COMM=ugni + TASK=qthreads; so no useful information would be lost if ugni-qthreads was abbreviated to ugni.  

However, unlike the KNL test config name changes you wanted, this ugni-qthreads -> ugni name change could also impact performance test artifacts. I much less familiar with performance tests, and I do not know if this ugni-qthreads abbreviation would be worth the trouble for performance tests. 

However, it looks like we could do that abbreviation in the test config names (ie, xc.ugni.*) but NOT in the perf config names (perf.xc.16.ugni-qthreads.*)

Then there's the question, why keep the Jenkins matrix config name "ugni-qthreads" at all? If we just changed it to "ugni" at the Jenkins-matrix level, hardwired TASK=qthreads everywhere else (if it isn't already), and removed the related test name twiddling that already exists in the test script, we might get to the same place- with less code, not more.  Is that the way to go? 

Please stand by for another comment coming soon, with PRs.

**Comment by bradcray** [comment]
> nowadays we only run COMM=ugni + TASK=qthreads; so no useful information would be lost if ugni-qthreads was abbreviated to ugni.

I'd definitely be open to that, though the current labels aren't so long that I find them all that off-putting.  So, I agree it'd be philosophically consistent to rename them, but it doesn't feel necessary / high-priority to me.  And like you, I can imagine it might have ripple effects whose overhead might outweigh the (minor) benefit.  From a K.I.S.S. perspective, I might leave them until someone complains.

I'd be interested in hearing from others who have a good handle and investment in test configurations as well, like @benharsh or @ronawho.

**Comment by ronawho** [comment]
It shouldn't be too hard to switch from ugni-qthreads to just ugni. The major thing that would need to be done is renaming the perfdat directory

**Comment by awallace-cray** [comment]
I'm much less familiar with the perf tools ... it still looks scary to me.  Anyway, I think the changes (emailed separately) are ready to go, and don't present any big new risks or require a big churn of complex existing data.

**Comment by awallace-cray** [comment]
Done working on this.
