### ISSUE TITLE
adding channel.advancePastByte ?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#8105]
I've been working with @benharsh on some revcomp benchmarks game I/O speed issues.
I'm proposing to add a method to IO.chpl called channel.advancePastByte that reads
until a particular byte is found and leaves the channel cursor just after that byte.
(And raises an EOF error if the byte is not found).

This function enables succinct expression of the fastest known I/O pattern for revcomp.
It could be used in other contexts as well, for example, we could use it in the implementation
of readln to skip characters until the newline.

See also PR #8103.

``` chapel
/* Reads until ``byte`` is found and then leave the channel offset
    just after it. If that byte is never found, raises an UnexpectedEOFError. */
proc channel.advancePastByte(byte:c_int) throws
```

**Comment by ben-albrecht** [comment]
Are there examples of this functionality in IO libraries of other languages?

**Comment by mppf** [comment]
@benharsh - to what extent was the buffered reader you were emulating part of the Rust standard library?

C++ has such a thing:
http://www.cplusplus.com/reference/istream/istream/ignore/

**Comment by benharsh** [comment]
Rust has its ``BufReader`` as part of its standard IO library:

https://doc.rust-lang.org/std/io/struct.BufReader.html

**Comment by mppf** [comment]
and https://doc.rust-lang.org/std/io/trait.BufRead.html#method.read_until in particular is the corresponding function.

**Comment by benharsh** [comment]
I vote for ``uint(8)``.
