### ISSUE TITLE
initializing fields out-of-order results in "multiple initializations" error

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#8137]
### Summary of Problem

Initializers currently require fields to be initialized in the order that they were declared in the
class/record.  When initializing them out of order, the compiler complains about "multiple
initializations."  However, this error message is confusing because a user inspecting the code
will only see a single initialization (the "multiple" refers to the one that the compiler inserted
when it inserted the auto-initialization that it thought was required when it encountered a
subsequent field).  This seems like a case where we should customize the error message to
report that the fields are being initialized out-of-order, reserving "multiple initializations" for
cases when a user initializes a field multiple times.

### Steps to Reproduce

**Associated Future Test(s):**
[`test/classes/initializers/phase1/unorderedFields-preferred.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/phase1/unorderedFields-preferred.chpl
          ) #5797

**Comment by benharsh** [comment]
Resolved by #8660
