### ISSUE TITLE
Different path functions for different OS

### ISSUE THREAD

**Issue by victor-ludorum** [chapel-lang/chapel#8146]
I am working to add two path function in Chapel language i.e **normCase()** function #6013 and **isAbsPath()** function #6010 . Each having the same issue that the function definition are different for different OS. But, there is only one separate file in Chapel module for all path function instead of two or three for each OS like Python. Kindly suggest any ways to implement these functions .

**Comment by mppf** [comment]
> function definition are different for different OS

Could it be as simple as using some `if` conditionals based upon `CHPL_TARGET_PLATFORM` ?

What is the behavior that differs for different platforms? So far, Chapel assumes a unix-like environment.

**Comment by lydia-duncan** [comment]
normCase's behavior varies depending on if the file system is case sensitive, and converts forward-slashes to back-slashes on Windows systems.  isAbsPath should only accept paths like "C://path/to/foo" if it is on a windows system

**Comment by mppf** [comment]
For normCase, it's not platform dependent, it's filesystem dependent. E.g. on Mac OS X you can make HFS+ filesystems that are case sensitive even though they are usually case insensitive. So it seems to me the code has to query whether or not the filesystem is case sensitive.

For isAbsPath, I'd expect that we'd ignore functionality for such windows-only paths for now, since that's what we've done everywhere else AFAIK.

**Comment by victor-ludorum** [comment]
@mppf Thanks!! for your advice . But Can you elaborate how can I use _CHPL_TARGET_PLATFORM_  as in the [doc](https://chapel-lang.org/docs/1.15/usingchapel/chplenv.html#readme-chplenv-chpl-target-platform) too there is no example to suggest how can I use this . Also Can you suggest any method to check **case sensitivity of file system** as in other languages (like in _python_ and _node.js_ ) they have separated these functions in separate modules so I have not got any help  . 

> For isAbsPath, I'd expect that we'd ignore functionality for such windows-only paths for now, since that's what we've done everywhere else AFAIK.

As the problem of **isAbsPath()** function , the same problem is with other functions too **expandVars()** and **expandUser()** . So , do I only implement for Unix-like environment ignoring Windows environment .

**Comment by bradcray** [comment]
Taking one piece of this:

> Can you elaborate how can I use CHPL_TARGET_PLATFORM

Within module code, the CHPL_* environment variables are generally available as `param` strings.  For example, see: https://chapel-lang.org/docs/latest/builtins/internal/ChapelEnv.html?highlight=chpl_target_platform#ChapelEnv.CHPL_TARGET_PLATFORM

**Comment by victor-ludorum** [comment]
> Within module code, the CHPL_* environment variables are generally available as param **strings**.
@bradcray  Thanks for this info I was actually confused about the parameter which you have cleared by mentioning _strings_ .

**Comment by ben-albrecht** [comment]
It looks like a solution was developed for this in https://github.com/chapel-lang/chapel/issues/6013 - I'm going to close this issue. Let me know if anyone disagrees.
