### ISSUE TITLE
Read configuration files at run time

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#8154]
For instance, if I want to use the `dev` database during this run and the `prod` database during that run, it would be nice to have

dev.cfg
```bash
DB_HOST=localhost
DB_USER=sally
DB_PW=secret
```

prod.cfg
```bash
DB_HOST=10.11.12.hike
DB_USER=ckaepernick
DB_PW=afro
```

Then be able to run my chapel program and point to the file

```bash
./dotslashables --config=prod.cfg
```

There was some discussion of this a while ago, but I don't see a ticket for it.

**Comment by daviditen** [comment]
Are `DB_HOST`, `DB_USER`, and `DB_PW` all declared as `config const` or `config var` in your program?  If yes, they can be set with config files as you request with the option `-f`.

`./dotslashables -f prod.cfg`

**Comment by buddha314** [comment]
Oh, that sounds nice.  Do you have an example lying around I could follow?

**Comment by daviditen** [comment]
Sure thing:

configs.chpl:
```
config const a = 1,
             b = 2.0,
             c = "hello";

writeln((a, b, c));
```

configs.cfg:
```
a=2
b=3.14
c="world"
```

% chpl configs.chpl
% ./configs
(1, 2.0, hello)
% ./configs -f configs.cfg
(2, 3.14, world)

**Comment by buddha314** [comment]
hells^{yes}.  Let me try this out. Will be back shortly.

**Comment by ben-albrecht** [comment]
More about the `-f` flag at the bottom of the [setting configuration variables](https://chapel-lang.org/docs/master/usingchapel/executing.html#setting-configuration-variables) section in the docs.

**Comment by buddha314** [comment]
so, RTFM, Ben? et tu?

**Comment by buddha314** [comment]
I'm not sure what I should do about this: 

```bash
 error: Configuration constants are allowed only at module scope.
```

and I'm not seeing it in the freakin manual, BEN!!!! I'M LOOKING AT YOU ALBRECHT!

**Comment by buddha314** [comment]
Nota bene: I edited the file to be have the variables be `config` variables, but they were inside `main()` so that's what caused the error.  Also, in experimenting I learned you can't have spaces in your config file like

```
FAIREST_IN_THE_LAND = "Betty White"
```

It will barf on the spaces (but not, presumably, Betty White)

**Comment by buddha314** [comment]
Okay, this looks like it's working for me.  Perhaps we can add some examples to the docs for the slow learners like myself.  Thanks, guys!

**Comment by ben-albrecht** [comment]
> Okay, this looks like it's working for me.

Great! Should we close this issue then?

>  Perhaps we can add some examples to the docs for the slow learners like myself. 

Could you suggest some examples that would have been useful for you?

**Comment by buddha314** [comment]
You're asking the slow guy to write the manual?

Sure, close the issue unless this is creating a downstream issue I'm unaware of.  It would be nice to have an example like

```chapel
const config svar: string,
                     ivar: int,
                     aardvark: [];
proc main() {
  // use the configured variables
}
```

```bash
svar="es a var, mang"
ivar=23
aardvard=1,1,2,3,5,6
```

Along with limitations or cases that would break.

**Comment by ben-albrecht** [comment]
Thanks. That is useful.

> Along with limitations or cases that would break.

Is there a specific limitation you ran into that would be worth pointing out?

**Comment by bradcray** [comment]
> Is there a specific limitation you ran into that would be worth pointing out?

Not to put words into Brian's mouth, but I assumed he was referring to [his note](https://github.com/chapel-lang/chapel/issues/8154#issuecomment-356383824) that there couldn't be spaces around the `=` characters (while letting us think of others that we might be aware of).

**Comment by cassella** [comment]
> There was some discussion of this a while ago, but I don't see a ticket for it.

That was in #7186.
