### ISSUE TITLE
Bug with bigint, initializers, and reductions over an in-place created array

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#8164]
### Summary of Problem
A user encountered an issue when calling a reduction over an array of bigints that was created in the reduction expression.  It seems to be limited to when the array is created using 1..0.  The code would compile, but then segfault during a deinitialization after the array was created.

This issue is most easily seen when running the program under valgrind, as some variations will pass in some settings but fail in others.

### Steps to Reproduce

**Source Code:**

```chapel
use BigInteger;

proc reductive_sequential(n:int): bigint {
  return * reduce for i in 1..n do new bigint(i);
}

proc main() {
  writeln(reductive_sequential(0));
}
```

**Compile command:**
`chpl foo.chpl`

**Execution command:**
`valgrind ./foo`

**Associated Future Test(s):**
[`test/classes/initializers/records/reductionOverCreatedArray-*.chpl`](https://github.com/chapel-lang/chapel/blob/master/classes/initializers/records/reductionOverCreatedArray-zero.chpl) #8163 

### Configuration Information

- Output of `chpl --version`: chpl version 1.17.0 pre-release

**Comment by cassella** [comment]
Is this related to #8156?  They both involve a runtime error after capturing the result of a ``for`` expression over the range ``1..0``.

**Comment by lydia-duncan** [comment]
I believe they are separate but similar.  Michael's branch to handle #8156 did not appear to resolve this issue, and this issue goes away when the type uses a constructor instead (or at least seems to, I didn't actually check with valgrind), which makes me inclined to think that the problem is something with the initializers implementation

**Comment by benharsh** [comment]
Resolved by the LoopExprs effort.
