### ISSUE TITLE
Using a global variable as a default argument in DateTime causes internal error

### ISSUE THREAD

**Issue by daviditen** [chapel-lang/chapel#8166]
### Summary of Problem
Changing the `time` constructor in the `DateTime` module to use the module level `nilTZ` constant for the default value of the `tzinfo` argument causes an internal compiler error when compiling test/library/standard/DateTime/testTimezone.chpl.

### Steps to Reproduce
Change the time.time constructor as shown here:
```
% git diff modules/standard/DateTime.chpl
@@ -527,7 +527,7 @@ module DateTime {
      `microsecond`, and `timezone`.  All arguments are optional
    */
   proc time.time(hour=0, minute=0, second=0, microsecond=0,
-                 tzinfo: Shared(TZInfo)=new Shared(nil: TZInfo)) {
+                 tzinfo: Shared(TZInfo)=nilTZ) {
     // For some reason, the compiler fails if we use nilTZ for the
     // tzinfo argument above.  Almost everywhere else it works fine.
     // Testcase: test/library/standard/DateTime/testTimezone.chpl
```

Then try to compile the testcase:
```
% chpl test/library/standard/DateTime/testTimezone.chpl
$CHPL_HOME/modules/standard/DateTime.chpl:530: internal error: invalid attempt to get reference type
```

### Configuration Information

- Output of `chpl --version`:
chpl Version 1.17.0 pre-release (ee2c152649)
Copyright (c) 2004-2018, Cray Inc.  (See LICENSE file for more details)

**Comment by bradcray** [comment]
Since this appears in a constructor call, I'd be curious if this worked any better with initializers—see PR #8141.

**Comment by daviditen** [comment]
Yes, it compiles and executes cleanly with #8141 applied.

**Comment by bradcray** [comment]
OK, I think we shouldn't worry about this then.  Hopefully #8141 will be merged soon (there's just one failure and it can be worked around), and constructors will be going away soon (fingers crossed).

**Comment by bradcray** [comment]
BTW, in picking #8141 back up, I got the obvious merge conflict on this line, so will try converting to the desired nilTZ in my final testing and merge that if it works... sound good?

**Comment by bradcray** [comment]
(let me know if any other changes are required beyond the default argument value...)

**Comment by daviditen** [comment]
Yes, that sounds good.  You can delete the comment just below it that describes the problem too.  Thanks.

**Comment by bradcray** [comment]
Weird, it seems like the nilTZ works in the time initializer, but not in the datetime initializer (I get the same error you reported here when I use it there).

Also, I've started getting a failure:

```
testTimezoneConversions.chpl:341: error: assert failed
```
that I didn't get prior to merging... :(

**Comment by bradcray** [comment]
Wait, new failure was my fault (or arguably the compiler's for not catching a dumb error on my part).

**Comment by daviditen** [comment]
I see the assert failure on `testTimezoneConversions` after copying this, but not the error on `testTimezone` anymore.

**Comment by bradcray** [comment]
Huh, that's weird...  I thought I still got the internal error for _some_ test in test/library/standard/DateTime/ when I convert the datetime.init() argument to nilTZ...
Maybe it was a different one?
