### ISSUE TITLE
where clause not working with :integral

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#8172]
I would expect the following program to print out "integral" but it does not:

``` chapel
proc foo(x) where x:integral {
  writeln("integral");
}
proc foo(x) {
  writeln("any type");
}

writeln("foo");
var i8:int(8) = 1;
bar(i8);
```

The problem is with isSubTypeOrInstantiation, which does not follow all of the possible "instatiations" that the compiler knows about (through other means than instantiatedFrom) such as :integral).

**Comment by lydia-duncan** [comment]
I believe in this situation we usually use `where isIntegralType(x.type)` or something along those lines

**Comment by mppf** [comment]
Right but since `proc f(x:integral)` works, it seems reasonable to expect it works in a where clause too. Obviously we have to be doing something else right now where we could be using `where t:integral`.

**Comment by lydia-duncan** [comment]
Okay, seems fair!
