### ISSUE TITLE
'new ChildClass' confusion for class inheritance

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#8176]
Consider a situation like the below, assuming that `ParentClass` and `ChildClass` provide initializers:

``` chapel
class ParentClass {
  ...
}
class ChildClass : ParentClass {
  ...
}

var c = new ChildClass(...);
```

(where the ... indicates code that was left out).

It seems to me that the `new ChildClass` communicates clearly that the programmer is trying to create a `ChildClass` instance. Thus, the result should always be to run a `ChildClass` initializer. However that is not always the case.

For example, consider the inheritedInitWrongName future:

``` chapel
class C {
  var x: int;
  var y: string;
  var z: real;

  proc init(x, y, z) {
    this.x = x;
    this.y = y;
    this.z = z;
    super.init();
  }
}

class D : C {
  proc init(a, b, c) {
    super.init(a, b, c);
  }
}

var myD = new D(x=3, "hi", 4.6);
writeln(myD);
delete myD;
```

This results in a compilation error such as:
 ```
inheritedInitWrongName.chpl:20: error: type mismatch in assignment from C to D 
```

but it should result in an unresolved call error, since there's no D initializer with a formal named x to match the `x=3` actual in the call. The other futures below include versions that don't compile now but should run.

**Associated Future Test(s):**
test/classes/initializers/inheritance/inheritedInitWrongName.chpl (PR #8141)
test/classes/initializers/inheritance/parent-child-coerce.chpl (PR #8083)
test/classes/initializers/inheritance/parent-child-coerce-class.chpl (PR #8083)

**Comment by lydia-duncan** [comment]
Yeah.  We also get confused in cases like test/classes/initializers/compilerGenerated/parent_inherits_initializer_bad.chpl, where an explicit initializer on the grandparent type takes precedent over the compiler generated initializer on the child.  I think we'll need to add some sort of rule to avoid virtual dispatch in these cases

**Comment by mppf** [comment]
In the cases I've seen, it's not that you're getting virtual dispatch - it's that you're getting regular dispatch with disambiguation that doesn't treat the `type` argument for `_new` as a requirement (but it should be a requirement ). I.e. there shouldn't be able to be coercions on the type you're creating.

**Comment by lydia-duncan** [comment]
I believe I've tried to add an explicit where clause in the past to force what you are describing, but was either unsuccessful or had to back away in the case where the user provided an explicit where clause

**Comment by bradcray** [comment]
I haven't taken the time to check but IIRC, I think we have two styles of where clauses:  `x:D` and `x.type == D` where the former probably permits subtypes and the latter might not (?).  Could it be that the where clauses created for initializers are of the wrong form?

**Comment by lydia-duncan** [comment]
I'll try take a look at both my open question and yours, but not tonight since I am timing out shortly

**Comment by lydia-duncan** [comment]
Following up, we use the initializer where clause if it exists (instead of making our own for the type argument), and explicitly set the type argument's type, which would explain why we dispatch

**Comment by lydia-duncan** [comment]
I would like to prevent _new functions and initializers from dynamically dispatching on the "chpl_t" and "this" arguments, specifically, though
