### ISSUE TITLE
Support equality comparisons between Shared/Owned and nil

### ISSUE THREAD

**Issue by daviditen** [chapel-lang/chapel#8180]
In the `time` type in the `DateTime` module there is a `Shared(TZInfo)` field that can ether be `nil` or a dynamic subclass of TZInfo implementing a time zone.  Since it can be `nil`, there is a lot of code that checks if it is.  That code currently has to do something like:

```
if dt1.tzinfo.borrow() != nil && dt2.tzinfo.borrow() == nil then
```
or
```
if dt1.tzinfo != new Shared(nil:TZInfo) && dt2.tzinfo == new Shared(nil:TZInfo) then
```
Adding `==` and `!=` overloads comparing `Shared/Owned` objects to `nil` directly would be useful instead of having to call `borrow()` or create `nil` `Shared` objects.

```
if dt1.tzinfo != nil && dt2.tzinfo == nil then
```

**Comment by mppf** [comment]
A related question is how to describe a `nil` Shared value, e.g.:
``` chapel
  proc datetime.init(year, month, day,
                     hour=0, minute=0, second=0, microsecond=0,
                     tzinfo: Shared(TZInfo)=new Shared(nil: TZInfo))
```

This is a bit awkward and in some ways it would be nicer to simply write

``` chapel
  proc datetime.init(year, month, day,
                     hour=0, minute=0, second=0, microsecond=0,
                     tzinfo: Shared(TZInfo)=nil)
```

**Comment by bradcray** [comment]
+1 for being able to just say `nil` in the above example.

**Comment by mppf** [comment]
#10436 adds tests checking that the `nil` comparisons work OK, but I'm leaving this issue open for the case described in the comment above.
