### ISSUE TITLE
Implement matPow in LinearAlgebra.Sparse

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#8192]
Or, if it is implemented, please help me figure out why it's failing.  Here is my message.  I seem to have a special talent for finding these things Friday afternoons after everyone has gone home.

I've tried this using `LinearAlgebra, LinearAlgebra.Sparse` and it's power set.  Same error every time.

This guy works
```chapel
  var S = fcnBigSparseMat();
  var P = S.dot(S);
```

This version fails
```chapel
  var S = fcnBigSparseMat();
  var P = matPow(S,2);
```

And the crying starts...

```bash
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:309: In function 'eye':
$CHPL_HOME/modules/packages/LinearAlgebra.chpl:310: error: can't apply '#' to a range with idxType int(64) using a count of type CSDom(2,int(64),domain(2,int(64),false),true,false)
make: *** [setup] Error 1
```

**Comment by cassella** [comment]
It looks like the sparse domain isn't matching ``Dom`` here since it's not a ``domain(2)``:

```chapel
/* Return an identity matrix over domain ``Dom`` */
proc eye(Dom: domain(2), type eltType=real) {
  var A: [Dom] eltType;
...
```

so ``matPow()``->``_expBySquaring()`` -> ``eye(x.domain)`` is resolving to the version that's fully generic on its first argument,

```chapel
/* Return a square identity matrix over domain ``{0..#m, 0..#m}`` */
proc eye(m, type eltType=real) {
  var A: [{0..#m, 0..#m}] eltType;
...
```

and you can't do that.

**Comment by ben-albrecht** [comment]
I took it as "you can't yet", because we haven't implemented it yet.

**Comment by cassella** [comment]
I just meant you can't do the ``0..#m`` (in that ``eye()``) where ``m`` is your sparse domain.  (AFAIK)

Maybe as a workaround, writing your own ``eye()`` that accepts a sparse domain would work.  Or maybe it would just show where the next roadblock is.
