### ISSUE TITLE
Handle or document promotion flattening when multiplying by scalars

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#8200]
Multiplying a matrix by a scalar messes up everything nice in the world.

```chapel
use LinearAlgebra, 
    LayoutCS,
    LinearAlgebra.Sparse;

var nv: int = 8,
    D = {1..nv, 1..nv},
    SD: sparse subdomain(D) dmapped CS(),
    W: [SD] real;

SD += (1,2); W[1,2] = 1.0;
SD += (1,3); W[1,3] = 1.0;
SD += (1,4); W[1,4] = 1.0;
SD += (2,2); W[2,2] = 1.0;
SD += (2,4); W[2,4] = 1.0;
SD += (3,4); W[3,4] = 1.0;
SD += (4,5); W[4,5] = 1.0;
SD += (5,6); W[5,6] = 1.0;
SD += (6,7); W[6,7] = 1.0;
SD += (6,8); W[6,8] = 1.0;
SD += (7,8); W[7,8] = 1.0;

writeln("W.domain:\n", W.domain);
var W2 = W.dot(W);
writeln("W2 domain:\n", W2.domain);
var aW = 0.5 * W.dot(W);
writeln("aW domain:\n", aW.domain);
```

```bash
W.domain:
{
 (1, 2) (1, 3) (1, 4)
 (2, 2) (2, 4)
 (3, 4)
 (4, 5)
 (5, 6)
 (6, 7) (6, 8)
 (7, 8)
}  // GOOD!

W2 domain:
{
 (1, 2) (1, 4) (1, 5)
 (2, 2) (2, 4) (2, 5)
 (3, 5)
 (4, 6)
 (5, 7) (5, 8)
 (6, 8)
}  // GOOD!

aW domain:
{1..11}  // WHY GOD WHY?!?!
```

**Comment by buddha314** [comment]
You can, apparently, do this

```chapel
var a: real = 0.5;
W.dot(a);
```
but not
```chapel
a.dot(W);
```

Which makes sense is orthogonal to "intuitive".  And it really makes building a polynomial hard.  How do you get

```chapel
var T = W.dot(a) + W.dot(W).dot(a**2)....
```

**Comment by buddha314** [comment]
Let's say you're trying to be sneaky...

```chapel
var T = matPlus(W.dot(a), W);
// Barf
```

Don't be sneakly.  No variant of nesting appears to work.

**Comment by ben-albrecht** [comment]
Could you clarify what you mean by "handle or document"? There is already an open issue for promotion-flattening causing problem (#5958).

Until that's addressed, building polynomials looks something like this:

```chpl
const a = 0.5;
const polynomial = dot(a, W).plus(dot(a**2, W.dot(W))).plus(dot(a**3, W.dot(W).dot(W)));
```

**Comment by buddha314** [comment]
"handle" -> "make it stop!"
"document" -> "put an example on the page that warns me this is going to happen"

And your example is awesome.  I put up a question on [SO](https://stackoverflow.com/questions/48271879/how-to-build-a-matrix-polynomial-in-chapel)

**Comment by ben-albrecht** [comment]
> "handle" -> "make it stop!"

I think that's the focus of #5958

> "document" -> "put an example on the page that warns me this is going to happen"

This is discussed in [promotion flattening](https://chapel-lang.org/docs/master/modules/packages/LinearAlgebra.html#linear-algebra-interface) subsection here. Would it be correct to interpret this issue as "add more examples to this section"? Beyond computing a matrix polynomial, are there other examples that would be useful in this section?


> And your example is awesome. I put up a question on SO

Done.

**Comment by bradcray** [comment]
I agree that this is another instance of issue #5958 and that it's regrettable / needs to be fixed.  I'd love to see this show up high on your mega-issue priority list, but I think this copy of the issue should be closed as a duplicate.

**Comment by ben-albrecht** [comment]
Promotion now preserves shape for domains and arrays. (#5958)
