### ISSUE TITLE
Internal compilation error RES0472 encountered for attempted param range class member declaration

### ISSUE THREAD

**Issue by ian-bertolacci** [chapel-lang/chapel#8240]
### Summary of Problem
Attempting to create a param range in a class results in internal error RES0472.
This is in contrast to the more helpful `error: 'symbol' is not of a supported param type` when trying to do the same **outside** a class declaration.
(I am now aware that param ranges are not yet supported.)

### Steps to Reproduce

**Source Code:**
```chapel
class Foo {
  param _range_ = 1..1;
}

var f = new Foo();
writeln( f._range_ );
```

(see [this TIO instance](https://tio.run/##S85ILEjN@f8/OSexuFjBLT9foZpLQaEgsSgxVyG@KDEvPTVewVbBUE/P0JqrlourLLFIIQ0okJdaDlKsoWnNVV6UWZKak6ehkKYH06Bp/f8/AA))

### Configuration Information

- Output of `chpl --version`: 
```
> chpl --version
chpl Version 1.16.0.e43acc7
Copyright (c) 2004-2017, Cray Inc.  (See LICENSE file for more details)

```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
> $CHPL_HOME/util/printchplenv --anonymize
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_MAKE: make
CHPL_ATOMICS: intrinsics
CHPL_GMP: none
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_WIDE_POINTERS: struct
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
>  gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by ian-bertolacci** [comment]
Also, additional 'fun' (internal error FUN7520) happens when typing that variable as a range:
```chapel
class Foo {
  param _range_ : range = 1..1;
}

var f = new Foo();
writeln( f._range_ );
```
(see [this TIO instance](https://tio.run/##S85ILEjN@f8/OSexuFjBLT9foZpLQaEgsSgxVyG@KDEvPTVewUoBzFCwVTDU0zO05qrl4ipLLFJIAwrkpZaDNGloWnOVF2WWpObkaSik6cE0alr//w8A))

**Comment by daviditen** [comment]
The error in the first comment can be simplified to:

```
proc notParam(x) return x;
proc f(param r = notParam(1)) { }

f();
```

In the default value for `param r = notParam(1)`, `notParam(1)` can be replaced by anything that is not a `param`.
