### ISSUE TITLE
Add support for user-defined assignment-based initialization

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#8242]
While converting code to use initializers, I've been musing over the relationship between copy initializers, coercions, and assignments.  For example, start with a record declared like this:

```chapel
record R {
  var x: int;

  // a 0-arg initializer
  proc init() { 
    this.x = 42;
    super.init();
  }

  // a copy initializer
  proc init(r: R) {
    this.x = r.x;
    super.init();
  }

  // an int initializer
  proc init(x: int) {
    this.x = x;
    super.init();
  }
}
```

The presence of the copy initializer permits us to invoke it by writing:

```chapel
var myR2 [: R] = myR;
```

where `myR` and `myR2` are both instances of `R`.  That is, because we're in a variable initialization context, we invoke the copy initializer rather than assignment.  And it also permits us to say the following in phase 1 of an initializer:

```chapel
this.r = r;
```

with a field and a value `r` of type `R`.  That is, because we're in phase 1, we're going to use a copy initializer to implement this assignment rather than assignment.

This has led me to wonder whether this suggests (a) we should also permit automatic invocation of other initializers in single-value cases of other types, such as:

```chapel
var myR3: R = 10;   // should this be equivalent to `= new R(10)`?
```

or:

```chapel
this.r = 11;    // should this be equivalent to `= new R(11)`?
```

or (b) we should use some other way of declaring copy initializers to make it clearer why a procedure named `init` is invoked in one case but not the other, or (c) whether user-defined coercions are really the way to support such cases where integers seem to become `R`s.

Put another way, if copy initializers are special initializers that just happen to be invoked when both (a) the RHS and LHS are of the same type and (b) there's an initializer that accepts a single argument of that type, are we setting up confusion for users who might think initializers would also get invoked when initializing with single-value expressions of other types?

**Comment by bradcray** [comment]
As a more realistic motivation for this issue, I was wondering whether we could add an "`int` initializer" like the one on `R` above to our `atomic int` record in order to support initialization of `atomic int`s as follows:

```chapel
var myAtomicInt = 42;
```

or

```chapel
this.myAtomicInt = 365;
```

even if we were to never add support for directly assigning to atomics.  I.e., could we support initializing them without assigning them.  Was discussing this with @ronawho last night.

**Comment by bradcray** [comment]
Noting belatedly that the previous comment relates to issue #5037.

**Comment by bradcray** [comment]
Speaking with @cassella this evening, I'm feeling increasingly convinced that the case in which we might want to do something like:

```chapel
this.myRecord = 20;
```

should be handled through coercions rather than copy initializers.  The reason is that I don't think we want to go down the (C++-esque) route of having:

```chapel
record Vector {
  proc init(length: int) { // allocate a vector of length 'length' }
  ...
}
```

result in the ability to write:

```chapel
myRecord.myVectField = 20;
```

as a means of getting a 20-element vector.  This suggests that a different mechanism should be used to convert `20` into a record field than simply the presence of an `init()` routine that takes the RHS expression.  And that suggests either (a) leaning on user-defined coercions, or (b) having a different way of marking copy initializers (like calling them `copyInit()` or having a modifier keyword).

Thinking about (b), arguably, converting 20 into a record isn't a "copy initializer" (since the types are different), so that names doesn't make sense.  And simultaneously, I think we'd also like to use the same routine for both initialization and copy initialization when the types _are_ the same.  So (b) doesn't really seem attractive to me.

Meanwhile, I think we do continue to want user-defined coercions, and this feels like a natural place to use them to me, so I'm leaning heavily towards (a) after this conversation.

**Comment by bradcray** [comment]
> recognizing that this a placeholder syntax

For once, I'm not using a placeholder syntax here.  I actually think `init=` should be the syntax (but that's not to say you can't dislike it or propose alternatives).  I agree that it's subtle, but I think this is a virtue since for the most part it's the same as any other initializer (it can be invoked in `new ...` expressions), but adds the additional property that it can also be used in an "assignment initialization" context.

> I'm also wondering if reusing the same syntax for copy initializers and this coercion-like behavior would lead to the same problems we currently experience with distinguishing copy initializers with generic arguments.

I was thinking it would help with those problems because my guess is that most declarations of `init=` would be more explicit about their argument types since they're designed for fairly specific use cases.  I also think the cases we've been wrestling with have been cases where a generic `init()` overload was accidentally being called in the copy initialization case, whereas in this proposal that couldn't happen since such procedures wouldn't be candidates for copy initialization.

> Finally, it seems a bit odd to have a specific method be limited to always having a single argument 

I didn't mean to imply that `init=` could only be defined to take a single argument.  Rather, I think
 the key is that they _can_ only be called with a single argument.  I.e., since `init=` initializers can also be used in `new ...` expressions, they can take additional arguments as long as those arguments have defaults.  This makes them similar to our current implementation of copy initializers (which can have additional arguments as long as they have defaults).  You could imagine the compiler generating a warning for `init=` declarations whose 2nd+ arguments didn't have default expressions or which didn't have any arguments.

**Comment by lydia-duncan** [comment]
These are good points.  I'll muse on this more and see if I have more thoughts later.

**Comment by lydia-duncan** [comment]
Coming back to this, I wonder if this is optimizing for an unusual case.

Does this seem like something a user would naturally want for types with more than one field, or does it seem only applicable for one field or a type field plus a field of that type?  I don't mean to imply that this doesn't have merits in those cases on their own, but I'm unsure whether it will come up for more than just atomics.  It seems to me that most classes/records that people would actually use will have multiple fields.

Take for instance a Square implementation.  While I'm sure a user would enjoy being able to say `var x: Square = 20;`, I don't particularly see them tearing their hair out because they don't have one.

Was there an additional case that you had in mind that I'm not thinking of?

**Comment by bradcray** [comment]
> Does this seem like something a user would naturally want for types with more than one field, or does it seem only applicable for one field or a type field plus a field of that type?

I'm confused by the question.  Just because the `init=` overload takes one _argument_ (the RHS of an `=` operator), doesn't mean it can only take one _value_.  The RHS could of the assign-initialize could be a tuple, some other record, a class, an array, etc.

**Comment by benharsh** [comment]
I know some time has passed, so opinions may have shifted, but:

> Coming back to this, I wonder if this is optimizing for an unusual case.

I agree that this isn't a common case, but I think it significantly improves the elegance/ergonomics of using types that wrap other types.

I think another use-case is something like 'bigint'. I believe we're leveraging custom ``_cast`` calls right now, but ``init=`` could be used to allow ``var x : bigint = 1`` in a more principled way.

I think we've also seen in practice that users wrap arrays in records, and a generic ``proc init=(data : [])`` could be useful.

**Comment by bradcray** [comment]
Since posting [the comment above](https://github.com/chapel-lang/chapel/issues/8242#issuecomment-366365485) that proposed `init=`, I've continued to like it more and more and haven't come up with any obvious problems/downsides to it (though, admittedly, I haven't worked at doing so either).  If I'd had more time / presence of mind, I'd probably have split the proposal off into its own feature request issue and closed this one just to avoid all the thrash at the beginning of this issue.

**Comment by bradcray** [comment]
I think this issue has run its course, so I'm closing it in favor of #10615.
