### ISSUE TITLE
Returning from a forall loop should generate a compiler error

### ISSUE THREAD

**Issue by aditmehta9** [chapel-lang/chapel#8251]
```chpl
//Functions for uppper triangular matrix and lower triangular matrix
var row:int =3;
var col:int =3;
var ar=[[1,2,3],[1,1,1],[10,10,10]];
proc upper(arr,r, c): (bool) {
	forall i in 1..#r{
		forall j in 1..#c{

			if(i<j&&arr[i][j]!=0)
			{
				return false;
			}
		}
	}
	return true;
}
writeln(upper(ar,row,col));
proc lower(arr,r,c): (bool) {
	forall i in 1..r{
		forall j in 1..c{
			if(i>j&&arr[i][j]!=0)
			{
				return false;
			}
		}
	}
	return true;
}

```

It enters if condition but not returning false in upper triangular matrix. I tried to solve issue  #5753  end up creating new issue.

**Comment by aditmehta9** [comment]
It must return false value.

**Comment by mppf** [comment]
You can't return from a forall loop. It should be generating a compilation error.

**Comment by ben-albrecht** [comment]
Hi @aditmehta9 - Are you trying to implement iterators for `upper()` and `lower()` from  #5753? If so, I suggest working through the [iterator primer](https://chapel-lang.org/docs/master/primers/iterators.html) as a starting point.

**Comment by bradcray** [comment]
Strangely, we generated an error for returning within a `forall` loop in the past (as recently as Chapel 1.15.0), but don't seem to anymore:

```chapel
proc foo() {
  forall i in 1..10 do
    if i == 2 then
      return 2;
  return 0;
}

writeln(foo());
```

Then:
```
testit.chpl:4: error: return is not allowed in forall statement
```

Now:
```
0
```

**Comment by bradcray** [comment]
@vasslitvinov, from what I can see with a quick look, this backslide occurred as a result of #5295 when the way we built ForallStmts changed.  Generating an error for this case also seems similar to the errors you introduced for `break` and `continue` recently.  Would you take this issue on?

**Comment by vasslitvinov** [comment]
Sure.
