### ISSUE TITLE
writef JSON format prints enum values incorrectly.

### ISSUE THREAD

**Issue by ian-bertolacci** [chapel-lang/chapel#8252]
### Summary of Problem
When printing enum values from writef (using the `%jt` format string), the enum value string is printed without quotation marks, which is invalid JSON.
[This can be seen using an online JSON validator](http://jsoneditoronline.org/?id=4f35e24d601868831f7ab88fa5794920)

### Steps to Reproduce

**Source Code:**

```chapel
enum EnumType { Type1, Type2, Type3 };
record RecType {
  const s : string;
  const e : EnumType;
}

writef( "%jt\n", new RecType( "example_string", EnumType.Type1 )  );
```

which produces the output
```
{"s":"example_string", "e":Type1}
```

[See this TIO instance](https://tio.run/##PY5BCsIwEEX3c4pPQbBQBHVn1l5AXAqlxFEr7TQkkVakZ4@xIW7mwf8zj9GPxnAXAsurxzGO89swPvhhWy3YJewxK7KsB3vFiXXaI0AP4jwcDnDetnJX/4xjlpWKZqLRtp5vaxSrp79IUUF4zK6Y8tT0puM6eWKdjzfLNyiBUhGF8AU)

### Configuration Information

- Output of `chpl --version`: 
```
> chpl --version
chpl Version 1.16.0.e43acc7
Copyright (c) 2004-2017, Cray Inc.  (See LICENSE file for more details)

```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
> $CHPL_HOME/util/printchplenv --anonymize
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_MAKE: make
CHPL_ATOMICS: intrinsics
CHPL_GMP: none
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_WIDE_POINTERS: struct
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
>  gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by nimitbhardwaj** [comment]
I want to work on this issue, I read [here](https://stackoverflow.com/questions/45052750/json-data-enum-types) there that there is no enum type in JSON, so want to know which of the implementation of better, according to me first one using array is better, I want some feedbacks  :simple_smile:

**Comment by nimitbhardwaj** [comment]
Or, I think simply `{"s":"example_string", "e":"Type1"}` is also good way, because this also can be parsed easily, may be.

**Comment by nimitbhardwaj** [comment]
But this code is working fine
```chapel
enum EnumType { Type1, Type2, Type3 };
record RecType {
  const s : string;
  const e : EnumType;
}

var r = new RecType('Hello', EnumType.Type2);
var S = '{"s": "Nimit Bhardwaj", "e": Type3}';

writef( "%jt\n", new RecType( "example_string", EnumType.Type1 )  );
writeln(r);

var mem = openmem();
var writer = mem.writer().write(S);
var reader = mem.reader();

var f = new RecType();
reader.readf("%jt", f);
writeln(f);
```
working correct 
giving output
```
{"s":"example_string", "e":Type1}
(s = Hello, e = Type2)
(s = Nimit Bhardwaj, e = Type3)
```
So enum is parsed correctly, even the json is incorrect.
from [here](https://stackoverflow.com/questions/45617341/how-to-populate-a-chapel-class-object-from-a-json)

**Comment by nimitbhardwaj** [comment]
I just thought of a way to represent Enum in json, I don't know it is good or not, please have a check for it
for the above record, `var r = new RecType('Hello', EnumType.Type1);`.

`r` is then in json I think of representing `{"s": "Hello", "e": "enum#EnumType Type1"}`, this can be converted to the type and also not violating the rules of json and also we got the info that e is of enum and of type EnumType with value Type1, so it is readable and user friendly.

Please tell me, I don't know it can be used or not.

**Comment by ian-bertolacci** [comment]
I think the produced JSON string representing the enum value should just be the enum value name (in this example, `{"s": "Hello", "e": "Type1"}`).
The string `"enum#EnumType Type1"` doesn't seem to provide the `readf` function any more information for parsing the value than just the enum value string (`"Type1"`) and also knowing the type of the `e` field of the `RecType` record.

The `"enum#EnumType Type1"` string also has the side effect of being more obtuse to parse by other, non-Chapel applications that would parse that JSON.
For example, if I had a server-side app written in chapel that was producing JSON responses, I would have to be clever (either when producing or reading) JSON responses that involved enums, which is unfortunate.

**Comment by nimitbhardwaj** [comment]
OK, cool, I understand
