### ISSUE TITLE
What is the pattern for timing in tests?

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#8294]
An important part of testing is timing.  But if I do a test.chpl 

```chapel
var t: Timer;
t.start();
var b = bigOlHonkinDataMunchinMoFo();
t.stop();
writeln("wow, that took ", t.elapsed(), "!!!!!");
```

Then my tests fail because the elapsed time is different.  What is the correct pattern for this? How do I get times without failing tests?

**Comment by ben-albrecht** [comment]
For clarification on the context, are you referring to writing a `.good` file for using `start_test` on a Chapel program with timing output?

**Comment by ronawho** [comment]
We don't typically do timings for correctness tests, only performance tests. For benchmarks we usually do is something like:

```chapel
config const printStats = true;

var t: Timer;
t.start();
var b = bigOlHonkinDataMunchinMoFo();
t.stop();
if printStats then 
  writeln("wow, that took ", t.elapsed(), "!!!!!");
```

And then we'll have a test.execopts file with

```
--printStats=false
```

Or sometimes it's reversed and `printStats` will be false by default and we'll have a `test.perfexecopts` that throws `--printStats=true`

**Comment by buddha314** [comment]
Yeah, in the `.good` file you'll have "wow, that took"

**Comment by ben-albrecht** [comment]
@buddha314 - I don't think there is an actual issue here - just a question, so I'm going to close the issue.
