### ISSUE TITLE
Compiler error when zippering tuple and array in a forall loop

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#8313]
### Summary of Problem
A zippered `forall` loop over a tuple and array results in a (confusing) compiler error. Changing the leader (first argument to `zip()`) impacts the error message given.

### Steps to Reproduce

**Source Code:**

Promoted assignment works as expected
```chapel
var V = [0,0,0];
var T = (1,2,3);

V = T;
```

Serial zippered for loop works as expected
```chapel
var V = [0,0,0];
var T = (1,2,3);

for (v, t) in zip(V, T) do 
  v = t;
```

Parallel zippered `forall` loop with array as leader results in a compiler error
```chapel
var V = [0,0,0];
var T = (1,2,3);

// ChapelTuple.chpl:231: In iterator 'these':
// ChapelTuple.chpl:234: error: tuple indexing expression is not of integral type
forall (v, t) in zip(V, T) do
  v = t;
```

Parallel zippered `forall` loop with tuple as leader results in a different compiler error
```chapel
var V = [0,0,0];
var T = (1,2,3);

// error: unresolved access of 'range(int(64),bounded,false)' by '(1)'
forall (t, v) in zip(T, V) do
  v = t;
```

### Configuration Information

- Output of `chpl --version`: `chpl version 1.17.0 pre-release (05b5ccf)`

**Comment by ben-albrecht** [comment]
This bug was encountered in the implementation of ` proc Vector(x: ?t, Scalars...?n)` in the `LinearAlgebra` module (#8269)

**Comment by ben-albrecht** [comment]
Digging a little deeper, it looks like there may be a discrepancy between the `followThis` type for array leader/followers vs. tuple leader/followers. 

The array leader passes 1-element tuples of ranges, e.g. `(0..0,)` as `followThis` to the tuple follower, whereas the the tuple follower expects ranges, e.g. `0..0`. The error occurs when the tuple follower loops over the `followThis` of `(0..0,)` and indexes with the range `0..0` instead of the range value of `0`.

**Comment by ben-albrecht** [comment]
A (kind of lame) work-around for this might look like:

```chapel
  pragma "no doc"
  iter _tuple.these(param tag:iterKind, followThis)
      where tag == iterKind.follower
  {
    var fThis: range;
    // Received followThis from a multi-dimensional object (e.g. an array)
    if isTuple(followThis) {
      if followThis.size != 1 then
        compilerError('Tuples cannot be zipped with a multi-dimensional object in a forall');
      fThis = followThis(1).translate(1);
    } else {
      fThis = followThis;
    }

    for i in fThis {
      yield this(i);
    }
  }
```

**Comment by ben-albrecht** [comment]
Looking further, it looks like all the leader/follower iterators in `internal/modules` use tuples of ranges as the format for `followThis` except for tuples. I suspect this may have been an oversight, and tuples should also use tuples of ranges (even though  it would always be 1-element tuples of ranges).

@bradcray || @benharsh - any thoughts on this?

**Comment by bradcray** [comment]
I agree that this sounds like an oversight in the design of tuples, probably caused by only thinking about zippering them with themselves, not with other things (and that it should be changed to match the standard tuple-of-ranges interface).

**Comment by ben-albrecht** [comment]
> and that it should be changed to match the standard tuple-of-ranges interface

Cool. I am happy to take this.
