### ISSUE TITLE
Provide example of capturing group in Chapel regexp library

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#8318]
Inspired by this ticket at [Chrest](https://github.com/marcoscleison/chrest) and this [SO on capturing groups](https://stackoverflow.com/questions/5642315/regular-expression-to-get-a-string-between-two-strings-in-javascript), it would be good to see how Chapel can extract a group from a string.  

Specifically, I want to get the phrase  "always gives" as a variable from the middle of the phrase "my cow always gives milk".  Then I want to take that to my cow and demand an explanation on why there was no milk, but that's my problem.

**Comment by mppf** [comment]
``` chapel
use Regexp;

var input = "my cow always gives milk";

var capture:string;

var r = compile("""(always gives)""");
var match = r.search(input, capture);

if match.matched then
  writeln(capture);
else
  writeln("not a match!");
```

If you had more than one paren indicating a capture group in the regexp, you'd just pass more arguments to search/match.

**Comment by buddha314** [comment]
And to the original problem, I'd like to get the number "17" out of a string with the pattern "/home/user/:ID/details" when the string "/home/user/17/details" comes in, if that's not too much.

**Comment by mppf** [comment]
``` chapel
use Regexp;

var input = "/home/user/17/details";

var capture:string;

var r = compile("""/home/user/(\w+)/details""");
var match = r.search(input, capture);

if match.matched then
  writeln(capture);
else
  writeln("not a match!");
```

**Comment by buddha314** [comment]
WOO HOO!  Nice job!

**Comment by bradcray** [comment]
Should this have been an SO question?  (would it have helped others?)

**Comment by buddha314** [comment]
doing that right now
