### ISSUE TITLE
Buy the """ guy/gal a beer

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#8320]
Whoever implemented the triple quote literal has literally saved me an hour of work today.  Please, if you sit next to him/her, buy him/her a beer on me.  (I'll get you back!)

**Comment by bradcray** [comment]
Sadly, none of us sit anywhere near @daviditen...   Glad you're enjoying it though!

**Comment by buddha314** [comment]
Then this ticket will remain open forever, like a monument to an unfulfilled promise.

**Comment by ben-albrecht** [comment]
Maybe @tmacd9 can handle this one?

**Comment by daviditen** [comment]
I think I could buy a beer.  That would probably fix this. :)  Glad you like it @buddha314.

**Comment by buddha314** [comment]
Technically, that qualifies.  However, you should provide some sort of validation the beer was bought in celebration of this win.  Like a bar napkin with a note in lipstick on it or something.

**Comment by bradcray** [comment]
I think @benjamin-robbins is the new logical owner of this issue when he makes his inaugural trip to MoA.  :)

**Comment by buddha314** [comment]
Make sure he brings lipstick to sign the note.

**Comment by benjamin-robbins** [comment]
I'm on for beer.
