### ISSUE TITLE
How should this.init(...) work for "new initializers"?

### ISSUE THREAD

**Issue by noakesmichael** [chapel-lang/chapel#8323]
What is the behavior for this.init(...) within an init(...) method for records and classes?

1) An implementation of record.init(...) may choose to call this.init(...); typically to leverage common
code.  Before the call, the method cannot read/init any fields or call any methods defined for the
record.  However it can perform any other computation on local variables or module level variables.

When the call returns it is known that record is fully initialized.  Should the remainder of the body
of the init method be allowed to call methods defined for the record?  On the one hand this would
allow "phase 2" code to run within a record init() method without additional syntax.  On the other
hand it means that there are two rules for allowable operations within a record init() method.

Suppose we assume that a call to this.init(...) returns  a fully initialized instance of the record and
we allow the body to invoke any method.  This provides an "escape" to providing "phase 2"
behavior when useful.  Is this a bug or a feature?  This might encourage an effort to define two
initializers with formal-lists that differ in some "trivial" way with the expectation that one version
implements the public interface and the second implements an escape to provide "phase 2"
behavior to the first implementation.

Can a call to this.init() appear in a conditional?  If they only appear within param conditionals then
it is reasonably easy for the compiler to determine that there will be just one call at runtime and that
other constraints are observed.  If they are allowed within non-param conditionals then we might
insist that they appear in every arm of the conditional or else implement a more sophisticated
analysis.

2) An implementation of class.init() may choose to call this.init(). Before the call, the method cannot
read/init any fields or call any methods defined for the record.  However it can perform any other
computation on local variables or module level variables.

For an init method on a base class, the issues are comparable to init methods for records with the
wrinkle of handling calls to super.init().  If the call to this.init() appears at top level within the method
then a) there cannot be any other call to an init() method b) we suppress auto-insertion of super.init().

Should we allow this.init() in a param conditional?  The issues are, again, comparable to init for
records but with additional complexity if we allow mixing calls to super.init() and this.init() along
different arms.  These issues are more complex if we allow super.init()/this.init() in non-param
conditionals.

The use of this.init() is a little more complex for derived classes.  The current proposal assumes
that a call to super.init() on a child class allows the compiler to treat the class as an initialized
instance of the parent class.  When this call returns it is possible to call methods on defined
on the parent.  As with base classes we must determine whether the compiler should regard
'this' as having the type of parent class or the current class.  This issue is more complex if we
allow super.init() and this.init() to be mixed in conditional expressions.

**Comment by lydia-duncan** [comment]
I think bullet 2 meant to say "class.init()" instead of "record.init()"

**Comment by benharsh** [comment]
I believe we arrived at a consensus elsewhere, and that this issue can be closed.
