### ISSUE TITLE
Need some intuition on dmapped()

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#8328]
This isn't really an "issue", but I could use some help understanding why this fails and how I can learn the limitations.

```chapel
use Time,
    LinearAlgebra.Sparse;

var t1, t2: Timer();

t1.start();
var D = {1..60000, 1..60000};
var Ds: sparse subdomain(D) dmapped CS(compressRows=true);
var M: [D] real;
t1.stop();
writeln("D elapsed() ", t1.elapsed());

t2.start();
var E = {1..2500000, 1..2500000};
var Es: sparse subdomain(E) dmapped CS(compressRows=true);
var N: [E] real;
t2.stop();
writeln("E elapsed() ", t2.elapsed());
```

Running this on my laptop, it dies before it sets up N.

```bash
./bigdoms 
D elapsed() 22.3511
Killed: 9
```

I don't really know what is taking up memory and why it is killed.  Thanks for the help.

**Comment by benharsh** [comment]
If I'm reading this correctly, you are declaring your arrays over the dense domains (D, E), not the sparse domains (Ds, Es). Meaning that you are allocating 60k**2 and 2.5m**2 elements.

**Comment by buddha314** [comment]
Oh good god, cut and paste error.  Now on the right domains, I get

```bash
./bigdoms 
D elapsed() 0.002099
E elapsed() 0.053566
```

So E is still much slower.  What is going on?  I'm not saying it's a problem, just trying to understand so I know how to handle it.  Also, it's late in your time zone so i can wait.

**Comment by bradcray** [comment]
CS* data structures have a setup cost that's proportional to the number of rows/cols in the matrix. 
 If I'm using my calculator correctly. `Es` has about 41x more rows/cols than `Ds` and is running about 25.5x slower.  So this doesn't seem surprising to me.

**Comment by bradcray** [comment]
Do you buy this argument?  Can I close this issue?

**Comment by buddha314** [comment]
Why not?!  CLOSE THAT BABY!
