### ISSUE TITLE
lifetime checking: default return lifetime

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#8378]
In the event that the return lifetime is not explicitly specified (see #8377), what should the compiler assume about the lifetime of a call-expression that is calling that function?

**Comment by mppf** [comment]
In my draft branch, it is "minimum lifetime of all actual arguments subject to lifetime analysis".
But array accessors generally needed annotation in this case, so it might be nicer to have the default for methods be the lifetime of 'this'. That's (part of) the default in Rust.

**Comment by mppf** [comment]
Rust's rules are these:
* each argument gets its own lifetime 'a 'b 'c ...
   * if there is one argument, its lifetime applies to return
   * methods return lifetime of 'self' by default

**Comment by psahabu** [comment]
[Link to the full Rust lifetime elision rules.](https://doc.rust-lang.org/book/second-edition/ch10-03-lifetime-syntax.html#lifetime-elision)

What you have implemented on the branch could be considered a fourth rule, having the default be the minimum of the provided lifetimes. I'm not sure what we should do if the user wants something else though.

**Comment by mppf** [comment]
> I'm not sure what we should do if the user wants something else though.

That is what issue #8377 is supposed to be discussing.

**Comment by vasslitvinov** [comment]
I am game using these rules by default. We can adjust as we gain experience and users.

I am OK whether "these rules" do or do not include the special rule for methods/`this`.

**Comment by mppf** [comment]
I think I've already "gained experience" sufficient to say that the special rule for methods/this is a better default than the plain old minimum-lifetime-of-all-actuals.

**Comment by mppf** [comment]
``` chapel
record R {
} 

// This should be an error if the return lifetime
// for a method is 'this' by default.
proc R.identity(ref x) ref { 
  return x;
} 
```

**Comment by mppf** [comment]
Closing this issue because the default is implemented and seems to be working OK.
