### ISSUE TITLE
example/hello.chpl doesn't compile with full LLVM support

### ISSUE THREAD

**Issue by caizixian** [chapel-lang/chapel#8380]
### Summary of Problem
What behavior did you observe when encountering this issue?
```
$CHPL_HOME/modules/internal/String.chpl:103: internal error: EXP1378 chpl Version 1.16.0.e43acc7
Note: This source location is a guess.

Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug -- 
please see http://chapel.cray.com/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.
```

But it does compile with `chpl --llvm --fast examples/hello.chpl`.

What behavior did you expect to observe?

It compiles and runs.

Is this a blocking issue with no known work-arounds?

No.

### Steps to Reproduce
```
git checkout 1.16.0
source ./util/setchplenv.bash
export CHPL_LLVM=llvm
export CHPL_WIDE_POINTERS=node16
make
```

**Compile command:**
`chpl --llvm --llvm-wide-opt --fast examples/hello.chpl`

**Execution command:**
N/A

### Configuration Information

- Output of `chpl --version`:
```
chpl Version 1.16.0.e43acc7
Copyright (c) 2004-2017, Cray Inc.  (See LICENSE file for more details)
```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_MAKE: make
CHPL_ATOMICS: intrinsics
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_WIDE_POINTERS: node16 *
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
gcc (Ubuntu 7.2.0-8ubuntu3) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
```
clang version 4.0.1-1build1 (tags/RELEASE_401/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by mppf** [comment]
Hi @caizixian - I believe --llvm-wide-opt wasn't working in the 1.16 release (unfortunately). However I believe it's working now on the master branch. Does it work for you with the master branch? Is there some reason you need to use 1.16?

Thanks!

**Comment by mppf** [comment]
(Also the current version removes CHPL_WIDE_POINTERS=node16 as this was a workaround that is no longer necessary).

**Comment by caizixian** [comment]
I just checked. It does work on the master branch.

I read #7487 so I was thinking that it should work on 1.16 release.

**Comment by caizixian** [comment]
I was going to play with LLVM optimization passes so I thought it might be a better idea to apply my changes on top of stable releases

**Comment by bradcray** [comment]
@caizixian (since @mppf is home for the evening): Starting with stable releases generally makes sense.  We've done a fair amount of LLVM-related work since 1.16, and master tends to be pretty stable in general (and has seemed particularly stable this past week or so), so I wouldn't shy away from master if it'd help you make progress (and might even recommend it from the perspective of being better w.r.t. LLVM).
