### ISSUE TITLE
Bad references to moved `multilocale.rst`

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#8385]
### Summary of Problem
Erroneous multilocale executions print bad path to `multilocale.rst` that was moved to `$CHPL_HOME/doc/rst/**usingchapel**/multilocale.rst`. When fixed, some tests are also affected with hard-coded output expecting the old path.

### Steps to Reproduce
**Execution command:**
`./foo -nl 4`

**Output**
```
error: Only 1 locale may be used for CHPL_COMM layer 'none'
To use multiple locales, see $CHPL_HOME/doc/rst/multilocale.rst
```

### Configuration Information
```
chpl version 1.17.0 pre-release (81470ac9ba)
```

**Comment by ben-albrecht** [comment]
Thanks for reporting!

**Comment by mppf** [comment]
@cassella - I know this might sound strange, but would it be reasonable for chplspell to find such path issues?

**Comment by cassella** [comment]
@mppf Nothing's occurring to me immediately.  Do you have an approach in mind?

**Comment by mppf** [comment]
Well, paths could be "words" and a "dictionary" could be populated with paths that exist. Of course, that's all said from a place of having no idea how chplspell works... so it might not have a reasonable implementation there.

**Comment by cassella** [comment]
It's not a natural fit for chplspell -- the scpell script tokenizes everything up front on spaces and punctuation including ``/``, so it's already "CHPL_HOME" "doc" "rst" "multilocale" "rst" before any spell checking can happen.

Though  for a first cut, only considering paths that are anchored by "CHPL_HOME/",

```
grep -n -I -o  -r CHPL_HOME[-_./a-zA-Z0-9]\* . | sed s,CHPL_HOME/,, | sed s,CHPL_HOME,, | sed s/:/\ /g | while read f l p; do [ -z "$p" -o -e "$p" ] || echo $f:$l names $p; done
```

There are a fair number of false positives, but also what look like a bunch of out-of-date docs.  (And CHANGES.md lines refering to files that no longer exist, I think.)  But it didn't pick out any more instances in runtime/ (or compiler/ besides an llvm RUN_CONFIG script.)

I'm not sure this can be made into something reliable enough to be smoke-testable.  Or if it'd be reasonable to look for e.g ``doc/`` ``compiler/`` ``test/`` ... as anchors.
