### ISSUE TITLE
type-from-new param variations

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#8388]
### Summary of Problem

I saw the comment in #8361 (type inference from ``new`` within
initializers) about a special case for ``type`` fields, and was
curious what happens with a ``param`` field.  A few things happen.

### Steps to Reproduce

**Source Code:**

I started with the test added there, [test/classes/initializers/generics/phase1/type-from-new.chpl](https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/generics/phase1/type-from-new.chpl )

```chapel

record R {
  var x : int;
}

class C {
  type t;
  var v = new R();

  proc init() {
    t = new R();
    super.init();
    v = new R();
  }
}

proc main() {
  var c = new C();
  delete c;
}
```

Compiling this produces the desired error: ``Cannot initialize type
field 't' with 'new' expression``.

1. But if I change ``type t`` to ``param t``,

```
fortytwo@magrathea:~/src/chpl/tfn$ chpl param-from-new.chpl 
param-from-new.chpl:12: internal error: seg fault [misc.cpp:558]
Note: This source location is a guess.
```

That shouldn't compile, but shouldn't be a segfault.

2. The same error occurs with ``var t``, which AFAIK should compile.

I removed the field ``v`` and its initialization in ``C.init()`` phase2.  Both the ``param`` and ``var`` versions compile that way.

3. However, I think the ``param`` version shouldn't compile.

4. Curious about what ``c`` had ended up looking like in the param, "no v" case, I added ``writeln(c)`` to ``main()``, and got

```
fortytwo@magrathea:~/src/chpl/tfn$ chpl param-from-new-no-v-writeln.chpl 
In file included from /tmp/chpl-fortytwo-22186.deleteme/_main.c:28:0:
/tmp/chpl-fortytwo-22186.deleteme/ChapelIO.c: In function ‘writeThisFieldsDefaultImpl’:
/tmp/chpl-fortytwo-22186.deleteme/ChapelIO.c:310:13: error: ‘tmp_chpl’ undeclared (first use in this function)
 call_tmp7 = tmp_chpl;
             ^
/tmp/chpl-fortytwo-22186.deleteme/ChapelIO.c:310:13: note: each undeclared identifier is reported only once for each function it appears in
/home/fortytwo/src/chapel/runtime/etc/Makefile.exe:27: recipe for target '/tmp/chpl-fortytwo-22186.deleteme/param-from-new-no-v-writeln.tmp' failed
make: *** [/tmp/chpl-fortytwo-22186.deleteme/param-from-new-no-v-writeln.tmp] Error 1
error: compiling generated source
```

**Associated Future Test(s):**
None yet.

### Configuration Information

```
fortytwo@magrathea:~/src/chpl/tfn$ chpl --version
chpl version 1.17.0 pre-release (48805b1)
Copyright (c) 2004-2018, Cray Inc.  (See LICENSE file for more details)
```
```
fortytwo@magrathea:~/src/chpl/tfn$ printchplenv --anonymize
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: intrinsics
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none
```
```
fortytwo@magrathea:~/src/chpl/tfn$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.6) 5.4.0 20160609
```

**Comment by cassella** [comment]
One more thing I didn't manage to get into the bug last night.  The minimal program I've found to reproduce the seg fault is

```chapel
record R {}

class C {
  var t = new R();
  proc init() {}
}
```

```
fortytwo@magrathea:~/src/chapel (master)$ chpl assign-record-in-phase2.chpl 
assign-record-in-phase2.chpl:5: internal error: seg fault [misc.cpp:558]
```
If it's ``var t:R = new R()``, there's no seg fault.  If I leave out the explicit ``init()``, there's no seg fault.

**Comment by lydia-duncan** [comment]
> If I leave out the explicit init(), there's no seg fault.

That's because the default initializer is not used yet.  I suspect if you left off the explicit `init()` and compiled with `--force-initializers`, you would start to see the segfault again.

**Comment by lydia-duncan** [comment]
You are correct that the param case shouldn't compile, we don't allow param classes/records yet.  The `var t` case is mysterious, but I might be misunderstanding the code.  Can you update the issue with the code for that example?

Thanks for reporting!

**Comment by benharsh** [comment]
I'll take the first shot at this.

**Comment by cassella** [comment]
> That's because the default initializer is not used yet. I suspect if you left off the explicit init() and compiled with --force-initializers, you would start to see the segfault again.

I hadn't thought of that.  But in fact, done that way, it compiles.
(And with a writeln() of a new C(), it reports ``{t = ()}``.

The compiler must have an easier time of it when it gets to write the
initializer from scratch.


> Can you update the issue with the code for that example?

The ``var t`` case is the one I simplified to the "minimal program" above.

**Comment by lydia-duncan** [comment]
> The var t case is the one I simplified to the "minimal program" above.

So the code looks like this?
```chapel
record R {
  var x : int;
}

class C {
  var t;
  var v = new R();

  proc init() {
    t = new R();
    super.init();
    v = new R();
  }
}

proc main() {
  var c = new C();
  delete c;
}
```
because that isn't the code you have above, the code above has `t` as a type field

**Comment by lydia-duncan** [comment]
Oh, never mind, you mean the second comment
