### ISSUE TITLE
classes allow param record fields

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#8422]
### Summary of Problem

```chapel
record R { }

class C {
  param r:R;
  proc init() { }
}

var c = new C();
writeln(c);
delete c;
```

Without the ``writeln()``, this compiles.  With it,

```
fortytwo@magrathea:~/src/chpl/tfn$ chpl wrparmem.chpl
In file included from /tmp/chpl-fortytwo-23814.deleteme/_main.c:28:0:
/tmp/chpl-fortytwo-23814.deleteme/ChapelIO.c: In function ‘writeThisFieldsDefaultImpl2’:
/tmp/chpl-fortytwo-23814.deleteme/ChapelIO.c:236:26: error: ‘tmp_chpl’ undeclared (first use in this function)
 writeIt_chpl(_ref_tmp_6, tmp_chpl);
                          ^
/tmp/chpl-fortytwo-23814.deleteme/ChapelIO.c:236:26: note: each undeclared identifier is reported only once for each function it appears in
/home/fortytwo/src/chapel/runtime/etc/Makefile.exe:27: recipe for target '/tmp/chpl-fortytwo-23814.deleteme/wrparmem.tmp' failed
make: *** [/tmp/chpl-fortytwo-23814.deleteme/wrparmem.tmp] Error 1
error: compiling generated source
```

I expected an error along the lines of the one you get declaring such a ``param r:R`` outside of a class:

```
param-record-field.chpl:4: error: 'r' is not of a supported param type
```
**Associated Future Test(s):**
[`test/classes/initializers/generics/param-record-field.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/generics/param-record-field.chpl)

[edit 2/12 cassella to add path to future]

### Configuration Information

```
fortytwo@magrathea:~/src/chpl/tfn$ chpl --version
chpl version 1.17.0 pre-release (44fa845)
Copyright (c) 2004-2018, Cray Inc.  (See LICENSE file for more details)

fortytwo@magrathea:~/src/chpl/tfn$ printchplenv --anonymize
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: intrinsics
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none

fortytwo@magrathea:~/src/chpl/tfn$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.6) 5.4.0 20160609
```

**Comment by cassella** [comment]
I don't know if this is related to initializers per se.  Trying to write the same thing in the constructor world fails because it requires a constructor that takes a ``param r:R``, and such a constructor can't be written.  So I can't figure out how to test just the field declaration under constructors.

**Comment by lydia-duncan** [comment]
It's related to initializers in that such a program would be caught by other means in the constructors world, but initializers allow you to write your program in such a way that those other means are avoided or foiled.  It's a good thing, but it means we needed to be more careful than we were.
