### ISSUE TITLE
problem with if expressions containing range field accessors

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#8464]
### Summary of Problem

Generated code for an if-expr involving internal range fields can return a pointer to a local argument.

### Steps to Reproduce

**Source Code:**

```chapel
proc outputIt(y:int) {
  if y == 1 then
    writeln("OK");
  else
    writeln("BAD");
}

proc const range.testIfExpr(other:range(?)) {

  var lo1 = if hasLowBound() then this._low else other._low;
  outputIt(lo1);
}

proc main() {
  var a=1..10;
  var b=1..10;

  a.testIfExpr(b);
}
```

**Compile command:**
`chpl range-field-ifexpr.chpl --no-inline`

**Execution command:**
`valgrind ./range-field-ifexpr`

**Associated Future Test(s):**
test/expressions/ferguson/if-expr/range-field-ifexpr.chpl

### Configuration Information

quickstart

**Comment by benharsh** [comment]
Resolved by #9649 .
