### ISSUE TITLE
Section in Docs on Configuring Tests

### ISSUE THREAD

**Issue by Tshimanga** [chapel-lang/chapel#8472]
Maybe I just haven't found it, but it may be helpful for newcomers to have a section in the docs on configuring chapel tests. An overview on the default settings, how it works, and  things like the process/syntax for changing the runtime upper bound, pointing to db credentials, modifying compopts, etc.

**Comment by daviditen** [comment]
This isn't particularly easy to find and could probably stand to be linked more directly from the [developer resources](https://chapel-lang.org/developers.html) page:

https://github.com/chapel-lang/chapel/blob/master/doc/rst/developer/bestPractices/TestSystem.rst

**Comment by cassella** [comment]
FWIW, that doc seems far from comprehensive.  For example, it doesn't mention ``.skipif`` or ``.suppressif``, or the difference between them, or the syntax of the files.  Or what the developer mindset should be when creating a future of a failure that doesn't fail on all platforms or configs.

It doesn't describe how a ``.compopts`` or ``.execopts`` can cause a single ``.chpl`` test to have multiple ``.good`` files.  Though it does have a TODO noting the absence.

Also, it suggests to the reader:

> For more information on these capabilities, review the comments at the
> top of ``start_test`` which is currently the most complete documentation
> on the testing system.

But there are no comments at the top of the python ``start_test``.

**Comment by lydia-duncan** [comment]
I have an improved version of the document over in #8978.  @Tshimanga and/or @cassella, feel free to give feedback on the approach.

**Comment by jabraham17** [comment]
Closing, the [Test System docs](https://chapel-lang.org/docs/main/developer/bestPractices/TestSystem.html) seem much improved since this issue was opened
