### ISSUE TITLE
`start-test` Issue with test-specific EXECOPTS

### ISSUE THREAD

**Issue by Tshimanga** [chapel-lang/chapel#8475]
### Summary of Problem

Running `test.chpl` with a `test.EXECOPTS` fails to grab runtime configurations. Using directory-wide `EXECOPTS` works however this then needs to modified from test to test.

I expected that `start_test` would grab the relevant runtime configs (`test.EXECOPTS`)

### Steps to Reproduce
git clone https://github.com/buddha314/a-test-story
cd a-test-story/test
start_test test.chpl

Expected Output:
I am a test
Are you feeling... frustrated ?

Actual Output:
I am a test
Are you feeling... ?

**Comment by bradcray** [comment]
I believe that the filenames are case-sensitive and that you need to use lower-case `.execopts` for a test-specific (rather than directory-general EXECOPTS) file specifying executable options.  By convention we use upper-case filenames for directory-wide options and lower-case extensions for test-specific options.

**Comment by buddha314** [comment]
that might be the case, since I am running the test on my Mac and it works just fine.  However, Macs are kinda slippery when it comes to handling case

**Comment by buddha314** [comment]
is this also true for `COMPOPTS`?

**Comment by bradcray** [comment]
Macs are more forgiving with case and seem to accept `foo.EXECOPTS`.  It's not clear from context: is @Tshimanga running on something more case sensitive than a Mac?  (e.g., Linux).

> is this also true for `COMPOPTS`?

I believe it's consistent for all of our testing options.  Directory-wide options are all-caps, test-based options use lower-caps suffixes.

**Comment by Tshimanga** [comment]
Yeah I'm running on Ubuntu

**Comment by Tshimanga** [comment]
Thanks @bradcray
