### ISSUE TITLE
Should we change the conditional expression implementation to use a separate AST node?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#8479]
Today, we represent if expressions (`var x = if a then b else c;`) in the compiler as a nested function.  However, this causes problems:
- In the case of if expressions used as the default value of an argument when no type is specified (see #8189), the function call is copied to the type of the argument, but the definition is not.
- In the case of field defaults when default initializers are involved, the function is defined to utilize fields, but we want those fields to be references to the necessary arguments to the default initializer (since the fields are initialized when the default initializer is called).  However, the function definition has been entirely separated from the call to it, so it can't be updated when this is happening.
- #8464 demonstrates that the generated code may cause the return of argument pointers when used with the internal fields of the range type.

We believe that representing if expressions as a separate AST type would help alleviate these problems.  It would allow the representation to remain within the scope in which it was defined, enabling the necessary analysis and code transformations that would allow these cases to succeed (or at least allow the bug fixes that the current implementation thwarts).

**Comment by mppf** [comment]
This also causes problems with `new borrows`, e.g. `var x = if y then new borrowed MyClass(1) else new borrowed MyClass(2)` - the owned temporaries are freed before the if expr fn returns.
