### ISSUE TITLE
Provide names of missing module or Enum

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#8493]
I keep getting errors like this:

```
src/Ayatollah.chpl:6: error: Cannot find module or enum
```

But It won't tell me which module or enum.  Grrr..  Is that possible?  To get around it, I have to `use` multiple statements, and abuse the `use/mention` distinction.  HOW META!

**Comment by bradcray** [comment]
Just for a bit more context, what does line 6 of that file say?  Thanks.

**Comment by buddha314** [comment]
So I just tracked this down and was thinking about opening a ticket.  I have these files

```
src/Modesl.chpl
    /Api.chpl
    /Setup.chpl
```

The calling file asked for

```
use Models,
      API,
      Setup;
```

For the file and the module, `API` has a case mis-match.  Within the file, the module is identified as 

```chapel
module API {
  ...
}
```

Building this on my mac, this hasn't been a problem. I had to change the `use`, filename and `module` call all to the same case.  Here `API`;

**Comment by bradcray** [comment]
I think I see: you were getting the error when you moved to Linux?  Yeah, I believe we can generate a better error for that, I just needed to know how to reproduce it.  I've got it now, thanks.

**Comment by bradcray** [comment]
@buddha314: Who loves ya?  #8495 should resolve this.

**Comment by buddha314** [comment]
Do you really?  Could have said something yesterday before I spent $200 on dinner with my wife...

Thanks brad!

**Comment by bradcray** [comment]
This error message was improved as requested by PR #8495.
