### ISSUE TITLE
Default initializers: compilation failure for dmapped domains

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#8503]
### Summary of Problem
Calling a default initializer for a class with a dmapped-domain field results in an internal compiler error.

It looks like domain literals in the AST aren't normalized properly (or in the expected way) for code like ``dmapped Block({1..10})``.

### Steps to Reproduce

**Source Code:**

```chpl
use BlockDist;

class C {
  var dom = {1..10} dmapped Block({1..10});
}

proc main() {
  var c = new C();
}
```

**Compile command:**
``chpl foo.chpl --force-initializers``

Output:

```txt
foo.chpl:4: internal error: CAL0078 chpl version 1.17.0 pre-release (e00d06a)
Note: This source location is a guess.

Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug -- 
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.
```

**Associated Test(s):**
[`test/users/npadmana/npb-mg/mg.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/users/npadmana/npb-mg/mg.chpl
          )

**Comment by bradcray** [comment]
I have a case like this that I was working towards filing today.  In my case, I was guessing it was because domain maps themselves don't use initializers yet...  Could that be the case here as well?

**Comment by benharsh** [comment]
Maybe? What I observed was that during function resolution we had AST like:
```
call:
    - UnresolvedSymExpr '_construct_Block'
    - call:
        - chpl__buildDomainExpr
        - call_tmp:range
```

At this point in the compiler, my impression has been that there should not be CallExprs within CallExprs.

**Comment by bradcray** [comment]
OK, I'll continue to file the future and then refer to it here.

**Comment by lydia-duncan** [comment]
I suspect what happened is that the AST for the domain map code did not get transformed appropriately due to being attached to a field instead of placed in a function during scope resolution.  Independently or perhaps relatedly, the initializer normalization operations did not expect that particular AST structure and so did not transform it into the expected set up for resolution to handle.

**Comment by lydia-duncan** [comment]
I would take a look at how the code for this case looks for constructors at the end of scope resolution and normalization and see how it gets to that point
