### ISSUE TITLE
Internal alist indexing error for generic class hierarchies without many members

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#8522]
### Summary of Problem

For certain generic class hierarchies, we hit an internal error related to accessing an alist using an illegal index.  My best guess as to the root cause is that the classes don't have much in the way of fields (so maybe some code path assumes there's at least one field?).  I haven't tried to diagnose this any further but suspect this may be low-hanging fruit to someone familiar with initializers.

### Steps to Reproduce

**Associated Future Test(s):**
[`test/classes/initializers/generics/inheritance/generic-inherit-alist-index-error.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/generics/inheritance/generic-inherit-alist-index-error.chpl
          ) #8521 

### Configuration Information

- Output of `chpl --version`: `chpl version 1.17.0 pre-release (6f306ab)`

**Comment by bradcray** [comment]
@lydia-duncan, @benharsh, @noakesmichael : As noted above, I suspect that this may be low-hanging fruit for someone familiar with initializers.

**Comment by lydia-duncan** [comment]
There's a number of default initializers tests with inheritance of generics that run into this same error message.  I suspect @noakesmichael's current work will help

**Comment by lydia-duncan** [comment]
@noakesmichael and @benharsh - I added this issue and future to that location in the docs

**Comment by benharsh** [comment]
#8707 fixed this issue and retired the linked future
