### ISSUE TITLE
initialization of dmapped domain fields not working properly

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#8525]
### Summary of Problem

An object's domain field is `dmapped` to a previous field's domain map, yet at the time that we're initializing the field, the domain's distribution is not set to the previously initialized domain map (determined this by adding debug printing to the `Cyclic` code manually since the current initializer rules prohibit inspecting field information within phase 1 of an initializer).

My first guess was that we were seeing this issue because the domain map hierarchy hasn't been converted over to use initializers yet, but it may also be related to issue #8503.

Perhaps most strangely, this pattern seems to work better for `--no-local` compilation (where it reaches the teardown before hitting a `nil` dereference error) than it does for `--local` compilations (where it runs into problems setting up when trying to initialize the domain field).  I haven't looked into the `--no-local` case at all yet to try and understand why it's working "better" there.

### Steps to Reproduce

**Associated Future Test(s):**
[`test/classes/initializers/phase1/domainMaps/init-dmap-dom-arr-local.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/phase1/domainMaps/init-dmap-dom-arr-local.chpl
          ) #8521
[`test/classes/initializers/phase1/domainMaps/init-dmap-dom-arr.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/phase1/domainMaps/init-dmap-dom-arr.chpl
          ) #8521

### Configuration Information

- Output of `chpl --version`: `chpl version 1.17.0 pre-release (1a84c75)`

**Comment by benharsh** [comment]
Michael un-futurized these back in May, closing.
