### ISSUE TITLE
Reflection error in use of fielderator on generic class

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#8526]
### Summary of Problem

Using the Reflection module's "fielderator" capabilities results in an error for a generic class:

```
$CHPL_HOME/modules/standard/Reflection.chpl:150: error: illegal expression to return by ref
```

### Steps to Reproduce

**Associated Future Test(s):**
[`test/library/standard/Reflection/fielderator-generic.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/library/standard/Reflection/fielderator-generic.chpl
          ) #8521

### Configuration Information

- Output of `chpl --version`: `chpl version 1.17.0 pre-release (1a84c75)`

**Comment by DanilaFe** [comment]
This is not a bug, but a very bad error message. The issue is that we're trying to take a referene to a field type `B`, which is obviously not able to be returned by reference. I will improve the error message.

**Comment by bradcray** [comment]
@DanilaFe : Good point!  I think what this program should've been doing is to change line 9 to:

```chapel
    if !isType(getField(data, i)) && (isRecordType(vtype) || isClassType(vtype)) {
```

If you'd consider making a clone of this test with this change along with any PR that improves it, I think that'd be great.
