### ISSUE TITLE
Multi-line comments in documentation is not rendered properly

### ISSUE THREAD

**Issue by caizixian** [chapel-lang/chapel#8532]
https://chapel-lang.org/docs/master/primers/learnChapelInYMinutes.html

The following code block
```
// one line comment
/*
   multi-line comment
*/
```
is rendered as 
```
// one line comment

   multi-line comment
```

**Comment by lydia-duncan** [comment]
Thanks for reporting!  This is indeed a bug, specifically one with the script that turns our primers into html files.

**Comment by lydia-duncan** [comment]
@ben-albrecht - I've taken a brief look at this.  It seems like the code in chpl2rst.py doesn't account for comments within explicit code blocks and tries to treat them the same as comments in normal code, so it removes the surrounding multi-line markers.  I think it'll take a slightly more thorough rewrite of that logic to fix this bug.

**Comment by ben-albrecht** [comment]
@lydia-duncan - Yep, this is a known issue: https://github.com/chapel-lang/chapel/issues/6766

We just need to decide on a syntax for it.

**Comment by lydia-duncan** [comment]
Ah, okay.  I missed that context, glad I didn't dive too deeply into it
