### ISSUE TITLE
How should `enum` values be represented in generated code?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#8561]
The current Chapel compiler inspects the (implicit or explicit) integer values associated with an enumerated type and makes some attempt to map the symbols in our generated C code to the smallest integer type that can store all of the values, preferring unsigned integers over signed when in doubt.  This can be seen by compiling the following code, saving the C, and inspecting the generated `chpl__header.h` for the enumerated symbols:

```chapel
enum color1 {red, green, blue};
enum color2 {red = 257, green, blue};
enum color3 {red = -10, green, blue};  
enum color4 {red = -257, green, blue};                   
enum color5 {red = 1099511627776, green, blue};

var colorVar1: color1;
var colorVar2: color2;
var colorVar3: color3;
var colorVar4: color4;
var colorVar5: color5;
```

Specifically, the generated C contains the lines:

```c
typedef enum {color1_chpl_red_chpl = UINT8(1), color1_chpl_green_chpl = UINT8(2), color1_chpl_blue_chpl = UINT8(3)} color1_chpl;
typedef enum {color2_chpl_red_chpl = UINT16(257), color2_chpl_green_chpl = UINT16(258), color2_chpl_blue_chpl = UINT16(259)} color2_chpl;
typedef enum {color3_chpl_red_chpl = INT8(-10), color3_chpl_green_chpl = INT8(-9), color3_chpl_blue_chpl = INT8(-8)} color3_chpl;
typedef enum {color4_chpl_red_chpl = INT16(-257), color4_chpl_green_chpl = INT16(-256), color4_chpl_blue_chpl = INT16(-255)} color4_chpl;
typedef enum {color5_chpl_red_chpl = UINT64(1099511627776), color5_chpl_green_chpl = UINT64(1099511627777), color5_chpl_blue_chpl = UINT64(1099511627778)} color5_chpl;
```

showing the attempt to store the values using signed and unsigned integers of various sizes depending on the values.  This issue is designed to capture the tradeoffs of this approach.

@mppf and I both think that he may have implemented this, and in issue #8552 he captures the likely rationale as "I had convinced myself at some point that when doing binary I/O with a value of enum type, it should occupy as many bits as the enum needs to store all of the values. In the context of binary I/O, having enum values default to writing 8-byte values seems to be less likely to be what is wanted than e.g. a 1 byte value, since most enums have only a small collection of small constants."

The first question is whether or not it is an effective approach.  Calling `sizeof()` on the symbols and variables of the enumerated types suggests that it may not be:

```chapel
extern proc sizeof(x): size_t;

writeln(sizeof(color1.red));
writeln(sizeof(color2.red));
writeln(sizeof(color3.red));
writeln(sizeof(color4.red));
writeln(sizeof(color5.red));


writeln(sizeof(colorVar1));
writeln(sizeof(colorVar2));
writeln(sizeof(colorVar3));
writeln(sizeof(colorVar4));
writeln(sizeof(colorVar5));
```

where the output is:

```
4
4
4
4
8
4
4
4
4
8
```

demonstrating that the C implementation is choosing the round the `enum` type representation up to C's default integer size anyway (presumably that's the rationale).

Reasons we may want to continue doing this:
* might support more compact representations in memory or binary files
* arguably symmetric to `bool` types vs. `bool(n)` types in Chapel where the former lets the implementation decide the width and the latter lets the programmer control it.  For enums, if we had a declaration style that let the programmer choose a specific representation, as proposed in issue #5417, this would permit users who care to be specific.

Reasons we may not want to do this:
* It doesn't seem like it's having the intended effect based on my experiment above.  But even if it did...
* Within Chapel's semantics, `enum`s act like default-sized integers (`int(64)`s) more than they do these smaller values, so it can be confusing when looking at the generated code to see a representation that doesn't match the semantic behavior
* It arguably makes the generated code unstable w.r.t. how the enums are represented depending on what integer values they were assigned.  For example, if their integer values were used to represent bitmasks and the addition of new enums over a program's evolution tipped us into a new integer size, the program would behave fairly differently all of a sudden which seems unfortunate.  OTOH, the output above shows that C has this same characteristic.
* Along similar lines, it seems attractive for enums to have a predictable size.  E.g., from an interoperability perspective it might be easier to just "know" what an enum's size was rather than having to understand this auto-sizing approach.
* Arguably adds modest complexity to the compiler (though it is already implemented...).

I felt pretty negative about this approach when reading generated code and getting confused by it this afternoon; then in thinking about writing up this issue I became more open to it given that it didn't seem to be causing problems and felt similar to the `bool` situation; now having written it up and finding that it doesn't seem terribly effective I feel more opposed to it again, though it doesn't feel like a huge issue to me.  That said, if it does affect binary file formats, it may be nice to settle sooner than later.

**Comment by mppf** [comment]
> Specifically, the generated C contains the lines:
> ...
> showing the attempt to store the values using signed and unsigned integers of various sizes depending on the values. This issue is designed to capture the tradeoffs of this approach.

Actually our compiler just always wraps integer literals with a macro to specify the size. At some point I changed enums to always wrap the integer literals with the same type for all enum constants, instead of marking them with a different size per constant, and this seems a reasonable improvement.

Additionally, if you make an enum storing a value that only fits in a uint(64), AFAIK the current implementation works correctly, where the previous did not. We could certainly decide that an `enum` is always a `int(64)`, though.

In C, an enum is guaranteed to have enough space for an int, which might only be 16 bits (if we're only relying on the standard) but @dmk42 tells me that most implementations make available enums with larger size. So, what I'm saying is that even C compilers have a concept for adjusting the type of an enum based upon what constants are stored in it.

**Comment by mppf** [comment]
I just have two more things to bring up.

1. This issue is tagged "Language Design" but I don't see any argument about changing the behavior of any Chapel program. Yeah, the generated C is weird, but it is in so many other ways... Why does this weirdness matter?

2. I see no reason why we need to continue to generate Chapel enum constants as a C enum. Instead, we could just generate each Chapel enum constant as an integer literal. I think changing that strategy would make much of this easier to understand.

**Comment by dmk42** [comment]
> In C, an enum is guaranteed to have enough space for an int, which might only be 16 bits (if we're only relying on the standard) but @dmk42 tells me that most implementations make available enums with larger size. So, what I'm saying is that even C compilers have a concept for adjusting the type of an enum based upon what constants are stored in it.

That isn't quite how it works, but you have the right general idea.  The width is variable all the time.  The type of an enumeration constant in C is int, and the compiler is required to support enums up to the size of an int, but is allowed to store them in a smaller size if they will fit.  As you say, many compilers also extend enums so that they can be larger than an int as well.

**Comment by bradcray** [comment]
> This issue is tagged "Language Design" but I don't see any argument about changing the behavior of any Chapel program.

I called this language design because you said something implying to me that this may affect the binary I/O width of an enum.  If it's unrelated (that is, if the binary I/O width of an enum is also variable but unrelated to how we code generate the enum), then I agree this label should be removed (and maybe a new issue should be opened w.r.t. that).

I also tend to agree that leaning on C enums may be doing us a disservice here and that codegen-ing enums more like params or consts may be better.

**Comment by mppf** [comment]
Right, the I/O code just calls enum_mintype(t) on the enumerated type to get the "minimum appropriate integer size". But that all happens at resolution time and doesn't have anything really to do with the generated code. I'll remove the Language label from this issue.

**Comment by bradcray** [comment]
Continuing this discussion in light of the recent semantic changes to enums...

The more I work with enums, the more I think that we should probably represent them in generated code as an integer value that represents their unique order in the enumerated type (as determined by the `chpl__enumToOrder()` function, yielding 0, 1, 2, 3, ...).  The advantages it seems like this would yield include:

* no ambiguity w.r.t. enums with an identical value as noted in issue #9786 
* supports creating easy lookup tables between an enum's execution-time value in the generated code to its underlying integer value (when available) or string representation
* permits ranges on enums to do less conversion back and forth between representations

I'd be inclined to say that the width of the integer used to store the enum is implementation-dependent, but guaranteed to be large enough to store all the enums (where, in general, 8 bits is likely to be sufficient as Michael notes above).  I'd also propose providing users with a means of specifying a specific representation width, as with bools, for those who want to optimize for memory usage or alignment (similar to what @ben-albrecht proposes is issue #5417).

Some open questions that remain for me:
* what are the implications for the LLVM back-end?  How does it represent enums?
* what are the implications for interoperability (passing enums to/from extern routines;  extern enums)?
* what are the implications, if any, for binary I/O?

**Comment by bradcray** [comment]
At this point, I think this issue is in much better shape on master today, and is subsumed by #10307 and #10139 as far as future efforts go, so I'm going to close it.  Thanks for the discussion!
