### ISSUE TITLE
lvalue error in creating an array of Owned with forall expr

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#8596]
This is forked off of #6044 since part of the original problem has since been solved in PR #8501.

### Summary of Problem

``` chapel
use OwnedObject;

class C {
  var x: int;
}

proc main() {
  const a = [i in 1..3] new Owned(new C(i));

  writeln(a);
}
```

**Associated Future Test(s):**

test/classes/delete-free/owned-init.chpl

**Comment by cassella** [comment]
This future was retired by #9748
