### ISSUE TITLE
lvalue error in creating associative array of Owned

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#8597]
This is split off from issue #6841.

**Source Code:**

```chpl
use OwnedObject;

class Turtle {
  var x: int;
  var D: domain(string);
  var A: [D] Owned(Turtle);
}

var worldTurtle = new Turtle();
```

**Compiler Error Message:**

```
$CHPL_HOME/modules/internal/DefaultAssociative.chpl:572: In function 'clearEntry':
$CHPL_HOME/modules/internal/DefaultAssociative.chpl:574: error: illegal lvalue in assignment
```

**Comment by cassella** [comment]
Changing `Owned(Turtle)` to `owned Turtle`, this compiles and runs.

I added a `writeln(worldTurtle)` at the end, and further making `D` non-empty,

`  var D: domain(string) = {"down"};`

compiles but fails at runtime:

```
{x = 0, D = {down}, A = $CHPL_HOME/modules/internal/OwnedObject.chpl:371: error: halt reached - argument to ! is nil
```

It works fine again with `owned Turtle?`.

**Comment by mppf** [comment]
@cassella - thanks. The remaining TODO is covered by #13602 so I'll close this one.
