### ISSUE TITLE
Theme: Performance

### ISSUE THREAD

**Issue by benjamin-robbins** [chapel-lang/chapel#8608]
Theme for epics and stories related to Chapel Language Performance

**Comment by bradcray** [comment]
@chapel-lang/perf-team : @mstrout pointed out this issue and I tend to think that it doesn't serve a lot of value.  We'll be working on performance until the end of time (if we're successful) and have a performance label we can apply to issues that relate to performance.  Closing as a result, but if anyone disagrees, we can reopen.
