### ISSUE TITLE
Chapel 2.0

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#8614]
As a Chapel Programmer, I want to have confidence that the core language is not going to change, without due process, in ways that will break my existing programs because I don't want to have to rewrite them for each subsequent release.

Acceptance criteria:
TBD

**Comment by mppf** [comment]
@bradcray - it seems to me that we need to define zippering between different domain/array types, e.g. sparse and dense, dense and associative. We've talked about this before in various places but I don't see an issue about that question exactly. This seems to be a Chapel 2.0 issue to me though. It's a pretty easy problem to run in to when writing code working with sparse or associative domains and arrays. #6577 and #9437 seem to be issues discussing a facet of it. Shall I create an issue for the language design to-do?

**Comment by mppf** [comment]
More generally, should there be a Leader-Follower 2.0 epic?

**Comment by mppf** [comment]
I created #11504 and #11505.

**Comment by mppf** [comment]
@lucaferranti - good point, I will close it.
