### ISSUE TITLE
Owned(T) default intent

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#8618]
Right now, an Owned argument that transfers ownership needs to use the 'in' or 'ref' intent, rather than the default of 'const ref'.

But arguably a 'const ref' Owned is as good as a borrow and so maybe that's not the right default intent. Furthermore, comparing a default-intent Owned passed to a function with an argument of class type, the argument of class type is a pointer to the instance, while the Owned argument has const ref default intent - meaning that it's a pointer to a pointer to the instance. Thus, changing an argument from a class type to an Owned can have performance consequences. (This might appear to be an issue with using Owned more generally). For example:

``` chapel
// data is an Owned(MyClass) per regular instantiation rules
proc process(data) {
  var sum = 0;
  for i in 1..n {
    sum += data.value; // double-deref here, in case of owned data
  }
}
proc test() {
  var data = new Owned(MyClass(1));
  process(data);
}
```

Another issue with the current default intent is that it might not be obvious to users when the 'in' or 'ref' intent is required to transfer ownership. See for example issue #8604.

A further issue with the current default intent is that it interferes with a simple implementation of the desired subclass type behavior, at least when the Chapel compiler generates C. See issue #8489.

We could consider:
 * making the default intent to "borrow" - but that might present problems if we want the argument to continue to have Owned type. Certainly we could adjust the compiler to generate a code pattern we want for this case (e.g. by copying in the value of the Owned record but not destroying it in the called function).
 * making the default intent be "in" but change "in" to mean shallow copy and rely on other (more explicit) means to implement ownership transfer / sharing
 * making the default intent ref-if-modified similarly to arrays (see issue #5219)
 * the default intent for Owned is to transfer ownership but generics instantiate differently.
 * the default intent for Owned is to transfer ownership including in generics

**Comment by mppf** [comment]
Issue #8489 describes a problem with handling subclassing for `const ref` class arguments. The same problem would apply to `Owned` if it's passed by const ref, and that suggests to me that it's important that the default be "borrow".

**Comment by mppf** [comment]
When I say the default Is "borrow", that might mean two things:
 1. blank-intent Owned(SomeClass) simply changes into SomeClass during compilation
 2. it remains Owned(SomeClass) but has borrow-like behavior.

The disadvantage of 1 is that it might hinder /surprise when doing generic programming.
The disadvantage of 2 is that it requires the compiler understand a new intent (even if the language does not get a new intent) which would be something like "copy the bits in, don't run the copy initializer, don't destroy".

**Comment by mppf** [comment]
Here's an example of a generic program that would depend on the difference between 1 and 2 above:

``` chapel
proc addTwo(arg) {
  globalArray.push_back( new arg.type() );
}
addTwo(new Owned(new MyClass()));
```

Interestingly, that one would work equally well for choice 1 above if 'new' returned an 'owned' by default. And, if all 'new' had to be annotated with 'owned', the above code would error anyway.

Here's another example, where the type is merely used as a part of a type specifier:
``` chapel
proc addToArray(in val, ref array:[] val.type) {
  array.push_back(val);
}
var A:[1..0] Owned(MyClass);
addToArray(new Owned(new MyClass())); 
```

That wouldn't compile if we chose option 1, since an array of Owned won't coerce to an array of borrows.

**Comment by vasslitvinov** [comment]
Interesting side question: what does the expression `new T` mean when T is (a) owned, (b) borrow, (c) unsafe ?

**Comment by vasslitvinov** [comment]
What if the default and 'const' intents for "owned" mean 'const in' with borrow behavior? That is, in contrast to an explicit '[const] in', it would not take over the ownership and not delete at the end of the function.

This way we can say that the default and 'const' intent for class types is 'const in' regardless of whether it is owned, borrow or unsafe.

**Comment by mppf** [comment]
> Interesting side question: what does the expression new T mean when T is (a) owned, (b) borrow, (c) unsafe ?

I interpret this question as refering to a generic instantiation context, e.g.
``` chapel
proc makeit(type t) {
  return new t();
}
```

In that event:
 * `makeit(owned MyClass)` would result in an `owned MyClass`
 * `makeit(raw MyClass)` would result in a `raw MyClass`
 * `makeit(MyClass)` (ie borrow) would result in an error, or do whatever `new MyClass()` does.

**Comment by mppf** [comment]
> What if the default and 'const' intents for "owned" mean 'const in' with borrow behavior? That is, in contrast to an explicit '[const] in', it would not take over the ownership and not delete at the end of the function.
>
> This way we can say that the default and 'const' intent for class types is 'const in' regardless of whether it is owned, borrow or unsafe.

I think we still have to explain the difference between ownership transfer and borrowing, but I'm generally leaning towards a design where the default and `const` intent create some kind of borrow.

One interesting question is whether `const in` for `shared` is a "borrow" or an "ownership transfer". In the context of `shared` (or even `owned`), the difference between `const in` and `in` is just whether or not the argument (which is potentially the result of copy initializing) can be modified within the function. So it seems strange to me to make `const in` borrow but `in` transfer ownership.

**Comment by mppf** [comment]
> When I say the default is "borrow", that might mean two things:
>  1. blank-intent Owned(SomeClass) simply changes into SomeClass during compilation
>  2. it remains Owned(SomeClass) but has borrow-like behavior.
> 
> The disadvantage of 1 is that it might hinder /surprise when doing generic programming.
> The disadvantage of 2 is that it requires the compiler understand a new intent (even if the language does not get a new intent) which would be something like "copy the bits in, don't run the copy initializer, don't destroy".

A further issue with 2 is that it creates a situation where we have an Owned that is a Borrow. But the whole point of introducing different types for these things is so that people and the compiler can reason about them! If it's behaving as a Borrow, shouldn't it have a Borrow type, rather than an Owned type?

So, let's think about Option 1 some more.

I think the implication is that the generic author would need to explicitly opt-in to accepting and instantiating with Owned/Shared/etc types, since by default the generic would only work with borrows. Consider the array type, which is generic. Without some way of telling the compiler, "It's OK to instantiate this type for managed pointers", it would only be possible to construct arrays of borrows. We've been through this topic before, with #8652. If the Owned-ness of an actual doesn't impact the argument type used when instantiating a generic, for the purposes of generic instantiation it's behaving "like ref". Interestingly, a workaround is available (as described in that issue) which is to introduce a record wrapping an Owned field, and then instantiate the generic (e.g. array) with that.

E.g. in

``` chapel
proc cloneToArray(x: shared?) {
  var A:[1..10] x.type;
  for a in A {
    a = x;
  }
}
```

the `shared?` would mean "I can be instantiated with a Shared argument or a borrow". We might also have `managed` to mean Shared/Owned and `managed?` to mean borrow/Shared/Owned.

**Comment by mppf** [comment]
Over on #8939, we've been talking about how `in` might not be the best way to describe ownership transfer. What if we changed `in` intent and variable initialization for Owned/Shared to mean "shallow copy" (which is certainly borrow-like in some ways)?

``` chapel
// data is an Owned(MyClass) per regular instantiation rules
proc process(data) {
  var sum = 0;
  for i in 1..n {
    sum += data.value; // no double-deref, since Owned record was shallow-copied in
  }
}
proc test() {
  var data = new Owned(MyClass(1));
  process(data);
}
```

I think my main reservation about this idea is that it's unclear to me how the compiler will know when it should delete the memory managed by an Owned. In the current implementation, it knows to delete all Owned records when they go out of scope. While making the shallow copy solves the double dereference problem, now how will the compiler know to delete the `Owned(MyClass)` in `test` but not in `process`?
