### ISSUE TITLE
Add `array.front()` and array.back()`

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#8620]
Following on from #8601, getting the last element from an array before executing `array.pop_back()` requires using the array's domain (or implicitly knowing what that last index is from the size).
```chpl
writeln(arr[arr.domain.last]);
```

Please consider adding C++ `std::vector`-style convenience functions **`array.front()`** and **`array.back()`** to retrieve the respective elements.

**Comment by daviditen** [comment]
I think the request for these methods sounds good independently from what happens with #8601.
