### ISSUE TITLE
`list.pop_front` should not return a value

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#8621]
From #8601, `array.pop_back()` doesn't return a value for exception safety (I agree).

Therefore, `list.pop_front()` probably shouldn't return a value either (and currently does).

**Comment by mppf** [comment]
I disagree about `array.pop_back()` not returning a value for exception safety. See https://github.com/chapel-lang/chapel/issues/8601#issuecomment-369608650

**Comment by daviditen** [comment]
Michael's argument in #8601 has me convinced that `array.pop_back()` should return the popped value, so I think `list.pop_front()` should continue to as well.

**Comment by BryantLam** [comment]
@daviditen: Any consideration for implementing #10148 on lists and possibly other relevant data structures?
