### ISSUE TITLE
UTF-8 strings

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#8635]
As a Chapel Programmer, I want the language's strings and their supporting library routines to support UTF-8 strings because I want to be able to represent unicode characters and consider UTF-8 to be the dominant choice for doing so.

Acceptance criteria:
I can write programs defining UTF-8 string literals and variables and calling all of the string library routines on them.

**Comment by bradcray** [comment]
@e-kayrakli: Searching for something else, I just stumbled into a raft of issues like this that made me ask "can this be closed now?"

**Comment by e-kayrakli** [comment]
We still have https://github.com/cray/chapel-private/issues/407 in my backlog as part of this epic. But it is not a priority for 1.21 release. The most "epic" parts of this epic is done, though. So, closing it wouldn't cost us anything important IMO. @mppf, do you have a preference?

**Comment by mppf** [comment]
It'd be fine to close it; we just need to keep track of 407.

**Comment by bradcray** [comment]
I think for all intents and purposes, this epic is done.  We could keep it open because there may be additional improvements and refinements and additions to UTF-8 strings, but by that argument, we would potentially have epics open eternally for all language features. :)

**Comment by e-kayrakli** [comment]
407 is relatively high in my backlog, and we had a discussion with @bradcray about it earlier in the release cycle. I expect we'll have another one early in the next cycle, too :)

I am closing this.

**Comment by bradcray** [comment]
I personally don't feel deeply worried about 407, but that could be because I don't understand how terrible it is not to have it for the time being (and to just rely on documentation to say what we expect).
