### ISSUE TITLE
Finalize meaning of 'in'/'out'/'inout' argument intents

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#8637]
As a Chapel Programmer, I want the definition of the 'in', 'out', and 'inout' argument intents to stabilize so that I don't need to change my programs in the future to deal with future changes to these intents.

Acceptance criteria:
Team determines and documents semantics of 'in', 'out', and 'inout' such that user code will not break in the future.

---

This can be a breaking change because some programs using `out` or `inout` might have fewer record copy-initializations and/or deinitialize records in different places. As of 10/01/2019, @mppf believes `in` is working reasonably well although not documented in the spec (it is however documented in [CHIP 13](https://github.com/chapel-lang/chapel/blob/master/doc/rst/developer/chips/13.rst) ).

**Comment by mppf** [comment]
I'd view this as having a few reasonable next steps:
 * for `in` intents, which are handled reasonably well at this point (as far as I know), it's mainly a documentation issue. Consider migrating some of CHIP 13 to the language specification.
 * come up with a strategy for `out` intent. Main issue here is that it can be set multiple times.
 * come up with a strategy for `inout`
 * reconsider enabling the expiring value optimization (while this isn't strictly about intents, it's thematically related, and might suggest a different strategy for explaining the language copy rules). See #9490.

**Comment by mppf** [comment]
Note that an improved strategy for `out` could allow `out` arguments that cannot be default initialized. Right now, you can't have an `out` for a non-nilable class type.
