### ISSUE TITLE
VS Code IDE integration

### ISSUE THREAD

**Issue by benjamin-robbins** [chapel-lang/chapel#8642]
As a Chapel Programmer, I want to be able to use VS Code to write my Chapel programs in because I and most efficient/comfortable utilizing an IDE.

Acceptance Criteria:
Open VS Code, write program, chapel syntax, compilation, debugging supported.

**Comment by Dunky13** [comment]
I would like to have IDE support as well. 
Currently using the JetBrains IDE stack (PyChar, Intellij, CLion etc)
Would be neat if there is IDE support, whether it is VS Code, Atom, CLion. Doesn't really matter.
But having autosuggest, autocomplete, built-in docs etc would be really helpful

**Comment by fsouza** [comment]
Ideally it would be something a LSP server (https://langserver.org/), so multiple IDEs could benefit from a single implementation :D

**Comment by jabraham17** [comment]
Closing this, we have a [VSCode extension](https://marketplace.visualstudio.com/items?itemName=chpl-hpe.chapel-vscode) for Chapel that utilizes the language servers provides by `chpl-language-server` and `chplcheck`.
