### ISSUE TITLE
owned & borrowed syntax proposal: owned type, new returns owned

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#8651]
Previous: none. Next: #8652.

General idea: `MyClass` refers to a borrow, `owned MyClass` refers to an owning pointer. `owned` works as a record similar to the current `Owned` record. `new MyClass()` returns an `owned MyClass`. Implicit coercions from owned to borrow. Ownership transfer possible on `=` as assignment or copy-initialization, or on `in` intent.

### Locales Primer Example
``` chapel
class Node {
  var data: real;
  var next: owned Node;
}
var head    = new Node(0); // owned
var current = head.borrow();
for i in 1..numLocales-1 do on Locales[i] {
  current.next = new Node(i);
  current      = current.next.borrow();
}
```

### Generic Collection Example
``` chapel
record Collection {
  var element;
}
proc Collection.addElement(in x) {
  element = x;
}
proc test() {
  var c: Collection(owned MyClass);
  c.addElement(new MyClass(1));
  var d: Collection(int);
  d.addElement(2);
}
```

### Generic Function Example
``` chapel
// data is an owned MyClass per regular instantiation rules
proc process(data) {
  var sum = 0;
  for i in 1..n {
    sum += data.value; // double-deref here, in case of owned data
  }
}
proc test() {
  var data = new MyClass(1); // returns owned MyClass
  process(data);
}
```

### Borrow into Argument Record
``` chapel
record Argument {
  var data;
}
proc process(arg:Argument) {
  ... use arg.data ...
}
proc test() {
  var data = new MyClass(1); // returns owned MyClass
  var arg:Argument(MyClass) = new Argument(data.borrow()); // record stores borrow
  process(arg); 
}
```
 
### Function returning newly allocated object
``` chapel
proc returnNewMyClass() : owned MyClass {
  return new MyClass(1);
}
proc wrapReturnNewMyClass() {
  return returnNewMyClass(); // return type inferred as owned MyClass
}
```

### Function returning a borrow
``` chapel
proc returnBorrowGlobal() : MyClass {
  return globalMyClass.borrow();
}
proc wrapReturnBorrowGlobal() {
  return returnBorrowGlobal(); // return type inferred as MyClass
}
```

### Does specifying type change new?
``` chapel
var myC = new MyClass(1);
// myC has type owned MyClass

// vs
var myC:MyClass = new MyClass(1);
// compiler error/warning on borrow from temporary owned
```

**Comment by BryantLam** [comment]
Casual thought, what if a new type was introduced for `owned`? I haven't thought through all of the ramifications so this might be a really bad idea.

### Locales Primer Example
```chpl
owned Node { // <---
  var data: real;
  var next: Node; // <---
}
var head    = new Node(0); // owned
var current = head.borrow();
for i in 1..numLocales-1 do on Locales[i] {
  current.next = new Node(i);
  current      = current.next.borrow();
}
```

**Comment by mppf** [comment]
re. `owned Node { .... fields ... }`, that's an interesting idea, but it doesn't answer one of the key questions here. Certainly if it was `owned Node` it wouldn't be surprising that `new` returned `owned`. But what would be the type returned by `head.borrow()`? How would a field in a record, say, differentiate between owning and borrowing?

**Comment by lydia-duncan** [comment]
> Generic Function Example
```
// data is an owned MyClass per regular instantiation rules
proc process(data) {
  var sum = 0;
  for i in 1..n {
    sum += data.value; // double-deref here, in case of owned data
```

I don't understand this part.  Is that going to be an error case?  Or is this just a description of how the access occurs?

**Comment by mppf** [comment]
> > Generic Function Example
> ```
> // data is an owned MyClass per regular instantiation rules
> proc process(data) {
>   var sum = 0;
>   for i in 1..n {
>     sum += data.value; // double-deref here, in case of owned data
> ```
> 
> I don't understand this part.  Is that going to be an error case?  Or is this just a description of how the access occurs?

Since owned is really a record, it passes by `const ref` by default. So in the `process` function, the `data` would be more fully spelled out as `const ref data:owned MyClass`. Thus accessing the value of data involves two dereferences:
 1. Reading the pointed to instance from the Owned (since we have the record by const ref).
 2. Reading the numeric value from the MyClass field.

Compare with the pre-Owned / user calls `delete` scenario, where data would just be a `MyClass` and so there would only be the second of these two dereferences in the loop. Of course we could try to adjust the proposal further to handle that, but in my view it adds complexity and might morph it into another proposal anyway. (Basically we'd be changing it to "default intent is borrow").

**Comment by mppf** [comment]
Closing since we decided on #8938
