### ISSUE TITLE
owned & borrowed syntax proposal: owned type, explicit new

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#8654]
Previous: #8653. Next: #8667.

General idea: `MyClass` refers to a borrow, `owned MyClass` refers to an owning pointer. All `new` calls on class types must be marked as `owned` or `unsafe`.

Note, this proposal has changed from earlier versions. It now includes:

Additionally, as a special case, an `owned` passed by blank intent is a borrow (i.e. the pointer type) rather than a `const ref owned(T)`. See issue #8618.

### Locales Primer Example
``` chapel
class Node {
  var data: real;
  var next: owned Node;
}
var head    = new owned Node(0);
var current = head.borrow();
for i in 1..numLocales-1 do on Locales[i] {
  current.next = new owned Node(i);
  current      = current.next.borrow();
}
```

### Generic Collection Example
``` chapel
record Collection {
  var element;
}
proc Collection.addElement(in x) {
  element = x;
}
proc test() {
  var c: Collection(owned MyClass);
  c.addElement(new owned MyClass(1));
  var d: Collection(int);
  d.addElement(2);
}
```

### Generic Function Example
``` chapel
// data is an owned MyClass per regular instantiation rules
// default intent for that is "borrow"
proc process(data) {
  var sum = 0;
  for i in 1..n {
    sum += data.value; // single-deref here, in case of owned data
  }
}
proc test() {
  var data = new owned MyClass(1);
  process(data);
}
```

### Borrow into Argument Record
``` chapel
record Argument {
  var data;
}
proc process(arg:Argument) {
  ... use arg.data ...
}
proc test() {
  var data = new owned MyClass(1);
  var arg:Argument(MyClass) = new Argument(data.borrow()); // record stores borrow
  process(arg); 
}
```
 
### Function returning newly allocated object
``` chapel
proc returnNewMyClass() : owned MyClass {
  return new owned MyClass(1);
}
proc wrapReturnNewMyClass() {
  return returnNewMyClass(); // return type inferred as owned MyClass
}
```

### Function returning a borrow
``` chapel
proc returnBorrowGlobal() : MyClass {
  return globalMyClass.borrow();
}
proc wrapReturnBorrowGlobal() {
  return returnBorrowGlobal(); // return type inferred as MyClass
}
```

### Does specifying type change new?
``` chapel
var myC = new owned MyClass(1);
// myC has type owned MyClass
var myC:MyClass = new owned MyClass(1);
// myC has type MyClass

var myC = new owned MyClass(1);
// myC has type owned MyClass
var myC:owned MyClass = new owned MyClass(1);
// myC has type owned MyClass

var myC = new MyClass(1);
// compilation error
var myC:MyClass = new MyClass(1);
// compilation error
```

**Comment by lydia-duncan** [comment]
This doesn't have an example of it, but I'm assuming the other `new` syntax would be `new unsafe MyClass(1)` and record `new`s would be unaffected?

I find this idea intriguing.  What would happen with the following code?
```chapel
var c = new owned MyClass(1);
c = new unsafe MyClass(2); // c now refers to a borrow
// Would the old value of c get cleaned up before getting the new value?
// What about the reverse case?
// Or is this just an error?
delete c;
```

**Comment by mppf** [comment]
> This doesn't have an example of it, but I'm assuming the other `new` syntax would be `new unsafe MyClass(1)` and record `new`s would be unaffected?
> 
> I find this idea intriguing.  What would happen with the following code?
> ```chapel
> var c = new owned MyClass(1);
> c = new unsafe MyClass(2); // c now refers to a borrow
> // Would the old value of c get cleaned up before getting the new value?
> // What about the reverse case?
> // Or is this just an error?
> delete c;
> ```

AFAIK this would be an error as the assignment on the 2nd line won't resolve. `c` has type `owned MyClass` and we won't have an `=` function with `owned MyClass` LHS and `unsafe MyClass` RHS. (We'd want users to call c.retain in such a case).

What about the reverse case? I'm guessing that this is what you mean:

```chapel
var c = new unsafe MyClass(1);
c = new owned MyClass(2);
delete c;
```

Here, it depends on some open design questions about coercions between the borrow type and the raw/unsafe pointer type (discussed in issue #8375). If we allow no coercions involving unsafe pointers or only coercions from raw -> borrow type, the assignment on the 2nd line is still an error. While `new owned MyClass(2)` can coerce into `MyClass` (aka the borrow type), `unsafe MyClass` is a *different type from the borrow type* and we won't perform coercions for the LHS of assignment (for type safety reasons, since it's a `ref` argument).. Note that Rust allows coercions from a borrow to an unsafe pointer - so if we followed that design, the assignment line would compile since the Owned could coerce to the unsafe pointer. But in that event I'd consider the resulting memory errors squarely in the user's court, since they were using an `unsafe` pointer type after all.

**Comment by mppf** [comment]
I just edited the "Does specifying type change new?" section, because I think I had made an error there. So I think this has the same problem as #8651.

**Comment by bradcray** [comment]
I think in this description of the proposal:

> All new calls must be marked as owned or unsafe.

the intention is that "All `new` calls on **class** types must be...":  (?)


> I just edited the "Does specifying type change new?" section, because I think I had made an error there. So I think this has the same problem as #8651.

Assuming you're referring to this:

> ```chapel
> var myC = new owned MyClass(1);
> // myC has type owned MyClass
> var myC:MyClass = new owned MyClass(1);
> // myC has type MyClass
> ```

I don't find this offensive/surprising as #8651 because if you asked me "What does `new owned MyClass()` return, I'd look at the expression and say "an `owned MyClass`.  So the thing I'd really be curious about was whether these two declarations had the same effect:

```chapel
var myC = new owned MyClass(1);
var myC: owned MyClass = new owned MyClass(1);
```

(where I think the answer is "yes, they do" (?)).

The cousin of this question (for any of these proposals) would be whether the following two declarations behaved the same (or at least, unsurprisingly):

```chapel
var myC = new MyClass(1);
var myC: MyClass = new MyClass(1);
```

If I'm understanding the proposal properly, these wouldn't be legal (the `new` on a class type must be decorated), so these behave consistently at least.  And then the third case would be:

```chapel
var myC = new unsafe MyClass(1);
var myC: unsafe MyClass = new unsafe MyClass(1);
```

which also behave similarly.

One thing I like about this proposal is that there isn't an implicit/subtle switching between owned and borrow based on context.  I'd keep this one in the running.  I'm not wild about `unsafe` as a keyword or descriptor here since these classes could be used in a safe way -- they're just leaving you to your own devices to achieve that.

**Comment by bradcray** [comment]
Comparing this to #8653 a bit more, I guess I'm not seeing why the choice of what happens to `owned` arguments sent to a generic formal isn't independent of whether `owned` is specified explicitly or not in other contexts.  Aren't those two distinct choices?

**Comment by mppf** [comment]
I'm curious about the impact of this proposal on generic code.

Do we have code that takes in a `type t` argument and then tries to `new` it? Presumably such code would no longer work on both records and classes without modification, right?

```
proc makeIt(type t) {
  return new t(1);
}
```

now you'd have to write
```
proc makeIt(type t) where isClass(t) {
  return new owned t(1);
}
```

**Comment by bradcray** [comment]
> now you'd have to write
> ```chapel
> proc makeIt(type t) where isClass(t) {
>    return new owned t(1);
> }
> ```

Or maybe you'd have to write `makeIt(owned C)` or `makeIt(raw C)` rather than `makeIt(C)`?

**Comment by mppf** [comment]
yes, I'd hope you could do both.

**Comment by mppf** [comment]
What would happen with this proposal if you have a record, say `SomeRecord` and you `new owned SomeRecord()` or `new unsafe SomeRecord()`?

I think the options are:
 * compiler error (you can't make an owned record)
 * ignore owned (since records behave as though "owned" anyway), but error for unsafe
 * ignore owned and unsafe

where the latter 2 options would be in the spirit of enabling more generic code to work for both records and classes.

**Comment by vasslitvinov** [comment]
Require the addition of something in every 'new' expression feels too burdensome on users. Especially because a lot of existing class-based code will need to change. Although I do not have much experience writing code with 'new', so it may be OK in practice.

I propose to provide a default for 'new C()'. It would mean a borrow from a temp that gets deleted at the end of the lexical scope. This is quite limiting I think, so we have room to relax it in the future.

**Comment by vasslitvinov** [comment]
> What would happen with this proposal if you have a record, say SomeRecord and you new owned SomeRecord() or new unsafe SomeRecord()?

I vote to allow one or both to support writing generic code.

**Comment by mppf** [comment]
> I propose to provide a default for 'new C()'. It would mean a borrow from a temp that gets deleted at the end of the lexical scope. This is quite limiting I think, so we have room to relax it in the future.

I had earlier created #8938 to describe this story. I think (from an implementation perspective) it makes sense to start without a default for 'new C' and then decide what it should be with the benefit of experience with the general design.
