### ISSUE TITLE
Test "library/packages/ZMQ/interop-py/server" broke. Pip/virtualenv/shebang problem.

### ISSUE THREAD

**Issue by awallace-cray** [chapel-lang/chapel#8668]
03/01/2018: Jenkins nightly gasnet-fast test (Jenkins `chapcs-correctness-test-gasnet-fast/583`), chpl test `library/packages/ZMQ/interop-py/server` started throwing errors on 02/27, after "virtualenv" was system-installed on chapcs09 on 02/26. 
```
[Success compiling library/packages/ZMQ/interop-py/server]
[Executing ./PREEXEC]
New python executable in pyzmq-venv/bin/python
Installing setuptools, pip, wheel...done.
./PREEXEC: /ptmp/jenkins/chapel-ci/workspace/chapcs-correctness-test-gasnet-fast/test/library/packages/ZMQ/interop-py/pyzmq-venv/bin/pip: /ptmp/jenkins/chapel-ci/workspace/chapcs-correctness-test-gasnet-fast/test/li: bad interpreter: No such file or directory
[Executing program ./server -nl 1 < /dev/null]
[Error: Timed out executing program library/packages/ZMQ/interop-py/server]
[Execution output was as follows:]
Traceback (most recent call last):
  File "client.py", line 2, in <module>
    import zmq
ImportError: No module named zmq
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
chapelu  45029  199  0.0 209175272 10172 ?     SNl  04:26  16:39 ./server_real -nl 1
```

Virtualenv was system-installed at my request, while trying to fix the broken c2chapel test job. 

The chpl test failed because the "pip install" run by the PREXEC did not work, and thus the requirements for this chpl test were not available in the new virtual env.  The PREEXEC:
```
#!/usr/bin/env bash

if [[ ! -f pyzmq-venv/bin/activate ]] ; then
    virtualenv pyzmq-venv
    source pyzmq-venv/bin/activate
    pip install -r requirements.txt
    deactivate
fi
```

The root cause is a kernel config limit that truncates over-long shebang lines in executable script files- in this case, the temporary "pip" script file installed by that PREEXEC in the new virtual env. 
```
# 2018/03/01-13:40:12 chapelu@chapcs09 # head /ptmp/jenkins/chapel-ci/workspace/chapcs-correctness-test-gasnet-fast/test/library/packages/ZMQ/interop-py/pyzmq-venv/bin/pip
#!/ptmp/jenkins/chapel-ci/workspace/chapcs-correctness-test-gasnet-fast/test/library/packages/ZMQ/interop-py/pyzmq-venv/bin/python
```
This kernel config limit seems unique to SLES-12, as far as I know at this point. According to a quick search, the kernel variable is named BINPRM_BUF_SIZE.

This case is complicated- although this chpl test was PASSING prior to 02/27, it (the PREEXEC) was still not working exactly as intended. 
```
[Success compiling library/packages/ZMQ/interop-py/server]
[Executing ./PREEXEC]
./PREEXEC: line 4: virtualenv: command not found
./PREEXEC: line 5: pyzmq-venv/bin/activate: No such file or directory
You 
...[truncated 11848 chars]...
ils.so
Successfully installed pyzmq-17.0.0
./PREEXEC: line 7: deactivate: command not found
[Executing program ./server -nl 1 < /dev/null]
[Elapsed execution time for "library/packages/ZMQ/interop-py/server" - 0.516 seconds]
[Executing prediff ./server.prediff]
[Executing diff server.good server.exec.out.tmp]
[Success matching program output for library/packages/ZMQ/interop-py/server]
```

Also: Why did the Jenkins job (or at least, that chpl test) not throw an error BEFORE 02/27, if those commands in the PREEXEC were failing, as they were?  That sounds like another issue I thought was fixed long ago (for SKIPIFs anyway). Refs: CHAPDEV-189, PR #5558

Also note: Other unrelated changes, possibly affecting Chapel's built-in test-venv, are being made this week.

**Comment by ben-albrecht** [comment]
Would updating the `PREEXEC` to call `python -m pip` instead of `pip` avoid this issue?

**Comment by ben-albrecht** [comment]
> Would updating the `PREEXEC` to call `python -m pip` instead of `pip` avoid this issue?

I am pleased to find the answer to this question is "yes".

FWIW, this can be reproduced on any linux machine with any Chapel configuration if you have a really long path (exceeds 128 chars). I renamed `chapel` directory to be a really long name to reproduce the error, and then replaced  `pip` with `python -m pip` in `PREEXEC` to test the above hypothesis.

PR incoming.

**Comment by awallace-cray** [comment]
2018-03-01 : The system-installed virtualenv (and pip) on chapcs09 **only** have been removed. 

This change was made in order to allow side-by-side testing on this issue, with and without system-installed virtualenv, on otherwise-identical systems.

The other chapcsNN systems still have their system-installed virtualenv (and pip), which were first installed on all chapcsNN on 02/26.

**Comment by awallace-cray** [comment]
There is no way to re-system-install virtualenv and pip before tomorrow. Maybe I can switch that job somewhere besides chapcs09 though.

**Comment by awallace-cray** [comment]
2018-03-02 : Jenkins test passed (job ran on chapcs08). 
I.T. has re-system-installed virtualenv and pip on chapcs09. 
Switching job config to run there, same as before this week.
