### ISSUE TITLE
Uninformative Error in Testing

### ISSUE THREAD

**Issue by Tshimanga** [chapel-lang/chapel#8669]
We created a class
```
  class BiMap {
    var keys: domain(string),
        ids:  [keys] int,
        idxkey: domain(int),
        idx: [idxkey] string;
        .
        .
        .
   }
```

and I went to write a field-wise union method I naively called it `union` which turns out is already a keyword in Chapel. So my test failed but the failure threw `syntax error at line...` which doesn't really describe the issue well. After realizing that it was really a namespace issue and *not* a syntax error, the test ran just fine.

**Comment by bradcray** [comment]
Syntax errors are, by nature, pretty hard to generate better error messages for.  I'll be curious if anyone on the dev team has any thoughts on this (I think @mppf looked into improving syntax errors recently?).  When I tend to make mistakes like this, I tend to rely on syntax highlighting in my editor to help point out that something is a reserved word (that said, I use the emacs syntax highlighter which isn't the greatest...).

As an aside, and for my own curiosity, I wanted to see how the syntax highlighter here on github would handle things, and interestingly it seems it does highlight `union` when it's followed by a colon or space, but not when it's followed by parenthesis:

```chapel
class BiMap {
  var x: int;
  var union: int;
  var union = 2;
  proc foo() { ... }
  proc union() { ... }
}
```

**Comment by mppf** [comment]
I believe I could improve the error message in this case but in the general case it's quite hard to get something better than "syntax error" out of a flex/bison parser for this class of error.

**Comment by bradcray** [comment]
Michael's concern reflects mine: that one could pour infinite effort into making our flex-/bison-based front-end report better errors for syntactically illegal code, but it's impossible to predict all the ways in which users might write illegal code, so unlikely that we'd be able to implement something that would catch the next case where you or some other user accidentally used a keyword in an incorrect context.  For that reason I'm tempted to label this issue as "won't fix" and close it:  I simply think there are other things that you'd find it more profitable for us to work on than writing a better error message for this case which you may never stumble into again (given that it would do nothing to address the many other equivalent issues like it that you might hit someday).

**Comment by cassella** [comment]
FWiW, the error message is somewhat improved now (for Brad's code):

```
foo.chpl:3: syntax error: near 'union'
```

(And if the two `var union` fields are renamed, the same error for line 6.)

**Comment by bradcray** [comment]
I'm going to close this on the argument that it's improved, and also that it's hard to know how to improve it much more (which I guess is what I proposed 5 years ago).
