### ISSUE TITLE
Add "mason test" target

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#8714]
`Twouldn't surprise me a jot if some people lobbied to break this into multiple tickets.

This idea combines two efforts. First, trying to move to a Masonic view of the world.  Second, the `start_test` functionality is kind of limited and too sensitive to the version of Python installed on the system, so we should move towards an application-centric test suite.

The idea would be that `mason test <optional file.chpl>` would enter the `test` directory, then compile and execute the test according to their `.compopts`, `.execopts`, `.good` etc.  

In practice, I have been moving towards `asserts` instead of `writeln`.  For instance, if I want to make sure a `domain(string)` has the entry `banjo`, a `writeln` may print `fiddle, banjo` or `banjo, fiddle`, so asserting the entries is more reliable than assuming a print order.  As @bradcray points out, this is less interesting, but can be useful in some contexts.

**Comment by buddha314** [comment]
Okay, I couldn't wait much longer. I start a test suite that sucks and needs your help: https://github.com/buddha314/Charcoal

**Comment by buddha314** [comment]
I don't know if this will go into Mason or not, but here is an example of how we are using   [Charcoal](https://github.com/buddha314/Charcoal) https://github.com/buddha314/numsuch/blob/develop/test/NumSuchTest.chpl it would be cool if the test suite was similar to this.

**Comment by Spartee** [comment]
This command is now supported with PR #9966
