### ISSUE TITLE
Refactor the locale models to take new initializer rules into account

### ISSUE THREAD

**Issue by dmk42** [chapel-lang/chapel#8732]
As a Chapel Implementer, I want to be able to copy an existing locale model to use it as a "good example," and then modify it to my needs because I don't want to have to start from a blank sheet of paper.

Acceptance Criteria:
Fields that should not change are `const`, or a workaround is in place to prevent them from being modified.

The locale models were originally designed for constructors.  They were then converted to use an older version of `init()`.  They have been patched to work with newer initializer rules, but this involved turning some `const` fields into `var` fields.  In the long run, the locale models should be refactored to be _based on_ the final version of the initializer rules, rather than minimally converted.

Some strategies for dealing with pointers to locale models as const fields in other locale models might be:

* Live with the loss of constness
* Be the base class when passing `this` to another locale model
* Wrap the field we wish were const in an accessor field that only grants read access

**Comment by benharsh** [comment]
As of #8790 you should now be able to pass ``this`` to ``new MemoryLocale(...)`` before calling ``this.complete``.

**Comment by benharsh** [comment]
This was pointed out to me as a still-open issue, and in revisiting this it appears we still need to address the non-const nature of the locale model fields. Ideally someone who is more currently familiar with locale model testing will take this on, though I'd be happy to assist in a pair-programming capacity. We should either:
a) refactor locale model initialization in a chapel-tastic manner, or
b) at the very least, add 'const' modifiers to the field accessor methods.

**Comment by bradcray** [comment]
The locale models are about to undergo a fairly massive refactoring (and hopefully simplification), so I'd be inclined to close this under the assumption that that new effort won't inherit the baggage of our current approach (and that we wouldn't want to clean up the current effort just to throw it away in the new effort).  Tagging @stonea and @mppf who've been discussing this lately, and @e-kayrakli due to his GPU leadership to see if anyone objects.

**Comment by benharsh** [comment]
Sounds good to me.

Closing due to impending refactoring.
