### ISSUE TITLE
chpldoc python 3 support

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#8756]
Generally, we strive to support Python 3 for user-facing features. The following steps should be taken to ensure `chpldoc` supports Python 3:

- [x] **Step 1:** Find out if the top-level `make chpldoc` target works with Python 3, i.e. if `chpldoc-venv` builds correctly with Python 3.

- [x] **Step 2:**
  - If it does not work, make necessary changes to support Python 3.
  - If it does work, add it to the python 3 nightly testing configuration.

Related: #8750

**Comment by ronawho** [comment]
https://github.com/chapel-lang/chapel/pull/9137 fixed Python 3 support. https://github.com/chapel-lang/chapel/pull/11729 will get us testing that support nightly.
