### ISSUE TITLE
Code cleanup: use `stripDirectories()` in computing executableFilename

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#8759]
In PR #8733, @cassella notes that the code I wrote re-implemented existing logic to strip
a filename down to its basename:

> FWIW, compiler/utils/file.cpp already has a stripdirectories()
> that returns a newly-allocated string containing just the basename,
> however long it is.

and that the code could be refactored to avoid this duplication.

**Comment by krishnadey30** [comment]
@bradcray I would like to work in this issue.

**Comment by krishnadey30** [comment]
@bradcray @ben-albrecht Please have a look at 
https://github.com/krishnadey30/chapel/

**Comment by krishnadey30** [comment]
I have opened a PR for this https://github.com/chapel-lang/chapel/pull/12546

**Comment by bradcray** [comment]
Hi @krishnadey30 — Thanks very much for taking this on.  I don't believe we have a contributors' agreement for you, which is required to contribute code to the Chapel project.  Please refer to the link and instructions here:  https://github.com/chapel-lang/chapel/blob/master/.github/CONTRIBUTING.md

**Comment by krishnadey30** [comment]
@bradcray sir, I have signed the licence and sent it. Please have a look.
