### ISSUE TITLE
Default initializers and records that store arrays of other records

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#8761]
### Summary of Problem
When a record with a default initializer stores as a field an array of other records with default initializers, we get an internal compiler error when trying to determine the argument type for the argument corresponding to the array field.

This is because when resolving the argument type the first time, we go down through array methods and when we try to initialize the contents, we consider the outer type's initializer as a candidate for the initializer call.  In considering that initializer, we attempt to determine its type from the expressions used to initialize it, but because we haven't finished resolving the array functions yet, their return type is dtUnknown.  We set the type of the array argument to dtUnknown and then try to determine the intent of that argument which triggers the internal compiler error.

If we limit the candidates searched for when resolving initializers to methods on the type we intend to get, we should be able to avoid this problem.  It is unclear whether this error will hide the appropriate error for records storing arrays of themselves, though.

### Steps to Reproduce

**Source Code:**

```chapel
record R {
  var x: int;
}

record StoresR {
  var x: [1..3] R;
}

var storing = new StoresR();
writeln(storing);
```

**Compile command:**
`chpl --force-initializers foo.chpl`

**Associated Future Test(s):**
[`test/classes/initializers/compilerGenerated/arrayOfOtherRecs-allDefault.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/compilerGenerated/arrayOfOtherRecs-allDefault.chpl) #8762

### Configuration Information

- Output of `chpl --version`: chapel 1.17.0 pre-release

**Comment by benharsh** [comment]
I don't see this error walking through methods on arrays. Has something changed on master since this issue was created?

**Comment by benharsh** [comment]
Oh, is the problem that we fail to resolve the type expr during candidate searching, and the go into wrapper creation with an unknown type? My (potentially faulty) interpretation of the issue text was that we try to do some resolution during wrapper creation.

**Comment by benharsh** [comment]
I have a fix for this issue now. I also discovered that the following future is also fixed by the same commit:

[test/classes/initializers/records/arrayOfOtherRecs-implicitType.chpl](https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/records/arrayOfOtherRecs-implicitType.chpl)
