### ISSUE TITLE
Initializers bug with default value on array argument with implicit type

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#8763]
### Summary of Problem
Initializers encounter a compilation segfault when they have an argument with an array default value and no explicit type.  This might be limited to when the array's element type is a record with an initializer, but I suspect it is not.

This does not impact ordinary functions.

### Steps to Reproduce

**Associated Future Test(s):**
[`test/classes/initializers/records/arrayOfOtherRecs-implicitType.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/records/arrayOfOtherRecs-implicitType.chpl) #8762 

### Configuration Information

- Output of `chpl --version`: chapel 1.17.0 pre-release

**Comment by benharsh** [comment]
This test has been passing for a while now, closing.
