### ISSUE TITLE
No constructors in our code

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#8772]
As a Chapel implementer, I anticipate the day when all constructors within our code (modules, tests) have been converted to initializers because it will increase my confidence that initializers are sufficient to replace constructors and that constructors can be deprecated (#8773).

Acceptance criteria:
A version of the compiler that complains about the presence of constructors in _any_ module (not just user modules) can be run on the test system without any complaints.

**Comment by buddha314** [comment]
Looks like Brad has recently been briefed on Agile!  It's great, but you'll get sick of it.

**Comment by bradcray** [comment]
@benharsh: I think we can close this now, right?
