### ISSUE TITLE
Use of 'this' within initializers

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#8779]
As a Chapel Programmer, I want to be able to call methods on `this` and pass `this` to functions in a way that respects its type because this permits my initializers to contain richer and more general code.  Specifically, in `D.init()`, between the call to `super.init()` and `initDone()`, I want to `this` to act like a `C` and after `initDone()`, I want it to act like a `D` (for a class `D` that's a subclass of `C`).  In an initializer that calls `this.init()`, I want it to act like a `D` after that point.

Acceptance criteria:
Users can refer to `this` after `this.init()`/`super.init()` and have it act like the type it should be at that time w.r.t. dynamic dispatch and other program semantics.

**Comment by benharsh** [comment]
Yes. The tests are located in [classes/initializers/phase1/dynamicThis](https://github.com/chapel-lang/chapel/tree/master/test/classes/initializers/phase1/dynamicThis) if you or anyone else want to verify that the desired features are supported.

**Comment by bradcray** [comment]
Let's close it then!
