### ISSUE TITLE
owned & borrowed syntax proposal: explicit new, explicit move

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#8797]
Previous: #8667. Next: #8938.

This is a variation on #8654.

General idea: `MyClass` refers to a borrow, `owned MyClass` refers to an owning pointer. All `new` calls must be marked as `owned` or `unsafe`. Instead of allowing ownership transfer on assignment or initialization, require a `move` keyword in those cases. The default intent for `owned` is `const in` but the in intent results in a shallow copy that is not deinitialized in the body of the function.

This issue has been edited to:
 * remove the rule about not requiring 'move' from a call return
 * = is not allowed between Owned/Shared
 * the default intent for Owned/Shared is now `const in` but this results in a shallow copy of the Owned/Shared record. The compiler never deinits Owned/Shared arguments - only variables.

### Locales Primer Example
``` chapel
class Node {
  var data: real;
  var next: owned Node;
}
var head    = move new owned Node(0);
var current = head.borrow();
// var current = head; would be an error since there is no 'move' there

for i in 1..numLocales-1 do on Locales[i] {
  current.next = move new owned Node(i);
  current      = current.next.borrow();
}
```

### Generic Collection Example
``` chapel
record Collection {
  var element;
}
// uses ref intent because in intent does not transfer ownership
proc Collection.addElement(ref x) {
  element = move x; // 'move' required here for Owned
}
proc test() {
  var c: Collection(owned MyClass);
  c.addElement(new owned MyClass(1));
  var d: Collection(int);
  d.addElement(2);
}
```

### Generic Function Example
``` chapel
// data is an owned MyClass per regular instantiation rules
// default intent for that is in, shallow-copy
proc process(data) {
  var sum = 0;
  for i in 1..n {
    sum += data.value; // single-deref here, in case of owned data
  }
}
proc test() {
  var data = move new owned MyClass(1);
  process(data);
}
```

### Borrow into Argument Record
``` chapel
record Argument {
  var data;
}
proc process(arg:Argument) {
  ... use arg.data ...
}
proc test() {
  var data = new owned MyClass(1);
  var arg:Argument(MyClass) = new Argument(data.borrow()); // record stores borrow
  process(arg); 
}
```
 
### Function returning newly allocated object
``` chapel
proc returnNewMyClass() : owned MyClass {
  return new owned MyClass(1);
}
proc wrapReturnNewMyClass() {
  return returnNewMyClass(); // return type inferred as owned MyClass
}
```

### Function returning a borrow
``` chapel
proc returnBorrowGlobal() : MyClass {
  return globalMyClass.borrow();
}
proc wrapReturnBorrowGlobal() {
  return returnBorrowGlobal(); // return type inferred as MyClass
}
```

### Does specifying type change new?
``` chapel
var myC = move new owned MyClass(1);
// myC has type owned MyClass

var myC:owned MyClass = move new owned MyClass(1);
// myC has type owned MyClass

var myC:MyClass = move new owned MyClass(1);
// error: can't move an owned into a borrow

var myC:owned MyClass = new owned MyClass(1);
// error: can't initialize owned without move
```

**Comment by mppf** [comment]
Adding the "no explicit move" rule doesn't seem to have really helped make the code clearer. Additionally, I worry that generic code would need "move" only when applied to Owned things. I suppose as it stands now generic code needs to be attentive to Owned because we don't auto-copy... but I'm not convinced of the benefit of require "move" be written.

**Comment by bradcray** [comment]
I seem to have overlooked the notification on this one's creation and almost missed reading it because it wasn't listed on the line listing the proposals on issue #8373.  I'm tempted to add it, but holding off in case I'm missing something.

**Comment by mppf** [comment]
I've updated this issue to explore removing the ownership transfer on `in` or variable initialization, since that's something we're talking about on issue #8939.

 * remove the rule about not requiring 'move' from a call return
 * = is not allowed between Owned/Shared
 * the default intent for Owned/Shared is now `const in` but this results in a shallow copy of the Owned/Shared record. The compiler never deinits Owned/Shared arguments.
