### ISSUE TITLE
Enable LinearAlgebra usage without BLAS/LAPACK dependencies

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#8803]
Currently, using the `LinearAlgebra` library requires compiling with BLAS & LAPACK. This can be burdensome for users to install and find the right flags to compile with, and many of the `LinearAlgebra` features do not rely on these libraries. Ideally, users should be able to compile and run programs using the subset of `LinearAlgebra` that does not rely on BLAS & LAPACK.

There are 2 mechanisms of accomplishing this (that I can think of at the moment):

1. Have a `config param` that specifies the user will be using native implementations, which will fold the `require` statements away and throw compiler errors for functions that require BLAS or LAPACK.

```chpl
// BLAS.chpl
if !noRequire {
  if isBLAS_MKL {
    require "mkl_cblas.h";
  } else {
    require "cblas.h";
  }
}
```

```chpl
// LinearAlgebra.chpl

private proc _csrmatmatMult(A, B) where noRequire {
  compilerError('Dependency error: matrix multiplication requires BLAS');
}
```

2. Put the `use` statements inside of the function bodies for functions that depend on them.

```chpl
private proc _matmatMult(A: [?Adom] ?eltType, B: [?Bdom] eltType) {
  use BLAS;
  ...
  gemm(A, B, C, 1:eltType, 0:eltType);
  return C;
}
```

**Comment by ben-albrecht** [comment]
Writing these examples out, option 2 seems more appealing, since it does not require modifying all the dependency modules.

Separately and slightly off-topic, having a way to ignore `require` statements does seem like a generally useful feature.

**Comment by bradcray** [comment]
> Separately and slightly off-topic, having a way to ignore `require` statements does seem like a generally useful feature.

I'm not sure what you're requesting here.  Your code suggests that you know we do have a way to ignore them (using param conditional folding).  Could you clarify?

Also the following code snippet from your issue makes me want to make sure you know that require statements can take param strings:

```chapel
  if isBLAS_MKL {
    require "mkl_cblas.h";
  } else {
    require "cblas.h";
  }
```

could be written:

```chapel
config param BLAS_header = if isBLAS_MKL then "mkl_cblas.h" else "cblas.h";

if !noRequire then
  require BLAS_header
```

**Comment by ben-albrecht** [comment]
> Your code suggests that you know we do have a way to ignore them (using param conditional folding). Could you clarify?

Yes - I mean a global compilation flag (or `config param`) that ignores *all* `require` statements, without requiring wrapping them all in a `param` conditional, which could vary from module to module. The use case would be anytime you want to overwrite dependencies in hard-coded `require` statements. Anyway, that's kind of tangential from what this issue sets out to accomplish, and should probably be discussed elsewhere.

> Also the following code snippet from your issue makes me want to make sure you know that require statements can take param strings

Oh. I like that! I was aware, but had not considered this. That seems like a good feature to add, regardless of which solution we pursue here.

**Comment by bradcray** [comment]
> The use case would be anytime you want to overwrite dependencies in hard-coded `require` statements.

It seems like a huge hammer to me to say "ignore _all_ `require` statements within a program when the client of a large set of libraries may (hopefully) have no idea what `require`s their dependencies contain nor how to fulfill them manually.  It also seems unlikely that, if a module does have true requirements, it would work without them being provided.

This is partly what led me to pointing out the possibility of using config param strings to specify the requirements.  Not only does it permit you to eliminate a conditional in the code each time you want to state that requirement, but it also permits the user to specify their own means of fulfilling that requirement using something not anticipated by the code (e.g., `chpl -sBLAS_header=\"myblas.h\"`).

Now, imagine that we extended `require` statements to permit empty requirement strings to be supplied and silently ignored (where today they generate a complaint that the file extension type is unknown).  In that event, you could compile with `chpl -sBLAS_header=\"\"` as a means of squashing the requirement completely.  And this would permit the module author to couple or decouple requirements as they chose, make them stricter or less strict, on whatever granularity made sense to their code.

Back to the big hammer point, it seems unlikely that even if I did want to squash the BLAS requirement in LinearAlgebra for some reason, I'd also want to simultaneously squash all other requirements in all other modules that I `use` (or at least, I don't see when a user would want to do that).

**Comment by ben-albrecht** [comment]
> Now, imagine that we extended require statements to permit empty requirement strings to be supplied and silently ignored (where today they generate a complaint that the file extension type is unknown). In that event, you could compile with chpl -sBLAS_header=\"\" as a means of squashing the requirement completely. And this would permit the module author to couple or decouple requirements as they chose, make them stricter or less strict, on whatever granularity made sense to their code.

Also really liking this idea. 👍 

> Back to the big hammer point, it seems unlikely that even if I did want to squash the BLAS requirement in LinearAlgebra for some reason, I'd also want to simultaneously squash all other requirements in all other modules that I use (or at least, I don't see when a user would want to do that).

Agreed. There may be a use case for this where an external tool managing dependencies such as Mason needs to override all `require` statements even if the library authors did not thoughtfully make their `require` statements take a `config param string`. However, that's not really relevant to the solution here, so we can cross that bridge when we come to it.

**Comment by ben-albrecht** [comment]
After much trial and error with many of the approaches discussed above, I was only able to get this functionality to work as intended by placing the `require` statements into each function body (thanks for suggestion @bradcray). With these changes, users will no longer need to link `BLAS` or `LAPACK` when using the `LinearAlgebra` library, unless they are making calls that end up using `BLAS` or `LAPACK` functions.

Here is the branch comparison:

https://github.com/chapel-lang/chapel/compare/master...ben-albrecht:blas-lapack-flags?expand=1

(I've also deprecated the `-isBLAS_MKL` flag for more robust flag `blasImpl` and `blasHeader` flags and added `MKL` support to `LAPACK` (#10251), but that could be separated out if deemed necessary.) 

One minor downside to this approach is that users of the low-level C interface will now need to explicitly add the `require` statements into their user code. However, I don't think this is a very important use-case to worry about.

@bradcray - Does this approach seem reasonable to you? If so, I'll pursue a PR for this branch.

As a follow-on to this, we could give the `LinearAlgebra` library a `config param` that allows users to say whether or not they will be linking `BLAS` or `LAPACK` so that we can give cleaner compiler errors when they call something that is not supported in native Chapel, as mentioned in the original issue description.

Separately, I'm considering opening an issue for exploring ways in which the language/compiler could better support dependent require statements.

**Comment by bradcray** [comment]
This generally sounds fine to me, and a brief glance looked OK, though GitHub only wanted to show me the BLAS diff, not LAPACK.

I'm trying to think about ways to permit the `require` to be put back into C_BLAS...  One approach without language changes might be to say that if we dead-code eliminate everything within a module (i.e., it was `use`d but not actually used), we could drop its `require` statements on the ground.  I think that would work for this case?  Or maybe it'd be more principled to say that we only run a module's `init()` routine if things within it are used/referenced outside of the module, in which case we could put the `require` into the `init()` routine?
