### ISSUE TITLE
mason run fails when top level directory is renamed

### ISSUE THREAD

**Issue by thomasvandoren** [chapel-lang/chapel#8817]
### Summary of Problem

I tried creating a mason package, and then renamed the top-level directory. I
expected that I could still run `mason run`, but I received an error.

### Steps to Reproduce

```bash
mason new FizzBuzz
mv FizzBuzz chapel-fizzbuzz
cd chapel-fizzbuzz
mason build
mason run
```

Actual output:

```
uncaught FileNotFoundError: No such file or directory (encountered when launching subprocess)
  $CHPL_HOME/modules/standard/SysError.chpl:397: thrown here
  ./MasonUtils.chpl:53: uncaught here
```

Expected output:

```
New library: FizzBuzz
```

### Configuration Information

I was running off PR #8784 branch on my mac.

- Output of `chpl --version`:
```
chpl version 1.17.0 pre-release (733d402765)
Copyright (c) 2004-2018, Cray Inc.  (See LICENSE file for more details)
```

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: clang
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: intrinsics
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none
```

- `mason --version`:
```
mason 0.1.0
```

**Comment by thomasvandoren** [comment]
As a work around, I update mason.chpl to read the Mason.toml file and use brick->name as the executable name. https://github.com/chapel-lang/chapel/compare/master...thomasvandoren:8817-mason-run

Is that a reasonable fix for this issue? If so, I'm happy to submit a PR from the above branch.

**Comment by thomasvandoren** [comment]
#7106 also mentions this issue.

**Comment by bradcray** [comment]
Hi @thomasvandoren: I'm not enough of a mason expert to have a good insight here but am trying to rustle up some attention for you on this issue.  My intuition is that since you and @nspark are in agreement, you're probably right.

**Comment by ben-albrecht** [comment]
> Is that a reasonable fix for this issue? If so, I'm happy to submit a PR from the above branch.

Yes, I think so, and opening a PR would be appreciated. As you point out, this is a known issue that has not yet received attention.
