### ISSUE TITLE
Need Access to Transposes *and* Slicing of Sparse Arrays

### ISSUE THREAD

**Issue by Tshimanga** [chapel-lang/chapel#8819]
As in [On the Subtleties of Sparseness in Chapel](https://stackoverflow.com/questions/49283425/on-the-subtleties-of-sparseness-in-chapel), among my desiderata are access to both slicing and transposition  of sparse arrays simultaneously. Hoping this is an issue of ignorance rather than something that will need to be introduced.

**Comment by ben-albrecht** [comment]
>  access to both slicing and transposition of sparse arrays simultaneously

This could be solved by supporting proper slicing on `CS` arrays, which have a supported transpose function in the `LinearAlgebra` module. Would that be an acceptable solution to you? 

If so, this may be considered a duplicate of #8023

**Comment by ben-albrecht** [comment]
With sparse transpose supported and #8023 covering sparse slicing, I'm going to close this issue as duplicate.
