### ISSUE TITLE
Should Owned allow compiler-added copies to transfer ownership?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#8843]
With the current record-based Owned implementation, the compiler will create an error at compile time rather than transfering ownership due to an auto-copy. Consider for example:

``` chapel
class MyClass { var x:int; }
proc f( ref arg:Owned(MyClass) ) {
  return arg;
  // compiler adds copy initialization to this return
  // since it's returning a reference by value
  // is it surprising that arg stores nil after the return?
}

proc main() {
  var x = new Owned(new MyClass(1));
  f(x);
  writeln(x); // is it surprising that x now stores nil?
}
```

Should such compiler-added ownership transfers be enabled?

**Comment by mppf** [comment]
I think so, once we have checking for empty Owned things, but I'm not totally certain.

**Comment by vasslitvinov** [comment]
From the user's view, the function returns an owned thing. That ownership has to come from somewhere right? In this case it happens to come from the formal. So the ownership being taken from 'x' is what f() is doing. Sure it may be surprising for the caller of f(), yet this is what f() is written to do.

So I think the program should compile and writeln a nil.

**Comment by mppf** [comment]
I'm inclined to agree that such compiler-added copies should be allowed, especially since the current alternative makes a common patterns into errors (e.g. #9259)

**Comment by bradcray** [comment]
I think I tend to agree with @mppf and @vasslitvinov here.

**Comment by psahabu** [comment]
I agree with the decision that was made here.
