### ISSUE TITLE
"Pragma unsafe" error on previously compiling code, cannot compile

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#8846]
Attempting to compile a simple file, I get a new error.  Just start this morning after I pulled last night (Around 8pm PT, 16 March).  I cannot compile anything.

```chapel
var states: [1..0] string;
states.push_back("bob");
writeln(states);
states.push_back(["fred", "joe"]);
writeln(states);

> $CHPL_HOME/modules/internal/ChapelBase.chpl:1054: error: unknown pragma: "unsafe"
```

We all know my computer freaks out once in a while, as does its user, so I'll keep looking.  But this means I can't compile anything.

```
printchplenv 
machine info: Darwin macbuddha.local 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64
CHPL_HOME: /Users/buddha/github/chapel *
script location: /Users/buddha/github/chapel/util
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: clang
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: intrinsics
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none
```

```
chpl --version
chpl version 1.17.0 pre-release (ef8d835169)
Copyright (c) 2004-2018, Cray Inc.  (See LICENSE file for more details)
```

**Comment by buddha314** [comment]
Well, I did a bunch of things to re-create this.  Clobbered everything, earlier versions.  It seemed to be dependent on the shell, as in if I took a new shell it would no longer fail.  I'd love a little insight on how this happened if anyone has advice.

**Comment by ben-albrecht** [comment]
> Well, I did a bunch of things to re-create this. Clobbered everything, earlier versions. It seemed to be dependent on the shell, as in if I took a new shell it would no longer fail. I'd love a little insight on how this happened if anyone has advice.

Would it be correct to interpret this  as "This issue has been resolved, but your not sure why"? 

I don't have any ideas as to how you might have stumbled upon it. I haven't seen this error before.

**Comment by cassella** [comment]
``pragma unsafe`` was added to the compiler and modules in commit 09db08470 on Thursday 3/15.  The initial report shows a compiler that was built against master as of the previous Friday, 3/9:

> chpl version 1.17.0 pre-release (ef8d835169)

**Comment by buddha314** [comment]
Thanks, Paul.  At one point, I was compiling the same program in different terminals, getting the error in one and not the other.  Then I tried reverting to a Wednesday build, got the same thing twice, then it went away after some change.  I think I met a ghost.  Did you guys develop Chapel on top of an ancient Indian burial ground or something?  Don't you know better?  You moved the headstones but you DIDN'T MOVE THE BODIES!!!!

![image](https://user-images.githubusercontent.com/630441/37567143-dff19cf8-2a7f-11e8-8469-3dcc1bfa4e5c.png)

I wouldn't be so quick to declare "this house is clean", but go ahead, close the ticket AT YOUR OWN PERIL, BEN!

**Comment by buddha314** [comment]
For what it's worth, this just happened to @tshimanga and when he opened a new terminal, it went away. Seems to happen around the time we pull new versions of chapel.

**Comment by ben-albrecht** [comment]
Given that we don't have a way to reproduce the error encountered here, and we haven't heard of any other instances since, we're going to close this issue. We can reopen if it is ever encountered again in the future.
