### ISSUE TITLE
mason run ambiguous behavior

### ISSUE THREAD

**Issue by thomasvandoren** [chapel-lang/chapel#8852]
`mason run` usage, documentation, and implementation differ. The usage and online documentation suggest that `mason build` will be executed if needed when `mason run` is called (to paraphrase). There is also a `--build` flag for `mason run`, which executes `mason build`. `mason run` implementation will also call `mason build` when target/ directory exists but Mason.lock does not exist. This behavior is not well documented and it is not necessarily intuitive for the end user.

Also, `mason run` implementation passes all the unmatched flags and arguments down to the chapel module executable, which doesn't seem to be documented. It seems useful to provide a way for end users to call `mason run` and have flags/arguments passed down to the main module. I think there are some subtle issues with current implementation though (e.g. how to pass conflicting flag like `--build` to executable).

Issue 1: expected `mason run` behavior is not well defined
Issue 2: docs, usage, and implementation do not match expected behavior

### References

* Online docs: https://chapel-lang.org/docs/tools/mason/mason.html#building-and-running-your-project
* Usage: https://github.com/chapel-lang/chapel/blob/2cb8621cb34f302aa92f961a32feca7716214c3e/tools/mason/MasonHelp.chpl#L65-L80
* Implementation: https://github.com/chapel-lang/chapel/blob/2cb8621cb34f302aa92f961a32feca7716214c3e/tools/mason/mason.chpl#L99-L142

Other related issues:

* #7106 and specifically this comment: https://github.com/chapel-lang/chapel/issues/7106#issuecomment-342145046
* #8831

**Comment by ben-albrecht** [comment]
Thanks for writing this up @thomasvandoren

Breaking each point into answers / tasks that I think need to be done in order to resolve this issue:

> The usage and online documentation suggest that mason build will be executed if needed when mason run is called (to paraphrase). 

- [ ] This is incorrect and needs the text needs to be updated.

> here is also a --build flag for mason run, which executes mason build

- This is correct

> mason run implementation will also call mason build when target/ directory exists but Mason.lock does not exist. 

- [ ] I am not sure why we do that, and think it should be updated to keep behavior consistent

> Also, mason run implementation passes all the unmatched flags and arguments down to the chapel module executable, which doesn't seem to be documented. 

- This is documented now.

>  I think there are some subtle issues with current implementation though (e.g. how to pass conflicting flag like --build to executable).

- This is handled by adding an extra `--` before flags to be ignored by mason.
  - e.g. `mason run -- --build`. 
  - This is documented in a `.. note::`.

@spartee - let me know what you think on these.
