### ISSUE TITLE
Chapel smoke / correctness tests run on chapNN slaves fail in easy_install w https/SSL errors (Cray int)

### ISSUE THREAD

**Issue by awallace-cray** [chapel-lang/chapel#8866]
Chapel smoke and correctness tests which run on chapNN (older Cray-I.T.-built SLES-11 build slaves) and which use Python virtual env's created by Chapel (`make test-venv`, `make chpldoc-venv`) started failing repeatedly on 03/15 around 5:30 PM CT. 

The easy_install commands (from `make *-venv`) got fatal connection errors trying to download from https://pip.pypi.org: 

```
error: Download error for https://files.pythonhosted.org/packages/38/a5/781ba11e55ccdede3d43e8493087c5c768e5a1724f30f255d8c066529720/virtualenv-12.0.5.tar.gz: [Errno 1] _ssl.c:497: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
```

These failures stopped by themselves after 8:20 PM that evening, and many tests ran successfully until the next morning 03/16 at 10:00am CT, when they started failing again with the same error.

**Comment by awallace-cray** [comment]
All these errors were fixed by changing the Jenkins job configs for all Chapel smoke and correctness-test jobs fitting the above description, to use a hand-built version of Python 2.7 instead of the system-installed Python 2.6 that they previously used. That Python 2.7 version is conveniently activated by source'ing `/data/cf/chapel/setup_python27-byhost.2017-08-09.bash`, and the Jenkins job config change was to add that shell command in the appropriate places.

**Comment by ben-albrecht** [comment]
Should re-open this, since the custom Python installation is a temporary solution?

**Comment by awallace-cray** [comment]
Open a new ticket w the permanent solution you want?

**Comment by awallace-cray** [comment]
2018-03-20 : Added info

I can replicate this simply by using wget:

SLES11:
```
$ wget https://files.pythonhosted.org/
--2018-03-20 11:13:47-- https://files.pythonhosted.org/
Resolving files.pythonhosted.org... 151.101.45.63, 2a04:4e42:2c::319
Connecting to files.pythonhosted.org|151.101.45.63|:443... connected.
OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Unable to establish SSL connection.

$ rpm -qa | grep libopenssl
libopenssl0_9_8-0.9.8j-0.80.1
```
SLES12:
```
$ wget https://files.pythonhosted.org/
--2018-03-20 11:13:57-- https://files.pythonhosted.org/
Resolving files.pythonhosted.org (files.pythonhosted.org)... 151.101.185.63, 2a04:4e42:d::319
Connecting to files.pythonhosted.org (files.pythonhosted.org)|151.101.185.63|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-03-20 11:13:57 ERROR 404: Not Found.

$ rpm -qa | grep libopenssl
libopenssl1_0_0-1.0.2j-60.20.2.x86_64
```
So either you need to use your Python version or these machines need to be upgraded to SLES12. As there is no other path forward for supporting this.

**Comment by ben-albrecht** [comment]
There is no way to get an `libopenssl` updated?
