### ISSUE TITLE
Migrate chplenv/template into developer documentation

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#8904]
Within `util/chplenv/`, we have a `template` file that provides a basic template for creating a new `chplenv` script.

While some might find this useful, it seems a bit unusual to leave a template file laying around within the `util/` directory, especially given how infrequently new `chplenv` scripts are introduced.

Also, #6124 reminded me that this gets bundled into the release, which is also weird, and ends up requiring explicit instructions to ignore in the Debian package metadata.

I think it would be reasonable to move this template file into developer documentation, where it can continue to be a useful reference, but does not live among production files.

**Comment by ronawho** [comment]
Removed in https://github.com/chapel-lang/chapel/pull/11720
