### ISSUE TITLE
collect scalability data

### ISSUE THREAD

**Issue by psahabu** [chapel-lang/chapel#8933]
## user story
As a Chapel programmer, I want to know how well my programs will scale because I want my performance to be fast and predictable.

### acceptance criteria
Scalability data has been collected and graphed for the following tests:
- RA-on
- RA-rmo
- RA-atomics
- reduction
- stream
- PRK Stencil
- ISx

On the following multilocale configurations:
- up to 256 nodes on an internal Cray system
- up to 1024 nodes on NERSC's Edison

**Comment by ronawho** [comment]
1024-locale (Edison) graphs at https://github.com/chapel-lang/chapel/issues/8935
256-locale graphs at https://github.com/chapel-lang/chapel/issues/9213
