### ISSUE TITLE
internal scalability data

### ISSUE THREAD

**Issue by psahabu** [chapel-lang/chapel#8934]
### Configuration:
- up to 256 nodes on an internal Cray system
 
### Collect and graph scalability data for the following tests:
- [ ] PRK Stencil
- [ ] ISx
- [ ] RA-on
- [ ] RA-rmo
- [ ] RA-atomics
- [ ] reduction
- [ ] stream

**Comment by ronawho** [comment]
See https://github.com/chapel-lang/chapel/issues/9213 for graphs/results
