### ISSUE TITLE
owned & borrowed syntax proposal: new returns borrow

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#8938]
Previous: #8797. Next: none.

This is a variation on #8654.

General idea: `MyClass` and `borrowed MyClass` both refer to a borrow, `owned MyClass` refers to an owning pointer. `new` calls can be marked as `owned` or `unmanaged`, but one that is not marked returns the result of `(new owned C(...)).borrow()`.  Additionally, when instantiating generics, Owned/Shared non-type arguments are replaced by Borrows unless the generic explicitly opts in to accepting Owned/Shared. The default intent for Owned/Shared is to perform ownership transfer / sharing (ie `const in`).

A generic argument or field can opt in to accepting owned/shared with the following generic types:
 * `managed` means must be owned/shared
 * `managed?` means it could be owned/shared/borrow/int
 * `owned` means it must be owned
 * `shared` means it must be shared
 * `borrowed` means it must be a class borrow

The general idea driving the special rule for the instantiation of owned/shared in this proposal is that it would be surprising for generic code (especially code that is not written with owned classes in mind) to have ownership transfers by default. However once a generic argument has a type or partially specified type, be it a class type (borrow) or owned or ..., it becomes clear that ownership transfer should or should not occur. So, this special rule need only apply to totally generic arguments (those with no type as in `proc f(x)` or those with a queried type like `proc g(x:?t)`.

Edits to this issue:
 * updated to treat instantiations of generic functions with Owned arguments as borrow type by default, per discussion in #8618.
 * updated to imagine default intent of Owned/Shared is ownership transfer rather than borrow.
 * described type constructor error
 * unsafe -> unmanaged per discussion in #8374
 * special rule for instantiation does not apply to type arguments or compiler-generated default initailzers
 * `borrowed` keyword is added

### Locales Primer Example
``` chapel
class Node {
  var data: real;
  var next: owned Node;
}
var head    = new Node(0); // this is a (new Owned(new Node(0)).borrow()
var current = head;

for i in 1..numLocales-1 do on Locales[i] {
  current.next = new owned Node(i); // forgot 'owned'? error, borrow doesn't coerce to owned
  current      = current.next.borrow();
}
```

### Generic Collection Example
``` chapel
record Collection {
  var element;
  // compiler-generated initializer uses `managed?` on the element argument.
  // compiler-generated type constructor is not subject to the owned->borrow substitution
  // rule since it only consists of type arguments.
  // This element field can store owned or borrowed class instances.
}

// Note that the default intent for a managed pointer
// is to transfer ownership, which is what is desired here.
proc Collection.addElement(x:element.type) {
  element = x;
}
proc test() {
  var c: Collection(owned MyClass);
  c.addElement(new owned MyClass(1)); // forgot 'owned' ? then error from lifetime checker
  var d: Collection(int);
  d.addElement(2);
}
```

### Generic Function Example
``` chapel
// data is MyClass per special instantiation rules
// default intent for that is 'const in' rather than 'const ref'
proc process(data) {
  var sum = 0;
  for i in 1..n {
    sum += data.value; // single-deref here for Owned actual
  }
}
proc test() {
  var data = new owned MyClass(1);
  process(data);
  // but for such an example, the version without owned
  // would work too, and instantiate 'process' with the borrow type.
}
```

### Borrow into Argument Record
``` chapel
record Argument {
  var data:borrowed; // may not store owned, since it says borrowed
}
proc process(arg:Argument) {
  ... use arg.data ...
}
proc test() {
  var data = new owned MyClass(1);
  var arg = new Argument(data); // record stores borrow
  process(arg);
  // the above snippet could also be written as
  // var data = new MyClass(1); // this is a borrow
  // var arg = new Argument(data);
  // process(arg);
}
```
 
### Function returning newly allocated object
``` chapel
proc returnNewMyClass() : owned MyClass {
  return new owned MyClass(1);
  // forgot owned? error from type system or borrow checker
}
proc wrapReturnNewMyClass() {
  return returnNewMyClass(); // return type inferred as owned MyClass
}
```

### Function returning a borrow
``` chapel
proc returnBorrowGlobal() : MyClass {
  return globalMyClass.borrow();
}
proc wrapReturnBorrowGlobal() {
  return returnBorrowGlobal(); // return type inferred as MyClass
}
```

### Does specifying type change new?
``` chapel
var myC = new owned MyClass(1);
// myC has type owned MyClass
var myC:owned MyClass = new owned MyClass(1);
// myC has type owned MyClass

var myC = new MyClass(1);
// myC has type MyClass (borrow)
var myC:MyClass = new MyClass(1);
// myC has type MyClass (borrow)
```

**Comment by mppf** [comment]
I've updated this issue:

 * updated to treat instantiations of generic functions with Owned arguments as borrows by default, per discussion in #8618.
 * updated to imagine default intent of Owned/Shared is ownership transfer rather than borrow.

**Comment by mppf** [comment]
I have some concern that record / class fields would have to be annotated to allow managed types and that would be easy to miss. I *think* that the borrow checker would catch many confusions here, but what if no type annotations are used in either place? E.g.
``` chapel
record Collection {
  var element; // oops! forgot :managed?
}
proc Collection.addElement(x /*forgot :managed? */) {
  element = x;
}
proc test() {
  var c: Collection(owned MyClass);
   // I think the above would have to be an error, since you can't make a
   // Collection(owned MyClass) since it can only store a borrow.
  c.addElement(new owned MyClass(1)); // this would coerce to borrow
  var d: Collection(int);
  d.addElement(2);
}
```

Additionally it seems odd to me that code such as the above could accept a record containing a shared field, e.g.
``` chapel
record R { var x:shared MyClass; }
var c: Collection(R);
c.addElement(new R(...));
```

(But this would not work in the case of owned because the default `const ref` intent for R would not allow the ownership transfer within `addElement`)

**Comment by lydia-duncan** [comment]
Reading through #8618, how would you write the following when the argument is `managed?`?
``` chapel
proc addTwo(arg: managed?) {
  globalArray.push_back( new arg.type() );
}
addTwo(new Owned(new MyClass()));
```

**Comment by mppf** [comment]
> Reading through #8618, how would you write the following when the argument is `managed?`?

I think what you have above would work just fine. The `:managed?` would cause generic instantiation to use `owned MyClass` as the type of arg in the instantiation, resulting in `arg.type` being `owned MyClass`.

**Comment by mppf** [comment]
Discussing this proposal with @vasslitvinov brought up some questions / possible adjustments. I'll try to put each in a separate comment.

### Q. Do fields need the special treatment? Can the compiler just never adjust type arguments to make them go from owned to borrow?

``` chapel
// Consider an alternative: type arguments aren't messed with
record Argument {
  var data;
}

var data = new owned MyClass(1);
var arg:Argument(owned MyClass) = new Argument(data);
  // X why shouldn't this work?
  // LHS uses Argument(owned) but RHS uses Argument(borrow)
  // because initializer accepts generic argument, not type argument.

var arg = new Argument(data);
  // this is a record storing a borrow, is that surprising?

var arg = new (Argument(owned MyClass))(data);
  // you'd have to write this

// Pro: easier to instantiate types with managed
// Con: inconsistent between value argument and type argument

// compare with the system described in the proposal
record Argument {
  var data:managed?;
}

var data = new owned MyClass(1);
var arg:Argument(owned MyClass) = new Argument(data);
  // this works

var arg = new Argument(data);
  // this works

var arg = new (Argument(owned MyClass))(data);
  // this works

```

**Comment by mppf** [comment]
### Q. Does x:managed or x:managed? have any effect when instantiated with an int?

In other words, should this compile?

``` chapel
proc f(x:managed?) { }
proc g(x:managed) { }
f(1);
g(2);
```

The expectation is that this should be allowed in order to avoid needing to create 2 versions of each generic function (one for classes).

**Comment by mppf** [comment]
### Q. Would it be smoother with an intent-like syntax?

Note that the things like `managed?` are not intents, since when instantiated they will have whatever intent the do (or they might combine with other intents). However we could consider use a more intent-like syntax. e.g. for the Generic Collection Example
``` chapel
record Collection {
  var owned element;
}
proc Collection.addElement(managed x) {
  element = x;
}
proc test() {
  var c: Collection(owned MyClass);
  c.addElement(new owned MyClass(1));
}
```

**Comment by psahabu** [comment]
I like this proposal, with two reservations:

1.  Having both `managed` and `managed?` seems unnecessary. I would collapse it down to just `managed` meaning owned/shared/borrow.
2. The plain `new MyClass()` does not seem useful as it returns a borrow to a class that cannot be returned. In that sense it's even more limited than a record. We could make it return an `unsafe` instead, though that's another can of worms.

My responses to Vass' questions are below.
> Q. Do fields need the special treatment? Can the compiler just never adjust type arguments to make them go from owned to borrow?

Library writers should have full control over the ownership that their collections and functions will manage. The special treatment helps the library author maintain a consistent internal representation, which is important for any API.

> Q. Does x:managed or x:managed? have any effect when instantiated with an int?

To me, `managed` and the other keywords imply a restriction on class generics but not records or primitives. As such, the provided examples should compile.

> Q. Would it be smoother with an intent-like syntax?

I was partial to the previous intent-like proposal, so I would like to see this as well.

**Comment by lydia-duncan** [comment]
> Q. Does x:managed or x:managed? have any effect when instantiated with an int?
> 
> In other words, should this compile?

I thought the intention was that `managed` would require interaction with `owned`/`borrow`/`raw` while `managed?` would allow either?

**Comment by psahabu** [comment]
> I thought the intention was that managed would require interaction with owned/borrow/raw while managed? would allow either?

This would make sense to me, though I don't think `raw` falls under `managed`. Here's how I would do it:

`managed`: `owned`, `shared`
`managed?`: `managed`, `raw`, `record`, primitive types
`<blank>`: `raw`, `record`, primitive types

**Comment by mppf** [comment]
@bradcray brought up a good point that in the Generic Collection example, what the collection author would really like to be able to say is that the argument to `addElement` has the same type (including managed-ness) as the `element` field.

``` chapel
record Collection {
  var element:managed?;
}
proc Collection.addElement(x:"as managed as element") {
  element = x;
}
```

This makes me revisit @vasslitvinov's proposal above & wonder if there is a way to adjust the proposal to say, only exempt type constructors from the conversion from owned->borrow during instantiation.

Additionally @bradcray pointed out that the `managed?` syntax could be moved into a where clause. I'm not sure how I feel about that, because I don't see the `managed?` keyword as affecting which function applies as much as how it is instantiated. (But, in the constrained generics proposal, `A implements B` in a where clause *does* impact how the function is instantiated, since functions from the `implements` will be made available in preference to say global functions. Even there I've generally preferred that we could put these `implements` argument annotations outside of the where clause, partly since it has a role beyond filtering). In any case, it is interesting to think of `managed?` as some kind of interface/type trait.

**Comment by mppf** [comment]
Regarding
> Q. Do fields need the special treatment? Can the compiler just never adjust type arguments to make them go from owned to borrow?
``` chapel
record Argument {
  var data;
}
var data = new owned MyClass(1);
var arg:Argument(owned MyClass) = new Argument(data);
  // this works
```

I take that back - I don't think it's an advantage if that works. It would "work" by converting the type of both the LHS and RHS to store a borrow. This looks like the case in https://github.com/chapel-lang/chapel/issues/8938#issuecomment-376918805 -- I think I'd prefer a compilation error than silently (and confusingly) changing the declared type.

This makes me think that there's probably a special rule here for type arguments and/or type constructors that we need to figure out. It might be:
 * all type arguments are exempt from owned->borrow by default
 * the type constructor is exempt from owned->borrow by default

I'm not so sure I'm happy with "all type arguments are exempt" as a rule.
I'd view the following as two ways of writing a generic function that have a different calling pattern:
``` chapel
proc f_type( type t, arg: t ) { ... }
proc f( arg ) { ... }
```
If type arguments are somehow exempt from the rule, the `f_type` version would behave differently when passed an owned type & owned than the `f` version would - in particular `arg.type` would be owned in `f_type` but not in `f`.

Should initializers be exempt from the rule? Well, if they were, this example
``` chapel
record Argument {
  var data;
}
var x = new Argument( new owned MyClass(1));
```
would create an x with x.data being an owned, which is counter to one of the design goals here (generic code/collection authors should opt-in to ownership transfers).

Of course, if the type constructor alone is exempt from the rule, there is an inconsistency in behavior between these two statements:
``` chapel
var a:Argument(owned MyClass) = new Argument(data);
var b = new Argument(data);
```

I think that the solution is to rather make `Argument(owned MyClass)` an error on its own. The justification for that would be that the author of `Argument` hasn't opted in to accepting owned/shared types and the resulting default ownership transfer/sharing. This error would take the form of additional checking for type constructors for generic record/classes - wherever the type constructor argument is owned/shared but the field is totally generic, raise an error. I think this is a more specific description of what I meant in https://github.com/chapel-lang/chapel/issues/8938#issuecomment-376918805 .

Regarding the example I just noted in the previous comment, since the rule in the existing proposal only applies to arguments that are totally generic (i.e `proc f(x)` or `proc f(x:?t)`), it would not apply to arguments with a type expression, such as `proc f(x:something.type)`.

In particular, I think that the way to write what @bradcray was suggesting, where the managed-ness of the `element` field determines it for the `addElement` argument, is this:
``` chapel
record Collection {
  var element:managed?;
}
proc Collection.addElement(x:element.type) {
  element = x;
}
```

Or, equally well:
``` chapel
record Collection {
  type elementType:managed?;
  var element:elementType;
}
proc Collection.addElement(x:elementType) {
  element = x;
}
```

Lastly, I thought to bring up another example, which I think works but it's worth explaining why:
``` chapel
proc sametype(a:?t, b:t) { }
```
In particular, the author of such a generic function would certainly expect that `a` and `b` have the same type. That will happen with "change owned to borrow for unspecified types" rule, because the type of `a` would be a borrow (were an owned passed in) and thus the queried type `?t` would also get set to the borrow type, and then `b` would be set to match.

**Comment by lydia-duncan** [comment]
Would it help to provide a way to query if an instance is owned or borrowed?  Then the methods could base their behavior off of if the field gives the specific result from that query.  If that information is not deemed useful outside of the type information, then it makes sense to have it be a property of the type.  (Apologies if this functionality is already provided)

**Comment by mppf** [comment]
I'm currently thinking that we should amend the proposal to:
 1. not transform generic owned->borrow for `type` arguments
 2. not transform generic owned->borrow for generic arguments to initializers
 3. add 'borrowed' keyword

doing 1 and 2 together keeps initializers consistent. It follows a different strategy from the generic `proc f(x)` rule, but I think there's less reason to change the type of a field in a generic record on instantiation, since it's typical to transfer ownership into a collection. Then, the default for a generic record/class is to leave it up to the caller.

Note that if we did only 1, we could end up in a situation where declaring a generic field with a separate type argument like this:
``` chapel
record R {
  type t;
  var field:t;
}
```

would behave differently from the version without the explicit type:
``` chapel
record R {
  var field;
}
```

I think it's interesting that we could actually use that strategy to eliminate `managed?` altogether - you'd use the `type t` version if you wanted the equivalent of `managed?` and the `var field` version if you didn't. But I think it's even more reasonable, for fields, to have a `borrowed` keyword and do effectively default to `managed?` on the field.

Then `managed?` could be avoided for methods using the pass-a-separate-type trick... but arguably we will still need a keyword/generic type for it.

**Comment by vasslitvinov** [comment]
"+1" for 1. and 3.

I can go either way for 2. I suggest to restrict 2. to apply only to compiler-generated initializers.

**Comment by lydia-duncan** [comment]
I agree with @vasslitvinov's suggestion to only apply the rule to compiler-generated initializers.  Doing the same thing for explicit initializers is making an assumption about the use for the argument in question - we don't know it will be used as an initial value for a field and adjusting based on that seems confusing.  As an example:
```chapel
proc init(x) {
  field = callOnX(x); // callOnX probably expects a borrow
}
```
or
```chapel
proc init(a, b, c) {
  field1 = a; // Maybe this should be owned
  if (someComputationOnB(b)) { // But maybe we expect a borrow here
     field2 = c; // Who even knows?
  }
}
```

**Comment by mppf** [comment]
For the `borrowed` keyword, should it be `borrowed` or `borrow` or `borrows` ?

`borrowed` has the advantage to being a parallel construct to `owned` and `shared`.
But these terms don't say *who* owns/shares. That ends up being confusing with sentences like "the compiler checks that borrows do not outlive the borrowed variable", because a "borrowed variable" might now refer to one of borrow type, which is a borrow... (But I meant it to mean "the result of a borrow").

Would it be better to use another variant? Would `own` / `share` / `borrow` be better as a set?

**Comment by lydia-duncan** [comment]
I would use `borrowed`, personally.  I think the `borrow` or `borrows` form are more likely to make awkward sentences, while the case you describe just means we'd have to be careful to indicate what specifically we are referring to.

**Comment by vasslitvinov** [comment]
See also Michael's illustrations [here](https://github.com/chapel-lang/chapel/issues/8374#issuecomment-382389322) in #8374 .

I prefer the -ed forms. `owned MyClass` says "the value of this type is **owned** by \<whatever variable it is in>".

Even more importantly, neither "own" nor "owns" works well /  makes sense when looking at the type alone. The type itself is the primary context to consider, whereas variables of the type are secondary.

**Comment by bradcray** [comment]
> I'm currently thinking that we should amend the proposal to:
>  1. not transform generic owned->borrow for `type` arguments
>  2. not transform generic owned->borrow for generic arguments to initializers
>  3. add 'borrowed' keyword

I'm definitely behind 1 and 3.  2 I'm still unsure about.

> Note that if we did only 1, we could end up in a situation where declaring a generic field with a 
> separate type argument ... would behave differently from the version without the explicit type:

I'm not necessarily convinced that this is an inherently bad thing, though I think it depends a lot on the answer to the question "What is the compiler's default type initializer if none is specified?" which I think remains less well-defined than we'd like—particularly for cases like this with a completely generic field (or at least, the current plan is not particularly clear to me and in discussions it's felt like we're not 100% sure we've got it right).

> I think it's interesting that we could actually use that strategy to eliminate managed? altogether

This is incredibly tantalizing to me.

**Comment by psahabu** [comment]
Late to the conversation, but I have always felt that `managed?` is klugey. If`borrowed` makes some things clearer while getting rid of `managed?`, I'm for it.

**Comment by mppf** [comment]
Closing this because it's mostly implemented. We didn't end up implementing `managed?` but everything else here is implemented. #10215 covers the less solid portion of the design.

**Comment by mppf** [comment]
Just for future reference, I'm recording the cases where it's been potentially surprising that `new C` won't work (where `new owned C` would) that might suggest `new owned` is a better default:
 * `var x = [i in 1..3] new C(i);` #11022
 * `record R { var field = new C(); }` #11021
 * `proc f() { return new C(); }` (mentioned in above discussion)

In both of these cases there `new borrowed C` creates a temporary `owned` in a block that isn't exactly user visible (loop body, or init function).

**Comment by mppf** [comment]
See also https://github.com/chapel-lang/chapel/issues/11021#issuecomment-436076406 which proposes `new C()` possibly meaning something else entirely.
