### ISSUE TITLE
SPIKE: Prioritize HDF5 Functionality

### ISSUE THREAD

**Issue by benjamin-robbins** [chapel-lang/chapel#8961]
Spike: What is the order of HDF5 Dev? What order will we work on HDF5 support?

**Comment by daviditen** [comment]
HDF5 has a low-level [Core library](https://portal.hdfgroup.org/display/HDF5/Core+Library) and a [High-level Library](https://portal.hdfgroup.org/display/HDF5/High-level+Library).  Both are written in C.

I think we should start with a direct `extern` interface to the high-level library.  The high-level library is broken up into 7 APIs, the most important appear to be "Lite", "Images", "Tables", "Packet Tables", "Dimension Scales", in that order.

Once the direct `extern` interface is in place, we can use Chapel features to make the API more user friendly.  For example, we can wrap HDF5 types with Chapel records to group methods for each type, and automate things like closing files in the destructor.  There are already [C++](https://portal.hdfgroup.org/pages/viewpage.action?pageId=50073884) and [Java](https://portal.hdfgroup.org/display/HDF5/HDF5+Java+Reference+Manual) interfaces to HDF5 that we should be able to draw inspiration from.

At that point we can build an `extern` interface to the low-level Core library for users that need the low-level functionality.
