### ISSUE TITLE
Port Chapel to libfabric / OFI

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#8963]
As a Chapel Programmer, I'd like to have Chapel's runtime target libfabric / OFI directly so that I can run on networks that support it without paying the overhead of going through additional portability software layers.

Acceptance criteria:
Given a libfabric-capable network, I can set `CHPL_COMM=ofi` (or `libfabric`?) in order to compile and run programs for it, and all reasonable tests in the testing suite pass.

**Comment by jhh67** [comment]
Closing this as we met the acceptance criteria long ago.
