### ISSUE TITLE
Investigate fft/hpl perf loss from full dynamic registration

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#8967]
There were some non-trivial performance regressions for FFT and HPL under comm=ugni as a result of full dynamic memory registration (https://github.com/chapel-lang/chapel/pull/7700)

Somehow we missed these during our normal performance triage, though they are visible: https://chapel-lang.org/perf/16-node-xc/?startdate=2018/01/01&enddate=2018/01/30&configs=gnuugniqthreads&graphs=hpccfftperfgflopsn220,hpcchplreleaseperfgflopsn255nb32

While we haven't optimized these benchmarks or spent a lot of time looking at them recently, it would be good to understand the cause of the performance loss, and if possible address it.

Note that we discovered these after the fact in the release-over-release timings, where the regressions are more pronounced: 

![fft-20](https://user-images.githubusercontent.com/1588337/37936380-2edddb2a-310a-11e8-8c0f-9721b87e2378.png)

![hpl-255-32](https://user-images.githubusercontent.com/1588337/37936384-32828c94-310a-11e8-9a1a-cd9334a2d0fb.png)

**Comment by gbtitus** [comment]
More info from FFT.  I added timers to fft.chpl to compute the time spent in various phases of the timed part of the program, specifically each major white-space-separated piece of `main()` and then after an initial run, each of the two major blocks of `dfft()`.  I did BW28 runs using this built with an up-to-date master and a repo from just before PR #7700.  The master version reported an execution time of 1.36 secs vs. 0.933 secs with pre-#7700.  All of the 0.43 second difference was in the 2nd `ddft()` call, 0.39 sec in the first major block and 0.46 sec in the second major block.  Put another way, the 1st major block of `dfft()` ran about 1.5x as long after #7700 and the 2nd one ran about 1.8x as long.

**Comment by gbtitus** [comment]
More FFT info: I added some temporary atomic counters to `chpl-mem.h` to count array allocs and bytes allocated, whether from the comm layer or the regular memory interface.  Then I modified FFT to zero those counters right before the 2nd `dfft()` call (the one that runs longer as of #7700) and print them right afterward.  There were only 7 arrays with a total of 1792 bytes allocated, all from the regular memory layer, during that 2nd `dfft()` call.  (We already knew there were no hugepage-based large arrays allocated during that call, because [above](https://github.com/chapel-lang/chapel/issues/8967#issuecomment-376340318) I reported that internal comm=ugni statistics showed no such allocations during the entire timed region of FFT.)  I had been wondering if perhaps we were allocating a whole lot of temporary arrays for the slices in the butterfly calls and the extra logic needed to decide where to get the memory was adding overhead, but that seems not to be the case.

**Comment by ronawho** [comment]
Running fft with `CHPL_RT_MAX_HEAP_SIZE=16G` (avoiding dynamic heap extension) didn't seem to impact performance, which led me to think the performance loss was from one of the semi-unrelated commits in the PR. I think I have tracked it down to https://github.com/chapel-lang/chapel/commit/ace5e852 ("Don't bother trying to use stack-based remote fork completion flags")

At https://github.com/chapel-lang/chapel/commit/ace5e852 I still see poor performance, but if i go back to the commit before (https://github.com/chapel-lang/chapel/commit/16c32760) I see much improved performance. Here's some results (I ran with the default n=20, as well as n=24 to try to stabilize timings):

| size | 16c32760d4    | ace5e852fa    |
| ---- | ------------- | ------------- |
| n=20 | ~.11 Gflops/s | ~.08 Gflops/s |
| n=24 | ~.15 Gflops/s | ~.09 Gflops/s |

**Comment by ronawho** [comment]
@gbtitus I'm not having much luck trying to re-add stack-based rf_done flags. Using a stack allocated one I'm just getting an execution hang, and I don't understand that code well enough yet to debug intelligently. Is that something you could look at?

And FYI the blocking progress thread [further hurt fft](https://chapel-lang.org/perf/16-node-xc/?startdate=2017/12/21&enddate=2018/04/20&configs=gnuugniqthreads&graphs=hpccfftperfgflopsn220,hpccffttimesecn220), so even if stack-based rf_done flags help,  we might not quite see the peak old numbers (though you could run with `CHPL_RT_COMM_UGNI_BLOCKING_CQ=f` to see if that gets back to old numbers)

**Comment by gbtitus** [comment]
I will take a look at this this week.

**Comment by ronawho** [comment]
Subsequent changes in https://github.com/chapel-lang/chapel/commit/86b33f8443c5f82c64c5ee6e6fd186503757ebb2 and https://github.com/chapel-lang/chapel/commit/4d45a101c2907f7e33e8e69cf8e04593c49f63c0 made it harder to "revert" ace5e85. 

Think I finally got a hacky version working on master though: 

```diff
diff --git a/runtime/src/comm/ugni/comm-ugni.c b/runtime/src/comm/ugni/comm-ugni.c
index 08479807b3..a54de64755 100644
--- a/runtime/src/comm/ugni/comm-ugni.c
+++ b/runtime/src/comm/ugni/comm-ugni.c
@@ -4265,8 +4265,10 @@ void send_polling_response(void* src_addr, c_nodeid_t locale, void* tgt_addr,
   // This gets nearly all the benefit of not waiting for completions,
   // while avoiding concurrency control entirely.
   //
-  if (cd == NULL || !cd->firmly_bound) {
-    do_remote_put(src_addr, locale, tgt_addr, size, &gnr_mreg_map[locale],
+  // TODO I'm not what to do for the the polling task response, so just force
+  // it to go through the blocking put case, so I can test fft perf.
+  if (true || cd == NULL || !cd->firmly_bound) {
+    do_remote_put(src_addr, locale, tgt_addr, size, NULL, // &gnr_mreg_map[locale],
                   may_proxy_false);
     return;
   }
@@ -7108,16 +7110,25 @@ void do_fork_post(c_nodeid_t locale,
                   uint64_t f_size, fork_base_info_t* const p_rf_req,
                   int* cdi_p, int* rbi_p)
 {
+  rf_done_t             rf_done;
   gni_post_descriptor_t post_desc;
   int                   rbi;
   gni_return_t          gni_rc;

   if (blocking) {
+    mem_region_t* rf_done_mr;
+
     //
     // Our completion flag has to be in registered memory so the
     // remote locale can PUT directly back here to it.
     //
-    p_rf_req->rf_done = rf_done_alloc();
+
+    p_rf_req->rf_done = &rf_done;
+    rf_done_mr = mreg_for_local_addr(p_rf_req->rf_done);
+    if (rf_done_mr == NULL) {
+      p_rf_req->rf_done = rf_done_alloc();
+    }
+
     *p_rf_req->rf_done = 0;
     atomic_thread_fence(memory_order_release);
   }
@@ -7172,7 +7183,8 @@ void do_fork_post(c_nodeid_t locale,
       local_yield();
     }

-    rf_done_free(p_rf_req->rf_done);
+    if (p_rf_req->rf_done != &rf_done)
+      rf_done_free(p_rf_req->rf_done);
   }
 }
```

That patch effectively turns off 4d45a101c2907f7e33e8e69cf8e04593c49f63c0, so there will be other regressions (i.e. it's not a full fix):

no-block = `CHPL_RT_COMM_UGNI_BLOCKING_CQ=f`

| size | 16c32760d4    | ace5e852fa    | master        | master + patch | master + no-block | master + no-block + patch |
| ---- | ------------- | ------------- | ------------- | ---------------| ----------------- | ------------------------- |
| n=24 | ~.15 Gflops/s | ~.09 Gflops/s | ~.07 Gflops/s | ~.08 Gflops/s  |  ~.09 Gflops/s    | ~.15 Gflops/s             |

So that patch by itself doesn't do a whole lot, but the patch + `CHPL_RT_COMM_UGNI_BLOCKING_CQ=f` restores the old performance. I think we're going to stick with a blocking CQ by default, so it might not be worth trying to resolve this regression.

**Comment by gbtitus** [comment]
In conversation we've decided the problem is likely due to contention on the pools of remote-fork-done flags and their lightweight allocator.  If we're doing a lot of executeOns we can get either lock contention or cache interference due to the shared pool index, or both.  I'm going to make another spike, to confirm this and prototype a fix.

**Comment by ronawho** [comment]
We're now reasonably confident that locale 0 is in parallel creating a bunch of on-stmts to remote locales, but only when `cyclicPhase=true`, which is only done in the second call to `dfft()`. We believe this explains the root cause, and why Greg only saw the second call to `dfft()` slow dow in https://github.com/chapel-lang/chapel/issues/8967#issuecomment-376579430 

Here's part of the offending code in fft (only run on locale 0, during the second call to `dfft()`):

https://github.com/chapel-lang/chapel/blob/79d83fdf6b317c26180f6bc19a0c988a25bcab71/test/release/examples/benchmarks/hpcc/fft.chpl#L187-L189

**Comment by gbtitus** [comment]
Update based on #9323: reducing/removing inter-thread contention in the rf-done data structure improves FFT (XC-16, `n=24`) by 10-20%.  I think we may be able to do a little better, however.
