### ISSUE TITLE
Compilation failures due to argument order in default initializers

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#8974]
The following tests all fail due to an issue involving initializer argument order on an inherited class. Run with ``--force-initializers``:

[test/types/type_variables/deitz/part5/inherit_instantiate2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/types/type_variables/deitz/part5/inherit_instantiate2.chpl)
[test/classes/diten/override_with_subclass_ret_type_generic.chpl](https://github.com/chapel-lang/chapel/blob/master/test/classes/diten/override_with_subclass_ret_type_generic.chpl)
[test/classes/diten/override_with_subclass_ret_type.chpl](https://github.com/chapel-lang/chapel/blob/master/test/classes/diten/override_with_subclass_ret_type.chpl)
[test/classes/ferguson/generic-inherit3.chpl](https://github.com/chapel-lang/chapel/blob/master/test/classes/ferguson/generic-inherit3.chpl)
[test/classes/ferguson/generic-inherit2a.chpl](https://github.com/chapel-lang/chapel/blob/master/test/classes/ferguson/generic-inherit2a.chpl)
[test/classes/ferguson/generic-inherit2.chpl](https://github.com/chapel-lang/chapel/blob/master/test/classes/ferguson/generic-inherit2.chpl)
[test/classes/ferguson/generic-inherit.chpl](https://github.com/chapel-lang/chapel/blob/master/test/classes/ferguson/generic-inherit.chpl)
[test/classes/ferguson/generic-inherit4.chpl](https://github.com/chapel-lang/chapel/blob/master/test/classes/ferguson/generic-inherit4.chpl)
[test/release/examples/primers/classes.chpl](https://github.com/chapel-lang/chapel/blob/master/test/release/examples/primers/classes.chpl)
[test/studies/590o/blerner/xml-parse.chpl](https://github.com/chapel-lang/chapel/blob/master/test/studies/590o/blerner/xml-parse.chpl)
[test/classes/deitz/dispatch/test_dd5.chpl](https://github.com/chapel-lang/chapel/blob/master/test/classes/deitz/dispatch/test_dd5.chpl)
[test/expressions/ferguson/dynamic-class-name.chpl](https://github.com/chapel-lang/chapel/blob/master/test/expressions/ferguson/dynamic-class-name.chpl)
[test/io/ferguson/readThis/readclass.chpl](https://github.com/chapel-lang/chapel/blob/master/test/io/ferguson/readThis/readclass.chpl)
[test/library/standard/List/deitz/test_seq_class4.chpl](https://github.com/chapel-lang/chapel/blob/master/test/library/standard/List/deitz/test_seq_class4.chpl)
[test/users/ferguson/aa/class-ref-two.chpl](https://github.com/chapel-lang/chapel/blob/master/test/users/ferguson/aa/class-ref-two.chpl)
[test/users/ferguson/aa/aa4.chpl](https://github.com/chapel-lang/chapel/blob/master/test/users/ferguson/aa/aa4.chpl)

**Comment by lydia-duncan** [comment]
I meant to update compiler generated initializers to reset the ordering of parent and child arguments back to the way it was with constructors, but I haven't taken the time yet.  It shouldn't be difficult to do, though

**Comment by cassella** [comment]
None of these tests are presently futures, and they all pass

```
fortytwo@magrathea:~/src/chapel (master)$ cat > init-order
#paste in list above
fortytwo@magrathea:~/src/chapel (master)$ start_test `cat init-order`

[Test Summary - 190319.144852]
[Summary: #Successes = 16 | #Failures = 0 | #Futures = 0 | #Warnings = 0 ]
[Summary: #Passing Suppressions = 0 | #Passing Futures = 0 ]
[END]
```

**Comment by bradcray** [comment]
Seems like we should close.  @benharsh ?
