### ISSUE TITLE
Tab completion for chpl inserts a space after a directory in some cases

### ISSUE THREAD

**Issue by daviditen** [chapel-lang/chapel#8975]
After setting up tab-completion for chpl in bash:

```
% source $CHPL_HOME/util/chpl-completion.bash
```

Trying to complete:
```
% chpl ~/chapel/test/release<TAB>
```

gives a space at the end instead of a slash (and also escapes the `~` character):
```
% chpl \~/chapel/test/release <CURSOR IS HERE>
```

It should give:
```
% chpl ~/chapel/test/release/<CURSOR_IS_HERE>
```

**Comment by cassella** [comment]
BTW, if you want to add tests for the completion, there are ways to do that:

https://brbsix.github.io/2015/11/29/accessing-tab-completion-programmatically-in-bash

**Comment by daviditen** [comment]
Thanks for the tip @cassella.

**Comment by daviditen** [comment]
The root of this problem is that the completion script gets the string "~/chapel/test/release" as a quoted string, so tilde expansion doesn't happen, and `test -d $DIRNAME` returns `false`.  That implies that it isn't a directory, so a space is added instead of a slash.  To fix it, the script will need to manually do tilde expansion.

The backslash escape on the tilde is coming from bash's `printf %q` format specifier.  It can be replaced with `%s` to use the string directly.
