### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#8976]
Python 3 as default `python` is becoming more common. Notably, Homebrew recently made python 3 the default when doing `brew install python`. Also, [Ubuntu 18.0.4](https://wiki.ubuntu.com/Python/Python36Transition)  (releases April 26th, 2018) will switch to python 3 as default.

Consequently, it would be worthwhile to support python 3 for most if not all components of Chapel, including developer features.

[PEP 394](https://www.python.org/dev/peps/pep-0394/) describes how projects can prepare for this transition. Namely, we should use `python2` or `python3` in the shebang to specify which python is supported, if the program does not support both `python2` and `python3`.

Note that Chapel will need to continue supporting Python 2.6.9 until Chapel drops support for CLE 5 / SLES 11 [(EOL March, 2019)](https://www.suse.com/lifecycle/).

Here is a rough overview of current python support, by component:

|                         | 2.6.9              | 2.7.14             | 3.6.0              |
|-------------------------|--------------------|--------------------|--------------------|
| `printchplenv`          | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| `make chpldoc`          | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| `make docs`             | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| `make test-venv`        | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| Testing system          | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| `c2chapel`              | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| Other `util/` scripts   | ?                  | :white_check_mark: | ?                  |
| `chpl --library-python` | :x:                | :x:                | :white_check_mark: |

**Comment by ben-albrecht** [comment]
Related: #8704, #8766

**Comment by ben-albrecht** [comment]
I didn't see https://github.com/chapel-lang/chapel/issues/8897 before writing this issue, but I suppose this issue describes one potential solution https://github.com/chapel-lang/chapel/issues/8897.

**Comment by marcoscleison** [comment]
Hi, I could dot compile docs due to my python 3 environment. I think that it will be great to migrate to Python 3.

**Comment by ronawho** [comment]
https://github.com/chapel-lang/chapel/pull/11728 should resolve this. I was able to run a full paratest under it, and verified that c2chapel also works. In the above table I left "Other util/ scripts" as a question mark, because I'm not positive everything has been caught, but certainly most thing have been.
