### ISSUE TITLE
postinit not applied for type declaration when record is generic

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#9001]
### Summary of Problem
When a record instance is declared with just a type (no explicit initial value), `postinit` is not called.

### Steps to Reproduce

**Source Code:**

```chapel
record MyRec {
  type t;
  var x : t;

  proc init() {
    this.t = int;
    this.x = 10;

    writeln('MyRec.init default');
  }

  proc init(type t) {
    this.t = t;

    writeln('MyRec.init type');
  }

  proc postinit() { // This should get run, but accidentally is skipped today
    writeln('MyRec.postinit');
    writeln();
  }
}

proc main() {
  var r1 : MyRec(int);

  writeln(r1);
}
```

generates this output:
```
MyRec.init type
(x = 0)
```

**Compile command:**
`chpl foo.chpl`

**Execution command:**
`./foo`

**Associated Future Test(s):**
[`test/classes/initializers/postInit/record-generic-fails.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/postInit/record-generic-fails.chpl) #9002

### Configuration Information

- Output of `chpl --version`: Chapel 1.18.0 pre-release

**Comment by bradcray** [comment]
Fascinating...

**Comment by lydia-duncan** [comment]
When this is resolved, test/types/typedefs/nelson/typedefFixingParameter.chpl can be converted to use `postinit` instead of `initialize`
