### ISSUE TITLE
Convert strings to use initializers

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#9006]
As a Chapel implementer, I want strings to use initializers because strings are frequently used and would help to demonstrate initializer stability.

Acceptance criteria: Replacement of 'proc string' constructors with initializers.

**Comment by benharsh** [comment]
Recommended testing configurations:
- full local + futures
- full gasnet
- valgrind
- memleaks

**Comment by benharsh** [comment]
Some initial observations:

The ``chpl__initCopy()`` for strings behaved like ``init(x, owned=x.owned)``, but the copy initializer is actually ``init(x, owned=false)``. This leads to additional memory usage in some cases.

A double-free can occur with the following pattern:
```chpl
const ret = foo:string; // foo is a string
```

The compiler fails to insert a copy-init, so 'ret' is an alias of 'foo'. This seems to be cast-specific and a general issue for records.

Some tests under memory/figueroa/ aren't actually testing string leaks, but are testing string memory usage.

**Comment by benharsh** [comment]
The initCopy issue is discussed further in #9171.

**Comment by bradcray** [comment]
I don't feel particularly tied to that example staying as-is per se, but #9173 seems troubling enough to end-users to warrant fixing it rather than working around it for cases like this to me.

**Comment by benharsh** [comment]
Yeah, that's my thinking too. I'm running a test of classes/initializers with the proposed fix in the linked PR.
