### ISSUE TITLE
Resolve double-free when initializing from casted record

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#9007]
### Summary of Problem
If a variable is initialized from an expression that casts a record of type ``T`` to ``T``, the compiler fails to insert a call to the copy initializer.

### Steps to Reproduce

**Source Code:**

```chapel
record R {
  var x : int;

  proc init() {
    writeln("R.init()");
  }
  proc init(r:R) {
    this.x = r.x;
    writeln("R.init(R)");
  }
  proc deinit() {
    writeln("R.deinit");
  }
}

proc bad(n:int) {
  var err_args : R;
  for i in 1..n do err_args.x += 1;

  const ret = err_args:R;
  return ret;
}

proc main() {
  var b = bad(10);
  writeln("b = ", b);
}
```
Output:
```
R.init()
R.deinit
b = (x = 10)
R.deinit
```
In this example we expect to see a call to "R.init(R)"

### Configuration Information

- Output of `chpl --version`: 1.17.0

**Comment by benharsh** [comment]
Thinking about this some more, I'm not sure what the semantics really are if a variable is cast to the same type as itself.

```chpl
const foo = original:R;
```

In this case it seems reasonable to me that ``foo`` is some kind of copy of ``original``. Whether it's from the ``_cast`` function or ``R.init(R)`` I'm not exactly sure.

What about this case?

```chpl
(original:R).something(); // equivalent to ``original.something()`` ??
```

Is ``something`` invoked on a copy of ``original``?

**Comment by bradcray** [comment]
> I'm not sure what the semantics really are if a variable is cast to the same type as itself.

My general intuition is that casts create new values, so by default, I'd tend to expect that to happen when casting something to its own type as well.  I could imagine the compiler optimizing the copy away if it found it was legal / unobservable for it to do so.
