### ISSUE TITLE
basic arithmetic on Series

### ISSUE THREAD

**Issue by psahabu** [chapel-lang/chapel#9038]
## user story
As a Chapel Programmer, I want to do basic arithmetic operations on my Series because it helps me analyze my data in powerful ways.

### acceptance criteria
- Series with the same underlying datatype and index types can be combined arithmetically to produce a new Series.
- Series can be combined arithmetically with scalars of the same type to produce a new Series.

## design and implementation tasks
- [x] what index set should the new Series use?
  - union of the two index sets
- [x] implement arithmetic between two Series:
  - [x] addition / string concatenation
  - [x] subtraction
  - [x] multiplication
- [x] enforce invariants between the two Series:
  - [x] same underlying type
- [x] implement arithmetic between a Series and a scalar
  - [x] addition and subtraction
  - [x] multiplication

**Comment by bradcray** [comment]
Is "same underlying type" the constraint we want here, or is it really "compatible underlying types"?  (e.g., I can add an int and a real... should I be able to add a Series of ints and reals?)
