### ISSUE TITLE
Dataframes ADT with Series

### ISSUE THREAD

**Issue by psahabu** [chapel-lang/chapel#9042]
## user story
As a Chapel Programmer, I want to use the Dataframe ADT because it best represents the tabular nature of my data while providing powerful tools for analysis.

### acceptance criteria
- Dataframes can be initialized with or without Series.
- Series can be added or removed from a Dataframe.

## design and implementation tasks
- [x] all Series within a Dataframe are contained within an associative array
  - string -> Series
- [x] all Series within a Dataframe share the same index set
- iteration and access
  - [ ] iteration interface (deferred: see #9660)
  - [x] access interface
  - https://www.tutorialspoint.com/python_pandas/python_pandas_iteration.htm
- [ ] arbitrary Series can be set as the index
  - deferred: see #9658
  - https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.set_index.html

## resources
Pandas DataFrame: https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html

**Comment by buddha314** [comment]
We have started on a data-frames like object we called [NamedMatrix](https://github.com/buddha314/numsuch/blob/master/src/MatrixOps.chpl#L11-L16) and an operation that [conforms the dimensions before multiplying](https://github.com/buddha314/numsuch/blob/master/src/MatrixOps.chpl#L334-L364).  I opened an issue on DataFrames a [few months ago](https://github.com/chapel-lang/chapel/issues/7187) 

If the team thinks this should be hosted in an external package (like pandas is to Python) I would be personally thrilled to get some contributions to NumSuch or even hand over ownership.  This way we could contribute use cases like in our [test cases](https://github.com/buddha314/numsuch/blob/master/test/NumSuchTest.chpl#L119-L185) and continue momentum.

**Comment by psahabu** [comment]
@buddha314: Thanks for letting us know about NamedMatrix. Looking over it, it seems very similar to what we want to do with Dataframes. The main design difference I see is that NamedMatrix requires all the data to be of the same type, whereas a Chapel Dataframe will only require that data in the same Series be of the same type.

Bringing in @benharsh: Do you see this as a good start for what we want to do, or would a separate Chapel Dataframe library be better?

**Comment by psahabu** [comment]
Conferring with @benharsh, we're thinking that a separately developed Chapel Dataframe library modeled directly after pandas will be better for this user story. If Dataframes end up being more suited to NumSuch than NamedMatrix, we'd be happy to support your use cases.

NamedMatrix has a place as a separate package though, for users who don't need the full power of Dataframes.

**Comment by buddha314** [comment]
Honestly we dont want it as a separate package.  We just want the functionality of being able to address rows and columns by name, so point us in the direction of your dataframes usrt stories and we will contribute there. The pandas functionality is limited and mutiple people havr tried to extend it, so lets get ti right the first time


Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by psahabu** [comment]
Gotcha, thanks for the insight on your use case and experience. #8638 is the Epic for DataFrames, which all the user stories link to.

**Comment by Tshimanga** [comment]
One distinction to keep in mind between general dataframes and our current NamedMatrix class is that the named matrices are decorated *sparse* array by default. That is a key bit of functionality that we need in our use cases.
