### ISSUE TITLE
fixpath.py doesn't handle PATH that contains space on fish shell correctly

### ISSUE THREAD

**Issue by caizixian** [chapel-lang/chapel#9049]
https://github.com/chapel-lang/chapel/blob/master/util/config/fixpath.py#L43

If one entry of `PATH` contains space, `fixpath.py` will treat it as multiple entries, because of space being used as the delimiter. Therefore, after `source ./util/setchplenv.fish`, `PATH` might become invalid.

**Comment by ben-albrecht** [comment]
@caizixian - thanks for reporting. 

It looks like https://github.com/chapel-lang/chapel/blob/master/util/config/fixpath.py#L25 needs to be updated to use `delim` instead of `:` to handle escaped spaces for `fish`.

**Comment by caizixian** [comment]
PR #9078 opened
