### ISSUE TITLE
--savec without compile option?

### ISSUE THREAD

**Issue by ian-bertolacci** [chapel-lang/chapel#9070]
Does there already exist a way to use the `--savec` option while also not compiling the generated code?
I'd like to be able to see the C code the chapel compiler generates without compiling that code, as it may be extremely costly (see issue #9047).

My current work around is using `--ccflags --do-not-run-gcc-thanks`, which causes gcc to fail since `--do-not-run-gcc-thanks` is not a valid option in gcc.

**Comment by mppf** [comment]
This seems related to #9025

**Comment by bradcray** [comment]
I'm not aware of a current way to do this, but Michael's cross-link to Louis's recent related issue is definitely appropriate.  I was going to suggest setting CHPL_MAKE to 'glorp' (assuming you don't have a make-like program named glorp :) ) before seeing that you were essentially doing the equivalent.

**Comment by ian-bertolacci** [comment]
Agreed. Closing in favor of #9025
