### ISSUE TITLE
Can't push_back to array of Owned objects

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#9082]
### Summary of Problem
```
$CHPL_HOME/modules/internal/ChapelArray.chpl:2737: In function 'push_back':
$CHPL_HOME/modules/internal/ChapelArray.chpl:2747: error: illegal lvalue in assignment
```

### Steps to Reproduce

**Source Code:**
```chapel
use OwnedObject;

class Foo {
  var x: int;
}

var foolist: [0..-1] Owned(Foo);

var data = new Owned(new Foo());
foolist.push_back(data);
```

**Compile command:**
`chpl --force-initializers`

### Configuration Information
`chpl version 1.17.0 pre-release (7025ff7fe2)`

**Comment by ben-albrecht** [comment]
Seems related to #6841

**Comment by BryantLam** [comment]
@ben-albrecht -- Thanks! I should have checked on the latest master. This problem was fixed.
