### ISSUE TITLE
Replace easy_install usage with pip

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#9095]
Historically, we have used `easy_install` as our project dependency over `pip`, since it came with python installation. Some time has passed since that decision was made... Now `pip` is included with python installations (since Python 2.7.9), and `easy_install` is deprecated, so we should make the switch in our build system.

This change is primarily motivated by `easy_install` not using the latest TLS. PyPI has deprecated TLS versions below 1.2, and will deny all deprecated requests starting on April 8th (currently during brownouts - first 15 minutes of the hour).

We currently use `easy_install` to install `virtualenv` for `make test-venv` and `make chpldoc`. After April 8th, these make targets may no longer work on certain systems (e.g. OS X), until we replace `easy_install` with `pip`.

**Comment by ben-albrecht** [comment]
FYI @awallace-cray

**Comment by awallace-cray** [comment]
Yes, the PyPA tribe strongly advocates dropping easy_install/distutils for pip/setuptools. 
It's probably good advice.

**Comment by ben-albrecht** [comment]
I have a [branch](https://github.com/chapel-lang/chapel/compare/master...ben-albrecht:issue-9095) with a fix that is working locally so far, but it will need significant cross-platform and cross-python-version testing before merging.
