### ISSUE TITLE
Heap allocation of stack variables is buggy

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#9106]
Background: when needHeapVars()==true, a variable that would normally live on stack needs to be heap-allocated - if it can be referenced on a remote locale. The compiler makes this transformation in makeHeapAllocations() during the 'parallel' pass.

**The bug is**: some variables that need to be heap-allocated are not.

It is unclear how this affects real programs. As of 2018-04-04, the claim that the bug exists is based on Vass's examining the generated C code for a simple test and by examining and tracing through the compiler code in makeHeapAllocations(). needHeapVars()==true happens only in a couple of configurations, which we do not test much. A full paratest of one such multilocale configuration did not show any memory access-related issues.

### Configurations

* One configuration where needHeapVars()==true is:

```
CHPL_COMM=gasnet
CHPL_GASNET_SEGMENT=fast
CHPL_TARGET_ARCH=none
CHPL_TASKS=fifo
```

The full printchplenv dump from the aforementioned paratest is:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: none
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: fast
CHPL_TASKS: fifo
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: intrinsics
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: none
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none
```

It would be great to set also CHPL_MEM=cstdlib so we can use valgrind. However, while in this configuration everything compiles, running the program gives this "error: Your CHPL_MEM setting doesn't support the registered heap required by your CHPL_COMM setting. You'll need to change one of these configurations."

* Another configuration for needHeapVars()==true is our valgrind testing configuration:

```
CHPL_COMM=none
CHPL_HOST_PLATFORM=linux64
CHPL_MEM=cstdlib
CHPL_TARGET_ARCH=none
CHPL_TASKS=fifo
compile with --no-local
```

This does not expose incorrect remote memory accesses, however.

#### What is going wrong?

* As makeHeapAllocations() traverses the AST from uses to defs, it drops some symbols from further consideration by not adding them to refVec or varVec. There are TODOs in the code. There might be additional omissions without a todo annotation.

* Consider a function whose by-ref formal may be referenced on a remote locale. The corresponding actual for each invocation of such a function needs to be added to refVec or varVec. makeHeapAllocations() does not implement the case where such invocation happens due to dynamic dispatch. That is, when the call being examined refers to another method that is virtual and can be dynamically dispatched to the  function in question. This is the case with dsiReallocate() in  test/arrays/deitz/jacobi-no-local.chpl

#### Tests

* A simple test:

```chpl
// an extract from test/arrays/deitz/jacobi-no-local.chpl

param rank = 1;
const LOC = Locales[numLocales-1];

// As of this writing, the default intent for 'bounds' is 'const ref'.
// This is incorrect - it should be 'const in'. If we fix that,
// we need to specify 'const ref' explicitly.
proc dsiReallocate(bounds:rank*range)
{
  on LOC {
    writeln((...bounds));  // some use of 'bounds'
  }
}

proc main {
  dsiReallocate((555..666,));
}
```

In the generated C code for this, the literal (555..666,) is stored in a local variable of chpl_user_main(). A reference to it is passed into the on-function that executes the writeln() in dsiReallocate(). That local variable should go on the heap instead.

* For an extended version of the above, compile:

```
chpl --no-local test/arrays/deitz/jacobi-no-local.chpl
```

* The results from the aforementioned paratest are:

(a) An assertion failure when compiling:

```
exercises/c-ray/c-ray.badscenes.chpl
exercises/c-ray/c-ray.chpl
exercises/c-ray/forStudents/c-ray.chpl
```

(a bis) BTW these are due to Vass's running paratest with --verify. With --no-verify, these compilations produce invalid C code.

(b) Execution failure, probably unrelated:

```
# test: runtime/configMatters/comm/oversubscribedArrayAlloc
oversubscribedArrayAlloc.chpl:31: error: Out of memory allocating "array elements"

```

**Comment by bradcray** [comment]
@gbtitus , @ronawho : Any thoughts on this issue?

**Comment by ronawho** [comment]
I'm not sure I quite follow what this issue is actually talking about. In particular I'm not following if  Vass actually encountered a bug, or if he just saw a logic error in `needsHeapVars()`. 

ugni and gasnet both support out-of-segment gets/puts/amos now, so there shouldn't be any correctness concerns WRT to not heap allocating variables anymore. Additionally, fifo and qthreads stacks are allocated from the registered heap, so there's no performance benefits to promoting things anymore. I would expect we can just remove `needsHeapVars()` now (https://github.com/chapel-lang/chapel/pull/6203 has a little more discussion on this)
