### ISSUE TITLE
Make internal errors distinguishable in user output again

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#9107]
### Summary of Problem
I may or may not have been partially responsible for this, but I've found it increasingly difficult lately to determine the compiler source file from a user's version of the internal error message.

Today, the output is something like `MIS0594`, where the first three characters are from the start of the file name, and the last four are the line number with the error.  We get these characters either from a user report or from the output of a `start_test` run.

When files starts with a similar prefix, like resolveIntents and resolveFunction or (**cough**) initializerRules and initializerResolution, the developer is forced to recompile the code outside of `start_test` to get the full file name.  Sometimes even that doesn't help, like for AST node files where we have a copy in `compiler/AST` and `compiler/codegen`.

While the time saved is miniscule depending on when in compilation the error occurs, it would save a step for determining what is going wrong with the user's program.

### Configuration Information

- Output of `chpl --version`: chapel 1.18.0 pre-release

**Comment by daviditen** [comment]
https://github.com/daviditen/chapel/blob/internal-error-to-text/util/internalToText.sh

**Comment by lydia-duncan** [comment]
Resolved by #11104
