### ISSUE TITLE
Normal BTR support for Chapel modules on Cray XC w ARM-based Processors

### ISSUE THREAD

**Issue by awallace-cray** [chapel-lang/chapel#9124]
https://github.com/chapel-lang/chapel/issues/8729 and https://github.com/chapel-lang/chapel/issues/9065 explored what Chapel modules on Cray XC w ARM-based processors would look like. 

This task is to implement normal BTR support for such modules, so that the new aarch64 Chapel RPMs can be routinely built and tested by automated Jenkins processes, and passed to downstream consumers inside Cray in the usual way. 

Changes are needed in the RPM specfile and build scripts used to build and test the Chapel RPM.  See https://github.com/chapel-lang/chapel/issues/8729#issuecomment-378941528. The first task should be to develop those changes on the private branch(es) already being used for this work. 

Then, those private-branch changes need to be implemented on master branch, without breaking the automated BTR processes supporting x86_64 Chapel RPMs. 
Note: https://github.com/chapel-lang/chapel/issues/8729 and https://github.com/chapel-lang/chapel/issues/9065 focused on Chapel release 1.17.0. This task will focus on master branch. 

Refs: 
https://github.com/awallace-cray/priv/issues/3
https://github.com/awallace-cray/chapel/tree/gh8729b

**Comment by awallace-cray** [comment]
https://github.com/chapel-lang/chapel/issues/8721 is required

**Comment by awallace-cray** [comment]
@bradcray Could we please put this in the Backlog?  I thought this was my next big important thing after Releases 1.17.x.  It is one of my 2 OKRs.

**Comment by bradcray** [comment]
Yep, thanks!

**Comment by awallace-cray** [comment]
The Chapel modules for aarch64 still have a few issues (some nightly correctness test errors), but the BTR support is complete.
