### ISSUE TITLE
collect additional scalability data

### ISSUE THREAD

**Issue by psahabu** [chapel-lang/chapel#9133]
### Machines:
- up to 256 nodes on an internal machine
- up to 1024 nodes on NERSC's Edison
 
### Collect and graph scalability data for the following configurations:
- [ ] ISx
  - [ ] 1.15
  - [ ] 1.16
  - [ ] reference
- [ ] RA
  - [ ] reference  
- [ ] stream
  - [ ] reference
- [ ] PRK stencil
  - [ ] reference

**Comment by bradcray** [comment]
With the risk of naming names, @ronawho pointed out to me on Friday that @benharsh has typically gathered reference numbers for the perf reports / slides.
