### ISSUE TITLE
chpldoc is missing from "brew install chapel" as of Chapel release 1.17.0. Mac OS.

### ISSUE THREAD

**Issue by awallace-cray** [chapel-lang/chapel#9153]
This issue just notes the fact that chpldoc was deliberately omitted from the Homebrew formula, this release.  Given the choice between losing chpldoc v. forcing every `brew install chapel` to also install `python@2` (Homebrew's latest Python-2.7-plus-utilities package), we decided to not require every Chapel user to take python@2. 

Those interested in chpldoc on Mac OS may build chpldoc themselves. 
* First, `brew install python@2`. 
* Then, build Chapel 1.17.0 from source: see [download](https://chapel-lang.org/download.html) and [Quickstart](https://chapel-lang.org/docs/usingchapel/QUICKSTART.html) instructions. 
* Right after the final `make` command, run:  `make chpldoc`.

**Comment by stonea** [comment]
This issue appears to be out of date; closing for now; please revive if I'm incorrect.
