### ISSUE TITLE
comm=ugni minimal-registered mode sometimes doesn't register enough memory

### ISSUE THREAD

**Issue by gbtitus** [chapel-lang/chapel#9154]
While investigating another issue I unloaded the `craype-hugepages` module I had been using, so I was then in minimal-registered mode.  I then encountered this comm=ugni internal error trying to run ra-rmo:

    internal error: out of NIC-registered space

The way this mode works is by computing the total amount of registered space that will be needed, allocating and registering that, and then handing out pieces of it as the comm layer requests them.  Each request is supposed to have a matching reservation done earlier, so that by the time we need the space it's all ready and there's enough.  The message above is printed when an allocation call finds that there isn't sufficient space.

This isn't a mode that we test regularly, but nevertheless it should work.  Probably this is just a bit-rot problem.

**Comment by ronawho** [comment]
FYI a TODO in https://github.com/chapel-lang/chapel/issues/5675 is to add nightly minimal registration testing.

**Comment by ronawho** [comment]
I couldn't reproduce this originally, but I was only running with 2 locales. On machine C I see the same failure if I run with 15 or more nodes, and on machine J I needed 74 or more nodes.

**Comment by gbtitus** [comment]
We didn't assign a weight in sprint planning.  I'm thinking this is a 1-day problem and have changed it unilaterally.

**Comment by ronawho** [comment]
Confirmed that #9172 resolves this for me on machine J. 74 nodes and 128 nodes for hello w/o hugepages runs without issue.

I'd like run stream on C tomorrow up to 256 nodes, but that shouldn't hold up that PR.

**Comment by ronawho** [comment]
hello.chpl with 256 nodes on C looks good! I checked stream-ep perf and that looks as expected at 256 nodes as well:

| hugepages | GB/S   | GB/s per-node |
| --------- | ------ | ------------- |
| yes       | 24,500 | 95.5          |
| no        | 25,000 | 98.0          |

(Slightly higher perf for stream w/o hugepages is expected: https://github.com/chapel-lang/chapel/issues/7852)
