### ISSUE TITLE
Should string's init-copy create a deep copy by default?

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#9171]
In the old initCopy world, string's [initCopy](https://github.com/chapel-lang/chapel/blob/d67e929695e8bc66d11740517733717111da7867/modules/internal/String.chpl#L1381) would only create a deep copy if the original string was owned. In the initializer world, that would look something like:
```chpl
proc init(s:string, owned : bool = s.owned);
```

Yet there was a string constructor that by default always created a copy:
```chpl
proc string(s:string, owned : bool = true);
```
This string constructor should become the copy-initializer, but that would change memory usage (and perhaps program behavior).

Should string's copy-initializers create a deep copy by default?

**Comment by bradcray** [comment]
I'd think "by default, yes."  As in other cases, I'd hope that we'd eventually have a way to steal the string from a dead RHS.  I'm not convinced the `owned` argument is the right way to do this, however.

**Comment by mppf** [comment]
I would think no, because the common case for an "unowned" string is in fact a string literal. These have no relevant "ownership" and are just available for the whole program run. Shouldn't copying a string literal result in something that shares the (const) string literal?

``` chapel
var x = "hi";
var y = x; // Why can't this also point to the constant literal "hi" ?
```

**Comment by mppf** [comment]
I think the problem in this case is the string constructor's awkward use of default arguments.

**Comment by benharsh** [comment]
Whatever the case, I believe this has been settled for 2.0. At a glance, it looks like we always copy now. My guess is we handle string literals through some of the move-steal analysis.
