### ISSUE TITLE
Generic record fields and omitted initialization in initializers

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#9181]
### Summary of Problem
We've solved the issue with a field being initialized via a `new` expression in the past, but it looks like we missed when the field's type is a generic instantiation.

The case below gets an internal compiler error

(Thanks to Ben A for finding the problem!)

### Steps to Reproduce

**Source Code:**

```chapel
var foo = new Foo();
writeln(foo);

record Foo {
  var a = new A(real);

  proc init() {
  }
}

record A {
  type aType;
}
```

**Compile command:**
`chpl foo.chpl`

**Associated Future Test(s):**
None yet

### Configuration Information

- Output of `chpl --version`: chapel 1.18.0 pre-release

**Comment by benharsh** [comment]
@lydia-duncan : I think this bug has since been resolved (by who knows what), can you confirm?

**Comment by lydia-duncan** [comment]
Looks like it, I'll close this.  Thanks!
