### ISSUE TITLE
Chapel Release 1.17.1 BTR support

### ISSUE THREAD

**Issue by awallace-cray** [chapel-lang/chapel#9193]
Create release materials for Chapel Release 1.17.1 using the existing release/1.17 branch. 

~Schedule:  TBD~ 
Release date: 2018-04-30

Scope: Cray modules, release-tar on GitHub, ~more TBD~, Homebrew, Docker

Content: Currently as follows, possibly more

master branch PR | release/1.17 branch PR
------------------ | ----------------------
https://github.com/chapel-lang/chapel/pull/9053: typos in CHANGES.md (bradc, bena) | https://github.com/chapel-lang/chapel/pull/9060 (merged 2018-04-02)
https://github.com/chapel-lang/chapel/pull/8981: hwloc update (davidk, elliot) | https://github.com/chapel-lang/chapel/pull/9195
https://github.com/chapel-lang/chapel/pull/9044: postinit	bug fix	for generic record (bharsh) | https://github.com/chapel-lang/chapel/pull/9196
https://github.com/chapel-lang/chapel/pull/9068: ugni polling thread contention fix (elliot, gbt) | https://github.com/chapel-lang/chapel/pull/9197
https://github.com/chapel-lang/chapel/pull/9076: docs/latest link	improvements (bradc) | https://github.com/chapel-lang/chapel/pull/9198
https://github.com/chapel-lang/chapel/pull/9115: CCE -hipa (IPA) fix (davidk, elliot) | https://github.com/chapel-lang/chapel/pull/9199
https://github.com/chapel-lang/chapel/pull/9162: fix ugni	debug build problems (gbt, elliot) | https://github.com/chapel-lang/chapel/pull/9200
https://github.com/chapel-lang/chapel/pull/9168: skip unregisterable mem segments	in ugni (gbt, elliot) | https://github.com/chapel-lang/chapel/pull/9201
https://github.com/chapel-lang/chapel/pull/9172: pre-compute max comm domains for	ugni (gbt, elliot) | https://github.com/chapel-lang/chapel/pull/9202
(copied here from updates below) | 
https://github.com/chapel-lang/chapel/pull/9112 Make LinearAlgebra.Sparse.eye() concrete | https://github.com/chapel-lang/chapel/pull/9214
https://github.com/chapel-lang/chapel/pull/9188 Process /proc/cpuinfo for CPU counts | https://github.com/chapel-lang/chapel/pull/9285
https://github.com/chapel-lang/chapel/pull/9264 correct fltk tarball | https://github.com/chapel-lang/chapel/pull/9286
https://github.com/chapel-lang/chapel/pull/9148 Adjust launchers to work with CHPL_THIRD_PARTY | https://github.com/chapel-lang/chapel/pull/9320
( 2018-04-25 ) | 
https://github.com/chapel-lang/chapel/pull/9102 Replace usage of easy_install with pip | https://github.com/chapel-lang/chapel/pull/9346
https://github.com/chapel-lang/chapel/pull/9293 Follow-up work to #9102 | same
https://github.com/chapel-lang/chapel/pull/9330 Use CHPL_PYTHONPATH for python -S calls | same
https://github.com/chapel-lang/chapel/pull/9347 Dockerfiles | https://github.com/chapel-lang/chapel/pull/9348
https://github.com/chapel-lang/chapel/pull/9340 Proposed CHANGES.md entries for 1.17.1 | https://github.com/chapel-lang/chapel/pull/9352 Final rev https://github.com/chapel-lang/chapel/commit/bae434820cd5811ed37c184faa9ba5bab6356b11
(2018-04-30) | Cherry-picked after release tag 
https://github.com/chapel-lang/chapel/pull/9360 Make some late-breaking CHANGES.md edits | https://github.com/chapel-lang/chapel/pull/9398

**Comment by awallace-cray** [comment]
2018-04-13 16:00 : release 1.17.1 build 0 from release/1.17 at 31dc29dd164

**Comment by awallace-cray** [comment]
2018-04-16 
Content update: per @ben-albrecht 

master branch PR | release/1.17 branch PR
------------------ | ----------------------
https://github.com/chapel-lang/chapel/pull/9112 | https://github.com/chapel-lang/chapel/pull/9214

**Comment by awallace-cray** [comment]
2018-04-16 12:14 : release 1.17.1 build 1 from release/1.17 at https://github.com/chapel-lang/chapel/commit/1235fa7ddbbc8bcd36fd6ac4882936860dd8d169

**Comment by awallace-cray** [comment]
@bradcray, please confirm when you want more PRs cherry-picked to release/1.17 branch. 
#9188, for example. Thanks!

**Comment by bradcray** [comment]
I think moving #9188 over makes sense once we know none of last night's failures were due to it.  (I haven't spent enough time with last night's testing results to know).

**Comment by ronawho** [comment]
FYI I think we'll also want to promote https://github.com/chapel-lang/chapel/pull/9264. Without that chplvis fails to build on linux systems

**Comment by awallace-cray** [comment]
2018-04-18 16:00
Great day for no build errors. If that holds, I'll pick #9188
I cannot see how #9264 could hurt, but will at least wait a day before picking it.

**Comment by bradcray** [comment]
Hi @awallace-cray -- I'd like to propose that PR #9148 be considered for addition to 1.17.1 based on recent users running into the issue and a sense that it shouldn't be any worse than what we have now.

**Comment by awallace-cray** [comment]
2018-04-19 17:00
Picking 

master branch PR | release/1.17 branch PR
------------------ | ----------------------
https://github.com/chapel-lang/chapel/pull/9188 Process /proc/cpuinfo for CPU counts | https://github.com/chapel-lang/chapel/pull/9285
https://github.com/chapel-lang/chapel/pull/9264 correct fltk tarball | https://github.com/chapel-lang/chapel/pull/9286

https://github.com/chapel-lang/chapel/pull/9148 Adjust launchers to work with CHPL_THIRD_PARTY : later, after some successful Jenkins nightlys? 

Admittedly, Jenkins will not test the new gasnet-launchers-can-be-moved quality yet. Think of the build time we could save, just being able to "make" on a local filesystem.

**Comment by awallace-cray** [comment]
2018-04-23 10:00
No progress since 2018-04-19 due to other priorities. Will Pick PR #9148 soon.

**Comment by awallace-cray** [comment]
2018-04-23 19:00

master branch PR | release/1.17 branch PR
------------------ | ----------------------
https://github.com/chapel-lang/chapel/pull/9148 | https://github.com/chapel-lang/chapel/pull/9320

Commit https://github.com/chapel-lang/chapel/commit/3d125c9c8952d312a25b36f3c611507ae0eb5609

**Comment by awallace-cray** [comment]
2018-04-25 

master branch PR | release/1.17 branch PR
------------------ | ----------------------
https://github.com/chapel-lang/chapel/pull/9102 Replace usage of easy_install with pip | not yet on release/1.17
https://github.com/chapel-lang/chapel/pull/9293 Follow-up work to #9102 Use CHPL_PYTHONPATH for python -S calls | not yet on release/1.17
https://github.com/chapel-lang/chapel/pull/9340 Proposed CHANGES.md entries for 1.17.1 | not yet on master

**Comment by awallace-cray** [comment]
2018-04-25 18:30
sha256
`f0a4671ca23832d69f831d230ca82264500ad1836d240854ba0835b95137f4f1  chapel-1.17.1.tar.gz`

**Comment by awallace-cray** [comment]
2018-04-26 17:10
Homebrew formula update request staged: https://github.com/Homebrew/homebrew-core/compare/master...awallace-cray:chapel-1.17.1

**Comment by awallace-cray** [comment]
2018-04-30 
Created release tag 1.17.1 at https://github.com/chapel-lang/chapel/commit/bae434820cd5811ed37c184faa9ba5bab6356b11
Then cherry-picked a minor fix to the CHANGES.md file which didn't make it into the actual release products. https://github.com/chapel-lang/chapel/pull/9398

**Comment by awallace-cray** [comment]
Cray release done.
GitHub release done.
chapel-lang.org updates needed, e.g. https://chapel-lang.org/download.html

**Comment by awallace-cray** [comment]
@bradcray - Chapel 1.17.1 is almost complete- the only outstanding item is for Homebrew to approve https://github.com/Homebrew/homebrew-core/pull/27281, and no problems are expected there.

**Comment by awallace-cray** [comment]
2018-05-01 Homebrew installer was updated 1/2 hour after the download-stats were collected.
Wait one more day and then verify download-stats include Homebrew Chapel 1.17.1.
