### ISSUE TITLE
Chapel program execution hangs on Titan

### ISSUE THREAD

**Issue by OrwellsGhost** [chapel-lang/chapel#9194]
### Summary of Problem

I installed and built the latest version of Chapel (1.17.0) on Titan Cray XK7 at ORNL and the execution stalls until timeout (5 minutes) when attempting to run a simple "hello world" Chapel program over 4 nodes.  The prebuilt Chapel module (1.10.0) works and I also installed Chapel 1.10.0 which works.  Howver all attempted later versions of Chapel (1.12.0, 1.13.0, 1.15.0, and 1.17.0) cause the execution to hang.

### Steps to Reproduce

**Source Code:**

config const numTasks = here.maxTaskPar;
forall tid in 0..#numTasks do
  writeln("Hello from task " + tid); 

**Compile command:**

chpl --fast -o hello hello.chpl

**Execution command:**

aprun -cc none -d16 -n4 -N1 -j0 ./hello_real -nl4 --numTasks=16 --verbose 

**Associated Future Test(s):**

### Configuration Information

- Output of `chpl --version`:
1.17.0, 1.15.0 1.13.0 and also 1.12.0 (using dlmalloc instead of jemalloc)

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
machine info: Linux titan-ext4 3.0.101-0.47.106.11-default #1 SMP Tue Jan 2 10:46:28 UTC 2018 (afabf7c) x86_64
CHPL_HOME: /lustre/atlas/scratch/user/project/framework/chapel/chapel-1.17.0 *
script location: /lustre/atlas2/project/scratch/user/framework/chapel/chapel-1.17.0/util
CHPL_TARGET_PLATFORM: cray-xe
CHPL_TARGET_COMPILER: cray-prgenv-pgi
CHPL_TARGET_ARCH: interlagos
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: gemini
  CHPL_GASNET_SEGMENT: fast
CHPL_TASKS: qthreads
CHPL_LAUNCHER: aprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: locks
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: system
CHPL_HWLOC: hwloc
CHPL_REGEXP: none
CHPL_AUX_FILESYS: none 

- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
gcc (SUSE Linux) 4.3.4 [gcc-4_3-branch revision 152973]

- (For Cray systems only) Output of `module list`:
Currently Loaded Modulefiles:
  1) eswrap/1.3.3-1.020200.1280.0
  2) craype-network-gemini
  3) pgi/17.9.0                            
  4) craype/2.5.13                         
  5) cray-libsci/16.11.1                   
  6) udreg/2.3.2-1.0502.10518.2.17.gem     
  7) ugni/6.0-1.0502.10863.8.28.gem        
  8) pmi/5.0.12                            
  9) dmapp/7.0.1-1.0502.11080.8.74.gem
  10) gni-headers/4.0-1.0502.10859.7.8.gem
  11) xpmem/0.1-2.0502.64982.5.3.gem        
  12) dvs/2.5_0.9.0-1.0502.2188.1.113.gem   
  13) alps/5.2.4-2.0502.9774.31.12.gem
  14) rca/1.0.0-2.0502.60530.1.63.gem
  15) atp/2.1.1
  16) PrgEnv-pgi/5.2.82
  17) cray-mpich/7.6.3
  18) craype-interlagos
  19) lustredu/1.4
  20) xalt/0.7.5
  21) git/2.13.0
  22) module_msg/0.1
  23) modulator/1.2.0
  24) hsi/5.0.2.p1
  25) DefApps

**Comment by bradcray** [comment]
Off-issue we discussed trying compilers other than pgi and `CHPL_COMM=ugni` to see if those helped at all.  We do nightly testing on an XE, so another thing to do would be to compare CLE version numbers and your module list vs. the ones that we use in that testing configuration.

**Comment by OrwellsGhost** [comment]
'module swap PrgEnv-pgi PrgEnv-gnu' fixed the problem.  Thanks!
