### ISSUE TITLE
Make the LLVM back end work on 64-bit ARM

### ISSUE THREAD

**Issue by dmk42** [chapel-lang/chapel#9225]
As a Chapel user, I want to be able to use the LLVM back end to generate Chapel code for 64-bit ARM systems because I want to take advantage of the llvm-wide-opt optimizations and extern blocks.

Currently, Chapel's LLVM back end does not support 64-bit ARM due to ABI incompatibilities.

**Comment by mppf** [comment]
This was addressed in PR #15990 and previous PRs.
