### ISSUE TITLE
Task-Resetting: Remove workaround from StencilDist

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#9237]
PR #9231 implemented a workaround for a task-resetting related regression in PRK Stencil. The fix was to not rely on default initializers and to instead explicitly write an initializer, which avoids a forall loop that would offset tasks.

Once task-resetting is addressed, we should go back to default initializers.

**Comment by ronawho** [comment]
https://github.com/chapel-lang/chapel/issues/9618 tracks the core task-resetting issue
