### ISSUE TITLE
Import HDF5 Files in Parallel

### ISSUE THREAD

**Issue by benjamin-robbins** [chapel-lang/chapel#9263]
As a chapel developer, I want to be able to use a chapel library to import multiple HDF5 files (with the same structure) from a single directory in parallel with a single function call so that I don't have to manual import each file.

Acceptance Criteria: Pass in dir path to function in lib, all data imported in HDF5 files under that dir are imported into an array in chapel.

**Comment by daviditen** [comment]
PR https://github.com/chapel-lang/chapel/pull/9707 adds a function to read HDF5 files into arrays in parallel.
