### ISSUE TITLE
Allow use of concrete type alias to call generic initializer?

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#9268]
Consider the following program:
```chpl
// Assume initializers
class C {
  type t;
  var x : t;
}

// Goal: return C(t)
proc helper(foo, type t) {
  return new (foo.type)(t);
}

var c = new C(int);
var h = helper(c, string);
```

While we currently consider this to be an invalid program, the goal of this code seems potentially useful: given a concrete instantiation, create a different concrete instantiation of the same generic type.

Encountered while looking at partial reduction code, where we want to take a ``ReduceOp(T)`` and return a ``ReduceOp([] T)``.

**Comment by bradcray** [comment]
In your example, my intuition is that `foo.type` should result in `C(int)` rather than a generic `C`.  So if that's right, it seems like we would need some other sort of query to get the generic version of the expression's type. What partial reduction code are you referring to?

**Comment by benharsh** [comment]
Here's the program:

https://github.com/chapel-lang/chapel/blob/450d7423b0cd4d8cba992a9fefaaf7e0faf1ef8b/test/reductions/partial/DRimpl.chpl#L23

**Comment by benharsh** [comment]
I think the language has long diverged from permitting this kind of feature simply through ``.type``, which to my knowledge hasn't been requested by anyone else. Closing.
