### ISSUE TITLE
delete-free subtask: compiler flag to toggle default class type meaning

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#9289]
As a Chapel user migrating code to the new class ownership system, it would help significantly in such migrations if I can toggle between the old and new system within the same version of the compiler. This will allow me to more easily convert code, since I can verify it works with that version of the compiler before starting migration.

See design discussion here: https://github.com/chapel-lang/chapel/issues/9278#issuecomment-382852278

This flag will help with migrating user code because the delete-free language changes can be toggled on and off separately from the other language changes.

Acceptance criteria:
New compiler flag allows toggling between class types / new default to unmanaged and default to borrow.

**Comment by mppf** [comment]
Even if we change the default, the compiler needs to know about the difference between unmanaged and borrowed when they are used explicitly e.g., for example in function resolution's choice of overload.

**Comment by mppf** [comment]
I wonder if it's possible to change this behavior by adjusting Scope Resolve?

**Comment by mppf** [comment]
We could do that, but the problems are two:
 1. We'll want the default toggle to apply to class types outside of `new` (e.g. `var x:MyClass`)
 2. `new t()` where `t` is a `type t` argument shouldn't be changed in this way.

**Comment by bradcray** [comment]
Good points... bummer.
