### ISSUE TITLE
Remove internal create_atomic helper functions in favor of initializers

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#9297]
Our internal atomic types follow this basic pattern for initialization:
```chpl
proc create_atomic_type() {
  var ret : atomic_type;
  atomic_init_atomic_type(ret, _defaultOf(base_type));
  return ret;
}

record atomic_type {
  var _v:atomic_type = create_atomic_type();
}
```

The helper function can be eliminated with initializers:
```chpl
record atomic_type {
  var _v:atomic_type;
  proc init() {
    this.complete(); // cannot use '_v' until it is initialized
    atomic_init_atomic_type(_v, _defaultOf(base_type));
  }
}
```

**Comment by ronawho** [comment]
👍 

Minor nit, instead of `atomic_init_atomic_type(_v, 0)`, I think it should be something like `atomic_init_atomic_type(_v, _defaultOf(base_type))` (initialize it to the default value of the non-atomic base-type instead of hardcoding to 0/false/0.0/whatever)
