### ISSUE TITLE
Should enums support `<`, `<=`, `>`, `>=` by default?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#9306]
Issue #8794 proposed that the compiler should only create `==` and `!=` comparisons for enums by default.  It could be argued that it should also create `>`, `>=`, `<`, and `<=` since an enumerated type has a well-defined order.

One challenge to implementing such comparisons is that if an enum's underlying integer values were not statically known to be monotonically increasing, these couldn't be implemented simply by casting to integers and calling the integer comparisons.  Instead, we'd need to have some sort of "enum to order" function that would convert an enum to an ordinal value that we could do the comparison on.  This is functionality that would likely be required to support enum ranges as well (see #9117).  Presumably, with additional effort the compiler could distinguish between cases that need this extra conversion step and those that don't in order to implement the monotonic case more efficiently.

[edited to capture further discussion below]:

In discussions, some argued that they would want these operators to compare the underlying integer values rather than the declaration order of the enums.  However, we ended up agreeing/acquiescing that respecting the declaration order was the right thing for enums based on the following argument:

1) In most cases, the two orders are the same, either because the user has either not given their enums integer values, or because they've given them monotonically increasing integer values.

2) When the orders are not the same, we'll argue that the enumeration order is preferable because:
  a) comparisons against the enum values can always be obtained by casting to integers or overloading these operators themselves if that's what's truly wanted
  b) if users want a specific order, they can reorder the enum to reflect any order; but if the integer values encode certain properties (say by using a bitmask that doesn't result in monotonically increasing values), they may not be able to give them different values.

**Comment by bradcray** [comment]
One argument against supporting such comparisons is that, intuitively for many enums, there's no reason to believe that "red" should be less than "blue" (say) just because they happened to be listed in a given order.

**Comment by mppf** [comment]
I find the point about ranges reasonably compelling but am unconvinced by the argument that the declaration order is somehow more natural / better than the integer value order.

**Comment by mppf** [comment]
But, it's also unclear to me why we would want to support enum ranges.

**Comment by bradcray** [comment]
Capturing some cases where codes wanted to use comparisons on enums, for future reference:

* Our `BLAS` module used comparisons in its `gemm()` routine to see what opA was passed in
* Some programs that use the `sorted()` iterator (the "sorterator") on associative domains required it in order to apply the sort to the enumerated indices

**Comment by bradcray** [comment]
As noted in the (edited) original message above, we decided to support these by default as described.  This was implemented in PR #9670, so I'm closing this issue.
