### ISSUE TITLE
Make basic ZMQ pair of programs

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#9349]
In preparation for calling Ben's AI workflow.

Stupid version: program A sends number to program B.  Program B returns that number + 1.  Program A writes both.

Check behavior:
- [x] on same machine
- [x] across compute nodes
- [x] from a compute node and a log in node.

**Comment by lydia-duncan** [comment]
Debating whether this implies that Chapel should handle the ZMQ calls (called via Cython) or whether it's okay to just transform everything into a string and then back.

**Comment by bradcray** [comment]
I think this reinforces what we were suspecting already:  That we probably want Python to talk through Cython (or whatever) to Chapel running on the same node, and then have Chapel talk through ZMQ to Chapel running on the distributed nodes.

**Comment by bradcray** [comment]
Here's my minor mod to Lydia's `foo.chpl` from above s.t. the compute node's name is fed into the program as a config const rather than embedded into the source text:

```chapel
use ZMQ;

config const node: string;

if node == "" then
  halt("Must specify compute node name using --node=<name>");

var context: Context;
var socket = context.socket(ZMQ.REQ);
socket.connect("tcp://"+node+":5555");

var val = 42;
socket.send(val);
writeln("sent: " + val);
val = socket.recv(int);
writeln("received: " + val);
```
