### ISSUE TITLE
Slow Sparse Matrix Addition

### ISSUE THREAD

**Issue by Tshimanga** [chapel-lang/chapel#9364]
I tried using `.plus()` to add a large (square 10^6 with 10^6 nonzeros) matrix to it's transpose using

`var ppt = P.plus(PT);`

and the computation hadn't finished after 45 minutes so I killed it.

I wrote my own matrix addition method to work around this as follows

````
proc matPlus(A:[],B:[]) {
  var dom = {A.domain.dim(1),B.domain.dim(2)};
  var sps = CSRDomain(dom);
  sps += A.domain;
  sps += B.domain;
  var S: [sps] real;
  for (i,j) in sps {
    S(i,j) = A(i,j) + B(i,j);
  }
  return S;
}
````

and with that instead, the same line ran in 26 seconds.

**Comment by ben-albrecht** [comment]
I believe this is related to #9344.

**Comment by ben-albrecht** [comment]
Here's a standalone reproducer of this perf difference:

```chpl
// Sparse case

use Time;
use LinearAlgebra.Sparse;

var t: Timer;

var ADom = CSRDomain(2553515);
var BDom = CSRDomain(2553515);

var Aindices = for i in 1..1000000 do (i,i);
var Bindices = for i in 2..2000000 by 2 do (i,i);

ADom += Aindices;
BDom += Bindices;

var A: [ADom] real = 1.0;
var B: [BDom] real = 2.0;

writeln('Inputs created');

t.start();
{
  var CDom = CSRDomain(ADom.parentDom);
  CDom += ADom;
  CDom += BDom;
  var C: [CDom] A.eltType  = [ij in CDom] A[ij] + B[ij];
}
t.stop();
writeln('forall ij in CDom');
writeln(t.elapsed());

t.clear();
t.start();
{
  var C = A.plus(B);
}
t.stop();
writeln('A.plus(B)');
writeln(t.elapsed());
t.clear();
```

**Comment by ben-albrecht** [comment]
This was caused by slow sparse domain assignment, which was sped up by ~900x for CSR domains in https://github.com/chapel-lang/chapel/pull/14112.

@Tshimanga - Thanks again for making us aware of this, and thanks for addressing it @e-kayrakli!
