### ISSUE TITLE
add error handling to mason

### ISSUE THREAD

**Issue by psahabu** [chapel-lang/chapel#9375]
### user story

As a Chapel programmer, I want my package manager to be resilient to errors because such protection prevents me from needing to handle packages manually, and provides next steps for resolving errors.

### acceptance criteria
- mason no longer uses `halt()` et. al.
- All errors provide clear direction to the user for next steps.

**Comment by ronawho** [comment]
Why is this closed? Because it's a duplicate of https://github.com/chapel-lang/chapel/issues/8868?

**Comment by psahabu** [comment]
Yeah I made the issue before realizing that #8868 was a thing.
