### ISSUE TITLE
spike: which error handling modes should be supported?

### ISSUE THREAD

**Issue by psahabu** [chapel-lang/chapel#9379]
### user story
As a Chapel programmer, I want the language to support the right number of error handling modes because on one hand, I want my code to be free to unexpected errors, while on the other hand I want to be able to draft code quickly.

### questions
- [ ] Which of Fatal, Relaxed, and Strict modes should remain within the language?
- [ ] How will those different modes be accessed?

**Comment by ben-albrecht** [comment]
The answers to these questions have been settled for the time being.
