### ISSUE TITLE
add Curl testing

### ISSUE THREAD

**Issue by psahabu** [chapel-lang/chapel#9381]
### user story
As a Chapel programmer, I want the Curl library to be tested because I want to have confidence when I use it in my libraries and programs.

(Under the Error-handling Epic because it was initially motivated by #7570, a bug against Error handling.)

### acceptance criteria
A test suite is set up for the Curl library and works in nightly testing.

**Comment by psahabu** [comment]
I have a branch open for this task, but it is rather old: https://github.com/psahabu/chapel/tree/curl-tzakian

**Comment by mppf** [comment]
This is done.
