### ISSUE TITLE
Is halting in pure virtual methods acceptable short term?

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#9393]
So far as I know, we don't actually have pure virtual methods today (https://github.com/chapel-lang/chapel/issues/8566 proposes introducing them). However, we do have a couple of cases that fake them by using methods that just halt. 

The ones that I have found so far are:
 - _throwPVFCError() -- used by ChapelLocale (and one mock locale test)
 - TZInfo -- halts with "Abstract base method called"
 - BarrierBaseType -- halts with "<proc> not implemented"
 - some base distributions call halt with "<dsiProc> is not implemented"

As part of our effort to prevent module code from halting (https://github.com/chapel-lang/chapel/issues/8695 and https://github.com/chapel-lang/chapel/issues/8626) I've found myself wondering what to do about these cases in the short term. I _think_ once pure virtual functions are actually implemented this will just go away (and will be a compilation error instead of a runtime error.) 

However, in the short term I'm thinking about adding something like `pureVirtualMethodHalt()` (or maybe keeping the ugly `_throwPVFCError()`). This should make it easier to grep for virtual function in the future, unify the error message, and remove explicit calls to `halt()`

**Comment by bradcray** [comment]
I don't personally have a problem with keeping these halt()s until such time as we have pure virtual functions.  Adding a comment to such cases may be sufficient to grep for them in the future and permit focusing on cases that are reasonable to convert to error-handling (?).

**Comment by ronawho** [comment]
>Adding a comment to such cases may be sufficient to grep for them in the future and permit focusing on cases that are reasonable to convert to error-handling (?).

I'd like to add a script similar to [lookForBadRTCalls](https://github.com/chapel-lang/chapel/blob/master/util/devel/lookForBadRTCalls), but looking looking for `halt()`, `try!`, `__primitive("chpl_error")`, and `assert()` so as much as possible I'd like to get rid of explicit calls to `halt()` (even if they're just replaced with calls that eventually halt)

**Comment by ronawho** [comment]
We have decided that halting is acceptable short term, and created a `pureVirtualMethod()` halt in https://github.com/chapel-lang/chapel/pull/9832

With https://github.com/chapel-lang/chapel/pull/9832, https://github.com/chapel-lang/chapel/pull/10220, https://github.com/chapel-lang/chapel/pull/10331 most halts are converted over to use `pureVirtualMethodHalt()` and the `_throwPVFCError()` routine is gone
