### ISSUE TITLE
What is the expected behavior for pop_front on an empty list/vector?

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#9399]
Currently `pop_front()` (which should really be converted to camelCase) just halts when the list is empty. I would like to treat this as undefined behavior (UB), but halt if boundsChecking is on. (I believe pop_front on an empty list is basically the same as an out-of-bounds array access, so we should treat them similarly). Note that this behavior is undefined for C++/Swift, and I think Python

---------------------
Alternative proposals:

 - return` _defaultOf(eltType)`:
   - I don't love this. Seems expensive (length check required), and like it would just hide errors 
 - throw:
   - I don't love this either. Also seems expensive (length check, and call site error checking) and I would imagine most users will just ignore this error
   - Maybe we could have the default pop be UB, and have a `checked_pop_front()` or something?

----------------------------
Behavior in other languages:

This is definetly UB for both  [`list::pop_front()`](http://www.cplusplus.com/reference/list/list/pop_front/) in C++  and [`array.removeFirst()`](https://developer.apple.com/documentation/swift/array/2884646-removefirst) in Swift
 - C++ says "If the container is not empty, the function never throws exceptions (no-throw guarantee). Otherwise, it causes undefined behavior."
 - Swift says "The collection must not be empty."

Python [`list.pop(0)`](https://docs.python.org/3/tutorial/datastructures.html#more-on-lists) seems to throw an exception, though the documentation just says "It is an error if there is no such item". `list.index()`, explicitly says it "raises a ValueError", so I'm guessing since `pop()` doesn't explicitly say it throws, that it's implementation defined what happens, so probably similarly UB.

**Comment by bradcray** [comment]
This seems related to issue #8601

**Comment by daviditen** [comment]
`array.pop_front()` and `array.pop_back()` on an empty array already do what @ronawho suggests in the top proposal.  It is UB if bounds checking is off, and halts if bounds checking is on.  I agree that it would be reasonable for `list.pop_front()` to do the same.

**Comment by ronawho** [comment]
Converted to `HaltWrappers.boundsCheckHalt()` in https://github.com/chapel-lang/chapel/pull/10255
