### ISSUE TITLE
Spike: AI workflow in container

### ISSUE THREAD

**Issue by benjamin-robbins** [chapel-lang/chapel#9405]
Understand container story for AI workflow

**Comment by ben-albrecht** [comment]
Successfully ran a multilocale Chapel program in a singularity container. 

There are still some open questions about the final interface for launching these programs, however.

One idea is to have a Chapel launcher specifically for the Cray analytics stack. This is easier than it sounds. Cray analytics has a tool similar to Chapel launchers, so we'd just need to map the Chapel launcher flags to theirs.
