### ISSUE TITLE
Should Chapel support UTF-8 identifiers?

### ISSUE THREAD

**Issue by dmk42** [chapel-lang/chapel#9406]
Should it be possible to use UTF-8 alphanumeric characters in identifiers, such as variable names?

A reason to do this:
It allows non-English identifiers, possibly supporting adoption around the world.

A reason not to do this:
The keywords are in English, which will not change.  The combination looks strange.
```chapel
forall événement in Événements do
  yield événement;
```

Our parsing of identifiers is currently not 8-bit clean.  If we decide to support UTF-8 identifiers, our lexical analysis will need to change.

**Comment by ben-albrecht** [comment]
What are some other languages doing?

**Comment by mppf** [comment]
Pretty much every modern language seems to be on this list:

https://rosettacode.org/wiki/Unicode_variable_names

I think we should allow it, within reason.

**Comment by benharsh** [comment]
Does "UTF-8 alphanumeric characters" exclude zero-width/invisible characters?

**Comment by dmk42** [comment]
@benharsh - I'd be curious to know if you had something particular in mind.  I was thinking along the lines of characters for which `isalnum()` is true in a UTF-8 locale (using the C meaning of locale).

**Comment by benharsh** [comment]
A specific example I'm aware of is that clang++ with ``-std=c++11`` allows for zero-width characters in identifiers. I think most popular editors will render something for a zero-width character (e.g. a red dot), but it still seems like something we should disallow.

**Comment by dmk42** [comment]
I agree, allowing invisible characters would be asking for trouble.  I think we would have to go out of our way to allow them, so I'm surprised that clang++ does.  If they end up being allowed by whatever mechanism we choose, we probably ought to go back in and disallow them explicitly.

**Comment by dmk42** [comment]
The general opinion, including off-line discussions, is that we should allow UTF-8 characters in identifiers, but that it should wait until later (probably the Compiler 2.0 front end).  I have created issue #9545 to track this.
