### ISSUE TITLE
Scalability collection TODOs for 1.18

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#9413]
There are some remaining things that we should improve in our scalability collection scripts. I think we have what we need for this release, and I'm hesitant to make changes to scripts that won't actually get tested until next release, so this issue is just to capture the remaining todos:

 - Continue to improve logging: 
   - Need to log when a timeout occurs (and prevent any more trials from running)
   - Need to log non CHPL env vars that we set (by putting them in the scale-config.json instead)

 * Use our launcher on edison: 
   * instead of doing manual sbatch/srun

- move the scalability collection scripts to the public repo (https://github.com/chapel-lang/chapel/issues/9339)
   - should try to unify problem sizes between regular multi-locale and scalability runs

* Re-add ISx 
  * At 512/1024 scales ISx takes a long time to run, even though the kernel itself is fast (https://github.com/chapel-lang/chapel/issues/9414)

 - Automatically generate .gpi files from template 
   - Currently we create them by hand for each test

**Comment by mppf** [comment]
@ronawho - based on the title it seems like it might make sense to close this issue or rename it?
