### ISSUE TITLE
Spike: check STREAM against python interoperability to fully understand the impact of nogil

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#9417]
In the demo yesterday, we wondered about the impact of nogil on Chapel thread creation.  Threadring is not a particularly good demonstration of this impact, so Elliot suggested we try it with STREAM.  This spike it to get STREAM to run when called from Python and to observe the performance impacts of doing so with and without the GIL

**Comment by lydia-duncan** [comment]
Was able to get STREAM to run when called from Python.  We will need to do something about the globals not getting initialized, that's a bit annoying.

Results (with four runs):
Plain Chapel:
avg - .2229845 (variability .009362)
min - .219714 (variability .002592)

Cython with gil:
avg - .21189825 (variability .001741)
min - .209382 (variability .001583)

Cython without gil:
avg - .21308975 (variability .006087)
min - .209591 (variability .001648)

The two Cythons are too close together to be distinguishable and have some data overlap.  The Cythons have no data overlap with the plain Chapel runs, and the with gil numbers are just barely statistically significant from the plain Chapel numbers (the no gil numbers are not statistically significant).  Of course, statistical significance should be taken with a grain of salt because the max values are not provided for these runs, only average and min.

**Comment by lydia-duncan** [comment]
This is way less variation than was observed with threadring

**Comment by bradcray** [comment]
This is reassuring.  My sense of the GIL and what nogil could mean is that it might govern how Python data is / can be accessed from within an external program, but shouldn't have a direct impact on the execution of that external program if it never calls back into Python / refers to Python structures, etc.  Where I suspect that understanding this option better may matter is if/when we're trying to operate on Python arrays in situ without copying them.

**Comment by lydia-duncan** [comment]
This will also impact strings we get from Python as well.  But I agree that it is reassuring
