### ISSUE TITLE
ZMQ interoperability test times out with gasnet

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#9425]
### Summary of Problem

The ZMQ `interop-py` test (added in #7049) currently times out with gasnet configuration. This test was failing silently on nightly gasnet testing until #9072, which surfaced the test timing out. The configuration will be skipped until this issue is resolved.

Something about the gasnet communication layer is interfering with Chapel's ability to connect to the process it spawns. When running `client.py` separately, outside of the Chapel program, the connection succeeds and no timeout occurs.

It's unclear to me whether this is an issue with the test or the module so far.

Note that I have only tested gasnet locally (`GASNET_SPAWNFN=L`) on OS X so far.

### Steps to Reproduce

**Associated Future Test(s):**

 [`test/library/packages/ZMQ/interop-py`](https://github.com/chapel-lang/chapel/blob/master/test/library/packages/ZMQ/interop-py)
### Configuration Information

- Output of `chpl --version`: `chpl version 1.18.0 pre-release (ed162f8)`
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:

```
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: clang
CHPL_TARGET_ARCH: unknown
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: intrinsics
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: none *
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2 *
CHPL_AUX_FILESYS: none
```

**Comment by nspark** [comment]
Any updates on whether this is specific to OS X? I originally added the interoperability tests when running on a Linux laptop, but I don't think I ran the `interop-py` tests with GASNet (only `multilocale`). I can probably try `interop-py` with GASNet this soon-ish.

Are there any known issues between `Spawn.spawn()` and GASNet?

**Comment by cassella** [comment]
I get the hang on Linux too.

If I change the ``Spawn.spawn()`` call to launch ``sleep 60``, and
after starting the server, run ``client.py`` (via wrapper.sh)
separately, they'll both just sit there until the 60 seconds is up,
and then complete the communication.


I instrumented ZMQ.chpl a bit,

```diff
--- a/modules/packages/ZMQ.chpl
+++ b/modules/packages/ZMQ.chpl
@@ -843,17 +843,20 @@ module ZMQ {
     // recv, strings
     pragma "no doc"
     proc recv(type T, flags: int = 0) throws where isString(T) {
+      writeln("in recv");
       var ret: T;
       on classRef.home {
+       writeln("got home");
         // Initialize an empty ZeroMQ message
         var msg: zmq_msg_t;
         if (0 != zmq_msg_init(msg)) {
           try throw_socket_error(errno, "recv");
         }
-
+       writeln("zmq_msg_init returned");
         // Receive the message
         while (-1 == zmq_msg_recv(msg, classRef.socket,
                                   (ZMQ_DONTWAIT | flags):c_int)) {
+         writeln("zmq_msg_recv returned -1 errno ", errno);
           if errno == EAGAIN then
             chpl_task_yield();
```

when invoked with ``--spawnClient=false`` it reports a continuous
stream of "return -1 errno 11" (which is EAGAIN).  Launching the
client works immediately.

When invoked without the flag, so doing the spawn, it prints "return
-1 errno 11" *once*, and sits there until the sleep is done.  So it's
EAGAIN again, but ``chpl_task_yield()`` must not be returning while
the spawned subprocess is around?

**Comment by cassella** [comment]
I've reproduced the problem without ZMQ.  It feels like ``client.communicate()``
doesn't call anything like ``chpl_task_yield()`` while waiting for the
spawned task.

On my laptop (2 cpus), this program prints both lines immediately when run with ``--n 1``.
The lines are separated by fifteen seconds when run with ``--n 2``:

```chapel
use Spawn;

config const n = 1;

for i in 1..n {
  begin {
    var client = spawn(["sleep", "15"]);
    client.communicate();
  }
}

writeln("Wait");
chpl_task_yield();
writeln("for it");
```


I get the same behavior with a ``CHPL_COMM=none`` build as with ``gasnet/udp``.


I'm guessing that something in ``ZMQ`` is also creating a chapel task that doesn't yield, and that's why it takes only one ``Spawn.communicate()`` to hang?

**Comment by ben-albrecht** [comment]
Thanks for the info @cassella - it was very helpful in narrowing down the issue.

> I'm guessing that something in ZMQ is also creating a chapel task that doesn't yield, and that's why it takes only one Spawn.communicate() to hang?

It looks like ZMQ does [yield properly](https://github.com/chapel-lang/chapel/blob/master/modules/packages/ZMQ.chpl#L778-L785) whereas `spawn.communicate()` makes blocking calls in 2 places (`select` and `waitpid`). 

I have a fix on the way that replaces these blocking calls with while-looped non-blocking calls that yield instead.

**Comment by bradcray** [comment]
Pinging @mppf on this as the author of the Spawn module and @ronawho as the master of efficient waiting.

**Comment by ben-albrecht** [comment]
https://github.com/chapel-lang/chapel/pull/9507 is still open with some TODOs. It's not in my priorities for this sprint, but maybe I could finish it up as a background activity.
