### ISSUE TITLE
Globals declared in .chpl files compiled in library mode do not get given their declared value

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#9441]
### Summary of Problem
We don't seem to run a module's initialization function when `chpl_library_init` is called, meaning that globals and configuration constants in a library module do not get set up prior to any calls to functions that reference them.  I'm not sure if the module's initialization function is exported or not (probably not), but it should be either run automatically or something that the client program can call prior to calling any exported functions.

This issue blocks the AI port work

### Steps to Reproduce

**Source Code:**

```chapel
config const x = 10;

export proc whatIsX() {
  writeln(x);
}
```
Some code that uses this file as a library.

**Compile command:**
`chpl --library foo.chpl -o libfoo`

**Associated Future Test(s):**
TBA

### Configuration Information

- Output of `chpl --version`: Chapel 1.18.0 (pre-release)

**Comment by gbtitus** [comment]
Module initialization is called from the runtime by [this function](https://github.com/chapel-lang/chapel/blob/master/runtime/src/chpl-init.c#L222).  There are calls to it in two places in that same file, one for when we're a Chapel main program and another for library mode.

**Comment by lydia-duncan** [comment]
I'm talking about the user module I exported, the standard modules seem fine

**Comment by lydia-duncan** [comment]
library in this case means a .chpl file compiled using --library, not a Chapel standard library, sorry to be unclear

**Comment by gbtitus** [comment]
Ah, that's right, I'd forgotten that in the case of a program the user module initializers are called from `chpl_gen_main()`, which is a compiler-emitted function called by the runtime's `chpl-init.c:chpl_executable_init()`. They aren't called with the rest of the module initializers, and there isn't an equivalent for the library side of things.

**Comment by lydia-duncan** [comment]
Closing this, opening a new issue for the additional improvements to --library compiles we discussed
