### ISSUE TITLE
Move array-as-vec operations into a distinct type

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#9452]
As a Chapel architect, I am concerned about the overloading of vector operations on 1D arrays that happen to meet certain criteria, some of which are only knowable at execution time; because it seems fraught with problems (see below) and likely to break backwards compatibility in the future.

Acceptance Criteria:
* current vector operations are still available on something as convenient to declare and use as an array, but without

Problems:
* Chapel was designed such that anonymous domains could be known to be constant; yet in the current approach, they can't be assumed to be
* The current array-as-vec features permit a user to modify a domain declared as const:

```chapel
const D = {1..10};
var A: [D] real;
A.push_back(1.2);
writeln(D);  // prints {1..11}, yet D was supposed to be const
```

Background:
* our motivation for putting this onto arrays was to maximize code reuse by being able to send vectors in to routines expecting arrays without writing special overloads of the routines; I think this is something we want to preserve, but perhaps we can do it in a different way.

Possible alternative approaches:
* implement vector using a custom layout and provide utility functions to create vectors?
* user-defined coercions from vector type storing domain + array to array?
* cool use of advanced forwarding?
* constrained generics?

**Comment by benharsh** [comment]
What about a special range literal that turns into a ``DefaultVector`` (in the vein if DefaultRectangular, DefaultAssociative, etc.) ?

```chpl
var A : [..1..] int;
A.push_back(1);
var D : {..5..};
var B : [D] int;
```

The intent of ``..1..`` is to express the notion that vectors can grow in both directions. Even if we did like that (big 'if'), could we parse that?

**Comment by benharsh** [comment]
Do we want to support vector operations on arbitrary distributions?

**Comment by bradcray** [comment]
@benharsh: Thinking more about your [proposal above](https://github.com/chapel-lang/chapel/issues/9452#issuecomment-386409201) this weekend, I think a potential downside is that this pattern of wanting to wrap an array and have it behave in an array-like manner is something that comes up often in libraries, and so I think it's important that we be able to support patterns like this without requiring special syntax.  That said, I'm sortof tickled by how the proposal addresses concerns people have had about the learning curve of `[1..0]` being an empty array (though I'm also willing to believe we just need to improve our documentation / education on this).

> Do we want to support vector operations on arbitrary distributions?

Good question, I'm not sure.  Since we don't now (I think, right?) I'd be fine if we continued not to for now.

**Comment by benharsh** [comment]
> I think it's important that we be able to support patterns like this without requiring special syntax

It wasn't my intention to suggest that ``..1..`` would be the only way to create these things, if that's what you were thinking. We should definitely be able to write something like:
```chpl
class C {
  var D : domain(/*something for vector*/); // uses 0 or 1 as anchor index by default
  var A : [D] int;
  forwarding A;
}
```

**Comment by bradcray** [comment]
Over on issue #9478, @LouisJenkinsCS contributed the following feedback:

> I would be in favor of removing `push_back`, but only if we get a nice reliable vector/list data type. Doubly so if it were distributed, and with nice first-class language support for them. Syntax like...
> 
> ```chpl
> var x : Vector(int);
> var y : Vector(int);
> y.push_back(1..100);
> y += 1; // Vector operation on a Vector...
> x.push_back(y);
> // Make this parallel-safe...
> cobegin {
>    x.push_back(1);
>    x.push_back(2);
>    y.push_back(x);
>    y.push_back(y);
> }
> ```
> 
> Easier said than done, but even if it wasn't thread-safe, so long as it can support vector operations, I'm all for it. I'd also like a `Map` data type as well that supports vector operations, which can replace an associative array. I believe having named data types, `Set`, `Vector`, `List`, `Map`, etc., make it easier for the reader to understand the type of the object they are using. Also benefit of not having to add language syntax and constructs.

**Comment by mppf** [comment]
Two questions:
 * Are we interested in changing associative arrays in a similar manner? (Can't modify domain through the array)
 * Do people already have a good sense of whether or not we're talking about making a different array type (e.g. a quick suggestion`var x:[ growable ] int`) or a different type entirely (e.g. `var x: vector(int)` ) ? The difference here matters for #10911.

**Comment by bradcray** [comment]
> Are we interested in changing associative arrays in a similar manner? (Can't modify domain through the array)

Yes, I think so.

> Do people already have a good sense of whether or not we're talking about making a different array type (e.g. a quick suggestionvar x:[ growable ] int) or a different type entirely (e.g. var x: vector(int) ) ? The difference here matters for #10911.

I don't think we have a good sense, though I'm not thinking of it as a different array type in that sense—maybe a different domain map.  I suspect that if we had constrained generics today, it would simply be its own record type that wrapped a domain + array.  I think in any case we'd want a `List(int)` (or `Vector(int)` sugar for referring to the type even if it were a domain map under the hood.

**Comment by bradcray** [comment]
I wonder whether we can close this now or whether we should wait until the deprecated features are removed.  @dlongnecke-cray, @mppf, what do you think?

**Comment by bradcray** [comment]
(though I guess the feature is still not technically deprecated on master...  :'(  any day now, though, right?)

**Comment by dlongnecke-cray** [comment]
I think it is OK to close this issue, if no one else objects.

**Comment by dlongnecke-cray** [comment]
Resolved via the introduction of the `list` type, and the impending merge of #13999.
