### ISSUE TITLE
Type inference fails when called through initializer?

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#9459]
### Summary of Problem
When initializing `main:f3`, the third initializer calls another initializer. Type interference should be able to pick the more specific initializer (the first one), but it can't pick between the first and second. Why? The code works fine if `f3` is commented out (and the third initializer is never run).

Workaround is to use a `where` clause on the second initializer and remove it from being a viable candidate when T == bool. ~But this would mean `bool`s are coercing to `int`s somewhere... >:|~ On second look, this looks like the second initializer is being picked as a viable candidate (and is thus ambiguous with the first) even though the first initializer is more specific.

### Steps to Reproduce

**Source Code:**

```chapel
module TypeSpecificity {
class Foo {
  type T;
  var x: T;

  proc init(param is_int: bool) {
    T = if is_int then int else real;
    x = if is_int then 1 else 2;
  }

  //proc init(val: ?T) where T != bool {
  proc init(val: ?T) {
    this.T = T;
    this.x = val;
  }

  proc init(param is_int: bool, val: ?T) {
    this.init(is_int); // <-- Problem here.
    this.x = val;
  }

  proc writeThis(f) {
    f.write(T:string, " x=", x);
  }
}

proc main() {
  var f1 = new Foo(true);
  writeln(f1); // int(64) x=1
  var f2 = new Foo(3:int(32));
  writeln(f2); // int(32) x=3
  var f3 = new Foo(true, 4);
  writeln(f3); // int(64) x=4
}
}
```

### Configuration Information
`chpl version 1.18.0 pre-release (a6005281c5)`

**Comment by bradcray** [comment]
Surprising...  Thanks for reporting this, Bryant!

Interesting observation:  If the only call is the `f3` case, it seems to work properly.  Adding the `f2` case also seems to work.  The presence of the `f1` case seems to be what sends things down the wrong path.  This suggests to me that we're doing something wrong in the compiler, either in terms of having instantiated a generic for the first call that it's considering ambiguous incorrectly, or in terms of memoizing a result incorrectly (though the first seems more likely).

Interestingly, this does seem like it's specific to initializers if I've translated to other cases correctly:

standalone functions:
```chapel
proc foo(param is_int: bool) {
  writeln("In param bool case");
}

proc foo(val: ?t) {
  writeln("In generic case");
}

proc foo(param is_int: bool, val: ?T) {
  foo(is_int);
}

foo(true);
foo(true, 4);
```

non-init method:
```chapel
class Foo {
  type T;
  var x: T;

  proc foo(param is_int: bool) {
    writeln("In case 1");
  }

  proc foo(val: ?T) {
    writeln("In case 2");
  }

  proc foo(param is_int: bool, val: ?T) {
    writeln("In case 3");
    foo(is_int);
  }

  proc writeThis(f) {
    f.write(T:string, " x=", x);
  }
}

proc main() {

  var myC1 = new Foo(int, 3);
  myC1.foo(true);

  var myC = new Foo(int, 3);
  myC.foo(true, 4);
}
```

**Comment by benharsh** [comment]
This is indeed a problem with initializers.

Our 'more specific' implementation currently has some special handling for generic initializers. Apparently that handling is not triggered in all cases. I will begin working on a more robust approach once I close some of my open PRs.
