### ISSUE TITLE
'require' clauses not honored in library compilation

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#9466]
Not sure if this is an "issue", per say, but it's important to note that when linking a library created with the --library flag, if it has `require` statements involving libraries you have to explicitly provide those flags.

For example, if your library code has `use ZMQ;`, you have to link it with `-lzmq`

**Comment by bradcray** [comment]
This could be considered a feature request—perhaps compiling Chapel in library mode should create a Makefile stub in addition to the library (and, eventually, header file?) that would define some variables that specified requirements like this?

**Comment by lydia-duncan** [comment]
Oh, good point!  I'll link this to the generating files issue (#9311)
