### ISSUE TITLE
Use Github's new Checks API?

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#9470]
Github added a new checks API, which might be useful for improving or extending the amount of testing we do on PRs. Currently, we just have some travis-ci testing for a few basic things like running `make check`, `make check docs`, `lookForBadRTCalls`, and `check_annotations.py`.

See the [Github checks API blog post](https://blog.github.com/2018-05-07-introducing-checks-api/) for details.

**Comment by ronawho** [comment]
Related to https://github.com/chapel-lang/chapel/issues/6758

**Comment by ben-albrecht** [comment]
Maybe this would be a good fit for `chplspell` and `check_paths` scripts. What do you think @cassella ?

**Comment by ronawho** [comment]
Closing, I think the checks API was replaced with actions -- https://github.com/chapel-lang/chapel/issues/14442
