### ISSUE TITLE
Inclusion of function creates "It's not you, It's me" error

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#9475]
I have a complicated package so I'm pointing to the source code instead of pasting it here.  When extending a class in my [Relch policies](https://github.com/Deep6AI/Relch/blob/broken-constructor/src/policies.chpl#L60-L88) I get the 

If you decide to compile this yourself, you'll need a file called `local.mk` that look like

```
CHINGON_HOME=$(HOME)/git/chingon
NUMSUCH_HOME=$(HOME)/git/numsuch
CDO_HOME=$(HOME)/git/cdo
CDOEXTRAS_HOME=$(HOME)/git/cdo-extras
CHARCOAL_HOME=$(HOME)/git/Charcoal
BLAS_HOME=/usr/include/
CHREST_HOME=$(HOME)/git/chrest
RELCH_HOME=$(HOME)/git/Relch
```

Also note the branch is `broken-constructor` If you run `make` it should compile.  If you run `make test` it will fail with

```
make test
chpl -M/home/buddha/git/chingon/src -M/home/buddha/git/cdo/src -M/home/buddha/git/numsuch/src -M/home/buddha/git/cdo-extras/src -M/home/buddha/git/Charcoal/src -Msrc --fast --print-callstack-on-error --print-commands -I/usr/include -I/usr/include//include -I -L/usr/include//lib -lblas -o test/test test/RelchTests.chpl ;\
./test/test ; \
rm test/test
internal error: BAS0316 chpl version 1.18.0 pre-release (111c69353f)

Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug -- 
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.

/bin/sh: 2: ./test/test: not found
rm: cannot remove 'test/test': No such file or directory
Makefile:21: recipe for target 'test' failed
make: *** [test] Error 1
```

This does not appear to be an error in my code.  The specific function that causes the error is in the `policies.chpl` file, around line 81. Including `proc` and it fails, excluding `proc` and it runs.

```
proc f(options:[] int, state:[] int) {
    //var targetPosition = this.sensor.target.position;
    //writeln("target position: ", targetPosition);
    //var opt:[1..options.shape[2]] int;
    var opt:[1..4] int;
    return opt;
}
```

```
chpl --version
chpl version 1.18.0 pre-release (111c69353f)
Copyright (c) 2004-2018, Cray Inc.  (See LICENSE file for more details)



 printchplenv 
machine info: Linux ubuddha 4.13.0-39-generic #44-Ubuntu SMP Thu Apr 5 14:25:01 UTC 2018 x86_64
CHPL_HOME: /home/buddha/git/chapel *
script location: /home/buddha/git/chapel/util
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: intrinsics
CHPL_GMP: system *
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none
```

**Comment by buddha314** [comment]
Continuing on this, the error only occurs when you try to call `var tfp = new FollowTargetPolicy(sensor=new Sensor(name="can't see squat"));`  If I don't call `new`, it's fine.

**Comment by buddha314** [comment]
I have learned that if I rename that function `f` in FollowTargetPolicy to `g` it compiles and runs.  I don't understand why this overload creates the problem, since the `f` overloads in RandomPolicy and QLearningPolicy work just fine.

**Comment by buddha314** [comment]
The story is only getting more bizarre.  If I don't call the function `f` on FollowTargetPolicy, it errors with the "not you".  See [these lines](https://github.com/Deep6AI/Relch/blob/broken-constructor/test/RelchTests.chpl#L241-L244) of the test file.  If I DO call `f`, it completes. 

This makes no sense to me, but it appears that the complier is only checking the return type or something on functions that are actually called. If `ClassA.f()`  and `ClassB : ClassA .f()` are not both called, it seems to get confused.  Any thoughts?

**Comment by ben-albrecht** [comment]
>Including `proc` and it fails, excluding `proc` and it runs.

Could you clarify what this means?

I suggest compiling with `CHPL_DEVELOPER=1` or the `--devel` flag. This will give you the actual error message, rather than the generic internal error message.

**Comment by mppf** [comment]
The links to the reproducer seem broken and I'm doubtful that the issue still exists. If somebody comes up with a short reproducer we can look at it.
