### ISSUE TITLE
Default to gcc 8 for nightly testing

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#9482]
We test a lot of configurations (different platforms, OSs, backend compilers) for portability, but we have a "primary" backend compiler that we use for a large fraction of configurations. Currently we're using gcc 6.3, because we had several issues with gcc 7: https://github.com/chapel-lang/chapel/issues/6481.

We like to run with the most recent release of gcc. gcc 8 seems to be much more stable as a backend compiler for us, so we should try to make it our default. Misc things to test:
 
 - [x] std configuration correctness
 - [x] std gasnet configuration correctness
 - [x] single-locale performance (specifically string tests that regressed with gcc 7)
     - There are no major regressions for the [string tests](https://chapel-lang.org/perf/chapcs/gcc81/?startdate=2018/05/03&enddate=2018/05/12&graphs=stringtemporarycopies,allocatingstringoperations,passingandreturningstrings,searchesovernstrings)
     - There a various regression and improvements for many other tests. None of which give me deep concern
 - [x] multi-locale performance
   - some minor regressions and improvements (nothing that should prevent switching):
     - ~5% improvement for isx-hand-optimized
     - ~5-10% improvement for CoMD
     - ~5% regression for NPB EP
     - ~50% regression for non-optimized stencildist PRK-Stencil
 - [x] sporadic multi-locale lulesh failure we saw with gcc 7 (passed 500 trials w/ gcc 8.1, gcc 7 failed 1/5 trials)

After switching the default to gcc 8 we should also: 
 - [x] add a nightly config to do limited testing on gcc 6.3
 - [x] update nightly config that does limited testing on gcc 7.2 to test 7.3
 - [x] update https://github.com/chapel-lang/chapel/issues/6481 to recommend against gcc 7.X for performance and correctness reasons

**Comment by ronawho** [comment]
@dmk42 From my perspective gcc 8.1 looks good. Once it's the default on internal crays, I think we should default to that for nightly testing.

**Comment by ronawho** [comment]
gcc 8.2 is the new default on internal crays. @dmk42 When you get a chance could you install 8.2 for chap*?

**Comment by dmk42** [comment]
We said we would do this when gcc 8 became the default on internal Cray systems.  That has now happened, so it is time for me to do this.

**Comment by dmk42** [comment]
Gcc 8.2 has now been installed on the internal cluster.  It has been tested on linux64 (x86_64 and ARM), Cray XC, and Ubuntu.

Once #11711 is merged, we will be ready to switch to gcc 8.2 as the nightly testing default.

@ronawho - Are you interested in trying 8.2 in the perf playground first?

**Comment by ronawho** [comment]
> @ronawho - Are you interested in trying 8.2 in the perf playground first?

Results are up at https://chapel-lang.org/perf/chapcs/gcc82/?suite=performancetracking

There are minor differences for a handful of tests, but nothing that concerns me.

**Comment by dmk42** [comment]
Now that the dust has settled from #11762 it looks like we can close this issue.  (Feel free to reopen if you disagree.)
