### ISSUE TITLE
issues with eliding copies from expiring values

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#9490]
I earlier implemented a compiler pass to elide copies and assignments when the RHS value was dead. But, it was reverted due to an unexpected problem discovered in testing. See also PRs #2868, #3104, #3103, #3109, in which it is referred to as "expiring value optimization". However it's probably not something we'd want to turn on and off with `--fast` so isn't so much an optimization as just what the language does.

What was the problem that came up? Here is a simplified example from #3103 (test/types/records/ferguson/expiring-value-alias.chpl):

``` chapel
class C {
  var x:int;
}

record R {
  var c:C;
}

// R's copy initializer creates a new class
proc R.init(copyFrom:R) {
  this.c = new C(copyFrom.c.x);
}
// R's assignment function is not used in this example.
// (but one would normally also make such a thing)

// This function just creates an R with an allocated class instance
proc makeR(x:int) {
  var ret: R;
  ret.c = new C(x);
  return ret;
}

var globalR = makeR(100);

proc test4() {
  // Here we set up a local record that contains a pointer
  // to the same class instance as the global record.
  // It is done directly here but you might imagine API
  // functions that do this (e.g. aliasing arrays was the
  // original example, string.localize() can do it too).
  var local_dom:R;
  local_dom.c = globalR.c;

  // Now create a new variable copy-initialized from local_dom.
  // Note that the copy-initializer for R (the type of these variables)
  // will create a new instance (so curr_dom.c != local_dom.c after
  // this line).
  //
  // Also note that local_dom is dead at this point and thus the
  // "Elide copies from expiring values" rule can apply
  // to elide this copy initialization (and "move" from local_dom
  // into curr_dom).
  var curr_dom = local_dom;

  // Lastly, we'll update our local variable curr_dom.
  // Note that this update is modifying something
  // inside the class instance that curr_dom points to.
  curr_dom.c.x = 3;

  // Did the previous line modify globalR.c.x ?
  // Did curr_dom.c point to the same instance as globalR.c ?
  // Or a different instance? In the original example, the
  // programmer intent was that it point to a different instance.
  // However eliding the copy-initialization of curr_dom above
  // changes it to point to the same instance.

  writeln(globalR);
}

test4();
```

The problems seem to come up when a record is logically mutable and can sometimes alias another record (as when containing a pointer).

How could we rule out a case like the above? I think it would be sufficient to check either:
- the record cannot logically alias something else (e.g. another record)
   - but it would be OK if the copy/assign overloads always copied the pointer (e.g. with the default copy initializer for R instead of the one provided above that creates a new class instance)
- the LHS available for copy-elision is not logically mutated (including mutation through a pointer member) 

Other notes:
- creating a reference to a field in the RHS should arguably prevent the optimization
- PR #3110 explores enabling the copy-elision only for compiler-introduced variables

**Comment by mppf** [comment]
I think that this issue is related to #11534.

**Comment by vasslitvinov** [comment]
Speaking about arrays in particular, copying of array elements upon the initialization:

```chpl
var B = A; // both are arrays
// or equivalent when 'A' is passed to a function by in-intent
```

can be elided when:
* `isPOD(A.eltType)`, and
* nothing accesses A or its elements afterwards.

The latter could be established conservatively when:
* there are no `ref` decls whose RHS contains 'A' passed by ref, and
* 'A' is not passed by ref to something that captures it in a `begin`.

The check for `begin` could be conservatively approximated by checking for `sync` statements around the scope of 'A'. Without a sync statement, capturing 'A' is illegal/undefined anyway.

**Comment by mppf** [comment]
I think we'd probably want to not apply the copy elision if the copy is `var` but the copied-from dead value is `const` or `const ref`. Because then if the `var` value is mutated, we don't have const-correctness.

**Comment by mppf** [comment]
> I think we'd probably want to not apply the copy elision if the copy is var but the copied-from dead value is const or const ref.

Actually I think the expiring values analysis covers it already, at least in the md case. The existence of aliasing is the problem.

> the record cannot logically alias something else (e.g. another record) 

I think the expiring value analysis covers this.

I know of these open questions:

* Should copy elision change assignment like `lhs = rhs` into `deinit/move` ? If we did, I think we'd need a way to have a record implementation adjust fields at that point, especially in the event that lhs and rhs are stored on different locales, e.g. `proc R.postmove(fromLocale:locale)` (from https://github.com/chapel-lang/chapel/issues/14271#issuecomment-546388943). Note that in this `=` pattern the lhs and rhs can be on different locales and the compiler cannot detect that by looking for `on` statements e.g.
* How does the copy elision interact with runtime types? Perhaps we need a `R.postmove(runtimeType)`. But we could start by disallowing it for types with runtime type.
* Does copy elision use the same "last mention" point as deinit calls? Or is it less strict? For example, would it go within a nested block? `var a = ...; { var b = a; }`
* How does copy elision applied to copy initialization (vs `=`) interact with `on` statements? In this case, it's possible for the compiler to detect if the destination variable is created within an `on` statement - and it wouldn't consider the variable "dead" until after the on statement if the usual deinit point is used:

``` chapel
var a = new R();
on Locales[numLocales-1] {
  var b = a; // copy elision does not occur because a is not dead until after on statement?
}
// a dead here
```

**Comment by mppf** [comment]
I've created #14860 to focus more on the design proposal here.

**Comment by mppf** [comment]
Plan from #14874 is implemented; closing.
