### ISSUE TITLE
Should unmanaged and borrowed types have a .borrow() method?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#9501]
It occurs to me that `shared` and `owned` are nicely symmetric in that you can call the `.borrow()` method to get a borrow out of them. Since borrowing from an unmanaged pointer is also possible (and in fact happens automatically in many cases with coercions) should unmanaged pointers also support a `.borrow()` method to make the operation clearer?

Pros:
 * Allows code borrowing from unmanaged to be written more clearly (I think myVariable.borrow() is clearer than myVariable:MyClass)
 * Allows code borrowing from unmanaged to be written without figuring out or naming the borrow type (e.g. myVariable:MyClass vs myVariable.borrow() ) which can make it easier to write code that is generic for many class types
 * Enables generic code to work with unmanaged and borrowed just as well as it works with owned or shared

Cons
 * Would imply that one cannot make a method on a class type called `.borrow()` since this is reserved for the borrowing operation

**Comment by psahabu** [comment]
I also support this proposal.
