### ISSUE TITLE
User-Defined Reduction Interface (UDRI) design

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#9542]
Last significant edits:
* 6/15 : switch to a simple interface #9879
* 6/08 : add Design Goals
* 6/01 : introduce Minimal Interface and Full Interface

#### Switch to a simple interface

6/15: #9879 defines a simple interface that will be sufficient for most needs. When we see a use case that we would like to handle and that interface is not enough, we will return back to this discussion.

Other key changes in #9879 compared to the proposal below:

* The reduction author never has (nor can) deal with synchronization concerns. I.e. parSafe is always false and so is eliminated from the interface.

* Instead of having two distinct interfaces, allow each action to be specified in multiple ways depending on complexity, or not at all when there is a natural default. For example, default to accumulate() if combine() is not provided.

#### The rest of this issue

... reflects out thinking prior to the switch.

Sections: Design Goals, Minimal interface, Full interface, Overview, Key decisions, More.

# Design Goals

Our design is guided by the following goals:

* Allow simplicity: if the desired reduction is simple, the amount of code to describe it should be minimal, with the rest provided by the Chapel implementation. For a plus reduction, for example, it should suffice to specify just the identity element (zero) and the accumulation operation (addition).

* Support advanced reductions: for example, support the cases where the input type, accumulation type, and output type are different.

* Open question: do we support (a) reduction-specified synchronization, (b) a distinction between global vs. per-locale vs. per-task actions? Both features are desired to implement MapReduce-style word counting described [here](#issuecomment-393623009) and [here](#issuecomment-393955382). (a) is needed for a plus reduction where concurrent updates rely on atomic addition instead of a lock.

* Allow the following clients of the user-defined reduction:

  - a full reduction expression
  - a partial reduction expression
  - a reduce task/forall intent
  - reproduceable reduction results (*)
  - execution on GPUs

(*) For example, consider a plus reduction on floats. The result may depend on the order of the individual additions. The user may desire for this order to be the same from run to run.

* Allow the above operations to have good performance.

* As an example, avoid allocating the final result distinctly from the global accumulation state unless necessary. (Important when those are large arrays/data structures.)

# Minimal interface

Features:

* A new reduceOp is oblivious of its parent task.

* All synchronization concerns are delegated to the Chapel implementation if the initializers with 'parSafe' formal are not included.

* `dataType` can be used to indicate all of; inputType, accumType, outputType.

```chpl
record ReduceOp {    // user to choose the name

  // type fields or type procs
  type dataType // optional
  // any of these can be omitted if 'dataType' is to be used instead
  type inputType
  type accumType
  type outputType

  // How to create an instance.
  proc init(type inputType)

  // Creates an instance in a child task.
  // 'parentOp' is the instance in the parent task.
  // Optional. If provided, used instead of the above init().
  proc init(parentOp)

  // Optional. When provided, used instead of the corresponding
  // single-argument version.
  proc init(param parSafe, type inputType)
  proc init(param parSafe, parentOp)

  // The "zero" value for the reduction.
  proc identity()

  // Adds 'input' onto 'AS'.
  proc accumulate(ref AS, input)

  // Combines the child's AS with the parent's AS.
  // 'this' is the parent's reduceOp.
  // Synchronization is required when 'this' was created with parSafe==true.
  // TBD: should we allow dropping 'childOp' formal?
  proc combine(ref parentAS, childOp, childAS)

  // Produces the reductionn result given the global AS.
  // Optional. If not provided, the global AS is the reduction result.
  proc generate(ref AS)
}
```

# Full interface

```chpl
record ReduceOp {    // user to choose the name

  // fields or procs
  type inputType
  type accumType
  type outputType
  param parSafe

  // Creates the initial instance, aka "globalOp".
  proc type newGlobalOp(param parSafe, type inputType)

  // Optional. When provided, used for reduce intents only
  // instead of the other newGlobalOp() + initialAccumulate().
  proc type newGlobalOp(param parSafe, type inputType, outerVar)

  // Creates an instance in a child task.
  // 'this' is the instance in the parent task.
  proc newChildOp(param parSafe, parentAS)

  // Creates an instance in a child task.
  // 'this' is the instance in the parent task.
  // 'perLocale' is true when this child task is potentially
  // on a different locale than its parent.
  // Optional. When provided and this feature is supported,
  // is used instead of the other newChildOp().
  proc newChildOp(param parSafe, param perLocale, parentAS)

  // The "zero" value for the reduction.
  proc identity()

  // Optional. When provided, identity() is needed
  // only for partial reductions.
  // Returns a reference to the current task's accumulation state.
  // Which is to be arranged by ReduceOp, possibly inside the reduceOp.
  proc refToAccumState() ref

  // Adds 'input' onto 'AS'.
  // Synchronization is not required.
  proc accumulate(ref AS, input)

  // Accumulates the initial value of the outer variable.
  // Synchronization is not required.
  // For reduce intents only if newGlobalOp(..., outerVar) is not provided.
  // Optional. If nether initialAccumulate() nor newGlobalOp(..., outerVar) 
  // is provided, accumulate() is used.
  proc initialAccumulate(ref AS, outerVar)

  // Combines the child's AS with the parent's AS.
  // 'this' is the parent's reduceOp.
  // Synchronization is required when this.parSafe==true.
  proc combine(ref parentAS, ref childOp, ref childAS)

  // Produce the reduction result given the global AS.
  // Optional. If not provided, the global AS is the reduction result.
  proc generate(ref AS)
}
```

Prior to deinitializing AS, it will undergo either a combine() or a generate() (when provided).

# Overview

The interface works with two kinds of data: reduceOp and accumulation state (AS).

### reduceOp

A reduceOp is an instance of the ReduceOp record type (see below). It provides a set of reduction-specific methods for the Chapel implementation to call into. It may also provide synchronization, contain state, and more.

Its flavor may differ along these axes:

**parSafe** : When created for parSafe=true, its combine() method must work correctly in the case of concurrent combine() calls on the same parent reduceOp and AS.

**partial reductions** : When created for a partial reduction (TBD: how does it know that?), the state within a reduceOp instance must not be specific to a single accState instance. In other words, accumulate() and combine() calls on the same reduceOp may have different AS-es.

**globalOp** : The initial reduceOp created when executing a reduction or a reduce intent, colloquially the "globalOp", may have a different concrete type (and possibly a different generic type) than reduceOps created from it to serve the tasks spawned by the parallel iterator.

**per-locale vs. per-task** : We consider providing distinct ways for creating a per-locale vs. per-task reduceOp. When the parallel iterator spawns a task on another locale, that task would get a per-locale reduceOp, otherwise a per-task reduceOp. This feature may interact with the "globalOp" feature above.

**same AS** : The current interface provides a single ReduceOp.accumType type. This means that AS should have the same type - given by the accumType - regardless of the kind of the reduceOp that created it.

### AS - accumulation state

An AS is a variable that an individual input is "accumulated" onto. For example, for a sum-reduction over an array, each array element is added onto one of AS-es.

Each AS is local to a task. The Chapel implementation ensures that there are no concurrent accesses to a given AS.

The AS of each child task is "combined" into the AS of its parent task. At the end of the reduction, the top-most AS is optionally "generated" into the reduction result.

The reduction author chooses the type of AS. In a simple case it can be the type of an input element, ex. `real`. It can even be `void`. If so, the corresponding reduceOp needs to maintain the state to support accumulation, and partial reductions are not defined.

### ReduceOp

ReduceOp is the record type that defines the reduction to be performed. It does so by implementing the reduction interface that the Chapel implementation calls into.

Client chapel code, in a (full or partial) reduce expression or a reduce intent, requests this reduction by writing the name of the ReduceOp type or by supplying its instance. In the latter case the instance plays the role of the globalOp in the interface.

# Key decisions

* This design differs from #5470, and previously #5248, in these ways:

  * It provides two flavors: minimal interface and full interface.

  * It moves synchronization concerns when parSafe=true from the accumulation state to the reduction op. This is to support partial reductions and to make the accumulation state available to the loop body as the shadow variable free of synchronization concerns.

* ReduceOp is a record, not a class.

Rationale: avoids malloc+free in the common case
when class functionality is not needed and a record suffices.

* Accumulation state (AS) is outside the ReduceOp record.
The AS variables are managed by the compiler.
The initial value for AS is given by ReduceOp.identity().

The alternative is to embed AS in the ReduceOp record.
If so, the compiler would access AS by creating, for example:
`ref AS = currentReduceOp.refToAccumState();` .

In both cases, AS is what the reduce-intent shadow variable
represents in the forall loop body. It does not include any
support for synchronization. Background: synchronization is needed
to avoid data races when multiple child tasks may be combine()-ing
their results into the parent task's AS.

Rationale: "AS outside ReduceOp" simplifies the setup for partial
reductions. For example, if AS is `real`, it is easier to initialize
and bulk-transfer an array of reals than an array of records
that contain a single real field.

The downsides of this choice are:
- More arguments for the interface functions. Because now we need
to pass the reduce op and the AS separately.
- Perhaps a loss of generality. The initial value given by identity()
does not know about the parent ReduceOp and the parent AS.
Also, initialization and deinitialization of the AS and the reduce op
are forced to occur separately, ex. in two separate deinit() methods
instead of one deinit().

If needed in the future, we can add support for the "AS is in ReduceOp"
style, for example, by detecting whether ReduceOp.refToAccumState()
is available.

Also if needed in the future, within the "AS separate from ReduceOp"
setup, we can add support for an alternative to identity()
that accepts the parent ReduceOp/AS or the outer variable, as in #5470.

* Allow the optimization where the outer variable and the global AS
are the same variable. This requires that AS type and the output type
are the same. If so, the initialization of globalAS and the call
to initialAccumulate should be skipped.

* ReduceOp is to support two modes: with synchronization and without
synchronization.

The first mode is for use with full reductions and
reduce intents. ReduceOp must include the needed state.

The second mode is for partial reductions. There, a single ReduceOp
may be shared among multiple AS-s performing independent full reductions.
Chapel implementation will provide synchronization outside ReduceOp.

# More

We can provide a helper record in the modules:

```chpl
  record ReduceLock {
    private var l: atomicbool;
    proc lock() { ... } // see ChapelReduce.chpl
    proc unlock() { l.clear(); }
  }
```

So the lock+unlock requirements are satisfied simply by declaring a field in ReduceOp:

```chpl
  forwarding var locker: if parSafe then ReduceLock else void;  // defines lock(), unlock()
```

**Comment by mppf** [comment]
> Perhaps a loss of generality. The initial value given by identity() does not know about the parent ReduceOp and the parent AS.

Since `identity` is called as a method on ReduceOp, and ReduceOp is constructed either with init (for global state) or with newLocalOp (for local state), couldn't the AccumType be a class/record that contains some kind of pointer to the local state and/or the global state?

I think it's really important to make sure that the case of global accumulation state being a distributed associative array will work. In that event, we'd want local accumulation state to be something else in practice. Now, there could be one AccumType type that contains a pointer to either distributed accumulation state or local accumulation state. Or, it might be interesting to consider, what would the interface look like if local accumulation state and global accumulation state were actually different types?

I wonder about that partly because it seems to me to be related to the `parSafe` and `combine` elements of the interface. If we had two different `combine` calls, one for local combining and one for global combining, what would the interface look like? Would everything you want to see with partial reductions still work?

**Comment by vasslitvinov** [comment]
These questions are still open in my mind:

* Should we allow optional future extensions? For example, what if we find a compelling case to keep AS inside the ReduceOp record and have the shadow variable within the forall loop body to be a `ref` to that AS, to avoid excessive indirection. The compiler could support that by checking whether there is `proc ReduceOp.refToAccumState()` and use it when available instead of identity(). identity() would still be required to support partial reductions.

* Do we want our ReduceOp interface to be more of the style "I am defining the reduction's 0 and +" or "I am defining what happens when a new task starts". The latter would suggest, for example, the following methods:

```chapel
// a factory method instead of ReduceOp.init()
proc type ReduceOp.newGlobalAccState(initUserValue, param parSafe)

// instead of identity()
proc ReduceOp.newLocalAccState(parentAS)
```

Speaking of indirection from the shadow variable to the ReduceOp instance mentioned above. The ReduceOp author could make the shadow variable be nothing, i.e. have the `void` type. All accumulation state would be embedded in the ReduceOp record instead. This would not support partial reductions and would make `reduce=` the only useful operation on the shadow variable. However, this way there would not be any indirection.

**Comment by bradcray** [comment]
* the references to "parent" and "child" reduceOps doesn't really make sense to me.  What do these refer to and why are they needed?  Specifically, what is the role of `newLocalOp()`?

* it seems unfortunate to me that the reduction author would ever have to worry about synchronization rather than having the external framework implementing the reduction take care of it.  Specifically, I'd be happy if `parSafe` could be made to go away and each reduceOp operations could assume that they had exclusive access to the values they were being asked to act on.  What do we lose in that approach?

* do you imagine an opportunity to use reflection for things like "if no identity() routine is provided, the default value of the accumulation type is the identity" or "if no generate() routine is provided, the accumulation state is also the output type?"  These seem like they could help support common cases and make things slightly more efficient  (I'm particularly interested in the case where input type == accumulation type == output type not resulting in a bunch of needless processing when possible).

**Comment by mppf** [comment]
> * it seems unfortunate to me that the reduction author would ever have to worry about synchronization rather than having the external framework implementing the reduction take care of it.  Specifically, I'd be happy if `parSafe` could be made to go away and each reduceOp operations could assume that they had exclusive access to the values they were being asked to act on.  What do we lose in that approach?

Consider the case of accumulation state (and result of reduction) being a distributed array. This might come up in say making a distributed histogram / word count / set. In that event, we *really* don't want to lock the entire distributed array when processing updates to it. We just want to lock the portion we are updating at the time we are updating it. I.e. we don't want to have a global lock across all locales for the distributed array - just local locks for the portion on each locale. (distributed-associative can do this sort of thing by implementing += or the bulk-domain-add interface).

**Comment by bradcray** [comment]
> we really don't want to lock the entire distributed array when processing updates to it.

Sure, but why would having the reduction framework implement the synchronization suggest that we'd have to do something as naive as locking the entire distributed array?  In the event of full reductions, the combine steps are typically done on a task-pair basis as tasks are destroyed, not over the entire collection.  In the event of partial reductions, the domain map is involved in specifying the reduction, so would know about the distribution of the array and could do the right thing.

**Comment by bradcray** [comment]
Let me amend that previous response, hold on.

**Comment by mppf** [comment]
>  This suggests that for a large, distributed reduction, we're potentially/likely going to create numLocales * numPUs() copies of AccumType. It seems unlikely that we'd ever want that type to be a distributed array for scalability purposes.

> For this case, what seems more likely to me is that we'd want each AccumType to be some local set of data to be put into a global distributed array, where perhaps the combine() and/or generate() steps might put the local contents into the global resulting output type.

Exactly. That's why I like the idea in the proposal to allow the reduction to have a different accumulation state type for local vs global state.

> To make this more concrete, can you give a motivating example?

If we think about how to implement Map/Reduce (a-la Hadoop or Spark) in Chapel, what we need is substantially similar to the needs of existing reductions (especially reductions that work across many locales, say a reduction over a distributed array). The difference is just that the result of a Hadoop Reduce is usually a large aggregate object (say a giant map of keys to values). That's why I'm talking about DistributedAssociative being the result of a reduction. You might imagine using such a Map/Reduce job to create a distributed set of words in some data, or count those words, or ...

I've thought a bit about how to provide a Map/Reduce like library that offers similar performance and I think it should be a combination of API functions that seem like Map/Reduce and also an implementation that is efficient and builds upon other Chapel code. Building it upon the custom reductions interface would be a great way to do that & would save quite a bit of work in re-doing many related things. At the same time, it might lead to some interesting features (such as using reduce intents in a forall loop for a Map/Reduce style reduction) that we wouldn't otherwise be able to explore.

> But I'm still not convinced that this is a case that the reduction framework—at least as currently/historically envisioned—might be expected to handle.

I think we're re-envisioning it, to some degree, right now in this discussion. I agree it wasn't a case it was originally intended to handle and I also agree we could decide it shouldn't be handled by it.

However, the variations on the design that support it do not seem so far off from what we might otherwise do.

**Comment by mppf** [comment]
Here is a sketch of what MapReduce might look like in Chapel. The starting example for MapReduce is typically word count, which computes a histogram - for every word, what is the number of times that word occurred?

What are the basic types in MapReduce? I'll call it a `dict` for now (just to use a unique term) but it's a mapping from string key to some value type. The value type would be integer for our word count example. During the reduction phase of a MapReduce, the goal would be to combine counts for the same terms.

``` chapel
// Suppose Input is a distributed array of strings (words)
// suppose dict(string,int) is a mapping from string words to their counts
record Value {
  var x:int;
  proc combine(other:int) {
    x += other;
  }
}
var result : dict(string, Value)
forall word in Input with (reduce result) {
  dictCombine[word] += 1;
  // another idea: dictCombine += (word, 1);
  // or result reduce= (word, 1);
}
```

and that would be it. Under the hood, the reductions interface and the `dict` type would work together to:
 * create a local-to-each-task word count
 * combine task word counts to the global `dict` instance in a parallel-safe way

To be scalable, I'd imagine `dict` would be implemented with distribute associative arrays.

What would a dict's ReduceOp look like?
 * InputType = void ?
 * AccumType = dict
 * (local accum type = non-distributed dict?)
 * parSafe = false
 * proc init(type InputType, param parSafe) creates a distributed array
 * newLocalOp creates a local array
 * identity is an empty (local, presumably?) array
 * accumulate updates a local array without locking
 * initialAccumulate is not needed
 * combine -- in bulk, move accumulated data to the locale owning that data, and do so under a lock for that locale only (not a global lock)
 * generate -- doesn't do anything in particular for this example

**Comment by vasslitvinov** [comment]
One thing that jumps at me is that the ReduceOp author may want to distinguish per-locale state vs. per-task state. In the spirit of per-locale vs. per-task task-private variables.

**Comment by vasslitvinov** [comment]
[This summarizes discussions between Brad and Vass.]

## Why do we want the reduction author to be concerned with synchronization?

Here, "synchronization" means prevention of data races when multiple child tasks pass their accumulation results to the parent task.

#### Two design directions

We have considered these two design directions:

"allow parSafe" : The reduction author may choose not to cater to synchronization concerns, delegating them to the compiler. Do so ex. by not defining certain interface methods or their flavors. Or the author may support two cases: the compiler creates a reduction op that does its own synchronization (parSafe=true), or a reduction op that leaves it to the compiler (parSafe=false).

"simple" : The compiler / the Chapel implementation always address synchronization concerns. The reduction author cannot specify how to synchronize.

Since the "allow parSafe" option is more complex, both for the author and for the Chapel implementation, why would we want to choose it?

#### Use atomic operations for synchronization

When an atomic operation is available to combine values, for example addition of floats, it seems appealing to allow the recuction author to do so instead of compiler-provided synchronization.

However, is this really beneficial, compared, for example, to GPU-style synchronization (see below) ? It is unclear that this will result in noticeably better performance. Without better performance, there is no reason to support this.

#### Avoid compiler-added synchronization.

For the MapReduce-style word counting example described [here](#issuecomment-393623009) and [here](#issuecomment-393955382), the top-level combine operation incorporates the word counts computed on a single locale into the global distributed dictionary.

Here, we need to avoid a global lock that the compiler may add to isolate the updates from separate locales. Instead, we want to perform global-lock-free updates concurrently from all locales, relying on lock-free update functionality hopefully provided by the dictionary itself.

In this case, GPU-style synchronization is not appropriate either, due to the large size of child (i.e. per-locale) data.

However, is Chapel's reduce framework the right one in this case? How can we implement it by other means, to avoid causing UDRI design complexity?

#### Other cases when author wants to control synchronization?

#### GPU-style synchronization

This is a counter-argument to the benefits of author-supplied synchronization.

In the currently-implemented reduction framework, we need to lock the parent's accumulation state when combining with the child's accumulation state. This eliminates the race on the accumulation state when multiple children may be requesting it at the same time.

"GPU-style synchronization" is when instead, the parent allocates a separate accumulate-state slot for each child. Each child computes its partial results into its slot. When all children are finished, the parent traverses all children's slots and combines them together.

This avoids the race without any locking. We call it "GPU-style" because it is typically used for GPUs when locking/synchronization is not available.

This adds o(#children) storage and combine operations to the parent. In cases like numeric addition this overhead is negligible. It may also be small compared to the time/memory used by the child tasks. How to detect the cases where this scheme is not appropriate because it degrades performance and/or requires too much additional memory?

One advantage of this approach is seen with partial reductions. When the partial results of child tasks do not overlap, the parent needs to allocate only a single array of partial results. Each task updates its portion of that array. Post-processing in the parent task is not needed at all. Challenge: how to detect this situation?

Implementation concerns:

* Need to add the allocation of the array of child tasks' accumulation states and pass the AS reference to each task. This is a simple case.

* When the child task is remote, it still needs to allocate its own AS. At the end, copy the local AS into the child task's slot in the parent task.

* When the child tasks are spawned locally over NUMA domains, follow the remote case, except probably there is no need for the final copy.

* When the number of child tasks is not known, the parent task needs to allocate, say, a linked list instead of an array.

**Comment by mppf** [comment]
Responding to the above discussion, I want to bring up 2 things:

1. Regarding the map-reduce style computation, I suspect that whether or not this ends up using a reduction, it will end up using something reduction-like. So I suspect the compiler work will be the same whether we do the "simple" reduction interface or not. This is more of a branch-prediction on my part, since I don't think we yet know what is "right way" to write these computations in Chapel.
2. Regarding the GPU-style synchronization, I view the desire to possibly use this alternative synchronization strategy as an argument *for* reductions that can specify their own synchronization. That way, this synchronization strategy can be implemented and explored without needing to modify the compiler. I think being able to do this in module code would be a real benefit (multi-resolution design and all that).

**Comment by mppf** [comment]
Regarding using reductions for the map-reduce style - in conversation with @vasslitvinov he pointed out that the same pattern can probably be achieved with task-private-variables, where each task-private-variable would include a destructor that sends any accumulated updates to the global state. That should allow the user-defined-reduction interface design to continue regardless of what we do for map-reduce style computation.

**Comment by vasslitvinov** [comment]
Switched to a simple interface in #9879.
