### ISSUE TITLE
Spike: What scripts could we provide to users to build their own matrix of configurations?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#9551]
As a system administrator, I'd like to have some support for specifying a matrix of Chapel configurations (e.g., CHPL_COMM=none, ugni, gasnet/aries vs. CHPL_TASKS=qthreads|fifo vs. CHPL_TARGET_COMPILER=...) and having all those configurations be built in one fell swoop rather than doing that scripting myself.

**Comment by bradcray** [comment]
I believe that @thomasvandoren did some groundwork in this area, but don't know that it ever got completed, so I'd imagine this spike being to learn about what we have and what would need to be done to make it user-ready.

**Comment by ben-albrecht** [comment]
> I believe that @thomasvandoren did some groundwork in this area, but don't know that it ever got completed

It is checked in as [`build_configs.py`](https://github.com/chapel-lang/chapel/blob/master/util/build_configs.py).

I wrote something simpler for building the AWS image configurations, but the above looks much further along. I'd start from that.

**Comment by awallace-cray** [comment]
2018-05-16 10:00 : 
* util/build_configs.py is a very general-purpose script to run "makes" for any chosen matrix of CHPL env settings.  Running those "makes" is all it does- there's no help at all for downloading sources, packaging the resulting binaries, or miscellaeous bits like man pages or Python venv. The user can easily select which CHPL env vars to vary (ie, assign values to) and what those values are, choosing from a fixed inventory built-into the script - and the script will grind out the resulting matrix of "makes".  That built-in inventory of available CHPL env settings is a few years old now, but the Python coding makes it easy to update this.  Another thing missing from build_configs.py, is any provision for some CHPL env settings depending on other ones. For example, the Cray module build starts out as a general config matrix like this, but then different things happen to other env settings depending whether COMM is ugni or gasnet.  
* The other approach would be to adapt some of the shell scripts Jenkins uses to do the Cray module build.  This idea would start with mockJenkins.bash, common.bash, and chapel.bash from chapel-code/build/cray-module, throw out a lot of it, and end up with a much-simplified script to run an end-to-end build. Starting from a release tarball, and ending up with a big tar.gz file, which you could install whereever you wanted by simply un-tarring it.  Just how much scripting we could throw out would depend on whether the user wants to support multiple compilers in the same installation.  If one COMPILER and one COMM type per installation was good enough, it would probably eliminate loading and swapping other Cray modules between make passes - making this proposition a very easy one. OTOH, if the target user wasn't happy without that complexity, or if they needed the package to be an actual RPM, then this approach still works- we just don't get to throw out as much of the existing scripts.

**Comment by ben-albrecht** [comment]
> there's no help at all for downloading sources, packaging the resulting binaries, or miscellaeous bits like man pages or Python venv. 

I assumed this would be a tool a sys-admin could use once they have a Chapel release on their machine already. Were you guys (@bradcray && @awallace-cray) thinking of a general installation script starting from nothing, like [rustup](https://github.com/rust-lang-nursery/rustup.rs) for Rust?

Functionality like installing man pages and building python venv should be pretty easy to add to the existing script.

Separately, I wonder what compatibility issues we need to account for. For example, if we pursue a python script for this, will we need to support python 2.6 for sys admins on SLES 11 / CLE 5 machines?

**Comment by bradcray** [comment]
Thanks for the investigation here.  To address some of the comments and implied questions:

* I don't think there's a need to download the sources per se.  I.e., it's OK with me to assume that the sources are already downloaded and somewhere convenient; this script could even reside within the release tarball where a user could invoke it to tell it to "build itself."  Maybe ultimately, it'd also be nice to have an option to download then run, but for starters I don't think that's necessary.

* I don't think building an RPM is as important as building a usable installation.  I.e., my model is that the goal would be to generate a working version of $CHPL_HOME, not necessarily a bundled / packaged version of the same as an RPM or .tar.gz.

* I do think we ultimately would like something that works well on Crays (say, uses CHPL_COMM=ugni) as well as on standalone systems.  At present, I'm more interested in the Cray case.

* I agree with Ben that, if we started with the `build_configs.py` script, it shouldn't be hard to teach it to build the man page, though the compatibility problems could be an issue.  Specifically, I think we should assume that this might be run from older OSes like SLES 11 / CLE 5.

* If we start with the Jenkins scripts, the implied goal would be that we'd want to get them into sufficient shape that they could stand alone outside of Jenkins and be accessible (physically and intellectually) to an end-user or sysadmin.

**Comment by awallace-cray** [comment]
2018-06-11 12:30 : re-reviewed this info
