### ISSUE TITLE
Convert DateTime module to use error handling

### ISSUE THREAD

**Issue by benjamin-robbins** [chapel-lang/chapel#9552]
Convert halts in DateTime module to throw'ing functions (where appropriate)

**Comment by ronawho** [comment]
https://github.com/chapel-lang/chapel/pull/9832 removed or converted some halts that are no longer necessary. The harder part of actually converting some cases to error-handling remains.

**Comment by ronawho** [comment]
https://github.com/chapel-lang/chapel/pull/9944 does most of the conversion. There are some remaining halts, but what we do with those depends on https://github.com/chapel-lang/chapel/issues/9941, so I think this is done for now.
