### ISSUE TITLE
default-init not working for record with generic field

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#9568]
The following program doesn't compile but it should:

``` chapel
pragma "use default init"
record R {
  var i:integral;
}

proc test() {
  var rec:R(int);
  writeln(rec.type:string, " ", rec);
}
test();
```

**Associated Future Test(s):**
test/classes/ferguson/generic-field/generic-field-integral-not-inited-record.chpl

**Comment by bradcray** [comment]
@mppf: This seems more related to the initializers epic than to the delete-free epic to me.  Am I missing something?  Thanks.

**Comment by mppf** [comment]
@bradcray - it's related in that a field like `unmanaged` counts as generic. However we can put it in both epics, which I've done. If you think it'll help you to remove it from the delete-free epic, feel free to do so.

**Comment by bradcray** [comment]
Tagging @benharsh due to the link to initializers.

**Comment by benharsh** [comment]
@mppf : There are a couple of other futures in the same directory related to this bug that I have questions about.

1) generic-field-record-not-inited2.chpl

I think this test is working correctly. The type of ``f`` should be ``GenericRecord(GenericRecord(int))`` right? The .good file suggests it should be ``GenericRecord(int)``.

2) generic-field-record-not-inited3.chpl

I think this test is incorrectly written. My plan is to have _defaultOf generation treat a field with a generic type expr the same as if it had no type expr. In the no-type case the compiler will create a temporary based on the instantiated type and pass that temporary to the initializer:

```chpl

record R {
  var x;

  proc init(type t) {
    var temp : t;
    this.x = temp;
  }
}

var r : R(int);
// var temp : int;
// init(r, temp); // no matching initializer!
```

If the user-defined initializer only accepts a type, then this program will fail.

**Comment by mppf** [comment]
> generic-field-record-not-inited2.chpl

> I think this test is working correctly. The type of f should be GenericRecord(GenericRecord(int)) right? The .good file suggests it should be GenericRecord(int).

OK, that seems right.

> generic-field-record-not-inited3.chpl

Your description of what this test needs seems plausible but unfamiliar to me. Do we document anywhere what initializer one needs to provide to get defaultOf-type expressions working for generic records?

**Comment by benharsh** [comment]
I don't think we document this anywhere.

I think my work on initializing from instantiations may result in a document describing these rules.
