### ISSUE TITLE
Sparse Matrix Product Hanging at Scale

### ISSUE THREAD

**Issue by Tshimanga** [chapel-lang/chapel#9574]
Steps to Reproduce:
````
var A = ["any 10^6 by 10^6 sparse array with 10^6 or 10^7 nonzeros"]; //3.3mil nonzeros in my case

var AT = transpose(A);

var aat = A.plus(AT);  // almost 7mil nonzeros

var aat2 = dot(aat,aat);  // this dot product never seems to terminate
````

At this time, I haven't been able to compute `dot(A,A)` either.

**Comment by ben-albrecht** [comment]
@Tshimanga - do you consider this different from https://github.com/chapel-lang/chapel/issues/9445 ?

**Comment by ben-albrecht** [comment]
Ah, OK. I'm going to close as duplicate then - we'll continue in that issue.
