### ISSUE TITLE
unexpected behavior of DefaultRectangularDom leader iterator

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#9575]
When compiling under NUMA and executing in a situation where there is only 1 sublocale, the DefaultRectangularDom standalone iterator generates a normal(*) number of tasks. The leader iterator, however, generates only a single task. This is unexpected and we should probably fix it.

(*) For example, when running with --dataParTasksPerLocale=3 and there are 12 indices in the domain, the standalone iterator gets numChunks=3 and its coforall spawns 3 tasks.

Cf. the leader iterator caps numChunks with the number of sublocales, so it ends up being 1. The "if numChunks == 1" branch does not bother with a coforall, so the current task runs the entire iteration space.

Vass observes:

* Under NUMA when executing in a situation where there is only 1 sublocale, do we want our code (for example, the parallel iterators) to behave the same way as they do under FLAT? If so, we could simply replace the check `numSublocs != 0` in the DR leader iterator with `numSublocs > 1` .

* The DR domain standalone iterator is numa-unaware. Do we want to make it numa-aware? Or do we want to make the leader iterator numa-unaware?

**Comment by cassella** [comment]
I gather the NUMA locale model has been deprecated.  Is this still an issue, or an issue under other circumstances?

**Comment by vasslitvinov** [comment]
@ronawho @stonea is this issue still relevant?

**Comment by bradcray** [comment]
I'd tend to agree that without the NUMA locale model (which we don't have any intention of resurrecting), this issue probably isn't relevant anymore.
