### ISSUE TITLE
Improve performance of elegant BlockDist sliced assignment

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#9593]
PR #9592 introduced a comm-count performance test demonstrating remarkably poor performance for simple assignment between slices of a Block-distributed array. The slices involved are each living on only one locale, so we should be able to perform each transfer with a handful of GETs or PUTs. However, we instead see hundreds/thousands of GETs/PUTs and a large number of on-statements.

The BlockDist bulk-transfer implementation has not been closely examined in quite some time, and clearly does some unnecessary remote-task creation. For example, the implementation always performs a coforall+on on every locale over which the array is distributed.

These are the tasks to complete here:
- [x] create time-based performance test/graph instead of raw comm counts
- [x] enable bulk-transfer optimization for Block by default (do not rely on useBulkTransferDist param)
- [ ] reduce overhead of slicing block-distributed arrays **or** avoid true/deep slicing for assignment between slices.

**Comment by benharsh** [comment]
While attempting to enable Block's bulk-transfer optimization, I observed a variety of errors for strided, sliced, reindex, and rank-changed arrays. I think the optimization needs further work in order to correctly handle these cases.

While investigating the exchange comm-counts test, I observed that the majority of comm-counts came from slicing the Block-distributed arrays. I don't think we can make a dent in the performance issues here without first addressing slicing overhead.

**Comment by bradcray** [comment]
Here are some fun stats from some exploratory branches that I've been working on recently.  The three things that I'm comparing here are:
* master
* my branch which strives to not involve locales that don't own part of a distributed domain/array unnecessarily when slicing (slice-ownership), and 
* my branch which creates slices of distributed arrays locally and then propagates them to other locales lazily (lazy r.v.f. slice).

exchange-elegant.dat:
```
# Date          GETS:   PUTS:   ONS:
01/14/19        121681  108     689 # master
01/14/19        121660  105     694
01/14/19        121653  102     697
01/14/19        121670  106     688
01/14/19        121684  108     683

01/14/19        120459  48      391 # slice-ownership
01/14/19        120456  47      382
01/14/19        120459  48      400
01/14/19        120468  48      410
01/14/19        120463  48      407

01/14/19        120183  4       54  # lazy r.v.f. slice
01/14/19        120180  6       49
01/14/19        120131  2       60
01/14/19        120198  3       58
01/14/19        120136  0       54
```

exchange-destLocal.dat:
```
# Date          GETS:   PUTS:   ONS:
01/14/19        120853  51      303 # master
01/14/19        120859  52      307
01/14/19        120824  48      298
01/14/19        120873  54      312
01/14/19        120850  51      311

01/14/19        120350  30      221 # slice-ownership
01/14/19        120346  30      214
01/14/19        120334  29      229
01/14/19        120334  29      219
01/14/19        120347  30      215

01/14/19        120155  1       9   # lazy r.v.f. slice
01/14/19        120156  4       10
01/14/19        120187  4       13
01/14/19        120118  0       4
01/14/19        120131  2       9
```

(my branches don't do anything interesting for the "both local" case).

**Comment by bradcray** [comment]
At the suggestion of @ronawho / @benharsh, I tried using the `useBulkTransferDist` flag with the above branches and got improvesments for the destLocal case for the slice-ownership branch:

```
01/15/19        517     42      291 # slice-ownership +	-suseBulkTransferDist
01/15/19        511     41      294
01/15/19        490     40      285
01/15/19        516     42      302
01/15/19        513     42      298
```

the others, not so much.

**Comment by benharsh** [comment]
PR #12797 will enable bulk-transfer for BlockDist by default.

**Comment by benharsh** [comment]
I think this issue is rather out of date at this point, and there has been more work in this area since the last update, so I will close.
