### ISSUE TITLE
Support param iteration over a heterogeneous tuple

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#9607]
### Summary of Problem

While working with tuples today, it occurred to me that it could be nice to support param iteration over heterogeneous tuples.  That is:

```chapel
for param v in (1, 2.3, "four") do
  writeln(v.type:string);
```

would essentially write out

```chpl
int
real
string
```

being equivalent to:

```chpl
{
  param v = 1;
  writeln(v);
}
{
  param v = 2.3;
  writeln(v);
}
{
  param v = "four";
  writeln(v);
}
```

This seems like a much nicer / more productive alternative to the current approach:

```chapel
const tup = (1 2.3, "four");
for param i in 1..tup.size do
  writeln(tup(i).type:string);
```

### Steps to Reproduce
**Associated Future Test(s):**
[`test/types/tuple/tupleParamLoop.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/types/tuple/tupleParamLoop.chpl
          ) #9604

### Configuration Information

- Output of `chpl --version`: `chpl version 1.18.0 pre-release (2bcd25f)`

**Comment by ben-albrecht** [comment]
Why stop at params? Can we eventually support general iteration over heterogenous tuples?

**Comment by ben-albrecht** [comment]
@bradcray - Thanks for the details. I forgot that bit.

Is there a similar challenge preventing us from supporting runtime-indexing?

```chpl
var t = (1, 2.3, "four");

for i in 1..3 {
  writeln(t[i]);
}
```

**Comment by bradcray** [comment]
That's right.  Imagine that this is going to be translated into a C loop like:

```c
for (i=1; i<=3; i++) {
  writeSomeType(t[i]);
}
```

The problem is that there's no `writeSomeType()` routine in C that can simultaneously handle an int, a real, and a string.

**Comment by ian-bertolacci** [comment]
Would this be a motivating case for implicitly converting the loop `for v in (1, 2.3, "four") ...` into it's `param` equivalent? (`for param v in (1, 2.3, "four") ...`)

Or is implicitly making things `param` a bad idea?

**Comment by bradcray** [comment]
I'm closing this issue in favor of #14929.  I think @ben-albrecht and @ian-bertolacci were right on the money above and that I was the one who was too stuck in traditional thinking.  See the new issue for details.
