### ISSUE TITLE
Internal error using List 

### ISSUE THREAD

**Issue by TomsyPaul** [chapel-lang/chapel#9628]
Hi all,

I had been working on Chapel 1.14. Recently I decided to switch to latest version. I used git clone and am working on the latest Chapel. I face these problems now.

1. I am creating a module, say M. In this I use some List operations. I have been including `use List;` in modules/internal/ChapelStandard.chpl and it was okay in 1.14. But now I get the error that  `unresolved call 'list(type 2*2*int(64))'`

2. When I include `use List;`, to overcome the problem,

```chpl
module M {
  use List; ....
```

it gives an Internal Error
```
chpl examples/primers/tomsy/sample.chpl --fast -o examples/primers/tomsy/sample.out
examples/primers/tomsy/sample.chpl:22: internal error: IMP0087 chpl version 1.18.0 pre-release (3b5bc1d)
```

Please help!!

**Comment by daviditen** [comment]
Hi @TomsyPaul, is it possible to provide some example code that will cause the errors you're seeing?  I've been unable to reproduce the problems based just on what you've said so far.

**Comment by TomsyPaul** [comment]
I am looking into internal error, and shall update in a couple of days. 

Meanwhile, the other issue may be due to some recent changes in handling Internal and Standard modules. List is in modules/standard. I observe that if I keep "M", my module (M.chpl, containing module M{....}) inside modules/standard, it is sufficient to add "use List;" to modules/internal/ChapelStandard.chpl. But if "M" is in modules/internal, it needs an explicit "use List;" inside M.chpl.

**Comment by daviditen** [comment]
In most cases you probably don't want to modify anything in modules/standard or modules/internal.  These directories are treated specially by the Chapel compiler in a few ways.  For your own codes, it would usually be best to create your own directory in some other location, and keep your code there.

The reason the `M` module needs to `use List;` after modifying `ChapelStandard.chpl` when it is in `modules/internal` but not when it is in `modules/standard` is that the standard modules automatically use the `ChapelStandard` module while internal modules do not (one of the ways these directories are treated specially).

Instead of adding `use List;` to `modules/internal/ChapelStandard.chpl` it's best to just add it directly to your `M` module, which now resides somewhere outside of `modules/standard` and `modules/internal`.

**Comment by TomsyPaul** [comment]
Hi. It is clear now, except for the question why I could access the List module in version 1.14, from module M, by adding it in ChapelStandard and keeping M as internal?

**Comment by TomsyPaul** [comment]
Hi @daviditen, by the way, my work is some modifications to the Chapel compiler itself. In that case, isn't it better to add my module as internal? And if so, what is the best way of 'using' List?

**Comment by lydia-duncan** [comment]
@TomsyPaul - I seem to recall us doing some clean up on which modules were automatically included and which were not, probably around that time.  I suspect it worked in 1.14 because some module was already including List that early.

**Comment by daviditen** [comment]
> Hi @daviditen, by the way, my work is some modifications to the Chapel compiler itself. In that case, isn't it better to add my module as internal? And if so, what is the best way of 'using' List?

I hadn't realized that you were working on Chapel internals.  In that case it may be appropriate to put your new code into an internal module.  The ideal way to use `List` is to add `use List;` to your module.

I don't know the details of how you're using `List`, but the `List` module hasn't received much implementation effort recently.  [Array vector operations](https://chapel-lang.org/docs/master/primers/arrayVectorOps.html) may be a better match for you.

**Comment by TomsyPaul** [comment]
Hi all.
I could figure out the cause of the Internal Error, it was an assert inimplementForallIntents2.cpp, in compiler/resolution. Since this file was not there in previous version, I was ignorant of this assertion. List package has nothing to do with the error.

Thanks for your quick assistance.

By the way, can't we give a better name to implementForallIntents2.cpp?
