### ISSUE TITLE
copyFile does not produce exact copy in some cases

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#9629]
### Summary of Problem

When copying a gzipped file with `FileSystem.copyFile()`, the copy is not exact, resulting in a malformed gzip file that can no longer be unzipped.

### Steps to Reproduce

**Source Code:**

Here is a standalone reproducer:

```chapel
use FileSystem;

runCommand('touch a.txt');
runCommand('gzip a.txt');

copyFile('a.txt.gz', 'a2.txt.gz');
runCommand('cp a.txt.gz a3.txt.gz');

// Checking results of copy:

writeln('copyFile diff:');
runCommand('diff a.txt.gz a2.txt.gz');
// Binary files a.txt.gz and a2.txt.gz differ

writeln('cp diff:');
runCommand('diff a.txt.gz a3.txt.gz');
// (No output, as expected)

proc runCommand(cmd) {
  use Spawn;

  var args = cmd.split();
  var sub = spawn(args);
  sub.communicate();
}
```

### Configuration Information

- Output of `chpl --version`: `chpl version 1.18.0 pre-release (91d47ac)`

**Comment by ben-albrecht** [comment]
@mppf - this is the issue I talked to you about earlier today.

**Comment by cassella** [comment]
If the last line in the file doesn't have a newline, ``readline()``
will return the data and count into its `arg[]` and `numRead`, and
return false.

```chapel
proc channel.readline(arg: [] uint(8), out numRead : int, start = arg.domain.low,
                      amount = arg.domain.high - start + 1) : bool throws
...
   while i <= maxIdx {
      got = qio_channel_read_byte(false, this._channel_internal);
      arg[i] = got:uint(8);
      i += 1;
      if got < 0 || got == newLineChar then break;
    }
    numRead = i - start;
    if got < 0 then err = (-got):syserr;
    got_copy = got;
...
  if !err && got_copy != 0 {
    return true;
  } else if err == EEOF || got_copy == 0 {
    return false;

```

```chapel
proc copyFile(src: string, dest: string) throws {
...
  while (try srcChnl.readline(line, numRead=numRead)) {
    try destChnl.write(line[0..#numRead]);
```

When `readline()` returns false, `copyFile()` will exit the loop
without writing the data that last call to `readline()` returned.

You can see this by preparing a file

`(echo hello; echo -n world) > a.txt`

and using `copyFile()` to copy that file.


I think either `copyFile()` should expect this behavior from
`readline()`, or `readline()` should return true when it read some
data, even if it later hit an error.  FWIW, I think the latter
behavior is how C's `getline()` works.  (If the file's at EOF, it'll
still be there when the caller calls again.)

Or `copyFile()` can use something besides `readline()` -- I don't see
that it has any need to read or write a line at a time, or inspect the
data for newlines.

**Comment by mppf** [comment]
> Or copyFile() can use something besides readline() -- I don't see
that it has any need to read or write a line at a time, or inspect the
data for newlines.

+1
