### ISSUE TITLE
Internal error for illegal runtime-dependent tuple

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#9630]
### Summary of Problem

Defining a tuple based on a runtime value, such as an array size, generates an internal error. This could use a more helpful error message.

### Steps to Reproduce

**Source Code:**

```chapel
var A: [1..2] int;
var tup: A.size*int;
```
Compilation output with `--devel`:

```
internalError.chpl:2: internal error: assertion error [tuples.cpp:1181]
Note: This source location is a guess.
```

### Configuration Information

- Output of `chpl --version`: `chpl version 1.18.0 pre-release (91d47ac)`

**Comment by cassella** [comment]
This now reports
```
foo.chpl:2: error: tuple size must be known at compile-time
```

Is that better?

The only test whose .good has this error is `test/trivial/shannon/condReturn2.chpl`.  But that has had a clean error since 2007.   So maybe there should be a separate test to lock in this behavior, in whatever manner distinguishes it from that test?

**Comment by ben-albrecht** [comment]
> So maybe there should be a separate test to lock in this behavior, in whatever manner distinguishes it from that test?

Agreed. Thanks for checking this @cassella.

**Comment by ben-albrecht** [comment]
I'll close this issue with the PR to add that test.
