### ISSUE TITLE
hwloc failing to build on Ubuntu 18.04

### ISSUE THREAD

**Issue by marcoscleison** [chapel-lang/chapel#9643]
### Summary of Problem

I pulled from master branch today and try to recompile it. But I could not recompile it because it is giving error related to something with libhwloc. I made `make clobber` but it does not compiles.

### Steps to Reproduce
```bash
make clobber
make 


checking for high resolution timer type... clock_gettime
checking hwloc.h usability... yes
checking hwloc.h presence... yes
checking for hwloc.h... yes
checking for library containing hwloc_topology_init... no
configure: error: Specified topology library (hwloc) does not work.
Makefile:114: recipe for target 'qthread-config' failed
make[4]: *** [qthread-config] Error 1



```

### Configuration Information

Commit d13e11a2b9cd1540adebe1b5ad943584b5689682
Os: Ubuntu 18.04 x64  4.15.0-22-generic
gcc --version:    gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0

**Comment by mppf** [comment]
@marcoscleison - did you recently upgrade to Ubuntu 18.04? I wonder if it's an issue with that particular OS. I'm expecting to upgrade to it myself at one point and that might allow us to reproduce it.

**Comment by marcoscleison** [comment]
@ben-albrecht , excuse-me the long waiting. I executed according to your suggestion and could compile the chapel again. Thank you very much. I will close the issue.

**Comment by mppf** [comment]
I got this same error with a `make -j 8` on my Ubuntu 18.04 system. But it didn't go away when I clobbered and rebuilt. Additionally this system seems to have hwloc installed and that might be related to the issue.

**Comment by mppf** [comment]
I see the error without a parallel make, even. The configure log says something like this
```
/// lots of stuff omitted
| char hwloc_topology_init ();
| int
| main ()
| {
| return hwloc_topology_init ();
|   ;
|   return 0;
| }
configure:26652: gcc -o conftest -g -I/home/mppf/w/13/runtime/include/localeModels/flat -I/home/mppf/w/13/runtime/include/mem/jemalloc -I/home/mppf/w/13/runtime/include -I/home/mppf/w/13/third-party/jemalloc/install/linux64-gnu-native/include -I/home/mppf/w/13/third-party/hwloc/install/linux64-gnu-native-flat/include  -L/home/mppf/w/13/third-party/hwloc/install/linux64-gnu-native-flat/lib  conftest.c -lhwloc -lnuma  -lm -lpthread  >&5
/home/mppf/w/13/third-party/hwloc/install/linux64-gnu-native-flat/lib/libhwloc.a(topology-nvml.o): In function `hwloc_nvml_query_devices':
/home/mppf/w/13/third-party/hwloc/hwloc-src/src/topology-nvml.c:38: undefined reference to `nvmlInit_v2'
```

I think on this system, hwloc is detecting something CUDA related, and perhaps needs -lnvidia-ml. I thought we handled this earlier... but havn't found the issue/PR yet.

**Comment by ben-albrecht** [comment]
@mppf - Are you finding this to be a sporadic error, or does it consistently fail for you?

I installed Chapel from master on my Ubuntu 18.04 system with `make -j 12` (CUDA installed, if that matters) and did not encounter this error.

**Comment by mppf** [comment]
it fails consistently for me

**Comment by mppf** [comment]
hwloc configure says
```
checking nvml.h usability... yes
checking nvml.h presence... yes
checking for nvml.h... yes
checking for nvmlInit in -lnvidia-ml... yes
```

**Comment by mppf** [comment]
PR #7794 disabled hwloc cuda device discovery. I'll make something similar for nvml.
