### ISSUE TITLE
Syntax of Partial Reductions

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#9656]
A partial-reduction expression needs these 3 ingredients:

* reduction operation (`OP`)
* the result shape (`SHAPE`)
* the expression being reduced (`EXPR`)

The proposed syntax options are:

(A) `OP reduce (SHAPE) EXPR`

This is the simplest option.

(A2) `OP reduce (shape=SHAPE) EXPR`

Allow the user to add the optional "shape=" annotation to clarify the role of the expression within the parentheses.

(A3) `OP reduce {SHAPE} EXPR`

Use curly braces to suggest a similarity of SHAPE to a domain.

(B) `OP reduceto (SHAPE) EXPR`

This option requires the introduction of a new keyword, such as `reduceto`. On the upside, it provides a clear distinction from the syntax of a full reduction.

`SHAPE` is one of:
* a domain
* a tuple with one component per dimension:
  - a bounded range
    + indicates a preserved dimension if it matches the corresponding dimension of EXPR
    + indicates a collapsed dimension if it contains a single index
  - an unbounded range - indicates a preserved dimension
  - an integer - indicates a collapsed dimension

For example, given `A: [1..10, 1..20, 1..30, 1..40] real', SHAPE could be `(5, 6..6, 1..30, ..)`, indicating dimensions 1, 2 to be collapsed and 3, 4 to be preserved.

**Comment by ben-albrecht** [comment]
@vasslitvinov - This might be easier to reason about with a few concrete examples.

Stylistically, it might be easier for users to remember this syntax by suggesting the shape is being passed into the reduction machinery, writing it like so:

```chpl
+ reduce(dom) myArr
```

Maybe this is too misleading though.

Note the format of `SHAPE` differs from the shape used in array/domain terminology, such as `array.shape` / `domain.shape` (tuple of sizes in each dimension, e.g. `(3, 4)`). We'll have to make sure documentation is clear in the distinction between the two.

**Comment by vasslitvinov** [comment]
@ben-albrecht - `+ reduce(dom) myArr` is exactly what we want to express.
The problem is that I do not know how to adjust the parser to parse that.
The parentheses are ambiguous with a full reduction as in `+ reduce (myArr)`.
What do you think?

**Comment by mppf** [comment]
While it's certainly the case that an ambiguity makes adjusting the parser harder, it doesn't mean it's impossible. The language already has a variety of ambiguities that are handled by precedence rules and I see no reason that `reduce` could not have similar treatment. It just means it will take longer to figure out how to make the parser handle it than an un-ambiguous design. Additionally with ambiguities we have to think about whether or not the ambiguity would be confusing to a human reading a program.

**Comment by vasslitvinov** [comment]
For example:

```chpl
+ reduce (A) (B)
```

This could be a partial reduction where A is the shape.

Or it could mean `(+ reduce (A)).this(B)` i.e. a full reduction over A that produces an object, and then the object is invoked on B.

One way to disambiguate is to make `reduce` right-associative. How would that work?

Another way to disambiguate is by requiring "shape=" for partial reductions. Ex.

```chpl
+ reduce (shape=A) (B)
```

Will this require making "shape=" a token?

**Comment by vasslitvinov** [comment]
Update: after discussing with @bradcray, we chose (A) as the starting point.
Thanks to @mppf for implementing it in the parser!
