### ISSUE TITLE
Classify existing uses of nested classes and records

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#9664]
Initializers do not work with complicated nested types, and in discussing solutions some on the team wondered whether the affected tests were using nested types in a reasonable way. Our language design for nested types has never quite been solidified, so there is the chance that we may decide to deprecate behavior that interferes with initializers.

Before proceeding, we should classify the failing tests' usage of initializers and determine if we value that functionality. To clarify, this effort will focus on programs that were not written to stress-test nested type functionality (e.g. AMR).

See #9353 for more.

**Comment by benharsh** [comment]
I focused on three cases:

1) release/examples/programs/*
  There are a couple of tests, genericStack and linkedList, that use nested types. The nested type does not use 'outer' directly or indirectly, so the only benefit is scoping.

2) studies/uts/*
  The failing test,  uts_deq, did not use 'outer' directly or indirectly.

3) studies/amr/advection
  The failing tests under AMR do use 'outer', but only to access type/param fields. This means that the uses of 'outer' could be replaced with param/type fields in the nested type.

Overall, these tests barely rely on nested class functionality. The primary usage seems to be around scoping. AMR does use 'outer', but could just as easily use type/param fields on the nested type itself. None of these tests expose the nested type outside of the parent type, nor do they rely on methods on the nested type.

**Comment by bradcray** [comment]
@mppf: Following up on today's discussion, would you create an issue (or issues) that captures concerns you have with `outer` and/or other aspects of nested classes/records?

**Comment by benharsh** [comment]
Just a quick follow-up: about 400 of our 8000 tests (5%) fail when nested types are disabled.

**Comment by mppf** [comment]
Pretty sure that goes down to ~32 once you remove the nested TargetLocaleComparator out of SparseBlock Dom.

**Comment by mppf** [comment]
I've created an issue that tries to summarize my concerns:  #9674.
