### ISSUE TITLE
Adopt new memory management model in AI workflow application

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#9665]
In an effort to reduce memory leaks, reduce the complexity of memory management, and put more weight on the new memory management model, we should migrate the AI workflow application to the new memory management model.

This task will aim to:

- *Strategy 1*
  - [x] Convert all class instances to `owned`/`shared`/`borrowed`
  - [x] Remove all significant memory leaks
- *Strategy 2*
  - [x] Convert all class instances to `owned`/`shared`/`borrowed`
  - [x] Remove all significant memory leaks

**Comment by ben-albrecht** [comment]
Upon successfully converting my program for *strategy 1* to use delete-free managed types, all memory leaks were fixed.

**Comment by ben-albrecht** [comment]
General feedback so far (@mppf):

Biggest time sink in making this transition has been debugging `dereference nil` errors and seg faults when something goes wrong, e.g. stumbling over a bug (documented in other issues) or a user error. The most common user error for me was inadvertently transferring ownership of an `Owned` type, and later accessing it to get a `dereference nil` error. Identifying all the cases where transfers are happening is not as mechanical (`grep`-able) as I had expected.

While it took some effort, I'm happy with how the code has ended up now.

**Comment by mppf** [comment]
Regarding the general feedback - we might want to take that as increasing the priority of #9089 / #9090 /  #9500.

**Comment by mppf** [comment]
i.e. we're talking about making such cases usually caught at compile time

**Comment by ben-albrecht** [comment]
> we're talking about making such cases usually caught at compile time

That would have saved me so much time. 👍 to prioritizing those efforts.

**Comment by ben-albrecht** [comment]
@mppf - I know this is in the works, but wanted to note it for completeness: another large time sink in this task was finding the right resources. I mostly had to resort to digging up powerpoint slides and searching the `test/` directory to find examples of what I was trying to do.

A well-written tech note with ample examples would go a long way in helping users transition to delete-free memory management.
