### ISSUE TITLE
should nested classes/records have a runtime link to outer class/record?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#9674]
Before initializers, the compiler has supported some forms of nested classes and nested records.
The question is, should there be a run-time relationship between the nested type and the parent type? Or, should the nesting be available only for controlling visibility of the inner type (and to access outer compile-time param/type values)?

What do other languages do?
 * Swift, C#, C++ have nested classes that don't have a run-time relationship. You can set this up yourself when needed by adding a link to the parent as a field in the nested class.
 * Java, D have nested classes that can access the fields in the containing class at run-time.
 * Rust doesn't allow nested classes/structs.

For types using constructors, the compiler has added an `outer` field to the inner record/class. For a record/class contained in a class, this `outer` field points to the outer class instance. But for a record/class contained in a record, this `outer` field is a copy of the outer record.
 
This question seems related to me to the question of whether or not an inner function, first class or not, or a method on a class declared in a function, has access to the functions variables, e.g.:
``` chapel
proc foo() {
  var i = 1;
  record R {
    var x = 1;
    proc bar() { return x+i; }
  }
  var r:R;
  return r.bar();
}
```
That can work now (compiler adds arguments to the `bar` method for to refer to the outer variable `i`). What if R is returned, though? (Right now, you can't call the `bar` method on `R` once you're outside of `foo` - but that wouldn't be true for a first-class-function since they have a well known type). But, the corresponding example does work today with nested records:
``` chapel
record Outer {
  var i = 1;
  record R {
    var x = 1;
    proc bar() { return x+i; }
  }
  proc make() {
    var r:R;
    return r;
  }
}

proc test() {
  var o = new Outer();
  var r = o.make();
  writeln(r.bar());
}

test();
```

Here is an example case that compiles today but leads to accessing uninitialized memory:
``` chapel
class Outer {
  var i = 1;
  class R {
    var x = 1;
    proc bar() { return x+i; }
  }
  proc make() {
    var r:R = new R();
    return r;
  }
}
proc get() {
  var o = new owned Outer();
  var r = o.make();
  return r;
}
proc test() {
  var r = get();
  writeln(r.bar());
}
test();
```

What is the reason people use nested classes?
 * in C++, and in my tests of the feature in Chapel, I've used them to encapsulate a bunch of template / generic type/params into the parent class so that the nested class doesn't need to list these again
 * in C++ and Chapel, they might be useful to limit access to the nested class (but one might argue module visibility is a better way to achieve this)
 * group classes that are only used as "helpers" for another classes

I don't think any of these require that the classes have an implicit runtime relationship. Additionally, I think we should try to make a harmonious decision here with the case of code/types declared inside functions (so there can be simple rules for inner functions / classes / lambdas declared inside of functions that are consistent with classes / records declared inside of other classes /records).

Arguments for putting off the decision / considering lambdas at the same time:
 * consistency with types/functions/methods declared inside of functions

Arguments for not allowing such nesting:
 * modules are a better way to encapsulate related functionality and handle visibility

Arguments for implicit runtime relationship:
 * lexical scoping, strictly interpreted, allows access to the outer fields

Arguments against the implicit runtime relationship:
 * for types nested in records, it's likely that the outer type is *larger* than the nested type. So it would be surprising for the inner type to contain a copy of the outer data.
 * for types nested in classes, the lifetime of the outer class isn't necessarily related to the lifetime of the inner class (see the example above). I think this is part of the reason the implicit runtime relationship is more common in garbage collected languages.
 * the implicit field is something that the user cannot adjust (say, they might want it to own the parent class reference, or refer to a singleton, or refer to nothing at all). If the user creates a field to express the runtime relationship, they can express any pattern they desire.

**Comment by benharsh** [comment]
Arguing against 'outer':

I think the presence of an ``outer`` symbol would be inconsistent with the rules we have established for initializers. A common case with nested types is for the outer type to have a field whose type is the inner, nested type. For the outer type to initialize that field, it must pass ``this`` to the nested type's initializer. Passing ``this`` as if it were the fully-initialized type is not allowed until ``this.complete``, because ``this`` may not yet be fully initialized.

I think this inconsistency is enough, but there are some other odd cases to consider:
- would method calls be allowed within the nested type's initializer after this.complete()? 
- What about for generics? What if the field with the nested type is initialized before a param/type field?

**Comment by benharsh** [comment]
If we were to allow 'outer' within an initializer only, I think we would have to require that an outer field with the nested type be initialized after any fields the nested type might use. For example, we would not allow this:

```chpl
class A {
  var b : B; // T, x not yet initialized
  type T;
  var x : T;
  var q : real; // B does not use q

  class B {
    var y : T;
    var z = x;
  }
}
```

But we might allow the following:
```chpl
type T;
var x : T;
var b : B;
var q : real;
```

Personally I'm skeptical that the additional rules for the compiler/user to deal with would be worth the expressiveness, but I think it can technically be done.

I would advocate for deprecating ``outer`` entirely first, and then re-introducing it for initializers if needed later on.

**Comment by mppf** [comment]
Regarding the previous comment, I think it's a valid program & would expect the type of y to be `int`. I'm happy to have (as a Chapel user) the ability for nested classes to use type / param fields from the enclosing class. However you might be able to articulate reasons that would be hard to implement.

My main personal opinion is that the *runtime* component of *outer* is a bad idea.

**Comment by benharsh** [comment]
What I was trying to get at with my second comment is that we could/should only support using type/param fields from the enclosing class if the nested type is being instantiated after those enclosing fields have been initialized. So this would be illegal:
```chpl
var b : B;
type T;
var x : T;
```
But this would be OK:
```chpl
type T;
var x : T;
var b : B;
```

My rationale here is that we would have to pass 'this' to B's initializer in order to access those type/param fields, but 'this' may not be fully initialized/instantiated yet.

I'm not opposed to allowing this functionality, but would prefer to start by disallowing it for simplicity's sake.

**Comment by mppf** [comment]
I think it's reasonable to limit the outer class field declaration order as in your case above.

**Comment by bradcray** [comment]
@benharsh and @mppf: I think we've effectively decided to remove support for `outer` but preserve nesting for the namespace convenience.  Issue #9896 captures the main remaining question in my mind, making me wonder if we can close this issue now.  Thoughts?

**Comment by mppf** [comment]
Yeah let's close it, but make the remaining questions issue link to this one (for achival reasons).

**Comment by bradcray** [comment]
Interesting... though I was the one who referenced this issue, it was in an edit to @benharsh's comment, so he gets the credit above...  Now I'm wondering how I could use this for evil...!
