### ISSUE TITLE
 Enabling fields with generic declared types introduced memory leaks

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#9689]
https://github.com/chapel-lang/chapel/pull/9489 introduced several new memory leaks:

https://chapel-lang.org/perf/chapcs/?startdate=2018/05/13&enddate=2018/05/19&graphs=memoryleaksforalltests,numberoftestswithleaks (seen on the 17th)

Looking at a partial diff of `diff memleaks.2018-05-16.nightlyfull.log memleaks.2018-05-17.nightlyfull.log`:
```diff
246a254
>       192400  test.chpl
275a284
>         3216  assign.chpl
292a302
>         1824  writef_readf.chpl
295a306,308
>         1584  forwardDefaultDom.chpl
>         1584  forwardDefaultArr.chpl
>         1584  dataPar2.chpl
297a311
>         1520  mason-chpl-version-update.chpl
303d316
<         1376  mason-chpl-version-update.chpl
327a341
>          864  equality.chpl
337a352
>          704  localDataPar.chpl
359a375
>          480  test_forall_of_arrays_is_parallel.chpl
372a389
>          384  test_2D_whole_array_assignment_is_parallel.chpl
378c395,396
<          272  test.chpl
---
>          288  test_whole_array_assignment_of_array_promotion_is_parallel.chpl
>          264  digits.chpl
394a413,418
>          192  test_reduction_of_forall_expression_is_parallel.chpl
>          192  test_whole_array_assignment_is_parallel.chpl
>          192  test_whole_array_assignment_of_elemental_value_is_parallel.chpl
>          192  test_reduction_of_array_promotion_is_parallel.chpl
>          192  test_reduction_of_nested_forall_expressions_is_parallel.chpl
>          192  generic-field-unmanaged-borrowed.chpl
400a425
>          160  readfre.chpl
406a432
>          152  regex.chpl
408c434,435
<          136  regex.chpl
---
>          144  mason-chpl-version-new.chpl
>          144  masonNewTest.chpl
410d436
<          136  mason-chpl-version-new.chpl
412,413d437
<          136  masonNewTest.chpl
<          136  readfre.chpl
472a497
>           64  test_reduction_is_parallel.chpl
477a503
>           48  generic-field-default-init.chpl
478a505,506
>           48  coercions-shared.chpl
>           48  generic-field-integral.chpl
480a509
>           48  generic-field.chpl
490a520
>           40  recordio.chpl
502a533
>           32  coercions.chpl
508a540
>           24  coercions-to-init-borrowed.chpl
511a544
>           20  weirdParamInit4.chpl
518a552
>           16  read-string-zero.chpl
521d554
<           16  coercions-shared.chpl
522a556
>           16  coercions-generic.chpl
533d566
<           16  coercions.chpl
552a586
>            8  scanstring-precision.chpl
561a596
>            8  json-enum.chpl
```

So new leaks for: 

    assign.chpl
    writef_readf.chpl
    forwardDefaultDom.chpl
    forwardDefaultArr.chpl
    dataPar2.chpl
    mason-chpl-version-update.chpl
    equality.chpl
    localDataPar.chpl
    test_forall_of_arrays_is_parallel.chpl
    test_2D_whole_array_assignment_is_parallel.chpl
    test_whole_array_assignment_of_array_promotion_is_parallel.chpl
    digits.chpl
    test_reduction_of_forall_expression_is_parallel.chpl
    test_whole_array_assignment_is_parallel.chpl
    test_whole_array_assignment_of_elemental_value_is_parallel.chpl
    test_reduction_of_array_promotion_is_parallel.chpl
    test_reduction_of_nested_forall_expressions_is_parallel.chpl
    generic-field-unmanaged-borrowed.chpl
    test_reduction_is_parallel.chpl
    generic-field-default-init.chpl
    generic-field-integral.chpl
    generic-field.chpl
    recordio.chpl
    coercions-to-init-borrowed.chpl
    weirdParamInit4.chpl
    read-string-zero.chpl
    coercions-generic.chpl
    scanstring-precision.chpl
    json-enum.chpl

And increased leaks for:

    mason-chpl-version-update.chpl
    test.chpl
    regex.chpl
    mason-chpl-version-new.chpl
    masonNewTest.chpl
    readfre.chpl
    coercions-shared.chpl
    coercions.chpl

**Comment by mppf** [comment]
TODO: also look at leaks in subquery-crazy, field-in-unmanaged, and subquery-tuple.

**Comment by mppf** [comment]
default-unmanaged is always going to leak. PRs #9802  #9796 #9799 resolve most of the remaining leaks. What remains:

subquery-crazy, subquery-tuple, json-enum.
