### ISSUE TITLE
varargs and type query syntax

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#9692]
In looking at resolving issue #9521, I've noticed several problems with the implementation of type query arguments in functions with variable arguments.

First, my position is that the type supplied for a varargs argument indicates that the function accepts only 1 argument type (i.e. that the argument is a homogenous tuple) and that the type is the argument type (rather than a tuple type). The language specification, section 13.6, says:

> Either or both the number of variable arguments and their types can
be specified. For example, a basic procedure to sum the values of three integers can be written as
> ``` chapel
>   proc sum(x: int ...3) return x(1) + x(2) + x(3);
> ```
> Specifying the type is useful if it is important that each argument have the same type.  Specifying the number is useful in, for example, defining a method on a class that is instantiated over a rank parameter.

Now, what if instead of `int` that function queried the type?
``` chapel
proc sum(x: ?t...3) return x(1) + x(2) + x(3);
```

Should it be callable as `sum("hi", 1, 2)` ? I think the answer must be "no". The reasoning is that the `?t` syntax indicates that we don't know what type we would write there - but that there is a type that could be written there. However that is not what master (as of 17d0976eb2b4a89b699041f6a653babd8b843421) does:

``` chapel
proc sum(x: ?t...3) return x(1) + x(2) + x(3);
writeln(sum("hi",1,2)); 
// outputs hi12
```

I would expect this program to fail to compile since the `sum` call is not resolveable.

This issue is even more pronounced for queries on arguments to generic records in a varargs context, for example:

``` chapel
record R {
  var x;
}
proc foo(arg:R(?t) ... ?k) {
  writeln(arg);
}
foo(new R(1), new R("hi"));
// outputs ((x = 1), (x = hi))
```

Here again I expect that the ?t stands in for *some type* and that therefore it must be the same type for each argument.

My proposal here is that the ?t used on the type of a vararg refers to the element type and indicates that all of the vararg arguments must be of the same type. The result would be that both of the above examples would no longer compile.

**Comment by ben-albrecht** [comment]
> My proposal here is that the ?t used on the type of a vararg refers to the element type and indicates that all of the vararg arguments must be of the same type.

Alternatively, `?t` could refer to a tuple of types and we could allow heterogeneous argument types, but that seems like it could lead to trouble..

One use-case that might benefit from your proposal is the `Matrix` overload for building 2D arrays from 1D arrays in `LinearAlgebra`:

```chpl
proc Matrix(arr: ?t ... n) {

}
```

This would now enforce that the static component of the array types are homogenous, which is nice.

**Comment by bradcray** [comment]
I think I agree with Michael's analysis here.  I think if one wanted to support heterogeneous varargs and query the types of all arguments as Ben hopes for, the way to do it would be to avoid putting the type constraint on the formal argument:

```chapel
proc foo(x: ...) {
  writeln(x.type:string);    //  prints (string, int, real) 
}
foo("hi", 1, 2.3);
```

**Comment by ben-albrecht** [comment]
> I think if one wanted to support heterogeneous varargs and query the types of all arguments as Ben hopes for, the way to do it would be to avoid putting the type constraint on the formal argument

Agreed, I think that's completely reasonable. If it wasn't clear from my previous comment, I also agree with Michael's analysis.

**Comment by mppf** [comment]
PR #9723 makes this change but in order for that to work needed to modify several functions in ChapelArray, e.g.

``` chapel
proc chpl__distributed(d: _distribution, ranges: range(?) ...?rank) {
```

changed to
``` chapel
proc chpl__distributed(d: _distribution, ranges...)
where chpl__isTupleOfRanges(ranges) {
```

@benharsh said on the PR:

> This feels unfortunate to me. I see how range(?t) ... would require all elements to have the same type, but could we allow the old behavior for range(?)...?

(and later made it clear that wasn't intended to block the PR).

I don't think I agree that we should do that though. Anyway, if we decide to talk about it more, we should make a new issue, since merging that PR will close this one (momentarily).

**Comment by bradcray** [comment]
I'm sympathetic to @benharsh's view that `range(?)` could, and perhaps should, be considered a constraint that all elements are ranges, but that their generic aspects might differ from one another since the question mark isn't binding anything to an identifier.  I do find it more attractive from a user productivity perspective than a `where chpl__isTupleOfRanges()` argument which would then need to be defined (and potentially documented if this were in a user-facing routine).

**Comment by mppf** [comment]
To be clear, is the argument that `range(?)` specifically allows different instantiations of `range`, or that in general `MyGenericType(?)` allows different instantiations of `MyGenericType`?

I.e. is the argument that `?` is different from `?t` or that `range` is special?

**Comment by ben-albrecht** [comment]
It would seem natural for the undecorated `proc(x: ...) { }` to be the most generic / unconstrained case, where one could constrain specific `param` arguments, by providing values to those `param` arguments, even for default values:

```chpl
proc foo(r: range(idxType=int, stridable=false): ...) {
  ..
}
```

**Comment by benharsh** [comment]
> I.e. is the argument that ? is different from ?t or that range is special?

My thinking was that ``?`` is different from ``?t``, so this isn't limited to ``range``.

**Comment by bradcray** [comment]
Same as @benharsh.
