### ISSUE TITLE
Dereference nil with managed types and arrays

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#9703]
### Summary of Problem

Pushing a managed instance that contains an array onto another class's instance's array within an inner scope results in a seg fault / dereference nil error (depending on the array element type). See the example below if that sentence was hard to read.

There may be a more distilled version of this bug, but this seemed like a good spot to stop.

### Steps to Reproduce

**Source Code:**

```chapel
class I {
  var dom: domain(1);
  // if this is a primitive type like int, we get dereference nil error instead
  var r: [dom] string; 
  proc init(in r: [?dom] string) {
    this.dom = dom;
    this.r = r;
  }
}

class D {
  var iArr: [1..0] I;
}

var i = new shared I(['a', 'b']);
var d = new D();

{
  d.iArr.push_back(new shared I(i.r)); // shared/owned/borrowed all result in seg fault
}

for element in d.iArr {
  writeln(element); // Seg fault here
}

```

Output:

```
# string case
Segmentation fault: 11
```

```
# int case
{dom = $CHPL_HOME/modules/internal/ChapelArray.chpl:1764: error: attempt to dereference nil
```

### Configuration Information

- Output of `chpl --version`: `chpl version 1.18.0 pre-release (51f70f0)`

**Comment by ben-albrecht** [comment]
This came up in https://github.com/chapel-lang/chapel/issues/9665

I'd be more interested in a reasonable work-around in the short-term, so that I can continue the effort in https://github.com/chapel-lang/chapel/issues/9665

Ping @mppf

**Comment by ben-albrecht** [comment]
For my particular use-case, representing this class as a record turned out to be reasonable. This still isn't a general work-around, but this issue is no longer blocking me, specifically.

**Comment by mppf** [comment]
Compiling with --warn-unstable pointed out that on line 12 the array is made out of `I` which is `borrowed I`. Changing the declaration to `shared I` allows the test to work.

However this error should have been detected with --lifetime-checking so I will look into that.

**Comment by mppf** [comment]
It turns out that the lifetime checking design has a gap in it to do with array.push_back. See issue #9853.
