### ISSUE TITLE
Double-free involving IfExprs and cast from string to string

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#9711]
### Summary of Problem
@psahabu ran into a double-free bug while working on DataFrames. It appears to manifest when one branch of an IfExpr returns an expression cast to a string, when that expression is a function call that itself returns a string.

**Source Code:**
The following program when run will fail with some error message related to freeing an unallocated pointer.
```chapel

config const cond : bool = true;

proc foo() {
  return "A";
}

proc main() {
  var y = if cond then foo():string else "B";
  writeln(y);
}
```

I am not yet sure if this is limited to IfExprs or strings.

### Configuration Information

- Output of `chpl --version`:
```
chpl version 1.18.0 pre-release (7bba95f)
Copyright (c) 2004-2018, Cray Inc.  (See LICENSE file for more details)
```

**Comment by benharsh** [comment]
#9007 may be a related issue.

**Comment by cassella** [comment]
valgrind doesn't complain about anything for that test for me today.  I can't quickly find a test locking in that behavior.

**Comment by benharsh** [comment]
Hmm, you're right. I'll close this and see if I can find which PR resolved the issue.

**Comment by bradcray** [comment]
Could we check the code from this issue in as a test to guard against backslides (since it presumably didn't work before?)
