### ISSUE TITLE
redundant .type for array type fails

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#9715]
### Summary of Problem

I expect .type applied to something that is already a type to do nothing, but when the type is an array type, it causes compilation failures:

``` chapel
var A:[1..10] int;

proc tf(type t) type {
  return t.type;
}

tf(A.type);
```

**Associated Future Test(s):**
  test/arrays/ferguson/runtime-type-type.chpl

**Comment by mppf** [comment]
I think preFoldPrimOp / PRIM_TYPEOF handling is related but fixing that to do nothing for type variables doesn't solve the problem.

**Comment by lydia-duncan** [comment]
I was actually just looking at this.  In the handling of PRIM_TYPEOF, we insert a call to convert the runtime value to a type when a runtime type is involved, but we don't check to ensure what we had was a value beforehand.

**Comment by lydia-duncan** [comment]
I don't have a fix myself, though, I was running into it because I was doing something else wrong with my new array types

**Comment by lydia-duncan** [comment]
That's probably about the same conclusion you came to yourself

**Comment by bradcray** [comment]
Am I understanding that you think that `t.type` should return `t` for a type t?

I'm not convinced that `.type` should be able to be applied to types (i.e., that instead, the compiler should warn/error when this happens).  It strikes me as being more likely to be a misunderstanding on the user's part than a useful feature.  If we had things that were generic over both types and values, perhaps it would make sense, but I don't think we do?

**Comment by mppf** [comment]
> Am I understanding that you think that `t.type` should return `t` for a type t?

Yes -- I think it should be idempotent. But at the very least the program in this issue should be a reasonable error.

**Comment by ben-albrecht** [comment]
>> Am I understanding that you think that `t.type` should return `t` for a type t?

> Yes -- I think it should be idempotent.

It would make more sense to me for the `type.type` to be a bare "type" or compiler error than the original value type.

Here's what some other modern languages do with this design decision:

| Language | `print(type(type(1))`        |
|----------|------------------------------|
| Go       | Compiler error               |
| Rust     | Printing types not supported |
| Swift    | `int`                        |
| Python   | `type`                       |

**Comment by bradcray** [comment]
I'm still inclined to make it an error (though Python's answer of `type` is a little intriguing to me, I'm not sure it would add value for Chapel).  Again, my rationale is that since we don't have code contexts where something can be either a type or a value (all types are syntactically noted at their declaration point), it seems more likely to be indicative of confusion on the programmer's part than a valuable tool for programming.  It feels a bit to me like the case where we used to support using a value in a type's location:

```chapel
var i: int;
proc foo(x: i) { ... }
```

where an argument _could_ be made that this supports convenience, but in practice seemed to result in more confusion (and support for writing confusing code) than utility.  If someone wanted the Python-like behavior, I'd be inclined to support it via `isType()` than by querying the type of a type (since I think we'd only have one possible answer?)

**Comment by ben-albrecht** [comment]
I'd be in favor of returning `type` or emitting a compiler error.

> it seems more likely to be indicative of confusion on the programmer's part than a valuable tool for programming


One (admittedly not too compelling) use-case to consider is a user calling a library function, where they don't know the return type, so they want to inspect it from within their Chapel program  through some interactive debugging:

```chpl
// Library
proc f() type {
  return int(64);
}
```

```chpl
// User code
use Library;

writeln(f().type:string);
```

A compiler error or returning `type` would provide the user with the information they need. The former would report that information at compile-time, but maybe not too clearly, whereas the latter would report it clearly, but at run-time.

**Comment by ben-albrecht** [comment]
> I don't see how a compile-time error message like "Can't apply .type to a type (int(64))" would be less useful than getting an execution-time output of "type".

If there error message was as clear and concise as your example, that'd probably be more helpful than returning just `type`.

**Comment by vasslitvinov** [comment]
+1 for making t.type a compile-time error when t is a type.
