### ISSUE TITLE
use override in module and test code

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#9733]
As a Chapel user, I want to be able to specify that a method I am implementing is intended to replace a method in a parent class so that I can understand my programs and receive more understandable errors.

As a Chapel developer, in order to globally enable the checking described above, we need to migrate all test and module code to pass with the checking enabled.

This task is to get full testing passing with --override-checking enabled.

**Comment by bradcray** [comment]
Module code is now done due to PR #10655.  Starting to look a test code under issue #10690.
