### ISSUE TITLE
Anomalous assignment from iterator to array

### ISSUE THREAD

**Issue by TomsyPaul** [chapel-lang/chapel#9738]
Hi all,

I can't understand the following code's output.

```chpl
iter test
{
  yield 1;
  yield 2;
  yield 3;
}  
var A:[1..10] int;
A=test;
writeln("A = ", A);
```
Which is `1 2 3 3 1 2 3 3 1 2`.

My question is..

1. Is the iterator promoted to array? If so is that desirable? I mean it should affect only the first three elements. Isn't it?

2. Why is 3 repeated?

**Comment by ben-albrecht** [comment]
Hi @TomsyPaul - what version of the compiler are you using? I got the following on the master branch:

```
iter.chpl:8: error: zippered iterations have non-equal lengths
```

**Comment by daviditen** [comment]
It's compiled with `--no-checks` or something that implies that flag.  The output is undefined because the zippered iterations have unequal lengths as the error message @ben-albrecht showed described.

**Comment by TomsyPaul** [comment]
Yes.. @daviditen , I was using --fast flag, which implied --no-checks.
