### ISSUE TITLE
Should casting from borrowed, owned, or shared to c_ptr or c_void_ptr be allowed?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#9740]
Should it be legal to cast from owned, shared, or borrowed to c_ptr or c_void_ptr?

Note this issue is asking about explicit casts (not implicit coercions).

For example
``` chapel
class MyClass { }
var x = new unmanaged MyClass();
var y = x:c_void_ptr;
```

``` chapel
class MyClass { }
var x = new owned MyClass();
var y = x:c_void_ptr;
```

**Comment by mppf** [comment]
I don't see any problem allowing such casts. I think by writing the cast, the user has indicated they wish to convert pointer types. They'd still be able to do the same by casting first to unmanaged, if we decided not to allow it.

**Comment by lydia-duncan** [comment]
Would such a cast be considered a transfer of ownership in the owned case?  Or would it be treated like a borrow?

In the case of a shared, would this usage be tracked?  If so, how would we know it was no longer in use?

**Comment by mppf** [comment]
> Would such a cast be considered a transfer of ownership in the owned case? Or would it be treated like a borrow?

> In the case of a shared, would this usage be tracked? If so, how would we know it was no longer in use?

No, it would be in both cases equivalent to x.borrow():c_void_ptr
I think it's OK to do this because c pointers are a kind of unmanaged (or managed by the user) pointer.

**Comment by lydia-duncan** [comment]
That seems tenable to me, then :)

**Comment by lydia-duncan** [comment]
Would our compiler analysis be able to fire on their use within Chapel code with that in mind?  Or would we lose some of that tracking?  (I figure we would lose for external code for sure)

**Comment by mppf** [comment]
> Would our compiler analysis be able to fire on their use within Chapel code with that in mind? Or would we lose some of that tracking? (I figure we would lose for external code for sure)

The lifetime checker sees c_void_ptr or unmanaged or c_ptr and says "hands off" and stops doing lifetime checking.

**Comment by psahabu** [comment]
I might consider disallowing it to prevent users from shooting themselves in the foot, perhaps casting a pointer they thought was unmanaged but is actually managed. On the other hand, that could get really annoying for users who do this cast frequently.

**Comment by bradcray** [comment]
I'm OK with supporting the casts, with the understanding that casting to C pointer types is essentially escaping the Chapel language and any support it gives.

I've lost track, but if it isn't already, I could imagine that all these C-oriented features should only be enabled by `use`ing a module that provides C type support rather than being features that are available in the standard context by default.

**Comment by mppf** [comment]
> I've lost track, but if it isn't already, I could imagine that all these C-oriented features should only be enabled by useing a module that provides C type support rather than being features that are available in the standard context by default.

They are used in the string type and so are included by default. We probably need to improve private use & related issues to do better.

**Comment by mppf** [comment]
Closing this issue because the consensus seems to be that these casts are OK and that's already what is implemented.
