### ISSUE TITLE
Disallow initializing-from-self variables

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#9750]
The compiler should generate an error for this code:

```chpl
var a: int = a;
```

**Comment by BryantLam** [comment]
As of `chpl version 1.18.0 pre-release (b0251ba45e)`, this error is reported:
`error: use of 'a' before encountering its definition, type unknown`

For this specific case, the reported error seems descriptive enough.

In #9985, however, the error message could be better.

**Comment by bradcray** [comment]
> for me the compiler accepts this line without generating an error.

Same here, and worse, it prints out an arbitrary value.  My wild guess is that Bryant might have tried `var a = a;` which does generate a somewhat reasonable error.

This discussion illustrates why issues that don't have accompanying futures drive me a bit nuts...

**Comment by BryantLam** [comment]
@vasslitvinov -- You're right. My bad! Your code with the explicit type declaration does get accepted.
