### ISSUE TITLE
Improve our handling of first class functions or c_fn_ptr for use with C interoperability

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#9768]
I was trying to send a function pointer to an extern C function from Chapel, but because of naivety in our c_fn_ptr and FCF implementation, I ended up needing to make an extern type to represent the type of the function pointer and defining explicit instances of that type in C that I could pass around in Chapel.  This seemed unnecessarily painful

**Comment by lydia-duncan** [comment]
From Michael: "c_ptrTo(c_free) or c_fn_ptr are jamming all function ptrs into 1 type which can cause problems in C compilation ...
"it would be pretty nice to fix the problems with c_fn_ptr ... mainly c_fn_ptr has to take arguments and the codegen needs to know how to generate it"

**Comment by bradcray** [comment]
Is this issue the same as #9411 or similar enough to it that one could be subsumed by the other?

**Comment by lydia-duncan** [comment]
That one seems more general to me, so I'm inclined to leave both open.  @mppf - what are your thoughts?

**Comment by mppf** [comment]
I'd consider these issues duplicates. If the other issue is more general, the description / comments here could reasonably be pasted there.

**Comment by lydia-duncan** [comment]
I've moved it over.  Closing now
