### ISSUE TITLE
Should enum->int casts be supported only for enumerated types with explicit values?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#9785]
In thinking about enums being 0-based vs. 1-based by default this morning when casting them to integers, it occurred to me that a better solution might be to not have enums be anything-based by default.  This would be easy to enforce by only supporting casts to integers for enums that are given values.  Thus, given:

```chapel
enum color {red, green, blue};
enum day {monday=0, tuesday, wednesday};
enum size {small=1, medium, large};
```

a value of type `color` could not be cast to int since no integer values had been given for any of its items, whereas a value of type `day` or `size` could.  The benefits of this choice would be that it would remove a place in the language where we may 0- vs. 1-based decisions on the programmer's behalf while also strengthening the enum abstraction for users who do not want to think of them as having underlying integer values.

(Note that all enums would still have an integral order still which is currently 0-based)

**Comment by mppf** [comment]
My opinion: yes

**Comment by bradcray** [comment]
Consensus here seemed to be that this change makes sense.  It seems to provide the best of both worlds:  Enums that have no relation to integers for those who want them to be a very abstract type and those that can be mapped to integers for those who want more of a C-like capability.
