### ISSUE TITLE
Weighted sampling

### ISSUE THREAD

**Issue by hmedal** [chapel-lang/chapel#9805]
**What I would like:**
To be able to do weighted random sampling from an array.

**What it should look like:**

```chpl
proc getRandomElement(probabilitiesArray: [] real){
    //returns a random element from the domain of probabilitiesArray based on the values of probabilitiesArray
   //the values of probabilitiesArray should sum to one
}
```

**Example:**

```chpl
var probabilitiesArray: [{1..5}] = [0.6, 0.1, 0.1, 0.1, 0.1];
var randomElement = getRandomElement(probabilitiesArray); //randomElement is 1 60% of the time and 2, 3, or 5 10% of the time each. 
```

**Use case:**
For random graph generation in which we are randomly selecting two vertices in a graph in order to add an edge between them. The random selection should be based on the desired degree of each of the vertices.

**Comment by ben-albrecht** [comment]
I actually have an implementation of something like this. I will try to clean that up and contribute upstream. The open question is where does something like this belong? 

Maybe the `Random` module?

**Comment by hmedal** [comment]
Yes, I think the `Random' module makes sense.

**Comment by hmedal** [comment]
``

**Comment by hmedal** [comment]
Sorry, accidentally pressed "Close".

**Comment by ben-albrecht** [comment]
My current implementation is the naive `O(n)` version. It would be nice to implement the `O(1)` implementation [from this paper](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=92917&tag=1), eventually.

As for the interface, I find the [`numpy.random.choice`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.choice.html#numpy.random.choice) interface appealing.

**Comment by hmedal** [comment]
Yes, I also like the `numpy.random.choice` interface.

**Comment by ben-albrecht** [comment]
After chatting with some other developers on the team, it sounds like `Random.choice` is the right place to put this function. I'll consider myself the owner of this task.

**Comment by ben-albrecht** [comment]
@hmedal - this is now available as [`Random.choice()`](https://chapel-lang.org/docs/master/modules/standard/Random.html#Random.RandomStreamInterface.choice) in the 1.19 pre-release: .
