### ISSUE TITLE
Support LayoutCS( sorted : bool )

### ISSUE THREAD

**Issue by ian-bertolacci** [chapel-lang/chapel#9811]
Per #9810 need to have LayoutCS take a boolean option indicating if the sparse dimension is sorted, and supporting implementation of optional sorting.

**Comment by bradcray** [comment]
Thinking about your param bool loop over on issue #9860 this morning...  while I agree that param loops over bool ranges are reasonable to support, I also found myself wondering whether I was wrong in suggesting that this sorted flag should be a param.  Is it a case where compile-time code specialization is likely to significantly impact performance on critical paths?  Or is it a case where an execution-time check would be sufficient?  (A potential secondary consideration being code size:  If a program uses only sorted or unsorted sparse domains, is the code size significantly smaller?  If it uses both, is the code size significantly bigger?)

**Comment by ian-bertolacci** [comment]
Are you anticipating that people will want to decide in execution-time if they want sorting on?
My intuition says that any additional overhead to index lookup would be bad, but then again it's only one if statement per lookup.

**Comment by bradcray** [comment]
> Are you anticipating that people will want to decide in execution-time if they want sorting on?

Mmmmaybe.  Or, they may want to have the opportunity to turn sorting on and off over the lifetime of a sparse domain, maybe?  I don't feel confident about either of these things, though... was just second-guessing whether my instinct to make it a `param` was overkill.

> My intuition says that any additional overhead to index lookup would be bad, but then again it's only one if statement per lookup.

If index lookup were O(1), I'd agree that we might want to avoid a conditional.  But my guess was that the index lookup case (and others where this param would come into play) already probably have so many conditionals and loops that one more outer-scope conditional would hardly be noticeable.

In no way am I insisting on anything here, though, just exploring the question.

**Comment by ian-bertolacci** [comment]
Lemme get some numbers.

**Comment by bradcray** [comment]
You're also welcome to just file this away as food for thought.  No need to let it stand in the way of progress (it mostly came up for me as I was thinking about ways you might work around the lack of param bool for loops before learning you had a workaround already).

**Comment by ian-bertolacci** [comment]
Closed with #9877
