### ISSUE TITLE
Spike: explore the issue of slicing in sparse arrays

### ISSUE THREAD

**Issue by ian-bertolacci** [chapel-lang/chapel#9813]
Many users want slicing of sparse arrays (#8023, #8819, #9446). I think slicing on distributed sparse arrays is (or was) also mentioned. I'd like to spin up on what it would take to get slicing working on sparse arrays.

**Comment by benharsh** [comment]
I spent some time investigating this as part of an issues-week, but quickly discovered that providing a fully-functional implementation would take more time than I had. Here are some observations:

- We need a 'stridable' method on sparse domains/arrays to avoid issues with shared-code for rectangular slicing (easily achieved by adding a method to BaseSparse*)
- We currently always return a rectangular domain when slicing any domain. We should return a domain of the kind being sliced, or allow the domain map author to decide what that means.
- ArrayViewRankChange and ArrayViewReindex are not set up to handle non-rectangular domains/arrays, and easily break.
- ArrayViewSlice can be made to work relatively quickly, but slices will be printed as if they were rectangular arrays. I think we may want a general way of telling an array to print itself with a given set of indices.

**Comment by ben-albrecht** [comment]
Migrating this info to https://github.com/chapel-lang/chapel/issues/8023 and closing.
