### ISSUE TITLE
Spike: Bale's Toposort benchmark

### ISSUE THREAD

**Issue by ian-bertolacci** [chapel-lang/chapel#9814]
The [Toposport benchmark](https://github.com/jdevinney/bale/tree/master/apps/topo_src) is an interesting sparse matrix benchmark. Investigate this benchmark and explore developing it in Chapel (likely after addressing LayoutCS sorting (#9810)).

**Comment by mppf** [comment]
@ian-bertolacci - if this spike allows for a simple sketch of naive topo-sort in Chapel, could you add it to #9848? thanks.
