### ISSUE TITLE
CI testing for Mason-Registry

### ISSUE THREAD

**Issue by Spartee** [chapel-lang/chapel#9846]
Ideally each package within the registry is tested fully using a testing framework, but since that has not been developed yet some simple testing could be beneficial in the meantime. Upon a user opening a PR the Travis CI would perform a series of checks. 

A few examples of points we would check
- `Mason.toml` formatting 
- git tag version formatting
- namespace collisions

**Comment by ben-albrecht** [comment]
We could also enforce some package quality constraints:

- Does the package documentation build successfully?
- Does the package have tests?
- Does the package have examples?

**Comment by ankingcodes** [comment]
@ben-albrecht There was a "todo" comment on MasonSearch which required to sort the list of packages on some "best match" metric. Probably, these same constraints can be used to generate a `rank` for the packages. for example, `npm` ranks its packages on the basis of popularity, quality, maintenance. We could do the same for Mason but only on the basis of quality ( presence of README, stability, tests, examples) and maintenance(checking the version number). What do you think ?

**Comment by ben-albrecht** [comment]
@ankingcodes - That sounds like a great feature. I would suggest opening a new issue to discuss design details further.

**Comment by ankingcodes** [comment]
> We could also enforce some package quality constraints:

@ben-albrecht  Could we perform these checks on a TOML file submitted in the PR for mason registry ?

**Comment by ben-albrecht** [comment]
>  Could we perform these checks on a TOML file submitted in the PR for mason registry ?

Yes. I believe `mason publish --ci-check` aims to implement some checks, but do not recall which checks it implements off the top of my head.

**Comment by ankingcodes** [comment]
I checked out `mason publish --ci-check` which is as follows : 
```
 if ci {
    if package && moduleCheck(projectCheckHome) {
      attemptToBuild();
      # executes mason build --force and checks the status and displays result
      exit(0);
    }
    else {
      writeln('New package does not have the proper structure.');
      exit(1);
    }
}
```
Also, by my question I meant , could we do the checks you mentioned in Travis ?

**Comment by ben-albrecht** [comment]
Does `moduleCheck(projectCheckHome)` check any of these things?

> could we do the checks you mentioned in Travis ?

Absolutely, I think the intention is for a Travis check to run `mason publish --ci-check <pkg>` for packages added in the PR.

**Comment by ankingcodes** [comment]
> Does moduleCheck(projectCheckHome) check any of these things?

@ben-albrecht Nope, it just checks if there is atleast 1 module file inside of `src`. I guess we can modify this to perform the checks you mentioned?

**Comment by ben-albrecht** [comment]
>  I guess we can modify this to perform the checks you mentioned?

Yes, I think that's the right idea.

**Comment by ankingcodes** [comment]
I don't think we should make a separate issue for this, since it already comes under this issue and I have already included it in my proposal.

**Comment by ben-albrecht** [comment]
Agreed!

**Comment by ankingcodes** [comment]
@ben-albrecht In Sam's comment above, by Mason.toml formatting , does it mean checking if the important fields required to publish a package are present ? 
I'm not very sure about git tag version formatting? Could you explain that & how could that be checked ? 
By namespace collisions, I understand that name of a proposed package should not match with those already present.
Also, should the package quality constraints defined by you be checked together with those proposed by Sam ?

**Comment by ankingcodes** [comment]
There's a similarity of these checks with the ranking issue of mason search at #15715 . I have an idea, what if we could derive the points for a package within this function, and do the following : 
- append the rank to the Toml cache
- configure with an email and name that is allowed to push to mason-registry git repo.
( `git config --global user.name USERNAME && git config --global user.email EMAIL `)
- Perform commands to push to repo using
```
git add -A
git commit -m "update cache"
git push 
```

**Comment by ben-albrecht** [comment]
> In Sam's comment above, by Mason.toml formatting , does it mean checking if the important fields required to publish a package are present ?

Yes, I think the required bare fields are package name, version, chplVersion, and source. Author would be good to require too.

> I'm not very sure about git tag version formatting? Could you explain that & how could that be checked ?

If `version = "0.1.0"` and `source = "https://gitlab.com/npadmana/numpylike.git"`, then we should clone `https://gitlab.com/npadmana/numpylike.git`, fetch the tags, and verify that a tag named `v0.1.0` exists.

> By namespace collisions, I understand that name of a proposed package should not match with those already present.

That is correct.

> Also, should the package quality constraints defined by you be checked together with those proposed by Sam ?

I think my suggestions should go into the package ranking system that you have developed. We could emit a message in the CI testing output that mentions lack of documentation, testing, etc. but it shouldn't fail due to it.

> I have an idea, what if we could derive the points for a package within this function, and do the following :

That's a great idea.

> - configure with an email and name that is allowed to push to mason-registry git repo.
( `git config --global user.name USERNAME && git config --global user.email EMAIL `)

We could use an existing account in @chapel-lang/automatons or add a new one for this.

**Comment by ankingcodes** [comment]
> > By namespace collisions, I understand that name of a proposed package should not match with those already present.
> That is correct.

@ben-albrecht When an user wants to publish their package, they have to create a directory with their `packageName` which includes a manifest file containing package details. So, if a directory with that name already exists in the `Bricks/` directory, they would be unable to create the directory itself. So, I think there shall not be any namespace collision in that case. 
Can there be a case when the name of the directory created in `Bricks/` be different than that of the package name defined in `Mason.toml` of an user's actual package repository ?

**Comment by ben-albrecht** [comment]
> So, I think there shall not be any namespace collision in that case.

That's correct. The main `mason-registry` is a single name space which does not allow for collisions

> Can there be a case when the name of the directory created in Bricks/ be different than that of the package name defined in Mason.toml of an user's actual package repository ?

No, the package name should match the directory name (and we should enforce that).

**Comment by ankingcodes** [comment]
> No, the package name should match the directory name when publishing (and we should enforce that).

@ben-albrecht Actually there's a case where such a condition is allowed. The `--name` option in `mason new` & `mason init` allows users to create packages with illegal package names, where the directory name is kept illegal, however, a legal name is used in manifest file. This option contradicts our check for namespace collision. Therefore, I believe we should omit this check !

**Comment by ben-albrecht** [comment]
>  Actually there's a case where such a condition is allowed. The `--name` option in `mason new` & `mason init` allows users to create packages with illegal package names, where the directory name is kept illegal, however, a legal name is used in manifest file. This option contradicts our check for namespace collision. Therefore, I believe we should omit this check, or at most provide a warning !

I think we can continue to let users put their package in any directory they wish, but when they publish to the registry, the registry directory needs to match the package name. I think `mason publish` should use the package name for the directory name automatically when publishing to prevent users from making this error. What do you think?

**Comment by ankingcodes** [comment]
@ben-albrecht That can be a way to solve this problem, but from an user point of view, I don't find this very convenient. A package developer might be confused between legal and illegal package names. I think if we supported using illegal package names while creating a package, we should also allow users to have an illegal mason registry directory name. Can you think of a problem that an illegal package directory name might cause for mason-registry ?

**Comment by ben-albrecht** [comment]
In an offline discussion we determined we should continue to allow users to put a package in whatever directory they'd like, but for the directory name within the registry to always match the package name for simplicity in the registry. `mason publish` should convert the name of the directory automatically if it does not already match.
