### ISSUE TITLE
Spike: non-Chapel dependencies in Mason

### ISSUE THREAD

**Issue by Spartee** [chapel-lang/chapel#9847]
Q: how do other package managers handle external dependencies and what should our implementation strategy be for incorporating external dependencies into mason.

 - explore cargo and other package managers methodologies

**Comment by Spartee** [comment]
Closing spike, look for other related research spikes to follow.

**Comment by ben-albrecht** [comment]
> Interface with system level package managers

I think this approach would only make sense if the other approaches were determined to be too large of scope to complete within this summer. Relying on the system-installed packages is not necessarily a stepping stone towards where we want mason to be, but it would probably be good enough for many users in the short-term future.
