### ISSUE TITLE
Bool ranges

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#9866]
Now that ranges are starting to support `idxType`s other than primitive `int`s, should we support ranges of `bool`?  And `param` ranges of bools?

Pros
----
* well-defined, rounds out the set of supported types

Cons
-----
* limited utility (although... see issue #9860).

**Comment by mppf** [comment]
I don't have a strong opinion but the utility does seem pretty limited to me.

**Comment by dmk42** [comment]
Another reason to support them might be to facilitate writing generics.

**Comment by bradcray** [comment]
I should add that if we decide not to support them, I think we should create an overload of the range creation routines for bools that issues an error rather than having them coerce to the integer range creators.

Also, while running testing on other branches yesterday, I fairly easily put together a PR #9916 that adds support for them.

**Comment by bradcray** [comment]
@daviditen : I just came across test/param/diten/paramForBool.chpl which made me wonder if you had an opinion on this.

**Comment by daviditen** [comment]
I think it looks reasonable and fits well with enum ranges.  I don't see any real downside.  I'm fine with that test changing to expect `false/true` instead of `0/1`.
