### ISSUE TITLE
Scope precedence for type from another module

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#9884]
Consider the following program:
```chpl
module X {
  module M {
    record R { // M.R
      type t;
      var x : int;
    }
  }

  use M;

  record R { // X.R
    var r : R(int); // M.R! Should it be X.R?
  }

  var r : R;
  writeln(r);
}
```

At the time this issue was created, this program compiled successfully. The compiler resolves the type of X.R to have a field of type M.R. Is this intentional?

The current implementation of the compiler identifies the field 'r' to have type X.R during scope resolution, but later replaces the call (R int) with (type_construct_R int), where "type_construct_R" is an UnresolvedSymExpr.

Type resolution will later search for any "type_construct_R" that accepts a type variable, and finds M.R.

**Comment by bradcray** [comment]
I think `r` should have type `X.R` (which itself should be illegal since it's a recursive record creation).

I was hoping to take stock of issue #8555 today and am wondering whether it's at all related to this one.

**Comment by benharsh** [comment]
Thanks. The following program fails under --force-initializers due to this distinction:
``types/records/sungeun/chapelTypes/record_range.chpl``

I intend to retire that test and create a new test based on the code from the issue.
