### ISSUE TITLE
Run script against data during import

### ISSUE THREAD

**Issue by benjamin-robbins** [chapel-lang/chapel#9885]
As a Chapel Developer I want to run a preprocessing function against my data during import so that I can transform my data as needed in line during import rather than as a separate step.

Success Criteria:
Select HDF5 Files for import
Select script for use as preprocssing function
Run function against data as import is happening
Data is transform in array/dataframe

**Comment by bradcray** [comment]
By "script" do you mean a literal external script or some preprocessing computation written in Chapel itself?

**Comment by daviditen** [comment]
My understanding of this task is that we'd provide something like a `HDF5Preprocessor` class with a `preprocess` method that could be extended with `preprocess` overloaded to do whatever you want with the data.  The `preprocess` overload could then call other Chapel routines or call out to external scripts or programs to manipulate the data.

**Comment by daviditen** [comment]
Closed with PR #10138.
