### ISSUE TITLE
Support unmanaged keyword in chpldoc

### ISSUE THREAD

**Issue by Spartee** [chapel-lang/chapel#9887]
**Problem Summary**
Today the chpldoc tool does not support the unmanaged keyword as a return type and produces an unattractive string in its place. In working on the TOML documentation(issue #9841) I realized this might not be the only return type not supported. 

***Steps to Reproduce***
filename = sample.chpl
``` chapel
 proc parseToml(input: channel) : unmanaged Toml {
    var tomlStr: string;
    input.readstring(tomlStr);
    return parseToml(tomlStr);
}
```
***command***
`chpldoc sample.chpl`

***produces***
proc parseToml(input: channel): AppendExpr.Call09

**Comment by lydia-duncan** [comment]
I suspect we also fail to handle owned and shared
