### ISSUE TITLE
`chpl_topo_getNumCPUsPhysical` declared implicitly

### ISSUE THREAD

**Issue by PHHargrove** [chapel-lang/chapel#9888]
It appears that 68dbb1dd introduced a regression in master:

```
comm-gasnet.c(801): error #266: function "chpl_topo_getNumCPUsPhysical" declared implicitly
    num_cpus = chpl_topo_getNumCPUsPhysical(true) + 1;
```

This was observed on master at  771ea642 with PrgEnv-intel on NERSC's Edison, if that matters.

**Comment by ronawho** [comment]
Just merged https://github.com/chapel-lang/chapel/pull/9889, which should resolve this. Thanks for the heads up.
