### ISSUE TITLE
Confusing error in assignment with mismatched types

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#9923]
### Summary of Problem
This code is wrong. However, the compiler emits a confusing error message.
```
error: type mismatch in assignment from G1(1) to G1(1)
```
One suggested resolution is to say what the mismatched types are.

### Steps to Reproduce
**Source Code:**

```chapel
module ParamType {
  class G1 {
    param x;
  }

  proc main() {
    var g1 = new G1(1);
    var g2 = new G1(1:uint);

    g1 = g2;
    delete g1, g2;
  }
}
```

### Configuration Information
`chpl version 1.18.0 pre-release (e770634374)`

**Comment by bradcray** [comment]
It looks to me like the compiler _is_ saying what the mismatched types are, it's just not saying what type the `param` values that characterize those types are in a way that lets them be distinguished.  My proposed fix here would be to have non-default param values print out their type after the value in a type context.  I.e.,

```
error: type mismatch in assignment from G1(1:uint) to G1(1)
```

**Comment by mppf** [comment]
I'm working on a fix for this
