### ISSUE TITLE
Forwarding bug with param fields

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#9926]
### Summary of Problem
The following program fails to compile when I attempt to access a forwarded param field:

```chpl

class Inner {
  param x : int;
  param y : bool;

  var z : if y then x*int else x*real;
}

class C {
  forwarding var i = new Inner(2, true);
}

var c = new C();
writeln(c.x);
```
The output of the compiler is:
```
foo.chpl:14: error: ambiguous call 'C.x'
foo.chpl:10: note: candidates are: C.x
foo.chpl:10: note:                 C.x
```

**Associated Future Test(s):**
[classes/forwarding/forward-param.chpl](https://github.com/chapel-lang/chapel/blob/master/test/classes/forwarding/forward-param.chpl)

**Comment by benharsh** [comment]
@ben-albrecht , @ian-bertolacci : Here's an issue for the forwarding bug encountered during the LayoutCS-sorted work.

**Comment by ian-bertolacci** [comment]
I'm not familiar with forwarding. Is this what is happening in LayoutCS.CSDom?

**Comment by benharsh** [comment]
Our internal implementation of arrays/domains/distributions will forward calls to the underlying class, which in your case was CSDom.

**Comment by ben-albrecht** [comment]
@ian-bertolacci - Check out [forwarding docs](https://chapel-lang.org/docs/master/technotes/forwarding.html) for additional info.
