### ISSUE TITLE
Figure out why arrays made with the extern domain don't get initial contents

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#9934]
### Summary of Problem
Valgrind complains about using uninitialized memory when using the following library code.  I want to determine the cause of that, so that we can give the array initial contents when appropriate.

### Steps to Reproduce

**Source Code:**

```chapel
export proc foo(arr: [] int): [arr.domain] int {
  var x: [arr.domain] int;  // Okay if given initial value
  return x;
}
```

**Compile command:**
`chpl --library foo.chpl -o libfoo`
`gcc `$CHPL_HOME/util/config/compileline --includes-and-defines` -o caller caller.test.c -L. -lfoo `$CHPL_HOME/util/config/compileline --libraries``

**Execution command:**
`valgrind --tool=memcheck -q ./caller`

**Associated Future Test(s):**
[`test/compflags/lydia/library/exportArray/returningArr/callFuncReturnsArrayTakesArrayArg3.test.c`](https://github.com/chapel-lang/chapel/blob/master/test/compflags/lydia/library/exportArray/returningArr/callFuncReturnsArrayTakesArrayArg3.test.c) #9931

### Configuration Information

- Output of `chpl --version`: 1.18.0 pre-release
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: fifo *
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: intrinsics
CHPL_GMP: gmp
CHPL_HWLOC: none
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none

**Comment by bradcray** [comment]
I think it's worth thinking about whether we can reuse code from DefaultRectangular to initialize this array in order to (a) avoid redundant code, and (b) get good NUMA first-touch behavior.

**Comment by lydia-duncan** [comment]
In the planning meeting, Brad also characterized this (accurately) as more about unifying the behavior with Default Rectangular, especially in this regard.
