### ISSUE TITLE
CHPL_HWLOC=system does not work in Ubuntu 18.04

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#9950]
I get an error like
```
ValueError: CHPL_HWLOC=system but unsupported version 1.11.9 was found.
Please use one of the following versions 1.11.5 1.11.6 1.11.7
```

This error was added in PR #6148 but I don't personally remember why we decided not to allow all the minor versions (for say 1.11).

Adding 1.11.9 to the version whitelist in util/chplenv/chpl_3p_hwloc_configs.py allows `make` and  `make check` to complete succesfully.

**Comment by ronawho** [comment]
We're on hwloc 1.11.10 (the latest 1.X version): https://github.com/chapel-lang/chapel/pull/8981

I think we can just add 1.11.8, 1.11.9, and 1.11.10 to the whitelist
