### ISSUE TITLE
Should casts to borrowed or unmanaged be allowed?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#9967]
Several test and module codes have a workaround to call _to_borrowed or _to_unmanaged on a type or on a value to get the corresponding borrow / unmanaged type.

Should it be allowed to write these as casts, where the RHS is theoretically generic, as in:
``` chapel
  type t = unmanaged MyClass;
  // This sort of thing usually comes up in a generic function
  t:unmanaged; // means use the unmanaged version aka unmanaged MyClass
  t:borrowed; // means use the borrowed version aka borrowed MyClass
```

This specifically relates to #9273.

**Comment by mppf** [comment]
I'm not so much trying to emphasize casting *the type* as much as casting to literally `unmanaged`.

Here is an alternative example:
``` chapel
class MyClass {
 var x: int;
}
class Container {
 var field;
}
proc Container.borrow() {
  return field:borrowed;
}
```

Here the point is that `field:borrowed` is casting to a generic type (in a manner) but I think it has clear meaning & makes such a pattern possible. Right now this (and the type version above) are both written with `_to_borrowed` or `_to_managed` (i.e. using a work-around strategy).

**Comment by psahabu** [comment]
Ah okay, seeing the use case I support this pattern.
