### ISSUE TITLE
"use only" prevents visibility of module deinit

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#9983]
### Steps to Reproduce
`error: unresolved call 'R(int(64)).deinit()` with `use A only`.
If `only` is omitted, the program compiles. Possibly related to #7857.

**Source Code:**

```chapel
module A {
  record R {
    type t;
  }
}

proc main() {
  use A only;
  var r: A.R(int);
}
```

### Configuration Information
`chpl version 1.18.0 pre-release (b0251ba45e)`

**Comment by lydia-duncan** [comment]
This is definitely the same cause as #7857.  Deinit counts as a method on the type, albeit one that is sometimes generated automatically.  I'll see if I can get to these issues shortly
