### ISSUE TITLE
Documentation bug: IO.openwriter is documented to return a reading channel

### ISSUE THREAD

**Issue by wasamasa** [chapel-lang/chapel#9993]
### Summary of Problem

https://chapel-lang.org/docs/modules/standard/IO.html#IO.openwriter
The documentation describes the return type in a short summary and a "Returns:" section. I expect both to state that a writing channel is returned. Instead they disagree, the short summary claims a writing channel is returned while the "Returns:" section mentions a reading channel. This is somewhat confusing, but it's obvious from the method name which one is correct.

**Comment by bradcray** [comment]
Thanks for pointing these out @wasamasa!
